### ISSUE TITLE
[MU4 Issue] Improve grace note slashes when straight flags are used

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#10016]
Leland:
![image](https://user-images.githubusercontent.com/20604032/145236374-5935f3fd-7e1f-4653-9af1-1ad405c51571.png)

Bravura:
![image](https://user-images.githubusercontent.com/20604032/145237478-2bb435cf-a843-4ddd-84e4-99cceb8fcc23.png)

We can't make assumptions about the shape of the flag glyphs in different fonts, but could either try to find a solution that works well for at least those fonts which even include them (which may be just these two?), or do something fancy using the bounding boxes of the glyphs themselves.

**Comment by Jojo-Schmitz** [comment]
These slashes seem to be longer on the flag side than on the notehead side, i.e. not centrered to the stem. This may be part of the issue or a separate one, and esp. in Leland and for notes in the space it leads to the slash touch the staff line, which I think should be avoided?

**Comment by Tantacrul** [comment]
After chat with @oktophonie, I'm bumping to 4.x. If we find we have capacity, we can do it in 4.0.
