### ISSUE TITLE
[MU4 Issue] Score position is too low when panning in note entry mode

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10012]
**Describe the bug**
Score panning during note entry mode currently places the active staff at the bottom of the screen (when multiple staves are involved). 

![MS4-pan-252-highest-staff](https://user-images.githubusercontent.com/86290556/145165619-489f034a-953f-4d74-8860-9c080597f0ff.gif)

**Expected behaviour**
Basically, it seems that the active staff (i.e. the one into which notes are being entered) should not fall too far below the y-axis centre of the score view window (although it seems behaviour for this is contingent on the number of staves and which staff is active). Fundamentally, panning in note entry mode should at the moment just replicate MS3.6 behaviour:
![MS3 6-pan-252-highest-staff](https://user-images.githubusercontent.com/86290556/145165408-b07b556c-6df1-49fb-b208-20ac7118e271.gif)

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Additional context**
Refers to #9923 
@cbjeukendrup

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10393

@bkunda Please check it briefly when you have time (to make sure I didn't miss anything)

Thanks!
