### ISSUE TITLE
[MU4 Issue] Commands with multiple keyboard shortcuts are represented as discrete commands

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10025]
**Describe the bug**
A number of commands that appear to contain multiple shortcut options are currently represented as discrete commands (I.e. appearing as duplicate commands across multiple rows):

The affected commands are:

- Change enharmonic spelling (both modes)
- Delete
- Fret # (TAB)
- Full screen
- Next lyric
- Remove selected range

Example:
<img width="874" alt="Screenshot 2021-12-09 at 8 18 41 pm" src="https://user-images.githubusercontent.com/86290556/145370392-dbadc35a-7b88-472d-9e68-1e60d87763f0.png">

Example:
<img width="877" alt="Screenshot 2021-12-09 at 8 19 17 pm" src="https://user-images.githubusercontent.com/86290556/145370411-c7eed958-2cd8-43e0-a1b8-ee9e8554a515.png">

**Expected behavior**
In MS3.6, multiple shortcuts are represented with a `;` separator:
<img width="487" alt="Screenshot 2021-12-09 at 8 25 16 pm" src="https://user-images.githubusercontent.com/86290556/145370544-7ca55d72-b09c-4f65-9bcd-a2ddce39a941.png">

It seems that MS4 uses a regular comma `,`. In either case, these commands should not appear over two separate rows, but should only take one row, with all options for keyboard shortcuts represented against the single command and separated by either `;` or `,`.

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10073

**Comment by DmitryArefiev** [comment]
Hello @bkunda , can you check this on Mac/Win on your side please? (should be in master already)

Thanks!

**Comment by bkunda** [comment]
Tested in MacOS and Windows - FIXED
