### ISSUE TITLE
[MU4 Issue] Palette tooltips don't consistently clear when dragging tiles: persist over main window (MacOS)

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10026]
**Describe the bug**
Dragging a palette tile with a tooltip visible sees the tooltip container persist over the main window.

![palette_tooltips_problem](https://user-images.githubusercontent.com/86290556/145378215-eb3b2e36-dc7d-46d4-96c9-f5c6873642e0.gif)

**Expected behavior**
Tooltip should disappear entirely when dragging palette tiles.

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Not reproducible in Windows

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check PR https://github.com/musescore/MuseScore/pull/10029

**Comment by DmitryArefiev** [comment]
Tested #10026 on Mac12 - FIXED      

Please merge into master
