### ISSUE TITLE
[MU4 Issue] Tablature staves have weird beam/stem placement

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10023]
**Describe the bug**
Tablature staves (TABS) have wierd beam/stem placement

![beams on tab](https://user-images.githubusercontent.com/90187801/145294302-dafa31d3-08e2-4d10-9fe8-645489bff1cf.PNG)

**Desktop:**
Win/Mac/Lin

**Comment by oktophonie** [comment]
Another consequence of #9792 - fix coming!

**Comment by RobFog** [comment]
"wierd" → weird
