### ISSUE TITLE
[MU4 Issue] Using "Add" to define a shortcut places new definition after an "empty" one

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10024]
**Describe the bug**
This issue was mentioned in the comments to #8898.

> ...if you use "Add" when defining a sequence and there's not a sequence already defined, the sequence ends up being defined as, for instance `, Ctrl+Alt+E` (with the leading comma), which Qt doesn't like (causes asserts and even crashes in the debug version anyway). 

![shortcut-add-issue](https://user-images.githubusercontent.com/86290556/145362216-099fd861-d5e0-4ea3-ac10-0e84b16d4b5c.gif)

**Expected behavior**
When using "Add" to define a shortcut for a command that has no shortcut, the sequence should not be preceded by an "empty" shortcut space (i.e. ` ,`). Instead, it should appear as it currently does when using the "Replace" function (see demo above).

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 10

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10073

**Comment by DmitryArefiev** [comment]
Hello @bkunda , can you check this on Mac/Win on your side please? (should be in master already)

Thanks!
