### ISSUE TITLE
[MU4 Issue] Custom instrument order reverted to Orchestral when opening the Instruments panel

### ISSUE THREAD

**Issue by Howard-C** [musescore/MuseScore#10038]
**Describe the bug**
Custom instrument order reverted to Orchestral when opening the Instruments panel.

**To Reproduce**
1. Create a score and add two instruments, for example a woodwind, say, alto saxophone, and a brass, say, cornet. Now cornet should be below alto saxophone by default.
2. Move cornet above alto saxophone. The instrument order type is changed to Custom. Then close the Instruments panel.
3. Reopen the Instruments panel, and see that the instrument order type is now displayed as Orchestral, but the order itself didn't change.
4. Add a new instrument, for example a string, say, contrabass. Cornet and alto saxophone are then reordered.

**Expected behavior**
The order type should not be reverted to Orchestral, and the instruments should not be reordered when adding new instruments if the type was set to Custom.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10345
