### ISSUE TITLE
[MU4 Issue] Instruments panel shows incorrect staff type

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#10037]
**Describe the bug**

When viewing the details for a given staff, the staff type will always be shown as "standard" even if it's a tablature staff.

https://user-images.githubusercontent.com/5659171/145519850-1a810f0c-f429-488b-a191-18cc95434de9.mov

**Expected behavior**

The staff type should be pre-populated with the current staff type.

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1, Apple Silicon

**Comment by Howard-C** [comment]
When I add an instrument with tablature staff, it is shown as standard. I'll have to manually switch it to tablature. Same goes for other staff types.

**Comment by Nick-Mazuk** [comment]
> When I add an instrument with tablature staff, it is shown as standard. I'll have to manually switch it to tablature. Same goes for other staff types.

Is this what you're referring to: https://github.com/musescore/MuseScore/issues/10036?

**Comment by Howard-C** [comment]
Ah, yes you're right :)

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/9622
