### ISSUE TITLE
[MU4 Issue] Arrow keys on tab staves behave unexpectedly

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#10035]
**Describe the bug**

When navigating a tab staff in edit mode using the up/down arrow keys, lines are skipped.

https://user-images.githubusercontent.com/5659171/145519219-812817ba-eb96-4493-9aad-9215650d076d.mov

Notice how when using the vertical arrow keys, lines are skipped.

**Expected behavior**

I'm not familiar enough with tab staves to know what the desired behavior is. However, my expectation is that the arrow keys would be able to select every line, not skip them.

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1, Apple Silicon

**Comment by Tantacrul** [comment]
I've tested this in the latest version and it is no longer happening (thankfully!)

@boryskuzmenko, can you confirm?

Closing for now.

**Comment by boryskuzmenko** [comment]
Confirmed. This issue can't be reproduced.
