### ISSUE TITLE
[MU4 Issue] Settings in Styles dialog override changes to Instrument Name text made in properties panel

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10033]
**Describe the bug**
This is another variant of case from #9837

https://user-images.githubusercontent.com/90187801/145440928-dcbf8e2b-e4c3-4b42-98d0-4b188af92e94.mp4

**Desktop:**
Win/Mac/Lin

**Additional context**
Changing Instrument name text properties from Properties is complex issue and requires a refactoring work.

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/pull/10734
