### ISSUE TITLE
[MU4 Issue] Tabbed instruments do not have tab staffs when added

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#10036]
**Describe the bug**

When you add the tablature variant of an instrument, the added staff is not a tab staff. I've seen this behavior both with creating a new score and adding instruments to an existing score.

https://user-images.githubusercontent.com/5659171/145519541-9d696de9-1364-4e61-a2b7-d1630cfddacb.mov

**Expected behavior**

If you select the tablature variant of an instrument, the added staff should already be a tab staff.

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1, Apple Silicon

**Comment by bkunda** [comment]
This is critical for creating tab scores

**Comment by igorkorsukov** [comment]
I believe this will be fixed after the merge of this PR https://github.com/musescore/MuseScore/pull/9982
@DmitryArefiev FYI

**Comment by bkunda** [comment]
Ah yes, it seems like it is 👍🏻

**Comment by DmitryArefiev** [comment]
Tested on master build (Win10, Mac11, LinuxMint 20) - FIXED

**Comment by DmitryArefiev** [comment]
@bkunda Can you check this in master build please? To make sure I didn't miss anything ;)

**Comment by Nick-Mazuk** [comment]
Looks fixed to me

**Comment by DmitryArefiev** [comment]
Thanks!

**Comment by bkunda** [comment]
Ditto from me.
