### ISSUE TITLE
[Installer] MU4 installer should not contain "3"  and License Agreement should be updated (Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10043]
1. MU4 installer should not contain 3 (from previous version)

![01](https://user-images.githubusercontent.com/90187801/145563747-7eb9cd2e-16de-41b0-8f79-1ab1980d3e64.PNG)

2. End-User License Agreement should be updated 

![LA](https://user-images.githubusercontent.com/90187801/145565213-30ab76f0-fc5f-440b-b39b-ef5f0ee38467.PNG)

**Comment by Jojo-Schmitz** [comment]
The bogus 3 is in [.../build/packaging/installer_background_wix.png](https://github.com/musescore/MuseScore/blob/master/build/packaging/installer_background_wix.png)
The outdated copyright year in [.../LICENSE.rtf](https://github.com/musescore/MuseScore/blob/master/LICENSE.rtf)

**Comment by cbjeukendrup** [comment]
For the 1st part: see also https://github.com/musescore/MuseScore/pull/7219, where I tried to implement the new images a long time ago, but we did not include them in the 3.6 release (as we had planned earlier) because we weren't sure whether it would work correctly and there were some problems that prevented us from testing it.

The new top banner would become this:
![](https://github.com/cbjeukendrup/MuseScore/raw/fb7244a585f0ffa3acfc4a266c5fae722634ee49/build/packaging/installer_banner_wix.png)

And the new background would become this:
![](https://github.com/cbjeukendrup/MuseScore/raw/fb7244a585f0ffa3acfc4a266c5fae722634ee49/build/packaging/installer_background_wix.png)

@jessjwilliamson Are you still happy with these versions, or would you like to create updated ones by now?

**Comment by Jojo-Schmitz** [comment]
They are is twice as big as the ones they replace, does that matter?

**Comment by cbjeukendrup** [comment]
That was one of the things we were not sure about. I'm afraid it will; for macOS it did (but for macOS it works completely different). I think we just need to change the DPI from 72 to 144, and then it should work (for macOS that was the solution).

**Comment by jessjwilliamson** [comment]
> For the 1st part: see also #7219, where I tried to implement the new images a long time ago, but we did not include them in the 3.6 release (as we had planned earlier) because we weren't sure whether it would work correctly and there were some problems that prevented us from testing it.
> 
> The new top banner would become this: ![](https://github.com/cbjeukendrup/MuseScore/raw/fb7244a585f0ffa3acfc4a266c5fae722634ee49/build/packaging/installer_banner_wix.png)
> 
> And the new background would become this: ![](https://github.com/cbjeukendrup/MuseScore/raw/fb7244a585f0ffa3acfc4a266c5fae722634ee49/build/packaging/installer_background_wix.png)
> 
> @jessjwilliamson Are you still happy with these versions, or would you like to create updated ones by now?

For now this is fine :)

**Comment by Jojo-Schmitz** [comment]
Added to #10044, see https://github.com/musescore/MuseScore/pull/10044/commits/cb89106047baf503f307d0537ba47fb59b827870

**Comment by cbjeukendrup** [comment]
Hm, that version looks blurry on my High Dpi screen. 
In these ones, I only doubled the DPI but kept the same number of pixels. I think you should use this instead:
<img width="493" alt="installer_banner_wix" src="https://user-images.githubusercontent.com/48658420/145602274-182e920d-69bf-41c1-b000-85dcbdc8c7a8.png">
<img width="493" alt="installer_background_wix" src="https://user-images.githubusercontent.com/48658420/145602315-092d87bf-5456-4e23-a589-6a01a4959eef.png">

**Comment by Jojo-Schmitz** [comment]
They are double the size

**Comment by Jojo-Schmitz** [comment]
What the heck, let's try it. Next installer build would show.

**Comment by cbjeukendrup** [comment]
Yes, the number of pixels is twice as big, but the DPI (which GitHub Desktop apparently does not take into account) too, so the physical size _should_ be the same. But maybe the windows installer also does not take the DPI into account, in which case I guess the only option is to disappoint high-dpi screen users... 
We'll see!

**Comment by Jojo-Schmitz** [comment]
on HighDPI screens too?

**Comment by cbjeukendrup** [comment]
On my M1 Mac with Windows in Parallels, and with a high-dpi screen, it looks perfect!

**Comment by Jojo-Schmitz** [comment]
Great!
