### ISSUE TITLE
[Installer] MU4 installer should not uninstall MU3 (Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10042]
**To Reproduce**
1. Install MU3
2. Install MU4 (notice MU4 doesn't have any option (checkbox) which proposes to uninstall MU3)
3. Check c:\Program Files\MuseScore 3\ - **MU3 is uninstalled**

https://user-images.githubusercontent.com/90187801/145562471-8bd6ce59-de31-485d-9773-fa939261efd5.mp4

**Comment by Jojo-Schmitz** [comment]
Also note that big "3" in the setup wizare, should be a "4"

**Comment by Jojo-Schmitz** [comment]
Wouldn't MuseScore 4 just need a new UUID for not overwriting MuseScore 4?

**Comment by DmitryArefiev** [comment]
> Also note that big "3" in the setup wizare, should be a "4"
Yes, noticed that too. Will log it separately.

Thanks!

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check (need to build a master)

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev Please check (need to build a master)

Tested on latest master build, Win10 - FIXED

Closing
