### ISSUE TITLE
[MU4 Issue] Separator lines in note input bar are too tall

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#10045]
![image](https://user-images.githubusercontent.com/71656189/145569595-3a5c367e-9406-422f-a359-2468b0eb3f27.png)

**Comment by jessjwilliamson** [comment]
@cbjeukendrup

**Comment by cbjeukendrup** [comment]
The cause of this problem is that the note input bar is still 36px tall instead of 40, which I was fixing in PR #9872 (but there were some review issues in that PR that I need to resolve).
