### ISSUE TITLE
[MU4 Issue] Bracket might automatically extend to the next instrument

### ISSUE THREAD

**Issue by Howard-C** [musescore/MuseScore#10040]
**Describe the bug**
Bracket might automatically extend to the next instrument.

**To Reproduce**
1. Create a score and add instruments that include at least a multi-stave instrument followed by another instrument, in this case, two pianos followed by a violin.
2. Delete the last stave of every multi-stave instrument. The brackets don't disappear, nor are they shortened, but instead stay where they were, extending to adjacent instruments.

**Expected behavior**
The brackets should disappear, or be shortened to only cover the right instruments. I'd prefer the former for one-stave instruments, BTW.

**Screenshots**
![image](https://user-images.githubusercontent.com/46259489/145523311-907e00a5-0fe1-44de-997e-6d0098dbdb08.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by mattblo** [comment]
related to #9210

**Comment by njvdberg** [comment]
Is indeed the same bug and it's on my list,

**Comment by njvdberg** [comment]
By the way, MU3 has the same problem.
Nevertheless, I'm looking for a solution.

**Comment by njvdberg** [comment]
Unfortunately, this isn't solved by the PR solving #9210. Will be solved with dedicated PR.

**Comment by Tantacrul** [comment]
I'm adding this to target Beta 1 (based on comments on the related PR). That should give enough time!
