### ISSUE TITLE
[MU4 Issue] When create a new score, changing note duration in Tempo mark does not apply (Additional Score Information)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10054]
![01](https://user-images.githubusercontent.com/90187801/145616943-4b2aec1e-bcba-4dcf-8a00-15edad9c708b.PNG)

https://user-images.githubusercontent.com/90187801/145616984-c98a6e0b-d11e-44e2-81fb-88d8e773eed0.mp4

**Desktop:**
 - OS: doesn't depend

**Additional context**
This feature is absent in MU3, so it requires additional implementation in MU4

**Comment by HemantAntony** [comment]
I'm working on this. PR will be coming soon
