### ISSUE TITLE
[MU4 Issue] New Score> Additional Score Info: Title, Subtitle and Composer fields should select after one mouse click (Improvement)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10076]
**Describe the bug**
After #9186, we have auto filled Title, Subtitle and Composer with default text. 

![01](https://user-images.githubusercontent.com/90187801/145817721-2034b843-82fd-43c8-a575-a1c55ae0fb2e.PNG)

But when user wants to change them with a different text he needs to erase them at first. 
On **Win, Linux**, after you click with mouse the value selects and deselects for a moment which is strange and not convenient.
We should give to user a **quick way** to fill out Title, Subtitle and Composer with his own text

https://user-images.githubusercontent.com/90187801/145818305-b6e2ad76-0be7-46de-8990-b0a6ba6ec22e.mp4

**Comment by HemantAntony** [comment]
Hey, when you edit Title, Composer, Subtitle, there is already text there. But, I was thinking if the "text" in it, could be like Lyricist and Copyright. So something like this:

https://user-images.githubusercontent.com/88136054/147342500-88eaa774-c491-42a3-9518-e583e925f4a1.mp4

**Comment by Howard-C** [comment]
@HemantAntony I agree with this solution. Does this mean you already implemented the fix?

**Comment by HemantAntony** [comment]
I can have the fix ready with a couple of hours. So, the text would be like this:
1. Title: Name of the Score
2. Composer: Name of the Composer
3. Subtitle: Subtitle
4. Lyricist: Name of the Lyricist
5. Copyright: Copyright
Got any suggestions for the text?

**Comment by Howard-C** [comment]
Now that I think about it, I find these texts to be completely redundant… Are they really necessary? Aren't "Title", "Composer", "Subtitle", "Lyricist", "Copyright" already self-explanatory?

**Comment by HemantAntony** [comment]
Yeah I was thinking about that too. We already know what it is. So just remove the text and keep it blank?

**Comment by Howard-C** [comment]
The only good thing about the original implementation, I think, is the "Untitled Score" default value for the "Title" field. Maybe we can keep that and put it the same way as the "Optional" texts, but I really don't find the rest of the texts useful.

**Comment by HemantAntony** [comment]
Okay, so I will grey out "Untitled Score" and remove all the other text

**Comment by Howard-C** [comment]
This is only my opinion, others might disagree

**Comment by DmitryArefiev** [comment]
Hi @HemantAntony , Checked on Windows. It looks good and the initial bug is fixed. Thanks! 
But **Composer** and **Subtitle** fields should not be empty. That was by design.. Could you return that back please for now?

![Capture](https://user-images.githubusercontent.com/90187801/147503249-36d6d21a-182f-470e-a2c2-fdcec70d68c4.PNG)

**Comment by DmitryArefiev** [comment]
@HemantAntony Thanks for fixing that! All good now! 

Tested on Win10, Mac12, LinuxMint 20.2 - PASS
