### ISSUE TITLE
[MU4 Issue] Application crash when changing "Text Style" for any text object.

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#10083]
**Describe the bug**
Trying to select a different text-style for any text object causes MuseScore to crash.

**To Reproduce**
1. Create a new score
2. Add any sort of text (e.g. a title, dynamic etc.)
3. In the inspector click "More"
4. From the "Text style" drop-down choose another option
5. MuseScore crashes

**Expected behavior**
Not a crash

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
The crash is because the inspector is trying to set the SUB_STYLE property to be a string, but it's actually meant to be an integer.

Crash at propertyvalue.h, line 311

at was nullptr

>	MuseScore4.exe!mu::engraving::PropertyValue::value<int>() Line 311	C++
 	MuseScore4.exe!mu::engraving::PropertyValue::operator==(const mu::engraving::PropertyValue & v) Line 75	C++
 	MuseScore4.exe!Ms::EngravingObject::undoChangeProperty(Ms::Pid id, const mu::engraving::PropertyValue & v, Ms::PropertyFlags ps) Line 424	C++
 	MuseScore4.exe!Ms::TextBase::undoChangeProperty(Ms::Pid id, const mu::engraving::PropertyValue & v, Ms::PropertyFlags ps) Line 3670	C++
...

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10086
