### ISSUE TITLE
Shortcut description for ties is incorrect

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10090]
**Describe the bug**
When hovering over a tie, the shortcut is described as '+'. However, the currently working shortcut is '**Shift**' + '**+**'

![image](https://user-images.githubusercontent.com/21022311/146014969-782253c7-c037-43f4-a8cc-b5057a5cc888.png)

**Comment by Tantacrul** [comment]
'+' is currently used to enable/disable automatic placement, btw.

I actually think that these should be swapped around.

**Comment by RobFog** [comment]
Might this be a [good first issue](https://github.com/musescore/MuseScore/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)?

**Comment by Tantacrul** [comment]
Yep

**Comment by Jojo-Schmitz** [comment]
I'd rather have them swapped too, a tie is needed much more often than toggling autoplace and as such should have less key strokes in its shortcut. Also 'finger-brain' from 3.x is asking for + to tie

**Comment by Tantacrul** [comment]
Let's just do it then. It is such an obvious improvement. @Jojo-Schmitz - you want it?

**Comment by Jojo-Schmitz** [comment]
I'm confused, the shortcut for "toggle-autoplace" is `=`, not `+`, in all 3 shortcut xml files (shortcuts_Mac.xml, shortcuts.xml and shortcuts_AZERTY.xml) and the shortcut for "tie" is `+` already.

**Comment by Jojo-Schmitz** [comment]
I see though that on a US keyboard you need `Shift` to get to the `+` (unless you use the keypad). Not the case on a German QWERTZ keyboard though. And no reason to show "`Shift`+`+`" in the menu, we never did that.

**Comment by Jojo-Schmitz** [comment]
And `=` is indeed the unshifted `+` on an US keyboard. It is "`Shift`+`0`" though on a German QWERTZ.

So this issue here really is none!

**Comment by Tantacrul** [comment]
Oh, man. Yes. I just realised. It is '=' for Autoplace. My mistake.

Hmm. I wonder whether it wouldn't be clearer to label the shortcut "Shift+=", rather than '+' ? 

Also, should we still swap them? 

- Autoplace (+)
- Tie (=)

**Comment by Jojo-Schmitz** [comment]
I'm against adding the "Shift+" to the display, that won't work for German Keyboards (and be a `*` there).
I'm against swapping those, at least for German Keyboards ;-), but also, due to 'finger-memory' for all others too

The '£' is different, it is not available on any keyboards except a British one, and as such should not get used as a shortcut at all

**Comment by Tantacrul** [comment]
This is my point. It should be Alt + 3 (which produces '£'). It makes sense to always show the modifier and the default key, not the result of the combination of those two things.

Another example: specifying '?' as a shortcut. That's really weird.

It should be 'SHIFT' + '/'

**Comment by Jojo-Schmitz** [comment]
Well `?` would be `Shift`+`ß` here. and `/` is `Shift`+`7`
Showing the modified doesn't make sense, if the shortcut is `+` and you need `Shift` to get a '+`, so be it. As said here `Shift`+`+` gives `*`

**Comment by Tantacrul** [comment]
Nah. Most applications do this. There are some technicalities to iron out, but specifying that the shortcut for a tie is '+' is ridiculous. Showing the modifier makes it clear how to achieve the shortcut. The problem you are discussing is a problem regardless of the system we choose.

Even in the shortcut definition screen we don't do that:
![image](https://user-images.githubusercontent.com/21022311/146034865-36a13f52-4d21-437a-977c-947015e4a45f.png)

Neither do other applications.

Here's Adobe:
![image](https://user-images.githubusercontent.com/21022311/146035577-4efb5365-ea0c-4a5c-93a6-9d2cd2c949fc.png)

Here's Dorico:
![image](https://user-images.githubusercontent.com/21022311/146035631-8cf6cebb-4483-463a-b7e4-34ee4507c26a.png)

**Comment by Tantacrul** [comment]
Anyway, this has turned into a much wider, general issue. I'm going to close this bug.
