### ISSUE TITLE
[MU4 Issue] Crash when adding a trill line object to a selected range

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10099]
**Describe the bug**
MuseScore crashes when adding any one of these objects to a selected range:

<img width="515" alt="Screenshot 2021-12-15 at 10 34 19 pm" src="https://user-images.githubusercontent.com/86290556/146179377-e1a6afd7-4dd2-4e1b-86c4-7c93af1aeb1e.png">

**Demo**

![crash-trill-selected-bar](https://user-images.githubusercontent.com/86290556/146179397-66b669c5-6f21-4793-a370-02544f264d06.gif)

**Expected behavior**
MuseScore should not crash. Object should apply to length of entire selection (as per MS3.6).

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10111

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
