### ISSUE TITLE
[MU4 Issue] Selecting and then holding Ctrl and dragging crashes MuseScore (Debug builds with asserts enabled)

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#10100]
**Describe the bug**
When you click and drag a note, a crash occurs

**To Reproduce**
1. Create a new score with instruments
2. Add notes
3. Select a note
4. Then hold Ctrl
5. Now, drag the note
6. Crash occurs

**Expected behavior**
MuseScore is not supposed to crash

**Screenshots**

https://user-images.githubusercontent.com/88136054/147527497-c87e1370-cff2-4094-a105-14775eb07bd3.mp4

https://user-images.githubusercontent.com/88136054/146532305-732f329d-bf3c-4f31-aaa8-6ec43d810086.mp4
(In this video, I tell you the steps I am following in case you can't reproduce)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional Context**
The original issue was edited significantly. So, some of the comments below may not make sense. If you want to understand the context, you can look at the original issue by clicking on the edited dropdown in this comment's header

**Comment by wizofaus** [comment]
Can't reproduce, but it looks like you were running this under the debugger, can you provide the stack trace and/or complete log?

**Comment by HemantAntony** [comment]
I don't know what stack trace is (I am a bit new). This is the log when I click on it the second time:
![image](https://user-images.githubusercontent.com/88136054/146490214-569c2a0e-1e91-4c0b-bd22-e95a85111ecc.png)
I have also asked @DmitryArefiev if he could reproduce this issue

**Comment by DmitryArefiev** [comment]
Hi @HemantAntony I tried on Windows10/Windows11/Mac12 - I can't reproduce it with your steps but found a way how to crash MU with one additional step:

1. Create a new score with instruments
2. Add notes
3. Click and drag a note
4. Click and drag a note again
5. **Press and hold Ctr+Z**

@wizofaus Can you try these steps on your side please?

**Comment by HemantAntony** [comment]
I'm going to edit this issue a bit. It turns out I was doing something extra the second time. So the way to produce the current issue:

https://user-images.githubusercontent.com/88136054/146532292-8eaf0787-e9c9-4298-b5ad-b86db38c32f9.mp4


https://user-images.githubusercontent.com/88136054/146532305-732f329d-bf3c-4f31-aaa8-6ec43d810086.mp4

The second video is the shorter way to reproduce the crash. Basically I am doing the same things in the second video, the second time in the first video. So I will be editing this issue

**Comment by DmitryArefiev** [comment]
@HemantAntony That strange.. I still can't reproduce it on my side even using Ctr+click

**Comment by DmitryArefiev** [comment]
I can get crash only when Undoing all action (after you steps) but it has rare reproducibility

**Comment by HemantAntony** [comment]
I don't think it has a rare reproducibility. It has gotten produced every single time

**Comment by DmitryArefiev** [comment]
I mean it has rare reproducibility on my side (with adding Undo command after all steps).
Using the initial steps I still can't reproduce unfortunately..

Did you try on the latest master build and without debugger running on the background?

**Comment by HemantAntony** [comment]
I can reproduce your undo crash. But that seems to be another problem

**Comment by HemantAntony** [comment]
What I am doing is 
1. Clicking on a note (You have to do this first)
2. Holding Ctrl
3. Then drag (holding Ctrl at the same time)

I will make another video where you can see my keyboard if you still can't reproduce. But this is definitely an issue.

But I think you have to follow the instructions in this message strictly

**Comment by HemantAntony** [comment]
https://user-images.githubusercontent.com/88136054/146539578-1b85a339-80d8-4fb6-aeb4-07c499698ef2.mp4

This video shows my keyboard too. Hope you can see exactly what I am doing. Also, yes I am running the latest master build

**Comment by cbjeukendrup** [comment]
Reproduced it! Both Mac and Win.
So, you basically just need to select one note, then press the Ctrl/Cmd key down and drag the selected note while keeping the Ctrl/Cmd key pressed. 

I think the reason for the crash is the following: the mouse press event with the Ctrl/Cmd key pressed causes the note to be deselected, so nothing is selected anymore. Still, the drag event, that follows after the press event, is handled as if there was a selection, which causes an assertion failure.

**Comment by DmitryArefiev** [comment]
That's really weird.. I still can't reproduce it (Win/Mac)

I'm doing exactly what video shows (press the Ctrl/Cmd key down and drag the selected note while keeping the Ctrl/Cmd key pressed) but still can get a crash..

https://user-images.githubusercontent.com/90187801/146548853-0bb5684a-561b-45cd-800c-d10d08795823.mp4

**Comment by HemantAntony** [comment]
Try following these instructions exactly. Don't assume anything. Do it like a robot:
1. Select a note (It has to remain selected). You have to release the click. So, one full click.
2. Hold, but obviously, do not release Ctrl.
3. Click on the same note, but don't release. Do a half click. Just drag.
4. Crash occurs

**Comment by cbjeukendrup** [comment]
Oh - one more thing: make sure that you have a Debug build, with asserts enabled. So, for example, a build from a PR or a self-built version. I believe Nightlies are built in Release mode, so they have asserts disabled. As said, this crash is an assertion failure, so that really matters in this case.

**Comment by DmitryArefiev** [comment]
Thanks! I've tried on master builds/PR builds but with asserts disabled.

I will change summary

**Comment by wizofaus** [comment]
Yeah it seems to need to be a FULL debug build (even RelWithDebInfo won't cut it).
I can see that that IF_ASSERT_FAILED is occurring in NotationViewInputController::startDragElements( ) if you hold down CTRL then try to drag a note that was already selected.
As it happens this assert failure seems to be harmless enough and there's no reason to believe it will cause an issue in release builds.

BUT...perhaps a the bigger issue is that Ctrl+mouse *down* deselects (as does V3), whereas if you check the behaviour of many other software applications, it's ctrl+mouse *up* that deselects, and only when you haven't dragged in the meantime.  If you have dragged while ctrl was down, it typically indicates the object should drag in some different manner - again, for many other software applications it's "copy & drag", but MuseScore (both v3 & v4) it's "restrict to horizontal dragging only".  So if I have a note selected and then I *want* to start dragging it restricting to horizontal movement, logically I should be able to hold down CTRL, click on it and start dragging.  But this doesn't work in v3 either - the initial mousedown deselects the note, and dragging after that does nothing. The only thing that *does* work is pressing and holding the mouse down on the note *then* pressing CTRL*, then dragging.

So I think there's a usability decision here, and once that's made it will allow us to ensure the assert doesn't occur (for those running debug builds).

**Comment by HemantAntony** [comment]
> As it happens this assert failure seems to be harmless enough and there's no reason to believe it will cause an issue in release builds.

So should I close this issue?

**Comment by wizofaus** [comment]
No, I think there's a definite usability issue and asserts in debug builds are still annoying for developers running them!  Also would like to get to the bottom of the undo crash.

**Comment by HemantAntony** [comment]
Were you able to reproduce the undo crash?

**Comment by wizofaus** [comment]
No luck there, tried all sorts of things.  I've certain seen undo trigger crashes in the past, so it's quite possibly unrelated anyway.  Would just like to know for sure, and the code around selecting/dragging is something I did a lot of work on recently so it's not unlikely to be my fault if it crashes!

**Comment by HemantAntony** [comment]
The funny thing is that I was able to reproduce the undo crash intially. But after seeing your previous message, I tried to reproduce it again, but couldn't

**Comment by Tantacrul** [comment]
I can reproduce this on Mac by holding the CMD button and dragging a note.

**Comment by HemantAntony** [comment]
> I can reproduce this on Mac by holding the CMD button and dragging a note.

Wait, how's that possible? You should not be able to reproduce that. How did you "build" MU4? Did you download it as a nightly or did you build it from the source code? I think you would have done the former

Unless you built MuseScore from the source code with Debug mode switched on, you should not be able to reproduce this

**Comment by Tantacrul** [comment]
Via a nightly, yes. I'll try again later today. Didn't test extensively.

**Comment by wizofaus** [comment]
The problem still exists - if you select a note first, then hold down CTRL and start dragging that note, the note gets deselected, which I'd argue is the wrong behaviour, and in actual local Debug builds there is an Assert that fires.  Really it should be mouse-up that deselects.
