### ISSUE TITLE
[MU4 Issue] Chord symbols are recognized (parsed) properly only in a just created scores 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10103]
**To Reproduce**
1. Create a score
2. Add some notes
3. Save and close
4. Reopen
5. Select note and enter chord input mode
6. Type **am7** and hit Space - you see **m7** instead of Am7 

https://user-images.githubusercontent.com/90187801/146188507-31649f9d-ee89-439c-a47f-7f195b636184.mp4

**Expected behavior**

**Screenshots**

**Desktop:**
 - OS: all

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
