### ISSUE TITLE
[MU4 Issue] Menus getting cleared and filled repeatedly

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#10105]
**Describe the bug**
File Menu is getting cleared and filled repeatedly (Just watch the video)

**To Reproduce**
1. Click on File
2. The bug occurs

**Expected behavior**
The File menu is supposed to remain still

**Screenshots**

https://user-images.githubusercontent.com/88136054/146197674-cd4f27bf-ae59-4377-b256-a3a820e9bc30.mp4

https://user-images.githubusercontent.com/88136054/146197658-a2f5a404-bfd6-4e30-8a6b-6bc4e476ca2d.mp4

The videos are not that good. If you are lucky, you might be able to see it blink a couple times more.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I don't have a good issue name. Its at least better than the original: Menus are having a seizure

**Comment by DmitryArefiev** [comment]
Thanks for logging this!

**Comment by Eism** [comment]
@HemantAntony hey!
I cannot reproduce on Windows/Linux

Сan you provide more information on how to reproduce the bug?
Is the bug reproducible in the nightly build?
Do you reproduce stably or does it happen randomly?

**Comment by DmitryArefiev** [comment]
@Eism @HemantAntony I found that the bug doesn't occur on the the first score (after MU launch) you need to create a second one using shortcut when open New Score Wizard:



https://user-images.githubusercontent.com/90187801/146353590-aa9f1ac2-9540-474c-a4b4-40e68b09a769.mp4

**Comment by HemantAntony** [comment]
It still occurs even though I updated the code to the latest nightly. There really isn't much information to provide. But after reading Dmitry's message, it just got weirder because this happens for me in the first score itself. I don't need to create the second score

**Comment by HemantAntony** [comment]
@Eism, I created a video with audio explaining how I am reproducing this bug:

https://user-images.githubusercontent.com/88136054/146354709-f2932248-b99d-4c91-b9d7-589e74a56334.mp4


Also, the bug did appear a little the first time @DmitryArefiev did it. You can see the File blink 2 or 3 times

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10124

At this point, the problem will not appear. But there was a technical problem with the app menu itself, I added a technical task https://github.com/musescore/MuseScore/issues/10125

**Comment by DmitryArefiev** [comment]
Tested  on Win10, Mac12, LinuxMint 20.2 - FIXED
