### ISSUE TITLE
[MU4 Issue] Several Properties buttons are missing icons

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10109]
**Describe the bug**
There are a couple of parts to this issue:

1. The following buttons in **Properties** are missing icons from `musescoreicon`.

- Volta (should be f410)
- Vibrato (should be f411)
- Let ring (should be f40f)
- Ottava (should be f40d)
- Palm mute (should be f40e)

<img width="298" alt="Screenshot 2021-12-16 at 5 11 29 pm" src="https://user-images.githubusercontent.com/86290556/146317882-3720b8d0-92f4-46e2-896a-b5fee152f9f8.png">

2. Tuplets currently contain the incorrect icon

<img width="136" alt="Screenshot 2021-12-16 at 5 32 24 pm" src="https://user-images.githubusercontent.com/86290556/146320149-13c34684-311d-4e48-b5e0-6d50e6cd2e5d.png">

This should be f422, as per @Tantacrul's design spec:
 
<img width="283" alt="Screenshot 2021-12-16 at 5 33 27 pm" src="https://user-images.githubusercontent.com/86290556/146320221-34e2d45a-f6db-49bc-ac21-e920c8d5d1da.png">

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by HemantAntony** [comment]
Is it ok if I work on this?

**Comment by Tantacrul** [comment]
> Is it ok if I work on this? Its probably an easy fix

Please!

**Comment by HemantAntony** [comment]
I can't seem to find this panel even though I managed to fix it. Can you tell me where it is? Its in the properties, right? So, which element do I need to click on to see this?

**Comment by Eism** [comment]
Yes, it is Properties panel.

You should select multiple elements(volta, hairpin, ottava, etc) by pressing Ctrl. Then the Notation section will appear

**Comment by cbjeukendrup** [comment]
These are the elements in question: 
<img width="644" alt="Schermafbeelding 2021-12-16 om 11 04 49" src="https://user-images.githubusercontent.com/48658420/146351089-4286aecf-6c2f-42ab-b2b9-8a2c37bab026.png">
Indeed, as Elnur says, if you add them all to the score, and then select them all by Ctrl+Clicking, you will see these buttons in the Properties panel.

**Comment by HemantAntony** [comment]
Thank you! I managed to find the buttons. I could not add the Ottava initially. I searched google for "Ottawa" and Canadian things started popping up. Finally, I did figure it out.

**Comment by DmitryArefiev** [comment]
Hi @bkunda can you check it on your side please (Win/Mac)?

Thanks!

**Comment by bkunda** [comment]
Tested on Windows and MacOS. FIXED.
I believe another icon is on the way (via @cbjeukendrup) for measure repeats. 
Great work and thank you @HemantAntony!

**Comment by DmitryArefiev** [comment]
@bkunda Thanks! I've tested on Linux. Here is a screenshot:

![Screenshot from 2021-12-17 16-02-46](https://user-images.githubusercontent.com/90187801/146542294-a28b6245-bef8-4f7c-a819-027c51206bf3.png)

**Comment by bkunda** [comment]
It looks so lovely 😍

**Comment by DmitryArefiev** [comment]
Cool! Then we can merge it!
