### ISSUE TITLE
[MU4 Issue] Project name does not update on save

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#10102]
**Describe the bug**
When you save a project, the project name does not update.

**To Reproduce**
1. Create a score and add notes
2. Save the Score
3. The name of the project does not get updated (Look in the tab "untitled")

**Expected behavior**
Project name should be updated on saving the score

**Screenshots**

https://user-images.githubusercontent.com/88136054/146185959-c9bec876-23d4-423e-b15d-91b578d6bd6e.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by HemantAntony** [comment]
Mind if I take a crack at this?

**Comment by DmitryArefiev** [comment]
Tested  on master build (Win10, Mac11, LinuxMint 20) - FIXED
