### ISSUE TITLE
[MU4 Issue] Instrument name does not update in parts dialog and its tab on replace

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#10122]
(Updated by @Tantacrul, @DmitryArefiev )
**Describe the bug**
When opening some older scores, the 'Replace Instrument' feature does not work. However, it **does** work for new scores.

BUG№1 - **FIXED** in #13097
To Reproduce:
1. Open  [string quartet 2.zip](https://github.com/musescore/MuseScore/files/9594429/string.quartet.2.zip)
2. Open Violin I part
3. Go to score and replace the Violin I with another instrument, like a Flute, using the Instruments panel
4. Observe that the **instrument label in score/mixer** and **sounds do not update**.

https://user-images.githubusercontent.com/90187801/190918230-036284c9-7ec6-4971-9e1f-ade697bb5a60.mp4

BUG№2 (**STILL OCCURS**)
To Reproduce:
1. Open  [string quartet 2.zip](https://github.com/musescore/MuseScore/files/9594429/string.quartet.2.zip)
2. Open Violin I part
3. Go to score and replace the Violin I with another instrument, like a Flute, using the Instruments panel
4. Observe that the **instrument name in part, in its tab and in parts dialog do not update**.

https://user-images.githubusercontent.com/90187801/190918628-ed607a95-dde3-4545-a3eb-344fb7ff3031.mp4

**Expected behavior**
The instrument's name should be updated in the parts dialog and its tab

Initial video from bug report

https://user-images.githubusercontent.com/88136054/146490932-a6ced8f6-6d20-4c0c-9d38-c2142dcf0a55.mp4

**Desktop (please complete the following information):**
Win, Mac, Linux

**Comment by HemantAntony** [comment]
I am working on this

**Comment by Tantacrul** [comment]
I don't know how widespread this problem is anymore. It could just be an issue with my file, which was originally a MusicXML import into 3.6. Other comments welcome!

**Comment by HemantAntony** [comment]
I can still reproduce this

Also if unclear, I'm no longer working on this. 5 months is too long :)

**Comment by Tantacrul** [comment]
OK, I've moved it to alpha then if you are still experiencing it.

**Comment by DmitryArefiev** [comment]
@RomanPudashkin Says there are two different issues here: 
* **one** about not updating sounds/name in Mixer 
* and **another** about not updating instrument name in part, in parts dialog and in part's tab

The **issue №1** is fixed in #13097 
The **issue №2** still happens 

I've edited the description to separate two issues

**Comment by DmitryArefiev** [comment]
@Tantacrul I moving this to Beta2 since the issue with changing sound and the name in Mixer is fixed now.

And also this issue is similar to #13239

**Comment by Tantacrul** [comment]
@DmitryArefiev - agreed. Moving now.

**Comment by woooowoooo** [comment]
An interesting thing to note is that on _other_ parts the name is updated, but not on the original.
![image](https://user-images.githubusercontent.com/51186839/198500827-acfefa4f-ac2b-4f95-895d-f9a9a5d1a01a.png)
![image](https://user-images.githubusercontent.com/51186839/198500857-fe65fd74-d4a0-4f97-9b90-687de95f2cfc.png)
The name change shown here is from Trumpet 4 to Trumpet 3. This is an issue for instrument _name_ changes too, not just actual instrument changes.

**Comment by DmitryArefiev** [comment]
Fixed in #14288
