### ISSUE TITLE
[MU4 Issue] Left, Right keys to move objects are not working

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10138]
**Describe the bug**
Left, Right keys to move objects are not working

**To Reproduce**
1. Select text (e.g. Staff text)
2. Move it with left right keys (arrows)  - **MU responds only first key pressing** 

**Desktop (please complete the following information):**
 - OS: all

**Additional context**
**Up, Down** keys start to work from a second press
Recent builds

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10144

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
