### ISSUE TITLE
[MU4 Issue] Delete, Cut, Copy, Paste operations are broken

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10132]
**Describe the bug**
Delete, Cut, Copy, Paste, Swap with clipboard (and maybe others similar) operations are broken

https://user-images.githubusercontent.com/90187801/146756031-1386ce10-71fe-4d29-8329-6a85802ef9b8.mp4

**Desktop:**
 - OS: all

**Additional context**
Recent builds

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10135
