### ISSUE TITLE
[MU4 Issue] MU removes line break for second text string when entering text

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10134]
MU removes a line break for the second text string when entering text (using Return).
Occurs with all text (Title, Staff text, Figured bass etc.)

https://user-images.githubusercontent.com/90187801/146768661-c081158c-b0a1-4ce9-ab88-55ab01b3b5e5.mp4

**Desktop:**
 - OS: all

**Comment by DmitryArefiev** [comment]
The similar issue when entering figured bass

https://user-images.githubusercontent.com/90187801/146945844-88e6f33e-b6a7-4b35-ba0b-3fac9b32ca57.mp4

(Should be logged separately if it's not fixed within current bug)

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10230

**Comment by DmitryArefiev** [comment]
Tested #10230 on Win10, Mac12, LinuxMint 20.2 - FIXED
