### ISSUE TITLE
[MU4 Issue] Shortcuts for note/rest durations are not working (1-9 and dot)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10137]
Shortcuts for note durations are not working (numbers and dot)

**To Reproduce**
1. Select note or rest
2. Hit 3 to change duration to 16th note - **it's not working**

**Desktop:**
 - OS: all

**Additional context**
Recent builds

**Comment by HemantAntony** [comment]
I am working on this

**Comment by DmitryArefiev** [comment]
Tested  on Win10, Mac12, LinuxMint 20.2 - FIXED in #10144 as well
