### ISSUE TITLE
[MU4 Issue] Implicit copy constructor for 'BeatsPerSecond' is deprecated

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#10139]
**Describe the bug**

When building MuseScore from the master branch, you get the following warning many, many times:

```
/src/engraving/types/bps.h:56:28: warning: definition of implicit copy constructor for 'BeatsPerSecond' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
    inline BeatsPerSecond& operator=(const BeatsPerSecond& v) { val = v.val; return *this; }
                           ^
/src/engraving/libmscore/tempo.h:91:46: note: in implicit copy constructor for 'mu::engraving::BeatsPerSecond' first required here
    BeatsPerSecond relTempo() const { return _relTempo; }
                                             ^
```

**Desktop (please complete the following information):**
 - OS: macOS 12.1, Apple Silicon

**Additional context**

This is one of two build issues I'm filing today. Currently every build prints 4,500+ lines of output to the terminal, making it nearly impossible to catch and fix these build errors. There should be far less output so we can quickly find what's going on.

**Comment by Jojo-Schmitz** [comment]
This "missing the tree in the forest" problem is the reason for my decade long fight against compiler warnings ;-)
Fix this one though is beyond my pay grade I'm affraid.

**Comment by cbjeukendrup** [comment]
The fix could be very simple: just delete the explicit assignment operator and it's fine. The idea of this warning is that it wants you to define an explicit copy constructor if you have defined an explicit assignment operator, and vice versa. 

I am not completely sure whether we really need the explicit assignment operator. @igorkorsukov What was the reason to add it?

**Comment by igorkorsukov** [comment]
> I am not completely sure whether we really need the explicit assignment operator. @igorkorsukov What was the reason to add it?

I couldn't compile without it.
I will now correct this warning.
Unfortunately, for some reason, I am currently using gcc 7.5, which is quite old, and therefore does not show me these warnings.

**Comment by Jojo-Schmitz** [comment]
There's another very frequent warning on Mac:
```
clang: warning: precompiled header '/Users/runner/work/MuseScore/MuseScore/build.release/src/framework/global/CMakeFiles/global.dir/cmake_pch_x86_64.hxx.pch' was ignored because '-include /Users/runner/work/MuseScore/MuseScore/build.release/src/framework/global/CMakeFiles/global.dir/cmake_pch_x86_64.hxx' is not first '-include'
```

**Comment by igorkorsukov** [comment]
> This is one of two build issues I'm filing today. Currently every build prints 4,500+ lines of output to the terminal, making it nearly impossible to catch and fix these build errors. There should be far less output so we can quickly find what's going on.

You can use IDE like QtCreator which will show warnings and errors separately

**Comment by Jojo-Schmitz** [comment]
> I couldn't compile without it.
If I uncomment those it compiles just fine in MinGW

**Comment by cbjeukendrup** [comment]
> There's another very frequent warning on Mac:
> 
> ```
> clang: warning: precompiled header '/Users/runner/work/MuseScore/MuseScore/build.release/src/framework/global/CMakeFiles/global.dir/cmake_pch_x86_64.hxx.pch' was ignored because '-include /Users/runner/work/MuseScore/MuseScore/build.release/src/framework/global/CMakeFiles/global.dir/cmake_pch_x86_64.hxx' is not first '-include'
> ```

I suspect those are caused by ccache. I believe they occur since ccache version 4.4. But maybe it is still our fault, since I can't find anything about it on the internet at all.

**Comment by igorkorsukov** [comment]
> If I uncomment those, it compiles just fine in MinGW and MSVC

hmm, now I compiled it too, but I wouldn't add it just like that. I will remove the assignment operator.

**Comment by Jojo-Schmitz** [comment]
of course, uncommenting was just to test ;-)

**Comment by Jojo-Schmitz** [comment]
See #10142
