### ISSUE TITLE
[MU4 Issue] 'showEvent' overrides a member function but is not marked 'override'

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#10140]
**Describe the bug**

When building MuseScore from the master branch, you get the following warning.

```
/src/notation/view/widgets/breaksdialog.h:50:10: warning: 'showEvent' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    void showEvent(QShowEvent*);
         ^
/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h:109:10: note: overridden virtual function is here
    void showEvent(QShowEvent *) override;
         ^
```

**Desktop (please complete the following information):**
 - OS: macOS 12.1, Apple Silicon

**Additional context**

This is one of two build issues I'm filing today. Currently every build prints 4,500+ lines of output to the terminal, making it nearly impossible to catch and fix these build errors. There should be far less output so we can quickly find what's going on.

**Comment by igorkorsukov** [comment]
Why not just add override?
