### ISSUE TITLE
[MU4 Issue] Selection behavior when creating a score and opening a score should correspond to MU3

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10156]
Actual result:
When **creating a new score**, MU selects the first rest in the first bar.
When **opening a recent score**, MU selects the initial barline of the top instrument.

Expected result:
When **creating a new score**, MU selects the first rest in the first bar.
When **opening a score**, MU selects nothing.  But if you press Tab it should select the first note/rest (or initial barline) 
(the second part was not implemented in MU3.6 but it should be implemented in MU4 for better navigation/accessibility)

https://user-images.githubusercontent.com/90187801/147117767-17b78b64-e83f-46f0-afd5-20074049b5f9.mp4

**Desktop (please complete the following information):**
 - OS: all

**Comment by cbjeukendrup** [comment]
Maybe a good first issue. 
I think the desired behaviour is selecting the first note or rest, like when creating a new score.

<details><summary>Hint</summary>
Start by looking at `NewScoreModel::createScore` (which is called in NewScoreDialog.qml), and `NotationPaintView::selectOnNavigationActive`.
</details>

**Comment by DmitryArefiev** [comment]
I thought a little and decided to change MU4 current behavior to MU3.6 behavior
 
When **creating a new score**, MU selects the first rest in the first bar.
When **opening a score**, MU selects nothing and the next Tab should select the first note/rest (or initial barline) - the second part was not implemented in MU3.6 but it should be implemented in MU4 for better navigation/accessibility

Will edit the summary and description

**Comment by DmitryArefiev** [comment]
Closing, since #10428 has more discussion about desired behavior
