### ISSUE TITLE
Score jumps when adding a slur or selecting a note

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10168]
**Describe the bug**
Another score jumping bug. When the page is a little more to the right of the screen, adding a slur (by clicking on a note and pressing 'S') the score jumps to the left.

**To Reproduce**
Watch video: 

https://user-images.githubusercontent.com/21022311/147372920-32684803-dcbe-40e3-b653-a5f1a69e55f8.mp4

You can also see that the score very often jumps when I select a note too. I've created a separate video to show how you can replicate the behaviour.

https://user-images.githubusercontent.com/21022311/147373073-d99ea8be-0f11-4ef8-be5d-7d850f95df19.mp4

**Expected behaviour**
Score jumps should not happen when adding elements to areas that are visible on the page. And definitely not when using your mouse to select a note that is visible on the page.

**Comment by wizofaus** [comment]
Probably not the same problem, but it may be related to something I'd looked into whereby the scroll position tries to ensure all selected elements are in view, but in some cases the selected elements include lines like slurs or hairpins etc. that have invalid bounding rectangles.  But that problem only occurred when selecting a range (e.g. a measure) that happened to include a line object.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
