### ISSUE TITLE
[MU4 Issue] Score jumps when entering note with mouse because dragging is turned on in Note Input mode

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10166]
Score jumps when entering note with mouse because dragging is turned on in Note Input mode

https://user-images.githubusercontent.com/90187801/147351906-e4f1a582-5db6-4257-a96c-a07c171dfd33.mp4

**Desktop:**
 - OS: all

**Additional context**
Recent builds

**Comment by Tantacrul** [comment]
Possibly related: https://github.com/musescore/MuseScore/issues/10168

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10177

**Comment by DmitryArefiev** [comment]
Tested #10177 on Win10, LinuxMint 20.2 - FIXED

**Comment by DmitryArefiev** [comment]
> Possibly related: #10168

Looks like it's different because not fixed with the current PR
