### ISSUE TITLE
[MU4 Issue] Closing project should change the window from Score to Home

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#10172]
**Describe the bug**
In my opinion, when you close a project, the current window should change from Score to Home.

**To Reproduce**
1. Create a Score
2. Close it now
3. The current window is still Score

**Expected behavior**
The window should change from Score to Home

**Screenshots**

https://user-images.githubusercontent.com/88136054/147434364-ec3ee7e8-8020-4b28-96a3-897eaf6dee10.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by RomanPudashkin** [comment]
@bkunda what do you think about this? :)

**Comment by bkunda** [comment]
@RomanPudashkin I agree this is a sensible suggestion 😀
