### ISSUE TITLE
[MU4 Issue] Tempo not changed during playback if note duration is not quarter

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#10171]
**Describe the bug**
When creating score if you were to change the note duration to something else other than a quarter note, say an eighth note, playback does not update the tempo on play (Probably best to watch the video if you don't understand). However, if you were to edit the tempo text, playing the score updates the tempo

**To Reproduce**
1. Create a score with a tempo text (by changing the note duration)
2. Play the score, the tempo does not update
3. Now, edit the tempo text to another tempo
4. Playing the score now updates the tempo

**Expected behavior**
Tempo should be updated when you play the score

**Screenshots**

https://user-images.githubusercontent.com/88136054/147433798-6138f98c-51db-4d4e-9a9c-30f0b2f89234.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by mattblo** [comment]
could be related to #9227

**Comment by HemantAntony** [comment]
I don't think so. This issue doesn't have much to do with the actual playback. It has to do with the displayed tempo. It correctly converts the tempo (displayed one at least) when you edit the tempo text and displays it when played. But it doesn't when a score is created

**Comment by HemantAntony** [comment]
In my opinion, I don't understand why the tempo cannot be updated immediately when the tempo text is changed. It seems better this way.

**Comment by RomanPudashkin** [comment]
Should be fine in the current master. Please, reopen the issue again if you can still reproduce it
https://github.com/musescore/MuseScore/pull/10803
