### ISSUE TITLE
[MU4 Issue] "Update translations" button in "Preferences > General" leaves settings in inconsistent state

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#10183]
**Describe the bug**
In Preferences > General, there is a button called "Update translations" that closes the preferences dialog and opens the Languages page.

When closing the preferences dialog, this button does not apply the changed settings, but also does not cancel them, leaving the app settings in "transaction mode". This may cause strange behaviour, like settings not being saved after closing the app, or settings that are outside the preferences dialog being reverted when the user opens the preferences dialog a second time and then pressing cancel.

**Expected behaviour**
@Tantacrul If the user has made any changes in the Preferences dialog, and then presses this "Updated translations" button, should the changes then be applied or canceled?

**Additional context**
Applying and canceling in the Preferences dialog was implemented by @Eism in PR https://github.com/musescore/MuseScore/pull/7856.

**Comment by Eism** [comment]
Nice catch, @cbjeukendrup

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/pull/10479
