### ISSUE TITLE
[MU4 Issue] Auto save overwrites existing score

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#10189]
**Describe the bug**
Auto save saves **into** the existing score instead a dedicated backup score

**To Reproduce**
1. Open any existing score.
2. Make any change (adding/changing note, whatever). Now the score is marked with an star.
3. Wait until auto-save kicks in.
4. Now the star is gone, indicating the score is saved. This shouldn't happen!
5. Close the score (File -> Close), the scores closes without the "Do you want to save changes tot the score..." dialog.
6. Open the score again, the previous made changes are stored. However, the original score is expected (as load in step 1).

**Expected behavior**
Auto save should save the score into a dedicated score file. Only after an explicit save (using the "Save" command) the score should be saved in the original file.
The original file should **never** be overwritten by the auto-save.

**Screenshots**
n.a.

**Desktop (please complete the following information):**
 - Linux

**Additional context**
Now the behavior of auto-save is changed with respected to MU3 (and (almost?) other program).

**Comment by wizofaus** [comment]
If saving was 100% reliable and the undo history was maintained, I wouldn't have an issue with it auto-saving over the existing file (after all, IDEs typically do that - every time you execute your code it auto-saves it).  But I do think users typically expect to be able to experiment with changes they don't intend to preserve, and certainly you should never lose work via auto-save, which you can now - e.g. if you do select+all then delete, then auto save occurs, then the application exits/restarts for any reason.

**Comment by Eism** [comment]
resolved in #10273
