### ISSUE TITLE
[MU4 Issue] Zoom in doesn't work with Ctrl + + but does with Ctrl + Shift + +

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#10192]
**Describe the bug**
If you were to use the shortcut Ctrl + +, it wouldn't zoom in. However, if you used Ctrl + Shift + +, it works.

**To Reproduce**
1. Create a Score
2. Use the shortcut Ctrl + + (as in Hold Ctrl and the Equal Buttons)
3. It does not work
4. Now do the same thing with Ctrl + Shift + +, it works

**Expected behavior**
Ctrl + + should zoom in similar to Chrome

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 
**Additional context**
Using Ctrl + - zooms out

**Comment by HemantAntony** [comment]
I'm working on this

**Comment by Jojo-Schmitz** [comment]
`Ctrl`+`+` just works for me in the current builds. 
As far as I can tell it ain't broke, so no need to fix.

**Comment by Jojo-Schmitz** [comment]
Even worse: `Ctrl`+`Shift`+`=`isn't even possible here
