### ISSUE TITLE
[MU4 Issue] When entering notes with keyboard, mouse cursor should not show a note symbol (MU3 missing functionality)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10208]
**To Reproduce**
1. Click empty bar
2. Start to Input Notes with keyboard 
3. Notice mouse cursor shows a note symbol - **it should not show a note symbol** because there are no any movements of mouse cursor. **It should show a note symbol when you start to move the mouse** (**it should work like in MU3**)

https://user-images.githubusercontent.com/90187801/148112118-ca07ea08-e551-4f0c-bcd5-1c98c0c3bcce.mp4

**Expected behavior**
Should work like in **MU3**

**Desktop:**
 - OS: all

**Comment by wizofaus** [comment]
As far as I can tell the mouse cursor only changes to a note symbol after entering the 2nd note with the keyboard, and that makes sense because at that point clicking the mouse button does in fact add a note at the position the mouse cursor is.  If anything I would suggest it's v3.6 that's wrong here, as the mouse cursor doesn't change to indicate that the action of clicking will add a note.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED

**Comment by DmitryArefiev** [comment]
> As far as I can tell the mouse cursor only changes to a note symbol after entering the 2nd note with the keyboard, and that makes sense because at that point clicking the mouse button does in fact add a note at the position the mouse cursor is. If anything I would suggest it's v3.6 that's wrong here, as the mouse cursor doesn't change to indicate that the action of clicking will add a note.

@wizofaus I think MU3.6 behavior is more desirable because appearing of shadow note (when user wants to input note with keyboard only) distracts attention especially when the mouse cursor is in a different location. And if user wants to combine note input from keyboard and mouse he can just move mouse and make shadow note visible.
