### ISSUE TITLE
[MU4 Issue] Saving causes zoom to go to 100%

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#10202]
**Describe the bug**

When saving with the keyboard shortcut `⌘S`, the screen zooms to 100%, regardless of the current zoom level.

**To Reproduce**
1. Zoom on the score to anything aside from 100% (doesn't matter how, either using the icons, the menu bar, pinch to zoom, or `⌘+` and `⌘-`)
2. Use the keyboard shortcut `⌘S` to save the file
3. The zoom level changes

**Expected behavior**

Saving with the keyboard shortcut should not affect the zoom level.

**Screenshots**

https://user-images.githubusercontent.com/5659171/147709762-52ab22b2-7462-47ca-8f08-70911bb352b3.mov

**Desktop (please complete the following information):**
 - OS: macOS 12

.1, Apple Silicon

**Additional context**

I'm unsure if this is a macOS specific bug. It has been present for at least a week or two now and I've been forgetting to add a bug report for this.

**Comment by HemantAntony** [comment]
Yeah, I can reproduce this on Windows 11. I'm working on this

**Comment by Tantacrul** [comment]
This issue is no longer occurring for me. Closing for now.
