### ISSUE TITLE
When adding slurs in MS4, you cannot use Keyboard shortcuts to extend / contract them as with MS3

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10209]
**Describe the bug**
The desired functionality was actually working in MS4 until a few days ago. I was away on holiday so didn't notice exactly when this happened. Basically, if you create a slur (I'm doing this by pressing 'S' in the attached video), you should be able to extend / contract it immediately using the shortcuts: **Shift+Command+Left/Right arrow** or **Shift+Alt+Left/Right arrow**.

This is also true for hairpins, pedal marks and various other lines. It is one of the most important shortcuts in the app and must function the same way as MS3. This is related to the bug: https://github.com/musescore/MuseScore/issues/10169

**To Reproduce**
See video

https://user-images.githubusercontent.com/21022311/148116986-dbc6f1c1-c53c-4320-8f1b-8b888eda2d28.mov

Mac: Catalina.

**Comment by wizofaus** [comment]
I believe https://github.com/musescore/MuseScore/pull/10185 fixes this (was reported as https://github.com/musescore/MuseScore/issues/9902)

**Comment by DmitryArefiev** [comment]
Tested  on Win10, Mac12, LinuxMint 20.2 - FIXED in #10401

**Comment by Tantacrul** [comment]
Awesome :)
