### ISSUE TITLE
[MU4 Issue] Appimage will freeze upon first use if "no telemetry" is selected.

### ISSUE THREAD

**Issue by MintMain21** [musescore/MuseScore#10215]
**Describe the bug**
When I download an Appimage for the first time, a dialogue box pops up asking if I want telemetry on of off. Every time I selected off, the app froze and I had to kill it with the system monitor. I tried older appimage releases to see if they resolved the bug, until at one I decided to just say "yes" and see what happened. The app actually ran, and I was free to disable telemetry in the preferences. After upgrading to the most recent (Appimage) release, I found that the telemetry preference was retained, and the bug was not encountered. Nevertheless, I'm reporting this because I fear it will turn away potential (privacy conscious) users. 

**To Reproduce**
1. Download the Appimage on a computer where Musescore was not previously used (as an Appimage).
2. When the telemetry pop-up appears, select "no".
3. The app will freeze, forcing me to kill it.
4. Open Appimage again, select "yes", and it will be circumvented. 

**Expected behavior**
The app should properly boot regardless of if I select Yes or No. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2, XFCE Edition.

**Additional context**
Now that I got the Appimage working, I can finally uninstall the Flatpak. I was legitimately concerned that Musescore would only work as a Flatpak. Furthermore, I suspect it may be related to https://github.com/musescore/MuseScore/issues/8143 .

**Comment by cbjeukendrup** [comment]
MuseScore 4 (which will be the next release) won't have telemetry anymore, so I think this is not applicable anymore and can be closed 🙂
