### ISSUE TITLE
[MU4 Issue] Incorrect font in app menu

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#10214]
**Describe the bug**
@Eism and I have discussed this previously. 
Turns out it is being 'MS Shell Dlg 2' (almost looks like Verdana!) in Qt for Windows instead of 'Segoe UI' which is what it should be.

Currently (MS Shell Dlg 2):
![image](https://user-images.githubusercontent.com/71656189/148217643-994a3c13-f19a-46c0-92a6-24721a48cca7.png)

Should be looking like this (Segoe UI):
![image](https://user-images.githubusercontent.com/71656189/148217605-e1fbc136-17af-47a8-ba03-378544105930.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Eism** [comment]
fixed in #10191
