### ISSUE TITLE
[MU4 Issue] Home tab side bar has reduced width when first opened.

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#10213]
**Describe the bug**
When first open Musescore the sidebar doesn't expand to its full width. This would have to be fixed by stretching it out.

Also note: The design of the sidebar should change when in narrow mode - Issue related to this from @bkunda https://github.com/musescore/MuseScore/issues/9488

https://user-images.githubusercontent.com/71656189/148214200-6ca9fb37-e63f-4a74-8799-4a24a12374e8.mp4

**Comment by Srijan-Chak012** [comment]
So I tried to replicate this issue on Linux, seems to me that the width of the sidebar depends on the previous width set by the user.  For a further explanation, I have attached a video showing how it works on my system

https://user-images.githubusercontent.com/76106446/148345591-7435f34e-d973-4647-a4b7-91c4f62f2f89.mp4

**Comment by bkunda** [comment]
@jessjwilliamson, if you select `Preferences` > `Reset Preferences`, then restart MuseScore, what width does the sidebar take? 

On my system it shows at what I *think* is the correct width. But the issues of resizing it still remain.

**Comment by jessjwilliamson** [comment]
> 

Ah, that did the trick. The weirdest thing is before I resetted it, every time I was opening musescore the sidebar was reduced and I had to drag it out every single time as it was so annoying! Strange...

**Comment by bkunda** [comment]
All good then. I think it probably makes sense for the sidebar to remember its last set width (especially if the user has deliberately chosen to reduce it to its narrow version). With this in mind – and unless I'm mistaken – there doesn't seem to be anything left in this issue. If you agree @jessjwilliamson then feel free to close it 🙂

**Comment by Tantacrul** [comment]
This is actually quite annoying and will break translations, so I've bumped to a p2.

**Comment by HemantAntony** [comment]
I don't think this issue occurs anymore. The behaviour of the side bar has changed:
[Issue.webm](https://user-images.githubusercontent.com/88136054/184638286-169b5dff-f3ae-4ebe-bf90-0c691053f4c4.webm)
