### ISSUE TITLE
[MU4 Issue] Grace note sits vertically above rest

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#10217]
**Describe the bug**

Grace notes should always come after rests horizontally—even if aligning them vertically doesn't create a collision.

Current

<img width="233" alt="Screen Shot 2022-01-06 at 4 10 38 PM" src="https://user-images.githubusercontent.com/5659171/148470141-7c437395-1341-4ac0-89a9-26c1353812fd.png">

Desired

<img width="232" alt="Screen Shot 2022-01-06 at 4 11 41 PM" src="https://user-images.githubusercontent.com/5659171/148470201-7dd52d4e-ed4c-4aef-8aa0-f11066e5fa03.png">

**Comment by oktophonie** [comment]
(See also: #9868)
