### ISSUE TITLE
[MU4 Issue] Beam breaks

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#10220]
**Describe the bug**

According to the [MuseScore 3 handbook](https://musescore.org/en/handbook/3/time-signatures#change-default-beaming), you should be able to change the default beaming for a time signature. This does not seem to be working right now.

**To Reproduce**
1. Go to the Time Signatures palette
2. Click "More"
3. Click "Create time signature"
4. As described in the [handbook](https://musescore.org/en/handbook/3/time-signatures#change-default-beaming), drag the beam break icons (which also need to be added) onto the displayed notes
5. The display does not update

**Expected behavior**

I should see visual confirmation of the new default beaming. Instead, everything looks unchanged.

> Note: Clicking directly on the notes to create a complete break is working as expected. It's only the dragging behavior that isn't working.

**Screenshots**

https://user-images.githubusercontent.com/5659171/148495083-525c9583-cb35-44e4-99c8-054373d2c8f5.mov

**Desktop (please complete the following information):**
 - OS: macOS 12.1, Apple Silicon

**Comment by Tantacrul** [comment]
This issue is duplicated here:
https://github.com/musescore/MuseScore/issues/9620
