### ISSUE TITLE
[MU4 Issue] Ctrl+click doesn't cycle between items in z-order

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#10225]
**Describe the bug**
In MuseScore 3, ctrl + left mouse button click can be used to select items that overlap each other (e.g. unison notes in different voices etc.).  This functionality is not implemented in MuseScore 4.

**To Reproduce**
1. Create a new score
2. Add a 1/4 note A in voice 1 and a 1/4 note A in voice 2 such that they overlap.
3. Click on the A, and note that the voice 1 note is selected
4. Ctrl+click, and note that it is just deselected.

**Expected behavior**
As per MuseScore 3, ctrl+click should cycle through elements stacked on top of each other.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by MarcSabatella** [comment]
Just a note that this is a still an issue in the latest build I tried.  It's a significant regression that should be fixed before release, but needn't hold up a public alpha.

The correct behavior of Ctrl+click with overlapping elements is that the first Ctrl+click should select the top element of the stack, then each successive Ctrl+click deselects whichever element is currently selected (as would normally happen for non-overlapping elements) and simultaneously selects the next element down.  When the last element in the stack is reached, Ctrl+click deselects it and does not select anything else, again reflecting the normal behavior of Ctrl+click in the non-overlapping case.

**Comment by Tantacrul** [comment]
Added a priority and targeted at beta.

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.org/en/node/332671

**Comment by re1san** [comment]
Hey, I would like to work on it.

**Comment by rgreen5** [comment]
Just checking to make sure this is still in progress.
