### ISSUE TITLE
[MU4 Issue] [Accessibility] Range Selections are not spoken by screen readers

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#10228]
**Describe the bug**
When a range of notes is selected, the screen reader should say "Range Selection" followed by the start and end location in terms of bars and beats similar to that displayed in the Status Bar at the bottom of the screen.

![image](https://user-images.githubusercontent.com/11011881/148757626-a5eedc3f-a2e0-4aca-a5d5-1fa58204a14b.png)

Here the screen reader should say _"Range selection: starts staff 1, measure 3, beat 3; ends staff 3, measure 5, beat 1.75."_

**To Reproduce**
1. Open an existing score or enter notes in a new score.
2. Start the screen reader (Narrator, NVDA, VoiceOver, Orca, etc.)
3. Select a range of notes (e.g. hold Shift and press Up, Down, Left or Right arrow keys) and listen to the screen reader.
4. Continue extending the range selection and listening to the screen reader.

**Expected behavior**
The screen reader should say the contents of the status bar: _"Range selection: starts... ends..."_. Instead it just says the name of the last note in the range selection.

 - OS: All (tested on Windows and macOS)

**Additional context**
There is code to do this in [src/notation/internal/notationaccessibility.cpp](https://github.com/musescore/MuseScore/blob/c816fb01719e81575579e132b150237f0f8685db/src/notation/internal/notationaccessibility.cpp#L102-L115) but it appears to be unused at the moment, and I'm not sure how it integrates with the element accessibility code in [src/engraving/accessibility](https://github.com/musescore/MuseScore/tree/master/src/engraving/accessibility).

**Comment by shoogle** [comment]
@HemantAntony, happy to take this one? I suggest you implement a simple fix in [accessibleitem.cpp](https://github.com/musescore/MuseScore/blob/5377cefdb436e7e267dd548e6366dfb186a4aa94/src/engraving/accessibility/accessibleitem.cpp#L175-L203) where you manipulate the name and description of the selected element to indicate to users that a range selection is taking place. Do this properly and you should be able to fix this issue and https://musescore.org/en/node/303351 at the same time (just screen reader output, not playback at this time).

So where MU3 would say this:

*"Range selection: starts measure 3, beat 3; ends measure 5, beat 1."*

MU4 should say this:

**Accessible name:** _"Selection ends Note C3 half, measure 5 beat 1, tremelo 8th through stem, start of hairpin crescendo"_
**Accessible description:** _"Selection starts Note C5 dotted quarter measure 3 beat 3"_

Or in generic terms:

**Accessible name:** _"Selection ends "_ + `element2.name` + `element2.description`
**Accessible description:** _"Selection starts_ + `element1.name` + `element1.description`

Where `element2` is the last element in the range selection and `element1` is the first element in the range selection.

I want to give the name of the end element first because that's the element that changes as you press Shift+Right to grow the selection to the right, so it is important that blind people hear its name sooner. If you press Shift+Left then the selection shrinks from the right, so we should continue to name the end element first. However, if you keep pressing Shift+Left to the point that the selection shrinks to a single element and then starts growing to the left then we should name the start element first. We should always name the changing element first and the fixed element second.

**Comment by HemantAntony** [comment]
Okay, thank you! I have understood the specs. I am going to start working on this :)

**Comment by DmitryArefiev** [comment]
@Tantacrul What about to move this to Beta2 for now? (with P1)

**Comment by shoogle** [comment]
@DmitryArefiev, I believe @HemantAntony will submit at least a partial fix for this today or tomorrow.

**Comment by Tantacrul** [comment]
I agree that if Hemant's fix doesn't work, this one should be bumped to Post Beta

**Comment by HemantAntony** [comment]
@shoogle Check #13502
