### ISSUE TITLE
[MU4 Issue] `Save selection...` does nothing

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10223]
**Describe the bug**
`Save selection...` doesn't save a file. Seems to perform no function. 
This is currently working in 3.6, so it seems it might be a regression in MS4.

**To Reproduce**
1. Open or create a new score containing some engraved elements
2. Select a range of music (e.g. a few bars)
3. Select `File`>`Save selection...`
4. Choose your destination file location and click `Save`
No file will be created

**Expected behavior**
A new file containing only the selected measures should be created at the chosen file destination (Per MS3.6).

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by igorkorsukov** [comment]
@VanSHOE fixed the problem, @DmitryArefiev  please check, PR https://github.com/musescore/MuseScore/pull/10224

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
