### ISSUE TITLE
[MU4 Issue] Text items from `+` menu don't recognise keystrokes; causes crash after repeated attempts 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10222]
**Describe the bug**
Text items from the `+` menu aren't recognising keystrokes:

![Add-menu-text-items](https://user-images.githubusercontent.com/86290556/148522021-baa8d237-1901-493f-a83d-840cfd73d0cf.gif)

Making repeated attempts at this causes MuseScore to crash:

![crash-add-menu-item](https://user-images.githubusercontent.com/86290556/148522074-4a57cbf4-699f-47ca-84e6-794531db2f3f.gif)

**Expected behavior**
Text items should respond to keystroke entry when inserted from the `+` menu.
MuseScore should not crash.

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by HemantAntony** [comment]
Interesting, when I just opened the score (without clicking on anything afterwards), I could create a lyrics text by using the shortcut

**Comment by bkunda** [comment]
Keyboard shortcuts seems to work fine. It's inserting text items from the actual "+" menu item that don't work correctly.

**Comment by HemantAntony** [comment]
I'm not exactly sure, but this appears to be a context problem. I will take a look at this. The fix looks easy

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
