### ISSUE TITLE
[MU4 Issue] Crash after PR #10212

### ISSUE THREAD

**Issue by VanSHOE** [musescore/MuseScore#10233]
**Describe the bug**
After the requested change in the PR, a crash has started happening on continuously closing the project and opening it back up
As discussed in discord, I am raising an issue for the same
**To Reproduce**
1. Open a project, save it
2. Change zoom, save
3. Close the project
4. Open it again from recents (ensure the zoom has reset itself) 
5. Repeat from 2 until a crash happens (could take a while)

**Expected behavior**
No crash should happen

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This happens after the changes of https://github.com/musescore/MuseScore/pull/10212
![image](https://user-images.githubusercontent.com/75690289/148824456-7f6c329d-ff92-4022-9b17-9973cd195310.png)
The crash as shown in QT

**Comment by RomanPudashkin** [comment]
I don't think, that it is a good idea to create an issue when you have some problems in your PR. @Eism offered his help with this crash in your PR
