### ISSUE TITLE
DevTool menu options overlap with the title bar (Win10, MuseScoreNightly-202201090423-master-b30ac74-x86_64

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#10232]
I will now **Describe the bug**
This is a short and clear description of what the bug is.
Basically, DevTool menu options overlap with the title bar when you scroll down.

**To Reproduce**
1. Go to 'MuseScore 4'
2. Click on 'DevTools'
3. Scroll down to 'anywhere'

**Expected behavior**
This is a clear and concise description of what I expected to happen.
The options would go up the screen and be covered and hidden by the title bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/87204246/148796448-add80c04-bafb-4789-bda2-b0e287a234f4.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
I will not add any other context about the problem here.

Anyone who has reported several things on MuseScore (or has read this sentence) has probably realized that I just changed the template issue as little as possible.

**Comment by Tantacrul** [comment]
This appears to be fixed. Closing.
