### ISSUE TITLE
[MU4 Issue] Some menus from Menu bar don't fit into the screen on 150% and higher (Windows 10)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10238]
**Describe the bug**
Some menus from Menu bar don't fit into the screen on 150% and higher (Windows 10):
- **View**
- **Add>Intervals**
- **Add>Text**

![01_100](https://user-images.githubusercontent.com/90187801/148941684-1cff5646-358f-41eb-8c15-e5d270685d31.png)

<img width="960" alt="01_150" src="https://user-images.githubusercontent.com/90187801/148941702-1201a223-aefb-4b72-ab0c-614a89d84bbc.png">

![02_150](https://user-images.githubusercontent.com/90187801/148941716-b024961a-1b7f-4843-ac73-b0e00bb31619.png)

<img width="960" alt="03_150" src="https://user-images.githubusercontent.com/90187801/148941731-e529ef70-e45a-4380-a8c9-df8d89ac4e09.png">

**To Reproduce**
1. Change Windows scaling to 150% or higher

**Screenshots**

**Desktop:**
 - OS: Win10

**Comment by Eism** [comment]
@DmitryArefiev 
I fixed it in https://github.com/musescore/MuseScore/pull/10706
Please recheck

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev I fixed it in #10706 Please recheck

@Eism Yes, it looks good now in master. Thanks!

Tested in **latest master** on Win10 (150-200%) - **FIXED**

Closing
