### ISSUE TITLE
[MU4 Issue] double and triple-click in text fields do not highlight the word or paragraph

### ISSUE THREAD

**Issue by riaanvn** [musescore/MuseScore#10242]
**Describe the bug**
When editing text (in the header frame or the score), double and triple-click in text field do not highlight the word or paragraph.

**To Reproduce**
1. Add staff text, containing multiple lines
2. Double-click or triple-click on a word 

**Expected behavior**
Double-clicking a word selects the word
Triple-clicking a word selects the paragraph.

**Expected behavior**
Nothing happens

**Desktop (please complete the following information):**
 - OS: macOS 12.1

This is standard GUI behaviour on Windows, Linux and macOS.
It works on MuseScore 3.6.2, e.g. this is a regression. 

** Workaround **
Highlight text using the mouse cursor, or Ctrl/Cmd+A to select all text

**Comment by DmitryArefiev** [comment]
Fixed in #13103
