### ISSUE TITLE
[MU4 Issue] Style properties for a range of objects do not update across parts 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10268]
**Describe the bug**
Changing the appearance of certain objects does not update across parts:

https://user-images.githubusercontent.com/86290556/149475357-e78571ea-9804-48b0-9b16-109d327fb93d.mp4

*Affects the following objects*
- Lines
- Jump marks (E.g. D.C, D.S., coda)
- Rehearsal marks
- Text (e.g. staff text, system text)

**Note**: Generating parts for the first time will correctly read object style properties. The issue is then changing those object style properties after parts have first been generated. 

**Note also**: Deleting and recreating the parts again does not update with object style changes (i.e. this is not a workaround). A workaround does, however, exist specifically for text objects (including rehearsal marks, but not including line text objects), where the user changes something in the actual text itself (this then forces the parts to update with the changed style properties). 

**Expected behavior**
Any changes to object style properties in the main score should be automatically and immediately visible in existing and subsequently created parts).

**Desktop (please complete the following information):**
- MacOS 11.6 (M1)
- Windows 11

**Additional context**
Also a bug in MS3.6 (see https://musescore.org/en/node/299851)
See also https://github.com/musescore/MuseScore/issues/10098

**Comment by bkunda** [comment]
Just re-testing this and I can see it is still a problem.
@RomanPudashkin what info do you need and is there any way I can help?

**Comment by oktophonie** [comment]
Closed as incorporated into https://github.com/musescore/MuseScore/issues/16544
