### ISSUE TITLE
[MU4 Issue] Very difficult to use line grip points when the navigator is shown

### ISSUE THREAD

**Issue by RomanPudashkin** [musescore/MuseScore#10269]
**Describe the bug**

https://user-images.githubusercontent.com/67867444/149493422-1c425b1f-9d60-4c9b-a034-cee0c1de4d46.mp4

**Desktop (please complete the following information):**
 - OS:  macOS (with HIDPI screen)

**Comment by DmitryArefiev** [comment]
@RomanPudashkin Since the feature (showing selection in Navigator) is missing in MU3 let's promote without it.
In my opinion, Navigation looks fine without it. 

FYI @Tantacrul @bkunda

**Comment by Tantacrul** [comment]
I agree that showing the selection in the navigator is a trivial issue.
