### ISSUE TITLE
[MU4 Issue] Text fields not recognising some accented characters in MacOS

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10262]
**Describe the bug**
Two parts to this issue:

1. Attempting to enter acute and grave accents, as well as umlauts, using the `option` key fails to produce the correct character in text fields (including lyric lines)
2. Long-pressing a key does not open MacOS's special characters menu

**Examples and demonstration**
`Option`+`e` then `e` should produce é:
![GIF 1-13-22 at 21 58 30](https://user-images.githubusercontent.com/86290556/149323242-e5143eeb-eeab-414e-af4d-bdbc0efffe8d.gif)

Accent modifier keys `´` and ` (backquote) on language-specific keyboards should also produce é and è, respectively (Spanish keyboard shown in this example):

![GIF 1-13-22 at 22 01 13](https://user-images.githubusercontent.com/86290556/149323900-335231c5-8ebe-4193-baca-4d5c4526c848.gif)

**Expected behavior**
1. Accent modifier keys should produce acute and grave accents, as well as umlauts, on any applicable keyboard, as per MS3.6:

![Recording 2022-01-13 at 22 45 07](https://user-images.githubusercontent.com/86290556/149324775-4e6ed97e-69de-4d76-a560-2648cfd73872.gif)

2. The MacOS long-press should trigger the special characters popup:

<img width="304" alt="Screenshot 2022-01-13 at 10 49 09 pm" src="https://user-images.githubusercontent.com/86290556/149325096-cdd7f9fb-833c-4627-89e1-699183a05d30.png">

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)

**Comment by Tantacrul** [comment]
Nice discovery @bkunda !
