### ISSUE TITLE
[MU4 Issue] Deleting note with right click not working (in Note input mode)

### ISSUE THREAD

**Issue by izarys** [musescore/MuseScore#10276]
**Describe the bug**
Deleting a note with right mouse click is not working. It either does nothing or adds a new note.

**To Reproduce**
1. Create an empty score.
2. Add a note.
3. Right click directly on the added note.
4. Note is not deleted.

Another behavior that is causing an unexpected result:
1. Create an empty score.
2. Add a note.
3. Right click below or above the added note.
4. A new note is added.

**Expected behavior**
Note should be deleted.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Note**
The feature was available in MuseScore 3, so I assumed that it should also work in MuseScore 4.

**Comment by DmitryArefiev** [comment]
@izarys - thank you for logging this!

One thing.. you forgot to add a step that user should trigger note input mode (N)

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10443

@izarys it should be in the next master. Thanks!
