### ISSUE TITLE
VST - Crash: Choosing a VSTi and two VST effects, then saving causes a crash

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10275]
**Describe the bug**
Please see video. I have altered the sound to a VSTi (choosing Vital). I then add two effects and try to save. Here are the steps. 

**To Reproduce**
1. Create a score with a few woodwind, brass and string instruments. Around 12-15.
2. Then save the score on your machine
3. Close MS4
4. Reopen it and then choose the saved score
5. Add a VSTi to replace the MuseSampler on one instrument (not strictly necessary. I've got it to crash without this step). Best to choose Vital
6. Add two VST effects to the same instrument
7. Then try to save the score
8. App crashes

**Desktop**
 - Windows 10

**Video**

https://user-images.githubusercontent.com/21022311/149587745-e0726db4-2fc6-4250-b973-50a4e366ed00.mp4

**Comment by Tantacrul** [comment]
Noticed this similar bug:
https://github.com/musescore/MuseScore/issues/9884

Just adding evidence. I see these issues haven't been tackled yet, so I won't log more for now. I assume we're waiting until playback core work has been completed.

**Comment by jessjwilliamson** [comment]
This issue seems to be solved :)

**Comment by Tantacrul** [comment]
@DmitryArefiev

**Comment by DmitryArefiev** [comment]
Tested in master build on Win10, Mac12 - **FIXED**, no crash

Closing
