### ISSUE TITLE
[MU4 Issue] Hyphenated lyrics render small text size for syllables after the first one

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10271]
**Describe the bug**
The text size for multisyllabic lyrics is rendered smaller for all syllables following the first syllable:

<img width="1095" alt="Screenshot 2022-01-14 at 10 08 30 pm" src="https://user-images.githubusercontent.com/86290556/149507095-977fc4a5-b380-4ec9-9a4e-daa83ca7c120.png">

**To Reproduce**
![GIF 14-01-2022 at 22 21 15](https://user-images.githubusercontent.com/86290556/149508298-cd194625-2b83-4670-b747-2ada09775237.gif)

**Expected behavior**
Font size should not change for multisyllabic lyric text.

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Additional info**
This is critical as any score with lyrics is practically unusable with this bug.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
