### ISSUE TITLE
[MU4 Issue] Crash when editing `Score properties`

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10289]
**Describe the bug**
Making any kind of change to any of the text entry fields in `File` > `Score Properties` triggers a crash: 

![crash-score-properties](https://user-images.githubusercontent.com/86290556/149932375-47236efc-62e7-43a3-9857-4c58a4b73944.gif)

**Expected behavior**
Crash should not occur. 

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by cbjeukendrup** [comment]
There is already a PR for this crash: https://github.com/musescore/MuseScore/pull/10266

**Comment by bkunda** [comment]
Thanks @cbjeukendrup.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10266
