### ISSUE TITLE
[MU3.6.2_backend Issue] Stretched out lyrics

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#10286]
**Describe the bug**
Not sure how to describe in words, but check out the images, resulting from the attached score ([lyrics-test.zip](https://github.com/musescore/MuseScore/files/7887546/lyrics-test.zip)), this is how it looks in 3.6.2:
![image](https://user-images.githubusercontent.com/1786669/149903276-2e82072c-7aa1-4537-861a-319fc60217f6.png)
This is how it looks in 3.6.2_backend (and therefore on musescore.com too):
![image](https://user-images.githubusercontent.com/1786669/149903411-8917e0b7-5128-4f78-8598-362cb08dfb2f.png)

**To Reproduce**
1. Download the above attached score (unpack .zip to get to the .mscz
2. Open the .mscz in MuseScore 3.6.2
3. Use File > Save online
4. See error on musescore.com

**Expected behavior**
The backend in musescore,com (taken from the 3.6.2_backend branch) should render scores the same as the released version, 3.6.2.

**Screenshots**
See above. 

**Additional context**
The master branch doesn't seemt to be affected by this, apparently the 'culprit' change hasn't yet been ported over to it.
I've pinpointed the culprit to be the 1st commit of PR #8296, titled "ENG-34: Fix erroneous space created for melismas".

It does get worse than that, on every "Ctrl+A, Ctrl+R" (i.e. resetting all elements to their default positions, step by step digressing more into something entirely bogus:
![image](https://user-images.githubusercontent.com/1786669/149904554-dace19a2-5e2e-4d6d-a593-d75881649df4.png)
![image](https://user-images.githubusercontent.com/1786669/149904583-b0ee8291-d11c-407e-b052-761033b6f93d.png)
![image](https://user-images.githubusercontent.com/1786669/149904600-0b6149b2-0e01-4945-aeff-931bc6a68bda.png)
![image](https://user-images.githubusercontent.com/1786669/149904624-4e3b6f12-6f1a-4f14-8487-c9774ba2cc66.png)

See also issue #9747, which might be related, at least there's an overlap in the possible culprit
See also PR #9581, which is a start ar porting all these 3.6.2_backened changes to master

**Comment by Tantacrul** [comment]
@oktophonie - for reference.

I'm going to close since we have not inherited this nastiness :)

**Comment by Jojo-Schmitz** [comment]
We'd still better fix the 3.6.2_backend. If it is still affected.
