### ISSUE TITLE
[MU4 Issue] [Accessibility] Measure and Beat are not spoken by screen readers

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10284]
**Describe the bug**
A short and clear description of what the bug is.

![Capture](https://user-images.githubusercontent.com/90187801/149810848-0cec58fd-3f35-41e9-bd2b-fb349e96e373.png)

**Expected behavior**

**Desktop:**
 - OS: Win (Narrator), Mac (VoiceOver)

**Additional context**

**Comment by Tantacrul** [comment]
I'm bumping this because you can't write music if you don't know what measure and beat you are on.

**Comment by DmitryArefiev** [comment]
Fixed in #11663
