### ISSUE TITLE
[MU4 Issue] Notes not playing back when editing or inputting notes

### ISSUE THREAD

**Issue by SamPro910** [musescore/MuseScore#10281]
**Describe the bug**
MuseScore only plays a very short blip when selecting or inputting notes
**To Reproduce**
1. Open any score
2. select/add a note

**Expected behavior**
MU4 should play back the whole note, not a short blip

**Desktop (please complete the following information):**
 - OS: Windows 11 64-bit

**Comment by HemantAntony** [comment]
Related to #9251
