### ISSUE TITLE
[MU4 Issue]misrepresenting "undock"as "dock"

### ISSUE THREAD

**Issue by duanjr** [musescore/MuseScore#10292]
**Describe the bug**
Dockable panels (Palettes, Instruments, etc.) misrepresenting undock operation's title "undock"as "dock"

**To Reproduce**
1. Create a new score or open an exsiting one.
2. Make any dockable panel visible.
3. a. If the panel is undocked, make it docked.
b. If the panel is already docked, make it undocked first and then make it docked.

https://user-images.githubusercontent.com/71218187/149950506-cbeb850b-011c-4798-b780-dd8aeddbcaf4.mp4

**Comment by duanjr** [comment]
I think I had fixed it and I'll make a pull request soon.

**Comment by HemantAntony** [comment]
This issue is missing a Title

**Comment by duanjr** [comment]
> This issue is missing a Title

Sorry it's my first time to report a issue, I have added a title.

**Comment by DmitryArefiev** [comment]
Fixed in #11459
