### ISSUE TITLE
[MU4 Issue] Touchpad single tap doesn't work properly with Note Input bar on Windows 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10291]
**Describe the bug**
When using touchpad on Windows, single tap doesn't toggle Note Input bar buttons (like MU3 does)

**To Reproduce**
1. Select note
2. Try to change its duration by tapping with finger Note Input bar - **nothing happens**, you need to double tap to toggle the buttons

https://user-images.githubusercontent.com/90187801/149945641-8c35887a-64d5-41cb-8a1f-95d0c566ce26.mp4

**Desktop (please complete the following information):**
 - OS: **Windows only** (Win10)

**Additional context**
Doesn't occur in **MU3** (Win10)

**Comment by Tantacrul** [comment]
Great find man!

**Comment by DmitryArefiev** [comment]
Oh, it's @Eism found it! 💪

**Comment by Tantacrul** [comment]
@DmitryArefiev - is this still happening. I'm testing on Mac and it appears to be working well.

**Comment by HemantAntony** [comment]
@Tantacrul I can reproduce it. There's more to this issue. You can't click most buttons in that toolbar with one click

**Comment by MarcSabatella** [comment]
For me all buttons work as I expect *except* the dropdown next to the note input button.  I would expect clicking the little arrow would open it. but it doesn't, I need to long-tap.  Not sure if that's on purpose or not, but it took me a while to discover it was possible, since long-tap isn't something I expect to use on my laptop.

**Comment by Tantacrul** [comment]
Yes, that Note Input button change was by design. I'd be keen to revisit it another time - especially when we fix up those modes so they are more useful / understandable.

**Comment by HemantAntony** [comment]
I can reproduce this issue on Windows 11

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev - is this still happening? I'm testing on Mac and it appears to be working well.

@Tantacrul Yes, still occurs on my Windows10. This is a Win only issue so working fine on Mac.

@HemantAntony Thanks for checking!

**Comment by DmitryArefiev** [comment]
Fixed in #13080
