### ISSUE TITLE
[MU4 Task] [GP] Display ghost-note correctly

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10306]
**Task description**
Display ghost-notes with parenthesis

Current state:
![Screenshot 2022-01-19 at 15 21 55](https://user-images.githubusercontent.com/24373905/150128519-d2799699-e6a8-4c71-ad6a-9eb18659e33f.png)

Expected:
![Screenshot 2022-01-19 at 15 22 07](https://user-images.githubusercontent.com/24373905/150128551-dd644fc9-e096-4c4d-b953-c49621cc4b27.png)

**Comment by Jojo-Schmitz** [comment]
I'd actually expect the notehead in the 'normal' staff to be a X shape rather than a normal notehead with parens?

**Comment by alexpavlov96** [comment]
@Jojo-Schmitz like a dead note?
![Screenshot 2022-01-19 at 16 06 30](https://user-images.githubusercontent.com/24373905/150136553-41544565-1f1d-4d76-a86a-4b3181fce485.png)

**Comment by Jojo-Schmitz** [comment]
Hmm, guess so, but a dead note still needs a fret (not an x), doesn't it?

**Comment by alexpavlov96** [comment]
@Jojo-Schmitz according to guitar-pro it has just 'x' in both places
