### ISSUE TITLE
[MU4 Task] [GP] Display dives of different types

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10313]
**Task description**
Display dives of different types: tremolo bar dive, dive and dip, pre-dive, etc.

**Expected:**
![Screenshot 2022-01-19 at 16 09 08](https://user-images.githubusercontent.com/24373905/150137009-5bc792e0-188d-420c-a878-ed60d4e34a9d.png)

**Comment by alexpavlov96** [comment]
should be implemented after design

**Comment by Tantacrul** [comment]
Can I ask what this is about? What design is needed? Is this another blocker on MS4?
