### ISSUE TITLE
[MU4 Task] [GP] Display harmonics

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10311]
**Task description**
Show harmonics (text and different note display)

**Excepted:**
![Screenshot 2022-01-19 at 15 40 22](https://user-images.githubusercontent.com/24373905/150132578-e9d81e15-8d4d-431b-ba1e-91653cbb7331.png)

**Comment by boryskuzmenko** [comment]
**Reopened**
The issue is still reproducible on TAB staff. Harmonics are not rendered correct. See video:

https://user-images.githubusercontent.com/101250347/164323637-bda88819-173a-4f05-8e2b-76c688aef321.mov

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
