### ISSUE TITLE
[MU4 Task] [GP] Display fermatas

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10318]
**Task description**
Fermata is not shown

**Comment by boryskuzmenko** [comment]
**Reopened**
Fermata is displayed on TAB staff when standard notation staff also present. According to the consistency all marks should be hidden in case of using 'Tab. 6str. - common' and 'Tab. 6str. - simple' staff types.
![Capture 2022-04-20_04-19-42_PM](https://user-images.githubusercontent.com/101250347/164240641-57534d39-223b-48e7-b82a-9cebc13722ff.png)
<img width="810" alt="Знімок екрана 2022-04-20 о 16 24 45" src="https://user-images.githubusercontent.com/101250347/164240687-ef576e4f-619b-4692-8111-45f42482df0f.png">

**Comment by alexpavlov96** [comment]
I will leave it as a draft cause this would be fixed through styles

**Comment by boryskuzmenko** [comment]
Will be done in scope of https://github.com/musescore/MuseScore/issues/11688
