### ISSUE TITLE
[MU4 Task] [GP] Display octave signs correctly

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10326]
**Task description**
1. Show all different octave signs, not just "8"
2. '8vb' is shown wrong: should be below the staff
3. The sign should be displayed only for standard notation (tab notation should not be affected)

**Current state:**
![Screenshot 2022-01-19 at 19 32 53](https://user-images.githubusercontent.com/24373905/150173765-8433d496-33ae-4850-9217-720660e749bf.png)

**Expected:**
![Screenshot 2022-01-19 at 19 32 59](https://user-images.githubusercontent.com/24373905/150173776-6c3b4acc-1cab-4b92-8b82-de87132f0097.png)

**Comment by MarcSabatella** [comment]
1 and 2 works fine for me - are you setting the option in the Properties panel to make those symbols appear?  The 8 below works fine for me as well when adding from the palette.

But it's true that none of these symbols should be displayed by default for tab.  As with MU3, workaround is to mark them invisible manually.

**Comment by alexpavlov96** [comment]
@boryskuzmenko 
"1" is correct by now (8 and not 8va - it will be an issue of design later)
"3" was not correct and fixed in the PR
