### ISSUE TITLE
Crash on opening orchestral score from MuseScore.com

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10323]
**Describe the bug**
When trying to open [this score](https://www.dropbox.com/s/pmwqima2bvate1p/Minecraft_Orchestra_Edition_for_the_Intermission_Orchestra_at_UCSD.mscz?dl=0) MS4 crashes. The score opens fine in MS3.

**Comment by Tantacrul** [comment]
@vpereverzev Let me know if these kinds of bugs are worth logging yet. I'm unsure how well we expect scores to behave until our playback system is complete.

Also let me know if you want me to create a new label for this: for example 'Legacy Score Problems' or something like that.

**Comment by HemantAntony** [comment]
I think the reason why this crash occurs is because MuseScore is trying to load an item that is not present in the path:
![image](https://user-images.githubusercontent.com/88136054/150164112-5ffacc09-31fe-4d4d-9166-b0a2d327202d.png)
There is no user "tommy" in my computer. Maybe its the author's?

**Comment by Jojo-Schmitz** [comment]
Culprit 'cpde' in the mscx:
```
        <Image>
          <offset x="4.73182" y="5.827"></offset>
          <path>f7b790b317b857c1ff9aa74bf240665d.png</path>
          <linkPath>C:/Users/tommy/Downloads/Minecraft-Logo-PNG.png</linkPath>
          <size w="209.209" h="76.2735"></size>
          </Image>
        <Image>
          <offset x="13.4862" y="113.874"></offset>
          <path>bf15b2d13f3209bc565eebbd9a229278.jpg</path>
          <linkPath>C:/Users/tommy/Downloads/a3390257927_10.jpg</linkPath>
          <size w="187.126" h="187.126"></size>
          </Image>
        <Image>
          <linkedMain></linkedMain>
          <offset x="20.7398" y="-2.91889"></offset>
          <visible>0</visible>
          <path>f7b790b317b857c1ff9aa74bf240665d.png</path>
          <linkPath>C:/Users/tommy/Downloads/Minecraft-Logo-PNG.png</linkPath>
          <size w="37.8787" h="13.8099"></size>
          </Image>
        <Image>
          <linkedMain></linkedMain>
          <offset x="113.845" y="2.74403"></offset>
          <visible>0</visible>
          <path>f7b790b317b857c1ff9aa74bf240665d.png</path>
          <linkPath>C:/Users/tommy/Downloads/Minecraft-Logo-PNG.png</linkPath>
          <size w="37.8787" h="13.8099"></size>
          </Image>
 ```

**Comment by vpereverzev** [comment]
> @vpereverzev Let me know if these kinds of bugs are worth logging yet. I'm unsure how well we expect scores to behave until our playback system is complete.
> 
> Also let me know if you want me to create a new label for this, like 'Legacy Score Problems' or something similar.

Ye, I think it's still worth to log such issues

this one is actually quite a useful bug. We store local copies of the images in the .mscz container, so we don't need to use the "original" images when loading the score. However, this case shows that we are trying to access the original one and then it crashes.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED

When tested on Linux, there was an assertion in some cases (will log it separately if reproduces in master after merging)
