### ISSUE TITLE
[MU4 Task] [GP] Display swing and triplet feel

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10324]
**Task description**
Display swing and triplet feel

**Expected:**
![Screenshot 2022-01-19 at 18 37 05](https://user-images.githubusercontent.com/24373905/150163685-b1a83fe6-3189-4cdf-bc0b-a8c237149049.png)

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/11802
Tested on macOS 12, Win 11, Ubuntu 20
