### ISSUE TITLE
[MU4 Task] [GP] Display hammer-on/pull-off

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10322]
**Task description**
1. Display hammer-on/pull-off with H and P (or H.O and P.O.)  indication

**Expected:**
![Screenshot 2022-01-19 at 17 58 42](https://user-images.githubusercontent.com/24373905/150156300-b7d69ca3-5504-4edb-8b18-023a8e2632bd.png)

2. Continuous hammer-ons/pull-offs should have one tie over the whole passage

**Expected:**
![Screenshot 2022-01-25 at 18 18 42](https://user-images.githubusercontent.com/24373905/151004711-af5f2e13-4c71-4a3e-8398-f6e9facf5238.png)

**Comment by Jojo-Schmitz** [comment]
hummer -> hammer ;-)

**Comment by oktophonie** [comment]
Oh I dunno, I'm always happy to have my hummer pulled off.
