### ISSUE TITLE
[MU4 Task] [GP] Display two-measure repeat sign

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10325]
**Task description**
Instead of two-measure repeat sign MU import it as two single-measure repeat signs.

**Current state:**
![Screenshot 2022-01-19 at 19 20 49](https://user-images.githubusercontent.com/24373905/150171721-d2c1886c-1d63-4d35-a9f0-cb781943bb98.png)

**Expected:**
![Screenshot 2022-01-19 at 19 20 36](https://user-images.githubusercontent.com/24373905/150171669-a5106536-90c4-4a70-b958-714b7dad0a01.png)

**Comment by Jojo-Schmitz** [comment]
Seems an ommision when the 2-measure repeats had been implemented during last GSoC, @IsaacWeiss ?
