### ISSUE TITLE
[MU4 Issue] Note name displayed in the bottom screen bar is not refreshing

### ISSUE THREAD

**Issue by izarys** [musescore/MuseScore#10337]
**Describe the bug**
Moving the note by up/down arrows does not change the note name displayed in the bottom screen bar.

**To Reproduce**
1. Create an empty score
2. Add a note
3. Click up/down to change the added note
4. Note name displayed in bottom screen bar is not refreshed

**Expected behavior**
The note name is changed accordingly.

**Screenshots**

![musescore_a4](https://user-images.githubusercontent.com/69964767/150300329-e5d7b92b-5692-4498-84cf-da49584fa0b5.PNG)
![musescore_d5_incorrect](https://user-images.githubusercontent.com/69964767/150300355-c4b9eb1e-8eee-42c0-a965-68e422dd06ad.PNG)
You can see that on the second screenshot it says A4, but it should be D5.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Note**
It's working correctly in MuseScore 3.

**Comment by cbjeukendrup** [comment]
Working on it!
