### ISSUE TITLE
[MU4 Task] [GP] Display tuning

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10333]
**Task description**
Display tuning

**Expected:**
(here Standard tuning)
![Screenshot 2022-01-19 at 23 07 56](https://user-images.githubusercontent.com/24373905/150205858-a1da3dc2-e86e-49f9-bd19-a4f96ea1d236.png)

Other example:
![Screenshot 2022-01-19 at 23 17 09](https://user-images.githubusercontent.com/24373905/150207218-da180d1e-a58c-4e5d-9d2b-b264e485f604.png)

**Comment by alexpavlov96** [comment]
will be done after design work

**Comment by Tantacrul** [comment]
GP has a feature where, if you change the tuning, those changes are automatically reflected on the score. MS4 basically needs to also have this feature. This needs to also affect actual playback too.

Bumping to 4.X and will reopen after 4.0 is released.
