### ISSUE TITLE
[MU4 Issue] "Palette Properties..." not working for several palettes

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10339]
**Describe the bug**
"Palette properties..." appears to contain no pre-filled information (I.e. "Name", "Cell size"), and settings contained therein don't affect the corresponding palette. 

Moreover, adding information to the text fields, such as "Name", does nothing.

This affects the following palettes: 
- Arpeggios & glissandi
- Breaths & pauses
- Repeats & jumps

(Interestingly, all the palettes that contain an `&` in the palette name 🤔)

**Demonstration: Correctly functioning "Palette properties" v. non-functional "Palette properties"**

![palette-properties-broken-functionality](https://user-images.githubusercontent.com/86290556/150329916-07abbb18-f92f-43b6-9af7-2744c82d1959.gif)

**Demonstration: "Name" field does nothing**
![palette-properties-2](https://user-images.githubusercontent.com/86290556/150330445-6d87eb18-a494-47d1-ae3e-1097f3f92c90.gif)

**Expected behavior**
"Palette properties" should contain the palette name and pre-filled settings for cell size. Changes to "Name" and "Cell size" text fields should update the corresponding palette as per all other (currently working) palettes. 

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1) 
 - Windows 11

**Additional context**
Relates to #10307.
If it would help, I'd be happy to test a working build that fixes this before it gets merged. This would allow us to specify what the default cell size settings should be for these palettes (I can't do it at the moment because, obviously, they don't work 😁)

**Comment by HemantAntony** [comment]
Hello the problem in this issue seems to be the `&` in the names of the affected palettes. So, when the data is sent, parseParams() tries to separate various parameters by splitting using the `&` which results in the name getting split too. So, I was wondering what the solution should be?

![image](https://user-images.githubusercontent.com/88136054/150368770-13211ef7-c1df-40dd-9f6f-cf62339d57a7.png)


The string in which split is used: `sync=true&properties={\n    "cellHeight": 28,\n    "cellWidth": 75,\n    "elementOffset": 0,\n    "name": "Repeats & jumps",\n    "paletteId": "67",\n    "scale": 0.65,\n    "showGrid": true\n}\n`

**Comment by Jojo-Schmitz** [comment]
These ampersands in Palette names are causing trouble one way or the other since ages. How about replacing them with a `+' or the word 'and'?

**Comment by HemantAntony** [comment]
> These ampersands in Palette names are causing trouble one way or the other since ages. How about replacing them with a `+' or the word 'and'?
> 
> Won't prevent a user from creating such a palette name though

That would be the easiest solution. @bkunda, what do you think?

**Comment by Jojo-Schmitz** [comment]
It'd be a half-baked solution, as a user could still created a palette with an ampersand in its name

**Comment by HemantAntony** [comment]
> It'd be a half-baked solution, as a user could still created a palette with an ampersand in its name

Maybe we allow only Alphabets and Space in Palette Names?

**Comment by HemantAntony** [comment]
It seems like Qt has a function for percent encoding: https://doc.qt.io/qt-5/qbytearray.html#toPercentEncoding. I will start working on a solution with this

**Comment by bkunda** [comment]
> > These ampersands in Palette names are causing trouble one way or the other since ages. How about replacing them with a `+' or the word 'and'?
> > Won't prevent a user from creating such a palette name though
> 
> That would be the easiest solution. @bkunda, what do you think?

If there is a solution to be found that allows the use of ampersands, then that's certainly what we should be aiming for. From a user POV, it's kind of ridiculous that inserting this character would cause some functionality to break. 

But if a quick workaround is absolutely necessary (and restoring this functionality _is_ necessary), then I would suggest only using the word "and" (and not "+"). 

We would at least rename our default palettes in this way so that at least the palette properties work. If the user decides to rename a palette with an ampersand, then that's unfortunately something they will have to deal with until we find a more permanent solution to the problem.

**Comment by HemantAntony** [comment]
> > > These ampersands in Palette names are causing trouble one way or the other since ages. How about replacing them with a `+' or the word 'and'?
> > > Won't prevent a user from creating such a palette name though
> > 
> > 
> > That would be the easiest solution. @bkunda, what do you think?
> 
> If there is a solution to be found that allows the use of ampersands, then that's certainly what we should be aiming for. From a user POV, it's kind of ridiculous that inserting this character would cause some functionality to break.
> 
> But if a quick workaround is absolutely necessary (and restoring this functionality _is_ necessary), then I would suggest only using the word "and" (and not "+").
> 
> We would at least rename our default palettes in this way so that at least the palette properties work. If the user decides to rename a palette with an ampersand, then that's unfortunately something they will have to deal with until we find a more permanent solution to the problem.

I don't think that's a problem now because I have created a PR which solved this. Also when you test it, try to break the functionality where the user can change the name of the palette themselves by using various symbols like & and +

**Comment by bkunda** [comment]
> > > > These ampersands in Palette names are causing trouble one way or the other since ages. How about replacing them with a `+' or the word 'and'?
> > > > Won't prevent a user from creating such a palette name though
> > > 
> > > 
> > > That would be the easiest solution. @bkunda, what do you think?
> > 
> > 
> > If there is a solution to be found that allows the use of ampersands, then that's certainly what we should be aiming for. From a user POV, it's kind of ridiculous that inserting this character would cause some functionality to break.
> > But if a quick workaround is absolutely necessary (and restoring this functionality _is_ necessary), then I would suggest only using the word "and" (and not "+").
> > We would at least rename our default palettes in this way so that at least the palette properties work. If the user decides to rename a palette with an ampersand, then that's unfortunately something they will have to deal with until we find a more permanent solution to the problem.
> 
> I don't think that's a problem now because I have created a PR which solved this. Also when you test it, try to break the functionality where the user can change the name of the palette themselves by using various symbols like & and +

Brilliant. Is it #10347? I'll look at it now!
