### ISSUE TITLE
[MU4 Issue] Instruments have the sound of other instruments and play the notes of other instruments (also in the mixer the assignment is wrong)

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#10336]
**Describe the bug**
When creating a new score over the classical orchestra template, the cello notes are played by the oboe and the contrabass notes are played by the horns. Cello and contrabass, on the other hand, have no sound in the mixer!

**To Reproduce**
1. Create a new score from template "classic orchestra" or open this score
[Test classic orchestral score.zip](https://github.com/musescore/MuseScore/files/7903078/Test.classic.orchestral.score.zip)

2. Playback and open the mixer
2. See there is no sound for cello and contrabass
3. Oboe and Horns instead plays the notes for cello and contrabass

**Expected behavior**
Each instrument should play the notes in its staff with the correct sound.

**Screenshots**

https://user-images.githubusercontent.com/63284090/150292821-043e304f-43c1-4472-98de-175a9735e357.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by mattblo** [comment]
Similar problems also occur when downloading and opening scores from musescore.com. 
E.g.: with "the nutcracker".
[Nutcracker_Suite_Dance_of_the_Reed_Pipes.zip](https://github.com/musescore/MuseScore/files/7903143/Nutcracker_Suite_Dance_of_the_Reed_Pipes.zip)

The strings here have no playback at all, instead the horn plays the notes of the viola... where the other instruments are played back, I cannot assign.

**Comment by Jojo-Schmitz** [comment]
See PR #9102, which, amongst other things, assigings MIDI channels to instruments in the template at hand here in this issue

**Comment by mattblo** [comment]
Ah okay good to know. Should I rather close this issue then?

**Comment by Jojo-Schmitz** [comment]
Better check whether that PR fixes the issue (so far that's just my suspicion). And let's make sure the PR gets merged ;-)

**Comment by Jojo-Schmitz** [comment]
PR got merged, please check whether it solved this issue (in the passing)

**Comment by mattblo** [comment]
> PR got merged, please check whether it solved this issue (in the passing)

As far as I could check with the artifacts, this does not solve the problem. In the Nutcracker Suite, for example, the basson still sounds like percussion or something. In a string quartet, however, the cello sounds like percussion.

**Comment by Jojo-Schmitz** [comment]
Pity. So the culprit got to be somewhere else

**Comment by DmitryArefiev** [comment]
Tested in **latest master build** on Win10, Mac12, LinuxMint 20.2 - STRINGS are sound fine (checked some orchestral templates)

Closing

@mattblo Please reopen if something still occurs with sounds. Thanks!
