### ISSUE TITLE
[MU4 Issue] More palette popup should move with MuseScore window

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#10356]
**Describe the bug**
When you click on the More button in a palette, it opens a popup. However, if you move the MuseScore window, the popup does not move with the window.

**To Reproduce**
1. Create a Score
2. Click on any palette
3. Click on 'More'
4. Move the MuseScore window
5. The popup stays in its opened position

**Expected behavior**
The popup should move with the MuseScore window

**Screenshots**

https://user-images.githubusercontent.com/88136054/150627090-1083a33b-4cde-4685-b346-c988f8ccdc07.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by Eism** [comment]
Duplicate #9867
