### ISSUE TITLE
[MU4 Issue] Drumline templates have an old version (trigger export dialog) and don't have unique names in Templates

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10351]
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**
1. Install Drumline templates from Home>Add-ons>Extensions
2. Go to New Score>Templates>Other

![Screenshot 2022-01-21 at 7 05 47 PM](https://user-images.githubusercontent.com/90187801/150572852-aaceb18f-0d9b-4784-830c-010cbd3a1c20.png)

https://user-images.githubusercontent.com/90187801/150573065-d257984a-9001-470b-9a69-e1cfa6b6b104.mp4

**Desktop:**

**Comment by RomanPudashkin** [comment]
No longer relevant, see:
https://github.com/musescore/MuseScore/pull/10487
