### ISSUE TITLE
[MU4 Issue] Crash adjusting tie of grace note to a chord

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#10361]
Due to seeing a difference of tie placement between an acciaccatura/etc to a note (personally looks better in 3.6 imo), here's an attempt to change a node position with keyboard (left-arrow after mouse selection of node), but there's an immediate crash. Sorry if this was previously logged (and lack of further details). 

Here's a screencast:

https://user-images.githubusercontent.com/7139517/150723390-adc26a24-d4de-4261-b111-a923f5e2d43c.mp4

**Comment by oktophonie** [comment]
Neither I nor @asattely can reproduce this; has it maybe been incidentally fixed in the meantime, or if not, could you perhaps supply a test file?

**Comment by worldwideweary** [comment]
Looks like it was fixed in the meantime, as I now neither receive a crash in performing the same task with a Nightly. Although, the result is slightly odd:  the alteration seems to move the tie to the original position expected in 3.6 (or pretty close to it), even though it would probably be expected to perform incremental shifts of one grip node. That is, with one left-arrow, a jump occurs on both grip-nodes:

https://user-images.githubusercontent.com/7139517/155421001-e35b87b1-8bd1-4012-81bb-b128a1275ae9.mp4

Personally, the resulting change appears more appropriate. Either way, thanks for the message + test.
