### ISSUE TITLE
[MU4 Issue] Create time signatures doesn't work

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10372]
**Describe the bug**
Creating custom time signatures via the "More" popup in the time signatures palette doesn't add the custom time signature to the palette. 

This seems like a regression, hence I'm raising it as an issue. If we can slightly tweak the UX from MS3.6, however, then that would be ideal as the way this currently works in 3.6 is problematic (no feedback is provided to user that their time signature has been created). 

I propose that, when the user clicks "Add" in the "Create time signature" dialog, the dialog will close and their custom time signature would be added to the main part of the time signature palette (not the "More" popup). 

Please see this video for further explanation: 

https://user-images.githubusercontent.com/86290556/150960298-f3b15c97-2cda-4b1f-8a98-6434f05b0243.mp4

A further bug in Windows: the "Create time signature" dialog is actually drawn behind the main MS project window, rather than in front of it: 
![Screen Recording 2022-01-25 at 09 43 51 57 PM](https://user-images.githubusercontent.com/86290556/150963067-591b657f-4289-4063-ae43-c382abd4c466.gif)

**Expected behavior**
Clicking `Add` in the "Create time signature" dialog should close the dialog and add the custom time signature to the "time signature" palette (Main section, not "More" popup).
"Create time signature" dialog should be drawn in front of main MS project window (currently only a problem in Windows as far as I can tell).

**Desktop (please complete the following information):**
 - MacOS 12.1 (M1)
 - Windows 11

**Additional info**
In case it's relevant, I am using an external monitor with my Windows laptop.
This issue is partly related to a broader palette tidy-up, which I have raised in #10307

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10419

Related issues are logged separately #10423 #10424 

Closing
