### ISSUE TITLE
[MU4 Task] [GP] Display percussion correctly

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10379]
**Task description**
Display percussion correctly

Problems:
1. Crashes (49 and 57) are swapped
**Current:**
![Screenshot 2022-01-25 at 23 22 11](https://user-images.githubusercontent.com/24373905/151053458-bc6302e9-1dfd-4aaf-b5ff-f5b13a23f9c8.png)

**Expected:**
![Screenshot 2022-01-25 at 23 23 05](https://user-images.githubusercontent.com/24373905/151053596-0954546d-effb-405d-abe6-1b9bdf187e1c.png)

2. China (52) has no 'roof'
**Current:**
![Screenshot 2022-01-25 at 23 24 28](https://user-images.githubusercontent.com/24373905/151053783-949201ba-72f7-480e-9618-cda7819421dd.png)

**Expected:**
![Screenshot 2022-01-25 at 23 24 00](https://user-images.githubusercontent.com/24373905/151053722-d04a0553-b49b-4a09-96b6-3b066d4bf5a5.png)

3. Ride edge (59) is wrong (looks the same as ride bell 53)
**Current:**
![Screenshot 2022-01-25 at 23 25 25](https://user-images.githubusercontent.com/24373905/151053937-e0f8cd08-b209-448c-b075-91b162c99b13.png)

**Expected:**
![Screenshot 2022-01-25 at 23 25 03](https://user-images.githubusercontent.com/24373905/151053874-948a9770-1fb7-485c-8d15-3ba91783551f.png)

**Comment by alexpavlov96** [comment]
waiting for https://github.com/musescore/MuseScore/issues/10684 to implement "China (52)"

**Comment by boryskuzmenko** [comment]
@alexpavlov96 Please, pay attention, that Ride bell and Ride (edge) note icons is not are not fixed:
![Capture 2022-04-18_08-03-29_PM](https://user-images.githubusercontent.com/101250347/163846100-1264ecd4-8882-45f0-a98a-6eceb0e4506e.png)
![Capture 2022-04-18_08-01-32_PM](https://user-images.githubusercontent.com/101250347/163846101-6298fac4-6413-473b-b901-5f78f7f77539.png)

**Comment by Tantacrul** [comment]
It's not going to be possible to coordinate this without someone overlooking it. @lengthwave - I'd suggest you keep an eye on these PR's. @alexpavlov96 - you should check with @lengthwave to make sure we don't alter MuseScore to use bad defaults.
