### ISSUE TITLE
[MU4 Issue] Create Key Signatures does not work

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#10389]
**Describe the bug**
There are mainly two bugs here. One is when opened, Key Signature Dialog goes behind MuseScore. The other one is that clicking `Add` does not work. 

**To Reproduce**
1. Click on Key Signatures Palette
2. Click on More
3. Click on Create Key Signature
4. It goes behind MuseScore
5. Now, on clicking the dialog via the taskbar, create a key signature
6. Then, Click Add, nothing happens

**Expected behavior**
The Dialog should not go behind MuseScore and the dialog should work.

**Screenshots**

https://user-images.githubusercontent.com/88136054/151335518-0294676b-7125-4709-8d7c-2cccdffda76d.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
This is slightly related to #10372. That issue has the same bugs

**Comment by HemantAntony** [comment]
I am currently working on rewriting this in qml

**Comment by sammik** [comment]
Please, have a look into slight enhancement (add arrow keys navigation) as described in [https://musescore.org/en/node/328853](https://musescore.org/en/node/328853)
Thank You

**Comment by HemantAntony** [comment]
> Please, have a look into slight enhancement (add arrow keys navigation) as described in https://musescore.org/en/node/328853 Thank You

Hello, I read your feature request. I think the idea is great. But, I am not sure if I will be able to implement this. However, I will try. Thank you!

**Comment by vpereverzev** [comment]
> > Please, have a look into slight enhancement (add arrow keys navigation) as described in https://musescore.org/en/node/328853 Thank You
> 
> Hello, I read your feature request. I think the idea is great. But, I am not sure if I will be able to implement this in MU4. However, I will try. Thank you!

Make sure that you don't do double work

https://github.com/musescore/MuseScore/issues/9618#issuecomment-1010248494

**Comment by HemantAntony** [comment]
> > > Please, have a look into slight enhancement (add arrow keys navigation) as described in https://musescore.org/en/node/328853 Thank You
> > 
> > 
> > Hello, I read your feature request. I think the idea is great. But, I am not sure if I will be able to implement this in MU4. However, I will try. Thank you!
> 
> Make sure that you don't do double work
> 
> [#9618 (comment)](https://github.com/musescore/MuseScore/issues/9618#issuecomment-1010248494)

That's Time Signatures. Key Signatures don't work also

**Comment by HemantAntony** [comment]
> See also: #10372

That's Time Signatures. Key Signatures Dialog face a similar problem.
