### ISSUE TITLE
[MU4 Issue] Navigation doesn't work (focus is lost) in New Score window if it's opened as new copy of MU

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10391]
**To Reproduce**
1. Run MU
2. Open a score
3. Hit **Cmd+N** to open New Score wizard (or navigate to Home>Score>New Score)
4. Try to navigate with Tab within New Score window - focus is lost (see video)

https://user-images.githubusercontent.com/90187801/151376729-56c5bd21-5085-4110-96c1-72ef9fcd957c.mov

**Desktop:**
 - OS: Mac12 (Mac only)

**Comment by Tantacrul** [comment]
This is now working for me. @DmitryArefiev - can you confirm?

**Comment by DmitryArefiev** [comment]
@Tantacrul Yes, doesn't occur on my side as well now (latest master, Mac12.3). Closing

Thanks for rechecking!
