### ISSUE TITLE
Creating custom key signatures dialog is broken and missing parts (in both Palettes and Master Palette)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10405]
**Describe the bug**
See video

https://user-images.githubusercontent.com/21022311/151660118-b0f79651-b062-425d-aace-6b4cc9e44af3.mov

**Comment by HemantAntony** [comment]
This is related to #10389. Your issue seems to have reported more bugs (There is a Windows Bug too). Should I close my issue?
