### ISSUE TITLE
ALSA sequencer device leaks when toggling MIDI ON/OFF

### ISSUE THREAD

**Issue by hselasky** [musescore/MuseScore#10407]
**Describe the bug**
ALSA sequencer device leaks when toggling MIDI ON/OFF

**To Reproduce**
1. Build musescore with ALSA MIDI support enabled.
2. Click on the MIDI DIN-5 plug ICON four times.
3. Run "aconnect -l"
4. Verify that multiple ALSA MIDI instances are registered.

**Expected behavior**
At any time only one instance should be registered.

**Screenshots**
Not applicable.

**Platform information**
 - OS: FreeBSD (MuseScore 3.6.1)

**Additional context**
Patches are attached:
1. [patch-audio_drivers_alsa.cpp.txt](https://github.com/musescore/MuseScore/files/7964105/patch-audio_drivers_alsa.cpp.txt)
2. [patch-audio_drivers_mididriver.cpp.txt](https://github.com/musescore/MuseScore/files/7964106/patch-audio_drivers_mididriver.cpp.txt)
3. [patch-audio_drivers_alsamidi.h.txt](https://github.com/musescore/MuseScore/files/7964880/patch-audio_drivers_alsamidi.h.txt)

**Comment by hselasky** [comment]
@probonopd : FYI

**Comment by hselasky** [comment]
Looks like this is fixed in MU4.

**Comment by Jojo-Schmitz** [comment]
Guess I'll add that fix to PR #9000 then.

**Comment by Jojo-Schmitz** [comment]
Please check the GitHub CI artifact from PR #9000, I can't, don't have a LInux box to test

**Comment by hselasky** [comment]
@Jojo-Schmitz : Looks good!

**Comment by hselasky** [comment]
2234 hans         39  20    0   780M   443M select   1   0:53  98.56% mscore

Looks like a polling bug somewhere.

**Comment by Jojo-Schmitz** [comment]
Where, in the artifact from PR #9000, in 3.6.x or in master?

**Comment by hselasky** [comment]
@Jojo-Schmitz : This is something specific to FreeBSD and nothing to worry about for MuseScore.

**Comment by Jojo-Schmitz** [comment]
I see, thanks

**Comment by Tantacrul** [comment]
We won't be making any fixes for 3.x.

It would be great to test this again on MS4. Closing for now. Let me know if there is a reason to reopen.

**Comment by probonopd** [comment]
MuseScore in FreeBSD is still 3.x...
https://www.freshports.org/audio/musescore/

**Comment by RobFog** [comment]
Yes, MuseScore 4 is currently in development.
