### ISSUE TITLE
[MU4 Issue] MU4 crashes when creating a new score

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#10418]
**Describe the bug**
Any attempt to create a new score results in a crash.

**To Reproduce**
1. Open the application
2. Click on "New score"
3. Add some instruments.
4. Click on "Done"

Now the application crashes.

**Expected behavior**
Able to create a score without a crash.

**Screenshots**
N.a.

**Platform information**
 - OS: Linux

**Additional context**
1. MU4 also crashes when trying to create a new score from a template. As a matter of fact, is crashes already when clicking on "Choose from template"
2. It is possible to add instruments to an existing score.

**Comment by DmitryArefiev** [comment]
Can reproduce on **Win**, **Mac** as well. Thanks for catching this!

**Comment by njvdberg** [comment]
Seems to be caused by PR #10414

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
