### ISSUE TITLE
[MU4 Issue] Clicking Add in Palettes 'More' popup should close the dialog

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10424]
Clicking Add in Palettes 'More' popup should close the dialog (KS, TS, Dynamics etc.)

https://user-images.githubusercontent.com/90187801/152007624-479862f1-6140-426a-9567-3fecb1dd7d3d.mp4

**Platform information**
macOS, Windows, Linux

**Comment by Tantacrul** [comment]
I think it should work exactly as it does in that animation. It is useful to keep the 'More' popup open so you can understand that you have 'transferred' items into the main palette.

I do think that creating a new Key sig **_should_** close the 'More' popup though. I don't think this is inconsistent.

**Comment by DmitryArefiev** [comment]
> It is useful to keep the 'More' popup open when adding things to the main palette (as you did with dynamics) so you can understand that you have 'transferred' items from one to the other.

Yeah, make sense. Thanks! Let's close it (Works as intended)
