### ISSUE TITLE
[MU4 Issue] Fretboard diagram chord symbol is doubled in edit mode

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10435]
https://user-images.githubusercontent.com/90187801/152333863-add047ae-7675-4f48-bffb-0122f95578f5.mp4

**To Reproduce**
1. Add a fretboard diagram to the note from Palettes
2. Edit the chord symbol

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by Tantacrul** [comment]
Confirmed on todays' build.
<img width="193" alt="image" src="https://user-images.githubusercontent.com/21022311/171036956-e580ee88-766c-4f81-a009-3c1487e63598.png">

**Comment by DmitryArefiev** [comment]
Fixed in #14312
