### ISSUE TITLE
Properties (Inspector) Regression: Changing a parameter in a popup now also closes that popup

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10430]
**Describe the bug**
This was working in MS4 before so I suspect it is a relatively recent regression. If I select a range of elements and then open a popup, any change to a parameter in that popup will also immediately close it. Please see the attached video for a precise demonstration:

**Watch video**

https://user-images.githubusercontent.com/21022311/152186479-533199c0-bfdd-46a9-81cf-fa8232269e1b.mov

**Comment by Tantacrul** [comment]
@DmitryArefiev - don't know when this regression happened. I thought I'd tag you because I've never properly taken you through the concept for how popups are handled in the Properties panel before.

**Comment by DmitryArefiev** [comment]
@Tantacrul - it's should fixed by #10417 and will be in master when it's ready (~30min)

**Comment by Tantacrul** [comment]
Great stuff!
