### ISSUE TITLE
[MU4 Task] Implement slur properties in Inspector/Properties

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10448]
**Task description**
Settings for slurs are yet to be implemented in MS4. These include: 
- Line style (Continuous, Wide Dashed, Dashed, Dotted)
- Line position (Above, Below)

For now, we aim to simply reinstate functionality from MS3.6.

Please note: new icon for "Wide Dashed" in musescoreicon at U+F434.

The new design for this can be found in Figma here: https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/Musescore-Notation-App-MASTER?node-id=22155%3A686227

<img width="292" alt="SLURS_POPUP" src="https://user-images.githubusercontent.com/86290556/152532696-f943cc27-6c39-4d6b-9a94-915f1357340c.png">

Many thanks!
Bradley

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by DmitryArefiev** [comment]
@bkunda Hello! How about to change "Slur position" text to "Position"?

 As we found with @boryskuzmenko, other lines have only "Position" in the Inspector:

https://user-images.githubusercontent.com/90187801/159474258-31d7e1f1-5fb5-446f-aa45-1e4ac25ed929.mp4

Thanks!

**Comment by bkunda** [comment]
> @bkunda Hello! How about to change "Slur position" text to "Position"?
> 
> As we found with @boryskuzmenko, other lines have only "Position" in the Inspector:
> 
>  bandicam.2022-03-22.13-39-48-874.mp4 
> 
> Thanks!

Yes this makes perfect sense. Let's go with "Position" for slurs too then.
Good spot @boryskuzmenko and @DmitryArefiev!

**Comment by DmitryArefiev** [comment]
Cool! Thanks!
