### ISSUE TITLE
Context menu no longer has 'Remove measures' option. We should re-add it with some UX cleanup.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10440]
**Describe the bug**
Removing measures is still quite hard in MS4. One method from MS3 was to right click on selected measures and opt to 'remove' them. This was always a little tough to find because there is another option called **'Delete'** which seems much more likely to fulfil that function.

I'm guessing someone assumed these two functions were duplicating functionality and removed one of them.

![image](https://user-images.githubusercontent.com/21022311/152381654-1a363008-c498-477d-974f-252ba42266a0.png)

**Expected behavior**
We need to do two things:

1. We need to add a 'Delete measures' option (and still use the delete icon) - this should be tied to the existing shortcut: Ctrl (command) +backspace
2. Under that we put the existing 'Delete' feature but rename it to 'Clear measures' (and still use the delete symbol)

**Additional context**

**Comment by RobFog** [comment]
>This was always a little tough to find because there is another option called 'Delete' which seems much more likely to fulfil that function.

Yes, I do think this is something many first-time users trip over. I know I did years ago. :-)

**Comment by iamjithinjohn** [comment]
I'm trying to solve this, and it is now behaving as what @Tantacrul mentioned in the Expected behaviour, but what if I just click a note and I want to delete the note, not the whole measure, then will the image shown makes any confusion for the user?
![image](https://user-images.githubusercontent.com/73242397/152679937-4b117a99-9197-4158-927d-5a253ceff932.png)

**Comment by Tantacrul** [comment]
Good point. I actually think that the options should be different when you right click on elements like this:

![image](https://user-images.githubusercontent.com/21022311/152687768-98718ca4-aab8-48a9-bbd8-bd56d392ed3b.png)

I think you should just have a 'delete' option that removes them.

---

However, if you right click on the bar itself, then the options should be 'Delete measures' / 'Clear measures'

**Comment by sammik** [comment]
I think, contex menu is context dependent, so it is different, when is selected single note, different, if is selected measure, ...
But every different menus have shared "copy paste" block / list, which cantains "Cut, Copy, Paste, Swap with clipboard, Delete"

1) should Measure Context menu share this block too (but modified), or can have its own ad hoc items list? (it is question more for porgramers, not for designers)

2) separators - where separators should be?

3) icon - "Range delete" doesnt have icon assigned. Should be icon set directly to it (like it is for Delete, ...), or better to be able to set custom icon, like it is possible to set custom title for menu item?

**Comment by Tantacrul** [comment]
I have two minor changes (now that I see it). The first two look good.

For the final image, I'd put 'delete measures' above 'clear measures' and I'd remove the trash can icon from 'clear measures' too!

Thanks!

**Comment by duanjr** [comment]
oops! I didn't notice @iamjithinjohn  is working on this, I noticed this issue this morning and I found no pr is linked to this issue (just looking from outside), so I just worked on it and notice discussions above just after my pr. Really sorry for my mistake.

**Comment by Tantacrul** [comment]
@RomanPudashkin - don't know if this can get merged or not soon. It solves a pretty bad omission from MS3.6

**Comment by Tantacrul** [comment]
(We can leave until Beta if that is the preferred option. I'll leave it to you)
