### ISSUE TITLE
[MU4 Issue] Master channel doesn't handle plugins well

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#10450]
**Describe the bug**
It seems the Master channel handles Audio FX plugins differently than any normal instrument channel. In this case, it won't load the VST UI. 

https://user-images.githubusercontent.com/71656189/152535993-ff8e37d0-34fe-4e71-8f60-00671d34d876.mp4

**Platform information**
 - OS: Windows (mostly likely Mac too)

**Comment by jessjwilliamson** [comment]
@mattblo

**Comment by mattblo** [comment]
> @mattblo

Ah yes! Thank you!

**Comment by DmitryArefiev** [comment]
Fixed in #10911
