### ISSUE TITLE
[MU4 Task] Improvements to "layout" palette

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10451]
**Task description**
This task aims to improve the usability and visual aesthetic of the layout palette.

The key tasks are:
1. Render all icons in the same font colour (Font_Primary_Colour)
2. ~~Implement scalability of icons generated from musescoreicon~~ (FIXED ELSEWHERE)
3. ~~Replace icon "Insert one measure before selection" with new icon U+F432~~ (FIXED ELSEWHERE)
4. Replace icon "Staff type change" with new icon U+F433
5. Replace current tooltip for "Group measures" with "Keep measures together"

<img width="1361" alt="Screenshot 2022-02-05 at 12 31 42 am" src="https://user-images.githubusercontent.com/86290556/152537415-81a82c94-1363-4dcf-85dc-8187dbfb6ae8.png">

Thanks!

**Comment by duanjr** [comment]
Looks this issue is not active.
I've done some job research.
My current palette looks like this:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/71218187/158515491-3f0a4d6c-bb90-4e3e-a02e-d40d3d660999.png">
One thing to notice is that "Staff type change" is not an anction, it needs more change to show U+F433 than just change the icon code, which may not worth it.(looks we only set icon for actions)

**Comment by HemantAntony** [comment]
> Looks this issue is not active. I've done some job research. My current palette looks like this: <img alt="image" width="292" src="https://user-images.githubusercontent.com/71218187/158515491-3f0a4d6c-bb90-4e3e-a02e-d40d3d660999.png"> One thing to notice is that "Staff type change" is not an anction, it needs more change to show U+F433 than just change the icon code, which may not worth it.(looks we only set icon for actions)

Yeah, I had tried to change that icon. I don't think its actually displayed as an icon. It seems like its being "drawn" or "painted" with lines and not as a pre-existing icon. I remember the code for that being in engraving folder in `stafftypechange.cpp`. Maybe the `draw()` function. Its not direct like the other icons

**Comment by duanjr** [comment]
> > Looks this issue is not active. I've done some job research. My current palette looks like this: <img alt="image" width="292" src="https://user-images.githubusercontent.com/71218187/158515491-3f0a4d6c-bb90-4e3e-a02e-d40d3d660999.png"> One thing to notice is that "Staff type change" is not an anction, it needs more change to show U+F433 than just change the icon code, which may not worth it.(looks we only set icon for actions)
> 
> Yeah, I had tried to change that icon. I don't think its actually displayed as an icon. It seems like its being "drawn" or "painted" with lines and not as a pre-existing icon. I remember the code for that being in engraving folder in `stafftypechange.cpp`. Maybe the `draw()` function. Its not direct like the other icons

Yeah, and those 'break' and 'spacer' are neither icons. You remember right about the code, I rewrite `draw()` function, but disrupted part of the existing code structure about painting

**Comment by duanjr** [comment]
I suggest not using U+F433 or we can "draw" a new icon with painter for consistency with existing code.(I can't find a palette cell which is not action but uses icons)

**Comment by HemantAntony** [comment]
> > > Looks this issue is not active. I've done some job research. My current palette looks like this: <img alt="image" width="292" src="https://user-images.githubusercontent.com/71218187/158515491-3f0a4d6c-bb90-4e3e-a02e-d40d3d660999.png"> One thing to notice is that "Staff type change" is not an anction, it needs more change to show U+F433 than just change the icon code, which may not worth it.(looks we only set icon for actions)
> > 
> > 
> > Yeah, I had tried to change that icon. I don't think its actually displayed as an icon. It seems like its being "drawn" or "painted" with lines and not as a pre-existing icon. I remember the code for that being in engraving folder in `stafftypechange.cpp`. Maybe the `draw()` function. Its not direct like the other icons
> 
> Yeah, and those 'break' and 'spacer' are neither icons. You remember right about the code, I rewrite `draw()` function, but disrupted part of the existing code structure about painting

I'm not really sure about this, but I think you shouldn't just change the "icon" by rewriting the `draw()` because unless I am mistaken that function gets called when you add a StaffTypeChange to the score

**Comment by bkunda** [comment]
@vpereverzev @igorkorsukov @Eism can one of you please weigh in on this when you get a minute? I seem to remember a discussion about leaving some of these as `musescoreicon` and making them scalable like the "drawn" icons. I don't have an opinion about the best way forward here, but I think you guys should perhaps advise what the best path is for this issue 🙂

**Comment by duanjr** [comment]
> I'm not really sure about this, but I think you shouldn't just change the "icon" by rewriting the `draw()` because unless I am mistaken that function gets called when you add a StaffTypeChange to the score.

Yes and it will be about only half the size as expected. And more change is needed to fix this.

**Comment by HemantAntony** [comment]
@bkunda I've managed to fix this after a couple of months :) Check #12865

**Comment by jeetee** [comment]
Addendum to this task by forum confusion reports.
It seems that many users expect the "keep together" element to work as a "force and squeeze and magic together" element rather than what it does.

I propose to have this, due to its more niche and specific use case, hidden behind the "more" button of the layout palette by default.

**Comment by oMrSmith** [comment]
Maybe so?

![Example](https://user-images.githubusercontent.com/78870770/208669417-c25bed7a-1222-41e0-90ac-51b184a86705.JPG)
