### ISSUE TITLE
[MU4 Issue] "Add Palettes" popup dialog close when the tooltip show

### ISSUE THREAD

**Issue by Fince10086** [musescore/MuseScore#10463]
**Describe the bug**
Add Palettes popup dialog close when the tooltip show

**To Reproduce**
1. Create a new score
1. Go to 'Palettes'
2. Click on 'Add Palette'
3. Let the mouse over any "+" button and wait

**Expected behavior**
the tooltip show with no other actions.

**Screenshots**

https://user-images.githubusercontent.com/87692117/152667803-a47dd659-0c51-49fa-a7a2-95e6602594ae.mp4

**Platform information**
 - OS: Windows 11

**Comment by DmitryArefiev** [comment]
Fixed in #10837
