### ISSUE TITLE
[MU4 Issue] [Accessibility] [Linux] Text characters are typed twice when screen reader is running

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#10467]
**Describe the bug**
When typing text in the score (e.g. staff text, tempos, frame text, etc.) each character appears twice. This only occurs when the screen reader is running, and it only occurs in the score (it doesn't happen in search boxes or text fields in the New Score Wizard).

![image](https://user-images.githubusercontent.com/11011881/152682939-8a32c254-530b-4d2d-a233-ad67f394df3b.png)

**To Reproduce**

1. Start Orca screen reader running before you launch MuseScore.
2. Launch MuseScore and create a blank score.
3. Add staff text. Each character you type will appear twice on the screen.
4. Quit the screen reader.
5. Add some more staff text. Characters now appear once per keystroke as expected.

**Expected behavior**
Typed characters should appear once per keystroke.

**Platform information**
 - OS: Linux (Ubuntu 20.04 x86_64) running the built-in screen reader (Orca)

**Comment by shoogle** [comment]
Test comment

**Comment by DmitryArefiev** [comment]
Tested on LinuxMint 20.2 (Win10, Mac12) - FIXED in #10627
