### ISSUE TITLE
[MU4 Issue] Many UI elements don't respond to keyboard input

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#10460]
I am finding that very few UI elements that traditionally respond to keyboard input work as expected in MU4 - spinboxes, dropdown lists, defaults button in dialogs, etc.  So for example

Spinbox issue
1) go to Edit / Preferences
2) click within the "Auto save every" spinbox
3) press Up arrow to increase
Result: spinbox loses focus, no change is applied

Dropdown issue
1) select any text element in a score
2) click in the Font dropdown
3) type either Z or similar to move to the end of the list of fonts
Result so far: dropdown repositions to show fonts starting with that letter, as expect
4) use cursor to select one of the fonts shown
Result: dropdown closes, no change is applied

Note that if you type a letter A-G, instead of repositioning the dropdown, a note is entered into the score.

Default button issue:
1) File / Open
2) click any score in the list
3) press Enter to open the select score
Result: nothing happens

Checkbox issue:
1) Edit / Preferences
2) click the checkbox for "Auto save every" to disable it
3) press Space to toggle it back
Result: nothing happens

and so on.

I find I can operate at least some controls by keyboard *if* I don't touch the mouse at all during the process.  Basically, if the element receives focus via the keyboard, then the keyboard often works to activate it.  So the good news is, blind users who literally use the keyboard only may not see many problems here (although I can't get spinboxes to work no matter what).  But for most of us who use some combination of clicking and keyboard, it's not good at all.

**Comment by MarcSabatella** [comment]
Is there any way this could be bumped in priority to be dealt with before alpha?  In more regular use of MU4 over the past few weeks, this is by far the single biggest usability issue I encounter, and a much bigger regression over MU3 than any single missing feature.

**Comment by Eism** [comment]
@MarcSabatella 
I think it will be fixed in #9839
And I'll start fixing it soon

**Comment by MarcSabatella** [comment]
Fantastic, thanks!

**Comment by Eism** [comment]
@MarcSabatella 

>  Default button issue:
> 
> File / Open
> click any score in the list
> press Enter to open the select score
> Result: nothing happens

Where is "File / Open"?

**Comment by MarcSabatella** [comment]
I mean the File menu, then Open.  It’s really the same for most controls throughout the UI - keyboard just doesn’t work.

**Comment by Eism** [comment]
But File->Open launches the system's standard file open dialog, we can't change the behaviour of this dialog.
What platform do you have this behaviour on?

**Comment by MarcSabatella** [comment]
Linux, running on my Chromebook. It's not a standard dialog at all, I've never seen this before - looks like MuseScore's own color scheme, icons, etc.  And I've never encountered another file dialog I can't work via keyboard.

But again, that's just one of dozens of examples.  Basically, hardly any controls work via keyboard after being activated via click, as they don't seem to accept focus the way they should.  In Qt, this was, I think, called "StrongFocus", but I assume there is something similar that needs to be enabled for QML.

**Comment by Eism** [comment]
I have implemented the start of navigation after clicking on the component. It remains to implement for dropdown, spinbox.

To fix the rest of the places where the navigation doesn't work properly, I need to know the exact places. (It would be cool if you provide a video or a screenshot)

There will be a pull request coming soon, where you can test the navigation and suggest places for improvement.

https://user-images.githubusercontent.com/10116828/163318588-3bb37ff1-4b77-47f9-905c-3743b11590f4.mov

**Comment by Eism** [comment]
> Linux, running on my Chromebook. It's not a standard dialog at all, I've never seen this before - looks like MuseScore's own color scheme, icons, etc. And I've never encountered another file dialog I can't work via keyboard.

Do you mean this dialog? 

https://user-images.githubusercontent.com/10116828/163320064-08bb99fe-afc3-4f46-b8f0-79ba70f71662.mp4

**Comment by MarcSabatella** [comment]
No, I mean the File / Open dialog.  On my system it looks like this:

![image](https://user-images.githubusercontent.com/1799936/163507552-ffb7df1f-58d5-4391-955a-5d63af7d71e4.png)

Meanwhile, it seems this problem has also been reproduced and is somewhat different than it first appeared, see https://github.com/musescore/MuseScore/issues/11193.  Keystrokes entered into this dialog get passed to the score, I can confirm.

**Comment by llui85** [comment]
> Do you mean this dialog?

No, that's the GTK file chooser. This is the Qt file picker (see #10836).

**Comment by MarcSabatella** [comment]
> I have implemented the start of navigation after clicking on the component. It remains to implement for dropdown, spinbox.
> 
> To fix the rest of the places where the navigation doesn't work properly, I need to know the exact places. (It would be cool if you provide a video or a screenshot)

Excellent, looking forward to it!  The places I notice it are primarily spinboxes and drop down lists, and mostly in either the Properties window or Preferences window.

The lack of keyboard control for spinboxes in Properties is the most painful by far.  But, it's also crucial for dropdowns such as the font selectors for text elements.

So, spinboxes and dropdowns in Properties and Preferences are the ones I notice over and over.  Toggle buttons don't necessarily *have* to take keyboard focus, there was some debate about this on Discord a while back.  Not a big deal to me because I almost never would toggle a button by mouse then immediately toggle it back by keyboard.

Besides that, the Instruments window suffers the same problem.  Click an instrument or staff, then try navigating up or down - no dice.

Lots of other dialogs *do* work, though, like Style, Tranpose, Measure Properties, and Staff Properties.  It does seem to be mainly in Preferences, Properties, Instruments, and file dialogs where there keyboard doesn't work.  It's pretty much all controls within those windows, though.

I'll keep my eye to see if I can find others.

**Comment by Eism** [comment]
@MarcSabatella 
Please check this PR https://github.com/musescore/MuseScore/pull/11233
I partially fixed, it remains to fix dropdowns, will be in next PR

**Comment by Tantacrul** [comment]
I'm closing this because it is several issues joined together under a similar theme and I understand a few are fixed. Each instance of a shortcut not working should be logged individually.

**Comment by MarcSabatella** [comment]
Indeed, each of the individual cases I had noticed before seem fixed at this point, except the file dialog, which I gather is a known separate issue for Linux only involving native vs Qt dialogs.

I'll resubmit separate issues for any other controls I find that still don't work.
