### ISSUE TITLE
[MU4 Issue] Cannot delete bars with Ctrl+Del in Windows

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#10476]
**Describe the bug**
Ctrl+Backspace will delete a selected bar (or bars), but Ctrl+Delete has no effect.

**To Reproduce**
1. Select an entire bar, or multiple bars
2. Press Ctrl+Del
3. (watch as nothing happens)

**Expected behavior**
Ctrl+Delete should work identically to Ctrl+Backspace. (I assume that Delete and Backspace should be interchangeable in all contexts?)

**Platform information**
 - OS: Windows 11
 (Reliable Sources tell me that Cmd+Delete and Cmd+Backspace work identically on Mac, as they should)

**Comment by MarcSabatella** [comment]
I agree Ctrl+Delete is the expected shortcut here.  But just one minor point of clarification - for historical reasons, these are usually independent shortcuts, and in note input mode specifically, they do different things.  Delete is delete, Backspace has generally been an alias for undo.  Not saying this should necessarily be taken forward, but probably we should take a look at the bigger picture here.  I suspect that only keyboards designed for Windows typically even have these as independent keys, and on macOS specifically I think the shortcuts have traditionally been customized (by us) to not require Fn activate the Delete functionality, but when using keyboards that lack independent Backspace and Delete keys on Windows or Linux, results can be unexpected at times.

**Comment by Kissh12** [comment]
heyy, may I work on this?

**Comment by oktophonie** [comment]
I don't see why not!

**Comment by VanSHOE** [comment]
@Kissh12 Could you confirm if you are still working on this?

**Comment by Kissh12** [comment]
> @Kissh12 Could you confirm if you are still working on this?
> 
> Edit: For some reason, I am unable to reproduce the issue at all Both Ctrl+Del and Ctrl+Backspace seem to be deleting the bars for me

yes yes, I am working on it

**Comment by Kissh12** [comment]
> @Kissh12 Could you confirm if you are still working on this?
> 
> Edit: For some reason, I am unable to reproduce the issue at all Both Ctrl+Del and Ctrl+Backspace seem to be deleting the bars for me

can you help me a little please with this problem, as I am new to open source contributions.

**Comment by VanSHOE** [comment]
> > @Kissh12 Could you confirm if you are still working on this?
> > Edit: For some reason, I am unable to reproduce the issue at all Both Ctrl+Del and Ctrl+Backspace seem to be deleting the bars for me
> 
> can you help me a little please with this problem, as I am new to open source contributions.

I would absolutely love to but I am unable to reproduce the problem itself :(

**Comment by Kissh12** [comment]
> > > @Kissh12 Could you confirm if you are still working on this?
> > > Edit: For some reason, I am unable to reproduce the issue at all Both Ctrl+Del and Ctrl+Backspace seem to be deleting the bars for me
> > 
> > 
> > can you help me a little please with this problem, as I am new to open source contributions.
> 
> I would absolutely love to but I am unable to reproduce the problem itself :(

ohh, so what should I do now?? Also, I am looking forward to contributing with musescore in gsoc, can you please guide me on that and tell me a platform to connect and learn further from you? It would be my pleasure sir

**Comment by VanSHOE** [comment]
@Kissh12 Hey! I am also just a contributor like you, I suggest you join MuseScore's server to communicate with plethora of people (including me) there! https://discord.gg/gnpWDhQw

**Comment by Kissh12** [comment]
> @Kissh12 Hey! I am also just a contributor like you, I suggest you join MuseScore's server to communicate with plethora of people (including me) there! https://discord.gg/gnpWDhQw

thanks a lot

**Comment by Tantacrul** [comment]
Any movement on this?

**Comment by GargDivanshu** [comment]
Hey if the issue was not resolved can you assign it to me ? I will be glad to work on it.

**Comment by shoogle** [comment]
@GargDivanshu, feel free, assuming this bug is still active? Perhaps someone on Windows can confirm?

The basic idea is that we want the <kbd>Delete</kbd> and <kbd>Backspace</kbd> keys to be equivalent except when editing text. This should mean looking for shortcuts involving one of those keys in [shortcuts.xml](https://github.com/musescore/MuseScore/tree/master/src/framework/shortcuts/data) and adding the other key as an alternative combination. However, it looks like that has [already been done](https://github.com/musescore/MuseScore/blob/ef951993a7a425bd6db52c1990f6925c7d28ca4c/src/framework/shortcuts/data/shortcuts.xml#L523-L537) in several places, so either the bug is fixed or there's an underlying problem that needs to be resolved.

**Comment by poypoyan** [comment]
Just built the current master branch in Windows (10) at time of this writing, and I cannot reproduce the bug anymore; all Ctrl+Del, Ctrl+Backspace, Ctrl+Shift+Del, and Ctrl+Shift+Backspace works for their function in shortcuts.xml

**Comment by oktophonie** [comment]
Just checked on Windows and Linux now, and indeed this appears to have been fixed somewhere along the way.
