### ISSUE TITLE
[MU4 Issue] Parts always stay opened as tabs

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10478]
**To Reproduce**
1. Open score
2. Open some parts 
3. Close parts
4. Save and close score
5. Reopen score - **Parts are still opened as tabs**

https://user-images.githubusercontent.com/90187801/152791974-8a2b7f78-b0a9-4bfa-8f34-1570fe4050b8.mp4

**Expected result**
Score should save the state how many tabs/parts (and which parts) are opened

**Platform information**
macOS, Windows, Linux

**Comment by sammik** [comment]
Also, parts stay open, even if user removes instruments from score.

![score-parts-bug](https://user-images.githubusercontent.com/1646034/153610483-34a3795c-a08c-4243-b617-25f7d814469c.gif)

**Comment by cbjeukendrup** [comment]
> Also, parts stay open, even if user removes instruments from score.

I think that's basically fine; then the parts that contained only those instruments become just empty parts. Note that these "parts" (in the code they are called `Excerpts`) are different things than "Instruments" in the Instruments panel. There is no 1:1 relation between parts (`Excerpts`) and instruments, so it is not self-evident that parts should be deleted and closed when instruments are deleted.

(See #10128 for explanation of the terminology.)

**Comment by sammik** [comment]
> it is not self-evident that parts should be deleted and closed when instruments are deleted.

OK, that makes sense. Than why parts are deleted, if they are not already open?

![Score-parts](https://user-images.githubusercontent.com/1646034/153714815-364c34b0-a25a-41be-9e2d-6ccc0b6e0545.gif)

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10572
