### ISSUE TITLE
[MU4 Issue] Mixer and timeline should be tabbed by default, and height adjustment interaction needs fixing

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10477]
**Describe the bug**
Opening the timeline before the mixer stacks the two panels rather than tabbing them together. 
There is also some glitchy interaction when resizing these panels vertically. 

See this video:
(N.B: In the video, when I say "docked" by default, I actually mean "tabbed". Docking is already working as default behaviour). 
https://www.dropbox.com/s/fx3jlv5ny2ewfwz/mixer-timeline-docking-issue.mov?dl=0

**Expected behavior**
1. Mixer and timeline should be tabbed by default when both are opened (regardless of the order in which they are opened)
2. Vertical height of these panels when tabbed should be the same as that of the mixer by default (when opened by itself)
3. The user should be able to change the height of the tabbed panels up to the maximum value currently specified for the mixer, and without any glitches.

**Platform information**
 - MacOS 12.1 (M1)
 - Windows 11

**Additional context**
Relates to #9241

**Comment by DmitryArefiev** [comment]
Fixed in #10874

**Comment by DmitryArefiev** [comment]
@bkunda It seems to be fine but can you check it briefly on 1 OS please? (in PRs build or later in master)

Thank you!

**Comment by bkunda** [comment]
> @bkunda It seems to be fine but can you check it briefly on 1 OS please? (in PRs build or later in master)
> 
> Thank you!

Looking at this now...

**Comment by bkunda** [comment]
Tested PR in #10874 in MacOS. FIXED.
