### ISSUE TITLE
[MU4 Issue] Custom Key Signatures scaling bug

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#10497]
**Describe the bug**
When Line DIstance is changed, Accidentals in custom key signature douesnt adapt it, are misplaced.

**To Reproduce**
1. Create Custom Key Signature
2. Add it to score
3. Change Staff Properties - Line Distance
4. Accidentala are misplaced

**Expected behavior**
Accudentals should adapt their positions.

**Screenshots**
![Key_Signature_Accidentals_Scaling_Bug](https://user-images.githubusercontent.com/1646034/153034173-95dd443d-aaa9-4270-afc3-f54b7d122f08.png)

**Platform information**
 - OS: Linux (but probably exist on all platforms)

**Additional context**
If Key signature is added before, or after scaling doesnt play role.

zipped mscz file attached
[Key Signature Accidentals Scaling Bug.zip](https://github.com/musescore/MuseScore/files/8025777/Key.Signature.Accidentals.Scaling.Bug.zip)

**Comment by Jojo-Schmitz** [comment]
Probably affects MuseScore 3 too, right?

**Comment by DmitryArefiev** [comment]
Tested in master build (Win10, Mac12, LinuxMint 20.2) - FIXED in #11280
