### ISSUE TITLE
[MU4 Task] [GP] fix arpeggio import

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10491]
**Task description**
Arpeggio was shown differently in new version of import
Add stretching of arpeggio sound

Expected result:
![Screenshot 2022-02-08 at 15 32 13](https://user-images.githubusercontent.com/24373905/152987690-fdde0bc1-bfc4-4886-bc60-5759c0580528.png)

**Comment by boryskuzmenko** [comment]
**Reopened**
The arpeggio Up is rendered as a simple arpeggio. 
![Capture 2022-04-21_10-53-53_AM](https://user-images.githubusercontent.com/101250347/164407415-91bc97f3-dc8c-41d4-ae17-6c8832f9d1cf.png)
![Capture 2022-04-21_10-53-04_AM](https://user-images.githubusercontent.com/101250347/164407421-05ff1c54-49d9-4cf6-99b6-ea926cb8a377.png)

**Comment by alexpavlov96** [comment]
@boryskuzmenko there is specific style that hides arpeggio: "ArpeggioHiddenInStdIfTab". And this style is default now.
But it's true that if we hide the TAB staff with an "eye", arpeggio doesn't appear on STANDARD staff. This will be fixed in the PR

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
