### ISSUE TITLE
[MU4 Issue] MU4 starts take a lot of CPU if to launch it together with MU3 (Win10)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10494]
**To Reproduce**
1. Run MU4 
2. Run Task Manager and notice how much of CPU it takes (about 1-5%)
3. Run MU3 (3.6.2)
4. Notice how much of CPU MU4 takes now (it's about **40-50%**)

https://user-images.githubusercontent.com/90187801/153012557-3a504b1e-81ea-469a-b53a-3e6b9f1decba.mp4

**Platform information**
Windows 10, no additional audio device

**Additional context**
Noticed only on **Windows** (Win10 and Win11)

Doesn't occur on some Windows machines with powerful CPU (see comments below)

**Comment by DmitryArefiev** [comment]
@bkunda @jessjwilliamson Hi! Can you check this on your Windows machine please?

I just wonder if that only my environment or not.

Thanks!

**Comment by bkunda** [comment]
@DmitryArefiev yes I have the same issue. It went up to ~31%, then hit as high as ~54%, then went back into the 30s. Pretty strange!

**Comment by jessjwilliamson** [comment]
It depends on how powerful your computer is. Mine is pretty powerful so it hardly touched anything for me. I wonder if you have some logfiles stored that needs cleaning which is a known issue for Windows.

**Comment by Jojo-Schmitz** [comment]
Not for me either, 4% CPU load and none of the cores busy:
![image](https://user-images.githubusercontent.com/1786669/153200182-fc59d14b-76ed-405b-9836-2f624fa90c0e.png)

**Comment by DmitryArefiev** [comment]
@jessjwilliamson @Jojo-Schmitz Thanks for checking!

I've tested this issue on another laptop with Windows 11 (but with less power processor) and still have that strange behavior. So definitely that could be an issue for other users with not powerful computers.

(Tried to clean MU log files - nothing changes)

**Comment by Jojo-Schmitz** [comment]
If there were a performance issue, I'd have expected at least one core to be at or near 100% load. Doesn't matter too much if you have 24 of them (a mere 2.4%), but certainly hurts if you have just 2 (50%) or 4 (25%)
