### ISSUE TITLE
[MU4 Issue] When 'Continue last session' option is enabled, app should not show Home page on start

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10508]
When 'Continue last session' option is enabled, app should not show Home page on start - **the Home page appears for a second before the score opens**

https://user-images.githubusercontent.com/90187801/153199118-8d4f3d9d-8e25-4b8a-9d40-8d39e6b21256.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by Tantacrul** [comment]
This is no longer happening, I believe. Closing for now (unless @DmitryArefiev you have found differently)

**Comment by DmitryArefiev** [comment]
Fixed in #19586
