### ISSUE TITLE
[MU4 Issue] Wrong OK/Save/Yes buttons order in dialogs on Windows (uses Mac style) 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10505]
**Describe the bug**
MU4 windows builds now using **Mac style** for OK/Cancel buttons order in dialogs. 
It should be changed to Windows style - **OK/Save/Yes buttons should be from the left side** 

**MU4:**

![MU4](https://user-images.githubusercontent.com/90187801/153180975-a6906589-6ad5-49d1-843b-928ce92d4f53.PNG)
![MU4 2](https://user-images.githubusercontent.com/90187801/153180983-dc8fdaa6-0586-4b1d-82cb-4f94b711e5aa.PNG)
![MU4 3](https://user-images.githubusercontent.com/90187801/153180998-0cf65dd4-67a0-4c47-b247-fcf30755acf0.PNG)

**MU3:**
![MU3](https://user-images.githubusercontent.com/90187801/153181022-fba16c00-8954-4671-bf67-a891008982e7.PNG)
![MU3 2](https://user-images.githubusercontent.com/90187801/153181030-ddc661f2-0c89-4db1-9a9f-c5b92b784582.PNG)
![MU3 3](https://user-images.githubusercontent.com/90187801/153181043-63982baa-894c-48f0-937d-9bbcf55c3638.PNG)

**Expected behavior**
OK/Save buttons should be from the left side (See MU3 (or other Win app) to compare)

**Platform information**
Windows 10

**Additional context**
Doesn't occur in **MU3**

Some dialogs have the **right** order:  
Style, Page settings, Add/Remove system breaks, Transpose

Another dialogs with the **wrong** order:
New Score wizard, Export, Score properties, Parts, Reset palette

**Comment by Jojo-Schmitz** [comment]
I believe this doesn't happen in MU3 because it got fixed there, some time after 3.x got split off of master

**Comment by vihaanthora** [comment]
Hello @DmitryArefiev, I wanted to know if this is the case with every dialog in MU4 or just the ones that you have shown as examples in the issue?
Thank you

**Comment by cbjeukendrup** [comment]
There is generally no handling for the different order on Windows. So it will be wrong in all dialogs.

**Comment by Jojo-Schmitz** [comment]
Well, that depends on how the dialog is made. Only those using OK, CANCEL etc. buttons directly rather than a QDialogButtonBox have it potentially wrong (from the back of my head, might not be 100% correct)

**Comment by cbjeukendrup** [comment]
Ah, yes, dialogs in QWidgets that are using QDialogButtonBox will be correct. But other QWidget dialogs and in all QML dialogs, it will be wrong.

**Comment by Jojo-Schmitz** [comment]
See https://github.com/musescore/MuseScore/commit/c9bea539e9aa0bbd888be2520deee9736e02b0e9, which fixed this in 3.x

**Comment by Jojo-Schmitz** [comment]
Score properties is amongs those I fixed for 3.x ;-)

**Comment by HemantAntony** [comment]
@DmitryArefiev it seems like some dialogs also have wrong/different orders for yes and no. For example, Revert to Factory Settings and Reset Palette Buttons. Worth creating a separate issue for this?

**Comment by cbjeukendrup** [comment]
@HemantAntony It's indeed worth mentioning, but actually it's just a general problem with more or less all dialog buttons, so one general issue like this is enough.

**Comment by HemantAntony** [comment]
@DmitryArefiev does the Yes/No button order also depend on the OS?

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev does the Yes/No button order also depend on the OS?

@HemantAntony Yes, 
- on **Mac**: 'Yes' should be from the right
- on **Win**: 'Yes' should be from the left

Also, you can compare with MU3 on Windows (expected result)

**Comment by DmitryArefiev** [comment]
Fixed in #11646

**Comment by Tantacrul** [comment]
Moving to 4.x. Will reopen when 4.0 is out. There are issues with the PR that need extra work to resolve.

**Comment by cbjeukendrup** [comment]
Reopening, otherwise people start filing duplicates because they can't find it (which already happened in #15570)

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/349101

**Comment by Jojo-Schmitz** [comment]
Check https://musescore.org/en/node/354139#comment-1205896 how bad this wrong order is recieved by the community

**Comment by DmitryArefiev** [comment]
Fixed in #19429
