### ISSUE TITLE
[MU4 Issue] Adding measures to the end with Ctr/Cmd+B should not take focus and change score position 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10510]
**Describe the bug**
In the recent MU4 builds, the score position changes when adding bars at the end of score with **Ctr/Cmd+B** shortcut because it takes focus on that area. 
That **can be annoying when user adding a notes at the beginning of score**.

This behavior was introduced recently in latest builds. 

https://user-images.githubusercontent.com/90187801/153206401-231b04b9-5985-491d-a7ff-12127bc9d8a3.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Actually, the same behaviour in **MU3**. But I think it can be improved.

**Comment by cbjeukendrup** [comment]
I would actually like this behaviour, because it makes clear to the user that the measures are added. 
Also, in practice, I don't expect users will not often want to add bars to the end of the score while working at the beginning of the score. Or do I miss something and is that a common use case?

**Comment by Tantacrul** [comment]
I have no issue with repositioning when you add measures to a page you are not currently looking at.

However, I agree with the general opinion that we should avoid too much automatic movement. In MuseScore 3, I felt it was too jumpy and often found myself being bumped to a part of the score I wasn't interested in. Specifically, I'd be adding notes to the end of one system and MuseScore would jump to the system below. This is massively irritating. For example, I may want to add more notes / articulation to the previous system. I may want to write notes for a different instrument, etc.

**Comment by DmitryArefiev** [comment]
@bkunda @Tantacrul Make sense! Let's close it then. Thanks!
