### ISSUE TITLE
[MU4 Issue] Palette properties become frozen for previously-opened palettes when adding a new palette

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10539]
**Describe the bug**
Please see this video: 

https://user-images.githubusercontent.com/86290556/153591397-def6fbfa-8039-4690-9d60-1db7fab20a07.mov

**Expected behavior**
Changes to palette properties should work for all palettes, regardless of whether a new palette has been added 

**Platform information**
 - MacOS 12.1 (M1)
 - Windows 11

**Comment by Tantacrul** [comment]
I think this issue has fixed itself at some point over the last few months. Closing for now. Can you confirm, @bkunda ?
