### ISSUE TITLE
[MU4 Issue] Palette icons from `musescoreicon` are not scalable

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10538]
**Describe the bug**
A number of palette elements are taken from the `musescoreicon` font, rather than being rendered in Qt Paint.
These icons currently don't respond to palette properties adjustments, including most critically, scaling. 

Several of the icons in question include...
These ones: 
<img width="296" alt="Screenshot 2022-02-11 at 11 10 27 pm" src="https://user-images.githubusercontent.com/86290556/153589399-ca93f6a6-1809-43da-ad06-564475839755.png">

All of these:
<img width="298" alt="Screenshot 2022-02-11 at 11 10 54 pm" src="https://user-images.githubusercontent.com/86290556/153589423-af42df39-f83e-421d-88e1-c61baf7dc6d6.png">

And these:
<img width="295" alt="Screenshot 2022-02-11 at 11 11 03 pm" src="https://user-images.githubusercontent.com/86290556/153589438-0e07723c-ac72-4af9-af60-d77ea95c9157.png">

**Expected behavior**
All palette elements should respond to scaling in `palette properties`, regardless of whether they come from `musescoreicon` or are rendered from Qt Paint. 

**Platform information**
 - MacOS 12.1 (M1)
 - Windows 11

**Additional context**
Please consult the latest version of `musescoreicon` when resolving this issue, as it contains some new icons relevant to the above mentioned palettes.

Many thanks!

**Comment by mattblo** [comment]
related with [#9292](https://github.com/musescore/MuseScore/issues/9292). Should I rather close my issue so that only one is open?

**Comment by bkunda** [comment]
Sorry @mattblo, I usually try to check for existing issues so I don't duplicate anything. I obviously missed this one 😶.
One reasons to keep this one open and close #9292 is that this one references the layout palette, which should probably be explicitly mentioned. 
Many thanks!

**Comment by mattblo** [comment]
All right! No problem, with so many open issues it's easy to miss one. I will close #9292 then.
