### ISSUE TITLE
[MU4 Issue] Drumset tools panel appears on startup

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10537]
**Describe the bug**
The "Drumset Tools" panel appears at the bottom of the score window when starting up the latest nightly build:

<img width="1152" alt="Screenshot 2022-02-11 at 10 56 13 pm" src="https://user-images.githubusercontent.com/86290556/153587993-3c961fd7-9512-47a0-8c6f-0bb1bed3fddd.png">

**To Reproduce**
1. As a precaution, click "Reset Preferences" in the Preferences dialog, then close and reopen the latest nightly build of MS4
2. Go to the "Score" tab
3. See the "Drumset Tools" panel at the bottom of the window

**Expected behavior**
"Drumset Tools" should not appear by default when starting up MuseScore 

**Platform information**
 - MacOS 12.1 (M1)
 - Windows 11

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10546
