### ISSUE TITLE
[MU4 Issue] In the Instruments panel, Delete/Backspace should delete staves

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#10533]
**Describe the bug**
In the Instruments panel, Delete or Backspace should delete selected instruments or staves, but currently have no effect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the Instruments panel
2. Select an Instrument (or a stave belonging to an instrument) in the panel
3. Press Delete or Backspace
4. (Nothing happens)

**Expected behaviour**
The instrument or stave should delete when Delete or Backspace is pressed - this should be identical behaviour to clicking the trash can icon in the top right (which does work)

**Screenshots**
<img width="302" alt="image" src="https://user-images.githubusercontent.com/20604032/153570584-df5518bf-cd7b-41f8-9125-a050cfccc8a6.png">

**Platform information**
 - OS: Windows 11

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10567
