### ISSUE TITLE
[MU4 Issue] When editing bracket in Properties, span values should be limited

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10548]
**Describe the bug**
When editing bracket in Properties, span min/max values should be limited to 1 and the remaining staves (should be limited by bottom staff)

https://user-images.githubusercontent.com/90187801/153645615-254555b9-1008-4f23-a585-c8e83405c69e.mp4

**Platform information**
 macOS, Windows, Linux

**Comment by njvdberg** [comment]
It is better the limit the maximum value to the **remaining** staves, not the number of staves.
If in this example the bracket starts at the second staff (Violin II), the maximum should be 3, not 4.

**Comment by cbjeukendrup** [comment]
What should happen when multiple brackets are selected? Maybe disabling the "span" field altogether?

**Comment by DmitryArefiev** [comment]
> What should happen when multiple brackets are selected? Maybe disabling the "span" field altogether?

Yes, that's good idea!
