### ISSUE TITLE
[MU4 Issue] `Delete` and `Backspace` should hide palette elements and entire palettes

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10540]
**Describe the bug**
In MS3.6, `backspace` hides individual palette items as well as entire palettes.

![delete-backspace-palettes](https://user-images.githubusercontent.com/86290556/153592092-4cfae141-4e36-423a-97ac-bae0669830eb.gif)

This currently does not work in MS4.

**Expected behavior**
We would actually like **both** `backspace` AND `delete` to hide individual palette items as well as entire palettes.

**Platform information**
 - MacOS 12.1 (M1)
 - Windows 11

**Additional context**
Also related to #10533

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10567
