### ISSUE TITLE
[MU4 Task] Opening files from previous major versions should be handled as import

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#10556]
**Task description**
When opening a file from MuseScore 1, 2, or 3, it should be handled as if the file is imported from other file formats. This way, the user will either have to confirm that they want to override the old file, or select a new location. Together with the "Migration" dialog when opening a score, this will help making the user aware that they are potentially overriding the old file that was compatible with the older version of MuseScore.

**Comment by Tantacrul** [comment]
100%. Targeting at alpha.

**Comment by DmitryArefiev** [comment]
Fixed in #11782
