### ISSUE TITLE
[MU4 Issue] When creating project from template, the specified number of measures is not reflected

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#10576]
**Describe the bug**
When creating a new score from a template, the number of measures specified in the New Score dialog is not reflected in the created score. Additionally, the system breaks from the template file are imported into the new score, which is not desired.
This must be a relatively recent regression.

**To Reproduce**
1. Open the "New Score" dialog
2. Choose a template and click Next
3. Specify the number of measures you want and click Done
4. The newly created score contains as many measures as the template had, not as many as specified.

**Expected behavior**
The newly created score should have the specified number of measures and no system breaks.

**Platform information**
 - OS: reported on macOS

**Comment by HemantAntony** [comment]
Reproduced on Windows

**Comment by RomanPudashkin** [comment]
This fix should help:
https://github.com/musescore/MuseScore/pull/10575

**Comment by Jojo-Schmitz** [comment]
Quesion is though whether this is really worth a warning

**Comment by cbjeukendrup** [comment]
I think the problem is that those template scores have a MU3 MSCX format, but MU4 is trying to read them as a MU4 MSCX format.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED  in #10575 (together with #10574)

**Comment by Jojo-Schmitz** [comment]
> I think the problem is that those template scores have a MU3 MSCX format, but MU4 is trying to read them as a MU4 MSCX format.

Nope:
```
<museScore version="4.00">
```
