### ISSUE TITLE
[MU4 Issue] "Do you want to save..." dialog should not show file extension

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10589]
Doesn't occur with new scores.

1. Open recent score
2. Make some changes
3. Close score

![Capture](https://user-images.githubusercontent.com/90187801/154309293-b7f2e7eb-8d5e-4114-a4f6-87b9419033d8.PNG)

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by cbjeukendrup** [comment]
This happens to be fixed by PR #10552. (It will show the extension only when it is "interesting", i.e. when it is something different than mscz.)
