### ISSUE TITLE
Some of the Palette Options in MS3 have not been ported to MS4 (in the '...' menu)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10618]
**Describe the bug**
In MS3.6, there are a few useful options in the '...' menu, next to the search bar:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/21022311/154809457-f0586ddb-07a7-43ce-add1-b2823f1a2512.png">

However, there is one option missing which used to be available in previous versions: the ability to open a palette by single-clicking on it. This is a common complaint from users of older versions of MuseScore. So, in addition to the options in the image above, we should also reintroduce the checkbox for the option '**Single-click to open a palette**'

They should be added to the new '...' menu here:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/21022311/154809587-c6fc52cb-8853-43cc-84e2-b1bc1d1fa116.png">

I seem to recall that a member of the community did some work on this last year. Maybe @Howard-C or @cbjeukendrup? Perhaps I'm wrong.

**Comment by cbjeukendrup** [comment]
Yes, it was me who worked on that for MU3.6 :)
I'd be happy to reimplement it for MU4.

**Comment by Tantacrul** [comment]
Wow, that long ago?

**Comment by Tantacrul** [comment]
@cbjeukendrup, I've removed everyone else and left the task to you. Cheers!

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10619
