### ISSUE TITLE
[MU4 Issue] [Inspector] You need to click Reset button two times to apply the action (Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10611]
You need to click Reset button two times to apply the action in Properties. In some places where that button is not hidden in 3 dot menu (on Windows only)

https://user-images.githubusercontent.com/90187801/154667895-7c433d37-a3bf-4163-a7d9-f03c695ef9f9.mp4

**Platform information**
Windows only (Win10)

**Comment by duanjr** [comment]
This only happens in popup view. 
Maybe because tooltip is also a popup view and some signal is listened twice.
Another issue may be related: [10463](https://github.com/musescore/MuseScore/issues/10463) (also tooltip in popupview)

**Comment by duanjr** [comment]
> 

Did you wait until the tootip show?

**Comment by duanjr** [comment]
> I can't reproduce at all sorry. I tried undocking the properties panel and while I still can't reproduce it, I did notice that where the "Appearance" pop-up appears doesn't make a lot of sense.

Did you wait until the tooltip show to click?(Just make sure the title did not mislead you)

**Comment by wizofaus** [comment]
Ah yes you're right - if the tooltip shows, then you have to click once to dismiss the tooltip and again to activate the command.  Suspect trying to change that behaviour wouldn't be trivial.

**Comment by Eism** [comment]
working on it

**Comment by DmitryArefiev** [comment]
Fixed in #10837
