### ISSUE TITLE
MuseScore did'nt start on Fedora 35 Kinoite (Flatpak)

### ISSUE THREAD

**Issue by destinatorM** [musescore/MuseScore#10622]
MuseScore will not start on my Fedora 35 Kinoite.

I installed it with Flatpak (Flathub).

There is no Error-prompt or something. If I try to start, nothing happens.

**Comment by MarcSabatella** [comment]
Thre MuseScore team doesn't support Flatpak, that is something you'd have to report to the folks who packaged it - probably they got something wrong.  Instead, use the supported version - the AppImage you can download directly from musescore.org.  And then if you have issues, please ask for help on the Support forum (same website).
