### ISSUE TITLE
[MU4 Issue] Crash on undoing after creating a new part

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#10620]
**Describe the bug**
When, you create a new part using the Parts Dialog and then decide to undo it by clicking Ctrl + Z, it crashes

**To Reproduce**
1. Create a new score
2. Open parts dialog
3. Create a new Part
4. Close the dialog by pressing Open
5. Then press `Ctrl + Z`

**Expected behavior**
MuseScore should not crash

**Screenshots**

https://user-images.githubusercontent.com/88136054/154833468-5371a1ab-2a1e-4eb4-bb16-724798e442d7.mp4

**Platform information**
 - OS: Windows 11

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10625
