### ISSUE TITLE
[MU4 Issue] Channels from mixer won't load until after opening Mixer 2nd time

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#10633]
**Describe the bug**
This is happening almost all the time, it might be happening to only channels that include VSTs, not sure if it's just Musescore General instruments.

Here I have a project where all instruments use VSTis.

**To Reproduce**
1. Open a project with a few instruments that include VSTis (BBC Orchestra, LABS etc)
2. Click on Mixer button, observe error
3. Click on Mixer button again to close
4. Click on Mixer button 3rd time to re-open and all instruments should appear

**Expected behavior**
Obviously, it shouldn't take 2 times to open all instruments

https://user-images.githubusercontent.com/71656189/155004091-df875b68-bc26-42f5-bfb2-4aa11ba8e469.mp4

**Comment by HemantAntony** [comment]
I think that it doesn't have much to do with the number of times Mixer was clicked. It takes a bit of time to load the instruments. I don't know how to open VSTs in MU. Therefore, I did it with instruments:

https://user-images.githubusercontent.com/88136054/155045430-159ff40f-f6da-46b8-a26a-fc80c8ffdf67.mp4

I think something similar will happen when you just wait for a few seconds (I'm not in the latest master. So I also couldn't test properly)
