### ISSUE TITLE
[MU4 Task] [GP] Barlines import

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#10638]
**Task description**
Fix barlines import.

**Current state:**
![Screenshot 2022-02-17 at 19 54 49](https://user-images.githubusercontent.com/24373905/155085678-80ed1c23-06c7-4dd0-be00-8626c5e063fe.png)

**Expected:**
![Screenshot 2022-02-17 at 19 54 20](https://user-images.githubusercontent.com/24373905/155085663-7fc60d78-75f3-4f9c-8bc7-95f781ba14b4.png)

**Comment by boryskuzmenko** [comment]
**Reopened**
The issue is partly fixed. Barlines on imported score are not applied to all staves. See screenshot:
![Capture 2022-04-19_11-18-58_PM](https://user-images.githubusercontent.com/101250347/164090273-6698b49b-8daf-4497-9800-859ee34b2aa1.png)

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
