### ISSUE TITLE
[MU4 Issue] Multiple pop-ups are being opened at the same time

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#10635]
**Describe the bug**
Pop-ups (commonly found in Properties) are being opened/activated at the same time when they should be opened one at a time.
This causes the pop-ups to overlap each other

https://user-images.githubusercontent.com/71656189/155008730-c0f0da4c-5c22-4667-9811-f7f8e19bbd5a.mp4

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12 - FIXED in #10640
