### ISSUE TITLE
Ctrl+A shortcut does not 'select all' text in Lyrics or Chord symbols.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10632]
**Describe the bug**
**Ctrl + A** (Windows), **Command + A** (Mac) does not select all text when editing lyrics or chord symbols.

See video for comparison.

https://user-images.githubusercontent.com/21022311/154996272-af85f49e-d24b-41c8-a688-441acf735c90.mov

**Comment by DmitryArefiev** [comment]
Fixed in #10818
