### ISSUE TITLE
[MU4 Issue] 1st channel Audio FX slot glitches when using pan knob

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#10634]
**Describe the bug**
It seems to happen only the first channel (very left) Audio FX empty slot/s glitches. Even when adding effects it's still happening.

https://user-images.githubusercontent.com/71656189/155005322-ec1aebd1-7562-48e5-8158-a2a2685fe021.mp4

**Comment by boryskuzmenko** [comment]
The issue is not reproducible anymore.
**Can not reproduce**
