### ISSUE TITLE
Shortcuts for note entry on Guitar Tablature not working

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10641]
**Describe the bug**
Users can not navigate guitar tablature using shortcuts to enter notes. See video:

https://user-images.githubusercontent.com/21022311/155109392-78c0f035-9bcf-4584-844b-a25cfed4c5df.mov

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/10612

I'm working on it right now

**Comment by Tantacrul** [comment]
Ah, awesome :)

**Comment by RobFog** [comment]
Would #10612 make this issue a duplicate?

**Comment by Tantacrul** [comment]
> Would #10612 make this issue a duplicate?

Yeah, Roman mentioned this is a dupe. He's already working on it, which is great :)

**Comment by RobFog** [comment]
If this issue is a duplicate shouldn't it be closed then?
