### ISSUE TITLE
[MU4 Tech Debt] Unit tests in src/notation are never running

### ISSUE THREAD

**Issue by helloworld12321** [musescore/MuseScore#10667]
**Task description**

At the moment, the tests in `src/notation` are not included in the build, even if the `-DBUILD_UNIT_TESTS=-ON` flag is set. This means that the test file [`notationviewinputcontroller_tests.cpp`](https://github.com/musescore/MuseScore/blob/ae475cecbeed40e501c6c1f895c9894849e890df/src/notation/tests/notationviewinputcontroller_tests.cpp) never compiles or runs. :cry:

The mock files [`controlledviewmock.h`](https://github.com/musescore/MuseScore/blob/ae475cecbeed40e501c6c1f895c9894849e890df/src/notation/tests/mocks/controlledviewmock.h) and [`notationsceneconfigurationmock.h`](https://github.com/musescore/MuseScore/blob/ae475cecbeed40e501c6c1f895c9894849e890df/src/notation/tests/mocks/notationsceneconfigurationmock.h) are also affected by this issue.

As it stands, `notationviewinputcontroller_tests.cpp` is outdated, and would need revisions before it compiles and runs successfully. We could either make these revisions, or we could delete the files in question, since they aren't contributing to test coverage anyway. :slightly_smiling_face:

**Comment by helloworld12321** [comment]
Right now, the `src/notation` tests are commented out in `src/CMakeLists.txt`: https://github.com/musescore/MuseScore/blob/ae475cecbeed40e501c6c1f895c9894849e890df/src/CMakeLists.txt#L100-L102

(A comment says there aren't any tests in `src/notation`, but this isn't currently accurate.)

**Comment by cbjeukendrup** [comment]
The issue still exists; the unit tests for the notation module are outdated and are not running. It has been like that for a while, so it will probably take some effort to make the tests up-to-date again. I don't think that getting these tests working will help us a lot with the release of MU4.0, so my feeling is that we should not spend too much valuable time on it now. @RomanPudashkin what is your opinion?
