### ISSUE TITLE
[MU4 Issue] `0` should enter open string – not rests – in tablature staves

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10669]
**Describe the bug**
Keyboard shortcut `0` currently enters rests in tablature staves, rather than open strings (as per MS3 behaviour)

**To Reproduce**
1. Enter **note input** mode in a tablature staff
2. Hit `0`
3. A rest is entered

**Expected behavior**
The tablature number `0` (representing an open string) should be entered when the keyboard shortcut `0` is typed on tablature staves

**Platform information**
 - macOS 12.1
 - Windows 11

**Comment by Jojo-Schmitz** [comment]
Hmm, I don't see 0 doing anything in a tablature in MuseScore 3

**Comment by bkunda** [comment]
@Jojo-Schmitz this is what I see in MS3:

![0-tab-staves](https://user-images.githubusercontent.com/86290556/155710098-3da2d802-2b11-4c85-9144-de5d1e978a21.gif)

**Comment by Jojo-Schmitz** [comment]
Ah, NumPad 0 does nothing, the 'normal' 0 does

**Comment by bkunda** [comment]
My NumPad (with numlk on) changes note durations while the number row enters tablature numbers (in MS3.6)

**Comment by Jojo-Schmitz** [comment]
With 0 being a rest, yes, but apparently not in Tablature?

**Comment by bkunda** [comment]
Correct, not in tablature.
