### ISSUE TITLE
[MU4 Issue] Select submenu missing from context menu if range selection present

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#10674]
The context menu that appears on right-click an element is missing the "Select" submenu if a range selection is present.  This is an key regression, since losing that menu negates the ability to ever use the "Select: similar in the range" item that is normally present when there is no range, or to use the dialog.  BTW, do we really need the word "the" in "similar in the range"?  And if so, maybe we should add it "similar in same staff"?

To reproduce:

1. Make a range selection
2. Right-click a note

Result: contextual menu is missing the "Select" submenu

**Comment by wizofaus** [comment]
Just noticed this, and it's worse, the option *is* there if you don't have a range selected (just a single note), which makes no sense.
Happy to look at...

**Comment by wizofaus** [comment]
NB fixing this is relatively straightforward, but @Tantacrul do you have a preference as to what exactly *should* appear in the Select menu when you right click on an element while there's a range selected?  In v3 it does actually allow you choose various other options that to me don't necessarily make obvious sense, basically using the element under the mouse as the "reference" element that the command applies to, even though it's not selected as such.
My proposal is that if there is a range selected and you right-click an element (note etc.), then ONLY "Select>all similar elements in range selection" is available. If you want to use the other commands (all similar elements, similar elements in staff, select dialog), you must deselect the range first (which is just a single click).
"Select similar elements in range selections" is the ONLY command that needs two references - one being the current range selection, the other being the element under the mouse pointer (which I will note makes this command essentially unusable by users that can't use a mouse, but there's no straightforward fix for that unfortunately).

**Comment by wizofaus** [comment]
Oh btw if you don't click on a element, but somewhere else inside the range, you get this

![image](https://user-images.githubusercontent.com/5364225/160556646-d5dd053b-24bd-4daf-89a3-60b2d20f0987.png)

**Comment by jeetee** [comment]
> "Select similar elements in range selections" is the ONLY command that needs two references

This is untrue, there (at least in MS3) are a plethora of options within the select dialog that *also* need the range selection and come into play when "similar in range" is too broad of a filter. When subtype/voice needs to be filtered as well, within the range, you do still need the dialog **and** the range

**Comment by wizofaus** [comment]
Ah, yes, you're right, in v3 the element type field is based on the clicked-on element, but that's it as far as I can see.
However I agree we should preserve that behaviour in v4, which would be a bit more work, I'll look into it.

**Comment by wizofaus** [comment]
Actually...a significant percentage of the functionality in the Select Note Dialog doesn't work at all... @Tantacrul ...I'm happy to fix it all, just don't want to end up with another PR that never gets merged.

**Comment by wizofaus** [comment]
I have the main functionality working now as far as I can see, this includes:
a) select note/select element dialog can be brought up if you have a range/list selection and you right-click on an individual element, such that the clicked-on element is used to populate the selection criteria (pitch, type etc.)
b) note-specific criteria like "pitch" or notehead type etc. now actually work 
c) "in selection" checkbox actually works and restricts selection to among those that are already selected
d) "add" works as expected, even if a range is selected beforehand

The "search in selection" option is always disabled though, and I can't quite work out how to get it enabled in v3 either!
