### ISSUE TITLE
(Nice to Have for MS4) Remove 'Direction' option for Articulations

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10671]
**Describe the bug**
When selecting an articulation, you see these options in the inspector:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/21022311/155799028-009f121f-dc2b-4baf-8d67-9935083d5039.png">

After a little testing (and consulting others on the team), we think that the 'direction' option is both confusing and very likely not useful as an option. At least not useful to the point where it shouldn't be exposed to limit the 'WTF' factor.

I'd like to shop this opinion out to see if anyone can help us understand why the 'direction' option is needed.

I move that we hide this option and keep 'Placement' (which will be easier to understand without the 'direction' option)

**Comment by MarcSabatella** [comment]
The intent is to allow things like marcato symbols to be flipped upside down (display8ing as a "v") while keeping the symbol still above the staff.  It does work for that purpose, at least in MU3.  Hard to say if anything really uses it except for weird special effects.

**Comment by Tantacrul** [comment]
So, we do know what it does, alright. It's just that it is hard to think of a justification.

The problem with options like these is that 1. they produce bizarre results (for example, a lot of symmetrical symbols will not appear to do anything). 2. It is the kind of option a user might deride - and that does affect our image as a serious music app. I do think it's important that options are described (and behave) in sensible and predictable ways.

If we really wanted this, I'd suggest a generic transform tool that allows users to flip items 90 or 180 degreed, etc.

**Comment by MarcSabatella** [comment]
I would definitely favor that, and I know people would find uses for it on other things like clefs.

But for the record, I suspect one specific reason why it is present for articulations only is that SMuFL probably defines separate symbols for some of these, so it isn't necessarily just a graphical transformation - it's substituting a different glyph.  That's just (educated) guessing on my part, though.

**Comment by oktophonie** [comment]
There are independent SMuFL symbols for above/below versions of articulations. In the vast majority of cases these are mirrored versions of each other (relative to the baseline) but that isn't always necessarily the case.

**Comment by Tantacrul** [comment]
@wizofaus - you think you could help us with this one? This particular UI is just embarrassing because it almost never provides anything useful.

**Comment by wizofaus** [comment]
I'd assume you could just remove that section from the qml file, but changes to dialog/form layouts etc. aren't really my forte...

**Comment by wizofaus** [comment]
BTW the default behaviour for, say, the up- and down- bow articulations is still to flip them when shown under a note, but I've definitely seen cases where their normal direction is preserved. And apparently showing a down-bow "upside-down" was done in older French scores: https://music.stackexchange.com/questions/43196/upside-down-down-bow

**Comment by wizofaus** [comment]
Anyway, happy to put up a PR that just marks that row with visible: false, it looks/works fine as far as I can tell.

**Comment by Tantacrul** [comment]
OK, I guess if @RomanPudashkin or @Eism is happy with that, it'd be a simple merge. If you don't feel comfortable with it, that's fine.
