### ISSUE TITLE
[MU4 Issue] Add noteheadHeavyX and noteheadHeavyXHat to Noteheads palette

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#10684]
**Task description**

Make these two noteheads (U+E0F8 and U+E0F9) available via the Noteheads palette:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/20604032/155966623-e09297ad-8334-4727-a2a7-30505beed0d1.png">
(from https://w3c.github.io/smufl/latest/tables/noteheads.html)

They do not belong to a 'notehead group' (i.e. a 'black'/'half'/'whole'/'doubleWhole' set), so, for each of these two, the same notehead will be used for any note regardless of its duration. Can they go into a 'group of one' or is there a better solution?

**Comment by Jojo-Schmitz** [comment]
Could we add [Chromatic noteheads to moveable do](https://w3c.github.io/smufl/latest/tables/note-name-noteheads-supplement.html) too? See https://musescore.org/en/node/329930

**Comment by miiizen** [comment]
I'm currently taking a look at this :)

**Comment by miiizen** [comment]
> Could we add [Chromatic noteheads to moveable do](https://w3c.github.io/smufl/latest/tables/note-name-noteheads-supplement.html) too? See https://musescore.org/en/node/329930

Do we want chromatic noteheads on as default in movable do or as another scheme entirely?

**Comment by Jojo-Schmitz** [comment]
Best ask this in that issue.
