### ISSUE TITLE
Volta Brackets should be able to extend over additional bars via click & drag

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10695]
**Describe the bug**
There is a usability issue with Volta brackets, where we show a clear dragging affordance to users that allows them to be stretched over multiple bars:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/21022311/156171109-735aad33-af88-4dad-b0f8-e93d553bc4b7.png">

However, if you do stretch a volta line out, it does not affect playback. The 'pink connection' line still shows which bar the line is actually applying to. We fixed this issue with hairpins a few years ago but never fixed it for other lines. It is a pretty bad usability trap with no clear fix (until you learn the Shift+Arrow shortcut).

<img width="466" alt="image" src="https://user-images.githubusercontent.com/21022311/156171404-3bc7fbb7-b44e-4c15-bd2e-f35836937750.png">

**Expected behavior**
Dragging a volta line should result in the 'pink connector' jumping to back and forth between barlines appropriately. Similar to the way hairpins work but limited to barlines and not to durations.

Note: This is not a crucial fix for the release of MS4. It is a desired 'nice to have' if anyone has the time.

**Comment by mccoydtromb** [comment]
I've started looking into this, but don't know enough about the pink connectors and where they come from in the code, or where to find the OnDragEvent type of handlers for these objects. I'll keep searching, though.

**Comment by Tantacrul** [comment]
Closing as a 4.x feature request, since the issue was already present in MS3.6.2.
