### ISSUE TITLE
[MU4 Issue] Crash when making changes to staff/part properties after double-click on instrument name

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10692]
**Describe the bug**
MuseScore crashes when making changes within the Staff/Part Properties dialog IF the dialog was triggered by double-clicking on the instrument name label next to a staff.

This crash does not seem to occur when triggering this dialog via the context menu.

![crash in staff-part properties](https://user-images.githubusercontent.com/86290556/156145236-63a27c2b-2672-4f3a-a5b7-f3b96da2e5c8.gif)

**To Reproduce**
1. Double-click on an instrument name label
2. Change a value in one of the "instrument name" text fields, or check/uncheck a check box
3. Click "Apply" or "OK"
4. MuseScore crashes

As a minor additional issue, the context menu item "Staff/Part Properties..." when right-clicking an instrument name doesn't seem to have been implemented in MS4. This should be reinstated if possible. 

<img width="526" alt="right-click" src="https://user-images.githubusercontent.com/86290556/156146976-bed9b091-0fb8-45bf-8666-9141cd26ae2a.png">

**Expected behavior**
MuseScore should not crash
Right-click on instrument name label should reveal context menu item "Staff/part p/roperties..." to trigger the "Staff/part properties" dialog. 

**Platform information**
 - MacOS 12.1 (M1)
 - Windows 11

**Comment by cbjeukendrup** [comment]
The cause of this crash is that the instrument name element gets deleted and recreated when changing the name in Staff/Part Properties. 
But, the Appearance Inspector Model still holds a pointer to the deleted one, and tries to get information from the deleted one, which causes a crash.

Something similar seems to be happening in #10693.

All those crashes happen in the same place with the same stack trace:
<img width="1150" alt="Schermafbeelding 2022-03-01 om 11 42 33" src="https://user-images.githubusercontent.com/48658420/156154604-c6e15e9b-db98-4b63-825e-23c1bd4dbc34.png">

When an element gets deleted, it does get removed from the `selection` in libmscore (see `Score::onElementDestruction`), but somehow that is not picked up by the Inspector models.

**Comment by RomanPudashkin** [comment]
I'm working on these crashes
