### ISSUE TITLE
[MU4 Issue] Hidden staves become un-hidden on app re-open

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10694]
**Describe the bug**
See this demo video: 

https://user-images.githubusercontent.com/86290556/156156500-d2a9213b-44f6-427c-b7c1-484b55bb86cb.mp4

**Expected behavior**
Staves hidden in the Instruments Panel should remain hidden until the user makes them visible again (even after closing and re-opening the project file or app)

**Platform information**
 - MacOS 12.1 (M1)
 - Windows 11

**Additional context**

**Comment by Tantacrul** [comment]
This is a P1, not a P3!
