### ISSUE TITLE
[MU4 Task] Identify non-default styles in saved files

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#10700]
**Task description**

Currently in MU4, _every_ style setting is saved as part of the file package (in `score_style.mss`), and inside the .mscx file, the complete instrument definition data (from `instruments.xml`) for each instrument is copied to an `<Instrument>` element inside each `<Part>`.

It is proposed that instead, we include only style settings that _differ_ from the default settings (as given in `styledef.cpp`) - which was the behaviour pre-MU4 (and in fact continues to be the behaviour in that the non-default settings are still saved into the `.mscx` currently, as well as the 'complete' style information going into the `.mss` file) - and also only the instrument data that differs from that of `instruments.xml` (by default, an unaltered instrument could be represented simply by e.g.  `<Instrument id="piano" />`).

As well as a modest reduction of file size, this also helps in development since, whenever a style has its default changed, or an instrument definition is tweaked, we do not have to go through all the templates and tests to update them to match. If these files require custom style or instrument data it can still be included where necessary.(Special care will be required for tests which explicitly address the application of styles!)

For score migration, we already include style sheets with the legacy defaults for previous file versions (`legacy-style-defaults-v1|2|3|302.mss`) which are used to provide the 'base' styles for any scores created in previous versions, so much of this functionality already exists. We could do something similar for instrument definitions if necessary.

When loading a file, assuming the `.mscx` or `.mss` file contains a reference to the file format version (which they currently do), all 'missing', i.e. default, information can be repopulated. When saving, all settings and instrument information will be compared against the defaults, and included only where it differs.

Explicitly saving an .mss file from within MuseScore would, of course, still save the complete set of styles.

One potential disadvantage is that this renders styles generally implicit rather than explicit, i.e. if the underlying defaults change then the settings of the score will also change. However, these changes should only happen as part of a new software version (and/or file format version), and as long as we supply complete style sheets for each version, we can continue to honour the settings of the version in which the file was previously saved, with only those exceptions as required by the specific migration path being taken (i.e. for styles which are now deprecated, have a different interpretation so require a recalculation, etc.)

Comments/outrage welcome!

**Comment by shoogle** [comment]
It turns out that we _do_ need to save all the styles after all, including the default styles. However, we _also_ need to save a tag or other indicator to tell us whether the saved style was default or not. See https://github.com/musescore/MuseScore/pull/10963#issuecomment-1095529655.

**Comment by shoogle** [comment]
It can't be closed, but I also can't look into it right now as I have several other tasks that need my attention to unblock other people. This one isn't blocking anyone and it could be fixed by any developer or even a community member; it's just a matter of finding the right place in the code.

**Comment by RomanPudashkin** [comment]
Discussed this issue with @vpereverzev. We are satisfied with the current behavior, but it can be further improved in the future
