### ISSUE TITLE
[MU4 Issue] [Accessibility] Screen readers not working in Palettes

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#10717]
**Describe the bug**
Speech output for all palette items is just _"List item"_. The screen reader should say the name of the item (e.g. _"Treble clef"_, _"C Major"_, _"Common time"_, _"Fermata"_, etc.). This is necessary for blind users to be able to find items and add them to the score.

**To Reproduce**
1. Start up a screen reader (e.g. NVDA, Windows Narrator) and then launch MuseScore.
2. Open/create a score.
3. Press Tab repeatedly until the Clefs palette has focus.
    - The screen reader will correctly say _"Clefs"_.
4. Press Right to focus on the little "expand" triangle next to the palette name.
5. Press Space to expand the palette.
6. Press Down to highlight the first item in the palette and listen to speech output.
    - The screen reader says _"List item"_. It should say _"Treble clef"_.
7. Continue to press Down and listen to speech output for each item. Also try other palettes like Key signatures, etc.

**Expected behavior**
The screen reader should say the name of the item that has focus. Instead it just says _"List Item"_ on each item.

**Screenshots**
![image](https://user-images.githubusercontent.com/11011881/156465073-494ebc4c-e1fc-4b5f-8057-f0750ddbbbc3.png)

**Platform information**
 - OS: Windows 10 running either NVDA or Windows Narrator screen reader

**Additional context**

The free program [Accessibility Insights for Windows](https://accessibilityinsights.io/docs/en/windows/overview/) provides this view of the accessibility tree.

![image](https://user-images.githubusercontent.com/11011881/156464976-4b269d44-7521-403a-8714-585032fd0adf.png)

Notice that the names of palette elements are present and correct. However, the Clefs palette is identified as a "list item", whereas the palette elements like treble clef are identified as "groups". This may indicate that the Accessible Role is incorrect for palettes and/or palette elements. A "list item" would normally be child of a "list" object.

**Comment by Eism** [comment]
@shoogle 
please check #10878
