### ISSUE TITLE
[MU4 Issue] Percussion panel interactions not yet implemented

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10719]
**Describe the bug**
Some important interactions are still missing from the percussion panel. These include: 

- Double click to enter the note into the score
- Number row shortcuts to change note duration

Demo video:

https://user-images.githubusercontent.com/86290556/156534406-40142165-f705-47ce-9def-ac3992e7c59d.mp4

**Expected behavior**
See video above

**Platform information**
 - MacOS 12.1 (M1)
 - Windows 11

**Comment by cbjeukendrup** [comment]
> * Number row shortcuts to change note duration

@RomanPudashkin, I fixed that item as part of #10735, so you don't need to do that :)

**Comment by MarcSabatella** [comment]
BTW, regarding the proposal in https://github.com/musescore/MuseScore/issues/11743 to make drum input work on single click - it's a good idea in principle, but there are important use cases that are broken if we do this without making other changes to compensate.  We discovered this quite by accident in MuseScore 3.4 when the standard palettes were converted from double to single click and drum palettes were unintentionally affected too.  Then the complaints came in, and we were able to see what was missing, so we ended up reverting the change for drum palettes specifically.  I'm quite sure it would have been possible to find an alternate design that covered all use cases with a single click, but anyhow, that would need to be addressed.  See https://musescore.org/en/node/300139 for some of the discussion.

**Comment by bkunda** [comment]
Thanks for this background info, @MarcSabatella. it makes me think we need to do some more research and user testing ahead of making any overhauls to the way percussion note input works (and we will be doing an overhaul to percussion at some point in a future release, so these considerations you've shared will be very useful).

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

The point about sound preview in percussing panel is reported as a separate issue https://github.com/musescore/MuseScore/issues/11722
