### ISSUE TITLE
[MU4 Issue] Paste text when editing doesn't work on Linux

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10742]
**To Reproduce**
1. Double click on Title
2. Ctr+A to select all
3. Ctr+X to cut (text disappears)
4. Ctr+V to paste - **nothing happens**

Also doesn't work if to use commands from File menu>Edit>Paste

**Platform information**
Linux only

**Additional context**
Doesn't occur in **MU3**

**Comment by Tantacrul** [comment]
Bumping to beta since it is an existing issue

**Comment by DmitryArefiev** [comment]
> Bumping to beta since it is an existing issue

@Tantacrul I just realized that made a typo in the Description : Wanted to write "Doesn't **occur** in MU3 instead of "Doesn't **work** in MU3".. Let's put this again to Alpha2 (but with P2) since it's critical when working with text in score.

If disagree just move to Alpah2 again. 

Sorry for confusion!

**Comment by DmitryArefiev** [comment]
FYI @Eism

**Comment by DmitryArefiev** [comment]
Fixed in #12157
