### ISSUE TITLE
[MU4 Issue] An octave higher when playing the note C-flat

### ISSUE THREAD

**Issue by Fince10086** [musescore/MuseScore#10756]
**Describe the bug**
MU4 has an octave higher when playing the note C-flat.

**Screenshots**
![image](https://user-images.githubusercontent.com/87692117/156922561-81c86244-d379-42fd-a48a-935d68127ce5.png)

**Platform information**
Windows and Linux (not tested on macOS)

**Comment by cbjeukendrup** [comment]
There are more problems with notes with accidentals... 
- F## sounds like Eb
- Cb, Cbb, A## sound an octave to high
- B#, B##, Db, Dbb sound an octave to low

**Comment by vimpostor** [comment]
I have fixed this in #10798 :)
