### ISSUE TITLE
[MU4 Issue] Fix solo/mute interactions in mixer

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10766]
**Describe the bug**
There are a couple of bugs with how solo and mute currently work in the mixer.
1. Turning off solo on a track leaves all other tracks muted. 
2. After enabling solo on a track, setting solo on any subsequent track leaves that track in mute state.

Video: issue 1

https://user-images.githubusercontent.com/86290556/157428929-12f78e85-ca17-4db1-a9d8-1afdf2b5c1e3.mov

Video: issue 2

https://user-images.githubusercontent.com/86290556/157428959-7644781a-c177-47e2-afc0-59dec8be04b5.mov

**Expected behavior**
**Issue 1:**
The rule should be that where only one track is set to SOLO, disabling that solo should UN-MUTE all other tracks.
_Condition_: This would not happen where multiple tracks are set to SOLO. In this case, disabling solo on one track should not affect other tracks with solo/mute settings. 

**Issue 2:**
The rule should be that, where a track is set to SOLO, and a _second_ track is set to SOLO, that second track should come off mute. 
_Condition_: It should still be possible to mute one of the solo'd tracks.

**Platform information**
 - MacOS 12.1 (M1)

**Comment by mattblo** [comment]
Related to https://github.com/musescore/MuseScore/issues/10335

**Comment by DmitryArefiev** [comment]
@bkunda Can you check this on your side please? in #10824

Thank you!
