### ISSUE TITLE
The search button in Palettes is still taller than the button next to it

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10762]
**Describe the bug**
The search button in Palettes is still too tall. It is amazingly annoying to look at :)

<img width="969" alt="image" src="https://user-images.githubusercontent.com/21022311/157243310-6480e6ad-458f-4a0c-b328-a4eacc46f692.png">

Giving it a P2 just for the annoyance factor.

**Comment by Tantacrul** [comment]
I know I logged this a while ago but I can't find the issue. Perhaps it was fixed and then unfixed?

**Comment by HemantAntony** [comment]
@Tantacrul see #9278

**Comment by RobFog** [comment]
And #9278 was closed in favour of the older and more comprehensive #8098.

**Comment by Tantacrul** [comment]
@RobFog - thanks!

Closing this one down.
