### ISSUE TITLE
[MU4 Issue] 'Play notes when editing' checkbox can't be unselected in the preferences 

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#10774]
'Play notes when editing' checkbox can't be unselected in the preferences 

**To Reproduce**
1. Go to 'Preferences > Note Input'
2. Try to untick 'Play Notes when Editing' checkbox
3. Pay attention to the checkbox behavior

**Expected behavior**
'Play notes when editing' checkbox can be unselected 
'Play Chord when Editing' and 'Play Chord Symbol when Editing' checkboxes should be disabled in this case

**Screenshots**
![Screenshot at Mar 10 09-49-11](https://user-images.githubusercontent.com/101250347/157854144-def791f2-f374-4ca7-b21f-f5132300c207.png)

**Platform information**
 - OS: [macOS]

**Comment by HemantAntony** [comment]
@boryskuzmenko Just wanted to check if I'm understanding correctly:
When 'Play notes when editing' is checked, 'Play Chord when Editing' and 'Play Chord Symbol when Editing' should not be disabled
But when 'Play notes when editing' is not checked, 'Play Chord when Editing' and 'Play Chord Symbol when Editing' should be disabled

**Comment by boryskuzmenko** [comment]
Yes, that's right.
You can check the correct behavior in MU3

**Comment by HemantAntony** [comment]
I'm working on this. PR soon!

**Comment by boryskuzmenko** [comment]
Great, thanks!

Сб, 12 марта 2022 г. в 11:00, Hemant Antony ***@***.***>:
