### ISSUE TITLE
[MU4 Issue] Score preview is not updated according to the updates in the score after 'Save' and 'Close'

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#10777]
**Describe the bug**
Score preview is not updated according to the updates in the score after 'Save' and 'Close'

**To Reproduce**
1. Go to 'MU'
2. Create new score, save it empty, close it
3. Pay attention to the score preview
4. Open the same score, add any notes/symbols, save it, close it
5. Pay attention to the score preview

**Expected behavior**
Score preview is updated according to the updates in the score after 'Save' and 'Close'

**Screenshots**
![Screenshot at Mar 10 22-07-28](https://user-images.githubusercontent.com/101250347/157860185-aca72ab0-1685-42e9-badd-66b73efad79f.png)

**Platform information**
 - OS: [macOS]

**Comment by Tantacrul** [comment]
I can see that the score preview does not immediately update, but it does update if you close and reopen MS4 (at least now it does).

I think this is acceptable. Unless anyone has a strong opinion, I think close this as a wont fix.

**Comment by cbjeukendrup** [comment]
It looks like this has already been fixed. @abariska feel free to reopen if you find otherwise.

**Comment by abariska** [comment]
🟢 **FIXED**
