### ISSUE TITLE
Too many 'Stave Types' displayed in the Instruments Panel compared to MS 3.6

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10780]
**Describe the bug**
See video for the full explanation. 

https://user-images.githubusercontent.com/21022311/157869299-c7763456-7895-4059-a422-fdfc497caacd.mov

1. Step one would be to hide any options not displayed in MuseScore 3.6
2 Step two is to also remove any other redundant options (which I'm not 100% sure about yet. There may be reasons there is a 'Standard' and a 'Custom Standard' staff definition for each instrument but I'm not sure what it is.

**Comment by Tantacrul** [comment]
Again @wizofaus - if you're game, this one might be up your alley. It could be the simplest fix ever, but there might be more thinking required.

**Comment by wizofaus** [comment]
Well it doesn't work properly in V3 - the options "Custom Standard"/"Custom Tablature"/"Custom Percussion" staff do nothing at all as far as I can tell, for most instruments it displays as a standard staff (and when you return to the instruments dialog it's ignored what you've selected).  Even if you select something like an unpitched percussion instrument you get a different set of staff types, but again those 3 don't work.  If you select "Classical Guitar (tablature)" as an instrument you get a lot more options, including Standard, but again "Custom Standard/Tablature/Percussion" don't work.
So yes, I think this needs a good deal more thought...

**Comment by Tantacrul** [comment]
I wonder if @Jojo-Schmitz, @jeetee, @MarcSabatella or @shoogle could shed any light?

What are the "Custom Standard"/"Custom Tablature"/"Custom Percussion" options intended to do?

**Comment by Jojo-Schmitz** [comment]
Sorry, no idea

**Comment by jeetee** [comment]
I believe they prevent some reset-behavior when a user changed Advanced Style Properties of a normal staff of each respective type.
See also https://musescore.org/en/node/279897 for a bit of context

**Comment by Tantacrul** [comment]
@oktophonie, would be interested to get your thoughts on this feature: "Custom Standard"/"Custom Tablature"/"Custom Percussion" in general, since they appears to be an option that affects engraving settings.

Are they valuable do you think? Most certainly they are incomprehensible.

**Comment by wizofaus** [comment]
"Custom Standard"/"Custom Tablature"/"Custom Percussion" don't appear in 4 currently, there doesn't appear to be any point in adding them until we understand what they're supposed to do.
But the next problem is that the default staff *name* for, say, Acoustic Guitar (Tablature) is still "Treble clef 8va bassa" which is just confusing...

**Comment by Tantacrul** [comment]
> "Custom Standard"/"Custom Tablature"/"Custom Percussion" don't appear in 4 currently, there doesn't appear to be any point in adding them until we understand what they're supposed to do. But the next problem is that the default staff _name_ for, say, Acoustic Guitar (Tablature) is still "Treble clef 8va bassa" which is just confusing...
> 

Oh, Yuk. Never noticed this before:

- The name doesn't update when you change the staff type
- The dropdown reverts back to 'Standard' even when you change it

**Comment by wizofaus** [comment]
Yes I fixed the latter problem.  But I'm not sure what should happen with the staff name if you change the type - esp. if the user has already given it the name they want.

**Comment by wizofaus** [comment]
Ok I've fixed that too - the staff name is now properly generated from the actual clef type, which is determined by the staff type.  But there's a new problem - in v3 you can add multiple Tablature staves to a Guitar part, but v4 doesn't appear to allow this, at least not from this screen.  Should it? @Tantacrul

**Comment by wizofaus** [comment]
Ok I've now implemented the logic as per v3.  Instruments of type "percussion" only allow the 3 percussion staff types, whereas all others allow the "standard" staff type, and instruments that have more than 0 fretted strings also allow the tablature staff types that don't have more tab lines than the instrument's string count.
You can change, e.g. a guitar from back and forth between "standard" and the supported Tablature types, and the staff name should update appropriately.
The only slightly clunky thing is that now most instruments ONLY allow "Standard", yet still have a drop-down, which arguably should be disabled in that case.

**Comment by Tantacrul** [comment]
I'd definitely agree that the dropdown should be disabled if there is only one option.

**Comment by Tantacrul** [comment]
> but v4 doesn't appear to allow this, at least not from this screen. Should it? @Tantacrul

It should do. Check this out:

https://user-images.githubusercontent.com/21022311/158967469-a82a6ecd-883d-4df8-8127-a725d6a91c5d.mov

**Comment by wizofaus** [comment]
Yes I've restored that ability.  You can try it out with the build from that PR (mac one is here: https://github.com/musescore/MuseScore/actions/runs/2001010457)

**Comment by Tantacrul** [comment]
Just tested. Man, that is so much better! Thanks :)

I do agree (now that I see it) that when there are no options in the dropdown, we should probably disable it.

<img width="258" alt="image" src="https://user-images.githubusercontent.com/21022311/159115019-138fd842-a81b-4130-8036-38f0f7b2af2e.png">

**Comment by Tantacrul** [comment]
Oh, another thing I just noticed. Not sure if this is a simple fix or not but when I save the file, close MS4 and reopen it, the drop downs all revert back to saying 'Standard'.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/21022311/159115291-cce3c472-bc04-4b7a-9a71-95c169f60c10.png">

**Comment by wizofaus** [comment]
Are you saying that happens even with the build from my PR? Because that was something I explicitly fixed...

**Comment by Tantacrul** [comment]
Yeah, from this one here: https://github.com/musescore/MuseScore/actions/runs/2001010457)

I've recorded a video:
https://user-images.githubusercontent.com/21022311/159117602-99e89ee9-2039-440f-bc45-334b0100d269.mov

**Comment by wizofaus** [comment]
Ah ok, yeah, can reproduce that, something definitely wrong when scores are loaded, surprised it isn't having other impacts.

**Comment by wizofaus** [comment]
Ok figured it out, v3 is indeed trying to find the best matching preset based on the other staff properties. It's still true now that it will show "Standard" if the staff type properties *don't* match any of the presets, but I think we can live with that. Have also ensured dropdown is disabled unless there's at least 2 items to choose from.

**Comment by Tantacrul** [comment]
You're the hero we need.

**Comment by wizofaus** [comment]
Let me know how you go with the latest build: https://github.com/musescore/MuseScore/actions/runs/2009875795

**Comment by Tantacrul** [comment]
Just tested it. Both fixes are working perfectly.

**Comment by wizofaus** [comment]
> I believe they prevent some reset-behavior when a user changed Advanced Style Properties of a normal staff of each respective type. See also https://musescore.org/en/node/279897 for a bit of context

Yes, I can understand if you've customized the staff so it doesn't match any preset then logically it could show "Custom <x>" or something similar, and provided you don't change it, it won't modify your customizations. But in v3 they're shown even for non-customized staves, and do nothing if you select them.  I'd think it would make just as make sense to show the combo with no current selection in such a case though, which is a change I could make for v4 if needed.

**Comment by Tantacrul** [comment]
@RomanPudashkin or @Eism, when you have time to review, this fix is looking good to me from a feature point of view.

**Comment by Tantacrul** [comment]
I'm changing this to a P1, since we keep getting issues about it. Also, it is making it really hard to create linked staves that make sense.

Not sure if @wizofaus's fix can be merged or not but the issue is a real pain.

**Comment by wizofaus** [comment]
I just tested the latest nightly build and it still looks wrong to me - e.g. for the "Lead Vocal" part in a score created from the Rock Band template, when adding additional staffs, it shows ALL possible staff types, including Perc./Tab etc.
My PR *did* address this, but apparently never got merged.
@Tantacrul

**Comment by wizofaus** [comment]
My apologies, ignore above, was testing the wrong version - confirmed it's fine in actual latest nightly.
