### ISSUE TITLE
When the New Score dialog is triggered, the search bar should automatically be in focus 

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10791]
**Describe the bug**
When the **New Score** dialog is triggered, the search bar should automatically be in focus so users can immediately begin typing.

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/21022311/157952262-4454e268-5a1d-4416-979a-ee0b536dca72.png">

**Comment by tzarjakob** [comment]
If is this open, can I work on this one?

**Comment by Tantacrul** [comment]
It's all yours!

I'll make sure to test so accessibility isn't broken.

**Comment by tzarjakob** [comment]
While solving, I found this potential improvement: when you open MuseScore the search bar for recent scores is already in focus, so anyone can search immediately without selecting the box manually. Eventually it is not a problem to remove it and leave only the requested one. I am waiting for a feedback.

**Comment by Tantacrul** [comment]
> when you open MuseScore the search bar for recent scores is already in focus, so anyone can search immediately without selecting the box manually

Yes, this is the desired behaviour. Looking forward to testing it out. Can you link to a PR?

**Comment by tzarjakob** [comment]
I think it is almost fixed. Now if you open the new score the search bar is not in focus, but if you select "create from template" and then again on "choose instruments", the bar is in correctly focus. I can't understand why it is not in focus from the beginning... Can I do a PR even if the bug is not completely fixed?

**Comment by RobFog** [comment]
Make the pull request. Others may be able to help with the missing bits. 🙂

**Comment by tzarjakob** [comment]
> Yes, this is the desired behaviour. Looking forward to testing it out. Can you link to a PR?

Here it is: https://github.com/musescore/MuseScore/pull/10920

**Comment by Tantacrul** [comment]
Yep. Only seems to work when switching between templates and 'add instruments'. I agree, perhaps @RomanPudashkin, @Eism or @cbjeukendrup can help when they have time.

**Comment by cbjeukendrup** [comment]
> perhaps @RomanPudashkin, @Eism or @cbjeukendrup can help when they have time

I posted a comment on the PR!

**Comment by Tantacrul** [comment]
@tzarjakob - are you still working on this issue?
