### ISSUE TITLE
Stave lines in palettes are quite harsh and would be easier to read if toned down

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10797]
**Describe the bug**
Stave lines in palettes are quite noisy in places. We could fix this by applying a 50% transparency, or simply choosing a softer colour for them. (I can supply the colours if needed)

Example:
Original:
<img width="108" alt="image" src="https://user-images.githubusercontent.com/21022311/158034603-4463dac4-af47-4477-ab6e-6e9ae410eae6.png">

Becomes:
<img width="111" alt="image" src="https://user-images.githubusercontent.com/21022311/158034640-717fd4d9-c6cd-4173-8fd3-8eb53a3ea54e.png">

When you have loads of these stacked together, it becomes quite noisy and harsh. This simple fix will just add another level of finesse. It is much more necessary for dark mode than light mode but I think it's fine to do it for both.

**Comment by Kissh12** [comment]
Heyy, is this open? Can I work on this?

**Comment by Tantacrul** [comment]
@Kissh12 - with our blessing ;)

If you have any questions or want a build reviewed, please just send me a message.

**Comment by mccoydtromb** [comment]
Is this still open? If so, I think I have a solution. Don't want to step on any toes though. First time contributor, so unsure of any issue poaching guidelines.
![image](https://user-images.githubusercontent.com/92689427/160000828-728e8073-08d8-4422-8486-fd7a542d4cb5.png)

**Comment by Tantacrul** [comment]
> Is this still open? If so, I think I have a solution. Don't want to step on any toes though. First time contributor, so unsure of any issue poaching guidelines.

@Kissh12 ?

**Comment by mccoydtromb** [comment]
If it gets transferred I'll go through the PR system, but would be grateful for a quick code check. It's just 3 lines:

```
Color lighterpen(configuration()->elementsColor());
    lighterpen.setAlpha(int(lighterpen.alpha()*0.5));
    Pen pen(lighterpen);//reduce alpha by half
```

It's been a while since I used C++. Can I just create a temporary color to set the alpha?

**Comment by mccoydtromb** [comment]
I know that everyone is busy with new bugs from the private alpha. Can I submit a PR for this?

**Comment by Tantacrul** [comment]
@cbjeukendrup ?

**Comment by cbjeukendrup** [comment]
Sorry, missed this one!

@mccoydtromb Since we haven't heard anything from other potential contributors on this issue for weeks now, I think we can safely transfer it to you. 

That code basically looks good. I think you can simplify it to the following:
```c++
Color staffLinesColor(configuration()->elementsColor());
staffLinesColor.setAlphaF(0.5); // Use setAlphaF, so set the alpha component on a 0.0 - 1.0 scale; 
                                // you may assume in this case that the old alpha component was 1.0 anyway, so no need to take it into account
Pen pen(staffLinesColor);
```

No worries about memory leaks in this case, as you're just using values, not pointers.

**Comment by mccoydtromb** [comment]
@cbjeukendrup Thanks for the hint! I'll implement that now and then submit the PR.
