### ISSUE TITLE
[MU4 Issue] There is should not be a noticable delay when starting playback right after MU launch (on small scores) 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10807]
**To Reproduce**
1. Run MU
2. Open a small score quickly
3. Start playback

Compare delay in **MU2**, **MU3.6.2** and **MU4**:

https://user-images.githubusercontent.com/90187801/170300776-2da102f5-f314-49d5-996e-2cbb45f54882.mp4

**Platform information**
 Windows 10

**Additional context**
Doesn't occur in **MU 2.0.1**
**Occurs** in **MU3.6.2**

**Comment by Tantacrul** [comment]
@DmitryArefiev - is this issue solved to your satisfaction now?

**Comment by Tantacrul** [comment]
By the way, since we have moved to a new audio system with proper tracks, a little bit of delay is expected. We no longer run a single instance of the Fluid synth.

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev - is this issue solved to your satisfaction now?

@Tantacrul Yeah, I'm OK now because we have **Loading audio samples** progress bar (user will know he needs to wait to hear a sound)
