### ISSUE TITLE
[MU4 Issue] Main pitch should not change after changing default sample rate in audio device settings (Windows10, Realtek Audio Device) 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10804]
**Describe the bug**
On my ASUS laptop I found weird behavior when MU changes its pitch after changing sample rate in Realtek Audio Default settings (Internal Audio Device). 
Pitch should not change and be correct (like it behaves in **MU3**)

Pitch is **not correct** when sample rate is **44kHz**:

https://user-images.githubusercontent.com/90187801/158224147-9144ab40-0513-4698-8777-c46a6080e7e5.mp4

Pitch is **correct** when sample rate is **48kHz**:

https://user-images.githubusercontent.com/90187801/158224292-edc5d672-4e0f-4c79-bd87-30945562050b.mp4

**Expected behavior**
Pitch should be correct in 44kHz and in 48kHz

**Platform information**
Windows10, Realtek Audio Device, ASUS Laptop VivoBook

**Additional context**
Doesn't occur in **MU3**
Should be rechecked after fixing #11748

**Comment by DmitryArefiev** [comment]
related to #9225

**Comment by Tantacrul** [comment]
Two questions:

1. Is this still a problem?
2. Shouldn't this be targeted at **Beta 1**, at least? Also, doesn't it seem more like a P1 than a P2? Especially since I imagine users would never figure out how to fix it.

**Comment by DmitryArefiev** [comment]
@Tantacrul Yes, still occurs in latest master and agree with P2.  Also putting back audio device settings to Preferences might fix the issue #11748

**Comment by Tantacrul** [comment]
> @Tantacrul Yes, still occurs in latest master.  Also putting back audio device settings to Preferences might fix the issue #11748 
> 
> 
> 
> (regarding priority Vasilij was unable to reproduce this issue on his machine with a different version of Realtek Audio Manager)

When - why did audio device get taken out? Seems very unusual not to provide that option. Is there a separate issue for that?

**Comment by vpereverzev** [comment]
@DmitryArefiev should be fine after my fixes to alpha-2. Please, check one more time on the latest master

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev should be fine after my fixes to alpha-2. Please, check one more time on the latest master

@vpereverzev Yes, it looks now! Checked on the **latest master**, the same ASUS laptop, Windows 10
