### ISSUE TITLE
[MU4 Issue] Mixer issues: metronome track position and failed refresh when instruments are deleted

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10815]
**Describe the bug**
Two (or three) issues here:

1. The metronome track should remain aligned to the immediate left of the master track when new instruments are added. This currently does not take place (i.e. new instruments in the mixer are stacked to the right of the metronome track). 
2. Removing instruments by the `undo` command fails to remove them from the mixer.
3. Removing instruments from the **Instruments** dialog fails to remove them from the mixer. 

Demo video: https://www.dropbox.com/s/44giq806fskwihb/three-mixer-issues.mov?dl=0

**Expected behavior**
As above: 
1. Mixer should remain aligned to immediate left of Master track when new instruments are added. 
2. Tracks should be removed when instruments are removed. 3. 

**Platform information**
 - MacOS 12.1 (M1)

**Comment by jessjwilliamson** [comment]
Absolutely agree!

**Comment by Tantacrul** [comment]
Seems like a P1 candidate to me.

**Comment by cbjeukendrup** [comment]
Working on it as we speak! :)
