### ISSUE TITLE
[Improvement] Playback options for ornaments are not implemented in the Inspector (Properties)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10825]
1. Playback drop down menu is greyed out
2. No difference between **Standard** and **Baroque** performance style for all ornaments except trill

![MU4](https://user-images.githubusercontent.com/90187801/158618976-260fe9dd-893d-4c6b-915d-0240fef0644a.PNG)

**Platform information**
macOS, Windows, Linux

**Additional context**
Those options are not working properly in MU3 as well..

1. As a Playback options in MU3, there is a **Time stretch** option but it also doesn't work 
2. No difference between **Default** and **Baroque** ornament style too (for all ornaments except trill)

![MU3](https://user-images.githubusercontent.com/90187801/158619817-fe91950d-0e6e-4334-9ad5-ecddb41904ff.PNG)

**Comment by miiizen** [comment]
Currently looking at this :)

**Comment by miiizen** [comment]
Regarding the baroque playback options, would it be worth greying the buttons out if there's no applicable baroque style?

**Comment by DmitryArefiev** [comment]
@miiizen Yes for now.. But that will not fix the main issue :)

**Comment by Tantacrul** [comment]
We removed these options because they don't do anything in MS3. It's been a while but I recall being told that this was an incomplete feature. Closing for now. Please let me know if you think this is an error. Thanks!

**Comment by miiizen** [comment]
Sorry, I've been meaning to get back to this for a while.  The draft PR implements time stretch - if that's a feature that is wanted it's ready to be merged!  
Regarding the baroque performance style, I've been meaning to say I don't think there's any difference needed in playback apart from those which are implemented already.  If the feature's just going to be removed this isn't a problem though.  Thanks!

**Comment by Tantacrul** [comment]
Is time stretch working in your PR? If so, then cool. If not, then I think we just abandon the PR. Thanks though!

**Comment by miiizen** [comment]
Ah just taken a closer look and it's not really working as I'd like.  Never mind, I'll close it!
