### ISSUE TITLE
[MU4 Issue] Crash in v4 opening score saved in v3

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#10831]
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**
1. Unzip the attached score
[direction.zip](https://github.com/musescore/MuseScore/files/8283539/direction.zip)

2. Open it in MuseScore 3, choose Ignore. It will display blank. Leave it open long enough that auto-save occurs (or manually save it).

4. Now open it in V4. V4 crashes.

We probably can't help the fact that V3 isn't able to preserve the score data, but V4 shouldn't crash trying to open it.

**Screenshots**

**Platform information**
Windows

**Additional context**

**Comment by RomanPudashkin** [comment]
Thank you for reporting! Should be fine after https://github.com/musescore/MuseScore/pull/10793

**Comment by Jojo-Schmitz** [comment]
That fix BTW solves both, the crash **and** the empty score
