### ISSUE TITLE
[MU4 Issue] "Keep going" button does not return user to "getting started" flow when attempting to close dialog

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10835]
**Describe the bug**
Closing the "getting started" dialog with the "x" window button triggers a dialog that invites users to "Cancel" or "Keep going".
When the user clicks "Keep going", the entire "getting started" dialog closes.
This shouldn't happen. Instead, only the "do you want to cancel" dialog should close, but the actual "getting started" dialog should remain open. 
This should affect ALL screens in the dialog. 

![getting-started-exit](https://user-images.githubusercontent.com/86290556/158945206-b85595f4-b911-4128-ac6e-103f0006a8e8.gif)

**Platform information**
 - MacOS 12.1 (M1)
 - Not yet tested on Windows

**Comment by DmitryArefiev** [comment]
@bkunda Just in case, the 'Cancel/Keep going' dialog doesn't appear after closing the last Video tutorials dialog with X

https://user-images.githubusercontent.com/90187801/160189773-9fdd99e2-b0c7-40b7-b877-ec04273910d8.mp4

**Comment by bkunda** [comment]
> @bkunda Just in case, the 'Cancel/Keep going' dialog doesn't appear after closing the last Video tutorials dialog with X
> 
>  bandicam.2022-03-25.21-16-28-157.mp4

This certainly makes sense. Thanks @DmitryArefiev!
