### ISSUE TITLE
[MU4 Issue] Wrong explorer in latest build on Linux (Qt's dialog instead of Native dialog)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10836]
Wrong explorer in latest build on Linux when using Save as or Open dialogs

**Actual:**
![Снимок экрана от 2022-03-17 18-27-50](https://user-images.githubusercontent.com/90187801/158977876-f13cfc1b-0281-406b-bf57-88698f071c24.png)

**Expected:**
![Снимок экрана от 2022-03-17 18-26-11](https://user-images.githubusercontent.com/90187801/158977856-da886826-9042-46f6-986f-2282f4ba43b7.png)

**Platform information**
 Linux Mint 20.2

**Additional dialog**
- Qt's file dialog is **buggy** (e.g. it doesn't save score if it was entered without extension and I can't open a score from a flash drive)

- In the "wrong", unexpected save/open dialog, all key presses are consumed by the main window. E.g. Return inserts a line break in the score instead of opening a file (see comment below)

**Comment by Jojo-Schmitz** [comment]
Is that Native file dialog vs. Qt's file dialogs?

**Comment by DmitryArefiev** [comment]
Yes, looks like it is. 

> MuseScore 3 has an (advanced) option to change between them

Thanks! I've founded it in MU3 (and it's turned on by default) but it's missing in MU4
![Capture](https://user-images.githubusercontent.com/90187801/158992604-a2430412-3563-4082-a528-c6873e506c22.PNG)

**Comment by Eism** [comment]
I tested a little and noticed that the dialog is different when building on my laptop(Ubuntu) and on CI.

So, first we need to understand the reason for this behavior.

Laptop
![image](https://user-images.githubusercontent.com/10116828/158993261-3de56e24-49ac-4b33-8ff6-f0c6c5ea3c36.png)

CI
![image](https://user-images.githubusercontent.com/10116828/158993355-9b4c1310-560f-4229-991a-b39bdd30952a.png)

**Comment by schoettl** [comment]
Not sure if I should create a new issue for that:
In the "wrong", unexpected save/open dialog, all key presses are consumed by the main window. E.g. Return inserts a line break in the score instead of opening a file.

**Comment by DmitryArefiev** [comment]
> Not sure if I should create a new issue for that:
> In the "wrong", unexpected save/open dialog, all key presses are consumed by the main window. E.g. Return inserts a line break in the score instead of opening a file. (Today's master branch on Linux.)

@schoettl  Let's leave it here for now (I don't know if we want to give to the user the option to switch between QT's and Native dialog). I'll just add it to the description. 


> Maybe related #10460

I think the Qt's dialog is more buggy.. I even can't Tab within the window (Navigation is not working)

Thanks for adding details!

**Comment by Jojo-Schmitz** [comment]
> Thanks! I've founded it in MU3 (and it's turned on by default) 

It used to be off by default for Linux, but at one point (3390aab3) that got changed. IMHO for the worse, see #7739 and https://musescore.org/en/node/297613

**Comment by DmitryArefiev** [comment]
Fixed in #12111
