### ISSUE TITLE
Onboarding process no longer starts in the main 'Score' tab. Rewording of Tutorial description needed. App should start maximised.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10848]
**Describe the bug**
When opening the app for the first time, the opening screen overlays the 'Home' tab. The 'Score' tab should be selected at this point, so the user has a better idea of how the theme colour will affect the main UI. This will also make the transition to the 'Learn' section more obvious.

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/21022311/159135739-af9597ac-90b0-44d6-ba37-081db4884721.png">

Secondly, when the popup describes the tutorial section, the wording should be revised. Rather than saying 'this is the 'Learn section', it should be clearer, saying something like: 'Behind me, is the 'Learn' section...', or 'When you close this popup, you will see the 'Learn' section', etc. I don't have an exact wording in mind. The current wording just seems a little strange, since it seems to be referring to itself. Almost as if it is saying 'This is the 'Learn' section of this popup'.

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/21022311/159135819-398cf428-48e0-45e6-a038-94d5dd580ad6.png">

Lastly, when the app is first launched, it should open maximised. Currently, it open in a little window, which is a bit annoying. Each time, my first action is to maximise it. This will avoid the problem of the popup overlapping most of the UI too.

**Comment by Nikos410** [comment]
> Lastly, when the app is first launched, it should open fullscreen.

@Tantacrul I'm not really a fan of applications starting in fullscreen without being asked to do so. Do you really mean fullscreen or maximized?

**Comment by Tantacrul** [comment]
Maximised. Thanks for pointing that out!

**Comment by bkunda** [comment]
@cbjeukendrup @Eism micro-copy for the final screen will read: "Behind this dialog is the 'Learn' section, where you'll find tutorials to get you started (Video tutorials require an internet connection)"

<img width="956" alt="Screenshot 2022-03-22 at 8 17 27 pm" src="https://user-images.githubusercontent.com/86290556/159447860-038702e3-0646-47c4-acbb-80505b75c5ea.png">

Thanks!

**Comment by cbjeukendrup** [comment]
I added the micro-copy fix to PR #10847.

About whether the Home page or the Score page should be visible: it's trivial to change it back, but a while ago, we made the decision to show the Home page instead because that gives a good impression of the theme as well and may look nicer than the empty score page with only disabled UI elements. See https://github.com/musescore/MuseScore/pull/10174#issuecomment-1004548429.

**Comment by Tantacrul** [comment]
Yes, I chatted to @bkunda about this. I don't think the Home panel is the right page to land on for a few reasons and I do think we should change it back to the main score page.

I think it's more appropriate to see the main UI - which is what you are specifically deciding on at that point, including the BG colour. The Score tab is where you are going to be living 95% of the time, so it makes sense to be making the decision there. Moreover, the popup is already in front of the UI, so the absence of a score isn't really much of a problem. What bothers me most though is that you don't notice the changes between screens in the current version because they both look really similar. The transition felt more effective before.

**Comment by cbjeukendrup** [comment]
Ok, fix added to #10847!

**Comment by boryskuzmenko** [comment]
Tested.
FIXED
