### ISSUE TITLE
[MU4 Issue] After score navigation, wrong button is selected in "Do you want to save changes.." dialog

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10840]
**Describe the bug**
After score navigation, wrong button is selected in "Do you want to save changes.." dialog: 
**Don't save** is selected instead of **Save**

https://user-images.githubusercontent.com/90187801/159044831-a326bb96-4dc3-4e5a-8698-9ba59eb7f59d.mp4

**To Reproduce**
1. Navigate with Tab and left/right arrows 
2. Make some changes in the score
3. Press Ctr+W to close the score - **Don't save** is selected in "Do you want to save changes.." dialog (if you press Return you changes don't save)

**Expected behavior**
**Save** button should be selected

**Screenshots**

**Platform information**
 macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by HemantAntony** [comment]
Pretty sure this is a Good First Issue

**Comment by DmitryArefiev** [comment]
@HemantAntony  Good. Will add the label. Thanks!

**Comment by tzarjakob** [comment]
On Ubuntu it works fine, if Return is pressed the file is saved regularly

**Comment by DmitryArefiev** [comment]
> On Ubuntu it works fine, if Return is pressed the file is saved regularly

@tzarjakob Have you tried navigation with Tab?
