### ISSUE TITLE
[MU4 Issue] [MacOS] Global system shortcuts (e.g. Cmd+C, Cmd+V) can't be called when non-English language used 

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#10854]
TBD

**Comment by Tantacrul** [comment]
Is this still happening? I'm not an English speaker but is this definitely the desired functionality?

**Comment by boryskuzmenko** [comment]
@Tantacrul yep. And it's pretty annoying if you use another languages on keyboard

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/10857
Tested on macOS 12, Win 11, Ubuntu 20
