### ISSUE TITLE
[MU4 Issue] [Improvement] Score tab should indicate if it has an opened score when switching to other tabs (Home, Publish, DevTools)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10859]
**Describe the bug**
Score tab should indicate if it has an opened score when switching to other tabs (Home, Publish, DevTools)
Score tab ("Score" text) can be bold and maybe highlighted but **NOT underlined** showing that there is an opened score already, when user doing something on Home, Publish or DevTool tab.

https://user-images.githubusercontent.com/90187801/159350217-87a621ff-4468-4f89-be64-9762053457af.mp4

**Platform information**
macOS, Windows, Linux

**Expected result**
If there is an opened score in MU, **Score tab should be bold but not underlined** when clicking/navigating Home or Publish or DevTools tab.

**Comment by DmitryArefiev** [comment]
@Tantacrul @bkunda @jessjwilliamson What do you think about this improvement (and the expected result)?

**Comment by Tantacrul** [comment]
I'm not sure I understand exactly. So, if the Score tab has no opened score, if I click on it, it should just highlight and the text should be bold but there should be no underline?

I do like the idea of trying to trying to help indicate to the user when a score is open.

**Comment by DmitryArefiev** [comment]
> I'm not sure I understand exactly. So, if the Score tab has no opened score, if I click on it, it should just highlight and the text should be bold but there should be no underline?

I think there should not be changes in the behavior (it should be bold, highlighted and underlined when click on it even if it has no opened score (empty))

The changes here are only when user has an opened score and wants to click on Home/Publish/DevTools tabs. In that case Score tab should be bold and maybe highlighted but **NOT underlined**

Sorry for my English 🙂

**Comment by Tantacrul** [comment]
OK, I get it now :)

I don't really know, to be honest. Jess? Could you try this idea out as a mockup when you've time?

**Comment by DmitryArefiev** [comment]
https://user-images.githubusercontent.com/90187801/160824223-d069fbb9-55d3-4eff-a763-15d5541d6416.mp4

@Tantacrul @jessjwilliamson Please see the video. 

1. Roman has made the initial solution for now: **"Score" text is bold** when score is opened and user navigates other tabs. 

2. Also, Roman suggested to mark score preview pictures with some mark (check mark for example) on Home>Score page, to mark score (scores) that are opened.  Something like we want to do with a cloud scores as I understand. 
This item requires a design decision. 


What do you think about №1 and №2?  (as you see, №1 can be implemented already)

**Comment by Tantacrul** [comment]
I have no problem with this.

About the second idea. I'll ask @jessjwilliamson to work on it.

Jess: basically, if you already have a score opened, then it should have a little 'tick' mark in the home tab so users don't try to open a score that's already opened :)

**Comment by jessjwilliamson** [comment]
> I have no problem with this.
> 
> About the second idea. I'll ask @jessjwilliamson to work on it.
> 
> Jess: basically, if you already have a score opened, then it should have a little 'tick' mark in the home tab so users don't try to open a score that's already opened :)

Yeah I have no problem either, seems simple enough 👍
