### ISSUE TITLE
[MU4 Issue] Backwards/Forwards buttons (In 'General' / Properties panel) have no effect

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#10877]
Edited by Martin:

What we need is the same options you find in most creation software. Basically four buttons that do the following:

**Forwards** (looks at the items in front of it and moves in front of the nearest item)
**To front** (looks at the items in front of it and moves in front of the item furthest to the front)
**Backwards** (looks at the items behind it and moves behind the nearest item)
**To back** (looks at the items behind it and moves behind the one furthest back)

**Design mockup**
<img width="292" alt="APPEARANCE_POPUP_SNAP_OFF_V2c" src="https://user-images.githubusercontent.com/86290556/171202958-e853820b-2cc8-4c76-b6b2-eacf85c4c180.png">

Link to Figma file (internal team only): https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/Musescore-Notation-App-MASTER?node-id=1621%3A74746

**Comment by DmitryArefiev** [comment]
@MarcSabatella @Tantacrul As I see, Backward/Forwards buttons are equivalent of Stacking order (Z) feature in MU3 (up/down controls). 
But in MU3 the user seeing the changes of actions in the numeric field. 
In MU4 we don't have that numeric field and user doesn't see the changes in Properties (only in score).

https://user-images.githubusercontent.com/90187801/170740314-2caf4171-87db-43ba-9a8c-89f8cdf93a69.mp4

So one of the fix can be putting a numeric value to Arrange section showing the object's layer in score.
The same as MU3 does in the stacking order field:


https://user-images.githubusercontent.com/90187801/170740905-bf8c3b0f-e0f9-44e3-846f-269052bd267f.mp4



(I guess we can delete extra zeros and use only xx or x format)

**Comment by Tantacrul** [comment]
@DmitryArefiev: I think we need a more sensible interface for this. A textbox (like in MS3) is just ridiculous.

What we need is the same options you find in most creation software:

**Forwards** (looks at the items in front of it and moves above the closest one)
**To front**  (looks at the items in front of it and moves above the top one)

**Comment by MarcSabatella** [comment]
Right, I agree most users don't need to be able to set via a text field, even if it *is* useful to some of us.  But again, the real issue is that to forwards button *doesn't work* as described above.  It doesn't look at the elements in front, it just decrements the stacking order by a fixed amount.  And thus you have to press it literally dozens of times.  making it seem it just isn't working at all.

**Comment by Tantacrul** [comment]
> Right, I agree most users don't need to be able to set via a text field, even if it _is_ useful to some of us. But again, the real issue is that to forwards button _doesn't work_ as described above. It doesn't look at the elements in front, it just decrements the stacking order by a fixed amount. And thus you have to press it literally dozens of times. Making it seem it just isn't working at all.

Yes. The current functionality is not working as expected.

**Comment by Tantacrul** [comment]
@bkunda - can you mock this up? I've changed the issue description to explain what is needed.

**Comment by MarcSabatella** [comment]
FWIW, the recent PR to add To Front / To Back buttons includes some of the needed code to fix this.  But it's a bit off, it looks at the entire page rather than just the element that overlap the current element.

**Comment by bkunda** [comment]
> 

I'll do this today.

**Comment by DmitryArefiev** [comment]
The main issue (Backwards/Forwards buttons have no effect) looks much better after #11760, but the design change (buttons consequence) still needs to be implemented

**Comment by DmitryArefiev** [comment]
The only issue left is on UI side: **Buttons consequence should be changed** 

See master

![Untitled](https://user-images.githubusercontent.com/90187801/197168788-d7235a2b-de1a-4a4f-856b-f9c03736870c.png)

and compare with design mockup in Description

**Comment by Tantacrul** [comment]
Nice catch @DmitryArefiev 
<img width="522" alt="image" src="https://user-images.githubusercontent.com/21022311/197172400-3d3c2de9-6e30-48e3-9fc6-1f09abe7073f.png">
