### ISSUE TITLE
[UI] Popups not closing when 'clicking away' on the inspector

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10871]
**Describe the bug**
See video (below). When opening a popup, you can not click elsewhere on the UI to dismiss it. This is one of those bugs that tends to reappear every once in a while, unfortunately :(

https://user-images.githubusercontent.com/21022311/159536162-45323520-43b0-4e9d-93f9-56ec82b87f0a.mov

**Comment by boryskuzmenko** [comment]
**FIXED**
OS: macOS 12, WIN 11
