### ISSUE TITLE
[MU4 Issue] Search fields: The first entered space shows all elements that contain a space in their names

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10879]
**Describe the bug**
The first entered space shows all elements that contain a space in their names.
It occurs in New Score>Search, Instruments>Search, Palettes>Search, Scores>Search

**To Reproduce**
1. Click search field
2. Hit space one time

https://user-images.githubusercontent.com/90187801/159783363-41f0bc7e-1133-43db-ba93-efbfc0a952d1.mp4

**Expected behavior**
Single space without any letter should not trigger a search

**Platform information**
macOS, Windows, Linux

**Additional context**
Occurs in **MU3**

**Comment by the-next-ceo** [comment]
https://user-images.githubusercontent.com/66167731/166812975-a8439ff4-438c-4d9c-b05e-4352e44a2977.mov

**Comment by DmitryArefiev** [comment]
@the-next-ceo  Thanks for fixing!

**Comment by DmitryArefiev** [comment]
Fixed in #11314
