### ISSUE TITLE
[MU4 Issue] Some dynamic options in the Inspector should be hidden because they don't make any changes

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10893]
Some dynamic options in the Inspector (Properties) should be hidden because they don't make any changes:

- Text>Font
- Text>Style

https://user-images.githubusercontent.com/90187801/159981499-e958b36c-4691-4d49-859a-c6cd05e3ef82.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Occurs in MU3 as well

**Comment by cbjeukendrup** [comment]
These options do affect extra text that is added to the dynamic marking, for example, if you want to write _più forte_:
<img width="480" alt="Schermafbeelding 2022-03-24 om 19 27 49" src="https://user-images.githubusercontent.com/48658420/159985607-48a6fd5d-ba15-4001-a57c-e14e2ae0e87b.png">

**Comment by jeetee** [comment]
Please keep these text options.
While they don't affect the symbols in the marking there are plenty of times where a marking needs a slight addition (such as the above or "*subito*" etc.

Same for coda and segno markers for example, where the default text element for them only contains the symbol. But there as well font settings do make sense for whenever the symbol is amended for clarity.

**Comment by DmitryArefiev** [comment]
@cbjeukendrup @jeetee Oh I see now.. You are absolutely correct those options should be there. 
Thanks for the clarification!

**Comment by DmitryArefiev** [comment]
Working as expected.

Closing
