### ISSUE TITLE
[MU4 Issue] Loud distorted sound when adding an Audio VST FX ⚠️

### ISSUE THREAD

**Issue by KaiVinter** [musescore/MuseScore#10900]
**Description**
I found a weird audio bug that might actually hurt your ears. I don't know if it's known:

**Steps to reproduce the behavior:**
1. Create a score with some instruments (Probably only one is needed. Although, I used Piano, 2 Violin sections, 1 Viola Section, 1 Celli Section and 1 Contrabass section).
2. Add some notes to an instrument (I used the first one, Piano)
3. Go to Mixer
4. Add an Audio VST FX (I used FabFilter's Pro-MB)

5. ⚠️  [WARNING] Turn down your volume to the lowest (not 0, though). ⚠️

6. Select a note on the same instrument.

**Expected behavior:**
Normal audio from selecting a note.

**Current behavior:**
Loud long distorted sound with heavy clipping.

I hope nobody finds this the hard way.

**Screenshots**

![Screen Shot 2022-03-24 at 3 11 33 PM](https://user-images.githubusercontent.com/88064903/160018760-7b2841bf-0d34-4424-af36-b15d85241b18.png)

**⚠️  Video ⚠️**

https://user-images.githubusercontent.com/88064903/160019593-8f253ad8-2bac-43d9-a36c-6375ec9a6c28.mp4

**Platform information**
 - OS: macOS Mojave 10.14.6

**Comment by vpereverzev** [comment]
@KaiVinter 

It was fixed on these builds already (or you can grab the latest nightly)

- Lin - https://github.com/musescore/MuseScore/suites/5790217393/artifacts/193231049

- Win - https://github.com/musescore/MuseScore/suites/5790217395/artifacts/193236250

- Mac - https://github.com/musescore/MuseScore/suites/5790217387/artifacts/193235122
