### ISSUE TITLE
[MU4 Task] Implement cross-staff beaming button in note input toolbar

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10908]
**Task description**
This is a task to add a button for cross-staff beaming into the note input toolbar. 

The button will trigger a context menu – much the same as the current behaviour for the tuplet button. 

The actions will be identical to the current keyboard shortcut commands "move chord/rest to staff above" and "move chord/rest to staff below". We are not adding any new functionality to this feature at this stage.

<img width="912" alt="Screenshot 2022-03-25 at 11 53 41 pm" src="https://user-images.githubusercontent.com/86290556/160124337-1a430eba-8198-40de-b67f-d8ccafc7bff9.png">

Please see this Figma file for the full design spec: https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/Musescore-Notation-App-MASTER?node-id=23179%3A569821

The relevant icon has been added to `musescoreicon` in position U+F43D

Let me know if you have any questions,
Thanks!

**Comment by HemantAntony** [comment]
I am attempting to work on this :)
