### ISSUE TITLE
[MU4 Issue] Space bar to press play doesn't work on Mac OS

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#10909]
Quick issue to report, pressing space bar on Windows works, but not on Mac. Would appreciate this gets fixed :)

**Comment by cbjeukendrup** [comment]
Hm, for me, space bar just works on macOS...

**Comment by Eism** [comment]
for me too

**Comment by jessjwilliamson** [comment]
Huh...  now it's working how bizzare! Will close this! Thanks guys :)

**Comment by Jojo-Schmitz** [comment]
Did you press hard enough?  ;-)

**Comment by jessjwilliamson** [comment]
> Did you press hard enough? ;-)

I slammed it hard with my overpriced iPhone and that didn't work, ended up with broken iPhone screen. "It just works!"

**Comment by Jojo-Schmitz** [comment]
Ah, loaded the good old spider app.

**Comment by HemantAntony** [comment]
> > Did you press hard enough? ;-)
> 
> I slammed it hard with my overpriced iPhone and that didn't work, ended up with broken iPhone screen. "It just works!"

You wouldn't have that issue with my Nokia Phone

**Comment by Jojo-Schmitz** [comment]
AKA "The Brick"
