### ISSUE TITLE
[MU4 Issue] Tabbing around while inputting additional score information is out of order.

### ISSUE THREAD

**Issue by MajesticString** [musescore/MuseScore#10919]
**Describe the bug**
Upon creating a new score, when inputting "Additional Score Information", tabbing around doesn't select the right inputs

**To Reproduce**
1. Create a new score (ctrl + N or other)
2. Get to the Additional Score Information
3. Click the title input
4. Press tab

**Expected behavior**
The selected input would be Composer, Instead, it selects the "key signature"

**Screenshots**
![2022-03-26_12-08-51_AdobeCreativeCloudExpress (2)](https://user-images.githubusercontent.com/66224939/160253801-3fbe7a22-e58c-47a6-96ba-b69287165f9e.gif)
(sorry its so low quality)

**Platform information**
 - OS: Windows 11

**Comment by RobFog** [comment]
@vpereverzev This should probably be targeted for the public alpha. There have been plenty of reports.

**Comment by DmitryArefiev** [comment]
Fixed in #11233
