### ISSUE TITLE
VST: Dynamic information does not seem to be interpreted by VSTs

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#10915]
**Describe the bug**
When setting dynamics, like PP<FFF, the soundfont will respect them but VST's don't.

**Expected behavior**
Dynamics should determine MIDI velocity information to be sent to VST. I assume it is already doing that and simply isn't working right now.

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/21022311/160236443-fb911f06-f18b-42f0-ad2f-9b42c3a74922.png">

https://user-images.githubusercontent.com/101250347/161255403-b9415dec-c150-4b9a-8fee-624afa4c8583.mov

**Comment by mccoydtromb** [comment]
I may be preaching to the choir here, but as far as I understand, VSTs use a variety of messages for information regarding dynamics, and sometimes a combination.
For instance, Spitfire's standard practice uses velocity for short samples (such as staccato brass), but Modulation (CC1) to change between levels of dynamic recordings and Expression (CC11) to adjust the volume of the samples.

MuseScore 3 (I'm not sure what MU4 works off of) produces Breath Control (CC2) data from dynamic markings. In MU3 you could change this in the Synthesizer, but that's no longer available in MU4, so we need to provide some kind of mapping structure (perhaps provided in templates based on VST brand) that will produce the correct MIDI information for the current VST.

**Comment by vpereverzev** [comment]
Fixed in #12568
