### ISSUE TITLE
[MU4 Issue] render bug when select same notes in different voices and scaling

### ISSUE THREAD

**Issue by Fince10086** [musescore/MuseScore#10917]
**Describe the bug**
When selecting the same notes in different voices and scaling, the order of the voices covered will be random.

https://user-images.githubusercontent.com/87692117/160241021-b521681a-a99d-4bc1-8833-d6acb9418b53.mp4

**Expected behavior**
the voice 4 should always cover voice 3, and the 3 cover 2, 2 cover 1. Just likes in MuseScore 3:
![image](https://user-images.githubusercontent.com/87692117/160241165-badc9d26-0d6d-470e-897e-336a57dd0ea5.png)

**Additional context**

**Comment by KaiVinter** [comment]
It doesn't seem to be random, though. It follows the 1-3-2-4 Pattern (1 & 3 ↑ and 2 & 4 ↓)

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS, Win11, Linux
