### ISSUE TITLE
[MU4 Issue] Properties. 'Text style' drop-down can't be collapsed by clicking on Properties free space 

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#10925]
**Describe the bug**
'Text style' drop-down can't be collapsed by clicking on Properties free space. Exception only is area on the right and left from the drop-down.

**To Reproduce**
1. Open MU4 
2. Create/open score
3. Select Title text
4. In Properties click 'More' 
5. Open Text style drop-down
6. Try to collapse the drop-down by clicking around the Properties dialog

**Expected behavior**
'Text style' drop-down can be collapsed by clicking on Properties free space 

**Screenshots**

https://user-images.githubusercontent.com/101250347/160301491-6a756176-edde-4b9b-a2cc-f11134707ef1.mp4

**Platform information**
macOS, Windows, Linux

**Comment by micpap25** [comment]
Hi @boryskuzmenko , it seems that the nature of this issue has changed due to changes in how the "More" dropdown works. It's caused other problems like #10995 but I believe this is resolved. 

https://user-images.githubusercontent.com/34077605/163068594-0aef190b-8464-4ee3-8c6f-6f437a85f78e.mp4

**Comment by boryskuzmenko** [comment]
The issue can not be reproduced anymore on all platforms.
**Closed**
