### ISSUE TITLE
[MU4 Issue] no chord symbol playback

### ISSUE THREAD

**Issue by s1m0n-github** [musescore/MuseScore#10921]
**Describe the bug**
The chord symbols don't have any sound playback, if they aren't realized via the `realize chord symbols` action _(play ticked on in the properties panel)_

**To Reproduce**
1. Create a new score
2. Click on some rest or note, then hit Ctrl + K, type some chord (e.g. Cmaj7), then hit Return
3. Play back the score or measure or click on the chord symbol once
4. See error: no sound played

https://user-images.githubusercontent.com/90187801/161310485-73bd42c4-7d81-4935-aa21-226b90c6883d.mp4

**Expected behavior**
Like in MS3, would expect sound both in playback and on click

**Platform information**
 - OS: openSUSE Linux, latest AppImage (builds 03/27, 03/26, 03/17, 02/28 tested)
 - also occurs in Win/Mac

**Comment by s1m0n-github** [comment]
Also creating the symbol looks glitchy, the type dialogue doesn't disappear when pressing return

https://user-images.githubusercontent.com/98892639/160281737-6e31c21f-b008-43f4-a6a1-9c1f904e1d7f.mp4

It only disappears when clicking with the mouse

**Comment by DmitryArefiev** [comment]
Thanks for catching this!

**Comment by DmitryArefiev** [comment]
> Also creating the symbol looks glitchy, the type dialogue doesn't disappear when pressing return
> Bildschirmaufzeichnung_vom_27.03.2022__14.37.18.mp4
> 
> It only disappears when clicking with the mouse

I already logged that in #10435. And also added your comment there. Thanks!

**Comment by DmitryArefiev** [comment]
Hi @Tantacrul , just in case, do we want to fix that in MU4? 
Also, bring back the 2 features: playback when entering chords and playback when clicking chords? (or maybe only the second one?)

**Comment by Tantacrul** [comment]
We should fix all of these. It's not good to drop the playback features unless there are significant technical problems with doing so.
