### ISSUE TITLE
[MU4 Issue] Strings playback have audible gaps inbetween notes

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#10942]
Spoke with @bkunda about this as I wasn't sure if to raise this issue in case I was wrong but it does seem there are some audible gaps in-between each note when it comes to bowed strings (violin, violin II, viola, cello, contrabass). They do not play continuously as demonstrated in MS3 version. I tried another instrument like Soprano and that seems okay so at the moment I only know strings has this issue. 
The only way to fix this issue is adding slurs.. which is not the answer when making a score to have slurs everywhere!

https://user-images.githubusercontent.com/71656189/160603681-17607905-5b73-400e-92cf-dff231428a27.mp4

**Comment by MarcSabatella** [comment]
It's not just strings; I hear this on other instruments too.  I thought playback simply wasn't finished yet or I'd have commented sooner.  See for instance https://musescore.com/marcsabatella/reunion.  This is the former demo song shipped with MuseScore for years, and one I often use as a basis for comparison.

**Comment by jessjwilliamson** [comment]
> It's not just strings; I hear this on other instruments too. I thought playback simply wasn't finished yet or I'd have commented sooner. See for instance https://musescore.com/marcsabatella/reunion. This is the former demo song shipped with MuseScore for years, and one I often use as a basis for comparison.

Good to know, thank you Marc for your input :)

**Comment by Tantacrul** [comment]
This is actually my fault. We set an MPE preset to treat slurred notes as legato and non-slurred notes as non-legato.

We just need to reset this parameter and we'll have legato back again. It's actually really bad as is. Sorry! At least it's an easy enough fix (I think).

**Comment by Tantacrul** [comment]
The issue of large gaps between un-slurred notes seems to have been fixed. There are other refinements needed for when slurs **are** added but this particular issue is fixed. (Tested MacOS)

**Comment by jessjwilliamson** [comment]
> 

I just re-produced the exact same as video above I made in March. Unless there was intention for a more realistic/better playback, I'm still hearing gaps. Definitely less obnoxious but if I have a score using legato whole notes for orchestral strings, these gaps in this context doesn't glide well. - I have a 4 string piece with BBC orchestra and these gaps also appear. Unless I have to have slurs in every whole note.

**Comment by Tantacrul** [comment]
> > 
> 
> I just re-produced the exact same as video above I made in March. Unless there was intention for a more realistic/better playback, I'm still hearing gaps. Definitely less obnoxious but if I have a score using legato whole notes for orchestral strings, these gaps in this context doesn't glide well. - I have a 4 string piece with BBC orchestra and these gaps also appear. Unless I have to have slurs in every whole note.

Can we see this video?

**Comment by Tantacrul** [comment]
It's interesting, I can only hear a minuscule difference between MS3 and MS4 now for the solo violin. Nothing like the playback in your original issue Jess. So if we can hear what your score sounds like now, that'd be very interesting. Cheers!
