### ISSUE TITLE
[MU4 Issue] Mouse's Scroll Wheel does not work when on 'Instruments' Tab

### ISSUE THREAD

**Issue by Darkspeen** [musescore/MuseScore#10956]
**Describe the bug**
Using the scroll wheel within the tab of instruments does not work.

**To Reproduce**
1. Add more than 20 instruments to the score
2. Click on the 'Instruments' tab
3. Try to scroll down the list with the mouse scroll wheel

**Expected behavior**
Just like the 'Palettes' tab it should scroll down with the mouse scroll wheel instead of having to use the scroll bar 

**Platform information**
 - OS: Windows 10

**Comment by GabeS573** [comment]
It also does not work when trying to two-finger scroll using a touchpad. (Windows 11)
