### ISSUE TITLE
[MU4 Issue] Improper scaling in continuous view (measure width becomes too large)

### ISSUE THREAD

**Issue by Tegze** [musescore/MuseScore#10955]
**Describe the bug**
Horizontal scaling is too large in continuous view

**To Reproduce**
1. Create a new score with two or more instruments
2. Switch to continuous view (bottom right)

**Expected behavior**
Scaling should be based on the current notes

**Screenshots**
![image](https://user-images.githubusercontent.com/38992967/160693671-6acb57e8-867a-4e9f-8599-71bf70e6741c.png)
![image](https://user-images.githubusercontent.com/38992967/160693702-d4e52b1f-a373-401c-b19b-c0c489462189.png)

**Platform information**
Windows 10, macOS, Linux

**Additional context**
Continuous view works properly with one instrument

**Comment by DmitryArefiev** [comment]
https://user-images.githubusercontent.com/90187801/160809629-e93ff0bf-e362-4f05-9225-e484239645de.mp4

Can reproduce on my side as well. Measure width becomes too large in continuous view.

Thanks for catching this!

**Comment by DmitryArefiev** [comment]
Can be related to #10973

**Comment by DmitryArefiev** [comment]
Fixed in #10980
