### ISSUE TITLE
[MU4 Issue] Windows auto-hidden Taskbar does not pop up when MS4 window is maximised

### ISSUE THREAD

**Issue by LCHMusic** [musescore/MuseScore#10958]
**Bug**
When taskbar in Win10 is set to "automatically hide" and a MS4 window is maximised (but not full screen), moving the mouse cursor to the bottom of the screen does not bring up the taskbar.

**Expected behavior**
When not in full screen the taskbar should appear when the mouse cursor is moved to the taskbar position.

**Screenshots**
![image](https://user-images.githubusercontent.com/102627176/160705867-d4fa3424-f1c4-45f8-bfc9-e8259ec272b7.png)

https://user-images.githubusercontent.com/90187801/160831967-ebbe8690-e646-4ba1-95cb-1dcf063c8e53.mp4

**Platform information**
 - OS: Windows 10

**Additional context**
Doesn't occur in **MU3**

**Comment by DmitryArefiev** [comment]
Works fine in **MU3** but not in **MU4**

Added video to the description.

Thanks for catching this!

**Comment by Fristover** [comment]
I can reproduce this too with Windows 11.
