### ISSUE TITLE
[MU4 Issue] When filename is long, the `*` gets cut off in its tab when the score needs to be saved

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#10953]
**Describe the bug**
If a score needs to be saved, an asterisk (`*`) is added to the end of its tab title. However, the width of the tabs is limited to 200px, which causes the asterisk to be cut off if the filename is too long.

**To Reproduce**
1. Open a score with a long filename and make some changes. You won't see the asterisk, even if it should be there. 
<img width="635" alt="Schermafbeelding 2022-03-29 om 21 08 15" src="https://user-images.githubusercontent.com/48658420/160688177-27dcdc00-3880-43d9-9f26-b89e28c93439.png">

**Expected behavior**
An indication that the file is unsaved should always be visible when relevant, regardless of the length of the filename.

Actually, I think we can do something smarter than just showing an asterisk. This is what VisualStudioCode does for example:
<img width="540" alt="Schermafbeelding 2022-03-29 om 21 06 04" src="https://user-images.githubusercontent.com/48658420/160687477-3d142f72-ff86-49c5-b131-42ec4ac67f6c.png">
(see the white dot that appears at the location of the 'x' button; when hovering it, the 'x' button reappears.)

**Comment by duanjr** [comment]
@DmitryArefiev I have a fix already：

![upload](https://user-images.githubusercontent.com/71218187/161374552-c008fc2d-a112-4c08-885c-f446f293d54b.gif)

Is this expected?  Should we change color of the dot when light mode or this is ok?

**Comment by duanjr** [comment]
when file name is very long:
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/71218187/161374986-e45ad8f3-8d4f-407f-bfe4-a3f0e4409d98.png">

**Comment by cbjeukendrup** [comment]
@duanjr To me, that looks good!

@jessjwilliamson Do you like it too?

**Comment by HemantAntony** [comment]
@cbjeukendrup Perhaps a dumb suggestion, but maybe if the colour was red in this case? I don't know what the colour is called, but the supporting colour. In the default light mode, it would be blue

**Comment by cbjeukendrup** [comment]
Yeah, that's called the accent color. But I'm afraid it would catch _too_ much attention. It should only be a subtle hint at the moment that the user looks at it to close the document, but it should absolutely not draw attention to itself.

**Comment by jessjwilliamson** [comment]
Hmm, I'm not a massive fan of the idea. With the asterisk, we can really make this simple - we can put it at the beginning of the project name instead of at the end. Something I've seen like this is Notepad (Windows 11 version) That way no matter the size of tab it is always there.
![image](https://user-images.githubusercontent.com/71656189/161448374-68e72f53-565b-430f-abb6-638e3c029a0a.png)

**Comment by duanjr** [comment]
> Hmm, I'm not a massive fan of the idea. With the asterisk, we can really make this simple - we can put it at the beginning of the project name instead of at the end. Something I've seen like this is Notepad (Windows 11 version) That way no matter the size of tab it is always there. ![image](https://user-images.githubusercontent.com/71656189/161448374-68e72f53-565b-430f-abb6-638e3c029a0a.png)

I still prefer the previous one (probably because I am used to code editor's behavior), but that's acceptable for me as well.
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/71218187/161464472-96a28d10-e450-4649-b519-7cd0b0aa5e06.png">

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev I have a fix already：
> 
> ![upload](https://user-images.githubusercontent.com/71218187/161374552-c008fc2d-a112-4c08-885c-f446f293d54b.gif)
> 
> Is this expected? Should we change color of the dot when light mode or this is ok?

@duanjr Thank you for the work! But I agree with @jessjwilliamson about adding an asterisk (at the beginning of the name) instead of dot. Because the dot it's a new design element and it takes too much attention (in my opinion).
Or as a variant of fix, we can resize the tab length if the name is too long (with asterisk at the end), but probably it takes more time.

**Comment by duanjr** [comment]
> @duanjr I've tested the build from #11084 and noticed that the asterisk also adds at the beginning to a **NOT** long names (where it doesn't require a 3 dots at the end)
> 
>  bandicam.2022-04-04.18-09-04-550.mp4

Yes, isn't this the expected behavior?
In [jessjwilliamson](https://github.com/jessjwilliamson)'s comment picture, its filename is short too.

**Comment by jessjwilliamson** [comment]
> @duanjr I've tested the build from #11084 and noticed that the asterisk also adds at the beginning to a **NOT** long names (where it doesn't require a 3 dots at the end)
> 
>  bandicam.2022-04-04.18-09-04-550.mp4



> > @duanjr I've tested the build from #11084 and noticed that the asterisk also adds at the beginning to a **NOT** long names (where it doesn't require a 3 dots at the end)
> > bandicam.2022-04-04.18-09-04-550.mp4
> 
> Yes, isn't this the expected behavior? In [jessjwilliamson](https://github.com/jessjwilliamson)'s comment picture, its filename is short too.

I did not comment about the filename being short or not. If we all agree to have it in the beginning then it should be there, not the end depending on file name, all at the beginning :)

**Comment by duanjr** [comment]
> I did not comment about the filename being short or not. If we all agree to have it in the beginning then it should be there, not the end depending on file name, all at the beginning :)

Yes, just wanted to express your opinion that the asterisk's position has nothing to do with whether we have 3 dots or not.
agree to unify their behavior
