### ISSUE TITLE
[MU4 Issue] Tablature Guitar "Edit Staff Type" menu not saving 

### ISSUE THREAD

**Issue by Tegze** [musescore/MuseScore#10964]
**Describe the bug**
The "Fret Marks" and "Note Values" sections of "Edit Staff Type" for guitars doesn't save settings. 

**To Reproduce**
1. Create a new score
2. Add a guitar with tablature (e.g., "Electric Guitar (tablature)")
3. Select a measure and right-click
4. Click "Staff/part properties..."
5. Under "Staff properties" click "Advanced style properties..."
6. Make a change under "Fret Marks" or "Note Values"
7. Click "OK"
8. Click "Apply"
9. Click "OK"
10. Repeat 3-5
11. Observe no settings under "Fret Marks" or "Note Values" was saved

**Expected behavior**
Settings inside of the "Fret Marks" and "Note Values" should be saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/38992967/160734159-3f029d5b-85cd-48b9-96b5-e4087b211ea9.png)

**Platform information**
Windows 10

**Additional context**
All settings inside of the "Edit Staff Type" window will save except items under "Fret Marks" and "Note Values". Setting a template does not keep the set template inside the dropdown after clicking "OK", unsure if this is the intended behavior though. 

Only tested on Electric and Acoustic tablature guitars. Issue doesn't occur for instruments without this menu (e.g., Piano).

**Comment by DmitryArefiev** [comment]
Good catch! Thanks for logging this!

This is important option for tab staves.

**Comment by DmitryArefiev** [comment]
https://user-images.githubusercontent.com/90187801/160883520-09cec58b-0a1e-4fa0-8088-b0177955678f.mp4

**Comment by miiizen** [comment]
I don't know if anyone has already fixed this, but I've just had a quick look and got this working - didn't notice anyone was assigned, apologies!

**Comment by RomanPudashkin** [comment]
> I don't know if anyone has already fixed this, but I've just had a quick look and got this working - didn't notice anyone was assigned, apologies!

I can assign it to you if you have a solution

**Comment by DmitryArefiev** [comment]
Fixed in #11100

**Comment by Tegze** [comment]
@DmitryArefiev Looks good! Working for me on Windows 10 master-67b7102.

**Comment by DmitryArefiev** [comment]
Cool! Thank you!
