### ISSUE TITLE
[MU4 Issue] MeldaProduction VST Plugins only open correctly the first time

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#10969]
**Describe the bug**
The VST plugins from MeldaProduction only open correctly the first time. On the second try, it appears as shown in the screenshot.

**To Reproduce**
1. Install the MeldaPlugins
2. Add for example The Melda Compressor
3. The Plugin opens
4. Close the plugin and try to reopen

**Expected behavior**
The UI of the plugins should be displayed correctly

**Screenshots**
![MeldaPlugins](https://user-images.githubusercontent.com/63284090/160775917-6d4fe899-882e-4cde-bdf3-7f49e50f7872.png)

**Platform information**
 - OS: Windows 11 (private Alpha)

**Additional context**
If the plugin is deactivated once and activated again, it works properly once more. However, this is probably due to the fact that the plug-in settings are reset when deactivating it. This has already been logged here: https://github.com/musescore/MuseScore/issues/10968

**Comment by mattblo** [comment]
> @mattblo Hi! That occurs only with MeldaProduction plugins? What display resolution do you have? (FullHD or higher) and what scaling in display settings (100 or higher)?

I tried it with the MeldaProduction, Alcon Digital VerberateBasic 2, Klanghelm DC1A3, Tokyo Dawn Labs TDR Nove plugins. However, the problem only appeared with the MeldaProduction plugins.

I have a full HD monitor (1920x1080) with 100% scaling.

**Comment by DmitryArefiev** [comment]
Got it. Thanks for detailed info!

**Comment by DmitryArefiev** [comment]
@mattblo Can you try again please? (in latest master)

**Comment by mattblo** [comment]
Works fine on my side. :-)

**Comment by DmitryArefiev** [comment]
> Works fine on my side. :-)

@mattblo Cool. Thanks!
