### ISSUE TITLE
[MU4 Issue] Playback cursor in parts follows position on main score

### ISSUE THREAD

**Issue by dragonwithafez** [musescore/MuseScore#10961]
When trying to play back a part, the blue playback cursor follows where the cursor would be if the main part were displayed, rather than the instrument part.

**Steps to reproduce the behavior:**
1. Create a score
2. Add some notes so you can hear if the cursor is properly aligned to what's playing
3. Create a part, and change its layout so it is different from the main score
4. Play back the main score and then pause playback
5. Switch to the part, and press space to resume playback from the same location
6. Note the incorrect location of the blue cursor

**Expected behavior:** Cursor should properly follow the stave(s) in the part

https://user-images.githubusercontent.com/57819859/160707877-bbfc8acd-63a7-482b-81ac-eb32eff86f11.mp4

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059952268, revision: github-musescore-musescore-abc123456

**Additional context**
Doesn't occur in **MU3**

**Comment by DmitryArefiev** [comment]
Thanks for logging!

**Comment by Tantacrul** [comment]
I'm closing this one in favour of the original I posted which goes into a bit more detail and also includes looping. This is a clear P0.
https://github.com/musescore/MuseScore/issues/9181
