### ISSUE TITLE
[MU4 Issue] VST Instruments get louder when I close and reopen project

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#10974]
Similar to this issue https://github.com/musescore/MuseScore/issues/10916

VSTs get louder when I close the project and reopen (while keeping MS4 open) (here I'm using BBC Orchestra)
Apologies for the very loud distorted one at the very end.. oops

** PLEASE ignore the clicky noise.. Not MS4 related :) that's my audio interface. I'm due to getting a new one soon! 

https://user-images.githubusercontent.com/71656189/160829228-8a7b3da0-e4a1-4329-b317-5d652c9e14e5.mp4

**Comment by vpereverzev** [comment]
Fixed in #12568, confirmed by @Tantacrul in a separate conversation
![image](https://user-images.githubusercontent.com/57620349/181257997-9b229da1-7f34-48ec-b817-53e5059d2ea1.png)
