### ISSUE TITLE
[MU4 Issue] Incorrect playback of individual voices in some cases 

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#10970]
**Describe the bug**
The first Voice in the female staff in some cases is playback wrong in this score.

**To Reproduce**
1. Open this score: https://musescore.com/user/1050536/scores/6746105
2. Play back the score and listen to the 1st female Voice in bar 19+20 (Voice 2 seams to be correct to me)
3. The played duration of the notes is wrong (to short/staccato?)

**Expected behavior**
Correct Playback

**Platform information**
 - OS: Windows 11 (Private Alpha)
 - Mac as well

**Additional information**
Doesn't occur in **MU3**

**Comment by mattblo** [comment]
In the same score, a similar error can also be heard in bar 11 to 12 in the piano in the bass part. The Bb from bar 11 is played into bar 12.

**Comment by DmitryArefiev** [comment]
https://user-images.githubusercontent.com/90187801/162046253-ba048d14-ccd8-4807-8512-0a1d44745431.mp4

**Comment by Tantacrul** [comment]
This issue has already been logged here: https://github.com/musescore/MuseScore/issues/11012

So, I'm going to close this and elevate the other one to a P1.
