### ISSUE TITLE
[MU4 Issue] Tempo. Eights are played straight when Swing tempo mark is placed on the score

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#10972]
**To Reproduce**
1. Open any score
2. Put a Swing tempo mark to the score
3. Play the score

**Expected behavior**
Eights are played with swing effect when Swing tempo mark is placed on the score

**Screenshots**

https://user-images.githubusercontent.com/101250347/160894818-697abfc8-19dc-41db-b882-b56864a17bc5.mov

**Platform information**
 - OS: [macOS, Windows]

**Comment by Motorblade** [comment]
This also occurs with the 16th note swing setting as well.

**Comment by MarcSabatella** [comment]
In the last build I have from earlier today, Swing and Straight are *only* on the Tempo palette, not Text.  Which is fine, really,  They add System text just as the entry on the Text palette did in 3.x.  But indeed, if you add an ordinary staff text and set its swing properties manually (something people do occasionally to get drums, for instance, to play with a different swing ratio than the rest of the band), it would need to work.  It *should* be the exact same code in all cases, so it would probably be difficult to fix one without fixing the others.  But definitely good to test!

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12621 
(except this bug https://github.com/musescore/MuseScore/issues/12687 which came from MU3)
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by Tantacrul** [comment]
Well done @RomanPudashkin and @boryskuzmenko 🥇 

Legends.
