### ISSUE TITLE
[MU4 Issue] Duration value is cut on all percussion instruments 

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#10979]
**Describe the bug**
Also, playback of sounds that have been "cut short" continues into subsequent instrument sounds

"if you select a note, you can hear it get cut off before it finishes playing. 
I suspect the amount of time allows to let a sample play is too short. 
You can hear it clearly when you have headphones on. (Martin)"

**To Reproduce**
1. Create a score with Percussion instrument 
2. Add a note with long sample instrument
3. Pay attention to the cut of its sound
4. Add another note of it

**Expected behavior**
All instrument samples are not cut and don't have previous note tails in the sample start

**Screenshots**
https://www.dropbox.com/s/n69vf2kbueh6cdr/sounds-continue-into-one-another.mov?dl=0 

https://drive.google.com/file/d/1vVV_NUoL3LopbnuZndka7OQWHCg43xhg/view?usp=sharing

**Platform information**
 - OS: [macOS, WIN]

**Comment by vpereverzev** [comment]
Doesn't seem to appear anymore. Tested by me and @Tantacrul
