### ISSUE TITLE
[MU4 Issue] Attachment lines appear and don't hide after doing dragging mouse cursor within selection area

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10976]
**Describe the bug**
Attachment lines (blue dotted lines) appear and don't hide after doing dragging mouse cursor within selection area

**To Reproduce**
1. Select bar with notes and dynamics (or tempo and rehearsal mark)
2. Click, hold the left mouse button and drag it within selection area

https://user-images.githubusercontent.com/90187801/160837949-9a13a546-e007-4ed0-b133-b0bab6fd431f.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by RomanPudashkin** [comment]
I'm working on it
