### ISSUE TITLE
[MU4 Issue] VST plugin added during playback does not seem to be active (no effect)

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#10971]
**Describe the bug**
A VST plugin added during playback does not seem to be active (there is no effect). You have to disable and enable it, but this resets the settings from the plugin as logged here: https://github.com/musescore/MuseScore/issues/10968

**To Reproduce**
1. Playback a score and add a VST during playback 
2. Notice there is no aktiv Effekt
3. Disable the VST and enable it again
4. VST Effekt starts working

https://user-images.githubusercontent.com/90187801/161284770-2aceee82-df59-4ba5-9925-e9b9a25d3efd.mp4

**Expected behavior**
VST effects should work immediately (or adding them during playback should be prevented).

**Platform information**
 - OS: Windows 11 (Private Alpha)

**Comment by DmitryArefiev** [comment]
Seems to be doesn't occur on Mac, but should be re-tested on both platforms after fix.

Attached the video demo.

Thanks for logging this!

**Comment by DmitryArefiev** [comment]
Still occurs in master (Windows10)

**Comment by DmitryArefiev** [comment]
Fixed in #13632
