### ISSUE TITLE
[MU4 Issue] Repeats cause playback drop-outs until file is saved and re-opened

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#10977]
**Describe the bug**
Playback drop-outs occur somewhat erratically when repeat signs are used (incl. volta, da capo, etc.).
This issue tends to correct itself when the file is saved and re-opened. When the file is reopened, playback is correct).

https://user-images.githubusercontent.com/86290556/160848809-85ad76c4-b26e-4a69-a342-1ccfec50bdc4.mov

https://www.dropbox.com/s/lrv5i7gge522uth/volta-1.mov?dl=0
https://www.dropbox.com/s/xf1tqidd3su1i4c/volta-2.mov?dl=0
https://www.dropbox.com/s/e2sixp8z5ntxqqu/volta-3.mov?dl=0
https://www.dropbox.com/s/0j23dalrya7wd7w/volta-test.mscz?dl=0

**Additional issue (discovered 16 May 2022)**
Connected (I suspect) to this issue: the palette item `Repeat last bar` also doesn't seem to affect playback (I.e. the repeated bar does not play):

https://user-images.githubusercontent.com/86290556/168584325-30adc275-ea0b-495d-b304-80df229a6e51.mov

**Expected behavior**
No playback drop-outs should occur

**Platform information**
 - MacOS 12.3 (M1)
 - Windows 11

**Comment by Majora320** [comment]
I'm still experiencing erratic playback dropouts on the latest master build. Sometimes within the repeat block, sometimes outside of it, but the issue only shows up when repeats are involved. Also odd things like notes being played back as staccato the second time around. Doesn't seem consistent at all to reproduce - it'll show up after entering new notes sometimes, but other times it'll just be there after opening the file - but here's a recording of one example, triggered by cutting and pasting a block of notes into the same location:


https://user-images.githubusercontent.com/16787503/177627138-2b732380-41f9-4533-9b45-314a9caab604.mp4

**Comment by Majora320** [comment]
@vpereverzev
