### ISSUE TITLE
[MU4 Issue] "Percussion" instrument has incorrect note assignments

### ISSUE THREAD

**Issue by dragonwithafez** [musescore/MuseScore#10982]
**Describe the bug**
The default drumset configuration for the Percussion instrument has some issues with the pitches being assigned to the wrong MIDI notes. For instance "Closed Hi-Hat" as defined in MU4 plays back as a completely different instrument. Viewing the drumset configuration reveals that Closed Hi-Hat is assigned to pitch number 27, whereas according to the General MIDI standard, it should be 42.

Instruments that I have found that have issues:
- "Ride Cymbal 1" is assigned to 30, should be 51
- "Closed Hi-Hat" is assigned to 27, should be 42

**To Reproduce**
1. Create a score using the Percussion instrument (found under Percussion - Unpitched)
2. Add a Closed Hi-Hat or Ride Cymbal 1 pitch to the staff
3. Note the incorrect playback

**Expected behavior**
Instruments should sound according to how they are named

https://user-images.githubusercontent.com/57819859/160895543-8bfd9fe9-10da-4eb2-8faa-d650a6291942.mp4

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059952268, revision: github-musescore-musescore-abc123456

**Additional context**
Does not occur in MU3 (at least not with the default sondfont, I haven't tried HQ in MU3). GM percussion map from https://musescore.org/sites/musescore.org/files/General%20MIDI%20Standard%20Percussion%20Set%20Key%20Map.pdf

**Comment by boryskuzmenko** [comment]
Looks like that.
My bug is more general. There's not description needed, because our team already knows and fixes the issue.
Currently, a huge spreadsheet with all mapping issues has been created and I only put them to one issue in GitGub.
Sorry, I'm closing your ticket and Thanks for your attentiveness!
