### ISSUE TITLE
[MU4 Issue] Playback. Mapping issues in Percussion instruments

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#10999]
**Expected behavior**
All instruments have corresponding midi and sound mapping

**Screenshots**
See [Spreadsheed](https://docs.google.com/spreadsheets/d/1p544iRhT_kGtkQd0u2qdgEoKb0ZHggvUg8FARhhZNMY/edit#gid=1759187492) with the issues described 

**Platform information**
 - OS: [macOS, Windows]

**Comment by RobFog** [comment]
#10982 is a duplicate of this issue?

**Comment by boryskuzmenko** [comment]
Looks like that. 
My bug is more general. There's not description needed, because our team already knows and fixes the issue. 
Currently, a huge spreadsheet with all mapping issues has been created and I only put them to one issue in GitGub. 
Sorry, I'm closing your ticket and Thanks for your attentiveness!

**Comment by boryskuzmenko** [comment]
Closed as a duplicate of

**Comment by boryskuzmenko** [comment]
FYI. New instrument Flexatone has been added to percussion mapping. All changes are reflected in the spreadsheet (see issue description)

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/11355
