### ISSUE TITLE
[MU4 Issue] Menus cannot be closed when cursor exits (Linux only)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#10993]
**Describe the bug**

If you open a menu from the menu bar, it is difficult to close it. Clicking out or pressing ESC does not work.
**To Reproduce**

1. Click on, say, the "Format" option in the top menu bar.
2. Hover down over a few items in the Format menu. Then hover out of the menu (to the side, say). Click on an empty space; then press ESC.

RESULT: The menu stays open. Neither clicking on an empty space nor pressing ESC will close it.

**Expected behavior**
As in MS 3. If you press ESC or click out of the menu it should close.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7

**Comment by wizofaus** [comment]
Can only reproduce if you click in the space between two menu items, seemingly (but not visibly) changing the focus.  ESC works otherwise.

**Comment by rgreen5** [comment]
Investigated this a bit further.

1. Menus close as expected when you hover the mouse down the primary menu without opening any secondary menus, then click on a blank area or press ESC.
2. If, however, you hover down and unfurl any secondary menus in the pocess, clicking off or pressing ESC will NOT close the menu.

AFAICS, this is the trigger factor.

**Comment by wizofaus** [comment]
Yes, that's also an issue - if a secondary menu unfurls itself then closes again automatically after moving to a different menu item ESC no longer works.

**Comment by rgreen5** [comment]
Same to be a general problem with all menus – e.g. Mixer (F10) > Sound.

**Comment by DmitryArefiev** [comment]
Can reproduce it, but on Linux. Thanks for logging!

**Comment by DmitryArefiev** [comment]
Tested in master build on Linux Mint 20.2 - **no longer occurs**

Closing

Please reopen if you able to reproduce
