### ISSUE TITLE
[MU4 Issue] No popup text on "Customize Toolbar" icon

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#10994]
**Describe the bug**

The "Customize Toolbar" icon / button has no popup text, unlike other items in the top toolbar

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7

**Comment by RobFog** [comment]
By "popup text"; you mean a [tooltip](https://en.wikipedia.org/wiki/Tooltip)?

**Comment by rgreen5** [comment]
Yes.

**Comment by HemantAntony** [comment]
@bkunda and @DmitryArefiev, I have a fix already. This is the tooltip I added:
![image](https://user-images.githubusercontent.com/88136054/160972485-0605f73d-13bd-4b68-8cca-c11c959b9845.png)
Any changes needed to this?

**Comment by bkunda** [comment]
Yes it seems like there is a pattern of adding a secondary line of explanatory text here, which for this button could read:

"Show/hide toolbar buttons"

B.
