### ISSUE TITLE
[MU4 Issue] No possibility to add custom elements to a palette 

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#11006]
**Describe the bug**
No possibility to add custom elements from the score to a palette.

**To Reproduce**

https://user-images.githubusercontent.com/63284090/160989070-f3e95169-239b-4d44-937b-14a2ee190ca0.mp4

**Expected behavior**
As in MS3, it should also be possible in MS4 to drag custom elements from the score into a palette. (Press Ctrl+Shift to drag and drop)

**Platform information**
 - OS: Windows 11 (Private Alpha)

**Comment by cbjeukendrup** [comment]
Related to #8512 (but rather an useful addition than a duplicate).

Thanks for reporting!

**Comment by wizofaus** [comment]
NB when you create a custom palette it shows

![image](https://user-images.githubusercontent.com/5364225/173437384-199476df-c1e8-4ecc-9500-89ea7359f0ef.png)
 
This does sort of work, but ONLY if you drag from existing palette elements, not from elements from the score.
Nor can you copy and paste (v3 doesn't support that either).

**Comment by wizofaus** [comment]
BTW I also noticed that in v3, dragging items from the palette seems the work the same way as CTRL+SHIFT+drag of existing items on the score, in which case it's not always obvious why you can't drop certain items in certain locations - e.g. you can't drag a tempo marking onto a empty measure unless you point the mouse exactly at the whole-measure rest (which is rather hard to do given the mouse pointer is shown as the item you're dragging), and the item is NOT added to the score at the exact location you drop, rather it's added as a logical child of whatever you drop onto, in the default position for such new children.
