### ISSUE TITLE
[MU4 Issue] Note dragging behaviour is wrong in Alpha build (defaults to "edit mode")

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#11004]
**Describe the bug**
The default behaviour when dragging around notes appears to be wrong - it's like it's in "edit/free-drag" mode that doesn't keep the note tied to specific staff positions etc.  This doesn't occur using builds done locally from source  - *unless* you double-click a notehead first, which is sort of by design (but it's serious problem that you can't tell that you've entered this new mode, unlike in v3 which did indicate when you were in "edit mode").  In neither case does the playback correctly reflect what new pitch position you've dragged to.
However on restarting the software it seemed to be correct, for a while, then after switching to another app and back it went into some even stranger mode where the leger line position was wrong.
My suspicion is that something is happening in the background that's causing issues with timing that means just clicking on the notehead twice even after an appreciable gap is being treated as a "double-click" which does trigger edit mode, quite unexpectedly and, as noted, with no user feedback that this has occurred.

**To Reproduce**
1. Create a new score, add a note
2. Drag it up and down
3. Repeat 2. until it starts dragging in "edit mode".

**Expected behavior**
5. Note should only move to a recognised staff line or space (adding/removing leger lines as needed), and playback at the relevant pitch while dragging

**Screenshots**
![image](https://user-images.githubusercontent.com/5364225/160986195-ad2ced75-6bcd-4e5d-a941-14f8daf765d3.png)

**Platform information**
 - Windows 10

**Additional context**

**Comment by Tantacrul** [comment]
I created another issue that relates to this (and would inadvertently solve it): https://github.com/musescore/MuseScore/issues/10642

Here's the PR, which (I think) is just about ready for merging.
https://github.com/musescore/MuseScore/pull/10691

**Comment by Tantacrul** [comment]
Incidentally, the accidental double-clicking on notes, which triggers accidental 'Edit mode' is quite a bigger interaction problem than I think some people realise.

**Comment by wizofaus** [comment]
According to the comments at the top of that PR, double-clicking a note still activates "edit mode", so I'm not sure it solves it?
And I totally agree it's a big problem, not least because it seems that whatever logic is detecting double-click (might be inside Qt somewhere?) is incorrectly detecting two deliberate single-clicks as double-click, i.e. the time threshold is too high.  Usually a double click is only detected if both clicks occur within 500ms (according to MS anyway) with no mouse movement in-between, but for me double-click is often getting detected for time-gaps longer than this.  It's also a big problem because there's no visual feedback that you're in Edit Mode in v4 (v3 did have this).

**Comment by Tantacrul** [comment]
No, we changed it so double click doesn't trigger edit mode. You have to chose it from the context menu. In addition, we then made it so that if you double click on a measure, you are entered into NI mode.

**Comment by wizofaus** [comment]
I'm happy to have this closed once that's been merged and I or someone else can confirm the problem no longer exists then.
But as it stands currently it's still an active issue.

**Comment by wizofaus** [comment]
BTW that other issue certainly doesn't address the issue of no playback feedback while dragging, which is definitely a big regression on v3.  So I'm a bit confused why this has been closed. @Tantacrul

**Comment by Tantacrul** [comment]
You see, this is my point about convoluted issues referencing multiple problems in one, followed by a ton of comments. This stuff gets missed. 

Clearly vertical dragging and the lack of sound should be a separate bug with a single line explanation. Is mark it a P1 easily.

**Comment by wizofaus** [comment]
I logged it as one issue because both were observed while dragging a note and I figured it was likely they were both due to the same underlying bug (though on digging further, I suspect they may not be).
