### ISSUE TITLE
[MU4 Task] Users should be able to copy and paste more than one note at a time (see video)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11009]
**Task description**
See video. We allow users to copy and paste one note but not multiple notes, which is a limitation most other notation apps don't suffer from.

I am not targeting this task at a release of MS4.0 because it is an **additional** change. However, if it is 1. easy to do and 2. If anyone has time, then it would be a very nice improvement to include.

https://user-images.githubusercontent.com/21022311/161015578-27d54fea-eb4d-47a7-978b-9371c9d256f6.mov

**Comment by llui85** [comment]
What would be the expected behaviour if the selected notes aren't adjacent? (e.g you select the 1st, 2nd and 4th notes of a phrase)

**Comment by jeetee** [comment]
My immediate expectation would be that upon pasting you paste those same time-relative notes, and leave whatever was present at place 3 as close to what it was.

If you select things in different staves, then I expect the relative number of staves inbetween to be respected when pasting as well. This might be a bit more convoluted as to whether to account for invisible/hidden staves as well (imho at least hidden ones should be considered here as well). If you'd paste past the bottom end of a system, then whatever would've ended up there is dropped.

**Comment by Tantacrul** [comment]
> If you select things in different staves, then I expect the relative number of staves inbetween to be respected when pasting as well. 

Yes, this :)

**Comment by Tantacrul** [comment]
Bumping to 4.x
