### ISSUE TITLE
[MU4 Issue] Cross staff arpeggios extend (staff spacing changes weirdly)

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#11002]
**Describe the bug**
Cross staff arpeggios extend when they are rerendered.

**To Reproduce**
1. make cross staff arpeggios
2. do something (eg. imput notes)
3. see extended arpeggios

If you do not understand my poor English, please watch the attached video:

https://user-images.githubusercontent.com/102702868/160948366-e0ea4198-a17a-4449-9203-70987cefca55.mp4

**Expected behavior**
Arpeggios should not extend.

**Platform information**
 - OS: Windows 11
 (Occurs on Mac and Linux as well)

**Additional context**
Doesn't occur in **MU3**

**Comment by DmitryArefiev** [comment]
Easy to reproduce. Thanks for logging this!

**Comment by Tantacrul** [comment]
I can still reproduce this in the latest version.

**Comment by Tantacrul** [comment]
@oktophonie - is this something one of your lot could fix?
