### ISSUE TITLE
[MU4 Issue] Grace notes playback issues 

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#11019]
**Describe the bug**
1. Acciaccaturas overlap with the main note
2. Appoggiaturas are too short and detached from the main note

**To Reproduce**
1. Create a score with two measures of eights notes
2. Add Acciaccaturas to one measure and Appoggiaturas to another
3. Play the score and pay attention to the grace notes playback in both cases

**Expected behavior**
1. Acciaccaturas don't overlap with the main note
2. Appoggiaturas are smoothly joined with the main note (like with a slur)

**Screenshots**
https://www.dropbox.com/s/cat2p7w2xn6dtnx/acciaccatura-overlap.mov?dl=0 

**Platform information**
 - OS: [macOS]

**Comment by DmitryArefiev** [comment]
@abariska Tried on Windows10. The initial issue seems to be fixed. Could you recheck please?

**Comment by DmitryArefiev** [comment]
One thing I found with Appoggiaturas - it triggers endless duration notes which looks similar too your #13203 (I will comment there)


https://user-images.githubusercontent.com/90187801/191723035-0c7522ad-9543-48f6-a96c-a44afcd67882.mp4

**Comment by abariska** [comment]
🟢 **Can't reproduce anymore**
