### ISSUE TITLE
[MU4 Issue] Allow user to hide all "under menu" categories except "Score"

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11010]
**Summary of New Feature**

AFAICS, only the "Score" option in the "under menu" is strictly necessary. Would it be possible to allow users the option to hide all categories except "Score"?

**Comment by RobFog** [comment]
You would like "Home", "Publish" and "DevTools" hidden?

**Comment by rgreen5** [comment]
Yes. All the options I really need (e.g. Export) can be accessed from the main menu bar or by shortcuts. The rest is visual clutter. It would also give the interface an appearance more familiar to those used to MS3.

**Comment by bkunda** [comment]
I wasn't around when this particular feature was designed, but I can see that there is a good deal of "designing for the future" going on with these tab options, allowing them to house functionality that doesn't even exist yet. 

And unless I'm mistaken, I do believe "DevTools" will be removed by the time we get to the public release. 

In general, we don't want to rely on shortcuts or hidden menu items for higher-level UI elements like these. These tabs are designed to move you between different _active_ high-level screens within the app's structure, so reducing them down to only one visible tab (even if only making the rest hidden) could cause confusion when it comes to understanding how all these screens interact. For example, I can't see how we could reduce these options further than the "Home" and "Score" tabs; If "Home" is not visible or hidden, for example, it would look like _nothing_ was selected when the user lands on the there, causing them to potentially get lost in the user flow.

But certainly, more granularity in the customisation available could really be worth looking into 🙂

**Comment by Tantacrul** [comment]
Yes, we may offer the ability to hide those options, or consolidate them into one button or something but not for the release of MS4. We're trying to draw a line under the app and get it stable now and UI changes like this need to be considered (and future-proofed) properly.

In future releases, we want to introduce a new 'minimal' mode, for example. I think we'd include an option like the one you're describing with that.
