### ISSUE TITLE
[MU4 Issue] [UX] Number inputs can't be scrolled

### ISSUE THREAD

**Issue by llui85** [musescore/MuseScore#11018]
**Describe the bug**
In MU3, when a numerical input is focused and the pointer hovering over it, scrolling changes the value.
In MU4 this does not occur.

**To Reproduce**
1. Open a score
2. Select a note
3. Open the "Playback" section of the Properties
4. Focus the "Velocity" input
5. Try and scroll, and observe that the value is not changed.

**Expected behavior**
Scrolling over the input while focused will change the value in the direction scrolled.

**Platform information**
 - OS: Linux

**Comment by boryskuzmenko** [comment]
Hi @poypoyan,
Unfortunately, this feature doesn't work on macOS. Please, take a look

**Comment by poypoyan** [comment]
Now using `MouseArea`. Maybe the `WheelHandler` not working is related to [this bug report](https://bugreports.qt.io/browse/QTBUG-87646), but I am not sure.

If this still doesn't work on macOS, this is most likely a Qt bug.

**Comment by poypoyan** [comment]
Update: number field scrolls only when clicked/text input is focused.

**Comment by boryskuzmenko** [comment]
> Update: number field scrolls only when clicked/text input is focused.

Right. It is expected behavior

**Comment by poypoyan** [comment]
This my last attempt for macOS fix. If this even works, it may be very sensitive, wrong flick direction, or both. Please inform. Thank you!

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS12, Win11, Ubuntu20
