### ISSUE TITLE
[MU4 Issue] Grace note stems too elongated; and custom lengths appear to be lost from MS3

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11016]
**Describe the bug**
In the attached score, the stems of beamed grace note clusters are far too long, much longer than in MS3. It also looks as if any alterations made to the length of grace note stems in MS3 is being lost on import into MS4.
**To Reproduce**

1. Open the attached score. 
[test_file1.mscz.zip](https://github.com/musescore/MuseScore/files/8388383/test_file1.mscz.zip)

2. Look at the beamed grace note clusters in 4, 12, 25, 28, 34, 38.
3. Compare to the appearance of the score when opened in MS3.

RESULT: Grace note stems are too elongated. Custom lengths are also being lost.

**Expected behavior**
Similar or improved stem lengths to MS3

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7

**Comment by oktophonie** [comment]
Custom beam positions to be fixed by #10940

**Comment by DmitryArefiev** [comment]
#11817 can be similar

**Comment by oktophonie** [comment]
Fixed by #11788
