### ISSUE TITLE
[MU4 Issue] Display 4 voices on the Note Input toolbar (default workspace)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11017]
**Describe the bug**
IMV, all voice options should be shown on the Note Input Toolbar of the default workspace (not just 1 and 2). In classical guitar music, for example, 3- and 4-voice sections are not uncommon.

**Comment by bkunda** [comment]
We've tried to reduce the number of elements in the toolbar to those that are most likely to be useful in the majority of user cases. It also makes the toolbar less cluttered, which is particularly important for people who work on small screens.

As for people who frequently write with more than 2 voices on a stave, we've tried to make it super easy to reveal these voices. You can do this using the settings "cog" icon in the note input toolbar.

(Btw I totally get this, being a classical guitarist/composer myself 😀)

Hope that explains our design rationale a bit!

**Comment by MarcSabatella** [comment]
I agree there is no need for the additional voice buttons to appear by default for most users, particular new ones.  But, see https://github.com/musescore/MuseScore/issues/11057.  I think this combined with the very many palettes that are similarly hidden by default (and the very many clicks required to restore a more "useful" as opposed to "friendly" environment) is going to be a significant issue for experienced users.  And that basically means, most people updating from MU3.  So I would not argue for the return of the voice 3/4 buttons *by default*, but for the return of the "Advanced" workspace, or some similarly easy way to instantly get these controls back.  Nice thing about doing this via an Advanced workspace is that the controls are all there, no UI or code changes required, just a new workspace file to be included in the package.

Anyhow, I would say this particular issue doesn't need to be reopened, but https://github.com/musescore/MuseScore/issues/11057 should definitely be considered.
