### ISSUE TITLE
[MU4 Issue] Reverb effect is not applied to the piano and some percussion instruments (tambourine)

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11011]
**To Reproduce**
1. Create a score with woodwind, strings, brass, piano and tambourine instruments
2. Create some notes for each instrument
3. Click the notes
4. Pay attention to the sound of piano and tambourine 

**Expected behavior**
Reverb effect is applied to all instruments in score

**Screenshots**

https://user-images.githubusercontent.com/101250347/161028419-dd51c330-20ac-4767-89a2-e62014a2d888.mp4

**Platform information**
 - OS: [macOS, Windows]

**Comment by Tantacrul** [comment]
Also, some have far too much reverb, as noted here (https://github.com/musescore/MuseScore/issues/11976)
 @vpereverzev - when we get around to this task, I can quickly test with you to get to a reasonable result.

**Comment by Tantacrul** [comment]
https://github.com/musescore/MuseScore/issues/11976

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12545
