### ISSUE TITLE
[MU4 Issue] 1st beat of each measure is not accented in Metronome playback

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#11014]
**To Reproduce**
1. Open any score
2. Enable metronome
3. Play the score
4. Pay attention to the first beat of each measure

**Expected behavior**
1st beat of each measure is accented in metronome playback

**Screenshots**

https://user-images.githubusercontent.com/101250347/161030507-0dc17d50-1f40-4325-9438-19fecbd164eb.mov

**Platform information**
 - OS: [macOS, Windows, Linux]

**Comment by zacjansheski** [comment]
@davidwhearn I understand the metronome in MuseSounds has an accent.  Also MS3 metronome has accents on downbeats on downbeats.  Could we make a plan to implement this?
