### ISSUE TITLE
[MU4 Issue] "Disable Vertical justification of staves" setting is being ignored in imported MS3 files

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11023]
**Describe the bug**

It seems that MS4 is ignoring the "Disable vertical justification of staves" setting which was previously applied to MS3 files and applying automatic vertical justification instead.

**To Reproduce**

1. Open the attached score. 
[staves_justification_issue.mscz.zip](https://github.com/musescore/MuseScore/files/8388993/staves_justification_issue.mscz.zip)

2. Go to Format > Style > Page. Notice that the "Enable vertical justification of staves" option is ticked. However, this was not the option specified option in MS3 which was "Disable …". This has clearly spoilt the layout of the score.
3. Open the same score in MS3 and notice the correct layout. Note also the "Disable vertical justification of staves" option is selected in Format > Style > Page.

https://user-images.githubusercontent.com/90187801/161567314-827a464c-396c-4531-aff1-77c03ed91e99.mp4

**Expected behavior**
For imported MS3 files the correct staff justification option should be carried over into MS4.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7
- occurs on Mac and Win as well

**Comment by DmitryArefiev** [comment]
Attached a video demo to the description

**Comment by Jojo-Schmitz** [comment]
In 3.6 "Enable vertical spread" was the default, hard coded in `MuseScore::init()`.
