### ISSUE TITLE
[MU4 Issue] Creating a staff / tablature system is more complicated than in MS3

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11027]
**Describe the bug**

Creating a staff / Tablature combination (e.g. for guitar music), has become more complicated than it was in MS3. The process has been split between two windows (in MS3 it was one), and the layout of controls in the "Instruments" sidebar is confusing.

**Details**

In order to create a staff/tab system the user has to add a guitar staff to the "New Score" wizard, then go the score view and add the Tab staff there (in the Instruments sidebar). This begs the question, "why split the process between two windows."

There is an additional problem:

- Create a guitar treble staff in the New Score Wizard, then close it and go to the main score window. Open the Instruments sidebar and expand the instrument name. Two possibilities are open to you:
     (a) "Add staff" adds a staff to the same instrument which is _not_ linked (i.e. not "mutually updating").
     (b) The other option is to highlight the existing staff then click on the cog icon and choose "Create a linked staff".
    
The creation of **linked** and **non-linked** (same instrument) should be alternatives _in a single dialog_, but they have been erroneously separated.

I would strongly suggest moving the "Add staff" option in the "Instruments" sidebar into the "Cog dialog" for the staff, so that it is above, and similar in appearance to, the "Add linked staff" option.

**Comment by bkunda** [comment]
You make a compelling point in this issue. I too have also noticed some potential user traps in the way this panel is currently set up – particularly when it comes to the process of adding linked staves.

Will leave this issue open and add as a design task for myself. Thanks for pointing this out!

**Comment by Tantacrul** [comment]
This is exactly as complicated as it was before. Putting niche options like this in font of every user who wants to create a score provides a nasty experience for the majority of people.

The feature was impossible to intuit before, as it is now. We've simply moved it and will deal with it in due course.

Incidentally, we'll also be creating tutorials to specifically call this out because users won't get it.

Ultimately, we should just have better templates and a guitar instrument that has a linked stave by default.

**Comment by Tantacrul** [comment]
Definitely agreed we need to do more work on the instruments panel and make the whole thing a little more intuitive.

**Comment by MarcSabatella** [comment]
I agree the old system was a mess and not very discoverable at all.  But, it's not really accurate to say the new system is only "exactly as complicated".  As originally stated, in the past, you could set up what you needed immediately within the score creation dialog using the controls that are visible there.  Now, you have to partially set up your score in that dialog, and then after the fact, go to a separate window to complete the job - and in that window, interact with additional dialogs as well.  This requires the user to deal with several additional UI components above and beyond MU3, which increases both cognitive load and literal number of clicks required pretty significantly.

I'm not thinking of discoverability but of usability for the experienced user who does this often.  And I wouldn't call this a "niche feature"  - my impression is that there are a significant number of guitarists using MuseScore, and we even have a publicly stated goal of improving the experience for them.  This much at least is, unfortunately, a step backwards.

Unfortunately, I don't see a good solution here that doesn't have exactly the problem we want to avoid - overcomplicating the score creation process for the majority of users.  So, I'm not necessarily saying the design change isn't good overall - but it does come at a very real cost that I'd like to see us mitigate.

So, what if we think outside the box a little and consider adding a "Guitar standard + linked tab" entry to the instrument list itself?  This would actually be a big improvement over MU3 in terms of discoverability as well as ease of use, and it costs nothing in terms design or UI changes.  It's just a new entry (or handful of them) in the instruments definition file and perhaps a small amount of code to support adding linked staves directly in this way if it isn't currently possible.
