### ISSUE TITLE
[MU4 Issue] MS4 struggles to open long scores which open easily in MS3

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11035]
**Describe the bug**
The attached score takes a few seconds to load in MS3 – despite being 49 pages long. However it takes minutes in MS4, if it loads at all.

**To Reproduce**

1. Open the attached (zipped) file in MS3. It should load in a few secs. 
[problem_loading.mscz.zip](https://github.com/musescore/MuseScore/files/8391176/problem_loading.mscz.zip)

2. Now try opening the same score in MS4.

RESULT: Loading takes forever if it takes place at all. You may have to force quit.

**Expected behavior**
Loading time should be comparable to MS3.

**Platform information**
OS: Linux Mint 20.1 / 3.7 GB RAM / 2.40 GHz processor.

**Comment by wizofaus** [comment]
I was worried this hadn't been resolved yet, it was reported well over a year ago and I spent quite some time investigating but never made all that much progress unfortunately. I was never able to load the sample Beethoven 9 score for example.

**Comment by RomanPudashkin** [comment]
> I was worried this hadn't been resolved yet, it was reported well over a year ago and I spent quite some time investigating but never made all that much progress unfortunately. I was never able to load the sample Beethoven 9 score for example.

This particular problem is new. For some reasons ChordArticulationsParser::parseSpanners freezes on the attached score. Anyway, I'm working on it now

**Comment by wizofaus** [comment]
Ok, well good luck with it - I vaguely remember that parseSpanners in fact was one of the functions taking a long time back then too.  Here was the original issue BTW: https://github.com/musescore/MuseScore/issues/8143 (though I thought there was one even earlier than that)

**Comment by boryskuzmenko** [comment]
Tested on MacOS. Your score was opened in 44 sec.
