### ISSUE TITLE
[MU4 Issue] Mute and Solo buttons don't work for Metronome 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11031]
**Describe the bug**
Mute and Solo buttons don't work for Metronome in Mixer

https://user-images.githubusercontent.com/90187801/161094359-cd5adfe8-d463-4a2a-8f36-bcd19f7df08d.mp4

**Platform information**
 macOS, Windows, Linux

**Comment by Tantacrul** [comment]
Potential solution to this:

1. **(preferred)** the metronome toggle in the top bar simply unmutes/mutes the mixer channel
2. Remove the solo and mute buttons from metronome
