### ISSUE TITLE
[MU4 Issue] New Score window: suggested improvement

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11038]
**Describe the bug**
When you open the New score window, the "non-active" heading looks greyed out in comparison to the active heading. i.e.:

![new_score_headings](https://user-images.githubusercontent.com/87246583/161104631-17613d62-b271-424f-8f6b-37712f31af15.png)

IMV, this can lead the user to overlook the non-active section or assume that it is non-operational.

**Expected behavior**

The UI should give both halves of the New Score window "equal weight", by some kind of visual cue, e.g. Tabs or suchlike.

**Platform information**
Linux MInt 20.1

**Comment by DmitryArefiev** [comment]
@rgreen5 Thanks for your suggestion for improvement MS, but we need a design approval for these kind of things.
I understand what you mean, but (in my opinion) after a second MS launch the user will not have a doubts that the second section is non-active.

@Tantacrul @jessjwilliamson @bkunda Please review (implementation in #11089)

**Comment by jessjwilliamson** [comment]
Hi @DmitryArefiev @rgreen5 thank you so much for pointing this out. This was actually not intended for the text to be so greyed out! That's too low of an opacity. 

In our original designs the text is 100% opacity. Can someone fix this please? :) I can't remember who made it greyed out. Here's what it should look like: 

![image](https://user-images.githubusercontent.com/71656189/161710029-18cb7b7f-7140-4d5f-9f21-01dd927cd11e.png)
![image](https://user-images.githubusercontent.com/71656189/161710075-eafeeb27-d8a5-406e-9799-2ed82e0cd3f4.png)

**Comment by VanSHOE** [comment]
Sure, ill rework my PR for the same, should I remove or keep the small underline effect?
Also after setting opacity to 100%, there is no distinction when hovering, should I leave that as is?

**Comment by jessjwilliamson** [comment]
Hi @DmitryArefiev  @rgreen5  @VanSHOE 
Sorry I got slightly confused and deleted my original comment.
I have to agree with @DmitryArefiev. This is one of those design methods to make hover, hit, selected states. I've tested it out and 75% is strong enough to not make it look disabled - we use 30% opacity for disabled, which is pretty low. So I appreciate your suggestion @VanSHOE but I'm going to suggest keeping the 75% normal and 100% hover.

**Comment by VanSHOE** [comment]
@jessjwilliamson Sorry for the confusion, the current one is not 70% but rather 75% only 
https://github.com/musescore/MuseScore/blob/master/src/framework/uicomponents/qml/MuseScore/UiComponents/StyledTabButton.qml#L86
![image](https://user-images.githubusercontent.com/75690289/161726083-c5225fae-e69e-47f4-abf6-59e16a15c2ab.png)

Should everything be left as is then?

**Comment by jessjwilliamson** [comment]
> @jessjwilliamson Sorry for the confusion, the current one is not 70% but rather 75% only https://github.com/musescore/MuseScore/blob/master/src/framework/uicomponents/qml/MuseScore/UiComponents/StyledTabButton.qml#L86 ![image](https://user-images.githubusercontent.com/75690289/161726083-c5225fae-e69e-47f4-abf6-59e16a15c2ab.png)
> 
> Should everything be left as is then?

Yes, thank you :) Don't think 75% would look like a disabled button!

**Comment by Tantacrul** [comment]
Closing as a suggestion we can target for 4.X
