### ISSUE TITLE
[MU4 Issue] Continuous view while having more than 1 instrument doesn't work properly.

### ISSUE THREAD

**Issue by FTGCocolandia** [musescore/MuseScore#11036]
**Describe the bug**
Sometimes if you have more than one instrument while using the continuous view option the bars will look extremely long and if you move the whole score dissapears.

**To Reproduce**
1. Create a score with an instrument.
2. Use Continuous View.
3. Add another instrument.

**Expected behavior**
It should have the same behaviour as Musescore 3.

**Screenshots**

https://user-images.githubusercontent.com/91145640/161100281-016105b0-d82f-4f35-9f66-00572e7d2c3e.mp4

**Platform information**
 - OS: Windows 10.

**Additional context**
None.

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/10980
