### ISSUE TITLE
[MU4 Issue] VST. Second of two same pitch notes is not played or played staccato 

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11048]
**Describe the bug**
Repeated notes (of the same pitch) are not played when a VSTi is used 

**To Reproduce**
1. Open/create a score
2. Add a few same notes in the score
3. Play it with Internal Muse sampler
4. Add VST (Spitfire LAB glass piano, Sampletank 4, Kontakt) and play it
5. Pay attention to both results

**Expected behavior**
All notes are played with corresponding length

**Screenshots**

https://user-images.githubusercontent.com/101250347/161257373-45052d47-b841-4449-8a54-d8980f1d0c5d.mov

**Platform information**
 - OS: MacOS, Windows

---

Note: one of the original issues logged here has been fixed: repeated notes of the same pitch sound staccato with the Fluid synth.

**Comment by Tantacrul** [comment]
Well spotted @boryskuzmenko!

**Comment by vpereverzev** [comment]
Fixed in #12568

@boryskuzmenko please confirm the fix on master branch

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
