### ISSUE TITLE
[MU4] Staff instrument alignment not correct when using two lines

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#11044]
Instruments names using two lines are not all "right aligned". The style is set to right align, however the first line is left aligned.
All text should be right aligned.

Staff instrument names as shown in MU3:
![image](https://user-images.githubusercontent.com/13550012/161150825-85e00d1b-933a-44a1-b427-8d1f6a8cf8bf.png)

Staff instrument names as shown in MU4:
![image](https://user-images.githubusercontent.com/13550012/161150994-36101064-8ec5-4b7c-b793-24aee8828213.png)

**Comment by Tantacrul** [comment]
Oh, wait. I misread the issue. Reopening. @oktophonie - thoughts?

**Comment by Tantacrul** [comment]
This feels a bit more serious than a P3 then.
