### ISSUE TITLE
[MU4 Issue] Add back "Advanced" workspace, or something like it

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11057]
MuseScore 3 used to ship with Basic and Advanced workspaces.  I was never a huge fan of this, but I get why defaulting to Basic was good for new users, and it was simple enough for the rest of us to switch to Advanced.

Now, there is only a single workspace, essentially the old Basic.  Adding back all the missing palettes is now a *much* more cumbersome affair, and you end up with a poorly-organized palette for your trouble since the new palettes just go to the top.

I'm sure there was a reason for removing the Advanced workspace, but I would like to revisit this.  I recommend *at least* we keep a complete default palette ordering in mind so that when adding these palettes, they go where they belong, and you can quickly repopulate your palettes with everything you need (eg, everything except Accordion and Bagpipes, for most people).  But, I also suggest we consider a fuller workspace you can switch to easily.  And I think it should include voice 3 & 4 buttons.

**Comment by kuwitt** [comment]
+1
(A little bit OT, reminds me on: https://musescore.org/en/node/283982 ;-).
For me: Also noticed it and would prefer myself to have different options regarding different user capabilities for workspaces.

**Comment by rgreen5** [comment]
Request for 4 voice buttons at #11017.

**Comment by MarcSabatella** [comment]
I'd like to revist this.  I still see the value in having a nice clean look for newcomers and beginners.  But experienced users - not just of MsueScore but of *any* notation program - are going to want an easy way to get access to a fuller set of palettes.  And, probably, the voice 3-4 buttons.  There's extremely little cost in providing a predefined "advanced" workspace you can switch to easily, and it's a big win for the user.  Yes, you can laboriously add all this stuff back one at a time, and then rearrange the palettes to be in some sort of logical order.  But you shouldn't have to.

**Comment by bkunda** [comment]
I'm not entirely sure we need a dedicated "Advanced" workspace. Given this is, as you say @MarcSabatella, for experienced users, it really isn't difficult to set up your workspace exactly the way you want and save it as your own "workspace" (MS4 makes it really easy to do this).

I do realise it's a bit fiddly, but I wouldn't say it's laborious, and it only needs to be done once per saved workspace. If it's experienced users we're talking about here – who each might have particular things they want in particular places – then going through the fiddly routine of setting up the UI just the way you want is part of the process (some people might actually enjoy it!). Moreover, setting up one "advanced" workspace may likely still not cater to every experienced user's needs, so isn't it better to let each user decide for themselves what they really need in their workspace?

**Comment by quinnouyang** [comment]
From a MU3 POV, I'm for Basic and Advanced as I treat Advanced as having basically everything, which makes customizing easier as we'd be offering "two ends of the spectrum" on how many options are visible. I'd rather remove a little than add a lot for my workflow. My stance might be moot for MU4 as adding stuff from the default basic seems really quick.

+1 for default palette order too (though still allow customizations + a reset option).

**Comment by bkunda** [comment]
Thanks @quinnouyang. I definitely take the point about the default palette order. 

Canvassing opinions: when adding a palette (using the `Add palettes` button), would it make more sense for that palette to slot in to a default order, or instead should it just go to the bottom of the current list (rather than the top, which is what happens at the moment)?

**Comment by bkunda** [comment]
> My stance might be moot for MU4 as adding stuff from the default basic seems really quick.

This was, as I understand it, exactly what we wanted 🙂

**Comment by MarcSabatella** [comment]
I think there should be a logical default order when adding the predefined palettes that are missing.  Otherwise it takes that much longer to get a reason environment set up.

As for the advanced work space being for “experienced” users, I don’t mean the top 1% most expert users.  I mean the average user who  even using MuseScore for a month or more and has moved beyond “Mary Had A Little Lamb” and just wants to be able to use grace notes like they could in MuseScore 3.  They’ve never needed to mess with customizing workspaces before - it’s been a simple two-second process to get everything they need by switching to the predefined one.  Why make it so much harder now?  It makes the move to MuseScore 4 seem much more painful that it needs to be for the average user - suddenly they need to learn about customization just to do things that used to be easy.

**Comment by Tantacrul** [comment]
I'm closing this for now, since I think we agree that UX optimisations to palettes and a few other UX optimisations would do further reduce the need for another workspace definition. I'm not crazily against the idea of having more defined workspaces but I'd like to do it in a structured way and not make it another task for 4.0.

In future (for example), I'd love for there to be a 'guitar' workspace. Or a more refined 'marching percussion' workspace.

**Comment by Tantacrul** [comment]
I've moved this to 4.x so we don't forget about this general discussion.

**Comment by RobFog** [comment]
Or a workspace for drummers… 🎉

**Comment by jeetee** [comment]
Just a follow +1 for a more bloated starting point as a mostly support user I currently use a slightly bloated version of the Advanced space in MS3.
I'm not demanding that a new "Advanced" space is to be included in the future, but that a fairly easy way to "add all" to a palette, or multi-select things to add to it allows fast (re-)creation of such a workspace.

And I must say that I do like the idea of some more tailored workspaces for certain instruments/use cases.
Perhaps this can somehow link back to an old idea of the Extensions and a method for easily sharing workspaces.

**Comment by Tantacrul** [comment]
I have no problem adding more workspaces. In fact, I'm hoping to see some sensible ones added (although hopefully not **too** many!) for 4.0.

In particular:

- Marching band
- Solo Piano
- All palettes (formerly 'advanced')
- Rock band
- etc.

**Comment by ShibuyaCyana** [comment]
tbh I'd like to have a sort button to sort them by names. It often happens when I know which palette a symbol is in but still take a long time to find it because the palettes are almost arranged randomly.
and also see this issue:
https://github.com/musescore/MuseScore/issues/12753

**Comment by cbjeukendrup** [comment]
@ShibuyaCyana Please open a new issue for that, if you want your comment to be seen; that's more effective than commenting on a random (or, okay, tangentially related) issue that has been closed for almost 1.5 years.

Also, it doesn't really make sense to post "also see this issue" links to issues that happen to be in the same area of the app but have no relation. It won't speed up things; it will only pollute the issue with "<user> mentioned this issue somewhere blah blah" items.
