### ISSUE TITLE
[MU4 Issue] Button for "system text properties" should be available in properties

### ISSUE THREAD

**Issue by kuwitt** [musescore/MuseScore#11053]
(See also: https://musescore.org/en/node/330829#comment-1121865)

As long as there's no redesign for the system text properties, there should be still a button for it in properties as with MuseScore 3.6.2 available (maybe needs a decision for which system text elements it would make sense).

With MuseScore 3.6.2:

![systemtextproperties](https://user-images.githubusercontent.com/37350572/161333567-8b33cc15-eb0c-4b85-9efb-cc41012062bc.png)

With MuseScore 4.0-Alpha:

![systemtextproperties4](https://user-images.githubusercontent.com/37350572/161333578-8763ef13-1353-49b5-84a2-b8896e0b4076.png)

**Comment by DmitryArefiev** [comment]
https://user-images.githubusercontent.com/90187801/163433675-61ed3e41-03ee-47d4-9195-297403ba428d.mp4

**Comment by HemantAntony** [comment]
@DmitryArefiev I have created a fix for System Text (This is definitely needed). However, Swing (and Straight for that matter) are part of Tempo Text. So its not as straightforward to do so as its part of this classification. I also saw that @Tantacrul said some of the things needed replacing in the System Text Properties Dialog. So, I wanted to know if I should just create a PR for System Text without Swing (and Straight)

**Comment by Tantacrul** [comment]
@HemantAntony - since swing and capo settings both work on system text for MS3, they should do so for MS4

We are going to remove both 'Change Channel' and 'MIDI Action' from stave text properties because we are planning a proper universal system to replace them. 'Change Channel' no longer serves any purpose at present and 'MIDI Action' never did.

**Comment by cbjeukendrup** [comment]
It is. Closing!
