### ISSUE TITLE
Crash on loading this score

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#11065]
Load this score cause crash
[47- Twelve - N°5- Characteristic Studies 317-319.zip](https://github.com/musescore/MuseScore/files/8403123/47-.Twelve.-.N.5-.Characteristic.Studies.317-319.zip)
.

**Comment by HemantAntony** [comment]
This is weird. I can open the score in the latest nightly:
![image](https://user-images.githubusercontent.com/88136054/161431663-7b63d6d4-885a-450f-98dd-c442b3dce31b.png)
But it crashes in the Alpha

**Comment by cbjeukendrup** [comment]
That's good news, this crash has already been fixed (it's that same tie crash we've come across multiple times already). The fix will be included in the next alpha release.
