### ISSUE TITLE
VST - Mentions of VST should make it clear it is VST3 only

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11061]
**Describe the bug**
A few users have reported being confused that their VST2 plugins aren't being recognised. To help make this a little easier to understand, we should make sure to specify 'VST3' wherever they are mentioned.

1. In this Mixer popup, it should say 'VST3' rather than just 'VST'
<img width="334" alt="image" src="https://user-images.githubusercontent.com/21022311/161384615-3b85e485-b8f9-4905-ab19-862839f088b8.png">

2. When adding the ability for users to specify VST locations (and additional locations too), (See #9420) it should specify 'VST3' on the left:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/21022311/161384682-061a018e-069b-4771-a484-2b3527ba6776.png">

**Comment by Eism** [comment]
I am working on it

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS, Windows 11
