### ISSUE TITLE
[MU4] MU4 uses RAM too many (maybe over 1GB)

### ISSUE THREAD

**Issue by HardSmoothy** [musescore/MuseScore#11069]
**Task description**
Musescore 4.0.0 uses ram too many.
Example, when i opened same file(concert band preset, 185 bars 4/4) in 4.0.0 and 3.6.2 ,
3.6.2 was using 143MB ram, but
4.0.0 was using over 900MB ram.

**Comment by HardSmoothy** [comment]
my pc specs:
Windows 10 (21H1) OS
CPU: intel celeron n4000 (1.1GHz) , RAM 4GB

**Comment by fgimian** [comment]
I can confirm this too on Windows 11, Intel i7 7700K, 64 GB RAM

![image](https://user-images.githubusercontent.com/1811813/161424196-9ff70144-b250-42e4-b309-d92b06aa3860.png)

I'm not sure if this is due to extra debugging in the current build?

Cheers
Fotis
