### ISSUE TITLE
[MU4 Issue] Playback bar misaligned and does not readjust to different playbacks

### ISSUE THREAD

**Issue by Motorblade** [musescore/MuseScore#11067]
**Describe the bug**
The blue playback bar highlighting the notes being played can become misaligned, and doesn't attempt to match up with where the playback begins.

**To Reproduce**
1. Open a MuseScore 3.6 file
2. Go to a "part" tab
3. Begin playback

**Expected behavior**
The bar should move to highlight the note being played, and should start wherever playback begins.

**Screenshots**
https://www.youtube.com/watch?v=4kQa_tcGjEM

**Platform information**
 - OS: Windows 10

**Additional context**
Immediately after recording the video above, I clicked back onto the main score and MuseScore crashed.

**Comment by cbjeukendrup** [comment]
Seems the same problem as #10961
