### ISSUE TITLE
[MU4 Issue] Crash opening MusicXML file

### ISSUE THREAD

**Issue by jacobtylerwalls** [musescore/MuseScore#11075]
**Describe the bug**
Hard crash when loading musicxml file: no dialog given about invalid file, just hard crash. (Finale validates the file fine.)

**To Reproduce**
Open attached file (strip ".txt" suffix)

**Platform information**
 - OS: macOS 11.6
 - v4 closed alpha

**Additional context**

[crash.musicxml.txt](https://github.com/musescore/MuseScore/files/8405387/crash.musicxml.txt)

**Comment by jacobtylerwalls** [comment]
Ah. Can't repro in nightly. Dupe of #11065?

**Comment by cbjeukendrup** [comment]
Yes, same cause again, so it's fixed!
