### ISSUE TITLE
[MU4 Issue] Cursor gets stuck as "no" symbol after clicking help icon in VST window

### ISSUE THREAD

**Issue by dragonwithafez** [musescore/MuseScore#11076]
**Describe the bug**
After clicking the question mark icon in the menu bar of a VST window, nothing happens, and the cursor gets stuck as the "no/forbidden" symbol.

**To Reproduce**
1. Open the Mixer panel of a score
2. Add a VST instrument or effect
3. Click on the question mark icon in the top-right of the title bar
4. The cursor is now stuck as the crossed red circle symbol

**Expected behavior**
Cursor should probably remain as a normal arrow since interaction with the score is still allowed.

https://user-images.githubusercontent.com/57819859/161485820-a2047863-5f47-4988-b24c-28832f3c27b5.mp4

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059952268, revision: github-musescore-musescore-abc123456

**Comment by cbjeukendrup** [comment]
Let's remove that `?` button entirely, since it has no purpose :)
