### ISSUE TITLE
[MU4 Issue] Create a new part and opening it crashes with a specific score.

### ISSUE THREAD

**Issue by KaiVinter** [musescore/MuseScore#11079]
**Describe the bug**
Creating a new part crashes MuseScore 4

**To Reproduce**
1. Open the Score:
[(Crash, generate all parts)_L._Boccherini-Guitar_Quintet_No._4_in_D_major copy.mscz.zip](https://github.com/musescore/MuseScore/files/8407665/Crash.generate.all.parts._L._Boccherini-Guitar_Quintet_No._4_in_D_major.copy.mscz.zip)
2. Go to Parts.
3. Choose to create a new part.
4. Open the new part.

**Expected behavior**
New part can be opened.

**Current behavior**
MS4 Crashes

**Platform information**
 - OS: macOS Mojave 10.14.6

**Comment by KaiVinter** [comment]
In case it's important:
This score was created on MS3, imported to MS4 and saved as a MS4 score.

**Comment by Jojo-Schmitz** [comment]
And it doesn't crash in MS3? Just asking because today a case came up with a 3.6.2 score that crashes on part creation, see https://musescore.org/en/node/330975, I wonder whether this might be related?

**Comment by boryskuzmenko** [comment]
Issue is FIXED
Tested on MacOS 12, WIN 11

**Comment by boryskuzmenko** [comment]
Fixed!
Tested on MacOS

**Comment by KaiVinter** [comment]
> And it doesn't crash in MS3? Just asking because today a case came up with a 3.6.2 score that crashes on part creation, see https://musescore.org/en/node/330975, I wonder whether this might be related?

It doesn't crash MS3.
Although, as for the conversation over there, I can relate to having messed up a little with Castanets and hidden staves.
Glad there is a merged PR already

**Comment by Jojo-Schmitz** [comment]
> It doesn't crash MS3. Although, as for the conversation over there, I can relate to having messed up a little with Castanets and hidden staves. Glad there is a merged PR already

Sorry, I don't understand this
