### ISSUE TITLE
[MU4 Issue] Alt-something shortcut focuses menu

### ISSUE THREAD

**Issue by schoettl** [musescore/MuseScore#11071]
**Describe the bug**
(I guess MU4 stands for MuseScore version 4?)
On latest master, pressing an `Alt-something` shortcut executes the command but: releasing `Alt` key focuses the menu. Specifically, this is a problem for the actions `interval1` to `interval9` (bound to `Alt-1` to `Alt-9`).

**To Reproduce**

1. Open MuseScore, add a note to a score
2. Mark the note (or switch to note input mode)
3. Hold `Alt`
4. Press `3`
5. Release `Alt`

**Expected behavior**
An interval should be added and the menu bar should not be focused.

**Screenshots**
The interval is added but the menu is focused when releasing `Alt`

https://user-images.githubusercontent.com/101250347/161778077-ac964dc5-337f-4df4-b20a-72053f8aa00a.mp4

**Platform information**
 - OS: Linux, WIN 11

**Comment by boryskuzmenko** [comment]
Thank you for logging the issue!
Screen recording was added

**Comment by DmitryArefiev** [comment]
FIxed in #11208
