### ISSUE TITLE
[MU4 Issue] MS4 does not remember last folder when opening file (defaults to option in Preferences > Folders)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11082]
**Describe the bug**
MS4 does not remember the last folder used when opening a file. It defaults every time to the scores folder specified in Preferences.

**To Reproduce**
1. Choose open, navigate to another folder, open a file, then close it.
3. Now try opening another file.

RESULT: program has returned to the default folder specified in Preferences

**Expected behavior**

Program should always open in the last folder from which a file was opened.

P.S. Try checking the Save behaviour as well.

https://user-images.githubusercontent.com/101250347/162968968-74c3c323-6cee-4fec-bbf7-2b004ed35408.mov

**Platform information**
MacOS, WINDOWS, Linux 20.1.

**Comment by boryskuzmenko** [comment]
Thank you for logging the issue!
Screen capture of the issue is added.

**Comment by DmitryArefiev** [comment]
>Expected behavior

>Program should always open in the last folder from which a file was opened.

I have some doubts about "always" condition.. Maybe to save location for Open files only during one session.. And restore the default location (when triggering Open command) after MS restart..

FYI @Tantacrul

**Comment by Tantacrul** [comment]
- When saving a new file, it should always suggest the folder that most recently had a file saved in it. This is a general standard used in most other creations apps.

- When opening an existing file and pressing 'Save as', it should suggest the location where **that specific file** was last saved

- We should not reset this option per session. The reason is this: if a user wants to use the 'Scores' location, then they'll always be able to do so. If a user wants to save **anywhere else** on their system, then they will always have to keep navigating to it.

**Comment by Tantacrul** [comment]
Altered the P number because this specific problem causes high amounts of frustration.

**Comment by DmitryArefiev** [comment]
>When saving a new file, it should always suggest the folder that most recently had a file saved in it. This is a general standard used in most other creations apps.

I checked MS Office Word 2007, it follows that rule during the current session. After restart, Word saving a newly created doc to the default location.

I just thinking for what purposes we have a default folder in the Preferences?

**Comment by Tantacrul** [comment]
It's some legacy thing. I think it's fine to have it as an initial default. However, Word is quite poor with this setting. From my years working at Microsoft, I can tell you that they regularly made bad choices when it came to file storage. :D

I tested it on the Adobe suite and a few other similar creation apps.

**Comment by DmitryArefiev** [comment]
OK. Got it!
