### ISSUE TITLE
[MU4 Issue] Unable to color notes in one chord independently

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11096]
**Describe the bug**
Unable to color notes in chord independently, all notes in chord become painted in one color

https://user-images.githubusercontent.com/90187801/161743446-b1c2f09f-e41c-49ab-bc07-d3fa1df3a268.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by micpap25** [comment]
Can confirm this still happens for the latest version of Musescore (MuseScoreNightly-202204110420-master-67b7102-x86_64.7z)
I'd like to attempt to solve this issue, so I'll begin working towards a solution. I'd appreciate any research / knowledge anyone has on this topic.

**Comment by micpap25** [comment]
Another problem I've come across from testing: If a note is colored, and then other notes are added to the chord, those notes will be colored black BUT their internal value in the inspector is the same color as the base note.
![image](https://user-images.githubusercontent.com/34077605/162845655-a58287af-6bd8-489b-8221-4dabe4c0cd08.png)

**Comment by micpap25** [comment]
If the black notes are deleted above and then the delete is undone with Ctrl+Z, the notes are then rendered as the color in their value.

**Comment by micpap25** [comment]
Upon further inspection, this issue is actually caused by the broader issue that "General" selects the entire chord, not just notes, for changing values. This can be seen when "Visible" or "Auto-place" are selected and deselected.
To fix this issue would mean broader changes for the "General" inspection tab.

**Comment by DmitryArefiev** [comment]
Retested on Win10
