### ISSUE TITLE
[MU4 Issue] deleting Key signature from score removes it only from single staff

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#11109]
**Describe the bug**
Deleting Key signature from score removes it only from single staff

**To Reproduce**
1. Create score with multiple staves
2. Add Key Signature
3. Select one and press "del"
4. Onli single stave has removed it

**Expected behavior**
Whole staves have removed it

**Screenshots**
![Keysig_del_bug](https://user-images.githubusercontent.com/1646034/161973859-66c94124-4c9e-4e63-88e0-ff335352c404.gif)

**Platform information**
 - OS: Linux (but probably all)

**Comment by RomanPudashkin** [comment]
@quinnouyang 
>Should we configure the behavior to where selecting one key signature auto-selects all of them in that measure

Yes, that's how it works in MU3. I'll close this issue because it duplicates https://github.com/musescore/MuseScore/issues/9445

But you are free to fix #9445 :)
