### ISSUE TITLE
[MU4 Issue] New instrument added to score miss Key Signature sometimes

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#11106]
**Describe the bug**
After adding new instrument to score, sometimes it miss Key Signature.

**To Reproduce**
1. Create String (orchestra) or Piano score
2. Add Key Signature
3. Add Woodwind instrument (flute, oboe, clarnet, whatewer, ...)
4. Key signature in new instrument is missing

**Expected behavior**
Key signature should be there also for new added instruments

**Screenshots**
![KeySig_bug_not_added](https://user-images.githubusercontent.com/1646034/161949498-a4d219b6-eb52-4ce2-a55f-dd20f3855d4e.gif)

**Platform information**
 - OS: Linux

**Additional context**
It seems Woodwinds are problem.
If Woodwind were first in score, ewerything is fine.
If first instrument is something different, adding woodwinds causes bug.
After adding woodwinds (which miss keysig), also adding other instruments causing bug.

**Comment by mccoydtromb** [comment]
This does not happen if the flute is added below the piano, but with orchestral, wind band, etc. ordering the flute gets added to the top of the list and loses key sig. The same happens if I add a trumpet to a score with piano because it goes to the top of the list.

**Comment by mccoydtromb** [comment]
![image](https://user-images.githubusercontent.com/92689427/162049124-dab42e20-e2d6-4df8-a57a-c181004af5bb.png)
And I got this monstrosity by making a score with piano in G major,
Adding a flute, but moving it below the piano before accepting the dialog,
Then adding a Clarinet with orchestral ordering
Then adding a violin with orchestral ordering

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS, Win11, Linux
