### ISSUE TITLE
[MU4 Issue] Hairpins (crescendo, diminuendo) don't play back withing repeats 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11108]
**Describe the bug**
 Hairpins (cresc and dim lines as well) don't play back withing repeats

https://user-images.githubusercontent.com/90187801/161972915-88dfe472-7221-4bd8-89d8-07093c90ee61.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**

**Comment by boryskuzmenko** [comment]
@Eism It plays correctly the second time but ignores crescendo for the third time.
Check this score out
[Hairpins.mscz.zip](https://github.com/musescore/MuseScore/files/9191583/Hairpins.mscz.zip)

I've edited the issue description

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
