### ISSUE TITLE
[MU4 Task] Add score preview to percussion staff "Advanced style properties"

### ISSUE THREAD

**Issue by miiizen** [musescore/MuseScore#11101]
**Task description**
Both standard staves and TAB staves have a score preview in the advanced style properties while percussion staves do not.  It would be nice to include this.
**Standard stave options**
![Standard stave options](https://user-images.githubusercontent.com/26510874/161835897-6ff43811-3de5-454a-bdc9-b88efc7b4c92.png)
**Percussion stave options (currently)**
![Percussion stave options](https://user-images.githubusercontent.com/26510874/161836472-92249dcc-2847-4dfb-9336-0e5eb0a6239e.png)

**Comment by Tantacrul** [comment]
Since this is already an issue with version 3.6, we won't be including it in 4.0, since we are in bug fixing now.

Moreover, we want to reimagine the entire **stave/part properties** dialog in general (because it is a bit of a mess). We'll get to this in a later release.
