### ISSUE TITLE
[MU4 Issue] Continuous view hides all notation when the left side is obscured.

### ISSUE THREAD

**Issue by Tankakuka** [musescore/MuseScore#11119]
I am currently on MU4 Alpha 1 on Windows 10.
![musescorecontinuous](https://user-images.githubusercontent.com/71955529/162446172-78e0bd5e-c549-4a74-b229-cde28ba70426.gif)

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/10980
