### ISSUE TITLE
[MU4 Issue] Weird Key Signatures when confirm instrument's transposition change by Apply - OK

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#11129]
**Describe the bug**
When instrument transposition changed, weird key signature appears, when Apply - OK are pressed.

(May be related with #11106?) 

**To Reproduce**
1. Staff/part properties
2. Cahnge transposition
3. Click "Apply"
4. Click "OK"

**Expected behavior**
Correct Key Signature should appear.

**Screenshots**
![Transposition-keysig-bug](https://user-images.githubusercontent.com/1646034/162592602-6c7a1daa-182d-4505-8873-00b27b45a2b8.gif)

**Platform information**
 - OS: [Linux]

**Comment by Tantacrul** [comment]
I've been playing with this a bit in the latest nightly and I'm not experiencing weird key signatures any more. For example, I chose a perfect 5th and saw your standard double sharp key signature. I also tried changing the overall key signature too and they still looked OK. Perhaps this has been fixed? @sammik can you check again?

If it is still a problem, I will reopen the issue and assign a higher priority.
