### ISSUE TITLE
When trying to horizontal scroll the Mixer with a trackpad, the volume/pan controls keep taking over in unexpected ways

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11128]
**Describe the bug**
When trying to H-scroll using the trackpad (which usually requires two fingers), various controls take over the interaction in very unexpected ways. Namely, the volume and pan controls.

**Tested on a Macbook Pro** - affects trackpad
**Tested on a Windows** - affects mouse wheel

**To Reproduce**
See video. The position of the cursor is key to the problem. When it is hovering over a pan/volume control, that is when the issue occurs.

https://user-images.githubusercontent.com/21022311/162586863-178dc4a0-527c-43c9-9a53-1fbeb1f3f23c.mov

**Expected behavior**
Pan, volume, and aux send knobs should not be affected by horizontal or vertical scrolling using the trackpad. If a user begins scrolling, the control should not take it over. I would imagine this **might** also be a problem when using the mouse wheel. Will need to test this later. If anyone else can comment to confirm, that would be welcome.

**Solution**
Disable the use of scroll to adjust the volume slider and pan/aux send knobs on channel strips in the mixer.

**Comment by poypoyan** [comment]
I'll try to work on this.

**Comment by Tantacrul** [comment]
Edited the description to include Mouse wheel on Windows Desktop as well as trackpad for Macbook

**Comment by poypoyan** [comment]
I'm sorry I'll not focus on this anymore.

Hopefully this is helpful: https://doc.qt.io/qt-5/qml-qtquick-controls2-control.html esp. `wheelEnabled` for this task since `KnobControl.qml` and `VolumeSlider.qml` are controls.

**Comment by cbjeukendrup** [comment]
See also https://github.com/musescore/MuseScore/issues/11605#issuecomment-1125397365 (me trying to explain how scroll events work and why we can't (easily) fix this bug while using Qt/QML)

**Comment by avvvvve** [comment]
@cbjeukendrup I may not be understanding your comment correctly, but is it possible to completely disable the behavior of scrolling to edit the values of knobs and sliders on individual channel strips? That would solve this issue. Yes, we would lose the scrolling feature but I assume most people do not interact with the controls that way.

**Comment by cbjeukendrup** [comment]
@avvvvve Yes, that's possible. Trivial, even. (And it would indeed solve the problem.)
If we decide to go with that solution (at least temporarily) that would make this a good first issue.

**Comment by avvvvve** [comment]
@cbjeukendrup Awesome, just updated the description to include aux sends since those were added since this issue was filed. Thanks!

**Comment by benku2** [comment]
If this issue is still persistent, I would like to try fixing it with the suggested temporary solution.

**Comment by Tantacrul** [comment]
I believe this gets fixed with a move to Qt 6, right @cbjeukendrup ?

**Comment by cbjeukendrup** [comment]
No, that doesn't seem to be the case. Qt 6 did fix some other types of scrolling issues, but not this one.

**Comment by samdcchurch** [comment]
Perhaps I am missing something (I am new), but is this not as simple as making the wheelEnabled bool false in KnobControl.qml and VolumeSlider.qml, as suggested above?

**Comment by Tantacrul** [comment]
I personally do not see any reason for the mouse wheel or trackpad to affect volume sliders or pan controls, or any other rotary knobs.

In Logic Pro for example, they specifically disabled that capability in their mixer so people could scroll without issue.

I always thought the problem was more awkward. Are we really saying that we could have solved this years ago by just disabling trackpad / mousewheel on these UI items in the Mixer?

**Comment by avvvvve** [comment]
Yup, we already decided to disable scrolling when we last were chatting here but as Casper said we wanted to keep it available as a community issue. So please go ahead and open the PR @samdcchurch!

**Comment by Tantacrul** [comment]
Can I just point out that this is a really bad bug, so if it doesn't get done in the next few days - and it's a simple fix - let's just do it ourselves. Been a thorn in our side for years.

**Comment by Eism** [comment]
As an idea:
ListView has a property responsible for scrolling - moving. When the user scrolls, the value of moving changes. 
You can do something like this:

```
    ListView {
        id: view
        delegate: Slider {
            wheelEnabled: !view.moving
        }
    }
```
This works fine on the Qt test project, but for some reason it doesn't work in MuseScore.

https://github.com/user-attachments/assets/bbddccdd-e6fe-4abb-8c01-3e9f40a200e4

**Comment by avvvvve** [comment]
To me (and I think @Tantacrul agrees), we should not bother looking for a fix that allows scrolling to both scroll the mixer horizontally and adjust sliders and knobs. We do not want sliders and knobs to react to scrolling _at all_.

I don't see this as a temporary fix—it's just the desired behavior. It's too easy to accidentally mess up your mix with scrolling, even if the horizontal scrolling played nicely with scrolling on these elements.

**Comment by Tantacrul** [comment]
Agree with Ben. There's almost no value in having the trackpad or scrollwheel work on any of those controls. Just disable it and call it an easy day!

**Comment by Albergarri788** [comment]
At least, the function could be left but used in combination with another key, such as alt or control + mouse wheel.

**Comment by avvvvve** [comment]
@Albergarri788 Feel free to open a feature request to allow scrolling on mixer faders/knobs to adjust them while holding a modifier key so we can keep track of the idea.
