### ISSUE TITLE
[MU4 Issue] Alpha crashes whenever I open a certain score

### ISSUE THREAD

**Issue by Dergos** [musescore/MuseScore#11139]
**Describe the bug**
Whenever I try load this score in to the alpha build, it immediately crashes.

**To Reproduce**
1. Open score.
2. Crash.

**Expected behavior**
Score should open as it does in MU3

**Platform information**
 - OS: macOS

**Additional context**
Attached is the error message it gave and the score itself
[Score and Error.zip](https://github.com/musescore/MuseScore/files/8461107/Score.and.Error.zip)

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/10939, https://github.com/musescore/MuseScore/pull/10978
