### ISSUE TITLE
[MU4 Issue] Viewing problem with the "Continuous view" option

### ISSUE THREAD

**Issue by salomo-michelfeit** [musescore/MuseScore#11136]
**Describe the bug**
The "Continuous view" seems to not work. It only shows the first bar and the note after that.
And when scrolling to the right, the page just gets white.

**To Reproduce**
1. Create a Score with a few instruments
2. Use the "Continuous view"-view. 
3. Only the first bar and first note of the second bar are shown and the lines (see first screenshot)
4. Scroll to the right, until the page border is out of the frame
5. The whole page turns white (see second screenshot)

**Expected behavior**
To see the whole score in a continuous view and when scrolling to the right, continuo seeing it.

**Screenshots**
<img width="1680" alt="Bildschirmfoto 2022-04-10 um 18 15 45" src="https://user-images.githubusercontent.com/103373506/162629055-1220b9a0-dca1-4648-a2ee-13e8cabb933c.png">
<img width="1680" alt="Bildschirmfoto 2022-04-10 um 18 15 55" src="https://user-images.githubusercontent.com/103373506/162629043-acb59c10-9dd1-4942-8ddb-57a956252f3f.png">
<img width="1680" alt="Bildschirmfoto 2022-04-10 um 18 32 41" src="https://user-images.githubusercontent.com/103373506/162629825-98923aa4-2224-455c-aa1a-39b8a3f21295.png">

**Platform information**
 - OS: macOS

**Additional context**
<b>1. </b>Might have something to do with changes for the issue mentioned <a href="https://github.com/musescore/MuseScore/issues/8924">here</a>
<b>2. </b>Also when viewing a part of a single instrument of this score, it works as should. (see third screenshot)

**Comment by RomanPudashkin** [comment]
Fixed in #10980
