### ISSUE TITLE
[MU4 Issue] Note input still "enabled" in publish

### ISSUE THREAD

**Issue by poypoyan** [musescore/MuseScore#11132]
**Describe the bug**
When in note input mode, you can still input notes in publish (but not accidentals).

**To Reproduce**
1. Click on score tab.
2. Enable note input mode (i.e. by pressing 'n' so that the pencil icon is selected).
3. Click on publish tab. 
4. Add notes (but you can't raise it semitone up or down).

**Expected behavior**
I don't think we should be able to add notes in publish.

**Platform information**
 - Windows

**Additional Context:**
Not sure if this is bug or feature. What should be editable in publish tab? Thanks!

**Comment by Tantacrul** [comment]
This issue has been fixed with @RomanPudashkin's changes. I'm now closing this issue, since it no longer occurs.
