### ISSUE TITLE
[MU4 Issue] Playback. Mapping issues in Strings Plucked instruments

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11148]
**Expected behavior**
All instruments have corresponding midi and sound mapping

**Screenshots**
See [Spreadsheed](https://docs.google.com/spreadsheets/d/1p544iRhT_kGtkQd0u2qdgEoKb0ZHggvUg8FARhhZNMY/edit?pli=1#gid=2028889784) with the issues described 

**Platform information**
 - OS: [macOS, Windows]

**Comment by Tantacrul** [comment]
I have logged the one issue that remains in here separately. Closing this one down.
