### ISSUE TITLE
[MU4 Issue] Playback. Mapping issues in Strings Bowed instruments

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11147]
**Expected behavior**
All instruments have corresponding midi and sound mapping

**Screenshots**
See [Spreadsheed](https://docs.google.com/spreadsheets/d/1p544iRhT_kGtkQd0u2qdgEoKb0ZHggvUg8FARhhZNMY/edit?pli=1#gid=0) with the issues described 

**Platform information**
 - OS: [macOS, Windows]

**Comment by Tantacrul** [comment]
I have logged these issues separately today:

- https://github.com/musescore/MuseScore/issues/11932
- https://github.com/musescore/MuseScore/issues/11933

Closing this bug down.
