### ISSUE TITLE
[MU4 Issue] Playback. Mapping issues in Brass instruments

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11149]
**Expected behavior**
All instruments have corresponding midi and sound mapping

**Screenshots**
See [Spreadsheed](https://docs.google.com/spreadsheets/d/1p544iRhT_kGtkQd0u2qdgEoKb0ZHggvUg8FARhhZNMY/edit?pli=1#gid=531568298) with the issues described 

**Platform information**
 - OS: [macOS, Windows]

**Comment by Tantacrul** [comment]
I have logged these as a separate issue. Can close this now.
