### ISSUE TITLE
[MU4 Issue] Toolbars checkmarks incorrectly displayed upon opening

### ISSUE THREAD

**Issue by Arkantyne** [musescore/MuseScore#11153]
**Describe the bug**
When viewing the Toolbars subsection of the View tab, there are three checkable buttons: Playback Controls, Note Input and Status bar. While all three Toolbars are active (by default upon installation), only Note Input is checked in the tab. Upon clicking either of the bugged buttons, the button will stay as is but the respective toolbar _will_ disappear. From there forth they work as normal, but not before they are clicked.

**To Reproduce**
1. Go to the View tab
2. Open the Toolbars subsection

**Expected behavior**
All three buttons should have checkmarks, not just Note Input.

**Screenshots**
![image](https://user-images.githubusercontent.com/103443116/162792124-9c9663e8-b499-4dbe-b228-723b33e37d16.png)

**Platform information**
 I'm running 64-bit Windows 10, latest version.

**Additional context**
I have just installed the Alpha build of Musescore 4 and immediately encountered this rather minor bug while exploring the interface.

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/10936
