### ISSUE TITLE
[MU4 Issue] Playback. Mapping issues in Winds instruments

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11150]
**Expected behavior**
All instruments have corresponding midi and sound mapping

**Screenshots**
See [Spreadsheed](https://docs.google.com/spreadsheets/d/1p544iRhT_kGtkQd0u2qdgEoKb0ZHggvUg8FARhhZNMY/edit?pli=1#gid=1035353106) with the issues described 

**Platform information**
 - OS: [macOS, Windows]

**Comment by Tantacrul** [comment]
I have logged the remaining mapping issues. Closing this now.
