### ISSUE TITLE
[MU4 Issue] Prompts can be confusing with accent color

### ISSUE THREAD

**Issue by micpap25** [musescore/MuseScore#11155]
**Describe the bug**
Prompts are made visually confusing due to options being highlighted with the accent color. End users may make mistakes by accident due to this. One immediate example is when a save prompt appears while a document is being closed in the default Dark Theme. Due to the red accent, the "Save" option is a bright red while the "Don't Save" option is black. A user may associate red with a negative action and click the wrong choice.

**To Reproduce**
1. Go to **Edit > Preferences > Appearance**.
2. Set "Accent Color" to a red color.
3. Edit a document
4. Attempt to close that document.

**Expected behavior**
Prompts should always follow a specific accent color scheme, regardless of the user's accent color in preferences. For example, "Save" should always be blue or "Don't Save" should always be red.

**Screenshots**
![image](https://user-images.githubusercontent.com/34077605/162793642-e26085e0-38d1-4e84-bb36-163dd7054a69.png)

**Platform information**
 - OS: Windows 11
 - Version: MuseScoreNightly-202204110420-master-67b7102-x86_64

**Comment by Tantacrul** [comment]
By design. If we find users are confused (in testing) we'll change it.
