### ISSUE TITLE
[MU4 Issue] The part duplicates several time after showing other instrument in that part and reopening the score

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11154]
**To Reproduce**
1. Create a score with Piano and Violin
2. Save the score
3. Open Violin part
4. Show and then hide Piano (notice now the Violin part has an instrument name)
5. Open Part window - **now it has two parts of Violin**
6. Open all two part of Violin
7. Close and reopen the score
8. Open Part window - **now it has three parts of Violin**

https://user-images.githubusercontent.com/90187801/162792454-da2f1e50-a3f4-4363-bec5-02a54e0e5240.mp4

**Expected behaviour**
No additional parts should be created/exposed in the "Parts" dialog when instruments are shown/hidden in the **Instruments** panel.

**Platform information**
 macOS, Windows, Linux

**Additional context**
See also #11420

**Comment by bkunda** [comment]
This is definitely unexpected behaviour. Expected behaviour is that no additional parts are created/exposed in the "Parts" dialog when instruments are shown/hidden in the **Instruments** panel.

**Comment by DmitryArefiev** [comment]
Fixed in #11858
