### ISSUE TITLE
[MU4 Issue] Playback. Mapping issues in Percussions (Pitched) instruments

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11151]
**Expected behavior**
All instruments have corresponding midi and sound mapping

**Screenshots**
See [Spreadsheed](https://docs.google.com/spreadsheets/d/1p544iRhT_kGtkQd0u2qdgEoKb0ZHggvUg8FARhhZNMY/edit?pli=1#gid=583645955) with the issues described 

**Platform information**
 - OS: [macOS, Windows]

**Comment by Tantacrul** [comment]
I have tested (and passed) a few of these. @bkunda - can you confirm that the rest of the mappings (marked as 'not yet') are now mapped? I checked a few and found them to be working now. However, there are a few I don't 100% understand as described.

For now, I just want to focus on mapping. We can approach the ideal sounds for articulations a little later.

**Comment by Tantacrul** [comment]
@bkunda logged these issues v.recently with more specifics:
https://github.com/musescore/MuseScore/issues/11974
