### ISSUE TITLE
Playback: Fermata 'Time stretch' settings in properties do not work

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11165]
**Describe the bug**
The fermata markings should behave as with MuseScore 3. Time stretch should allow the user to lengthen the duration that the fermata is applied to.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/21022311/162967654-afef9853-7f9c-4b58-8394-8a9ec9f4f1b4.png">

**Comment by DmitryArefiev** [comment]
Hi @Tantacrul , it seems to be working on my side:

Uploading bandicam 2022-04-13 21-17-24-639.mp4…

**Comment by Tantacrul** [comment]
Hmmm. OK, this is strange. I was sure it wasn't working when I tested it... and now I'm trying it again and it IS working.

I'm closing for now, and if I encounter it again, I'll reopen. Thanks @DmitryArefiev
