### ISSUE TITLE
[MU4 Task - Mixer] Panning Mode Options

### ISSUE THREAD

**Issue by SketalDaz** [musescore/MuseScore#11161]
Hello,

Feature Request:
There should be an option for each track to change the panning function between two different modes: Balancing Mode & Stereo Mode.

The following video gives detail description of how these modes function:
https://www.youtube.com/watch?v=cYBVwulZyTA

Thx!

**Comment by Tantacrul** [comment]
Nice idea. Going to bump to 4.X

Closing until we release 4.0
