### ISSUE TITLE
[MU4 Issue] Undo & Redo shortcuts displayed multiple times in Edit menu

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#11166]
**Describe the bug**
In the Edit menu, the Ctrl+Z shortcut for Undo, and the Ctrl+Y shortcut for Redo, are repeated multiple times.

![image](https://user-images.githubusercontent.com/11011881/162972524-9a67893d-acad-4cd8-89bb-c11b357adb68.png)

Ideally we would see:

- Undo: Ctrl+Z; Alt+Backspace
- Redo: Ctrl+Y; Ctrl+Shift+Z; Alt+Shift+Backspace

I swapped the order of Ctrl+Shift+Z and Alt+Shift+Backspace for Redo compared to the screenshot. This is so they align under the corresponding shortcuts for Undo.

**Platform information**
 - OS: Windows 10

**Comment by poypoyan** [comment]
Additionaly, in File Menu, the Close shortcut displayed Ctrl+F4 twice. Observed in Windows 10.

**Comment by quinnouyang** [comment]
I do not observe this on Mac. Looking for a fix atm...

**Comment by shoogle** [comment]
@quinnouyang, are you developing the fix on macOS? If so it would probably be better to develop on a system that is able to reproduce the problem.

**Comment by quinnouyang** [comment]
@shoogle Yeah, defintely recommend someone on Windows to take point. I just wanted to take a quik look to see if the fix was obvious (can't seem to find the shortcut display logic, though I'm new here)

**Comment by DmitryArefiev** [comment]
Fixed in #11679
