### ISSUE TITLE
[MU4 Issue] 'All instruments' set is displayed in the Replace instrument dialog instead of 'Common'

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11167]
**To Reproduce**
1. Open any score in MU4
2. Open Instruments tab in Inspector
3. Select on of instruments and click Replace button
4. On the opened dialog pay attention to the set of available instruments 

**Expected behavior**
'Common' set is displayed in the Replace instrument dialog

**Screenshots**

https://user-images.githubusercontent.com/101250347/162991880-377ca00a-cb3f-4dd0-9a29-91f6cfe1dd12.mp4

**Platform information**
 - OS: macOS, Windows, Linux

**Additional context**
Use main Instruments dialog for reference (by clicking 'I' on keyboard)

**Comment by VanSHOE** [comment]
I am unable to reproduce this

https://user-images.githubusercontent.com/75690289/163028646-3fff73e6-8bc9-4f78-be5a-b7e42eb93a9b.mp4

Posting the video here to show the steps I took
Please let me know if I did something wrong in 'To Reproduce'

**Comment by quinnouyang** [comment]
Is the issue that the dialogue for "Replace Instrument" shows "All Instruments" instead of "Common", i.e. default should be "Common"?

**Comment by boryskuzmenko** [comment]
> Is the issue that the dialogue for "Replace Instrument" shows "All Instruments" instead of "Common", i.e. default should be "Common"?

yes, that's right.
cc: @VanSHOE

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
