### ISSUE TITLE
Continuous View not showing barlines or stavlines, quite laggy

### ISSUE THREAD

**Issue by jegmanu** [musescore/MuseScore#11178]
**Expected behavior**
A continuous view of the score, similar to MS 3.6

**Platform information**
 - OS: Windows

**Additional context**
Three instruments, standard fonts, layout etc.

**Comment by RomanPudashkin** [comment]
The description of the issue is very vague. Do you mean this problem?
https://github.com/musescore/MuseScore/issues/10973

It has already been fixed in the main branch

**Comment by jegmanu** [comment]
Ah, yes, exactly. Thanks!
