### ISSUE TITLE
Flip Directions 

### ISSUE THREAD

**Issue by jegmanu** [musescore/MuseScore#11171]
**Issue**
When clicking the "Flip Direction" button, it takes several clicks to do so, and it lags a bit. Same for when I want to flip the directions back. 

**Expected behavior**
After one click, the directions should be flipped. 

**Platform information**
 - OS: Windows

**Comment by MarcSabatella** [comment]
For me, most elements flip fine.  But, ties do not.  It seems the property gets changed but there is no relayout of the score, so you don't *see* the effect until the next edit operation.

So:

1) enter two tied notes
2) select the tie
3) press "X" or use the flip button

Result: nothing appears to happen.  But then, make another edit, and suddenly the tie flips

**Comment by Tantacrul** [comment]
I think this issue has long been solved. Closing for now.
