### ISSUE TITLE
[MU4 Issue] Huge cursor is rendered when editing dynamics on a score

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11173]
**To Reproduce**
1. Create a score
2. Add fff dynamic mark to the score
3. Double-click the mark to edit
4. Pay attention to the cursor size

**Expected behavior**
Cursor size corresponds to the dynamics font size when editing dynamics on a score

**Screenshots**

https://user-images.githubusercontent.com/101250347/163053457-f135e9b6-d7eb-4be7-99db-dcb3cd12a3e6.mov

**Platform information**
 - OS: macOS, Windows, Linux

**Comment by tzarjakob** [comment]
Can I work on this one?

**Comment by Tantacrul** [comment]
@tzarjakob - have you made any progress?

**Comment by tzarjakob** [comment]
No, you can unassign me
