### ISSUE TITLE
[MU4 Issue] Several properties from "Staff property" menu are not working

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#11180]
**Describe the bug**
See attached video. Several properties are not registering the change. Among those, the "Small staff" toggle is probably the most important.

**Additional context**
Testing on latest master on Linux.

https://user-images.githubusercontent.com/93707756/163197509-4bd58450-4b4f-48f1-a9ca-4d3e2893c21b.mp4

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/11205

Also see: https://github.com/musescore/MuseScore/issues/11216
