### ISSUE TITLE
[MU4 Issue] Some items get duplicated or don't show between parts and score (when creating a new part/showing instruments)

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#11186]
**Describe the bug**
Some items become duplicated between parts and score when creating a new part and adding instruments (see video attached). Especially clefs, time signatures and key signatures.

**Additional context**
Current master branch. Linux platform.
(also occurs on Mac/Win)

(The screen recording doesn't show the pop up menus, for unknown reasons)

https://user-images.githubusercontent.com/93707756/163221072-365f3935-daa3-49c5-80b5-9918f226fc5a.mp4

[video.zip](https://github.com/musescore/MuseScore/files/8487953/video.zip)
-----------------------------------------
**Part 1**:
- When creating a new part, **time signatures and key signatures are duplicated in the new part** (after showing other instruments). But all looks OK after reopening the score

https://user-images.githubusercontent.com/90187801/163380031-dcf70deb-f292-438f-b2e5-dd0d55e86a75.mp4

**Part 2**:
- When showing another instruments in the part, **fermatas are duplicated in the score** and **don't show in the part** (in unhidden instruments)

https://user-images.githubusercontent.com/90187801/163379012-4018fd19-f7c8-4ce2-9daa-2a989ee8cb97.mp4

**Part 3**:
- When creating a new part, **Tempo (and system text) don't show in the new part** (see video from Part 1)

**Comment by DmitryArefiev** [comment]
@mike-spa I've reattached your video in zip package for easy download.

**Comment by DmitryArefiev** [comment]
Found the same things with fermatas and Tempo (system) text. Divided into 3 parts and added to the description.

**Comment by DmitryArefiev** [comment]
can be related to #11154

**Comment by DmitryArefiev** [comment]
Fixed in #11260
