### ISSUE TITLE
[MU4 Issue] Improvement. Score view is not move back to the current playback cursor during playback

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11181]
**Describe the bug**
We have playback option 'Pan score automatically'. When this option is disabled I can move/scroll a score sheet without any limits, when this option is enabled (default) I can't really move around the score (the same is in Sibelius). My point is that it looks weird and is not really good from UX side. So, I propose to look to approach which used in UG playback: during playback you can scroll around the tab until you do scrolling, but after around 1 sec after no action with the tab user is moved back to the current playback position. 
Pros from this improvement:
- user can move around a score and select any note/measure 
- in any case (I propose after 2 sec) cursor will returned back to the current playback position
- no visual artifacts like this (when 'Pan score automatically' is enabled)
- consistency between Muse products

**Screenshots**
**MU4 ('Pan score automatically' in both states)**

https://user-images.githubusercontent.com/101250347/163205894-5618393d-888e-426c-af0d-33fa99a6370e.mov

**UG**

https://user-images.githubusercontent.com/101250347/163206688-4a8b1111-708b-4ce8-b463-ace6e3344463.mov

**Platform information**
 - OS: macOS, Windows, Linux

**Comment by Tantacrul** [comment]
Nice suggestion!

**Comment by boryskuzmenko** [comment]
🟢 FIXED
Tested by @Tantacrul
