### ISSUE TITLE
[MU4 Issue] Playback starting point cannot be set by selecting a whole bar

### ISSUE THREAD

**Issue by georggleixner** [musescore/MuseScore#11196]
**Describe the bug**
When selecting a whole bar and then clicking play, the starting point of the playback is not the selected bar. When selecting notes it works correctly.

**Expected behavior**
Playback should start from first note in the selected measure.

**Platform information**
 - OS: Windows

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/10795
