### ISSUE TITLE
[MU4 Task] Re-organise "Measure" screen in "Style" dialog

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11200]
**Task description**
This is a task to reorganise and re-label settings within the "Measure" screen of the "Style" dialog.

**Existing layout (to be changed)**

<img width="922" alt="Screenshot 2022-04-14 at 11 54 24 pm" src="https://user-images.githubusercontent.com/86290556/163405668-1ec41b31-5975-44e6-ac94-d2707e00b66a.png">

**Proposed NEW layout**

<img width="1028" alt="UI-design_Styles_Measures" src="https://user-images.githubusercontent.com/86290556/163405733-47c31f4f-6a52-4183-86e7-af8230a781ed.png">

Please note: text field values above are indicative only, and do not represent actual default values.

Thanks!

**Comment by MarcSabatella** [comment]
Without diving in too deep, at first glance it's a huge improvement!  But - is this just about the labels, or are the different values (eg, everything being changed 1.500) also being proposed?  I'm guessing it's just a mockup?

**Comment by oktophonie** [comment]
"Please note: text field values above are indicative only, and do not represent actual default values."
Don't panic :)

**Comment by MarcSabatella** [comment]
Ah, missed that comment, thanks!

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
