### ISSUE TITLE
[MU4 Issue] Reopening TX16Wx Software Sampler VSTi crashes MU4

### ISSUE THREAD

**Issue by KaiVinter** [musescore/MuseScore#11207]
**Describe the bug**
Opening TX16Wx a second time crashes MuseScore 4

TX16Wx: https://www.tx16wx.com

**To Reproduce**
1. Create a score.
2. Open the Mixer.
3. Choose an instrument and change the Sound doing Sound > VST3 > CWITEC > TX16Wx.
4. Close TX16Wx.
5. Open TX16Wx again.

**Expected behavior**
TX16Wx should open again.

**Current behavior**
MuseScore 4 Crashes

**Video**

https://user-images.githubusercontent.com/88064903/163503496-3ba55217-3ffe-47a1-98d3-338416135eca.mp4

On the video I tried with an earlier version of TX16Wx, but then I upgraded to the latest and it still crashes.

**Platform information**
 - OS: macOS Mojave 10.14.6

**Tested on:**
Latest MuseScore 4 Nightly ( 2022-04-14 04:31 | 190M )

**Comment by Tantacrul** [comment]
Confirmed. Nice example, since this is a free plugin.

**Comment by vpereverzev** [comment]
Should be fixed in #12568
@KaiVinter please confirm the fix on master branch or on the **next** nightly build

**Comment by KaiVinter** [comment]
Thank you so much @vpereverzev !
Yes, I can confirm this works on the latest Nightly.
Tested on MacOS Mojave 10.14.6
