### ISSUE TITLE
[MU4 Issue] Trying to Slur a Particular Section Crashes MuseScore

### ISSUE THREAD

**Issue by jieshunwang** [musescore/MuseScore#11210]
**Describe the bug**
Trying to add a slur through four bars reliably crashes Musescore. This error seems to occur with a placement slur over the 4 bars via any method: using keyboard shortcut, inputting via mouse, inputting a shorter slur before dragging length into place, inputting the notation in different bars and copying it over into place. All of the methods above crashes MuseScore.

**To Reproduce**
1. Open file: [dropbox link](https://www.dropbox.com/s/hi660itkmguzpg8/May%20It%20Be.mscz?dl=0)
2. Place slur bars 9 - 12.
3. musescore crashes

**Expected behavior**
Add slur as per screenshot

**Screenshots**
Attempting to place slur as seen below crashes musescore.
![Screenshot 2022-04-15 182620](https://user-images.githubusercontent.com/39250962/163546262-4fdad6f5-58ee-487d-9b34-7e8e6cf39ef0.jpg)

**Platform information**
 - OS: Windows 11 Home 
 - Version: 21H2
 - Build: 22000.613
 - Experience: Windows Feature Experience Pack 1000.22000.613.0

**Additional context**

**Comment by DmitryArefiev** [comment]
Tested in **latest master build** on Win10, Mac12, LinuxMint 20.2 - **CRASH NO LONGER OCCURS**
(but crashed in alpha build)

Closing
