### ISSUE TITLE
[MU4 Issue] "Hide instrument name if there is only 1 instrument" not always applied

### ISSUE THREAD

**Issue by RootCubed** [musescore/MuseScore#11211]
**Describe the bug**
The style setting "Hide instrument name if there is only 1 instrument" (Style -> Score) is not honoured after adding and removing instruments to/from a part score. This happens in the master score too, but there it might be intended behaviour (?).

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a score with at least two instruments.
2. Open the part score of an instrument.
3. Observe that the instrument name is hidden, since the option is enabled by default.
4. Make another instrument visible, then invisible.
5. Observe that the instrument name is not hidden anymore, even though the option is enabled.

Video demonstration attached.

https://user-images.githubusercontent.com/41953062/163548692-9eb25634-0778-4135-914e-de0c385134fd.mp4

**Expected behavior**
The style setting "Hide instrument name if there is only 1 instrument" should always be applied.

**Platform information**
 - OS: Windows (but most likely all)

**Comment by Tantacrul** [comment]
@oktophonie - not sure if this is an issue you guys should take on (I'm guessing not) but thought I'd alert you to it just in case.

**Comment by oktophonie** [comment]
Score and parts should behave the same, I think. And we should interpret "when there is 1 instrument" to mean "when only 1 instrument is visible" (rather than "when the score contains only 1 instrument" - an academic distinction now, really, since it's so easy to show/hide instruments in parts.) Will sort.
