### ISSUE TITLE
[MU4 Issue] When loading a score created on Musecore 3.6 and trying to load it in Musescore 4 it either crashes, only shows part, or doesn't show anything

### ISSUE THREAD

**Issue by Jurassicboy2710** [musescore/MuseScore#11223]
When trying to load a score that I created or downloaded from Muscore three it either does 1 of three things. It crashes the whole application, It only shows a couple of measures and then the rest is just white, or nothing at all shows.

1. Press "File"
2. Press "Open..."

3. Locate folder with saved scores
4. Open score
5. Be prompted with a screen on format changes
6. Press "Ok"
7. Error Happens

What is expected is a nice clean opening of the file and the whole score to be there. Some formatting might have to be done to the score once loaded but no crash should happen. 

This is a screen shot of it only opening half way. This only happens if you put it into continuous view.
https://user-images.githubusercontent.com/103903531/163742854-5fd05363-1150-4cfa-bc97-846cc87b95f2.jpg

Operating System - Windows 10 Home

**Comment by RomanPudashkin** [comment]
The problem with the continuous view has been fixed here:
https://github.com/musescore/MuseScore/pull/10980

Please attach some scores on which the app crashes
