### ISSUE TITLE
[MU4 Issue] When Changing View to Continous View It Glitches and Has an Infinite Measure

### ISSUE THREAD

**Issue by Jurassicboy2710** [musescore/MuseScore#11226]
When viewing the score and changing the view to continuous view there are only two measures that pop up and the second measure is infinite.

1. Open up a new score or open recent score
2. Change view from "Page View" To "Continuous View Horizontal"
3. Encounter Error

When creating a score it can be disorienting to look at the score with page view. It is expected to change to a flat layout continuous on the horizontal horizon.

Screenshots
https://user-images.githubusercontent.com/103903531/163765892-e1cc1637-f62b-4f38-94a1-cdbf31b3b313.jpg
https://user-images.githubusercontent.com/103903531/163765894-289bfa52-1674-4966-9a8d-cc7308e5d424.jpg
https://user-images.githubusercontent.com/103903531/163765896-d97b39f4-187b-4047-b885-0d9716b53862.jpg

Operating System - Windows 10 Home

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/10980
