### ISSUE TITLE
[MU4 Issue] Program Crashes when I open a larger file made in Musescore 3.6

### ISSUE THREAD

**Issue by FancyMrMurray** [musescore/MuseScore#11224]
**Describe the bug**
I tried to open a score created in musecore 3.6.2, and it crashed. It contained many section breaks and other formatting objects. Other scores without as many of these were able to load.

**To Reproduce**
1. Go to open
2. Click on [any larger file]
3. See error

**Expected behavior**
My score would load (granted with some buffering time)

**Platform information**
macOS

File in question:
[Suite_on_Three_Artworks.mscz.zip](https://github.com/musescore/MuseScore/files/8503707/Suite_on_Three_Artworks.mscz.zip)

**Comment by HemantAntony** [comment]
Please give this issue a title and upload the score that crashes

**Comment by DmitryArefiev** [comment]
Tested in **latest master build** on Win10, Mac12, LinuxMint 20.2 - **CRASH NO LONGER OCCURS**
(but crashed in alpha build)

Closing
