### ISSUE TITLE
[MU4 Issue] External MIDI keyboard unable to play MuseScore instruments (Sound preview not working)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11234]
**Describe the bug**
There has been a regression in MS4. Now, the MuseScore instruments _cannot be played at all_. Input is only possible in note input mode, which of course stops the user from using the software to test the various instrument sounds or to demo ideas _without_ commiting them to notation.

**To Reproduce**
1. Ensure that your external MIDI keyboard is connected before launching MS4, and that the settings in Preferences > I/O are correct. 
2. Create a jazz combo from the Template secion, for example.
3. Click on a rest in the top staff and play the MIDI keyboard. Try other staves as well.

_Actual result_: No sound. 

**Expected behavior**

As MuseScore 2, the user should be able to click on any staff in non-note-input mode and be able to play the staff instrument.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7 . Akai LPK25 USB keyboard.

**Comment by DmitryArefiev** [comment]
@vpereverzev @Eism Checked in **latest master** - still **doesn't work**

As a reference, it should work like in **MuseScore 2** (it doesn't work in MuseScore 3 properly)

https://user-images.githubusercontent.com/90187801/184132594-d7122a26-43d4-4b45-a74c-774c9fcc40e3.mp4

**Comment by DmitryArefiev** [comment]
Fixed in #12879

But it doesn't work exactly as in MuseScore2, now it has fixed duration while playing MIDI keyboard. That's logged separately #13381
