### ISSUE TITLE
[MU4 Issue] Unable to select text times (Title, Subtitle, Compose ) within a text frame 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11252]
1. Create a score
2. Try to select Untitled Score or Subtitle or composer/arranger

https://user-images.githubusercontent.com/90187801/164038933-1b126c3b-35e1-4145-97ad-0fb19c050e03.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Recent builds

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
