### ISSUE TITLE
[MU4 Issue] Properties. Bar Width reset button is disabled after changes and deselecting current element 

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#11255]
**To Reproduce**
1. Open any score in MU4
2. Select a note 
3. In the Appearance menu of the Properties change the Bar Width value (and pay attention to the reset button)
4. Deselect the note and select it again
5. Pay attention to the Bar Width reset button

**Expected behavior**
Bar Width reset button is enabled after the value changed 

**Screenshots**

https://user-images.githubusercontent.com/101250347/164076673-1ccb2ef6-aff4-4734-9884-60a8b1e32eab.mov

**Platform information**
macOS 12, Win 11, Ubuntu 20

**Additional context**
The issue is not reproducible in MU3

**Comment by poypoyan** [comment]
It seems like `Measure::propertyDefault` in \src\engraving\libmscore\measure.cpp isn't executed so that `Pid::USER_STRETCH` should be set to 1.0 when resetting.

**Comment by Tantacrul** [comment]
Bar width seems to have been lost from here somehow... (it is still accessible as 'layout stretch' in the **bar properties** dialog.

**Comment by cbjeukendrup** [comment]
Looking at the code, it was surely not intentional. Just a mistake that has occurred when renaming some stuff in the code. Created a quick fix: #13075

(The issue with the reset button still occurs though.)

**Comment by Tantacrul** [comment]
Thanks @cbjeukendrup! I've upgraded the priority, since not being able to reset a parameter does deserve to be a P2

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
