### ISSUE TITLE
[MU4 Issue]

### ISSUE THREAD

**Issue by NickVnH** [musescore/MuseScore#11257]
Playback has cracking and popping sound.

**To Reproduce**
Press play in a score created in musescore 3.6.2 and opened in musescore 4.

**Expected behavior**
Clean playback

**Platform information**
Windows 10

**Additional context**
Considering i don't see alot of issues about this, so perhaps this is a driver issue on my end..
If someone who is more enlightened about the subject could tell me more about, that would be nice.

**Comment by HemantAntony** [comment]
This is a commonly reported issue one of which is #11222. Also, remember to give issues titles

**Comment by RomanPudashkin** [comment]
I will close this issue because we already have this one:
https://github.com/musescore/MuseScore/issues/11222

**Comment by NickVnH** [comment]
Thanks! And apologies, I didn't check thouroughly enough so it seems!
