### ISSUE TITLE
'Arrange' back/forward feature missing two options

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11253]
**Describe the bug**
At the moment, the 'Arrange' feature allows users to move an item behind or in front of another item. However, standard practice is to also have options to arrange 'To front' and 'To back'.

To front: this would move the selected item in front of anything else in the score.
To back: this would move the selected item to the back of the score

<img width="325" alt="image" src="https://user-images.githubusercontent.com/21022311/164040533-40349055-94b3-4e79-b2f9-ba8bd354b8a4.png">

This feature was never fully completed (by design) due to the transition from MS3 to MS4 - as this new inspector was originally created to live in V3.

**Comment by MarcSabatella** [comment]
These would be nice indeed.  But for the record, also, the existing buttons don't work :-).  Well, they kind of do, but you have to press them literally 50 or more times before anything happens in most cases.  That's because it's just incrementing or decrementing the internal stacking order by a small fixed amount.  The MU3 model of giving direct control over stacking order was far more direct and efficient.  It just wasn't very understandable for newcomers.  Ideally, we'd find a way to serve both newcomers and people concerned about efficiency and accuracy (eg, setting a very specific stacking order to facilitate reusing the same symbol in a different context later).

**Comment by Tantacrul** [comment]
I would call the MS3 version incomprehensible. Absolutely no way most users would ever intuitively learn how it works!

Yes, we will need to fix this properly. Moving the z order the way we are doing now is useless.

I fear it'll be hard to make the feature work well with old scores but at least bring to front and send to back will help them fix it more easily

**Comment by MarcSabatella** [comment]
I don't *think* there would be a problem with older scores, as internally, this is all still based on the same "Z" values as far as I know.  At least, that's what would totally explain the current apparently-broken behavior of the forwards/backwards buttons.

For the "proper" fix, what the forwards/backwards buttons *should* do is simply check the current stack of elements and figure out which the next element in line is, then set the "Z" value to just above/below that.  The values for each element type are in increments of 100, so I'd recommend 50 beyond the element you are shooting for (eg, 1650 to lay behind an element of "Z" value . 1700).  Shouldn't be hard at all to implement that way.  We actually already have logic to move the selection through the stack as you Ctrl+click elements.

But while most people won't need it, having explicit control over the "Z" value directly *is* quite useful on occasion.  For example, it's pretty common to use an opaque white graphic to blot out certain elements while exposing others - such as to break a tie that crosses over a key signature change   A Z value of 1150 is perfect for that.  Or text elements with opaque white backgrounds designed to blot out a barline and/or staff lines.  But, different "Z" values are needed for different cases.  Once one comprehends this (and it *is* perfectly comprehensible through documentation, even if not intuitive), you can take advantage of this to create nicely customized palettes with this stuff all preset.

Fiddling with forwards/backwards buttons every time you add such an element from the palette beats fiddling with "Z" values in a spinbox every time, to be sure.  But it's still fiddling with something you shouldn't need to fiddle with, when you could have customized your palette to avoid the need for that.  So I would still advocate for exposing the "z" value directly in addition to the arrange buttons.  They would actually complement each other nicely, as watching the "z" value update as you hit the other buttons would give you insight into what is going on.

I would agree it's not a big deal to have to fiddle with the arrange buttons, but it's important, I think, to realize that there really *is* value in the explicit "Z" setting, before completely ruling out the idea of including that as well.

**Comment by quinnouyang** [comment]
From my experience, I've relied on "To Front" to get elements on approximately the same z-level before using "Forward" etc. to adjust them so I don't have to keep spamming "Forward." I think users would only care about having control over a "local area" of elements and want to easily change the z-levels of those.
