### ISSUE TITLE
[MU4 Issue]Text lines: Visibility shortcut not working for staff text lines 

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11265]
**Describe the bug**
If you create a staff text-line you cannot make it invisible using the V shortcut.

**To Reproduce**

1. Creat a guitar staff/tab score from the Template section of the New Score wizard.
2. Click on the first whole note rest and add a staff line from the Lines palette.
3. Select the line in the tab and click "V".

RESULT: Nothing happens. (However if you use the "Properties" sidebar the "Visible" option works.)

**Expected behavior**
The line should become invisible when the visibility shortcut is pressed.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7

**Comment by Tantacrul** [comment]
Confirmed in the latest nightly (also, what an odd bug! :D)
