### ISSUE TITLE
[MU4 Issue] Text-lines: Property to allow user to adjust horizontal gap between text and line

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11264]
AFAICS, there is no way for the user to adjust the horizontal gap between text and its line in a text-line. All text-lines have the same default space. 

**Expected behavior**
A user-adjustable gap between text and line in text-lines.

**Screenshots**

Some published works favour the guitar barre line line flush to the text: 

![barre_line_(noad)](https://user-images.githubusercontent.com/87246583/164247712-1b11e5c2-85d0-4297-8aaa-3bf8182fe110.png)

![barre_line_(harris)](https://user-images.githubusercontent.com/87246583/164248383-4a9f413f-5ee7-4a85-a47c-6fdc49528f86.png)

Others have a space:

![barre_line_(noad1)](https://user-images.githubusercontent.com/87246583/164248854-011ab9d8-361d-4ef2-be70-010937b499c3.png)

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7

**Comment by Tantacrul** [comment]
If I understand this bug correctly, then you can edit the vertical position of text on a line by selecting the line and going to the 'Properties' panel and selecting the 'Text' tab. Vertical offsets can be found there for most (if not all) text lines.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/21022311/166006858-f4ffa50b-c983-4ae3-af48-55bf6b68a566.png">

If this doesn't answer your request then I'll reopen this bug. 

Thanks!
Martin

**Comment by rgreen5** [comment]
Clicking on the "Text" tab _does_ give you access to a property called "Offset"  but, this should only affect vertical and _not_ horizontal alignment (that it affects both, currently, is a bug; see #11266).

So, AFAICS, there needs to be both a "Vertical offset" button _and_ a "Gap (horizontal)" button in the Text tab.

So, could this be reopened?

**Comment by Tantacrul** [comment]
I don't think we need a horizontal offset option. It was overkill in MS3 and certainly the kind of thing that should live in an engraving styles section and not in the inspector. Also, there is already another bug about the diagonal positioning problem - I've recommended renaming the vertical position option there.

**Comment by quinnouyang** [comment]
Partial workaround for increasing the **gap** between the text and the line is appending whitespace to the text. This sounds more like editing text margins rather than a horizontal offset, unless we want the text to be independent of the line position, e.g. allowing it to overlap the line if we move it to the right enough.

**Comment by njantony1** [comment]
@Tantacrul this looks like an interesting one, I would love to take it on as a first-time contributor! I'd be working on this with @bakalr10 as a part of a school assignment. Would you be willing to assign this to us and share the design you had in mind?

**Comment by cbjeukendrup** [comment]
@njantony1 You're welcome! For technical questions you can address me. Maybe you'll also like to join [our Discord server](https://discord.gg/HwHhXEbJ4r).

**Comment by Tantacrul** [comment]
@njantony1 - cool.

Well, all we need to satisfy what @rgreen5's request is to have an offset field for X (currently we only have Y). You can see exactly how this should look by clicking on any element and selecting the 'Appearance' popup, which contains an 'Offset' setting for X and Y.

<img width="271" alt="image" src="https://user-images.githubusercontent.com/21022311/228914905-02761f4f-a4d8-440d-9d50-0ef8024ea2b0.png">

**Comment by Tantacrul** [comment]
Excuse the slightly ugly mockup here. I'm away from my normal machine (on vacation)

<img width="526" alt="image" src="https://user-images.githubusercontent.com/21022311/228915467-d465fcbe-f4ee-402e-bd02-d7d7d73d11d6.png">

**Comment by njantony1** [comment]
Looks like we got this working! 

![offset_0](https://user-images.githubusercontent.com/60052199/232910742-63205d1f-9a38-4279-972d-3629535a7684.png)
![offset_3](https://user-images.githubusercontent.com/60052199/232910793-92cc74dd-0481-469e-88e6-deb4dd52e6e3.png)
![combined_with_offset](https://user-images.githubusercontent.com/60052199/232910813-8c79737a-e997-4fe5-bb45-a2068ae1618d.png)

Would you also like us to add similar functionality for "Text when continuing on to a new system," or is this place the only one where you want it? Thanks!

**Comment by Tantacrul** [comment]
Seems like a wise decision.

One thing: I'm not a fan of '**Begin line gap from text**'. Very hard to figure out what that might do.

Perhaps: **Gap between text and line**

**Comment by njantony1** [comment]
With the current implementation that we have, the "gap between text and line" (which we will change the title to) affects both locations simultaneously. Would this be the desired behavior? Or would you prefer to separate them? One might argue that for reasons of consistency, the current behavior is desirable.

https://user-images.githubusercontent.com/60052199/232973382-0dd47fe3-bdc7-4d23-bb7b-43ed1caf7773.mp4

**Comment by Tantacrul** [comment]
Ah. So, because there's a dividing line under the **'Begin line gap from text'** but not above it, I assumed it was only related to the upper offset.

Just put a divider above it too so it will feel like a separate section and that should be fine.

**Comment by Tantacrul** [comment]
And yes, one setting for both is obviously much better. Thanks!
