### ISSUE TITLE
[MU4 Issue] No apparent default color when switching to dark theme

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11268]
When a user first starts MU4 after installing - or after resetting preferences - you are greeted with the option of selecting a color theme. 
 The light theme is offered as the default choice, and  with it, an accent color of blue:

![image](https://user-images.githubusercontent.com/1799936/164260579-ff2eeaba-77cc-4eda-96e4-78d05600ca5e.png)

But if you switch to dark mode, you find there is *no* accent color preselected - none of the color buttons are highlighted:

![image](https://user-images.githubusercontent.com/1799936/164260747-e57ac532-3152-44e9-bbc7-4bef6de8bb09.png)

That much is a bug, pure and simple.  But also, why is red the "de facto" default for dark mode?  We are recommending that everyone working on documentation for MuseScore standardize on dark theme, blue accent.  So, why not make blue the actual default for dark mode?

**Comment by quinnouyang** [comment]
Note that the red accent is also not selected when you check it in Preferences -> Canvas
<img width="372" alt="image" src="https://user-images.githubusercontent.com/90884224/164261986-2432fdf3-1fcb-4ca5-8402-dfa2efcfff53.png">

**Comment by MarcSabatella** [comment]
BTW, instead of selecting blue specifically as the default for dark the first time you enable it, another possibility is to simply borrow the current light theme accent color.  So if upon first starting, you change accent color to green, then immediately decide to try out dark mode, probably we should stick with the green.

I recognize that *after* having enabled dark mode for the first time, now there are independently-maintained accent colors, and that's a good thing.  I'm just talking about the experience when you first enable dark mode after installation or resetting preferences.

And yes, all of this applies equally to the theme selector in the Preferences dialog.

FWIW, this isn't new, it's been this way as long as I can remember.  I reset preferences pretty often in my testing, and the same thing happens every time.
