### ISSUE TITLE
[MU4 Issue] Text-lines: "Offset" doesn't work as it should

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11266]
**Describe the bug**
If you create a text-line the "Offset" property causes the text to move at a diagonal, rather than vertically.

**To Reproduce**
1. Add a Staff text line from the line palette to the score.
2. With the text-line selected, in the Properties side bar, chose Text-line > Text.
3. Adjust the "Offset property"

RESULT: The text moves at a diagonal in relation to the line.

**Expected behavior**

The text should move vertically. In addition, IMV, the labelling should be better: "Vertical offset" for example.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7

**Comment by quinnouyang** [comment]
Fix seems to be in `textlinesettingsmodel.cpp` under `createProperties()`.
E.g. for `beginingText` (spelled wrong?), change 
`QPointF(m_beginingTextVerticalOffset->value().toDouble(), newValue.toDouble()));`
to
`QPointF(0.0, newValue.toDouble()));` (we include the first argument `xpos` offset)
Being safe here, but can someone verify this?

**Comment by Tantacrul** [comment]
I can confirm that this is still happening in the latest nightly. Also strongly agree that for this parameter, we should use the term '**vertical offset'**

**Comment by Tantacrul** [comment]
@quinnouyang - is your PR working perfectly or are you still experiencing problems?

Also - have you included the copy change in your PR (from 'offset' to 'vertical offset')?

**Comment by quinnouyang** [comment]
@Tantacrul I'd need to squash the commits (hence the draft PR) but from my manual testing, seems to work as intended. Here's another sample:  
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/90884224/166122656-d57b1e37-f7b6-4d2c-8889-538d7a007d7e.png">

As for adding a "Vertical offset" label, I like the vertical top-bottom arrow icon so if having too much text concerns us, maybe we can have a tooltip upon hovering over the box and/or the icon. Although I think the more important missing feature is text alignment with the line, e.g. see these Staff Text options:
<img width="150" alt="image" src="https://user-images.githubusercontent.com/90884224/166122777-9bd53b87-f070-4d02-8a12-ffd658146586.png">

**Comment by Tantacrul** [comment]
I think the string change is fine. Most people wouldn't think to hover over that vertical icon. I also think the alignment thing would be overkill. We'll be refining the engraving of these elements so people generally won't need to touch vertical offset anyway.

**Comment by quinnouyang** [comment]
Got it! Do we want to implement horizontal offset as mentioned in #11264?

**Comment by Tantacrul** [comment]
I don't have any strong opinion. If anyone wants to do it, I see no reason to object and can provide a design in a few minutes.

**Comment by quinnouyang** [comment]
I can try to implement it, could you send it over please?

**Comment by Tantacrul** [comment]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/21022311/166124849-80774617-8b5b-492c-95db-3032ec912578.png">

This is it, in all its glory! Note that the title should actually just be 'offset' in this case.

The horizontal icon is EF32 in the icon font.

**Comment by Tantacrul** [comment]
Bear in mind, it would need to be this way for all lines that contain text

**Comment by quinnouyang** [comment]
@Tantacrul Preliminary implementation (shrunk the page width to see the continuous text more easily):
<img width="621" alt="image" src="https://user-images.githubusercontent.com/90884224/166126071-991497f9-0385-4e8f-85a1-6ec62928631a.png">
Haven't figured out how to swap the positions of horizontal and vertical offset options. Also, I assume we at least expect this behavior of the line "following" the text while the anchor stays in place: 
<img width="591" alt="image" src="https://user-images.githubusercontent.com/90884224/166126119-789240d3-206b-4806-9396-5e30e26a1d4f.png">

**Comment by Tantacrul** [comment]
Hmm. The point of the horizontal offset is to create more distance from the line, so the line should not move when the horizontal offset changes.

**Comment by Tantacrul** [comment]
The ordering (horizontal on the left. Vertical on the right) is fine.

**Comment by quinnouyang** [comment]
> Hmm. The point of the horizontal offset is to create more (or less) distance from the line, so the line should not move when the horizontal offset changes.

Right, will try to fix the line in-place. If the user offsets the text to the right enough, should we allow it to overlap the line?

**Comment by Tantacrul** [comment]
> Right, will try to fix the line in-place. If the user offsets the text to the right enough, should we allow it to overlap the line?

Yes. I think that's the only logical answer... however, the more I think about this, the less sensible I think this option is.

**Comment by quinnouyang** [comment]
I can imagine people wanting a gap (though they _can_ just append spaces to the end of text), but that's not really a horizontal offset anymore.

The current implementatin just feels like another way to do move the element horizontally without changing the anchor...redundant IMO.

**Comment by Tantacrul** [comment]
Exactly, the MS3 way is pointless. Either you increase / decrease the gap or there's no point :D

**Comment by quinnouyang** [comment]
~~_thou should have X-Y position control for everything!!_~~

Hmm, what now then? Keep only vertical offset and add a text-line "gap" option? Feels like an "unusual" Properties option and I'm increasingly doubtful of the need. (Especially when the whitespace-after-text workaround is _so_ tempting.)

**Comment by Tantacrul** [comment]
I'd say leave just vertical for now. (and choose the title 'vertical offset')
