### ISSUE TITLE
Final Colours for MS4

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11261]
After some exploration and user testing / polling, we have arrived at what we hope are the final colours for MS4.

**Dark Mode**

1. Default BG Colour: #27272B
2. POPUP_BACKGROUND_COLOUR: #39393C
3. In our designs on Figma, I notice that the mixer's main background colour is (incorrectly) using POPUP_BACKGROUND_COLOUR for the main background right now. If this is also true in code, It should instead be using BACKGROUND_PRIMARY_COLOUR, which matches the rest of the main UI.
<img width="562" alt="image" src="https://user-images.githubusercontent.com/21022311/164234659-eaa1a52c-8fa6-4cd0-9d6a-21b226e7915b.png">

4. The default accent colour for dark mode should be set to Blue, not Red

**Light Mode**

1. Default BG Colour: #BCC1CC
2. Accent colours (from left to right)
- Red: No change
- Orange: #EDB17A
- Yellow: #D6CC78
- Green: #8BC9C5
- Blue: No change
- Purple: #A09EEF
- Pink: #DBA0C7

<img width="731" alt="image" src="https://user-images.githubusercontent.com/21022311/164233245-38c4fae3-d6b8-40ae-8a7c-0355f5e4c7e4.png">

**Comment by Tantacrul** [comment]
When ready, just ping me for a very quick bit of testing to confirm everything is OK.

**Comment by MarcSabatella** [comment]
Btw, last I checked the accent color reset itself when switching to dark mode.  Could that be addressed too?

**Comment by Tantacrul** [comment]
I can't reproduce that (unless I'm misunderstanding). If it is an existing bug, I'd probably raise it separately.

**Comment by cbjeukendrup** [comment]
@MarcSabatella the accent color is meant to be a per-theme setting. Are we on the same page there?

**Comment by MarcSabatella** [comment]
What I mean is, the picture of the theme dialog above shows the accent color is blue.  The moment I click the "dark" button. it changes to red, but also, the accent color selector shows nothing selected.  So changing to the official recommended color scheme for documentation requires two clicks: first to change to dark, then to re-establish blue as the accent color:

https://watch.screencastify.com/v/LifsVdGgHCr7MUuBACmH

**Comment by jessjwilliamson** [comment]
By the way, by default, the accent colour for light mode should be blue, not red. (both themes should be blue!)

**Comment by Tantacrul** [comment]
The accent colours are per-theme. If you choose blue for light and purple for dark, and toggle between them, both are remembered. We don't link a choice in one to the other.

@cbjeukendrup is correct

**Comment by cbjeukendrup** [comment]
> 1. Default BG Colour: #27272

What is the final digit?? :)

**Comment by MarcSabatella** [comment]
I had just done a reset preferences.  I had never gone to dark mode before in this session.  I think it reasonable to expect that open switching to dark mode for the first time, there should be a reasonable default color selected, just as there was when I first reset preferences and found myself in the light theme.  It just looks broken right now to find there is a reasonable default accent color pre-selected for me in light mode, but no default at all selected when I for the very first time upon starting the program switch to dark mode.  There is literally nothing selected - none of the color icons are highlighted.  The color happens to red, but there is no visual indication that red was pre-selected for me.  This just looks unfinished, and it's one of the very first things users see upon installation.  We can and should do better.

Since blue is the officially-sanctioned accent color for documentation, I'm simply asking that the default for dark mode - the color you see *before* you make any other selection for yourself - be blue, not "nothing will appear selected at all, but it happens to look like red".

**Comment by jessjwilliamson** [comment]
> > 1. Default BG Colour: #27272
> 
> What is the final digit?? :)

B

**Comment by Tantacrul** [comment]
If there's no colour selected, that's a bug - and quite a weird, new one. Can you log it separately?

**Comment by Tantacrul** [comment]
> > 1. Default BG Colour: #27272
> 
> What is the final digit?? :)

Sorry @cbjeukendrup, I was away. The hex is: #27272B

**Comment by Tantacrul** [comment]
Also @cbjeukendrup - @jessjwilliamson mentioned that the was confused by my description 'BG colour'. I'm sure you realised but to be sure, I'll clarify that I meant the 'Background colour' behind the score.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/21022311/164260939-6037f8bd-bafd-4011-ba00-fe863b9719cd.png">

**Comment by MarcSabatella** [comment]
Default color issue is https://github.com/musescore/MuseScore/issues/11268

**Comment by cbjeukendrup** [comment]
@Tantacrul I created PR #11269, the test builds should be available in a while!

**Comment by Tantacrul** [comment]
Awesome @cbjeukendrup, will check later tonight

**Comment by Tantacrul** [comment]
@cbjeukendrup Thanks for this! I've asked @jessjwilliamson to have a look and give her blessing too. In the meantime, I've noticed one thing:

None of the popups seem to be using the **POPUP_BACKGROUND_COLOUR** style. For dark mode, in particular, this means that the popups don't stand out because they're the same style (BACKGROUND_PRIMARY_COLOUR) as the main UI.

This was meant to be used for all popups:

For example in the inspector:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/21022311/164400462-932215b9-2087-4a5c-9897-4db1ebebf7bd.png">

New score wizard:
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/21022311/164400772-b88b6075-4376-4a67-9775-34453dddbb0f.png">

Add Palettes popup:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/21022311/164400994-258652dd-f0ea-46fa-9313-4da034ed598e.png">

You get the idea... all popups.

We didn't notice this before because we assumed the colours we chose were just too similar to the main UI colour. Now I can see that the correct colour style isn't being used.

Could you fix this?

**Comment by Tantacrul** [comment]
Also (because this might on first glance be confusing) I should mention that currently in the light theme, the colour of **BACKGROUND_PRIMARY_COLOUR** & **POPUP_BACKGROUND_COLOUR** is the same.

We set it POPUP_BACKGROUND_COLOUR to solve a contrast problem in dark mode but also because it will be useful when  creating new colour themes and accessibility features in the future. It gives us flexibility.

**Comment by cbjeukendrup** [comment]
@Tantacrul I added a fix to #11269!

**Comment by Tantacrul** [comment]
Well, you've fixed the problem for sure! I've noticed two minor cleanup issues:

The 'Show more' toggle is still using **BACKGROUND_PRIMARY_COLOUR**

<img width="268" alt="image" src="https://user-images.githubusercontent.com/21022311/164456151-59621947-37de-4de1-ac25-3e620b7f24f5.png">

<img width="268" alt="image" src="https://user-images.githubusercontent.com/21022311/164456209-9d5fd019-73b6-4ef4-8901-ac7754b4d845.png">

This is also true for the 'Playback' popup:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/21022311/164456633-4906b1fb-1364-4a67-811c-451712f6e118.png">

<img width="291" alt="image" src="https://user-images.githubusercontent.com/21022311/164456672-1004b373-ffd3-477e-9678-1270dd3ff99b.png">

**Comment by cbjeukendrup** [comment]
Should be better now!
