### ISSUE TITLE
[MU4 Issue] App is crashed when importing second Guitar Pro score

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11282]
**To Reproduce**
1. Import any GP file in MU4
2. Close the opened score as a tab (don't close the app)
3. Import another GP file 
4. Pay attention to the app behavior

**Expected behavior**
Any GP file can be opened without crash

**Screenshots**

https://user-images.githubusercontent.com/101250347/164484032-0add0d3f-9839-4011-8ec6-4df11c57bdcc.mov

[Архів.zip](https://github.com/musescore/MuseScore/files/8532670/default.zip)

**Platform information**
 - OS: macOS, Windows, Linux

**Additional context**
The issue is reproducible for any versions of GP (Guitar Pro)

**Comment by sammik** [comment]
Exactly same happens, when importing musicxml files following steps described above.

**Comment by cbjeukendrup** [comment]
Today, I experienced the same with just mscz files. I think there was a crash that happened just with the second file you open. 
I also think it has already been fixed, by PR #11293.

**Comment by boryskuzmenko** [comment]
**FIXED** in https://github.com/musescore/MuseScore/pull/11293
