### ISSUE TITLE
Glissando down won't play with appergio

### ISSUE THREAD

**Issue by UnaidedButton86** [musescore/MuseScore#11297]
**Describe the bug**
If you set a glissando down from a chord with an appergio, the glissando down wouldn't play.

**To Reproduce**
1. Set the notes and glissando as seen in the screen video below.
2. Play the sound. Nothing wrong, right?
3. Add an appergio on the chord.
4. Error: The glissando down doesn't play.

**Expected behavior**
- The lowest e with the glissando should play up to the highest e. ✔ (this isn't part of the bug)
- The highest e-b should play a appergio (so just e-b after each other) ✔
- The glissando should play back to the lowest note while the last step is playing. (as seen in the first clip) ❌

**Screenshots**
Here's a screen video made by me: https://youtu.be/9DQndjDXJyI
The file was too big for directly uploading :(

**Platform information**
 - OS: Windows 10
 
**Other information**
I'm not native English and i'm not a developer, so i can't code.

**Comment by HemantAntony** [comment]
Just close this issue. You can't delete issues

**Comment by HemantAntony** [comment]
Also, you don't need to create a youtube video. You can just drag and drop a video to where you want to post it in the textbox :)

**Comment by UnaidedButton86** [comment]
> Also, you don't need to create a youtube video. You can just drag and drop a video to where you want to post it in the textbox :)

The file was too big

**Comment by UnaidedButton86** [comment]
I wanted to delete the comment because i didn't finish it, but ima edit it

**Comment by Jojo-Schmitz** [comment]
And fix the typos, it is "Gissando" not Glissiando" ;-)

**Comment by UnaidedButton86** [comment]
Oh, I thought i mentioned I am not native English, I'm a Dutch kid

**Comment by Jojo-Schmitz** [comment]
Even in Dutch it is Glissando. (Well actually Italian)

**Comment by UnaidedButton86** [comment]
I always use gliss. Never use the full word

**Comment by Jojo-Schmitz** [comment]
Always? Really? ;-)

**Comment by UnaidedButton86** [comment]
Oh shoot :(

**Comment by HemantAntony** [comment]
Wait, is this MU3?

**Comment by UnaidedButton86** [comment]
> Wait, is this MU3?

Yes why

**Comment by HemantAntony** [comment]
I'm pretty sure GitHub issues are for MU4. You have to report MU3 issues on musescore.org

**Comment by UnaidedButton86** [comment]
> I'm pretty sure GitHub issues are for MU4. You have to report MU3 issues on musescore.org

Okay, maybe head over there later. I've accidentally deleted the last part but it said:
"Since musescore 4 is about the new vst player it could relate"
I also didn't know this was for msc 4.

**Comment by Jojo-Schmitz** [comment]
GitHub issues are for MuseScore 4 __AlPHA__ (and maybe Beta too)

**Comment by UnaidedButton86** [comment]
> And fix the typos, it is "Glissando" not Glissiando" ;-)
> 
> And "arpeggio" not "appergio"

1st: I've not studied music theory that hard
2nd: I've not gotten any typo recogniser: 
![image](https://user-images.githubusercontent.com/87303800/164705510-de14fa15-c635-4168-a353-91a886aed03b.png)

**Comment by UnaidedButton86** [comment]
> GitHub issues are for MuseScore 4 **ALPHA** (and maybe Beta too)

Thanks. I think i close this issue then.

**Comment by Jojo-Schmitz** [comment]
> 2nd: I've not gotten any typo recogniser: 

Look again, the red wiggly line below it

**Comment by UnaidedButton86** [comment]
> > 2nd: I've not gotten any typo recogniser:
> 
> Look again, the red wiggly line below it

Below EVERYTHING*

**Comment by Jojo-Schmitz** [comment]
Almost everything, I guess the rest is not spelled correctly in Dutch...

**Comment by UnaidedButton86** [comment]
Lol still going about the typos

**Comment by UnaidedButton86** [comment]
Hier's het in t Nederlands als da zo nodig moet:

**Beschrijf de bug**
Als je een glissando neerzet van een akkoord met een arperggio, zou de glissando-down niet spelen.

**Om het te reproduceren**
Stappen om de fout te reproduceren:

- Stel de noten en glissando in zoals te zien is in de onderstaande schermvideo. ✔
Speel het geluid af. Niks mis toch?
Voeg een arpeggio toe aan het akkoord.
Error: De glissando naar beneden wordt niet afgespeeld.

**Verwacht gedrag**

De laagste e met de glissando zou tot de hoogste e moeten spelen. ✔ (dit maakt geen deel uit van de bug)
De hoogste e - b moet een arpeggio spelen (dus gewoon e-b na elkaar)
De glissando moet terugspelen naar de laagste noot terwijl de laatste stap wordt gespeeld. (zoals te zien in de eerste clip) ❌
Schermafbeeldingen
Hier is een schermvideo gemaakt door mij: https://youtu.be/9DQndjDXJyI
Het bestand was te groot om direct te uploaden :(

**Platforminformatie**

Besturingssysteem: Windows 10

**Andere informatie**
Ik heb Engels niet als moedertaal en ik ben geen developer, dus ik kan niet coden.

**Comment by HemantAntony** [comment]
Google translate surprisingly worked :)

**Comment by UnaidedButton86** [comment]
> Google translate surprisingly worked :)

Yeah but it has very much mistakes the other way around

**Comment by UnaidedButton86** [comment]
> > > > > > > > > > > > > > > > > >
