### ISSUE TITLE
[MU4 Issue] Crash when pressing arrow key when Bracket selected in Edit mode

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#11294]
**Describe the bug**
A crash occurs when you press an arrow key while a Bracket is selected in Edit mode. 

**To Reproduce**
1. Create a score with multiple instruments, and add a Bracket if not yet present;
2. Double-click the bracket to enter "Edit mode"
3. Press one of the arrow keys
A crash occurs. 

**Expected behavior**
No crash; maybe, the bracket should respond to the key press.

**Platform information**
 - OS: reported on macOS

**Comment by DmitryArefiev** [comment]
Fixed in #11681
