### ISSUE TITLE
Dropdowns no longer functioning.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11311]
**Describe the bug**
I just discovered that it is no longer possible to select an option in a dropdown. As demonstrated in the video below, when trying to select an option in a dropdown, you can sometimes end up selecting UI 'behind' them instead.

Tested on MacOS only.

https://user-images.githubusercontent.com/21022311/164894168-679aced6-9592-4e00-b622-e5129c07c941.mov

**Comment by HemantAntony** [comment]
Can confirm this occurs in Windows 11 too

**Comment by HemantAntony** [comment]
@Eism this bug is caused by line 190: `popup.closeAndReturnFocus()` in `onActiveChanged`. I have no idea for a fix. So I hope this helps you
