### ISSUE TITLE
[MU4 Issue] Continuous View - Instrument Name Position

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11326]
**Describe the bug**
Instrument names do not remain in fixed position and measure numbers are not updated when scrolling.

**To Reproduce**

1. Go to 'Any open score'
2. Click on 'Continuous View'
3. Scroll left
4. Note the instrument names disappear when scrolling left past the first bar.

**Expected behavior**
Instrument names should remain in a fixed position when scrolling left past the first bar (as in Musescore 3.x).

Measure number should be indicated above the first visible bar and correspond to measure number of first visible bar as user scrolls left or right.

**Screenshots**
<img width="1920" alt="Screen Shot 2022-04-25 at 10 41 14 AM" src="https://user-images.githubusercontent.com/30370609/165042987-1cea070b-981b-4a1b-ab7d-7674eee300d3.png">
<img width="1918" alt="Screen Shot 2022-04-25 at 10 43 01 AM" src="https://user-images.githubusercontent.com/30370609/165043024-d3e53874-5985-49ee-8763-a0ecbf3be12f.png">

**Platform information**
OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2199691027
revision: github-musescore-musescore-41e572f

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
I completely missed this. Thanks @lengthwave!

The functionality should just match MS3

**Comment by DmitryArefiev** [comment]
The same as #8924

**Comment by DmitryArefiev** [comment]
Fixed in #11396
