### ISSUE TITLE
[MU4 Issue] Crash when creating/opening a second score

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11339]
https://user-images.githubusercontent.com/90187801/165078863-d1538978-2bb2-427f-9039-cac2975fd8ce.mov

**Platform information**
 **macOS, Linux**

**Additional context**
Doesn't occur on **Windows**

**Comment by vpereverzev** [comment]
@DmitryArefiev please check on the latest master

**Comment by DmitryArefiev** [comment]
Tested in **master build** on Win10, Mac12, LinuxMint 20.2 - **FIXED**

Closing
