### ISSUE TITLE
New MS4 Loading Screen

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11330]
**Task description**
Essentially, this should work exactly like the MS3 loading screen, including the dynamic loading text.

I have provided it as a Figma file (so, all vector) but can provide a PNG version if needed.

Here's what it looks like
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/21022311/165067152-de61ba3b-111d-49eb-984d-5bbf0d90a9e7.png">

We should use the text field here to describe important processes:

- **Scanning for VST plugins: name of plugin** (this is important, since there may be a lot of scanning involved the first time a user opens MS4)
- **Loading (process, file, etc.)** (I don't have suggestions here - anything the development team thinks is relevant / anything else that impacts opening time

(Ignore the 'restoring session' text. This is just a placeholder example)

**Comment by RobFog** [comment]
I'd prefer "Restoring session" to "Resoring session". :-P

**Comment by Jojo-Schmitz** [comment]
You're mentioning a sore point there...

;-)

**Comment by HemantAntony** [comment]
@Tantacrul This looks really cool!

**Comment by Tantacrul** [comment]
Resoring is a new technical process... that...

**Comment by Tantacrul** [comment]
> You're mentioning a sore point there...
> 
> ;-)

Nah, it's cool to correct my typos :)

**Comment by HemantAntony** [comment]
I wonder if there will be holiday variations of the splash screen like in MU3
