### ISSUE TITLE
[MU4 Issue] Drop shadow less visible vertically/underneath pop-up

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#11337]
**Describe the bug**
Me and @Tantacrul noticed recently in most pop-ups that there is a lot of drop shadow going on on both horizontal sides but much less on the bottom of the pop-up/vertically. 
The issue is affecting the dark mode the most - it does not 'pop' very well.
Light mode is much more visible to see the issue. 

The bottom needs some more shadow intensity, around same value as the sides

![image](https://user-images.githubusercontent.com/71656189/165076854-81fce5ef-016a-49e3-900f-e3767d2605f2.png)

This is how the drop shadow should look like here:
![image](https://user-images.githubusercontent.com/71656189/165079922-8b7eaa27-4788-48d0-a5be-033df2c5a9df.png)

**Comment by Tantacrul** [comment]
Making a P2 because it helps popups look more like popups in dark mode (they are hard to distinguish from the BG)

**Comment by boryskuzmenko** [comment]
**FIXED**
