### ISSUE TITLE
Create link to Privacy Policy in the 'About' panel

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11334]
**Task description**
I have updated this on Figma. We just need a link that takes us to our Privacy Policy.

For now, until the PP is ready, I suggest linking to the MuseScore.org homepage.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/21022311/165072361-e1cbffe7-9f1f-4e9b-aea7-bd4707b79d37.png">

For anyone interested, we're nearly finished the privacy policy text. I'll be publishing a draft for consultation shortly. It's pretty standard stuff but want to make sure the wording is clear.

**Comment by Tantacrul** [comment]
Or perhaps @shoogle: you could create a dummy page on musescore.org where we'll eventually publish the new privacy policy? Then we can just link to that?

**Comment by Tantacrul** [comment]
This is linked to another task, which also requires a PP link:
https://github.com/musescore/MuseScore/issues/11336

**Comment by shoogle** [comment]
@Tantacrul, sure. Are we referring to it as a "Privacy Policy" or a "Privacy Notice"? Audacity calls it a "notice" on the website and a "policy" in the app, not that it really matters of course.

**Comment by Tantacrul** [comment]
> 

Yeah, I noticed that too. I've asked to use the term Privacy Policy everywhere, so let's just go with that.

**Comment by HemantAntony** [comment]
@Tantacrul I have created a fix. I just need the URL now:

https://user-images.githubusercontent.com/88136054/165093455-815fe939-c634-4625-9351-06c5daf9c5b3.mp4

**Comment by Tantacrul** [comment]
Hahah. Although that is funny, I would **strongly** advice not to have that link in the master build. A tester who isn't aware of our GitHub hijinks might get the wrong idea and think we're not taking privacy seriously!

I'd just link to the MuseScore.org homepage for now.

Sorry for being a killjoy!

**Comment by HemantAntony** [comment]
> Hahah. Although that is funny, I would **strongly** advice not to have that link in the master build. A tester who isn't aware of our GitHub hijinks might get the wrong idea and think we're not taking privacy seriously!
> 
> I'd just link to the MuseScore.org homepage for now.
> 
> Sorry for being a killjoy!

Yeah I'm going to remove that :)

**Comment by Tantacrul** [comment]
Thanks btw!
