### ISSUE TITLE
[MU4 Issue] Toolbar - Docking - Two columns when docking L/R

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11348]
**Describe the bug**
When docking the toolbar to left or right position, the toolbar is snapped to two columns with no ability to adjust.

**To Reproduce**
1. Click on Toolbar handles
2. Click and drag to left position
3. Click and drag to right position
4. See issue

**Expected behavior**
Expected default behavior is single column toolbar like 3.x

**Screenshots**
<img width="549" alt="Screen Shot 2022-04-25 at 4 37 05 PM" src="https://user-images.githubusercontent.com/30370609/165100269-d32c6683-4ea2-43fc-a1b6-947fe33033cc.png">

**Platform information**
 OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by lengthwave** [comment]
@Tantacrul  - FYI

**Comment by Tantacrul** [comment]
By design for now. The single column version in 3.x often extended so far vertically, many options would be out of range.

We'll add refinements to this over time but I think this version is a big improvement on 3.x
