### ISSUE TITLE
[MU4 Issue] Parts - Rename - Text box edit state automatically changes on selection

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11345]
**Describe the bug**
After selecting to rename a part, when you place cursor in text window of highlighted part name, the state immediately changes to renamed and text window closes without any change.

**To Reproduce**
1. Click on Parts icon in top navigation
2. Click on three dot menu at right of any part name
3. Scroll down to 'Rename' and select
4. Try to edit by clicking on highlighted text
5. See error

Note: It does work if you start typing or hit delete key, but say you want to simply change "Horn in F" to "Horn" by placing the cursor in the text window and deleting "in F"..... no soup for you.

**Expected behavior**
Possible to click on the text window when in renamed state.

**Screenshots**
<img width="893" alt="Screen Shot 2022-04-25 at 4 14 04 PM" src="https://user-images.githubusercontent.com/30370609/165096994-81f8ed0e-de95-4b6a-a928-65c5d340ed6f.png">
<img width="1070" alt="Screen Shot 2022-04-25 at 4 11 10 PM" src="https://user-images.githubusercontent.com/30370609/165097029-eb490eca-dc3a-4247-951a-884cefc2b2ab.png">

**Platform information**
OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
Closing this because I've discovered it is a global problem with textboxes that seems to have occurred recently.

I've logged it here: #11445
