### ISSUE TITLE
[MU4 Issue] Timeline - Instruments not scrollable

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11342]
**Describe the bug**
Not possible to scroll through instruments in timeline.

**To Reproduce**
1. Select 'View > Timeline'
2. Try to scroll through instruments list in Timeline window

**Expected behavior**
Possibility to scroll through instruments lists (as in 3.x)

**Screenshots**
<img width="1916" alt="Screen Shot 2022-04-25 at 2 51 50 PM" src="https://user-images.githubusercontent.com/30370609/165084064-40832ab5-f909-4c6c-be48-78a3f5a543c6.png">

**Platform information**
OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
Nice catch!

**Comment by MarcSabatella** [comment]
FWIW, scrolling works partially me using the mouse wheel (well, two-finger swipe) on Linux.  But there is no scroll bar until there are enough measures to fill the window.  And then that scroll bar works, well, weirdly.  It does scroll but the visual feedback of the scrollbar itself seems kind of random.  And depending on the number of instruments, it may or may not make it to the bottom of the list.

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/9948
