### ISSUE TITLE
[MU4 Issue] Playback Controls - Not dockable in alternate positions

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11347]
**Describe the bug**
While the Toolbar is dockable in top, left, right, and bottom positions, Playback Controls are not dockable in alternate positions (only top right or float).

**To Reproduce**
1. Click on handles for Playback Controls 
2. Click and drag Playback Controls to desired position
3. See your desires be denied

**Expected behavior**
Ability to drag Playback Controls to alternate positions (top, left, right, bottom), same as 3.x.

**Screenshots**

<img width="958" alt="Screen Shot 2022-04-25 at 4 22 03 PM" src="https://user-images.githubusercontent.com/30370609/165098688-0346839e-b130-49e8-8c3c-e08c7b80a628.png">

**Platform information**
OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by lengthwave** [comment]
@Tantacrul  - FYI

**Comment by Tantacrul** [comment]
I agree this is probably desirable but we won't target it for 4.0. It will generate too many more bugs. Docking issues and the play panel issues took a long time to stabilise.
