### ISSUE TITLE
[MU4 Issue] Acell. rit. and other tempo change marks should be 'System text' (or else all Parts will be incorrect)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11343]
**Describe the bug**
**Acell. rit.** and other tempo change marks should behave as a system text.  The same as other Tempo marks behave. 
Now  tempo change marks behave as a staff text and don't show in all parts when adding to one staff in a score:

https://user-images.githubusercontent.com/90187801/165090125-038a516e-4de7-4be2-8fd5-2c3732d6725b.mp4

 

**Platform information**
macOS, Windows, Linux

**Comment by DmitryArefiev** [comment]
Fixed in #11955

**Comment by eg0n1984** [comment]
This should be reviewed, the #11343 is already deployed.
@boryskuzmenko can you confirm in a recent build? Thanks

**Comment by cbjeukendrup** [comment]
@eg0n1984 What do you mean? As far as I know, this fix has been merged and approved/confirmed. Are you experiencing problems?

**Comment by eg0n1984** [comment]
> @eg0n1984 What do you mean? As far as I know, this fix has been merged and approved/confirmed. Are you experiencing problems?

Sorry I posted on wrong issue. I will delete my comments
