### ISSUE TITLE
[MU4 Issue] New Score - Opens complete new instance when score already open

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11340]
**Describe the bug**
Creating a new score when a score is already open automatically opens a complete new instance of MuseScore.

**To Reproduce**
1. Open a score
2. With score open, select "File > New ..."
5. See described behavior

**Expected behavior**
Like Logic, Sibelius, or other popular applications that are both resource intensive and use VST, there should be a separate instance opened as a window on top of existing instance, without a redundant icon in the OS dock/systray.

User should be prompted with choice to close existing score or open new instance.
New instance should open, but without redundant icon.
User can toggle between sessions using navigation window (maybe under View?).

**Screenshots**
<img width="1919" alt="Screen Shot 2022-04-25 at 2 41 04 PM" src="https://user-images.githubusercontent.com/30370609/165082708-a7276777-83c5-4f53-9e37-c4505012d3e3.png">
<img width="1920" alt="Screen Shot 2022-04-25 at 2 41 20 PM" src="https://user-images.githubusercontent.com/30370609/165082707-94d8c5f0-57f1-46e6-b3cb-7bbf95b170fb.png">
<img width="1341" alt="Screen Shot 2022-04-25 at 2 42 18 PM" src="https://user-images.githubusercontent.com/30370609/165082699-dc385b03-1f22-4ed7-af96-0d36f87f794c.png">

**Platform information**
OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
This is actually a MacOS-specific problem (not sure about Linux). On Windows it works as expected.

![image](https://user-images.githubusercontent.com/21022311/165088738-a00cd42c-1088-4e76-8a87-ada7b1202ed7.png)

**Comment by jeetee** [comment]
Can we close this one in favor of https://github.com/musescore/MuseScore/issues/12647 which contains more developer-oriented argumentation around this issue?
