### ISSUE TITLE
[MU4 Issue] Note head selection clashes with note flag selection

### ISSUE THREAD

**Issue by amsuu** [musescore/MuseScore#11341]
Description: Note flag gets selected when clicking on note head of upside-down note, especially when belonging to a chord.

1. Open any score;
2. Find/create a treble clef stave;
3. Input a G4, B4, and D5, belonging to the same chord, OR any note at or above the middle line. This should cause them to flip;
4. Click on center part of the note head of the note, which is at the bottom of the chord\*;
5. Flag gets selected\*\*;

Expected behavior: note head gets selected

See attached video for more info

 - OS: Windows

**Issue occurs in MuseScoreNightly-202204250424-master-df96a36-x86_64** (latest nightly at the time of writing)

\*-The point of the chord is to push the note flag "deeper" into the note head, if you will. Any inverted note will do, but on single notes, the hit box for the note flag is actually a bit more to the bottom-right of the note head.

\*\*-If failed, try clicking more to the bottom-right, but still within the note head

https://user-images.githubusercontent.com/102627400/165080107-d26bd34c-126c-47fe-bd4f-83b37e905161.mp4

**Comment by Tantacrul** [comment]
Nice spot!

Flags should really be drawn behind noteheads, I think.

**Comment by MarcSabatella** [comment]
See also https://github.com/musescore/MuseScore/issues/10225.  Regardless of which element is drawn on top, there is meant to be a way to select what's underneath - it's just currently broken.
