### ISSUE TITLE
[MU4 Issue] Export - Parts Selection

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11356]
**Describe the bug**
When a new score is created Parts are automatically created. These Parts appear in the Parts window after clicking on the Parts icon in the top navigation. These parts do not appear in the Export window until the part has been opened and closed at least once.

**To Reproduce**
1. Create new score.
2. Click on 'Parts' icon and see list of available parts
3. Close Parts window
4. Select "File > Export" to open the Export window
5. See issue with no parts available
6. Close Export window
7. Click on 'Parts' icon and see list of available parts
8. Select a Part and click 'Open'
9. Close Parts window
10. Close Part in Score view by clicking on X in Part tab
11. Select "File > Export" to open the Export window
12. See Part in Export window

**Expected behavior**
When a part is created, it should automatically be available in the Export window.

**Screenshots**
<img width="872" alt="Screen Shot 2022-04-25 at 5 55 46 PM" src="https://user-images.githubusercontent.com/30370609/165117358-16ce413f-56b8-48b1-945e-ca60f14c68d4.png">

**Platform information**
OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
Again, a very nice spot!

@cbjeukendrup or @RomanPudashkin. Would we be able to easily display the parts in the export dialog at all times without needing to open and close them first?

**Comment by DmitryArefiev** [comment]
Fixed in #11858
