### ISSUE TITLE
[MU4 Issue] Workspace - New Workspace - UI Layout Issues

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11351]
**Describe the bug**
After creating a new workspace, moving toolbars to an alternate position, then returning to default workspace, UI Layout breaks.

**To Reproduce**
1. Create new Workspace (all checkboxes selected)
2. In new Workspace, drag Toolbar to left position
3. Go back to default Workspace

Note: adding additional workspaces and toggling between them introduces even greater inconsistencies.

**Expected behavior**
Workspaces should maintain their last saved configuration. Toggling between workspaces should correctly load last saved configuration.

**Screenshots**
<img width="1919" alt="Screen Shot 2022-04-25 at 5 18 32 PM" src="https://user-images.githubusercontent.com/30370609/165110485-18a54457-af65-4671-aa48-b3d497929e47.png">
<img width="1919" alt="Screen Shot 2022-04-25 at 5 18 32 PM" src="https://user-images.githubusercontent.com/30370609/165110713-39277b53-fe53-4653-b0ae-928806a60c39.png">
<img width="1916" alt="Screen Shot 2022-04-25 at 5 11 38 PM" src="https://user-images.githubusercontent.com/30370609/165110732-c6c23082-480e-42fb-879d-e8e5df89547d.png">
<img width="1916" alt="Screen Shot 2022-04-25 at 5 11 12 PM" src="https://user-images.githubusercontent.com/30370609/165110738-5b4d7fb8-b4ca-42e3-8a79-7265eaa07f7c.png">

**Platform information**
OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by DmitryArefiev** [comment]
Fixed in #11459
