### ISSUE TITLE
[MU4 Issue] Parts - Scrollbar Prevents Closing Tabs

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11358]
**Describe the bug**
When more parts are open than the width of the window, a floating scrollbar appears on top of tabs. This scrollbar prevents ability to close tabs.

**To Reproduce**
1. Open or create score with many parts
2. Open all parts
3. Try to close part tabs

**Expected behavior**
Ability to delete tabs.

**Screenshots**
<img width="1188" alt="Screen Shot 2022-04-25 at 5 57 14 PM" src="https://user-images.githubusercontent.com/30370609/165118202-f4e127c3-efa5-41b9-bb73-cfc9936d9e12.png">

**Platform information**
OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
Here is @jessjwilliamson design to fix this issue
https://www.dropbox.com/s/bjs56hs8nx3v8cn/Scrolling%20Tabs.pdf?dl=0
