### ISSUE TITLE
[MU4 Task] New colour definition - Hyperlink

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#11350]
Tagging @Tantacrul into this too as it has brought to our attention that the hyperlinks in some dialogs and other places contain hyperlinks with no colour being defined. 

Just added the 'HYPERLINK_COLOUR' in the Figma Master colour palette in all 4 themes.

Here are some examples with hyperlinks with updated colours.
**Another to include is the 'About Qt...' dialogue**

![image](https://user-images.githubusercontent.com/71656189/165105294-3ce6ed7e-6c2c-418c-a031-7c92a2bbda5b.png)
![image](https://user-images.githubusercontent.com/71656189/165105316-7e6b7b48-22d3-443f-b7c4-d193be8e4148.png)
![image](https://user-images.githubusercontent.com/71656189/165105532-90081771-9594-40cf-9c4b-07510b7c6f7c.png)

**Comment by boryskuzmenko** [comment]
**FIXED**
