### ISSUE TITLE
[MU4 Issue] Mixer - Scrollbar masks instrument label

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11367]
**Describe the bug**
When there are a large number of instruments, the scrollbar on the bottom of the mixer masks/obscures instrument names.

**To Reproduce**
1. Open/create score with more instruments than width of mixer
2. Go to Mixer
3. Scroll left/right
4. See issue

**Expected behavior**
Scrollbar should be below mixer, not floating on top of labels. 

**Screenshots**

<img width="1509" alt="Screen Shot 2022-04-26 at 12 06 29 AM" src="https://user-images.githubusercontent.com/30370609/165175550-fa2bf7f2-ea53-40cf-b309-5b1538bbfa2a.png">

OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
@jessjwilliamson - I guess we are probably going to have to sort that out. :)
