### ISSUE TITLE
Preloader for Audio Samples in Bottom Bar

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11365]
**Task description**
When opening / creating a new score, we should have a preloader in the status bar that informs users that MS4 is still loading and preparing audio samples. This will be particularly useful for larger scores that use the new orchestral library.

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/21022311/165135568-e9432f93-ca42-4163-a2cc-b67cb6c30e19.png">

For the developer who works on this, the dimensions can be found in Figma under **BOTTOM INFO BAR**

While this is displayed, it should replace the status bar info. When it is no longer needed, the status bar info can be displayed again (as shown in the image above).

**Comment by Eism** [comment]
@Tantacrul 
Looks like you didn't finish describing the problem.

**Comment by Tantacrul** [comment]
Just replace the statu...

That's it. Just one thing :)

<img width="704" alt="image" src="https://user-images.githubusercontent.com/21022311/178252555-59ec25bc-3293-4f12-a96b-0f7c8bb8e68a.png">

**Comment by Tantacrul** [comment]
OK, I've finished it off. It was a very basic point to make! Please let me know if you want me to clarify anything!
