### ISSUE TITLE
[MU4 Issue] Synthesizers - Mixer - Not all synth instruments appear in Mixer

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11368]
**Describe the bug**
Not all synth instruments are appearing in mixer

**To Reproduce**
1. Open attached file
2. Open Mixer
3. Notice all the missing instruments

**Expected behavior**
All instruments should appear in Mixer

**Screenshots**
<img width="1914" alt="Screen Shot 2022-04-26 at 12 28 42 AM" src="https://user-images.githubusercontent.com/30370609/165178080-56339108-847e-4e34-9851-3741bdfd2f94.png">

**Test File**
[test_synthesizers.mscz.zip](https://github.com/musescore/MuseScore/files/8558202/test_synthesizers.mscz.zip)

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by lengthwave** [comment]
@Tantacrul - FYI

BTW - How to attach .mscz?

**Comment by cbjeukendrup** [comment]
> BTW - How to attach .mscz?

I believe uploading them as a zip file is an option.
