### ISSUE TITLE
[MU4 Issue] Instrument descriptions are not shown in Instruments panel

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#11360]
**Describe the bug**
The instrument descriptions are shown at the bottom left of the New Score Wizard instrument selector:

![image](https://user-images.githubusercontent.com/20604032/165121304-828dc044-8c06-4b75-bb6b-ed4a5ca0b4ae.png)

However, descriptions are _not_ shown in the otherwise more-or-less-identical Instruments panel (as accessed after score creation, for example by pressing I):

![image](https://user-images.githubusercontent.com/20604032/165121550-b7507f17-0157-40df-a1aa-2d15e954882b.png)

**Expected behavior**
Descriptions should be shown in the Instruments panel just as they are in the New Score Wizard.

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
