### ISSUE TITLE
[MU4 Issue] New Score - Templates - No preview for first template in category list

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11374]
**Describe the bug**
When creating a new score from a template and browsing templates it is not possible to preview the first template in a category list. Single click does not change preview. It is only possible to preview after clicking on another score in the category list, then clicking on first score. 

**To Reproduce**
1. Go to 'Scores'
2. Click on 'New Score'
3. Select  'Create from template'
4. Browse to a template category
5. Single click on first template in category (nothing happens)
6. Single click on other template in category (see preview)
7. Single click on first template in category again (see preview)

**Expected behavior**
Should display preview of first template in category on single click and should preview by default when selecting the category.

**Screenshots**

https://user-images.githubusercontent.com/30370609/165245238-a0dfc508-13c2-473a-bcd5-691033be75d9.mov

**Platform information**
OS: macOS 12.2, Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2224366007
revision: github-musescore-musescore-9a7fabf

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
How did we miss this?

**Comment by HemantAntony** [comment]
This should fix it: #11385

**Comment by DmitryArefiev** [comment]
Fixed in #11403
