### ISSUE TITLE
[MU4 Issue] Palettes - Search - No context indication when results not found

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11378]
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**
1. Go to Palettes
2. Type something into search box that will not be found
3. Panel is blank without context

**Expected behavior**
If no results are found, should be some context provided (ex: No results found)

**Screenshots**

https://user-images.githubusercontent.com/30370609/165256662-2bad8eb9-2ed0-4b54-88a0-cdf974883d89.mov

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2224366007
revision: github-musescore-musescore-9a7fabf

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
When there are no results for a given search, there should be a message that says:

'No results found'
