### ISSUE TITLE
[MU4 Issue] Scores - Search - No results causes icon to disappear with out context

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11376]
**Describe the bug**
In the Scores tab when you search for a score and no results are found, all items disappear (including new score icon) with no context (ex: "Sorry, no results found").

**To Reproduce**
1. Go to 'Scores'
2. Type something in search bar that will not be found
3. Watch window contents disappear

**Expected behavior**
If no results are found, there should be some contextual cues to let the user know that nothing is found, for example text.

**Screenshots**

https://user-images.githubusercontent.com/30370609/165254585-1347104d-35ce-46e2-8c4d-9809aea4279c.mov

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2224366007
revision: github-musescore-musescore-9a7fabf

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by HemantAntony** [comment]
@Tantacrul I'm thinking about working on this. Can you tell me what should be the text when no related scores are found?

**Comment by Tantacrul** [comment]
I would go for:

1. The 'New' button does not disappear
2. The text should be 'No results found'

I would actually create another score BG rectangle, make it 30% opacity and place the 'No results found' text in it.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/21022311/177000406-52655ee3-aba8-43d2-b324-f695ed3f503e.png">

Note: I'd make sure the textbox can go down to two lines for translations

**Comment by HemantAntony** [comment]
@Tantacrul I made a PR! - #12245

**Comment by Tantacrul** [comment]
> @Tantacrul I made a PR! - #12245

Hey, I forgot about this. Do you need it tested still?
