### ISSUE TITLE
[MU4 Issue] New Score - Templates - Search - No context on results not found

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11377]
**Describe the bug**
In the New Score - Create from template tab if you perform a search and no results are found, all items disappear and no context or indication is provided.

**To Reproduce**
1. Go to New Score
2. Select "Create from template"
3. Enter anything in to search bar that will not be found
4. Watch everything disappear without indication

**Expected behavior**
If no results are found there should be some form of indication for the user that no results are found.

**Screenshots**

https://user-images.githubusercontent.com/30370609/165255837-db9af8ef-738e-4d1f-aa02-d821f4d587d7.mov

**Platform information**
 OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2224366007
revision: github-musescore-musescore-9a7fabf

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
Ideally, there should be a message that says:

'No results found' in both the 'Template' column.

**Comment by Tantacrul** [comment]
Moving to 4.x. Will reopen when 4.0 is out.
