### ISSUE TITLE
[MU4 Issue] Synthesizers - Not all default synthesizer instruments playback

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11370]
**Describe the bug**
Not all default synthesizer instrument playback.

**To Reproduce**
1. Open attached file
2. Play
3. Notice playback does not work for multiple instruments

Instruments not playing back (worked in Musescore 3.x):

- Percussion Synthesizer
- Bowed Synthesizer
- Brass Synthesizer
- Choir Synthesizer
- Halo Synthesizer
- Metallic Synthesizer
- New Age Synthesizer
- Pad Synthesizer
- Poly Synthesizer 
- Saw Synthesizer
- Sci-fi Synthesizer
- Sine Synthesizer
- Soundtrack Synthesizer
- Square Synthesizer
- String Synthesizer
- Sweep Synthesizer
- Warm Synthesizer

**Expected behavior**

**Screenshots**
N/A

**Test File**
[test_synthesizers.mscz.zip](https://github.com/musescore/MuseScore/files/8558191/test_synthesizers.mscz.zip)

**Platform information**
OS: macOS 12.2
Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2214419458
revision: github-musescore-musescore-df96a36

**Comment by Tantacrul** [comment]
Nice work, man

**Comment by DmitryArefiev** [comment]
The same as #11232

**Comment by Tantacrul** [comment]
@RomanPudashkin - if there are any issues remaining with this, once the mapping fixes are done, perhaps chat to @bkunda and me - and we can make any decisions needed to get this issue finished.
