### ISSUE TITLE
[MU4 Issue] Palettes - Tempo - Inconsistent text sizes

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11382]
**Describe the bug**
In the Palettes - Tempo the text sizes for different items are inconsistent. Some giant, some tiny.

**To Reproduce**
1. Go to Palettes
2. Click on Tempo
3. Scroll through Palette items
4. See inconsistency of text size

**Expected behavior**
1. The below palette objects could take the following properties specifications by default, which would align their optical size with that of existing text objects (E.g. "Grave", "Largo"):
X: 0sp
Y: 0.4sp
Content scale: 1.3

- accel.
- allarg.
- rall....
- rit...
- Swing
- Straight
- calando
- lentando
- morendo
- precipitando
- smorz.
- sost...
- string.

2. Musical notes, which are currently taken from Leland Text, should be scaled at a ratio of 5:3 relative to their adjacent numerical tempo specification (See example below, where I have scaled the half-note in the first cell (marked "correct") to 26.5pt alongside the "= 80", which is set at 16pt).

**Screenshots**
CURRENT
<img width="296" alt="Screen Shot 2022-04-26 at 12 03 57 PM" src="https://user-images.githubusercontent.com/30370609/165264864-ac569cad-b5a1-4936-9b91-a450614760c5.png">

EXPECTED
<img width="500" alt="tempo-palette-revised" src="https://user-images.githubusercontent.com/86290556/165891213-f1db687f-2e03-4562-ae76-f0b5578ef2c0.png">

(N.B. For demonstration purposes, only the first cell in the above example has the correct font size ratio of musical note to numerical tempo indicator.)  

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2224366007
revision: github-musescore-musescore-9a7fabf

@HemantAntony you may want to have a look at this and #11383, as you did the most recent work on tidying-up palettes 🙂

**Comment by Tantacrul** [comment]
@bkunda - it would be good to specify some scaling improvements for these cells and then assign this task to Vasily when you're done.

**Comment by bkunda** [comment]
@lengthwave I have updated your issue description with some specifications to address the discrepancy in text object sizes.

**Comment by bkunda** [comment]
@oktophonie I have updated this issue description with information about note sizes (from Leland Text). Please advise if this needs amending. 

@vpereverzev @HemantAntony FYI

**Comment by bkunda** [comment]
This is looking good @HemantAntony. 

Could you also please fix the "Swing" and "Straight" text objects so that they appear like the other text objects? 

<img width="298" alt="Screenshot 2022-05-02 at 3 05 37 pm" src="https://user-images.githubusercontent.com/86290556/166186802-03835a79-8ffb-4ad5-88b8-6274d43160b5.png">

That should tidy this one up nicely 🙂

Also I might just tag @oktophonie in on this so he can cast a second (brutal) eye over the notehead sizes.

**Comment by HemantAntony** [comment]
> This is looking good @HemantAntony.
> 
> Could you also please fix the "Swing" and "Straight" text objects so that they appear like the other text objects?

That's weird. I did change those sizes. Was there any change at all?

**Comment by bkunda** [comment]
It may just be that they need to be set in bold (if the sizes are indeed the same). This is also how they are rendered in the score.
