### ISSUE TITLE
[MU4 Issue] Instrument - Replace Instrument - Clef changes do not occur

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11387]
**Describe the bug**
When selecting Replace Instrument from the instrument menu and replacing with an instrument that uses a different default clef, no clef change occurs.

**To Reproduce**
1. Go to Instruments
2. Click on Instrument settings
3. Click on Replace Instrument
4. Select instrument with a default clef change
5. Instrument name and playback changes
6. Clef does not change

**Expected behavior**
When an instrument is replaced with another instrument that has a different default clef, instrument clef should change.

**Screenshots**

https://user-images.githubusercontent.com/30370609/165275450-76bacba9-d9b3-4018-8c45-a68601899370.mov

**Platform information**
OS: macOS 10.16
Arch.: x86_64
MuseScore version (64-bit): 3.6.2.548020600
revision: github-musescore-musescore-3224f34

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
Confirmed. When replacing an instrument, using this panel, it should include information that gets added when you create an instrument change.

Example: 
- Create a new score and add a Horn
- Click on the second measure and drag an 'Instrument change' element from palettes, then choose to change to a cello
- Notice how a bass clef now gets added
<img width="529" alt="image" src="https://user-images.githubusercontent.com/21022311/165286262-96e6d7b6-a5b0-4945-970b-4f009e4d60b1.png">

However, when you use the instruments panel to 'Replace' an instrument (which is a master replace action, not an instrument change), the clef does not get added.

Example: 
- Create a new score and add a Horn
- Go to the instruments panel, click on the settings cog, choose 'Replace instrument' and pick a cello
- Notice that the cello is now being used but the bass clef hasn't been added

**Comment by Tantacrul** [comment]
By the way, there is another 'Replace Instrument' option in the Staff/Part properties dialog that **actually does it right**

I think we should use this logic instead.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/21022311/165289309-d7320ac4-e82c-42fc-875f-024337365bd3.png">
