### ISSUE TITLE
[MU4 Issue] Palettes - Fretboard diagrams - Element Collissions

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11380]
**Describe the bug**
In the Fretboard diagram palette there are collisions between elements displayed in fretboard diagrams in the palettes. 

**To Reproduce**
1. Go to Palettes
2. Click on Fretboard diagrams
4. See collisions in some elements

**Expected behavior**
Fretboard diagrams should be displayed in palettes as they would be on page (they are correct when placed on page).

**Screenshots**
<img width="296" alt="Screen Shot 2022-04-26 at 11 46 15 AM" src="https://user-images.githubusercontent.com/30370609/165261096-0f82dc13-0035-49d7-a942-363fa0ad3549.png">

Correct on page:
<img width="236" alt="Screen Shot 2022-04-26 at 11 48 59 AM" src="https://user-images.githubusercontent.com/30370609/165261165-8ba6d6f6-260d-4546-9fd5-a7b2812b3e09.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2224366007
revision: github-musescore-musescore-9a7fabf

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
@oktophonie - have you any idea what's going on there?

**Comment by oktophonie** [comment]
None - the workings of the palettes are a mystery to me in general!

**Comment by RobFog** [comment]
I believe @cbjeukendrup has worked on palettes in #11041 and #10608.

**Comment by DmitryArefiev** [comment]
Fixed in #11407. Now it looks the same as in **MU3**
