### ISSUE TITLE
[MU4 Issue] Palettes - Repeats & jumps - Text size / fit to window

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11383]
**Describe the bug**
In Palettes - Repeats & Jumps, the text exceeds the width of the window. The items exceeding the window are rarely used and maybe could be hidden. 

**To Reproduce**
1. Go to Palettes
2. Click on Repeats & jumps
3. Scroll through the palette items
4. See palette item width issues

**Expected behavior**
1. By default, all palette objects in "Repeats & jumps" should take the following properties specifications:
Width: 100
Height: 28
Element offset: 0sp
Scale: 0.75

2. All objects should be centrally aligned (If further specification is required for this, please let me (@bkunda) know. At present, a the "coda" and "segno" signes from `musescoreicon` are optically off-centre – see below screenshot).

**Screenshots**
EXPECTED (Showing optical centre lines for cell columns)
<img width="571" alt="Screenshot 2022-04-28 at 9 05 55 pm" src="https://user-images.githubusercontent.com/86290556/165738972-387b50ab-d0fc-4f83-90c8-78f26f740a1e.png">

CURRENT
<img width="299" alt="Screen Shot 2022-04-26 at 12 08 42 PM" src="https://user-images.githubusercontent.com/30370609/165265900-45fb6fb7-727d-4beb-bf52-d9c9faafcf44.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2224366007
revision: github-musescore-musescore-9a7fabf

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
@bkunda - same deal here :)

**Comment by bkunda** [comment]
@lengthwave I have updated the issue description with some specifications that should address this issue.

**Comment by Jojo-Schmitz** [comment]
"... Double Coda", serious? "Engtalian"? Shouldn't that rather be "...Doppia Coda" or some such?

**Comment by Tantacrul** [comment]
Engtalian (and for that matter Engerman) is an unfortunate reality today. :)

**Comment by Tantacrul** [comment]
Thanks @bkunda - I've now assigned this to the dev team.

**Comment by bkunda** [comment]
@HemantAntony if you want to have a crack at this, let us know!

**Comment by HemantAntony** [comment]
> @HemantAntony if you want to have a crack at this, let us know!

I think @cbjeukendrup already has a PR for this: #11452

**Comment by bkunda** [comment]
And so he does. I failed to see that 🤦‍♂️
I sent you another one @HemantAntony https://github.com/musescore/MuseScore/issues/11527

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
