### ISSUE TITLE
[MU4 Issue] Instrument - Replace Instrument - Transposing to non-transposing instrument

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11386]
**Describe the bug**
When using the Replace Instrument function to change a transposing instrument to non-transposing the instrument is changed, but not the transposition.

**To Reproduce**
1. Create a score with a transposing instrument
2. Select the corresponding instrument from the Instruments tab
3. Click on Settings icon
4. Click on Replace Instrument
5. Select non-transposing instrument
6. See instrument change in score (but not key signature and transposition)

**Expected behavior**
Instrument change from transposing to non-transposing instrument updates the key signature and transposition

**Screenshots**

https://user-images.githubusercontent.com/30370609/165271988-2eeadcf7-e83b-49e0-9d25-7b7e59745e80.mov

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2224366007
revision: github-musescore-musescore-9a7fabf

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
It's worth trying this in MuseScore 3 to see how it behaves. In this case, the key signature for the oboe (C major/A minor) should be used.

**Comment by DmitryArefiev** [comment]
Fixed in #11454
