### ISSUE TITLE
Multiple Glissando Playback issues

### ISSUE THREAD

**Issue by HairyPug213** [musescore/MuseScore#11395]
**Describe the bug**
(@Tantacrul) Note: I have rewritten this bug to encompass the multiple problems Glissando lines have.

Glissando has multiple problems (see video below)

- Dropdown with different variations (chromatic / black keys / diatonic, etc.) is ignored
- Adding sharps / flats often causes unusual playback problems
- Key signatures are ignored by all notes, apart from the beginning and ending note (the ones you can see)
- Key signatures can also cause really strange playback problems when other notes are included in the score

**Expected behavior**
Different playback options in the dropdowns will behave correctly.
- 'Chromatic' will result in all semitones played between the beginning and end note (see MS3)
- Black keys will only play sharps / flats
- DIatonic will be the default playback (see ms3)

In addition, when a key signature is applied, and 'DIatonic' is chosen in the dropdown, all notes played should respect the key signature. For example, if a D Major key signature is applied, then all C's and F's should be sharp, unless they have been altered within the same measure as the key signature. (See ms3)

https://user-images.githubusercontent.com/21022311/166004603-da33e001-17b3-436b-a2c4-494c74b3a48c.mov

**Comment by Tantacrul** [comment]
I've altered this issue to focus on the totality of Glissando problems that I can spot.

**Comment by HairyPug213** [comment]
Hi, Tantacrul.

I'm just putting this here as well as I am not even getting playback for my glissando

https://user-images.githubusercontent.com/80493174/166056377-f4b1c197-a6cb-4545-85b9-ee6443430b6b.mp4

**Comment by Tantacrul** [comment]
@HairyPug213 - excellent. This is all very useful to help solve the problem.

Incidentally, we agreed to tackle this particular problem when the new orchestral sampler is ready - to avoid having to do the work twice, but it's still important we log all the issues :)

**Comment by Tantacrul** [comment]
Bumping in order to help sort the priorities more clearly for beta
