### ISSUE TITLE
[MU4 Issue] Mixer clipping meter UI

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#11402]
**Describe the bug**
This is something that needs to be mentioned about the meter of the Mixer when it comes to playback.
I apologise this was not addressed in the original Mixer spec so I'm mentioning it now!
This top area of the meter should become red when an audio playback clips or exceeds +0dB. This is standard behaviour in DAWs.

Current behaviour: 
![image](https://user-images.githubusercontent.com/71656189/165336014-ceef219f-ac65-4c80-beaf-b39188bbef44.png)

Expected behaviour:
![image](https://user-images.githubusercontent.com/71656189/165330959-82fad3b8-e8ec-4dcc-bbb4-90d87f41ee29.png)

The red is in #FF1C1C 100% opacity

**Comment by cbjeukendrup** [comment]
@jessjwilliamson Is this how it should work?

https://user-images.githubusercontent.com/48658420/165363316-61ad01f8-c8db-42dd-9b76-d314bf44485a.mov

**Comment by jessjwilliamson** [comment]
Beautiful!!!

**Comment by cbjeukendrup** [comment]
Great! Added to #11369.

**Comment by boryskuzmenko** [comment]
**FIXED**
