### ISSUE TITLE
[MU4 Issue] Clear Recent Files removes all Recent Files from Windows

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#11404]
**Describe the bug**
When you press `Clear Recent Files` in `File`, instead of just removing only MuseScore files, it removes all recent files. If you don't understand, just watch the video

**To Reproduce**
1. Take a look at Quick Access (in Windows 11, maybe 10 too)
2. Go to File Menu
3. Hover on Open recent
4. Click on Clear recent files
5. Now go to Quick Access and all files are gone

**Expected behavior**
Only recent MuseScore files (preferably those shown in score tiles) should be removed

**Screenshots**

https://user-images.githubusercontent.com/88136054/165346246-add70c6c-5623-46e7-a101-826ca9f3218e.mp4

**Platform information**
 - OS: Windows 11 (Probably 10 too)

**Additional context**
I believe this is a critical bug as it can cause problems not related to MuseScore itself

**Comment by Eism** [comment]
@cbjeukendrup, it is for you

**Comment by cbjeukendrup** [comment]
Windows keeps amazing me... and it's not in a very positive way. It seems easier to break the whole OS than to perform a simple task for one app.

There is apparently no API to clear recent files for MuseScore only. So I'll altogether disable clearing the Windows recent files list. (We will still clear MuseScore's own internal list of recent files, of course.)
