### ISSUE TITLE
Add new MacOS Launch icon (MSCORE.icns)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11400]
**Task description**
I've created a version of the launch icon for MacOS icon, which looks a little different to previous versions. Specifically, I've altered the thickness of the icon and saturated the colour to help distinguish it from MS3.

<img width="201" alt="image" src="https://user-images.githubusercontent.com/21022311/165331620-2043ca6b-d8a7-42d0-a66a-43ea22e214f3.png">

If this looks good, then my next step will be to create the same for Windows & Linux (no idea how to do this for Linux. Advice would be appreciated).

LINK: https://www.dropbox.com/s/pgzngotsojsb60u/mscore.icns?dl=0

---

Note: we may alter the colours of this icon more significantly. It depends on how the overall package feels.

**Comment by boryskuzmenko** [comment]
**Tested. No Issues**
