### ISSUE TITLE
[MU4 Issue] Mouse pressing seems to be disproportionate with the place / buttons it's on

### ISSUE THREAD

**Issue by RotoBanana** [musescore/MuseScore#11406]
**Describe the bug**
Unable to use the playback button after using it once,
Mouse cannot use anything above the writing line,
Mouse pressing seems to be disproportionate with the place / buttons it's on.

**What I've done to make it happen:**
0. Open an new score, write some notes into it (I don't think that's relevant.)
1. Open an old score in **another** tab, so now you'll have multiple tabs
2. Play with the program for a bit, use the playback button
3. Try and stop or use the playback option to no avail
4. Try and use anything else to no avail

**Expected behavior**
That the mouse will press what it is on, Haha

**Screenshots**
https://imgur.com/meKPBCL (NOTE: The mouse in on the playback button.)

**Platform information**
Windows 10

**Additional context**
Bruh UI looks so pretty

**Comment by Tantacrul** [comment]
So this only happens with the play button when two scores are opened at the same time?

**Comment by cbjeukendrup** [comment]
Am I understanding correctly that this is a similar problem as in https://github.com/musescore/MuseScore/issues/8270?

**Comment by Jojo-Schmitz** [comment]
I don't see anyr relation to "[MU4 Issue] Transparent app border on Windows" ??

**Comment by cbjeukendrup** [comment]
Both issues involve that same mouse offset issue, don't they?

**Comment by Jojo-Schmitz** [comment]
Ah, I see.

**Comment by RotoBanana** [comment]
It got fixed with the beta.
