### ISSUE TITLE
[MU4 Issue] Empty Vertical frame is displayed in the headerless main score after opening a part 

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#11408]
**To Reproduce**
1. Open any score with 2 or more instruments with no header info (e.g. [Test_vertical_frame.mscz.zip](https://github.com/musescore/MuseScore/files/8566124/Test_vertical_frame.mscz.zip))
2. Open any part of the score (vertical frame with the part name displayed)
3. Pay attention to the displayed vertical frame on the main score

**Expected behavior**
Vertical frame is hidden on the headerless main score after opening any of its part

**Screenshots**

https://user-images.githubusercontent.com/101250347/165374086-9fbd235d-147f-4d0f-b8b8-3bd94ea0c339.mov

**Platform information**
 - OS: macOS, Windows, Linux

**Additional context**
Some discussion part is in this[ issue ](https://github.com/musescore/MuseScore/issues/10332)

**Comment by zacjansheski** [comment]
I just tried this and it didn't happen for me (but the score window zooms in like crazy!)
Can we close?

https://github.com/musescore/MuseScore/assets/69917893/9c5165a1-eb5e-4947-8d60-cfc0c687b527
