### ISSUE TITLE
[MU4 Issue] Too easy to select measures or click wrong element

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#11410]
## Description

When trying to click on a note in the score, it is too easy to miss the note and click on the measure behind it instead.

## Recommended solution / Expected behaviour

Set the default "selection proximity" value (found in Preferences > Canvas) to 5px.

### Report from an accessibility tester:

> It is taking a lot of getting used to, selecting a single note vs the entire measure. I probably select the measure 3 or 4 times for every time I try to select a note. My mouse cursor must be touching just outside of a note I want to select. This feature, selecting the entire measure might be better off with a mouse modifier like Alt/Option
>
> MacOS Monterey 12.3.1 16GM RAM Apple M1
> Using Zoom (system magnification tool, not video conferencing software)

I think it is mainly a problem on macOS, though other platforms may be affected to a lesser extent.

### macOS cursor problem

On macOS the cursor/pointer has border and the cursor's "hotspot" is on the inside of this border rather than the outside, which I find to be rather unintuitive. This means you are not quite clicking where you think you are.

<img width="300" alt="macOS cursor hotspot placement" src="https://user-images.githubusercontent.com/11011881/165360668-3f72715f-ba58-4ba0-b402-81a97a4e8928.svg">

This video shows how it can lead to problems selecting objects in the score. **(Video has sound!)**

https://user-images.githubusercontent.com/11011881/165380364-c2598e02-ef76-4ee1-83f7-8e83162f1803.mp4

**Comment by RobFog** [comment]
If the cursor behaves the same in Calculator (and likely elsewhere), I'm not convinced we should deviate from that.

**Comment by shoogle** [comment]
@RobFog, I agree to an extent. When there are two similarly sized objects next to each other then I agree that we should follow the macOS convention. So we should consider this a click on the 5 button and not on the 8:

![image](https://user-images.githubusercontent.com/11011881/165390148-b8c756e0-a7dc-4808-900b-e0f56dbc0494.png)

But when there is a very small object in front of a very large object (or in front of an empty background), then I think it is safe to assume that this is a click on the object and not on the background:

![image](https://user-images.githubusercontent.com/11011881/165389692-23ae0460-fe2f-406e-ba9f-bdbead8eb008.png)

I'm just suggesting that we should make the click region a bit bigger for small objects. I certainly don't think we should add an artificial offset to the cursor position in MuseScore just to make up for my gripe with cursors on macOS!

**Comment by cbjeukendrup** [comment]
In MuseScore 3, we indeed had a thing called 'selection proximity' (Preferences > Canvas), which has a default value of 6px, allowing you to click a few pixels next to the element to select it. In MuseScore 4, we also have that, but the default value is only 2px, and I'm not 100% sure if it is working. But its purpose is exactly to make the clickable area slightly bigger to make it easier to select (small) elements. So I think it would be good to investigate to what extent it is working or needs fixing in MU4.

**Comment by shoogle** [comment]
@cbjeukendrup, thanks for pointing that out! If you set the selection proximity to something stupidly high (e.g. 10px) you'll see it is definitely working in MuseScore 4, at least for noteheads and a few other elements. I find setting it to 5px removes the macOS offset, though 6px might be better for a bit more leniency.

However, I find that the clicks can be a bit inconsistent right on the borderline between two objects. You can see this in the video where the click at 0:26 selects the measure but the click at 0:40 selects the note even though the cursor has returned to the _exact same position as before_, then at 0:45 it's the measure again. Maybe it gives priority to the object already selected? No, the clicks at 1:01, 1:04 and 1:07 are in the same position and they always select the measure, even when the note was previously selected, so there is no clear pattern to what happens on the borderline.

**Comment by bkunda** [comment]
fwiw, my view on this is that if 6px as the default click area is already established and familiar to users of MS3 (and assuming nobody has complained too much about this so far), then we should reinstate that for MS4. 

The borderline issue does seem glitchy (inasmuch as it is apparently unpredictable). I don't have any inspired ideas on how to solve this though.

**Comment by MarcSabatella** [comment]
There is a setting in Edit / Preferences / Canvas to control the proximity.  In MU3, the default value was 6px.  In MU4 it seems to only be 2px.  Maybe all we need to do is restore the former default?

**Comment by MarcSabatella** [comment]
(posted first before realizing the change from 6px to 2px was already mentioned)

One other thing to notice is that for most elements, it seems we use the rectangular "bounding box" as the click area - so you click well above or below the narrow end of a hairpin and still select it.  Other objects like slurs are treated more intelligently in terms of what is considered their shape.

**Comment by Tantacrul** [comment]
@shoogle - we should assign this to someone. Are you, @MarcSabatella and @bkunda happy enough you know what should be done? If so, then I'd update the task and assign to V-man.

**Comment by bkunda** [comment]
If I've comprehended it correctly that the simplest fix at the moment is simply changing the default click area to 6px, then yes, this should be an easy fix.

I'm happy to update the issue description, unless @shoogle or @MarcSabatella indicates there is something I've missed.

**Comment by MarcSabatella** [comment]
As far as I know that's all that should be needed.  My comment about different types of shapes was just meant as a "heads up" if you notice what seems to be inconsistencies in testing.  The point being, these are normal and not related.  Someday it would be great to have smarter shape calculations for hairpins and other symbols - this would help the layout calculations as well.  But that is a separate issue.

**Comment by bkunda** [comment]
@shoogle @MarcSabatella I have just updated this issue description with our proposed solution.

**Comment by DmitryArefiev** [comment]
@Tantacrul @bkunda @cbjeukendrup Hi, I asked to change proximity setting to **2px** in #9768 (but without explanation) because with **6px** it was hard to select measures when they small (usually they small in big scores).
With 5px it's still little bit hard to edit orchestral scores with mouse especially when you want to see the whole page. You can try on your side with big scores.
 
I made a video with explanation:

https://user-images.githubusercontent.com/90187801/168839088-976e9216-6a05-427a-af17-7ecff507efae.mov

I have some complains about the fix (to change default to 5px)

1. That's the Mac only issue (as a compromise it's not necessary to change default value on Windows and Linux)
2. The user (reporter) has a big mouse cursor and **it's not a common case** (as I understand)
3. The user (reporter) can change proximity settings on his side. If there will be a lot of reports in future with that problem we can change the default value then (if we don't have another fix).

**Comment by Tantacrul** [comment]
@DmitryArefiev if you recommend we leave things as they are and close the issue, then I think we should do that.

Definitely agree that a MacOS issue should not impact Win+Linux

**Comment by Tantacrul** [comment]
@shoogle ?

**Comment by sammik** [comment]
I was transcribing some score today (bigger work at MS4 for the first time) and was surprised, that I accidentaly select measure instead of note too many times. In Linux. And now I see this discussion. So may be 2px is too litle globaly.

**Comment by MarcSabatella** [comment]
My personal feeling on Linux and sometimes Windows is that 2 px is too small, 6 px too big.  I'm not sure if optimal would be 3, 4, or 5, but if we went with 4,we'd only be off by 1 at most :-)

**Comment by Tantacrul** [comment]
So, I think the way to really solve this is to detect where there is actually complaints about how it works now. I must admit that I never noticed the change - ever. On either Mac or PC.

I don't support returning to the MS3 values unless there's a real need to do so. This is something that (if it is a big problem) will become known when we get into Beta 1 or Beta 2 (when much more people will be testing).

Since it is so simple to change, we can really do it at any time. I suggest closing this for now. Then waiting to see if a larger issue emerges.

**Comment by MarcSabatella** [comment]
FWIW, I also can't say I noticed a difference so far, until I started playing with pedal lines a lot today.  2 px makes it really hard to select them.  4 px is working better for me.
