### ISSUE TITLE
[MU4 Issue] Help Menu - Ordering

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11415]
**Describe the bug**
It seems the help menu order does not match user priority/potential frequency.

**To Reproduce**
1. Go to Help menu
2. Click on Help
4. See dropdown

**Expected behavior**
Ordering should be according to what we want to highlight to the user.

Recommended ordering:

----
Check for updates
----
Online handbook
----
Ask for help
Report a bug
Feedback
----
About MusicXML ...
About QT ... (<-- suggest to move from MuseScore menu)
----
Revert to factory settings
----

**Screenshots**

<img width="480" alt="Screen Shot 2022-04-27 at 1 10 19 PM" src="https://user-images.githubusercontent.com/30370609/165495670-ea2fba47-e61e-4ddf-93d5-3ecf5430d2ba.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
Agreed. This should be a v.simple community issue. Nice spot!
