### ISSUE TITLE
[MU4 Issue] Status Bar - Zoom - Enter numerical values

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11414]
**Describe the bug**
Entering numerical values for zoom in status bar does not display same numerical values entered.

**To Reproduce**
1. Go to Status Bar
2. Double click on zoom % in bottom right
3. % value becomes highlighted and curson blinks
4. Type new numerical value
5. See error

**Expected behavior**
Numerical value displayed corresponds to numerical value entered.

**Screenshots**

https://user-images.githubusercontent.com/30370609/165495134-aa0ac3c5-b774-4a1f-b4a6-98416d9466dd.mov

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Salavin** [comment]
I would like to work on this issue; it seems like it's an issue of the background color of the `NumberInputField` being deceivingly set to `ui.theme.accentColor`, which makes it seem like the text is being selected when it, in fact, is not.

**Comment by Tantacrul** [comment]
Cool. Let me know when you want one of us to test it for you.

Either myself, @bkunda or @DmitryArefiev will take a look.

**Comment by Salavin** [comment]
Should be all good to go!

**Comment by DmitryArefiev** [comment]
Retested on Mac12
