### ISSUE TITLE
VSTs are loading on every startup. No blacklisting / whitelisting, causing crashes and extremely slow loading times

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#11412]
**Describe the bug**
MuseScore attempts to load all VSTs at startup, which leads to slow startup times and occasional activation dialogs appearing. Other programs scan for VSTs at startup but only load the ones that are actually used in the current project.

Report from an accessibility tester (though not related to accessibility):

> MuseScore 4 [alpha version] scans and apparently attempts to load(?) all of my VSTs - normally not a problem. But I have several VSTs that require iLok activation. I've actually moved those to another computer and neglected to delete them on this one as I might move back and forth. With that background, MuseScore appears to be attempting to load those VSTs - as a result I get a handful of activation popups. My DAW does not behave in this manner. It does not load the VST unless and until it is actually used in a project, making startup much much faster.
>
> MacOS Monterey 12.3.1 16GM RAM Apple M1

**Comment by jessjwilliamson** [comment]
> **Describe the bug** MuseScore attempts to load all VSTs at startup, which leads to slow startup times and occasional activation dialogs appearing. Other programs scan for VSTs at startup but only load the ones that are actually used in the current project.
> 
> Report from an accessibility tester (though not related to accessibility):
> 
> > MuseScore 4 [alpha version] scans and apparently attempts to load(?) all of my VSTs - normally not a problem. But I have several VSTs that require iLok activation. I've actually moved those to another computer and neglected to delete them on this one as I might move back and forth. With that background, MuseScore appears to be attempting to load those VSTs - as a result I get a handful of activation popups. My DAW does not behave in this manner. It does not load the VST unless and until it is actually used in a project, making startup much much faster.
> > MacOS Monterey 12.3.1 16GM RAM Apple M1

Completely agree!

**Comment by Tantacrul** [comment]
I think it is scanning VST's, right? This really should only happen the first time MuseScore boots. At that point, it would then have some kind of record of which VSTs are available.

@vpereverzev - does it scan for VST's each time it opens or just the first time?

**Comment by Tantacrul** [comment]
Adding a P1, just so the issue is addressed. We can reprioritise if we think it's the right move.

**Comment by Tantacrul** [comment]
This is an issue David Hearn also highlighted to me. He says his main computer is unable to open MuseScore and he suspects this is the reason. We probably need some kind of initial black listing / white listing phase - and as Jess suggested, the loading screen can flash up some text to explain to the user this is what is happening the first time they load the app.

**Comment by jessjwilliamson** [comment]
> This is an issue David Hearn also highlighted to me. He says his main computer is unable to open MuseScore and he suspects this is the reason. We probably need some kind of initial black listing / white listing phase - and as Jess suggested, the loading screen can flash up some text to explain to the user this is what is happening the first time they load the app.
> 
> @vpereverzev On Audacity, we keep record of which effects were automatically disabled because we couldn't load them. Perhaps we can do this by default for now and then create an interface for the process in future releases?

Which reminds me.. maybe we could start thinking about making a VST/plugin manager for MS4?

**Comment by Tantacrul** [comment]
Whoever works on this: I can be a point of contact for functionality. Ideally, we just want some background process for MS4. However, if we feel we need an interface, I can provide something.

I also want to mention that this loading screen: https://github.com/musescore/MuseScore/issues/11330, is where we should describe the VST's being scanned when the app opens.
