### ISSUE TITLE
Remove option for 'Single Note Dynamics' in the Staff/Part Properties dialog

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11417]
**Describe the bug**
This option (at the bottom left corner of the dialog) no longer functions, since we have replaced the entire engine and how it works. It was always a pointless option to expose to the user anyway. Good riddance!

<img width="753" alt="image" src="https://user-images.githubusercontent.com/21022311/165509829-7b8bfbab-7951-420a-b0bd-4f74f475da77.png">

**Comment by quinnouyang** [comment]
On a tangent, I assume we should exile it from the hairpin playback popup too?
<img width="283" alt="image" src="https://user-images.githubusercontent.com/90884224/166156456-77ac6ecb-db88-4eba-9255-07e486413484.png">

**Comment by Tantacrul** [comment]
> On a tangent, I assume we should exile it from the hairpin playback popup too? 

Yes! Thanks for spotting that.
