### ISSUE TITLE
[MU4 Issue] Project Properties - File path should not be modifiable 

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11429]
**Describe the bug**
In Project Properties the file path window is visually represented as being modifiable and includes the file browser icon, but this is not user modifiable information.

**To Reproduce**
1. Go to File > Project Properties
2. Click on folder icon under file path
4. Huh?

**Expected behavior**
File path should be displayed as static and unmodifiable.

**Screenshots**
<img width="847" alt="Screen Shot 2022-04-27 at 3 52 40 PM" src="https://user-images.githubusercontent.com/30370609/165522718-fff5ef37-db0c-49f7-9528-f4068129c2c4.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by HemantAntony** [comment]
Did you mean that you though the folder icon was for changing the folder? Its for opening the project's folder

**Comment by Tantacrul** [comment]
No, he means the user should not be able to edit the file path itself because that would be impossible!

**Comment by Tantacrul** [comment]
So, it should not be an editable text box. Just text.
