### ISSUE TITLE
A default location should be chosen for sound fonts in Preferences

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11426]
**Describe the bug**
At the moment, the locations for soundfonts needs to be specified by the user. I would suggest using the same default locations used by MuseScore 3.

For example, on mac, that would be: /Users/**username**/Documents/MuseScore/SoundFonts

That way, users familiar with installing soundfonts will know what to do.

**Comment by quinnouyang** [comment]
I'm unsure how we configured the folders for development, but the `SoundFonts` folder doesn't even exist (nor do some others: VST3, Images, etc.):
<img width="441" alt="image" src="https://user-images.githubusercontent.com/90884224/166155996-47675795-2e0f-4fad-9903-092c8575e002.png">

Should we add one?

**Comment by Tantacrul** [comment]
Unless someone thinks it is a very stupid idea, then I'd suggest adding the same default folder, in the same location, that was true for MuseScore 3.

**Comment by cbjeukendrup** [comment]
@Tantacrul Yes I think that's a good idea. 

@quinnouyang it would be good if those default folders would be created during the first launch. This was also the case in MU3.

**Comment by DmitryArefiev** [comment]
Fixed in #11520
