### ISSUE TITLE
[MU4 Issue] Playback - Some instruments not playing back

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11424]
**Describe the bug**
Some instruments do not playback, but start to playback when you click on a note within the staff that is not playing back (while playback is in process).

**To Reproduce**
1. Open attached score
2. Play
3. Notice playback Jank (brass don't playback in attached score)
4. Click on a note in any staff not playing back
5. Scratch your head and wonder

**Test file**
[Fanfare_for_the_Common_Man.mscz.zip](https://github.com/musescore/MuseScore/files/8571869/Fanfare_for_the_Common_Man.mscz.zip)

**Expected behavior**
Everything playsback.

**Screenshots**
N/A

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
Yes. Confirmed. I noticed this regression yesterday.

**Comment by DmitryArefiev** [comment]
Fixed in #11709
