### ISSUE TITLE
[MU4 Issue] Project Properties - MuseScore version number

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11427]
**Describe the bug**
MuseScore Version number in Project Properties is non-editable, but displayed in same way as editable text boxes, leading to potential user confusion.

**To Reproduce**
1. Open File > Project Properties
2. Click on Work title text box
3. Text is highlighted and becomes editable
4. Click on identical looking MuseScore Version text box
5. Wonder why nothing happens :-)

**Expected behavior**
Version number should be clearly shown as non-editable, plain text may be better (maybe above file path?).

**Screenshots**
<img width="853" alt="Screen Shot 2022-04-27 at 3 33 14 PM" src="https://user-images.githubusercontent.com/30370609/165518822-1a7fc707-a966-4ef4-8dee-0f3e8342e4e3.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by RobFog** [comment]
Maybe one for @HemantAntony who did #10630?

**Comment by HemantAntony** [comment]
> Maybe one for @HemantAntony who did #10630?

I am okay with working on this. But I wanted to know what the fix should be. Should it be a text label replacing the text fields (in the top panel) to show that it is not editable? @Tantacrul

**Comment by Tantacrul** [comment]
@HemantAntony - Yes, exactly. Basically just the text by itself.

**Comment by HemantAntony** [comment]
@Tantacrul It doesn't look as good
![image](https://user-images.githubusercontent.com/88136054/166093996-b15aac05-9c2b-447f-8f05-d66bb1fa7ddd.png)
I can of course play around with the spacing. I didn't change it yet

**Comment by lengthwave** [comment]
Since this information is not editable by the user and is only for user reference, maybe this should go at the bottom and a window title at the top?

**Comment by Tantacrul** [comment]
@HemantAntony two things:

As Dan said, move it to the bottom and set the text of the file path itself to 70% transparency

**Comment by Tantacrul** [comment]
Actually - move the row under the file path to the bottom too (version, etc.)

**Comment by Tantacrul** [comment]
Apart from that it looks fine
