### ISSUE TITLE
[MU4 Task] Minor tweaks to Parts dialog

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11420]
**Task description**
This task proposes some UX fixes to the current Parts dialog. Worth noting is that this is **not** going to be our optimal _eventual_ solution; instead, I've tried to keep this fix as lightweight as possible, with the aim of resolving some recently identified usability problems ahead of the MS4, release while keeping any risk of further bugs and testing requirements as low as possible. 

Please see the Figma design file here: https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/Musescore-Notation-App-MASTER?node-id=23228%3A573668

In sum:

1. Changes made within the Parts dialog should be persistent when the dialog is closed and re-opened
2. The `Open` button should be replaced with two buttons: `Open selected` and `Open all`
3. Behaviour and ordering of context menu items is given additional specification
4. The `Close` button should be moved to the bottom-left corner of the dialog. 

<img width="634" alt="parts-dialog-new" src="https://user-images.githubusercontent.com/86290556/165508932-66b48606-09be-4f36-a0c0-3571c593218d.png">

**Additional context**
Partly resolves #11359 

**FYI**
@Tantacrul @lengthwave @MarcSabatella @jessjwilliamson @cbjeukendrup @RomanPudashkin

**Comment by Tantacrul** [comment]
For anyone interested, I created a little twitter poll about this to make sure the UX was clear. It has done pretty well.

https://twitter.com/Tantacrul/status/1519250774932574208

**Comment by DmitryArefiev** [comment]
@bkunda @Tantacrul I think it also would be nice to have an option to close all parts at once. Especially when you have a big score.

Or to add to the Parts dialog the ability not only to open all/selected parts **but also to close all/selected parts**.  

Just thoughts..

**Comment by wizofaus** [comment]
Figma link doesn't work? @bkunda

**Comment by DmitryArefiev** [comment]
Implemented in #11858
