### ISSUE TITLE
[MU4 Issue] Multiple Instances - Closing two instances of same score divides by zero

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11428]
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**
1. Open MuseScore
2. Open any score in MuseScore
3. Open any other score in MuseScore without closing current
4. On Mac, see a new instance of MuseScore open
5. Open same score as open in other instance
6. Close one instance
7. Witness the visual representation of dividing by zero

**Expected behavior**
Should not have ability to have 2 complete instances open at same time.
Should not have ability to have 2 instances opening the same score at the same time.

**Screenshots**
<img width="1917" alt="Screen Shot 2022-04-27 at 3 44 15 PM" src="https://user-images.githubusercontent.com/30370609/165520878-8c2bacaa-572c-4187-944c-ce4dc194ba81.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

**Comment by lengthwave** [comment]
@Tantacrul - FYI/WTF :-)

**Comment by Tantacrul** [comment]
It is no longer possible to open the same score twice in one session. As for the other bug (seeing two completely different instances), this has been logged elsewhere, so I'll close this issue.
