### ISSUE TITLE
[MU4 Issue] Help > MusicXML > Remove Menu Item

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11437]
**Describe the bug**
MusicXML menu item and corresponding pop up window is not required and should be removed in order to streamline UI.

**To Reproduce**
1. Go to Help > About MusicXML
2. See issue

**Expected behavior**
No pop up window should appear and menu item should not be present. 

**Screenshots**
<img width="590" alt="Screen Shot 2022-04-27 at 8 04 21 PM" src="https://user-images.githubusercontent.com/30370609/165581118-d05483c8-70eb-4b74-999a-e79aba05d3be.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

**Comment by lengthwave** [comment]
@Tantacrul - FYI

Maybe version number should also be indicated in export window?

<img width="942" alt="Screen Shot 2022-04-27 at 8 37 52 PM" src="https://user-images.githubusercontent.com/30370609/165586408-9d3d59cd-1ff4-45e9-af86-19f92c519e93.png">
t

**Comment by Jojo-Schmitz** [comment]
It is "MusicXML 4.0" meanwhile, and I guess the copyright years need to get uüpdated too? The hyperlinks indicate 2022

**Comment by lengthwave** [comment]
I cannot find any requirement to display this statement in any of the MusicXML developer documentation:

https://www.w3.org/2021/06/musicxml40/

Since there is no clear requirement, I think this statement within the source code comments would be sufficient and that we should just remove the "About MusicXML" menu option and window entirely.

@Tantacrul thoughts?

**Comment by Tantacrul** [comment]
No objection

**Comment by lengthwave** [comment]
@Tantacrul - I have updated the issue to remove the menu item and popup. 

I will create another issue with the MusicXML version number to be displayed in Export settings.

**Comment by shoogle** [comment]
Hold on guys... it's actually a requirement to attribute the MusicXML specification. It's something we signed up to when joining W3C. I think it would probably be best to keep the About MusicXML dialog, with a link to the full specification, specification agreement, and MusicXML version number.

As for the Export dialog, I don't think we should show a version number there. Or if we do, we should clarify that we don't support **all** features of the MusicXML 4.0 specification. In reality, MusicXML 4.0 is simply the most recent version of the specification for which we support **any** new features that were not available prior to that version.

**Comment by Tantacrul** [comment]
Hmm. In that case, I think we should close this and focus our attention on more pressing issues.
