### ISSUE TITLE
[MU4 Issue] - Request - Tuplets Ratio + Note

### ISSUE THREAD

**Issue by charlesneimog** [musescore/MuseScore#11435]
**Describe the bug**

Sorry is this is not the right place request it.

**But I'd to ask if could be possible implement the possibily to show the note besides the ratio like in Sibelius.**

* Musescore
![image](https://user-images.githubusercontent.com/31707161/165551412-39b3f269-2deb-45cb-82b5-5a16bd2c621c.png)

* Sibelius
![image](https://user-images.githubusercontent.com/31707161/165551806-6c57c127-392a-4e4a-8863-6c9a91b9b008.png)

**Expected behavior**
Add the option `Ratio + Note` inside the red block.

![image](https://user-images.githubusercontent.com/31707161/165552601-c2d31d58-65ac-4934-93e0-c7caa541d640.png)

**Screenshots**

**Platform information**
 - OS: Windows

**Additional context**
Just congrats for all the work with Musescore 4!

**Comment by Tantacrul** [comment]
@oktophonie - I'll let you comment on this request with recommendations.

I've added the request to our internal list. Closing the comment.

**Comment by charlesneimog** [comment]
Thanks!
