### ISSUE TITLE
[MU4 Issue] Preferences > General > Languages - Current language not displayed

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11430]
**Describe the bug**
Selected language is blank. It is populated only once you make a change.

**To Reproduce**
1. Go to Preferences > General > Languages
2. See the blank dropdown

**Expected behavior**
Current language should be displayed.

**Screenshots**
<img width="1154" alt="Screen Shot 2022-04-27 at 3 58 18 PM" src="https://user-images.githubusercontent.com/30370609/165524167-c74f28b2-03c8-4897-8ea4-0f60e2b538f3.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by DmitryArefiev** [comment]
Fixed in #12474
