### ISSUE TITLE
[MU4 Issue] Export > MusicXML - Remove outdated format

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11439]
**Describe the bug**

Export options for MusicXML still shows .xml option, which is very outdated (no other current software uses).

**To Reproduce**
1. Go to File > Export
2. Select MusicXML from Format dropdown
3. Click on File Type dropdown
4. See Uncompressed (outdated) (.xml)

**Expected behavior**
Only uncompressed option should be .musicxml as .xml option does not really much value and just creates confusion with less technical users. 

We lose nothing by removing it and improves user experience (reduces potential confusion).

**Screenshots**
<img width="940" alt="Screen Shot 2022-04-27 at 8 42 50 PM" src="https://user-images.githubusercontent.com/30370609/165588153-8630c9a6-7755-4bfd-848a-7333c5bd46a4.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
Assuming there are no objections, let's remove it.

**Comment by Jojo-Schmitz** [comment]
It took a loooong to time to get it added back, there are still programs out there that don't accept .musicxml but insist on .xml, and forcing users to drill down into the OS and rename a file extension, esp. on Windows, is a very very **very** bad idea.

**Comment by Tantacrul** [comment]
If there are legitimately apps that require this, then no harm leaving it there.

**Comment by lengthwave** [comment]
@Jojo-Schmitz not one other **current** software supports this very outdated format and neither does the sponsor of the MusicXML working group.

Programs that do not support .muisicxml do support .mxl and regardless, the user can just edit the file extension.

We should not confuse 12 million users for the convenience of probably less than 100 users.

**Comment by Jojo-Schmitz** [comment]
OK,so  you talk every inexperienced Windows user though on how to rename an extension. Deal?

.xml file still come up time and time again in the musescore.org forums, so there got to be programs out there working with them.

**Comment by lengthwave** [comment]
@Jojo-Schmitz if they don't know how to rename a file extension, this is not the type of user that should be dealing with legacy import functions. 

It can easily be solved by renaming the file. 

If we keep every possible legacy file format option for micro user cases the software will be bloated jank.

Backwards compatibility should have some limitations and this extension was discontinued more than 5 years ago and no other current software supports it.

**Comment by Jojo-Schmitz** [comment]
Do we have the deal I proposed? If not, leave that format in.

Renaming a file, esp. an extension and esp. on Windows is not easy at all. Most Windows users don't even see the file extension, as Microsoft in there unlimited wisdom hides them by default!

**Comment by lengthwave** [comment]
@Jojo-Schmitz after reviewing the .xml issues in the forums, the majority of user issues are due to confusion of not knowing the difference.

The number of user that actually need this feature is extremely small, yet having this option in confuses users (as can be seen from browsing the forums). 

The other reason for not supporting this (and the reason why it was discontinued) is that .xml is too generic and when users download these to their computers they are not recognized specifically as MusicXML files and so no default app is assigned.

The end goal should be to make the experience as easy as possible for the widest number of users. XML vs. MusicXML/MXL extension introduces more user confusion (and system confusion) than the micro-segment of users this needing this legacy format.

**Comment by Jojo-Schmitz** [comment]
So again: do we have a deal? You support that, every single time is comes up in the forums?

**Comment by Tantacrul** [comment]
Closing this issue for now due to needing to focus our attention on more important things. If we think there's some legit reason to keep this, let's do so. Hurts no one to keep it. Perhaps later, we can discuss removing it.

**Comment by shoogle** [comment]
Here's what the export dialog looks like for MIDI. Notice the text at the bottom to clarify details about the export.

![image](https://user-images.githubusercontent.com/11011881/165621368-8a6e0fa5-1e98-44a3-b5f3-5f5f27cb2af5.png)

We could add text like this for `.xml`:

> The .xml extension is no longer used for MusicXML files. Please use the newer .musicxml file extension instead if your software supports it.

**Comment by Jojo-Schmitz** [comment]
Yes, I'm not against this at all, if/as "(outdated)" isn't discouraging enough already...
Even make it fat and red, all fine by me
