### ISSUE TITLE
[MU4 Issue] MU hangs after deleting the top instruments in score

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11442]
**Describe the bug**
MU freezes after deleting the top instruments in score

**To Reproduce**
1. Open a score
2. Open Instrument window
3. Delete the top instrument and click OK

https://user-images.githubusercontent.com/90187801/165719127-93659af6-4eac-4c57-b93b-ed04fb85d31d.mp4

**Platform information**
 macOS, Windows, Linux

**Comment by igorkorsukov** [comment]
Fixed by https://github.com/musescore/MuseScore/pull/11443
