### ISSUE TITLE
[MU4 Issue] Piano Keyboard - Add shortcut

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11441]
**Describe the bug**
Despite being a potentially common toggled feature, there is no shortcut to View/Hide onscreen piano keyboard.

**To Reproduce**

**Expected behavior**

Onscreen piano keyboard should have a shortcut ( _Breve Advance (F.B./Chord Symbol)_ has a shortcut and I don't have a clue what that could possibly even be. :-) )

Let's show the piano keyboard some love and give it a shortcut!

How about F5? (easy to remember because you have 5 fingers)

**Screenshots**
<img width="576" alt="Screen Shot 2022-04-27 at 9 13 10 PM" src="https://user-images.githubusercontent.com/30370609/165592285-85c30aec-d054-4305-a7c6-70c13e644230.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

**Comment by lengthwave** [comment]
@Tantacrul - FYI

**Comment by Tantacrul** [comment]
One problem we have (and Audacity too) is that people keep relying on F numbers, which aren't on some laptop keyboard and (for Mac) are often hijacked to provide macOS specific functions. For primary UI elements, we should use primary characters and not F numbers.

I don't have a suggestion here. The only real solution is to create a proper keyboard shortcuts system, which we will do in later versions. Then we need to revise the shortcuts too.

**Comment by Jojo-Schmitz** [comment]
In MuseScore 3 "P" was the shortcut for this. I see no reason for MuseScore 4 to not use that too

**Comment by Tantacrul** [comment]
Agreed.
