### ISSUE TITLE
Text Box Regression. Users cannot select text with a mouse anymore.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11445]
**Describe the bug**
There has been a regression with all text boxes.

1. Users cannot place an insertion point in the text itself
2. Users cannot select a range of text
3. Users cannot deselect the full text (unless they press left or right with the arrow key)

For example, when trying to save a score to the cloud or renaming an instrument the user cannot click at in the middle (or at the end) of the text to deselect everything and insert additional text. 

<img width="337" alt="image" src="https://user-images.githubusercontent.com/21022311/165735930-73076d25-8f3b-4464-b548-525671787fae.png">

<img width="307" alt="image" src="https://user-images.githubusercontent.com/21022311/165736323-f413a0bf-4eeb-4d7c-95cc-c3c1e96079bc.png">

**Comment by Eism** [comment]
@Tantacrul 
Fixed in this PR https://github.com/musescore/MuseScore/pull/11447

**Comment by Tantacrul** [comment]
Have tested the PR. Seems to be working as expected!
