### ISSUE TITLE
[MU4 Issue] Chords are not played during Left/Right navigation

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#11451]
**Describe the bug**
In MuseScore 4, only the top note of chords is played when you navigate through the score with the Left and Right arrow keys. In MuseScore 3 all notes were played. This is important for blind users because otherwise they will not know that the selected note belongs to a chord.

**Additional context**
When navigating with Alt+Right and Alt+Left, it is correct for only one note at a time to be played. This is because those shortcuts give access to all notes in the chord whereas Left and Right alone only give access to the top note.

### Example 1: Navigation with Right/Left arrow key _alone_
**UiActions: `play-next-chord`/`play-prev-chord`**

1. The note before a chord is selected.
  ![image](https://user-images.githubusercontent.com/11011881/165780916-b2eab74c-5674-4988-9dbf-e89f97fb618a.png)

2. Press the Right arrow key. The top note of the chord is selected and **you should hear a sound**.
  ![image](https://user-images.githubusercontent.com/11011881/165781448-982ff9ef-c433-474f-b2f4-7c53a4f757ae.png)
**Expected behavior:** You should hear all three notes in the chord, even though only the top note is actually selected.
**Actual behavior:** You only hear the top note. **WRONG!**

3. Press the Right arrow key again. The rest after the chord is selected (and you should hear nothing).
  ![image](https://user-images.githubusercontent.com/11011881/165787104-b798c387-2dd7-48ec-9a3c-5453b02db59f.png)

### Example 2: Navigation with Left/Right arrow keys _with Alt modifier_
**UiActions: `next-element`/`prev-element`**

1. The note before a chord is selected.
  ![image](https://user-images.githubusercontent.com/11011881/165780916-b2eab74c-5674-4988-9dbf-e89f97fb618a.png)

2. Press Alt+Right arrow. The top note of the chord is selected and **you should hear a sound**.
  ![image](https://user-images.githubusercontent.com/11011881/165781448-982ff9ef-c433-474f-b2f4-7c53a4f757ae.png)
**Expected behavior:** This time you should only hear the top note.
**Actual behavior:** You only hear the top note. **CORRECT!**

3. Press Alt+Right arrow again. This time the middle note of the chord is selected (and you only hear the middle note).
  ![image](https://user-images.githubusercontent.com/11011881/165791172-dafb0d26-287c-4bf3-af95-17fd215c6f7c.png)

**Please fix Example 1 without breaking Example 2. Thanks!**

---

**Related edit (Martin)**
When in Note Input mode on a **Tablature stave**, pressing **up** or **down** to jump between notes in a chord - you will hear one note in the chord being played each time. The result should behave in the same way as MuseScore 3: no sound should be heard in this specific instance.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/21022311/172210567-79cfc738-deb1-4f00-a7d7-e31d9c5f4e0c.png">

**Platform information**
 - OS: Windows

**Comment by Tantacrul** [comment]
This is a very important bug to fix, so I have assigned it to Alpha 2.

**Comment by DmitryArefiev** [comment]
Fixed in #11965
