### ISSUE TITLE
[MU4 Issue] Master Palettes - UI Issues

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11457]
**Describe the bug**
Master Palettes window UI is not consistent with other pop up windows or main Palettes (it feels unfinished).

See padding issues, borders on selected category, etc.

See button placement, color (cancel/clear is bright vs. action).

See font style and colors.

**To Reproduce**
1. Go to 'View > Master Palettes'
2. See issue

**Expected behavior**
UI should be more consistent with other pop up windows and main Palettes UI.

**Screenshots**
<img width="1040" alt="Screen Shot 2022-04-29 at 12 24 33 PM" src="https://user-images.githubusercontent.com/30370609/165918677-9a9ca9ee-e7dc-4207-85df-a8a018bbccfc.png">

<img width="1064" alt="Screen Shot 2022-04-29 at 12 28 07 PM" src="https://user-images.githubusercontent.com/30370609/165919206-ab5f4b7d-7d09-48f7-83d0-f9cd79d2f9c7.png">

Compared to

<img width="1212" alt="Screen Shot 2022-04-29 at 12 12 05 PM" src="https://user-images.githubusercontent.com/30370609/165918734-9a9f19ce-dbfa-4419-8e83-8e343795ef47.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2243301402
revision: github-musescore-musescore-a6ab311

**Comment by Tantacrul** [comment]
Yeah. This is a port from MS3. We're eventually going to simplify and replace it. Unfortunately not in scope for MS4.
