### ISSUE TITLE
[MU4 Issue] Preferences > General > Languages - Check for Update button

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11456]
**Describe the bug**
The check for update button in Preferences > Language is a bit confusing.

The placement of the button suggests that the action is connected to submitting the language selection.

**To Reproduce**
1. Go to Preferences > General > Languages
2. Select language from dropdown
3.Click 'Check for updates'
4. See issue

**Expected behavior**
As the check for updates function is logically separate from the language selection action, it could be clearer if there is more visual distinction.

Maybe this can be moved to the Updates section of Preferences?

**Screenshots**
<img width="1212" alt="Screen Shot 2022-04-29 at 12 12 05 PM" src="https://user-images.githubusercontent.com/30370609/165916867-12540a61-2445-49a9-aec3-edb7a27811e2.png">

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2243301402
revision: github-musescore-musescore-a6ab311

**Comment by Tantacrul** [comment]
This update button is only for languages - hence why it is next to the languages dropdown. I suggest a simple rewording to 

**Check for language updates**

See the 'Updates' section lower down for the **app update**.

**Comment by Tantacrul** [comment]
Marked as P2 because of potential (quite bad) misinterpretation on the behalf of the user.

**Comment by RobFog** [comment]
Would it perhaps makes sense to just move the update checking button below the dropdown?

**Comment by Tantacrul** [comment]
We can move it below and rename it too. Should be enough.

**Comment by igorkorsukov** [comment]
renamed to "Check for language updates" 
https://github.com/musescore/MuseScore/pull/12455
