### ISSUE TITLE
Build broken - qprocess.h problem [MU4 Issue]

### ISSUE THREAD

**Issue by SteveBooth-1** [musescore/MuseScore#11463]
**Describe the bug**
Trying to build 'mscore' fails in MSVC 2019 after carefully following the installation instructions with the following error:

**Error (active)	E1574	static assertion failed with "Required feature processenvironment for file C:\Qt\5.15.2\winrt_x64_msvc2019\include\QtCore\qprocess.h not available."	accessibility	C:\Qt\5.15.2\winrt_x64_msvc2019\include\QtCore\qprocess.h**	

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the 4.0 repo
2. Follow all indicated installation steps in the WIKI including all prereq's
3. Attempt to Build the 'mscore' project, as instructed

**Expected behaviour**
The solution builds successfully

**Screenshots**
See attachment

**Platform information**
 - OS: Windows 10, MSVC 2019, Qt 5.15.2

**Additional context**
![Capture](https://user-images.githubusercontent.com/29924924/166007685-1e305d1b-782d-4fae-a9d0-c7251ace8556.PNG)

**Comment by Jojo-Schmitz** [comment]
Doesn't fail for me locally nor on GitHub CI, so it must be your setup

**Comment by SteveBooth-1** [comment]
All I can say is that I followed the installation/build instructions in the WIKI, so clearly there must be some difference between what you have and what is created by the documentation.  I would expect that you have some configuration setting that is not currently documented.

**Comment by SteveBooth-1** [comment]
Believe I've found it.. at least it's root cause:

![image](https://user-images.githubusercontent.com/29924924/166083675-e105e993-ab6a-454a-91df-0ff761b5a0fc.png)

**Comment by SteveBooth-1** [comment]
Bad PATH variable assignment:
![image](https://user-images.githubusercontent.com/29924924/166084018-04a9eec4-81f8-4a04-9066-e8964c8f330a.png)

**Comment by Jojo-Schmitz** [comment]
Yes, a) my PATH points to the rest get one and b) that winrt stuff isn't installed in the first place. I'm sure the latter is not mentioned as having to be installed in the Wiki

**Comment by Tantacrul** [comment]
This isn't really a bug for GitHub. I think the Discord is the best place to continue this discussion. I would also suggest you ask our community ambassador, @shoogle for help.
