### ISSUE TITLE
[MU4 Issue] Textframes Cannot be Edited or Displayed

### ISSUE THREAD

**Issue by jieshunwang** [musescore/MuseScore#11467]
**Describe the bug**
Any newly added textframes, besides the title frame which is originally added by the score setup wizard, cannot be edited.

**To Reproduce**
1. Create a new score.
2. Add a custom text frame from either the side bar or going to "Add -> Frames -> insert text frame/append text frame"
3. The resulting textframe cannot be edited. Any text that has been forced into them also doesn't display.

**Expected behavior**
Adding a textframe should result in an editable textframe where text can be entered, and displayed.

**Screenshots**

https://user-images.githubusercontent.com/39250962/166101354-afeba5cf-7807-4855-97f0-01a57d622f2c.mp4

**Platform information**
 - OS: Windows 11 Home
- Version: 21H2
- OS Build: 22000.613
- Experience: Windows Feature Experience Pack 1000.22000.613.0

**Additional context**

**Comment by Tantacrul** [comment]
Confirmed in latest nightly. The user cannot enter text in this field.

**Comment by DmitryArefiev** [comment]
Fixed in #11639
