### ISSUE TITLE
[MU4 Issue] Staff Type is diplayed wrongly in Instruments sidebar etc.

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11469]
**Describe the bug**
In the Instruments sidebar, if you click on the "edit" cog for a tablature _staff_, it always shows "Standard (staff)" no matter what the _actual_ setting of the tablature.

**To Reproduce**

1. Select New Score > Create from Template > Solo > Guitar + Tablature. Click "Done".
2. Click on the tablature staff, open the "Instruments" sidebar and click on the cog next to the tablature staff. Read the "Staff type".

RESULT: It shows "Standard", though the tablature is actually "Tab 6-str simple".

3. Open "Staff Part properties > Advanced style properties" and look at "Template".

RESULT: It is blank.

**Expected behavior**
The Staff type should always show the correct setting for tablature, as should "Template" in Advanced style properties.

**Comment by Tantacrul** [comment]
I logged this a few weeks ago #10780. There is a fix prepared for it.
