### ISSUE TITLE
Shortcuts section in Preferences is still very broken

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11474]
**Describe the bug**
The shortcuts panel has the following issues.

1. When holding the shift modifier and pressing a number (in this example '0'), the keys that appear are **⇧ )** rather than **⇧ 0**
As a result, the newly defined shortcut doesn't work

<img width="620" alt="image" src="https://user-images.githubusercontent.com/21022311/166109666-7124d981-6bfc-48f2-a685-cba1bcf7e537.png">

2. If you search for 'Triplet' and then clear the shortcut for it ( which is **⌘ 3** or **Ctrl 3**). Now try to define the same shortcut again and an error will tell you it is already in use. (See image below). This means a user cannot clear a shortcut from one action in order to assign it to another.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/21022311/166109732-917a563a-d61c-4bac-bb50-02dc49f733e9.png">

3. In one case (possibly more, I've not checked) the same shortcut is defined by default to multiple actions:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/21022311/166109820-2c74db02-bb34-4e4d-8183-6b88ab7e35c6.png">
<img width="595" alt="image" src="https://user-images.githubusercontent.com/21022311/166109826-44a51419-3815-4f14-830a-d06af1d42134.png">

We need to remove all default duplicates 

4. We no longer want to reveal shortcut sequences. They cause incredible confusion to users who just want to specify a simple shortcut and cause constant crashes in MS3. We **may** decide to support them again in later versions but only if there is enough demand for them.

5. We should remove the ability to have to 'Add' another shortcut definition. There should only be one shortcut (or shortcut sequence) per action. For this reason, we need to remove the 'Add' button and only have the **Replace** button, which should be renamed to **Apply**. This will also massively help the UX.

6. By removing the button (and functionality) for the 'add' button, this will help with this last visual bug, which is that the cancel button is falling out of frame 
<img width="552" alt="image" src="https://user-images.githubusercontent.com/21022311/166109766-c5632074-d8a2-45e3-b676-6b251bf77ff9.png">

Please send to @bkunda or myself for testing. If anything is unclear in this description, let me know and I'll happily jump on a call or chat to clarify

**Comment by Tantacrul** [comment]
I've added a P0 because it is core functionality that is completely broken.

**Comment by Tantacrul** [comment]
@bkunda - I seem to recall that you defined some of this stuff before. Is there a task or issue somewhere that I should link to?

**Comment by cbjeukendrup** [comment]
This one is also related: https://github.com/musescore/MuseScore/issues/11060

**Comment by Tantacrul** [comment]
Thanks for linking. I'm aware that many of the old shortcuts cannot simply be ported because they were developed more like little mini-programs. For this reason, we need to be careful not to get too bogged down trying to recreate every old shortcut again. My advice would be to judiciously add ones we think are high priority and save the rest until later releases.

If people really miss some, they'll tell us either during beta or after.

**Comment by MarcSabatella** [comment]
Right now from what I can see, the most glaringly obvious missing shortcuts are the navigation commands that are absolutely essential for accessibility as well as for keyboard use in general.  In particular, the shortcuts for next/previous staff or voice.  These commands seem to just be gone, unless they've been renamed to something I can't find, which is certainly possible.

Without these commands, it's impossible to navigate or edit anything but the top staff of a score without the mouse.  So if they are truly missing, adding them back should be P0, as it's a complete showstopper for accessibility, and also quite bad for anyone trying to enter notes via keyboard.

Next most important missing shortcuts to me are F2 (special characters dialog) and Z (symbols palette).  I would also put in votes for Shift+K/T for key/time signatures palettes.  These are ones I find myself most often being disappointed by.

**Comment by Tantacrul** [comment]
Would you mind listing the ones you consider to be essential in a comment under #11060? Then we can edit the overall issue and include them. Just keeps the task in one place.

**Comment by MarcSabatella** [comment]
Done!

Regarding the ability to have more than one shortcut for the same command, I agree it's not really "essential" and shouldn't be implemented in a way that confuses the experience for others, and I agree the MU3 implementation had that flaw

But it is important to realize that this capability *was* added for good reason, and it's something I and many others take advantage of quite regularly, and it *will* be missed if removed.  Far from theoretical, it's the most practical way to have a single set of shortcuts shared between multiple systems that have possibly different keyboard layouts.  For example, if you have a desktop system with a numpad and a laptop without, or a Mac and a Windows computer, or two different Linux machines but one of them reserves certain Alt combinations and the other reserves different ones.  It's incredibly useful to be able to make changes to the shortcut customizations on one system and then export those shortcuts and import into the other systems.  But making this work requires the ability to have multiple shortcuts for any given command.

This very shortcut is an excellent case in point  As long as I can remember, it's been the case that the shortcut for zoom in works one way on some keyboards, differently on others, depending on the specific keycodes your particular system issues for the "+" key.

There are other use cases worth considering too, like having a single system used by multiple people, or someone (e.g., me) who wants to be able to use his own favorite shortcuts without losing sight of the defaults so he can still use those in demonstrations etc.

**Comment by Tantacrul** [comment]
Well, rather than get into this in details, I'll just put it like this:

The current state of shortcuts (an incredible mess from a technical POV and not great from a UX POV) was something we didn't expect to encounter. Our attitude when coming across something unmaintainable is to build a solid foundation, which we can build upon over time.

In the case of assigning multiple shortcuts, our feeling is to:
1. Stick with what we have (with some UX cleanup) for 4.0. Fix the code mess. Get it stable, etc.
2. Design a comprehensive system for shortcuts in 4.x
3. Add high-level customisation on top of that system (including the features under discussion here)

So, when I advocate to ditch something, I'm doing so because I believe we can safely re-introduce it later without causing outrage. This isn't always going to be the case... we'll quickly catch up to all the features we used to have and soon after that, we'll be far ahead.

**Comment by MarcSabatella** [comment]
Understood.  As I said, I don’t consider this “essential” at all.  I just wanted to be sure the actual use cases were understood so we don’t rule them out completely.  I’m fine with multiple shortcuts not being part of an initial release, but do hope to see them back at some point.

BTW, as part of any major rethink of shortcuts, I do hope we can finally consider including individual palette items in this!

**Comment by cbjeukendrup** [comment]
@Tantacrul just to clarify: #11060 is not about specific actions that have not been ported yet. 

It is about how actions are listed in preferences; actions that don't have a shortcut will not appear in the list. So the user is unable to add a shortcut to an action that does not have a shortcut by default. That's just a technical mistake, or just not yet fully implemented.

**Comment by MarcSabatella** [comment]
Indeed, there was an issue for action kissing actions but it got closed - which is fine, because the specifics were from a year ago and were way out of date.  But that’s why I commented here as the closest relevant place to keep the most important points alive.

probably there should be a new issue dedicated to the most important remaining unimplemented commands.  But right now it’s hard to know which commands are unimplemented and which are merely missing from the list because they have no default shortcut.

**Comment by bkunda** [comment]
> @bkunda - I seem to recall that you defined some of this stuff before. Is there a task or issue somewhere that I should link to?

Yes https://github.com/musescore/MuseScore/issues/8746. I've just assigned @vpereverzev so his can coordinate it with his team.

**Comment by jieshunwang** [comment]
> Thanks for linking. I'm aware that many of the old shortcuts cannot simply be ported because they were developed more like little mini-programs (or hacks) in MS3. For this reason, we need to be careful not to get too bogged down trying to recreate every old shortcut again. My advice would be to judiciously add **only** shortcuts we think are high priority and save the rest until later releases.
> 
> If people really miss a shortcut, they'll tell us either during beta or after.

While I have tested out a entering a score completely from scratch, the only one I think would be very helpful is to be able to attach accidentals to notes from the keyboard. It is a big hassle having to enter those notes, and then go back and manually attach accidentals using a mouse.

**Comment by Tantacrul** [comment]
100% agree about this. Can you create a new issue for it - and possibly suggest key-bindings too?

**Comment by Tantacrul** [comment]
@jieshunwang  100% agree about this. Can you create a new issue for it - and possibly suggest key-bindings too?

**Comment by jieshunwang** [comment]
> @jieshunwang 100% agree about this. Can you create a new issue for it - and possibly suggest key-bindings too?

Done in #11500.

**Comment by wizofaus** [comment]
BTW there are quite a few other issues with the shortcuts assignment dialog that I noted recently, including that a number of commands (e.g. Transpose) are not available for mapping to shortcuts, and that it doesn't appear to prevent me from assigning the same key to a large number of commands.
Under Windows at least, shortcut sequences do generally work, though there are certainly cases they can behave unexpectedly (in particular Ctrl+Y Ctrl+1/2 for adding treble/bass clef, as Ctrl+Y is already mapped to something else). But the shift+R sequences for adding different length rests seem to work OK.

**Comment by bkunda** [comment]
> BTW there are quite a few other issues with the shortcuts assignment dialog that I noted recently, including that a number of commands (e.g. Transpose) are not available for mapping to shortcuts, and that it doesn't appear to prevent me from assigning the same key to a large number of commands.
> Under Windows at least, shortcut sequences do generally work, though there are certainly cases they can behave unexpectedly (in particular Ctrl+Y Ctrl+1/2 for adding treble/bass clef, as Ctrl+Y is already mapped to something else). But the shift+R sequences for adding different length rests seem to work OK.

If it's possible to assign the same shortcut sequence to multiple commands, I'd suggest this is probably a bug worthy of a dedicated issue. Would you mind raising it please @wizofaus? 

Also if there are any specific commands that aren't yet ported, it might be because they weren't prioritised for porting (see https://github.com/musescore/MuseScore/pull/10006). If there's something that is on this list, or which has been inadvertently left-out, please also write that up as a dedicated issue. Thank you!

**Comment by wizofaus** [comment]
Have logged https://github.com/musescore/MuseScore/issues/11521.
I thought that "Transpose" wasn't in the list simply because it didn't have a shortcut by default (known bug as mentioned already), but nor does "Go to top staff", which is shown, though it seems to be the only command shown that doesn't have one by default.

**Comment by rgreen5** [comment]
One other issue for fixing (if not already known): the "Cancel" button in the "Define Keyboard Shortcut" abuts  onto the dialogue edge and has an indefinite length; if you extend the dialogue, the button extends with it.

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2513269173, revision: github-musescore-musescore-7117330

Some shortcuts which have been assigned in the action list (Preferences) and _do_ actually work, do not have menu entries. e.g.

* Insert (insert one measure after selection). Should be in Add > Measures.
* Ctrl+B (Insert one measure at end of score). Should be in Add > Measures.

Conversely, there are menu entries which work but have no shortcuts displayed or assigned. e.g.

* Insert after selection
* Insert at start of score.
