### ISSUE TITLE
[MU4 Issue] Accessibility: keyboard navigation breaks at key and time signatures if >1 staff

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11478]
Navigation of the score one element at a time via Alt+Left/Right it how blind users use MuseScore.  Currently in MU4 (as of the build I'm using from a few days ago, anyhow), navigation breaks when you reach a key or time signature, if there is more than one staff.

To reproduce:

1) new score, grand staff
2) start pressing Alt+Right to navigate

Result: when you reach the key or time signature, you will note they are selected across both staves.  This much is kind of normal when *clicking*, in that we do "often" want selecting a time signature to select them across all staves.  But navigation by keyboard needs to select just the one on the current staff.  Otherwise the screen reader doesn't know what to read.  And more importantly, right now pressing Alt+Right again does nothing - navigation gets stuck at the list selection.

**Comment by Tantacrul** [comment]
@shoogle  - FYI. Can you keep an eye on this one?

**Comment by DmitryArefiev** [comment]
Fixed in #11911

Testing on Linux is blocked by #11897

**Comment by DmitryArefiev** [comment]
@MarcSabatella You can check it in master now if you want (if I missed anything when tested)
