### ISSUE TITLE
Crash when undoing a split measure.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11488]
**To Reproduce**
1. Open this score: https://www.dropbox.com/s/dzwvbhobmxo9yzl/MS4_Advert_01.mscz?dl=0

2. Go to measure no.9 and select the following note in the Oboe
<img width="708" alt="image" src="https://user-images.githubusercontent.com/21022311/166147874-15f9d520-f126-447e-9f9d-22e2ea1d02b0.png">

3. Select **Tools > Measures > Split measure before selected note/rest**

4. Observe that the measure is now split:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/21022311/166147884-fcdde659-be56-46c4-9c97-2e27db31baa8.png">

5. Now press **Ctrl+Z** undo the action (this regularly causes a crash)

6. If it doesn't crash then redo the split measure action again (this should produce the crash)

This crash is not 100% reproducible on new scores. However, once you perform the split action, it doesn't take long for the app to crash when trying to do something else. The score I provided above is one where the problem was most easily reproduced.

**Comment by donarturo11** [comment]
![split-crash-20220501](https://user-images.githubusercontent.com/6421054/166149224-606709e2-2615-4c70-b6bb-804a22b0a629.png)

**Comment by donarturo11** [comment]
[backtrace-after-crash.txt](https://github.com/musescore/MuseScore/files/8611053/backtrace-after-crash.txt)
So with gdb with backtrace I found problem in [tie.cpp:976](https://github.com/musescore/MuseScore/blob/0aceb6c53155847cec880a3616ef134c130f1a4e/src/engraving/libmscore/tie.cpp#L976).
I checked too that joining measures from menu doesn't cause SEGFAULT. I'll check this function. I think that in this place must be a risk to call to unavailable resource causing SEGFAULT.
