### ISSUE TITLE
Remove ugly 'MU' file icon from the top bar for saved scores

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11496]
**Describe the bug**
Not sure when this was added but it is a little ugly looking and adds unnecessary extra noise above 'Mixer' and 'Parts'

<img width="796" alt="image" src="https://user-images.githubusercontent.com/21022311/166216880-6d5fc9d5-e135-4ddd-bccf-73d804363b1b.png">

**Expected behaviour**
Text only

**Comment by HemantAntony** [comment]
Can't reproduce in Windows 11

**Comment by cbjeukendrup** [comment]
@Tantacrul I'm quite strongly against removing this. It is the default behavior of macOS, and it is very functional: 
- if the file has unsaved changes, the icon will be darkened as on this screenshot
- you can drag this icon to drag the file, for example to drag it to an email, or to drag it to another folder. This way, you don't need to look for the file in Finder to drag it from there.
- if you still need to see the file in Finder, you can right-click the icon, and click the containing folder from a menu, to open that folder in Finder. 

We can remove it, but anyone who knows the power of this icon will miss it.

**Comment by Tantacrul** [comment]
@cbjeukendrup - thanks. I was not aware of any of these functional properties.

I guess I'll need to simply redesign the thing because it's an eyesore :)

Assigning to myself.

**Comment by cbjeukendrup** [comment]
You can't really design much about this, it's fully controlled by macOS. (Unless you mean you'd like to redesign the icon itself, which I of course appreciate 😄)

**Comment by Tantacrul** [comment]
Yes, the icon itself.

**Comment by cbjeukendrup** [comment]
@Tantacrul does the new icon (#11556) count as a fix for this issue?
<img width="375" alt="Schermafbeelding 2022-05-12 om 21 42 46" src="https://user-images.githubusercontent.com/48658420/168155669-692bbc52-95b9-4b41-9732-0826d6cd6a16.png">

**Comment by Tantacrul** [comment]
Yes it does. And also you're helpful tutorial :)
