### ISSUE TITLE
[MU4 Issue] A number of text items from Palettes have no text settings in Properties

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11495]
**Describe the bug**
The following items from the "Text" palette currently show no text appearance settings in the Properties panel. 

- Open
- Distort
- Overdrive
- Legato
- Pizz.
- Arco
- Tremolo
- Mute
- Normal
- Detache
- Martele
- Col legno
- Sul pont.
- Sul tasto
- Vibrato

<img width="500" alt="Screenshot 2022-05-02 at 6 31 23 pm" src="https://user-images.githubusercontent.com/86290556/166206738-8de68e6f-4bcc-417b-ab31-0417bef2f0d2.png">

**To Reproduce**
1. Select a note in any score
2. Open the "Text" palette
3. Click on any of the above-listed text items to add it to the selected note
4. Open the "Properties" panel and observe no settings beneath the "General" section

**Expected behavior**
Text settings as per all other text objects (See, for example, "System text") should apply to all above-listed text objects

**Platform information**
 - MacOS 12.3.1 (M1)

**Comment by RomanPudashkin** [comment]
Works fine in the current master. @bkunda please reopen if you can still reproduce it
