### ISSUE TITLE
[MU4 Task] Add new instruments for fretted instruments that have tablature option

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11497]
**Task description**
This is a proposal to address #11027 (concerning a UX issue around creating linked staves for tablature instruments) by adding a new instrument for each of the below-listed instruments in the format "`instrument name`(notation + tablature)". These instruments would contain both their standard notation stave _plus_ a linked tablature stave (of the variety already defined in the "tablature" version of the corresponding fretted instrument). 

- 5-str. Electric Bass (high C/tenor)
- 5.str. Electric Bass
- 6-str. Electric Bass
- 7.str. Guitar
- Acoustic Guitar
- Bandurria
- Banjo
- Bass Guitar
- Cavaquinho
- Classical Guitar
- Electric Bass
- Electric Guitar
- Irish Tenor Banjo
- Laúd
- Lute
- Mandolin
- Mtn. Dulcimer
- Mtn. Dulcimer - Baritone
- Mtn. Dulcimer - Bass
- Ukelele

_Example mockup_
<img width="1854" alt="new-instruments-clef-plus-tab" src="https://user-images.githubusercontent.com/86290556/166224119-23ec29f6-b062-40ee-bc42-66df9e8d4839.png">

N.B. The instrument descriptions (as displayed in the bottom left corner of the **Instruments** panel) would also need to be updated as part of this task. This is important for displaying longer instrument names that don't fit within the centre "Instruments" column of the dialog. Here I would suggest we could provide something along the lines of the following: For example, "Classical Guitar (notation + tablature)" might contain the description "Acoustic nylon-strung guitar (staff notation with 8va bass treble clef and linked tablature stave)". 

N.B. Any of the above instruments currently available when the "Common" filter is applied should _also_ have the new "...(notation + tablature)" instrument included as part of the "Common" instruments list.

Tagging and assigning also @shoogle and @oktophonie who both have a lot to do with instrument definitions 🙂

**Comment by Tantacrul** [comment]
I wonder whether we should use those dropdowns we use elsewhere for transposition instead. It would make the list a bit easier to parse.

For example you'd see **Bass Guitar** + a DD that contains 3 options: Notation / Tab / Notation + tab

**Comment by bkunda** [comment]
> I wonder whether we should use those dropdowns we use elsewhere for transposition instead. It would make the list a bit easier to parse.
> 
> For example you'd see **Bass Guitar** + a DD that contains 3 options: **Notation / Tab / Notation + tab**

Actually I don't see why we _shouldn't_ do this. It would definitely make this panel easier to parse. 

I'll correct the issue description accordingly.

**Comment by bkunda** [comment]
Actually on second thoughts, I would propose we keep this task as initially suggested. 

One significant issue is the horizontal space available in the centre "instruments" column for both the instrument name label _and_ the dropdown menu. Our current design pattern for the dropdown is not wide enough to accommodate the lengthy menu option "notation + tablature" (or even an abbreviated "notation + tab"), and in the interests of not introducing anything significantly new at this stage of MS4's release, I think that _not_ disrupting the current design is perhaps the prudent path to take. 

Also having the instruments listed separately gives us the opportunity to add a more useful (and lengthier) description for each one: For example, "Classical Guitar (notation + tablature)" might contain the description "Acoustic nylon-strung guitar (staff notation with 8va bass treble clef and linked tablature stave)". 

Ultimately though, I _do_ think that a cleverer dropdown (or context menu) solution is absolutely the way to go. But at this late stage of the piece, my recommendation is to adopt the path of minimal change. 🙂

**Comment by Tantacrul** [comment]
Got it. Thanks

**Comment by shoogle** [comment]
As a short term solution, adding new "Guitar (notation + tablature)" instruments might indeed be best compromise, but I'll need to discuss it with @oktophonie first because it could create more headaches for us in the future in terms of backwards compatibility, etc. We might recommend living with the issue in the short term and returning to look at it properly after MU4 is released.

As a long term solution, I propose adding a settings cog wheel button (⚙️) in the "Your score" column next to / instead of the "Make soloist" button that appears for the selected instrument. This button would open a popup with options to customise the instrument (e.g. change staff type or clef).

![image](https://user-images.githubusercontent.com/11011881/166269101-56370413-f5e4-46db-bcc2-cef63af43ba6.png)

Advantages:

- The NSW is no more complicated than before (complexity is hidden behind a popup)
- The options displayed in the popup can be different for different instruments (most instruments don't need the tab staff option).

**Comment by Tantacrul** [comment]
I think we need a solution for this in MS4. I dislike the idea of the cog over in 'Your score'. It would mean that some instrument-specific settings are on the left and some on the right.

I can actually think of quite a few solutions for this. Ultimately, we should replace the dropdowns that contain transposition info and replace them with popups that contain more space to handle more detail and precise, well-described options.

**Comment by shoogle** [comment]
The detailed popup sounds good. I think I'd still put the button on the right though to enable you to customize the instrument after you've added it to the "Your score" column. This would allow you to change your mind about the transposition, clef, staff type, etc. without having to remove the instrument and add a new one with new settings.

**Comment by bkunda** [comment]
While I find the "change your mind" argument quite compelling (in favour of having the settings button – whatever it ends up being – in the "your score" column), the disadvantage of this could be one of discoverability: the user won't necessarily know that they can, for example, select a specific instrument transposition until after they've added the instrument. From my POV, this latter case might outweigh the former argument. 

I would totally like to design a more complete popup for this dialog though, and would be strongly advocating for this now if we weren't so close to the MS4 release. So @shoogle do let us know what your's and @oktophonie's recommendation is about the present solution, and we can re-assess things from there 🙂.

**Comment by shoogle** [comment]
Let's put the long term solution to one side for now. @oktophonie, @bkunda and I had a chat about short term solutions earlier.

### Short term options

1. Create duplicate instruments in instruments.xml with IDs like:
    - guitar
    - guitar-tab
    - guitar-normal+tab
 
 2. Avoid duplicate IDs and instead allow the `guitar` instrument ID to be used with normal, tab, or both types of staff.
 
For both options, the end result would be like in @bkunda's [mock-up screenshot](https://github.com/musescore/MuseScore/issues/11497#issue-1222755219), where each fretted instrument appears three times in the instrument list in the New Score dialog.

### Implementation

For the above options

1. An easy solution now but creates compatibility headaches in the future.
2. Avoids compatibility problems but it's more difficult in the short term and would delay MU4's release.

For a while we thought we could get the best of both worlds, but then then we remembered that the instrument list is also used in the [Change Instrument](https://user-images.githubusercontent.com/11011881/166454532-67e73476-a693-4ded-91e7-1fa137b9d2fe.png) and [Replace Instrument](https://user-images.githubusercontent.com/11011881/166454615-09835b5c-2dad-4023-8a6a-654370e453b5.png) dialogs. This makes everything more tricky, both in terms of implementation, and also in terms of fulfilling user expectations:

> _"I added a Guitar (normal), then I changed it to Guitar (normal + tab) but it didn't give me an extra staff!"_

### Conclusion

So, unfortunately, our recommendation is to not fix this for the time being. Instead, we recommend waiting to implement a general solution in MuseScore 4.1 or later.

**Comment by shoogle** [comment]
### Alternative suggestion

Instead of exposing the option in the New Score dialog, we might be able to make it easier to add a linked staff from within the Instruments panel. Currently there is a prominent "Add staff" button but the option to create a linked staff is buried inside a popup.

Instruments panel | Staff type popup
---|---
![image](https://user-images.githubusercontent.com/11011881/166460911-dd24c747-c374-446c-ac3a-99e8a7fe8b3e.png) | ![image](https://user-images.githubusercontent.com/11011881/166456946-b52d1766-be58-4333-932d-b7e6a539a6c7.png)

Why not have an "Add linked staff" button right next to the "Add staff" button? The new button would be disabled (greyed out) until a staff is selected, but it would be visible all the time to aid discoverability.

**Comment by Tantacrul** [comment]
Agree.

**Comment by Tantacrul** [comment]
However, I still think we should think of a solution for adding them to a score without the step of a 'linked stave', which is a really strange and unintuitive idea.

**Comment by bkunda** [comment]
> However, I still think we should think of a solution for adding them to a score without the step of a 'linked stave', which is a really strange and unintuitive idea.

I think the longer term solution of having a more complete popup in all of the various "instruments" dialogs is going to be the way to go. But this is likely to be too much to implement for MS4. I'm happy to start working on some designs for this, though.

**Comment by Tantacrul** [comment]
We don't need the uber solution - just a solution. I'm happy with there being instruments that say 'tab + notation', if Simon and Peter are happy with it.

The reason for this issue was that we wanted to make guitar with notation+tab easy to fine because we recognise that 'linked staves' won't be figured out by most users.

The solution to this problem isn't to make linked staves slightly more discoverable.

**Comment by bkunda** [comment]
The problem as I've begun to understand today (from talking with Peter and Simon) concerns the Instrument IDs. If we implement my proposed solution, this could either cause:

1. Significant headaches down the track (because – when we do eventually adopt the "über solution" – we'll end up having superfluous IDs that could cause problems when importing scores), OR 
2. Delays in implementation (should we adopt the more elegant solution of using the same Instrument ID for multiple staff configuration (which we were all in favour of) – this is apparently going to be complicated because there are multiple dialogs where adding instruments is possible. 

Hence the real solution is probably to leave the UX as it currently stands...unless we can be somewhat certain that using the same Instrument IDs is not going to be too complicated to implement.

**Comment by shoogle** [comment]
Here's a really out-there solution: we could add a notation and tab staff to all the fretted instruments and then tell people to delete the staff they don't need! 😉

**Comment by bkunda** [comment]
> Here's a really out-there solution: we could add a notation and tab staff to all the fretted instruments and then tell people to delete the staff they don't need! 😉

As a classical guitarist, this solution wounds me.

**Comment by bkunda** [comment]
Seeing as how we've realised implementing this solution properly (assigning the same Instrument ID to multiple staff configurations) is going to add implementation delays, I think it's reasonable to close this task for now. We'll most likely end up replacing it with a task to implement the "ideal" solution of a comprehensive popup in the various instruments dialog.
