### ISSUE TITLE
Rename "MuseScore_General_HQ" sound font to "MS Basic"

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11492]
**Task description**
Hear me out...

One of the awkward things about our new mixer is that we've necessarily needed to keep each track quite narrow. As a result, some VST and sound font titles get truncated (a very common issue across plenty of DAWs and other notation apps).

In the case of **MuseScore_General_HQ** (which is now our default), I feel we can't have a situation where this is what people are greeted with when they first open the app:
<img width="114" alt="image" src="https://user-images.githubusercontent.com/21022311/166163347-f2c39d1a-fc82-4bbe-8a9a-c5c9ff7bb160.png">

Or possibly:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/21022311/166163418-d6a7cdd7-1a32-4572-a0c9-9fa49c6b83a3.png">

**Comment by RobFog** [comment]
"MS Jojo-Schmitz" is probably best.

**Comment by quinnouyang** [comment]
Especially for 3rd-party names, what if we add a hover tooltip? (Assuming it doesn't deviate much from the design practices.)

**Comment by Tantacrul** [comment]
We should do a tool tip but I'd say we leave that for a later release. Trying to lock things down now as much as possible.

**Comment by MarcSabatella** [comment]
Good call.  I feel like I’ve noticed similar opportunities elsewhere but of course I can’t think of any at the moment.

**Comment by Jojo-Schmitz** [comment]
"MS General HQ" would probably fit too

**Comment by Tantacrul** [comment]
I think 'HQ' is redundant now, since that it is the default.

**Comment by RobFog** [comment]
> I think 'HQ' is redundant now, since that it is the default.

For the many users who will be updating from MuseScore 3, an FAQ could be: "Which of the previous default soundfonts is this?"  Maybe this question could be handled in version 4's release announcement.

**Comment by Tantacrul** [comment]
Actually, I've always wondered how many users actually realised you can update to MuseScore_General_HQ, given how hidden the option to update it is. Lemme create a poll...

**Comment by Tantacrul** [comment]
Let's see how this pans out. My prediction is that **'I did not know about this'** will get over 70%.

My reasoning is that the place it is installed from is very hidden and very few users ever read user manuals.
https://twitter.com/Tantacrul/status/1521069078018142209

However, my predictions tend to be overly heavy handed. Let's see!

**Comment by Tantacrul** [comment]
Also posted the same poll here: https://www.youtube.com/c/musescore/community

**Comment by quinnouyang** [comment]
I, for one, did not know about this:D Though I've been using the [ASO](https://sites.google.com/view/hed-sounds/aegean-symphonic-orchestra) soundfont for years...

**Comment by MarcSabatella** [comment]
Without seeing the result of the poll, I'd also expect a significant number of people saying "I heard about it, tried to install it, but got an error and gave up".  Because this basically stopped working a year or two ago when the timeout for the download got shortened in the code, and most people don't have internet connections fast enough.  So the only reliable way to get this now is not through the resource manager but by finding the magic location you can download the file from directly then install it manually.

**Comment by Tantacrul** [comment]
Well, a lot of people have responded and the result is actually worse than I expected.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/21022311/166292958-78d3c1a4-6902-4af6-8466-39c0b5a527cd.png">

<img width="838" alt="image" src="https://user-images.githubusercontent.com/21022311/166293126-02350da6-746b-4f62-9a0d-9a8f9ef9782e.png">

**Comment by Tantacrul** [comment]
We should absolutely not require users to go to the mixer to change anything when coming from MS3. We just need to change the name of the soundfont. It should then just be called 'MS Basic' and require no set up at all.

**Comment by Tantacrul** [comment]
Oh, well in that case, it's fine :D

Sorry! I was quite rushed + confused

**Comment by DmitryArefiev** [comment]
Oh cool!
