### ISSUE TITLE
Put "Head Scheme" dropdown (from MS3) into the MS4 inspector 

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11505]
**Describe the bug**
This is an option I missed when creating the Inspector design for noteheads. It is a simple dropdown in MS3 that looks like this:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/21022311/166445842-9396b36b-846f-4cf8-903d-817782e73df0.png">

This is actually a lovely little feature. In MS4, we just need to put the same dropdown here, at the top of the **Show more/less** section. I also propose we rename it to 'Notehead system' unless anyone has any objections? I do not propose any functional changes. It works well as it is now.
<img width="578" alt="image" src="https://user-images.githubusercontent.com/21022311/166445482-3fc3d4fa-4277-44b9-ae2a-e2683b355983.png">

This is found in our Figma file in the 'Inspector' page.

**Comment by HemantAntony** [comment]
@Tantacrul check #12281
