### ISSUE TITLE
[MU4 Issue] Cancelling "change instrument" dialog still effects instrument change

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11502]
**Describe the bug**
Entering a "change instrument" element from the **Text** palette triggers a dialog that allows the user to select which instrument/sound they want for their mid-score instrument change. 

The issue is that, if the user clicks **Cancel** without making any instrument selection, an instrument change is still added to the score, and a (rather random) instrument is assigned for playback. 

Video to demonstrate: 

https://user-images.githubusercontent.com/86290556/166232893-0a51304d-1098-49a7-8864-37410738c2f6.mov

**Expected behavior**
I would expect that pressing **Cancel** in this dialog would cancel the process of adding a "change instrument". The label in the score would therefore be removed and there would be no change to the playback sound of the stave in question.  

**Platform information**
 - MacOS 12.3.1 (M1)

**Comment by Tantacrul** [comment]
Confirmed. I'm guessing this is an easy fix. Nice spot!

**Comment by shoogle** [comment]
> The label in the score would therefore be removed

Or better yet, not added in the first place. Ideally it should only be added after the user clicks "OK" in the dialog.

**Comment by bkunda** [comment]
> > The label in the score would therefore be removed
> 
> Or better yet, not added in the first place. Ideally it should only be added after the user clicks "OK" in the dialog.

If that's possible, then yes! I was only thinking that all palette objects currently behave on an apply-immediately-on-click basis (assuming an object in the score has been selected first). But if an exception can be made for cases that trigger a dialog, then all the better 🙂

**Comment by HemantAntony** [comment]
@bkunda I finally finished polishing 😄

Also there was a similar bug when you applied by clicking a note and then just clicking the Change inst. Palette Cell instead of dragging
