### ISSUE TITLE
[MU4 Task] Assign default shortcuts to selected note input commands for adding accidentals 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11516]
**Task description**
Would resolve #11500 

The suggestion here is to assign default shortcuts for the below actions as follows: 

- `+` for **Note input: sharp** (and rename action to **Toggle accidental: sharp**)
- `-` for **Note input: flat** (and rename action to **Toggle accidental: flat**)
- `=` for **Note input: natural** (and rename action to **Toggle accidental: natural**)

And while we're at it:

- Change the shortcut for ties to `T`. 

**Note also**: 
- Shortcut `-` should retain its existing functionality for text entry, while also being available for note input mode as described above.
- Existing shortcut `=` should be removed from "Toggle 'automatic placement' for selected elements". A replacement shortcut does not need to be designated at this stage.  

Let me know if there are any questions about this
Thanks!

**Comment by quinnouyang** [comment]
There's two available shortcuts for each in `notationuiactions.cpp`, e.g. for sharps:
- `sharp`, "Toggle accidental: sharp"
- `sharp-post`, "Double ♯ (non-toggle)"
Ignoring the toggle option, I can set the default for `sharp-post`. To double-check, should I re-write these as `add-sharp` and `Add sharp` (I can try to sneak in the ♯ symbol like we do for note duraitons).

**Comment by bkunda** [comment]
I can't actually advise on whether/how this should be re-labelled in the code. Perhaps @MarcSabatella or @cbjeukendrup might have an opinion on this.

But you have made me realise that the word "toggle" should probably be included in the UI label, because this is effectively what the shortcut does. I'm going to correct the issue description to reflect this, but yes the labels in the "Action" list in "Preferences > Shortcuts", should read in the format "Toggle accidental: sharp".

(Don't bother about sneaking in those symbols - they already appear in the left column, and they are problematic substitutes for the actual words from an accessibility and translation POV) 🙂

**Comment by quinnouyang** [comment]
To clarify, I added those symbols in the left column.

Are we toggling or just adding? The differences between `sharp` and `sharp-post`, etc. is whether they toggle or just add.

On a UX POV, I kind of found the `+` shortcut a little jarring because it's the only one out of the three that require the `Shift` key. (And_ we're still figiuring out how shortcuts look and work through Preferences...)

**Comment by bkunda** [comment]
Oh good. Those symbols are helpful in the left column 👍🏻.

And my mistake 🤦‍♂️. I had actually proposed to use `#` for sharp because `+` is already tied up with...ties.

I'll correct this in the issue description (my apologies for this).

And I take your point about the shift key. It's unfortunately unavoidable: on some keyboards, the user won't need to use shift, and on others, they will. It's a trade-off we're willing to accept in this case, given how we've allocated other shortcuts across the system. 

Finally, I think we should be working with the toggle-able option here (is that `sharp` or `sharp-post`?)

**Comment by quinnouyang** [comment]
Oops, forgot to mention that `+` is already the default for ties:D (Though personally, I've set that to `t` in MU3.)

Right, I forget that larger keyboards have an explicit `+` key, etc. The shortcut settings function, but IIRC, defining a shortcut for a symbol that requires `Shift` is currently impossible for the user. I couldn't manually set one to `+` with by using `Shift`+`=`.

`sharp-post` is for toggling and similar ones exist for other accidentals. I'll use those and update the specs!

**Comment by MarcSabatella** [comment]
As far as I know, the difference between sharp and sharp-post *should* be, if you're in note input mode, the former does the same as the toolbar - toggles the state of the button to apply to the *next* note - whereas sharp-post would apply the accidental to the *previously entered* note.  Or more generally, to whatever note is selected.  In normal mode, both commands operate on the selection and

Symbols showing is good, but make sure the word appears too, so people using the search bar to look for "sharp" don't come up empty like they do in 3.6.2.

I don't know if the "post" commands actually toggle or not in the MU4 code but in MU3, they did not - they simply added the accidental, or did nothing if the accidental was already present.

And oh yeah, I totally forgot that "+" doesn't work.  I'm still not totally happy with # and - as a pair; one is chosen because it *looks* like the actual symbol, the other because it *means* something similar.  # and b make more sense logically, and it's what we do for chord symbols and other places within text, but all the "b" shortcuts are taken.  The Shift difference bothers me less.  After all, math is a thing, and people deal with + and - being inconsistent in that same way.  Plus whenever I type my name, I need to use Shift for the "M" but not the "arc" :-).  But whatever, we can revisit this any time before the actual release (I wouldn't recommend making changes after), and people can customize it in any case.

**Comment by bkunda** [comment]
> Right, I forget that larger keyboards have an explicit `+` key, etc. The shortcut settings function, but IIRC, defining a shortcut for a symbol that requires `Shift` is currently impossible for the user. I couldn't manually set one to `+` with by using `Shift`+`=`.

If the user needs to use `Shift` to define a shortcut, they can (I've just checked in MS3 and 4 and it is possible in both, although in MS3 using `Shift` to access the `#` just results in `#` being applied. In MS4 the shortcut actually registers both `Shift` and `#`.

**Comment by quinnouyang** [comment]
I noticed that MU4 does detect the `Shift` key, but I oddly can't seem to trigger the `#` shortcut unless I hard-code it as `Shift`+`3` (though it works for ties with `+`, hmm...).

For `+` vs `#`, I'm biased towards setting ties to `t` and sharp toggles to `+`. Keeps the `+`/`-` consistency and if anything, I think the `t` shortcut makes more sense for ties (though I haven't tried the shortcut in other notation apps).

**Comment by bkunda** [comment]
You know what, this actually makes a lot of sense. 

I'd be in favour of doing this. I realise that there might be some backlash from users who are very familiar with the `+` being used for ties. The good thing, though, is that shortcuts can always be changed by the user. What we should be prioritising is logical design that makes the most sense (which `+` and `-` clearly do as opposites of "sharp" and "flat"), even if it means occasionally compromising on some thoroughly learned behaviour (in principle, getting really good at using a less-than-sensible product doesn't justify the product's design). 

Good to have your input @quinnouyang! I'll again update the issue description.

**Comment by Tantacrul** [comment]
I don't have a giant objection. I agree 't' for ties makes sense.

One thing: we need to be able to set a natural too, so it can cancel sharps/flats in a key. We can't rely on something like pressing the sharp or accidental shortcut twice.

**Comment by bkunda** [comment]
> One thing: we need to be able to set a natural too, so it can cancel sharps/flats in a key or measure. We can't rely on something like pressing the sharp or accidental shortcut twice.

I have `=` proposed for naturals. But do let me know if you have a better suggestion 🙂

Let's go with `+` for sharps and `t` for ties then. I'll update the issue description (again)!

**Comment by Tantacrul** [comment]
Hm. Maybe that's an ok compromise. OK. Yeah, makes sense.

**Comment by bkunda** [comment]
@quinnouyang This is ready to go 👍🏻

**Comment by Jojo-Schmitz** [comment]
> On a UX POV, I kind of found the `+` shortcut a little jarring because it's the only one out of the three that require the `Shift` key. 

No, on a German (QWERTZ) keyboard it doesn't.
On NumPAD it doesn't either, independant of language and keyboard layout

> I have `=` proposed for naturals. But do let me know if you have a better suggestion 🙂

That seems fine to me, but does require Shift (on a German QWERTZ keyboard)

> Let's go with `+` for sharps 

# for sharp and b for flat makes more sense IMHO. b might not work though as it is used as a notename, - would work.

> and `t` for ties then. I'll update the issue description (again)!

t for tie makes sense in English, but not most other languages, + seems far more universal there (then again s for slur has the same issue)

**Comment by bkunda** [comment]
I don't think we're going to win on all fronts here @Jojo-Schmitz. What's optimal in one case invariably effects something else. Hopefully we've settled on here will be a reasonable compromise for default behaviour. Beyond this, it is always available to the user to make their own changes according to their preferences and setup 🙂

**Comment by Jojo-Schmitz** [comment]
Well, I'm not sure changing these long-term-finger-memory shortcuts is the way to go at all.

**Comment by Eism** [comment]
@bkunda 
also these shortcuts are already reserved

<img width="600" alt="Screenshot 2022-05-16 at 12 07 24" src="https://user-images.githubusercontent.com/10116828/168558585-2f58d3dd-bbfc-473a-a9b0-3aca435e3295.png">

<img width="600" alt="Screenshot 2022-05-16 at 12 07 44" src="https://user-images.githubusercontent.com/10116828/168558603-82ffc90a-d707-455b-a10e-b2d482cd174f.png">

**Comment by Jojo-Schmitz** [comment]
`-` is only used in lyrics entry mode though

**Comment by Eism** [comment]
@Jojo-Schmitz thanks!
No problem with `-` (next syllable works only when text editing)
What triggering logic should be for `=`?

**Comment by bkunda** [comment]
I'm not worried about "toggle 'automatic placement' for selected elements". Can we perhaps just leave this one blank (undefined)? 

"Next syllable" must retain `-` though, because it crucially adds a hyphen to connect multi-syllable words (and the hyphen appears in the text).  Is it possible for this shortcut to behave in one way for text and another for note entry?

**Comment by MarcSabatella** [comment]
At least in MU3, it wasn't a problem to have shortcuts do different things in different contexts.  Each command had a list of which modes it was active in (normal, note input, lyrics edit, chord symbol edit, etc).

As for "=" for autoplace, I wouldn't worry too much about losing that either, nor would I be in a hurry to choose a replacement.  Maybe leave it blank for now and see how people react.  We can always choose a new default shortcut before release.

**Comment by bkunda** [comment]
Agreed @MarcSabatella. I have updated the issue description accordingly.

**Comment by quinnouyang** [comment]
@MarcSabatella Could you elaborate on what _should_ be different in `sharp-post`, etc.?
(I presume selecting a note turns on note input mode and vice versa.) Current behavior for `sharp-post` seems to be:
- If not in note input mode, nothing happens
- If in note input mode, adds a sharp to the currently selected note
`sharp` seems to turn on note input mode (if not on already), add/remove the sharp from the current selection, and toggle applying the sharp on future notes to input.

We also described the `sharp-post` shortcut as "Add accidental retroactively: sharp", which is more confusing than helpful to me. Locally, I have `sharp` described as "Add/remove sharp", etc.

I downgraded my PR (#11536) to a draft, pending decisions on this and updates from code changes in the past months.

**Comment by MarcSabatella** [comment]
I'm not sure what's been decided about how these should work in MuseScore 4 or if the "post" commands will exist at all, but the way they were originally designed for MuseScore 3:

In normal (not note input) mode *with one or more notes selected*, the commands are identical - they add the accidental to the selected notes (or, if all notes in the selection already have the accidental, it is removed).  If the MU4 version of sharp-post doesn't behave exactly like regular sharp in this case, it's broken according to the original design.

In normal mode with *nothing* selected, regular sharp does the thing you described - goes into note input, activates the sharp button.  sharp-post does nothing.

In note input mode, the behavior differs:

- The regular sharp command does exactly the same as the toolbar: it toggles the state of the button, and when on, it means the *next* note entered will have a sharp.
- The sharp-post command simply adds a sharp to the currently selected note (normally the one you just entered).  If it already had a sharp, nothing happens.

**Comment by quinnouyang** [comment]
MU4 seems to behave as intended, nearly exact to what you say, aside from minute details that are easy to miss when describing via text. However, I'm struggling to find a situation where `sharp-post` is more desirable–it only works when a note is selected and cannot remove accidentals while `sharp` intuitively toggles the accidental on the selection and input mode. Only use difference I can tell is that `sharp-post` doesn't toggle the note input mode (if it's on).

If we're keeping the `-post` commands, accurately and succinctly describing these shortcuts is difficult (I'm already struggling here, heh).

**Comment by MarcSabatella** [comment]
The reason for sharp-post is that it matches much more closely how many people think about notes with accidentals.  We write "G#", we say "G sharp", so many people naturally want to enter the G *then* add the sharp.  And that is what the sharp-post command does - adds a sharp to the note you just entered.  This is actually the way the regular sharp command always worked before it was changed a couple of years ago.  Enough people complained bitterly about the change, that a version of the old behavior was reinstated as a new command.  So now people who have the foresight to press the accidental button before entering the note have their command, and those who just don't think that way have theirs.

Not saying it's an ideal situation, but anyhow, it is what it is.

**Comment by quinnouyang** [comment]
Hmm, that makes much more sense, thanks! How do you propose we describe this? Currently `sharp-post` is "Apply accidental retrospectively: sharp" and `sharp` is "Sharp". I think we can do better?

**Comment by MarcSabatella** [comment]
First, again, I'm not 100% sure it was decided to keep these commands at all.  But assuming we do, then it's actually very easy to describe, because the behavior is mostly pretty straightforward: "Apply sharp to selected notes".

The harder part, frankly, is a good description of *regular* sharp command, because it's behavior is so different between normal and note input modes.  "Apply sharp to selected notes in normal mode, or toggle the accidental state for next note in note input mode" doesn't exactly roll off the tongue.

But, we face exactly the same problem for most of the note input commands.  Consider, the actual behavior of the augmentation dot is "apply dot to selected notes in normal mode, or toggle the duration state for next note in note input mode".  Similar for other quarter note button or the voice buttons.

I think the sensible think is to only focus on the note input behavior for all of these.  Right now the duration shortcuts simply say, "Set duration: quarter note", setc.  So logically, the sharp command should be "Set accidental: sharp".  And don't worry too much about the fact that it doesn't *actually* describe what it really does, because there simply is no good one-line description.

**Comment by MarcSabatella** [comment]
@bkunda what do you think?

**Comment by quinnouyang** [comment]
Makes sense! Though `sharp` can also remove on selections too (even though similar commands also imply just adding).

**Comment by MarcSabatella** [comment]
Sssshhh!!!  Yes, it's even more complicated than I stated, but no need to put the entire Handbook page for the command in its one-line summary :-)

**Comment by quinnouyang** [comment]
Hehe yeah, which is why I'm leaning towards "Toggle accidental: sharp" and let users infer its effect on a selection and the note input mode.
