### ISSUE TITLE
[MU4 Issue]Not all VSTs installed are showing up

### ISSUE THREAD

**Issue by LaxVox** [musescore/MuseScore#11524]
When I looked into the VST section in the mixer, only one of my VSTs showed up (the only VST3 version on my machine). Will MU4 not work with VST2 or is it just a work in progress?

Platform: Windows 10

**Comment by KaiVinter** [comment]
MuseScore 4 will only allow to use VST3.
This has been asked before on Discord.

See:
https://discord.com/channels/818804595450445834/818848561047273544/959871100458766406
