### ISSUE TITLE
[MU4 Task] Further minor tweaks to palette layout properties

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11527]
**Task description**
This describes a few minor tweaks to the following palettes: 

### Beam properties
Default palette properties should be: 
Width = 35
Height = 33
Element offset = 0sp
Scale = 1.4
Show grid = ON

<img width="294" alt="Screenshot 2022-05-05 at 3 23 56 pm" src="https://user-images.githubusercontent.com/86290556/166867889-8bcd9b9f-3fd5-4852-b0e9-330f19e5edd9.png">

### Key signatures
Make default height = 47

### Clefs
Make default height = 55 

### Bagpipe embellishments
Set show grid = ON

### Time signatures
Set show grid = ON 

@HemantAntony another minor one if you're interested 😀

**Comment by HemantAntony** [comment]
Working on it

**Comment by HemantAntony** [comment]
@bkunda Do you want me to change the magnification of AUTO? It looks too zoomed in
![image](https://user-images.githubusercontent.com/88136054/166869413-a837f96e-0ba3-4470-9ef8-7b144d752f45.png)

**Comment by bkunda** [comment]
It should match as closely as possible to what I've provided in the attached image (all of these look like they're scaled up too much)

**Comment by bkunda** [comment]
@HemantAntony I've added two more tiny things to the task description (see "bagpipe embellishments" and "time signatures") 🙂
