### ISSUE TITLE
[MU4 Issue] Further palette items appear "greyed-out"

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11529]
**Describe the bug**
Four of the palette items in the "Text" palette are being rendered in a light grey colour, instead of our standard `font_primary–colour`. These are: 

- S/A
- T/B
- T/L
- B/B

<img width="404" alt="Screenshot 2022-05-05 at 8 48 36 pm" src="https://user-images.githubusercontent.com/86290556/166909014-f4adab1d-e176-4d5a-9516-cfa1220a336e.png">

Note this issue likely connects to the discussion raised in https://github.com/musescore/MuseScore/issues/10451, and perhaps might be solved together with implementing this task. 

**Expected behavior**
These items should be rendered in the same colour as all other palette items

**Platform information**
 - MacOS 12.3.1 (M1) 

**Additional context**
See https://github.com/musescore/MuseScore/issues/10451

**Comment by cbjeukendrup** [comment]
@bkunda I think we can close this issue: see #14903 for why these specific elements look "greyed out".
