### ISSUE TITLE
[MU4 Issue] Palette properties dialog - Problems clicking and scrolling

### ISSUE THREAD

**Issue by poypoyan** [musescore/MuseScore#11530]
**Describe the bug**
While working on #11384, I found out that clicking the up and down button on "width" spinbox in Palette properties dialog seems to also 'activate' the "scale" spinbox! For all spinboxes, scrolling can only be done once per focus. This suggests a bug in focus.

This is likely to be P3, so I'll try to fix this.

**To Reproduce**
1. Go to Palettes.
2. Click on 'three dots'.
3. Click on 'Palette properties...'in the context menu.
4. Try to click  'up' and 'down' button on 'width' spinbox (single click and holding mouse button)
5. Also, try to click the textfield in the spinboxes, then scroll up or down.

**Expected behavior**
Spinboxes should work as expected.

 **Screenshots**

https://github.com/musescore/MuseScore/assets/90187801/0eec7696-760b-4f0f-98b4-cde01223a0e4

**Platform information**
Windows

**Comment by poypoyan** [comment]
@Tantacrul Hi! Apologies for this late reply. I cannot work on all open-source projects I normally contribute.

Upon looking on this problem, I have no idea on how to fix this bug. This palette dialog is implemented in "PalettePropertiesDialog.qml" and uses so-called "Repeater" to generate the 4 "spinbox" options. This repeater looks alright to me. Apologies for this.

**Comment by DmitryArefiev** [comment]
Added video to the description (the current state in 4.2 master)
