### ISSUE TITLE
[MU4 Issue] Section of Font face in Preferences goes blank

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#11532]
**Describe the bug**
Under the right conditions, a part of the font face dropdown go blank on scrolling

**To Reproduce**
1. Go to Preferences
2. Click on the dropdown near Font face
3. Scroll down fast and then suddenly scroll up
4. You will be able to see a blank space

**Expected behavior**
Font face dropdown should not have blank sections

**Screenshots**

https://user-images.githubusercontent.com/88136054/166938529-a15aa322-0c05-469f-adc1-b8c825b479ac.mp4

**Platform information**
 - OS: Windows 11

**Additional context**
This bug seems a bit random. Also note the extra scroll bar

**Comment by the-next-ceo** [comment]
In mac, the blank section does not exist but yeah the problem with the duplicate scroll bar do exist.

**Comment by HemantAntony** [comment]
> In mac, the blank section does not exist but yeah the problem with the duplicate scroll bar do exist.

There are no correct instructions to reproduce this. Maybe you might not have done the correct things. But I think it does exist since Tantacrul assigned and added labels

**Comment by HemantAntony** [comment]
@the-next-ceo Actually I updated the steps to reproduce now. Turns out I was doing something and I did not realise it

**Comment by the-next-ceo** [comment]
https://user-images.githubusercontent.com/66167731/167182290-5087294f-641c-484e-ba85-a7d8fdcf48d3.mov

@HemantAntony see i tried to follow ur steps (scrolling fast up&down) but I didn't observe any of the mentioned issue.

**Comment by Eism** [comment]
@HemantAntony 
I also can't reproduce on master

**Comment by Tantacrul** [comment]
I can't reproduce it either. @HemantAntony - test to see if this is still happening for you.

I've reprioritised as a P3 because this isn't really a big deal and very few people are able to see it (so far)

**Comment by HemantAntony** [comment]
I can't reproduce in the latest master. But I was able to do so like yesterday. So I'll close this issue

**Comment by cbjeukendrup** [comment]
I think this is a QML issue. It is not reliably reproducible, but I have experienced it with various ListViews. The problem is that QML fails to render the items fast enough (they are unloaded whenever they are scrolled out-of-view, and need to be recreated just before they become visible). 

Since _we_ can't do anything about this, let's keep this issue closed.
