### ISSUE TITLE
[MU4 Issue] [GP] 'Slide in' and 'Slide out' marks are not rendered in MU4 after importing

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11540]
**Describe the bug**
Slide marks to fix:
- Slide in from below
- Slide in from above
- Slide out downwards 
- Slide out upwards

**To Reproduce**
1. Open test GP file in MU4
[test tab for MU4.gp.zip](https://github.com/musescore/MuseScore/files/8635775/test.tab.for.MU4.gp.zip)

2. Pay attention to the 13-14 measures

**Screenshots**
![Capture 2022-05-05_11-12-52_PM](https://user-images.githubusercontent.com/101250347/167017952-5256cb9e-13c9-4df9-8b67-f46eb65f39f6.png)
![Capture 2022-05-05_11-10-31_PM](https://user-images.githubusercontent.com/101250347/167017960-9583962c-4a5a-402e-8779-4a99defd03bb.png)

**Expected behavior**
All elements are rendered according to the imported file
![Capture 2022-05-05_11-10-50_PM](https://user-images.githubusercontent.com/101250347/167018011-a6ae25ea-b2bc-423f-b773-02e67506b6b0.png)

**Comment by Tantacrul** [comment]
Hey @boryskuzmenko - I notice in that screenshot that the tab numbering looks quite bad. First, the font is wrong, which is making it harder to read. It seems like the correct style for tab numbering isn't being used. If this isn't already logged as an issue, can you log it?

Your image:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/21022311/167298216-705e3d3b-92a0-4247-927a-f40afa1e53b7.png">

MS4 (normal style)
<img width="405" alt="image" src="https://user-images.githubusercontent.com/21022311/167298253-0905e101-3dc4-4b04-9583-1828bdf45e04.png">

**Comment by boryskuzmenko** [comment]
** Can't reproduce**
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by boryskuzmenko** [comment]
The issue is still reproducible for TAB staves
