### ISSUE TITLE
[MU4 Issue] Reinstate drag-and-drop interaction for SoundFont installation

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11549]
**Describe the bug**
In MS3.6, it was possible to install a SoundFont by dragging and dropping it into the main score window. This interaction has been lost in MS4 and is therefore a regression.  

**To Reproduce**
1. Drag and drop a SoundFont into the MuseScore 4 main window
Nothing happens

**Expected behavior**
This interaction should work as per MuseScore 3.6 (see videos):

1. Installing a SoundFont for the first time 

https://user-images.githubusercontent.com/86290556/167135182-dc184b6c-2c66-4bdb-9706-b156b9441897.mov

2. Messaging when a SoundFont has already been installed 

https://user-images.githubusercontent.com/86290556/167135311-f8550032-fa1e-4e02-89b4-8b293f866042.mov

3. Dialogs will obviously require updating. Please use the below as references for updated microcopy: 

<img width="452" alt="Frame 137" src="https://user-images.githubusercontent.com/86290556/167135409-51642cd5-4aca-4003-bd1a-d013f07d50be.png">

<img width="431" alt="Frame 138" src="https://user-images.githubusercontent.com/86290556/171150824-b0b9e433-0343-4c12-8e84-c85996e440c3.png">

<img width="527" alt="Frame 139" src="https://user-images.githubusercontent.com/86290556/167135481-f290c7ec-b190-4de9-831e-d6e18a8ba390.png">

**Platform information**
 - MacOS 12.3.1 (M1) 

Thanks!

**Comment by Tantacrul** [comment]
@bkunda slight tweak: I think that second dialog could perhaps say:

**Soundfont installed. You can assign soundfonts to instruments using the mixer panel**

**Comment by bkunda** [comment]
> **Soundfont installed. You can assign soundfonts to instruments using the mixer panel**

Agreed. I've updated the issue description accordingly.

**Comment by RobFog** [comment]
> > **Soundfont installed. You can assign soundfonts to instruments using the mixer panel**
> 
> Agreed. I've updated the issue description accordingly.

Shouldn't this complete sentence end with a full stop?

**Comment by bkunda** [comment]
yes quite right. I've updated the mockup.
