### ISSUE TITLE
[MU4 Issue] Preferences>Appearance>Font face dropdown UI issues

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11548]
The remaining minor issues from #11366

 https://github.com/musescore/MuseScore/pull/11366#issuecomment-1119510212 :

1. Once clicking on the drop down, a single frame flashes before seeing the current font being selected. Focus on it and notice (Windows only)

https://user-images.githubusercontent.com/90187801/167123895-0d4f13c1-f9df-4579-880e-9e9f39266adc.mp4

2. Drop shadow looks off, there is a cut out line around the shadow:

![167121801-a1149e03-97a4-4fca-8a6f-a4e3e8b5ee5b](https://user-images.githubusercontent.com/90187801/167124418-c005d0d2-83ee-4361-93f0-286471340a5b.png)

**Comment by jessjwilliamson** [comment]
> > 2. Drop shadow looks off, there is a cut out line around the shadow
> 
> @jessjwilliamson Can you check this on you screen as well please? (in the next master) Thanks!

It's definitely less harsh, but there is still some line/edge. I think the 'blur' of the dropshadow is spread too far, just anything to solve this 'line' :) 
![image](https://user-images.githubusercontent.com/71656189/168122478-683d9b5b-5dc1-4548-9900-faadd638606f.png)

**Comment by DmitryArefiev** [comment]
> > > 2. Drop shadow looks off, there is a cut out line around the shadow
> > 
> > 
> > @jessjwilliamson Can you check this on you screen as well please? (in the next master) Thanks!
> 
> It's definitely less harsh, but there is still some line/edge. I think the 'blur' of the dropshadow is spread too far, just anything to solve this 'line' :) ![image](https://user-images.githubusercontent.com/71656189/168122478-683d9b5b-5dc1-4548-9900-faadd638606f.png)

@jessjwilliamson Thanks for checking!  @Eism Told me he will tackle this in the next PRs  :)
