### ISSUE TITLE
[MU4 Issue] No any instrument to choose in New Score or Instruments dialog windows

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11552]
https://user-images.githubusercontent.com/90187801/167160707-7b486d08-4e80-4ef3-acac-1b2b8c43140a.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Recent builds

**Comment by Tantacrul** [comment]
Confirmed on both my Mac and PC

**Comment by donarturo11** [comment]
@Eism I built Musescore from your branch and ran with no problem. Thank you very much. I think, that your solution totally fixed this issue. I must now wait to merge your code to master branch for resolve issue #11331.

**Comment by DmitryArefiev** [comment]
Fixed in #11555
