### ISSUE TITLE
Narrator on MacOS no longer working - breaks keyboard navigation

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11559]
**Describe the bug**
This is a very recent regression from previous versions of MS4 (from last week or the week before). 

- Keyboard navigation works until you turn on the narrator, at which point it stops functioning properly. It seems to keep selecting options that aren't in view and it is impossible to navigate to the right menu item.

https://user-images.githubusercontent.com/21022311/167256590-1af434fe-69f1-4ce7-8f1c-689a13be5c2c.mov

**Comment by Eism** [comment]
@Tantacrul 
Make sure you don't have quick navigation enabled
This mode is currently not supported in MU4

<img width="886" alt="image" src="https://user-images.githubusercontent.com/10116828/167273403-5548eaf2-42c3-499d-8e5c-2da3f0e0e252.png">

**Comment by Tantacrul** [comment]
Thanks @Eism - I had not got the memo about this. I've written a **big** note to myself to include this in documentation
