### ISSUE TITLE
Linked staves: TAB does not update when notation is altered

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11568]
**Describe the bug**
This is true for templates and when you create a new score and set up a linked stave manually. When working with a notation + (linked) tab, the tab will look fine when you first enter notation but does not update when you change anything (see video).

https://user-images.githubusercontent.com/21022311/167298140-471483b2-4ea4-4bcd-9ced-5c311b739597.mov

@boryskuzmenko - I didn't see this logged anywhere else. Is it a regression on previous builds?

**Comment by boryskuzmenko** [comment]
@Tantacrul Yep, looks like regression
As I see @alexpavlov96  is already working on it ))

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
