### ISSUE TITLE
Guitar tab numbering should default to Sans Serif in all cases

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11569]
**Describe the bug**
This will be a very easy win for the appearance of our guitar tablature.

Comparing our 'Simple' tab style to our 'Common' tab style reveals that we are using different styling for tab numbering. The style used for 'Common' is far less easy to read and uglier than 'Simple'.

I created a poll to see if others agreed (which so far, they do)
https://twitter.com/Tantacrul/status/1523297155837956096

I think a very easy win for tab engraving would be to always use the font style and size of 'Simple' in all cases. This will also help us to match the appearance of Guitar Pro, who use a similar style.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/21022311/167299870-f39fdb43-96af-4c28-9eca-16ad33aac41e.png">

**Comment by Tantacrul** [comment]
You can alter this setting by right-clicking on the measure and choosing 'Staff/Part Properties'

<img width="653" alt="image" src="https://user-images.githubusercontent.com/21022311/167304686-311ac2d9-fc60-441e-bbfb-d221fe163c49.png">

Tab Sans should always be chosen by default for all tab.

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
