### ISSUE TITLE
[MU4 Issue] page size stuck on metric

### ISSUE THREAD

**Issue by hackbar** [musescore/MuseScore#11573]
**Describe the bug**
After changing the page size to inches, it will be in metric the next time you open the page settings dialog.

**To Reproduce**
1. Create a new score, from the template, "Treble Clef".
2. Open Page Settings.
3. Set units to inch.
4. Set the size to 7.75 inches width, 5.50 inches height.
5. Hit OK.
6. Open the page settings dialog.
7. See the units in metric.

**Expected behavior**
Units should stay in inches, as they were set to.

**Platform information**
 - OS: Linux & MacOS

**Additional context**
OS: Ubuntu 20.04.4 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2288470234, revision: github-musescore-musescore-cfce3e5

**Comment by Tantacrul** [comment]
Confirmed. Nice spot! @hackbar 

<img width="825" alt="image" src="https://user-images.githubusercontent.com/21022311/168443700-7eb16199-d77d-439f-9e4c-d49cbb378230.png">

**Comment by HemantAntony** [comment]
@Tantacrul I created a PR: #15974

**Comment by bkunda** [comment]
🟢 Re-tested in 4.0.2. Remains FIXED.
