### ISSUE TITLE
[MU4 Issue] No instruments in New Score window

### ISSUE THREAD

**Issue by donarturo11** [musescore/MuseScore#11575]
**Describe the bug**
No instruments in New Score window

**To Reproduce**
1. Go to 'File > New...'
2. Click on eg. 'Woodwind' from 'Family' column
3. No instrument appears

**Expected behavior**
After click on instrument family, instrument names should appear in 'Instruments' column

**Screenshots**
![NewScore-window](https://user-images.githubusercontent.com/6421054/167405440-08760324-64b5-4416-bb09-753d20bd5850.png)
![NewScore-window](https://user-images.githubusercontent.com/6421054/167405471-c45cf1b7-2bd3-4a2a-892d-43d8b8fabd33.png)

**Platform information**
 - OS: Linux

**Comment by HemantAntony** [comment]
Does this occur only when you build MU4? No instruments is shown at all, right?

**Comment by HemantAntony** [comment]
If so check https://discord.com/channels/818804595450445834/939880479887327302/957270176032768050

**Comment by jessjwilliamson** [comment]
Oh that's not good! Thanks for pointing it out!

**Comment by donarturo11** [comment]
@HemantAntony I built with CMake.

**Comment by donarturo11** [comment]
> Duplicate of #11552 @donarturo11, could you test the build from #11555

Sorry! I didn't found.
