### ISSUE TITLE
[MU4 Issue] Linux VST Gui does not open

### ISSUE THREAD

**Issue by diedeno** [musescore/MuseScore#11592]
**Describe the bug**
Ubuntu 20.04 LTS
In mixer, when choosing a (any) VST, the VST GUI does not open.
All MS4 versions (alpha and nightly)

1. Go to Mixer
2. Choose any VST
3.  Score plays OK, but GUI does not open. 
(With VST's where an instrument has to be chosen first, such as Decentsampler, of course here is no sound)
5. See error

**Expected behavior**
VST UI opens when selecting in Mixer

**Screenshots**
N/A

**Platform information**
 - OS:= Linux Ubuntu 20.04 TLS

**Additional context**

**Comment by llui85** [comment]
I can also reproduce this on `Linux 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux`. In the terminal, I see the following logs:

```
SurgeXT VST3
  - Version      : 1.0.1.60228e8 with JUCE 60102
  - Build Info   : 2022-01-31 17:08:57 using GNU-7.5.0
  - Data         : "/usr/share/surge-xt"
  - User Data    : "/home/me/Documents/Surge XT"
22:18:48.499 | INFO  | 140415747712768 | VstAudioClient | setUpProcessData: BusIndex: 0
22:18:48.500 | INFO  | 140415747712768 | VstAudioClient | setUpProcessData: BusType: Main
22:18:48.500 | INFO  | 140415747712768 | VstAudioClient | setUpProcessData: BusFlag: DefaultActive
22:18:48.500 | INFO  | 140415747712768 | VstAudioClient | setUpProcessData: BusIndex: 1
22:18:48.500 | INFO  | 140415747712768 | VstAudioClient | setUpProcessData: BusType: Main
22:18:48.500 | INFO  | 140415747712768 | VstAudioClient | setUpProcessData: BusFlag: ControlVoltage
22:18:48.500 | INFO  | 140415747712768 | VstAudioClient | setUpProcessData: BusIndex: 2
22:18:48.500 | INFO  | 140415747712768 | VstAudioClient | setUpProcessData: BusType: Main
22:18:48.500 | INFO  | 140415747712768 | VstAudioClient | setUpProcessData: BusFlag: ControlVoltage
22:18:48.500 | INFO  | 140415747712768 | VstAudioClient | setUpProcessData: 0 active input buses, activating default bus
22:18:48.500 | WARN  | 140415747712768 | VstSynthesiser | setupSound: Not supported!!
```

**Comment by Jon0** [comment]
Same issue, I compiled with the hasNativeEditorSupport set to true, now it opens: https://github.com/Jon0/MuseScore/tree/Enable_vst_editor

**Comment by Tantacrul** [comment]
@DmitryArefiev - are you able to reproduce this?

**Comment by vpereverzev** [comment]
VST GUI for Linux is not supported in MU4, since VST requires separate event loop

I'm pretty sure it was mentioned by @Tantacrul in a couple of previous announcements
