### ISSUE TITLE
[MU4 Issue] Vague MIDI assigning info in MIDI Device Mappings

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#11600]
So far, when assigning a note with a MIDI controller/keyboard, it is displayed as 'Note XX'. For example, Note C4 on the keyboard. It is able to recognise any note in any octave.

![image](https://user-images.githubusercontent.com/71656189/167876804-fb7ecc13-7a36-44eb-9ee3-f6d7b9995531.png)

However, with other buttons on a MIDI keyboard such as a play or stop button, they are all labelled as 'Controller 0'. If they have a MIDI CC attached to it, it would be good to show the MIDI CC number value instead of 'Controller 0'.

Example, I have a Novation Impulse keyboard, I want to assign the play score button on MS4 to the play button on the Novation keyboard. Doing, this, MIDI Device Mappings recognises this button as 'Controller 0'. This label also shows up in other different buttons as well.

![image](https://user-images.githubusercontent.com/71656189/167876853-a6c1724a-66bd-48fa-90a6-13405d3507ec.png)

**Comment by Tantacrul** [comment]
@jessjwilliamson  can you show what another program displays when you enter the same information there?

**Comment by jessjwilliamson** [comment]
> 

Yes of course! Ableton is good example:
Here I'm using the Novation Impulse.
I've mapped stop, start and record buttons on the Novation keyboard, with the stop, start and record buttons on Ableton.
What it's showing that:
CC114 is stop
CC115 is start
CC117 is record.

These CC values are from the Novation. So it would be clearer instead of having 'Controller 0' everywhere.

So on Musescore, it'll be showing something like example 'Novation Impulse > CC114' not 'Novation Impulse > Controller 0'
![image](https://user-images.githubusercontent.com/71656189/168051120-fa8cb32e-6ec7-40be-9e94-d76d1219ce92.png)


Expected: 
![image](https://user-images.githubusercontent.com/71656189/168054192-b12eb254-1a47-4cfd-b5b9-a23b40c8d967.png)

**Comment by Eism** [comment]
@Tantacrul @jessjwilliamson @abariska 
Hm, I disabled controllers assigning when I fixed https://github.com/musescore/MuseScore/issues/13028

So, should we support such a assigning?

**Comment by Tantacrul** [comment]
> @Tantacrul @jessjwilliamson @abariska Hm, I disabled controllers assigning when I fixed #13028
> 
> So, should we support such a assigning?

In this particular instance, I would say yes. I'm uncertain how the two are exactly related - apart from the involve MIDI CC events. Does fixing this unfix the other problem?

**Comment by abariska** [comment]
As was discuss with @Eism regression with midi CC events assigning to be fixed in scope of this issue.

**Comment by Eism** [comment]
@jessjwilliamson 
Could you test the build from https://github.com/musescore/MuseScore/pull/14386 ?
