### ISSUE TITLE
[MU4 Issue] "None" is the not the correct key signature for the new score wizard

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11618]
When creating a new score via File / New, the default key signature is reported as "None".  This is not correct, it is actually "C major".  "None" isn't really a thing, but I notice that the "open/atonal" key signature - which is what I'd have assumed "none" to refer to - is missing.  So the dialog *looks* like it is applying the open/atonal key signature, but it isn't - it's applying C major.  The difference being, a key signature of none or open/atonal should remain as such even when adding transposing key signatures.

So:

a) the default in the dialog should be the one labeled C major
b) there should also be one labeled "open/atonal" (and it should not be mixed in with the others - probably it should be last in the list)
c) the one labeled "none" should be removed

I would say the one labeled "none" should simply be relabeled "open/atonal" and fixed to actually work that way.  but I'm guessing the actual arrangement of keys within the dialog is kind of deliberate, with the default in the middle.  That much I have no problem with.  And the open/atonal one shohdl not be mixed up on the middle with the ordinary ones.

**Comment by Tantacrul** [comment]
I had not realised 'none' was acting like C Major.

- Rename **none** to **open/atonal**
- Make sure it references the correct key signature seen in the New Score Wizard in MuseScore 3 (which is called **open/atonal**)
<img width="966" alt="image" src="https://user-images.githubusercontent.com/21022311/168124122-34c43e0b-5d74-4692-9a8b-0fff152e7f7f.png">
- Make the default C major
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/21022311/168124554-7e082059-668a-4074-95b2-fd6b50b256fe.png">

--

So, the popup would look like this by default:
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/21022311/168127042-aab77373-c879-4f76-abb2-d323069ee6ef.png">

**Comment by cbjeukendrup** [comment]
@Tantacrul Maybe this is a strange comment, but to me it would feel more natural to have the key sigs with sharps in the top row, and the flats at the bottom. Is there a reason to have them like they are now?

**Comment by Tantacrul** [comment]
I have zero problems with that (as long as C Major is at the top left!)

Agreed!

**Comment by sammik** [comment]
I tried to fix this, but I am stuck.
I think, Atonal key is defined as `KeyMode::NONE`.
But I dont know, how are theese setings transfered from dialog to new score.
I added it to additionalinfomodel.cpp. In newscoremodel.cpp it is still present. 
But in created score, it is missing.
Any hint please? Thank You!
