### ISSUE TITLE
[MU4 Issue] Dropdown lists in Preferences don't close when dragging the window

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11619]
https://user-images.githubusercontent.com/90187801/168120844-4e7b1245-6d43-47de-87f2-2226bf559c35.mp4

**Platform information**
**macOS, Windows**
Can't reproduce on Linux

**Comment by the-next-ceo** [comment]
https://user-images.githubusercontent.com/66167731/168144681-a93d2b4b-babb-4c39-9d9f-a1b4e361c820.mov

it doesn't seem that issue exists in MacOs.

**Comment by rgreen5** [comment]
Related issue in Linux, #10993.

**Comment by DmitryArefiev** [comment]
> Screen.Recording.2022-05-13.at.12.02.56.AM.mov
> 
> it doesn't seem that issue exists in MacOs.

@the-next-ceo Thanks for rechecking! That's just a new bug, and present only in today's hightly build

**Comment by DmitryArefiev** [comment]
Fixed in #11654
