### ISSUE TITLE
[MU4 Issue] system/ifilesystem.h is nowhere to be found

### ISSUE THREAD

**Issue by RmGkAppDev** [musescore/MuseScore#11628]
Hello everyone!
I'm new to this project and I'm trying to build it for the first time, while building it, I've noticed that there is a missing file:
`system/ifilesystem.h`
The error comes from the file: `\src\framework\audio\audio.vcxproj`
From further investigations, I've found out that inside the `audioconfiguration.h` file, there is an `#include` that calls for the missing file.

I just cloned the project and followed the steps here: https://musescore.org/en/handbook/developers-handbook/compilation/compile-instructions-windows-visual-studio#1._Prerequisites
(Please note that I did not build the project using Visual Studio, but it happened there too. I used the following command: `cmake -P build.cmake -DCMAKE_BUILD_TYPE=Release`)

Is the file missing because of something that I have done wrong? or is it because there is a bug on the master branch?

Needless to say that this is the only error and the building process was unsuccessful
(The full log from the building process is the following: [Unsuccessful Building Process.log](https://github.com/musescore/MuseScore/files/8690159/Unsuccessful.Building.Process.log))

**Comment by cbjeukendrup** [comment]
@RmGkAppDev There's indeed a problem on the latest master branch! I'll fix it asap.

**Comment by RmGkAppDev** [comment]
The exact error is the following:
`fatal error C1083: Cannot open include file: 'system/ifilesystem.h': No such file or directory`

**Comment by RmGkAppDev** [comment]
Wow, that was quick!!!

**Comment by cbjeukendrup** [comment]
Now, let's double-check that this makes the continuous integration tests happy, and then I'll merge the fix directly. After that, you can pull/rebase on the latest master branch and everything should be fine!

**Comment by RmGkAppDev** [comment]
Thanks a lot! Happy to help with your amazing project!
