### ISSUE TITLE
[MU4 Issue] Switching view (Page view -> Continuous view etc.) should work independently for score and parts 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11621]
https://user-images.githubusercontent.com/90187801/168129478-f4d1f2c3-f3e8-4692-b722-a7bc29a4b009.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
The same was fixed for zooming/scrolling in #7879
Doesn't occur in **MU3**

**Comment by martin-danhier** [comment]
Hello, I can look into it this weekend if you want.

Also, unlike the zoom/scroll state, the view mode (page/continuous/...) is saved in the mscz file and restored when loading a project. I assume we will thus now need to save the view mode of each part as well? (with backward compatibility for old files)

**Comment by igorkorsukov** [comment]
Dev notes
We would be do like: 
Score.mscz\
    Excerpts\ 
        Part\
            Part.mscx
            style.mss
            viewsettings.json
            audiosettings.json
            ...

that is, we can add another nesting in the Excerpts and make their structure similar to the main score

**Comment by RomanPudashkin** [comment]
@Tantacrul FYI

@DmitryArefiev and I decided to move this issue to POST-BETA (with the P0 priority) because it requires some significant changes in the file structure (see https://github.com/musescore/MuseScore/issues/11621#issuecomment-1271377164). But we definitely have to do this work before the POST-BETA release

**Comment by Tantacrul** [comment]
100%

This is not a blocker at all. I also think it's still a P1... but let's leave it for now :)

**Comment by RomanPudashkin** [comment]
@Tantacrul I have moved this issue to the RELEASE project. The problem itself isn't so critical, but it requires global changes in the mscz structure, so we have to do these changes before releasing the app

**Comment by Tantacrul** [comment]
> @Tantacrul I have moved this issue to the RELEASE project. The problem itself isn't so critical, but it requires global changes in the mscz structure, so we have to do these changes before releasing the app

Understood. Thanks!

**Comment by DmitryArefiev** [comment]
Fixed in #13971
