### ISSUE TITLE
[MU4 Issue] Languages list in Preferences is empty on Linux

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11620]
**To Reproduce**
1. Go to Preferences>General
2. Click on Languages field - **it's empty**

![preferences](https://user-images.githubusercontent.com/90187801/168122770-2b939fdc-4c0e-48e3-a9fc-373db7fab18c.png)

**Platform information**
**Linux only**

**Additional context**
Other languages issues in Preferences:
#11432
#11432

Probably it's because of missing MU4 translations (all platforms)

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2478704457, revision: github-musescore-musescore-594ee1a

Confirmed. No English (GB) or English (US) options.

**Comment by DmitryArefiev** [comment]
In master build (on Linux) the language list is not empty anymore, but the first time your open Preferences the field is empty (nothing is selected). The second issue will be fixed in #12474

**Comment by DmitryArefiev** [comment]
> In master build (on Linux) the language list is not empty anymore, but the first time your open Preferences the field is empty (nothing is selected). The second issue will be fixed in #12474

Since the **main issue (the language list is empty) is FIXED in master** and there is another issue related to blank field #11430 let's close the current.
