### ISSUE TITLE
Fingering: Issue with excess spacing compared to MS3

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11635]
**Describe the bug**

In MS3 it was possible to add a string tuning indication to the start of a guitar score. This could be created by adding a string number and staff text to the first note, then dragging them into position to the left. (see attached score and screenshots below). However this method does not work in MS4 unless you turn off autoplacement.

**To Reproduce**

1. Open the attached MS3 score and compare it to the original appearance in MS3. 
[fingering_test_file.zip](https://github.com/musescore/MuseScore/files/8692741/fingering_test_file.zip)

2. Try to create the tuning indication in both versions and compare the process.

**Expected behavior**

The string tuning indication imported from MS3 should remain roughly the same. The autoplacement behaviour appears to have changed in MS4. Is this correct?

**Screenshots**

MS3 versus MS4:

![string_tuning_ms3](https://user-images.githubusercontent.com/87246583/168421790-a0a973c7-fc5d-4762-bcad-ca2aca936c0f.png)![string_tuning_ms4](https://user-images.githubusercontent.com/87246583/168421798-36c11c96-8dae-4d3f-ba35-b771f433aea3.png)

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2322935308, revision: github-musescore-musescore-c77bf9c

**Comment by cbjeukendrup** [comment]
Yes, the autoplace behaviour was changed. Generally the new behaviour makes more sense, but it obviously breaks this use case. Maybe @oktophonie and @mike-spa can comment.

**Comment by Tantacrul** [comment]
I'll let @oktophonie prioritise this.

**Comment by rgreen5** [comment]
Workaround: Set "Leading" to a negative value.

**Comment by mike-spa** [comment]
Ah yes, this happens because the new spacing system generally avoids items "tucking" above/below time signatures, with rare exceptions. In principle I just need to add this exception, should be a very quick fix. Thanks :)
