### ISSUE TITLE
[Properties Panel] X & Y Offset values are broken for text and lines

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11637]
**Describe the bug**
When changing X and Y values for a text (or line) element and then de-selecting and re-selecting it, the positions are often incorrect. Also, resetting the position of a text element, it will only reset the Y or X but not both, resulting in an incorrect position.

See video

https://user-images.githubusercontent.com/21022311/168443082-07782127-0128-416c-808f-fdd771f41e5d.mov

**Comment by Tantacrul** [comment]
I've altered the issue description a little because the issue is a little bit larger and more universal than originally suggested. I've added a video too.

**Comment by rgreen5** [comment]
See also [Manual fingering placement made with Inspector changes after layout](https://musescore.org/en/node/308212) (MS3).

**Comment by Tantacrul** [comment]
This issue now seems to be fixed after we solved similar issues in **Alpha 2**. Please let me know if anyone experiences this again and I'll reopen.
