### ISSUE TITLE
No capo playback

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11631]
MuseScore 3 had a feature where you could set staff text properties that would cause playback to be  one or more semitones higher, mimicking a capo.  The dialog still has this setting, but it does nothing, and indeed, any setting made is lost if you revisit the dialog.  So far all I know, the

To reproduce:

1) enter middle C in a score
2) add a staff text "capo 3"
3) got to Staff Text Properties
4) on the Capo tab, enable the capo and select 3
5) hit OK
6) play

Result: still plays as a C.  If you then go back to the dialog, the capo is disabled again.

I should mention, the more or less unrelated (!) capo feature in Format / Style / Chord Symbols works fine for the display of chord symbols, so don't confuse this bug report on the staff text properties feature with the chord symbol style feature of the same name.  My personal recommendation for 4.0 is to just fix the staff text properties bug, but ASAP afterward, as part of the "improved experience for guitarists", rip all this out and replace it with something more well-thought-out.

**Comment by Tantacrul** [comment]
I swear this was working recently!

**Comment by bkunda** [comment]
I might just add some detail to this issue: not only does the application of a capo setting not work as intended, but it also seems to produce some unintended octave transpositions of certain notes (depending on the capo setting specified).

https://user-images.githubusercontent.com/86290556/217246839-9f56fe72-fd04-4feb-85ef-6389d0308b24.mov

This is the same problem @abariska identified in [#14937](https://github.com/musescore/MuseScore/issues/14937), but it affects an even wider range of notes than is specified there.  

Even worse, if you happen to delete the stave text to which the capo setting is applied, the unexpected octave transpositions persist (and you have to rely on the undo command to correct them). 

To my mind, this effectively renders capo playback completely unusable at the moment, and I'd also suggest this issue (together with [#14937](https://github.com/musescore/MuseScore/issues/14937)) should maybe be bumped back up to a higher priority. 

Worth pointing out that we do have plans to re-design this particular feature (espeicially to improve its discoverability), so I wouldn't want to devote any more time to fixing it than is required. But it strikes me that the underlying functionality re: playback still needs to be fixed, regardless of how and where these settings are accessed. @Tantacrul what do you think?

**Comment by rgreen5** [comment]
Just a few more observations. At a capo setting of 1 or 2, the notes are unaffected. If you apply higher settings than this (3 and above), the effect is chaotic, with some notes being transposed, others not, and others seem to be transposed incorrectly.
