### ISSUE TITLE
String numbers ("Fingering" palette): icons have no circles around them

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11632]
**Describe the bug**
String number icons in the "Fingering" palette have no circles around them. This does appear OK once the number is applied to the score, but it needs to be be visible in the palette as well.

**To Reproduce**

1. Open any score.
2. Add a Fingering palette to the workspace (if not already there)
3. Open the palette and inspect the string numbers .
4. Now apply a string number to the score.

RESULT: No circle around string number in palette. But circle is visible, as expected when applied to the score

**Expected behavior**

By default, string number icons in a palette (and on the score) should have a circle around them (as in previous MS versions)

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2322935308, revision: github-musescore-musescore-c77bf9c

**Comment by Tantacrul** [comment]
I'm seeing circles in the build I've got (MacOS).

Could you possibly go to **Help>Revert to Factory Settings** to see if the problem persists?

<img width="297" alt="image" src="https://user-images.githubusercontent.com/21022311/168425958-81c150af-0e63-444f-bd93-b45bb8ccc1e5.png">

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2322935308, revision: github-musescore-musescore-c77bf9c

Curiously, I can't reproduce this now.

**Comment by Tantacrul** [comment]
I'm going to close for now... but we'll keep an eye.
