### ISSUE TITLE
MS3 scores open even if user tries to interrupt by pressing the close icon

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11633]
**Describe the bug**
When you open an MS3 file, a dialog appears about style improvements. However, the file opens even if you try to interrupt the process by pressing the cross icon.

**To Reproduce**
1. Open the attached MS3 file.
2. When the dialog appears, press the cross icon, in an attempt to interrupt the process.

RESULT (unexpected): The file opens.

**Expected behavior**

The user should be able to stop the file opening by pressing the close button

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2322935308, revision: github-musescore-musescore-c77bf9c

**Comment by cbjeukendrup** [comment]
Is this issue maybe already covered by #10421? Or is that not what you mean?

**Comment by rgreen5** [comment]
Yes, I missed that one. It's the same issue (just the dialog looks different).
