### ISSUE TITLE
Properties: "Appearance" dialog closes when you click away from the MS4 window

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11636]
**Describe the bug**

if you click away from the MS4 onto another running program, say, you expect MS4 to look the same when you click back. However, this is not the case with secondary dialogs from the "Properties" sidebar, for example, which unfurl unexpectedly.

**To Reproduce**

1. Open the attached score. 
[dialogs.zip](https://github.com/musescore/MuseScore/files/8692783/dialogs.zip)

2. Click on the fingering number in measure 2, say
3. In the Properties sidebar, click the "Appearance" button.
4. Now click on another running program and come back to MS4.

RESULT: The Appearance dialogue has closed

**Expected behavior**

MS4 should remain exactly as you left it with the "Appearance" dialog unfurled.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86
_64, MuseScore version (64-bit): 4.0.0-2322935308, revision: github-musescore-musescore-c77bf9c

**Comment by RobFog** [comment]
I think was previously discussed here: https://github.com/musescore/MuseScore/issues/11248#issuecomment-1102750636

I don't know what happened after @Tantacrul's last comment there.

**Comment by Tantacrul** [comment]
Yes, I think this is covered there. Let's close this issue - I've prioritized the other.
