### ISSUE TITLE
[MU4 Issue] Middle Mouse Reproduces Left Mouse Functionality

### ISSUE THREAD

**Issue by hmturnbull** [musescore/MuseScore#11656]
**Describe the issue**
Middle mouse button intermittently adds notes and moves elements when I try to pan around.

**To Reproduce**
1. Open a score
2. Add some notes/other elements
3. Try to pan with middle mouse while the cursor is on an element
 (May take several tries, as the bug is inconsistent)

**Expected behavior**
Middle mouse should pan around the score without interacting with elements.

**Platform information**
 - OS: Windows 10 (64 bit)
 - MuseScore Version: 4.0 Nightly 2022-05-16

**Additional context**
We already have the left mouse button for selecting and moving elements; having the middle mouse reproduce that functionality is both redundant and frustrating.

Most software that involves panning around a page/canvas/etc. reserves the middle mouse button for navigation.  As such, when users want to manipulate elements, they use the middle button/scroll wheel intuitively, and the current functionality makes panning a delicate task when it should be effortless.

**Comment by Tantacrul** [comment]
Did MuseScore 3 use the middle mouse button as you've specified here? (Don't have a 3 button mouse to hand right now)

**Comment by hmturnbull** [comment]
In MuseScore 3, the middle mouse always works identically to the left mouse (affecting elements), as opposed to doing so intermittently as described above in 4.

"Fix #312574: Always dragging with middle mouse button" looks like it was supposed to make it so the middle mouse button could pan without the problem of inadvertently grabbing elements.  Upon testing the functionality in Musescore 4, the commit seems to fix the issue only some of the time.

**Comment by Tantacrul** [comment]
Hmm. I suppose this isn't really a regression on V3 then. It sounds more like an improvement on V3 that hasn't been perfected. I can't access that fix you mentioned... (I think there's one digit too many). Who did it? Perhaps we can ask them to try and resolve this issue.

**Comment by cbjeukendrup** [comment]
This is the commit: https://github.com/musescore/MuseScore/pull/7393/commits/59796b9d788e2e23aea1328cf1c2c6f61e9097e4 (from PR #7393)

It was working back then, but somehow has been broken again.

**Comment by Tantacrul** [comment]
Ah! 

Well, in that case, @cbjeukendrup, if it is trivial to fix, then let's do it. However, I think we should focus on Alpha bugs for the moment. I'll move this to Beta. In your opinion, is P3 the right severity?

**Comment by cbjeukendrup** [comment]
Yes, that's okay!

**Comment by DmitryArefiev** [comment]
Fixed in #15037

**Comment by DmitryArefiev** [comment]
Retested on Win10
