### ISSUE TITLE
[MU4 Issue] unable to select by Shift + Arrows right after left note input mode

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#11666]
**Describe the bug**
When user leaves note input mode, Shift + Arrows dont work.

**To Reproduce**
1. Write some notes
2. Leave note input mode (press Esc, or n)
3. Try to select more notes - Shift + Left, or Shift + Right
4. Nothing happens

**Expected behavior**
I expect adding notes to selection.

**Screenshots**

https://user-images.githubusercontent.com/1646034/168896031-c41b4382-9592-463e-956c-be08119b1406.mp4

**Platform information**
 - OS: [tested on Linux]
 (also occurs on Win/Mac)

**Additional context**
Only right after left note input mode. I press arrows first, Shift + Arrow than works. (See video)
Doesn't occur in **MU3**

**Comment by DmitryArefiev** [comment]
Can reproduce it on Mac/Windows as well. Also that doesn't occur in **MU3** (will add some details to the description) 
Laving with P2 and Beta1.

@sammik Thanks for logging!

**Comment by DmitryArefiev** [comment]
Fixed in #12724
