### ISSUE TITLE
[MU4 Issue] Right after opening the score, the first playback always starts from the beginning even if some element is selected

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11674]
**To Reproduce**
1. Open a score
2. Select a note not in the first measure
3. Start playback - **it starts from the beginning and not from the selected note** (see the video to compare with MU3)

https://user-images.githubusercontent.com/90187801/169038345-3f086ee9-84f4-4b2c-8d70-68043d2320e0.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by cbjeukendrup** [comment]
@RomanPudashkin This is caused by `PlaybackController::m_needRewindBeforePlay`. If I remove that, it seems to work properly. Could you tell me what's the purpose of this member? It seems like you added it in 1dc2cc0876da1946c99526193b0c89e665c8e665.

**Comment by DmitryArefiev** [comment]
Fixed in #12663
