### ISSUE TITLE
[MU4 Issue] Note is not selected on linked staff after had been selected on the main staff

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11677]
**To Reproduce**
1. Open any score
2. Create a linked staff
3. Select a note on the first of the linked staves
4. Pay attention to the same note on the second linked staff
5. Do the same selecting a note on the second staff

**Screenshots**

https://user-images.githubusercontent.com/101250347/169068369-806a2f48-66d8-40bf-9b18-67745415da01.mov

**Expected behavior**
Note is selected on linked staff after had been selected on the main staff

**Platform information**
 - OS: macOS, Windows, Linux

**Comment by boryskuzmenko** [comment]
> Are you sure this is desired? It doesn't work that way in MU3, and I can easily see one reason why that's a good thing - you might want to change properties of one note but not the other and thus need to be able to select them independently. For example, if you have a note doubled between voices, you will likely want to make the second tab note invisible. Or there might be times you want certain notes on the standard staff to be small but not on the tab staff. Or you may need to adjust the horizontal offset of a notes on the standard staff but not the tab staff.
> 
> It's already the case that for most other operations, the link is honored even though both notes aren't selected. For adding articulations or whatever affects both even though only one is selected. But no doubt, there are times when things don't work as one might expect, and thus room for improvement.
> 
> I'm happy to discuss this further on Discord or the Discussions area here on GutHub or elsewhere if we don't clutter this issue itself.

@MarcSabatella Your point doesn't look as really actual because literally everything is synchronized between linked staves (that's the main purpose of them) except note selecting. So it looks a bit weird not have selection in case when every change in one linked staff is doubled on the second one.

**Comment by Tantacrul** [comment]
I think the desired functionality would need to be moved to 4.x. Agree it makes sense. I do think it may require some extra work. You can still change engraving settings for linked elements (offsets for example) and we'd need to account for that.
