### ISSUE TITLE
[MU4 Issue] Playback - Repeated note articulation ignored

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11684]
**Describe the bug**
When a note is repeated, the articulation is ignored and plays back as staccato regardless of marked articulation. 

**To Reproduce**
1. Open attached score
2. Go to bar 16
3. Play
4. See error in beats 3 & 4 of trumpet parts

**Expected behavior**
Plays back with articulation as noted in score.

**Screenshots**
n/a

**File**
[Fanfare_for_the_Common_Man 2.mscz.zip](https://github.com/musescore/MuseScore/files/8726993/Fanfare_for_the_Common_Man.2.mscz.zip)

**Platform information**
OS: macOS 12.3
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2349650330
revision: github-musescore-musescore-8c123de

**Comment by lengthwave** [comment]
FYI - @Tantacrul

**Comment by Tantacrul** [comment]
This issue seems to have been fixed while we were tackling similar problems for Alpha 2. Closing!
