### ISSUE TITLE
[MU4 Issue] Playback - Cannot Scroll Page Vertically

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11685]
**Describe the bug**
When playing back a score it is not possible to scroll a score vertically, it jumps back to top when mouse is released.

**To Reproduce**
1. Open any score where score extends vertically beyond visible window
2. Click on Play
3. Scroll score vertically while playing

**Expected behavior**
Score should be scrollable vertically and point of focus should remain where user stops scrolling.

**Screenshots**

https://user-images.githubusercontent.com/30370609/169248259-5b686908-48e0-4514-a778-2785df9b570c.mp4

**Platform information**
OS: macOS 12.3
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2349650330
revision: github-musescore-musescore-8c123de

**Comment by lengthwave** [comment]
FYI - @Tantacrul

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/11655
