### ISSUE TITLE
[MU4 Issue] VST on Linux should be blocked since it's not properly supported in MU4.0 release

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11689]
**Describe the bug**
VST is not planned to support in MU4.0.0 release. The critical issue is related to missing VST GUI - #11592, which is not planned to be fixed in the current release.

VST feature should be blocked for Linux users in MU for now.

**Platform information**
Linux

**Additional context**
#11592
#11550
#9481

**Comment by DmitryArefiev** [comment]
@Tantacrul FYI

**Comment by Tantacrul** [comment]
Although our new plugin sampler will work for Linux, VST support is something we will include in 4.1. This will correspond with other VST features that are necessary for high-quality playback.

**Comment by Jon0** [comment]
yabridge (https://github.com/robbert-vdh/yabridge) plugins are already working. yabridge provides the gui event loop so just compiling with the flag to enable the editor to open is enough to have most of my plugins working.
