### ISSUE TITLE
[MU4 Task] [GP] import dives from gp as w/bar line

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#11687]
**Task description**
Import dives from gp as w/bar line 
<img width="683" alt="Screenshot 2022-05-19 at 12 31 19" src="https://user-images.githubusercontent.com/24373905/169261883-b42e5d7c-4c52-475c-9368-755ac7ab7a05.png">

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

Please, merge to master
