### ISSUE TITLE
Can't select word with double-click; or text-block with triple-click

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11691]
**Describe the bug**

In MS3, double click selects a word and triple click a text-block. This does not appear to have been implemented yet in MS4.

**To Reproduce**

Create a new score then try to select the word / text-block of the title by mouse clicks.

RESULT: No effect.

**Expected behavior**

Double click selects a word. Triple click selects the text-block.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2349660861, revision: github-musescore-musescore-8c123de.

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/10242
