### ISSUE TITLE
Text lines: no font or position properties visible in sidebar 

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11690]
**Describe the bug**
In MS3, if you click on a textline, you can clearly see the font and placement properties in the Inspector: e.g.
![ms3_sidebar](https://user-images.githubusercontent.com/87246583/169284602-816a526c-e6a2-4262-9046-de54351fe889.png)

 However, _no font or position properties seem to be visible in the sidebar in MS4_.

**To Reproduce**

1. Unzip and open the attached file in MS4. 
[textline_properties.zip](https://github.com/musescore/MuseScore/files/8728722/textline_properties.zip)
2. Click on the textline to select it
3. Look in the sidebar for any trace of font or position properties.

RESULT (unexpected): _No font or position properties visible_.

**Expected behavior**

Font and position (above / below) properties should be visible in the sidebar. (Contrast this with selecting a Staff text object (for example), where the font and position properties _are_ clearly shown in the sidebar.)

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2349660861, revision: github-musescore-musescore-8c123de

**Comment by Tantacrul** [comment]
We've decided to bump this to 4.x.

For the moment, this should be changed in 'Styles' (which we will also improve in later releases)

<img width="935" alt="image" src="https://user-images.githubusercontent.com/21022311/169384216-173d7929-bd4b-4736-871f-8a5c956c9caa.png">

However, these text styles are not working (in either 4.0 or 3.6), so I'll need to raise an issue about it.

**Comment by MarcSabatella** [comment]
There are indeed a number of text styles where the style dialog isn't hooked up to the right info even in 3.6.  This was logged some time ago as https://musescore.org/en/node/284288.  I did some investigation as shown in the discussion, and @peterhieuvu apparently worked on this some, but it proved annoyingly tricky to solve, for no good reason.

Note in 3.6, it *is* possible to set the text style for text lines via the Inspector and the "S" button.

**Comment by rgreen5** [comment]
The "Position" (formerly "Placement") property can still be set in MS4 using the "X" shortcut, which suggests that "Position (Above / Below)" should also be in Sidebar > Properties.

**Comment by Tantacrul** [comment]
We've lifted that UI element out because it is almost entirely useless and generally just provides a wrong result. Shortcut doesn't bother me, since it is universal. But I've also no problem switching it off for most, if not all text lines.

**Comment by cbjeukendrup** [comment]
It looks like this has been superseded by https://github.com/musescore/MuseScore/issues/14238.
