### ISSUE TITLE
Lines: end anchor on first system wrongly positioned when line continues to next system

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11702]
**Describe the bug**

When a line crosses from one system to the next, the final anchor on the first system appears attached to the wrong note: e.g.
![line_anchor](https://user-images.githubusercontent.com/87246583/169505699-84a9f31e-db08-496e-91bc-4a2c50888bfe.png)

**To Reproduce**

1. Open the attached MS4 file. 
[line_anchors.zip](https://github.com/musescore/MuseScore/files/8738548/line_anchors.zip)

2. Select the line

RESULT: The end anchor appears attached to the wrong note.

**Expected behavior**

The end anchor line should drop down vertically from the end of the first system line (just like in MS3): i.e.
![line_anchor2](https://user-images.githubusercontent.com/87246583/169507399-5354e85a-8a71-4f15-9f8b-004ca8868816.png)

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2356064672, revision: github-musescore-musescore-6eb6034

**Comment by cbjeukendrup** [comment]
To whoever works on this: make sure to coordinate your efforts with whoever works on #16796, to prevent duplicative or conflicting work.
