### ISSUE TITLE
[MU4 Task] Pedal delay in advanced preference

### ISSUE THREAD

**Issue by johnrubensaragi** [musescore/MuseScore#11704]
When exporting a sheet music into a MIDI, the pedal is placed exactly in the start of a note/measure, just as the sheet music says. This might cause some issues when the sheet music is connected to VST. [Someone dealt with this problem by putting the pedal release early](https://github.com/musescore/MuseScore/commit/ea046a230549eaeb04262e8473f358826dbf81b1), but it is incomplete. There should be an option to put the pedal pressing _late_.

**Comment by Tantacrul** [comment]
This will be the kind of thing we'll tackle in 4.1 or 4.2.

Until we finish 4.0, I'm going to place this in waiting as a '4.x' feature request and close for now. Thanks!
