### ISSUE TITLE
[MU4 Issue] Preferences>General>Folders: Crash sometimes when adding or deleting VST directory (Windows only)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11706]
https://user-images.githubusercontent.com/90187801/169540144-c9f40566-3af6-47cf-a81d-713e60348c6e.mp4

**Platform information**
 Windows 10

**Additional context**
Please also notice a little delay when adding VST path (comparing with other fields)
Can reproduce only on Windows

**Comment by DmitryArefiev** [comment]
@boryskuzmenko Can you check on your Windows machine please?

**Comment by boryskuzmenko** [comment]
> @boryskuzmenko Can you check on your Windows machine please?

Couldn't reproduce on macOS and Windows

**Comment by DmitryArefiev** [comment]
@boryskuzmenko Thanks!

**Comment by DmitryArefiev** [comment]
Changing to P3 and Beta2

**Comment by DmitryArefiev** [comment]
Can't reproduce anymore.

Tested in **latest master** on Win10 - **FIXED**  

Closing
