### ISSUE TITLE
Staff instrument not playing back

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11711]
**Describe the bug**

Whether or not you hear a particular staff seems to depend on how you start playback.

**To Reproduce**

1. Open the attached file and play back from the beginning. 
[playback_issue.zip](https://github.com/musescore/MuseScore/files/8741798/playback_issue.zip)

RESULT: The vocal line is not playing back, only the guitar.
2. Now click on the first note in the vocal line and play back from here.
RESULT: The vocal line plays back as well as the guitar.
3. Click on a guitar note that coincides with the first note of the vocal line and play back.
RESULT: The vocal line plays back as well as the guitar.
4. Click on a note in the guitar line just before the first note of the vocal and play back.
RESULT: The vocal line is not playing back, only the guitar.

**Expected behavior**

All lines should play back no matter how playback is initiated.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2356064672, revision: github-musescore-musescore-6eb6034

**Comment by cbjeukendrup** [comment]
It looks like this will be fixed in PR #11709! Could you try out the builds from that one?
