### ISSUE TITLE
No swing playback

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11710]
**Describe the bug**
Even with the swing set correctly on Staff text, swing is not being implemented in playback.

**To Reproduce**

Open the attached score and play back (note: ignore the problem with capo text (#11631). Check the staff text to confirm that swing has been set. 
[playback_issue.zip](https://github.com/musescore/MuseScore/files/8741693/playback_issue.zip)

RESULT: Swing is not audible in playback.

**Expected behavior**

Swing setting are audible on playback.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2356064672, revision: github-musescore-musescore-6eb6034

**Comment by DmitryArefiev** [comment]
Already logged #10972

Closing

Thanks!
