### ISSUE TITLE
[MU4 Issue] Minor fixes for "learn" > "classes"

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11721]
**Describe the bug**
There are a few minor tweaks @MarcSabatella has requested for the "Learn" > "Classes" section (in the "Home" tab).

1. CTA button "Open Mastering MuseScore School" needs its URL corrected as it currently redirects to the wrong site. It should be: https://www.masteringmusescore.com/musescore4. 

2. CTA button should have label updated to read: Open Mastering MuseScore

3. Tag line (beneath the heading "Marc Sabatella") should be updated to read: Creator, Mastering MuseScore. 

4. Body copy should be updated to read as follows: 

Welcome to _Mastering MuseScore_ – the most comprehensive resource for learning the world’s most popular music notation software! My name is Marc Sabatella, and I have been helping develop, support, and promote MuseScore since its initial release over ten years ago.

Whether you are just getting started with music notation software, or are a power user eager to explore advanced engraving and playback techniques, my flagship online course _Mastering MuseScore_ covers everything you need to know to get the most out of MuseScore. In addition, _Mastering MuseScore_ features a supportive community of musicians, with discussion spaces, live streams, and other related courses and services to help you create your best music. Take advantage of this opportunity to learn MuseScore from one of its most recognized experts!

**Expected behaviour**
Updated changes should look like this:

<img width="1920" alt="Learn-NEW 23MAY21" src="https://user-images.githubusercontent.com/86290556/169799724-47f8d6da-22a5-4099-9f59-b8d4219b2747.png">

Thanks!

**Comment by HemantAntony** [comment]
@bkunda #11725 should fix this

**Comment by bkunda** [comment]
That would be terrific. Thanks @HemantAntony!
