### ISSUE TITLE
[MU4 Issue] Palette element is not searchable when located in 'More' section of palette

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11723]
**To Reproduce**
1. Open any score
2. Search any element from 'More' section of any palette (e.g. dynamics or accidentals)
3. Pay attention to the search results

**Expected behavior**
Palette element is searchable when located in 'More' section of palette

**Screenshots**

https://user-images.githubusercontent.com/101250347/169816125-2aa10823-7431-4333-933b-d58707e6f47f.mov

**Comment by HemantAntony** [comment]
@boryskuzmenko Duplicate of #11113 and apparently a draft PR that's inactive

**Comment by boryskuzmenko** [comment]
@HemantAntony thanks man! Closing his one
