### ISSUE TITLE
[MU4 Issue] Rallentando (rall.) and Accelerando (accel.) are also rendered for linked staff

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11730]
1. Open test file
[Test_accel.mscz.zip](https://github.com/musescore/MuseScore/files/8757877/Test_accel.mscz.zip)

2. Add accel. mark to the staff
3. Create a linked staff
4. Pay attention to the linked staff

**Expected behavior**
Rallentando (rall.) and Accelerando (accel.) are not also rendered for linked staff

**Screenshots**

https://user-images.githubusercontent.com/101250347/169900010-7dc48a83-56c7-49c5-8b6e-f3545ffa5c77.mov

**Comment by DmitryArefiev** [comment]
@boryskuzmenko @Tantacrul It's expected for rit. accel. lines because they should behave as System text (the same as Tempo text does) but now you can add those for both staves independently because #11343 it's not fixed yet. 

Closing

**Comment by DmitryArefiev** [comment]
Might be fixed by #11343

**Comment by Tantacrul** [comment]
I'm not seeing this issue in the latest build. @boryskuzmenko, what do you think? Is this one ready to be closed?

**Comment by boryskuzmenko** [comment]
@Tantacrul you're right. Can't reproduce too. Closing
🟢 **Can't reproduce**
