### ISSUE TITLE
[MU4 Issue] Brackets - No Editable State on Double Click 

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11731]
**Describe the bug**
When adding a new bracket there is no longer an editable state when double clicking; bracket is fixed to single staff.

**To Reproduce**
1. Open a score with multiple instruments
2. Add a bracket
3. Double click on bracket

**Expected behavior**
After adding a bracket you should be able to double click on the bracket for it to enter an editable state that allows to extend bracket over multiple staves.

**Screenshots**

https://user-images.githubusercontent.com/30370609/169973361-1aeece12-fd2d-4593-83e5-fb7ac2b4ab66.mp4

**Platform information**
OS: macOS 12.3
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2368923748
revision: github-musescore-musescore-8e6cd1f

**Comment by Tantacrul** [comment]
Hmm. This was definitely working at some point....

**Comment by cbjeukendrup** [comment]
I think this was disabled in #11614. I agree that it would be logical to show the controls on single-click for brackets too.

**Comment by Tantacrul** [comment]
Probably an accidental consequence of my request to remove double-click from notes to enter 'Edit Mode'.

**Comment by DmitryArefiev** [comment]
> I would say that the controls should just appear on single-click too.

@Tantacrul  I vote for enable edit mode and to show handle **on double-click**. 
When you want to delete multiple brackets it shows only one handle and when editing bracket via inspector it shows the handle only from the beginning of editing.
It's just cosmetic thing of course..  🙂  

https://user-images.githubusercontent.com/90187801/170769530-8677baec-f437-4cf0-950f-05090264a1a6.mp4

**Comment by Tantacrul** [comment]
OK, I understand.

My feeling is to fix each issue so that the final result is better.

1. For now, we should definitely use single-click rather than double-click (DC is really hard to discover). 
2. (Later) multi-select should also work better

For this bug, we just need to undo the regression

**Comment by cbjeukendrup** [comment]
@Tantacrul How about the following rule:
- if a single element is selected, _always_ show grips for that element (if that element has any grips at all)
- if multiple elements are selected, never show grips

So it would just be based on the selection only, regardless of whether you double-clicked or single-clicked or whatever. 
I think that would guarantee consistent behaviour. 

--
(With brackets specifically, there are some bugs; for every edit that you make, the bracket is replaced, and the new one does get selected, but grips are not shown again. That should just be fixed.)

**Comment by Tantacrul** [comment]
@cbjeukendrup Sounds perfect to me.

**Comment by DmitryArefiev** [comment]
Fixed in #11738

**Comment by DmitryArefiev** [comment]
> (With brackets specifically, there are some bugs; for every edit that you make, the bracket is replaced, and the new one does get selected, but grips are not shown again. That should just be fixed.)

@cbjeukendrup @Tantacrul Created 2 bugs related to bracket resizing #11806 #11808
