### ISSUE TITLE
[MU4 Issue] Ability to change audio device is missing in Preferences>I/O

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11748]
**Describe the bug**
Ability to change **audio device**, **sample rate** and **buffer size**. 
The buffer size option is not present in **MU3** but will be useful for MU4 (buffer size increasing can solve some playback issues with big scores and a lot of VSTi)

Also bringing back **Restart Audio Engine option** to preferences fixes the issue described in #10987

 #11190 also might be fixed after adding additional settings to Preferences>I/O

**MU4:**
![MU4](https://user-images.githubusercontent.com/90187801/170244065-bdad22c5-365e-4ad3-a2d3-b2ddc69f28a7.PNG)

**MU3:**
![MU3](https://user-images.githubusercontent.com/90187801/170244050-3cacae56-cf08-482e-9731-667f3b6a3002.PNG)

**Expected behavior**

**Platform information**
 macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by Tantacrul** [comment]
Don't know how we missed this. Nice work, @DmitryArefiev !
