### ISSUE TITLE
[MU4 Issue] Drumset Palette - Edit Drumset - Save As

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11744]
**Describe the bug**
 It is possible to browse to desired directory when attempting to save changes to a Drumset Palette (export .drm file), but directory cannot be selected. User cannot continue Save As process.

**To Reproduce**
1. In a score with an upitched percussion instrument enter note entry mode
2. Click on Edit Drumset
3. Change any value in drumset properties
4. Click Save As
5. Browse to desired target directory
6. See error

**Expected behavior**
User should be able to select target directory to save and complete Save As function.

**Screenshots**

https://user-images.githubusercontent.com/30370609/170224867-16478daa-658e-4555-9273-f80361611cd9.mp4

**Platform information**
OS: macOS 12.3, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2368923748, revision: github-musescore-musescore-8e6cd1f

**Comment by Tantacrul** [comment]
@lengthwave - is this blocking your work?

**Comment by lengthwave** [comment]
Not blocking. I can do this one manually.
This is also a regression from 3.x.

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
