### ISSUE TITLE
For notes, the "v" keyboard shortcut is not connected to "visible" toggle in property panel

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#11740]
**Describe the bug**
The "v" keyboard shortcut for "visible" _does_ cause the selected item to become invisible, but that is not connected to the "visible" toggle in the property panel for that item. It looks as if the shortcut makes it invisible on screen but does not change the underlying `visible()` property. Indeed, if I make notes invisible via the property toggle, they will be spaced as invisible, but if I use the shortcut their positioning is not affected.

**@Tantacrul edit:** Worth mentioning that this only seems to happen for notes. It doesn't happen for most other elements.

So if I click on a notehead or stem and press 'V', the whole note (notehead, stem, flag) become invisible but the visible checkbox is not marked.

**To Reproduce**
Play around with the "v" shortcut and the "visible" toggle.

**Expected behavior**
Unless I'm missing something, I would expect the shortcut to act as if I'm pressing the toggle, and the two to be connected.

**Screenshots**

https://user-images.githubusercontent.com/93707756/170217604-21f202dd-f7d2-4e44-a997-fc792159ca87.mp4

**Platform information**
 - OS: Linux

**Additional context**
Current master

**Comment by bkunda** [comment]
@VanSHOE this might be a good one for you to kick-start your work on shortcuts :-)

**Comment by VanSHOE** [comment]
The main issue is that the inspector does not refresh upon pressing v

Regarding this, I can cause a refresh of the inspector page by sending a notification on `selectionChanged()` and catching it at the inspectorModel whenever the hotkey is pressed
But with that some other issues are coming up (essentially, the inspector is updated well for the whole measure selections but not for individual selections)
I'll continue to look into the same

**Comment by cbjeukendrup** [comment]
@VanSHOE Have a look at `AbstractInspectorModel::updatePropertiesOnNotationChanged()` and how that's used.

**Comment by VanSHOE** [comment]
> @VanSHOE Have a look at `AbstractInspectorModel::updatePropertiesOnNotationChanged()` and how that's used.

Thank you! Ill have a look into that!

**Comment by cbjeukendrup** [comment]
@VanSHOE and me did some research on this yesterday, and we found that it is indeed a problem of the inspector rather than related to the shortcut. It turns out that Michele was quite right that the inspector is not affecting the same thing as the shortcut. The shortcut toggles the visibility of the note itself, while the inspector toggles the visibility of the containing chord. @VanSHOE also discovered that the "Auto-place" property shows the same problem. 

We would need to consider carefully in which cases the Inspector should affect individual notes or their parent chord. If it turns out that the "General" section should affect notes in all cases, then a fix may be relatively easy, but if it turns out that some properties should affect the notes, and some the chords, a good fix might require a bit more thought.

**Comment by HemantAntony** [comment]
@cbjeukendrup I think this can be related to #11096. Ironically, there was a comment about this issue posted a month ago

**Comment by mike-spa** [comment]
@cbjeukendrup I've bumped before into ambiguity problems between the "visible" property of individual items (for example notes) versus the "visible" property of their parent item (for example chord). Some of that ambiguity translates into this kind of UI problems. I'd probably say the safest way is for the toggle to always refer to the individual item, but it's probably worth taking a deeper look at it

**Comment by Tantacrul** [comment]
The way this should work should be similar to how we handle 'indeterminate' states everywhere.

For example, when we have three notes selected which have a natural, a sharp and a flat applied selectively. Observe how the UI behaves.

A better example would be the text styling options in the inspector when you select multiple different text options that have different styles.

1. When the user selects a note, where only one element (eg: a stem) is hidden, we show an indeterminate state (a square) in the checkbox
3. When all parts of the note are hidden, we show a 'tick'
4. When no parts of a note are hidden, we don't show a 'tick'

**Comment by Tantacrul** [comment]
I can spec the above out if needed.

**Comment by sammik** [comment]
For rests, it works as expected


https://user-images.githubusercontent.com/1646034/192147014-f58798b2-8348-426a-b180-bacfe0a6f909.mp4

**Comment by Tantacrul** [comment]
Worth mentioning that this only seems to happen for notes. It doesn't happen for most other elements.

So if I click on a notehead or stem and press 'V', the whole note (notehead, stem, flag) become invisible but the **visible** checkbox is not marked.
