### ISSUE TITLE
[MU4 Issue] Drumset Palette - Palette Item Staff Lines

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11745]
**Describe the bug**
The number of staff lines in the Drumset Palette item does not correspond to the number of staff lines in the instrument definition.

Example: Single line percussion staff appears as 5 line staff in palette. 

**To Reproduce**
1. Create a new score with concert snare drum
2. Enter Note Entry mode
3. View Drumset Palette

**Expected behavior**
The number of staff lines in the Drumset Palette item preview should correspond to the number of staff lines in the instrument definition.

**Screenshots**

<img width="1440" alt="2022-05-25_11-56-43" src="https://user-images.githubusercontent.com/30370609/170225600-3446e4c7-a341-431c-b373-bb8a01a388c1.png">

**Platform information**
OS: macOS 12.3, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2368923748, revision: github-musescore-musescore-8e6cd1f

**Comment by Tantacrul** [comment]
I'm going to bump this to 4.x since it is already a problem with MS3. For sure it is a very annoying and stupid issue.
