### ISSUE TITLE
[MU4 Issue] Drumset Palette - Note Entry from Palette

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11743]
**Describe the bug**
Note entry from palette no longer works when double clicking on individual item in drumset palette.

**To Reproduce**
1. Create a score with any unpitched percussion instrument
2. Enter note entry mode
3. Click on any individual item in the palette

**Expected behavior**
Note entry should be possible from drumset palette.

**Screenshots**

https://user-images.githubusercontent.com/30370609/170221111-cdcf3fc3-2128-4389-862e-74458704d44c.mp4

**Platform information**
OS: macOS 12.3, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2368923748, revision: github-musescore-musescore-8e6cd1f

**Additional context**
My assumption is that this issue occurs because double click action was removed.

It is recommended that instead of note entry when double clicking on individual palette item note entry occurs when single clicking on item.

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/10719
