### ISSUE TITLE
[MU4 Issue] Drumset Palette - Audio Preview

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11742]
**Describe the bug**
Audio preview no longer works with clicking on individual item in drumset palette.

**To Reproduce**
1. Create a score with any unpitched percussion instrument
2. Enter note entry mode
3. Click on any individual item in the palette

**Expected behavior**
User should be able to preview sound.

**Screenshots**

https://user-images.githubusercontent.com/30370609/170221111-cdcf3fc3-2128-4389-862e-74458704d44c.mp4

**Platform information**
OS: macOS 12.3, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2368923748, revision: github-musescore-musescore-8e6cd1f

**Additional context**
My assumption is that this issue occurs because double click action was removed.

It is recommended that instead of preview when clicking on individual palette item it can be preview when hovering over item.

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/11722
