### ISSUE TITLE
[MU4 Task] Thumbnail icon to be created for GP files

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11759]
**Task description**
I believe we should have to separate GP files from MU files on the Recent board. To do that specific icon should be created and implemented.
Also will be good to use this icon as a file icon for GP files in case when there's no Guitar Pro installed (just thoughts)
MU4 file icon as an example:

![Capture 2022-05-25_08-48-05_PM](https://user-images.githubusercontent.com/101250347/170330665-a8d9ea5a-565f-468a-b3b6-eed309a14dd5.png)

**Comment by Tantacrul** [comment]
@jessjwilliamson - I know I said not to... but can we make a GP image>? :)

I'd suggest a guitar silhouette or plectrum symbol or something like that.

**Comment by jessjwilliamson** [comment]
> 

hehe.

Of course :)

**Comment by DmitryArefiev** [comment]
Fixed in #11773
