### ISSUE TITLE
[MU4 Issue] Crash when starting to drag text line while there is a range selection

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#11756]
**Describe the bug**
If you start dragging a "text line" (for example, a pedal marking or volta) while there is a range selection, a crash occurs. 

**To Reproduce**
1. Create a new score 
2. Add some notes
3. add a text line
4. If you click the measure to make a range selection, the blue rectangle will _not_ include the text line:
    <img width="206" alt="Schermafbeelding 2022-05-25 om 17 53 24" src="https://user-images.githubusercontent.com/48658420/170305022-8d1cbe4b-99eb-4698-95b5-3f9b803b1ad8.png">
    That's quite odd, but not critical. 
5. If you now start dragging the text line, everything is okay.
6. After having moved the text line a bit and selecting the measure again, the rectangle _will_ include the text line:
    <img width="206" alt="Schermafbeelding 2022-05-25 om 17 54 28" src="https://user-images.githubusercontent.com/48658420/170305218-57dd2c3d-3534-4d7e-9ec6-4a6ef7fe8c8c.png">
7. If you now start dragging the text line, a crash occurs. (Note that the starting point for dragging must be inside the blue rectangle to make the crash happen.)

**Expected behavior**
No crash

**Platform information**
 - OS: reported on macOS 

**Additional context**
It's a nullptr dereference, seems not massively complicated.

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Can reproduce it on Windows as well. Also occurs if to drag a line (trill or crescendo) inside the range selection and then start to drag

https://user-images.githubusercontent.com/90187801/170464872-1c7deea6-9ecd-4f6d-ac8c-c2598a4fce61.mp4

Thanks for logging! 

(If you want to fix it please reassign to yourself)

**Comment by DmitryArefiev** [comment]
Fixed in #11880
