### ISSUE TITLE
[MU4 Issue] File icons look pixelated on Windows/Linux (FullHD, 100% scaling)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11757]
**Windows10, FullHD, 100%**
![Capture](https://user-images.githubusercontent.com/90187801/170513152-e7db5d36-4fb9-40a2-84fa-f34817f955da.PNG)

Windows10, FullHD, 150%
![Capture2](https://user-images.githubusercontent.com/90187801/170511763-eb5009aa-cee5-4c04-a47c-b4103c939338.PNG)

Mac12, Retina display
![Screenshot 2022-05-26 at 5 44 17 PM](https://user-images.githubusercontent.com/90187801/170512883-24c3118a-a961-4648-bf71-d24e0dde2acc.png)

**Platform information**
 Windows, Linux - FullHD, 100

**Comment by HemantAntony** [comment]
I can reproduce on my laptop. The icon is too sharp

**Comment by DmitryArefiev** [comment]
Fixed in #11773
