### ISSUE TITLE
[MU4 Issue] Real-time (metronome) and Real-time (foot pedal) entry modes not working

### ISSUE THREAD

**Issue by Phantasmogenesis** [musescore/MuseScore#11761]
**Describe the bug**
The "real-time (metronome)" note entry mode does not work as expected; instead, seems to act somewhat like "re-pitch existing notes" entry mode.

**To Reproduce**
1. Enter "real-time (metronome)" entry mode on a score
2. Press a key with MIDI keyboard
3. See error

https://user-images.githubusercontent.com/90187801/170496948-8d1415cb-bec2-4176-8708-227b58f299ff.mp4

**Expected behavior**
Once the MIDI key is pressed, the metronome should start and each metronome tick with the MIDI key held down should add some rhythm value to the entered note.

**Platform information**
 - Ubuntu

**Additional context**
As I understand it, in previous versions of MuseScore, the "real-time (automatic)" note entry mode existed in place of "real-time (metronome)." However, in various places in the codebase there still exist references to "real-time (automatic)" mode; perhaps these should be refactored to "real-time (metronome)" or vice versa for the sake of consistency?

https://musescore.org/en/handbook/3/note-input-modes (description of the features)

**Comment by DmitryArefiev** [comment]
@Phantasmogenesis Thanks for catching this! I also found real-time (foot pedal) doesn't work too. Added info to the description and summary.

Tested on Windows10

**Comment by DmitryArefiev** [comment]
Fixed in #12906

The related issue which left after implementation is logged separately #13095
