### ISSUE TITLE
[MU4 Issue] Drum Palette - Tooltip missing on hover

### ISSUE THREAD

**Issue by lengthwave** [musescore/MuseScore#11766]
**Describe the bug**
When hovering over drum palette item there is no tooltip to show the name of the palette item.

**To Reproduce**
1. Create score with unpitched percussion
2. Enter note entry mode for unpitched percussion instrument
3. View Drum Palette
4. Mouseover palette item
5. See error

**Expected behavior**
Should display tooltip with individual palette item name on hover (same as 3.6).

**Screenshots**

<img width="1440" alt="2022-05-26_12-47-33" src="https://user-images.githubusercontent.com/30370609/170464118-cdd809d8-327a-47fb-b1fd-3b2f810053cd.png">

**Platform information**
OS: macOS 12.3, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2388592852, revision: github-musescore-musescore-44e3783

**Comment by lengthwave** [comment]
@Tantacrul - this is a blocker for further percussion testing

**Comment by Tantacrul** [comment]
Added a P1 because this is effectively blocking the work @lengthwave is doing to fix up percussion definitions. It is also really bad because (as a composer) it is impossible to know what each of the symbols are when writing.

**Comment by Tantacrul** [comment]
@cbjeukendrup - is this an easy fix?

**Comment by cbjeukendrup** [comment]
It seems not entirely trivial. It looks like it has to do with the fact that the drumset palette is a QWidget embedded in QML. 

If you select an element in the drumset palette, its name is displayed at the left side of the panel. Could that maybe serve as a workaround for now? Or is the tooltip particularly crucial?

**Comment by lengthwave** [comment]
Will check latest build, label was not appearing previously.

Also, there is no sound preview ([#11722](https://github.com/musescore/MuseScore/issues/11722)), so not super user friendly.

**Comment by Tantacrul** [comment]
OK, since there is at least some solution evident (and we're planning on replacing the panel anyway) I'll close this issue.
