### ISSUE TITLE
[MU4 Issue] Play panel shows incorrect tempo

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#11776]
**Describe the bug**
When adding "Quarter note = 80 BPM" element from the palette, the play panel shows "♩= 79" in nightly build

**To Reproduce**
1. Create new score
2. Add "Quarter note = 80 BPM" element from tempo palette to the score
3. See play panel

**Expected behavior**
Play panel should show "♩= 80"

**Screenshots**
![スクリーンショット (19)](https://user-images.githubusercontent.com/102702868/170606298-b695b70f-ff86-471d-bcb1-7446e9c75b20.png)

**Platform information**
 - OS: Windows 11

**Additional context**
Doesn't occur in Private Alpha

**Comment by Obliquely** [comment]
**Extra info** If you edit the tempo, e.g.  change it to 81 BPM and then back to 80, then the Play Panel shows the expected value, 80. If you save and reload, the error persists. If you export to MusicXML or MIDI the error sorts itself out.

**Comment by Tantacrul** [comment]
Confirmed. All you have to do is add this from the 'Tempo' palettes and you see the issue right away. 

<img width="284" alt="image" src="https://user-images.githubusercontent.com/21022311/170705134-2370175b-659d-4b3d-bf7b-c3982ecb0a9e.png">

Nice catch!

**Comment by HemantAntony** [comment]
@Tantacrul, I have a fix: #11795

If you're wondering what happened. The tempo was stored like this - 79.99998 But the tempo wasn't getting rounded. It was just getting converted to 79
