### ISSUE TITLE
[MU4 Issue] Mixer tracks are loaded slowly just after score opening

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11772]
**Describe the bug**
Mixer tracks loading takes 1+ seconds. Loading time depends on number of instruments. Sometimes it take up to 10 sec for big scores. But the bug is noticeable even on piano scores

**To Reproduce**
1. Open the test score (mixer should be expanded by default)
[Mozart_Symphony_No._40_in_G_Minor_K._550_I._Molto_Allegro.mscz.zip](https://github.com/musescore/MuseScore/files/8780182/Mozart_Symphony_No._40_in_G_Minor_K._550_I._Molto_Allegro.mscz.zip)
2. Pay attention to the mixer tracks loading

**Expected behavior**
Mixer tracks are fully loaded just after score opening

**Screenshots**

https://user-images.githubusercontent.com/101250347/170523095-7cea364d-c486-45dc-9107-880e656a55fa.mov

**Platform information**
 - OS: macOS, Windows, Linux

**Comment by Tantacrul** [comment]
This is known - and there's already a task to include a loader to explain to people that the app is loading sounds. I think we should close this for now and let that task be completed first.
