### ISSUE TITLE
[MU4 Issue] Metronome does not play during notes that begin on off beats

### ISSUE THREAD

**Issue by Phantasmogenesis** [musescore/MuseScore#11777]
**Describe the bug**
During playback, the metronome does not tick if the note being performed does not begin on the beat.

**To Reproduce**
1. Open a score with the metronome enabled
2. Create a section of music containing notes that do not fall on the main beats
3. Click "Play"

**Expected behavior**
The metronome should tick on each beat evenly rather than being silent during notes that do not begin on the beat.

**Screenshots**

https://user-images.githubusercontent.com/65755354/170616116-349b9fab-e396-434a-9446-eb5333d54ddd.mp4

**Platform information**
Ubuntu

**Additional context**
In the screen capture provided, the third and fourth measures show that the same rhythm will cause the metronome to act differently depending on how it is notated; the third measure does not have proper metronome playback whereas the fourth does because each note that falls on the beat is separately notated but connected using ties.

**Comment by cbjeukendrup** [comment]
As reported in #12094, the problem also occurs when a dotted quarter note is used.

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12486
Tested on macOS 12, Win 11, Ubuntu 20
