### ISSUE TITLE
'Feathered Beams' option has disappeared from the Inspector

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11792]
**Describe the bug**
The feathered beams option that we designed for MS4 (and which was working) has gone missing. It's purpose was to accomplish these effects:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/21022311/170777767-f90c751e-7a3c-4b4b-8fbf-0a447f680fc5.png">

Here is an example of the design in Figma (in the 'Inspector' page)
<img width="738" alt="image" src="https://user-images.githubusercontent.com/21022311/170776592-23ffad7c-d1ea-47c6-8705-33e009d1a7f7.png">

The idea is this:

This button sets: **Grow left = 1' / Grow right = 0** on a selected beam (which can be accomplished in MS3)
<img width="183" alt="image" src="https://user-images.githubusercontent.com/21022311/170777131-e661527e-bb58-479d-ba1c-056970ea31a4.png">

This button sets: **Grow left = 0' / Grow right = 1** on a selected beam (which can be accomplished in MS3)
<img width="203" alt="image" src="https://user-images.githubusercontent.com/21022311/170777248-71c08d60-4f66-48e4-b11d-1923439b1532.png">

This is not new functionality, so should be very simple to implement (replacing the text boxes in MS3). If there is any confusion, just contact me and I'll take you through it.

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by Tantacrul** [comment]
@RomanPudashkin - I suspect that this might be blocked behind @asattely's work on the beaming code. Perhaps he may want to have a say in this too. I'm unsure.

**Comment by cbjeukendrup** [comment]
@Tantacrul I see that currently the wrong icons are used:
<img width="299" alt="Schermafbeelding 2022-06-08 om 22 56 57" src="https://user-images.githubusercontent.com/48658420/172715851-31d4b1a9-843e-49af-8641-e1008e161d1b.png">
I will fix that. 

I was also thinking about the screen reader text and tooltip (in palettes). Currently the inspector uses "Left" and "Right", but that might be confusing and not for everyone intuitive. The palette uses "slower" and "faster". But I think even better would be "Decelerate" and "Accelerate". Do you agree?

**Comment by cbjeukendrup** [comment]
Pushed a fix to #11934!

Now the next problem becomes visible: the correct icons are not correctly centered in their bounding box:
<img width="299" alt="Schermafbeelding 2022-06-08 om 23 56 46" src="https://user-images.githubusercontent.com/48658420/172724411-ed4d430a-d5e2-4752-9eda-2e4ba302d657.png">

This must be a problem of the icon, not the UI. 

Also, the beam mode icons are tiny compared to the feathering icons. That was not obvious because some scaling was applied to them, but in the screenshot above I temporarily removed that scaling. I think it is preferable if the beam mode icons would be sized similar to the feathering icons. 

@bkunda Could you make these tweaks, and send me the updated version of the font? Then I'll add it to the PR.

**Comment by Tantacrul** [comment]
@cbjeukendrup - try this to fix the centring of the feathered beams.
https://www.dropbox.com/s/0onoito87kf572k/MusescoreIcon.ttf?dl=0

As for the beam icons, if we tweak them, that'll also affect them in palettes too.

So...

1. We leave the scaling as it was befor
2. OR: we remake the icons then fix scaling in Palettes & Properties
3. OR: we make a new set of the same icons and scale the up just for Properties

What do you think?

**Comment by cbjeukendrup** [comment]
The beam mode icons are used only in the Beam Properties palette and the Beams inspector, and in both those places the icons are too small if we don't apply additional scaling. So I think the cleanest way is to update the icons so that the scaling is not necessary anymore in both places.

**Comment by Tantacrul** [comment]
OK, we'll scale them up then. @bkunda - I'll leave that to you, since @oktophonie had thoughts about how to make those symbols better anyway!

**Comment by cbjeukendrup** [comment]
By the way, the fix for centering the feathering icons works great!
<img width="299" alt="Schermafbeelding 2022-06-09 om 00 27 28" src="https://user-images.githubusercontent.com/48658420/172728057-643145d1-7a8d-4b1d-a534-77f6f52bb8ce.png">

**Comment by Tantacrul** [comment]
Yep. I just made them wrong the first time. :)
