### ISSUE TITLE
[MU4 Task] Implement expandable category rows for keyboard shortcuts in Preferences 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11804]
**Task description**

This task proposes a basic solution for improving the discoverability of keyboard shortcuts in the Preferences dialog.

Instructions are in [this UX spec document](https://www.dropbox.com/s/560s71riwqjhmoq/UX-Design_Keyboard-Shortcuts_v.2.pdf?dl=0)

@VanSHOE we can at some point discuss this in relation to your GSoC project 🙂

**Comment by VanSHOE** [comment]
@bkunda Sure! I have added this to the extended objectives as well!
