### ISSUE TITLE
[MU4 Issue] Grace note stem custom direction in MU3 score is lost

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11817]
**To Reproduce**
1. Open [grace-3-original.zip](https://github.com/musescore/MuseScore/files/8800042/grace-3-original.zip) in MU3
2. Open [grace-3-original.zip](https://github.com/musescore/MuseScore/files/8800047/grace-3-original.zip) in MU4

![01](https://user-images.githubusercontent.com/90187801/171041222-068e7c34-ae21-41af-8ab3-f84b37b06601.PNG)

![02](https://user-images.githubusercontent.com/90187801/171041235-5e9ee7af-8663-436e-afb4-2bf5f3604201.PNG)

https://user-images.githubusercontent.com/90187801/171040710-8c5f21ad-33c2-45d1-82d2-d94656d7dbb3.mp4

This occurs if to set stem custom direction in **Beam** section in MU3's Inspector

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Comment by oktophonie** [comment]
Fixed by #11788
