### ISSUE TITLE
[MU4 Issue] Changed parameters are not reverted after clicking 'Cancel' button on the 'Page settings' dialog

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#11841]
**To Reproduce**
1. Open any score
2. Go to the Page settings (in system menu 'Format')
3. Change any parameter (difference should be visible)
4. Click Cancel
5. Go to Page settings again
6. Pay attention that changed value was reseted but changes on the score are not

**Expected behavior**
Changed parameters are not reverted after clicking 'Cancel' button on the 'Page settings' dialog

**Screenshots**

https://user-images.githubusercontent.com/101250347/171390734-02c55eca-1a09-4b97-8bf3-53010ce3d767.mov

**Comment by boryskuzmenko** [comment]
@RomanPudashkin Please, pay attention that Staff space parameter in Page settings is not reverted visually after clicking Cancel

https://user-images.githubusercontent.com/101250347/186697089-1075f265-d02a-459d-8a39-8302154e1a1a.mov

**Comment by boryskuzmenko** [comment]
Or it could be a separate bug?

**Comment by boryskuzmenko** [comment]
Also, found the same behavior in Styles dialog. Only in the Music top/bottom margin parameters
![Capture 2022-08-29_11-46-49_PM](https://user-images.githubusercontent.com/101250347/187296205-9fb8883e-0672-47a5-bc7a-8ddc9ceaf72e.png)

**Comment by RomanPudashkin** [comment]
> Or it could be a separate bug?

@abariska yes, let's open a separate issue for this particular problem

**Comment by abariska** [comment]
Separate issue created https://github.com/musescore/MuseScore/issues/13861
