### ISSUE TITLE
[MU4 Issue] Crash when un-hiding an instrument in a part

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11842]
**Describe the bug**
The latest nightly crashes when un-hiding an instrument in a part: 

Video demo: https://www.dropbox.com/s/17ds79w0fe0zo6e/crash-unhiding-staff-instruments.mov?dl=0

**To reproduce**
1. Create a score with more than one instrument 
2. Enter some notes on each instrument
3. Open a part 
4. In the opened part, go to the instruments panel
5. Click the "eye" icon on another instrument to show it in the selected part
MuseScore crashes

**Platform information**
 - MacOS 12.3.1 (M1)
 - Windows 11

**Comment by Jojo-Schmitz** [comment]
I can't reproduce on Windows 11 with the latest build

**Comment by bkunda** [comment]
I too can reproduce on Windows 11

**Comment by Jojo-Schmitz** [comment]
I still can't, also not in MSVC

**Comment by Jojo-Schmitz** [comment]
Slight deviation from the latest code: I'm using the code from #11786

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/11853
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by boryskuzmenko** [comment]
🟢 **Regression FIXED** in https://github.com/musescore/MuseScore/pull/12164
Tested on macOS 12, Win 11, Ubuntu 20
