### ISSUE TITLE
[MU4 Issue] Shortcut `toggle 'insert mode'` doesn't work correctly 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11844]
**Describe the bug**
The shortcut `Toggle 'insert mode'` doesn't trigger expected behaviour (see #11829 for details on how to reproduce)

**Expected behavior**
When `Toggle 'insert mode'` is triggered (Shortcuts: `Cmd`/`Ctrl`+`I`), the note input mode should toggle between **insert mode** and **default (step-time)** mode.
 
<img width="1177" alt="Screenshot 2022-06-01 at 10 31 37 pm" src="https://user-images.githubusercontent.com/86290556/171405017-aff1b281-b1fe-4dcb-9cb9-03a6eeb2247b.png">

**Platform information**
 - All platforms

**Additional information**
@VanSHOE this might be another good one for you 🙂

**Comment by Tantacrul** [comment]
Moving to 4.x. Will reopen when 4.0 is out. The PR needs revision and may cause problems if merged.

**Comment by MarcSabatella** [comment]
As per my comment in https://github.com/musescore/MuseScore/issues/14496#issuecomment-1380414009, I would suggest should be very high priority to simply remove this completely broken shortcut for 4.1.  Then worry later about what we might replace it with.  People keep accidentally pressing Ctrl+I in normal mode and then wondering why they can't delete measures anymore and why their scores keep getting corrupted.  But that is exactly what this command does right now - disables measure deletion and corrupts scores.

I'm happy to create a PR doing just that - removing the shortcut, nothing else.

**Comment by cbjeukendrup** [comment]
@MarcSabatella It looks like I partially did that in 74362072c58f052c6e18735759dcc717c5451201. Still, the PR of @VanSHOE is welcome, to make the command do something useful.
