### ISSUE TITLE
[MU4 Task] Add stem direction to tremolo properties

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#11852]
Tremolos have their own settings in the Properties panel. As we are now making two-note tremolos more like beams (conceptually and visually), they would benefit from having access to some of the same properties as beams available.

Currently:
![image](https://user-images.githubusercontent.com/20604032/171444978-4f0ab8c1-98e8-4be1-bf20-a8bafd0534ab.png)

It would be useful for now to add stem direction to this (from Note -> Stem properties):
![image](https://user-images.githubusercontent.com/20604032/171445209-1b99cf4a-85bf-4edc-bb60-d2e9517bba97.png)

Primarily this (and other properties added later) are for two-note tremolos, which function in a beam-like way. It wouldn't hurt to add stem direction for single-note tremolo slashes too.

**Comment by oktophonie** [comment]
Yes, the configuration with stems going in opposite directions is no longer possible (assuming #11836 is ever merged).

**Comment by HemantAntony** [comment]
I have a fix ready. I will wait until #11836 is merged

**Comment by HemantAntony** [comment]
@oktophonie I have a PR ready. Can you check #12284
