### ISSUE TITLE
[MU4 Issue] Augmentation dot setting ignored when entering rests

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11851]
**Describe the bug**
Selecting the augmentation dot on the toolbar during note input affects the next note entered, but is ignored for rests.

**To Reproduce**
1. New score, 12/8 meter
2. Note input mode
3. Type "5 ." or select the quarter note and dot icons to select dotted quarter duration
4. Type "0" to enter a rest
5. Result: only a quarter rest is entered

**Expected behavior**
A dotted quarter rest should be entered

**Screenshots**
![image](https://user-images.githubusercontent.com/1799936/171441664-ad21ffd4-f825-4ccf-8804-5e102597e3d9.png)

**Platform information**
 - OS: Linux

**Additional context**
I guess maybe this comes from some sort of effort to enforce a rule against dotted rests, but a) that rule doesn't apply in compound meter like 12/8, b) it's not absolute even in 4/4, and c) we shouldn't be overriding what the user is asking for

**Comment by Tantacrul** [comment]
No, we never intended to prevent dotted rests. This is just an oversight. Nice catch.
