### ISSUE TITLE
[MU4 Issue] Changing of multimeasure rest number position can not be safed

### ISSUE THREAD

**Issue by love4drums** [musescore/MuseScore#11869]
**Describe the bug**
When the number position of a single multimeasure rest is changed, this will not be safed after closing and reopening the score.

**To Reproduce**
1. Create a new simple score with a row of rests
2. Via "Format ->Styles ->Rests" enable "Multimeasure rests" and click "ok"
3. Now the row of rest bars merged to a single multimeasure rest
4. Click on the multimeasure rest and change the number position in the properties (the former inspector), for example from -0.5 to +6.5, so that the number will be positioned below the staff
5. Save the score and close it
6. Reopen the score

**Expected behavior**
Instead of being in the changed position, the rest number is in the default position above the staff

**Screenshots**

**Platform information**
 - OS: Windows

**Additional context**

**Comment by cbjeukendrup** [comment]
This seems to be fixed by #16046, so I'll close it as completed.

@love4drums You could download the latest 4.0.2 nightly build from https://musescore.org/en/nightly-builds to try out the fix. If the issue still occurs, we can reopen this.
