### ISSUE TITLE
[MU4 Issue] Sometimes the File-menu drop-down highlighting sticks

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#11860]
**Describe the bug**
On my Linux distro, moving around on the File menu can get the highliter to be stuck. Not sure why light gray instead of blue, but only shows up blue when stuck. Included is a demonstration video:

https://user-images.githubusercontent.com/7139517/171521759-4a9a2b0e-3b4a-41d3-8bd5-0bcd3e5e8ed2.mp4

**Comment by Eism** [comment]
Fixed in #11750

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
