### ISSUE TITLE
[MU4 Task] Add ability to arrow buttons work in auto repeat mode when holding mouse button (to scroll part tabs)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11864]
**Task description**
https://github.com/musescore/MuseScore/pull/11582#issuecomment-1143609319

**To Reproduce**
1. Open a big score
2. Open all part (you see arrow buttons at the top right)
3. Click one of them and hold the key - **it should trigger auto repeat mode and start scroll process**

![Capture](https://user-images.githubusercontent.com/90187801/171617203-91fa782e-11fa-4213-8504-a5bf505b202d.PNG)

**Additional context**
#11582

**Comment by cbjeukendrup** [comment]
@DmitryArefiev No problem, I added it to the PR! I was initially afraid that it would be too fast if it was the same as the inspector. But now I realize that _if_ the user clicks and holds, they probably _want_ to scroll fast, so it's probably a good change.
