### ISSUE TITLE
[MU4 Issue] Multiple undo commands required to undo delete of multiple staves.

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#11861]
**Describe the bug**
When multiple staves are selected on the instrument panel and deleted, `Undo` will restore only one staff. Extra `Undo` commands are required to restore all deleted staves.

**To Reproduce**
1. Create a score with several instrument, e.g. a Piano and an Organ
2. Click on the first staff of the Piano.
3. Ctrl-Shift-Click on e.g. the second staff of the Organ.
4. Delete the staves (using the waste bin icon)
5. Now the staves are deleted.
6. Undo the command (Ctrl-Z).
7. Now only the staff of the Piano is restored, not the deleted staff of the Organ, this requires an extra `Undo`.

**Expected behavior**
When multiple staves are deleted with one action, `Undo` should restore all delete staves in one single `Undo` operation.

**Screenshots**
N.a.
**Platform information**
 - OS: Linux

**Additional context**
N.a.

**Comment by Tantacrul** [comment]
I'm unable to reproduce this on MacOS.

@DmitryArefiev ?

**Comment by njvdberg** [comment]
Has apparently same root cause as #11856 and is solved with PR #11882 (which simply disables selecting multiple staves).

**Comment by njvdberg** [comment]
@DmitryArefiev This exactly the same issue!

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/11961
Tested on macOS 12, Win 11, Ubuntu 20
