### ISSUE TITLE
[MU4 Issue] Unable to add Staff text or Expression text to a multimeasure rest with the shortcut Ctrl+T/Ctrl+E

### ISSUE THREAD

**Issue by love4drums** [musescore/MuseScore#11870]
**Describe the bug**
It is not possible to add text to a multimeasure rest, as it is in Musescore 3

**To Reproduce**
1. Create a new simple score with a row of rests
2. Via "Format ->Styles ->Rests" enable "Multimeasure rests" and click "ok"
3. Now the row of rest bars merged to a single multimeasure rest
4. Click on the multimeasure rest 
5. Try to type Ctrl+T 

There is no possibility to add text to the multirest. Not via context menu nor properties nor Ctrl+T

https://github.com/musescore/MuseScore/assets/90187801/ebff42d0-4d3b-4368-9cfd-9241de6d842a

**Platform information**
 - OS: Windows

**Comment by zacjansheski** [comment]
Currently able to add test to multi-measure rests from palettes but not with the Ctrl + T shortcut

Updating the title to reflect this.

https://github.com/musescore/MuseScore/assets/69917893/0b195d69-1ddb-4436-b069-cb5df721969a

**Comment by DmitryArefiev** [comment]
The same with expression text using shortcut Ctr+E 
(will modify the summary)
