### ISSUE TITLE
[MU4 Issue] MU can't switch between different VSTi (Kontakt or BBC Symphony) configurations (saved in score) when opening scores in one MU session

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11879]
**To Reproduce**
1. Open score A 
2. Load Kontakt with Piano sample
3. Save and close score A
4. Open score B
5. Load Kontakt with Synth sample
6. Save and close score B
7. Open score A and play - **MU loads Kontakt with Synth sample (from score B)**

https://user-images.githubusercontent.com/90187801/171860228-084f22f8-8aa8-4410-8a6a-8fe9ea8e9613.mp4

The same with BBS Symphony Orchestra:

https://user-images.githubusercontent.com/90187801/172207165-92efe092-312e-4be8-8ff9-9e4663025384.mp4

**Additional context**
That doesn't occur if to restart MU before loading the score with different Kontakt configuration

**Platform information**
macOS, Windows

**Comment by Tantacrul** [comment]
Excellent find, @DmitryArefiev

**Comment by vpereverzev** [comment]
Fixed in #12568, confirmed by @Tantacrul 
![image](https://user-images.githubusercontent.com/57620349/181257505-e500cdba-3b4f-4703-be42-12cb4162289b.png)
