### ISSUE TITLE
Chord not sounding when cursor advances; (tablature) chord sounding when cursor moves vertically

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11885]
**Describe the bug**

When the cursor advances onto a chord (and "Play chord when editing" is checked in preferences) the chord should sound. However only the top note of the chord seems to be sounding.

Secondly, in MS3, in note-input mode, when the cursor moves vertically in a chord in tablature, _no_ note sounds. However in MS4, the top note of the chord sounds for each move.

**To Reproduce**

1.Open the attached file. 
[test_file.mscz.zip](https://github.com/musescore/MuseScore/files/8834332/test_file.mscz.zip)
2. Click on the top note, say, in the first chord, then use the right arrow to move from chord to chord. Repeat actions in note input mode.
RESULT: Only the _top_ note of the chord sounds
3. Enter note input mode. Move the cursor vertically down from note to note.
RESULT: The top note of the chord sounds each time. Even if you move the cursor off the chord onto a blank string, the chord sounds.

**Expected behavior**
If "Play chord when editing" is operative, the chord should always play when the cursor advances to it in both "normal" and "note input" mode, for both staff and tablature.

In note input mode, when you move the cursor vertically along a chord in tablature, there should be _no_ sound (as in MS3).

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2432394363, revision: github-musescore-musescore-1ff2049

**Comment by Tantacrul** [comment]
Already logged by @shoogle. https://github.com/musescore/MuseScore/issues/11451

Definitely needs to be fixed. Incidentally, this was the very first feature I suggested that was implemented before I came on the team full time!

**Comment by Tantacrul** [comment]
I have added the extra information about Tab stave playback in the other issue too. Thanks @rgreen5 !
