### ISSUE TITLE
[MU4 Issue] [Inspector] "Text line" and "tempo line" buttons have missing icons

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11886]
Edited by Bradley:

![Capture](https://user-images.githubusercontent.com/90187801/172045871-bb01780c-5c04-47b2-9ad8-c2c61fb24515.PNG)

<img width="1143" alt="Screenshot 2022-06-03 at 6 34 38 pm" src="https://user-images.githubusercontent.com/86290556/172097975-5401df8e-e130-46b2-b51a-381d9e6e3f78.png">

https://user-images.githubusercontent.com/90187801/172046108-6a255c89-3ad9-4dfa-940f-fff8465088af.mp4

**Platform information**
macOS, Windows, Linux

**Comment by DmitryArefiev** [comment]
@Tantacrul @bkunda Leaving in Beta1 for now

**Comment by Tantacrul** [comment]
Ah, it's just missing an icon. @bkunda: can you recommend a symbol (or make a new one, if needed)?

**Comment by bkunda** [comment]
Good spot @DmitryArefiev. I too found another one recently (for tempo change lines), which is exactly the same problem.
I might expand this issue to include both icons. I'll then work on recommending or creating new ones, which I'll post as a task.

**Comment by DmitryArefiev** [comment]
> Good spot @DmitryArefiev. I too found another one recently (for tempo change lines), which is exactly the same problem. I might expand this issue to include both icons. I'll then work on recommending or creating new ones, which I'll post as a task.

Ohh.. it's @RomanPudashkin found :)
