### ISSUE TITLE
Applied brace is too small on application; fixes itself when extended

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11884]
**Describe the bug**
When a brace is first applied it is too small. It only assumes the right size when extended.

**To Reproduce**

1. Create a guitar staff/tab score.
2. Click on first measure and add a brace (brackets are not affected)
RESULT: The brace is too small
4. Extend the brace manually to the tab line
RESULT: The brace assumes the correct size.

**Expected behavior**
The brace should be at the correct size as soon as it is applied, just like the bracket.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2432394363, revision: github-musescore-musescore-1ff2049

**Comment by njvdberg** [comment]
I agree a one staff brace looks silly but to looks too me what it should look like. Braces are scaling in horizontal direction depending on the height. Before PR #7124 they didn't resulting in too thick braces.

**Comment by Tantacrul** [comment]
It does look a bit funny when applied to one staff. However, this is an existing issue with 3.6, so we won't be fixing it in 4.0.

**Reasoning:** We already have a lot to fix and we don't want to add existing legacy issues on top of that. I'm not even 100% sure if this should be solved in Leland (or at all). @oktophonie ?
