### ISSUE TITLE
[MU4 Issue] Unable to run latest builds on Linux

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11897]
**Describe the bug**
Unable to run latest build on Linux

try these
https://github.com/musescore/MuseScore/actions/runs/2445567865
https://github.com/musescore/MuseScore/actions/runs/2446767239

see [terminal output.txt](https://github.com/musescore/MuseScore/files/8844994/terminal.output.txt)

**Platform information**
Linux Mint 20.2

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.org/en/node/332616
