### ISSUE TITLE
There are two dialogs called "Instruments"; cannot pre-specify staff type to be added

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11896]
**Describe the issue**

1. There are now two dialogs with the name **Instruments**. We should rename the 'Instruments' popup to be called **Add or remove instruments**

**Comment by Tantacrul** [comment]
1. I think we should change the 'Instruments' popup to be called '**Add or remove instruments**'
2. This is out of scope for 4.0

I have edited the description accordingly.
