### ISSUE TITLE
Crashes on score with stemless notation

### ISSUE THREAD

**Issue by sberla365** [musescore/MuseScore#11899]
Hi, not sure this is the correct place to report this.

 I am trying to open a file created in MS3.6 with MS4 but it crashes before opening. The file contains stemless notation, empty text frames (a box surrounding the notes created through staff text with empty content and a rectangular frame) and lines stretching across multiple lines. I also have a lot of hidden content (mostly rests from empty bars).
After some testing (I deleted elements one by one to see what stops loading the file) the crash seems to be caused by stemless notation. However, if I set my my score to display stems and add some other stemless notation to a different staff in MS3 the file opens correctly

**Comment by cbjeukendrup** [comment]
Hi! If you send us the score, we can investigate. You can upload it here on GitHub by wrapping it in a .zip file.

**Comment by sberla365** [comment]
Ok, I attach the file.

I have been playing around with the file and figured out that the issue seems to be caused by stemless quavers (or smaller divisions). If I rewrite the passage with stemless crotchets MS4 loads the file correctly.

Here is my test file. I don't know if it is worth saying that I am running MS on Linux (Fedora 36). I will test the same file tomorrow on a mac.
[Uploading test.zip…]()

**Comment by asattely** [comment]
gotcha! pow, bug zapped

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/11950
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by sberla365** [comment]
Hi, the crash with stemless notation is back with yesterday and today's nigh build

**Comment by HemantAntony** [comment]
Yeah I can reproduce the crash with the same score

**Comment by asattely** [comment]
This may have been a problem with the tremolo PR that was merged, possibly some kind of rebase failure or regression of some kind. I'm going to be working on https://github.com/musescore/MuseScore/issues/12287 today, and I will make sure to test this score, so my PR for that one should fix the issue
