### ISSUE TITLE
[MU4 Issue] When line (hairpin, slur etc.) is located within a range selection, after single selection the grips are disappear

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11902]
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**
1. Place slur near to measure lines
2. Select measure
3. Click on slur - **the grips are shown for a moment and then disappear. Also, you can't use Shift+arrows shortcut to extend the slur line**

https://user-images.githubusercontent.com/90187801/172193268-a758e4ca-67fd-4bcb-8070-add88887566a.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by Tantacrul** [comment]
Excellent spot @DmitryArefiev !

**Comment by DmitryArefiev** [comment]
Fixed in #13136
