### ISSUE TITLE
[MU4 Issue] Positioning and appearance of note head parenthesis

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#11903]
(Logging this issue for the sole purpose of not forgetting about it. Please @Tantacrul and @oktophonie feel free to prioritize this as needed.) 

Our default positioning of note head parenthesis is currently like this:
![Screenshot from 2022-06-06 17-35-26](https://user-images.githubusercontent.com/93707756/172195378-2cc61918-cf13-4d5f-84e2-900a19cd309a.png)
but ideally it should look something closer to this:
![Screenshot from 2022-06-06 17-37-00](https://user-images.githubusercontent.com/93707756/172195481-de9c9d32-6e92-4488-b045-4360a8d7800e.png)

A few of the more obvious issues:
- Parenthesis is too close to the note
- Parenthesis is touching the stem
- Parenthesis is crossing ledger lines
- Parenthesis should also include the accidental.

The last one is more delicate, as accidentals can also be separately parenthesized so we should clarify what happens in such case.

On a separate note: the current parenthesis symbols in Leland _may_ be slightly too thin. With 5.5 mm staff size (which isn't particularly small) I've noticed they tend to disappear in print and are not well visible. Not really my domain though @oktophonie @Tantacrul

**Comment by RobFog** [comment]
Looking forward to this. In drum notation, parentheses are frequently used for ghost notes.

**Comment by Tantacrul** [comment]
I'm going to move this to 4x, since I assume we are in agreement that we shouldn't tackle it until after 4.0?

I'm also wondering if the correct parenthesis is being used here, @oktophonie? If so, do you agree they need a little engorging? (Trello me)

**Comment by mike-spa** [comment]
Yes, definitely 4.x

**Comment by oktophonie** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/17515
