### ISSUE TITLE
[MU4 Issue] Crash on inserting special character in heading or sub-heading

### ISSUE THREAD

**Issue by VanSHOE** [musescore/MuseScore#11926]
**Describe the bug**
Crash on inserting special character in heading and subheading

**To Reproduce**
Steps to reproduce the behavior (video in `Additional Context`):
1. Open a new score
2. Go to properties panel and double click the header or sub header
3. Open the insert special character box
4. Insert any character
5. It will crash

**Expected behavior**
The character should have been inserted into the text box

**Platform information**
 - OS: Windows 10

**Additional context**

https://user-images.githubusercontent.com/75690289/172584990-e4ed037e-4355-4b9b-9321-29d04d39f209.mp4

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/11927 
Tested on macOS 12, Win 11, Ubuntu 20
