### ISSUE TITLE
[MU4 Task] [GP] Simple and Common TAB staff types to be automatically applied to linked staff in specific combination with Standard staff

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#11925]
**Task description**
The rule to be implemented:
- when creating linked staff for standard staff Simple type is applied for it
- when hiding/deleting standard staff (in case standard and TAB linked staves created) Common type is applied for TAB staff

**Comment by Tantacrul** [comment]
@boryskuzmenko - is this a feature change in MS4? Or is it related to GP import.

If it is a feature request, then we should bump to 4.x to avoid more issues.

**Comment by boryskuzmenko** [comment]
@Tantacrul It's a GP import thing. With this fix user can open GP file with the same staff type as saved in GP. Now we can open every GP file as standard staves score. (e.g. Currently, if I saved a guitar part with linked standard and TAB staves in GP, and import it to MU4 - I get only one standard staff)
I'd leave this issue for now.

**Comment by Tantacrul** [comment]
OK, cheers.

**Comment by abariska** [comment]
To be fixed after https://github.com/musescore/MuseScore/issues/12624
