### ISSUE TITLE
'Pizz/Arco' & 'Mute/Open' directions cancel out dynamic directions when they happen at the same time.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#11932]
**Describe the bug**
In order to see this in action, place a change (pizz/arco) on the same beat as a dynamic change. (See video).

https://user-images.githubusercontent.com/21022311/172635043-107c04d8-1066-4181-bef8-0f048f80edc1.mov

I have also noticed this with Mute/Open although there is one important thing to note: **dynamics can also cancel out performance directions.** It seems to depend on which element you place on the score first:

https://user-images.githubusercontent.com/21022311/172636616-2f4e068a-680f-4f97-b3ce-ff3d499ac5c3.mov

**Comment by DmitryArefiev** [comment]
Fixed in #13495
