### ISSUE TITLE
[MU4 Issue] heap-buffer-overflow in framework/global/tests

### ISSUE THREAD

**Issue by AntonioBL** [musescore/MuseScore#11938]
**Describe the bug**
When running the tests after enabling AddressSanitizer, a heap-buffer-overflow is found in global_tests, happening here:
https://github.com/musescore/MuseScore/blob/master/src/framework/global/types/bytearray.cpp#L166
The corresponding line in the test is here:
https://github.com/musescore/MuseScore/blob/master/src/framework/global/tests/bytearray_tests.cpp#L90

`m_buffer_size` is left to 0 when the `ByteArray ba` is constructed here https://github.com/musescore/MuseScore/blob/master/src/framework/global/tests/bytearray_tests.cpp#L84 so that `ndata` created at line https://github.com/musescore/MuseScore/blob/master/src/framework/global/types/bytearray.cpp#L165 is not long enough to contain the original data.

A possible solution could be to ensure that `m_buffer_size` is at least equal to `m_size` (or maybe `m_size+2` ????) when using the copy constructor for the ByteArray.

**To Reproduce**
1. Compile MuseScore and the tests in debug mode with flags `-fsanitize=address -fno-omit-frame-pointer`
2. Run global_tests
3. The ByteArray_Modification test triggers a heap-buffer-overflow

**Expected behavior**
No overflows

**Platform information**
 - OS: Linux Mint 20.3

**Comment by igorkorsukov** [comment]
@AntonioBL Thank you very much, I've been wanting to rewrite the implementation for a long time, there was no reason, and now there was an excuse. Made a vector-based implementation https://github.com/musescore/MuseScore/pull/11958

**Comment by AntonioBL** [comment]
Well, thanks to you for fixing the bug. 😉
