### ISSUE TITLE
[MU4 Issue] Change instrument event doesn't always add new key signature

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#11946]
**Describe the bug**
If the instrument at the score level is non-transposing and you insert a change instrument event to a transposing instrument, the key signature is changed as expected. But the reverse is not true - starting with a transposing instrument and changing to a non-transposing one no key signature change is added/shown.

**To Reproduce**
1. Create a new score with a single instrument such as "English Horn"
2. After the 1st measure add a change instrument event to "Oboe"
3. "To Oboe" text is shown, but no key signature change

**Expected behavior**
As per the reverse scenario (starting with Oboe and adding Change Instrument to English Horn), if the instrument transposition changes a new key signature should always be shown.

**Screenshots**

**Platform information**
 - Windows 10

**Additional context**

**Comment by MarcSabatella** [comment]
FYI - iIt's an issue in MuseScore 3 when adding the instrument change from the palettes.  Strangely, it's *not* an issue in MuseScore 3 when adding from the menu (Add / Text).  I'd kind of guess the same situation might exist in MU4, except - Add / Text / Instrument Change isn't working at all for me.  I'll file that separately.

**Comment by oktophonie** [comment]
This seems to have been fixed somewhere along the line, at least as of 4.0.2.
