### ISSUE TITLE
[MU4 Issue] Many commands in Add / Text do nothing (Win/Linux)

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11947]
**Describe the bug**
If you try to add elements from the Add / Text menu, nothing happens for several of the commands.

**To Reproduce**
1. select a note in a score
2. Add / Text / Sticking
3. See error - nothing happens

**Expected behavior**
Normally, you should get an empty element in edit mode, with a visible cursor, ready for you to type.  This works as expected for Title, Staff Text, and a few other element types, but not for others - for others, nothing at all happens.

Among the commands that don't work are Sticking, Roman numeral analysis, and Nashville number, which is especially unfortunate since there is no *other* way to add these right now.  Most others have shortcuts that do work, or are also present in palettes.  Also, for Instrument change, you *can* add it from the palette, but there is a bug (present in MU3 as well) where the key signature may be added incorrectly.  In MU3, adding from Add / Text has been the recommended workaround.

**Platform information**
 - OS: Linux

**Additional context**

**Comment by DmitryArefiev** [comment]
This occurs on **Windows** and **Linux** and with all commands below (including) **Instruments change**:

![Capture](https://user-images.githubusercontent.com/90187801/185424391-350f1911-69a7-4ce1-bc0f-cbafed2e530a.PNG)

**Comment by SilverGreen93** [comment]
Although the menu does not work, pressing a shortcut such as Ctrl+L (for the menu items that have a shortcut) will work just fine.

**Comment by wizofaus** [comment]
It's odd, the menu items below "rehearsal mark" aren't hooked up to the AbstractMenuModel (handleMenuItem) at all.  I can't see any reason why those be different to the rest.  It seems fine if you access the menu items with the keyboard (ALT+A, cursor keys, enter) too, so it's something to do with the mouse position handling.

**Comment by DmitryArefiev** [comment]
Fixed in #13189
