### ISSUE TITLE
[MU4 Issue] [GP] Crash when opening saved mxcz. file twice after TAB style changes

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#11962]
**To Reproduce**
1. Open the test file in MU4 (use build https://github.com/musescore/MuseScore/pull/11716)
[test tab for MU4.gp.zip](https://github.com/musescore/MuseScore/files/8871443/test.tab.for.MU4.gp.zip)
2. Create a linked TAB Simple staff for that Standard staff
3. Save this file as .mscz score
4. Open it and change some of parameters in TAB import preferences (Format > Styles > Tabulature styles)
5. Save the score
6. Open the score (without closing app)

**Expected behavior**
Score is opened

**Screenshots**

https://user-images.githubusercontent.com/101250347/172877973-3a313f6f-34c1-4955-82c1-4dda61a58579.mov

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/11716 
Tested on macOS 12, Win 11, Ubuntu 20
