### ISSUE TITLE
[MU4 Issue] "Echo"-like effect on certain instruments 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#11976]
**Describe the bug**
This is an issue I've so far only encountered with some of the "auxiliary percussion" instruments in templates like "European concert band" and "Small pit percussion".

@Tantacrul has apparently heard this in more places, so we may expand this issue.

The following instruments within "auxiliary percussion" sound with a quasi echo/delay effect.

- Closed hi-hat
- Pedal hi-hat
- Snare side-stick
- Concert snare drum

See this video to compare MS3 with MS4 behaviour: 

https://user-images.githubusercontent.com/86290556/173083015-0377dc4a-b541-4aad-b802-67510330fd9e.mov

My guess is this is an artefact of the reverb.

This is a problem because it can aurally convey a rhythmic idea that differs from what the user notated.

**Expected behavior**
Playback sound should be clean with no aural impression of echo/delay

**Screenshots**

**Platform information**
 - Tested on MacOS 12.3.1 (M1)

**Comment by rgreen5** [comment]
This issue would be much easier to test if  #11234 could be made a priority fix; at the moment you can't play any instruments, even from the virtual piano keyboard, without entering notation as well. The reverb unit also needs to be accessible so testers can see and change the reverb properties (predelay, amount, etc).
