### ISSUE TITLE
[MU4 Issue] Crash when acting with score parts in Parts dialog after ctrl+Z

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#11977]
**Describe the bug**
The crash reproduces during any act with parts in Parts dialog after one part was opened/created and ctrl+Z used

**To Reproduce**
1. Open the test score 
[brackets.mscz.zip](https://github.com/musescore/MuseScore/files/8879650/brackets.mscz.zip)
2. Via Parts dialog open any part
3. Click ctrl+Z
4. Come back to the Parts dialog and do any action there (e.g. create new part or open another part)

**Expected behavior**
Corresponding system response is called when acting with score parts 

**Screenshots**

https://user-images.githubusercontent.com/101250347/173087636-b49245c7-6849-4bf6-8179-a460cac989e7.mov

**Comment by HemantAntony** [comment]
@boryskuzmenko I can not reproduce this in the latest master. A lot of crashes did get fixed recently with a PR. Maybe this was one of them?
