### ISSUE TITLE
[MU4 Issue] Palette names with & have weird symbols added

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#11978]
![Capture](https://user-images.githubusercontent.com/90187801/173106409-e7a3ef94-5282-451b-a77f-bce813bb8762.PNG)

**Platform information**
macOS, Windows, Linux

**Additional context**
Recent builds

**Comment by HemantAntony** [comment]
I can't reproduce in the latest master

**Comment by wizofaus** [comment]
Dang I searched to see if anyone else had already reported but didn't match this one!

**Comment by wizofaus** [comment]
Why am I seeing this then?

![image](https://user-images.githubusercontent.com/5364225/173702071-fd01ab0a-8311-488d-a8f8-da5c124ac699.png)

**Comment by wizofaus** [comment]
Seems OK now after rebuilding etc.  Still a bit unclear whether you really need to "Reset palette" for just the palette in question.
