### ISSUE TITLE
Open or New Score commands opens new instance of Musescore (rather than staying within the existing window)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#11989]
**Describe the bug**

In MS3, Ctrl + N, New Score, works within the existing window, adding the new score as another tab. However, this nightly is launching another instance of MS4.

**To Reproduce**

1. Open any score.
2. Press Ctrl + N (File > New)

RESULT: A new instance of MS4 is launched.

**Expected behavior**

The new score should be created as a tab within the existing MS4 window.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2478704457, revision: github-musescore-musescore-594ee1a

**Comment by HemantAntony** [comment]
This is by design. If I remember correctly, there was issues implementing VSTs in the old way

**Comment by rgreen5** [comment]
1. Open a score.
2. Open another one.

_Expected result_: Scores should open in same window as separate tabs.
_Actual result_: A new instance of the program is launched eact time.

**Comment by HemantAntony** [comment]
Again, same thing. There was a problem with implementing VSTs when you have scores as separate tabs

**Comment by Tantacrul** [comment]
Exactly, this was an unfortunate necessity, given how we are now supporting far more CPU intensive plugins.

**Comment by topquark22** [comment]
So there is no way to have multiple tabs in the same instance? What's the point of tabs then? I need to copy/paste from one score to another.

**Comment by MarcSabatella** [comment]
You can copy and paste between scores already, no need for tabs to do that.  Just because the scores happen to be in different windows doesn’t change how copy and paste works at all.
