### ISSUE TITLE
[MU4 Task] Restore the 'Add' context submenu for horizontal and vertical frames

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#11982]
Right-clicking on a horizontal or vertical frame in MuseScore 3 revealed a context menu with options to add text and images. There was also an option to add horizontal frames _inside_ vertical frames to create a table structure. These options should be provided in MU4.

MU3 scores that already contain frames with text and images open correctly in MU4, so we're just missing the option to add new text and images.

### Vertical Frames (`VBox`)

![image](https://user-images.githubusercontent.com/11011881/173132288-514a8cca-4098-42a8-8f7f-0318c356c62d.png)

MU4 needs to provide all the options in the Add submenu. Notice that the user can add as many instances of these elements as they like (e.g. multiple 'Title' text elements, multiple horizontal frames, multiple images, etc.). In the screenshot, clicking Add > Title again would add a third title, it wouldn't edit one of the existing ones. The new title would overlap with Title 1 (I dragged Title 2 down to make the image easier to understand). Multiple text instances are necessary to create scores like [this](https://musescore.com/openscore/scores/5673458) (see page 4).

### Horizontal Frames (`HBox`)

![image](https://user-images.githubusercontent.com/11011881/173137711-1226fd42-22db-44a0-ab90-29aeb52d2e96.png)

Horizontal frames are more restrictive in terms of what can be added to them, but it is still possible to add multiple text instances and multiple images.

### Text Frames (`TBox`)

![image](https://user-images.githubusercontent.com/11011881/173138372-b8be8f8e-68dc-4add-939a-b77dfb8d2391.png)

Ordinary text frames don't need an 'Add' submenu because they can only contain a single text instance, which you add by double-clicking on the text frame itself. This is already working in MU4. Text frames cannot contain images.

## Additional context
The main Add menu at the top of the screen doesn't help us here. It behaves the same as it did in MU3.  It has options to add Title, Subtitle, etc. text, but it only adds that text to the very first vertical frame in the score. It doesn't add text to horizontal frames or to subsequent vertical frames. It also doesn't allow adding images, and it doesn't allow adding horizontal frames inside vertical frames, hence we need the context menus back.

![image](https://user-images.githubusercontent.com/11011881/173133501-02518cb7-e743-42ed-ba63-64dbc321c6e9.png)

**Comment by DmitryArefiev** [comment]
Fixed in #12882 

All is fixed except **the option to add horizontal frames inside vertical frames** ('Add' context submenu in Vertical frame). I've logged that separately #12930
