### ISSUE TITLE
[MU4 Issue] Downwards glissando not playing back

### ISSUE THREAD

**Issue by Uncodeable864** [musescore/MuseScore#11999]
**Describe the bug**
When adding an gliss to to notes, glisses that start high and end low do not play back. On the other hand, glisses that start low and end high do play back

**To Reproduce**
1. Create a new file with a grand staff
2. In the treble clef, place two notes (with one first one higher than the second)
3. Add a "straight glissando" in between the notes 
4. Play the notes back, and only the second note will be played (the first note and silent and there is no playback of the gliss)

**Expected behavior**
The downwards gliss plays back

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/49599682/173408860-37b71696-2591-46b2-8e8f-8799e606ea45.png)

**Platform information**
 - OS: macOS M1

**Additional context**
N/A

**Comment by Tantacrul** [comment]
Confirmed on MacOS. Happens for everything, as far as I can see.

**Comment by boryskuzmenko** [comment]
The issue is partly fixed. 
There's still an issue: all notes inside downwards glissando play sustained.
https://user-images.githubusercontent.com/101250347/179019216-f601a705-ae37-4955-9e9d-4c2586bac8fa.mov

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12371
