### ISSUE TITLE
[MU4 Issue] Dragging hairpin across dynamic causes odd behaviour

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#11997]
**Describe the bug**
When trying to drag a hairpin *past* an existing dynamic marking (_**p**_, _**f**_ _etc._), it doesn't drag as unexpected and can change length very unexpectedly.

**To Reproduce**
1. Create a new score and enter in a few notes
2. Add a dynamic marking (say _**f**_) to the last note
3. Select the first couple of notes as a range and add a hairpin (so that it finishes before the dynamic added in step 2)
4. Drag the hairpin (middle grip) to the right, past the _**f**_
5. Hairpin squashes up and refuses to go past the _**f**_
6. Drag the hairpin to the top of the staff then past the _**f**_
7. Notice that its length suddenly increases, sometimes by a huge amount
8. Drag back and forth and over hairpin and notice increasingly unexpected results.

**Expected behavior**
Dynamic should not change length unpredictably and it should be possible to easily drag it from one side of the dynamic marking to the other.
Ideally I would expect it *should* be possible to have a dynamic marking drawn over a hairpin in a readable fashion, e.g. by putting a "gap" in the hairpin.  e.g. from:

![image](https://user-images.githubusercontent.com/5364225/173262125-f367a58f-6b2f-4df6-ada6-23652ec451f3.png)

to:

![image](https://user-images.githubusercontent.com/5364225/173262055-640af700-9bb1-4bff-bb23-63a94f6c0bc4.png)

to:

![image](https://user-images.githubusercontent.com/5364225/173262056-7d5928ff-ec6b-46aa-95f9-758e8c0e5d1f.png)

Alternatively the dynamic should move down out of the way of the hairpin (as that's what you're dragging, so having that jump about vertically wouldn't be nice):

![image](https://user-images.githubusercontent.com/5364225/173262259-6452191d-becf-4e28-924a-d4b413653972.png)

Even v3's behaviour here is not ideal, but it's a good deal better than v4's.  Even just having the hairpin draw right over the top of the dynamic would be better than what it does currently.

**Screenshots**

**Platform information**
 - Windows 10

**Additional context**
Nightly build from Jun-10

**Comment by Tantacrul** [comment]
From testing this, both MS3 and MS4 are both equally appalling. We're not going to be tackling this for 4.0.

However, a **proper** overhaul to hairpins is on the cards in 4.x
