### ISSUE TITLE
Loop playback of section also repeats first note of following measure

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12004]
**Describe the bug**
If you specify loop playback of a section of the score (full measures), playback also includes the first note of the following measure.

**To Reproduce**

1. Open the attached score. 
[loop_playback.zip](https://github.com/musescore/MuseScore/files/8898846/loop_playback.zip)

2. Turn on "loop playback" for one or more measures. Then press play.

RESULT: After the first play through, playback includes the first note of the following measure in error (even though it is not included in the selection).

**Expected behavior**

Only the notes measures selected for loop playback should actually play back.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2492766781, revision: github-musescore-musescore-80d0eb6

**Comment by zacjansheski** [comment]
I just tried this (Ubuntu).  If it is still an issue on Mint we can re-open, but I will close this for now since this is about a year old.

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231610304, revision: github-musescore-musescore-644a78d

Playback fine here as well.
