### ISSUE TITLE
[Optional Task] Add Finale's Maestro and Broadway fonts

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#12001]
**Task description**
This is a task that does not need to be implemented for 4.0. However, if a community member is interested, these are the fonts that it would make the most sense for us to include:

- **Finale Maestro (& Finale Maestro Text)**
- **Finale Broadway (& Finale Broadway Text**

You can get them here: https://makemusic.zendesk.com/hc/en-us/articles/1500013053461-MakeMusic-Fonts-and-Licensing-Information

Note: we would only merge this if the fonts have no issues, which should be the case if they are now indeed proper SMuFL fonts, especially after the cleanup we did for SMuFL support last year.

**Comment by Jojo-Schmitz** [comment]
Unfortunaltely they are not just plain downloadable, you'd have it download an msi (Windows) or pkg (Mac) file and install them, to then extract, add to MuseScore and uninstall them again.

**Comment by cbjeukendrup** [comment]
I'v just extracted them from the pkg installer and will put the extracted versions in MuseScore 😎

**Comment by Jojo-Schmitz** [comment]
Yeah, it seems possible to open the msi file with 7Zip, as I just found out
