### ISSUE TITLE
[MU4 Issue] Crash on clicking on any button in part name's context menu

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#12005]
**Describe the bug**
After you right click on a part name, click on any option, you get a crash. Aside from this way of reproducing you don't even need to click on a button. You can just click outside the popup.

**To Reproduce**
1. Right click on a part name
2. Click on any option
3. MuseScore crashes

**Expected behavior**
MuseScore should not crash on clicking button in the context menu

**Screenshots**
This following shows both ways of reproducing the crash

https://user-images.githubusercontent.com/88136054/173555720-78ef0528-2f24-4ab3-b40c-57d6eab6fa97.mp4

**Platform information**
 - OS: Windows 11

**Additional context**
@Tantacrul imho, this is a critical crash

**Comment by Tantacrul** [comment]
Added a P0. Thanks @HemantAntony !

**Comment by wizofaus** [comment]
NB this is only recent, wasn't happening in a build from a few days ago (but reproduced with last night's build).

**Comment by DmitryArefiev** [comment]
> NB this is only recent, wasn't happening in a build from a few days ago (but reproduced with last night's build). Very easy to reproduce in debugger and see cause, related to accessibility changes (selectedElement->accessible() is returning nullptr)
> 
> Most likely fixed by #12013 ?

Yes, confirm the crash in previous master and was not able to repro after merging #12013 to master
