### ISSUE TITLE
[MU4 Issue] Bold typeface as default for chord symbol typeface causes accidentals to be hidden in chord symbols

### ISSUE THREAD

**Issue by a-munro** [musescore/MuseScore#12012]
**Describe the bug**
Accidentals are not shown in chord symbols when the chord symbol:
(i) contains a symbol that turned into an accidental - i.e. # or b
AND
(ii) the chord symbol is set to Bold _and_ this is set as default for the entire score. 

**To Reproduce**
Open a new score. Add a chord symbol containing a sharp sign above any chord / note. 
--> Chord symbol should show correctly (see screenshot 1)
Click chord symbol and change the typeface to Bold --> Click on more settings (...) and set this as default for the whole score.
--> Sharp sign in chord symbol disappears (see screenshot 2)

**Expected behavior**
Sharp and flat signs persist in displaying regardless of typeface setting (Bold / Italic).

**Screenshots**
Attached, as noted above. 

**Platform information**
OS: Ubuntu 22.04 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2492766781, revision: github-musescore-musescore-80d0eb6

**Additional context**
![Screenshot from 2022-06-14 17-01-11](https://user-images.githubusercontent.com/64255835/173623907-cc64570a-de63-4458-9806-d74eec5f1384.png)
![Screenshot from 2022-06-14 17-01-38](https://user-images.githubusercontent.com/64255835/173623924-211a34af-0b62-4ebd-96f6-30fa543c4297.png)

**Comment by oktophonie** [comment]
Actually an Edwin problem rather than MuseScore itself, per se; see: https://github.com/MuseScoreFonts/Edwin/issues/11
A fix is actually almost ready, I just need to make a new Edwin release.

**Comment by a-munro** [comment]
Apologies - I thought I'd searched everywhere to see if this was already an issue.
