### ISSUE TITLE
[MU4 Issue] Fix slight spacing issue with the avatar button in the Home tab

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#12016]
**Describe the bug**
Currently, the avatar button (where it shows my face) is flush against the top bar. There is a space below it that separates it from the menu items. I've hovered over the button so you can see the gap below:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/21022311/173694517-41cf9799-e6cb-4048-b48a-ba2680c11fc0.png">

It would look much better if the gap was above the avatar, not below it. So just swap them around:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/21022311/173694629-e15e78b9-42ef-4dc9-81e8-865ffd84c0a6.png">

**Comment by Tantacrul** [comment]
@HemantAntony / @VanSHOE / @miiizen - a super trivial one, if any of you fancy it.

Doubt the core team will have time.

**Comment by wizofaus** [comment]
Can be done replacing "spacing: 20" in HomeMenu.qml (line 58) with

        Rectangle {
             height: 15
        } 

But not sure if that's the ideal solution.  Looks like this:

![image](https://user-images.githubusercontent.com/5364225/173700265-f49018ab-1a50-4291-be52-c0876c2fd019.png)

**Comment by cbjeukendrup** [comment]
Creating a Rectangle is not really a good idea, since it always has a color and therefore needs to be drawn. Using simply `Item { height: 15 }` would already be better, since that adds no unnecessary drawing overhead. But it still involves creating an almost useless `Item` object. The really correct solution is to give the `ColumnLayout` some `anchors.topMargin: 15` (or 20 or whatever).

**Comment by cbjeukendrup** [comment]
Actually it would be quite fun to give a crash course QML for designers (and everyone else who hasn't learned it yet)... Maybe I could do something like that, this summer!

**Comment by Tantacrul** [comment]
> Actually it would be quite fun to give a crash course QML for designers (and everyone else who hasn't learned it yet)... Maybe I could do something like that, this summer!

Yes please! When I was at Microsoft, I generally fixed these kinds of things myself.

**Comment by wizofaus** [comment]
> Creating a Rectangle is not really a good idea, since it always has a color and therefore needs to be drawn (even when you set the color the same as the color of the item behind it). Using simply `Item { height: 15 }` would already be better, since that adds no unnecessary drawing overhead. But it still involves creating an almost useless `Item` object. The really correct solution is to give the `ColumnLayout` some `anchors.topMargin: 15` (or 20 or whatever).

Yeah, I figured there would probably would be a better way to do it, though I would hardly be worried about the overhead, not likely to make any measurable difference to performance.
