### ISSUE TITLE
[MU4 Issue] When opening a non-existing (deleted) file, you get the corruption dialog instead of missing file dialog

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12028]
**To Reproduce**
1. Open score A from a Flash drive
2. Close score A
3. Eject Flash drive
4. Try to open score A from Recent scores - **you get the corruption dialog instead of missing file dialog**

### Actual result:

![Capture](https://user-images.githubusercontent.com/90187801/224660204-0f31815b-376a-4a18-8507-b872bf6321df.PNG)

### Previous actual result:

**MU shows "File open error" instead of "File not found" message** 

![Capture2](https://user-images.githubusercontent.com/90187801/224660268-ea311f24-a913-47e9-91ca-0abdbdfbacea.png)

**Expected behavior**
MU should show message about the file is missing

**Platform information**
macOS, Windows, Linux

**Additional context**
#8884

**Comment by DmitryArefiev** [comment]
@Tantacrul Putting to Beta2 with P3 but I think can be moved to 4.x.x as well

**Comment by cbjeukendrup** [comment]
It looks like this issue has become a bit more strange. Now, when opening a non-existing file, you get the corruption dialog! When you click "Show details", you see "Error opening the file".

**Comment by DmitryArefiev** [comment]
Yes, the same on my side:

![Capture](https://user-images.githubusercontent.com/90187801/220156894-380feab9-484c-4c1d-b967-c017786134e4.PNG)

FYI @Eism
