### ISSUE TITLE
No tooltips in Properties sidebar

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12021]
**Describe the bug**
After selecting a score element and hovering the mouse over various properties in the Properties sidebar, absolutely NO tooltips are visible. In MS3 they appeared, as expected.

**To Reproduce**

1. Open a score.
2. Click on a text element, say, such as "Title", then hover the mouse over various items in the Properties sidebar.

RESULT: NO tooltips visible at all.

**Expected behavior**

Tooltips should appear if you hover the mouse over various properties in the sidebar when a score element is selected.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2499731453, revision: github-musescore-musescore-d8b6263

**Comment by Tantacrul** [comment]
Bumping to 4.x as a feature request.

The new inspector is a lot clearer than the old one and the old one didn't have all that many tooltips.

However, we should definitely include more of them - just not for 4.0.
