### ISSUE TITLE
"Change time signature" button (Properties sidebar) should be "Time signature properties"

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12022]
**Describe the bug**

if you want to change an existing time signature, the method of choice should be to select it and click on a new time signature from the palettes.

In MS4, if you select an existing time signature, there is a button in the Properties sidebar called "Change time signature". The wording is wrong since this is _not_ the function of the dialog – which is actually to change the text _appearance_ of the time sig. or the beaming of notes under its "jurisdiction".

IMV, this button should revert to "Time signature properties" (as the option was in MS3 and before).

**To Reproduce**

1. Select a time signature.
2. Inspect the properties sidebar for the "Change time signature" button.

**Expected behavior**

The button should be called "Time signature properties" (or suchlike).

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2499731453, revision: github-musescore-musescore-d8b6263

**Comment by Tantacrul** [comment]
Yeah, I agree - since you can't actually change the time signature using this (awful) modal. Thanks!
