### ISSUE TITLE
[MU4 Issue] [GP] Harmonic text mark visibility rules are wrong for GP import

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12030]
**Description**
Actual rules:
- any harmonic mark is rendered for standard staff
- any harmonic mark is not rendered for TAB Simple staff

**To Reproduce**
1. Import test GP file to MU4
2. Pay attention to measure 10

**Screenshots**
![Capture 2022-06-15_06-54-33_PM](https://user-images.githubusercontent.com/101250347/173871858-ce9febf2-8132-4fe3-830a-7630553fbb82.png)

**Expected behavior**
- any harmonic mark is rendered not for standard staff
- any harmonic mark is rendered for TAB Simple staff

![Capture 2022-06-15_06-52-36_PM](https://user-images.githubusercontent.com/101250347/173871893-7a366b1b-514b-492d-8c7c-b585501b9941.png)

**Comment by alexpavlov96** [comment]
@abariska already solved, please check

**Comment by abariska** [comment]
🟢 **FIXED** in scope of xtz fixes
