### ISSUE TITLE
[MU4 Issue] [GP] Arpeggio and Strumming elements are not rendered for standard staff after GP import

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12035]
**To Reproduce**
1. Open test GP file 
[test tab for MU4.gp.zip](https://github.com/musescore/MuseScore/files/8911222/test.tab.for.MU4.gp.zip)
2. Pay attention to measure 18 on standard staff

**Expected behavior**
Arpeggio and Strumming elements are rendered for standard staff 

**Screenshots**
![Capture 2022-06-15_07-25-30_PM](https://user-images.githubusercontent.com/101250347/173877870-28d0e3cf-8470-4d1c-afb5-2b880d38e7b4.png)

**Comment by alexpavlov96** [comment]
@abariska it is styled this way, should it be changed still?

**Comment by abariska** [comment]
@alexpavlov96 yep, lets show these elements for both notation types. First, to be consistent with xtz and current native MU behavior
