### ISSUE TITLE
MS4 crashes causing wider system problems

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12038]
**Describe the bug**

System details: OS: Linux Mint 20.1, Arch.: x86_64. / Cinnamon 4.8.6.

Over the past two weeks I have experienced two MS4 crashes which have affected the wider system. This has only happened with MS4; with MS3 nightlies the crashes never affected the system itself.

1. A few weeks ago (sorry, I didn't record the nightly details), my Cinnamon desktop crashed while using an MS4 AppImage nightly. This was an unusual and one-off event; never happened with any other app.
2.  Today, while using MS4, the whole system froze for half a minute or so. MS4 eventually crashed, but seems to have corrupted some system files, leading to a general slowdown and making it difficult to reboot the PC (eventually resolved by restoring a previous system image using Timeshift). MuseScore version (64-bit):4.0.0-2499731453, revision: github-musescore-musescore-d8b6263

I don't have sufficient technical knowledge to provide any useful data for developers, but there seems to be an unresolved problem with MS4 that is leading to system instability.

**Comment by wizofaus** [comment]
If a user-level application like MuseScore can do that to your operating system, my first reaction is get a better operating system!
The only thing an application can do that causes system-wide issues is to use up too much CPU, memory or HD space.  
Unfortunately I can't see any realistic chance that a developer would be able to take this issue and figure out how to "fix" anything in MuseScore itself.
FWIW I haven't observed anything similar at all under Windows 10.  My only issue is how much HD space all the tools required to build it from source take up (including all the intermediate binaries etc.)!

**Comment by Tantacrul** [comment]
Closing as unfixable. But we've noted your complaint.
