### ISSUE TITLE
[MU4 Issue] MuseScore_amd64 failed to run "global_test" on release and debug configuration with MSVC on windows. 

### ISSUE THREAD

**Issue by rachelhe123** [musescore/MuseScore#12047]
**Describe the bug**
MuseScore_amd64 failed to run "global_test" on release and debug configuration with MSVC on windows. Could you please help look at this issue or provide some workarounds? Thanks in advance.

**To Reproduce**
1. git clone https://github.com/musescore/MuseScore F:\gitP\musescore\MuseScore
2. mkdir F:\gitP\musescore\MuseScore\build_amd64
3. cd F:\gitP\musescore\MuseScore\build_amd64
4. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBUILD_UNIT_TESTS=ON -DCMAKE_BUILD_TYPE=Release .. 
5. msbuild /m /p:Platform=x64 /p:Configuration=Release mscore.sln /t:Rebuild 
6. ctest --build-config Release --output-on-failure -E "engraving_utests|iex_braille_tests|iex_capella_tests|iex_musicxml_tests"

**Expected behavior**
For MuseScore_amd64, "global_test" test should be run pass on the windows.

**Error Message**
[----------] Global test environment tear-down
[==========] 55 tests from 9 test suites ran. (791 ms total)
[  PASSED  ] 51 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] Global_IO_IODeviceTests.Open_ReadOnly
[  FAILED  ] Global_IO_IODeviceTests.Open_WriteOnly
[  FAILED  ] Global_IO_FileInfoTests.IsRelative
[  FAILED  ] Global_IO_FileInfoTests.IsAbsolut

**Platform information**
 OS: Windows

**Setup**
VS 2019 + Windows Server 2019

**Additional context**
test log
[test.log](https://github.com/musescore/MuseScore/files/8916366/test.log)
[test.log.3.out.txt](https://github.com/musescore/MuseScore/files/8916368/test.log.3.out.txt)

**Comment by Tantacrul** [comment]
@cbjeukendrup - since I can see a PR from you, I've assigned you. Please close when finished.

**Comment by cbjeukendrup** [comment]
@igorkorsukov Do you agree with my previous comment? If so, we can close this.
