### ISSUE TITLE
[MU4 Issue] Video tutorials (in 'Learn') are very often 'unable to load'

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#12054]
**Describe the bug**
As you can see below, this is the most common message I see when I click on the learn section, despite being connected to the internet. (MacOS). I'm wondering whether there is a refresh setting that could check from time to time to see if the user is connected, so the videos can display? It only sometimes works.

<img width="1723" alt="image" src="https://user-images.githubusercontent.com/21022311/174079100-8402a649-0935-47b1-b2ab-26f81b1f0865.png">

**Comment by Eism** [comment]
Yes, it works for me. I'll investigate why it might not work for you.

**Comment by Tantacrul** [comment]
This is what I got. @cbjeukendrup doesn't think this has anything to do with the issue here:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/21022311/174096480-1710564c-25dc-4511-89ee-9d704d901575.png">
