### ISSUE TITLE
Fretboard diagrams: "click zone" extends too far away from the left-hand edge of fretboard

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12053]
**Describe the bug**
Normally, you create a finger dot on a fretboard diagram by hovering over the desired string and fret position, then clicking. However the active area for clicking finger dots on to the leftmost string also includes a significant area to the left of the fretboard.

The area area needs to be more focused so that the "click zone" ends at the fretboard edge.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2506665316, revision: github-musescore-musescore-c31e7fb

**Comment by Tantacrul** [comment]
I think this is too trivial to be an issue we should concern ourselves with. I'm closing as a **won't fix**

Thanks for mentioning it though. We'll be redesigning this system soon enough anyway and will tackle it then.
