### ISSUE TITLE
[MU4 Issue] Repeat command doesn't work properly in note input mode (makes duplications and range selection)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12055]
**To Reproduce**
1. Select measure
2. Press c (to enter C note)
3. Press r - **it makes two C notes after (instead of one) and doing a range selection of the last note (instead of moving cursor to the next empty beat)**. See video to compare with MU3 

https://user-images.githubusercontent.com/90187801/174087710-8bb23034-2762-47a5-8a0a-e0885be930f8.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by wizofaus** [comment]
Happy to have a look at this, as I definitely worked on this area at some point.

**Comment by DmitryArefiev** [comment]
> Happy to have a look at this, as I definitely worked on this area at some point.
> 
> Edit: wasn't to do with anything I'd changed, but an easy fix _for notes_. It still doesn't work for rests - but nor does it in v3!

Thanks for fixing that! 

Yes, I see it doesn't work in MU3 as well so could be fixed later..

**Comment by DmitryArefiev** [comment]
> > Happy to have a look at this, as I definitely worked on this area at some point.
> > Edit: wasn't to do with anything I'd changed, but an easy fix _for notes_. It still doesn't work for rests - but nor does it in v3!
> 
> Thanks for fixing that!
> 
> Yes, I see it doesn't work in MU3 as well so could be fixed later..

Actually I see now when input rests, Repeat command is not needed because hitting 0 multiple times doing the same thing (rests do not have so many parameters as notes)
