### ISSUE TITLE
Fretboard diagrams: No "Fret number" property?

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12052]
**Describe the bug**

There seems to be no way to change the _fret number_ on a fretboard diagram. An oversight has omitted the "**Fret number**" from the Properties sidebar!

MS3 Inspector:

![ms3_inspector](https://user-images.githubusercontent.com/87246583/174061885-6f3f5f2d-14c8-40f6-9c94-5131b60b0623.png)

MS4 Properties sidebar (note the gap where, presumably, "Fret number" should be):

![ms4_properties](https://user-images.githubusercontent.com/87246583/174061968-17d53cd6-5dd7-447a-91c0-02790dab35d6.png)

Note also that "Clear" does not clear the existing fret number.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2506665316, revision: github-musescore-musescore-c31e7fb

**Comment by Tantacrul** [comment]
Very good point. I don't know how we missed this. Thanks!

**Comment by HemantAntony** [comment]
@Tantacrul I have created a PR. Check #12282
