### ISSUE TITLE
[MU4 Task] Co-location of selected "lines" palette elements within other palettes

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#12069]
@HemantAntony given your previous recent work on palettes, I thought this one might be of interest to you. Let us know if you have the time! 

## Goal
To co-locate elements in the current Lines palette within other palettes (new and existing), based on a musical-notation logic rather than a purely visual logic.

## Rationale
Currently, elements in Lines palette are included because they are lines, whereas elements in all other palettes are organised according to their musical function and/or notational conventions.

This task will align the UX logic of these elements with that of the other palettes.

In addition, it creates opportunities to offer new default palettes that cater to instrument-specific notation requirements of some of our largest user groups (piano and guitar). 

Once this task has been implemented, the current Lines palette should not be deleted, but could instead be hidden by default.

## List of palettes shown by default (new)

- Clefs
- Key signatures
- Time signatures
- Tempo
- Pitch
- Accidentals
- Dynamics
- Articulations
- Text
- Keyboards
- Repeats & jumps
- Barlines
- Layout

## List of palettes hidden by default (new)

- Brackets
- Ornaments
- Breaths & pauses
- Grace notes
- Noteheads
- Arpeggios & glissandi
- Tremolos
- Guitar
- Fingering
- Fretboard diagrams
- Accordion
- Bagpipe embellishments
- Beam properties
- Lines

### Dynamics
Co-locating:

- Crescendo line
- Diminuendo line
- Crescendo hairpin
- Diminuendo hairpin

<img width="294" alt="dynamics-new" src="https://user-images.githubusercontent.com/86290556/174278802-5a350895-7e57-4679-b723-2cd3f57f5792.png">

Co-locating but hiding by default:

- Dynamic + hairpin

Hiding by default (existing elements):

- sfpp

### Articulations
Co-locating:

- Slur
 
Hiding by default:

- Laissez vibrer (l.v.) above 

<img width="293" alt="articulations-new" src="https://user-images.githubusercontent.com/86290556/174278845-3c4cb67b-c66e-4562-9d76-3f2a17f94ae2.png">

### Repeats & Jumps
Co-locating:

- Prima volta
- Seconda volta, open
- Seconda volta
- Terza volta

Co-locating but hiding by default:

- Vibrato sawtooth
- Tremolo sawtooth wide

Hiding by default (existing elements):

- D.C. al Double Coda
- D.S. al Double Coda
- Dal Segno Segno
- D.S.S. al Coda
- D.S.S. al Double Coda
- D.S.S. al Fine
- Da Coda
- Da Double Coda

<img width="299" alt="repeats-and-jumps-new" src="https://user-images.githubusercontent.com/86290556/174278896-32d386a2-3401-4f3d-b547-e2baf0bf6008.png">

### Ornaments
Co-locating:

- Trill line
- Upprall line
- Downprall line
- Prallprall line

Overall palette properties specifications (new):

- Width = 73
- Height = 27
- Element offset = 0sp
- Scale = 1
- Show grid = yes

<img width="2053" alt="Ornaments-palette-content-scaling" src="https://user-images.githubusercontent.com/86290556/174279175-a72ded23-2046-412f-a4a2-895663471449.png">

_Note: individual palette element scaling specified in red above_

### Text
Co-locating:

- Staff text line
- System text line

Overall palette properties specifications (new):

- Width = 100
- Height = 28
- Element offset = 0sp
- Scale = 0.85
- Show grid = yes

<img width="600" alt="text-new" src="https://user-images.githubusercontent.com/86290556/174279219-98cb98c5-d94b-4768-b9b6-324fd8303c2e.png">

_Note: System text line requires a new icon. It should be drawn in the same manner as staff text line:_

<img width="500" alt="System-text-line-icon" src="https://user-images.githubusercontent.com/86290556/174279243-f0358f1a-2349-4e9e-a0cc-932a96fe96b3.png">

### Guitar
Co-locating:

- Text line (and renaming to Capo line)
- Palm mute
- Let ring
- Bend
- Tremolo bar
- Guitar vibrato
- Guitar vibrato wide
- RH guitar fingering p
- RH guitar fingering i
- RH guitar fingering m
- RH guitar fingering a
- RH guitar fingering c
- LH guitar fingering 0
- LH guitar fingering 1
- LH guitar fingering 2
- LH guitar fingering 3
- LH guitar fingering 4
- LH guitar fingering 5
- LH guitar fingering T
- String number 0
- String number 1
- String number 2
- String number 3
- String number 4
- String number 5
- String number 6
- Thumb position
- Right-hand fingering, thumb
- Right-hand fingering, first finger
- Right-hand fingering, second finger
- Right-hand fingering, third finger
- Distort* 
- Overdrive*

*These come from the Text palette. Due to a bug, I am unable to insert these into any custom palette, so they don't appear in the mockup below

Overall palette specifications:

- Width = 60
- Height = 33
- Element offset = 0sp
- Scale = 1.2
- Show grid = yes

<img width="1559" alt="Guitar-palette-new" src="https://user-images.githubusercontent.com/86290556/174279336-a982fea4-2445-4b10-9d49-289a38bd31ea.png">

_Note: individual palette element scaling specified in red above. All other elements are scaled at 1.0._

### Keyboards
Co-locating:

- Pedal (with ped and asterisk)
- Pedal (with ped and line)
- Pedal (straight hooks)
- Pedal (angled end hook)
- Pedal (both hooks angled)
- Pedal (angled start hook)

Overall palette specifications:

- Width = 73
- Height = 30
- Element offset = 0sp
- Scale = 1
- Show grid = yes

<img width="295" alt="keyboard-new" src="https://user-images.githubusercontent.com/86290556/174279370-83d74e68-5f4d-4474-b176-f81ec411ae30.png">

### Pitch
Co-locating:

- 8va alta
- 8va bassa
- 15ma alta
- 15ma bassa

Co-locating but hiding by default:
- 22ma alta
- 22ma bassa
- Ambitus

Overal palette specifications:

- Width = 100
- Height = 30
- Element offset = 0sp
- Scale = 0.8
- Show grid = yes

<img width="298" alt="pitch-new-2" src="https://user-images.githubusercontent.com/86290556/174309440-4426766c-e8b9-4940-ad8f-07dd991e8173.png">

**Comment by HemantAntony** [comment]
Working on it!

**Comment by bkunda** [comment]
> Working on it!

Legend. Thank you! 🙏🏻

**Comment by wizofaus** [comment]
Was there a really a decision to definitely do this for 4.0? Putting hairpins in a palette with dynamic markings in may seem logical, but I can see it leading to a fair bit of confusion (as hairpins most definitely behave nothing like dynamic markings).
And "Staff lines" and "System lines" definitely behave nothing like other text elements.
Having the organisational model of the palettes vary so much from the underlying model (which is based on how the objects behave as you interact with them and as they're drawn on the score) wouldn't be something I'd look for in a music notation software package, but I get I'm not a 'regular' user...

**Comment by Tantacrul** [comment]
@wizofaus - yes. We discussed this and unanimously agreed that ordering elements by how they work is less important than ordering them by purpose.

Dynamics are a very good example. They are elements that are meant to work together, and it is not obvious that you would find one in 'Lines'. Practically, it means users have to keep jumping between the two palettes for one action. I don't believe that users will look at hairpins - not that they can be extended horizontally - and then expect to be able to do also extend a pianissimo marking.

Another example is how miserable the experience is for guitarists. You have to jump all over the panel to find stuff you need - and much of it is buried away in 'More'.

Lastly, we're keeping the 'Lines' palette the way it is right now because we recognise that muscle memory needs to be respected.

**Comment by wizofaus** [comment]
Well given the palettes are completely customisable, I guess us techy users that prefer to keep things together based on what they are (rather than what they're used for) can still rearrange them to suit.  I do understand the justification for the non-technically minded users, probably just need to be careful about the Palette names.  If you actually start *calling* hairpins "dynamics" that will definitely lead to confusion.

**Comment by Tantacrul** [comment]
I don't think we want to rename any elements. Hairpins would just go in dynamics (and stay in 'lines')

**Comment by wizofaus** [comment]
I guess I'm suggesting the palette should be called hairpins and dynamics then. One is not a type of the other! (Internally dynamics are actually just text elements, and support all of the behaviors of text elements, which may or may not make sense in all cases).

**Comment by HemantAntony** [comment]
@bkunda I have a PR ready. I sadly was not able to change the System icon

I know why its happening. But I have no idea how to solve it

**Comment by cbjeukendrup** [comment]
@HemantAntony Maybe you can fix it by adjusting this line: `systemTextLine->setLen(w);`.

**Comment by HemantAntony** [comment]
I tried that, but it didn't work. If you are wondering the word System is too big to create the hook. I did think of increasing the length of the TextLine, but I couldn't find the function. I also thought `setLen()` would be it

**Comment by bkunda** [comment]
@cbjeukendrup when you get a minute could you maybe look into this one? If it's too complicated a fix then we might need to look for an alternative design solution. But ideally speaking, it would make the most sense if we can have this palette element appear like the staff text line.

**Comment by wizofaus** [comment]
You can get this adjusting the font size:

![image](https://user-images.githubusercontent.com/5364225/174693513-40c6bb66-f071-44de-8ad5-c622c20096cc.png)

**Comment by wizofaus** [comment]
The reason setting the len doesn't work is because of
```
void SLine::layout()
{
    if (score()->isPaletteScore() || (tick() == Fraction(-1, 1)) || (tick2() == Fraction::fromTicks(1))) {
        //
        // when used in a palette or while dragging from palette,
        // SLine has no parent and
        // tick and tick2 has no meaning so no layout is
        // possible and needed
        //
        setLen(score()->spatium() * 7);
```

**Comment by HemantAntony** [comment]
So there's no point in doing `setLen` at all? I did see a lot of `setLen` calls in the file

**Comment by wizofaus** [comment]
It's necessary to create the segments (`systemTextLine->segmentAt(0)` will return `nullptr` if you don't call `setLen` first). But other than that, it's pointless.

**Comment by wizofaus** [comment]
(I'm still concerned about the proposal to put hairpins in a palette called just "dynamics" btw - a hairpin is decidedly not in any functional or interactional way a type of "dynamic", even if they both happen to affect the velocity notes are played at and are often used in tandem @bkunda).

**Comment by HemantAntony** [comment]
I actually disagree with you. Dynamics is related to the volume. Similarly Hairpins are for volume too. When a new user would want to add a Hairpin, the first place they are likely to look is Dynamics because it makes sense (with the volume). It would take some time before they find it in Lines. Even if they do it will take a bit of muscle memory to remember this. I remember me looking for hairpins in the dynamics

Also, we aren't moving the hairpins. We are just adding the Hairpins to another spot to avoid possible confusion.

**Comment by wizofaus** [comment]
I don't have any problem with them being in the same "Dynamics and Hairpins" palette. Just please don't actually label them as "dynamics" because they share exactly zero behaviour and underlying functionality with hairpins (well, other than what all elements share)
