### ISSUE TITLE
[MU4 Task] [Accessiblity] Implement Return focus to score command (and shortcut)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12075]
**Task description**
Now when editing score (in accessibility mode), and applying a different operations to selected element (note, text, range selection) you need to press Tab several times to find command/window/panel in MU UI, apply command and return back to score hitting Tab multiple times. 

The goal of this task to implement **command that can quickly return blind user to editing score** from any MU location

**Comment by MarcSabatella** [comment]
FWIW, the goal in the past was always to make Esc perform this function.  In places where you're deep enough in dialogs, of course it might be necessary to press it multiple times, but the expectation was that after closing any open dialogs, you'd be back in the score.  And also if focus was in a non-modal panel, like the Inspector.  As far as I know that works everywhere in MU3 although there could be some corner case where it doesn't.  It definitely doesn't work that way at all in MU4, but that would be my vote.

**Comment by DmitryArefiev** [comment]
> FWIW, the goal in the past was always to make Esc perform this function. In places where you're deep enough in dialogs, of course it might be necessary to press it multiple times, but the expectation was that after closing any open dialogs, you'd be back in the score. And also if focus was in a non-modal panel, like the Inspector. As far as I know that works everywhere in MU3 although there could be some corner case where it doesn't. It definitely doesn't work that way at all in MU4, but that would be my vote.

@MarcSabatella  That's good idea about Esc. Thanks!

@Eism FYI

**Comment by DmitryArefiev** [comment]
Implemented in #13010
