### ISSUE TITLE
[MU4 Issue] [GP] Line elements are divided when rests present under it

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#12076]
**Describe the bug**
There're affected elements:
- octave up/down
- let-ring
- palm mute
- rasgueado

**To Reproduce**
1. Open the test file in MU4
[Line elements with rests.gp.zip](https://github.com/musescore/MuseScore/files/8929131/Line.elements.with.rests.gp.zip)
2. Pay attention to the division of line elements

**Screenshots**
![Capture 2022-06-17_07-09-36_PM](https://user-images.githubusercontent.com/101250347/174338287-5b6991e1-cd72-47be-864f-539b033e8f56.png)

**Expected behavior**
Line elements are not divided when rests present under it
![Capture 2022-06-17_07-08-50_PM](https://user-images.githubusercontent.com/101250347/174338313-715d2414-3e04-4f6d-bbb1-999590a930f7.png)

**Comment by wizofaus** [comment]
NB to be clear this only when importing from GP, doesn't happen normally (regardless of which version the score was created in)

**Comment by boryskuzmenko** [comment]
@wizofaus it's clear due to the [GP] in the summary

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12095
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by alexpavlov96** [comment]
<img width="295" alt="Screenshot 2022-06-21 at 19 29 16" src="https://user-images.githubusercontent.com/24373905/174850640-8d79e9ec-9b84-4ae6-b513-8e1b6a156b9f.png">
regression: no ties and pitch octave lower

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12119
Tested on macOS 12, Win 11, Ubuntu 20
