### ISSUE TITLE
[MU4 Issue] Сrash when moving bracket 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12074]
**To Reproduce**
1. Open a score
2. Try to move bracket with mouse or keyboard arrows 

https://user-images.githubusercontent.com/90187801/174315264-494a8b47-d6f6-43e8-ac37-12d18806d09f.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Recent builds

**Comment by Tantacrul** [comment]
Jesus, these brackets....

**Comment by DmitryArefiev** [comment]
Yeah, lovely brackets))

**Comment by wizofaus** [comment]
AccessibleRoot strikes again!

        NotationUndoStack::commitChanges

 	MuseScore4.exe!mu::engraving::EngravingItem::staffIdx(void)	Unknown
 	MuseScore4.exe!mu::engraving::AccessibleRoot::updateStaffInfo(class mu::engraving::AccessibleItem const *,class mu::engraving::AccessibleItem const *)	Unknown
>	MuseScore4.exe!mu::engraving::AccessibleRoot::setFocusedElement(class mu::engraving::AccessibleItem *)	Unknown
 	MuseScore4.exe!mu::engraving::EngravingItem::setSelected(bool)	Unknown
 	MuseScore4.exe!mu::engraving::Selection::update(void)	Unknown

My debug info is screwed up but it looks like newAccessibleItem->element() might be null in updateStaffInfo...

**Comment by wizofaus** [comment]
Had another look at it, and there is a simple/safe fix that doesn't change the existing behaviour of internal logic of how brackets work (and in fact this crash can in principle happen for other types of elements that can get deleted/replaced when performing certain operations with the mouse or keyboard)

**Comment by wizofaus** [comment]
Strangely now I can't reproduce that latter crash.  But basically the way the code is written, any element that might get deleted during layout could have this problem.  While Barlines are the obvious case, there are certainly other types of elements that do get deleted during layout, I just haven't managed to find a reliable set of steps for reproducing a crash.
I even just managed to trigger it by clicking on the *page* (which is another element that can get deleted during layout).
