### ISSUE TITLE
Frame properties: standardise property readouts to two decimal places (as in MS3)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12071]
**Describe the bug**

Subsequent to #9841. The gap and margin properties for frames are currently displaying different numbers of decimal places. These need to be standardised so that the display always defaults to two decimal places (starting from 0.00), as was the case in MS3..

**Comment by Tantacrul** [comment]
Bumping to 4.x, as it is a trivial fix that has no real consequences, which we can tackle later.
