### ISSUE TITLE
[MU4 Issue] "." creating diminuendo hairpin instead of dotted note

### ISSUE THREAD

**Issue by rabbitdragon2** [musescore/MuseScore#12093]
With the last four pre-releases (2022-06-16,17,18,19), I have noticed that whenever I press the period key to create a dotted note, instead all I get is a diminuendo hairpin. This occurs on both macs I have worked on, MacOS monterey, default keyboard settings.

**Comment by cbjeukendrup** [comment]
It looks like this is related to #11956.

**Comment by wizofaus** [comment]
Would say so, and is MacOS specific, so will need a dev who can build on MacOS to investigate...

**Comment by cbjeukendrup** [comment]
@rabbitdragon2 I believe this has been fixed; at least for built-in shortcuts. (For customised shortcuts, we still have #14539.)

I'll close this for now, but please re-open if it still doesn't work properly for you in the latest Release Candidate build (see our Discord server / Muse Hub).
