### ISSUE TITLE
[MU4 Task] Playback line remaining in centre of screen when in continuous view

### ISSUE THREAD

**Issue by BenignPigeon** [musescore/MuseScore#12090]
**Task description**
When Musescore is in the continuous view option, I believe there should be an option for the transparent blue playback bar to remain in the middle of the screen and for the music itself to move rather than the notes jolting towards the left when the playback bar reaches the end of the screen.

This would allow the user to see what comes directly before and after the current section they are on.

https://user-images.githubusercontent.com/85837722/174452753-38ede854-49b3-4e74-8e52-7fefbf3dea52.mp4

Attached I have a very basic representation of what's desired. Please imagine that the blue line is stationary and fixed to the middle of the screen and that it's the music that's moving.

PS: I'm not sure if this is possible or if I've formatted this correctly so I apologise if it's either unclear what the request is for or if it's just not possible to implement within Musescore, or if it's already an option that I am yet to come across.

**Comment by MarcSabatella** [comment]
Actually this was already implemented and has been in MU3 for some time already, although a bit hidden.  In MU3, you enable this via options in Edit / Preferences / Advanced - the various ones labeled smoothPan.  So the absence of these controls is currently a regression in MU4.  I know there is work currently on restoring other lost preferences.  It would be great to see this added as part of that effort.  Probably no need for all the fine-grained controls that were added for MU3; the single "enable" toggle is all most people would ever want.

**Comment by cbjeukendrup** [comment]
This was implemented in https://github.com/musescore/MuseScore/pull/18718. It could still be refined a little bit, but that is already covered by https://github.com/musescore/MuseScore/issues/19210.
