### ISSUE TITLE
[MU4 Issue] Voice-To-Parts not working

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#12114]
**Describe the bug**
If a staff has two voices, e.g. soprano and alto on a condensed score, in MU it is possible to create separate soprano and alto parts where the soprano part contains the notes of voice 1 of the master score and alto the notes of voice 2 of the master score. However in both parts the voice becomes voice 1. So the alto notes in voice 2 (alto) in the master score becomes notes 

**To Reproduce**
See: 

https://user-images.githubusercontent.com/48352523/174776357-04fce035-abae-40c5-a2c5-348c87694365.mp4

Here you see a simple condensed score with a soprano in voice 1 (blue) and a alto in voice 2 (red).
Next a part `Soprano` is created which contains note of voice of the `women` staff only. Also a `Alto` part is created with voice 2 notes of the `women` staff only.
Also a more complicate part `S+A` is created in which two staves are created, on for the soprano and one for the alto.

Now there are 3 parts:

1) `Soprano` containing the blue soprano notes as voice 1.
2) `Alto` containing the red alto notes, *also* as voice 1.
3) `S+A` which is actually a combination of the `Soprano` and `Alto` parts/

This seems not possible in MU4 anymore??

**Expected behavior**
Same MU3 Voice-To-Parts functionality in MU4.

**Platform information**
 - OS: Linux

**Additional context**
n.a.

**Comment by wizofaus** [comment]
Can you create two parts for the same instrument, but hide voice 1 in one and hide voice 2 in the other?

**Comment by njvdberg** [comment]
No, the result is different. See this picture.

![Screenshot_20220621_145132](https://user-images.githubusercontent.com/48352523/174803494-bc1a2c5f-4a80-4ad4-9bfe-58de75a95d68.png)

1) First line shows the two voices in in voice 1 (blue) and voice 2 (red).
2) Second line shows the two parts but with the not wanted voices made invisible. It is clear the blue A4 should have the stem down while all red notes should have the stems down, except the C5.
3) Now all parts have there notes in voice 1 and now the stems are as expected.

What actually happens in MU3 is the voice mapping master/part score is 1-1 for part 1 and 2-1 for part 2.

**Comment by wizofaus** [comment]
Fair enough.  It definitely sounds like key functionality that got lost along the way...

**Comment by Tantacrul** [comment]
This was not lost along the way. The ability to add the same instrument to a part multiple times was something we tried to implement but ran into significant issues. This is mainly because we want to optimise the general handling of parts to be quite different to how MS3 does it currently. As it stands, we're kind of in a 'half way' territory, where supporting this particular capability (technically speaking) was going to store up a lot of trouble in future.

Of course the ability to add the same instrument multiple times to the same part times is one we do want to support. However, we planned to tackle this in a subsequent release, when we can dedicate time to more efficient part handling. The technical reasoning is best explained by @RomanPudashkin or @vpereverzev.

**Comment by njvdberg** [comment]
I'm not sure we talk about the same thing but I'm talking about mapping a voice in the main score onto another voice in the part. It sounds different as adding the same instrument to a part multiple times but maybe that's what you mean? (@Tantacrul)

Also if the technical reason can be explained I'm interested, maybe I can contribute to it.

By the way, MU3 scores using this feature can be read without problem in MU4. It looks it's mainly the UI is missing and no new voice-to-part parts can be created but if it there,you can still use it.

**Comment by cbjeukendrup** [comment]
@njvdberg With 'adding the same instrument to a part twice', we mean that in the video, for the S+A part (`Excerpt`), you add the "Women" `Part` twice, once to show only voice 1, and once to show only voice 2. This is one of the missing possibilities in MU4. 

For me, mapping voices seems to work correctly, if I use the popup in the Instruments panel. If I only show voice 2 in an `Excerpt`, the notes appear as voice 1. Isn't that expected?

**Comment by Tantacrul** [comment]
@njvdberg: voice **conversion** then?

- I have something that is Voice 1, I can convert it to be Voice 2/3/4 in a part?

If that's something we want to include, I'd need to give it a little thought from a UX point of view. A part of me thinks it could either be

1. An option in the context menu
2. A separate advanced popup of some kind

I have a sense that our internal developers would prefer to include something like this in a 4.x release to be safe. There are going to be quite a few small releases with little things over the months following 4.0. What do you think?

**Comment by MarcSabatella** [comment]
MU3 did not have a user-specified voice conversion feature - just the automatic one that would map voice 2 to voice 1 when create Flute 1 & Flute 2 parts from a single Flutes staff in the score.  Unless I'm misunderstanding something, this is the functionality that is being discussed.

My impression is the functionality *is* still present but located in a different place.  It is now accessed via the Instruments panel, not the Parts window:

![image](https://user-images.githubusercontent.com/1799936/175306829-5bffcda9-218c-4bf6-a440-8c1a2c20ee73.png)

However, it's still rather mysterious to me how it works exactly.  I see the documentation in https://musescore.org/en/handbook/4/parts#Choose_which_voices_appear_in_each_part 

But somehow, if I create Flute 1 and Flute 2 parts in the Parts window and go through these steps, the measure appear empty.  It seems that only notes added to the score *after* going through these steps will appear in the part.  That's got to be a bug.  But the feature itself *is* there as far as I can tell, and does work at least sometimes.

**Comment by wizofaus** [comment]
As far as I can tell you can definitely do what the original reported seemed to think MS4 couldn't support.
There's definitely some weirdness with the Parts dialog (reported elsewhere), but the functionality to hide all but one voice and have that show with normal stem direction etc. seems to work fine.

**Comment by Tantacrul** [comment]
I'm going to bump to 4.x for the time being. We have a lot of work to do on Parts and I **think** we should tackle some of the issues mentioned here at that time.

(Excepting the crash @wizofaus, which should be logged separately)

**Comment by njvdberg** [comment]
Excuses, the feature **is** there indeed but slightly hidden for me (@MarcSabatella, thanks for the link to the manual).
So this issue is solved.

**Comment by Tantacrul** [comment]
(phew!)

**Comment by MarcSabatella** [comment]
I'll file a separate issue on the issue where it only works for notes you add after creating parts.  Hopefully it turns out to be something simple.
