### ISSUE TITLE
Tablature: note input cursor has spurious line on left edge of blue rectangle

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12124]
**Describe the bug**

If you select a tablature measure, say, then go into note input mode, the cursor should appear as a blue rectangle on the active string. But in MS4 there is an additional spurious black line on the left edge of the cursor. See screenshots below.

**To Reproduce**

1. Create a new tablature score
2. Click on the first measure and enter note input mode (N)
3. Enter a few notes.

RESULT: There is a black line on the left edge of the blue rectangle.

**Expected behavior**

The cursor should be a blue rectangle, as it was in MS 3.

**Screenshots**

MS3 versus MS4:

![ms3](https://user-images.githubusercontent.com/87246583/174995037-421e00f3-f9d8-4633-9be9-a2c7fcffceac.png)![ms4](https://user-images.githubusercontent.com/87246583/174995048-1a4fbc59-0548-4d1e-ac87-5efc7c758109.png)

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2539818534, revision: github-musescore-musescore-a0fd49e

**Comment by Tantacrul** [comment]
Not spurious. By design. Also better
