### ISSUE TITLE
[MU4 Issue] Missing icons on Plugins page

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12127]
![Capture](https://user-images.githubusercontent.com/90187801/175025914-768d662c-e292-47f6-9273-d9c50b4d321d.PNG)

**Screenshots**

**Platform information**
**Windows 10**
Can't reproduce on Mac/Lin

**Comment by jessjwilliamson** [comment]
Yes, thank you Dmitry for reporting, it's the same on my Windows too!

**Comment by DmitryArefiev** [comment]
Fixed in #12132
