### ISSUE TITLE
[MU4 Task] New image for Muse Sounds library + New Copy

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#12130]
**Task description**
Were now have imagery and text for the second panel in the 'Getting Started' flow. We have assets ready for whoever implements this. @jessjwilliamson will send the visual asset.

String:
Title: **Playback**
Description: **Enjoy realistic playback for free by downloading our new Muse Sounds library**

Screenshot:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/21022311/175038194-df4cebb3-96a8-494d-b41e-ed391fce4d20.png">

**Comment by Tantacrul** [comment]
@HemantAntony - pretty please!

**Comment by Tantacrul** [comment]
Assigned to Alpha 2 due to the string changes, since we want to issue string freeze before Beta.

**Comment by RobFog** [comment]
Would it be a good idea to inform the user about the size of the download? It's pretty large, right?

**Comment by HemantAntony** [comment]
@Tantacrul I'm working on it :)
