### ISSUE TITLE
[MU4 issue] Stems and beams are placed on the wrong side of the tablature staff

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12144]
**Describe the bug**

It appears that stems and beams are being placed on the wrong side of the tablature staff.

**To Reproduce**

1. import the attached MS3 file.
[a_rag.zip](https://github.com/musescore/MuseScore/files/8967021/a_rag.zip)
2. Notice the placement of stems and beams in the tablature and the fact that they do not coincide with the notation in the standard staff.
3. ![ms4_tab](https://user-images.githubusercontent.com/87246583/175296269-d9ba2075-8db5-4211-b44b-3d77c03a5b5c.png)
4. Compare this with the correct appearance in MS3.
![ms3_tab](https://user-images.githubusercontent.com/87246583/175296247-5f31a82d-0855-4580-828a-f598688b13ab.png)

**Expected behavior**

The stem and beam positions in tablature should always coincide with that shown in the standard staff

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2546690257, revision: github-musescore-musescore-a8f4a8c

**Comment by boryskuzmenko** [comment]
It's definitely a bug which relates only Common tab staff type. It could be a part of [this regression](https://github.com/musescore/MuseScore/pull/11857), but could be not. 
Also, there's another bug with 2 voices on the same note. Will report it separately.

**Comment by RomanPudashkin** [comment]
@asattely could you please help with this bug? Thank you!

**Comment by asattely** [comment]
On it now!

**Comment by asattely** [comment]
Can you confirm that this is still an issue in the current master, @rgreen5 or @RomanPudashkin? I suspect this might have been an issue that was fixed by some other PR.

**Comment by asattely** [comment]
Seems that this one has been solved by https://github.com/musescore/MuseScore/pull/13188! If not, let me know.

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3005092866, revision: github-musescore-musescore-a7329b5

Looks OK here.
