### ISSUE TITLE
[MU4 Issue] Holding Cmd/Ctr+Q to quit makes multiple copies of "Do you want to save cahnges.."dialog (and leads to crash on Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12150]
**To Reproduce**
1. Open a score 
2. Make some changes
3. Press and hold Cmd+Q (Ctr+Q on Win/Lin) - **it makes multiple copies of "Do you want to save changes.."window**

**Mac/Lin**

https://user-images.githubusercontent.com/90187801/175382687-1b685711-90de-42b1-a840-a11567de2800.mov

**Win**

https://user-images.githubusercontent.com/90187801/175382738-fd7d6964-abbf-483d-8212-2352b0e750c8.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
On **Windows** it leads to **crash**

Doesn't occur in **MU3**

**Comment by wizofaus** [comment]
Ctrl+Q can cause a crash in quite a lot of cases where secondary top-level windows are being shown actually, trying to work out a good generic way to prevent it.

**Comment by DmitryArefiev** [comment]
Fixed in #12152

**Comment by DmitryArefiev** [comment]
> Ctrl+Q can cause a crash in quite a lot of cases where secondary top-level windows are being shown actually, trying to work out a good generic way to prevent it.

@wizofaus Thanks for fixing! #12152 seems to be fine
