### ISSUE TITLE
[MU4 Issue] Voices don't work correctly after Part opening/creating

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12154]
**To Reproduce**
1. Create a score with piano staff
2. Open Piano part (via Parts dialog)
3. Unselect 1, 2 and 3 voices
4. Use Undo (voices still unselected
5. Use Undo again (only 3 voice returned back to selected state)
6. Any next Undo's do not return back 1 voice.

Also check this issue for more information about this bug https://github.com/musescore/MuseScore/issues/12116

**Expected behavior**
Undo works once it's applied. All voices can be returned back to the selected state by using Undo

**Screenshots**

https://user-images.githubusercontent.com/101250347/175491481-e9e1dc2e-4941-4f04-a7fe-bec7636c9b26.mov

**Comment by DmitryArefiev** [comment]
Fixed in #17327
