### ISSUE TITLE
[MU4 Issue] New score with compound time has incorrect tempo

### ISSUE THREAD

**Issue by olivercoad** [musescore/MuseScore#12153]
**Describe the bug**
Depending on the time signature and tempo mark picked when creating a new score, sometimes it uses the wrong value for the tempo.

**To Reproduce**
1. Go to 'Home'
2. Click on 'New Score'
3. Add an instrument and click next
4. Change the time signature to '6 8'
5. Change the tempo to 'dotted crochet = 60'
6. Click 'Done'
7. Observe the tempo on the score is 'dotted crochet = 40'

**Expected behavior**
It should be 'dotted crochet = 60'.
The tempo used on the score should be the same as what is selected in the new score wizard, regardless of the time signature.

**Screenshots**
![image](https://user-images.githubusercontent.com/24837994/175488792-3cb9c319-9f18-4a3f-8798-c939d8d4f3b5.png)  
![image](https://user-images.githubusercontent.com/24837994/175488834-19a6e14c-fa0a-4cc9-a6a6-23f9118dd87a.png)  

**Platform information**
 - OS: Windows
 - Version: `MuseScoreNightly-202206240438-master-c8ce0c4-x86_64`

**Comment by wizofaus** [comment]
For step 5, how are you "changing" the tempo? Can't reproduce by just editing the text anyway...

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12158
Tested on macOS 12, Win 11, Ubuntu 20
