### ISSUE TITLE
Tab or Ctrl+Tab not allowing access to all options [MU4 Issue]

### ISSUE THREAD

**Issue by eg0n1984** [musescore/MuseScore#12166]
The Tab or Ctrl+Tab option is not allowing access to some option on the New Score menu

1. Go to 'Additional Score Information'
2. Click on 'Key Signature'
3. Pres Tab or Ctrl+Tab, multiple times
4. It will be possible step between 3 fields but not accessible the others
5. See error

**Expected behavior**
Access to all fiels on the menu with Tab or Ctrl+Tab

Video attached

**Platform information**
 - OS: Windows

https://user-images.githubusercontent.com/28876087/175773047-d3b83d8e-b79b-4cf9-bf8a-5fe4ef06fdb0.mp4

**Comment by mxmou** [comment]
This appears to be intended: https://github.com/musescore/MuseScore/issues/10919#issuecomment-1102809644
Up/down arrow keys work as expected.
