### ISSUE TITLE
[MU4 Task]player mode

### ISSUE THREAD

**Issue by litong01** [musescore/MuseScore#12167]
**Task description**
Can musescore support a player mode so that during the playback, only selected instrument stuff will be displayed? For example, for the `carol of the bells` trumpt and Alto Sax duet, if I am a saxophone player, while I am playing Saxophone, I may not want to see the stuff for the trumpet, can one simply select just the A. Saxophone, so that Musescore only display Saxophone stuff, not the entire stuff, this way, during the playback, it will also reduce the score movement since the display window now only need to show one stuff vs showing many. This will also solve the problems if there are so many instruments for a piece.

**Comment by cbjeukendrup** [comment]
You can already create parts showing only one instrument. For the instructions for MuseScore 3, see https://musescore.org/en/handbook/3/parts. In MuseScore 4 it will be so straight-forward that you probably won't even need instructions.

**Comment by litong01** [comment]
@cbjeukendrup Thanks for following up on this.
