### ISSUE TITLE
[MU4 Issue] Beams broken in imported MS3 tablature

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12177]
**Describe the bug**
Beams are broken in this imported MS3 lute tablature.
MS3:
![ms3_tab](https://user-images.githubusercontent.com/87246583/175914074-82db53d0-7d07-40e2-b918-bad82b7fd02b.png)
MS4:
![ms4_tab](https://user-images.githubusercontent.com/87246583/175914103-97c0ad61-4be8-4558-a9b8-9255634d6b3f.png)

**To Reproduce**

1. Unzip attached file and open in MS4 and MS3.
[dowland_lute_tab.zip](https://github.com/musescore/MuseScore/files/8990806/dowland_lute_tab.zip)

RESULT: Beams are broken in MS4.

**Expected behavior**

Appearance of score should be almost identical in both scores with beam appearance in MS4 the same as in MS3.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2566765347, revision: github-musescore-musescore-415d5c0

**Comment by cbjeukendrup** [comment]
This _might_ be partly improved by a commit in my Feathered beams PR: https://github.com/musescore/MuseScore/pull/12082/commits/c1facd4fd00cfedbacee9f04af6437b74f8758e1.
