### ISSUE TITLE
[MU4 Issue] Preferences > Program Start Naming Inconsistency

### ISSUE THREAD

**Issue by JC-ProgJava** [musescore/MuseScore#12172]
**Describe the bug**
There are naming inconsistencies in the "Program start" tab under "General" in Preferences.

**To Reproduce**
1. Open Preferences > General > Program start
2. See error

**Expected behavior**
1. Both mentions of 'program' should be spelled in the same way.

**Screenshots**
<img width="441" alt="Issue" src="https://user-images.githubusercontent.com/61588096/175846828-28a99bea-bcc2-46dc-8375-a2f4b8062fac.png">

**Additional context**
- Locale: en-US
- Reported env: macOS 12.1 (although probably affects all envs)
- MS Version: 4.0.0.2553485363

**Comment by JC-ProgJava** [comment]
Mention of "Programme start":
https://github.com/musescore/MuseScore/blob/3eb416085aa03e21523a0895c80357d15aa06b75/src/appshell/qml/Preferences/internal/ProgrammeStartSection.qml#L30

**Comment by Eism** [comment]
Here's what it looks like in [Figma](https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/Musescore-Notation-App-MASTER?node-id=3106%3A28112). So, need to rename to 'Programme start'
![image](https://user-images.githubusercontent.com/10116828/175865824-8eac3396-65b8-4bb0-9c45-808a12c5ccff.png)

@jessjwilliamson FYI

**Comment by Jojo-Schmitz** [comment]
No, "Programme start" is British English, "Program start" American English, so it should be the latter. The rest is work for the translators

**Comment by GabeS573** [comment]
Another similar misspelling occurs on the Plugins page, where the word color is spelled as both "Color" and "Colour." See screenshot:
![image](https://user-images.githubusercontent.com/91428485/178344172-f27e37f7-0db9-4f23-b04d-f79d044a329d.png)

**Comment by GabeS573** [comment]
Yet another British spelling is on the My Account page where the word "favorite" is spelled as "favourite." Screenshot:
![image](https://user-images.githubusercontent.com/91428485/178345913-4207e646-0fe7-4b59-9bb9-8eccb27b6997.png)

**Comment by Jojo-Schmitz** [comment]
Yep, neds to be "color" and "favorite"

**Comment by jessjwilliamson** [comment]
It has come to realisation me and @Tantacrul have been making these Figma mockups in British English (English GB) , the wording of course doesn't apply to English US language. Apologies this have been confusing but I appreciate the clean up of this.

**Comment by HemantAntony** [comment]
Also, shouldn't this be 'Customize toolbar' instead of 'Customise toolbar':
![image](https://user-images.githubusercontent.com/88136054/178445797-d8e93439-39d4-452b-ba57-e7a49b61cd6f.png)

**Comment by Jojo-Schmitz** [comment]
Yes

**Comment by Jojo-Schmitz** [comment]
Issue had been resolved a while ago.
