### ISSUE TITLE
Period tablature: "cue marks" for bass courses are not being shown in note-input mode

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12170]
**Describe the bug**

In period tablature (Baroque lute, Theorbo etc.), the space below the 6th line is used to show notes on bass courses. Although fretmarks can still be entered in MS4 as before, the "cue marks" are not being displayed, so the user does not know which course they are entering the note onto.

MS3: showing "cue mark" (in note input mode) indicating the currently active bass course (missing in MS4):
![ms3_bass_courses](https://user-images.githubusercontent.com/87246583/175814742-8c75ba43-54c7-4e11-947c-1816f6fd409f.png)

MS4: no cue mark:
![ms4_no_cue_mark](https://user-images.githubusercontent.com/87246583/175904858-f264d894-2c25-4c64-b3f2-d08e04af29f9.png)

(There is also a bug with the appearance of the cursor, reported separately in #12171.)

**To Reproduce**

1. Open the attached score (MS3) for Baroque (13 string) lute.
[13_string_lute.zip](https://github.com/musescore/MuseScore/files/8986634/13_string_lute.zip)

2. Press N for note input mode.
3. Move cursor with the down arrow so that it rests in the space below the sixth string.
4. Now continue to press the down arrow.
5. Compare this with a similar score in MS3.

RESULT: The cursor is not showing "cue marks" for the active bass course. As you press the down arrow the appropriate bass course _does_ becomes active, and this can be show by entering a note – it will appear correctly. However without the correct cue mark the user does not know which bass course s/he is on.

**Expected behavior**

In note input mode, as the cursor moves up or down through the bass courses it should display a cue mark (on the left of the cursor) to show the user which course is currently "active:
no cue = 7th course,
/ = 8th course,
// = 9th course,
/// = 10th course,
4 = 11th course
5 = 12th course
6 = 13th course
7 = 14th course
8 = 15th course

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2562915295, revision: github-musescore-musescore-415d5c0

**Comment by Tantacrul** [comment]
Excellent find @rgreen5. Thank you!

**Comment by Tantacrul** [comment]
@boryskuzmenko / @alexpavlov96 : I think this might be one for you. What do you think?

**Comment by DmitryArefiev** [comment]
Fixed in #13130
