### ISSUE TITLE
[MU4 Issue]  Staccato doesn't play properly in fast tempo (or with small duration notes)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12178]
https://user-images.githubusercontent.com/90187801/175983554-f6c5499c-0cff-469d-94cb-734125be097c.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by wizofaus** [comment]
BTW your video demonstrates the issue with the first note being louder than others, which I'd noted before...

**Comment by DmitryArefiev** [comment]
No longer occurs

Tested in **latest master** on Win10, Mac12, LinuxMint 20.2 - **FIXED**

Closing
