### ISSUE TITLE
[MU4 Task] Publish to MuseScore.com should be hidden until it's properly implemented on musescore.com

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12188]
**Task description**
Just hide **Publish to MuseScore.com** button grey out on Publish tab (and in File menu)

![Capture](https://user-images.githubusercontent.com/90187801/176138384-5af05e2e-31cd-45fd-9920-874a9688a581.PNG)

**Comment by DmitryArefiev** [comment]
Hi @cbjeukendrup , let's just **hide the button** (from Publish tab and File menu). I'll rewrite the summary.
Thanks!

**Comment by cbjeukendrup** [comment]
@DmitryArefiev Thanks, I updated the PR!

**Comment by DmitryArefiev** [comment]
Fixed in #12200
