### ISSUE TITLE
[MU4 Issue] Export format dropdown is blocked if any other dropdown (Mixers sound ot 3 dot dropdown) is open in Mixer (Mac only)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12182]
https://user-images.githubusercontent.com/90187801/176007731-af3c44cb-4f11-4902-9b2f-3f82ca011150.mp4

**Platform information**
 macOS only

**Comment by cbjeukendrup** [comment]
Additional info: the dropdown menu does appear, but it appears behind the export dialog.
<img width="1440" alt="Scherm­afbeelding 2023-02-18 om 22 28 12" src="https://user-images.githubusercontent.com/48658420/219900286-19d92b4b-aecf-4cb4-b348-4e8864d8be58.png">

**Comment by zacjansheski** [comment]
@DmitryArefiev I just tried this and I don't think it is happening anymore (dropdown closes when export window opens)

**Comment by DmitryArefiev** [comment]
@zacjansheski Yes, it doesn't occur on my side too in **latest 4.1 master, Mac13** (but happens in 4.0.2)

Thanks for checking!

Closing
