### ISSUE TITLE
[MU4 Issue] Instruments missing key in their names

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#12180]
**Describe the bug**
Instead of displaying instruments like 'Clarinet in B♭', their names are being displayed as 'Clarinet in '

**To Reproduce**
1. Click New score
2. Double click on Bass Clarinet
3. Instead of 'Clarinet in B♭', 'Clarinet in ' is displayed

**Expected behavior**
'Clarinet in B♭' should be displayed instead of 'Clarinet in '

**Screenshots**

https://user-images.githubusercontent.com/88136054/175992729-27e3e91a-1054-448f-8929-f4b10f8e97d1.mp4

**Platform information**
 - OS: Windows 11

**Additional context**
If my title is weird, feel free to change it. I didn't have a better one
I wonder if this is related to the recent switch to `String` from `QString`

@Tantacrul this seems important

**Comment by Tantacrul** [comment]
Confirmed on MacOS

**Comment by Tantacrul** [comment]
@oktophonie / @shoogle - any ideas how or when this happened and what could resolve it?

**Comment by DmitryArefiev** [comment]
Looks good in #12207
