### ISSUE TITLE
[MU4 Improvement] Ability to add glissando to all chord notes when whole chord is selected

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#12190]
**Describe the bug**
Ability to add glissando to all chord notes when whole chord is selected

**Screenshots**

https://user-images.githubusercontent.com/101250347/176152297-3a28bc51-6f06-45e9-ae3a-78f6593b727b.mov

**Comment by Tantacrul** [comment]
👍

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12306
Tested on macOS 12, Win 11, Ubuntu 20
