### ISSUE TITLE
[MU4 Issue] Score looks blurry on 125%, 150% DPI scaling and FullHD displays (Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12193]
**Describe the bug**
This occurs after #10285 implementation and just requires additional work to fix the blurry issue in score

**To Reproduce**
1. Go to Settings>Scale and Layout and set **100%**
2. Open score in MU
3. Go to Settings>Scale and Layout and set **150%**
4. Notice the score elements (text especially) became not so sharp as the were on **100**

https://user-images.githubusercontent.com/90187801/176193217-2c8927db-71df-4818-b61e-fcbb6faffef2.mp4

**Platform information**
Windows10

**Additional context**
That blurry effect not so noticeable on QHD, 4K displays

**Comment by DmitryArefiev** [comment]
Fixed in #12591

**Comment by DmitryArefiev** [comment]
@bkunda or @jessjwilliamson This is fixed and in master now! Can you check it briefly on your side please (Windows, High Res Display on 125,150,175,200)?

Now score elements and palettes should look fine.

Thanks!

**Comment by jessjwilliamson** [comment]
Yep! Looks lovely! <3 

Related topic - If there is some work done related to scaling, I'd really appreciate if[ this issue](https://github.com/musescore/MuseScore/issues/9893#issuecomment-1205440868) gets fixed. I basically can't use VSTs in Musescore unless I'm using 100% only. I work 200% because I have 4k screen but I can imagine this will be problematic for a lot of users who can't use 100%.

**Comment by DmitryArefiev** [comment]
Cool! Thanks!

> Related topic - If there is some work done related to scaling, I'd really appreciate ifhttps://github.com/musescore/MuseScore/issues/9893#issuecomment-1205440868 gets fixed. I basically can't use VSTs in Musescore unless I'm using 100% only. I work 200% because I have 4k screen but I can imagine this will be problematic for a lot of users who can't use 100%.

Absolutely agree. Now I have the same problem with my new Windows laptop and QHD display.
