### ISSUE TITLE
[MU4 Issue] Crash closing score with linked parts and slurs (Windows/Linux)

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#12205]
**Describe the bug**
You can crash MuseScore quite easily by creating linked parts and slurs then closing without saving

**To Reproduce**
1. Create a score
2. Ensure at least one part is "created" (opened) for it
3. In the opened part, add a note and a slur
4. Close main score without saving
5. MuseScore crashes

https://user-images.githubusercontent.com/90187801/177056857-0c974e53-6c69-44ad-8526-3583d2a886aa.mp4

**Expected behavior**
No crash would be nice

**Screenshots**

**Platform information**
- Windows 10
- Doesn't crash on Mac

**Additional context**
Debug build running under Visual Studio using latest code from master branch.

_First was 0xFFFFFFFFFFFFFFFF.

>	MuseScore4.exe!std::list<mu::engraving::EngravingObject *,std::allocator<mu::engraving::EngravingObject *>>::remove_if<bool <lambda>(mu::engraving::EngravingObject * const &)>(std::list<mu::engraving::EngravingObject *,std::allocator<mu::engraving::EngravingObject *>>::remove::__l2::bool <lambda>(mu::engraving::EngravingObject * const &) _Pred) Line 1613	C++
 	MuseScore4.exe!std::list<mu::engraving::EngravingObject *,std::allocator<mu::engraving::EngravingObject *>>::remove(mu::engraving::EngravingObject * const & _Val) Line 1604	C++
 	MuseScore4.exe!mu::engraving::EngravingObject::removeChild(mu::engraving::EngravingObject * o) Line 198	C++
 	MuseScore4.exe!mu::engraving::EngravingObject::~EngravingObject() Line 111	C++
 	MuseScore4.exe!mu::engraving::EngravingItem::~EngravingItem() Line 184	C++
 	MuseScore4.exe!mu::engraving::Spanner::~Spanner() Line 406	C++
 	MuseScore4.exe!mu::engraving::SlurTie::~SlurTie() Line 450	C++
 	MuseScore4.exe!mu::engraving::Slur::~Slur() Line 73	C++
 	[External Code]	
 	MuseScore4.exe!mu::engraving::Score::~Score() Line 418	C++

NB in some cases instead of crashing it just gets stuck in an infinite loop.
Note that the EngravingObject pointed to by "this" had already been deleted.

**Comment by boryskuzmenko** [comment]
Can't reproduce it on macOS.
@DmitryArefiev could you try to reproduce on WIN and Linux, please?

**Comment by wizofaus** [comment]
To be fair there were some cases it didn't happen, try with different creation options (various templates etc.). And may be less likely with a release build, where freeing memory doesn't necessarily invalidate the data there.

**Comment by wizofaus** [comment]
Just confirmed it's still occurring with latest master source, but it didn't happen using just the Treble clef template, only the Grand Staff template.  Have had it happen creating without template too.

**Comment by DmitryArefiev** [comment]
I can't reproduce it on Windows10 as well (latest master)..

@wizofaus Can you attach a video demonstration please? (you can use Bandicam screen recorder from https://www.bandicam.com, it's a free app and very easy to use). Thanks!

**Comment by wizofaus** [comment]
Won't be able to until next week,  but it's 100% reproducible running under debugger if creating from piano template - always crashes in the same spot.

**Comment by DmitryArefiev** [comment]
Oh, I found the steps now!  In step #3 was not specified that the note+slur should be added to the part (not to the score). I will edit the description. 

https://user-images.githubusercontent.com/90187801/177056814-c7cf8c87-eb66-4893-9f20-9f2940ed1ee9.mp4

**Comment by wizofaus** [comment]
To be fair there were some cases it didn't happen, try with different creation options (various templates etc.). And may be less likely with a release build, where deleting memory doesn't necessarily invalidate the data there.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
