### ISSUE TITLE
[MU4 Issue] Flags colide with noteheads

### ISSUE THREAD

**Issue by KaiVinter** [musescore/MuseScore#12216]
**Describe the bug**

Flags colide with noteheads and I doubt it's something desired

**To Reproduce**

1. Create a score
2. Input a note with a flag
3. Select flag or notehead

**Expected behavior**

Flags shouldn't colide (? Probably? Or at least not that much in some cases)

**Screenshots**

![Screen Shot 2022-06-29 at 11 18 07 AM](https://user-images.githubusercontent.com/88064903/176507884-663939bf-5c74-4190-90e2-db56ac99c5a1.png) ![Screen Shot 2022-06-29 at 11 17 57 AM](https://user-images.githubusercontent.com/88064903/176507890-80f10b2d-1641-4bd3-bed7-1b36d6b15bc5.png) ![Screen Shot 2022-06-29 at 11 17 30 AM](https://user-images.githubusercontent.com/88064903/176507893-a54c1ca7-05ec-4387-802d-ddbe8875b1ce.png) ![Screen Shot 2022-06-29 at 11 17 22 AM](https://user-images.githubusercontent.com/88064903/176507894-5e131315-c231-4a32-a18e-1d87a136dffd.png) ![Screen Shot 2022-06-29 at 11 26 03 AM](https://user-images.githubusercontent.com/88064903/176509244-f83b34a7-eafb-4455-9624-d659c4943330.png)

**Video**

https://user-images.githubusercontent.com/88064903/176508786-a280efe4-3eba-47f3-bd20-17389bffaa42.mp4

**Platform information**

 - OS: macOS Mojave 10.14.6
 - Tested on MuseScoreNightly-202206290442-master-9d40605.dmg | 2022-06-29 04:55 | 194M |

**Comment by KaiVinter** [comment]
Oh, I see. I agree the overlap right now is too much. So far MS4 has become a ton better than last time I tried a Nightly, though.
One more thing. Flags appear to behave like rectangle images instead of vectors, and I was filling an Issue about that as well. Should I submit that as well? Or that's how it's supposed to behave?

**Comment by Tantacrul** [comment]
@oktophonie, @asattely, @mike-spa - I assigned to you, unless you disagree?
