### ISSUE TITLE
[MU4 Issue] Notes played staccato under slur

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12210]
**Describe the bug**
In a piano score, all notes after the first under a slur are played staccato

**To Reproduce**

1. Enter four quarter notes into the top staff of any measure of a piano score
2. Add a slur
3. Press play

The first note is played legato, the others staccato.

**Expected behavior**
All notes should be legato, with at most a slight shortening of the last note of the slur.

**Screenshots**

![image](https://user-images.githubusercontent.com/1799936/176453375-77947fa7-9b45-4651-abf7-b94ed6d3dd00.png)

**Platform information**
 - OS: Linux

**Additional context**
This relates to https://github.com/musescore/MuseScore/issues/11012.  Some of the issues demonstrated in that previous issue appear to have been fixed, but simple cases like this have not.

FWIW, I noticed this playing the score "Reunion" that I originally created as the demo for an earlier version of MuseScore.  I still find this very useful as a test of any of things, since it was specifically designed to show off lots of features of the program within a single page.  See https://musescore.com/marcsabatella/reunion

In this score, many notes under slurs *do* play back legato, but other do not.  In trying to reproduce a simple sample case, I discovered that in new scores at least, it's really all notes except the first that play staccato.  In other scores, it seems to work if slurs are present for all voices but fails if there are sluts for one voice/staff only.

Related observation: notes are also played staccato during note input now

**Comment by Tantacrul** [comment]
This also manifests differently for soundfont and VST. It is possibly the single worst playback issue that remains. Vasily is working on it at the moment. I might close this if I discover another issue that covers the same thing. This particular issue has been reported a few times... but each one is slightly different.
