### ISSUE TITLE
[MU4 Issue] Scrollbar colides with dropdown list in the New Score Wizard > Time Signature

### ISSUE THREAD

**Issue by KaiVinter** [musescore/MuseScore#12221]
**Describe the bug**

There's a scrollbar that appears over a dropdown list.
Also, is the scrollbar needed? Will there be more options there?
Scrolling with the mouse doesn't seem to work either way, only dragging the scrollbar.

**To Reproduce**

1. Open the New Score Wizard to create a new score
2. Add an instrument and click "Next"
3. Click "Time Signature"
4. Move your cursor to the right side of the pop-up
5. See the scroll bar

**Expected behavior**

Either the scrollbar placed more to the right, or not any scrollbar.

**Video**

https://user-images.githubusercontent.com/88064903/176571584-22cb5f24-d39f-4202-9bb5-41fcffd2810e.mp4

**Platform information**
 - OS: macOS Mojave 10.14.6
 - Tested on MuseScoreNightly-202206290442-master-9d40605.dmg | 2022-06-29 04:55 | 194M |

**Comment by sammik** [comment]
Similar in instruments dialog #11124

**Comment by Tantacrul** [comment]
Ah, never noticed this before! Nice catch.
