### ISSUE TITLE
[MU4 Task] Preferences > Import > Style used for import not yet connected

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12225]
In Preferences > Import, the "Style used for import" setting is not yet connected. Its value is stored in the MusicXML* configuration, but never read from there. 

\* If this is a MusicXML specific setting, it should be in the MusicXML section on the page; if it is a general import setting, it should not be stored in the MusicXML configuration but in a more general place.

**Comment by wizofaus** [comment]
Definitely seems like a generic setting to me.  Looks like it should be easy to implement anyway.

**Comment by RomanPudashkin** [comment]
Also see: https://github.com/musescore/MuseScore/pull/12448

The "Guitar Pro import character set" option is no longer supported

**Comment by wizofaus** [comment]
@cbjeukendrup would be good to have actual repro steps/expected behaviour described here!
