### ISSUE TITLE
[MU4 Issue] Wrong pitch for MuseScore General playback device in exported audio (Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12237]
https://user-images.githubusercontent.com/90187801/176912302-6eaadfcd-ba5e-4a61-8984-c5f9024515d5.mp4

**Platform information**
Windows

**Additional context**
Changing sample rate export setting to 32kHz or 48kHz doesn't fix the issue

**Comment by Tantacrul** [comment]
Also happening on MacOS. I changed this to P0.

**Comment by vpereverzev** [comment]
Fixed in #12566
