### ISSUE TITLE
[MU4 Issue] Reordering instruments in Instruments panel only works in one direction (Parts)

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#12235]
**Describe the bug**
When changing the order of instruments using the Instruments panel in a part, staves only change order when moving instruments "upwards". Moving instruments "down" has no effect.

See demo video: https://www.dropbox.com/s/yqxscjzfayi48op/reordering%20instruments.mov?dl=0

**Expected behavior**
Reordering should work in both directions

**Platform information**
 - MacOS 12.3.1 (M1)

**Additional context**
Lag shown in the above video relates to [#8871](https://github.com/musescore/MuseScore/issues/8871)

**Comment by wizofaus** [comment]
Can't reproduce at all on Windows, either dragging or using Up/Down buttons.  Does it happen with a brand new/empty score?

**Comment by bkunda** [comment]
> Can't reproduce at all on Windows, either dragging or using Up/Down buttons. Does it happen with a brand new/empty score?

@wizofaus I reproduced this on Windows using the nightly build from 1 July:

https://www.dropbox.com/s/pdw0ajywq0impq6/Recording%202022-07-04%20at%2016.21.47.mp4?dl=0

FWIW this video shows a newly created score from template. I was also able to reproduce the same issue after creating a new score and adding the same instruments manually.

**Comment by Tantacrul** [comment]
If this is still persisting, it's a P0, not a P2.

I can't replicate it on MacOS myself. Anyone else?

**Comment by bkunda** [comment]
My apologies, I now see that I didn't specify that this issue only seems to occur in parts. I shall correct the issue description now.

**Comment by lyrra** [comment]
Can't reproduce on linux. Tried to add parts.

**Comment by wizofaus** [comment]
Can you attach the score and provide textual instructions on how to reproduce from a "clean" start (reset factory settings, or reinstall etc.)

**Comment by sammik** [comment]
> * on the same panel, drag the violin II part up and down, after a few attempts you can end up with a different order between what's in the instrument panel and what's on the score

To be more precise:
reordering direction down doesnt work
reordering direction up works

(Linux)

**Comment by wizofaus** [comment]
I couldn't see any predictable difference between moving up or down, just that after enough attempts you could definitely end up with them being out of sync.
