### ISSUE TITLE
[MU4 Issue] AppImage: default paper color black; cannot reset

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12247]
**Describe the bug**
In the latest AppImage, for some reason the default paper color has been set to black.

 OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2603809362, revision: github-musescore-musescore-c83d663

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2613746296, revision: github-musescore-musescore-b70aa9b

Still the same issue. What's worse is that every time you reset the paper colour to white, it turns black again when you reopen the program.

**Comment by cbjeukendrup** [comment]
Sounds like something is wrong with either the reading or the writing of (color) settings. @igorkorsukov You worked on this recently, maybe this is something for you to look at?
