### ISSUE TITLE
[MU4 Issue] Crash when using Palette search and showing tooltips

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12249]
**Describe the bug**
When searching in the Palettes, a crash can occur related to the showing/hiding of tooltips.

**To Reproduce**
1. Open the search field in Palettes.
2. Type a character, so that some search results appear.
3. Put the mouse on one of the cells in the search results, to show a tooltip for that cell.
4. Type another character that causes the cell with the tooltip to disappear (because it is no longer a search result).
5. The crash occurs, because the cell that was the parent of the tooltip has been deleted while the tooltip itself is still alive. Some error messages in the console say:
```
14:57:37.133 | ERROR | main_thread | AppShell   | run: error: qrc:/qml/MuseScore/UiComponents/StyledPopupView.qml:76: TypeError: Cannot read property 'isOpened' of null

14:57:37.133 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/StyledPopupView.qml:76: TypeError: Cannot read property 'isOpened' of null
14:57:37.133 | ERROR | main_thread | AppShell   | run: error: qrc:/qml/MuseScore/UiComponents/StyledPopupView.qml:78: TypeError: Cannot read property 'isOpened' of null

14:57:37.133 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/StyledPopupView.qml:78: TypeError: Cannot read property 'isOpened' of null
```

**Platform information**
 - OS: reported on macOS

**Comment by DmitryArefiev** [comment]
Fixed in #12266
