### ISSUE TITLE
[MU4 Issue] Instrument names are empty when adding new instruments

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#12255]
**Describe the bug**
Adding further instruments to a score via the Instruments dialog shows the new instruments with only a number next to their corresponding stave (i.e. no instrument name). Further, instrument names are empty in both the Parts dialog and the Instruments dialog itself. 

https://www.dropbox.com/s/vtzrehlob6mypwi/empty-instrument-names.mov?dl=0

N.B. This must be a recent regression as it was not a problem in the nightly from 29 June.

**Expected behavior**
All newly added instruments should appear with correct labels.

**Platform information**
 - MacOS 12.3.1 (M1)

**Comment by DmitryArefiev** [comment]
Fixed in #12262
