### ISSUE TITLE
Steinberg Halion sonic crashing musescore

### ISSUE THREAD

**Issue by JosephZayoun** [musescore/MuseScore#12259]

**Comment by cbjeukendrup** [comment]
Could you please provide some more details? 
Personally, I'm able to reproduce the crash by selecting HALion in MuseScore, then closing its plugin window, and trying to reopen it. Are there other situations where a crash occurs?

**Comment by JosephZayoun** [comment]
in the mixer I changed the sound font to vst3, by selecting Halion sonic. then in Halion Sonic I changed my vst3 sound to a violin section in Halion symphonic orchestra. shortly afterwards, it gives a synth sound by its self and crashes. when reentering to ms4 it asks me if I want to open previous session, I accept, and it crashes again

**Comment by DmitryArefiev** [comment]
@JosephZayoun Can you try again in latest master please? Does it still crashes?

Thanks!

**Comment by RomanPudashkin** [comment]
@JosephZayoun please reopen the issue if you can still reproduce the crash
