### ISSUE TITLE
[MU4 Issue] "Staff text properties" button doesn't work if you are in edit mode

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12250]
**Description of issue**

You can open "Staff properties" in the Properties sidebar after selecting Staff text, but the same button doesn't work in "Edit mode"

**To Reproduce**

1. Open a score
2. Create some staff text
3. Go into edit mode and highlight a few letters with the cursor, say.
4. In Properties (sidebar), press "More", then "Staff properties".

RESULT: Nothing happens.

**Expected behavior**

The staff properties window should open?

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2603809362, revision: github-musescore-musescore-c83d663

**Comment by cbjeukendrup** [comment]
This must be the same problem as #12218. I'll close this one, but added a mention of it to #12218.

**Comment by DmitryArefiev** [comment]
Looks fine after #12368
