### ISSUE TITLE
[MU4 Issue] unable to select anything except measure

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#12257]
**Describe the bug**
It is not possible to selectanythibgexcept measure.

**To Reproduce**
1. Click on Title - Nothing Selected
2. Click on note - Measure selected

**Expected behavior**
What is clicked, is selected.

**Screenshots**

https://user-images.githubusercontent.com/1646034/177110595-ccf16471-5a6e-4171-83c6-0d4133c091b4.mp4

**Platform information**
 - OS: [Linux]

**Additional context**
Regression.
Possibly related to #11410 too?

**Comment by Tantacrul** [comment]
@DmitryArefiev - can you check this?

@sammik - is this a recent build / nightly?

**Comment by DmitryArefiev** [comment]
@Tantacrul That works fine on my **LinuxMint 20.2** with the latest nightly build.

@sammik Can you please again using this build? https://github.com/musescore/MuseScore/actions/runs/2633864232

**Comment by sammik** [comment]
@Tantacrul @DmitryArefiev 
I needed to Reset Preferences.
Seems to be OK now.
Sorry.

**Comment by DmitryArefiev** [comment]
@sammik That's cool. Thanks!
