### ISSUE TITLE
[MU4 Issue] unable to create custom key signature

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#12254]
**Describe the bug**
Unable to create new custom key signature in Palette

**To Reproduce**
1. Palettes - Key Signatures
2. Click on 'More'
3. No option to create new Key Signature

**Expected behavior**
User should be abletocreate custom Key Signature

**Screenshots**
![No Custom KeySig](https://user-images.githubusercontent.com/1646034/177059871-a9a81453-2af9-4698-8466-4a0839f56694.png)

**Platform information**
 - OS: [checked on Linux]

**Additional context**
Master Pallette works.
Regression. It worked in MU4 some time ago.

**Comment by DmitryArefiev** [comment]
Fixed in #12268
