### ISSUE TITLE
[MU4 Issue] Tempos mark in imported MS3 score is offset to the left (also occurs with a new score)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12252]
**Describe the bug**

This seems to be a relatively new issue. The position of tempo marks (and perhaps other text?), for some reason is being offset to the left.

**To Reproduce**

1. Open the attached score in both MS3 and the MS4 nightly. 
[tempo_shift.zip](https://github.com/musescore/MuseScore/files/9034859/tempo_shift.zip)

2. Observe the relative position of the tempo mark at the beginning of the score (which is the default for MS3)

RESULT: The tempo mark in MS4 has been offset to the left.

|MS3|MS4|
|-|-|
|<img width="215" alt="Schermafbeelding 2022-07-03 om 15 58 34" src="https://user-images.githubusercontent.com/48658420/177043133-209a8dfd-f544-49e5-ac7a-4a8a98e5e830.png">|<img width="215" alt="Schermafbeelding 2022-07-03 om 15 59 06" src="https://user-images.githubusercontent.com/48658420/177043149-515f77fb-337b-4a51-93dd-ffa791af23ab.png">|

--------------------------------------------
(from Dmitry Arefiev) Or just add a Tempo mark to the first measure in score

https://user-images.githubusercontent.com/90187801/177584715-7fe49bb6-b11c-4b52-8a53-cb56259ccaad.mp4

**Expected behavior**

Text positions should be the same as MS3.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2603809362, revision: github-musescore-musescore-c83d663

**Comment by Tantacrul** [comment]
It's a super annoying issue, actually.

**Comment by Tantacrul** [comment]
@oktophonie, @mike-spa, @asattely - assigning to you for the moment. Lemme know if you want it reassigned.
