### ISSUE TITLE
dynamics not playing back

### ISSUE THREAD

**Issue by JosephZayoun** [musescore/MuseScore#12260]
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by cbjeukendrup** [comment]
It looks like this problem is already covered by #10915, which is being working on at the moment. Also, please provide a little bit more detail in your issues! But thanks for reporting anyway!
