### ISSUE TITLE
[MU4 Issue] All elements in Palettes > More section are missing

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12263]
![Capture](https://user-images.githubusercontent.com/90187801/177172297-113192d8-ad60-415d-8bd7-440b3511288d.PNG)

https://user-images.githubusercontent.com/90187801/177172315-88ae152f-c160-4d1e-af70-7105e6c43006.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Was broken recently

**Comment by DmitryArefiev** [comment]
@Tantacrul  Adding to Alpha2 since it was broken recently (please change if needed)

**Comment by bkunda** [comment]
Yes I can verify that the PR I just re-tested from @HemantAntony (https://github.com/musescore/MuseScore/pull/12103) didn't have this problem.

**Comment by cbjeukendrup** [comment]
I may have found the cause, and it's pretty stupid and my fault...

**Comment by DmitryArefiev** [comment]
Fixed in #12268
