### ISSUE TITLE
[MU4 Issue] Odd behavior when dragging note downwards

### ISSUE THREAD

**Issue by JC-ProgJava** [musescore/MuseScore#12278]
**Describe the bug**
Dragging a note downwards results in odd behavior, causing note to eventually jump upwards.

**To Reproduce**
1. Enter a note
2. Keep dragging the note down.
3. See error

**Expected behavior**
It would be ideal if the note 'locked' in place when it reaches the lowest pitch. This behavior isn't exhibited when dragging the note upwards.

**Screenshots**

https://user-images.githubusercontent.com/61588096/177323164-0df9da71-808d-47ed-a3df-b499c18ce7b6.mov

**Platform information**
 - OS: macOS
 - Version: 4.0.0.2607659352

**Comment by Tantacrul** [comment]
How weird. Confirmed on MacOS. Nice catch!
