### ISSUE TITLE
[MU4 Issue] Changes made under 'Publish' cannot be undone unless switching back to 'Score' tab 

### ISSUE THREAD

**Issue by JC-ProgJava** [musescore/MuseScore#12277]
**Describe the bug**
Changes made under 'Publish' cannot be undone unless switching back to 'Score' tab.

**To Reproduce**
1. Go to 'Publish' tab and make changes.
2. Attempt to undo changes using Cmd + Z
3. See error

**Expected behavior**
Cmd + Z should undo changes made in the 'Publish' tab. The only way currently to undo changes are to switch back to the 'Score' tab and press Cmd + Z.

**Screenshots**

https://user-images.githubusercontent.com/61588096/177322118-6942fd20-9785-4272-94dd-1342ed223453.mov

**Platform information**
 - OS: macOS
 - Version: 4.0.0.2607659352

**Comment by JC-ProgJava** [comment]
Out of curiosity, is it by design that switching between the tabs resets the page such that it aligns with the upper left corner? Would it be more practical or ideal for the viewport to be kept the same (e.g., having dozens of pages and switching between the tabs results in the view locking on the first page)?

**Comment by DmitryArefiev** [comment]
The current bug and related issues #15277 #13397 should be fixed by blocking any change in score (note input, drag obejcts) when switching to Publish tab

**Comment by abariska** [comment]
**Not Actual** 
See comment above
