### ISSUE TITLE
[MU4 Issue] Staff instrument reset to default for imported MS3 scores

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12314]
**Describe the bug**

In the attached vocal staff (and perhaps other cases?) MS4 appears to be resetting the staff instrument sound to default for imported MS3 scores.

**To Reproduce**

1. Open the attached score. 
[scarborough_fair.zip](https://github.com/musescore/MuseScore/files/9071383/scarborough_fair.zip)

2. Compare playback of the vocal section in MS3 with MS4.
RESULT: The Vocal instrument sound has been reset to "Choir Aahs" in MS4 (was "Bassoon" in MS3).

**Expected behavior**

Scores in imported MS3 files should retain the same staff instrument sounds as set in MS3.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2633864232, revision: github-musescore-musescore-1f88df6

**Comment by Tantacrul** [comment]
Thanks for this example!

**Comment by HemantAntony** [comment]
@rgreen5 Can you check again. This seems to work fine in the latest nightly

**Comment by Tantacrul** [comment]
After some discussion, this is another aspect of the entire sound mapping system from V3 that we are making a clean break with.

One of our most important upcoming features in V4 is a new **universal** mappIng system that works with both VST, soundfont and Muse Sounds. It will not be compatible with the V3 way of doing things. With that it mind, I am bumping this to 4.x
