### ISSUE TITLE
[MU4 Issue] Playback varies depending on whether a note or a measure initially selected

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12315]
**Describe the bug*

If playback is started on a selected note then all staves are played back. But if playback is started from a selected measure, only the staff selected is played back.

**To Reproduce**

1. Open the attached score and click on a note in the "Verse" section. 
[scarborough_fair.zip](https://github.com/musescore/MuseScore/files/9071448/scarborough_fair.zip)
2. Play back and verify that all staves are sounding.
3. Stop, and this time select a measure rather than a note. Play back again
RESULT: Only the staff selected plays back.

**Expected behavior**

All staves should play back no mater whether a note/rest _or_ a measure is initially selected.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2633864232, revision: github-musescore-musescore-1f88df6

**Comment by Tantacrul** [comment]
This is very much by design 😄 

See this video: https://www.youtube.com/watch?v=qM1CcIRzJHE&ab_channel=Musescore
