### ISSUE TITLE
[MU4 Issue] Changing "Audio device" in preferences results in white noise / crash / loss of playback (Linux only)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12313]
**Describe the bug**

Changing the "Audio device" in preferences causes crashes / loss of playback.

**To Reproduce**

The following steps are applicable to my system:
1. Go to Preferences > I/O.
2. Change Audio Device from "Default" to 
![audio_device](https://user-images.githubusercontent.com/87246583/177971024-8eeccaf1-8909-465c-ac9c-01abc767f477.png)
RESULT: Immediate continuous white noise (even without playback)
3. Go back and change the Audio device back to default; press OK, then try playback. Repeat if possible.
RESULT: In one case, attemting to change from the audio device pictured above to default, caused the program to freeze and crash. In another changing back to default resulted in loss of playback. The feature seems very buggy.

**Expected behavior**

At worst no playback sound?

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2633864232, revision: github-musescore-musescore-1f88df6

**Comment by Tantacrul** [comment]
@DmitryArefiev - can you have a look at this to confirm on Linux when you have time? I've only tested on MacOS so far and not experienced this problem.

**Comment by DmitryArefiev** [comment]
@Tantacrul - yes, the same on my **LinuxMint20.2**. That came when we added ability to choose available audio devices in #12115, but I just I forgot to create an issue to filter non-working devices on Linux. I guess **we should just remove everything except Default** for now.

FYI @Eism

**Comment by boryskuzmenko** [comment]
Have the same issue on Ubuntu12.
But also noticed that I can't run a MuseScore app after that and need to turn my PCs power off and on to be able run MU again (even reset function doesn't help)
Tested with Motu Ultralite AVB and portable usb headphones logitech
