### ISSUE TITLE
Number values for frames allow too many digits after the decimal point

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#12316]
**Describe the bug**
Text frames can sometimes have values that are so long, they exceed the width of the text box. We need to limit these to two points after the decimal.

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/21022311/177985565-d8253de9-ffa5-4bfc-94d1-8310a0445a7d.png">

Here's another example of the default for a Symphony Orchestra template
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/21022311/177985840-9fe77a44-7064-43b1-86a5-a65275920881.png">

**To Reproduce**
1. Open the Symphony Orchestra template
2. Click on the title frame
3. Observe the 'Gap above' and 'Gap below' value

**Comment by HemantAntony** [comment]
On it!

**Comment by HemantAntony** [comment]
@Tantacrul The PR is #12318

**Comment by rgreen5** [comment]
Looks similar to  #12071?

**Comment by Tantacrul** [comment]
> Looks similar to #12071?

I thought that issue was about general consistency. Didn't realise you were referring to this specific (and ludicrous) problem. Anyway, we should close both in that case, once this is done.
