### ISSUE TITLE
[MU4 Issue] "Don't show again" checkbox sometimes doesn't work in "How would you like to save?" dialog (Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12317]
**To Reproduce**
1. Reset preferences
2. Restart MU
3. Create a score from template and make some changes
4. Close score and click Save
5. In How would you like to save dialog, check **Don't show again** option
6. Save score to disk
7. Restart MU
8. Create a score from template and make some changes
9. Close score and click Save
10. In How would you like to save dialog, **Don't show again** option is **still checked**

https://user-images.githubusercontent.com/90187801/177991582-d6747647-0118-4468-8cdf-87ae42aa8080.mp4

**Expected behavior**

**Screenshots**

**Platform information**
Windows10

**Additional context**
Can't reproduce on Mac

**Comment by Tantacrul** [comment]
Assigning to @cbjeukendrup

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev can't reproduce

Yes, the same on my side now. Thanks!

**Comment by DmitryArefiev** [comment]
Tested in **latest master** on Win10, LinuxMint 20.2 - **Can't reproduce. FIXED**  

Closing
