### ISSUE TITLE
[MU4 Issue] Unable to open Parts window if line (hairpin, slur, trill line etc.) or frame or bracket are selected 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12326]
**To Reproduce**
1. Select slur
2. Click on Parts button - **nothing happens**

https://user-images.githubusercontent.com/90187801/178028506-e30f3e74-6ddc-4475-a1b2-357a84d31d60.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Also occurs when frames, brackets are selected

**Comment by cbjeukendrup** [comment]
I think this is just another instance of #12218.

**Comment by DmitryArefiev** [comment]
Fixed in #12368
