### ISSUE TITLE
[MU4 Issue] String instrument gets stuck on playback (MIDI note input)

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#12324]
**Describe the bug**
When using MIDI keyboard as note input, some MIDI notes gets stuck on playback. This is Musescore_General. This may be difficult to re-produce
This seems to happen only on Windows.

https://user-images.githubusercontent.com/71656189/178012408-a247f759-6f0e-49aa-9f96-c144fa09b979.mp4

**Comment by DmitryArefiev** [comment]
Tested in **latest master** on Win10, Mac12, LinuxMint 20.2 - **FIXED**
