### ISSUE TITLE
[MU4 Issue] No audio backend causes SIGSEGV (crash) on Linux.

### ISSUE THREAD

**Issue by lyrra** [musescore/MuseScore#12328]
If no audio backend, click anywhere on the staff, causes SIGSEGV (crash) on Linux.

Create a new score, click on the staff.

Stacktrace:

Thread 1 "mscore" received signal SIGSEGV, Segmentation fault.
mu::playback::PlaybackController::seek (this=0x555558adddd0, tick=0) at src/playback/internal/playbackcontroller.cpp:157
157	    playback()->player()->seek(m_currentSequenceId, tickToMsecs(tick));
(gdb) ba
#0  mu::playback::PlaybackController::seek (this=0x555558adddd0, tick=0) at src/playback/internal/playbackcontroller.cpp:157
#1  0x00005555565d77e7 in mu::playback::PlaybackController::seekElement (this=0x555558adddd0, element=0x555560050160) at src/playback/internal/playbackcontroller.cpp:237
#2  0x000055555634d35f in mu::notation::NotationViewInputController::mousePressEvent (this=0x55555e6b6ac0, event=0x7fffffffd6e0)
    at src/notation/view/notationviewinputcontroller.cpp:524
#3  0x0000555556346671 in mu::notation::NotationPaintView::mousePressEvent (this=0x55555e6b6480, event=0x7fffffffd6e0) at src/notation/view/notationpaintview.cpp:906
#4  0x00007ffff7ac2388 in QQuickItem::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#5  0x0000555556346cdf in mu::notation::NotationPaintView::event (this=0x55555e6b6480, event=0x7fffffffd6e0) at src/notation/view/notationpaintview.cpp:986
#6  0x00007ffff68d115f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff5e0efca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff7adcc56 in QQuickWindowPrivate::deliverMatchingPointsToItem(QQuickItem*, QQuickPointerEvent*, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#9  0x00007ffff7addce7 in QQuickWindowPrivate::deliverPressOrReleaseEvent(QQuickPointerEvent*, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#10 0x00007ffff7ade5ed in QQuickWindowPrivate::deliverMouseEvent(QQuickPointerMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#11 0x00007ffff7adf64b in QQuickWindowPrivate::deliverPointerEvent(QQuickPointerEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#12 0x00007ffff61f57e5 in QWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#13 0x00007ffff68d115f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff5e0efca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff61e9583 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#16 0x00007ffff61bf64c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#17 0x00007ffff27017da in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#18 0x00007ffff4af1e6b in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff4af2118 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff4af21cf in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff5e6651f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff5e0d98b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff5e15c00 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x0000555555eca3d8 in mu::appshell::AppShell::run (this=0x7fffffffe0e0, argc=1, argv=0x7fffffffe518) at src/appshell/appshell.cpp:237
#25 0x0000555555740b21 in main (argc=1, argv=0x7fffffffe518) at src/main/main.cpp:321

Alternative stacktrace:
Thread 1 "mscore" received signal SIGSEGV, Segmentation fault.
0x00005555565d840c in mu::playback::PlaybackController::onSelectionChanged (this=0x555558adddd0) at src/playback/internal/playbackcontroller.cpp:336
336	    playback()->player()->resetLoop(m_currentSequenceId);
(gdb) ba
#0  0x00005555565d840c in mu::playback::PlaybackController::onSelectionChanged (this=0x555558adddd0) at src/playback/internal/playbackcontroller.cpp:336
#1  0x00005555565d7eaf in operator() (__closure=0x55555db95048) at src/playback/internal/playbackcontroller.cpp:315
#2  0x00005555565fac69 in std::__invoke_impl<void, mu::playback::PlaybackController::onNotationChanged()::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...)
    at /usr/include/c++/10/bits/invoke.h:60
#3  0x00005555565fa0b4 in std::__invoke<mu::playback::PlaybackController::onNotationChanged()::<lambda()>&>(struct {...} &) (__fn=...) at /usr/include/c++/10/bits/invoke.h:95
#4  0x00005555565f7b24 in std::__apply_impl<mu::playback::PlaybackController::onNotationChanged()::<lambda()>&, std::tuple<> >(struct {...} &, std::tuple<> &&, std::index_sequence) (
    __f=..., __t=...) at /usr/include/c++/10/tuple:1723
#5  0x00005555565f7b5e in std::apply<mu::playback::PlaybackController::onNotationChanged()::<lambda()>&, std::tuple<> >(struct {...} &, std::tuple<> &&) (__f=..., __t=...)
    at /usr/include/c++/10/tuple:1734
#6  0x00005555565f7b9e in deto::async::Channel<>::ReceiveCall<mu::playback::PlaybackController::onNotationChanged()::<lambda()> >::received(const deto::async::NotifyData &) (
    this=0x55555db95040, d=...) at src/framework/global/thirdparty/deto_async/async/channel.h:80
#7  0x0000555555850655 in deto::async::Channel<>::ChannelInvoker::doInvoke(int, void*, deto::async::NotifyData const&) (this=0x55555daf05d0, callKey=1, call=0x55555db95040, d=...)
    at src/framework/global/thirdparty/deto_async/async/channel.h:126
#8  0x000055555577c214 in deto::async::AbstractInvoker::invokeCallback (this=0x55555daf05d0, type=1, c=..., data=...)
    at src/framework/global/thirdparty/deto_async/async/internal/abstractinvoker.cpp:61
#9  0x000055555577c011 in deto::async::AbstractInvoker::invoke (this=0x55555daf05d0, type=1, data=...)
    at src/framework/global/thirdparty/deto_async/async/internal/abstractinvoker.cpp:44
#10 0x00005555558296e6 in deto::async::Channel<>::send() (this=0x55555daefee8) at src/framework/global/thirdparty/deto_async/async/channel.h:32
#11 0x00005555558257b8 in deto::async::Notification::notify (this=0x55555daefee8) at src/framework/global/thirdparty/deto_async/async/notification.h:14
#12 0x000055555639a053 in mu::notation::NotationInteraction::notifyAboutSelectionChangedIfNeed (this=0x55555daefe20) at src/notation/internal/notationinteraction.cpp:255
#13 0x000055555639cff8 in mu::notation::NotationInteraction::select (this=0x55555daefe20, elements=std::vector of length 1, capacity 1 = {...}, type=mu::engraving::SelectType::SINGLE, 
    staffIndex=0) at src/notation/internal/notationinteraction.cpp:682
#14 0x000055555634d11d in mu::notation::NotationViewInputController::mousePressEvent (this=0x55555ec6cd00, event=0x7fffffffd6e0)
    at src/notation/view/notationviewinputcontroller.cpp:517
#15 0x0000555556346671 in mu::notation::NotationPaintView::mousePressEvent (this=0x55555ec6c6c0, event=0x7fffffffd6e0) at src/notation/view/notationpaintview.cpp:906
#16 0x00007ffff7ac2388 in QQuickItem::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5

**Comment by lyrra** [comment]
Possible to insert notes, when in note-insertion mode.

**Comment by lyrra** [comment]
resolved in PR: https://github.com/musescore/MuseScore/pull/8956

**Comment by cbjeukendrup** [comment]
@lyrra This comment here: https://github.com/musescore/MuseScore/issues/10433#issuecomment-1263330016 suggests that this issue might have been resolved too. Could you re-check?

**Comment by lyrra** [comment]
Yes, no more crashes! Thanks!
