### ISSUE TITLE
[MU4 Issue] Values do not always update when moving between text styles in style dialog

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#12336]
**To Reproduce**
Open the Style dialog and choose 'Text Styles' on the left:
![image](https://user-images.githubusercontent.com/20604032/178233631-cd423bde-6259-4e5b-98a8-109e5532fcac.png)
'Title' is selected in the list by default; note that 'Size' is 22pt.

Now choose another style, e.g. 'Hairpin':
![image](https://user-images.githubusercontent.com/20604032/178233871-051a9ba7-253e-4a87-b9c5-8b89ca65f696.png)
The actual size of this style is 10pt, but not that  'Size' does not update (it remains at 22pt).

_Sometimes_ the size changes as you move around this list, but not consistently. I'm not sure if this affects only the 'Size' field, or others too.

It also seems to affect only certain styles for some reasons - Hairpin and Volta are two. But this does make it effectively impossible to change the values in these styles.

**Expected behavior**
All values should update correctly.

**Screenshots**

**Platform information**
 - OS: Arch Linux

**Comment by rgreen5** [comment]
Looks similar to #11262?

**Comment by oktophonie** [comment]
Note that this particularly seems to afflict the Hairpins style (possibly among others), to the extent that changing styles here has no effect. This means there's no way to change font for hairpin text (which also includes cresc./dim. text lines), short of creating a style sheet with them explicitly in and applying it.
