### ISSUE TITLE
[MU4 Issue] Copied durations in 3/4 display incorrectly when pasted in new measure

### ISSUE THREAD

**Issue by shhh26** [musescore/MuseScore#12330]
(Edited by Martin)
While trying to copy and paste a dotted half note into an empty measure while the song is in 3/4, the note is pasted as a whole note.

**To Reproduce**
Steps to reproduce the behaviour:
1. Song must be in 3/4
2. Copy a dotted half note already in the score from previous build
3. 3. Paste note into empty measure

https://user-images.githubusercontent.com/21022311/178241775-871bd9ed-5df8-4131-9a1c-dbd4e437ad86.mov

**Platform information**
 - OS: Windows 10, MacOS

**Comment by MarcSabatella** [comment]
I can reproduce - including in a new score created within MU4 - but only if I do two things that might not be clear from the description:

1) for the source, you have to select the note itself, not the full measure or any other range
2) for the destination, you have to similarly select the rest itself and not the empty measure or any other range

Normally copy/paste is done by range, not by individual note/rest.  If you do try to copy a single note and paste onto another note or rest, the "correct" behavior (the way it's been designed as the result of consensus among users) is to keep the duration of the destination but replace it with the pitch of the source.  Apparently, in this case, we are misinterpreting the duration of the full measure rest as being a whole rest, which of course are two different things.

**Comment by wizofaus** [comment]
I did some work on this a while back, and it was decided that copy/paste for individual notes should work the same as copy/paste for a chord (which can only be selected as a "range") - i.e. everything (pitch/duration/attached elements etc.) should be preserved. 
Pasting onto a whole-note rest does work in some cases, but not for dotted half-notes, not quite sure why, but happy to look at it.

**Comment by wizofaus** [comment]
A good test of this would be trying to paste a double-dotted half-note onto a whole measure rest in 7/8. But I can't figure how to create a double-dotted note at all!

**Comment by MarcSabatella** [comment]
Click the gear icon on the toolbar to customize it and add the double-dot button.

**Comment by wizofaus** [comment]
I literally would never have figured that out if you hadn't told me. I'd tried the gear button but the list of visible options didn't include double-dot, and it doesn't look scrollable.

**Comment by wizofaus** [comment]
Anyway it confirmed my suspicion - when you paste a note of a particular length that happens to match the underlying duration of a whole-measure rest, it incorrectly converts it to a whole-note duration.

**Comment by Tantacrul** [comment]
Yeah, this instance must have been missed when we made the decision to preserve the duration in **all** circumstances when copying and pasting. @wizofaus - I'll assign to you.

I've also updated the description with a video to help those new to the issue.

**Comment by wizofaus** [comment]
Your edited description is not quite right. It's inky even pasting on to a single selected whole measure rest whose underlying duration matches that of the note that was copied.

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12350
Tested on macOS 12, Win 11, Ubuntu 20
