### ISSUE TITLE
[MU4 Issue] Stem direction doesn't change in some double note cases

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12343]
**Describe the bug**
Stem direction (beam position) doesn't change in some double voice cases. 

![Capture](https://user-images.githubusercontent.com/90187801/178285073-77835a1e-5092-46c2-a342-2b0d0d0827d3.PNG)

https://user-images.githubusercontent.com/90187801/178285136-7e70f493-fedb-4330-8bf0-dde72d48894b.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by oktophonie** [comment]
Will be fixed by #12294 once merged:
![image](https://user-images.githubusercontent.com/20604032/178289059-5d3d6839-0941-4123-9bc3-60081cf5e6a7.png)
