### ISSUE TITLE
[MU4 Issue] Elapsed Time does not run at the correct rate

### ISSUE THREAD

**Issue by GabeS573** [musescore/MuseScore#12349]
**Describe the bug**
The Elapsed time shown in the top-right corner of MuseScore while a score is being played does not run at the correct speed. In other words, the MuseScore playback is slower than it should be. (See the video below)

**To Reproduce**
1. Open a score
2. Open a stopwatch app
3. Move the playhead in the score to the 3-second mark.
4. Start the stopwatch
5. Start the score after 3 seconds have passed on the stopwatch so that the score and stopwatch timers are synchronized.
6. After a few minutes, MuseScore falls behind by a few seconds.

**Expected behavior**
Scores should play at the correct rate, and 1 MuseScore second should equal one real-world second.

**Screenshots**

https://user-images.githubusercontent.com/91428485/178357158-d556147b-1392-4acb-9356-17c32ece9331.mov

**Platform information**
 - OS: Windows 11

**Comment by Tantacrul** [comment]
This is a known issue we are currently dealing with. I'll keep on Alpha 2 for now, unless @vpereverzev disagrees.
