### ISSUE TITLE
[MU4 Issue] Renaming Part doesn't work after Parts dialog were open

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#12366]
**Describe the bug**
Renaming Part doesn't work after Prarts dialog were open.

**To Reproduce**
1. Open and Close Parts dialog
2. Rename Part name (in Instruments panel, or in Staff/Parts propertiesdialog)
3. Open Parts dialog
4. Part name is not updated

**Expected behavior**
Part name in Part dialog (and in opened part tab) should be updated

**Screenshots**

https://user-images.githubusercontent.com/1646034/178602646-ea4f2d0e-f141-4de8-9506-41f2c8119f8c.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
This happens only if Part name is changed after Parts dialog were opened before.
If you change partname before first opening of Part dialog, everything is good.
Once Part dialog were open, part names became locked.

(Fixing this potentialy fixes also #10122, I guess)

**Comment by sammik** [comment]
May be same root of bug also in #10966?

**Comment by DmitryArefiev** [comment]
Fixed by removing Part name field (in Instruments panel and Staff/Part properties) in #14288
