### ISSUE TITLE
[MU4 Issue] Selected group becomes unselected when genre is changed in New Score Dialog and Instruments Dialog

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#12376]
**Describe the bug**
When you select an group and then you select a different genre in the New Score Dialog or the Instruments Dialog, the selected group becomes unselected

**To Reproduce**
1. Go to New Score Dialog
2. Click on a Group (eg: Keyboards)
3. Change the Genre to something else (eg: All instruments)
4. Keyboards become unselected

**Expected behavior**
The group should not be unselected when you change genres

**Screenshots**

https://user-images.githubusercontent.com/88136054/178723338-4386fab9-2b4f-476e-a56c-c900aefdcec8.mp4

**Platform information**
 - OS: Windows 11

**Comment by HemantAntony** [comment]
@Tantacrul can you check #12377 and see if my implementation is good? :)

**Comment by Tantacrul** [comment]
Looking good to me! Nice little fix 😄 
Thanks!

**Comment by Tantacrul** [comment]
@RomanPudashkin @cbjeukendrup - this would be a neat little improvement to merge when you've got time.
