### ISSUE TITLE
[MU4 Issue] App dialog position not restored correct after minimize on Windows

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#12372]
**Describe the bug**
When the app dialog is minimized, I expected it will restore the state it was before I minized the app. This works fine in MU3 but does not work in MU4. When the app is restored, it returns to the initial dialog size (not maximized).

**To Reproduce**
1. Start MU4
2. Click the Maximize option
3. Click the Minimize option
4. Click the app icon in the taskbar to restore the window

**Expected behavior**
The app should be restored to the previous state.

**Screenshots**
Showing the issue in MU4:
![MU4-Maximize-minimize](https://user-images.githubusercontent.com/13550012/178661388-a89479ff-1d5e-40b7-9370-69655d077b6d.gif)

Showing expected working using MU3:
![MU3-Maximize-minimize](https://user-images.githubusercontent.com/13550012/178661422-67e03371-ddc7-4904-8f58-ee042788d8d1.gif)

**Platform information**
 - OS: Windows 11

**Comment by Tantacrul** [comment]
Nice spot!
