### ISSUE TITLE
[MU4 Issue] Certain items become misplaced after switching languages

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12382]
**Describe the bug**
After you switch to another language in Preferences, not only the texts in the UI are refreshed, but also something less nice is happening: a lot of UI elements get misplaced.

**To Reproduce**
1. Open Preferences
2. Switch to another language
3. Observe that some text and icons become misplaced, for example:
    - The left sidebar in Preferences
    - The toolbars at the top of the window
    - some things in the Inspector

**Expected behavior**
That should obviously not happen.

**Screenshots**

https://user-images.githubusercontent.com/48658420/178751213-afde7cff-1331-4eba-816d-b599f07dd3f1.mov

**Platform information**
OS: at least macOS, and Windows (I also see it happening in the video in #12379)

**Additional context**
This may well be the fault of the stupid implementation of QQmlEngine::retranslate, which reevaluates ***every single property binding in the whole app***, rather than only those with translatable strings:
https://code.woboq.org/qt5/qtdeclarative/src/qml/qml/qqmlengine.cpp.html#1415

**Comment by Tantacrul** [comment]
I've noticed a very recent messing up of the icons in the top bar (player, mixer, etc.).

Assigning to Beta1 for now with a P1.

**Comment by cbjeukendrup** [comment]
Not actual anymore, since we decided to require a restart after changing or updating the language
(and the non-language-change-related issue with toolbar misalignment has been fixed as well)
