### ISSUE TITLE
[MU4 Issue] Key signature changes don't show for transposing instruments when not in concert pitch

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12387]
**Describe the bug**
See compare with previous build and latest master

https://user-images.githubusercontent.com/90187801/178800709-3ed459ac-6c61-492d-8560-682a2d608415.mp4

**Steps to reproduce**
1. Open Wind Quartet template
2. Turn on/off concert pitch mode - you should see key signature change in Clarinet instrument

This occurs only if you start from a scratch without adding a new key signatures to the score

**Platform information**
macOS, Windows, Linux

**Additional context**

**Comment by DmitryArefiev** [comment]
Another related weird thing

https://user-images.githubusercontent.com/90187801/178801873-280e509f-f1f6-453e-8e1e-f0dccfabe224.mp4

**Comment by Eism** [comment]
@cbjeukendrup 
I assigned you because #12240 is the cause of this problem

**Comment by DmitryArefiev** [comment]
Fixed in #12427
