### ISSUE TITLE
[MU4 Task] Score tab button panel UI update

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#12406]
![image](https://user-images.githubusercontent.com/71656189/179013516-ef6d02df-cc98-4887-abc6-a11f4d12299d.png)

Button panel at the bottom has 2 changes:
- Background is now BG Secondary colour.
- There is a gradient on top of panel (same behaviour as the titles when scrolling)
- The panel is now reduced to 100 pixels high

This can be found in HOME_TAB

Thanks!

**Comment by HemantAntony** [comment]
@jessjwilliamson I created a PR: #12420 :)
