### ISSUE TITLE
[MU4 Issue] Multi-measure rests showing hidden staves

### ISSUE THREAD

**Issue by vallieplushie** [musescore/MuseScore#12417]
**Describe the bug**
In systems with hidden staves, collapsing rests into multi-measure rests shows staves that would usually be hidden. This leads to a stave with only rests appearing for a single system

**To Reproduce**
1. Make a new score with one instrument
2. Add a stave to the instrument
3. Add some notation to the first stave, separated by a few bars
4. Turn on Style > Hide empty staves
5. Press M to make multi measure rest
6. The stave that was hidden should appear 

**Expected behavior**
The empty stave should stay hidden

**Screenshots**
<img width="813" alt="Screen Shot 2022-07-15 at 07 32 34" src="https://user-images.githubusercontent.com/108653255/179166265-d4122f9e-58e0-4ed4-8a1c-0ee135d68a94.png">

**Platform information**
 - OS: macOS 11.6, Arch.: x86_64, 
 - MuseScore version (64-bit): 4.0.0-2639806783, revision: github-musescore-musescore-6a9867d

**Additional context**
I don't know the way the MuseScore system works, but my guess is that the number text for multi measure rests is counted as notation which you have to show.

**Comment by mike-spa** [comment]
👀

**Comment by Jojo-Schmitz** [comment]
As per https://musescore.org/en/node/341431 this still happens in the released 4.0.0
