### ISSUE TITLE
[MU4 Issue] [VST] Crash when replacing Kontakt with Vital in Mixer (Mac)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12411]
**To Reproduce**
1. Open Treble Clef template
2. Select Kontakt player in Mixer
3. Replace Kontakt with Vital

https://user-images.githubusercontent.com/90187801/179031394-d4bf6765-7d26-4266-a670-d3c8973dc969.mov

If the crash hard to reproduce: add more instruments and repeat 2-3 steps on new instruments in Mixer (also you can combine with start/stop playback)

**Platform information**
macOS 12.3 (M1)

**Additional info**
Needs to check on Win

**Comment by vpereverzev** [comment]
Fixed in #12568
