### ISSUE TITLE
[MU4 Issue] TAB: Cannot place note on last fret using Ctrl-Up/Down

### ISSUE THREAD

**Issue by dragonwithafez** [musescore/MuseScore#12437]
**Describe the bug**
As described in https://musescore.org/en/node/333596, on guitar tablature, notes cannot be placed on the highest fret of a given string without first entering a lower note and using the arrow keys to move it up to the highest fret.

**To Reproduce**
Using the default 24 fret electric guitar as an example,
1. Create a treble 8vb electric guitar staff
2. Add a linked tablature staff
4. Add a note two octaves above the base pitch of a string (e.g. E4) to the treble staff
5. Attempt to move the note downwards using Ctrl+Down so it is on the 24th fret of a string
6. Note that the note will not go lower than the 19th fret of the string above
7. Change the tablature staff to have 25 frets
8. Repeat step 5, noting that the E4 will now move onto the 24th fret of the low E string

**Expected behavior**
The note should continue to be able to be moved onto the highest fret of the string for every string.

**Screenshots**
https://www.youtube.com/watch?v=j0GdnPhJyCw

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2674626696, revision: github-musescore-musescore-abc123456

**Additional context**
Present all the way back to 2.0's initial tablature implementation.

**Comment by cbjeukendrup** [comment]
It turns out that this has later been duplicated by #15729, which has been fixed by #15730.
