### ISSUE TITLE
[MU4 Issue] Menu shortcuts key combinations duplicated

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#12434]
**Describe the bug**
Undo/Redo in the Edit menu and Close in the File menu show the same shortcut key multiple times

**To Reproduce**
1. Open Edit menu
2. See error

1. Open File menu
2. See error

**Expected behavior**
Same shortcut key combination should not be repeated.

**Screenshots**
Edit Menu (showing with Dutch language loaded):
![image](https://user-images.githubusercontent.com/13550012/179308798-f308aa23-48ff-4791-ba12-dc2c4af985b6.png)

File Menu (showing with Dutch language loaded):
![image](https://user-images.githubusercontent.com/13550012/179308858-2f6d4007-207f-4f5b-9182-5a96d44617f5.png)

**Platform information**
 - OS: Windows 10

**Additional context**
Using Dutch/Netherlands language in Nightly generated 15-July 04:53.

**Comment by Eism** [comment]
@henkdegroot Yes, we had such a bug, but we fixed it and I can't reproduce on master. 
Please reset your settings(Preferences->Reset preferences). Should help you

**Comment by wizofaus** [comment]
I don't see the duplication but I still think showing ALL the shortcut key combinations in the menu looks very cluttered and non-standard:

![image](https://user-images.githubusercontent.com/5364225/179322057-bffd2c4c-1dee-4183-b98c-0b2cc07b7b32.png)

Compare, e.g. Visual Studio (where all those key combinations DO work, but only the primary ones are shown):

![image](https://user-images.githubusercontent.com/5364225/179322171-1cfc375f-c020-4810-a0e8-65e6868c73ad.png)

Similarly for most other apps I checked (note that Office apps don't even menus like this any more).  Notepad++ was the only other app I could find that showed multiple shortcut keys.

**Comment by henkdegroot** [comment]
@Eism, thanks. That seems to have worked. 
@wizofaus, I agree with it looks cluttered like this and MU3 did not do that as well. Think that should be a new/separate issue?

**Comment by Eism** [comment]
@henkdegroot we have already logged this issue. See https://github.com/musescore/MuseScore/issues/12236
Thanks!
