### ISSUE TITLE
[MU4 Issue] Channel change, from normal to arco, lost in imported MS3 score

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12441]
**Describe the bug**
MS4 seems to be ignoring a channel change instruction from normal to arco in an imported MS3 score.

**To Reproduce**
1. Open the attached score. 
[specimen.zip](https://github.com/musescore/MuseScore/files/9125640/specimen.zip)

2. Click play and listen out at measure 6 for a change from normal to arco in the bass part.
3. Compare this with playback in MS3.

RESULT: The bass part in MS4 does not obey the channel change order (arco) and continues as a plucked rather than a bowed bass.

**Expected behavior**

The channel change instruction should be obeyed, and you should clearly hear the change from plucked to bowed string.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2680600421, revision: github-musescore-musescore-315cfb3

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/13836
