### ISSUE TITLE
[MU4 Issue] weird Backspace action in Note input mode

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#12445]
**Describe the bug**
In Note input mode, backpsace reverts last change, but works only for single change (last one). Pressing it multiple times doesnt act anything. It creates extra record  into undo stack.

**To Reproduce**
1. Go to Note input mode ("n")
2. Write some notes
3. Press backspace several times
4. Only last one change is reverted
5. This revert is added to undo stack

**Expected behavior**
Backspace in note inputmode should behave as "undo". 3 x backspace should be 3 x undo. (As it is in MU3)

**Screenshots**

https://user-images.githubusercontent.com/1646034/179398487-efe71db6-687d-4ac9-a323-d5cc5086bd40.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
Regression from MU3.

**Comment by MarcSabatella** [comment]
See https://github.com/musescore/MuseScore/issues/9188

Basically, Backspace is no longer intended to simulate Undo  It's now the same as Delete, by design.  Although ideally, of course, eventually it should be a "real" backspace - Delete and move cursor to the left also.

**Comment by sammik** [comment]
Ah, I see, thanks.
I didn't find that issue. Probably because it is marked "closed".
