### ISSUE TITLE
[MU4 Issue] Crash when using playback toolbar in a score with no instruments

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12465]
**Describe the bug**
If you try to toggle the metronome in a score that contains no instruments, a crash occurs.

**To Reproduce**
1. Create a score
2. Delete all instruments using the instruments panel
3. Save and close the score
4. Reopen the score
Note that the metronome track is not created and doesn't appear in the Mixer.
5. Click a button in the playback toolbar
A crash occurs.

**Expected behavior**
Even though scores with no instruments don't make much sense at all, it would still be nice if they don't cause crashes.

**Platform information**
 - OS: reported on macOS

**Comment by hodori0719** [comment]
Additional issues with empty scores: crash on interaction with playback after saving. Empty scores crash upon using "transpose," "note input"/N, or "select all"/ctrl-A. Empty scores arbitrarily crash while using "find"/ctrl-F. Frames persist and work after removing last instrument but disappear and are unaddable upon saving and reloading. Inserting measures at any point on an instrument-less score causes a crash. After adding the first instrument back to a score, attempting to add measures to the beginning causes crash. Attempting to create parts causes crash.

**Comment by Tantacrul** [comment]
The ability for a score to have no instruments just makes UX easier. You can remove an instrument (or hide an instrument) you don't want and then add (or show) one that you do.

If you have a 'no empty score' rule, these things become really annoying. This is something that perpetually irritated me with MS3. The point isn't that the user would ever want a blank score. The point is that it makes other operations easier and will make future operations easier too.

For this reason, I do not like the idea of reintroducing the limitation of always having to have one instrument visible. I'd prefer us to apply some rules that when the score is empty, we simply disable certain parts of the UI, including the Note Input bar and the Play Panel.

**Comment by Tantacrul** [comment]
Just to confirm after a chat with @vpereverzev 

1. We have to allow the ability to have no instruments on a score for various important interaction reasons (mentioned above)
2. We should just use blocking mechanisms to sort out various crash issues (player should be disabled, if the user tries to save a score with no instruments, we should provide a popup to tell them they can't do it) 

@Eism

**Comment by Eism** [comment]
@Tantacrul 
What message should we show the user?

**Comment by Tantacrul** [comment]
@bkunda can you help with text?

**Comment by Tantacrul** [comment]
I'm unavailable for the next few hours

**Comment by bkunda** [comment]
@Eism @Tantacrul This is what I would propose: 

<img width="578" alt="Screenshot 2022-10-12 at 3 44 54 pm" src="https://user-images.githubusercontent.com/86290556/195359395-97262b4c-f80d-4c89-94fe-b81b8974eb7e.png">

**Comment by RobFog** [comment]
Please add a full stop at the end of the sentence. 😉

**Comment by cbjeukendrup** [comment]
@RobFog I also think that in a lot of places, but apparently it is different in English (?). In the Dutch translation, I'm definitely going to add a full stop, like we do in those other places :)

**Comment by RobFog** [comment]
> I personally find it cleaner to not have the period in cases just like this.

To my eyes, it looks wrong, in the non-bolded part more so than in the bolded (title?) part.

> Coming up with some sort of consistent copywriting style guidelines might be something we can turn our attention to once we are past the current release stage 🙂

That'd be great. 👍

**Comment by cbjeukendrup** [comment]
@bkunda Good to know where the idea of leaving out periods comes from :)

But in Dutch, it feels _really_ sloppy, and in a way "unsatisfying", if a sentence is not ended with a period. So do you allow us to add it in the translation when we feel we really need it? 😇

(Of course, if the text is _not_ a full sentence, then a period would be undesired. It's just about full sentences.)

**Comment by bkunda** [comment]
@cbjeukendrup you (and not I) are certainly the Dutch expert here, so if that's how it needs to be, then that's what should be done! 

To be clear, I'm neither strongly against nor for using periods in English in this case. I could be persuaded either way. I just recognise (as does @cbjeukendrup) that it is currently inconsistently applied in the app.

**Comment by Eism** [comment]
@Tantacrul 
Could you test the build from #13733?

**Comment by Tantacrul** [comment]
About the burning **full stop / no full stop** question: since we use it elsewhere, let's just use it here too.

If we find there are some other inconsistencies, we can fix them in a later build.

**Comment by Tantacrul** [comment]
> @Tantacrul Could you test the build from #13733?

Tested. Looking good.

**Comment by DmitryArefiev** [comment]
Fixed in #13733
