### ISSUE TITLE
[MU4 Improvement]  Ability to add glissando between two selected notes in two chords

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12468]
Would be great to have an ability to add glissando between selected notes, especially if we talk about chords or intervals

https://user-images.githubusercontent.com/101250347/179742053-8a7ee314-5700-42a8-a7a6-cdbcc761fa74.mov

**Comment by Tantacrul** [comment]
Although I agree, this feels like a **4.x** thing because it also has playback implications.
