### ISSUE TITLE
Tied notes are 'untied' when an articulation is added

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#12464]
**Describe the bug**
When an articulation is added to the first note in a tied duration, it causes the second note to be played.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/21022311/179709598-600c39dc-ab88-45de-a319-8de35c47c67e.png">

**To Reproduce**
1. Open this score: https://www.dropbox.com/s/o59mawsm0r398x5/12_Tied_Notes_with_Articulation.mscz?dl=0
2. Press play and note how every time an articulation is added, the tied duration repeats the second note

**Expected behavior**
Articulations applied to the first note of a tied duration should not cause the tie to be disrupted

EXCEPTION: if either staccato, tenuto or staccato+tenuto is applied to the **last note** of a tied duration, it should shorten it's duration. For example: in this image below, the tied notes should remain tied but the overall note event should end earlier.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/21022311/179710431-11dc9912-cfd9-4faf-a310-69b34094ec1f.png">

**Comment by rgreen5** [comment]
Also reported on the MuseScore Issues forum: [Glissando on final tied note causes it to repeat, rather than sustain](https://musescore.org/en/node/318773).

**Comment by vpereverzev** [comment]
Fixed in #12567
