### ISSUE TITLE
[MU4 Issue] [Inspector] 'Play' option doesn't work in Parts (Play option should work independently between score and parts)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12478]
**To Reproduce**
1. Open a part
2. Select some notes 
3. In Properties, uncheck Play setting - **you still hear the sound during playback**

https://user-images.githubusercontent.com/90187801/179806861-c77b139b-883a-4b2d-a28e-4ff1a8ef6dbb.mp4

**Expected behavior**
Play option should work independently between score and parts (I think)

**Platform information**
macOS, Windows, Linux

**Comment by RomanPudashkin** [comment]
@Tantacrul FYI

@DmitryArefiev and I decided to hide this option for parts because there is no easy way to fix it for them. Currently, we render ONLY the main score, so changing this option in a part score can't affect the rendering. This option was also non-functional in MU3 in the same scenario

**Comment by Tantacrul** [comment]
I agree with that decision @RomanPudashkin

**Comment by DmitryArefiev** [comment]
Fixed in #12926 (by removing Play option for Parts)
