### ISSUE TITLE
[MU4 Issue] Playback with Space doesn't start after deleting instrument and bringing it back with Undo

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12476]
**To Reproduce**
1. Open a score with two or more instruments (or just open  [string quartet NEW.zip](https://github.com/musescore/MuseScore/files/9142924/string.quartet.NEW.zip) )
2. Delete one instrument
3. Undo (Ctr/Cmd+Z)
4. Start playback with space - **nothing happens**

https://user-images.githubusercontent.com/90187801/179800529-d4d83132-3e60-48d7-aa6b-4d2b34767021.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Recent changes

**Comment by Tantacrul** [comment]
Can't reproduce on Windows. Perhaps it is fixed?

Anyway, I'm bumping this to post-beta

**Comment by DmitryArefiev** [comment]
> Can't reproduce on Windows. Perhaps it is fixed?
> 
> Anyway, I'm bumping this to post-beta

Yes, the same on my side. No longer occurs
