### ISSUE TITLE
[MU4 Issue] Unable to choose an audio input device

### ISSUE THREAD

**Issue by BoBogus** [musescore/MuseScore#12484]
**Describe the bug**
If I go into the Preferences menu, there is no option to select any audio APIs (though I am able to choose audio output devices as well as MIDI input and output devices

**To Reproduce**
1. Go to Edit > Preferences.
2. In the Preferences window, go to the I/O tab.
3. See that the API option is missing

**Expected behavior**
I expected to see an option to pick an audio API (like Windows Direct Sound, MME, and WASAPI).

**Screenshots**
![Audio Preferences](https://user-images.githubusercontent.com/96084585/179937610-d5b368d2-c3d8-4699-8dcf-10a72043ae8f.jpg)

This shows the options I am seeing in the I/O tab.

**Platform information**
 - OS: Windows 10 Pro, 64-bit

**Additional context**

**Comment by cbjeukendrup** [comment]
But MuseScore doesn't use audio input at all, it has no features that would use the microphone. So why would you want to select an input device?

**Comment by hodori0719** [comment]
I believe OP does not mean an input device, but rather an audio API (Windows Direct Sound, MME, and WASAPI). Musescore 3 supports this feature.

**Comment by hodori0719** [comment]
https://github.com/musescore/MuseScore/issues/11748

**Comment by Eism** [comment]
@BoBogus We currently only support one API per platform. For Windows it is WASAPI. There are no plans to add new APIs yet.

@Tantacrul FYI
