### ISSUE TITLE
[MU4 Issue] Inspector and other things don't update when a style value is changed by undo/redo

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12481]
**Describe the bug**
If a style value is changed not directly, but via an undo or redo action, the `styleChanged` notification is not emitted. Thus, certain objects in the UI that rely on this notification won't update properly in this situation. For example, the flag type selector in the "Stem" Inspector.

**To Reproduce**
1. select a note, and go to the "stem" inspector
2. open the Style dialog, go to the "Notes" and change the flag type
3. notice that the Inspector correctly updates now, because a style setting was changed directly
4. Press OK
5. Now, use the "undo" button or press Ctrl/Cmd+Z. The score updates properly (because that happens inside the engraving module), but the Inspector not (because that should have happened via the `styleChanged` notification from the notation module, but that notification is not emitted this time)

Or another way: **THIS IS LOGGED SEPARATELY** #13437
1. have a score with transposing instruments (not necessary, but useful for checking behaviour)
2. enable concert pitch using the checkbox in the Status bar
3. press undo
Expected: concert pitch is disabled again, and the concert pitch checkbox reflects this
Actual: although the score is updated correctly (because that happens inside the engraving module) but the checkbox not (because that should have happened via the `styleChanged` notification from the notation module, but that notification is not emitted this time)
If you click the checkbox again after this, unexpected things may happen.

In both cases:
Afterwards, if you do anything else that causes the `styleChanged` notification, the state of the UI is (of course) updated/fixed again.

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/48658420/179816948-1df456df-d039-48b4-9b09-354e691bce3c.mov

**Platform information**
 - OS: reported on macOS

**Additional context**
We can use a stopgap solution by listening for `undoStack()->stackChanged()` or `notationChanged()` notifications instead (or additionally). Or by emitting the `styleChanged` notification whenever one of these notifications is emitted.

But that will cause _a lot_ of unnecessary notifications and updates. A real fix might be not so easy; it would require a smart solution for communication between the engraving module and the notation module. 

It is not certain that this kind of problem is limited to the `styleChanged` notification. Other things may have similar problems in combination with "undo", although I can't think of any right now.

**Comment by wizofaus** [comment]
I'd expect the inspector/properties panel to refresh every time a undo/redo event occurs, so listening to stackChanged seems reasonable, if it's a simple change in one place.

**Comment by wizofaus** [comment]
BTW a bigger issue to me is that if I select just a single note and change its flag type in the properties panel, all the other notes change too! There's no clue/indication in the UI that it should behave in that way.

**Comment by DmitryArefiev** [comment]
Fixed in #13083

**Comment by DmitryArefiev** [comment]
> Or another way:
> 1. have a score with transposing instruments (not necessary, but useful for checking behaviour)    
> 2. enable concert pitch using the checkbox in the Status bar
> 3. press undo
> 
> Expected: concert pitch is disabled again, and the concert pitch checkbox reflects this
> Actual: although the score is updated correctly (because that happens inside the engraving module) but the checkbox not (because that should have happened via the styleChanged notification from the notation module, but that notification is not emitted this time)
>     If you click the checkbox again after this, unexpected things may happen.

This was not fixed in #13083

Logged separately #13437
