### ISSUE TITLE
[MU4 Issue] [Accessibility] Using Alt in navigation (Alt+arrow) switches to File menu each time you release Alt key

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12488]
**To Reproduce**
1. Run Orca
2. Move to note with arrow
3. Then press Alt+down arrow to navigate to other staff - after you release Alt key (in shortcut) File menu is enabled

**Platform information**
Linux20.2

**Additional context**
Occurs only when **Orca is enabled**
**Linux** only

**Comment by wizofaus** [comment]
Pretty sure I already reported this, though it may have been part of another issue.  Definitely an issue though.
