### ISSUE TITLE
[MU4 Issue] Crash when starting playback

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#12496]
**Describe the bug**
When I start playback, the program crashes.

**To Reproduce**
1. Open or create a score 
2. Press the playback button
3. Crash 

**Expected behavior**
Playback starts without crash.

**Platform information**
 - Windows 11 with latest nightly

**Additional context**
The crash happens only when I use the computer's built-in speakers, wireless earphones, or wired earphones via 3.5mm phone connector.
When I connect wired earphones via USB-C, this does not happen.
This does not occur in the June 23 nightly build, but occurs in the June 24 nightly build..
Selecting a notehead or a measure also causes crash but entering note input mode by pressing N doesn’t cause crash.

**Comment by Eism** [comment]
@bakajikara Please check this build https://github.com/musescore/MuseScore/suites/7435223417/artifacts/303902403

**Comment by bakajikara** [comment]
@Eism I have tried it. In this build,
- When using the computer's built-in speakers, wireless earphones, or wired earphones via 3.5mm phone connector, no crashes occurred, but no sound could be heard.
- When using wired earphones via USB-C, **a crash occurred**, which does not happen on nightly builds.

**Comment by boryskuzmenko** [comment]
@bakajikara could you please clarify this? You described two opposite cases

![Capture 2022-07-27_02-07-17_PM](https://user-images.githubusercontent.com/101250347/181233394-d0f04abd-80c1-4d4e-8860-cb4c3bf8b532.png)

**Comment by bakajikara** [comment]
This may sound crazy, but it occurs exactly as I wrote.
- When I use wired earphones via USB-C, nightly build does not crash but Eism's build crashes.
- When I use other sound devices, Eism's build does not crash but nightly build crashes.

Sorry for the poor explanation.

**Comment by Eism** [comment]
@bakajikara 
I fixed the bugs in my PR and one bug from master
Could you recheck this build https://github.com/musescore/MuseScore/suites/7556251692/artifacts/312053224 ?

**Comment by bakajikara** [comment]
@Eism The program no longer crashes in both cases. Thank you. I will close the issue now.

**Comment by Eism** [comment]
The fix will be merged in #12580

**Comment by boryskuzmenko** [comment]
@bakajikara could you please try to reset preferences on previous master (which been crashing) and recheck this crash again?
