### ISSUE TITLE
[MU4 Issue] Download button in "Getting started" wizard doesn't work

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#12493]
**Describe the bug**
The second page of the Getting Started wizard ("Playback") has a "Download" button that doesn't do anything.

**To Reproduce**
1. Uninstall & reinstall latest v4 build
2. Launch app and click next on first page of Getting Started wizard
3. On the next page, click the Download button
4. Nothing happens...

**Expected behavior**
Something should happen?

**Screenshots**

**Platform information**
Windows 10, MuseScoreNightly-202207200438-master-0d2b4c7-x86_64

**Additional context**

**Comment by Yann-Kaelig** [comment]
Same issue on Linux with Nightly Build MuseScoreNightly-202207270441-master-37d172f-x86_64.AppImage

**Comment by Tantacrul** [comment]
This is by design. The library isn't downloadable yet. This _will_ work for Beta.
