### ISSUE TITLE
[MU4 Issue] Audio doesn't work

### ISSUE THREAD

**Issue by rebiolca** [musescore/MuseScore#12497]
**Describe the bug**
Audio doesn't work on latest nigthly AppImage

**To Reproduce**
1. Press play on any score: no audio

**Expected behavior**
Hear audio

**Screenshots**

**Platform information**
 - OS: Linux LMDE5 and Chromebook Asus C425T (Both Debian based)

**Additional context**
This nightly I tried was revision 0d2b4c7, audio worked with last one I had tried which was revision 6a9867d

**Comment by Eism** [comment]
@rebiolca 
Make sure you have MS Basic selected instead of MuseScore_General in the mixer under Sound.

**Comment by rebiolca** [comment]
@Eism
Ahhh, I was getting crazy in the settings I/O etc.. trying to find a solution there, but it was easier than I thought.

**Comment by Eism** [comment]
@rebiolca
Can we close the issue?
