### ISSUE TITLE
[MU4 Issue] Background of dragged palette icons is white rather than transparent (obscures the score when dragged)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12501]
**Describe the bug**

The backgrounds of arpeggios and glissandi should be _transparent_ so that the underlying score is always visible if the user chooses to drag the symbol from the palette (rather than click it in). At least, this was the case in MS3.

**To Reproduce**

* Drag a symbol from the arpeggios and glissandi palette, say, to a note.

RESULT: The white background appears when the symbol is above notes or fretmarks. This obscures the note or chord at that position and makes it unclear where the symbol is to be dropped.

**Expected behavior**

The Background to the dragged symbol always remains transparent and there is a clear indication to the user when the symbol is in a drop position.

**Screenshots**
![drag_icon](https://user-images.githubusercontent.com/87246583/180205223-eb1d448d-fcaf-4e4d-9f70-4e70cb593d17.png)

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2709288230, revision: github-musescore-musescore-bed6689

**Comment by Tantacrul** [comment]
Yes, this is something that has been wrong with the palettes panel for ages. My understanding is there's a really awkward problem with matching the way it works in MS3. However, it's likely something that just requires aa different solution (meaning a lot more work).

I'm putting this on Beta 1 for now because it is extremely annoying. However, it may get bumped to 4.x, if we get pressed with a lot more significant / blocking issues.

**Comment by HemantAntony** [comment]
@Tantacrul Are you sure this is the desired behaviour. If you were in Dark mode, dragging white accidentals on a transparent background doesn't make sense. You wouldn't be able to distinguish it
![image](https://user-images.githubusercontent.com/88136054/183584632-33fd49ec-9e2b-4217-924c-50e4bf865ad3.png)

Also, what if the score background color was black and you were using light theme. You wouldn't be able to distinguish it in that case too
![image](https://user-images.githubusercontent.com/88136054/183584855-2174a24b-7a5f-4d3d-a61a-f0ae35e3533b.png)

**Comment by Tantacrul** [comment]
@HemantAntony - good point. It can be fixed by altering the visualisation while you are dragging. A little bit of transparency would help though.

@jessjwilliamson - this might be a visual challenge to look at at some point soon.

**Comment by MarcSabatella** [comment]
Is this truly fixed?  I don't use drag & drop often, but I just tried it and the background is still opaque:
![image](https://user-images.githubusercontent.com/1799936/191626953-173cf28b-003c-4e84-a624-a1704ba3e1d9.png)

Do I need to factory reset?  I did reset the palette.
