### ISSUE TITLE
[MU4 Issue] Adjustment handles do not zoom

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12500]
**Describe the bug**

A bug carried over from MS3. When you zoom the score, all elements should get larger or smaller in equal measure. However adjustment handles on lines, slides etc remain at the same size

**To Reproduce**

1. Apply, say, a line from the Lines palette (one with adjustment handles).
2. With the line selected and adjustment handles visble, zoom the score.

RESULT: Adjustment handles stay the same size.

**Expected behavior**

Adjustment handles should should zoom in line with the rest of the object.

**Screenshots**
High zoom level, but adjustment handles are small in comparison.
![adjustment_handles](https://user-images.githubusercontent.com/87246583/180202645-d020568e-b478-4b71-a970-5dfbb37fb60c.png)

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2709288230, revision: github-musescore-musescore-bed6689

**Comment by MarcSabatella** [comment]
And eventually, the handles can disappear entirely within the zoomed in object.  See for instance https://musescore.org/en/node/309324  I recall we tried fiddling with this but weren't entirely happy with how it felt to have them scale, either, especially in the case of zooming *out*.  Probably there should be a minimum handle size or something else to prevent unusable handles at small zoom factors.  Also, of course, handles aren't unique to MuseScore; it would be good to compare with other applications.

**Comment by wizofaus** [comment]
Sorry, I wouldn't expect drag handles to zoom at all - they're a fixed size that's just to indicate where the mouse needs to point in order to manipulate the handle.  At best there could be a global option to adjust the size if it's too small for you, but I honestly don't see any advantage in them resizing (and lots of disadvantages - I zoom in explicitly to ensure the handles are clearly separated from each other).

**Comment by Tantacrul** [comment]
Yes, I agree with @wizofaus: UI controls should not zoom but I do think those handles are too small in general.

I'm closing this issue as a **won't fix**
