### ISSUE TITLE
[MU4 Issue] Deleting first measure in score removes Key Signatures in transposing instruments when score is not in concert pitch

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12506]
**To Reproduce**
1. Open Wind quintet template
2. Make sure the concert pitch is unchecked
3. Delete the first measure (Ctr/Cmd+Delete) - **key signatures in Clarinet and Horn should not be removed**

https://user-images.githubusercontent.com/90187801/180238020-223f5ac4-6a10-4369-83d9-8c1de21662eb.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Also occurs in **MU3**

from @sammik :
1) occurs only in C major
2) and only if Key signature in first measure wasnt changed before removing first measure
(if you change initial ks to G major and than to C major, bug not there)

**Comment by DmitryArefiev** [comment]
@Tantacrul I've added to Beta1 but this weird issue also occurs in MU3

**Comment by sammik** [comment]
1) occurs only in C major
2) and only if Key signature in first measure wasnt changed before removing first measure
(if you change initial ks to G major and than to C major, bug not there)

**Comment by DmitryArefiev** [comment]
> 1. occurs only in C major
> 2. and only if Key signature in first measure wasnt changed before removing first measure
>    (if you change initial ks to G major and than to C major, bug not there)

Yes, noticed that too. Will add to the description. Thanks for testing!

**Comment by zacjansheski** [comment]
This is fixed in the current nightly
