### ISSUE TITLE
[MU4 Issue] Character code appears in palette names instead of &

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12528]
**Describe the bug**

It appears that the equivalent character code is being displayed for an ampersand in certain palette names, such as Arpeggios & Glissandi,.

See also, #11978.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2722421418, revision: github-musescore-musescore-5e7884d

**Comment by HemantAntony** [comment]
This can no longer be reproduced. Hence, can be closed:
![image](https://user-images.githubusercontent.com/88136054/188398573-ad0b3140-9c9b-4d79-9f0f-61f5d0fd09e6.png)

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2990798632, revision: github-musescore-musescore-5d26e7f

The issue is still there in this nightly.
![palettes](https://user-images.githubusercontent.com/87246583/188400314-d0f9b6fe-0872-4676-86af-17fd3a4cf214.png)

**Comment by HemantAntony** [comment]
Can you do a factory reset and check? Or try reseting the palette?

**Comment by rgreen5** [comment]
A factory reset corrected it.
