### ISSUE TITLE
[MU4 Issue] Tablature TIES still placed too high

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12529]
**Describe the bug**

Problem was apparently fixed in  #10991. But it's still there in the attached MS3 score.

**To Reproduce**

1. Open the attached zipped score in both MS3 and MS4. 
[ties_too_high.zip](https://github.com/musescore/MuseScore/files/9173473/ties_too_high.zip)

2. Compare the tie placement in tablature measures 5-6, 11-12, 16-17.

RESULT: The top tie in all cases seems to be too high. But in other measures the placement seems OK. 

**Expected behavior**

Tie placement should be the same as in MS3.

**Screenshots**

MS3 ties:
![ms3_ties](https://user-images.githubusercontent.com/87246583/180599694-8040e10f-7dbf-45b8-9f44-32b315c13fc3.png)
MS4 ties:
![ms4_ties](https://user-images.githubusercontent.com/87246583/180599695-e938deca-fc73-4520-9ed9-ac9c283b2fb2.png)

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2722421418, revision: github-musescore-musescore-5e7884d

**Comment by oktophonie** [comment]
Assuming the top note is its own voice, this looks as expected. Currently single-note ties are drawn 'outside' (above/below) the notes and chord ties are drawn 'inside'. Compare these two:

![image](https://user-images.githubusercontent.com/20604032/180600402-71c53b7c-c6ae-45ba-949e-f8ecb59e8fc5.png)
