### ISSUE TITLE
[MU4 Issue] Note Off MIDI messages not sent when notes are entered quickly in Note Input Mode (Vital, Surge XT, Arturia synths etc.)

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#12523]
**Describe the bug**
When notes are entered too quickly in Note Input mode, Note Off messages are not sent, at least not to VST plugins.

**To Reproduce**
1. Create a new MuseScore project with at least one instrument.
2. Set it to a VST instrument (Vital, Surge XT or Arturia synth).
3. Go into Note Input mode and enter notes quickly.

**Expected behavior**
Note Off messages should be sent when the next note is entered (or after a certain amount of time).

**Screenshots**
See https://github.com/musescore/MuseScore/issues/12523#issuecomment-1283984757

**Platform information**
 - OS: Windows
 - Version: MuseScoreNightly-202207220438-master-059dda5-x86_64

**Additional context**
I don't need to add any other context about the problem here.

**Comment by DmitryArefiev** [comment]
Should be the same as #12324

**Comment by DmitryArefiev** [comment]
Should be fixed now (in master)

@ThePython10110 Please reopen if still persists

**Comment by ThePython10110** [comment]
AFAIK, I can't reopen the issue, but it still happens with the latest nightly build.

**Comment by DmitryArefiev** [comment]
> AFAIK, I can't reopen the issue, but it still happens with the latest nightly build.

@ThePython10110 I've reopened the issue. Can you attach a video demo please? You can use app from https://www.bandicam.com

Thanks!

**Comment by ThePython10110** [comment]
It seems to only be happening with certain VST plugins, including Vital and Surge XT. I guess I should have tested more thoroughly.

**Comment by DmitryArefiev** [comment]
> It seems to only be happening with certain VST plugins, including Vital and Surge XT. I guess I should have tested more thoroughly.
Ah, I see now and can reproduce it! It happens with synthesizers such as **Vital**, **Arturia**


https://user-images.githubusercontent.com/90187801/196699022-dcb9e641-2d6f-41cb-af7a-f9ab8996d138.mp4

**Comment by abariska** [comment]
Seems like the same https://github.com/musescore/MuseScore/issues/12669
