### ISSUE TITLE
[MU4 Issue] Flag style property behaves unexpectedly

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#12525]
**Describe the bug**
While the "Stem direction" property in the Property Panel/inspector applies as expected to just the selected notes, the very next property "Flag style" seems to apply to all notes regardless of what's selected, with no indication the two properties should behave differently.

**To Reproduce**
1. Create a score with two or more unbeamed 8th notes
2. Select one of them
3. In the Properties panel under the "Stem" sub-tab, change the stem direction and note that it applies to just the selected note.
4. Now change the flag style.
5. All notes change their flag style!
 
**Expected behavior**
Either you should be able to change the flag style for just the selected notes, or the UI should make it clear that Flag style is a global score style.  NB v3 does not have this issue as flag style is not shown on the inspector.

**Screenshots**

**Platform information**
Windows 10

**Additional context**
Built from source, running under VS 2019 using latest master as of Jul-23 2022.

**Comment by oktophonie** [comment]
Flag style is indeed a score-wide setting.

For that reason, I have asked several times for 'Flag style' to be taken out of the Properties panel and exist only in the Style dialog but this has so far fallen on deaf ears. I repeat this plea here.

@Tantacrul

**Comment by wizofaus** [comment]
I don't necessarily have a problem with it being there as long as it's clear it's a score wide setting.

**Comment by Tantacrul** [comment]
@oktophonie - the plea hasn't fallen on deaf ears. I just don't want to do it.

I don't want a useful setting buried away where no one will ever find it.

**Comment by wizofaus** [comment]
Sorry why is this closed? The issue still exists, and adding an indication to the property label to indicate it's a score wide setting is a very simple fix..

**Comment by abariska** [comment]
@oktophonie @Tantacrul Flag style option looks inconsistent in this Properties area. I agree that it shouldn't be removed from Properties but I believe it should be placed in General section at least. 
Moreover, in [Mesescore handbook](https://musescore.org/en/handbook/4/stems-and-flags#stem-flag-style) it descripted as an option for selected note and there're another parameter in Style for entire score (@bkunda FYI)

**Comment by Tantacrul** [comment]
Is this an issue though? All someone needs to do is press it one - see the result and then it is clear. I don't want to keep this issue open when we have so many others to be dealing with.
