### ISSUE TITLE
[MU4 Issue] Hairpin is invisible when added to particular scores

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#12527]
**Describe the bug**
For certain scores, adding hairpins results in an invisible hairpin (the handles can be seen and adjusted but no hairpin is shown).

**To Reproduce**
1. Open the attached score [34.zip](https://github.com/musescore/MuseScore/files/9173010/34.zip)
2. In the first measure add a hairpin with shift+, (<)
3. Hairpin is not visible (only the grip handles)

**Expected behavior**
Hairpin should be visible. Can be fixed by resetting the "style" in the properties panel, but newly added hairpins still have the same problem, until you do "Reset all styles to default" in the Styles dialog.
I never changed these style settings before saving this file so I have no idea what happened.

**Screenshots**

**Platform information**
Windows 10

**Additional context**
Built from latest master with VS 2019 as of Jul 23 2022.

**Comment by HemantAntony** [comment]
I cannot reproduce this with the attached score

**Comment by cbjeukendrup** [comment]
I can't reproduce this either, and it is very likely that this has been fixed. For an explanation, see https://discord.com/channels/818804595450445834/939880479887327302/1018305828840820817.
