### ISSUE TITLE
[MU4 Issue] Language dropdown in Preferences is cut off at the top

### ISSUE THREAD

**Issue by mxmou** [musescore/MuseScore#12536]
**Describe the bug**
If the Preferences window is near the top of the screen, a part of the language dropdown is not visible. I can reproduce this even when the window is at its default position (on 1920x1080 display, 125% scale).

**To Reproduce**
1. Go to Preferences, open the language dropdown and choose a language that isn't too close to the top of the list.
2. Move the Preferences window up, near the top of the screen.
3. Open the dropdown again and scroll to the top.

**Expected behavior**
All items would be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/51849865/180608026-ceabf7ff-2fac-4c23-8e98-679850e963a7.png)

**Platform information**
 - OS: Windows

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12538
Tested on macOS 12, Win 11, Ubuntu 20
