### ISSUE TITLE
[MU4 Issue] Selected external (additional) MIDI I/O can't be deselected 

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#12543]
**Describe the bug**
I suddenly figured out that we don't have an ability to deselect external MIDI devices after we selected them. 
I see two problems here:
1. The root problem is that we don't have an empty option in the dropdown, or at least default one which means using fluid. 
2. When we have select external MIDI output signal is still going via fluid. And it's a big problem on my Windows 11. There's a Microsoft onboard MIDI synth and when I select it I here audio from both fluid and MS MIDI and they are not sound good together. 
So, I believe fluid should be deselected in case when we choose another MIDI device for MuseScore playback and be present in the MIDI output as Default.
And the most sad part of this story is that you should reset all preferences to reset MIDI settings and be able playing your scores again 

**Expected behavior**
To be discussed

**Screenshots**

https://user-images.githubusercontent.com/101250347/180665054-f4856a39-07d3-4122-8936-1053adb70ea8.mov

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**
Could be linked with https://github.com/musescore/MuseScore/issues/12312

**Comment by Eism** [comment]
@bkunda 
Could you help us with the first point?

**Comment by bkunda** [comment]
> The root problem is that we don't have an empty option in the dropdown, or at least default one which means using fluid.

So if I understand this correctly, if the user doesn't select their own device from the dropdown in "Midi input" and "Midi output", then they are using the Fluid Synthesiser. Have I understood correctly? 

In that case, the solution would probably be to have a menu option labelled something like "Default (Fluid Synthesiser)" selected by default. The user can then go back to this if they want to disable their own device in MuseScore. 

@Eism @boryskuzmenko let me know if this sounds like a sensible option, and if you want me to quickly mock it up.

**Comment by Eism** [comment]
> Have I understood correctly?

Yes, all right

>"Default (Fluid Synthesiser)"

I'm not sure if Fluid Synthesiser in the title
Does the user know what a Fluid Synthesiser is?

**Comment by boryskuzmenko** [comment]
could be 'Default sound library'

**Comment by bkunda** [comment]
> could be 'Default sound library'

I worry this could get a bit confusing: it's not exactly the case (if I understand things correctly) that the user is going to be loading a sound _library_ when they select an option for MIDI input/output. And the types of user that will be making a selection here are either going to have some understanding of what MIDI is, or they are going to expect to see some sort of device represented (a physical thing that they've plugged into their computer), and could therefore be confused if they see any mention of a sound library. 

I'd probably be happy with "Default" just on its own tbh, or perhaps better still: "System default".

**Comment by cbjeukendrup** [comment]
Why not simply "No MIDI output" or "None" or something like that? Because that is what this option should do. It hasn't anything to do with the system and also not with MuseScore's synths (Fluid, VSTi).

**Comment by boryskuzmenko** [comment]
Let's put our brainstorming to pause for a while :) 
I'll research a bit more

**Comment by boryskuzmenko** [comment]
Hi there,
After investigation in Sibelius, Finale and other music software I see only one right decision. Midi input and output should be implemented as dropdown with detected midi devices with the first value in the list 'No device'. It means that user can disconnect all midi devices without affecting main processes in MU4. Midi out is pretty specific option, so I believe that any additional logic is redundant for now. Let's use this approach and see how it works for users.
@Eism please, use this as expected result.

**Comment by Tantacrul** [comment]
Nice work all!

**Comment by DmitryArefiev** [comment]
Fixed in #12877
