### ISSUE TITLE
[MU4 Issue] User-created parts show generic title/subtitle/composer etc.

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12544]
**Describe the bug**
If the user creates a custom part in the Parts dialog, this part contains text fields that only show generic title/subtitle/composer info, rather than the same info as the full score. 

**To Reproduce**
1. Create a score, and on the "additional info" page, enter a custom title, subtitle, and/or composer. 
1. Open the Parts dialog
2. Click "Create new part"
3. Open the newly created part

**Expected behavior**
Newly created parts should show the same info as the full score and the "default" parts.

**Comment by sammik** [comment]
And Lyricist is completly missing in custom parts.

**Comment by shoogle** [comment]
@oktophonie, maybe one for the engraving team?

Just to clarify for anybody (like me) who didn't read the description properly first time: it is necessary to click the "Create new part" button. If you click "Open all" then you won't see this issue.
