### ISSUE TITLE
[MU4 Issue] Add / Tuplets / Other is non-functional

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12548]
**Describe the bug**
The dialog box for Add / Tuplets / Other appears, but no matter what duration had been selected and no matter what choices you make in this dialog, no tuplet is actually created.

**To Reproduce**
1. New score, 4/4, treble staff
2. Measure 1, Note input mode
3. Select quarter note duration
4. Add / Tuplets / Other
5. Hit OK
6. 

**Expected behavior**
A tuplet is created

**Actual behavior**
No tuplet is created; the dialog closes having done nothing

**Platform information**
 - OS: Linux

**Additional context**
Same result if you try doing this from Normal mode.  Also, sometimes the dialog just doesn't appear.

**Comment by boryskuzmenko** [comment]
Also reproducible on macOS

**Comment by wizofaus** [comment]
Looking at this, the code does look like it's there, just isn't working properly for some reason. Can't reproduce the dialog sometimes not appearing.

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/12588 
Tested on macOS 12, Win 11, Ubuntu 20
