### ISSUE TITLE
[MU4 Task] Determine to which extent the "staff text properties" dialog is still actual

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12586]
**Task description**
We should check whether the settings in the Staff Text Properties dialog are still functional and relevant. For example, the pages about "Change Channel" and "MIDI Action" seem obsolete to me, since we aren't making use of "channels" anymore. We should discuss to what extent we are ready to drop parts of this dialog.

**Comment by MarcSabatella** [comment]
Neither swing nor capo are actually working as far as I know, but this is pretty important functionality - especially swing, which has been a core part of MuseScore for as long as I’be been on the project, which is saying something.

No doubt it’s possible to find a better way to expose this, but until then, it’s premature to consider removing it.

**Comment by DmitryArefiev** [comment]
There is a bug about Changing channel options - they are not working now in MU4  #12827. 

So we don't want to support them?

**Comment by cbjeukendrup** [comment]
> So we don't want to support them?

I think that's a question for @Tantacrul

**Comment by Jojo-Schmitz** [comment]
That channel changing option is still needed and important IMHO. The MIDI actions is not and never was, as far as I can tell

**Comment by Tantacrul** [comment]
The current staff text properties system that relates to channels is not compatible with our new engine. Moreover, it also won't be sufficient for anything other than soundfonts, even if we implemented a workaround. we want to replace it with a unified solution that provides (much) more capability for soundfonts & VST in an upcoming release. It's among the most important pieces of work in front of us.

This really is a case of omelette/ eggs, I'm afraid.

**Comment by Tantacrul** [comment]
One point I should make here is that I think a wide % of users are going to no longer be relying on Soundfonts, once Muse Sounds is stable. And even then, the systems we are going to implement will be much more powerful than the MS3 solution for mapping sounds / channels. So any reduction in capability will be short lived

**Comment by DmitryArefiev** [comment]
@Tantacrul @cbjeukendrup I created a task for **Change Channel, MIDI Action** tabs removing #12903. 
(Please notice if want to remove others)

**Comment by DmitryArefiev** [comment]
> That channel changing option is still needed and important IMHO. The MIDI actions is not and never was, as far as I can tell


Yes, using Channel changing option we can assign different techniques to different voices within one staff.  

![Capture3](https://user-images.githubusercontent.com/90187801/185103891-6079acf8-a3d2-4a2b-b08a-2f976ea0c5b1.PNG)



We don't have it yet (when using pizz, arco etc. from Palettes).

**Comment by zacjansheski** [comment]
I will close this since "Change Channel" and "MIDI Actions" are removed in https://github.com/musescore/MuseScore/pull/12913
