### ISSUE TITLE
[MU4 Issue] MuseScore 4 Fails to Playback Microtonal Adjustments on Notes in Files Imported from MuseScore 3

### ISSUE THREAD

**Issue by DaffodilAura** [musescore/MuseScore#12582]
**To Reproduce**
1. Open to MuseScore 3
2. Create a New Score
3. Input notes
4. Go to Inspector and adjust the tunings of the notes by around 50 cents so that the difference is noticeable
5. Save Score
6. Open MuseScore 4
7. Open the aforementioned score from MuseScore 3
8. Attempt to playback the notes...
9. Listen as microtonal adjustments are not reflected in playback

**Expected behavior**
MuseScore 4 should adjust the pitch of note playback according to the tuning values in "Playback" under "Properties"

**Screenshots**
![image](https://user-images.githubusercontent.com/110142307/181516580-15d5fa44-5478-4373-87c3-1fa23834232b.png)
![image](https://user-images.githubusercontent.com/110142307/181516764-f4610064-724c-42e0-ac89-b8a216e18644.png)

**Platform information**
 - OS: Windows 11

**Additional context**
Some things will likely only be found by microtonalists...

**Comment by DaffodilAura** [comment]
This appears to be related to #10990...

**Comment by Tantacrul** [comment]
Please try this build when ready: https://github.com/musescore/MuseScore/issues/13896

**Comment by Tantacrul** [comment]
I've created a score in MS3, added 50 / -50 cent changes and imported to V4 with no problems. Since the original poster isn't responding and the issue appears fixed, I'm closing this.
