### ISSUE TITLE
[MU4 Issue][Intermittent] Crash when deleting palettes

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12604]
**Describe the bug**
Only information I have for now is that this crash happens when deleting palettes. Sometimes after the first deleted palette, sometimes no, sometimes can't catch the crash after deleting all palettes. 
No additional info yet

**Expected behavior**
No crash when deleting palettes

**Screenshots**

https://user-images.githubusercontent.com/101250347/181803339-619bfae6-afca-4564-bbac-7cb5a819dadd.mov

**Platform information**
 - OS: macOS

**Comment by Tantacrul** [comment]
@abariska can you still reproduce this? Wondering if we should keep it in Beta 1 or not.

**Comment by abariska** [comment]
Can't reproduce, so closing for now
