### ISSUE TITLE
[MU4 Issue] Cross-System Selection Note Change Crashes MS4 (if slur is selected)

### ISSUE THREAD

**Issue by KaiVinter** [musescore/MuseScore#12619]
**Describe the bug**
Pretty self-explainable.

**To Reproduce**
1. Open a score with more than 1 system
2. Select a range from a system to another
3. Change the notes with Up/Down arrow keys or with Ctrl/Cmd+Up/Down arrow keys
4. See crash

**Expected behavior**
Notes should be changed accordingly and it shouldn't crash.

**Video**

https://user-images.githubusercontent.com/88064903/182070889-7c0b8169-3f9a-4e9e-aa17-6c3d2538c8ab.mp4

**Platform information**
 - OS: MacOS Mojave 10.14.6

**Additional context**
Tested on the latest Nightly:

MuseScoreNightly-202207310439-master-5859b12.dmg | 2022-07-31 04:52 | 165M
-- | -- | --

**Comment by DmitryArefiev** [comment]
@KaiVinter Thanks for logging!

**Comment by DmitryArefiev** [comment]
The main condition reproduce is the selection should contain a slur

https://user-images.githubusercontent.com/90187801/182134685-22827a1d-5df2-47ad-8360-265eeb2d4d14.mp4

**Comment by DmitryArefiev** [comment]
Fixed in #12620
