### ISSUE TITLE
MuseScore user eval of 4.x - how to download & use separated, in an existing 3.6.x environ?

### ISSUE THREAD

**Issue by gandsnut** [musescore/MuseScore#12616]
I've looked through both the MS websites and here on GH, and can't find instructions how to download any nightly builds of the 4.x work in progress.   Also, I'd be willing to do testing, but would need to know how I keep my existing MS setup isolated.  Also, where are the nightly builds found?   Thank you.

**Comment by Jojo-Schmitz** [comment]
See https://ftp.osuosl.org/pub/musescore-nightlies/ and take a nightly build from the master branch
