### ISSUE TITLE
[MU4 Task] Add icons for "Text line" and "Tempo change" buttons in Properties

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#12623]
**Task description**
This task will resolve https://github.com/musescore/MuseScore/issues/11886, which concerns missing icons for two buttons in the **Properties** panel.

From the latest version of [musescoreicon.zip](https://github.com/musescore/MuseScore/files/9233205/musescoreicon.zip)

- "Text line" will take `ef60`
- "Tempo change" will take `f43f`

<img width="855" alt="Screenshot 2022-08-01 at 8 37 47 pm" src="https://user-images.githubusercontent.com/86290556/182131899-d192957f-ebea-4647-86de-7511ff577878.png">

Thanks!

**Comment by HemantAntony** [comment]
@bkunda I have made a PR: #12634
