### ISSUE TITLE
[MU4 Issue] Playback stops working when switching between audio output devices using low buffer size on Mac (32, 64, 128)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12636]
**To Reproduce**
1. Go to Preferences>I/O>Buffer size
2. Change buffer size to 32 or 64 or 128
3. Start playback - works fine
4. Connect headphones to your Mac
5. Start playback - **no sound**, also playback cursor **may freeze on 32**

That doesn't happen when using 256 - 4096 buffer sizes

**Expected behavior**
Switching between audio output devices during one session should work fine 

**Platform information**
 macOS 

**Additional context**
We added the ability to change buffer size in #12228 but also some related issues have appeared

**Comment by Tantacrul** [comment]
@DmitryArefiev - is this one ready to be assigned or do you need to dig a little more?

**Comment by DmitryArefiev** [comment]
@Tantacrul Yes, it's finished.. I've rechecked in master, and the issue persists in the same way.

Assigning to @Eism

**Comment by DmitryArefiev** [comment]
Also, if the issue will not be fixed during Beta we can just hide 32, 64, 128 buffer sizes

**Comment by Tantacrul** [comment]
> Also, if the issue will not be fixed during Beta we can just hide 32, 64, 128 buffer sizes

@vpereverzev - what do you think of this suggestion? I'm all for it.

**Comment by vpereverzev** [comment]
> > Also, if the issue will not be fixed during Beta we can just hide 32, 64, 128 buffer sizes
> 
> @vpereverzev - what do you think of this suggestion? I'm all for it.

Totally support this idea

**Comment by Tantacrul** [comment]
Moving to post Beta. This means we may or may not get around to fixing the issue prior to the release. If anyone has strong objections, let us know.

**Comment by DmitryArefiev** [comment]
Low buffer sizes removed in #13623 (Fixed)

**Comment by DmitryArefiev** [comment]
Low buffer size support can be added in future
