### ISSUE TITLE
[MU4 Issue] Playback stumbles on 256/512 buffer size on Windows

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12637]
**To Reproduce**

https://user-images.githubusercontent.com/90187801/182210152-893e023d-1b57-4af7-b9e8-f87fd5ab2d35.mp4

**Platform information**
Windows10

**Additional context**
We added the ability to change buffer size in #12228 but also some related issues have appeared

**Comment by Tantacrul** [comment]
I'm curious to know if this is a massive problem to solve?

If it is, should we consider removing the really bad options and bumping it to a later release?

Incidentally, I only get bad results with an orchestral score, with the buffer set to either 32 or 64. In this example, my machine appears to handle it without issues.

**Comment by MarcSabatella** [comment]
Fwiw, my Windows machine (Microsoft Surface Pro 6) chokes on the default 1024 as well, even playing just a single note at a time.  2048 works better.

**Comment by Tantacrul** [comment]
OK, that's good to know.

**Comment by Tantacrul** [comment]
Added a P0 - although I can be talked out of this by @Eism if we think it needs be set to a different priority / project

**Comment by GabeS573** [comment]
This is related to: #11190, #11222, #12349, and #12483

**Comment by DmitryArefiev** [comment]
Low buffer sizes removed in #13623 (Fixed)

**Comment by DmitryArefiev** [comment]
Low buffer size support can be added in future
