### ISSUE TITLE
[MU4 Issue] Auto-generating duplicates of manually generated part scores 

### ISSUE THREAD

**Issue by KleinkMusic** [musescore/MuseScore#12641]
**Describe the bug**
The app generates part-scores after opening a MS3 score in MS4, even if part-scores are already user-generated.

**To Reproduce**
1. Create score on MS3 or older
2. Create one or more part scores
3. Save and exit
4. Open that same score in MS4
5. Click the "Parts" button
6. Result

**Expected behavior**
One would expect to see the manual generated parts without any auto-generating. It's a neat feature to want to generate part-scores upon score creation but it would be helpful to have the system be more context-aware, recognizing already existing parts and only generating when parts don't already exist.

**Screenshots**
Score parts in MS3 ![image](https://user-images.githubusercontent.com/104653161/182338833-b345cd77-88da-41d2-9586-6995cb8ce388.png)
Same score in MS4 
![image](https://user-images.githubusercontent.com/104653161/182338953-658388c4-3251-4337-a64b-76304c0297f3.png)

**Platform information**
 - OS: Windows 10

**Additional context**
From the looks of it, they aren't necessarily duplicates, but rather just a consequence of adding a system that auto-generates parts upon score creation. In some cases, there will be a score with specific custom parts and those auto-generated by the app won't really reflect them, simply generating for the individual part as-is.

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/14288
