### ISSUE TITLE
[MU4 Issue] After applying Transpose, score loses focus and stops to recieve keyboard commands (Windows and Linux)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12659]
**Describe the bug**
After applying Transpose, score loses focus and stops to receive keyboard commands (**Play with Space, Select All with Ctr+A, Esc** etc. )

**To Reproduce**
1. Open any score
2. Run Transpose dialog (Tools>Transpose)
3. Select some value and click OK
4. Start playback with Space - **nothing happens**

https://user-images.githubusercontent.com/90187801/182594338-61443126-2cc7-43a4-a725-b5787dd8fa64.mp4

**Platform information**
**Windows, Linux**
Doesn't occur on Mac

**Additional context**
Doesn't occur in **MU3**

**Comment by Eism** [comment]
@DmitryArefiev I can't reproduce
Please recheck on master

**Comment by DmitryArefiev** [comment]
@Eism Yes, the same on my side now.

Tested in latest master on Win10, LinuxUbuntu 22.04 - **FIXED**

Closing
