### ISSUE TITLE
[MU4 Issue] [Inspector] Text options which have no effect for dynamics should be disabled/greyed out

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12656]
**Describe the bug**
Text options which have no effect for dynamic should be disabled/greyed out. They should not give an expectation for user that he change those dynamic parameters via Inspector.

 

https://user-images.githubusercontent.com/90187801/182580417-5d6fb054-b779-4bfa-9bc0-629cc5557203.mp4

**Platform information**
 macOS, Windows, Linux

**Additional context**
The same issue **occurs in MU3**

**Comment by oktophonie** [comment]
The font and style (bold/italic) have no effect on dynamics symbols, but these items (which are just normal text strings) can be extended to also include other text, in which case these settings do become relevant.

**Comment by DmitryArefiev** [comment]
> The font and style (bold/italic) have no effect on dynamics symbols, but these items (which are just normal text strings) can be extended to also include other text, in which case these settings do become relevant, e.g.:
> 
> ![dynamics-styles](https://user-images.githubusercontent.com/20604032/182586021-83155a4d-8f2b-49a9-9d39-bf03c52694c4.png)

Oh I see, you absolutely right. Let's close this as expected.

Thanks!

**Comment by DmitryArefiev** [comment]
**Working as intended**

Closing
