### ISSUE TITLE
[MU4 Issue] VST plugin doesn't sound until meet dynamic sign 

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#12668]
**Describe the bug**
After adding VST plugin you can get sound from it when playing from the begine of score or from place with dynamic sign

**To Reproduce**
1. Open the score 
[97117.mscz.zip](https://github.com/musescore/MuseScore/files/9253607/97117.mscz.zip)

2. Start playback with soundfont first
3. Stop and add VST instead soundfont
4. Play the score 
5. Pay attention to the place where VST started playing

**Expected behavior**
VST starts playing after adding 

**Screenshots**

https://user-images.githubusercontent.com/101250347/182666907-d83c2856-a137-4ff4-b97d-a16887518e48.mov

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Comment by cbjeukendrup** [comment]
Aside: in debug builds, this scores appears to cause crashes. It looks like the score is from 1.3, and it seems like we're not really prepared for that. The logs contain multiple messages about unrecognized data in the XML.

**Comment by boryskuzmenko** [comment]
@cbjeukendrup only bug I found related to MU1.x is https://github.com/musescore/MuseScore/issues/11843
You can add info to description if any

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
