### ISSUE TITLE
[MU4 Issue] [VST] Notes from selecting notes are frozen when selecting during playback 

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12669]
**Describe the bug**
The issue is reproducible on Sample Tank, Vital, OB-Xd

**To Reproduce**
1. Open the score [test.mscz.zip](https://github.com/musescore/MuseScore/files/9253637/test.mscz.zip)
2. Assign VST synth
3. Play it and at the same time select different notes 

**Expected behavior**
Notes from selecting notes are played as usual when selecting during playback 

**Screenshots**

https://user-images.githubusercontent.com/101250347/182668603-735138c0-d1c7-44c8-9ea2-cbb976098598.mov

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Comment by Tantacrul** [comment]
Is this problem still present in the latest nightly?

**Comment by abariska** [comment]
Yes, it's still actual
