### ISSUE TITLE
[MU4 Issue] [UI Finesse] On wide screens, the text in Learn > Classes is too wide to be comfortably readable

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12673]
**Describe the bug**
If the MuseScore window is relatively wide, like full screen on a 27" screen, the text in Home > Learn > Classes becomes too wide to be comfortably readably (i.e. there are too many words per line; lines too long).

**Expected behavior**
Text should have a maximum width. Most (accessibility) guidelines say max 50-80 characters per line; so I guess that can be translated to something like 576 pixels.

**Screenshots**
<img width="2672" alt="Schermafbeelding 2022-08-04 om 01 12 12" src="https://user-images.githubusercontent.com/48658420/182728095-8c362446-20cf-426c-86ec-1188bef844c6.png">

**Comment by MarcSabatella** [comment]
Also on less wide screen, it doesn't scroll.  On mine, I can't see the button :-(

**Comment by Eism** [comment]
@jessjwilliamson 
Can you look at this issue? 
How can we best solve the problems of Casper and Marс?

@iwoithe Let's wait for Jessica's answer

**Comment by jessjwilliamson** [comment]
> @jessjwilliamson Can you look at this issue? How can we best solve the problems of Casper and Marс?
> 
> @iwoithe Let's wait for Jessica's answer

Hi! Thank you for reaching out to me. I can suggest a few things that might solve this issue, with screenshots I provided of new design. This is also updated on Figma in HOME_TAB. 
One thing I'd also add is I don't believe there is a point of having a search box in this specific Classes page. Get started and Advanced should still have search box but not Classes. :) So...

- The BG1 rounded box behind text should be maximum 1000 pixels wide, which means the text box (in Figma anyway) would be reduced to 928 pixels, so it can fit within the padding and BG1 box.
- To make text more readable I'd suggest create another paragraph on sentence "In addition," etc.
- If it's possible, I did this in Figma but paragraph spacing between text lines I've made a bit taller to 6.

Here's what it would look like in different screens sizes, and yes this page should be scrollable for small screens if this section is too big.

![image](https://user-images.githubusercontent.com/71656189/184333410-8382ad1c-b26c-4f14-8350-7dc56307bf7c.png)
![image](https://user-images.githubusercontent.com/71656189/184333445-af400303-91ed-4712-b41c-9f767d6be5d0.png)
![image](https://user-images.githubusercontent.com/71656189/184333470-823c93e0-8056-449b-ae62-a9f28acbe61a.png)

**Comment by aritroCoder** [comment]
is this issue avalable now? I am a beginner in C++ and want to contribute if possible

**Comment by HemantAntony** [comment]
Hello! Welcome to MuseScore!

This issue already has a PR by @iwoithe . However, I do not think that PR has the updated specs @jessjwilliamson provided

@iwoithe Are you still working on this?

**Comment by iwoithe** [comment]
> @iwoithe Are you still working on this?

Yeah, sorry for the inactivity. My life has picked up quite significantly in the last few weeks and will probably stay that way for another few weeks.

@aritroCoder Go for it. :slightly_smiling_face:

**Comment by aritroCoder** [comment]
![image](https://user-images.githubusercontent.com/92646038/189517343-d751c1d9-8eb8-4434-a00e-39c23209add9.png)
I am getting this warning in ubuntu, should I go ahead and install it, or there is something else i need to do?

**Comment by HemantAntony** [comment]
This is the wiki for building projects: https://github.com/musescore/MuseScore/wiki/Set-up-developer-environment

It should tell you how to install cmake and git

It also tells you how to build and run the project

**Comment by GargDivanshu** [comment]
Hey I wish to contribute if the issue is still not resolved can I do it to you?

**Comment by HemantAntony** [comment]
@aritroCoder might be working on this. If you aren't, can you say so?

**Comment by aritroCoder** [comment]
Sorry, I was not able to respond for a while, yes I am working on it, already set up the development environment, and now trying to understand the source a little more

**Comment by aritroCoder** [comment]
I have followed the steps as given in the doc till https://github.com/musescore/MuseScore/wiki/Compile-on-the-command-line
But now I am getting error while trying to run `./build.cmake`
![image](https://user-images.githubusercontent.com/92646038/189984489-091f25ce-fa19-4e1c-8128-b5136d00462a.png)

Please assist me to identify why I get this error as I did all the steps mentioned correctly

**Comment by octopols** [comment]
Can I work on this?

**Comment by octopols** [comment]
I would like to work on this, can someone assign me this issue?

**Comment by octopols** [comment]
> > @jessjwilliamson Can you look at this issue? How can we best solve the problems of Casper and Marс?
> > @iwoithe Let's wait for Jessica's answer
> 
> Hi! Thank you for reaching out to me. I can suggest a few things that might solve this issue, with screenshots I provided of new design. This is also updated on Figma in HOME_TAB. One thing I'd also add is I don't believe there is a point of having a search box in this specific Classes page. Get started and Advanced should still have search box but not Classes. :) So...
> 
> * The BG1 rounded box behind text should be maximum 1000 pixels wide, which means the text box (in Figma anyway) would be reduced to 928 pixels, so it can fit within the padding and BG1 box.
> * To make text more readable I'd suggest create another paragraph on sentence "In addition," etc.
> * If it's possible, I did this in Figma but paragraph spacing between text lines I've made a bit taller to 6.
> 
> Here's what it would look like in different screens sizes, and yes this page should be scrollable for small screens if this section is too big.
> 
> ![image](https://user-images.githubusercontent.com/71656189/184333410-8382ad1c-b26c-4f14-8350-7dc56307bf7c.png) ![image](https://user-images.githubusercontent.com/71656189/184333445-af400303-91ed-4712-b41c-9f767d6be5d0.png) ![image](https://user-images.githubusercontent.com/71656189/184333470-823c93e0-8056-449b-ae62-a9f28acbe61a.png)

I was not able to remove the search box only from the class tab in learn. In the PR the search box is gone from the learn page itself.

**Comment by octopols** [comment]
![max_1000_px](https://user-images.githubusercontent.com/90182257/214950106-de6b6b34-3c51-42fb-b17c-f5f5996b6eb0.png)
![scrollable_can_go_under_1000](https://user-images.githubusercontent.com/90182257/214950119-94efc16d-be96-48e1-b541-1c762c60a8e1.png)

**Comment by jessjwilliamson** [comment]
@octopols Thank you for jumping in! For search bar don't worry about removing it at all then if it's causing issues. We want to especially use it in the Get started tab!
Your screenshots look good - is there a PR I can test? :)

**Comment by octopols** [comment]
> @octopols Thank you for jumping in! For search bar don't worry about removing it at all then if it's causing issues. We want to especially use it in the Get started tab! Your screenshots look good - is there a PR I can test? :)

I was able to fix the search box thing in the second commit of the PR #16087. Now it's visible in the Get started tab and hidden in the classes tab.
