### ISSUE TITLE
[MU4 Task] Add 'Don't show again' checkbox to MU3 scores import dialog

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12681]
**Task description**

Import MU 3 scores dialog
![Capture2](https://user-images.githubusercontent.com/90187801/182847208-4c2f9970-83a0-4263-8ec2-6a7c8e6c0920.PNG)

Import MU 2 scores dialog
![Capture](https://user-images.githubusercontent.com/90187801/182847230-21e29648-8292-454a-9b2d-0350198e6ce0.PNG)

**Comment by cbjeukendrup** [comment]
Maybe "Don't show again" or "Don't show this message again", consistent with other dialogs.

**Comment by DmitryArefiev** [comment]
> In the newer dialogue there is no question and no choice so "Don't ask again" would have the wrong verb.



> Maybe "Don't show again" or "Don't show this message again", consistent with other dialogs.

Yeah, that makes sense. Thanks!

**Comment by Jojo-Schmitz** [comment]
Adding to #12635? And if so, how exactly?

**Comment by DmitryArefiev** [comment]
> Maybe "Don't show again" or "Don't show this message again", consistent with other dialogs.

@Tantacrul Please choose the right variant. And also there is should be a design solution for the dialog probably?

Thanks!

**Comment by DmitryArefiev** [comment]
> Adding to #12635? And if so, how exactly?

@Jojo-Schmitz Probably yes (should be added to translation task)

**Comment by Tantacrul** [comment]
@bkunda ill leave this question with you and @oktophonie

**Comment by cbjeukendrup** [comment]
(In this case we don't need to worry about the translation, because the strings "Don't show again" and "Don't show this message again" already exist in the "global" context.)

**Comment by bkunda** [comment]
> @bkunda ill leave this question with you and @oktophonie

I think I'd be in favour of "Don't show this message again", just to make it abundantly clear that the checkbox relates to the dialog, and not to its content ("Don't show again" _might_ be confused with "don't show these changes again..."). It is also consistent with other dialogs elsewhere in the app.

@DmitryArefiev this is how I would arrange the elements: 

<img width="1064" alt="Screenshot 2022-08-05 at 11 35 21 pm" src="https://user-images.githubusercontent.com/86290556/183088520-fb9289c2-c658-470a-acbd-14b81e19b950.png">

Thanks!
Bradley

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz I see that you changed the text for the "large"  migration dialog, for pre-3.5 scores (`"Don't ask again"` → `"Don't show this message again"`).
Just to be sure, @bkunda, is this what you expect, or was your suggestion only intended for the small dialog for 3.6 scores? 

(I could imagine we want different texts for both versions of the dialog, because the large one is in fact a question so <code>"Don't _ask_ again"</code> makes sense there, and the small one is just a message, so <code>"Don't show this message again"</code> makes sense there.)

**Comment by Jojo-Schmitz** [comment]
There's no other use of `Don't ask again` anywhere in the code, so I could change only that single one.,

**Comment by Jojo-Schmitz** [comment]
Should I remove it from #12635? then?

**Comment by boryskuzmenko** [comment]
@Jojo-Schmitz yep. Thanks!

**Comment by Jojo-Schmitz** [comment]
done
