### ISSUE TITLE
[MU4 Issue] Menu options are not executed on Alt+letter

### ISSUE THREAD

**Issue by SilverGreen93** [musescore/MuseScore#12688]
Start MuseScore 4, Hold down Alt+F to access the File menu, then press O to open a file.

The File menu opens, the Open option is selected, but does not get executed. This is not what is expected, as a normal UI would execute the command right away the letter is pressed on the keyboard.

As a workaround you can press Enter after pressing O, but it requires an extra keypress.

Tested on Windows 11 with musescore nightly from 2022.08.04.

**Comment by DmitryArefiev** [comment]
Fixed in #13009
