### ISSUE TITLE
[MU4 Issue] Note input from MIDI keyboard can be not so accurate as in MU3, some notes are not picked up when entering chords (Mac)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12694]
**Describe the bug**
Note input from MIDI keyboard can be not so accurate as in MU3, some notes are not picked up sometimes.  Check on chords with more than 5 notes

**MU3**

https://user-images.githubusercontent.com/90187801/183108706-5b824bdd-fe08-4095-863b-91ccc40b6de7.mov

**MU4**

https://user-images.githubusercontent.com/90187801/183108731-d36d53bc-c2e7-4dd9-a1ab-71d2ff6634b3.mov

**Platform information**
macOS

**Additional context**
#12261

**Comment by abariska** [comment]
I can't reproduce this issue anymore. 
@DmitryArefiev could you recheck?

**Comment by DmitryArefiev** [comment]
@abariska Still occurs on my side (latest master, Mac12.6, Arturia KeyLab 61 Essential USB)

**Comment by bkunda** [comment]
@DmitryArefiev Still able to reproduce in MacOS with MS4. 

https://user-images.githubusercontent.com/86290556/190997466-e6f8ce46-b1cc-4879-9a1d-80a5e54cc461.mov

Part of this experience for me made me wonder whether the issue was related to how sensitively MS is recognising the input signal; the seventh chord I play in the above video, for example, could potentially be a result of my not playing both hands _exactly_ together.

But, as something of a sanity check, I did try using a flat, level object to press all the keys down simultaneously (see the lower-pitch chords towards the end of the video). Turns out this was worse than when I used my own fingers (which is, as far as my piano technique goes, something of a relief 😅).

For what it's worth, this was tested using a Roland F701.

And unfortunately I couldn't get MS3.6 to recognise my keyboard, which is bizarre, but as a result I was unable to do a comparative test this time around.

**Comment by DmitryArefiev** [comment]
@bkunda Thanks!

**Comment by DmitryArefiev** [comment]
@Tantacrul I think we can move it to Beta2. MIDI note input is better in **MS3** but the basic things work fine in **MU4** :  

https://user-images.githubusercontent.com/90187801/193644657-2bbcc174-d071-4dc6-bf23-b83215c465fd.mov


There are some issues with delay and with missing notes in cluster chords (on Mac) but it's not critical for now

**Comment by Tantacrul** [comment]
Since it is likely that we will release once everything in Beta 1 is complete, I think we should leave this here.

However, @Eism / @RomanPudashkin - it's fine to focus on other issues for now. I'd like to understand how difficult / unknown / time-consuming these fixes will be.

**Comment by Eism** [comment]
@Tantacrul 
It's hard for me because I can't reproduce it. This may be due to the fact that I have a specific midi keyboard or that I press the keys in a wrong way.

**Comment by Tantacrul** [comment]
@DmitryArefiev - what device do you have? Perhaps we ask to get Elnur the same one?

**Comment by DmitryArefiev** [comment]
@Tantacrul I have Arturia KeyLab 61 Essential. It might help but I'm not sure...
 
I think the root issue here that **MU4** has a **bit more delay** when entering notes from MIDI keyboard comparing with **MS3**. It could be due to general performance issue (MU4 take more cpu comparing with MS3) 
 Maybe @vpereverzev can help to understand is it related or not.

@Tantacrul To understand how critical or not the current issue  (_Note input from MIDI keyboard can be not so accurate_) you should try MIDI note input in MS3 and in MU4.  I think for basic note input, MU4 works fine.

**Comment by Tantacrul** [comment]
@jessjwilliamson @bkunda - it would be good to get your thoughts on this by comparing MS3 with MS4 quickly and determining how much of a problem this is? When you have time. I'll jump on it when I have a chance too.

**Comment by bkunda** [comment]
I just had another look at this. The time between striking a key on the piano keyboard and having it register in note input mode is definitely slower in MS4 than in MS3. 
But for general note entry purposes, I'd say the way MS4 currently works is still adequate. Things can get a bit dicey if you try to enter large note clusters, but we aren't talking about the majority of user cases here, so I think we can safely save this for a future optimisation.

**Comment by Tantacrul** [comment]
@Eism - so the first point about latency could be addressed it seems.

Specifically the comparison between MS3 and MS4. If this is a much tougher piece of work to do, perhaps we move it to 4.x. Let me know if it's something you think you can look into or whether you think it will take a lot of time.

**Comment by hpfmn** [comment]
Is this still being worked on? Midi note input is a nightmare in 4.x compared to 3.x

**Comment by DmitryArefiev** [comment]
Looks good in #20568 (comparing with master)
