### ISSUE TITLE
[MU4 Issue] Key signatures from Instrument change from top staff are duplicated to new staves 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12690]
**Describe the bug**
Key signatures from Instrument change (transposing instrument) from top staff are duplicated to new staves 

**To Reproduce**
1. Open [KS.zip](https://github.com/musescore/MuseScore/files/9268239/KS.zip)
2. Add Flute - **Key signatures should not be copied from Oboe 1 to Flute**

https://user-images.githubusercontent.com/90187801/183071253-ccc3c59d-a5ba-4a48-92b8-c7dbdef8ab13.mp4

And also unable to delete key signatures independently (you need to create Instrument change again to have proper KS)

https://user-images.githubusercontent.com/90187801/183073472-d3afc306-4c07-4959-bcdd-8ba52f1088e2.mp4

**Platform information**
 macOS, Windows, Linux

**Additional context**
* This bug also happens with user-created local key signatures; not only with local key signatures that are created as a result of adding an instrument change.
 (To create a local key signature, hold Ctrl/Cmd while adding it from the Palette; to select a key signature on one staff only, hold Ctrl/Cmd while clicking it, which allows you to delete it for that staff only.)

* Also occurs in **MU3**

**Comment by DmitryArefiev** [comment]
Could be removed to Beta2 since the bug occurs in MU3

**Comment by cbjeukendrup** [comment]
This bug also happens with user-created local key signatures; not only with local key signatures that are created as a result of adding an instrument change.

(To create a local key signature, hold Ctrl/Cmd while adding it from the Palette; to select a key signature on one staff only, hold Ctrl/Cmd while clicking it, which allows you to delete it for that staff only.)

**Comment by DmitryArefiev** [comment]
Thanks! Added to the description
