### ISSUE TITLE
[MU4 Issue] Missing Qt translation

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#12700]
**Describe the bug**
Not all Qt button (and perhaps some dialog options) are translated to Dutch.
This might apply to other languages as well. This depends on the Qt version being used to compile the code.
Qt 5.x does not include the Dutch text file library.
For MS3 this was resolved by including the "qt_nl.ts" file in the locale folder (being distributed as .qm with the install).
I believe this file is even customized for some texts which are missing in some language files.

**To Reproduce**
1. Open MS4
2. Select Dutch (Nederlands) as the language
3. Load a Score or create a new one
4. Open a dialog which contain standard Qt buttons (i.e. Page Settings - Pagina Instellingen)
5. Check the buttons. Cancel should be Annuleer in Dutch and OK is normally written as Ok.

**Expected behavior**
Dialog buttons should showing in selected language.
NOTE: I believe to recall it was not only buttons in MS 3 (or might have been MS 2 even) which should English while using Dutch language. Some common dialog text messages would appear "untranslated" as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/13550012/183147671-1f697de5-8d29-4e6b-91ae-215746b78af0.png)

**Platform information**
 - OS: Windows 10 using MS4 Nightly dated: 5th Aug 2022

**Additional context**
As mentioned there are more languages in the MS3 share/locale folder.

**Comment by Jojo-Schmitz** [comment]
That's rather a Qt problem than a MuseScore one, we rely on Qt's translations for these.
Contribute translations to Qt and MuseScore and all other users of Qt would benefit from it.

In short: this is nothing MuseScore can fix, short of dropping all the standard Qt dialog elements and rolling out ones.

**Comment by henkdegroot** [comment]
@Jojo-Schmitz I don't agree with you and we had this discussion many years ago as well. Check the 3.x branch and you will notice the included qt_nl.qm and ts file. They are not in MS4.

**Comment by Jojo-Schmitz** [comment]
I don't recall having had that discussion.
If qt_*.qm files are missing in MS4, that is a bug in the MuseScore build indeed.
If the qt_nl.qm is lacking the translation of the OK and Cancel buttons though, it is a Qt bug we can't solve.

**Comment by Jojo-Schmitz** [comment]
Hold on, in the far back of my head theres a bell ringing...
Yes, i seem to remember that we indeed did tamper with some qt_* files in addition to those provided by Qt. Need to dig deeper for the dirty details

**Comment by Jojo-Schmitz** [comment]
Hmm, in the 3.x repo in ...share/locale we do have 13 qt_*.ts files,  2 of them are empty, qt_lv.ts and qt_gd.ts, so I guess those are not needed at all anymore (any maybe weren't ever needed)?
So for fixing (a part of) this should be to get those (remaining 11) back into the repo?
I'll add them to #12635.

**Comment by Jojo-Schmitz** [comment]
Hmm, in the 3.x repo in ...share/locale we do have 13 qt_*.ts files.
So for fixing (a part of) this should be to get those back into the repo?
I'll add them to https://github.com/musescore/MuseScore/pull/12635.

Edit: seems this isn't sufficient, the step to copy them into the install dir seems missing too

**Comment by Jojo-Schmitz** [comment]
Seems indeed fixed:
![image](https://user-images.githubusercontent.com/1786669/183245900-78d75c53-1960-443a-adfa-746174672bf0.png)

**Comment by Jojo-Schmitz** [comment]
Manually reinstating that lost/deleted qt_nl.qm:
![image](https://user-images.githubusercontent.com/1786669/183247510-7eb87fae-38a0-4717-a299-350cd9bc4aca.png)

**Comment by henkdegroot** [comment]
@Jojo-Schmitz, thank you

Regarding the delete of the .qm files, I have noticed this as well and wanted to report an issue. However it only seems to apply to Dutch. I tried with German and Afrikaans...but no problem with these languages. Will need to do some more testing. For Dutch it is even worse, as after factory reset....Dutch no longer exist as a selectable language (as the files are deleted from the install folder).

**Comment by Jojo-Schmitz** [comment]
Very strange. Might be due to no Dutch translation being available from Qt?

**Comment by henkdegroot** [comment]
That is why I tried with Afrikaans, as there does not seem to be a Qt file for that as well.

**Comment by Jojo-Schmitz** [comment]
Not even after my change

**Comment by shoogle** [comment]
If we provide a manual translation for OK and Cancel with the right context then it will probably work. Are there any other Qt strings that are not being translated?

**Comment by Jojo-Schmitz** [comment]
Probably, all from the `QDialogButtonBox` and most probably more.
Still removing the old translations, and from the install dir, is not OK at all.
I guess it is happening here:
```
Ret LanguagesService::removeLanguage(const QString& languageCode) const
{
    io::paths_t files = configuration()->languageFilePaths(languageCode);

    for (const io::path_t& filePath: files) {
        Ret ret = fileSystem()->remove(filePath);
        if (!ret) {
            LOGE() << "Error remove file " << filePath << ret.toString();
            return make_ret(Err::ErrorRemoveLanguageDirectory);
        }
    }

    return make_ret(Err::NoError);
}
```

**Comment by cbjeukendrup** [comment]
We should absolutely not be deleting qm files that are package with the app when the user updates a language. In other words, MuseScore should never modify itself during runtime. I will change this asap.

If we properly pack the Qt translation files with MuseScore, is there then still a reason to try to provide manual translations for Qt's buttons? 
(It would be better if we can just use Qt's own translation files, because those `QDialogButtonBox` are not the only strings: the "About Qt" dialog, the Open/Save dialog on platforms where a native dialog is not supported... probably even more.)

**Comment by Jojo-Schmitz** [comment]
> We should absolutely not be deleting qm files that are package with the app when the user updates a language. In other words, MuseScore should never modify itself during runtime.

Indeed!

> I will change this asap.

Thanks

> If we properly pack the Qt translation files with MuseScore, is there then still a reason to try to provide manual translations for Qt's buttons? (It would be better if we can just use Qt's own translation files, because those `QDialogButtonBox` are not the only strings: the "About Qt" dialog, the Open/Save dialog on platforms where a native dialog is not supported... probably even more.)

No. That's why I'd rather add those files back. In addition to using the ones that come from Qt directly.

**Comment by henkdegroot** [comment]
> We should absolutely not be deleting qm files that are package with the app when the user updates a language. In other words, MuseScore should never modify itself during runtime. I will change this asap.

Change is very much appreciate, as I did some more testing now and even loose language because of this. First thought it was only Dutch, but it happens to all languages.
- Select a custom language
- Click check for update (make sure to use a language which has updates)
- Restart MS
- All good now and displayed in the selected language
- Now revert to factory settings
- Restart MS
- MS is now back to English and when you select the previous used custom, there is no error but MS keep being displayed in English.

**Comment by henkdegroot** [comment]
> No. That's why I'd rather add those files back. In addition to using the ones that come from Qt directly.

Move to Qt6 will help as well (at least for NL)....but think it will be a while for that is being done.

**Comment by shoogle** [comment]
> is there then still a reason to try to provide manual translations for Qt's buttons?

Only if Qt doesn't provide a translation in a particular language that we are providing translations for.
