### ISSUE TITLE
Add new instrument Bass Tuba (bass clef) in Bb transposing

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#12705]
**Describe the bug**
A short and clear description of what the bug is.
~~Bass Tuba (treble clef) Bb is missing in MS4 instruments. Should be included as transposing instrument.~~
~~Bass Tuba Bb is missing in MS4 instruments. Only F and Eb exist.~~
~~Bass Tuba C is missing in MS4 instruments. Only F and Eb exist.~~

And it would be nice if a Bass Tuba Bb with bass clef as transposing instrument could be added as well. This is used in several european countries and is missing in MS.

**To Reproduce**
1. Open Instruments dialog
2. Select all instruments
3. Select Brass section
4. Check the instrument list

**Expected behavior**
Instruments which existed in MS3 (and which are even used in templates) should be available in MS4.

**Platform information**
 - OS: Windows 10

**Comment by Tantacrul** [comment]
@oktophonie and @shoogle - can you advise on this issue and I'll prioritise it then.

**Comment by shoogle** [comment]
I think the Bb and C tubas still exist in MuseScore 4 but they have been renamed to "Contrabass tubas", presumably because @oktophonie felt this is a more accurate name for them. This includes the treble clef variety.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/11011881/184758351-97193a4f-72ee-434b-88a1-d611b18060c1.png">

We've never had a transposing Bb tuba in bass clef so that is a feature request rather than a bug. I'll leave @oktophonie to comment on whether he thinks it necessary to add one of those.

**Comment by henkdegroot** [comment]
Good spot.....Contrabass Tuba....never knew I am playing a Contrabass Tuba. It is definitely not a commonly used name (to my knowledge) and could be confusing for users. I also cannot recall I have ever seen a published UK style Brass Band score which refers to Contrabass Tuba. There is just Tuba Eb and Tuba Bb, both in Treble Clef and as transposing instruments. Sometimes they are referred to as Bass Tuba. 

See also: https://www.besson.com/en/instruments/tubas/sovereign-be994/ and https://usa.yamaha.com/products/musical_instruments/winds/tubas/ybb-641/index.html

If the suppliers of these instruments are not using that terminology, then I think it would be an odd decision to name it Contrabass in MS.

Regarding the transposing Bb tuba in bass clef, this has been discussed for MS3 many times and is posted in the forum as well several times. The feature request to add this was mainly rejected as it would be hard to see which instrument is what in the MS3 instrument list. Happy to leave as is in MS4, but thought about mentioning it just in case it was an easy thing to do.

**Comment by henkdegroot** [comment]
> we're actually thinking about divorcing instrument definitions from notation conventions

That sounds like an excellent solution. Asong as keep/get the flexibility to select tranaposing or not for all variants but from your comment that is covered.

With that state, I am happy to close this issue.
