### ISSUE TITLE
[MU4 Issue] VST3 asserts, and freezes with multi-out

### ISSUE THREAD

**Issue by eyalamirmusic** [musescore/MuseScore#12701]
When building an almost empty JUCE VST3 plugin and loading it into MU4, there's an assert happening in the JUCE hosting code due an an incorrect call order.

If there are more than two output buses in the plugin, this also results in a freeze that stops the plugin from playing sound.

That was tested on MacOS 12.5, on both M1 Macbook pro and M1 Mac Mini.

To reproduce using Mac/CMake:
1. git clone https://github.com/eyalamirmusic/JUCECmakeRepoPrototype
2. cd JUCECmakeRepoPrototype
3. cmake -G Xcode -B build -D CMAKE_OSX_ARCHITECTURES="x86_64"
4. cmake --build build --target DummySynth_VST3
Or - load the project in Xcode and build the DummySynth_VST3 target.
5. Load the plugin in MuseScore into a channel.

The assert is happening in the following code in the JUCE VST3 wrapper:
```cpp
tresult PLUGIN_API activateBus (Vst::MediaType type,
                                    Vst::BusDirection dir,
                                    Steinberg::int32 index,
                                    TBool state) override
    {
        // The host is misbehaving! The plugin must be deactivated before setting new arrangements.
        jassert (! active);
```

**Comment by Tantacrul** [comment]
@RomanPudashkin / @vpereverzev - I'll need some advice on assigning / prioritising this.

**Comment by Tantacrul** [comment]
I've popped it into beta2 for now. Gave it a P1 too.

**Comment by RomanPudashkin** [comment]
I'm pretty sure this was fixed in this commit (by changing the order of calls in VstAudioClient::updateProcessSetup(): ensureActivity() is now called after setUpProcessData()): https://github.com/musescore/MuseScore/pull/22791/commits/a52916decfdf48d04ec8c742850f7d68ec711857. Please reopen if it still occurs
