### ISSUE TITLE
[MU4 Issue] Language update check not working when set to System Default

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#12702]
**Describe the bug**
At the start of MS4, it detects my system language is Dutch and shows the GUI with Dutch strings.
When I check in preferences, I noticed the language is set to "System Default".
Click the "Check for update" button now and the system tells me it is up-to-date.
I know this is not correct, as not all text is shown in Dutch.
When I change the "System Default" to "Nederlands" (Dutch) and click the "Check for update" button, it will download and update the  latest language and update.

**To Reproduce**
See "describe the bug"

**Expected behavior**
Check for update should work while the "System Default" is selected.

**Platform information**
 - OS: Windows 10 with Dutch language

**Comment by henkdegroot** [comment]
@cbjeukendrup, this is the issue I referenced on Discord.

**Comment by Tantacrul** [comment]
@cbjeukendrup - let me know if you're happy for me to assign this to you.

**Comment by cbjeukendrup** [comment]
Yes, in fact I'm already working on it :)
