### ISSUE TITLE
[MU4 Issue] Migration dialog: engraving example shows MU3.6 engraving

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12711]
**Describe the bug**
The engraving example in the Migration Dialog shows the MU3.6 engraving, and not yet the improved MU4 engraving. This is particularly noticeable from the beams, but also from the slurs and horizontal spacing. We should simply update or replace the image.

**The image:**
<img width="590" alt="Scherm­afbeelding 2022-08-07 om 15 39 55" src="https://user-images.githubusercontent.com/48658420/183293597-8c185b1e-aedb-44e5-b71e-14e5b3eef386.png">

**The current engraving:**
<img width="590" alt="Scherm­afbeelding 2022-08-07 om 15 41 01" src="https://user-images.githubusercontent.com/48658420/183293635-4dbd0513-c658-4915-9282-88c0d06147e7.png">

**Comment by oktophonie** [comment]
Good point!
(strictly, the F should have an l.v. symbol on it, rather than a slur/tie)

**Comment by Tantacrul** [comment]
@oktophonie and @jessjwilliamson - can you collaborate on the replacement image and then ask someone to make the replacement?

**Comment by HemantAntony** [comment]
Someone call me? :)

**Comment by Tantacrul** [comment]
Haha. You're the best man!

**Comment by jessjwilliamson** [comment]
Updated on Figma 'SCORE MIGRATION' ready to go :)

![image](https://user-images.githubusercontent.com/71656189/184849253-5098020d-8b89-49a6-b7a8-8e768f95f5f8.png)

**Comment by Tantacrul** [comment]
Does @HemantAntony have access to that Figma?

You may need to send him the image directly.
