### ISSUE TITLE
[MU4 Issue] Mute and Solo buttons don't work for Chord Chanel

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#12716]
**Describe the bug**
In the latest NightlyBuild the chord channel is visible in the mixer. However, the Solo and Mute buttons do not work here. Also the chords are quite loud in contrast to the other channels.

**To Reproduce**
1. Create a new score and add some Chords
2. Got to the mixer and try to solo/mute the Chord chanel
3. Notice how loud the chords are

**Expected behavior**
The chord channel should be muted and soloed just like the other channels. 

**Screenshots**
For my personal use Chord Chanel should be in about -18 below the other channels
![Screenshot 2022-08-08 083442](https://user-images.githubusercontent.com/63284090/183354801-ecfeb1c1-cd6d-4f78-b8fc-c7964fcd465d.png)

**Platform information**
 - OS: Windows 11

**Additional Information**
https://github.com/musescore/MuseScore/issues/11031

**Comment by DmitryArefiev** [comment]
Thanks for logging!

**Comment by DmitryArefiev** [comment]
Fixed in #12926
