### ISSUE TITLE
[MU4 Issue] Crash with Vinyl VST plugin

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12726]
**Describe the bug**
After some manipulations with Vinyl MU4 is crashed (see first part of video)
When changing some settings on Vinyl and saving score than the score can't be opened again (crashed without any notifications)

**To Reproduce**
1. Open any score and assign Vinyl VST to the master track
2. Open the plugin and raise the Scratch amount
3. Move Gain of the Scratch to 100% and unclick the mouse button
4. Move the Gain of the Scratch to 0 
5. If no crash repeat the same

OR try to open this score with saved Vinyl inside (see second part of video)
[97117 MU4.mscz.zip](https://github.com/musescore/MuseScore/files/9282348/97117.MU4.mscz.zip)

Also, this this plugin doesn't save its settings when saving score!

**Expected behavior**
No crash when using Vinyl VST plugin

**Screenshots**

https://user-images.githubusercontent.com/101250347/183436150-efcd9b09-d0ae-40b6-93cf-7faabb6420b4.mov

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Comment by DmitryArefiev** [comment]
@abariska I can't reproduce it on my side with latest master.. Can you try again on your Mac please?

**Comment by abariska** [comment]
🟢 **Can't reproduce**
Tested on macOS 12.6
