### ISSUE TITLE
[MU4 Issue]  When the score file from explorer, MU shows a whole path instead of just a file name and after re-saving it makes the score corrupted and unreadable (Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12728]
**To Reproduce**
1. Open score from Explorer (not from MU and not via drag'n'drop)

![Capture](https://user-images.githubusercontent.com/90187801/183473920-4ceb6a8f-1039-48cc-a693-0f5e92a02a1b.PNG)

https://user-images.githubusercontent.com/90187801/183473980-8cb6bf4d-c98f-450a-85cc-d33362ded24f.mp4

2. Then make some changes
3. Close and save score
4. Reopen score - **it makes the score corrupted and unreadable**

**Platform information**
Windows10

**Comment by DmitryArefiev** [comment]
This is more critical then I though... If to open score from Explorer, make some changes and then reopen score - **the score becomes corrupted without chance to open**

https://user-images.githubusercontent.com/90187801/184178027-7bc459e0-3cda-4927-a842-38455a84f8ad.mp4




(will edit the summary)

**Comment by Skelbti** [comment]
Same thing happened for me...

**Comment by DmitryArefiev** [comment]
Fixed in #12923

**Comment by DmitryArefiev** [comment]
> Same thing happened for me...

@Skelbti This is fixed now in master. But you should use MuseScore Installer and not regular unpacked builds when open scores from explorer.

You can use this build - https://github.com/musescore/MuseScore/actions/runs/2912758835 , it's installer.
(better to uninstall Alpha2 build before)

Thanks!
