### ISSUE TITLE
[MU4 Issue] Volume of instrument tracks is attenuated 

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12731]
**Describe the bug**
This can be noticed when comparing used self-sounding plugin on instrument track or on master track

**To Reproduce**
1. Install any self-sounding VST audio plugin (e.g. Izotope Vinyl or WavesFactory Cassette Transport)
2. Create a simple score
3. Assign the plugin to instrument track and then to the master track
4. Compare volumes of the same plugin

**Expected behavior**
Volume of instrument tracks is not attenuated 

**Screenshots**

https://user-images.githubusercontent.com/101250347/183513275-d8e1ad22-9aba-4bff-acaa-961d0b79f50d.mov

**Comment by boryskuzmenko** [comment]
@Tantacrul Yes, in both cases (plug-in on instrument and on master) volume of the plug-in should be the same. 
If this issue fixed our global issue with low volume in MU4 also will be fixed or at least partly fixed.

**Comment by Tantacrul** [comment]
It's worth mentioning that we've saved any issues to do with mixing & overall levels until the Muse Sounds plugin is ready. That way, we can balance them all together at once.

This may or may not be useful information to fix this bug.

**Comment by boryskuzmenko** [comment]
BTW I used MU3 volume as a reference in this case
