### ISSUE TITLE
[MU4 Issue] Drumset contains duplicate sounds/instruments

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#12734]
**Describe the bug**
In the Edit Drumset dialog, there are duplicate sounds listed. Some are removed from the list when you click on them and introduce another sound duplicate, others are just removed, and some even generate a full list with many duplicates.
Check the attached gif to see.

Also note the value of the Name field when some of the sounds are selected. It shows "Enter a name to enable pitch editing"

**To Reproduce**
1. Start a New Score
2. Add the drumset to the score
3. Start Note Entry
4. Click the Edit Drumset button

**Expected behavior**
I believe the list should not have duplicate items.

**Screenshots**
![EditDrumset](https://user-images.githubusercontent.com/13550012/183577665-03d0260d-2c6e-4fa7-a0e7-579bf346353b.gif)

**Platform information**
 - OS: Windows 10, using the Nightly build created 9th of Augsut.

**Additional context**
I made sure to reset all my preference and also did a factory reset before testing this. So believe this is not caused by a setting on my system.

**Comment by Tantacrul** [comment]
@henkdegroot - is this also the case with MS3?

**Comment by henkdegroot** [comment]
No not in MS3:
![image](https://user-images.githubusercontent.com/13550012/184673893-88553c5e-0662-4a16-b36c-f7c48f9fcd51.png)

Seems in MS3, I only see the "higher" pitch numbers. The low number do not have a sound connected.
This made me wonder if it could be related to having multiple VST instrument with drumsets, so checked on a sort of clean system and had the same result.

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2858462377, revision: github-musescore-musescore-93c9b73

Can't reproduce here:

![edit_drumset_ms4](https://user-images.githubusercontent.com/87246583/184676738-9a042112-9115-4191-ae78-1d5157501f9c.png)

**Comment by henkdegroot** [comment]
Just verified on using MuseScoreNightly-202208150453-master-93c9b73-x86_64.

No problem any more. So will close this issue, as it seems it has been resolved.
Issue was reported using the Alpha2 release.
