### ISSUE TITLE
[MU4 Issue] Backslash in paths (CLI) on Windows not working

### ISSUE THREAD

**Issue by geniot** [musescore/MuseScore#12745]
**Describe the bug**
Backslash in paths causes MuseScore 4 to ignore the command on Windows 10 (CLI).

**To Reproduce**
Using command line try to export a score on Windows:

The following is ignored silently (no file created):
`C:/Users/vital/CLionProjects/MuseScore/builds/Win-Qt5.15.2-msvc2019_64-VS16-Release/install/bin/MuseScore4.exe --trim-image 0 --force -o C:\Users\vital\AppData\Local\Temp\166004490466617445266007645084517\score_wide.svg C:\Users\vital\AppData\Local\Temp\166004490466617445266007645084517\score_wide.mscx`

The following works:
`C:/Users/vital/CLionProjects/MuseScore/builds/Win-Qt5.15.2-msvc2019_64-VS16-Release/install/bin/MuseScore4.exe --trim-image 0 --force -o C:/Users/vital/AppData/Local/Temp/166004490466617445266007645084517/score_wide.svg C:/Users/vital/AppData/Local/Temp/166004490466617445266007645084517/score_wide.mscx`

**Expected behavior**
Backslash in paths should work the same way as forward slash.

**Platform information**
 - OS: Windows 10.

**Additional context**
This is regression as compared to 3.6.2

**Comment by HemantAntony** [comment]
Let me guess, the backslash represents escape sequences

**Comment by Tantacrul** [comment]
@cbjeukendrup - when you have a moment can you comment on priority / severity?

**Comment by DmitryArefiev** [comment]
Should be fixed in #12923
