### ISSUE TITLE
[MU4 Issue] No audio tail at the end of score on exported mp3

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12747]
**Describe the bug**
Audio is just stopped right after the last note played. No tail with full note duration and reverb 

**To Reproduce**
1. Open the test score
2. Export it to mp3 (44100/320kbs)
3. Listen to the very end of the score

**Expected behavior**
Audio tail is present till any sound goes 

**Screenshots**
Listen to this exported file 
[The_Avengers_Theme_Song_full_orchestra.mp3.zip](https://github.com/musescore/MuseScore/files/9291352/The_Avengers_Theme_Song_full_orchestra.mp3.zip)

**Comment by DmitryArefiev** [comment]
Fixed in #13658
