### ISSUE TITLE
[MU4 Issue] New Shortcuts don't work

### ISSUE THREAD

**Issue by BenignPigeon** [musescore/MuseScore#12750]
**Describe the bug**
Upon changing the shortcut for the mixer from "F10" to "M" neither key is recognised

**To Reproduce**
To reproduce the behaviour change the mixer shortcut to a different key

**Expected behavior**
This new "M" key will act as a shortcut for the mixer

**Platform information**
I am on Windows 10 on the 2nd alpha of musescore 4

Please look at the attached video for more information 

https://user-images.githubusercontent.com/85837722/183755909-2f06dff4-df01-4ecc-a371-8d2bdb8694ef.mp4

**Comment by Tantacrul** [comment]
I'm getting the same issue on MacOS. When I follow these steps, I also notice that **Toggle Multibar Rest** is still showing as having **M** as its shortcut, even though it has been removed.

Annoying, since this _was_ working only a week or two ago.

**Comment by BenignPigeon** [comment]
Upon further inspection it seems as if the issue isn't with the newly assigned shortcuts, but rather with unassigning used shortcuts. For example M was already assigned to the toggle multibar rest function and didn't unassign automatically when I selected m for mixer even though there was a popup saying that it would be unassigned due to it's previous use.

Upon reassigning the redo button to ctrl+shift+z  it worked perfectly since ctrl+shift+z had no other purpose in musescore

Another instance of this bug occurring is reassigning the rehearsal marks shortcut to "ctrl r" as it's already in use as the shorcut for reset shapes and positions. Despite there being a popup (shown below) that shows that it should be deleted for it's previous function, Ctrl R is now in use for two different shortcuts so neither will work.

![image](https://user-images.githubusercontent.com/85837722/184863632-4ec8b68e-b251-4e0d-b39d-e02fa256386c.png)

**Comment by DmitryArefiev** [comment]
Fixed in #12890

**Comment by Tantacrul** [comment]
@RomanPudashkin - legend!

**Comment by Tantacrul** [comment]
@Eism - legend! Thanks for fixing this :)
