### ISSUE TITLE
[MU4 Issue] In imported MS3 scores, playback of chord symbols is heard even if NOT specified in Style properties (Play option in Style settings doesn't work to mute chords)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12755]
**Describe the bug**

In the attached MS file, chord symbol playback was turned OFF in the MS3 style settings, but is turned ON again when imported into MS4.

**To Reproduce**

Open and play back the attached MS3 file. 
[cream_in_my_coffee.zip](https://github.com/musescore/MuseScore/files/9298834/cream_in_my_coffee.zip)

RESULT: Although playback is unticked in Format > Style > Chord symbols, playback is clearly _heard_ in the score.

**Expected behavior**

Chord symbol playback settings should always be respected.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2829968415, revision: github-musescore-musescore-2d21253

**Comment by MarcSabatella** [comment]
Not just for imported score, and not just in the Style settings.  Even in scores created within MU4, chords always play, even if you turn off playback in the style settings, even if you turn off playback of individual chord symbols in the Properties panel, even if you try to mute the chord symbols channel in the mixer (the button never engages).  Only thing you can too is turn the volume down to minimum.

**Comment by DmitryArefiev** [comment]
@vpereverzev The **root issue here Play option in Style settings doesn't work to mute chords**. 
![Capture](https://user-images.githubusercontent.com/90187801/184646577-193483d8-2147-4c98-8f35-1ce825168628.PNG)



As I see, the Play option in Style settings in the attached score is unchecked so it should work after the main issue is fixed. But the initial scenario when porting MU3 score with unchecked Play option also should be rechecked after fix. 


@rgreen5 Thanks for logging!

**Comment by DmitryArefiev** [comment]
Other related issues to chords muting:

#12755
#12866
#12645
#12716

**Comment by DmitryArefiev** [comment]
**Play** option in Style settings is removed by design. Now user can mute chords in Mixer (and save that state for score).

Unfortunately now the muted state for chords in MS3 scores **can't be imported** to MU4.

(@Tantacrul please indicate if disagree with the last point and it requires a new task)

**Comment by Tantacrul** [comment]
This was the compromise we had to arrive at, so this is the desired behaviour for MS4.0.
