### ISSUE TITLE
[MU4 Issue] The new musescore basic playback system is not installed

### ISSUE THREAD

**Issue by BenignPigeon** [musescore/MuseScore#12760]
**Describe the bug**
The "musescore basic" playback system has not automatically been installed upon the installation of the second aplha release of musescore 4. Instead the old "musescore general" playback system still remains there but produces no audio sound upon moving over the notes.

**To Reproduce**
I'm not too sure how to reproduce this particular issue as all I did was install the new alpha release and the renamed playback system was not installed with it. To clarify, I'm not referring to the new and upcoming "Musesounds" playback system, rather the "basic" playback system that hasn't been installed.

**Expected behavior**
I expected the "musescore basic" playback option to be available so I could hear the music that I have composed.

**Platform information**
I am on the Windows 10 OS and on the 2nd alpha release of musescore 4

**Screenshots**

https://user-images.githubusercontent.com/85837722/183900844-32643c68-07ff-4cba-be85-0c798438ab3c.mp4

**Comment by cbjeukendrup** [comment]
This is a known bug for scores from earlier nightly builds and Alpha 1. New scores and pre-4.0 scores should use MS Basic by default. Since this issue only affects scores from unstable pre-release versions (which you should not use to do any valuable work), it is unlikely that this will be fixed.

**Comment by cbjeukendrup** [comment]
Maybe I should clarify this a bit: MuseScore_General was renamed to MS Basic. So in fact nothing is ‘new’ about it; MS Basic will be the default in MuseScore 4 but it is not the great new playback library. But existing MS4 scores that used MuseScore_General are not automatically updated to MS Basic, so MuseScore can’t find the SoundFont for those scores.

**Comment by BenignPigeon** [comment]
Yes, thanks for the clarification, upon manually copying and pasting it into the latest version with some tweaking, I have managed to get a sound to play using the MS Basic soundfont
