### ISSUE TITLE
[MU4 Issue] Weird playback after changing note

### ISSUE THREAD

**Issue by Nikos410** [musescore/MuseScore#12765]
**Describe the bug**
I'm sorry for the somewhat generic title, I'm not sure how to describe the problem concretely. Feel free to update the issue :)

If you open the [attached score](https://github.com/musescore/MuseScore/files/9302157/Score.zip) and change the second last note in the tuba voice to an F it sounds *weird*. And it keeps sounding weird after changing it back to an B.

**To Reproduce**
1. Open attached score
2. Play back the last 2 Bars -> Sounds fine
3. Change the second last note in the tuba voice to an F1
4. Play back the last 2 Bars again -> The changed note sounds weird
5. Change the last note back to an Bb1 -> Still sounds weird

**Expected behavior**
Normal Playback

**Screenshots**

https://user-images.githubusercontent.com/20876882/183964108-700f6fa2-dd87-4b47-8502-4f2c0e9fee5b.mp4

**Platform information**
 - OS: Windows
 - Version: Originally noticed in v4.0_alpha_2 / Still happens with 2022-08-31 nightly build

**Comment by DmitryArefiev** [comment]
@Nikos410 Yes, I also can reproduce the issue, looks like two notes sound instead of one. But after reopening the score it sounds fine




https://user-images.githubusercontent.com/90187801/184180581-cb350ae9-da1e-43bb-a1a6-64db153bd341.mp4


Thanks for logging!

**Comment by cbjeukendrup** [comment]
@Nikos410 @DmitryArefiev Is this still actual? When I try to reproduce this now, I hear nothing weird, so it seems like it's been fixed.

**Comment by Nikos410** [comment]
Hey, I just tried again and the issue seems to be fixed. Thanks for the great work @cbjeukendrup @DmitryArefiev (and everyone else) 👍
