### ISSUE TITLE
Allow MIDI echo when not in note input mode

### ISSUE THREAD

**Issue by blackears** [musescore/MuseScore#12766]
In MuseScore3, if the user is not in note input mode and they select a measure in the score and then press some keys on their MIDI keyboard, they will hear the notes played in the voice of the instrument used for that measure.  This can be useful for experimenting with different ideas before inputting them.  MuseScore4 does not retain this feature, and it would be nice to have it added back in.

**Comment by cbjeukendrup** [comment]
This seems a duplicate of #11234, but please correct me if I'm wrong.

**Comment by Lestrad** [comment]
In MS 3, as you say, the behavior is that at least two notes have to be selected for the instrument to be heard. If the insertion point is in a measure but nothing is selected, the voice of whatever instrument is in the top score is heard, and not that of the instrument in the current score. Several [threads](https://musescore.org/en/node/118726) have requested that the MIDI keyboard should play the voice of whatever score the insertion point is in, regardless of whether anything in that score is selected or not.
For those of us who have made that request, it looks as if MS 4 has made a double regression - "no steps forward, two steps back."

**Comment by cbjeukendrup** [comment]
@Lestrad If I understand correctly what you mean, this seems resolved in 4.6, but otherwise please open a new issue instead of commenting on a half-related closed issue, because that makes it very difficult to keep track of your comment.
