### ISSUE TITLE
[MU4 Issue] Build fail with `-DBUILD_JACK=ON`

### ISSUE THREAD

**Issue by hfiguiere** [musescore/MuseScore#12775]
**Describe the bug**
Build fail with -DBUILD_JACK=ON because the macro PKGCONFIG1 is unknown

**To Reproduce**
1. configre the build on Linux wtih `-DBUILD_JACK=ON`
2. build
3. Build fail because PKGCONFIG1 isn't known.

**Expected behavior**
Either it find jack or it doesn't.

**Screenshots**
n/a

**Platform information**
 - OS: Linux

**Additional context**

You need this patch:
```diff
diff --git a/build/cmake/FindJack.cmake b/build/cmake/FindJack.cmake
index 6713e3aeef..58cc8cee14 100644
--- a/build/cmake/FindJack.cmake
+++ b/build/cmake/FindJack.cmake
@@ -3,6 +3,7 @@
 ## Find JACK >= JACK_MIN_VERSION
 ##
 
+include(UsePkgConfig1)
 
 IF(BUILD_JACK)
      IF(MINGW OR MSVC)
```

**Comment by Tantacrul** [comment]
I'm moving Jack issues to 4.x, which is when we will begin to address them.

Closing until 4.0 is released, after which, I'll reopen.

**Comment by tibequadorian** [comment]
This is not a Jack issue and @hfiguiere already provides a patch. This should be fixed before the 4.x release.

**Comment by cbjeukendrup** [comment]
`-DBUILD_JACK=ON` does nothing, so you can just drop it.
