### ISSUE TITLE
[MU4 Issue] PNG Export dialog - Resolution - unable to enter more than 3 digits 

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#12772]
**Describe the bug**
It is not possible, to enter more than 3 digits in Export - PNG - Resolution dialog

**To Reproduce**
1. Open Score
2. Export - PNG
3. Try to enter new resolution higher, than "999"

**Expected behavior**
Any "allowed" resolution should be enterable

**Screenshots**

https://user-images.githubusercontent.com/1646034/184036158-b7b21a6a-7727-40ec-b572-b01402399a40.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
- Higher resolution is possible to achieve by hitting UP arrow.
- In MU3, it worked well.

**Comment by Tantacrul** [comment]
@sammik - what is the use case for having the DPI so high? You've mentioned it worked well on MS3. I'm curious? It'll help me prioritise this.

**Comment by sammik** [comment]
> @sammik - what is the use case for having the DPI so high? You've mentioned it worked well on MS3. I'm curious? It'll help me prioritise this.

@Tantacrul In fact nothing. I just found it, when testing different bug (and checked MU3 as standard issue report routine).
I would say, it cannot affect any real world work, so priority is not real question :)

**Comment by octopols** [comment]
I would like to work on this issue, can someone assign it to me?

**Comment by octopols** [comment]
`intinputvalidator.cpp` acts as a input validator for the text field holding the dpi value, the regular expression it accepts have a minimum length of `1` and maximum length of `3`. 
If it does not affect any other text field in a bad way I can change the regular expression such that it accepts values of max length 4.

**Comment by Jojo-Schmitz** [comment]
Same issue in Mu3, but entirely different cause apparently
