### ISSUE TITLE
[MU4 Issue] chord symbol always plays as piano, even in solo guitar score

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12771]
**Describe the bug**
Chord symbol playback always plays as piano, even for guitar scores, no way to alter this (other than specify a different soundfont entirely)

**To Reproduce**
1. Create score using solo guitar template
2. Add a chord symbol
3. Press Play

**Result**
Chord symbol plays with piano sound

**Expected behavior**
Chord symbol should play with with guitar sound by default, or else a way to make it play that way should be provided

**Platform information**
 - OS: Linux

**Additional context**
There was some debate over what the actual defaults should be when chord symbol playback was first implemented for 3.5.  At first, it used the sound of the current instrument, but this sounded really bad and unexpected when writing a lead sheet with voice or saxophone as the instrument.  So we made it piano always by default, but guitarists complained it should be guitar if the score is guitar.  We decided to handle that special case by hard coding it into the solo guitar template.  Not necessarily ideal, but there haven't been many complaints.  A better solution might have been to add a tag to the instrument definition itself to specify whether it should provide its own chord symbol sound (or to specify a different default).

In any case, having the ability to specify the sound in the mixer would of course provide a workaround in any case where the default wasn't what you wanted.  But failing that, at least implementing the solo guitar template hack would probably be appreciated by most guitarists.  Assuming that method could even still work - it seems the chord symbol channel is no longer per-instrument.

**Comment by Tantacrul** [comment]
Hmm. I'll chuck this in Beta2 for now. In all honestly, it might be one of those issues we need to tackle post 4.0 release. We have it logged anyway.

**Comment by DmitryArefiev** [comment]
Fixed in #13228

**Comment by Tantacrul** [comment]
Yes. This is working in the nightlies now.
