### ISSUE TITLE
[MU4 Issue] Mixer Button is not highlighted when mixer is open

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#12779]
**Describe the bug**
When mixer is open, mixer button is not highlighted

**To Reproduce**
1. Open Mixer (click Mixer Button, or press F10)
2. Mixer Button is not highlighted

**Expected behavior**
I expect, button is highlighted, if Mixer is open (like Metronom button is highlighted, when is active)

**Screenshots**

https://user-images.githubusercontent.com/1646034/184070263-2139dfe0-b864-490a-9d98-492f9ad0f353.mp4

**Platform information**
 - OS: [reported on Linux]

**Comment by Tantacrul** [comment]
I'm unsure about this. It may be a good idea. I just don't know if it would be annoying for it to always be blue when the mixer is open. I feel we should explore this in a revised design after 4.0 is released.

Moving to 4.X for now. We'll reopen once MS4.0 is released.
