### ISSUE TITLE
[MU4 Issue] View - Show checkmarks are wrong in Parts tabs 

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#12777]
**Describe the bug**
If check, or uncheck some Wiew - Show options in Parts, checkmarks always represent Score setting.

**To Reproduce**
1. Create Parts
2. On Score tab set View - Show - Show page margins
3. Go to Part Tab
4. Margins are invisible, but View - Show - Show page margins is Checked

**Expected behavior**
In Parts tabs, View - Show checkmarks should represent Parts settings

**Screenshots**

https://user-images.githubusercontent.com/1646034/184068665-eef9adcc-46c3-4914-a041-c48b09261edb.mp4

**Platform information**
 - OS: [reported on  Linux]

**Additional context**
Setting itself is toggled correctly, only checkmarks are problem.

**Comment by sammik** [comment]
Swiches in Properties Tab behaves differently.

In fact, they doesnt respect actual score / part status at all. They simply toggles themself, and active tab (score or part).


https://user-images.githubusercontent.com/1646034/184230740-298e139c-e58b-4e33-8b00-d38c5e823893.mp4

**Comment by Tantacrul** [comment]
Hmm. Just tested and realised this is quite a serious problem. Users **need** to be able to toggle ON/OFF invisible items on part scores.

The inspector should update to reflect what is and isn't visible on each score.

**Comment by Tantacrul** [comment]
Thanks @sammik !

**Comment by DmitryArefiev** [comment]
Fixed in #13116

**Comment by DmitryArefiev** [comment]
Inspector issues are not fixed in #13116. 
Logged as #12480
