### ISSUE TITLE
[MU4 Issue] Notes are very short on input and keyboard navigation

### ISSUE THREAD

**Issue by la-bel** [musescore/MuseScore#12783]
**Describe the bug**
When you input a note, it plays back a very short note.

**To Reproduce**
1. Create a score
2. Enter a note
3. The input playback is short and staccato

Alternatively:
1. Create a score
2. Enter several notes
3. Navigate between them using the left and right keys, or change pitch with the up and down keys, or select a note by clicking
4. The note playback is short and staccato

**Expected behavior**
As in MuseScore 3: the note to play the written length as long as the mouse is held down during mouse input, e.g. 

**Platform information**
 - OS: macOS

**Additional context**
Every note being played staccato during input or navigation is worse than previous behaviour and makes it harder for me to write or transcribe melodies in particular.

**Comment by MarcSabatella** [comment]
Note that this was an issue up until a week or so ago then was fixed i the nightly builds, but this seems to have been somehow reverted in the alpha.

**Comment by cbjeukendrup** [comment]
Let's close this since the original issue #12273 has been reopened. Thanks for reporting!
