### ISSUE TITLE
[MU4 Issue] Drumset palette layout is broken after opening/closing Mixer 

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#12789]
**To Reproduce**
1. Create a score from Battery Percussion template
2. Activate note input ('N')
3. Open mixer
4. Close mixer

**Expected behavior**
Drumset palette layout is not changed after opening/closing Mixer 

**Screenshots**

https://user-images.githubusercontent.com/101250347/184123008-5355e9e2-68a3-43ba-b134-16dae98e412f.mov

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**
The issue more noticeable on Windows

**Comment by DmitryArefiev** [comment]
Fixed in #12937
