### ISSUE TITLE
[MU4 Issue] Beams beginning with a rest are not displayed

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#12785]
**Describe the bug**
Beams beginning with a rest are not displayed

**To Reproduce**
1. Enter notes
2. Change beam property of rest
3. See error
4. Save and reopen the score
5. See another error

See video:

https://user-images.githubusercontent.com/102702868/184100926-727c6a81-60e3-4a98-acef-83b49a320107.mp4

**Expected behavior**
Beams are displayed as in MU3: 
![スクリーンショット (38)](https://user-images.githubusercontent.com/102702868/184100375-9c5f9c5f-5a51-4aae-ab9d-e97ffc3beeb7.png)

**Platform information**
 - OS: Windows 11

**Additional context**
Checked with Public Alpha

**Comment by oktophonie** [comment]
Thanks for the report; you'll be pleased to know we're actually already working on a fix for this at the moment (keep an eye out for a PR this week)!
