### ISSUE TITLE
[MU4 Issue] Maximized windows do not appear full screen on some display scales

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#12786]
**Describe the bug**
Maximized windows do not appear full screen on some display scales.

**To Reproduce**
1. Set to a specific display scale (175% or 225% in my environment)
2. Open MuseScore and maximize window
3. See gaps around the window

**Expected behavior**
There should not be gaps around the window.

**Screenshots**
Display scale: 175%
![スクリーンショット (39)](https://user-images.githubusercontent.com/102702868/184104032-8db0932a-f900-401e-88a5-9fcf8c9786ed.png)

**Platform information**
 - OS: Windows 11

**Additional context**
My display resolution is 2880x1920.
Checked with Public Alpha

**Comment by cbjeukendrup** [comment]
Came up again in #15201

**Comment by DmitryArefiev** [comment]
Should be in fixed in #15151

@bakajikara Please recheck on your side (and reopen if still happens)

Thanks!

**Comment by DmitryArefiev** [comment]
Retested on Win10 with 4.0.2 RC build - **Doesn't occur**
