### ISSUE TITLE
[MU4 Issue] MS4 crashes Cinnamon desktop (Linux Mint)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12797]
**Describe the bug**

This happened was reported before (see #12038) but can now be reproduced. The cue in this case is to try to close a tab when the Properties > Appearance panel is open.

**To Reproduce**

1. Open the attached file. 
[slides_in_out.zip](https://github.com/musescore/MuseScore/files/9309327/slides_in_out.zip)
2. Click on a slide in and ensure that the Properties > Appearance panel is open.
3. Now click on the close tab icon (cross)
RESULT: Cinnamon desktop crashes. A window will eventually appear allowing you to restart the desktop.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2826032396, revision: github-musescore-musescore-2d21253

**Comment by DmitryArefiev** [comment]
Can reproduce it on my LinuxMint20.2 as well


![Uploading IMG_20220811_200449.jpg…]()


Thanks for logging!

**Comment by rgreen5** [comment]
There seem to be numerous ways to crash the desktop. Another way:

1. Create a new file with just a treble staff in C major.
2. Enter a few notes in measure 1.
3. Click on a notehead, then select "Appearance".
4. Select "Color".
RESULT: The program freezes; shortly after the desktop crashes.

**Comment by DmitryArefiev** [comment]
Fixed in #12797

**Comment by DmitryArefiev** [comment]
@rgreen5 Can you check please on your side as well?  It looks fine on my Linux now.

Thanks!

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2931312884, revision: github-musescore-musescore-c4515b8

No problems here either.

**Comment by DmitryArefiev** [comment]
Thanks for checking!
