### ISSUE TITLE
[MU4 Issue] Different font size and placement are applied for drumset shortcuts on different OS

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#12792]
**Describe the bug**
macOS
![Capture 2022-08-11_02-29-43_PM](https://user-images.githubusercontent.com/101250347/184125522-049680eb-5907-45dd-ac8e-9f9248994ec0.png)

Windows
![Snag_176e5a](https://user-images.githubusercontent.com/101250347/184125718-d2d53091-b1b8-4642-b28b-997ff6bdc6c7.png)

Linux
![Screenshot from 2022-08-11 14-36-43](https://user-images.githubusercontent.com/101250347/184125742-a403a80b-a4b3-4e88-a47b-2530e21262d4.png)

**Expected behavior**
Same font size is applied for drumset shortcuts on different OS

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Comment by Tantacrul** [comment]
That one on Windows is quite bad, so I upped it to a P2.

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** 
Tested on macOS 12, Win 11, Ubuntu 20
