### ISSUE TITLE
[MU4 Issue] Laissez vibrer signs play loud

### ISSUE THREAD

**Issue by la-bel** [musescore/MuseScore#12793]
**Describe the bug**
Laissez vibrer signs appear centred under a note or chord, with a single sign appearing for a chord. In the playback, they (correctly) linger but (incorrectly) play much louder than surrounding notes.

**To Reproduce**
1. Create a score
2. Enter chords
3. Mark one with the laissez vibrer articulation
4. First issue: The articulation appears incorrectly
5. Play back
6. Second isssue: the chord plays back as if played sforzando

**Expected behavior**
Laissez vibrer signs to appear like ties to nowhere on every note in the chord. The playback should be at general dynamic level.

**Screenshots**
<img width="546" alt="Screenshot 2022-08-11 at 12 40 42" src="https://user-images.githubusercontent.com/63920211/184125532-52545250-4e55-4ed2-8f19-2aa89b8bb815.png">

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Comment by oktophonie** [comment]
A proper overhaul of the placement/appearance of l.v. ties is certainly high on the wishlist but will happen in a 4.x release, unfortunately; for now I'm afraid they will need to be offset manually. (Playback is not my domain, but I'm certain that side of this issue will be addressed for 4.0.)

**Comment by la-bel** [comment]
Fixed at or before «major new build» linked on Discord
