### ISSUE TITLE
[MU4 Issue] No screen reader feedback for GettIng Started wizard

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12808]
**Describe the bug**
The very first windows a user encounters when first starting MuseScore 4 do not read their contents.

**To Reproduce**
1. Start screen reader (tested with NVDA & Narrator)
2. Start MuseScore for the first time (or after factory reset)

Result:
The getting started dialog does not read anything in particular.  You can press tab to hear labels of buttons, but you have no idea what is happening, because none of the rest of the text is read.  Same for the next screen where you find a download button but have no idea what is being offered for download, etc.

**Expected behavior**
Dialogs should read their contents, either in full upon opening, or at least when a user presses the appropriate shortcut key for their particular screen reader (eg, Narrator+W).

**Platform information**
 - OS: Windows

**Comment by Tantacrul** [comment]
@shoogle, I'll let you be the point of contact for desired behaviour here.

**Comment by DmitryArefiev** [comment]
Fixed in #13443
