### ISSUE TITLE
[MU4 Issue] Side Panels Width gets extremely wide when closing them, opening them again and then opening the Mixer

### ISSUE THREAD

**Issue by KaiVinter** [musescore/MuseScore#12806]
**Describe the bug**
Pretty self explanatory.

**Requisites**
You need to have the Mixer closed and the side panels open by default when opening the score, otherwise this doesn't seem to happen.

**To Reproduce**
1. Prepare MS4 with the requisites above
2. Open a score
3. Open Mixer (nothing happens, it's just so you can see when it doesn't happen)
4. Close Mixer
5. Close all the Side Panels (Palettes, Properties and Instruments)
6. Reopen the Side Panels
7. Open Mixer again.
8. See error

**Expected behavior**
Side panels should not get any wider when opening the Mixer.

**Videos**

With the requisites:

https://user-images.githubusercontent.com/88064903/184242886-095a80e2-e0a6-4d8f-822a-56badefdf567.mp4

Without the requisites (no bug):

https://user-images.githubusercontent.com/88064903/184242997-56203693-5df8-4fb9-ba79-9166f0229bc6.mp4

**Platform information**
Tested on MacOS Mojave 10.14.6
Tested on MS4 Alpha 2

**Additional context**
There's usually a crash after closing MS4 with the score open, I'm not sure if it's always or only after reproducing this bug.

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2844416344, revision: github-musescore-musescore-ae252cd

Same issue in Linux.

**Comment by DmitryArefiev** [comment]
Fixed in #12937
