### ISSUE TITLE
[MU4 Issue] Musescore 4 starts with a white screen with large transparent field in the middle

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#12814]
**Describe the bug**
Musescore 4 starts with a white screen with large transparent field in the middle

**To Reproduce**
1. Start the Musescore 4 Alpha 2
2. See video below

**Expected behavior**
No white screen. Just the Musescore UI.

**Screenshots**

https://user-images.githubusercontent.com/63284090/184312908-900a07b0-7499-41ed-b75a-966609ac9b4e.mp4

**Platform information**
 - OS: Windows 11

**Comment by jeetee** [comment]
I see the same happening with a recent nightly (29/8)
What seems to happen is that the main window background is being drawn unpainted (white), but "smart" window repainting doesn't repaint the area where the splash screen was (that hides at the same time). Thus leaving a brief "transparent" window effect.

**Comment by Tantacrul** [comment]
Both @jeetee and @Jojo-Schmitz are getting this too, so I think we need to address it in beta.

**Comment by Eism** [comment]
@mattblo @jeetee @Jojo-Schmitz 
Please check the build from this PR https://github.com/musescore/MuseScore/pull/12595
Casper reimplemented the splash screen. Maybe the problem is no longer relevant.

**Comment by Jojo-Schmitz** [comment]
I don't see a difference. But I don't see that effect anymore either

**Comment by jeetee** [comment]
Issue still present on the artefact of that PR:
![MS4-launch-repaint-onPR](https://user-images.githubusercontent.com/895153/187858901-2e6265df-ed28-4c57-b590-f9f0489c656f.gif)

**Comment by cbjeukendrup** [comment]
FWIW, I think it doesn't have to do with the splash screen; for me, this issue has existed already before the splash screen was there. But anyway, we might try what happens when disabling it altogether.

**Comment by BenignPigeon** [comment]
I also seem to be getting this issue too. FYI im on the alpha version and on windows 11

https://user-images.githubusercontent.com/85837722/187985593-9f878754-1c36-4183-bcb3-0c640cad13e9.mp4
