### ISSUE TITLE
[MU4 Issue] Placing grace notes in different voices on the same beat creates an extremely wide measure

### ISSUE THREAD

**Issue by Der-Leiermann** [musescore/MuseScore#12812]
**To Reproduce**
(See enclosed videos)
1. Open new score
2. Place note in voice 1
3. Place note on the same beat in voice 2
4. Add a grace note before each note

OR

1. Open new score
2. In voice 1 place a rest and then a note
3. In voice 2 place a note of the same duration as the rest in voice 1
4. Add a grace note before the note in voice 1 and after the note in voice 2

**Expected behavior**
The spacing adjustments should be less drastic.

**Screenshots**

https://user-images.githubusercontent.com/110511209/184272609-5a6b194f-09cf-4632-b1e4-fb147eff27ed.mov

https://user-images.githubusercontent.com/110511209/184272624-d05a64df-02fa-45a5-b496-15c1955d2194.mov

**Platform information**
 - OS: macOS Monterey 12.5

**Comment by MarcSabatella** [comment]
Confirmed, pretty crazy really - it's *not* subtle :-)
