### ISSUE TITLE
[MU4 Issue] Unable to rename User Text Style

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#12810]
**Describe the bug**
User styles have editable names, but any change is lost.

**To Reproduce**
1. Open Format - Style - Text Styles
2. Find "User-1" style
3. Change its name
4. Hit OK (or select another Text Style)
5. Check edited style - changes are lost

**Expected behavior**
Changed names remain changed (and saved)

**Screenshots**

https://user-images.githubusercontent.com/1646034/184247426-3835324c-02dc-42c8-9898-f44e1592de88.mp4

**Platform information**
 - OS: [reported on Linux]

**Comment by RobFog** [comment]
Should this issue be moved to the MuseScore 4.1 milestone to indicate it will be part of that version?
