### ISSUE TITLE
[MU4 Issue] Crash when closing a score after disabling/enabling mixer several times

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#12815]
**Describe the bug**
Musescore 4 crashes when the score is closed, both with and without saving. Before that, I think the mixer has to be enabled and disabled several times. At least that's how I was able to reproduce it.

**To Reproduce**
1. Open one of those score for example
[test scores.zip](https://github.com/musescore/MuseScore/files/9314987/test.scores.zip)
2. See the video

**Expected behavior**
No crash!

**Screenshots**

https://user-images.githubusercontent.com/63284090/184318881-bbfdec45-8496-4e40-88aa-eb81d3ad0228.mp4

**Platform information**
 - OS: Windows 11
 
 **Additional information**
 - Musescore 4 has already been reset to factory settings before the video

**Comment by Tantacrul** [comment]
Making a P1 because I'm worried it may lead to occasional crashes when someone opens / closes the mixer only once.
