### ISSUE TITLE
[MU4 Issue] Default page size is A4 instead of Letter in North America

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12829]
**Describe the bug**
In North America, the standard paper size is Letter, and this should be the default page size in MuseScore.  But in MuseScore 4, it is A4, even in North America.

**To Reproduce**
1. Live in North America :-)
2. Create a new score, using either Choose instruments or Create from template
3. Go to Format / Page Settings

**Result**
Score is A4

**Expected behavior**
Score should be Letter

**Platform information**
 - OS: Windows

**Additional context**
In MU3, we used a bad hack to determine the default page size: we queried the default printer to find its default paper size.  This worked most of the time, but failed always on Linux, and occasionally on macOS and on Windows, particularly if your default printer was not accessible (e.g., turned off) or if the default printer was a virtual printer like a "print to PDF" utility.  With MU4, I'm not sure if the same hack is being attempted, but bottom line, it isn't working for me in North America even though my default (virtual) printer is set up with Letter as the default papr size.

Using the default printer to determine default page size is, as I suggested, a bad hack.  But for various reasons, no one could seem to agree on the better way that would work reliably across platforms.  Hopefully for MuseScore 4 we can do better!

**Comment by MarcSabatella** [comment]
@Tantacrul - I forgot about this one, but this will be an enormous headache for American users.

**Comment by Tantacrul** [comment]
Marc. Any chance you can submit a PR for this - or cajole a community member? It would help us focus on the trickier issues.

**Comment by MarcSabatella** [comment]
Unfortunately, I don't know what the best solution would be - no one could agree on it back in the day.

But I'll try to drum up a consensus and see what I can do.  No doubt, it's a very simple fix no matter what strategy is chosen.

**Comment by MarcSabatella** [comment]
My current PR https://github.com/musescore/MuseScore/pull/14457 is, I think, the best I personally can do for now.  It doesn't solve the problem for the user automaticall, but it at least makes sure the workarounds that have always existed (since this didn't always work reliably in MU3 either) continue to work in MU4.  So it's way better than nothing.

The main thing it does is fix https://github.com/musescore/MuseScore/issues/12828, so that the feature of specifying custom MSS files for score and parts in Edit / Preferences / Score actually works.  Right now, it's broken - user-specified page size settings are ignored when creating scores from templates (the parts style file is ignored completely in all cases).  We want the template page size to win if they aren't just defaults (so an orchestra template can set extra-large paper), but not our templates that simply use the generic default.  So, that's what my PR does.

My PR also provides a start on providing a better way of overriding the default page size - one that doesn't depend on custom MSS files.  I put code in place to establish a default page size separate from the MSS files and to use this where appropriate.  I just don't have a UI to actually let the user set the default.  I think it *should* be a setting in Edit / Preferences / Score, but I wouldn't be a good choice to implement that, and in any event, that's a UI change we might not want for 4.0.  If Edit / Preferences / Advanced is more acceptable for changes, that could be OK too, but again, someone who knows that code better would need to implement it.

Even so, this is all just giving us the *option* to override the A4 default, not anything about automatically detecting that you probably want Letter as the default.  I still have no good insight into how to do that, and in particular I would not be in favor of reimplementing the MU3 hack of checking the default print's default paper size.  I think the right solution is to add a couple of radio buttons (or a dropdown) in the startup wizard to ask the user which size they prefer, and then hook this up to a preference setting you can change later - same as we do for color scheme.  Again, though that would require UI change and I'm not in a position to implement that even if if it were to be approved.

**Comment by Jojo-Schmitz** [comment]
Would making it locale dependant work? (en_US || *_CA) -> Letter, else A4?

**Comment by MarcSabatella** [comment]
> Would making it locale dependant work? (en_US || *_CA) -> Letter, else A4?

From what I understand, there is no reliable cross-platform way to check this.  I'd love to be wrong...
