### ISSUE TITLE
[MU4 Issue] Home > Plugins: Selected plugin is not mutually exclusive between "Enabled" and "Disabled" sections

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12826]
**Describe the bug**
In Home > Plugins, two plugins can be "selected" at the same time: one in the "Enabled" section, and one in the "Disabled" section.

**To Reproduce**
1. Go to Home > Plugins
2. (Make sure some plugins are enabled and others are disabled, so you have both sections)
3. Select a plugin in the "Enabled" section
4. Select a plugin in the "Disabled" section
Note that the plugin in the "Enabled" section erroneously stays selected.

**Expected behavior**
A maximum of one plugin should be selected at the same time, in both sections together.

**Screenshots**

https://user-images.githubusercontent.com/48658420/184369163-59672210-ea86-4326-bed1-fbe268ed5bcb.mov

**Additional context**
It is mainly a visual/UI problem; functionality seems okay.

**Comment by DmitryArefiev** [comment]
Fixed in #12854
