### ISSUE TITLE
[MU4 Issue] Fingering by default is too close to left barlines

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12825]
**Describe the bug**

The default distance from the left barline to fingering symbols is too small. This obviously affects LH Guitar Fingering 1 but may apply to other fingering symbols as well.

**To Reproduce**

1. Open the attached file named "barline_to_note_ms4". 
[fingering_files.zip](https://github.com/musescore/MuseScore/files/9316595/fingering_files.zip)
2. Observe the position of the fingering symbols in relation to the left barlines.
RESULT: The default distance is too small.
3. Open the MS3 file "barline_to_note_ms3" in both MS3 and MS4
RESULT: The barline to fingering distace is again too small for LH Guitar Fingering 1 (compared to MS3).

**Expected behavior**

A reasonable default distance should be maintained between left barlines and any fingering symbols.

**Screenshots**
MS4:
![fingering](https://user-images.githubusercontent.com/87246583/184363234-083de7e9-47f0-481d-a945-84c80436dc6c.png)

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2844416344, revision: github-musescore-musescore-ae252cd

**Comment by oktophonie** [comment]
Nice catch; looks like these used to be considered for justification before but we've forgotten about them in the redesigned spacing system.
