### ISSUE TITLE
[MU4 Issue] - Chord playback

### ISSUE THREAD

**Issue by drbirkenstocks** [musescore/MuseScore#12837]
**Describe the bug**
Toggling chord playback on/off does not affect playback; it currently plays regardless

**To Reproduce**
1. Play a selection with chord symbols
2. Toggle on/off chord playback
3. Chords play regardless

**Expected behavior**
Toggling chord playback on/off will work as expected

**Platform information**
 - Windows 11

**Comment by MarcSabatella** [comment]
Indeed, see https://github.com/musescore/MuseScore/issues/12755 - this is a known issue currently.  Meanwhile, the (partial) workaround is to pull the volume slider down for the chord symbol channel in the mixer.

**Comment by drbirkenstocks** [comment]
Ah ok, thank you! I'm just taking notes on things as I experience them and submitting.
