### ISSUE TITLE
[MU4 Issue] Accessibility navigation commands (Alt+Left/Right) do not set playback position

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12831]
**Describe the bug**
If you navigate through the score with Alt+Left an Alt+Right, then start playback, playback continues where it left off last time rather than starting at the location you selected.

**To Reproduce**
1. Load a score
2. Start playback
3. Pause it
4. Use Alt+Left/Right to navigate to a specific note in the score (other than where you paused playback)
5. Press Play

**Result**
Playback resume where it left off

**Expected behavior**
Playback should start at the selected note, same as if you had either clicked it or navigated there using Left/Right without Alt

**Screenshots**
https://youtu.be/q1uDP7wmY2o

**Platform information**
 - OS: Windows

**Additional context**
This is pretty critical, as Alt+Left/Right are a blind user's normal way of navigating a score, more so than Left/Right on their own.  That's because Alt+Left/Right navigate through all symbols, not just notes.  And while we sighted users can see based on the playback cursor that plaback is starting in the wrong place, this won't be apparent at all to blind users!

**Comment by DmitryArefiev** [comment]
Fixed in #12977
