### ISSUE TITLE
[MU4 Issue] Portamento playback does not work for voice

### ISSUE THREAD

**Issue by MaximilianoGG** [musescore/MuseScore#12838]
**Describe the bug**
The first note keeps playing (unless the same pitch was previously sounding)
No portamento playback.

**To Reproduce**
1. Insert two different and consecutive notes and add a glissando between them.
2. Click the glissando and go to Properties tab, then click Playback and then select Portamento as Style.
3. Play.
 
**Platform information**
 - OS: Xubuntu Linux 18.04.6

**Additional context**
MuseScore-4.0.0.2826032396-x86_64 version.

https://user-images.githubusercontent.com/7459884/184451438-076b4eaa-a35e-4041-89b0-a55eff29c748.mp4

**Comment by MarcSabatella** [comment]
I can confirm for "voice" instruments specifically.  Seems to work more as expected for winds and strings.

**Comment by MaximilianoGG** [comment]
Yes. That's right. At least for me too.

**Comment by MaximilianoGG** [comment]
(Sorry, I unintentionally closed it.) Yes, the same for me, only voices.

**Comment by MaximilianoGG** [comment]
I'm also experiencing no glissando playback at all (none of the styles) if the first note is tied, and not only for voices
![gliss](https://user-images.githubusercontent.com/7459884/184499788-6f0219ec-5176-4ddc-ae24-5a653bc3ebe0.png)

**Comment by DmitryArefiev** [comment]
Fixed in #16597 (together with #15268)
