### ISSUE TITLE
[MU4 Issue] Use of arrow keys on a score element has different and surprising results depending on whether the appearance tab is open.

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#12842]
**Describe the bug**

After selecting a score item if the Appearance tab is closed, the arrow keys will move the item.  If the Appearance tab is open, the arrow keys have different behaviour depending on the type of element which in turn determines the initial focus in the Appearance dialogue.

**To Reproduce**

1. Create a simple score like this

![Issue2](https://user-images.githubusercontent.com/60138048/184496813-2880b3e9-8656-4905-a2f4-c8c327038c3e.png)

Example 1. Select the staff text with Appearance tab closed.  Up/down/left/right arrow keys adjust the position of the text relative to the note it is attached to.  The note remains where it is.  The behaviour is similar to that of MS3 (albeit the movement steps are 0.5 sp in MS4 rather than 0.1 sp in MS3).

Now open the Appearance tab.  Note that focus is in the Leading Space field.  Left/right arrows have no effect.  Up/down arrows increase/decrease the note’s leading space so that the text moves left/right but the note it is attached to also moves.

https://user-images.githubusercontent.com/60138048/185966109-6644a121-5033-44aa-990e-fd995f1a888d.mp4

Example 2.  Select the slur with the Appearance tab closed.  Up/down/left/right arrow keys adjust the position of the slur.

Now open the Appearance tab.  Note that focus is in the Minimum Distance field.  None of the arrows affect the slur’s position.  However, up and down arrows adjust the Minimum Distance value.  Left and right arrows move the cursor in the Minimum Distance field.

Example 3.  Select the dynamic with the Appearance tab closed.  Up/down/left/right arrow keys adjust the position of the slur.  

Now open the Appearance tab.  It is not obvious where the focus is, but up arrow seems to move it to the Colour selector; down arrow or right arrow moves it to the Leading Space field; right arrow left arrow moves it to the Reset circular arrow above the Leading Space field.  Further presses of arrow keys move the focus until it reaches a value field and thereafter the value of that field is adjusted.  The exact results depend on which order the arrow keys are pressed

**Expected behavior**

Arrow keys should move the selected score item when the Appearance tab is opened unless the user has explicitly selected a field in the Appearance tab.

**Screenshots**

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, 
MuseScore version (64-bit): 4.0.0-2826033426, revision: github-musescore-musescore-abc123456

**Additional context**

I tried to create a video that demonstrates the problem but the contents of the Appearance tab were not captured (using OBS)

[Edit] and now I managed to capture the problem using Bandicam

**Comment by Tantacrul** [comment]
Hmm. This is where expectation collides with accessibility. As you can see by clicking on 'Appearance', the focus moves to leading space, which allows screen readers to begin describing what the first option is (in this case leading space). And since focus is moved to the spin box, the arrows are no longer editing the note itself.

I'm open to suggestions about best practice here. I think this is more of a future design question which we won't be able to address for 4.0. I'm legitimately unsure if it really should be changed at all, to be honest.

For now though, I'll move to 4.x and close until 4.0 is released. Then we'll reopen this issue.
