### ISSUE TITLE
[MU4 Issue] Use of arrow keys alone moves slur anchor point (but only to the right)

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#12843]
**Describe the bug**

Moving the leftmost handle of a slur sufficiently far to the right unexpectedly and unnecessarily changes the anchor point.  Moving the handle to the left does not change the anchor point.

**To Reproduce**

1. Select the leftmost handle of a slur that includes more than two notes and has unslurred notes to the left of it.  
2. Press right arrow several times.

Result: Eventually. the anchor point is moved to the next note to the right.

3. From the same starting point select the leftmost handle.
4. Press left arrow several  times.  

Result: The handle moves to the left but the anchor point never moves to another note.  There seems to be a one-way street for this operation. 

**Expected behavior**
As there is already a shortcut (SHIFT+LEFT/RIGHT arrow) to move the anchor point, the right arrow alone (i.e. without SHIFT) should only adjust the position of the slur endpoint, not move the anchor point.  This is the behaviour in MS3

**Screenshots**

**Platform information**

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2826033426, revision: github-musescore-musescore-abc123456

**Additional context**

**Comment by Tantacrul** [comment]
I've just tested this - and it seems the issue may have been subsequently fixed. Or at least, it now matches MuseScore 3. @SteveBlower, can you check?

**Comment by SteveBlower** [comment]
Yes, the behaviour is the same as MS3 - I should have checked that first.  And it is still present in the latest nightly (OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3212867789, revision: github-musescore-musescore-abc123456) 

But I would suggest it is not the desired behaviour.  Either the anchor point should always move with the handle or never move with the handle.  It should not move/not move depending on which direction the handle is moved.  My preference would be for it never to move.  Shift+Arrow already moves the anchor point.  No need for another way to do that and users may find some application that needs a slur endpoint to be moved so that its visual representation does not match its playback range of application (if slurs do in fact affect playback).  But I guess there are arguments that the visual representation and playback should match wherever possible.

**Comment by Tantacrul** [comment]
My own sense is that there is no value in the anchor point not moving regardless of whether you press the arrow or shift+arrow but that's a discussion for another day!

For now, since it seems to now behave like MS3, I'm going to move to 4.X.

Will reopen once 4.0 is released
