### ISSUE TITLE
[MU4 Issue] Lay-out of 1st / 2nd time endings broken in imported MS3 score

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12845]
**Describe the bug**

This issue seems to affect measures in 1st / 2nd time endings. In the imported MS3 score,  line breaks are being applied where not specified and some measures are elongated to the extent that they disappear off the right-hand edge of the page.

**To Reproduce**

* Open the attached score in MS3 and MS4 and compare the two. 
[elongated_measures.zip](https://github.com/musescore/MuseScore/files/9331756/elongated_measures.zip)

RESULT: Layout broken across 1st and 2nd time endings in MS4.

**Expected behavior**

Layout in MS4 should be the same as in MS3.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2850670314, revision: github-musescore-musescore-93c9b73

**Comment by oktophonie** [comment]
I think the 1st/2nd-time endings are actually a red herring here. The real issue appears to be caused by the grace notes in two voices (which happen to occur under the 1st-time bars in this score), as already reported in #12812.
