### ISSUE TITLE
[MU4 Issue] - printing is truncated on page 1

### ISSUE THREAD

**Issue by drbirkenstocks** [musescore/MuseScore#12847]
**Describe the bug**
When printing directly from MU4, page 1 is truncated; subsequent pages do not appear affected.

**To Reproduce**
1. From MU4, Ctrl(Cmd)+P to print
2. Print document
3. Page 1 is truncated

**Expected behavior**
Page 1 will print in its entirety as expected.

**Screenshots**
See below.

**Platform information**
 - Windows 11
![MU4 print](https://user-images.githubusercontent.com/111152765/184507296-3062d5ac-feb2-4eff-a192-817a0474eb76.jpeg)

**Comment by sammik** [comment]
May be related with #12773 (as output looks similar)

**Comment by DmitryArefiev** [comment]
**Can reproduce** on my side with **physical printer** and **Microsoft Print To PDF** (Windows10)

**Comment by oktophonie** [comment]
I have also encountered this (Win 11 + Artix Linux)

**Comment by DmitryArefiev** [comment]
Tested in **latest master** on Win10, Mac12 - **FIXED**
