### ISSUE TITLE
[MU4 Issue] Straight start hook option is missing in pedal properties

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#12849]
**Describe the bug**
You cannot set the starting hook of a pedal to straight using the properties panel.

**To Reproduce**
1. Add pedal line to score
2. Go to properties panel

**Screenshots**
![スクリーンショット (52)](https://user-images.githubusercontent.com/102702868/184521543-35613987-8217-44af-9e63-15e77f5068ce.png)

**Platform information**
 - OS: Windows 11

**Additional context**
The line type option only affects the end hook.

**Comment by Tantacrul** [comment]
@oktophonie - can you oversee this one with @jessjwilliamson ?

Obviously I'll jump in if needed but I think the design is self-explanatory. Lemme know if I'm wrong.

**Comment by jessjwilliamson** [comment]
Yo! Good news is the icon already exists in the font - Unicode EF9E. Should look something like this :) 

![image](https://user-images.githubusercontent.com/71656189/187430229-df411a1c-6b33-42f8-a187-8484cf21945f.png)
