### ISSUE TITLE
[MU4 Issue] Text formatting options are missing in properties of text lines

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#12848]
**Describe the bug**
Text formatting options are missing in the properties of text lines.
(and elements similar to text lines, like crescendos, tempo changes, and so on!)

**To Reproduce**
1. Add a text line to score
2. Go to properties panel

**Expected behavior**
These options should be available.
![text options](https://user-images.githubusercontent.com/102702868/184521019-b8dd1839-af5f-4b59-9c55-31146da19cd0.png)

**Screenshots**
There are no text formatting options available.
![スクリーンショット (51)](https://user-images.githubusercontent.com/102702868/184521101-96ac8602-cb60-4c86-9ef0-2351e87c4235.png)

**Platform information**
 - OS: Windows 11

**Additional context**

**Comment by DmitryArefiev** [comment]
The same as #13338. Closing to leave only one issue. 

Thanks for finding!
