### ISSUE TITLE
Arrow keys move the anchor point of dynamic but there is no indication to the user of the change

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#12844]
**Describe the bug**
Moving a dynamic by selecting it and using the arrow keys changes the note to which the dynamic is attached if it moved suffiently far.  However, there is no indication during or after the operation that this change has happened.

**To Reproduce**

1. Select a dynamic.
2. Move it slightly with the mouse
3. Note the anchor point.  
4. Press right arrow several times.  
5. The dynamic moves to the right.  
6. After the dynamic has moved past a few notes, move it again with the mouse.
7. Note that the anchor point has changed.  

**Expected behavior**

Either the anchor point should not change, or the connecting line to the anchor point or just the anchor point should be shown when the arrow key is invoked.

**Screenshots**

https://user-images.githubusercontent.com/60138048/185971613-a56c1a18-d934-431f-97b5-bbf523dabede.mp4

**Platform information**

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2826033426, revision: github-musescore-musescore-abc123456

**Additional context**

In MS3, moving the dynamic using the arrow keys does not change the anchor point, no matter how far the dynamic is moved.  Moving it by dragging **does** move the anchor point.  These two alternatives are useful allowing the user to either move the anchor point with the dynamic or not.

**Comment by Tantacrul** [comment]
Basically, when using the arrow keys to move an object, the 'pink connecting line' that shows what it is snapping to should be visible.

**Comment by wizofaus** [comment]
I have some familiarity with this code and made a number of changes around it some years back, so I'm happy to have a look, even if it's not a priority for 4.4.

**Comment by oktophonie** [comment]
@wizofaus No, thanks.

**Comment by wizofaus** [comment]
Then should you remove the community tag?
