### ISSUE TITLE
[MU4 Issue] Glissandi Playback doesn't work properly

### ISSUE THREAD

**Issue by Fristover** [musescore/MuseScore#12855]
**Describe the bug**
Glissandi take longer to arrive to the ending note when range is more than an octave.

**To Reproduce**
1. Add a glissando with a range bigger than an octave.
2. Hit play.
3. See (or listen to, actually...) error.

**Expected behavior**
Glissando takes the written time to play.

**Screenshots**
![Screenshot (1)](https://user-images.githubusercontent.com/68985619/184561714-269c287f-34ec-457f-9fb3-2d7e6294cde6.jpg)

**Platform information**
 - OS: Windows 11 22000.856

**Additional context**
Using the alpha from the forum announcement (might be fixed now? oops).

**Comment by Tantacrul** [comment]
This has improved a little. The first two examples are now fine. The third example (2 octaves) still takes too long.

This affects **Soundfont & VST** but doesn't affect **Muse Sounds**

**Comment by Fristover** [comment]
Not a thing anymore, Fixed.
