### ISSUE TITLE
[MU4 Issue] - crashes after adjusting leading space on multiple notes

### ISSUE THREAD

**Issue by drbirkenstocks** [musescore/MuseScore#12856]
**Describe the bug**
Adjusting the leading space on more than one note at a time (i.e., multiple notes selected) initiates crash.

**To Reproduce**
1. Select more than one note
2. Select Properties/Appearance, adjust leading space
3. Click anywhere else in the score after leading space is adjusted
4. Program crashes

**Expected behavior**
Leading space will be adjusted without initiating crash

**Platform information**
 - Windows 11

**Comment by DmitryArefiev** [comment]
I **can reproduce it**, but with one additional step (re-opening the Appearance popup)

https://user-images.githubusercontent.com/90187801/184680156-29a8f2b0-73ca-4567-8d77-e0776c448245.mp4

**Comment by boryskuzmenko** [comment]
Also reproducible on Mac and Linux

**Comment by DmitryArefiev** [comment]
Fixed in #12885
