### ISSUE TITLE
[MU4 Issue] Pedal playback not working for "pedal change"

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12869]
**Describe the bug**
The standard "pedal change" marking \_\_\_/\\\_\_\_ does not work; it lifts the pedal off but does not return it to the on position

**To Reproduce**
1. Piano score
2. Add four quarter notes C D E D to first measure and again to the second
3. Add a |___/ pedal marking from the first C to the second
4. Add a \\___| pedal marking from the second C to the end of the measure
5. Play

*Result**
Pedal lifts in bar 2 but does not re-engage

**Expected behavior**
Second measure should have pedal engaged just like the first

**Screenshots**
![image](https://user-images.githubusercontent.com/1799936/184670289-e552b221-9a5b-4f63-9f0c-1c33fdb3d5fc.png)

**Platform information**
 - OS: Linux

**Additional context**
The old-style Ped___* markings work fine because they don't overlap.  The issue seems to only occur on the pedal changes - the places where the end of one pedal coincides the the start of the next to create the characteristic pedal change \_\_\_/\\\_\_\_.  If I were to guess, I'd say the pedal off and on messages are simply being sent in the wrong order.

**Comment by MarcSabatella** [comment]
Bump - could this get prioritized?

**Comment by Tantacrul** [comment]
Yeah, I've been noticing this myself too.

**Comment by MarcSabatella** [comment]
FWIW, this is now the only significant issue remaining with "Reunion" - https://musescore.com/user/2975/scores/39069

**Comment by Tantacrul** [comment]
Just had a call with Vasily an hour ago, where we placed this issue in our top 3. Won't be much longer

**Comment by FireController1847** [comment]
I'm still having issues with pedal changes on this front, particularly when migrating from old versions of MuseScore. Notes are cut off early, general playback with MS Sounds is unreliable and unclean. Every once in a while a note goes max velocity as well. I can send example files but the songs are copyrighted so I'll have to email them or send them through other means.

**Comment by Ander3232** [comment]
Any progress with this? It seems like a pretty basic thing. And how do you include the "Ped." text symbol at the beginning of the extended line?

**Comment by MarcSabatella** [comment]
The issue reported here was fixed a year ago, which is why this issue is marked “closed”.  If you are having issues using a current version of MuseScore, that is probably something different.  Please open a new thread and ZIP and attach the score you are having trouble with and give precise steps to reproduce the problem.

To add text to a line, or change other line properties such as hooks, use the Properties panel.  See the existing Ped line to see the syntax for that special symbol.  If you have further questions about how to use MuseScore, please use the support forum on MuseScore.org
