### ISSUE TITLE
[MU4 Issue] If Add button tooltip appears, it removes selection when choosing multiple instruments (Add instruments window)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12862]
**To Reproduce**

https://user-images.githubusercontent.com/90187801/184619941-227c12ea-8ba7-4799-8c31-8cd5d6ca7675.mp4

**Platform information**
macOS, Windows, Linux

**Comment by Tantacrul** [comment]
Arg, Yeah, that's really stupid. I'd almost put this in Beta 1.

**Comment by cbjeukendrup** [comment]
I can't reproduce this anymore. @DmitryArefiev Could you please check if we can close this?
