### ISSUE TITLE
[MU4 Issue] 'Play' option in Inspector doesn't work for chords (to mute chords)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12866]
https://user-images.githubusercontent.com/90187801/184640311-e2986d0d-ff1b-432f-a010-ecb8ce000767.mp4

**Expected behavior**

**Workaround**
You can use Chord symbols channel in Mixer but it works for all chords in score together

**Platform information**
macOS, Windows, Linux

**All issues related to chords muting**
#12755
#12866
#12645
#12716

**Comment by oMrSmith** [comment]
The global mute setting "Play" under Style/Chord Symbols
also seems to be ineffective...

**Comment by DmitryArefiev** [comment]
Fixed in #12926
