### ISSUE TITLE
[MU4 Issue] Playback tempo is unsteady

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12870]
**Describe the bug**
The tempo does not always remain constant, often sounding like a beginner trying to keep a steady tempo but just not quite pulling it off

**To Reproduce**
1. Load [this score](https://musescore.com/user/2975/scores/39069)
2. Play

**Result**
It's just not even.  The eighth notes are not all the same length.  Almost but not quite like some sort of reverse swing is being applied - short-long, short-long, etc - but it's not consistently that either.  It's just erratic.

**Expected behavior**
Playback should keep at least a steady tempo as I can :-)

**Platform information**
 - OS: Linux, Windows

**Additional context**
This doesn't happen for *all* scores - at least, not to such a noticeable extent.  But it's not just this one either.  BTW, that particular copy of the score was created in 2.3.2, but I get the same result if I re-enter the first few measure directly into MU4.

**Comment by RazerMoon** [comment]
I'm also getting this exact issue, very annoying 😅

**Comment by MarcSabatella** [comment]
Is anyone looking at this?  It's pretty bad, and even once new sounds are in place, it's going to be an embarrassment if people's first exposure to them is with scores that won't play with a steady tempo.

**Comment by MarcSabatella** [comment]
@Tantacrul - this is the issue I mentioned on Discord

**Comment by MarcSabatella** [comment]
FWIW, in case anyone is having trouble reproducing (for me it's 100% reproducible with this score on Linux and Windows), here is a video demonstration:

https://watch.screencastify.com/v/CbkUzqPU6wB85an3MCQn

**Comment by Tantacrul** [comment]
@MarcSabatella - we have a few bugs like this now. There's one where you provided a visual comparison using Audacity and also @bkunda's 'Uneveness' issue mentioned above. Am I good to close this as an issue that is reproduced elsewhere? If not, I'll reopen.

Also - is the issue any better?

**Comment by MarcSabatella** [comment]
Yes, it's fine to have closed this; I'm sure any of the reports are the same basic issue.

It's hard to say if it's better or not.  Certainly not completely fixed.  I *think* maybe it seems slightly better if I turn up the buffer size.  But it's just prominent enough for me to be pretty sure it's not my imagination, but just subtle enough for there to be that little bit of doubt.

**Comment by Obliquely** [comment]
Just checked with most recent build and I'd say definitely quite a lot better than it was. Checking the two scores from my earlier comment, they are now listenable, whereas before they just weren't.
