### ISSUE TITLE
[MU4 Issue] Keyboard selection disabled after note input

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12894]
**Describe the bug**
After leaving note input mode, the last-entered note is selected, but Shift+Left/Right will not create a selection.

**To Reproduce**
1. New score
2. Enter some notes
3. Leave note input mode
4. Press Shift+Left to extend a range selection to the left of the most recently entered note
5. See error - nothing happens

**Expected behavior**
Shift+Left should always work to create a range selection, if a note or rest is currently selected.

**Platform information**
 - OS: Linux

**Additional context**
Works as expected in MU3.  Other keyboard navigation commands work, just the Shift versions to create/extend range selections do not.  Workaround, then, is use left then right to move focus away from and back to the last-entered note, and now Shift+Left/Right will work as expected.

FWIW, there are a number of other small glitches like this I've noticed where navigation or selection gets broken somehow during editing, requiring manual intervention.  I don't have any other specific examples at the moment, but from memory, it seems conceivable that they might all be related and that there is one central location where something is not getting set that should be.

**Comment by Tantacrul** [comment]
This is working for me in the latest nightly. Can you check again @MarcSabatella ?

**Comment by MarcSabatella** [comment]
Confirmed, working for me now.  BTW, in situations like this, should just hit the "Close" (as completed?) button myself (I guess I can do this for my own issues), or do you do some additional tagging/logging?

**Comment by Tantacrul** [comment]
Yeah, that'd be great!
