### ISSUE TITLE
[MU4 Issue] cant start play or move cursor to beginning after export to ogg

### ISSUE THREAD

**Issue by lyrra** [musescore/MuseScore#12900]
commit aeea6b1

export to wav or mp3 works.

**Comment by Tantacrul** [comment]
Can't replicate bug because I don't have enough information. Closing for now.

**Comment by lyrra** [comment]
Please reopen: reproducible in mingw. Not reproducible in linux.

**Comment by Tantacrul** [comment]
Can you flesh out the information. Add an image or two. Explain the problem in more detail and add reproduction steps.

We can't solve an issue we only vaguely understand.

**Comment by lyrra** [comment]
The menu panes isn't shown due to it being rendered in its own window, but around the middle of the video I'm doing an export to ogg.





https://user-images.githubusercontent.com/243748/195172134-950f514b-3199-45d2-b339-9d67665ac142.mp4

**Comment by lyrra** [comment]
Fixed in commit c1a6462 , closing.
