### ISSUE TITLE
[MU4 Issue] Accessibility: Braille displays to not show content of text input boxes

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12907]
**Describe the bug**
When entering text into an input field like for title in the new score wizard, a Braille display does not show the text you are typing

**To Reproduce**
1. Connect a Braille display (issue reported using a "Hims Polaris 6")
2. Create new score
3. Upon reaching the score information page, try entering a title
4. See error - Braille display does not show the characters as you type

**Expected behavior**
All text you type should show on Braille display

**Platform information**
 - OS: Windows

**Additional context**
Reported by user in https://musescore.org/en/node/334223#comment-1137793

I have no real experience with Braille displays myself.  In MU3, anything that happened with them happened simply because it was the Qt default; we never did anything special to interact with them that I know of.  But apparently this sort of thing worked better, as the user in question was accustomed to MU3 behavior and found this surprising in MU4.

**Comment by Tantacrul** [comment]
@shoogle - can you prioritise this and add a priority when you have time?

**Comment by shoogle** [comment]
@hhpmusic, can you confirm whether this issue still exists in the latest nightly builds of 4.1?

> When entering text into an input field like for title in the new score wizard, a Braille display does not show the text you are typing

**Comment by hhpmusic** [comment]
Now it shows.

**Comment by msviolafangirl** [comment]
I am a braille display user, and I can confirm this is no longer an issue. I tested with the latest stable release of MuseScore 4.
