### ISSUE TITLE
[MU4 Issue] Microsoft GS Wavetable Synth should be removed to avoid a problems (Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#12909]
**Describe the bug**
**Microsoft GS Wavetable Synth** was not present in MU3 in that form as it is now in MU4. 
Now you can select **Microsoft GS Wavetable Synth** in MIDI output and to have a problems like that:

https://user-images.githubusercontent.com/90187801/185153661-14136fff-0748-43c9-bbb5-e7a786e796fc.mp4

**Platform information**
 Windows10

**Additional context**
Doesn't occur in **MU3**

**Comment by DmitryArefiev** [comment]
Hi @Tantacrul , what do you think about just to remove Microsoft GS Wavetable Synth from the MIDI output list (on Windows)?

**Comment by cbjeukendrup** [comment]
But what are the problems specific to Microsoft GS Wavetable Synth? Everything I see in the video seems to be covered by #12543 and #12552.

**Comment by DmitryArefiev** [comment]
I don't think any user will be using Microsoft GS Wavetable Synth as output device. Especially when we will have Muse Orchestra sounds ( + MS basic).
 
And actually, Microsoft GS Wavetable Synth doesn't work properly now. You **can't use it just to play the scores**, you can't do any routing using MU interface and to have a proper sound as Sibelius or Finale have.

**Comment by Tantacrul** [comment]
@DmitryArefiev if it does I n fact serve no purpose or is broken, then yes, it should be removed.

**Comment by DmitryArefiev** [comment]
Done in #12877
