### ISSUE TITLE
[MU4 Issue] cant reach windows-toolbar if maximized window

### ISSUE THREAD

**Issue by lyrra** [musescore/MuseScore#12901]

**Comment by mattblo** [comment]
I don't know if this is exactly what you mean, but my guess is this: If you set the taskbar in Windows to "auto-hide", it will no longer appear automatically when Musescore 4 is open.

**Comment by lyrra** [comment]
Exactly this. Thanks for clarifying!

**Comment by Tantacrul** [comment]
Can you please provide a visual to show what the issue is? @DmitryArefiev / @jessjwilliamson - do either of you know this issue?

**Comment by cbjeukendrup** [comment]
Duplicate of #10958

**Comment by Skelbti** [comment]
This behaviour still happened for me with the latest release.

**Comment by DmitryArefiev** [comment]
> This behaviour still happened for me with the latest release.

Yes, #10958 is not fixed yet. Also occurs in the latest master in my side.

Thanks!
