### ISSUE TITLE
[MU4 Issue] Dynamics search in palettes 

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#12905]
Wouldn't count this as a bug but maybe a request/improvement?

These dynamics are not under their full names - found in tool tips and search box in palettes.

For example - I want to search for 'forte' dynamic. But because it is named under 'f' in tooltips, this comes back with strange search results:
- Searching 'forte' doesn't show the dynamic
- Searching 'f' results in other mixed results

**To Reproduce**
1. Go to 'Palettes'
2. Click on Search box
3. Search for 'forte'

![image](https://user-images.githubusercontent.com/71656189/185115169-31713715-32dd-408f-81b0-e3e70637997e.png)
![image](https://user-images.githubusercontent.com/71656189/185115643-22fd1ab8-ff72-435f-9269-e288aa7c20d6.png)

**Expected behavior**
I'd like to see if the names of all the dynamics to be improved. 
Instead of 'p' use 'piano', instead of 'mf' use 'mezzo-forte' etc.

**Comment by MarcSabatella** [comment]
I think ideally both should be in the name, so you can search on either.  Searching based on the abbreviation is more efficient  and also more natural for many people
who might not even know the full Italian names.  So it would be an accessibility regression to remove this ability while also adding the new full names.

**Comment by jessjwilliamson** [comment]
> 

Yes, both to be possible would be great :)

**Comment by quinnouyang** [comment]
Well, if you set every dynamic to its full name, searching by the letter representation would still generate it as a result, unless there's a dynamic that doesn't take its symbol from its name. I'm for this!

**Comment by MarcSabatella** [comment]
That works only for single letter dynamics.  The string "pianissimo" doesn't contain the substring "pp", nor does "mezzo forte" contain "mf".

**Comment by quinnouyang** [comment]
Right. Could take a look at the structure and maybe add a parameter of hidden alternate names to search for, if appropriate.

**Comment by Tantacrul** [comment]
Yeah. We should definitely do this. Thanks Jess. Adding to 4.x. Will reopen once 4.0 is out.
