### ISSUE TITLE
[MU4 Task] Make language selector react to key presses

### ISSUE THREAD

**Issue by Wim4rk** [musescore/MuseScore#12915]
When I'd like to change language in "Preferences" I don't want to scroll. I want to punch the first letter of the language I'm looking for and it should appear. If I'm allowed to type that would be a luxury. Possibly change to combo-box?

**Comment by henkdegroot** [comment]
Perhaps some other list box items in the several dialogs can be update with the same feature as well?

**Preference dialog:**
Font face selection in Appearance
Default zoom selection in Canvas
Overture import and shortest note selection in Import
Audio device and Midi Input/output in I/O

**Style dialog:**
Musical Text Font in Score style.   (Interesting fact, Musical Symbol Font already contains the logic)

Glad the functionality to select the font for each Text style list item is working.

**Comment by Tantacrul** [comment]
This would be really nice for all our dropdowns actually. I can't (in good conscience) make it a priority for this release but we really do need to do it in the next release. All dropdowns work this way and it's annoying as hell when they don't.

If anyone wants to take this, I can specify logic.

I'm bumping to 4.x for now. We'll reopen once 4.0 is out. We **will** fix this soon.

**Comment by MarcSabatella** [comment]
I'd love to see this reopened and prioritized, and indeed, for all dropdowns or equivalent lists (eg, the sound selection in the mixer).

**Comment by cbjeukendrup** [comment]
I'll create a fresh new task, since this applies to dropdowns and menus in general.

**Comment by cbjeukendrup** [comment]
See #16508.
