### ISSUE TITLE
[MU4 Issue] Playback of a score made with Nightly 4.0 causes crash of the program

### ISSUE THREAD

**Issue by stefanorattini** [musescore/MuseScore#12911]
**Describe the bug**
Playback of a score made with Nightly 4.0 causes the crash of the program

**Expected behavior**
I closed the score and re-opened it to play it back, but the program crashed.

**Platform information**
 - OS: Windows 11

Many thanks! Stefano

**Comment by HemantAntony** [comment]
Can you upload the score?

**Comment by Tantacrul** [comment]
I'm closing this issue until more information is added. Thanks!

**Comment by stefanorattini** [comment]
Sorry,
I have uninstalled the Nightly and I have "downgraded" to 4.0 Alpha; now it
seems to work properly..

Many thanks, Stefano Rattini

Il giorno sab 27 ago 2022 alle ore 14:07 Hemant Antony <
***@***.***> ha scritto:
