### ISSUE TITLE
[MU4 Issue] Adding parts sometimes chrashes program

### ISSUE THREAD

**Issue by Wim4rk** [musescore/MuseScore#12914]
Adding parts sometime crashes program. 

__Steps to reproduce the behaviour:__
1. Open score made in MU3.6.2 from Home/Scores/New & recent
2. Acknowledge "Style improvements"
3. Click on parts
4. Click on Create new part.
5. Musescore crashes

__Alternatively:__
1. Open score made in MU3.6.2 from Home/Scores/New & recent
2. Acknowledge "Style improvements"
3. Save as MU4.
4. Click on Create new part.
5. Musescore crashes 

**Expected behaviour**
Expected a new part to be added

**Platform information**
 - Ubuntu 20.04

**Additional context**
_Nota bene_: this is for some files, some work great, even if they're MU3-files. Used pretty similar files for testing though. Trombone exercises; one part, no chords, some slurs, some staccato dots.

**Comment by Tantacrul** [comment]
Could you provide a score where this is happening? It would help us isolate this issue. At present, I cannot reproduce this.

**Comment by Wim4rk** [comment]
Can no longer recreate. Probably solved...

**Comment by Tantacrul** [comment]
Thanks. Closing for now.
