### ISSUE TITLE
[MU4 Issue] Repeat last measure symbol not centered in tablature

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12928]
**Describe the bug**

If you create an empty Guitar staff/tab score, and apply a __Repeat last measure__ symbol (Repeats and Jumps palette), it is placed vertically off-centre in the tablature staff.

![repeat_last_measure](https://user-images.githubusercontent.com/87246583/185597144-4429a8ea-2c83-4ff0-9846-74f2b2e369d4.png)

The same thing happens with imported MS3 scores.

Incidentally, in MS3 a similar setup looks like this:
![ms3_repeat](https://user-images.githubusercontent.com/87246583/185597449-6cbad2a9-d847-4116-9ea3-e3331a0cbe51.png)

In MS4, the repeat symbol is the same size in both staves. Is that now by design?

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2887048614, revision: github-musescore-musescore-61484bc

**Comment by oktophonie** [comment]
By design - see [#9886](https://github.com/musescore/MuseScore/pull/9886).
