### ISSUE TITLE
[MU4 Issue] Dock panel does not respect maximum size anymore after moving it from leftmost column to other location

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#12925]
**To Reproduce**
1. Open a score on the "Score" page.
2. Have some panels docked in the leftmost column.
3. Move one or more panels to a different dock location in a different column.
See error: the moved panel does not respect its maximum size anymore; you can resize it very wide.
4. Open the Mixer 
See error: the moved panel becomes automatically very wide (it seems that the space is distributed equally between the notation view and the moved panel)
5. Switch to another page and switch back to the "Score" page.
Note that everything is fine again, until you move a panel again to the left column and then again move it to another location.

**Expected behavior**
Maximum size should be respected.

**Screenshots**

https://user-images.githubusercontent.com/48658420/185448445-9f8ca1b4-38b9-45e7-9d55-6eac4e429464.mov

**Platform information**
 - OS: reported on macOS

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Can you upload the video again please? It shows me the file is corrupt..

**Comment by cbjeukendrup** [comment]
Hm... let's try if this helps.

https://user-images.githubusercontent.com/48658420/186714342-23f27af7-539b-4b10-8685-c0aacfc0e1cc.mov

**Comment by DmitryArefiev** [comment]
Hm.. strange I still don't see them (in player).. Probably because I'm on Windows. 
Anyway I downloaded the file and opened in video player, it's fine now.

**Comment by DmitryArefiev** [comment]
What app do you have for video capture?

**Comment by cbjeukendrup** [comment]
I use macOS's built-in default.

**Comment by DmitryArefiev** [comment]
You mean Quick Time Player? Can you try Export as menu (720p) and upload the video again please?

Just curious:)

**Comment by cbjeukendrup** [comment]
For the recording, I don't use QuickTime, I always just press Cmd+Shift+5 (but the result is probably technically equivalent).

I already tried re-exporting, but with 1080p. Here's the 720p version:

https://user-images.githubusercontent.com/48658420/186719757-02a2072c-efa5-4c16-977f-f1c4cf54d0e0.mov

**Comment by DmitryArefiev** [comment]
Ah, OK. 

The last video is also not shown for me. But that's not a problem I can download it and reopen in windows player.

Thanks anyway!

**Comment by DmitryArefiev** [comment]
Fixed in #12937
