### ISSUE TITLE
[MU4 Issue] Ampersand is present in Export and Save shortcuts name

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12921]
**Expected behavior**
No ampersands shortcuts names

**Screenshots**
![Capture 2022-08-18_02-54-51_PM copy](https://user-images.githubusercontent.com/101250347/185392406-c0f304ca-7a5a-4a5b-8d50-98b815ff28e5.png)

**Additional context**
Could be fixed along with https://github.com/musescore/MuseScore/issues/12922

**Comment by Jojo-Schmitz** [comment]
Should be solved by #12861
