### ISSUE TITLE
[MU4 Issue] Percussion beams on wrong side

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#12936]
**Describe the bug**
Percussion staff stems and beams can be on the wrong side when entered from the on-screen Piano. I haven't tested a MIDI keyboard, but it is possible that the problem exists there as well.
 
**To Reproduce**

1. Create a 5-line percussion staff score.
2. In note-input mode, ensure voice 1 is selected and enter some eighth-note closed hihats (F#2) in measure 1  using the on-screen piano.
3. Select voice 2 and enter some 1/4 note bass drum beats (C2) in the same measure using the on-screen piano.

RESULT: Voice 1 beams are on the wrong side of the notehead.

![percussion_beams](https://user-images.githubusercontent.com/87246583/185669280-34ded430-5926-4e59-857f-ad15722cb646.png)

 Curiously, if you break all the beams using the "no beam" icon then UNDO, the beams appear on the correct side.

**Expected behavior**

Voice 1 Stems should point upwards in this case.

**Platform information**
 OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2887048614, revision: github-musescore-musescore-61484bc

**Comment by Tantacrul** [comment]
@mike-spa / @asattely - can either of you fix this issue? Sounds quite bad.

**Comment by mike-spa** [comment]
I think I actually have a fix, gonna make a PR soon

**Comment by MarcSabatella** [comment]
No, the beam direction issue does not occur in MU3.  It's kind of moot because normally you get the wrong note entirely, so you basically can't use MIDI / piano input for drums in MU3.  But interestingly, in those few cases where you do manage to get the right note, the beaming is actually correct in *both* versions.  It's only the cases where you do get the right note that the beaming is wrong in MU4.

**Comment by Tantacrul** [comment]
> I think I actually have a fix, gonna make a PR soon

Awesome.

**Comment by Tantacrul** [comment]
@rgreen5 / @MarcSabatella: will you check this when it's ready?

Currently testing a bunch of other PR's myself.

**Comment by MarcSabatella** [comment]
I tested, and it fixes both issues as advertised - nice job, @mike-spa!

**Comment by Tantacrul** [comment]
In that case @RomanPudashkin / @Eism - if you're happy, can we proceed to merge-ville?
