### ISSUE TITLE
[MU4 Issue] "R" command to add a repeated note does not also play the note

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12935]
**Describe the bug**
When in Note Input mode, pressing 'R' repeats the last entered note. However, you do not hear the new note (we did in MS3). This is a problem for blind users.

**To Reproduce**
1. New score
2. First measure, note input
3. Type C (enters a C and you hear it)
4. Press R (adds a new 'C' - but you don't hear it)

**Comment by Tantacrul** [comment]
I've altered the description and explanation to just make it a little clearer.

**Comment by MarcSabatella** [comment]
@Tantacrul - I meant to list this one last week as one of the accessibility issues worth addressing.

I *think* it's a one-line fix, the same as https://github.com/musescore/MuseScore/issues/13687 - just a matter of adding a call to setPlayNote() to the right place.  I can probably find the right spots with some trial and error (or if someone wants to advise me).  I will see if I can pull that off; would be nice to contribute something concrete to the code for 4.0

**Comment by MarcSabatella** [comment]
See https://github.com/musescore/MuseScore/pull/14347, which fixes this
