### ISSUE TITLE
[MU4 Issue] Opening a file will launch the app but not load the score on macOS

### ISSUE THREAD

**Issue by TheCymaera** [musescore/MuseScore#12943]
**Describe the bug**
Opening a file with MuseScore4 will launch the app but not load the score, unless the app is already open.

**To Reproduce**
1. Ensure all MuseScore windows are closed.
2. Open a .mscz or .mid file with MuseScore4.
3. MuseScore launches, but the score is not loaded.
4. Optional: Try again, the score will now load.

**Expected behavior**
The score should load after launch.

**Platform information**
 - OS: macOS Monterey 12.4

**Comment by cbjeukendrup** [comment]
This was indeed an issue in Alpha 2, but I have already created a fix: #12595. It has not yet been merged, but once it's merged, you can retry using the latest nightly build from https://ftp.osuosl.org/pub/musescore-nightlies/macos/4x/nightly/?C=M;O=D.

**Comment by DmitryArefiev** [comment]
Fixed in #12595
