### ISSUE TITLE
[MU4 Issue] Sustain pedal not working with VSTs

### ISSUE THREAD

**Issue by bastien-57** [musescore/MuseScore#12941]
**Describe the bug**
The sound prolongation effect linked to the symbol of the sustain pedal does not work with VSTs, although it works with the MS Basic soundfont.

**To Reproduce**
1. Create a piano score
2. Compose some bars
3. Add a pedal line on the desired measures
4. Change the sound in the mixer to a VST
5. Play

**Expected behavior**
The sound produced by the VST must be sustained, like the sound of the starting piano.

**Screenshots**

The default piano sound with the pedal :

https://user-images.githubusercontent.com/52534278/185740226-e1aa4883-b15f-4295-a26c-2757c5d65ce2.mp4

The sound of a piano vst (here LABS from Spitfire Audio, but works with all the other vst tested) with the pedal :

https://user-images.githubusercontent.com/52534278/185740273-24cdaf66-2b96-415f-aae5-4adad5cf3477.mp4

**Platform information**
 - OS: Windows 10 x64

**Comment by ChriiMoral** [comment]
I've noticed that the notes actually become shorter (as if they became stacatto).

**Comment by DmitryArefiev** [comment]
Fixed in #13755
