### ISSUE TITLE
Numpad not working to select notes

### ISSUE THREAD

**Issue by flyingrabbitgb** [musescore/MuseScore#12944]
The numpad keys are not working to select note durations for input - the numbers above the letters on the keyboard have to be used. This was working fine in Musescore 3. Even after changing the shortcuts in Preferences this doesn't work - it doesn't seem to see a difference between keyboard and numpad.

**Comment by critchie** [comment]
See #12791

**Comment by cbjeukendrup** [comment]
Closing as a duplicate of #12791. Thanks for reporting!
