### ISSUE TITLE
[MU4 Issue] Can't add accidentals to trills

### ISSUE THREAD

**Issue by dxing97** [musescore/MuseScore#12954]
**Describe the bug**
When attempting to add an accidental to a trill line, nothing happens. 

**To Reproduce**
1. Click on a note
2. Add a trill line from the "Lines" palette
3. Click on the trill line
4. Click on an accidental from the "Accidentals" palette
5. Nothing happens

**Expected behavior**
An accidental appears somewhere next to/above the trill line.

**Screenshots**

**Platform information**
OS: macOS 12.5, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2897146315, revision: github-musescore-musescore-89ef1de

**Additional context**
Works in 3.6.

**Comment by oktophonie** [comment]
I don't recall having touched trill lines in any way (from the engraving side) that would have caused this regression. Anyhow, we'll take a look!
