### ISSUE TITLE
[MU4 Issue] Articulations will jump above measure numbers

### ISSUE THREAD

**Issue by dxing97** [musescore/MuseScore#12955]
**Describe the bug**
When measure numbers are set to be centered above measures, articulations will jump up above the measure number, even if the measure number is very far away from the staff and there is clearly enough space below the measure number to fit articulations. 

**To Reproduce**
1. Open a new score2. 
2. Make a bunch of eighth notes at C5 on a couple of measures, place accents on all of them
3. In Format-> Style-> Measure Numbers, change measure numbers to 1) show at every interval 2) set horizontal placement to "Center"
4. Go to Format-> Style-> Text Styles -> Measure number and increase the size of the font and increase the Y axis offset.  
5. Go back to score, look at accents float above measure numbers

**Expected behavior**
Accents to be below measure numbers

**Screenshots**
<img width="481" alt="image" src="https://user-images.githubusercontent.com/3182625/185837284-29087fdc-8df2-42bd-8cf7-70c293016825.png">

https://user-images.githubusercontent.com/3182625/185837215-abef1e2a-19e0-4332-9e84-9adf02646320.mov

**Platform information**
OS: macOS 12.5, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2897146315, revision: github-musescore-musescore-89ef1de

**Additional context**
Can also occur with system/staff text, tempo markings.

**Comment by MarcSabatella** [comment]
FWIW, same issue in 3.6.2.  Measure numbers themselves don't move to avoid other elements, but other elements move to avoid them.  They are generated pretty early in the layout process.  No idea if it could be safe to move that until after articulations.

**Comment by oktophonie** [comment]
As this is not a regression, we will defer to 4.X (but I would like to sort it out properly).

**Comment by mike-spa** [comment]
A few thoughts for when we come back to this.
1) Start-of-system measure numbers are different than mid-system measure numbers. In the first case, the position of the number should be fixed and the other object should move out of their way (a). In the second, it is the number that should move out of the way (b).


<img width="829" alt="image" src="https://user-images.githubusercontent.com/93707756/185936273-4457fbd0-a6e1-4c0b-82e5-78fac646ed6e.png">
