### ISSUE TITLE
[MU4 Issue][Win] Cracks are present in audio when playing score with opened mixer

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#12968]
**To Reproduce**
1. Open any score 
2. Open Mixer
3. Play the score 
4. Pay attention to the audio artefacts

**Expected behavior**
No audio cracks when playing score with opened mixer

**Screenshots**

https://user-images.githubusercontent.com/101250347/185964966-d7df2001-c4ec-4aa7-a34b-4798f5e7c068.mp4

**Platform information**
 - OS: Windows 11

**Additional context**
Could be linked with https://github.com/musescore/MuseScore/issues/12969

**Comment by boryskuzmenko** [comment]
@Tantacrul If you think that this issue is not for Beta1 please move to MU4.x

**Comment by Tantacrul** [comment]
Anything that affects all audio like this (extra-specially when it's on Windows) should most likely be a P1 or a P0. Definitely a Beta 1 issue.

If it is a rare problem (and doesn't happen on most Windows devices), then it can definitely be deprioritised a bit. @DmitryArefiev, @oktophonie - are you also getting this problem?

**Comment by Tantacrul** [comment]
Thanks @boryskuzmenko !

**Comment by DmitryArefiev** [comment]
@Tantacrul Yes, also occurs on my Windows Laptop with Mixer opened. Should be fixed in Beta1

**Comment by Tantacrul** [comment]
@DmitryArefiev - there have been a lot of performance improvements in this are (I notice on Mac and PC). Could you potentially re-check? Regardless, I think it is safe to move this to Post-Beta now because the issues are significantly improved.

**Comment by DmitryArefiev** [comment]
@Tantacrul Yes, there were some improvements.. but unfortunately the issue still exists on **Windows** with MS Basic and Muse Sounds

https://user-images.githubusercontent.com/90187801/195397209-940712c1-e5ad-4222-804b-30dd786fd694.mp4

**Comment by zacjansheski** [comment]
This seems resolved (Capture from entry-level Windows 11 PC)  Are there any objections to closing?

https://github.com/musescore/MuseScore/assets/69917893/cfaa8d01-ede6-4d8b-8414-19635a61058f

**Comment by DmitryArefiev** [comment]
All good on my side too (4.2.0 master, Win10). I think this was fixed long time ago

Closing
