### ISSUE TITLE
[MU4 Issue] Too big custom time signature causes the program to stop responding

### ISSUE THREAD

**Issue by PetJer** [musescore/MuseScore#12970]
**The bug**
Program stops responding when entering too big numbers (e.g. 1000) in a custom time signature. Same issue in v3.6

**To Reproduce**
1. Open the window for creating a custom time signature from the palette
2. Enter a big number (e.g. 1000) 

![create_time_signature_window](https://user-images.githubusercontent.com/79419198/185990354-a6a07658-0b81-411b-9fe7-8c4fe011fb59.jpg)

**Platform information**
 - Windows 11

**Suggestion for fix**
Give the Value field a range like in the New score wizard (1 - 63)

**Comment by L0uisc** [comment]
Hi @jacobjohnso. Are you still working on this?

**Comment by Jojo-Schmitz** [comment]
Restricting the value seems to cure the symptom rather than the cause, such large numbers are possible in Mu3

**Comment by avvvvve** [comment]
I think this mainly has to do with the beam groups renderings redrawing every time a new number is typed (on Mac currently, it just takes a really long time to update but eventually does). I'm mid-redesign of time signature creation now and it's safe to say we'll separate beam grouping into its own window or popup, so that should solve this issue.

**Comment by zacjansheski** [comment]
See https://github.com/musescore/MuseScore/issues/23697 for conversation about imposing a limit

**Comment by avvvvve** [comment]
The suggested fix (if someone picks this up before we overhaul time signatures):

- Add an upper limit to the numerator field of 999
- Do not re-render the beam diagrams while the user is typing. Only do so once they've focused away from the numerator field.

**Comment by Abhay-Varnekar** [comment]
I would like to give a try and find out a solution for this issue 
Please let me know if anyone else is already working on this or if I have your permission to proceed.

**Comment by cbjeukendrup** [comment]
@Abhay-Varnekar it looks like this one hasn't been taken yet, so go for it!

Quick hint to get you started: see timesignaturepropertiesdialog.ui/.cpp, _and_ timedialog.ui/.cpp. And note that spinboxes in Qt have not only a `valueChanged` signal but also `editingFinished`, which is probably necessary to address the second point from [the suggested fix above](https://github.com/musescore/MuseScore/issues/12970#issuecomment-2474720644).

**Comment by Abhay-Varnekar** [comment]
https://github.com/user-attachments/assets/bc806488-3769-4d3f-a1cc-fc0d9a9e52f1

## Summary of Changes

1. **Numerator Field Limit**:
   - An upper limit of **999** was added to the **numerator field** (zNominal) to restrict the user input.
   - This change ensures that users cannot input a numerator larger than **999**.

2. **Graphics Rendering Behavior**:
   - The graphics (time signature diagram) now **do not re-render continuously** while the user is typing.
   - Instead, the graphics will only **re-render when the user presses Enter or moves focus away from the numerator field**. This prevents unnecessary re-renders during typing and improves performance.

**Comment by cbjeukendrup** [comment]
@Abhay-Varnekar Yes, that looks right! Looking forward to your PR.
