### ISSUE TITLE
[MU4 Issue] Falls & other bends do not play on last note of a tie

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12971]
**Describe the bug**
The new fall playback is basically good, but fails if adding to the end of a tied note.

**To Reproduce**
1. Score for trumpet
2. Enter two tied notes
3. Attach a fall to the second
4. Play
5. See error: the fall does not play

**Expected behavior**
Fall should play

**Screenshots**
![image](https://user-images.githubusercontent.com/1799936/185995972-f2a348be-3a9c-4f67-aae6-9dd5bddc7cf5.png)

**Platform information**
 - OS: Linux

**Additional context**
It works if you add to the first note of the tie, although that's incorrect notation

**Comment by wizofaus** [comment]
This is true of glissandi too which is especially annoying, as the default (and seemingly unadjustable) playback for portamento glissandi is to smoothly change the pitch as soon as the note is first sounded, despite this rarely being what would be musically expected except in the case of special effects.

**Comment by MarcSabatella** [comment]
The workaround of placing the fall on the note before the tie is what I'm doing right now for my MuseScore Café theme music.  But it's hard to say that this constitutes an improvement over the workaround with gliss in MuseScore 3.  This ends up being one of the only remaining issues in that piece.

**Comment by MarcSabatella** [comment]
@Tantacrul - this is one of the few playback-related bugs not already on the "release" list that I'd like to see added.

FWIW, I had originally hoped maybe this was fixed as part of a somewhat similar fix involving glissandi (https://github.com/musescore/MuseScore/pull/13820), but it seems not,  However, it also seems that fix wasn't quite right and led to the ties-not-working-for-playback issue (https://github.com/musescore/MuseScore/issues/14137).  So whenever the glissando fix is revisited, it might make sense to look at this as well to see if similar code can apply.

**Comment by MarcSabatella** [comment]
Interesting new behavior, not sure exactly when this changed, but - the fall on a tied note does play, if the passage also has a slur.  Maybe that much is connected to #13820?  Will be interesting to test again with the tie playback fix.

For example, in the following:
![image](https://user-images.githubusercontent.com/1799936/200891567-5f3a95ee-8b33-4503-8e7f-63794f3a32e5.png)
The trumpet and alto sax fall, the trombone does not.

So my new workaround for this particular case is, add an invisible slur (invisible, because slurs on trombone parts don't normally make sense).

**Comment by wizofaus** [comment]
Not to sidetrack the issue but wouldn't a slur in a trombone part just indicate "play as a phrase, as legato as possible"?

**Comment by MarcSabatella** [comment]
Just tested again with the the PR that fixes the general tie-within-slur playback issue, unfortunately it broke the fall playback again, so adding slurs no longer allows tied falls to work.

**Comment by Tantacrul** [comment]
We'll unfortunately need to move it to Post Release because the fix is too risky to attempt at this stage.

**Comment by s11141827** [comment]
Yeah I'm having this kind of issue too.

**Comment by s11141827** [comment]
I also noticed that the falls don't also play on the Trumpets A4, Trombones A3, & Horns A6 sounds for Musebrass so we need to get that updated too.
