### ISSUE TITLE
[MU4 Issue] Panels doesn't go back to previous size after opening Mixer panel

### ISSUE THREAD

**Issue by cgpqci** [musescore/MuseScore#12976]
**Describe the bug**
Panels, specifically the bottom panel and right panel, doesn't resize back to smaller size after closing an opened Mixer panel.

**To Reproduce**
1. Dock any panel from the left side of the screen to the right and resize width to its minimum Additionly, you may resize the bottom panel to its minimum height (_optional_).

![image](https://user-images.githubusercontent.com/90231404/186098078-14100ec5-3075-4d6f-9e5e-9dcc2a3d66f8.png)

2. Open the Mixer panel through any preferred method.

![image](https://user-images.githubusercontent.com/90231404/186098198-26dbd188-ef30-4733-95bb-1cf3a7b112cc.png)
(_The bottom panel resizes to fit the Mixer interface, and somehow the right panel will extend its width as well to a certain extent._)

3. Close the Mixer panel through any preferred method.

![image](https://user-images.githubusercontent.com/90231404/186098278-c8d0e8d3-314c-462b-8b95-1826f475b06a.png)
(_The resize persists._)

**Expected behavior**
The panels should shrink back to its prior size; better yet, the Mixer interface can adjust to its window/panel size.

**Screenshots**
See above.

**Platform information**
 - OS: Windows 10
 - Version: MuseScoreNightly-202208230452-master-64960b1-x86_64

**Additional context**
After fiddling a bit with the issue, it seems that it only occurs when it's the Mixer that's activated. When you priorly open the Mixer, resize, and open the Keyboard panel (given that the said panel is inactive), no resize occurs, but does happen when the Mixer is opened afterwards. This is quite bothersome especially when using MuseScore on smaller screensize.

**Comment by RomanPudashkin** [comment]
Could you please check this fix?
https://github.com/musescore/MuseScore/pull/12937

**Comment by DmitryArefiev** [comment]
Fixed in #12937
