### ISSUE TITLE
[MU4 Issue] [Accessibility] VoiceOver says 'text' after dropdown values

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#12984]
**Describe the bug**
When a dropdown box is expanded and you select a value using the arrow keys, VoiceOver says the word "text" after each value. (Possibly to do with the accessible role being reported for dropdown controls.)

**To Reproduce**
1. Launch VoiceOver (Cmd+F5).
2. Open the New Score dialog > Choose Instruments page.
3. Navigate to the "Order" dropdown and press Spacebar to expand it.
4. Use the Up and Down arrow keys to change the value.
<img width="401" alt="image" src="https://user-images.githubusercontent.com/11011881/186041217-f715cebe-6de4-4815-88a8-a8f8b199b2f0.png">

5. Navigate to 2nd page of the New Score dialog ("Additional score information")
6. Expand the Time Signature popup.
7. Tab to the denominator dropdown and press Spacebar to expand it.
8. Use the Up and Down arrow keys to change the dropdown value.
<img width="310" alt="image" src="https://user-images.githubusercontent.com/11011881/186040493-5eac23bb-d40c-44ae-83e7-b8a5560435b4.png">

**Expected behavior**
The screen reader should just announce the dropdown value as it changes:
- "Orchestral"
- "Choir"
- "Marching band"
- etc.

 Instead it says the value followed by the word "text".
- "Orchestral, text"
- "Choir, text"
- "Marching band, text"
- etc.

Similarly, in the time signature dropdown it says the number followed by "text".

**Platform information**
 - OS: macOS running VoiceOver

**Comment by Tantacrul** [comment]
Since you've targeted this, I'm closing until we reopen 4.x issues.
