### ISSUE TITLE
[MU4 Issue] Score date on MuseScore 4 always say 'TODAY'

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#12995]
**Describe the bug**
Dates for recent scores are no longer working as before and always say TODAY

<img width="686" alt="image" src="https://user-images.githubusercontent.com/21022311/186381812-13cfc802-2cf1-4ca1-a8c8-8b5db3667125.png">

**Platform information**
 - MacOS
 - (not checked Windows / Linux)

**Comment by Jojo-Schmitz** [comment]
Esp. wierd: the string "TODAY" (in all-caps) doesn't show anywhere in the MuseScore sources, only the string "Today"

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz Not so weird, see https://github.com/musescore/MuseScore/blob/9c82c6428985ee117a95b2d768992dce12ce43dc/src/project/qml/MuseScore/Project/internal/ScoreItem.qml#L187

**Comment by Jojo-Schmitz** [comment]
Ah, I see.

**Comment by Jojo-Schmitz** [comment]
Not sure though whether's a good idea.

**Comment by Jojo-Schmitz** [comment]
If these strings are to be used in uppercase only, the original strings should be in uppercase. And it should be left to the translatore whether to keep them that way

**Comment by HemantAntony** [comment]
@Tantacrul Here ya go: #12996

I also removed the brackets. So '2 DAY(S) AGO' is no '2 DAYS AGO'. Similarly for weeks. There will never be a case for '1 DAY AGO' since we call that 'YESTERDAY'

**Comment by Tantacrul** [comment]
> @Tantacrul Here ya go: #12996

Wow, that was fast! Thanks so much @HemantAntony :)
