### ISSUE TITLE
[MU4 Task] Show tooltips in Properties panel

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#13012]
**Task description**
Show tooltips for options in the Properties panel. Tooltips are useful for nameless buttons that just have an icon with no text: it gives users a string that they can type into search engines / forum posts to get help. Tooltips also mean that users are less likely to need help in the first place.

Tooltips in the Properties panel should have a short 'title' and an optional 'body', just like these examples from the note input toolbar:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/11011881/186555018-09c57c8f-5a89-4417-8a0a-3f2cb9a0f0bf.png"> <img width="100" alt="image" src="https://user-images.githubusercontent.com/11011881/186555289-a84daa37-1aad-4d78-9063-ab6a1ed2759d.png">

**Title:** should be same as accessible name sent to screen readers.
**Body:** should be same as accessible description (or blank if there is no description).

It should be possible to create these tooltips in the Properties panel without creating any new strings.

### Text alignment buttons

<img width="299" alt="image" src="https://user-images.githubusercontent.com/11011881/186668547-ff32367e-ebe3-478b-b4b9-3030fcbf3a34.png">

In the case of the buttons for text alignment, it is desirable to change the strings (though the new text is similar to tooltips displayed in MU3, so we already have translations for most of these). The new strings are:

Tooltip title & accessible name | Tooltip body & accessible description
:---|:---
Align left | Align left edge of text to reference point
Align center | Align horizontal center of text to reference point
Align right | Align right edge of text to reference point
Align top | Align top edge of text to reference point
Align middle | Align vertical center of text to reference point
Align bottom | Align bottom edge of text to reference point
Align baseline | Align baseline of text to reference point

The purpose of mentioning a reference point is to clarify that **align top** text will appear _below_ **align bottom** text in the score:

Alignment to fixed reference point | Example: staff text with 'auto-place' disabled
:---:|:---:
![image](https://user-images.githubusercontent.com/11011881/186447332-112e690b-b5f0-4c75-903e-81e2f6235c8d.png) | <img width="378" alt="image" src="https://user-images.githubusercontent.com/11011881/186441545-05864fe1-d17c-4b31-b01c-84cef893fe73.png">

Users may be more accustomed to alignment in boxes and tables, which exhibits the opposite behaviour:

Alignment to container boundaries<br>(i.e. moving reference point) | Example: text in a vertical frame
:---:|:---:
![image](https://user-images.githubusercontent.com/11011881/186449933-62e48e89-7e18-42bf-8c55-5e74dafb5d22.png) | <img width="85" alt="image" src="https://user-images.githubusercontent.com/11011881/186462853-0baa5984-22e4-4c78-b9fc-13e4b8f67dd5.png">&nbsp;<img width="88" alt="image" src="https://user-images.githubusercontent.com/11011881/186463091-93e7cf2f-aff3-468e-ae22-aac265c782b7.png">&nbsp;<img width="92" alt="image" src="https://user-images.githubusercontent.com/11011881/186463361-2e7a5647-3b95-4e3b-864a-dca3c450364e.png">&nbsp;<img width="98" alt="image" src="https://user-images.githubusercontent.com/11011881/186463899-b9b04ffe-2b19-44bb-adb4-9e576947ae64.png">

Similarly, **align left** text will appear to the _right_ of its reference point, which is often the _left_ edge of a frame.

(Perhaps in frames we should provide the option to move the reference point independently of the alignment, like the [Gravity setting in ImageMagick](https://www.rubblewebs.co.uk/imagemagick/notes/gravity.php), but with a default 'auto' option to make the gravity match the alignment. Just an idea for the future 🙂)

**Comment by HemantAntony** [comment]
On it!

**Comment by shoogle** [comment]
@HemantAntony, thanks! If it's not possible to create tooltips automatically in a generic way (i.e. always use accessible name as title and accessible description as body) then it's ok to just create tooltips manually for the text alignment buttons and leave the rest of the Properties panel for another time.

**Comment by HemantAntony** [comment]
@shoogle Also the Style buttons also seem to be missing a tooltip:
![image](https://user-images.githubusercontent.com/88136054/186672574-0f5ae435-bc13-4beb-a5cd-6a97351f8f7d.png)

**Comment by shoogle** [comment]
Cool. I don't think we need anything special for those: just "Bold", "Italics" and "Underline" will do as the names. Currently screen readers say "Style: bold", etc. so you should remove the "Style" from the front of name (for both tooltips and screen readers). These don't need a description.

**Comment by Jojo-Schmitz** [comment]
And "Strike-through" too I guess

**Comment by HemantAntony** [comment]
@shoogle I create a PR: #13021
