### ISSUE TITLE
[MU4 Issue] Mapping. More than one midi parameter can be mapped to one MU parameter

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#13028]
**Describe the bug**
In this case I use NI Maschine MK3 Mikro (pad controller)
When I map a pad to Play action I just press the pad. In the settings I see corresponding midi input and note. But at the same time aftertouch parameter was catch when I pressed the pad and also mapped. I'm not sure it was mapped to Play also or to rewind but when I press the pad and unpress for a while playback is stuck on the first note. When aftertouch parameter is changed it plays from the start again and again. 
Second part of story.
When I map another pad to Rewind action aftertouch is also mapping to the Loop action, so when I press the pad it move playback to start but at the same time enable/disable Loop.

Also, I believe that only 0 and 127 values should be recieved for midi controllers which send values 0-127 during mapping. So they should be used as on/off controller till we have only simple toggle elements for mapping.

**Expected behavior**
Only Note On midi event is used for mapping when any note pressed

**Screenshots**

https://user-images.githubusercontent.com/101250347/188182484-b6958ffd-8eb4-4649-83cc-c12e790f3dcf.mov

**Platform information**
 - OS: macOS, Windows

**Additional context**
Could be linked with https://github.com/musescore/MuseScore/issues/13030 and https://github.com/musescore/MuseScore/issues/13031

**Comment by jessjwilliamson** [comment]
Looks like attached mov file didn't upload properly. can you try re-uploading it please?

**Comment by boryskuzmenko** [comment]
@jessjwilliamson I found that file and re-uploaded again but unfortunately there's no sound (possibly video file was corrupted). 
I'll be able to record a new video on Tuesday

**Comment by abariska** [comment]
@jessjwilliamson @Tantacrul Here's the video with audio. When you see a lot of events on midi monitor and stuck note thats me pressing note to get aftertouch effect.
And also I've investigated a bit more. My summary is there're some midi events which affect to all assigned mappings. For instance, you assigned Play to C0, Rewind to C#0 and Loop to D0. It will work as expected only if your midi device sent only note on and note off events. Once your device sent Aftertouch, Pitch bend, Timing clock or Program Change events MU reacted to it and receives them to all active assignments at the same time. 
I assume that there could be more affective midi event types but these ones are the most common in lots of musical instruments and controllers. 

https://user-images.githubusercontent.com/101250347/189754073-866cb6be-f68d-4e23-aa0b-6bd2affa4e36.mp4

**Comment by jessjwilliamson** [comment]
Hey Borys! I got something interesting - Thanks for your suggestion to use the same app, I had the play loop issue right? Turns out it's because there are constantly MIDI messages when I used a MIDI out and in ports to USB converter cable. 

https://user-images.githubusercontent.com/71656189/189756972-2581527e-5b75-4cfe-87ca-f867e983dfb3.mov

**Comment by abariska** [comment]
Great you catch it. That's not bad these events are sent and received but MU just should ignore them

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12
