### ISSUE TITLE
[MU4 Issue] Crash after actions with clef on staff

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#13032]
**To Reproduce**
1. Open any score (e,g, 
[Hairpins.mscz.zip](https://github.com/musescore/MuseScore/files/9434445/Hairpins.mscz.zip)
2. Select clef and in its Properties > Appearance change the Leading space parameter
3. Via Staff/part properties make clef hidden (Show Clef to False) and Apply
4. Apply Undo

**Expected behavior**
Last action is reverted in case of using Undo

**Screenshots**

https://user-images.githubusercontent.com/101250347/186940114-cdfb9059-c337-4739-8919-69516ba3cb0b.mov

**Comment by DmitryArefiev** [comment]
Fixed in #13036
