### ISSUE TITLE
[MU4 Issue] Lyrics defaulting to Lyricist Text Style

### ISSUE THREAD

**Issue by deltz025** [musescore/MuseScore#13044]
**Describe the bug**
Lyrics in MuseScore 4 are reportedly using the Lyricist style, instead of the Lyrics Odd/Even Lines styles. 

**To Reproduce**
1. Create a new score and add some notes
2. Add lyrics
3. Select a syllable, and click More... under Properties to view the Text Style

**Expected behavior**
The Text Style should be Lyrics Odd/Even Lines, depending on which verse the selected syllable is from. 

**Screenshots**
![image](https://user-images.githubusercontent.com/49649081/187031986-7d8c4242-9c7d-4fda-93b0-a836ee4d7a0a.png)

**Platform information**
 - OS: Windows 10

**Comment by cbjeukendrup** [comment]
Actually, this is a good first issue. One hint: the problem is in the UI, not in the engraving engine. Start searching in the Inspector QML files.

**Comment by Jojo-Schmitz** [comment]
You probably mean the "Poet" text style, don't you? Whoich really should get names "Lyricist" again, like it was in MuseScore 2 and 3

**Comment by Wim4rk** [comment]
Have a proposed fix brewing, but I have a question:
If I now add lyrics and click on it it says "Lyrics odd line". Well and good.
If I add a second line of lyrics, it still says "Lyrics odd line", but I can change it into "Lyrics even line".
Is that the desired behaviour, it seems a little counter-intuitive?

**Comment by Wim4rk** [comment]
Okay, I think there's two problems here. One is the lyrics/lyricist mix-up, I've fixed that.
Second, adding several lines of lyrics only results in only "odd" lines. Never even.
I poked around in `src/engraving/libmscore/lyrics.cpp`. I think line 683 always returns LYRICS_ODD...
