### ISSUE TITLE
[MU4 Issue] When removing an augmentation dot, it remains on the linked tablature

### ISSUE THREAD

**Issue by GrayCatMusic** [musescore/MuseScore#13047]
**Describe the bug**
When you remove an augmentation dot from a note in a standard notation staff, the linked tablature part keeps the dot visible on that note/number. You can manually delete the dot from the tablature. 

**To Reproduce**
Create a score with any standard notation staff with a linked staff of "full" tablature, meaning with the rhythmic notations. Place a dotted quarter, eighth note, anything on the staff. Remove the dot from the note on the standard notation. Notice the dot that remains on the tablature. 

**Expected behavior**
Most changes happen on the tablature too. 

**Screenshots**
<img width="385" alt="Screen Shot 2022-08-27 at 10 18 34 AM" src="https://user-images.githubusercontent.com/89216233/187036642-f22ec00d-f244-4478-82a4-bcd1bd66e313.png">
<img width="411" alt="Screen Shot 2022-08-27 at 10 18 44 AM" src="https://user-images.githubusercontent.com/89216233/187036644-7cc917d5-412d-4c6e-84a2-98496495253c.png">

**Platform information**
MacOC, Monterey, Intel

**Additional context**
 The same behavior happened in MS3.

**Comment by oktophonie** [comment]
Possibly related (and also not a regression, but surely not intended behaviour?), when _deleting_ a dotted rest, the rest disappears but the dot remains.

This:
![image](https://user-images.githubusercontent.com/20604032/189100088-dbcf54d8-8c7c-4ce5-974f-46a4cf03a5ae.png)

becomes this:
![image](https://user-images.githubusercontent.com/20604032/189100167-6d4fa46c-4711-47d8-be03-7b95af890e78.png)

While the rest and dot can be selected separately, and there is maybe some use in toggling visibility for them separately, it seems very strange to delete a rest but have its dot(s) remain. They should disappear, along with the rest.

**Comment by Wim4rk** [comment]
Would like to bump this issue and add that it's also impossible to make the dot invisible. See example:
![Visibility](https://user-images.githubusercontent.com/28199893/200135627-883f1280-c60f-4caf-a093-c2d34e929ba1.png)

**Comment by MarcSabatella** [comment]
FWIW, it is a temporary glitch that fixes itself on save/reload.  I recall having fixed a similar bug a few years back involving linked parts - see https://github.com/musescore/MuseScore/pull/4858 and in particular https://musescore.org/en/node/286530.  It's possible my fix for that is what broke this, or it could just be, a similar fix needs to be applied elsewhere.
