### ISSUE TITLE
[MU4 Issue] Pasting Cyrillic characters in the header crashes MS4

### ISSUE THREAD

**Issue by GrayCatMusic** [musescore/MuseScore#13046]
**Describe the bug**
When I paste Cyrillic characters into any field in the header, MS4 crashes instantly. Lyrics are ok.

**To Reproduce**
Copy Cyrillic text such as this Ukrainian song title: Була соби Маруся
Paste it into the song title or subtitle field in the header. 

**Expected behavior**
I expect to be able to paste text into the title field.

**Screenshots**
n/a

**Platform information**
macOS Monterey 12.5.1, iMac 27" 2020, 3.1 GHz 6-core Intel Core i5, 8GB memory

**Additional context**
n/a

**Comment by SilverGreen93** [comment]
Works for me in master-2f7d29c
Please provide a crash log or score.

**Comment by DmitryArefiev** [comment]
@GrayCatMusic **Can't reproduce**  on my side as well (Windows10/Mac12.5)

Can you try again in latest master please?

**Comment by GrayCatMusic** [comment]
I got it working the latest nightly build. Thanks! In the future, where can I find the crash log?

**Comment by DmitryArefiev** [comment]
> I got it working the latest nightly build. Thanks! In the future, where can I find the crash log?

@GrayCatMusic Cool! Thanks! You can use mac crash log such as that (copy text and paste it to some text file)
<img width="1000" alt="Screenshot 2022-09-16 at 18 33 42" src="https://user-images.githubusercontent.com/90187801/190676887-8ba1ca44-35da-4975-ad64-19ef0863fc5a.png">



And MS regualar logs are here ~/Library/Application Support/MuseScore/MuseScore4Development/logs/
