### ISSUE TITLE
[MU4 Issue] Low sound output level

### ISSUE THREAD

**Issue by SilverGreen93** [musescore/MuseScore#13053]
**Describe the bug**
The default volume for playback with the default instruments is very low compared to Musescore 3 or other notation software.
I have volume set to 100% in windows audio and the volume is still low even if I put dynamics such as fff.

If I use the mixer and change the volume to +10 or +12 the situation is better, but some audio clipping/distorsion may occur.

**To Reproduce**
1. Create new score
2. Select any instrument, piano, trumpet etc
3. write some notes and then play them back.

**Expected behavior**
The volume should be at a normal level.

**Screenshots**

**Platform information**
Windows 11

**Additional context**

**Comment by MarcSabatella** [comment]
It's the same for me on Linux, although not as much on Windows.

**Comment by cbjeukendrup** [comment]
Is this still actual? It seems okay for me nowadays.

**Comment by SilverGreen93** [comment]
From the time I reported this, I moved to the new MuseSounds, where things got better I think.
There are still some volume discrepancies though between Violins I and Violins II for example. I tend to increase the volume for Violins II as they are not really audible at the default level.

**Comment by cbjeukendrup** [comment]
@SilverGreen93 Thanks for your comment. I will mark this issue as completed. About balance problems within Muse Sounds, I think it is better to create a new issue for that.
