### ISSUE TITLE
[MU4 Task] [GP] Extra octave symbol "8" is imported on a rest

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#13069]
<img width="227" alt="Screenshot 2022-08-29 at 19 59 52" src="https://user-images.githubusercontent.com/24373905/187243808-576455f7-90b0-41a7-b1de-ba3f58511d37.png">

Expected behaviour: no octave symbol on rest

**Comment by alexpavlov96** [comment]
[extra_8.gp.zip](https://github.com/musescore/MuseScore/files/9446078/extra_8.gp.zip)

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/13070
