### ISSUE TITLE
[MU4 Issue] "save as default" for offset fails; always changes default to 0

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13077]
**Describe the bug**
When using the "save as default style for this score" command in Properties / Appearance / Offset, instead of making the current values the default for the score, the default is instead always changed to 0 horizontal, 0 vertical

**To Reproduce**
1. Empty score
2. Enter a staff text in both of the first two measures
3. In Properties / Appearance, change the X & Y offset to 1 and -3 respectively
4. Click "..." / Save as default style for this score
5. See error: the second staff text actually changes offset to 0, 0

**Expected behavior**
Second staff text should have changed to 1, -3 like the first.

**Screenshots**
![image](https://user-images.githubusercontent.com/1799936/187349505-d175b55d-7050-4564-9a17-f5f50b4b6a01.png)

**Platform information**
 - OS: Linux

**Additional context**
Other "save as default style for this score" commands work as expected, somehow only the offset is messed up.  But, the bug with offset applies not just to staff text but to all element types I tried.

Not sure if it's related, but after this, it also becomes hard to edit the offset via keyboard - typing new values into the spinbox doesn't seem to work as it usually does.  At least temporarily; it does fix itself.  So very likely not related, but I mention it just in case.

**Comment by MarcSabatella** [comment]
@Tantacrul could this get prioritized?

**Comment by Tantacrul** [comment]
Done. Thanks

**Comment by Tantacrul** [comment]
@oktophonie - is this one you're guys can do?

**Comment by oktophonie** [comment]
@Tantacrul We'd prefer not, as it's basically a UI matter. Strikes me as a @cbjeukendrup special, if he has the capacity!

**Comment by DmitryArefiev** [comment]
Fixed in #13521
