### ISSUE TITLE
[MU4 Issue] Chord symbol alignment settings (maximum shift above/below) have no effect

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13078]
**Describe the bug**
The style options intended to control the vertical alignment of chord symbols are not working at all

**To Reproduce**
1. Enter whole notes E5 and E6 in first two measures of score
2. Add chord symbols to both notes
3. Go to Format / Style / Chord Symbols
4. Set "Maximum shift above" to a suitable value like 5 sp
5. See error: chord symbols remain unaligned

**Expected behavior**
Entering a value of 5 sp should cause any chord symbols to align with the highest chord symbol on the system as long as it doesn't need to move more than 5 sp (this is to allow a cap on the shift amount, so a single outlier chord doesn't force everything to align ridiculously high)

**Screenshots**
![image](https://user-images.githubusercontent.com/1799936/187350325-650299d0-c2a1-4a5e-bc5f-346fc2bd8a49.png)

**Platform information**
 - OS: Linux

**Additional context**
This is meant to work for chord symbols as well as the related types - Roman numeral analysis and Nashville numbers.  Maximum shift above to control alignment above the staff, Maximum shift below for alignment below.

**Comment by oMrSmith** [comment]
> this is to allow a cap on the shift amount, so a single outlier chord doesn't force everything to align ridiculously high

Indeed, this works nicely in MU 3.6. and I think it is a very good solution! 
The only thing I could recommand is to increase the default value 
for "maximum shift above" to avoid questions ;)...

**Comment by cbjeukendrup** [comment]
@MarcSabatella Please check #13156 :)

**Comment by MarcSabatella** [comment]
Thank you!  I tested the build and it works.  I have no idea if maxFretShiftAbove is really meant to be a thing and should be considered also, though.  I could imagine it relating to GuitarPro import but not otherwise being supported in the UI.  Or just a typo.  I will assume the "MM" reference is fine, and this isn't some sort of mismatch between sp and mm but is just how things work now, because as far as I can tell it *is* working in sp units.

FWIW, though, @oMrSmith absolutely has a point that we *could* change the style default here.  We kept it at 0 - thus effectively disabling alignment - when the feature was first introduced somewhere in a 3.x release, just to avoid changing layout of existing scores.  Otherwise, I'd have been recommending we enable it by default as we do for lyrics etc.

If we're ever going to do enable this by default, now would be a great time.  One thing we *did* do was update the Jazz templates to set this, at least.  We chose 3.00 sp as the value, which seemed reasonable, although higher could be good too.  It starts to look ridiculous to allow a shift of more than 5 sp, though.

**Comment by cbjeukendrup** [comment]
About `maxFretShiftAbove`, I basically restored the situation as it was in MU3, so I don't think it has to do with GuitarPro. These settings have been available in MU3 in Format > Style > Fretboard Diagrams. 

Whether to enable chord symbol alignment by default, seems a question for @oktophonie.
