### ISSUE TITLE
[MU4 Issue] "Learn more" button (My Account page) and "Watch Video" button (Success dialog) have no actions 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13085]
[Edit by @bkunda]: The "Learn more" button on this page should link to this video on YouTube: https://youtu.be/6LP4U_BF23w

<img width="1344" alt="Screenshot 2022-08-30 at 15 06 35" src="https://user-images.githubusercontent.com/90187801/187434941-a2f722d0-fcae-4ca4-910b-eb417e177d01.png">

This same video should also be linked to the "Watch video" button on the "Success!" dialog (which appears the _first time_ the user saves a score privately to the cloud):

<img width="517" alt="Screenshot 2022-10-07 at 3 22 10 pm" src="https://user-images.githubusercontent.com/86290556/194564335-4e9c97c8-204e-42ea-92f5-a81f5a6097e8.png">

**Platform information**
macOS, Windows, Linux

**Comment by DmitryArefiev** [comment]
FYI @Tantacrul

**Comment by Tantacrul** [comment]
Assigning to myself. I may specify that this links to a video... or I'll simply specify that it gets removed altogether.

I'm moving this to Post Beta for now and made it a P1.

**Comment by cbjeukendrup** [comment]
@Tantacrul @bkunda It might be good to sort this out before the release. A button that does nothing is not great, and it is a one minute task to implement once we have the design (either hide the button or open some webpage).

**Comment by Tantacrul** [comment]
Nice catch @cbjeukendrup !

**Comment by Tantacrul** [comment]
@HemantAntony - any chance of some love?

**Comment by HemantAntony** [comment]
@Tantacrul check #14273 😁

**Comment by Tantacrul** [comment]
I'm going to bump this one over to mr @bkunda! (I've got a backlog of other PRs to check right now :) )
