### ISSUE TITLE
[MU4 Issue] AppImage won't run (2022-08-30 05:03 128M)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13081]
**Describe the bug**

The latest AppImage won't run at all. No problems with previous files.

By contrast, the previous day's nightly (2022-08-29 04:52 | 123M)  runs OK.

**Platform information**
Linux Mint 20.1.

**Comment by igorkorsukov** [comment]
fixed

**Comment by MarcSabatella** [comment]
I'm a bit confused - as far as I can tell, the latest AppImage nightly was created after that PR was merged, but it doesn't work for me either:

/tmp/.mount_MuseSce3fgh8/bin/mscore-portable-nightly: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_MuseSce3fgh8/bin/mscore-portable-nightly)

This is running on Debian "bullseye" 11.2

Is the fix going to take effect on the next nightly build, or is there a different problem now?

**Comment by cbjeukendrup** [comment]
The PR was merged today, after the latest nightly was created, so it should be okay tomorrow.
