### ISSUE TITLE
[MU4 Issue] Mapping - Active looks disabled

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#13098]
![image](https://user-images.githubusercontent.com/71656189/187684283-142989c6-0f22-4993-9e1b-a62ce6be8d17.png)

Text should be 100% opacity when active.

When it comes to design there are 2 options to approach this:

1. Keep the name 'Active' 
![image](https://user-images.githubusercontent.com/71656189/187683915-0739490d-0ec9-4c56-87a7-465d6723ddf5.png)

2. Or instead of active is can be the name of the assigned control (like Note C4 as an example)
![image](https://user-images.githubusercontent.com/71656189/187684040-1b5f99b0-24c0-430f-a52b-d3bc55328a0c.png)

I personally prefer 2nd option, would like @Tantacrul input on this please. Original designs we wanted to show the device and control name if we both agree?

**Comment by Tantacrul** [comment]
@HemantAntony - what do you think? 😆

**Comment by HemantAntony** [comment]
I made a PR #13124 :)

**Comment by Tantacrul** [comment]
Can you test @jessjwilliamson and let us know if you're happy?

Thanks @HemantAntony !
