### ISSUE TITLE
[MU4 Issue] enter chordsymbol+return assert

### ISSUE THREAD

**Issue by lyrra** [musescore/MuseScore#13105]
Enter a note,
press ctrl-k
Type in some chord symbol and press enter.
Assert.

**Comment by MarcSabatella** [comment]
But see also https://github.com/musescore/MuseScore/issues/10119 - Return is not actually *supposed* to do anything in particular here, although there are proposals for possible future behaviors.  Definitely crashes aren't good, but assert failures won't crash in release builds.
