### ISSUE TITLE
[MU4 Issue] Playback seekbar bugged on repeats

### ISSUE THREAD

**Issue by billycookin** [musescore/MuseScore#13102]
**Describe the bug**
When playback reaches the end of a score involving repeated passages, the progress indicator is not at the end of the seekbar. Instead, it indicates time remaining.

**To Reproduce**
1. Open the attached score
2. Begin playback and allow to play through score
3. By the end of the piece, the timestamp and bar number indicator are correct, but the current time indicator has not reached the end of the seekbar. It shows significant time remaining. 

**Expected behavior**
That the seekbar progress indicator would reach the end of the seekbar by the final barline!

**Screenshots**
[Anerio Factum_est_silentium.zip](https://github.com/musescore/MuseScore/files/9462202/Anerio.Factum_est_silentium.zip)
![image](https://user-images.githubusercontent.com/112558900/187699844-4894f767-f58c-496b-a7dc-6e3486b58fa6.png)

**Platform information**
 - OS: Windows 10

**Additional context**
This is in the context of other playback bugs I have encountered in this score, including: 
- the seekbar being unscrubbable (report submitted)
- multiple bars playing back simultaneously during the repeat (report not submitted as I cannot reproduce the behaviour after restarting MU4)

**Comment by DmitryArefiev** [comment]
Fixed in #14449
