### ISSUE TITLE
[MU4 Issue] [Accessibility] Style settings dialog opens slowly when screen reader enabled on Windows

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13104]
Style settings dialog opens slowly when screen reader enabled - **it takes 6-8sec**

See compare without/with Narrator

https://user-images.githubusercontent.com/90187801/187726031-e3300f5d-d218-490f-bc93-d6827206d4f9.mp4

**Platform information**
Windows10, Narrator

**Comment by Jojo-Schmitz** [comment]
I wonder whether this is related to #13193 and/or #17060
