### ISSUE TITLE
[MU4 Issue] Empty staves doesn't affect first page

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#13119]
When pressing the button 'empty staves' in properties. It is able to hide all empty staves apart from the ones in the first page.

https://user-images.githubusercontent.com/71656189/187903582-c70e0c98-d018-45b6-8100-34e5b91aa9ff.mp4

**Comment by Jojo-Schmitz** [comment]
There's another setting, "Don't hide empty staves in 1st system", on by default.

So this is by design and has been that way ever since

**Comment by jessjwilliamson** [comment]
Oh, wow, okay. hmmm.. so 'empty staves' doesn't necessarily mean all staves then as I expected.. @Tantacrul thoughts?

**Comment by Jojo-Schmitz** [comment]
I beliebe that setting triggers the same as the one from Format > Score, so yes, it would affect all but the 1st system
With the latter setting being missing in that properties side bar

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz is right. And that setting isn't even missing in the Inspector; it's just hidden in the popup behind the ⚙️ button.

**Comment by Jojo-Schmitz** [comment]
Ooops. Well hidden I must say...

**Comment by Jojo-Schmitz** [comment]
Do we still call it "Inspector"?

**Comment by jessjwilliamson** [comment]
Nope, Properties.

**Comment by Jojo-Schmitz** [comment]
Just saw it: https://musescore.org/en/handbook/4/properties

**Comment by jessjwilliamson** [comment]
So I'm just saying 'Empty staves' wording itself doesn't make sense.. at least to me anyway. Because it's like "all staves are empty apart from first page"

**Comment by Jojo-Schmitz** [comment]
It doesn't make sense in absence of that other and closely related setting, yes.

**Comment by Jojo-Schmitz** [comment]
So that'd better not be hidden

**Comment by Tantacrul** [comment]
> Ooops. Well hidden I must say...

To be fair, it's a lot more visible since it is in addition to the place where these options could only be found in MS3.

However, it's really just step 1. We want to enable the ability for users to select a page / instrument and let users hide them individually. The current options are a bit too blunt.

Don't think we should expose it up-front. Would be too noisy. Better to replace the whole thing with superior interactive options in a later release.

**Comment by Jojo-Schmitz** [comment]
It is not "first page", but "first system. In your case it it is tha same though

**Comment by Jojo-Schmitz** [comment]
Why not both: show it now and replace it for something better in a later release?

**Comment by Tantacrul** [comment]
> Why not both: show it now and replace it for something better in a later release?

Too much noise for a setting you'll only hit once. It can be found in two places. So my reason is that it's not good design.

**Comment by Jojo-Schmitz** [comment]
That dialog is not particularly busy currently, just a single setting

It will cause questions in the forum, jusl like this one here, time and time again

**Comment by Tantacrul** [comment]
If it does, we'll solve it then. Let's not fall into the trap of assuming something will be a problem and solve it by complicated the interface.

I think any option that gets added to the default inspector view needs to be a super important. It is prime real-estate.

**Comment by Jojo-Schmitz** [comment]
Then remove that single setting too. At least

**Comment by Tantacrul** [comment]
> Then remove that single setting too. At least

Not sure I follow. The 'hide empty staves' setting?

**Comment by Jojo-Schmitz** [comment]
yes. On its own it doesn't make sense. it either needs the other one (don't his in 1st system) or should not be there at all

**Comment by Jojo-Schmitz** [comment]
or trigger both, set one, unset the other

**Comment by Tantacrul** [comment]
Oh, I see. There's a setting missing? Lemme quickly look at that later (not on a computer running MS at the moment)

**Comment by Jojo-Schmitz** [comment]
Yes. "Hide empty staves" and "Don't hide empty staves on 1st system" are both on Format > Score, but should be in Properties too, as one without the other doesn't make much sense, and here triggered @jessjwilliamson to open this issue here.

**Comment by jessjwilliamson** [comment]
There's this which we are talking about:
![image](https://user-images.githubusercontent.com/71656189/187911334-e0b92f2a-68e7-401b-b35f-29a568a2c437.png)

But to hide first page/system it's here in styles > score
![image](https://user-images.githubusercontent.com/71656189/187911485-fad7ffd2-5357-4618-a8fd-4140ce2c73b7.png)

**Comment by Jojo-Schmitz** [comment]
The 3rd related setting ("Show brackets when spanning single staff") IMHO is not needed on Properties

**Comment by Tantacrul** [comment]
So, the little cog displayed next to 'Hide Empty Staves' has at least one of those options in the inspector. Right?

**Comment by Jojo-Schmitz** [comment]
It should, but apparently doesn't?

**Comment by Tantacrul** [comment]
Yeah, this guy.

![image](https://user-images.githubusercontent.com/21022311/187912077-c41944ba-620b-47c1-b351-4b46d472d9ee.png)

**Comment by Jojo-Schmitz** [comment]
OK, guess I'm looking at a too ole nightly then

**Comment by Tantacrul** [comment]
OR... perhaps I'm using an older build and the setting somehow got removed?

I'll check the latest nightly soon. If someone else could do it that'd be great.

**Comment by Jojo-Schmitz** [comment]
No, I'm just too stupid to use it. Or rather: it doesn't work in a score whei no empty staves

**Comment by Jojo-Schmitz** [comment]
Which is strange, as the Format > Score settings stuff dosn't have that restriction
