### ISSUE TITLE
[MU4 Issue] Beams position is wrong when changing "Stems position" parameter

### ISSUE THREAD

**Issue by boryskuzmenko** [musescore/MuseScore#13118]
**To Reproduce**
1. Open the score
[test_common.mscz.zip](https://github.com/musescore/MuseScore/files/9469215/test_common.mscz.zip)

2. Go to the Staff/part properties > Advanced
3. Select 'Above' for Stems position
4. Apply

**Expected behavior**
Beams and stems position is correct and just moved above the staff

**Screenshots**

https://user-images.githubusercontent.com/101250347/187897574-04ae74ae-c948-4ad5-ae12-d41f45ddeff4.mov

**Comment by asattely** [comment]
I believe this has been fixed by https://github.com/musescore/MuseScore/pull/13188. If not, let me know and I'll take another crack at it.
