### ISSUE TITLE
[MU4 Issue] Alt+Left/Right no longer navigate while entering text (or navigate between figured bass, fingering)

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13148]
**Describe the bug**
Alt+Left/Right are supposed to be available to navigate from note to note while entering staff text or other elements that don't support navigation via Space/Shift+space

**To Reproduce**
1. add several notes to score
2. select first
3. Ctrl+T to enter staff text
4. type "one", then Alt+Right
5. Result: nothing happens

**Expected behavior**
What should happen is as in MuseScore 3 - entry of the current text is completed, cursor moves on to next note to allow you to enter another staff text.  Similar to how Space works when entering lyrics.

**Platform information**
 - OS: Linux

**Additional context**
This was a very handy feature for educators adding annotations to scores

**Comment by FrancRos31** [comment]
Same issue with dinamics: alt + right/left doesn't move the selection but change the dinamic offset.
