### ISSUE TITLE
[MU4 Issue] Fretboard diagram: Clear button doesn't remove fret number

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13143]
**Describe the bug**

The fret number on a fretboard diagram remains after you press the CLEAR button (Properties: Fretboard Diagram)

**Expected behavior**

CLEAR should clear everything leaving a blank fretboard.

**Comment by MaxiSchwindler** [comment]
Is it alright if i work on this as my first issue?

**Comment by cbjeukendrup** [comment]
@MaxiSchwindler Yes, welcome!

**Comment by Tejkh1** [comment]
@cbjeukendrup Since it is inactive from 3 week can I work on this?

**Comment by Tejkh1** [comment]
@cbjeukendrup  Can I work on this, since it is inactive from long time?

**Comment by Eism** [comment]
We shouldn't reset the number, as the reset button resets user-entered markets/points with the mouse on the diagram.
Number/scale properties, etc. have their own reset buttons.

@bkunda, do you agree?

**Comment by bkunda** [comment]
I may be missing something here, but isn't this the desired behaviour?

https://github.com/musescore/MuseScore/assets/86290556/8a41b673-8c17-4ad5-8b19-0c78b9d8fcac

(OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231290303, revision: github-musescore-musescore-5fc30ff)

**Comment by cbjeukendrup** [comment]
@bkunda When you go to "Settings", you can also set a fret number. The request is that "Clear" will additionally reset this fret number, since visually/intuitively that would be what you expect. 
But @Eism on the other hand argues that it might be more consistent if the "clear" button only deletes things that are added via the "general" tab, and things in the "advanced" tab have their own reset buttons.

**Comment by DmitryArefiev** [comment]
Sorry, I missed @Eism comment and #17156 is already merged.

@bkunda Here is how it works in master and in PR's build:


https://github.com/musescore/MuseScore/assets/90187801/e6d9a135-f14e-4900-974d-8c277d351003

**Comment by DmitryArefiev** [comment]
@bkunda The argument for leaving fret number is when user just want to clear dots,x,o and leave the position, but in other way, he can leave the fret number and remove(add) dots,x,o one by one like here:




https://github.com/musescore/MuseScore/assets/90187801/cbe0e01b-2853-43a6-bf54-06d64973c581

**Comment by bkunda** [comment]
I'm actually inclined to agree with @rgreen5's proposal here, that the clear button should actually clear everything visible from the fretboard diagram. So I'm glad this has been fixed and merged!

**Comment by DmitryArefiev** [comment]
Good. Thanks!
