### ISSUE TITLE
It would be helpful to specify the note value when choosing the bpm value during score setup

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13145]
I want dotted quater notes to be 60 bpm
but can't specify this right away.

![image](https://user-images.githubusercontent.com/78870770/188269820-a504dfd2-42ca-41aa-b8dc-f70c0dbd4687.png)

**Comment by cbjeukendrup** [comment]
Good news: this has been fixed for MuseScore 4.0!
