### ISSUE TITLE
It is quite fiddly to have a single bar-line go through the whole system 

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13144]
Achieving, what is shown below, is quite fiddly,
especially when writing scores, much larger than this:

![image](https://user-images.githubusercontent.com/78870770/188269595-fb360bec-0816-4606-83a2-a2b4ab98b455.png)

Would it be possible to add a shortcut to the inspector? <3

**Comment by oMrSmith** [comment]
When I feel sad, I open this menu to witness, how simple things can be:

![image](https://user-images.githubusercontent.com/78870770/188269753-f8ad1f93-50fd-49b1-86f7-640993666ca2.png)

**Comment by MarcSabatella** [comment]
It's supposed to be as simple as holding Ctrl while dragging a barline - except currently, this crashes.

But - are you sure that is what you want?  It's quite non-standard - normally either all the barlines would extend or none. Extending all is just a matter of dragging one.  But if you do have some special reason to need to extend only a single barline  whether it's a repeat barline or any other - Ctrl normally would do the trick.

**Comment by MarcSabatella** [comment]
BTW, your screenshots are shwoing MsueScore 3.  When reporting issues here on GitHubt, you should be testing with a nightly build of MsueScore 4.

In MsueScore 3, Ctrl+drag of the barline works.  The crash is only in the nightly builds of MuseScore 4.

**Comment by oMrSmith** [comment]
> It's supposed to be as simple as holding Ctrl while dragging a barline - except currently, this crashes.

Oh this actually works for me without crashing! Just that you can't undo it the other way round...
But thanks for the tip. I'll close this then.

> But - are you sure that is what you want? It's quite non-standard
I know. But the original reason to have bar lines not go through
the whole system are lyrics when in fact lyrics seldomly cross the last bar line
so that the good reason to have the last barline in a system not go through
is often missing.

**Comment by oMrSmith** [comment]
> When reporting issues here on GitHubt, you should be testing with a nightly build of MsueScore 4.

You're absolutely right and I'll do so for the next.
