### ISSUE TITLE
Proposal: More essential selection-filters inside the inspector which are shown based on the content of the selection

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13147]
First of all:

The Selection-Filters inside the inspector are a wonderful thing!

![image](https://user-images.githubusercontent.com/78870770/188271694-b1371be3-0397-4778-a966-070ee10e9877.png)

It would vastly improve the workflow 
to simply have more essential filter options inside the inspector
like "Chord Symbols", "Dynamics...".

Also: Only those filter options should appear,
which have valid content in the selected bars.

For example: If a selection of bars doesn't contain
any grace notes, the option to filter for grace notes doesn't need to show up.

PS: IMHO the "selection filter" (F6) is not usefull
to select elements of a specific type, like all dynamics...
Actually this case doesn't work at all.

**Comment by MarcSabatella** [comment]
Your screen shot shows the MuseScore 3 Inspector; for MuseScore 4 it's already quite different, and all the relevant settings for all selected elements are already shown, no need for special buttons.

Meanwhile, while still using MuseScore 3, be aware to you can right-click a chord symbol and then Select / All Similar Elements, also restrict to just the chord symbols within the range.  or simply click one and Shift+click another to select all chord symbols in that range.

**Comment by oMrSmith** [comment]
I cannot simply download the Code (MuseScore-master) and then run it as a portable app, can I?
Sorry I'm not too familiar with Github.

**Comment by cbjeukendrup** [comment]
You can find the nightly builds here: https://ftp.osuosl.org/pub/musescore-nightlies/
Under "MuseScore 4.x (master)", go to "nightly".

**Comment by oMrSmith** [comment]
Awesome! Thx. I'll check it out.

**Comment by oMrSmith** [comment]
> MuseScore 4 it's already quite different, and 
all the relevant settings for all selected elements are already shown, no need for special buttons.

This seems to be true but not what I meant. 

If you select a range of bars it would be helpful
to limit the selection to the elements of a specific type.

Example:
You select bars 5-8 and click a button
inside the inspector "Dynamics" and
all only the dynamic symbols are selected.

**Comment by oMrSmith** [comment]
PS: To me the selection filters
seem utterly inverted.

Like if I wanted to filter chord symbols
I would have to deselect all other elemts.
Shouldn't it be the other way round?

**Comment by MarcSabatella** [comment]
As I explained above, if your goal is to *select* just chor symbols you don't need (or want) the Inspector or Properties panel at all.  Simply use one of the other two methods I gave - right-click and the Select menu, or click / Shift+click.

The selection filter is not intended for *creating* selections, only for *excluding* individual element types from an *existing* range selection, while still leaving the basic range selection intact.

I recommend you first read the relevant sections of the Handbook (eg, the section on Selection), and if you have further questions on how to use MuseScore, please use the Support forum.  The issue tracker on GitHub is really just for reporting actual bugs.  For general questions or suggestions for further discussion, that's what the forums are for.

**Comment by oMrSmith** [comment]
> As I explained above, if your goal is to _select_ just chor symbols you don't need (or want) the Inspector or Properties panel at all. Simply use one of the other two methods I gave - right-click and the Select menu, or click / Shift+click.

You're right. Closed.

**Comment by oMrSmith** [comment]
Select similar in the same staff is what I was looking for.
