### ISSUE TITLE
[MU4 Issue] Crash extending a single barline using Ctrl+drag (also with bracket/slur/hairpin grips)

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13152]
**Describe the bug**
Attempting to extend a single barline through staves using Ctrl+drag produces an immediate crash

**To Reproduce**
1. Create score for flute & trumpet
2. Click on a barline in the flute
3. Ctrl+drag the bottom handle down to extend it through to the trumpet staff
4. See error: an immediate crash (for me, it seems to happen before I even commence the drag)

**Expected behavior**
As in MuseScore 3, it should be possible to Ctrl+drag the barline down to extend it through to the staff (or multiple staves) below.

**Platform information**
 - OS: Linux

**Additional context**
Normal drag - to extend all barlines together - works fine.  Only Ctrl+drag fails.

**Comment by cbjeukendrup** [comment]
Note that it works correctly if you hit the grip but not the barline itself.

What happens, is that by Ctrl+Click the barline gets deselected, which makes the selected element a nullptr, which causes a crash later on.

**Comment by MarcSabatella** [comment]
Thanks, I can confirm that.  More particularly, I have to hit *the portion of the grip that extended below the staff* - clicking within the grip but on the staff and not on the barline is pretty tricky but seems to just deselect the barline but not allow the drag.  Could be a matter of the proximity setting for click in preferences, combined with the fatness of my mouse pointer.

I mention this because at first I was having getting the handle to stay visible, and I think this is probably something to do with why.

**Comment by DmitryArefiev** [comment]
I **can reproduce** it on all platforms


https://user-images.githubusercontent.com/90187801/188412267-04e0022c-1a8e-4a09-a86a-3fcc2da9c0b7.mp4

**Comment by oMrSmith** [comment]
Just an idea...

![image](https://user-images.githubusercontent.com/78870770/188421472-324845e2-4e34-4d47-930d-5ae31c1b25dd.png)

**Comment by DmitryArefiev** [comment]
@cbjeukendrup I also have a crash when doing Ctr+drag (Ctr+click) on bracket grip:


https://user-images.githubusercontent.com/90187801/189641710-e25fe0aa-cf1c-44b2-80ad-85967762b4c6.mp4

Is it the same issue?

**Comment by DmitryArefiev** [comment]
Cool! I'll add the summary and description. Thanks!

**Comment by oMrSmith** [comment]
Hey @DmitryArefiev 
what do you think of this idea?
![image](https://user-images.githubusercontent.com/78870770/189647662-3d2fc21d-eac4-4b90-b307-c28f695611e5.png)

**Comment by oMrSmith** [comment]
Or maybe even better:
![image](https://user-images.githubusercontent.com/78870770/189650274-f31c8282-d645-4bda-950d-19e75c1466ec.png)

**Comment by cbjeukendrup** [comment]
@oMrSmith Those ideas are very nice, only not for now 😉
Right now, we're working very focusedly on the release of 4.0, and we don't really have the time to make any non-critical changes, unless someone from the community would like to take it on. When the release is finally done, we can start making refinements and enhancements.

**Comment by oMrSmith** [comment]
I can totally comprehend that!

**Comment by oMrSmith** [comment]
I found something out:
It seems like the program only crashes when you hit CTRL
*bevor* you begin to drag the grip with the mouse.

**Comment by cbjeukendrup** [comment]
@oMrSmith Thanks! That's in line with the finding that Ctrl + hitting the element "through" the grip causes the element to be unexpectedly deselected. 

Anyway, fortunately a fix is already pending: #13302

**Comment by oMrSmith** [comment]
Ah, nice, I'm looking forward to it!
