### ISSUE TITLE
MU4 does not play glissando and first note

### ISSUE THREAD

**Issue by amijaishalev** [musescore/MuseScore#13157]
**Describe the bug**
MU4 (alpha 2) doesn't play glissando with midi (no vst), and does not play the first note of the glissando.

**To Reproduce**
1. add instrument: violin
2. insert two notes and glissando, change glissando to portamento
3. play

**Expected behavior**
MU4 should play a glissando

**Comment by wizofaus** [comment]
Can you please add a title to the issue?

**Comment by wizofaus** [comment]
Just to confirm this is purely an issue with external MIDI playback.  It works ok for internal vst playback, even if the result isn't very musical or fine-tuneable.

**Comment by cbjeukendrup** [comment]
Is this still actual in the released version?

**Comment by amijaishalev** [comment]
Yes. I downloaded from MuseHub.
Now it doesn't play portamento glissando (on Cello for example, from musesounds)

**Comment by zacjansheski** [comment]
I don't experience this issue, is it resolved or am I misunderstanding the issue?

https://github.com/musescore/MuseScore/assets/69917893/9f3fb093-aa71-4523-aa6e-7f2a5159211d

**Comment by zacjansheski** [comment]
Closing
