### ISSUE TITLE
[MU4 Request] Option for Chord Symbols to evade as a row

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13150]
In Musescore, if you move a note upwards
to collide with a chord symbol,
only the concerned chord symbol evades upwards.

In Sibelius (and Dorico) all other chord symbols of the same row
will evade upwards too, so that all chords symbols remain aligned at the same height.

It would be great to have an option to engage this behavior.

**Comment by MarcSabatella** [comment]
MuseScore supports this, you simply need to how much you wish to allow MuseScore to shift the chord symbols in Format / Style / Chord Symbols.

As mentioned elsewhere, please use the Support forum when you have questions about how to do something in MuseScore.

**Comment by oMrSmith** [comment]
I'm sorry, but I (still) can't (and couldn't) find a way to trigger this behavior 
which is default in both Dorico and Sibelius:

![image](https://user-images.githubusercontent.com/78870770/188278388-535cf2d7-3884-4fe2-978f-134014b5e455.png)

**Comment by oMrSmith** [comment]
This is how Chord Symbols evade in MuseScore:
![image](https://user-images.githubusercontent.com/78870770/188278483-3dad1853-1845-456f-aed7-7abaaf029732.png)

**Comment by MarcSabatella** [comment]
If you made the setting I told you about and and are still having trouble, again, please ask for help on the support forum.  That's the place to ask questions about how to use MuseScore - not this GitHub tracker, which has a very different purpose.

When you ask for help on the support forum, be sure to attach your score after having made the setting so we can see what is happening.

**Comment by oMrSmith** [comment]
I'm sorry, if I asked for something that should be possible already.
I'll try to find it out then. I'm aware that this is not a help forum.

**Comment by oMrSmith** [comment]
PS: Changing the shift values inside style/chord symbols doesn't change the
behavior of how chord symbols evade for me. They still don't move as a row.

**Comment by MarcSabatella** [comment]
If you mean in MuseScore 4, that's a known bug indeed - see https://github.com/musescore/MuseScore/issues/13078

**Comment by oMrSmith** [comment]
> If you mean in MuseScore 4, that's a known bug indeed - see #13078.

Ah. You filed that yourself! :D I was even searching for chord symbols
inside issues but did not associate your heading with my request...
So yes, I have already switched to the latest "nightly build".
