### ISSUE TITLE
[MU4 Issue]  A plugin's  `requiresScore: false` seems to get ignored

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#13162]
**Describe the bug**
A plugin's  `requiresScore: false` seems to get ignored, in order for such a plugin to become active in the Plugins menu a score needs to be loaded

**To Reproduce**
1. Load and and activate the [Batch Convert](https://musescore.org/en/project/batch-convert) or the [ABC Import](https://musescore.org/en/project/abc-import) plugin.
2. (Re)Start MuseScore, don't open a score

**Expected behavior**
In MuseScore 2 and 3 that setting, `requiresScore: false`, resulted in the plugin menu enty to become active even without a score being loaded

**Platform information**
 - OS: Windows (but no reason tu assume this to be different on macOS or Linux

**Comment by Jojo-Schmitz** [comment]
Example: https://musescore.org/en/project/batch-convert

**Comment by Eism** [comment]
Related to #8859, which we moved to 4.x

**Comment by Jojo-Schmitz** [comment]
I see, thanks. Makes us falling back to pre 2.x times in this respect though...

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz Could you please try #13582?

**Comment by Jojo-Schmitz** [comment]
Seems to work!
