### ISSUE TITLE
[MU4 Issue] Save to cloud does nothing

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#13167]
**Describe the bug**
Using the "save to cloud" command shows no indication that anything is saved at all, and the score is still in "unsaved state"

**To Reproduce**
1. Open/create any score, make any modification
2. Choose "Save to cloud" from File menu
3. Leave defaults and hit enter
4. Score still shows as unsaved, and closing prompts to save again

**Expected behavior**
Score should be saved or an error/informational message indicating why save failed should be shown

**Screenshots**

**Platform information**
Windows 11

**Additional context**

**Comment by Jojo-Schmitz** [comment]
I guess the backend (on musescore.com) isn't yet ready for this?
Or #13149  needs to get merged first?
