### ISSUE TITLE
[MU4 Issue] In Properties: Section break, "Measure" (US) has been replaced by "Bar" (UK)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13164]
**Describe the bug**

Even if US spelling is selected in Preferences, the word "Bar" is still used in Properties: Section break. i.e. "Reset bar numbers for new section".

**Comment by Jojo-Schmitz** [comment]
Good catch, added to #12861

**Comment by MarcSabatella** [comment]
FWIW, I brought this up here a few months ago, it was then moved to a discussion - https://github.com/musescore/MuseScore/discussions/11916

**Comment by rgreen5** [comment]
Also "Bars" is used in the "Tools"menu,

**Comment by Jojo-Schmitz** [comment]
Nope, the string "Bars" just doesn't exist in MuseScore's code

**Comment by cbjeukendrup** [comment]
This has been fixed.
