### ISSUE TITLE
[MU4 Issue] App fails to start up if recently used file can't be read

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#13161]
**Describe the bug**
If a device or network issue means a recently used file can't be read from (in my example, OneDrive had gone into "paused" state and no files from my OneDrive folder could be read), MuseScore 4 will fail to start up at all, just showing an empty frame.

**To Reproduce**
1. Start MS, open/create a score and save to a location such as OneDrive where network reads can stall/timeout
2. Shutdown the app, change OneDrive or network settings such that the file just saved to can't be read from 
3. Restart MS
4. Application never gets past splash screen, or shows empty frame

**Expected behavior**
Attempts to read from recently used files on start up should not be blocking the UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/5364225/188297458-e4e29c19-25dd-410b-9107-155854278d1b.png)

**Platform information**
 - Windows 11

**Additional context**

**Comment by DmitryArefiev** [comment]
Should be fixed by #17573
