### ISSUE TITLE
[MU4] Suggestion: Include global option to "Play Chord Symbols" in Playback Settings (Toolbar/Dropdown) 

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13174]
I think it would be quite helpful to have 
the global option to "play chord symbols"
included in this menue: 

![image](https://user-images.githubusercontent.com/78870770/188461279-02c4ef8d-183d-41d8-9331-ba818efd2cc1.png)

**Comment by oMrSmith** [comment]
Damn I see: It's in the mixer. But this still seems to be WIP, doesn't it?
Like: The mute-button for Chord Symbols doesn't work.

**Comment by RomanPudashkin** [comment]
> Damn I see: It's in the mixer. But this still seems to be WIP, doesn't it? Like: The mute-button for Chord Symbols doesn't work.

https://github.com/musescore/MuseScore/issues/12716

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/13207#issuecomment-1239203100

This option is now very important. Thanks for the suggestion!

**Comment by DmitryArefiev** [comment]
Fixed in #13228

**Comment by DmitryArefiev** [comment]
Related bug #13271
