### ISSUE TITLE
[MU4 Issue] Add - Intervals/Notes - Below doesn't work (Win/Linux)

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13172]
**Describe the bug**
Add - Intervals - Below doesn't work.
Add - Notes - Below doesn't work.

![Capture2](https://user-images.githubusercontent.com/90187801/188477583-cd3417ac-294e-4ab9-a3ab-ae7fa957ba50.PNG)

![Capture](https://user-images.githubusercontent.com/90187801/188477611-7441eaf2-b514-4436-8080-91a24b49a4a1.PNG)

**To Reproduce**
1. Select note(s)
2. Click menu Add - Intervals/Notes - Something below
3. Nothing happens

**Expected behavior**
Interval(s) below note(s) are added.

**Platform information**
 - OS: [reported on Linux]

**Comment by DmitryArefiev** [comment]
The same with Add - Notes. 
Added additional info to the description.

Thanks for logging!

**Comment by DmitryArefiev** [comment]
Related to #11947

**Comment by wizofaus** [comment]
Should be fixed by https://github.com/musescore/MuseScore/pull/13189

**Comment by DmitryArefiev** [comment]
Fixed in #13189
