### ISSUE TITLE
[MU4 Issue] Note doesn't stop playing when some of articulations assigned

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#13185]
**Describe the bug**
Issued articulations:
- Laissez vibrer 
- harmonic
- up bow
- down bow
- fade in 
- fade out
- volume swell
![CleanShot 2022-09-06 at 00 04 46](https://user-images.githubusercontent.com/101250347/188513027-b810ed22-c993-46cf-8a6e-a5bf1ddc0ff0.png)

**Expected behavior**
Note keeps playing according to its duration and articulations assigned

**Screenshots**

https://user-images.githubusercontent.com/101250347/188513280-7baec041-556f-4eea-90de-d5db963a964b.mp4

**Comment by rettinghaus** [comment]
This is something I would expect on applying a _laissez vibrer_ (although it indeed sounds weird with trumpet sound).

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 13

The main issue with note durations is fixed. All other related issues to be reported separately.
