### ISSUE TITLE
[MU4 Issue] Playback is not started from the selected note

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#13184]
**Describe the bug**
This issue is about the case when playback stopped and already selected note is clicked. In this case playback keeps playing from the note which was stopped on

**To Reproduce**
1. Create a simple score
2. Select any note and start playback (leave the note selected)
3. Stop playback
4. Click the note once again

**Expected behavior**
Playback starts from the selected note

**Screenshots**

https://user-images.githubusercontent.com/101250347/188511843-50663059-d2be-406b-a450-601e80f37a51.mp4

**Platform information**
 - OS: macOS

**Comment by wizofaus** [comment]
Not so surprising, as clicking on an already selected note is not indicating any sort of "change" to the score or selection state.  However v3 does follow this behaviour so it seems worth preserving.

**Comment by boryskuzmenko** [comment]
This is a regression after some fixes during last week. 
It works as expected on the master for September 1

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
