### ISSUE TITLE
[MU4 Issue] Notes hang for a long time under various circumstances

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#13203]
**To Reproduce**
1. Open the score 
[Mozart_Symphony_No._40_in_G_Minor_K._550_I._Molto_Allegro 3.mscz.zip](https://github.com/musescore/MuseScore/files/9498061/Mozart_Symphony_No._40_in_G_Minor_K._550_I._Molto_Allegro.3.mscz.zip)

2. Play it back
3. Move the cursor to measure 200
4. Pay attention to the playback

**Expected behavior**
Playback goes as expected

**Screenshots**

https://user-images.githubusercontent.com/101250347/189615902-5716c209-141b-41e4-a655-454072549586.mp4

**Comment by abariska** [comment]
Oh, my fault. Video is replaced

**Comment by DmitryArefiev** [comment]
@vpereverzev The similar issue with appoggiaturas (the 2nd measure):


https://user-images.githubusercontent.com/90187801/191723574-95702fdf-c9d8-4e5b-a469-f4856dc23d81.mp4


[grace notes.zip](https://github.com/musescore/MuseScore/files/9624772/grace.notes.zip)

If it's not the same I'll log it separately

**Comment by Tantacrul** [comment]
@DmitryArefiev @abariska - we suspect this _might_ be fixed now. Can you retest your examples?

**Comment by abariska** [comment]
@Tantacrul unfortunately, still reproducible in both cases

**Comment by Tantacrul** [comment]
OK thanks!

**Comment by DmitryArefiev** [comment]
Fixed in #13798
