### ISSUE TITLE
[MU4 Issue] Chords on one staff stop playing after adding chords to another

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13207]
.**To Reproduce**
1. Open [2 guitars.zip](https://github.com/musescore/MuseScore/files/9499283/2.guitars.zip)
2. Add one chord to Guitar 2
3. Play score - **now the chords from Guitar 1 don't play back**

https://user-images.githubusercontent.com/90187801/188698060-c1467994-59d6-4f28-9ff2-d56c866fa8aa.mp4

After reopening score, chords playback on both staves

**Platform information**
macOS, Windows, Linux

**Comment by Tantacrul** [comment]
To fix this quickly (after chatting with Roman) I'm thinking the following:

- Each instrument with chords creates a new 'chords' track in the mixer
- The 'chords' track appear on the right, next to the Master fader
- Naming convention should stay as 'Chord Symbols' for now (we'll revise this more significantly in later releases)
- For the moment, all chords should play using the piano by default, although users can specify different VST's for them (or Muse Sounds) if they like.
- There'll be a 'Play Chord Symbols' option next to the 'Play Repeats' option, accessed from the Cog on the Play panel. @jessjwilliamson / @bkunda: we'll need a symbol for this option.

**Comment by DmitryArefiev** [comment]
Fixed in #13228
