### ISSUE TITLE
[MU4 Issue] [GP] Some note pitches are too high

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#13210]
**Describe the bug**
Sometimes guitar pro pitches are set too high, which is a mistake (cannot even be edited in guitar pro)
MU treats them as "red notes" but they can cause problems

**To Reproduce**
[red_import.gp.zip](https://github.com/musescore/MuseScore/files/9499443/red_import.gp.zip)
Open attached file
Strings are red

**Expected behavior**
Note pitches are in possible range during gp import

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
