### ISSUE TITLE
[MU4 Issue] Save As command deletes the initial score from disk

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13213]
**To Reproduce**
1. Create score
2. Save it as '1'
3. Reopen 
4. Using **Save as**, re-save it as '1a' - **score '1' is deleted from disk and both scores are empty in Recent scores** 
 

https://user-images.githubusercontent.com/90187801/188708418-71fb4ff9-92a9-4960-928d-57c50e38c494.mp4

**Platform information**
Windows, Mac, Linux

**Comment by HemantAntony** [comment]
@DmitryArefiev I made a PR: #13217 :)

**Comment by DmitryArefiev** [comment]
Fixed in #13217

**Comment by DmitryArefiev** [comment]
@HemantAntony Thanks for fixing!
