### ISSUE TITLE
[MU4 Task] 'Download' button on Onboarding Screen should now redirect to a YouTube video

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#13212]
**Task description**
When the user clicks the 'Download' button in our onboarding screen (image below), we need to hook it up to the Muse Hub:

<img width="865" alt="image" src="https://user-images.githubusercontent.com/21022311/188704863-3697d44d-4513-4d4c-99e2-8675b0386030.png">

Here's what would be ideal behaviour. Please let me know if it is doable.

1. Change the text from '**Download**' to '**Watch video**' (We should already have the translated strings for this)
2. It should link to here: https://youtu.be/n7UgN69e2Y8

**Comment by Tantacrul** [comment]
Update: I'm going to create a very short video for this to link to. The 'Download' button will change to 'Watch video'.

Will create the video today and will be finished in the next 2-3 days. Will update here.

**Comment by Tantacrul** [comment]
OK, I've updated this task to make it super simple :)

**Comment by HemantAntony** [comment]
@Tantacrul made a PR: #13310

**Comment by Tantacrul** [comment]
Perfecto. Thanks, @HemantAntony !
