### ISSUE TITLE
[MU4 Issue]Reloading the plugins is not reflected on the Plugins panel

### ISSUE THREAD

**Issue by lgvr123** [musescore/MuseScore#13220]
In the Plugins, panel, the button "Reload Plugins" has no visible effect.

Two ways to reproduce it:

1) Go in Preferences, select another folder for hosting the plugins (that may or nor contains actual plugins)
2) Go in Plugins, reload the plugins. The list of (user) available plugins has not changed.

-- Alt --
1) In an explorer, open the folder set has the one containing the user plugins, add or remove some plugins
2) Go in MuseScore, Plugins panel, reload the plugins. The list of (user) available plugins has not changed.

The only workaround is to close MS4 and reopen it in order to see the changes.

**Comment by Jojo-Schmitz** [comment]
Related to #8859, which has been moved to 4.x

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/363753

**Comment by wizofaus** [comment]
Happy to look at this
