### ISSUE TITLE
[MU4 Issue][Plugins]The plugins system presents as plugin qml files that are not plugins

### ISSUE THREAD

**Issue by lgvr123** [musescore/MuseScore#13221]
If a plugin is using some custom components defined in qml files, the plugins system will consider those components as valid plugins.

##Example##
The attached is structured in the following way:
```
+ mcveMS4.qml // main plugin code
+ mcveMS4/SmallCheckBox.qml // custom QML component
```

MS4 sees both `mcveMS4.qml` and `SmallCheckBox.qml` as plugins, in both in Plugins panel and the plugin menu:

![SmallCheckBox as a plugin](https://user-images.githubusercontent.com/50494/188855868-40ecac60-7c7b-456d-9958-feff84c9f062.png)

A solution would be to consider as plugins the qml files containing the `Musescore` object.

-----
Plugin : [plug4ms4.zip](https://github.com/musescore/MuseScore/files/9505907/plug4ms4.zip)

**Comment by Jojo-Schmitz** [comment]
That proposed solution is IIRC what MuseScore 2 and 3 used. I'm puzzled that MUseScore 4 doesn't

**Comment by Jojo-Schmitz** [comment]
Related to #8859, which has been moved to 4.x

**Comment by lgvr123** [comment]
EDIT: updated the plugin zip after correction of a typo

**Comment by XiaoMigros** [comment]
I've not had this issue with the files you provided, nor with any of my own plugins

**Comment by lgvr123** [comment]
Me neither. Looks like it has been fixed.

**Comment by XiaoMigros** [comment]
Probably worth closing the issue then
