### ISSUE TITLE
[MU4 Issue] Parts are not deleted after deleting those instruments from score

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13239]
**To Reproduce**
1. Create score with some instruments 
2. Open all parts
3. Close all parts
4. Delete some instruments from score
5. Add new instruments to score
6. Open parts - **deleted instruments in step 4  are still there**

https://user-images.githubusercontent.com/90187801/189067301-3d4d9a99-b785-4175-b7ac-53b1d3255578.mp4

**Expected result**
Conditions: Wind Quartet score (Flute, Oboe, Clarinet, Bassoon)

If **Flute part contains only Flute** instrument inside, removing Flute from score closes and **deletes Flute part**
If **Flute part contains Flute+Oboe+Calrinet** instruments inside, removing Flute from score **deletes ONLY Flute instrument from Flute part**

**Platform information**
macOS, Windows, Linux

**Comment by sammik** [comment]
May be different issue, but I think, it is related to this one:

If parts are not closed, and instrument is removed, part shouldnt be removed, but should became empty, see [comment](https://github.com/musescore/MuseScore/issues/10478#issuecomment-1036282928)

Now, part is not empty, contains unexisting /removed/ instrument

https://user-images.githubusercontent.com/1646034/192358171-5893579d-804f-4369-9847-558000a3c524.mp4

**Comment by Tantacrul** [comment]
> FYI @Tantacrul I've added expected result in two scenarios
> 
> Conditions: Wind Quartet score (Flute, Oboe, Clarinet, Bassoon)
> 
> If **Flute part contains only Flute** instrument inside, removing Flute from score closes and **deletes Flute part** If **Flute part contains Flute+Oboe+Calrinet** instruments inside, removing Flute from score **deletes ONLY Flute instrument from Flute part**

Yeah, I guess that makes sense logically, although I can't imagine a use case for that. I'm guessing you've seen issues like this with Sibelius in the past? Perhaps there's a reason to do this I've not yet thought of :)

Anyway, I see no reason to argue with you. Thanks!

**Comment by DmitryArefiev** [comment]
@Tantacrul Sibelius works differently with parts which generated automatically. In case like described above you can't add other instruments to **Flute** part, you should create a new part (custom) which you can modify by adding instrument from score.

So, in our case we should keep in mind more cases when deleting instruments from score and how those changes reflected in parts. Anyway we can change that logic (expected result in current PR) in future :)

**Comment by DmitryArefiev** [comment]
oh.. I was wrong.. in Sibelius, you can modify autogenerated part and add some instruments but via additional dialog. 
But the logic when deleting instruments is the same as we want to implement in current PR.

**Comment by DmitryArefiev** [comment]
Fixed in #14288

**Comment by DmitryArefiev** [comment]
It is still an issue in custom part. I'll log it separately

**Comment by Tantacrul** [comment]
> It is still an issue in custom parts. I'll log it separately

I suspect for custom parts, we don't really need to prioritise that for Release, right? We could give it a P1 (or P0) and put it in Post Release?

**Comment by DmitryArefiev** [comment]
Yeah, absolutely agree!
