### ISSUE TITLE
Appending a vertical frame at the end of the score bypasses "Last system fill threshold"

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13243]
I set up my test-score so that systems justify on the entire page.

To avoid the effect of system-justification on the very last page, I appended a vertical frame.

Doing so will bypass the setting for "Last system fill threshold".

https://user-images.githubusercontent.com/78870770/189100718-8851cd20-a120-435c-8092-f363f61b8b09.mp4

I guess the workaround is to add a horizontal frame after the last system,
but it still looks like a small bug to me 
as the last system is still the last system...

**Comment by Jojo-Schmitz** [comment]
Same in MU3. Actually a frame is a segment, just like a measure, so now it isn't the last segment anymore. At least I thing this is what it is.
Other workaround is to use a spacer.

**Comment by Jojo-Schmitz** [comment]
Similar effect after a section break, there too the last system threshold isn't honored

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.org/en/handbook/4/using-frames-additional-content#frames-between-systems
So don't use frames for spacing between or after systems

**Comment by oMrSmith** [comment]
I see. Thanks for the tip with the spacer! I hadn't filed it,
if the the option would have been called like "Last segment fill threshold" ;).
