### ISSUE TITLE
[MU4 Issue] Missing dialog message content for when adding certain text elements without selection

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13248]
**Describe the bug**
This dialog is triggered when attempting to add a text element without a note/rest selection:

<img width="310" alt="Screenshot 2022-09-08 at 3 46 04 pm" src="https://user-images.githubusercontent.com/86290556/189140291-8462d638-4f97-44f0-9806-cf68c98383f6.png">

The dialog is missing critical message content.

This relates to all of these text elements (except "Figured bass", which for some reason is still returning the correct dialog messaging):

<img width="217" alt="Screenshot 2022-09-08 at 3 54 28 pm" src="https://user-images.githubusercontent.com/86290556/189140719-a4a7339a-a261-4318-a050-ca0776aa4aaf.png">

**To Reproduce**
1. Create a new score
2. Select Add > Text > System text 
3. See above faulty dialog
4. Repeat for other text elements in the same menu

**Expected behavior**
This dialog should be triggered when attempting to add one of the above text elements and when no note/rest is selected:

<img width="474" alt="Screenshot 2022-09-08 at 3 57 47 pm" src="https://user-images.githubusercontent.com/86290556/189141336-87b2ff20-3e9b-4d7c-ba23-30ec5694daee.png">

**Platform information**
 - MacOS 12.3.1 (M1)
 - Windows 11

**Comment by HemantAntony** [comment]
@bkunda are you sure a dialog like this is needed in the first place. I remember talking about this in separate issue. It was sort of agreed on that a dialog is not really needed. See https://github.com/musescore/MuseScore/issues/10888#issuecomment-1079021187

**Comment by Tantacrul** [comment]
I think in this instance the dialog is needed because the rules behind when you can / can't add text are quite unintuitive.

I get caught by this problem a lot. So... we should do exactly what is suggested in @bkunda's description.

In future, we'll just change the behaviour to avoid this problem. However, we don't do it until 4.x

Nice catch @bkunda !

**Comment by Tantacrul** [comment]
@RomanPudashkin - back to you

**Comment by HemantAntony** [comment]
@bkunda Please check #13280
