### ISSUE TITLE
[MU4 Issue] Learn>Classes: Open Mastering MuseScore button is unreachable on high scaling (Mac mostly)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13244]
**Describe the bug**
Learn>Classes: **Open Mastering MuseScore** button is **unreachable** on high scaling (Mac mostly)

Probably adding ability to scroll (like on Get started page) can fix the issue

**Default:**

![Screenshot 2022-09-08 at 14 36 10](https://user-images.githubusercontent.com/90187801/189115980-c432e662-d13a-4981-bd8b-e7a1376aeb6a.png)

**Larger Text:**

![Screenshot 2022-09-08 at 14 35 56](https://user-images.githubusercontent.com/90187801/189116179-f4ba9025-3b78-4dec-9ccc-13540b443d03.png)

![Screenshot 2022-09-08 at 14 39 25](https://user-images.githubusercontent.com/90187801/189116230-02340d77-e657-45f7-b0b6-5a7e93efcc5b.png)

**Platform information**
macOS 12, MacBook Air M1 13"

**Additional context**
Can be noticeable on Windows on 200-250% on narrow displays

**Comment by DmitryArefiev** [comment]
https://user-images.githubusercontent.com/90187801/189116599-1b3b163e-f2f2-442b-928a-8b86e996e42e.mov

**Comment by cbjeukendrup** [comment]
Also reproducible by just resizing the window to a small vertical size. Easier and less dangerous than changing display resolution :)

We simply need to wrap the view in a scrollable view, so this seems a good first issue to me.

**Comment by Jojo-Schmitz** [comment]
You still need good first issues? ;-)

**Comment by DmitryArefiev** [comment]
Fixed ([see comment](https://github.com/musescore/MuseScore/pull/15585#issuecomment-1666906820))
