### ISSUE TITLE
[MU4 Issue] Clef modified offset position is lost after hiding and Undo

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13266]
**Describe the bug**
See https://github.com/musescore/MuseScore/pull/13036#issuecomment-1241229724

**To Reproduce**
1. Select clef 
2. In Properties > Appearance, modify "Offset"
3. Staff Part Properties > disable "Show clef"
4. Undo

https://user-images.githubusercontent.com/90187801/189364669-e2b93c8b-646b-4f87-9fc8-0969c4bc0328.mp4

**Actual:**
 Clef comes back but **offset is lost** (and technically, it's a different clef, but that doesn't matter from user POV)

**Expected:** 
Clef comes back and it's properties are the same as before (modified offset is kept)

**Platform information**
 macOS, Windows, Linux

**Additional context**
This also occurs in **MU3**.

In MU3, if you press undo multiple times instead of once, a crash will occur, but in MU4 this crash does not occur; instead, nothing happens.

**Comment by HemantAntony** [comment]
@DmitryArefiev I got a crash when trying to do this lol

**Comment by DmitryArefiev** [comment]
@HemantAntony That's correct! Crash is fixed in #13036

**Comment by HemantAntony** [comment]
Ah I didn't follow that thread :)

**Comment by DmitryArefiev** [comment]
NP :)

**Comment by cbjeukendrup** [comment]
Duplicate of #17482
