### ISSUE TITLE
[MU4 Issue] Shortcuts for Move pitch up/down an octave don't work for range selection 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13262]
**Describe the bug**
Shortcuts for Move pitch up/down an octave don't work for range selection (Ctr/Cmd+up/down)

**To Reproduce**
1. Select measure with some notes
2. Try to move them up on octave by using Ctr/Cmd+↑ - **notes stay at the same pitch and clef is selected**

https://user-images.githubusercontent.com/90187801/189325700-3893487c-4993-4cba-9e95-e3e2b9de9f70.mp4

**Platform information**
 macOS, Windows, Linux

**Additional context**
Recent changes
Works with single note selected

**Comment by HemantAntony** [comment]
@DmitryArefiev check #13267

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev check #13267

@HemantAntony Yeah, looks good! Thanks!

**Comment by DmitryArefiev** [comment]
Fixed in #13267
