### ISSUE TITLE
[MU4 Proposal] Allow to enter rests by pressing SPACE while note-input mode is active

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13275]
(... without reserving the shortcut)

With the left hand on the computer-keyboard to select note durations
and the right hand on either virtual or midi-keyboard,
it would feel absolutely intuitive to me
to enter rests by hitting SPACE with the thumb of my left hand. 

I know: Space is used to play or stop.

However: I think it is more likely to enter a rest 
than wanting to press play
during active note input.

**Comment by MarcSabatella** [comment]
FWIW, I think I recall it having worked that way at one time, but there were enough complaints about not being to start playback from note input mode that the shortcut was changed to 0.  Is this harder than hitting Space, or were you perhaps unaware of that shortcut?

Meanwhile, you're free to redefine rest to be space if you like, in Edit / Preferences / Shortcuts.  But indeed,d it will define it is normal mode as well.

**Comment by oMrSmith** [comment]
> I recall it having worked that way [...], but there were enough complaints about not being able to start playback from note input mode

Ah, I see. Then I'll just put "play" on "P" or "enter rest" on "CTRL+P" or so... ;)
"0" is good when using the numpad as you don't have to look at the keyboard during note input,
but I actually prefere using the other numbers as their alignement is just like the notes values are displayed...

**Comment by MarcSabatella** [comment]
Is 0 not right next to P on your keyboard?  It is on mine, so hitting 0 vs P is six of one, half dozen of the other.  But different keyboards are laid differently, so customizing shortcuts is quite useful

**Comment by oMrSmith** [comment]
Yes it is! But I don't press play very often, so I don't mind looking at the keyboard when doing so.
Entering notes on the other hand, I like to be like playing counter strike ;) 
Wanna keep my eyes on the screen and have all the fingers in place...
It could be an option for more nerdy users, but it doesn't seem urgent 
if the user-majority has complaint anyway...

**Comment by oMrSmith** [comment]
PS: @MarcSabatella, will the possibility to have different shortcuts for one command be taken out in MU4?

**Comment by MarcSabatella** [comment]
Yes, that seems to be the plan.
