### ISSUE TITLE
[MU4 Issue] Typing values into style fields triggers updates on each keystroke

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#13276]
**Describe the bug**
Perhaps more of a request or suggestion than a 'bug', but I'll explain why it is a problem.

For example: let's say I want to change my page width to 184mm. I open format > Page settings and select the value currently in the page width field (210mm) for me.

I can get the width I want by typing "184". But the score updates on every keystroke, and other settings can be affected too. In this case, as soon as I type "1", the score becomes 1mm wide, and also the _margins_ become 1mm (constrained as such by the width):

![image](https://user-images.githubusercontent.com/20604032/189477735-4a5c60b1-d8a7-4765-bcb3-d261001b820b.png)

and when I type the "8" and "4" the margins obviously do not increase again, so while I have successfully set my desired page width, my margins are now messed up.

This applies to all fields in the Page settings dialog and also the main Style dialog.

As well as being annoying, a full recomputation of the score layout happens with each keystroke too. In the case of a large, complex score this can be very slow, and if you are typing multiple digits into a style field, you are likely to see nonsense until they are all typed (plus it runs the risk of messing the layout up in unpredictable ways).

Would it be possible for the 'value updated' message to be sent not on every keystroke, but only by some appropriate trigger, for instance tabbing or clicking away from the field?

**Comment by oMrSmith** [comment]
Here comes another idea:

![image](https://user-images.githubusercontent.com/78870770/189478603-adb223c2-1a8d-476c-9862-e8dc95e1700d.png)

If you would exclude the unit from the field,
entering values would be even faster.

**Comment by wizofaus** [comment]
I'd certainly call it bug if you can't type in a new page width without having your margins changed to something impractical in the process.  The question is what the desired behaviour is - either use debounce (wait a small period before updating) or require a focus change.

**Comment by Tantacrul** [comment]
Yes. This is extremely annoying. The update should occur after the user clicks on another field or presses 'OK', etc. It should not update with every digit added.

**Comment by HemantAntony** [comment]
@oktophonie Check #15107

I have removed all updating for both Page Settings and Style Dialogs. I didn't test all of it. But I'm confident :)

**Comment by MarcSabatella** [comment]
How about instrument names?  That's where I experience this most, trying to rename an instrument and having to wait after each letter.

**Comment by HemantAntony** [comment]
@MarcSabatella @oktophonie Here?
![image](https://user-images.githubusercontent.com/88136054/207053973-445b2dfa-39a2-4bf9-bfe6-ca46b766a976.png)

**Comment by MarcSabatella** [comment]
Yes

**Comment by HemantAntony** [comment]
@MarcSabatella @oktophonie I have updated my PR. It should include that now :)
