### ISSUE TITLE
[MU4 Issue] Freezing and crash when entering capital letter b in chord symbol

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13272]
**Description**
User can use capital letter mode accidentally for b (flat) when trying to enter Cb 

**To Reproduce**
1. Select note
2. Enter chord input mode (Ctr/Cmd+K)
4. Enter "cB" and hit Space

https://user-images.githubusercontent.com/90187801/189394263-910aa5da-ebb1-414e-b9e1-168556a07e78.mp4

**Platform information**
macOS, Windows, Linux

**Comment by wizofaus** [comment]
I think you mean Ctrl+K not Ctrl+N? Curiously if you press that before selecting anything you get:

![image](https://user-images.githubusercontent.com/5364225/189511946-ccefd6cf-0a3b-4129-8685-8e9ecd27f20c.png)

which should probably be reported separately.

Anyway yes, it's a bug in String::replace(...)  (why are we even writing code like that, there are so many standard library functions that do it?), that goes into an infinite loop if the string being replaced with is empty.

**Comment by DmitryArefiev** [comment]
> I think you mean Ctrl+K not Ctrl+N? 

Yeah, I made a typo.. Corrected. Thanks!

Curiously if you press that before selecting anything you get:
> 
> ![image](https://user-images.githubusercontent.com/5364225/189511946-ccefd6cf-0a3b-4129-8685-8e9ecd27f20c.png)
> 
> which should probably be reported separately.

I see you are already logged #13286 Thanks!

> Anyway yes, it's a bug in String::replace(...) (why are we even writing code like that, there are so many standard library functions that do it?), that goes into an infinite loop if the string being replaced with is empty.

Thanks for fixing! I will check it after code review

**Comment by Tantacrul** [comment]
On behalf of every here, can I just say: lol.
