### ISSUE TITLE
[MU4 Issue] Apply current palette element command not implemented

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13281]
**Describe the bug**
MuseScore 3 had a command "apply current palette element" to easily reapply the most recently-used palette element.  This was a great usability feature and especially valuable for blind users even though it had no default shortcut.  This command is missing in MU4.

**To Reproduce**
1. Go to Edit / Preferences / Shortcuts
2. Search for "palette"
3. See error: no "Apply current palette element" command available

**Expected behavior**
The "apply current palette element" should be available, and ideally, should have a default shortcut assigned even though there was none in MU3.  FWIW, I normally used "\\".

**Platform information**
 - OS: Linux

**Additional context**
I know there is some new functionality coming for shortcuts via the GSoC project, but on the assumption that none of the pending work for that is being targeted for 4.0, re-implementing this one command would be a big help for now.

There are a handful of other commands that were dropped from MU3, some consciously, some perhaps less so.  This to me is the one most worth adding back for 4.0.

**Comment by wizofaus** [comment]
You normally used ""?
There is still "applyCurrentPaletteElement" in PalettesPanel.qml but nothing calling it...hard to judge whether it will actually work.

**Comment by MarcSabatella** [comment]
Sorry, I typed a backslash but GitHub ate it.  Fixed now.

**Comment by MarcSabatella** [comment]
I can make an attempt, if I can get a little help.  I knew how things worked in MU3 but it still is a lot of trial and error for me in MU4.

@wizofaus - I assume you're talking about the code here:

https://github.com/musescore/MuseScore/blob/master/src/palette/qml/MuseScore/Palette/PalettesPanel.qml#L46-L47

It looks like the actual work then is done here:

https://github.com/musescore/MuseScore/blob/master/src/palette/qml/MuseScore/Palette/internal/PaletteTree.qml#L111-L120

which looks about right to me (not that I know my way QML at all).  So, it seems promising.

In theory, then, all we'd need to do is make sure the command exists and calls the applyCurrentPaletteElement function.  The place where the command would be to be defined, I assume, is here:

https://github.com/musescore/MuseScore/blob/master/src/palette/qml/MuseScore/Palette/PalettesPanel.qml#L46-L47

And then after defining tyhe command itself there, I'd need to register it here:

https://github.com/musescore/MuseScore/blob/master/src/notation/internal/notationactioncontroller.cpp

That last part is the mystery to me - I have no idea what magic it would take to actually reference the applyCurrentPaletteElement function here.

**Comment by cbjeukendrup** [comment]
@MarcSabatella You could use the `"palette-search"` action as an example.

The class `PaletteRootModel` is instantiated in QML, and registers itself as a handler for this action. When the action is called, the model emits a signal, namely `paletteSearchRequested()`. 
https://github.com/musescore/MuseScore/blob/644cc1237216136d917dae1b4d66e97426f341c2/src/palette/view/paletterootmodel.cpp#L26-L32

In QML, there is a handler for this signal; in this handler, the relevant function in QML is called.
https://github.com/musescore/MuseScore/blob/644cc1237216136d917dae1b4d66e97426f341c2/src/palette/qml/MuseScore/Palette/PalettesPanel.qml#L62-L68

So, you can basically just copy & paste the handler registrations and fill in the correct names, action code and QML function.

**Comment by MarcSabatella** [comment]
Great, that gets me started!  Signals, yeah, makes sense.  I'll give it a shot.

BTW, the palette search command is actually defined in the palette code but I had been thinking it made sense for the apply current palette element command to be defined in notation, since that's where the focus would be on executing it and where action would actually take effect.  But maybe I'll try it all here in the palette code first.

**Comment by wizofaus** [comment]
I'd expect it to be in the Palette code - I wouldn't think the Notation code should depend on/ know about the Palette generally.
