### ISSUE TITLE
[MU4 Issue] Changing measures duration messes up playback

### ISSUE THREAD

**Issue by PetJer** [musescore/MuseScore#13288]
**Describe the bug**
Changing measures duration (CTRL+DEL / measure properties) messes up playback (*).

**To Reproduce**

1. Fill *x* measures full of notes
2. Change the duration of all the measures
3. Play -> at some point onwards some notes are repeated

**Examples**

https://user-images.githubusercontent.com/79419198/189962282-fd4bd0bf-59c5-48c6-b3ec-2cb92f2136ee.mov

https://user-images.githubusercontent.com/79419198/189961814-787df61a-43ed-490f-a6ea-9fdee70855c8.mov

**(*) If you fill a measure and change the duration immediately (instead of changing it after all measures are filled) the playback works normally**. 

https://user-images.githubusercontent.com/79419198/189961536-5da018ea-89da-4f11-b3f3-f923584147a6.mov

**Expected behavior**
None of the notes should be played again.

**Platform information**
- Windows 11

**Comment by oMrSmith** [comment]
You have in fact shortened each bar,
which the bar shows with the grey little minus symbol.
A wasn't aware of this hack!

**Comment by oMrSmith** [comment]
I wasn't aware that I can shorten bars that easily! That's a cool hack.

**Comment by wizofaus** [comment]
Hi, could you please use the template provided and fill out repro steps/expected behaviour etc.

**Comment by PetJer** [comment]
Sure, I'll update it. I also found up that the problem arises because of the change in the **measures duration**.

**Comment by cbjeukendrup** [comment]
I can't reproduce this anymore, so maybe it is fixed. @PetJer could you please verify that?

**Comment by PetJer** [comment]
@cbjeukendrup I can't reproduce it, too. This issue was reported in the alpha version, so it seems that it was fixed along the way.
