### ISSUE TITLE
[MU4 Issue] Reset Preferences crashes app if a part with no instruments is open

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#13297]
**Describe the bug**
If you've created an "empty" part with no instruments, reset preferences causes the app to crash.

**To Reproduce**
1. Open/create any score
2. From the Parts dialog, click Create New, then open selected.
3. Go to Edit|Preferences and select "Reset preferences"
4. App crashes

**Expected behavior**
App does not crash

**Screenshots**

**Platform information**
Windows 10

**Additional context**
Built from master branch, 12-Sep-2022.
Stack trace:

Exception thrown: read access violation
*this* was nullptr

>	MuseScore4.exe!mu::engraving::Score::doLayoutRange(const mu::engraving::Fraction & st, const mu::engraving::Fraction & et) Line 5500	C++
 	MuseScore4.exe!mu::engraving::Score::doLayout() Line 5493	C++
 	MuseScore4.exe!mu::notation::Notation::{ctor}::__l2::<lambda>(mu::framework::Orientation __formal) Line 95	C++
 	[External Code]	
 	MuseScore4.exe!deto::async::Channel<enum mu::framework::Orientation>::ReceiveCall<void <lambda>(mu::framework::Orientation),enum mu::framework::Orientation>::received(const deto::async::NotifyData & d) Line 80	C++
 	MuseScore4.exe!deto::async::Channel<enum mu::framework::Orientation>::ChannelInvoker::doInvoke(int callKey, void * call, const deto::async::NotifyData & d) Line 127	C++
 	MuseScore4.exe!deto::async::AbstractInvoker::invokeCallback(int type, const deto::async::AbstractInvoker::CallBack & c, const deto::async::NotifyData & data) Line 62	C++
 	MuseScore4.exe!deto::async::AbstractInvoker::invoke(int type, const deto::async::NotifyData & data) Line 45	C++
 	MuseScore4.exe!deto::async::Channel<enum mu::framework::Orientation>::send(const mu::framework::Orientation & <d_0>) Line 32	C++

This is because m_score is actually nullptr for the Notation object which sets up a "canvasOrientation" receiver (so this would likely happen when changing canvas orientation, and potentially other operations). I'm not sure if we should ever have a Notation object with m_score being nullptr, but obviously it is happening so we should handle it.

**Comment by DmitryArefiev** [comment]
Fixed in #13298
