### ISSUE TITLE
[MU4 Issue] Weird pop-up menu locations 

### ISSUE THREAD

**Issue by kislenok-roman** [musescore/MuseScore#13290]
All menu popups opens in unexpected locations, sometimes near the triggering element, sometimes far away.

**To Reproduce**
1. Open MuseScore
2. Click on menu

**Expected behavior**
Menu should be located near the triggering element.

**Screenshots**
![image](https://user-images.githubusercontent.com/5051096/189527681-6216111a-6a4f-4e40-9839-1a73b904c7f4.png)
![image](https://user-images.githubusercontent.com/5051096/189527684-0889b9bd-3b80-4975-89de-a19a6e988768.png)

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.27.0-3008277888, revision: github-musescore-musescore-abc123456

**Additional context**
I have two display configuration: one above the other. 
<img width="155" alt="image" src="https://user-images.githubusercontent.com/5051096/189527710-1d303d00-0681-4ac8-97cd-819db8f911a5.png">

**Comment by wizofaus** [comment]
Does this happen if you disconnect the 2nd display? If you use English for your O/S language?
I certainly can't reproduce or see why it might happen (I do have a 2nd monitor).

**Comment by kislenok-roman** [comment]
Sorry, lost email in the depth of my inbox. Put an "important" flag on it, should not lose it anymore.

I've set up English language (US) and detached 2nd display - everything is fine
![image](https://user-images.githubusercontent.com/5051096/202912594-72d4d224-c1b2-4ff5-819b-d3bb0ab5fe18.png)

I connect my 2nd display - menu is broken:
![image](https://user-images.githubusercontent.com/5051096/202912624-bac0c60e-1e2f-43f3-9534-f86cc542be8f.png)

My display configuration:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/5051096/202912711-5c85f6fc-a8fb-4c9e-9a60-e98f78f910f9.png">

I've tried to put them horizontally (different result, but it still doesn't look right: 
![image](https://user-images.githubusercontent.com/5051096/202912783-52aa5a7e-8788-41c1-a740-4ff047906a9c.png)

My displays configuration:
1. 
<img width="345" alt="image" src="https://user-images.githubusercontent.com/5051096/202912945-03e5dda7-f1f1-4183-8270-6550be9e3b86.png">
2. 
<img width="320" alt="image" src="https://user-images.githubusercontent.com/5051096/202912955-f88e2f4c-fcab-49c8-9c16-a67c329e9193.png">

**Comment by Eism** [comment]
@kislenok-roman 
Could you please check this build - https://github.com/musescore/MuseScore/suites/9843549657/artifacts/474421381?

**Comment by kislenok-roman** [comment]
@Eism Now it works as expected, thank you!

**Comment by DmitryArefiev** [comment]
Fixed in #15151

**Comment by DmitryArefiev** [comment]
Retested on Win10 with 4.0.2 RC build - **Doesn't occur**
