### ISSUE TITLE
[MU4 Issue] "Add intervals" commands do nothing if nothing selected

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#13296]
**Describe the bug**
The commands in the Add|Intervals submenu (Unison above, second above etc. etc.) are all enabled even if nothing is selected, but do nothing at all.

**To Reproduce**
1. Create or open any score, ensure nothing is selected
2. Open the Add menu and the Intervals submenu
3. Note that all commands are available
4. Choose any one of them
5. Nothing happens

**Expected behavior**
Either the commands should be disabled (as it's plainly obvious that they mean nothing if you have no note to add an interval to, and would be consistent with commands in the Add | Tuplets submenu), or on attempting to execute, a message telling the user to select a note first would be shown, consistent with what happens when you try to add text etc. when nothing is selected. 

**Screenshots**

**Platform information**
Windows 10
 
**Additional context**
Built from master branch as of 12-sep-2022.

**Comment by randoguyname** [comment]
I'd like to add to this that such functions only apply to the top note selected in a chord per staff

**Comment by randoguyname** [comment]
In hindsight, having looked through the code, the current functionality regarding the singular note added makes sense; if the interval is above, it will add it above from the top note, if it is below, it will add it below from the bottom note. I am however creating a pull request for the issue mentioned
