### ISSUE TITLE
[MU4 Issue] Flipping tie with 'x' does not trigger redraw

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#13303]
**Describe the bug**
When flipping ties via the keyboard shortcut 'x', a redraw is not triggered (i.e. the tie _is_ flipped, but this is not visibly evident until something else triggers a redraw).

Also if this 'flip' is undone with Ctrl+Z,  the tie is removed - that is, it looks like the flip action isn't put on the undo stack either.

Flipping either via the toolbar button or in the Properties panel works as expected. (Slurs work as expected in all cases.)

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a tie to two notes of the same pitch
2. Select the tie
3. Press 'x'; observe nothing happens
4. Trigger a relayout (by adding a system break, or whatever) - note the tie will now flip

**Expected behaviour**
Ties should visibly flip immediately, and undoing them should revert the flip.

**Comment by oktophonie** [comment]
I did check https://github.com/musescore/MuseScore/pull/13043 in case that fixed it, but this would appear to be a separate, if related, issue.

**Comment by wizofaus** [comment]
Can't reproduce sorry, at least on Windows using debug build from latest master branch.

**Comment by wizofaus** [comment]
NB it works fine if the *note* is selected when pressing 'x' (which flips the stem direction too).

**Comment by wizofaus** [comment]
NB the same bug was in 3.6 too, but only occurred when explicitly in "edit mode".
