### ISSUE TITLE
[MU4 Issue] CLI messages are printed to STDOUT rather than STDERR

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#13304]
**Describe the bug**
Command line error and warning messages are printed on the standard output stream rather than the standard error stream. This pollutes the desired output of terminal commands like `--score-media`, which will break these commands in scripts and on the MuseScore.com backend.

**To Reproduce**
Steps to reproduce the behavior on macOS (see [this comment](https://github.com/musescore/MuseScore/issues/13304#issuecomment-1246686232) for Linux):
1. Run this command in Terminal:
    ```Bash
    mscore score.mscz --score-media > output.json
    ```
2. View the output file by running:
    ```Bash
    less output.json
    ```
    Or open it in a text editor.

**Contents of `output.json`**
```JSON
13:33:47.680 | ERROR | main_thread | OSXAudioDriver | logError: Failed to get device's name, err: !siz(561211770)
13:33:47.685 | WARN  | main_thread | Qt         | QEventLoop: Cannot be used without QApplication
13:33:47.685 | WARN  | main_thread | Qt         | QEventLoop: Cannot be used without QApplication
{
"pngs":  ["BASE64DATA"],
"svgs":  ["BASE64DATA"],
"sposXML": "BASE64DATA",
"mposXML": "BASE64DATA",
"pdf": "BASE64DATA",
"midi": "BASE64DATA",
"mxml": "BASE64DATA",
"metadata": {
    "composer": "Composer / arranger",
    "duration": 64,
    "fileVersion": 400,
    "hasHarmonies": "false",
    "hasLyrics": "false",
    "keysig": 0,
    "lyrics": "",
    "measures": 32,
    "mscoreVersion": "4.0.0",
    "pageFormat": {
        "height": 297,
        "twosided": "true",
        "width": 210
    },
    "pages": 1,
    "parts": [
        {
            "harmonyCount": 0,
            "hasDrumStaff": "false",
            "hasPitchedStaff": "true",
            "hasTabStaff": "false",
            "instrumentId": "piano",
            "isVisible": "true",
            "lyricCount": 0,
            "name": "Piano",
            "program": 0
        }
    ],
    "poet": "",
    "previousSource": "",
    "subtitle": "Subtitle",
    "tempo": 0,
    "tempoText": "",
    "textFramesData": {
        "composers": [
            "Composer / arranger"
        ],
        "poets": [
        ],
        "subtitles": [
            "Subtitle"
        ],
        "titles": [
            "Untitled score"
        ]
    },
    "timesig": "4/4",
    "title": "Untitled score"
}

}

```

**Expected behavior**
- The first three lines (ERROR and WARN messages) should have been printed on the Terminal in step 1.
- Those lines should not be present in the `output.json` file viewed in step 2.

**Platform information**
 - OS: macOS (see [this comment](https://github.com/musescore/MuseScore/issues/13304#issuecomment-1246686232) for Linux)

**Additional context**
You can use this command to filter out the raw Base64 data to produce the condensed output as displayed above:
```Bash
mscore score.mscz --score-media | sed -E 's|"[A-Za-z0-9+/]{100,}=*"|"BASE64DATA"|g' >output-condensed.json
```

**Comment by wizofaus** [comment]
Is this MacOS specific? Definitely doesn't happen under Windows and/or Linux?

**Comment by wizofaus** [comment]
`MuseScore4.exe score.mscz --score-media > output.json` just produces an empty file for me (both cmd.exe and git bash).
