### ISSUE TITLE
Remove all shortcut sequences

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#13324]
**Describe the bug**
We made a lot of UX improvements to the Shortcuts dialog a few months ago. Part of that improvement was to prevent users from accidentally creating shortcut sequences when all they want to do is specify a different shortcut. In fact, we prevent their creation entirely.

However, there are still some sequences defined in the shortcuts dialog - and some of them work (although it depends on your machine, OS and the specific shortcut). We need to remove these.

For anyone who doesn't realise, sequences are recognisable because they are separated by a comma, rather than a semi-colon:

![image](https://user-images.githubusercontent.com/21022311/189863366-f3be8d53-777f-4d09-8ac3-0ece3046ba9a.png)

**Comment by aige02** [comment]
A second option would be to add a toggle to the widget.  The default would be to **not** allow multi-sequence shortcuts as is the current method.  Flipping the toggle would allow adding sequences instead of replacing the previous sequence.

**Comment by FrancRos31** [comment]
Sequences are still present in version 4.4.2 (OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97), but no more in the last build (4.5.0). Why so? Did you make it effective only now?

MS 4.4.2
![Image](https://github.com/user-attachments/assets/b34f2b8f-a4f6-4b45-81b3-8ac47f4525ed)

MS 4.5.0
![Image](https://github.com/user-attachments/assets/eb74ed54-d7ff-42bf-a412-d684a3a2adc6)
