### ISSUE TITLE
[MU4] Please, could you reduce the velocity (not the volume) when clicking on a chord symbol?

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13327]
As you click on a chord symbol, it plays back, which is super handy.
However in MU4 it almost sounds as if the the chord was hit with a velocity of 127. 
I think it would be necessary to reduce the default velocity for click-on-play back
in order to have a smoother sound which doesn't frighten you.

**Comment by Tantacrul** [comment]
I agree. It really sounds like the velocity is too high. Whoever works on this - please send me or @bkunda a build for review.

**Comment by MarcSabatella** [comment]
Oddly enough, this seems OK in Muse Sounds, just terrible in MS Basic.  Might relate to the fact that Muse Sounds is ignoring velocity settings on notes?  Anyhow, hopefully that helps point to where the problem actually is.

**Comment by DmitryArefiev** [comment]
Fixed in #14825
