### ISSUE TITLE
[MU4 Issue]MU4 alpha is defined as default application for .mscz and .mscx

### ISSUE THREAD

**Issue by lgvr123** [musescore/MuseScore#13323]
Installing on Windows MU4 alpha for testing purpose makes it the default application for .mscz and .mscx files
This shouldn't be the case as long as MU4 is in non official state.
MU3 should stay the default version, so that the user can keep on working **easily** on his scores with a stable version, while testing MU4 on the side.
The user is now forced to redefine manually MU3 as the main editor for all the MU-compatible files.

**Comment by Tantacrul** [comment]
We're unable to alter this now, I'm afraid. I'm going to close the issue, since it can't be rectified for old installs.

**Comment by lgvr123** [comment]
>it can't be rectified for old installs
But solved for the new builds ?

**Comment by cbjeukendrup** [comment]
In fact, the code to conditionally include the file associations in the installer already exists, and if I'm not mistaken we have always done this correctly for alpha/beta releases in the past.
Judging from this piece of code:
https://github.com/musescore/MuseScore/blob/af7f69fcf223a66fb6831637198c43cf867faf88/build/ci/windows/package.bat#L152-L155
it looks like @vpereverzev created the alpha build as a `stable_build` but it should probably have been `testing_build`. Hopefully we will do this correctly for the next beta.

It's no disaster that it has gone wrong for the alpha 2; re-running the MuseScore 3 installer should set the file associations back to MU3.
