### ISSUE TITLE
[MU4 Issue] Defining shortcut sequence for "Enter rest: xxxx" doesn't work as expected

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#13322]
**Describe the bug**
The default shortcut key sequences for "Enter rest: eighth/half/quarter/whole" are "Shift+R,Shift+<?>", i.e. a two key-combination sequence. But when you try to define your own sequence they're shown as two alternative single key-combination shortcuts (separated by a ";"), which is incorrect, and there appears to be no way to change them, so that e.g. "Enter rest: whole" is "Shift+R,Shift+W", other than editing shortcuts.xml

**To Reproduce**
1. Go to Edit | Preferences | Shortcuts
2. Find & select "Enter enter: whole"
3. Click "Define" (or double click the selected entry)
4. Sequence is incorrectly shown as two alternative shortcut key combinations, as per, e.g. "Insert full measure rest" (which is either "Ctrl+Shift+Del" OR "Ctrl+Shift+Backspace" by default).
5. Entering in Shift+R , Shift+W doesn't allow you change it to a new sequence.
6. Also note that the old and new shortcut key fields are misaligned horizontally, and the text "Define keyboard shortcut" seems unnecessarily huge (indeed, unnecessary entirely, given the dialog title is "Enter shortcut sequence").

**Expected behavior**
If the intention is to drop all support for shortcut key sequences then the defaults should not include these and the dialog title should not say "Enter shortcut sequence". But in fact such sequences are extremely handy providing they're defined sensibly and used by other well known applications (Visual Studio among them), so I would expect I can define such sequences, and certainly it should be obvious when re-defining a shortcut what the current definition is.
Either way the "Enter shortcut sequence" dialog could use some finesse.

**Screenshots**

**Platform information**
Windows 10

**Additional context**
Debug build from master branch as of 13-Sep-2022.

**Comment by Tantacrul** [comment]
The intention was to drop all support for sequences and we took a whole bunch of steps a few months ago to achieve that. However, it sounds like there are still some annoying hangover UI problems that are not making this clear.

**Comment by Tantacrul** [comment]
Anyway, I'm going to close this an open a new issue specifying that we burn out shortcut sequences completely.
