### ISSUE TITLE
[MU4 Issue] [Inspector] No text style settings (font, style) for text lines in Properties

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13338]
No text style settings for text lines in Properties. 

E.g. you **can't change** text style or font for "Staff" text in Staff text line (see video below)

**MuseScore3**
![Capture](https://user-images.githubusercontent.com/90187801/189955350-cf9f893e-fc0f-4d02-ad68-5ea4bc766a64.PNG)

**MuseScore4**

![Capture2](https://user-images.githubusercontent.com/90187801/189955365-e35b3e13-cb53-4a40-b05b-855d9d8c888a.PNG)

https://user-images.githubusercontent.com/90187801/189956258-a1aa3fbe-65b6-4c03-ace7-2e6c4d258204.mp4

**Platform information**
 macOS, Windows, Linux

**Additional context**
Doesn't occur in **MS3**

**Comment by mxmou** [comment]
I think #12848 describes the same issue.

**Comment by DmitryArefiev** [comment]
> I think #12848 describes the same issue.

@mxmou Yes, it the same. I'll close #12848 to leave only one issue

Thanks!

**Comment by MarcSabatella** [comment]
@Tantacrul - another missing control that would be great to have added before release.  Not necessarily beta-critical, except that anything that changes UI at all (even just to add an existing control to this particular set of properties) has impact on documentation.

**Comment by Tantacrul** [comment]
I have a sense that these changes will not make it to the release but you'd never know.

@bkunda - sorry but, again, I'm going to put this on you. Basically, we should just show the normal text settings section as well as the line info. 

<img width="299" alt="image" src="https://user-images.githubusercontent.com/21022311/195662356-1e70aad2-c466-4c1e-9563-f1ae6707376f.png">

**Comment by ShibuyaCyana** [comment]
Having the same problem. Plus trying to change it from style - text styles doesn't work, and setting is lost if I reopen that dialog.
![Change styles doesn't work](https://user-images.githubusercontent.com/39703247/204103998-ac5f0c64-6b55-4f39-82f8-e8bb4b011d3a.gif)

**Comment by Gravifer** [comment]
Related to [this line](https://github.com/musescore/MuseScore/blob/812e29acef82419fd35ba290916962f8968c489e/src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp#L3035)

**Comment by cbjeukendrup** [comment]
> Related to [this line](https://github.com/musescore/MuseScore/blob/812e29acef82419fd35ba290916962f8968c489e/src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp#L3035)

As said in https://github.com/musescore/MuseScore/issues/14238#issuecomment-1383138068, this is not true.

**Comment by DmitryArefiev** [comment]
The same with Voltas


https://user-images.githubusercontent.com/90187801/215543112-f41db303-eb14-482d-8218-64db4eef1e88.mp4

**Comment by bkunda** [comment]
> The same with Voltas

@DmitryArefiev this has been specified in the design task that would resolve this issue: [#14238](https://github.com/musescore/MuseScore/issues/14238)

**Comment by rgreen5** [comment]
One other thing. **Frame properties** needs to be added (missing in MS3): this would, amongst other things, allow the user to create string number lines.

**Comment by bkunda** [comment]
> One other thing. **Frame properties** needs to be added (missing in MS3): this would, amongst other things, allow the user to create string number lines.

I think we could better solve this separately, by adding a dedicated palette element (and/or a property to the existing ‘encircled string number‘ palette elements) that generates a 'ready-made' string number line (assuming this is what you were referring to): 
 
<img width="1107" alt="Screenshot 2023-03-17 at 11 13 29 am" src="https://user-images.githubusercontent.com/86290556/225876745-dac9223f-f9e7-42c8-99b6-063ad5eefacc.png">

Ideally, the user shouldn't need to build this themselves by altering a different kind of text line.

**Comment by rgreen5** [comment]
> I think we could better solve this separately, by adding a dedicated palette element (and/or a property to the existing ‘encircled string number‘ palette elements) that generates a 'ready-made' string number line (assuming this is what you were referring to):

OK, I'll open a feature request for that.

**Comment by bkunda** [comment]
Closing because it will be solved by https://github.com/musescore/MuseScore/issues/14238
