### ISSUE TITLE
[MU4 Issue] Adding sticking to note does nothing

### ISSUE THREAD

**Issue by lane-hogan** [musescore/MuseScore#13332]
**Describe the bug**
When a note is selected and you attempt to add sticking to it, nothing happens.

**To Reproduce**
1. Create a quarter note
2. Click on **Add > Sticking**
3. Nothing happens

**Expected behavior**
A textbox should appear to allow me to add a sticking text to the note.

**Platform information**
 - OS: Windows 11

**Comment by MarcSabatella** [comment]
Itthis using the latest nightly build?  It'd working for me now, fixed a few days ago as of https://github.com/musescore/MuseScore/pull/13189
