### ISSUE TITLE
[MU4 Issue] Dynamics and "pizz." instructions interfere with each other

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#13343]
**Describe the bug**
Depending on whether a dynamic marking or a "pizz." (or probably similar instrument change instructions) is added first, one is played and the other ignored. In some cases both seem to get ignored.

**To Reproduce**
1. Open the attached score and play it back
2. Notice that on measure 3, the playback is not ***f*** or pizzicato.

**Expected behavior**
Playback should match notation

**Screenshots**
~

**Platform information**
Windows 10

**Additional context**
Latest nightly build, Sep-14-2022.
[hairpinplayback.zip](https://github.com/musescore/MuseScore/files/9561757/hairpinplayback.zip)

(rename zip to mscz to open in MS)

I haven't quite worked out repro steps on how to create this from scratch yet, however it does seem if you add a dynamic to a note then add a "pizz." marking, the pizz. is ignored.

**Comment by DmitryArefiev** [comment]
It looks the same as #11932 
Fixed in #13495 (should be in master soon)

Please reopen if still occurs.
