### ISSUE TITLE
[MU4 Issue] Chord with arpeggio markings play too loud in presence of slurs

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13340]
**Describe the bug**
A chord with an arpeggio plays too loudly, if under a slur

**To Reproduce**
1. Enter four chords: normal, arpeggiated, normal, arpeggiated
2. Slur the last two chords
3. Play
4. Hear error: the arpeggiated chord under the slur plays much too loudly

**Expected behavior**
All chords play the same volume

**Screenshots**
![image](https://user-images.githubusercontent.com/1799936/189990824-574932e0-8040-4d2f-ae6e-134df89130f4.png)

**Platform information**
 - OS: Linux

**Additional context**
See also https://github.com/musescore/MuseScore/issues/12678.  Tenuto marks have the same behavior, not affecting volume normally but going crazy under slurs.

**Comment by MarcSabatella** [comment]
Same if there is pedal a line instead of slur.  But paradoxically, adding an accent *defeats* the accent in either case.  So: arpeggio alone is normal volume (fine).  Aprepggio plus slur: too loud (bad, should be normal).  Arepggios plus slur plus accent: normal volume (bad, should be loud because of accent).

**Comment by DmitryArefiev** [comment]
Fixed in #13656

Please reopen if still happens in other cases
