### ISSUE TITLE
[MU4 Issue] New tempo ignored after rit.

### ISSUE THREAD

**Issue by Wim4rk** [musescore/MuseScore#13366]
When entering a rit. (or rall.) a new tempo will be ignored. Possibly the same as #12140, but suggested fixes doesn't work for me.

1. Open attached file. Play it.
2. Move stuff around - rit. and new tempo.
3. Notice issue

**Expected behavior**
Tempo markings should work immediately after rit. or rall.

**Platform information**
 - OS: Ubuntu 20.04.5 LTS

**Additional context**
Working configurations are available: end rit. line on third beat of bar 3, and new tempo on second beat of bar 4 (B).

**Comment by Wim4rk** [comment]
[bug_report.zip](https://github.com/musescore/MuseScore/files/9576291/bug_report.zip)

**Comment by Wim4rk** [comment]
[bug_report.zip](https://github.com/musescore/MuseScore/files/9576379/bug_report.zip)

**Comment by MarcSabatella** [comment]
I can confirm the workaround of shortening the "rall." line does not work on this score for some reason.  I still suspect it's the same basic bug as #12140 , but maybe so other variable prevent the workaround from working here.  Not sure what it is though.  If I delete the other instruments, the workaround works.

Depending on what I do when playing around with it, there are also cases where the playback cursor moves at the correct tempo, but the actual playback does not.  This is especially noticeable if you change the new tempo to something much faster, like 180.

**Comment by Wim4rk** [comment]
A thought:
Does longer notes retain tempo data from where they began? Carrying it over and ignoring tempo changes?

**Comment by Wim4rk** [comment]
Stumbled across an even worse example when using repeats. Hard to explain, notes retain their tempo somehow.
[bug_report.zip](https://github.com/musescore/MuseScore/files/9591591/bug_report.zip)

**Comment by DmitryArefiev** [comment]
Fixed in #13538
