### ISSUE TITLE
[MU4 Issue] CPU load during playback is high on Mac (comparing with MuseScore 3) 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13365]
**Describe the bug**
%CPU load during playback is high on Mac12.6 even on small score

**MuseScore4 takes ~39%** comparing with **MuseScore3 ~23%** 

**To Reproduce**
1. Open and playback [piano3.zip](https://github.com/musescore/MuseScore/files/9575801/piano3.zip) in MS3 and MU4

**MuseScore4**
![Screenshot 2022-09-15 at 16 42 28](https://user-images.githubusercontent.com/90187801/190421419-3c440a8b-4b36-46c8-84cb-06be57489d24.png)

**MuseScore3**

![Screenshot 2022-09-15 at 16 35 02](https://user-images.githubusercontent.com/90187801/190421486-2d0c66e0-0c54-4f47-9f7f-7d6dedc1867c.png)

**Platform information**
 macOS 12.6, (MacBook Air13 M1, 2020)

**Additional context**
CPU load during playback on **Windows10** is also lower in **MuseScore3** (half as much), but in general it's not noticeable.
**MuseScore3 takes ~1%** and **MuseScore4 takes ~3%** (Lenovo IdeaPad5 Pro, Core i5-11300H)

**Comment by Tantacrul** [comment]
In the bottom of both of those screenshots, the 'User' % is about the same (around 5%).

Closing this on @vpereverzev's advice. We won't be tackling any more performance stuff of this nature for 4.0.
