### ISSUE TITLE
[MU4 Issue] hairpins (and cresc. and lines) added from palette to voice 2 (or 3, 4) are added to voice 1

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13374]
**Describe the bug**
Hairpins (or cresc. or any other line) added from palette to voice 2-4 is added always to voice 1

**To Reproduce**
1. Select note in voice 2 (or 3, 4)
2. Click on hairpin in palette (or any other line)
3. Hairpin is added to voice 1

**Expected behavior**
Hairpin is added to selected voice

**Screenshots**

https://user-images.githubusercontent.com/1646034/190482619-dfdcd50d-e2c5-4ef3-9b8c-5b982ebd8b7a.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
- Only palette is problem, if adding hairpins by shotcut, it works right (added to selected voice). /If selected notes are in multiple voices, from shortcut, hairpin is added to voice of first note ("most left side note")/
- If there are more than 2 notes selected, multiple hairpins (lines) are added (see #13317), but to correct voice (sic!)

**Comment by oktophonie** [comment]
While this is not a regression (3.6 is the same), it is indeed an unfortunate shortcoming. Dynamics can be added to specific voices, but hairpins cannot; a trill can be added as an ornament to a specific voice, but a trill line cannot, etc.

**Comment by Tantacrul** [comment]
Yes. The audio engine does not support multi-voice dynamics yet. This is on our radar. I've given it a P0 to keep it at the top of my 'to do' list!
