### ISSUE TITLE
[MU4 Issue] No sound when entering fretmarks in tablature

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13403]
**Describe the bug**

Open the attached score and enter notes in tablature.
[tab_input_no_sound.zip](https://github.com/musescore/MuseScore/files/9591710/tab_input_no_sound.zip)

RESULT: No sound

**Expected result**

Fretmarks should sound as they are entered.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3072092433, revision: github-musescore-musescore-007bc62

**Comment by DmitryArefiev** [comment]
Thanks for logging!

**Comment by DmitryArefiev** [comment]
https://user-images.githubusercontent.com/90187801/193040336-66ec51d1-dd1f-4f78-ae96-237573397c51.mp4

**Comment by DmitryArefiev** [comment]
Fixed in #15161
