### ISSUE TITLE
[MU4 Issue] Can't extend a bend without creating useless space in the score

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13401]
**Describe the bug**

This a problem introduced sometime in MS3 and has been carried over into MS4. As you extend the bend it collides with the note in front, creating useless space in the score.

![extend_bend_wrong](https://user-images.githubusercontent.com/87246583/190854302-f4186858-aaeb-430a-b290-e80927ec4cf9.gif)

**To Reproduce**

1. Open the attached score. 
[extend_bend.zip](https://github.com/musescore/MuseScore/files/9591563/extend_bend.zip)

2. Click on the final bend and in the graphical interface (Properties panel), extend it by creating extra nodes.

RESULT: The bend pushes the next note forward creating extra space to no purpose. Turning off autoplace is not the answer because then the note is put out of position.

**Expected behavior**

The bend should not create any extra space in the score.  The whole point of extending the bend is to fit over existing notes, therefore it should be allowed to extend or retract independently without triggering collision avoidance.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3072092433, revision: github-musescore-musescore-007bc62

**Comment by rgreen5** [comment]
Bump.

**Comment by bkunda** [comment]
This will no longer be an issue in our new 4.2 bends system.
