### ISSUE TITLE
[MU4 Issue] Chord symbols too loud in imported MS3 scores

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13412]
**Describe the bug**

Chord symbols in imported scores are being played back very loud. Open the attached MS3 for an example. 
[chord_symbol_volume.zip](https://github.com/musescore/MuseScore/files/9593800/chord_symbol_volume.zip)

Similar to #13327?

**Platform information**
 OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3075842495, revision: github-musescore-musescore-c7b4d51

**Comment by MarcSabatella** [comment]
For me, not just imported scores, all chord symbol playback is way too loud by default.  But see also https://github.com/musescore/MuseScore/issues/13604

**Comment by Tantacrul** [comment]
I think we should close this and keep https://github.com/musescore/MuseScore/issues/13327?

The issues are the same.
