### ISSUE TITLE
[MU4 Issue] "Capo line" should be "Barre line" (Guitar palette)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13411]
**Describe the issue**

In the "Guitar" palette, the "Capo line" symbol needs to be renamed to "Barre line".

**Comment by cbjeukendrup** [comment]
@bkunda Do you agree with this change?

**Comment by bkunda** [comment]
Yes this makes sense, as the line is actually there to indicate a barré, not the placement of a capo device.
Although technically it should be "barré" (if the accent is possible).
