### ISSUE TITLE
[MU4 Issue] "Notehead type" and "Notehead type (visual only)"

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13418]
**Describe the issue**

There are two properties with similarly names, but different functions, in __Properties: Note__ : namely "Notehead type", and "Notehead type (visual only)". IMV, they should have different names.

How about "Dummy notehead" instead of "Notehead type (visual only)" ("dummy" in the sense of "not real but having a similar appearance to something else")?

**Comment by GabeS573** [comment]
I don't think "Dummy notehead" really explains what it does. How about **"Notehead duration (visual only)"**?

**Comment by Tantacrul** [comment]
We altered this to the following prior to release. Obviously didn't close this issue back then. Thanks!

<img width="284" alt="image" src="https://user-images.githubusercontent.com/21022311/220397425-941a3b25-7d8a-4b21-a6a3-82863313321b.png">
