### ISSUE TITLE
[MU4 Issue] Articulation is deleted after changing note duration

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#13429]
**Describe the bug**
Two cases are present:
- One articulation is added to a note (case 1)
- Two articulations are added to a note (case 2)

**To Reproduce**
1. Create a simple score
2. Add a quarter note
3. Add staccato to the note
4. Change duration of the note

To get case 2 on the step '3' add staccato and accent

**Expected behavior**
Articulation s are not affected by duration change

**Screenshots**
Case 1

https://user-images.githubusercontent.com/101250347/191368104-3aa5c7fb-9285-40f4-a492-bb693fa32054.mp4

Case 2

https://user-images.githubusercontent.com/101250347/191368139-c6fa3fac-fa9b-450b-9f06-7569bd416618.mp4

**Comment by oktophonie** [comment]
I notice that articulations are also deleted (Case 1) when moving notes from one voice to another:

https://user-images.githubusercontent.com/20604032/192024778-d673dcd0-8bd5-4651-ace0-5e98f7d72981.mp4

**Comment by Tantacrul** [comment]
This is actually a really bad regression from V3, so I've bumped it to Beta 1. @oktophonie - is it something for your team do you think?

**Comment by cbjeukendrup** [comment]
PR created: #13675

**Comment by DmitryArefiev** [comment]
Fixed in #13675

**Comment by DmitryArefiev** [comment]
> I notice that articulations are also deleted when moving notes from one voice to another:
> box-220923-1836-39.mp4

The same issue in MuseScore3. Should be logged separately and solved in 4.x or later
