### ISSUE TITLE
[MU4 Issue] - unable to change Volta text size/appearance

### ISSUE THREAD

**Issue by drbirkenstocks** [musescore/MuseScore#13420]
**Describe the bug**
Unable to change volta text appearance or size under style settings.

**To Reproduce**
1. Go to Style Settings→ Text Styles→ Volta
2. Endeavor to edit text appearance/size/etc.
3. Click OK
4. See nothing changes

**Expected behavior**
Text styles/appearance will be affected by changes

**Platform information**
 - Windows 11

**Comment by cbjeukendrup** [comment]
It looks like this is going to be fixed by #13292!
