### ISSUE TITLE
[MU4 Issue] Concert pitch checkbox changes are not updated after Undo

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13437]
**Describe the bug**
This was reported within #12481 

**To Reproduce**
1. have a score with transposing instruments 
2. enable concert pitch using the checkbox in the Status bar
3. press undo

**Expected**: concert pitch is disabled again, **and the concert pitch checkbox reflects this**

**Actual**: although the score is updated correctly (because that happens inside the engraving module) **but the checkbox not** (because that should have happened via the styleChanged notification from the notation module, but that notification is not emitted this time). If you click the checkbox again after this, unexpected things may happen.

https://user-images.githubusercontent.com/90187801/191735418-f8183162-e6c2-48b7-9dda-9828e6f5b51d.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
#12481

**Comment by HemantAntony** [comment]
@DmitryArefiev check #13437

**Comment by DmitryArefiev** [comment]
Fixed in #16003
