### ISSUE TITLE
[MU4 Task] Link "Watch video" button in all "Style Improvements" dialogs to new engraving video

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13436]
**Task description**
The "Watch video" button in all "Style Improvements" dialogs should point to this video on the MuseScore YouTube channel: 
https://youtu.be/U7dagae87eM

<img width="509" alt="Screenshot 2022-09-21 at 4 24 35 pm" src="https://user-images.githubusercontent.com/86290556/191531100-a11ca4e0-98f7-43c4-bbe4-1d4bb7172ee2.png">

<img width="609" alt="Screenshot 2022-09-21 at 4 28 42 pm" src="https://user-images.githubusercontent.com/86290556/191531886-c5d36d80-67d6-43d4-837a-7481da55b260.png">

Note: these dialogs (and any other associated dialogs with alternate messaging referring to earlier versions of MuseScore) are triggered by opening a score created with MuseScore 3.6 or earlier in MuseScore 4.0.

@HemantAntony Wondering if you might be up for this one? 🙂 Let us know if you can help! 

Thanks!

**Comment by HemantAntony** [comment]
Seems easy enough! Happy to do it :)

**Comment by HemantAntony** [comment]
@bkunda Currently in the code there is a check if the person is from China, if so another link is used (https://www.bilibili.com/video/BV1FT4y1K7UM). This is likely because Youtube is blocked in China

**Comment by HemantAntony** [comment]
@bkunda Anyhow I have a create a PR #13484

Also, I couldn't test it because neither the new nor old video links open. I tried copying the link of a random youtube video and pasting, but that didn't work. I think Youtube is having a problem

**Comment by cbjeukendrup** [comment]
IIRC YouTube is not really blocked in China, but nobody really uses it. For that reason, @Howard-C re-uploaded the video (with Chinese captions "burned in", IIRC) to Bilibili which is the Chinese equivalent to YouTube. 

@Howard-C, would you like to do that again for this new video? You should probably work with @Tantacrul and/or @bkunda, because there are certainly more YouTube videos that are linked from MuseScore 4 (most notably, the "Learn" page is full of them!).

@HemantAntony Until the new video is uploaded to Bilibili, I suggest we just use the YouTube version. I think linking to an old video is worse than linking to the new video on a sub-optimal platform.

**Comment by Tantacrul** [comment]
@cbjeukendrup agreed

**Comment by Howard-C** [comment]
> Howard-C, would you like to do that again for this new video? You should probably work with Tantacrul and/or bkunda, because there are certainly more YouTube videos that are linked from MuseScore 4 (most notably, the "Learn" page is full of them!).

Hi @cbjeukendrup, sorry for the delay in response as I'm not often checking GitHub these days, but thanks for the invite! I'd really much like to do it. Also @Tantacrul I just saw the video list you posted in Discord, could you perhaps point out how many of them are to be linked from musescore.org and/or MuseScore itself? If it's all of them, then I'll do all of them, no probs, but I can't guarantee I can finish them before the final release.

**Comment by Tantacrul** [comment]
All the videos I linked on Discord are intended to be accessed from within MuseScore 4 too.

Thanks!

**Comment by Howard-C** [comment]
OK then!
By the way, Bilibili doesn't seem to have an unlisted option, so if we intend to get the links to Bilibili videos to include in the release, they would have to be uploaded and be seen by the public in advance. Is this OK?
