### ISSUE TITLE
MuseScore failed to build with "fatal error LNK1246: '/DYNAMICBASE:NO' not compatible with 'ARM64' target machine; link without '/DYNAMICBASE:NO'" with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by YangYang129** [musescore/MuseScore#13434]
MuseScore failed to build with "fatal error LNK1246: '/DYNAMICBASE:NO' not compatible with 'ARM64' target machine; link without '/DYNAMICBASE:NO'" with MSVC on Windows arm64ec. It can reproduce on latest version on master branch. Could you please help look at this issue?

**Versions and configuration**
OS: Windows Server 2022 Datacenter
VS: Visual Studio 2019(16.11.19)

**Repro steps:**

1. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
2. git clone https://github.com/musescore/MuseScore  F:\aa\MuseScore
3. cd F:\aa\MuseScore
4. git -C "F:\aa\MuseScore" apply f:\MuseScore_ARM64EC_C3861.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
5. xcopy F:\gitP\musescore\dependencies F:\aa\MuseScore\dependencies /k/r/e/i/s/c/h/f/y 
6. xcopy F:\tools\ARM64EC\xmmintrin.h  F:\aa\MuseScore\thirdparty\opus\include /k/r/e/i/s/c/h/f/y 
7. mkdir build_arm64ec && cd build_arm64ec
8. set PATH=F:\tools\qt5\qt\5_15_2\msvc2019_64\bin;%PATH% 
9. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release  -DBUILD_UNIT_TESTS=OFF ..
10. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release mscore.sln /t:Rebuild 

**Error info:**
`169>LINK : fatal error LNK1246: '/DYNAMICBASE:NO' not compatible with 'ARM64' target machine; link without '/DYNAMICBASE:NO' [F:\aa\MuseScore\build_arm64ec\src\main\mscore.vcxproj]`

**Error log:**
[MuseScore_msbuild.log](https://github.com/musescore/MuseScore/files/9616181/MuseScore_msbuild.log)

**Patch attachment:**
[MuseScore_ARM64EC_C3861.patch.log](https://github.com/musescore/MuseScore/files/9616186/MuseScore_ARM64EC_C3861.patch.log)

**Comment by cbjeukendrup** [comment]
You could try commenting out
```cmake
    set(CMAKE_EXE_LINKER_FLAGS          "/DYNAMICBASE:NO")
```
in `build/cmake/SetupBuildEnvironment.cmake`, line 48.

But I don't think building for Windows ARM64 is supported yet, especially since (as far as I know) Qt 5.15.2 only has x86_64/amd64 binaries.
What if you pass `-host_arch=amd64 -arch= amd64 ` in the beginning, to compile for amd64? (And AFAIK you can then run the app through Windows's builtin emulation. I do that when using Windows in Parallels on an ARM64 Mac.)

**Comment by Jojo-Schmitz** [comment]
Why using that set command when an easy patch of google crashpad fixes it too?

**Comment by YangYang129** [comment]
@Jojo-Schmitz If delete https://github.com/musescore/MuseScore/files/9616186/MuseScore_ARM64EC_C3861.patch.log, fail to build "F:\MuseScore\thirdparty\google_crashpad_client\third_party\mini_chromium\mini_chromium\base\logging.cc(357,5): error C3861: '__ud2': identifier not found "

**Comment by YangYang129** [comment]
@cbjeukendrup Thanks for your info. I try commenting out this option, and build pass.
