### ISSUE TITLE
[MU4 Issue] Dynamics are wrong when skipping backwards

### ISSUE THREAD

**Issue by Bolt7** [musescore/MuseScore#13441]
Dynamics are wrong when selecting a note during playback and pressing the left arrow key repeatedly to move back in the music.
The notes play at the volume of the "most recently passed" dynamic marking, rather than the dynamic marking most recently preceding the note. So if you're pressing left repeatedly and passing a pianissimo dynamic, the notes _before_ the dynamic are also very soft.

1. Open a score with dynamics
2. Start playback
3. Select a note past a certain dynamic marking and press left repeatedly
4. Notice the the notes to the left continue to play at that dynamic's volume.

 - OS: Linux

Screen recording (without sound, but shows the steps).
Github doesn't support .mscz files, but the recording should be enough to recreate the exact score if necessary.

[Screencast from 09-21-2022 09:39:24 PM.webm](https://user-images.githubusercontent.com/75871317/191639804-f0c21f80-33fd-434f-b82d-dfb4c90463fa.webm)

**Comment by DmitryArefiev** [comment]
Looks similar to #13534. Should be rechecked after fixing #13534

Thanks for logging

**Comment by DmitryArefiev** [comment]
Fixed in #13536
