### ISSUE TITLE
[MU4 Issue] Change default time stretch property for fermatas 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13464]
**Describe the bug**
Fermatas of all varieties currently play with a default "time stretch" property of 100%.
This value produces no discernible audible change, giving the impression that the fermata is not being recognised in playback. 

**To Reproduce**
See video demo: 

https://user-images.githubusercontent.com/86290556/191978684-e6add74e-0763-4032-a0a9-bbe539dc154f.mov

**Expected behavior**
@oktophonie and I have consulted together on making the following recommendations for default time stretch values: 

| Fermata type | Recommended time stretch value |
| ------------- | ----------------------------------|
| Very short fermata above | 125% |
| Short fermata above | 150% |
| Short fermata (Henze) above | 150% |
| Fermata above | 200% |
| Long fermata above | 300% |
| Long fermata (Henze) above | 300% |
| Very long fermata above | 400% |

**Platform information**
 - MacOS 12.3.1 (M1)

**Comment by Jojo-Schmitz** [comment]
There are several fermatas availa, very short, short, 'normal' lone, very long (also short and long Henze), these all should have their default time stretch but surly be different from one another (and of course sorted by legnth)

**Comment by Jojo-Schmitz** [comment]
Whether 200 is a good default for a 'normal' fermata is something for the experts to decide, to me that seems a bit too long?

**Comment by Jojo-Schmitz** [comment]
Maybe 125, 150, 175 (normal), 200 and 225?

**Comment by bkunda** [comment]
> There are several fermatas available, very short, short, 'normal', loge, very long (also short and long Henze), these all should have their default time stretch set but surly be different from one another (and of course sorted by length)
> 
> Whether 200 is a good default for a 'normal' fermata is something for the experts to decide, to me that seems a bit too long? Maybe 125, 150, 175 (normal), 200 and 225?

Thanks for pointing this out @Jojo-Schmitz. Please see updated issue description.

**Comment by Jojo-Schmitz** [comment]
Looks good to me.

**Comment by HemantAntony** [comment]
@bkunda made a PR #13506
