### ISSUE TITLE
[MU4 Issue] When deleting a chord, the resulting rest is deselected; when dotting a chord, the chord is deselected

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#13469]
**Describe the bug**
An inconsistency and minor annoyance more than a 'bug'.

When deleting a note, the rest that replaces it remains selected. When deleting a _chord_, the rest is not selected, and therefore must be manually selected in order to perform any further operations. (This is a regression from 3.6.)

https://user-images.githubusercontent.com/20604032/192023927-facd5d00-c92c-491c-990f-7ad0a204c1e5.mp4

Presumably somewhat related: when adding an augmentation dot to a note, the note remains selected. When adding a dot to a _chord_, the chord is deselected:

https://user-images.githubusercontent.com/20604032/192026248-c7271944-e5a0-4603-91ab-138929dbcf13.mp4

This is actually not a regression from 3.6, but it is an inconsistency.

---
Note: regarding this latter case, a chord can be selected in two ways. Either by Ctrl+clicking each of its notes:
![image](https://user-images.githubusercontent.com/20604032/192091699-46cc3625-0b23-4c6e-8216-8afb8711b12b.png)
or by clicking the first note then Shift+clicking another, whereupon it becomes a 'range' of one chord:
![image](https://user-images.githubusercontent.com/20604032/192026524-0e9de723-f7cd-4eea-b01d-261caba953de.png)
In the former case, it seems unarguable (famous words) that the resulting rest should remain selected. In the latter case, it appears logical for nothing to remain selected - a range could span any number of chords. However, is there a case to be made for an exception where the range spans only one duration, so that the rest remains selected?

The reason I mention this relates specifically to bar rests. It is much easier (and feels natural) to select the bar by clicking somewhere on it - rather than precisely on the bar rest symbol itself, which is a much smaller target. That selects the whole bar as a range:
![image](https://user-images.githubusercontent.com/20604032/192091822-2c62410a-a4e4-4c65-8406-29b440e77a7c.png)
At this point one can enter notes immediately by typing letter names. The first note created will be selected. If, instead, you choose a _duration_, then the bar rest splits to begin with a rest of that duration; that first rest, however is _not_ selected. If you then proceed to type letter names to input notes, they will actually be input wherever was _previously_ selected in the score (which could be anywhere), rather than where the new rest was just created:

https://user-images.githubusercontent.com/20604032/192092205-468de997-298d-44f9-be71-219e651f1e8b.mp4

**Comment by rgreen5** [comment]
I'm seeing this on all oktophonie's uploaded screencasts:

![file_corrupted](https://user-images.githubusercontent.com/87246583/192093278-944bb85a-3e18-41e2-bed2-08d30da7beab.png)

**Comment by HemantAntony** [comment]
All the videos work for me

**Comment by rgreen5** [comment]
Apart from oktophonie's, other screencasts are OK.

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/350526 (in a tangent)

**Comment by Tantacrul** [comment]
Delighted this one is done. This issue forces people to dedicate loads of additional time re-selecting things! A real pain.
