### ISSUE TITLE
[MU4 Issue] Playback in final measure stops abruptly if note durations fill the entire measure

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13463]
**Describe the bug**
Where the final bar of a score contains note durations that fill the entire bar:
- Playback stops abruptly (little or no discernible tail of the notes beyond the barline)
- A discernible audio click is heard

See this demo video: https://www.dropbox.com/s/1xwo9dh9xrwqnx5/end-of-score-audio-stops.mov?dl=0

**Expected behavior**
See NotePerformer examples in demo video above.
Also "expected behaviour" can more or less be realised in MS4 by simply adding an empty measure after the final measure of a score. Playback could ideally replicate this behaviour, _but without_ the user having to add an additional empty measure at the end of their score. 

**Platform information**
 - MacOS 12.3.1 (M1)

**Comment by cbjeukendrup** [comment]
Possibly related to #12747

**Comment by DmitryArefiev** [comment]
Fixed in #13658
