### ISSUE TITLE
[MU4 Issue] MuseScore.com visibility settings don't get recognised by the desktop app (Save to cloud)

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13462]
**Describe the bug**
When a score saved to MuseScore.com (either via "save to cloud" or "publish" flows) has its visibility setting changed on the website, the desktop app overrides that visibility setting on the next "Save" command. 

See demo video: https://www.dropbox.com/s/yswly6k5g35sa3p/save-to-cloud-website-integration-1.mov?dl=0

**Expected behavior**
The visibility setting for a cloud score on MuseScore.com should be recognised by MuseScore desktop app whenever the user executes a "Save" command.

If a privately saved score is set to "public" visibility on the website, then when the user next executes a "Save" command in the MuseScore desktop app, they should see this dialog: 

<img width="603" alt="Group 184" src="https://user-images.githubusercontent.com/86290556/191968697-b52c1432-8a0c-4b47-a386-ca2259bf5359.png">

If a published score on MuseScore.com has its visibility setting changed back to "private", then the next "Save" the user executes in the MuseScore desktop app should trigger this dialog:
<img width="482" alt="Cloud save confirmation_ordinary" src="https://user-images.githubusercontent.com/86290556/191967864-3142a579-f145-4ec7-99f6-1e967a65a3a0.png">

Hope that's clear! 
Thanks 🙂

**Comment by shoogle** [comment]
Related to #13571
