### ISSUE TITLE
[MU4 Task] Replace "callback received" page in save-to-cloud flow

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13460]
**Task description**
Currently, when the user attempts to save a score to the cloud, if they are not already logged into their MuseScore.com account within the desktop app, their browser is triggered and this message is displayed: 

<img width="358" alt="Screenshot 2022-09-23 at 2 51 50 pm" src="https://user-images.githubusercontent.com/86290556/191964476-aba77e8d-06dc-4768-9c28-587ced90e164.png">

At this stage in the user flow, it would be preferable if a page on musescore.com with this design were triggered instead: 

<img width="1348" alt="Screenshot 2022-09-23 at 2 56 23 pm" src="https://user-images.githubusercontent.com/86290556/191965067-d6f51fe3-b0d4-4e0c-8460-ef6fff4cd1f4.png">

Note: The "Take me there" button is not crucial if there are technical limitations that prevent it being implemented. 

Let me know if you have any questions.
Thanks!

**Comment by shoogle** [comment]
The "callback received" page is generated by Qt. @cbjeukendrup, do you know if it's possible for us to redirect to a real webpage instead?
