### ISSUE TITLE
[MU4 Issue] Making dotted note, or rest invisible doesnt make dot invisible - regression

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13487]
**Describe the bug**
When user makes dotted note, or rest invisible, dot reamins vible.

**To Reproduce**
1. Select doted note (or rest)
2. Press "v", or untick "Visible"
3. Dot remains visible.

**Expected behavior**
Dot is marked invisible,or visible together with note (or rest)

**Screenshots**

https://user-images.githubusercontent.com/1646034/192146645-cc06869b-acdd-4e7a-9d12-8acc9ecaf222.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
May be (or may be not) related to #13114

**Comment by oktophonie** [comment]
See also #13047 (the issue itself, and the comment https://github.com/musescore/MuseScore/issues/13047#issuecomment-1240531175)

**Comment by bkunda** [comment]
🟢 Re-tested in 4.0.2. Remains FIXED.
