### ISSUE TITLE
[MU4.x Request] Allow the user to create custom time signatures (and tempo changes) without having to choose from (or add to) the palette 

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13481]
For the most part, I find the palette system in muse score pretty perfect.

Two exception are: time signatures and tempo changes.

I would love to have a simple dialog
to place custom times signatures into the score right away
without having to add them to the presets first. 

For example like in Dorico:

![image](https://user-images.githubusercontent.com/78870770/192111289-1ad8c31c-173e-4943-8661-590589fc37a6.png)
 
Same goes for tempo changes...

**Idea 1**:

A button for an universal input dialog
could be included into the palette.

![image](https://user-images.githubusercontent.com/78870770/192111830-8b74708d-9ccb-49d5-bc8f-e3ed12245178.png)

**Idea 2**:

The Shift-T dialog could gain an additional "place" button
which will place the time signature into the score right away...

![image](https://user-images.githubusercontent.com/78870770/192112455-4dca4ead-1901-4c2d-84d0-d129e13f4f76.png)

**Comment by randoguyname** [comment]
I can certainly get behind Idea 2 – I'd probably move the button down next to add however, like this:
<img width="875" alt="Screen Shot 2022-12-20 at 10 30 08 am" src="https://user-images.githubusercontent.com/43623624/208548176-959dd18a-0208-44e6-9ad9-2bbda131b81e.png">
I've tried to implement it but clearly I'm way out of my depth on this one; hopefully someone smarter than me can work on this feature.

**Comment by oMrSmith** [comment]
That's very good!

**Comment by oMrSmith** [comment]
You could also call the buttons:
"Place in score" versus "Add to palette"
so that no one gets confused what "add" means.

**Comment by randoguyname** [comment]
Good idea; i've figured out my problem so i think i can actually make a PR for this

**Comment by oMrSmith** [comment]
Cool, then I will finally have to learn how to download a PR ;)

**Comment by oMrSmith** [comment]
Hey @bkunda, ok, I understand. Thanks for your message on that.
