### ISSUE TITLE
[MU4 Issue] The 'cresc.' and 'dim.' Properties popups each consider and affect items of both types collectively

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#13485]
**Describe the bug**
_cresc._ and _dim._ lines are sometimes treated as the same type of object, and sometimes as different. This makes certain types of editing difficult.

**To Reproduce**
Steps to reproduce the behaviour:
1. In a score with both _cresc_. and _dim_. lines, right-click one and choose Select > Similar. All instances of both types of line will now be selected.
![image](https://user-images.githubusercontent.com/20604032/192138664-5a1c6c04-7848-4fb2-b408-28e614da62b3.png)
2. Observe that the Properties panel shows each type separately, indicating that they are considered as different types of object.
![image](https://user-images.githubusercontent.com/20604032/192138641-29b2b064-6e1c-4d9a-8447-7c9a6852f2f8.png)
3. If we open the popup for either and move to the Text tab, note that the text fields show "--", indicating that not all values are the same. In this context, evidently, both types of line are being considered collectively.
![temp-cresc-dim](https://user-images.githubusercontent.com/20604032/192139060-e61fb585-e724-4900-9cd5-32c8fdd859f0.png)
4. Let's say I want to change all instances of _dim._ to _decresc._, for example. I optimistically try typing that into the text fields; all instances of _dim._ AND _cresc._ now change.
![image](https://user-images.githubusercontent.com/20604032/192139128-b3459aa5-3910-4720-9f3f-c04de45003ac.png)

**Expected behaviour**
The popups in the Properties panel for _cresc._ and _dim._ lines should consider only lines of their respective types, and edits made to either should only affect items of that type.

**Platform information**
OS: Artix Linux, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3114077031, revision: github-musescore-musescore-7d36360

**Comment by HemantAntony** [comment]
@oktophonie Made a fix: #13578

**Comment by oktophonie** [comment]
Thanks @HemantAntony!
