### ISSUE TITLE
[MU4 Issue] Save to Cloud fails silently with unactivated account

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#13498]
**Describe the bug**
Using File > Save to Cloud with a not-yet-activated MuseScore account fails without giving any indication that it has failed.

By unactivated/not-yet-activated, I mean that the user has not yet clicked the "Activate your account" link in the confirmation email send during the account creation process.

**To Reproduce**
1. Home tab > My Account page > Create new account.
2. Enter new user details on website (do not open the activation email).
3. Return to desktop program and create a new score.
4. File > Save > Save to Cloud.
5. Follow Save to Cloud flow to the end.
6. Visit https://musescore.com/my-scores (notice score is not there).
7. Activate your account via the email.
8. Refresh https://musescore.com/my-scores (notice score is still missing).
9. Do Save to Cloud again (now the score appears online).

**Expected behavior**
Edit by @bkunda: 
Save should be allowed to fail and the user notified by the following dialogs: 
_Attempted save to cloud_
<img width="600" alt="Screenshot 2022-10-12 at 2 02 07 pm" src="https://user-images.githubusercontent.com/86290556/195337687-5dc20a39-80e3-4a15-a799-de0cf9a11e6b.png">

_Attempted publish to musescore.com_
<img width="600" alt="Screenshot 2022-10-12 at 2 02 16 pm" src="https://user-images.githubusercontent.com/86290556/195337723-02055362-e598-4a64-9804-871166c32930.png">

For all other error messages [listed below](https://github.com/musescore/MuseScore/issues/13498#issuecomment-1263673996), the following dialogs would be triggered:

_Attempted save to cloud_
<img width="600" alt="Screenshot 2022-10-12 at 3 35 13 pm" src="https://user-images.githubusercontent.com/86290556/195357070-ff7351ef-51a6-42cd-898a-ac9e74cec9ce.png">

_Attempted publish to musescore.com_
<img width="600" alt="Screenshot 2022-10-12 at 3 35 17 pm" src="https://user-images.githubusercontent.com/86290556/195357077-4e6b1131-e314-47c5-8520-e44ee6e67f93.png">

**Please note**
1. The first line of body copy would adopt the error messaging shown in the [table below](https://github.com/musescore/MuseScore/issues/13498#issuecomment-1263673996)
2. The "Get help" button would direct to the [Support forum](https://musescore.org/en/forum/6) 

**Platform information**
 - OS: macOS

**Comment by shoogle** [comment]
It looks like we need to implement dialogs for these possible errors on **saving a new cloud score**:

Code | Description
:---:|:---
400	| Invalid request.
403 | Forbidden. *User's account is not activated.*
422	| Validation is failed.
500	| Internal server error.

When **updating an existing cloud score**, all the same errors can occur but the meaning of 403 is changed:

Code | Description
:---:|:---
403 | Forbidden. *User is not owner of the score.*

Assuming we've all done our jobs properly, **403 account not activated** is the only one of the above errors that users should ever see, so it's the only one that needs a properly designed dialog with friendly text along the lines of "Your account is not yet activated. Please click the link in the activation email".

All the other errors are avoidable (including **403 not owner** because we would not seek to update a score that the user is not the owner of) but we should still display a dialog for each of them, even if it is just the error code and the message in the table above.

**Comment by cbjeukendrup** [comment]
@shoogle @bkunda Please check https://github.com/musescore/MuseScore/pull/13789 :)

**Comment by cbjeukendrup** [comment]
One thing to keep in mind: due to the architecture of MuseScore.org, it looks like we can only really link to the English support forum. (Support) forums of other languages have other IDs (e.g. the English one has ID 6, the Dutch one ID 38).

**Comment by shoogle** [comment]
@cbjeukendrup, there is https://musescore.org/forum. You could link directly to the support forum if the language is English and link to the generic page in other languages. That would work quite well actually because local support forums appear top in other languages (e.g. https://musescore.org/de/forum) whereas 'Announcements' is top in English so we don't want people to post there.

**Comment by cbjeukendrup** [comment]
@shoogle Thanks, done!
