### ISSUE TITLE
[MU4 Issue] Echo effect when enter Chord input mode quickly

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13499]
**To Reproduce**
1. Add Flute
2. Add some notes
3. Click a note and trigger chord input mode quickly (Ctr+K)

https://user-images.githubusercontent.com/90187801/192327949-1eb8f1a5-6d40-4018-94db-473f0855b3ce.mp4

**Platform information**
Windows10

**Additional context**
Can be related to #13206

**Comment by zacjansheski** [comment]
Does this still happen for you @DmitryArefiev ?

**Comment by DmitryArefiev** [comment]
@zacjansheski Yes, still occurs (**latest 4.2 master, Win10**). And as #13206, only with **MS Basic only**


https://github.com/musescore/MuseScore/assets/90187801/9bdb3516-6278-4e4c-8ed5-d9c47627ac54
