### ISSUE TITLE
[MU4 Issue] Reset buttons not working for Dynamics velocity and velocity change

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13504]
**Describe the bug**
If you press the reset buttons for velocity and velocity change of dynamics (Properties > General > Playback > Dynamics), you get an unexpected result (-1). You would expect it always to reset the value to the default.

Try it on the dynamics in the attached example score.
[dynamics_issue.zip](https://github.com/musescore/MuseScore/files/9654280/dynamics_issue.zip)

**Expected behavior**

Reset should always be to the default velocity? If at default, the reset should not be enabled.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3132978172, revision: github-musescore-musescore-294b8d8

**Comment by Tantacrul** [comment]
This one has been duplicated already - and we have removed the UI this bug refers to (it'll be in the next nightly or the one after that) so one way or another, this bug won't be relevant anymore.
