### ISSUE TITLE
[MU4 Issue] Dynamic velocity and velocity change aren't working

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13503]
**Describe the bug**

No matter what the setting of "Velocity" or "Velocity change" in Properties > General > Playback > Dynamics, there is no perceived difference in loudness in the score.

**To Reproduce**

1. Open attached score example. 
[dynamics_issue.zip](https://github.com/musescore/MuseScore/files/9654228/dynamics_issue.zip)
2. Click on the sfz marking.
3. Change velocity settings in Properties > General > Playback > Dynamics.
4. Playback and listen.

RESULT: No difference in playback loudenss. Seems to affect all dynamics; not just single-note.

**Expected behavior**

Adjusting velocity should affect playback as it did in MS3.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3132978172, revision: github-musescore-musescore-294b8d8

-----------------------------------------------------------------------------------------

https://user-images.githubusercontent.com/90187801/195646118-b1c55860-460a-4dd9-b31a-f8d3d665be7f.mp4

**Comment by DmitryArefiev** [comment]
Looks the same as #10990

**Comment by MarcSabatella** [comment]
Is it definitely the same?  The other issue is about the velocity settings on *notes*; this is about the velocity setting on *dynamics*.  Could well have the same root cause, of course, and maybe that's what you were able to determine already.  I just wanted to make sure there wasn't confusion about the difference in the issue reports themselves.

**Comment by DmitryArefiev** [comment]
> Is it definitely the same? The other issue is about the velocity settings on _notes_; this is about the velocity setting on _dynamics_. Could well have the same root cause, of course, and maybe that's what you were able to determine already. I just wanted to make sure there wasn't confusion about the difference in the issue reports themselves.

@MarcSabatella Yes, you are totally right! That can be a different issue and worth to be tracked separately.
 My fault, I I initially missed the difference.

Thanks!

**Comment by MarcSabatella** [comment]
Also the velocity change for hairpins - see https://github.com/musescore/MuseScore/issues/13550

**Comment by DmitryArefiev** [comment]
OK. Thanks!

**Comment by Tantacrul** [comment]
We need to remove the 'velocity' setting from both dynamics and hairpins to make way for a more universal system where velocity is measured in one place (and will be affected by dynamics... but just not in 4.0).

This should also be done for: https://github.com/musescore/MuseScore/issues/13550

**Comment by Tantacrul** [comment]
Created a new issue:
https://github.com/musescore/MuseScore/issues/13858
