### ISSUE TITLE
Shortcuts for Subscript and Superscript

### ISSUE THREAD

**Issue by Pistos** [musescore/MuseScore#13509]
We have Ctrl-B and Ctrl-I for bold and italics. That's good.
Please also add shortcuts for subscript and superscript of selected text.
I do this often on lyric text, and it's inconvenient to have to use the mouse on the toolbar at the bottom (subscript button) every time.

Originally reported in https://musescore.org/en/node/335417

**Comment by mmeyn** [comment]
Please assign to me, a PR will follow in a few minutes (if the build after rebase is successful).

**Comment by rgreen5** [comment]
Just an idea. LibreOffice uses Ctrl+Shift+P for su**p**erscript. And Ctrl+Shift+B for su**b**script.

**Comment by mmeyn** [comment]
In German, LibreOffice uses Ctrl+H for superscript (hochgestellt) and Ctrl+T for subscript (tiefgestellt). I like the easy shortcut without Shift but of course sub/superscripts are a niche “problem” of a scorewriter.

**Comment by Jojo-Schmitz** [comment]
We can't use those though, they are talken already

**Comment by shoogle** [comment]
It shouldn't matter if the shortcuts are already taken in MuseScore as long as the existing functionality is not needed during text editing. For example, <kbd>Ctrl</kbd>+<kbd>B</kbd> is the shortcut for "Insert measure at end of score", but that doesn't stop us also using it as the shortcut for "Format text bold".

FWIW, [Microsoft Office uses](https://support.microsoft.com/en-us/office/format-text-as-superscript-or-subscript-e989637a-12ec-4fe5-8b04-345342408abd) <kbd>Ctrl</kbd>+<kbd>=</kbd> for subscript and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>=</kbd> (i.e. <kbd>Ctrl</kbd>+<kbd>+</kbd>) for superscript.

**Comment by cbjeukendrup** [comment]
It would be good to make a decision about this, so that it can be added to #19164. Since we can't currently localise shortcuts, the LibreOffice ones might not be ideal, so we could decide to go with those from MS Office, although those are not particularly logical. Google Docs uses <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>.</kbd> and <kbd>,</kbd>, but those are not a good choice for macOS, where <kbd>Cmd</kbd>+<kbd>,</kbd> is always the shortcut for Preferences. Apple Pages uses <kbd>Cmd</kbd>+<kbd>Ctrl</kbd>+<kbd>+</kbd> and <kbd>Cmd</kbd>+<kbd>Ctrl</kbd>+<kbd>-</kbd>, but that does not translate well to other OSs that don't have both Cmd and Ctrl.
So I'd choose either the MS Office version or the unlocalised LibreOffice version.

**Comment by mmeyn** [comment]
> FWIW, [Microsoft Office uses](https://support.microsoft.com/en-us/office/format-text-as-superscript-or-subscript-e989637a-12ec-4fe5-8b04-345342408abd) Ctrl+= for subscript and Ctrl+Shift+= (i.e. Ctrl++) for superscript.

I don’t think this is the best option when defaults cannot be localised: For example, on german keyboard layout, 
<kbd>+</kbd> and <kbd>=</kbd> don’t share the same key but + is simply <kbd>+</kbd> and = is <kbd>Shift</kbd>+<kbd>0</kbd>. So these would be <kbd>Ctrl</kbd>+<kbd>+</kbd> and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>0</kbd> in german.

Having said this and now knowing about MuseScore’s impossibility of localised shortcuts I’d vote for english LibreOffice (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd>/<kbd>P</kbd>). Or no default.

**Comment by mmeyn** [comment]
Just found out: <kbd>Ctrl</kbd>+<kbd>P</kbd> and <kbd>Ctrl</kbd>+<kbd>B</kbd> input _**p**_ (piano) and ♭ (flat accidental). I cannot find the former in the file shortcuts.xml, there it only stands for plugin creator. The latter stands for `insert-b` but I think that’s not the flat accidental thing but a shortcut in note input mode.

**Comment by mmeyn** [comment]
I probably won’t have time to do anything about this until next week but if there is a decision about default shortcuts I can implement them then.
