### ISSUE TITLE
Score playback stops working with midi input device selected

### ISSUE THREAD

**Issue by azgilbertdh** [musescore/MuseScore#13514]
**Describe the bug**
When a midi input device is connected, scores do not play back. The playback cursor sits at the beginning of the score and wiggles back and forth. With same score open, just changing the input device to midi makes the playback stop working. Changing it to no device makes it playback again.

**To Reproduce**
1. Connect a midi device for input and set the device in preferences. (Mine is a Yamaha Reface DX).
3. Create or open a score.
5. Press playback button or space bar.
6. Behavior described above occurs.

**Expected behavior**
Score should playback through speakers. 

**Screenshots**

**Platform information**

MAC OS 12.5.1  

**Additional context**
![io](https://user-images.githubusercontent.com/110208963/192658055-74806fe6-a319-4bac-8ea1-8c53d7e42a56.jpg)

**Comment by cbjeukendrup** [comment]
Does this still happen in the released version?

**Comment by zacjansheski** [comment]
Since there has been no reply in over a month I am closing this issue
