### ISSUE TITLE
[MU4 Issue] Playback for certain parts stop working within a certain amount of time of working.

### ISSUE THREAD

**Issue by Simonlp95** [musescore/MuseScore#13513]
**Describe the bug**
Once a score is sufficiently complex I encounter an issue with playback. More accurately: Playback works fine until i start tinkering with notes. Sometimes newly edited notes become mute. Also sometimes entire staves/bars become mute, even when they played fine earlier. It seems like at memory issue, but I'm not sure. To be clear: This is inconsistent and it's only part of the music that's playing, while other parts are not playing.

**To Reproduce**
I have attached the file wherein the issue happens in a separate submission on your issue tracker. You should be able to reproduce with editing new notes and repeated playback. However you may need to have the program open ("work") for 20-30 minutes before the issue happens.

**Expected behavior**
Notes should play regardless of how they are manipulated.

**Screenshots**
![musescore issue copy](https://user-images.githubusercontent.com/114079270/192635063-443c708a-e337-40a8-add9-06f09f017fb1.jpg)

**Platform information**
 - OS: Windows 10

**Additional context**
I have submitted an identical issue post on your issue tracker, with the .mscz file attached

**Comment by cbjeukendrup** [comment]
@Simonlp95 Does this still happen in the latest version?

**Comment by zacjansheski** [comment]
Since there has been no reply in over a month I will close this issue.
