### ISSUE TITLE
[MU4 Issue] Page numbers should not be selectable

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13535]
**Describe the bug**
Page numbers are currently selectable, exposing a range of settings in the Properties panel that don't actually get saved to the score (changing these settings has a visible effect on the selected page numbers initially, but all changes are then lost when the score is closed and reopened again). 

See this discussion in [#12756](https://github.com/musescore/MuseScore/issues/12756#issuecomment-1257848021) for more info. 

**Expected behavior**
As a short-term solution, page numbers should not be selectable at all in order to avoid misleading the user. A more elegant solution could possibly be investigated for a 4.x release.

**Platform information**
 - MacOS, Win

**Comment by HemantAntony** [comment]
@bkunda Here ya go: #13540
