### ISSUE TITLE
[MU4 Issue] Unwanted "tap/click" noise at certain dynamic levels in MuseSounds grand piano 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13532]
**Describe the bug**
There is a noisy artefact that resembles a "tapping" or very subtle "clicking" sound in the MuseSounds grand piano instrument. This can be heard at moderate dynamic levels (when _mp_ or _mf_ dynamic markings are applied).

Demo video with narration: https://www.dropbox.com/s/dq8ygvfgdv6zpre/beta-audio-tapsound-softpiano-1.mov?dl=0
Demo video where the unwanted sound is heard across the middle dynamic range of a crescendo from _p_ to _ff_: https://www.dropbox.com/s/ujys7paskmedaly/beta-audio-tapsound-softpiano.mov?dl=0

**Expected behavior**
This unwanted noisy artefact should not be heard. Compare with MS Basic or another piano VST (E.g. Pianoteq) to hear it not present (Demo video: https://www.dropbox.com/s/at2ezagdyaw3qoe/beta-audio-tapsound-softpiano-2.mov?dl=0)

**Platform information**
 - MacOS 12.6 (M1)

FYI @Tantacrul

**Comment by lyrra** [comment]
In the first video, at 0:48, you are compensating over a bug, the play wont start from a note clicked at, if it already is selected.

**Comment by cbjeukendrup** [comment]
(But that bug is fortunately already fixed in a currently open PR)

**Comment by bkunda** [comment]
I've re-tested this on macOS and Windows 11 and I can no longer hear/reproduce this issue. 
Closing for now unless someone else reports it 🙂
