### ISSUE TITLE
[MU4 Issue] For Dim. hairpins "Height: new system" works the wrong way round

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13549]
**Describe the bug**

When a diminuendo hairpin extends to a new system the "Height: new system" is applied in error to the end of the first hairpin. The start of the hairpin on the following system does not change.

**To Reproduce**

1. Open the attached score. 
[extend_dim_hairpin.zip](https://github.com/musescore/MuseScore/files/9683580/extend_dim_hairpin.zip)
2. Select the dim. hairpin and increase the "Height: new system" (Properties >Hairpin > Style).

RESULT: The height of the end of the first hairpin increases, but the height of the start of the continuation hairpin remains the same.

**Expected behavior**

The height of the start of the continuation hairpin should change, while the height at the end of the first hairpin remains unchanged.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3156357780, revision: github-musescore-musescore-581a5f9

**Comment by cbjeukendrup** [comment]
Actually I think this is working as desired. "Height" always controls the height of the 'open' end, "Height (new system)" always controls the height of the 'closed' end when continuing to a new system.
<img width="695" alt="Scherm­afbeelding 2022-10-01 om 18 37 37" src="https://user-images.githubusercontent.com/48658420/193419457-41bb0ea1-2ff8-49dd-a04a-324414d9794a.png">
@oktophonie Do you agree?

**Comment by oktophonie** [comment]
I do agree (though arguably a better name could be found; also, ideally, it wouldn't be possible to set it to a value equal to or greater than the main height).
