### ISSUE TITLE
[MU4 Issue] fp dynamic plays as f (no drop to p)

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13543]
**Describe the bug**
The "fp" dynamic (and similar) does not play correctly - you get the "f" but not the change to "p" after.

**To Reproduce**
1. Score for trumpet
2. Add a whole note
3. Add an "fp" dynamic to it
4. Play
5. Hear error: volume is "f" throughout

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1799936/193162583-50f5d71a-f5b6-45e2-8870-e063b2c174ae.png)

**Platform information**
 - OS: Linux

**Additional context**
This is one issue I hadn't caught yet using my MuseScore Cafe theme score - https://musescore.com/user/2975/scores/6656770.  That's the MuseScore 3 version; I'm working on a MuseScore 4 update to take advantage of things like the fall playback.

**Comment by MarcSabatella** [comment]
I don't know for sure if it was ever working in MU4, but I tend to doubt it.  I check nightly builds on this score on a pretty regular basis, but until recently there were enough other problems that this one could easily have escaped notice.  Oldest build I have handy to test is the alpha 2 from early August, and I can confirm it was a problem then.  Sorry for not catching it sooner, but dynamics were a complete mess (mostly because of all the articulation weirdnesses), so it was very easy to miss.

FWIW, the three scores I'm always checking are this one ("MuseScore Café" theme), Reunion, and the one I sent you to check with Muse Sounds - the "Music Master Class" theme.  All three sounded pretty bad just a couple of months ago, but gradually almost everything has been fixed.   At this point, Music Master Class is fine (at least with MS Basic and VST instruments - not sure if Muse Sounds will still show the odd portamento effect we heard a few weeks ago).  Reunion is good except for pedal playback.  And the MuseScore Café is good except for this "fp" issue plus falls/glissandi on tied notes - https://github.com/musescore/MuseScore/issues/12971.  Well, also https://github.com/musescore/MuseScore/issues/13544 but that is understandably being put off, and I'm now working around that using "doits" which are close enough.

**Comment by cbjeukendrup** [comment]
@RomanPudashkin Are you working on this currently? I have an idea for a solution, based on 3.x, which I could have ready today.

**Comment by DmitryArefiev** [comment]
Fixed in #14788
