### ISSUE TITLE
[MU4 Issue] Hairpins: ""Velocity change" not working as expected

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13550]
**Describe the bug**

Note velocity does not change over the range of a hairpin as much as expected even with a soft dynamic at the beginning, and a high "Velocity range setting" for the hairpin.

Compare playback of MS4 with, say, playback of the same MIDI file through another sequencer.

**To Reproduce**

1. Open the attached file. 
[hairpin_velocity_change.zip](https://github.com/musescore/MuseScore/files/9683896/hairpin_velocity_change.zip)
2. Play back.

RESULT: With a ___pp___ dynamic at the beginning of the hairpin and a velocity change of 90, one would expect the range of volume to be far greater than it is.

**Expected behavior**

A reasonable increase/decrease in volume commensurate with the start dynamic and the velocity change setting.

**Platform information**

 OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3156357780, revision: github-musescore-musescore-581a5f9

**Comment by Tantacrul** [comment]
We want to move away from the idea that hairpins and noteheads have separate velocities and only have one velocity setting. With that in mind, I'm unsure if we want to do this. Let me confirm.

**Comment by Tantacrul** [comment]
Created a new issue:
https://github.com/musescore/MuseScore/issues/13858
