### ISSUE TITLE
Allow to disable reverb

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13551]
It would be useful to have the option to disable reverb. 

One use case is adding your own custom reverb instead. 

Another use case is testing: the reverb setting can make it difficult to hear underlying playback problems.

**Comment by cbjeukendrup** [comment]
See also https://github.com/musescore/MuseScore/issues/16466#issuecomment-1438360872

**Comment by RomanPudashkin** [comment]
Will be implemented as a part of #16466
