### ISSUE TITLE
[MU4 Issue] Sound/channel changes not imported correctly from MuseScore 3

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13567]
**Describe the bug**
Scores from MuseScore 3 that use any of the various subchannels (arco/pizz for strings, mute/open for trumpet, distortion/palm mute/harmonics/etc for guitar) are not playing back correctly - all sounds are normal

**To Reproduce**
1. Open a MuseScore 3 score that uses any of the various provided subchannels (see attached, for instance) for sound changes
2. Play
3. Hear error: playback is normal

**Expected behavior**
Playback should use the specified sound

**Platform information**
 - OS: Linux

**Additional context**
I get that the mechanism is different between MU3 and MU4, but we do have the capability in MU4 to play these sounds - we should try to do the necessary mapping to the new facility on import

Rename to mscz:
[sounds.zip](https://github.com/musescore/MuseScore/files/9690828/sounds.zip)

**Comment by MarcSabatella** [comment]
@cbjeukendrup @jeetee If it's too late to consider an import migration plan for 4.0, I wonder if it would be possible to build a plugin to convert the old-style "staff texts" into new-style "playing technique annotations" as appropriate?  I kind of guess the new element might not be exposed in the framework yet.  But if *that* much is simple, then it could provide a path forward.  I'm really concerned that a *huge* percentage of existing scores won't play correctly because of this.

**Comment by jeetee** [comment]
The import approach should be hugely favored.
Even if we make the new annotations plugin API accessible and creatable (which would be nice regardless) a plugin can only run on the import result. Which means the subchannel data is already lost at that point. Of course we can perform an educated guess as to that text with the correct content (mute/open/arco/pizz) are very likely things to be replaced with the new entity it remains nothing more than guessing the intention.

**Comment by abariska** [comment]
🟢 **FIXED**
