### ISSUE TITLE
[MU4 Issue] Bad rendition of slurs

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13560]
**Describe the bug**

This was partially fixed in #13402. But in the attached score you can see two more examples of bad slur rendition in measures 7 and 8.

![image](https://user-images.githubusercontent.com/20604032/193448171-7903bf77-0c48-45b3-8fd7-9b18156a19a4.png)

[slur_placement.zip](https://github.com/musescore/MuseScore/files/9687307/slur_placement.zip)

**Expected behavior**

The flipped slurs should appear as they were in MS3.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3156357780, revision: github-musescore-musescore-581a5f9

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3194503368, revision: github-musescore-musescore-46fece3

Here's another test case. See measures 1 and 3.
[badly_formed_slurs.zip](https://github.com/musescore/MuseScore/files/9724506/badly_formed_slurs.zip)

**Comment by mike-spa** [comment]
Thanks, those are now all fixed in the linked PR
