### ISSUE TITLE
[MU4 Issue] Playback: tremolos, glissandos, grace notes are not scaled according to tuplet or local time sig

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#13576]
**Describe the bug**
The duration of NoteEvents that are generated by tremolos, glissandos, grace notes and possibly various ornaments is not adjusted according to tuplets or local time signatures. The durations of those generated notes are based on "normal" ticks, like if there were no tuplets (nor local time sigs). But of course, a quarter note under a tuplet has a different duration than a quarter note outside a tuplet.

For normal notes, the duration and timestamps are okay. It's only about "generated" notes.

**To Reproduce**
You could create a score like this:
<img width="543" alt="Scherm­afbeelding 2022-10-02 om 03 12 39" src="https://user-images.githubusercontent.com/48658420/193433792-25a9bdf2-9f3b-41a6-9e96-b7ec239d51f2.png">
Here I'm using custom "duplets" with ratio 2 : 1 whole notes. Both staves should sound identically, but they don't at the moment: the second staff gives very unexpected results.

**Additional context**
This was originally reported for tremolos in #13369, but turns out to be a more general problem.

**Comment by bkunda** [comment]
I can confirm that this issue, at least insofar as it pertains to tuplets, is still valid.
@Tantacrul this can produce completely incorrect results in playback. I'll leave it you to triage accordingly.

**Comment by Tantacrul** [comment]
@bkunda [made this](https://musescore.com/user/40633747/scores/9057425/s/GBmbOh?share=copy_link): which helps demonstrate the problem. In particular, the first issue with tremolos is the most problematic.
