### ISSUE TITLE
[MU4 Issue] Playback: Notes entered into a part score do not play

### ISSUE THREAD

**Issue by dragonwithafez** [musescore/MuseScore#13577]
**Describe the bug**
Entering notes into a part score causes them to not play back unless the score is reloaded, or the Play property of the notes is un-toggled then re-toggled in the main score. Additionally, the Play property is completely absent when working on part scores.

**To Reproduce**
1. Create a new score
2. Create a part score for one of the instruments
3. Enter some notes
4. Click on one of the notes and press Space to begin playback
5. Note that there is no sound
6. Navigate back to main score
7. Select the entered notes
8. Either:
8a. Uncheck and re-check the "Play" property in the inspector
8b. Reload the score
9. Attempt playback again
10. Note that the score plays properly

**Expected behavior**
Notes should be playable as soon as they are entered into a part score.

**Screenshots**

https://user-images.githubusercontent.com/57819859/193436542-22398509-502f-4c07-b56f-bc0e9ccbac17.mp4

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-, revision: github-musescore-musescore-
Tested using a self-built version, but also present in the past couple of nightlies (don't know exactly when)

**Additional context**
I believe this is a regression, though I couldn't tell you exactly when it changed.

**Comment by DmitryArefiev** [comment]
Fixed in #13598
