### ISSUE TITLE
[MU4 Task] Fix enums in the plugin API (but how?)

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#13585]
**Task description**
Currently, enums are broken in the plugin API. This affects many plugins, also those few that we want to pack with MuseScore, so it really needs to be solved.

**How are enums designed to work in the plugin API?**
An enum is exposed as an object of type `Enum`, which is not much more than a map from the name of an enum case to the value of that enum case. For example, the ElementType enum gets represented somewhat like this:
```js
{ 
    "CHORD" : int(ElementType::CHORD),
    ...
}
```
So it can be used in QML as `Element.CHORD`, which has type int, where `Element` is the name under which the enum is exposed.

**How is such an enum object constructed?**
Such an object is populated with the help of QMetaEnum. We create a QMetaEnum using `QMetaEnum::fromType<ElementType>()`, and then loop over the key/value pairs that it offers.
QMetaEnum offers these data based on the data that is collected by Qt's meta object compiler (moc). 

**And that is where it goes wrong...**
There are basically two limitations that make our life very difficult:
- The moc can not look in included files
- When using Q_NAMESPACE to expose enums that are in a namespace to the moc, all those enums must be in the same file, because if you put Q_NAMESPACE in the same namespace in multiple files, the moc will generate the definition of the static meta object in all the moc files for all those files, leading to conflicting redefinitions. 

**Solutions**
1. We could try to organise everything in such a way that we work around it. That means, we put all enums that we want to expose from the engraving module in one file, put Q_NAMESPACE macro in that file, and make all enums Q_ENUM_NS. It would probably work, but it's not nice, since we need to put a lot of stuff in one file, most notably the SymId enum too. 
(Note that the trick of putting the actual SymId enum in symid_p.h and then #including that, _does not work_ either, because moc can't look in included files, so it can't see the enum and ignores the Q_ENUM_NS macro.)

2. We could _copy_ all enums to the plugin api module, so that the engraving module stays clean as it is. The obvious big disadvantage is that we need to keep all that stuff in sync, which is guaranteed to go wrong at some point. And... copying SymId is not a particularly fun thing to do...

3. We could put all enums in the Engraving module in Q_GADGET wrapper classes (or Q_NAMESPACE wrapper namespaces), and use a typedef to be able to use the enum normally, i.e. 
    ```c++
    class SymId_wrapper {
        Q_GADGET
     public:
        enum E {
            .......
        };
        Q_ENUM(E)
    };
     using SymId = SymId_wrapper::E;
     ```
    (In the past, this has been done using a macro, but that macro needed to be copied in every file where it was used (because moc does still not look in included files), which kind of defeats the purpose of a macro.)

    But this has two big disadvantages: 
    - it requires polluting the engraving module
    - it makes it difficult to forward-declare enums, so we need to #include the whole file that contains the definition of the enum, even in header files where we only use the name of that enum -> more #includes -> even slower compile times

4. We could try to say farewell to the whole moc (at least for the engraving module and plugin API): meet [verdigris](https://github.com/woboq/verdigris). This is a library that consists of 3 header files, containing thousands of lines of C++/preprocessor magic, that can do almost everything the moc can do, but without a moc. It is binary-compatible with Qt, so the meta objects generated by verdigris can simply replace those generated by the moc. 
At a first glance, verdigris seems pretty great, since it is simply C++ and thus you don't need to worry about stupid things like that it can't look in #included files. 
However, there turns out to be a catch when it comes to enums: in the W_ENUM_NS macro, you (currently) need to write all enum cases by hand. Not much better than copying the whole enum, you'd say...
I was hoping we could do a trick like this:
     ```c++
    // --- elementtype_cases.h
    CHORD,
    NOTE,
    ...

    // --- types.h
    namespace mu::engraving {
    enum class ElementType {
        #include "elementtype_cases.h"
    }
    W_ENUM_NS(ElementType,
        #include "elementtype_cases.h"
    )
    ```
    But no, clang is pretty clear: `error: embedding a #include directive within macro arguments is not supported`.

5. However, we _can_ use a variation on that #include trick if we decide to circumvent any kind of meta object stuff. Like this:
     ```c++
    // --- elementtypes.h
    #ifndef ELEMENT_TYPE
    #define ELEMENT_TYPE(enum_case)
    #endif

    ELEMENT_TYPE(CHORD)
    ELEMENT_TYPE(NOTE)
    ...

    #undef ELEMENT_TYPE

    // --- types.h
    namespace mu::engraving {
    enum class ElementType {
        #define ELEMENT_TYPE(enum_case) enum_case,
        #include "elementtypes.h"
    }

    // --- somewhere in the plugin api
    QHash<QString, int> elementTypeCaseNameToValue {
        #define ELEMENT_TYPE(enum_case) { #enum_case, (int)enum_case },
        #include "elementtypes.h"
    }
    ```
    Credits: I saw this #include trick for the first time in [apple/swift](https://github.com/apple/swift).

    And yes, this also requires changes to the engraving module, but it is not super terrible because we can still make our own decisions. 

Anyway, enough funny / not funny solutions, but **which solution is the best / least painful?**

---

*Encore*: the #include trick is also extensible. How about this idea:
```c++
// --- elementtypes.h
#ifndef ELEMENT_TYPE
#define ELEMENT_TYPE(enum_case, class_name)
#endif

ELEMENT_TYPE(CHORD, Chord)
ELEMENT_TYPE(NOTE, Note)
...

#undef ELEMENT_TYPE

// --- types.h
namespace mu::engraving {
enum class ElementType {
    #define ELEMENT_TYPE(enum_case, class_name) enum_case,
    #include "elementtypes.h"
}

// --- engravingobject.h
class EngravingObject {
    ...
    
    #define ELEMENT_TYPE(enum_case, class_name) bool is##class_name() const { return type() == ElementType::enum_case; }
    #include "elementtypes.h"
}

#define ELEMENT_TYPE(enum_case, class_name) \
    static inline class_name* to##class_name(EngravingObject * e) { assert(e == 0 || e->is##class_name()); return (class_name*)e; } \
    static inline const class_name* to##class_name(const EngravingObject * e) { assert(e == 0 || e->is##class_name()); return (const class_name*)e; }
#include "elementtypes.h"

// Now we have e->isChord() and toChord(e)!

**Comment by cbjeukendrup** [comment]
@igorkorsukov I thought it'd be good to ask for your input on this :)

**Comment by igorkorsukov** [comment]
@cbjeukendrup I like option 2 or 5 :)

Option 2 partially implemented (excluding the largest enums) https://github.com/musescore/MuseScore/blob/master/src/plugins/api/apitypes.h

The main arguments for this option are:
* I am an ardent supporter of the fact that it is necessary to give only what you clearly want to give, what you are ready to support, to public access.
* This option will easily allow us to maintain backward compatibility, i.e. there should be no problem for us to be able to rename enum, but we should not break third-party plugins. To adapt plugins for each version, I think it's a bad idea. that is, the API must have either versioning (and stability within the version) or backward compatibility


I can consider options 5 as a fairly simple temporary solution to make the current plugin system work. With an eye that, for example, next year a new plugin system will be created that has either a versioned API or backward compatibility, which does not restrain the development of the musescore itself

**Comment by cbjeukendrup** [comment]
Thanks @igorkorsukov! I chose solution 2, because I agree with your arguments, and it seems the most straightforward option.
