### ISSUE TITLE
[MU4 Issue] Hairpin end line not visible for hairpins added from palettes after selecting an element

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#13581]
**Describe the bug**
When you add a hairpin by selecting a note and clicking a hairpin cell, the hairpin loses its end line

**To Reproduce**
1. Open a score and enter some notes
2. Select
3. Add hairpin from palette
4. The end line isn't visible

**Expected behavior**
The end lines should be visible

**Screenshots**

https://user-images.githubusercontent.com/88136054/193449434-2fcbefc7-73ea-44e1-a819-7310a67d298e.mp4

**Platform information**
 - OS: Ubuntu 22.04 LTS

**Comment by shoogle** [comment]
I think these lines start on one note and end on the very next note, which means they are too short for you to see the end, but the end is there and you would see it if you made the line longer.

When you add a line with two notes selected, the line will extend between those two notes, but that only works when exactly 2 notes are selected.

Perhaps when 1 or 3+ notes are selected the lines should extend from the selected note to the end of the measure. This would ensure the line is (usually) long enough to see the end.

**Comment by HemantAntony** [comment]
Ah that makes sense, let me see if I can fix this :)

**Comment by zacjansheski** [comment]
I will close this as it doesn't seem very problematic.
