### ISSUE TITLE
[MU4 Issue] Unable to change apperance/playback

### ISSUE THREAD

**Issue by jieshunwang** [musescore/MuseScore#13589]
**Describe the bug**
When trying to change the apperance/playback of a specific note, the user is unable to select or change any of it.

**To Reproduce**
1. Start a new score.
2. Select either 'Playback' or 'Appearance' in the Properties tab.
3. Click on any property.
4. The pop-up dissappears.

**Expected behavior**
Should be able to change property after clicking it. The pop-up should **not** dissapear.

**Screenshots**

https://user-images.githubusercontent.com/39250962/193515335-e856ca96-c37a-4042-a382-cccf4c8b2b35.mp4

**Platform information**
Edition	Windows 11 Home
Version	22H2
Installed on	‎28/‎09/‎2022
OS build	22621.521
Experience	Windows Feature Experience Pack 1000.22634.1000.0

**Comment by zacjansheski** [comment]
Closing as done
