### ISSUE TITLE
[MU4 Issue] New shortcut (t) to create ties is effective without being mapped

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#13595]
![image](https://user-images.githubusercontent.com/78870770/193574273-2669c867-3e3b-4fe1-b546-f392dbda367a.png)

![image](https://user-images.githubusercontent.com/78870770/193574620-28a40f35-83ab-4c1a-92bb-40ece54e8333.png)

_Originally posted by @oMrSmith in https://github.com/musescore/MuseScore/issues/13591#issuecomment-1265354883_

**Comment by Eism** [comment]
Reset preferences and try again

**Comment by oMrSmith** [comment]
Ok, that solved it. Wouldn't have come to this idea. Thanks.
