### ISSUE TITLE
[MU4 Issue] Adding "Title" (etc.) text from menu doesn't create a title frame if there are no frames in the score

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13590]
Edit @Tantacrul:

I've created a video to demonstrate
https://www.dropbox.com/s/7rkgsg2plgy7e80/Can%27t_Add_Title_to_Score_01.mov?dl=0

---

**Describe the bug**

If there are NO frames in the current score, when you attempt to add "Title" text (etc.) from the Add menu, NO frame is created.

**Expected behavior**

As in MS3. A title frame is created at the beginning of the score.

**Platform information**

 OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3171545449, revision: github-musescore-musescore-3d92b93

**Comment by Tantacrul** [comment]
I've created a video to demonstrate
https://www.dropbox.com/s/7rkgsg2plgy7e80/Can%27t_Add_Title_to_Score_01.mov?dl=0

**Comment by DmitryArefiev** [comment]
Fixed in #17265
