### ISSUE TITLE
[MU4 Issue] Chord symbol playback while editing has very short duration or does not work

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#13604]
**Describe the bug**
- During normal playback (i.e. after pressing the "Play" button), chord symbols "always" work properly, with Fluid, VST and Muse Sounds.
- Chord symbol playback while editing (i.e. clicking on a chord symbol, etc), doesn't work that flawlessly; this is the current status:
    - Fluid: no playback
    - VST: no playback
    - Muse Sounds: very short playback

**To Reproduce**
1. Have a score with chord symbols
2. Trigger a chord symbol to playback while editing (at the moment, a chord symbol seems to be triggered when you double click it to edit it and then move around with the blue text cursor within the chord symbol text. Not sure whether that's desired behaviour 🤔)
Either you'll hear nothing, or you'll hear a very short sound.

**Expected behavior**
Chord symbol played at the same length as when a note is played in Note Input Mode

**Platform information**
 - OS: reported on macOS

**Comment by MarcSabatella** [comment]
Not sure what you mean about the text cursor, maybe you mean Ctrl+Right which completes entry and moves to the next measure?  Or if youhit Space or Esc or any of the other shortcuts that complete chord symbol entry.

For me on Linux, they play, but excruciatingly loudly compared to anything else.  Been this way for some time.  Playback volume reasonably during playback, but crazy loud during editing.

**Comment by Tantacrul** [comment]
Thanks for pointing this out. Hadn't tried chord symbols for a while. @cbjeukendrup - you mentioned in your description a few things.

- They sometimes don't play back using fluid. This is a possibly quite a major issue. If so, could you include it here as an expected result more clearly.

- You mentioned VST isn't working at all. Can you make this a separate issue and give appropriate details, etc. Also tag me on it because it sounds like a beta 1 issue.

**Comment by cbjeukendrup** [comment]
- When pressing "play", chord symbols "always" work properly, with Fluid, VST and Muse Sounds. Maybe my comment was ambiguous about that.

- It looks like the VST problem is something with my local builds, since it looks fine in nightly builds. So it's still a pity for me, but there is no real bad problem in general. Probably messed up something with my build settings, although I wouldn't know what exactly...

- For chord symbol playback while editing, the status is the following:
    - Fluid: no playback
    - VST: no playback
    - Muse Sounds: very short playback

**Comment by MarcSabatella** [comment]
For me clicking on a chord is the same as entering it in the first place - normal length, much louder than anything else.  That's using default playback.  Here is a sample, brand new score created using Piano instrument:

https://youtu.be/smIgTD-y-e4

**Comment by cbjeukendrup** [comment]
Hm, that's indeed as it should be, except for the loudness. I don't understand why it is so broken for me then... I get no playback when clicking on a chord symbol. I'll try on some other OSs and machines.

**Comment by cbjeukendrup** [comment]
On Windows, it works 100% fine for me too. (I also notice that the loudness problem only seems to occur with Fluid. VST and Muse Sounds sound fine.)

**Comment by Tantacrul** [comment]
@cbjeukendrup - to confirm, is the stated issue solved? If there is a question about loudness, I'd say it should be a separate issue (probably is already)

**Comment by cbjeukendrup** [comment]
Nope, on my Mac it is still just not working. 
For the loudness, we have enough separate issues, for example #13412 and #13327.

**Comment by cbjeukendrup** [comment]
News: it looks like this only occurs in builds created on my own computer. In builds from GitHub it seems fine, even on my Mac. Quite annoying that I can't trust my own builds anymore. Debug vs Release doesn't seem to be the problem. I'll have to experiment a bit...

**Comment by cbjeukendrup** [comment]
On my old Intel Mac it also works correctly in home-made builds. So it's really a problem of my MacBook. The two main things that are different between the two Macs are the compiler version (MacBook has AppleClang 14, iMac has AppleClang 13.1) and the architecture (arm64 vs x86_64). So I'm gonna try what happens if I use AppleClang 13.

**Comment by Tantacrul** [comment]
Moving to post beta for now, since it's a little unclear exactly how to address the problem. However, there are loudness and interaction problems that we can address now and we've got issues for those. (I'm creating one of them now).

**Comment by cbjeukendrup** [comment]
In my own builds, chord symbol playback while editing still does not work at all (with MS Basic nor Muse Sounds); there is simply no sound at all currently. But since it does seem to work in the release build, I guess I'll close this.
