### ISSUE TITLE
[MU4 Task] [Accessibility] First navigation command should select first element

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#13608]
**Task description**
When a score has just been loaded and nothing has yet been selected:

- Pressing the next-element shortcut (Alt+Right) should select the very first element in the score. This will be the title frame if there is one, otherwise it could be a barline or clef at the start of the first system.
- Pressing the play-next-chord shortcut (Right) should select the very first note or rest in the score.

Please note that the selection should only take place after the shortcut is pressed. Prior to this, the notation view should have focus but nothing within it should be selected (see #10428).

**Comment by L0uisc** [comment]
I'm looking into this.
