### ISSUE TITLE
[MU4 Issue] viewport doesn't follow expanding range selection - regression

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13619]
**Describe the bug**
When expanding selection by "Shift + Right" or "Shift + Left", viewport doesnt follow it, selection goes out off screen.

**To Reproduce**
1. Select some range selection
2. Expand it by "Shift + Right"
3. When selection goes out of screen, viewport doesnt follow it.

**Expected behavior**
Viewport follows expanding selection.

**Screenshots**

https://user-images.githubusercontent.com/1646034/193924356-5927b326-e119-4474-91ec-b092eb95bd1c.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
Regression from MU3.

**Comment by zacjansheski** [comment]
Is this still an issue?  I don't see this behavior in the current master.

**Comment by sammik** [comment]
@zacjansheski You are right, thank You.
