### ISSUE TITLE
[MU4 Issue] Changing staff properties causes clef to change

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#13610]
**Describe the bug**
Changing staff properties (instrument label, toggling small stave, etc) can cause the instrument's clef to change.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new score with the 'Treble clef' template (which is a single-stave piano really)
2. Right-click the stave and open the Staff/Part properties... dialog
3. Change something - tick the 'Small staff' box, or change the long or short instrument name (I haven't tried changing every single option so can't say that every setting triggers this)
4. Note that the initial clef changes from treble to bass

I have observed this in other 'real' scores, not just in this template file, but this is the simplest situation in which I can reproduce it. It does not happen 100% consistently in other scores but I'm not sure why.

**Expected behaviour**
The clef should not change - unless perhaps a relevant setting is altered, like replacing the instrument. 

https://user-images.githubusercontent.com/20604032/193794126-d6d76fd2-670d-4b55-bfb0-4ef29003e0fe.mp4

**Platform information**
- OS: Artix Linux, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3174926639, revision: github-musescore-musescore-574c36f

**Comment by sammik** [comment]
> 3. Change something - tick the 'Small staff' box, or change the long or short instrument name (I haven't tried changing every single option so can't say that every setting triggers this)

You dont need to change anything, just press "Apply".

**Comment by oktophonie** [comment]
So it appears! Thank you.
