### ISSUE TITLE
[MU4 Issue] Recovery dialog does not appear after a crash

### ISSUE THREAD

**Issue by dragonwithafez** [musescore/MuseScore#13621]
**Describe the bug**
When opening MU4 after a crash, the dialog box to allow the user to recover the previous session does not appear visibly, but still takes focus away from the main application, requiring the user to use the keyboard to close the dialog box to continue.

**To Reproduce**
1. Open a score
2. Crash MuseScore somehow, e.g. using the crash button in dev settings
3. Re-open MuseScore
4. Attempt to click on anything; note that no interaction is possible
5. Press Enter or Escape to close the invisible dialog
6. The application can now be used

**Expected behavior**
The dialog should actually be visible.

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-, revision: github-musescore-musescore-

**Additional context**
Regression; last worked in nightly build from Sept 28

**Comment by Eism** [comment]
@dragonwithafez 
Please check the build from https://github.com/musescore/MuseScore/pull/13443

**Comment by dragonwithafez** [comment]
@Eism No, that doesn't seem to change anything.

**Comment by cbjeukendrup** [comment]
In https://github.com/musescore/MuseScore/issues/13635#issuecomment-1268620828, which is a suspiciously similar issue but with the New Score wizard, Marc says that the wizard appears _under_ the main window.

Is that maybe the case for the recovery dialog too?

**Comment by SilverGreen93** [comment]
Can confirm this one as well. In my case the window was outside of my screen, as in #13635

**Comment by dragonwithafez** [comment]
Yes, same issue. You can also easily reproduce it by just un-maximizing the main MuseScore window. It will disappear until you do the Alt-Space trick.

**Comment by Eism** [comment]
@dragonwithafez 
Please check the build from #13645
