### ISSUE TITLE
[MU4 Issue] Space does not restart playback after completion

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13638]
**Describe the bug**
Play a score to completion.  Press Play to hear it again - nothing happens

**To Reproduce**
1. Open a score
2. Click within one of the last measures
3. Press Space to play
4. Wait for playback to finish
5. Press Space again
6. See error: nothing happens

**Expected behavior**
Playback should restart from the beginning

**Platform information**
 - OS: Linux

**Additional context**
Playing from the beginning is how it worked in MU3, so that's my expectation.  One could probably make a case for restarting at the selected location instead.

**Comment by MarcSabatella** [comment]
I can't reproduce anymore.  Maybe one of the recent playback fixes (like the one adding the audio tail) fixed it.  Did anyone else ever see this, and is it fixed for you, too?

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3216906122, revision: github-musescore-musescore-eb51740

Seems fixed here.
