### ISSUE TITLE
[MU4 Issue] Creating new score opens a new window outside the screen area

### ISSUE THREAD

**Issue by SilverGreen93** [musescore/MuseScore#13635]
**Describe the bug**
When trying to create a new score while having another score already opened, the new window that opens will freeze and cannot do anything until it is killed.

**To Reproduce**
1. Open an existing score or create a new empty score.
2. Go to File -> New. This will open a new window (as expected for MU4).
3. The new window opens, but you cannot interact with it. The whole UI is freezed and just beeps no matter where you click on it.
4. The old windows is still operational.

EDIT: It seems that the new score dialog is shown outside the visible area of the screen.

**Expected behavior**
The new windows should present the New score dialog and do not freeze.

**Platform information**
Windows 11
MuseScoreNightly-202210040448-master-789056a

**Comment by cbjeukendrup** [comment]
> the new score appears, but also hidden underneath the Home window, so again you need to explicitly switch to it.

This confuses me a little bit, because the new score should appear in the same window as the home tab (just different tabs in the same window). Or is something going on with multiple instances of MuseScore?

**Comment by DmitryArefiev** [comment]
@MarcSabatella @SilverGreen93 Strange.. but I **can't reproduce** it nor on Windows10/11 nor on Ubuntu (latest master)

**Comment by SilverGreen93** [comment]
I did investigate more and sort-of found out that the issue in my case is that i'm using a dual monitor setup. My primary monitor is on the right and the secondary one on the left. The dialog box shows up on the left-most secondary screen, but outside the screen area (so I need the Alt+Space trick to get it back to a visible area).

If I disconnect the second monitor and restart MU4, the window are now showing correctly.

Furthermore, it seems (for now at least) that after connecting back the second monitor does not make the problem reproduce anymore (maybe some offsets are saved?).

Will try to reproduce again after a couple of reboots and/or monitor arrangements.

**Comment by Eism** [comment]
@SilverGreen93 
Please check the build from #13645

**Comment by dragonwithafez** [comment]
@SilverGreen93 Pretty much the same exact situation for me. In my case the second monitor was below my primary but otherwise things were the same. I will also continue testing, both for this issue and https://github.com/musescore/MuseScore/issues/13621.

**Comment by oMrSmith** [comment]
I'm on Windows 10 with 2 monitors, the main one is left.
If I open a score and then try to open another
new score,
the window opens but it is frozen.

Same thing happens if I try to relaunche MU4 after it has crashed.

**Comment by oMrSmith** [comment]
Just run the latest nightly build: Actually starting a new score opens a frozen window where I can't click on "new score".

**Comment by Eism** [comment]
@oMrSmith 
Could you please test the build from https://github.com/musescore/MuseScore/pull/13645?

**Comment by HemantAntony** [comment]
You, my friend, are in luck. We just created a page for that: [click here](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds)

**Comment by sammik** [comment]
@oMrSmith and here is direct link to [test build](https://github.com/musescore/MuseScore/suites/8651217634/artifacts/389070838)

**Comment by oMrSmith** [comment]
Oh, thank you both. I'll check it out now.

**Comment by oMrSmith** [comment]
Did a quick test: CTRL+N opens a new instance, shows the home screen and brings up the "choose instruments" dialog, no "freeze".

**Comment by SilverGreen93** [comment]
For me, I cannot reproduce anymore any of the bugs with either the original build or the updated ones.

**Comment by Eism** [comment]
@oMrSmith @SilverGreen93 
Sorry guys, but could you please test a new build? I reverted some changes

https://github.com/musescore/MuseScore/suites/8833286913/artifacts/402507063

**Comment by MarcSabatella** [comment]
The updated build Linux works for me just as well as the previous version I tested.  Both versions fix all three symproms I have been seeing:

1. when creating a new score with a score already open, the new score wizard was appearing behind the main window
2. after completing wizard, the new score itself was appearing behind the current score
3. after a crash, the restore dialog was appearing behind the main window
