### ISSUE TITLE
[MU4 Issue] Crash when changing time signature in score with parts

### ISSUE THREAD

**Issue by dragonwithafez** [musescore/MuseScore#13649]
**Describe the bug**
When trying to add a time signature change in a score where part scores exist, the software crashes. Occurs whether trying to add the time signature to a part score or the main score.

**To Reproduce**
1. Create a new score
2. Create a part score for one of the instruments
3. Try to add a time signature change anywhere in the score, i.e. from 4/4 to 2/4
4. Observe crash

**Expected behavior**
Software should not crash.

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-, revision: github-musescore-musescore-

**Additional context**
Application output from before crash:

> 15:20:53.470 | DEBUG | main_thread | UiActionsRegister | updateEnabledAll: currentCtx: UiCtxNotationOpened
> 15:20:53.736 | DEBUG | main_thread | UiActionsRegister | updateEnabledAll: currentCtx: UiCtxNotationFocused
> 15:20:53.803 | DEBUG | main_thread | Score      | tick2measure: tick2measure 57600 (max 54720) not found

**Comment by lyrra** [comment]
confirmed on linux.
<details><summary> stacktrace:</summary>

```
(gdb) ba
#0  0x0000555555dc0650 in std::vector<mu::engraving::MStaff*, std::allocator<mu::engraving::MStaff*> >::size (this=0x160)
    at /usr/include/c++/10/bits/stl_vector.h:919
#1  0x0000555555db82e1 in mu::engraving::Measure::setMeasureRepeatCount (this=0x0, n=0, staffIdx=0)
    at src/engraving/libmscore/measure.cpp:2986
#2  0x0000555555ce43b4 in mu::engraving::Excerpt::cloneStaff2 (srcStaff=0x55555aee4d90, dstStaff=0x55555c0740e0, startTick=..., endTick=...)
    at src/engraving/libmscore/excerpt.cpp:1395
#3  0x0000555555e1c749 in mu::engraving::ScoreRange::write (this=0x7fffffff8180, score=0x55555c1914a0, tick=...)
    at src/engraving/libmscore/range.cpp:727
#4  0x0000555555c94a25 in mu::engraving::Score::rewriteMeasures (this=0x55555c1914a0, fm=0x55555b1eb470, lm=0x55555adfe660, ns=..., 
    staffIdx=18446744073709551615) at src/engraving/libmscore/edit.cpp:1011
#5  0x0000555555c9512c in mu::engraving::Score::rewriteMeasures (this=0x55555c1914a0, fm=0x55555b1eb470, ns=..., staffIdx=18446744073709551615)
    at src/engraving/libmscore/edit.cpp:1088
#6  0x0000555555c968c5 in mu::engraving::Score::cmdAddTimeSig (this=0x55555c1914a0, fm=0x55555b1eb470, staffIdx=0, ts=0x55555f61b2e0,
    local=false) at src/engraving/libmscore/edit.cpp:1334
#7  0x0000555555db1838 in mu::engraving::Measure::drop (this=0x55555b1eb470, data=...)
    at src/engraving/libmscore/measure.cpp:1648
#8  0x00005555564c99ae in mu::notation::NotationInteraction::drop (this=0x55555c6565d0, pos=..., modifiers=...)
    at src/notation/internal/notationinteraction.cpp:1380
#9  0x0000555556470eaa in mu::notation::NotationViewInputController::dropEvent (this=0x55555de34fc0, event=0x7fffffffa850)
    at src/notation/view/notationviewinputcontroller.cpp:1014
#10 0x0000555556465ab4 in mu::notation::AbstractNotationPaintView::dropEvent (this=0x55555de34b10, event=0x7fffffffa850)
    at src/notation/view/abstractnotationpaintview.cpp:1108

```
</details>

**Comment by dragonwithafez** [comment]
Here's some additional info. I found that I can reproduce it every time by creating a new score but clicking "Finish" immediately after choosing instruments, bypassing the time signature selection and defaulting to 4/4. If I do continue through to the screen that allows selection of a time signature, I do not crash every time, but new issues occur (see video). I'll also attach some sample scores.

Here is an example where the score did not crash, but encountered obvious problems:
https://user-images.githubusercontent.com/57819859/196744024-2d03524f-26db-41df-8b13-e7070f533b36.mp4
Here is the score before it is corrupted: 
[time_sig_test2.zip](https://github.com/musescore/MuseScore/files/9822222/time_sig_test2.zip)
And after:
[time_sig_test2-2.zip](https://github.com/musescore/MuseScore/files/9822223/time_sig_test2-2.zip)

Here is an example where it does crash:
https://user-images.githubusercontent.com/57819859/196744822-193a2c69-1994-4d12-b6f3-350ebde49a65.mp4
And here is the score that crashes upon adding a time signature (specifically, any time after the first measure):
[time_sig_test1.zip](https://github.com/musescore/MuseScore/files/9822241/time_sig_test1.zip)

I can provide any more info needed. These tests were done on the latest nightly as of 12 PM EST, Oct. 19, but also reproduce in my self-builds.

**Comment by Tantacrul** [comment]
I experienced this yesterday (MacOS) although I hadn't time to confirm what the circumstances were. Didn't realise it was so widespread.

**Comment by Tantacrul** [comment]
I can sometimes add a time signature without the app crashing but can also very easily reproduce it [on this score](https://www.dropbox.com/s/z42xtk8gux7aq4h/String_Quartet_No._8_in_C_Minor_Op._110__Dmitri_Shostakovich.mscz?dl=0).

https://user-images.githubusercontent.com/21022311/196752346-a255b1ca-d8f0-4fc3-b85f-ceaeb780dba9.mov

**Comment by Tantacrul** [comment]
@mike-spa - all yours!
