### ISSUE TITLE
[MU4 Issue] Regression: missing ability to set custom hooks on line

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13653]
**Describe the bug**
MuseScore 4 is missing the ability to set a start hook on lines (other than volta or pedal), and the ability to set end hooks to point upward

**To Reproduce**
Steps to reproduce the issue with respect to start hook:
1. Add a plain line to a score (the one with no text and no hooks - called simply "Line")
2. Go to Properties
3. Attempt to add a start hook
4. See error: control is missing

So you're stuck with what you see on left when you want what's on right (this is done in MU3):

![image](https://user-images.githubusercontent.com/1799936/195631336-ac3b1f3e-dd07-4e62-a694-63141b238e0d.png)

Steps to reproduce the issue with respect to upward hooks:
1. In the above example, press "X" to flip the line below the staff
2. Go to Properties
3. Set the line type to show the end hook
4. Attempt to set the height negative so that it points upward
5. See error: spin box only accepts positive values

So you're stuck with what's on the left when you want what's on the right:

![image](https://user-images.githubusercontent.com/1799936/195631720-ef5109a7-3600-441e-bb07-663d9da96524.png)

Both of these controls worked in MU3.

**Platform information**
 - OS: Linux

**Additional context**
These types of markings are common in educational usage as well as any number of other contexts.

A control for start hooks was added recently for pedal lines.  As far as I can see, there is no reason it couldn't be used as is for other line types, or a new palette element could be added that has this pre-enabled.

The hook height issue would be fixed by simply removing the minimum value on the spin box.

One thing that would still be impossible is lines with start and end hooks pointing in opposite directions.  This is a less common case of course, but it's actually used quite a bit in educational contexts as well, to show modulations in Roman numeral analysis:

![image](https://user-images.githubusercontent.com/1799936/194444736-c4014554-06e0-476a-86cb-46b482628733.png)

So ideally there would actually be separate controls for start and end hook height, as there was in MU3.

**Comment by MarcSabatella** [comment]
In order for this to work for RNA, we also need independent start & end hook height fields.  Or some sort of system involving checkboxes for direction, I guess.

**Comment by MarcSabatella** [comment]
@Tantacrul - this could be one of those cases where you really want to go back to the drawing board a bit, but anyhow - right now it's a regression from MU3 that will adversely affect educators especially.  Simply adding the exsting "start hook" control to other line types and allowing negative hook heights would go a long way toward addressing it.

**Comment by Tantacrul** [comment]
@bkunda - can you also take a look at this. It's another case of a simple tweak or two. Agree it isn't crucial for the release.

**Comment by oktophonie** [comment]
Closing as incorporated into https://github.com/musescore/MuseScore/issues/14209
