### ISSUE TITLE
[MU4 Issue] Fretboard diagrams: "Orientation" property missing

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13655]
**Describe the bug**

For __fretboard diagrams__ MS3 had a "Orientation" property in the Inspector, which allowed you to set them horizontally.  See https://musescore.org/en/node/299644.

![fretboard_orientation](https://user-images.githubusercontent.com/87246583/194514327-4ce95d93-23bc-4b03-9937-a96507d19338.png)

However this is missing in MS4, and needs to be restored.

**Comment by rgreen5** [comment]
Bump. See https://musescore.org/en/node/338158.

**Comment by rgreen5** [comment]
Bump. Surely a missing property should receive some priority?

**Comment by cbjeukendrup** [comment]
@rgreen5 Please check https://github.com/musescore/MuseScore/pull/16331 :)
