### ISSUE TITLE
[MU4 Issue] Autosave saves score whether modified or not

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13661]
**Describe the bug**
Autosave kicks in every three minutes even if no changes have been made

**To Reproduce**
1. Open a score
2. Make a change (one change only; then stop)
3. Watch the modified date of the autosave file for several minutes
4. See error: every three minutes, it gets resaved, even if you aren't doing anything at all

**Expected behavior**
Autosave only kicks in if a change has happened since the last autosave

**Platform information**
 - OS: Linux

**Additional context**
I noticed this because I keep getting notifications from my OS about files being synced to backup.  In MU3, autosave files were in a system folder that is not typically synced.  But also, it seems in MU3 the autosave files are not continually updated if there have been no further changes since the last autosave.

**Comment by DmitryArefiev** [comment]
Fixed in #18922
