### ISSUE TITLE
Crash on export as .ogg

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#13666]
**Describe the bug**
Tested in the latest nightly on MacOS. Choosing to export as a .ogg file (4100 Hz or 48000 Hz) causes an immediate crash.

**To Reproduce**
1. Choose any file
2. Export as ogg
3. Crash occurs after you select your location

Happens regardless of whether Muse Sounds or Muse Basic is chosen. Tested on Beta candidate and Nightly.

**Comment by Tantacrul** [comment]
Note. VST does not seem relevant because if I change everything to MS Basic, the crash still occurs.

**Comment by HemantAntony** [comment]
@Tantacrul I can't reproduce this on Linux when you build it. Same with the Nightly. Can't reproduce

**Comment by cbjeukendrup** [comment]
@krtschil I think indeed that that is a different crash than what we experience on macOS. The macOS crash is specifically related to OGG and happens immediately when trying to export to OGG.

**Comment by AntonioBL** [comment]
Ciao.
I could reproduce the crash in a 64bit Linux Mint 20.3 virtual machine (VirtualBox running inside a Windows 7 pc), with both a nightly build and a local (debug) build.
In my machine, the crash occurs with an **Illegal Instruction** (SIGILL) [here](https://github.com/musescore/MuseScore/blob/6303c4042a1d7ff011a77fbb10d406b90bcb28c8/thirdparty/opus/celt/celt_encoder.c#L2531).
I tried to make small changes around that point in the code, but whenever the program was creating or casting a float or a double, it emitted the Illegal Instruction error. I also tried to play with opus options, but I got no positive results.
Then I saw this issue report: https://github.com/xiph/opus/issues/154 and I thought that maybe that could be the culprit; I applied the related patch ( https://github.com/mumble-voip/opus/commit/b7dc80cb4207595 ) and the resulting binaries do not crash anymore for me.
Could it be the same problem also for MacOS? If so, I would expect it to appear only for "old" hardware.

( By the way, among the opus options there is one labelled `OPUS_CUSTOM_MODES "Enable non-Opus modes, e.g. 44.1 kHz & 2^n frames"`; at the moment it is OFF, but shouldn't we enable it, if we want to export _44.1 kHz_ output? Or maybe this is not related to output sampling rate...)

**Comment by AntonioBL** [comment]
@Tantacrul : you can try this build, to check if also under Mac it is the same problem of SSE-optimized instructions:
https://github.com/AntonioBL/MuseScore/suites/8809133343/artifacts/400823174
It is the artifact of this test branch: https://github.com/AntonioBL/MuseScore/tree/oggcrash where I simply introduced the patch already present in upstream opus.
Ciao,
ABL

**Comment by cbjeukendrup** [comment]
@AntonioBL This seems to work perfectly for me on macOS, huge thanks!

@Tantacrul @vpereverzev check this out :)

**Comment by Tantacrul** [comment]
Just tested with MS Basic (Reunions) and a String Quartet using VSTi. In both cases, no problems with export. Great stuff!

@vpereverzev - if you are happy with this, can it be merged?

**Comment by vpereverzev** [comment]
> SSE

@AntonioBL great stuff! Open a PR and I'll push dat "merge" button so hard!

**Comment by AntonioBL** [comment]
Ok, I will do.
Thank you.
