### ISSUE TITLE
[MU4 Issue] Playback does not honor newly added tempo (by shortcut Alt+Shift+T)

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13662]
**Describe the bug**
If you add a tempo marking to a score via keyboard shortcut (Alt+Shift+T) and then play, the new tempo is ignored

**To Reproduce**
1. new 4/4 score, default (120) tempo
2. enter a C major scale in quarter notes: C D E F | G A B C
3. select first note
4. play
5. press Alt+Shift+T to add a tempo marking 80 to the first measure (do not edit!)
6. select first note again
7. play
8. hear error: playback is still 120 BPM (although the playback bar is moving at 80 BPM)

**Expected behavior**
Playback should be 80 BPM

**Platform information**
 - OS: Linux

**Additional context**
You can hear other "fun" effects of this, like try starting playback at the G.  It will actually start with the B.  Everything fixes itself if you actually edit the tempo - i.e, if you don't just keep the "quarter note = 80" that gets added by default.  And it works fine from the palette.

**Comment by DmitryArefiev** [comment]
See #19075 for video demos
