### ISSUE TITLE
Crash when moving a .rit mark in a part score

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#13674]
**Describe the bug**
This crash occurs [on this orchestral score](https://www.dropbox.com/s/cgfqjhvog5pijso/New_All_Forever_02_%28Alpha2%29.mscz?dl=0) consistently. I worry it is the kind of bug that only appears once there are a lot of parts and a few pages of music written.

**Video**

https://user-images.githubusercontent.com/21022311/194767970-dafad7bd-fefb-4fe5-bd46-5b7fbcb0fadb.mov

**To Reproduce**
1. Open the file
2. Choose a part score (I've chosen the horn in this video)
3. Try to move the **.rit** line
4. Observe an immediate crash

**Platform information**
 - OS: [tested on macOS]

**Comment by cbjeukendrup** [comment]
@Tantacrul please check #13676 :)
