### ISSUE TITLE
[MU4 Issue] [Accessibility] Layout break colour can not be customised

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#13678]
**Describe the bug**

MS3 includes various options in the Preferences->Advanced menu to customise the colour of score breaks.  This facility is not present in MS4.  
  
**To Reproduce**
1.  in MS4 open Edit->Preferences->Advanced
2. Compare with the range of options available in MS3 Edit->Preferences->Advanced

**Expected behavior**
MS4 Edit->Preferences-Advanced (or a different submenu) should include options to change the colour of non-printable score elements, and in particular score breaks.

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

I have no visual impairment but I find it useful to have score breaks (MS3 default light grey and not customisable in MS4) given more prominence.  I guess that some visually impaired users would also find this useful. My current preference is bright pink.  

I can understand the need to reduce the number of options for customisation of the user interface that currently exist in the MS3 advanced preferences and instead to offer options more suited to enhancing accessibility for users with particular visual needs.  However, it would seem useful to provide similar options for each category under the View->Show menu - i.e. Invisible, Formatting, Frames, Page margins, Irregular bars.

**Comment by SteveBlower** [comment]
Still the case with Beta therefore adding @Tantacrul for triage

**Comment by Tantacrul** [comment]
Going to pop this one in 4.x because we won't have time to tackle it for 4.0. Will reopen once 4.0 is out. Thanks!

**Comment by iwoithe** [comment]
Implemented in https://github.com/musescore/MuseScore/pull/22361
