### ISSUE TITLE
[MU4 Issue] Tempo text placement too high on first (pickup) measure

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13694]
**Describe the bug**

In the attached score tempo text appears far higher than it would on subsequent measures.

![tempo_text_placement](https://user-images.githubusercontent.com/87246583/195075640-861192de-dd5e-4809-8a83-a3d43426f72f.png)

**To Reproduce**

1. Open the attached score. 
[tempo_text_placement.zip](https://github.com/musescore/MuseScore/files/9754538/tempo_text_placement.zip)
2. Apply tempo text to the first (pickup) measure, then to a subsequent measure

RESULT: Tempo text is placed too high on the opening pickup measure.

**Expected behavior**

Tempo text placement should appear at the same height.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3224155784, revision: github-musescore-musescore-c6f3e75

**Comment by MarcSabatella** [comment]
That seems to be because there are already tempo markings there.  Not invisible - otherwise they'd be ignored in autoplace.  They are visible, but empty.  To find them, click the eighth rest and hit Alt+Right to navigate element by element.

**Comment by Tantacrul** [comment]
I think this means we should close this issue. Unless @MarcSabatella / @rgreen5 I'm missing something?

**Comment by MarcSabatella** [comment]
I'm guessing the score was imported from something (the missing instrument names are a clue).  Would be interesting to see the original to understand if there was a bug in the import.

**Comment by rgreen5** [comment]
BTW, the cause of the empty tempo markings was #12978.
