### ISSUE TITLE
'R' shortcut is no longer repeating selected notes (regression over the last 1-2 days)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#13702]
**Describe the bug**
Just in this most recent nightly, we have noticed that you can no longer select a note and press 'R' to repeat it.

**To Reproduce**
1. Make sure you are **not** in note input mode
2. Select any note
3. Press 'R' and notice that you now get this incorrect error:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/21022311/195159647-9a4bb5e9-ffa9-4827-95e8-a88c5ff5637a.png">

**Comment by DmitryArefiev** [comment]
Fixed in #13704
