### ISSUE TITLE
[MU4 Issue] Text cannot be copied / cut to the clipboard

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13712]
**Describe the bug**

It appears that any text you select, then copy or cut, is not being transferred to the clipboard. This was OK in MS 3.6.2.

**To Reproduce**

1. Open the attached score. 
[copy_cut_issue.zip](https://github.com/musescore/MuseScore/files/9763605/copy_cut_issue.zip)

2. Go to the end vertical frame, enter text edit mode, make a selection and copy it (use a shortcut)
3. Try to paste the result into another app.

RESULT: Nothing happens.

**Expected behavior**

Copied / cut text should be transferred to the clipboard and accessible to other apps.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3232046794, revision: github-musescore-musescore-58a64c7

**Comment by zacjansheski** [comment]
I am able to copy paste the lyrics at the end, although they include the font info (Ubuntu 20.04.6)

<font size="10"/><font face="Edwin"/>Now when she came to the first mile post,
<font face="Edwin"/>   Little Jane she was behind,
<font size="10"/><font face="Edwin"/>   All they could say of my little Creeping Jane:
<font size="10"/><font face="Edwin"/>   My fair little lady, you’re behind the lalli day!
<font size="10"/><font face="Edwin"/>   Sing pea-ne-lal-li-lie-day.
<font size="10"/><font face="Edwin"/>   My fair little lady, you’re behind the lalli day!

<font size="10"/><font face="Edwin"/>3. And when she came to the second mile po

**Comment by cbjeukendrup** [comment]
FWIW, that should be fixed by https://github.com/musescore/MuseScore/pull/16242 (not merged yet)

**Comment by Jojo-Schmitz** [comment]
I believe this issue should ret reopened

**Comment by cbjeukendrup** [comment]
Wasn't this fixed by https://github.com/musescore/MuseScore/pull/17527? And the issue about text formatting being included is logged separately in #16146.

**Comment by Jojo-Schmitz** [comment]
Yup, seems so
