### ISSUE TITLE
[MU4 Issue] Copy, Cut commands don't work from context menu

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13711]
**Describe the bug**

This appears to be an issue carried over from MS3 (unreported?). For text objects within frames, at least, the copy / cut commands don't work from the context menu.

**To Reproduce**

1. Open the attached score. 
[copy_cut_issue.zip](https://github.com/musescore/MuseScore/files/9763537/copy_cut_issue.zip)
2. Go to the final frame, and select a section of the lyrics in the end vertical frame (in text edit mode).
3. Right-click to bring up the context menu.
RESULT: The highlighting is lost.
4. Choose "Cut".
RESULT: Only one letter is cut from the selection!

**Expected behavior**

The highlighting should remain throughout? Copy and cut should work as they do using shortcuts

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3232046794, revision: github-musescore-musescore-58a64c7

**Comment by Tantacrul** [comment]
This has just been address here: https://github.com/musescore/MuseScore/pull/15427

Also there is an attached issue which duplicates this one.
