### ISSUE TITLE
[MU4 Issue] Cross (ghost) noteheads are too small in tablature staves

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13735]
**Describe the bug**
This is an issue inherited from previous versions. Crosshead notes are correctly-sized in the standard staff but in tablature are too small. See also https://musescore.org/en/node/94211.

![crosshead_notes](https://user-images.githubusercontent.com/87246583/195592484-eb9da54b-9cfa-4170-b821-0205ce17c464.png)

**Comment by mxmou** [comment]
This is probably the same issue as #11602.

**Comment by rgreen5** [comment]
> This is probably the same issue as #11602.

Yes. Identical.
