### ISSUE TITLE
[MU4 Issue] Deleted measure still plays back

### ISSUE THREAD

**Issue by KatrinaHahn1** [musescore/MuseScore#13738]
Describe the bug
Deleted measure still plays back **after** Coda

To Reproduce
1. Go to any measure after coda 
2. Delete a measure
3. Hit playback

Actual behavior
Notes still play after being deleted

Expected behavior
The notes should not be heard after being deleted

Screenshots
![image](https://user-images.githubusercontent.com/115717860/195632255-54290bd7-130b-4ec3-aa90-8289bd4a8553.png)

Platform information
 - OS: Windows

**Additional context**
Nightly build

**Comment by zacjansheski** [comment]
Closing as fixed.
