### ISSUE TITLE
[MU4 Issue] Playback not working

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#13734]
**Describe the bug**
When I click play (or use the shortcut, space), MU4 does not playback. The cursor just stays in place

**To Reproduce**
1. Open any score
2. Press Play
3. No playback

**Expected behavior**
MU4 should playback

**Screenshots**

https://user-images.githubusercontent.com/88136054/195581915-953ef591-3eb9-42f5-add1-8d5f93f61491.mp4

**Platform information**
 - OS: Ubuntu 22.04 LTS

**Additional context**

**No sounds is hear at all, even when putting in notes. The note doesn't play too**

I'm using a dev build, but I've heard of other people having this issue too

**Comment by HemantAntony** [comment]
If none of the devs can reproduce this, I can try to find out the source of this

**Comment by Tantacrul** [comment]
Are you building it directly? If so, what happens if you install a build on your machine instead? We're getting quite a few instances of bugs / problems manifesting for developers when building themselves VS installed versions of MuseScore.

**Comment by HemantAntony** [comment]
Yes I am building it myself. I just tried a nightly from two days ago. It isn't working in that case as well

**Comment by HemantAntony** [comment]
I know two other people that have this issue as well

**Comment by Tantacrul** [comment]
I guess you should add any other details you think pertinent. What is the playback profile set to? What version of Windows. Are you using MS Basic? VST? etc.

**Comment by Tantacrul** [comment]
> I know two other people that have this issue as well

Can you ask them to chime in? They all Windows too?

**Comment by HemantAntony** [comment]
> I guess you should add any other details you think pertinent. What is the playback profile set to? What version of Windows. Are you using MS Basic? VST? etc.

I actually don't know how to check the playback profile. I usually reset to preferences every once in a while (part of fixing some issues). I use MS Basic. I don't use VSTs

I actually don't use Windows anymore. I'm currently using Ubuntu 22.04 LTS (Linux). But I'll check in Windows too to see if its got something to do with my system or OS

**Comment by HemantAntony** [comment]
> Can you ask them to chime in? They all Windows too?

I have asked them and they haven't said anything yet. But this was their initial message on Discord:
 https://discordapp.com/channels/818804595450445834/939880479887327302/1029034815242121256
and https://discordapp.com/channels/818804595450445834/939880479887327302/1029035465048858716

**Comment by HemantAntony** [comment]
Playback works correctly on Windows 11. I used the latest nightly

**Comment by DmitryArefiev** [comment]
Playback works for me on my **Ubuntu 22.04.1 LTS** (latest master)

@HemantAntony Maybe check your I/O settings?

![Screenshot from 2022-10-13 18-06-34](https://user-images.githubusercontent.com/90187801/195636037-b0045ed0-6b86-468e-a5fe-06dbbab2a085.png)

And also, do you have a sound when just playing youtube in browser?

**Comment by HemantAntony** [comment]
Its just like yours
![image](https://user-images.githubusercontent.com/88136054/195643679-03fb4f30-31f8-4ce8-847f-8b1a0b3a16ae.png)

I do have sound when playing youtube in a browser

**Comment by Der-Leiermann** [comment]
Hi, I'm one of the two people @HemantAntony mentioned. However, I believe there may have been a miscommunication. Before my original message, I had been testing the .ogg export on my Mac; only after said export did the problem occur—see #12900. After closing and reopening the program, the playback worked as expected, and I have not had any such issues since. I apologize for the confusion—I should have been less vague.

**Comment by HemantAntony** [comment]
Ah, no problem. Sorry for bothering you too :)

**Comment by lyrra** [comment]
At startup check your terminal, if musescore has successfully connected to alsa it will display:
```
21:27:25.756 | DEBUG | main_thread | LinuxAudioDriver | open: Connected to default
```
If it fails, it should display:
```
21:21:37.664 | ERROR | main_thread | AudioModule | onInit: audio output open failed
```
And if it fails, it will show the symptoms of an hung playback cursor as you mention.

**Comment by HemantAntony** [comment]
@lyrra, I think it is successfully connected to alsa. But there is the message 'Connected to -1'
![image](https://user-images.githubusercontent.com/88136054/195787865-89143550-6504-4c43-8c44-f839b315fe1c.png)

**Comment by Eism** [comment]
'Connected to -1'
This means that you have not selected a midi device

**Comment by lyrra** [comment]
Can´t reproduce the condition of both having alsa connected (ie, logs says "LinuxAudioDriver | open: Connected to default"), and cursor not moving. If alsa is connected I see the mixer-volume-levels move during play and cursor moves.

On a side note, I tried uping the buffer-size to 4096, but my alsa didn't like that.
Not sure that was intended with the buffer setting to avoid stuttering:  internal buffer-io size is causing stuttering, not the hardware-buffer size.

I've added some error-checking and debug-output if alsa fails: https://github.com/musescore/MuseScore/pull/13744

**Comment by HemantAntony** [comment]
Ah cool! I'll use that branch to see if it fixes anything

**Comment by HemantAntony** [comment]
@lyrra I tried your commit, but it didn't work. Also this is the output. Anything of interest?
![image](https://user-images.githubusercontent.com/88136054/195978958-8ee59870-77eb-495d-a125-e57a47b65fbd.png)

**Comment by lyrra** [comment]
Strange, I get the same console output, but it works (cursor moves). 
```
11:25:46.769 | DEBUG | main_thread | LinuxAudioDriver | open: Connected to default
11:25:46.955 | DEBUG | main_thread | InstrumentTemplate | read: InstrumentTemplate:: init instrument <contrabass> not found
11:25:46.960 | DEBUG | main_thread | AlsaMidiInPort | connect: Connected to -1
11:25:46.960 | DEBUG | main_thread | AlsaMidiOutPort | connect: Connected to -1
```

**Comment by sammik** [comment]
@HemantAntony did you try Factory reset? It used to help in MU3 
https://musescore.org/en/handbook/3/revert-factory-settings#instructions-for-linux

**Comment by HemantAntony** [comment]
> Strange, I get the same console output, but it works (cursor moves).
> 
> ```
> 11:25:46.769 | DEBUG | main_thread | LinuxAudioDriver | open: Connected to default
> 11:25:46.955 | DEBUG | main_thread | InstrumentTemplate | read: InstrumentTemplate:: init instrument <contrabass> not found
> 11:25:46.960 | DEBUG | main_thread | AlsaMidiInPort | connect: Connected to -1
> 11:25:46.960 | DEBUG | main_thread | AlsaMidiOutPort | connect: Connected to -1
> ```

The connected to -1 just implies that there no MIDI input or output

**Comment by lyrra** [comment]
Yes, but "open: Connected to default" would suggest audio atleast works. Perhaps try all combinations of buffer-size and sample-rate. I got connect-error if buffer-size was 4096.

**Comment by HemantAntony** [comment]
I can't change the buffer-size, I would get a crash. Although I can try to change it in code. I'll try similarly with sample rate


@sammik I just tried it, but it did not work. I did the MuseScore4 equivalent

Also, I forgot to mention a crucial thing, but no sound is hear at all even when you are putting in notes. Its just the visual. The note isn't played back

**Comment by HemantAntony** [comment]
Also, just to say, I wonder if this would piss people off who are waiting for MuseSounds

**Comment by sammik** [comment]
> I can't change the buffer-size, I would get a crash. Although I can try to change it in code. I'll try similarly with sample rate
> 
> @sammik I just tried it, but it did not work. I did the MuseScore4 equivalent
> 
> Also, I forgot to mention a crucial thing, but no sound is hear at all even when you are putting in notes. Its just the visual. The note isn't played back

And this happens to downloaded nightly appimages too, right?

MU3 works?

**Comment by lyrra** [comment]
> I can't change the buffer-size, I would get a crash.
If you're using my PR and still get a crash when changing buffer-size, I could reproduce it. In the stacktrace it looks as if it is coming from alsa, ie, maybe the callback-process isn't unregistered when reloading audio.

To work around this I had to disable alsa  (Mu starts with audio disabled), and then change the buffer-size.

**Comment by HemantAntony** [comment]
@sammik Yes, in nightlies too. MU3 works properly

**Comment by shoogle** [comment]
@HemantAntony, could you run this command on a recent nightly build and attach the resulting `dependencies.txt` to a comment here?
```Bash
./MuseScore*.AppImage check-dependencies | tee dependencies.txt
```
This will tell us if you are missing any library dependencies on your machine.

**Comment by HemantAntony** [comment]
@shoogle I have linked the dependencies file. Also this was working till a couple weeks ago
[dependencies.txt](https://github.com/musescore/MuseScore/files/9792647/dependencies.txt)

**Comment by sammik** [comment]
Couldnt be #13415 a case?
You can try nigthly from 19.9. and from 20.9. or later

**Comment by HemantAntony** [comment]
I don't think so, because that's for the GitHub workflows when you create a PR (the tests). It doesn't affect the software

**Comment by shoogle** [comment]
> [I have linked the dependencies file.](https://github.com/musescore/MuseScore/issues/13734#issuecomment-1279781906)

Your dependencies.txt shows no missing libraries (see line `# Provided by neither: 0`) so the playback issue is more likely to be caused by our code than by a missing library, although we can't rule out libraries altogether.

**Comment by Tantacrul** [comment]
@HemantAntony - it seems that you're the only person experiencing this, so I'm tempted to chalk it down to your machine getting messed up from building MS4 a lot. Of course, I can't be sure of that, but this issue doesn't seem actionable because none of us can reproduce it.

**Comment by shoogle** [comment]
@HemantAntony, you could try booting Ubuntu 22.04 from a LiveUSB (no need to install the OS) and then download the nightly AppImage and run it inside the live environment to see if it works there. If so then it's probably a configuration problem or a dodgy audio driver update that you install sometime after installing 22.04.

**Comment by HemantAntony** [comment]
@shoogle I tried your way and the audio worked then. It likely is something to do with my machine
