### ISSUE TITLE
[MU4 Issue] Crash on changing buffer size in I/O Preferences

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#13739]
**Describe the bug**
MU4 crashes when you change buffer size in I/O Preferences

**To Reproduce**
1. Go to Preferences
2. Click on I/O
3. Change Buffer size
4. MU4 crashes

**Expected behavior**
MU4 should not crash

**Screenshots**

https://user-images.githubusercontent.com/88136054/195647134-a70f7659-ee8e-4f6e-b29c-77cff5f91eab.mp4

**Platform information**
 - OS: Ubuntu 22.04 LTS

**Comment by HemantAntony** [comment]
@Tantacrul FYI

**Comment by Tantacrul** [comment]
@DmitryArefiev - another Linux beauty. Can you take a look?

**Comment by lyrra** [comment]
Crashes on linux.
<details><summary>backtrace</summary>

```
#2  0x00007ffff567540f in __assert_fail_base (fmt=0x7ffff57de128 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff7ee0d3e "pcm", file=0x7ffff7ee62c5 "pcm.c",
    line=1343, function=<optimized out>) at assert.c:92
#3  0x00007ffff5684662 in __GI___assert_fail (assertion=0x7ffff7ee0d3e "pcm", file=0x7ffff7ee62c5 "pcm.c", line=1343, function=0x7ffff7ee3d18 "snd_pcm_drain")
    at assert.c:101
#4  0x00007ffff7e738c7 in snd_pcm_drain () from /usr/lib/x86_64-linux-gnu/libasound.so.2
#5  0x00005555560cd86c in (anonymous namespace)::alsaCleanup () at src/framework/audio/internal/platform/lin/linuxaudiodriver.cpp:95
#6  0x00005555560ce3f1 in mu::audio::LinuxAudioDriver::close (this=0x555559041410) at src/framework/audio/internal/platform/lin/linuxaudiodriver.cpp:199
#7  0x00005555560ce74b in mu::audio::LinuxAudioDriver::setOutputDeviceBufferSize (this=0x555559041410, bufferSize=4096)
    at src/framework/audio/internal/platform/lin/linuxaudiodriver.cpp:269
#8  0x00005555560cc457 in operator() (__closure=0x5555594ef338) at src/framework/audio/internal/audiooutputdevicecontroller.cpp:48

```
</details>

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev - another Linux beauty. Can you take a look?

@Tantacrul It looks fine again on my side :) (Ubuntu, Linux Mint)

**Comment by HemantAntony** [comment]
@DmitryArefiev It definitely crashes. @lyrra provided a stack trace. He also has a PR ready. If you want, I can test the PR

**Comment by HemantAntony** [comment]
This crash does not occur when you test in a system from when you boot from a LiveUSB. See [this comment](https://github.com/musescore/MuseScore/issues/13734#issuecomment-1283038504)
