### ISSUE TITLE
Note parenthesis duplicated in imported MS3 scores; can't be easily deleted

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13736]
**Describe the bug**

if you import an MS3 score in MS4, note parentheses are duplicated. In addition you cannot delete one of the parenthesis pairs independently because it has become "hard baked" to the note.

**To Reproduce**

1. Open the attached file in both MS3 and MS4. 
[parenthesis_issue.zip](https://github.com/musescore/MuseScore/files/9776579/parenthesis_issue.zip)
2. Observe the change in MS4.

RESULT: The paratheses have been duplicated and one pair cannot be deleted without taking the note with it.3

3.6:
![image](https://user-images.githubusercontent.com/20604032/195615914-411ccc9f-133b-444f-be3c-ed162f4a781b.png)

4.0:
![image](https://user-images.githubusercontent.com/20604032/195616160-2d004e5a-6df9-493c-b8e2-4e1b73fd6eca.png)

**Expected behavior**

Parentheses should be as they were in MS3.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3239707478, revision: github-musescore-musescore-2d8a581

**Comment by HemantAntony** [comment]
I'm not really familiar with guitar notation. But in the 3.6 version, is the 'x' thing same as 4.0 version '5'? I know the 'x' stands for a ghost note
