### ISSUE TITLE
[MU4 Issue] No sound output in last build 10/13/22

### ISSUE THREAD

**Issue by Grillzombie** [musescore/MuseScore#13747]
**Describe the bug**
No sound output in last build 10/13/22
OS: Linux Mint 21, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3239707478, revision: github-musescore-musescore-2d8a581

**To Reproduce**
No sound output, whether loading an existing score or create a new one. Mixer MS Basis. Play cursor moves.
Was ok in:
OS: Linux Mint 21, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3202248332, revision: github-musescore-musescore-56e2ae7

**Platform information**
OS: Linux Mint 21, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3239707478, revision: github-musescore-musescore-2d8a581

**Comment by lyrra** [comment]
I'm on linux/debian commit 5050c56 (2022-10-13) and can produce sound.
Ensure you dont see this error at startup:
```
21:21:37.664 | ERROR | main_thread | AudioModule | onInit: audio output open failed
```
Also, does the mixer volume levels move when you play?

**Comment by Grillzombie** [comment]
Where do i see this error message?

Yes, the mixer volume levels move.

**Comment by lyrra** [comment]
If you start musescore from the terminal, it should spit out logs.

**Comment by Grillzombie** [comment]
Sorry, i normally don't use the terminal, what exactly do i have to type in to start ms?

**Comment by lyrra** [comment]
Not sure how the nightly builds are installed. Perhaps it is possible to locate where MuseScore4 binary is installed, and start a terminal at that directory point (or use cd), then launch it by "./MuseScore4", but I'm guessing now.

**Comment by Grillzombie** [comment]
These nightlys are AppImages, they aren't installed!?

**Comment by MarcSabatella** [comment]
So how are you starting them?  Normally you'd just type the name of the file into a terminal window.  Note you *can* install AppImagines, just run from terminal with "install" command line option

**Comment by Grillzombie** [comment]
I click on the icon of the AppImage, which i downloaded (execution permission is set)

**Comment by HemantAntony** [comment]
@Grillzombie I wonder if this can be related to #13734. Please check that issue as well to see if you see identical symptoms

**Comment by Grillzombie** [comment]
Today, all is ok, should be an issue with my computer, sorry.
