### ISSUE TITLE
[MU4 Issue] Dark, Light, White and Black from View > Preferences > Appearance don't show translated

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#13742]
**Describe the bug**
Dark, Light, White and Black from View > Preferences > Appearance don't show translated

**To Reproduce**
1. Change language to some non-english but reasonably complte translation, Turkish, or German for example.
2. Update translations
3. Restart
4. Go tp View > Preferences > Appearance
5. See error

**Expected behavior**
Stringhs shopuld show translated

**Screenshots**
![image](https://user-images.githubusercontent.com/1786669/195660786-551baa63-7ee8-4be6-b99c-f583a3d44802.png)
![image](https://user-images.githubusercontent.com/1786669/195660908-52d70d35-ec0d-4ca2-aacf-866a201db62c.png)

**Platform information**
 - OS: Windows. but unlikerly restrocted to just that
 - 
**Additional context**
These 4 strings are the only translatable strings in src/framework/ui/internal/uiconfiguration.cpp

**Comment by orkuun** [comment]
and
- TAB and Drumset templates (like tab 6-str.simple or Perc 1 line) in Staff/Part properties section.
- all instrument names and descriptions.

**Comment by cbjeukendrup** [comment]
> * TAB and Drumset templates (like tab 6-str.simple or Perc 1 line) in Staff/Part properties section.
> * all instrument names and descriptions.

These are already fixed by PR #12712, but that has not been merged yet. 

I'll work on a fix for the names of the themes.

There's on more thing: the names of the templates. For those it's a bit less straight-forward _how_ to make them properly translatable. I'll discuss this with others. 

And actually, there's yet another more thing: the name of the default workspace is not translatable. This problem is known as #12658 and is not completely trivial to solve either, unfortunately.

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz Could you please verify if https://github.com/musescore/MuseScore/pull/13743 fixes the problem with theme names?

**Comment by Jojo-Schmitz** [comment]
Looks good!

**Comment by orkuun** [comment]
hello again, these problems were solved in the nightly build(10.20.2022), but I found problems in other lines as well. I wanted to write them too.
1- Go to Edit > Preferences > Appearance > Enable High Contrast (check)
"Accent color", "Text and icons", "Disable text" and "Border color"( the last three have no record on transifex )
2- Click any Dynamics. Properties > Playback > Dynamics > Slow, Normal and Fast ( have no record on transifex )
3- Go to Format > Style... > System Text Line > Placment > Nothing is selected in the Combobox and the words "above" and "below" still appear in English( I think these words are not in transifex ).
4-  and finally, the alignment button of some elements (dynamics,tempo, text) works in reverse (right button aligns left, left button aligns right:) ).

**Comment by cbjeukendrup** [comment]
@orkuun I think that the alignment buttons are working as they are supposed to work. Although it may be a little bit confusing, it should work like this: "Align left" means that the left side of the text will be aligned with the anchor point (which is the left side of the note), and "Align right" means that the right side of the text will be aligned with the anchor point. 
<img width="570" alt="Scherm­afbeelding 2022-10-20 om 20 48 55" src="https://user-images.githubusercontent.com/48658420/197032937-e9cfd4f2-23e9-4fa1-997c-a78224fd857f.png">

But thanks for the other points! Fix coming very soon.

**Comment by orkuun** [comment]
Hello, it's me again :) I think I found another mistake somewhere. Go to New Score (wizard)- Create From Template. Although I translated the categories and templates in this section into Turkish, they still appear in English.

**Comment by orkuun** [comment]
![MuseScore4](https://user-images.githubusercontent.com/35005568/204106710-63320165-3197-4b3c-943e-8954d959718a.png)

**Comment by cbjeukendrup** [comment]
Ah, yeah, those templates... thanks for reminding me! 🙂
