### ISSUE TITLE
[MU4 Issue] tooltips are localized even if app language is set to US English

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13750]
**Describe the bug**
(Some) tooltips are localized even if app is set to US English in Preferences.
 
**To Reproduce**
1. Open Clefs Palette
2. Put mouse over Treble clef
3. Tooltip is localized

**Expected behavior**
Whole app should use one laguage. (And non translated strings in default language - US English)

**Screenshots**
![localized-tooltips](https://user-images.githubusercontent.com/1646034/195706778-9ca004a0-6845-4d6b-a6b6-2b6807cae04e.png)

**Platform information**
 - OS: [reported on Linux]

**Additional context**
My guess: Probably depends on how many strings are translated. My language is translated wery little, so only few tooltips shows this bug.

**Comment by cbjeukendrup** [comment]
It looks like this is about palette elements specifically. Does it help to reset the palette? And if you change the language again after resetting, does the problem come back, or does resetting fix it entirely?

(to reset a palette, use its '...' button to open a context menu where you will find the reset option)

**Comment by sammik** [comment]
Reset seemed to help.
But after reset in some palette - clefs, now tolltip is in english, even if language is set to localised.
Other - lines works as expected. Doesnt even need reset.

**Comment by krtschil** [comment]
I guess the localization / language settings are still under development as I see a mix of English and localized text all over the place:
OS: Linux
Language setting: System default

![grafik](https://user-images.githubusercontent.com/7796440/195982818-28f96721-f596-455c-8a5d-b2de9602aa26.png)
![grafik](https://user-images.githubusercontent.com/7796440/195982836-78fe01ef-9a66-4d2a-9c8a-c90331d9cfdb.png)

**Comment by HemantAntony** [comment]
Which language are you using?

**Comment by krtschil** [comment]
German

**Comment by cbjeukendrup** [comment]
Preferences > General > Check for language updates should fix this!

**Comment by cbjeukendrup** [comment]
@sammik Does this issue still occur?

**Comment by sammik** [comment]
@cbjeukendrup seems to be fixed now

thank you
