### ISSUE TITLE
[MU4 Issue] MDL staves from imported MS3 scores have no channel in the mixer

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#13751]
If you open a score in Musescore 4 that has a Musescore Drumline staff in it, that staff will no have a channel in the mixer, and will just be skipped.

**To Reproduce**
1. Open a score from Musescore 3 that has a MDL staff
2. Open the mixer
3. See that the staff has no channel in the mixer

**Expected behavior**
The staves should have staves in the mixer, even if playback doesn't work.

**Screenshots**
![Screenshot (212)](https://user-images.githubusercontent.com/21023353/195708579-63050941-2075-41fe-a408-c0db5890ab16.png)
![Screenshot (213)](https://user-images.githubusercontent.com/21023353/195708580-1bbf0a98-5921-4ae6-8e7c-84c879abd99a.png)
[test.zip](https://github.com/musescore/MuseScore/files/9780601/test.zip) (rename to test.mscz)

**Platform information**
 - OS: Windows

**Comment by zacjansheski** [comment]
Definitely reproducible.

I have many older files with MDL instruments that I can open and they do appear in the mixer.  Perhaps it has to do with what version of MuseSocre 3 they were made in.  Unfortunately going from 3.6.2 definitely will not appear in the mixer.

Here is a file that does appear in the mixer if it helps at all
[8-8-16 Variations.zip](https://github.com/musescore/MuseScore/files/11920010/8-8-16.Variations.zip)

**Comment by zacjansheski** [comment]
This is no longer an issue with the latest versions that support Muse Drumline and have the mapping conversion dialogue on open
