### ISSUE TITLE
[MU4 Issue] in Lyrics, verses should have coresponding text style set

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13762]
**Describe the bug**
In Lyrics, verses should have coresponding text style set. Odd verses "Lyrics odd line" and even verses "Lyrics even lines"

**To Reproduce**
1. Select word in second (even) verse
2. Click on "Properties -> More
3. See: text style is set to "Lyrics odd line"

**Expected behavior**
Style should be set to "Lyrics even line"

**Screenshots**
![verse-style](https://user-images.githubusercontent.com/1646034/195861059-f2885e00-4f7f-48cb-b8c2-3ca46908eb5a.png)

**Platform information**
 - OS: [reported on  Linux]

**Comment by Jojo-Schmitz** [comment]
Seems this issue is back, at least in 4.3.2
Came up in https://musescore.org/de/node/365266

**Comment by Jojo-Schmitz** [comment]
And also in https://musescore.org/en/node/365953

**Comment by Jojo-Schmitz** [comment]
Actually that fix was plain wrong, instead of changing 
```cpp
    bool isEven() const { return m_no % 1; }
```
to
```cpp
    bool isEven() const { return m_no % 2; }
```
it should have been / should be (like it is in Mu3)
```cpp
    bool isEven() const { return m_no & 1; }
```

**Comment by Jojo-Schmitz** [comment]
So please reopn this issue and assign to me

**Comment by Jojo-Schmitz** [comment]
Seems I'm wrong about the way to fix it, for some strange reason it just doesn't work

**Comment by cbjeukendrup** [comment]
I think this is a duplicate of https://github.com/musescore/MuseScore/issues/23846, which would be fixed by https://github.com/musescore/MuseScore/pull/23868. Is that right?

**Comment by Jojo-Schmitz** [comment]
Rather the other way round...
