### ISSUE TITLE
[MU4 Issue] Trill lines "bleed" onto adjacent notes

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#13767]
**Describe the bug**
Trill lines "bleed" onto the note directly after the trill, causing it to also trill for it's entire duration.

**To Reproduce**
1. Make a score with any pitched instrument
2. Put two notes, the first with a trill line
3. Playback the score
4. Hear the trill play over both notes

**Expected behavior**
The trill should only play on the note(s) it is over.

**Screenshots**
https://user-images.githubusercontent.com/21023353/195954301-3c43caa0-28c6-4e6b-bf27-17880d200a32.mp4

**Platform information**
 - OS: Windows, Mac

**Additional context**

**Comment by cbjeukendrup** [comment]
This has been fixed meanwhile, so I'm closing it! (See also #14105.)
