### ISSUE TITLE
Chord Symbols should 'play' once when they have been created.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#13760]
**Describe the bug**
In MS3, after a chord has been created, we hear the sound of the chord. We do not hear this in MS4.

**To Reproduce**
See video:

https://user-images.githubusercontent.com/21022311/195846946-a48ce379-6cbe-4b23-b0d0-a053db6d2d34.mov

**Additional context**
Please ignore my comments on volume / velocity in the video. These are covered in a different issue already.

Also, I'm aware it's an F **minor** 7, so don't mention that you pedants!

**Comment by MarcSabatella** [comment]
FWIW, the chord *does* play during input if you hit Space to move to the next beat/note (or use any of the navigation shortcuts for chord symbol entry) - it only fails is when terminating chord symbol input.  So obviously the code to play during input is there already, it's just not being triggered in that case.
