### ISSUE TITLE
[MU4 Issue] Trill playback speed is affected by ties

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#13768]
**Describe the bug**
Trills (lines or not) on tied notes go slower depending on how many ties the note has.

**To Reproduce**
1. Create a score with a trilled note
2. Add a tie to the note
3. See that the trill speed has decreased

**Expected behavior**
Ties should not decrease the speed of trills. They should be the same speed regardless.

**Screenshots**
https://user-images.githubusercontent.com/21023353/195954904-49f363d8-7d1b-4c4d-999e-54588374daa0.mp4

**Platform information**
 - OS: Windows, Mac

**Additional context**
It appears that the trill speed changes so that it always has the same number of notes the first note would get without the ties.

**Comment by erinic04** [comment]
Also, if you tie a shorter note to a longer note, the trill doesn't extend into the longer note at all in some cases

**Comment by zacjansheski** [comment]
This no longer seems to be an issue, closing this.

https://github.com/musescore/MuseScore/assets/69917893/6d6d186a-4f00-49ba-afbd-f04f3d9254eb
