### ISSUE TITLE
[MU4 Task] Implement "Lyrics" panel in Properties with missing MS3.6 functionality and new button icon 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13761]
**Task description**
This task would resolve #13673. It comprises two elements: 

1. A new "Lyrics" panel would appear in Properties whenever a lyric element is selected:

<img width="318" alt="Properties_Lyrics-new" src="https://user-images.githubusercontent.com/86290556/195846069-847b519a-9b7a-4924-88eb-cd5f11f9cbab.png">

For now, this setting should function as per MS3.6 (Note also the change in label from "Verse" (3.6) to "Set to verse")

2. A new "Lyrics" button would appear in Properties whenever multiple different elements are selected:

<img width="627" alt="Screenshot 2022-10-14 at 2 21 29 pm" src="https://user-images.githubusercontent.com/86290556/195846271-e637d93e-eca7-4dfd-93d1-ccd844fbc8e5.png">

**New button icon**
Please note the new button above uses a new icon: F441 in musescoreicon
Download the new font files here: 
[musescoreicon_14Oct22.zip](https://github.com/musescore/MuseScore/files/9786261/musescoreicon_14Oct22.zip)

@HemantAntony please feel welcome to tackle this one if you like!

Many thanks 🙂

**Comment by HemantAntony** [comment]
Cool! I am going to start working on this soon! :)

**Comment by sammik** [comment]
I think, following is also related: coresponding verse should have corresponding style set (odd or even)

![verse-style](https://user-images.githubusercontent.com/1646034/195851034-f1e9c5d4-07e7-412d-b5f3-086b0134f2ab.png)

**Comment by bkunda** [comment]
> I think, following is also related: coresponding verse should have corresponding style set (odd or even)
Ah yes, I can see that the text style currently doesn't change if you select different verse lines.
Good spot @sammik! I'd suggest this should be raised as a separate issue (happy for you to raise it if you wouldn't mind!)

**Comment by sammik** [comment]
>I'd suggest this should be raised as a separate issue (happy for you to raise it if you wouldn't mind!)

Reported as #13762

**Comment by HemantAntony** [comment]
@bkunda Check #13770

**Comment by sammik** [comment]
> @bkunda Check #13770

@HemantAntony 
Please, correct Lyric**s** (plural)

**Comment by HemantAntony** [comment]
I actually did think of that, but the heading of those properties are usually given in singular like Text style, Hairpin. So I assumed Lyric would be the singular of Lyrics. It did sound weird to me

**Comment by Tantacrul** [comment]
I think the suggestion to call it 'Lyrics' makes sense here, even though we have singular in other places. Bear in mind, we also have 'dynamics'.

In English, 'Lyric' just seems wrong.
