### ISSUE TITLE
[MU4 Issue] Crashes when opening big file

### ISSUE THREAD

**Issue by LMGMMel** [musescore/MuseScore#13776]
**Describe the bug**
When trying to open a rather big file (311kB) the program crashes. Smaller files are no problem. 

**To Reproduce**
1. Go to 'Open new file' 
2. Click on a file which is relatively big

**Expected behavior**
I expected the program to open the file. Musescore 3 doesn't seem to have a problem with it

**Platform information**
Mac OS

**File**
[Le Nozze di Figaro ACT I Arrangement Complete.pdf](https://github.com/musescore/MuseScore/files/9792365/Le.Nozze.di.Figaro.ACT.I.Arrangement.Complete.pdf)

**Comment by MarcSabatella** [comment]
Please attach the file in question so this can be investigated.  ZIP it first so GitHub will accept it.

**Comment by LMGMMel** [comment]
Done! I edited the original comment.

**Comment by SteveBlower** [comment]
That is a pdf - a picture of the score, which will definitely not load into any version of Musescore. It is the .mscz that is needed.  But Github doesn't allow uploading of those so you need to make it into a valid (in Github terms) file type.  One way to do that is to make it into a .zip file either by using a file compression utility or (quick and dirty) just rename the file and add .zip to the file name. When someone downloads the file they can unzip it - if you compressed it, or just rename and delete the .zip extension if you didn't.

**Comment by LMGMMel** [comment]
[Le Nozze di Figaro ACT I Arrangement kopie.zip](https://github.com/musescore/MuseScore/files/9792501/Le.Nozze.di.Figaro.ACT.I.Arrangement.kopie.zip)

It should be ok now

**Comment by sammik** [comment]
Latest nigtly, linux.
Opened without crash.

Here is saved as MU4, please, check, if it works (if migration is problematic)
[Le.Nozze.di.Figaro.ACT.I.Arrangement.kopie_MU4.zip](https://github.com/musescore/MuseScore/files/9792923/Le.Nozze.di.Figaro.ACT.I.Arrangement.kopie_MU4.zip)

Possibly related #11392

**Comment by LMGMMel** [comment]
It works! Thank you so much!

**Comment by SteveBlower** [comment]
Original file also opens for me (but S...L...O...W...L...Y) with OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3254398636, revision: github-musescore-musescore-abc123456

@LMGMMel which version of MS4 were you using?

**Comment by LMGMMel** [comment]
Alpha 2. I guess it's the newest version.

**Comment by MarcSabatella** [comment]
Definitely not, the alpha 2 is a couple of months old now.  The nightly builds are what you should be using for testing.

**Comment by KaiVinter** [comment]
> Alpha 2. I guess it's the newest version.

It's been quite a while since Alpha 2.
Nightly builds are the ones to use to test. As the name implies, they're created every night.

**Comment by LMGMMel** [comment]
Aaaaaah, I didn't know. Do you have a link to the latest version perhaps?

**Comment by MarcSabatella** [comment]
Go to musescore.org, click Download / Software, scroll down to the development builds section.  Then be sure to grab a *nightly*, and don't get fooled by the year-old bild that i incorrectly labeled "beta".

**Comment by KaiVinter** [comment]
You can find them in musescore.org > Download > Development Builds > Nightly Builds > MuseScore 4.x (Master) > Nightly
Don't use the "Beta", that's an old build that is mislabeled as Beta. But there's no Beta yet

**Comment by LMGMMel** [comment]
Thanks a lot you guys!
