### ISSUE TITLE
[MU4 Issue] Velocity and Tuning have no affect on playback

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13782]
**Describe the bug**

Changing the Velocity or Tuning of a note in Properties >Playback > General makes absolutely no difference to the playback of the note

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3258241938, revision: github-musescore-musescore-644cc12

**Comment by HemantAntony** [comment]
Duplicate of #10990

**Comment by Tantacrul** [comment]
The duplicate is already in Beta 1 also, so closing this.
