### ISSUE TITLE
[MU4 Issue] playback bugs

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13780]
**Describe the bug**
### 1) infinite play on empty score (see: 00:05), or extra 7 beats on non empty score (see 00:30)
**To Reproduce**
1. Create new empty score
2. Start playback
3. See - playback still continues after score finished

### ~2) If endindgs are aded to score, playback after ending is affected (see 00:45)~
**~To Reproduce~**
~1. Create score~
~2. Add some notes to bar 10 or so~
~3. Create repeat with endings before bar with notes~
~4. Play notes after endings~
fixed by #14449

### ~3) If pitch is changed after endings all notes that were on corespondong beat are played (02:00)~
**~To Reproduce~**
~1. Open score with endings (or create one)~
~2. Change pitch on some note after endings~
~3. Play - see, all pitches on that beat are played~
fixed by #14449

### 4) Chords after ending play, even if Play option is unticked in properties (02:28)
**To Reproduce**
1. Open score with endings
2. Add some chords after ending
3. Select chords and untick "Play" option
4. Play score - Chord is still playing back

**Screenshots**
**unmute video to hear it please**

https://user-images.githubusercontent.com/1646034/196008334-26cf1567-b1ac-4f86-9e5a-24d7a1610389.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
1. If You save and reopen file, it initially plays correctly. Every time, only new changes produces bugs.
2. Lenght of the prima volta in 2nd bug play role. It is different, if only one bar prima volta, or two bars (playback starts to repeat after length of prima volta)

**Comment by sammik** [comment]
1. was reported separately as #13683

**Comment by DmitryArefiev** [comment]
@sammik Can you try №5 again in latest master please? I can't reproduce it now

**Comment by sammik** [comment]
> @sammik Can you try №4 again in latest master please? I can't reproduce it now

I cant reproduce it anymore. Thank You. 
Closing this again.

**Comment by DmitryArefiev** [comment]
Cool! Thanks!
