### ISSUE TITLE
[MU4 Issue] Thumbnails in "Scores" appear to be unsorted   

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13793]
**Describe the bug**
I can't quite work out what the sorting method is that is being used for thumbnails in the "Scores" screen (it's certainly not alphabetical), but it is currently making it extremely difficult to locate files when there are many of them.

In this screenshot, for example, note that some of my more recently-viewed scores are actually scattered throughout the list. The score I was working on "today" appears towards the bottom of the screen:

<img width="3008" alt="Screenshot 2022-10-17 at 3 21 09 pm" src="https://user-images.githubusercontent.com/86290556/196188834-275f42f5-9f0b-45bb-ba07-fb3c85c4bf30.png">

**Expected behavior**
For now, I think it makes sense if the thumbnails on this screen are sorted by most recently viewed (as in, most recently opened). We can think about implementing some further sorting options at a later stage.  

**Platform information**
 - MacOS 12.6 (M1)

**Comment by cbjeukendrup** [comment]
@bkunda The list is* sorted by "last opened", and the dates that you see are the "last modified" dates. That should explain the discrepancy. 

Every time that you open or save a score, it is bumped to the top of the list.

\* unless this has been broken recently, but that would _really_ surprise me.

**Comment by bkunda** [comment]
You're right, of course @cbjeukendrup. That is exactly how it works – and it does still work! 😅
It would appear I have been tripped up by a potential UX trap. Given that sorting obviously works, I don't think addressing this need be a priority now, so I'll close this issue and make a note about it to revisit later.
