### ISSUE TITLE
[MU4 Issue] Rhythm stems on tablature staves are too short

### ISSUE THREAD

**Issue by GrayCatMusic** [musescore/MuseScore#13800]
**Describe the bug**
A short and clear description of what the bug is.

Rhythm stems on tablature are too short by default. I have to make most of them 2.5 in length. If I copy and paste a passage with those stems that I elongated, the pasted *treble* clef stems will be elongated too. 

**To Reproduce**
Create a new score with a treble clef staff and a linked tablature staff for any instrument. 
Enter notes on the treble clef. Notice how short the stems are. 
Elongate stems to desired length. 
Copy and paste the treble clef notes to a different part of the score. 
Notice the longer stems on the treble clef notes now. 

**Expected behavior**
I expect the rhythm stems to be a reasonable length like they were in MS3

**Screenshots**
Here's an example with a transcription for a ukulele tuned in D.
<img width="1094" alt="Screen Shot 2022-10-17 at 10 58 05 AM" src="https://user-images.githubusercontent.com/89216233/196226264-57f14153-6e52-40e1-be7a-a8b3481a0e69.png">
By changing their length to 2.5:
<img width="1116" alt="Screen Shot 2022-10-17 at 10 58 51 AM" src="https://user-images.githubusercontent.com/89216233/196226366-1e761606-e84e-4c00-a8df-f9fcaacc2260.png">
And then pasting that same passage to the next line:
<img width="1145" alt="Screen Shot 2022-10-17 at 10 59 05 AM" src="https://user-images.githubusercontent.com/89216233/196226568-7f514695-dd8d-45c4-8b96-edde444f6cdb.png">

**Platform information**
Mac OS Monterey 12.6

**Additional context**
This happens regardless of the instrument or amount of strings on the tablature.

**Comment by asattely** [comment]
I am not able to reproduce this on Windows, interestingly:
![image](https://user-images.githubusercontent.com/89263931/222248828-b3debd2f-0a3c-4118-8d46-4c86139be77c.png)

Is there anyone out there who can investigate this on OSX? relevant parts of code are:

Stem length:
https://github.com/musescore/MuseScore/blob/8319ad54622f88ab936823fce5b994fe176dbe4d/src/engraving/libmscore/stafftype.cpp#L738

Stem position:
https://github.com/musescore/MuseScore/blob/8319ad54622f88ab936823fce5b994fe176dbe4d/src/engraving/libmscore/stafftype.cpp#L675

Both using values defined here:
https://github.com/musescore/MuseScore/blob/8319ad54622f88ab936823fce5b994fe176dbe4d/src/engraving/libmscore/stafftype.h#L45
