### ISSUE TITLE
[MU4 Issue] Zoom to page width command missing

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13806]
**Describe the bug**
The "zoom to page width" comamdn from MU3 is missing

**To Reproduce**
1. Go to Edit / Preferences / Shortcuts
2. Search for "Zoom"
3. See error: no zoom to page width command

**Expected behavior**
Zoom to page width should be an available command

**Platform information**
 - OS: Linux

**Additional context**
The underlying code is present, but the command it not hooked up.

In MU3, this actually worked as a toggle, switching between page width and whatever the previous setting was.  That's somewhat useful but the current code does not appear to support it.  Not a big deal to me; the command is worth having anyhow.   I will try a PR for this...

**Comment by DmitryArefiev** [comment]
Implemented in #13807

Before:

![Capture](https://user-images.githubusercontent.com/90187801/235750855-30ee4129-9d6d-4ed0-8c86-7c47e85b263f.PNG)

After:

![Capture2](https://user-images.githubusercontent.com/90187801/235750889-aeeaf046-01ab-4ba2-91c6-df8ba70bc8ed.png)
