### ISSUE TITLE
[MU4 Task] Window can't be resized enough

### ISSUE THREAD

**Issue by UnaidedButton86** [musescore/MuseScore#13818]
**Task description**
So this probably is intentional, but hear me out,

![image](https://user-images.githubusercontent.com/87303800/196436279-29e99861-71c6-4ea5-9799-556259fb41cf.png)

Writing over from e.g. a PDF.
This is one of the things I do all the times with MU3, but is impossible in the nightly builds of MU4
You could say there's a function to import PDF's, but it doesn't recognize anything in normal pieces:

![image](https://user-images.githubusercontent.com/87303800/196440072-9ab8ba11-b69a-47d9-baac-d8bf0797f6ba.png)

**Comment by MarcSabatella** [comment]
This is a duplicate of https://github.com/musescore/MuseScore/issues/13372.  It's unfortunately currently as good as can be done, but obviously, it would be good to be able to do better in the future.

**Comment by sammik** [comment]
You can probably force PDF window to be "always on top".
I have this option on riht click - more actions (Linux KDE Plasma)

**Comment by UnaidedButton86** [comment]
> This is a duplicate of #13372. It's unfortunately currently as good as can be done, but obviously, it would be good to be able to do better in the future.

Closing for duplicate
