### ISSUE TITLE
[MU4 Issue] Extra notes heard on repeat

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#13811]
**Describe the bug**
In the given score for two voices, a third voice enters and plays along during the repeat.

**To Reproduce**
1. Open this score: https://musescore.com/user/2975/scores/8832948/s/WjWOoF?share=copy_link
2. Add a start repeat to the marked measure (bar 3 of the second page)
3. Start playback somewhere before the end epeat
4. Hear error: on the repeat, in around the second bar, a third voice enters and continues playing throughout the rest.

**Expected behavior**
It sounds pretty nice, actually, because it's a round, but - I only wrote two voices, I should only hear two voices :-)

**Screenshots**
Here is a video: https://watch.screencastify.com/v/AScFIAkNZQh6pcyMdAbp

**Platform information**
 - OS: Linux

**Additional context**
The problem goes away on save / reload, so I guess it has something to do with the playback info not being built correctly immediately after adding the repeat.  Perhaps the section break on the previous page is significant, but actually, if I delete it, I get even crazier results.  Actually, I can tell it's playing a line from the beginning of the score, as I hear the A natural.

**Comment by sammik** [comment]
I reported similar (but not identical) issues as #13780 
But core may be same.

**Comment by rgreen5** [comment]
And #13683.

**Comment by MarcSabatella** [comment]
@Tantacrul this is likely related to #13780 but is infinitely more critical; not just the playback running past the end of the score but actually hearing notes from multiple measures at the same time.  I know it's been discussion a bit on Discord but I'm not seeing another really clear issue for this specifically.

Here is a really simple sample case:

![image](https://user-images.githubusercontent.com/1799936/198858854-be416a1f-baf4-4223-a99d-ba0c1d7e3b84.png)

Enter that in a score created from scratch and hit play.  On the DC, starting at bar 3, you hear both bar 3 & 4 playing at the same time, then in bar 4, you hear bars 4 & 5 together.  Actually I think you might be hearing three bars being played at once.

This is still the case with nightly build as of )October 29.

**Comment by cbjeukendrup** [comment]
Important information from #14263: this happens exactly the same with both Muse Sounds and MS Basic. Not sure if that was already clear, but let's make it explicit anyway :)

**Comment by DmitryArefiev** [comment]
@MarcSabatella Can you check this issue on build from #14449 (or in master tomorrow)

Thanks!

**Comment by MarcSabatella** [comment]
Will do, looking forward to it as it seems there quite a few symptoms here that hopefully will all be cleared up by this fix!

**Comment by DmitryArefiev** [comment]
Oh thanks!

**Comment by MarcSabatella** [comment]
So far so good - I din't hear any problems with this or any of the other scores where I was experiencing repeat issues.

**Comment by DmitryArefiev** [comment]
> So far so good - I don't hear any problems with this or any of the other scores where I was experiencing repeat issues.

@MarcSabatella Great! Then let's close it. Thanks for testing!
