### ISSUE TITLE
[MU4 Issue] Acciaccaturas plays as appoggiaturas 

### ISSUE THREAD

**Issue by krtschil** [musescore/MuseScore#13817]
**Description**
Grace notes do not play properly when compared to how it sounds with MU3. It sounds like the grace notes are played AFTER the notes but should be played BEFORE (see attached scores [measures 2 and 5] and .mp3 exports for comparison).

**Expected behavior**
These grace notes should be played before the notes they are attached to.

**Platform information**
 - OS: Linux,macOS

**Attachment**
[Test.zip](https://github.com/musescore/MuseScore/files/9810375/Test.zip)

**Comment by sammik** [comment]
I hear them before notes in both cases.
Just in MU4 they are played two times slowlier (as eight notes).

**Comment by MarcSabatella** [comment]
This is correct Baroque-style interpretation of appopggiaturas (half the value of main note); better to use acciaccaturas if you want them played quickly.  MU3 did treat appoggiaturas as if they were acciaccaturas when added in groups; MU4 could consider doing the same.

See also https://github.com/musescore/MuseScore/issues/14093 - one of these can be closed as a duplicate.

**Comment by krtschil** [comment]
Actually the attached example above is taken from an official score https://musescore.com/official_scores/scores/6963091
Playing it online sounds like MU3 and using acciaccaturas instead sounds even worse.

**Comment by MarcSabatella** [comment]
If you’re experiencing a problem with acciaccaturas, that’s separate - best to open a new issue for that.

**Comment by adamspagge** [comment]
Actually, I have a problem with grace note oversounding a lot. The score was created in MS3.6. The appogiatura is being held for a long time which creates a terrible dissonancy. Video atttached for reference.


https://user-images.githubusercontent.com/16725155/200148071-85a13af7-8e31-4517-bbc3-6b34ffc2a7cd.mov

**Comment by abariska** [comment]
Changed description of the issue a bit.
I also meet this issue when acciaccaturas start playing in the main note time (and main note sounds after its time) instead of before. Only the difference that acciaccaturas sounds a bit out of time.

https://user-images.githubusercontent.com/101250347/207589293-0e76422a-3e7d-4f8a-ac52-d7f998f7a4ff.mp4

[Test4.mscz.zip](https://github.com/musescore/MuseScore/files/10227566/Test4.mscz.zip)

**Comment by abariska** [comment]
@oktophonie please, clarify if my expected result is correct? 
I know that depend on genre of music could be different ways to play them but default behaviour should be different from each other

**Comment by oktophonie** [comment]
@oktophonie tends not to weigh in on playback issues; he is generally concerned with how things look, and less with how they sound.
(He will, however, agree that the current system is somewhat inadequate; the presence or absence of a slash shouldn't really determine whether something is an acciaccatura or an appoggiatura or not, whether it's played fast or slow, whether it's on or before the beat, etc; these should all be customisable.)

**Comment by Dima12357** [comment]
I tried to explain the same thing in issue #20494

**Comment by DmitryArefiev** [comment]
@krtschil Please compare MU3 and 4.4 nightly master 
Mac: https://github.com/musescore/MuseScore/actions/runs/8810360611
Linux: https://github.com/musescore/MuseScore/actions/runs/8810390190
