### ISSUE TITLE
[MU4 Issue] opening midi files causes crash (regression)

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13825]
**Describe the bug**
Opening some midi files causes crash. Files are open fine in MU3.

**To Reproduce**
1. Get attached file [Sammartini.zip](https://github.com/musescore/MuseScore/files/9813657/Sammartini.zip) (extract midi)
2. Open it
3. See crash

**Expected behavior**
MU opens file.

**Platform information**
 - OS: [reported on Linux]

**Additional context**
Not every midi file crashes.
MU3 works.

**Comment by Tantacrul** [comment]
Confirmed. Crashed on any MIDI I tested. Here are three more that crash MS4:
https://www.dropbox.com/sh/1bbf0u60y2lnvdj/AADiC60cOQ4wgIPZR9kLnxCma?dl=0

Nice spot @sammik !

**Comment by DmitryArefiev** [comment]
Fixed in #13841
