### ISSUE TITLE
[MU4 Issue] MU crashes when using drag and drop on Linux

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13845]
**To Reproduce**
1. Open MU
2. Drag'n'drop any score

**Platform information**
**Linux Ubuntu 22.04 LTS**
Doesn't occur on Mac/Win 

**Additional context**
Doesn't occur in **MS3**

**Comment by sammik** [comment]
Cant reproduce
Linux Ubuntu Studio 22.04 KDE Plasma

**Comment by DmitryArefiev** [comment]
Oh.. Thanks for testing.

@Eism Can you try on you Linux machine please?

**Comment by Eism** [comment]
Ah, may be it is depends on workspace environments
For me it is KDE Plasma too as for @sammik 
(Switched to kde for fixing https://github.com/musescore/MuseScore/issues/13113)

**Comment by HemantAntony** [comment]
Okay then, I'll try finding out the problem

**Comment by Grillzombie** [comment]
Don't crash on
OS: Linux Mint 21, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3286835863, revision: github-musescore-musescore-6a5fc09

**Comment by HemantAntony** [comment]
@Eism The `m_loop.exec()` is the line which crashes it. I have no idea how to fix this since its related to QEventLoops. If anyone needs helps debugging this further, do ask :)

**Comment by Eism** [comment]
@HemantAntony Please show the stacktrace of the crash

**Comment by HemantAntony** [comment]
![image](https://user-images.githubusercontent.com/88136054/197015397-bc20df91-6ae9-4320-9717-e507105d0c1b.png)

**Comment by Eism** [comment]
@HemantAntony thank you!
I learned how to switch between sessions in kde and can reproduce the bug on wayland :)

**Comment by DmitryArefiev** [comment]
Fixed in #13958
