### ISSUE TITLE
[MU4 Issue] MuseSounds output volume is softer overall, relative to MS Basic

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13842]
**Describe the bug**
In general, there is about a 9dB difference between Muse Sounds and MS Basic (Muse Sounds being overall significantly softer).

Comparative video: winds, brass, some percussion: https://www.dropbox.com/s/qtqpok4c1aod6ly/MuseSounds-volume-comparison-winds-brass-perc.mov?dl=0

Comparative video: piano, harp, strings: https://www.dropbox.com/s/7chpzlhok6jut5a/MuseSounds-volume-comparison-pno-hrp-strings.mov?dl=0

I understand we are yet to properly mix playback. This table might perhaps be of some assistance when we get around to mixing (maximum volume levels were measured in Logic using the audio from the above videos with no dynamic markings applied. The very significant volume differences between, for example, the french horns, and to a lesser extent the bassoons and violas, are easy to hear):

<img width="443" alt="Screenshot 2022-10-20 at 11 28 28 am" src="https://user-images.githubusercontent.com/86290556/196911423-173f047e-005a-4cca-810e-b56b361e055a.png">

**Expected behavior**
As a starting point, the overall volume of MuseSounds could be increased by somewhere between 5dB-9dB (obviously would need to be tested for any undesirable clipping or distortion).

**Platform information**
 - MacOS 12.6 (M1)

**Additional context**
Not sure if this is also related to #13053, but the main issue I'm raising here is the _relative_ difference between MS Basic and Muse Sounds, rather than a comparison with other notation apps.  

@Tantacrul FYI

**Comment by Tantacrul** [comment]
Vasily and I had a secret agreement that we'd tackle mixing issues once beta was out. But for sure, Muse Sounds does seem to generally be very quiet. Thankfully very easy to set a new global setting.

**Comment by Tantacrul** [comment]
@bkunda - what do you think? Shall we close this and perhaps instead focus on issues related to balance within instruments in the Muse Sounds set instead?

I do take the point that the highs can get very high with Muse Sounds, so the dynamic range is naturally wider.
