### ISSUE TITLE
[MU4 Issue] Dynamics retroactively apply to sustained notes

### ISSUE THREAD

**Issue by la-bel** [musescore/MuseScore#13854]
**Describe the bug**
Within an instrument, adding a dynamic marking midway through a sustained note changes the velocity of the sustained note.

**To Reproduce**
1. Create a grand staff or solo piano score
2. Add notes to both staves or in multiple voices - one line should have a long note, the other much shorter notes
3. Start with one dynamic marking and change to another, or use a sfz/sffz mark.

**Expected behavior**
At least for piano, once a note has been played, you can't make it get louder and you can only make it get softer by releasing the key and controlling the sound with the pedal. When I write a piano note, I expect it to decay according to the dynamic it started with. I can't speak to the expected behaviour on non-keyboard instruments.

**Screenshots**
<img width="527" alt="Screenshot 2022-10-20 at 22 57 12" src="https://user-images.githubusercontent.com/63920211/197066635-a7e1b103-a79a-40e5-b85d-d04272313300.png">
Bar one: the RH note should still sound loudly in the second half, it gets much quieter
Bar two: the first chord should decay as a loud note
Bar three: the first octave should decay as softly - the RH note should not get louder

**Platform information**
 - OS: macOS

**Additional context**
This adds up to make playback on a few of my piano scores significantly worse than MS3

**Comment by cbjeukendrup** [comment]
I think the expected behaviour also depends on the instrument. What you describe is obviously correct for piano and several other instruments (maybe except in the case of tremolo notes? those aren't really "sustained" notes anyway), but for instruments that can do "in-note dynamics", it is probably different.

**Comment by la-bel** [comment]
It should only be a problem for polyphony — as far as polyphonic instruments go, if I wanted to write an organ piece that changed registration or swell pedal mid-note, I wouldn't notate it like this (but I wouldn't expect good native organ playback on MuseScore anyway—maybe one day...).

For a split group, like a cello section, my expectation would be for exclusively per-voice dynamic markings in the event of possible ambiguity, and that default behaviour would be that notes maintain their initial dynamic rather than following a dynamic change applied to a different voice—but I have only written those parts rather than played them.

**Comment by la-bel** [comment]
Fixed in «major new build» linked on Discord
