### ISSUE TITLE
[MU4 Issue] Editing a score that has already been published doesn't apply the modifications on the online version

### ISSUE THREAD

**Issue by Stccl** [musescore/MuseScore#13868]
**Describe the bug**
When you work on a score that you have already published to musescore.com from musescore 4 directly, it doesn't apply the modifications to the online version when you save. You thus have to edit the file directly from musescore.com. This means that if you're working with VSTs, you will need to update the score as a brand new one for it to have VST sounds on the website, since you need to render audio to publish a score with VST sounds on the website.

**To Reproduce**
1. Create as score and publish it on musescore.com from musescore 4.
2. Edit somethig on it.
3. Save it with ctrl + s
4. Musescore doesn't ask to re-render the audio and doesn't replace the existing online score with the new version.

**Expected behavior**
When saving a score that has been published to musescore.com, it should re-render the audio, upload the new version of the score and REPLACE the old version with it. Instead, it just saves the local file on your computer.

**Platform information**
 - Windows 10

**Additional context**
You should be able to choose if you want to re-render the audio and save the changes on musescore.com when you hit ctrl + s. You should also be able to choose if you want it to do that with every auto-save, or once every X autosaves.

**Comment by MarcSabatella** [comment]
If you want to update the score on musescore, you need to publish it again.  Same as MU3 (and MU2)

It's only when using "save to cloud" that your changes get pushed on every save - but the audio is not necessarily regenerated every time.  There is a preference setting to control how often the audio gets regenerated.

**Comment by Stccl** [comment]
@MarcSabatella Yeah, I got it. As I said in discord the "save to cloud" feature is indeed broken, but the "publish to musescore" one has no issue.

I do find however that having to click "publish" each time you want to push the changes online might not be the most intuitive thing in the world. Maybe once it's been published, the option should rename to "update published score" or something? Who knows.

**Comment by MarcSabatella** [comment]
Agreed.  MU3 simply called it "save online" which made it a little clearer.  But FWIW I do like the suggestion of Publish / Update.
