### ISSUE TITLE
[MU4 Issue] Crash when closing ARIA Player VST window

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#13867]
**To Reproduce**
1. Create score
2. Load ARIA Player VST for an instrument (can be downloaded for free and without any account from https://makemusic.zendesk.com/hc/en-us/articles/4548377288599-ARIA-Player-version-2-001-Apple-Silicon-Native-)
3. Close the ARIA Player window 
-> Crash

**Platform information**
 - OS: tested on two macOS computers

**Comment by DmitryArefiev** [comment]
Fixed in #15227
