### ISSUE TITLE
[MU4 Issue] 'Don't show this message again' checkbox is not clickable in migration dialog 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#13866]
![Capture](https://user-images.githubusercontent.com/90187801/197263401-6bf17332-6f8d-4eab-984c-a42ffa0f8656.PNG)

https://user-images.githubusercontent.com/90187801/197263424-5ca620ed-b8e8-49b6-a4a7-493521bb6485.mp4

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Comment by cbjeukendrup** [comment]
Still after #13850?

**Comment by DmitryArefiev** [comment]
Yeah

**Comment by DmitryArefiev** [comment]
Fixed in #13869
