### ISSUE TITLE
[MU4 Issue] Crash when shift+selecting a range that contains a beam over a rest 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#13863]
**Describe the bug**
Selecting a range that contains a beam group over a rest triggers a crash:

See video demo: 

https://user-images.githubusercontent.com/86290556/197212136-ffab7d92-ab4b-4f81-8550-ee7a0b659d61.mov

**Platform information**
 - MacOS 12.6 (M1)
 - MuseScore beta (from Hub v.0.9.5)

**Additional information**
Test score used in the above video: 
[Tannhäuser-excerpt-Wolfram.mscz.zip](https://github.com/musescore/MuseScore/files/9839652/Tannhauser-excerpt-Wolfram.mscz.zip)

**Comment by MarcSabatella** [comment]
Isn't the bug just fixed the other day?  See https://github.com/musescore/MuseScore/pull/13832

**Comment by oktophonie** [comment]
It appears so!
