### ISSUE TITLE
[MU4 Issue] Editing anything after editing bracketing selects all the bracketing you've edited (also Repeat doesn't work properly)

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#13870]
**Describe the bug**
If you have a score with any bracketing that has been edited (or new brackets), if you edit anything, it will select all the bracketing with the edits.

**To Reproduce**
1. Make a new score
2. Put new bracketing on the score (spanning multiple staves) OR edit any existing bracketing
3. Edit anything in the score
4. Observe that all the new/edited bracketing is selected

**Expected behavior**
The bracketing should not be selected.

**Screenshots**

https://user-images.githubusercontent.com/21023353/197308311-b9f0f276-010c-40c0-80c1-ac8cf9207402.mp4

**Platform information**
 - OS: Mac, Windows

**Additional context**
If you restart Musescore, the items become "unlinked"

**Comment by DmitryArefiev** [comment]
The same when just edit the bracket and input notes. But more **critical with Repeat** command (R), you **can't use it more than two times in a row**


https://user-images.githubusercontent.com/90187801/202464493-389910e7-4950-4900-863f-8677e295b32d.mp4

Thanks for logging!

**Comment by DmitryArefiev** [comment]
Fixed in #14572
