### ISSUE TITLE
Crash when adding Time Signature

### ISSUE THREAD

**Issue by flyingrabbitgb** [musescore/MuseScore#13871]
When trying to drag a new time signature into a score, Musescore crashes to desktop without fail. This happens both with dragging/dropping and with selecting the measure to apply it to and double-clicking in the toolbox.

**Comment by oktophonie** [comment]
It would be useful to know what build you are using.

Do you have any parts open for your score when this happens? If so, this should be fixed by https://github.com/musescore/MuseScore/pull/13856.

**Comment by flyingrabbitgb** [comment]
I'm on the latest nightly, and yes, this happens when working in a part.

**Comment by oktophonie** [comment]
OK, good news (in a way)! It would great if you could try it again once the above PR is merged (or try that build specifically even before then, if you fancy it) and confirm that you no longer encounter the problem.,
