### ISSUE TITLE
[MU4 Issue] Grace notes holds up to 4 beats.

### ISSUE THREAD

**Issue by MattisBirk** [musescore/MuseScore#13872]
**Describe the bug**
The bug is when you use the gracenotes it does not just give you a short note, it holds the
note up to 4 beats.

**To Reproduce**
1. Go to 'gracenotes'
2. Click on 'the note you want'
3. Place it
4. Play the bar
5. Hear the error.

**Expected behavior**
I expected a short note, not a long one.

**Screenshots**
![image](https://user-images.githubusercontent.com/116434202/197334265-dcc8f346-aa23-4744-826e-28bbc2fa237e.png)

**Platform information**
 - OS: Windows

**Comment by MarcSabatella** [comment]
You have added an appoggiatura when you presumably wanted an acciaccatura.  Appoggiaturas by definition take half the duration of the main note, according to standard classical convention.
