### ISSUE TITLE
Single Note Dynamics should be disabled for Piano

### ISSUE THREAD

**Issue by ShawTakeuchi** [musescore/MuseScore#13877]
**Describe the bug**

Single Note Dynamic (SND) appear to be used for piano.  This is true for MS Basic, VST but not Muse Sounds.

Single note dynamic (SND) should be "off" for percussive instruments such as Piano or Drums.  The "hairpin" should *not* affect the sound volume on the sustained notes.

**To Reproduce**
See image:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/21022311/197384788-80162012-349e-44fe-ade6-c0910d0699e2.png">

For the release, single note dynamics should be switched off for:

- Piano
- Celesta
- Vibraphone
- Harpsichord
- Marimba
- Harp
- Guitars
- All other instruments in the 'plucked strings' category
- All percussion instruments

**Comment by Tantacrul** [comment]
Thanks for pointing this out. I have updated the issue to target a fix for this release. I do not think SND should be on for any instrument that can't support it naturally. Perhaps later, we might provide a way for users activate them but I see that as an ultra-niche use case.

**Comment by ShawTakeuchi** [comment]
As of MS 4.0.2 / MuseHub refreshed on 2023.03.15.

*  This issue seems to be fixed for MuseHub Piano!

*  It is not yet fixed for 

1)  MS Basic 
2)  3rd party Soundfont (tested with MS3 default soundfont port by Mark Sabatella)
3)  3rd party VSTs (tested with EastWest Opus Steinway)

I created a mscv test file with various use-cases if helpful - See attached.

cc: @MarcSabatella 

[Tester-20230315d.zip](https://github.com/musescore/MuseScore/files/10983598/Tester-20230315d.zip)

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d / MS Basic

I can confirm that _**pf**_ _**fp**_ dynamics are still switched on for classical guitar;, though not working correctly as the last dynamic of the pair persists beyond the next note.

**Comment by DaddyLudwig** [comment]
Is that not how they are supposed to work? I thought _**fp**_ was forte for the first note on instruments that can't support SND and then piano until otherwise marked. And opposite for _**pf**_(which I don't see nearly as often). Whereas _**sfp**_ would not have the piano dynamic persist past the second note and afterwards it would go right back to forte or whatever. At least, that's my understanding of SND.

**Comment by ShawTakeuchi** [comment]
> Is that not how they are supposed to work? I thought _**fp**_ was forte for the first note on instruments that can't support SND and then piano until otherwise marked. And opposite for _**pf**_(which I don't see nearly as often). Whereas _**sfp**_ would not have the piano dynamic persist past the second note and afterwards it would go right back to forte or whatever. At least, that's my understanding of SND.

The issue is not specifically about fp, but MS4 (4.0.2) currently treats piano, drums, harps dynamics like the wind, brass and string instruments.   With impact instruments like piano, once you strike a note, you cannot increase the volume on its sustain or long note by a hairpin (or decrease volume more than the natural decay).  It's more about disabling hairpin dynamics for these instruments, than about fp!

I am hoping this will get picked up for MS release 4.2, as the issue is only partially fixed for MuseSounds.
