### ISSUE TITLE
[MU4 Issue] Ubuntu 22.04 Muse-Hub (test version) Pegging CPU to 100% After Instrument Download

### ISSUE THREAD

**Issue by ShawTakeuchi** [musescore/MuseScore#13875]
**Describe the bug**

MuseHub-Linux (test version): after downloading an instrument, closing the GUI window, pegs one CPU core at 100% until killed

**To Reproduce**

1.   Install Musehub-Linux (test version 2022/10/22)
2.   ./muse-hub
3.   Download single instrument "harp"
4.   Close muse-hub GUI
5.   Check CPU (ps -aux / htop)

**Expected behavior**

CPU usage should reduce to near 0% 

**Screenshots**

Available up on request

**Platform information**

Ubuntu 22.04/64/LTS Desktop
2nd Gen i7 8GB 8-cores (Dell Lattitude)

**Additional context**

Available upon request

/////

It seems MuseHub is partially implemented as a system service running under root -- it is persistently active by default after install, without manually launching the muse-hub GUI or MuseScore app.  I recommend running this as a non-root service, or as part of user-priv forked process as part of the Musescore app.

@Tantacrul @MarcSabatella

**Comment by MarcSabatella** [comment]
Confirmed on my system.  I have no insight into how it should be implemented, but definitely lots of CU usage while Muse Hub is idle, then through the roof if I close it.

**Comment by Tantacrul** [comment]
Is this still happening for you?

**Comment by ShawTakeuchi** [comment]
> Is this still happening for you?

Please verify if I am re-testing the correct version of MuseHub
Musehub Version: 0.9.10.363 downloaded from www.musehub.com on 20221207`
Linux version, running on Ubuntu 22.04 on bare metal (no VM), laptop 

-----------

Single core "100% CPU" problem is still occurring as of 2022.12.07 for the version above, but this seems to be caused by interaction between Muse-hub daemon and Muse-hub GUI front-end app.  (Seems to be independent of MuseScore4.)  Steps to reproduce:

1.  Run htop (or any CPU monitoring app)
2.  Re-start daemon (sudo service muse-hub stop; sudo service muse-hub start)
3.  Run muse-hub front-end GUI app (muse-hub)
4.  Exit muse-hub front-end GUI app 

At step 4, 100% CPU is seen on one core, and it will continue until 1) muse-hub daemon is restarted, 2) muse-hub GUI app is launched again, or 3) the machine is rebooted.

Will try to get more details tomorrow.

**Comment by DominicMaas** [comment]
Sounds like a similar repro as https://github.com/musescore/MuseScore/issues/15016 ?

**Comment by DominicMaas** [comment]
This should now be fixed in the latest version of Muse Hub (v0.9.12)

**Comment by ShawTakeuchi** [comment]
> This should now be fixed in the latest version of Muse Hub (v0.9.12)

Verified working this morning on Musehub 1.0.0.392 downloaded from musehub.com on 2022.12.14 05:00 PST
"100% CPU peg" problem no longer occurs!

*  Tested multiple times starting/exiting muse-hub GUI app, with and without "community acceleration" and "automatic update check" 
*  Update from 0.9 to 1.0 also went through smoothly via dpkg -i muse-hub.deb

Ok to close this issue upon your concurrence.
