### ISSUE TITLE
[MU4 Issue] Closing tab closes the program window as well.

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13884]
**Describe the bug**
Open the attached MS3 test score. Then click on the tab close icon. Whether you save or don't the program closes.

[arpeggio_issue.zip](https://github.com/musescore/MuseScore/files/9845471/arpeggio_issue.zip)

**Expected behavior**

Only the tab should close, not the program.

**Platform information**

 OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289917644, revision: github-musescore-musescore-1ac395a

**Comment by cbjeukendrup** [comment]
Similar to #13764?
(When you have multiple instances of MuseScore open, then closing the tab _is_ supposed to close the window.)

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289917644, revision: github-musescore-musescore-1ac395a

It's fixed now after a "Revert to factory settings".

**Comment by Tantacrul** [comment]
I'm actually in agreement about this. If you have a second window open, closing the score should just bring you back to the 'Home' tab in that same second window. The current behaviour just keeps wrongfooting everyone.

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289917644, revision: github-musescore-musescore-1ac395a

Unfortunately, the issue has recurred. Pressing "Revert to factory setting" doesn't seem to work as the program will not automatically reopen.

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289917644, revision: github-musescore-musescore-1ac395a

Funnily enough, I have downloaded the same version and the problem has disappeared again.
