### ISSUE TITLE
[MU4 Issue] Custom length of strum arrows (in imported MS3 file) reset to default in MS4

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13885]
**Describe the bug**

MS4 is resetting to default length all strum arrows in the attached MS3 file.

[arpeggio_issue.zip](https://github.com/musescore/MuseScore/files/9845476/arpeggio_issue.zip)

**Expected behavior**

Position and length of all arpeggio symbols in imported MS3 files should be unchanged

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289917644, revision: github-musescore-musescore-1ac395a

**Comment by Tantacrul** [comment]
@mike-spa @oktophonie - can you have a look and triage as needed?
