### ISSUE TITLE
[MU4 Issue] Muse Hub can't be opened in MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by KaiVinter** [musescore/MuseScore#13880]
**Describe the bug**
Muse Hub can't be opened in MacOS Mojave 10.14.6

Tagging @Tantacrul as he said in Discord

**To Reproduce**
1. Download the Muse Hub installer (.dmg) and run it.
2. See Muse Hub Icon with a ban sign

**Expected behavior**
No ban sign so it can be oppened

**Screenshots**
![Screen Shot 2022-10-22 at 2 34 47 PM](https://user-images.githubusercontent.com/88064903/197363412-0882d5de-9a3f-4d0c-8835-92c7ac9277a9.png)

**Platform information**
 - OS: MacOS Mojave 10.14.6

**Comment by rgreen5** [comment]
Nothing doing in Linux Mint 20.1 (Cinnamon) either.

**Comment by Tantacrul** [comment]
@iamtesch - does the Muse Hub support this version?

**Comment by iamtesch** [comment]
We do not support macOS Mojave for the Muse Hub; you need Big Sur or later here.
