### ISSUE TITLE
[MU4 Issue] Crash when moving staves in case of cross staff notation

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#13886]
**Describe the bug**
In scores with cross-staff notation, moving the staves of an instrument can cause a crash.

**To Reproduce**
1. Create score with grand staff
2. add note on top staff
3. Cmd+Shift+Down to move the note to the bottom staff
4. using the instruments panel, swap the staves OR delete the bottom staff
-> crash 

Also interesting: if you _hide_ the bottom staff instead of deleting it, the note moves back to the top staff but is still on the line as if it is on the bottom staff.

https://user-images.githubusercontent.com/48658420/197366860-1867fb36-48e6-4098-97bf-725dd15c2142.mov

**Expected behavior**
No crash, but... maybe simply move the note back to the top staff when the top staff becomes the bottom staff?

**Additional context**
Also occurs in MS 3.6.2

**Comment by Tantacrul** [comment]
Again @mike-spa @oktophonie - can you let us know if this is something the engraving team can isolate / fix? If not, I'll throw it into genpop. :)

**Comment by mike-spa** [comment]
The crash itself is an easy fix, but there's a bit of general mess with how we check the validity of cross-staff moves and how we handle them in these kind of corner cases. I'm trying to come up with a proper solution, hopefully will be ready soon
