### ISSUE TITLE
[MU4 Issue] MuseScore 4 won't open in Windows 10

### ISSUE THREAD

**Issue by anjwl** [musescore/MuseScore#13899]
**Describe the bug**
MuseScore 4 closes or crashes at start.

**To Reproduce**
1. Open MuseScore 4
2. Wait until Loading window appears
3. See crash

**Expected behavior**
MuseScore shound not crash or close at start.

**Platform information**
 - OS: 64-bit Window 10

**Additional context**
It is similar to https://github.com/musescore/MuseScore/issues/12577.  
But it happens even after adding a firewall exception.
I checked the log file from
C:\Users\<user>\AppData\Local\MuseScore\MuseScore4\logs\dumps and found settings.dat file.
But I can't read it because the file is corrupted.

**Comment by Tantacrul** [comment]
@DmitryArefiev - can you possibly troubleshoot this to see if we can figure out what is going on?

**Comment by DmitryArefiev** [comment]
@anjwl Is it the first time you opened MuseScore4? 
Is it installed version or nightly master build?

Can you remove c:\Users<user>AppData\Local\MuseScore\MuseScore4\ folder and try again? Does it help?

**Comment by anjwl** [comment]
@DmitryArefiev It is my first time I opened MuseScore 4 after installing it.
I installed Musescore 4 from Muse Hub.
I removed the folder and tried to run it again, but the same problem occurred.

**Comment by DmitryArefiev** [comment]
@anjwl Maybe you can try this build https://github.com/musescore/MuseScore/actions/runs/3305790308 ? 
Unpack 7z archive and run MuseScore4.exe file from **bin** folder

**Comment by anjwl** [comment]
The same problem occurred. But I found dmp files from C:\Users\user\AppData\Local\MuseScore\MuseScore4Development\logs\dumps\reports.

**Comment by anjwl** [comment]
@DmitryArefiev The same problem occurred. But I found dmp files from C:\Users\user\AppData\Local\MuseScore\MuseScore4Development\logs\dumps\reports.

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev The same problem occurred. But I found dmp files from C:\Users\user\AppData\Local\MuseScore\MuseScore4Development\logs\dumps\reports.

@anjwl Cool. Can you zip and attach it here please?

**Comment by anjwl** [comment]
@DmitryArefiev this is the log file.
[logs.zip](https://github.com/musescore/MuseScore/files/9851379/logs.zip)

**Comment by DmitryArefiev** [comment]
@anjwl Thanks!

Do you have MuseScore3 installed on your system? (Is it run fine?)

Also, can you check User Account Control Settings? Move slider down and try to run MuseScore4 again?

![Capture](https://user-images.githubusercontent.com/90187801/197585978-b788bc1b-613d-425d-84e6-662e2f8b83c2.PNG)

**Comment by anjwl** [comment]
Yes, I have MuseScore 3 installed and it run fine.
I changed the settings and ran MuseScore 4 again, but it's the same.
This is a new log file.
[logs.zip](https://github.com/musescore/MuseScore/files/9853953/logs.zip)

**Comment by anjwl** [comment]
@DmitryArefiev If the user name is not in English, Does MuseScore 4 crash?

**Comment by DmitryArefiev** [comment]
I don't think so but everything possible.. Does user name has a special symbols and what OS language?

**Comment by anjwl** [comment]
My OS language is Korean and I use Korean for my user name.

**Comment by anjwl** [comment]
@DmitryArefiev My OS language is Korean and I use Korean for my user name.

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev My OS language is Korean and I use Korean for my user name.

Got it. I tried to switch OS to Korean and created a user with Korean letters but was not able to reproduce.. (Windows11)

@Eism Can you check the attached dmp file (logs.zip) and find the reason please?

**Comment by anjwl** [comment]
thanks. It runs fine on my computer.
I have a few questions. @DmitryArefiev 
Is it correct that there is no sound if I set the instrument in MS Basic? 
Is it normal to hear noise when playing with MuseSound? 
How do you test vst?

https://user-images.githubusercontent.com/103595427/198061102-5b7eaa3a-c435-44b3-8aaa-91305dd9aa7b.mp4

**Comment by DmitryArefiev** [comment]
> Is it correct that there is no sound if I set the instrument in MS Basic?

@anjwl No.. The sound should be when you switch to MS Basic. 
Can you reset factory settings in MU (Top menu>Help>Revert to factory settings) and try again?

> Is it normal to hear noise when playing with MuseSound?

Yes, we have a lot of issues with Muse Sounds for now (fixing in progress)

> How do you test vst?

You can use any vst instruments or effects, but it should have VST3 format (**MuseScore 4 supports only VST3** and doesn't support VST2 or others)
 
You can download and install some free instruments from Native Instruments. As I see, they propose Komplete Start with included Kontakt Player https://www.native-instruments.com/en/products/komplete/bundles/komplete-start/ 
It's good to start

**Comment by anjwl** [comment]
> Can you reset factory settings in MU (Top menu>Help>Revert to factory settings) and try again?

@DmitryArefiev  No sound even after factory reset.

And I have installed some vst from Native Instruments but they are not running on MuseScore 4.
Should I add vst in MuseScore 4?

**Comment by DmitryArefiev** [comment]
> Should I add vst in MuseScore 4?

MuseScore should automatically detect VST3 plugins and they should appear in Mixer instrument/effect dropdown:


![Untitled](https://user-images.githubusercontent.com/90187801/198559556-b90733f3-877d-4be6-9fa9-5da8bd285b17.png)

You can use also Preferences>General>Folders>VST3  to setup custom location for VST3, but for NI instruments it should work without that.

**Comment by DmitryArefiev** [comment]
> No sound even after factory reset.

That's strange..

Can you show me how the path for soundfounts looks on your machine?

Here is my:

![Capture](https://user-images.githubusercontent.com/90187801/198561146-88e2bf02-8fea-431e-91d4-2295697a0d81.PNG)

And one more try, if possible can you switch your OS to English and try again please?

**Comment by anjwl** [comment]
@DmitryArefiev After rebooting the computer, vst works fine. 
I moved the file to C:/ and I can hear the sound. Perhaps there was no sound because there were other languages ​​in the path. thank you!
