### ISSUE TITLE
[MU4 Issue] Muse Sounds maps some sounds incorrectly to the wrong instruments

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#13898]
**Describe the bug**
On score creation or importing an old score from another version, some instruments are mapped to the wrong sounds. Specifically:
(instrument -> sound)
Bass Flute -> Flute 1
Oboe -> English Horn
Eb Clarinet -> Bb Clarinet
Bb Clarinet -> Eb Clarinet (Mac)
Bass Clarinet -> Eb Clarinet
Soprano Sax -> Tenor Sax
Chimes (Tubular) -> Mark Tree
Hand Bells -> Cowbell
Bass Drum -> Field Drum
Cimbasso -> MS Basic
Harpsichord -> MS Basic
Upright Piano -> Grand Piano
Hammond Organ -> MS Basic

**To Reproduce**
1. Create a score with any of these instruments
2. See the sound is the wrong sound in the mixer

**Expected behavior**
The instruments should be mapped to the right sounds

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**
Additionally, with [#13894](url), mapping things like the hyperbass flute to flute 1 makes no sense, because no notes in that staff will ever play back because of the range differences

**Comment by erinic04** [comment]
There also isn't an instrument that maps to the bell tree, gong, or sus. cymbal sounds by default

**Comment by GabeS573** [comment]
Bb Clarinet maps to Eb Clarinet on Windows 11 as well (not just Mac).

**Comment by Fristover** [comment]
Some brass instruments like trombone (including bass trombone) and trumpet get mapped to sections (trombones a3 and trumpets for instance) instead of their solo variants, which I think is a better choice and makes more sense.
