### ISSUE TITLE
Electric Guitar with 'Distortion' from MS3 not playing in MS4

### ISSUE THREAD

**Issue by IINekoII** [musescore/MuseScore#13895]
**Describe the bug**
When changing the sound to 'Distorted' using the soundfont in MS3, this sound is ignored in MS4.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/21022311/197386879-a5bfc6ee-484e-46a3-b1ad-465bb2e56cd1.png">

**To Reproduce**
1. Make a Score in MS3 and add an electric Guitar and some other instruments around it with some notation on electric guitar. *Note, I am choosing the distorted sound in the mixer for the the Guitars in MS3 before importing*
2. In MS4, import the score and hopefully that should reproduce it. 

**Expected behavior**
The Electric Guitars playback properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/116476688/197374074-81d200f7-291a-426a-b132-d9665c992981.png)

**Platform information**
 - OS: Windows 10

**Additional context**
The score seen in the picture is completed and heavily edited so I can't list everything I did in the score but I believe this is what is needed to reproduce the error.

**Comment by Tantacrul** [comment]
I have updated the issue to focus on the distortion sound. Thanks!

**Comment by MarcSabatella** [comment]
As far as I know, this is true of *all* non-default sounds assigned via the mixer in MuseScore 3 - they get converted to the default sound for the instrument on import.  It's a similar issue as https://github.com/musescore/MuseScore/issues/13567.  So, same story if I have a piano instrument and change the sound to "tine electric piano", or a score for voices and I change the playback sound to strings.

It would be nice to be able to honor sound selections made via the mixer in MU3 even if the ability to select sounds in the mixer is not yet present in MU4.  Not sure how feasible that is, though.

**Comment by abariska** [comment]
🟢 **FIXED** https://github.com/musescore/MuseScore/issues/13567

**Comment by MarcSabatella** [comment]
I'll have to test this, but from the changes I see in that PR, it doesn't seem like it would fix the problem in this issue.  I can see that the PR in question handles sound changes accomplished by staff texts, by changing them into playing techniques.  But, the issue in *this* report is about sounds that were specified directly in the mixer for the score itself - no staff texts involved at all.  So, for example a score in which there is a single instrument, no staff text at all, and the sound for that instrument was changed directly in the Mixer.

**Comment by abariska** [comment]
@MarcSabatella you're right. This case is a bit different. 
@RomanPudashkin please pay attention to the Marc's comment

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/12314#issuecomment-1266868562

**Comment by MarcSabatella** [comment]
I was probably misleading when I said it was a “similar” issue.  It’s similar indeed - maybe “analogous” - but not identical.

@Tantacrul - I’m kind of guessing this isn’t solvable without adding more capability to the playback framework.  But, if it were to happen, I assume it would need to be integrated with whatever solution is designed to allow people to choose sounds within soundfonts.  Otherwise there just another import problem later.  FWIW, I very much approved of your suggestion from some months ago to have an additional level of pop up menu in the Mixer, after choosing soundfont, to choose sound.

**Comment by Tantacrul** [comment]
Hey Marc. That's exactly it. We are definitely going to allow users to specify sounds from within the soundfont. It is going to be pretty similar to Muse Sounds actually. However, we agreed it would be dangerous to try and fit that in now. We'll likely get it in just after.

In the meantime, we have the new 'Distortion' performance direction as a workaround. In future, we'll also implement a new universal mapping system so users can assign sounds to performance directions themselves. That latter functionality will come a little later.

**Comment by MarcSabatella** [comment]
Great, that will be *extremely* welcome!
