### ISSUE TITLE
[MU4 Issue] (+) Shortcut not working for adding ties

### ISSUE THREAD

**Issue by llui85** [musescore/MuseScore#13893]
**Describe the bug**
Pressing `+` does not add a tied note, but instead sharpens the selected note. It seems that this shortcut has been mistakenly allocated to multiple actions.

**To Reproduce**
1. Attempt to press `+` to tie a note.
2. Observe the sharp applied to the note instead.

**Expected behavior**
Pressing `+` should add a tied note.

**Platform information**
`Linux 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux`

https://user-images.githubusercontent.com/47158068/197372825-5bcd19fd-c16f-49c3-9195-c6a199058c45.mov

**Comment by MarcSabatella** [comment]
This is not a bug; the default tie shortcut has been changed to "T"; "+" is now sharp (along with "-" for flat and "+" for natural).

**Comment by erinic04** [comment]
You need to reset your keyboard shortcuts for this to take effect

**Comment by llui85** [comment]
> This is not a bug; the default tie shortcut has been changed to "T"; "+" is now sharp (along with "-" for flat and "+" for natural).

Ah, thank you. I assumed that the shortcuts would have changed automatically, but obviously not!

**Comment by MarcSabatella** [comment]
> > This is not a bug; the default tie shortcut has been changed to "T"; "+" is now sharp (along with "-" for flat and "+" for natural).
> 
> Ah, thank you. I assumed that the shortcuts would have changed automatically, but obviously not!

If you had old shortcut definitions left over from a previous build, they aren't necessarily cleaned up - you might need to reset to defaults.
