### ISSUE TITLE
[MU4 Issue] Holding down the mixer button causes Musescore to crash

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#13903]
**Describe the bug**
Holding the mixer button for about a second on larger scores causes Musescore to crash

**To Reproduce**
1. Open a larger score
2. Hold the mixer button (F10 by default)
3. Observe the crash

**Expected behavior**
Musescore shouldn't crash

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by Tantacrul** [comment]
What OS are you using? I can't replicate it with the shortcut or the UI.

**Comment by erinic04** [comment]
I'm using Windows. Also, it needs to be a larger score for it to work. I did it reproducibly on a 7 minute marching band full score (with Muse Sounds if that makes a difference)

**Comment by cbjeukendrup** [comment]
@erinic04 It seems that I can only reproduce this issue during playback. Is that the case for you too?

**Comment by erinic04** [comment]
It wasn't the case before, not sure if it is now

**Comment by cbjeukendrup** [comment]
@erinic04 Could you please try if this problem is fixed for you in the builds from #14790? (see https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests for how to download it)

**Comment by erinic04** [comment]
Yeah it's fixed for me (whether holding the button while the score is playing or not)

**Comment by erinic04** [comment]
I tested it on a full orchestra score that's 600 measures long so we good

**Comment by zacjansheski** [comment]
@cbjeukendrup should this still have the label "needs info"?

I have reproduced in the nightly, but it takes quite a bit and I found it it easier to reproduce when the mixer is docked.

https://github.com/musescore/MuseScore/assets/69917893/fccf8d26-468b-4aa0-95e3-be591f60a136
[13903_ZJ.zip](https://github.com/musescore/MuseScore/files/11637064/13903_ZJ.zip)

[Mvt 4_Beethoven__Symphony_No._9__Op._125.zip](https://github.com/musescore/MuseScore/files/11637093/Mvt.4_Beethoven__Symphony_No._9__Op._125.zip)

**Comment by cbjeukendrup** [comment]
I think we have enough info indeed :)

I checked it again, and found indeed that the same crash still happens and the same fix still works.
