### ISSUE TITLE
[MU4 Issue] Bad slide spacing in MS3 score

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13907]
**Describe the bug**

In the attached MS3 score there is an unexpected large space before the slide in measure 3 and slightly too much space for the slides in other measures. Resetting shapes and positions doesn't help.
[slide_spacing.zip](https://github.com/musescore/MuseScore/files/9846353/slide_spacing.zip)

MS3
![ms3_spacing](https://user-images.githubusercontent.com/87246583/197388370-9c1a08b5-97a9-4a68-99bf-4d80f89df3d5.png)

MS4
![ms4_spacing](https://user-images.githubusercontent.com/87246583/197388378-b263d975-814b-4687-b5af-b0f94fe32927.png)

**Expected behavior**

Slide spacing the same as MS3.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289917644, revision: github-musescore-musescore-1ac395a

**Comment by Tantacrul** [comment]
@oktophonie @mike-spa

Let me know your thoughts and feel free to assign to whatever project is most appropriate.
