### ISSUE TITLE
[MU4 Issue] VST3 plugins not available on Linux

### ISSUE THREAD

**Issue by prokoudine** [musescore/MuseScore#13908]
**Describe the bug**

VST3 plugins do not show up in MuseScore 4.0 beta:

Ubuntu 22.04.1 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289917644, revision: github-musescore-musescore-1ac395a

**To Reproduce**

1. Run MuseScore 4 beta
2. Attempt to add any instruments or effects in the Mixer
3. None are listed

**Expected behavior**

All the 20+ effects and instruments from ~/.vst3/, /usr/local/lib/vst3/ and elsewhere should be listed as options to load into mixer channels (yes, they _are_ VST3 plugins, yes, the do load in other programs, yes, they did load in MS4 alpha).

**Comment by llui85** [comment]
VST is not yet supported on Linux due to a separate event loop needing to be implemented.

https://github.com/musescore/MuseScore/issues/11592#issuecomment-1128922059
