### ISSUE TITLE
[MU4 Issue] - instruments present in instruments list #2 are not displayed in the mixer

### ISSUE THREAD

**Issue by Baol77** [musescore/MuseScore#13910]
**Describe the bug**
After opening a MS3 file into MS4, If some instruments are listed in the second file, they are not displayed in the mixer.

**To Reproduce**
1. On the latest version of MS3: Define another instuments.xml and import it as second file in the preferences
3. Add an instrument from that list
4. Open the file with MS4
5. Open the mixer

**Screenshots**
![image](https://user-images.githubusercontent.com/3105101/197390577-49ed882e-8390-40bf-9e7f-692a66d9c691.png)

**Platform information**
 - OS: OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289914935, revision: github-musescore-musescore-abc123456

**Comment by abariska** [comment]
As was discussed with @Tantacrul and @RomanPudashkin there was a decision to remove an ability to choose instrument lists anymore. Deleted in https://github.com/musescore/MuseScore/pull/13978 
🟢 The issue is not actual

**Comment by shoogle** [comment]
@Baol77, please let us know which instruments you need and we will try to add them to the default list for you. You can attach your custom instruments.xml to a comment here if that's easier.

**Comment by Baol77** [comment]
Hello,
I was using the asian gong
https://m.youtube.com/watch?v=DTTtld-gkVw
Gesendet von Yahoo Mail auf Android 
 
  Am Mo., Okt. 24, 2022 at 20:28 schrieb Peter ***@***.***>:   


@Baol77, please let us know which instruments you need and we will try to add them to the default list for you. You can attach your custom instruments.xml to a comment here if that's easier.

**Comment by Reloup38** [comment]
@abariska does that mean we will not have the ability to chose from custom instrument lists anymore ? that would be a shame, because outside of adding more instruments, custom instrument lists allows us to modify existing instruments (for exemple, if you have an organ soundfont and you want your instrument to have many articulations so that you can set different stops at different points in your score), which is a thing you can't do at all without editing instrument lists.

**Comment by Tantacrul** [comment]
We're going to be building systems that allow users to modify things like this (especially sounds and articulations) over the next few releases. The custom instrument list feature conflicts with our new playback system too much for it to be honoured in V4.

There have been a few instances where we've had to do this, unfortunately. We'll be adding much more configurability to MS4 over the next few releases.

**Comment by donbox** [comment]
@Tantacrul - it's been a bit over a year since you last commented.

Any update on when to expect this to come back?

Alternatively, is there a mitigation?

For example the ability to copy/paste an entire staff (or instrument) would go a long way at least for my use case.

**Comment by donbox** [comment]
@Tantacrul - Even "Duplicate Staff" would help as a mitigation.

**Comment by Tantacrul** [comment]
@donbox 

When something is logged as a ticket, it is prioritised against other issues. Tagging me to complain wastes my time and does nothing to advance the issue you want solved. Please only offer context or help when commenting on an issues and strictly refrain from badgering and rushing.

**Comment by Tantacrul** [comment]
We are preparing the ability to include articulation mapping, MIDI mapping and other kinds of sound customisation. These have been planned and will be implemented, one by one.
