### ISSUE TITLE
MuseSampler: assertion failure "Ending previous ranged articulation, but no 'end ranged' call occurred!"

### ISSUE THREAD

**Issue by diedeno** [musescore/MuseScore#13915]
**Describe the bug**
When using Muse Sounds, MS4 sometimes waits for user input

_Ending previous ranged articulation, but no 'end ranged' call occurred!
Assertion 'false' failed (DEBUG)
  in file TrackMap.cpp, line 116
  function: bool staffpad::musesampler::TrackMap::EndRanged(int, ms_NoteArticulation)
  with message: Ending empty ranged articulation!

Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort: F
14:25:57.169 | ERROR | 139677449787136 | MuseSamplerSequencer | addNoteEvent: Unable to add ranged articulation range end_

If MS4 is started by clicking on Appimage, then, after a while, the systemd.journald goes 100% CPU.
If started via cmd line, one can just enter Ignore or Ignore Forever to continue.
Until this is done, nothing works anymore.

**To Reproduce**

**Expected behavior**
Should not ask for user input

**Screenshots**

**Platform information**
 - OS:  Ubuntu 20.4 LTS

**Comment by Tantacrul** [comment]
@cbjeukendrup - could you interpret this for me? 😄

**Comment by MarcSabatella** [comment]
I don't understand the conditions that lead to this, but I can confirm that at at various point while using the beta with Muse Sounds, the program seems to freeze, and if I check the console window, I see the error messages shown above, and it's obviously waiting for me to respond by choosing one of the list options (ignore / abort etc).

So the basic symptom is, the program stops responding for no obvious reason.  Which is obviously serious.  But I don't know the specific steps to trigger the problem.

**Comment by cbjeukendrup** [comment]
I do see a lot of `Ending previous ranged articulation, but no 'end ranged' call occurred!` messages printed to stderr for some scores; either this is a problem inside MuseSampler, or MuseScore is using it incorrectly. 

However, I don't experience that I need to enter something in the console. That's probably Linux specific behaviour.

Also interesting that these assertion failures make it into a release build...

Anyway, I think this should really be fixed before release, or at least that strange behaviour on Linux must be fixed/disabled.

**Comment by Tantacrul** [comment]
P1? P2?

**Comment by iamtesch** [comment]
This should be resolved (as of a while ago!). Sorry for not following up sooner; let us know if this is still an issue!
