### ISSUE TITLE
Playback with Musesounds

### ISSUE THREAD

**Issue by aceplayermusic** [musescore/MuseScore#13911]
When applying muse sounds, the playback struggles a lot, making distorted cracking sounds throughout playing, and making it impossible to work, especially with big scores.

**Comment by Tantacrul** [comment]
A few questions:

- What OS?
- Have you set the buffer to 2048 **(preferences > I/O)**

**Comment by Tantacrul** [comment]
Since this is a well known issue with existing tickets, I'm going to close it for now

**Comment by aceplayermusic** [comment]
Hi,
Windows. And no I haven't done that, it seems to be working fine now that
ive increased the buffer. Apologies for the false alarm, and thank you so
much.

Ace.

**Comment by Tantacrul** [comment]
OK that's great. Thanks!
