### ISSUE TITLE
[MU4 Issue] Clarinet in Bb playback through MuseSounds incomplete

### ISSUE THREAD

**Issue by gremghost** [musescore/MuseScore#13916]
**Describe the bug**
When using MuseSounds, Clarinet in Bb cannot go above an fourth octave E, even though it's in a player's range.

**To Reproduce**
1. Open MuseScore 4.
2. Write a fourth octave F (or F#) in a Clarinet in Bb part.
3. No playback occurs unless the note goes to an E or lower.

**Expected behavior**
The note should have playback. It's in a very high range for a clarinet, but still very much playable.

**Screenshots**
![image](https://user-images.githubusercontent.com/116465388/197393120-3887b9cd-1b99-4810-8b06-9b1f210e3f5a.png)

**Platform information**
 - OS: Windows 10

**Additional context**
With MS Basic or using an earlier version of MuseScore, it works as expected with proper playback on a note in the range between the fourth octave E and the fifth octave C overtone (including chromatics).

**Comment by cbjeukendrup** [comment]
Maybe related to #13894?

**Comment by erinic04** [comment]
Yes it is related to that issue; it's just a more general way of saying it rather than specifically focusing on clarinet.

**Comment by erinic04** [comment]
I could open a multitude of issues for different instruments specifically, but I just made one general one.

**Comment by cbjeukendrup** [comment]
I propose we close this issue then, in favour of the general one (#13894).

@Tantacrul I've upgraded the priority of that one to match this issue's priority.
