### ISSUE TITLE
[MU4 Issue] - pizz. / arco notations are not taken into account when imported from MS3

### ISSUE THREAD

**Issue by Baol77** [musescore/MuseScore#13912]
**Describe the bug**
The text notation "pizz" and "arco" are not taken into account after having imported a MS3 file into MS4.

**To Reproduce**
1. Create a MS3 score for a string instrument (ex. violin) and add a "pizz." notation
2. Open the score in MS4 and play it

**Expected behavior**
The pizz / arco sound should work for the string instrument

**Platform information**
 - OS: OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289914935, revision: github-musescore-musescore-abc123456

**Comment by MarcSabatella** [comment]
This was already fixed a few days ago, it just seems not present in the beta build - see https://github.com/musescore/MuseScore/issues/13567.  I haven't tested the fix yet, and don't know if it works on Muse Sounds

Meanwhile, the workaround is to delete and re-add the markings.
