### ISSUE TITLE
[MU4 Issue] Typo in Score Settings

### ISSUE THREAD

**Issue by prokoudine** [musescore/MuseScore#13918]
The score settings dialog has a field called "Worktitle". That doesn't look like regular English. Shouldn't it be "Work Title" or some such thing?

**Comment by Tantacrul** [comment]
@HemantAntony - can you do us a favour! **Work title** is correct!

**Comment by HemantAntony** [comment]
Seems like a really easy fix :)

**Comment by HemantAntony** [comment]
@Tantacrul check #13924
