### ISSUE TITLE
[MU4 Issue] Musescore UI not in System Default language

### ISSUE THREAD

**Issue by teetow** [musescore/MuseScore#13926]
**Describe the bug**
Musescore shows the incorrect language by default, not respecting its own setting "System Default."

**To Reproduce**
1. Go to Edit > Preferences
2. Verify "Language" set to "System Default" (English in my case)
3. Note that the Musecore UI is in Swedish, which is not my selected Display Language (see screenshots)
4. Silently wonder why every single multiplatform app gets this wrong

**Expected behavior**
Musescore UI being in English, as per its Language setting

**Screenshots**

Windows Display Language setting

![image](https://user-images.githubusercontent.com/183582/197399876-fa149eff-80b8-4f96-b31a-0fafb6bb22b3.png)

**Platform information**
 - OS: Windows 10

**Additional context**
As mentioned, this is a common screwup in applications where devs mistakenly interpret User Regional formatting settings (stuff like date and time formatting) to mean System Language. Please be one of the good guys here.

**Comment by cbjeukendrup** [comment]
I'm afraid this might be a Qt problem. We get the system language from Qt, using [`QLocale::system().uiLanguages()`](https://doc.qt.io/qt-5/qlocale.html#uiLanguages). 
Although Qt intends that this is the correct way to retrieve the display language, we might try another way.

**Comment by teetow** [comment]
Hmm. I whipped up a quick test app (in PyQt5, granted) and it gave me the following values for the settings I could scrounge up from various SO answers:

![image](https://user-images.githubusercontent.com/183582/197405163-b8c85897-ebf7-46b0-9425-586d3344c717.png)

So, the only place where Swedish shows up is indeed in `QLocale::system()::uiLanguages()`. Now, I can't really make heads or tails of all the stuff in `languageService.cpp` but I'm seeing references to `languageCode` which makes me believe that (at least on my machine) the _last_ code in that list gets picked as the assumed system language.

Good news is, you have two other methods that (again, on my machine) yields English -- `QLocale.system().language()` and `QLocale.system().name()`. So maybe there's some hope.

**Comment by Tantacrul** [comment]
@cbjeukendrup - can you prioritise (4.x, post-beta, release etc.)? If we think it's an easy, quick fix, then release would be appropriate.

**Comment by cbjeukendrup** [comment]
@teetow There's a small chance that this is fixed by #14701. Could you please try the builds from that PR?

**Comment by teetow** [comment]
> @teetow There's a small chance that this is fixed by #14701. Could you please try the builds from that PR?

I did, and the issue is no longer present. 

For what it's worth, it's also not present in the build currently on MuseHub (info pasted below). 

![image](https://user-images.githubusercontent.com/183582/203815166-5543546a-0081-47c1-b4e1-4ab403c43205.png)
