### ISSUE TITLE
[MUSE HUB] Suggestion - Download progress in tray tooltip

### ISSUE THREAD

**Issue by deltz025** [musescore/MuseScore#13925]
It would be nice to see the progress of downloads without having to pull up the main Muse Hub interface. Ideally, some information like download speed, remaining size, and/or estimated time remaining would show up in a tooltip when one hovers over the tray icon (similar to some download managers and p2p clients). 
![image](https://user-images.githubusercontent.com/49649081/197399608-31de8b30-ac27-42fb-ba6d-29fe4200bee2.png)

**Comment by Tantacrul** [comment]
Nice idea! It won't be in the upcoming release but we'll look into it soon.
