### ISSUE TITLE
Muse Sounds struggles when 'play' is first pressed

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#13927]
**Describe the bug**
I have noticed just over the last day or two that playback is struggling when you press play:

- My buffer is set to 2048 (the problem is the same regardless of the buffer)
- Some instruments don't sound until around a second after you press play, and it feels like they are 'catching up'
- There is a lag after you press play which feels worse than before
- Scores which used to start fine now have trouble (our internal Star Wars score is a very good example of this)

**To Reproduce**
1. Open this file [this file](https://www.dropbox.com/s/gxgm53nnp8iyh07/Playback_Ident_01.mscz?dl=0)
2. Play the start of the score and note how it take almost until measure 2 before all the instruments can be heard
3. Click on measure 8, press play and you'll hear the same thing

**Recording**

https://user-images.githubusercontent.com/21022311/197404440-52100aa3-adf4-4c22-a225-912f3c3a9da2.mov

**Platform information**
 - Tested on MacOS

**Comment by llui85** [comment]
I can reproduce this on Linux (Debian).

**Comment by Tantacrul** [comment]
Interestingly, I am **not** having this same problem on Windows. Others welcome to give input about whether they are experiencing it, and if so, on what OS (with specs)

**Comment by cbjeukendrup** [comment]
I think I'm having this issue almost always when I press play. The first note always sounds laggy/softer/not at all, especially with faster notes, even in a single-instrument score. It's clearly audible in this example; the first note seems to miss its attack:

https://user-images.githubusercontent.com/48658420/197542282-98dd3220-4c4c-4fde-a967-ad4ee0cd4ab9.mov

**Comment by ModernMozart** [comment]
macOS 11.6, M1 Macbook Air, 16GB RAM. I can reproduce

**Comment by MarcSabatella** [comment]
I have similar struggle to get underway then playback mostly fine after that on Linux, two different systems (both Chromebooks, which shouldn't matter).  One is 8th gen m3 / 8 GB RAM, the other 11th gen i5 / 16  GB RAM, both the lower-power fanless versions but the 11th gen i5 system in general is quite fast.  Oddly, the i5 system struggles more in this particular respect though.  Not sure if that's just because I'm asking more of it though.  I don't have room on the m3 system for much beyond choir and harp.

**Comment by MarcSabatella** [comment]
Hmm, now it's working much better on the i5 system, same scores that were causing problems earlier.  I did just reboot.  Could be some background process leftover from having run Muse Hub was getting in the way.

**Comment by Tantacrul** [comment]
Seems much better for me now.
