### ISSUE TITLE
[MU4 Issue] Assertion Error when selecting Bass Trombone from Muse Sounds

### ISSUE THREAD

**Issue by Gobbel2000** [musescore/MuseScore#13922]
When selecting Bass Trombone from the Muse Sounds Brass package in the Mixer, the following error is printed to the console:
```
Assertion 'intervalSampleIndex >= 0' failed (DEBUG)
  in file SfzParser.cpp, line 582
  function: staffpad::vi::SfzParameterMap staffpad::vi::SfzParser::createRegions(staffpad::vi::SfzRegionList&)
Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:
```
This causes playback to break and the mixer UI becomes unresponsive. By entering `F` into the console to ignore this error forever, everything seems to work normally again. 

**To Reproduce**
1. Open a new score with Bass Clef template
2. Enter some notes
3. In the mixer panel change the sound to Muse Sounds > Muse Brass > Bass Trombone

**Platform information**
 - OS: Arch Linux
 - Musescore 4 beta release AppImage

**Comment by cbjeukendrup** [comment]
Interesting, here we see that same strange behaviour with assertion failures as in #13915. Apart from the fact that the error itself should be fixed, the user shouldn't need to notice assertion failures in a release build.

**Comment by 4gboframram** [comment]
Also seems to happen for me with Flute 1

**Comment by Gobbel2000** [comment]
This one too is now fixed with the recent beta releases of muse sounds and musescore.
