### ISSUE TITLE
Crash when clicking anywhere on score or starting playback (Razer USB Sound Card)

### ISSUE THREAD

**Issue by drewwjs** [musescore/MuseScore#13939]
**Describe the bug**
Whenever I click anywhere on the score (not including the ribbon at the top or the workspace panel on the left), the loading cursor appears and the program crashes a few seconds later.

**To Reproduce**
1. Open MuseScore 4 beta from Muse Hub.
2. Create a new score or open an existing .mscz file.
3. Click anywhere on the score or press the start playback button.
4. Follow Windows program crash prompts, which force close the program.

**Expected behavior**
MU4 should not crash whenever the score is moved, clicked on, altered or played back.

**Screenshots**

https://user-images.githubusercontent.com/116519099/197415455-7f2dde5d-a0fc-4f73-9433-007ee728d7da.mp4

**Platform information**
 - OS: Windows 10 x64
 - MU4 Version: MuseScore 4.0.0.222931342

**Comment by Tantacrul** [comment]
@DmitryArefiev - can you try to get more info about this crash?

**Comment by Tantacrul** [comment]
Basically to get to the bottom, we need **logs, sound card details, dumps**

**Comment by DmitryArefiev** [comment]
Hi @drewwjs , can you get **logs** folder from c:\Users\dima\AppData\Local\MuseScore\MuseScore4\ zip it and attach here please?

Also, what sound card do you have installed in Windows? 

And can you make a screenshot of I/O tab in MuseScore preferences (Top menu>Edit>Preferences>I/O)?

Thanks!

**Comment by drewwjs** [comment]
Hello, apologies for the late response.

Here is my logs folder:
[logs.zip](https://github.com/musescore/MuseScore/files/9894553/logs.zip)

I am using a Razer USB Sound Card.

And here is my I/O tab:
![MU4 IO tab](https://user-images.githubusercontent.com/116519099/198851360-6661c858-d0e4-4824-8e94-aab21271cd7d.png)

Please let me know if there's any other information you need me to provide. Thank you!

**Comment by DmitryArefiev** [comment]
@vpereverzev Another issue about sound cards on Windows.. (maybe logs can help to define problem)

@drewwjs Does crash occurs when you switch OS sound settings to internal sound card (probably Realtek)?
Or you can select Realtek Audio directly in MuseScore, just click on dropdown in Preferences>I/O>Audio device.

**Comment by drewwjs** [comment]
The issue went away once I switched to Realtek audio, but I didn't get any sound on any output devices except for THX Spatial Audio, where the sound works fine.

**Comment by DmitryArefiev** [comment]
@drewwjs Can you try again please on this build? https://github.com/musescore/MuseScore/pull/14612#issuecomment-1321835198

Does it help with Razer USB Sound Card?

Thanks! 

(the build from the link above is installer)

**Comment by Tantacrul** [comment]
Here they are just to avoid confusion: 
WIN - https://github.com/musescore/MuseScore/suites/9417801459/artifacts/444885402
MAC- https://github.com/musescore/MuseScore/suites/9417818476/artifacts/444895098

**Comment by drewwjs** [comment]
The new build works fine with my Razer USB Sound Card, but now all other audio outputs are giving me no sound, except for THX Spatial Audio, which is playing everything but very sped up and higher pitched. But that sounds like a different issue :)

**Comment by Tantacrul** [comment]
However, since the Razor issue is solved, I'm going to close this.

It would be useful to post any new audio issues with other outputs separately (with details about what they are, etc.).

Thanks very much!
