### ISSUE TITLE
[MU4 Issue] Musesounds Wood Block (not metronome) playback not working

### ISSUE THREAD

**Issue by Just-your-average-Github-user** [musescore/MuseScore#13930]
**Describe the bug**
The Muse Sounds playback for wood blocks isn't working. 

**To Reproduce**
1. Create a new score with wood block as instrument. 
2. Add a few notes. 
3. Open the mixer and set the wood blocks playback soundfont to Muse Sounds wood blocks. 
4. Start playback. 
5. See error. 

**Expected behavior**
The playback works. 

**Screenshots**

**Platform information**
 - OS: Windows 10

**Additional context**

**Comment by Tantacrul** [comment]
We're considering just locking the metronome to MS basic for now. @vpereverzev - I do also wonder whether we should actually package a metronome sound with MuseScore 4 ourselves that uses neither MS basic or Muse Sounds. We have a specific (much more appropriate) sound available. Let me know.

I worry that defaulting the metronome to MS Basic (when Muse Sounds is being used everywhere else) will cause more unnecessary performance problems.

**Comment by Just-your-average-Github-user** [comment]
Just checking if you understood the issue: I am referring to the wood block instrument, not to the metronome. I am aware of the fact that the metronome is not a part of Muse Sounds, but the wood block is.

**Comment by Tantacrul** [comment]
In fact, I did not realise this is what you meant! Thanks!

**Comment by Just-your-average-Github-user** [comment]
You're welcome.

**Comment by cbjeukendrup** [comment]
The woodblocks seem to work now for me, albeit a little bit quiet. @Just-your-average-Github-user could you please try if it's fixed for you too? (after making sure the latest Muse Sounds are installed by quitting and reopening the Muse Hub)

**Comment by Just-your-average-Github-user** [comment]
Yes, it does work now.
