### ISSUE TITLE
[MU4 Issue] (Fedora) MuseSampler* Errors: Unable to open MuseSampler library

### ISSUE THREAD

**Issue by 0x656b694d** [musescore/MuseScore#13935]
**Describe the bug**

Musescore4 won't work with `libMuseSamplerCoreLib.so`.

**To Reproduce**
1. Start muse-hub service;
2. Start `./MuseScore-4.0.0.3289917644-x86_64.AppImage`;
3. Open a score;
4. See only MS Basic is available in the mixer.

**Installation**

1. `ar x muse_hub.deb && tar xf data.tar.xz`;
2. `sudo mv opt/muse-hub /opt`;
3. Run `sudo /opt/muse-hub/Muse.Service`;
4. Run `/opt/muse-hub/Muse.Client.Linux`;
5. Get all sound libraries.

**Expected behavior**
I'd expect Muse sound to be available.

**Platform information**
 - OS: Fedora 36.

**Additional context**
Logs
```
15:11:01.882 | ERROR | main_thread | MuseSamplerLibHandler | MuseSamplerLibHandler: Unable to open MuseSampler library, path: libMuseSamplerCoreLib.so
15:11:01.882 | ERROR | main_thread | MuseSamplerResolver | MuseSamplerResolver: Incompatible MuseSampler library; ignoring
```

**Workaround**

`LD_LIBRARY_PATH=/usr/lib ./MuseScore-4.0.0.3289917644-x86_64.AppImage`

**Comment by llui85** [comment]
That's odd, it works on Debian (incl. running with the AppImage) for me. The custom installation steps you've used don't mention extracting `libMuseSamplerCoreLib.so` to `/usr/lib` - does the library actually exist at that path?

**Comment by 0x656b694d** [comment]
Hm, `libMuseSamplerCoreLib.so` is not part of the installation bundle, apparently. It gets installed by the hub, I suppose.
Anyway, I cannot reproduce the problem anymore after having tried to clean up and redo the installation.

**Comment by Batwam** [comment]
I have looked into the MuseHub deb file and there is no `libMuseSamplerCoreLib.so` file in it.

I am getting the error with the flatpak `Unable to open MuseSampler library, path: libMuseSamplerCoreLib.so`. However, it works with the appImage version so I suspect that this is an issue with the Flatpak.

**Comment by frispete** [comment]
`libMuseSamplerCoreLib.so` is installed by `muse-hub`, but that doesn't respect a differing OS library path on 64 bit systems. Another possible work around is:
```
ln -s /usr/lib/libMuseSamplerCoreLib.so /usr/lib64/libMuseSamplerCoreLib.so
```
Not sure about the library handling of appimages and flatpaks, though.

I've filed a related note already here: https://musehub.zendesk.com/hc/en-gb/community/posts/8476678878109-Make-musesampler-work-on-openSUSE-Tumbleweed

**Comment by cbjeukendrup** [comment]
The issue with `/usr/lib/` vs `/usr/lib64/` has also been logged in #15562.

**Comment by Batwam** [comment]
For info, I just tried to link `libMuseSamplerCoreLib.so` in `lib64` to see if that would help for the Flatpak not loading MuseSounds but it still doesn't work.

**Comment by frispete** [comment]
> For info, I just tried to link `libMuseSamplerCoreLib.so` in `lib64` to see if that would help for the Flatpak not loading MuseSounds but it still doesn't work.

No, that cannot work. Flatpak manages applications in isolated [sandboxes](https://docs.flatpak.org/en/latest/basic-concepts.html). Therefore, the application builder needs to cope with any dependencies in a Flatpak conformant way.

**Comment by Batwam** [comment]
Yeah, that makes sense. 

Sorry for the sightly unrelated question but does anyone know how I can contact the Flatpak maintainer to investigate this issue? I have searched and asked around but can't seem to find how as flathub links back to here.
