### ISSUE TITLE
[MU4 Issue] linux syslog being spammed by appimage

### ISSUE THREAD

**Issue by Xtarich** [musescore/MuseScore#13946]
**Describe the bug**
The beta 4.0 appimage is spamming /var/log/appimage
**For example, it consumed > 100GB in a couple of hours. disk full!**
Using the beta is unusable. It's slow, freezes and crashes.

**To Reproduce**
1. Install musehub and musesounds
3. Launch appimage
4. load a score (clicked on a recent file)
5. Close the app. The log file is still being written.

**Expected behavior**
Not spam log.

### During and after closing app:

xavier@coffee:/var/log$ ps -ef | grep muse
root         851       1  0 Oct23 ?        00:00:00 /bin/sh /usr/bin/muse-hub-service
root         853     851  0 Oct23 ?        00:01:17 /opt/muse-hub/Muse.Service
xavier@coffee:/var/log$ 

I guess one of these is writing to the log

**Screenshots**
![image](https://user-images.githubusercontent.com/105360640/197422812-4f6e2813-ec1c-4f84-bc2a-2906edb1b450.png)

ct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: message repeated 27 times: [ Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:]
Oct 24 10:14:27 coffee gnome-shell[4403]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55a20f677ba0] is on because it needs an allocation.
Oct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:
Oct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: message repeated 27 times: [ Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:]
Oct 24 10:14:27 coffee gnome-shell[4403]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55a211ce6750] is on because it needs an allocation.
Oct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:
Oct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: message repeated 27 times: [ Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:]
Oct 24 10:14:27 coffee gnome-shell[4403]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55a20f6774a0] is on because it needs an allocation.
Oct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:
Oct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: message repeated 10407 times: [ Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:]
Oct 24 10:14:27 coffee dbus-daemon[4158]: [session uid=1000 pid=4158] Successfully activated service 'org.gnome.NautilusPreviewer'
Oct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:
Oct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: message repeated 6243 times: [ Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:]
Oct 24 10:14:27 coffee gnome-shell[4403]: DING: Detected async api for thumbnails
Oct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:
Oct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: message repeated 2827 times: [ Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:]
Oct 24 10:14:27 coffee gnome-shell[4403]: DING: GNOME nautilus 42.2
Oct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:
Oct 24 10:14:27 coffee org.gnome.ArchiveManager1[19783]: message repeated 979 times: [ Press (I)gnore / Ignore (F)orever / Ignore (A)ll / (D)ebug / A(b)ort:]

**Platform information**
Ubuntu 22.04

**Additional context**
Muse Sounds are installed and being used. 
Muse sounds are set to default playback.
This issue did not occur prior to the beta.

**Comment by Xtarich** [comment]
not musescore,something is wrong with appimages on my system, getting this spam for all of them

**Comment by Xtarich** [comment]
sorry, this is muse score. The Process ID in the log messages is the muse score appimage. 
The logs go beserk when opening a file in musescore.

**Comment by gampnico** [comment]
This also occurred with me on Ubuntu 20.04 when running the AppImage whilst Muse Hub was doing something (e.g. when selecting a MuseSounds instrument via the mixer, or downloading an instrument pack). As long as Muse.Service was running, the process `mscore4portable` didn't end when exiting the GUI, but instead syslog was flooded with (mostly |DEBUG|) messages - writing ~500MB/min.

The bug didn't occur if Muse.Service was stopped or when using MSBasic playback - the process ended normally.

**Comment by Xtarich** [comment]
@Tantacrul yes the issue is fixed thanks!
