### ISSUE TITLE
[MU4 Issue] MuseSounds causes MuseScore CPU% to skyrocket to over 1000%

### ISSUE THREAD

**Issue by DavidMcCaulley** [musescore/MuseScore#13949]
**Describe the bug**
Upon using MuseSounds in an orchestral context where there are a lot of different instances of MuseSounds instruments, the CPU% that MuseScore takes always shoots up well into the hundreds, even sometimes past 1000%. In the attached video, you can see how MuseScore stays at around 25% when idle, but as soon as play is hit, the CPU% spikes. It's worth mentioning that this doesn't just have to do with playback, but at the end of the video, just selecting a note (or even a rest in some cases) caused it to jump over 400% (after it had gone back down to idle).

**To Reproduce**
1. Open any score with a decent amount of MuseSounds instruments
2. Press play (or click on a note or rest) and observe the CPU stats

**Expected behavior**
I'm not sure MuseScore should be using that much CPU%. With MS Basic, the CPU% never strays above 100%.

**Video Example**

https://user-images.githubusercontent.com/31858876/197425416-b19e6ed9-7387-4819-8905-c4efab12c343.mp4

**Platform information**
Tested on macOS 12.0.1 (also worth mentioning I use a 2.3 GHz 8-Core Intel Core i9 and have 64GB of memory)

**Additional context**
I have a hunch this is related to #13927. I notice that the problem of MuseScore struggling to start playback seems to occur _while_ the CPU% is at a very high number. Even more, MuseScore starts playback just fine after waiting for the CPU% to return to normal. Since even clicking on notes or rests causes this spike, if I click anywhere in the score, wait for the CPU% to drop back down, and _then_ hit play, the playback starts without a hitch.

It's also worth mentioning, that yes, the _user_ percentage doesn't go past 31%, but it seems to pretty quickly heat up my laptop to the point where the fans are running at full speed within seconds of hitting play.

**Comment by pawelulita** [comment]
I can also reproduce this issue using the "Searching Four" sample song, available in Muse Hub. For example, by just playing Violins 1, I'm able to make MuseScore max out my 8 core, 16 thread CPU. The screenshot shows 1381.6% CPU usage.

<img width="2048" alt="Screenshot 2022-10-24 at 20 39 09" src="https://user-images.githubusercontent.com/5839781/197601806-4c722abe-5278-410a-a22b-4534049f893b.png">

**Comment by DavidMcCaulley** [comment]
Tested this a little more on the latest nightly with the same test score I recorded above. The problem actually seems better _during_ playback. The CPU% doesn't go up to 1000% during playback anymore, though it still hovers around 300%. It does  still go up towards 1000% when playing and stopping playback a few times in quick succession though.

**Comment by RomanPudashkin** [comment]
@DavidMcCaulley could you please check the CPU usage with 4.1.1? It should be better. Thanks!

**Comment by DavidMcCaulley** [comment]
Just tested it with a decently complex orchestral score with MuseSounds. It's definitely nowhere near the 1000% usages that earlier builds reached, but still reaching between 150% - 200% pretty consistently. The laptop still heats up a decent bit, but if this is as optimized as MuseSounds can get for now, I can certainly live with it. Thanks to the development team for all the great work on MuseScore 4!
