### ISSUE TITLE
[MU4 Issue] Version should change to no longer say abc123456

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#13943]
**Describe the bug**
Beta version about dialog gives no clue that you're running the Beta version and just says 4.0.0 revision abc123456 like all the development builds.

**To Reproduce**
1. Install Beta using Muse Hub & launch
2. Dismiss splash screens and go to Help | About
3. Observe info about version

**Expected behavior**
Should say 4.0.0 Beta, ideally with a meaningful revision number based on the build number or git commit SHA

**Screenshots**

**Platform information**
Windows 10

**Additional context**

**Comment by Eism** [comment]
Fixed generating of revision number in #14082. 

Yes, it would be useful to add Beta to the title, but it doesn't make sense right now since we've already released Beta. 
@Tantacrul we need to move this to 4.x.

**Comment by Tantacrul** [comment]
If we're fixing this for the release, then I think the issue can be closed.

**Comment by DmitryArefiev** [comment]
Fixed in #14082
