### ISSUE TITLE
[MU4 Issue] Muse Sounds not loading into MS4 even after MS4 and MuseHub uninstall and reinstall

### ISSUE THREAD

**Issue by AwsomeTyper** [musescore/MuseScore#13952]
Muse Sounds not loading into MS4 even after MS4 and MuseHub uninstall and reinstall 

**Platform information**
 - OS: Windows 11

**Workaround**

1. Uninstall Musescore 4 and MuseHub
2. Uninstall previously downloaded Muse Sounds
- Win+R to open Run
- Then type %ProgramData%
- Find the MuseHub folder and Shift+Delete to delete the folder permanently.
3. Delete the MuseHub installer from the download folder (no idea if this is necessary but I did it anyways)
4. Restart the computer
5. Reinstall MuseHub
6. Install MuseScore 4 and Muse Sounds through the MuseHub.

**Additional context**
- Previous MS4 nightlies and Alphas were installed on my machine
- Installed Muse Effects worked from the beginning, only the Muse Sounds were not showing up
- Going to View>Playback Setup before workaround MS4 gives two options. 1 "MuseScore Basic is Active" and 2 "Muse Sounds is Inactive". However, the second option is grayed out and you are unable to activate it
- I also installed literally all of the MuseSounds before the workaround and opened MS4 before they all finished downloading (a few of them had finished). When they didn't show up I waited until they had all downloaded and when they still did not appear in MS4 I tried several things and eventually came up with the workaround where the issue seems to be resolved and Muse Sounds were properly loaded into MS4
- I also posted this on https://musescore.org/en/node/336003#comment-1146100

This is also my first GitHub post so sorry for any mistakes in formatting.

**Comment by Just-your-average-Github-user** [comment]
Unfortunately, after doing your steps, you have Musescore 4.0.0 installed. If you try to update it, delete the older version and then install Musesounds, 4.27.0 still doesn't give you MuseSounds.

**Comment by cbjeukendrup** [comment]
You should not have version 4.27. That version should not be offered. It is an old build (from before Muse Sounds was enabled) that was used to test MuseScore's auto-update mechanism.

@Eism Do you know why people are still getting offered this build? It seems like it happens mostly to people on Windows, but I'm not sure about that. I believe I haven't experienced this myself.

**Comment by mccoydtromb** [comment]
Has anyone found a quicker workaround than uninstalling and deleting everything? Isn't there a direct to a folder, or a settings file that can be rebuilt?

**Comment by cbjeukendrup** [comment]
Uninstalling MuseScore 4.27 itself should be enough. For me, it's installed in `C:\Program Files`.

**Comment by mccoydtromb** [comment]
Unfortunately not, MuseSounds still not picked up by MuseScore 4.0.0 after uninstalling 4.27

**Comment by Mark-WWW** [comment]
AwesomeTyper Many thanks for your suggestion. It has solved the problem for me, and I am now able to hear MuseSounds in all its glory. Yippee!

Hard to know why deleting the MuseHub folder from %ProgramData% is necessary and just deleting and re-installing MuseHub and MS4 wasn't sufficient, but that was the case for me too.

Also posted to https://github.com/musescore/MuseScore/issues/13934

Thanks again.

**Comment by AwsomeTyper** [comment]
> Has anyone found a quicker workaround than uninstalling and deleting everything? Isn't there a direct to a folder, or a settings file that can be rebuilt?

Not that I know of. It seems to be a relatively uncommon issue. Though it seems that everyone that has this issue had other versions of MS4 before the Beta and MuseHub were released. I will do some more testing on a Windows VM later today to try and replicate this issue and find a quicker workaround

**Comment by Tantacrul** [comment]
@AwsomeTyper - so are you satisfied that this issue can be closed now? Not 100% sure myself.

**Comment by Tantacrul** [comment]
I'll close for now and if that is in error, just let me know and I'll reopen.

**Comment by AwsomeTyper** [comment]
@Tantacrul - It seems that this is still an issue, I just found a workaround to get Muse Sounds to work when an MS4 and Musehub uninstall and reinstall does not work. I think the issue might stem from previous MS4 builds but I'll have to find out for sure when I do more testing later today. But for now, yes close this issue and I'll post my findings on #13934

**Comment by ThePython10110** [comment]
Same problem, same solution (Windows 10)
