### ISSUE TITLE
[Muse Hub]Can't open Muse Hub on Ubuntu 22.10

### ISSUE THREAD

**Issue by yuki0035** [musescore/MuseScore#13955]
**Describe the bug**
Cannot open Muse Hub after installing it from the .deb package.Nothing happen after clicking on the Muse Hub icon.

**Platform information**
 Ubuntu 22.10 ''Kinetic Kudu''

**Comment by llui85** [comment]
Duplicate of #13909

**Comment by Tantacrul** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/13909
