### ISSUE TITLE
[Muse Hub Issue] EN-US uses British spellings

### ISSUE THREAD

**Issue by GabeS573** [musescore/MuseScore#13953]
Issue: Even when "English (United States)" is selected as the language for Muse Hub, British spellings are still used.

I have found two spelling issues so far:

- In the Settings page, "color" is spelled as "colour":
![image](https://user-images.githubusercontent.com/91428485/197436774-8a4a2690-ada0-4076-9f2a-618326f251b9.png)

- On the Sounds tab, "favorites" is spelled as "favourites":
![image](https://user-images.githubusercontent.com/91428485/197437032-15b8779f-e633-4b49-a54a-d907f0edc046.png)

**Comment by GabeS573** [comment]
It looks like the "Favorites" spellings have been fixed. However, the "colour" spelling is still wrong in the Settings tab; it should be "color" in en-US.

**Comment by zacjansheski** [comment]
Locale issue will be managed by Muse Hub team
