### ISSUE TITLE
[MU4 Issue] Muse Sounds not loading into MuseScore 4.27.0

### ISSUE THREAD

**Issue by SigmaWaveProds** [musescore/MuseScore#13954]
**Describe the bug**
After installing the latest version of MuseScore 4 Beta 4.27.0, it refuses to load the already installed Muse Sounds library. The issue is still present after deleting all MuseScore 4, Muse Sounds, and Muse Hub files, apps, and data and reinstalling fresh. Issue was still present after restarting computer too.

**To Reproduce**
1. Install Muse Hub, then MuseScore 4, then all Muse Sound libraries.
2. Open MuseScore 4 then open MuseScore document or create new score.
3. Check Mixer to see "Muse Sounds" unavailable every time.

**Screenshots**
![Screen Shot 2022-10-23 at 11 45 48 PM](https://user-images.githubusercontent.com/73251296/197444864-d8c122ea-23f8-4949-a122-f0080d7d8542.png)
![Screen Shot 2022-10-23 at 11 45 17 PM](https://user-images.githubusercontent.com/73251296/197444867-ecdb91b6-47f1-4fe7-a458-08480f49e8d5.png)

**Platform information**
 - OS: macOS _Monterey_ v12.6 | Apple M1 Mac Mini 8 GB RAM

**Comment by Just-your-average-Github-user** [comment]
Reproducible on Windows 10.

**Comment by cbjeukendrup** [comment]
Indeed, it looks like this is covered by https://github.com/musescore/MuseScore/issues/13952. Conclusion: you should not have MuseScore 4.27.0 but just 4.0.0. It is a mistake on our side that you received the update to 4.27.0. So, kill 4.27 with fire, install 4.0.0 from the Hub, and ignore the update to 4.27 if you receive it again.

**Comment by Just-your-average-Github-user** [comment]
Ah, that clears it up. Thanks!
