### ISSUE TITLE
[MU4 Issue] Mixer shows no channels for instruments in the score on Linux Mint 

### ISSUE THREAD

**Issue by robinboncoeur** [musescore/MuseScore#13959]
**Describe the bug**
MU4 Mixer shows no channels for instruments in the score

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Muse Sounds via Muse Hub
2. Open MU4, create a new score with 4 instruments (Flute / Oboe / Clarinet / Bassoon)
3. Click on the Mixer icon at the top of MU4
4. See that only the Master channel appears in Mixer (see screenshot below)

**Expected behaviour**
The Muse Sounds library files installed successfully via Muse Hub, confirmed download in /srv/muse-hub/download/Instruments/. As this is Linux, I downloaded the zip of the AppImage via the link provided on this Beta announcement page:

https://musescore.org/en/node/336003

The file unarchived successfully to a folder named "MU4_3289917644_Lin" (same as the zip). I set execute permissions for the file: 

MuseScore-4.0.0.3289917644-x86_64.AppImage

so the program would run, then launched the AppImage. Created a new score (see attached). Expected to hear note input, but did not. Clicked on Mixer, but no instrument channels were visible, nor were any libraries or even MS Basic available.

**Screenshots**

**Platform information**
 - OS: [Linux Mint 21, Cinnamon]
 - System:
  Kernel: 5.15.0-52-lowlatency x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: Cinnamon 5.4.12
    tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: ASRock model: B360M Pro4 serial: <superuser required>
    UEFI-[Legacy]: American Megatrends v: P3.10 date: 07/11/2018
CPU:
  Info: 6-core model: Intel Core i5-9400F bits: 64 type: MCP arch: Coffee Lake rev: A cache:
    L1: 384 KiB L2: 1.5 MiB L3: 9 MiB
  Speed (MHz): avg: 800 min/max: 800/4100 cores: 1: 800 2: 800 3: 800 4: 800 5: 800 6: 800
    bogomips: 34798
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA GM206 [GeForce GTX 960] vendor: Gigabyte driver: nvidia v: 470.141.03 pcie:
    speed: 2.5 GT/s lanes: 16 bus-ID: 01:00.0 chip-ID: 10de:1401
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1680x1050 s-dpi: 87
  Monitor-1: DVI-I-1 res: 1680x1050 dpi: 90 diag: 559mm (22")
  OpenGL: renderer: NVIDIA GeForce GTX 960/PCIe/SSE2 v: 4.6.0 NVIDIA 470.141.03
    direct render: Yes
Audio:
  Device-1: Intel Cannon Lake PCH cAVS vendor: ASRock driver: snd_hda_intel v: kernel
    bus-ID: 00:1f.3 chip-ID: 8086:a348
  Device-2: NVIDIA GM206 High Definition Audio vendor: Gigabyte driver: snd_hda_intel v: kernel
    pcie: speed: 8 GT/s lanes: 16 bus-ID: 01:00.1 chip-ID: 10de:0fba
  Sound Server-1: ALSA v: k5.15.0-52-lowlatency running: yes
  Sound Server-2: JACK v: 1.9.20 running: no
  Sound Server-3: PulseAudio v: 15.99.1 running: yes
  Sound Server-4: PipeWire v: 0.3.48 running: yes

**Additional context**
The attached file Toodles.zip is a .mscz file: extension renamed. This file opened and played successfully in a MacOS (Monterey) install on my network *after* being created in MU4 in the AppImage on the Linux box.

![Mixer](https://user-images.githubusercontent.com/5742322/197484676-7b278672-f669-4b0d-943a-3b3f2bb5d570.png)
[Toodles.zip](https://github.com/musescore/MuseScore/files/9850149/Toodles.zip)

**Comment by MarcSabatella** [comment]
What happens if you try other instruments?  There are known issues with woodwinds specifically on Linux (check your console log to see all the errors).

**Comment by MarcSabatella** [comment]
Additional info: I can get it to work if I then go to the console with and notice the error message sitting there waiting for my input.  Typing "F" (for "ignore forever") and hitting Enter then allows MuseScore to work normally after that.  The current score won't start working, nr will others created while in this state, but newly created ones will.

**Comment by robinboncoeur** [comment]
Not sure this is going to be helpful but here's the output from Terminal running the AppImage (uninstalled) 
[22.10.25-MU4-CLIoutput.txt](https://github.com/musescore/MuseScore/files/9855119/22.10.25-MU4-CLIoutput.txt)

**Comment by iamtesch** [comment]
Thank you for the report -- we know what's going on here, and should have this fixed up in the next few days.
