### ISSUE TITLE
[Muse Hub Issue] After downloading strings library, musehub still shows it as not downloaded

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13965]
**Describe the bug**
After downloading strings library, after reopening MuseHub, strings library is shown as not downloaded - "Get" button, instead of "Done"

**To Reproduce**
1. Open Muse Hub
2. Download Strings
3. Close Muse hub
4. Open Muse Hub

**Expected behavior**
Downloaded libraries are marked as downloaded.

**Platform information**
 - OS: [reported on Linux]

**Additional context**
In MuseScore, library is recognised, only MuseHub shows it incorrectly.
After some time and several restarts of MuseHub, it shows correctly now.

**Comment by Tantacrul** [comment]
@sammik - has this issue been solved in any of the updates that have happened since you logged this?

**Comment by sammik** [comment]
Ubuntu Studio 22.04 (KDE Plasma)

Still same. Mostly times it is correct. But sometimes it shows as not downloaded. But clicking "get" icon does nothing.
After restarting Muse Hub it usualy shows correct button.

**Comment by Tantacrul** [comment]
OK, so this is more a UI bug then? Muse Sounds is actually working, it's just that the Muse Hub delivers incorrect information?

**Comment by sammik** [comment]
> OK, so this is more a UI bug then? Muse Sounds is actually working, it's just that the Muse Hub delivers incorrect information?

Yes, exactly

**Comment by Tantacrul** [comment]
@sammik - is this still happening for you.

**Comment by sammik** [comment]
> @sammik - is this still happening for you.

Yes, after latest Mus Hub update, it showed Strins library as not downloaded ("Get" button). 
But clicking that button did nothing. Also Alt + Click to uninstall didnt work. 
After few restarts of Muse Hub app, it is showing now correctly.

**Comment by iamtesch** [comment]
We can no longer reproduce this, and I believe this should be working on the latest versions.  If not, we can reopen and add logs to diagnose the issue.
