### ISSUE TITLE
[MU4 Issue] Snare drum hits not fully mapped

### ISSUE THREAD

**Issue by Just-your-average-Github-user** [musescore/MuseScore#13975]
**Describe the bug**
The Muse Sounds snare drum not fully mapped

**To Reproduce**
1. Create a new score with snare drum or concert snare drum as instrument.
2. Add a few notes of different types.
3. Open the mixer and set the snare drum playback soundfont to Muse Sounds snare drum.
4. Start playback.
5. See error.

**Expected behavior**
The snare drum should play different types of notes differently.

**Screenshots**

https://user-images.githubusercontent.com/111419220/197608752-427e9723-cb4e-4fde-94b1-7df17d822b71.mp4

**Platform information**
 - OS: Windows 10

**Additional context**
The problem doesn't exist for bass drums.

**Comment by Tantacrul** [comment]
Can you provide a video or a score to help us see what noteheads you are trying? Some may or may not be supported.

**Comment by Just-your-average-Github-user** [comment]
I could, though it would probably be redundant since I tested every one of them and they all sound the same.

**Comment by Tantacrul** [comment]
Lol but what are you expecting? That's the question. Otherwise all we have to go on is 'the snare doesn't sound right'. Do the sounds work with MS Basic? That'd be a good place to start

**Comment by Just-your-average-Github-user** [comment]
The sounds do work with MS Ba

https://user-images.githubusercontent.com/111419220/197608617-6ddf126c-22e9-4923-bea5-18ddd1beeb58.mp4

**Comment by erinic04** [comment]
That's a marching snare drum. Those are completely different instruments in sound
