### ISSUE TITLE
[MuseHub Issue] MuseSounds not found when searching for Sounds

### ISSUE THREAD

**Issue by jeetee** [musescore/MuseScore#13974]
1. Launch MuseHub
2. Go to the Sounds tab
3. Type "Strings" into the search field

Actual Result:
![image](https://user-images.githubusercontent.com/895153/197527624-73f295e8-2b8d-46c9-a355-38cd5dba3a8a.png)

Expected Result:
MuseSounds "Strings" library is listed there.

**Comment by jeetee** [comment]
This is true for all MuseSounds libraries.

**Comment by Tantacrul** [comment]
Yes, this is point of confusion I've heard about from a few others.

**Comment by Tantacrul** [comment]
This has been fixed.

**Comment by jeetee** [comment]
For me, (still on 0.9.10 apparently), they don't show up in the search field as well.

**But** they are now listed within the Sounds tab as their own category (MuseSounds first, Elements next) and the search field clearly belongs to the latter section imho.

So I'd consider this indeed closed as is (previously MuseSounds simply wasn't on this tab *at all*)

**Comment by cbjeukendrup** [comment]
I see. Makes sense to me too!
