### ISSUE TITLE
[MU4 Request] Change the iteration with Palletes 

### ISSUE THREAD

**Issue by charlesneimog** [musescore/MuseScore#13976]
**Describe the bug**

In **Palettes**, we need to click on the arrow to open the options. I believe it would be easier if they opened automatically when I hovered over the arrow.

![image](https://user-images.githubusercontent.com/31707161/197536085-cac73e51-43a1-44d0-b93d-f7d1439c3e6b.png)

**Comment by Tantacrul** [comment]
Design request. We may revisit the design in future but for now, this isn't an issue we can meaningfully triage.
