### ISSUE TITLE
[MU4 Issue] Can't delete sounds in Muse Hub

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13989]
**Describe the bug**
After you have downloaded a soundset through MuseHub, when you mouse over the tick sign you get a message "Press Alt and click to uninstall. i.e.

![sounds_delete_issue](https://user-images.githubusercontent.com/87246583/197583204-baff463f-304f-4278-96c8-291794aaea69.png)

However, this does not do anything. No progress bar, nothing. The files remain in the "Bin" directory" and when you reopen Muse Hub the sounds are shown as present.

**Expected behavior**

There should be a visible sign of progress and the files should be deleted.

**Platform information**

Linux Mint 20.1 (Cinnamon)

**Comment by MarcSabatella** [comment]
Same for me on Linux Debian.  Works on Windows.

As a workaround, I can manually delete the appropriate folder from /src/muse-hub/downloads, and this *seems* to work in the sense that the space is reclaimed and I can then redownload.  But, I suspect the .instruments file in that same folder also should be updated and I have no clue how to do that.

**Comment by iamtesch** [comment]
Can you verify if this is still an issue on the latest updates?  Preferably, remove the `/src/muse-hub` folder in its entirely first to ensure there is not any old information here.

Thanks!

**Comment by MarcSabatella** [comment]
If I delete that folder, then there is no more checkmark by the installed sounds.  I only see the checkmarks if the folder is present.  But Alt+click continues to not work for me on Linux.

**Comment by MarcSabatella** [comment]
Either I'm going crazy or something changed recently (or both).  There is no mention of "Alt" in the tooltip when I hover over the checkmark icon; it just says to click the trashcan.  And it works now.

**Comment by MarcSabatella** [comment]
FWIW, it worked that day only.  Then again one day a couple of weeks later.  Then again just now.  But 95% of the time it does not.  I'm reporting this on Zendesk as well now.

**Comment by oktophonie** [comment]
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.
