### ISSUE TITLE
Muse Sounds - Long Tied Notes Drops Too Early

### ISSUE THREAD

**Issue by LordJonx** [musescore/MuseScore#13983]
**Dropped Notes **
Brass drops on whole note and or long notes 
 

Windows 10
32 GB of ram
Ryzen 5 3600x

**Additional context**
Link to score -  https://drive.google.com/file/d/17J_-DRYTzt5GOnlzmj8lwO0kL4ko-PBL/view?usp=sharing

https://user-images.githubusercontent.com/116473300/197566436-cf6439eb-a207-4f0c-b685-da6763921758.mp4

 about the problem here.

**Comment by JGreenlee** [comment]
I have sporadic issues with brass dropping off any sustained note - even half notes, dotted quarters, etc

I can't delineate when precisely when it does and doesn't happen, so this may be hard to debug

**Comment by LordJonx** [comment]
Do you think because its a score created on musescore 3

**Comment by KatrinaHahn1** [comment]
I noticed this behavior with Bflat trumpet, sporadically dropping the notes and also two same notes in progression sound like a tied note. Also the trumpet seem to rush some of the notes.
