### ISSUE TITLE
[MuseHub Issue] Setting MuseHub download location to external hard drive created new mount point

### ISSUE THREAD

**Issue by jrbraatz** [musescore/MuseScore#13981]
**Describe the bug**
I set the Muse Sounds download location to /ExternalHD/Music App Content/MuseSounds, and instead of using the existing hard drive named ExternalHD to store the files it ended up creating a new mount point called ExternalHD, and kicked the "real" ExternalHD offline. When I restarted and got it back, my external was on /Volumes/ExternalHD 1/. 

With the HD unplugged, MuseHub still creates a mount point under /Volumes/ for the external hard drive until changed back to default folder and restarted.

**To Reproduce**
1. Go to MuseHub settings
2. For the "Sounds Install Location" select a folder on an existing external hard drive
3. Download a sound package
4. Look at the contents of /Volumes, see if there are multiple instances of your external hard drive
5. Browse to the location it "should" have been saving to on your external HD, notice that no data is there
6. Unplug the external drive, restart.
7. Clean up the disconnected mount points from /Volumes
8. Start MuseHub
9. Check contents of /Volumes/ again, and observe that a new mount point for a drive that isn't plugged in has been created

**Expected behavior**
Use the hard drive requested instead of building a shadow mount copy of it
Be able to tell that an external drive has been disconnected and display error message or otherwise fail vs. creating a new mount point

**Platform information**
 - OS: MacOS 12.6

**Comment by Tantacrul** [comment]
Could you possibly check to see if this has been solved with our latest fixes?

Just to prepare you - if this issue takes a lot of work to solve, we may have to delay it until after the 4.0 launch of MuseScore.

**Comment by Tantacrul** [comment]
> Does the beta version of musehub available from musehub.com contain the latest fixes?
Yep!
