### ISSUE TITLE
Muse Hub: not obvious how to quit the Hub application

### ISSUE THREAD

**Issue by fynndesign** [musescore/MuseScore#13984]
**Describe the bug**
I cannot quit it on OSX without opening the Activity Monitor and abort the process. There is no option to quit at all.

**To Reproduce**
1. Search for an option to quick MuseHub
2. There is none!

**Expected behavior**
I'd expect to be able to quit MuseHub from the MuseHub Menu or Settings

**Screenshots**

**Platform information**
latest OSX

**Additional context**

**Comment by cbjeukendrup** [comment]
You can quit the Hub by right-clicking the Hub icon (either in the Status Bar, or in the Hub popup itself), and then closing "Quit" from the context menu. 
It's not very obvious though; I think that few Mac users know that this is a common way to quit Status Bar applications, simply because Status Bar applications are not _that_ common.

**Comment by fynndesign** [comment]
Hm, I'm pretty sure I tried that before but didn't notice the quit option. However, thanks for the hint. It'd still be nice to have a more visible option though.

**Comment by Obliquely** [comment]
Right-clicking and control-clicking are usually equivalent on the Mac. But the Muse Hub quite menu only appear with a "genuine" right-click. This is highly unusual. And it means some users will notice this all the time and be frustrated and others will never notice it is an issue at all. Gah! 😀

Other Menu Bar applications offer Quit options (and sometimes other options) regardless of whether the user right-clicks or control-clicks. And almost without exception, right-click and control-click are equivalent. (I didn't even know an app could distinguish the two!)

The workaround (for now) for users who are having a problem is to work out how to do a "genuine" right click on their system. On my MacBook I can do this with a two finger tap on the trackpad, and I *think* that's the default, but it's tweakable in System Preferences (or, Settings on Ventura). This is one of those weird issues where mouse users may never even notice that there is an issue!

- - -
**Secondary issue** If this is being fixed, it's worth noting that on the menu option is showing "⌘Q" as the shortcut. But that's definitely bucking Menu App conventions. If the Menu App has the focus then ⌘Q will quit, but no other Menu App I know of shows the shortcut. (This makes a certain sort of sense as the the main focus is really whatever other normal app is running. And, whether you agree with the logic or not, it does seem to be the very strong convention with Menu Apps.)

<img width="142" alt="shortcut shown" src="https://user-images.githubusercontent.com/3323784/206161373-7db59b4e-beac-4f19-8a28-cdeb2afae93f.png">

<img width="262" alt="Screenshot 2022-12-07 at 10 53 26" src="https://user-images.githubusercontent.com/3323784/206161977-0570cd4c-4577-451d-8564-cbc7df7e2cf3.png">

**Comment by oktophonie** [comment]
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.

**Comment by Obliquely** [comment]
> Muse Hub issues are now being handled elsewhere, so will be closed here.
> If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
> You can link to this GitHub issue if it provides useful context or discussion.

Thanks Simon. I've posted something to the MuseHub zendesk
