### ISSUE TITLE
[MU4 Issue] Dropdown not responsive when trying to create a new score

### ISSUE THREAD

**Issue by philipplndwhr** [musescore/MuseScore#13996]
**Describe the bug**
Unable to interact with the Dropdown Menu while trying to create a new score

**To Reproduce**
1. Go to Create New Score
2. Select a different instrument family
3. try to select a different instrument family
4. MS renders the dropdown in the wrong place and becomes irresponsive

**Expected behavior**
Render dropdown properly and allow to click an option

**Screenshots**
<img width="1432" alt="Bildschirmfoto 2022-10-24 um 20 31 00" src="https://user-images.githubusercontent.com/109522890/197601085-1a9ff255-e9c0-4b1f-87e5-50172218e501.png">

**Platform information**
 - OS: macOS Monterrey 12.5.1

**Comment by Tantacrul** [comment]
Can you go to **help > reset to factory settings** and then try again. That is a very unusual bug I've not seen before (been testing this app on MacOS for 2.5 years!)

**Comment by Tantacrul** [comment]
And also, does it happen all the time or under specific circumstances?

Lastly, have you tested with the latest nightly build or are you testing the Beta release?

**Comment by zacjansheski** [comment]
Closing
