### ISSUE TITLE
[MU4 Issue] Muse Sounds no reverb when playing from MIDI keyboard

### ISSUE THREAD

**Issue by DaveCos29** [musescore/MuseScore#13994]
When I use a MIDI controller to enter notes, the playback has no reverb.  

1. Activate instrument 
2. Press N for note entry
3. Play notes via MIDI/USB keyboard
4. Instrument will sound dry with no ambience at all
5. play a line in
6. press PLAY in Muse Score transport
7. instrument plays back with reverb

**Expected behavior**
Ambience should be consistent between note entry and playback .

**Platform information**
 - OS: Mac OS 12.6

**Additional context**
Korg MicroKey 49 as MIDI keyboard entry
Steinberg UR22C audio interface

**Comment by Tantacrul** [comment]
I have a feeling this is a 'won't fix' for 4.0. Will need confirmation though.

**Comment by zacjansheski** [comment]
I believe this currently works as expected.  Closing unless told otherwise.
