### ISSUE TITLE
[MU4 Issue] MuseScore Hub not showing anything when offline

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#13991]
**Describe the bug**

When off-line, Muse Hub doesn not show anything in the window. However it would seem reasonable for it to still indicate the presence of any downloaded soundsets, and allow them to be deleted etc.

**Expected behavior**

Allow reasonable indications and activity offline as explained above. In fact, all the features should be visible offline; so if you try to download something the hub will ask you to connect to the internet.

**Platform information**

Linum Mint 20.1

**Comment by oktophonie** [comment]
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.
