### ISSUE TITLE
[MU4 Issue] Cannot run MuseHub after quitting it

### ISSUE THREAD

**Issue by fynndesign** [musescore/MuseScore#13998]
**Describe the bug**
After quitting MuseHub from the context-menu on OSX, when trying to restart MuseHub I get a Window saying MuseHub wants to install a helper tool. That didn't pop up on the first install. Why now. And what does that tool do?

However, wether I cancel that request or enter my admin details to allow it, I get an error message after that and MuseHub does not start. Restarting OSX does not work. I need to uninstall, restart, reinstall Musehub to resolve that issue.

**To Reproduce**
See above

**Expected behavior**
MuseHub should start without issues and not act like an offended child, replying with some odd message.

**Screenshots**
<img width="262" alt="Screenshot 2022-10-24 at 22 23 36" src="https://user-images.githubusercontent.com/73836300/197622693-a77a5c2d-ece9-4209-a69e-85745664a47f.png">

<img width="260" alt="Screenshot 2022-10-24 at 22 23 58" src="https://user-images.githubusercontent.com/73836300/197622650-f76c169e-6b5f-403f-a54f-de8f565c4772.png">

**Platform information**
Latest OSX

**Additional context**

**Comment by iamtesch** [comment]
Can you provide the exact OSX version?  macOS 13 just came out, so I'm not sure if you are referring to Ventura here or macOS 12.

**Comment by iamtesch** [comment]
I'll go ahead and close this, assuming this is fixed now; we have pushed out updates that make this process more stable.  If this is still an issue, please re-open with OS version info.

Thanks!
