### ISSUE TITLE
[MU4 Issue] Options missing from New Score > Choose instruments > Your score

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#14006]
**Describe the bug**
Applies to today's nightly (i.e. not a problem yesterday):
There are no longer any options in the dropdown menu for ordering instruments in a new score.

<img width="1027" alt="Screenshot 2022-10-25 at 11 01 56 am" src="https://user-images.githubusercontent.com/86290556/197731651-566aae7a-e12e-4b48-a460-d400cb369b56.png">

See demo video: 
https://www.dropbox.com/s/2hwc9wlspwvs5t9/missing-options-in-instrument-order-list.mov?dl=0

**Expected behavior**
This menu should be populated with options for instrument ordering

**Platform information**
 - MacOS 12.6 (M1)

@shoogle any ideas here?

**Comment by DmitryArefiev** [comment]
Fixed in #14017
