### ISSUE TITLE
[MU4 Issue] MuseHub failing to install on older versions of Windows 10

### ISSUE THREAD

**Issue by aero7405** [musescore/MuseScore#14004]
**Describe the bug**
When opening the MuseHub installer it throws an error stating that the windows version is not supported despite being on win10.

**To Reproduce**
Unzip folder containing fresh installer.
Attempt to run MuseHub on Windows 10 18363 build.
Throws error shown in screenshot.

**Expected behavior**
Expect the installer to run and install MuseHub

**Platform information**
 - OS: Windows 10

![image](https://user-images.githubusercontent.com/66096753/197719819-ac0cd44c-0988-4ace-953a-e5d9f2412992.png)

**Comment by Janidim** [comment]
I don't get that error on my Win 10 , it installs, but doesn't open. It runs the service, but nothing appears on screen.

**Comment by aero7405** [comment]
It maybe a machine specific issue with some weird settings (which would make it difficult to reproduce), but it specifically threw the error claiming the OS build was too old so I'm inclined to think that maybe your windows version was too recent?

**Comment by iamtesch** [comment]
This version of Windows is not supported by the Hub (as a note it is from November 2019, and is no longer supported by Microsoft either -- see https://en.wikipedia.org/wiki/Windows_10_version_history )

The error states that you need 19041 to install the hub.

**Comment by Jojo-Schmitz** [comment]
See also #15877, which might solve this here too
