### ISSUE TITLE
[MU4 Issue] Process on root level running on Mac OSX even after uninstallation of MuseHub

### ISSUE THREAD

**Issue by fynndesign** [musescore/MuseScore#14008]
**Describe the bug**
I deleted MuseHub for the time being due to too many issues and problems on my Mac. Emptied the trash, restarted my MBP. In the activity Monitor is still a service running on root level (!) which I can't either abort or delete in any way. It's there, after evert reboot. How do I get rid of that? 

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="954" alt="Screenshot 2022-10-25 at 11 26 06" src="https://user-images.githubusercontent.com/73836300/197739601-e0b79b2c-0ff0-4e2c-a6bd-ba6f95d90d4b.png">

**Platform information**
Latest OSX

**Additional context**

**Comment by fynndesign** [comment]
I installed the new OSX Ventura yesterday. And guess what... the process com.muse.museservice is still running. How do I get rid of that?

**Comment by IsaacWeiss** [comment]
Workaround for the end user from https://musescore.org/en/node/336003#comment-1146722:

> you have to go to /Library/LaunchDaemons/ and delete com.muse.museservice.plist - empty the trash and restart

**Comment by iamtesch** [comment]
When Muse Hub is installed, you can right click on the icon and select "uninstall helper".  This needs to be done before deleting Muse Hub.

We will work to improve the uninstall process of the hub before full release so this doesn't occur.

**Comment by iamtesch** [comment]
The "uninstall" option in the latest mac hub should cleanly uninstall all associated processes now; let use know if you are still having any issues here!
