### ISSUE TITLE
[Muse Hub Issue]  After quitting Muse Hub MuseService.exe remains active

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#14000]
**Describe the bug**
After right clicking on the Muse Hub icon in the system tray and selecting Quit as described here [https://github.com/musescore/MuseScore/issues/13984](url)

Windows task manager shows Muse.Service.exe to be active, using CPU and performing IO.

**To Reproduce**
1. Start Muse Hub
2. Look at windows task manger
3. Note two processes: Muse.exe and MuseService,exe
4. Right click on Muse Hub icon in system tray
5. Select Quit
6. Look at windows task manager
7. Note that Muse.Service.exe is still running (CPU usage non-zero and IO activity non-zero)

**Expected behavior**

All Muse Hub related processes should stop

**Screenshots**

**Platform information**

OS: Windows 10 Version 2009, Arch.: x86_64, 
Muse.exe - Muse Hub version 0.9.6.484
Muse,Service.exe - Muse Hub background service version 0.9.6.484

**Additional context**
@Tantacrul for triage

**Comment by SteveBlower** [comment]
Not sure if this is relevant to the issue but after force terminating Muse.Service.exe in task manager Muse.Service.exe no longer starts when I start Muse Hub. I only see the Muse.exe process.  When I open Musehub I see an error message "Muse Hub helper service is not running" with greyed out "Connect" button.  See screencap image

![MuseHubError](https://user-images.githubusercontent.com/60138048/198012883-52d0199d-a465-4f7b-abc1-9ca1fd2b881d.jpg)

**Comment by iamtesch** [comment]
These issues are related; the service is designed to keep running while your PC is on so that you can continue to download sounds in the background.  Quitting this service leads to issues when restarting the hub UI.

We understand this is a bit misleading, though, and are looking into changing this behavior.

**Comment by RichardJECooke** [comment]
Even if you disable automatic startup in both Window start menu - Startup apps, and Musehub - Gear icon - Startup at sign in, the service still runs in the background at startup. And there doesn't seem to be an option to turn it off in Windows Services either - the startup type combobox is disabled for me.

Turning off the startup option in Musehub - Gear icon should prevent the Musehub service from starting at startup.

https://musescore.org/en/comment/1150480

**Comment by iamtesch** [comment]
Just as an update -- we should have a fix for this in the next week.  Thanks for your patience!

**Comment by swcastle** [comment]
FYI, related to this issue, the Torrent connections that the service tries to establish are repeatedly denied by the firewall on my provider, with the message that a known malicious site connection was denied. Some of them are established successfully but a sizable fraction are not. Maybe we should have an option not to use Torrent? (I can supply a Wireshark log if necessary.)

**Comment by Tantacrul** [comment]
All Muse Hub issues should now be directed here:
https://musehub.zendesk.com/hc/en-gb

This is so we can return to addressing issues for MuseScore only. Thank you!
