### ISSUE TITLE
[MuseHub feature request] allow setting a seeding limit

### ISSUE THREAD

**Issue by jeetee** [musescore/MuseScore#14005]
Here in Belgium, metered connections are the standard.
Even so I can easily reserve a portion of my montly throughput for seeding via the Hub. It would be nice to be able to configure the Hub to allow seeding up to a certain upload size limit / period.

If that is not feasible, then consider at least showing the amount of data transferred somewhere within the Hub for manual verification.

@Tantacrul for triage

**Comment by Tantacrul** [comment]
Thanks for the issue. I'm letting the team know now.

**Comment by DominicMaas** [comment]
> For further clarification; those structural changes meaning that in Muse Hub v2 there no longer should be p2p traffic.

Yes
