### ISSUE TITLE
[MU4 Muse Sounds] Blurry, messy performance with fast intervals on Linux

### ISSUE THREAD

**Issue by sberla365** [musescore/MuseScore#14014]
I am not sure how to address this issue, since it is not particularly specific to my set ups but rather to various issues at once related to the type of music I am trying to play.

The sounds skip, blur, speed up and slow down producing a messy, rhythmically inaccurate performance. 

I am having a horrible experience with MSounds and I am not too sure how to address the issue and be helpful other than posting everything I can here for you to try to reproduce. I try to guess what is happening, at least in terms of performance.

I attach a couple of scores and screencast of how they sound on my system to give an example of the blurryness and mess in the performance of Muse Sounds I am experiencing. 
The results are independent of buffer size. [Here it Comes Andromeda - MU4 Test.zip](https://github.com/musescore/MuseScore/files/9860389/Here.it.Comes.Andromeda.-.MU4.Test.zip)

[Kooha-2022-10-25-14-42-43.webm](https://user-images.githubusercontent.com/55401477/197778405-c3db00d9-620a-4f94-92a2-7da4433a5be1.webm)

The issue, to me, seems linked to the standard interpretation of clean (non articulated) notes. All notes without articulation are performed horrybly wrong. I attach an example of the same piece (and screencast) in which I give articulations to each note in the first few bars to show how the difference is huge. Although it does not sound well, the rhythms are more accurate. 
Woodwind players would normally articulate clean notes (no slurs, no articulation marks) with a very light staccato, which seems to be missing in MS at the moment. It seems that the notes are played slurred but being far apart and fast the result is not great. 

[Kooha-2022-10-25-14-43-59.webm](https://user-images.githubusercontent.com/55401477/197778563-d4d6fa54-2eba-4c59-99d0-4a9ae67fb4f0.webm)

[Here it Comes Andromeda - MU4 Test Staccato.zip](https://github.com/musescore/MuseScore/files/9860390/Here.it.Comes.Andromeda.-.MU4.Test.Staccato.zip)

I have the same issues with many other scores, no matter the instrument. For instance, the same happens with a trnacription of the same piece for string quartet.

As a bonus, when opening a new Saxophone Quartet, or importing a saxophone quartet score from MU3 Muse Sounds defaults to 4 tenor saxophones each and every time. Has this been reported already or should I open another issue for this?

This was tested on Fedora 36 and Ubuntu 22.04 on a Tuxedo Infinitybook with i5 11th gen and 16gb of ram. I obtained the very same results on other hardware with lower specs.

**Comment by zacjansheski** [comment]
Has this improved? Since the latest update (with additional reverb control) I am getting much cleaner playback.

**Comment by zacjansheski** [comment]
Closing, no response
