### ISSUE TITLE
Crash when hiding a staff in tab with no title and reprise in the first measure

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#14029]
**Describe the bug**
Reproduces only with 
[test tab for MU4.gp.zip](https://github.com/musescore/MuseScore/files/9861862/test.tab.for.MU4.gp.zip)

**To Reproduce**
1. Open the tab
2. In instruments tab of inspector hide the staff

**Expected behavior**
Blank page

**Screenshots**

https://user-images.githubusercontent.com/101250347/197821007-ad80a82d-3ebc-447f-a2e5-25b432508557.mp4

**Comment by alexpavlov96** [comment]
@abariska reproduces on files with reprise on the first measure
also reproduces on files saved after import
doesn't reproduce on created files in MU
[crash-reprise.zip](https://github.com/musescore/MuseScore/files/9862014/crash-reprise.zip)

**Comment by alexpavlov96** [comment]
@abariska crash happens when there is reprise on first measure and there is no title box, with no connection to GP import
[reprise-crash.mscx.zip](https://github.com/musescore/MuseScore/files/9930084/reprise-crash.mscx.zip)

**Comment by abariska** [comment]
@alexpavlov96 App still crashes

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12
