### ISSUE TITLE
[MU4 Issue] Chord symbols placed on the first beat of a measure and attached to an invisible rest get placed too close to the barline

### ISSUE THREAD

**Issue by Riisus** [musescore/MuseScore#14037]
**Describe the bug**
As the title says, if you attach a chord symbol on an invisible rest on the first beat of a measure, it gets placed too close to the preceding barline.

**To Reproduce**
1. Go to any score
2. Place a chord on a rest in the first beat of a measure that has a barline before it
3. Make the rest attached to the chord symbol invisible (If there are other instruments, they must have an invisible rest there as well).

**Expected behavior**
Chord symbols placed on invisible rests remain correctly offset from a preceding barline.

**Screenshots**
<img width="760" alt="chord symbol offset" src="https://user-images.githubusercontent.com/116495080/197857090-dff9a483-c002-4176-ae0a-0e2e92079da2.png">
<img width="678" alt="chord symbol offset 2" src="https://user-images.githubusercontent.com/116495080/197858497-7c909f8b-c1e0-4bf4-8349-86f781c2f8d3.png">

**Platform information**
 - MacOS 13.0

**Comment by oktophonie** [comment]
Further, I'd say the invisible rest is too close to the barline.

**Comment by Riisus** [comment]
Yes they are, but only ones with a chord symbol attached to them. Invisible rests without a chord symbol are fine.

**Comment by oktophonie** [comment]
Even worse!
