### ISSUE TITLE
[MU4 Issue] Musescore quits when trying to open a MIDI file.

### ISSUE THREAD

**Issue by Just-your-average-Github-user** [musescore/MuseScore#14036]
**Describe the bug**
When trying to open a MIDI file, Musescore closes.

**To Reproduce**
1. From 'File', click 'Open'
2. Select a MIDI file.
3. See error.

**Expected behavior**
Musescore should convert the MIDI file to a score and open it.

**Screenshots**

**Platform information**
 - OS: Windows 10

**Additional context**

**Comment by MarcSabatella** [comment]
Please attach the specific MIDI file you are having trouble with (ZIP it first if GitHub won't take it as is).

**Comment by Just-your-average-Github-user** [comment]
[MuseNet improvises Rachmaninoff.zip](https://github.com/musescore/MuseScore/files/9863197/MuseNet.improvises.Rachmaninoff.zip)

**Comment by Eism** [comment]
Is it reproduced on the nightly build? 
https://github.com/musescore/MuseScore/suites/8942547540/artifacts/410438712

(I fixed a crash when opening a midi file a week ago)

**Comment by Just-your-average-Github-user** [comment]
Fortunately, no.
