### ISSUE TITLE
Focus state & screen reader support for the Muse Hub

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#14034]
**Task description**
Since MS4 works with various screen readers and has been developed with a high level of accessibility in mind, it would be really great for the Muse Hub to do the same.

Without this, blind users will not be able to install Muse Sounds.

We will have direct links to MS4 available on MuseScore.org in the meantime but this is not an ideal solution.

**Comment by iamtesch** [comment]
The latest versions of MuseHub have improved screen reader support.  If there are still specific issues, we can address these individually.
