### ISSUE TITLE
[MU4 Issue] Musescore not load SoundFonts with special char (accents)

### ISSUE THREAD

**Issue by charlesneimog** [musescore/MuseScore#14032]
**Describe the bug**
Musescore not load SoundFonts with special char (accents). For example, MU4 read the soundfont called `Cajon.sf2`, but not load if the SoundFont is called `Cajón.sf2` - same `sf2` file renamed.

**To Reproduce**
1. Rename any soundfont with accents.

**Expected behavior**
Work with accents.

**Screenshots**

https://user-images.githubusercontent.com/31707161/197833852-ffcb0063-6e4c-44fd-8e0a-a7b29c12cab0.mp4

**(Sound weird because of OBS.)**

**Platform information**
 - OS: Windows 64bits

**Comment by cbjeukendrup** [comment]
This looks similar to https://github.com/musescore/MuseScore/issues/17518, which has been fixed. Could you please check if this still occurs in the latest nightly build? https://musescore.org/en/nightly-builds

**Comment by mercuree** [comment]
@cbjeukendrup It works for me on windows 10 with nightly 4.2.0
1. Downloaded random sf2
2. Renamed to Cajón.sf2
3. Installed this sf2 soundfont
4. Opened with 4.1.1 - not working
5. Opened with MuseScore version (64-bit): 4.2.0-232222302 - now it works!

Also I see this line in logs 
```
FluidSynth | addSoundFonts: success load soundfont: C:/Users/Mercuree/Documents/MuseScore4Development/SoundFonts/Cajón.sf2
```

**Comment by cbjeukendrup** [comment]
@mercuree Thanks for checking! That's indeed the expected outcome: starting with the 4.2.0 it should work. I'll close this issue.
