### ISSUE TITLE
Muse Hub not installing on Linux Mint 20.3

### ISSUE THREAD

**Issue by musescorebeta1** [musescore/MuseScore#14048]
Linux Mint 20.3: Musehub.deb extracts & installs but fails during launch.

**To Reproduce**
extract musehub.deb
install
run app

**Expected behavior**
Musehub app should load

**Screenshots**
n/a

**Platform information**
Linux Mint 20.3

**Additional context**

**Comment by Tantacrul** [comment]
Can you provide any more information or a video? Does you get any errors?

**Comment by rgreen5** [comment]
Similar to #13909.

**Comment by Tantacrul** [comment]
Thanks @rgreen5 

Duplicate of https://github.com/musescore/MuseScore/issues/13909
