### ISSUE TITLE
[MU4 Issue] Broken pizzicato layering on regular sound.

### ISSUE THREAD

**Issue by Lighwan** [musescore/MuseScore#14042]
Score in question; https://musescore.com/user/13502736/scores/5582243

https://user-images.githubusercontent.com/68567124/197871275-a9a5750f-3e7e-4e9a-9ac5-86e866272cf2.mp4

Downloaded a score made on musescore 3.6. It has left hand pizzicato notated for the violin using staff text "arco" and "pizz." The classes for these in ms4 are "technique annotations" and staff text no longer works for playback.

Anyway, as I was changing the old staff texts to technique annotations from the palettes menu, the last line somehow overlapped the pizz and normal bowing resulting in this nightmare. 

Attached is a full 4minute video of my replication steps in causing this bug.

P.S. the + sign for left hand pizzicato does not play the left hand pizzicato in playback. would appreciate it if you fixed it as well.

**Comment by Lighwan** [comment]
I apologize for the video quality, had to compress it down from 200ish mb. and i'm guessing 8mb.video isn't the most efficient.

**Comment by Tantacrul** [comment]
Was this tested in the beta version? We've just updated the nightly builds with a fix for interpreting arco / pizz directions from older scores. Would be great if you could test that:

https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/?C=M;O=D

**Comment by Lighwan** [comment]
Fixed in newest nightly. (or atleast could not reproduce. old staff text also is converted appropriately)
