### ISSUE TITLE
[MU4 Issue] could not get Muse Hub to open in AV linux

### ISSUE THREAD

**Issue by sevcikshifter** [musescore/MuseScore#14040]
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by MarcSabatella** [comment]
I have heard that AV Linux does not run systemd by default, and running it might help.  Or, you night find starting muse-hub-service manually helps.

**Comment by jivy59** [comment]
Select the "SystemD" option when you boot AVL.
Install the .deb file 
From the menu select "All Applications" then scroll down until you find "Muse-Hub"
Muse-Hub should open and allow you to download the various Muse-Sounds

**Comment by oktophonie** [comment]
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.
