### ISSUE TITLE
[MU4 Issue]

### ISSUE THREAD

**Issue by bobjp** [musescore/MuseScore#14047]
**Describe the bug**
Audio export of orchestral files created in MuseScore 3.6.2 gets the last several notes cut off when exported in MU4.

**To Reproduce**
Load an orchestral mscz. file created in 3.6.2
Export as WAV or mp3

**Expected behavior**
Result should be a rendition of entire score

**Screenshots**

**Platform information**
Windows 10 

**Additional context**
I've had this result with two scores that work fine in 3.6.2. Can't attach a score.

**Comment by erinic04** [comment]
This is the same problem as #13938

**Comment by Eism** [comment]
closed as duplicate
