### ISSUE TITLE
[MU4 Issue] Missing Margin in Horizontal Continuous View

### ISSUE THREAD

**Issue by akulisch** [musescore/MuseScore#14046]
**Describe the bug**
When viewing scores in the horizontal continuous view, right and bottom margins are missing, while top and left margins are present.

**To Reproduce**
1. Open a score (“Introducing Muse Orchestra” used in screenshots)
2. Change view to continuous view (horizontal)
3. Compare top and left “page” margins with right and bottom margins.

**Expected behavior**
Similar margins to the top and left should be present on the right and on the bottom of the continuous page.

**Screenshots**
Bottom right:
![image](https://user-images.githubusercontent.com/15906252/197899531-8b005cfe-bf9c-4f40-81fb-0ba490d66796.png)
In comparison, top left:
![image](https://user-images.githubusercontent.com/15906252/197899481-141d222f-f754-4178-b2ed-6f6e7a68b1bc.png)

**Platform information**
 - OS: Windows 10 Pro 21H2 10.0.19044 Build 19044.2130
 - MuseScore 4.0 Beta (installed through Muse Hub), labeled in software as Revision abc123456 😅

**Additional context**
 - There is already a possibly related issue #11325 regarding the surrounding whitespace, which doesn’t consider the internal margins, though.

**Comment by Tantacrul** [comment]
Oh, this is actually super annoying. @oktophonie - what do you think? Some additional space at the end of a score?

**Comment by cbjeukendrup** [comment]
@Tantacrul @oktophonie please check #14121; I made the bottom / right margins the same size as in Page View, similar to what we are doing for the top / left margins.
