### ISSUE TITLE
[MUSE HUB Issue] Muse Hub didn't get any download links

### ISSUE THREAD

**Issue by arnison** [musescore/MuseScore#14049]
**Describe the bug**
The delegate executed asynchronously through timeoutpolicy did not complete within the timeout.

**To Reproduce**
1. Launch Muse Hub.
2. See error.

**Expected behavior**
didn't see any download button after launching Muse Hub. 

**Screenshots**
![image](https://user-images.githubusercontent.com/108361135/197914960-05ac74e6-034e-426d-acc9-60dc7445e729.png)

 - OS: Windows 10

**Comment by iamtesch** [comment]
Currently we are working to get the server back up; sorry for the inconvenience!

**Comment by iamtesch** [comment]
This has been resolved, and we've addressed the root cause.
