### ISSUE TITLE
[MU4 Issue] Typo in german translation of Playback setup

### ISSUE THREAD

**Issue by Grillzombie** [musescore/MuseScore#14059]
**Describe the bug**
There is a typo in the german translation of the Playback setup dialog.  

**To Reproduce**
View -> Playback setup, if you change a profile, there is a button "Diese Profil aktivieren".

**Expected behavior**
This text on the button has to be spelled "Dieses Profil aktivieren" in german.

**Screenshots**
![Wiedergabedialog](https://user-images.githubusercontent.com/97833240/198017795-14ca0e5d-cca7-4767-9f1f-ae428da366cb.png)

**Platform information**
 - OS: Linux Mint 21

**Comment by RobFog** [comment]
@Jojo-Schmitz

**Comment by cbjeukendrup** [comment]
I just fixed it on Transifex. @Grillzombie, if you go to Preferences > General now, and click "Check for language updates", and then restart MuseScore, you should see the fixed version.
