### ISSUE TITLE
[MU4 Issue] Preferences: problem with subheadings?

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#14052]
**Describe the bug**

When you first open Preferences, the top of the dialog looks like this:

![preferences_dialog](https://user-images.githubusercontent.com/87246583/198000080-17b1c15e-2ec5-4acf-8116-bccfd773771e.png)

The indentation of the headings "Program start" and "Folders" suggests that they are subheadings of "General". In which case you must also show the other sections of "General" as subheadings. And, the content (in the RH pane) of visible subheadings should also be visible, or accessible through scrolling.

It looks odd having visible subheadings but the subtext not being visible until you click on them.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3326178321, revision: github-musescore-musescore-cea74a0

**Comment by Tantacrul** [comment]
Yeah, this hasn't quite worked out as planned. We expect there to be a lot more settings so created a sub menu, which only gets used with 'General' right now. We'll address this again in later releases. Closing for now.
