### ISSUE TITLE
[MU4 Issue] Adjusting frame gap causes system to freeze

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#14057]
**Describe the bug**

Adjusting the top gap in the title frame of the attached score, causes the whole PC to freeze up. This may require a turnoff and reboot to recover.

**To Reproduce**

1. Open the attached score. 
[beethoven_sym6.zip](https://github.com/musescore/MuseScore/files/9868977/beethoven_sym6.zip)

2. Select the first (title) frame.
3. Place the cursor in "Top margin" in the Properties panel
4. Use the up arrow to progressively increase the top space

RESULT: The system freezes.

**Expected behavior**

Adjustment should be instantaneous and without any lagging or system freeze. As it is in MS3.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3326178321, revision: github-musescore-musescore-cea74a0

(Intel Pentium CPU 2020M @ 2.40GHz × 2 / 3.7 Gb RAM.)

**Comment by oktophonie** [comment]
Could not reproduce (OS: Artix Linux, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3326178321, revision: github-musescore-musescore-cea74a0). Anyone else?

(Adjusting the top margin isn't expected to have any effect in this situation, but it obviously shouldn't cause a freeze or crash.)

**Comment by rgreen5** [comment]
BTW. You may need to mix up things using both the spinner controls and the keyboard arrows. Click outside occasionally as well. IME, it starts off as laggy behviour then eventually becomes a system freeze.

**Comment by oktophonie** [comment]
Yes! I can reproduce the problem in this way.

This is the same as a problem I encountered while inputting a score, around a month ago, but as I could not work out how to reliably reproduce it, I had not logged it. Like you described, the whole system (not just MuseScore) would start lagging severely, and if MuseScore were not closed quickly enough, it soon becomes impossible to perform any operations at all; everything would freeze, and eventually (in my case) the X server would crash entirely.

So it would appear that performing certain operations in the Properties panel, changing numeric values, causes this to occur.

**Comment by DmitryArefiev** [comment]
@RomanPudashkin To reproduce just **click and hold** the down spinner control for some seconds then the up control, and do this actions several times. 
Notice that memory is **incredibly growing**




https://user-images.githubusercontent.com/90187801/200521271-3a6e17cd-edf4-4fa4-95e9-7462533fa0b5.mp4
