### ISSUE TITLE
[MU4 Issue] Parts from MuseScore3 are duplicated after opening in MuseScore4 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#14066]
**To Reproduce**
1. Create score in MS3 
2. Extract parts
3. Save it
4. Open in MU4 (or just open [String_quartet.zip](https://github.com/musescore/MuseScore/files/9871110/String_quartet.zip) in MU4)

https://user-images.githubusercontent.com/90187801/198073505-373fdb3a-90ff-4d57-8ffc-9ef8950d106a.mp4

**Actual result**
There are two instances of each part. First is modified part in MS3 and second is regenerated new part in MU4

**Expected result**
There should be only one instance, the one created/modified in MS3

**Platform information**
macOS, Windows, Linux

**Comment by woooowoooo** [comment]
I'd like to note that the ones created in MS3 are deletable while the auto-generated ones in MS4 are not

**Comment by DmitryArefiev** [comment]
You're right. Good catch! Thanks

FYI @RomanPudashkin

**Comment by sammik** [comment]
Also problem when opening MU3 < 3.5 version score with multiple same instruments.
It is different issue  #14163 , but I think, it is also related to this one.

**Comment by sammik** [comment]
@RomanPudashkin I checked PR #14288 
MU 3.5 scores are fixed, but earlier versions are not, see:

https://user-images.githubusercontent.com/1646034/199977124-c40ec826-f359-4bb1-b50c-e214ee3cf1a0.mp4

Its probably because of [issue](https://github.com/musescore/MuseScore/issues/14163) I mentioned above.

**Comment by DmitryArefiev** [comment]
Fixed in #14288

**Comment by DmitryArefiev** [comment]
@sammik Can you recheck briefly on master if all issues are fixed on your side? Thanks!

**Comment by DmitryArefiev** [comment]
Thanks!
