### ISSUE TITLE
[MU4 Issue] Playback timer is reset on repeat or jump

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#14064]
**Describe the bug**

The elapsed play time indicator in the Playback controls toolbar is reset when a repeat or backwards jump is encountered
 
**To Reproduce**

1. Rename attached score by removing .zip extension
2. Load into MuseScore4
3. Play
4. Note the timer is reset to zero when the repeat is taken and when the DC is taken.
5. Note that the timer jumps from 4.00 seconds to 6.00 seconds when the jump to Coda is taken.
6. Note that the timer continues to run when play stops and reads 11.00 seconds when play is completed - based on the tempo of crotchet = 120 it should take12.00 seconds.

**Expected behavior**
Timer should reflect the actual elapsed time.

**Screenshots**

https://user-images.githubusercontent.com/60138048/198049699-270fe88b-6eb0-4e09-855e-ecf8d411a33c.mp4

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289914935, revision: github-musescore-musescore-abc123456

**Additional context**

This may be connected with #13683

@Tantacrul for triage

**Comment by DmitryArefiev** [comment]
Fixed in #14449
