### ISSUE TITLE
[MU4] Caesura causes inconsistent playback between parts

### ISSUE THREAD

**Issue by jcourtne** [musescore/MuseScore#14071]
**Describe the bug**
When a caesura is included, playback does not pause correctly (some parts continue to play). Also, after resuming, not all notes are played (notes at the end of the piece are cut off).

**To Reproduce**
1. add 2 instruments to a new score.
2. add 2 measures of music
3. add a caesura at the same point in each part
4. playback the part

**Expected behavior**
Music should pause and resume consistently across both parts.

**Sample score**
[caesura example.zip](https://github.com/musescore/MuseScore/files/9872456/caesura.example.zip)

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289914935, revision: github-musescore-musescore-abc123456

**Comment by Tantacrul** [comment]
I'm playing this on the Beta and the latest nightly and not replicating the issue. Both instruments start and stop at the same time for me in the main score. (Each part also sounds fine)

**Comment by jcourtne** [comment]
After taking another look, it's adding/removing the cesura that causes the problem, but once it's saved and reopened, it works correctly.

cesura removed:
https://user-images.githubusercontent.com/1214737/198464661-6f0fff45-a07c-4c97-ac23-23b6232a52c8.mp4

cesura added:
https://user-images.githubusercontent.com/1214737/198465944-d40d04b7-b648-4fa4-86f5-f3eb4fd4a7cc.mp4

**Comment by jcourtne** [comment]
Looks like this is still happening after the most recent update
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223072007, revision: github-musescore-musescore-2c34155
