### ISSUE TITLE
[MU4 Issue] MuseHub will not download anything after changing download directory

### ISSUE THREAD

**Issue by taylank** [musescore/MuseScore#14075]
**Describe the bug**
Setting a custom download directory for MuseHub results in the app being unable to download anything.

**To Reproduce**
Install MuseHub.
Start downloading something.
Change the download directory while downloading.
Pause download and quit.
Upon restarting the app, observe that downloads cannot proceed.

Uninstalled, removed directories, reinstalled. Did not fix the issue. 
Switching back to default directory did not fix the issue.

The following errors pop up in service log file:

2022-10-26 10:34:54.7328|INFO|Muse.Service.Interop.ServiceCore|Registering Hidden Item (Type: Application, Id: hub, Name: Muse Hub)...
2022-10-26 10:34:54.7328|INFO|Muse.Service.Interop.ServiceCore|Calling register hidden download
2022-10-26 10:34:54.7328|ERROR|Muse.Service.Interop.ServiceCore|Calling registerHiddenDownload before init or after finalize!

ERROR|Muse.Service.Interop.ServiceCore|Calling startDownload before init or after finalize!

Also reported here:
https://musescore.org/en/node/336270
https://musescore.org/en/node/336135

**Expected behavior**
MuseHub should be able to download to a custom directory

**Platform information**
Windows 10

**Additional context**
[service_log.txt](https://github.com/musescore/MuseScore/files/9873320/service_log.txt)
[client_log.txt](https://github.com/musescore/MuseScore/files/9873321/client_log.txt)
[common_settings.txt](https://github.com/musescore/MuseScore/files/9873323/common_settings.txt)
[user_settings.txt](https://github.com/musescore/MuseScore/files/9873324/user_settings.txt)
[dlcache.txt](https://github.com/musescore/MuseScore/files/9873326/dlcache.txt)

**Comment by Skelbti** [comment]
Exactly the same things happened to me on Windows 10 too. I had to delete every file (even in hidden folders) and reinstall MuseHub to fix it.

**Comment by MoritzBrueckner** [comment]
I had the same issue, also on Windows 10. Deleting all the files and reinstalling MuseHub didn't work for me, however I eventually fixed it by restarting the `Muse Hub Background Service` in the task manager (service tab). MuseHub then asked me whether I want to reconnect to the service and suddenly the downloads started working again:

![Screenshot of the reconnect prompt in MuseHub](https://user-images.githubusercontent.com/17685000/198405448-b72ea00b-de14-4679-b5d6-11ca7c791d86.png)

A few more observations/remarks:
- The issue even occurs when the download is started _after_ choosing the custom installation directory, you don't need to have an already running download.
- The issue persists even after changing the installation directory back to default.
- Even though the install location setting seems to be for sounds only\*, this issue also prevents downloading or even updating the software (Musescore, Audacity, ...).
- In my case, the MuseHub executable was located on another drive than the custom install location, but as I wrote changing it back to default (which is on the same drive and partition than the executable) also didn't help.

\* *Off-topic: can you please add a setting in the UI for the software install location as well? There is an entry for that in `Settings.json`, but I haven't tested yet whether changing it will actually have an effect.*

**Comment by iamtesch** [comment]
This should be fixed in the most recent build -- can you verify this is still an issue?

**Comment by taylank** [comment]
I can confirm hub is now able to download to a custom directory on 0.9.9.515.
But now I'm running into the issue of MuseSounds being inactive in the app with no way of enabling them.

**Comment by iamtesch** [comment]
Thanks for verifying -- the remaining issue is a separate issue reported elsewhere (and for which we'll have an update soon to fix), so I'll go ahead and close this particular issue in favor of that.
