### ISSUE TITLE
[MU4 Issue] Violins 1 and 2 (solo) have a lower range of notes than they should.

### ISSUE THREAD

**Issue by Lighwan** [musescore/MuseScore#14080]
The orchestral violins 1 and 2 as well as the musebasic soundfont plays high notes fine, but the solo violin instruments cease playing entirely when going into very high registers.

Here is a video comparing muse basic behavior to muse violin 1.
https://user-images.githubusercontent.com/68567124/198159210-c2d643c4-262c-42e4-bb53-854b62e2edfe.mp4

**Comment by KaiVinter** [comment]
Also, the highest A it reaches sounds quite flat.
