### ISSUE TITLE
[MU4 Issue] self-exit when using muse sounds solo string instrument

### ISSUE THREAD

**Issue by YuenSzeHong** [musescore/MuseScore#14083]
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**
1. open the score
2. switch to any solo string instrument (in muse sounds)
3. crash on playback / click on a single note

**Expected behavior**

**Screenshots**

**Platform information**
 - OS: Microsoft Windows 11 for Workstations (x64) beta 22623
 - CPU: Intel I7 10700
 - RAM: 32GB

**Additional context**
score used:
https://musescore.com/user/13502736/scores/5582243

log:
[MuseScore_221027_121619.log](https://github.com/musescore/MuseScore/files/9876819/MuseScore_221027_121619.log)

crash dump
https://transfer.sh/jHX3xD/1b9060ff-bf34-4ffe-9571-6d39f94658b6.dmp

crash details (ran analyse on windbg)
[crash-analysis.txt](https://github.com/musescore/MuseScore/files/9876831/crash-analysis.txt)

**Comment by cbjeukendrup** [comment]
@YuenSzeHong Hello! Could you please check if this is still happens in the latest versions of MuseScore (the RC) and Muse Sounds? (Update them using the Muse Hub.)

**Comment by YuenSzeHong** [comment]
The issue resolved for a few versions ago

**Comment by cbjeukendrup** [comment]
Thanks, then I'll mark it as completed!
