### ISSUE TITLE
[MU4 Issue] Save to cloud: pressing "Save" creates a new file on musescore.com

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#14087]
**Describe the bug**
This is a recent regression!
Saving a private cloud score now creates a new file on musescore.com – every time a "Save" command is run. 

Demo video (showing how to reproduce): https://www.dropbox.com/s/02w26b1a9mmzfl8/savetocloud-newfiles.mov?dl=0 

**Expected behavior**
"Save" should save changes to the existing cloud score file, not create a new file.

**Platform information**
 - MacOS 12.6 (M1)

**Comment by shoogle** [comment]
This was caused by a website change that has been fixed now. @bentl is investigating long term solutions to prevent it happening again.

**Comment by bkunda** [comment]
Thanks @shoogle. Just tested this on Mac and it is working again as expected.
Closing this issue for now.
