### ISSUE TITLE
[MU4 Issue] MP3 conversion displaces notes

### ISSUE THREAD

**Issue by dyyap** [musescore/MuseScore#14081]
**Describe the bug**
If you convert the score to mp3, some instruments are not in time with the rest of the instruments given a big score.

**To Reproduce**
1. Find a big score (orchestral, big band, etc.)
2. Convert to MP3
3. Hear Playback

**Expected behavior**
Should hear everything line up and notes to not be on time

**Screenshots**

**Platform information**
Windows 

**Additional context**
[Salt, Sugar, Spice.zip](https://github.com/musescore/MuseScore/files/9876136/Salt.Sugar.Spice.zip)
https://musescore.com/user/338211/scores/6037953 == what it should sound like (not a plug I promise)

**Comment by Reloup38** [comment]
This happens to me too, whether it is mp3 or wav, when i export a file it seems like the musesounds instruments are noticeably slower than the other kinds of instruments

**Comment by cbjeukendrup** [comment]
I think this is the same problem as #13938. As a workaround, it _could_ help to make sure that the sample rate of your currently selected speakers matches the sample rate you choose in the export dialog. Would be great if you could try that and let us know the result!

**Comment by gerrybass** [comment]
happens to me too, when recording playback via audiotool it's ok

**Comment by Tantacrul** [comment]
@DmitryArefiev / @cbjeukendrup - can you try to figure out if there's a common reason for this (sampler rate of speakers or device, etc.)

**Comment by cbjeukendrup** [comment]
I finally reproduced it! Only on **Windows** though, not yet on macOS.

1. Set system speakers to 48000Hz (for example)
2. Launch MuseScore
3. Select Muse Sounds
4. Export audio at 44100Hz (for example; in any case different from system speakers)
-> audio too slow

**Comment by cbjeukendrup** [comment]
I think it is certain now that this is the same problem as #13938. So let's close this issue, and continue the discussion in the other one!
