### ISSUE TITLE
Auto updates from MS3.6 download the Muse Hub.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#14095]
**Task description**
Auto updates from MS3.6 download the Muse Hub. Thats it!

**Comment by cbjeukendrup** [comment]
Is this still actual?

**Comment by qnebra** [comment]
> Is this still actual?

Yes. Update from 3.6.2 downloads Muse Hub.

**Comment by Tantacrul** [comment]
This is by design. 3.6.2 is the final version of MuseScore 3. It links to the Muse Hub to download version 4. In this way, there are fewer steps for the user to learn about and install Muse Sounds.
