### ISSUE TITLE
[MU4 Issue] Multiple Appoggiaturas don't play as Acciaccaturas

### ISSUE THREAD

**Issue by LuisLiszt** [musescore/MuseScore#14093]
**Describe the bug**
Affects soundfont, VST and Muse Sounds.

Appoggiaturas seem to have the logic that they should take half of the duration they are attached to. However, this means that when there are multiple appoggiaturas, the playback always causes overlap.

**Fix**
The simple fix is: **when there are more than one successive appoggiaturas, treat them as acciaccaturas.**

---

Video with comparison to MS3 (I replaced the notes in MS4 to make sure)

https://user-images.githubusercontent.com/55204261/198285520-228899a4-b1b0-4b32-99a5-4cbd26fba155.mp4

**Platform information**
 - OS: Windows

**Comment by MarcSabatella** [comment]
Because these are appoggiaturas rather than acciaccaturas, this is actually correct interpretation according to Baroque standards - appoggiaturas take half the value of the main note.  But, MuseScore 3 does make an exception for multiple appoggiaturas, to allow them to play as if they were acciaccaturas.  As far as I know, that's valid - the Baroque appoggiaturas wouldn't normally occur in groups like that.  So it could certainly be considered.

Meanwhile, the solution is to simply add them as acciaccaturas (with slash through stem, which will only appear on the first of the group, and which you can hide if you like).

See also https://github.com/musescore/MuseScore/issues/13817

**Comment by erinic04** [comment]
@MarcSabatella The first grace note is an acciaccatura, but it's still delayed. Also, it's interesting that the grace notes in the left hand aren't aligned vertically, even though they are at the same time, just in different voices.

**Comment by erinic04** [comment]
I don't have any specific problems with acciaccaturas, I just heard that the first one on the example provided wasn't played correctly.

**Comment by MarcSabatella** [comment]
Hard to Impossible to say from just the video, but again, they play fine for me in my tests.  Could be just a slight lag in the first note of playback, that much is pretty common especially with Muse Sounds.  Test again and be sure to give some lead time, and if you do continue to see a problem, please open a new issue.

**Comment by erinic04** [comment]
Fair enough

**Comment by nogramix** [comment]
@erinic04 I just tested it with a new score and indeed an Acciaccatura won't play if itt's the first note in the score! I will add it as a new issue. :)

**Comment by erinic04** [comment]
I believe that is just the issue with delayed playback right now (#13927)

**Comment by Tantacrul** [comment]
@nogramix - can you provide a link to that score so I can check myself?

**Comment by nogramix** [comment]
There you go.
[Hungarian Rhapsody 2.zip](https://github.com/musescore/MuseScore/files/9883116/Hungarian.Rhapsody.2.zip)

**Comment by Tantacrul** [comment]
@oktophonie / @bkunda - reading the above conversation... in your opinion, should acciaccaturas playback like appoggiaturas when there are multiples of them?

**Comment by MarcSabatella** [comment]
Vice versa, is what MU3 does and what I was suggesting.  That is multiple appoggiaturas should perhaps play as acciaccaturas (fast).

FWIW, I found the PR from @Jojo-Schmitz that implemented this for MuseScore 3 (3.5, to be exact): https://github.com/musescore/MuseScore/pull/4105

Looks like a one-line change plus a couple of updated tests.  The history makes it *look* like the change is in master as well, but maybe this code isn't being used anymore.

Apparently it was done specifically for bagpipe, but examples like this one make it seem more generally useful.  I might worry about other cases breaking, but it's been this way the past two years in MuseScore 3 and I don't recall any complaints.

**Comment by Tantacrul** [comment]
@MarcSabatella - yes, I swapped the words around and arrived at a nonsense statement. I've swapped them so my question now makes sense (and removed references to the mistake so as not to confuse folk!). And yes, I agree it should be done.

**Comment by oktophonie** [comment]
It doesn't really make any sense to have multiple successive appoggiaturas. (I'm sure someone will find an exception, but still.)
Really these are acciaccaturas; it is common, especially in older engraving, to see these written without a slash (only a single, flagged notes get a slash.)
So it makes sense to me to consider multiple appogs as acciaccs. Though, really, it would be better in time to have their playback independently controllable from their quantity/slashedness.

**Comment by nogramix** [comment]
Thank you! @Tantacrul @MarcSabatella @oktophonie 
Also here is an explanation by Oxford Music:

![Acciaccatura](https://user-images.githubusercontent.com/55204261/198402291-e9f32aac-a518-4038-b188-6b4875969e44.png)

Therefore it should be implemented in MS4 as well. :)

**Comment by Tantacrul** [comment]
OK, so the simple fix is: **when there are more than one successive appoggiaturas, treat them as acciaccaturas.**

**Comment by Jojo-Schmitz** [comment]
Which is exactly what my fix from #4105 did, not sure why it's not working in MU4?
The code is still in master:
https://github.com/musescore/MuseScore/blob/8b160717101f80f1fe01aa09b70408a0276fca4d/src/engraving/libmscore/rendermidi.cpp#L2011

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz The RenderMidi code is currently only still used by the MIDI export, but for playback events generation, the whole new code in `engraving/playback/` is used. So that's why it doesn't work :)
