### ISSUE TITLE
To put bars more tightly

### ISSUE THREAD

**Issue by gycguyuechen** [musescore/MuseScore#14098]
**Task description**
A short and clear description of what the task is.
![image](https://user-images.githubusercontent.com/116809984/198319061-aeff14de-99a1-4863-a67c-bf14712c9d9f.png)
As the picture, I cannot put them together, so I had no alternative but to put half of a bar in two lines.
In fact, I set an invisiable time signature of 2/4, so that I can write like this. But I hope to write two whole bars in one line. It is still unavailable, but available in other softwares like Sibelius.
If possible, I also want you to create a fuction to cut a bar in its half, so it can be in two different lines.

**Comment by MarcSabatella** [comment]
You don't need invisible time signautes, see the split & join commands in Tools / Measures, also the ability to set custom actual durations in measure Properties.  So splitting a measure across systems is easy.

From the looks of your score, it doesn't look physically possible to fit that all on one line at the page size and staff size you have chosen, so you're best best is probably to increase one or decrease the other in Format / Page Settings.  Or make the notes in that passage small using the Properties panel.  But if it *is* physically possible at the current size, it would be doable by reducing the minimum note spacing and/or other settings in Format / Style / Measure.  Also consider using the Decrease layout stretch on the measure before G.  The spacing will be inconsistent and thus incorrect, but it might help it fit.

In the future, when you have problems seeing how to use MuseScore, best to ask for help on the forums on msuescore,.org.
