### ISSUE TITLE
[MU4 Issue] Trill playback workaround no longer works at the start of measures

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#14100]
**Describe the bug**
The workaround to playback trills with accidentals (invisible note with the accidental in the second voice) no longer works at the beginning of measures.

**To Reproduce**
1. Create new score
2. Input a trilled note on the first beat
3. Input note that gives the trill an accidental
4. Hear that the trill doesn't respect the accidental

**Expected behavior**
The trills should respect the accidental

**Screenshots**
<img width="78" alt="Screen Shot 2022-10-27 at 9 16 03 AM" src="https://user-images.githubusercontent.com/21023353/198329611-091e5096-6919-437d-b455-130799ce0640.png">

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**
As far as I know, there is currently no way to get these types of trills to play back correctly other than changing the key signature.

**Comment by Tantacrul** [comment]
The way to fix this properly is to just provide options to specify how many semitones a trill should cover in the Properties panel (as well as allowing for accidental markings on the score that affect playback). This is on our shortlist for MS4.1

**Comment by erinic04** [comment]
Something like this would be awesome #11686

**Comment by zacjansheski** [comment]
Closing as fixed with our new ornaments features
