### ISSUE TITLE
[MU4 Issue] Trill Line trills the notes before and after the line

### ISSUE THREAD

**Issue by nogramix** [musescore/MuseScore#14105]
**Describe the bug**
The Trill Line doesn't only trill the assigned notes, it additionally trills the note before and after the trill line begins/ends. Even if those notes are in a different bar. This isnt't the case with the normal "Trill" ornament, as shown in the video. The problem occurs with MS Basic and MuseSounds.

**To Reproduce**
1. Open a new score.
2. Arrange notes like shown in the video.

**Expected behavior**
Trill line should only trill the notes it's assigned to.

**Screenshots**

https://user-images.githubusercontent.com/55204261/198336693-b9bd0c8c-35df-4e84-a994-ab3e6b9263f5.mp4

**Platform information**
 - OS: Windows

**Comment by cbjeukendrup** [comment]
I can indeed confirm that this was broken in the Beta, but fixed in the latest master branch / latest nightly. So this has already been solved. Thanks for reporting though!

**Comment by nogramix** [comment]
Oh, I didn't know we had access to the development builds, so I just downloaded the latest Beta via MuseHub, thanks for letting me know!

**Comment by cbjeukendrup** [comment]
For how to access these development builds, see: https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-nightly-builds 🙂
