### ISSUE TITLE
[MU4 Issue] Shortcut for Sharp doesn’t apply Sharp in Flat Key Signatures even to notes that aren’t flat 

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#14101]
**Describe the bug**
I’m not sure if this is a bug or not, but I’ve noticed this when trying to put in any score with sharps notated on the note rather than in the key signature, at least in key signatures with flats, I haven’t tested out sharp keys yet to see if it makes a difference. But I should be able to like enter in an F# in Bb major by going + F and I can’t, I have to use the accidentals palate  or the up arrow key for F#.

**To Reproduce**
1. Make a score with a flat key signature 
2. Press +
4. See that it maps to natural 

**Expected behavior**
I would have expected it to possibly highlight both natural and sharp or maybe to not highlight at all until the note is entered in so that say + B gives me B natural but + F gives me F# in a key like Bb major.

**Screenshots**

**Platform information**
 - Windows 10

**Additional context**

**Comment by erinic04** [comment]
make sure you are using + instead of = for this, = is natural shortcut (I don't have this problem), see if the sharp is selected in the toolbar when entering the note

**Comment by DaddyLudwig** [comment]
Okay, I thought I was pressing +, but I guess I wasn’t, or rather I wasn’t doing the shift to get it to change from = to + or it somehow wasn’t registering it cause that sometimes happens, that I’ll like press a key and it doesn’t register. So I’ll close this.
