### ISSUE TITLE
Suggestion: Progress bar and timer shouldn't reset after a repetion measure

### ISSUE THREAD

**Issue by LuisLiszt** [musescore/MuseScore#14117]
**How it is right now**

When a repetition measure is passed and the passage plays again, the progress bar and the timer will set back to the beginning state of the passage. (It's hard to explain - watch the video as an example, pay attention to the timer (top right corner)).

https://user-images.githubusercontent.com/55204261/198410222-e53fbfec-4199-439b-ad2a-a8fcc4d463ee.mp4

**How it should be - and why**

The timer should continue to run normally, the progress bar as well.
This would enable the user to track the length of the whole score and it would be possible to fast forward and hear the transition between the passages much faster and frequent (while composing), without having to hear the whole first passage - like it is now in MS4 and was in MS3.
Especially with a long passage which is repeated, it is very annoying, because you have to hear this full passage in order to hear the transition to the new passage after the repetition measure.
And yes - you can turn off that repetitions play, but when you have Voltas (like in Für Elise), this isn't an option neither.

It would make working with MuseScore much easier and enjoyable.

I hope it'll be considered.

**Comment by SteveBlower** [comment]
Already reported in #14064.
