### ISSUE TITLE
[Muse Sound[ Flute 1 freezes MuseScore

### ISSUE THREAD

**Issue by sberla365** [musescore/MuseScore#14114]
Switching to Muse Sounds Flute 1 freezes Muse Score. The app becomes unresponsive and stops playback. It is possible to close the open score and have the save dialogue but opening another score without actually closing Muse Score keeps the app unresponsive.

To reproduce:

1. Open a score with flute
2. Go to mixer and select Flute 1

Flute 2 does not produce this issue though.

I encountered this on Linux (Fedora 36 and Ubuntu 22.04)

**Comment by MarcSabatella** [comment]
If you start MuseScore from a console window, you will probably see that there is an error message and it is waiting for you to give input.  Type "A" and hit Enter and then things unfreeze.

This is the same (critical) bug as in https://github.com/musescore/MuseScore/issues/13959, https://github.com/musescore/MuseScore/issues/13915, https://github.com/musescore/MuseScore/issues/13922, and probably others.

**Comment by Tantacrul** [comment]
Dmitri can you check this on your Linux machine to replicate the issue?

**Comment by MarcSabatella** [comment]
As per https://github.com/musescore/MuseScore/issues/13959#issuecomment-1290817060 it sounds like this is understood already?

**Comment by sberla365** [comment]
No more freezes after recent Muse Sounds updates
