### ISSUE TITLE
Double dotted duration

### ISSUE THREAD

**Issue by amijaishalev** [musescore/MuseScore#14112]
I Can't find the double dotted duration.
Not sure if it has been eliminated...

**Platform information**
MacOS

**Comment by oktophonie** [comment]
Click the cog in the toolbar to customise it. Scroll down to the find the double dot, and click the eye symbol to the left to display it in the toolbar:

![image](https://user-images.githubusercontent.com/20604032/198368883-fcd98693-2554-4813-9f4b-cc57e181a92a.png)

Hope that helps! In future, this type of request would be better sent to the support forum on musescore.org.

**Comment by amijaishalev** [comment]
Thanks!
