### ISSUE TITLE
[MU4 Issue] Muse Sounds - when in note input mode sounds no reverb, when playing on playback there is reverb

### ISSUE THREAD

**Issue by maestroharmony** [musescore/MuseScore#14113]
**Describe the bug**
The bug occurs when on note input mode. There is no reverb attached to the sample the way it does in playback.

**To Reproduce**
1. Open a score in MU4
2. Start inputting notes randomly in the staff with the note input mode
3. Hear no reverb when inputting notes
4. Play the playback
5. There is now reverb

**Expected behavior**
There should be reverb when inputting notes and not sounding too dry/no reverb at all.

**Platform information**
Windows 11 latest update, R7 3700x 32 Gb RAM

**Comment by Tantacrul** [comment]
This is not going to be fixed in MS4.0 or any time soon. The note input works differently to the sampler playback. Closing as a won't fix.
