### ISSUE TITLE
[MU4 Issue] Exported audio should ignore selection and always export full score audio

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#14123]
**Describe the bug**
If you happen to have a range selected when you publish to musescore.com, only the select staves are exported

**To Reproduce**
1. Open a score for multiple instruments
2. Select one measure in one instrument
3. File / Export or File / Publish to musescore.com
4. Listen to exported/published score
6. Hear error: only the select staff plays

**Expected behavior**
Full score should play

**Additional context**
The feature of soloing selected staves is nice although still a bit divisive in that many of us continue to accidentally invoke it because it's so much easier to select a measure rather than a note to start playback.  But, at least we realize our mistake instantly when we don't hear what we expect.  Whereas, when exporting audio or publishing to musescore.com, it might literally take an hour to export the audio for a large score with Muse Sounds, and it's *incredibly* frustrating to then realize we have to redo it.  I would claim that as useful as soloing staves by selection might be, it should be ignored for export / publish.

**Comment by Zanctarian** [comment]
It'd be nice for expandability upon that feature as well. I get so frustrated when I accidentally click the measure instead of the note! It'd be nice to be able to click, lets say, the instrument name on the left side instead.. or at the very least a toggle to enable or disable the feature!

**Comment by DaddyLudwig** [comment]
I tend to click on the measure too as force of habit from earlier MuseScore versions.

**Comment by cbjeukendrup** [comment]
I'll work on this, this is a pretty bad bug and also affects score uploading to .com.

@Tantacrul Extra question: should solo/mute state in the Mixer be honoured by audio export?

**Comment by teetow** [comment]
> Extra question: should solo/mute state in the Mixer be honoured by audio export?
It's a reasonable expectation, especially if you're looking to export a "no soloist" version, for example. This would be a lot of extra work otherwise -- exporting separated tracks and re-assembling them in a DAW.

**Comment by Tantacrul** [comment]
Solo / Mute should absolutely be respected and I agree 100% that selection should have no bearing on what is exported.

**Comment by cbjeukendrup** [comment]
Okay. That's what #14129 does :)

**Comment by MarcSabatella** [comment]
FWIW, in MU3, mute is respected for export but not solo.  That was by design, as there was at one time a consensus that mute is sometime you do with intent to make it permanent but solo is something you are probably just doing temporarily.  But this never felt right in practice and generated complaints occasionally from people who want solo to be respected even when used temporarily - the whole point might have been to generate audio.  So I approve of seeing solo respected in MU4.

**Comment by Tantacrul** [comment]
Yeah, I think that MS3 behaviour should be reversed for multiple reasons. I won't bother going into it because we're already changing it. However, if a user is confused by exporting with solo switched on - it's a one-time confusion. They'll understand after that.

**Comment by Tantacrul** [comment]
Actually cannot wait for this one to be fixed. It keeps catching me out 😄

**Comment by DmitryArefiev** [comment]
Fixed in #14129

**Comment by DmitryArefiev** [comment]
@MarcSabatella Please check it briefly on your side if I missed something

https://github.com/musescore/MuseScore/pull/14129

Thanks!
