### ISSUE TITLE
[MU4 Issue] Muse Hub locks up when trying to connect to Muse Helper.

### ISSUE THREAD

**Issue by John7482** [musescore/MuseScore#14125]
**Describe the bug**
Muse Hub freezes after clicking on "Connect" with the "Muse Hub helper service is not running" error and clicking on any "Apps" or "Muse Sounds".

**To Reproduce**
1. Install Muse Hub.
2. Open the Muse Hub window.
3. See error that pops up on the bottom saying "Muse Hub helper service is not running" and a button labeled "Connect".
4. Click "Connect".
5. "Connect" is greyed out.
6. Click on something to install (e.g. Musescore).
7. Muse Hub freezes.

**Expected behavior**
I expected Muse Hub to be able to connect to this helper service sucessfully, allowing me to install Apps and Muse Sounds.

**Video**
https://user-images.githubusercontent.com/109434278/198459630-bf967216-0f9d-4a02-8750-ebb327edff03.mp4

**Platform information**
 - OS: Windows 11 Home 21H2 Build 22000.978

**Additional context**
- Before clicking on "Connect", I am able to go within the menus (e.g. clicking on a Muse Sound shows its installation menu), however it does not do anything when I click on the button labeled "Get". Along with this, clicking on "Musescore" in "Apps" does not do anything either.
- Clicking on "Connect" and waiting does not do anything.
- You can quit Muse Hub after this bug by right clicking on its tray icon and selecting "Quit", but this doesn't fully close the app; it lingers in the background. You have to go into Task Manager in order to fully restart Muse Hub, allowing it to be opened again.

**Comment by SteveBlower** [comment]
Seems to be the same or similar to #14000.  However, it is not clear to me what Muse.Service.exe actually does and under what circumstances it is _meant_ to start or stop.  I'll leave it to someone else to judge how related these two issues are.

**Comment by iamtesch** [comment]
It seems that the service (which manages the actual downloads and cache for the UI) wasn't installed/starting properly here.  Can you try to uninstall the Hub and then reinstall the latest version, and let me know if this still occurs?

We'll work on reducing the instability if the service can't be connected to, though

**Comment by John7482** [comment]
@iamtesch - This bug is still occurring for me after uninstalling Muse Hub and installing the latest version grabbed from the [Muse Hub website](https://www.musehub.com/).

**Comment by John7482** [comment]
Hi everyone, checking back today and it seems like my issue has been fixed. I downloaded the latest version from the Muse Hub website and now I can download Muse Sounds and Musescore 4 now. There are no errors while downloading as well.
