### ISSUE TITLE
[MU4 Issue] Gradual tempo changes do not change tempo gradually (need more fine-tuning control)

### ISSUE THREAD

**Issue by woooowoooo** [musescore/MuseScore#14122]
**Describe the bug**
Gradual tempo changes, such as ritardando, rallentando, and so on only change tempo exactly four times, instead of changing gradually as would be expected. As an example, a rallentando over five measures would change tempo exactly once per 1.25 measures.

I have been informed that this is intentional in the sense that it is what the code is intended to do, but this behavior is not the intent of such markings, and therefore I believe this is still considered a bug.

**To Reproduce**
1. Create or import a score
2. Over a range of music, create a gradual tempo change (accel., allarg., rall., rit.)
3. (Optional) Fiddle with the tempo change settings in Properties > Playback to make the effect more noticeable (try changing "Amount" to 1%) (0% renders nothing playable but that's a separate issue)
4. Play the music: you should be able to hear the change happening at those selected areas but you can also  look at the top right, at the BPM indicator, to see it

**Expected behavior**
The tempo changes gradually over the course of the playback.

**Platform information**
 - OS: Linux Mint 21

**Comment by jeetee** [comment]
The approach used in the TempoChanges plugin for 3.x was to apply the gradual change on every existing segment between start and end. I can understand not wanting to flood tempo messages, but 4 changes over a multiple measure range is just too coarse.

**Comment by DmitryArefiev** [comment]
Looks the same as #21115

@woooowoooo Please try #23879. If it's not good please reopen the current bug
