### ISSUE TITLE
[MU4 Issue] Musescore 4 crashed or kept not-responding when opening a .mid or .MID file

### ISSUE THREAD

**Issue by GOTLTL** [musescore/MuseScore#14127]
**Describe the bug**
Musescore 4 crashed or kept not-responding when opening a .MID or .MIDI file. These files opened normally in Musescore 3 without causing any issues.

**To Reproduce**
1. Open Musescore 4 Beta
2. Click File > Open 
3. Select a .mid or .MID file (feel free to use midi files in attached)

**Expected behavior**
Musescore will crash outright, or stay loading and start Not Responding.

**Platform information**
 - OS: Windows 10 Home 64-bit (Build 19044)
 - PC Info: Ryzen 7 3800X, 64GB DDR4 3200 MHz, rtx 3070.

**Attachment**
[Musescore 4 crashing MIDI.zip](https://github.com/musescore/MuseScore/files/9885501/Musescore.4.crashing.MIDI.zip)

**Comment by Eism** [comment]
Thank you for reporting. 
I fixed this bug. Please check the nightly build
https://github.com/musescore/MuseScore/suites/9006002660/artifacts/415001967

**Comment by GOTLTL** [comment]
confirm fixed in the build! tyvm!
