### ISSUE TITLE
[MU4 Issue] - Consecutive accents sounds weird in Choir voices

### ISSUE THREAD

**Issue by JesWagner** [musescore/MuseScore#14130]
**Describe the bug**
Notes with accents (>) sounds really weird 

**To Reproduce**
1. Bass voice from measure 35 in this piece: [http://www.cafe-puccini.dk/Puccini/Gloria/musescore/01_Kyrie.mscz](url)

**Expected behavior**
More destinct sound with little 'space' between notes

**Platform information**
 - OS: Windows 10.

**Additional context**
N/A

**Comment by Tantacrul** [comment]
This isn't really actionable because we don't have enough information on what is weird and what could be better. Moreover, it's not something that's going to be changed in the near term.
