### ISSUE TITLE
[MU4 Issue] Crash when doing ctrl+R on let ring or palm mute lines

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#14135]
**Describe the bug**
Crash when doing ctrl+R on let ring or palm mute lines.

https://user-images.githubusercontent.com/93707756/198589723-ba1ad966-a6d5-4644-9add-81416688d5ce.mp4

**Comment by cbjeukendrup** [comment]
Is this a duplicate of #13670 (which in turn is a sort-of-duplicate of #13500)?

**Comment by mike-spa** [comment]
Ha! Yes, definitely. Sorry I hadn't realized that
