### ISSUE TITLE
[MU4 Issue] Impossible to use Publish mode in imported Scores

### ISSUE THREAD

**Issue by charlesneimog** [musescore/MuseScore#14138]
**Describe the bug**
Musescore crash when I try to use the `Publish` mode in imported Scores, from Sibelius. If I edit the Musicxml file, edit it and save as a Musescore file the problem persists.

**To Reproduce**
1. Export a Musicxml file from Sibelius.
2. Read it in Musescore 4.
3. Click in Publish mode.

**Screenshots**

Importing File: 

https://user-images.githubusercontent.com/31707161/198611255-12f288ba-0245-469d-a58a-348d5516ac6d.mp4

________________________________
________________________________
**This is the more serious problem...** A imported musicxml file, but already edited and saved as a Musescore File.

https://user-images.githubusercontent.com/31707161/198611952-388ee614-54c3-4d34-965f-f6b181de9c09.mp4

**Platform information**
 - OS: Windows 11

**Comment by DmitryArefiev** [comment]
@charlesneimog Hi, I can't reproduce on my side.. Can you attach that musicxml file here? (it can be excerpt from score)

Thanks!

**Comment by charlesneimog** [comment]
Yes!

A scale of C4 to C5 not work here too...

[C4 to C5.zip](https://github.com/musescore/MuseScore/files/9889178/C4.to.C5.zip)
[Estudo no. 1 - Piano.zip](https://github.com/musescore/MuseScore/files/9889179/Estudo.no.1.-.Piano.zip)

**Comment by DmitryArefiev** [comment]
Strange.. I still can't reproduce it using your files.. (beta build or latest master build on Windows10)

https://user-images.githubusercontent.com/90187801/198656007-1b7938b0-0d93-4d64-9d84-0fb127256d9e.mp4

What build are using? 
Maybe you can do Factory reset and try again? (but you will lose recent score list)

**Comment by charlesneimog** [comment]
I am using the beta build. 

![image](https://user-images.githubusercontent.com/31707161/198666231-525c192a-421a-4e51-a63b-d7cd5b2ed897.png)

I will try to Download the latest master.

**Comment by DmitryArefiev** [comment]
Yes, please try on master. Thanks!

**Comment by charlesneimog** [comment]
Sorry for wasting your time., it is working of master!

**Comment by DmitryArefiev** [comment]
Oh cool!
