### ISSUE TITLE
[MU4 Issue] MuseScore's `libssl` and `libcrypto` depend on `msvcr100.dll` but some people don't have that

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#14144]
In order to make https connections (which Qt does for us), MuseScore depends on `libssl` and `libcrypto`. These libraries are packaged with MuseScore. 

The problem is that these libraries depend on a DLL file called `msvcr100.dll`, which should live in `C:\Windows\System32\`. It turns out that some people don't have this file, for unknown reasons. 

Symptoms:
- Can't log in with MuseScore.com account in MuseScore desktop
- Videos in Learn page are not loaded even though Internet connection is okay
- "Publish to MuseScore.com" always gives "Could not connect to MuseScore.com" or similar

There have been two reports of this so far, one by @bkunda (which we solved by copying my `msvcr100.dll` to his virtual machine) and one on Discord.

I googled a bit for `msvcr100.dll`, and it seems to be part of "Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package MFC Security Update" (https://www.microsoft.com/en-us/download/details.aspx?id=26999). 
So that's something from 2010. 

So, I wondered: **Can we package a newer version of `libssl` and `libcrypto` that does not depend on `msvcr100.dll`?**

(These newer libraries will need to be uploaded to https://s3.amazonaws.com/utils.musescore.org/dependencies.7z because that's where they are downloaded from during the build process. The dependencies of libraries can be checked using the `dumpbin` command; see also https://github.com/musescore/MuseScore/pull/13859#issuecomment-1292308928.)

**Comment by cbjeukendrup** [comment]
@igorkorsukov Is this something you could help with?

**Comment by Tantacrul** [comment]
So, to clarify, do we think there's a danger of this happening 'in the wild', among regular users (not community testers & contributors)?

I'm asking so we can make a call about whether to address it for release or not.

**Comment by cbjeukendrup** [comment]
That's right. We have currently no view of how widespread the problem of missing `msvcr100.dll` is among Windows users. Apparently not _very_, since we have had only two reports of it so far, but still I think that's significant. And the number of webpages describing "how to get that dll file if it is missing" might also mean that this quite a common problem. 

Downloading the missing dll file is not that difficult, but the problem is that it is impossible for a user to realise that the inability to login is caused by some missing system dll file. There is absolutely no indication that this is what's happening. Unless we start doing really hacky things, it is also not possible for MuseScore itself to know that the dll file is missing, because this is all handled deep inside Qt and Windows. 

So if possible, I would recommend to find a solution without this problematic dll file.

**Comment by Tantacrul** [comment]
OK, I'll pop it in Release for now and we can assess.

**Comment by Tantacrul** [comment]
This issue was also reported by this user and replacing the missing **msvcr100.dll** fixed the issue.
https://github.com/musescore/MuseScore/issues/14246

**Comment by AntonioBL** [comment]
@cbjeukendrup :
Ciao,
I tried to compile openssl under Windows by manually changing the makefile (obtained with the configure script) to include the "/MT" flag (i.e. to use the static version of the runtime libraries) instead of "/MD". When not changing the makefile, crt runtime dlls were listed as dependencies of the output dlls.
Such "/MT"-built openssl does not pass all the tests ("nmake tests"), but when used in the `bin` folder of a nightly build, it seems to behave properly: the videos are loaded in the dashboard page.
Attached you can find those two dlls. Since they include a static version of the runtime libraries, they are larger than the dlls normally used in MuseScore.
In case, I think they need thourough testing before including them in MuseScore.
Ciao,
ABL

[libssl_libcrypto.zip](https://github.com/musescore/MuseScore/files/9940330/libssl_libcrypto.zip)

**Comment by Eism** [comment]
I just placed the libs collected by Antonio to dependencies.
You can check on this build 
https://github.com/musescore/MuseScore/actions/runs/3435543846

Works for me without msvcr100.dll in C:\Windows\System32\ 

Please check someone else, after that we will close the issue.

@AntonioBL thanks!

**Comment by cbjeukendrup** [comment]
Seems to work for me too, with and without msvcr100.dll!
