### ISSUE TITLE
[MU4 Improvement] Instrument selection not clear for new/first time use

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#14150]
**Describe the bug**
Some instruments have the option to select a different key while others don't. Excellent!
However when these are combined in the same dialog it is not clear which key is used for the instruments that do not have this selection option.
In my example I search for tuba and get several results. From the first step, I can't tell which key is used for the Bass Tuba (treble clef).
I need to select the instrument first, then look at the bottom of the dialog so see the extra information or add the instrument to the score and see it automatically add the "in Eb" text.
With this design it also feels as if there are options missing. I.e. why the different keys for the Bass Tuba but not for the Bass Tuba (treble clef)? 
I am sure there are more instruments which have this.

**To Reproduce**
1. Create a new score
2. In "choose instruments" search for tuba
3. Check the screen

**Expected behavior**
Make the key used for the instruments more obvious in the dialog. Perhaps just always show the key (even if there is only 1 option)?

**Screenshots**
![image](https://user-images.githubusercontent.com/13550012/198694349-e086b433-7b3c-4d40-bc21-92804608448f.png)

**Platform information**
 - OS: Windows 10

**Additional context**

**Comment by SteveBlower** [comment]
I noticed the same thing for "Clarinet" in the Woodwind section of the "Common" instrument list.  When added to the score it becomes clear that it is a Bb clarinet.  It would be better/clearer if the Common instrument list had it as Bb clarinet as is the case in MuseScore 3

**Comment by Tantacrul** [comment]
@oktophonie to comment, assign or close as you see fit.

**Comment by oktophonie** [comment]
Yes, it would be better to show the transposition for instruments which have multiple transpositions in the full list, but where only one is shown in 'Common'. (The transposition was a part of the instrument name in MU3, so it was shown then.)

It's not necessary for instruments where the default transposition is not shown in the score (those which, in the instruments spreadsheet, have () around the transposition in the `traitName`), i.e. Piccolo, Bass Clarinet.

So in the 'Instruments' column it should the names as they appear in 'Your score', once added, i.e.:

- Clarinet in Bb
- Cornet in Bb
- Horn in F
- Trumpet in Bb

(Though I wonder whether our 'Common' trumpet should be in C, which is the default transposition in the full list.)

This addresses @SteveBlower's point but not @henkdegroot's really; the tuba issue is a rather intractable one.

**Comment by henkdegroot** [comment]
It looks like that when you "search" for an instrument, you always use the full list. So thinking that adding/showing the transposition when the full list is used could work for tuba as well.

**Comment by henkdegroot** [comment]
@SteveBlower, that would be an excellent solution for me :) As a Contrabass Tuba isn't really a thing/name used in brass band world as well (back in July I already reported an issue about that and thought my tuba was missing....just wasn't aware of the name being used).
