### ISSUE TITLE
[MU4 Issue] Request: Add fretting hand fingering numbers to fretboard diagrams

### ISSUE THREAD

**Issue by sisyphusmc** [musescore/MuseScore#14152]
It would be useful to be able to add fingering numbers for the fretting hand under the dots on fretboard diagrams.

![d7-chord](https://user-images.githubusercontent.com/76957788/198715118-33c33ea1-3da0-483c-a8eb-ac818241991a.png)

**Comment by scorster** [comment]
https://musescore.org/en/node/313074
