### ISSUE TITLE
[MU4 Issue] Pressing "T" to add tie in note input mode does not play note

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#14153]
**Describe the bug**
Pressing "T" to add a tie should give audible confirmation of the note added, but does not in MU4 (regression from MU3)

**To Reproduce**
1. new score
2. add a note
3. still in note input mode, press "T"
4. hear error: newly added note does not play

**Expected behavior**
Note should play when added

**Additional context**
It's moderately annoying to me, but is really bad for blind users

**Comment by rgreen5** [comment]
Same as #13687.

**Comment by MarcSabatella** [comment]
Thanks, somehow I didn't see that in my search
