### ISSUE TITLE
[MU4 Issue] Segfault when attempting to copy-paste beam (crash)

### ISSUE THREAD

**Issue by 4gboframram** [musescore/MuseScore#14159]
**Describe the bug**
Musescore crashes with a segfault when attempting to paste the beam of a beamed note

**To Reproduce**
1. Create a new score
2. Add 2 consecutive eighth notes
3. Select the beam of the eighth notes and press Ctrl + C
4. Press Ctrl + V
5. See error

**Expected behavior**
Attempting to copy-paste a beam should not cause Musescore to crash, but should do nothing

**Screenshots**
[beam.log](https://github.com/musescore/MuseScore/files/9892573/beam.log)
[core dump](https://www.mediafire.com/file/nf0n7ze6m6p813m/core.zip/file)

**Platform information**
 - Debian 11 Bullseye, Linux kernel 5.10.0-8-amd64

**Additional context**

**Comment by DmitryArefiev** [comment]
@4gboframram Yes, that's negative scenario but it crashes MU! Thanks for logging!

 Can reproduce on my side

https://user-images.githubusercontent.com/90187801/199535508-e9e5b336-8146-459e-a5ca-34b40471ebe4.mp4

**Comment by cbjeukendrup** [comment]
@DmitryArefiev Thanks! I already have a PR to fix this, that's waiting for code review: #13410
