### ISSUE TITLE
[MU4 Issue] Ties in tablature are positioned the wrong way round

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#14160]
**Describe the bug**

It appears that MS4 is setting the position (above/below) of ties in tablature wrongly – at least in imported MS3 files. e.g.

MS3
![ms3_slur](https://user-images.githubusercontent.com/87246583/198825037-fefc30ce-46db-446b-a0c0-a26532f26ab6.png)

MS4
![ms4_slur](https://user-images.githubusercontent.com/87246583/198825047-80632fb8-9353-4bb2-bc31-a3065d718085.png)

**To Reproduce**

1. Open the attached MS3 file in both MS3 and MS4. 
[ties_wrong_way.mscz.zip](https://github.com/musescore/MuseScore/files/9893561/ties_wrong_way.mscz.zip)

2. Compare and contrast the positions of ties in mm 1,2,3, and 4.

RESULT: The ties which were correctly oriented upwards in MS3, now point downwards.

**Expected behavior**

Ties should be correctly oriented by default, as they were in MS3 (and should respect positions set in MS3).

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223020418, revision: github-musescore-musescore-fa12b58

**Comment by cbjeukendrup** [comment]
I think you mean ties, don't you? Or both ties and slurs?

**Comment by rgreen5** [comment]
Oops. Have corrected post and title.

**Comment by asattely** [comment]
This does indeed seem to be an issue with imported previous-version files. '6-str. simple' staves should not show ties at all, and if you change the staff type to 'common' and then back to 'simple' it's fixed. I'll go through the import code and see if I can find the culprit.

**Comment by rgreen5** [comment]
See also, #12530.
