### ISSUE TITLE
[MU4 Issue] Close Tab on second instance close 2nd instance MuseScore

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14166]
- Open a score MS4, Instance 1
- Open a new score create a new Instance 2
- I want to Close tab of instance 2  because i want open new score result : close Instance 2, expected : open a new score
- Close Instance 1 tab, close only Tab

**Comment by Tantacrul** [comment]
This one has been reported numerous times. Duplication.
