### ISSUE TITLE
[MU4 Issue] Exporting mp3 to Onedrive folder crashes musescore

### ISSUE THREAD

**Issue by sikamber** [musescore/MuseScore#14169]
**Describe the bug**
When I try to export a score to mp3 and save it in my onedrive folder, the program crashes to desktop when the progress bar reaches 80%. An mp3 file is created, but the file is unplayable. Exporting to another folder works fine.

**To Reproduce**
1. Export export mp3 file
2. Choose a folder within a onedrive (mine has cloud sync available, but I am unsure if that has affected the issue)

**Expected behavior**
I expected the program to create am mp3 file and stay open

**Platform information**
 - OS: Windows 10

**Additional context**
After my first crash, musescore became unresponsive on the "new and recent scores" window when I opened it again. I can bypass this issue by opening a second copy of Musescore with the unresponsive one in the background. I don't know if the two issues are related.

**Comment by sikamber** [comment]
Huh, I can't reproduce the issue anymore. I can't tell what the difference is. It was quite consistent earlier today, but now everything seems in order. 

What is proper procedure then? Do I close the issue?

**Comment by Tantacrul** [comment]
I'll close it. Thanks very much!
