### ISSUE TITLE
[MU4 Issue] Crash when trying to enter a rest in note-input mode while the accent articulation is selected.

### ISSUE THREAD

**Issue by AdamAViolist** [musescore/MuseScore#14174]
**Describe the bug**
Whenever you want to enter notes with an accent, you would press ctrl+V and then enter the note. However, if you want to add rests between the notes, you must deselect the accent to avoid a crash.

**To Reproduce**
1. Open a new/existing score
2. Enter note-input mode
3. Use command Ctrl+V or click on the accent in the toolbar
4. Press 0 to enter a rest
5. See crash

**Expected behavior**
It is expected that a rest should be entered, regardless of whether any articulation is selected. It would make sense to keep the workflow moving.

**Platform information**
 - OS: Windows 11 64 bit, x64-based processor

**Comment by cbjeukendrup** [comment]
This looks similar to #13740, which was fixed in #13746. Could you please test if this still happens in the latest nightly builds? (See https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-nightly-builds)

**Comment by AdamAViolist** [comment]
> This looks similar to #13740, which was fixed in #13746. Could you please test if this still happens in the latest nightly builds? (See https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-nightly-builds)
> 
> Also, I think Ctrl+V for accents is a custom shortcut of yours, isn't it? By default this is "paste".

My bad I'm all over the place recently. This does not happen in the latest nightly I apologize; I was using the MuseHub beta and didn't check the recent build. And yes I meant to put Shift+V instead of Ctrl+V. This issue should be ignored. :)

**Comment by cbjeukendrup** [comment]
Ah, no problem at all! So let's close this as completed :)
