### ISSUE TITLE
[MU4 Issue] You cannot see the 'play' checkbox while in a part score

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#14179]
**Describe the bug**
While you are in a part score, you cannot see the checkbox for play in the properties panel.

**To Reproduce**
1. Open a score
2. Go into a part
3. Select note in part
4. See no play checkbox

**Expected behavior**
There should be a play checkbox

**Screenshots**
In part:
![aaaaaaaa](https://user-images.githubusercontent.com/21023353/198864439-b337d4c6-286d-4293-9e07-cb94cda8b913.png)

In full score:
![aaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/21023353/198864448-25855c38-b2f6-4d90-ac98-2dbeadd0ad94.png)

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by Tantacrul** [comment]
This is by design. The playback is handled from the main score and it causes major complications to have potentially competing 'Play' options in part scores. This was also true of MS3.
