### ISSUE TITLE
[MU4 Issue] Pizzicato from MU3 played as arco in MU4

### ISSUE THREAD

**Issue by SamYeh** [musescore/MuseScore#14175]
**Describe the bug**
Pizzicato in MU3 is played as arco in MU4.

**To Reproduce**
1. Create a score with pizzicato using MU3. Example (violins):
![Pizzicato Test](https://user-images.githubusercontent.com/10248807/198859812-9ae73617-e9b4-46a7-a8d2-db482683bac8.png)

2. Open the score in MU4 and play it.

**Expected behavior**
Pizzicato should sound like pizzicato.

**Platform information**
 - OS: Windows 11

**Comment by SamYeh** [comment]
![Pizzicato Test](https://user-images.githubusercontent.com/10248807/198859796-603c8282-7006-481b-ad69-0da2140eebc8.png)

**Comment by erinic04** [comment]
This is already reported and being worked on.

**Comment by erinic04** [comment]
#13567 apparently it's supposed to be fixed already

**Comment by SamYeh** [comment]
Duplicate of #13912
