### ISSUE TITLE
[MU4 Issue] Special characters in exported file names causes odd behavior

### ISSUE THREAD

**Issue by sikamber** [musescore/MuseScore#14173]
**Describe the bug**
When exporting audio to a file with special characters in the name (such as the danish "ø" character), Musescore creates two files: One file which has the right name, but which is empty (0 bytes), and one file with a distorted character but proper audio contents

**To Reproduce**
1. Choose "file->export"
2. Choose an audio format and click "Export..."
3. Choose a filename with a special character

**Expected behavior**
I expected one sound file with the chosen file name.

**Screenshots**
In the screenshot, the right file has the filename I chose, but that file is empty. The left one plays properly:
![image](https://user-images.githubusercontent.com/28673463/198851335-bad4757b-f6a7-49bd-ad24-e7f72013df97.png)

**Platform information**
 - OS: Windows

**Additional context**
I tested with FLAC and MP3 files, and both had the same problem. I did not get the same issue when exporting to PDF.
When I look at the timestamp on the files, they are created at the same time, but one of them (the one with the distorted name and actual contents) is modified a bit later.

**Comment by cbjeukendrup** [comment]
According to #14913, there is also sometimes a crash, but that might also be the crash from #14765.

**Comment by Tantacrul** [comment]
@sikamber can you please check this issue on this build?

https://github.com/musescore/MuseScore/suites/9677220380/artifacts/463337181

**Comment by sikamber** [comment]
> @sikamber can you please check this issue on this build?
> 
> https://github.com/musescore/MuseScore/suites/9677220380/artifacts/463337181

@Tantacrul That one seems to work properly
