### ISSUE TITLE
[MU4 Issue] Muse Hub can't open.

### ISSUE THREAD

**Issue by Slightly2** [musescore/MuseScore#14178]
**Describe the bug**
Muse Hub does not open after it is installed. Attempting to run the muse.exe file returns an error: "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item."
I have attempted to solve this problem by changing the ownership of Muse.exe and every other file in its folder. While this does fix the error message, nothing happens when running the program and Muse Hub does not open. According to task manager, the Muse Hub service is running. However, it only starts when running the installer exe. Running Muse.Service.exe returns the error.

**To Reproduce**
I don't think that this issue is able to be reproduced, and I may just be doing something wrong.
But what I've done to get this behavior is:
1. Download the Muse Hub installer from the dropbox link (https://www.dropbox.com/s/424y9t5ej5hz6sa/Muse_Hub_Win.zip?dl=1)
2. Unzip the folder and run the executable.
3. Muse Hub should open after it finishes installing. This doesn't happen.
4. Attempt to manually run Muse.exe or Muse.Service.exe, causing the Windows error.

**Expected behavior**
After running the Muse Hub installer, it should just open. Well, this is what I think would happen, but I haven't managed to successfully use Muse Hub yet.

**Platform information**
 - OS: Windows 10 Pro 64 Bit
 - Version: 10.0.19043 Build 19043

**Comment by Tantacrul** [comment]
Have you been able to install the MuseHub since?

I'd recommend uninstalling the Muse Hub and all versions of MS4 and then downloading it from here: https://www.musehub.com/

And reinstalling the hub and trying again. Thanks!

**Comment by oktophonie** [comment]
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.
