### ISSUE TITLE
[MU4 Issue] Notes playing twice when selecting an option from palettes

### ISSUE THREAD

**Issue by BenignPigeon** [musescore/MuseScore#14189]
**Describe the bug**
The note are playing twice when selecting a dynamic or articulation option from palettes when it isn't the first note selected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on a note
2. Click on a different note
3. Then select a dynamic or articulation
4. The note will play twice instead of once

**Expected behavior**
The note should playback once or no times at all.

**Platform information**
 - OS: Windows 11 on MS4 Beta

**Additional context**
The problem does not occur if the note is the first one selected, as shown in the video.

**Screenshots**

Please watch in it's entirety to see the bug

https://user-images.githubusercontent.com/85837722/198884755-c03f3ec4-89e5-4341-8bb9-d37030f04940.mp4

**Comment by cbjeukendrup** [comment]
I think that in the end this is related to #13814. Let's leave both open for now, but when one is fixed, we should definitely retest the other.

**Comment by BenignPigeon** [comment]
It looks rather similar since it also only seems to occur with muse sounds and not with ms basic

**Comment by BenignPigeon** [comment]
For the record, this continues to be an issue on the latest beta version (4.0.0223072007)

**Comment by zacjansheski** [comment]
I am not able to reproduce this.  Windows 11 with Muse Sounds
