### ISSUE TITLE
[MU4 Issue] Keyboard shortcut to reset a slider

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#14187]
**Describe the issue**

IMV, it would be a good idea to have a shortcut to reset a slider to its default: Ctrl + click for example?

**Comment by cbjeukendrup** [comment]
In the Mixer, we use double-clicking to reset the volume slider and pan knob. Maybe we could do that for other sliders too?

**Comment by Tantacrul** [comment]
Won't fix.

**Comment by Tantacrul** [comment]
It's a fine suggestion @rgreen5 - and it makes sense for us to document the way it can currently be done in MS4
