### ISSUE TITLE
[MU4 Issue]  A piano metronome sounds when playing even when the metronome button is not clicked.

### ISSUE THREAD

**Issue by odelphi** [musescore/MuseScore#14198]
When I play a musescore that was originally scored in version 3.6,  there is a piano sound metronome that plays constantly and there is no way to stop it.  It plays even when the metronome is not clicked on the playback bar.  Also, when you listen to measure 8, there is a three-note appoggiatura.  It sounds like a piano sound is playing it, not violin.

1. Open up a score that was originally scored in MS version 3.6
2. Click on play

**Expected behavior**
I expected the metronome to ONLY sound if I turn it on the playback bar. 

https://user-images.githubusercontent.com/52181093/198904965-efffd240-2d4f-4ec3-baca-106ce478ef4b.mp4

Platform
 - OS: Windows 10

**Comment by KaiVinter** [comment]
The best way is probably to share your score here. Either compress it as a .zip or rename it (because .mscz files are already .zip files). And also, please write a title so the devs can recognize your issue when checking them out.

**Comment by MarcSabatella** [comment]
Do you by chance have another program running - or an external synthesizer - that might be listening for MIDI output events and playing a sound in response (e.g., a DAW)?  If so, you might be affected by https://github.com/musescore/MuseScore/issues/12552.  Solution is to close the other program/device.

**Comment by odelphi** [comment]
If you mean another music notation program running or another program that uses the sound card,  NO.  I do have a synthesizer, but it is currently not connected to my computer.

**Comment by MarcSabatella** [comment]
Nothing else using the soundcard, not MuseScore 3, not a web browser, etc?  Could really be pretty much anything.  See the comments in the other issue for possibly some more insight, but I don't think the situation is fully understood yet.

**Comment by odelphi** [comment]
Sorry Marc.  I don't have anything else running that I believe could be using the soundcard.  Also, when I change the Sound plugin for the metronome on the mixer, the metronome sound stops.  So maybe it has something to do with the sound plugin.  The default one that it uses is "MS BASIC".

**Comment by MarcSabatella** [comment]
What did you change it to, then, that made it stop?

Also, do you have MIDI output enabled?  Disable it so.

Also as mentioned, please attach the score for which you are seeing the problem (ZIP it so GitHub will accept it).

**Comment by odelphi** [comment]
I changed it to a VST plugin called Oberhausen.
When I go into I/O preferences, it shows "Microsoft GS Wavetable synth" in the Midi output.  However, when I click on the pulldown menu, it doesn't let me change it.  

[Ashokan Farewell Gtr.zip](https://github.com/musescore/MuseScore/files/9905820/Ashokan.Farewell.Gtr.zip)

**Comment by MarcSabatella** [comment]
I think those are likely the problems right there.  You said you don’t have anything running that is capable of accessing the sound card, but both the Microsoft synth and the VST plugin are examples of things that *do* respond to MIDI.  So it’s likely one of them that is producing the sound - most likely the Microsoft synth since that is what is connected to the MIDI output.

**Comment by odelphi** [comment]
So is that a bug that I can't delete the Microsoft synth?  Also, when I put the VST, it STOPS the metronome.  It doesn't start it.

**Comment by MarcSabatella** [comment]
I wouldn't expect to be able to "delete" it, but I'd expect you should be able to disable MIDI output.  If you're having trouble doing that, best to submit a new issue on that.

And yes, changing to a VST probably bypasses the regular MIDI output.

**Comment by odelphi** [comment]
Thank you, Marc. I will submit an issue on that unless there is another way to disable MIDI output that I am not aware.  You should be able to just use the dropdown menu to disable it, but that doesn't work (at least not for me).

**Comment by odelphi** [comment]
I have another update.  I was told that a nightly build may have solved this issue.  SO I downloaded a nightly build, and it looks like it solves it.  In the MIDI output setting, it doesn't let me put anything in MIDI output unless it detects I have a MIDI device connected.  That is the way it should be.
