### ISSUE TITLE
[MU4 Issue] Unison/Phasing demonstration = Sound increases but when you do it with a2 or more doesn't sound the same way.

### ISSUE THREAD

**Issue by maestroharmony** [musescore/MuseScore#14194]
**Describe the bug**
Ok so this might be a bug, but when showcasing a2, a3 or a4 anything that includes more than 1 instrument in solo instrument patches it doesn't double or sound 2 instruments, at this point someone would use ensemble patches.

**To Reproduce**
1. Put 2 staves of each instrument
2. Make a unison melody for the 2 instruments and one for a solo staff that has a2 on it.
3. Sound gets bigger with individual staves, but single staff sounds 1 instrument.

**Expected behavior**
It should increase the sound and give the instruments more identity.

https://user-images.githubusercontent.com/104784996/198895375-2ef31326-bf28-43bb-95f2-dc334d2dc956.mp4

https://user-images.githubusercontent.com/104784996/198895385-70d20ac4-4bd6-4f55-bda8-126ceb022330.mp4

https://user-images.githubusercontent.com/104784996/198895381-e1f74f73-723e-4022-8a6e-515f782e3a37.mp4

https://user-images.githubusercontent.com/104784996/198895392-224aac2b-7485-4151-9929-c5908521309f.mp4

**Platform information**
 - OS: Windows 11, R7 3700x, 32 Gb RAM

**Additional context**
If this is not intended playback or anything in the same regard. I would like to see this as a feature to avoid complicating things with the Transpsition Trick to avoid phasing issues.

**Comment by maestroharmony** [comment]
If you do the rhythm at different times with different notes, you can't avoid and get awful phasing effect. 

https://user-images.githubusercontent.com/104784996/198896235-33d40b33-be07-41a0-93bf-9b3db04dab84.mp4

**Comment by KaiVinter** [comment]
Playback rhythm/tempo in Trumpets is also notoriously irregular
