### ISSUE TITLE
[MU4 Issue] Muse Hub window is too big to fit on screen with 150% scaling

### ISSUE THREAD

**Issue by BGdeLaNight** [musescore/MuseScore#14192]
**Describe the bug**

The Muse Hub application does not display fully on the screen (the window is too big to be seen entirely, the top part is outside the screen field) when scaled to 150% on Windows.

**To Reproduce**
1. Go on Windows display settings in order to set the screen scale to 150%.
2. Make sure that the previous setting is correctly applied. Every Windows UI elements should look bigger now (obisously, I know).
3. Launch Muse Hub
4. Notice that the app is too big to been seen entirely. It is specifically the top of the window that disappears.

**Expected behavior**
The Muse Hub application should fit into the screen to be fully seen.

**Screenshots**
[screenshot of the issue](https://imgur.com/a/qEoHzaf)

**Platform information**
 - OS: Microsoft Windows 10 64-bit
 - Computer : 14 inches 1080p display laptop

**Additional context**
n/a

**Comment by Crono23** [comment]
Just wanna add. The window size isn't as bad on a 1366x768 screen with 100% scaling, but it could be better. It cut off a bit, and it overlaps with the taskbar even on small taskbar mode. So I hope the scaling gets better overall, not just for 150%.
![Muse Hub screenshot](https://user-images.githubusercontent.com/88884864/199685023-fdaac04f-f77f-4e9f-a735-196479f94e8d.png)

**Comment by amminadabz** [comment]
I can report this also happens under Windows 11. Tested on a 13" 1080p screen at 150% scale.

**Comment by cgpqci** [comment]
> ...The window size isn't as bad on a 1366x768 screen with 100% scaling...

Excuse me to add, but this issue also occurs to me as well. With the exact scaling and screen size mentioned in the quote above.

![image](https://user-images.githubusercontent.com/90231404/200109244-9f6c5dfd-f118-47fc-98d6-7c0fdf3ef09e.png)

The options are still accessible, though obviously I can't see them.

**Comment by DominicMaas** [comment]
The latest version of Muse Hub should fix this (Hub won't extend its height above / below your monitor). Would be great to confirm!
