### ISSUE TITLE
Default shortcut restored when reopening MS4

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14193]
See comment by @Tantacrul below for better repro steps:

- Go to Shortcut preferences
- Undefine "+" Shortcut (Sharp Note)
- Define shortcut "+" to tie note
Work
Close MuseScore
Reopen Musescore
- "+" key is assigned to both function. Add Sharp and Tie note
- Tie Note won't work

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289914935, revision: github-musescore-musescore-abc123456

**Comment by Tantacrul** [comment]
Confirmed.

- You have to **clear** the '+' key as the shortcut for '**Toggle accidental: sharp**' first
- Then apply it for '**Add tied note**'
- Try the shortcut and it is still applied to '**sharp**'

The second part:
- Reset shortcuts
- Now try change the '**Add tied note**' shortcut with the key '+'
- You'll be told it is already assigned to '**Toggle accidental: sharp**'. Do it anyway
- Ties will work with the shortcut now
- Close and reopen MuseScore: shortcut has now reset back to '**Toggle accidental: sharp**'

**Comment by DmitryArefiev** [comment]
Fixed in #14384
