### ISSUE TITLE
MuseHub Not Really Functional On Mac OS 12.1

### ISSUE THREAD

**Issue by daveman1010221** [musescore/MuseScore#14208]
Generally, MuseHub is incredibly slow. Icons/images do not load. I was attempting to follow the directions to install the MuseScore 4 Beta, detailed here:

https://musescore.org/en/node/336003 

I receive a notification in Muse Hub that there is an update for MuseScore and then I click the "download" arrow. The arrow appears to do nothing. No further notifications of said download appear from the Hub.

I'm attaching a few screen captures, so that others may see what I am seeing. If I can provide additional information that is helpful to you during your Beta, please let me know.

![Screen Shot 2022-10-31 at 8 43 20 AM](https://user-images.githubusercontent.com/26435768/199012576-f3a53eab-1c2a-4e03-b8f8-d4bda53d099e.png)

![Screen Shot 2022-10-31 at 8 41 53 AM](https://user-images.githubusercontent.com/26435768/199012645-33c32119-0b14-4b02-b08a-95cb50fcfd02.png)

![Screen Shot 2022-10-31 at 8 36 32 AM](https://user-images.githubusercontent.com/26435768/199012722-2c80a27f-41d0-4ed3-b67b-dc286607dce4.png)

**Comment by Christof1981** [comment]
I've had the exact same issue. Thanks for posting.

**Comment by barnard-optician** [comment]
I was about to post that I had these issues (on Mac 12.5) including frequent hangs/crashes but since trying a couple of hours ago, Muse Hub seems to working much more smoothly. Would there have been an update to MHub that would have automatically installed in the last couple of hours?

**Comment by daveman1010221** [comment]
Not sure if it was something ephemeral that  cleared up or the fact that I upgraded my Mac OS to the latest release of Catalina. Either way, it's working great now. :-)

**Comment by barnard-optician** [comment]
Sorry to revisit this, but Muse Hub has reverted to the issues described above since I last tried it. Have downloaded the latest Beta release.
