### ISSUE TITLE
[MU4 Issue] Score becomes unusable after a certain point, causing consistent crashes

### ISSUE THREAD

**Issue by AdamAViolist** [musescore/MuseScore#14200]
**Describe the bug**
I was simply working on a score and then I find that whenever I press a specific set of numbers past a specific measure, the program crashes. I don't exactly know what is causing it to crash but when I press 5, 6, 7, 8, or 9 on a measure past the written measure 131, the crash happens.

**To Reproduce**
1. Open the score [Stone_and_Mortar ms4.zip](https://github.com/musescore/MuseScore/files/9897388/Stone_and_Mortar.ms4.zip)
2. Navigate to measure 131, the first measure on the 11th page
3. Click on a rest on any staff
4. Press the shortcuts 5, 6, 7, 8, or 9 (1, 2, 3, 4, and 0 are safe)
5. Program will crash

**Expected behavior**
The rest should've adjusted to the duration pressed, but instead the program crashes

**Platform information**
 - OS: Windows 11 64 bit, x64-based processor
 - Tested on both the beta in MuseHub and the recent nightly build

**Comment by AdamAViolist** [comment]
btw, this does not happen on any measure or staff before measure 131.

**Comment by lyrra** [comment]
Reproduced on linux.
<details><summary> backtrace </summary>

```

#0  0x00005555559bc802 in std::vector<mu::engraving::EngravingItem*, std::allocator<mu::engraving::EngravingItem*> >::size (this=0x160) at /usr/include/c++/10/bits/stl_vector.h:919
#1  0x0000555555a5abf6 in mu::engraving::Segment::element (this=0x0, track=8) at src/engraving/libmscore/segment.cpp:488
#2  0x0000555555d9b98f in mu::engraving::findLinkedVoiceElement (e=0x5555606ba060, nstaff=0x55555ebd7eb0) at src/engraving/libmscore/edit.cpp:4861
#3  0x0000555555d9c01b in mu::engraving::Score::undoChangeChordRestLen (this=0x55555d9831e0, cr=0x5555606ba060, d=...) at src/engraving/libmscore/edit.cpp:4938
#4  0x0000555555d56bc2 in mu::engraving::Score::changeCRlen (this=0x55555d9831e0, cr=0x5555606ba060, dstF=..., fillWithRest=true) at src/engraving/libmscore/cmd.cpp:1443
#5  0x0000555555d56830 in mu::engraving::Score::changeCRlen (this=0x55555d9831e0, cr=0x5555606ba060, d=...) at src/engraving/libmscore/cmd.cpp:1395
#6  0x0000555555a0cc73 in mu::engraving::Score::padToggle (this=0x55555d9831e0, p=mu::engraving::Pad::NOTE4, ed=...) at src/engraving/libmscore/score.cpp:3341
#7  0x000055555627cc6c in mu::notation::NotationNoteInput::padNote (this=0x55555d563e20, pad=@0x555559c9d7a8: mu::engraving::Pad::NOTE4)
    at src/notation/internal/notationnoteinput.cpp:348
#8  0x00005555564e546a in mu::notation::NotationActionController::padNote (this=0x5555590fdd00, pad=@0x555559c9d7a8: mu::engraving::Pad::NOTE4)
    at src/notation/internal/notationactioncontroller.cpp:715

```

</details>

<details><summary> possible fix (tested, avoids crash) </summary> 

```

diff --git a/src/engraving/libmscore/edit.cpp b/src/engraving/libmscore/edit.cpp
index 719472a666..7dcb322ce4 100644
--- a/src/engraving/libmscore/edit.cpp
+++ b/src/engraving/libmscore/edit.cpp
@@ -4858,6 +4858,9 @@ static EngravingItem* findLinkedVoiceElement(EngravingItem* e, Staff* nstaff)
     Measure* measure = segment->measure();
     Measure* m       = score->tick2measure(measure->tick());
     Segment* s       = m->findSegment(segment->segmentType(), segment->tick());
+    if (! s) {
+        return 0;
+    }
     return s->element(dtrack);
 }
 
```

</details>

**Comment by asattely** [comment]
@AdamAViolist When you were making this score, did you do anything with generating or modifying parts? If so, which ones / what did you do? The nullcheck above fixes the issue but I'm trying to investigate the root cause of the issue in your particular score.

**Comment by AdamAViolist** [comment]
> @AdamAViolist When you were making this score, did you do anything with generating or modifying parts? If so, which ones / what did you do? The nullcheck above fixes the issue but I'm trying to investigate the root cause of the issue in your particular score.
> 
> edit: ... and/or did you use the split measure command (cr. https://github.com/musescore/MuseScore/issues/14607)?

I am pretty sure I had parts already made and then the newer updates duplicated them. I'm not sure about the split measure tool if it relates to the first measure being an anacrusis (I used the measure properties panel for that).

**Comment by cbjeukendrup** [comment]
> then the newer updates duplicated them

That might mean that the issue is caused by the beta1/beta2 incompatibility relating to parts, which may have caused things to go out of sync. However, we'd need to find out if that's also the case in #14606.
