### ISSUE TITLE
[MU4 Issue] Crash when loading Relab Development LX480 reverb

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#14205]
**Describe the bug**
After installation, I was actually able to successfully load the Relab Development LX480 plugin into the MuseScore mixer and have the interface appear on my screen.
Playback then worked for a few seconds before MuseScore crashed.
Now even clicking on the plugin in the mixer causes MuseScore to crash (Even before the plugin UI appears). 

**To Reproduce**
See video: 

https://user-images.githubusercontent.com/86290556/198984286-a5dbae36-7757-44e5-8397-d15c1a6d5eb1.mov

**Platform information**
 - MacOS 12.6 (M1)
 - Relab Development LX480 V4 Complete

**Comment by DmitryArefiev** [comment]
@bkunda Hi, can you try these builds please? #15227

**Comment by DmitryArefiev** [comment]
> @bkunda Hi, can you try these builds please? #15227

No need to test. I've installed LX480 in trial mode and it looks fine now on **Win10/Mac13**

Fixed in #15227

**Comment by bkunda** [comment]
> > @bkunda Hi, can you try these builds please? #15227
> 
> No need to test. I've installed LX480 in trial mode and it looks fine now on **Win10/Mac13**
> 
> Fixed in #15227

All good. I tried it anyway when testing 4.0.1. Works well!

**Comment by DmitryArefiev** [comment]
Great. Thanks!
