### ISSUE TITLE
[MU4 Issue] MuseScore files from previous versions don't work well

### ISSUE THREAD

**Issue by OwenV1** [musescore/MuseScore#14203]
Title.  Sound doesn't play unless a note is clicked on first (not a big deal), chord arpeggios and notes played with pedal down play at max velocity, a lot of the specific formatting (text reset to default places and default options, especially chord labels), clucters of notes will sometimes play only 1 note.

**Comment by sammik** [comment]
It would be nice, if You attach some reference score (fragment), where it happens.
(Just rename "mscz" to "zip", so GitHub accepts it.

**Comment by OwenV1** [comment]
[broken_score(1).zip](https://github.com/musescore/MuseScore/files/9903934/broken_score.1.zip)
alr here you go.  I last opened it in MU3 so idk if it will have the same results as the one I experienced it on, but I'm pretty confident it will.

**Comment by oktophonie** [comment]
Closing as rather old - but also, having played this score, the playback issues you describe seem to have been addressed by now. If there are issues remaining, please file them separately (if a similar open issue doesn't already exist).
