### ISSUE TITLE
[MU4 Issue] No MuseHub installer for any distribution aside from Debian-based

### ISSUE THREAD

**Issue by Dupiter-AU** [musescore/MuseScore#14201]
**Describe the bug**
The Musehub installer is a `.deb` file, which is built specifically for Debian distros. Since I am on Arch Linux, I cannot install MuseHub, and therefore cannot install the sound library.

**To Reproduce**
1. Go to the [musehub downloader](https://musescore.org/en/node/336003)
2. Download the Linux installer
3. Note that the file is `.deb`, not for example a `.appimage`, or flatpak, which would work on any distro

**Expected behavior**
Installer that would work on any generic linux distro, such as `.appimage` or a flatpak

**Platform information**
 - OS: Arch Linux

**Additional context**
Without the MuseHub application, it is impossible to install sound libraries

**Comment by dragonwithafez** [comment]
I will note that technically you can extract the binaries from the .deb archive and install them manually, though that is no replacement for a proper distro-agnostic installer.

**Comment by eyolf** [comment]
That is only a very partial solution, since there are also dependency issues, primarily, i think, because certain required package names differ between distributions.

**Comment by LasseRosenow** [comment]
I would love if musescore would publish official flatpaks on flathub.org

**Comment by aspiers** [comment]
This is a duplicate of #13919 which is receiving a lot more attention, so I recommend closing in favour of that.

**Comment by charlesneimog** [comment]
It's not working for me... ;(

**Comment by Dupiter-AU** [comment]
Closed in favor of #13919
