### ISSUE TITLE
[MU4 Issue] Default muse sounds for string instruments should not be "solo"

### ISSUE THREAD

**Issue by Xtarich** [musescore/MuseScore#14202]
**Describe the bug**
When setting playback to muse sounds, the mixer should automatically select the orchestral sounds for each instrument: vlns, vla, cello and double bass, instead of "solo" for each.

**To Reproduce**
1. Open a score with vln, vla, cello or double bass.
2. Click on "playback setup" and activate muse sounds.
3. See that each instrument is automatically set to "solo"

**Expected behavior**
Each instrument should not be solo by default. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/105360640/198919935-7ae7ed88-2600-4b26-b22c-12ffa97ba67f.PNG)

**Platform information**
 - OS: [Windows 10]

**Comment by Fristover** [comment]
the "solo" sounds get applied because you're using the individual instruments, you have the sections as separate instruments in the menu

**Comment by Xtarich** [comment]
Oh thank you that makes sense haha, Good.
