### ISSUE TITLE
[MU4 Issue] Tempo lines are invisible if there's nothing on those beats in the top staff

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#14212]
**Describe the bug**
Tempo lines are invisible if there isn't anything on the beats where the tempo lines are in the top staff (eg. last two beats of a whole note)

**To Reproduce**
1. Create a score
2. Put tempo line on last two beats of measure
3. Put whole note on top staff
4. See no tempo line

**Expected behavior**
The tempo line should still be there

**Screenshots**
<img width="493" alt="Screen Shot 2022-10-31 at 8 49 36 AM" src="https://user-images.githubusercontent.com/21023353/199036906-320aaf18-31fc-4d05-b0f4-00bba1c15932.png">
<img width="490" alt="Screen Shot 2022-10-31 at 8 49 51 AM" src="https://user-images.githubusercontent.com/21023353/199036959-b15128c1-e107-46b3-b97d-0367ccdba9c3.png">

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by oktophonie** [comment]
This is a general problem, it seems, when the rhythmic attachment point disappears. For example, taking this:
![image](https://user-images.githubusercontent.com/20604032/199058162-2a7096bf-eaba-44ed-b193-3b0eff98aaac.png)
and changing the first half note to a whole note causes the hairpin to vanish:
![image](https://user-images.githubusercontent.com/20604032/199058116-9a95fe82-20cd-4ecf-8345-47facd08a3fa.png)

While we desperately want to be able to attach things to specific rhythmic positions within notes, that's a future (4.x) feature, so the question is what the behaviour should be right now. @Tantacrul

**Comment by oktophonie** [comment]
The problem with lines exists in 3.6; tempo lines are new in 4.0 so on the one hand it's just another instance of the same problem, but on the other hand it's 'new'.

In 3.6, however, a plain tempo (not a line) _does_ keep its position in this situation. This:
![image](https://user-images.githubusercontent.com/20604032/199087284-6aa5c764-9e7f-4466-a74f-63a49bd8d07e.png)
becomes this:
<img width="214" alt="Screenshot 2022-10-31 185604" src="https://user-images.githubusercontent.com/20604032/199087935-0e1e1901-e5d7-4b13-9d5b-050e30b25ec9.png">

It would be great if lines could do the same. I suspect that's infeasible for now, but we'll have a look in case.

**Comment by Tantacrul** [comment]
Yeah, why not see? Thanks @oktophonie :)

**Comment by mike-spa** [comment]
Closing this issue as it's been incorporated into the more general #14296. Will be fixed by #14397.
