### ISSUE TITLE
[MU4 Issue] Pitch and string number can't be changed from TAB notation staff (in different cases)

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#14218]
**Describe the bug**
The issue is reproducible for both MU4 created scores and MU4 import.
Two cases for reproduce found yet:
- if octave up/down line is applied for note (any score/tab)
- if capo is applied for tab (for import only)

**To Reproduce**
1. Open the tab
[test tab for MU4.gp.zip](https://github.com/musescore/MuseScore/files/9903091/test.tab.for.MU4.gp.zip) or 
[Tab_pitch _change.mscz.zip](https://github.com/musescore/MuseScore/files/9909328/Tab_pitch._change.mscz.zip)

2. Create linked Tab staff for the main one
3. Select note in the first measure on the linked Tab staff
4. Try to change its pitch using arrows up/down
5. Try to change string using cmnd+arrow up/down

**Expected behavior**
[Handbook](https://musescore.org/en/handbook/3/tablature#edit-notes)

**Screenshots**

https://user-images.githubusercontent.com/101250347/199063683-b8d878d0-2d1b-4114-8ea2-ddcf3be30f57.mp4

**Comment by aquiferweb** [comment]
When in Note input mode and trying to type a new fret number - this bug produces an erratic / unexpected response in this scenario too.

**Comment by ShibuyaCyana** [comment]
Sorry but, looks like this needs some more works...
I still can't change string by dragging, but ctrl + up/down works.
![dragging](https://github.com/musescore/MuseScore/assets/39703247/db308a4d-7282-48f8-ae1a-73292195c154)
