### ISSUE TITLE
[MU4 Issue] Default shortcut "+" is duplicated 

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#14225]
**Describe the bug**

Shortcut "+" seems to be duplicated between "Tie" and "Toggle sharp", and it only does the latter. It should be only used for one of the two. We can choose either one, obviously, but it used to be the tie in 3.6 (and I've got it pretty much in the muscle memory at this point). @bkunda you're probably the right person to triage this one. This also seems connected to #14193, thought that one is more specifically about custom shortcut settings not being retained upon closing-reopening Musescore.

**Comment by cbjeukendrup** [comment]
I can imagine that this gets fixed when you delete your custom shortcuts file from `$HOME/.local/share/MuseScore/MuseScore[Version]/` (or reset preferences). I think that if we _add_ a default shortcut, this will be automatically added to the custom shortcuts file, but if we _remove_ a default shortcut, this is _not_ removed from the custom shortcuts file. So, if we _change_ a default shortcut, i.e. remove the old one and add the new one, the old one will still be in the custom shortcuts file, so you end up with both.

**Comment by erinic04** [comment]
Yeah you just need to reset the shortcuts to default and the problem will be fixed

**Comment by mike-spa** [comment]
Ha! I actually never changed any shortcut proference myself, so I assumed that what I was seeing was just the default. Not sure at which point that one's changed then

**Comment by mike-spa** [comment]
Thanks, anyway. Gonna close this now 👍
