### ISSUE TITLE
[MU4 Issue] Keyboard shortcuts for dotted rests not functional

### ISSUE THREAD

**Issue by Christof1981** [musescore/MuseScore#14227]
While it is possible to select a dotted rest using keyboard shortcuts—5+., 4+., etc.—the dot has no effect. The dot icon must be clicked manually before the dotted rest appears in the score.

1. In a score, type in the keyboard shortcut for a dotted quarter-note: 5+. Type in a pitch name, and a dotted note appears, as expected.
2. With the icons for a dotted quarter note still highlighted, type 0. What would normally happen is that a dotted quarter rest would appear in the score; instead, a quarter rest (not dotted) appears.
3. The same error holds true for other note values.
4. The solution is to click the dot icon manually, and typing 0 will have the expected result.

Mac OS 12.6.1

**Comment by MarcSabatella** [comment]
Have you tried this with a current nightly build?  This was just fixed a few days, and works fine for me currently.

**Comment by Christof1981** [comment]
I haven't, but I will. Thanks for the tip.

**Comment by Christof1981** [comment]
And sorry, I'm a novice at this type of thing: Are the nightly builds stable enough to replace the Beta version? (I know the Beta is somewhat buggy as well, but I'd hope for something that is at least as reliable, if not more so.) Also, will Muse Sounds still work with the nightly build even though it's not downloaded through Muse Hub?

**Comment by MarcSabatella** [comment]
Generally, yes, the nightlies are better than the beta.  Neither are meant for real work, but if you're going to test, you might as well test the current version so you don't spend time finding bugs that have already been fixed.  Of course, that does mean occasionally new bug creep in too, but it's important we find those, too!  Anyhow, both versions can coexist.

And yes, as of last week, the night builds work with Muse Sounds.

**Comment by oktophonie** [comment]
Indeed, fixed as of #14033.
