### ISSUE TITLE
add text to palette

### ISSUE THREAD

**Issue by gerrybass** [musescore/MuseScore#14224]
pressing strg + shift does not work to copy selfdefined text to the palette

windows 10

**Comment by MarcSabatella** [comment]
Which build are you using?  Works fine for me in the Beta and in recent nightlies.  Are you pressing both of those keys before starting the drag and holding them the whole time?

**Comment by gerrybass** [comment]
MU4, i did some experiments

- i clicked text, then strg+shift - it worked as expected
- then i pressed strg+shift, then text - 1.x it didnt work
  2.x it worked
- sometimes MU4 freezed, sometimes it crashed

really weird... seems to be my personal problem  ;-)

**Comment by cbjeukendrup** [comment]
The freeze/crash problem may be fixed by #13410 (at least, that fixes a possible cause).
