### ISSUE TITLE
[MU4 Issue] Playback MS Basic - strings staccato too quiet, especially in shorter duarations

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#14231]
**Describe the bug**
In MS Basic sound font, playback of strings staccato is too quiet. Solo strings, as well as Section strings.

**Expected behavior**
Balanced volume in staccato playback.

**Screenshots**

https://user-images.githubusercontent.com/1646034/199174289-656f20f0-ce95-46d6-af5c-7cbc71a6517c.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
As far as I know, only strings and only in MS Basic and specially shorter durations (eights, sixteens) are affected. 
Other instruments (Piano, flute) in MS Basic works fine.
Muse Sounds has oposite problem,staccato is too loud. (It is already reported.)

**Comment by Tantacrul** [comment]
Yes, they're really quiet. I think for 8ths / 16ths, they should perhaps last a **little** longer for strings, so they have a bit more time to be heard. Perhaps also increasing the volume would make sense too.

Worth comparing to MS3, where they're notably easier to hear and sound more balanced with legato notes.

**Comment by sammik** [comment]
Yes, in MU3 staccato 8 sounds like normal 16. In MU4 staccato 8 sounds like normal 32.
And normal 32 in MU3 is better hearable then normal 32 in MU4.

https://user-images.githubusercontent.com/1646034/199323868-ca52891a-5b3a-4e4b-9846-c91469b8ec4e.mp4

(Also there are extra beats played after end of score in MU4, but it is another issue, I guess olready reported.)
