### ISSUE TITLE
Can't change the language from Hebrew to English[MU4 Task]

### ISSUE THREAD

**Issue by RotoBanana** [musescore/MuseScore#14237]
Can't change the language from Hebrew to English.
![image](https://user-images.githubusercontent.com/62190339/199219153-ee0aa68d-5f3c-4137-a066-4833c7701c2b.png)

**Steps to reproduce**
1. Be on a non-English Windows system (On the Hebrew version of Windows to be spesific)
2. Go to File --> General --> Languages (On the picture, written as "שפות")
3. Try and change for English, yet English doesn't appear in the Menu.

**Expected Behavior**
Change the language to English, from system default.

Btw, the Hebrew version sucks, half of musescore is in English, and the other is in Hebrew.
I mean, if you got time to translate go for it, but like for us non-English natives, just to have Musescore in English would be pretty good.

**Comment by MarcSabatella** [comment]
Your screenshot only shows up to the letter C.  What happens if you scroll further down?

**Comment by RotoBanana** [comment]
> Your screenshot only shows up to the letter C. What happens if you scroll further down?


> Yes, can you confirm if you scroll english can't be found at all? Incidentally, Hebrew is only partially translated and we've been asking community folk to help out with it but so far, no luck.

Oh my god, I feel so stupid... I didn't think I can scroll down...
So I guess my recommendation would be to add a visable scroll bar, haha.

Regarding the translation part - maybe if I'll find time I might be able to help. I would gladly if I can be given more information about how can I help translating.
