### ISSUE TITLE
[MU4 Issue] Arpeggios are rendered long on Tab staves regardless to the quantity of notes in chord

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#14243]
**To Reproduce**
Steps to reproduce the behaviour:
1. Create a small score with Guitar instrument 
2. Change staff type to Tab
3. From palette add an arpeggio to single notes and chords
4. Pay attention to the length of arpeggios

**Expected behavior**
Arpeggios length corresponds to quantity of notes in chord 

**Screenshots**
![CleanShot 2022-11-01 at 16 20 28](https://user-images.githubusercontent.com/101250347/199258699-eb8ff793-82b7-4850-a09b-fc79ac5e577f.png)

https://user-images.githubusercontent.com/101250347/199258444-3189e125-c016-4103-a6ef-2da748093e6b.mp4

**Comment by oktophonie** [comment]
This appears to now be fixed in master. (It was OK in 4.0 but not 4.1)
