### ISSUE TITLE
[MU4 Issue] Import This XML File and try to change page format. MuseScore 4 Beta crash

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14251]
**Describe the bug**
 Import This XML File and try to change page format. MuseScore 4 Beta crash

**To Reproduce**
- Set import parameter like the screenshot
- Open this XML file produced by Photoscore
- Open format page
- MS4 freeze and then crash (Same issue in MS3,6. but need to be corrected in 4.0)

**Screenshots**
![image](https://user-images.githubusercontent.com/1835871/199290068-1fd9b7f0-93f8-4ba6-b5ff-6fd238aad2dd.png)

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289914935, revision: github-musescore-musescore-abc123456

**Additional context and workarround**
Unselect "Importer la mise en page" in import parameters. The file is correctly imported and change page layout work fine.

[HSPK-25-Trb Ut 3.zip](https://github.com/musescore/MuseScore/files/9912428/HSPK-25-Trb.Ut.3.zip)

**Comment by DmitryArefiev** [comment]
@Gai-Luron Thanks for logging! I can reproduce on my side as well

https://user-images.githubusercontent.com/90187801/199524442-bd57ef8b-087a-43d1-9f44-dc1b0a6e60d0.mp4

**Comment by DmitryArefiev** [comment]
I can't reproduce with others musicXML files. Changing to P2

**Comment by lvinken** [comment]
The attached MusicXML file contains a page-layout element without a page-margins element. I suspect this leads to uninitialised data in struct PageFormat after executing function MusicXMLParserPass1::pageLayout().

**Comment by lvinken** [comment]
Problem reproduced running on Linux (but not on MacOS). Problem does not reproduce for me on Linux in GDB, which makes debugging difficult. When adding page-margins to the attached file, the problem does not reproduce anymore. This supports my hypothesis, which means a fix should be trivial (suggestion: initialise struct PageFormat's members to any reasonable default).

**Comment by lyrra** [comment]
Got a hit in gdb:
<details><summary>backtrace:</summary>

```

#0  0x00007ffff521bbc8 in double double_conversion::StringToDoubleConverter::StringToIeee<char const*>(char const*, int, bool, int*) const ()
   from /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.3
#1  0x00007ffff5c9af5f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ffff5c8e326 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff6a6f214 in QDoubleSpinBox::setMaximum(double) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x0000555556311daf in mu::notation::PageSettings::setMarginsMax (this=0x555561410290, pw=223.5275) at src/notation/view/widgets/pagesettings.cpp:129
#5  0x0000555556312528 in mu::notation::PageSettings::updateValues (this=0x555561410290) at src/notation/view/widgets/pagesettings.cpp:189
#6  0x0000555556312f49 in mu::notation::PageSettings::twosidedToggled (this=0x555561410290, flag=172) at src/notation/view/widgets/pagesettings.cpp:276
#7  0x000055555636cec0 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<bool>, void, void (mu::notation::PageSettings::*)(bool)>::call (f=
    (void (mu::notation::PageSettings::*)(mu::notation::PageSettings * const, bool)) 0x555556312ef8 <mu::notation::PageSettings::twosidedToggled(bool)>, o=0x555561410290, arg=0x7fffff7ff970)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#8  0x000055555636a498 in QtPrivate::FunctionPointer<void (mu::notation::PageSettings::*)(bool)>::call<QtPrivate::List<bool>, void> (f=
    (void (mu::notation::PageSettings::*)(mu::notation::PageSettings * const, bool)) 0x555556312ef8 <mu::notation::PageSettings::twosidedToggled(bool)>, o=0x555561410290, arg=0x7fffff7ff970)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#9  0x0000555556365c51 in QtPrivate::QSlotObject<void (mu::notation::PageSettings::*)(bool), QtPrivate::List<bool>, void>::impl (which=1, this_=0x555560c96a30, r=0x555561410290,
    a=0x7fffff7ff970, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:418
#10 0x00007ffff5e435a6 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff69bbea2 in QAbstractButton::toggled(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff69bd019 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff69bd7d0 in QAbstractButton::setChecked(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x0000555556312af3 in mu::notation::PageSettings::updateValues (this=0x555561410290) at src/notation/view/widgets/pagesettings.cpp:226

```

</details>

pagesettings.cpp:129 is:
```
void PageSettings::setMarginsMax(double pw)
{
    oddPageLeftMargin->setMaximum(pw); <----------- line 129
    oddPageRightMargin->setMaximum(pw);
    evenPageLeftMargin->setMaximum(pw);
    evenPageRightMargin->setMaximum(pw);
}
```

**Comment by lvinken** [comment]
Indeed caused by uninitialized data, created pull request https://github.com/musescore/MuseScore/pull/14618.

**Comment by Jojo-Schmitz** [comment]
And in #9000 for 3.x
