### ISSUE TITLE
MU 4 Issue: Muse Sounds anticipate hairpins and dynamic markings during playback

### ISSUE THREAD

**Issue by bobjp** [musescore/MuseScore#14259]
This might be fine in certain cases but not all. 
For example, while playing back a passage at forte, About 1 or 2 measures before a piano dynamic, MuseScore starts to get softer. As though there was a hairpin there. If I wanted a sudden volume change, it can't be done as far as I can tell. This happens with all instruments I've tested so far.

**Comment by cbjeukendrup** [comment]
This looks like a duplicate of #13902. Thanks for reporting!
