### ISSUE TITLE
[MU4 Issue] Tie rendering issues when grace notes are tied to main chords

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#14267]
**Describe the bug**
As far as I know it's quite uncommon, but in MU, you can tie a grace note to its main chord. In certain cases, the tie is not rendered correctly:

- Grace note before, tied to main chord -> tie direction is upwards, but that makes it collide with the flag of the grace note. Could be avoiding by drawing the tie downwards. 
    <img width="94" alt="Scherm­afbeelding 2022-11-02 om 14 22 41" src="https://user-images.githubusercontent.com/48658420/199500580-8dc26dc2-1dac-4d02-9bef-bfe481bb7ca0.png">
    (However, it turns out that this also happens for non-grace chords: 
    <img width="105" alt="Scherm­afbeelding 2022-11-02 om 14 42 48" src="https://user-images.githubusercontent.com/48658420/199504977-89a44332-8d25-4df6-95d1-cc490a1290ed.png">
    so not sure if this is really an issue)

- More importantly: grace note after, tied to main chord, where the grace chord or the main chord has multiple notes -> tie rendered in the wrong place
    <img width="95" alt="Scherm­afbeelding 2022-11-02 om 14 26 14" src="https://user-images.githubusercontent.com/48658420/199501359-61f15645-548f-4a26-9bfd-a66bcf258ae0.png"> is fine
    <img width="102" alt="Scherm­afbeelding 2022-11-02 om 14 26 50" src="https://user-images.githubusercontent.com/48658420/199501486-8247a15b-94bd-4860-ad82-61931099ab30.png"> not
    <img width="115" alt="Scherm­afbeelding 2022-11-02 om 14 27 40" src="https://user-images.githubusercontent.com/48658420/199501654-19f0ccab-0c60-4bf4-b792-651c65a25200.png"> also not

**Expected behavior**
Although this situation is maybe exotic, it would be great if ties were rendered correctly even in this situation.

**Comment by oktophonie** [comment]
The former case is not (imo) an issue; the latter certainly is!
