### ISSUE TITLE
[MU4 Issue] Score deleted from cloud persists on Scores tab

### ISSUE THREAD

**Issue by cgpqci** [musescore/MuseScore#14269]
**Describe the bug**
To quote:

> ...I'm able to save my score to cloud without exporting the MuseSound audio. Since this is not the result I want, I would followingly delete it. As a result, the duplicate score in the cloud is gone, but it would persist on the Scores Tab. (_See below_)
> 
> ![image](https://user-images.githubusercontent.com/90231404/199512341-4da8c954-6e87-42bc-bbeb-9846726d3cff.png)

**Expected behavior**
Deleted score should be gone from display on the Scores tab once deleted from the cloud (i.e. the online platform)

**Platform information**
- OS: Windows 10
- Version: 4.0.0.222931342 (released early public beta)

**Additional context**
- This is in part of a failed result of publishing a score along with the issue #14268
- I did this a few times, as evident of the multiple scores with the cloud icon.
- After further fiddling, it seems that these scores still exists as I can still access and edit them. The only thing is I don't see them on my _My Scores_ page on my account. Maybe there's a mistake on my part but I can't figure it out either.

**Comment by Tantacrul** [comment]
@shoogle @bkunda @cbjeukendrup - I sort of feel that this is really something we should address in 4.x.

Let me know what you think.

**Comment by cbjeukendrup** [comment]
Yes, I agree. Currently there is simply (almost) no communication from MuseScore.com to MuseScore desktop (only the other way around). I think it is preferable solve this issue in combination with the problem that the MuseScore.com file may have been modified on another device (and the latter problem may be quite complicated because of potential conflicting changes).

**Comment by bkunda** [comment]
Yes agreed. The scores persist because they are still sitting in the user's ‘cloud scores‘ folder on their harddrive, and there is currently no synchronisation between this folder and the score manager on musescore.com. Definitely something we should look further into in 4.x.
