### ISSUE TITLE
[MU4 Issue] Cannot export audio of one instrument - always full score audio

### ISSUE THREAD

**Issue by Xtarich** [musescore/MuseScore#14265]
**Describe the bug**
Musescore 4 always exports the audio as the full score, never just the instrument specified, e.g. violin.

**To Reproduce**
1. Go to 'File... Export'
2. Click on 'Format... mp3 or flac'
3. Select one instrument, e.g. 'violin'. 
4. Click export.
5. Listen to audio file and hear all instruments.

**Expected behavior**
Only the playback of the one instrument is exported, e.g. violin.

**Screenshots**

https://user-images.githubusercontent.com/105360640/199464577-12df7dd4-036f-4c5b-ab31-b2bc7d1bb822.mp4

**Platform information**
 - OS: [Windows 10]

**Comment by DmitryArefiev** [comment]
Fixed in #14129
