### ISSUE TITLE
Installing MuseScore 4 using the Muse Hub should not uninstall MuseScore 3

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#14270]
When the user has installed MuseScore 3, and then installs MuseScore 4 from the Muse Hub, their installation of MuseScore 3 should _not_ be removed. Different major versions of MuseScore should always be able to coexist. 

(This issue is the clear-and-concise version of #14024 🙂)

**Comment by thermogl** [comment]
Taking a look
