### ISSUE TITLE
[MU4 Issue] Stems and lines in additional part staves are very thin

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#14275]
**Describe the bug**
Whenever you add a staff to an existing part, all the stems and other lines are set to a thickness of 0.03 sp.

**To Reproduce**
1. Open a part score
2. Add another staff to the part
3. See that all the lines in the added staff are tiny

**Expected behavior**
The lines should be a normal thickness

**Screenshots**
<img width="498" alt="Screen Shot 2022-11-02 at 12 48 18 PM" src="https://user-images.githubusercontent.com/21023353/199576227-41c076e0-e95c-40db-a802-64693480e66d.png">

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by oktophonie** [comment]
I am not able to reproduce this. Which build are you using, and are you able to attach a score (in a .zip) where this happens for you?

**Comment by erinic04** [comment]
I believe I am using the Halloween nightly for this

**Comment by erinic04** [comment]
Also here's this 
[Uploading Super Mario Galaxy.mscz.zip…]()

**Comment by erinic04** [comment]
Also here's this 
[Uploading Super Mario Galaxy.mscz.zip…]()

**Comment by erinic04** [comment]
Also some of the stems intersect with the barlines for some reason

**Comment by oktophonie** [comment]
> Also here's this Uploading Super Mario Galaxy.mscz.zip…

This upload did not work correctly, I'm afraid.

**Comment by erinic04** [comment]
Aight here's this?
[Super Mario Galaxy.mscz.zip](https://github.com/musescore/MuseScore/files/9930155/Super.Mario.Galaxy.mscz.zip)
