### ISSUE TITLE
[MU4 & MU App on iOS] MuseScore 4 files uploaded to musescore.com don't play on mobile

### ISSUE THREAD

**Issue by OwenV1** [musescore/MuseScore#14283]
**Describe the bug**
Title: every musescore 4 score I've uploaded doesn't play on the mobile app.

**To Reproduce**
1. Upload a MuseScore 4 score to musescore.com (via "Save on Cloud" in the app or "Upload" on the website)
2. Once it's finished uploading and processing, try to open it and listen to it on the mobile app.

**Expected behavior**
The HUD will still load, but the score itself will appear white (no lines, notes, keys, time signatures, etc, at all).

**Screenshots**
![image](https://user-images.githubusercontent.com/16928323/199632139-5d8f7b2d-1011-4cb1-8e9b-f207f623b70a.png)

**Platform information**
Uploaded from Windows 10, attempted to open on iPhone (iOS 16)

**Additional Information**
These scores specifically:
https://musescore.com/user/31319606/scores/8927235?share=copy_link
https://musescore.com/user/31319606/scores/8905587?share=copy_link
https://musescore.com/user/31319606/scores/8905488?share=copy_link
https://musescore.com/user/31319606/scores/8887596?share=copy_link

**Comment by Tantacrul** [comment]
For a short period of time after the launch of MS4.0, this is going to be the case until a new version of the notation viewer is released on MuseScore mobile. I've moved this to 4.x.

**Comment by jppaolim** [comment]
This is very painful and make musescore 4 basically useless for me and I imagine a range of users. Do you kindly have any timeline in mind ?

**Comment by Tantacrul** [comment]
Since this is a MuseScore mobile issue, it can't be fixed by the MuseScore team. However - it is being tackled right now and will the new notation system in MuseScore mobile will be out in the next month or two.
