### ISSUE TITLE
[MU4 Issue]

### ISSUE THREAD

**Issue by roundearth** [musescore/MuseScore#14289]
**Describe the bug**
I'm currently working on a piece with 11 instruments, and whenever I try to perform any action in MuseScore, it ends up crashing. I cannot point to exactly what makes it crash, but basic actions such as moving some bars around, trying to copy-paste a tempo mark has made do so. Unsure if it has to do with my hardware or not.

I loaded over the file from MuseScore 3 with an XML-file before toying around with the trumpet-voice and adding Muse Sounds without any problems. Suddenly, the program started crashing. The program has also crashed before when trying to apply Muse Sounds, but it has been an issue that just disappeared after reopening this program. The crashes I experience now are persistent.

I've imported the soundfonts manually from /srv/muse-hub/downloads/Instruments to ~/Documents/MuseScore4/SoundFonts since they didn't appear when running the .AppImage

This was also an issue when I used the Alpha-version a while back.

PS: Simply trying to play the score also crashes it now.

**To Reproduce**
* Open the mscz-file in 
* Do basic actions such as moving bars around (ctrl x + ctrl v to move it forwards for backwards)
* Crash (at least for me)

**Expected behavior**
Playback and normal editing shouldn't crash the program

**Hardware**
CPU: 11th Gen Intel i3-1115G4 (4) @ 4.100GHz
GPU: Intel Device 9a78
Memory: 7608MiB

**Operative system**
Zorin OS 16.2 x86 with kernel 5.14.0-1054-oem

**Software used**
[Muse Hub](https://www.dropbox.com/s/o2rtbu3nrbuf3rc/Muse_Hub_Linux.zip?dl=1)
[MuseScore](https://github.com/musescore/MuseScore/releases/download/v4.0_beta/MuseScore-4.0.0.3289917644-x86_64.AppImage)

**Additional context**
I have also published this in the Issue tracker, [#336532](https://musescore.org/en/node/336532#comment-1147622)

**mscz-file (zipped)**
[Christmas Don't Let Me Down.zip](https://github.com/musescore/MuseScore/files/9929623/Christmas.Don.t.Let.Me.Down.zip)

**Edit log**
Fixed the number in memory
Added link to the Issue on musescore.org

**Comment by LuisLiszt** [comment]
Hey there,

I have no crashes when I perform basic actions with your file. I tried it with the nightly build from 31st October. Do you have the latest nightly build?

**Comment by roundearth** [comment]
> Hey there,
> 
> I have no crashes when I perform basic actions with your file. I tried it with the nightly build from 31st October. Do you have the latest nightly build?

Hi! 
Tried running it in the November 4th nightly build. The program crashed before bar 2 when I tried to play it.

**Comment by LuisLiszt** [comment]
@roundearth is your puffer size set to 2048 in I/O settings? That causes problems sometimes.

**Comment by roundearth** [comment]
> @roundearth is your puffer size set to 2048 in I/O settings? Lower setting 1024 causes problems sometimes...

I tried setting it to 2048 and 4096 with no success

**Comment by Tantacrul** [comment]
Hey @roundearth - could you please do the following:

Uninstall any version of MS4 you have installed. Then open the Muse Hub and install all the updates. If nothing is appearing, try going to the 'gear' icon and checking for updates.

Bear in mind, your revision number should be: **2C34155**

<img width="214" alt="image" src="https://user-images.githubusercontent.com/21022311/200571901-f6c9fabf-c083-403d-b3e8-3cf4d119cef8.png">

**Comment by cbjeukendrup** [comment]
Closing, since it seems outdated and has been in "needs info" state for months
