### ISSUE TITLE
[MU4 Issue] Gap between note and barline in pick-up measure w/ only one note

### ISSUE THREAD

**Issue by cgpqci** [musescore/MuseScore#14284]
**Describe the bug**
Wide gap exists between note and barline in a pick-up measure with only a single note as input.

**To Reproduce**
1. Create score as of liking.
2. Insert a pick-up measure amid the process.
3. Insert note according to the whole duration of the pick-up measure

In MU4, the procedure would result to this with the gap.

![image](https://user-images.githubusercontent.com/90231404/199662073-9abe70d7-7120-499f-af6b-8b27ea92c549.png)

In contrast, MU3 is able to render this better.

![image](https://user-images.githubusercontent.com/90231404/199662123-71c1f6e6-bc40-4254-a757-1766ba6f5980.png)

This doesn't occur when the duration of the pick-up measure is split.

![image](https://user-images.githubusercontent.com/90231404/199662667-6824540b-30e5-48b7-b97e-a7b029db351b.png)
![image](https://user-images.githubusercontent.com/90231404/199662700-a5b964fe-d9fb-48fd-8828-fbde801e6f50.png)

The gap results to wasted space on score, and it would still persist after decreasing stretch.

**Expected behavior**
Gap should not be there, and the note should be centered/fit properly inside the pick-up measure when covering whole duration.

**Platform information**
 - OS: Windows 10
 - Version: 4.0.0.222931342 (released early public beta)

**Comment by oktophonie** [comment]
Good catch! I'm going to guess that this is the minimum measure width being applied even to what might be a very short anacrusis. Clearly, an exception should be made.
