### ISSUE TITLE
[MU4 Issue] Several problems with system-line objects

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#14296]
**Describe the bug(s)**
We have _serious_ problems handling system-line objects when they are created from a staff that isn't the first of the score. Specifically, when the system line is created on a note, but the first staff doesn't contain any chordRest in the same segment, the result is basically random. All of these issue affect System-text-line items but also, crucially, tempo change lines. All of these problems have a common cause in the well known, general problem that lines can't be attached to rythmic positions but only to chord/rests. However, they are also separate problems with specific separate causes.

1. This is the most serious one: if the start point of the system line is mid-way through a measure, the line will not be saved, and thus goes lost upon closing-reopening the score.

https://user-images.githubusercontent.com/93707756/199779860-d2af3413-46ff-4d98-ad12-a835b61e3e60.mp4

2. If the start point is mid way of a measure, layout goes completely out of place. But only after a certain measure. 

https://user-images.githubusercontent.com/93707756/199776596-93ee4430-9c85-4d05-908d-62d80e0ced74.mp4

3. Layout goes completely out of place, but oppositely, if mid-way of the first measure.

https://user-images.githubusercontent.com/93707756/199777010-0d7fa739-9d58-4447-9f99-11eb0b230f9a.mp4

4. If entered with range selection (shift+click) the line will go above the top staff as expected. But if entered with list selection (ctrl + click), the line goes above the selected staff. 

https://user-images.githubusercontent.com/93707756/199778513-31f6a59e-19aa-47e2-8f4f-013f494cb5d5.mp4

5. If the end point of the selection is mid-way through a measure, it will extend until the end of the measure, and not until the selected point.

https://user-images.githubusercontent.com/93707756/199780463-b26ae766-a5cf-45df-b2a7-12878e7ccba0.mp4

6. The issue repoerted in #14212, namely that the line disappear if it has been put on a rest and then a note takes its place. This is the less serious of all the issue IMO, but still annoying.

https://user-images.githubusercontent.com/93707756/199783494-6413b00a-fa50-4572-bf08-f35ebe938588.mp4

**Comment by mike-spa** [comment]
Oh, and I forgot another very obvious (and very bad) one.

7. Tempo lines (unlike tempo text) will disappear if the top staff is hidden

https://user-images.githubusercontent.com/93707756/199930041-1ce6ddd3-14c0-439c-8f6d-7baa6f780b91.mp4

**Comment by mike-spa** [comment]
8. Tempo lines are not saved in parts if they aren't open.

https://user-images.githubusercontent.com/93707756/200559737-a251dc66-f6c9-4653-abc8-2974b5e4547d.mp4

**Comment by oktophonie** [comment]
Just a couple of extra things.

Copying/pasting one of these lines (as opposed to inputting from the palette) will put the copies on the stave which was selected:
![image](https://user-images.githubusercontent.com/20604032/200824578-927cb327-5a6b-423d-bb96-539c1933bd01.png)

Also tempo lines which begin in the middle of a longer duration in some parts, end up in the wrong position in parts. In this score:
![image](https://user-images.githubusercontent.com/20604032/200826499-8842a018-bf33-4a31-85e0-b74b0fe739a5.png)

The viola part appears as expected:
![image](https://user-images.githubusercontent.com/20604032/200826608-eb91b919-a9a5-4735-bb6d-331bc54acc93.png)

But in the others:
![image](https://user-images.githubusercontent.com/20604032/200826782-a6accba4-72dc-44db-bd1f-67eecc12bce5.png)
The 'rall.' which began half way through bar 4 ends up off to the left of the system

Note also that the 'Lento' has vanished. (This is actually not a regression - 3.6 does the same.)

**Comment by dxing97** [comment]
Another fun one: reordering instruments can cause system text to move, especially in multi-instrument parts. 

https://user-images.githubusercontent.com/3182625/209049912-f535f6d0-75d7-4635-a3a4-ef154ff226ca.mov

**Comment by Tantacrul** [comment]
Even though there have been a few good fixes for the issues above, I can still find some more.

I've managed to get some seriously messed up tempo lines in this score:
https://www.dropbox.com/s/hif6b020ppit43q/The%20Griggles%20Part%202.mscz?dl=0

Check out Violins 1 & 2 for an example.

Moved this to Patch Release V2.

---

Process:
1. I added Accel / Rit lines
2. I cut some measures and then added time signatures so they added up
3. I added some more time sig changes in a few places
4. Some of the parts have impossible to fix rit. and Accel. lines (Violins 2, Violins 1, Violoncellos, etc.)

**Comment by cbjeukendrup** [comment]
Steps to reproduce from scratch:
1. Create score 
2. Create the parts
3. Add tempo line spanning measure 1 and 2
4. Change time sig from 4/4 to 3/4 
-> in what's now measure 3, two rests are written, to make sure that the tempo line ends on a rest (as it can't end on a non-note-or-rest segment yet)
5. Select measure 3 and press backspace to replace the two rests with one full measure rest
-> in the full score, the tempo line is (seemingly) shortened, but in the part, where multi-measure rests are enabled, it has no valid end segment anymore
6. Save, close, re-open
-> now the tempo line is gone in the full score, and in the part score it is still there but with no valid end segment.
