### ISSUE TITLE
[MU4 Task] Disable ability to give same name to multiple parts

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#14290]
**Task description**
To avoid unexpected errors in the handling of parts, we should disable the ability to use the same name for more than one part. 

The flow for this would be:

1. User creates a new part
2. User double-clicks to rename their part
3. They choose a name that already exists for another part
4. They see this error message:

<img width="664" alt="Group 98" src="https://user-images.githubusercontent.com/86290556/200014181-11a8fa40-a162-499e-b251-87304c240e7d.png">

Note there should be a maximum character limit set for the text input field: I'm again going to suggest 40 characters.

A full design specification has been sent to @RomanPudashkin.

### Default naming convention ###
An extra step we will have to take here is to change the current naming convention when new parts are created. So, instead of every new part being given the default name **Part**, only the _first_ new part will take this name. All other subsequently created parts will have a numerical suffix in parentheses appended. I.e.:

First new part: **Part**
Second new part: **Part (1)**
Third new part: **Part (2)**
etc...

@Tantacrul FYI

**Comment by DmitryArefiev** [comment]
Fixed in #14288
