### ISSUE TITLE
[MU4 Issue] Parts from score show in Beta but do not show in recent nightlies

### ISSUE THREAD

**Issue by dragonwithafez** [musescore/MuseScore#14295]
**Describe the bug**
In the following score, there should be an individual Violin part aside from the main score: [Introduction et Rondo Capriccioso.zip](https://github.com/musescore/MuseScore/files/9931024/Introduction.et.Rondo.Capriccioso.zip). This exists fine in the Beta, but opening the same score in the nightly shows no part scores. Opening the Parts dialog shows three parts: Piano, "Violin.", and Violin. None of these correspond to the heavily customized layout of the Violin part from the Beta.

**Expected behavior**
Parts should not be deleted between versions.

**Screenshots**
Behavior in Beta:
![Screenshot 2022-11-03 121243](https://user-images.githubusercontent.com/57819859/199774705-362e5b42-1649-4838-bcdc-42a844aaf556.png)
![Screenshot 2022-11-03 121257](https://user-images.githubusercontent.com/57819859/199774707-fccff197-0974-46e8-a079-1cc18d3637dc.png)

Behavior in 11/3 Nightly:

![Screenshot 2022-11-03 121322](https://user-images.githubusercontent.com/57819859/199774767-6ad41af4-2b80-42d3-842d-81f14cad4203.png)
![Screenshot 2022-11-03 121335](https://user-images.githubusercontent.com/57819859/199774771-2c17baca-5483-47a1-8655-c26fd322e7ed.png)
![Screenshot 2022-11-03 121604](https://user-images.githubusercontent.com/57819859/199775393-18134ceb-197e-4c97-ab40-fa64546a57dd.png)
![Screenshot 2022-11-03 121616](https://user-images.githubusercontent.com/57819859/199775394-bc3f9553-016b-4279-91ac-75f1db0482c1.png)

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223070413, revision: github-musescore-musescore-36a8ffa

**Comment by Tantacrul** [comment]
We have made an announcement on the Discord server about this, which I'll post here:

---

**Important note about part scores**

We have had to make necessary changes to the file format to handle how part scores are handled . These absolutely had to be done prior to the release of MS4.0 or else we would have needed to wait until MS5.0.

For this reason, parts created in the alpha or beta release will be interpreted differently in nightly releases going forward.

1. Any changes you made to part scores (engraving alterations, etc.) will be lost. A new part will be generated instead
2. You will see new, duplicated parts created with one of the duplicated scores being blank. You can just delete those
3. This does not affect scores coming from previous 'official' MuseScore releases
