### ISSUE TITLE
[MU4 Issue] Piano won't play same note while sustaining on different staff.

### ISSUE THREAD

**Issue by xman2156** [musescore/MuseScore#14301]
**Describe the bug**
When sustaining a note on one staff then trying to play the same note on a different staff, the note doesn't replay.

**To Reproduce**
1. Create a score for piano, using Muse Sounds, 120 BPM
2. Create a measure sustaining a note on top staff, with a note a beat later on top staff
3. Play
4. Hear error: The note doesn't play on the bottom staff

**Expected behavior**
The note should be played again when the bottom staff calls for it

**Screenshots**
Here is a sample to try
![image](https://user-images.githubusercontent.com/34029777/199815648-b79289ac-2dfe-4dd1-8155-1a22073df3c4.png)

**Platform information**
 - OS: Windows

**Comment by cbjeukendrup** [comment]
Related to #13853
