### ISSUE TITLE
[MU4 Issue] No sound when using Plogue Sforzando

### ISSUE THREAD

**Issue by Reloup38** [musescore/MuseScore#14306]
(Edited by @DmitryArefiev )

**Describe the bug**

3. **Plogue Sforzando** doesn't seem to work at all for me

For Sforzando :
1. Load Sforzando, and load a preset
2. Nothing seems to play

**Platform information**
 - OS: Windows 7, i was using the last nightly (04/11 at 04:42)

**Comment by cbjeukendrup** [comment]
_If_ we manage to reproduce and fix this, then it would be a good candidate for 4.0.2.

**Comment by Tantacrul** [comment]
@DmitryArefiev - can you split this out? Thanks!

**Comment by Reloup38** [comment]
@Tantacrul 
Should i open new issues if i find other problems with other specific VST ?

**Comment by Tantacrul** [comment]
@Reloup38 - yes. Each problem should have its own issue. Thanks!

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev - can you split this out? Thanks!

@Tantacrul I was able to reproduce each of 4 issues, and 3 of them are mostly should be fixed together with #12523 and #14216 (but I'm not 100% sure)

 And after fixing #12523 and #14216 we can leave the current bug only for №3. Plogue Sforzando doesn't seem to work at all for me

**Comment by Reloup38** [comment]
In addition to sforzando, it seems like the plugin sfizz doesn't work at all either

**Comment by Tantacrul** [comment]
@Reloup38 - again: every individual issue needs to be logged separately. Developers can't estimate (and often fix) issues when people append loosely connected issues in comments. Please do not comment in an issue with another issue,

**Comment by zacjansheski** [comment]
Sforzando works well for me currently.  Is this still an issue or can we close it?
