### ISSUE TITLE
[MU4 Issue] Playback issue with volta brackets from MS3.6 file

### ISSUE THREAD

**Issue by Vincentwang987** [musescore/MuseScore#14319]
**Describe the bug**
The first volta always plays regardless how many times the section repeats.

**To Reproduce**
1. Download [repeat_error_test.zip](https://github.com/musescore/MuseScore/files/9943364/repeat_error_test.zip)
2. Play the file
3. See error

**Expected behavior**
The first volta shouldn't play the second time. Only the second volta should.

**Screenshots**

https://user-images.githubusercontent.com/93361820/200110977-304243b7-2a29-498f-8790-9221f9424565.mp4

**Platform information**
 - OS: Windows 11

**Additional context**
Happens on both MS Basic and Musesounds and doesn't work on a MS4 file.

**Comment by jlizhiyi** [comment]
I observe the same issue.

**Comment by Tantacrul** [comment]
I believe this is fixed now and I can not replicate the issue on this file. @jlizhiyi and @Vincentwang987 - can you confirm? If not, I'll reopen this issue.

**Comment by erinic04** [comment]
I replicated the issue just now on the latest nightly @Tantacrul

**Comment by erinic04** [comment]
Wait never mind - I hadn't refreshed the nightly page so my nightly is actually 10 days old; sorry
