### ISSUE TITLE
[MU4 Issue] Musescore cannot find Muse Sounds Percussion

### ISSUE THREAD

**Issue by Grim-O** [musescore/MuseScore#14326]
Muse Sounds Percussion cannot be selected in the mixer menus for each instrument. This issue did not exist for me until the latest beta update. Since there is no way to reinstall through the MuseHub and deleting it doesn't notify the Hub of its absence (even when restarting my laptop at every stage of my attempts), I can't use Muse Sounds Percussion at all.

**Platform information**
 - OS: Windows 10
![Screenshot (1)](https://user-images.githubusercontent.com/115939617/200120440-dc804d0a-1a64-43b2-a2e1-504b765943b8.png)

**Comment by cbjeukendrup** [comment]
To uninstall a sound via the Hub, press the Alt key while hovering over the sound, which should give you a trash can button that lets you uninstall it.

**Comment by Grim-O** [comment]
thanks for the tip but sadly, pressing that trashcan does nothing

**Comment by MarcSabatella** [comment]
For me, Alt+click works on Windows but not Linux.

**Comment by Grim-O** [comment]
strange, I'm a windows user

**Comment by Grim-O** [comment]
> To uninstall a sound via the Hub, press the Alt key while hovering over the sound, which should give you a trash can button that lets you uninstall it.

@cbjeukendrup is there any other way of doing it since the trashcan doesn't work and deleting the folders also doesn't update MuseHub. It seems to always think MuseSounds is installed

**Comment by cbjeukendrup** [comment]
I don't know of any other way... Maybe MuseHub is confused because you deleted certain files manually and thus its own database doesn't match the reality anymore? 

As a last resort, you can try the super drastic solution that Henk described here: https://github.com/musescore/MuseScore/issues/14317#issuecomment-1304778414

Anyway, maybe @iamtesch can help...

**Comment by MarcSabatella** [comment]
When Alt+click doesn't work, you can instead simply delete the folder for the sounds you want to remove.  Wherever Muse Hub says the install location is (differs between systems), look under "downloads/Instruments" and delete whatever folders you want.  Next time you run Muse Hub, it will then see that sound as having been uninstalled.

**Comment by Grim-O** [comment]
I tried that but also to no avail. I'm now doing what cbjeukendrup suggested

**Comment by Grim-O** [comment]
Henk's solution did the trick

**Comment by iamtesch** [comment]
> When Alt+click doesn't work, you can instead simply delete the folder for the sounds you want to remove.  Wherever Muse Hub says the install location is (differs between systems), look under "downloads/Instruments" and delete whatever folders you want.  Next time you run Muse Hub, it will then see that sound as having been uninstalled.

This is not recommended - generally, manually removing only some files in the folder may leave the hub in an unstable state. If alt-click to remove doesn't work, can you try a PC restart first? If that doesn't work, I will look into other diagnostics

**Comment by MarcSabatella** [comment]
Yeah, I can't say I've felt good about that hack, but it does basically work.  Anyhow, I've rebooted my computer many times, Alt+click has never worked on either of my Linux systems for me.  Upon pressing Alt, the check turns into a trashcan and the tooltip "Click to uninstall" appears, but clicking does nothing at all - it doesn't even clear the tooltip.  The trashcan remains displayed, and no messages of any kind are printed to console for either muse-hub or muse-hub-service (both were started from terminal windows; the service with "sudo"). On Windows, though, it works as expected for me.

**Comment by MiguelVicenteGarcia** [comment]
Alt+click does not work for me either in Windows 10.

**Comment by cbjeukendrup** [comment]
(@iamtesch to clarify: @MiguelVicenteGarcia just reported on Discord that after updating, Muse Choir does not appear in MuseScore anymore for him.)

**Comment by MiguelVicenteGarcia** [comment]
Finally it worked fine this morning. Uninstalled Muse Choir with Alt+click, reinstalled and I was correctly recognized by MS4.
