### ISSUE TITLE
[MU4 Issue] Cannot get muse hub to work on a fedora 35: torrent files are not downloaded

### ISSUE THREAD

**Issue by EB2000** [musescore/MuseScore#14325]
I am using a linux fedora 35 computer, and I am trying to make muse-hub works. I could install the program, run the background service, run the frontend, but no downloading occurs. I tried to work around the problem, but ultimately failed. I am now going into details

For redacting this bug report, I erased /srv, desinstalled muse-hub and started from scratch.

### Installing
I downloaded a muse-hub.deb, converted it into a .rpm using alien, installed dependencies by hand and then could finally install muse-hub. I am lucky to run a fedora 35 which provides liblttng-ust.so.0()(64bit) in the package lttng-ust (a requirement of muse-hub). Fedora 36 provides liblttng-ust.so.1()(64bit), and so dependencies are harder to meet, see bug #13919

### Initial logs
At this point I haven't yet run muse-hub. There are some logs in /srv/muse-hub/logs/current.txt . Here are some interesting bits:
```
2022-11-05 08:50:38.4917|INFO|Muse.Service.Interop.ServiceCore|Setting SSL_CERT_DIR to /etc/pki/tls/certs
2022-11-05 08:50:38.5243|INFO|Muse.Service.Interop.ServiceCore|Setting SSL_CERT_FILE to /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
[...]
2022-11-05 08:53:14.5937|ERROR|Muse.Service.Interop.ServiceCore|Other alert: 50: could not map port using UPnP[192.168.0.13]: no router found
2022-11-05 08:53:14.5937|ERROR|Muse.Service.Interop.ServiceCore|Other alert: 50: could not map port using UPnP[192.168.0.13]: no router found
2022-11-05 09:05:41.3038|ERROR|Muse.Service.Interop.ServiceCore|Other alert: 49: successfully listening on [TCP] 192.168.0.13:6881
2022-11-05 09:05:41.3064|ERROR|Muse.Service.Interop.ServiceCore|Other alert: 49: successfully listening on [uTP] 192.168.0.13:6881
2022-11-05 09:05:42.4309|ERROR|Muse.Service.Interop.ServiceCore|Other alert: 49: successfully listening on [TCP] [fe80::2c8b:524e:f717:4df1%wlp2s0]:6881
2022-11-05 09:05:42.4318|ERROR|Muse.Service.Interop.ServiceCore|Other alert: 49: successfully listening on [uTP] [fe80::2c8b:524e:f717:4df1%wlp2s0]:6881
2022-11-05 09:08:17.3066|ERROR|Muse.Service.Interop.ServiceCore|Other alert: 50: could not map port using UPnP[192.168.0.13]: no router found
2022-11-05 09:08:17.3082|ERROR|Muse.Service.Interop.ServiceCore|Other alert: 50: could not map port using UPnP[192.168.0.13]: no router found
```
The "successfully listening" bit is hopeful, but why does it comes 15 minutes after starting the service. Weird. Should I be worried about the `no router found` bit?

There are also some different logs in `/var/log/messages`; every minute I have:
```
muse-hub-service[654036]: curl_easy_perform() failed: Problem with the SSL CA cert (path? access rights?)
```
However, I do have the file  `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`, provided by the package  `ca-certificates-2022.2.54-1.2.fc35.noarch`.

### Running muse-hub
I now launch muse-hub. A window appears, proposing to download some sound pack. For now, I don't click on anything. The following lines appear (among others) in the logs of muse-hub.service:
```
INFO|Muse.Service.MuseClientConnection|Received message from client -  User: eric, Type: Muse.Common.Messages.Actions.RegisterHiddenDownloadAction, Data: ItemId=musesampler;ItemType=Application;P2PInfoFile=https://muse-webservice.azurewebsites.net/musedownload/application-builds/dc02a17f-f3bc-4035-8acb-e08c341db510?entity=applicationLinuxVersion&entity-id=53df157d-e2f3-47cf-815a-40730cd6cc8f;Version=0.2.4.7;ItemName=MuseSampler
INFO|Muse.Service.Interop.ServiceCore|Registering Hidden Item (Type: Application, Id: musesampler, Name: MuseSampler)...
INFO|Muse.Service.Interop.ServiceCore|Calling register hidden download
INFO|Muse.Service.Interop.ServiceCore|Error getting .musedownload file from: https://muse-webservice.azurewebsites.net/musedownload/application-builds/dc02a17f-f3bc-4035-8acb-e08c341db510?entity=applicationLinuxVersion&entity-id=53df157d-e2f3-47cf-815a-40730cd6cc8f
ERROR|Muse.Service.Interop.ServiceCore|Error registering hidden download: musesampler: MuseSampler
INFO|Muse.Service.MuseClientConnection|Received message from client -  User: eric, Type: Muse.Common.Messages.Actions.RegisterHiddenDownloadAction, Data: ItemId=hub;ItemType=Application;P2PInfoFile=https://muse-webservice.azurewebsites.net/musedownload/application-builds/166bf15f-0a20-4c81-9990-b6c13901f41d?entity=applicationLinuxVersion&entity-id=8ff711c9-7d78-4d93-a9b5-ad3b934b63b5;Version=0.9.9.295;ItemName=Muse Hub
INFO|Muse.Service.Interop.ServiceCore|Registering Hidden Item (Type: Application, Id: hub, Name: Muse Hub)...
INFO|Muse.Service.Interop.ServiceCore|Calling register hidden download
INFO|Muse.Service.Interop.ServiceCore|Error getting .musedownload file from: https://muse-webservice.azurewebsites.net/musedownload/application-builds/166bf15f-0a20-4c81-9990-b6c13901f41d?entity=applicationLinuxVersion&entity-id=8ff711c9-7d78-4d93-a9b5-ad3b934b63b5
ERROR|Muse.Service.Interop.ServiceCore|Error registering hidden download: hub: Muse Hub
```
It cannot download the `.musedownload` files, but doesn't say why. The following files have appeared
```
/srv/muse-hub/downloads/.musedl/166bf15f-0a20-4c81-9990-b6c13901f41d
/srv/muse-hub/downloads/.musedl/dc02a17f-f3bc-4035-8acb-e08c341db510
```
but they are empty! (size 0)

### Trying to download on instrument
In the muse-hub application, I click to get the "harp" sound files. A black window pops up with the text:
```
Something went wrong, please try again later

ID: cba44cea-47bc-4c61-bf57-abcb4e998bc9
Type: Instrument
```
In the logs, I now have
```
INFO|Muse.Service.MuseClientConnection|Received message from client -  User: eric, Type: Muse.Common.Messages.Actions.StartDownloadAction, Data: ItemId=cba44cea-47bc-4c61-bf57-abcb4e998bc9;ItemType=Instrument;P2PInfoFile=https://muse-webservice.azurewebsites.net/musedownload/library-packages/a8ebbbf1-7231-41b6-ab04-6646c6bb84ba?entity=libraryVersion&entity-id=ffbc377d-4725-47bb-b466-5f3158e6cf03;Version=0.2.0;ItemName=Muse Harp
INFO|Muse.Service.Interop.ServiceCore|Downloading Item (Type: Instrument, id: cba44cea-47bc-4c61-bf57-abcb4e998bc9, Name: Muse Harp)...
INFO|Muse.Service.Interop.ServiceCore|Calling start download
INFO|Muse.Service.Interop.ServiceCore|Error getting .musedownload file from: https://muse-webservice.azurewebsites.net/musedownload/library-packages/a8ebbbf1-7231-41b6-ab04-6646c6bb84ba?entity=libraryVersion&entity-id=ffbc377d-4725-47bb-b466-5f3158e6cf03
```
The file `/srv/muse-hub/downloads/.musedl/a8ebbbf1-7231-41b6-ab04-6646c6bb84ba` has appeared, but it is empty.

I have no clue as to why the files cannot be downloaded.

### Trying to work around the problem

The logs give me the URL that muse-hub.service is trying to download. I can download them manually
```
wget 'https://muse-webservice.azurewebsites.net/musedownload/application-builds/dc02a17f-f3bc-4035-8acb-e08c341db510?entity=applicationLinuxVersion&entity-id=53df157d-e2f3-47cf-815a-40730cd6cc8f' -O sampler
wget 'https://muse-webservice.azurewebsites.net/musedownload/application-builds/166bf15f-0a20-4c81-9990-b6c13901f41d?entity=applicationLinuxVersion&entity-id=8ff711c9-7d78-4d93-a9b5-ad3b934b63b5' -O hub
wget 'https://muse-webservice.azurewebsites.net/musedownload/library-packages/a8ebbbf1-7231-41b6-ab04-6646c6bb84ba?entity=libraryVersion&entity-id=ffbc377d-4725-47bb-b466-5f3158e6cf03' -O harp
```
The files are bittorrent files. I can try to download the content with a standard bittorrent client. It worked for me with qbittorrent. (with ktorrent, I could download the instruments, but not the hub and sampler torrents. Weird).

The "hub" torrent contains another copy of `muse-hub.deb`. Why is it needed ?
The "sampler" torrent contains the file `musesampler-linux-0.2.4.7.tar.zip` which contains `libMuseSamplerCoreLib.so`
The "harp" torrent contains a directory structure `Muse Harp`

I moved `libMuseSamplerCoreLib.so` to `/usr/lib` and  ran `ldconfig`. Then, I moved `Muse Harp` to `/srv/muse-hub/downloads/Instruments` and launched musescore 4 (version `MuseScoreNightly-223080420-master-2c34155-x86_64.AppImage`)

It doesn't work: I cannot have musesound fonts. Inspecting what happens, musescore does load the `libMuseSamplerCoreLib.so` library, and then checked on the file `/srv/muse-hub/downloads/Instruments/.instruments` which seems to contain a database of downloaded instruments. Even though the "Muse Harp" instrument is present in the directory, it is not registered in the `.instruments` file and the MuseSampler library does not see it.

### Conclusions

No muse sound for me. The Muse-hub fails to download the files. I can download them manually, but without a correct  `/srv/muse-hub/downloads/Instruments/.instruments` database, they are not being used.

- Why aren't the downloads working? It is not a network issue as I can download them with a different client.
- Could I have the `.instruments` files that would allow me to register the instruments manually?

Thanks,
Éric Brunet

**Comment by EB2000** [comment]
Hi!
I managed to make it work, by doing two things:

1. I configured my router to redirect connections from the outside to my computer (UPnP).
2. I added a link:
```
sudo ln -s /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt
```
(I had noticed that muse-hub.service tried to open `/etc/ssl/certs/ca-certificates.crt` and failed, because I have no such file. This is weird, because in the first lines of the logs, there is `INFO|Muse.Service.Interop.ServiceCore|Setting SSL_CERT_FILE to /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`.)

I am  not sure which of these changes did the trick, or if both were needed. Anyway, I am downloading everything now, and I don't want to change anything on my computer by fear of breaking it again.

Éric Brunet

**Comment by iamtesch** [comment]
Fedora is not currently supported; right now, Muse Hub is only designed to run on debian-based linux distributions.  We will be adding support for other distributions in the future.

That said, the core issue here is the error:
`muse-hub-service[654036]: curl_easy_perform() failed: Problem with the SSL CA cert (path? access rights?)`

The linking fix you did should do the trick for now; the other change shouldn't be necessary.

I admire your debugging but I would be cautious with trying the other workarounds (manually downloading files and moving them around); as we improve and tweak the services, this will not be a stable approach.

**Comment by iamtesch** [comment]
Closing in favor of #13919

**Comment by EB2000** [comment]
Ok, fair enough.
This is beta, it is ok if some fiddling is required. Some remarks:
- Thanks for everything. The sounds are very good!
- They are also computationally demanding. Musescore took 30 minutes to export into mp3 a 5 minute orchestral piece... That's the price for having a quality mp3, I guess.
- I still wonder why musehub pretends to use the certificate file `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`, as seen from the second line of the logs (`Setting SSL_CERT_FILE to ...`), while in fact it uses `/etc/ssl/certs/ca-certificates.crt`. I would have found the workaround some hours earlier if the logs had mentioned the latter file...
- I love musescore and muse-sounds, but I quite dislike muse-hub. The purpose of muse-hub is to download files, check for updates, and maintain consistency between the program, the muse-sampler library and the samples. This is exactly the job done by the package manager, in any OS and distribution. Ideally, in the long run, there should be a Musescore package, a Musescore-musesampler package, and a series of Musescore-instrument package, with correct dependencies, and the package manager would do muse-hub's job.

Well, thanks again for the wonderful software.

**Comment by cesarizu** [comment]
On openSUSE you need to install `ca-certificates-steamtricks` to get the `/etc/ssl/certs/ca-certificates.crt` file
