### ISSUE TITLE
[MU4 Issue] MuseScore crash in some scenarios during playback with MuseSounds (Choir)

### ISSUE THREAD

**Issue by eg0n1984** [musescore/MuseScore#14324]
Steps to re-create the crash:

- Start MU4
- Create New score
- In choose instruments, select Tenor
- Change the sound to Muse Sound Choir Tenor (using the mixer)
- Start Note entry (press N)
- Try to enter the first note C
- Now crash

See screenrecord:
![mu4-crash-tenor](https://user-images.githubusercontent.com/13550012/202639365-9b6dfdba-85b7-430d-9254-92f0ad4f3b0a.gif)

MU4 Log file:
[MuseScore_221118_080733.log](https://github.com/musescore/MuseScore/files/10038893/MuseScore_221118_080733.log)

MU4 New Project file (renamed to zip): 
[new_project.zip](https://github.com/musescore/MuseScore/files/10038920/new_project.zip)

MU4 dumps folder:
[dumps.zip](https://github.com/musescore/MuseScore/files/10038922/dumps.zip)

If there is more data/information you need, please let me know.

OS: Windows 10

**Comment by cbjeukendrup** [comment]
I seem unable to reproduce this. Does it also happen with newly created scores for you, or just this one? If the latter, could you please upload the score? (You'll need to put it in a ZIP file first, otherwise GitHub doesn't let you upload it)

**Comment by mmeyn** [comment]
I had a similar problem (crash while inputting choir) and can reproduce it on my Linux system:

1. Have Muse Sounds Profile set as default.
2. Create a new score containing a Tenor as single “instrument”, using default time signature etc.
3. Try to enter a dotted quarter f by keyboard (n 5 . f) and see MuseScore crash.

**Comment by eg0n1984** [comment]
> I seem unable to reproduce this. Does it also happen with newly created scores for you, or just this one? If the latter, could you please upload the score? (You'll need to put it in a ZIP file first, otherwise GitHub doesn't let you upload it)

Please note that is an sheet created in MU 3.6 and open in MU 4
[Gloriosa_Mae_de_Deus_MCarneiro.zip](https://github.com/musescore/MuseScore/files/9955671/Gloriosa_Mae_de_Deus_MCarneiro.zip)

**Comment by mccoydtromb** [comment]
I'm noticing the Tenor is particularly troublesome. On a new MU4 score, adding SATB first does not assign the voices correctly. I get 3 altos and a bass in that order.
But more troublesome is that if I already have some music in the choir, then change to Tenor sound it sometimes crashes immediately, sometimes allows playback for a few seconds then crashes, sometimes when the Tenor is resting!

**Comment by henkdegroot** [comment]
@cbjeukendrup, here is my steps to re-create the crash:

- Start MU4
- Create New score
- In choose instruments, select Tenor
- Change the sound to Muse Sound Choir Tenor (using the mixer)
- Start Note entry (press N)
- Try to enter the first note C
- Now crash

See screenrecord:
![mu4-crash-tenor](https://user-images.githubusercontent.com/13550012/202639365-9b6dfdba-85b7-430d-9254-92f0ad4f3b0a.gif)

**Comment by henkdegroot** [comment]
Another scenario I noticed.

- Start MU4
- Create New score
- In choose instruments, select Soprano
- Start Note entry
- Enter a C
- Leave Note entry
- Change the sound to Muse Sound Choir Tenor (using the mixer)
- Now crash

**Comment by cbjeukendrup** [comment]
This crash seems to be Windows only. On Windows I can reproduce it on the first try, but on macOS not at all.

**Comment by MarcSabatella** [comment]
On Linux I managed to reproduce it once in many attempts.

**Comment by Tantacrul** [comment]
@eg0n1984 - thanks very much for all the detail. Can you try this new build, where a lot of Windows-specific issues have been addressed and let us know if it is still happening? Same to anyone else who could reproduce this.

https://github.com/musescore/MuseScore/suites/9417801459/artifacts/444885402

**Comment by henkdegroot** [comment]
> thanks very much for all the detail. Can you try this new build, where a lot of Windows-specific issues have been addressed and let us know if it is still happening? Same to anyone else who could reproduce this.

Installed this build and MU4 still crashes when I create a new score with Tenor and Muse Sounds.

**Comment by mccoydtromb** [comment]
Trying to test this, but Muse Hub is stuck trying to install Choir and doesn't get anywhere, just spinning. And in doing so got rid of the existing choir in MU4. Other libraries have updated fine, but choir is stuck. Tried restarting, tried power cycling Muse Hub.

**Comment by mccoydtromb** [comment]
On my home PC now, got the new nightly, works with the other voices, still crashes as soon as I try to playback any tenor.

**Comment by Tantacrul** [comment]
OK, thanks! One other question: does it do this with MS Basic too?

**Comment by henkdegroot** [comment]
MS Basic works fine.

Another scenario I noticed.

Start MU4
Create New score
In choose instruments, select Soprano
Start Note entry
Enter a C
Leave Note entry
Change the sound to Muse Sound Choir Tenor (using the mixer)
Now crash

**Comment by henkdegroot** [comment]
Just adding something I noticed today. I have installed todays MU4 nightly and Muse Sounds on a Windows 11 machine.
Choir - Tenor is working correct on that machine, no crash. The first note entered is very loud, the second note has a much lower volume. Maybe that is a hint to what my cause this issue.

**Comment by Tantacrul** [comment]
Could you re-test this please. We recently fixed the issue with Tenors crashing the app. Thanks!

**Comment by mccoydtromb** [comment]
Yes! No more crashing on Win 10.

**Comment by henkdegroot** [comment]
working here as well, no crash when using Tenors on Win10.
