### ISSUE TITLE
[MU4 Issue] MuseScore4 crashes when pressing 0 in staccato mode

### ISSUE THREAD

**Issue by simon14264** [musescore/MuseScore#14322]
**Describe the bug**
MuseScore4 crashes when pressing 0 in staccato mode.

**To Reproduce**
1. Press N
2. Press shift+s
3. Press 0

**Expected behavior**
Crash

**Platform information**
 - OS: Windows

**Additional context**
Was on Viola and eigth notes.

**Comment by cbjeukendrup** [comment]
I think this is a duplicate of #13740, which has been fixed meanwhile. Could you please try again in the latest beta version (in Muse Hub, check for updates) or the latest Nightly build (https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-nightly-builds)?

**Comment by RomanPudashkin** [comment]
Please reopen the issue if you can still reproduce the crash
