### ISSUE TITLE
[MU4 Task] Instrument order is confusing

### ISSUE THREAD

**Issue by Grim-O** [musescore/MuseScore#14327]
Often throughout the program, instruments, even when listed in their instrument families, are listed alphabetically instead of in orchestral or otherwise appropriate order. This makes it very confusing to look up instruments because not only do I expect instruments to be in orchestral order, it also makes sense to put them in this way as they are listed from high to low registers, teaching new users, through design, which instruments belong (roughly) in which range.

It would thus be awesome to see instruments listed in orchestral order instead of the now often prefered alphabetical order.

**Comment by MarcSabatella** [comment]
@Tantacrul - a small thing, but really annoying.  @shoogle - I recall you having mentioned what the fix would be, just skipping the sort and using the raw instruments.xml order?  Would nulling out this function be the way to go - https://github.com/musescore/MuseScore/blob/446091c86863da18fb9b022cfd4b805c0a9a6e2f/src/instrumentsscene/view/instrumentlistmodel.cpp#L309?  Obviously, we'd want to ensure the raw ordering really is good.

If it's agreed this is good to do, and as simple as that, I can do a PR.

**Comment by Tantacrul** [comment]
@shoogle - unless you think there's an easy way for you to solve this, I do no think we should try to tackle it now.

**Comment by MarcSabatella** [comment]
Actually, I now have a solution, it sorts accord to the instruments.xml order:
![image](https://user-images.githubusercontent.com/1799936/200684041-1975fbf7-682d-4902-9a25-0f24214d1938.png)
Perhaps better would be to somehow check the currently-select score order and use that, but really, most of the variations between different score orders are about rearranging families more so than individual instruments within families.  So it wouldn't actually make much difference.

I'll clean this up and then people can review.

**Comment by MarcSabatella** [comment]
Current PR #14431 is my proposed fix; not sure if there is a formal process to request review.

**Comment by Tantacrul** [comment]
Thanks, Marc! 

Both @oktophonie and @shoogle will take a peek. Would be great to merge, once they are happy.
