### ISSUE TITLE
[MU4 Task] Design Consideration: More button in Properties tab

### ISSUE THREAD

**Issue by Grim-O** [musescore/MuseScore#14334]
In certain cases, for example when selecting dynamics, there is a more button which opens an extra little window with some more options although there is enough space to add those options to the properties tab without the need of a more button at all. 
I would suggest simple adding these features to the tab without the more button, perhaps in a "more" section.
![Screenshot (4)](https://user-images.githubusercontent.com/115939617/200123934-984d4988-469d-4b55-805e-8137f738b80c.png)

**Comment by Tantacrul** [comment]
We created the 'More' button so as not to overwhelm users with tons of options (many of which are little used). However, there is always an ongoing conversation about what _deserves_ to be promoted to the main panel.

Also, on some devices, there is not enough room - especially when you select more than one item.
