### ISSUE TITLE
[MU4 Issue] Missclicking while selecting several things, although still holding control shouldn't remove all the selections.

### ISSUE THREAD

**Issue by Grim-O** [musescore/MuseScore#14338]
When you make a selection (holding the control button) and then try to select something else but accidentally click on empty space, the selection is cleared. 

It would be awesome if the selection is kept because it often happens that I'm selecting things quickly and misclick or select tiny things such as staccato markings and also misclick.

**Comment by MarcSabatella** [comment]
Indeed, and see also https://github.com/musescore/MuseScore/issues/10225.  These are two related features that were implemented together (same code) in MuseScore 3 but seem to have been lost in MuseScore 4.

**Comment by cbjeukendrup** [comment]
Might be a good first issue; hint: `NotationViewInputController`.

**Comment by MarcSabatella** [comment]
I assume you mean not clearing the selection would be easy first issue.  I think reimplementing the select-element-underneath behavior is rather trickier.

**Comment by octopols** [comment]
> Might be a good first issue; hint: `NotationViewInputController`.

I removed the condition which called clearselection in that file which I think fixes the issue but after using it for a while the experience feels quite odd, like whenever I want to get rid of selections I have to click somewhere outside the canvas or use my arrow keys.

**Comment by Grim-O** [comment]
the way I think it should work (and how I've seen it work in other programs) is that when you hold control, the selection isn't cleared regardless of where you click and when you don't hold control the selection is cleared when clicking anywhere. If you click on another element (possibly part of the larger selection) without control, only that one element should be selected.

**Comment by octopols** [comment]
> the way I think it should work (and how I've seen it work in other programs) is that when you hold control, the selection isn't cleared regardless of where you click and when you don't hold control the selection is cleared when clicking anywhere. If you click on another element (possibly part of the larger selection) without control, only that one element should be selected.

That makes sense, let me look into the code to see if I can make that work.
