### ISSUE TITLE
[MU4 Issue] MacOS Muse Hub Problems

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#14357]
Hey, I might have mentioned this before, but just for the sake of issuing only on this post, I need to say something about the Muse Hub problems I'm having on my Mac Os.

Whenever I try to open the application after it installed, I get a message saying that I am unable to connect to the Helper. Not only that, but whenever I opened up the interface, there are no application + Muse Sound pack icons. MuseScore 4 and Muse Sounds are working well, but not the Muse Hub application.

Again, I've mentioned this before, but I understand that I should've done it in a separate issue, so there you go.

**Comment by iamtesch** [comment]
This may be an issue from installing or updating from an early beta; can you:
(1) Let me know which version of MacOS you are using.
(2) Try these steps and see if the problem is resolved
 a) right click on the hub, and click "uninstall helper"
 b) go to "applications" and drag "muse hub" to the trash
 c) reinstall the latest hub from musehub.com
 d) update this issue to let me know if this resolves the problem

**Comment by cunningar0807** [comment]
Well @iamtesch, I have a Mac OS Monterey, version 12.6.1.
I did re-install the latest version of Muse Hub, and opened it up, and I STILL get the unable to connect to Server message, and STILL got nothing showing up in the application + Sound Pack installations.

Sorry, I couldn't find a way to reply to your comment.

**Comment by VSTHero** [comment]
Do you have the installers still mounted on the desktop - I found when those are present I would get the helper error.  If I ejected them MuseHub and downloads would function.

**Comment by cunningar0807** [comment]
@VSTHero I don't know where the installers are. I still get the error even when they are or aren't there, but my answer is I don't know.

**Comment by VSTHero** [comment]
Well either way, it shouldn’t matter but thought it might provide a clue to where the bug is.  It seems like these problems are linked with the older OSes, I’m using BigSur; I haven’t tried loaded MuseHub in a few days so I’ll check today.

**Comment by telephono** [comment]
I have the same issue on macOS Monterey 12.6.1
![Screenshot 2022-11-11 at 15 23 29](https://user-images.githubusercontent.com/111712/201360079-2ddb4f71-b70e-48ef-a87a-33624c89facf.png)

When I try to uninstall the helper, MuseHub just displays a warning and quits.
![Screenshot 2022-11-11 at 15 22 51](https://user-images.githubusercontent.com/111712/201360216-36ad6612-4e98-40f4-a513-3e805c8292cd.png)

I already tried to deinstall MuseHub, MuseScore and deleted the Container ~/Library/Containers/com.muse.hub
When I restart my computer, I get a prompt to install the Muse Hub helper, but after that the error message from above apears again and MuseHub quits.

**Comment by PWmercy** [comment]
Identical issue

**Comment by cunningar0807** [comment]
I'm just not quite sure if this issue will ever be fixed soon. Maybe once MuseScore 4 completely releases? Though I understand Muse Hub works on Windows and Linux, so why does it not work on Mac?

**Comment by telephono** [comment]
@cunningar0807 It works on macOS. I have a MacBook (Apple M1 2020) with macOS Ventura 13.0.1 running MuseHub and MuseScore just fine.

Don't know what hardware the other folks are using. Maybe my Mac mini (Late 2014) is just to old?

**Comment by ModernMozart** [comment]
Also on an M1 2020 Macbook, but on Big Sur, and Muse Hub crashes on opening when connected to the internet

**Comment by cunningar0807** [comment]
Well, again, this is what I get after I open up Muse Hub.

![Screen Shot 2022-11-15 at 5 56 16 AM](https://user-images.githubusercontent.com/32210900/201904350-fe81c8d0-c145-4b84-9202-3b0cd028f1f1.png)

Though whenever I downloaded MuseScore this way, after setting everything up in the app, it should give me tutorial videos which don't show up after the setup completion.

Also, I can't install Ventura because whenever I download it, I keep getting a message saying that the OS is not available.

**Comment by telephono** [comment]
@cunningar0807 You probably can't install Ventura because it's not supported on your Mac. I have the same "problem" on my old Mac mini (Late 2014)...

**Comment by cunningar0807** [comment]
I understand. So does this mean that Muse Hub won't show up the app+Sound pack icons in an old version of any Mac OS system?

**Comment by barnard-optician** [comment]
Hello, i'm having the issues mentioned here too.

Latest version of Muse Hub on macOS 12.5. MuseHub is basically unusable.

**Comment by telephono** [comment]
After downloading the current MuseHub from https://musehub.com I can use MuseHub and MuseScore on macOS 12.6.x without problems...
Thank you very much!

**Comment by david-bonin** [comment]
Having the same issue, for me it's moving the Muse Sounds location which seems to have broken Muse Hub, now it asks to install a helper but it's not working and MuseHub cannot be started. I've reproduced the problem 2-3x by installing/reinstalling.

**Comment by david-bonin** [comment]
Problem may be that MuseHub needs to be given disk access, that and along with direct download from MuseHub website (and not MuseScore) seems to work.

**Comment by david-bonin** [comment]
So as it turns out, the problem seems to reproduce itself over and over. After a reboot, MuseHub asks to install an helper tool if you say yes it stops working, if you hit cancel MuseHub loads up but isn't able to connect to the internet. 

<img width="250" alt="image" src="https://user-images.githubusercontent.com/30135692/208256559-5b5a2c5a-ca8e-4d40-8a8a-403704d67a1c.png">


MuseScore and MuseSounds still work though so I think I'll stop worrying about MuseHub for awhile.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/30135692/208256511-ed2b0e32-f049-411a-9506-7de384938261.png">

**Comment by aarushbothra** [comment]
I managed to fix the helper issue by giving muse hub full disk access in system and privacy settings.

**Comment by barnard-optician** [comment]
> After downloading the current MuseHub from https://musehub.com I can use MuseHub and MuseScore on macOS 12.6.x without problems... Thank you very much!

I think the hub is working fine for me again now with the stable release (fingers crossed).

**Comment by oktophonie** [comment]
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.
