### ISSUE TITLE
[MU4 Task] Include more instruments for Muse Sounds

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#14358]
So I understand that Muse Sounds has almost all the instruments that you could find in an orchestra score, but I'm slightly disappointed that there aren't any patches for Euphonium, Recorders, Contra-alto/Contrabass Clarinets, Pipe Organ, Sopranino & Bass Sax, etc.

So I was thinking that the task should be adding these specific instruments to the Muse Sounds library. But for now,I'm using VST instruments that try to emulate the instruments I've mentioned before.

**Comment by Tantacrul** [comment]
We'll be gradually adding instruments over time. I think it makes sense to close this issue, since by the time we have all the instruments you are asking for, this issue will be completely ancient. It is just not actionable any time soon.

Thanks for posting it though!
