### ISSUE TITLE
[MU4 Issue] Change Actual Measure Duration in a mmRest result in crash when revert it Ctrl+Z

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14350]
**Describe the bug**
Change Actual Measure Duration in a mmRest result in crash when revert it Alt-z

**To Reproduce**
1 - Create a Score as this with mmRest
![image](https://user-images.githubusercontent.com/1835871/200137020-2fa19987-56b4-4a0d-abef-dd530dda23e9.png)
2 - Open measure Properties of the mmRest and change actual measure duration
![image](https://user-images.githubusercontent.com/1835871/200137036-32dc52e3-12c5-4dae-a039-585a732b7c7d.png) 
Change to 
![image](https://user-images.githubusercontent.com/1835871/200137051-cbc59273-26fd-4532-8607-062e90f41826.png)
3 - Apply
![image](https://user-images.githubusercontent.com/1835871/200137062-01f12dca-3b82-4da1-958b-612dc87471f3.png)
4 - Ctrl-Z result in crash

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Comment by cbjeukendrup** [comment]
Yep, reproduced. I think the easiest solution would be disallowing the Measure Properties dialog for mmrests, like we do apparently in MS3.

**Comment by Gai-Luron** [comment]
You can't disable Measure Properties because we need it to access strech measure even in mmRest.

**Comment by cbjeukendrup** [comment]
But it was disabled in MS3 too, right? Or was there another way of accessing it than via the context menu?

But of course, if someone manages to fix this and possible other bugs with Measure Properties and MMRests, I have no problem with allowing it.

In MS4, you can also access the stretch property in Properties > Appearance > Measure width. And you can use the keyboard shortcuts `{` and `}` of course.

**Comment by Gai-Luron** [comment]
Why not disable only the Measure actual field? Anyway, use of arrows button to go next or previous measure skip MMRest and I think it's not the good behaviour. MMRest it's a measure like other. I have take a look at code of MMRest in the past and I know that's no easy to manage that.
Do that you think it's better. No problem for me. ;-)

**Comment by MarcSabatella** [comment]
It's really not clear how most of the measure properties should be applied if a multimeasure rest is selected,  For some settings, it might make sense to ignore as not applicable, for others apply to the mmrest itself, fir others to apply individually to the underlying measures, for others just to the *first* or *last* underlying measures, etc.  So I can't see any value in enabling the dialog; it would just cause confusion and problems.  As mentioned, stretch is the only thing that really makes sense and it can already be accessed multiple several ways.

Note there is a style setting to control the minimum size of mmrests, you might want to increase that rather than rely on stretch so much.

**Comment by Gai-Luron** [comment]
It is not a problem of minimum size, but of proportionality. You can't do without a manual adjustment

**Comment by MarcSabatella** [comment]
Sure, but that's perfectly possible as mentioned, using the Properties panel as well as shortcuts as well as menu commands.

**Comment by Gai-Luron** [comment]
Hello, I will try to be clear with my thinking. The goal is not to impose it but rather to give that thought as a user on what seems to me to be logical for the basic user.
I remember that the inspector had been created to simplify the handling of the software and to avoid that the parameters are exploded in all the menus of the software. If we follow this logic, the Measure settings should be in the inspector and maybe this is planned in the future.
With regard to the MMRest, it also seems more logical for the workflow to find its configuration in the same place as the Measures (Inspector or the Measure configuration window). If you make exceptions on the location of settings for the same types of objects, you quickly end up with software that is difficult to learn and "Finale" is a good example of this. Finale is powerful, but very difficult for a beginner, as it is illogical in the way it works.
This is why I suggested keeping the MMRest settings in the same place as the Measurements while hiding unnecessary fields even if you can modify the MMRest settings elsewhere.
It's not up to me to choose how the software will evolve and it's not up to me to impose my ideas. For those who try to help with debugging, the goal is not to be absolutely right about how to do it. The goal, it seems to me, is to exchange and understand the other in an objective way so that the developers find and choose the best solution, not a workaround.

**Comment by mike-spa** [comment]
https://user-images.githubusercontent.com/93707756/203130644-64ad583b-6abe-41b9-a7c1-5774084a277d.mp4

The crash isn't solely connected to using the Measure properties dialog. Also changing the stretch by "}" shortcut and then doing ctrl+Z causes it to crash.
