### ISSUE TITLE
[MU4 Issue] Tempo changes in a measure cause notes to be cut off or sustain too much (metronome mark or accel./rit.)

### ISSUE THREAD

**Issue by LRenn0** [musescore/MuseScore#14369]
**Describe the bug**
When the tempo changes within a measure, notes such as whole notes will not hold for their complete value.

**To Reproduce**
1. Make a score with multiple instruments
2. Put a whole note on one instrument's part
3. Put something other than a whole note on the other instrument's part in the same measure and change the tempo within that measure (not on beat 1)
4. On playback, the whole note will not be held to the end of the measure

**Expected behavior**
On playback, the note that was played before the tempo change will hold through the tempo change and to the end of the measure.

**Screenshots**
![image](https://user-images.githubusercontent.com/117554969/200189800-7b8c1d4b-8949-432d-a2a1-5f4906a96311.png)
In a setup like this, the whole note from violin 1 will hold for 4 counts at 120 bpm. Violin 2 will play the first half note for 2 counts at 120 bpm and the next half note for 2 counts at 60 bpm. This means that the whole note being played by violin 1 will be cut off before the end of the measure and violin 2 will continue holding the half note until the end of the measure.

--

Added by @DmitryArefiev 

Good example from #17909

https://github.com/musescore/MuseScore/assets/90187801/65e884ca-eecf-4186-b8fa-63d19e156888

**Platform information**
 - OS: Windows

**Comment by Tantacrul** [comment]
Confirmed. Created an example score to demonstrate the issue.
https://www.dropbox.com/s/wmnouy3ha1j6ygu/Tempo%20change%20mid%20bar.mscz?dl=0

Happens with MS Basic and Muse Sounds, so must be an MPE thing.

**Comment by erinic04** [comment]
Also happens with soundfonts, seems to just be a global thing

**Comment by zacjansheski** [comment]
Additional issue reportsd
https://github.com/musescore/MuseScore/issues/17863
https://github.com/musescore/MuseScore/issues/15552

**Comment by DmitryArefiev** [comment]
Another similar issue 
#17909

**Comment by DmitryArefiev** [comment]
Fixed in #15609
