### ISSUE TITLE
[MuseSounds] legatos and overall sound quality reduction in latest update

### ISSUE THREAD

**Issue by Grim-O** [musescore/MuseScore#14363]
Since the latest update of MuseSounds, I've noticed quite the considerable setback in sound quality and legato playback. Mainly the strings and woodwinds seem to be affected by this. the most notable differences are hearable around the 1:20 mark in following audio clips.
Also, it should be noted that some instruments don't play exactly what it written. Most notably, the tenor and bass trombone at the start miss quite a few notes.

Playback from 1st MuseSounds release:
https://soundcloud.com/grim-ongena/the-mountain-v1/s-oOw5oap2lvi?si=facd98d8a77a41098182abb65317f083&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing
Playback from latest update of MuseSounds:
https://soundcloud.com/grim-ongena/the-mountain-v2/s-o793aTk3Fv1?si=ef7829b3cfbc485c9dc3b7a78fe70039&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing

The Score for reference:
[The Mountain v1 .pdf](https://github.com/musescore/MuseScore/files/9945805/The.Mountain.v1.pdf)
And the MuseScore project:
[The Mountain - 2 .zip](https://github.com/musescore/MuseScore/files/9945809/The.Mountain.-.2.zip)

The Percussion in the 2nd audio clip is ms basic because MuseScore no longer recognizes my MuseSounds Percussion.

**Comment by Tantacrul** [comment]
@Grim-O, can you check again and let us know if you're still experiencing issues? There have been a number of changes over the last two weeks.

**Comment by Grim-O** [comment]
@Tantacrul I checked again with the latest nightly (21/11) and the most up to date libraries and most notably the english horn and all strings still suffer from this problem. the other woodwinds seem better although still lagging behind a bit. the bassoon is the only one playing correctly.

**Comment by MarcSabatella** [comment]
FWIW, the passage in question appears to be start after the key change in bar 22, and the string and woodwind parts are dominated by triplets.  It's possible this will turn out to be another side effect of https://github.com/musescore/MuseScore/issues/14220.  I suspect it would be useful to know if there are any examples of the issue occuring somewhere that triplets are not involved.

**Comment by Grim-O** [comment]
it likely indeed is a side effect of #14220. I have so far not yet encountered any of these problems with 'normal' subdivisions. only thing I have noticed is fast passages not ending properly. alternating 16th notes end on the wrong one for example. this seems to be because the last note only triggers the end of the sample which is almost inaudible. the same is true for 8th notes at double the tempo of those 16th notes.

test file:
[Muse Sounds Test File.zip](https://github.com/musescore/MuseScore/files/10085520/Muse.Sounds.Test.File.zip)

**Comment by vpereverzev** [comment]
@Grim-O since I've already fixed #14220, take a look on a fresh nightly

**Comment by Grim-O** [comment]
it seems to be fixed in the latest nightly!
