### ISSUE TITLE
[MU4 Issue] Crash editing a cross-staff slur

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#14367]
**Describe the bug**
MuseScore 4 crashes when editing (changing anchors or flipping) a cross-staff slur

**To Reproduce**
1. Open attached file
2. Click the slur
3. Press "X" to flip it below
4. See error: crash

**Expected behavior**
Slur should flip

**Screenshots**
![image](https://user-images.githubusercontent.com/1799936/200188129-b0548b27-6bed-4df4-bd6a-301100fe5eed.png)

**Platform information**
 - OS: Linux

**Additional context**
Similar crash if you select the end handle and use Shift+Left to move the anchor to the previous note.

Not *all* cross-staff slurs reproduce this problem.  But this one - created from scratch in a nightly build a few days ago - does.  Some experimentation suggests the issue is connected specifically to the second beamed group of eighths.  If *all* of the notes are moved to the staff above, or if none of them are, no crash happens.  I can only reproduce a crash if the beamed group itself is cross-staff.  But the crash is triggered by operations on the slur, not on the notes - go figure.

[crash-on-flip.zip](https://github.com/musescore/MuseScore/files/9946530/crash-on-flip.zip)

**Comment by MarcSabatella** [comment]
Hmm.  I was testing with the nightly build from that day.  Tried again with last night's build, crashes for me the same way.  No useful info printed to console unfortunately.  Oh well.  At least it's easy to work around - set up the slur before doing the cross-staff  adjustments.

**Comment by oktophonie** [comment]
Closed as unable to reproduce, but if anything else comes to light, feel free to reopen.

**Comment by MarcSabatella** [comment]
FWIW, I can no longer reproduce.  I did see a couple of crash fixes over the last week that were sort of generalized "fix potential crash" things and suspect one of those did the trick here.
