### ISSUE TITLE
[MU4 Issue] note editing spikes CPU temperature and usage, selecting a note stutters for a second

### ISSUE THREAD

**Issue by repetabd** [musescore/MuseScore#14379]
**Describe the bug**
Every time I start to edit a specific measure, my processor's usage spikes by at least 30% each time, shortly reaching 100% in some cases, as well as increasing its power draw significantly. I don't know if this is an issue with my system (I will be checking my BIOS settings and other processing stuff shortly), but I'm going to log it here just so it's here if the problem isn't my computer.
A linked issue is that whenever I select a note to edit it, my mouse will freeze for a second while my CPU decides to freak out.

**Platform Information**
- OS: Windows 10 Home
- CPU: Ryzen 5 3600

**Comment by Fristover** [comment]
I can reproduce this too.
CPU: Ryzen 5 4600H / Intel Core i3-8130U
Both on Windows 11 22H2

**Comment by llui85** [comment]
Also can reproduce on Linux. Possibly an AMD issue?

```
Linux 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux
AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
```

**Comment by Tantacrul** [comment]
Is this when using Muse Sounds?

Can you please try this build: https://github.com/musescore/MuseScore/suites/9417801459/artifacts/444885402

And let us know if it improves matters at all? Also make sure you open the Muse Hub and get the latest changes from there too. Thanks!

**Comment by repetabd** [comment]
Most of the problems were much more apparent using the new Muse Sounds, yes. This build seems to have fixed the bulk of the issue! There are still a few hitches here and there, but I've gotten used to that with MuseScore 3. The program as a whole is a lot less intensive on my computer. Thanks!

**Comment by Tantacrul** [comment]
@vpereverzev - you'll be happy to read the above comment ^

I'm going to close this for now. We have more performance work to do on both MS4 and Muse Sounds to solve other issues, so expect this to get better again over the next week or two.
