### ISSUE TITLE
[MU4 Issue] Handle Linux dark-mode settings

### ISSUE THREAD

**Issue by AdrianVovk** [musescore/MuseScore#14377]
**Describe the bug**
MU4 doesn't currently support Linux's cross-desktop system dark mode settings. This setting provides a cross-desktop method for apps to query system settings about whether or not the user prefers a light theme, a dark theme, or has no preference. This would allow MuseScore to better respect user preferences

**To Reproduce**
1. Go to Edit > Preferences > Appearence
2. Observe that there's no "Follow System Settings" option
3. Skim MuseScore source code to see that functionality for such an option does seem to exist on Windows and macOS

**Expected behavior**
MuseScore uses the [org.freedesktop.portal.Settings](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Settings) dbus API to query the
`org.freedesktop.appearance color-scheme` setting, and integrates this functionality into MuseScore the same way it is done for Windows/macOS

**Screenshots**

**Platform information**
 - OS: Linux (using the GNOME DE)

**Additional context**
Even though this setting exists in and is provided to apps by the Flatpak portal infrastructure, running in a Flatpak container isn't a prerequisite. Many modern cross-desktop specifications are being implemented as Flatpak portals, for a couple of reasons:
1) It's a good place to define cross-desktop generic APIs (since apps need to talk to the portals anyway, to work inside the sandbox)
2) It has a mechanism for different desktop environments to provide a backends for these APIs without having to rewrite the whole thing
3) These APIs work exactly the same way inside of a sandbox as they do outside of a sandbox (so apps that make use of these APIs will Just Work™ in the sandbox)

The dark mode specification has already been implemented by the major DEs:
- KDE: https://github.com/KDE/xdg-desktop-portal-kde/blob/master/src/settings.cpp#L292-L306
- GNOME: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/blob/main/src/settings.c#L174-L184
- And others

For your referernce, [here](https://invent.kde.org/frameworks/kguiaddons/-/blob/master/src/colors/kcolorschemewatcher_xdg.cpp) is KDE's existing implementation for querying the value of the setting and monitoring it for changes. [Here](https://api.kde.org/frameworks/kguiaddons/html/classKColorSchemeWatcher.html) is a description of what that code is implementing.

**Comment by cbjeukendrup** [comment]
Thanks for these references, very interesting! I will definitely look into this for MuseScore 4.x. Or feel free to implement this yourself if you'd like!
