### ISSUE TITLE
Muse Hub: right-clicking the logo does not *always* display Muse Sampler version

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#14376]
**Describe the bug**
When you right-click the Muse Hub logo in the top-left corner of the Muse Hub window, you see a context menu, that among other things displays the Muse Hub version. Sometimes, this context menu also displays the Muse Sampler version, but sometimes it doesn't. I wonder what's the reason for that; Muse Sounds itself does work correctly in MuseScore all the time. 

Anyway, the version can currently also be checked using MuseScore, so this is a low-priority issue.

**Comment by iamtesch** [comment]
Can you let us know what operating system and hub version this is on?

**Comment by cbjeukendrup** [comment]
It's on macOS (13). 
(Oops, I had meant to specify that initially 🙂)

**Comment by cbjeukendrup** [comment]
A bit of news on this: I just opened Muse Hub and it installed some updates for some sounds, and after that, I did see the MuseSampler version in the context menu. But after quitting the MuseHub and reopening, it was gone again.

**Comment by iamtesch** [comment]
This should be fixed in the latest version of the hub -- can you reopen if this is still an issue?

**Comment by cbjeukendrup** [comment]
I can't recheck at the moment unfortunately, because Muse Hub suddenly won't launch anymore. I was not sure whether I was using the latest version, so I re-downloaded the Hub from musehub.com. When I now try to open it, first, I get a password prompt to install the new helper, then I get this error:
<img width="328" alt="Scherm­afbeelding 2022-12-07 om 20 12 13" src="https://user-images.githubusercontent.com/48658420/206274121-7f7a829a-43be-487b-93b2-895db4794012.png">
Maybe it's because the old `com.muse.museservice` is still running, so I'll retry after restarting my Mac probably tonight. But for now I seem to be stuck... 😕

**Comment by cbjeukendrup** [comment]
I'm still experiencing this, even with Muse Hub v1.0.0...

**Comment by zacjansheski** [comment]
No longer displayed in V2
