### ISSUE TITLE
[MU4 Issue] MuseSounds Percussion changes not triggering

### ISSUE THREAD

**Issue by mccoydtromb** [musescore/MuseScore#14371]
Unable to access many percussion sounds. I don't have a comprehensive list, and I'm presuming they just haven't been implemented yet. A github issue seemed like a good idea.

So far:
Triangle open and muted. Cross head and normal note head play the sound sound, as do open and mute articulations.
Same with piatti, and suspended cymbals.
There is no instrument in MU4 for Taikos. Chinese Tom-toms is closest approximation I could find and I'm guessing that's a fairly bad Asian stereotype. Equally, cannot find a way to swap between drum head and rim.
Snare drum - no way to turn snares off and on in MU4.
There is no instrument for bell tree or mark tree - metal wind chimes are the closest approximation, and they don't allow glisses.
Vibraphone - pedal markings don't dampen or release.
There is no instrument for Tubular Bells in MU4. I used Chimes and changed the playback instrument, but many (older) scores use Chimes to indicate Glockenspiel, so not the best word to use.

 - OS:  Windows

**Comment by erinic04** [comment]
I have never heard glockenspiel called chimes before. I think you might be thinking of bells, which can be either glock or tubular bells

**Comment by Tantacrul** [comment]
We have a little bit of mapping work to do and will get new articulations in shortly. I'm going to close this issue because it's more of a wishlist than a bug. Will reassess where we are with percussion once the new mapping is complete.
