### ISSUE TITLE
Muse Hub > Settings > Updates: "Last checked" date not updated at start of new day

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#14375]
**To Reproduce**
1. In Muse Hub > Settings > Updates, check for updates. 
-> Muse Hub says "Last checked: **today** at [time]". 
3. Wait until next midnight
Expected: the label now says "**yesterday** at [time]". 
Actual: the label still says "**today** at [time]", which is in fact in the future 😄 

**Screenshots**
<img width="527" alt="Scherm­afbeelding 2022-11-07 om 00 20 59" src="https://user-images.githubusercontent.com/48658420/200201204-547da31c-b97e-4398-9ee3-8e0c5748c6e4.png">

**Platform information**
 - OS: macOS; don't know about Windows

**Additional remark**
The time is shown including seconds; maybe that's a bit superfluous, but that's a trivial detail.

**Comment by wizofaus** [comment]
Is this related to the fact that "Check for updates" in MuseScore itself doesn't seem to do anything? Is that a reported issue already (I couldn't find it)?

**Comment by cbjeukendrup** [comment]
> Is this related to the fact that "Check for updates" in MuseScore itself doesn't seem to do anything? Is that a reported issue already (I couldn't find it)?

No, that is a very different kind of issue. This is purely a UI label issue, not related to any actual update check.

Regarding MuseScore's own update check: for me, it properly displays the "you're up to date" dialog. If this is not the case for you in the latest builds, then I think that's worth a new issue.
