### ISSUE TITLE
[MU4 Issue] First note doesn't play in imported MS3 file

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#14387]
**Describe the bug**

When playing a score previously created in MS3 and last saved in MS3 the first note does not play.  After saving in MS4 and re-opening playback is correct.

**To Reproduce**

1. Open a score previously created in MS3
2. Click on play
3. Note that playback starts with the second note.
4. Save score and close.
5. Open score saved in step 4
6. Click on play
7. Note that playback starts with first note.

**Expected behavior**
Playback should start with first note on all scores whether last saved with MS3 or MS4

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223080418, revision: github-musescore-musescore-2c34155
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**
The problem occurs with both MS Basic sounds and also with Muse Sounds.

**Comment by DmitryArefiev** [comment]
Can reproduce on my side too. Thanks for finding that!

https://user-images.githubusercontent.com/90187801/201888854-f8d5d39b-c01f-4d82-842a-22519b6c13a3.mp4
