### ISSUE TITLE
[MU4 Issue] VST plugin on master section sounds when bypassed

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#14394]
**Describe the bug**
The issue is reproducible with any plugin
**To Reproduce**
1. Create a score
2. Put any plugin to the Mixer master section 
3. Play the score
4. Turn the plugin off in the mixer

**Expected behavior**
Plugin is turned off and not processing audio

**Screenshots**

https://user-images.githubusercontent.com/101250347/200533205-cf26eab7-a7c4-42ad-952a-ebc6933667a3.mp4

**Comment by Tantacrul** [comment]
Confirmed. Disabling a VST effect in the Master channel doesn't actually disable it, even when saving and reopening a score.

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12
