### ISSUE TITLE
[MU4 Issue] Repeat measure symbols won't playback

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#14402]
So whenever I try to playback a score in MuseScore 4 with some repeat marks in a measure of a part, and I'm not basically talking about the repeat lines which they work fine, but just the repeat symbol from the palette, it just wouldn't playback, AT ALL, even if I switched to Muse Sounds or use MS Basic in general.

**Comment by erinic04** [comment]
This is already reported. #14234
