### ISSUE TITLE
[MU4 Issue] Time Signature Crash

### ISSUE THREAD

**Issue by Johnnos92** [musescore/MuseScore#14417]
**Describe the bug**
Crash on insertion of Time Signature

**To Reproduce**
1. Go to any bar in the attached score and insert a time signature - the specific issue happens at bar 557 but seems to also happen anywhere else

**Expected behavior**
The selected time signature is inserted within the score
**Screenshots**

**Platform information**
 - OS: Windows

**Additional context**
File Attached
[Bartok Duos All Books.zip](https://github.com/musescore/MuseScore/files/9960806/Bartok.Duos.All.Books.zip)

**Comment by oktophonie** [comment]
Can I ask which build you are using? I cannot reproduce this myself (but we did fix an issue that sounds similar to this some time ago).

**Comment by Johnnos92** [comment]
Hi Simon

Just using the version downloaded from Musehub - 4.0.0 I think is the
current build. Please note - it doesn't happen in other scores on the same
build but just that score.

Thanks,
John

**Comment by Johnnos92** [comment]
An update - I am able to change the time signature within that score but not at the required location.

**Comment by oktophonie** [comment]
Well, what time signature exactly are you trying to insert, and at exactly which location?

**Comment by Johnnos92** [comment]
At bar 557 and 34 meter

**Comment by Johnnos92** [comment]
An update - I sent it to another computer with MS4 and was able to add the 34 time signature at the correct spot but now playback is not working.
[Bartok Duos All Books.zip](https://github.com/musescore/MuseScore/files/9980078/Bartok.Duos.All.Books.zip)

**Comment by Johnnos92** [comment]
Last Update - Playback issue now fixed - was attempting to put in expression text (sempre più tranquillo) via the rall _ _ _ function for specific text and _ _ _. Had changed playback tempo change to 0% and didn't realise that would affect the whole score.
Still not sure what was causing the crash for the time sig but changing computers seems to have worked.
Thanks.
