### ISSUE TITLE
[MU4 Issue] Muse Sounds: Crash during playback; dynamic range too extreme

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#14418]
**Describe the bug**

Playback the attached choir piece with Muse Sounds Choirs activated.
[dynamics_playback_issue.zip](https://github.com/musescore/MuseScore/files/9960822/dynamics_playback_issue.zip)

Problem 1: The dynamics range from pp to ff. Playback is handled fine with MS basic, but the f and ff dynamics are ear-splitting with the Muse Sounds choirs.

Problem 2. Playback may freeze and the score may need to be terminated (or crash?) towards the end of the piece.

**Expected behavior**

Playback of dynamics should reflect that in MS Basic; not so extreme. The score should not crash.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223120419, revision: github-musescore-musescore-4006440

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223300405, revision: github-musescore-musescore-88bcaae

A lot better. No problems with crashing or with closing the score afterwards. Just the issue with extreme dynamic range and low default volume compared to MS Basic. These issues are being covered in #12699 and #12023.

**Comment by zacjansheski** [comment]
Since crashing is resolved (high priority issue) and there are other issues covering the playback (less high priority issue), I will close this issue. :)
