### ISSUE TITLE
[MU4 Issue] Playback button is blocked after end of a piece 

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#14415]
**Describe the bug**
Most likely related to https://github.com/musescore/MuseScore/issues/13683

**To Reproduce**
1. Open any score
2. Play it till the very end (when playback stopped automatically)
3. Press Play

**Expected behavior**
Playback is run from begin of the piece

**Screenshots**

https://user-images.githubusercontent.com/101250347/200547077-b04e79e6-d018-4657-b18e-1948999f0767.mp4

**Comment by sammik** [comment]
Seems to be fixed by #14449

But it brought oposite problem, if playback stops at the wery end, it always starts from begining, even if user select some note, where to start play.

https://user-images.githubusercontent.com/1646034/200962253-8de9a540-9f8e-4d59-9185-ba81d8e3c411.mp4

**Comment by DmitryArefiev** [comment]
> Seems to be fixed by #14449
> 
> But it brought oposite problem, if playback stops at the wery end, it always starts from begining, even if user select some note, where to start play.
> Start-Playback.mp4

@sammik I see that issue also occurs in master so I've logged it separately #14458. Thanks for finding!
