### ISSUE TITLE
[MU4 Issue] First notes missed in playback; spurious notes during playback and at end.

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#14416]
**Describe the bug**

Play back the attached score. Make sure that Muse Sound choirs are activated in the playback setup (View). Listen for any playback effects that do not match the written score.

[dowland_all_people.zip](https://github.com/musescore/MuseScore/files/9960756/dowland_all_people.zip)

RESULT: The first chord is omitted during playback. There is a wrong note in the soprano voice after several of the quarter notes (crotchets). At the end there is a spurious note added.

**Expected behavior**

Playback should match the written score.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223120419, revision: github-musescore-musescore-4006440

**Comment by SteveBlower** [comment]
See also #14387

**Comment by Tantacrul** [comment]
Same question as before @rgreen5 - are you still experiencing this? If not, please return to it once we've made an announcement about merging our large performance issues and let us know if this goes away. It'll be really helpful!

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223300405, revision: github-musescore-musescore-88bcaae

Better. No wrong notes and no extra note after the end of the score. Just the sound lag, which is also covered by #14716.
