### ISSUE TITLE
[MU4 Issue] Stuttering on Windows when mixer is open

### ISSUE THREAD

**Issue by Reqrefusion** [musescore/MuseScore#14419]
**Describe the bug**
I hear annoying noises when I play with the mixer on. This situation exists in both ms basic and muse sound.

**Platform information**
 - OS: Windows 10 Home

https://user-images.githubusercontent.com/39885728/200559264-74093710-fb24-428a-a647-d5339b03d1ec.mp4

**Comment by Tantacrul** [comment]
Can you please try this build and let us know if it fixes the issue:  https://github.com/musescore/MuseScore/suites/9417801459/artifacts/444885402

**Comment by Reqrefusion** [comment]
> Can you please try this build and let us know if it fixes the issue: https://github.com/musescore/MuseScore/suites/9417801459/artifacts/444885402

Solved
