### ISSUE TITLE
Changing Muse Sound instruments on the fly resets playback sound but not playhead

### ISSUE THREAD

**Issue by majenkotech** [musescore/MuseScore#14424]
**Describe the bug**
If you change Muse Sound instruments on the fly the piece starts playing from the start again, but the playhead line on the screen doesn't go back to the start and continues playing from where it was.

**To Reproduce**
1. Open a fresh score
2. Spam a load of notes into it
3. Select a Muse Sound instrument
4. Play
5. While playing change to another Muse Sound instrument

**Expected behavior**
The sound will start from the start of the score again but the play head continues on from where it was.

**Platform information**
 - OS: Windows 10

**Comment by Tantacrul** [comment]
Moving to Post Release for now. It is an annoying issue but we're focusing on some other core playback issues first. It's possible we'll get to this issue but unlikely for the initial release.

**Comment by Tantacrul** [comment]
We've just fixed this issue in our latest nightly. Will be available v.soon.
