### ISSUE TITLE
[MU4 Issue] Save to cloud: no "unlisted" visibility option

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#14434]
**Describe the bug**
There is no unlisted option for "publish to musescore.com", and existing unlisted scores get downgraded to private on update.

**To Reproduce**
1. Create a score
2. File / Publish to MuseScore.com
3. See error: no unlisted option.  And when updating an existing unlisted score, it gets converted to private, breaking secret links.

**Expected behavior**
Unlisted should be an option for online scores

**Platform information**
 - OS: Linux

**Additional context**
When upload is complete, you have the opportunity to change to unlisted.  But, especially for larger scores that use Muse Sounds and might take the better part of an hour to upload, you might not be in a position to make the change when the upload completes.  Thus you can be left with an inaccessible score.  Also, the license gets changed in the process, from whatever you've set it to (e.g., "Attribution") to "None".

**Comment by Tantacrul** [comment]
We did this intentionally to keep the saving options simpler in MS4. However, we may undo this decision if we find it is causing any issues.

Worth mentioning that we're in the middle of making alterations to Private scores so that a user can invite people to look at them and comment on them.

**Comment by Tantacrul** [comment]
I'm going to close this as a won't fix for now. If we find there are issues users are raising, it'll wind back up here anyway. For now, it's not actionable.

**Comment by Jojo-Schmitz** [comment]
I need my scores being unlisted.

**Comment by Daniel-R15** [comment]
Those of us who create practice files absolutely do need the "Unlisted" option when publishing for a closed choral group.  "Private" doesn't allow members to see the scores, and "Public" breaks copyright.

Please reconsider and realise that "Unlisted" is essential to our workflow.

**Comment by Jojo-Schmitz** [comment]
Came up yesterday in https://musescore.org/en/node/344336

**Comment by bkunda** [comment]
> And when updating an existing unlisted score, it gets converted to private, breaking secret links.

Just to clarify, we did actually address this issue late last year and I can confirm (having just tested it) that the unlisted status of a score is preserved online even when saving changes in the desktop app. 

Certainly I can appreciate the hassle of not being able to set the status as unlisted from within the desktop app in the first place, but I just wanted to be clear that you can still work on an unlisted score and maintain its visibility status as such (unless someone has found a bug with this that I haven't been able to reproduce!).

**Comment by Jojo-Schmitz** [comment]
No, there's no such but, to my knowledge

**Comment by murimk** [comment]
For what it's worth, I also think the unlisted option should be added back sooner rather than later.

For context:
My workflow is making snippets of music (like a motif) that I then embed into a educational website, to give you playback and sheet music nicely embedded between text, videos, gifs and whatever else. This quickly adds up to hundreds of snippets, and none of them are of any relevance to the public. They can't be private, as I can't embed them and they absolutely shouldn't be public, as they are of no relevance to any one else. Sometimes there's also copyright issues...

I don't think having this option makes cloud saving more difficult or cluttered, and I'd vote for it to be added back in at firt convenience. :-)

**Comment by Tantacrul** [comment]
@shoogle - are there any major roadblocks to simply adding this option?

I would think that for unlisted scores, we might want to force audio upload, so users can have consistent Muse Sounds playback. It's a tricky one. Either option is less than ideal.

**Comment by Jojo-Schmitz** [comment]
Audio upload should only ever be forced when using Muse Sound or some custom soundfont, never for MS Basic

**Comment by Tantacrul** [comment]
@Jojo-Schmitz agreed. We need to eventually plug in that logic. It needs to be only if MS basic is completely untouched (by VST fx or changed reverb settings)

**Comment by shoogle** [comment]
> are there any major roadblocks to simply adding this option?

Nope! I would gladly see this option restored. It will make the code much simpler.
