### ISSUE TITLE
[MU4 Issue] MS Basic & VST: for certain instruments, notes with "detache" marking sound infinitely

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#14447]
**Describe the bug**
With certain instruments, notes with a "detache" marking sound infinitely when MS Basic or VST is used. For Muse Sounds, such notes sound very shortly. 
This happens both when clicking the note during editing and during full playback.

It seems to affect woodwinds and brass, but not strings. That probably means it has to do with those "articulation profiles" again... I think we should do something to prevent that missing articulation patterns cause problems like this.

**Comment by Tantacrul** [comment]
Confirmed. Adding **detache** to a woodwind produces infinity sound.
<img width="266" alt="image" src="https://user-images.githubusercontent.com/21022311/203314163-1f141c71-98fa-4fc9-a666-40733c6738a7.png">
