### ISSUE TITLE
[MU4 Issue] Notes in last bar are missing in parts when adding instruments

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#14442]
**To Reproduce**
1. Create a score with multiple instruments.
2. Enter some notes on all instruments up to last measure.
3. Open one of the parts.
4. Make _another_ instrument visible on that part.
5. See the notes are missing from the last measure.

**Additional context**
I was ready to bet that the problem was caused by my [don't layout closed parts PR](https://github.com/musescore/MuseScore/pull/13724), but apparently _it isn't_. The following screen capture is taken from the current master with that PR reverted.

**Screenshots**

https://user-images.githubusercontent.com/93707756/200809485-dacde324-a9b8-4c63-bb10-02846cbd7d9c.mp4

**Comment by RomanPudashkin** [comment]
@mike-spa nice catch! Thank you!

**Comment by DmitryArefiev** [comment]
Fixed in #14461
