### ISSUE TITLE
[MU4 Issue] Chimes/Tubular Bells Misplaced in Orchestral order

### ISSUE THREAD

**Issue by Fristover** [musescore/MuseScore#14454]
The Chimes/Tubular Bells instrument gets placed under woodwinds and above brass sections in a score when using orchestral order during instrument selection

1. Create a new score
2. Add some woodwinds, some brass and some percussion + chimes
3. See error

**Expected behavior**
Chimes get placed in the correct place

**Screenshots**
![image](https://user-images.githubusercontent.com/68985619/200977693-a2c986d7-256e-4258-a643-5ec3b9782ad3.png)

**Comment by oktophonie** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/14328
