### ISSUE TITLE
[MU4 Issue] Muse Hub pegs at 100% CPU usage after update

### ISSUE THREAD

**Issue by majenkotech** [musescore/MuseScore#14462]
**Describe the bug**
Muse Hub service is consuming 100% CPU usage

![image](https://user-images.githubusercontent.com/3812892/201151181-f70dd6f8-4633-4ef6-a4c6-c008f4ad1404.png)

**To Reproduce**
Just use it. (I saw this after some Muse Sounds updated, but I was seeing unusual CPU usage before too).

It seems to get locked in a tight loop of `recvmsg`:

```
recvmsg(121, {msg_name=NULL, msg_namelen=0, msg_iov=[...], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 0
```

Over and over and over, consuming all the CPU on that thread.

**Platform information**
 - OS: Arch Linux

**Comment by DominicMaas** [comment]
This should now be fixed in the latest version of Muse Hub (v0.9.12)

**Comment by DmitryArefiev** [comment]
Closing

@majenkotech Please reopen if still occurs on your side

**Comment by Onedy** [comment]
This is happening to me too, but when I disconnect the screen on Windows 10. I had to take a blind screenshot of the task manager because when I reconnect the screen, Muse Hub stops working.

**Comment by DominicMaas** [comment]
Hmmm interesting, I'll have to loop back around to this in a month or so sadly. 

We've got a large update coming out soon-ish so a bit busy with that, but once out, if it's still causing issues I can take a deeper look.
