### ISSUE TITLE
[MU4 Issue] Instruments in custom part are not deleted after deleting those instruments from score (using Add/Remove instruments dialog)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#14478]
**Describe the bug**
That was fixed for regular parts in #14288 for #13239 but not for custom parts

**To Reproduce**
1. Create new part
2. Show some instruments in that part
3. Open **Add and remove instruments** dialog (I shortcut)
4. Remove instruments from score which were mentioned in Step 2

https://user-images.githubusercontent.com/90187801/201374657-2fc5d359-d66a-498e-8faa-cb6057f14ca2.mp4

**Expected behavior**
Custom part should be cleared from those instruments. The same behavior when deleting from Instruments panel (see attached video) 

**Screenshots**

**Platform information**
macOS, Windows, Linux

**Additional details**
Doesn't occur if delete instruments from Instruments panel

**Comment by sammik** [comment]
Also generic parts are affected in scores migrated from earlier version containing parts already.

But these migrated scores seems to be special chapter (with own issues).

**Comment by oktophonie** [comment]
@DmitryArefiev I think this has been fixed at some point in 4.1?
