### ISSUE TITLE
Renaming Part issues (slash symbols should not be allowed)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#14477]
Some algorithms were implemented in #14288 #14290. 

The current issue collects all other problems.

1. Some special symbols should be filtered since the cause problems with saving files:

<>:\/“|?* 

This should be investigated more to find all symbols that are not appropriate

https://user-images.githubusercontent.com/90187801/201346868-0cd6842c-72a9-450f-9a4f-08e70a839e51.mp4

2. [**THIS IS FIXED in #18999**] When renaming parts, the filter mechanism **should not be case sensitive**. I.e. it should not allow to create **Violin** and **violin**
This is important for Uncompressed MuseScore folder format  

3. When renaming part, it should allow to create **more than one SPACE** in name.

 

https://user-images.githubusercontent.com/90187801/201347454-d53fe893-f1cc-4b6a-974f-74ba68cb7535.mp4

**Platform information**
 macOS, Windows, Linux

**Additional context**
#16127 #14288 #14290

**Comment by DmitryArefiev** [comment]
@RomanPudashkin There is also case sensitive issue with workspace name

https://user-images.githubusercontent.com/90187801/201349955-558f6eb9-20f1-41f7-a9f8-019429823b2c.mp4

**Comment by DmitryArefiev** [comment]
> The current issue collects all other problems.
> 
> 1. Some special symbols should be filtered since the cause problems with saving files:
> 
> <>:\/“|?* 

Using slash symbol (/) probably is most dangerous (see #19054)

**Comment by bkunda** [comment]
@RomanPudashkin I thought a fix for this was addressed here? https://github.com/musescore/MuseScore/issues/14290

But certainly it seems it is still possible to enter "excluded" characters in 4.1.1.

**Comment by DmitryArefiev** [comment]
See #16127 how slash symbols are dangerous

**Comment by bkunda** [comment]
@cbjeukendrup just confirming whether you are still pursuing a fix for this?

**Comment by cbjeukendrup** [comment]
Yes! This is one of the next things I'll do.
