### ISSUE TITLE
[MU4 Issue] Chord symbols do not sound correctly on transposing instruments

### ISSUE THREAD

**Issue by MoltenReplica** [musescore/MuseScore#14487]
**Describe the bug**
Chord symbols on non-concert pitch instruments sound the wrong chord when concert pitch is turned off.

**To Reproduce**
1. Start a score with a transposing instrument (e.g. tenor sax)
2. Turn on concert pitch
3. Write a series of chords using the chord symbol tool
4. Write a melody that fits the chords
5. Turn off concert pitch
6. Start playback

**Expected behavior**
The playback sounds identical each time.

**Observed behavior**
The melody will play back identically. However, the chord symbols will play the chord symbols as though they are at concert pitch.

Take this snippet as an example. 
![image](https://user-images.githubusercontent.com/88700334/201457794-fb3d5652-000f-4f92-bcd7-af92f6268ac2.png)
Here, we have a melody played on a tenor saxophone, with concert pitch turned on. The saxophone will sound these notes at concert pitch, and a piano will sound these chords at the appropriate concert pitch as well. The D, Bb, and G at marker A will be consonant chord tones of the piano's G minor chord.

![image](https://user-images.githubusercontent.com/88700334/201457877-dbe7eb4d-c6f2-4512-8541-4d5b9e2e03de.png)
However, if we turn off concert pitch, things immediately become dissonant. In this snippet, the tenor sax will sound these notes a major 9th below what is written. So the first three notes at marker A will be the same D, Bb, and G as before. However, the piano will play a concert pitch A minor chord, rather than the previous G minor. This creates unintended dissonance and plays back differently than if concert pitch were turned on.

**Platform information**
 - OS: Windows 10

**Additional context**
I've attached an example .mscz file. Switching concert pitch on and off particularly reveals the dissonant impact on more complex chords.
[Dracula's_Solos.zip](https://github.com/musescore/MuseScore/files/9994133/Dracula.s_Solos.zip)

**Comment by Tantacrul** [comment]
Confirmed. Chord symbols should not playback differently when the user switches on/off concert pitch.

**Comment by oMrSmith** [comment]
+1

**Comment by chile1900** [comment]
+1

**Comment by DmitryArefiev** [comment]
Fixed in #15146
