### ISSUE TITLE
[MU4 Issue] Muse Sounds' saxophones feel quite bad for bebop

### ISSUE THREAD

**Issue by MoltenReplica** [musescore/MuseScore#14486]
**Description**
Muse Sound soprano, alto, and tenor saxophones play poorly with fast tempos, drop notes, have limited range, and have too much dynamic range when dipping into the lower register.

**To Reproduce**
1. Compose an 8th note line with swing feel.
2. Set the tempo to a high bpm (i.e. 280 bpm)
3. Set dynamics to fortissimo at the start of the composition.
4. Set the instrument to soprano, alto, or tenor saxophone from Muse Woodwinds.

**Expected behavior**
The part will be played perfectly.

**Observed behavior**
A variety of issues will occur during playback.

- The soprano saxophone will play softly, despite the fortissimo marking.
- All three instruments will play much quieter when there is a large downward register change during a phrase, despite the fortissimo marking. They will, however, play fortissimo if the phrase starts in the lower register. (For example, at mm. 9 with the alto sax, after the range goes below the instrument's range.)
- The tenor saxophone will miss many notes and rhythms. There are examples at mm. 13, mm. 18, mm. 28, and more.
- The tenor saxophone overall sounds rather bad. This is especially the case at very high tempos. The alto is not great either, but is less offensive. The tenor and alto sound as though they have a chorus and reverb on them.
- Altissimo range is unavailable for all three saxophones.

**Platform information**
 - OS: Windows 10

**Additional context**
I've attached an example .mscz file from a project I was working on. The part was originally written for tenor sax, but these issues still occur when accounting for necessary transpositions for alto and soprano.
[Dracula's Castle.zip](https://github.com/musescore/MuseScore/files/9994106/Dracula.s.Castle.zip)

**Comment by MoltenReplica** [comment]
Issue #13894 is related to the lack of altissimo.

**Comment by Tantacrul** [comment]
There are multiple different issues here - some of which have already been logged. I can't see this issue being resolved anytime soon - and it would make a lot more sense to log each problem individually.

For example: dropped notes is a known issue. Inappropriate dynamic leaps are known too.

I'm going to close this issue but encourage you to take any remaining problems and log each one individually. In that way, we can resolve each - one at a time.
