### ISSUE TITLE
[MU4 Issue] Factory reset seems to uninstall Muse Sounds; can't reinstall them

### ISSUE THREAD

**Issue by njimenez07** [musescore/MuseScore#14484]
**Describe the bug**
Following a previous issue, I factory reset Musescore. It then seemed to have uninstalled all of my MuseSounds and, and will not let me redownload them.(Instead of a green "Get" button, it is just a grey play button)

**Screenshots**
![Screenshot (6)](https://user-images.githubusercontent.com/117788672/201434960-70d0a373-27d7-44b9-a348-4347a04ef15f.png)
*

**Platform information*

 - OS: Windows 10

**Comment by LuisLiszt** [comment]
Uninstall, delete the MuseHub folder in C:\ProgramData and reinstall with the latest installer from Musehub.com ... This should fix the issue. Unfortunately, you will have to download all the instruments again.

**Comment by cbjeukendrup** [comment]
@njimenez07 What do you mean by "factory reset"? 

If you mean "Help > Revert to factory settings", then it is very unlikely that this affects the state of Muse Sounds and Muse Hub. So probably that is not related to the factory reset.

**Comment by Tantacrul** [comment]
@njimenez07 - I'm going to have to close this since without enough info, it isn't actionable. Will reopen if you have any further info or news for us.

Thanks!
