### ISSUE TITLE
[MU4 Issue] Instruments panel: "Add" should be "Add or remove"

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#14482]
**Describe the issue**

The instruments panel contains a button called "Add". This is a misnomer because it actually opens a dialog that allows you to add _or_ remove instruments. Therefore it should be called "Add or remove" (or suchlike).

**Comment by Tantacrul** [comment]
I'm not sure this would practically ever lead to confusion - especially because you can remove instruments from the Instruments panel anyway (but can't add them). I just dislike the extra wordiness too.

I think I'll close this as a won't fix unless anyone thinks I'm nuts.
