### ISSUE TITLE
[MU4 Issue] Master Palette crashes MS4 due to application/paletteScale stuck on 0

### ISSUE THREAD

**Issue by Galathorne** [musescore/MuseScore#14489]
For working on a HiDPI device, I mistakenly set the `Preferences > Advanced > application/paletteScale` to "5", realised my mistake and then set it to "2". It worked OK and I continued my session. The next time I opened MS4, some of the Palettes' symbols were missing, showing only a horizontal line, and others garbled as it rendered much to large.

Examples:

![Palette symbols missing](https://user-images.githubusercontent.com/87099108/201462540-ad4f3a96-7822-4ef6-b6f9-fb350cdc6e2e.png) ![Crazy large palette symbols](https://user-images.githubusercontent.com/87099108/201462777-0027832a-6492-4f67-9f49-d2dc872a083a.png)

I tried to open the Master palette, and MS4 immediately crashed (closed/disappeared without warning message). After some troubleshooting, I realised that the issue is with the application/paletteScale setting. It is now stuck reverting back to "0" after each MS4 restart, and I have to change it back to 1 each time for the Master palette to function without crashing MS4. Even changing this back to "1" does not solve the standard palette issues, and the grid in the Master Palette is also somewhat screwed up since then...

![Master Palette woes](https://user-images.githubusercontent.com/87099108/201463222-45d39b4e-4fb1-4f84-b5c9-0d24755362f2.png)

When using the `Reset to default` button at the top of the Advanced page, it does the same as manually changing it to "1", so the outcome is the same as above. However, when clicking on the `Reset preferences` (for all) at the bottom, MS4 hangs indefinitely. 

![Reset Preferences](https://user-images.githubusercontent.com/87099108/201463399-d8b1383c-4ec3-4a93-8fee-e578a4e0090b.png) 

When closing the Preferences dialog (immediately or even after hours), Windows spits out the standard "not responding" window.

![Not responding](https://user-images.githubusercontent.com/87099108/201463429-11ebcaba-8b04-403a-af05-4ce7596d619a.png)

**Steps to reproduce the behaviour:**
1. Go to `Preferences > Advanced` and change `application/paletteScale` value to "0". 
2. Click OK.
3. Close MS4, then reopen.
4. Open the Master palette.
5. MS4 crashes. If not, repeat steps 1 - 4, but change the value to "5" when at step 1.
6. When this crashes MS4, open it again, and view `application/paletteScale` to confirm that it has changed to "0" after MS4 restart.

**Expected behaviour**
The `application/paletteScale` should remain as the user have set it, not revert to "0". All palettes should have the correct size symbols and grids, not mismatched as in the screenshots above.

**Steps tried to fix the issue:**
1. I uninstalled MS4
2. Deleted the Program Files folder as well as the AppData folder
3. Ran CCleaner (Custom clean plus Registry clean)
4. Restarted Windows
5. Reran CCleaner as above
6. Reinstalled MS4

When opening MS4 after all this, it remembered my previous Scores, still showing them on the Home screen, and the issue described still remains. Thus there are still one or more locations where orphan settings are stored. As a temporary workaround for this issue I would like to completely purge MS4 from my system, removing all traces, then do a completely clean install. How would I go about doing this? 

**Platform information**
OS: Windows 10 (21H2 version19044.2251)

### **EDIT: WORKAROUND**
1. I opened the `Diagnostic paths` window from the menu `Diagnostic > System > Show paths...`
2. Took a screenshot
3. Repeated "Steps tried..." above, but made sure to purge all the folders in the Diagnositc paths window when at step 2.
4. Did not need to restart Windows... (it was overkill but I was deperate)
5. Reinstalled MS4 and got greeted by the first time setup, with all setting back to a fresh default.

This bug is still out there, but for now this workaround did the trick for me.

**Comment by DmitryArefiev** [comment]
Fixed in #14653
