### ISSUE TITLE
[MU4 Issue]

### ISSUE THREAD

**Issue by mikosax21** [musescore/MuseScore#14493]
The post #14395 was suggesting that the subject of the repeat of measures was solved.

I tested with 2022-11-10 and 2022-11-12 versions.

Repeat **last bar works fine**.

But repeat last 2 bars or last 4 bars does not work as it should.

See the score in .pdf attached (Too bad we can't attach an .mscz file).
In green: what works; in orange: what works partially; in red: what does not work at all.
[Measure repeats (test with nightly 2022-11-10).pdf](https://github.com/musescore/MuseScore/files/9994764/Measure.repeats.test.with.nightly.2022-11-10.pdf)

**Comment by krtschil** [comment]
If you want to upload a score (.mscz file), just rename it to .zip (or zip it really) and leave instructions to rename the file or unzip it.

**Comment by mikosax21** [comment]
Thank you. I hadn't thought of that.
Even if the mscz file doesn't bring much more than the .pdf, here it is as a .zip file. 
[Measure repeats (test with nightly 2022-11-10).zip] : unzip under the same name.(https://github.com/musescore/MuseScore/files/9994975/Measure.repeats.test.with.nightly.2022-11-10.zip)

**Comment by MarcSabatella** [comment]
See https://github.com/musescore/MuseScore/issues/10922.  Unfortunately, it does not look playback of mult-measure repeats will be sovled for 4.0, but hopefully not too long after.

**Comment by mikosax21** [comment]
Thanks Marc.
It's not a big problem. I had just hoped by following the answer given to this question.
But as long as the repeat of a measure works, it's fine!
