### ISSUE TITLE
[MU4 Issue] String instruments play pizz. notes with tremolo through the stem as bowed

### ISSUE THREAD

**Issue by philipplndwhr** [musescore/MuseScore#14491]
**Describe the bug**
- When string instruments pizz _(can I say 'to pizz' for playing pizzicato in English?)_ notes with a tremolo through the stem in MU4's playback, the tremolo is played as bowed instead of pizzed.
- happens regardless of whether MuseSounds or the basic sound is selected in the mixer
<img width="941" alt="Bildschirmfoto 2022-11-12 um 11 09 58" src="https://user-images.githubusercontent.com/109522890/201469339-c1d8a1f5-d0ae-4f2b-bec6-cc45f6b6a9db.png">

- check the zipped folder for an .mp3 and for the .mscz

[MU4-pizz-tremolo-bug.zip](https://github.com/musescore/MuseScore/files/9994747/MU4-pizz-tremolo-bug.zip)

**To Reproduce**
1. open any score with bowed string instruments 
2. change bowing to _pizz._
3. write a note with tremolo through the stem before switching back to _arco_
4. playback will play the tremolo note as bowed

**Expected behavior**
Should play the tremolo as _pizzicato_ instead of bowing the note.

**Platform information**
 - OS: macOS 12.5, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-3289913152, revision: github-musescore-musescore-1ac395a

**Comment by Tantacrul** [comment]
Yes, we use 'pizz.' too :)

**Comment by DmitryArefiev** [comment]
Closing as covered by #19266
