### ISSUE TITLE
[MU4 Issue] Shortcut file Mismatch beetween Num+ and NumPad+

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14505]
**Describe the bug**
Shortcut file Mismatch beetween Num+ and NumPad+

**To Reproduce**
1. Réinit MuseScore préférences
2. Numpad 1,2 3 dosn't work in french keyboard
3. Export Shortcuts to xml file
4. Load in xml editor shortcuts file
5. All numpad shortcuts have been generated with "Num+".
6. Replace All "Num+" with "NumPad+"
7. Import modified shortcuts file
8. Numpad 1,2 3 dosn't work anyway
9. exit from Musescore 4
10. Run MuseScore 4
11. Numpad 1,2,3 Work Now

Not that NumPad shortcut dosn't  appear in shorcut préférences but work.
![image](https://user-images.githubusercontent.com/1835871/201520101-77ef64d9-aa09-4d86-ac07-5f54cd5676f0.png)

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223170411, revision: github-musescore-musescore-7b85777

**Comment by Eism** [comment]
@Gai-Luron 
Please check the build from https://github.com/musescore/MuseScore/pull/15819

**Comment by Jojo-Schmitz** [comment]
Tested: durations (1-9) work, /, +, - and Enter works, but . (resp. , in my case) does not,
Windows 11, German QWERTZ keyboard, German language settings

Changing to
```
    <SC>
        <key>pad-dot</key>
        <seq>.</seq>
        <seq>Num+.</seq>
        <seq>Num+,</seq>
    </SC>
 ```
makes 'dot' work for me

NumPad+0 doesn't work for Rest 
```
    <SC>
        <key>rest</key>
        <seq>0</seq>
        <seq>Num+0</seq>
    </SC>
 ```
fixes that. Both are vital shortcuts that did work in MU3 out of the box
