### ISSUE TITLE
[Muse Hub Issue] Windows 11: Blue screen on installation

### ISSUE THREAD

**Issue by roninhoaguiar** [musescore/MuseScore#14506]
Good Morning. I tried to install Musescore 4 beta through MuseHub and, in addition to giving a blue screen, it corrupted Windows 11 files and I had to format my pc. As soon as I formatted, I tried to install again and the same problem occurred. After that, I can't even try to install. Can someone help me?

**Comment by roninhoaguiar** [comment]
Blue screen on installation
Good Morning. I tried to install Musescore 4 beta through MuseHub and, in addition to giving a blue screen, it corrupted Windows 11 files and I had to format my pc. As soon as I formatted, I tried to install again and the same problem occurred. After that, I can't even try to install. Can someone help me?

**Comment by cbjeukendrup** [comment]
Is there any chance that this is the same issue as https://github.com/musescore/MuseScore/issues/13882? If so, let's close this one, and continue the discussion in https://github.com/musescore/MuseScore/issues/13882.
