### ISSUE TITLE
[MU4 Issue] Move rit. with middle anchor and Ctrl pressed result in crash

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14508]
**Describe the bug**
Create and move "rit." with middle anchor and Ctrl pressed result in crash

Look at this vidéo

https://user-images.githubusercontent.com/1835871/201540045-b6c086b6-3fe8-4d88-8ae6-2045ec0f3b47.mp4

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223170411, revision: github-musescore-musescore-7b85777

**Comment by cbjeukendrup** [comment]
This will be fixed by my existing PR #13302 :)
