### ISSUE TITLE
[MU4 Issue] Add crescendo in a part result in a thick line in Conductor

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14500]
**Describe the bug**
Add crescendo in a part result in a thick line in Conductor

**To Reproduce**
1. Create a part from a score
2. Enter note ans add crescendo in the part
3. Result in conducteur thick line for crescendo

**Part**
![image](https://user-images.githubusercontent.com/1835871/201491338-d23b5269-e599-4134-bb80-c540b3c72e5c.png)

**Conductor**
![image](https://user-images.githubusercontent.com/1835871/201491363-5b782bab-c4a3-4f81-8c15-a7197730e45e.png)

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223160409, revision: github-musescore-musescore-b6a6b23

**Comment by cbjeukendrup** [comment]
Although this looks suspiciously similar to https://github.com/musescore/MuseScore/issues/14275, I can still reproduce this in the latest master branch. Note that it only happens if the spatium in the full score is smaller than in the part scores.

**Comment by Gai-Luron** [comment]
Yes you are right when you talk about spatium.
**Full score :**
![image](https://user-images.githubusercontent.com/1835871/201497037-667980de-1ffc-4c98-9fd1-ebcfe837406c.png)

**Part:**
![image](https://user-images.githubusercontent.com/1835871/201497051-0d937dd7-05c0-4ab4-8080-c16798df0690.png)

Thank's for the reply

**Comment by mike-spa** [comment]
👀
