### ISSUE TITLE
[MU4 Issue] When adding a key signature from the palettes, it does not always appear, but does affect playback and accidentals

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#14510]
**To Reproduce**
1. Have a score with notes (to create one quickly, you can use the virtual piano keyboard and drag over the keys with the mouse)
2. Repeatedly, click a note and click a key signature in the Palettes.

Actual behaviour: sometimes, the key signature does not appear. However, it does seem to affect playback and the accidentals of subsequent notes. It is not yet clear under which circumstances the key signature does/doesn't appear. 

Expected behaviour: key signature is applied reliably. 

**Also:** when you save/close/reopen the score, the effects of the "ghost" key signatures seems totally gone; the notes simply have accidentals again. 

**Screenshots**
In this video I manage to reproduce it once in the end:

https://user-images.githubusercontent.com/48658420/201544701-c65f3f1f-aa1b-4b0d-8737-f0b22215b435.mov

**Platform information**
 - OS: reported on macOS

**Comment by zacjansheski** [comment]
I am unable to reproduce currently.  @cbjeukendrup I'll leave closing up to you

**Comment by cbjeukendrup** [comment]
I cannot reproduce anymore either (even if I exactly replicate the score from the video). Will close!
