### ISSUE TITLE
[MU4 Issue] Cyrillic file names cause weird names in exported files

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#14514]
**To Reproduce**
1. Open [Де я небо тримав_corrected.zip](https://github.com/musescore/MuseScore/files/10001678/_corrected.zip)
2. Export audio 
3. Open Explorer and check exported file - **there are two files (instead of one). One file has weird name and another has appropriate name but it's empty**
 
![Capture](https://user-images.githubusercontent.com/90187801/201630638-7807f2d5-1edc-4278-a5c0-3a002243219b.PNG)

**Expected behavior**

**Screenshots**

**Platform information**
Windows10

**Additional context**
Doesn't occur in **MS3**

**Comment by Tantacrul** [comment]
@DmitryArefiev - do you think this will be resolved with the fix Vasily provided here:

https://github.com/musescore/MuseScore/issues/14765

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev - do you think this will be resolved with the fix Vasily provided here:
> 
> #14765

Yeah! It looks good in #14981. Closing
