### ISSUE TITLE
[MU4 Issue] renaming Long instrument name in older files with multiple same instruments causes wrong part names

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#14520]
**Describe the bug**
In migrated oldeder scores, with multiple same instruments, when user edit Long (and short) instrument name, it produces wrong part names.

**To Reproduce**
1. Open file [Rodny moj kraj SQ.zip](https://github.com/musescore/MuseScore/files/9990140/Rodny_moj_kraj_SQ.zip)
2. Rename Long and Short instrument names for Husle (Change it to Husle 1, Husle 2)
3. See Parts names

**Expected behavior**
Part names should be Name1, Name2, ...

**Screenshots**

https://user-images.githubusercontent.com/1646034/201696646-090e6a74-e26a-4327-b70d-35b839ab8596.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**

**Comment by Tantacrul** [comment]
We are no longer tying part names to the names chosen on the score in the same way as MS3. We have had endless problems with this. Our solution now is to auto-generate names that avoids any possibility of instruments being called the exact same thing in the Parts dialog.

From now on, users can rename parts in the Parts dialog only.

**Comment by Tantacrul** [comment]
I didn't say your specific issue was fixed, I'm saying that we can't fix the issue you've raised because MS4 no longer works that way. Moreover, we'll be introducing new systems for renaming / managing parts in future that'll help further.
