### ISSUE TITLE
[MU4 Issue] Musesounds section strings play with excessive legato

### ISSUE THREAD

**Issue by Valdessir** [musescore/MuseScore#14524]
**Describe the bug**
Musestrings section strings (most notably the violoncellos) play with excessive legato as if there's a slur marking, resulting into unintelligible fast passages, and occasionally behind tempo. 

**To Reproduce**
1. Create a new score with violins 1 and 2, violas, violoncellos, and contrabasses using Musestrings. 
2. Add any fast passage in tempos of 130-150bpm (Preferably the excerpt I used in the documentation video)
3. Press play
4. Hear how the notes between the passage are nearly discernible due to excessive legato, and occasionally plays behind tempo. The issue is more apparent with the section violoncello. 

**Expected behavior**
Such passages should be played with clarity, and not so connected unless marked with a slur or legato text or the like. 

**Screenshots**
Here's the Google Drive link to the OBS recording of the issue: https://drive.google.com/file/d/10onV96F4xg7-AcoO5WdfNGnEjxRh9Dno/view?usp=sharing

**Platform information**
 - OS: Windows 10, Musescore 4 beta 2

**Additional context**
Despite the version of my copy of Musescore 4, Musestrings on my end is up to date.

**Comment by maestroharmony** [comment]
This isn't only in Muse Strings, also happens in Muse Woodwinds and Muse Brass.

**Comment by rgreen5** [comment]
Related to #13878?
