### ISSUE TITLE
[MU4 Issue][Muse Sounds] Woodwind notes are incorrectly rendered as slience

### ISSUE THREAD

**Issue by SamYeh** [musescore/MuseScore#14530]
**Describe the bug**
With Muse Sounds, some woodwind instruments (flute, clarinet, and possibly more) incorrectly render notes as silence in some cases.

**To Reproduce**
![image](https://user-images.githubusercontent.com/10248807/201790228-c25a6f14-7ae8-4de3-9a29-033b57ea28e4.png)
Play the score above and observe that the last note (G) is silent.
The score can be downloaded [here](https://musescore.com/user/55169571/scores/8991239).

**Expected behavior**
The note should be audible.

**Platform information**
 - OS: Windows 11

**Comment by MarcSabatella** [comment]
I can't access the score (is it private?), but I strong suspect this will turn out to be related to if not a duplicate of https://github.com/musescore/MuseScore/issues/14220

**Comment by SamYeh** [comment]
@MarcSabatella The score is public. I tested and it can be accessed without signing in to musescore.org. The symptom seems to be somewhat different from those in #14220. In this bug, the last audible note is #F. The G that follows, duration 1/12 + 1/8, is entirely silent.

**Comment by SamYeh** [comment]
@davidwhearn Thank you for the reply. My versions are:

Muse Hub: 0.9.9.515 (x64)
MuseScore 4: MuseScoreNightly-223220403-master-fd02c8d-x86_64
MuseHub says that everything is up to date.

And `.dlcache` is:
```
0,146bcefa-1588-44e4-9782-59ddc78daa36,Muse Woodwinds
I,0.4.8.0
0,1707eef4-633c-413d-8b1f-725e1cdc05b8,Muse Brass
I,0.3.3.0
0,1f7e1d31-6313-4329-a6bc-987cafa7d56d,Muse Keys
I,0.4.2.0
0,54becf84-d723-4417-9c7d-7d0c0ed33596,Muse Percussion
I,0.4.7.0
0,a1531f7f-6b8d-45ee-81d5-942a329994c4,Muse Choir
I,0.3.6.0
0,c242d818-4654-41f6-8659-a8d0f5c9232b,Muse Strings
I,0.4.0.0
0,cba44cea-47bc-4c61-bf57-abcb4e998bc9,Muse Harp
I,0.2.1.0
1,audacity,Audacity
I,3.2.1.0
1,hub,Muse Hub
I,0.9.9.515
1,musesampler,MuseSampler
I,0.2.4.0
1,musescore,MuseScore
I,4.0.0.223072007
3,20fc4538-4f90-4da7-bb66-8698568d9880,Compress
I,1.0.0.0
3,27a4842c-ab64-4394-84e2-6c4281842487,Chorus
I,1.0.0.0
3,2f453ce4-f65e-40ff-9ca6-5383d0b32013,Reverb
I,1.0.0.0
3,82eab78b-9689-48b5-b421-d10b99ec6cf3,Noise Gate
I,1.0.0.0
3,d3102331-2233-4e06-8999-182f3e64bef1,Master
I,1.0.0.0
3,fb7b8dca-5ebf-4dc6-98e7-3fe016937830,Pro EQ
I,1.0.0.0
```

I can consistently reproduce the issue in my environment. I understand that it's very hard to tackle when it can't be reproduced by the dev team. If there is any additional info that I can provide to help, please let me know.

**Comment by SamYeh** [comment]
I noticed that if I decrease the tempo of my bug example to, say, 60 bpm, then it would play as expected. I wonder if the problem may be related to #14038?

**Comment by SamYeh** [comment]
As of the nightly build of Nov. 29, 2022 (MuseScoreNightly-223330401-master-3277328-x86_64), I can no longer reproduce the bug with the example above.
