### ISSUE TITLE
[MU4] New score window slightly goes out of screen from Top.

### ISSUE THREAD

**Issue by Tejkh1** [musescore/MuseScore#14542]
**Describe the bug**
New score window slightly goes out of the screen from top which actually cuts the close button in half.

**To Reproduce**
1. Go to '..scores.'
2. Click on '..New score..'

**Screenshots**

<img width="899" alt="Screenshot (6)" src="https://user-images.githubusercontent.com/117664421/202005781-ffc909ed-cffa-432d-bdb7-1d835bd8402e.png">
platform: windows 11

**Comment by DmitryArefiev** [comment]
Fixed in #14547

**Comment by DmitryArefiev** [comment]
Retested on Win10
