### ISSUE TITLE
[MU4 Issue] Instrument description not changed when selecting a different key

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#14554]
**Describe the bug**
At the bottom of the choose instruments dialog, the description of the selected instrument is shown.
However, the description is not changed/updated when a different key for an instrument is selected.
Selecting another instrument and then back to the instrument with the key changed, does show the corresponding description for the instrument. Please see animated gif, hope that is making the issue clearer.

**To Reproduce**
1. Start a new score
2. Use the choose instruments dialog
3. Select an instrument like Clarinet
4. Check the description
5. Change the key for the selected instrument
6. Check the description

**Expected behavior**
Description should refresh when a different key is selected.

**Screenshots**
![Instrument-selection](https://user-images.githubusercontent.com/13550012/202273807-1072e753-ce01-4fa2-83de-5c7906e73ee6.gif)

**Platform information**
 - OS: Windows 10

**Additional context**

**Comment by Tantacrul** [comment]
We're planning on making some design alterations to this panel at some point, so we'll most likely fix this then.

**Comment by HemantAntony** [comment]
@Tantacrul Can you check: #17564

**Comment by Tantacrul** [comment]
I'm going to bump this one to @DmitryArefiev because I won't be able to get around to testing this today.

**Comment by DmitryArefiev** [comment]
All good now. Thanks! 

Fixed in #17564.
