### ISSUE TITLE
[MU4 Issue] key signature added to part is local key signature in score

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#14558]
**Describe the bug**
When user adds key signature to part, it is added as local key signature - is missing in other instruments in score.

**To Reproduce**
1. Open some part
2. Add key signature
3. Check score - key signature were added as "local key signature"

**Expected behavior**
Key signature added to part should be standard key signature for all instruments. Ctrl + key signature is for local key signature.

**Screenshots**

https://user-images.githubusercontent.com/1646034/202289617-9936b2fb-6263-4282-9a7c-97e3fc3feb0d.mp4

**Platform information**
 - OS: [reported on Linux]

**Comment by Tantacrul** [comment]
@oktophonie

**Comment by oktophonie** [comment]
Fix to be included in solution to https://github.com/musescore/MuseScore/issues/16544
