### ISSUE TITLE
MS Sounds: Mordents don't honour key signature

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#14564]
**Describe the bug**
**Muse Sounds only (Not MS Basic)**

Instead of playing diatonic as they are supposed to, mordents default to a tone wide regardless of note or key signature. In a lot of cases, that's okay. But, not every case. Indeed, I've run into many mordents that just sound wrong because they are a tone wide instead of Diatonic.

**To Reproduce**
1. Select any key signature you want
2. Put in a diatonic note that is a semitone above another diatonic note
3. Add a mordent
4. Hear that the mordent is a tone wide instead of the diatonic semitone

**Expected behavior**
It should default to diatonic rather than a specific interval unless marked for chromatic alteration.

**Screenshots**

https://user-images.githubusercontent.com/6530761/202349780-25432486-36f9-4dd2-8cf1-85e6ee54b715.mp4

C mordent should be C B C here but it isn't. Doesn't matter if I select Baroque under Properties or not.

**Platform information**
 - OS: Windows 10 MU4 Beta and Latest Nightly both

**Additional context**
Trills aren't affected, I don't know if the same issue is occurring with turns or not. I've only tested Muse Sounds, but if it's occurring with Muse Sounds and it's a case of ornaments sounding wrong, I highly suspect that MS Basic has the same issue.

Link to affected score https://musescore.com/user/50070/scores/9005510/s/kEntJ2?share=copy_link

**Comment by DaddyLudwig** [comment]
Related

https://github.com/musescore/MuseScore/issues/11361

**Comment by DaddyLudwig** [comment]
Okay, turns don't seem to be affected either, it's just mordents.

**Comment by DaddyLudwig** [comment]
Okay, it is MuseSounds specific after all, those same mordents sound as they are supposed to in MS Basic.

**Comment by Fristover** [comment]
Just bumping this (I shouldn't, I know, sorry...) as I can still reproduce it on the latest nightly and it's _very_ annoying.

**Comment by DaddyLudwig** [comment]
I'm not getting this anymore, so I'll close it as fixed.
