### ISSUE TITLE
[MU4 Issue][Muse Sounds] Fast choir passages have swoop into the note

### ISSUE THREAD

**Issue by egonelbre** [musescore/MuseScore#14568]
**Describe the bug**

Fast choir passages have a short swoop into the note, this is especially audible on bass notes.

Might be related to https://github.com/musescore/MuseScore/issues/14320

**To Reproduce**

Here are two small examples that should make it obvious:
* https://musescore.com/user/32602541/scores/9006947/s/y0yJWx
* https://musescore.com/user/32602541/scores/9006881/s/XFUchw

To reproduce locally, add fast repeated note with rests between them.

_While making the bug report, I noticed that the generated audio in the second example has bunch of additional notes after the "piece" finishes._

**Expected behavior**

I would expect the notes to be sung precisely, especially when singing the same note. The tiny "glide" into the note should only happen before the note, or in other words at the end of the note leading into the note. So, if there are any rests before the note, it should not happen.

**Screenshots**

<img width="911" alt="Screenshot 2022-11-17 at 12 39 20" src="https://user-images.githubusercontent.com/192964/202424847-70b00dea-6ac5-449e-b632-6eac18796cfe.png">

<img width="627" alt="Screenshot 2022-11-17 at 12 24 43" src="https://user-images.githubusercontent.com/192964/202421870-91a0118e-1bd0-41b7-939c-498868dffbc6.png">

**Platform information**
 - OS: macOS 13.0, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223072008, revision: github-musescore-musescore-2c34155

**Comment by cbjeukendrup** [comment]
It looks like I can't access these scores... are you sure they are Public?

**Comment by egonelbre** [comment]
@cbjeukendrup ah, sorry. I thought private meant that you were able to still send the link to other people. I changed it to Unlisted, I didn't notice that option before.

**Comment by cbjeukendrup** [comment]
Ah, I see. Unlisted is indeed what you're looking for :)

And I can hear the problem now!

**Comment by lehtoranta** [comment]
It's because the soprano sound has a slower attack than the alto sound. (If you e.g. switch soprano to use the Alto sound the problem is fixed.) Thus you hear first only just the alto sound, and then the soprano. The choir sounds have problems with slow attacks in general --- apparently they also have inconsistent attacks durations between different voice-sounds (i.e. soprano, alto, tenor, bass).

**Comment by DaddyLudwig** [comment]
I didn't notice an inconsistency in the attack durations, but with the inconsistency in relative volume(tenors being louder than altos and basses which in turn are louder than sopranos, thus me always having to set the sopranos higher than the rest in the mixer in say Bach cantatas), that doesn't surprise me a bit that the attack durations are inconsistent too.

**Comment by egonelbre** [comment]
Indeed, the second example does have problem with attacks as well. I wouldn't say the problem is the duration itself -- ideally the note is prepared before the note sounds.

**Comment by egonelbre** [comment]
Looks like these are fixed with the latest release.
