### ISSUE TITLE
CTRL-HOME and CTRL-END Shortcuts Not Working on my Win11 System

### ISSUE THREAD

**Issue by napochanIsMe** [musescore/MuseScore#14579]
(I did not see this behavior listed elsewhere so hopefully this is not a duplicate under another post.)

The CTRL-HOME and CTRL-END key combinations do not move the document in the display.  They do change the measure number at the bottom of the window appropriately, but the document display does not change.  CTRL-PgUp and CTRL-PgDn both work as expected, moving the document display in the corresponding direction.

All three views (Page, Continuous-horizontal, and Continuous-vertical) react similarly.

**To Reproduce**
Open a multipage score and press CTRL-END. You will see the measure location change in the lower section of the MU4 window indicating the last measure in the document, but the score will not move to that location.

Windows 11 Home version 10.0.22621
![MU4 CTRL-Home](https://user-images.githubusercontent.com/115959059/202575518-829370cb-736b-4eb2-a8be-0363d74ffcdc.png)

**Comment by SteveBlower** [comment]
Do you have Pan score during playback disabled?  If so, what you are experiencing is a known bug in MU3 where many navigation commands are ineffective unless that button is selected.  See https://musescore.org/en/node/330598.  I just checked with a recent MU4 nightly and the problem persists.  

If enabling Pan score during playback does not fix it for you then it seems you have a different problem.

In MU4 the button is rather more hidden within the settings menu of the playback panel.  See screenshot.

![PanScoreSetting](https://user-images.githubusercontent.com/60138048/202672009-e83df62f-def0-40fa-83da-4ed479eee0ac.png)

If enabling Pan score during playback does not fix it for you then it seems you have a different problem.

**Comment by MarcSabatella** [comment]
I can confirm this is the case even with the pan score option enabled.  Home and End position the score, but Ctrl+Home and Ctrl+End do not.  I think there should be a call to showItem() in the [selectFirstElement()](https://github.com/musescore/MuseScore/blob/70217d65a9dca6ee8c1c92dd4e3fc377d81b6819/src/notation/internal/notationinteraction.cpp#L779)

**Comment by MarcSabatella** [comment]
I recently fixed Ctrl+F and Ctrl+L, which also did the selection but not the score view.  I'm going to guess there are other commands with the same issue, that just need the showItem() call.  If anyone who wants to help go through various commands to see what else seems to be off, I can try to fix them all at once.

**Comment by MarcSabatella** [comment]
So far I found also inserting measures at start/end of score don't show them, also the various add text commands.

**Comment by napochanIsMe** [comment]
As confirmed, I did have Pan Score Automatically enabled. Either way, the Ctrl+Home and Ctrl+End do not reposition the score in the display.

I'm not familiar with many shortcuts, but I also found    add-parenthesis (   does not work as in MU3. Curiously, contrary to an earlier post Ctrl+L did open a lyric text box.

MU4 OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223072007, revision: github-musescore-musescore-2c34155

**Comment by MarcSabatella** [comment]
The parenthesis short is a known issue where no Shift+number shortcuts work.

Ctrl+L does add lyrics, but if the note you have selected is at the bottom of the window, the lyric you type might be off-screen - the view doesn't reposition to allow you to see what you are typing.  That's what my fix above addresses.

**Comment by DmitryArefiev** [comment]
Fixed in #15451

**Comment by DmitryArefiev** [comment]
Retested on Win10
