### ISSUE TITLE
[MU4 Issue] A4 scores created in MU3 get imported as Letter

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#14570]
**Describe the bug**
Scores created in MU3 that use the default page size of A4 get converted to Letter on import into MU4

**To Reproduce**
1. In MU3, create a score that uses the default page size of A4
2. Load that score into MU4
3. Go to Format / Page Settings
4. See error: page size is now Letter

**Expected behavior**
Page size should remain A4

**Platform information**
 - OS: Linux

**Additional context**
The problem is that the [legacy 302 style defaults file](https://github.com/musescore/MuseScore/blob/master/src/engraving/data/styles/legacy-style-defaults-v302.mss) is wrong - it has letter as the page size.  The height/width/printablewidth settings need to be fixed.

Note the problem is only visible for scores that truly use the built-in default A4 settings.  If your system currently defaults to Letter in MU3 (because of the printer check, or because you have a custom default style set in preferences) and manually set the page size to A4 - or if you change the page size to something else then back to A4 - then the problem might not occur.  That's because MU3 might see the page size as not being exactly equal to A4 due to round-off, and thus, the modified page size is written to the file.  Whereas on systems where A4 is the true default and you leave the page size alone, the page size does not normally get written.

**Comment by Tantacrul** [comment]
@oktophonie

**Comment by Tantacrul** [comment]
OK, good to know!

**Comment by cbjeukendrup** [comment]
@MarcSabatella If you have a potential solution, feel free to make a PR for it. I don't have much time for coding the next few days. Also, as a small separate PR, it may be merged sooner than as part of a large-ish PR.

**Comment by MarcSabatella** [comment]
PR submitted, see note in PR comment about how to test.

**Comment by MarcSabatella** [comment]
I had forgotten about this after https://github.com/musescore/MuseScore/pull/14561 was merged, but this bug still exists and was just reported by a user today.  I believe my PR is still valid.

**Comment by Jojo-Schmitz** [comment]
Yet another showstopper (for me), fix should really make it into 4.0.2
