### ISSUE TITLE
[MU4 Issue] Massive memory use trying to do Select All

### ISSUE THREAD

**Issue by dragonwithafez** [musescore/MuseScore#14582]
**Describe the bug**
When trying to use Ctrl+A to select all on a large score, more than 2 GB of memory use is added for the MU4 task. Deselecting and selecting again then continues to add more and more memory.

**To Reproduce**
1. Load attached score: 
[S4-piano.zip](https://github.com/musescore/MuseScore/files/10037758/S4-piano.zip)
2. Open Task Manager and note memory usage for MU4 process
3. Use Ctrl+A to try and select everything in the score
4. Watch memory usage in Task Manager rise
5. Deselect score by clicking in blank space
6. Repeat from step 3 (as long as your computer can take it)

**Platform information**
Using latest nightly build
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223210402, revision: github-musescore-musescore-089ce9f

**Additional context**
Using MuseSounds grand piano with no effects for playback.
Here's a video of the leak in action: https://youtu.be/Ae9sC93_cNM

**Comment by DmitryArefiev** [comment]
@dragonwithafez I can't reproduce it on my Windows10 with the attached score.. and it's strange that **Select All** takes so time on your PC.

Does it occur if to use MS Basic instead of MuseSounds?
Does it occur with other scores?

**Comment by dragonwithafez** [comment]
On my system, even using an empty score, for example using the default Grand Staff template with no modifications, selecting all adds ~10MB of memory used, over and over.

**Comment by DmitryArefiev** [comment]
That's strange.. I've tried again in the latest master and still can't reproduce


https://user-images.githubusercontent.com/90187801/202919736-cc3c9a3a-b3d7-42ff-8fb2-4abcb121bdb9.mp4

**Comment by DmitryArefiev** [comment]
Can you Reset factory settings and try again? Maybe that helps

**Comment by dragonwithafez** [comment]
Yes, still occurs after a factory reset, and in the more recent nightlies as well.

**Comment by DmitryArefiev** [comment]
Hmm.. Really strange.. Let's leave the bug open for now

**Comment by DmitryArefiev** [comment]
@dragonwithafez Can you try the build from https://github.com/musescore/MuseScore/actions/runs/3538604434 ?
It should fix the issue

**Comment by dragonwithafez** [comment]
Yes, that fixes things for me!

**Comment by DmitryArefiev** [comment]
Cool! Thanks!
