### ISSUE TITLE
[MU4 Issue] Default shortcuts for inserting bars using `Ins` key are not working on macOS 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#14585]
**Describe the bug**
The default shortcut on macOS for `Insert measures before selection` (&#8984;Ins) doesn't seem to trigger any action. 
The same command in Windows (Ctrl+Ins) does seem to be working.

Demo video: https://www.dropbox.com/s/4ymolgea1zyfq6e/insert-bars-before-selection.mov?dl=0

EDIT
The shortcut `Ins`, which on Windows adds a single measure before selection, also doesn't work on macOS (not documented in the above video).

**Expected behavior**
1. This command should respond to the default shortcut and trigger the "Number of bars to insert" dialog (as it currently does in Windows).
2. The shortcut `Ins` should also insert a single bar before selection.

**Platform information**
 - macOS 12.6 (M1)

**Additional context**
Note: That the command `Insert bars before selection` now triggers the "Number of bars to insert" dialog is by design.

**Comment by cbjeukendrup** [comment]
Possibly related to #14184

**Comment by bkunda** [comment]
> Possibly related to #14184

In this case, I shall give this one the same project assignments :-) I suspect it is a regression, and being able to insert measures without the mouse is an important accessibility requirement.

**Comment by bkunda** [comment]
@cbjeukendrup just found the same problem with inserting single bars before selection. Something to do with the `Ins` key, I suspect.

**Comment by Tantacrul** [comment]
@bkunda - how on earth do I find 'INS' on an M1 Mac? Are you using an external keyboard?

(Tried FN + Enter, FN + I, etc)
