### ISSUE TITLE
[MU4 Issue] Crash when doing "Repeat selection" with 256th notes or shorter

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#14599]
**To Reproduce**
1. Enter 256th notes or shorter
2. Select one or more of them
3. Press <kbd>R</kbd> ("Repeat selection")
-> crash

**Platform information**
 - OS: reported on macOS

**Additional context**
- Also occurs in MS3.6.2.
- It seems that you sometimes need to press R two times before it happens.

**Comment by cbjeukendrup** [comment]
See also https://github.com/musescore/MuseScore/issues/14840; that is probably the cause of this issue

**Comment by cbjeukendrup** [comment]
... it's not the _only_ cause though. Once this crash is fixed, the original cause that I had found (and that also happened in MS3) will re-surface.

**Comment by DmitryArefiev** [comment]
Fixed in #16254

**Comment by DmitryArefiev** [comment]
Retested on Win10
