### ISSUE TITLE
Cannot open certain 3.6 scores

### ISSUE THREAD

**Issue by GeertWil** [musescore/MuseScore#14593]
I cannot open some 3.6 scores in version 4.x. No error messages are shown; Musescore closes automatically after a few seconds. Those file can be opened and played back in version 3.6. without any problem.
I exported the files as MusicXML and as files without compression, but these files cannot be opend in version 4 too.
Is there a log file somewhere that tells me more??
[A Wither Shade Of Pale (Procol Harum) - Arr. Gwm.zip](https://github.com/musescore/MuseScore/files/10043246/A.Wither.Shade.Of.Pale.Procol.Harum.-.Arr.Gwm.zip)

**Comment by oktophonie** [comment]
(I tried this today, couldn't reproduce either)

**Comment by GeertWil** [comment]
Hi

 �

Thanks for he fast reply.

 �

 �

I downloaded the latest nightly build and now the problem seems to be is solved. I’m able to open the problematic files without any issue.

 �

Thanks again.

The new MuseScore is more than incredible.


Kind regards

 �

Geert Willemarck

 �

**Comment by oktophonie** [comment]
Glad to hear the problem seems to have been resolved!
