### ISSUE TITLE
[MU4 Issue] MuseHub 'Unable to download ...' error

### ISSUE THREAD

**Issue by the-jasoney** [musescore/MuseScore#14605]
**Describe the bug**
When I try to download something (e.g. Muse Choir), it gives me a 'Unable to download' error.

**To Reproduce**
1. Open Muse Hub
2. Click on any of the 'Get' buttons

**Expected behavior**
I expected to download something.

**Platform information**
 - OS: Windows 11 21H2, same error with 22H2 as well

**Additional context**
No one else seems to be getting this error. I also am not seeing any cover pictures

![image](https://user-images.githubusercontent.com/107383260/202820276-ef125dc4-00b0-47ca-82a2-97d9b8c23257.png)

**Comment by Haru00007** [comment]
I had the same problem.
check out and try it: #14316

**Comment by the-jasoney** [comment]
@Haru00007 did not work

**Comment by the-jasoney** [comment]
It also doesn't let me click it again and the icons don't show up

**Comment by Haru00007** [comment]
hmm...
I ran into this problem too.
might be Muse hub server has some error

**Comment by NuclearBoofluff** [comment]
Same issue. For 2 days already

**Comment by the-jasoney** [comment]
The issue seems to be resolved for me.

**Comment by the-jasoney** [comment]
Probably a server error
