### ISSUE TITLE
[MU4 Issue] Corrupt file after splitting measure

### ISSUE THREAD

**Issue by SamYeh** [musescore/MuseScore#14607]
**Describe the bug**
File becomes corrupted after splitting a measure.

**To Reproduce**
1. Download and open [this score](https://musescore.com/user/55169571/scores/9017513). Its contents are shown below.
![image](https://user-images.githubusercontent.com/10248807/202828189-a0aae415-3666-4e1d-abbf-5747f32529b9.png)
2. Click on the half rest in bar 2.
4. Choose Tools > Measures > Split.
5. Save the file, close, and re-open.
6. Observe the MU4 error message about the file being corrupted.

This may be related to #14606.

**Expected behavior**
Saving a score should not corrupt the file. If a score becomes corrupt (which is a bug in itself), MU4 should warn the user and prevent overwriting the file.

**Platform information**
 - OS: Windows 11
- Build: MuseScoreNightly-223220403-master-fd02c8d-x86_64

**Comment by asattely** [comment]
if you open the flute part, the first measure is an entirely different length--a very similar situation to #14606. In effect, the part seems to no longer be linked to the masterscore. I think this might be a corrupted part, so if anyone is able to reproduce this score, where the measures in the part and in the masterscore are different, I'd love to hear how!

**Comment by oktophonie** [comment]
Closed as we have no way to create a new score that can reproduce this.
