### ISSUE TITLE
[MU4 Issue] Playback issue after playing the last measure.

### ISSUE THREAD

**Issue by Valdessir** [musescore/MuseScore#14609]
**Describe the bug**
After playing the last measure of a score, regardless of what measure you highlight to play, playback will play the first measure.

**To Reproduce**
1. Open a new score with any instrument
2. Highlight any measure and let playback play to the end of the score.
3. After the last measure is played, highlight any measure but the first and press play again.
4. See that regardless of where you highlight, playback will play the first measure.

**Expected behavior**
Playback should play on the measure highlighted by the user.

**Screenshots**
Here's a link of the OBS recording documenting the bug reproduction: https://drive.google.com/file/d/1Y4S1jsEsNchNyiyLV5ekG8rq5JxmZJl6/view?usp=sharing

**Platform information**
 - OS: Windows 10, MU4 Nightly

**Comment by Tantacrul** [comment]
Yeah, this is quite annoying for sure.

**Comment by DmitryArefiev** [comment]
The same as #14458

**Comment by DmitryArefiev** [comment]
Fixed in #15048
