### ISSUE TITLE
When score is in continuous view, the line that follows notes being played is off screen for a while.

### ISSUE THREAD

**Issue by Philorganic** [musescore/MuseScore#14627]
When the playhead plays to the far right of a score, a page refresh occurs, which brings a new part of the score into view... but the playhead line takes 1/2 a second to catch up.

New video uploaded here - https://youtu.be/m6rnfugoRhE

**Comment by MarcSabatella** [comment]
This came up again in the forums.  The video is deleted so it is difficult to be sure, but I believe this may be referring to the way the panel on the left obscure the cursor at first.  As such, it is probably a duplicate of https://github.com/musescore/MuseScore/issues/16173.

Workaround - actually a better solution if you want to be following the playback cursor to read along - is to switch to the "Smooth panning" mode in Edit / Preferences / Advanced.

**Comment by Philorganic** [comment]
Brilliant! Thank you, that fixes it for me.

**Comment by cbjeukendrup** [comment]
This seems indeed a duplicate of https://github.com/musescore/MuseScore/issues/16173 (well, chronologically it's officially the other way around...)
So I'll close this issue in favour of https://github.com/musescore/MuseScore/issues/16173.
