### ISSUE TITLE
[MU4 Issue] Minimize, Maximize, and Close buttons don't line up with the top edge of the screen (Windows)

### ISSUE THREAD

**Issue by GabeS573** [musescore/MuseScore#14624]
**Describe the bug**
On Windows 11, the Minimize, Maximize, and Close buttons do not line up with the top edge of the screen, unlike in other Windows apps. Similarly, the File, Edit, etc. menu buttons do not line up with the top edge of the screen.

**To Reproduce**
1. Open MuseScore 4
2. Maximize the MU4 window
3. Move your mouse all the way against the top edge of the screen and try to click the minimize, maximize, and close buttons.
4. The buttons cannot be clicked while the mouse is against the top edge of the screen.
![image](https://user-images.githubusercontent.com/91428485/202927328-8b8a713c-2e99-429c-b59a-a82fed41b2a9.png)

**Expected behavior**
On other Windows apps, these buttons extend all the way to the edge of the screen, which is a good design choice as it allows them to be quickly clicked even if the user overshoots them and hits the edge of the screen.
![image](https://user-images.githubusercontent.com/91428485/202927323-6a1a2fac-e7f4-4e32-b040-553e53c2ee3b.png)

**Platform information**
 - OS: Windows 11

**Additional context**
This also applies to the File, Edit, etc. menus (although in most Windows apps menus like these aren't directly along the top edge of the app window anyway, so it's not as obvious as the Min/Max/Close buttons).
![image](https://user-images.githubusercontent.com/91428485/202927512-bff067c0-4dce-4ea6-b6dc-46e6d3d4e360.png)

~~Also, on most Windows apps the Close button turns red when hovered over, but the MuseScore close button is the same color as the other two.~~ Edit: ignore this

**Comment by Tantacrul** [comment]
So, in terms of look, we (like plenty of other apps) have a customised toolbar, so it doesn't correspond exactly to the visual style of Windows.

However, we should expand the clickable area for the menu bar so it is at the very edge of the app (Fitts’ Law).

Here's a cool video explaining what the concept is for anyone who doesn't know. https://youtu.be/3wbnf87dGms

(That guy designed the Ribbon btw)

**Comment by DmitryArefiev** [comment]
Retested on Win10
