### ISSUE TITLE
[MU4 Issue] Implode from multiple voices to chords loses courtesy accidentals

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#14633]
**Describe the bug**
If you have multiple voices on a staff and use Tools / Implode, courtesy accidents in voices other than 1 get lsot

**To Reproduce**
1. Score with one staff, C major
2. Measure one, note input
3. Enter voice 1 C6, voice 2 A with explicit natural
4. Select the measure
5. Tools / Implode
6. See error: the natural on the A is lost

**Expected behavior**
All accidentals - including courtesy (user) accidentals, should be retains

**Screenshots**
![image](https://user-images.githubusercontent.com/1799936/203075279-f18d5749-d993-44c5-b502-c8a0ded88b69.png)

**Platform information**
 - OS: Linux

**Additional context**
Not a regression; same bug in 3.6.2.  Also, other note properties like velocity and tuning are not preserved.

**Comment by Tantacrul** [comment]
@oktophonie - think this might be something for your krew?
