### ISSUE TITLE
[MU4 Issue]

### ISSUE THREAD

**Issue by TimFritzges** [musescore/MuseScore#14637]
When having a tie between multiple notes in a cord then only some are played  **Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**
1. Make a Cord
2. Make a second cord including some or all of the notes of the first cord
3. put ties in

**Expected behavior**
I want to hear all the notes

**Screenshots**
![grafik](https://user-images.githubusercontent.com/118749462/203086829-6c724e7e-613f-42d2-a00d-eddf01e33de6.png)
![grafik](https://user-images.githubusercontent.com/118749462/203087041-579db0e2-ae18-473f-b221-cd9e37321156.png)
![grafik](https://user-images.githubusercontent.com/118749462/203087953-b4e2354d-c46d-4ec2-a9e9-2f917b13c17e.png)
![grafik](https://user-images.githubusercontent.com/118749462/203087967-33720f31-a017-4099-b88d-9790e7b1bd2e.png)

**Platform information**
 - Windows 10

**Additional context**

**Comment by TimFritzges** [comment]
Hello! Ok. That seems to have been the problem. Just to ask then. Are things like:
-Isotope Plugins Crashing musescore if you try using their learning functions
-Plugins that would usually just get their time from the Programm and only send the sound back to the programm (for example StudioV) already adressed? [Are those intended to be implemented? If not then Musecore should maybe not show them as VST options :)]

**Comment by Tantacrul** [comment]
@TimFritzges - regarding the issue you posted (lets' ignore VST for now because that's a separate issue)

Could you uninstall the build you have and try this build instead? It is much more optimised for Windows:
https://github.com/musescore/MuseScore/suites/9417801459/artifacts/444885402

Then let us know if the issue with ties are fixed for you. After that, we can delve into the VST stuff. Thanks!

**Comment by cbjeukendrup** [comment]
Closing, since this has been in "needs info" state for months, and most likely the mentioned issues have already been fixed (and if not, for each problem a separate and clear issue should be created).
