### ISSUE TITLE
[MU4 Issue] MuseFX Pro EQ settings not saved

### ISSUE THREAD

**Issue by SamYeh** [musescore/MuseScore#14646]
**Describe the bug**
Custom settings to MuseFX Pro EQ do not persist through file close/open.

**To Reproduce**
1. Create a score with a Muse Sounds instrument.
2. Apply MuseFX Pro EQ to the instrument.
3. Turn the Pro EQ knobs so that it's different from the default.
4. Save the file, close, and reopen.
5. Open the Pro EQ and observe that the settings are reverted to the default.

**Expected behavior**
I expect Pro EQ settings to persist indefinitely.

**Platform information**
 - OS: Windows 11
 - Build: MuseScoreNightly-223250406-master-2e65739-x86_64

```
1,hub,Muse Hub
I,0.9.9.515
1,musesampler,MuseSampler
I,0.2.4.0
1,musescore,MuseScore
I,4.0.0.223072007
3,fb7b8dca-5ebf-4dc6-98e7-3fe016937830,Pro EQ
I,1.0.0.0
```

**Additional context**

**Comment by Tantacrul** [comment]
Also, please uninstall any version of MS4 you have already before installing this.

**Comment by SamYeh** [comment]
@Tantacrul  - I didn't try the build you mentioned. I tried the nightly build of Nov. 23 instead, and it no longer has the problem. Thanks!

**Comment by Tantacrul** [comment]
OK, thanks!

**Comment by Attackoh** [comment]
I have this issue on version 4.0.2-230651553. My settings get reverted to the default except for two instruments which managed to save correctly.

**Comment by Tantacrul** [comment]
> I have this issue on version 4.0.2-230651553. My settings get reverted to the default except for two instruments which managed to save correctly.

Just so you know, if an issue reoccurs, it's best to log a new issue and provide instructions and an example file too. We cannot act upon the info you've provided here.

In most cases, it's better than commenting on a closed issue.
