### ISSUE TITLE
[MU4 Issue] Cross-Staff Beaming Cause Some Accidentals to Intersect With Stem

### ISSUE THREAD

**Issue by ludovikbechard** [musescore/MuseScore#14645]
**Describe the bug**
Cross-staff beaming cause some accidentals to intersect with stem.

**To Reproduce**
1. Create a new keyboard score;
2. Create a left-hand arpeggio in 16th notes (e.g. F4 - F3 - Bb3 - D4 or E4 - E2 - G#3 - B3);
3. Switch the first note to the right-hand staff (Ctrl+shift+up arrow).

**Expected behavior**
The accidental should not intersect with the stem.

**Platform information**
Linux Ubuntu 22.04

![image](https://user-images.githubusercontent.com/20604032/203252244-467af15b-4e04-40e1-aff8-e82090344520.png)

**Comment by oktophonie** [comment]
(3.6 for comparison):
![image](https://user-images.githubusercontent.com/20604032/203252492-0bed8409-49a6-4141-82da-762450ae9881.png)
