### ISSUE TITLE
[MU4 Issue] Cross-staff notation w/ multiple voices causes rests to be displaced abnormally

### ISSUE THREAD

**Issue by cgpqci** [musescore/MuseScore#14650]
**Describe the bug**
In entering music with multiple voices, doing cross-staff notation on one of the voices cause corresponding rests at another voice to be displaced abnormally.

**To Reproduce**
1. Create score as of liking (preferably a grand staff).
2. Split measure on one of the staves into at least two voices.
3. Input a line of music on the lower voice
4. Perform cross-staff notation on lower voice
5. See error

The displacement seems to correspond to where the notes transferred to the lower staff are located. See:

Higher position

![image](https://user-images.githubusercontent.com/90231404/203209639-d184c1d2-6c67-4bbb-a4a9-0fe74cbe0b5a.png)

Lower position

![image](https://user-images.githubusercontent.com/90231404/203209791-e23575b1-6394-4ede-819a-bc1402ac2492.png)

Both staves same clef

![image](https://user-images.githubusercontent.com/90231404/203209892-7c0f26e4-b5c5-49e6-8c8b-56e6832179c8.png)

At lower staff

![image](https://user-images.githubusercontent.com/90231404/203211445-6285b36c-cf4d-4a71-86a5-9b8b46e05b33.png)
![image](https://user-images.githubusercontent.com/90231404/203211519-3a6065d7-0bbc-411e-927a-be6fbab21cd8.png)
![image](https://user-images.githubusercontent.com/90231404/203211637-683fe655-1df9-4801-adc2-ca48d8dc17d4.png)

It does kind of happen at inverse, though it isn't as apparent, and you have to set the notes lower to be so.

![image](https://user-images.githubusercontent.com/90231404/203211976-5e2b5b92-87c4-4d03-b45c-5afb53799177.png)
![image](https://user-images.githubusercontent.com/90231404/203212054-ff0f7ec7-21a8-4c40-9aaf-898a4b3c670c.png)

**Expected behavior**
Rests position at empty voices should only be respecting elements within its local staff.

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223072007, revision: github-musescore-musescore-2c34155

**Comment by oktophonie** [comment]
Not a regression, and there's a more comprehensive overhaul of vertical rest displacement planned, but it would be worth looking into whether there's a quick/easy fix for this (as you say, rests just shouldn't adjust for items that are displaced to another stave).

**Comment by mike-spa** [comment]
Will be fixed by the linked PR. To clarify: this issue (and the relative solution) only deals with notes that are moved _away_ from the staff where the rests are. Notes that are moved _into_ the staff are a whole different story and will be dealt with in a separate work.
