### ISSUE TITLE
[MU4 Issue] Rhythm only mode: not possible to specify duration of rests correctly

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#14654]
**Describe the bug**

In MS3 **Rhythm** mode, pressing a duration icon/shortcut enters a note, BUT pressing 0 (zero) has NO effect until a duration icon/shortcut is subsequently pressed, after which a rest of the corresponding duration is entered onto the staff.

However, in MS4 **Rhythm only** mode, 0 (zero) _immediately_ enters a rest. This makes it impossible to specify a duration for the rest.

**Expected behavior**

1. Clicking a duration icon or shortcut enters a note on the middle line of the staff of the same duration.
2. Pressing a . (period/full stop) makes subsequent durations dotted/undotted until pressed again.
3. Pressing a zero has no effect until a duration icon/shortcut is subsequently pressed; then a rest of the same duration is entered.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223260405, revision: github-musescore-musescore-13f3d88

**Comment by bkunda** [comment]
I can confirm I have just experienced this same problem. This is a regression from MS3 and pretty much makes "rhythm" mode unusable, because the duration of rests can't be selected before they are entered.

**Comment by Tantacrul** [comment]
I'm keeping this in Post Release because we don't have time to be adding more stuff now.

**Comment by oMrSmith** [comment]
> This is a regression from MS3 and pretty much makes "rhythm" mode unusable

I agree, but it's not the only problem with this mode. Even in MU3 you cannot specify the length of a following tied note.
While in rhythm-only input mode, ties would have to work _backwards_ in order for that to function. In MU4 I think you actually can specify the length of rests though, you just have to click on the rest-symbol in order to toggle rests to "on".

**Comment by MarcSabatella** [comment]
The above PR address the rest shortcut issue.  It doesn't touch on the subject of ties, or change anything else about rhythm mode.

**Comment by MarcSabatella** [comment]
BTW, I can confirm that only the shortcut was broken - the toolbar button does work.  Another (lame) workaround, that also works for rests on tab staves: enter the note then hit Delete.  And then hit the Right cursor key.
