### ISSUE TITLE
[MU4 Issue] Strange Key Signature issue with Horn in F part

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#14675]
**Describe the bug**
Strange Key Signature issue

**To Reproduce**
1. Create a new score in F Major with 1 flute and 1 Horn in F
![image](https://user-images.githubusercontent.com/1835871/203426227-1ba77977-dd8d-4bbe-8c3b-3ee03f76eb9f.png)
2. Add "Flute" or other instrument result in wrong key signature.
![image](https://user-images.githubusercontent.com/1835871/203426269-9c7f8376-dd9b-465f-97f2-00909c103424.png)
![image](https://user-images.githubusercontent.com/1835871/203426588-f5b8d0f2-2d90-4272-8c9f-2f6db159037b.png)
3 Remove Horn in F, and leave only Flute
![image](https://user-images.githubusercontent.com/1835871/203426737-7a6817bb-448e-435b-9fff-e0e5ef65b3a9.png)
4 Add new instrument
![image](https://user-images.githubusercontent.com/1835871/203426900-404b2882-fc71-4af5-8d6d-4d311c7206d3.png)

all work Fine 

I don't know why

**Expected behavior**
Flute created must be in F Major

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223260401, revision: github-musescore-musescore-13f3d88

**Comment by sammik** [comment]
It hapens, when bottom staff contains transposed instrument, which have no key signature (C major).

Regression. Didn't Happen in Alpha2, but is already present in Beta.
