### ISSUE TITLE
Notes do not play full length during playback

### ISSUE THREAD

**Issue by blackears** [musescore/MuseScore#14674]
**Describe the bug**
Notes do not play full duration during playback.
[organ.zip](https://github.com/musescore/MuseScore/files/10071118/organ.zip)

**To Reproduce**

Create a new score with an organ part.
Add four whole note Cs in consecutive measures and tie them together.
Press play to start playback.
Only 8 beats are played even though 16 are notated.

**Expected behavior**
An organ should sustain for the entire 16 beats.

**Platform information**
Windows 10

**Additional context**
This is also happening with live MIDI playing.  Notes are not sustained for the full time the key is pressed.

**Comment by Grillzombie** [comment]
All ok with this provided score on Linux Mint 21
OS: Linux Mint 21, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223240408, revision: github-musescore-musescore-56b4855

**Comment by blackears** [comment]
This seems to be fixed with OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223291259, revision: github-musescore-musescore-3eb4117
