### ISSUE TITLE
Cannot hear other parts play back if measure is selected

### ISSUE THREAD

**Issue by blackears** [musescore/MuseScore#14671]
**Describe the bug**
If a measure is selected and the play button is pressed, only the notes in the currently selected staff are played back.  Effectively, the part is soloed until you click outside of it clearing the selection.  This is unlike the behavior in MuseScore 3.  

I was talking with some people in the chat who were saying that this is an intentional change, but I would hope the team would reconsider this.  I like to generate musical ideas by playing on my MIDI keyboard while the rest of the song plays in the background.  This necessitates that a staff is selected so MuseScore knows which voice to render my MIDI input in.  However, if this also causes that part to be soloed, I am no longer able to hear how the notes I am playing fit in with the rest of the piece.  

I would hope that at least a configuration option could be added so that it is still possible to have a measure selected and still hear the other parts during playback.

**To Reproduce**
Create a new piece with multiple staves.
Enter notes on one staff.
Select the second staff.  
Press play.

**Expected behavior**
All parts can be heard, not just the selected one.

**Platform information**
Windows 10

**Comment by MarcSabatella** [comment]
Playing your keyboard shouldn't necessitate that you select a range - it *should* work to select a single note or rest.  So, the same method that allows you to playback the full score should allow you to hear your keyboard playback using the appropriate sound.

If *that's* not working, that's a separate issue.

**Comment by blackears** [comment]
I get the same behavior if I select a rest instead of the measure.

**Comment by blackears** [comment]
I can hear playback if a note or rest is selected.  My point was that soloing when a range is selected is not always desirable.

**Comment by MarcSabatella** [comment]
FWIW, I tend to agree - I'd like the soloing behavior to be harder to invoke accidentally as well.  But that *is* the design, and it *does* work to select a note rest instead.  So I don't see any relevance to observations about MIDI keyboards here; seems to be a red herring.  Unless there is something special about MIDI keyboards that really does require range selections, in which case, that would be a separate issue.

**Comment by blackears** [comment]
The live MIDI playing is the scenario in which I was encountering this problem, but I guess it's not really relevant as it seems you cannot live play when playback is engaged anyway.  It would be nice to be able to do this as MS3 allowed you to.

**Comment by Tantacrul** [comment]
This is going to be something we hear a lot from MS3 users initially. I have tried to make sure it is covered in accompanying videos and other documentation.

However, once people get used to it, I'm convinced they won't be able to live without it. It's a standard function among many of our competition and a gigantic time saver from a composition POV (it means you can quickly isolate winds, brass, strings, soloists, etc. without having to open / close the mixer)

**Comment by Tantacrul** [comment]
However, it's the kind of change we try not to make because it interrupts flows users are already familiar with. Closing as **by design** but that doesn't mean the issue isn't legit. It's just one we have decided to run with.
