### ISSUE TITLE
[MU4 Issue] Playback plays when reordering instruments via drag (Musesound specific)

### ISSUE THREAD

**Issue by Valdessir** [musescore/MuseScore#14695]
**Describe the bug**
Note input playback plays in a stuttery manner when you're reordering instruments in the instrument panel via drag. It only occurs if the instrument is using musesounds.

**To Reproduce**
1. Open a new score with more than one instrument
2. Add a few notes on both instruments on the first beat
3. Set one of the instruments to Musesounds or both.
4. Drag instrument part around in the instrument panel (preferably multiple times to really trigger the bug especially for small scores)
5. Notice that the playback will play the note you inputted on the score but in a stuttery manner.

**Expected behavior**
Playback should not play when you are rearranging the order of instruments via dragging them around.

**Screenshots**
OBS recording of the score where I discovered the bug: https://drive.google.com/file/d/1utubx0QZ2jA-hgti9WiJOtJ_paW5u10I/view?usp=sharing
OBS recording of a reproduction with a new score, and using different soundfont settings in the mixer to see if it affects MSbasic set instruments too (Note how only the instruments using Musesounds play when I drag around the instrument parts): https://drive.google.com/file/d/1JVWvTb3yYML7VJpQTcCkJE0faHgghylw/view?usp=sharing

**Platform information**
 - OS: Windows 11, MU4 nightly

**Additional context**
The bug is more apparent in large scores, and hard to trigger in small scores (that's why I was dragging aggressively on the small score, but on the large score, all it took was dragging it normally like I would in an applied setting.)

**Comment by cbjeukendrup** [comment]
Probably related to:
#13826
#13603
(when one of these is fixed, we should also retest the others)

**Comment by cbjeukendrup** [comment]
@Valdessir Does this still happen?

**Comment by Valdessir** [comment]
> @Valdessir Does this still happen?

I tested this with the stable release and the MU4.02 nightly. I no longer experienced the issue on both those builds.

**Comment by cbjeukendrup** [comment]
Great! Let's mark it as completed in that case.
