### ISSUE TITLE
[MU4 Issue] Extending selection with Shift+cursor does not reposition score view

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#14691]
**Describe the bug**
WHen using Shift+cursor shortcuts like Shift+Left, Shift+Up, Ctrl+Shift+Right, etc, the selection is extended but eh score view not repositioned.  This makes it difficult to extend a note or measure at a time, because you can't see where your selection actually ends.

**To Reproduce**
1. Open a score that does not fit on the screen all at once
2. Select the last fully visible measure on screen
3. Press Shift+Ctrl+Right to extend the selection to the next measure
4. See error: score view is not repositioned

**Expected behavior**
Score view should be repositioned to show the newly-selected measure

**Platform information**
 - OS: Linux

**Additional context**
In MU3, the score was repositioned on Shift+Home/End and Shift+Ctrl+Home/End.  I'm not so convinced it should be though, because there is no concern about then continuing to select more as there is with Shift+Right etc.  And especially for Shift+Ctrl+End to select to end of score - after that, here is almost nothing you might want to do that actually involves looking at the en of the score.  It's much more likely you still want to see the start of the selection, such as if you are going to copy to the staff below.

So, I propose we only change the behavior for Left/Right/Up/Down.  But see also https://github.com/musescore/MuseScore/issues/14579.  Here, it's not about extending the range to the end of the score, but merely selecting the last element.  In that case, it does make sense to position the view there.

**Comment by erinic04** [comment]
Oh yeah I've noticed this a lot, just never remembered to report it lol. (It is really annoying though)

**Comment by DmitryArefiev** [comment]
Fixed in #15451

**Comment by DmitryArefiev** [comment]
Retested on Win10
