### ISSUE TITLE
[MU4 Issue] Preferences > Shortcuts > Define shortcut: fields for Old/New shortcut not aligned

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#14699]
In the "Define shortcut" dialog, found in Preferences > Shortcuts, the fields for the Old and New shortcut are not aligned. 

It's especially visible in the Dutch translation at the moment: 

<img width="573" alt="Scherm­afbeelding 2022-11-23 om 19 05 11" src="https://user-images.githubusercontent.com/48658420/203618201-a05ee78d-4711-42a2-b760-5ba853406e3a.png">

<sup>(Aside: that translation is incorrect; the word "Sneltoetscombinatie" is a contamination of "Sneltoets" and "Toetscombinatie". I've already fixed it on Transifex.)</sup>

**Expected behaviour**
It would be visually more pleasant if the two fields were aligned, i.e. their left sides are at the same horizontal position. 

The left-alignment of the text labels should stay as it is.

**Additional context**
This can be solved pretty easily by using a QML GridLayout instead of two RowLayouts.

**Comment by vaibhavrawat24** [comment]
Hey @cbjeukendrup can I work on this issue ?

**Comment by cbjeukendrup** [comment]
Yes, you're welcome!

**Comment by vaibhavrawat24** [comment]
thank you @cbjeukendrup for assigning me the issue, I've cloned the repo and read the readme file since I'm new to this repo can you please guide me through.

**Comment by cbjeukendrup** [comment]
I would suggest you start reading here: https://github.com/musescore/MuseScore/wiki/Set-up-developer-environment 
It is a complete guide for how to compile the code and set up your IDE for editing it.

**Comment by cbjeukendrup** [comment]
@bkunda Could you please check the linked PR to see if you like the change? (#15491)
