### ISSUE TITLE
[MU4 Issue] Instrument Changes to octave-transposing instruments can generate unnecessary courtesy clefs and key signatures

### ISSUE THREAD

**Issue by GabeS573** [musescore/MuseScore#14704]
**Describe the bug**
Using an Instrument Change to change to an instrument which transposes by octaves causes a courtesy clef and key signature to appear, even if the clef and key are identical to the ones already used.

**To Reproduce**
1. Create a score with a Vibraphone (treble clef, key of C, does not transpose).
2. Partway through the score, add an instrument change to Marimba Single Staff (also treble clef, key of C, does not transpose). As expected, **no** courtesy clef is generated because the clef and key are the same.
3. Later in the score, add an instrument change to Glockenspiel (also treble clef, key of C, _but transposes by 2 octaves_). MuseScore generates a courtesy clef and key signature, even though they are the same clef (treble) and key that were already being used in the score.

**Expected behavior**
If changing from Vibraphone to Marimba (same clef) does not cause a courtesy clef and key signature to appear, then changing from Marimba to Glockenspiel shouldn't create a courtesy clef and key signature either.

**Screenshots**
![image](https://user-images.githubusercontent.com/91428485/203672020-e918a847-0328-4d86-84bb-67c3731713b3.png)

**Platform information**
 - OS: Windows 11

**Additional context**
This isn't a very high-priority bug, since the courtesy clef and key signature can simply be deleted and do not alter subsequent notes, but it is still incorrect behavior.

**Comment by abariska** [comment]
@oktophonie could you, please, recheck it? I see this issue reproducible now
<img width="991" alt="abariska 2023-01-09 at 15 00 25" src="https://user-images.githubusercontent.com/101250347/211313845-c3ef5fc8-4a16-478e-8463-a3969f138240.png">

**Comment by oktophonie** [comment]
Checked, and seems fine with me (current master).
