### ISSUE TITLE
[MU4 Issue] Percussion instruments refuse note input

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#14720]
Testing @vpereverzev [build](https://github.com/musescore/MuseScore/pull/14684#issuecomment-1325024033) 

I would mark this as a high priority if this is affecting everyone else too. I'm not sure if it's just me

It seems only percussion-related instruments refuse to note input, both Muse sounds and MS basic.

https://user-images.githubusercontent.com/71656189/203763687-b1cb63a4-fbda-4d26-b98b-a5f7a7375e79.mov

**Comment by MarcSabatella** [comment]
It looks to me like you haven’t selected the pitch you want in the drum palette.  That’s the necessary first step to drum input when using mouse entry.

**Comment by jessjwilliamson** [comment]
AH. thank you Marc. Dumb moment!
