### ISSUE TITLE
[MU4 Issue] Incorrect transposition when changing from one transposing instrument to another.

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#14722]
**Important** (Edit Tantacrul)
Instrument changes work correctly in MU3 only if added from the [Add]>[Text] menu.  If added from the Text pallet they produce incorrect transpositions.  See https://musescore.org/en/node/320828

---

**Describe the bug**

Case 1) If applied from the pallet, new key signatures are applied at the point of the instrument change but they are incorrect.

https://user-images.githubusercontent.com/60138048/203775557-27156d67-2e95-4d16-91a0-b660a724dc74.mp4

Case 2) If applied from the [Add]>[Text] menu, the original key signature on the staff is changed and there is no new key signature added at the point of the instrument change.

https://user-images.githubusercontent.com/60138048/203775614-2b713ee6-1c0d-462e-8055-42a11281ca40.mp4

**To Reproduce**

**Case1.  Change Instrument Text added from the Text pallet.**
1. Start new score with clarinet in Bb and concert pitch key signature F major (written pitch G major). Enter notes
2. Add instrument change to clarinet in A
3. New key signature added with two flats (written pitch) it should be 4 flats Enter notes.
4. Add another instrument change to Bb clarinet
5. Key signature changes to natural – it should be back to 1 sharp. Enter notes.
6. View staff properties from right click menu and then close the dialogue
7. Notes in the A clarinet section change pitch randomly!! 

**Case 2. Change instrument Text added from [Add]>[Text] menu**
1. Start new score with clarinet in Bb and concert pitch key signature F major (written pitch G major). Enter notes
2. Add instrument change to clarinet in A from the [Add]>[Text] menuj
3. The starting key signature is changed to 4 flats but no new key signature is added.

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223280401, revision: github-musescore-musescore-2756533

@Tantacrul for triage

**Comment by sammik** [comment]
Reported alsa as #14705 

Core of issue seems to be, that new added instrument doesnt take into count that previous instrument can be transposed one.
(Issue happens also when You changes B Clarinet to Flute, ...)

**Comment by Tantacrul** [comment]
@oktophonie - what do you think? I'm guessing it's probs not an engraving thing but thought I'd give you first dibs!

**Comment by SteveBlower** [comment]
I saw #14705 but in this case the instruments are not the same transposition.  However, it seems that the underlying cause is likely the same or perhaps there is more than one underlying cause as the behaviour depends on how the instrument change is added.

It is a bit of a deal breaker for orchestral scores where change of transposing instruments on a single part is very common - clarinet in A/Bb.  Horn/Trumpet in whatever.

**Comment by sammik** [comment]
Case 2 (adding from menu Add - Text - Change instrument) is even worse (comletly unusable).

It changes initial instrument, before change. If you have Clarinet, and want to to change it at bar 4 to obe, it instead changes staff to oboe at begining of score and to clarinet at bar 4. 
See video

https://user-images.githubusercontent.com/1646034/204098788-da232b6a-b062-403f-b4e5-886035763d04.mp4


But I think, also MU3 behaviour is weired. 
User has to add some text first, than right click on it to select instrument, which also changes that text he had to add before.

https://user-images.githubusercontent.com/1646034/204098969-09b4f0e3-0e55-4e6c-86ae-aa18f4f2f5e1.mp4


I think, it would be better, if menu Add-Text-Change instrument directly calls Select instrument dialog. @Tantacrul ?

**Comment by Tantacrul** [comment]
Yeah, the first point has to be fixed now.

https://user-images.githubusercontent.com/21022311/204264212-553eb9cc-6464-4306-a6e1-bb5844567da7.mov

1. When changing from one transposing instrument to another, the new transposition is wrong. (The second instrument is calculating its transposition based on the first instrument, rather than calculating from C) 
2. This means that you still see the transposing key signature of the first instrument when you enable concert pitch (you should see no key signatures in this instance)

**Comment by Tantacrul** [comment]
Whoever is working on this, I'll help, advise & test.

**Comment by sammik** [comment]
@Tantacrul I already did basic change, which seem to resolves "case 1" - adding from palette. 
Feel free to test it #14802, there is also some info in PR message, if someone want do something better.

**Comment by DmitryArefiev** [comment]
Fixed in #14804

**Comment by Tantacrul** [comment]
Excellent stuff!
