### ISSUE TITLE
[MU4 Issue] "You are not signed in" dialog missing from save to cloud flow (existing scores)

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#14725]
**Describe the bug**
When an existing cloud score is saved in the latest nightly, and the user is not logged in to their musescore.com account in the app, the web browser is triggered immediately on the 'Save' command without triggering this dialog first: 

<img width="480" alt="Modal_Dialog_1" src="https://user-images.githubusercontent.com/86290556/203811262-9050ccc5-7d1e-411f-993f-517c49fa321b.png">

**To Reproduce**

Demo video: https://www.dropbox.com/s/xvw7cawerjuos8a/cloud-save-login-dialog.mov?dl=0

**Expected behavior**
The "You are not signed in" dialog should appear on existing cloud scores when the user executes a 'Save' command and is not already logged in via the app.

**Platform information**
 - macOS 12.6 (M1) 
 
**Additional context**
@Tantacrul FYI

**Comment by cbjeukendrup** [comment]
(@Eism I took this one, hope you don't mind 🙂)
