### ISSUE TITLE
[Muse Hub] Muse Hub won't open (Windows App)

### ISSUE THREAD

**Issue by MalignantCarp** [musescore/MuseScore#14735]
**Describe the bug**
Muse Hub doesn't open. There are no error messages that are brought to the user's attention, it just silently fails.

**To Reproduce**
Likely not reproducible without particular conditions.

I have installed Muse Hub from the MuseHub.com website. The service doesn't start and the application doesn't start, either. It just silently fails. Attempting to manually start the service gives error 1053: The service did not respond to the start or control request in a timely fashion.

**Expected behavior**
Muse Hub should open.

**Platform information**
Windows 10 Pro 64 Bit, Version 21H2 Build 19044.2251.

**Additional context**
I'm not sure if this is tied to #14178 or not, or whether that op is experiencing due to a similar reason.

I have the following error reports in my Windows logs:

__Application Error__
```
Faulting application name: Muse.Service.exe, version: 0.9.9.515, time stamp: 0x6331eb0e
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2193, time stamp: 0x7f7062e1
Exception code: 0xe0434352
Fault offset: 0x000000000002cd29
Faulting process id: 0x20a0
Faulting application start time: 0x01d9008e5254d59d
Faulting application path: C:\Program Files\WindowsApps\Muse.MuseHub_0.9.9.515_x64__rb9pth70m6nz6\Muse.Service.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 03d21673-8f5e-4b6f-821b-c62d1ce8fd92
Faulting package full name: Muse.MuseHub_0.9.9.515_x64__rb9pth70m6nz6
Faulting package-relative application ID: App
```
__.NET Runtime Error__
```
Application: Muse.Service.exe
CoreCLR Version: 6.0.922.41905
.NET Version: 6.0.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Stopped without starting
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args) in D:\a\Muse\Muse\Windows\src\Muse.Service\Program.cs:line 71
   at Program.<Main>(String[] args)
```

There is also an empty log entry for Muse Hub Background Service.

In my case, and after seeing where this application is installed, it appears that Muse Hub was developed as a Windows App instead of a standard executable. When I built this rig back in 2019, as part of my security measures, I permanently disabled the Windows App Store, thus I suspect the components required to run the application are not present on my rig. But in the unlikely chance it is something else, I thought I should bring this all up.

**Comment by MalignantCarp** [comment]
Well, this is interesting. After a few subsequent restarts while solving an entirely unrelated issue, both the service and Muse Hub itself appear to run now. Muse Hub suddenly popped open on one of the restarts. It didn't initially have any Internet access as I had Metro Apps blocked in my firewall, but it does appear to work just fine. Taking forever to download MuseScore, though. Can download a sample library in minutes, but it just sits there spinning on MuseScore. I'm sure it will finish eventually.

This can probably be closed.

**Comment by zacjansheski** [comment]
Closing as fixed in V2
