### ISSUE TITLE
[Muse Sound Issue] Muse Sound and microtonal musics

### ISSUE THREAD

**Issue by kyeon-go** [musescore/MuseScore#14739]
**Describe the bug**
Muse Sound doesn't play microtonal musics(e.g 19-TET) properly

**To Reproduce**
1. Open any microtonal music (especially 19-TET)
2. Change playback profile to Muse Sound
3. Click play

**Expected behavior**
In 12-TET, Muse Sound's quality is good
I expected that quality in microtonal musics.

**Platform information**
 - OS: Windows 11 22H2 (10.0.22621.819)
 - Musescore : 4.0.223072007
 - Muse Hub : 0.9.9.515

**Comment by cbjeukendrup** [comment]
I've created a new issue that represents the current state more specifically: #18036
