### ISSUE TITLE
[MU4 Issue] Empty window/crash when closing Preferences without opening a score (first run or after Reset preferences, Mac only)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#14742]
**To Reproduce**
1. Reset preferences 
2. Restart MU
3. Open Preferences
4. Click OK

https://user-images.githubusercontent.com/90187801/203985216-20d93dc3-a114-459f-9055-291a1d49f4c0.mov

**Platform information**
macOS 12.6

**Additional context**
Related to #14489

**Comment by zacjansheski** [comment]
@DmitryArefiev does this still happen for you?

**Comment by DmitryArefiev** [comment]
@zacjansheski Doesn't happen anymore.  Still **happens in 4.0.2** release, but **doesn't occur** in **4.1** release and **4.1.1** RC.  
Was fixed somewhere in 4.1
