### ISSUE TITLE
[MU4 Issue] Changing volume faders causes VST effects to be removed

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#14752]
Double clicking on the master fader knob, which my intention is to reset the value back to 0, it is also ending up deleting the master effects which should not happen at all! FXs should still stay in place no matter what.

The only way to get those effects back is to close without saving then re-open project again.

MacOS Ventura

https://user-images.githubusercontent.com/71656189/204025982-a20874f1-37a2-435c-bb0d-f05aeb262574.mov

**Comment by jessjwilliamson** [comment]
Just also tried if just changing volume knob from 0 to another value and it does the same effect. Best to see this when you just opened a project, add effects, save, close, reopen and try what I showed above

**Comment by jessjwilliamson** [comment]
**UPDATE:**
Further found out it's **NOT just the master fader.** It's **ALL faders** when this happens:
1. When you open an existing score with FXs already, move volume - FX disappears
2. Open a score, insert FX, save, close, reopen, move volume slider - FX disappears.

https://user-images.githubusercontent.com/71656189/205875240-44940bee-52f3-4bc8-9ff9-c67cb12b0c8a.mov

**Comment by DmitryArefiev** [comment]
Fixed in #14752
