### ISSUE TITLE
[MU4 Issue] selecting key signature selcts only one in bottom staff

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#14769]
**Describe the bug**
Select key signature. Only bottom staff one is selected.

**To Reproduce**
1. Select keysignature
2. See - only bottom staff one is selected

**Expected behavior**
Key signatures in all staves are selected.

**Screenshots**

https://user-images.githubusercontent.com/1646034/204076996-7db4b9ae-548b-4122-98c1-3f2cdf11cf42.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
Regression. Didnt occur in 3.6.2 nor in previous MU4 nightlies (not sure, when it appeared).

**Comment by sammik** [comment]
@Tantacrul I ping You, as I think, this is quite crucial issue.

**Comment by erinic04** [comment]
I don't see this behavior in the latest build.

**Comment by sammik** [comment]
I just checked Win, and present there too (todays nightly).

**Comment by erinic04** [comment]
Interesting

https://user-images.githubusercontent.com/21023353/204077806-945f5edc-3144-4a67-9493-2b0982521e80.mp4

**Comment by erinic04** [comment]
I'm using the build from today (the one in the Discord)

**Comment by sammik** [comment]
> I'm using the build from today (the one in the Discord)

Ah, Yes, You checked RC testing version. That one works fine.

Master (nightly) is affected.
