### ISSUE TITLE
[MU4 Issue] Fortepianos don’t playback

### ISSUE THREAD

**Issue by JordanTMM** [musescore/MuseScore#14767]
**Describe the bug**
When trying to playback a fortepiano, you only receive a forte 

**Expected behavior**
Fortepianos should start loud and get instantly quiet, instead of staying at loud volume 

**Platform information**
Windows 11

**Comment by erinic04** [comment]
Already reported. (#13543) Thanks for reporting though!

**Comment by cbjeukendrup** [comment]
Duplicate of #13543
