### ISSUE TITLE
MuseScore4 crashes when exporting audio

### ISSUE THREAD

**Issue by scilxurkel001** [musescore/MuseScore#14765]
**描述Bug/Describe the bug**
如题，MuseScore4在导出音频至80%时崩溃了。
As the title suggests, MuseScore4 crashes when exporting audio to 80%.

**如何复现/How to Reproduce**
[升C小调第14钢琴奏鸣曲_月光第三乐章.zip](https://github.com/musescore/MuseScore/files/10095613/C.14._.zip)
1. 打开上面附件里面的MSCZ文件
2. 点击“文件”>“导出”
3. 选择MP3文件，点击确定
------------------------------------
1. Open the MSCZ file in the attachment above
2. Click on "File" > "Export"
3. Select the MP3 file and click OK

**预期操作/Expected operation**
MP3文件被导出到指定文件夹中。
MP3 files are exported to the specified folder.

**实际上/In fact**
在进度条走到80%时，MuseScore4意外崩溃。
MuseScore4 crashes unexpectedly when the progress bar reaches 80%.

**严重性/Severity**
中等 Medium

**附加信息/Additional Information**
操作系统：Windows 11 22H2（内部版本22621.819）
Operating system: Windows 11 22H2 (internal version 22621.819)

PS：当视频可用时，将提供视频。Videos will be provided when they are available.

**Comment by scilxurkel001** [comment]
[2022-11-26_12-17-01.zip](https://github.com/musescore/MuseScore/files/10095657/2022-11-26_12-17-01.zip)
Video posted.

**Comment by erinic04** [comment]
I have noticed in my exporting that 80% is the final number displayed before it jumps to 100% on the export, so it might be having trouble with something in finalizing the exported file.

**Comment by scilxurkel001** [comment]
我已经从官网下载了最新的Nightly Builds（上传于2022年11月28日，版本号：4.0.0.223320401的预发布不稳定版），经过实际测试，此问题依旧出现。
顺带一提的是，此问题不仅依旧出现，导出的速度比原来（在Github Releases下载的MuseScore4 Beta版本）慢了很多【我无语了】。
文件如下，请尽快查找问题，发现原因，感谢！
I have downloaded the latest Nightly Builds (uploaded on Nov 28, 2022, version 4.0.0.223320401 pre-release unstable) from the official website, and after actual testing, this issue still appears.
Incidentally, not only does the problem persist, the export speed is much slower than the original (MuseScore4 Beta downloaded from Github Releases) [I'm speechless].
The file is below, please look for the problem and find the cause as soon as possible, thanks!
[升C小调第14钢琴奏鸣曲_月光第三乐章.zip](https://github.com/musescore/MuseScore/files/10108468/C.14._.zip)

**Comment by Tantacrul** [comment]
I've moved this into release just so we can try to establish what the issue is here.

@scilxurkel001 - I can audio it on MacOS. This must be an issue with MS4 and your sound card / sound device. We have made a lot of changes recently in this area.

Can you provide the machine specs and info about your sound setup? Buffers / sample rates. Anything like that?

It's essential for us to figure out the issue. Thanks for all your help so far.

**Comment by vpereverzev** [comment]
> 我已经从官网下载了最新的Nightly Builds（上传于2022年11月28日，版本号：4.0.0.223320401的预发布不稳定版），经过实际测试，此问题依旧出现。 顺带一提的是，此问题不仅依旧出现，导出的速度比原来（在Github Releases下载的MuseScore4 Beta版本）慢了很多【我无语了】。 文件如下，请尽快查找问题，发现原因，感谢！ I have downloaded the latest Nightly Builds (uploaded on Nov 28, 2022, version 4.0.0.223320401 pre-release unstable) from the official website, and after actual testing, this issue still appears. Incidentally, not only does the problem persist, the export speed is much slower than the original (MuseScore4 Beta downloaded from Github Releases) [I'm speechless]. The file is below, please look for the problem and find the cause as soon as possible, thanks! [升C小调第14钢琴奏鸣曲_月光第三乐章.zip](https://github.com/musescore/MuseScore/files/10108468/C.14._.zip)

Could you also provide us with the content of your "MuseScore4.0 > logs" folder. You can fine the path in "Diagnostic > System > Show paths". Double-click on "userAppData"

Thanks!

**Comment by scilxurkel001** [comment]
![image](https://user-images.githubusercontent.com/82962664/204445750-f5ecd79c-02cd-4301-b174-b550b355f5ad.png)
![image](https://user-images.githubusercontent.com/82962664/204445787-9eb84214-67cd-47db-bb23-be66c87b8b71.png)
![image](https://user-images.githubusercontent.com/82962664/204445832-b8db87e0-7bf3-4e27-b1e4-39f26638f655.png)
![image](https://user-images.githubusercontent.com/82962664/204445898-79cc40b1-9c6e-4715-a48b-cc6675f9b42e.png)
[MU4Logs.zip](https://github.com/musescore/MuseScore/files/10110004/MU4Logs.zip)
This may be help.
And I will test them in my Windows 7, Windows 8.1 and Windows 10 1607/1909 VMs.
Thanks!

**Comment by vpereverzev** [comment]
@scilxurkel001 could you please try to:
- turn off "auto-update checking", see screenshot below
![image](https://user-images.githubusercontent.com/57620349/204520378-abece7dd-508a-444f-820b-da7a279a98a7.png)
- try to reproduce your issue one more time

**Comment by scilxurkel001** [comment]
[2022-11-29_21-00-15.zip](https://github.com/musescore/MuseScore/files/10113423/2022-11-29_21-00-15.zip)
I have done so, but the problem still exists.
I will create a new score and see if it still exists.

**Comment by vpereverzev** [comment]
> [2022-11-29_21-00-15.zip](https://github.com/musescore/MuseScore/files/10113423/2022-11-29_21-00-15.zip) I have done so, but the problem still exists. I will create a new score and see if it still exists.

may I ask you for the fresh logs after that? :)

**Comment by scilxurkel001** [comment]
[MuseScore_221129_213700.log](https://github.com/musescore/MuseScore/files/10113682/MuseScore_221129_213700.log)

**Comment by scilxurkel001** [comment]
The problem seems to have gotten worse.
See the video for more details.

https://user-images.githubusercontent.com/82962664/204549926-91a0aff9-841e-4901-9eaf-0f18815b2556.mp4

Log File:
[MuseScore_221129_214115.log](https://github.com/musescore/MuseScore/files/10113733/MuseScore_221129_214115.log)

**Comment by vpereverzev** [comment]
> The problem seems to have gotten worse. See the video for more details.
> 2022-11-29_21-42-00.mp4
> 
> Log File: [MuseScore_221129_214115.log](https://github.com/musescore/MuseScore/files/10113733/MuseScore_221129_214115.log)

thanks!

@scilxurkel001 judging by the log output I have one theory - I assume it'd crash for you if in the "Export Dialog" you'll choose 48000 sample rate instead of 44100. Is that correct?

**Comment by scilxurkel001** [comment]
No, all is default. 44100Hz

**Comment by scilxurkel001** [comment]
Everything is set by default and unchanged.
You can watch the video.

Tomorrow (GMT +8:00) I will try the VM to see if the same problem happens.

**Comment by vpereverzev** [comment]
> Everything is set by default and unchanged. You can watch the video.
> 
> Tomorrow (GMT +8:00) I will try the VM to see if the same problem happens.

Sorry, I wasn't clear about that. Let me reword this.

I assume that **if you'll deliberately set 48000 sample rate in that dialog it'd work fine**. Let's give a try and please let me know what happens

**Comment by scilxurkel001** [comment]
Windows 10 1607 virtual machine test results: the problem still exists.
The following log files are available.
[MuseScore_221130_124148.log](https://github.com/musescore/MuseScore/files/10119547/MuseScore_221130_124148.log)

Video is here:

https://user-images.githubusercontent.com/82962664/204710280-2ed7acde-e110-4ea2-90c4-ba506574783b.mp4

Additional information.
Host system: Windows 11 22H2 22621.819
Virtual machine system: Windows 10 LTSB 1607 14393.2035

Please find and fix the problem as soon as possible based on the above log files and videos, thank you for your efforts and dedication.

**Comment by scilxurkel001** [comment]
Now give a temporary solution. If you encounter the same problem, try exporting MP3 audio files using the following method.
First, download MuseScore3 from musescore.org, install it and open it. (If you downloaded the portable version, you can use 7-Zip to extract it to some folder - except Program Files, Program Files (x86) or Windows folder)
Export your score to a midi file using MuseScore4. Then open the midi file you just exported with MuseScore3.
Finally, export the MP3 audio file with MuseScore3.

**Comment by Tantacrul** [comment]
> Windows 10 1607 virtual machine test results: the problem still exists. The following log files are available. [MuseScore_221130_124148.log](https://github.com/musescore/MuseScore/files/10119547/MuseScore_221130_124148.log)
> 
> Video is here:
> 
>  2022-11-30_12-41-29.mp4 
> Additional information. Host system: Windows 11 22H2 22621.819 Virtual machine system: Windows 10 LTSB 1607 14393.2035 VM Software: VMware WorkStation Pro 12.5.9 Please find and fix the problem as soon as possible based on the above log files and videos, thank you for your efforts and dedication.

One thing: please don't log virtual machine issues. We don't solve things that break on virtual machines because we're a cross platform app. We have dedicated builds for each OS.

In this case, it's fine because you are telling us about your Win11 build. But make sure that in future, if you are experiencing a problem only with a VM, do not post the issue because we will not address it.

**Comment by scilxurkel001** [comment]
> > Windows 10 1607 virtual machine test results: the problem still exists. The following log files are available. [MuseScore_221130_124148.log](https://github.com/musescore/MuseScore/files/10119547/MuseScore_221130_124148.log)
> > Video is here:
> > 2022-11-30_12-41-29.mp4
> > Additional information. Host system: Windows 11 22H2 22621.819 Virtual machine system: Windows 10 LTSB 1607 14393.2035 VM Software: VMware WorkStation Pro 12.5.9 Please find and fix the problem as soon as possible based on the above log files and videos, thank you for your efforts and dedication.
> 
> One thing: please don't log virtual machine issues. We don't solve things that break on virtual machines because we're a cross platform app. We have dedicated builds for each OS.
> 
> In this case, it's fine because you are telling us about your Win11 build. But make sure that in future, if you are experiencing a problem only with a VM, do not post the issue because we will not address it.

Comprehension.
In fact, I just tried to try different environment variables. Because environment variables may affect the running state of software, for example, software that works on Windows 10 may not work well on Windows 7, or run differently.
Since I have a single environment variable on my computer and I will only have the opportunity to test it on other computers once the COVID19 outbreak is over, I had to use a virtual machine to create different environment variables. This is actually a clumsy way to do it.
For now I will still operate with Windows 11 on my own physical machine, and when the outbreak is over I will try other computers and systems to test if the problem is with the computer hardware itself.

**Comment by Tantacrul** [comment]
OK, understood. Thanks very much.

**Comment by Tantacrul** [comment]
Since we're unable to reproduce this and can't figure out what the specific issue is here (this is the only existing report of it), we have to bump it to Post Release.

**Comment by scilxurkel001** [comment]
Okay, I'll try to find a few more test environments to see if there's a problem with my hardware itself.

**Comment by lukasz-matylla** [comment]
I seem to have just encountered the same or a very similar issue.
The application crashes at 80% when exporting to mp3.
It happened on the RC build from 2022-12-03. My system is Windows 10.

The log and the mscz file that causes the crash are attached.

[Crash.zip](https://github.com/musescore/MuseScore/files/10146433/Crash.zip)

**Comment by vpereverzev** [comment]
> I seem to have just encountered the same or a very similar issue. The application crashes at 80% when exporting to mp3. It happened on the RC build from 2022-12-03. My system is Windows 10.
> 
> The log and the mscz file that causes the crash are attached.
> 
> [Crash.zip](https://github.com/musescore/MuseScore/files/10146433/Crash.zip)

looks like there should be another log, the one you've attached doesn't contain any info about exporting. Can you please try to find and attach another one? Or simply try to reproduce the issue one more time and send us the latest file from there

Thanks

**Comment by lukasz-matylla** [comment]
That's the only file that was created in the folder pointed to userAppDataPath, in subfolder "logs". 

I just re-ran the export. Crashed again. I hope the log will be more helpful this time.
[MuseScore_221203_150009.log](https://github.com/musescore/MuseScore/files/10146574/MuseScore_221203_150009.log)

**Comment by cbjeukendrup** [comment]
@scilxurkel001 When you export audio and this crash occurs, does the filename maybe contain "special" characters (for example, Chinese characters, emoji, accented letters...)? 

If yes, does it still crash if you try to export to a filename containing only English letters?

In #14913, the "special" characters seem to be the cause of a crash, so I wondered whether that is the case here too.

**Comment by scilxurkel001** [comment]
Now I use full English paths and English filenames and it exports.
Maybe that's the reason for this.
Thanks.

**Comment by vpereverzev** [comment]
@scilxurkel001 can you please check this issue on that build?

https://github.com/musescore/MuseScore/suites/9677220380/artifacts/463337181

**Comment by bakajikara** [comment]
@vpereverzev It's fixed in that build. Thanks!

**Comment by scilxurkel001** [comment]
Now it's fixed in this build.
Thanks for your efforts and dedication.
This issue will be closed as completred.

**Comment by cbjeukendrup** [comment]
@Tantacrul Here's a quick list of issues that seem related:
#14913
#14613
#14514
#14173

We should test those too in @vpereverzev's build.

**Comment by CarlGao4** [comment]
This still happens on my computer.
