### ISSUE TITLE
[MU4 Issue] Increasing buffer seems to do nothing

### ISSUE THREAD

**Issue by Fristover** [musescore/MuseScore#14760]
**Describe the bug**
Buffer size seems to stay at 1024 even when 2048 or 4096 are selected

**To Reproduce**
1. Open any score (you need to have some performance issues to notice this)
2. Select buffer size 1024 and play, hear some stuttering
3. Select buffer size 2048 or 4096 and play, hear no improvement

**Expected behavior**
Buffer sizes should change

**Screenshots**
Recording with buffer 4096 on the latest nightly available (11/25/22)
https://www.dropbox.com/s/zo9ly4hc328n9n4/Nightly.mp4?dl=0

Recording with buffer 4096 on the "RC candidate" (1024 sounds exactly the same)
https://www.dropbox.com/s/embja7fa0f4g3xw/RC%20candidate.mp4?dl=0

**Platform information**
 - OS: Windows 11 22H2 22621.819

**Additional context**
This doesn't happen with the latest nightly and I suspect this has to do with builds with installer since the same has happened with some other builds I have installed that way, ~~I'll wait for this night's nightly to confirm this anyway.~~ I've confirmed this only happens with builds with an included installer as the latest nightly is totally fine.

**Comment by GabeS573** [comment]
I'm experiencing this same issue, also on Windows 11. As pointed out in Additional Context, this was also an issue back when the Beta and Alpha were released (although iirc the alpha did not have as many options for buffer sizes as the current builds do).

**Comment by Fristover** [comment]
I did try today's nightly (Nov, 26) and buffer size seems to change as expected (see attached video), so I can confirm this issue only happens with builds that have to go through an installer.

https://www.dropbox.com/s/t8178dakwlitqzl/Nightly1126.mp4?dl=0

**Comment by Tantacrul** [comment]
In around 30 minutes, this build will be ready. It fixes one issue with WASAPI, where it automatically chooses the lowest latency option. This build should now return the ability to change buffer size to fix those stuttering problems.

https://github.com/musescore/MuseScore/actions/runs/3558033558

**Comment by Fristover** [comment]
I have tried the build here because it seemed to be linked to the one that failed, I didn't see any difference still.

 https://github.com/musescore/MuseScore/actions/runs/3559284321

**Comment by vpereverzev** [comment]
test this one pls
https://github.com/musescore/MuseScore/suites/9543256626/artifacts/453807796

**Comment by Tantacrul** [comment]
Yes, we'd really appreciate it if you'd try the build @vpereverzev provided above and let us know!

Thanks!

**Comment by Fristover** [comment]
I just tested this one, buffer size does change now but playback randomly rewinds like 1 or 2 beats for some reason, no stuttering though...

**Comment by Tantacrul** [comment]
> I just tested this one, buffer size does change now but playback randomly rewinds like 1 or 2 beats for some reason, no stuttering though...

When you say it randomly rewinds, could you possibly provide a video so we can understand what that looks like?

Does it do it once? Does it do it repeatedly during playback?

**Comment by Fristover** [comment]
ok so I rebooted my laptop because windows updates and it's much worse now, BUT it works just fine if mixer is opened

https://www.dropbox.com/s/9qrhivwzg4w2wl9/buffer.mp4?dl=0

**Comment by vpereverzev** [comment]
@Fristover @GabeS573 could you also provide us with info regarding your PC specs? Thanks!

**Comment by GabeS573** [comment]
> test this one pls https://github.com/musescore/MuseScore/suites/9543256626/artifacts/453807796

The buffer size seems to work for me in this build. I'm not hearing any more popping noises or lag on the 4096 buffer size!

**Comment by GabeS573** [comment]
> @Fristover @GabeS573 could you also provide us with info regarding your PC specs? Thanks!

![image](https://user-images.githubusercontent.com/91428485/204435273-6cda3675-9f03-4c12-9d54-8d8122b6ddf1.png)

**Comment by GabeS573** [comment]
> ok so I rebooted my laptop because windows updates and it's much worse now, BUT it works just fine if mixer is opened (video is less laggy irl but obs did its thing)
> 
> https://www.dropbox.com/s/9qrhivwzg4w2wl9/buffer.mp4?dl=0

That's strange, I'm not experiencing that issue. Playback works fine regardless of whether the mixer is open or not.
