### ISSUE TITLE
[MU4 Issue] Musescore doesn't allow soundfonts to use samples above C8 or below C0

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#14778]
**Describe the bug**
Musescore 4 doesn't allow soundfonts to use samples above C8 or below C0, even if the soundfont itself supports it.

**To Reproduce**
1. Create a score with a soundfont that uses pitches above C8 or below C0 (ex. unpitched percussion)
2. Write notes going above C8 or below C0
3. Hear that all the notes above C8 or below C0 sound exactly the same as C8

**Expected behavior**
Musescore should allow the use of samples above C8 or below C0

**Screenshots**
MS3:

https://user-images.githubusercontent.com/21023353/204118547-8beac9c9-e46b-46bd-b8f5-93a520395453.mp4

MS4:

https://user-images.githubusercontent.com/21023353/204118554-b00b8e72-30b2-4c3e-bdfd-925fa0c6ceab.mp4

https://user-images.githubusercontent.com/21023353/204118566-e29e8477-3eef-48c0-bc8d-2fc0d6000e03.mp4

https://user-images.githubusercontent.com/21023353/208227596-557ec16a-2a75-442c-bf10-ec746883f6e4.mp4

**Platform information**

 - OS: Windows

**Additional context**
This is very inconvenient for things like instruments where the staccato samples are 3 or 4 octaves above the regular notes.

**Comment by erinic04** [comment]
Update: MS also doesn't allow the use of samples below C0, and if they are notated, they play as C8 also

**Comment by cbjeukendrup** [comment]
I found that this is a more general problem, not specific to SoundFonts, so I created #16657 and will close this one.
