### ISSUE TITLE
[MU4 Issue] ledger lines too wide in scaled staves

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#14792]
**Describe the bug**
If staff is scaled to 200% or 400%, ledger lines are too wide. (If scaled down, it is oposite).

**To Reproduce**
1. write note with ledger line
2. Change scale (Right click - Staff/part properties - Scale) to 400%
3. See - wide ledger lines

**Expected behavior**
Width of ledger lines should be scaled proprtionally.

**Screenshots**
![Ledgerline-wide](https://user-images.githubusercontent.com/1646034/204205717-3aac468a-a3d3-44ae-a41b-bc1d943cec37.png)

**Platform information**
 - OS: [reported on Linux]

**Comment by erinic04** [comment]
This also happens with score wide scaling, just not permanently. If you edit anything, it goes away

**Comment by sammik** [comment]
> This also happens with score wide scaling, just not permanently. If you edit anything, it goes away

I am not sure, I understand. Could You please describe it step by step?
Thank You!

**Comment by erinic04** [comment]
I'll make a video. One minute

**Comment by erinic04** [comment]
Alright here 

https://user-images.githubusercontent.com/21023353/205188926-7bad97c2-c25c-43cd-9ef9-81e5a6f0ace2.mp4
