### ISSUE TITLE
[MU4 Issue] New Audio Changes Cause Logitech Headset to Play at Very Fast Speed.

### ISSUE THREAD

**Issue by LuisLiszt** [musescore/MuseScore#14809]
**Describe the bug**
Watch the video, it's hard to describe but the playback is completely distorted. This is the case since the nightly build of 24th November. When I use the version of 23rd November the playback is normal. It's the same for MuseSounds and MSBasic.

**To Reproduce**
1. Use any nightly build since 24th November.
2. Play any score.

**Expected behavior**
Score should play normal.

**Screenshots**

https://user-images.githubusercontent.com/55204261/204338044-b6a66202-49f8-4657-9fd7-9c24d6bd898b.mp4

**Platform information**
 - OS: Windows

**Comment by cbjeukendrup** [comment]
@Tantacrul for triage

@LuisLiszt Could you add some details about your speaker setup and sound card? What is your sample rate, buffer size etc.?

**Comment by LuisLiszt** [comment]
@cbjeukendrup 
My buffer size is 2048, changing this option doesn't have affects on the problem, it still persists. I use a Logitech Headset and with it's own driver (this probably isnt the problem as it works with nightlies before 24th November). In system settings I've set the quality to CD-quality (16 Bit, 44100HZ), changing this to higher or lower option doesn't resolve the problem either.

**Comment by Tantacrul** [comment]
@LuisLiszt - there has a been a major change to MS4's audio engine for Windows, so it may very well be a compatibility issue with your setup.

You have a Logitech Headset. What kind of sound card or external sound unit do you use?

If you don't use the Logitech Headset, what happens?

**Comment by LuisLiszt** [comment]
@Tantacrul - I don't use an external sound card I just plug the USB Cable of Logitech in the Mainboard and then the Sound is managed by Logitech GHUB. When I change the output in MuseScore to my monitor I don't hear anything but based on the blue playback line it seems to play normal. Interesting...

**Comment by Tantacrul** [comment]
I assume you don't hear anything because you don't have a sound source? (Hence, why you need the Logitech?)

**Comment by LuisLiszt** [comment]
@Tantacrul - I don't hear anything because I would have to put a 3.5mm Audio Cable in my monitor to hear something, when I set it as my output source. I use the Logitech G432 headset with the newest version of LGHUB.

**Comment by vpereverzev** [comment]
@LuisLiszt

Can you please:
1 - clear MuseScore4 "logs" folder. To find out the path open MuseScore 4.0 > Diagnostic top menu > System > Show paths > Double click on "UserAppDataPath"
2 - grab this build (which includes extra logging) - https://github.com/musescore/MuseScore/suites/9548882963/artifacts/454195567
3 - install and launch downloaded version
4 - try to playback some random score on different buffer sizes (Preferences > IO)
5 - close app and throw me the content of updated "logs" folder

Thanks

**Comment by vpereverzev** [comment]
> @vpereverzev [MuseScore_221129_154143.log](https://github.com/musescore/MuseScore/files/10114078/MuseScore_221129_154143.log)

@LuisLiszt have you tried to reproduce the issue on the build I gave?

One other question - do you have any other speakers on your laptop/pc apart from logitec headset and your monitor? Does the problem occurs on any other devices you have?

Also, are there any sample rate related settings in the Logitech GHUB? it looks to me that they're being set to 96000+ somewhere

**Comment by LuisLiszt** [comment]
@vpereverzev yes, the same issue occured with your build. I don't have any other soundcards except my headset and monitor, of course the mainboard has plugs for audio aswell. I don't see any sample rate related settings in GHUB and no value of 96000.

**Comment by Tantacrul** [comment]
This is a Logitech headset issue, which the logs indicate is using a really high sample rate. Since when you remove the logitech, MS4 appears to be operating normally, we'd advise getting some other type of sound device.

We'll continue helping you to resolve this issue. We'll need to get a Logitech headset ourselves! However, we have to bump this to Post-Release because we have no more time to troubleshoot now.

**Comment by cbjeukendrup** [comment]
Also came up in https://github.com/musescore/MuseScore/issues/14921

**Comment by LionFJ** [comment]
same thing happened to me. 

Windows 11
Beyerdynamic Headset Straight into PC
Sonar GG Audio Interface (default interface had the same problems)

**Comment by LuisLiszt** [comment]
@Tantacrul interestingly, everyone who has this issue (including me, @LionFJ and #14921 ) have Windows 11. Maybe it's related to Windows 11?

**Comment by cbjeukendrup** [comment]
In any case it's not caused by _just_ Windows 11, because on my (virtual) Windows 11 machine, it works fine.

**Comment by AdamAViolist** [comment]
Switching audio sources for me does not resolve the issue.

Using Roccat Elo 7.1 Air, audio is fastest with 2 octave pitch up. [16 bit, 48000 Hz]

Using Speakers(Realtek Audio), audio is only pitched up 1 octave. [24 bit, 96000 Hz]

Using a pair of Audio-technica ATH-M40x, audio works as expected. [2 channels, 24 bit, 48000 Hz]

**Comment by LionFJ** [comment]
I changed the playback device from system default to my regular headphones and now instead of it play 4x speed and up two octaves it is playing at 1/2 speed and down two octaves!

**Comment by vpereverzev** [comment]
@LuisLiszt @LionFJ @AdamAViolist 
Can you please try to reproduce this issue on that [build ](https://github.com/musescore/MuseScore/suites/9677220380/artifacts/463337181) and show me the fresh log file

THanks!

**Comment by LuisLiszt** [comment]
@vpereverzev issue persists.
[MuseScore_221205_185500.log](https://github.com/musescore/MuseScore/files/10156637/MuseScore_221205_185500.log)

**Comment by vpereverzev** [comment]
> @vpereverzev issue persists. [MuseScore_221205_185500.log](https://github.com/musescore/MuseScore/files/10156637/MuseScore_221205_185500.log)

It was just a build with a bunch of debug information, so it only helps to collect some data to resolve the issue. Thanks for quick response!

@LuisLiszt what is your nickname in our Discord server? I think direct chat would simplify this investigation

**Comment by LionFJ** [comment]
@vpereverzev you can message me on discord server also (Lion) and maybe we can resolve it quicker.

**Comment by LuisLiszt** [comment]
@vpereverzev Luis04#5811

**Comment by jopherleap** [comment]
Just wanted to chime in -- I'm getting the same problem on Windows 10 with a Corsair Void Pro wireless headset. Not a huge problem, as it goes away once I use other headphones.
