### ISSUE TITLE
[MU4 Issue] Crash when switching Tenor to Muse Choir (Soprano, Alto, Bass seem to work) (Win10)

### ISSUE THREAD

**Issue by HuBandiT** [musescore/MuseScore#14800]
**Describe the bug**
Crash when I try to switch Tenor to Muse Choir Tenors in the the attached score.

**To Reproduce**
1. Open [attached score](https://github.com/musescore/MuseScore/files/10103360/Csilagfenyes.Csondes.Ejjel.zip). Observe how Soprano, Also, Bass is set to Muse Choir, while Tenor is set to MS Basic.
2. Observe, that playback works, no crashes occur.
3. Try to set Tenor to Muse Choir Tenors.
4. MuseScore crashes.

**Expected behavior**
MuseScore should set Tenor to Muse Choir Tenors, and allow continuing work with the score, including playback.

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223310401, revision: github-musescore-musescore-9c645ff

**Comment by HuBandiT** [comment]
Probably related to #14598 ?

**Comment by fynndesign** [comment]
Downloaded, tried and it worked flawlessly for me. Using latest nightly build on MacOS Ventura.

**Comment by HuBandiT** [comment]
Thank you for trying. Same thing transpired on my other reported crash: crashes consistently for me on Win10, works well for someone else on MacOS.

This suggests the bug might be platform-specific. Perhaps something in the audio layer(s) on Windows?

Any way I can help further?

**Comment by fynndesign** [comment]
You're welcome. Nice arrangement of Hark the Herald Angel sings btw ;)

**Comment by Tantacrul** [comment]
This is a problem on all OS. It has already been logged (and fixed). We're just waiting for the sampler update to be pushed.

Since this issue has already been logged, I'll close this one. Thanks!

**Comment by HuBandiT** [comment]
@fynndesign I'm merely a transcriber, it is not my arrangement. :)

@Tantacrul Lovely! Looking forward to it!
