### ISSUE TITLE
[TASK] Since we are not implementing 'Count In' in MS4.0, we need to hide the UI for it

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#14807]
**Describe the bug**
This option needs to be hidden until we have the 'Count-in' feature re-implemented in 4.X

<img width="441" alt="image" src="https://user-images.githubusercontent.com/21022311/204329665-32845aa6-b1af-4b9c-aaf5-219fd84065e9.png">

**Expected behavior**
Option is not visible

**Comment by Tantacrul** [comment]
@HemantAntony - I don't know if you are around, but we have a release blocker here you could potentially help with!

**Comment by HemantAntony** [comment]
Seems easy enough! I'll have a look into it

**Comment by HemantAntony** [comment]
@Tantacrul As promised: #14834 :)
