### ISSUE TITLE
[MU4 Issue] Bb Clarinet gets assigned Muse Sound Eb clarinet sound

### ISSUE THREAD

**Issue by Hasenn** [musescore/MuseScore#14818]
**Describe the bug**
When using Muse sounds, loading up a new score with a Bb clarinet assigns the Eb clarinet sound to it

**To Reproduce**
1. Activate Muse Sound from the *Playback Setup* menu in view
2. Make a new score with a Bb clarinet
3. View the mixer
4. Bb clarinet gets the wrong sound while there is a sound for it in muse sound

**Expected behavior**
Bb clarinet should get the Muse Sound Bb clarinet sound

**Screenshots**
![image](https://user-images.githubusercontent.com/20937891/204403713-1b8eeb26-a3e3-400a-be14-d0db905528b4.png)

**Platform information**
 - OS: Linux (ubuntu)

**Comment by cgpqci** [comment]
Probably a duplicate #13898

**Comment by Hasenn** [comment]
Yes, my bad. I'll close this Issue then
