### ISSUE TITLE
[MU4 Issue] One metronome click is played right after a score created when metronome is enabled

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#14810]
**Describe the bug**
Also catch this bug when importing GP scores. But the click is not heard when opening a big scores.

**Expected behavior**
No metronome click is played right after a score created

**Screenshots**

https://user-images.githubusercontent.com/101250347/204343324-c2a559fc-d7af-401f-95b0-c34cd62688f0.mp4

**Platform information**
 - OS: macOS

**Comment by cbjeukendrup** [comment]
I think this is related to #13826.

**Comment by abariska** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/13826
