### ISSUE TITLE
[MU4 Task] Plugin absence alert window to be implemented

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#14824]
**Task description**
When opening score with VST plugins which don't exist in the system user doesn't have any notifications. This task is about creating notification window (dialog) right after score opening.
Example from Logic Pro 
<img width="663" alt="abariska 2022-11-29 at 13 53 56" src="https://user-images.githubusercontent.com/101250347/204525042-9a46d0bb-0bed-43b3-8ba7-8b1d93fc59af.png">

To be discussed.
Related to https://github.com/musescore/MuseScore/issues/14823

**Comment by bkunda** [comment]
hi @abariska,
I know this issue is a little old now, but can you please confirm how this is related to [#14823? ](https://github.com/musescore/MuseScore/issues/14823). Are these two issues not duplicates?

**Comment by abariska** [comment]
hello,
these two different options of 'Missing plugins' feature, but both are accurately described and will be implemented in this task https://github.com/musescore/MuseScore/issues/16079
