### ISSUE TITLE
[MU4 Issue] Metronome audio does not remember being toggled on

### ISSUE THREAD

**Issue by mccoydtromb** [musescore/MuseScore#14836]
If the metronome has been toggled on, then the score closed, then opened again, the metronome still displays being on in the UI, but does not play back. You have to turn it off and on again to trigger the metronome sound.

**To Reproduce**
1. Open any score.
2. Make sure that metronome is toggled on. 
3. Close all scores
4. Open any score.
5. Play score.
6. Hear no metronome.
7. Turn metronome off, then on again.
8. Play score
9. Hear metronome.

**Expected behavior**
Metronome should play if it is toggled on in the UI

**Platform information**
 - OS: Windows 10

Using MuseSounds Metronome, but also does it with MS Basic

**Comment by mccoydtromb** [comment]
Possibly related to #14012, or has a similar cause.

**Comment by MarcSabatella** [comment]
Also possibly related to https://github.com/musescore/MuseScore/issues/14616

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/14839

Please reopen the issue if you can still reproduce the bug
