### ISSUE TITLE
Percussion Note Input: Previous Drum Sound Gets Carried to New Instrument

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#14896]
**Describe the bug**
This is hard to describe. Say you are inputting notes for the Bass drum and then move to snare by clicking on one of its measures... you will still hear the bass drum sound. See the video:

**Video**
https://user-images.githubusercontent.com/21022311/205347273-73c174ae-6b4f-477e-8055-ac6ced843475.mov

**Platform information**
Windows 10 / MacOS

I've logged as P0 because the problems can be really confusing. Sometimes you can't stop the previous percussion sound from happening over and over again.

**Comment by rgreen5** [comment]
Possible related: [Selecting an instrument in the Drum Input Palette effectively disables drum input from the on-screen Piano and/or MIDI keyboard](https://musescore.org/en/node/150621)?

**Comment by rgreen5** [comment]
Deleted.

**Comment by DmitryArefiev** [comment]
Fixed #14945
