### ISSUE TITLE
MuseScore 4.0 now crashes on startup-was ok before

### ISSUE THREAD

**Issue by macgarvin** [musescore/MuseScore#14907]
MuseScore 4.0 now crashes on startup, having worked until tonight.

Happens for both the original 'public beta' 4.0.0. and 'MuseScore 4.0.0.223360501 Nightly'. Musescore 3.0 unaffected.

This behaviour first seen when attempting to open after installing latest Muse Sounds updates ca 1 hour ago, but that doesn't mean that's the cause.

**To Reproduce**
Double click on either version of MuseScore 4, quits after a few seconds, after correctly showing the startup splash.

**Expected behavior**
Not to crash

**Platform information**

MacOS 13.0.1, Intel MacBookPro 15-inch 2017

**Comment by cbjeukendrup** [comment]
This has to do with an update to MuseSampler / Muse Sounds. Very soon, we will release a Release Candidate of MuseScore, that is able to work with the updated sampler, so that it doesn't crash.

**Comment by macgarvin** [comment]
Thx

**Comment by macgarvin** [comment]
Working again with build MuseScoreNightly-223370502-4.0_rc-d050fb0

(https://ftp.osuosl.org/pub/musescore-nightlies/macos/4x/nightly/MuseScoreNightly-223370502-4.0_rc-d050fb0.dmg)

**Comment by LionFJ** [comment]
Same thing happening to me still.

Windows 11. Where are the nightly builds?

**Comment by MarcSabatella** [comment]
You can access nightly builds from the Download / Software menu on musescore.org, but, at this point you should no longer be testing nightly builds - all testing should be focused on the release candidate.  See the announcement on the Discord server for further info - https://discord.com/channels/818804595450445834/1014583499497410580
