### ISSUE TITLE
[MU4 Issue]App crashes every time on opening this file.

### ISSUE THREAD

**Issue by RotoSound** [musescore/MuseScore#14918]
**Describe the bug**
MU4 (nighly build from yesterday) crashes every time that I try to open the file that I have attached below.

**To Reproduce**
1. Open the file "That_girl_issue"
2. Watch MU4 go down.

**Expected behavior**
Was expecting to se the score of "That_girl_issue".

**Platform information**
 - OS: Win10
[That_girl_issue.zip](https://github.com/musescore/MuseScore/files/10146868/That_girl_issue.zip)

**Comment by DmitryArefiev** [comment]
Fixed in #14920
