### ISSUE TITLE
[MU4 Issue] Audio export problems when double-byte characters are included in file names

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#14913]
**Describe the bug**
When exporting audio, if the file name contains double-byte characters, one of the following will occur:
- Export crashes when the progress bar reaches 80%.
  - When exporting a wav file, only the export process crashes, but when exporting a mp3 file, the entire software crashes.
- The export completes, but produces a garbled file.

**To Reproduce**
1. Create score
2. Export audio with double-byte file names

If you export with filename "あ.wav" for example, export process crashes.
If you export with filename "漢.wav", produces a garbled file ( "貍｢.wav" ).

**Platform information**
 - OS: Windows 11, RC1

**Additional context**
may be related to #14765

**Comment by cbjeukendrup** [comment]
Probably also related to https://github.com/musescore/MuseScore/issues/14173, but maybe not entirely a duplicate because this issue also involves a crash

**Comment by cbjeukendrup** [comment]
@bakajikara Does the crash happen _only_ when the filename contains such characters? Or does it also sometimes crash when the filename contains only single-byte characters?

**Comment by bakajikara** [comment]
@cbjeukendrup Yes, the crash occur only when the filename contain double-byte characters. Exporting the same score with a file name that contains only alphabetic characters will end successfully.
Whether a crash occurs or a garbled file is generated depends entirely on the filename.

**Comment by Tantacrul** [comment]
Can you please try this build and report back?

https://github.com/musescore/MuseScore/suites/9677220380/artifacts/463337181
