### ISSUE TITLE
[MU4 Task/Issue]

### ISSUE THREAD

**Issue by BetonBrut69** [musescore/MuseScore#14923]
I've been using MU4 for several weeks, and I want to bring these problems up.

1. Please bring these back!

-Text vertical distance settings
-Font preview on selection
-Options(bold, italic, etc…) for the text of the text line
-“Screenshot” functionality (I can’t find it..or is it gone??)
-Function to copy SmuFL code from the master palette
-Start hook/End hook function (I can’t set a start hook on regular lines)
-Cannot move beams to the desired position sometimes (if they are extended across the measures

MuseSounds

Viola’s “professional” range doesn’t play in the playback
Violoncello(Solo) is missing about 50% of the note that they were supposed to play

**Comment by MarcSabatella** [comment]
Thanks for your comments!  Many of these have already been reported, so it is best in the future to create separate issues for separate problems, so if some are found to be duplicates or get fixed, they can be closed.  You can also use the search facility here to see if someone has already reported an issue before opening a new one.

When you open new issues for these, please be clear for each exactly what you mean.  The image capture tool is indeed currently not implemented, and is expected to be redesigned/reimplemented in a future update, no need to report that.  Similarly for the hooks and text formatting on lines.  For the others, please open new issues and describe each issue in more detail.

**Comment by oktophonie** [comment]
As Marc says, best to file these as separate issues. Thank you!

I have created the beam one myself, here: https://github.com/musescore/MuseScore/issues/14944
The start hook/end hook one already exists here: https://github.com/musescore/MuseScore/issues/14209
And the text formatting options for text lines here: https://github.com/musescore/MuseScore/issues/14238
