### ISSUE TITLE
[MU4 Issue] MU4 doesn't run on macOS Ventura

### ISSUE THREAD

**Issue by BetonBrut69** [musescore/MuseScore#14926]
**Describe the bug**
After I updated my MacBook to macOS Ventura, Musescore 4 refuses to open up.

**To Reproduce**
1. Update your mac to macOS Ventura
2. Click on MU4
3. (just a loading pop-up and doesn't open)

**Expected behavior**
The program is supposed to open

 - OS: macOS Ventura

**Comment by MarcSabatella** [comment]
Are you running the latest RC release as per the announcement in Discord?

**Comment by Jojo-Schmitz** [comment]
As per https://discord.com/channels/818804595450445834/818804809784229898/1048956549432877117 a reinstalle brought it back to life, right?

**Comment by BetonBrut69** [comment]
Yes, I was using the latest RC (before updating), and reinstallation brought it back to life, which is really bizarre..
