### ISSUE TITLE
[MU4 Issue] Double/Halve Selected Duration commands not actioned during note input

### ISSUE THREAD

**Issue by Phil-TA** [musescore/MuseScore#14927]
**Describe the bug**
MuseScore 3 provides two commands for adjusting the duration of a selected note or chord, namely "Double Duration" and "Halve Duration". These work both "on the fly" during note input, and when a note/chord is selected when note input is inactive. With MuseScore 4, these commands (now known as "Double Selected Duration" and "Halve Selected Duration") are only effective when note input is inactive. They do nothing when note input is active (regardless of note input mode).

**To Reproduce**
1. Create a new, blank score.
2. Enter a quarter note in the first bar (note input is now active).
3. Hit the keyboard shortcut for "Double Selected Duration" (in my case I have key "w" assigned for this).

**Expected behavior**
The selected quarter note is replaced "on the fly" (i.e. without any need for further key presses or mouse clicks) with a half-note of the same pitch.

**Actual behavior**
Nothing happens with the selected note (but the Half note icon in the menu is now highlighted).

**Screenshots**
N/A

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223330401, revision: github-musescore-musescore-3277328

**Additional context**
Perhaps this feature been intentionally removed from MuseScore 4?

**Comment by MarcSabatella** [comment]
The behavior of Q and W has changed, so these now work more like the other duration command (and accidental commands, and voice commands, etc) - they "set the stage" for the *next* note to be entered.

The commands Shift+Q and Shift+W continue to operate on the selected note.

**Comment by Phil-TA** [comment]
Thanks Mark. Shift+Q and Shift+W do operate on the selected note, but don't do what Q and W used to to. For example, Shift+W changes the quarter note to a dotted quarter note, and Shift+Q changes the quarter note to a dotted eighth note. Perhaps this is a bug?

**Comment by MarcSabatella** [comment]
No, that is by design, and it is how those commands have always worked (in MuseScore 3 as well).  Indeed, they operate in a more fine manner than Q/W, first adding a dot, then increasing to the next duration.  So it takes two presses of Shift+W to equal one of W.

**Comment by Phil-TA** [comment]
Ah, thanks Mark, I didn't realise that! This issue can be closed then - thanks for your help.

**Comment by Phil-TA** [comment]
Closed - not a bug.
