### ISSUE TITLE
[MU4 Issue] Unable to suppress Continue Text for pedal lines

### ISSUE THREAD

**Issue by Phil-TA** [musescore/MuseScore#14928]
**Describe the bug**
Musescore 4 provides features for adding and removing text to and from lines (both at the beginning of a line, and at the continuation point where a line continues through a system break).  However, these features are not available for pedal lines.

**To Reproduce**
1. Create a new, blank score.
2. Arrange two systems of a few bars each.
3. In the last bar of the first system, add a Pedal line.
4. Extend the pedal line to continue into the first bar of the second system. The system now adds "(Ped)" continuation text to the line.
5. Select the Pedal line and open the Properties panel.

**Expected behavior**
The Properties panel should have a "Text" section providing access to features which would allow the selected pedal line's continuation text to be changed or removed if required.

**Actual behavior**
The Properties panel has no "Text" features available for editing text associated with the Pedal line. The continuation "(Ped)" text cannot therefore be removed.

**Screenshots**
N/A

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223330401, revision: github-musescore-musescore-3277328

**Additional context**
Perhaps this feature been intentionally removed from MuseScore 4?

**Comment by oktophonie** [comment]
Pedal lines should have the same text settings as, for example, cresc/dim or gradual tempo changes:
![image](https://user-images.githubusercontent.com/20604032/206124521-de79e48b-59a3-4a05-a14c-e0e568b61262.png)
This enables not only suppressing the continuation but also other styles of pedal indication, such as just the 'P' symbol, or 'Ped' in normal text, etc. (The 'Show pedal symbol' checkbox will likely then become redundant.)
