### ISSUE TITLE
[MU4 Issue] [RC] Pdf exports as a long single page while in continous view

### ISSUE THREAD

**Issue by Fristover** [musescore/MuseScore#14929]
**Describe the bug**
Pdf export makes a single long page if continuous view is used while exporting

**To Reproduce**
1. Go to any score
2. Click on continuous view, either vertical or horizontal
3. Export as pdf

**Expected behavior**
Pdf export should export like page view regardless of the viewing mode

**Screenshots**
![image](https://user-images.githubusercontent.com/68985619/205503276-2aed258c-6d88-44e0-8eb5-08c049406ff1.png)

**Platform information**
 - OS: Windows 11

**Additional context**
Happens with both vertical and horizontal modes, testing on the latest RC build shared on discord.

**Comment by Tantacrul** [comment]
Hahaha! @oktophonie, what do you think?

**Comment by Fristover** [comment]
I now think this should actually be a feature 😅, been using these exports for some projects and it's pretty good, would be a shame to lose it haha.

**Comment by DmitryArefiev** [comment]
Fixed in #16639

**Comment by DmitryArefiev** [comment]
Retested on Win10
