### ISSUE TITLE
[MU4 Issue] [GP] Note "B" pitch is 1 octave higher than written when imported a score with 'Keep fingering' capo

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#14937]
**To Reproduce**
1. Open the score 
[Guitar tuning and capo.gp.zip](https://github.com/musescore/MuseScore/files/10676825/Guitar.tuning.and.capo.gp.zip)
2. Check B notes
3. Pay attention to the its pitch

**Expected behavior**
All notes have corresponding pitch (as written)

**Screenshots**

https://user-images.githubusercontent.com/101250347/205580504-2d51276d-850f-4cbe-a72b-7f4365dbf90b.mp4

**Platform information**
 - OS: macOS

**Additional context**
When applied 'Adjust fingering" capo the issue doesn't reproduce

**Comment by bkunda** [comment]
I believe this has been resolved following the new capo feature implementation (I can no longer reproduce this issue in the attached file or in a new score). 
Happy to re-open if the problem can be shown to persist.
