### ISSUE TITLE
[MU4 Issue] Wrong (?) part labeling for section strings

### ISSUE THREAD

**Issue by Fristover** [musescore/MuseScore#14930]
**Describe the bug**
Section strings get the following part names:
- Violins (section) 1, 2 or whatever
- Violas (section)
- Violoncellos (section)
- Contrabasses (section)

**To Reproduce**
1. Create any score with string sections
2. Click on Parts
3. See error (?)

**Expected behavior**
Part names should be either Violin 1 or Violins 1 (or whatever the instrument is)

**Screenshots**
![image](https://user-images.githubusercontent.com/68985619/205503574-187d7b08-b982-4fc8-89a4-4ac3366d427a.png)

**Platform information**
 - OS: Windows 11

**Additional context**
I asked many string players before posting this and everyone agreed that the labeling is wrong and should be like the expected behavior section, a common comment was that the letter "s" already implies there's a section instead of a solo instrument (which they commonly see labeled as a "solo [instrument]" part in orchestral stuff)

**Comment by MarcSabatella** [comment]
My assumption is that the "section" is intended to be there only for the instrument list, to help clarify to people the difference between adding Violin vs Violins.  Adding the wrong one was an extremely common error in previous versions of MuseScore.  But indeed, even if it appears that way in the instrument list, it shouldn't in the part.

**Comment by oktophonie** [comment]
Yes, it looks like the trackName is being used to name the part as opposed to the longName. This affects some other instruments too, like all the (tablature) variants.

**Comment by Fristover** [comment]
If this is the case then piccolo is also affected, adding "in C" to the part name:

![image](https://user-images.githubusercontent.com/68985619/205507481-3ab6d88c-9f12-4a38-8847-c71757cbc67b.png)

**Comment by Jojo-Schmitz** [comment]
See https://github.com/musescore/MuseScore/blob/5200cd0d3c128e3e422abbdfbe3b5737b260037e/src/engraving/libmscore/part.cpp#L532-L535

**Comment by cbjeukendrup** [comment]
It looks like we're doing exactly the same as in MS3. The only thing that did change is the contents of the trackNames themselves. So I'll change the behaviour so that we now use long names instead of track names.
