### ISSUE TITLE
[MU4 Issue] MuseScore 4 always crashes when trying to start the application

### ISSUE THREAD

**Issue by philipplndwhr** [musescore/MuseScore#14932]
**Describe the bug**
When trying to start the application, MuseScore immediately crashes after showing the launching screen.

**To Reproduce**
1. Be on my machine
2. Start MuseScore4, latest version (I reinstalled through the MuseHub)
3. Musescore crashes
4. Optionally reinstall both the MuseHub and Musescore
5. They still crash every time, even after restarting my machine

**Expected behavior**
MuseScore should start and show me the main menu instead of crashing.

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/109522890/205508408-1e1e182d-a5e3-40db-b06e-443c3595f3d2.png">

**Platform information**
 - OS: macOS 12.5.1; I did not update my system since installing the beta a day after its original public launch.

**Additional context**
Before closing musecore purposefully the last time (and never being able to open it again), I encountered a bug which makes the playback unable to produce any sounds at all after closing the laptop with MuseScore open. I had headphones plugged in and closed MuseScore with the headphones still in my machine.

**Comment by MarcSabatella** [comment]
Yes, after the most recent Muse Hub update, you neither either the latest nightly build, or better, the release candidate

**Comment by philipplndwhr** [comment]
@MarcSabatella In fact, after updating MuseScore today, the issue resolved itself without further ado. However, I am not able to decide if I wish to install a nightly build or the release candidate. How would I do that?

**Comment by MarcSabatella** [comment]
Yes, the Muse Hub was apparently updated to install the RC, so you should be good to go.  The RC is all we should be testing between now and the official release.

**Comment by cbjeukendrup** [comment]
I'll close this, since it's fixed in the RC (and for me in the latest nightly builds too). If it happens again in the RC, please let us know.
