### ISSUE TITLE
[MU4 Issue] Playhead should only be placed OnRelease (it currently places on MouseDown & OnRelease)

### ISSUE THREAD

**Issue by egonelbre** [musescore/MuseScore#14949]
**Describe the bug**

It seems that mouse down and selection changes both move the playback head movement. I would expect this to only happen with mouse-up.

**To Reproduce**

1. Open a piece of music
2. Ensure nothing is selected
3. Press play
4. Press and hold on a location to move the playback (notice that playhead moves)
5. Wait
6. Release (notice that the playhead moves again)

**Expected behavior**

I would expect the playback head to only move when releasing the mouse button.

**Screenshots**

The following video contains only two mouse presses. One to start playback and then one to move the playhead.

https://user-images.githubusercontent.com/192964/205659252-70fe5951-e6e1-4ad5-93fe-0341d4683e32.mp4

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223362132, revision: github-musescore-musescore-d050fb0

**Comment by Tantacrul** [comment]
Nice catch!

**Comment by RobFog** [comment]
Is this a regression from MuseScore 3?

**Comment by egonelbre** [comment]
I wasn't able to repro it in MS3.

**Comment by DmitryArefiev** [comment]
> Expected behavior
> I would expect the playback head to only move when releasing the mouse button.

The expected result doesn't correspond with **MS3** behavior. In **MS3**, Playhead is placed on MouseDown.

The bug in MS4 (comparing with MS3) is **playhead currently places twice**: on **MouseDown** & **OnRelease**. 
In **MS3**, Playhead is placed on **MouseDown only**.

@Tantacrul Please approve if we want to change the behavior comparing with **MS3**

(now #15161 fixes **playhead currently places twice** and doesn't change the MS3 behavior)
