### ISSUE TITLE
Limitations with the copyright functionality in MU4

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#14947]
As I regularly write arrangements for copyrighted songs,
most of them having longer multi-line copyrights,
I want to mention three issues with the copyright functionality 
in Muse Score that still remain in version 4. 
 
1. By design it is not possible to change font and size
of a copyright text without changing
other footer or header text, 
like page numbering, as well.

2. The field to enter the copyright
shows only one line even though
many if not most copyrights
consist of several lines.  

3. There is no footer tag
to insert a copyright 
only on page number 1
which is not the same as "first page",
if there is a tilte-page on page number 0.

Because of these issues I never actually use the copyright functionality
of Muse Score but rather create the copyright as a text frame unless
I'm writing a score which will be delivered with the individual parts.

I the future I would love to see further innovation on the copyright functionality in Muse Score...

From my user-perspective it could look like this:
Entering or editing the copyright happens inside the score via double click on "copyright"
and feels pretty much like editing a text frame. There is a copyright tab inside the style page,
which let's you specify text-font and size and on which pages the copyright shall appear.

**Comment by MarcSabatella** [comment]
These would be good enhancements indeed.  Meanwhile, though, there are better workarounds than resorting to text frames - you can use "font" tags in the footer to change size, you can paste multi-line text from elsewhere, and you add title pages separately.  Note also, the copyright *itself* is always just the one line; the rest is just usage info should probably be entered into the footer separately.   For more help with this, feel free to ask on the support forum.

**Comment by AntonioBL** [comment]
Regarding item 1. you can somehow do something with a semi-hidden feature of MuseScore: you can use some sort of html tags to edit individual portions of a single text in headers and footers, see for example this old comment [here](https://musescore.org/en/node/39606#comment-173546) (those tags still work in MuseScore 4, but not all of Qt rich text tags are supported)

**Comment by Tantacrul** [comment]
@oktophonie

**Comment by oktophonie** [comment]
It's certainly often desirable to have a copyright indication only on the first page (or just a different footer on p1 than on subsequent pages).

There is the ability to reference the copyright string from the score metadata and show it only on the first page with the $C tag. This can work, but poses a few difficulties (challenges with formatting etc), and also doesn't solve the problem of what do to if you want that on the first page but then something else on subsequent pages. (I encountered this recently: I needed a catalogue number centered on all pages except the first, where the catalogue number would appear right-justified, and the copyright text left-justified.)

The easiest way to do this would be by turning off the existing 'Show on first page' option and to manually insert a custom footer on that page.

We can do this with a text frame but that's problematic for a few reasons, including:
- Text frames are hese are inserted in the flow of the music, i.e. after the last system on the page, so can move around if the layout changes;  they also then appear in that same place in parts, where they will almost certainly interfere with the layout
- They interfere with vertical justification
- They don't appear at the actual footer position, but are padded against it, so won't be consistent with footers elsewhere

I'd propose implementing a new 'Footer' item, which is a special type of text frame which:
- can be added anywhere in the score (for a copyright notice this would be at the very beginning)
- will show at the bottom of the page on which that point occurs. It will appear at footer position if there is no footer present, or just above it ('bottom justified') if there is one. (Perhaps we make it configurable whether it just replaces any footer that is present on that page; that allows you to create copyright lines on subsequent pages, which may be useful if you are creating a compilation of songs/pieces)
- remains attached to that point in the score, and appears in parts relative to that same point
- can obviously have default space above and other style settings
- can use the same tags as the existing Header/Footer do, so one can reference metadata

Note that this functionality can then also be used to create **footnotes**, though a proper implementation of such a feature (multiple footnotes on one page, specifying whether a footnote applies to specific instruments or to the whole system, etc) would require extra work.

Just a thought!

**Comment by oMrSmith** [comment]
> I'd propose implementing a new 'Footer' item, which is a special type of text frame which:

That sounds really good, I also like your idea of designing the footer as special type of text frame.

**Comment by oMrSmith** [comment]
> Regarding item 1, as Marc said, you can somehow do something with a semi-hidden feature of MuseScore: you can use some sort of html tags to edit individual portions of a single text in headers and footers, see for example this old comment [here](https://musescore.org/en/node/39606#comment-173546) (those tags still work in MuseScore 4, but not all of Qt rich text tags are supported)

Thanks for the info! It works and is fairly simply.

**Comment by iainhallam** [comment]
> I'd propose implementing a new 'Footer' item, which is a special type of text frame which:

A proper ad-hoc footer frame would be awesome - I often need footnotes for critical editions, and being able to work around the current repeated footer's limitations for copyright would be great. I also like the idea of them stacking automatically in score order, followed by the repeating footer; that would make footnotes really easy to format.

**Comment by marcstober** [comment]
Hi everyone, I was pointed here from https://musescore.org/en/node/286521. I was a little confused as that was a feature request for foot**notes** including a number or symbol (possibly even auto-numbered) as may be desired in more "academic" works, and the title of this issue and the request about copyright text above aren't exactly the same thing as the suggestion on the old tracker. Although, it seems to me that @oMrSmith's requirements could be easily satisfied with such footnote functionality (plus probably needing to hide the number/symbol). Should this issue be used to track the footnote functionality (that the page on the old tracker and @iainhallam and I want) and the title perhaps changed, or is this copyright text feature something that should be separate from footnotes?

**Comment by oktophonie** [comment]
Closing this one as it's mostly done as of 4.4; the remainder I've tried to capture in https://github.com/musescore/MuseScore/issues/23989; the footnotes request we can track as https://github.com/musescore/MuseScore/issues/23921.
