### ISSUE TITLE
[MU4 Issue] Muse Sounds: Arpeggio also affects the next chord

### ISSUE THREAD

**Issue by LuisLiszt** [musescore/MuseScore#14941]
**Describe the bug**
See video. An arpeggio also plays the next chord as an arpeggio, even if it's not the same measure.

**To Reproduce**
1. Place multiple chords.
2. Place arppegio.
3. Play

**Expected behavior**
Arpeggio should only play the assigned chord, not the next one.

**Screenshots**

https://user-images.githubusercontent.com/55204261/205606322-02bf02fd-a911-4fb2-9268-2acf5bd573d6.mp4

**Platform information**
 - OS: Windows 11

**Comment by krtschil** [comment]
Seems to be correlated with Muse Sounds. If set to MS Basic the Arpeggio is played correctly.

**Comment by LuisLiszt** [comment]
@krtschil Yes, I can confirm that! Thanks for adding the information

**Comment by LuisLiszt** [comment]
Issue still persists and is stuck in MU4.0 Release which isnt worked on anymore...

**Comment by cbjeukendrup** [comment]
> Issue still persists and is stuck in MU4.0 Release which isnt worked on anymore...

Don't worry, it's also in the `Muse Sounds` project, which is where the Muse Sounds developers look.

**Comment by zacjansheski** [comment]
Combining this with https://github.com/musescore/MuseScore/issues/16917
