### ISSUE TITLE
[MU4 Issue] Gradual tempo change text lines (e.g. rit.,accel.) can't continue next measure on 'Shift' + '->'

### ISSUE THREAD

**Issue by Haru00007** [musescore/MuseScore#14943]
**Describe the bug**
Gradual tempo change text lines (e.g. rit., accel.) can't continue next measure on 'Shift' + '->'.
So, I have to continue the next measure on the mouse left click, but the designs aren't beautiful.

**To Reproduce**
1. Create a new score
2. Add any gradual tempo changes to text lines(rit., accel.)
3. try to continue the next measure
4. I can't do that even if there were notes

**Video**

[2022-12-05 19-31-40.zip](https://github.com/musescore/MuseScore/files/10153356/2022-12-05.19-31-40.zip)

**Platform information**
 - OS: WIndows 10 22H2 Musescore: latest RC Edition

**Comment by MarcSabatella** [comment]
I can confirm this using the RC.  Shift+Left/Right work *within* a measure, but you can't extend beyond the original end measure.

However, the solution is to simply select the measures you wish to cover *before* adding the line.  That's the correct way to add any line - first select a range, then click the palette icon.

**Comment by Tantacrul** [comment]
I think this deserves to be a separate bug, since the shortcut just doesn't work at all on tempo lines, whereas https://github.com/musescore/MuseScore/issues/14952 deals with a more specific problem regarding moving between systems.
