### ISSUE TITLE
[MU4 Issue] Falls play as chromatic instead of portamento (MS Basic)

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#14958]
**Describe the bug**
In the RC, falls play as chromatic instead of portamento when using MS Basic

**To Reproduce**
1. Create a score for trumpet
2. Add a whole note
3. Add a fall (from arpeggios & glissandi palette)
4. Play
5. Hear error: fall is chromatic

**Expected behavior**
Fall should use portamento.  Similarly for the other similar elements (doit, etc)

**Screenshots**

https://user-images.githubusercontent.com/1799936/205691346-b59e0877-afc4-4968-89f3-3a3d9f59dc93.mp4

**Platform information**
 - OS: Linux

**Additional context**
This was working well up until shortly before the RC.  But I can't say for sure when it broke.

**Comment by Tantacrul** [comment]
Putting in Release, since this was working correctly a few weeks ago.
