### ISSUE TITLE
[MU4 Issue] Instruments dialog - search for "trumpet" defaults to C

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#14957]
**Describe the bug**
If you search for "trumpet" in the instruments dialog, the default choice offered is C, but it should be Bb.

**To Reproduce**
1. Create a new score
2. Under "Choose instruments", type "trumpet" into the search box
3. See error: the default choice offered is C, and you need to change to Bb manually via the dropdown

**Expected behavior**
The default should be Bb, with C available via the dropdown

**Screenshots**
![Screenshot 2022-12-05 9 16 08 AM](https://user-images.githubusercontent.com/1799936/205686919-f6c26e96-95bc-43d3-b5a5-90e4a15b0c78.png)

**Platform information**
 - OS: Linux

**Additional context**
It's not that way for cornet, horn, clarinet, or other instruments offered in a variety of transpositions - they all default to the most common variant.  I do recognize that in orchestral music, C trumpet might be about as common as Bb, but it's not common at all outside that world.  And Bb trumpet is the one listed if, instead of searching, you select the Brass family in the Common genre.  So it makes no sense that C would be offered as the default choice in the search.

This is not a recent regression; it's been this way for as long as that drop-down has been a thing, I believe.  MU3 didn't have this; it just listed all matching instruments in one long list.

**Comment by Tantacrul** [comment]
@oktophonie

**Comment by oktophonie** [comment]
Seems fair enough to have Bb as the default, especially as it's the only one offered in 'Common'.
