### ISSUE TITLE
[MU4 Issue] Playback sound is high-pitch and choppy when device sample rate is set to 192000Hz

### ISSUE THREAD

**Issue by SilverGreen93** [musescore/MuseScore#14965]
**Describe the bug**
Increasing the sample rate of the audio device in Windows Sound settings to 192000Hz makes the Musescore sound playback be a high-pitched choppy sound.

**To Reproduce**
1. Go to Windows sound settings.
2. Change the sample rate for the default audio device from 44100Hz to maximum, in my case 192000Hz
3. Open any score in Musescore.
4. Click play.

**Expected behavior**
The score should play normally. Sounds should be the right pitch.

**Additional notes**
This happens regardless of 16bit or 24bit depth.
This happens only on 192000Hz. On any lower settings such as 96000Hz it plays fine.
Enabling or disabling audio enhancements does not change anything.

**Platform information**
 - Musescore master-5200cd0
 - OS: Windows 11 22H2
 - Device used: High Definition Audio Device (built-in on the MB) HDAUDIO\FUNC_01&VEN_10EC&DEV_0887&SUBSYS_1462FA72
 - Driver version 10.0.22621.608

**Comment by Tantacrul** [comment]
Yes, at present, MuseScore only supports a max of 96,000Hz. This is largely down to the natural limitations of the Fluid synth. I'm going to close this issue, since it is not something we are intending on tackling any time soon.

**Comment by SilverGreen93** [comment]
> Yes, at present, MuseScore only supports a max of 96,000Hz. This is largely down to the current limitations of the Fluid synth we are using. I'm going to close this issue, since it is not something we are intending on tackling any time soon.
> 
> Thanks!

Thanks for the info! Could we add a warning or something on startup to inform the user of their settings?

**Comment by milnak** [comment]
On my machine, I found that anything over 16 bit, 48000 Hz caused choppy sound.
