### ISSUE TITLE
[MU4 Issue] Entering accented letters on a Mac keyboard results in unintended extra characters.

### ISSUE THREAD

**Issue by TheMattSykes** [musescore/MuseScore#14964]
**Describe the bug**
On any text field (that I've tested) if you press and hold a character such as `e` (then press `2`/click the accent) to get the accented variant `é`, the text field will register as the key being held down and repeat the character as well as giving the accent context menu. So instead of the intended result of something like `café` you get `cafeeeeee2é`.

**To Reproduce**
1. Go to an existing or newly created score.
2. Double click to edit the title.
3. Press and hold a letter on the keyboard that has an accented variant such as e or a.

**Expected behavior**
The character accent menu should appear when you press and hold a letter that has them available, no extra characters should be entered until an accent is selected or another letter is pressed.

**Screenshots**
![Screenshot 2022-12-05 at 19 33 56](https://user-images.githubusercontent.com/34308307/205726596-084565e0-98e2-4960-9a52-0c1a5359778b.png)

**Platform information**
 - OS: macOS 13.0
 - Version: 4.0.0.223390501 Latest Nightly as of 5th Dec 2022 19:30 UTC. Also occurs on latest Beta.

**Comment by cbjeukendrup** [comment]
Also occurs in MuseScore 3.6.2 and in Dorico. Happens not only in "in-score" text fields, but also in "standard" text fields in dialogs. It's a Qt issue: see https://bugreports.qt.io/browse/QTBUG-71394. It is fixed in Qt 6.2, but unfortunately I don't think we are able to switch to Qt 6 soon. I also think we don't have much chance to find a workaround using Qt 5.15.

**Comment by Tantacrul** [comment]
Since we can't take action on this - and since we are planning to switch to a new version of Qt soon anyway, we'll have to close this for now.
