### ISSUE TITLE
[MU4 Issue] System dividers obscure other elements in vertical continuous view.mscz

### ISSUE THREAD

**Issue by SamYeh** [musescore/MuseScore#14966]
**Describe the bug**
In vertical continuous view, system dividers may obscure other elements above or below systems.

**To Reproduce**
See the score shown below ([download link](https://musescore.com/user/55169571/scores/9126987)). Note: The bug does not occur when viewing the score on musescore.org.

**Expected behavior**
System dividers should not obscure other elements.

**Screenshots**
![image](https://user-images.githubusercontent.com/10248807/205728069-1b2910c2-d905-4ae4-8a16-28a276f479f8.png)

**Platform information**
 - OS: Windows 11
 - Build: MuseScore RC1

**Comment by oktophonie** [comment]
The system dividers are quite 'dumb' in terms of their placement, and ignore/are ignored by autoplace, so this needs to be overhauled.

The marks on the left should probably have options to be placed relative to the left margin (the current default), or the system barline (which I'm more used to), and how they are to be justified; and space should be made between systems such that they do not collide with any items above and below. We will revisit this in 4.x.
