### ISSUE TITLE
[MU4 Task] Piano Roll

### ISSUE THREAD

**Issue by DocBobB** [musescore/MuseScore#14967]
Piano roll and editing midi
Musescore 3 has a piano roll and I can edit e.g. velocity. This feature is missing entirely in Musescore 4 as far as I can tell.

**Comment by MarcSabatella** [comment]
Yes, this - or some other replacement for its functionality - is one of the things being worked on for a future update.

**Comment by Tantacrul** [comment]
Yes. I'm going to close this issue because it's already on our roadmap. In particular, a method of easily editing Velocity is going to come earlier than a piano roll.
