### ISSUE TITLE
[MU4 Issue] Exporting score and parts combined cuts off music from parts

### ISSUE THREAD

**Issue by pgrimes2002** [musescore/MuseScore#14974]
**Describe the bug**
When exporting combined score and parts, the right margin on the part becomes cut off and clips the music.

**To Reproduce**
1. file -> export
2. Check "all parts combined on one file"
3. export
4. See error on pdf

**Expected behavior**
Sheet music should look like when parts are exported to separate files and in the preview shown.

**Screenshots**
Musescore preview
<img width="1438" alt="Screenshot 2022-12-06 at 12 26 34 AM" src="https://user-images.githubusercontent.com/103294056/205824072-d9c2d514-c957-4847-8e96-af08105ba26c.png">

Exported on a combined pdf file (exports incorrectly)
<img width="1440" alt="Screenshot 2022-12-06 at 12 25 43 AM" src="https://user-images.githubusercontent.com/103294056/205824143-bf6820fe-3650-47ab-83a1-0b1cf355e94f.png">

Exported on a separate file (exports correctly)
<img width="1439" alt="Screenshot 2022-12-06 at 12 26 09 AM" src="https://user-images.githubusercontent.com/103294056/205824215-a63882d3-d547-41af-bbfb-aa7f8ecd0719.png">

**Platform information**
 - OS: macOS

**Comment by cbjeukendrup** [comment]
I assume that this is because the parts have a different page size than the score, is that right?

**Comment by Tantacrul** [comment]
@oktophonie for advice on triage.

**Comment by oktophonie** [comment]
Outside my field really; is this not another manifestation of https://github.com/musescore/MuseScore/issues/14666 ?

**Comment by pgrimes2002** [comment]
> 

Yes, the page size of the parts is different from the score.

**Comment by MarcSabatella** [comment]
@oktophonie I suspect it's not related to that other issue since it is about very slight discrepancies (fractions of a millimeter).  I think this issue is about cases where you deliberately have very different page sizes for score and parts - like score A3, parts A4.  It would be good if the score demonstrating the problem were attached.

FWIW, previous versions of MuseScore had a similar problem but it was fixed a few years ago.

**Comment by DmitryArefiev** [comment]
Fixed in #15025
