### ISSUE TITLE
[MU4 Issue] Option to disable Backup feature is missing in MS4

### ISSUE THREAD

**Issue by LoveJessyChen** [musescore/MuseScore#14973]
**Bug:**

Option to disable Backup feature (like in MS3) is missing in MS4

![2022-12-05_22](https://user-images.githubusercontent.com/48858531/205800841-2f175673-c62b-4627-a429-c1c871a957b7.png)

Also [see comment](https://github.com/musescore/MuseScore/issues/14973#issuecomment-2196559919)

**Platform information**
macOS 13.0.1

**Additional content**
#23386

**Comment by Tantacrul** [comment]
This is an MS3.6 issue, right?

**Comment by LoveJessyChen** [comment]
> This is an MS3.6 issue, right?

No ，I want to add this 3.6's feature to version of 4.0

**Comment by Tantacrul** [comment]
I have unfortunately very little idea what it is you are suggesting actually - although I suspect some other community folk may know better than I. @MarcSabatella - any idea what this is? I'm sure it's something we discussed 2 years ago or so but it has escaped me now

**Comment by MarcSabatella** [comment]
@Tantacrul MuseScore has always made an automatic backup copy of your score when you first save it during a session.  it also autosaves a separate copy every few minutes to use in recovering from a crash.  At some point in the last few years, someone decided to add options to allow the user to specify where these backups are stored, and also, to disable the automatic backups completely.

Frankly, I'm not sure what the purpose of either of those options would be, really - seems like asking for trouble for me.  But a few users seemed to think it would help them somehow.  And this option is not present in MU4.  Backups are always made, and their location is not changeable.

**Comment by Tantacrul** [comment]
@LoveJessyChen - can I ask why you would want this feature?

**Comment by LoveJessyChen** [comment]
This is my reason of this features: When I move original mscz files to other new folder, the Backup FILE WILL REMAIN in old folder . This is meaningless and uses my memory of the disks.

**Comment by Tantacrul** [comment]
Yeah, I'm trying to figure out repro steps and can't get to any issue. For sure if you move a score while MS is open, the the autosave naturally stays put. I don't get it.

**Comment by DmitryArefiev** [comment]
> However, I do think we should provide an option to disable the backup feature, for people who care about that tiny bit of wasted disk space. Also, especially on macOS, you might argue that the backup feature is somewhat redundant since you already have Time Machine, the system wide backup solution. (Of course, I know that this works quite differently from MuseScore's backup feature, but still.) **Therefore I think we should provide the option to disable backups, just in Preferences > Advanced, like in MS 3.6.2.**

@bkunda I agree with Casper, some users may want to disable backups and not create **.mscbackup** hidden folder on their disk drives. We can easily put the main option (generateBackup checkbox) to Preferences>Advanced (like in MS3.6.2):
![205800841-2f175673-c62b-4627-a429-c1c871a957b7](https://github.com/musescore/MuseScore/assets/90187801/006867df-b604-41be-8b70-b60a19bd7a8b)

![Capture](https://github.com/musescore/MuseScore/assets/90187801/211a88b5-7270-4db3-be4d-572b149078bf)

And actually, it's not a feature request it's a bug (missing MS3 functionality)

**Comment by DmitryArefiev** [comment]
> To set .mscbackup to another directory

This is logged separately (#23386)

**Comment by LoveJessyChen** [comment]
When will this issue solve? I have waited it 3 years.

**Comment by cbjeukendrup** [comment]
Since this is a relatively niche and uncommon request, we cannot give it a very high priority of course. Currently there is no concrete schedule for this issue. 
Contributors are welcome to work on this, since it is unlikely that the internal team will work on this within the next few months.

**Comment by LoveJessyChen** [comment]
OK I will not MS4 till ms5 released.

**Comment by cbjeukendrup** [comment]
A new version number isn't going to change much about this issue. However, this Pull Request, made by a contributor, is: https://github.com/musescore/MuseScore/pull/25178
