### ISSUE TITLE
[MU4 Issue] 'Send to YouTube' function not working for files created using Musescore 4 Beta

### ISSUE THREAD

**Issue by moysey1987** [musescore/MuseScore#14971]
**Describe the bug**
After uploading files created in MuseScore 4 Beta to musescore.com, the 'send to youtube' feature does not generate a video download link.

**To Reproduce**
1. Create and save any file in MuseScore 4 Beta
2. Upload to musescore.com
3. Select 'Send to YouTube'
4. Select 'Create video'
5. Video download link is never received via email (as is usually the case with the existing MuseScore 3 workflow)

**Expected behavior**
A video download link is usually sent via email.

**Screenshots**
Not applicable.

**Platform information**
 - OS: MacOS Monterey 12.6

**Additional context**
Not applicable

**Comment by bkunda** [comment]
I've tested this twice in the last day or so using MuseScore 4.1 and video files now seem to be processed again (I also received email notifications about it). 

I understand there is still some missing functionality (i.e. the virtual piano keyboard is not being exported to YouTube). I will raise this as a separate issue. 

For now, seeing how old this issue now is and that it seems the problem has been resolved, I'll close this issue. Of course I'll readily see it re-opened if the problem persists for others.
