### ISSUE TITLE
[MU4 Task]Add a feature to disable backup file.

### ISSUE THREAD

**Issue by LoveJessyChen** [musescore/MuseScore#14985]
In MS4，How To set .mscbackup to another directory or disable this backup？

**Comment by oktophonie** [comment]
Closing as effectively duplicate of https://github.com/musescore/MuseScore/issues/14985

**Comment by RobFog** [comment]
@LoveJessyChen The Support forum ([link](https://musescore.org/en/forum/6)) is better suited for support requests such as this one.

This issue tracker is intended for concrete bug reports and feature request that allow for fixing specific bugs. or adding features
