### ISSUE TITLE
MUSE SOUNDS / MS4: Bell Tree & Harpsichord Mapping Problems

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#14980]
**Describe the bug**
On MacOS, with the Release Candidate and MuseSampler 0.3.1, there are two issues with mapping:

**- The Bell Tree appears to map correctly in the mixer but there's no sound**
**- The Harpsichord does not automatically map to Muse Sounds. When you do it manually, the sound is fine**

<img width="224" alt="image" src="https://user-images.githubusercontent.com/21022311/205893130-39333b21-a3be-45ec-8543-001bfe5c4a31.png">

**Comment by vpereverzev** [comment]
Unfortunately, harpsichord is still missing. Take a look on musesampler lib output:

![image](https://user-images.githubusercontent.com/57620349/206186886-3050fddc-1b54-42f5-b29d-22263fa9fe59.png)

Every other instrument is in place already, expect poor harpsichord :)

**Comment by vpereverzev** [comment]
Just confirmed, it's working on the latest updated of MuseKeys. Thanks @davidwhearn
