### ISSUE TITLE
[MU4.xx] Request for Design Improvement: In normal view all 88 keys of the virtual keyboard should fit on an HD monitor

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#14998]
The graphic quality of the virtual keyboard has been improved significantly 
for the price of being less practical:

In normal view all 88 keys do no longer fit on an HD monitor without scrolling left or right.

I would suggest to scale down the keyboard 
so that in normal view all 88 keys fit on an HD monitor without the need to scroll left or right.

**Comment by LuisLiszt** [comment]
@oMrSmith click on the keyboard, press STRG while scrolling out, the Keyboard gets smaller and will fit onto your screen.

**Comment by oMrSmith** [comment]
Oh nice, thanks for letting me know! So I'm wondering: Why are there the different settings "small, normal, big"?

**Comment by oMrSmith** [comment]
Maybe this should be default then and the zoom setting should be saved when toggling "P"?...

![Unbenannt](https://user-images.githubusercontent.com/78870770/206039635-29f5f1ee-7f2d-442f-94cb-37bbed1f04bb.JPG)
