### ISSUE TITLE
[MU4 Issue] File menu items are disabled on the publish page

### ISSUE THREAD

**Issue by iwoithe** [musescore/MuseScore#15008]
**Describe the bug**
Options under `File` on the publish page are disabled even if there are buttons outside of the file menu.

**To Reproduce**
1. Create a new score or open a score
2. Go to `Publish`
3. Open the `File` menu
5. See the disabled menu items

See video under **Screenshots/Videos** for clarity.

**Expected behavior**
Items to be enabled. Particularly `Export...` and `Save to MuseScore.com...` as they have separate buttons on the `Publish` page.

I also don't see a problem personally enabling some of the other file menu items without buttons on the `Publish` page, for example project properties.

**Screenshots/Videos**

https://user-images.githubusercontent.com/73422868/206097325-8fc3dbd9-592d-441e-9f16-8391a8b97fca.mp4

**Platform information**
 - Slackware 15, Xfce 4.16

**MuseScore Version**
- Latest commit on `master`

**Additional Context**
I believe the cause is the same one in https://github.com/musescore/MuseScore/issues/12277 (that is, UI actions aren't allowed to exist in more than one context)

**Comment by DmitryArefiev** [comment]
Fixed in #16051

**Comment by DmitryArefiev** [comment]
Retested on Win10
