### ISSUE TITLE
[MU4 Issue] Muse Hub update process not user friendly

### ISSUE THREAD

**Issue by krtschil** [musescore/MuseScore#15015]
Update process of Muse Hub is not user friendly. The silent shutdown looks like a crash but is actually a regular shutdown of the application (at least I assume so).
If this is the intended workflow for the final version please rethink this as such a silent shutdown is irritating and annoying.

1. Download Muse Hub (Linux) from https://www.dropbox.com/s/o2rtbu3nrbuf3rc/Muse_Hub_Linux.zip?dl=1
2. Install it
3. Start Muse Hub, check the version (e.g. 0.9.7)
4. When there is an update available the app installs it silently and upon completion the app disappears / crashes
5. Restart the app and checking the version shows that a newer version is installed now (e.g. 0.9.10)

**Expected behavior**
On step 4 the user should be informed that an update is being installed, that the app will shutdown upon completion and the user must restart it.

**Platform information**
 - OS: Linux

**Comment by oktophonie** [comment]
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.
