### ISSUE TITLE
[MU4 Issue] Violoncellos seem to ignore the first note in triplets in f dynamics

### ISSUE THREAD

**Issue by innerthought** [musescore/MuseScore#15021]
**Describe the bug**:
Violoncellos seem to ignore the first note in triplets in f dynamics

**To Reproduce**:
1. Create a score with a stave for violoncellos with a triplet in dynamics f
2. Play it back to see the issue

**Expected behavior**:
The first note in the triplet must be heard

**Screenshots**:
![ignored_note](https://user-images.githubusercontent.com/119835219/206211385-0f4730c2-4251-4427-a0b7-72dcb4335cc3.jpg)

https://user-images.githubusercontent.com/119835219/206343463-9050d843-342a-4f54-9623-bac4b328378f.mp4

**Platform information**:
OS: Win-10, 64-bit operating system, x64-based processor

**Additional context**:

Latest builts tried:
MuseScoreNightly-223420306-master-8703745-x86_64
MuseScoreNightly-223410502-4.0_rc-a43001b-x86_64
MuseScore-4.0.0.223362132-x86_64 (Release Candidate)

The score: [ignored.zip](https://github.com/musescore/MuseScore/files/10177174/ignored.zip)

Comparing the violoncellos part to the violins part (in the solo mode) in the provided score helps to see the problem better. [EDIT of 2022.12.08] Or, perhaps, comparing this MS4 score playback to how same group of notes was played in MS3 makes the difference even more obvious: 
[ignored_in_MS3.mp3.zip](https://github.com/musescore/MuseScore/files/10186463/ignored_in_MS3.mp3.zip)

**Comment by krtschil** [comment]
Tried with RC1 and Nightly (Linux) at different tempi. I can clearly hear the first note of the triplet.

**Comment by innerthought** [comment]
@MarcSabatella: "RC = release candidate - the build announced on Discord that we're supposed to be testing exclusively"

- Thank you, Marc, for this explanation. What is Discord? How can I get to that built, which was announced on Discord? 
Do you, by any chance, mean this built: https://github.com/musescore/MuseScore/releases/download/v4.0_rc/MuseScore-4.0.0.223362132-x86_64.msi  ?

**Comment by krtschil** [comment]
@innerthought I reduced the tempo to be able to better discern the individual notes. To do this click on the first rest in your score, hit SHIFT+ALT+T which places a tempo above the stave. Double click inside and change the number from 80 to e.g. 40 for half the speed.

![grafik](https://user-images.githubusercontent.com/7796440/206441656-984e4a63-5632-4e8b-aa8c-1c8c1ccb5529.png)

This way the notes are played slower and I can hear all three notes of the triplet with the same volume.

**Comment by innerthought** [comment]
@krtschil: I see. However,  what is important to me is to be able to hear them all in the original tempo (that's how it was in MS3). Were you able to discern them all in the tempo in the original score?

**Comment by krtschil** [comment]
In the original tempo I think I can hear all 3 notes of the triplet with the same volume.

**Comment by krtschil** [comment]
I created mp3 from original and slowed down version. In my opinion I can hear all 3 notes of the triplets in both versions (although a bit fast in the original)

Original:
[ignoredOriginal.mp3.zip](https://github.com/musescore/MuseScore/files/10185872/ignoredOriginal.mp3.zip)

Tempo 65
[ignored65.mp3.zip](https://github.com/musescore/MuseScore/files/10185874/ignored65.mp3.zip)

(Remove the .zip ending to get the mp3 files)

**Comment by innerthought** [comment]
@krtschil One note or, perhaps, a part of a note is definitely missing in your first mp3 file (ignoredOriginal.mp3] Just compare the same score to how it was played in MS3 and the difference will be very clear: 
[ignored_in_MS3.mp3.zip](https://github.com/musescore/MuseScore/files/10186489/ignored_in_MS3.mp3.zip)

**Comment by krtschil** [comment]
Ok, if you can hear that, I don't. That's why I slowed down the playback so I can hear everything clearer. In tempo 45 I defintely can hear all three notes from the triplet and I assumed that the change in tempo does not change the playback but maybe it does exactly that.

**Comment by innerthought** [comment]
@krtschil: "_Ok, if you can hear that, I don't_"
–  Please, listen to the mp3 file that I gave you. It's just impossible that you can't hear it. I don't posses any phenomenal hearing ability and I don't think that I am hallucinating. It is very important for me that the difference is acknowledged here by others besides me.

**Comment by krtschil** [comment]
In the file you posted I can clearly hear the three notes (that is the MU3 version). My version from MU 4 sounds different at the point of the triplet but I find it hard to say whether there a three or only two notes played. That's why I tried slower tempi to find out. But as said earlier the change in tempo might affect also the playback.

**Comment by innerthought** [comment]
@krtschil : "My version from MU 4 sounds different at the point of the triplet but I find it hard to say whether there a three or only two notes played"
– I see. Thank you for saying that. It may be still three notes played, but kind of differently from how it was played in Musecore 3. There is definitely a difference, but I don't know how to determine and describe it correctly. It may be a short delay right before the triplet, or, perhaps, on some note within the triplet. I don't know. It just sounds different and grates on my ear.
Maybe, before posting this issue here on GitHub I should have firstly asked the community on MuseScore to help me determine what exactly constituted the difference.

**Comment by innerthought** [comment]
Thank you, Marc. It's good to know that this issue is not just my imagination and that it has, in fact, already been reported here. So, given that, should I close this thread then or should I keep it?

**Comment by MarcSabatella** [comment]
It's similar to those issue and *may* have the same underlying cause, but I suggest leaving it open until there the developers have a chance to analyze what's going on.

**Comment by innerthought** [comment]
@MarcSabatella: Got it. Thank you.

**Comment by innerthought** [comment]
With today's nightly build MuseScoreNightly-230300506-4.0.2-c229b14-x86_64 this problem has been fixed.
I am gladly closing this thread.
