### ISSUE TITLE
Modal behaviour when opening new windows

### ISSUE THREAD

**Issue by topquark22** [musescore/MuseScore#15036]
**Problem description**

Sometimes the interface goes into a "modal" behaviour when opening a new window. That could be opening "Stave/Part properties", or simply the main screen upon starting up MS4.

It becomes impossible to click on the window, as it seems to be expecting input from some other (nonexistent or inaccessible) modal dialog.

This seems to happen when using multiple monitors, with MS4 on Monitor 2 in full-screen mode, but I've seen the behaviour at other times.

The only way out is to kill the process in Task Manager.

**Expected behavior**
Window responds to input.

**Platform information**
Windows 10

**Additional context**
multiple monitors

**Comment by Eism** [comment]
@topquark22 
It seems that this is the same issue as #15119

So, check this issue too https://github.com/musescore/MuseScore/issues/15119#issuecomment-1350909594

**Comment by cbjeukendrup** [comment]
@topquark22 Is this still actual in the latest nightly build of MuseScore 4.1? https://musescore.org/en/nightly-builds
