### ISSUE TITLE
[MU4 Issue] Slur in tabulature attaches beam to head

### ISSUE THREAD

**Issue by GeertWil** [musescore/MuseScore#15042]
**Describe the bug**
See image. Slurs in standard score are as expected, in tabulature they are not.

**Expected behavior**
Slurs should connect beams or note heads (numbers in the case of guitar tabulature).
[Note: this happens only when Stem style = 'Beside stave' (not 'through stave')]

**Platform information**
 - OS: Windows 11.

![MuseScore4_ClqtfM296k](https://user-images.githubusercontent.com/9659505/206453976-498ad5fc-34ff-43e7-a9c6-abf775bd610a.png)

**Comment by oktophonie** [comment]
I'll add that, while creating an example to reproduce this, it's apparent that the horizontal offsets for slurs relative to beams in tablature are also off:

![image](https://user-images.githubusercontent.com/20604032/206456828-b46d9c95-2f2e-425e-bf1b-353ad6ea0b8f.png)
