### ISSUE TITLE
Alto instrument is missing

### ISSUE THREAD

**Issue by topquark22** [musescore/MuseScore#15045]
There is no Alto under Instruments -> Vocal (for SATB)

**Comment by oktophonie** [comment]
It's there but called "A. Bu." for me for some reason (?)

![image](https://user-images.githubusercontent.com/20604032/206486026-ec4124de-ba57-4625-a78a-038ca1183001.png)

**Comment by topquark22** [comment]
I would do that, but I can't do anything until  #15036 is resolved. That is a P1 that stops me from using MS4 at all.
----

    On Thursday, December 8, 2022 at 10:48:43 a.m. EST, Peter Jonas ***@***.***> wrote:  
 
 


Try updating your UK English translation in Preferences.

**Comment by topquark22** [comment]
Whatever. Nobody knows what "A. Bu." means, not even my best efforts to figure it out with Google. If it's Alto, then call it Alto.



    On Thursday, December 8, 2022 at 10:27:43 a.m. EST, Simon Smith ***@***.***> wrote:  
 
 


It's there but called "A. Bu." for me for some reason (?)

**Comment by oktophonie** [comment]
Fixable by updating translations as described.

**Comment by Jojo-Schmitz** [comment]
Oops, seems to have been a translation mistake of  mine...
