### ISSUE TITLE
[MU4 Issue] Playback not in sync with playhead when changing instrument in mixer

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#15047]
**Describe the bug**
Note: similar to #14894, but with a different trigger

When substituting instruments in the mixer and then resuming playback mid-score, the substituted instrument alone recommences playback from the start of the score (concurrently with the playback at playhead position).   

**To Reproduce**
See demo video:
https://www.dropbox.com/s/mx9ymh9rtbfihax/playback-sync-position-change.mov?dl=0

**Expected behavior**
Substituted instrument should not recommence playback from start, but should instead sync with current playhead position.

**Platform information**
 - macOS 12.6 (M1)
 - RC (4.0.0.223411003)

**Comment by pmarx810** [comment]
@Tantacrul @bkunda Very similar to #14902 , could be duplicate

**Comment by pmarx810** [comment]
@Tantacrul @MarcSabatella @RomanPudashkin also similar to the issue found in #14910

**Comment by bkunda** [comment]
Thanks @pmarx810, all these issues do indeed seem very similar to one another.
I'll keep this one open for now though because it contains a demo video, which is always useful for our devs so they can actually see what's going on. 
Thanks!

**Comment by MarcSabatella** [comment]
@Tantacrul this one comes up often and I assume it would be a simple fix to consider for a patch

**Comment by cbjeukendrup** [comment]
> @Tantacrul this one comes up often and I assume it would be a simple fix to consider for a patch

@Tantacrul This would indeed be good. Not sure how simple it is (although it can't be too complicated), but it would certainly be nice to get this fixed since it has come up quite a few times.

**Comment by Tantacrul** [comment]
I'd like to hear what @vpereverzev has to say.

Patch or 4.1?

**Comment by bkunda** [comment]
@DmitryArefiev can you please check this one again for validity/reproducibility?

**Comment by DmitryArefiev** [comment]
Fixed in #20626
