### ISSUE TITLE
[MU4 Issue] MS Basic has a mono reverb even if Audio FX is set to No effect

### ISSUE THREAD

**Issue by lgmventura** [musescore/MuseScore#15054]
**Describe the bug**
Mono reverb on MS Basic instruments. This is happening even if _Audio FX_ is set to _no effect_. This is not happening with imported SoundFonts (SF2) and with MuseSounds.

**To Reproduce**
1) Open any recent development version of MuseScore 4.0. I tested with both Beta and Release Candidate 1.
2) Create a score using MS Basic
3) Add some notes, especially short (staccato) notes
4) Playback

If you listen carefully, there is an awful mono reverb in apparently every MS Basic instrument. In MuseScore 3.6.2, there is the Zita reverb, which is a better quality stereo reverb and you can deactivate it in the synthesizer if you want to use your own reverb or simply don't want any reverb.

**Expected behavior**
No reverb if no reverb was chosen for the instrument or globally. Especially not a mono reverb.

**Platform information**
 - OS: Ubuntu 22.04
 - Stereo phones

**Comment by bravely-beep** [comment]
Is there any plan to implement a short-term solution to allow the option of disabling reverb entirely, as a temporary measure until the 'better alternative' reverb is implemented?

**Comment by Tantacrul** [comment]
We're going to be conclusively fixing this in 4.1.

**Comment by Tantacrul** [comment]
We already have it logged as a task, so I'm closing this. Thanks!
