### ISSUE TITLE
Critical issue #14308 was closed for the wrong reason, please read! The issue is still present in the release candidate. I found a fix!! [MU4 RC]

### ISSUE THREAD

**Issue by Lighwan** [musescore/MuseScore#15062]
@bkunda @pmarx810 @Tantacrul [Issue in question](https://github.com/musescore/MuseScore/issues/14038)

The issue was not caused by the score being created in musescore 3, it was caused by this forte!

![image](https://user-images.githubusercontent.com/68567124/206607244-52207189-2c16-4ae3-992b-d1a52373b8dd.png)

Adding a forte after a piano on solo violin results in the violin becoming overly quiet, dynamics being all over the place and of course, dropping notes! After loading up the score mentioned in #14308 again, I found that simply removing the forte in the next variation solved the issue!

It also tremendously improved audio quality in the final variation.
Getting rid of these forte markings improved the quality of the quieter sections tremendously!
I cracked the code!
![image](https://user-images.githubusercontent.com/68567124/206607794-cc546007-91fa-4927-8ab8-c6af9d1714f5.png)

**Comment by pmarx810** [comment]
Again, weird too. Haven't got around to re-notating in MS3, but also yes, I found that dynamics were a big struggle in the RC I was using at the time.
