### ISSUE TITLE
[MU4 Issue] Can't scroll horizontally with touchpad after export folder is opened

### ISSUE THREAD

**Issue by Fristover** [musescore/MuseScore#15086]
**Describe the bug**
After exporting a project with "Open destination folder on export" checked, horizontal scroll on touchpad doesn't work until you close or minimize the opened folder

**To Reproduce**
1. Open any project
2. Export to any format and check "Open destination folder on export"
3. Folder will open, click outside to focus on MU window
4. Try to do a horizontal scroll, see error.

**Expected behavior**
Horizontal scroll works

**Platform information**
 - OS: Windows 11

**Additional context**
Only tried with Windows, I assume a normal mouse will work fine as doing shift + vertical scroll does work fine

**Comment by zacjansheski** [comment]
I can't reproduce, but I am using Mac trackpad.  (only mouse on other OS)

1.  Is this still an issue?
2.  What hardware are you using?

**Comment by Fristover** [comment]
Hey!, this is not an issue anymore, doesn't happen on the laptop I used that time nor on the new one, forgot to close it hehe
