### ISSUE TITLE
Melisma remains after changing note value

### ISSUE THREAD

**Issue by Aurivox** [musescore/MuseScore#15093]
If you have lyrics with melisma and have changed the values, the melisma remains. In MS 3 you were able to remove them by editing the lyrics and type the space bar. In MS 4 you have to delete the lyric

(Current MuseHub OS: macOS 13.0, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223362133, revision: github-musescore-musescore-d050fb0)
![Bildschirm­foto 2022-12-10 um 09 25 50](https://user-images.githubusercontent.com/103463374/206841328-dfd71371-ee69-4346-93a5-d1f2065264a1.jpg)

**Comment by oktophonie** [comment]
Seems logical to me that if a melisma is reduced to one note then the line should just disappear:
![image](https://user-images.githubusercontent.com/20604032/206851838-11098d59-1554-4f8f-b991-713139b68d3b.png)
_b)_ and _c)_ already work as described here so only _a)_ is the problem.
(This is not a regression from 3.6, but the spacebar behaviour is different, as noted.)

Whether the syllable should automatically become centered when the melisma is removed is a question.

**Comment by Aurivox** [comment]
In MS 3 it's the same behavior with the underline
![Bildschirm­foto 2022-12-10 um 16 51 35](https://user-images.githubusercontent.com/103463374/206863761-b39fc3a7-c1e5-44ba-b23b-26ec3db2172a.jpg)

**Comment by oktophonie** [comment]
An issue that may be considered related (or not).

If a syllable after a dash is deleted, the dash remains (it should go), and also the __previous__ syllable, if it was centred, becomes left-aligned (it shouldn't):
![image](https://user-images.githubusercontent.com/20604032/209385895-ff4f3603-c715-432a-ba6b-cb69c084e1f8.png)
![image](https://user-images.githubusercontent.com/20604032/209385957-f1131b29-6c41-4db2-9b28-cb942c927452.png)

**Comment by Jojo-Schmitz** [comment]
Came up again in the German forum, see https://musescore.org/de/node/343537
Very anoying to have to remove the syllable in order to be able to dget rid of the melisma
