### ISSUE TITLE
[MU4 Issue] - Constant freezes

### ISSUE THREAD

**Issue by flyingrabbitgb** [musescore/MuseScore#15092]
**Describe the bug**
Freezes can happen at different times. It variously freezes when on the Welcome Screen, when trying to create a new file, or when trying to open an existing file. It has also started to recently happen with saving a file (should I actually be lucky enough to be able to open or create one in the first place). This has only recently started happening, since the update that caused issues with MuseSounds. I've completely uninstalled MS4, MuseHub, MuseSounds, and reinstalled them all. I've installed MS4 both through the RC1 download link and through MuseHub, but this keeps happening. As far as I can tell, I also removed all related files and folders (unless there is something hidden in a non-standard location

**Platform information**
 - OS: Windows 10 (fully updated)
 - CPU: Intel i7 7700k
 - RAM: 32GB
 - Graphics: NVidia 1060 6GB
 - HD: Running off SSD

MuseScore 3 and all other software is completely stable. As previously stated, this only started happening around the time of the RC1 update.

**Comment by oktophonie** [comment]
Closing as too vague, but if you are still encountering this problem (with 4.0.1 or later) please open a new issue with specific reproduction steps/circumstances.
