### ISSUE TITLE
[MU4 Issue]"Play" property for note mutes playback of entire chord

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#15096]
**Describe the bug**
Turning off playback for a single note in a chord actually turns it off for the entire chord

**To Reproduce**
1. Enter a chord C-E-G
2. Select to G
3. Turn of "Play" in Properties
4. Play score
5. Hear error: entire chord is muted

**Expected behavior**
Only the select note should be muted

**Screenshots**

https://user-images.githubusercontent.com/1799936/206860492-77284466-ca89-4322-9686-787ea64ebec2.mp4

**Platform information**
 - OS: Linux

**Additional context**
Reproduced in RC and in current nightly from rc branch.  Applies to both MS Basic and Muse Sounds.

This is a regression vs MU3.  I'm not sure this ever worked in MU4 and might currently be by design, since other general settings do apply to the full chord.  But the ability to disable playback of individual notes is important, and if this isn't the correct control for the note only, a separate control should be provided in the note section.

**Comment by LuisLiszt** [comment]
Same on WIndows. Though by deselecting the "play" property for one note, it's not like that's muting the entire chord, it's more like the other notes of the chord also have the "play" property deselected. That's important here.
