### ISSUE TITLE
[MU4 Issue] Instant crash when pressing Ctrl+A on an old musescore 2 file (with workaround).

### ISSUE THREAD

**Issue by bambancico** [musescore/MuseScore#15108]
**To Reproduce**
1. Load an old file [Musescore website](https://musescore.com/emperoni/gran-jota-de-concierto), [my copy](https://github.com/musescore/MuseScore/files/10202299/Files.zip) (I reproduced the error with original file again to ensure it is not corrupt).
2. Press Ok when shown the "it may be shown differently" prompt
3. Press Ctrl+A
4. Crash

**Expected behavior**
It outright crashes, but it doesn't when you select the whole score with the mouse.

**Workaround**
When saved in Mu4 AND reopened it no longer crashes.

**Platform information**
 - Windows 11 (22H2), AMD 5600u

**Additional context**
I cannot troubleshooot further since I don't have access to Mu2. [This](https://musescore.com/emperoni/gran-jota-de-concierto) has been, so far, the only file that's given me trouble. I am attaching the [original and the "resaved" files](https://github.com/musescore/MuseScore/files/10202299/Files.zip).

**Comment by oktophonie** [comment]
Can confirm this crash still occurs in 4.0.1 (with https://musescore.com/emperoni/gran-jota-de-concierto)

**Comment by Jojo-Schmitz** [comment]
3.6.2 crashes on thos too.

**Comment by DmitryArefiev** [comment]
Fixed in #17302
