### ISSUE TITLE
[MU4 Issue] MuseHub Demo Scores not using Muse Sounds sounds by default

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#15106]
**Describe the bug**
Downloaded the 2 demo songs available in MuseHub today. 
Muse Orchestra Demo & Searching For

The downloaded files have a really strange name once downloaded. I.e. bb8dcc72-f68e-400b-b8af-287f56a3ee4b.mscz
Not the bigest problem though.

When I open the Introducing Muse Orchestra score, the playback settings show that MuseSounds is the active profile, however in the mixer all channels are set to use MS Basic.
Changing the profile to MuseScore Basic, activate it, and then change back to MuseSounds does not change the sounds used in the mixer.
Another issue I noticed for this score is that the Picollo and Flute are using notes in the score outside the range of MuseSounds. Not a big issue but not something you would expect from a demo.

When I open the Searching Four score, the playback settings show that MuseScore Basic is the active profile. Selecting the MuseSounds profile, and activate it changes the sounds used in the mixer to the MuseSounds versions. Except for the Alto Flute, this remains using MS Basic.

Both cases not really helpful for a good demo....

**To Reproduce**
1. Open MuseHub
2. Open Inspiration tab
3. Download the songs
4. Open the song in MU4

**Expected behavior**
The demo songs should he Muse Sounds enabled by default, including the selected sounds in the mixer.

**Platform information**
 - OS: Windows 11

**Comment by DmitryArefiev** [comment]
I've checked **Muse Orchestra Demo** and **Searching For** on MuseHub 1.0.2.800, MuseScore 4.1.1, Windows10 - **all good now**

Please reopen if still occurs

**Comment by henkdegroot** [comment]
@DmitryArefiev, almost all good now. In both scores the Clarinet Bb is using MS Basic. And in the Searching Four, the Bass Clarinet is also MS Basic. So slightly different now. Do you prefer to open a new issue for that?

**Comment by DmitryArefiev** [comment]
@henkdegroot Thanks for testing! Yes, please a create new one, and please do it on MuseHub site. 
When creating a new issue, just click Muse Hub issue and it will transfer you to https://musehub.zendesk.com/hc/en-gb
![Capture5](https://github.com/musescore/MuseScore/assets/90187801/18891f45-a48a-408c-bda3-6849e4d81f25)
