### ISSUE TITLE
[MU4 Issue] Muse Hub Wont Launch

### ISSUE THREAD

**Issue by Jurassicboy2710** [musescore/MuseScore#15118]
Went Clicking on the Icon for Muse Hub or using MuseHub.exe, the application will not open.

1. Click On The Icon To Open Muse Hub Or Double Click MuseHub.exe
2. Experience Bug

Expected behavior:
Muse Hub is expected to open allowing access to its interface.

 - OS: Windows 10 Home

**Comment by rubiot** [comment]
Same behavior here, it worked fine, but then I accepted an update to Muse Hub itself and it won't start anymore. I even uninstalled it and reinstalled but no luck. The service starts OK, though. Unfortunately I overwrote the old installer... I'm positive it would work.
OS: Windows 10 Pro 64-bit

**Comment by rubiot** [comment]
https://github.com/musescore/MuseScore/issues/15032#issuecomment-1343091273
Installing the update mentioned in the issue above solves the issue (https://download.microsoft.com/download/4/f/a/4fa2ea8c-c5ef-4ba7-8855-0c578090c094/WindowsAppRuntimeInstall.exe)

**Comment by DominicMaas** [comment]
Which link did you install to fix the issue, the top one or bottom one?

**Comment by rubiot** [comment]
The bottom one.

**Comment by DominicMaas** [comment]
Very interesting, I may need to bump the WinAPPSDK version we're using.

@Jurassicboy2710 Can you try installing the link above and trying again

Linking in #15005 as it might be related

**Comment by Jurassicboy2710** [comment]
> Very interesting, I may need to bump the WinAPPSDK version we're using.
> 
> @Jurassicboy2710 Can you try installing the link above and trying again
> 
> Linking in #15005 as it might be related
> 
> Or use this direct link here (they are the same): https://aka.ms/windowsappsdk/1.2/1.2.221116.1/windowsappruntimeinstall-x64.exe

After downloading from the link and installing it, Muse Hub is working again. Thx for the help!

**Comment by DominicMaas** [comment]
Good to hear! No problem.

**Comment by oktophonie** [comment]
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.

**Comment by huien535** [comment]
thanks!!!
