### ISSUE TITLE
[MU4 Issue] File corrupted including backup after creation and saving in MU4

### ISSUE THREAD

**Issue by ecstrema** [musescore/MuseScore#15113]
**Describe the bug**
The title says it all. See attached file. I created it in MU4 (latest), saved it, and couldn't open the next day. Nothing really dramatic on my end, since it was only maybe an hour of work, but the fact that the backup too is corrupted really worries me.

**To Reproduce**
I can't recreate such a corrupted file. However, if you try to open the attached file, you'll see that same "file is corrupted" error.
[corrupted_file.zip](https://github.com/musescore/MuseScore/files/10203464/corrupted_file.zip)

**Expected behavior**
No file corruption.

**Screenshots**

**Platform information**
 - OS: Windows,

![image](https://user-images.githubusercontent.com/35939574/206932608-4b4d7e62-5a2a-4c6a-9705-0c9904e5afe9.png)

**Additional context**
I don't remember how I closed musescore. Did I just close my laptop lid? Did I shutdown the computer without shutting down MuseScore first? Maybe, but that still shouldn't cause such file damage.

**Comment by Tantacrul** [comment]
@RomanPudashkin - same question. Has this corruption issue been fixed? It's sitting in the old Patch 4.0.1 project and I thought I'd clear it out. Reopen if you need.

**Comment by RomanPudashkin** [comment]
> @RomanPudashkin - same question. Has this corruption issue been fixed? It's sitting in the old Patch 4.0.1 project and I thought I'd clear it out. Reopen if you need.

This particular corruption is different from other types of corruption that have been fixed in the first patch. However, we could not reproduce it. The description of the issue is also rather vague. So, there wasn't much we could do about it

**Comment by Tantacrul** [comment]
OK, well if @ecstrema can provide more info, perhaps we'll reopen it.

**Comment by ecstrema** [comment]
I unfortunately don't have more info. I have no idea how I ended up with this corrupted score. I wish it's fixed though.
