### ISSUE TITLE
[MU4 Issue] Wrong notes played when setting play count of a repeat

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#15112]
**Describe the bug**
If you set a repeated section to play three times, the wrong notes / measures get played

**To Reproduce**
1. Create a score and add notes to first three or more measures
2. Add an end repeat to bar 2
3. Set bar 2 play count to 3
4. Play
5. Hear error: on the 2nd repeat, the first note of the passage is not played, and on the third repeat, a measure from after the end repeat is played although the playback cursor shows the correct measure

**Expected behavior**
Correct playback

**Screenshots**

https://user-images.githubusercontent.com/1799936/206931154-2ea4d8a7-8bdf-43c8-aa1b-4abd44a969cd.mp4

**Platform information**
 - OS: Linux

**Additional context**
Tested on last night's RC build (December 12)

The issue fixes itself on save/reload, and also, if you then add or remove a repeat - I guess that recalculates the repeat map.

**Comment by bkunda** [comment]
@zacjansheski pls check for reproducibility
