### ISSUE TITLE
When using multiple monitors, popup screens appear way offscreen to the right

### ISSUE THREAD

**Issue by topquark22** [musescore/MuseScore#15119]
**Describe the bug**
When using dual monitors, with Monitor 2 on the right, the popup dialogues appear off screen to the right.

**To Reproduce**
Open a score.
Move it to the 2nd monitor on the right.
Open a dialog (e.g. "Add instrument)

**Expected behavior**
Dialog appears in the middle of the operative monitor.

**Actual behavior**
Dialog appears off to the right-hand side of the screen.

**Platform information**
 - OS: Windows 10

**Additional context**
dual monitors

**Comment by Eism** [comment]
@topquark22 
Please check this build https://github.com/musescore/MuseScore/actions/runs/3693810661

**Comment by DmitryArefiev** [comment]
Fixed in #14547

**Comment by DmitryArefiev** [comment]
Retested on Win10
