### ISSUE TITLE
OK and Cancel untranslated in Slovenian

### ISSUE THREAD

**Issue by Mejdunn** [musescore/MuseScore#15114]
In Slovenian language, despite in Transifex it is translated, in most dialogs "OK" and "Cancel" are not showing as translated. Colleague on forum mentioned that this can be connected to Qt libraries and that it has been resolved for a couple of other languages that had the same issue.

**Comment by Jojo-Schmitz** [comment]
Not much we can do about this: those translations stem from Qt directly. In this case they are simply missing.
And no, other languages srtill have the same issue
