### ISSUE TITLE
Musescore 4 (Release Candidate version) "Export" feature does not work

### ISSUE THREAD

**Issue by Violafred** [musescore/MuseScore#15128]
Musescore 4 (Release Candidate version) "Export" feature does not work. I can't export a MP3 score soundtrack, or anything else, for saving to the local PC.

1. Go to 'File'
2. Click on 'Export'
3. Select file 'Type', (MP3, PDF, etc.)
4. Select 'Export'

After selecting Export, I should be given a 'Save To' location window, but nothing happens.

**Platform information**
Windows 11 Pro 64-bit

**Comment by MarcSabatella** [comment]
I'm guessing you accidentally moved the dialog offscreen and now it keeps trying to appear there.  Try Help / Revert to Factory Settings.

**Comment by Violafred** [comment]
Thank you for a prompt response. I'll try your recommendation as soon as I get home from work and I'll let you know if it fixed the problem. Thanks for all you do.

**Comment by Violafred** [comment]
It worked. Thank you. However now my score always open corrupted. I just ignore and make the corrections. I hope that is fixed with the stable version. Thank you.
Regards,

Frederick Del Pozo Jr.
(You don't have to be classy to enjoy Classical music. That's the beauty of the language of music) 

    On Monday, December 12, 2022, 01:47:24 PM EST, Marc Sabatella ***@***.***> wrote:  
 
 


I'm guessing you accidentally moved the dialog offscreen and now it keeps trying to appear there. Try Help / Revert to Factory Settings.

**Comment by MarcSabatella** [comment]
If your score is corrupted, that isn't going to fix itself, you'll need to fix the corruptions.  If you need help with that, best to ask on the Support forum on musescore.org

**Comment by Violafred** [comment]
I do fix the corruptions. But since the 'Show Details' button is still missing on MU4 RC, it is a pain-staking task, to say the least. I fix the current corruptions and new ones pop up the next time I open the score. Unless these are corruptions in the score that I missed the last time I made corrections. Again, I can't help but stress the importance of the 'Show Details' button. I really miss that button. :)

**Comment by MarcSabatella** [comment]
Yes, that has been amde a high priority issue.  meanwhile, you can export to MusicXMl and load into MuseScore 3 to get the list.

Anyhow, if you are saying you have fixed all corruptions and verified this by loading into MuseScore again, then new ones appear, we'd definitely want to know more about how to reproduce that issue - the un-corrupted score and precise steps to reproduce the corruption.  Best to open a new issue for that.  THen the problem can be investigated and hopefully fixed.

**Comment by Violafred** [comment]
Yes, I can do that for you. It will take me a couple of hours or so to put it all together for your team to take a look at. However, before I do that, I will need to verify that the score is truly uncorrupted to begin with. After I verify that, I'll know that I either missed some corrections or MU4 (RC) really is corrupting the score after closing it and reopening it. Stay tuned (no pun intended). Thank you.

**Comment by Violafred** [comment]
I see you closed this ticket. However, the issue persist. To recap,(using 4.0.1, 64-bit), when I open a completed score, it shows as corrupted. I then fix all the wrong notes. I close the score. I then reopen the same score, it shows as corrupted again. this has gone on since Musescore 4.0 was released. I need more guidance on how to show the issue.
Regards,

Frederick Del Pozo Jr.
(You don't have to be classy to enjoy Classical music. That's the beauty of the language of music) 

    On Wednesday, February 22, 2023 at 07:53:27 AM EST, Simon ***@***.***> wrote:  
 
 


Closed #15128 as completed.

**Comment by MarcSabatella** [comment]
Maybe I'm missing something, but support questions about how to fix a corrupted score don't relate to the original issue about the export dialog not appearing.  The issue is closed because that was never a bug.

Meanwhile, if you have questions about how to fix corruptions, please ask for help on the Support forum on musescore.org.  Be sure to attach the score in question there.
