### ISSUE TITLE
[MU4 Issue] Playback Tempo 4x Faster

### ISSUE THREAD

**Issue by xman2156** [musescore/MuseScore#15137]
Description:
When creating any score, the tempo is 4x faster and the audio is high pitched no matter what SoundFont I'm using.

1. Create normal score
2. Add notes
3. Listen to playback set too fast

Expected Behavior:
The tempo should be much slower, and the pitch shouldn't be that high

Example:
https://user-images.githubusercontent.com/34029777/207176892-6dd42367-1caf-4c9b-9412-139230117b01.mp4

Info:
 - OS: Windows 11
 - Build: MuseScore 4.0.0.223362132

**Comment by CarlGao4** [comment]
I know what happened! I also encountered this. Please go to system settings (<kbd>Win</kbd>+<kbd>i</kbd>), `System`, `Sound` (I'm using Chinese, maybe incorrect), click you currently using output device, and see the format you are using. It may be 192000Hz, while MU4 can only use 44100Hz, so it is (192000/44100) times faster. 
![image](https://user-images.githubusercontent.com/57826826/207262878-197a20ba-11b0-455d-bba2-0149e21eed97.png)

**Comment by CarlGao4** [comment]
@xman2156 Maybe you can change the title to "Playback can't use system samplerate but stick to 44100"

**Comment by xman2156** [comment]
It was set to 192000Hz but turning it down to 44100 didn't fix the issue.

**Comment by CarlGao4** [comment]
Did you change the sample rate of the output device that MuseScore is using? If it is, please restart MuseScore.

**Comment by xman2156** [comment]
I tried that.

**Comment by CarlGao4** [comment]
But the problem was solved after I did this. Maybe restarting the system is required? (I restarted my computer after changing sample rate)

**Comment by xman2156** [comment]
Seems to be fixed in the official release.
