### ISSUE TITLE
[MU4 Task] Allow dynamics to be played independently between hands on the Piano

### ISSUE THREAD

**Issue by JR-Tech-and-Software** [musescore/MuseScore#15133]
**Task description**
I was looking through my older scores in MuseScore 4 and wanted to hear how they sounded with MuseSounds. I opened up a piano piece that had the two hands playing different dynamics. When I played it, both hands used the same dynamics instead of each hand having different dynamics.

In MuseScore 3, I could fix this using the "Dynamic Range" property. In MuseScore 4, I either cannot find that property, or it doesn't exist. I would assume it would be under the "Playback" settings in the Properties pane, but it is grayed out. I'm sorry if I'm wasting your time and that the solution is that I cannot find the setting, but I truely have no idea how to do this.

I should also note that I am using the Keyboard Muse Sounds while playing back the music. I'll attach the MuseScore 3 file, along with the MuseScore 4 file I got when I saved my score with new engraving. Thanks!

[MuseScore Files.zip](https://github.com/musescore/MuseScore/files/10212390/MuseScore.Files.zip)

**Comment by fsgregs** [comment]
I totally agree wit this bug.  Dynamics MUST be **adjustable** between the treble and bass clefs of an instrument, so that one can be played louder or softer than the other.  I use this all the time in MS 3.6 and to not be able to use it in MS is a MAJOR issue.  Thanks in advance.

**Comment by oktophonie** [comment]
Superseded by https://github.com/musescore/MuseScore/issues/16812
