### ISSUE TITLE
[MU4 Issue]crash when export svg

### ISSUE THREAD

**Issue by enochenoch** [musescore/MuseScore#15138]
crash when export svg

**Comment by Eism** [comment]
@enochenoch 
Please follow the template when creating an issue and complete at least these fields. 

**To Reproduce**
Steps to reproduce the behavior
**Platform information**

Anyway, I can't reproduce on macOS. Please attach a score on which you have a crash.

**Comment by CarlGao4** [comment]
@Eism Maybe this person encountered the same issue as #15142

**Comment by abariska** [comment]
Can't reproduce also. macOS and Ubuntu

**Comment by zacjansheski** [comment]
Closing due to lack of information and lack of reproducibility.
