### ISSUE TITLE
[MU4 Issue] changing time signature changes number of measures in piece

### ISSUE THREAD

**Issue by hackbar** [musescore/MuseScore#15131]
**Describe the bug**
Changing the time signature changes how many measure are in a piece.

**To Reproduce**
- Create a piece with 187 measures with time signature 4/4.
- In the 9th measure, change the time signature to 2/4.
- The rest of the piece will be in 4/4 (expected), but the numbers of measures will about double.

**Expected behavior**
Changing time signatures shouldn't affect how many measures a piece has. 

**Screenshots**

**Platform information**
OS: Debian GNU/Linux rodete, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223072007, revision: github-musescore-musescore-2c34155

**Additional context**
I'm guessing the measure count is actually beat count, which isn't right.

**Comment by MarcSabatella** [comment]
? I'm confused.  If you change from 4/4 to 2/4, of course there will need to be twice as many measures to continue to hold all the music you've entered.  I guess maybe you haven't entered music yet, but I don't think the behavior of this command should change according to when you run it.

**Comment by hackbar** [comment]
Yes, I'm starting with a blank piece, so there's not a reason to change the number of measures.

Even with a piece with existing music, if I change the time signature early in the piece, the end result (notes moved around) is kinda strange.

I think the issue here is Musescore deals with beats, while I as a composer think in terms of measures.

**Comment by MarcSabatella** [comment]
As a composer also, I think in terms of *notes*, and am glad MuseScore doesn't throw half of them away just because I change time signatures :-)

**Comment by hackbar** [comment]
I wouldn't expect notes not fitting in measures to be deleted, rather stay in the same measure and turn red or whatever to show they don't fit in the measure anymore.

**Comment by MarcSabatella** [comment]
That's not what I expect all - I expect the music to simply be rewritten in 2/4 - so

| C D E F |

would then become

| C D | E F |

and this is exactly what happens.  Feel free to start a discussion about this in the fourms on musescore.org (which is the more appropriate place for that sort of brainstorming).  Perhaps if there are enough others users who also would want a new feature that forces extra notes into measures when you change time signatures, it could be considered as an option.  But for now, I think the vast majority are happy that doesn't happen by default.
