### ISSUE TITLE
[MU4 Issue] shortcut in text field adds special character

### ISSUE THREAD

**Issue by ecstrema** [musescore/MuseScore#15135]
**Describe the bug**
Pressing shortcuts like ctrl+s in text fields adds special characters instead of actually executing the shortcut.

**To Reproduce**
1. Click a note, and ctrl+t to add text to it.
2. press ctrl+s.

You should see this:
![image](https://user-images.githubusercontent.com/35939574/207168633-28da8f36-fbe0-427f-886a-4a7498624000.png)

**Expected behavior**
pressing ctrl+s or any other shortcut should execute the shortcut instead. definitely not add an unknown special char.

**Platform information**
 - OS: Windows

**Comment by oktophonie** [comment]
This seems to have become fixed at some point in master (see latest nightlies) - though not 4.0.2; I'm not sure which PR did it!
I'll close this for now, but do reopen if you find otherwise.

**Comment by MarcSabatella** [comment]
I am assuming it is probably https://github.com/musescore/MuseScore/pull/15081, but this PR is problematic in that it breaks Ctrl+Left/Right (navigation by measure for chord symbols).  So hopefully whatever is done to fix that does not inadvertently unfix this...
