### ISSUE TITLE
[MU4 Issue] Exported audio file name uses wrong encoding which may cause crash

### ISSUE THREAD

**Issue by CarlGao4** [musescore/MuseScore#15142]
**Describe the bug**
The encoding of file names of exporting audio files is wrong

**To Reproduce**
My file name: "清流赋诗 MU4.mscz"
I then tried to export an audio named "清流赋诗 MU4.flac"
It create an audio with correct file name but contains nothing. Then the progress bar of exporting appears. 
Minutes later, the progress reaches 80%, then it created a file called "娓呮祦璧嬭瘲 MU4.flac". 
After the end of exporting, the first file contains nothing, the file wrongly named has the whole audio. 
![image](https://user-images.githubusercontent.com/57826826/207260668-3e3406eb-2136-49d2-984c-57c9dc1d0ad3.png)

I also noticed that "清流赋诗" encoded using utf-8 and "娓呮祦璧嬭瘲" encoded using gbk (which is the encoding of default code page 936 on a computer whose default language is Chinese) is same.
So I can conlude that the export module has wrongly disabled unicode for writing file name.  
![image](https://user-images.githubusercontent.com/57826826/207257344-77e0a987-6742-4d90-93dc-5e80011c4e19.png)

Then I deduced that the reason why sometimes the program directly crashes at 80% is because encoding error: if I set the file name as "云海的潮声.flac", then its utf8 encoded string can't be decoded using gbk:
![image](https://user-images.githubusercontent.com/57826826/207261965-a598a17e-2d8c-4c25-b303-54a335e2e79a.png)

**Expected behavior**
I know that you all know. 

**Screenshots**
See above. 

**Platform information**
 - OS: Windows 11 (10.0.22623.1028) (Latest Insider preview of Beta)

**Additional context**
Yes, this is the same issue as:
https://github.com/musescore/MuseScore/issues/14765
https://github.com/musescore/MuseScore/issues/14913
https://github.com/musescore/MuseScore/issues/14613
https://github.com/musescore/MuseScore/issues/14514
https://github.com/musescore/MuseScore/issues/14173
I've used the latest build, but the problem exists. 

I know that you are releasing MU4 in the near future, so this issue become important.

**Comment by CarlGao4** [comment]
The release fixed this.

**Comment by CarlGao4** [comment]
Hmmmm...
This issue still exists on 4.0.0 sometimes...

**Comment by zacjansheski** [comment]
Is this still actual?  (I see many of the related issues are closed)

**Comment by CarlGao4** [comment]
I encountered this issue on 4.0.2
I'll try 4.1 later today (UTC+8) and tell you whether it still exists

**Comment by CarlGao4** [comment]
Yes, this issue still exists on 4.1.0

**Comment by zacjansheski** [comment]
@vpereverzev I've seen that you have closed similar issues with your PRs... I'm not completely sure how to prioritize this one, please advise, thank you!

**Comment by vpereverzev** [comment]
looks like this issue deserves another try in the next release (4.2)

**Comment by CarlGao4** [comment]
I hope that you can understand what I mean in the description of this issue!

**Comment by cbjeukendrup** [comment]
Is this issue specific to FLAC export, and are other audio types fine? (I can't test this myself right now, because this issue seems specific to Windows, which I don't have handy at the moment)

**Comment by CarlGao4** [comment]
You can tell me where the codes of exporting audio files are, I can try to read the codes myself and figure out what the problem is

**Comment by CarlGao4** [comment]
Same issues:
#15539

**Comment by cbjeukendrup** [comment]
It looks like this can be solved by updating the version of the FLAC library that we use. I am currently doing that; there is a small problem but I expect to have it ready later today.

**Comment by cbjeukendrup** [comment]
@CarlGao4 Could you please test whether #18824 solves this? (See here for how to test the builds from a pull request: https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests; the build will be ready in ca. 30 minutes from now.)
