### ISSUE TITLE
[MU4 Issue] Changing soundfont while playback causes the specific instrument to start from beginning while the others and cursor continue

### ISSUE THREAD

**Issue by CarlGao4** [musescore/MuseScore#15143]
Using Windows 11 Latest Insider Beta Channel
Musescore version: 4.0.0.223391656

**Comment by abariska** [comment]
Can't reproduce.
@CarlGao4 Could you provide screen recording of the issue reproducing? 
Thanks

**Comment by CarlGao4** [comment]
Duplicated so I'll close this
