### ISSUE TITLE
[MU4 Issue] Crash after specific actions with Instruments

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#15165]
**Describe the bug**
Probably related to https://github.com/musescore/MuseScore/issues/15127
Test score [smoke 2.mscz.zip](https://github.com/musescore/MuseScore/files/10258986/smoke.2.mscz.zip)

**To Reproduce**
1. Open the score
2. Choose one instrument and add a stave for it
3. Ctrl+Z
4. Add a linked staff for the same instrument
5. Ctrl+Z
6. Delete the instrument
7. Ctrl+Z

**Expected behavior**
No crash

**Screenshots**

https://user-images.githubusercontent.com/101250347/207611950-34a54269-275d-4d66-bf51-ef5bb4dcff44.mp4

**Platform information**
 - OS: macOS

**Comment by Harmoniker1** [comment]
Can't seem to reproduce this on Windows 11…

**Comment by cbjeukendrup** [comment]
@abariska I think I have a fix; it seems to be caused by the articulations. But to be sure, could you please upload the score so that I can check?

**Comment by abariska** [comment]
> could you please upload the score so that I can check?
@cbjeukendrup added to description

**Comment by cbjeukendrup** [comment]
@abariska Thanks! Indeed my PR turns out to fix it for this score too!

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12
