### ISSUE TITLE
[Windows Installer] MuseScore udpate via MuseHub doesn't uninstall the previous build properly (two version entries in Installed apps) if previous version was installed from msi file manually

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#15167]
**To Reproduce**
1. Install previous version of MuseScore v4 from https://github.com/musescore/MuseScore/releases
2. Install current MuseScore release build via MuseHub

![Screenshot 2022-12-14 141738](https://user-images.githubusercontent.com/90187801/207630423-53f87adc-7ad8-4fa3-b746-46d517d052a0.png)

But if to close the window by clicking OK the installation of the latest build is fine.

Only leads to this:

![Capture](https://user-images.githubusercontent.com/90187801/207630567-2973cd68-2fb7-47ac-8ce2-fa908eecc1cc.png)

 You should uninstall MU previous build from that menu to live only one MU4 item

Occurs if to update MuseScore via MuseHub (doesn't occur if to update manually)

**Platform information**
Windows10

**Additional info**
See #18562 for some details

**Comment by DmitryArefiev** [comment]
Should be fixed in 4.0.1

**Comment by DaffodilAura** [comment]
I've experienced this too.  What info do you need?

**Comment by DmitryArefiev** [comment]
> I've experienced this too. What info do you need?

@DaffodilAura If you also reproduced that so no more info is needed I guess. Thanks!

**Comment by henkdegroot** [comment]
Today I got the 4.0.1 update on Windows and now I have 4.0.0 and 4.0.1 listed in windows apps listing:
![image](https://user-images.githubusercontent.com/13550012/212406714-c15c4074-e8eb-463c-8a51-78e58e4760fc.png)

First install was direct from the Muse Hub, update installed from the notification received when I started MuseScore.
Seems as if the Muse Hub installed version is not "recognized" as being the same software. 
Now got two icons for MS4 on my desktop. Both launch 4.0.1. Also when I launch MS from the Muse Hub, the 4.0.1 version is launched. 

If this is a different issue, please let me know and I will create a new github issue.

**Comment by henkdegroot** [comment]
Update on my previous comment, Muse Hub has now detected there is a newer version of Muse Score available. This resulted in another download and install. One icon removed from the desktop after this, so only 1 left and only 1 MuseScore 4 listed in the apps section. 

So seems to recover by itself once the Muse Hub update kicks in. Just annoying it performs another download and install.

**Comment by bkunda** [comment]
@DmitryArefiev @zacjansheski this issue is relatively old now. Can it please be re-tested for relevancy?

**Comment by henkdegroot** [comment]
The issue also exist when updating using the application instead of via the musehub. The recent 4.3.1 update did not download using the musehub, so when the application detected there was an update available, I completed the upgrade. Once done, I had two versions of MuseScore in the application list in Windows. Musehub also kept reporting a newer version was available. I manually removed the 4.3 0 version using the apps functionality in Windows.
Happy to report this as a separate issue if that would be better. Please let me know what you think.

**Comment by DominicMaas** [comment]
I think what might be happening here is the MuseScore inbuilt updater is updating as a user install, but Hub is updating / installing as a machine wide install. But not 100% sure.

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev @zacjansheski this issue is relatively old now. Can it please be re-tested for relevancy?

@bkunda The issue still here. But the problem occurs if update installation is made from a different source: e.g. **4.3.1 msi file** -> **4.3.2 via MuseHub** (and I think vice versa too)

**Comment by DominicMaas** [comment]
Narrowed down to Machine Installs vs User Installs. Hub gets confused between the two. Working on the best way forward here.

**Comment by DmitryArefiev** [comment]
Doesn't occur with MuseHub v2 (beta). 
Closing (for now)
