### ISSUE TITLE
[MU4 Issue] Playback Setup option in Mixer is disabled

### ISSUE THREAD

**Issue by jeetee** [musescore/MuseScore#15169]
**Describe the bug**
Playback Setup menu entry in the three-dots (...) menu at the top-right of the mixer is disabled.

**To Reproduce**
1. Launch MuseScore 4.0.0
2. Click on '...' on the top-right of the Mixer
3. "Playback Setup" menu option is disabled.

**Expected behavior**
The option is enabled

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Additional context**
The same option in the **View** menu *is* enabled and working

**Comment by MarcSabatella** [comment]
FWIW, it works as expected for me on Linux

**Comment by cbjeukendrup** [comment]
Isn't this a duplicate of #13787?

**Comment by jeetee** [comment]
Yes, same workaround confirmed too.
Somehow I missed it in my search, apologies.
