### ISSUE TITLE
[MU4 Issue] MuseScore gives me the finger when I undo deleting letters

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#15170]
**Describe the bug**
After deleting letters in a dynamics and undoing, I get a finger

**To Reproduce**
1. Create a dynamics text (like ppp)
2. Double click to go into edit mode
3. Delete a letter
4. Undo

**Expected behavior**
MuseScore should not give me the finger

**Screenshots**
[Issue.webm](https://user-images.githubusercontent.com/88136054/207647867-93bcab40-29a2-412e-bd1b-86360a7d92ff.webm)

**Platform information**
 - OS: Ubuntu 22.04 LTS

@Tantacrul FYI

**Comment by abariska** [comment]
Can't reproduce on Ubuntu 20.06

**Comment by sammik** [comment]
I can reproduce on Ubuntu Studio 22.04

**Comment by DmitryArefiev** [comment]
> Can't reproduce on Ubuntu 20.06 @DmitryArefiev could you check. As I know you also have Ubuntu 22

Yes, I **can repro** on my **Ubuntu 22.04.01**.

And it really gives the finger))))

![Screenshot from 2022-12-15 19-19-13](https://user-images.githubusercontent.com/90187801/207926624-f7b47929-37ce-4efe-a0de-bd083833b51f.png)

**Comment by sammik** [comment]
Also happens in MU3.

And not only in dynamics, but in any text, if You "insert special characters" -> "musical symbols" and than remove symbol and want undo, it doesnt bring back removed symbol, but replaces it by some other _non musical_ symbol.

**Comment by HemantAntony** [comment]
I'm working on this. Hope I can create a PR soon 🤞🏾

**Comment by abariska** [comment]
👉

**Comment by HemantAntony** [comment]
@abariska @DmitryArefiev I have a PR for this issue #15529. But it reverts a change made by @wizofaus in his PR #8815. Since its a large PR, I'm not sure why he would add this change

Also @sammik My PR should solve the bug you mentioned

**Comment by DmitryArefiev** [comment]
> @abariska @DmitryArefiev I have a PR for this issue #15529. But it reverts a change made by @wizofaus in his PR #8815. Since its a large PR, I'm not sure why he would add this change
> 
> Also @sammik My PR should solve the bug you mentioned

@HemantAntony I checked #15170 briefly on #15529, it seems to be fine. But it also should be reviewed before full testing. 

Thank you!

**Comment by abariska** [comment]
I will miss this issue 😄

**Comment by HemantAntony** [comment]
You're not alone 😁. Will remember this issue. Its my 100th merged PR :)

**Comment by Tantacrul** [comment]
Congrats!

Let us remember this issue by holding up our glasses. We wish you well!

**Comment by Jojo-Schmitz** [comment]
Apparently a similar issue with 3.x, not a finger but a wrongly styled dynamics glyph
