### ISSUE TITLE
[MU4 Issue] Frequent unexplained crashes while trying to set shortcuts (official release version)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#15171]
**Describe the bug**

I am getting frequent unexplained crashes when trying to set shortcuts in Preferences.

**To Reproduce**

1. Open MuseScore. It should open empty in the Home > Scores section
2. Choose Edit > Preferences > Shortcuts
3. Bring up the "Format style" option. Enter shortcut Ctrl+Shift+S. Press **Save** then **OK**.
4. Bring up the Page setting option. Set a shortcut of Ctrl+Shift+P
5. Bring up the list of intervals. Try and set a shortcut there.

This is not a definitive guide. However, IME, it is relatively easy to trigger a crash event if you continue plugging away setting new shortcuts. You will probably need to try all kinds of variations. Try mixing things up using SAVE and CANCEL and so on.

**Expected behavior**

No crashes when you set shortcuts.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472159, revision: github-musescore-musescore-5485621

**Comment by nutella511** [comment]
I'm also having this exact issue

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Comment by abariska** [comment]
Confirm. Also reproducible on macOS

**Comment by DmitryArefiev** [comment]
Fixed in #16132
