### ISSUE TITLE
[MU4 Issue] Muse Hub doesn't launch on macOS: "Unable to connect to helper, please contact support."

### ISSUE THREAD

**Issue by D-Tylr** [musescore/MuseScore#15176]
**Describe the bug**
Installed the new muse hub app today, but something strange is happening. I get an error saying "unable to connect to helper, please contact support." Every time I try to open muse hub it tries to install the helper but fails.
> I have stable internet
> I read something that said to "right click the hub logo and select reinstall helper" but that option doesn't exist.
> Sometimes I can get muse hub to open, but nothing loads and I think it's more of a glitch than properly opening up

**To Reproduce**
1. Download Muse Hub on mac system
2. Move Muse Hub to application folder as per installer
3. Open Muse Hub
4. Error as described above: "unable to connect to helper, please contact support."

**Expected behavior**
The program should download whatever the helper program is and operate normally.

**Platform information**
 - OS: MacOS 12.5.1

**Comment by cbjeukendrup** [comment]
Is it the first time you're installing Muse Hub, or did you already have it installed previously?

Does the error say anything more than "unable to connect to helper, please contact support."?

**Comment by D-Tylr** [comment]
<img width="255" alt="Screen Shot 2022-12-14 at 2 03 46 PM" src="https://user-images.githubusercontent.com/120594646/207689300-7ab3b29f-7488-42c8-8260-9140c90505da.png">

**Comment by gary-schiltz** [comment]
I have the same issue as described above. On Ventura 13.0.1

BTW, it seems weird reporting bugs in non-open-source software (MuseHub) on the repository for open source software (MuseScore).

**Comment by cbjeukendrup** [comment]
> <img alt="Screen Shot 2022-12-14 at 2 03 46 PM" width="255" src="https://user-images.githubusercontent.com/120594646/207689300-7ab3b29f-7488-42c8-8260-9140c90505da.png">

In fact, I'm having this too, after updating to 0.9.12 (and seemingly successfully using it for a while after installing the update). 

When I tried to launch MuseHub at some point, I was prompted for my password to install the helper (even though I had already successfully used the Hub after installing 0.9.12), and then it gave this time-out error message. 

I tried a few times, and sometimes the Hub did launch (without asking for password), but it wouldn't load any content. 

Then I clicked the "uninstall" button in the Hub, hoping that uninstalling and re-installing would fix it, but now I only get the time-out error.

It also looks like some people have reported the same on Discord: https://discord.com/channels/818804595450445834/818804595450445837/1052656422070013992

**Comment by cbjeukendrup** [comment]
Huh... Just tried it again, and now it launched one time without asking for password, loading only the logos of the four apps, but not the rest. 
Then quit and tried yet another time, and this time I did get a password prompt, and after that it also launched successfully and even seems to have loaded all content.
Then tried a third time and now it asks for password again and gives timeout... so it looks like it's doing something different on every launch!
Here are some logs, in case it helps: [Muse Hub logs 14 dec.zip](https://github.com/musescore/MuseScore/files/10231117/Muse.Hub.logs.14.dec.zip)

**Comment by iamtesch** [comment]
> I have the same issue as described above. On Ventura 13.0.1
> 
> BTW, it seems weird reporting bugs in non-open-source software (MuseHub) on the repository for open source software (MuseScore).

Definitely agreed!   In the Muse Hub application, you can click on the "contact support" icon; of course with installation issues this is not available :/

 In the meantime, feel free to report at https://musehub.zendesk.com -- here we have a support forum set up as well as resolutions for some common issues.

Thanks for the logs; I'm looking into the cause of this now.

**Comment by kolydart** [comment]
I had the same response, just after I had set a different download location in settings. 
I had to remove the com.muse.hub directory to make the app run again.
`sudo rm -r ~/Library/Containers/com.muse.hub`

**Comment by oporapunk** [comment]
> I had the same response, just after I had set a different download location in settings.
> I had to remove the com.muse.hub directory to make the app run again.
> `sudo rm -r ~/Library/Containers/com.muse.hub`
> Have in mind that after this command, all settings are deleted. So, please use with caution.

Same here...
Even if I try to download the library in an external drive, the download stays at 1% forever.

Is it possible to be related to external drive access maybe?

**Comment by kolydart** [comment]
The issue was resolved next day without any action from my part. It just worked.

**Comment by oporapunk** [comment]
> The issue was resolved next day without any action from my part. It just worked.

 I did what you said to solve my problem today, but with the expense of not being capable of installing the sounds outside my internal SSD. As soon as I try to change it, same thing happens.

**Comment by kolydart** [comment]
> > The issue was resolved next day without any action from my part. It just worked.
> 
> I did what you said to solve my problem today, but with the expense of not being capable of installing the sounds outside my internal SSD. As soon as I try to change it, same thing happens.

A workaround I tried was the following: move the Muse Sounds directory to the external drive and create a symlink to the new location. It is working fine, with one side effect: you have to have the external drive mounted all the time. If you open a score when the external drive is not mounted, all the playback instruments in the mixer are switched to "MS Basic" SoundFont; if you save the score and you want to use the Muse Sounds Instruments, you have to switch them back one by one.
The commands to move and create the symlink are the following:
`
# first, make sure musescore is not running
EXTERNAL_VOLUME=/Volumes/change_this_to_your_ssd_name
sudo mv -v ~/Library/Containers/com.muse.hub/Data/InstallData/Instruments ${EXTERNAL_VOLUME}/MuseSoundsInstruments;
ln -s ${EXTERNAL_VOLUME}/MuseSoundsInstruments ~/Library/Containers/com.muse.hub/Data/InstallData/Instruments;
`

**Comment by oktophonie** [comment]
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.
