### ISSUE TITLE
[MU4 Issue] Unable to copy text from text fields to clipboard

### ISSUE THREAD

**Issue by sherlockholmestech** [musescore/MuseScore#15186]
**Describe the bug**
Text from the score cannot be copied from text fields to the clipboard

**To Reproduce**
1. Create a empty score
2. Add a staff text (or anything that contains text)
3. Write some text into the text field
4. Try to copy with Ctrl + C or the context menu
5. Text cannot be pasted as it is not in the clipboard

Here is a minimum working example: 
[Untitled score.zip](https://github.com/musescore/MuseScore/files/10233803/Untitled.score.zip)

**Expected behavior**
Text copied should be added to the clipboard

**Screenshots**
Here is a video of the bug:

https://user-images.githubusercontent.com/63144250/207775124-4aa3c413-9839-4165-80bd-645b147ac451.mp4

**Platform information**
 - OS: OS: openSUSE Tumbleweed, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472159, revision: github-musescore-musescore-5485621

**Additional context**
NIL

**Comment by Eism** [comment]
We don't actually support context menu for text editing. This context menu is shown for the text object. This behavior from MU3.
Editing(copy/paste/select and etc) only works with shortcuts.

@Tantacrul FYI

**Comment by Tantacrul** [comment]
The MS3 behaviour is not good and we should improve upon it.

In any text editor, when you are actually editing text (which places an insertion point into the text field), the context menu should show unique options. In the case being shown here:

1. The user should be able to right click on the selected range of characters and copy them
2. The user should be able to paste wherever at the insertion point too
3. The context menu should only show options for the entire text object when the user 'clicks away' and the insertion point is no longer displaying

**Comment by Tantacrul** [comment]
@Eism - if you'd like a spec to be written to describe desired behaviour, let me know!
