### ISSUE TITLE
[MU4 Issue] Slurs will push accents into bowing markings

### ISSUE THREAD

**Issue by dxing97** [musescore/MuseScore#15184]
**Describe the bug**
Bowings should move up with accents when slurs are added. Instead they stay in place while accents get pushed up, usually causing them to overlap. 

**To Reproduce**
1. Create some notes at the top of the staff
2. Add accents and some sort of bowing to every note
3. Slur the notes

**Expected behavior**
Accents should not overlap bowings 

**Screenshots**
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/3182625/207752916-d753b0e4-d052-4b9b-a247-b9f4c0fddc9f.png">

**Platform information**
OS: macOS 12.5, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Comment by RobFog** [comment]
cc @oktophonie
