### ISSUE TITLE
[MU4 Issue] [MU3 Regression] Unable to select individual sounds in soundfonts (e.g. MS Basic)

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#15190]
**Describe the bug**
You are unable to select individual sounds within a soundfont.

**To Reproduce**
1. Load soundfont with multiple sounds (especially non-GM)
2. Observe no way to select individual sounds

**Expected behavior**
There should be a way to select individual sounds within the Mixer

**Screenshots**
Not really?

**Platform information**
 - OS: All

**Additional context**
I'm surprised I couldn't find an existing issue on here for this

**Comment by abariska** [comment]
@erinic04 There's no ability to change sounds for instruments because they use General Midi mapping standard and can't be remapped. But good news that it's possible to change sounds if using Muse Sounds or VST plugins.

**Comment by erinic04** [comment]
Is it planned for this to be fixed? It's quite a major hassle for people like me who use non GM soundfonts.

**Comment by abariska** [comment]
@Tantacrul please, answer to this question

**Comment by Gai-Luron** [comment]
Hello,
Use VST 3 sforzando plug-in
![image](https://user-images.githubusercontent.com/1835871/207941697-62edf99b-9f49-41b9-8314-8a6669ad7801.png)

![image](https://user-images.githubusercontent.com/1835871/207941805-a4411087-9c5f-49ff-b352-0bffd9c8e360.png)

**Comment by erinic04** [comment]
I am aware, it's just a workaround for something that should be possible natively (also I can't get sforzando on my Mac because it's a school computer)

**Comment by quotepilgrim** [comment]
This issue alone led me to keep using the latest MuseScore 3 version. Even if you're using a GM soundfont, you can't select alternative sounds for the drums, which most if not all GM soundfonts have.

**Comment by cuteoreo** [comment]
if musescore 4 can't do this i will forever use musescore 3

**Comment by MarcSabatella** [comment]
Not to worry, this limitation won’t exist forever.  If for some reason the ability to select individual sounds within Soundfonts is more important to you right now than scores that look their best or the ability to use VST or Muse Sounds, no reason you can’t continue to use MuseScore 3 temporarily.  Soon enough you’ll have the best of both worlds though, so no need to be so dramatic :-)

**Comment by cuteoreo** [comment]
sorry about that my brain went into auto mode

**Comment by Gai-Luron** [comment]
Hello, Yes MuseScore 4 is sometimes confusing. But even if it still has a lot of bugs, I force myself to use it, if only to report problems. I rant about the slow interface, but the software has huge potential. Marc is right to say that you should not worry, I use the nightly versions and I can assure you that the software evolves every day and very quickly. On the other hand, I fully understand your reaction because we are moving from a stable and finalized version to a version which sometimes introduces new problems. Let's be patient and we will have a powerful tool to create our scores. ;-)

**Comment by ChapeauCanotier** [comment]
Sorry if this is an unhelpful message but I'm curious when this will be fixed? I'm very excited to use MS4 because musesounds is incredible but as for drums, guitar, etc. the default fonts are awful

**Comment by jeetee** [comment]
This can be considered fixed by #18976 and as such will be available with the release of 4.2
