### ISSUE TITLE
[MU4 Issue] Linux VST Plugin Detection

### ISSUE THREAD

**Issue by ltrel** [musescore/MuseScore#15195]
**Describe the bug**
Detection of VST plugins on Linux does not appear to work

**To Reproduce**
1. Go to mixer
2. Click the sound drop down
3. VST plugins installed on the system are not listed

**Expected behavior**
Installed VST plugins should be discovered and listed in the sounds drop down

**Screenshots**
![image](https://user-images.githubusercontent.com/79512656/207843020-78fc76bf-43b5-4441-8224-143fb271aa13.png)

**Platform information**
 - OS: Linux

**Additional context**
The plugins are being detected by Ardour on the same system, so whatever they are doing works.
![image](https://user-images.githubusercontent.com/79512656/207843646-a09f2196-aaa1-47f9-a8bc-410e729d7542.png)

**Comment by michele-perrone** [comment]
The VST3 feature seems to be missing altogether from the Linux build.

Unlike in Windows, if you go to Edit -> Preferences -> General -> Folders, there's not "VST3" folder to set:

![Screenshot_20221215_164637](https://user-images.githubusercontent.com/38738346/207905316-58531a2e-f9d0-41e2-bfdb-2dae3af8130b.png)

There's only "Plugins", but that's for MuseScore plugins and not for VST3.

Is there any reason why is this missing?

**Comment by michele-perrone** [comment]
OK, I found the relevant issue: https://github.com/musescore/MuseScore/issues/11689

This issue should be closed.

**Comment by ltrel** [comment]
Thanks
