### ISSUE TITLE
[MU4 Issue] Window doesn't fit the screen completely when 150%

### ISSUE THREAD

**Issue by aaronsendra** [musescore/MuseScore#15201]
**Describe the bug**

The MuseScore window does not fit the screen completely when the screen scale configuration is at 150% in Windows 11. It looks like there is a small space between the screen limits and the MuseScore window border. In other cases, like scale at 125% it does not happen.

**Screenshots**

![2022-12-15-17-17-10](https://user-images.githubusercontent.com/46270385/207913018-c2a7f4d6-879f-44ee-96ca-745eb3127361.gif)

**Platform information**

 - OS: Windows 11 22H2 22621.963
 - Screen scale: 150%

**Comment by cbjeukendrup** [comment]
This looks like a duplicate of #12786, isn't it?

**Comment by DmitryArefiev** [comment]
Fixed in #15151

**Comment by DmitryArefiev** [comment]
Retested on Win10 with 4.0.2 RC build - **Doesn't occur**
