### ISSUE TITLE
[MU4 Issue] [MSVC] MuseScore failed to build due to error C2065 and error C2275 with msvc on Windows

### ISSUE THREAD

**Issue by Zhaojun-Liu** [musescore/MuseScore#15216]
**Describe the bug**
Hi, the MSVC team updated the commit of MuseScore for RWC testing recently. It built failed due to the below error. Could you please  look into this issue? Thanks.
```
F:\gitP\musescore\MuseScore\src\framework\audio\internal\platform\win\wasapitypes.h(95,13): error C2065: 'is_guid_of': undeclared identifier (compiling source file F:\gitP\musescore\MuseScore\build_amd64\src\framework\audio\CMakeFiles\audio.dir\Unity\unity_1_cxx.cxx) [F:\gitP\musescore\MuseScore\build_amd64\src\framework\audio\audio.vcxproj]
         F:\gitP\musescore\MuseScore\src\framework\audio\internal\platform\win\wasapitypes.h(95,26): error C2275: 'IMFAsyncCallback': expected an expression instead of a type (compiling source file F:\gitP\musescore\MuseScore\build_amd64\src\framework\audio\CMakeFiles\audio.dir\Unity\unity_1_cxx.cxx) [F:\gitP\musescore\MuseScore\build_amd64\src\framework\audio\audio.vcxproj]
         F:\gitP\musescore\MuseScore\src\framework\audio\internal\platform\win\wasapitypes.h(95,46): error C2275: 'IUnknown': expected an expression instead of a type (compiling source file F:\gitP\musescore\MuseScore\build_amd64\src\framework\audio\CMakeFiles\audio.dir\Unity\unity_1_cxx.cxx) [F:\gitP\musescore\MuseScore\build_amd64\src\framework\audio\audio.vcxproj]

```
**To Reproduce**
1. Open VS2019 x64 Native Tools command.
2. git clone https://github.com/musescore/MuseScore F:\gitP\musescore\MuseScore
3. xcopy F:\gitP\musescore\dependencies F:\gitP\musescore\MuseScore\dependencies (the dependcies is unziped from [dependencies.7z](https://s3.amazonaws.com/utils.musescore.org/dependencies.7z))
4. mkdir F:\gitP\musescore\MuseScore\build_amd64 and cd F:\gitP\musescore\MuseScore\build_amd64
5. set PATH=F:\tools\qt5\qt\5_15_2\msvc2019_64\bin;%PATH%
6. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBUILD_UNIT_TESTS=ON -DCMAKE_BUILD_TYPE=Release ..
7. msbuild /m /p:Platform=x64 /p:Configuration=Release mscore.sln /t:Rebuild

**Expected behavior**
Build successful.

**Screenshots**
N/A

**Platform information**
 - OS: Window Server 2022
 - VS: VS2019 (16.11.20)
 - Commit of MuseScore: 93a915f8dff4aebcd49ef7f146b2698265da42d6

**Additional context**
log: [build.log](https://github.com/musescore/MuseScore/files/10243018/build.log)

**Comment by FigmentBoy** [comment]
Make sure you are using the most recent Windows 10/11 Build Tools from the Visual Studio installer

**Comment by Zhaojun-Liu** [comment]
> Make sure you are using the most recent Windows 10/11 Build Tools from the Visual Studio installer

@FigmentBoy Thanks for your reply. I updated the value of -DCMAKE_SYSTEM_VERSION in step 6 above to be 10.0.22618.0, it built successfully. Thanks.
