### ISSUE TITLE
[MU4 Issue] Continuous mode smooth scrolling (during Playback)

### ISSUE THREAD

**Issue by TheChilliPL** [musescore/MuseScore#15212]
**Edited by** @DmitryArefiev 

**Describe the bug**
MuseScore 4 doesn't seem to have the `smoothPan/enabled` advanced option of MuseScore 3 

**To Reproduce**
1. Go to **Preferences>Advanced**

**Expected behavior**
The option should be there and be functional.

**Screenshots**

https://user-images.githubusercontent.com/90187801/234865116-2edbacfe-ea3e-4293-b982-2839969ffa64.mp4

**Platform information**
 - OS: Windows

**Additional context**
From https://musescore.org/en/node/340597 :

> Smooth panning is not available anymore, annoying for choir singers that would like to see whats next and not wait for a pageturn during playback
> 
> For our (older) choirmembers **this is a blocker to work with version 4**, I understand for the development of this version missing this option is even les then a minor . But perhaps there is a quickfix or workaround that can help.

**Comment by Mikaa404** [comment]
Same here. I'm using macOS 13.1, MuseScore 4.0.1.230121751.

**Comment by Jojo-Schmitz** [comment]
This is a regression actually. Came up in https://musescore.org/en/node/340597 and https://musescore.org/en/node/346625

**Comment by Daniel-R15** [comment]
Came up again on the Feature Request forum on musescore.org:
"How I make the Blue bar be stable or static while is scroling"
https://musescore.org/en/node/348229

**Comment by theadventuresofsirautismo** [comment]
I can see this has been given high priority, which is much appreciated; this feature will make recording short form content much more straightforward!

**Comment by antonioleal** [comment]
This single feature missing is the reason I'm still on MuseScore 3.6.3...

**Comment by MarcSabatella** [comment]
@bkunda - any chance of finding a way to make this more discoverable than burying it in the "advanced" page of preferences?  That's where it was in MU3 but mostly out of laziness really, plus it was kind of considered experimental.

**Comment by joaolimapiano** [comment]
Hello, Lennysme, it should be already working under preferences -> advanced -> smooth paning

________________________________________________
João G. A. Lima
Piano Popular Brasileiro
Pesquisador de expertise e cognição musical
Doutorando na Universidade Federal do Paraná
GRUME (Grupo de Pesquisa Música e Expertise)

________________________________
De: lennysme ***@***.***>
Enviado: sábado, 28 de fevereiro de 2026 14:40
Para: musescore/MuseScore ***@***.***>
Cc: joaolimapiano ***@***.***>; Manual ***@***.***>
Assunto: Re: [musescore/MuseScore] [MU4 Issue] Continuous mode smooth scrolling (during Playback) (Issue #15212)

[https://avatars.githubusercontent.com/u/143040963?s=20&v=4]lennysme left a comment (musescore/MuseScore#15212)<https://github.com/musescore/MuseScore/issues/15212#issuecomment-3977480587>

February 2026, still no smooth panning option for MS4.
