### ISSUE TITLE
[MU4 Issue] Can't change playback settings for dynamic markings unlike MU3.6

### ISSUE THREAD

**Issue by rich777300** [musescore/MuseScore#15215]
**Describe the bug**
I cannot change playback settings for dynamic markings (ie change velocity, dynamic to affect only one stave). 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open, say, a piano score
2. Apply a dynamic
3. Click on that dynamic and view Properties panel
4. No playback settings available to change (button greyed out)

**Expected behavior**
I can change the playback settings for that dynamic marking (ie change velocity, affect only one stave)

**Screenshots**
![image](https://user-images.githubusercontent.com/102642087/208000564-8b18bc4c-e0a3-4d48-8963-6387f52acd6a.png)

**Platform information**
 - OS: Windows 10 Pro 64-bit

**Additional context**
This was possible to do in MU3.6...I would give each hand a different dynamic marking and during playback, each dynamic marking would only affect one stave. 

Since we can't do that anymore, the playback doesn't work properly either since each dynamic marking would be affecting the entire score and only one can apply at a time.

(I hope this is the right place to post this, if not please let me know and I'll correct it)

**Comment by Fristover** [comment]
this is known and intended while a new feature to control dynamics is being made (something like a "velocity lane")

you can still access velocity settings on notes, just not on dynamics

**Comment by MarcSabatella** [comment]
In the future, the best place to ask questions about what is or is not intended to be supported would be the Support forum on musescore.org.  Then if it is confirmed there that something is actually a bug, *then* you would create an issue here.

**Comment by oktophonie** [comment]
Closing; the dynamics-per-hands issue still exists as https://github.com/musescore/MuseScore/issues/15133
