### ISSUE TITLE
[MU4 Issue] CC signals from MIDI controller are not correctly recognized in MIDI device mapping

### ISSUE THREAD

**Issue by Felge-Schneider** [musescore/MuseScore#15219]
**Describe the bug**
When using a MIDI keyboard with buttons that are assigned to CC signals, the MIDI device mapping only recognize the signal as "CC 0", although another (e.g. CC 24) is assigned. This happens for every trigger pad I tested.
The bug was confirmed in the German Musescore forum section.

**Hardware**
- MIDI keyboard: M-Audio Oxygen pro mini

**Expected behavior**
The CC signals should be distinguished properly

**Platform information**
 - OS: W10

**Comment by abariska** [comment]
Confirm that this issue reproduces on Win 11 and Ubuntu 20

**Comment by Skelbti** [comment]
Same thing here with an M-Audio Axiom 61 mk II and the lastest version of MS4.

**Comment by Julien441Lab** [comment]
Same here with a Novation Launchkey Mini MK3, on OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Comment by lachbaer** [comment]
I think that might come from the lines at 
https://github.com/musescore/MuseScore/blob/de760621dccd3b05195bf31f1326b5e326033f8d/src/framework/midi/midievent.h#L769

This leads to skip (`break`) the assignment of the controller index to the newly created event if the controller is not one of values in the set.
