### ISSUE TITLE
[MU4 Issue] System Dividers (still) collide (with text) 

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#15213]
![3](https://user-images.githubusercontent.com/78870770/207997000-f1adcaf0-258e-467e-ab62-3c7b1044c696.JPG)

![4](https://user-images.githubusercontent.com/78870770/207997129-c06fdf2a-6336-45ef-88a9-c151499d806e.JPG)

**Comment by cbjeukendrup** [comment]
I consider this a duplicate of #14966, which is temporarily closed to be reopened in 4.x times, which is when system dividers will receive an overhaul.
