### ISSUE TITLE
[MU4 Issue] Playback always starts from beginning if playback runs to the end

### ISSUE THREAD

**Issue by jcourtne** [musescore/MuseScore#15228]
**Describe the bug**
If you playback a piece all the way to the end, playback will always start from the beginning, even if you select a measure in the middle of the piece after playback has finished.

**To Reproduce**
1. Starting from any point in the piece, playback the piece all the way to the end.
2. Select a measure in the middle of the piece.
3. Start playback.
4. Playback will start from the beginning.

**Expected behavior**
Playback should start from the selected measure.

**Screenshots**

https://user-images.githubusercontent.com/1214737/208124096-ee6da717-2e87-4e79-b2ab-9f75927ee375.mp4

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Comment by MarcSabatella** [comment]
@Tantacrul this one has got to be a trivial fix and would be worth prioritizing for a patch

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/15048
