### ISSUE TITLE
Feature request: Windows Store

### ISSUE THREAD

**Issue by marczellm** [musescore/MuseScore#15223]
MuseScore 3 was released on the Windows Store and I immediately switched to using the Store version. I strongly prefer apps using the OS native update mechanism instead of having their own updaters, for several reasons:
- The OS can optimally choose the best time to non-disruptively update stuff because it knows what my "active hours" are, it can balance app updates with OS updates, anti malware scans, disk defragmentation, telemetry scans and other scheduled tasks
- Bespoke updaters use additional resources
- Bespoke updaters can have separate bugs

 But I was "left in the dust" because after 3.4 the Store didn't receive updates. I tried to raise the topic several times on the website, but after a long time it became clear that only the internal development team can publish MuseScore on the Store, which the people answering on the forums are not members of.

So this is an attempt to reach the actual development team and get a definitive answer. Will the Store version of MuseScore 3.4 receive an update to version 4? Can I do anything or help out in any way to make that happen? For example other OSS projects like WinSCP or LibreOffice are using a model where they are selling the app on the Store, for money, in exchange for the convenience of OS managed automatic updates. I would certainly be willing to pay for that here too.

**Comment by Jojo-Schmitz** [comment]
Relates to https://musescore.org/en/node/313298

**Comment by mmarczell-graphisoft** [comment]
Audacity has this note in the Store:
![image](https://user-images.githubusercontent.com/72875131/230337125-19b4abec-6caf-45c0-845a-a9b31c07e27a.png)
This is a newer, different mode of Store distribution, under which even if I install it from the Store, I don't get automatic updates from the Store. (After the installation, the Store "forgets" that I got the app from there.) As per my above comments, I consider OS managed automatic updates the main benefit of Store based installation.

**Comment by Jojo-Schmitz** [comment]
As per @Tantacrul Mu4 is now in the score (at https://apps.microsoft.com/store/detail/musescore/XP89BN2QWZXG3T), so I guess we can close this issue?

**Comment by marczellm** [comment]
In my original comment, the reason I requested MS to be available in the Windows Store was to have OS managed automatic updates. This is still not the case but I opened a separate feature request with a different name, for clarity.

https://github.com/musescore/MuseScore/issues/17359
