### ISSUE TITLE
[MU4 Task] New dialogs for corruption warnings

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#15226]
**Task description**
This task would resolve the issues in #11807 

There are two variations of the same dialog to be implemented.

1. When the user attempts to open a corrupted file, and the file _can still be opened_

<img width="527" alt="Group 198" src="https://user-images.githubusercontent.com/86290556/211331237-a8ff4bb5-d4c7-4df6-8b77-da7133dbfb0d.png">

<img width="527" alt="Expanded" src="https://user-images.githubusercontent.com/86290556/211331268-2707d398-ad4f-4903-a8fa-a6ca1e6d4c31.png">

<img width="527" alt="Expanded1" src="https://user-images.githubusercontent.com/86290556/211331289-fff5b732-e85b-4713-ab57-c882121c56bd.png">

2. When the user attempts to open a corrupted file, and the file _cannot be opened_

<img width="527" alt="Group 1598" src="https://user-images.githubusercontent.com/86290556/208117493-c9fa2928-b688-4d97-b8a2-89843e40c8b5.png">

<img width="527" alt="Expanded" src="https://user-images.githubusercontent.com/86290556/208117510-7aec00fc-be8c-4515-8a33-d8e5ccf5e14a.png">

(In this case, **Get help** redirect to [the musescore.org support forum](https://musescore.org/en/forum/6)).

Full UX specification has been sent to @RomanPudashkin for implementation

@Tantacrul @oktophonie @abariska FYI

**Comment by eitanmuir** [comment]
Noting that in Windows 10 there is no option to Show Details - please add this feature too as restarting a whole score is a bit of a headache!

**Comment by cbjeukendrup** [comment]
@bkunda One thought about this design: it feels a little bit random to me that this dialog mentions musescore.com. The fact that uploading might not work properly is just one small aspect. Something like the following would be more complete and informative:

> **File "The_Avengers_Theme_Song_full_orchestra.mscz" is
> corrupted and may contain errors**
> 
> This can cause MuseScore to malfunction and might lead to crashes. 

(You can probably find a nicer wording for this.)

If we really want, we could add "In particular, saving to musescore.com may fail unless these errors are resolved."

**Comment by sam-the-programmer** [comment]
We need a show details feature on Musescore 4 when a file is corrupted.

**Comment by cbjeukendrup** [comment]
> @bkunda One thought about this design: it feels a little bit random to me that this dialog mentions musescore.com. The fact that uploading might not work properly is just one small aspect. Something like the following would be more complete and informative:
> 
> > **File "The_Avengers_Theme_Song_full_orchestra.mscz" is
> > corrupted and may contain errors**
> > This can cause MuseScore to malfunction and might lead to crashes.
> 
> (You can probably find a nicer wording for this.)
> 
> If we really want, we could add "In particular, saving to musescore.com may fail unless these errors are resolved."

@bkunda Friendly bump on this comment :)

**Comment by bkunda** [comment]
Thanks @cbjeukendrup, this makes perfect sense. 
I'll amend the mockups now.

**Comment by bkunda** [comment]
I've updated the messaging of the first dialog in the issue description: basically, I've shortened the header text by removing the reference to "errors", and have put this instead in the body text. I think it's wise to not limit the scope of potential "malfunctions", and I also don't think it's necessary to alarm the user _too much_ by mentioning crashes. Also, the detail about "saving to musescore.com" can, I think, safely be covered within the scope of "...could cause MuseScore to malfunction". 
Thanks, as always, for your input on this @cbjeukendrup!

**Comment by cbjeukendrup** [comment]
That looks good to me! 

Actually I had one more thought: instead of "may contain errors" we can just say "contains errors". That's simply the definition of being corrupted, so there's no uncertainty. That's a bit of a nitpick though, so not sure if it's worth the efforts of rendering the mockups yet again...

And then I have an unimportant cosmetic suggestion for the "Error details have been copied to the clipboard" message: instead of showing yet another popup, we could show it a bit more subtly next to the button itself. Here's a very quick and rough mockup:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/48658420/211296354-522ad66a-c917-45c5-bff8-84258f638b59.png">

**Comment by RobFog** [comment]
Yeah, would be nice to avoid the popup.

**Comment by bkunda** [comment]
I cannot disagree with any of your suggestions @cbjeukendrup 🙂

**Comment by bkunda** [comment]
@cbjeukendrup Issue description updated accordingly. Will send you link to Figma files separately.

**Comment by cbjeukendrup** [comment]
@RomanPudashkin Please let me know if you are working on this or if you would like me to do it in a follow-up PR :)
