### ISSUE TITLE
[MU4] Not running on Ubuntu 18.04

### ISSUE THREAD

**Issue by antonio-petricca** [musescore/MuseScore#15220]
Hi, unfortunately it does not run on Ubuntu 18.04.

Here is the output:

>  $ ./MuseScore-4.0.0-x86_64.AppImage 
/usr/lib/x86_64-linux-gnu/libjack.so.0
/usr/lib/x86_64-linux-gnu/libnss3.so
/tmp/.mount_MuseScvgwfbz/bin/mscore4portable: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_MuseScvgwfbz/bin/mscore4portable)
/tmp/.mount_MuseScvgwfbz/bin/mscore4portable: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_MuseScvgwfbz/bin/mscore4portable)
/tmp/.mount_MuseScvgwfbz/bin/mscore4portable: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_MuseScvgwfbz/bin/../lib/libsndfile.so.1)
/tmp/.mount_MuseScvgwfbz/bin/mscore4portable: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_MuseScvgwfbz/bin/../lib/libFLAC.so.8)

I tried building it on my own, but it fails because **Qt 5.15** cannot be installed on my **Ubuntu 18.04**.

How could I solve it?

Thank you so much!

**Comment by jeetee** [comment]
Ubuntu 18.04 comes with glibc 2.27. You could attempt upgrading that to 2.29 manually (but take care to not break dependencies) or simply update your Ubuntu to 22.04 which is also an LTS release.

**Comment by antonio-petricca** [comment]
I cannot harm my PC upgrading, I use it for my job too.

**Comment by jeetee** [comment]
Please notify your job that 18.04 has entered its last phase of maintenance before it is EOL (Canonical will kill it on April 30, 2023).
If they don't want to jump to the current LTS (22.04) they should at the very least consider moving to 20.04. Ubuntu LTS releases have a default maintenance cycle of 5 years (https://ubuntu.com/about/release-cycle).

What we did here at one of my clients was to update to 22.04 and for one specific package run 18.04 in a VM until it got ported over.

**Comment by zacjansheski** [comment]
Closing this, we are unable to support Ubuntu 18.04

Thank you @jeetee for sharing advice on this issue.
