### ISSUE TITLE
[MU4 Issue] Applying "Break inner beams" over rest only creates a "joined beam"

### ISSUE THREAD

**Issue by DavidMcCaulley** [musescore/MuseScore#15229]
**Describe the bug**
When applying any of the "break inner beam" options from the **palettes** over a rest, the visual result isn't that the beam goes over the rest with a beamlet in the correct place, but that the entire beam is joined over the rest (as if I had applied the "join beams" option). 

**To Reproduce**
1. Enter a 16th note, followed by a 16th rest and two more 16th notes.
2. Click on the rest and try to apply the "break inner beams (eigth) option from the **palettes**
3. It looks as if only the "join beams" option has been applied

**Expected behavior**
The beam should look as it was in MuseScore 3.6 when applied with the same palette option. There is a workaround I found (see video below) using the properties panel, but this is quite time consuming.

**Screenshots**
The desired outcome when using the palettes:
<img width="262" alt="CorrectBeamBreak" src="https://user-images.githubusercontent.com/31858876/208130054-d6f4ea9e-6d28-487f-b397-56d24c47f886.png">

Video of the actual result (including the workaround):

https://user-images.githubusercontent.com/31858876/208130542-62a7ef7e-3dfa-4a98-9053-7066e851b304.mp4

**Platform information**
OS: macOS 12.0, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Comment by abariska** [comment]
@oktophonie Please, take a look
