### ISSUE TITLE
[MU4 Issue] Measure repeats ignore dynamics

### ISSUE THREAD

**Issue by lucyydotp** [musescore/MuseScore#15232]
**Describe the bug**
Dynamics are ignored with bar repeats.

**To Reproduce**
1. Create a score with any instrument
2. Notate a measure containing dynamics with a single measure repeat immediately after. Screenshot attached below.
3. Play from beginning and observe how measure 2 is played pianissimo.

**Expected behavior**
Dynamics attached to notes on the first measure are respected when played on the second measure.

**Screenshots**
<img width="327" alt="image" src="https://user-images.githubusercontent.com/35287819/208153373-763b6036-6d06-4b31-9854-323a6411bacc.png">

**Platform information**
 - OS: macOS Ventura 13.1
 
**Additional context**

**Comment by DmitryArefiev** [comment]
Fixed in #20598
