### ISSUE TITLE
[MU4 Issue] Crash when opening (generating) parts in score from "Treble clef" or "Bass clef" template

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#15237]
**To Reproduce**
1. Create score from Treble Clef or Bass Clef template
2. Open Parts dialog
3. Select the "Piano" part (the only one)
4. Open it
-> CRASH

**Additional context**
Fix coming in a few minutes

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12
