### ISSUE TITLE
[MU4 Issue] Velocity ignored for notes with cross notehead (soundfonts)

### ISSUE THREAD

**Issue by djfun** [musescore/MuseScore#15243]
**Describe the bug**
When using SoundFonts for a vocal type instrument (for example Alto), the playback for notes with a cross as notehead is louder than for other notes.

**To Reproduce**
1. Create a new score with a vocal instrument (for example Alto)
2. Enter multiple notes
3. Change the notehead for one of the notes to a cross
4. In the mixer panel, select MS Basic or any other SoundFont for the vocal instrument
5. Play back the notes
6. Observe how the note with the cross notehead is much louder than the others

**Expected behavior**
All notes are played at the same volume

**Platform information**
 - OS: Linux

I also tried changing the velocity (where I also encountered #13476), but even with a velocity of 0, the note is louder than the rest.

**Comment by djfun** [comment]
`src/framework/mpe/resources/general_voice_articulations_profile.json` is missing a definition for `CrossNote`

**Comment by zacjansheski** [comment]
I wonder if there is any relation to https://github.com/musescore/MuseScore/issues/16389
