### ISSUE TITLE
[MU4 Issue] Alto saxophone playback bug

### ISSUE THREAD

**Issue by AlmogDob** [musescore/MuseScore#15247]
**Describe the bug**
Notes sometimes get an accent for no apparent reason.

like the note in the image 
![image](https://user-images.githubusercontent.com/120760400/208210511-2032ac13-7e6a-44bf-a762-0a56d212d4de.png)

**Comment by zacjansheski** [comment]
Is this still actual?  Is there any additional info to reproduce?  

Uploading video1289398359.mp4…

**Comment by zacjansheski** [comment]
Closing
