### ISSUE TITLE
[MU4 Issue] Muse Hub not installing on Windows 11

### ISSUE THREAD

**Issue by N0tAnaNT27** [musescore/MuseScore#15240]
**Describe the bug**
When I attempt to open "Muse_Hub.exe", a pop up dialogue shows saying, "Unable to install Muse Hub, please try again. Check the logs for more information. 

AppX Deployment operation failed for package Muse.MuseHub_1.0.0.624_x64__rb9pth70m6nz6 with error 0x80073D19. The specific error text for this failure is: Deployment Add operation with target volume C: on Package Muse.MuseHub_1.0.0.624_x64__rb9pth70m6nz6 from:  (MSIX_MUSEHUB.MSIX)  failed with error 0x80073D19. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues."

**To Reproduce**
1. Click on 'Muse_Hub.exe'
2. See error

**Expected behavior**
Muse Hub would begin downloading or launch. 

**Screenshots**
<img width="307" alt="image" src="https://user-images.githubusercontent.com/120751733/208182679-45364022-0150-477e-a25f-5c4e2bdb151d.png">

**Platform information**
 - OS: Windows 11

**Additional context**
I initially received the error of Windows App SDK runtime not downloading, but I managed to install Visual Studio 2022, after which I received this error message. Sorry if this is just an issue with me!

**Comment by cbjeukendrup** [comment]
@DominicMaas This looks like one for you again :)

**Comment by DominicMaas** [comment]
Slowly tracking down these MSIX errors!

@N0tAnaNT27 I know it's cliché, but can you try restarting your computer and trying again?

**Comment by DominicMaas** [comment]
If the restart doesn't work, do the following paragraphs sound applicable to you?

> The deployment operation was blocked because Special profile deployment is not allowed. Please try logging into an account that is not a Special profile. You can try logging out and logging back into the current account, or try logging into a different account.

> By default, Windows blocks deployment operations on special profiles. The term ‘special profile’ will cover roaming profiles, mandatory and super-mandatory profiles, temporary profiles and guest account profiles. Usually, it is recommended that you don’t allow deployment on such user profiles. You can find more information about [AllowDeploymentInSpecialProfiles here](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-admx-appxpackagemanager).

**Comment by N0tAnaNT27** [comment]
Hi, thanks for the help. I think the problem was that I don't have admin perms on my account (I'm like 14), starting it on my dad's account worked perfectly! Thanks for the help anyway.
