### ISSUE TITLE
[MU4 Issue] Holding mouse down on button for too long prevents it from being pressed

### ISSUE THREAD

**Issue by Nathan-Fenner** [musescore/MuseScore#15258]
**Describe the bug**
If I click a button, it works. But if I hold down the left mouse button for (e.g.) 1 second without moving off of the button, letting go does not click the button. The threshold seems to be somewhere around 0.25 seconds; if I let go soon enough, it works; if I'm too slow, the button ignores the press.

**To Reproduce**

1. Go to `File > New ...`
2. Move the mouse cursor to hover over the "Cancel" button
3. Hold the left mouse button down for 1 second without moving the mouse cursor
4. Let go

**Expected behavior**
Pressing the mouse down on a button and letting go without moving the mouse off of the button should activate it.

There seems to be some minimum amount of time after which clicking stops working. It seems to be about 0.25 or so seconds but I can't measure precisely.

**Screenshots**

**Platform information**
 - OS: Windows 11
 - `Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621`

**Additional context**
The "Cancel" button is the easiest to reproduce with but it seems to affect all of the "dialog" buttons (e.g. "Next"/"Back" right next to it, or "Done").

**Comment by zacjansheski** [comment]
Is this still actual? (I'm not able to reproduce)

**Comment by cbjeukendrup** [comment]
This might be related to #16012, which has been fixed.

**Comment by Nathan-Fenner** [comment]
I can confirm that it's fixed. Thanks!
