### ISSUE TITLE
[MU4 Issue] Crash When Selecting or Hearing Playback From Measures

### ISSUE THREAD

**Issue by AnibruNotro** [musescore/MuseScore#15252]
**Describe the bug**
The program crashes when any note or rest in measures 6-9 are selected, or this section is reached in playback. This includes when attempting to export the audio.

Link to download file here: https://drive.google.com/drive/folders/1xUNaV8MRng3_U7VLtqE9pRPjZfBqDBWA?usp=share_link

**To Reproduce**
1. Download the attached .mscz file from Google Drive
2. Open in Musescore 4
3. Select any rest or note from measures 6 - 9 or attempt playback
4. See error (crash)

**Expected behavior**
Select measures, notes, rests
Hear playback

**Platform information**
 - OS Windows 10, latest MU4 build.

**Additional context**
The problem occurs on a score created in Musescore 3.6, and recently ported over to MU4.

**Comment by zacjansheski** [comment]
Is this still actual?

I am able to play mm6-9

The score does have a corruption message...
Incomplete measure: Part score: Drumline, measure 1, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 1, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 1, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 11, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 11, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 11, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 12, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 12, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 12, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 13, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 13, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 13, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 14, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 14, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 14, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 15, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 15, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 15, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 16, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 16, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 16, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 17, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 17, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 17, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 18, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 18, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 18, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 19, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 19, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 19, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 20, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 20, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 20, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 21, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 21, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 21, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 22, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 22, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 22, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 23, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 23, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 23, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 24, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 24, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 24, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 25, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 25, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 25, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 26, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 26, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 26, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 27, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 27, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 27, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 28, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 28, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 28, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 29, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 29, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 29, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 30, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 30, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 30, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 31, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 31, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 31, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 32, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 32, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 32, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 33, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 33, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 33, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 34, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 34, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 34, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 35, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 35, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 35, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 36, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 36, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 36, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 37, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 37, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 37, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 38, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 38, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 38, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 39, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 39, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 39, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 40, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 40, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 40, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 41, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 41, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 41, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 42, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 42, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 42, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 43, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 43, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 43, staff 3. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 45, staff 1. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 45, staff 2. Found: 0/1. Expected: 3/4.
Incomplete measure: Part score: Drumline, measure 45, staff 3. Found: 0/1. Expected: 3/4.

**Comment by zacjansheski** [comment]
Closing
