### ISSUE TITLE
[MU4 Issue] Not restoring system barline after toggling

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#15253]
**Describe the bug**
MuseScore does not restore system barline after toggling the setting in Staff/Part properties dialog.

**To Reproduce**
See video.

https://user-images.githubusercontent.com/102702868/208219235-f86353ef-efc4-47ec-9f85-798a6d2a50c5.mp4

**Platform information**
 - OS: Windows 11

**Comment by oktophonie** [comment]
Not that after save/reload, the barline will reappear.
