### ISSUE TITLE
[MU4 Issue] Cutaway checkbox is always unchecked

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#15254]
**Describe the bug**
Regardless of whether the staff is cutaway or not, the cutaway checkbox is always unchecked when the Staff/Part properties panel is opened.

**To Reproduce**
See video.

https://user-images.githubusercontent.com/102702868/208219377-3860f5f8-29c0-49dc-be05-158be824aef5.mp4

**Expected behavior**
The checkboxes should reflect the current state.

**Platform information**
 - OS: Windows 11

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12
