### ISSUE TITLE
[MU4 Issue] Portamento glissandos break playback for random assortment of instruments (synths, keyboards, and voices)

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#15268]
**Describe the bug**
Portamento glissandos cause the note they are attached to to ring out until the note is played again for a seemingly random assortment of instruments. Saxophone, cornet, and accordion all work fine, but synths, keyboards, and voices don't

**To Reproduce**
1. Create a score with portamento glissandos for one of the affected instruments
2. Hear glissando breaking everything

**Expected behavior**
The glissando should not cause the notes to ring out indefinitely

**Screenshots**

https://user-images.githubusercontent.com/21023353/208237548-f7ce42fd-ca2e-4460-9e4a-0c17755fb92a.mp4

https://user-images.githubusercontent.com/21023353/208237551-8571ef68-0242-4846-bc84-e77646004555.mp4

https://user-images.githubusercontent.com/21023353/208237552-753825d8-2338-4185-8284-fe82df55ecd8.mp4

https://user-images.githubusercontent.com/21023353/208237556-8acae5bb-983d-4e10-abd8-851a1ef1115f.mp4

https://user-images.githubusercontent.com/21023353/208237565-bca350bf-398b-462e-9e15-ab69fda2c4a3.mp4

**Platform information**
 - OS: Reported on Windows

**Additional context**

**Comment by djfun** [comment]
see #12838

**Comment by djfun** [comment]
`src/framework/mpe/resources/general_voice_articulations_profile.json` is missing a definition for `ContinuousGlissando`

**Comment by Jojo-Schmitz** [comment]
Any progress on this? Just came up again in https://musescore.org/en/node/345691, and  the above comment seems to indicate where exactly the problem lies?

**Comment by DmitryArefiev** [comment]
Fixed in #16597
