### ISSUE TITLE
[MU4 Issue] Can't change "Cloud Scores" location in preferences, "Scores" location isn't respected

### ISSUE THREAD

**Issue by vpatkov** [musescore/MuseScore#15264]
**Describe the bug**
I want to move "MuseScore4" from my $XDG_DOCUMENTS_DIR to another location. Preferences allow you to change most of the pathes, but not "Cloud Scores". Also after changing "Scores" location, it doesn't respected, and the folder created at the default path ($XDG_DOCUMENTS_DIR/MuseScore4/Scores) automatically when I launch MuseScore.

**To Reproduce**
1. Go to Edit/Preferences.
2. No "Cloud Scores" here. Set "Scores" to another location.
3. Move "Scores" directory the new location. Delete "Cloud Scores" directory.
4. Relaunch MuseScore. "Scores" and "Cloud Scores" directories are re-created on the default locations.

**Platform information**
 - OS: Linux

**Additional context**
Musescore v4.0.0

**Comment by cbjeukendrup** [comment]
The "Cloud scores" case will be "fixed" by #17764, and the "Scores" part is being tackled as part of issue #15567, so I think we can close this issue as a duplicate. Thanks for reporting!
