### ISSUE TITLE
[MU4 Issue]Crashes when deleting measures (Mac OS)

### ISSUE THREAD

**Issue by opjazz** [musescore/MuseScore#15265]
Musescore 4 crashes when deleting measures

**To Reproduce**
1.Select measures 
2. Click command+backspace or right click and choose "delete measures"
3. Musescore 4 crashes

**Expected behavior**
Delete the measures chosen

**Platform information**
 - OS: macOS

**Additional context**

**Comment by eitanmuir** [comment]
I'm encountering a similar problem in Windows 10 when deleting measures from scores with a moderate number of staves (7 instruments).

**Comment by cbjeukendrup** [comment]
I can't reproduce this so far. If this happens with specific scores, could you upload one of those? Or are there additional steps/circumstances required to reproduce this?

**Comment by opjazz** [comment]
Well, I can't reproduce it now either, but I will watch out for the issue and report if it happens again.
