### ISSUE TITLE
[MU4 Issue] Guitar Tablature not Rendering Properly when Invert Colors is enabled

### ISSUE THREAD

**Issue by Sandwall** [musescore/MuseScore#15273]
**Describe the bug**
I have the invert score feature enabled (white score paper should become black, text should become white under default settings). Instead of this happening for the fret numbers in guitar tablature, only the foreground color changes to white, leaving its background color as white. In this state, the two colors are indistinguishable and the fret number of the note cannot be read unless I select it with the mouse cursor, changing its foreground text color to blue.

**To Reproduce**
1. Open Edit -> Preferences -> Appearance, and check _Invert Score_ button (can be seen after scrolling to the bottom of the page, it's above the _Reset to Default_ button)
2. Apply the Change
3. Create New Project, with a single electric guitar tablature staff.
4. Add any notes to the staff with note input mode.

**Expected behavior**
I expected the foreground color and background text color to swap (the background of the note would become black, and the foreground of the note would become white).

**Screenshots**
Here are screenshots of the bug:
![deselected](https://user-images.githubusercontent.com/17184361/208238513-d199a330-261d-4745-bafd-3ed68b3acd0e.png)
![only one note is selected](https://user-images.githubusercontent.com/17184361/208238532-8b842281-6bbb-42dd-bc2c-2600fdd70090.png)
![selected](https://user-images.githubusercontent.com/17184361/208238520-10e8bdf9-7a54-425d-b4fd-b5645d3341e5.png)

Here is a screenshot when _Invert Score_ is not enabled:
![invert score disabled](https://user-images.githubusercontent.com/17184361/208238630-a4335105-a133-425c-99ac-cef83fe73d1a.png)

**Platform information**
OS: Windows 10 Version 2009
(This was done on a Windows 11 22H2 machine, the above statistic was copypasted directly from the MuseScore 4 _About_ window)

Arch.: x86_64
MuseScore version (64-bit): 4.0.0-223510501
revision: github-musescore-musescore-5485621

**Additional context**
This is not the main focus of this issue, but I also noticed that if you try to click one of the toggle (single or double) sharp/flat/natural buttons in either the top toolbar or the (default) left-docked sidebar under the "Accidentals" category when selecting measures of tablature (note input mode is off), the notes' background color switches to a red and all of the notes become an open note on the string at the top. You seem to be able to trigger this from any string/pitch.
I don't know if this is intentional, but I noticed it when playing around with the tablature features and felt I should also maybe mention it. Here's a screenshot (with and without _Invert Score_ enabled):
![with it on](https://user-images.githubusercontent.com/17184361/208239056-a89d57ef-2c21-41f5-8205-0c8fcd76f5af.png)
![with it off](https://user-images.githubusercontent.com/17184361/208238999-7f57bd79-c180-4ad0-8125-f772a67f696c.png)

**Comment by Nyde42** [comment]
Both of the bugs you mentioned also happen to me.

Another thing about the second one: The note being turned into an open note on the top string with a red background isn't directly caused by applying the accidental - rather, applying the accidental makes the note turn into a C9, which then causes this effect (which is intentional, since that's just what happens for out-of-range notes in MuseScore tabs - the bug here is the note's pitch suddenly jumping up).

OS: Windows 10 Version 2009 (Actual OS version is 10.0.19044)
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-223472200
revision: github-musescore-musescore-5485621

**Comment by ShibuyaCyana** [comment]
Looks like the same issue: https://github.com/musescore/MuseScore/issues/11570

**Comment by Nyde42** [comment]
@ShibuyaCyana Is there already something regarding the bug when applying accidentals that was also mentioned?

**Comment by ShibuyaCyana** [comment]
@Nyde42 nope, but maybe open a different issue for it since it's not related with the title

**Comment by Nyde42** [comment]
@ShibuyaCyana Will do, thanks :)

**Comment by Sandwall** [comment]
> Looks like the same issue: #11570

I did not see that, thank you for letting me know. (My search terms only involved "tablature" and "invert colors" and not "guitar tab" in general, that was my mistake)

I'll be closing this issue as it seems to be a duplicate of #11570, and we have a new issue (#15284) for the secondary problem in the _Additional Context_ section, hope development on all the guitar issues/features goes well.
