### ISSUE TITLE
[MU4 Issue] Can't close the BBC Symphony Orchestra VST when chosen as audio playback

### ISSUE THREAD

**Issue by thomassamoth** [musescore/MuseScore#15283]
**Describe the bug**
I can't close the BBC Symphony Orchestra VST when it's chosen for the playback.

**To Reproduce**
1. Go to 'Mixer'
2. Next to MS Sound, click on the arrow to choose another intrument.
3. Choose 'VST3 > Spitfire Audio > BBC Symphony Orchestra'
4. The VST opens but I can't close it.

**Expected behavior**
It would be better to see the close button. FYI, it exists if I choose another VST.
![image](https://user-images.githubusercontent.com/25958977/208254180-30ebd450-2570-4e48-b253-417c2e15f2e6.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/25958977/208254003-2262cf32-8bd5-452b-85d2-dddd417db840.png)

**Platform information**
 - OS: Windows 10

**Additional context**
I can't event grab the window to move it and eventually see the closing button. The problem may be that the window is too large for my sreen. It works fine in Ableton though.

**Comment by MarcSabatella** [comment]
You probably can via the standard Windows shortcuts like Alt+F4 or Alt+Space.  Also see https://github.com/musescore/MuseScore/issues/15200

**Comment by thomassamoth** [comment]
I hadn't seen the issue. Thanks for the tip.
