### ISSUE TITLE
[MU4 Issue] Applying accidentals to a guitar tab note turns it into C9

### ISSUE THREAD

**Issue by Nyde42** [musescore/MuseScore#15284]
**Describe the bug**
When applying any accidental to a note in a guitar tablature staff, the note will turn into a C9 (as indicated by the display at the bottom of the software) and be displayed as an out-of-range note (fret 0 with red background) on the top string.

**To Reproduce**
1. Open or create a score containing a guitar tablature staff.
2. Create any arbitrary note within the tablature staff.
3. Apply any accidental to the note. This includes _all_ accidentals in the top toolbar and _all_ elements in the "Accidentals" palette except for "Add parentheses to element" and "Add brackets to accidental".

**Expected behavior**
I'm not sure about this one - I would expect the note to either not change at all, or change its pitch like it would if it were notated in standard notation. The latter would certainly be possible, since MuseScore does store the actual note name of a note, even in tablature (again, as shown in the bottom display) - however, doing nothing at all would be the more logical approach in my opinion.

**Screenshots**
Before applying the accidental:
![image](https://user-images.githubusercontent.com/59689867/208254380-44468d8e-35c3-417e-a6b6-43b92987d69c.png)
(The white box behind the note is already an open issue, don't worry about it.)

After applying the accidental:
![image](https://user-images.githubusercontent.com/59689867/208254409-d8289bcd-2694-443b-89be-0b50238fae50.png)
![image](https://user-images.githubusercontent.com/59689867/208254424-e966481f-d892-4c12-8ba1-968e75740516.png)

**Platform information**
OS: Windows 10 Version 2009 (not confident about the correctness of this one - Actual version is Windows 10 Home 21H2, Version 10.0.19044)
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-223472200
revision: github-musescore-musescore-5485621

**Additional context**
I'm not 100% confident, but I think that I've already seen this bug in MuseScore 3.

**Comment by randoguyname** [comment]
Reproduced on MacOS, in MU4 and MU3

**Comment by Nyde42** [comment]
A small followup: After testing a little more, I noticed that I overlooked something. Even though the pitch does jump up to a C9 (in MU3 it's G9 and in MU2 it's C-1), **the accidental is still applied**. So in MU4, applying a double sharp to any note will actually result in a C##9, and a flat will result in a Cb9, etc., as shown here:
![image](https://user-images.githubusercontent.com/59689867/208280763-9f481370-4b0e-46f6-a2e3-23ec3bb8677f.png)

In the screenshot that I attached to the issue itself, the note is actually just C9 because I applied the "natural" accidental.

**Comment by randoguyname** [comment]
I believe i've found the problem; the function `void Score::changeAccidental` uses the 'line' of the note to find its pitch and then change it, which obviously doesn't work for tablature. I'll work on a PR now
