### ISSUE TITLE
[MU4 Issue] MuseHub is having trouble connecting, when I'm connected.

### ISSUE THREAD

**Issue by scannerbrightly** [musescore/MuseScore#15280]
**Describe the bug**
Install MuseHub, open it. It displays the following:
 ![Muse_YHRohoFoWA](https://user-images.githubusercontent.com/9724119/208252347-1e5d1744-3508-4667-acee-3e59b8db5dc2.png)

**To Reproduce**
1. Install MuseHub
2. Open MuseHub
3. It shows that it can't connect. 

**Expected behavior**
That MuseHub would find my Ethernet connection, which is connected via a Dell D3100 USB3 dock, as are my screens, keyboard, and mouse. 

There are no ways to edit any connection settings in the Settings area. I tried to turn off 'Community Acceleration' but it didn't change anything. I've rebooted. I've also connected to my Wi-Fi while still connected to my dock and pressed the 'round arrow', but it still didn't find a connection. I've tried to 'repair' the install. No joy. 

**Screenshots**
 ![Muse_YHRohoFoWA](https://user-images.githubusercontent.com/9724119/208252347-1e5d1744-3508-4667-acee-3e59b8db5dc2.png)

MuseScore3 was able to find my connection:
![MuseScore3_tpHL1vzYJf](https://user-images.githubusercontent.com/9724119/208252593-03be8d1d-b427-4940-a84c-2d60eb78dbf4.png)

**Platform information**
 - OS: Windows 10, 22H2, build 19045.2364 
 - Lenovo T460s, 12 GB RAM, i5-6300U
 
**Additional context**
I might be able to try to capture network traffic, if somebody pointed me to what I might be looking for. What address is it trying to connect to? Is it trying to resolve that address using a DNS?

**Comment by jtackaberry** [comment]
AFAICT their backend is not sized to meet the demand.  Muse Hub tries to query https://muse-webservice.azurewebsites.net/graphql but it's frequently timing out.

**Comment by jtackaberry** [comment]
Related to #15275

**Comment by arhadthedev** [comment]
> AFAICT their backend is not sized to meet the demand

Would total replacement of the Azure-hosted GraphQL API with a GitHub in-repo manifests increase reliability?

I believe that GitHub imposes no quota or bandwidth limitation on GET queries like `https://github.com/musescore/MuseScore/blob/master/musehub-manifest.json` or `https://github.com/musescore/MuseScore/releases/download/v4.0/MuseScore-4.0.0-x86_64.msi`.

**Comment by cbjeukendrup** [comment]
Closing, since this is a Muse Hub issue and not a MuseScore issue, and it seems like this was a one-time server issue.
