### ISSUE TITLE
Unsupported on Windows 7?

### ISSUE THREAD

**Issue by severak** [musescore/MuseScore#15287]
Hi,
I wanted to test new MuseScore 4 on my computer and got some DLL error message.

From https://musescore.org/en/download I understood that Windows 7 is not supported by MuseScore v 4 which I understand as Win7 is somewhat outdated. 

But it would be nicer if I was told this by installer or at https://musescore.org/en page.

**Comment by jeetee** [comment]
Microsoft does not support its audio SDK on Windows 7 and 8. That SDK is used by the new playback engine. So yes, support for windows 7 has been dropped.

It's mentioned on the download page itself though: https://musescore.org/en/download

**Comment by MarcSabatella** [comment]
Feel free to suggest this to Microsoft, but they've made it pretty clear they do not want people continue to use Windows 7 and creating security risks.

Meanwhile, you are of course welcome to choose to use older versions of MuseScore just as you are choosing to use older versions of Windows - that's the workaround.

**Comment by Tantacrul** [comment]
> that's unfair there should be a workaround for old users

The pace of technology is a real pain for everyone for sure. However, we don't hold all the cards here. Other technologies we rely on eventually drop supported for older OS (and adopt new ones), and we're largely tied to those decisions.
