### ISSUE TITLE
[MU4 Issue] Some of the tempi have learned to fly...

### ISSUE THREAD

**Issue by quinnouyang** [musescore/MuseScore#15297]
https://user-images.githubusercontent.com/90884224/208274968-a47c5225-fc48-4a37-b6e1-87cba80719d9.mov

**To Reproduce**
1. Open the Master Palette
2. Click to Tempo
3. Wave your cursor over the grid. Magic! (Direction does not matter–any movement moves the same group of tempi vertically.)
(This doesn't seem to occur for any other tabs in the Master Palette.)

**Expected behavior**
This should not happen.

**Platform information**
 - OS: macOS Monterey 12.6, Macbook Air M1 with built-in trackpad (if that matters)

**Comment by cbjeukendrup** [comment]
Another way to reproduce the same issue in the regular Palettes:

https://user-images.githubusercontent.com/48658420/208277483-87b270ae-9845-46b0-8583-c3ecb8409f26.mov

On every redraw of the palette cell, the text is moved upwards a little bit.

**Comment by quinnouyang** [comment]
~~Who's going to displace those specific palette options enough times to notice?~~
