### ISSUE TITLE
[notation issue] beam direction ignoring default, disappearing stems

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15298]
**Describe the bug**
On a percussion staff, sometimes beam direction got reversed for unknown reasons and also made the stems disappear.

**To Reproduce**
1. on a single line percussion staff (like bass drum), add a note
3. press ctrl + 3/4/5 to make it into a tuplet
4. see the beam direction flip and if more notes are added to the rest of the tuplet, the stems disappear
5. this can also happen for non tuplets but I do not know how to reproduce that (example in screenshot)

**Expected behavior**
On a single line percussion staff (like bass drum), beam direction is defaulted to down so all notes including tuplets should also have beams facing downwards.

**Screenshots**
![image](https://user-images.githubusercontent.com/120861729/208274728-8930188b-3730-488d-b1d3-4d0f701ff67e.png)

**Platform information**
windows

**Additional context**
It also happened in musescore 3 but the stems did not disappear before.

**Comment by oktophonie** [comment]
This is very similar to https://github.com/musescore/MuseScore/issues/15166 and we shuld therefore ensure it is also fixed by https://github.com/musescore/MuseScore/pull/15205

**Comment by eitanmuir** [comment]
I have also noticed this on Percussion staves and staves with less than the standard 5 lines
