### ISSUE TITLE
[MU4 Issue] a Tempo option (Request)

### ISSUE THREAD

**Issue by pumkinisawesome** [musescore/MuseScore#15294]
It would be lovely if there was an option of "a Tempo" inside of the Tempo section of the Pallettes menu, as at the moment I have to manually insert the correct tempo object and then change the tempo, which is more time consuming than it needs to be, and it also makes changing the tempo later very frustrating.

**Comment by cbjeukendrup** [comment]
Hello! This has already been requested in #14445, so if you don't mind I'll close this one as a duplicate. Thanks though!
