### ISSUE TITLE
Key signatures of transposed instruments

### ISSUE THREAD

**Issue by oscardssmith** [musescore/MuseScore#15291]
Adding a key signature to a solo piece for an instrument that isn't in concert pitch adds a key signature in concert pitch. I'm not sure what the right behavior is when dragging a key signature into a score with multiple instruments that are in different keys, but it's really confusing as a user to drag a key signature with 2 sharps into a clarinet part and see 4 sharps.

**Comment by eitanmuir** [comment]
This doesn't strike me as an issue, but more a matter of user preference - just add a C Major key signature for two sharps in a Bb clarinet? Or compose in concert pitch, then transpose the whole score down a Major Second?

**Comment by oscardssmith** [comment]
Unfortunately this is probably one where desired behavior depends on background, but as a woodwind player, I am much more likely to think in instrument pitch than concert pitch. This definitely isn't a massive issue, but it's just one that requires an extra couple seconds of thought whenever you change key signatures.

**Comment by quinnouyang** [comment]
Next time, for issues, we encourage you to follow [this](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues):).

Though I understand your issue. When you create a score for a transposed instrument, say B-flat clarinet, we start with the key of D, because C-major in concert pitch is D-major for a B-flat clarinet (their D sounds like a concert C). The key signatures in the palette are also in concert pitch, so dropping them onto the score will give their transposed counterparts.

Whether this should be the intended behavior is up to question, and I'd agree that this should not be the behavior for transposed solo instruments.

**Comment by Fristover** [comment]
"but as a woodwind player, I am much more likely to think in instrument pitch than concert pitch."

As a woodwind player too I do think the same usually, but this is not the case, when you see a clarinet sonata in Eb major you don't see clarinet having an Eb major signature, can't see why this shouldn't be the same even when there's no other instruments

**Comment by MarcSabatella** [comment]
The reason it is done this way is because otherwise the behavior is undefined when you have a score for mixed transpositions - if you select D major in a score for orchestra, how should MuseScore know which D major you meant?  The only sensible thing is to treat key signatures as concert in that case.  And then having it work differently depending on how many instruments happen to be included would be inconsistent and would look like a bug.

**Comment by sammik** [comment]
> if you select D major in a score for orchestra, how should MuseScore know which D major you meant? 

It could be done this way:
- if You drop into transposed instrument, MS ads keysig in instrument pitch
- if You drop into normal instrument, MS ads keysig in concert pitch
- if multiple staves with different transposing (and normal) isnstruments are selcted, MS ads keysig in concert pitch

**Comment by Fristover** [comment]
Ehh, I really don't think that's a good idea, the way it works now it's just fine, they're transposing instruments so you should think of them as that

**Comment by MarcSabatella** [comment]
I agree, it's possible to design in inconsistent interface that attempts to "do what I mean", and hope users can guess which behavior they'll get from any given action.  I think it better to keep it consistent personally, then no one needs to guess.

**Comment by sammik** [comment]
> I agree, it's possible to design in inconsistent interface that attempts to "do what I mean", and hope users can guess which behavior they'll get from any given action. I think it better to keep it consistent personally, then no one needs to guess.

It is not "inconsistent". It has just different rules ("add always in concert pitch" vs "add in selected instrument pitch").

(I would leave it, as it is now, but it is not true, "is not possible do it other way".)

**Comment by MarcSabatella** [comment]
Think if someone dragging to the score, not particularly thinking about which staff their mouse happens to be closest to when they release the mouse.  It would look random to them.  Or if they just happen to click a measure before clicking the key signature without thinking about what its transposition is.

I’m not saying it’s impossible to make up an algorithm, but I am saying, it’s likely to generate surprise a lot of the time and not feel like an improvement as a result.

**Comment by sammik** [comment]
Well, than more rigid rule could be: add in instrument pitch, if there is (are) only instrument(s) only that pitch. 
(which is actually original request here)

But yes, it is a bit ad hoc rule.

**Comment by sammik** [comment]
I just realised one more context - note input mode.

Key stroke "c" always creates written note C - if score is in concert pitch, it creates C note in concert pitch, if score is in transposed pitch, it creates written C, which is not (sounding) C.

**Comment by MarcSabatella** [comment]
Certainly, but in that context it is 100% clear and obvious the pitch refers to the staff you are entering the note on.  There is no such thing as entering a note for the entire score the way there is for key signatures.  So, there really isn't much to the analogy, as the case that explains why key signatures are always concert pitch simply cannot exist in note input mode.
