### ISSUE TITLE
[MU4 Issue] Opening a score (clicking its file) launches the homepage instead of opening the score view (macOS only)

### ISSUE THREAD

**Issue by quinnouyang** [musescore/MuseScore#15292]
Haven't seen a report of this which I'd find odd, considering opening a file is pretty common to do.

**To Reproduce**
1. Ensure MS4 is not running. Scores open properly if there is an existing instance running
1. Open any MS4 score (older score versions prompt the update notice and open the score properly).
2. Note that the program launches to the homepge. It does not navigate to the Score tab nor does it show it there either.

**Expected Behavior**
Opening a score should open an instance that presents the Score view.

**Platform information**
 - OS: macOS Monterey 12.6

**Comment by cbjeukendrup** [comment]
I can reproduce this in the release build, but strangely enough not in my own local builds...

**Comment by mscuthbert** [comment]
Indeed, in the same download as reported in #15465 I have the same issue of the score not opening.

**Comment by bkunda** [comment]
I can reproduce this in both the release build and the latest nightly. Definitely worth an urgent fix!

**Comment by DmitryArefiev** [comment]
Fixed in #15815
