### ISSUE TITLE
[MU4 Issue] Playback toolbar: "pause" button changes to "play" icon when docking/undocking during playback

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#15302]
**To Reproduce**
1. Start playback in a score.
→ the "play" button in the playback toolbar gets a "pause" icon, as expected.
2. Dock or undock the playback toolbar.
→ the "pause" icon unexpectedly changes back to a "play" icon.

This is only a visual problem; the playback itself and the button itself still function correctly.

**Comment by DmitryArefiev** [comment]
Fixed in #15309

**Comment by DmitryArefiev** [comment]
Retested on Win10
