### ISSUE TITLE
[MU4 Issue] The sound from the program goes to the speakers instead of earphones.

### ISSUE THREAD

**Issue by SmileyTheSmile** [musescore/MuseScore#15308]
**Describe the bug**
After plugging in Type-C earphones, the sound still goes to the speakers instead of earphones. Not sure if that's configurable or intended, but i think the sound should be sent to the earphones by default

**To Reproduce**
1. Plug in Type-C earphones
2. Play any sounds in the program
3. Realize they come out of your laptop's speakers instead of the earphones

**Expected behavior**
The sound should be sent to the earphones by default.

**Platform information**
 - Windows

**Comment by shoogle** [comment]
Does it work if you open the program after you plug in the headphones? (I appreciate this shouldn't be necessary.)

**Comment by SmileyTheSmile** [comment]
Yep and it seems that unplugging them crashes the whole thing. 
--
Отправлено из Mail.ru для Android воскресенье, 18 декабря 2022г., 15:00 +03:00 от Peter Jonas  ***@***.*** :

**Comment by shoogle** [comment]
Ok thanks. These problems appear to be covered by these existing issues:

- #10987
- #15029

Somebody already commented in the second one to say its not just Bluetooth headphones that are affected.
