### ISSUE TITLE
[MU4 Issue] Pause (fermata/caesura) duration not honored until save/reload

### ISSUE THREAD

**Issue by SamYeh** [musescore/MuseScore#15305]
**Describe the bug**
The pause time setting for fermata and caesura has no effect. For caesura, it does not pause at all.

![image](https://user-images.githubusercontent.com/10248807/208282075-f154b639-5557-429b-b2b9-522ebd769fb3.png)

**To Reproduce**
1. Create a score like the one above
2. Add a caesure, Inspect the properties of the caesura and change the specified pause to 10 seconds.
3. Play the score and observe that the pause is only 2 seconds.  Cursor and playback are no longer aligned

**Expected behavior**
The music should pause for the specified duration.

**Platform information**
 - OS: Windows 11
 - Build: MU4 Release (MuseScoreNightly-223480502-4.0_rc-5485621-x86_64.7z)

**Comment by Jojo-Schmitz** [comment]
Came up in https://musescore.org/en/node/339353

**Comment by MarcSabatella** [comment]
The pause is honored after the playback info is regenerated - save/reload, for example, but also any edit that changes the playback.

**Comment by MarcSabatella** [comment]
Is this fixed in a development build?  It's definitely still an issue in 4.1.1, as described.  The caesura does not affect playback until save/reload.

**Comment by zacjansheski** [comment]
Hope I'm not missing something
Opened score in Windows 11 on 4.1.1
Caesura lasts 10sec

https://github.com/musescore/MuseScore/assets/69917893/3b44d783-0883-493b-8e4a-464966a6b06c

**Comment by MarcSabatella** [comment]
Right, that's because this score has now already been saved and reloaded since the caesura was added.  Try adding a new one and you'll hear it has no effect (except on the cursor) until after another save/reload.

**Comment by Jojo-Schmitz** [comment]
regression vs. Mu3 apparently

**Comment by DmitryArefiev** [comment]
Fixed #20982
