### ISSUE TITLE
[MU4 Issue] Beams Collide With Rests When Beams Are Over Rests

### ISSUE THREAD

**Issue by onnogli** [musescore/MuseScore#15301]
**Describe the bug**
Notes which are beamed together manually (with beam properties) over a rest will now have beams which collide with the rest. This also didn't happen in MuseScore 3.

**To Reproduce**
1. Write 2 notes which have flags or beams by default (8th, 16th, 32nd, etc.), and are either high or low on the staff (ex. treble clef G and above).
2. Separate them with at least 1 rest.
3. Select the rest(s) and use "Join Beams" from the "Beam Properties" palette.

**Expected behavior**
The rest(s) move out of the way (either up or down depending on the notes) of the beam to avoid collision (which I would prefer), OR the beam stretches out of the way of the rest(s) (like in MuseScore 3). (or a combination of both?)

**Screenshots**
![image](https://user-images.githubusercontent.com/103379965/208278486-89522576-b9ef-489f-b1cf-0cd426b79fcc.png)
![image](https://user-images.githubusercontent.com/103379965/208278492-1853300a-9abc-44c9-9b77-d261ea07df49.png)
![image](https://user-images.githubusercontent.com/103379965/208278426-72869d1d-d573-4b1d-b6d7-7cdb992ff9b8.png)

**Platform information**
 - OS: Windows 10

**Comment by oktophonie** [comment]
Your 'expected' solution is exactly what we have planned, watch this space :)
