### ISSUE TITLE
Glissando lines appearing in weird places

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15316]
**Describe the bug**
gliss lines appear at places where there should only be rests (probably a teleporting issue, the glisses seem to belong to other staves in other bars but get moved to unwanted places)

**To Reproduce**
I don't know what causes this to happen, but maybe it is more likely to happen in areas with glissandi in other staves.
The gliss lines do not have to be on the same page but can also originate near that page.

**Expected behavior**
There should not be gliss lines in places where they were not added, and intentional gliss lines should not get lost and reappear in unexpected places.

**Screenshots**
![image](https://user-images.githubusercontent.com/120861729/208292602-ab84a478-8826-4fb3-b7e7-98951ee42344.png)
There are some unwanted gliss lines in the top staff (pg 33 of the score), after some searching, they seem to belong to trombone parts 7 bars later on the next page (pg 34) which went missing.

![image](https://user-images.githubusercontent.com/120861729/208291587-9f457203-bb9f-4b15-bfeb-67c2af5ac30e.png)
When inspecting these lines, they appear to have no displacement like they were not shifted here from somewhere else.

![image](https://user-images.githubusercontent.com/120861729/208292481-62cfeff2-0d47-4f46-a19e-ae744d3e489a.png)
But on the next page, the trombone glisses were missing, but the grace notes were still seperated like there should be a gliss line between them and the note on the beat (automatic placement for the gliss seems to be working, but the gliss line is missing)
Also notice there were 5 different gliss lines in the 5/8 bar but only 4 gliss lines at the start of this bar (so the fifth one could be teleporting there from somewhere else).

![image](https://user-images.githubusercontent.com/120861729/208293156-d405d6f8-1b9f-4a86-bf49-43a2122053e7.png)
Solution 1: after deleting one of the displaced gliss lines, the rest of the gliss lines returned to their original place on the next page, but the line which was deleted is also deleted at the place it originated.

The problem was reset using the undo button to try this other solution:

![image](https://user-images.githubusercontent.com/120861729/208292713-1d91d5c5-ab8d-4918-80db-b138fa38a481.png)
Solution 2: after changing (and reverting) one pitch on the trombone bar, all the gliss lines returned to the right place.

![image](https://user-images.githubusercontent.com/120861729/208293261-6affeff3-8b6f-49a9-a718-750a63eebddb.png)
After fixing these lines on pg 33 and 34, I noticed more gliss lines at the top of page 34, originating from another stave at start of the page 35 (again lines teleporting one page back):
![image](https://user-images.githubusercontent.com/120861729/208293447-ad2bdb2b-53f2-43b6-9488-ad57115bea90.png)
timpani gliss lines went missing on page 35 which seemed to teleport to the top of page 34

**Platform information**
windows

**Additional context**
After fixing it properly, pressing undo does not replace those glitched lines.

In MU3, this also happened with ties and sometimes the ties reappeared (without deleting the original one) in weird locations multiple pages away from where they originated for unknown reasons, deleting one of the glitched ties would also delete the tie it originated from. (but selecting the reappearing tie also selected the original tie like they were the same object but in two different places at once)
I do not know if this gliss line problem is the same as the tie one, but they look similar.

**Comment by Vykoiazon** [comment]
![image](https://user-images.githubusercontent.com/120861729/208296531-daca466f-d01c-4ae9-a3ad-56191b082613.png)
When the next page has a lot of gliss lines, it can make things a lot more messy

**Comment by oktophonie** [comment]
I noticed this myself in conjunction with the issue eventually fixed by https://github.com/musescore/MuseScore/pull/14890. Perhaps you might try this score with that build to see if it makes a difference.

**Comment by mike-spa** [comment]
@Vykoiazon could please share the speficic file where this is happening? That would help us investigate the issue. It doesn't need to include the whole piece, you can cut it down to the specific bars involved.

**Comment by Vykoiazon** [comment]
[glissando glitch demo.zip](https://github.com/musescore/MuseScore/files/10273300/glissando.glitch.demo.zip)
The corruption has nothing to do with the glissando glitch, it is a problem with meter in the drumset at the first bar.

To reproduce the glitch, edit the text on the first page by deleting letters or something.

**Comment by mike-spa** [comment]
Thank you! 👍

**Comment by aige02** [comment]
I have observed this behavior in 230370506-4.0.2-aabbec1-x86_64 on Windows 11.  A glissando in measure 145 staff 17 is drawn on staff 1 approximately (exactly?) 1 page earlier, which places it across measures 130-132.  Dragging the glissando shows it anchored on staff 17.  Releasing it after dragging it redraws it correctly in measure 145.

**Comment by oktophonie** [comment]
It has not been merged, so you should not expect to see the results of this fix in any builds yet (except for a specific build of the PR in question)

**Comment by Vykoiazon** [comment]
they no longer reappear on other pages but they can go missing from a page which but they return to place after changing any note on the page (but once they went missing and had to be manually readded)

**Comment by oktophonie** [comment]
If you can provide a score where this reliably happens, or describe proper steps to consistently reproduce it, then we can reopen this issue.
