### ISSUE TITLE
[MU4 Issue] Crash if MuseScore cannot modify %userprofile%\Documents during startup

### ISSUE THREAD

**Issue by aminya** [musescore/MuseScore#15315]
**Describe the bug**

I use the protected file system feature of Windows to lock some of the folders. For most of the other apps, I get a pop-up from Windows security about the access, and I have to allow that certain app. However, MuseScore crashes before I can enable that.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable the protected system folder on Windows
2. Open MuseScore

**Expected behaviour**

Show a dialogue to retry the modification or something similar instead of crashing.

**Screenshots**
![image](https://user-images.githubusercontent.com/16418197/208292668-7a260b1e-5a3f-4f22-b38f-63e286edf184.png)

**Platform information**
 - OS: Win 11

**Additional context**

**Comment by aminya** [comment]
It is also useful to show the progress of loading. I have several VST files, and it took a long time to start, but it was only showing loading. I thought something else is going on until I saw the Waves rotating icon.

![image](https://user-images.githubusercontent.com/16418197/208292888-d7f8a4a1-01c1-40aa-8d2d-1b20b807d317.png)

**Comment by zacjansheski** [comment]
Is this still actual?

**Comment by zacjansheski** [comment]
Closing (no response)
