### ISSUE TITLE
[MU4 Issue] Crash when trying to create a new score based on a custom template with instruments changes

### ISSUE THREAD

**Issue by metasekk** [musescore/MuseScore#15313]
**Describe the bug**
MuseScore4 crashes when trying to create a new score based on a custom template containing at least one instrument change in it.

**To Reproduce**

1. Create a new score
2. Set at least one mid-staff instrument change (with the *Change Instrument* text) on an arbitrary staff
3. Save the score in the *Template* directory of your Musescore4 working directory.
4. Try to create a new score based on it.
5. See Musescore4 crash.

**Expected behavior**
The new score should be created without a crash, regardless of the content of the template.

**Screenshots**
I provide a [video](https://user-images.githubusercontent.com/120221700/208291774-b9ec7e01-440a-411a-8b8f-1f0d49ccc0b6.mp4) of the crash.

**Platform information**
 - OS: Windows 10 Version 22H2, 64 bits, x64-based processor
 - Tested on: MuseScore Release version (64-bit): 4.0.0-223472200 with MuseSampler v.0.3.2

**Additional context**
It does not appear to be a critical issue, but it seems worth knowing about.

**Comment by bkunda** [comment]
Still reproducible in latest master.
Leaving as P2 for now as the triggers are not sufficiently frequent to affect most regular use cases.

**Comment by mathesoncalum** [comment]
The repro steps for this one seem to have evolved slightly in the current master; the score can be created just fine but interacting with it (e.g. adding some notes) causes a crash.

I'm fairly certain the root cause is the same though, #20102 should rectify.
