### ISSUE TITLE
[MU4 Issue] not resync view score using Ctrl-End and Ctrl-Home, 

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#15318]
1 - open score
2 - Select first Measure
![image](https://user-images.githubusercontent.com/1835871/208294471-5af43f4f-c430-437b-a87f-78e2d046495e.png)
3 - Press Ctrl-End
Info bar at bottom reflect the jump to end. 
![image](https://user-images.githubusercontent.com/1835871/208294522-23f601a2-b398-489d-920b-5a5a1ae78b53.png)
View don't jump to end of score, stay at first measure and lost focus
![image](https://user-images.githubusercontent.com/1835871/208294497-c81dc7e3-90b5-4ea8-9b44-3b549e1be00a.png)
4 - Espected, Cursor jump to last Measure of the current part.

Same issue if you select last Measure and use Ctrl+Home

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223510501, revision: github-musescore-musescore-5485621

**Comment by MarcSabatella** [comment]
Thanks for the report - this is already a known issue with a pending fix (see nhttps://github.com/musescore/MuseScore/issues/14691 and the associated PR)

**Comment by zacjansheski** [comment]
I believe this is no longer an issue.

**Comment by MarcSabatella** [comment]
Indeed, it was fixed in https://github.com/musescore/MuseScore/pull/15451.  This issue was actually a duplicate of https://github.com/musescore/MuseScore/issues/14579
