### ISSUE TITLE
[MU4 Issue] "More" section closes unexpectedly when you adjust properties outside it

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#15319]
**Describe the bug**

This is best illustrated by a screen cast. The attached animated gif (below) shows an adjustment being made to the text font size when the "More" section is open.

![menu_close_issue](https://user-images.githubusercontent.com/87246583/208294596-fdb0551d-2153-4daa-8b55-6d991170a3ed.gif)

As you can see, as soon as you alter the font-size, the "More" submenu closed unexpectedly causing the widgets to be suddenly relocated.

**Expected behavior**

In this case (and others like it) the "More" submenu should stay open.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223520506, revision: github-musescore-musescore-5485621

**Comment by iwoithe** [comment]
The popup is removed in https://github.com/musescore/MuseScore/pull/15821 in favour of an expandable section, so this specific issue should be resolved with it

**Comment by zacjansheski** [comment]
Closing per comment above
