### ISSUE TITLE
Slurs/ties/hairpins/etc cannot be removed from selections made by shift-clicking

### ISSUE THREAD

**Issue by Isaskar** [musescore/MuseScore#15321]
**Describe the bug**
Normally, objects can be added or removed from a selection by Control/Command-clicking. However, when a slur, tie, or other similar object has been added to a selection by shift-clicking, or by clicking on a measure, it cannot be removed from the selection. 

A slur that has been added by control-clicking can be removed the same way - it is specifically slurs selected by shift-clicking or by selecting the measure that cannot be removed.

I have not been able to test everything but I can confirm that Slurs, ties, trill lines, pedal markings, octave markings and hairpins are affected by the bug - it may be that it applies to every object that behaves in this way, with a start note and an end note.

**To Reproduce**
1. Add two notes
2. Connect them with a slur, tie, hairpin etc
3. Click the first note
4. Shift click the second note
5. Control/command-click a note or an object attached to a single note, like an accidental - it will be deselected
6. Attempt to control/command-click the slur/tie/etc - it will not be deselected

**Expected behavior**
Slurs/ties/etc should be removable from any selection by control/command-clicking, no matter what method was used to create the selection.

**Platform information**
I am on macOS Ventura. I cannot confirm the issue on any other platform, but it should be easy to test.

**Additional context**
There is also some weird behaviour - maybe deserving of a separate issue, though minor - when a selection is made by shift-clicking or measure selection in that pedal/octave markings will not have the text part appear selected (coloured blue), whereas when they are clicked or control/command clicked both the text and line appear selected.

**Comment by Tantacrul** [comment]
I don't feel this needs a design. I think you're right that it should just work as described.
