### ISSUE TITLE
[MU4 Issue] All palletes are completely messed up

### ISSUE THREAD

**Issue by alexybaddie** [musescore/MuseScore#15322]
**Describe the bug**
Palletes are messed up, look at screenshot. Some palletes don't even have labels anymore (just completely empty slots that add something to the score but it's impossible to know what's what.)

**To Reproduce**
1. I don't know, it kinda just happened and is stuck like this

**Expected behavior**
For the pallete to function like it should

**Screenshots**
![Screenshot 2022-12-18 115942](https://user-images.githubusercontent.com/28188721/208295504-6d1cd74b-b37b-4b7f-887b-94238747fd14.png)
![Screenshot 2022-12-18 122547](https://user-images.githubusercontent.com/28188721/208295797-94bb352c-e852-46a9-b783-a2545d112579.png)

**Platform information**
 - OS: Windows 10

**Additional context**

**Comment by shoogle** [comment]
Try going to **Help > Revert to factory settings**. Let us know if that fixes it for you.

**Comment by alexybaddie** [comment]
That fixed it, the cause seemed to be related to "invert score" in preferences or "application/paletteScale".

**Comment by shoogle** [comment]
Thanks for investigating! It looks like `application/paletteScale` is the culprit, at least in the 4.0 release build. It seems to be fixed already in the nightly builds, possibly by PR #14653.
