### ISSUE TITLE
[playback issue] mispitching tremolo

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15320]
**Describe the bug**
Audio playback of tremolo can sound like the wrong pitch.

**To Reproduce**
https://user-images.githubusercontent.com/120861729/208295234-81feff3f-c25f-439b-b560-767cbd50bffc.mp4

(this was MuseSounds flute 1 and flute 2)

**Comment by cbjeukendrup** [comment]
I think this is caused by #15250
