### ISSUE TITLE
[MU4 Issue] Recommendation: Add "Safe-Mode Open" That Bypass/Disable 3rd party VST loading

### ISSUE THREAD

**Issue by ShawTakeuchi** [musescore/MuseScore#15339]
**Describe the bug**

Recommendation only:  Add an option to open a saved file, bypassing loading of all VST instruments and effects specified in the .mscz file.

This is for score recovery for when unstable, incompatible, uninstalled, obsolete, or corrupt VSTs are encountered and the score cannot be opened.

**To Reproduce**

See https://github.com/musescore/MuseScore/issues/15335 for an example scenario.

**Expected behavior**

If implemented, open the file with MSBASIC default instrument assignments, and no Effects.

**Screenshots**

N/A

**Platform information**

N/A

**Additional context**

My DAW has this feature!
Alternatively a procedure to manually edit the content of .mscz?

You may close this issue as it is just a recommendation.

**Comment by NoSocket** [comment]
Any update on this? I was transcribing a piece this evening and using MODO DRUMS for playback. I restarted MS4 and now I can't open the score any more as MS4 crashes even though the score is fine and MODO DRUMS is fine and I use it every day.

**Comment by cbjeukendrup** [comment]
@davidjohnconnors In the upcoming MuseScore 4.1 update, plugin scanning at launch will happen in a separate process, so that MuseScore does not crash anymore if there is a plugin that crashes when loading it.

But that won't solve *your* issue of course, since that has to do with a specific score. I suggest that you create a new issue (to keep _this_ issue focused on one topic), and attach the crashy score in that new issue, so that we can investigate. Thanks!

**Comment by ShawTakeuchi** [comment]
> @davidjohnconnors In the upcoming MuseScore 4.1 update, plugin scanning at launch will happen in a separate process, so that MuseScore does not crash anymore if there is a plugin that crashes when loading it.
> 
> But that won't solve _your_ issue of course, since that has to do with a specific score. I suggest that you create a new issue (to keep _this_ issue focused on one topic), and attach the crashy score in that new issue, so that we can investigate. Thanks!

Unfortunately I wrote this issue when a EastWest Opus VST was crashing under MS4.  An updated VST was released by EastWest shortly after, and I am no longer able to reproduce this error.

Systemically it would be nice to have a "skeleton test VST" that creates the following conditions, for testing response behavior of MS4.x:
*  Divide by zero exception
*  Hung on infinite loop

For now I am ok w/ closing this issue, until someone else in the future files a new issue with specific, reproducible details (perhaps that will be me!)

**Comment by zacjansheski** [comment]
Closing per comment above
