### ISSUE TITLE
[MUSE HUB] No clear way to turn off seeding in Muse Hub

### ISSUE THREAD

**Issue by LucientZ** [musescore/MuseScore#15338]
When downloading Muse Sounds via Muse Hub, it appears that Muse Hub also uploads a large amount of data. I'm pretty sure this is because it uses torrent seeding/leeching in order to download the sounds. While this is fine for the most part, it doesn't seem like there's a way to limit or turn off the data uploading. This is an issue since the network in which I'm downloading the sounds on has a lot lower upload speed than download speed, making it so if the upload bandwidth gets capped, downloading essentially doesn't work. This ultimately makes it so downloading the sounds takes a lot longer than it should and I can't download them in a feasible amount of time. If there is a way to limit or disable the data uploading already that I don't know about it, information would be greatly appreciated.

**Platform information**
 - Windows 10

**Comment by MarcSabatella** [comment]
Click the settings icon and disable community acceleration.

**Comment by LucientZ** [comment]
Oh, I wasn't aware of that option. Didn't realize it was turned on by default. I also didn't realize that by "community" it referred to the Muse community. Appreciate the feedback!
