### ISSUE TITLE
[MU4 Issue] Dynamics don't work correctly

### ISSUE THREAD

**Issue by clsard** [musescore/MuseScore#15331]
**Describe the bug**
[MU4 Issue] Incorrect Implementation of dynamics

**To Reproduce**
1. In any type of dynamic, with any instrument.

**Expected behavior**
Being able to control the level of the dynamics.

**Platform information**
 - OS: [Windows]

**Additional context**
MS4 looks good, but these bugs need to be worked on.

**Comment by MarcSabatella** [comment]
Can you be more specific about what goes wrong?  If you attach a score and say which dynamic idn't working correctly, it can be investigated.

Note it's by design that dynamics no longer have their own velocity settings.  Instead, you set velocity on the notes themselves.

**Comment by clsard** [comment]
Dynamic _pp_ (pianissimo) is inaudible. A crescendo from _pp_ to _f_ (forte), the change is very abrupt. Not because the forte is too loud, but because the pianissimo is too low.
Sorry for my english

**Comment by clsard** [comment]
Your Note: _it's by design that dynamics no longer have their own velocity settings. Instead, you set velocity on the notes themselves._

If a note has a dynamic pp and a crescendo starts from it and it occupies 40 or more notes; Do you have to change the velocity value of all of them progressively (is it a crescendo)?

**Comment by clsard** [comment]
https://user-images.githubusercontent.com/2716821/208316085-aa392bda-9a70-49f4-acea-a4562ff98ea3.mp4

You can check in the mixer, the low values for the pianissimo and the abrupt change in the forte.

**Comment by MarcSabatella** [comment]
Crescendos work automatically; you don't need to change any settings in the crescendo or in the notes for that.  If you wish to customize the behavior of the crescendo, then yes, you'd do it via note velocities.  Eventually there are plans for a "volume lane" for this sort of thing.

**Comment by clsard** [comment]
Great idea "the volume lane"
