### ISSUE TITLE
[MU4 Issue] Expression text placement resets to different place

### ISSUE THREAD

**Issue by SilverGreen93** [musescore/MuseScore#15337]
**Describe the bug**
When using Ctrl+R to reset shapes and positions, Expression text is placed on the same line as staff text, instead of being at its default position, under the notehead.

**To Reproduce**
1. Add a couple of notes
2. Click one of the notes and add an expression text
3. The text will be added below the notehead.
![image](https://user-images.githubusercontent.com/24845602/208308699-d9699625-5f5d-4d5f-9141-8fe15f3ac48a.png)

4. Select the whole measure and press Ctrl+R
5. The expression text now sits above the staff, just like a staff text or system text.
![image](https://user-images.githubusercontent.com/24845602/208308711-8d32f75d-47c0-40c8-a38d-a9f393084e28.png)

**Expected behavior**
The expression text should maintain its place and not move above the staff.
If you manually move the text and Ctrl+R again, it reproduces the same.

**Additional context**
Musescore release 4.0.0

**Comment by MarcSabatella** [comment]
This is kind of any unfortunate side effect of the fact that expression text is actually staff text but with a different text style applied.  Probably it should be promoted to a first class element type.

**Comment by oktophonie** [comment]
Fixed by https://github.com/musescore/MuseScore/pull/17001

**Comment by SilverGreen93** [comment]
Confirmed fixed.
