### ISSUE TITLE
[MU4 Issue] Voices 3-4 collide with voices 1-2.

### ISSUE THREAD

**Issue by SilverGreen93** [musescore/MuseScore#15334]
**Describe the bug**
If using more than 2 voices, voices 3 and 4 will collide on display with voices 1 and 2.

**To Reproduce**
Use the attached file for an example. No matter if the 3rd voice is voice 3 or 4, it will collide with voices 1 and 2.

![how it looks](https://user-images.githubusercontent.com/24845602/208306367-fa085ae0-1e1a-45e0-9261-bb48081155d3.png)

![how it looks voices](https://user-images.githubusercontent.com/24845602/208306371-5bcd4625-da2f-4c45-9e53-dde6302ff32e.png)

**Expected behavior**
The voices should be displayed like this:
![how it should look](https://user-images.githubusercontent.com/24845602/208306362-82664d70-70f2-4732-ac0e-91a9e98361b9.png)

Attached score: 
[voices.zip](https://github.com/musescore/MuseScore/files/10254095/voices.zip)

Bug found in MU4 release 4.0.0.

**Comment by MarcSabatella** [comment]
Currently this is by design, as there are definitely some cases where one would want voices to align.  And it’s far easier to use manual adjustments to offset them than to attempt to align them perfectly.  But there should indeed someday be more control over this, I would agree.
