### ISSUE TITLE
Musescore does not detect already installed sounds after an app reset in Windows settings.

### ISSUE THREAD

**Issue by Jeeko336** [musescore/MuseScore#15330]
**Describe the bug**
After I reset the app in windows settings to fix an issue I faced, Musescore no longer detects my already installed sounds. I reset the app as when I tried installing new sounds, it would say ''Unable to resume download, please try again later.''. The reset fixed that issue, and I can now install new sounds. The sounds I had downloaded before also show as being present. Though in practice, in Musescore, only the newly installed sounds after the reset are shown and I am unable to download the ones that were there before as Musehub sees them as downloaded. As well as that, I'd rather not reinstall everything as I am on a data budget and wasting another 10GB is not in my interest.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the download of 2 Musesounds, pause 1 and let the other finish downloading.
2. Restart Windows.
3. Paused Musesound is now stuck in ''Unable to resume download, please try again later.''.
4. Go to Windows 11 settings, Apps, Installed Apps, MuseHub, Advanced Options, and Reset.
5. This fixed the ''Unable to resume download, please try again later.'', but now there is the issue that is in the description.

**Expected behaviour**
After the reset, I expected it to either delete all data including Musesounds and make me redownload them, though I hoped it would just keep them and detect the ones that are actually downloaded and leave behind the bricked downloads. Neither of those happened, instead the opposite, I am able to download new Musesounds but the existing ones I had are now bricked.

**Screenshots**
Musesounds Keys - Downloaded previously, now not detected by Musescore.
![image](https://user-images.githubusercontent.com/120938755/208301259-97d8dde4-c025-4ded-a302-a65003bdb33b.png)
![image](https://user-images.githubusercontent.com/120938755/208301274-34ba63c8-54b0-4190-a529-e381f0086d5b.png)
![image](https://user-images.githubusercontent.com/120938755/208301313-f630ce70-79fd-40ce-90b8-26c15e0f98d2.png)
Musesounds Woodwinds - Downloaded after reset, works fine.
![image](https://user-images.githubusercontent.com/120938755/208301341-f154825b-29ab-4a8a-8988-0b315e4cffb9.png)
![image](https://user-images.githubusercontent.com/120938755/208301352-580da23e-26c2-45c2-9226-0fd02d212f6b.png)

**Platform information**
 - OS: Windows 11

**Comment by Jeeko336** [comment]
I guess what I am asking for is an automatic detection of already downloaded sounds by Musescore, instead of a file that contains data about what Musesounds have been downloaded previously or however way it works.

**Comment by Jeeko336** [comment]
Sorry, didn't mean to close the issue.

**Comment by cbjeukendrup** [comment]
So Muse _Hub_ still recognises that you have installed the sounds, but MuseScore not anymore, right?

**Comment by Jeeko336** [comment]
> So Muse _Hub_ still recognises that you have installed the sounds (or at least it pretends to), but MuseScore not anymore, right?

Correct.

**Comment by iamtesch** [comment]
Can you do the following:
(1) quit Muse Hub
(2) go into Windows Services, and quit the "Muse Hub" service
(3) go into the directory where you are downloading Muse Sounds, and delete the ".dlcache" file
(4) restart the service, then start Muse Hub

Then redownload the packages you want.  The parts of the files you have already downloaded should not be redownloaded, so this should not use extra bandwidth.

After this, the packages should be available in MuseScore.  Let me know if this solves the problem; we'll get this more stable in the Hub as well so you don't have to jump through these hoops.  We're looking into how to handle this "App Reset" better internally.

**Comment by Batwam** [comment]
For anyone facing this issue on Linux, I had to use the appImage version of MuseScore4 instead. the sounds are downloaded after having installed and run MuseHub using the deb file provided. The Flatpak doesn't seem to be able to recognise the sounds.
