### ISSUE TITLE
[MU4 Issue] Slide out from tied note does not play back

### ISSUE THREAD

**Issue by joshuaboniface** [musescore/MuseScore#15342]
**Describe the bug**
A slide out from a tied note does not play back correctly as it does for a single note. In the example screenshot below, the first instance plays back as expected, but the second and third do not (the note is simply held for the entire duration).

**To Reproduce**
1. Create a note tied to the previous note.
2. Add a slide out (down or up) to the second, tied note.
3. Play back and observe that the slide out is not played.

**Expected behavior**
Slide outs should play even on the second (or more) parts of tied notes as if they were a continuous duration.

**Screenshots**
![Screenshot from 2022-12-18 12-43-34](https://user-images.githubusercontent.com/4031396/208311846-d0413a1d-5eca-44fb-b9bc-2abc63805777.png)

**Platform information**
 - OS: Debian GNU/Linux 11.5 "Bullseye"
 - Method: AppImage
 - Version: 4.0 Stable

**Additional context**
I'm using MS Basic sounds for playback here; cannot confirm other sound sets as this is a guitar part.

**Comment by MarcSabatella** [comment]
See also https://github.com/musescore/MuseScore/issues/12971 - probably a duplicate

**Comment by joshuaboniface** [comment]
Whoops thanks @MarcSabatella it is indeed the same issue just with the other articulation type. I'll close this one.
