### ISSUE TITLE
[MU4 Issue] Clef changing in stave properties

### ISSUE THREAD

**Issue by majenkotech** [musescore/MuseScore#15348]
**Describe the bug**
When editing the stave properties the first stave you select to open the properties dialog gets some settings from other staves you edit in the same dialog.

**To Reproduce**
1. Open the attached example file
2. Double-click `Soprano` to open the stave dialog
3. Press the down-arrow button three times to move to the `Bass` stave
4. Click the `Apply` button. 

The soprano stave will now suddenly have a bass clef.

Using the up-arrow button to go back to `Soprano` and hitting `Apply` again will reset the stave to treble clef.

[20-peter.mscz.gz](https://github.com/musescore/MuseScore/files/10254703/20-peter.mscz.gz)

**Comment by Harmoniker1** [comment]
Can't seem to reproduce on Windows 11…

**Comment by majenkotech** [comment]
I was seeing it with the release version (I think... if it updated...) on Windows 10. Lemme just compile from git on Linux. Maybe this is something that has already been fixed and I'm seeing an old version...

**Comment by majenkotech** [comment]
Nope, I'm not seeing it on Linux from git either. I guess it's something that got fixed and my windows installation just hasn't updated to the release version yet...?
