### ISSUE TITLE
[MU4 Issue] Maximized app window doesn't fill screen at 125% or 175% scaling on Windows

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#15341]
## **Describe the bug**
At certain display scales, MuseScore's main window doesn't entirely fill the screen when maximized. Occurs for these scale values in Windows display settings:

- 125%
- 175%
- 225%
- etc.

## **To Reproduce**
1. Right-click on Windows desktop.
2. Go to "Display settings".
3. Set scale to a value ending 25% or 75% (e.g. 125%).
4. Launch MuseScore and maximize the main window.

## **Expected behavior**
The app windows should fill the screen when maximised. Only our custom minimize, restore, and close icons should be visible.

## **Screenshots**

125% | 175% | 225%
---|---|---
![image](https://user-images.githubusercontent.com/11011881/208308476-1c34dc9c-3226-45c5-af70-a8b92390e6ea.png) | ![image](https://user-images.githubusercontent.com/11011881/208308493-b7db63ed-9513-470a-90c8-f0850015c973.png) | ![image](https://user-images.githubusercontent.com/11011881/208308537-25969ba5-1414-40e2-8a86-6dc211eb2e78.png)

Notice the small region of desktop background that is visible around the maximized window.

Also notice the small native minimize, restore, and close icons displayed above our custom icons.

<img width="500px" src="https://user-images.githubusercontent.com/11011881/208308668-daf0ad55-4c28-4777-b072-1a1068f4542f.png"/>

## **Platform information**
 - OS: Windows 11, display resolution 2256x1504 (3:2 aspect ratio).

## **Additional context**
The problem doesn't occur for integer scaling (100%, 200%, etc.) or half-integer scaling (150%, 250%, etc.).

100% | 150% | 200% | 250%
---|---|---|---
![image](https://user-images.githubusercontent.com/11011881/208309004-013d783f-9c6f-48f5-b5a9-434ee012b49e.png) | ![image](https://user-images.githubusercontent.com/11011881/208309045-08236f8b-9179-4734-99c8-89e7a50b8d71.png) | ![image](https://user-images.githubusercontent.com/11011881/208309090-8707f817-1dcf-4e93-bfd8-6910e8f11100.png) | ![image](https://user-images.githubusercontent.com/11011881/208309113-348a6a39-ec34-4b82-8378-dc925a4aa9d7.png)

At scales where the problem does occur, closing the app and relaunching doesn't help. Nor does reverting to factory settings.

**Comment by cbjeukendrup** [comment]
Does this still happen on the latest master branch? It was originally reported in #12786, which was fixed a few days ago.

**Comment by shoogle** [comment]
Ah, yes you're right. I thought I checked for duplicates but apparently not
