### ISSUE TITLE
[MU4 Issue] Ottava on notes stave locks linked tab stave

### ISSUE THREAD

**Issue by ThaBaer** [musescore/MuseScore#15344]
**Describe the bug**
It's a score for bass guitar with two linked staves: notes and tab.
Usually pitch and string can be changed on the tab stave by arrow up/down and ctrl-arrow up/down.
If an ottava (any) line is assigned to a measure in the notes stave, the tab stave locks and cannot be changed any more. Arrow keys do nothing.

**To Reproduce**
1. Create a new bass guitar score with notes stave and linked tab stave.
2. Enter some notes, try changing strings on tab stave -> works
3. Assign an ottava to the previously entered notes
4. Tab is automatically adjusted (I was absolutely thrilled when I noticed that! Awesome!)
5. Try changing strings on tab stave -> no reaction

**Expected behavior**
Strings on tab stave can be changed by selecting a note and using ctrl - arrow up/down

**Screenshots**
n/a

**Platform information**
Win 10

**Additional context**

**Comment by zacjansheski** [comment]
Closing this and referring to https://github.com/musescore/MuseScore/issues/15344
