### ISSUE TITLE
[MU4 Issue] Unable to Publish to Site or Export Audio

### ISSUE THREAD

**Issue by gsnutmeg** [musescore/MuseScore#15359]
**Describe the bug**
Upon reaching around 20% on the export progress bar, MuseScore 4 crashes, and the score never publishes or saves as an audio file.
Edit: This problem seems to only apply to larger scores (on the scale of a symphony orchestra). When attempting to export a smaller score (a woodwind quintet, total of 6 parts), the score exports as expected.
Edit 2: This problem also occurs when exporting a selection (done by using save selection and attempting to export the new file). The selection is the smallest .mscz file I have (and by smallest, I literally mean I've only selected and am trying to export a single part), and it still will not export, despite larger files exporting without issue.
Edit 3: I'm now unable to play the score in standard view without it crashing about 2 minutes in.

**To Reproduce**
1. Open a score
2. Go to "Publish"
3. Select "Publish to Musescore.com" or "Export"
4. Attempt to publish score or export as audio file
5. MS4 crashes once the "export" bar hits ~20%

**Expected behavior**
The score exports and publishes to the site.

**Platform information**
 - OS: Windows 11

**Additional context**
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz w/ 8GB RAM. Relatively weak, but should be able to handle exporting mp3 files of this size.

Link to score: https://drive.google.com/file/d/1HUyWgSjLaiorZszW-xhla7HdBzmKJj2w/view?usp=sharing

===========

Does anyone know if this is a MuseScore issue, or a hardware incompetency? Thanks ahead of time!

**Comment by gsnutmeg** [comment]
After doing some fiddling around and testing, I have a working theory (that is most likely inaccurate) that the "Publish" tab is the issue here. I can safely export other scores, even ones that are larger in file size than my problem score. However, my problem score seems to crash only when I am on the publish tab for an extended period of time. An issue with this theory is that, after creating a new score and pasting only individual parts, I still am unable to export. I'm truly at a loss for options.

The score in question: https://drive.google.com/file/d/1HUyWgSjLaiorZszW-xhla7HdBzmKJj2w/view?usp=sharing

**Comment by zacjansheski** [comment]
There have been improvements made since issue was reported.  Is this still actual?  I was able to publish the attached score without issue from a weak PC, it took a while but it worked :)

**Comment by zacjansheski** [comment]
Closing
