### ISSUE TITLE
[MU4 Issue] Maximised window has border which shows up on other monitors in multi monitor setups

### ISSUE THREAD

**Issue by 3dWrecker** [musescore/MuseScore#15356]
**Describe the bug**
White border around musescore window in maximised mode shows on multiple monitor setups.

**To Reproduce**
1. Have a multi-monitor setup.
2. Open musescore and maximise the window.

**Expected behavior**
The musescore window should maximise and be confined to the screen in which it was maximised.

**Screenshots**
![image](https://user-images.githubusercontent.com/34898242/208345181-f620a75b-dda1-4ee2-a5e8-1ecf83064758.png)

**Platform information**
Windows 10 22H2, OS BUILD 19045.2364

**Additional context**
The white line between the two screens in the screenshot is present on the right-hand moitor. Each monitor uses different scaling and resolution. The left monitor is 2560x1440 @ 100% and the right monitor is 1920x1080 @125%.

**Comment by 3dWrecker** [comment]
Probably related to #15233

**Comment by Eism** [comment]
Could you check the nightly build?
[MU4_223560304_Win_master](https://github.com/musescore/MuseScore/suites/10003500773/artifacts/485771616)

**Comment by 3dWrecker** [comment]
@Eism I can confirm the white line is gone in [MU4_223560304_Win_master](https://github.com/musescore/MuseScore/suites/10003500773/artifacts/485771616) and the window is confined to the screen.

**Comment by zacjansheski** [comment]
Closing per last comment
