### ISSUE TITLE
[MU4 Issue] MuseScore 4.0 does not build on Windows 10 x64 without undocumented SDK install and changes to projects

### ISSUE THREAD

**Issue by hanoixan** [musescore/MuseScore#15361]
**Describe the bug**
First of all, MuseScore 4 looks fantastic. I'm new to this software, but I just want to say congratulations on a fine product release.

Following the [compile instructions](https://musescore.org/en/handbook/developers-handbook/compilation/compile-instructions-windows-visual-studio) for a Standard Build on Windows, I get a slew of errors such as:

> musescore audio.lib(unity_0_cxx.obj) : error LNK2019: unresolved external symbol WINRT_GetRestrictedErrorInfo

The reply from @Jojo-Schmitz at https://musescore.org/en/node/338573 clued me in to install the Windows 10 SDK (10.0.20348.0). I had to pull it from [this Microsoft archive](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/), as it is not listed in the VS2019 Installer app.

After starting over and recaching CMake, I got the same error. I then had to select all the projects in the .sln and switch from 10.0.19041.0 to 10.0.20348.0. And voila, I have a running RelWithDebInfo build.

So, there are some potential necessary additions to the compile instructions I think, and possibly a misconfiguration for properly using the 20348 SDK in the VS projects.

**Platform information**
 - OS: Windows 10 Home 64bit

**Comment by Jojo-Schmitz** [comment]
It is in the VS2019 installer, that's where I got it from

**Comment by hanoixan** [comment]
I'm certain 20348 wasn't in the Workloads or Individual Components area of the VS Installer until I installed it from the archive. But, it could also be an issue specific to my system. I fully wiped and recloned from git, and CMake properly detected 20348 this time (vs. just removing the msvc.build_x64 folder, as I did before).

Now that I know that editing the build instructions is encouraged (which is great), I'll add a note in case 20348 is missing from others' VS installers. Thanks.

**Comment by Jojo-Schmitz** [comment]
It should probably go into https://github.com/musescore/MuseScore/wiki too

**Comment by hanoixan** [comment]
While 10.0.20348.0 is the correct SDK for Windows 10, is Windows 11 just the latest (10.0.22621.755)?

Also, the developer environment instructions on the wiki are very different than the compile instructions. I should leave updating that page to someone more seasoned on the project.

**Comment by Jojo-Schmitz** [comment]
Not sure it matters

**Comment by hanoixan** [comment]
Ok, added. Thanks for your help.
