### ISSUE TITLE
[MU4 Issue] Making a range cue-size reduces accidentals twice

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#15365]
**Describe the bug**
Selecting a range and checking 'cue size' makes the accidentals too small.

![image](https://user-images.githubusercontent.com/20604032/208390497-78f0c2be-8e5c-4835-9c7a-6767b9612bbe.png)

I assume this is because each item selected has 'cue size' applied; but when cue size is applied to a note, the accidental automatically scales to match it, so this is unnecessary.

Since we want to retain the ability to make an accidental cue-sized independently of the notehead, it makes sense for it to _possible_ to achieve a 'double-reduced' accidental, but it shouldn't be easy for this to happen 'by accident'. When a range of notes is made cue sized, accidentals should be skipped; the result is the same as if each chord were selected manually:

![image](https://user-images.githubusercontent.com/20604032/208391577-7f87484a-c9ec-4b8c-bf6f-5e0b3d4089ba.png)

OS: Artix Linux, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223530506, revision: github-musescore-musescore-5485621

**Comment by oMrSmith** [comment]
This issue makes it more complicated
to create cue notes in a part,
which already takes 10 steps.

**Comment by oktophonie** [comment]
Your haiku has slightly too many syllables, I'm afraid.

**Comment by DmitryArefiev** [comment]
Fixed in #16645

**Comment by Tantacrul** [comment]
Tested this again on MacOS. Still looks good. Nice work!
