### ISSUE TITLE
[MU4 Issue] Regression: Multi-measure rests break "hide when empty"

### ISSUE THREAD

**Issue by jeetee** [musescore/MuseScore#15368]
**Describe the bug**
A multi-measure rest is not considered "empty" for the "Hide when empty" logic

**To Reproduce**
1. Open https://musescore.org/sites/musescore.org/files/2022-12/Nur%20ein%20Wort.mscz
2. Notice how on the first and last system, all staves are shown even though "hide when empty" style setting (and first system subsetting too) are active.
3. Press "M" to toggle multimeasure rests off
4. Empty staves are now hidden (as expected)
5. Press "M" to toggle multimeasure rests back on
6. Error: Empty staves are made visible again

**Expected behavior**
A multimeasure rest condensed measure should be regarded as equally empty as when expanded.

**Platform information**
 - OS: Verified on Windows 10, but platform agnostic

**Additional context**
This is a regression compared to MS3.6.2

**Comment by oMrSmith** [comment]
(I confirm.)
