### ISSUE TITLE
[MU4 Issue] Tempo marking is only created at the top of system

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#15373]
**Describe the bug**
When creating a score, the tempo marking is only created at the top of the system and does not appear where the system object should appear.

**To Reproduce**
See video

https://user-images.githubusercontent.com/102702868/208415805-8eb3d553-bdfa-4edd-b04d-b96068aac255.mp4

**Platform information**
 - OS: Windows 11

**Comment by DmitryArefiev** [comment]
Fixed in #15397
