### ISSUE TITLE
[MU4 Issue] Playback problems related to tempo slider

### ISSUE THREAD

**Issue by daddadpfc** [musescore/MuseScore#15385]
Playback on the same file that performs well in 3.6.2 has several issues 4. 

The behaviour is inconsistent. Sometimes it behaves as shown, sometimes not. So far behaviour has not been that of 3.6.2. files. I am getting some success with some other files however when there is a problem file it seems to stay a problem file.

Multiple versions of a track playing at the same time. Might be related to confusing "repeat" notation
Skipping bars
Delay between bars
tracking curser skipping bars

Dropbox Link to video of MS3 and MS4 playback and also MS3 file and MS4 file: 

https://www.dropbox.com/scl/fo/6v0ckrokrzn5hx77h30c1/h?dl=0&rlkey=n2ei87jb7qux1bs4s1jco9ghp

MacOS Monterey 12.6.2
Macbookpro early 2015
2.7GHz dual core intel core i5
8GB 1867 MHz DDR3

**Comment by daddadpfc** [comment]
Thanks for responding so promptly Casper. I thought you were correct as it played at 100% without issue.... right up until the repeat bar then it all went very weirdly wrong I'm afraid. It jumped early back to the start of the repeat but only gave silence for several seconds.

I've posted another video into the dropbox link

**Comment by cbjeukendrup** [comment]
Hm... what's strange is that that video doesn't sound like 100% speed to me; it still sounds like 65%. That would mean that the slider somehow got disconnected from the actual playback. I've not managed to reproduce that, so far.

**Comment by daddadpfc** [comment]
I thought that too.

is there any other information I can provide?

**Comment by daddadpfc** [comment]
Ive done a fair bit of investigation on this over the last few days. It appears to me the behaviour is specific to the scrubber slider. I thought I have files that worked fine using the slider. I was mistaken. It appears to impact all the files I have.

I tried to copy  a line of the music into a new file and see if that works. it doesnt.

I tried writing a new file. random notes. It gets totally confused. 

I have tried changing the note = 120 to 80 as written text. unfortunately its the same result.

The question is whether this is unique to my download or is everybody experiencing this?

Do I delete and reload the software? Any suggestions?

**Comment by GeertWil** [comment]
Same problem here. Playback is perfect only at 100%.
If you pay attention to the metronome click in the attached file, you can clearly here that at certain point 2 fragments are played at the same time time. A few moments later 3 or even more fragments are played at the same time. 


https://user-images.githubusercontent.com/9659505/209166911-27fefef3-5313-44e7-9c10-b50003e0288b.mp4

**Comment by daddadpfc** [comment]
thats exactly the behaviour I am experiencing

**Comment by GeertWil** [comment]
I think this bug is releated to the repeats. If I uncheck "Play repeats" in the Playback Controls, this weird behavior does not happen.

**Comment by daddadpfc** [comment]
Well done. Yes I see that now. the slower speed on the slider works correctly if you remove repeats. Something to add to dialogue which I have just confirmed is that "unticking" the play repeats needed to be repeated. This has happened on more than one file. When I did it the first time the tick reappeared with the same behaviour. Unticking repeats a second time removed the behaviour of multiple voices and skipping.

**Comment by daddadpfc** [comment]
I hope my comment was clear. I think the  untick process of the "repeats" option is required more than once.

the Un-repeats needs repeated ... urghhh!

**Comment by daddadpfc** [comment]
Another update. I notice even with the repeats option unticked the curser lagged behind the melody significantly. In the file I shared it ends up 4 bars behind the playback sound.

**Comment by daddadpfc** [comment]
I can confirm this is not resolved by 4.01. Is there any indication about where this in a priority list? ATM I am just using 3.6. I appreciate efforts being made.

**Comment by cbjeukendrup** [comment]
@Tantacrul Could you prioritise this one?

**Comment by Tantacrul** [comment]
This is an excellently described bug @daddadpfc! Thanks for the files too. Definitely a patch candidate.

**Comment by DmitryArefiev** [comment]
Fixed in #16045

**Comment by DmitryArefiev** [comment]
Retested on Win10
