### ISSUE TITLE
[MU4 Issue] Increase measure duration changes the duration of next measure.

### ISSUE THREAD

**Issue by Coxev** [musescore/MuseScore#15388]
**Describe the bug**
When increasing the duration of a measure which contains notes, the duration of the next measure is equal to the difference between the new measure duration and the old one.

**To Reproduce**
1. Enter some notes in a measure.
2. Increase its duration by *x* beats.
3. See that the next measure's duration is equal to *x*.
(4. When deleting the measure content, its duration goes back to the new one.) 

**Expected behavior**
Increasing a measure duration should not affect the next measure. It should only increase the current measure duration.

**Screenshots**
https://user-images.githubusercontent.com/39700491/208474506-da51965c-6afa-41f2-be40-4bf75d91230e.mp4

**Platform information**
 - OS: Windows

**Comment by cbjeukendrup** [comment]
Ha, you're not the only one who reports this issue today: see https://github.com/musescore/MuseScore/issues/15358, which I just fixed in #15380. The fix will be included in the first patch release (I don't know when that will be released though).
