### ISSUE TITLE
[MU4 Issue] File picker does not show .mscz files on linux

### ISSUE THREAD

**Issue by Dunkhan** [musescore/MuseScore#15396]
**Describe the bug**
The file -> open menu does not display any files

**To Reproduce**
1. The file menu
2. Click on open
3. In the pop up file picker window, navigate to a directory with .mscz files in it
4. Observe that these files do not display
5. Check different file type filters
6. Observe that none of the filters solve the issue including 'all supported files'

**Expected behavior**
The files should be shown in the file picker, double clicking one of them should open the file.

**Screenshots**
![MuseScoreBug](https://user-images.githubusercontent.com/4968631/208516624-c63b95bb-8a99-4d59-bed7-92567c03648e.png)
In the screenshot I have opened my filebrowser on the right and the musescore filepicker on the left to compare

**Platform information**
 - OS: Linux Mint 20.3 Cinnamon

**Additional context**
It is unlikely that this issue is affecting everyone, or even affecting all linux users, as it seems like it would have been noticed by now if it were. With that in mind I am available for further testing and debugging. I have worked as both a professional QA tester and also as a programmer so let me know if there is anything I can do on my end.

**Comment by MarcSabatella** [comment]
Definitely not affecting all Linux users - plenty of us are using it successfully.

You r screenshot shows two totally different pathnames.  Are these links that you had set up in a way that you expected to resolve to the same place?  What happens if you actually navigate to the same path?

**Comment by Dunkhan** [comment]
How embarrassing :-(
