### ISSUE TITLE
[MU4 Issue] Two measure repeat signs behave like 1 measure repeat signs in playback

### ISSUE THREAD

**Issue by donnybeelo** [musescore/MuseScore#15392]
**Describe the bug**
When entering a two measure repeat sign or four measure repeat sign, the symbol is engraved correctly, but upon playback it behaves identically to a regular single measure repeat sign, meaning it repeats the bar right before it and then stays silent for the rest of the bars the symbol encompasses.

**To Reproduce**
1. Make a new score
2. Write two bars worth of music
3. Enter a two measure repeat sign (named "Repeat last two bars" underneath the "More" box in the "Repeats & jumps" section on the left sidebar)
4. Press the play button

**Expected behavior**
The two bars that have been written should be played back twice

**Observed behavior**
https://user-images.githubusercontent.com/44618024/208490294-7738be9c-8d35-4aca-a7a9-1ca6adc6456f.mp4

**Platform information**
 - OS: Windows 11

**Comment by cbjeukendrup** [comment]
This is a known issue; see #10922. I'll close this as a duplicate. Thanks for reporting!
