### ISSUE TITLE
[MU4 Issue] Multi-measure rests do not scale

### ISSUE THREAD

**Issue by derjonasda** [musescore/MuseScore#15390]
**Describe the bug**
Multi-measure rests do not scale how it should.

**To Reproduce**
1) Change the scale in the "Staff/Part properties".
2) Long pauses are now not scaled.
3) This happens both in the full score and in individual parts

**Expected behavior**
The rest bar also scales in the same ratio of the staff.

**Screenshots**
![Example_1](https://user-images.githubusercontent.com/121052482/208487752-a37200e6-b0ef-46ed-9892-d7974288808f.png)

**Platform information**
 - Windows

**Comment by cbjeukendrup** [comment]
@oktophonie I think that if you specify the design for this, this might be a nice issue for contributors from the community.
