### ISSUE TITLE
[MU4 Issue] Stem disappears when adjusting beam height over rests (MU3 import)

### ISSUE THREAD

**Issue by denischevalier** [musescore/MuseScore#15401]
**Describe the bug**
When adjusting beam height in tuplet where the first note is a ~silence~ rest, the stem disappears

**To Reproduce**
1. On MuseScore 3.6.2, create a new score.
2. On the first bar, create a triolet on the first beat. 
3. Fill a middle c at the second part of the triolet.
4. Select the first note (silence) of the triolet, and in the palette, go to "beam properties", and select the "bean start" option.
5. Select the last note (silence) of the triolet, and in the palette, go to "beam properties", and select the "bean middle" option.
6. Save your score.
7. Open the score on MuseScore 4.
8. The beam crosses the ~silences~ rest.
9. Try to adjust the beam height.
10. The C4 stem disappears.

**Expected behavior**
At step 8: The bean does not cross the ~silences~ rest.
At step 10: The stem stretches to the beam.

**Screenshots**
At step 8:
<img width="172" alt="image" src="https://user-images.githubusercontent.com/7075183/208541084-8a15d789-6cea-49ae-aca8-6f9fdc802355.png">

At step 10: 
<img width="172" alt="image" src="https://user-images.githubusercontent.com/7075183/208541159-42cc1db3-96ee-49ec-9fee-32b2b6c382f4.png">

**Platform information**
MuseScore 3:
- OS: macOS 10.16,
- Arch.: x86_64,
- MuseScore version (64-bit): 3.6.2.548020600,
- revision: github-musescore-musescore-3224f34

MuseScore 4:
- OS: macOS 12.6,
- Arch.: x86_64,
- MuseScore version (64-bit): 4.0.0-223472200,
- revision: github-musescore-musescore-5485621
- Installed through MuseHub

**Additional context**
The bug does not apply if only one of steps 4 and 5 is applied.
There is another bug: On MU4, this behavior (applying "beam start" or "beam middle" to a silence) doesn't seem to be doable.

**Comment by denischevalier** [comment]
Note, the bug appears also outside of tuplets, on this pattern: 
<img width="75" alt="image" src="https://user-images.githubusercontent.com/7075183/208546981-e814a3e1-8fdf-41aa-b975-4896de38d7ef.png">

**Comment by miwelte** [comment]
Confirmed. Same here:
OS: Windows 10 22H2, Dell 5520 Xeon E3-1505M 32GB RAM
MU4 revision: github-musescore-musescore-5485621

**Comment by asattely** [comment]
This is fixed by PR https://github.com/musescore/MuseScore/pull/15383, please confirm

**Comment by Jojo-Schmitz** [comment]
(and change "silence" to "rest")

**Comment by asattely** [comment]
#15383 Now fixes this one, if you'd like to use that build to verify the issue has been fixed

**Comment by denischevalier** [comment]
> #15383 Now fixes this one, if you'd like to use that build to verify the issue has been fixed

I'll try it as soon as I have some time, thanks!

**Comment by bkunda** [comment]
Re-tested on macOS. 
Certainly, the stem no longer disappears, which would suggest this problem has been fixed. 
@oktophonie there's obviously some work still to be done here, but I expect what we're seeing in the below video lies outside the realm of the present issue (please confirm):

https://user-images.githubusercontent.com/86290556/222765532-6e43dfa1-894d-4682-8b7c-343d4ca7f187.mov


If addressing the behaviour of the stem (i.e. so it doesn't disappear) does mean this issue has been fully resolved, then we can move it to the [Done - Tested again](https://github.com/musescore/MuseScore/projects/62#column-19380613) project.

**Comment by oktophonie** [comment]
The other issues are indeed quite separate (but could perhaps do with being filed independently!) 🥺

**Comment by bkunda** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adjusting stem height over tuplets](https://trello.com/c/klCUmRB4/215-adjusting-stem-height-over-tuplets)
