### ISSUE TITLE
[MU4 Issue] Reset All Page Settings to Default doesn't update score

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#15409]
**Describe the bug**
See video

https://user-images.githubusercontent.com/102702868/208554342-9891d0d3-c78a-4d5a-9acf-a45caafd32a7.mp4

**Platform information**
 - OS: Windows 11

**Comment by octopols** [comment]
Is the issue still not fixed? I can see a pull request which shows reset working or is there something wrong with that?

**Comment by cbjeukendrup** [comment]
The pull request is fine, but the problem was that the author had not signed the CLA yet at that point so we couldn't merge it. But that's changed now, so I'll take another look at it. (Thanks for the reminder!)
