### ISSUE TITLE
[MU4 Issue] Entering lyrics for multiple notes: Dialog is confused

### ISSUE THREAD

**Issue by BenWiederhake** [musescore/MuseScore#15406]
**Describe the bug**
Entering lyrics is very counter-intuitive. Ctrl-L refuses to work even when it could make a safe, correctable guess.

**To Reproduce**
Steps to reproduce behavior 1:
1. Have a single staff, of type "voice" ("Gesang") with some notes on it, and no lyrics so far. So there's no real question about where the lyrics should go.
2. Select the Menu Add > Text > Lyrics (… I guess. I use the German version, and I see the labels "Hinzufügen > Text > Liedtext")
3. See an error dialog.

Steps to reproduce behavior 2:
1. Have a single staff, of type "voice" ("Gesang") with some notes on it, and no lyrics so far. So there's no real question about where the lyrics should go.
2. Select two notes (because a single syllable should be sung at these two notes) by pressing the shift key and dragging with the left mouse button
3. Press Ctrl-L to add lyrics
4. See an error dialog that contradicts reality.

**Expected behavior**
In both cases, I expected MuseScore to create a lyrics textbox and move my text cursor there, so that I can begin typing the lyrics.

I know, I've read ~~[the manual](https://musescore.org/en/handbook/3/lyrics) in the meantime~~ oh, I've been reading the wrong manual, my bad.

Now I've read [the manual](https://musescore.org/en/handbook/4/lyrics), and I understand how it works, so it's a solved problem, but the error message is silly enough that I want to show it here.

**Screenshots**
MuseScore thinks that, because two notes are selected, no note is selected:
![Bildschirmfoto_2022-12-20_00-37-47](https://user-images.githubusercontent.com/2690845/208550086-d37503da-1ee1-4fc5-90b3-0d8bee2d73ca.png)
Rough translation: "No note or pause selected. Please select a note or a pause and try again."

**Platform information**
 - OS: Linux, but I don't think that's relevant.

**Additional context**
None

**Additional questions**
Could [the search](https://musescore.org/en/search/content?keys=lyrics) be changed to prefer MuseScore 4 help pages? Also, perhaps the manual could include some form of marker which version of MuseScore it's about, that might be helpful. I only noticed that I'm reading the wrong manual because I double-checked the link when pasting it here.

**Comment by BenWiederhake** [comment]
Very similar issue, but I'm not sure whether it should go into a separate ticket:
I selected a bar (accidentally thinking that I selected the whole-bar pause), and tried to add a tempo annotation. I'd argue that it is a reasonable thing to try, but MuseScore disagrees:
![Bildschirmfoto_2022-12-20_02-16-53](https://user-images.githubusercontent.com/2690845/208558881-264b3fbd-181b-4685-81b4-b2a810c24498.png)
I achnowledge that it's not really a bug, but it also feels like there's room for improvement.

**Comment by oMrSmith** [comment]
The problem is the lack of precision in the language: It should better say "Keine einzelne Note oder Pause gewählt."

**Comment by BenWiederhake** [comment]
Still happens with MuseScore 4.1.0 (`OS: Debian GNU/Linux trixie/sid, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a`)

**Comment by cbjeukendrup** [comment]
IMO the real solution is that we avoid the need for a dialog at all, and just make it work :)

**Comment by mmeyn** [comment]
Some of these are fixed/behaviour changed in version 4.1.1:

- Adding a tempo mark to a selected measure works as expected.
- Adding lyrics via the shortcut Ctrl+L or the main menu works in the sense that the lyric text is added to the last note of the selection (though it should be the first note as @cbjeukendrup suggested).
- Adding lyrics to a selected measure does not work.
- Adding lyrics to nothing selected does not work but I would not expect that. Of course you could argue that it’s clear what the user wants in the case of only one voice but this is a special case.

Note that there’s a difference between selecting a measure or all notes in a measure (even when the blue selection rectangle has the exact same size in both cases).

**Comment by Cameron-Whyte** [comment]
I'd like to take a look at this issue. @mathesoncalum
