### ISSUE TITLE
Solo Viola in string quartets too quiet - demo

### ISSUE THREAD

**Issue by macgarvin** [musescore/MuseScore#15405]
Solo viola too quiet relative to the other three instruments in quartet

**Steps to reproduce the behavior**
Play this attached 8 bar extract:
[Demo Solo viola too quiet.mscz.zip](https://github.com/musescore/MuseScore/files/10263474/Demo.Solo.viola.too.quiet.mscz.zip)

This is a copy and paste from bars 77-85 Beethoven String Quartet Op.59 no. 3, transcribed by Friedrich Hueppe https://musescore.com/user/1021946/scores/5151753 (which displays the same issue)

Although the viola passage has the same dynamic markings as the other instruments it is much fainter. Particularly noticeable in the solo passage in  bars 2 and 5, but I think it is consistent throughout

**Expected behavior**
In the mss and real instrument performances the viola sound level is similar to the other instruments, certainly not drowned out as here.

**Screenshot**
<img width="524" alt="Screenshot 2022-12-19 at 23 06 42" src="https://user-images.githubusercontent.com/31008354/208545407-80295c9c-f0fa-4d66-a999-264e1cbd47f4.png">

**Platform information**
15" MacBook Pro 2017; macOS 13.0.1; latest Musesounds beta as of 19 December; Current Musesounds as of 21.00 hours UTC

**Additional context**
NB in the simple scale demo of the four string quartet instruments produced by [abariska](https://github.com/abariska) addressing another dynamics issue ( #15144), the viola acro sections sound ok

Aside - note the two weird bad notes in bar 4 of the clip and in the original trs.

**Comment by Vykoiazon** [comment]
the volume of the other instruments can be lowered in the mixer for a temporary fix

**Comment by Vincentwang987** [comment]
I think now that Muse Strings 0.4.20 came out, this may have been fixed.

**Comment by FrancRos31** [comment]
> I think now that Muse Strings 0.4.20 came out, this may have been fixed.

Yeah, check #22655.

**Comment by macgarvin** [comment]
Thanks for the heads up - I look forward to trying 0.4.20

**Comment by cbjeukendrup** [comment]
Closing this as per the comments above. In case there are further issues with Muse Sounds, it's best to report them directly via Muse Hub (version 2.0, see https://musehub.com if you still have version 1). Thanks!
