### ISSUE TITLE
[MU4 Issue] German note name "H" not recognized in German locale

### ISSUE THREAD

**Issue by BenWiederhake** [musescore/MuseScore#15404]
**Describe the bug**
Notes can be input by typing their names. Awesome!
I can input a "G" by typing "G". Nice and simple!
And I can input an "H" by typing … "B". *rolls eyes*

I'm sure you know what's going on, but just in case: In [Germany and many other countries, the notes are called "A H C D E F G"](https://en.wikipedia.org/wiki/Musical_note#12-tone_chromatic_scale). And to make things really awkward, the German "B" is the English "B flat".

I'll be the first to admit that the German system is stupid. But it's how German users think, were taught in (music)school, and what they/we would assume is how the shortcuts work, *especially* when presented with a German-language GUI.

**To Reproduce**
1. Open MuseScore in a German locale
2. In a new stave, type on your keyboard the letters (not spaces) "C D E F G A H C"

**Expected behavior**
The full scale in C major should be written down.

**Actual behavior**
The partial scale in C major should be written down, with "H" missing, because in the English system that note would be called "B".

**Screenshots**
![Bildschirmfoto_2022-12-20_00-13-48](https://user-images.githubusercontent.com/2690845/208546167-61da8990-5db8-4e1e-9e06-1bfc5f443c42.png)

**Platform information**
 - OS: Linux
 - Locale: German (text, datetime, numbers, everything)

**Additional context**
I know, this problem is terrible and causes headaches, and I have absolutely no suggestion or even idea how to handle the German "B" (English "B flat"). Not handling it at all seems like a reasonable compromise.

However, it seems that the key "H" isn't bound to any shortcut. So I would argue that if the user presses "H", then the only possible thing they might want is a "B" note to appear. In that case, the shortcuts don't need to depend on the user's locale. Is that perhaps an option?

**Comment by oMrSmith** [comment]
I think you can change the shortcut to enter the note "B" to "H" :P.

**Comment by BenWiederhake** [comment]
That looks so silly :D
![Bildschirmfoto_2022-12-20_03-08-10](https://user-images.githubusercontent.com/2690845/208564366-2cb8f1a3-c8ec-47c9-81e1-e3696a7505f8.png)

**Comment by BenWiederhake** [comment]
Looks like another visual glitch, but I guess that's alright ^^
![Bildschirmfoto_2022-12-20_03-09-14](https://user-images.githubusercontent.com/2690845/208564510-77e0eef8-1cce-426c-92b2-991f2f039324.png)

**Comment by oMrSmith** [comment]
Harhar, stimmt schon auf der anderen Seite werden die Akkordsymbole auch mit den englischen Tonnamen eingegeben. Dann würde man H drücken und "B" sehen...

**Comment by cbjeukendrup** [comment]
> Looks like another visual glitch, but I guess that's alright ^^
> ![Bildschirmfoto_2022-12-20_03-09-14](https://user-images.githubusercontent.com/2690845/208564510-77e0eef8-1cce-426c-92b2-991f2f039324.png)

I just fixed this in the German translation (https://www.transifex.com/musescore/musescore/translate/#de), so if you wait 15 minutes from now and then go to Preferences, click "Check for language updates" and restart MuseScore, this should be fixed.

**Comment by BenWiederhake** [comment]
Just as a data point: This particular translation should probably also be adapted:
![Bildschirmfoto_2023-02-05_00-10-06](https://user-images.githubusercontent.com/2690845/216793431-88483378-a76a-494d-8d13-1dacd7a7889f.png)

**Comment by Jojo-Schmitz** [comment]
B-Dur/g-Moll is correct (for 2 flats), don't confuse with H-Dur/gis-moll (5 sharps)

**Comment by Jojo-Schmitz** [comment]
I believe we could ship shortcuts.xml with B **and** H being the shortcut for entering a B (German H)
```xml
...
    <SC>
        <key>insert-b</key>
        <seq>Ctrl+Shift+B</seq>
        <seq>Ctrl+Shift+H</seq>
    </SC>
 ...
    <SC>
        <key>note-b</key>
        <seq>B</seq>
        <seq>H</seq>
    </SC>
    <SC>
        <key>chord-b</key>
        <seq>Shift+B</seq>
        <seq>Shift+H</seq>
    </SC>
...

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz I heard that @bkunda is not against, so feel free to turn that into a PR :)

**Comment by Jojo-Schmitz** [comment]
There we go: #22569
