### ISSUE TITLE
[MU4 Issue] Resolution settings not initially present when exporting as PDF 

### ISSUE THREAD

**Issue by Leonerd-04** [musescore/MuseScore#15417]
**Describe the bug**
The Resolution option isn't initially available when exporting as a PDF:
![No DPI settings](https://user-images.githubusercontent.com/87563929/208618135-90bf2df2-c626-4257-b39d-f7958d02ba28.png)

**Expected behavior**
The Resolution option should be visible, below the format selector. I was able to bring it back by selecting any other format and then selecting PDF again:
![DPI settings present](https://user-images.githubusercontent.com/87563929/208618449-2c4b7841-3d04-4871-92cf-e219f6e767d6.png)

**Platform information**
 - OS: KDE Neon on Ubuntu 22.04

**Comment by DmitryArefiev** [comment]
Confirm on my side. This is **regression** from **MS3**. Thanks for logging!


https://user-images.githubusercontent.com/90187801/224036668-6c7c1130-550b-4d2d-a23c-3cd97bc5550b.mp4

**Comment by DmitryArefiev** [comment]
Fixed in #16837
