### ISSUE TITLE
[MU4 Issue] Project settings has visual overflow despite hardcoded size

### ISSUE THREAD

**Issue by BenWiederhake** [musescore/MuseScore#15411]
**Describe the bug**
In the project settings, the label "MuseScore-Version" doesn't fit in its fixed-size space, causing ellipsis to be displayed instead: "MuseScore-Ve…"

**To Reproduce**
1. Open MuseScore
2. In the Menu, go to "File > Project settings" (I guess; in the German version it's "Datei > Projekteigenschaften")

**Expected behavior**
All text labels should be legible, or at least there should be a way to make them legible (resizable window, resizable container, scrolling, tooltip).

**Screenshots**
![Bildschirmfoto_2022-12-20_01-55-03](https://user-images.githubusercontent.com/2690845/208556873-8f1970be-b0a9-45a7-a49a-3e5beec15dbc.png)

**Platform information**
 - OS: Linux
 - German locale
 - I'm not entirely sure about my font-setup, but I would assume that all relevant fonts are installed (most importantly all microsoft-fonts are there), so that shouldn't be an issue.

**Additional context**
Those hardcoded sizes seem to be a real bummer :/
Related, but different window: #15395

**Comment by thewindsofwinter** [comment]
Hi, if no one's taken this I can grab it! Am new to this project so may need some guidance, will hopefully put up a PR soon (today?) 😅

**Comment by cbjeukendrup** [comment]
@thewindsofwinter Welcome! Feel free to work on this.

**Comment by RobFog** [comment]
> […] Am new to this project so may need some guidance […]

Have you discovered the MuseScore Discord server? It's the best place to ask questions relating to MuseScore development. You can join here: https://discord.gg/HwHhXEbJ4r

**Comment by thewindsofwinter** [comment]
Thanks for the resources!

**Comment by Ts0117** [comment]
Hi, are you still working on this? @thewindsofwinter 😊

**Comment by ayushsingh01042003** [comment]
Hey i noticed that the code relevant to this issue happens to be in the musescore-old repo now does that mean is it still open to work or not? if it is, do i fork the musescore-old repo and work on it?

**Comment by cbjeukendrup** [comment]
You shouldn't do anything with the musescore-old repo, and that repo has nothing to with any recent version of MuseScore. Everything is in this repo, and the relevant code for this issue is in the file called `ProjectPropertiesDialog.qml` (or in the files referenced from there).

**Comment by ryan-roche** [comment]
It appears that there aren't currently any assignees on this issue. I'd love to try my hand at this as a first issue.

**Comment by ryan-roche** [comment]
<img width="824" alt="image" src="https://user-images.githubusercontent.com/48164514/227795132-804becd1-d031-49fb-8559-8282ca88d35f.png">

Can confirm that the issue occurs on macOS w/ US English locale, as well.

**Comment by ryan-roche** [comment]
Update- I replaced the inherited, hard-coded propertyNameWidth value with `t_metrics.tightBoundingRect.width`, which obtains the width of an "imaginary" bounding box surrounding the text. This fixes the truncation, as shown below:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/48164514/227802519-130efe5b-4f4a-4fbc-a4f8-831015226acd.png">

Using this bounding-box value instead of a hard-coded value also allows the sizing to adapt to other languages:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/48164514/227802611-c77ef840-db94-43cb-9633-aaf739897d6b.png">

Since this issue only pertains to the "Musescore version" field, I only altered that particular element.

I've created a pull request: #17019

**Comment by thewindsofwinter** [comment]
Hi! Sorry for this: wasn't sure how to test different displays on Windows, so was having a lot of trouble figuring out whether stuff was working. Glad someone else picked it up, really sorry about the delay.

**Comment by jessjwilliamson** [comment]
> @ryan-roche Can you explain to me what the `t_metrics` object is? I can't find any information about it anywhere, and it's not in the qt source code (version 5.15.3). In any case, it seems like it's some private property, and in QML it's better not to use such properties. We need to find a more straightforward solution that's easier to understand.
> 
> @jessjwilliamson We need your help first. Can you take a look and suggest the best way to solve this problem? Do you like Ryan's solution? (visually)

It's fine :)

**Comment by Jojo-Schmitz** [comment]
Reg. `t_metrics`, see https://stackoverflow.com/questions/36364168/can-i-get-the-real-width-height-of-a-text-element

**Comment by Eism** [comment]
We can just remove this line and it works for me 
https://github.com/musescore/MuseScore/pull/17019/files#diff-0ad192bd592b87f013eebf577fe0a6e74d2a5c7e9c590658765fa6ed633fbabeL81

@ryan-roche can you confirm my guess?

**Comment by BenWiederhake** [comment]
Still happens with MuseScore 4.1.0 (`OS: Debian GNU/Linux trixie/sid, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a`)
![Bildschirmfoto_2023-07-16_16-33-29](https://github.com/musescore/MuseScore/assets/2690845/dbdf7783-fe77-413d-9ca5-3ebf70a67328)

**Comment by MaxiSchwindler** [comment]
> We can just remove this line and it works for me https://github.com/musescore/MuseScore/pull/17019/files#diff-0ad192bd592b87f013eebf577fe0a6e74d2a5c7e9c590658765fa6ed633fbabeL81
> 
> @ryan-roche can you confirm my guess?

At least for me (Linux), this works; I created a pull request (#19280) which does exactly that
