### ISSUE TITLE
[MU4 Issue] Regression: Missing File Operation buttons

### ISSUE THREAD

**Issue by jeetee** [musescore/MuseScore#15426]
**Describe the bug**
File operation buttons (New / Open / Save) are no longer present. It seems especially the latter is quite dear to some users.

**Expected behavior**
While we don't ask for those buttons to eat up space by default it would be nice if via the toolbar customization there was the option to customizing them back in.

Given that the file action icons are available in the icon font (shown in the menu items) and the actions themselves are still present and fully functioning this *feels* like it could be a good beginner task.

**Comment by Tantacrul** [comment]
I'm sorry but a dedicated save button is going to have to stay in the 90's where it belongs. I know some people will be annoyed but it's not worth accommodating.

**Comment by Jojo-Schmitz** [comment]
Got requested again in https://musescore.org/en/node/339494

**Comment by Tantacrul** [comment]
It will come up a few times. No change meets zero resistance. We are not putting a save button on the top bar again.
