### ISSUE TITLE
[MU4 Issue] Grace note beam direction is sometimes off

### ISSUE THREAD

**Issue by Harmoniker1** [musescore/MuseScore#15422]
**Describe the bug**
The beam should be heading downwards rather than upwards. In this case it only happens when the grace notes are 32nd or shorter
![image](https://user-images.githubusercontent.com/46259489/208641031-36d1e99a-cb79-453b-b66b-8ab1e17d862a.png)

**Platform information**
 - OS: Windows 11

**Comment by Jojo-Schmitz** [comment]
BTW: this is a regression vs. Mu3...
