### ISSUE TITLE
Tied notes occasionally not playing full length[MU4 Issue]

### ISSUE THREAD

**Issue by bryandadson** [musescore/MuseScore#15429]
**Describe the bug**
A short and clear description of what the bug is.
Tied notes occasionally do note play full length, especially if a long held tied note over several measures.
**To Reproduce**
1. Go to organ or voices (may also happen to others - I have not tried)
2. Insert several measures of a single tied note (eg 10 measures of A4)
3. Playback will occasionally stop during one of these notes (eg on 2nd quarter), ending playback of whole stretch of tied notes
4. Not always reproducible, but has occurred previously at different places and times.

**Expected behavior**
Playback to begin at start of long tied stretch and end at the finish of tied stretch, sounding as one long unbroken sound.

**Screenshots**
![Musescore github](https://user-images.githubusercontent.com/120390381/208662230-290062d4-5813-4677-a481-4d1efde4d59f.png)

**Platform information
 - OS: Windows 11

**Additional context**

**Comment by cbjeukendrup** [comment]
Does this happen with MS Basic, or with Muse Sounds, or with both?

**Comment by bryandadson** [comment]
This is with the is with the Organ sound (not pipe organ) on MS Basic. I have tried copying and pasting identical notes from other bars which sound full length and also copying them into the non-playing right hand staff to see if it is an issue with the individual measure in that stave or an issue with the whole instrument. At this time I have not resolved it by tinkering...

**Comment by cbjeukendrup** [comment]
Hm, yeah, now I can confirm. For me it happens consistently with very long notes (the fact that they are notated with ties seems not to make a difference), but only with Organ from MS Basic. It looks like the notes are played a certain percentage too short.

**Comment by adazem009** [comment]
I'm not sure whether this is related, but this also happens when there's a tempo change. Here's a minimal example:

![Screenshot](https://github.com/musescore/MuseScore/assets/68537469/5205d6e9-89ec-4564-b2a5-073648c5190f)

If I remove the ritardando, everything is working fine.

**Comment by cbjeukendrup** [comment]
(And the problem from adazem900's comment is a different issue, but covered by #14369)
