### ISSUE TITLE
[MU4 Issue] Changing colors on note head/stem/beam does not work (not voicings)

### ISSUE THREAD

**Issue by miwelte** [musescore/MuseScore#15433]
**Describe the bug**
Changing colors on note head/stem/beam does not work via appearance does not wok after opening a scrore from MU3 and having saved it in MU4 format. If note head/stem/beam colors on score were changed from defalult to e.g. red in MU3 (e.g. as a reminder) and than opened in MU4 it is not possible to change them completely to another or default color. Stems and beams keep their existing color, regardless of whether one or more elements were selected.

**To Reproduce**
1. Open a score that was was previously saved in MU3 and where one ore more note note heads/stems/beams have been changed in color (not by voicings)
2. Go to 'File > Save as ...' and save/convert score to MU4
3. Select 'score' in 'page view' (any other views do not work either)
4. Select one ore more note elements
5. Go to 'Properties > Appearance > Color' 
6. Select any color from panel that is not the current elemnt color and click 'OK'

**Expected behavior**
Colors of all selected elements should have changes to the selected new color.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/77207091/208676144-7cbe1ac9-0ba6-419c-bedd-65e2dc317d2f.png)

**Platform information**
 - OS: Windows 10 22H2, Dell 5520 Xeon E3-1505M 32GB RAM 
 - MU4 revision: github-musescore-musescore-5485621

**Additional context**
Sometimes MU4 crashes completely while trying so as descibed in "To Reproduce". 
Feels like a classic 'null pionter / out of range' crash.

**Workaround**
Change beam/stem properties temporarily (back and forth) while having selected the desired color beorehand.

**Comment by icmporto** [comment]
The stem itself doesnt change of colors either

**Comment by oktophonie** [comment]
These issues are fixed by https://github.com/musescore/MuseScore/pull/15970
(You can test this yourself with a nightly build of master or 4.0.2, if you wish)
