### ISSUE TITLE
[MU4 Issue] [Assert] Crash on deleting characters in a Text

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#15432]
**Describe the bug**
When you delete the last character in a Text, MU crashes

**To Reproduce**
1. Open a build with asserts enabled (like Debug)
2. Open a score
3. Add a Staff Text
4. Delete the characters in the Text
5. MU4 crashes on deleting the last character

**Expected behavior**
MU4 should not crash

**Screenshots**
[Screencast from 20-12-22 06:37:32 PM IST.webm](https://user-images.githubusercontent.com/88136054/208674610-cde5b41f-aa1f-43eb-9299-b7b666678bd5.webm)

**Platform information**
 - OS: Ubuntu 22.04 LTS

**Additional context**

**This happens only in Assert builds and not release builds**

**Comment by cbjeukendrup** [comment]
@HemantAntony Is this still actual?

**Comment by HemantAntony** [comment]
No, this can no longer be reproduced :)
