### ISSUE TITLE
[MU4 Issue] (Windows) Title bar font setting

### ISSUE THREAD

**Issue by Hulenkius** [musescore/MuseScore#15430]
**Describe the bug**
Font of title bar text won't follow the setting in the Preference.

**To Reproduce**
Like this gif shows:
![字](https://user-images.githubusercontent.com/32562298/208667680-ccaec8da-b59b-48a9-8d3c-fed6fc8e4047.gif)

**Platform information**
 - OS: Windows

**Comment by Eism** [comment]
It is by design
See https://github.com/musescore/MuseScore/issues/15187

Anyway, thanks for reporting!
