### ISSUE TITLE
[MU4 Issue] Palettes remain stuck open after aborting search with Esc-key

### ISSUE THREAD

**Issue by BenWiederhake** [musescore/MuseScore#15449]
**Describe the bug**
In the "Palettes" tab, it is possible to get the menus (e.g. clefs, keys, measures, tempos, etc.) stuck open. All ways to collapse them stop working.

**To Reproduce**
1. Open MU4, begin editing a new partiture.
2. In the "Palettes" tab, click on the magnification glass to bring up the search box, and type something, e.g. "nonexistent"
3. Press and release the "Esc" key to abort the search.

**Expected behavior**
1. The clef/key/measure/tempo/etc. menus should all go back to their previous state
2. Furthermore, It should still be possible to collapse/expand each menu at will.

**Actual behavior**
1. All such menus are now expanded, despite being collapsed initially.
2. It seems impossible to collapse them. Clicking on the menu label (e.g. "Schlüssel") has no effect, clicking on the little arrow beside it has no effect, and (the three dots next to the word "Palettes" open a context menu which contains the option) "Collapse all palettes" has no effect either.

Clicking on "expand all" has no effect, not even making collapsing possible again. MU4 is still perfectly usable at this point, but it seems very unintentional. The only way to get out of this state is to restart MU4.

**Screenshots**
As the issue is absence of reaction, I attach a video instead. (19 seconds, 0.2 MB)

https://user-images.githubusercontent.com/2690845/208722749-801adeaf-fc61-4fdb-9141-0b73eb88f9b3.mp4

**Platform information**
 - Linux, German locale, but I don't think either of these matter.

**Additional context**
My best guess is that during the search, all menus are expanded in the hope of being helpful. I have no idea what could cause them to get "stuck" like this.

**Comment by applesarefum** [comment]
I was able to reproduce this bug, but I found that restarting MU4 is not necessary to restore the normal behavior. Closing and reopening the Palettes tab (either by closing it from the context menu and reopening from View>Palettes, or simply pressing F9 twice).

**Comment by BenWiederhake** [comment]
Still happens with MuseScore 4.1.0 (`OS: Debian GNU/Linux trixie/sid, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a`)

**Comment by bleistift-zwei** [comment]
You can also restore the default behaviour by aborting the search with the cross in the search bar. This closes the search and restores the palettes to the state they had before you started searching.

Another thing not mentioned in the initial description is that the collapse/uncollapse behaviour is already broken while the search terms are still visible.


https://github.com/musescore/MuseScore/assets/60063716/8db83489-7d32-48b6-a4b5-36479b54401a

**Comment by wizofaus** [comment]
Seems like it should be easy to fix - currently it seems to determine collapsibility is based on whether any search text has been typed but not cleared, even if you've exited search mode.
