### ISSUE TITLE
[MU4 Issue] Saxophone altissimo range not played in playback

### ISSUE THREAD

**Issue by noloerino** [musescore/MuseScore#15458]
**Describe the bug**
Altissimo notes (F# above the staff and higher, as written in the appropriate transposition) for saxophones from Muse Sounds are not played and left silent during playback. For soprano and tenor, anything _including_ the high F# is not played; for alto and bari, anything _above_ the high F# is not played. 

**To Reproduce**
1. Create a new score with a saxophone instrument
2. Turn on transposed score
3. Enter a note higher than F# above the staff (presumably this also works if you input the appropriate note in concert pitch)

Example in attached file.
[MRE - sax altissimo notes.zip](https://github.com/musescore/MuseScore/files/10273101/MRE.-.sax.altissimo.notes.zip)

**Expected behavior**
Altissimo notes should be played back.

**Platform information**
 - OS: Windows 10

**Comment by SteveBlower** [comment]
Seems to be another example of [#13894]

**Comment by oktophonie** [comment]
(Closing as incorporated into #16244)
