### ISSUE TITLE
Overlap in score

### ISSUE THREAD

**Issue by realhackcraft** [musescore/MuseScore#15456]
A big bracket is overlapping a small bracket (I don't know the technical terms)

![Screenshot 2022-12-20 at 5 24 07 PM](https://user-images.githubusercontent.com/65378120/208778411-78d4ee4f-62dc-4130-a36b-7358e67fe555.jpg)

To reproduce: create a new score with Xylophone, Vibraphone and Marimba

**Comment by oMrSmith** [comment]
Workaround/Fix: Select Bracket and increase "Column"-value to 1 inside the inspector.
