### ISSUE TITLE
[MU4 Issue] Frame Corner Radius range limited via Properties Panel

### ISSUE THREAD

**Issue by jeetee** [musescore/MuseScore#15462]
**Describe the bug**
When adjusting the corner radius for a text element frame via the Properties > More... popout the setting is clipped to the range [0-5]. The same setting via Format > Style > Text Styles is allowed (and functional!) in the range [0-100]

**To Reproduce**
1. Set a Rectangle Frame on any text element in the score
2. Properties Panel > More... and click on the rectangle frame
3. Attempt to set a value for the radius in the range ]5, 100], either using the arrow spin buttons or by directly typing a value into the field
4. The value gets clipped to 5

**Expected behavior**
The Properties Panel should respect the same [0-100] range as the Style setting does

**Additional nitpick**
The style panel works with values accurate to the unit. The Properties Panel seems to allow for accuracy up to a tenth. Best to streamline those identical as well.

**Comment by jackm9367** [comment]
Happy to take this one on - should (hopefully!) be a simple qml fix. 
In relation to the nitpick - completely agree but I am unsure whether this is possible as the step defines both the limitation for specificity in the input _and_ the step size of the increase/decrease buttons.

**Comment by cbjeukendrup** [comment]
> In relation to the nitpick - completely agree but I am unsure whether this is possible as the step defines both the limitation for specificity in the input _and_ the step size of the increase/decrease buttons.

I think this is not entirely true... the maximum number of decimals for input is defined by the `decimals` property; the `step` property should not affect this (it should only influence the increase/decrease buttons).

**Comment by jackm9367** [comment]
> So I think it is fine to leave decimals at its default (which is 2) and set step to 1.

Had a look and it seems as though adding those properties fixed the nitpick as well (thankyou @cbjeukendrup)
PR updated and should be good to merge pending GitHub actions CI tests.
