### ISSUE TITLE
[MU4 Issue]parts generated from a midi file in MU4 only show rests, no notes.

### ISSUE THREAD

**Issue by rbnpi** [musescore/MuseScore#15469]
**The issue**
I have several 4 part midi files and I am trying to create parts using the parts button in MU4. However this just creates parts containing rests and tempo changes but no notes.
I want to export them to individual uncompressed musicxml files.

**To Reproduce**
Attached is one of the midi files I tired. Three images
1 the zipped midi file loaded into musescore4
2 the parts button pressed (I would usually rename the parts p1///p4 but problem same if I don't)
3 openly the parts. Each just contains rests and tempo info. No notes.

I want to export individual uncompressed musicxml files for each part separately. No good if the parts contain just rests.
As a workaround I delete 3 parts in turn and exported the remaining one in the main file. Then undid deletions and repeated retaining a different part. Works, but tedious.

**Expected behavior**
Parts should contain all notes and rests and tempo changes

**Screenshots**
Three screen shots

**Platform information**
 - OS: macOS

**Additional context**
bug discussed at https://musescore.org/en/node/339061 and verified by user jeetee who found parts works if the midifile was loaded then saved, and then the resulting mscz file was quit and reloaded before the parts were generated by the parts button.

**attachments follow**

(https://github.com/musescore/MuseScore/files/10276574/carols8.mid.zip)
![1-Musscore4 with 4 part midifile](https://user-images.githubusercontent.com/5587849/208875105-750a9eb9-ba50-4a79-bf5f-5f1456b6d258.png)
![2-partsButtonPressed](https://user-images.githubusercontent.com/5587849/208875129-a5fd9ac5-fd2c-4e6b-b43e-beb76f3a85af.png)
![3-partContainsRests](https://user-images.githubusercontent.com/5587849/208875152-0a0d8a0e-8adf-4801-8d84-7c2b7a57c61b.png)

**Comment by DmitryArefiev** [comment]
Fixed in #15501
