### ISSUE TITLE
[MU4 Issue] malloc-related crash when inserting quaver (when Muse Sounds are active)

### ISSUE THREAD

**Issue by xorgy** [musescore/MuseScore#15463]
**Describe the bug**
When I insert a quaver in the second bar of the vocal staff in this score, MuseScore aborts due to a bad malloc.

**To Reproduce**
1. Open the attached score
2. Insert a quaver in the second bar of the vocal staff

**Expected behavior**
not crashing

**Screenshots**
Here showing exactly what I did, two ways to make sure it's not just an issue with the crash restore:
[musescore-crash.webm](https://user-images.githubusercontent.com/1272018/208791128-1be5945f-9117-4167-96af-4b4824861a6b.webm)

**Platform information**
 - OS: Linux (Archlinux, present in v4.0 release 548562132fe98e55cc32b571cf629aad621f2fd9 and in master as of report be4665241d45f75f045caaea5d8e89e952784b84)

**Additional context**
The score that is triggering this is at https://qui.suis.je/drop/Lift%20Every%20Voice-voc.mscz

If resources are scarce for this sort of thing, let me know and I can do a debug build and trace the source of the bad malloc.

**Comment by xorgy** [comment]
Similar to some other issues I've now found, if I switch the playback to Basic, and turn off Muse Sounds, it does not crash.

**Comment by OttoKaaij** [comment]
I've been having similar issues too.

**Comment by zacjansheski** [comment]
@xorgy  We are currently unable to reproduce this.

Could you confirm if the issue is resolved or still present?

**Comment by zacjansheski** [comment]
Closing as stale
