### ISSUE TITLE
Dropdown in settings going behind menu

### ISSUE THREAD

**Issue by MyCatIsAChonk** [musescore/MuseScore#15481]
**Describe the bug**
A short and clear description of what the bug is.
The dropdown menu in Preferences > Import > MIDI is going behind the menu, as shown in the screenshot. I'm using MacOS Ventura 13.0.1.

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Import'
3. Scroll down to 'MIDI'
4. Select the dropdown menu
5. See error (at least, on MacOS Ventura 13.0.1; not sure if this is the case on other OS's)

**Expected behavior**
I expect the dropdown to come in front of the menu so I can click one of the options.

**Screenshots**
![image](https://user-images.githubusercontent.com/121187295/208960740-68d30dce-99b3-4b11-aa44-7f2dee42a602.png)

**Platform information**
 - OS: MacOS Ventura 13.0.1

**Additional context**
N/A

**Comment by Eism** [comment]
@MyCatIsAChonk 
I can't reproduce it on macOS Ventura 13. Need more info

Are you using a multi-monitor setup?

**Comment by MyCatIsAChonk** [comment]
Yes, I have it pulled up on an alternate monitor connected to my actual computer. The monitor is a Dell S2721HN.

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by abariska** [comment]
🔴 Reproducible again after the PR https://github.com/musescore/MuseScore/pull/17268

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20
