### ISSUE TITLE
[MU4 Issue] Score manager (online): No cancel on the "Send to YouTube" option

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#15505]
**Describe the bug**

There is no cancel button on the "Send to YouTube" option

**To Reproduce**

1. Save a score to the cloud but don't publish it.
2. Click on the "Send to YouTube" option on the online "My scores" page

RESULT: There is no cancel option.

**Expected behavior**

A cancel option that returns you to "My scores".

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223560506, revision: github-musescore-musescore-5485621

**Comment by shoogle** [comment]
This is purely a MuseScore.com issue so please report it at https://musescore.com/groups/improving-musescore-com
