### ISSUE TITLE
[MU4 Issue] Middle mouse drag moves whatever is selected

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#15517]
I frequently drag with the middle mouse button to move around a score. In MuseScore 4, this doesn't work when something is selected, because it will just move the selected object, no matter where the mouse is. In MS3, objects would only be moved when the mouse was on them. Please add an option to enable/disable this behavior, or get rid of it entirely.

**Comment by zacjansheski** [comment]
I just tried using the middle mouse drag (Windows 11) seemed to work as expected.  May we close this issue?

**Comment by zacjansheski** [comment]
Closing
