### ISSUE TITLE
[MU4 Issue] Feature request: enable note playback when clicking on notes even if note playback is disabled for editing

### ISSUE THREAD

**Issue by LuFlo** [musescore/MuseScore#15515]
I use a midi keyboard for note editing and external software for note playback of the midi inputs, since the Musescore playback still has some issues (lag, note sustain is fixed, etc.). I can disable note playback in the settings menu but then the notes are not played even when I exit note editing mode. The notes only played when I select the track and press "play" but sometimes it's really handy to "scroll" around with arrow keys.

I see two solutions to this:

1. Ignore the setting "Play notes when editing" as soon as the user exits note editing. This would also align with the wording. When disabling the checkbox one might assume that this option only applies to the note editing mode.
2. Add an additional checkbox two distinguish between note editing and "normal mode" (is there a better word for this? :D )

**Comment by cbjeukendrup** [comment]
To check if I understood correctly: so you want basically that notes _do_ play when you click on them, but _don't_ when you play on your MIDI keyboard, but _do_ get inputted on the score?

It seems like the only use case for this is a workaround for the current bugs with playback from MIDI input. I think we'd better fix those bugs than introducing workaround features...

**Comment by LuFlo** [comment]
> To check if I understood correctly: so you want basically that notes _do_ play when you click on them, but _don't_ when you play on your MIDI keyboard, but _do_ get inputted on the score?
> 
> It seems like the only use case for this is a workaround for the current bugs with playback from MIDI input. I think we'd better fix those bugs than introducing workaround features...

Yes, that would be exactly what I imagined. I agree that fixing the bugs should have a higher priority of course. I just thought that especially the first solution would coincide more with the description of the checkbox.

**Comment by RomanPudashkin** [comment]
This request sounds like a hack. We're going to fix our latency issues properly, so this feature won't be needed
