### ISSUE TITLE
[MU4 Issue] System-wide elements (incl Tempo, rehearsal markings) are gona until restart if a part is made without the first staff of an instrument

### ISSUE THREAD

**Issue by randoguyname** [musescore/MuseScore#15510]
**Describe the bug**
System-wide elements such as Tempo changes and rehearsal marks disappear after making a new part with only the 2nd or 3rd (or both) etc. staff of a multi-staff instrument.
**To Reproduce**
1. Create a new file with the template Great Stave (works with other multi-staff instruments as well)
2. Add a tempo or rehearsal mark element to the score
3. Go to parts
4. Create a new part
5. Show only the bass staff of the piano (this can be done in the instruments panel by showing the piano itself then hiding the treble staff)
6. See the tempo or rehearsal mark diasappear

Then:
Save and reopen the file and see that it now exists on the part
OR
Add a new rehearsal mark or tempo element on the main score and see that it appears in the part.

**Expected behavior**
Such elements are not lost when creating new parts

**Platform information**
 - macOS, Monterey

**Comment by oktophonie** [comment]
Note (for emphasis): only happens when creating a _new_ part, not if you open the 'existing' Piano part from the score.
