### ISSUE TITLE
[MU4 Issue] Instable performance

### ISSUE THREAD

**Issue by TheBrunoRM** [musescore/MuseScore#15525]
**Describe the bug**
The program jumps from nearly 0% CPU usage to around 50% when just clicking around.

**To Reproduce**
1. Click on random measures.

**Expected behavior**
The program should select the clicked measure without jumping to 50% CPU usage.

**Screenshots**
https://user-images.githubusercontent.com/38665405/209250731-604ad722-2bf0-4ca8-bed3-4994b4dad96b.mp4

**Platform information**
 - OS: Windows 10, 64-bit.

**Comment by Vykoiazon** [comment]
it probably depends on what processor you are using

**Comment by TheBrunoRM** [comment]
> it probably depends on what processor you are using

these are some of my pc specs:

processor: Intel Core i5-7600 3.50GHz
ram: 16GB DDR4
graphics card: NVIDIA GeForce GTX 1050 Ti

I am running MuseScore 4 on a 256 GB M.2 NVMe SSD

**Comment by TheBrunoRM** [comment]
I have been testing, and I came to this conclusion:
When having the MuseSounds playback selected, it takes around a second when clicking on things like measures and buttons like the note input button.
Then I tried switching to the MuseScore Basic sounds, and it didn't take that long to respond when clicking around.
So I believe it is a problem with the MuseSounds samples that make the program really slow.

**Comment by TheBrunoRM** [comment]
I dont know if this is supposed to be related, but I've found these weird situations where I was using the MuseScore Basic sounds:

1) It doesn't read the input correctly (on the piano, in this case). (Later, I've tried copying the same input from the other instruments to the piano, and it works):
https://user-images.githubusercontent.com/38665405/209413380-7c0deca0-8db3-46a5-889e-7ba03a74966c.mp4

2) It desyncs some instruments (the violins, in this case) in certain parts of the score (in this case, the first part sounds normal, but the later part sounds late):
https://user-images.githubusercontent.com/38665405/209413445-511d7c4d-6010-4552-af9a-fffe6c5144aa.mp4

**Comment by RomanPudashkin** [comment]
@TheBrunoRM does this issue still exist in 4.1.1? Thanks!

**Comment by TheBrunoRM** [comment]
I've been using the program for a while now, and the performance has increased considerably. But I've tested the same thing as above in the same project, just clicking and selecting random measures, and the CPU usage still bumps up when doing that. The application may be performing some heavy logic when selecting the measures? I'm not sure, but I think that before, the application would freeze for a moment when selecting measures, but now, it does not freeze as much as before. Still, the improvement is very noticeable, but it would be great for the lag to not be as noticeable. Great work at the latest improvements though, and I'm happy the app is performing better each update.

**Comment by RomanPudashkin** [comment]
Thanks for testing! There are already a bunch of issues about CPU spikes when clicking on notes. We are going to fix them in future releases
