### ISSUE TITLE
[MU4 Issue] Text impossible to read on export audio files

### ISSUE THREAD

**Issue by dartmol203** [musescore/MuseScore#15537]
**Describe the bug**
I was exporting a score in MP3 format but one of the options isn't possible to read, the text is too big for the space.

**To Reproduce**
 - I'm using musescore in portuguese
1. Go to "Publish"
2. Click on 'Exportar'
3. change the format to export to "MP3 audio"
4. See error on "Taxa de am..."

**Expected behavior**
It should be possible to read all the text in this field

**Screenshots**
![image](https://user-images.githubusercontent.com/78980992/209365456-50fddbee-ef44-4640-b4bd-4429672c5ae1.png)

**Platform information**
 - OS: Windowns
 - lang: portuguese

**Comment by JLWALTENER** [comment]
Same problem in French translation:
- String to translate = Sample rate:
- French Translation = Taux d'échantillonnage :
- Same behavior for all Audio export dialog
- The space to translatable string is too short.
-

**Comment by dartmol203** [comment]
the same problem happens in the "WAV audio", "OGG audio", "FLAC audio" formats

**Comment by cbjeukendrup** [comment]
@jessjwilliamson @bkunda I think we'll need a bit of design for how to handle longer translations in this situation...

**Comment by jessjwilliamson** [comment]
This should solve the issue :) We have lots of other UI where text is placed above an input box (e.g Properties) This may resolve making the export dialog slightly taller but i don't think this should be a massive issue. @cbjeukendrup  
<img width="915" alt="image" src="https://user-images.githubusercontent.com/71656189/225317858-5fd08783-6bad-48a7-895c-46ef99ed2d96.png">

**Comment by bkunda** [comment]
Thanks @jessjwilliamson, this is definitely the solution! 
@cbjeukendrup do you need Jess's design raised as a separate task, or is it enough to work from this issue?

**Comment by cbjeukendrup** [comment]
That looks like a beautiful solution indeed! Let's work just from this issue. 🙂

**Comment by DmitryArefiev** [comment]
Fixed in #17126
