### ISSUE TITLE
[MU4 Issue] Line break causes frame around text to expand in width for no apparent reason

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#15535]
**Describe the bug**

1. Create staff text, say, with the letter T.
2. Add a frame from Properties.
3. Now add a series of line breaks.

RESULT: The text object expands in width for no apparent reason

**Expected behavior**

Adding a line break should only cause the height to increase. The width should stay the same.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223570506, revision: github-musescore-musescore-5485621

**Comment by oktophonie** [comment]
Closing in favour of https://github.com/musescore/MuseScore/issues/17912
