### ISSUE TITLE
[MU4 Issue] Multiple dynamics at one place crashes the app when isolating voices

### ISSUE THREAD

**Issue by bmacs001** [musescore/MuseScore#15548]
Steps to reproduce: 
-Begin with a score with multiple parts, at least one of them with multiple voices written
-Go to the part(s) with multiple distinct voices
-Put in any two dynamics at the same point (same position in time and same staff)
-Hide any voice from the part

The app crashes. I understand that having multiple dynamics at the same point is probably not an intended use case, but I've used it before to play a different dynamic than what's written. 

MuseScore 4.0.0, MacOS 13.0.1

**Comment by cbjeukendrup** [comment]
I investigated this crash and it turns out that it has already been fixed namely by #15391. So it will be contained fixed in the next patch release. Thanks for reporting!
