### ISSUE TITLE
[MU4 Issue] Muse Hub Installer is top-most during entire installation

### ISSUE THREAD

**Issue by tmr232** [musescore/MuseScore#15558]
**Describe the bug**
Muse Hub installer stays a the topmost window on Windows as it is loading, making it impractical to do anything else.

**To Reproduce**
1. Download the Muse Hub installer
2. Double-click

**Expected behavior**
It shows the installer, and allows me to minimize it while it is installing.

**Screenshots**
![image](https://user-images.githubusercontent.com/1386239/209437076-1858f7f6-3a21-4cfc-ae71-63138b0301b5.png)

**Platform information**
 - OS: Windows 11

**Comment by oktophonie** [comment]
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.
