### ISSUE TITLE
[MU4 Issue] Musescore opens another instance of itself when creating a new score if a score is open.

### ISSUE THREAD

**Issue by ableunable** [musescore/MuseScore#15557]
**Describe the bug**
The program launches again if there's a score open and you try to create a new one. No options have been modified, this is a fresh and clean upgrade from MS3 the other day.

**To Reproduce**
Steps to reproduce the behaviour (also see the attached screen recording):
1. Create or open a score
2. Click on `Home` in the top left
3. Click `New score`
4. Observe how an entirely new Musescore window launches.

**Expected behaviour**
I assume it is supposed to instead put the new score in the same window, in another tab.

**Screenshots**
Here's a screen recording. 

https://user-images.githubusercontent.com/28569802/209433690-c79cb821-a7de-4b12-92d1-76367e31d40c.mp4

**Platform information**
- Arch Linux 6.0.12-arch1-1

**Comment by oktophonie** [comment]
This is by design; see, for example https://github.com/musescore/MuseScore/issues/11989

**Comment by ableunable** [comment]
So it works well in different windows but not in the same window and different tabs?

Well, as a programmer myself, albeit a mere hobbyist, I do understand. Sometimes it's just like that. Thanks for the speedy response.
