### ISSUE TITLE
[playback issue] sustained notes stop sounding at end of a bar

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15552]
**Describe the bug**
The sustained notes stop playing when they should still be sounding at the end of a bar,
maybe caused by the tempo slowing?

**To Reproduce**
1. add rhythms like this where somebody has sustained notes but another part has moving notes before a barline
![image](https://user-images.githubusercontent.com/120861729/209421131-4fabeb0f-f3d3-46e2-8931-ec40904cec51.png)

2. make the second bar a slower tempo and add a rit on the first bar toward the second bar (does not need two different tempo numbers like the example)
4. press play and hear the sustained notes stop around half a beat early
5. if it does not work then maybe test what happens if accents or grace notes are added

**Screenshots**

https://user-images.githubusercontent.com/120861729/209421170-7a670530-fb75-4d4f-ba36-d755fcc20025.mp4

**Comment by cbjeukendrup** [comment]
Yes,  I think it is indeed related to the ritenuto, or more generally, that the tempo at the start of the note differs from the tempo at the end of the note. For example, in this extreme example, the dotted whole note ends _way_ too early:
<img width="344" alt="Scherm­afbeelding 2022-12-24 om 18 26 14" src="https://user-images.githubusercontent.com/48658420/209446002-8f820502-ee19-485a-85d9-3f9c813c633e.png">

**Comment by zacjansheski** [comment]
Combining this with https://github.com/musescore/MuseScore/issues/14369 for reference
