### ISSUE TITLE
[MU4 Issue] "View | Fullscreen" does not appear as a toggle (Windows and Linux)

### ISSUE THREAD

**Issue by iwoithe** [musescore/MuseScore#15551]
**Describe the bug**
The `View | Fullscreen` menu item does not look like a toggle even though it acts as one.

About **macOS** [see comment](https://github.com/musescore/MuseScore/issues/15551#issuecomment-1711598339)

**To Reproduce**
1. Open MuseScore 4
2. Click `View | Fullscreen`
3. Open `View` again
4. A tick does not appear

https://user-images.githubusercontent.com/73422868/209420946-7a3b486f-68fa-41b4-b3e7-8bd69356da0b.mp4

**Expected behavior**

A tick to appear next to `Fullscreen`, like all of the togglable panels in the `View` menu.

**Platform information**

- Linux (Slackware 15, Xfce 4.16)

**Additional context**

- Build commit: d759f2983173fe513111d4d6ab2ce65334fd1c20

**Comment by Tejkh1** [comment]
@cbjeukendrup Sir ,can you please assign it to me.

**Comment by DmitryArefiev** [comment]
@Eism pointed me out that on Mac the behavior with Full Screen switching doesn't look as a bug (native macOS menu). 
It has different text for two states: **Enter Full Screen** and **Exit Full Screen**, so we can interpret as a toggle. 
Rewriting the bug to Win/Linux only (and closing)


![Screenshot 2023-09-08 at 14 56 33](https://github.com/musescore/MuseScore/assets/90187801/ba1b0f2c-fb3a-415a-bc37-1fdb514246d2)

![Screenshot 2023-09-08 at 14 56 45](https://github.com/musescore/MuseScore/assets/90187801/6eca35a3-c168-470e-9e23-5195035da582)

**Comment by DmitryArefiev** [comment]
Fixed in #16870
