### ISSUE TITLE
[MU4 Issue] Playback issues when changing the number of repeats

### ISSUE THREAD

**Issue by fredg999** [musescore/MuseScore#15554]
**Describe the bug**
In scores that contain repeat barlines, several playback issues occur if the number of repeats ("play count") of a repeated passage is changed from its previous value.

If the new play count is greater than 1: 
- the first note of the repeated passage will be skipped on each new repeat (but not the first time).

If the play count is increased: 
- after the previous number of repeats, the cursor moves back to the start of the repeated passage for the next repeat (as expected), but playback proceeds after the end repeat barline, except for the first note which is not played back;
- when the cursor reaches the last bar of the repeated passage again, playback skips to this bar and plays it correctly;
- if there are any repeats left (i.e. the play count was increased by at least 2), playback is silent for the remaining repeats except for the last bar of the repeated passage, which is played each time;
- when the cursor reaches the bar after the end repeat barline, the first note is played back, but the remaining notes are not.

If the play count is decreased: 
- after the new number of repeats, the cursor moves to the bar after the end repeat barline (as expected), but playback will jump back to the beginning of the repeated passage again, after playing the first note of the first bar after the end repeat barline instead of the first note of the repeated passage;
- if the repeated passage was modified as well (e.g. changing pitches), playback of the additional repeats (after the new number of repeats) will correspond to the old passage instead of the new one;
- playback stops when the cursor reaches the end of the score (even if it was in the middle of playing some notes).

Somewhat similar issues can occur when using volta lines, in particular when setting up volta lines first (i.e. adding volta lines, changing their repeat list, etc.) and changing the play count afterwards. Let me know in the discussion if you need the details for this case.

The above issues may combine if multiple conditions are met at once.

Current workaround: adding/removing a bar, a repeat barline or a volta line in the score (possibly anywhere), or changing the repeat list of a volta line, any of which seems to force MuseScore to recalculate the repeat starting and ending points for playback. It seems as though that changing the play count should do the same, but it currently doesn't.

**To Reproduce**
1. Open [this score](https://github.com/musescore/MuseScore/files/10298064/demo2.zip) (unzip before opening), or create any score with a repeated passage.
2. If desired, play back once to see normal behavior.
3. Right-click on the last bar of the repeated passage and select "Measure properties...".
4. Change the play count to any other value.
5. If desired, change the contents of the score (changing pitches, rhythms, etc.).
6. Play back again and notice the playback issues mentioned above (i.e. playback does not match score at some points).

**Expected behavior**
Playback should play all notes as usual and follow the play count chosen by the user.

**Screenshots**
I'll try to add a video later if possible, but my video capture tool isn't working properly right now. Sorry for the inconvenience.

**Platform information**
- OS: Ubuntu 22.04.1 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223580304, revision: github-musescore-musescore-d759f29

**Additional context**
These issues occur:
- with both the official 4.0 release and the latest (2022-12-24) nightly release;
- with both MS Basic and Muse Sounds playback profiles (and switching profiles has no effect on the issue);
- with both the beginning of the score and a start repeat barline as the starting point of the repeated passage;
- on all instruments of a multi-part score.

**Comment by taironemagalhaes** [comment]
I report the same behavior on `OS: macOS 10.15, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621`.

Thanks for sharing the workaround!

**Comment by mrshr3d** [comment]
Confirming issue is still present on `OS: Manjaro Linux, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-, revision: github-musescore-musescore-`  (this is currently the latest available version in the standard repository)

Definitely a bug when setting the Play Count variable  -  applying the "work-around" fixes it, and it then breaks again if the Play Count is changed once more.

**Comment by DmitryArefiev** [comment]
Thanks for logging!
