### ISSUE TITLE
[MU4 Issue] First options in dialog buttons in "Properties" cannot be edited via group select

### ISSUE THREAD

**Issue by Kkyehh** [musescore/MuseScore#15574]
**Describe the bug**
If a line is selected via group select such that its respective dialog is relegated to a button, there are certain properties of the line that cannot be edited. It generally seems to happen with the first options of a line; for example, the "show pedal symbol" and "Line type" options on a pedal, the "Niente circle" and "allow diagonal" boxes on hairpins, or the "show line" box on tempo changes. Attempting to edit these options will instantly close the dialog without altering anything.

**Edit**: This seems to be an issue with all buttons, not just lines or buttons under the "Notation" tab.

**To Reproduce**
1. Add line (pedal, tempo change, etc.)
2. Group select measures including the measure with the line
3. If there are enough elements, the dialog for the options are relegated to buttons under "Notation" (see video)
4. Click one of the buttons and click one of the first options (usually a checkbox)
5. The dialog will instantly close without altering the property.

**Expected behavior**
The option should be changed and the dialog should stay open.

**Screenshots**
(please excuse the odd cursor behavior, that seems to be an issue with the capture software I used)

https://user-images.githubusercontent.com/68103566/209450285-496d5f58-3036-48df-97bb-ee733db252b6.mp4

**Platform information**
 - OS: Windows 11

**Comment by zacjansheski** [comment]
Although there are still some known issues with these menus, I believe this is no longer an issue in the current nightly, could you please confirm?

**Comment by zacjansheski** [comment]
Closing
