### ISSUE TITLE
[MuseSounds Issue] Pauses not Working, Playback Clipped Sometimes, Removing Pauses makes it Worse

### ISSUE THREAD

**Issue by rich777300** [musescore/MuseScore#15578]
**Describe the bug**
Breath Marks and Caesuras (I'll refer to both of these as 'pauses') glitch and don't play properly. Beginning of playback is clipped when you don't press rewind button first. Playback is much worse if you remove the pauses and try again.

**To Reproduce**
Steps to reproduce the behaviour:
1. New score
2. Notate something, say a long scale like I did (attached)
3. Add an assortment of pauses
4. Though the bar following the music (cursor?) stops, the sound doesn't stop and glitches.
5. Notice the beginning notes are clipped if you don't press rewind
6. Notice the worse playback if you remove the pauses after the fact

**Expected behaviour**
Everything pauses for the specified amount of time before continuing without glitching or clipping. When removing the pauses, there should be no glitching.

**Platform information**
 - OS: Windows 10 64-bit
 
**Additional context**
When starting the playback, the first few notes are clipped as well, but this doesn't happen when you press rewind first. The pauses never seem to work, however. The playback is worse if you remove the pauses after the fact. I would attach a mscz but I can't. 

I noticed an issue with no default time on breath marks is still open too so I thought I'd mention it here too.

Used MuseSounds Grand Piano soundfont, recorded with OBS.

https://user-images.githubusercontent.com/102642087/209454779-40c7a2d2-fba0-42b8-b57a-2a8f09c39db2.mp4
https://user-images.githubusercontent.com/102642087/209454797-0ee25390-ccc4-4970-bc50-1ee5287523cc.mp4

I don't know if this should be one big issue or two, three...I thought they were all somewhat interconnected so I'm putting everything here for now...?

**Comment by wwwbagel3** [comment]
Same thing here.

**Comment by AIPAL18** [comment]
Breath mark (comma), Breath mark (tick-like), Breath mark (salzedo), Breath mark (upbow-like) don't work well when I enter the value myself, but when I use the arrows (buttons) they do....

**Comment by grigorax** [comment]
I have something similar with caesura: Deleting and then reinstating a caesura can cause a playback error.

[Playback error. From 'Common Chord'.mscz.zip](https://github.com/musescore/MuseScore/files/12772707/Playback.error.From.Common.Chord.mscz.zip)

ACTION
1. Delete the caesura in bar 3. 
2. Reinstate the caesura by doing CMD-Z (for example).
RESULT
1. The Gmaj chord in bar 4 plays before the pause is executed.

Note: Then if we save and reopen the score, the problem goes away.

ACTION
1. Delete the caesuras in bars 3 and 6.
2. Reinstate the caesuras by doing CMD-Z (for example).
RESULT
1. What should be the pause at bar 3 is filled with the contents of bar 4 and a bit of bar 5, after which 'play' continues as normal from the start of bar 4.

Note: Then if we save and reopen the score, the problem goes away.

Note: By playing around with caesuras is possible to generate more extreme examples of playback error, but hopefully these will go away when the above bug is fixed.

**Comment by DmitryArefiev** [comment]
Fixed in #20982

Please reopen if still occurs
