### ISSUE TITLE
[MU4 Issue] Properties panel doesn't update when new elements are added to a range selection

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#15576]
**Describe the bug**
When adding new elements to the score, the Properties panel doesn't update real-time to show options for these elements.

**To Reproduce**
1. Make the Properties panel visible
2. Make a range selection
3. Add elements by clicking them in the Palettes
The Properties panel doesn't update to show options for the newly added elements.
When you click on empty space and then make the same selection again, the options appear.

**Expected behavior**
The options should appear immediately when new elements are added.

**Video**

https://user-images.githubusercontent.com/48658420/209453259-f3c20ef5-c1ca-4474-9fac-dfa28b7c15d9.mov

**Comment by Tantacrul** [comment]
Agreed. I think this is a straight-up bug. Doesn't need design beyond what @cbjeukendrup has mentioned here.
