### ISSUE TITLE
[MU4 Issue] Ctrl+Up/Down do not change tablature strings in note input mode

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#15588]
**Describe the bug**
Ctrl+Up/Down work to change strings in normal mode but not in note input mode

**To Reproduce**
1. Create guitar tablature score 
2. Enter a note on top string, fret 0
3. While still in note input mode, press Ctrl+Down
4. See error: cursor moves to next string, but note stays on top string

**Expected behavior**
The fret 0 top string should change to fret 5 next string, as it does in normal mode

**Platform information**
 - OS: Linux

**Additional context**
This worked in MU3

**Comment by DmitryArefiev** [comment]
The same on my side

https://user-images.githubusercontent.com/90187801/209939752-84bfd952-aa1d-4bac-9aab-4004641a4512.mp4


Thanks for logging!

**Comment by HemantAntony** [comment]
@DmitryArefiev I made a fix couple months ago and forgot to tag you: #15745 :)

**Comment by zacjansheski** [comment]
I believe this was fixed by  https://github.com/musescore/MuseScore/pull/18424

@MarcSabatella please confirm

**Comment by MarcSabatella** [comment]
That was the intent of the change, yes.  I can't verify if it is working in a current nightly because no AppImages have worked for a week or two now due to incorrect GLIB_CXX version being used in the build.
