### ISSUE TITLE
Please reconsider Muse Hub as a background service

### ISSUE THREAD

**Issue by tank-trax** [musescore/MuseScore#15589]
I am using Linux exclusively for audio production. One of the things that I do to optimize my system is disable unneeded services.

I tried the latest appimage of Musescore and installed Muse Hub, as someone noted it needs a reboot to work because of sudo permissions.

That being said, I do not want an extra background service running so I uninstalled it immediately. 

This Muse Hub is a terrible, terrible idea. If it was just an app for downloading I would use it, but not as a background service. 

Could you possibly make it that we can get your sound packs and install them without this program, because quite frankly, I won't install it.

Also, please include VST plugins on the Linux version.

Thanks

**Comment by krtschil** [comment]
I agree as I also do not want to run unneccessary services in the background. Because the Muse Sounds are much better for playback then the Basic sounds I want to use them in MuseScore. Uninstalling Muse Hub removes also these sounds which I want to avoid.

What I do: 

- I disable the muse hub background service (**sudo systemctl disable muse-hub.service**) so it does not run even after reboots 
- Start it occasionally (**sudo systemctl start muse-hub.service**) and run muse-hub to check whether updates to the sounds are available and disable it again.

Maybe this helps

**Comment by tank-trax** [comment]
@krtschil that's a nice work around, thanks

that being said, I use WINE and have installed products for ikmultimedia and native-instruments using their app to access their products hub, neither of these runs in the background, yes they exist in systray but can be exited

is it absolutely necessary that Muse Hub be a service? IMHO the answer is no

and that removing Muse Hub also removes the sounds is another aspect of this strategy that I would assert is poorly thought out, at least as far as user experience is concerned

I love the direction MuseScore is heading, I pay for a Pro account on MuseScore.com, MuseScore is my premier notation software.... on any OS

I still urge a rethink on this latest development because quite frankly it's a major deal breaker

**Comment by MrCampbellDuchess** [comment]
+1 for this.

I teach Music Composition in a lab environment and requiring the Muse Hub service to be running is a problem my IT department isn't willing to entertain, and rightly doesn't see as required to download and maintain the files.

The files physically exist on my SSD, I can see them in the downloads folder but I can't point MuseScore at that folder without a background service running?

I understand that this is done to maintain the P2P sharing nature of the distribution of these files but I don't understand why I can't access these files myself.

**Comment by MarcSabatella** [comment]
You should be able to stop the service at any time without interfering with MuseScore's operation at all.  As long as you downloaded them to the default location, MuseScore should see them whether Muse Hub or the background service are running or not.

**Comment by tank-trax** [comment]
it still doesn't answer the question as to why tie Muse Hub into a background service? it's obviously not necessary and creates unwanted headaches

again my opinion is that it's a bad strategy, my request is to please make it an app only

for example, Tracktion Waveform and Bitwig have download managers that detect latest versions of the main application and plugins and/or add-ons, they can run with the DAW or in the case of Tracktion as a separate download manager... but neither are background services, once closed they don't continue running in the background

my recommendation/request is to detach the service aspect from the download manager, otherwise I can foresee more backlash from users once more people try version 4 and they realize what's at play here

**Comment by cbjeukendrup** [comment]
I'll close this, since it is a Muse Hub issue, not a MuseScore issue. Muse Hub issues can be discussed at https://musehub.zendesk.com/ (but this issue has been discussed there often enough already, so it makes no sense to bring it up yet again).

**Comment by tank-trax** [comment]
how is this not a MuseScore issue? I would not have even considered using MuseHub if not for MuseScore... 

another question I have is why is MuseHUb not open source? 

it's not that complicated... abandon Muse Hub... and find a better way of distributing MuseScore sounds

my suggestion is direct download and manual install.... at the very least leave that option open 

Muse Hub is a deal breaker

**Comment by tank-trax** [comment]
inevitably this is MuseScore issue as people that use MuseScore 4 will be directed to use MuseHub to install sounds

another question I have is why is MuseHub not open source?

for user experience, and it appears I am not alone on this, there should be a better way of distributing MuseScore sounds and imo that would be direct download and manual install, or develop an installer that isn't dependent on a bg service.... at the very least leave the option open for users that don't need or want to use a hand holder app, especially for those uninterested in having an additional service running in the background

**Comment by cbjeukendrup** [comment]
The fact that MuseScore might currently be the biggest reason to download Muse Hub doesn't change anything about the fact that this issue it technically and practically a Muse Hub issue and not an issue in MuseScore itself. If you want things to change in Muse Hub, you should not talk to us (developers of MuseScore) but to the developers of Muse Hub, at https://musehub.zendesk.com/. But again, this issue has been discussed there often enough already, and the Muse Hub team already know about it, and I wouldn't be surprised if they are already working on a solution.
