### ISSUE TITLE
[MU4 Task] Add Project Version

### ISSUE THREAD

**Issue by WcRnm** [musescore/MuseScore#15597]
**Task description**
Consider adding a project version to the set of project properties. It's possible to add a custom property, but there will be no corresponding custom code for use in the header or footer. The current work around is to have the version only in the header or footer.

Including a version number (e.g. 0.3) when printing out a work-in-progress is nice to have, especially if there have been several copies made of different revisions.

**Comment by cbjeukendrup** [comment]
Any meta tag can be included in the header or footer using `$:tagName:`. So, if the custom version number property is called `versionNumber`, you can include it in the header or footer by typing `$:versionNumber:`.

**Comment by WcRnm** [comment]
I'd had tried that. I must have had a capitalization wrong - it does work as you describe. I apologize for creating an unnecessary issue.

**Comment by WcRnm** [comment]
Closing issue.

**Comment by cbjeukendrup** [comment]
No problem!
