### ISSUE TITLE
[MU4 Issue] Playback of notes with "slide out up" gets stuck

### ISSUE THREAD

**Issue by stuartizon** [musescore/MuseScore#15608]
**Describe the bug**
When playing back the attached score the chord with "slide out up" notation on each of the notes gets stuck. It sounds like the rest of playback is happening normally, but the second chord is held for a very long time (over the rest of the music).

**To Reproduce**
1. Open the attached score
2. Press play
3. The second chord (tzur) is held much longer than it should be.

The attached MP3 was generated from the same score, and demonstrates the same broken playback behavior.

**Expected behavior**
The chord should be held for its written length (dotted crotched), ideally with a slide up to the next chord (though I'm unsure if that feature has been built yet).

**Attachments**
<img width="714" alt="Screenshot 2022-12-26 at 2 52 44 PM" src="https://user-images.githubusercontent.com/10707512/209579697-4a9859d7-d8f9-4620-b940-e56d2d390548.png">
[Slide out bug.mscz.zip](https://github.com/musescore/MuseScore/files/10304658/Slide.out.bug.mscz.zip)
[Slide out bug.mp3.zip](https://github.com/musescore/MuseScore/files/10304662/Slide.out.bug.mp3.zip)

**Platform information**
 - Mac OS 12.2.1
 - Sounds are MS Basic

**Comment by Koopa1018** [comment]
Still occurring as of 4.1. Happens with all slides, in and out, including curved (doit/fall/scoop/plop).
