### ISSUE TITLE
[MU4 Issue] Rest input not working for tablature

### ISSUE THREAD

**Issue by SavannahGosling** [musescore/MuseScore#15611]
**Describe the bug**
In note input mode, Musescore 4 allows you to directly input rests, but this is not possible with tablature.

**To Reproduce**
1. Create Electric Guitar or Bass Guitar instument
2. Switch stave to tablature (Common or Full so note values and rests are visible)
3. In note input mode, attempt to input a rest

**Expected behavior**
Expected to be able to input a rest directly without exiting note input mode

**Screenshots**

https://user-images.githubusercontent.com/120750503/209586741-b5c77e28-5b69-4000-ac90-72a644e82e86.mov

As opposed to...

https://user-images.githubusercontent.com/120750503/209586765-b01a868d-6a9d-402d-af9f-43542cada2a1.mov

**Platform information**
MacOS

**Comment by MarcSabatella** [comment]
Thanks for the report  this is a known issue currently, see https://github.com/musescore/MuseScore/issues/11736
