### ISSUE TITLE
[MU4 Issue] MS Basic and SoundFonts are playing largely out of tune, while Muse Sounds and most VSTs are fine (using 192kHz sample rate output)

### ISSUE THREAD

**Issue by MineCake147E** [musescore/MuseScore#15615]
**Describe the bug**
The frequency of the A4 should be exactly 440Hz, but the MS Basic produces the same sound at 1915Hz, about 4.35 times higher. 
The pitch differences between SoundFont and Muse Sound are consistent among the different SoundFonts, including MS Basic.  
The number 4.35 is close to 192000/44100, where 192000 is the output sampling frequency.  

**To Reproduce**
1. Get some device that runs MuseScore 4 and has an 192kHz output.
2. Set sampling frequency of output device to 192kHz.
3. Launch MuseScore 4.
4. Create an empty score with piano part.
5. Play the A4 note with Grand Piano from Muse Sound.
6. Play the A4 note with MS Basic.
7. You'll see the pitch difference of these two.

**Expected behavior**
Piano from MS Basic plays A4 at 440Hz.

**Screenshots**
<details><summary>Image of MuseScore 4</summary>

![image](https://user-images.githubusercontent.com/31585494/209610617-935c0f1f-d276-4cf8-9b4a-8dcba551805f.png)

</details>
<details><summary>Spectrum analysis of A4 note played with Piano from MS Basic, in Audacity</summary>

![image](https://user-images.githubusercontent.com/31585494/209610713-78db18df-5a3f-49db-b8e0-17a2b1c27187.png)

</details>

**Platform information**
- PC1: Modified DELL XPS 8700
  - OS: Windows 10 Home 22H2 Build 19045.2364
  - CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  - RAM: 32.0 GB DDR3 DIMM
  - Graphics: NVIDIA GeForce GTX 1060 (6 GB) from 玄人志向
  - Audio: VB-Audio VoiceMeeter VAIO @ 24bit 192kHz Stereo
  - Storage: 
    - OS (C:) : Western Digital WDC WDS100T2B0A-00SM50 1000.2 GB SATA SSD
    - WORKSPACE (D:) : Seagate ST1000DM003-1ER162 1000.2 GB 7200RPM SATA HDD
    - DATA (E:) : Western Digital WDC WD10EZEX-22MFCA0 1000.2 GB 7200RPM SATA HDD
    - ARCHIVE (F:) : HGST HCC541010B9E660 1000.2 GB 5400RPM SATA HDD

EDIT: It also reproduced in my new PC.
- PC2: Custom built PC
  - OS: Windows 11 Home 22H2 (22621.1992)
  - CPU: Intel(R) Xeon(R) w5-2455X   3.19 GHz
  - RAM: 32 GB DDR5 ECC RDIMM
  - Graphics: NVIDIA GeForce GTX1060(6 GB) (transplant from PC1)
  - Storage: 
    - OS(C:) : WD_BLACK SN770 1TB
**Additional context**

**Comment by cbjeukendrup** [comment]
It looks like FluidSynth, our SoundFont synthesiser, doesn't support sample rates above 96 kHz...

**Comment by cbjeukendrup** [comment]
@MineCake147E I've created an experimental solution: https://github.com/musescore/MuseScore/pull/16018

Would be great if you could download the test builds for this version (they're ready in 30 minutes). See https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#Downloading-Builds-from-Pull-Requests for how to download these builds.

**Comment by MineCake147E** [comment]
@cbjeukendrup Thank you! It works for 192kHz!  
However, when I changed the output device and set the sample rate of that device (not including the other devices) to 384 kHz, it played at twice the tempo and an octave higher pitch.  
When I reduced the sample rate of the output device to 96 kHz, it played at half the tempo and an octave lower pitch. 
In these cases, all instruments tested are affected, including Muse Sounds and some VSTs (including Dexed).  
The VST plugin sforzando is showing the host rendering sample rate as being set to 192kHz in both cases, even though I have changed the sample rate of the output device to 384kHz or 96kHz. In contrast, when it is hosted in Cakewalk, it correctly shows the host rendering sample rate.  
Restarting the test build of MU4 doesn't solve anything about it.  
There are certainly some problems with the rendering sample rate.

**Comment by DmitryArefiev** [comment]
@MineCake147E Can you check the last build from #16018 please? Does it solve the initial bug?

I just don't have an audio device that supports 192kHz to check

Thanks!

**Comment by MineCake147E** [comment]
It looks good to me with 192kHz.

**Comment by DmitryArefiev** [comment]
Thanks for checking!

**Comment by DmitryArefiev** [comment]
@MineCake147E Can you check also **384kHz** please?

**Comment by MineCake147E** [comment]
It also looks good to me with 384kHz.
Changing sample rate requires restarting MU4 to take effect, though.

**Comment by DmitryArefiev** [comment]
Good. Thanks!

**Comment by MineCake147E** [comment]
@DmitryArefiev I'm afraid that I couldn't find any `.mscz` files in https://github.com/musescore/MuseScore/pull/19241.

**Comment by DmitryArefiev** [comment]
@MineCake147E Oh, sorry! My bad.. I meant #19242 , or just try this
[EXPORT.BASIC_AUX.REVERB.zip](https://github.com/musescore/MuseScore/files/12521884/EXPORT.BASIC_AUX.REVERB.zip)

**Comment by MineCake147E** [comment]
I think it's fine for both sampling frequency.

I recorded a playback for both 192kHz and 384kHz in Audacity:

## 192kHz
![image](https://github.com/musescore/MuseScore/assets/31585494/b562868b-f911-4516-b128-dedd4d7f75ce)
![image](https://github.com/musescore/MuseScore/assets/31585494/b223cdc1-b584-4783-9f3e-0f71fb63b910)
[EXPORT BASIC_AUX REVERB.zip](https://github.com/musescore/MuseScore/files/12522554/EXPORT.BASIC_AUX.REVERB.zip)

## 384kHz
![image](https://github.com/musescore/MuseScore/assets/31585494/70f0d90b-96f7-411f-bc4f-9652b3f5655d)
![image](https://github.com/musescore/MuseScore/assets/31585494/8582f536-d071-4b6b-af11-cc0786458d18)
[EXPORT BASIC_AUX REVERB_384kHz.zip](https://github.com/musescore/MuseScore/files/12522659/EXPORT.BASIC_AUX.REVERB_384kHz.zip)

**Comment by DmitryArefiev** [comment]
Yeah, I see it's fine. Thank you for testing!
