### ISSUE TITLE
[MU4 Issue] When open score from Finder, it just open MU app and not score itself (macOS, Ventura 13.1)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#15620]
**To Reproduce**
1. Install MuseScore from Muse Hub
2. Open MuseScore
3. Create score and save
4. Close MuseScore
5. Open Finder and double click on score - **it just open MU app but not the score itself** (you need to double click in Finder again)

https://user-images.githubusercontent.com/90187801/209686282-e76b83bf-416e-4a10-993d-cc6c4f038dea.mov

**Platform information**
macOS13

**Additional context**
#9411

**Comment by cbjeukendrup** [comment]
See also #15465 and #15292. I can reproduce this in the release build from Muse Hub, but not in any other build so far.

**Comment by DmitryArefiev** [comment]
Yeah, it was fine when I tested #9411

**Comment by DmitryArefiev** [comment]
> See also #15465 and #15292. I can reproduce this in the release build from Muse Hub, but not in any other build so far.

Yeah, the same as #15292.. Closing as dupe
