### ISSUE TITLE
[playback issue] ritardando not playing correct rate of change

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15628]
**Describe the bug**
the rit slows down a little bit but then suddenly drops to the next tempo instead of slowing down by an equal amount every beat to gradually reach the next tempo

**To Reproduce**
1. make a line of notes starting at a fast tempo
2. add a rit to a slow tempo
3. play and hear it does not slow down by enough and suddenly jumps to the next tempo at the end

**Expected behavior**
it should change by the same amount every beat instead of a sudden drop in tempo at the end

**Screenshots**

https://user-images.githubusercontent.com/120861729/209750361-3ff5dbe0-afd7-461d-a223-c33434c12218.mp4

**Platform information**
windows

**Comment by Vykoiazon** [comment]
when watching the tempo marker in the top right of musescore, it usually drops by around 15 per beat but then suddenly drops by 120 bpm when it should be a gradual change by the same amount until reaching the next tempo

**Comment by erinic04** [comment]
you need to manually set the % to line up with your end tempo
