### ISSUE TITLE
[MU4 Issue]Error 401 upon Upload to MuseScore 

### ISSUE THREAD

**Issue by BPCompositions** [musescore/MuseScore#15636]
**Describe the bug**
On trying to upload a score to MuseScore.com, an error 401 message appears

**To Reproduce**
1. Go to “file”
2. Click on “upload to MuseScore.com
3. See error

**Expected behavior**
My score gets published to MuseScore.com

**Platform information**
 - OS: Windows 11

**Comment by abariska** [comment]
Confirm. I got the same issue few times on macOS. Didn't find a trigger of the problem yet

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12
