### ISSUE TITLE
[MU4 Issue] App Icon in Linux Task Bar is Generic X-Windows Icon

### ISSUE THREAD

**Issue by JeffRocchio** [musescore/MuseScore#15634]
Very minor issue. On fedora-35 the running MS4 app icon in the taskbar displays the generic X-Windows icon vs a MuseScore icon.

I am running X-Windows still as I am still having issues with Wayland.

Screenshot:

![MS4_App-toolbar-icon_f35-Xwin_20221228](https://user-images.githubusercontent.com/26509192/209881881-0e682c7a-a748-4acd-8902-9cf653544fb9.png)

Platform:
   - fedora-35
   - X-windows
   - running the MS4 appimage: MuseScore-4.0.0-x86_64.AppImage

**Comment by MarcSabatella** [comment]
Did you install the AppImage yet (run from command line with “install” option)?  This works for me.

**Comment by JeffRocchio** [comment]
I confess I do not understand what you mean by using the 'install' option. I should have added to my Platform info that I am running the KDE desktop. What I did was:
   - Downloaded the appimage file from the MuseScore site (into my 'AppImages' directory).
   - Set permission on the appimage file to Execute.
   - Made a KDE desktop app-launcher file, which executes the command: _/home/jroc/AppImages/MuseScore-4.0.0-x86_64.AppImage_ when double-clicked.

In creating the desktop file I did hunt around for a MuseScore icon for the desktop file to use as it's desktop display icon, but wasn't able to find one (probably I could get one off the github, but of course a normal user should need to go to such lengths).

I did google up appimage install and did see a little bit about some utility for Ubuntu that would auto-create the desktop file and add it to the menu system. But that seemed like it was just automating what I had already done. And I didn't see anything pertaining to fedora/KDE. I did take a shot at execting a few command variants in the terminal with 'install'; but only got errors back.

**Comment by MarcSabatella** [comment]
I mean, literally adding "install" as a command line option.  That's how you install the AppImage.  So from a terminal, type the filename of the AppImage, follow by a space and the word "install" (without the quotes.  This is what integrates the AppImage into the desktop environment, setting up the desktop file, the icons, and everything else needed to make it work normally.

**Comment by JeffRocchio** [comment]
Ok, that did actually work Marc. Old dog, new trick - thank you. 

But now I'm down a rabbit hole trying to understand why it worked. 30 mins this morning with google searches and I still can't find and documentation on this - other than a separate utility - "AppImageLauncher" - which I do not have installed on my machine. When I look at the terminal output it gives me the sense that 'install' was a parameter that the MuseScore appimage handled (as opposed to a directive to the Linux or KDE system). I get this impression because it appears to have installed two libraries (libjack.so.0 and libnss3.so) which must be specific to MuseScore. That and also that to make it work I did have to invoke it with the usual bash 'run this executable, don't treat this like a bash command' ./ prepend.

Just for my own education I'd be interested in understanding what component(s) of my system are responding to and handling the AppImage 'install' parameter.

Install Terminal Log: [MS4_App-toolbar-icon_InstallLog.txt](https://github.com/musescore/MuseScore/files/10320237/MS4_App-toolbar-icon_InstallLog.txt)

**Comment by MarcSabatella** [comment]
The main thing the install option does is create a ".desktop" file in ~/.local/share/applications.  That's how your desktop environment knows about things like which icons go with which programs, how to start them from a menu or taskbar or launcher or whatever your specific environment provides, etc.  The install option also moves the AppImage itself to ~/.local/bin, and also copies the icons and/or other files needed to corresponding locations.  All this is done by the AppImage itself, no other programs needed as far as I know.

JACk and NSS are not specific to MuseScore, and I don't think those libraries are actually *installed* by this process.  But there are some fallback versions used, I think, so that MuseScore can use your own already-installed version if they are available, or the fallback versions if not.  That's a bit of a mystery to me.  But when you run the AppImage normally from the command line (without the "install") it should tell you which is being used - the installed version or the fallback.

**Comment by JeffRocchio** [comment]
> JACk and NSS are not specific to MuseScore...

Yeah, after I posted my reply I did think to look at the timestamps on those two lib files - they were already on my system, which makes sense as they'd be needed by some other apps as well. So probably all that was happening was that the AppImage 'install' was checking to see if they were there.

Thanks for your help Marc.

**Comment by leleogere** [comment]
While using the `install` command does fix the issue, I am curious about how some AppImages (e.g. [SourceGit](https://github.com/sourcegit-scm/sourcegit) or [DarkTable](https://github.com/darktable-org/darktable)) are able to get an icon without needing to do anything?

Ideally, I feel like the vast majority of AppImage should work out-of-the-box when executed, and should need to looking at the doc to simply get a taskbar icon! Having an `install` command to create the desktop shortcut might still be useful, but I feel like the icon should work without needing to do anything (which should be possible looking at other apps).

**Comment by MarcSabatella** [comment]
Maybe your distribution or desktop manager comes pre-configured with the appropriate icons for those programs?  Icons don't work by magic; they are pointed to by a desktop file etc.  For programs installed from a repository by a tool like "apt", the icon desktop file and desktop file are set up by that tool.  For an AppImage, something else needs to set it up.  Could be the AppImnage itself, could be a separate third party tool like "AppImage Launcher", could be a user downloading the icon and desktop file separately, could be something else.

For more questiosnb on how to use MuseScore, please ask for help on the official support forums over at musescore.org
