### ISSUE TITLE
[MU4 Issue] The instrument names of hidden staffs affect indentation on the first system

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#15638]
**Describe the bug**
On the first system, the name of the hidden staff affects the indentation.

**To Reproduce**
See video

https://user-images.githubusercontent.com/102702868/209924040-310f43bb-b9ee-4300-8d0a-31d3270299c9.mp4

**Expected behavior**
On the first system, the instrument names of the hidden staffs should not affect the indentation.

**Platform information**
 - OS: Windows 11

**Comment by L0uisc** [comment]
@oktophonie Have you started working on this yet? I'd like to take it on to help me learn the code base.

**Comment by oktophonie** [comment]
I'm not working on it, I'm merely the Engraving Overseer to have assigned myself so that I can keep track of the issue. If you'd like to take a look at it, please feel free!

**Comment by Jojo-Schmitz** [comment]
It does also happen in Mu3, just slighly different: the space is not added at the beginning, but the measures of the 1st system seem to get increased and may cause an automatic system break at an earlier measure as it'd otherwise happen
