### ISSUE TITLE
[MU4 Issue] Slur adjusted over tuplet number in MS3, collides with it when imported into MS4

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#15639]
**Describe the bug**

In MS3, you can add a slur and adjust its position so that it sits neatly above or below a truplet number. e.g.

![slurs_ms3](https://user-images.githubusercontent.com/87246583/209981777-b37a43b5-51a0-47d2-94a4-fcab4a632735.png)

However its position is reset when imported into MS4 and collides with the tuplet number. e.g.

![slurs_ms4](https://user-images.githubusercontent.com/87246583/209981958-ebde9d83-322d-4b3e-bf71-553a0d2a2fc1.png)

Here is the file: 
[slur_triplet_collision.zip](https://github.com/musescore/MuseScore/files/10320472/slur_triplet_collision.zip)

See also #15336.

**Expected behavior**

Slurs over/under triplet numbers should carry over their customised positions from MS3 into MS4.

**Platform information**
 
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223630304, revision: github-musescore-musescore-3f9b94d

**Comment by oktophonie** [comment]
This is expected. The algorithms for the placement of slurs and ties has been rewritten. As the offsets for slurs and ties are relative, not absolute, this means they are now relative to a different initial position. The position will therefore almost always be different (even if slightly), so they are reset when files are migrated from earlier versions.

Eventually of course slurs will avoid tuplets automatically, or vice versa; see e.g. https://github.com/musescore/MuseScore/issues/15336
