### ISSUE TITLE
[MU4 Issue] Control+[Number] shortcut with figured bass not working

### ISSUE THREAD

**Issue by aaronsendra** [musescore/MuseScore#15632]
**Describe the bug**
When I press the keys Control + [a number], in order to advance the cursor while I'm writing figured bass (for example, Control+6 to advance the cursor a half note), this shortcut doesn't work, it only writes the number I press.

**To Reproduce**
1. Create a new score
2. Write an aleatory whole note
3. Down that note, write any figured bass
4. Press Control + 6 to advance a half note over that whole to write another figured bass
5. The cursor doesn't advance and it writes a 6

**Expected behavior**
Instead of writing a 6, the cursor should advance a half note.

**Platform information**
 - OS: Windows 11

**Comment by cbjeukendrup** [comment]
Coincidentally, the fix (#15081) for this problem (which was earlier reported in #14916) was merged just today! So it will be in the next patch release. Thanks anyway for reporting!
