### ISSUE TITLE
[notation issue] polyrhythms of a beat of 5 sixteenths is not allowed

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15630]
**Describe the bug**
when making a tuplet out of a beat of 5, musescore shows an error instead of splitting the group of 5.

**To Reproduce**
1. make a bar with a multiple of five beats
2. select it and press ctrl+#
3. see the error

**Expected behavior**
it should allow the polyrhythm to be made of a group of 5 like this:
![image](https://user-images.githubusercontent.com/120861729/209752326-406a16e7-ab7f-4178-af7e-2116b73c19fe.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/120861729/209752285-a4080282-6ed7-46c0-b796-46ee191216b4.png)
![image](https://user-images.githubusercontent.com/120861729/209752288-1e46a037-9eca-4015-800d-c1d20e88dabe.png)

**Platform information**
windows

**Additional context**
4:9 rhythms are known to be possible and maybe 4:7 is allowed but not 4:5

**Comment by oktophonie** [comment]
Fixed by https://github.com/musescore/MuseScore/pull/15966
(apologies for my duplicated issue about it; I managed to miss this one)
