### ISSUE TITLE
i am having problems with midi

### ISSUE THREAD

**Issue by andy-bunny** [musescore/MuseScore#15642]
so I need help with my keyboard. so I plugged it into my computer and just so you know it is kind of old. and when I opened the musescore 4 software on my mac all seemed good. I then played something on my keyboard hoping to transfer it to notes but it just put all the notes I played into one large chord which was not what I played. I don't know why that happened and I really don't like it so if yall could help that would be great

**Comment by oktophonie** [comment]
Closing as much too vague, but if you are able to provide much more specific information (in the required format from the relevant issue template) feel free to file another issue.

**Comment by RobFog** [comment]
The Support forum ([link](https://musescore.org/en/forum/6)) is better suited for support requests such as this one.

This issue tracker is intended for concrete bug reports that allow for fixing specific bugs.
