### ISSUE TITLE
[MU4 Issue] Tuplet brackets/numbers not selectable using Alt + left/right

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#15641]
**Describe the bug**

For some reason Alt+up/down does not select tuplet numbers/brackets. 

**Platform information**
 
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223630304, revision: github-musescore-musescore-3f9b94d

**Comment by shoogle** [comment]
Closing in favour of https://github.com/musescore/MuseScore/issues/15641
