### ISSUE TITLE
[MU4 Issue] Valencian language detected as Catalan

### ISSUE THREAD

**Issue by aaronsendra** [musescore/MuseScore#15640]
**Describe the bug**
My system default language is Valencian, but MuseScore detects and uses the Catalan language when it is set at "System default".

**To Reproduce**
1. Set the device language to Valencian
2. Restart the computer to make the language changes effective
3. Open MuseScore
4. See that the translation corresponds to Catalan instead of Valencian.

**Expected behavior**
Show the Valencian translation instead of the Catalan one.

**Platform information**
 - OS: LliureX 21 (KDE neon 5.25)
 - OS: Windows 11

**Comment by cbjeukendrup** [comment]
I have created a test version for Windows, that will report which language code the system uses. You can download it from https://www.dropbox.com/s/k13jsa07jk37vcs/MuseScore-show_system_language-4.0.0.230022234-x86_64.zip?dl=0 (no need to create an account, just click "Download" in the top left corner). 

Could you run this build and tell me what it says?

**Comment by aaronsendra** [comment]
It says: "Your system languages are ca-ES-valencia, es-ES, en-US."

**Comment by cbjeukendrup** [comment]
Thanks! Then https://github.com/musescore/MuseScore/pull/15691 should be the solution! You can try the test versions for this fix in ca. 30 minutes from now.

**Comment by aaronsendra** [comment]
I have just tried it on both OS, and it works OK. The problem I see now is that when I check for language updates, it always detects there is an update and it never says that the language is up to date.

**Comment by cbjeukendrup** [comment]
Hm, yeah... I can reproduce that too. I'll take a look!

**Comment by cbjeukendrup** [comment]
@aaronsendra The fix for the original issue has been merged, so this is marked as fixed!

I've opened a separate issue for the language update problem, see #15704.

**Comment by aaronsendra** [comment]
I've downloaded the latest Nightly and the issue is happening again. MuseScore detects my language as Catalan and not Valencian.

**Comment by cbjeukendrup** [comment]
Hm... Is it the 4.0.2 nightly that you've downloaded? That apparently doesn't contain the fix yet. I've listed it to be included soon.

**Comment by Jojo-Schmitz** [comment]
It does not though

**Comment by bkunda** [comment]
🟢 Re-tested in OS: Windows 11 Pro, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d. Remains FIXED.
