### ISSUE TITLE
[MU4 Task] Musescore should add "a tempo" marking

### ISSUE THREAD

**Issue by savagestrawberryxd** [musescore/MuseScore#15652]
MS4 is great with the new ritardando option but even after the end of the rit.------- line the tempo remains slowed. There should be an "a tempo" marking, rather than the composer having to rewrite the original tempo marking which wouldn't look neat

**Comment by cbjeukendrup** [comment]
This has already been requested in #14445, so I'll close this as a duplicate. Thanks for reporting though!
