### ISSUE TITLE
[MU4 Issue] Arabic language names: Closing bracket is appears on the right

### ISSUE THREAD

**Issue by amsuu** [musescore/MuseScore#15654]
**Describe the bug**
In the language dropdown, the Arabic language names (which have brackets) have their "closing" bracket on the right instead of at the left, as they should.

**To Reproduce**
1. Open MuseScore in any language
2. Go to Edit > Preferences > General
3. Open the Languages dropdown

**Expected behavior**
Languages should be shown as: 
العربية (الخزائر)
العربية (مصر)
العربية (السودان)

**Screenshots**
![Bracketing](https://user-images.githubusercontent.com/102627400/210100650-9144b562-17dc-40a4-a104-adf3523760ae.png)

**Platform information**
 - OS: Windows 10
 - MuseScore 4.0.0

**Additional context**
[**Possible solution**](https://stackoverflow.com/questions/18375417/in-right-to-left-languagelike-arabic-and-hebrew-bracket-reversed) (also see [Right-to-left mark](https://en.wikipedia.org/wiki/Right-to-left_mark#Example_of_use_in_HTML))
[Similar problem](https://stackoverflow.com/questions/27910465/how-to-prevent-automatic-right-to-left-text-direction-for-hebrew-and-arabic) (also see [Unicode bi-directional support](https://en.wikipedia.org/wiki/Bidirectional_text#Unicode_bidi_support) and [#Marks](https://en.wikipedia.org/wiki/Bidirectional_text#Marks))

**Comment by HemantAntony** [comment]
@Tantacrul #16158 solves this too (@amsuu Feel free to check it out too) :)
