### ISSUE TITLE
[MU4 Issue]  Sustained note interaction inconsistencies

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#15653]
**Describe the bug**
If a sustained note is interrupted by a shorter note of the same pitch on a piano, the sound should stop at the end of the shorter note.  The actual behaviour depends both on how the two notes are entered - in separate voices or using cross staff notation - and on whether MS Basic or MuseSounds are used.  Only the former is modelled correctly.

**To Reproduce**
I investigated using the attached minimal examples

- **In MuseScore 3** the whole note is sustained through the bar and the eighth note is attacked on the third beat.  This is unreallistic.  Without pedal the note should stop sounding when the player releases the key at the end of of the eighth note.  It makes no difference to playback whether the whole and eighth notes are in separate voices on the lower staff (method a) or the whole note is on the lower staff and the eighth note is entered on the top staff but is moved to the lower staff using CTRL+SHIFT+DOWN (method b)

- **In Musescore 4** the playback is different and depends on whether you use method a or b but also on whether you are using MuseSounds or MS Basic.
   - **Using MuseSounds**
Using method a (separate voices), the playback is pretty much what a real piano would do.  The whole note sustains for two beats. On the third beat the eighth note is sounded and then the note is cut off at the end of the eighth note.  If pedal is added, the note sustains to the end of the bar.
Using method b (cross staff), the eighth note is not heard on the third beat, but the note is re-attacked very briefly right at the end of the bar (a short blip).  There is no difference with added pedal.
  - **Using MS Basic**
    Using method a (separate voices), the behaviour is similar to that with MU 3 but there is a very short but rapid decay after the eighth note is struck on the third beat, while the sound continues to sustain to the end of the bar.  With pedal that short, rapid decay is not heard and the sustain is as expected.
    Using method b (cross staff), the behaviour is the same as using method a with MuseSounds – i.e. what a real piano would do.  With pedal, the eighth note is heard to restrike and the sound sustains to the end of the bar.

- **In summary**
**Musescore 3:**  The sustained note is incorrectly sustained when it should be stopped by the later release of a shorter note.
**Musescore 4+MuseSounds:** Notes in separate voices model the correct behaviour and cut off when the shorter note is released. Cross staff notes miss the resounding of the later shorter note and there is an extraneous blip at the end of the sustained note
**Musescore 4+MS Basic:** With notes in separate voices the sustained note is incorrectly sustained when it should be stopped by the later release of a shorter note.  However, there is a rapid decay after the shorter note is struck.  With cross staff notes the correct behaviour is modelled and the longer note is cut off when the shorter note is released.

**Expected behavior**
- Using MuseSounds with simultaneous notes of the same pitch entered using cross staff notation there should be no "blip" at the end of the sustained note.
- Using MS Basic with simultaneous notes of the same pitch all simultaneous notes on the same staff but in different voices should stop when the shorter note is released.

**Screenshots**
Minimal test case
![Sustain_Test](https://user-images.githubusercontent.com/60138048/210095672-91df387d-b66f-4b62-b364-3f361b732e90.png)

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Additional context**
Minimal test scores

[Sustain Test MU3.mscz.zip](https://github.com/musescore/MuseScore/files/10325617/Sustain.Test.MU3.mscz.zip)
[Sustain Test MU4.mscz.zip](https://github.com/musescore/MuseScore/files/10325620/Sustain.Test.MU4.mscz.zip)

See also https://musescore.org/en/node/338405

**Comment by oktophonie** [comment]
As a pianist I'd have to side with those arguing that the sound should stop at the end of the _longer_ note.

**Comment by MarcSabatella** [comment]
I also absolutely agree the sound must continue to the end of the longer note as MuseScore 3 did, anything else breaks a lot of valid uses.

Anyhow, this is a duplicate of https://github.com/musescore/MuseScore/issues/13853 which was closed when it was fixed (mostly) for MS Basic, but it should have been immediately reopened as it was known at the time not to be fixed for Muse Sounds and fixing that was (and should be) considered a higher priority anyhow.

There are also half a dozen other reports of various side effects of this.

**Comment by SteveBlower** [comment]
How would that work physically.  If you look at the forum post that started my investigation you will see that the short note in question is part of an arpeggiated figure low down in the basement.  Holding the long note with a pedal makes everything very murky.  Do you mean that the common note of the arpeggio should be held with a finger and not released?

**Comment by DaddyLudwig** [comment]
As a pianist, if I saw a whole note and an eighth note of the same note in the same measure, or really any 2 durations of the same note where the first is longer(I commonly see this in Bach for instance), I'd do 2 attacks, one sustained for the length of the second note + any of what's left of the long note if it's not an end of bar attack and another for the length of the long note - the length of the second attack.

**Comment by oktophonie** [comment]
Yes, you'd hold it with the finger if the note needed to be rearticulated and you didn't want to use the pedal; that's how pretty much any pianist would interpret it, I'd like to hope.

Also, if there were similar notation for (say) two wind instruments on the same stave, there'd be no question of shortening the longer note to match the shorter one.

**Comment by SteveBlower** [comment]
I have a piano lesson next week.  Something to discuss with my teacher.

I'll shut up for now (and close this). :

**Comment by MarcSabatella** [comment]
FWIW, I'd only write this in situations where I expect the first note to be sustained via the pedal.  Like here:

![image](https://user-images.githubusercontent.com/1799936/210099145-c426922d-ffa6-48ba-9dc3-89a0441c916f.png)

But it's not underheard to write it in other situations.  I avoid it precisely because it's unclear and mostly nonsensical.

One of the linked issues is a bit more serious to me in that it even affected notes that don't actually overlap, just that follow each other in quick succession.  The second note cuts off way too soon, I guess because maybe internally Muse Sounds is overlapping the notes slightly for legato effect.  The result is disastrous:

https://user-images.githubusercontent.com/1799936/210099054-36e0442f-0ed6-4018-98d0-aa19fd8b7a39.mp4
