### ISSUE TITLE
[MU4 Issue] RTL Languages Break Loading Screen Info

### ISSUE THREAD

**Issue by amsuu** [musescore/MuseScore#15666]
**Describe the bug**
When using an RTL langauge (Arabic, Hebrew, Farsi, etc.), the startup loading screen version and website appear misaligned, as if flipped along their right side/margin.

**To Reproduce**
1. Change the app language to any RTL one (I used Hebrew)
2. Restart/Start the app
3. Observe loading screen info (version, website)

**Expected behavior**
Loading screen appears normally, no matter the language.

**Screenshots**
![Hebrew](https://user-images.githubusercontent.com/102627400/210139802-e829d443-570d-40fb-93df-24d98f8bf3d2.png)

**Platform information**
 - OS: Windows 10
 - Musescore 4.0.0

**Additional context**

***Side note**: When loading the app in an RTL language that doesn't have the "Loading..." string translated (I used
Egyptian Arabic -- العربية (مصر)), the dots are flipped and instead appear on the left of the text, like so:*
![egar](https://user-images.githubusercontent.com/102627400/210139833-27a72777-882b-45a4-8920-bf66394bbce7.png)
I wasn't sure if this was intended so i didn't make a separate issue

**Comment by HemantAntony** [comment]
@cbjeukendrup I managed to fix the first part. But I got stuck by the "…Loading" bug. When I checked Transifex, Arabic and Sudanese Arabic translations of "Loading…" are "…Loading". Could Egyptian Arabic be affected by this?

Also, there is a bug with Transifex currently for me. Some sort of server problem.

**Comment by HemantAntony** [comment]
I think I found the issue. The transifex thing was a weird co-incidence

**Comment by amsuu** [comment]
Should I create a seperate issue so we can close this one?

**Comment by HemantAntony** [comment]
@Tantacrul #16158 solves this issue also @amsuu

**Comment by Tantacrul** [comment]
Thanks @HemantAntony. Just reviewed and left a comment.
