### ISSUE TITLE
[MU4 Issue] RTL Languages Break Mixer Numbers

### ISSUE THREAD

**Issue by amsuu** [musescore/MuseScore#15667]
**Describe the bug**
When using any RTL language, the Mixer numbers appear flipped along the side closest to the center, compared to LTR languages

**To Reproduce**
1. Change the app language to any RTL one
2. Open any score
3. Open the Mixer
4. Observe Mixer dB numbers appearing behind Mixer lines

**Expected behavior**
Mixer appears normally no matter the language.

**Screenshots**
![Mixer](https://user-images.githubusercontent.com/102627400/210140424-5ddcc3f7-dc9f-49e8-8608-473476e215ca.png) 
![image](https://user-images.githubusercontent.com/102627400/210140533-75fe363b-6ed0-429c-b701-4311496fddb2.png)

**Platform information**
 - OS: Windows 10
 - Musescore 4.0.0

**Additional context**

**Comment by HemantAntony** [comment]
@Tantacrul I made a PR: #16158 :)
@amsuu do you mind checking out too?

**Comment by Tantacrul** [comment]
For me, this does appear to fix the mixer issue.
