### ISSUE TITLE
[MU4 Issue] Ties displayed in wrong staff after applying cross-staff notation

### ISSUE THREAD

**Issue by rich777300** [musescore/MuseScore#15662]
**Describe the bug**
The ties are displayed in the wrong staff after you apply cross-staff notation on a selection of notes. 

It will recognize the tie is possible because now (after you apply CS Notation) those notes are in the same staff but are displayed improperly.

**To Reproduce**
- Refer to video
- Generally, set things up so you have things to tie to, then apply cross-staff notation, then apply ties to the transformed notes to see the improperly displayed ties.

**Expected behavior**
Ties are displayed beside the notes they are tying.

**Platform information**
 - OS: Windows 10 64-bit

**Additional context**
Playback seems to be unaffected. The tiniest cut in sound can be heard?

https://user-images.githubusercontent.com/102642087/210125866-5fc081e5-d2ad-4797-814c-d0443cbe62d1.mp4

**Comment by bebobebo** [comment]
Behaviour varies according to whether the later tie chord has one note or many. See https://musescore.org/en/comment/1166872#comment-1166872

**Comment by bebobebo** [comment]
Please also check cross-stave grace-notes
[ties for cross stave notes and grace-notes.zip](https://github.com/musescore/MuseScore/files/10967378/ties.for.cross.stave.notes.and.grace-notes.zip)

**Comment by mike-spa** [comment]
> Please also check cross-stave grace-notes [ties for cross stave notes and grace-notes.zip](https://github.com/musescore/MuseScore/files/10967378/ties.for.cross.stave.notes.and.grace-notes.zip)

Also fixed by the same PR
