### ISSUE TITLE
[MU4 Issue] Incorrect/Various Instrument and Part Names

### ISSUE THREAD

**Issue by Ahh6483** [musescore/MuseScore#15660]
**Describe the bug**
Throughout the UI (On the main score, in the parts, in the Instruments Side Panel, in the Mixer, etc.) there are a few different names for some instruments or parts. Ex) Keyboard 1 will be call 'Keyboard 1' in Instruments and on the score, but on the mixer and in the Parts it is call 'Piano'.  

**To Reproduce**
1. Open Score (New or Old)
2. Click on 'Mixer'
3. Click on 'Instruments'
4. Click on Parts
6. See error

**Expected behavior**
I expect there to be a common global name for each part. Ex) Keyboard 1 will always be called Keyboard 1 whether is play piano or anything else. Just like if you name a part Reed 1, it will globally be know as 'Reed 1' to make organization, mixing, and parts a lot easier. When I change the name in the Instruments panel it only updates in the score, not everywhere. 

**Screenshots**
<img width="1301" alt="Screenshot 2022-12-30 at 10 04 24 PM" src="https://user-images.githubusercontent.com/79336035/210123218-37553f12-d1b4-4b90-978b-39d526b67905.png">
<img width="1190" alt="Screenshot 2022-12-30 at 10 00 03 PM" src="https://user-images.githubusercontent.com/79336035/210123225-40b66afe-41b9-41e7-adbd-deefaea8b9ae.png">

**Platform information**
 - OS: MacOS

**Additional context**
Screenshots from new and old scores.

**Comment by cbjeukendrup** [comment]
See also https://github.com/musescore/MuseScore/issues/21839#issuecomment-1982187754

**Comment by zacjansheski** [comment]
Let's close this and refer to 
https://github.com/musescore/MuseScore/issues/16962 (in depth discussion)
and
https://github.com/musescore/MuseScore/issues/14341 (feature request)
