### ISSUE TITLE
[MU4 Issue] Setting 'cue size' applies twice to some notes

### ISSUE THREAD

**Issue by Ahh6483** [musescore/MuseScore#15671]
**Describe the bug**
When selecting a range of notes and selecting 'Cue Size' some of the notes are the correct size however some notes are even smaller. When trying to undo this error it messes up the balance between the stem and note head. This error does not occur when you select notes one by one, only when you select a range of notes. 

**To Reproduce**
1. Select range of notes.
2. Click on 'Cue Size' in the 'Properties' Panel

**Expected behavior**
Expected all notes to be the same size and note varying in size.

**Screenshots**

https://user-images.githubusercontent.com/79336035/210156583-d219a88b-d1bf-48c0-b3a0-12049386bf7c.mov

The first range was able to make all the notes the proper cue size. The second range however was unable to on the first E. The only fix I can find is to go through and make each individual note cue sized. 

**Platform information**
 - OS: MacOS

**Additional context**
New Score

**Comment by Ahh6483** [comment]
Another note:
This issue also happens on notes of all duration, not just dotted notes.

**Comment by MarcSabatella** [comment]
I just ran into what I think is the same issue in the current 4.0.2 build, but for me, it's not some notes - it's all of them.  Not sure if that's a regression or not - it seems it could be somehow connected to the recent-ish change to allow notes to have independent properties.

The following example shows a passage normal, then small notehead, then cue:

![image](https://user-images.githubusercontent.com/1799936/222290336-c23a75cc-9f0d-442d-a922-a14dcbc16e04.png)

The third measure is *not* setting the "small notehead" properties but acts like it is, giving "double small" noteheads.

**Comment by DmitryArefiev** [comment]
Fixed in #16645
