### ISSUE TITLE
[MU4 Issue] Corrupting a score with duplets, time sigs and measure splitting

### ISSUE THREAD

**Issue by Fristover** [musescore/MuseScore#15679]
**Describe the bug**
Using tuplets (specifically a duplet here), key signatures and measure splitting can corrupt a score

**To Reproduce**
Steps to reproduce the behavior: (or see attached video)
1. Create a 12/8 score with 2 or more staves (a piano will do)
2. Add something like a 2/4 in the second bar
3. Dot the last quarter of measure 1 and create a duplet in one staff
4. Select the first rest of the duplet and go to tools -> measures -> split measure before selected note/rest, you will see an extra eight rest in the rest of the staves
5. delete the duplet, you'll see 3 eight rests in that staff and 4 in all the rest

**Expected behavior**
Not corrupting (lol) and respecting whatever the value should be, 3 eights in this case

**Screenshots**

https://user-images.githubusercontent.com/68985619/210188627-b341e8af-928e-4842-945c-e4c8c9794dc3.mp4

**Platform information**
 - OS: Windows 11

**Additional context**
Didn't try with other cases but I guess it happens in more situations.

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/15380

@Fristover could you please confirm using the nightly build of version 4.0.1? It will be available tomorrow:
https://ftp.osuosl.org/pub/musescore-nightlies

Thank you!

**Comment by Fristover** [comment]
Just tested it again on the latest nightly, can't reproduce it anymore so it's fixed :D
