### ISSUE TITLE
[MU4 Issue]Dynamics and articulations not recognised by VST

### ISSUE THREAD

**Issue by bryandadson** [musescore/MuseScore#15677]
**Describe the bug**
Dynamics and articulations are not recognised by Mus4 when using Spitfire Labs Epic Choir (it's the only VST I use, so can't confirm if others are the same)

**To Reproduce**
For example:
1. Select Spitfire Labs VST in Mixer
2. Add p crescendo ff dynamics to score
2. Play
4. No discernable difference in dynamic

**Expected behavior**
A very noticeable difference in dynamic, with crescendo. In the screen shot below, the parts all play at the same volume throughout, despite the variations in dynamics. Elsewhere articulations such as staccato and tenuto etc also do not work.

**Screenshots**
![Screenshot (387)](https://user-images.githubusercontent.com/120390381/210187747-f75011b2-8949-43db-9ac1-d72c25903b87.png)

**Platform information**
Windows 11
**Additional context**

**Comment by wyldcrd** [comment]
I’m going to test it with a couple of VSTs I have (a vocaloid alternative and a couple of synths)

I’m on win 10 but i doubt that will make a difference

**Comment by wyldcrd** [comment]
Also did a quick search through issues and a pull request fixed this, are you on the newest version?

https://github.com/musescore/MuseScore/pull/12568

**Comment by bryandadson** [comment]
HI

I had the beta version I downloaded in November, but didn’t try with VSTs (first experience). My current version and the one I identified this on, is the new Mus 4 as announced a couple of weeks ago...

Hope this helps

Bryan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by wyldcrd** [comment]
I could only test it on 1 vst because it does not detect versions other than 3. Works On My Machine™️

**Comment by wyldcrd** [comment]
But helm64 detects the dynamics and changes the velocity from forte to piano

**Comment by bryandadson** [comment]
Hmm. Interesting. I’m attaching the score with the sound from the Spitfire VST. It seems pretty uniform in volume to me. Perhaps some slight approximation of crescendo/diminuendo, but I think that’s the expressivity of the VST?
O_Magnum_Mysteriumfinal2022mus4 Sheet music for Piano, Bass guitar, Synthesizer (Mixed Quintet) | Musescore.com<https://musescore.com/user/17883526/scores/9370081/s/LzC5en>

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
