### ISSUE TITLE
[MU4 Issue] Crashes when reordering palettes in the palette view

### ISSUE THREAD

**Issue by Yzrsah** [musescore/MuseScore#15681]
**Describe the bug**
My MuseScore 4 has crashed a few times when reordering the sections of the palette view. Today I added some palettes and then went to drag them to reorder them and MuseScore crashed again.

**To Reproduce**
I can't reproduce the behavior consistently, it seems random. Today after MuseScore crashed I restarted and tried again to reorder them and it worked.

**Expected behavior**
No crash.

**Platform information**
 - OS: Windows 10

**Comment by oktophonie** [comment]
Closing in favour of the essentially-duplicate https://github.com/musescore/MuseScore/issues/15703
