### ISSUE TITLE
[MU4 Issue] Musescore will crash when the audio output device is not set to 44100 Hz 

### ISSUE THREAD

**Issue by 99hcl** [musescore/MuseScore#15685]
**Describe the bug**
Musescore will not open when an audio device is set to anything above 44100 Hz, simply showing a splash screen and closing without warning. It will crash mid-session if the audio device is set to a sampling frequency above 44100 Hz mid-session.

**To Reproduce**
1. Open Windows "Sound" setting, set primary audio device to any combination of channels and sampling frequency above 44100 Hz.
2. Attempt to open Musescore. Splash screen will be shown, but program will not launch.

Alternatively:
1. Set audio device to 44100 Hz and open Musescore normally.
2. Change audio device to 48000 Hz or above via the Windows Sound setting. A warning that programs using the device may stop working will appear. Click OK.
3. Musescore crashes.

Note that in both scenarios the application is prohibited from taking exclusive control of the audio device via Windows Sound setting.

**Expected behavior**
Needless to say, the expected behaviour would be for MU to work out of the box with whatever combination of channels and sampling frequencies I set my audio device to (or at the very least just 48k), or, **even better**: allow me to request a sampling frequency and preferred API along with buffer size from inside the I/O settings panel itself (just like REAPER, for example). Of course, for this to happen the program needs to open first. 

**Platform information**
 - OS: Win10, 64-bit

**Additional context**
Musescore has had problems with higher sampling frequencies since forever, and it seems this problem carried over to MU4. In MU3 it would stop all other applications from playing sounds, and hijack the device to 44100 Hz, even when it was blocked from taking exclusive control of the audio device via Windows settings. It would also not playback any sounds when started in a higher frequency. Multiple "Restart Audio and MIDI Devices" later, and maybe changing the API to something other than ASIO could make it work on a good day. In MU4 there is seemingly no way to set the API manually or reset the devices, so no workaround is possible. It's worth noting that after attempting to make MU4 work with my Behringer UMC404HD by setting it to a lower frequency, the option to make it 4 channel, 24 bit, 48000 Hz has disappeared entirely out of my Windows settings. I'll probably have to reinstall the driver to get it back.

I've also seen other issues being reported where users had to unplug their headphones in order to launch MU4 without crashing and I suspect this is what's at play.

**Comment by cbjeukendrup** [comment]
Hi! Could you please try if the build from https://github.com/musescore/MuseScore/suites/11044663711/artifacts/561149134 works correctly?

**Comment by 99hcl** [comment]
> Hi! Could you please try if the build from https://github.com/musescore/MuseScore/suites/11044663711/artifacts/561149134 works correctly?

It works! The program starts up and I'm able to change the I/O to my audio interface. 

However, I seem to be unable to set the buffer size to anything below 1024, and that is causing a pretty extreme delay in playback when using Muse Sounds. Also, if I change a sound on the Mixer during playback, part of the score plays back again. I guess I should open new issue tickets for these two problems. Thank you for the solution!

**Comment by cbjeukendrup** [comment]
@99hcl Thanks for testing! Both issues that you mention are already reported, so you don't need to log them :)
