### ISSUE TITLE
[MU4 Issue] Pedal lines shows dark bars when upload to musescore.com

### ISSUE THREAD

**Issue by notkaramel** [musescore/MuseScore#15680]
**Describe the bug**
After publishing score from MU4 to musescore.com, the first page shows normally, but from the second page, the pedal bars turns into a dark straight bar.
[Here is my recent score that has the issue](https://musescore.com/user/29658671/scores/9363754)

**To Reproduce**
Essentially publish the score from MuseScore4 directly, or upload it to musescore.com

**Screenshots**
![image](https://user-images.githubusercontent.com/24505220/210190153-ac4961d5-5456-4081-a5b0-f7cfb721056d.png)

**Platform information**
 - OS: Arch Linux
 - MU4 version 1.0.0

**Comment by DmitryArefiev** [comment]
Fixed in #18041 

Will be fixed on musescore.com after backend updating

**Comment by notkaramel** [comment]
@Jojo-Schmitz Do I have to reupload my score ([the affected one](https://musescore.com/user/29658671/scores/9363754)) or it will be automatically fixed once the backend is updated?

**Comment by notkaramel** [comment]
Got it, thanks!

**Comment by DmitryArefiev** [comment]
Fixed on musescore.com backend (when publish scores from **MuseScore 4.0.2**)

Closing

**Comment by Jojo-Schmitz** [comment]
@notkaramel now you can reupload your affected score(s)
