### ISSUE TITLE
[MU4 Task] Implement saving of parts independently from the score

### ISSUE THREAD

**Issue by frirobi** [musescore/MuseScore#15683]
In mu4 it is not possible to save separate parts that are independent of the score. this makes it impossible, e.g. to insert a text frame in one part without it affecting the score and the other parts.
(e.g. on the Trumpet part. - Adagio tacet.) And it is not possible from the Basso continuo part to delete the numeral to create a Cello part without also deleting the numeral in the score and in the Cembalo or Organ part. 
In mu4 non è possibile salvare delle parti separate indipendenti dalla Partitura. questo rende impossibile, ad es. inserire una cornice di testo in una sola parte senza che questo si riperquota sulla partitura e sulle altre parti.
(es. sulla parte della Tromba. - Adagio tacet.)  E non è possibile dalla parte del Basso continuo eliminare la numerica per creare una parte di Violoncello senza  cancellare la numerica anche nella Partitura e nella parte del Cembalo o dell'Organo.

**Comment by frirobi** [comment]
![cornice di testo su parte separata](https://user-images.githubusercontent.com/116483213/210211788-b02490b7-6262-4bb4-b859-2b986eb3ca8f.png)

**Comment by oktophonie** [comment]
Closing as duplicate of https://github.com/musescore/MuseScore/issues/15582
(The associated issue that you mention, of not being able to control what changes in score and parts are linked or not, or completely independent, is very much on the radar.)
