### ISSUE TITLE
[MU4 Issue] MS4 keeps crashing when clicking Publish tab

### ISSUE THREAD

**Issue by sepkG** [musescore/MuseScore#15696]
**To Reproduce**
Click on 'Publish' Tab on every type of score
App crashes

**Platform information**
 - OS: Windows 11

**Comment by abariska** [comment]
@sepkG Is the issue still reproducible on the last MU 4.0.2 or nightly builds?

**Comment by sepkG** [comment]
I just checked it with the nightly build 4.0.2. It seems to be resolved.

**Comment by abariska** [comment]
🟢 **Can't reproduce**

**Comment by sepkG** [comment]
After installing the stable version 4.0.2, MS4 crashes again when clicking the publish tab. I uninstalled MS4 and reinstalled it but the problem didn't go away.
