### ISSUE TITLE
[MU4 Issue] (Feature Request) A toggle for whether chord symbols play by default

### ISSUE THREAD

**Issue by Leonerd-04** [musescore/MuseScore#15699]
When writing music, I generally don't want chord symbols to play their chord. However, they play by default, so the only way for me to write them the way I want is to either uncheck the "play" box every time, or to copy + paste and change a chord symbol every time I need one.

It would be really useful to have a simple toggle to change this default behavior. If one happens to already exist deep in the settings somewhere, I apologize and this issue can be closed.

**Comment by iwoithe** [comment]
The option does exist - just uncheck `Play Chord Symbols` in the playback toolbar. :slightly_smiling_face:

![image](https://user-images.githubusercontent.com/73422868/210494686-c553058d-3b97-4d21-832e-7c7236cff2d3.png)

**Comment by Leonerd-04** [comment]
Ah, thanks a lot. I'm not sure how I missed this, apologies for the redundant issue.

**Comment by iwoithe** [comment]
> apologies for the redundant issue

Don't worry. :slightly_smiling_face:
