### ISSUE TITLE
[MU4 Issue] Customizing Pallets/Custom Workspace Extensively Causes Eventual Crash

### ISSUE THREAD

**Issue by ghost** [musescore/MuseScore#15703]
**Describe the bug**
When re-organizing the palettes/creating custom ones, Musescore 4 will crash with the pallets not saving.

**To Reproduce**
1. Open a score on Musescore 4
2. Start editing the palettes (delete all the default ones and add some on your own using the Master Pallet.
3. Musescore 4 will crash. When going back to the score, the custom pallets regress to a random point.

**Expected behavior**
Musescore 4 should not crash, and it should save my pallets when the program auto-saved before the crash.

**Platform information**
 - OS: Windows 11

**Comment by cbjeukendrup** [comment]
Related to #15681
