### ISSUE TITLE
[MU4 Issue] Incorrect playback of tremolo in strings

### ISSUE THREAD

**Issue by icebearisicebear** [musescore/MuseScore#15713]
When two tremolo notes are placed next to each other the convention is that they're played back to back as if they're one continuous tremolo note (tied up or not). In the MuseSounds playback of such tremolos in strings there's a slight gap between each note (e.g. two tremolo notes are played as if they were separate).

See attached file.
[tremolo playback.mscz.zip](https://github.com/musescore/MuseScore/files/10348067/tremolo.playback.mscz.zip)

**Comment by ChriiMoral** [comment]
https://github.com/musescore/MuseScore/assets/63615949/39ca2e36-350c-4555-ba85-35c13f02f03b

Having the note re-triggered is not desired in this example. It would be nice to have that option on the Performance button within the Properties pane (At the time, it's greyed out).
![image](https://github.com/musescore/MuseScore/assets/63615949/cdd955ba-1460-4185-99b9-7fe5dc4e4e9f)

**Comment by wizofaus** [comment]
This appears to only be due to the dynamic change, and it's not even clear there *is* a gap as such, but I agree the diminuendo isn't even. But if you swap the dynamics (*p* crescendo to *fff*) I definitely can't hear any gap or re-attack.
