### ISSUE TITLE
[MU4 Issue] Online playback of score does not play repeats, but animation does.

### ISSUE THREAD

**Issue by SilverGreen93** [musescore/MuseScore#15720]
**Describe the bug**
If I publish online a score from MU4 that was played back and saved as an MP3 without having the repeats playback activated, the online player will show that the repeats are playing, but the audio will go on wihtout the repeats.
So the audio will be in the future, but the selected measure that is playing will be wrong.

See my score here: https://musescore.com/user/36543683/scores/9378655

**To Reproduce**
1. Have a score with repeats.
2. Make sure the play repeats feature is deactivated from the playback menu
3. Save the score to publish online from the Publish tab
4. MU4 will ask to save an MP3 of the file.
5. Open the score online and click play.
6. The audio will not be in sync on the first repeat.

**Expected behavior**
The audio should be in sync. When generating the MP3 it should generate with the repeats as well if the Publish option is set to online.

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12

**Comment by SilverGreen93** [comment]
Seems to be fixed in latest MU 4.1-dev.
Re-upload now produces the expected playback behaviour.
