### ISSUE TITLE
[MU4 Issue]  Uploading an empty score to Musescore.com crashes Musescore.

### ISSUE THREAD

**Issue by PetJer** [musescore/MuseScore#15734]
**Describe the bug**
Musescore crashes when trying to upload an empty score to Musescore.com

**To Reproduce**
1. Have no score open:
![empty-score](https://user-images.githubusercontent.com/79419198/211023746-d3fc8b63-8a88-4f4d-b2ed-3f1cf6b0b2c7.PNG)

2. Go to the **Publish tab**:
![empty-publish](https://user-images.githubusercontent.com/79419198/211023756-abc88eec-35d5-45ef-9fef-ca8fa6312cef.PNG)

3. Click on **Publish to Musescore.com...**:
![publish-subtabs](https://user-images.githubusercontent.com/79419198/211024176-f35fc814-e9bd-497c-80d8-d6a22cbb9621.PNG)

4. Musescore closes.

**Expected behavior**
Musescore shouldn't let the user click the publish button/**any button** in the **Publish tab** if no score is selected (just disable all buttons)

**Platform information**
 - OS: Windows 10

**Comment by abariska** [comment]
Confirm. Reproduced on macOS 12.6

**Comment by DmitryArefiev** [comment]
Fixed in #16051
