### ISSUE TITLE
[MU4 Issue] Tempo change results in hanging, crash on save.

### ISSUE THREAD

**Issue by Laurelin** [musescore/MuseScore#15738]
**Describe the bug**
Musescore hangs forever if you add a tempo on a score with notes in it. If you add a tempo to a blank orchestra score, the tempo show twice up top instead of once up top and once above the violins. And if you do manage to change a tempo and then save, MS4 crashes immediately with no error messages

**To Reproduce**
1. Create a symphonic orchestra score
2. add some notes in the violin section
3. add a tempo to the first measure

**Platform information**
 - OS: Windows
 - MuseScoreNightly-230060304-master-7dd83e8-x86_64

**Comment by Laurelin** [comment]
I have now managed to do this with no notes added. Just attempt to change the tempo on an empty score, it hangs, I use task manager to close it, and now any time I attempt to save the score it crashes. It was impossible to save the tempo change because of the perpetual hang, and yet the score still crashes.

**Comment by MarcSabatella** [comment]
Hmm, there might be an issue with your template or something else about how you are creating the score - I've added hundreds of tempo markings to orchestral scores with no problems, and I just tried again in the current nightly using the provided "Symphony orchestra" template, adding tempos via shorcut, palette, and menu - all worked as expected.  Please attach the specific score that is giving you problems so it can be investigated.

**Comment by Laurelin** [comment]
Github doesn't support that file type.

<img width="686" alt="Screenshot_20230106_052505" src="https://user-images.githubusercontent.com/4733367/211110176-db20f7fc-79cb-4119-bc6c-5b0f92cf9c71.png">

[`The actual score, courtesy of the MS forum`](https://musescore.org/en/node/341556)

**Comment by RobFog** [comment]
You can change the file's ending to .zip instead of .mscz and it will work.

**Comment by Laurelin** [comment]
Ah, well. I've already gone through in detail every step on the thread I made in the Musescore Forums. @MarcSabatella 

I'll throw in the final (crash happy) score here directly though. 
[TestScore.zip](https://github.com/musescore/MuseScore/files/10363649/TestScore.zip)

**Comment by cbjeukendrup** [comment]
This was fixed in 4.1.0 (at least on macOS). Since it's very old anyway and we haven't seen any similar cases anymore either, I will close this.
