### ISSUE TITLE
[MU4 Issue] Crash when deleting staff containing system objects and all staves below in existing score with system objects and "Segno" marking

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#15735]
**To Reproduce**
1. Create a score from a template with system objects, like SATB+Piano or Symphony Orchestra
2. Add a "Segno" marking in some measure 
3. Delete the staff that shows the system objects and all staves below if any (so in the case of SATB+Piano, the Piano, and in the case of Symphony Orchestra, the whole strings section)
-> instant crash

**Additional context**
Originally reported in https://musescore.org/en/node/341484
I can't reproduce it with a Tempo marking rather than a Segno marker; for the Tempo, instead of a crash, the marking would be duplicated on the top staff.
Not yet fixed by https://github.com/musescore/MuseScore/pull/15715

**Comment by DmitryArefiev** [comment]
Retested on Win10
