### ISSUE TITLE
[MU4 Issue] Saving parts with a dot in the name truncates at the wrong point

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#15736]
**Describe the bug**
I name my files "Title (Composer, a. Arranger) [Instrumentation].ext", and when I exported the full score to a PDF, it correctly took that as the name. When I exported all the parts plus the full score as PDF, the new full score was named "Title (Composer, a.ext", and the parts were "Title (Composer, a-Part.ext". Clearly the code for exporting multiple parts takes a different execution path from the code for exporting a single full score, and believes that the first full stop is the end of the file name.

**To Reproduce**
1. Create a score named with another dot in the file name before the ".mscz" containing several parts
2. Export PDF to full score - the full name is respected
3. Export parts - the name is truncated

**Expected behavior**
The name including the dot should be preserved - only the last extension should be stripped off

**Platform information**
OS: Windows 10 Version 2009
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-223472200
Revision: github-musescore-musescore-5485621

**Comment by deswinteil** [comment]
can I try to work on this?

**Comment by deswinteil** [comment]
Actually,  this the assignment statement in "exportprojectscenario.cpp" leads to the issue
![image](https://user-images.githubusercontent.com/109189977/226078494-ba24f22b-fd28-46ba-b756-cb0065dffa62.png)

![image](https://user-images.githubusercontent.com/109189977/226078468-64c666af-719d-4088-888d-10ab133abacf.png)
I will try to solve this.

**Comment by deswinteil** [comment]
![image](https://user-images.githubusercontent.com/109189977/226085485-ce41559f-2cdb-43d4-9f4d-7e1085d1b20d.png)
Ok, Now I fully understand the reason for this error, it is because of the basename function, but I am not sure how to modify it 🤔

**Comment by deswinteil** [comment]
![image](https://user-images.githubusercontent.com/109189977/226086421-69630cd0-3584-499d-85a2-11fcb7c70daa.png)
 I want to use **completeBasename()** to replace **basename()**,I think it should be able to solve this issue. @cbjeukendrup

**Comment by Jojo-Schmitz** [comment]
IIRC a long time ago the same (or very similar) but got reported and resoloved in the very same way.
Might even have been me resolving it...

**Comment by deswinteil** [comment]
> 
Hah, So my solution is corecct?

**Comment by deswinteil** [comment]
> IIRC a long time ago the same (or very similar) but got reported and resolved in the very same way. Might even have been me resolving it...

Hah, That‘s interesting. So my solution is correct?

**Comment by deswinteil** [comment]
> IIRC a long time ago the same (or very similar) but got reported and resolved in the very same way. Might even have been me resolving it...
@Jojo-Schmitz Hah, That‘s interesting. So my solution is correct?

**Comment by Jojo-Schmitz** [comment]
I believe so, yes

**Comment by Jojo-Schmitz** [comment]
But see https://musescore.org/en/node/341230 -> https://musescore.org/en/node/14537 (and apparently it wasn't me but @lasconic, who fixed it)

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.org/en/node/20792 and 6de343c

**Comment by deswinteil** [comment]
> I believe so, yes. But when in doubt, try it out ;-)
> 
> But see https://musescore.org/en/node/341230 -> https://musescore.org/en/node/14537 (and apparently it wasn't me but @lasconic, who fixed it, Edit: no actually @wschweer, see https://sourceforge.net/p/mscore/code/5237 and https://sourceforge.net/p/mscore/code/5239)
> 
> See also https://musescore.org/en/node/20792 and [6de343c](https://github.com/musescore/MuseScore/commit/6de343cf2ed16d323d14808e509898c45c71c502) (this time really @lasconic)
@Jojo-Schmitz 
thanks a lot for your suggestions! I 'll read these websites carefully.
And I have tried this solution,I think the correct file name should be **Title (Composer, a. Arranger) [Instrumentation].ext.pdf**,but actually it's **Title (Composer, a. Arranger) [Instrumentation].pdf**

**Comment by cbjeukendrup** [comment]
@deswinteil Your suggested change is indeed correct. Feel free to open a PR for it!

**Comment by DmitryArefiev** [comment]
Fixed in #16906
