### ISSUE TITLE
[MU4 Issue] Unable to set brackets and braces invisible

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#15741]
**Describe the bug**
It is not possible to set Brackets and Braces invisible

**To Reproduce**
1. Select Bracket
2. Click "Visible" in 'Properties' tab
3. Nothing happens

**Expected behavior**
Brackets hides.

**Screenshots**

https://user-images.githubusercontent.com/1646034/211111387-a4695284-d78e-4c84-8f58-516070e0ad43.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
May be also related with #12215

**Comment by mike-spa** [comment]
Just for additional context. 
Toggling the "visible" property for a bracket _globally_, meaning in a way that affects all the instances of that bracket in the score, is very straightforward to implement. And I can't think of any particular reason why we shouldn't allow that in the program, so it's something that we may just go ahead and do.
Toggling the "visible" for an _individual_ bracket of an individual system, however, is a different story. Cause those items don't survive layout (the layout of a system can change depending on any change in the score, and they are always redrawn), so we'd need to think carefully about where and how to store the information about visibility. 
I'll look into that!

**Comment by iainhallam** [comment]
@RomanPudashkin should we open a new issue for the possibility of hiding individual systems' brackets and braces?
