### ISSUE TITLE
[MU4 Issue] Inspector: undefined behaviour when clicking "apply to style" with multiple elements with different values selected

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#15759]
**To Reproduce**
1. Create score
2. Enter notes with stems (or anything with a property that has an corresponding style setting)
3. Change stem thickness for one note to some value
4. Change stem thickness for another note to a different value
5. Select both stems
6. Try to click '...' > "Apply to style"
-> Because the current value is defined because it is different for the selected elements, an empty `PropertyValue` gets stored to style, resulting in a default stem width of zero.

**Expected behavior**
Probably the "Apply to style" button should just be disabled in this case? 

**Screenshots**

https://user-images.githubusercontent.com/48658420/211206209-76e5519f-4000-44ed-9a52-db108a87a6ac.mov

**Comment by Tantacrul** [comment]
Oh my god, that made me laugh. The punchline at the end is wonderful! If I was doing a video on this app, I would have had a field day with that!

So... if you select two things with different values, the 'save as style' button should be disabled. That seems pretty obvious.

**Comment by DmitryArefiev** [comment]
Fixed in #16932
