### ISSUE TITLE
[MU4 Issue] Musescore crashes when I try to change instrument in guitar tab to standard notation 

### ISSUE THREAD

**Issue by stand13** [musescore/MuseScore#15756]
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by MarcSabatella** [comment]
In order for someone to be able to investigate, please edit your description to provide the requested details

**Comment by cbjeukendrup** [comment]
Duplicate of #15757
