### ISSUE TITLE
Properties > Fret diagrams: when applying scale value to style, in fact 100x the scale value is applied to style

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#15752]
**Describe the bug**
In the Inspector, in some cases, there is a conversion between the value displayed in the UI and the internal value. For example, a scale value is internally stored as a real number, but in the UI presented as a percentage. But today, while digging in the code, I found something strange: this conversion is not applied when applying the current value to style. This results for example in the following bug:

**To Reproduce**
1. Create score
2. Add fret diagram
3. In Properties > Settings, change scale
4. Apply to style
-> Boom

**Screenshots**

https://user-images.githubusercontent.com/48658420/211175424-c4adb403-8687-431d-af52-f66194438e06.mov

**Additional context**
This was simply the first example I found, but this may very well apply to other elements and properties too; maybe with even more janky results.

**Comment by cbjeukendrup** [comment]
It seems this has been fixed (by e6457fb41ce568ef882444b5aa42293f751eec97). @DmitryArefiev or @zacjansheski could one of you confirm that? (retesting in 4.2 build should be enough)

**Comment by zacjansheski** [comment]
Fixed in 4.2
