### ISSUE TITLE
[MU4 Issue] Crash when dropping staff type change on multi-measure rest measure

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#15769]
**To Reproduce**
1. Create score
2. Enable multi-measure rests by pressing M on the keyboard
3. From the Layout palette, drop the Staff Type Change element on the measure containing the multi-measure rest symbol (not on the symbol itself because that does nothing).
-> Crash

**Comment by DmitryArefiev** [comment]
Fixed in #15891
