### ISSUE TITLE
[MU4 Issue] MuseSounds cannot handle large scores

### ISSUE THREAD

**Issue by metasekk** [musescore/MuseScore#15768]
**Describe the bug**
When a score becomes large (high number of pages whatever the content of the score is - *can be empty* - or medium number of pages with a lot of notes), Muse Sounds stop working and become permanently silent from a certain point onwards.

**To Reproduce**
1. Create a new empty score using MuseSounds in at least one staff.
2. Add more than 1000 bars (2*999 for example).
3. Go to the end of the score, and add notes on the staves using MuseSounds.
4. Hear no sound. Besides, there exists a well-defined bar before which MuseSounds works perfectly and after which it is permanently turned off.

**Expected behavior**
During playback, any staff using MuseSounds should play wherever it is located in the score, regardless of the length and content of the score.

**Screenshots**
I provide a short [video](https://drive.google.com/file/d/1aK4jwHAQkP4d1s6IKKsEmYvMDy7sZUcM/view?usp=share_link).

**Platform information**
 - OS: Windows 10 Version 22H2, 64 bits, x64-based processor
 - Tested and verified on: MuseScore Release version (64-bit): 4.0.0-223472200 with MuseSampler v.0.3.2 ; MuseScoreNightly-230080305-master-3602349-x86_64 with MuseSampler v.0.3.2

**Additional context**
I believe it is most likely to be correlated with https://github.com/musescore/MuseScore/issues/15094. If this is established, then the moment when MuseSounds is turned off depends at least on:

- The number of notes of the score;
- The number and values of tempo markings;

Consequently, in empty scores, MuseSounds can work up to more than 1000 bars (1075 in the case of the video I provide) but when the score contains stuff, the bug can happen at much lower bars (bar 367 in the score provided in https://github.com/musescore/MuseScore/issues/15094).
This variability makes this problem highly disabling.

**Comment by cbjeukendrup** [comment]
This came up a while ago on the MuseScore.org forum too. I shared it with the Muse Sounds team, and @iamtesch told me that they basically already have a fix, but this will require a change in MuseScore itself too, so will be released together with the next MuseScore update.

**Comment by DmitryArefiev** [comment]
Fixed in #16464 but still doesn't work because of an old version of MuseSampler. 

Should be rechecked when **v0.4** is released

**Comment by DmitryArefiev** [comment]
Tested on **4.1 RC build**, Win10, MuseSounds, Muse Sampler library is **0.4.0** - **FIXED**
