### ISSUE TITLE
[MU4 Issue] [Muse Sounds] Sound name is Tam-tam instead of Tam-Tam

### ISSUE THREAD

**Issue by Fristover** [musescore/MuseScore#15763]
**Describe the bug**
Muse Sounds has the Tam-Tam sound labeled as Tam-*t*am but MS itself uses Tam-*T*am for the instrument name, looking inconsistent

**To Reproduce**
1. Create a new score, add a Tam-Tam
2. Use Muse Sounds and look into the mixer
3. See instrument name "Tam-Tam" and sound "Tam-tam"

**Expected behavior**
Both names are the same (Preferably both Tam-tam [edited])

**Screenshots**
![image](https://user-images.githubusercontent.com/68985619/211209939-5f84e860-78eb-4cd6-9355-ed3067f6b5d1.png)

**Platform information**
 - OS: Windows 11

**Additional context**
It's a really small issue but I can't unsee it now

**Comment by oktophonie** [comment]
Actually I'd prefer Tam-tam for both

**Comment by Fristover** [comment]
Okay, I'm not really sure about which one was correct so I just guessed haha

**Comment by shoogle** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/19010
