### ISSUE TITLE
[MU4 Issue] Slide notation lost on linked tablature staff after file reload

### ISSUE THREAD

**Issue by Atomk** [musescore/MuseScore#15764]
**Describe the bug**
I have a bass guitar staff with a linked tablature staff. Applying a slide in/out on a note adds a symbol both in the main staff and in the tablature staff. After saving and reloading the file, the symbols on the tablature staff are lost. In some rare cases, a symbol disappears on the main staff but is kept on the tablature (see screenshots below)
This also happens with fall/dalt/plop/scoop symbols, I haven't tested any other instruments or notation but it seems glissandos are fine.

**To Reproduce**
1. Create a new bass guitar part with default settings
2. Add a linked tablature staff
3. Add some notes and apply slide in/out to some of them
4. Save the file, close and reload it
5. The notation in the tablature should be missing

**Expected behavior**
All of the notation is synced properly between linked staves.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/6122017/211209750-396b2791-2637-4106-a862-22d943c03f7a.png)

After saving and reopening the file:
(look at the first and last note in the tablature)
![image](https://user-images.githubusercontent.com/6122017/211209839-c77d6603-091b-441d-926a-ec0c32f5e763.png)

Sometimes the opposite happens:
![image](https://user-images.githubusercontent.com/6122017/211210096-3dfd567b-dece-48a1-ae06-567dbd78239e.png)

**Platform information**
 - OS: Windows 10 Pro x64 (21H2, build 19044.2364)

**Comment by oktophonie** [comment]
(Still reproducible as of MuseScore version (64-bit): 4.0.2-230510504, revision: github-musescore-musescore-8c85e6c)
