### ISSUE TITLE
[MU4 Task] Add ‘Rest‘ section in Properties panel

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#15779]
**Task description**
This task would resolve #15446.

A new ‘Rest‘ section should appear in the Properties panel whenever a rest is selected in the score. 

For now, it will only contain the **Beam type** settings, as currently found in the ‘Note‘/‘Beam‘ section of the Properties panel.

<img width="731" alt="Screenshot 2023-01-09 at 3 19 49 pm" src="https://user-images.githubusercontent.com/86290556/211329470-ea0e7917-38ff-45bd-8da6-f7726a5e1e17.png">

_N.B. The mockup above shows the variant of the **Beam type** settings as described in #9892. If practicable, it could be good to tackle both of these issues together._

When multiple elements – including a rest – are selected in the score, a new ‘Rest‘ button will be shown in the Properties panel. Note that the icon for this button is now available in the latest version of musescoreicon. 

<img width="371" alt="Screenshot 2023-01-09 at 3 12 46 pm" src="https://user-images.githubusercontent.com/86290556/211328837-f27c0a46-9fe8-4fad-a7d1-4f5c5bd3329a.png">

Thanks! 

FYI @oktophonie @Tantacrul @jessjwilliamson

**Comment by cbjeukendrup** [comment]
@bkunda if the user makes a selection containing both chords and rests, and then changes the beam mode in either the "notes" section or the "rests" section, what should happen?
- if this would only affects the chords (or only the rests), then the user may have to do the same thing again for the other kind of element, or the user may think that it doesn't work for rests and give up;
- if this would affect both chords and rests, it might be confusing because perhaps in certain cases the user does want to change only one of them.

Personally I have a slight preference for the latter option, but it would be even better if we could somehow convey more explicitly that this setting is shared between notes and rests. What do you think?

**Comment by Tantacrul** [comment]
I definitely think it should be option 2. In fact, we may want to eventually create a special condition for when the user selects both notes and rests at the same time, where beaming becomes a self-contained category.

**Comment by iwoithe** [comment]
I've thought of a (single) problem with this. Take the following example. Specifically, how changing the rest and note beaming gives an incorrect beaming result (I think. Correct me if I'm wrong).

*NOTE: The following video is using option 1 (how the PR is at the time of writing)*

https://user-images.githubusercontent.com/73422868/214720180-3a80e4f8-4dc9-4d54-9a36-48e8c4f7b954.mp4

With the new proposed behaviour: sure, you can solve it by selecting the third note and changing the beam mode back to automatic. But for me this would be quite a pain, particularly if this has to be done with many bars.

Just thought I'd put this out there. I am working on updating the PR as requested. :slightly_smiling_face:

**Comment by oktophonie** [comment]
I was about to mildly object, but then having tried it find that it does actually feel like it makes sense. Applying the same beam option to a whole range is rarely a sensible thing to do anyway - so in reality, tedious though it may be in certain cases, what you'll usually be doing is selecting a whole load of specific notes or rests.

(Though I agree that what will be better is a better way of changing beaming for notes and rests together, which also replaces these inadequate and unintuitive beam options with something more flexible that's also better suited for achieving the result you want in the common use cases in a clearer, simpler way)

**Comment by oktophonie** [comment]
I wondered at first whether it made sense for the ### beamtype options to be available on notes which have no flags (i.e. quarter and longer).
On reflection perhaps this does no harm, and could be useful in a fringe case where it's found useful to have 'join beam' set on both notes here:
![image](https://user-images.githubusercontent.com/20604032/214787466-b09ae142-0468-4174-8d3d-bb771307cccb.png)
which would mean that if you change the duration of the second note to something shorter, it would become:
![image](https://user-images.githubusercontent.com/20604032/214787654-616190f9-4a3d-4fe9-b18c-c0d47ebe5491.png)

Which brings me to my real question, which is possibly to become a separate issue. It doesn't seem to possible to apply beam options to rests which are a quarter or longer - or at least, applying them seems to have no effect. I can join the first two notes here easily enough, but can't see any way of joining the second two:
![image](https://user-images.githubusercontent.com/20604032/214788023-80043475-09de-4ad3-b2f2-b35ef89ea980.png)
which seems an arbitrary and unfortunate limitation.
