### ISSUE TITLE
[MU4 Issue] Caesuras do not Update Playback

### ISSUE THREAD

**Issue by 398utubzyt** [musescore/MuseScore#15773]
**Describe the bug**
Caesuras are completely ignored for note input. The position marker and dynamics seem to stop but note input continues.

**To Reproduce**
1. Play through part of the score
2. Add any type of caesura into the score
3. Play through that same part, now with an added pause
4. Playback will continue while position marker halts in place

**Expected behavior**
The playback system should update the audio track when a caesura is added. I assume this is because note inputs are not updated to compensate for new pauses.

**Video Demonstration**
https://user-images.githubusercontent.com/46660281/211233826-e16d00e5-c547-4cf0-b80d-71146043f4ee.mp4

**Platform information**
 - OS: Windows 10

**Additional information**
This bug causes the audio and score to not be synced up with each other. This can lead to more problematic issues with playback because there does not seem to be a way to fully refresh it without a full restart.

**Comment by ThatXliner** [comment]
I can reproduce.

**Comment by Ahh6483** [comment]
I am also experiencing this issue on Mac OS.

**Comment by maffan** [comment]
I'm also experiencing this on Ubuntu 22.04

**Comment by ironmatic1** [comment]
Hi, I just would like to bump this thread. In the latest build, 4.1.1.232071203, caesuras are still completely unusable without saving the 'broken' score and reopening it. It wasn't like this a while back—somewhere along the line, something in the notchcode broke it. I'm surprised this bug has been open almost a year; caesuras are a rather important feature in music.

**Comment by ThatXliner** [comment]
> As a workaround, it also works to simply edit anything in the score that causes the playback info to be regenerated. That is, it's only a temporary glitch that appears if you try to playback immediately after adding the caesuras but goes away as soon as you do almost anything else to the score.

This includes adding a tempo marker on the same note you added the caesura, as I found out today

**Comment by DmitryArefiev** [comment]
Fixed #20982

Please reopen if still occurs
