### ISSUE TITLE
[MU4 Issue] No audio playback on fresh install

### ISSUE THREAD

**Issue by fpdotmonkey** [musescore/MuseScore#15786]
**Describe the bug**

I just installed Musescore 4 on a machine that had never previously had any version of Musescore previously and on launch it does not play back any audio.

**To Reproduce**
1. Install Musescore (or alternately Factory Reset the existing install)
2. Launch the program
3. Create a new score and input a few notes
4. Hit the play button in the top right
5. Observe that no audio is produced and that the blue progress line appears at the beginning, though it does not move beyond the beginning

**Expected behavior**
Audio plays

**Screenshots**

![A sample of notes not playing](https://user-images.githubusercontent.com/3139615/211410905-26b85d9a-dc44-4a1d-9c19-711c756ee213.png)

**Platform information**
OS: Ubuntu 22.04.1 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472159, revision: github-musescore-musescore-5485621
Audio Server: pipewire 0.3.48

**Additional context**
I tried installing Muse Sounds and doing playback with them instead of the default, but that didn't work.

I noticed this in the output logs which seems it might be relevant.

```
23:32:36.646 | ERROR | 139869787493952 | SynthResolver | resolveSynth: invalid audio source params for trackId: 1
```

I also noticed that MuseScore loads the JACK audio server by default.  As said above, I have pipewire installed (including pipewire-jack), so there might be some compatibility issue there?  (I tried running running it explicitly as `pw-jack ./MuseScore[...].AppImage` to maybe coax it to work, but alas)

**Comment by zacjansheski** [comment]
Please take a look here to see if there are some useful workarounds
https://github.com/musescore/MuseScore/issues/11220

I will close this as it seems to have gone unnoticed / stale and we have other logged issues, see also:
https://github.com/musescore/MuseScore/issues/16787
https://github.com/musescore/MuseScore/issues/15937
