### ISSUE TITLE
[MU4 Issue] Severe crash and file corruption on templates with duplicate system marks

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#15796]
**To Reproduce**
1. Create a new file from one of the templates which have duplicate system marks (for example: SATB + Piano)
2. Save the file
3. Open the instrument panel, and delete the instrument which is supposed to hold the duplicate system mark (in this case, the Piano)
4. Try to insert from palette any system text or object (tempo mark, or rehearsal mark, or whatever) : **program will crash**
5. Reopen the program after the crash, and reopen the the file
6. **The program will now crash any time you try to save the file**, which means the entire file is now unusable.

Edit: the crash can actually be reproduced also without steps 3 & 4.

**Comment by cbjeukendrup** [comment]
Seems related to https://github.com/musescore/MuseScore/issues/15735

**Comment by DmitryArefiev** [comment]
Fixed in #15806

**Comment by DmitryArefiev** [comment]
> Seems related to #15735

@cbjeukendrup Unfortunately crash with segno still occurs in #15806
