### ISSUE TITLE
[MU4 Issue] Alto Horn position incorrect in Brass Band score order

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#15791]
**Describe the bug**
Alto Horn (in UK known as Tenor Horn) should be position after flugelhorn and before baritone when using the Brass Band score order. Instead they are placed even after the tuba.

**To Reproduce**
1. Start a New Score
2. Set the score order to Brass Band
3. Add the Flugelhorn, Alto Horn, Baritone Horn, Trombone, Tuba

**Expected behavior**
Alto Horn (in UK known as Tenor Horn) should be position after flugelhorn and before baritone when using the Brass Band score order.

**Screenshots**
![ms4-brassband-order](https://user-images.githubusercontent.com/13550012/211482969-6a8dc7d0-5c4e-4fc0-8c61-6377eefe8bcb.png)

**Additional context**
When using the Horn in Eb, this is placed at the position above, however that Horn instrument isn't the one used in a Brass Band.

**Comment by DmitryArefiev** [comment]
Fixed in #19336
