### ISSUE TITLE
[MU4 Issue] Toggle rhythmic slash notation leads to stem that are too long

### ISSUE THREAD

**Issue by moogly81** [musescore/MuseScore#15792]
**Describe the bug**
Turning a long stem note into a rhythmic slash notation lead to a stem that is too long. 

**To Reproduce**
1. create a note in the very high or very low register
2. select the note, and go to Tools --> toggle rhythmic slash notation
4. The stem of the slash notation is too long

**Expected behavior**
The stem of the slash note is normal

**Screenshots**
On the image, the stem on the 2nd slash notation is too long. 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/2691085/211509478-54b1b8e1-582d-4a2a-8a36-5a05469277ba.png">
example score : https://musescore.com/user/28745487/scores/9452614

**Platform information**
 - OS: [e.g. macOS ]

**Comment by MarcSabatella** [comment]
Confirmed.  This is a regression vs MU3.
