### ISSUE TITLE
[MU4 Issue] Repetition with prima volta gets incorrectly played if the tempo is not 100%

### ISSUE THREAD

**Issue by Futurama39** [musescore/MuseScore#15801]
**Describe the bug**
In any score with a repetition that contains a prima volta, if the playback speed is not set to 100%, the second repetition will begin either early or late based on the speed set

 - If set >100% there will be a gap of silence between the end of prima volta and the second repetition
 - If set <100% the second repetition will start before the prima volta has ended

**To Reproduce**
1. Create a score with a repetition and a prima volta
2. Change back the playback speed using the undocked playback panel, the effect gets more pronounced the more the speed is away from 100%

**Expected behavior**
The repetition starts again after the prima volta finishes playing. I've tested with Musescore 3.6.2 using the play panel to manipulate tempo and there it works as expected so this would be a regression

**Screenshots**
Setup in the example score that reproduces the issue
![image](https://user-images.githubusercontent.com/12499845/211558637-c5dd90fe-2a4c-4718-92a3-f87d406a1542.png)

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

**Additional context**
- [Musescore.org issue tracker link ](https://musescore.org/en/node/341879) (with example score)
- I was able to reproduce this using both using Muse Sounds and using Musescore Basic sounds

**Comment by zacjansheski** [comment]
Closing as fixed by https://github.com/musescore/MuseScore/pull/16045
