### ISSUE TITLE
[MU4 Issue] Alto Horn Eb range in Brass Band template does not match instrument definition

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#15802]
**Describe the bug**
When the Alto Horn Eb is added as an instrument to a score, the range for amateur and prof are different compared to the range used in the Brass Band template.

According to the instrument definition we have:
![ms4-alto-horn-def](https://user-images.githubusercontent.com/13550012/211558699-0afeeff4-77c8-486b-8e35-abf4eaf6f09a.png)

In the Brass Band template the range is shown as:
![ms4-alto-horn-bb-template](https://user-images.githubusercontent.com/13550012/211558597-1a078e3d-fc57-4ca8-ba06-28e5ca02046c.png)

**To Reproduce**
1. Start a New Score
2. Use the Brass Band Template
3. Check the range for the Horn(s)

**Expected behavior**
Believe in this case the Brass Band template should be updated to match the instrument definition.
Low range for amateur and would be A2
High range for amateur would be C5
High range for prof would be D#5

**Comment by zacjansheski** [comment]
I can fix this, but I don't quite understand the expected range

New Alto Horn in Eb range:
Amateur A2-C5, Professional A2-D#5

Range of "Solo Horn", "1st Horn" and "2nd Horn" in the Brass Band template:
Amateur C#2-A#4, Professional A1-D#5

This doesn't match the pitches requested above.

It looks to me that when that template was made, the instrument "Horn in C Alto" was used and then a transposition value was added, and that instrument does not appear as an option in MS4 instruments.

**Comment by henkdegroot** [comment]
@zacjansheski maybe I got mixed up by concert pitch/sounding pitch. Will update the issue.
