### ISSUE TITLE
[MU4 Issue] Slur overlapping with Tie

### ISSUE THREAD

**Issue by Gobbel2000** [musescore/MuseScore#15805]
**Describe the bug**
When entering the following notes (the A's are tied, then all notes are connected by a slur), the slur overlaps with the tie.

![slur_overlap](https://user-images.githubusercontent.com/26202156/211567008-9d4ee60b-1fb3-41c1-a7e1-e98d799c0ad3.png)

**Expected behavior**
There should be a gap between both lines.

**Platform information**
 - OS: Arch Linux
 - Version: Latest master branch (`a6ec87df`)

**Additional context**
Could be similar to #15317 but is not resolved by #15482.

**Comment by Jojo-Schmitz** [comment]
Just for the record: this is a regression vs. 3.x:
![image](https://user-images.githubusercontent.com/1786669/234061605-7466a1da-b183-432f-a498-6bc3302e6a5b.png)
