### ISSUE TITLE
[MU4 Issue] Staff bracket should be hidden when piano score goes to single staff

### ISSUE THREAD

**Issue by moogly81** [musescore/MuseScore#15817]
**Describe the bug**
Some scores (mainly piano) go from double staff to single staff back and fourth. When using double staff, bracket should be there. This is fine as is. But when going to single staff, the bracket should be hidden. It provides a clear indicator that we are going from double to single staff. 

**To Reproduce**
1. Make a piano score. double staff
2. Insert notes on both staff on line 1. Insert notes on treble clef only on line 2
3. Instruments --> piano --> bass clef (parameters wheel) -->  tick "Hide measures that do not contain notation" 
5. See error : bracket should be hidden

**Expected behavior**
When going to single staff, bracket should be hidden. 

**Screenshots**
bracket at measure 8 should be hidden
<img width="768" alt="image" src="https://user-images.githubusercontent.com/2691085/211778933-70f62793-46dd-4147-8e0f-27ccf4561688.png">

**Platform information**
 - OS: [e.g. macOS]

**Musescore example**
https://musescore.com/user/28745487/scores/9468214

**Comment by oktophonie** [comment]
The staff is still there, and space is being made for it. It's just that none of the bars on the system contain notation, so they are hidden, cutaway-style. In this context it makes sense to me that the brace remains.

It's very unconventional to use cutaways like this just for a piano score. To actually hide the stave, you want Format > Style > Hide empty staves within systems. That also hides the brace, though the very next option "Show brackets when spanning a single staff" also lets you configure that.

![image](https://user-images.githubusercontent.com/20604032/211786180-2471bfe5-ae48-4978-b15e-eccb567daa73.png)

**Comment by moogly81** [comment]
Correct ! Sorry about that. I should've asked the community 1st. I did not get the subtle hidden staff "cutaway style" vs "normal" hidden staff. You can close this one.
