### ISSUE TITLE
[MU4 Issue] Playback setting Dialog box should not  immediately close after selecting any option.

### ISSUE THREAD

**Issue by Tejkh1** [musescore/MuseScore#15812]
**Describe the bug**
while selecting any option in playback setting dialog box, the box should not close after any selection. (so that user can select multiple option)

**To Reproduce**
1. open any score.
2. Click on 'playback setting'
3. select any option

**Expected behavior**
the dialog box should remain on the screen. 

**Platform information**
 - windows

**Comment by MarcSabatella** [comment]
Can you explain which "playback setting" you mean?  Are you referring to the setting on the Playback tab of the Properties panel?  This stays open for me, until you select something for which it isn't relevant.

**Comment by Tejkh1** [comment]
Thinking about this again ,I think that you are right ,that would be pretty uncommon to want to change more than one thing .
I think I should close this issue now.
