### ISSUE TITLE
[MU4 Issue] Tempo wrong when initializing a score with compound meter

### ISSUE THREAD

**Issue by cmaxreilly** [musescore/MuseScore#15845]
When initializing a score that make initial use of a compound meter, the tempo played is incorrect. For example, when you make a score in 6/8, and set the dotted quarter equal to 120 in the new score wizard, it actually sets the quarter note to 120. This is easily worked around by simply selecting the tempo, deleting one of the numbers, retyping the number, and clicking elsewhere in the score, as in my examples.

1. Create a new score
2. Set the time signature to a compound meter
3. Set the tempo with a dotted quarter equaling a bpm
4. Press done
5. Write some music
6. Bpm has been assigned to the quarter note, not the dotted quarter note.

The new score wizard should be capable of assigning initial tempo to the quarter note.

 -Happens in OSX and Linux

Examples in the comments.

**Comment by cmaxreilly** [comment]
[score_creation_demo.mp4.zip](https://github.com/musescore/MuseScore/files/10405380/score_creation_demo.mp4.zip)
[tempo demo.mscz.zip](https://github.com/musescore/MuseScore/files/10405383/tempo.demo.mscz.zip)
[tempo_initialization.mp4.zip](https://github.com/musescore/MuseScore/files/10405384/tempo_initialization.mp4.zip)

**Comment by cmaxreilly** [comment]
Yes, that would seem to be the overarching issue!

**Comment by zacjansheski** [comment]
Combining with https://github.com/musescore/MuseScore/issues/14678
