### ISSUE TITLE
[MU4 Issue] Instance-specific crash when closing a score containing a missing instance of Kontakt

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#15853]
**Describe the bug**
See demo video (My apologies, it's pretty boring): 
https://www.dropbox.com/s/3g3r2n8zd0jgka1/Screen%20Recording%202023-01-13%20at%2012.46.45%20pm.mov?dl=0

This is the score I was able to reproduce the issue with: 
[Uploading The_Griggles (2).mscz.zip…](Original file containing Kontakt instance)

In short:

- Open the above score
- Wait for audio samples to load
- See message stating that an instance of Kontakt couldn't be loaded
- Press Cmd+W
- This instance of MuseScore crashes (At least 3-4 times). Other instances remain open and unaffected

Then

- Re-open this file
- Wait for audio samples to load
- Replace Kontakt instrument with something else (I used MuseSounds grand piano)
- Press Cmd+W
- Save dialog is triggered. Press Save
- Instance crashes
- Re-open instance, and close it again. No more crashes.

**Platform information**
 - OS: macOS 12.6 (M1)

@Tantacrul FYI

**Comment by DmitryArefiev** [comment]
Fixed in #16306

**Comment by DmitryArefiev** [comment]
Retested on Mac12.6
