### ISSUE TITLE
[MU4 Issue] App crashes and doesn't ask to save when quitting via dock (MacOs)

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#15852]
**Describe the bug**
The app crashes and doesn't show save as dialog when quitting the app via the dock (macos)

**To Reproduce**
1. Open a score
2. Make a change 
3. Quit app via right click, then Quit on app icon on dock

**Expected behavior**
Should ask to save before quitting.

**Screenshots**

https://user-images.githubusercontent.com/71656189/212312557-c08bfe2a-ff79-407f-a176-17f296332bfd.mov

**Platform information**
 - OS: MacOS

**Comment by cbjeukendrup** [comment]
This seems a good patch release 2 candidate to me

**Comment by DmitryArefiev** [comment]
Retested on Mac12.6
