### ISSUE TITLE
[MU4 Issue] Measure selecting is extended to the next measure after Undo ending adding

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#15851]
**Describe the bug**
Can't be reproduced with all notation elements but reproducible with barlines and clefs

**To Reproduce**
1. Open any score
2. select a measure and add any element (e.g. ending)
3. Undo (pay attention that selection frame is extended to the right)
4. Add repeat barline
5. Pay attention to the repeat barline also in the next measure

**Expected behavior**
Selection frame isn't extended to the right and any extra elements are not added after undo

**Screenshots**

https://user-images.githubusercontent.com/101250347/212309951-2b53390e-2895-44f9-9b2d-2e2438b105b2.mp4

https://user-images.githubusercontent.com/101250347/212309973-35a87ad8-f196-40a5-bc46-d6b766351374.mp4

**Platform information**
 - OS: macOS

**Comment by zacjansheski** [comment]
I will close this so we can refer to https://github.com/musescore/MuseScore/issues/17718 (more details there)
