### ISSUE TITLE
[MU4 Issue] Save to cloud should check for corruption before attempting to upload (and refuse in case of corruption)

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#15857]
**Describe the bug**
Save to cloud should check for corruption before attempting to upload (and refuse in case of corruption)

**To Reproduce**
1. Take a corrupt score (one that Mu4 reports as corrupted, the forum is full of them).
2. Save it online.
3. It does get saved, sort of.
4. But once finished on musescore.com, there an error gets reported:
```
Oops! Score download has stopped due to an unexpected error. Please try again.
If the error occurs, please contact our Support Team.
Thank you for understanding!
```

**Expected behavior**
Check for corruption priod to attempt to upload, and don't upload if it is corrupt.
MuseScore 3 (and 2) behaved like that.
Becomes more important with Mu4 because of the lengthy MP3 generation, resp. the time that gets wasted with that.

**Platform information**
 - OS: Window (but I don't think other platforms behave differently here).

**Additional context**
Came up in https://musescore.org/en/node/341658

**Comment by Tantacrul** [comment]
Definite Patch Release fix. Adding @shoogle and @bkunda to work out the specifics.

**Comment by Jojo-Schmitz** [comment]
Esp. in connection with #15226 and its fix

**Comment by Jojo-Schmitz** [comment]
Seems to have missed 4.0.1?

**Comment by shoogle** [comment]
There will be at least one more patch release before 4.1, so no need to delay the important fixes in 4.0.1 waiting for this one, which requires design work as well as development work.

**Comment by Tantacrul** [comment]
Yes, I added it to 4.0.2.

There are a few more things we want to fix, but it will take a little more time. Patch 4.0.1 is mainly to fix the worst corruption and crash problems. We didn't want to delay that and were already doing final testing on it yesterday.

**Comment by Jojo-Schmitz** [comment]
Ok, understood, thanks

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/16042
