### ISSUE TITLE
[MU4 feature request and/or bug report]: Batch convert jobs don't work.

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#15864]
**Describe the bug**
MuseScore 4.0.0 doesn't recognize the `-j` argument, so batch convert jobs (one of my favorite features) no longer work.

**To Reproduce**
1. Try to run something like `"C:\Program Files\MuseScore 4\bin\MuseScore4.exe" -j convert_job.json`

**Expected behavior**
What MuseScore 3 did: Read the JSON file (with its various input and output files), and convert accordingly.

**Actual behavior**
`Unexpected token '-j' in expression or statement.`

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/87204246/212401559-7338313b-0d95-4f77-b466-aa0cfafdd166.png)

**Platform information**
 - OS: Windows

**Additional context**
If this is fixed in 4.0.1, I wouldn't know... I haven't updated yet.

**Comment by cbjeukendrup** [comment]
Strange... that doesn't really look like a MuseScore error but rather a PowerShell (or whatever) error... In principle the feature does work; we use it daily in our CI for the Visual Tests (to convert scores to images and compare those images)

**Comment by ThePython10110** [comment]
I tried the same command in CMD, but it just silently fails. 
If I replace `MuseScore 4` with `MuseScore 3`, it works fine.
What do you mean "in principle?" Do you mean that image conversion works, or that batch conversions work?

**Comment by cbjeukendrup** [comment]
Ah. Yeah, I guessed it must be something like that; this really seems a non-MuseScore issue. And if you get the same with MS3, I think we can close this. 

(You could try running the command in Git Bash, if you have that installed; that should work.)
