### ISSUE TITLE
Instrument and staff hiding GUI don't make sense

### ISSUE THREAD

**Issue by gtbot2007** [musescore/MuseScore#15868]
When hiding an instrument, it mutes the instrument. The thing is when you hide a staff it doesn't mute the staff. This makes sense because you want to be able to hear the staff and not see it. But since they do different things, why is one hidden under the other? Why would I think to look under a setting that hides _and_ mutes for a drop down to only hide and not mute?

My idea would be to move the hide and not mute options to the staff/parts menu, and just link to the staff/parts menu in the gear that's already in the instruments panel.

**Comment by gtbot2007** [comment]
slightly relates to #10951 but only sorta

**Comment by GabeS573** [comment]
There could also be a "Hide and Mute" option (i.e. the current functionality) in the gear menu, with **all** of the "eye" buttons used to only visually hide instruments, whether it's a part or a staff.

**Comment by cbjeukendrup** [comment]
The Instruments panel itself certainly makes sense. It follows the natural hierarchy of instruments and staves:
```
├ Flute
│  └ The first (and only) staff of the Flute
├ Trombone
│  └ The first (and only) staff of the Trombone
└ Piano
   ├ The first staff of the Piano
   └ The second staff of the Piano
```
Those options that you mention are not "Hide and mute" and "Hide and not mute"; they are "Hide the whole instrument" and "Hide this staff only". 

Which effect these options have on playback ("to mute or not to mute"), is a question not related to the Instruments panel. That's rather something for the Mixer. How that should work, is currently being discussed in https://github.com/musescore/MuseScore/issues/10951, so I think this issue can be closed, unless @Tantacrul wants to add something.

**Comment by gtbot2007** [comment]
Its not about what they do per se, but instead about that if they do different things (like they do now) then they should not be in the same menu unless the menu gets a lot more clear about how they do different things (so that its clear for new users why hiding all the staffs of an instrument is different then hiding the instrument)

**Comment by cbjeukendrup** [comment]
Hm. I would expect that it is relatively clear because the button relating to the whole instrument is in the row for the instrument, and the buttons for staves are in the "subrows" for the staves. So once users get the hierarchy, it should be quite clear. But maybe users don't understand the hierarchy immediately, is that the problem maybe?

**Comment by GabeS573** [comment]
@cbjeukendrup It's not that the visual hierarchy is confusing; the ui is pretty clear as far as show/hide goes. The confusing part is that hiding an instrument also mutes it, but hiding an individual staff does not. This is being debated in a separate issue already.

**Comment by GabeS573** [comment]
In any vase, this is essentially a duplicate of #10951
