### ISSUE TITLE
[MU4 Task] Fix Deprecated wiki page on Musescore Code Structure

### ISSUE THREAD

**Issue by cmaxreilly** [musescore/MuseScore#15869]
In the Packages section of README.md in the root directory for the application, there is a single link to the wiki page on [Code Structure](https://github.com/musescore/MuseScore/wiki/CodeStructure). This page is deprecated, and needs to be updated to reflect the last two years of development. Rewrite this page so that there is an entry for all directories in the root with a brief description of what each directory does.

**Comment by cmaxreilly** [comment]
Wiki page has been updated.

**Comment by cbjeukendrup** [comment]
Thanks!
