### ISSUE TITLE
[MU4 Task] feature: remember window position and size on macOS

### ISSUE THREAD

**Issue by foss-** [musescore/MuseScore#15862]
macOS 13.1
MuseScore 4.0.1

**Currently**

MuseScore opend with maxed window size. On a 43" monitor that is not ideal.

**Expected**

Generally it would be nice if MuscScore remembered its window size and position and would resume with those after closing and re-opening the program.

**Comment by cbjeukendrup** [comment]
Duplicate of #10699. Thanks for reporting though!
