### ISSUE TITLE
[MU4 Issue] Printing scores prints square the number of requested copies

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#15861]
**Describe the bug**
Printing scores prints square the number of requested copies

**To Reproduce**
1. File > Print
2. Select number of copies: 2, 3 or 4
3. Print
4. Get 4, 9 or 16 copies printed, respectivly

**Expected behavior**
Well, oviously getting the exact number of requested copies...

**Platform information**
 - OS: Windows

**Additional context**
Came up in https://musescore.org/en/node/341823 and again in https://musescore.org/en/node/342447

**Comment by DmitryArefiev** [comment]
Retested on Win10 (with physical printer)
