### ISSUE TITLE
[MU4 Task] Provide a PortableApp version

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#15876]
**Task description**
Plesase also provide a PortableApp version.

See https://portableapps.com/node/67638, which proves that this is possible

**Comment by cbjeukendrup** [comment]
Is it right that the only remaining step is to publish the Portable builds on the OSUOSL server, and then on the MuseScore.org website?

**Comment by Jojo-Schmitz** [comment]
No idea, does it get build, but just not uploaded?
For PRs it doesn't get build.

Looking at https://github.com/musescore/MuseScore/actions/runs/5460642511 it seems the nightlies don't build it either

**Comment by Jojo-Schmitz** [comment]
It is actually not a feature, but a Mu3 regression...

Is your #18423 supposed to fix this?

**Comment by Jojo-Schmitz** [comment]
The Beta(s) did provide a PortableApp, what was different there?

**Comment by cbjeukendrup** [comment]
PortableApps are built for releases and pre-release builds, and uploaded to GitHub artifacts. 
In https://github.com/musescore/MuseScore/pull/18423, they will be uploaded to OSUOSL too, so that people have a way to download them without a GitHub account. 

Do we also want nightlies as PortableApps? I thought that since the nightly builds are not "installable" anyway, the benefit of having portable builds in addition to that might be limited.

**Comment by Jojo-Schmitz** [comment]
Well maybe we'd even want portable apps only. They are similar to appimages

**Comment by shoogle** [comment]
We could use the portable build as the regular nightly, the advantage being that users wouldn't have to install 7-zip in order to use them.

**Comment by Jojo-Schmitz** [comment]
Exactly.

**Comment by cbjeukendrup** [comment]
In #18448 I've added Portable nightly builds in addition to the existing nightly builds. The last step would be to advertise the Portable version somewhere on the MuseScore.org download page.

**Comment by Jojo-Schmitz** [comment]
Seems it hasn't happened yet? Not for releases atz least?

**Comment by cbjeukendrup** [comment]
I'll reopen the issue, hoping that someone will upload the builds this time. I don't know how the 4.1.1 build got there, I didn't upload it.

**Comment by Jojo-Schmitz** [comment]
The GitHub page for 4.2.0 Beta (https://github.com/musescore/MuseScore/releases/tag/v4.2.0-beta) is lacking the PortableApp

**Comment by Jojo-Schmitz** [comment]
And the new ARM version is missing there too

**Comment by cbjeukendrup** [comment]
@shoogle I'll assign this task to you now, since the only remaining step is to somehow mention the experimental builds on the Downloads page on .org, and that's something only you can do :)

**Comment by Jojo-Schmitz** [comment]
Shouldn't this be fixed meanwhile? Or do we want to check whether it is when 4.3 gets released?

**Comment by Jojo-Schmitz** [comment]
I believe this can get closed

**Comment by Jojo-Schmitz** [comment]
I believe this can get closed

**Comment by cbjeukendrup** [comment]
Well the portable build is _still_ not displayed at https://musescore.org/nl/download, but it doesn't look like having this issue open is going to help making that happen, so I'm happy to have it closed and will send Peter a reminder at release time :)
