### ISSUE TITLE
[MU4 Task] Remove 'Feedback' option from menu

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#15873]
**Task description**
This feedback form does not correspond to any data I've seen and I'm almost sure it is no longer being looked at by anyone at Muse. It came before my time. Also feels a little amateurish in its execution too. Let's destroy it.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/21022311/212467447-e8a4b7fb-142c-49a2-a525-b5f738fcd666.png">

Perhaps @HemantAntony, if you are interested ?

**Comment by HemantAntony** [comment]
Definitely! I love destroying things

**Comment by Jojo-Schmitz** [comment]
Been a wrecking ball in a previous life? ;-)

**Comment by HemantAntony** [comment]
Still am :)

**Comment by DmitryArefiev** [comment]
Retested on Win10
