### ISSUE TITLE
[MU4 Issue] Pasting text in a lyrics field always pastes: "<font"

### ISSUE THREAD

**Issue by PetJer** [musescore/MuseScore#15889]
**Describe the bug**
After copying any text inside Musescore (e. g. title, subtitle, lyrics ...) and pasting it in a lyrics field always pastes: "<font". (Pasting text that's not in the app will work normally!)

**To Reproduce**
1. Copy some text in Musescore.
![paste-in-lyrics-1](https://user-images.githubusercontent.com/79419198/212537602-07b07b01-5ca0-4249-801b-7a8436d0bc0f.PNG)

2. Paste it in a lyrics field $\to$ pastes "<font"
![paste-in-lyrics-2](https://user-images.githubusercontent.com/79419198/212537606-29ff9843-0e9f-412e-bfac-c25a9ba0050a.PNG)

**Expected behavior**
The copied text should be the same when pasting it in a lyrics field.

**Platform information**
 - OS: Windows 10

**Comment by PetJer** [comment]
It actually copied: **<font size="14"/><font face="Edwin"/>Subtitle**
And then took the first word.

**Comment by PetJer** [comment]
@cbjeukendrup I'll work on this.
Also do I need to ping someone specifically to assign me or can I just start doing it (So I can stop bothering you)?

**Comment by cbjeukendrup** [comment]
Oh wait. This might already be fixed as a (side) effect of https://github.com/musescore/MuseScore/pull/16242. It would be good to try that out before working on this yourself. 

It's fine if you ping me; assigning is useful to prevent that two people accidentally work on the same issue.

**Comment by zacjansheski** [comment]
Closing, no longer reproducible, likely fixed by https://github.com/musescore/MuseScore/pull/16242
