### ISSUE TITLE
[MU4 Issue] Playback UI, Tune UI, Appearance UI cannot be accessed at all

### ISSUE THREAD

**Issue by Apprisco** [musescore/MuseScore#15884]
**Describe the bug**
Playback UI, Tune UI, Appearance UI cannot be accessed at all

**To Reproduce**
Install Musescore 4.0.1 on Windows 11, latest version
Watch video for steps.

https://user-images.githubusercontent.com/34324909/212523709-beac8221-5a36-4b32-85ac-b1e4c5ccc442.mp4

**Expected behavior**
Be able to change the values in the playback UI without the UI closing on itself.

**Platform information**
 - OS: Windows 11
 - Processor: 5950x, 64GB 3600mhz cl14 memory, RTX 3090 FTW3 Ultra

**Additional context**
Doesn't happen on every system, but has happened to at least five people I've talked to in real life. Please let me know if there are any logs or anything I can send to help fix this issue. This is the only issue I have left that needs resolving before I can use Musescore 4, asides from the absolutely terrible audio crackling during export issue.
It seems that at the end of the video, the new score tab wasn't captured- however, rest assured that it's not a score problem as when I created a new score, the exact same issue happened.

**Comment by zacjansheski** [comment]
I cannot reproduce this, Windows 11 version 4.1.1
May we close?
