### ISSUE TITLE
[MU4 Issue] When MuseScore is enlarged, the window is larger than the screen, causing a white band on the second screen.

### ISSUE THREAD

**Issue by cy-polo** [musescore/MuseScore#15886]
**Describe the bug**
MuseScore when enlarged, takes up more space and sticks out on my second screen, making a small white band.

**To Reproduce**

1. Have 2 screens minimum (dual screen)
2. Open MuseScore
3. Put MuseScore in full screen
4. You can see the white band on the right

**Expected behavior**
I wish MuseScore wouldn't come out of my screen.

**Screenshot**
![image](https://user-images.githubusercontent.com/50364607/212529155-73432a1e-8bb8-45b1-b2f4-04d47687a39b.png)

**Platform information**
 - OS: Windows 10 (64 bits)

**Comment by GabeS573** [comment]
I wonder if this is similar to https://github.com/musescore/MuseScore/issues/14624?

**Comment by zacjansheski** [comment]
This could be Windows 10 specific.  Could you confirm it is still actual in 4.1.1?

**Comment by cy-polo** [comment]
@zacjansheskithis I can confirm you that this issue is now fixed in the 4.1.1 version.
