### ISSUE TITLE
How do we aggregate issues specific to MS3 => MS4 Upgrades ?

### ISSUE THREAD

**Issue by jjdonson** [musescore/MuseScore#15887]
## Goal: Streamline Upgrade Paths To MS4 For MS3 Users
- The immediate goal is to facilitate MS4 as the current stable version, proven via file testing.
  - The larger challenge is to track every MS4 feature in terms of how it may adversely impact MS3 files.
  - It is often premature to market MS4 awesome features that may create problems for legacy MS3 user files.
  - By preventing or minimizing inevitable legacy file upgrade support issues, 4.x training and promo are paved roads.
---
### Musescore Versions In 2023, Q1:
- [Emerging Stable Version: 4.x](https://github.com/musescore/MuseScore/releases/latest)
- [Current Stable Version: 3.6.2](https://github.com/musescore/MuseScore/releases/tag/v3.6.2)
- Legacy Stable Version: --
---
### MS3 User Testing: Targeting Most Common Use-Cases

- All MS3 users have MS3 skills that must adapt to the new user interface, tools and key commands.

- Most MS3 users have MS3 Files that must run right in MS4, or they will wait.
  - The 2022 install base of MS3 users around the world represents massive investments of time in MS3 files.  In order to pave the road for MS3 users to smoothly transition to MS4.x, careful testing of MS3 files in MS4 is required.  

- Many MS3 users have MS3 PlugIns that must run right in MS4, or they will wait.

- Many MS3 users have MS3 DAWs that must run right in MS4, or they will wait.

- _Someone from the dev team ought to review the list above and advise._
---
#### The proposed issue tags below correspond to the use-cases above...
- We would benefit from either tags or projects for the following:

  - UPGRADE TRAINING

  - UPGRADE TEST FILES
    - [ONE Example Set of MusicXML Files](https://www.musicxml.com/music-in-musicxml/example-set/)

  - UPGRADE PLUGIN TESTS

  - UPGRADE DAW TESTS

- Our custom issue labels are listed here:  https://github.com/musescore/MuseScore/labels

---
- [A support page for 3to4 Upgrade Info](https://musescore.org/en/handbook/4/upgrade-musescore-3x)
  - This might be split into:
    - GENERAL UPGRADE SUPPORT
      - OSX-only
      - WINDOWS-only
      - LINUX-only

- [An example of upgrade info on the wiki](https://github.com/musescore/MuseScore/wiki/Style-Parameter-changes-between-3.6-and-4.0)

---

**Comment by chenlung** [comment]
Just wanted to suggest another solution (not replacing the ones mentioned here): issue a 3.7 version (and a handful of patch releases where necessary).

This has some advantages:
-Fixes to issues and improvements (the release was arguably rushed at the time).
-Implementation of provisions to make the upgrade from Series 3 to 4 smoother.

**Comment by Jojo-Schmitz** [comment]
My PR #9000 is still there on standby...

**Comment by jeetee** [comment]
Re; Implementation of provisions to make the upgrade from Series 3 to 4 smoother.

The architectural changes are too big to make any meaningful addition to a 3.x in preparation of 4.x things. That time imho is way better invested in discovering which things break during import and improving the old scores import code of 4.x instead.

**Comment by arnaudlecam** [comment]
Hi,
I'm on Archlinux, and my sytem upgraded to MS4 at 2023-01-01T09:56:13+0100.
Therefore, I stopped working on music : I worked on trying to open my MS3's files and to adapt my scripts (dealing with bash, using old "musescore -j" to generate excerpt's PDF....).
I searched a long time, trying to understand new folders structure, style modifications/deletions, etc. I never found any documentation, and mscore -d didn't help me.
Today, I'm tired, and I downgrade to MS3...
MS4 looks fine, but I realy don't understand how "simple users" can test it.
So, I think it would be nice to get help on MS3->MS4 migration....
I hope it will be done, and perhaps I could contribute.

**Comment by MarcSabatella** [comment]
As mentioned, you shouldn't need to do anything special to "migrate" - just open your MuseScore 3 file in MuseScore 4 and it opens normally, but looking and sounding better.  If you continue to have trouble, best to ask for help on the Support forum and describe which file you tried to open, how you tried to open it, and what went wrong when you tried.  Then people can understand and assist.

**Comment by arnaudlecam** [comment]
Ok, i will. Thank you for your efforts.
