### ISSUE TITLE
[MU4 Issue] Lyrics elision shortcut not working

### ISSUE THREAD

**Issue by eg0n1984** [musescore/MuseScore#15890]
If we try to insert an elision in the lyrics, in the MS4 version it is not inserted. It's required copy from MS 3.6

**To Reproduce**
1. Create a bar 4/4
2. Add 4 quarter note
3. Ctrl+L to insert lyrics
4. Text 'Test'+ (Ctrl+Alt+\_) and see that no '\_' is added to the text

**Expected behavior**
Choral pieces sometimes requires elision in some words, it's expected use same command then in MS3.6

**Screenshots**
MS4:
![imagem](https://user-images.githubusercontent.com/28876087/212539570-e9c476f1-6bd5-4e9d-914c-2941e0d15c83.png)

MS3.6
![imagem](https://user-images.githubusercontent.com/28876087/212539583-b36e046d-e5de-447c-a5b4-7c4fd4ac5eb3.png)

**Platform information**
 - OS: OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Comment by PetJer** [comment]
It seems there's no shortcut for an elision in MS4 (yet?).
![elision](https://user-images.githubusercontent.com/79419198/212541860-4f9dee68-09d7-4a19-b144-b5dd4f9eae77.PNG)
You'll need to do it like the MS4 handbook says: https://musescore.org/en/handbook/4/lyrics#elision-slur

**Comment by eg0n1984** [comment]
Thanks @PetJer 
But the Ctrl+Alt+- shortcut works, only appears with wrong character
https://musescore.org/en/handbook/4/entering-and-editing-text#special-characters

**Comment by arnaubt** [comment]
I'm encountering the same issue. Using the underscore prints a forward-slash character (/).

**Comment by Jojo-Schmitz** [comment]
This isn't done via a 'programmable' shortcut, but hard coded into the text editing:
```cpp
        if (ctrlPressed && altPressed) {
            if (ed.key == Key_Minus) {
                insertSym(ed, SymId::lyricsElision);
                return true;
            }
        }
```

**Comment by zacjansheski** [comment]
The Mac OS equivalent of this shortcut works.  Perhaps this is something the community can get working on Windows?

**Comment by Jojo-Schmitz** [comment]
No idea whether this has any unwanted side effects though, nor whether it work on non-German keyboards.

**Comment by Jojo-Schmitz** [comment]
Testers of the #19018 artifacts wanted
