### ISSUE TITLE
[MU4 Issue] Update so that spanning chord/stem across staves works without the invisible method 

### ISSUE THREAD

**Issue by IndexLibrarian** [musescore/MuseScore#15908]
**Describe the bug**
Im struggling to extend the chord through 2 staves without hiding notes 

**Screenshots**
![Screenshot 2023-01-16 173227](https://user-images.githubusercontent.com/89202731/212657487-2b7ec408-e904-41cb-af7f-8a95125eb3cc.png)
I'm trying to replicate this but even if I hide the notes the playback doesn't sound right
**Platform information**
 - OS: Windows 11

**Comment by oktophonie** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/15544
