### ISSUE TITLE
[MU4 Issue] Extended Helmholtz-Ellis SMuFL accidentals not imported correctly from MusicXML 4 files

### ISSUE THREAD

**Issue by s-socha** [musescore/MuseScore#15903]
**Describe the bug**
MuseScore 4 does not import Extended Helmholtz-Ellis SMuFL accidentals from musicXML 4 files.

**To Reproduce**
Steps to reproduce the behaviour:
Open the attached musicXML file in MuseScore.

**Expected behaviour**
Pitches 2-12 in the sequence should contain the SMuFL accidentals defined in the attached musicXML file. The accidentals are (respectively):

accidentalFlatThreeArrowsUp
accidentalFlatOneArrowUp
accidentalFlatTwoArrowsUp
accidentalNaturalTwoArrowsUp
accidentalSharpTwoArrowsUp
accidentalSharpTwoArrowsUp
accidentalNaturalThreeArrowsDown
accidentalSharpTwoArrowsDown
accidentalNaturalTwoArrowsDown
accidentalFlatThreeArrowsDown
accidentalNaturalThreeArrowsUp

**Platform information**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223472200, revision: github-musescore-musescore-5485621

[musicXML_file.zip](https://github.com/musescore/MuseScore/files/10421256/musicXML_file.zip)
[MuseScore_file.zip](https://github.com/musescore/MuseScore/files/10421257/MuseScore_file.zip)

**Comment by Jojo-Schmitz** [comment]
See also https://github.com/w3c/musicxml/issues/482

**Comment by Jojo-Schmitz** [comment]
Not a plain Mu4 issue, Mu3 is affected too

**Comment by Jojo-Schmitz** [comment]
As per https://github.com/w3c/musicxml/issues/482#issuecomment-1384496150 indeed not (yet) implemented in the importer
