### ISSUE TITLE
[MU4 Issue] The same keyboard shortcut is used for 2 different actions

### ISSUE THREAD

**Issue by vsvyatski** [musescore/MuseScore#15900]
**Describe the bug**
I accidently noticed that the keyboard shortcut "+", that was used in MS 3.x for adding ties is still used in MS 4 for the same action, but the problem is that in MS 4 it's also set for toggling sharps on notes. You cannot set the same keyboard shortcut for 2 different actions in the same context, it doesn't work like that. The application like gets "confused", so it executes the last action of the two, the shortcut was assigned to by the developers. In this particular case I can no longer use "+" for adding ties, it just activates a sharp.

**To Reproduce**
1. Open any score in MuseScore so you can see the toolbar.
2. Move your cursor over the "Toggle Sharp" button. In the tooltip that appears you'll see the the keyboard shortcut for this action is "+".
3. Now move you cursor over the "Tie" button. In the tooltip you'll see that the keyboard shortcut is the same: "+".

**Expected behavior**
I expect to see 2 different keyboard shortcuts for those 2 different actions. If you believe that "+" is good for toggling sharps (I don't mind) then please change the keyboard shortcut for ties to something different (like shift plus, maybe, control plus is already occupied by zooming in). Right now I have to use only the toolbar button to add ties, that's not quite convenient. And the MS4 user interface provides incorrect information.

**Screenshots**
|![image](https://user-images.githubusercontent.com/11542782/212565899-e4dafdea-715a-4aa2-bafb-64d294febe1f.png)|![image](https://user-images.githubusercontent.com/11542782/212565947-fde6d680-130e-47b9-b037-0e5609592b32.png)|

**Platform information**
 - OS: Windows 10 22H2 64 bit
 - MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Comment by henkdegroot** [comment]
![ms4-shortcut](https://user-images.githubusercontent.com/13550012/212614185-79071931-49d4-4a44-94bf-dde851ac7adb.png)

This should not be the case. Looks like you may have some config/settings files being mixed up. Please use the Revert to Factory Settings (available in the help menu) to resolve this.

**Comment by vsvyatski** [comment]
It helped, thanks. I had alpha and beta versions of MS 4 installed in the past. I never have actually reset the setting files after uninstalling those. I guess this is how they got mixed up.

**Comment by Jojo-Schmitz** [comment]
Brings up an interesting issue: SHouzldn't a new install be able to revert to factory settings? 
Maybe the Installer could ask for this, and whether it is on by default or not gets decided when we know about an incompatible change, like recently the shortcuts one?
