### ISSUE TITLE
[MU4 Issue] Zip encoding of MSCZ file doesn't apply compression.

### ISSUE THREAD

**Issue by David-Keeffe** [musescore/MuseScore#15902]
**Describe the bug**
The MSCZ files from MuseScore 4 don't apply any compression: the contents are all reported as "stored". MS3 uses Flate (Deflate) compression. The consequence is that the uncompressed MSCX component takes a lot of space and the saving of the final file is slow, probably due to the volume of data being written to disk.

**To Reproduce**
Save any file.

**Expected behavior**
An MSCZ file with one of the standar Zip compression technologies applied.

**Screenshots**
Zip report for MS4:
```
% unzip -v Saint_Louis_Blues_March__Glenn_Miller_-_Brass_Quintet.mscz
Archive:  Saint_Louis_Blues_March__Glenn_Miller_-_Brass_Quintet.mscz
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
   65938  Stored    65938   0% 01-14-2023 08:30 731a8c67  score_style.mss
 6092368  Stored  6092368   0% 01-14-2023 08:30 8df900ca  Saint_Louis_Blues_March__Glenn_Miller_-_Brass_Quintet.mscx
   65937  Stored    65937   0% 01-14-2023 08:30 c613e4af  Excerpts/B�?� Trumpet 1.mss
  263208  Stored   263208   0% 01-14-2023 08:30 d8f7cb23  Excerpts/B�?� Trumpet 1.mscx
   65937  Stored    65937   0% 01-14-2023 08:30 c613e4af  Excerpts/B�?� Trumpet 2.mss
```
Zip report for MS3:
```% unzip -v Mas_Que_Nada_-_Jorge_Ben_Jor_-_Brass_Quintet.mscz
Archive:  Mas_Que_Nada_-_Jorge_Ben_Jor_-_Brass_Quintet.mscz
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     186  Defl:N      136  27% 04-14-2021 10:51 0c21a057  META-INF/container.xml
 5177983  Defl:N   110609  98% 04-14-2021 10:51 3230bf1b  score-4e4f22ff7f52ef6780b0ed4152366b1e.mscx
   26624  Defl:N    25584   4% 04-14-2021 10:51 f878bfea  Thumbnails/thumbnail.png

```

**Platform information**
MacOS 11.7

**Comment by krtschil** [comment]
On Linux this seems to be ok:
Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
   66243  Defl:N    10028  85% 2022-12-06 14:19 f03a2f70  score_style.mss
  135668  Defl:N     5079  96% 2022-12-06 14:19 872ab9b3  Inner_Light_(Piano).mscx
   28264  Defl:N    27378   3% 2022-12-06 14:19 fb6ffb6a  Thumbnails/thumbnail.png
    3088  Defl:N      502  84% 2022-12-06 14:19 b9219c2e  audiosettings.json
      55  Defl:N       45  18% 2022-12-06 14:19 93e5d13e  viewsettings.json
     340  Defl:N      167  51% 2022-12-06 14:19 7a1b43e4  META-INF/container.xml
--------          -------  ---                            -------
  233658            43199  82%                            6 files

**Comment by David-Keeffe** [comment]
I just installed 4.0.1 on my Mac and the non-compression issue seems to have been resolved.

**Comment by Jojo-Schmitz** [comment]
Strange enough nothing to that extent has been changed

**Comment by cbjeukendrup** [comment]
Is there still any problem here, or can we close this issue?

**Comment by zacjansheski** [comment]
Closing
