### ISSUE TITLE
Include lyrics when exporting MIDI files

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#15925]
**Task description**
At present, MuseScore exports type 1 MIDI files with note information separated into tracks, but contain no lyrics. As this is a clean interchange format between various software, and to aid further processing by virtual singer software or karaoke machines, it would be very useful if MuseScore could also export the lyrics as MIDI meta events in each track to go with the notes.

**Comment by Jojo-Schmitz** [comment]
Long time feature request, see https://musescore.org/en/node/6639 and https://musescore.org/en/node/337515

**Comment by jeetee** [comment]
For reference the MIDI file specification at https://midi.org/standard-midi-files also contains an addendum for "*recommended practice (RP) defining a common implementation for the use of Lyric Meta Events within a Standard MIDI File*" which should be helpful to anyone wishing to tackle this.
