### ISSUE TITLE
[MU4 Issue] Export to PDF of a multi-page score in "continuous view" creates just one (long/wide) page

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#15928]
**Describe the bug**
Export to PDF of a score in "continuuos view" creates just one (long/wide) page rather than (temporarily) switching to page view, like Mu3 did/does

**To Reproduce**
1. Open any milti page score
2. Switch to Continuous view (vertical/horizontal)
3. Export to PDF
4. Open the PDF in a PDF viewer

**Expected behavior**
Temporarily switch to page view, like Mu3 did/does

**Platform information**
 - OS: Windows, but I doubt that this makes a difference

**Additional context**
Came up in https://musescore.org/en/node/342743#comment-1166977

This behavoir may lead to parts of the score not getting exported at all, as the max. height and width of a PDF is limited (to 200" x 200" as far as I can tell)

**Comment by GabeS573** [comment]
Possible duplicate of https://github.com/musescore/MuseScore/issues/14929?
