### ISSUE TITLE
[MU4 Issue] Keyboard shortcuts conflicting or not working (MacOS)

### ISSUE THREAD

**Issue by marchfra** [musescore/MuseScore#15934]
Keyboard shortcuts are not working as intended: for example, the augmentation dot (.) shortcut simply doesn't work, and some shortcuts like (Cmd + B) should toggle Bold when in text edit mode and add a bar at the end of  the score otherwise, but adds a bar regardless.

1. Open new score, e.g. from the treble clef template
2. Add a quarter note (or any other duration)
3. Press (.) and nothing happens
4. Add text
5. Press (Cmd + B) to toggle Bold, a bar is added at the end

- OS: macOS 12.6, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

I haven't checked out more shortcuts because these two alone make it impossible for me to use MuseScore 4, but if anyone finds more please add a comment below to help developers!

**Comment by Fabien-B** [comment]
Same thing for me on linux, via the AppImage.
Being unable to type dotted notes make it impossible to use.

OS: Ubuntu 20.04.5 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Comment by zacjansheski** [comment]
Currently Bold and dot toggle shortcuts are working on Mac OS
We have a few other issues open for shortcut issues and will refer to those moving forward.
https://github.com/musescore/MuseScore/issues/15156
https://github.com/musescore/MuseScore/issues/14496
