### ISSUE TITLE
[MU4 Issue] Crash when notes above/below the staff are set to invisible

### ISSUE THREAD

**Issue by moogly81** [musescore/MuseScore#15932]
**Describe the bug**
When a notes above/below the staff is set to invisible, musescore crashes instantly. 
It happens when a note requires additional lines. 
  - treble clef : low c and below, high a and above
  - bass clef : low e and below, "high" c and above

**To Reproduce**
1. New score (ie treble clef template, but works with anything)
2. input a low c
3. set it to invisible by selecting the notehead and untick the **visible** checkbox in **properties** --> **general**
4. CRASH

**Expected behavior**
No crash :)

**Platform information**
 - OS: [macOS]
 - musescore 4.0.1

**Additional context**
Specially vicious when using the "toggle rhythmic slashes" option, since notes are below the staff

**Workaround** 
- change note pitch  to bring the note inside the staff
- set to invisible
- change pitch back

**Workaround 2**
  - press v. It toggles the visibility successfully

**Comment by moogly81** [comment]
Is like  #15355, but more precise.

**Comment by oktophonie** [comment]
Couldn't reproduce this myself, but this visibility crash seems to be a very sneaky issue that manifests some times and not others.

**Comment by MarcSabatella** [comment]
I can't reproduce either, but if you have a specific score that does this reliably, please ZIP and attach it and tell us which note specifically is crashing for you.

**Comment by moogly81** [comment]
I tried on another computer (mac), with a fresh musescore 4.0.1 install. Everything as default (on mac)
The score is literally the treble clef template, with a low c whole note on measure 1. When I set the low C to invisible, musescore crashes every time.

**Comment by moogly81** [comment]
my logs : 
```
21:39:09.461 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: put-note
[30387:764583:20230117,213919.943128:WARNING crash_report_exception_handler.cc:240] UniversalExceptionRaise: (os/kern) failure (5)
[1]    30385 segmentation fault  mscore --debug
```

**Comment by moogly81** [comment]
If that's any help, here my "score" 
[crash-when-set-to-invisible.mscz.zip](https://github.com/musescore/MuseScore/files/10439252/crash-when-set-to-invisible.mscz.zip)

**Comment by MarcSabatella** [comment]
Aha, thanks for the additional info - now I *can* get this score to crash, using the following steps:

1. new score, treble staff
2. enter a whole note middle C into the first measure
3. select the *entire measure* (not just the note)
4. uncheck "Visible" in the Properties panel

So far I can only get it to crash if the note is the first note of the piece.  I suspect it relates somehow to the system header also being present in the measure.

**Comment by moogly81** [comment]
Thanks for your answer ! I do get this crash by selecting only one the note, I don't need the whole measure selected. And any note in the score causes this crash. Initially I experimented this a lot on a large score, but it's been corrupted, so I started from scratch.

**Comment by MarcSabatella** [comment]
Interesting.  Well, that's the only way I was able to get it to crash, but maybe it was a fluke.

**Comment by DmitryArefiev** [comment]
Retested on Win10/Mac12
