### ISSUE TITLE
[MU4 Issue] Double bass harmonics missing.

### ISSUE THREAD

**Issue by macaquedev** [musescore/MuseScore#15941]
Please could you add double bass harmonics to MuseScore? Arguably the double bass is the instrument on which harmonics are the most useful in orchestral writing, and having harmonics on all the other string APART from the double bass seems like a bit of a waste.

**Comment by s11141827** [comment]
Solo Double Bass instrument would be another good one. I have the Harmonics from C4 to F#5 so I've got more notes but now there's a gap range between C4 & G3 we need to fill by adding more notes

**Comment by Zephereth** [comment]
Just needed bass harmonics yesterday and they only sustain for a few seconds before cutting out, but they definitely are there.  I just worked around it by rearticulating a new note after a few measures.

**Comment by macaquedev** [comment]
yeah they do now exist (finally!!) but I can confirm that Ihhave also noticed @Zephereth's bug

**Comment by matthewreadbass** [comment]
I have opened a Muse Sounds ticket to fix this issue

**Comment by Zephereth** [comment]
This has been closed due to out previous conversation of them being added, or because the bug with the harmonics was fixed?
