### ISSUE TITLE
[Github issue] Mouseover popups on the "Issues" board have become persistent

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#15950]
**Describe the bug**

This is not a MuseScore issue but  something that has suddenly arisen over the past week or so on the Github Issues board. When you mouse over issue headings and user names, you should get a popup which closes when the mouse leaves the area. However the popups have become persistent over the past week and are both obscuring text and making it cumbersome to use the board. They only close when another mouseover popup opens.

**OS: [e.g. macOS, Windows, Linux]**

Linux Mint 20.1

**Comment by RobFog** [comment]
Do you think this is something the MuseScore folks can fix?

**Comment by cbjeukendrup** [comment]
It looks like GitHub bugs must be reported at https://github.com/community/community/discussions or https://support.github.com/contact/bug-report. But in any case not to us :)
