### ISSUE TITLE
[MU4 Issue] Muse-Hub using resources while doing nothing

### ISSUE THREAD

**Issue by krtschil** [musescore/MuseScore#15956]
**Describe the bug**
Running Muse-Hub is consuming resources:
- Running top while the app is open and doing nothing results in about 20-25% CPU load
- All sounds are downloaded (all have the respective check mark applied)

Is the observed CPU load normal or should it be lower (as I would expect)?

**To Reproduce**

1. Start muse-hub
2. Watch CPU load with top command
3. See 20-25% CPU load most of the time, sometimes dropping to about 7% and increasing again

**Expected behavior**
Constant low CPU load (at least after all checks for updates are done )

**Screenshots**
top:
![grafik](https://user-images.githubusercontent.com/7796440/213311295-f6a298a5-d08d-4a4c-93cb-33dc222f5aeb.png)

Messages in terminal:
![grafik](https://user-images.githubusercontent.com/7796440/213310984-0eadf98d-0445-4e8c-9708-a75d1cab04c3.png)

The cleanup messages repeat endlessly until muse-hub is stopped

**Platform information**
 - OS: Linux
 - Muse-Hub version 1.0.1.450

**Comment by oktophonie** [comment]
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.
