### ISSUE TITLE
[MU4 Issue] Notes that are copy pasted get tied together when tied with a third note.

### ISSUE THREAD

**Issue by vincenthage** [musescore/MuseScore#15953]
**Describe the bug**
Two bugs:
* When copy-pasting notes and applying slurs to the original notes, tying the original notes with other notes seems to also tied the copy-pasted notes.
* The copy-pasted notes don't seem to be tie-able at all.

**To Reproduce**
1. We start with three notes:
![image](https://user-images.githubusercontent.com/19684839/213299406-8cdacc8d-cce9-4347-bb4e-be33fcf5b1ce.png)

2. We copy paste the three notes to the next bar: 
![image](https://user-images.githubusercontent.com/19684839/213299523-c077631a-187e-4a8b-a759-6813028f575d.png)

3. Now try to tie just the first two notes together, mess happens:
![image](https://user-images.githubusercontent.com/19684839/213299623-16e87cbd-c329-4680-955a-662875a112fe.png)

4. Second bug, the 4th and 5th notes (aka copy-pasted notes) don't seem to react when trying to tie them:
![image](https://user-images.githubusercontent.com/19684839/213300351-6d8b612f-b321-4a32-a014-35330796ade0.png)
It's probably the reverse of the medal of 3.

Looks like some reference needs to be cleared out for copy pasted notes. 

**Expected behavior**
Tieing notes shouldn't affect unrelated notes.

**Platform information**
 - OS: Windows

**Comment by cbjeukendrup** [comment]
This is expected. When you _tie_ notes, they will get a tie to the next note that has the same pitch, if there is such note.

You likely want to _slur_ these notes instead (press the keyboard shortcut 'S'; or use the 'Slur' button in the toolbar, namely the one showing 3 notes rather than 2; or add it from the 'Lines' palette).
