### ISSUE TITLE
[MU4 Issue] Waves plugins don't work properly with MuseScore (don't show bundle content)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#15968]
https://user-images.githubusercontent.com/90187801/213451167-34b80a67-3b52-43ca-88a6-57eb334fc13c.mp4

**Expected behavior**
MU should show all list of plugins (like Audacity does) not only WaveShell

**Platform information**
**Windows10**
**Mac12**

**Additional context**
Works fine in **Audacity** (see video)

**Comment by cbjeukendrup** [comment]
Is this maybe because those other plugins are VST2 (rather than 3)? Audacity does support VST2, while MuseScore doesn't.

**Comment by DmitryArefiev** [comment]
> Is this maybe because those other plugins are VST2 (rather than 3)? Audacity does support VST2, while MuseScore doesn't.

Hmm.. Good idea! But I replaced VST2 version of Waves plugins from default location and they still work in Audacity

![Capture](https://user-images.githubusercontent.com/90187801/213494317-4f41c0d4-2a62-4d71-bc81-5e4a9dd5aef4.PNG)

**Comment by jessjwilliamson** [comment]
I can confirm, Marek (who has a lot of plugins) also has this same issue with his Waves plugins. He reckons it's a Waves API issue

**Comment by DmitryArefiev** [comment]
Still occurs in **4.4.4** and **4.5 nightly**

**Comment by DmitryArefiev** [comment]
Also, I've found that **Waves** plugins working only with **one channel** (Left channel)  

Tested in **4.4.4** on Windows10
