### ISSUE TITLE
[MU4 Issue] Corruption sanity check does not check part scores

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#15977]
It only checks the master score, but not the part scores.

[Purposefully corrupted part score.mscz.zip](https://github.com/musescore/MuseScore/files/10460082/Purposefully.corrupted.part.score.mscz.zip)

In this test file, I have manually corrupted one of the parts, by deleting the content of some measures using a text editor. But this corruption goes completely unnoticed; MuseScore just opens the file without any warning. But if you look at the part score, it's immediately clear that something is wrong...
<img width="500" alt="image" src="https://user-images.githubusercontent.com/48658420/213534292-40477f3b-e2f8-44b7-9cbf-4c616706a62a.png">

This means that these corruptions are detected only when it is too late and they have already propagated to the master score. Instead, we should detect them as early as possible, and ideally offer the solution to delete the corrupted parts if the master score is still intact.

This will also require some design updates to the corruption warning dialog, because it now also needs to say _in which score_ the corruption is.

**Comment by cbjeukendrup** [comment]
@Tantacrul together with the other things relating to corruptions we're working on currently, this might be another important step in preventing/fixing them. I'll leave it to you to prioritise.

**Comment by Tantacrul** [comment]
I'll chuck it in 4.1 for the moment. We'll need to discuss our options. Thanks!

**Comment by cbjeukendrup** [comment]
Just came across a case on musescore.org where this happens in practice... https://musescore.org/en/node/343041

It looks like it would be relatively easy to check part scores too (as in, I should be able to finish this tonight). We just need to decide how to convey this in the corruption details dialog; I guess we can do it as simple as this:
> **Incomplete measure:** Full score, measure 62, staff 3. Found: 23/8. Expected: 3/4.
> **Incomplete measure:** "Flute" part score, measure 62, staff 1. Found: 9/4. Expected: 3/4.
> **Incomplete measure:** "Piano" part score, measure 62, staff 2. Found: 11/4. Expected: 3/4.

I'm not completely sure about the wording `"Flute" part score`, but I do think we should somehow make clear that we mean the  Flute _part score_, rather than the Flute _staff_ in the full score. Thoughts on this?

(And later, for 4.1 we can indeed start thinking about advanced options like offering to regenerate the corrupted parts, or even somehow only regenerate the corrupted measures only...)

**Comment by bkunda** [comment]
I think saying "part score" makes it pretty clear, and is unlikely to cause confusion with the idea of a part as a stave. 
A tiny nitpick might be instead to reverse the order of information, i.e. **Part score: Flute**. Then when scanning down the list, one more readily recognises both "full score" and "part score".

**Comment by cbjeukendrup** [comment]
@bkunda Thanks, that's much better indeed! I'm about to create a PR.

**Comment by Jojo-Schmitz** [comment]
Came up long ago in https://musescore.org/en/node/139026
