### ISSUE TITLE
[MU4 Task] Consider creating a DEB, RPM, etc. for installing MuseSounds instead of MuseHub

### ISSUE THREAD

**Issue by crispyricepc** [musescore/MuseScore#15978]
Since MuseHub is installing files to directories that should ideally be left for package managers to handle, and most package managers allow proprietary packages to be installed (see rpmfusion, OBS or the AUR), it would make more sense to use these pre-existing tools to distribute MuseSounds on linux.

**Comment by jeetee** [comment]
Muse Hub support and feature requests are handled over at their support site: https://musehub.zendesk.com/

**Comment by cbjeukendrup** [comment]
Indeed, this is something for the Muse Hub / Muse Sounds teams to handle over at https://musehub.zendesk.com/, so I'll close it here.
