### ISSUE TITLE
[MU4 Issue] multibar rest numbers incorrect

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#15984]
**Describe the bug**
multibar rest number range shows the wrong numbers or show % sign

**To Reproduce**
1. make a part with multiple rest bars
2. activate multirest bar numbers
3. see if the numbers are accurate

**Screenshots**

![image](https://user-images.githubusercontent.com/120861729/213612201-230bfd69-2469-4ee7-a659-6e3ff9b04bc8.png)

**Platform information**
windows

**Additional context**
and the "break multibar rest" function on the main score does not affect the parts

![image](https://user-images.githubusercontent.com/120861729/213611005-4d44b3ab-9d0e-44a4-a066-e46925665b6d.png)

![image](https://user-images.githubusercontent.com/120861729/213611216-aa5900f8-61a1-4b93-b070-dd0186a0ce40.png)

**Comment by Vykoiazon** [comment]
and breaking multibar rest in the parts also does not affect the part so it has to be done with invisible rests instead

**Comment by Vykoiazon** [comment]
the tremolo on whole notes is also switching between above and below staff for unknown reasons when it should always stay below (no option in properties to move the tremolo below the note except changing coordinates)

**Comment by MarcSabatella** [comment]
Thanks for the report - this is actually already known and fixed for a coming update.  See https://github.com/musescore/MuseScore/issues/15635
