### ISSUE TITLE
[MU4 Task] Set up translations for new strings in 4.0.2

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#15987]
**Task description**
Version 4.0.2 will contain some new strings. We need to upload these to Transifex, without removing any strings that are currently there, because version 4.0.1 and 4.0.0 still rely on those strings.

**So it is very important that nobody pushes any new strings to Transifex right now.**

Two possible solutions:
- Make an option in the "push to Transifex" GitHub Action, that allows us to choose whether "obsolete" strings should be removed or kept; that means we would push the new strings without removing the old ones. This way, both 4.0.0, 4.0.1 and 4.0.2 can keep using the languages from `http://extensions.musescore.org/4.0/languages/`.
- Create a new endpoint for uploading changes from Transifex, for example `http://extensions.musescore.org/4.0.2/languages/`, so that all new changes will be sent to that place, while the old place stays unchanged. This has the disadvantage that users of 4.0.0 and 4.0.1 won't receive any translation updates while 4.0.2 is in development (not even released yet).

**Comment by Jojo-Schmitz** [comment]
> **Task description** Version 4.0.2 will contain some new strings. We need to upload these to Transifex, with removing any strings that are currently there, because version 4.0.1 and 4.0.0 still rely on those strings.

with**out** removing any strings that are currently there

Responsible for that is the use, or here rather the non-use, of the `-no-obsolete` commandline option of the `lupdate` command

**Comment by cbjeukendrup** [comment]
> with**out**

Phew, silly typo! Corrected.

> Responsible for that is the use, or here rather the non-use, of the `-no-obsolete` commandline option of the `lupdate` command

Indeed, that's what I was thinking of. We just need a way to tell the CI action to use this flag.

**Comment by Jojo-Schmitz** [comment]
Or rather to **not** use it, we'd want to keeo those 'obsolete' strings (as they are not obsolete in 4.0.0 and 4.0.1). Not using that was common practise for all minor 2.x and 3.x releases, using it just once (and possibly manually) when moving to a new minor or major version, but not for patch releases

**Comment by Jojo-Schmitz** [comment]
I believe this is done now

**Comment by cbjeukendrup** [comment]
Last remaining step is to merge the changes to Master too. Apparently PRs to other branches don't automatically close issues.

**Comment by Jojo-Schmitz** [comment]
Ah, I see. But it might get removed from the 4.0.2 project ;-)
