### ISSUE TITLE
[MU4 Issue] Wrong pedal change playback

### ISSUE THREAD

**Issue by SFraissTU** [musescore/MuseScore#16001]
**Describe the bug**
Pedal changes using the `\___/\___/` -style notation often result in wrong playback, either by adding a noticeable pause before the pedal change, or by falsely continuing the previous notes for a while.

**To Reproduce**
Steps to reproduce the behavior (see screenshots below and attached file):
1. Create five piano bars with a half note in each of the first four bars (in the bass clef).
2. Add a `|____/` between the first and second note
3. Add `\____/` between the second and third, and the third and fourth note
4. Add `\____|` between the last note and the end of the fifth bar.

What I hear when I play this back is the following:
- The first two notes are not played for a full bar each, but there is a short pause before the first note from the next bar.
- The third note plays the full bar, but continues for two more beats into the fourth bar.
- The fourth note stops after two beats.

**Expected behavior**
- The first three notes are heard for one full bar each without any pauses in between.
- The fourth note is heard for two bars.
- 
The correct behaviour can be seen if instead of the `\____/`-notations I use `|____|` for the first three bars each and for the fourth and fifth bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/26391469/213881111-278b8b4f-d319-46b5-b303-fb7dff533495.png)
The first line displays an example that fails. The second line displays an example that sounds like what I want, but with a different notation (although in the second example I would expect the pauses that are hearable in the first example).

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Additional context**
This works fine for me in MuseScore 3.6.2.548021803 (rev github-musescore-musescore-3224f34). This, as well as other playback issues (especially that piano only results in a loud note being played with less volume rather than a soft note) is so annoying to me that I will probably switch back to MuseScore3. 

File in which this happens:
[MS-Example.zip](https://github.com/musescore/MuseScore/files/10472753/MS-Example.zip)

**Comment by bluebear94** [comment]
The pause before the pedal change probably happens because MuseScore subtracts `Constants::DIVISION / 4` ticks from the actual duration of any pedal line ending in an angled hook ([spannerfilter.cpp](https://github.com/musescore/MuseScore/blob/master/src/engraving/playback/filters/spannerfilter.cpp#L62)). I’ve also noticed the latter effect, but I don’t know what’s causing it yet.

**Comment by bluebear94** [comment]
The `Constants::DIVISION / 4` subtraction seems to have been introduced to fix #12869, but I think changing the `spannerTo < ctx.nominalPositionStartTick` comparison to use `<=` solves that bug as well as #16757.
