### ISSUE TITLE
[MU4 Issue] Score extremely zoomed in on ultra-wide monitor

### ISSUE THREAD

**Issue by rdelfin** [musescore/MuseScore#16002]
**Describe the bug**
When on my ultra-wide monitor (5120x1440), I cannot zoom out far enough to see a full page. Specifically, a 5% zoom shows me just under the height of a single staff. Naturally this makes the application very difficult to use.

**To Reproduce**
1. Open Musescore
2. Create a new score

**Expected behavior**
A screen with a page of score where I can at least see the full width of the page, or where the full page is visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/3235566/213887720-ffa44bfb-feda-4753-b15c-3d84958d19db.png)

**Platform information**
 - OS: Linux (Ubuntu 22.04) with Regolith 2 Window Manager

As provided by the app:
Ubuntu 22.04.1 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Additional context**
I've attempted switching back and forth between page view, continuous horizontal, and vertical view to no effect. I've also tried resizing the window on startup, and multiple different things that might show zoomed out pages to no effect. I've also confirmed it's not just the window manager I use as I've tried this on a laptop with a smaller screen which works fine.

**Comment by MarcSabatella** [comment]
What *should* happen is 100% zoom would display things "life size" - the score would be the same size on screen as printed.  But some systems scale things in ways that interfere with these calculations, and I guess that is likely what is happening here.  Does your window manager provide scaling controls you can play with?  Also try starting the AppImage with the QT_SCALE_FACTOR environment variable set.  Normally this sizes the interface but not the score, but depending on your system scaling, you might need some combination of the two.

**Comment by rdelfin** [comment]
Thanks for the quick response @MarcSabatella! I've tried what you suggested, both doubling and halving the scale factor, but in both cases the score looks the same. All the other UI elements do seem to scale up and down accordingly, but not the score itself.

**Comment by cbjeukendrup** [comment]
This reminds me of #15591, where the navigator seemed to be the cause of this. Is that possibly the case in your situation too?

**Comment by rdelfin** [comment]
Did a bit of playing around. It looks like this is (probably) _not_ my window manager as I initially thought! Switched back to Ubuntu's default and it _still_ shows this behaviour.

@cbjeukendrup: as far as I can tell that's not it. It does indeed open at "normal" 100% zoom unlike the reported issue. It's just that it looks like the way that 100% is calculated on my wide-screen makes it look extremely zoomed in. Don't see any of the stuttering described.

**Comment by rdelfin** [comment]
Interestingly, if I switch the orientation of my monitor the issues doesn't go away, so it might not be exclusively because of how _wide_ the monitor setting it. Unfortunately `QT_SCALE_FACTOR` didn't help, but let me see what else I can find

**Comment by rdelfin** [comment]
I've done a bit of digging and I'm fairly sure now this is because my monitor is reporting something wrong in the EDID, resulting in xorg thinking its "real size" is 1mm x 1mm (or defaulting to that for some god forsaken reason):
```
$ xrandr | grep -w connected
DP-0 connected primary 5120x1440+0+0 (normal left inverted right x axis y axis) 1mm x 1mm
```
I found an instance of this in AvaloniaUI/Avalonia#5124 (interestingly enough they have the exact same resolution as my monitor, maybe it's the same one?), including a suggestion on how to potentially fix it. @MarcSabatella: does this sound like it could be it?

**Comment by rdelfin** [comment]
I've now confirmed this is the case. It looks like my monitor does correctly report monitor physical dimensions if I change the resolution, at which point MuseScore shows a much smaller, but workable score window. I can temporarily solve this by lowering my resolution when I open MuseScore, starting the page I'm gonna work on, and increasing it again (it seems DPI is not dynamically re-calculated). Should there be an override in the settings or a min DPI? I attempted fixing this, but I'm unfortunately a bit unfamiliar with the codebase. I'd be happy to look into it if I can be pointed in the right direction!

**Comment by cbjeukendrup** [comment]
@rdelfin Is MuseScore's `-D <dpi override>` command like option maybe a solution in your case? like `mscore -D 144`

**Comment by MarcSabatella** [comment]
Unfortunately, even if it works in that case, this option does not propagate to additional instances opened after the first.  I sure wish it did; that would simplify my life considerably.

**Comment by Eism** [comment]
@rdelfin could you check the build from #17759?
Direct link - https://github.com/musescore/MuseScore/suites/13201140801/artifacts/718838823

**Comment by cbjeukendrup** [comment]
@rdelfin - kind reminder about the question above :)
