### ISSUE TITLE
[MU4 Issue] Gliss. hitbox prevents selecting the bar

### ISSUE THREAD

**Issue by Attackoh** [musescore/MuseScore#16017]
**Describe the bug**
The hitbox is too big. Trying to click on the bar instead selects the gliss instead. The only space where you can select the bar currently is clicking under or above the note to avoid the gliss.

**To Reproduce**
1. Create score with gliss
3. Click on parts of the bar with no elements
4. Gliss will instead be selected

**Expected behavior**
Gliss lines are small so it makes sense that the hitbox is bigger than it actually is, but in its current state it prevents other regular functions like selecting a bar.
**Screenshots**
![image](https://user-images.githubusercontent.com/120669196/213983164-acc33cc1-fcca-431a-ae4e-71c76b94e564.png)

**Platform information**
 - OS: Windows 10
**Additional context**

**Comment by cbjeukendrup** [comment]
Hm... coincidentally I had just logged this same issue a few days ago, see #15997. So I'll close this as a duplicate. Thanks for reporting though!
