### ISSUE TITLE
[MU4 Issue] Note entry toolbar icon for augmentation dot is confusing

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#16027]
**Describe the bug**
The icon to apply an augmentation dot is a dotted quarter note.  This has caused confusion with at least one user who assumed incorrectly but justifiably that selecting it would select a dotted quarter note as the duration and that no other dotted durations were possible.

**Expected behavior**
The icon for applying an augmentation dot should be unambiguous

**Screenshots**

![AugDotIcon](https://user-images.githubusercontent.com/60138048/214111228-2fb0b5a4-607a-4ae2-bbef-8dfb6a890269.jpg)

**Additional context**

The addition of a button to apply staccato articulation in MU4 has supplanted the MU3 icon for augmentation dot making it necessary to use a different icon for augmentation dot, but what? - a "ghost note" with a dot perhaps?

Forum thread: https://musescore.org/en/node/342766

**Comment by MarcSabatella** [comment]
Once upon a time, the rest icon was replaced with a much uglier one that showed multiple rests, to give you the hint that multiple values were possible.  I'm not proposing we do that here.  But maybe the icon itself could *change* appearance based on the selected duration?  I think that was actually what people wanted with respect to the rest, but it was perceived to be too awkward to implement.

**Comment by SteveBlower** [comment]
I thought of that, but then dismissed it as a sledgehammer to crack a nut.  But then again, I can't come up with a better idea.  Perhaps the sledge hammer **is** needed.

**Comment by M00nbox** [comment]
>...maybe the icon itself could _change_ appearance based on the selected duration?

This proposed solution begs the question of what the icon would look like _before_ a duration is selected. What default appearance would best communicate its function?

IMO, SteveBlower's _dotted ghost note_ suggestion is sensible.

**Comment by Tantacrul** [comment]
@SteveBlower - are you still confused by it, now that you know how it works?

I'm open to suggestion but I struggled to think of a better icon. A dot icon by itself would simply be mistaken for a stacatto mark by some people.

Closing for now because I can't quite see a way to make the icon clearer. Again - open to suggestion.

**Comment by SteveBlower** [comment]
I was never confused as I always use the keyboard shortcut rather than the toolbar.  However, another user was having difficulty and said that it seemed possible to only have augmentation dots on crotchets.  It took a while for the penny to drop (after I looked at the MU4 toolbar for the first time) that he was actually misinterpreting the augmentation dot icon.  I was hoping that raising the issue here would prompt someone with more design skills than I have to find a more suitable icon (which wouldn't be too similar to the staccato icon).

From my personal point of view this can be closed; but it should not be surprising if there are other users out there who misunderstand the current icon.

**Comment by MarcSabatella** [comment]
Fwiw, we had a similar issue with the rest icon, which was a quarter rest, and people always assumed it meant that was the only kind of rest you could enter.  So we changed it some years ago to college of different rests types which solves that issue kind of but certainly wouldn’t win any design awards.  Someone had the clever idea of making the icon change in response to the selected duration.  Seems this approach could be used here, but I don’t know if that’s too hacky.

**Comment by M00nbox** [comment]
Suggestion: Retain the current icon (dotted quarter-note) but grey-out the quarter note while keeping the dot black (or white, if display is set to dark mode). This will convey that the dot, not the note value, is the significant component of the icon.

**Comment by Tantacrul** [comment]
@MarcSabatella 

I dislike the idea of having loads of rests because I think the previous one was quite bad and illegible.

HOWEVER - I love the idea of swapping the icons depending on the duration you choose. That is actually quite an interesting idea that (if it doesn't behave weirdly) could be really elegant.

**Comment by Tantacrul** [comment]
> Suggestion: Retain the current icon (dotted quarter-note) but grey-out the quarter note while keeping the dot black (or white, if display is set to dark mode). This will convey that the dot, not the note value, is the significant component of the icon.

One small suggestion: it's always much handier when visual design proposals are accompanied with a visual example. Visual solutions can sound good when written in a sentence but all too often do not hold up when visualised. In this case, I can already picture a potential UX problem with greying out part of the icon (as well as a UI inconsistency which would spoil the overall look) in my head.

**Comment by MarcSabatella** [comment]
Yeah, I never liked the rest-collage either, but people thought it worth a shot, and it did cut down on the complaints noticeably.  I don't think anyone actually *tried* implementing the automatically-changing icon, but it's hard to imagine that being difficult to pull off.  It still relies on you having the foresight to try selecting duration first, but you select duration a hundred times a day anyhow, maybe you'd notice the icon changing and get the clue.

**Comment by SteveBlower** [comment]
Came up again https://musescore.org/en/node/347790
