### ISSUE TITLE
[MU4 Issue/Task] Inconsistencies regarding "Expand repeats" setting

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#16029]
**Describe the bug**
There are various problems with the "expand repeats" setting:
- When exporting audio, we use the value that is used for in-app playback
- That results in #15720 
(MuseScore.com apparently expects that we always expand repeats when uploading audio)
- For MIDI export: #16021
(I already fixed the checkbox locally, but now that the checkbox itself is working, these underlying problems surface)
- The `Score::extractLyrics` method assumes that `masterScore()->setExpandRepeats(…)` works (but it does nothing), possibly resulting in wrong lyrics (this method is used both for copying lyrics and for the MuseScore.com backend)

**The problem**
We have not one, not two, not three, but ***four*** sources of truth:
- `MScore::playRepeats`
- `MasterScore::_expandRepeats`
- `PlaybackModel::m_expandRepeats`
- `NotationConfiguration::isPlayRepeatsEnabled()`

Not very surprising that we have bugs...

**Comment by abariska** [comment]
@cbjeukendrup 
- Regression in the PR according to https://github.com/musescore/MuseScore/issues/16021 

Precondition - Expand repeats' is enabled. 
Notes from further measures are overlayed the repeat section  when played second time

https://user-images.githubusercontent.com/101250347/225894251-356324e8-ede3-4670-9862-253c418ebc6f.mp4


- Audio and cursor are still not synchronised when score exported with 'Play repeats' disabled

https://user-images.githubusercontent.com/101250347/225897293-c89843aa-36ea-47af-99ba-25a1114edd45.mp4


[Test score](https://github.com/musescore/MuseScore/files/11001004/repeat.midi.mscz.zip)

**Comment by abariska** [comment]
🟢 **TESTED on macOS 12
