### ISSUE TITLE
[MU4 Issue] Can't save locally if you chose "Save to cloud" and "Don't ask again" and don't log in to MuseScore.com

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#16037]
**To Reproduce**
Assuming you start with fresh settings (not logged in, and not yet clicked "Don't ask again" in "How would you like to save?" dialog)
1. File > Save as…
2. Check "Don't ask again" and click "Save to cloud"
3. You will be asked to log in to your MuseScore.com account. From now on, there is no way anymore to get the local file save dialog, because even if you click "Cancel" and then try again, you are immediately asked to log in again, skipping the "How would you like to save?" dialog.

**Workaround**
Log in with a MuseScore.com account when you're asked to do so. Then, you get the "Save to cloud" dialog, where you have a "Save to computer" button. 

**Additional context**
Originally reported in https://musescore.org/en/node/343408.
As people pointed out there, this may also cause you trouble when you're offline (because you need to get the "Save to cloud" dialog to be able to have a "Save to computer" button, but when you're offline, you can't get the "Save to cloud" dialog).

**Possible solutions**
- We could drop the "Don't ask again" checkbox
- We could make it so that "Save as…" always gives the local save dialog (because the "Save to cloud" dialog can be opened using "File" > "Save to cloud") (disadvantage: annoying for the few people who want "Save to cloud" to be their default option)
- We could add a new "Save to computer" option (disadvantage: that gives MuseScore more "Save…" options than the amount of magnifying glasses in Audacity)
- We could add a "Save to computer" to the dialog that asks you to log in to MuseScore.com (disadvantage: makes the dialog uglily wide) (is uglily even an existing word?)
- …

**Comment by bkunda** [comment]
Good spot!
I don't think it is hugely problematic to add that "save to computer" button to the "you are not signed in" dialog: in terms of aesthetics, we do (as you yourself recently reminded me @cbjeukendrup) already have a four-button dialog pattern in the app. 

<img width="1408" alt="Screenshot 2023-01-24 at 10 51 52 am" src="https://user-images.githubusercontent.com/86290556/214260956-c27266b2-d066-41f6-bac0-fc0d922262c0.png">

At least this way, we don't add any other "save" options to the mix, and we preserve the current behaviour that recalls the last-used save dialog. I also think we shouldn't ditch the "don't ask again" checkbox as this is important for users who don't want to be prompted where to save each time. 
 
With four options in the dialog, I'd be tempted to give the "Login" button an accent colour too, just to make the objective of the messaging super clear.

**Comment by Tantacrul** [comment]
@cbjeukendrup @bkunda - is this definitely needed for the patch or can it wait to 4.1?

**Comment by cbjeukendrup** [comment]
I doubt about it. I've seen only one thread about it on the forums so far, and the user can easily work around it by resetting preferences, making the correct choice in the "How would you like to save" dialog, or logging in to MuseScore.com so that the "save to computer" button in the "Save to cloud" dialog can be used.

**Comment by Tantacrul** [comment]
> 

I think 'create account' is overkill here. I'm moving to 4.1, since it's not an urgent fix.

**Comment by bkunda** [comment]
> @bkunda in that graphic you posted:

Completely agree 🙂

**Comment by rolodoom** [comment]
Hello there. I'm testing MuseScore on Linux Manjaro and getting the same problem. Reset the preferences worked for me but it's kind of a bummer. Hope it get fixed on next release. Also created a [forum report](https://musescore.org/en/node/346239)

Tested on Musescore 4.0.1 from Official Manjaro Repo

**Comment by bkunda** [comment]
@cbjeukendrup I think we have decided how best to tackle this (add the "save to computer" button and remove the "create account" button from the above dialog. lmk if you have any questions about this. Moving to "ready for development" for when you get a chance 🙂

**Comment by cbjeukendrup** [comment]
Ah yeah, this one is also still on my radar!

**Comment by mathesoncalum** [comment]
Nearly done with this @bkunda @cbjeukendrup, quick question about the copy in the dialog though.

Now that there isn't a "Create Account" button, should the dialog still say "Login or create a free account on musescore.com to save this score to the cloud", or would something like the following make more sense:

<img width="509" alt="Screenshot 2023-11-14 at 13 58 18" src="https://github.com/musescore/MuseScore/assets/47119327/db7b24df-cb41-472f-845d-dda9cb3ed36c">

**Comment by bkunda** [comment]
Good suggestion @mathesoncalum about the copy. I'm happy with this.

**Comment by shoogle** [comment]
@mathesoncalum, I believe it should be "Log in" (two words). You could also make "musescore.com" a clickable link to https://musescore.com/. I believe that's as simple as adding `<a href="https://musescore.com/">musescore.com</a>`.

**Comment by mathesoncalum** [comment]
Good shout @shoogle will change to "Log in" - @bkunda thoughts on adding a link here?
