### ISSUE TITLE
[MU4 Issue] Bar number offset between score and footer information bar when there is an anacrusis

### ISSUE THREAD

**Issue by Skelbti** [musescore/MuseScore#16049]
**Describe the bug**
The number shown in the information bar at the bottom of the screen is offset from the bar number on the score.

**To Reproduce**
1. Add an anacrusis
2. Add some measures
3. See error

**Expected behavior**
The number displayed should be the same on the information bar and on the score. The anacrusis bar should display the number 0 in the information bar.

**Screenshots**
![Capture d'écran_20230124_182157](https://user-images.githubusercontent.com/86026713/214365612-2b5600c0-bbed-4827-80cd-fc513d228b8e.png)

**Platform information**
 - OS: Windows 11

**Comment by Jojo-Schmitz** [comment]
That is normal and by design. MuseScore internally counts all measures and refers to them by their internal measure number, that's ther number shown in the footer

**Comment by Skelbti** [comment]
Sorry in this case. It seemed more convenient to have the same number everywhere to find your way around but I understand the importance of having a fixed reference point.

**Comment by Jojo-Schmitz** [comment]
The status bar might **additional** show the _logical_ measure number

**Comment by MarcSabatella** [comment]
Absolutely, showing both would be a good enhancement.  Kind of like how notes on transposing instruments report "D5 (sounding as C5)" etc.  But it would be a bit distracting to have that displayed for each and every element.  Probably some design work would be needed to come up with a good strategy.
