### ISSUE TITLE
Tie to nothing (for jazz)

### ISSUE THREAD

**Issue by moogly81** [musescore/MuseScore#16052]
**Describe the bug**
<img width="947" alt="musescore-open-ties" src="https://user-images.githubusercontent.com/2691085/214378482-8abe8d24-a5d0-4e51-9465-7896cec7c346.png">

Jazz rhythm section often use the concept of a "tie to nothing". Drums typically uses a cymbal. Pianos and guitars let a chord ring. 
I can already do it right now.
  - a tie to an invisible note (like bar 2 in the screenshot), but I have to remember to hide the note in the score AND the instrument part everytime.
  - a slur (like bar 4 in the screenshot). Each slur has to be adjusted manually. 

**Feature request**
A "tie to nothing" native feature, either with a tie or some kind of glissando symbol. 

PS Bar 2, the tie crosses the beam.

**Comment by MarcSabatella** [comment]
This is called “l.v.” and is found on the Articulations palette.  The default positioning is not currently ideal though.

**Comment by moogly81** [comment]
Oh ok, sorry ! I looked but did not find it. Including in the documentation.

**Comment by moogly81** [comment]
Hi, 
Thanks for the tip about the "l.v" (laissez vibrer). 
There are still some issues  : 
  - The l.v sign is placed wrong by default (pic 1), and therefore has to be fixed manually everywhere on score and parts. 
  - The l.v sign is always the same size, no matter the measure size (pic 2)

<img width="487" alt="image" src="https://user-images.githubusercontent.com/2691085/214445680-9f8c1b51-a0ab-433a-96b2-341e3237aec4.png">

<img width="975" alt="image" src="https://user-images.githubusercontent.com/2691085/214446398-2f5fd007-1165-4a5d-b3a8-fffcc90dd063.png">

**Comment by oktophonie** [comment]
Closing as replaced by https://github.com/musescore/MuseScore/issues/16052
