### ISSUE TITLE
[MU4 Issue] Jumps (Segno, Fine etc.) are doubled in Piano part in SATB + Piano template

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#16063]
**Describe the bug**
Jumps (Segno, Fine etc.) are duplicated in Piano part in SATB + Piano template. 
The same happens in similar scores where system objects are duplicated between several instruments in score (Violin 1 part in Symphony orchestra template)

https://user-images.githubusercontent.com/90187801/214608903-3e6b9f4a-1e50-46ed-9a83-81d0b9c0631b.mp4

 

**Platform information**
 macOS, Windows, Linux

**Additional context**
Doesn't occur in **MS3**

**Comment by DmitryArefiev** [comment]
FYI @oktophonie

**Comment by oktophonie** [comment]
Fix will presumably be similar to/an extension of https://github.com/musescore/MuseScore/pull/15389

**Comment by Jojo-Schmitz** [comment]
Check out https://musescore.org/en/node/343581 for another critical problem with SATB+Piano

**Comment by DmitryArefiev** [comment]
Fixed in #15938

**Comment by DmitryArefiev** [comment]
Retested on Win10
