### ISSUE TITLE
Note Velocities do not carry over from Main score to Part scores

### ISSUE THREAD

**Issue by RyanHanter** [musescore/MuseScore#16085]
When opening up a Part score for an instrument in the Main score, the note velocities stated in the Part score do not reflect that of the Main Score, and editing the note velocities of notes in the Part score does not change the note velocity of the Main score. 
While this could be by design, the playback does not reflect what is shown too.

To duplicate:
Create a template with multiple instruments and fill one instrument staff with notes
Change the velocity of some of the notes in that staff
Create a Part score for that instrument staff
Check the note velocity of the edited notes in the Part score (it will not reflect the true note velocity)
Edit the note velocity of several notes in the Part score (it will not carry over to the main score)
Play the playback (the playback will follow the note velocity of the Main score and not the Part score)

**Comment by scorster** [comment]
I'm not sure the pertains 100%, but in MuseScore 3 I believe there is only an initial conveyance of velocity to generated Parts. Thereafter the is no velocity synchronization in either direction. I haven't tested the behavior in MS4, but if velocity sync was not changed changed in MS4 I'd assume the issue remains. 

Playback is entirely dependent on velocities in the Main score ... ironically, even when Play Part Only is checked. Parts and linked staves are velocity orphans. 

Here are discussions from mid 2001 regarding velocity synchronization for Parts and Linked staves:

https://musescore.org/en/node/322562

https://musescore.org/en/node/323448

scorster

**Comment by oktophonie** [comment]
As of 4.2, velocity (and tuning) are synchronised with parts, and can be de-sync'd within the parts when modified there directly, like all other properties.

(As far as the sync system they are considered 'Style/appearance' settings, so either that category might be renamed or, perhaps more likely, we'll spin off playback settings to their own category so that they can be sync'd/reset independently, but that's another matter.)
