### ISSUE TITLE
[MU4 Issue] Fret marks badly misaligned between voices on tab staves

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#16088]
**Describe the bug**
Under certain conditions, voices 1 & 2 can be badly misaligned on tab staves.

**To Reproduce**
1. Download the attached score (created from scratch in 4.0.1 using the Guitar + Tablature template) - [misaligned.zip](https://github.com/musescore/MuseScore/files/10513441/misaligned.zip)
2. Rename to MSCZ
3. Open
4. See error: the voice 1 & 2 fret marks are not even close to being aligned on the tablature staff

**Expected behavior**
The two fret marks should be perfectly aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/1799936/214952067-bec95bfe-b61f-4af4-9fd2-3d4001fb628a.png)

**Platform information**
 - OS: Linux

**Additional context**
Originally reported in a case involving MuseScore 3 import.  But I have since reproduced from scratch.  And also, I have reproduced in a case where I add the two staves separately (not relying on the template.  But, it's hard to describe exactly what the steps are to reproduce that way, because it seems to depend somehow on the order I do things in.  At the least, the minimum requirements to reproduce seem to be, "full" tablature style, with linked standard staff also.

**Comment by oktophonie** [comment]
_Almost_ fixed by https://github.com/musescore/MuseScore/pull/15073 (coming in 4.0.2)

![image](https://user-images.githubusercontent.com/20604032/214953868-0b45d9ae-2468-4aea-9ed8-6a0fe43982ef.png)

**Comment by MarcSabatella** [comment]
Hmm, still looks the same as 4.0.1 for me in the current 4.0.2 nightly build.  I think maybe that PR is only in master?
