### ISSUE TITLE
[MU4 Issue] Flickering issue when using global menu (Linux, KDE Plasma)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#16094]
**Screenshots**

![menu-2-1](https://user-images.githubusercontent.com/90187801/215053112-9ea19f0a-cf2c-47a9-a293-33cfa3c78706.png)
![menu-2-2](https://user-images.githubusercontent.com/90187801/215053122-ce2ebc33-2e8e-4b7c-aceb-7d6852e84dad.png)
![menu-2-3](https://user-images.githubusercontent.com/90187801/215053127-e162c7cf-2d74-402b-81a0-5af6a7516528.png)

**Platform information**
Linux KDE Plasma

**Additional context**
Related to #15826 changes

**Comment by njvdberg** [comment]
FWIW, I see something similar is e.g. kdevelop5. So I'm not sure this is a MuseScore specific issue.

**Comment by adazem009** [comment]
Please check if this is resolved in #18593

**Comment by DmitryArefiev** [comment]
@adazem009 The initial screenshots was not taken from my machine (from Discord chat). 
Now I've installed KDE Plasma and can reproduce very similar effect in **4.2 master** when clicking File menu:

https://github.com/musescore/MuseScore/assets/90187801/97469942-930d-4803-977c-104fb2f76cb6

And it looks normal (fixed) in  #18593

**Comment by adazem009** [comment]
> @adazem009 The initial screenshots was not taken from my machine (from Discord chat). 
> Now I've installed KDE Plasma and can reproduce very similar effect in **4.2 master** when clicking File menu:
> 
> https://github.com/musescore/MuseScore/assets/90187801/97469942-930d-4803-977c-104fb2f76cb6
> 
> And it looks normal (fixed) in  #18593 
> 
> 
> 
> 
> 

Do you also experience crashes after closing MuseScore? That issue is related to the global menu bar too.
