### ISSUE TITLE
cursor type not updating when it's the first time switching from clef to tabs with ALT + ARROW [MU4 Issue]

### ISSUE THREAD

**Issue by somethingstarted** [musescore/MuseScore#16108]
**Describe the bug**
cursor type not updating when it's the first time switching from clef to tabs with ALT + ARROW

**To Reproduce**
1. open score with tabs, could be empty or have tabs already. 
2. enter enter notation mode. add a note to the notation above. 
3. press ALT + DOWN and you should see the long, big notation cursor over the tabs. 

**Expected behavior**
it should switch from the notation cursor to the tabs cursor

![bug i found musescore](https://user-images.githubusercontent.com/19464532/215259270-8dea5bf7-bb27-48b9-88ae-89531892648e.JPG)

**Platform information**
 - OS: win10

**Comment by zacjansheski** [comment]
Just tried this and it works right away for me on Windows 11, is this still an issue?

**Comment by zacjansheski** [comment]
Closing
