### ISSUE TITLE
[MU4 Issue] Instruments using MuseScore Basic going whack

### ISSUE THREAD

**Issue by Burke-Maester** [musescore/MuseScore#16100]
For whatever reason, when ever I put a note on an instrument using the MuseScore Basic sounds, this or something similar happens:
https://drive.google.com/file/d/1C7KF06okDqVkG1nsXJbhE27biQzWsxVU/view?usp=sharing

I've also gotten it to spam the note I create until I press escape, which then leaves me with many measures full of that one note I originally created.

This has happened to me with bass guitar and guitar. The same happens with piano, but only when I set it to use MuseScore Basic.

Does anyone know how to fix this?

**Comment by MarcSabatella** [comment]
I've never seen anything like that before = are you sure your house isn't defective?  What if you type the note instead?

It might be something corrupt in the score as well - best if you ZIP that and attach it.

**Comment by Burke-Maester** [comment]
What do you mean by "house"?
If I type the note, the exact same thing happens.
I know it is not the score; this has happened on several scores, though they have all been using the "Big band" template.

**Comment by cbjeukendrup** [comment]
My guess is that there's a MIDI loop somewhere... if you have selected MS Basic, the MIDI events are also sent to the selected MIDI output in Preferences > I/O. If the events are then somehow routed back to the selected MIDI input in Preferences > I/O, you might get something like this. Not sure why the "spam notes" are in a different octave though.

So, you could check what you have in Preferences > I/O, and you could try turning of MIDI input in the ⚙️ menu in the playback toolbar (top right corner of the window).

**Comment by Burke-Maester** [comment]
Okay, so after turning my MIDI settings to "no devise," that fixed it. 

Thank you both for your help!
