### ISSUE TITLE
[MU4 Issue] Inserting measures before measure 1 may keep clef and key signature in previous first measure

### ISSUE THREAD

**Issue by aige02** [musescore/MuseScore#16116]
In both 3.6 and 4.0:
I created a score in 3.6, then decided to add an intro, so I inserted 8 measure before the first measure. The result was that measure 9 had clefs and key signatures. Without saving, I then opened the opened the score in 4.0 and inserted the 8 measures with the same result. I've attached the 4.1 version of that file.

I would guess that the initial clef and key signature are associated with measure 1 instead of with the score. If so, the simple solution would be to move, rather than copy, those from the original to the newly-inserted first measure.

Originally reported as above in [#343325](https://musescore.org/en/node/343325) with attached file [Mi Chamocha-Grosky-4.1.mscz](https://musescore.org/sites/musescore.org/files/2023-01/Mi%20Chamocha-Grosky-4.1.mscz).

The solution is probably to move the clef and key signature rather than copying them.

This may be related to a similar problem when appending at the end and the final barline is duplicated instead of being moved.  There, a check should be made for the final barline being in the last measure or before something like a section break.  If so, then the final barline should be moved.

**Comment by oktophonie** [comment]
Very similar to https://github.com/musescore/MuseScore/issues/13917 which was also rather mystifying. Reproducible, though.
