### ISSUE TITLE
[MU4 Issue] Multi-measure rests display measure numbers incorrectly

### ISSUE THREAD

**Issue by jabenc** [musescore/MuseScore#16115]
**Describe the bug**
If "Show measure number range at multimeasure rests" is enabled, the range will be written incorrectly.

**To Reproduce**
1. Open a part with a multimeasure rest
2. Go to Format, Style, Measure Numbers, and check "Show measure number range at multimeasure rests"

**Expected behavior**
The correct measure numbers should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/62657351/215286066-26a633c0-2023-4b9c-9b4f-163e9cc8a8c2.png)

**Platform information**
 - OS: Windows

**Comment by cbjeukendrup** [comment]
This looks like a special case of #15635, which has been fixed. You can try the latest nightly build from the master branch to verify the fix: https://musescore.org/en/nightly-builds
