### ISSUE TITLE
[MU4 Issue] CLI. trim-image fails or doesn't produce the expected result

### ISSUE THREAD

**Issue by harleylara** [musescore/MuseScore#16118]
**Describe the bug**
I am trying to export from `.musicxml` into `.png` using the CLI and the operation **fails** or does **not produce expected** result.

**To Reproduce**

1. This command doesn't work at all and doesn't produce any errors.
```
musescore4 "C:\test.musicxml" -o "C:\test.png" -T 0
```

2. As a reference the above operation using `musescore3` works perfectly.
```
musescore3 "C:\test.musicxml" -o "C:\test.png" -T 0
```

3.  Replacing **backslash** `\` with **forward slash** `/` in the path, produces the image but **without transparency** and **without trimming**.
```
musescore4 "C:/test.musicxml" -o "C:/test.png" -T 0
```

4. As a reference, the operation with **forward slash** `/` works works perfectly again in `musescore3` .
```
musescore3 "C:/test.musicxml" -o "C:/test.png" -T 0
```

**Platform information**
Windows 11 Home
Version	22H2
OS build	22621.1105

**Additional context**
This behavior makes it impossible to use the beautiful engraving of MuseScore4 due to the operations described above are fundamental to render musical notation in [music21](http://web.mit.edu/music21) (toolkit for Computer-Aided Musicology).

Thank you for your incredible work with MuseScore.
- Harley Lara

**Comment by cbjeukendrup** [comment]
Hi! Could you please check if this issue still occurs in the latest nightly builds of MuseScore 4.1? https://musescore.org/en/nightly-builds
I think there is a chance that this has been fixed.

**Comment by feuerbart** [comment]
Checked the latest nightly build on Manjaro Linux, still does not produce expected result. Image will be created but -T 0 is ignored.

` ./MuseScoreNightly-latest-4.1.0-x86_64.AppImage AlleMeineEntchen.xml -o entchen.png -T 0`

**Comment by cbjeukendrup** [comment]
@harleylara @feuerbart Could you please test if #18754 fully solves the issue?
