### ISSUE TITLE
[MU4 Issue] Renaming my account isn't reflected on the app's account tab

### ISSUE THREAD

**Issue by Rekkonnect** [musescore/MuseScore#16123]
**Describe the bug**
Renaming my account isn't reflected on the app's account tab

**To Reproduce**
1. Create a new account from the account tab in the start screen of MU4
  - I specifically created my account using my Google account, and I wanted to adjust the default name my account was provided
2. Open account settings on the browser
3. Rename your account

**Expected behavior**
The app updates the account's name after the successful rename, like it automatically does when creating the new account from the prompt.

**Platform information**
 - OS: Windows

**Additional context**
I'm a brand new user, created my account using my Google account

**Comment by zacjansheski** [comment]
It does update when you close and re-open the program.
