### ISSUE TITLE
[MU4 Issue] Offsets are not preserved (or correctly applied) when changed via the Properties panel

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#16124]
**Note**: these issues appear to be an unintentional consequence of changes made in https://github.com/musescore/MuseScore/pull/15970

**Describe the bug**
Three interrelated issues:
1. Offsets applied to some items via the Properties panel are not preserved when the file is saved, closed and reopened;
2. Changing the offset of some items which are attached to chords (e.g. articulations, accidentals) via Properties moves the whole chord, rather than only the selected item;
3. Changing the offset of some items (e.g. fermata) via Properties seemingly has no effect.

All of these problems only occur when Properties is used to change the offsets (either by typing numbers in, or clicking up/down). They do _not_ occur when the selected item is moved around either by dragging with the mouse or with the cursor keys.

Also, if the item is _first_ moved with the mouse or cursor keys, and _then_ offsets are specified in Properties, this also prevents all of these problems. It is only when the first (and only) offsets are changed via Properties that these issues occur.

**To Reproduce**
Steps to reproduce the behaviour:
First, create a score such as this (with a note with an articulation and fermata, and a tempo):
![image](https://user-images.githubusercontent.com/20604032/215329202-9f455be7-f801-4570-93b4-8bad9d8ea4e2.png)

### 1. Offset changes not preserved through save/close/reopen
- Select the tempo and, using the Appearance popup in the Properties panel, change the X and/or Y offsets (either by typing numbers in, or clicking up/down).
![image](https://user-images.githubusercontent.com/20604032/215329436-2e98e045-55e5-494c-8f8e-aaea862ee711.png)
- Save and close the file
- Reopen the file, and note that the tempo now has a 0,0 offset and has returned to its default position. (If changing the offset caused the 'Minimum distance' to change, this change will be preserved.)

This seems to affect other text styles as well, not just tempo markings. It may affect other item types too.

### 2. Offsetting attachments to chords moves entire chord
- Select the accent articulation and change the offset via Properties
- Note that this causes the entire chord to move (except for the fermata):
![image](https://user-images.githubusercontent.com/20604032/215329944-98ca05a5-8f5b-4665-8fad-2ef7a224ab88.png)

(These changes _will_ persist through save/close/reopen).

### 3. Some items cannot be offset
- Select the fermata and change the offset via Properties
- Note that the fermata does not move, even though the values change

**Expected behaviour**
Changing the offset of an item via Properties should behave the same was as changing it by moving it using the mouse or cursor keys does (and, obviously, should persist through save/close/reopen).

**Platform information**
OS: Artix Linux, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-230191918, revision: github-musescore-musescore-39b40ed

**Comment by DmitryArefiev** [comment]
Retested on Win10
