### ISSUE TITLE
[MU4 Issue] Saved files don't retain their modified volume and panning

### ISSUE THREAD

**Issue by innerthought** [musescore/MuseScore#16126]
**Describe the bug**
More often than not when I save a score and open it again all the volume and panning settings revert to zeros

**To Reproduce**
1. Open a new score.
2. Develop it adding new instruments and adding special volume and panning settings for them.
3. Save the score (either by CNTRL+S, or by "Save", or by "Save as..." giving the file a new name.
4. Close the score.
5. Open it again - most likely to see that all the volume and panning settings are gone.

**Expected behavior**
Having saved files that would retain their volume and panning set up during the latest editing session.

**Screenshots**
–

**Platform information**
OS: Win-10, 64-bit operating system, x64-based processor

**Additional context**
This doesn't happen all the time, but at least in my case it happens every third or fourth time and it is rather annoying.
[EDIT of 2023.02.05] Here is one score that "lost" all its specified volumes and panning (earlier, the trombones were set to be much softer):
[testing_03.mscz.zip](https://github.com/musescore/MuseScore/files/10609043/testing_03.mscz.zip)

**Comment by scorster** [comment]
Tried twice on MacOS.

Found no issue when I:

1. Open an existing score
2. Change pan and volume in Mixer
3. Save or Save As
4. Quit
5. Reopen

Results all pan and volume setting in tack.

**Comment by MarcSabatella** [comment]
Same,  If you have a specific file where this happens and precise steps to reproduce the problem (eg, exactly which volume or pan settings to make to exactly which instruments), please post them.

**Comment by innerthought** [comment]
> Same, If you have a specific file...

Here is one score that "lost" all its specified volumes and panning (earlier, the trombones were set to be much softer):
[testing_03.mscz.zip]
(just added this file to the first message)

(https://github.com/musescore/MuseScore/files/10609043/testing_03.mscz.zip)

**Comment by cbjeukendrup** [comment]
Does this still happen in the nightly builds of MuseScore 4.1? https://musescore.org/en/nightly-builds

**Comment by innerthought** [comment]
> Does this still happen in the nightly builds of MuseScore 4.1? https://musescore.org/en/nightly-builds

-- Yes, from time to time. Not all the time.

**Comment by MarcSabatella** [comment]
My best guess is the problem was that the score was never correctly saved in the first place due to a bug like https://github.com/musescore/MuseScore/issues/16549, where changes made in the mixer wouldn't always mark the score "dirty" and hence saving would not do anything.
