### ISSUE TITLE
[MU4 Issue] [Workspaces] UI glitch in workspaces window when adding too much workspaces

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#16125]
![Capture](https://user-images.githubusercontent.com/90187801/215351270-3000b99d-1c96-4b94-b1bc-43ebc63eb9a2.PNG)
![Capture2](https://user-images.githubusercontent.com/90187801/215351278-4b9f14f0-dbc8-47a5-860a-bbb62986fd42.PNG)

https://user-images.githubusercontent.com/90187801/215351289-7bd692f6-09b0-4e15-a153-e6f5e417f696.mp4

**Platform information**

 macOS, Windows, Linux

**Comment by octopols** [comment]
I would like to work on this issue, can someone please assign it to me?

**Comment by octopols** [comment]
I'll work on this as soon as my classes ends
