### ISSUE TITLE
[MU4 Issue] New parts with slashes in their name are deleted when reopening score

### ISSUE THREAD

**Issue by dxing97** [musescore/MuseScore#16127]
**Describe the bug**
Creating a new part with a custom name that includes slashes works fine, but when the score is reopened, the part is missing. A new empty part is there instead, and its title is everything after the last slash in the original custom part. 

**To Reproduce**
1. Create a new score using one of the orchestra templates.
2. Click on "Parts"
3. Click on "Create new parts"
4. Double click the new part and name it something like "1/2/3/4"
5. Add instruments to the part
6. Save and close the file
7. Reopen the file
8. Check the list of parts, the original "1/2/3/4" part is gone and a new blank part titled "4" is there. 

**Expected behavior**
Parts with slashes in the title to save correctly. 

**Platform information**
OS: macOS 12.5, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

**Additional context**
May be related to https://musescore.org/en/node/316224 and https://github.com/musescore/MuseScore/pull/7313

**Comment by DmitryArefiev** [comment]
@bkunda The issue still occurs but it will be covered by #14477

Closing as duplicate

@dxing97 Thanks for logging! I'll add your case to #14477
