### ISSUE TITLE
MS4 ne fonctionne pas

### ISSUE THREAD

**Issue by Bobinique** [musescore/MuseScore#16131]
sous Windows 10
Bonjour,
Voilà plusieurs fois que je tente de télécharger votre nouveau logiciel.
La toute première fois j'ai pu ouvrir ne partition (qui s'est trouvée corrompue car j'ai dû la refaire avec MuseScore3.Ensuite le programme ne s'est plus jamais ouvert.
Je viens d'essayer à nouveau : le programme ne s'ouvre même pas sur mon ordinateur. Je l'ai donc donc à nouveau supprimé.
J'espère que vous conserverez MuseScore3 qui par ailleurs me donne entière satisfaction.
Merci du maintien de ce programme. |
Bobinique

**Comment by oktophonie** [comment]
Closing as lacks information to reproduce or investigate, but feel free to file a new issue with more specific details if you are still having problems.

**Comment by cbjeukendrup** [comment]
It looks like another report of those numerous crashes-on-launch on Windows related to the audio engine, which have been fixed recently and the fix will be included in 4.0.2.
