### ISSUE TITLE
[MU4 Issue] When the Mixer is undocked: Spacebar keystrokes toggle Mute or Solo (extant issue from MS3)

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#16148]
**Describe the bug**

A spacebar keystroke in the Mixer should toggle playback state, not the state of mixer controls. A fix was made when this was reported, but the fix only works when the Mixer is docked.

**To Reproduce**

    • Open a default New Score
    • Click Done
    • Undock the Mixer
    • Press the Mute button in the Piano (track 1) channel strip
    • Press spacebar

      Result: MuseScore toggles the Mute button rather that toggle playback on/off.

Dock the Mixer

      Result: Same behavior

Close and reopen mixer

      Result: Issue temporarily resolved

Undock Mixer:

      Result: Issue recurs

**Expected behavior**

When the Mixer is focuses, docked or undocked, a spacebar stroke should toggle playback, not the state of the last clicked Mute or Solo button.

**Platform information**
 - MacOS Ventrua 13.1; MuseScore 4.01

**Original forum post:**

https://musescore.org/en/node/318872#comment-1170339

**Comment by zacjansheski** [comment]
I am currently unable to reproduce this, is it resolved?

**Comment by MarcSabatella** [comment]
I had been able to reproduce (on Linux) back when first discussed in the forum, but I cannot reproduce now.

**Comment by scorster** [comment]
Just noticed these comments four months later!

I tested in MS4.1 with the Mixer undocked and a spacebar keystroke no longer toggles Mute or Solo.

Kudos!
