### ISSUE TITLE
[MU4 Issue] [Inspector] Text line spacing is missing in Properties

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#16141]
**Describe the bug**
Line spacing option is missing in Properties in MS4

![Capture](https://user-images.githubusercontent.com/90187801/215545419-92324ed8-5a13-4cbc-97a0-04de615a7558.PNG)

https://user-images.githubusercontent.com/90187801/215545609-7a2afd79-4ca0-48c2-a4d3-435ace9a9974.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MS3**

**Comment by DmitryArefiev** [comment]
@bkunda Maybe some design is needed here

**Comment by bkunda** [comment]
> @bkunda Maybe some design is needed here

@DmitryArefiev This is my suggestion:

<img width="300" alt="Text_More_Popup" src="https://user-images.githubusercontent.com/86290556/216944007-9c7f42d9-6895-4e40-bda4-94d52c6769b6.png">

Giving the spin box it's own space allows the possibility for us to add further typographical controls to that area in future (should we ever decide to do this). It also keeps this control out of the way of the other options (frame options expands out, for example). 

Hope that helps!

**Comment by DmitryArefiev** [comment]
@bkunda Cool! Thanks!

**Comment by octopols** [comment]
I want to work on this issue, can someone please assign it to me?

**Comment by octopols** [comment]
https://user-images.githubusercontent.com/90182257/218280994-6f4bb3cd-0ae9-43e7-9539-f04bb8301405.mp4

**Comment by DmitryArefiev** [comment]
Retested on Win10
