### ISSUE TITLE
[MU4 Issue] Cannot click property popups (2nd screen and maximized)

### ISSUE THREAD

**Issue by Jojo-1000** [musescore/MuseScore#16145]
**Describe the bug**
When the MuseScore window is maximized on my second monitor, I cannot click on menu popups. Instead they close as if I clicked behind them. Hover events seem to work though as the buttons are highlighted correctly.

**To Reproduce**
1. Open MuseScore 4 with 2 monitors. Maximize the window on the right side monitor (which is my main monitor).
2. Click something that opens a popup in the properties panel.
3. Click anywhere on the popup, on a button or just empty background.
5. The popup closes as if I clicked next to it.

**Expected behavior**
The mouse clicks should not close the popups and instead activate the UI elements or do nothing.

**Screenshots**
Here are some screenshots of popups that work and do not work (all with the window maximized on my right screen):

🟥  This popup closes when clicked:

![popup in properties that does not work](https://user-images.githubusercontent.com/33495614/215596040-55151f21-8f5e-43da-8718-a010c1891aff.png)

🟩 This popup works as expected:

![popup in top bar that works](https://user-images.githubusercontent.com/33495614/215597063-656d76ce-29af-4780-b6af-63da193c3dc2.png)

🟩 Works after I moved the properties pane to the right:

![popup in properties on the right that works](https://user-images.githubusercontent.com/33495614/215599734-c5ef4b0a-e804-43ea-96e0-b28d171da104.png)

🟥 Does not work above (or below) the other tabs:
![popup in properties on the left above the tabs that does not work](https://user-images.githubusercontent.com/33495614/215600249-7f07ccf6-27b5-4c0b-881c-a7818de58161.png)

🟩 Works to the right of the other tabs:
![popup in properties on the right of the tabs that works](https://user-images.githubusercontent.com/33495614/215600430-96fbea08-acdc-413f-a376-03a8cab470ab.png)

**Platform information**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c
 - Two 2560x1440px monitors with 125% UI scaling

 

**Additional context**
I found this closed issue that might be related: #9658

If the window is not maximized, or if it is maximized on my left screen, the menus work as expected. Keyboard interaction also works as expected. None of the popups on the properties page could be clicked on.

Other popups that look similar, but work as expected:
- Customization of the top menu bar
- Add palettes menu
- Instrument settings

When I moved the properties page out of the standard tab configuration, it started working as expected. It is working when the page is floating or on the right (see screenshots). **It seems to work whenever the left side is not touching the left side of the main window** (also in tab groups, as long as it is not on the left).

For now I am going to keep it on the right side, because otherwise the properties are not usable.

**Comment by cbjeukendrup** [comment]
Possibly related to #15884, #13589

**Comment by Jojo-1000** [comment]
I built the current master branch (c43a28af558c5d719cbf05601854cc2da1100601) and I tried the recent nightly build and cannot reproduce the issues anymore. On the commit tagged v4.0.1 (9b70a8cb28c5bbeba4f1ef5610f504c2080b9ee4) the issues are the same as in my main install, so I assume this has been fixed recently.

**Comment by Jojo-1000** [comment]
Updated to 4.0.2 and the issue is fixed.
