### ISSUE TITLE
[MU4 Issue] Mixer shows soundlevels during export

### ISSUE THREAD

**Issue by CodeSpoof** [musescore/MuseScore#16164]
**Describe the bug**
When I export a FLAC audio, the mixer show the sound level as it would during playback.

**To Reproduce**
1. Open the Mixer
2. Export the score as FLAC

**Expected behavior**
Mixer not doing anything

**Screenshots**
Export progress-bar not visible for some reason, but it is there
![image](https://user-images.githubusercontent.com/42744253/215838049-c1272aad-848b-420f-90ba-0e87dddef0c3.png)

**Platform information**
 - OS: Ubuntu 22.04 (AppImage)

**Comment by Tantacrul** [comment]
I think this is a straight-up 'won't fix'.

We didn't intentionally do it but I think it's rather useful by way of explaining to the user what's going on.
