### ISSUE TITLE
[MU4 Issue] Parts & exported pdfs created from imported midis are blank

### ISSUE THREAD

**Issue by ersherin** [musescore/MuseScore#16163]
MacBook Pro Venture 12.1.
Win 11
MS 4.01.23

Opening from a midi the score appears normally messy; however, generating parts by clicking on PARTS on top of main MS window generates all blank parts. I can create a new part and assign instruments to it, and those show up normally as far as the music being populated, but the parts created from the existing score are blank, and they export as blank pdfs. Zip file with MS & exports, and midi file attached.
 

[musescore bug report.zip](https://github.com/musescore/MuseScore/files/10548879/musescore.bug.report.zip)

**Comment by cbjeukendrup** [comment]
This looks similar to #15469, which has been fixed in the master branch already. The fix will be part of the 4.1 release, and you can try it out in the nightly builds from https://musescore.org/en/nightly-builds.
