### ISSUE TITLE
[MU4 Issue] Sound Replay Bug

### ISSUE THREAD

**Issue by Sytoplis** [musescore/MuseScore#16167]
**Describe the bug**
There is a strange gittering in the playback when playing a score with a Coda Jump right after the Coda (and also the Senio)

**To Reproduce**
1. Create a Score like shown in the attached image. (It seems that the dynamics play a big role in the bug)
2. Set the piano sound to the MS Basic sound.
3. Listen to the playback

**Expected behavior**
I expected a clear and normal sounding playback of the notes without an electronic gittering sound.

**Platform information**
 - OS: Windows 10
 - using MuseScore 4

**Additional context**
I uploaded a zip with the mscz file, a pdf export and a mp3 export.
[Bug Test.zip](https://github.com/musescore/MuseScore/files/10550080/Bug.Test.zip)

**Comment by zacjansheski** [comment]
For visibility

https://github.com/musescore/MuseScore/assets/69917893/dab6d34d-2233-4048-b951-02dd10ff75d4

**Comment by DmitryArefiev** [comment]
Fixed in #20374
