### ISSUE TITLE
[MU4 Issue] Crash after select all and delete all measures (one score)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#16174]
**To Reproduce**
1. Open [segno  crash.mscz.TXT](https://github.com/musescore/MuseScore/files/10556927/segno.crash.mscz.TXT)
2. Select all
3. Delete measures

https://user-images.githubusercontent.com/90187801/216042162-d9d21beb-578a-425a-8ee4-45a895720deb.mp4

**Platform information**
macOS, Windows, Linux

**Additional context**
I **can't reproduce** it from scratch.. only on the attached score
**MS4.0.0** also crashes with that score

**Comment by cbjeukendrup** [comment]
@DmitryArefiev It turns out that the parts of this score are corrupted. (This is not detected yet, see #15988.)

I'm not sure to what extent we are supposed to fix crashes that are caused by corrupted scores.

**Comment by cbjeukendrup** [comment]
Anyway, I've created this fix: #16175 
It will let the user delete the measures without crashing, which could be a good way to get rid of the corruptions in certain cases.

**Comment by DmitryArefiev** [comment]
Fixed in #16175

**Comment by DmitryArefiev** [comment]
Retested on Win10
