### ISSUE TITLE
[MU4 Issue] Problem with note name plugin

### ISSUE THREAD

**Issue by benoitnicomette** [musescore/MuseScore#16176]
Hello.
I just tried version 4 and it is very beautiful congratulations.
On the other hand, the "Note name" plugin which allowed in musescore 3 to automatically enter the name of the notes in the right language according to the language settings of musescore no longer works in French in version 4.
Can you solve this problem please?
Here are photos attached.
Have a good day

**Comment by cbjeukendrup** [comment]
I think @Jojo-Schmitz made a fix for this just today: see https://github.com/musescore/MuseScore/pull/16172.

**Comment by Jojo-Schmitz** [comment]
A partial fix at least

**Comment by benoitnicomette** [comment]
Thank you for your reply.

Unfortunately the text still does not appear in French notation "Do - Ré -
Mi etc ..." as it was the case in musecore 3, but in US notation "C - D - E
-etc .." only.

Cordially

Benoît NICOMETTE




20 rue Gerbault - 51100 Reims
*Tél* : 06.60.18.57.29
*e-mail* : ***@***.*** ***@***.***>
*Site internet* : www.emgerbault.org


Le mer. 1 févr. 2023 à 16:14, Joachim Schmitz ***@***.***> a
écrit :

**Comment by Jojo-Schmitz** [comment]
Really with that fixed plugin?

**Comment by cbjeukendrup** [comment]
(@benoitnicomette To clarify: the fix is not yet included in MuseScore itself; you would need to download Jojo's fixed version of the plugin and place it in your user plugins folder to try it out.)

**Comment by benoitnicomette** [comment]
No sorry :)

Benoît NICOMETTE




20 rue Gerbault - 51100 Reims
*Tél* : 06.60.18.57.29
*e-mail* : ***@***.*** ***@***.***>
*Site internet* : www.emgerbault.org


Le mer. 1 févr. 2023 à 16:34, Joachim Schmitz ***@***.***> a
écrit :

**Comment by Jojo-Schmitz** [comment]
;-)

**Comment by benoitnicomette** [comment]
Hello Joe.
Where can I find the download link please?

**Comment by Jojo-Schmitz** [comment]
De rien. ;-)

**Comment by benoitnicomette** [comment]
😀👍🙏
