### ISSUE TITLE
[MU4 Issue] Seems like all processing tasks are run on the gui-thread, making the interface freeze constantly.

### ISSUE THREAD

**Issue by TheWing** [musescore/MuseScore#16187]
**Describe the bug**
While working on larger scores, it seems that most if not all operations are running on the same thread as gui-updates, which at least on windows means that the user interface is totally frozen during actions. As an example I'll describe workflow of rearranging instruments in a three minute piece with four string instruments, but this seems to affect pretty much all processing-heavy tasks I tried.

**To Reproduce**
1. Open the score and notice you don't like the order of instruments
2. Click and drag an instrument on the left instruments panel to move it
3. The whole interface freezes until the score updates with the new order.

**Expected behavior**
I'd expect the updates to take place after releasing an instrument to the position I want, and for the UI to keep its responsibility while the score updates, even better if the score screen showed up as greyed out or something with a clear indication that the change is processing.

**Platform information**
 - OS: At least Windows, have yet to experiment on linux

**Additional context**
This to me seems like a pretty clear case of processes not releasing the gui-thread when they work on something processing-heavy, which then causes windows to show the whole program as unresponsive.

**Comment by avvvvve** [comment]
This is a duplicate issue of #20036

**Comment by bkunda** [comment]
This is a good idea: 

> I'd expect the updates to take place after releasing an instrument to the position I want, and for the UI to keep its responsibility while the score updates, even better if the score screen showed up as greyed out or something with a clear indication that the change is processing.

We'll note this in #20036 and close the present issue as a duplicate.
