### ISSUE TITLE
[MU4 Issue] Helm synth VST3 plugin crashes MuseScore

### ISSUE THREAD

**Issue by RyanMayers** [musescore/MuseScore#16186]
**Describe the bug**
When trying to assign the VST synth [Helm, by Matt Tytel](https://tytel.org/helm/), MuseScore crashes immediately. The first time, I saw a broken, scaled-up version of Helm's control window, but I couldn't interact with it, and it crashed shortly after. After, any time I tried to load Helm, the program would crash.

**To Reproduce**
1. Load a new project with a single grand staff.
2. In the Mixer panel, assign the VST plugin Helm to that track.
3. MuseScore crashes.

**Expected behavior**
I tested on the same score and another new one to reproduce the issue, and it persisted. I tried with another VST (Surge Synth), and the program worked as expected, allowing me full control and producing sound on note entry and playback.

**Platform information**
 OS: macOS 13.0
Arch.: x86_64
MuseScore version (64-bit): 4.0.1-230121751
Revision: github-musescore-musescore-9b70a8c

**Additional context**
This was on a nearly brand-new score. The only things I did before the issue manifested was name the score and add four bars of music. I was planning to test some VSTs in MuseScore which I like to use in other DAWs now that MS4 supports VST. I don't know if this is more of an issue with that specific VST, but it has always worked in other software I use (specifically, Ableton Live 10). I will test other plugins to see if others also crash MuseScore.

**Comment by zacjansheski** [comment]
On the current master build I am able to use Helm without issue.  Could you please confirm the issue is resolved?

**Comment by RomanPudashkin** [comment]
No response, closing
