### ISSUE TITLE
[MU4 Issue] Muse Strings + Woodwinds Update causes playback and score upload to crash

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#16197]
So I've updated the Muse Woodwinds and Strings yesterday, and I actually liked how the improved legato transitions sounded.

However, when I tried to playback one of my original compositions or arrangement .mscz files, or try to re-publish them to my account with the new improved playback, the process and playback causes MuseScore to crash for some stupid reason.

Is there a way this can be fixed, and what's the cause of that to happen?

I've attached a zip file of 2 example scores:
[MuseScore Files.zip](https://github.com/musescore/MuseScore/files/10571387/MuseScore.Files.zip)

**Comment by jwmatthys** [comment]
Same problem here. Updates to MuseSounds caused me to be unable to open a score made with the older version.

Log file attached: 
[MuseScore_230204_205334.log.txt](https://github.com/musescore/MuseScore/files/10610134/MuseScore_230204_205334.log.txt)

**Comment by jwmatthys** [comment]
(Tested on both MacOS and Ubuntu)

**Comment by cbjeukendrup** [comment]
@cunningar0807 @jwmatthys Does this still happen with the latest version of everything? (Muse Hub, Muse Sounds, MuseScore Nightly https://musescore.org/en/nightly-builds)

**Comment by cunningar0807** [comment]
@cbjeukendrup idk, I think it's the beta testing of 4.1 if I recall.

**Comment by cbjeukendrup** [comment]
Ok. In that case, since this is quite old already, I propose to close this. If you encounter another crash, please create a new issue. Thanks!
