### ISSUE TITLE
[MU4 Issue] "Hook height below" in Ottava style definition points the wrong way

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#16204]
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**
1. Open the Style Menu/Ottavas
2. Enter a value for "Hook height below"
3. Add an ottava bassa to the score

**Expected behavior**
The ottava should point upwards, towards the stave, but it points downwards instead.

**Screenshots**
[image](https://user-images.githubusercontent.com/116587995/216618401-45611ee3-da5d-4e8e-924c-c9b1a293b8d8.png)

**Platform information**
 - OS: Windows 10

**Additional context**
The same bug appears in MuseScore 3. Either the entry field should allow for negative input, or the hook should flip the other way.

**Workaround**
Manually edit the style file in a text editor. MuseScore interprets the value correctly.

**Comment by oktophonie** [comment]
Covered by https://github.com/musescore/MuseScore/issues/14209
