### ISSUE TITLE
[MU4 Issue] Repeat last two measures only repeats the last measure

### ISSUE THREAD

**Issue by ChriiMoral** [musescore/MuseScore#16208]
**Describe the bug**
When adding a symbol form the Repeats & jumps palette to repeat the last two measures (bars), playback only repeats the last bar (nothing plays back in the second measure).

**To Reproduce**
1. Create a new score and write two measures worth of notation.
2. Under Palettes, expand the 'Repeats & jumps' palette.
3. Drag and drop the 'repeat last two measures' symbol to the measure where the repetition is supposed to begin (alternatively, select that measure and then click on the symbol).
4. Playback your notation.

**Expected behavior**
The symbol would trigger the playback of the amount of measures corresponding to the symbol.

**Platform information**
 - OS: Windows 11

**Additional context**
Change the time signature does not affect whether or not the issues occurs. I haven't tried other repeat symbols (like the triple measure repeat).

**Comment by ChriiMoral** [comment]
https://user-images.githubusercontent.com/63615949/216683864-d3ed1f65-ae79-498f-b066-444a70355148.mp4

This video demonstrates the issue.

**Comment by Fristover** [comment]
Known issue, see #10922
Thank you for reporting though!

**Comment by ChriiMoral** [comment]
> Known issue, see #10922 Thank you for reporting though!

I tried searching for an existing issue but didn't find this. Thanks for mentioning my post in the original issue!
