### ISSUE TITLE
[MU4 Issue] Unnecessary bracket in Format /stretch window.

### ISSUE THREAD

**Issue by Tejkh1** [musescore/MuseScore#16214]
**Describe the bug**
There is a unnecessary brackets in format>stretch window .

**To Reproduce**
1. Go to '...score'
2. Click on '....format'
3. Scroll down to '...stretch.'

**Expected behavior**
There should not be braces.

**Screenshots**

**Platform information**
 -windows
<img width="589" alt="Screenshot (17)" src="https://user-images.githubusercontent.com/117664421/216783884-240183c6-8972-4fd0-be9b-f0aef7181c95.png">

**Additional context**

**Comment by cbjeukendrup** [comment]
Those are the keyboard shortcuts... 🙂
