### ISSUE TITLE
[MU4 Issue] When downloading Old-Version MSCZ files from the musescore site, they come corrupted

### ISSUE THREAD

**Issue by RotoBanana** [musescore/MuseScore#16212]
**Describe the bug**
When downloading MSCZ files from the musescore site, they come corrupted.
The shown score is apparently old, thus the code for loading old scores may need to be refined.

**To Reproduce**
1. Download a MSCZ file from the Musescore website
2. Open

**Expected behavior**
The bars and notation should be as in the musescore website, with all of the notes present, and without any visual bugs.

**Screenshots**
[Link for the bug recreation on veed.io](https://www.veed.io/view/b6148afb-8a32-4672-89b3-d24a51e514fb?sharingWidget=true&panel=download)

**Platform information**
 - Windows 10
 - Google Chrome

**Comment by cbjeukendrup** [comment]
Unless you have more examples, I think this is specific to this score (which, for reference, seems to be the one at https://musescore.com/user/19710/scores/53887). The score is indeed from a very old version; the code for reading scores from that version is maybe not in very good shape currently. Therefore it is difficult to say whether the score is really corrupted or that the corruption happens while reading the score.

**Comment by RotoBanana** [comment]
> Unless you have more examples, I think this is specific to this score (which, for reference, seems to be the one at https://musescore.com/user/19710/scores/53887). The score is indeed from a very old version; the code for reading scores from that version is maybe not in very good shape currently. Therefore it is difficult to say whether the score is really corrupted or that the corruption happens while reading the score.

Right. Thanks, I updated the issue request.

**Comment by Jojo-Schmitz** [comment]
As far as I can tell that score is corrupt already, a 4.0.2 pre-release reports it as such (see also #16657). But indeed Mu3 did not, and probably also older 4.0 releases neither

**Comment by bkunda** [comment]
Closing this for now as it does seem similar to #16672.
To be most helpful, we really need more concrete examples of scores that are being corrupted (not just "old-version MSCZ files").
