### ISSUE TITLE
[MU4 Issue] Export filetype and directory not memorized

### ISSUE THREAD

**Issue by BenWiederhake** [musescore/MuseScore#16215]
**Describe the bug**

When exporting a file several times in a row, the format is always reset to PDF, and the directory (for the filepicker dialog)is always reset to the directory containing the current `.mscz` file. This makes it needlessly difficult to re-export a file over and over again, for example when making slight incremental adjustments and seeing how the output has changed. (In my case: I wanted to tweak the score such that the generated FLAC-file has just the right length for a particular usage.)

**To Reproduce**
1. Open MuseScore
2. Write a few notes (probably optional, but just in case)
3. In the menu, go to File > Export, this should open a dialog. In the dialog, select a different format (e.g. FLAC), click "export" and select a different folder (e.g. `/tmp/foobar.flac`)
4. Change/add/delete a note (probably optional; included only for realism)
5. Repeat Step 3

**Expected behavior**
The second time the export dialog opens (specifically step 5), MuseScore remembers that I just exported the score as FLAC, and the format defaults to FLAC. Likewise, it should remember which directory was just used, and suggest that directory in the filepicker.

**Actual behavior**
The second time the export dialog opens (specifically step 5), MuseScore behaves just like the first time: I have to select the FLAC format (otherwise the filepicker suggests a PDF filename extension), and I have to manually navigate to the same destination folder again.

Curiously, if I select PDF format and a destination file like `/tmp/weird.flac`, then MuseScore generates a proper FLAC, as if I had selected flac in the dialog. Weird.

**Screenshots**
This is the "export dialog" I mean:
![Bildschirmfoto_2023-02-04_23-21-57](https://user-images.githubusercontent.com/2690845/216791929-020cc5b8-8084-4513-8fe2-06a4e043bf5c.png)

**Platform information**
 - OS: Linux, x64, German locale (I don't think any of these seem relevant here though)
 - Installation method: AppImage
 - Version: MuseScore-4.0.1.230121751-x86_64.AppImage

**Comment by BenWiederhake** [comment]
This can be abused for an accidental feature which I actually need right now: Selecting "Jedes Instrument in eine eigene Datei" in the PDF options (roughly translates to "each instrument in a separate file") really does produce several files with the correct instruments.

This seems highly unintentional, but right now saves me many clicks :D

**Comment by oMrSmith** [comment]
+ 1 (related to #16032)

**Comment by HemantAntony** [comment]
@DmitryArefiev I have made a PR: #16315

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev I have made a PR: #16315

@HemantAntony Thanks! I tested on Windows and left a comment there

**Comment by DmitryArefiev** [comment]
@Tantacrul @bkunda  This should be designed 

In my opinion, 
1. The first time Export dialog opens, it should show the same location as the score file has
2. **Directory** should memorized only during one MU session (several scores can be opened during one MU session). The next time MU runs it should respect rule №1
3.  **Export filetype** should memorized only during one MU session (default PDF is mostly common used). I'm **not sure** about this one (rule №3)

**Comment by Tantacrul** [comment]
I think I agree with all of those.

The most important thing is (for example) if a user selects **mp3** and chooses a different directory, then we should remember both those defaults the next time the choose the export dialog within the same session.

I assume we're all agreed on that but thought I'd check!

If we're happy, feel free to check @HemantAntony's PR, sign it off when it's ready and then ask one of the devs to review.

Thanks a lot @DmitryArefiev, @HemantAntony @BenWiederhake

**Comment by oMrSmith** [comment]
Guys, on this occasion 
would you perhaps also look into #13242 ?

**Comment by cbjeukendrup** [comment]
That's a completely different issue with a completely different fix.

**Comment by Tantacrul** [comment]
> Guys, on this occasion would you perhaps also look into #13242 ?

This appears to be a completely unrelated issue. Can you **please** not do that? It is incredibly time-wasting.

1. ONE issue per bug
2. No commenting irrelevant stuff on bugs that forces us to have to edit it and then issue this comment.

**Comment by Tantacrul** [comment]
@oMrSmith 

Another thing we request you don't do: no **pestering**.

"why isn't this done", "this isn't yet solved", etc. I hope it is obvious why this is time wasting and bothersome to others.

**Comment by oMrSmith** [comment]
@Tantacrul I asked a question in a polite way and regret that this has wasted your time so that I will refrain from commenting things that are not directly related to the issue in the future as you wish. I don't remember to have done "pestering" though.

**Comment by Tantacrul** [comment]
Well, if you don't think you are pestering, then I understand it may not seem like it to you.

But imagine it from our POV: we're trying to manage a ton of work, which includes a ton of bug triage. Then we get an email notification that essentially reads: **_'Can I remind you to solve at this issue again, even though it has already been triaged'._**

This is why I keep emphasising:

- Only comment when a comment forwards our understanding of how to solve the issue
- Do not post irrelevant stuff
- Do not reming us that an issue exists if we've already triaged it

**Comment by HemantAntony** [comment]
@DmitryArefiev I updated the PR. Can you test it again? :)

Currently, It now saves both the export format and export path for that score and that session. I was wondering if you want it to also save other data such as sample rate, bitrate for MP3 and similarly for other export formats. Also should I save what all parts were exported

![image](https://github.com/musescore/MuseScore/assets/88136054/5481de5a-6ae9-4c92-af80-cd1ffae63196)

@Tantacrul too

**Comment by Tantacrul** [comment]
Regarding specific output settings: 

I'd suggest that we should save them but only during a session. We shouldn't remember those settings when a user closes and reopens MS4.

@bkunda - whatayouthink?

**Comment by Tantacrul** [comment]
I have no problem with that idea. @cbjeukendrup.

Let's do that then.

**Comment by HemantAntony** [comment]
Okay, should those settings be the same for every score or only the score you saved it on? @Tantacrul @cbjeukendrup

**Comment by Tantacrul** [comment]
I don't think we should have different settings per score. I'd keep it global. In that way, it's clear to the user how it works.

**Comment by shoogle** [comment]
If we persist some settings beyond the session then I think we'll probably want a way to reset those settings back to their default values.

It wouldn't hurt to be able to reset the dialog within a session either, but it becomes more necessary if settings are remembered into the next session.

**Comment by Tantacrul** [comment]
@shoogle - it's possible people might want it but I'd rather see if anyone has an issue with this tweak first before providing more options to reset things. Persistent settings is not uncommon and one doesn't need to output from MuseScore all that much.

**Comment by HemantAntony** [comment]
@DmitryArefiev @Tantacrul I updated the PR again. Can you test again?

**Comment by Tantacrul** [comment]
@HemantAntony. I think this is pretty good.

- There is one thing I've noticed though. In a session, if I save a PDF in a new location, subsequent attempts to export a PDF will also default to the same location, which is good.

- However, if I then try to export a different file format (mp3, wav, etc.) within the same session, the location will change to the original (factory) default location.

I think the location should be remembered not just in one session... but also across all file formats. It's very likely a user would want to export both a PDF and an MP3, and I don't think there's any need to reset the location to the factory setting each time you switch between them. Does that make sense?

**Comment by HemantAntony** [comment]
@Tantacrul Yeah that makes sense. I updated the PR again :)

**Comment by Tantacrul** [comment]
> 

@DmitryArefiev I think it should be for an **MS session**, not just a **score session**

**Comment by BenWiederhake** [comment]
Data point: I'm an amateur and like to just throw all my MuseScore files in a single directory. So whenever it switches back to the factory default location, I would have to navigate manually to "the" directory.

**Comment by shoogle** [comment]
@BenWiederhake, if you want to put everything in the same place then you can set the default locations in Preferences > General > Folders.
![image](https://github.com/musescore/MuseScore/assets/11011881/c397bafc-ddef-4b9a-b61e-6b449d84041f)

**Comment by DmitryArefiev** [comment]
> > 
> 
> @DmitryArefiev I think it should be for an **MS session**, not just a **score session**.
> 
> Do you agree?

@Tantacrul Yes I do. 
If location is changed for the 1st score it should be respected for the next scores in MS session. 
But if location was not changed for the 1st score then it should use the location of each next score independently (default)

The same (probably) for file type too.

@HemantAntony Can you add that rule too please?

**Comment by HemantAntony** [comment]
@DmitryArefiev @Tantacrul I have updated the PR. Just a FYI, if you export "Score1" and then close it and open "Score2", it remembers the location of "Score1" export, but it does not remember the file name

**Comment by DmitryArefiev** [comment]
> I have updated the PR. Just a FYI, if you export "Score1" and then close it and open "Score2", it remembers the location of "Score1"

@HemantAntony The rule should be a little bit different.  
* If location **is changed** for the 1st score it **should be respected for the next scores** in MS session.
* But if location **was not changed** for the 1st score then it **should use the location of each next score independently** (default)

Also, I found a **bug** in #16215. When export any audio (MP3,WAV, FLAC, OGG) and if to click 'Open destination folder', it opens the location of Musescore.exe file

https://github.com/musescore/MuseScore/assets/90187801/ccbb76d3-11b6-49f7-97b2-83493737dcf2

**Comment by Tantacrul** [comment]
@HemantAntony

Just chatted with @DmitryArefiev. I think we can simplify those rules he mentioned in his last comment a little bit.

- If location is changed for **any score** it should be respected by the other scores in an MS session. Basically, if you change a location, it just gets remembered, regardless of the score.

**Comment by Tantacrul** [comment]
@HemantAntony - actually. Give us a minute. I think our instructions on this don't make sense. I would just stick to @DmitryArefiev's bug. Let us test this a bit more

**Comment by HemantAntony** [comment]
@DmitryArefiev can you check again? I think I fixed the bug. I checked on both Ubuntu 22.04 and Windows 11. It seems to be working

**Comment by DmitryArefiev** [comment]
Fixed in #16315
