### ISSUE TITLE
[MU4 Issue] Better fall rendering 

### ISSUE THREAD

**Issue by moogly81** [musescore/MuseScore#16246]
**Describe the bug**
Musescore4 falls are confusing. 
I experimented with different way to create falls  (see picture). Conclusion : we need a new feature. 

**Expected behavior**
Ideally, falls should be customisable : 
  - line width 
  - line type : straight/wiggly 

![fall-1](https://user-images.githubusercontent.com/2691085/217099480-0389c242-bb96-4e76-81f2-dc76c18c6af6.png)

**Comment by moogly81** [comment]
relates to https://github.com/musescore/MuseScore/issues/14878

**Comment by mike-spa** [comment]
Keep in mind that the default thickness and size of the fall was designed to look good with engraved fonts, so it is always going to look a bit too small and too thin if used with jazz fonts, like in this example. But besides that, I agree that our support for falls/bends is quite poor. I'll open a task for it, though I can't promise that it will be worked on any time soon 👍

**Comment by mike-spa** [comment]
Closing the issue as it's been reformulated into a task.
