### ISSUE TITLE
[MU4 Issue] Musescore crashes and closes when it plays a specific beat in a measure

### ISSUE THREAD

**Issue by literallyjustbeeb** [musescore/MuseScore#16249]
My score in Musescore 4 keeps crashing and closing everytime it plays a specific beat/note or rest in a specific measure or any after that (beat 3 of measure 21) it doesnt seem to be a specific instrument because it happens with all parts, it also crashes if you click on the beat or anything after it

**To Reproduce**
1. Open score
2. Play the score or skip to a few measures before 21
3. At measure 21 beat 3 (where vibraslap hits) it will crash and close the score

**Expected behavior**
I expected it to just play the note and carry on with the score

**Screenshots**
N/A

**Platform information**
 - I have a windows 11

**Additional context**
for context the original file was made with musescore 3, but when i encountered this issue on musescore 4, i actually tried to fix it by transcriving it to a new score file yet it didnt make a difference and it kept crashing.
In addition, heres the score: https://musescore.org/sites/musescore.org/files/2023-02/May%27s%20castle.mscz

**Comment by MarcSabatella** [comment]
I can confirm the crash FWIW, including using a currently 4.0.2 nightly build.

**Comment by literallyjustbeeb** [comment]
> Can you try this again after updating Woodwinds via the Hub? I think this has been fixed as part of another fix; at least, I can't reproduce on my system
> 
> 
> 
> Alternatively, if you choose the MS Basic profile (i.e take Muse Sounds out of the picture), does this still crash for you? If so, this is a MuseScore specific bug, rather than a Muse Sounds one.

Okay so as of yesterday when i checked, it started working so i believe it was fixed, i had forgotten to come back and mention this
But yes it's been fixed, which is peobably why you cant reproduce it
