### ISSUE TITLE
[MU4 Issue] Percussion cannot be merged in parts, just separated ways

### ISSUE THREAD

**Issue by GabrielYudenich** [musescore/MuseScore#16245]
**Describe the bug**
The percussion parts are always in separated parts and i cannot merge the percussion parts like in musescore 3. And when i create a new part, i cannot add any instruments inside of them

**Screenshots**
![image](https://user-images.githubusercontent.com/51841352/217064842-c3c23f3a-3f1d-409f-9364-a84ffbf055f8.png)

**Platform information**
 Windows

**Comment by jeetee** [comment]
Creating custom parts in 4 differs somewhat from 3, so make sure to have worked through https://musescore.org/en/handbook/4/parts#creating-custom-parts to learn how to add instruments (or rather "show" them) for ms4

**Comment by GabrielYudenich** [comment]
Thank you!
