### ISSUE TITLE
[MU4 Issue] Falls cannot cross barlines

### ISSUE THREAD

**Issue by moogly81** [musescore/MuseScore#16247]
**Describe the bug**
Falls can't "spill over" the next measure. More precisely, you can draw it at first, but as soon as the measure is reset (command-r), the barline is pushed further, so that the fall stays on the same measure. 

**To Reproduce**

1. add a fall to the last beat of a measure
<img width="283" alt="Screenshot 2023-02-06 at 23 35 08" src="https://user-images.githubusercontent.com/2691085/217103066-51f9f171-596b-41be-8f40-10f55546a439.png">

2. modify it so it goes over the barline
<img width="326" alt="Screenshot 2023-02-06 at 23 23 32" src="https://user-images.githubusercontent.com/2691085/217102878-c728e3d5-2fab-4a0b-91e0-24689586bf88.png">

3.  select the bar and reset shape and position (command-r)

4. **Error  : the barline has moved**
<img width="345" alt="Screenshot 2023-02-06 at 23 23 46" src="https://user-images.githubusercontent.com/2691085/217102876-659cf1e4-2c48-4a5a-9f68-b014ebfb0713.png">

**Expected behavior**
It should be possible to have falls cross over barlines

**Comment by mike-spa** [comment]
Fixed! I wouldn't expect it to be merged any time soon though. Meanwhile (I'm sure you know this already, but just in case) you can easily get around the problem by selecting the fall and disabling autoplace.
<img width="519" alt="image" src="https://user-images.githubusercontent.com/93707756/217799498-46ce81e9-4c69-4aae-9297-f6e173736dba.png">

**Comment by moogly81** [comment]
Thanks ! WOW this is so fast ! Auto-place can be disabled. But everytime auto-place is imroved, it makes musescore a tiny bit more user friendly and efficient.
