### ISSUE TITLE
[MU4 Issue] Crash when playing note with tremolo after a note with trill in woodwinds

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#16259]
**Describe the bug**
This issue couldn't be reproduced when creating new score with the same case

**To Reproduce**
1. Open the score
[Techniques.gp.zip](https://github.com/musescore/MuseScore/files/12372834/Techniques.gp.zip)

2. Play from measure 223

**Expected behavior**
No crash

**Screenshots**

https://user-images.githubusercontent.com/101250347/217277013-da131cd5-e3e2-41ee-95d1-72bc4b4ba0c0.mp4

**Comment by zacjansheski** [comment]
Is there a score to confirm this is still an issue?

**Comment by abariska** [comment]
🟢 **Can't reproduce** 
Seems like it's fixed. I can't reproduce anymore
