### ISSUE TITLE
[MU4 Issue] Problems with JuicySFplugin

### ISSUE THREAD

**Issue by Reloup38** [musescore/MuseScore#16266]
**Describe the bug**
I have a soundfont that reproduces the sound of a siren, I mapped different samples with different spool up times to MIDI velocities.
When loading this into JuicySFplugin, the different dynamics do not affect which sample is played, only the mf samples is played.
Furthermore, the realease sample (of the siren spooling down) will continue to play if it has not been fully played during play mode next time you want to listen to your score

**To Reproduce**
1. Use JuicySFplugin to load the siren soundfont (although i'm guessing this would work with a lot of different soundfonts)
2. Listen to the playback while trying to put different dynamics.
3. See error

**Expected behavior**
Different dynamics should be associated with velocity levels so that soundfonts play the appropriate samples. The bug cannot be reproduced in FL studio, so it isn't coming from the plugin.

**Screenshots**

https://user-images.githubusercontent.com/116571960/217339171-c6aa0667-4147-4d16-9f52-58420ec369ad.mp4

**Platform information**
 - OS: Windows 10

**Additional context**
The same problem occurs with another soundfont player (RF-Soundfont), except the release problem (the release sample doesn't play at all), but that comes from the plugin, not musescore, as the release sample doesn't play in FL studio either. The score and the soundfont are in the zipfile.
[test siren.zip](https://github.com/musescore/MuseScore/files/10678466/test.siren.zip)

**Comment by zacjansheski** [comment]
Is this issue still actual?

**Comment by Reloup38** [comment]
@zacjansheski i just tested it in Musescore 4.1.1 and yes, every issue described here are still actual. Musescore does not talk to juicysfplugin at all about what sample to play regarding velocity. The samples are played louder, but they are the mezzoforte ones.

**Comment by DmitryArefiev** [comment]
Partially fixed by #22953 if to use **not SND** instruments (such as Piano or Guitar). 

To have the fix worked in the attached score, Slide Whistle should be replaced with Piano

**Comment by DmitryArefiev** [comment]
Should work with **SND** instrument too (when using VST)
