### ISSUE TITLE
[MU4 Issue] Commands in command line throw "QEventLoop: Cannot be used without QApplication" error

### ISSUE THREAD

**Issue by Trolly-J** [musescore/MuseScore#16269]
**Bug description**
Whatever mscore command in command line I issue, error `QEventLoop: Cannot be used without QApplication` occurs.

**To Reproduce**
1. Open command line.
2. Issue `mscore` for example.

**Expected behavior**
Musescore app should open and it will. However when issuing commands which don't open GUI, the issued command will not work.

**Screenshots**
<img width="1250" alt="Snímka obrazovky 2023-02-07 o 23 00 58" src="https://user-images.githubusercontent.com/90610351/217376640-bb4b86e8-3247-47fc-a969-79dccf663e33.png">

There are also other errors, which I do not know, whether they have to do something with my OS configuration or MScore, but they don't have serious impact on my user experience.

**Platform information**
 - OS: MacOS Ventura 13.1 (22C65)

**Comment by Trolly-J** [comment]
Compiled MScore by myself and working well.

**Comment by cbjeukendrup** [comment]
This has been fixed in the master branch a while ago by #15818. Thanks for reporting though!
