### ISSUE TITLE
Musescore 4 will not start if using Steelseries Sonar audio routing as a default output device

### ISSUE THREAD

**Issue by Marora44** [musescore/MuseScore#16278]
**Describe the bug**
When using Steelseries Sonar for audio routing Musescore 4 will not get past the splash screen unless the default audio output of the computer is not one of the virtual audio devices provided by Sonar

**To Reproduce**
1. Install Steelseries Sonar
2. Set the default windows audio output to one of the Steelseries channels (game, chat, media)
3. Open Musescore4
4. Application will show splash screen but will not open

**Expected behavior**
The application should open correctly

**Platform information**
 - OS: Windows 11 64-bit

**Additional context**
I have used this with another audio routing software (ElGato Wave Link) in the past with no issues so as of right now this issue is exclusive to SteelSeries for me

**Comment by cbjeukendrup** [comment]
Hi! Could you please try if the build from https://github.com/musescore/MuseScore/suites/11044663711/artifacts/561149134 works correctly?

**Comment by cbjeukendrup** [comment]
@Marora44 Does this still happen in MuseScore 4.0.2?

**Comment by cbjeukendrup** [comment]
Closing due to irresponsiveness and because it's most likely fixed in the next update
