### ISSUE TITLE
[MU4 Issue] In English Horn, the notes above D are not played.

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#16283]
In English Horn, the notes above D are not played.

Transposed Note
![image](https://user-images.githubusercontent.com/1835871/217643923-b1f182d4-a7f4-494b-b520-27e53d5253b3.png)

Real notes
![image](https://user-images.githubusercontent.com/1835871/217645390-9ebc544c-ad22-4cb7-b0e5-31efb25356d0.png)

Range of English Horn
![image](https://user-images.githubusercontent.com/1835871/217644368-186308b0-a5f6-4445-9a5a-9df7f73d9f21.png)

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230350507, revision: github-musescore-musescore-aabbec1

**Comment by oktophonie** [comment]
Covered in https://github.com/musescore/MuseScore/issues/16244
