### ISSUE TITLE
[MU4 Issue] Dragging a note within a chord to change its pitch removes any of its accidentals 

### ISSUE THREAD

**Issue by Rekkonnect** [musescore/MuseScore#16299]
**Describe the bug**
Dragging a note within a chord to change its pitch removes any of its accidentals

**To Reproduce**

1. [Optional] Use a key signature other than C major/A minor
2. Place a note anywhere in the piece
3. Add an accidental to the note
4. Drag the note upwards or downwards to change its pitch
    - Avoid passing through an accidented pitch from the key signature or the same measure
5. The accidental is removed and never brought back, even if dragging back to the original pitch of the note
    Additionally, the accidental selection on the toolbar remains selected until the note is deselected, where its state properly resets.

**Expected behavior**
The accidental is preserved, like it would be on a single note (not a chord).

**Platform information**
 - OS: Windows

**Additional context**
I'm composing a piano solo, and using a single voice for the instrument, and two staffs, one with a treble clef and one with a bass clef as usual.

**Comment by Panogen** [comment]
I think that's the expected behavior. It's how it worked in MU3 iirc. I also don't think it's any different with single notes than with chords (I just tested it on my system—it also removes accidentals on single notes, regardless of the key signature).

**Comment by Rekkonnect** [comment]
On single notes it didn't remove the accidentals for me, as long as both staffs only contain one note in the same time

**Comment by oktophonie** [comment]
So there _is_ some inconsistency here, which I'll try to explain as clearly as I can.

As far as I can tell, an accidental on a note - whether a single note or a note in a chord - always disappears when you drag the note up or down, _except_ when:

- the accidental is a natural, _and_
- that natural was added 'explicitly' (i.e. outside note input mode, by selecting a note and clicking the natural button in the toolbar, _and_
- that natural isn't cancelling an accidental in the current key signature (a natural on an F in G major, for example)

This just seems like an inconsistency that we should do away with. When the position of a note on a stave changes by dragging it we have no way of knowing whether its accidental is still relevant or desired. (Different logic can apply when performing some more specific operations, like moving the note up or down by an octave, for example.)

There is a second, more insidious part to this: if the above conditions are all satisfied, it seems the note gets a "please keep my accidental" flag set on it. So, if you start with a note with an 'explicit' natural on it, then change the accidental to something else (sharp, flat, whatever), that accidental will _also_ be preserved when the note is dragged.

There is another inconsistency. In this situation:
![image](https://user-images.githubusercontent.com/20604032/221160716-9cb1e79d-490b-4ea3-8c45-c2ab5de1a223.png)
(the natural is not 'explicit' but that doesn't make a difference)
if I drag the F natural away, the natural disappears, but it will _reappear_ if I drag it back to the same F position (though not to any other F)

However, in this situation:
![image](https://user-images.githubusercontent.com/20604032/221161308-d89c7227-65d3-4c9e-b13f-67a5d9c44793.png)
if I drag the F natural away, the natural disappears, but does _not_ reappear if I drag it back to the same F position.

Your point about the toolbar not updating is quite correct. So I'd recommend:

- when a note is dragged, the accidental is always lost, in every circumstance
- the toolbar should, likewise, update immediately as soon as the accidental goes

There are, maybe, reasons to preserve an accidental in specific circumstances, but if these exist it should be able to define them specifically enough that they don't just feel inconsistent to the user.

**Comment by Tantacrul** [comment]
> - when a note is dragged, the accidental is always lost, in every circumstance
> - the toolbar should, likewise, update immediately as soon as the accidental goes

Agree. Un-assigning myself because I think this instruction is a clear design.
