### ISSUE TITLE
[MU4 Issue] "Da Coda" and "Da Double Coda" marks have 'Jumps' element type instead of 'Markers'

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#16294]
**Describe the bug**
For more info read comments here https://github.com/musescore/MuseScore/pull/16263

**Expected behavior**
"Da Coda" and "Da Double Coda" marks have 'Markers' element type

**Screenshots**

**Comment by Jojo-Schmitz** [comment]
Wouldn't "Da Double Code" rather need to be Da Doppio Coda" i.e. fully Italian?

**Comment by Jojo-Schmitz** [comment]
Or, to match the "To Coda", make it "To Diouble Coda".
Or change the "To Coda" (and the "To codasymbol" to use "Da" as well

**Comment by abariska** [comment]
@Jojo-Schmitz It will be reviewed in future and may be deleted some of them but for now they just should work correct

**Comment by Jojo-Schmitz** [comment]
Yes, matter of priorities, understood
