### ISSUE TITLE
[MU4 Issue] Palettes dissapeared from palettes panel

### ISSUE THREAD

**Issue by PetJer** [musescore/MuseScore#16321]
**Describe the bug**
I was just working in Musescore and somehow when I toggled to the palettes ribbon I saw this.

![no-palettes-found](https://user-images.githubusercontent.com/79419198/218278812-36d22272-102d-4c93-90d2-5ae436a1dc9e.png)

As the message suggest there's probably an issue with the search bar (I was playing with it for some time before it happend).

**To Reproduce**
I have no clues, the only way to get the palettes back is to restart Musescore.

**Expected behavior**
That just shouldn't happen.

**Platform information**
 - OS: Windows 10

**Comment by cbjeukendrup** [comment]
I think I found a way to reproduce:
1. Start searching in the Palettes
2. Close Palettes
3. Re-open Palettes
→ the Palettes are still in a state as if you are searching; so either it says "no results found", or you see the list of palettes that matched the latest search text, which may contain palettes that are normally hidden or may miss palettes that are normally visible.

Also, in the latter case, if you expand a Palette by clicking its ▶︎ button, and then click the "More" button inside the palette, a crash occurs.

**Comment by PetJer** [comment]
Uff, that was fast! And yes I remember closing the palettes by mistake when I was trying to undock it.

**Comment by DmitryArefiev** [comment]
Fixed in #16683
