### ISSUE TITLE
[MU4 Issue] Trumpet part don"t play with MuseSound. Ok with MS Basic

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#16332]
Trumpet part don"t play with MuseSound. Ok with MS Basic

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230430507, revision: github-musescore-musescore-a36e598

**Comment by Fristover** [comment]
Any more info on this? I didn't really get what the issue is specifically

**Comment by Gai-Luron** [comment]
Nothing special to say. Look at score. Flute play, trumpet no

[Trumpet Issue.zip](https://github.com/musescore/MuseScore/files/10716417/Trumpet.Issue.zip)

**Comment by Fristover** [comment]
It... plays fine here, I would check the Muse Brass installation, worst case reinstalling it as I can't reproduce your issue

**Comment by Gai-Luron** [comment]
I try to reinstall Muse Hub and Sound

**Comment by Gai-Luron** [comment]
Hello,
Work Now. Strange it's a fresh last week  install from scratch of windows and Apps.Sounds work fine 
It was working fine until today
Strange,..
Thank you very much
I close this issue
