### ISSUE TITLE
[MU4 Issue] Converting to mscz on the command line results in zero-sized output files.

### ISSUE THREAD

**Issue by kbloom** [musescore/MuseScore#16334]
**Describe the bug**
Converting to mscz on the command line results in zero-sized output files. 

**To Reproduce**

1. Find a score, e.g. https://github.com/kbloom/sheetmusic/blob/master/Agadelcha.mscz
2. mscore Agadelcha.mscz -o Agadelcha.mscz
3. ls -l Agadelcha.mscz

The resulting file has zero size.

**Expected behavior**
A valid mscz file should be output at Agadelcha.mscz

**Platform information**
Manjaro Linux running the Manjaro package of Musescore 4.0.1

**Additional context**
In this example, I attempt to upgrade a file from Musescore 3 format to Musescore 4 format. However, this also happens when the input is a Musescore 4 file. This happens when the output format is mscz. When the output format is pdf instead, a valid pdf is created. This also happens when the output file has a different  name than the input file.

**Comment by kbloom** [comment]
Since I just reread my bug description, and thought it might be confusing, I wanted to clarify.

 I get a zero file size when:

1. Converting Musescore3 file to Musescore 4 file.
2. Converting Musescore4 file to Musescore 4 file (which one might want to do if they were applying a new stylesheet to the score)
3. Doing the above conversions when the output file has a different name from the input file.
4. Doing the above conversions when the output file overwrites the input file.

The conversion is performed correctly when converting to another file format, such as PDF.

**Comment by helpy** [comment]
Confirmed!
The same happens if I try to convert a mxl file to a mscz file with MuseScore4.
The same command line works with MuseScore3.

**Comment by Eism** [comment]
@kbloom @helpy 
Please check the build from this PR https://github.com/musescore/MuseScore/pull/16461

**Comment by kbloom** [comment]
I have tested your Linux build artifact on a bunch of my scores, and it works.

**Comment by kbloom** [comment]
This didn't get pulled into 4.0.2, did it? Could it get pulled into 4.0.3 if there is a 4.0.3?
