### ISSUE TITLE
Arpeggios mess time of the next note  

### ISSUE THREAD

**Issue by Dies-Irae** [musescore/MuseScore#16330]
The time of notes are incorrect after a arpeggio (8th notes sounds like 16th).

**To Reproduce**
Place notes as the attached video

**Platform information**
 - OS: Windows 10

https://user-images.githubusercontent.com/30491121/218311942-b3a82b68-d373-408a-a529-429d9adc2395.mp4

**Comment by Dies-Irae** [comment]
The problem is caused by Muse Keys. I was using the "Grand Piano" in the video. The problem disappears when I switch to MS Basic

**Comment by xsrvmy** [comment]
I'm running into a different related problem: when using sound fonts or VST, the key up event is delayed on the upper notes causing the next note to be cut off instead.

**Comment by DmitryArefiev** [comment]
Fixed in #20243
