### ISSUE TITLE
[MU4 Issue] Installing MuseHub on Windows throws an error

### ISSUE THREAD

**Issue by Lynzzyr** [musescore/MuseScore#16347]
**Describe the bug**
When trying to install MuseHub on Windows 11, it fails to install and gives an error.

**To Reproduce**
1. Download the latest MuseHub installer. (4.0.1)
2. Run the installer.
3. Wait a bit after the installation window appears.

**Expected behavior**
MuseHub should simply install with no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/66968682/218488936-89b74dcf-dbfe-47da-87ed-6405f21d1417.png)

**Platform information**
Windows 11 21H2

**Additional context**
The log that was created following this error:

|LOG|: [.NET Runtime] Checking to see if .NET Desktop Runtime 6.0.9 is installed...
|LOG|: [Resource Extractor] Attempting to extract EXE_NETCORECHECK to a temporary location (C:\Users\sree\AppData\Local\Temp\Muse Installer Temp\EXE_NETCORECHECK.EXE)...
|LOG|: [Process Runner] Executed "C:\Users\sree\AppData\Local\Temp\Muse Installer Temp\EXE_NETCORECHECK.EXE": Success!
|LOG|: [.NET Runtime] .NET Desktop Runtime 6.0.9 is installed!
|LOG|: [MSIX] Found Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe. Version: 14.0.29016.0. But this does NOT match the minimum required version of 14.0.30704.0!
|LOG|: [MSIX] Found Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe. Version: 14.0.30035.0. But this does NOT match the minimum required version of 14.0.30704.0!
|LOG|: [MSIX] Found Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe. Version: 14.0.30704.0
|LOG|: Installing dependencies...
|LOG|: Installing Muse Hub...
|LOG|: [Resource Extractor] Attempting to extract MSIX_MUSEHUB to a temporary location (C:\Users\sree\AppData\Local\Temp\Muse Installer Temp\MSIX_MUSEHUB.MSIX)...
|LOG|: [Package Add] Preparing to add package for the current user

**Comment by oktophonie** [comment]
Muse Hub issues are now being handled elsewhere, so will be closed here.
If this issue is still valid, please raise it [here](https://musehub.zendesk.com/).
You can link to this GitHub issue if it provides useful context or discussion.
