### ISSUE TITLE
[MU4 Issue] Pizz. is not working in strings

### ISSUE THREAD

**Issue by RichardJECooke** [musescore/MuseScore#16359]
**Describe the bug**
See the attached MS4 file with a violin. Pizz. plays on only one group of notes, sometimes plays, sometimes not, and never plays on the strum.

**To Reproduce**
Play the file
[bug.zip](https://github.com/musescore/MuseScore/files/10730162/bug.zip)

**Expected behavior**
Pizz. causes all following notes to be pizzicato until insertion of arco text.

**Platform information**
Windows

**Comment by Fristover** [comment]
With further testing I narrowed down the issue:
Playing techniques (sul pont., pizz., sul tasto, tremolo, etc.) don't work (they're played as arco) on grace notes, arpeggios and tremolos (related to #14491).
This applies to every instrument both in MS Basic and Muse Sounds.

**Comment by bkunda** [comment]
Closing this as we are raising a more detailed issue that will cover everything here in https://github.com/musescore/MuseScore/issues/19266
