### ISSUE TITLE
Measure numbers are sometimes incorrect

### ISSUE THREAD

**Issue by Panogen** [musescore/MuseScore#16354]
This is a strange bug in Musescore 4 in which a measure sometimes doesn't get counted in the measure numbers:
![image](https://user-images.githubusercontent.com/73259774/218547040-0a0449c2-c99d-46c2-86e0-52b8ad361cc9.png)

When I deleted the line break at the end of the actual measure 12 and then replaced it, the problem went away:
![image](https://user-images.githubusercontent.com/73259774/218547347-7c251d49-4c46-4472-90c4-0d859d732e80.png)
![image](https://user-images.githubusercontent.com/73259774/218547502-d3933ad8-180f-4571-84c6-6af49e6c69eb.png)

But when I saved and reloaded the file, the problem returned.
![image](https://user-images.githubusercontent.com/73259774/218547900-a8626538-a2f1-4283-bbe7-f777a5468dd5.png)

I initially thought it was because of the combination of layout elements used on measures 11 and 12. But when I tried to reproduce the issue on a blank document, I couldn't. It seems to be specific to this file, and I don't know exactly the cause. [Here is the file in question.](https://github.com/musescore/MuseScore/files/10725349/urar.zip)

OS: Windows 11
MuseScore version 4.0.1

**Comment by mike-spa** [comment]
Btw, the issue fixes itself after any relayout is triggered. It only appears at first load of a file. Anyway, here's how to reproduce it from scratch:

1. Start from a document without any breaks or "no-break groups".
2. Apply a no-break to two measures across a "natural" system break.
<img width="815" alt="image" src="https://user-images.githubusercontent.com/93707756/220152808-6186d2fe-8651-4915-a2b1-ac0bb0435849.png">
3. Apply a line-break to the last measure spanned by the no-break.
<img width="833" alt="image" src="https://user-images.githubusercontent.com/93707756/220152984-af04dc98-c535-4a2a-ae75-f6976c603be2.png">
<img width="597" alt="image" src="https://user-images.githubusercontent.com/93707756/220153077-5c48ea80-0fc8-45f1-972e-394e43132968.png">
5. Save, close, reopen.
6. Observe wrong bar number on third system.
