### ISSUE TITLE
[MU4 Task] Tidy-up two aspects of new "corrupted score" messaging flows for unsaved scores

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#16360]
**Task description**
This task relates to #16042 and #16151.

Two things are required: 

1. When the user attempts to save **to the cloud** an _unsaved_ score, which has become corrupt while they were working on it, they should see this dialog:

<img width="555" alt="214262751-22db8ee7-91bb-4dfa-aff1-5390871a4e05" src="https://user-images.githubusercontent.com/86290556/218773813-838e27a1-6e22-45ae-ae1b-e28b925cb04b.png">

2. When the user attempts to "Save as" **to their computer** an _unsaved_ score, which has become corrupt since they created it, they should see this dialog: 

<img width="555" alt="Group 14196" src="https://user-images.githubusercontent.com/86290556/218774005-fe124cbe-3974-41ec-a5a4-0275695426b6.png">

"Save anyway" would trigger the operating system's local save dialog. 

I hope that's clear!

Thanks 🙂

**Comment by bkunda** [comment]
I have just retested this, and can see that there has been a minor mix-up concerning which buttons are shown in two of the corruption dialogs. 
Hopefully a simple swap of the button options should fix this 🙂🤞🏻

Basically, the button options in this dialog: 

<img width="528" alt="Screenshot 2023-03-03 at 2 45 47 pm" src="https://user-images.githubusercontent.com/86290556/222735775-38d369c5-6f2c-4a06-9db6-de77f1e753d0.png">

should be shown in this dialog instead:

<img width="681" alt="Screenshot 2023-03-03 at 2 47 02 pm" src="https://user-images.githubusercontent.com/86290556/222736033-ebba36d1-8026-4c3a-a61a-6cfc6d0123f9.png">

And vice-versa.

The reasons are:

The first dialog above gets triggered when the user attempts to save a score to their computer _that they have already saved before_, and which has since become corrupted. They need to see a "revert to last saved" option to return the score to its previously uncorrupted state (as is indicated in the messaging).

The second dialog above gets triggered when the user attempts to save a score for the first time to their computer, which has recently become corrupted, and which has **_never been saved by the user before_**. Therefore, showing a "revert to last saved" option makes no sense, because the user has never saved a previous version of the file. 

To be clear, the right messaging is currently being shown under the right conditions in the current 4.0.2 build, its just that the button options between these dialogs are the wrong way around 🙂.

Apologies I missed this in earlier testing – which is why it's very good we are doing a further testing round now!

**Comment by DmitryArefiev** [comment]
Fixed in #16648

**Comment by bkunda** [comment]
🟢 Re-tested in OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651546, revision: github-musescore-musescore-dbe7c6d. FIXED.
