### ISSUE TITLE
[MU4 Issue] Accidentals in chord symbols rendered incorrectly when using custom XML file

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#16363]
**Describe the bug**
If you use a custom XML file as your chord symbol style, then upon save/reload of your score, all accidentals get rendered as the numeric Unicode numbers (e.g., the actual string "266d" and "266f " rather than the corresponding Unicode characters

**To Reproduce**
1. Add a chord symbol "Bb7" to a score
2. Go to Format / Style / Chord Symbols
3. Under Appearance, select Custom and load the following file (after renaming to XML): 
[chords_flat.ZIP](https://github.com/musescore/MuseScore/files/10734722/chords_flat.ZIP)
4. Save
5. Reload
4. See error: the flat sign in Bb7 is now rendered as 266d

**Expected behavior**
Ther flat sign should remain a flat sign

**Screenshots**
![image](https://user-images.githubusercontent.com/1799936/218800311-236e52d6-7b18-4e81-a13c-3d5a718e8732.png)

**Platform information**
 - OS: Linux

**Additional context**
The XML files contain statements assigned the flat sign to that Unicode character 0x266d `<sym code="0x266d" name="b">`.  This works normally for the built in chord description files, which are always read in anew when opening the score.  But for custom XML files, we actually write the relevant contents of the XML file into the score itself.  And apparently this is done in a way that somehow messes up the syntax.

Looking at the contents of the MSCZ archive, I see the file chordlist.xml is written, but it's messed up, that line has turned into `<sym name="b" code="266d"/>`.  This worked correctly in MU3.

**Comment by Jojo-Schmitz** [comment]
So the `0x` is being ommitted when putting it into the mscx, right?

**Comment by MarcSabatella** [comment]
Yes.  I assume it somehow has to do with the XML read/write functions, something not being escaped that needs to be.

Meanwhile, a workaround seems to be, edit the XML file to replace the `0x266d` with the more HTML-friendly `&#9837;`

**Comment by Jojo-Schmitz** [comment]
Might be related to the 'home-brew' string lib

**Comment by moogly81** [comment]
**Additional info** 
The issue happens only on the score, NOT on the parts. 

**Workaround** 
step 1 :  format --> style --> chord symbols --> select jazz (or standard)
step 2 :  format --> style --> chord symbols --> select "custom" and chose your custom xml file again. 
==> chord symbols are fixed on the score

**Comment by SejoWuigui** [comment]
Open *.mscz file with arvhiver and delete 'chordlist.xml'. Then MuseScore 4 shows chords normally.
What's the reaseon?

**Comment by MarcSabatella** [comment]
Me cause now you’ve removed the custom chord symbol definition and are back to using the default.

**Comment by SejoWuigui** [comment]
I'm using MuseScore 4.02 and Windows 10(Korean language).
Before, I copied 'chords_jazz.xml' to [documents] musescore folder, and edited just slash chord part(a little positioning fix).
But the error like screenshot above occured.. 😥

Now, I ran into [program files] muscescore folder, and backup the 'chord_jazz.xml' and edit directrly.
Set score's chord style to 'Jazz', and save it. Then I re-open the file and sharps(#) and flats(b) are shown correctly.

**Comment by mattblo** [comment]
I also have this issue when using an custom chord style file. Is there a fix already? I have about 350 files top render with a custom style file and this is really annoying...

**Comment by MarcSabatella** [comment]
I don't think there is anyone working on a fix in the code, but the solution for now is to fix your custom XML file to use the better syntax I described above in https://github.com/musescore/MuseScore/issues/16363#issuecomment-1430235880

**Comment by cbjeukendrup** [comment]
I took a quick look and probably it has gone wrong either here: https://github.com/musescore/MuseScore/commit/ce2473bc80216b9af70945ef0b632f6a00ec6b13#diff-34fc1099345fb1b9e716cbe1602692db544d21858204ce45642aa36e99f779afR1794 or here: https://github.com/musescore/MuseScore/commit/0a13b86cbb35e2b20677b7f7f60427d9598b4ccc#diff-34fc1099345fb1b9e716cbe1602692db544d21858204ce45642aa36e99f779afR1792 (see the Git Blame for `ChordList::write`)

**Comment by AlteriusOmega** [comment]
I keep experiencing this issue, but I have never (intentionally) set a custom file for chord symbol styles. I didn't even know it was possible until I found this issue page. However in the past few days, my score has started exhibiting this problem a couple times. I just looked in Format --> Style --> Chord symbols and found it was set to Custom with "chords_std.xml". I don't know where this file came from so I assume its automatically built by MuseScore. The file says the version is 1.24, and it seems to be formatted correctly in terms of the XML but I don't know any of the specifics of this chord symbol style. So, I don't know why it would exhibit this problem 

I don't know how this got set this way as I have never opened this Style menu before. Is there some keybaord shortcut or some other action that can automatically set this? I don't know how it keeps getting set this way and I would like to avoid it since this problem is still present.

**Comment by Jojo-Schmitz** [comment]
Seems to happe on importing scores from older MuseScore versions

**Comment by AlteriusOmega** [comment]
> Seems to happe on importing scores from older MuseScore versions

Ah yes you are right, this score I'm working on was originally an older MuseScore version file. I'm guessing the chords_std.xml is a sort of bridge to make the new chord style system compatible with some previous one?

**Comment by Jojo-Schmitz** [comment]
Which version stemmed the score from?

**Comment by MarcSabatella** [comment]
chords_std *is* the default standard style; it it is just supposed to be accompanied by a tag marking it as such rather than as Custom.  So simply change the style to Standard instead of Custom to workaround this.

**Comment by Jojo-Schmitz** [comment]
Still an issue
[ILikeTheFlowersLEAD.zip](https://github.com/musescore/MuseScore/files/14898283/ILikeTheFlowersLEAD.zip)

**Comment by Alice1667** [comment]
I had this when loading MS3 music into MS4. I went into format style - chord symbols: changed it to Jazz & it gave me the correct flat chords. Changed it back again and it was still correct.

**Comment by Jojo-Schmitz** [comment]
Yes, that is the workaround

**Comment by Jojo-Schmitz** [comment]
Came up agaion in https://musescore.org/en/node/363221

**Comment by Jojo-Schmitz** [comment]
I believe it got go wrong somehere here:
```cpp
            while (e.readNextStartElement()) {
                if (e.name() == "sym") {
                    ChordSymbol cs;
                    cs.fontIdx = fontIdx;
                    cs.name    = e.attribute("name");
                    cs.value   = e.attribute("value");
                    String code = e.attribute("code");
                    String symClass = e.attribute("class");
                    if (!code.empty()) {
                        bool ok = true;
                        char32_t val = code.toUInt(&ok, 0);
                        if (!ok) {
                            cs.code = 0;
                            cs.value = code;
                        } else if (Char::requiresSurrogates(val)) {
                            cs.code = 0;
                            cs.value = String::fromUcs4(val);
                        } else {
                            cs.code = val;
                            cs.value = String(cs.code);
                        }

```
probably in the `toUInt()` method

**Comment by Jojo-Schmitz** [comment]
No it is not, it is going wrong on write, this fixed it:
```cpp
$ git diff
diff --git a/src/engraving/dom/chordlist.cpp b/src/engraving/dom/chordlist.cpp
index 8ddcd824d9..c80a218617 100644
--- a/src/engraving/dom/chordlist.cpp
+++ b/src/engraving/dom/chordlist.cpp
@@ -1780,7 +1780,7 @@ void ChordList::write(XmlWriter& xml) const
                 if (s.code.isNull()) {
                     xml.tag("sym", { { "name", s.name }, { "value", s.value } });
                 } else {
-                    xml.tag("sym", { { "name", s.name }, { "code", String::number(s.code.unicode(), 16) } });
+                    xml.tag("sym", { { "name", s.name }, { "code", u"0x" + String::number(s.code.unicode(), 16) } });
                 }
             }
         }
```
And indeed @cbjeukendrup was right in https://github.com/musescore/MuseScore/issues/16363#issuecomment-1553644553.

But for all scores that had been written already it is too late, so the reading needs to get fixed too, prefixing a `0x` it every value not having one and not starting with `&` (and ending with a `;`, so basically being alpha-numerical.

**Comment by Jojo-Schmitz** [comment]
Like this probably:
```cpp
diff --git a/src/engraving/dom/chordlist.cpp b/src/engraving/dom/chordlist.cpp
index 8ddcd824d9..72936bd543 100644
--- a/src/engraving/dom/chordlist.cpp
+++ b/src/engraving/dom/chordlist.cpp
@@ -1685,6 +1685,9 @@ void ChordList::read(XmlReader& e)
                     String code = e.attribute("code");
                     String symClass = e.attribute("class");
                     if (!code.empty()) {
+                        if (!code.startsWith(u"0x") && !code.startsWith('&') && !code.endsWith(';')) {
+                            code = u"0x" + code; // fix broken chord lists
+                        }
                         bool ok = true;
                         char32_t val = code.toUInt(&ok, 0);
                         if (!ok) {
@@ -1780,7 +1783,7 @@ void ChordList::write(XmlWriter& xml) const
                 if (s.code.isNull()) {
                     xml.tag("sym", { { "name", s.name }, { "value", s.value } });
                 } else {
-                    xml.tag("sym", { { "name", s.name }, { "code", String::number(s.code.unicode(), 16) } });
+                    xml.tag("sym", { { "name", s.name }, { "code", u"0x" + String::number(s.code.unicode(), 16) } });
                 }
             }
         }
```

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/364006

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/365531
