### ISSUE TITLE
[MU4 Issue] Request for Canvas to lose some weight

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#16373]
Please click the image to get a better impression:

![Untitled 2345](https://user-images.githubusercontent.com/78870770/219038386-d9041332-1f86-44e3-b528-37596c387a9f.jpg)

I don't see a need for the bar to be so thick.

Just to shrink its height would already help to make the whole bar less obtrusive, I think:

![Untitled 2346](https://user-images.githubusercontent.com/78870770/219038829-0cb91779-49b8-4171-8749-b1907fae0ec8.jpg)

**Comment by Tantacrul** [comment]
As you'll soon see, this area is going to be populated with:

- Tabs
- A few options for each tab

It may not be obvious now, but we designed this while looking to the future. We'll be providing designs for what's next soon.

Closing this issue.
