### ISSUE TITLE
[MU4 Issue] Adding Intervals on top of tied notes should apply a tie

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#16376]
https://user-images.githubusercontent.com/78870770/219055409-5316de6f-8dcb-4099-880a-5d04f5d4c9a5.mp4

**Comment by oMrSmith** [comment]
> Thoughts?

That sounds like a pretty good and straight forward solution to me!

**Comment by oktophonie** [comment]
Closing since this seems to have been addressed some time ago (in 4.1), though at this point I can't recall exactly where.
