### ISSUE TITLE
[MU4 Issue] Selection filter doesn't behave logically when selecting unisons

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#16375]
https://user-images.githubusercontent.com/78870770/219050642-fa9f7412-bdad-4c64-ab51-951f21e3d7ab.mp4

If voice 2 is filtered out
voice 1 should be selected.

For unisons I think that single note selections
should work like this: 
Of all voices which are not filtered out
the voice of the lowest number should be selected first.

**Comment by MarcSabatella** [comment]
The selection filter is for excluding elements from range selection, not for controlling how clicking an element works.  That would require an entirely different design.

**Comment by oMrSmith** [comment]
In this case I think it should be called range-selection filter.
