### ISSUE TITLE
[MU4 Issue] Concert pitch checkbox doesn't reflect state properly when switching between different tabs (score, parts)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#16374]
**To Reproduce**
1. Open score with transposing instruments (e.g. Wind quintet)
2. Open Clarinet and Horn parts
3. Change Concert pitch checkbox differently on different tabs
4. Switch between tabs - **concert pitch checkbox doesn't change it's state**

https://user-images.githubusercontent.com/90187801/219042294-7d4d0883-aabc-4fb0-a1cc-8a6d10ad85f3.mp4

**Expected behavior**
Concert pitch checkbox should reflect the state of current tab

**Platform information**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MS3**
Occurs in **4.0.0**

**Comment by zacjansheski** [comment]
@DmitryArefiev , I reproduced in 4.0, but not in the current versions, is this still an issue?

**Comment by DmitryArefiev** [comment]
@zacjansheski Tested on Win/Mac. I tested several versions and found actually it was already fixed in **4.1.0**

Closing
