### ISSUE TITLE
[MU4 Issue] Changing to "Continuous view (vertical)" after "Page view" often results in empty window

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#16371]
**Describe the bug**

1. Load a multipage score into MS4 in Page view mode.
2. Go to any page except page 1
3. Switch to Continuous view (vertical)

RESULT: The window is now blank. The viewer needs to adjust the viewport to get the score back into view. This happens if the original page in view is any but page 1.

**Expected result**

The viewport should not be empty.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230460504, revision: github-musescore-musescore-a36e598

**Comment by oMrSmith** [comment]
+1

**Comment by Tejkh1** [comment]
See PR #16752
