### ISSUE TITLE
[MU4 Issue][Playback] Many Noteheads sound infinitely on MS Basic instruments.  Cross noteheads only on vocal instruments (SoundFont)

### ISSUE THREAD

**Issue by jeetee** [musescore/MuseScore#16389]
**Describe the bug**
Using a crossed notehead on a vocal staff results in the note sounding infinitely when using a SoundFont for playback.

**To Reproduce**
1. Open the attached score (was created from scratch in 4.0.1) [Voice-cross-playback-glitch.zip](https://github.com/musescore/MuseScore/files/10754748/Voice-cross-playback-glitch.zip)
2. Play

**Expected behavior**
Crossed noteheads play back normally, or even a bit shorter (percussive-like).

**Platform information**
 - OS: Windows 10
 - Verified on:
     - 4.0.1
     - 4.0.2 nightly a36e598
     - master nightly 23f851d

**Additional context**
The bug shows both when using MS_Basic as well as the MuseScore_General.sf2 soundfonts.
It does *not* show when using those same soundfonts via Sforzando; hinting that the bug lies within the local synthesizer itself.

**Comment by zacjansheski** [comment]
There is an over-arching issue with noteheads.  I will re-scope this issue

https://github.com/musescore/MuseScore/assets/69917893/421995a5-8476-4fb7-ac22-ab98445b9a97

**Comment by bakajikara** [comment]
Similar to #15268, this is caused by missing definitions for CrossNote, CircleNote, TriangleNote, and DiamondNote in the json files in `src/framework/mpe/resources/` .

**Comment by Lenbus** [comment]
Any updates on this topic? Updating to MS4.1 unfortunately did not solve the issue. 👎 

I've encountered this faulty playback behaviour for:
• Articulation, such as: Fade In, Volume Swell, Fall, ...
• Glissando-like expressions, such as: Scoop, Fall, ...
• Note Heads like: Diamond, Triangle, Plus, ...
