### ISSUE TITLE
[MU4 Issue] Breath marks create unnecessary space for cross-system ties

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#16397]
**Describe the bug**
Where a note is tied across a system, breath marks (' and V etc) at the end of the system create an uncrossable space for slurs and ties at the end of the system. Moreover, they do it for all staves on the system - even those on which they don't appear:

![image](https://user-images.githubusercontent.com/20604032/219417163-085bdf5e-b7af-4b69-8eac-dec2d834fc91.png)

Here's another fun example:
![image](https://user-images.githubusercontent.com/20604032/219417732-c33684a8-95ef-461a-bfc3-77d3a561f19d.png)

**Expected behaviour**
The presence of a breath mark should not affect any slurs or ties that cross it, at the ends of systems (or indeed anywhere else).

**Platform information**
4.0.1

**Comment by GabeS573** [comment]
A much more dramatic example which I encountered today:
![image](https://user-images.githubusercontent.com/91428485/223623110-72d7532a-166a-48e8-b290-f8bad5b8e8cd.png)
