### ISSUE TITLE
[MU4 Issue] Deleting voice 2 rests in measures with small duration notes in voice 2 makes beat 1 stretch

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#16395]
**Describe the bug**
If you delete all the voice 2 rests in a measure where voice 2 has 64th notes or smaller on the last beat (and you also delete the half rest on beat 1 last), then beat 1 gets stretched out, with smaller note values in voice 2 corresponding to larger stretch.

**To Reproduce**
1. Create a score with notes in a measure
2. Put a 64th note or smaller in the second voice on the last available beat of the measure
3. Delete the rests in voice 2
4. See stretched out measure

**Expected behavior**
The measure shouldn't stretch out like this

**Screenshots**

https://user-images.githubusercontent.com/21023353/219399324-d444a5a8-3c76-4dd5-8b36-05fe4b00f9c2.mp4

https://user-images.githubusercontent.com/21023353/219399521-cad164cf-82f5-400a-aa0e-c866971aa97e.mp4

**Platform information**
 - OS: Reported on Windows, MU 4.0.1

**Additional context**
The stretch only seems to happen if you delete rests that are at least 5 powers of note value bigger than them

**Comment by DmitryArefiev** [comment]
Retested on Win10
