### ISSUE TITLE
Issues with tie invisibility when crossing system break

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#16396]
**Describe the bug**
First issue with tie invisibility: If you tie a note, make the tie invisible, then make the invisible tie go over a system break, the portion of the tie after the system break is visible and the keyboard shortcut 'v' doesn't do anything either. You either have to press v twice on the part of the tie before the system break, or you can also press the 'visible' checkbox in the Properties panel twice.
Second issue: If you copy and paste anything with invisible ties, the ties are visible after the paste and the only way to make them invisible is with the checkbox in Properties.
Additionally, the checkbox in the Properties tab will report the incorrect state for the tie, believing that it is invisible when it is not.

**To Reproduce**

https://user-images.githubusercontent.com/21023353/219411803-7b063ee2-9780-4537-9fa2-afa16de51e0b.mp4

**Expected behavior**
The ties should be invisible when I tell them to be

**Platform information**
 - OS: Reported on Windows

**Additional context**
This was an issue in MS3 too, not just MS4

**Comment by oktophonie** [comment]
Note to self: if you put the system break in (dividing a visibile tie over the break) and _then_ make the tie invisible, it works as expected.

**Comment by erinic04** [comment]
This issue is not actually fixed! Both halves of this issue are still a problem in musescore 4.4, its just harder to notice now. The ties will be colored gray inside musescore like other invisible elements, but they will not disappear when you uncheck the box for showing invisible elements, and they will also still show up in exported pdfs and on musescore.com uploads, arguably making the issue worse now since it is harder to notice and fix inside Musescore Studio
