### ISSUE TITLE
Chord or note duration

### ISSUE THREAD

**Issue by sdlawsonsjlondonorg** [musescore/MuseScore#16417]
issue chords bleeding into the next. Example "intro of "Eye Of The Tiger" the bumps. how can one fine tune the duration of each chord or note. There are no sharp cut off at the end of the chord it rings slightly into the next chord almost as if the 2 last chords are ringing together.

Another example "I feel good" bump! bump!
Another is I am working on a intro that walks up from 2-3-4=5
I need the 2, 3, 4 to barely sound Kind of of like bumps

**Comment by zacjansheski** [comment]
There is not enough information in this report for developers to work on this.  If you still have an issue, consider raising a new report with a reproducible bug.  You can attach scores when applicable
