### ISSUE TITLE
[MU4 Issue] Problem with Chord Symbol for minor chord with major seven 

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#16427]
Of the following three symbols (for the same chord)
only the first one will play the chord correctly:

![image](https://user-images.githubusercontent.com/78870770/219876706-6440e768-0b3d-410d-96e5-da8e5a1d10dd.png)

**Comment by MarcSabatella** [comment]
The second is pretty meaningless, #7 isn't something that really makes sense.  The third doesn't work for the same reason plain triangle doesn't work for major seventh - the original meaning of the triangle was really to just mean "major" without necessarily implying a seventh.  Although it's true that over time, some writers have used it that way.  Eventually, there should be a customization features where you can specify more playback details for non-standard notations etc.  But for now, best to sytcik to standard notations, like maj7, ma7, triangle7, even M7 (although I strongly recommend against relying on capitalization alone to indicate the different between major and minor).

**Comment by oMrSmith** [comment]
> the original meaning of the triangle was really to just mean "major"

I think that is pretty meaning less too, because the basis of every chord symbol is a plain major chord.

**Comment by MarcSabatella** [comment]
No one ever said that chord symbol nomenclature was entirely logical.  I'm just saying, #7 doesn't really make sense, would be ambiguous to most musicians who saw it, and no publisher I am aware of uses it.  I would never ever recommend anyone use such a notation.  If you have some special reason to need to disp[lay that, you can, and then if you also have a specific idea about how you'd want it played, you can enter a second invisible chord.  Same as if you wanted to enter any other meaningless notation.

I can't defend why the people who first started using triangle for major did so, I'm just reporting the facts.  Use of the triangle should always be accompanied by 7 to be unambiguous, same with the half-diminished symbol.  Doesn't matter what might seem "logical", if we were inventing a new system for chord symbol notation.  I'm just taking what actual publishers do, what actual published style guidelines call for, what actual textbooks teach, etc.

**Comment by oMrSmith** [comment]
> Use of the triangle should always be accompanied by 7 to be unambiguous

You're probably right. I thought the triangle was a stand-alone for major 7 and remember 
to have seen it as such.

**Comment by oMrSmith** [comment]
@oktophonie 
actually I found the case:

![image](https://user-images.githubusercontent.com/78870770/219878422-24c6781e-83d3-439b-b979-ea5470772ae1.png)

This is from the New Realbook.

The term "MA", which could have been replaced by the triangle, 
stands alone and does in fact refere to the seven.

**Comment by MarcSabatella** [comment]
Like I said, it's not necessarily logical.  But, it is pretty consistent: "ma" or similar abbreviations for major *by themselves* don't imply a 7.  But, in conjunction with any number greater than or equal to 7, it does *affect* the quality of the seventh in the stack of thirds.  So, ma7 means the seventh in the stack is major, and ma9 *also* means the seventh in the stack is major (it doesn't mean the ninth is major; that's already the case by default, but ma on its own just means a major triad.  It's crazy but that's how it developed over the decades.

The triangle is indeed unique in that *some* people have chosen to use it as a shorthand to imply the seventh, but others use it the same as ma/maj to simply mean major.

**Comment by oMrSmith** [comment]
> "ma" or similar abbreviations for major _by themselves_ don't imply a 7. But, in conjunction with any number greater than or equal to 7, it does _affect_ the quality of the seventh in the stack of thirds.

This explenation of yours gives some peace to my mind ;).
