### ISSUE TITLE
[MU4 Issue] Cutaway option resets upon opening Staff/Part properties

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#16436]
**Describe the bug**
If you set the cutaway option (either in the Instruments panel or in Staff/Part properties), then go to Staff/Part properties to complete the job by setting "Hide when empty" to "Always", the "Cutaway" option has been disabled again

**To Reproduce**
1. Create a score with two staves
2. For one staff, go to "Staff/Part properties" and enable Cutaway
3. Hit OK
4. Go back to "Staff/Part properties"
5. See error: the cutaway option is turned off again

**Expected behavior**
The option should stick

**Platform information**
 - OS: Linux

**Additional context**
At first I thought it was a bad interaction between the Instruments panel version of this setting and Staff/Part properties, but I see I can reproduce the error without using the Instruments panel at all.  So I suspect the dialog simply isn't initializing this setting correctly.

**Comment by bakajikara** [comment]
I think this is the same issue as #15254 and may have already been fixed in #15281

**Comment by cbjeukendrup** [comment]
Yes, I think that too. The fix didn't make it into 4.0.2, but will be in 4.1.

**Comment by MarcSabatella** [comment]
Ah, thanks, I did a search but obviously forgot to check closed issues.
