### ISSUE TITLE
[MU4 Issue] Crashes when deleting bars or change volta properties in certain files

### ISSUE THREAD

**Issue by unclewalter** [musescore/MuseScore#16442]
**Describe the bug**
When deleting more than two bars, it seems to crash with some files. I've attached a file than seems to cause it to happen.

[Musescore file](https://drive.google.com/file/d/1UHjAAxOGDS0Rf2PJ4GE2m7som3OadHoQ/view?usp=share_link)

**To Reproduce**
1. Select more than two bars
2. Cmd+delete
3. Program crashes

_or_

1. Change number or repeats
2. Program crashes

**Platform information**
 - OS: MacOS 13.2.1 (22D68)

**Comment by cbjeukendrup** [comment]
@unclewalter It looks like some special access is needed to download the attached file from Google Drive. You can upload the file directly on GitHub by wrapping it in a ZIP file.

**Comment by unclewalter** [comment]
[New Song 2.mscz.zip](https://github.com/musescore/MuseScore/files/10783879/New.Song.2.mscz.zip)

**Comment by oktophonie** [comment]
I find this file crashes upon opening(!) so perhaps a corruption issue at play?

**Comment by cbjeukendrup** [comment]
It seems to be related to the repeat list. I've created a stopgap solution in #16470, but I wonder why the situation even happens. @jeetee Could you please also take a look?

**Comment by jeetee** [comment]
I'll try to have a look this week.

I'm more interested into _why_ Harmony is requesting a utick that's outside of the score (according to repeatList). Seems like either Harmony or the RepeatList is not up to date when this call happens.

**Comment by DmitryArefiev** [comment]
Fixed in #16514
