### ISSUE TITLE
Crash on quit (macOS)

### ISSUE THREAD

**Issue by amijaishalev** [musescore/MuseScore#16456]
I recieve the attached crash log repeatedly.
Sometimes MS4 crashes and sometime after quitting.

There was a previous issue with Spitfire BBC Symphony, I uninstalled Spitfire from the computer  and deleted all related files (I think) however MS4 still shows it in the mixer... as if it was not updated. 
[MS4 crash log.pdf](https://github.com/musescore/MuseScore/files/10787090/MS4.crash.log.pdf)

**Comment by cbjeukendrup** [comment]
Thanks for the crash report, that's always very useful! It looks like this is from the crash after quitting, right? Did you mean that there is sometimes another crash too? If so, it would be great if you could capture a report for that one too.

The issue with the uninstalled VST plugin that still appears seems unrelated to this crash. It would be great if you could open create a new report for this; our rule of thumb is: one problem per GitHub issue. Thanks!

**Comment by amijaishalev** [comment]
Yes, indeed this is a crash after quitting.
There's also a crash while working, I'll upload the log when it happens.

**Comment by cbjeukendrup** [comment]
Thanks! I think it's the best if you open a separate issue for that crash too, when it happens again. Would be perfect if you can find how to reproduce the crash step by step!

**Comment by zacjansheski** [comment]
Have we determined a way to reproduce the crash?

**Comment by amijaishalev** [comment]
It happens to me almost on every session, I can attach the current file I am working on and the log if that helps. There isn't anything special on my side as a user, just notation...

**Comment by zacjansheski** [comment]
File and log would help us diagnose the issue.  (It was labeled "needs info" so I'm hoping it will help us get to the bottom of it) 🙂

**Comment by cbjeukendrup** [comment]
The crash report attached in the initial comment is probably the most helpful thing we can get... but you could try uploading the logs, maybe they give a clue...

When this happens, how exactly do you quit MuseScore? For example,
- click the 'X' button inside the tab bar inside the window
- click the red macOS close button at the top of the window
- File > Close 
- Cmd + W
- MuseScore > Quit MuseScore 
- Cmd + Q
- click Quit in the right-click menu of the icon in the Dock
- other?

Or does the crash happen with _all_ of these ways?

And another question: do you have any accessibility-related features enabled on your Mac?

**Comment by cbjeukendrup** [comment]
Oh, actually one very important question: the crash log reveals you are/were using MuseScore 4.0.1. Could you at least make sure that you are using 4.0.2?

And could you then please check if it also happens in the latest nightly build? https://musescore.org/en/nightly-builds

**Comment by amijaishalev** [comment]
I think that when I first submitted it was 4.0.1 now I am working with 0.2 so I will upload the next log.
I usually save just in case (cmd+s) and then click on the x or cmd+q. Normally I don't close the file before I quit.

It is worth mention that if I just open change a couple of notes and close the file it doesn't happen. It does happen after a session of work, but I still can't identify what it is exactly or how long I have to work for this to happen. 

I don't have any accesibilty features enables.

I will try the nightly next time it happens and will keep you updated.
Thanks

**Comment by amijaishalev** [comment]
Hi, 
I just had a crash message with a file that tends to corrupt while working (randomly saying that bars are different than expected), which I solve by deleting bars and adding them.

The crash message is: Musescore quit unexpectedly - although I exit using the X on the left. 
I will try it later today with latest nightly.

Hope that helps... 

[Crash log MU4 may 30.pdf](https://github.com/musescore/MuseScore/files/11602239/Crash.log.MU4.may.30.pdf)

**Comment by cbjeukendrup** [comment]
Interesting. This crash report is completely different from the initial one. Could you send me the score for which it happened? Maybe that will give me a clue. And if you find a deterministic way to corrupt it, that would be interesting too. But given the crash report, I doubt if the crash is related to the corruptions.

**Comment by amijaishalev** [comment]
[Downstream - crashed.mscz.zip](https://github.com/musescore/MuseScore/files/11607291/Downstream.-.crashed.mscz.zip)
Here is the file attached...
I usually get the corrupt message after editing some notes and saving, I could not find a systematic cause.  But it seems related to durations in the bar, it says it expects 4/4 and get 6/4 or 7/8 ... although there are no meter changes.

**Comment by zacjansheski** [comment]
Unable to open file on MacOS or Ubuntu on nightly.  
[16456 Diagnostic Files.zip](https://github.com/musescore/MuseScore/files/11616675/16456.Diagnostic.Files.zip)

I am able to open in 4.0.2 on MacOS

**Comment by bkunda** [comment]
Bumping this to 4.2 for now because it seems very difficult to reproduce and will require some dedicated resources to conduct further investigation.

**Comment by cbjeukendrup** [comment]
@amijaishalev Could you please try if you are still experiencing this crash in the latest nightly build? https://musescore.org/en/nightly-builds

**Comment by zacjansheski** [comment]
Closing (no response)

**Comment by DaveCos29** [comment]
4.2 crashes everytime which means I cannot save my workspace preferences (palette) which is frustrating to say the least. 

Mac OS 13.6.1 
Mac Mini M2 Pro 
16gb ram

I tried re downloading and installing directly from the site not the Hub and it still persists... :(

**Comment by MarcSabatella** [comment]
Be sure also you don't have multiple scores open when customizing workspaces because the different instances' customizations might be overwriting each other.  if you need further assistance on that front, please ask for help on the support forum on msuescore.org.

**Comment by DaveCos29** [comment]
Thanks Mark.  I have been very mindful only to have 1 score open at any time.  I wonder if I should trash all MuseScore files in the cache or do a full uninstall then re-install.  I don't recall this happening with 4.1 but I would be curious to try that version out again for comparison....
