### ISSUE TITLE
[MU4 Issue] Score becomes corrupted after actions with deleting piano instrument, undo and adding notes to bottom staff

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#16457]
**To Reproduce**
1. Open [Untitled score.mscz.TXT](https://github.com/musescore/MuseScore/files/10787184/Untitled.score.mscz.TXT)
2. Delete Piano from Instruments panel
3. Undo
4. Add note to bass clef staff
5. Save

https://user-images.githubusercontent.com/90187801/220181366-c17f3237-b6a2-440f-8d59-ba3d8cab5353.mp4

**Platform information**
 Windows10

**Comment by DmitryArefiev** [comment]
Fixed in #16474

**Comment by rich777300** [comment]
I downloaded the score, removed the .txt extension, opened it in MS4.0.1, went into the instruments panel, selected piano, and pressed the trash can icon on the top right of the instruments panel. MuseScore crashed on me, twice.

I'm on Windows 10 64-bit

**Comment by oktophonie** [comment]
@rich777300 Yes, this is as expected. Only in a build of the specific PR that fixes this issue (https://github.com/musescore/MuseScore/pull/16474) would you expect to not experience the crash. (I can confirm it works)

**Comment by DmitryArefiev** [comment]
Retested on Win10
