### ISSUE TITLE
[MU4 Issue] Infinite sustain triggered by time signature change

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#16460]
**Describe the bug**
The music starts in 1 time signature, say 4/4, and then it later changes to a different time signature like say 2/2. If there isn't a rest in the measure before the time signature change and there's nothing after the time signature change, the last notes to be played are sustained indefinitely after the time signature change. 

**To Reproduce**
1. Write some music in 4/4, leaving the last measure without a rest
2. Add a 2/2 time signature later on in the piece
3. Hear the infinite sustain in Muse Sounds

**Expected behavior**
The note stops after it's duration is up regardless of there being a time signature change or not

**Screenshots**

https://user-images.githubusercontent.com/6530761/220184776-42f704e2-c70b-475f-a5f4-9e651bfee8b1.mp4

**Platform information**
 - OS: Windows 10
 - MuseScore 4.0.1

**Additional context**
I noticed this in woodwinds first, don't know if it affects other instruments. I also don't know if it's time signature changes in general or specifically 4/4 to 2/2 that triggers it. And it's Muse Sounds specific. Here's the score where I first noticed it. 
[Symphony no. 1 in C Op. 21.zip](https://github.com/musescore/MuseScore/files/10787296/Symphony.no.1.in.C.Op.21.zip)

**Comment by cbjeukendrup** [comment]
Strange issue... I can't reproduce it on Mac nor on my Windows laptop. Not even with the attached score. Are your Muse Sounds up to date?

**Comment by DaddyLudwig** [comment]
I think so, It doesn't say that it needs updated when I refresh the update thing. I'll uninstall and reinstall Muse Woodwinds to check.

Okay, apparently the update automatically thing for Muse Sounds doesn't work for me for some reason, maybe I need to uninstall and reinstall Muse Hub, I don't think I've done that since beta. Yeah, it says BETA by the Muse Hub icon when I open it, so that might have something to do with it. But after uninstalling and reinstalling Muse Woodwinds, I'm not having the time signature cause an infinite sustain.
