### ISSUE TITLE
[MU4 Issue] MU freezes when trying to invoke Open dialog (Windows only)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#16477]
**To Reproduce**
1. Run MU 
2. File>Open

https://user-images.githubusercontent.com/90187801/220395258-f4ca3d18-6a98-45d4-8911-322e1a6959f0.mp4

**Platform information**
Windows10

**Additional context**
Recent changes

**Comment by asattely** [comment]
Reverting this commit fixes the issue: https://github.com/musescore/MuseScore/pull/16388/commits/9a978734eb1fe53750d8f70c5c59b1a8d5ae05bd

I have no idea why that is the case, but extreme thanks to @mike-spa who found that this was the issue!

**Comment by DmitryArefiev** [comment]
Fixed in #16484

**Comment by DmitryArefiev** [comment]
Retested on Win10
