### ISSUE TITLE
[MU4 Issue] Lyrics/Slurs visibility is toggled along with notes

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#16476]
**Describe the bug**
When making a note invisible, attached lyrics are also made invisible

**To Reproduce**
1. Add a note and lyric to a score
2. Select the note only
3. Press "V"
4. See error: the lyric is made invisible as well

**Expected behavior**
The lyric should remain invisible

**Additional context**
I know the behavior of the visibility toggle changed recently, mostly for the better, in the all components of the chord are made invisible at once.  And for most, this makes perfect sense.  Somehow lyrics seem different though.  In part because most other text is not affected (since it is normally attached to the segment instead of the note or chord), in part because having lyrics attached to invisible notes is a pretty common technique for a variety of purposes.  Not a big deal because you can always toggle the lyric back, but still, I'd vote to exclude lyrics from this, much as grace notes were as per https://github.com/RomanPudashkin/MuseScore/commit/918a00c083b23e737d977e0a5e4e40dd0d9213ca

**Comment by DmitryArefiev** [comment]
The same with slurs:

https://user-images.githubusercontent.com/90187801/225027452-27c76594-9890-4d0a-af02-e81b9991afc3.mp4

**Comment by DmitryArefiev** [comment]
Fixed in #16998
