### ISSUE TITLE
Create generic colour 'rainbow' swatch, which enables users to assign colours to mixer channels, percussion, etc.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#16485]
Here's an example of what Reason offers.
![image](https://user-images.githubusercontent.com/21022311/220582082-1b62a6d7-5bbe-407a-8850-7e88a83fa966.png)

This colour swatch would **not be affected** by the accent colour. We would most likely need two different swatches for dark / light mode.

**Comment by jessjwilliamson** [comment]
This task has been completed and is ready to be implemented
For accessibility reasons, the names of each color are also listed. All of this is in the 'UI Components & Styles' > 'Colors' page

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/71656189/235720508-48f96ba2-a201-40d3-b82f-4891c2109c94.png">

**Comment by jessjwilliamson** [comment]
Dev task raised in https://github.com/musescore/MuseScore/issues/17714
