### ISSUE TITLE
Crashes when moving a note after an undo

### ISSUE THREAD

**Issue by bebobebo** [musescore/MuseScore#16483]
https://musescore.org/en/node/342355

Repro

Type B, C, Ctl+Z, down

ie. enter two notes in sequence, undo, move the first note (up, down, ctl+up, ctl+down)

-> crashes every time.

Windows 11 and Windows 10 with 4.0.0 and 4.0.1

**Comment by oktophonie** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/16437
