### ISSUE TITLE
[MU4 Issue] Last 2 nightly freeze when click "open file" in menu or when drag a file.

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#16494]
Last 2 nightly freeze when click "open file" in menu or when drag a file.

MuseScoreNightly-230530506-4.0.2-fa46d7f-x86_64.7z	2023-02-22 05:39 	89M
MuseScoreNightly-230520507-4.0.2-fa46d7f-x86_64.7z	2023-02-21 05:31 	89M

**Comment by oktophonie** [comment]
Fixed by https://github.com/musescore/MuseScore/pull/16484; will be OK in tomorrow's nightly

**Comment by Gai-Luron** [comment]
Sorry!
