### ISSUE TITLE
[MU4 Issue] Tablature: Can't change fretmark to a crosshead (ghost) note; Shift+X not working

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#16490]
**Describe the bug**

In MS3, Shift+X was used (in normal mode) to change a fretmark to a crosshead (ghost) note in tablature. AFAIK, this behaviour should continue in MS4. However, for some reason, in MS4, parentheses are being applied instead of a crosshead.

**Expected behavior**

In normal mode, Shift+X should change a numerical fretmark to a crosshead (ghost) fretmark.

**Platform information**

OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230530504, revision: github-musescore-musescore-fa46d7f

**Comment by MarcSabatella** [comment]
The parentheses are by design, apparently for Guitar Pro compatibility (the documentation for that program confirms this).  See https://github.com/musescore/MuseScore/issues/10306.

**Comment by oktophonie** [comment]
I've turned this into a task; feel free to comment there: https://github.com/musescore/MuseScore/issues/16500
