### ISSUE TITLE
[MU4 Task] Dynamics placement per-staff, rather than global

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#16509]
In scores with vocal music as well as instruments, a global setting for dynamics placement is not enough. Vocal staves should normally have their dynamics default to above the music, while instruments should default to below, and grand staves should default to between the two staves. It's not enough to detect lyrics and shift the dynamics - sometimes vocal scores don't have lyrics on some singers but the dynamics should still appear above the staff.

**Comment by cbjeukendrup** [comment]
I was thinking about this too, recently. Maybe we should work towards a system where "style settings" can have multiple scopes: file-wide (to sync it between full score and part scores), score-wide, staff-wide... 

Of course, not for all style settings all scopes are applicable; for settings like "show system dividers", a staff scope would be pointless.

At some point there was some discussion about what to do with the "staff type" settings (that can be found in the "Staff/Part properties" dialog); this might also be a good solution for some of those.

**Comment by BoBogus** [comment]
This would be especially useful for piano, since the right hand sometimes needs to play louder than the left hand.

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/364157

**Comment by odie16** [comment]
Also looking forward to this feature!

**Comment by avvvvve** [comment]
Closing, this feature was added to 4.4 by #22662
