### ISSUE TITLE
During playback, L/R arrow keys should move playback cursor instead of selection

### ISSUE THREAD

**Issue by ArsenJazzPiano** [musescore/MuseScore#16519]
The playback cursor as it stands creates specific workflow issues. Previously in MuseScore 3 and prior, if you pressed the left/right arrow keys while in playback mode, the playback cursor would either go forwards or backwards and was dependent on the playback cursor position. This was good because there are many times where you want to listen to a whole section, and then skip to the next section by just holding right. Now, instead the playback cursor's position is dependent on what was last selected, meaning if you've selected a measure to start playback and have listened to, for example, 40 measures of music, and then want to skip the next 8 measures to listen to the next section, then that means you have to hold right for 48 measures, as opposed to just 8, or alternatively stop playback and scroll to the next section. Both options are slower than the previous functionality of the playback cursor. A viable solution would be to add preferences for the playback cursor to allow toggling between the previous functionality, or the current functionality.

Also, personal preference, I strongly dislike the smooth motion of the current playback cursor. There are many times where I want to actually see the beats getting "played" by the playback cursor. Again, a preference to toggle between old functionality versus current functionality is the most viable option to please all parties.

**Comment by Tantacrul** [comment]
I agree that the user's selection should not be taken into account when the score is being played. In that case, pressing right / left should just move the cursor forward / back from **it's current position**. It should not move the original selection as it does now.

I'm not going to comment on the smooth cursor here. That's a separate issue, which some may have differing feelings on. Let's not discuss that here and stick to one issue per ticket.

**Comment by Tantacrul** [comment]
I'm un-assigning myself, since I think the way forward is clear.

When a score is being played, pressing left or right should move the playhead's current position. It should not move the original note that was selected before play was pressed.
