### ISSUE TITLE
[MU4 Issue] Suggestion: Switch "Playback" and "Appearance" in Properties > General

### ISSUE THREAD

**Issue by GabeS573** [musescore/MuseScore#16513]
**Suggestion**
![image](https://user-images.githubusercontent.com/91428485/221042986-b06835fa-d9d0-4a7d-99c1-fe8592de6287.png)
In the General section of the Properties panel, there is a checkbox called "Play" in the right column, and a button called "Playback" in the left column. IMHO, it would make more sense for the "Playback" and "Appearance" buttons to be swapped so that the "Playback" button is directly beneath the "Play" checkbox.

**Comment by Tantacrul** [comment]
We're planning a general redesign of this section, which will make this ticket redundant. There's already [another ticket ](https://mail.google.com/mail/u/0/#inbox/FMfcgzGrcjSVrqqfxHdVzKbjmFTRqkDs?compose=FZxzwjpdknfQBJRprrzSklZZlrJjsjJJNlTcjVnGhRLMdHHqRbBfpknPrXvqtgknsphCDwRXGrMJfZlKxCcDhJbPgChxTSqmwKQxmhwmqLGzNmGnvNZhZXxlHqRxtdWxNcsRzFLMSnJTNKJhWCscHnrbScGbmzTfDgBcL)asking for changes on this specific area, so I'm going to close this one.

Thanks!
