### ISSUE TITLE
[MU4 Issue] Measures selected off-screen do not pan the camera to them even though "Pan Score Automatically" is enabled

### ISSUE THREAD

**Issue by ArsenJazzPiano** [musescore/MuseScore#16523]
Exactly what the title says. Regression from MU3 and prior.

1. Have measures that span 2 pages.
2. Select a measure on the 1st page, hold shift, and use the left/right arrow keys to also select measures on the 2nd page (off-screen).
3. Camera does not pan to the measures that are off-screen.

Expected behavior:
Camera should pan to measures off-screen on the 2nd page, as Pan Score Automatically is enabled.

Platform information:
 - OS: Windows

**Comment by MarcSabatella** [comment]
This is already fixed in 4.0.2 - see https://github.com/musescore/MuseScore/issues/14691
