### ISSUE TITLE
[MU4 Issue] Printing a part does nothing; saving the part to XML hangs.

### ISSUE THREAD

**Issue by aige02** [musescore/MuseScore#16537]
**Describe the bug**
Tried to print the Tenor 2 part; then tried to export that part as a PDF which could be printed.
1. Selecting the *Print* button did nothing.  Nothing was printed.  No print dialog was displayed.
2. Brought up the *Export* dialog.  The *Export* dialog popped up (but didn't have focus).  The *Tenor 2* part was selected.  Selected *PDF file*.  Clicked *Export...* in the dialog.  MU hug.

(Is there a way to get Windows to dump instead of just aborting?)

**To Reproduce**
1. Select the *Tenor 2* part.  (adjust the zoom to make part legible)
2. Click *Publish*.
4. Click *Print...*.  (click again if you wish; no response)
5. Click *Export...*.  (click on dialog to get focus)
6. In the *Format:*, select *PDF file*.
7. Click *Export...*.   (MU hangs!)

**Expected behavior**
1. Either default or previous zoom has been applied to part.
2. (NP)
3. Print dialog is display and part can be printed.
4. Dialog has focus when displayed.
5. (NP)
6. File selection dialog is popped up, allowing MU to save the part as a PDF.  

**Screenshots**
With the score in the attached ZIP, easily reproduceable.

**Platform information**
 - Windows 11
 - MuseScoreNightly-230530506-4.0.2-fa46d7f

**Additional context**
[ShinyStockings-hang-1.zip](https://github.com/musescore/MuseScore/files/10826661/ShinyStockings-hang-1.zip)

**Comment by zacjansheski** [comment]
I am unable to reproduce this in the current master.  Is this problem still actual?

**Comment by aige02** [comment]
I just tried it in 4.1.1.232071203 (Windows 11) and both appeared to work properly.

**Comment by zacjansheski** [comment]
Thank you!
