### ISSUE TITLE
[MU4 Issue] Space after commas and stops not recognised with .AppleSystemUIFont and SF Pro

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#16533]
**Describe the bug**
Related to [#10736](https://github.com/musescore/MuseScore/issues/10736).

Where the selected font is either .AppleSystemUIFont or SF Pro, MuseScore:

- Doesn't always enter spaces after commas and stops
- Doesn't always recognise the spacebar after a comma or stop

See video: https://www.dropbox.com/s/70twqwkfrwxzwd1/Screen%20Recording%202023-02-24%20at%203.48.56%20pm.mov?dl=0

**Expected behavior**
Spaces should be recognised after commas and stops (both in existing copy and on text entry)

**Platform information**
OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230551056, revision: github-musescore-musescore-530011b

**Comment by cbjeukendrup** [comment]
The solution is: 
1. Somehow grab macOS binaries of Qt 5.15.3 or higher (5.15.8 is the most recent one)
    - either build it ourselves, or use the one from HomeBrew
2. Upload it to the S3 server where we can download it in CI builds
3. If necessary, update some build scripts to use 5.15.8 instead of 5.15.2

**Comment by cbjeukendrup** [comment]
I think it would be nice to do this for 4.1, since the solution is already clear and actually it is quite trivial, and the problem is quite annoying and according to https://github.com/musescore/MuseScore/issues/17473 it's not just about commas and full stops.

**Comment by bkunda** [comment]
@cbjeukendrup if you can manage this, I would LOVE this issue to be fixed. It's one of those "trivial" problems that actually make the app look needlessly sloppy.

**Comment by cbjeukendrup** [comment]
@bkunda Could you please test #17772?
