### ISSUE TITLE
[MU4 Issue] When file is "dirty" because of changes in the Mixer, AutoSave marks it "saved"

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#16549]
**To Reproduce**
Prerequisite: AutoSave is turned on, preferably with a short time interval
1. Open an existing score
2. Make changes in the Mixer
-> the score is correctly marked "dirty", i.e. containing unsaved changes; this can be seen from the `*` that is appended to the title of its tab in the tab bar
4. Wait until AutoSave does its work
-> the score is incorrectly marked "clean".
4. Close the file
-> as a result of marking the score "clean", there is no popup asking "do you want to save the changes". So, MuseScore just closes the score without ever saving the changes to the real file (as opposed to the AutoSave file).
5. Reopen the file, to find out that the changes were indeed not saved to the real file.

**Expected behaviour**
Even though AutoSave "saves" the file to some hidden file, it should not mark the file as "saved", because the changes are not definitively saved to the original file.

**Platform information**
 - OS: macOS (N/A)

**Comment by DmitryArefiev** [comment]
Fixed in #16552
