### ISSUE TITLE
[MU4 Request] Select final slurred note instead of the slur (after adding a slur).

### ISSUE THREAD

**Issue by rich777300** [musescore/MuseScore#16546]
**Describe the bug**
Currently, when you use the shortcut 's,' a slur is added, but the slur is selected under the 'edit element' state, which is clunky.

**To Reproduce**
1. Go to a score
2. Select a note, and press 's'
3. Observe that the slur is the one that remains selected (in the edit element state)

**Expected behavior**
The last slurred **_note_** (be it a 2 or 10 note slur, whatever) should be selected, so using the arrow keys, you can quickly move on to another group of notes and continue the process of adding slurs.

I think the default position of slurs is usually good enough that we don't need to enter the edit element state as a slur is added. In fact, there doesn't seem to be a way (unless I'm mistaken) to easily use the keyboard to go from the edit element state of a newly added slur to one of the notes to keep moving forward. You have to use the mouse.

Edit: But that would make it slower to make a newly added slur invisible...?

**Platform information**
 - OS: Windows 10, 64-bit
 - MU4.0.1

**Comment by SteveBlower** [comment]
Having the slur remain selected allows the user to immediately adjust its range with SHIFT+ARROW.  This is the same behaviour for all lines and I don't see much advantage in changing it.

**Comment by rich777300** [comment]
> Having the slur remain selected allows the user to immediately adjust its range with SHIFT+ARROW. This is the same behaviour for all lines and I don't see much advantage in changing it.

Ahh interesting I usually select my notes first (Shift and arrow keys) before slurring so never thought of that.

**Comment by DaddyLudwig** [comment]
That’s what I used to do too. Now I tend to use the S key within note entry mode after seeing Marc Sabatella do the same thing in one of his livestreams.

**Comment by rich777300** [comment]
> That’s what I used to do too. Now I tend to use the S key within note entry mode after seeing Marc Sabatella do the same thing in one of his livestreams.

Interesting...it's a matter of different workflows I suppose. I usually enter only rhythm first, then add pitch, then articulations and whatnot so it's annoying to have to keep getting interrupted while adding slurs.

**Comment by DaddyLudwig** [comment]
I tend to do an all at once workflow when transcribing pieces(which I’ve been doing a lot lately), i.e. rhythm, pitch, articulation, dynamics, repeats, all while in note entry mode. For composition, I do pitch and rhythm simultaneously, then articulations, then dynamics, and then finally slurs.

**Comment by MarcSabatella** [comment]
FWIW I rarely think to add my slurs while in note Inuit, even though I know it’s a thing :-)

Probably a design could be devised where the focus upon adding a slur or other line depends on what was selected before.  If it’s a single note, then most likely people will want to extend the slur next, so having it selected makes sense.  If you started with a range selected, though, probably you’re good with the length already and are ready to move on.  But it’s tricky, because you might actually just want to do something else with that same range selection…

**Comment by rich777300** [comment]
>But it’s tricky, because you might actually just want to do something else with that same range selection…

Tricky indeed. I was working on something with lots of 2-note slurs when I wrote this issue but I can understand people doing a slur first and extending it.

**Comment by Tantacrul** [comment]
I definitely don't think we should move to a model where the slur becomes de-selected (while not in note input mode) for reasons given by @SteveBlower.
 
If we want to suggest new behaviour for slurs when the user is in NI mode, that would be interesting to see, for sure.

I'm closing this as a won't fix.
