### ISSUE TITLE
[MU4 Issue] On Arch Linux "Implode" behaves incorrectly directly after paste

### ISSUE THREAD

**Issue by bmarwell** [musescore/MuseScore#16551]
**Describe the bug**

Pasting two staves and calling "implode" right away will create voices 1 and 3, not one and two.
However, if you re-select the pasted part (ie the exact same selection),, it works like expected.

**To Reproduce**

1. Select two adjacent staves
2. Copy them
3. Paste them anywhere
4. Click on "Tools" => "Implode" and see voices 1 & 3 instead of 1 & 2 (see screenshots)

**Expected behavior**

Create voices 1 & 2.

**Screenshots**

Scenario 1 (buggy as described):

1. Paste

![2023-02-25T210327_screenshot](https://user-images.githubusercontent.com/1413391/221377473-a2e87440-9219-4d5b-870d-a4acf15f31df.png)

2. Implode

![2023-02-25T210754_screenshot](https://user-images.githubusercontent.com/1413391/221377477-da2017b2-b0ac-46da-adee-5a4e9572b1d9.png)

Now with the workaround to re-select staves

1. Re-select

![2023-02-25T210357_screenshot](https://user-images.githubusercontent.com/1413391/221377499-296961f0-6a18-4ac6-810a-ab769dbb316f.png)

2. Implode (now correctly): 

![2023-02-25T210409_screenshot](https://user-images.githubusercontent.com/1413391/221377500-6caed213-fa69-4d51-b75b-117101d7395b.png)

**Platform information**

OS: Manjaro Linux, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-, revision: github-musescore-musescore-7ef0732

**Additional context**

**Comment by L0uisc** [comment]
I can't reproduce on latest master. @bmarwell which version do you have? It would maybe be good to attach the score as well. You can attach a .zip or rename the file extension to .mscz.txt to let GitHub allow the file as attachment.

**Comment by bmarwell** [comment]
> I can't reproduce on latest master. @bmarwell which version do you have? It would maybe be good to attach the score as well. You can attach a .zip or rename the file extension to .mscz.txt to let GitHub allow the file as attachment.

Version is there, look closely.

You can use the zip file from here:

https://github.com/musescore/MuseScore/issues/16547

It's the score from the screenshot

**Comment by L0uisc** [comment]
@bmarwell thanks for the link to the scores. MuseScore claims all three scores in the archive (`Chorale für Blasorchester.mscz`, `Chorale für Blasorchester2.mscz` and `Chorale für Blasorchester 3.mscz`) are corrupt. Is the version of the score in which you found this issue still corrupt?

Furthermore, looking closely at your screenshot showing the issue with voice 3, the "Implode" created a copy of the bottom stave in both voice 2 and 3. That seems like a result of the corruption and not an issue on its own.

**Comment by bmarwell** [comment]
> @bmarwell thanks for the link to the scores. MuseScore claims all three scores in the archive (`Chorale für Blasorchester.mscz`, `Chorale für Blasorchester2.mscz` and `Chorale für Blasorchester 3.mscz`) are corrupt. 

Yes that's the other issue about. However, this happens to me even with new scores.

> Is the version of the score in which you found this issue still corrupt?

No, I created a new one and it happens there, too.

> > Furthermore, looking closely at your screenshot showing the issue with voice 3, the "Implode" created a copy of the bottom stave in both voice 2 and 3. That seems like a result of the corruption and not an issue on its own.

Are you sure? I never saw the implode function "deleting" the lower stave.

**Comment by L0uisc** [comment]
Ok, so I can't reproduce the issue, even with your corrupt scores from the other issue. There are two differences between our setups:

1. The OS. I am testing on Windows 10.
2. The version number hash differs. See below for my MuseScore version.

My version info in the About dialog is as follows:

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

I'm not sure what explains the difference, but I would've thought the revision should be the same for all OSes' 4.0.1 builds. One of the MuseScore team members will have to help here.

> Are you sure? I never saw the implode function "deleting" the lower stave.

I did not mean the lower stave was deleted. I meant the Implode result in your "buggy" screenshot copied the lower stave and pasted it in both voice 2 and voice 3 in the top stave. I.e. the bottom stave did not change, but the top stave got two copies of the voice from the bottom stave, one in its "voice 2" and one in its "voice 3".

**Comment by bmarwell** [comment]
> I did not mean the lower stave was deleted. I meant the Implode result in your "buggy" screenshot copied the lower stave and pasted it in both voice 2 and voice 3 in the top stave. I.e. the bottom stave did not change, but the top stave got two copies of the voice from the bottom stave, one in its "voice 2" and one in its "voice 3".

OH! I never noticed!




> OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

Yeah arch linux is a bit "special". They use their own build scripts and compile from source, maybe adding patches. I will try with an app image now.

**Comment by zacjansheski** [comment]
Could you please confirm this is still actual on Arch Linux? (Not reproducible on App Image)

**Comment by bmarwell** [comment]
I think this was related to corrupt scores from early 4.0.0 nightlies. I will close it because of this. I hadn't had this insight about corrupt scores when I opened this issue.
