### ISSUE TITLE
[MU4 Issue] Vertical and horizontal space is added to landscape score when printed

### ISSUE THREAD

**Issue by PetJer** [musescore/MuseScore#16553]
**Describe the bug**
Vertical and horizontal space (from the left and top) is added to landscape score when printed.

**To Reproduce**
1. Select a score
2. Right click $\to$ Page settings... $\to$ Select **Landscape**
3. Export then print or print directly (it has the same result)
4. Your printed score will have added space

In app (or in a **pdf viewer**) it looks like this:
![CMIM-landscape](https://user-images.githubusercontent.com/79419198/221377837-868b9aa6-767a-46d6-9e41-93f70e114818.png)

When printed:
![CIMIM-landscape-printed](https://user-images.githubusercontent.com/79419198/221377840-dc1de564-29f4-49ce-8ebc-24ce3304e482.jpg)

**Expected behavior**
The spacing in the printed score should be the same as in the app.

**Platform information**
 - OS: Windows 10

**Comment by cbjeukendrup** [comment]
Is it possible that this is caused by a mismatch of the page size of the score and the page size of your printer?

**Comment by PetJer** [comment]
Yes, my bad. I have a new computer and the default paper size was set to letter. Changed it, and it's cool now.
