### ISSUE TITLE
[MU4 Request] "To Coda" text should work in middle of measure

### ISSUE THREAD

**Issue by rich777300** [musescore/MuseScore#16558]
**Describe the bug**
The "To Coda" and all such related text can only be placed when the entire bar is selected (not any particular note), therefore, only performs the action (goes to coda) during playback after the _complete_ bar has finished. 

This is inconvenient because sometimes there's a rest before a pickup into some B section, let's say, and I want to go to the coda before the pickup (i.e. before beat 4 for example)...because I would find it confusing to have to play the beat 4 pickup and immediately switch somewhere halfway down the page for beat 1 of the coda...but maybe others won't?

MU4.0.1, Windows 10 64-bit

**Comment by SteveBlower** [comment]
This can be accomplished by splitting the bar at the To Coda jump point.  This would also be needed for a human reader to see where the To Coda jumps from.

**Comment by rich777300** [comment]
> This can be accomplished by splitting the bar at the To Coda jump point. This would also be needed for a human reader to see where the To Coda jumps from.

Would the split bar look weird when I'm not going To Coda (i.e. playing the first time through)?

**Comment by SteveBlower** [comment]
It would look even odder in the middle of a bar and would always be misinterpreted as a slightly misplaced instruction.   A player will **always** expect the To Coda to be at the **end** of the bar.  

Another way to go would be to put the To Coda instruction on the previous (full) bar and then copy whatever beats in the next bar you currently want before the coda starts to the start of the first bar of the coda, ,making that a full bar also.  

But, this is really not the place to discuss this.  This area of Github is reserved for bug reports and feature requests.  I know you started with an implied feature request, but that feature really makes no sense.  It will be better to discuss this in a new thread in the musescore.org forum where there is a bigger audience with more music theory knowledge.   Perhaps there is some other sort of notation that can indicate better what you are hoping for.

**Comment by rich777300** [comment]
> A player will always expect the To Coda to be at the end of the bar.

I’ve seen music where this isn’t the case but I think I agree with otherwise.
