### ISSUE TITLE
"Select More" is missing 2 options from MU3

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#16557]
The two selection-options, 
which are checked in the MU3-screenshot below,
are no longer available in MU4.

![image](https://user-images.githubusercontent.com/78870770/221388360-6dc38381-2992-4d1d-8bd6-58db97c5dc65.png)

At least "same bar" I would regard as very useful.

Discovered by trying:

https://user-images.githubusercontent.com/78870770/221388575-53e55c92-2928-4676-8d6f-3e1fe06115f7.mp4

**Comment by XiaoMigros** [comment]
'Same measure' and 'same beat' are both in 4.4, I believe this issue is resolved?

**Comment by cbjeukendrup** [comment]
Yes, it looks like it was implemented in https://github.com/musescore/MuseScore/pull/20137. Good catch!
