### ISSUE TITLE
[MU4 Issue] Crash when duplicating open parts

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#16566]
**Describe the bug**
MuseScore crashes when attempting to duplicate an open (I.e. created) part.
**Note**: Testing 4.0.2 patch release

**To Reproduce**

https://user-images.githubusercontent.com/86290556/221546640-43d98440-786e-4432-a5d9-1132487929dc.mp4

**Platform information**
OS: Windows 11 Pro, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230551516, revision: github-musescore-musescore-d23f054
Also reproduceable on macOS

**Additional information**
Only the opened score seems to crash; where multiple scores are open, other scores remain unaffected.

**Comment by Tantacrul** [comment]
Can reproduce on Win10

**Comment by DmitryArefiev** [comment]
Retested on Win10
