### ISSUE TITLE
[MU4 Issue] Delayed notes during playback in contrabassoon

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#16567]
**Describe the bug**
Testing 4.0.2, I've noticed a strange delay on tied notes in the contrabassoon (using Muse Sounds). I've isolated the issue and created an annotated file **[here](https://www.dropbox.com/s/boagcfzt72rh6qd/ContraBufoon.mscz?dl=0)**

This issue does not occur with MS Basic, so I can't definitively say it isn't a Muse Sampler issue.

**Platform information**
 - OS: Windows

**Comment by bkunda** [comment]
Re-tested on Windows and can still reproduce the problem:

OS: Windows 11 Pro, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230601206, revision: github-musescore-musescore-48ac167

https://user-images.githubusercontent.com/86290556/222748800-024fded4-2f50-4338-ae63-a87ef08f9200.mp4

**Comment by bkunda** [comment]
Re-tested with updated MuseSounds. This has indeed been fixed.
