### ISSUE TITLE
[MU4 Issue] Pedal continues into next bar 

### ISSUE THREAD

**Issue by Nicholas-Wise** [musescore/MuseScore#16564]
In the screenshot below, the staccatto notes in the bar after the pedal Are held for 3 8th notes. 
I have tried shortening the pedal length but it still holds them. The only thing that seems to fix it is by copying a pedal assigned to a shorter length and pasting it onto the original spot--but this only works until another edit is made, which causes the intial problem to consistently happen again.

![image](https://user-images.githubusercontent.com/106282447/221439224-147890f2-afe1-4739-8584-f01acefcca3e.png)

**Platform information**
 - OS: Windows 10

**Comment by Nicholas-Wise** [comment]
I should've specified: 
It doesn't matter which voice the pedal is in. It still produces the error.
I've also tried shortening the note and found that as long as it is not on the last rest/note before the next bar the error doesn't happen

**Comment by zacjansheski** [comment]
Is this still actual? I couldn't reproduce on Windows 11.

**Comment by Nicholas-Wise** [comment]
> roduce on Windows 11.

It seems like this issue must have been resolved in an update since my posting as I just opened my file on the latest update and it is no longer apparent. Thanks.

**Comment by zacjansheski** [comment]
Thank you!
