### ISSUE TITLE
Chord symbol horizontal alignment not saved as default style

### ISSUE THREAD

**Issue by bebobebo** [musescore/MuseScore#16560]
MS4.0.1 on Windows 11  . Reported at https://musescore.org/en/node/345629

Repro
1. Select a note and use Ctl-K to enter a Chord Symbol above
2. Select the chord symbol and in the Properties Pane, set Text > Alignment (horizontal) to Centred
3. Click the ellipsis for alignment and select > Save as default style for this score
-> note that there is a single option for both horizontal and vertical alignments.
-> note that this symbol is now centred, but no other chord symbols in the score are centred
4. To confirm, repeat steps 1 and 2 for another note
-> note that the horizontal alignment stays as left.

Work-around: Style settings > Text styles > Chord symbol : set the horizontal alignment

**Comment by bebobebo** [comment]
Re-opening as a bug report (this option was not available when I filed this issue)

**Comment by cbjeukendrup** [comment]
> Re-opening as a bug report (this option was not available when I filed this issue)

That's okay but not necessary. The new issue forms are only relevant while writing the issue initially, but once the issue has been created, there is nothing special about it anymore, so it is not more valid than existing issues.
