### ISSUE TITLE
[MU4 Issue]  Parts button has uninformative tooltip

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#16573]
### Issue type

UI bug

### Bug description

If you mouse over the Parts button in the toolbar an uniformative tool tip is displayed which reads:

Parts
parts...

That information repeated twice seems severe overkill when the button label itself gives the same information.

It might be more useful if the tooltip read

Show/hide/rename parts

or 

Mange parts

### Steps to reproduce

Place mouse cursor over Parts button
Read the uninformative tool tip

### Screenshots/Screen recordings

![PartsTooltip](https://user-images.githubusercontent.com/60138048/221617042-1fbf08c1-a83e-4159-a983-f58b1f33b6e9.jpg)

### MuseScore Version

4.0.1

### Regression

Choose option...

### Operating system

Windows 10

**Comment by rich777300** [comment]
This issue happens with the rewind, play, and loop buttons too in the play panel...and the two toggle loop marker buttons if you undock the play panel.

Windows 10 64-bit
MS Version:
![image](https://user-images.githubusercontent.com/102642087/221736022-44372265-d828-4df8-ac78-620773b246a5.png)
