### ISSUE TITLE
[MU4 Issue] List View inside UI gallery collides with the Menu bar.

### ISSUE THREAD

**Issue by pratyaksh1610** [musescore/MuseScore#16577]
### Issue type

UI bug

### Bug description

When toggling to UI gallery under the DevTools, when scrolling through the list, it collides with the menu bar.

### Steps to reproduce

Go to DevTools -> UI gallery

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/76740999/221677914-7c1815b2-487c-4b7e-a028-de92f7d9516b.mp4

### MuseScore Version

4.1.0

### Regression

I don't know

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment]
Since this affects only the dev tools that are not exposed to users, this is automatically a P4. Feel free to create a PR to fix it. Should be one line of code.

**Comment by pratyaksh1610** [comment]
I will fix it soon.
