### ISSUE TITLE
[MU4 Issue] Uninformative tooltip

### ISSUE THREAD

**Issue by pratyaksh1610** [musescore/MuseScore#16579]
### Issue type

UI bug

### Bug description

The buttons are having  uninformative tooltip.

1. <i>Originally posted by </i> @rich777300
https://github.com/musescore/MuseScore/issues/16573#issuecomment-1447466167

2. Also the buttons in the "Publish" section i.e "Print", "Publish to MuseScore.com", and "Export" also has uninformative tooltip.

### Steps to reproduce

Hover over the respective buttons.

### MuseScore Version

4.1.0

### Regression

I don't know

### Operating system

Windows 10

**Comment by Tantacrul** [comment]
Can you please re-log this again. But next time, include the following information:

1. What exact buttons have uninformative tooltips
2. Why are they uninformative
3. Images, if needed

We will not accept issues that force us to do loads of detective work.
