### ISSUE TITLE
Another note input productivity improvement 

### ISSUE THREAD

**Issue by moogly81** [musescore/MuseScore#16586]
### Your idea

When in note input mode , assign the shortcut o ("change **O**ctave" ) to change the current note's octave. This could accelerate note input on the keyboard. 

It would ideally behave in a circular manner : 

type o --> note is moved up an octave
type o again -> note is moved down an octave(*)
type o again --> note is moved back to its initial pitch 

(*) 1 octave down compared to original note. Which means 2 octaves downs from the step 1

### Problem to be solved

Note input on the keyboard is not very efficient

**Comment by MarcSabatella** [comment]
Ctrl+Up/Down are already available to change octaves, and you only need to press Ctrl+Down once instead of twice to get the note an octave below.  So this seems a less efficient method than the one that currently exists.

**Comment by moogly81** [comment]
Yes ctrl+Up/Down works well, I use it. It's knit picking at this point, but I felt it was more user friendly to use a single shortcut. Note that I can assign o to octave up and I'm halfway there. 

But this is not important.

**Comment by Fristover** [comment]
I don't think any other shortcut is any more user friendly than the current shortcut, the one you propose doesn't seem to be too intuitive for new users (having to use the same shortcut 2 times to get different results is not really nice for a first time user), while ctrl+up/down makes sense even if you never tried the program before.

**Comment by moogly81** [comment]
You're right, I'll close it.
