### ISSUE TITLE
Chord symbol horizontal alignment not saved as default style

### ISSUE THREAD

**Issue by bebobebo** [musescore/MuseScore#16599]
### Issue type

UI bug

### Bug description

Cannot set Chord Symbol horizontal alignment as score default from within Properties pane. Feature exists but doesn't work.

### Steps to reproduce

Select a note and use Ctl-K to enter a Chord Symbol above
Select the chord symbol and in the Properties Pane, set Text > Alignment (horizontal) to Centred
Click the ellipsis for alignment and select > Save as default style for this score
-> note that there is a single option for both horizontal and vertical alignments.
-> note that this symbol is now centred, but no other chord symbols in the score are centred
To confirm, repeat steps 1 and 2 for another note
-> note that the horizontal alignment stays as left.
Work-around: Style settings > Text styles > Chord symbol : set the horizontal alignment

### MuseScore Version

4.0.1

### Regression

I don't know

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
Reproduced in 4.0.2.
Fixed in current nightly
