### ISSUE TITLE
Copyright dates should be updated

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#16591]
#### Issue type

Other type of issue

### Bug description

Copyright dates should be updated to 1999-2023

### Steps to reproduce

![Capture](https://user-images.githubusercontent.com/90187801/221848415-97a55694-36ab-4fd1-9e91-c5f7f2aa2beb.PNG)

![Capture2](https://user-images.githubusercontent.com/90187801/221847707-812ac6a7-8c44-46ed-93b2-7a2f12845f76.png)

### MuseScore Version

4.0.2

### Regression

Occurs in 4.0.1
Doesn't occur in 4.0.0 

### Operating system

Win/Mac/Lin

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/15725
