### ISSUE TITLE
Deletion of last four bars and then an undo results in inability to form a blue rectangle.

### ISSUE THREAD

**Issue by grigorax** [musescore/MuseScore#16600]
### Issue type

UI bug

### Bug description

The test score has a last 'bar' consisting of 4 empty bars consolidated (= bars 11–14).

When bars 11–14 were deleted, and then restored by Undo, it was no longer possible to do a selection by means of a blue rectangle. Also playback in bars 7–8 was affected. 

The problem appears to be fixed by closing and re-opening the score.

[Original score.mscz.zip](https://github.com/musescore/MuseScore/files/10858413/Original.score.mscz.zip)

### Steps to reproduce

1. Select the consolidated bars 11–14.
2. Press CMD-DEL.
3. This operation is successful.
4. Press CMD-Z (Undo).
5. The operation appears to be successful.
6. Select any bar by clicking in blank space: Nothing happens.
7. Do playback from the start: Everything is OK, except that bars 7–9 do not play back correctly.
8. Do save and close,
9. Re-open the score. — It works once more.

### Screenshots/Screen recordings

![Screenshot 2023-03-01 at 8 23 53 pm](https://user-images.githubusercontent.com/94578785/222099763-82beeea1-ddf1-4a11-abfe-5e59ad62916b.jpeg)

### MuseScore Version

OS: macOS 13.2, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

Choose option...

### Operating system

MacOS 13.2.1

### Additional context
I originally performed this test on the same score but without the repeat signs. The result is a program crash. I have not reported this case, as the score in this case is a bit meaningless. I am assuming that this would not be a of great interest at this stage.

**Comment by grigorax** [comment]
Here is a simpler score for this problem.
<img width="1003" alt="Screenshot 2023-03-01 at 10 33 28 pm" src="https://user-images.githubusercontent.com/94578785/222128151-d3670de0-1f0d-4976-a962-4ff9f08d521f.png">

[Multimeasure Rest Deletion Problem.mscz.zip](https://github.com/musescore/MuseScore/files/10860472/Multimeasure.Rest.Deletion.Problem.mscz.zip)

**Comment by zacjansheski** [comment]
I reproduced this issue in 4.0.1
It is no longer reproducible in 4.1.1 or nightly, I will close this issue. Thank you for reporting!
