### ISSUE TITLE
Information copied from Help > About contains incorrect OS information

### ISSUE THREAD

**Issue by GabeS573** [musescore/MuseScore#16618]
### Issue type

UI bug

### Bug description

The OS information copied from Help > About contains the wrong OS name and version. It says "OS: Windows 10 Version 2009" when my OS is Windows 11, version 22H2.

### Steps to reproduce

1. Go to Help > About
2. Click the Copy button next to "Revision"
3. Paste the contents into a text editor

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/91428485/222302006-4a33b59f-d710-4671-8152-49a4c68591e6.png)

![image](https://user-images.githubusercontent.com/91428485/222302040-8c45678e-ba38-4217-9697-eae4e56a4b00.png)

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230551516, revision: github-musescore-musescore-d23f054

### Regression

I don't know

### Operating system

Windows 11 Home, version 22H2, OS build 22621.1265

**Comment by octopols** [comment]
This is what I found related to the issue [QT Bug](https://bugreports.qt.io/browse/QTBUG-99225)

**Comment by Jojo-Schmitz** [comment]
It indeed is Qt's fault, we're using their OS detection.
So this will get fixed onece we move to Qt 6.x, see https://github.com/musescore/MuseScore/pull/10108

**Comment by Jojo-Schmitz** [comment]
See #16649
