### ISSUE TITLE
Frames: "Margin" should be renamed "Padding"

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#16625]
### Your idea

In CSS (and WPs such as LibreOffice) "Margin" is used to describe the space _around_ an element and "Padding" that _within_ the element.

In MS frames "Left margin" and "Right margin" are currently the values of space _inside_ the frame and therefore should actually be named "Left Padding" and "Right Padding".

### Problem to be solved

It would make the MS terminology consistent with its usage elsewhere on the internet.

**Comment by pratyaksh1610** [comment]
Can I work on this ?

**Comment by cbjeukendrup** [comment]
Yes, feel free! 

(@bkunda could you please check if you agree with this idea? To me it would make sense, since "padding" seems to be used _everywhere_ to describe the space between a border and the content.)

**Comment by pratyaksh1610** [comment]
I will start working on this once @bkunda approves this.
