### ISSUE TITLE
[MU4 Issue] Graphics Usage Differences Potentially Linking to Playback Stuttering and Popping

### ISSUE THREAD

**Issue by LeafBusy** [musescore/MuseScore#16623]
### Issue type

Muse Sounds bug

### Bug description

Playback stutters and pops - the larger and longer the score seemingly the worse the issue becomes.
After some testing zooming in to only view a single bar on screen mostly resolves this issue, the result is seemingly similar when deliberately scrolling to the end of the score during playback.
Looking at task manager while doing this shows that when looking at the score regularly during playback GPU usage sits at around 2% whereas when zoomed in or scrolled to the end of the score usage rises to around 20-25% (this doesn't seem to be a completely consistant value but it does alway rise when zoomed or scrolled).
Further Testing Would Indicate the scrolling to the end "method" is dependant on how many bars are still on screen when scrolled there 

### Steps to reproduce

Have a score - the larger seemingly the better as the issue occurs more - running MuseSounds.

Press Play - Srackling and Popping Occurs

Then either zoom all the way in or scroll to the end of the score (will need to repeatedly scroll to prevent the playback bar jumping the image back)

The playback becomes considerably smoother

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/126777811/222424763-406dd259-3152-4bc0-abcb-e112b7364b8b.mp4

### MuseScore Version

4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

Windows 10 Home - 21H2

### Additional context

At one point discorvered two copies of Musescore 4 installed on my system - the issue was still present after uninstalling both and reinstalling musescore from MuseHub
Graphics Drivers were updated to their latest at the time of testing - GeForce Game Ready Driver Version 531.18 - 02/28/2023

### System Specs
Ryzen 7 3800X
32GB DDR4 Ram
MSI Geforce RTX 3080T

### Previous Versions 
My scores have played back smoothly on earlier versions of Musescore 4 but they have also not playback without popping and crackling on other versions

### Playback
Issue was experienced on all I/O buffers
Audio Driver is the Komplete ASIO (Komplete Audio 2)
Playback Issues were not experienced when switched to MuseBasic library

**Comment by en-programmerare** [comment]
I seem to have the same issue, but:
1. I experienced the issue when using MS Basic too.
2. I haven't tried using fewer instruments, but 4 clarinets triggered the issue.
3. Increasing the buffer size to 4096 fixes the problem completely for MS basic and almost fixes the issue for Muse sounds (some stuttering persisted, but was little enough that it didn't disturb the listening)
4. When the mixer is open, the issue disappears, even for lower buffer sizes.
5. Zooming in also fixes the issue, even for lower buffer sizes.


Windows 10
Musescore version 4.0.1, although the 4.0 version also had the issue.

**Comment by RomanPudashkin** [comment]
@LeafBusy @en-programmerare please try 4.1.1. Does the issue still exist there? Thanks!

**Comment by en-programmerare** [comment]
4.1.1 fixed the issue for all my scores, even if I put the buffer size back to 1024.
The largest score I have tested has 4 parts and around 320 measures, and it plays smoothly.
