### ISSUE TITLE
[MU4] Help -> About: untranslatable string (4.0.2-dev 48ac167)

### ISSUE THREAD

**Issue by Gootector** [musescore/MuseScore#16637]
### Issue type

UI bug
strings

### Bug description

String:
text: qsTrc("appshell/about", "Copyright © 1999-2023 MuseScore BVBA and others.\nPublished under the <a href=\"%1\">GNU General Public License version 3</a>.")
in src/appshell/qml/AboutDialog.qml is untranslatable.

### Steps to reproduce

Click Help -> About in any language in version 4.0.2-dev 48ac167.

### MuseScore Version

4.0.2-dev 48ac167

### Regression

I don't know

### Operating system

Windows 11 22H2

**Comment by cbjeukendrup** [comment]
Oh... this is because in the 4.0.2 branch, the copyright year was changed after the strings had been pushed, so now that changed string is not on Transifex.

I have just pushed it, so that people can translate it, but I'm not sure whether the string will make it into the release.

**Comment by Jojo-Schmitz** [comment]
Is `MuseScore BVBA` still correct?

**Comment by Gootector** [comment]
@cbjeukendrup OK. Thanks. Now is OK.
@Jojo-Schmitz musescore.org: © 2023 MuseScore BVBA; musescore.com: © 2023 MuseScore Ltd... from Cyprus (tax haven, yeah!). In the next year: Lucasfilm Ltd, read: Mickey Mouse. And rebranding: MouseScore 😂🤣
Greetings to You, Guys!
