### ISSUE TITLE
Paste Half Duration Crash Bug (MuseScore 4.0.1)

### ISSUE THREAD

**Issue by 3uclid** [musescore/MuseScore#16630]
### Issue type

Crash or freeze

### Bug description

When pasting half-duration from the clipboard, **specifically** when there aren't enough current measures remaining in the score to hold all the measures on the clipboard, MuseScore will crash rather than appending the needed measures (as it usually does on a normal paste).

### Steps to reproduce

1. Copy a number of measures from one place in a score, or from a separate score.
2. "Paste half duration" (ctrl+shift+Q) in the end of a score such that the length of the pasted content would exceed the current length of the score.
3. MuseScore freezes, then crashes.

### MuseScore Version

4.0.1-230121751 (64-bit)

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 10 Version 2009

**Comment by Jojo-Schmitz** [comment]
I can't reproduce with 4.0.2-230601206

**Comment by 3uclid** [comment]
@Jojo-Schmitz I don't have 4.0.2 yet; perhaps it's already been patched.

**Comment by Jojo-Schmitz** [comment]
Try 

* WIN - https://github.com/musescore/MuseScore/suites/11278379367/artifacts/578408840

**Comment by cbjeukendrup** [comment]
@3uclid Can you still reproduce this in 4.0.2?

**Comment by 3uclid** [comment]
Just checked-- the issue was resolved in 4.0.2.
