### ISSUE TITLE
Untranslatable strings in the 'corruption details'

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#16643]
### Issue type

UI bug

### Bug description

When loading a corrupt score a dialog pops up, and has a "show details" button, press that and see the issue

### Steps to reproduce

1. Open a corrupt score
2. Click on the show details button

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/1786669/222702378-d5b78c22-90c9-42ff-ab9b-1613b0e59c50.png)

### MuseScore Version

4.0.2-230601206

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
I don't understand why thpugh, the corresponding strings are all 'decorated' with `mstcs(...)`

**Comment by Jojo-Schmitz** [comment]
Is it caused by `errors << mtrc(`...)`, maybe?

**Comment by cbjeukendrup** [comment]
It was really something in the details... see #16651 😄

Since the corruption details section is one of the "flagship features" of 4.0.2, I think it woud be great to include this in 4.0.2 too, so that translations will also be correct.

**Comment by Jojo-Schmitz** [comment]
Oh, that 'easy'...

**Comment by bkunda** [comment]
@cbjeukendrup Just re-tested in the latest 4.0.2. The problem we identified yesterday with the unexpected dialog size persists: 

<img width="824" alt="Screenshot 2023-03-07 at 1 32 23 pm" src="https://user-images.githubusercontent.com/86290556/223423871-f3aea486-8e03-4f15-978a-df51ed37fbc2.png">

**Note**
- I have so far only triggered this when the app is set to German language
- It seems to only affect the save dialog triggered under these conditions:

1. User saves a "clean" (uncorrupted) file locally
2. Score becomes corrupted
3. User attempts to save changes locally (cmd/ctrl + S)

**Comment by Jojo-Schmitz** [comment]
But that's not at all what this issue is about, it is about the untranstated strings seen when using the "Zeige Einzelheiten" dialog

**Comment by Jojo-Schmitz** [comment]
And the size (here I guess the width) is apparently determined by the width of these buttons, which in turn depend on the length of the translated string. And here indeed German is a bit on the wordy side

**Comment by bkunda** [comment]
Yes we understand that @Jojo-Schmitz 🙂
@cbjeukendrup I can confirm that the translated strings in the "show more" popup now work correctly. 
We do need to fix the issue of the dialog size being borked in the German language dialog. I'll raise this separately and if either you or @RomanPudashkin can get to it as soon as you can, that would be terrific.  🙏🏻

**Comment by Jojo-Schmitz** [comment]
;-)
What then is unxepected about that dialog's size? The width is exactly what is needed. OK, the height could get reduced, maybe?

**Comment by bkunda** [comment]
> ;-) What then is unxepected about that dialog's size? The width is exactly what is needed. OK, the height could get reduced, maybe?

The height is very obviously far greater than it should be

**Comment by Jojo-Schmitz** [comment]
But wouldn't a super wide but flat dialog look rather wierd? I mean shouldn't there be some reasonably width-to-height ratio?
