### ISSUE TITLE
Crash when Tubular Bells play notes with accidentals in measure with quiet dynamics

### ISSUE THREAD

**Issue by opExe** [musescore/MuseScore#16642]
### Issue type

Crash or freeze

### Bug description

MuseScore crashes when you try to play a staff that uses the Tubular Bells instrument from Muse Sounds. This happens with the dynamics *mezzopiano*, *piano*, *pianissimo*, and so on. Further, this seems to only apply to notes with a higher pitch than C5 (c'') but lower than E5 (e''), with an accidental (or a key signature) that raise or lower the note by a semitone. Also, there has to be at least one other note in the measure. Please see the image for an example.

### Steps to reproduce

1. Create a score with chimes.
2. Make sure that the playback is set to Muse Sounds and that the instrument "Tubular Bells" is used.
3. Input two or more notes, of which one must have an accidental and have a higher pitch than C5 but lower than E5.
4. Add the dynamic *mezzopiano*, *piano*, or *pianissimo* to the note that has an accidental.
5. Try to play the measure.
6. MuseScore crashes.

### Screenshots/Screen recordings

For example, trying to play this will always cause a crash:
![screenshot](https://user-images.githubusercontent.com/78845603/222692945-58c47b8d-f1d1-4ff2-b88b-c12f8ec4c3ac.png)

### MuseScore Version

I used the nightly build 4.1.0.230610315, revision 8319ad5. The bug is also present in 4.0.1.

### Regression

No.

### Operating system

Windows 11

### Additional context

This seems to be the same bug as #14774.

**Comment by zacjansheski** [comment]
Closing now that Muse Sounds has been updated. Please let us know if the issue persists.
