### ISSUE TITLE
Position of articulations is incorrect in imported MusicXML files from Reaper

### ISSUE THREAD

**Issue by tohubohu38** [musescore/MuseScore#16658]
### Issue type

Engraving bug

### Bug description

Bug : After an export from reaper to musescore, the staccato dots are not positioned at the right place in musescore. 

Reaper : Good staccato positioning
[img]https://i.imgur.com/LqnL1nN.png[/img]

Musescore : bad positioning of staccato except for one note
[img]https://i.imgur.com/D16d5wo.png[/img]

expected : Staccato dots must be in the same places on musescore and reaper

### Steps to reproduce

Open the .xml that comes from reaper as an attachment and import it into musescore 4.0.0

### Screenshots/Screen recordings

Reaper : Good staccato positioning
[img]https://i.imgur.com/LqnL1nN.png[/img]

Musescore : bad positioning of staccato except for one note
[img]https://i.imgur.com/D16d5wo.png[/img]

### MuseScore Version

4.0.0

### Regression

I don't know

### Operating system

Mac OS 10.15.7

### Additional context

Example MusicXML file (in zip): 
[staccato.zip](https://github.com/musescore/MuseScore/files/10921717/staccato.zip)

**Comment by Jojo-Schmitz** [comment]
Reaper : Good staccato positioning
![image](https://user-images.githubusercontent.com/1786669/222919726-24815793-d958-4464-a6c6-6c07e0d2e08d.png)

Musescore : bad positioning of staccato except for one note _(and even there too far)_
![image](https://user-images.githubusercontent.com/1786669/222919759-29ea2714-d13e-490b-a5b7-08a4c416eced.png)

This is an import problem. And a regression vs 3.6.2:
![image](https://user-images.githubusercontent.com/1786669/222919879-aa4dc410-058a-47dd-a99d-3ec44c6ea1db.png)

**Comment by Jojo-Schmitz** [comment]
maybe @lvinken can sched a light?

**Comment by tohubohu38** [comment]
The problem also seems generalized to accents, marcato, tenuto...etc
![marcato](https://user-images.githubusercontent.com/83315564/222925643-01da33dd-dea7-4306-a059-2297e8f498b3.png)
![tenuto](https://user-images.githubusercontent.com/83315564/222925650-e84acfaf-c5b2-4988-8c3e-f83189d749e8.png)
![accents](https://user-images.githubusercontent.com/83315564/222925654-502eeec1-c632-45df-8156-b14c09f36583.png)

**Comment by Jojo-Schmitz** [comment]
And it isn't just 4.0.0, but also the latest 4.0.2 pre-release and current master too

**Comment by lvinken** [comment]
Have been looking into this, but did not yet found any plausible explanation. As far as I can tell, no relevant changes were made to the MusicXML importer. It may have (unknowingly) depended on assumptions that are no longer true, such as defaults.

**Comment by tohubohu38** [comment]
I hope you will find it because it's a big bug :)

**Comment by oktophonie** [comment]
If you save the imported file and then re-open it, the positioning is fine:
![image](https://user-images.githubusercontent.com/20604032/223690215-38334536-837a-43eb-9b25-b5fc730c4cd1.png)
which is, at least, a workaround - but we'll look into the source of the problem.

**Comment by lvinken** [comment]
Further debugging shows the MusicXML importer tries to set articulation placement based on the MusicXML placement attribute. In 3.6.2 this fails, resulting in placement "chord automatic". In 4.0.0 it succeeds (which explains the different behaviour) but the setting is not persistent. This is caused by a bug in function addArticulationToChord() in file importmxmlpass2.cpp, which does not set property ARTICULATION_ANCHOR to STYLED.

Notes:
- first steps towards a fix in https://github.com/lvinken/MuseScore/commits/issue_16658_experiment (for simplicity also removes the impact up/down has on placement)
- check: do we want "above/below staff", "above/below chord" for articulations (MusicXML does not explicitly distinguish between these) ?
- alternative: would we prefer to leave articulation placement styled ?

**Comment by lvinken** [comment]
Coding done, unit tests (iex_musicxml_tests) need some rework, will create a PR when done.

**Comment by tohubohu38** [comment]
How do we test?

**Comment by Jojo-Schmitz** [comment]
Or build yourself using the proposed code. I did: it works.

**Comment by Jojo-Schmitz** [comment]
There is no PR yet, that's why ;-)

**Comment by lvinken** [comment]
Pull request https://github.com/musescore/MuseScore/pull/16751.

To test, open attached MusicXML file. Observe articulations are imported as either chord auto, above chord or below chord depending on the placement and type attributes. Save in MuseScore format and reopen. Observe articulation placement is persistent.

[issue_16658_xml.zip](https://github.com/musescore/MuseScore/files/10950298/issue_16658_xml.zip)

**Comment by tohubohu38** [comment]
I don't really understand what you say to test.
but if I save the file and open it again, as we already saw, the articulations come to the right place :)
thanks

**Comment by Jojo-Schmitz** [comment]
In that form even Mu3 benefits from it ;-)
