### ISSUE TITLE
Trill line with grace notes after causes the grace notes to be trilled

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#16659]
### Issue type

Muse Sounds bug

### Steps to reproduce

1. Place any note of any length
2. Add some grace notes after it(used 2 in my test)
3. Add the trill line to the main note
4. Hear that the grace notes are also trilled

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/6530761/222920610-8d65c49b-beb9-4be3-9ffe-3bc6ce16e15d.mp4

### MuseScore Version

MuseScore 4.0.1

### Regression

I don't know

### Operating system

Windows 10

### Additional context

Muse Sounds only, MS Basic is fine in this regard.

**Comment by avvvvve** [comment]
I believe this is a duplicate of #15084 (also reported as #15120)

**Comment by avvvvve** [comment]
Closing, this is a duplicate of https://github.com/musescore/MuseScore/issues/15084 (also reported as https://github.com/musescore/MuseScore/issues/15120)
