### ISSUE TITLE
Crash when copy pasting cross staff notation containing tuplets

### ISSUE THREAD

**Issue by Attackoh** [musescore/MuseScore#16679]
### Issue type

Crash or freeze

### Bug description

When you paste cross staff notation into a staff that cannot cross, it will crash. 
For example, on a grand staff: bottom staff copy pasted onto the treble clef will crash, vice versa.
Pasting it onto a non grand staff will crash. 

### Steps to reproduce

1. Create grand staff
2. Write some cross staff beaming on one staff
3. Paste it onto the opposite staff, or onto a different instrument with only 1 staff
4. Crash

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/120669196/223281101-bf5f578e-0053-4684-8f86-c6df5c585fdf.mp4

### MuseScore Version

4.0.1-230121751

### Regression

I don't know

### Operating system

Windows 10

**Comment by oktophonie** [comment]
I couldn't reproduce this myself from creating a simple example (OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d); the behaviour was more or less what I expected. Maybe others can - but could you perhaps attach a file in which consistently encounter this?

**Comment by Attackoh** [comment]
Hmm, this would always crash for me yesterday, whether I was using the score above or creating a new one to test. It's a a bit less consistent now. For reference my machine is OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

Here's a file:
[crash test.zip](https://github.com/musescore/MuseScore/files/10919698/crash.test.zip)

**Comment by oktophonie** [comment]
Thanks, I can also reproduce it easily from this!
