### ISSUE TITLE
pizzicato sound does not stop (on non-string instruments)

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#16684]
### Issue type

Muse Sounds bug

### Steps to reproduce

See https://musescore.org/en/node/346143

### MuseScore Version

4.0.2-230601206

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

### Additional context

Maybe this could get resolved by adding a(n empty) Pizzicato section to .../src/framework/mpe/resources/general_voice_articulations_profile.json ?

**Comment by faskr** [comment]
This is more than a pizzicato issue. Distort does the same thing, and fade or bowing articulations for example don't stop on playback. It looks like this has to do with articulations being used outside their instrument families.

**Comment by Jojo-Schmitz** [comment]
Of course, all those articulations would need 'empty' definitions on instrument goups they don't apply to

**Comment by zacjansheski** [comment]
FIXED by https://github.com/musescore/MuseScore/pull/18891
