### ISSUE TITLE
The duplicate part still contains the instrument that was deleted from the master score (and that leads to corruption after adding measures)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#16686]
### Steps to reproduce

 

   1. Create score
    2. Open Parts dialog
    3. Duplicate some part and open the duplicate
    4. Go to the full score
    5. Open the "Add/remove instruments" dialog (rather than the instruments panel)
    6. Remove the instrument for which you duplicated the part and press OK
    7. Now, the duplicate part still contains the instrument that was deleted from the master score.
    8. Add measure -> corruption

----------Initial report------------
1. Open [corrupted part.mscz.TXT](https://github.com/musescore/MuseScore/files/10910102/corrupted.part.mscz.TXT) (remove ext.)
9. Add measure at the end
10. Save

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/90187801/223444395-959a6b50-5440-49df-9afe-d297ab630f37.mp4

### MuseScore Version

11.0.2

### Regression

No.

### Operating system

Win10

**Comment by marczellm** [comment]
In my experience this happens when
- an instrument is added to a part
- the instrument is removed from the score but the part referencing it still exists.

**Comment by cbjeukendrup** [comment]
@marczellm Thanks, it looks like that's exactly what happened in this score too. When removing an instrument, this instrument should also be removed from all part scores. I've created a fix to make sure we do that. Unfortunately, it looks like we cannot retroactively fix existing scores.

**Comment by cbjeukendrup** [comment]
@DmitryArefiev @marczellm I'm getting a bit confused because I can't seem to reproduce this situation (where an instrument is removed from the full score but still referenced in a part) in any new scores. Do you know perhaps a list of steps to reproduce this?

**Comment by mmarczell-graphisoft** [comment]
I'll try to repro later, but one piece of useful info might be this:
The file I experienced this on was originally created in Musescore 3.

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev @marczellm I'm getting a bit confused because I can't seem to reproduce this situation (where an instrument is removed from the full score but still referenced in a part) in any new scores. Do you know perhaps a list of steps to reproduce this?

@cbjeukendrup I can't reproduce it also. That strange score contains a a duplicated Soprano part with soprano stave (with notes) but Soprano is absent in the score. Probably, I was able to make it in some older build. I propose to close the bug for now. What do you think?

**Comment by cbjeukendrup** [comment]
@DmitryArefiev I tried a bit more, and now I could finally reproduce again! 
1. Create score
2. Open Parts dialog
3. Duplicate some part and open the duplicate
4. Go to the full score
5. Open the "Add/remove instruments" dialog (rather than the instruments panel)
6. Remove the instrument for which you duplicated the part and press OK
7. Now, the duplicate part still contains the instrument that was deleted from the master score.
8. Add measure -> corruption

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Oh, that's great! I can repro with that steps too. I'll add it to the description
