### ISSUE TITLE
View stave/part properties in the instruments tab

### ISSUE THREAD

**Issue by navickasm** [musescore/MuseScore#16696]
### Your idea

The Instruments window can be easily opened using the I key, however I want to be able to access the settings for any specific part in this window...

The instruments tab looks like this right now, ![image](https://user-images.githubusercontent.com/112985139/223587370-ea4396ea-6179-4f49-b601-46212cca874b.png)

and it would be nice if there was a button to allow me to edit the part like this...
![Screenshot 2023-03-07 182710](https://user-images.githubusercontent.com/112985139/223587858-db2eb0d4-fc2d-4194-9e22-def9c2ae51ea.png)

to get to this dialogue...
![image](https://user-images.githubusercontent.com/112985139/223588037-f8138e04-5f76-4b59-b02b-5fff981c250c.png)

### Problem to be solved

The inefficiency of scrolling to the start of the score and double clicking on the part.

**Comment by MarcSabatella** [comment]
It would be nice to get to the staff/part properties dialog more easily.  But note, the instruments dialog shows *instruments* not *staves*, and thus it's not really ideal to get at properties for individual staves (consider instruments with multiple staves).  On the other hand, to me, being able to getting to staff/part from the Instruments panel would make total sense.

Anyhow, you certainly don't have to scroll to the beginning of the score to get to staff/part properties - it's in the context menu.  So just right-click any measure at all to get there.  Also, if you ever do want to go back to the beginning of the score, no scrolling is required, Ctrl+Home does that in one click.

**Comment by cbjeukendrup** [comment]
For the reasons mentioned by Marc, I don't think this should be in the instruments dialog, since that has a different purpose. But in the instruments _panel_, it would make sense, and that has been requested already in #13328, among other issues. So I think we can close this one.
