### ISSUE TITLE
Command-line export of .mpos and .spos files is broken in MuseScore 4

### ISSUE THREAD

**Issue by KoenTanghe** [musescore/MuseScore#16710]
### Issue type

Other type of issue

### Bug description

Up to (and including) MuseScore 3.6.2, it was possible to use the command-line to export various files from a score, using the -o option (midi, wav, mp3, png, ...), following this documentation of the MuseScore command line options:  https://musescore.org/en/handbook/3/command-line-options

Most of these types of export still work, but the export of measure and segment position files (.mpos and .spos files) however does NOT work any longer in MusecScore 4.0..0 or 4.0.1.

### Steps to reproduce

1. Preamble: I did this on Windows 10 Pro, but it most probably is the same on macOS and Linux as well. MuseScore 3.6.2 and MuseScore 4.0.1 are installed and work properly.
2. Use the attached test score as an example: [La_Llorona.mscz.zip](https://github.com/musescore/MuseScore/files/10922176/La_Llorona.mscz.zip) (note: .zip was added for upload purposes, so you'll need to remove that extension again; the original file can also be obtained from: https://musescore.com/user/29343852/scores/6546801 )
3. Open a command prompt and first try the export with MuseScore 4.0.0 or 4.0.1:
    ```
    "C:\Program Files\MuseScore 4\bin\MuseScore4.exe" -o La_Llorona.mpos La_Llorona.mscz
    "C:\Program Files\MuseScore 4\bin\MuseScore4.exe" -o La_Llorona.spos La_Llorona.mscz
    ```
    Result: you do NOT get any output at all (.mpos and .spos files are NOT generated)..
4. Then try the export with MuseScore 3.6.2:
    ```
    "C:\Program Files\MuseScore 3\bin\MuseScore3.exe" -o La_Llorona.mpos La_Llorona.mscz
    "C:\Program Files\MuseScore 3\bin\MuseScore3.exe" -o La_Llorona.spos La_Llorona.mscz
    ```
    Result: you DO get the La_Llorona.mpos and La_Llorona.spos files as expected.

### MuseScore Version

4.0.1

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 10 Pro 64bit (latest updates)

### Additional context

**Original code**

The original code for this functionality (in branch 3.6.2) was here:
[https://github.com/musescore/MuseScore/blob/3.6.2/mscore/musescore.cpp#…](https://github.com/musescore/MuseScore/blob/3.6.2/mscore/musescore.cpp#L3715)
which then called into this code:
[https://github.com/musescore/MuseScore/blob/3.6.2/mscore/savePositions…](https://github.com/musescore/MuseScore/blob/3.6.2/mscore/savePositions.cpp#L51)

**Related info outside of GitHub**

This issue had already been discussed by another user ("Thibaultj") of this functionality here, while MuseScore 4 development was still in its early stages, but it never got fixed before the first 4.x release:
https://musescore.org/en/node/315219

It was also briefly discussed on the musescore.org issue forums, but I think it's best to have this stored in GitHub as a bug:
https://musescore.org/en/comment/1178056
Note that on that page, a PR is mentioned ( https://github.com/musescore/MuseScore/pull/13153 ), but from what I could see in that PR, mainly an extension name change from mpos / spos to mposXML / sposXML was committed in there. After I saw this, I also tried using the same command line as above, but using these other extensions, but that also did not work for me.:
```
"C:\Program Files\MuseScore 4\bin\MuseScore4.exe" -o La_Llorona.mposXML La_Llorona.mscz
"C:\Program Files\MuseScore 4\bin\MuseScore4.exe" -o La_Llorona.sposXML La_Llorona.mscz
```
So, that also seems to indicate that it's more than just the extension strings that changed.

**Use case**

See also the original report by user "Thibaultj" mentioned above.

In our case, we use these .mpos and .spos files in combination with the exported .png and .wav files to enable automatic score following on MuseScore files from live music performances in our desktop application "MusicFollower" (see SampleSumo website if you want more info, or ask me).

Not having the mappings of event IDs to locations on the images (which is what these files represent) basically makes it impossible to do our score following any longer (at least not with MuseScore 4), so for us this is a "breaking" change.

**Request for fix / alternative?** 

Can this useful functionality be restored please?
Or was this functionality perhaps transformed into something else (with the big changes for version 4), and can it be obtained in another way now from the command line?
I assume this kind of mapping data is also used for the "cursor" animations of the web site playback graphics?

**Comment by KoenTanghe** [comment]
@DmitryArefiev and team: thank you for the work on this issue and for keeping me in the loop.

I just did a very quick check, and these are my findings:

The commands from my "steps to reproduce" above to generate .mpos and .spos files seem to work again with this build: I do get an .mpos and .spos file now. So, that's good news!

When I do a diff between what I got for the same Musescore file with latest MS3 and with this MS4 build, I do see differences in the coordinates and sizes. This might be due to different layouts, or maybe untis changed, or something else. I haven't checked that at this point.
See attached screenshots below. I also added the generated files themselves (but had to add a .txt suffix in order to get them uploaded).

So, my conclusion for now: it seems like the functionality itself is indeed back now, and the files look like they are in the same format as before, but I'm not sure (yet) about the actual differences.

![diff_mpos](https://user-images.githubusercontent.com/872038/236270832-1932596a-6842-4b46-8da7-5faa8afdd110.png)
![diff_spos](https://user-images.githubusercontent.com/872038/236270848-09be8918-4cb8-4294-824a-dba3b5f9d559.png)

[La_Llorona_MS3.mpos.txt](https://github.com/musescore/MuseScore/files/11399641/La_Llorona_MS3.mpos.txt)
[La_Llorona_MS3.spos.txt](https://github.com/musescore/MuseScore/files/11399643/La_Llorona_MS3.spos.txt)

[La_Llorona_MS4.mpos.txt](https://github.com/musescore/MuseScore/files/11399645/La_Llorona_MS4.mpos.txt)
[La_Llorona_MS4.spos.txt](https://github.com/musescore/MuseScore/files/11399646/La_Llorona_MS4.spos.txt)

**Comment by KoenTanghe** [comment]
I now also just tested this with our own SampleSumo MusicFollower application (in beta) which calls these command-line commands, and it seems like import does work again now with this MS4 dev. build.

Visually, there is a clear difference, but that's most probably due to the changes in the layout engine.
And I believe when MS4 imports a score saved with MS3, it offers the option to "Select engraving improvements you would like to apply to your score" and it has the 2 checkmarks for "Our new notation font, Leland" and "Our new text font, Edwin" on by default, so I guess that's to be expected somehow.

Screenshots to show what I mean:

Score in our MusicFollower imported via MS3 commands:
![MS3](https://user-images.githubusercontent.com/872038/236320725-0a7b32f4-cb0c-47ea-9557-470ad7003b66.png)

Same score in out MusicFollower imported via this MS4 dev build commands (notice the somewhat strange placement of these rest symbols between the 2 staffs):
![MS4](https://user-images.githubusercontent.com/872038/236320737-263daa33-e6b2-4445-b351-40e352f4507a.png)

The strange thing is that the PNG images exported by MS4 also look different from what I see in MS4 itself, but that might have to do with default export settings perhaps (?):
![In MuseScore 4 1 0-dev](https://user-images.githubusercontent.com/872038/236320994-44c9944e-6a84-47a3-ae4a-82ec53e2500a.png)

If this is an issue in itself (I can't judge really), feel free create a new ticket for it.

Otherwise, I think we can this ticket can be considered solved once ends up in the next release?

**Comment by DmitryArefiev** [comment]
@KoenTanghe Yes, we have an engraving changes in MS4 and it effects layout, note position when export MS3 score to MS4 (it might look different comparing with v3)

Let's close the current bug then. Thank you for testing!
