### ISSUE TITLE
Poor user interface performance when editing score parameters

### ISSUE THREAD

**Issue by barnabycollins** [musescore/MuseScore#16724]
### Issue type

Other type of issue

### Bug description

Hey there - please let me know if there's already an existing issue for this; I couldn't find one.

I'm using MuseScore 4.0.1 to re-orchestrate [a large score](https://musescore.com/user/6543201/scores/5063369) on a reasonably powerful computer (Ryzen 7 2700X, 16GB DDR4-2400, GTX 1060 6GB, Windows 11), and I'm seeing really poor performance in the user interface. It seems to mostly happen when editing parameters that require re-rendering the score. For example, renaming an instrument takes ~7 seconds for each single-character change I enter. That is, I can type characters and they will appear fine, but the re-render on each character takes 7 seconds - meaning I can type, say, four characters fine but it will take ~28 seconds before all four characters are shown and the interface is responsive again.

I've noticed the same thing when editing things like the font size of the lyricist text, so my assumption is that my computer is re-generating the whole score every time there is a minor change. This happens on both Page View and Continuous View in my experience. I know the linked file is a MuseScore 2 file, but I've also tried using Save As and opening the new file (on the assumption that that would generate a 'fresh' MS4 file) and that doesn't seem to get me anywhere either. The file is saved on a Western Digital SN750 500GB NVMe SSD, so I wouldn't have thought the problem is disk performance.

Is this expected / normal behaviour, and if so are there any steps to reduce the impact? It's making MS4 pretty unusable for me right now. If there's any more information I can provide, please let me know.

I've also noticed it creates a spiking CPU load when 'catching up' after I enter characters into the instrument name field - this seems to match the cadence of screen updates; see image below:
![image](https://user-images.githubusercontent.com/23247109/224161828-4c675c0a-8fd6-4b0c-83be-854235fd0818.png)

### Steps to reproduce

- Download the score from [here](https://musescore.com/user/6543201/scores/5063369)
- Open the score in MuseScore 4.0.1
- Update an instrument name using the Instruments panel

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/23247109/224162573-4bdbf406-a3c3-4ee0-9280-348ce0de97a0.png)

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11 22H2 (22621.1265)

**Comment by RomanPudashkin** [comment]
@barnabycollins does this issue still exist in 4.1.1? Thanks!

**Comment by RomanPudashkin** [comment]
Closing, no response. Please open a separate issue for each performance problem (if you still can reproduce any). But things should definitely improve after these fixes:
https://github.com/musescore/MuseScore/pull/16409

Thanks!

**Comment by barnabycollins** [comment]
Hi there @RomanPudashkin - apologies for taking a while to respond; I've been away from my computer. Indeed, the issue seems to have been resolved in 4.1.1. Thank you very much!
