### ISSUE TITLE
Functional corrections to l.v. tie symbol (multiple notes per chord & default placement)

### ISSUE THREAD

**Issue by eitanmuir** [musescore/MuseScore#16726]
### Your idea

Hi MU4 team,

There are functional weaknesses with the l.v. tie symbol in MU4. My feature requests are below in order of priority (high to low):

1. l.v. ties should be added to multiple (or all) notes in the chord for any single voice.
2. Amend default placement of l.v. ties to match the start-point (and orientation) defined for slurs
3. Allow manual adjustment of length of l.v. ties

### Problem to be solved

Pardon any flawed technical knowledge, but I understand that the l.v. tie symbol is grouped in MU4 as an 'Articulation' with no further special treatment. As a result, the symbol exhibits the following key issues:

**1. [MODERATE] Only one single l.v. tie can be used on each chord, regardless of the number of notes.**
This is a significant issue when writing for percussion instruments and plucked/hammered strings.

**Workaround:** use duplicate Staff Text objects with Special Characters to add l.v. ties to every note in the chord. Requires manually matching font size to the Articulation object.

**2. [LOW IMPACT] Default placement of l.v. ties is incorrect**
This is a known issue but does get frustrating in large, percussion-heavy scores. Would be great to have a fix for this in the future!

**3. [LOW IMPACT] l.v. tie length cannot be manually adjusted**
This is just a 'finishing touch' feature that would really complete the l.v. tie functionality - sometimes we want ties over the barline and don't want to clutter up the note input workflow with multiple voices!

Thank you for reading and considering!

**Comment by oktophonie** [comment]
It's being thoroughly considered, don't worry ;)
Thanks for the accurate, helpful and thorough writeup! This issue exists already (sort of) as https://github.com/musescore/MuseScore/issues/16052 but I will close that one and refer to this instead.

**Comment by wizofaus** [comment]
2. seems to be done now in 4.4?  Still can't (easily) add multiple per chord though

**Comment by Dima-S-Jr** [comment]
It should be noted that #25435 solves only the issue of engraving. Playback is still unresolved. Therefore, I suggest removing the "Playback" label so that no one thinks that playback has been solved as well.
