### ISSUE TITLE
Corruption dialog becomes too tall when language is set to German 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#16728]
### Issue type

UI bug

### Bug description

The following corruption messaging dialog is badly resized (height is too tall) when the app language is set to German:

<img width="824" alt="Screenshot 2023-03-07 at 1 32 23 pm" src="https://user-images.githubusercontent.com/86290556/224290419-8ec4a250-88f4-410e-b93b-80f008f51469.png">

### Steps to reproduce

1. Set app language to German
2. Create a new score
3. Save the score locally
4. Enter some notes
5. Corrupt the score
6. Save the score

See dialog (shown in above image)

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/86290556/224290209-26ccab05-567f-4bae-a7a9-335f22529a98.mov

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651546, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

macOS 13.1

**Comment by Jojo-Schmitz** [comment]
FYI: I've now slighly shorted the translation for that right-most button, to "Zurück zum zuletzt Gespeicherten", maybe that helps already?
