### ISSUE TITLE
MS3.6.2 Format->Page settings freezes program for 100-110 seconds

### ISSUE THREAD

**Issue by gandsnut** [musescore/MuseScore#16736]
### Issue type

Crash or freeze

### Bug description

Ubuntu 20.04, tested in KDE/Plasma & XFCE4 desktops.  Attachments are from XFCE4 environ.

![sys_mon_during_playback](https://user-images.githubusercontent.com/29338195/224377847-08e2ae14-b8e1-478a-b050-eb3bad090770.png)

![sys_mon_format_page_settings_freeze](https://user-images.githubusercontent.com/29338195/224377883-69ae9b7f-171e-4ea9-9c0b-0b23f2a43d21.png)

### Steps to reproduce

Start program
Load score
(optional:  play score, rewind, open & close any menu item -- EXCEPT Format -- pop-up, then close)
Navigate to Format->Page settings
Wait until the pop-up window paints & becomes available
Click on any "Page settings" window item & change value
Wait another 100-110 seconds

### MuseScore Version

3.6.2.548021370  revision 3224f34

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Ubuntu 20.04 on Intel PC

### Additional context

A 3.7.x "development build" by Jojo-Schmitz manifests the same behavior.  4.0.x does not - but I have not done much testing in that version.   Reaching out to Qt message Forum for help with Qt suggests that whatever Qt exists on my Ubuntu, it is unlikely connected to this issue.

**Comment by Jojo-Schmitz** [comment]
Well, as 3.x won't receive further fixes, I guess this issue can get closed right away?
And what exactly is it a regression against?

**Comment by Jojo-Schmitz** [comment]
Anyway, if a fix is found, I'd certainly be interested to know about it

**Comment by gandsnut** [comment]
I thought 'regression' somewhat means "did it work before?" and yes, 2+ months ago there was no freezing.  Understood no fix is possible.  All I seek are suggestions what I can do to troubleshoot or understand my options.  3.6.2 is significantly hampered by this.  I've used it to produce 90+ scores.  I have 10-14 more scores to finish.  I have seen no suggestions on the .ORG Forum from others besides yourself.  Hoping to make this bad behavior go away.

**Comment by Jojo-Schmitz** [comment]
Well, 2 months+ ago it was also 3.6.2 (actually even 2 years ago), So at least it isn't a regression in MuseScore itself, but should be something on your cpomputer, your Linux distribution.

**Comment by gandsnut** [comment]
I believe the only group that can suggest WHAT I should do on my system are developers.  They appear my best resource to point me a certain way.

**Comment by oMrSmith** [comment]
Isn't that actually a progression rather than a regression, if it doesn't happen with MU4?

**Comment by gandsnut** [comment]
For any who might see this issue...  Yesterday I determined that MS3.6.2 - when run in the Ubuntu 'Budgie' desktop environment - has no "Page settings" freeze behavior.  This was surprising  & curious to me.  I will now try to analyze the configuration differences (as much as I can see / find them) between DE 'Budgie' and XFCE4, and perhaps KDE/Plasma.

**Comment by gandsnut** [comment]
In KDE/Plasma desktop, where the "Page settings" pop-up window is guaranteed to freeze, I find it curious that said window 1) shows up as a new icon on the desktop window list at bottom of the screen, but 2) in a terminal window, NO PID is created.

![big_screen_cap_showing_taskbar_added_icon_for_page_settings_while_frozen](https://user-images.githubusercontent.com/29338195/224576985-f7126680-2f4e-4219-8d55-ac4769bdfb29.png)

![terminal_window_capture_processes_before_during_after_freeze](https://user-images.githubusercontent.com/29338195/224577006-e418aad6-874a-4b98-b38f-dbfdee98adaa.png)
