### ISSUE TITLE
Random crash on program exit

### ISSUE THREAD

**Issue by laturetab** [musescore/MuseScore#16735]
### Issue type

Crash or freeze

### Bug description

Here is an example of a code pattern that is common in MuseScore that can a cause a crash when the program exits.

In UpdateModule.cpp, a pointer is declared static:

static std::shared_ptr<UpdateService> s_service = std::make_shared<UpdateService>();

Later in UpdateService::checkForUpdate a NetworkManager pointer is created as a member of "s_service"

After checkForUpdate finishes the NetworkManager pointer lives on.

When the program exits, the shared_ptr (above) is deconstructed at some random (out of our control) time. Sometimes this will cause QT to throw an exception in the destructor of NetworkManager.

In other words, "static shared_ptr<>" should be avoided. Perhaps moving these declarations into a class is the way to go.

The fix for this example is very simple: 
In checkForUpdate, do this:
INetworkManagerPtr manager = networkManagerCreator()->makeNetworkManager();

Instead of this: 
m_networkManager = networkManagerCreator()->makeNetworkManager();

### Steps to reproduce

In Visual Studio Debug (latest release)

loop:
Start Musescore, load a score, close Musescore.

Eventually it will crash in the destructor of NetworkManager. This will lead you back to checkForUpdate which leads to the static pointer being destructed during shutdown

### MuseScore Version

4.x Master (has occurred for at least last 4 weeks)

### Regression

I don't know

### Operating system

Windows 11, Visual Studio 17.5.1, Github Master, Debug

**Comment by Eism** [comment]
@laturetab 
> Sometimes this will cause QT to throw an exception in the destructor of NetworkManager.

can you reproduce it in the debugger and tell what exactly is the problem?

**Comment by laturetab** [comment]
@Eism 
Are you going to review this PR or should I just delete it. Sometimes I feel like I'm needlessly banging my head against the wall.
