### ISSUE TITLE
MusicXML Accent-Staccato Export

### ISSUE THREAD

**Issue by werneta** [musescore/MuseScore#16748]
### Issue type

Other type of issue

### Bug description

Notes marked with an accent-staccato articulation in the score are exported as staccato only.

### Steps to reproduce

1. Create a new score with any instrument
2. In a staff, add two notes
3. Select the first note, open articulations, and select "accent-staccato above"
4. Select the second note, then select "Staccato above"
5. Select the second note again, then select "Accent above"
6. Click File -> Export, set the format to MusicXML
7. Either open the exported MusicXML file, or  

### Screenshots/Screen recordings

A zip file with an mcsz and mxl is attached:
[accent+staccato.zip](https://github.com/musescore/MuseScore/files/10949794/accent%2Bstaccato.zip)

Measure from the mcsz file:
![image](https://user-images.githubusercontent.com/3794460/224519559-ffc0aa90-d62d-47c7-a035-a5d4d5423533.png)

Measure from the mxl file:
![image](https://user-images.githubusercontent.com/3794460/224519565-30295d99-2cac-4086-8bc0-43d9843dc639.png)

### MuseScore Version

MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

I don't know

### Operating system

Debian GNU/Linux bookworm/sid

**Comment by Jojo-Schmitz** [comment]
Confirmed. Same issue in Mu3.

           <notations>
          <articulations>
            <staccato/>
            </articulations>
          </notations>
 
vs.

        <notations>
          <articulations>
            <staccato/>
            <accent/>
            </articulations>
          </notations>

**Comment by Jojo-Schmitz** [comment]
The fix is in #8190, which has never been merged into master

**Comment by Jojo-Schmitz** [comment]
Or in #8514
