### ISSUE TITLE
Infinite Note Entry

### ISSUE THREAD

**Issue by cd1726** [musescore/MuseScore#16745]
Whenever I try to do any note entry in MuseScore, the first entry I make with either mouse or keyboard just repeats infinitely, as if MuseScore thinks I'm holding down a key (I'm not). 

The first two screenshots below show a new file, then selecting the note input option from the toolbar. Between the second and third screenshot, I clicked on the staff with my trackpad exactly once. The fourth and fifth screenshots show that MuseScore just continues to infinitely enter more F's until I close the program. For reference, the third through fifth screenshots were taken over a period of like one or two seconds.

As these new notes are infinitely being added, I do still have some amount of control over where they're going, I just can't stop more notes from being added. I can press the up and down arrow keys and the number keys to move the pitch around and change the rhythm as new notes are entered, but I can't stop the continuous note entry no matter what I've tried. 

Happy to add any further details to help troubleshoot as necessary. I'm not too familiar with what's needed to resolve issues like this, so go easy on me! I also realize it's possible there's just some problem on my computer, but that seems less likely than a MuseScore problem as I haven't had any similar issues with this computer while using other apps, including other music notation software.

OS: macOS 13.1, Arch.: x86_64
MuseScore version (64-bit): 4.0.1-230121751
revision: github-musescore-musescore-9b70a8c

<img width="1508" alt="Screenshot 2023-03-11 at 11 21 48" src="https://user-images.githubusercontent.com/107592987/224503134-e2597b79-0fc0-4c8b-a1b5-cc2868499506.png">
<img width="1508" alt="Screenshot 2023-03-11 at 11 21 58" src="https://user-images.githubusercontent.com/107592987/224503135-e36a7ac2-a9b2-46dd-bb28-b6c472794508.png">
<img width="1509" alt="Screenshot 2023-03-11 at 11 22 07" src="https://user-images.githubusercontent.com/107592987/224503138-c507b62f-fced-4ffe-8c91-52dbb0d9bf6f.png">
<img width="1511" alt="Screenshot 2023-03-11 at 11 22 09" src="https://user-images.githubusercontent.com/107592987/224503139-a01b5e17-dc26-441b-a389-7ff58ee65e39.png">
<img width="1509" alt="Screenshot 2023-03-11 at 11 22 11" src="https://user-images.githubusercontent.com/107592987/224503141-8af1ad7f-7d11-4c53-a34e-7d9ed0a6a712.png">

**Comment by cbjeukendrup** [comment]
I suspect that there is some  MIDI loop on your system. When you enter a note, MuseScore plays it, and when you have the MS Basic sounds selected, it also sends a MIDI signal to the output device that is selected in Preferences > I/O. So my theory is that this causes another MIDI signal to be sent back to MuseScore, which interprets it as note input. 

Which devices have you selected in Preferences > I/O?

**Comment by cd1726** [comment]
@cbjeukendrup Ah, this was exactly the issue. I think MuseScore was defaulting to a Loopback device I had set up for another program, which created this feedback loop you describe. Perfect. 

Thanks so much for the help.
