### ISSUE TITLE
Transport Panel, Undocked - Space keystroke toggles various settings rather than Playback

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#16740]
### Issue type

UI bug

### Bug description

The following Transport buttons toggle on a a Space keystroke when the Panel is undocked:

• the Play/Pause button
• the Loop playbck button
• the Metronome button
• the Gear/Settings button

I think it’s best if a Space keystroke *only* toggles playback (whether Playback is normal or looped)

Presently the user can click the Loop toggle button (in the undocked Transport) may immediately press Space to commence playback … but playback doesn’t occur because the Space keystroke toggles the Loop state again.

### Steps to reproduce

1) Open MuseScore 4.01
2) Undock the Transport
3) Click the Loop button
4) press Space to commence playback

Result: Playback does not occur. MuseScore toggle the Loop Playback setting.

### MuseScore Version

MS 4.01

### Regression

I don't know

### Operating system

MacOS 13.2.1

**Comment by DmitryArefiev** [comment]
Fixed in #16861
