### ISSUE TITLE
Pedal incorrectly applied to note after end of pedal (if there is only one note after end of pedal)

### ISSUE THREAD

**Issue by xsrvmy** [musescore/MuseScore#16757]
### Issue type

General playback bug

### Steps to reproduce

Enter this and play it with **MS Basic**. The last note gets held indefinitely.

![image](https://user-images.githubusercontent.com/7594338/224575314-94021e36-2c35-4dab-b57a-b89ea30bbb41.png)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/4ec5ae27-00d4-417b-9aca-fbd3cff3bdd2

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

Doesn't happen in **MS3**

### Operating system

Win 11

### Additional context

It seems that pedal playback through MIDI is currently implemented to end a CC64 value of 127 or 0 at the start of each note, and that when the bug triggers, 0 is sent correctly to lift the pedal, but immediately 127 is sent on the note after the pedal ends, leading it the pedal being held down incorrectly. Another manifestation of this same bug is to make the note after the pedal staccato, and a note after it, and note that the staccato doesn't actually play because it gets pedaled.

I ran into this issue with Pianoteq VST when working on a score, but I can't find a simple reproduction that breaks VST playback yet.
Note that there is no problem when using MuseSounds. There is also no problem when exporting MIDI as exporting doesn't produce the unnecessary CC64 events.

**Comment by bluebear94** [comment]
I think the note right after the pedal line is considered to overlap with the interval that the pedal line is active for. If you modify `SpannerFilter::spannerActualDurationTicks` to return `nominalDurationTicks - 1` for a pedal line, then this behavior no longer appears; however, this is a hacky solution.

There’s a comment saying that `spannerActualDurationTicks` is a hack that would no longer be needed once the “anchors” system is removed;

**Comment by Jojo-Schmitz** [comment]
Apparently a regression vs. Mu3

**Comment by DmitryArefiev** [comment]
> Apparently a regression vs. Mu3

Yes, confirm

The issue **occurs** if there is **only one note after end of pedal**. If there are two or more, the issue doesn't happen.

Added video to the bug description
