### ISSUE TITLE
Font point size fields in Properties panel only show/accept whole numbers

### ISSUE THREAD

**Issue by mart661331** [musescore/MuseScore#16764]
### Bug description

After typing font size of 8.5 for example, it is changed to 9.

### MuseScore Version

Version: latest nightly, March 13th 

### Regression

I don't know

### Operating system

Windows 11

**Comment by oktophonie** [comment]
Fractional point sizes can be set in the Style dialog. However, a (say) 8.5 point size will be shown in the Inspector as 9pt, and if 8.5pt is specified in the inspector, when the item is selected again, it will also show as 9pt.

**Comment by Jojo-Schmitz** [comment]
It is a regression vs Mu3. And 'just' an UI bug, internally the fractional setting is used, just gets rounded for display in the Properties tab (formerly Inspector). And it pertains to all texts.
Fractional values can get entered in the Properties and are taken, but again, they get rounded on next display.

Gut discussed on Discord some 3 weeks ago, see https://discord.com/channels/818804595450445834/818855201959051275/1078346948907646997 ff.

**Comment by mart661331** [comment]
I thought that too, but entering fractional size in properties panel, does
not make the font fractional size. i have tested it. 8.5 makes a 9 pt
fontsize

Op ma 13 mrt 2023 om 14:16 schreef Joachim Schmitz ***@***.***

**Comment by Jojo-Schmitz** [comment]
It does, check the score file, not the Properties panel display

**Comment by mart661331** [comment]
Yes - I am SORRY

**Comment by DmitryArefiev** [comment]
Fixed in #17083
