### ISSUE TITLE
Vertical box properties of templates are ignored

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#16761]
### Issue type

Other type of issue

### Bug description

When creating a new score, it resets the properties of the vertical box in the template.

### Steps to reproduce

1. create a template with first vertical box properties edited
2. use the template and create new score
3. see the first vertical box properties are reset

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz See https://github.com/musescore/MuseScore/issues/15858

**Comment by DmitryArefiev** [comment]
Fixed in #16762

Tested by editing scores in templates folder
