### ISSUE TITLE
4.0.2 crashes, seems related to auto-save

### ISSUE THREAD

**Issue by billlifferr** [musescore/MuseScore#16772]
### Issue type

Crash or freeze

### Bug description

Since installing 4.0.2 today, I can't use MuseScore for more than a few minutes before it crashes.

### Steps to reproduce

1. open a score
2. attempt to make edits or produce new material

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

macOS 13.2.1

**Comment by DmitryArefiev** [comment]
I have **13.2.1** too and don't have a crashes with **4.0.2**. 

@billlifferr Please attach a crash log

**Comment by billlifferr** [comment]
@cbjeukendrup Afraid I can't upload the score as I'm under an NDA for it. However, turning off autosave does seem to have fixed the issue - I've been going for 20 mins now with no issues. Not getting any crash logs.

**Comment by DmitryArefiev** [comment]
> However, turning off autosave does seem to have fixed the issue - I've been going for 20 mins now with no issues. Not getting any crash logs.

Interesting.. And that score is located on you internal drive or on a flash drive/external drive/cloud?

**Comment by MarcSabatella** [comment]
This may be obvious, but just in case - have you tried actually saving normally?  If autosave triggers a crash, there is an excellent chance a normal save will too.  So, you might want to test that before going too much further, if you haven't already.  Of course, without autosave on, you do risk losing work if the save crashes, but you've got to find out sooner or later I guess.

**Comment by billlifferr** [comment]
> > However, turning off autosave does seem to have fixed the issue - I've been going for 20 mins now with no issues. Not getting any crash logs.
> 
> Interesting.. And that score is located on you internal drive or on a flash drive/external drive/cloud?

Internal drive. There are samples on an external SSD, but even scores that don't use them were crashing.



> This may be obvious, but just in case - have you tried actually saving normally? If autosave triggers a crash, there is an excellent chance a normal save will too. So, you might want to test that before going too much further, if you haven't already. Of course, without autosave on, you do risk losing work if the save crashes, but you've got to find out sooner or later I guess.

Have been saving as I go (without autosave) and haven't had any issues.

**Comment by zacjansheski** [comment]
Closing as not reproducible and stale.  Feel free to open a new report if you have an issue in the latest version.  Thank you!
