### ISSUE TITLE
Version 4.0.2 is not working properly

### ISSUE THREAD

**Issue by Sulr221** [musescore/MuseScore#16784]
### Issue type

Crash or freeze

### Bug description

Windows 11, 16 GB Ram and Version is always crashing or freezing after adding new symbols.
 

### Steps to reproduce

1. Open a Sound file.
2. Copy a voice and paste it
OR
2. Type in some voices pitch after pitch and it is bugging
3. Attatches you ll find my diagnosis data

### Screenshots/Screen recordings

[000.zip](https://github.com/musescore/MuseScore/files/10962296/000.zip)

### MuseScore Version

4.0.2.230651553

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
Hello!

We don't have enough information from this report and logs.  Is this issue still present in the latest version?

**Comment by zacjansheski** [comment]
Closing
