### ISSUE TITLE
MuseScore not supporting SFZ anymore

### ISSUE THREAD

**Issue by lgmventura** [musescore/MuseScore#16788]
### Issue type

General playback bug

### Bug description

MuseScore 4 is not supporting SFZ instruments anymore. Unfortunately, although MuseSounds is amazing, it still lacks of many percussion articulations, as well as different cymbal sizes, prepared pianos etc. and my best workaround would be using SFZ instruments instead, especially because they are relative easy to create after recording or tweaking some samples. SF2 wouldn't work for that because they don't offer round robins, which is essential for percussive instruments.

### Steps to reproduce

1. Go to mixer and try to load any SFZ file stored in SoundFonts folder (preferences > folders)
2. SFZs won't show up

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Ubuntu 22.04

**Comment by DaddyLudwig** [comment]
I’m pretty sure this was planned for MuseScore 4 to only support sf3 and vst3 files directly as sf2, vst2, and siz are outdated.

**Comment by cbjeukendrup** [comment]
With SFZ specifically, there was an additional problem: the license of the Zerberus synth (GPL2?) was not compatible with the license of MuseScore 4 (GPL3). 

If you want to use SFZ files, the advice is indeed to use the Sforzando VST plugin.

**Comment by lgmventura** [comment]
VST is a Windows thing, I'm pretty sure.

**Comment by cbjeukendrup** [comment]
Ah, that's true. VST support on Linux has yet to come. It's at the top of the list of big things for which we would love contributions from the community, by the way.
