### ISSUE TITLE
[FEATURE] Tempo change lines should be recognised in MusicXML import

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#16797]
As gradual tempo changes have no explicit representation in MusicXML [somebody correct me if I'm wrong] this is really a question of _detecting_ them from their content and context, and then interpreting them as the new gradual tempo change item type that was introduced in MU4.

The more intelligent the behaviour can be, the better; in particular, a gradual tempo change line that ends with a new tempo should - at least optionally - be able to have its tempo change amount set automatically so that it reaches the new tempo.

This work is particularly important for situations where material is imported in a context where human intervention is impossible or impractical, e.g. material for MuseClass, Official Scores for musescore.com, etc.

**Comment by asattely** [comment]
This is fixed by https://github.com/musescore/MuseScore/pull/17257, which is ready for testing
