### ISSUE TITLE
Exit button disappears when Windows taskbar is set to hide automatically

### ISSUE THREAD

**Issue by opExe** [musescore/MuseScore#16794]
### Issue type

UI bug

### Bug description

When I set the Windows taskbar to hide automatically, the minimize, maximize, and exit buttons disappear from the Musescore window. Apparently, Musescore believes it's in full screen mode, which would normally be activated through **View** > **Full screen**.

### Steps to reproduce

1. In the Windows Settings app, go to **Personalization** > **Taskbar** > **Taskbar behaviors**
2. Activate **Automatically hide the taskbar**
3. Open Musescore and maximize the window if needed
4. The buttons in the upper right corner are now gone

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/78845603/224938090-d0856354-61a3-4a86-b03e-07bf7a3b5020.png)

### MuseScore Version

MuseScore version (64-bit): 4.1.0-230730304, revision: github-musescore-musescore-72553a2. Also present in 4.0.2. This did work in 4.0.1 though.

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

Windows 11

### Additional context

Possibly the same issue:
https://musescore.org/en/node/346571
https://musescore.org/en/node/346562

**Comment by cbjeukendrup** [comment]
Also related to #15749.

**Comment by opExe** [comment]
### Workarounds

I'm adding a number of workarounds here since there are a few people experiencing this problem. You can temporarily get the three icons back by pressing `F11` twice (or clicking **View** > **Full screen** twice). Of course, the simplest solution for now is to unhide the taskbar using the Windows Settings app.

**Close MuseScore**
- `Ctrl`+`Q`
- `Alt`+`F4`
- **File** > **Quit**
- `Alt`+`Space` and choose **Close**

**Restore**
- `Win`+`Downarrow`
- `Alt`+`Space` and choose **Restore**

**Minimize**
- `Win`+`Downarrow` (press two times)
- `Alt`+`Space` and choose **Minimize**

**Switch programs**
- `Alt`+`Tab`
- `Win`+`Tab`

**Comment by marczellm** [comment]
It's not just the buttons disappearing. The standard Windows gesture of touching the bottom border of the screen with the mouse to bring up the taskbar temporarily is also blocked.

**Comment by cbjeukendrup** [comment]
@marczellm That's a different issue though; or at least it is logged as https://github.com/musescore/MuseScore/issues/10958

**Comment by mralanng** [comment]
> ### Workarounds
> I'm adding a number of workarounds here since there are a few people experiencing this problem. You can temporarily get the three icons back by pressing `F11` twice (or clicking **View** > **Full screen** twice). Of course, the simplest solution for now is to unhide the taskbar using the Windows Settings app.
> 
> **Close MuseScore**
> 
> * `Ctrl`+`Q`
> * `Alt`+`F4`
> * **File** > **Quit**
> * `Alt`+`Space` and choose **Close**
> 
> **Restore**
> 
> * `Win`+`Downarrow`
> * `Alt`+`Space` and choose **Restore**
> 
> **Minimize**
> 
> * `Win`+`Downarrow` (press two times)
> * `Alt`+`Space` and choose **Minimize**
> 
> **Switch programs**
> 
> * `Alt`+`Tab`
> * `Win`+`Tab`

I tried all these command, all work fine except Alt + Space, the menu shown on left top corner, but the minimize and maximize were gray in color, I couldn't click them at all. For Win + Down Arrow, Alt+Tab. Win+Tab are very helpful.
Thanks for sharing. Best Regards

**Comment by opExe** [comment]
Oh, that's right; thank you. I've removed it from the post now.

**Comment by thomas-pike** [comment]
The window controls also disappear if the Musescore window is maximized on a screen without a taskbar (multi-monitor setup, taskbar on the other monitor, _not_ set to auto-hide).

**Comment by marczellm** [comment]
> @marczellm That's a different issue though; or at least it is logged as #10958

I'd think it's related or maybe even the same bug: Musescore mistakenly "thinks" it is in full screen mode when its size equals the screen size, and notifies the OS about it. The Windows feature is also activated that mutes notifications when you are presenting or playing in full screen.
