### ISSUE TITLE
[FEATURE] ANCHORS REDESIGN: Objects should no longer have to snap to a note or rest in a measure

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#16796]
This is a priority feature for 4.x that is essential for layout consistency. It will:

- Improve dynamic playback capability
- Greatly improve the UX of positioning elements on the score

Implementation of this is likely going to be dependent on the initial refactoring of libmscore.

This issue will be replaced with a design specification when it becomes available.

**Comment by MovableFormula** [comment]
It could just be a nightly build issue however are the dynamics also supposed to anchor to the new system? They show as if they do however are still locked to the front of a measure.
![Screenshot 2024-06-04 054530](https://github.com/musescore/MuseScore/assets/125432545/2b591bc0-48a9-493c-afd0-6aae00266d34)

**Comment by mike-spa** [comment]
@MovableFormula that's going to be fixed in https://github.com/musescore/MuseScore/pull/23046

**Comment by MovableFormula** [comment]
@mike-spa Awesome thanks!
