### ISSUE TITLE
MuseScore I/O audio related crash

### ISSUE THREAD

**Issue by MrFrinkles** [musescore/MuseScore#16806]
### Issue type

Crash or freeze

### Bug description

MuseScore crashes when removing or unplugging an I/O device from the PC.

### Steps to reproduce

1. with MuseScore open, go to preferences > I/O
2. change Audio Device from "System Default" to the audio device you are using and click "OK"
3. unplug said audio device
4. commence crash

### Screenshots/Screen recordings

https://youtu.be/AplUoPZ7ri4

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553

### Regression

I don't know

### Operating system

Windows 11

### Additional context

Note: I have not tried this bug with "System Default", although I do not use that option because it doesn't correctly output to the device my PC is using but instead to the other output (which is the laptop speaker in my case).

In the video, I try to show the crash by dragging the page in circles and unplugging the I/O while still dragging the mouse.

**Comment by zacjansheski** [comment]
Possibly related: https://github.com/musescore/MuseScore/issues/18161

**Comment by Eism** [comment]
@MrFrinkles Are you still reproducing the crash?
As I can see you are using USB audio interface (Behringer), I tested MuseScore with another USB audio interface (Focusrite Scarlett 2i2 3rd gen) and there is no crash. 

Maybe updating the drivers for your interface will help you.

Please check the latest release (https://github.com/musescore/MuseScore/releases/tag/v4.2.0-beta) and if you encounter crashes, please upload the diagnostic files (Menu -> Diagnostic -> Save diagnostic file).

**Comment by MrFrinkles** [comment]
Hello, I apologize for the very delayed response, but with the updates the issue has now been resolved.
Thank you so much for responding to my query.
