### ISSUE TITLE
[FEATURE] Audio.com upload integration

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#16802]
This task is to establish a flow in MuseScore for uploading audio directly to audio.com.

This issue will be replaced with a design specification soon.

**Comment by Tantacrul** [comment]
First pass design is done:
https://www.figma.com/file/IZ7TTcjlzgsN1mLbMfSkkL/MS4%3A-Upload-to-Audio.com?node-id=14%3A5817&t=kiBvvKAL6KTvNRGv-1

Please contact me in order to get a full explanation before proceeding with development.
