### ISSUE TITLE
[FEATURE] Make it possible to apply alternate tuning symbols (guitar)

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#16804]
This feature makes it possible to more simply apply and configure alternate string tunings. 

In addition to the existing **Edit string data** dialog, which will be retained, users can now apply string tunings from a palette element, which will make use of a configurable popup widget:

<img width="801" alt="Screenshot 2023-04-24 at 1 22 14 pm" src="https://user-images.githubusercontent.com/86290556/233982316-7c1da41f-7fa7-4a1c-a22a-7777fc9305a7.png">

Configuring alternate string tunings will also result in correct tablature fingering and an automatic adjustment to the instrument's pitch range (i.e. where the lowest string is tuned down, the playable pitch range will be adjusted accordingly so newly available notes don't get coloured in red). 

A full design specification will be sent directly to the development team. 

FYI
@alexpavlov96 
@abariska 
@oktophonie 
@mike-spa

**Comment by abariska** [comment]
🟢 **Developed**
