### ISSUE TITLE
[FEATURE] Implement support for multiple different dynamics on grand stave

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#16812]
For situations like this, MuseScore defers to the most recently placed dynamic and applies it uniformly to both staves: 

<img width="323" alt="Screenshot 2023-03-14 at 2 02 36 pm" src="https://user-images.githubusercontent.com/86290556/225011606-c0c64965-182b-4149-b832-3a2aad91103d.png">

What should happen instead is that the dynamics are recognised on a per-stave basis, meaning each stave should play back at the dynamic level indicated by any dynamic marks attached to it (Note this would also need to work where additional staves are added to the grand stave).

**Comment by L0uisc** [comment]
I seem to remember that this was partially implemented in MU3.x. One could set dynamics to affect the whole system, an instrument (all staves) or a single stave. I started looking into making dynamics with "voice" scope, but that's been 5 years ago, so I don't think it will be worth trying base anything from that.

**Comment by PROMAN-bit** [comment]
This is a feature musescore 3 had but I seem to remember you having to manually adjust it for it to work. Musescore 4 should have it on by default, and have the option to turn it off, because most people want the audio playback to be similar to how it would be played. When implemented this doesn't need to be off by default.

**Comment by cbjeukendrup** [comment]
@PROMAN-bit I doubt that. It's at least as common to have only one dynamic that should affect both staves. However, we could try to be smart by automatically making the dynamics per-staff when the user does specify a dynamic for each staff.

**Comment by bkunda** [comment]
A very good point @PROMAN-bit. I'll be bearing this in mind when it comes to design time.
Thanks for this input! 🙏🏻

**Comment by bkunda** [comment]
Closing because will be resolved in implementing a solution for #19137.
