### ISSUE TITLE
[FEATURE] Replace current loading screen when loading multiple instances of app (macOS)

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#16810]
This is a priority task for 4.1.

Note that it only partly solves the problem of multiple app instances currently experienced on macOS (see https://github.com/musescore/MuseScore/issues/12647 for more info). 

We intend to deal with the more complex problem of handling multiple app instances in a later version of MuseScore 4 (most likely 4.2).

For now, we intend to replace repeated displays of this loading screen with something that does not suggest the app is actually being opened again and again: 
 
<img width="805" alt="Screenshot 2023-03-14 at 1 52 32 pm" src="https://user-images.githubusercontent.com/86290556/225006886-67e53314-2a65-43c8-9066-88afbc7b055c.png">

(Note: this screen will still be displayed on open when no other instances of the app are already open).

**Comment by Tantacrul** [comment]
I'd suggest some kind of **"Opening score"** progress dialog of some kind.

**Comment by jessjwilliamson** [comment]
Designs are in 'MS4 LOADING SCREEN' in the Master project.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/71656189/235724539-f5ed9ecb-138d-40cd-8b7c-1316f6c57751.png">

**Comment by DmitryArefiev** [comment]
@bkunda This is only for MacOS? The only difference between master and this change is adding a progress dialog in the next instance of MS, right?

**Comment by DmitryArefiev** [comment]
Implemented in #17509
