### ISSUE TITLE
TASK: Remove 'Report a bug' option from help menu

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#16811]
Because we have now retired the old issue tracker on MuseScore.org, we should remove this option from the 'help' menu. Later, we can address needed changes to the forum and appropriate UI in MS4.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/21022311/225010827-0bcb75e6-21f5-4391-a4ed-1583a1a91aaf.png">

**Comment by HemantAntony** [comment]
@Tantacrul check #16818
