### ISSUE TITLE
MuseScore 4 64-bit without Muse Hub for windows doesn't work with WineHQ

### ISSUE THREAD

**Issue by ghost** [musescore/MuseScore#16820]
### Bug description

Musescore 4 for windows doesn't work with Wine ( version 8.3 )

### Steps to reproduce

1. Install wine 8.3
2. Run winecfg ( default )
3. Install musescore 4 ( MuseScore-4.0.2.230651553-x86_64.msi )
4. Run Musescore4.exe

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Gentoo

### Additional context

[musescore4-winehq-logs.txt](https://github.com/musescore/MuseScore/files/10971507/musescore4-winehq-logs.txt)

**Comment by RomanPudashkin** [comment]
Closing since there is this discussion
https://github.com/orgs/musescore/discussions/24072
