### ISSUE TITLE
Too many clefs and wrong tempo while importing BWW-File

### ISSUE THREAD

**Issue by michaelsiepmann** [musescore/MuseScore#16833]
### Issue type

Other type of issue

### Bug description

I've got a lot of BWW-Files, which I'd like to import to MuseScore. There are some issues with the imports. One is the start of the tune. Where there are 2 clefs and a wrong tempo.

### Steps to reproduce

Create a text-file "anyname.bww" and insert this code:

`Bagpipe Reader:1.0
MIDINoteMappings,(54,56,58,59,61,63,64,66,68,56,58,60,61,63,65,66,68,70,55,57,59,60,62,64,65,67,69)
FrequencyMappings,(370,415,466,494,554,622,659,740,831,415,466,523,554,622,699,740,831,932,392,440,494,523,587,659,699,784,880)
InstrumentMappings,(71,71,45,33,1000,60,70)
GracenoteDurations,(20,40,30,50,100,200,800,1200,250,250,250,500,200)
FontSizes,(90,100,100,80,250)
TuneFormat,(1,0,M,L,500,500,500,500,P,0,0)
TuneTempo,90
"Title",(T,L,0,0,Times New Roman,16,700,0,0,18,0,0,0)
"Type",(Y,C,0,0,Times New Roman,14,400,0,0,18,0,0,0)
"Composer/Arranger",(M,R,0,0,Times New Roman,14,400,0,0,18,0,0,0)
"Footer",(F,R,0,0,Times New Roman,10,400,0,0,18,0,0,0)

& sharpf sharpc 4_4
I! E_4 !I
`

Import this file.

### Screenshots/Screen recordings

![grafik](https://user-images.githubusercontent.com/26114608/225246381-c8cb0056-6d02-4f64-acb4-ad343cf5c6ca.png)

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

Windows 10

**Comment by Blargian** [comment]
Hi @michaelsiepmann, I started looking into the code for this one to see if I can write a fix. Just to help me understand - what makes you say that the tempo is wrong? From what I can see 90 is the tempo specified in the .bww file : `TuneTempo,90`. Or is the issue with the way it gets displayed "<sym>metNoteQuarterUp</sym> = 90"?

**Comment by Jojo-Schmitz** [comment]
I don't see the tempo at all, not in 3.6.2 mor in 4.0.2 or in the latest development build

Hmm, I do see it (in all version), when I drop the single quotes...

![image](https://github.com/musescore/MuseScore/assets/1786669/a78371ff-14ec-419e-a907-69e37caf56f6)

**Comment by sammik** [comment]
please, check #21796
