### ISSUE TITLE
MuseScore 4 install/update prevents embedded finder instances [Macbook Pro M1 Pro, macOS Monterey 12.3.1]

### ISSUE THREAD

**Issue by BaconWrappedShrimpWithEyes** [musescore/MuseScore#16831]
## Issue:

Upon installing or updating MuseScore 4, embedded Finder instances cannot be created.
### In this state:
- What works:
    - Opening files from Finder still works
    - Existing files can be saved to
    - the Finder app still works for navigation
- What does not:
    - Features such as Save As... which prompt with embedded instances of Finder do not work (apps hang for a couple minutes before giving up)
    - Opening an app (such as quick time player) which begins by prompting user with a finder window to find a file to open
    - Features such as Open File... from MuseScore or other apps which prompt for the user to choose a file from Finder
- What was tried:
   - It does not matter whether the app is picky about what files can be opened (such as MuseScore, QuickTime Player) or not (such as Discord, Chrome)
   - Relaunching Finder from Force Quit and quitting any other open apps does not fix issue
   - Quitting MuseScore does not fix issue
   - Restarting does fix the issue (until a new update occurs)
   - I was able to create a new text file in vim from the MacOS terminal, which does not use Finder, and this did successfully save to disk

## Steps to recreate:

On my laptop this has happened when:
- Installing MuseScore from MuseHub
- Installing MuseScore from the .dmg musescore.com
- Installing MuseScore from the disk image downloaded by the MuseScore 4 update prompt

This has always happened when installing or updating MuseScore 4

I have thus far always opened a .mcsz file immediately after downloading an update. I have not yet tested whether this issue persists if I were to first quit musescore 4 and reopen before opening a musescore file, or open another app which requires finder first.

No similar issue has occurred when installing on Windows

I do not have other Macs to test this with to know if this is unique to my device. I also have not tried it with other versions of MacOS. I have not been able to find evidence of this issue occurring online for other users.

## Full specs:

MacBook Pro 14-inch, 2021
Apple M1 Pro (10-core CPU, 16 Core GPU)
32 GB Memory
macOS Monterey 12.3.1 (21E258)
Internal and 1 external display
Most recent MuseScore revision used: 4.0.2 (Version string: `OS: macOS 12.3, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651546, revision: github-musescore-musescore-dbe7c6d`)

**Comment by William-Spector** [comment]
Correct, it regards the standard “open” dialogue, and it does persist accords other apps.

As noted, restarting fixes it.

**Comment by BaconWrappedShrimpWithEyes** [comment]
Correct, this regards standard open/save dialogues, and affects all apps which use such dialogues.

As noted, restarting fixes the issue.

**Comment by cbjeukendrup** [comment]
@BaconWrappedShrimpWithEyes Hi! I just came across this report again, and wondered if this is still happening. We haven't got any other reports of this so far.

**Comment by BaconWrappedShrimpWithEyes** [comment]
I've updated a couple times hoping I could capture anything when it's in this state and it hasn't happened again. I think I might've updated macOS since reporting this, but nevertheless I'm going to close this as cannot reproduce. Just weird that it happened twice
