### ISSUE TITLE
Trumpet MuseSound plays staccato when notes are accented

### ISSUE THREAD

**Issue by Baps-P** [musescore/MuseScore#16848]
### Issue type

Muse Sounds bug

### Bug description

Trumpet Muse Sound plays staccato when notes are accented

### Steps to reproduce

1. Create a trumpet Bb score
2. Activate MuseSounds profile
3. Select the Trumpet (singular) sound from MuseSounds
4. Write a tuplet of 3 quarter notes E, F, G and a half note G
5. Add an accent (>) to each note
6. Add a nuance of Fortississimo (fff)
7. Tempo 74
8. Play

The notes are to staccato

If you play this with the Trumpets (plural) sound from MuseSounds, no problem

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

No.

### Operating system

Windows 10

**Comment by bkunda** [comment]
Closing this as it appears to be a duplicate of #21267

**Comment by Valdessir** [comment]
Ah my bad. I totally missed the triplet part. Tested it and yep, the behavior is observed to happen, even when I haven’t marked dynamics on it yet.
