### ISSUE TITLE
Acciaccatura Sustains After Playing

### ISSUE THREAD

**Issue by osubuki** [musescore/MuseScore#16854]
### Issue type

General playback bug

### Bug description

Acciaccaturas appear to sustain longer than they should on MuseSounds playback under certain conditions.

### Steps to reproduce

1. Create a new score with a flute (MuseSounds)
2. Add a tempo marker at 160 bpm
3. Create a note on beat 1 with an accent or marcato
4. Add an acciaccatura to the note that has a different pitch
5. Start playback. The acciaccatura pitch will sustain much longer than necessary.

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

### Additional context

This doesn't seem to happen in MS Basic playback, nor does it happen for every MuseSounds instrument. I'm not sure what the "critical tempo" is, but this doesn't happen at 80 bpm and does at 160 bpm. It only happens when the note and acciaccatura are on the first beat of the first measure. It seems like the sustained pitch ceases when and only when it appears later in the piece.

**Comment by zacjansheski** [comment]
This issue is no longer present.
