### ISSUE TITLE
Rehearsal marks does not set as style and resets the style instead

### ISSUE THREAD

**Issue by Baps-P** [musescore/MuseScore#16850]
### Issue type

UI bug

### Bug description

When we change the alignement for a rehearsal mark, click "set as style" reset instead

### Steps to reproduce

1. On a score, add a rehearsal mark
2. Change the alignement from centered to left aligned
3. Click on "set as style"

It resets the style instead

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 10

**Comment by DmitryArefiev** [comment]
Tested on **latest 4.2.0 master**, Win10. It sets as style and after #19142 it **doesn't reset the style**

Closing
