### ISSUE TITLE
If a note is placed is low enough, a high note is played

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#16855]
### Issue type

General playback bug

### Bug description

If you place a note low enough, instead of a bassy low note being played back, a high note is. 

### Steps to reproduce

1. Choose an Instrument, say Piano
2. Add a C note
3. Press `Ctrl + Down` repeatedly until you hear a high sound

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/88136054/225530826-350eccc0-41c5-4360-a00c-be57426b1153.mp4

### MuseScore Version

Unstable prerelease for 4.1.0

### Regression

I don't know

### Operating system

Ubuntu 22.04

### Additional context

I use MS Basic

**Comment by cbjeukendrup** [comment]
I think this is covered by https://github.com/musescore/MuseScore/issues/16657

**Comment by zacjansheski** [comment]
Closing and referring to https://github.com/musescore/MuseScore/issues/16657
