### ISSUE TITLE
Add Fingering line (text-line with frame capability) to the "Fingering" palette

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#16876]
### Your idea

What I am calling a "fingering line" is a combination of a fingering symbol and a text-line, with the additional option to add a frame to the text.

### Problem to be solved

For example, it is used to indicate a run of notes on the same string (see image below), or a run of notes played by the right-hand-thumb and so on.

Example:

![string_number_line](https://user-images.githubusercontent.com/87246583/225882509-974e7415-e494-4604-b540-3975f6f37b8a.png)

**Comment by oktophonie** [comment]
Covered by #14238
