### ISSUE TITLE
One thread (or core) of CPU stopped working when MuseScore 4 was turned on

### ISSUE THREAD

**Issue by scilxurkel001** [musescore/MuseScore#16871]
### Issue type

Crash or freeze

### Bug description

This issue (or bug) may not be attention by some people because now CPUs have more than 4 cores (or threads), but I got this issue for CPUs less than 4 cores (or threads)
As the title suggests, when MuseScore 4 was turned on, one thread (or one core) of CPU seemed to stop working (the usage was less than 5%) no matter what operations or actions you did (for instance, open Microsoft Edge to search the web)

### Steps to reproduce

1. Open Task Manager, turn to "Performance" tab, Right-Click the CPU usage graphs and select "Logic processors"
2. Open MuseScore 4, and do any operations that uses CPU.
3. See the usage of CPU, and found one thread less than 5%.

### Screenshots/Screen recordings

Video is here:
https://user-images.githubusercontent.com/82962664/225812583-70c9d044-2b51-4797-a548-fa0a9edec492.mp4

### MuseScore Version

MuseScore 4 RC and later version

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

Windows 11 22H2 (22621.1413)

### Additional context

CPU: Intel (R) i5-4200M @2.50GHz (4 Cores)
You can find this issue in: 

- MuseScore 4.0.0 RC1
- MuseScore 4.0.0 Release
- MuseScore 4.0.1 Release
- MuseScore 4.0.2 Release

(Unsure for Nightly Version, because I didn't test for it)

Exceptions (In these versions of MuseScore, it's well):

- MuseScore 4.0.0 Beta
- MuseScore 4.0.0.223391656

**Comment by cbjeukendrup** [comment]
Closing because you opened a duplicate in #18636. Please never do that again!
