### ISSUE TITLE
'Loop Playback' Feature doesn't work correctly with repeats

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#16875]
### Issue type

General playback bug

### Bug description

The 'Loop Playback' option misinterprets repeats, and doesn't seem to take them into account when assigning playback points to loop to/from. Explained visually in a project file linked below.

### Steps to reproduce

1. Create a new Score
2. Add repeats of any kind (regular repeats, voltas, jumps)
3. Select a range to play looped during or after a repeat jump (a point after which the cursor has 'jumped' at least once)
4. Enable looped playback and play the range
5. The loop is offset by the amount of music repeated

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/116587995/225874638-9154590e-2d79-4403-bf04-ff1861beeac1.png)

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 10

### Additional context

[Loop Playback Bug Demonstration.zip](https://github.com/musescore/MuseScore/files/11000108/Loop.Playback.Bug.Demonstration.zip)

(this is actually a .mscz file that it wouldn't let me upload without renaming)

**Comment by BanjoJake** [comment]
Here's another example, I think, of the same bug.  Select All, Loop Playback, Jumps to start after first measure of B section
[MS4 Playback bug.zip](https://github.com/musescore/MuseScore/files/11106738/MS4.Playback.bug.zip)
Observed in MS 4.02 on Windows 11

**Comment by DmitryArefiev** [comment]
I can repro all cases. Thanks for logging!

**Comment by pcollinson** [comment]
Sadly, a fix for this hasn't made it into 4.2.0.

**Comment by Jojo-Schmitz** [comment]
there's no 4.2.0 yet

**Comment by pcollinson** [comment]
> there's no 4.2.0 yet

Yep sorry typo - I meant 4.0.2...

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d

I am getting exactly the same bug with this score. 
[loop_playback_issue.zip](https://github.com/musescore/MuseScore/files/11861282/loop_playback_issue.zip)
If you select a loop in the second system it plays back the corresponding measures in the first system instead. The problem disappears when you remove the repeat barline at the end of the first system.

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/de/node/359440

**Comment by vHeemstra** [comment]
I found similar behaviour in my score: after selecting a range, clicking "Loop Playback" and clicking Play, the playback starts X measures too early. Where X is the number of measures that are in repeating sections.

_**Extra info**_
If you unselect the "Play repeats" option from the playback options, playback starts at the right measure.

OS: Windows 10 Version 2009 or later
Arch.: x86_64
MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

**Comment by scorster** [comment]
I also encountered the issue today (as reported by [vHeemstra](https://github.com/vHeemstra)) in MS 4.2.1. As he mentioned, the workaround is turning off **Play Repeats** in the Toolbar settings (the gear icon.)

**Comment by BanjoJake** [comment]
Bug still present in MuseScore Studio 4.3

**Comment by MikeWilkey** [comment]
I just downloaded OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74
This is still an issue. Attempting to loop a score that contains repeats still causes weird jumps. There was a suggestion of setting the score to not play repeats but that defeats the purpose of using MuseScore as a practice partner to play along with since then it is just driving through first and second endings, which is not helpful. If more specific information is need or an example file, let me know.

**Comment by gabeluci** [comment]
@MikeWilkey They just fixed this a few days ago, but you won't see it till version 4.4

**Comment by MikeWilkey** [comment]
Aah…  Looking forward to the fix.

 

Michael T Wilkey

4770 Hilltop Dr.

DeForest, WI 53532

608-516-4556
