### ISSUE TITLE
Alignment of left-justified lyrics on whole notes different depending on stem direction

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#16878]
### Issue type

Engraving bug

### Bug description

When a lyric starts on a whole note and is left-justified on it (as it would be for a melisma), the alignment is different according to the stem direction of the chord. There should be no difference.

![image](https://user-images.githubusercontent.com/20604032/225908444-3ef3a090-6368-4a68-84ce-d392a797913b.png)
Here, the first note is upstemmed and the second note is downstemmed. (I made the lyrics much smaller than usual to make the difference more obvious.)

It looks like on the second note the lyric is aligned with the left of the bounding box of the notehead. This looks better than the first note to me; in any case, they should both be the same, as changing the stem direction of the note has no other graphical consequences in this case.

### MuseScore Version

OS: Artix Linux, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-230760632, revision: github-musescore-musescore-fdc7952

### Regression

No.

### Operating system

Linux, Windows 11

**Comment by MengLinMaker** [comment]
[@oktophonie](https://github.com/oktophonie), can't seem to reproduce the issue. Changing stem direction still looked like image 1:
![Slighly offset whole note lyric](https://github.com/musescore/MuseScore/assets/39476147/a91162c0-a3ae-412e-8d91-86fa9618e998)

Looks like the whole note is slightly wider than the half notes. Even the half notes are slightly offset:
![half note up lyric](https://github.com/musescore/MuseScore/assets/39476147/a1139fc8-1d01-40d7-bf41-582dd72882f0)
![half note down lyric](https://github.com/musescore/MuseScore/assets/39476147/7cc8bd72-d52b-4488-bb26-05642ada344f)

**So would the issue be: lyric left alignment is unaligned with the leftmost pixel of the note?**
![left alignment does not look left aligned](https://github.com/musescore/MuseScore/assets/39476147/2ea28442-d72e-42e5-9951-cf6fad17b947)

**Comment by MengLinMaker** [comment]
Could I tackle this issue?
I think I would need information on how to reproduce the problem.

**Comment by oktophonie** [comment]
It only occurs on unstemmed notes where the alignment of the lyric is set to 'Align left'.
Here you can see the difference as I flip the note repeatedly (by pressing X):

https://github.com/musescore/MuseScore/assets/20604032/fe236512-85c6-42c1-b0c1-194d271636d0

You're very welcome to try to find a solution!

**Comment by MengLinMaker** [comment]
@oktophonie Successfully reproduced.
I also reproduced this issue when the lyric is set to  'Align right'

https://github.com/musescore/MuseScore/assets/39476147/16a55395-9f30-4d01-bb8d-5d398634df06

**Comment by MengLinMaker** [comment]
@oktophonie Successfully reproduced your described issue.
I also reproduced this issue when the lyric is set to  'Align right'
https://github.com/musescore/MuseScore/assets/39476147/57c60d0f-a250-486c-8f6d-628d9606a488

**Comment by MengLinMaker** [comment]
Interestingly this change in placement is different for different Notehead types.
[Recording_12_05_2023_14_23_15.webm](https://github.com/musescore/MuseScore/assets/39476147/1b2f97aa-cdf2-4891-bb90-f71290f5faca)

**Comment by MengLinMaker** [comment]
@oktophonie It's not just the lyrics that show this behavior:
https://github.com/musescore/MuseScore/assets/39476147/66f387ed-1576-4f6e-8458-edce1db0b5d4

**Should the alignment of the other texts also remain the same?**
This issue applies to:
* Lyrics
* Sustain pedals
* Let ring
* Palm mute

**Comment by MengLinMaker** [comment]
Helpful information for locating files
* Lyric inspector qml: `src/inspector/view/qml/MuseScore/Inspector/text/TextInspectorView.qml`
*  Pedal inspector qml: `src/inspector/view/qml/MuseScore/Inspector/notation/lines/PedalSettings.qml`
**How does these UI relate to the code that changes the position information of Lyrics, Sustain pedal?**

**Comment by cbjeukendrup** [comment]
@MengLinMaker The UI files are not relevant for this issue, since it is purely an engraving issue and not an interaction issue. But for completeness, I will tell you how the Inspector works:
1. When the user changes something in the UI, the `value` property of the `PropertyItem` is changed in QML.
2. The `PropertyItem` emits the `propertyModified` signal.
3. This signal is handled by `AbstractInspectorModel`; see `AbstractInspectorModel::initPropertyItem` where it is connected.
4. The handler eventually calls `AbstractInspectorModel::setPropertyValue`, which communicates the change to the `engraving` module, where the actual engraving objects live.

But to find the cause of this issue, you'll need to look at the code where the layout is computed, which is in the files in the `src/engraving/layout` folder.

**Comment by MengLinMaker** [comment]
@cbjeukendrup Thank you, I've been trying to locate the relevant files.
I thought if I worked backwards from the UI I would be able to locate the relevant files.

**Comment by MengLinMaker** [comment]
So I have identified how to remove the alignment flipping issue:
[Recording_15_05_2023_17_12_03.webm](https://github.com/musescore/MuseScore/assets/39476147/60cbb8ac-77e7-4039-b925-9dd2b12aff87)

Reference file location: `src/engraving/layout/lyricslayout.cpp`

There is a minor issue where the offset alignment is the same for all noteheads. I believe adjustments for different noteheads should be made.

**Comment by MengLinMaker** [comment]
The problem appears to be related to the way the position of the `ChordRest` moves.
