### ISSUE TITLE
Crash setting properties for multiple elements at once

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#16887]
### Issue type

Crash or freeze

### Bug description

If you select multiple lyrics in a score and then adjust their vertical offset via the Properties panel, MuseScore on Linux will crash (not on Windows).

### Steps to reproduce

1. Add notes C D E F to a score
2. Add lyrics to these notes
3. Right-click one lyric, Select / Similar
4. Use the Appearance section of the Properties panel to increase the offset to 5

Result: crash.  Might happen immediately while increasing the offset, might happen when you click back in the score.  Might not happen until you perform another operation (including undo).  But for me at least, the crash is guaranteed.

It's not just lyrics, and not just offset.  Almost any change to any setting in the Properties panel will potentially result in a crash upon clicking back in the score (either immediately, or on the next action), if multiple elements were selected.  At least, I've been able to reproduce this for rests and for notes as well as lyrics and other text; for font size as well as offset on text, for measure width with notes selected, etc.

### Screenshots/Screen recordings

![offset-crash](https://user-images.githubusercontent.com/1799936/226061271-b38ebbe1-4615-48f2-851a-cadde727eb25.gif)

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Debian 11

### Additional context

Similar story on 4.0.1, so at least not a *recent* regression.

Reproducible on both of my Linux machines, but not on Windows.

No useful info printed to console.  Full crash log attached.

[crash-log.zip](https://github.com/musescore/MuseScore/files/11006739/crash-log.zip)

**Comment by MarcSabatella** [comment]
This is still an issue on master for me, completely reproducible.  Not just lyrics, also Roman numeral analysis.  And not just offset - also changing size.  Select a group of lyrics or RNA elements, click the spin box for size, hit up or down arrow a couple of times, then click somewhere else in the score - crashes for me.

**Comment by mike-spa** [comment]
I've tried on my Linux machine, current master, both with and without address sanitizer: can't reproduce the crash. I do exactly the same steps as you did and all works fine, so I'm not sure what's going on

**Comment by MarcSabatella** [comment]
Bummer.  I'll see if I can figure anything else out.

**Comment by MarcSabatella** [comment]
This seems to be the exact same crash as https://github.com/musescore/MuseScore/issues/16437.  At least, it happens in the same place.

**Comment by mike-spa** [comment]
Can you please let me know if you can reproduce the issue in 4.1 beta? If not, I think it should be closed.

**Comment by MarcSabatella** [comment]
Yes, it is still reproducible in the latest builds, as is #16437 .  As per the comment in https://github.com/musescore/MuseScore/issues/16437#issuecomment-1537544661, the cause is clear: an error in the accessibility code, with the exact lines and the actual problem identified.  So in principle, one can fix this even without being able to reproduce it, by fixing the bad pointer reference that is shown in the snippet there.

Since the error occurs within the accessibility code, I can imagine it might occur depending on whether your system has accessibility features enabled.  As I mentioned earlier, I'm not actively running the screen reader when the crash occurs, but if we're running the accessibility code any time the OS reports accessibility features are active, that could explain why it doesn't crash for everyone - only the people who have enabled accessibility features, perhaps.  On some systems that might be enabled by default but maybe not on yours? Try actually running a screen reader (Narrator is built-in on Windows, VoiceOver on macOS, and Orca is either built-in or installable on Linux).

So far the other crash has been reported quite a few times on the forums and on social media by quite a few users, some on Windows, some on Linux.  At least one of those users is blind and using a screen reader.

**Comment by mike-spa** [comment]
> So in principle, one can fix this even without being able to reproduce it, by fixing the bad pointer reference that is shown in the snippet there.

No, one can't, because [this](https://github.com/musescore/MuseScore/issues/16437#issuecomment-1537544661) misses the fact that, just a few lines before using `m_itemForRestoreFocus`, that pointer is set `= item`, which is the input argument of the method, which means that the bad pointer can originate at literally _any_ point above that call, so it's not obvious at all.

**Comment by MarcSabatella** [comment]
Description updated - not just lyrics, and not just offset.  It's really almost any setting made in the Properties panel, if multiple elements are selected (that seems to be an important aspect of the trigger).

I'm following up in #16437 since that's where the analysis of the issue started, but it is apparently the same bug.

**Comment by Eism** [comment]
@MarcSabatella 
#18227 fixes this issue?

**Comment by MarcSabatella** [comment]
@Eism Yes, it does - at least the current approach I'm using of unsettling m_itemForRestoreFocus in unreg().  I've updated the description to add that info.

**Comment by DmitryArefiev** [comment]
Fixed in #18227
