### ISSUE TITLE
Selective delete of list of recent files

### ISSUE THREAD

**Issue by mdeluca70** [musescore/MuseScore#16884]
### Your idea

The Scores section of the Home tab (which opens by default when MS4 is started) shows a "**New & recent**" section that provides a button to start a new score, or to select a score that was recently open in the program.  This list is also available from the main menu under **File --> Open Recent**.  When selecting Open Recent, the bottom of the menu provides an option to "**Clear recent files**".

In addition to clearing all files, it would help to be able to trim the Recent Files list by clearing individual files one at a time.  From a UI perspective, this could be done by adding a right-click menu option on the Scores section of the Home tab.

### Problem to be solved

This would allow this list to be purged of files that only needed to be opened one time, retaining projects that are on-going.

**Comment by cbjeukendrup** [comment]
This is a duplicate of #11235, which is already being worked on. Thanks for the suggestion anyway!

**Comment by mdeluca70** [comment]
Got it - thanks!
