### ISSUE TITLE
Musescore 4 causing bsod

### ISSUE THREAD

**Issue by Gerrard114** [musescore/MuseScore#16899]
### Issue type

Crash or freeze

### Bug description

I was composing a piece for piano (quite large actually, ~220 measures long). It used to work well without any problems, but now it's freezing my whole pc and causes bsod. My system is i5 4690k with 8gb (used to be 16gb) ram and 120gb ssd+1tb hdd.

### Steps to reproduce

Not sure how it happens, i was just composing then it bsod

### MuseScore Version

4

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment]
Did this happen just once, or is it reproducible by following certain steps? And does it still happen in the nightly builds of MuseScore 4.1? https://musescore.org/en/nightly-builds

**Comment by zacjansheski** [comment]
Closing, no response
