### ISSUE TITLE
MS Basic Instruments can not be selected for playback

### ISSUE THREAD

**Issue by Lenbus** [musescore/MuseScore#16892]
### Issue type

UI bug

### Bug description

In MS4 you can choose the distinct playback instrument from the MuseSounds library, but not from the MS Basic (missing dropdown). 

That way, you are tied to the instrument selected for the staff, which ist not always the preferred choice. In MS3 you could exchange the playback instrument utilizing the Sound Dropdown within the mixer panel.

E.g. for learning tracks for my choir, it would be a lot more feasible to quickly select an instrument with slightly more attack, without having to copy the entirety of notes to a new staff.

### Steps to reproduce

see screenshots attached

### Screenshots/Screen recordings

In MS4 you can freely choose Instruments from MuseSounds, but not for MS Basic.
![grafik](https://user-images.githubusercontent.com/12497326/226067033-5503202c-966c-48d3-a0bb-32cc7beab61a.png)

In MS3 this was possible by that (very cluttered and not well sorted dropdown menu, but at least there was that option)
![grafik](https://user-images.githubusercontent.com/12497326/226067119-b07f644d-b9f4-48b1-aded-f207be7717ff.png)

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
This is a known limitation indeed, already marked as a high priority to address for 4.1.

Meanwhle, though, there are workarounds.  Simplest is just to choose the Muse Sounds piano instead if that's the sound you want - you're not limited to MS Basic.  Or use a VST instrument.  Or, you can have separate soundfont files for the sounds you want.  See for instance this collection I created, which takes the default soundfont and splits it up into individual files so you can select between them as before - see https://community.masteringmusescore.com/c/resources/ms-basic-individual-sounds

**Comment by Lenbus** [comment]
Thanks a lot for the explanation intermediate workaround. Good to now that this is been worked on. 👍 
Hopefully you will find a less cluttered way than that huge dropbown that can not be filtered.

**Comment by cbjeukendrup** [comment]
"Duplicate" of #17233
