### ISSUE TITLE
Crashes before file open

### ISSUE THREAD

**Issue by jrceloni** [musescore/MuseScore#16898]
### Issue type

Crash or freeze

### Bug description

1:  Open MuseScore 4.0.2 for Windows or Linux, open certain files (2 attached); MuseScore closes before displaying file.
OR
2:  In Windows 10 or 11, go to file explorer and double-click certain file (2 attached); MuseScore closes before displaying file.

I also tried unzipping one of the .mscz files, extracting the .mscx file, and trying to load it both the above ways.  MuseScore closed before showing it too.

I tried to upload the files as .mscz but got "We don't support that file type", so I'm renaming them to just .zip and uploading them that way.  Please rename them to .mscz then try yourself.  Thank you.

[MassOfAscentKB.zip](https://github.com/musescore/MuseScore/files/11007085/MassOfAscentKB.zip)

[MassOfAscentLS.zip](https://github.com/musescore/MuseScore/files/11007086/MassOfAscentLS.zip)

### Steps to reproduce

1:  Open MuseScore 4.0.2 for Windows or Linux, open certain files (2 attached); MuseScore closes before displaying file.
OR
2:  In Windows 10 or 11, go to file explorer and double-click certain file (2 attached); MuseScore closes before displaying file.

I also tried unzipping one of the .mscz files, extracting the .mscx file, and trying to load it both the above ways.  MuseScore closed before showing it too.

I tried to upload the files as .mscz but got "We don't support that file type", so I'm renaming them to just .zip and uploading them that way.  Please rename them to .mscz then try yourself.  Thank you.
[MassOfAscentKB.zip](https://github.com/musescore/MuseScore/files/11007085/MassOfAscentKB.zip)
mscz then try yourself.  Thank you.
[MassOfAscentLS.zip](https://github.com/musescore/MuseScore/files/11007086/MassOfAscentLS.zip)

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11 Pro, Windows 10 Pro, Linux on Acer Chromebook

### Additional context

Tried on 3 PCs (2 Lenovo ThinkPad T15s 1 Win11Pro x64 1 Win10Pro x64, 1 generic desktop Win10Pro), and one Chromebook with Linux development environment.  PCs have 32, 16, and 8 GB RAM and 512GB SSD, 512 GB SSD, 256GB SSD+750GB HD.  Before I loaded files into v4, they worked fine in 3.6.4, but now v3 recognizes them as later and won't open them.  On 4.0.2, there's no message before the close.  Let me know if you want more info or want me to try something else.  Thank you.

**Comment by Jojo-Schmitz** [comment]
Stems from https://musescore.org/en/node/338227

**Comment by cbjeukendrup** [comment]
This turns out to be another case of https://github.com/musescore/MuseScore/issues/16442, which already has a pending fix. So I'll close this as a duplicate. Thanks for reporting!
