### ISSUE TITLE
Make Mixer Snap To Bottom Panel Area

### ISSUE THREAD

**Issue by Lenbus** [musescore/MuseScore#16895]
### Your idea

In MS3 the Mixer can only be snapped to side panels, even though the mixer rack is supposed to have a wide and not a high aspect ratio. 

Please fix that.

### Problem to be solved

Make Mixer Panel snap to bottom in MS3

### Prior art

Make it snap like so (in MS4 that works like a charme):
![grafik](https://user-images.githubusercontent.com/12497326/226070644-5aedc66d-d1da-46b0-b3a7-26b1cb0539c6.png)

### Additional context

This is a feature request for MS3!

**Comment by cbjeukendrup** [comment]
MS3 won't receive any updates anymore, at least no official ones. So I'll have to close this. Thanks for your input anyway!
