### ISSUE TITLE
Copy-paste of notes cause playing of them without sound

### ISSUE THREAD

**Issue by espi66** [musescore/MuseScore#16912]
### Issue type

Muse Sounds bug

### Bug description

When I copy-paste a verse with several instruments, the pasted version loses many if not all the instrument voices.
All you can see is the pasted notes but with no sound when they are played. This is something close to a show stopper!

This bug wasn't in 4.0.1, but in 4.0.2 (even in the nightly build) it is there are reproducible very easily.

Workaround to this is copy (ctrl-x) the beats that don't make a sound and paste it back (ctrl-v) to where they already were. This helps but does not stop from the bug happening all over again. Even with the same notes.

You have done a great job with musescore! However this error made me want to downgrade back to 4.0.1, but that isn't easily available anymore. Please flag this one urgent.

### Steps to reproduce

1. Create music
2. Copy it to another bar
3. Play it
=> some of the notes are silent when playing them

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

Windows 10

### Additional context

This bug can be reproduced any time 
It can be found also in the latest nightly build, so I guess it hasn't been found or fixed yet.

**Comment by MarcSabatella** [comment]
I’m not able to reproduce any problem with copy/paste.  In order for someone to be able to investigate, please attach your score (zip it so GitHub will take it) and give more precise steps - which notes specifically you are copying and where you are pasting them.

**Comment by espi66** [comment]
It may not be the copy paste case after all.
I found it while simpy editing notes in one bar, and the next bar played
without sound.
So I can't provide exact steps for you, I'm afraid.

**Comment by MarcSabatella** [comment]
At the very least, we'd need you to attach the score.  Certainly the vast majority of scores play just fine, and copy/paste and editing also work just fine.  If you are encountering a special case where something goes wrong in some particular score, we'd need your help in reproducing this issue.

In the future, when encountering problems, it's best to ask for help first on the official Support forum on musescore.org, and only open issues here on GitHub when something is confirmed to be an actual bug with precise steps that others can use reproduce the problem.

**Comment by fenugrec** [comment]
Having the same problem. Happens often but hard to reproduce; re-opening the file usually helps so there's something non-deterministic going on. I tried duplicating my usual patterns - copy+pasting, moving notes up/down octaves, keyboard entry, mouse drag...

**Comment by espi66** [comment]
Glad to hear it!

**Comment by zacjansheski** [comment]
Closing this as stale/not reproducible.  If the issue continues in the latest version feel free to open a new report, thank you!
