### ISSUE TITLE
Arpeggio using Muse Sounds affects next chord (if it has the same notes)

### ISSUE THREAD

**Issue by xman2156** [musescore/MuseScore#16917]
(Edited by @DmitryArefiev )

### Issue type

Muse Sounds bug

### Bug description

When putting an arpeggio on a chord, it plays it on the chord it's attached to and the next chord if it has the same notes

### Steps to reproduce

1. Place multiple similar chords (or contain several identical notes)
3. Place arpeggio to the first chord
4. Play

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/7201d42a-0754-4992-b419-270ecfac897e

### MuseScore Version

4.0.2-230651553

### Operating system

Windows 11

### Additional context

Similar issue with the same notes in the next chord with MS Basic #11936

**Comment by XiaoMigros** [comment]
I don't think this counts as a regression, MU3 doesn't have MuseSounds after all..

**Comment by xman2156** [comment]
I didn’t mean to mark it and it wouldn’t let me change it.

**Comment by DmitryArefiev** [comment]
@xman2156 Thanks for logging! I've added a little bit additional info to the description

**Comment by DmitryArefiev** [comment]
Fixed in #20243
