### ISSUE TITLE
Load thumbnails and metadata of recent scores asynchronously and only when necessary

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#16918]
Launching MuseScore, opening a score, and saving a score are very slow. And that's not because the operation itself is slow; it is because MuseScore has to reload the metadata and thumbnail (from your hard disk, or network drive, [or your non-responding OneDrive](https://github.com/musescore/MuseScore/issues/13161)) for every score in the "recent scores" list (which may contain an [infinite number of entries](https://github.com/musescore/MuseScore/issues/13799)), every single time when a score is added, moved or removed from the list. Even worse: it does this on the main thread, freezing the whole app for many seconds (in my case even 20 secs).

So I propose a few changes that will make a big difference:
- load the data in a background thread, so that the UI can move on. When the thumbnail for a score is not yet loaded but the home page is already displayed, just display a loading indicator in the spot of that thumbnail (or something else, or nothing).
- only load thumbnails for scores where needed. For example, the list may be very long, but until the user scrolls down, only the topmost few scores are visible, so we don't need to load a thumbnail yet for the others.
- don't reload _all_ thumbnails just when a score gets added/moved/removed, but cache them. (However, need to make sure that we do reload them when a score has been modified, otherwise an outdated thumbnail is displayed.)

**Comment by DmitryArefiev** [comment]
Implemented in #17573
