### ISSUE TITLE
Invisible lines of text lines are not clickable

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#16922]
### Issue type

Other type of issue

### Steps to reproduce

1. Input a textline (e.g. cresc.)
2. Go to the Properties panel
3. Uncheck the Show lines checkbox
4. Click on the line
5. Nothing selected

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/102702868/226159395-b84c43c7-4449-4640-8a05-f662a3950f2e.mp4

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

No.

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
An interesting note for this one.  If you de-select "show line" while the score properties are set to not show invisible elements.  The line will not appear when the score is set to "show invisible elements"

https://github.com/musescore/MuseScore/assets/69917893/e22877aa-74cb-4437-976b-9d6b5a0467ac

**Comment by bakajikara** [comment]
Seems to be fixed in #20930
