### ISSUE TITLE
Page Background Wallpaper is reset when restarting the program

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#16930]
### Issue type

Other type of issue

### Steps to reproduce

1. Go to Edit/Preferences/Appearance
2. Scroll down and select 'Wallpaper' under the 'Paper' section.
3. Choose any image file (MuseScore's preinstalled ones or your own)
4. Make note of the new page background
5. Close and reopen MuseScore
6. The background is no longer present

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/116587995/226267940-b8bad8e1-5041-4585-8359-075ee3e975e9.png)

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 10

**Comment by worldwideweary** [comment]
Came across this a moment ago while retesting MS4 to see if the slow palette search was fixed... will see if I can fix this since it shouldn't be difficult. Operative word *shouldn't* :)

**Comment by worldwideweary** [comment]
@XiaoMigros please test if you find some time. Should be okay, but who knows these days...

**Comment by XiaoMigros** [comment]
Works perfectly! Thanks so much
