### ISSUE TITLE
Gradual tempo change line cannot be extended to the end of the score

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#16944]
### Issue type

Other type of issue

### Steps to reproduce

1. Create a new score
2. Add a gradual tempo change line to the second last measure
3. Click on the line
4. Press Shift+→.
5. The line does not extend.

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
For reference/visablity
- Selecting last two bars and adding gradual tempo change line does not work as expected.
- Shift + Right arrow does not extend
- You can click and drag to extend, but the anchor will not attach to last bar


https://github.com/musescore/MuseScore/assets/69917893/5ef1c201-3801-494c-9fc2-2e17ea17f86d

**Comment by bakajikara** [comment]
This bug no longer exists in MuseScore 4.2. (Probably fixed in #18904).
