### ISSUE TITLE
Remove Shift+Ctrl duplication of lines (not needed as MS4 now supports copy and paste)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#16952]
### Your idea

Up to MS3, it was only possible to copy lines using Shift+Ctrl and then dragging the line into its new position. However this method is, IMV, surplus to requirements, as MS4 allows straightforward copy and paste to be applied instead – which is much better.

AFAICS, the old Shift+ Ctrl + drag method could be removed with no loss of utility.

**Comment by cbjeukendrup** [comment]
I believe that Shift+Ctrl+Drag is still the only way to add a custom item from the score to the palettes for re-use.

**Comment by rgreen5** [comment]
> I believe that Shift+Ctrl+Drag is still the only way to add a custom item from the score to the palettes for re-use.

Ah, I was forgetting that. If it's not feasible please feel free to close.
