### ISSUE TITLE
[MU4 Issue] "Update existing score" option missing from "Publish to musescore.com"

### ISSUE THREAD

**Issue by murimk** [musescore/MuseScore#16957]
### Issue type

Cloud saving/loading issue

### Bug description

In M3, when uploading to musescore.com, you have the option of selecting whether to update existing score or not. Often I choose not to, as I work from one document to make many different files. This is very useful for my purposes, making lots of one or two bar snippets (examples) that I later embed on a website. There is no need to keep files like these around, so I save them to the cloud directly. There's also custom page settings for different files, so setting up new files or making templates is not a good workaround.

In M4, there's no such option, and any file generated from the same "mother" file is automatically updated when uploaded. This completely break my workflow, and I'd love to see the option of updating existing score to be reintroduced.

### Steps to reproduce

1. ;Make a short score
2. Upload to musescore.com
3. Make change to score
4. Upload to musescore.com
5. See that there's no option to select whether you want to update your file or not
6. See on musescore.com that your file has been updated, and possibly renamed (if you chose to), but in any case your original file is gone.

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

OS: Windows 10 Version 2009, Arch.: x86_64,

**Comment by XiaoMigros** [comment]
Additionally, when updating an existing score, the title to be uploaded is always sourced from the file name rather than the title under which the score is already published.

**Comment by shoogle** [comment]
Here's an updated design for the _Publish to MuseScore.com_ dialog:

![image](https://user-images.githubusercontent.com/11011881/235878650-8cefd2e2-5977-4417-9b10-587eedec3b69.png)

This adds radios buttons with options to:

- Replace the existing [online score](https://musescore.com/user/37221589/scores/8455808)
- Publish as new online score

In the "replace" option, the words "online score" will be a link that points to the score page on MuseScore.com.

The options will only displayed when there is an existing score that could be replaced. If there is no online score, or it is on a different user's account, then the radio buttons are not displayed and the default action is to publish as a new online score. This keeps the dialog simple for first time users.

When there is an existing online score that could be replaced, the title and visibility displayed in this dialog will be taken from the online score. MuseScore must query the website to get the latest title and visibility every time the dialog is displayed.

**Comment by XiaoMigros** [comment]
After using the 'Publish' feature some more I've encountered another issue:

- When updating an existing score, the categories 'Disable Score Download' and 'Genre' don't save their settings from when the score was originally published. I assume this is an issue with the website itself, rather than the program?
