### ISSUE TITLE
Custom font size of dynamics-symbols of MU3-files are being ignored on import into MU4 

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#16969]
### Issue type

Engraving bug

### Bug description

See title.

MU3:

![image](https://user-images.githubusercontent.com/78870770/226923882-a72992b3-c810-4002-b5ee-73a8c82e573a.png)

after import in MU4:
![image](https://user-images.githubusercontent.com/78870770/226924096-6107a58d-a1ba-4e0a-8481-1cddcef551db.png)

### Steps to reproduce

1. Reduce the font size of a dynamics symbol in MU3 and save the style.
2. Open the file in MU4

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-230811026, revision: github-musescore-musescore-5f3913c

### Regression

I don't know

### Operating system

Windows 10

**Comment by oktophonie** [comment]
Pretty much by design, as the way dynamics are handled in 4.0 is rather different than in 3.6.

**Comment by oMrSmith** [comment]
I understand, I think it would be helpful though if the font size of dynamic symbols would correspond 
if you load a MU3 file into MU4. Then it would be more likely that the number of pages stays the same...
