### ISSUE TITLE
Impossible here to complete the upload with MS4.0.1

### ISSUE THREAD

**Issue by PRS1325** [musescore/MuseScore#16987]
### Issue type

Cloud saving/loading issue

### Bug description

Hi,

Since a few days, it is impossible for me to upload partitions created with MuseScore 4.0.2

I get the window where I fill in the different elements but when I validate it, I get the waiting message... and the wheel doesn't stop turning.

Impossible here to complete the upload.

The problem is solved with MuseScore 3.2.

### Steps to reproduce

1 - Publish > Publish on MuseScore.com

2 - Window > Public > "Publish" validation

3 - Export audio > ok

4 - Record online > ok

5 - "Score is being processed... " does not finalise... Oops message after very long minutes

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

MacOS Ventura 13.2.1

**Comment by shoogle** [comment]
Which sound technology are you using in the Mixer? (E.g. MS Basic, Muse Sounds, VST, other SoundFont?)

Does it work for you if you create a really simple score with just a piano instrument and use MS Basic for sound?

**Comment by cbjeukendrup** [comment]
@PRS1325 Kind reminder on the questions above. And does this issue still occur? Even when you upload scores using the latest nightly build of MuseScore 4.1? https://musescore.org/en/nightly-builds

**Comment by zacjansheski** [comment]
Closing, no response / stale
