### ISSUE TITLE
Musescore crashes when changing key signature of selected bars of a transposing instrument

### ISSUE THREAD

**Issue by IceOfPhoenix88** [musescore/MuseScore#16983]
### Issue type

Crash or freeze

### Bug description

When changing the key signature of a selected bar/bars of a transposing instrument, the programme crashes. Bug confirmed by other users.

### Steps to reproduce

1. Create score with clarinet part and piano part
2. Select a few bars in the middle of the clarinet part
3. Attempt to change key signature by using the palette
4. MuseScore 4 crashes

### MuseScore Version

MuseScore 4.0.2

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
I can confirm the crash - it doesn't seem to depend on the score.  But for the record, I created mine by selecting clarinet & piano, using default key signature etc (skipping the last screen of the wizard), entering no notes into the score, then selecting bars 2-3 of the clarinet staff and clicking the G major key signature on the palette.

Also reproduced in a recent build from master, and also in 4.0.1 and 4.0.0 - so, not actually a regression from previous 4.x versions.  But it did work in MU3.

It only crashes if the instrument is selected bars are on a transposing staff, and only if multiple bars are selected.  So presumably, it relates to the code that tries to reestablish the original key signature at the end of the selection in that case.

**Comment by IceOfPhoenix88** [comment]
Thanks Marc for the valuable info :)

**Comment by SteveBlower** [comment]
Another report on .org https://musescore.org/en/node/347090

**Comment by sammik** [comment]
My local build fix for #14274 seems to fix also this one.
(PR is not public yet, as it became bit more complex, than I thought at first sight)
