### ISSUE TITLE
Crash on opening this 4.0.2 score on 4.1.0 

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#16994]
### Issue type

Crash or freeze

### Bug description

Open this score created in MuseScore 4.0.2 cause crash in 4.1.0
Removing 2nd voice fix the crash, re-enter manually second voice cause crash too

[test.zip](https://github.com/musescore/MuseScore/files/11054865/test.zip)

### Steps to reproduce

1 - Open score

### MuseScore Version

MuseScore version (64-bit): 4.1.0-230820305, revision: github-musescore-musescore-a66ac8d

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

OS: Windows 10 Version 2009, Arch.: x86_64,

**Comment by cbjeukendrup** [comment]
@Gai-Luron Thanks very much for testing the nightly builds already! That's very useful!
