### ISSUE TITLE
MU4 won't open, crash on splashscreen (4.1.0)

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#17005]
### Issue type

Crash or freeze

### Bug description

Crash on Splashscreen

### Steps to reproduce

Open exe

### MuseScore Version

MuseScoreNightly-230830304-master-0a65ab2-x86_64.7z	

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

Windows 10

**Comment by Gai-Luron** [comment]
I had to delete the "MuseScore 4 Development" folder in C:\Users\User\AppData\Local\MuseScore
This folder work with version 4.1.0 master until March 15th (my last dev version).

There seems to be an incompatibility with the latest Master 4.1.0

Exception raised with old  "MuseScore 4 Development" folder
![image](https://user-images.githubusercontent.com/1835871/228381773-064719f5-3c42-46ac-9632-58b9289ac6d7.png)


If it can help anyone.

**Comment by cbjeukendrup** [comment]
@Gai-Luron Is this still actual in the latest nightly builds? https://musescore.org/en/nightly-builds

**Comment by zacjansheski** [comment]
Closing, no response
