### ISSUE TITLE
Instrument Field is the same as Part Full Name

### ISSUE THREAD

**Issue by smorell-1** [musescore/MuseScore#17004]
### Issue type

Other type of issue

### Bug description

Currently the Instrument Field simply displays the Full Name on the part.  This can be confusing and also represents a regression from behavior in MuseScore 3. Instead, "Instrument" should be fixed to what the instrument you have selected from the menu.

### Steps to reproduce

1.  In the Staff/Part Properties, change the part full name.
2. Save.  
3. Reopen the same Staff/Part Properties. The instrument name will now be the part full name.

### MuseScore Version

OS: macOS 12.4, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651546, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

MacOS 12.4

### Additional context

As a MuseScore user, I expect that what I select from this menu on a score:

<img width="919" alt="Screen Shot 2023-03-24 at 11 29 00 AM" src="https://user-images.githubusercontent.com/128835319/227610051-f09ce38f-bc02-4a0e-a7af-bf20efd67b1d.png">

Would match the Instrument field shown here:

<img width="746" alt="Screen Shot 2023-03-24 at 11 31 35 AM" src="https://user-images.githubusercontent.com/128835319/227610697-5e2dbda2-ff43-4964-8b6c-316e68212244.png">

Currently the Instrument Field simply displays the Full Name on the part.  This can be confusing and also represents a regression from behavior in MuseScore 3.  Instead, "Instrument" should be fixed to what the instrument you have selected from the menu.

Previously in MuseScore 3, if you added a Violin to a Score and then changed its Full Name to "Bassoon", the Instrument would still show as "Violin" as you have not changed instruments, only what the part name is (as seen here).  Once the Instrument field was set, the only way to change it for the staff was to select the "Change instrument" button.

<img width="754" alt="Screen Shot 2023-03-24 at 11 51 28 AM" src="https://user-images.githubusercontent.com/128835319/227614474-564d24b1-5c8e-454d-9f63-8e8782a74ede.png">

In MuseScore 4, you can now give the appearance of replacing the instrument by changing the part name text.

<img width="749" alt="Screen Shot 2023-03-24 at 11 54 20 AM" src="https://user-images.githubusercontent.com/128835319/227615022-1522e74c-1c70-40a8-9e5d-d79b2e30db11.png">

Changing any variation of the part name, track name or even playback sound should not effect the Instrument Field.

To be clear, also I would also remove any ability for a number to show up in the Staff/Part Properties next to instrument as part of this update.  While a part name might be Violin 1, the Instrument selected was either Violin or Violins (section) as those are the two options when adding instruments, so one of those two is what should be shown here.  The defaults for _**part**_ naming are great, and I hope it is not misconstrued I'm suggesting otherwise

Any MusicXML import should also follow the same principles when it comes to populating the Instrument field.

**Comment by shoogle** [comment]
**Summary:** The highlighted field should say "Violin" instead of "Violin 1". It should always show the default name of the instrument as it appeared in the New Score Wizard before it was added to the score.

![image](https://user-images.githubusercontent.com/128835319/227610697-5e2dbda2-ff43-4964-8b6c-316e68212244.png)
