### ISSUE TITLE
Adjusting measure width with } shortcut creates many extra zeroes in "Measure width" property

### ISSUE THREAD

**Issue by icactus** [musescore/MuseScore#17013]
### Issue type

UI bug

### Bug description

Adjusting measure width with } shortcut creates many extra zeroes in "Measure width" property. If you continue to increase the width, it will continue the pattern of displaying 1.2000000000000002, 1.30000000000003, ... 1.15000000000000015, etc. Initally decreasing the measure width with does not cause the same issue.

### Steps to reproduce

Create a new blank score
Select any measure, and increase the measure width a few times using } ( Shift + ] ). It's also noted as "Increase layout stretch" under Format > Stretch.
In the Properties panel, under Appearance, the measure width will read as something like "1.2000000000000002" instead of "1.2".
The workaround is to just manually type 1.2 into the "Measure width" box to fix the issue.

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 10 and 11

**Comment by jonmagicllama** [comment]
Heyo! wanted to get my hands dirty and try contributing to open source for the first time, probably take a look at this relatively soon if y'all don't mind.

**Comment by oktophonie** [comment]
https://github.com/musescore/MuseScore/pull/16386 might give you some pointers :)

**Comment by jonmagicllama** [comment]
Wow, most the of trouble was finding time between school and actually getting the project to compile, thanks for leaving such a simple issue up for me though! I'll try to get the pull rq up sometime today after running through the checklist. Seems like itll be hard to make unit tests for this though since its a runtime thing, either way, appreciate the patience :^)

**Comment by cbjeukendrup** [comment]
Don't worry about creating a unit test for this; for this issue specifically, it would be difficult anyway to come up with a kind of test that makes sense, and we don't really have any unit tests for the Inspector module at all, since it is so much a UI thing.
