### ISSUE TITLE
New Jazz Big Band scores drums instrument sounds seem to be mapped wrong.

### ISSUE THREAD

**Issue by rithvik-doshi** [musescore/MuseScore#17039]
### Issue type

Muse Sounds bug

### Bug description

In a new jazz big band score, the Drumset part sounds seem to be mapped wrong. For example, the Bass Drum 1 sound sounds like the clap instead, while Pedal Hi-Hat sounds like the Bass Drum. This has persisted even though I've updated my version from 4.0.0 -> 4.0.2. I'm using the MS Basic soundfont.

### Steps to reproduce

1. Create a new Jazz Big Band Score

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/81876806/228117392-ef9909c9-735d-44c0-86d9-d9cc25739f4b.MOV

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Ventura 13.1

**Comment by MarcSabatella** [comment]
I think what you’re seeing is just about the sound while clicking in the palette, but it will work correctly when you actually add to your score.  The glitch only occurs if concert pitch is turned off.  See https://github.com/musescore/MuseScore/issues/15866

If it seems like that’s not actually it, please attach your score and give precise steps to reproduce the problem.

**Comment by zacjansheski** [comment]
Fixed with https://github.com/musescore/MuseScore/pull/17674
