### ISSUE TITLE
Still problems with setting the figured bass durations

### ISSUE THREAD

**Issue by Kortaffelbreu** [musescore/MuseScore#17030]
Bug:  Same as in  #14916, #15081; 3 months ago closed because it seemed to be fixed. Is it really fixed?

Setting the duration of figured bass still doesn´t work. Pressing "Ctrl+[Number]" is not recognised at all and therefore the figured bass duration is always the attached note length and cannot be changed.

What happens:
Half note selected-->Ctrl+G-->"5"--> Ctrl + 5 --> "4": Half note with a figured bass "54" and half note duration. The Ctrl+[Num] command is not recognised. I tried different Ctrl keys, NumPad as well as usual digits. Still doesn´t work.

Example how it should work (according to manual):
Half note selected--> Ctrl+G --> "5" --> Ctrl + 5 --> "4": Half note with two quarter-note spaced figured bass attached to it (and equally spaced grey duration lines above). 

System information:
OS: Windows 11, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

**Comment by MarcSabatella** [comment]
The fix is in *master* builds, but unfortunately, it breaks some other functionality, so the fix isn't ready to be included in a release yet.

**Comment by trirpi** [comment]
When will this be expected and is there a way to access the build with this fix included even though it breaks other features?

**Comment by MarcSabatella** [comment]
And the issue with Ctrl+Left/Right has a pending fix that has been reviewed and should hopefully be merged soon - see https://github.com/musescore/MuseScore/pull/17434

**Comment by oktophonie** [comment]
(Fixed in 4.1)
