### ISSUE TITLE
Flats and Text Fonts in MusicXML Import

### ISSUE THREAD

**Issue by smorell-1** [musescore/MuseScore#17037]
### Your idea

When it comes to importing MusicXML, our goal is to make seamless transitions into MuseScore.  MuseScore 4 does not do very well capturing the finer points of how instrument names are presented when it comes to flat symbols, and should use Edwin more often to make for better looking imports when MusicXML files are encoded to use certain default text styles.

### Problem to be solved

When exporting from other notation software, it is common for parts like a B-Flat Clarinet to presented like this in the part names:

B♭ Clarinet
B♭ Clarinet 1
Clarinet in B♭ 1

This formatting is generally ignored in MusicXML exports and it commonly converted to "Bb".

Finale, employs a method to try to tell other notation products that may be importing it to use the flat symbol by including a _display_ element also as seen here:

<score-part id="P6">
      <part-name>Eb Clarinet</part-name>
      <part-name-display>
        <display-text>E</display-text>
        <accidental-text>flat</accidental-text>
        <display-text> Clarinet</display-text>
      </part-name-display>
      <part-abbreviation>Eb Cl.</part-abbreviation>
      <part-abbreviation-display>
        <display-text>E</display-text>
        <accidental-text>flat</accidental-text>
        <display-text> Cl.</display-text>
      </part-abbreviation-display>

This approach tries to incorporate a key element (the flat sign) that reflects the very different approach than MuseScore for how to present a flat sign in an instrument name.  For MuseScore's purposes, it makes sense to continue simply using the part name as the main driver, but to present certain text more elegantly for the two most common flats used in Instrument Names, B♭ and E♭.

"Bb" when separated by space should be imported as "B♭"
"Eb" when separated by space should be imported as "E♭"

This approach is used when adding new parts in MuseScore so keeps a consistent approach.

In a very related topic, MuseScore sets certain default fonts based on the element <word-font>.   While this is a good approach when a user goes out of their way in other software to change these defaults, the user more commonly does not set anything on purpose or changes the font with a more localized approach.  

The problem is that MuseScore is using this default information and importing scores using ugly defaults that highlight the origins of the file and not the beautiful default font that was created a couple years ago: Edwin.   Using Times New Roman as your default font is not indicative of someone who cares about a certain look to the score they are trying to retain in MuseScore.

Do not use these as default text fonts when presented and instead use Edwin:

Plantin MT Std - Previous Sibelius default
Palatino - Current Sibelius default
Times New Roman - Finale default
Norfolk Text Std - more of a symbols font with known issues when set in MuseScore as the default text font for all text.

By correcting these font defaults, a fix using B♭ instead of Bb with an import coming from Finale will go from this (how this appears using Times New Roman):

<img width="394" alt="Screen Shot 2023-03-27 at 3 11 17 PM" src="https://user-images.githubusercontent.com/128835319/228078598-3f7cccfc-988c-4692-8ace-0d11e1ab1b62.png">

to this using Edwin

<img width="394" alt="Screen Shot 2023-03-27 at 3 11 34 PM" src="https://user-images.githubusercontent.com/128835319/228078659-6335fe82-75a1-48fb-9e83-4e91c0f8ada9.png">

We want to highlight how much better scores can look in MuseScore using our terrific Edwin font over ugly/boring defaults in other software.  This will complement Leland which is often being defaulted to when imported on the Music Font side of things.

### Additional context

Here are some MusicXML files that test both the need to switch things like "Bb" and contain undesirable default fonts.

[Test XML.zip](https://github.com/musescore/MuseScore/files/11083436/Test.XML.zip)

**Comment by XiaoMigros** [comment]
> In a very related topic, MuseScore sets certain default fonts based on the element . While this is a good approach when a user goes out of their way in other software to change these defaults, the user more commonly does not set anything on purpose or changes the font with a more localized approach.

I would appreciate if we had an option to go the other way: To only use fonts set externally and not to change anything to Edwin. While I agree that most users would probably want the fonts to be replaced, that isn't always the case.

**Comment by oktophonie** [comment]
Actually we have this option already in Edit > Preferences > Import:
![image](https://user-images.githubusercontent.com/20604032/228282266-cc70ba4f-a571-4c1a-a882-241f08755846.png)
What's curious is that
- the first two options used to be on by default
- re Edwin, we used to get a popup in 3.6 to ask whether you wanted it or not, but we don't any more:
![image](https://user-images.githubusercontent.com/20604032/228283315-fa29141d-c210-4331-ad82-9f60170c9afe.png)

So those are the first things to look at.
