### ISSUE TITLE
Parts are not saved in opened state after saving and reopening score

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#17050]
### Issue type

Other type of issue

### Steps to reproduce

1. Open any score
2. Open or create and open a part
3. Save the score
4. Reopen the score

OR open the score (there're two opened parts)
[Untitled score.mscz.zip](https://github.com/musescore/MuseScore/files/11091922/Untitled.score.mscz.zip)

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/101250347/228303015-54e8da9b-3509-4805-881c-392c79635961.mp4

### MuseScore Version

MuseScore 4.0.2 

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

macOS 13

### Additional context

Could be related to https://github.com/musescore/MuseScore/issues/17047

**Comment by DmitryArefiev** [comment]
Fixed in #17065
