### ISSUE TITLE
Deleted in a Part instrument is shown again after moving to score and to the Part back

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#17067]
### Issue type

Other type of issue

### Bug description

@bkunda My expectation for this case is that the user shouldn't be able to delete an instrument from a part, but it could be discussed if you don't agree.

The issue could be linked with https://github.com/musescore/MuseScore/issues/17066

### Steps to reproduce

1. Open any score with 2+ instruments
2. Open a part
3. In the opened part delete an instrument
4. Move to full score (deleted instrument is present)
5. Move back to the part (deleted instrument is present)

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/101250347/228569191-f7367522-905f-4e26-94d7-a7f347cee498.mp4

### MuseScore Version

MuseScore 4.0.2 

### Regression

No.

### Operating system

macOS 13

**Comment by bkunda** [comment]
@abariska agreed. The fact that the instruments _re-appear_ when you toggle the part view is also quite comical, although it does in a way produce the expected result, which is that instruments should never be delete-able from a part (only made visible/invisible). 

I would propose simply disabling the delete button when selecting an **instrument** within the Instruments panel in a part score (Not to be confused with selecting a stave within that instrument, though, where it might still be desirable to allow stave deletion from both the part and the score views). 

Adding this to our 4.1 project, where we will be tackling the relationship between parts and the main score.

**Comment by bkunda** [comment]
@cbjeukendrup FYI
