### ISSUE TITLE
Missing text/staff line properties compared with MS3

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#17074]
### Issue type

UI bug

### Bug description

Unlike MuseScore3 both staff and text line are missing property `Placement` with options `above` or `below`. So the line is always placed above the staff.
Also it is not possible, unlike MuseScore3, to specify a negative hook height which is very useful when the line is placed below the staff.

When importing a MuseScore3 score with a staff or text line placed below the staff (and with a negative hook height) the line is placed as expected so it look like an UI bug to me.

### Steps to reproduce

1. Create a new score.
2. Select a few bars.
3. Add a staff line (palettes -> Lines, select `Staff text line`)
4. Open properties form

There is no option to change the placement.

5. Try the specify a negative hook height

Using the up down button the lowest value is `0.1`. When entering `-1` the value is "corrected" to `0.1`.

### Screenshots/Screen recordings

This is the properties form in MS3:

![Screenshot_20230330_124757](https://user-images.githubusercontent.com/48352523/228813302-b663d2a5-c006-473d-b61c-f6ab5426f3a2.png)

The option within the red rectangle is not available in MS4

### MuseScore Version

OS: openSUSE Tumbleweed, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Linux (openSuse Tumbleweed)

**Comment by oktophonie** [comment]
Negative hook height fixed by https://github.com/musescore/MuseScore/pull/16322
Position is indeed missing. (The X shortcut to flip it still works, at least.)
