### ISSUE TITLE
Mu4.0 crashes on .gtp file

### ISSUE THREAD

**Issue by jessezwd** [musescore/MuseScore#17070]
### Issue type

Crash or freeze

### Bug description

I'm trying to open a .gtp file with Mu4.0 on Manjaro-Gnome linux, Mu4.0 crashes/disappears. here is a comment from MS forum: "Mu3 crashes on it, Mu4 (4.0.2 and latest development build) opens a blank score (with just a title frame and a title)
Best to open an issue on GitHub about this"

### Steps to reproduce

1. go to File and Open
2. choose a .gtp file to open ([Preludio No-1.gtp.zip](https://github.com/musescore/MuseScore/files/11148125/Preludio.No-1.gtp.zip))
3. may 3 second, Mu4.0 crashes/disappears. 

### MuseScore Version

4.0

### Regression

I don't know

### Operating system

Manjaro-Gnome linux

**Comment by cbjeukendrup** [comment]
@jessezwd Could you please upload the gtp file for which this happens, or post a link to the thread where you uploaded the file on MuseScore.org?

**Comment by jessezwd** [comment]
I upload it on MS forum [https://musescore.org/en/node/347329](url). Thanks for your reply.

**Comment by Jojo-Schmitz** [comment]
Rather https://musescore.org/en/node/347329

**Comment by cbjeukendrup** [comment]
Thanks @jessezwd!

@alexpavlov96 Might this be relevant for you?

**Comment by abariska** [comment]
Test tab added to description

**Comment by bkunda** [comment]
Testing again on macOS and Linux:
The file opens without any content (except the title "ludio"), and hangs when scanning audio samples.
However, it does seem possible to open the attached file in Guitar Pro (v8), save it as a new file, and open it successfully in MuseScore 4 (latest nightly).
@jessezwd which version of GP are you saving the file from, and is it still an issue for you in the latest nightly?
Will close shortly if still reproducible.

**Comment by jessezwd** [comment]
> Testing again on macOS and Linux: The file opens without any content (except the title "ludio"), and hangs when scanning audio samples. However, it does seem possible to open the attached file in Guitar Pro (v8), save it as a new file, and open it successfully in MuseScore 4 (latest nightly). @jessezwd which version of GP are you saving the file from, and is it still an issue for you in the latest nightly? Does it happen with other GP files? Will close shortly if still not reproducible.

MuseScore 4 works fine with .gp5 files, the .gtp files are old version, I have not tested it in Guitar Pro (v8) and MuseScore nightly, but you may close this issue.
