### ISSUE TITLE
Feathering resets when beam is selected

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#17075]
### Issue type

Engraving

### Steps to reproduce

1. Enter some notes with a beam
2. Edit feathering left / right value
3. Deselect the beam
4. Reselect the beam
5. The feathering value resets

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/102702868/228812763-6eb7ca66-2c00-404b-b4ae-c575ea98afd7.mp4

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

**Comment by DmitryArefiev** [comment]
Confirm on my side as well. Also, feathered custom state resets after selecting note in the group


https://user-images.githubusercontent.com/90187801/229822738-72f09c20-c86c-4ab6-9760-a9165f0d3a9c.mp4
