### ISSUE TITLE
Gradually Accelerating Tempo Modifiers in MusicXML imports

### ISSUE THREAD

**Issue by smorell-1** [musescore/MuseScore#17081]
### Your idea

Currently, when importing MusicXML elements like "accel." or "stringendo" import as staff text attached to the top staff in the score. I would like to connect new accel. tool launched in MuseScore 4 (available in the tempo palette) to more elegantly address importing these elements.

### Problem to be solved

After importing MusicXML using "accel." or "stringendo", users must delete the staff text created in the import and add a accel. line to replace this behavior. The user must then identify the best location to drag the end of the line to decide where a logical end to the accel would be. This update seeks to streamline this behavior with smart defaults that leverage this great new tool (as seen here).

<img width="665" alt="Screen Shot 2023-03-30 at 1 51 48 PM" src="https://user-images.githubusercontent.com/128835319/228961642-59b66429-4a37-4d9d-a843-e2766a256a33.png">

Attached here is a flowchart for how/when to apply to an accel. line along with logic on where to set the end of the line, what % increase should be included, and when to display the line.

[Logic Path for Gradually Accelerating Tempo Modifiers.pdf](https://github.com/musescore/MuseScore/files/11116078/Logic.Path.for.Gradually.Accelerating.Tempo.Modifiers.pdf)

It is important to note that other updates to the MusicXML import process will need to be made for this to logic to be fully realized. This includes converting other text like "Allegro" to tempo text with a default BPM prior to applying this logic (requested in https://github.com/musescore/MuseScore/issues/17052), updates to gradually slowing tempo modifiers (requested in https://github.com/musescore/MuseScore/issues/17052) and properly creating jump elements for DC/DS form elements from MusicXML imports which will be handled in the future.

### Gradual Accelerating Terms

Here is the list of triggering text used in the gradual acceleration logic.

**Accelerando:** Gradually increase the tempo
Listed as: "accel.", "accel" or "accelerando"

**Stringendo:** gradually speeding up
Listed as: "stringendo"

Please see the list of Gradually Slowing Terms and Steady Tempo Instructions Based on Existing Tempos (Non-Gradual) in https://github.com/musescore/MuseScore/issues/17052 for text that triggers and end point as defined in the attached flowchart in this issue.

### Additional context

Here is a MusicXML file that will test a variety of situations.

[Test Accelerating Tempo Modifiers.zip](https://github.com/musescore/MuseScore/files/11116131/Test.Accelerating.Tempo.Modifiers.zip)

**Comment by oktophonie** [comment]
See also: https://github.com/musescore/MuseScore/issues/14445
