### ISSUE TITLE
Musescore 4 not start (Sorry by my English), I´ve been written text in Spanish because I think is better for your own translation

### ISSUE THREAD

**Issue by Alberthoven2** [musescore/MuseScore#17089]
### Issue type

Crash or freeze

### Bug description

Hola.

Os escribo porque el musescore 4 me está dando miles de problemas. No consigo que se ejecute con normalidad. Desde el primer día que lo instalé solo he conseguido abrirlo 2 veces. El resto es imposible. Se me abre el logo del programa, se cierra y ya está. No aparece nada nunca. He probado a desinstalar el antivirus, desinstalar e istalar de nuevo musescore, revertir el sistema a un estado anterior, etc... y no hay manera de hacerlo funcionar.

También tengo preoblemas con el correo electrónico de confirmación de cuenta. Es este correo, pero por alguna razón no llega nunca, ya lo he pedido 4 o 5 veces y siempre es lo mismo.

Necesito vuestra ayuda porque no entiendo que puede estar pasando y esto ya me empieza a cansar mucho.
Por favor. Ayudadme a solucionar esto lo antes posible. Muchísimas gracias.

### Steps to reproduce

Try to open the program

### MuseScore Version

4.02

### Regression

Yes, this used to work in a previous version of Musescore 4.x

### Operating system

Windows 10 Pro

### Additional context

[DxDiag.txt](https://github.com/musescore/MuseScore/files/11123206/DxDiag.txt)
[Report.txt](https://github.com/musescore/MuseScore/files/11123230/Report.txt)

**Comment by GabeS573** [comment]
Translation: (google translate + editing)

> Hello.
> 
> I am writing to you because MuseScore 4 is giving me thousands of problems. I can't get it to run normally. Since the first day I installed it I have only managed to open it 2 times. The rest is impossible. The logo of the program opens, closes and that's it. Nothing ever appears. I have tried uninstalling the antivirus, uninstalling and installing MuseScore again, reverting the system to a previous state, etc... and there is no way to make it work.
> 
> I am also having problems with the account confirmation email. It's this email, but for some reason it never arrives. I've already asked for it 4 or 5 times and it's always the same.
> 
> I need your help because I don't understand what could be happening and this is starting to tire me a lot.
> Please. Please help me fix this as soon as possible. Thanks a lot.

@Alberthoven2 

I'm not sure what the account confirmation email is referencing, but if it's related to the musescore.com website, you need to email their support team separately. This repository is for reporting issues with the desktop software specifically.

No estoy seguro de a qué hace referencia el "correo electrónico de confirmación de cuenta", pero si está relacionado con el sitio web musescore.com, debe enviar un correo electrónico a su equipo de soporte por separado. Este repositorio es específicamente para informar problemas con el software de escritorio.

**Comment by Alberthoven2** [comment]
Hi guys.

I think I have discovered the problem.

The program does not work if I am using the SteelSeries Sonar application

I leave you a video for a better understanding of what is happening.

PS: Thank you very much GabeS573

**Comment by Alberthoven2** [comment]
https://user-images.githubusercontent.com/18546869/229351592-59419394-ee8c-4fe5-9614-9c05e2d3ac6c.mp4

**Comment by Jojo-1000** [comment]
@Alberthoven2 This looks similar to the crash I get with my SteelSeries GameDAC (and some other audio devices #15235). Do you set Sonar as your audio output in Windows? If it is the same as for me, it should start fine if you set the default windows output (in task bar) to "Chat" instead of "Game".

You could also include a log file `%LOCALAPPDATA%\MuseScore\MuseScore4\logs` of the crash to see if it occurs at the same time during initialization.

**Comment by Alberthoven2** [comment]
Indeed the cause of the failure is the audio output device.

SteelSeries Chat is working normally.

Realtek(R) Audio too.

Steinberg UR22C which is my external audio card also works normally.

Any other configuration causes the application not to run.

I add the log file report.

[MuseScore_230402_235024.txt](https://github.com/musescore/MuseScore/files/11133443/MuseScore_230402_235024.txt)

**Comment by bkunda** [comment]
Seems like this could be related to: https://github.com/musescore/MuseScore/issues/15235, which is better described than the present issue. Closing this one for now.
