### ISSUE TITLE
Doesn't seem to load soundfonts from symbolic links

### ISSUE THREAD

**Issue by itaranto** [musescore/MuseScore#17103]
### Issue type

Other type of issue

### Bug description

On Linux, If I place a symbolic link in `~/Documents/Musescore4/SoundFonts/` it doesn't loads in MS4 while it used to work this way in MS3.

This is handy since I don't have to copy a whole soundfont file in order to use it for MS4.

### Steps to reproduce

1. Create a symbolic link in `~/Documents/Musescore4/SoundFonts/` pointing to an SF2/SF3 file.
2. Open MS4, go to the Mixer and look for recognized soundfonts.

**Expected:**
The new soundfont appears in the Mixer's menu.

**Actual:**
The new soundfont doesn't appear in the Mixer's menu.

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Arch Linux

**Comment by shoogle** [comment]
We should fix this, but as a workaround you could try making the entire `MuseScore4/SoundFonts` directory a symlink to the equivalent MuseScore 3 directory, so that you can use all the same sounds (except SFZs).

**Comment by cbjeukendrup** [comment]
> as a workaround you could try making the entire `MuseScore4/SoundFonts` directory a symlink to the equivalent MuseScore 3 directory, so that you can use all the same sounds (except SFZs).

But then you could as well directly select the `MuseScore3/SoundFonts` directory in Preferences > General > Folders, right?

**Comment by itaranto** [comment]
> > as a workaround you could try making the entire `MuseScore4/SoundFonts` directory a symlink to the equivalent MuseScore 3 directory, so that you can use all the same sounds (except SFZs).
> 
> But then you could as well directly select the `MuseScore3/SoundFonts` directory in Preferences > General > Folders, right?

Nope, I've just tried and it's the same, the app doesn't seem to be following symbolic links.

**Comment by itaranto** [comment]
Also, linking the entire `MuseScore4/SoundFonts` to `MuseScore3/SoundFonts` doesn't work either.

**Comment by MarcSabatella** [comment]
I think the suggestion of changing Preferences was to do that *instead* of using a symbolic link - just tell MuseScore 4 to looking in Documents/MuseScore3/SounfFonts directly, no links involved.  But, a downside of changing the preferences is not surviving revert to factory settings, which I end up doing more often than the average user probably for testing purposes.  So I prefer the symbolic link approach instead personally.

I don't remember having any issues when I had my soundfonts folder be a symbolic link, but actually, right now my entire MuseScore4 folder is a symbolic link, which definitely works, at least on my system (Debian 11, running as a container within ChromeOS).

Check the permissions on your links; that could be causing a problem.

**Comment by itaranto** [comment]
> I think the suggestion of changing Preferences was to do that instead of using a symbolic link 

Yes, I realized that now. That works, as long as the files there are not symlinks of course.

> I don't remember having any issues when I had my soundfonts folder be a symbolic link, but actually, right now my entire MuseScore4 folder is a symbolic link, which definitely works, at least on my system (Debian 11, running as a container within ChromeOS).

Check the permissions on your links; that could be causing a problem.

The permission are fine (755) which are the defaults. Also I installed MS3, and it detects symlinks properly.

**Comment by Jojo-Schmitz** [comment]
Why disallowing symlinks at all in the first place? Why now allowing them for soundfonts only?
In Mu3 they were only disallowed (or rather disabled) for extensions, which we don't (yet?) have for Mu4.

**Comment by itaranto** [comment]
> Why disallowing symlinks at all in the first place? Why now allowing them for soundfonts only? In Mu3 they were only disallowed (or rather disabled) for extensions (MDL and HQ soundfont), which we don't (yet?) have for Mu4.

I don't think the devs here said they've specifically disallowed symlinks, from what I understand this seems to be a bug.

In fact, someone has already opened a PR for this: https://github.com/musescore/MuseScore/pull/17267

**Comment by Jojo-Schmitz** [comment]
I've seen the PR.
But the code changes in MU4 vs MU3 are pretty clear and do explicitly disallow symlinks all the way, they did not in Mu3, except for extensions (MDL and the HQ soundfont, but not for soundfonts in general).
That PR fixes it for soundfonts only.

**Comment by shoogle** [comment]
I assume that whoever excluded symlinks had a good reason for doing so. Maybe they were being overly cautious. Maybe not. It's always best to give the benefit of the doubt until we know the actual reason.

**Comment by Jojo-Schmitz** [comment]
Of course, that's what this issue is for.
I didn't say that is what s stupid idea, just that it seems a deliberate change, and that I don't see a reason
