### ISSUE TITLE
Rotate symbols

### ISSUE THREAD

**Issue by jonarnoldmusic** [musescore/MuseScore#17116]
### Your idea

I would like to be able to rotate symbols inserted from the master palette, presumably from appearance properties.

### Problem to be solved

Specifically, this is an issue for me in the current method of making incipits since notes must be inserted from the medieval and renaissance sections of Bravura. They only appear in the original rotation, which results in the stems being the wrong direction.
![Screenshot 2023-04-02 203628](https://user-images.githubusercontent.com/11447289/229392774-3d7ce045-b546-4e04-8ad2-687446131814.png)

### Prior art

The application I have the most experience with is Lilypond, which can rotate any object: https://lilypond.org/doc/v2.22/Documentation/notation/rotating-object

### Additional context

My particular issue could also be solved by native incipit support, but I believe there might be other uses for rotating objects, like the hairpins in the Lilypond documentation linked above.

**Comment by oktophonie** [comment]
We also need to be able to scale symbols, as well as rotate them.

**Comment by awrog** [comment]
That would be great and would honor an 'old' request of mine (that was not granted).
![image](https://user-images.githubusercontent.com/12153667/231743188-8059a77c-7ec8-40cb-aef0-b133e383105d.png)
