### ISSUE TITLE
Joining measures in parts corrupts score

### ISSUE THREAD

**Issue by jonarnoldmusic** [musescore/MuseScore#17115]
### Issue type

File corruption

### Bug description

When inputting notation into a score, if you use join measures in the part, the other parts receive null content in that measure and the score is corrupted.

### Steps to reproduce

1. Open a score with multiple parts.
2. Open a part, select measures, Tools->Measures->Join Selected Measures
3. Go back to score. All other parts now have null content in resulting measure.
4. Score corruption dialog reports results like:
  Incomplete measure: Full score, measure 5, staff 1. Found: 0/1. Expected: 8/2.
  Incomplete measure: Full score, measure 5, staff 2. Found: 0/1. Expected: 8/2.
  Incomplete measure: Full score, measure 5, staff 3. Found: 0/1. Expected: 8/2.
  Incomplete measure: Part score: Cantus, measure 5, staff 1. Found: 0/1. Expected: 8/2.
  Incomplete measure: Part score: Altus, measure 5, staff 1. Found: 0/1. Expected: 8/2.
  Incomplete measure: Part score: Tenor, measure 5, staff 1. Found: 0/1. Expected: 8/2.

### Screenshots/Screen recordings

![Screenshot 2023-04-02 202700](https://user-images.githubusercontent.com/11447289/229391887-cf9dd3dd-1f70-4d72-a3b4-aee09d85aed9.png)

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 11

**Comment by oMrSmith** [comment]
Maybe it would make sense to restrict the function to split or joint measures to the score
as it will apply to all parts anyway...

**Comment by cbjeukendrup** [comment]
Or at least _under the hood_, this (and almost all other operations involving measures) should happen via the master score, to make sure that all parts and all staves are updated.

**Comment by sammik** [comment]
> @cbjeukendrup please check #19271

Hm, it seems, some Skeletons in the closet appeared.
working on it

**Comment by sammik** [comment]
Should be OK now.
