### ISSUE TITLE
This score keeps crashing when I try to play it

### ISSUE THREAD

**Issue by Attackoh** [musescore/MuseScore#17119]
### Issue type

Crash or freeze

### Bug description

Bar 55 crashes the score when played, bars 55+ crash the score when clicked on.
Issued occured after writing in piccolo line 61-62.
Would be incredibly helpful if someone can find what's going wrong!

[weight of the borld - copy.zip](https://github.com/musescore/MuseScore/files/11134324/weight.of.the.borld.-.copy.zip)

### Steps to reproduce

1. Go to bar 55-62
2. Click on a part
3. Crash?

Or
1. Play the score
2. Score crashes when it reaches 55

### MuseScore Version

4.0.2-230651553

### Regression

Choose option...

### Operating system

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

**Comment by vashutangri** [comment]
Hi, I tried to reproduce the issue but it did not crash at bar 55 for me

**Comment by Attackoh** [comment]
Thanks for checking it out. This bug would be odd if it's exclusive to my computer. Here's some more context if that helps.

https://user-images.githubusercontent.com/120669196/229690764-1d6fa690-4bb8-478b-891e-2031e8c74221.mp4

**Comment by Attackoh** [comment]
I created a new score with and copied in only the problem parts, and the same issue persists. 🤔

**Comment by Attackoh** [comment]
Ok so I got another instance of this bug again which also occurred after I wrote in these piccolo notes. I'm convinced that the piccolo is causing it to crash.
![image](https://user-images.githubusercontent.com/120669196/229751502-93f20a92-71f9-4170-a842-bda7827cc392.png)
 
File below is version of score with only the bugged parts
[1testbug - Copy.zip](https://github.com/musescore/MuseScore/files/11147032/1testbug.-.Copy.zip)

**Comment by Attackoh** [comment]
Here's a vid of me inputting the notes. The performance (framerate) gets worse and worse until it crashes.
https://user-images.githubusercontent.com/120669196/229754076-c6a2b39a-7a87-4b3f-8203-bd2415bf310e.mp4

**Comment by Eism** [comment]
Please attach diagnostic files: on the app menu bar click Diagnostic -> Save diagnostic files

**Comment by Attackoh** [comment]
My musescore crashes and the zip is unusable... 😓 
![image](https://user-images.githubusercontent.com/120669196/229765191-272ea655-d8a2-4e4c-bc0b-69e6f43b1825.png)

**Comment by Attackoh** [comment]
I think I managed to get the diagnostic files
[please work.zip](https://github.com/musescore/MuseScore/files/11147648/please.work.zip)

**Comment by krtschil** [comment]
Neither of your test scores do produce a crash (Linux, 4.02) 
Unfortunately your please.works.zip file cannot be opened or unzipped. I receive an error message :

End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

**Comment by Attackoh** [comment]
[qwerty.zip](https://github.com/musescore/MuseScore/files/11174292/qwerty.zip)
This zip should have no issues

**Comment by Attackoh** [comment]
I have solved the issue. Upon updating Musesounds Winds the crash no longer occurs. This bug was caused specifically by Musesounds piccolo. 

Video below is from before I updated. It shows that other instruments playing the same notes will not crash, but using piccolo will.
[piccolo shenanginaers.zip](https://github.com/musescore/MuseScore/files/11188755/piccolo.shenanginaers.zip)
