### ISSUE TITLE
Freezing or strange behavior when using grace notes.

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#17135]
### Issue type

Crash or freeze

### Bug description

Freezing or strange behavior when using grace notes.

### Steps to reproduce

1 create file for scratch
2 Add note
3 Add graces notes
4 Play with Q or W and Pitch or this grace notes.
5 Sometime scre display becomes corrupted , sometime MuseScore Freeze, all randomly

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/1835871/229852049-5e7e1e66-bbd7-4fb0-b2a2-b18a9aca74c8.mp4

### MuseScore Version

MuseScore version (64-bit): 4.1.0-230920304, revision: github-musescore-musescore-be093e6

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009, Arch.: x86_64

**Comment by bkunda** [comment]
@Gai-Luron are you still experiencing this problem in the latest master?

**Comment by Gai-Luron** [comment]
Hello,
Now seem to work.
Thanks

**Comment by cbjeukendrup** [comment]
Oh, I just realise that my https://github.com/musescore/MuseScore/issues/17287 was actually a duplicate of this... anyway, that does confirm that it has been solved indeed!
