### ISSUE TITLE
Crash when using $M or $m (date and time) macros on a file that has never been saved

### ISSUE THREAD

**Issue by rednoise0** [musescore/MuseScore#17137]
### Issue type

Crash or freeze

### Bug description

When using my own template where I altered the footer style to include either date ($M) or time ($m) variables, Musescrore 4.0.2 crashes immediately when creating a new score based on that template. This happens on three different computers, one running Windows 11, two on Windows 10, fully updated.

No crash when editing the footer for a document, only when that document is used as a template and a new score is created from it.

I tried a couple other variables and it didn't crash. It suspect it's only the date and time variables.

Sample template attached below. Logs folder attached below

[CrashTestTemplate.zip](https://github.com/musescore/MuseScore/files/11152623/CrashTestTemplate.zip)
[logs.zip](https://github.com/musescore/MuseScore/files/11152669/logs.zip)

### Steps to reproduce

1. Edit a template by going to Format | Style |Header, Footer
2. add $M or $m to any of the Footer Text boxes (I haven't tried it with the Header fields.)
3. Save and close the template.
4. Go to File | New | My Templates and chose the template you edited.
5. When you click Done, Musescore crashes hard and tries to send a crash report to Microsoft.

### MuseScore Version

version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 10 Pro Version 10.0.19045 Build 19045

### Additional context

(attached in Description above, but here they are again.)

[logs.zip](https://github.com/musescore/MuseScore/files/11152677/logs.zip)
[CrashTestTemplate.zip](https://github.com/musescore/MuseScore/files/11152681/CrashTestTemplate.zip)

**Comment by Jojo-Schmitz** [comment]
Stems from https://musescore.org/en/node/347698

**Comment by oktophonie** [comment]
A not dissimilar issue: https://github.com/musescore/MuseScore/issues/15313

**Comment by mike-spa** [comment]
This crash is not related to templates: it happens any time you use the $M macro on a file that has never been saved. To see this, create a new file from "Choose instruments", go to Style -> Heder/Footer, use the $M macro somewhere, see crash. The crash is due to the fact that, because the file isn't yet saved to a path, the "last modified" info isn't really available.

**Comment by Jojo-Schmitz** [comment]
Looking at the code that shouzldn't happen though, a not-yet safed score is dirty, so the current date gets used:
```cpp
            case 'm':
                if (score()->dirty()) {
                    d += Time::currentTime().toString(DateFormat::ISODate);
                } else {
                    d += masterScore()->fileInfo()->lastModified().time().toString(DateFormat::ISODate);
                }
                break;
            case 'M':
                if (score()->dirty()) {
                    d += Date::currentDate().toString(DateFormat::ISODate);
                } else {
                    d += masterScore()->fileInfo()->lastModified().date().toString(DateFormat::ISODate);
                }
                break;

```

**Comment by Jojo-Schmitz** [comment]
So I suspect that for some reason the score isn't marked dirty?

**Comment by Jojo-Schmitz** [comment]
Well, that did work in Mu3 though
Actually creating a new score does mark it dirty in Mu4, as seen by the asterisk (Mu3 did not, but did mark it dirty as soon as a $M got added to header/footer and didn't crash on templates using it)).
