### ISSUE TITLE
Deleting whole inner tuplet of nested tuplets corrupts score

### ISSUE THREAD

**Issue by Nekotizimo** [musescore/MuseScore#17147]
### Issue type

File corruption

### Bug description

When you have a tuplet nested inside another tuplet, selecting the entire inner tuplet and hitting delete will corrupt the file. However, deleting only a part of the inner tuplet, or selecting the number of the inner tuplet and hitting delete, produces the expected behavior.  

### Steps to reproduce

1. Create new file with an instrument
2. Create a tuplet
3. Create another tuplet inside that
4. Select the entire inner tuplet, hit delete
5. File is corrupted

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/42693098/230220818-d04eccd5-9f08-4abe-b223-c7bbbd0484c0.mov

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230950503, revision: github-musescore-musescore-8582f3a

### Regression

No.

### Operating system

OS: macOS 12.6, Arch.: x86_64

### Additional context

first issue :D

**Comment by oktophonie** [comment]
For info: this only happens when selecting all the inner-tuplet notes as a range (not as a list).
