### ISSUE TITLE
All types of VSTs being supported 

### ISSUE THREAD

**Issue by DimensionalSpace** [musescore/MuseScore#17158]
### Your idea

So the idea here is to support all types of VST like VST2 or even 32bit versions which the 2000s and early 2010s created. 

### Problem to be solved

It would solve people who paid or used these unsuported VST's so they can use them in future projects.

**Comment by DimensionalSpace** [comment]
Oh I heard FL Studio has support for 32 bit VST's but I couldn't find how they do it but I think this link could help? :https://support.image-line.com/action/knowledgebase/index?ans=415

**Comment by jeetee** [comment]
The SDK simply does not allow for this; one currently can only get licenses for VST3 support and nothing prior.

**Comment by DimensionalSpace** [comment]
So old VST's cannot be used anymore?

**Comment by MarcSabatella** [comment]
Only in old programs.  New licenses are no longer being made available by Steinberg, but companies that already had licenses can continue to use them.  The intent is clearly to encourage VST creators to release VST3 updates.
