### ISSUE TITLE
Additional page setting to determine whether the first page appears left or right in two sided page view

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#17154]
### Your idea

MuseScore will always depict the pages of a score 
as facing pages in page view ( - even if the setting "two sided" is unchecked, which seems a bit strange, but anyway).

By default the first page appears on the right, just like it would in a book.

![image](https://user-images.githubusercontent.com/78870770/230509685-adab3fd4-7fb0-4505-bcbe-ed595011842d.png)

Proposal: The page settings should provide an additional option to control that behavior 
so that the first page can also appear on the left if needed:

![image](https://user-images.githubusercontent.com/78870770/230509977-c2495fb9-db6f-4870-806b-f80d03d71d95.png)

### Problem to be solved

MuseScore is missing a simple option to control the page layout independly from the page numbering.
Achieving a layout, where page 1 & 2 face each other, 
requires the user to create a blank page and mess with page numbers.

![image](https://user-images.githubusercontent.com/78870770/230512094-715626bf-3d5e-4975-ac8a-7f41e8db82be.png)

Even when using this workaround it's currently impossible to maintain such layout due to #17153.

### Possible Design

I think the solution could be pretty straight forward:

![image](https://user-images.githubusercontent.com/78870770/230647019-9a008584-2c22-448e-a5da-ee416b0e6256.png)

**Comment by oktophonie** [comment]
Odd-numbered pages should always be on the right, even-numbered on the left. I don't see a valid use for this suggested setting.
MuseScore, nevertheless, should display the facing pages properly, so https://github.com/musescore/MuseScore/issues/17153 stands.

**Comment by oMrSmith** [comment]
> so #17153 stands.

That's good. And the first page will always be regarded an odd page, correct?
I mean: No matter the given number... Because otherwise the following layout would be impossible to achieve,
since the second page has an odd number.

![image](https://user-images.githubusercontent.com/78870770/231444495-c79eae55-a1f9-4f96-a340-44b3fcb3d77d.png)

**Comment by oktophonie** [comment]
The first page will be a left-hand page if its number is even, a right-hand page if its number is odd. So, yes, the layout shown in your image would, and should, be impossible.
