### ISSUE TITLE
Crash when trying to open an XML file in MS4 (one file)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17150]
### Steps to reproduce

1. Open this music xml file [crash.zip](https://github.com/musescore/MuseScore/files/11170754/crash.zip)

### MuseScore Version

4.1

### Regression

Doesn't occur in **MS3**

### Operating system

Windows10

**Comment by Jojo-Schmitz** [comment]
4.0.2 and laster master crashes on this too

**Comment by cbjeukendrup** [comment]
Seems yet another instance of https://github.com/musescore/MuseScore/issues/16442, which has pending PR https://github.com/musescore/MuseScore/pull/16514

**Comment by Jojo-Schmitz** [comment]
All of a sudden I can't reproduce with 4.0.2 nor with latest master

**Comment by cbjeukendrup** [comment]
It might depend on whether "play repeats" is enabled or not...

**Comment by Jojo-Schmitz** [comment]
Darn, now I can again

**Comment by Jojo-Schmitz** [comment]
No, seems entirely random, one time it crashes on open, next time it does not

**Comment by Jojo-Schmitz** [comment]
So your guess seems right on spot

**Comment by Jojo-Schmitz** [comment]
And it still crashes with the change from that PR.

**Comment by cbjeukendrup** [comment]
That's strange. For me it opens fine and Address Sanitizer doesn't catch anything.

**Comment by Jojo-Schmitz** [comment]
Anyway, #16514 fixes something, so should get in ;-)

**Comment by Jojo-Schmitz** [comment]
Forget my tets, tnat PR does fix it. I forgot the install step, so tested the wrong binary... have a brown paper bag for me?

**Comment by DmitryArefiev** [comment]
> Seems yet another instance of #16442, which has pending PR #16514

@cbjeukendrup 
The crash doesn't happen with that score [crash.zip](https://github.com/musescore/MuseScore/files/11173199/crash.zip) with build from #16514. But I see some chords don't import from xml comparing with MS3. Probably requires a separate issue?
![Capture](https://user-images.githubusercontent.com/90187801/230456852-a9b8eba0-74b7-4590-9da7-a0559a2fffd1.PNG)
![Capture2](https://user-images.githubusercontent.com/90187801/230456863-87c093f3-5ce6-4820-b9a2-c9ba79b62f76.png)

**Comment by cbjeukendrup** [comment]
Yes, there is already an open issue for that

**Comment by DmitryArefiev** [comment]
Oh, thanks!

**Comment by DmitryArefiev** [comment]
Fixed in #16514
