### ISSUE TITLE
[WEB] Some issues with parts in PDF on musescore.com

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17162]
### Steps to reproduce

**BUG 1**: Some parts in PDF are empty when downloaded from musescore.com, if they were not opened as tabs in MS while publishing 

1. Create a score (or open [publish2.zip](https://github.com/musescore/MuseScore/files/11179346/publish2.zip) )
2. Open some parts but not all
3. Publish
4. Go to musescore.com>your score>Download>PDF
5. Select all parts and download - some PDF of parts are empty

**BUG 2**: Custom parts are not available in musescore.com>your score>Download>PDF
1. Open [Check PDF publish (with custom parts).zip](https://github.com/musescore/MuseScore/files/11179371/Check.PDF.publish.with.custom.parts.zip)
2. Publish
4. Go to musescore.com>your score>Download>PDF - **the custom parts are not present**

### Screenshots/Screen recordings

**BUG 1**

https://user-images.githubusercontent.com/90187801/230620684-3f136d46-5f3f-4113-8f50-b94e1ec07494.mp4

https://user-images.githubusercontent.com/90187801/230620835-2f6383b2-7b33-4a4f-aa9d-a5d6a6b509ef.mp4

--

**BUG2**
![Capture](https://user-images.githubusercontent.com/90187801/230621198-da2873da-dcf4-45a7-ba7d-825265066aa1.PNG)

### MuseScore Version

4.1

### Regression

No.

### Operating system

Windows10

**Comment by bkunda** [comment]
@Eism why was this reopened?

**Comment by DmitryArefiev** [comment]
@bkunda I've checked that in latest master
**BUG 1:** Some parts in PDF are empty when downloaded from musescore.com, if they were not opened as tabs in MS while publishing **is FIXED**

But **BUG 2:** Custom parts are not available in musescore.com>your score>Download>PDF **STILL OCCURS**

![Capture](https://github.com/musescore/MuseScore/assets/90187801/6fe57e97-79e9-42d2-917c-0388d2c82ec3)
