### ISSUE TITLE
Musescore keeps crashing 

### ISSUE THREAD

**Issue by ParaliyzedEvo** [musescore/MuseScore#17193]
### Issue type

Crash or freeze

### Bug description

I tried asking the Musescore forum (which obviously didn't work) I already did the obvious things that people would do first. I already restarted my PC, uninstalled and reinstalled Musescore, just installed the standalone version, went back a few versions up to Musescore 4.0 and nothing. It keeps crashing, I already did some things that people wouldn't normally do like run sfc and DISM but that didn't work. I searched for forums but nothing like this has ever happened. The only thing that can work is Musescore 3 but to be honest I don't wanna to back to that. I checked event manager and it gave me this error

Faulting application name: MuseScore4.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1537, time stamp: 0x3c85b7e0
Exception code: 0xe06d7363
Fault offset: 0x000000000006536c
Faulting process id: 0x0x2318
Faulting application start time: 0x0x1D96B5B6F510E13
Faulting application path: C:\Program Files\MuseScore 4\bin\MuseScore4.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: e9c72651-14e2-4447-bfc7-47146bd77fc1
Faulting package full name:
Faulting package-relative application ID:

Don't know what this means or what's happening but I just need it to stop crashing, please help me I wanna finish some projects. I also provided a crash dump below to try and help you guys.

### Steps to reproduce

1. Opening Musescore by a score or icon at desktop or by clicking on the .exe itself 

### Screenshots/Screen recordings

![](https://musescore.org/sites/musescore.org/files/2023-04/Screenshot%202023-04-09%20222156_0.png)

### MuseScore Version

4.02 and 4.01

### Regression

No.

### Operating system

Windows 11

### Additional context

I am using a Asus 1080 with a i5 10400 with 48 gigs of ram
Crash dump below:
[MuseScore4.exe.9660.zip](https://github.com/musescore/MuseScore/files/11194535/MuseScore4.exe.9660.zip)

**Comment by ParaliyzedEvo** [comment]
Bump

**Comment by ParaliyzedEvo** [comment]
Bump

**Comment by cbjeukendrup** [comment]
If you do that one more time I'll just close it. Issues get fixed when it is their turn. It makes no sense to annoy us every day about it.

**Comment by ParaliyzedEvo** [comment]
Thanks, nightly builds work fine and I'm sorry if I caused any trouble, thanks!

**Comment by cbjeukendrup** [comment]
Glad to hear that the nightly builds do work! 

And don't worry, maybe I was a bit _too_ annoyed. But, you know, sometimes we see people who keep pinging us because they think that they and their issue are the most important in the world...

**Comment by Auase** [comment]
+1
=============
win11
=============
4.0.2 & 4.1.0_dev
=============
error:0xe06d7363
=============
error id:ID: 0x0x14C4
=============
Wrong module path:C:\WINDOWS\System32\KERNELBASE.dll （version: 10.0.22621.1555）
================

**Comment by cbjeukendrup** [comment]
@Auase Does it crash for you when you see the loading screen, or after the main window has been visible? 
And the nightly builds (https://musescore.org/en/nightly-builds) don't even work either?

**Comment by Auase** [comment]
I estimate it may be related to file read and write permissions, which resulted in the lack of permission to recover the system files used during uninstallation (deleting all uninstallation residues and registry related items has no effect)

**Comment by Auase** [comment]
I estimate it may be related to file read and write permissions, which resulted in the lack of permission to recover the system files used during uninstallation (deleting all uninstallation residues and registry related items has no effect)

**Comment by Auase** [comment]
> 当您看到加载屏幕时，或者在主窗口可见后，它会崩溃吗？夜间构建（https://musescore.org/en/nightly-builds）甚至也不起作用？

Yes, the main window crashed before it could load

**Comment by Auase** [comment]
> @Auase Does it crash for you when you see the loading screen, or after the main window has been visible? And the nightly builds (https://musescore.org/en/nightly-builds) don't even work either?

Yes, the main window crashed before it could load

**Comment by Auase** [comment]
@cbjeukendrup 
After the crash in 4.0.2, there was an audio issue when using 4.1.0- dev, resulting in severe latency and invalid timbre (pitch cannot be distinguished)

**Comment by Auase** [comment]
@cbjeukendrup 
After the crash in 4.0.2, there was an audio issue when using 4.1.0- dev, resulting in severe latency and invalid timbre (pitch cannot be distinguished)
