### ISSUE TITLE
musescore 4 rolls grace note chords

### ISSUE THREAD

**Issue by janmusija** [musescore/MuseScore#17229]
### Issue type

General playback bug

### Bug description

Instead of articulating the notes in grace note chords simultaneously, MS4 articulates them as if they were rolled, or perhaps as if indicated to be played one by one from lowest on the staff to highest on the staff. This does not depend on whether you use the basic soundfonts or muse sounds.

### Steps to reproduce

1. Create a score. Instrument choice doesn't seem to matter but this issue definitely occurs on piano 
2. Write a note anywhere in the score
3. Add a grace note to this note. Doesn't matter what kind.
4. Make this grace note into a chord by adding intervals on top. Doesn't matter how many, though the effect is more obvious with more notes:
5. Hit "play"; it should sound rolled
6. Export the audio; it will again sound rolled.

### Screenshots/Screen recordings

<img width="260" alt="image" src="https://user-images.githubusercontent.com/110359879/231617381-b8441597-897b-4557-80f7-89a91524beb0.png">

(audio export from this image):

https://user-images.githubusercontent.com/110359879/231618685-0bb43eb8-758e-424d-8393-688c6a374ad5.mp4

### MuseScore Version

MS 4.0.2-230651546

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

macOS 12.5 (x84)

### Additional context

Works fine in my installation of MS3, which is version 3.6.2.548020600.

**Comment by DmitryArefiev** [comment]
Fixed in #17266
