### ISSUE TITLE
No playback, crashes (segfault) on changing buffer size

### ISSUE THREAD

**Issue by Spaceginner** [musescore/MuseScore#17239]
### Issue type

Crash or freeze

### Bug description

When trying to change buffer size in I/O section of prefenreces musescore crashes with seg fault. Also when trying to playback anything, it seems like it is loading sounds (shows as it plays, however it actually do anything), but it is default playback (not muse sounds) so there isnt anything to load.

Also, whose idea was to make context menus as a separate windows? it looks HORRIBLE (and kinda unusable) on tiling compositor

### Steps to reproduce

1. install hyprland (or i think any other wayland compositor)
2. install musescore (`musescore` package)
3. try playbacking any score
4. try changing buffer to anything else than 1024

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/97038786/232053718-a8bb33d8-86e8-4d6e-912c-9a8f3d067537.mp4

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

Arch linux with zen kernel 6.2.10

### Additional context

Log (from stdout): https://pastebin.com/3fcXgQxv

Using PipeWire

CPU: AMD FX6100
GPU: NVidia GTX 1660 Super (`nvidia-open-dkms` driver with `nvidia-drm.modeset=1` kernel paramater)
Memory: 16 GB DDR3
Drive type: SSD

**Comment by lzqlzzq** [comment]
Here is my ouptuts of `alsa-info.sh`: http://alsa-project.org/db/?f=b0a3abf0cbefc1b54dea01a23070933123a0e354
