### ISSUE TITLE
[MU4 Task] Choosing soundfonts

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#17233]
New UX for being able to choose specific soundfont instruments
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/71656189/231731195-019ecf50-1d45-4ca5-aa46-b6d97bf99703.png">

Link to Figma page (Choosing soundfonts): https://www.figma.com/file/tn0dH2CQRbh53oYJI4Hquv/Mixer?node-id=6-35

**Comment by ccchips1949** [comment]
I am glad this is being worked on!

For many soundfonts, regular instrument categories don't really apply.  For instance, the stefans cathedral organ soundfont I use contains 5 banks, and for the most part, the banks apply to a particular keyboard (pd for pedals, g for great, sw for swell, c for choir, s for solo, and p I don't recall.)  For instance, there are sw_bordun_8, g_bordun_8, pd_bordon_16, etc.  How you would implement this in your menu design I can't say, but I would suggest sorting soundfonts by bank number, then program number internally, then display them in sorted order.

Thank you for your work.  I hope this helps some.
