### ISSUE TITLE
MuseScore 4 crashes when opening scores from OpenScore Lieder Corpus

### ISSUE THREAD

**Issue by apacha** [musescore/MuseScore#17241]
### Issue type

Crash or freeze

### Bug description

When trying to open a few songs from the OpenScore lieder corpus in MS4, the application reliably crashes, see https://github.com/OpenScore/Lieder/issues/4 for a full list.

### Steps to reproduce

Try to open the file like this https://github.com/OpenScore/Lieder/files/11219372/09_Der_Spinnerin_Nachtlied.zip with MuseScore 4 and the application crashes.

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651546, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

macOS 13.3, Arch.: x86_64

**Comment by DmitryArefiev** [comment]
Fixed in #17242
