### ISSUE TITLE
Incorrect text used for tooltip

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#17252]
### Issue type

UI bug

### Bug description

Tooltip for trash icoon in instruments panel not showing correct information. It tells you that it will remove the instrument, however when a single staff is selected it only removes the staff.

See screenshot:
![image](https://user-images.githubusercontent.com/13550012/232294642-ec6f1fcc-4167-4fbf-a43c-6f1a7f39f6a0.png)

I would suggest to change the text to something like: Remove selected instruments/staff.

### Steps to reproduce

Create a score and use an instrument which has multiple staves
Open the instrument panel
Reveal the instrument staves
Select a staff and hover over trash icon

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/13550012/232295243-abd1c353-46ad-4a55-9a48-75ec529c7801.png)

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
@bkunda Should we try to make this label "dynamic", i.e. if you have instruments selected it says `"Remove selected instruments"` and if you have staves selected it says `"Remove selected staves"`? Or can we simply change the text to `"Remove selected instruments/staves"`?

**Comment by henkdegroot** [comment]
> Should we try to make this label "dynamic"

That would be very nice!


> "Remove selected staves"

You cannot select multiple staves....at least I could not when I checked hence I used staff :)

**Comment by DmitryArefiev** [comment]
Fixed in #17280

**Comment by DmitryArefiev** [comment]
@bkunda Now it looks this way

https://user-images.githubusercontent.com/90187801/234217376-8f253b7f-8d16-4c64-9c0e-46aa4465a8df.mp4
