### ISSUE TITLE
Restore 'Auto' button for slur and tie position

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#17260]
In the Properties panel the 'Auto' button for slur and tie position went awol; we can set Above or Below:
![image](https://user-images.githubusercontent.com/20604032/232495803-b073e8f8-2231-4440-889d-4a9e4cd0bfa1.png)
but, having done so, cannot explicitly return to 'Auto' mode, except by resetting the position (Ctrl+R of Format > Reset shapes and positions.)

The Auto button should be restored, thusly:
![image](https://user-images.githubusercontent.com/20604032/232496424-af89c54b-2883-41bd-a811-9fbc42aed758.png)
(though not pink, obviously).

**Comment by cbjeukendrup** [comment]
Isn't this a duplicate of #11107, which has already been fixed in master?

**Comment by oktophonie** [comment]
I knew it sounded familiar!
