### ISSUE TITLE
The program crashes every time the monitor sleeps

### ISSUE THREAD

**Issue by Auase** [musescore/MuseScore#17273]
### Issue type

Crash or freeze

### Steps to reproduce

The program crashes every time the monitor sleeps.

### Screenshots/Screen recordings

![Uploading 20230419004743.png…]()

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

win11

**Comment by DmitryArefiev** [comment]
**Can't reproduce** it on my side (Windows11)

@Auase Can you provide more info please? (Environment, monitor or computer sleep, does it occur with MS3 and other apps)

**Comment by Auase** [comment]
@DmitryArefiev 
[MuseScore_230505_171455.log](https://github.com/musescore/MuseScore/files/11404867/MuseScore_230505_171455.log)
[MuseScore_230505_171820.log](https://github.com/musescore/MuseScore/files/11404868/MuseScore_230505_171820.log)
------------------------------------------
The following is a copy of the system error report file：
（Due to format limitations in uploading files, i have to compress them）
[WER2F1E.tmp.zip](https://github.com/musescore/MuseScore/files/11404900/WER2F1E.tmp.zip)

**Comment by Auase** [comment]
![bug](https://user-images.githubusercontent.com/56365735/236423728-eff4a1cc-901f-4e0d-a755-7e3ef29e1fd3.png)

**Comment by DmitryArefiev** [comment]
Thanks! 

Can you attach MS diagnostic files please (Menu bar>Diagnostic>Save diagnostic files)?

Also, can you answer some questions:
What is your environment (Laptop or Workstation, external monitor, external sound card, CPU, memory amount)?
Do you have the same crash with another apps?
MS crashes only when monitor sleeps or computer sleeps?
Does it crash even after several minutes of sleep?

**Comment by Auase** [comment]
@DmitryArefiev 
Hello, only MuseScore crashes during screen sleep. Here is the relevant information:
[Diagnostic files.zip](https://github.com/musescore/MuseScore/files/11406326/Diagnostic.files.zip)
![20230505201912](https://user-images.githubusercontent.com/56365735/236460629-15b9cb8e-b575-433f-bf18-c4dc87064ea4.png)
![20230505202006](https://user-images.githubusercontent.com/56365735/236460648-068ec69c-23f5-462d-a217-76892a179438.png)
![20230505202108](https://user-images.githubusercontent.com/56365735/236460676-6ef3c62c-3530-4c38-84ab-bf8e888e5b6b.png)
![20230505203243](https://user-images.githubusercontent.com/56365735/236460697-83192ae9-16b5-4987-8142-137e7f8f69e8.png)

**Comment by Auase** [comment]
@cbjeukendrup 
Thank you, (master)this version has indeed solved the problem. Is this a real fix or other reason?

**Comment by cbjeukendrup** [comment]
Thanks! In a way, that is good news, because that means that it has most likely the same root cause as #15235. On the other hand, that issue is still very much a mystery for us. The problem is that in nightly builds, or any other build without a MSI installer, it works fine, but if we create a build from exactly the same code but _with_ an installer, it crashes. Anyway, eventually we will find out the reason. It's just a matter of time and perseverance :)

**Comment by cbjeukendrup** [comment]
@Auase Good news: the mystery about that issue has been solved (seemingly)! Could you please do the following:
1. Download this build: [MU4_231261829_Win_fix_windows_crash](https://github.com/musescore/MuseScore/suites/12721517963/artifacts/683225342)
2. Run the MSI installer from that ZIP folder
3. Try to reproduce the crash in the version installed by that installer

Thanks!

**Comment by Auase** [comment]
@cbjeukendrup 
congratulate! It does not have this issue with me anymore. It works normally when the display output and external sound card audio output are turned off during playback. I opened the installation without unzipping it.

**Comment by Auase** [comment]
@cbjeukendrup 
I have a question to ask, but I know that posting on this page is not suitable. If possible, could you please send me an email or let me know which page to discuss?
-------------------------------------------
This is what I want (just add the display, no need to change the sound):
![20230508204256](https://user-images.githubusercontent.com/56365735/236843344-d551d22e-2896-4d84-aed4-90b3682de935.png)
 but I am not familiar with this project and feel at a loss after reading the code. I hope you can tell me some key steps.

**Comment by MarcSabatella** [comment]
MuseScore doesn't support Jianpu directly, but if you want to ask for help in how to create this notation using the tools that do exist, the official Support forum on musescore.org is the place to ask.

**Comment by Auase** [comment]
@MarcSabatella 
Hello, I understand what you said. Before asking the question, I had already checked the relevant information on the forum. What I mean is that I want to create this feature myself and know the key code file structure related to it. You understand this project, and if I could get your help, I would have avoided many detours.

**Comment by Auase** [comment]
@MarcSabatella 
Thanks!

**Comment by Auase** [comment]
@MarcSabatella Unfortunately, the link has expired
![Screenshot_20230509_204531](https://github.com/musescore/MuseScore/assets/56365735/929b0030-98ba-4aca-a7d5-92e628037b25)
