### ISSUE TITLE
Visibility state of Tempo text not maintained when opening Part

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#17274]
### Issue type

UI bug

### Bug description

Not sure if this is Engraving or UI. Please adjust if I picked the wrong type.

When a score is created, the only way to "define" a tempo is by adding a tempo text, set it to the desired value and then hide the tempo text. Not a major issue to overcome....

When I open the parts, I notice the Tempo text has changed from invisible to visible. This means I manually have to edit every part now and hide all tempo text. 

The visibility state should be respected when the part is opened. 

### Steps to reproduce

Create a new score
Add a tempo text
Hide the tempo text
Now click the Parts button and open the instrument part.
Check the tempo text state.

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
Certainly a) not a regression and b) by design.
Visibilty is part of layout and as such not synced between main score and parts. It does get copied though on part creation.

**Comment by henkdegroot** [comment]
@Jojo-Schmitz, please check as this is how it works in 3.6 and also how it works in MS4 for other elements (like staff text) just not for tempo text.

I can understand it will not be maintained AFTER the part has been generated/opened the first time. But hidden items in the main score should remain hidden when the part is opened for the first time.

**Comment by henkdegroot** [comment]
> how it works in MS4 for other elements (like staff text) just not for tempo text.

Silly.....but seems to work as expected...looks like I generated the parts before adding the tempo text.

**Comment by MarcSabatella** [comment]
Of course, in real world scores, you wouldn't normally want to hide the tempo for parts, unless you want everyone playing at a different speed because they are all guessing differently...
