### ISSUE TITLE
qt5-declarative 5.15.9+kde+r23-1 Bug MuseScore

### ISSUE THREAD

**Issue by ivanmelillo** [musescore/MuseScore#17276]
### Issue type

Other type of issue

### Bug description

With the new update of qt5-declarative 5.15.9+kde+r23-1 MuseScore cannot display the score editor. I'm an Arch user and had to downgrade to qt5-declarative 5.15.9+kde+r22-1

### Steps to reproduce

Update system pacman -Syu, y qt5-declarative 5.15.9+kde+r23-1 and open musescore

### Screenshots/Screen recordings

![Screenshot_20230418_215948](https://user-images.githubusercontent.com/67931709/232938029-fd715b99-e32b-4762-a93b-54b76da05314.png)

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

ArchLinux

### Additional context

The bug is due to the qt5-declarative 5.15.9+kde+r23-1 update. With Downgrade MuseScore works correctly

**Comment by Jojo-Schmitz** [comment]
As far as I know the AppImage used Qt 5.15.2, the last public available package.
I don't think we're supporting any distribution build. Or is this happening with the AppImage?

**Comment by Jojo-Schmitz** [comment]
Then report this to the maintainers. Here we're only responsible for the AppImage

**Comment by ivanmelillo** [comment]
In appimage MuseScore works correctly. See the test I did!

https://user-images.githubusercontent.com/67931709/233144524-abb43ea7-75a8-4f30-8b9e-79af1ca2589f.mp4
