### ISSUE TITLE
Empty midi file is saved when exporting a part of the score

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#17312]
### Issue type

Other type of issue

### Bug description

To reproduce the issue use  any score, e.g [PIZZ.mscz.zip](https://github.com/musescore/MuseScore/files/11297574/PIZZ.mscz.zip)

### Steps to reproduce

1. Open the score
2. In the Export dialog select Midi > select Violin II part and Score
3. Tick all checkboxes and export
4. Open the midi files in any DAW (or import to MU4)

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/101250347/233686525-40f3e1a9-2514-41a8-a42c-f0ab8491a4a0.mp4

### MuseScore Version

MuseScore 4.0.2 

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 13

**Comment by HemantAntony** [comment]
@abariska I made a PR: #17321
