### ISSUE TITLE
Pauses not working properly and delaying playback

### ISSUE THREAD

**Issue by PholMC** [musescore/MuseScore#17329]
### Issue type

General playback bug

### Bug description

When using a caesura for large scores, sometimes, it works and pauses the score for a second or two but in some cases, no matter what I do, the caesura doesn't work and delays the score playback by a second or two even though the playback line shows that the caesura did work.

### Steps to reproduce

1. Create a concert band score
2. Use a caesura for the flute part only
3. Input notes for multiple staffs
4. Insert the caesura in between measures with notes and at the end where after there are no notes
5. The score should either pause for a few seconds or playback gets delayed

### Screenshots/Screen recordings

https://www.youtube.com/watch?v=eGEzHUtNZz8&ab_channel=PhilMC_

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 11

### Additional context

All instruments sounds being used are Musesounds.

**Comment by Ahh6483** [comment]
I am also experience this issue in a Voice and Piano score, audio play back does not follow the blue line on screen.

(Mac OS)

**Comment by DmitryArefiev** [comment]
Fixed #20982

Please reopen if still occurs
