### ISSUE TITLE
Extracting individual parts on multi-voice staves DELETES last measure and replaces with a whole rest 

### ISSUE THREAD

**Issue by 1004PTLN** [musescore/MuseScore#17326]
### Issue type

UI bug

### Bug description

I have added this to the MuseScore forum as well but not answers.   When you have multivoice staves and try to extract each voice independently, the system deletes the notes in the last measure and replaces them with a whole rest.

### Steps to reproduce

(1) Create a new score, 
(2) Add a few notes in several voices to the score and ensure there are notes in the last measure,
(3)  Go to the parts icon, or File/Parts/Open Selected/Select One voice from Voices Visible in the Score.  
(4) You should see that the system deletes **last measure's** notes and replaced with a whole rest.

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/78986148/233851440-809be981-3c10-4065-a24f-b268d5fb1832.png)

![image](https://user-images.githubusercontent.com/78986148/233851542-d3c2388a-d7cc-4964-8e92-b79e0c0a91a2.png)

![image](https://user-images.githubusercontent.com/78986148/233851560-45d87574-1f87-4a85-8de9-a5101da6b73a.png)

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 10

### Additional context

Scfreen shots above

**Comment by DmitryArefiev** [comment]
Fixed in #17327

**Comment by 1004PTLN** [comment]
Thank you very much [DmitryArefiev](https://github.com/DmitryArefiev) for such a quick resolution.  I am new to MuseScore coming from Finale and Encore.  Can you tell me what the typical time frame is for these changes to make it into the production software?  Thank you again.
