### ISSUE TITLE
Changing time signature deletes stave spacer

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#17339]
### Issue type

Engraving bug

### Bug description

Wanting to change a time signature while having a stave spacer should not be deleted. 
Note - tried this with key signatures - no error, just time signature.

Tried and tested on MS3, also does the same behaviour - looks like it has always done this.

### Steps to reproduce

1. Create score with multiple instruments
2. Apply a stave spacer from palettes inbetween one of the instruments and stretch to a reasonable height
3. Apply/change time signature from palettes

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/71656189/233974553-f8733f69-8bf6-4a39-8c80-7c95ba6ecc75.mov

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

MacOS

**Comment by oktophonie** [comment]
I'd just lump it in with that.
