### ISSUE TITLE
-v/-h commands do not work

### ISSUE THREAD

**Issue by Eism** [musescore/MuseScore#17337]
### Issue type

Other type of issue

### Bug description

The -v/-h commands output an empty string. This is a consequence of the recent refactoring of the CommanLineController in this commit: https://github.com/musescore/MuseScore/commit/74a0fc548111afa0ba3890e519241f89b1e50d5c.

Also see https://github.com/musescore/MuseScore/issues/17247#issuecomment-1510443996

### Steps to reproduce

Run MuseScore in the terminal:
./musescore -v

### MuseScore Version

4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

any

**Comment by DmitryArefiev** [comment]
Fixed in #17510
