### ISSUE TITLE
After deleting all measures and recreating some, there is no time signature 

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#17336]
1. Create score
2. Ctrl+A to select all measures
3. Ctrl+Delete to delete them
4. Ctrl+B a few times to create new measures

Result: the new measures don't have any time signature

Same behaviour in MS3

Note: when simply deleting the first measure, the time signature survives. So this only happens when deleting all measures. It does not seem to have any disastrous consequences, but it's certainly a bit weird.

https://user-images.githubusercontent.com/48658420/233960201-256da0e5-26f6-483c-8d79-9e79cc2df7f3.mov

**Comment by oktophonie** [comment]
(Same with key signatures)
