### ISSUE TITLE
Part score gets into inconsistent state when undoing after making instrument visible

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#17333]
1. Create score with >= 2 instruments 
2. Open some part score
3. Make some other instrument visible in this part score
4. Undo

Result: the other instrument is removed from the score as expected, but the instruments panel still thinks that the instruments are is visible (look at the eye icon). Clicking the eye icon has no useful effect. This is not fixed after saving and reopening.

https://user-images.githubusercontent.com/48658420/233872376-447457b7-c912-4a4d-be45-222f86b1a032.mov

The problematic code is here:
https://github.com/musescore/MuseScore/blob/13404af0f51fc8159d8b935c729703004c0ddb23/src/notation/internal/notationparts.cpp#L753-L755
The problem is that this code does not register the change with the undo stack, and thus this change is not properly undone.

**Comment by bkunda** [comment]
@cbjeukendrup don't worry – @DmitryArefiev has just verified this.
