### ISSUE TITLE
Some brackets cannot be deleted

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#17341]
Since https://github.com/musescore/MuseScore/pull/16734 (4.1.0-230801020, revision: github-musescore-musescore-3feb99d), some brackets cannot be deleted.

Create, for example, a score with flute, oboe and piano:

![image](https://user-images.githubusercontent.com/20604032/234027091-1d67aeae-6d9f-4d05-bc8d-85caa1c13d2e.png)

The Fl/Ob bracket cannot be deleted on any system. The brace can.
The brace seems to be relevant: this problem only affects the bracket immediately above an instrument with a brace. In this example:
![image](https://user-images.githubusercontent.com/20604032/234027734-32ddbefb-8884-4329-9885-d3eeac2b3dc7.png)

The Horn/Trumpet bracket cannot be deleted, but the other two can.

**Comment by bkunda** [comment]
@oktophonie can you review the priority of this please?

**Comment by mike-spa** [comment]
Closing as neither I nor @oktophonie can't seem to replicate this issue in the current master. It may have been fixed unknowingly as part of other jobs. If anyone can replicate the issue I'll reopen it 👍
