### ISSUE TITLE
Feature request: Automatic updates from the Windows Store

### ISSUE THREAD

**Issue by marczellm** [musescore/MuseScore#17359]
### Your idea

Change the distribution method of MuseScore in the Windows Store from this:
![image](https://user-images.githubusercontent.com/6771275/234366656-48ac5238-026a-4d6b-b3bd-f2b3e556db26.png)
to this:
![image](https://user-images.githubusercontent.com/6771275/234366721-936985b4-dc1a-4261-9654-dd535d8d9cc6.png)
I believe the [Microsoft docs](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/publish-update-to-your-app-on-store) call the first one a MSIX app and the second one a MSI/EXE app. The main difference is that this second distribution method does not enable automatic app updates managed by the operating system.

### Problem to be solved

I strongly prefer apps using the OS native update mechanism instead of having their own updaters, for several reasons:

- The OS can optimally choose the best time to non-disruptively update stuff because it knows what my "active hours" are, it can balance app updates with OS updates, anti malware scans, disk defragmentation, telemetry scans and other scheduled tasks
- Bespoke updaters use additional resources
- Bespoke updaters can have separate bugs

Additionally, this chosen method of distribution has the idiosyncratic problem that the Store 'forgets' it has ever installed this app. If you open the Store app a second time, it still displays the Install button instead of Launch.

### Prior art

Other OSS projects like WinSCP or LibreOffice are using a model where they are selling the app on the Store, for money, in exchange for the convenience of OS managed automatic updates. I would certainly be willing to pay for that here too.

**Comment by Tantacrul** [comment]
We're not going to do that. Sorry.
