### ISSUE TITLE
Generated parts are missing voltas

### ISSUE THREAD

**Issue by bmarwell** [musescore/MuseScore#17354]
### Issue type

Engraving bug

### Bug description

Generating parts from a score in MuseScore 4.0.0, 4.0.1 or 4.0.2 will have missing voltas (1. / 2nd) on most occasions.

### Steps to reproduce

* Create score
* Add voltas
* Create parts

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Manjaro x64

**Comment by bmarwell** [comment]
After re-adding the voltas to one random part, they now appear in every part.

**Comment by oktophonie** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/16096
