### ISSUE TITLE
Crash after opening/generating parts and closing score (some old scores, Windows only)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17364]
### Issue type

Crash or freeze

### Steps to reproduce

1. Open [F.B._Piano_Anime_Collection_8_scores.zip](https://github.com/musescore/MuseScore/files/11333288/F.B._Piano_Anime_Collection_8_scores.zip) or 
[MU3.6.2 Shostakovich_Waltz.zip](https://github.com/musescore/MuseScore/files/11333289/MU3.6.2.Shostakovich_Waltz.zip)
2. Open all parts
3. Click X button to close score
4. Click **Don't save** (or **Save** and save the score)

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/90187801/234590106-f2294ad2-8f1b-4a25-836b-6dd45c89229d.mp4

Another case:

https://user-images.githubusercontent.com/90187801/234590334-34959857-66ee-4e54-abc6-be504722d48f.mp4

### MuseScore Version

4.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows10

**Can't reproduce** on **Mac**

**Comment by cbjeukendrup** [comment]
@DmitryArefiev Unfortunately I cannot reproduce it, not even on Windows, and not even using the nightly builds or self-built development builds...

**Comment by cbjeukendrup** [comment]
@DmitryArefiev I investigated little bit more, and I found that I _can_ reproduce it with the nightly build from April 24, but _not_ with the one from April 25. So most likely it got fixed! 

Just for the record: these are the PRs that have been merged on April 24: https://github.com/musescore/MuseScore/pulls?q=is%3Apr+merged%3A2023-04-24..2023-04-25
Maybe #13284 has fixed it.

**Comment by DmitryArefiev** [comment]
Oh, thanks!
