### ISSUE TITLE
Tick barline tooltip error in Barlines palette

### ISSUE THREAD

**Issue by JLWALTENER** [musescore/MuseScore#17385]
### Issue type

UI bug

### Bug description

The actual tooltip for the Tick barline tells Dashed barline.
There are 2 Tick berline, this one and the Tick barline 2 just on the right.
The dashed barline is in the right and above.
The exact name of this barline should be in the tooltip "Tick barline"

### Steps to reproduce

1 - Go to Barline palette
2 - Go to the Tick Barline
3 - See the wrong name Dashed barline in the tooltip

See the screenshot below :

### Screenshots/Screen recordings

![Barline tooltip error](https://user-images.githubusercontent.com/28805324/235156243-af60a055-5357-4c70-b0cd-92e79b7737c8.png)

### MuseScore Version

4.0.2 and Nightlies

### Regression

I don't know

### Operating system

Windows 10

**Comment by fhrw** [comment]
Apologies if this is completely wrong - I'm in a bit over my head, however I am very interested in helping!

I'm wondering if this line (355 of internal/palettecreator.cpp) is the source of the issue?

``` cpp
            { BARLINE_SPAN_TICK1_FROM,  BARLINE_SPAN_TICK1_TO,  SymNames::userNameForSymId(SymId::barlineDashed) },
```

I'm wondering if it needs to be changed to barlineTick? I'd be happy to make a PR and start attempting to fix. I haven't quite got the local building set up yet but will try this solution in the morning when I have it going!

**Comment by Jojo-Schmitz** [comment]
Seems indeed likely to be the culprit.
Actually I just tested: yes it is! I'll leave it to you to create a PR ;-)

**Comment by Jojo-Schmitz** [comment]
It is a regression vs 3.x BTW

**Comment by Jojo-Schmitz** [comment]
And no, it doesn't change strings, just pick on an existing one

**Comment by fhrw** [comment]
Thanks for the help Jojo! I shall do it in the morning and it shall be my very first first open source contribution. Very exciting. The humble barline indeed...

**Comment by fhrw** [comment]
Apologies - I'm just setting up uncrustify currently.
