### ISSUE TITLE
Crash when deleting instruments in a certain order from a score with a certain list of instruments

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#17390]
1. Create score from the String Quartet template
2. Add Flute
3. Delete Flute (using Instruments panel)
4. Select the other instruments in the Instruments panel
5. Delete them
-> crash, related to brackets

Could happen in other situations too. This is just a reliable way to reproduce.

**Comment by DmitryArefiev** [comment]
Fixed in #17409

**Comment by Jojo-Schmitz** [comment]
I guess this is was a regression vs. 3.x?

**Comment by cbjeukendrup** [comment]
Yeah, in a way... if only because MS3 does not have the UI to reproduce it.
