### ISSUE TITLE
[Musicxml Export] - Instrument change still not exported

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#17397]
### Issue type

Other type of issue

### Steps to reproduce

When there's an instrument change with either or both long and short names, it must be displayed in Musicxml as part-name, part-abbreviation, or the other pair with display-text. Currently none is exported, only transposition (if have) is exported. This brings confusion in both importing and braille transcription.

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

All

**Comment by rettinghaus** [comment]
Here is the example encoding for MusicXML: https://www.w3.org/2021/06/musicxml40/musicxml-reference/examples/instrument-change-element/

**Comment by hhpmusic** [comment]
@rettinghaus @miiizen
  I tried the build under this fix, but the result is the same, no instrument changes are exported. Pleasee see this file.
[Stravinsky - Symphony of Psalms.zip](https://github.com/user-attachments/files/17742649/Stravinsky.-.Symphony.of.Psalms.zip)

**Comment by rettinghaus** [comment]
@hhpmusic I've investigated the score you provided, and as far as I can see there are no "real" instrument changes, i.e. things happening with instrument name changes within a staff. And all directions in there are not marked as a MuseScore instrument change or changing the actual instrument name of the staff.

**Comment by hhpmusic** [comment]
> @hhpmusic I've investigated the score you provided, and as far as I can see there are no "real" instrument changes, i.e. things happening with instrument name changes within a staff. And all directions in there are not marked as a MuseScore instrument change or changing the actual instrument name of the staff.

I agree, but they do change staff namess and abbreviations. In Finale and Sibelius, these are exported. So Musescore should also export it. Instrument change doesn't always mean changing from flute to piccolo, or from clarinet in A to in Bb. It also means changing from an instrument label to another. If they are not exported, when imported, their staff names will always be the initial ones. In braille, I have to manually insert these changes into Musicxml by first using a Python code to add many staff texts into the musescore file, and then mark the changes by finding these texts. This will increase working effort, and also will destroy some layout by adding unwanted system breaks when too many texts are added.


Haipeng

**Comment by hhpmusic** [comment]
@rettinghaus I checked the score again. These are real changes. For example, line 11771, it changes from flute 1 2 to flute 1. This should be marked. I tried another score with several changes. Some are exported, but most are not. These include those with either/both player number or/and instrument key changes. Therefore, the implementation is really incomplete.

**Comment by hhpmusic** [comment]
Here's that file. You can see some clarinets, horns and strings are exported, but most not.
[Szymanowski-LdM.zip](https://github.com/user-attachments/files/17788586/Szymanowski-LdM.zip)

**Comment by rettinghaus** [comment]
@hhpmusic Thanks for insisting on this topic. I went through the files you provided and came up with a better solution in #25615. Please try it.

**Comment by hhpmusic** [comment]
> @hhpmusic Thanks for insisting on this topic. I went through the files you provided and came up with a better solution in #25615. Please try it.

Thank you very much, but in that page I can't find the artifacts link after entering the check page (this is someone taught me before). How can I get the Windows build?

**Comment by rettinghaus** [comment]
Try this one https://github.com/musescore/MuseScore/actions/runs/11979801910

**Comment by hhpmusic** [comment]
Thank you very much, this time all work fine. An interesting thing in the file attached is the first change at bar 16, flauto I and II, which appears twice, at the beginning and middle of this bar. Why? This doesn't impact braille conversion, but I'm interested in the reason of the duplication.
[Uploading Szymanowski-litany.zip…]()
