### ISSUE TITLE
[Documentation] Broken "mtest/README.md" link on github page 

### ISSUE THREAD

**Issue by holly564** [musescore/MuseScore#17394]
Minor issue
Priority: 4

Problem: The "mtest/README.md" link inside https://github.com/musescore/MuseScore leads to a 404 error.

Steps To Reproduce:
 - From the root page of github/musescore at https://github.com/musescore/MuseScore,
move to the Testing section at the end of the page.
- Click on  "mtest/README.md" 

Expected Result: A README page

Actual Result:  404 Error Page

![image](https://user-images.githubusercontent.com/17574699/235228856-f71fda72-574c-4e26-b3e3-cc0a162cc496.png)

**Comment by Bohdanator** [comment]
Hello, I'm new to this repo and I would maybe like to contribute. I can't find the `mtest` directory, so I'm not sure where the link should be leading, maybe `test/README`?

**Comment by cbjeukendrup** [comment]
You could link to https://github.com/musescore/MuseScore/wiki/Unit-tests, which I've just created as a stub page, which will have to be filled with information. 

Also, the sentence "The new script testing facility...." is outdated too, so that can go away entirely.
