### ISSUE TITLE
Crash when deleting staff from instrument

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#17392]
### Issue type

Crash or freeze

### Bug description

When staff is added to instrument and than deleted, MU crashed. If there were at least two instruments.

### Steps to reproduce

1. score with two instruments
2. add staff to second instrument
3. remove staff from second isntrument
4. crash

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/1646034/235218629-3d566db0-f18a-44c8-a908-c34c0c75d5b2.mp4

### MuseScore Version

4.1 master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 22.04

### Additional context

may be related #17387

**Comment by cbjeukendrup** [comment]
It turns out that this will be fixed by #17409!

**Comment by DmitryArefiev** [comment]
Fixed in #17409
