### ISSUE TITLE
Insert measure before instrument change moves keysignature of instrument change

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#17391]
### Issue type

Engraving bug

### Bug description

If instrument change is in score, with keysignature change, and user inserts measure before that bar, key signature is moved into new bar.

### Steps to reproduce

1. score with transposing instrument change 
2. insert measure right before one with instrument change
3. see - keysig is moved

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/1646034/235216723-c0572b74-bc07-44a1-96eb-2958b1d9b1b7.mp4

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

Ubuntu 22.04

### Additional context

If user removes instrument change, keysig remains in score.

**Comment by oktophonie** [comment]
@sammik are you looking at this one yourself?

**Comment by sammik** [comment]
> @sammik are you looking at this one yourself?

OK, Ill give a try
