### ISSUE TITLE
MuseScore 4 repeatedly stops responding

### ISSUE THREAD

**Issue by Whiskey955** [musescore/MuseScore#17406]

**Comment by cbjeukendrup** [comment]
You'll need to give a bit more information if you want us to solve this. Under what circumstances does it happen? Does it happen completely randomly, or every time after a certain time interval, or when using some specific function?
Does it happen with specific files, or with any file? Or even when no file is opened at all?
For how long does it stop responding? Seconds? Minutes? Seemingly infinitely? 
Which operating system? 
For example, if you're on macOS, can you provide a spindump or call graph (using "Sample process") from the Activity Monitor app?
