### ISSUE TITLE
No Taiko Drum instrument in MuseScore

### ISSUE THREAD

**Issue by mccoydtromb** [musescore/MuseScore#17417]
### Issue type

Other type of issue

### Bug description

There is a Taiko Drum available in MuseSounds, therefore there should be a Taiko drum in MuseScore (this is why I have listed this as a bug and not a feature request).

### Steps to reproduce

1. Open a new score and choose instruments.
2. Search for Taiko
3. No results

### MuseScore Version

4.1.0

### Regression

No.

### Operating system

Windows 10

**Comment by s11141827** [comment]
I have the Taiko Drum sound in Musesounds but Taiko Drum isn't yet listed in musescore.
