### ISSUE TITLE
Less-restrictive horizontal lyric spacing

### ISSUE THREAD

**Issue by peteranglea** [musescore/MuseScore#17423]
### Your idea

Allow lyric syllables to observe tighter, less restrictive horizontal spacing. 
- Lyrics need not be confined to the boundaries of the measure in which they appear
- Lyric syllables can overlap the horizontal boundaries of syllables in other verses
- The above should be possible without have to manually place (uncheck "Auto-place") each offending syllable. At a minimum, lyrics should be able to be nudged (using left/right arrow keys) across a barline or across the horizontal confines of an adjacent syllable.

### Problem to be solved

Often, when engraving music with multiple verses/stanzas, syllables of varying widths in different stanzas present a horizontal spacing issue. First, the longest syllable in a given beat sets the boundary box for all the verses. Second, syllables are not allowed to escape the boundary of the measure in which they are placed. 

This generally results in wider spacing than desired since no "overlap" is allowed. This is particularly problematic when engraving hymns, as line width is often at a premium and there are often several verses.
<img width="645" alt="Screenshot 2023-04-30 at 8 41 45 PM" src="https://user-images.githubusercontent.com/1030909/235386682-5a1d77d0-0004-43a1-a64d-3608366f71dc.png">

Here is an approximation of what a better solution might look like. The basic idea is that syllables can "overlap" and not have such a rigidly defined outer boundary.
<img width="594" alt="Screenshot 2023-04-30 at 8 42 09 PM" src="https://user-images.githubusercontent.com/1030909/235386925-fe1cb5df-fe70-49ac-b7a7-106b7fc1711a.png">

### Prior art

I have engraved well over 100 hymns in Lilypond and, whereas their lyric spacing algorithm isn't perfect either, it does observe more intelligent horizontal spacing by default. At a minimum, the measure boundaries do not interfere (see the syllable "mount")
<img width="174" alt="Screenshot 2023-04-30 at 9 16 53 PM" src="https://user-images.githubusercontent.com/1030909/235387251-b0ebc857-c663-46bd-8dad-2d9527d35ae0.png">

MuseScore here doesn't let a syllable escape the measure.
<img width="145" alt="Screenshot 2023-04-30 at 9 17 18 PM" src="https://user-images.githubusercontent.com/1030909/235387348-2a5e6fac-26f7-4435-b83f-0879a29852e3.png">

### Additional context

Related bug report here on musescore.com. https://musescore.org/en/node/338887

**Comment by oktophonie** [comment]
Oh, it's very much on the radar, don't worry!
The fact that the lyrics can't by default extend outside the confines of the bar is a unfortunate legacy of how this system was designed some time ago. We'll rip it out and fix it.

**Comment by peteranglea** [comment]
Awesome! Is there a roadmap I could follow along with (simply out of curiosity)?

**Comment by RobFog** [comment]
4.4 or 4.5?

**Comment by cbjeukendrup** [comment]
Part one was done in 4.4, part two was merged just now for 4.5
