### ISSUE TITLE
[Musicxml Export] - Better and real Musicxml 4 support for system texts and lines

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#17431]
### Issue type

Other type of issue

### Steps to reproduce

Currently all system texts and lines are still exported as common directions. In Musicxml 4.0, they must have system properties, e.g., directive="yes", and only-top or (in other parts) also-top (Musescore currently doesn't have this kind of text yet). For footnotes, they must have only-bottom property.

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

All

**Comment by rettinghaus** [comment]
They must not. According to reference all these attributes are not required. Also some examples would be helpful.

**Comment by hhpmusic** [comment]
For example, this example, all texts and lines should in system="yes" format. Other attributes are not forced, but system="yes" is the must one.
[system objects.zip](https://github.com/musescore/MuseScore/files/12671326/system.objects.zip)
