### ISSUE TITLE
Major performance issues

### ISSUE THREAD

**Issue by Whiskey955** [musescore/MuseScore#17435]
Compared to MuseScore 3 it is a major performance decrease.

**Comment by Jojo-Schmitz** [comment]
Where and when exactly?

**Comment by oktophonie** [comment]
Closing as impossibly vague.

**Comment by Whiskey955** [comment]
You gave me 2 hours to respond

**Comment by shoogle** [comment]
@Whiskey955, issues can be reopened if necessary, but in this case we'd appreciate it if you create a new one based on the templates we have provided at https://github.com/musescore/MuseScore/issues/new/choose

![image](https://user-images.githubusercontent.com/11011881/235764457-4f6934fd-4974-4e63-a0d9-b7d0c89b821b.png)
