### ISSUE TITLE
Mixer does not open

### ISSUE THREAD

**Issue by gassug3** [musescore/MuseScore#17438]
### Issue type

UI bug

### Bug description

Opening the Mixer via the hotkey (F10), the button in the top center, or under the "View" context menu does not open the Mixer.

### Steps to reproduce

1. Open musescore
2. Attempt to open the mixer by any of the listed means
3. Notice that the mixer does not open

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/46363352/235623485-4a5206b8-454e-4c38-abc9-c182e5a457b1.mp4

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Arch Linux (x86_64)

### Additional context

Diagnostic files: [musescore.zip](https://github.com/musescore/MuseScore/files/11371844/musescore.zip)

**Comment by gassug3** [comment]
Updated to include diagnostic files under "additional context"

**Comment by MarcSabatella** [comment]
Could also be opening offscreen, like if the display resolution changed since last time the mixer was opened.  Try View / Restore the default layout, and if that doesn’t work, Help / Revert to factory settings.

**Comment by cbjeukendrup** [comment]
Or "View" > "Restore the default layout" might help, if you don't want to lose all your settings

**Comment by gassug3** [comment]
> The logs do not show any issues. Make sure that the mixer is not opening on another monitor or behind the main window (which is also a bug).



>  The logs do not show any issues. Make sure that the mixer is not opening on another monitor or behind the main window (which is also a bug). 

> Could also be opening offscreen, like if the display resolution changed since last time the mixer was opened. Try View / Restore the default layout, and if that doesn’t work, Help / Revert to factory settings.

I have recently set up my second monitor roughly 2 weeks ago, and have only used Musescore periodically since then.

The Mixer does not open behind the main window, checking behind the window shows nothing, and attempting to open the Mixer again by any of the listed means does not do anything.

Mixer does not appear on second monitor. Restoring to default layout and restoring to factory settings do not fix the issue. The mixer does not appear nor do any of the listed means work to make it appear.

I have reinstalled Musescore to test, and the issue persists. I'll check to see if any of the alternative packages have this issue.

**Comment by cornelisbb** [comment]
Same bug is reported for openSUSE Tumbleweed:

https://bugzilla.suse.com/show_bug.cgi?id=1210980

Can this be related to fix for qt-declarative that both arch and Tumbleweed have included as fix for issue #17276 ?

**Comment by cornelisbb** [comment]
In openSUSE Tumbleweed the bug is fixed by updating qt-declarative to a version that reverts the change causing this bug:

https://invent.kde.org/qt/qt/qtdeclarative/-/commit/2f14549ee64782e9d64257696b10c6d59e884a7d
