### ISSUE TITLE
MuseScore 4.0.2 won't start 

### ISSUE THREAD

**Issue by SteppenHerring** [musescore/MuseScore#17454]
I realise that there have been a bunch of these. So here's one more. 

Setup: Win 10 build 19044.2846. Intel 6800K. 64GB RAM. Lots of drives (NVME, SSD and HDD). Audio: Focusrite Scarlett 18i20 (2nd gen, USB). MuseScore splash screen then the process dies. Killing any process starting with "Muse" does not help.

If I change to a different audio output, MS4 starts and runs fine. I can't listen to the output though.

If I start MS4 and then change to the Focusrite, it hangs for a bit, then dies. The Focusrite is my only audio option that is connected to anything I can listen to.

Things tried:

- Rebooting
- Uninstall and reinstall
- Reinstall standalone MuseScore 4
- Uninstall all sounds
- Drinking
- Swearing

**Comment by oktophonie** [comment]
@cbjeukendrup does this sound the same as https://github.com/musescore/MuseScore/issues/15235 to you?

**Comment by cbjeukendrup** [comment]
Yes, most likely it is the same. So let's close this as a duplicate for now, but let's check it again when we find a solution for #15235.
