### ISSUE TITLE
Space between "C" and "y" in Cymbal instrument name

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#17473]
### Issue type

Other type of issue

### Bug description

In the mixer and the add instruments window/panel there is a visual space between the letter "C" and the letter "y"

### Steps to reproduce

1. Make a new score
2. Search for "Cymbal"

Both Cymbal and Cymbals have the space.  It also appears this way in the mixer and the side panel.

### Screenshots/Screen recordings

<img width="959" alt="Screen Shot 2023-05-04 at 2 41 36 PM" src="https://user-images.githubusercontent.com/69917893/236334314-92abf03e-09f0-4c5f-b0b0-1e79ed5005c0.png">

### MuseScore Version

4.0.2-230651546

### Regression

No.

### Operating system

macOS11.7.6

**Comment by cbjeukendrup** [comment]
I think this is a font rendering issue, related to #16533. That means that it would be solved when we switch to Qt 5.15.8 (we have 5.15.2 now). Indeed, I can reproduce the issue in 4.0.2 builds, but in my local development builds, for which I use Qt 5.15.8, it looks much better: 
<img width="1136" alt="Scherm­afbeelding 2023-05-04 om 23 39 16" src="https://user-images.githubusercontent.com/48658420/236335752-153ec299-f0cf-4722-9425-7e96668fd0f2.png">
