### ISSUE TITLE
[MU4 Issue] Slured notes on the TAB staff are rendered wrong when slur goes over to next line

### ISSUE THREAD

**Issue by alexpavlov96** [musescore/MuseScore#17502]
<img width="442" alt="Screenshot 2023-05-08 at 20 51 59" src="https://user-images.githubusercontent.com/24373905/236895090-b5e0c8b4-f04f-49e2-84a5-50b7353591c3.png">

compare tab notes with ties and with slurs:
[archive.zip](https://github.com/musescore/MuseScore/files/11423764/archive.zip)

Issue is also reproducible when inserting notes and slurs.

**Comment by bkunda** [comment]
@oktophonie is this potentially related to the other issue regarding ties and visibility?

**Comment by Jojo-Schmitz** [comment]
As far as I can tell this doern't happen in 4.0.2 (nor in 3.x), so is a regression
