### ISSUE TITLE
Aux channel name doesn't update after changing plugin in Mixer

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17514]
### Issue type

VST bug

### Steps to reproduce

1. Change effect in Aux channel - **channel name doesn't change** (you should close and reopen score )

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/c86e5b3f-7be9-4b6c-afb9-4fac90ca91ae

### MuseScore Version

4.1

### Regression

No.

### Operating system

Windows10

**Comment by RobFog** [comment]
Should this issue be moved to the MuseScore 4.1.1 milestone seen as the fixes were ported in #18802?
