### ISSUE TITLE
Changes in page settings are no longer reflected in real time in the score 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#17511]
### Issue type

Other type of issue

### Bug description

Changing values in the spin boxes in the page settings dialog used to reflect changes to the score in real time (4.0.2). In the latest nightly, changes are no longer reflected as the user effects them; instead, the user has to select a different property (spin box) to see the updated value reflected in the score. 

### Steps to reproduce

1. Create a new score
2. Format > Page settings
3. Use the spin box for "Scaling" to adjust the stave space. Notice how nothing appears to happen in the score
4. Select either of the spin box input fields in "Page size". Notice how the score adjusts to reflect the current stave space value

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/86290556/851aa8d1-7510-4030-a68d-c03d1caab824

### Expected behaviour

- Clicking the spin box arrows should have a different behaviour to changing the value of the text input field: I.e. spin box arrows should function as per v.4.0.2, i.e. with immediate update to the score.
- Changing the value of the text input field can operate as per current master (i.e. no immediate update to score), however pressing `Enter` should update the layout, _not_ close the dialog.
- It would be helpful (bonus points) if the layout updated when clicking _anywhere_ outside of the text input field (i.e. not only selecting a different field, but also clicking on another part of the dialog UI).

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231290303, revision: github-musescore-musescore-5fc30ff

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 13.1

**Comment by bkunda** [comment]
Relates to https://github.com/musescore/MuseScore/issues/17160 (now closed)

**Comment by oktophonie** [comment]
This was a deliberate change, since causing the score to update in real time was immensely slow (could take seconds for each update). See: https://github.com/musescore/MuseScore/pull/15107

**Comment by HemantAntony** [comment]
@bkunda I made a PR: #18244 :)
