### ISSUE TITLE
Crash if two voices, and the all the notes in first voice moved to upper staff

### ISSUE THREAD

**Issue by lordlouckster** [musescore/MuseScore#17522]
### Issue type

Crash or freeze

### Steps to reproduce

1. Open https://cdn.discordapp.com/attachments/818804809784229898/1104313766339952720/634.mscz
2. Move the note marked in blue to the upper staff.
![MuseScore4_KwqwrwFcHt](https://github.com/musescore/MuseScore/assets/57062013/22c4fe00-4a57-4e2e-93c7-7d064c262d88)
3. Weird things happen. Now undo.
4. Crash.

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

Windows 10 64-bit

**Comment by oktophonie** [comment]
Good news: I can reproduce this in 4.0.2, but not in master - so it looks like this has been fixed already.
