### ISSUE TITLE
Scroll bar end-of-travel out of sync with page boundaries

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#17529]
### Issue type

UI bug

### Bug description

When you use the vertical or horizontal scroll bars there is some anomalous behaviour:

1. The end of travel of the scroll bar does not coincide with the page boundaries but seems to overshoot into the blank area of the MS4 desktop.
2. When the scroll bar reaches the end of its travel it starts to compress, as if elastic. As it does so the score continues to scroll. If you reverse the direction the scroll bar springs back to full length again.

Expected behaviour is that scroll bar end-of-travel should coincide with the page boundaries. And scroll bar length should be constant.

### Steps to reproduce

See screencast below.

### Screenshots/Screen recordings

![scrollbars](https://github.com/musescore/MuseScore/assets/87246583/602ec22c-0b58-4144-ab43-a000b1e97dd1)

The behaviour of the vertical scrollbar is similar.

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d

### Regression

N/A

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by cbjeukendrup** [comment]
As far as I know, that is not a bug but a feature. The idea is that you can push them beyond the border to scroll into the margin, just like you can do by dragging the score view or scrolling using the mouse.

@jessjwilliamson is that correct? (You designed the scroll bars, right?)

**Comment by Eism** [comment]
This is a cool feature that I love in MuseScore

**Comment by jessjwilliamson** [comment]
I designed the look of the scrollbars but I didn't design the behaviour.

**Comment by bkunda** [comment]
This behaviour is by design.
