### ISSUE TITLE
Wrong notes rendered after the tab transposition (Cant Help Falling In Love - Elvis)

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#17530]
### Issue type

Other type of issue

### Bug description

[Elvis Presley - Cant Help Falling In Love (ver 16 by savchenkoroman94).gpx.zip](https://github.com/musescore/MuseScore/files/11452521/Elvis.Presley.-.Cant.Help.Falling.In.Love.ver.16.by.savchenkoroman94.gpx.zip)

### Steps to reproduce

1. Open the tab
2. Apply transposition to the score on major third or to E major key (which is the same)
3. Pay attention to notes changes (e.g. measure 5 in ac guitar. Same notes are rendered)

At the same time there's no an issue if you transpose to 1 semitone

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/101250347/decadaa9-21c0-4f59-8ad1-bbd0ff1c8120

### MuseScore Version

MuseScore 4.0.2 

### Regression

No.

### Operating system

macOS 13

**Comment by Jojo-Schmitz** [comment]
Transposing chord symbols crash, not sure how/whether that relaes to this issue or got introduced via #17531

**Comment by Jojo-Schmitz** [comment]
Seems this is the needed chan ge to fix the crash:
```cpp
@@ -382,6 +384,8 @@ bool Score::transpose(TransposeMode mode, TransposeDirection direction, Key trKe
            }

      Segment* s1 = _selection.startSegment();
      if (!s1)
            return result;
      // if range start on mmRest, get the actual segment instead
      if (s1->measure()->isMMRest())
            s1 = tick2segment(s1->tick(), true, s1->segmentType(), false);
```
Fixes the crash and still does nothing on trying to transpose a (single) chord symbol

**Comment by mikekirin** [comment]
@Jojo-Schmitz You can't transpose chord symbol^ because it is just text. This is how it imported from gp file. Working on that.

**Comment by Jojo-Schmitz** [comment]
Jyes, that's OK, but it shouldn't crash on the attempt either ;-)

**Comment by Jojo-Schmitz** [comment]
Please check my #17588

**Comment by mikekirin** [comment]
I mean that the reason of the crash, you're right, but even before this PR you weren't be able to transpose chord symbol if you're importing the gp file. That's what I mean

**Comment by Jojo-Schmitz** [comment]
They are, but not in a list selection. Not even a simple "A". Works only in range-selection. Then even a Bmaj7/G works.

**Comment by bkunda** [comment]
This issue should be closed pending successful merging of #17588

**Comment by Jojo-Schmitz** [comment]
Up to @abariska I guess, as he reopened it but without giving the reason?

**Comment by abariska** [comment]
Two separate issues created for chord symbol transposition issues
https://github.com/musescore/MuseScore/issues/17637
https://github.com/musescore/MuseScore/issues/17638
