### ISSUE TITLE
Message user when attempting to delete initial key signature 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#17542]
### Your idea

Per https://github.com/musescore/MuseScore/pull/15503 it was resolved to disable deletion of the first key signature. This task ensures the user is appropriately messaged when attempting to do so to avoid likely confusion. 

### Problem to be solved

As above

### Prior art

<img width="485" alt="key-sig" src="https://github.com/musescore/MuseScore/assets/86290556/15fb59fb-ae0e-4b62-98a7-e9e215cbf9ce">

### Additional context

Marking as a priority to ensure it gets done for 4.1 – this really completes the feature implemented as part of #15503.

**Comment by iwoithe** [comment]
Working on it.

**Comment by sammik** [comment]
Wouldn't be better, instead of warning message, replace deleted key signature(s) by C major key signature?

I think, it is, what user wants, if deleting initial key signature - to became C major.
