### ISSUE TITLE
Adjust hyphens/extensions when changing note values

### ISSUE THREAD

**Issue by jonarnoldmusic** [musescore/MuseScore#17548]
### Your idea

I noticed that _sometimes_ lyric syllable alignment changes when note values change. For example, if you have two quarter notes where the second is only a hyphen
![image](https://github.com/musescore/MuseScore/assets/11447289/bd638aac-8cc5-4335-852d-6e1d367528ed) 
and you change those to a single half note, the syllable returns to center alignment. 
![image](https://github.com/musescore/MuseScore/assets/11447289/05be191e-fffc-4e51-a7bd-358a02f4d7fa)
However, even if the notes that follow have new syllables, the hyphen remains. 

Ideally, Musescore should be able to recognize that there are no notes in between those explicit syllables and therefore the hyphen is erroneous and should be discarded. The same should apply to word extensions.

### Problem to be solved

This would enable the user to change note values and have the lyrics respond more intelligently.

**Comment by jonarnoldmusic** [comment]
I wonder if it's possible that this principle work in reverse: if you make the half note two quarter notes, Musescore would look ahead to the third beat to see whether it is a hyphen or a new syllable. If a new syllable, it would add a lyric extender on the 2nd note; if not, it would add a hyphen.

**Comment by oktophonie** [comment]
A hyphen needs to remain between syllables even if there are no intervening notes.
Melisma lines (underscore) should behave the way you describe, and this should have already been fixed (https://github.com/musescore/MuseScore/issues/15093) but apparently isn't - or has become unfixed. Will look into it.

**Comment by jonarnoldmusic** [comment]
Oh yes, my thinking about the hyphen was definitely wrong, sorry. 

Indeed, melisma lines do not respond to the value, at least in 4.0.2-230651553:
![image](https://github.com/musescore/MuseScore/assets/11447289/9ea1194e-2320-490e-9e8d-f18ac93fb01c)

**Comment by jonarnoldmusic** [comment]
I'm not sure if this is related, but I noticed today that if a note previously had a melisma under it and you then go and type a syllable, the line is not erased.
![image](https://github.com/musescore/MuseScore/assets/11447289/fc268212-0543-46f3-b093-c76750dc8892)
