### ISSUE TITLE
Measure (bar) numbers disappear

### ISSUE THREAD

**Issue by composerdean** [musescore/MuseScore#17546]
### Issue type

Engraving bug

### Bug description

I imported a rather long composition with many staves from MuseScore 3 to MuseScore 4 .  Initially everything looked fine.  As I was editing the score, I needed to adjust the bar numbers.  After doing so, they disappeared and I cannot find a way to make them reappear even when restoring them to default.  Score can be found at:  https://musescore.com/user/35676498/scores/10832878

### Steps to reproduce

Go to Properties
Then Style Settings
Then Measure Numbers
You will note that in the composition no measure numbers appear.  Changing the settings results in no changes in the score.

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
All the measures (at least all the ones I checked) are set to "always hide" measure numbers in the measure properties.  So the score is honoring that.

I assume you didn't manually go into to every measure and change this and then forget about it :-), so it's possible there is a bug that somehow set that property on every measure...

**Comment by composerdean** [comment]
Thank you.  You're correct in that I didn't do that in every measure. 
 I reported the bug in GitHub.

Dean Hamill
385-309-9095

On 5/12/2023 at 3:57 PM, "Marc Sabatella"  wrote:
	All the measures (at least all the ones I checked) are set to "always
hide" measure numbers in the measure properties.  So the score is
honoring that. 

	I assume you didn't manually go into to every measure and change this
and then forget about it :-), so it's possible there is a bug that
somehow set that property on every measure...

**Comment by zacjansheski** [comment]
The link to the original score does not work.  Closing unless there is more information.
