### ISSUE TITLE
creating a half note always has a tremolo stem

### ISSUE THREAD

**Issue by a3emdot** [musescore/MuseScore#17554]
### Issue type

Engraving bug

### Bug description

I have a small measure set up using guitar tabs,
if i want to add an additional half note I always get a tremolo stem.
The attached text file is indeed a mscx file. I had problems attaching a mscz file

[test2.txt](https://github.com/musescore/MuseScore/files/11472061/test2.txt)

### Steps to reproduce

try to add a half note using the attached mscz aka mscx aka txt file

### Screenshots/Screen recordings

![Screenshot_2023-05-14_15-29-43](https://github.com/musescore/MuseScore/assets/124900167/0a2f94c4-dbd2-45fd-a8c3-6689d8766ba1)

### MuseScore Version

3.6.2

### Regression

I don't know

### Operating system

Fedora 37

**Comment by MarcSabatella** [comment]
This is by design currently - it’s one of the several options provided for how half notes are notated in tab.  It’s definitely an open question as to whether it should be the default though.  Anyhow, you can change the style in staff/part properties or by switching to a different tab style entirely in the instruments panel.

**Comment by a3emdot** [comment]
I didn't know about that.
But I wonder why it is different, when I open an empty new sheet with guitar tabs. No tremolo stem.
Was there a change in behavior in the near past?
Anyway thank you for sorting this out for me.

**Comment by MarcSabatella** [comment]
No, it just depends on how the score was created and which options were used when adding the tab staff.  For whatever reason, the templates use different defaults than when adding the instrument directly.
