### ISSUE TITLE
Play Panel measure count is inconsistently wrong

### ISSUE THREAD

**Issue by chunga2020** [musescore/MuseScore#17562]
### Issue type

UI bug

### Bug description

Sometimes while playing a score, the measure counter disrespects the score's time signature, leading to, _e.g._, a count of 7 beats in a measure of 4/4.

### Steps to reproduce

1. Open a score
2. Play the score, paying attention to the measure counter
3. Close and reopen MU4 as needed until the bug occurs. 

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11, Linux (Arch, native package)

**Comment by cbjeukendrup** [comment]
This looks quite similar to https://github.com/musescore/MuseScore/issues/17003. Could you please try if it is resolved in the latest nightly build? https://musescore.org/en/nightly-builds

**Comment by chunga2020** [comment]
@cbjeukendrup Seems to be resolved in the latest nightly.

**Comment by cbjeukendrup** [comment]
Great, thanks for checking!
