### ISSUE TITLE
UI text bug in Fretboard Diagram in Properties

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#17566]
### Issue type

UI bug

### Bug description

The text "You have multiple fretboard diagrams selected. Select a single diagram to edit its settings" is accidentally overlapping on the Settings tab in Properties, when selecting multiple fretboard diagrams at once. This message is supposed to only be in the General tab, but somehow managed to get itself placed on the Settings tabs.

### Steps to reproduce

1. Create 2 fretboard diagrams on a score
2. Select both at the same time
3. Open Properties where you see Fretboard Diagram options show
4. Select Settings tab
5. See issue

### Screenshots/Screen recordings

<img width="388" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/6e262f86-d4dc-4df2-a41b-57522a7ab9e7">

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

MacOS

### Additional context

Correct designs:
<img width="608" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/d7f803f7-9804-423b-a1ff-c3e36accf139">

**Comment by bkunda** [comment]
@HemantAntony, if you have time and are interested, perhaps you'd like to check this out? (We'd be very grateful!)

**Comment by HemantAntony** [comment]
@jessjwilliamson @bkunda - I made a PR: #17617 :)
