### ISSUE TITLE
Minor fixes for harp pedalling widget

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#17565]
### Issue type

UI bug

### Bug description

There are a few issues that should be addressed to polish-up the [recently implemented/merged harp pedal diagram feature](https://github.com/musescore/MuseScore/pull/12597):

#### Widget placement
The popup widget should always appear **above** the selected diagram (while also clearing the stave, as it currently does), _unless_ there is insufficient room at the top of the user's screen, in which case it should appear below the stave. 

In effect, this means the widget should be allowed to overlap the upper UI (note input toolbar, etc.), like so:

<img width="1054" alt="Screenshot 2023-05-15 at 2 48 31 pm" src="https://github.com/musescore/MuseScore/assets/86290556/cd4542cf-64d0-4c73-9e33-9dfaa064ef5c">

#### Key commands
These common key commands don't work on a selected harp pedal diagram:
- Delete (only works after scrolling the score to a different position)
- Copy/Paste (doesn't work at all)

https://github.com/musescore/MuseScore/assets/86290556/56201d79-dcf2-4812-a58b-a383001bae2d

In addition, the undo command reverts changes made to the diagram, but doesn't effect any visible change to the popup widget itself (the widget has to be closed and re-opened for the changes to appear).

https://github.com/musescore/MuseScore/assets/86290556/3514162d-bf81-409c-805d-834f2b54377c

_Expected behaviour_
It should be possible to **delete**, **copy/paste** harp pedal diagrams to different notes/rests.
It should also be possible to see the radio buttons within the UI of the widget itself revert to previous positions when the **undo** command is used 

 

### Steps to reproduce

See above videos

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231350302, revision: github-musescore-musescore-494477a

### Regression

No.

### Operating system

macOS 13.1

### Additional context

@miiizen @Tantacrul FYI
Assigning P1 because this needs to be fixed in order to properly complete implementation of this feature

**Comment by miiizen** [comment]
Hi - I'm available to help out with this again if needed!
I tried sorting out the copy/paste/delete issue but wasn't sure of the best way around this, perhaps would be quicker if @Eism has time to look or if not point me in the right direction.

**Comment by Eism** [comment]
@miiizen I just fixed most of the issues, but yes, there are problems with the copy/paste/delete issue, I'm working on it now.

**Comment by DmitryArefiev** [comment]
Fixed in #17583
