### ISSUE TITLE
Musescore 4.0 made my song unplayable

### ISSUE THREAD

**Issue by fsgregs** [musescore/MuseScore#17586]
### Issue type

General playback bug

### Bug description

I am an experienced user of MS 3.6, with over 60 scores now posted on the website.  I reluctantly tried MS 4.0 yesterday, knowing that it still has key bugs.  I launched MS4 and imported a MS 3.6 score into it.  In trying to use it, I encountered at least 14 bugs which I will post in this forum as needed, but I struggled through for a while.

The key bug is what happened when I closed the converted MS4 score, then reopened it later. I discovered ALL of the notes in the entire score had now become muted, with the "M" button at the bottom of the Mixer menu dimmed out.  None of the notes would play and try as I might, I could not get it working.  I installed a new instrument (violins) and assigned MuseSounds Violins1 to it, then copied and pasted all the notes from my existing violins track into it.  No good!  All those notes remained muted with the Mixer "M" button dimmed out.

### Steps to reproduce

Just open the score.  Then open the Mixer menu.  All the Mute buttons are dimmed out and none of the notes in the score will play, even if I cut and paste them into a new instrument.

A screenshot of the Mixer menu are attached 

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/133777637/a597be10-acc9-4499-8427-f9b7d7a61419)

The offending file is attached as a zip file:

[The Dark Knight Theme MS4.zip](https://github.com/musescore/MuseScore/files/11488551/The.Dark.Knight.Theme.MS4.zip)

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by oktophonie** [comment]
To attach a file here, either put it into a .zip, or just rename it from .mscz to .zip.

**Comment by MarcSabatella** [comment]
This is simply becasue you have soloed the timpani track.  Press the "S" to unsolo it, and the other instruments are unmuted.  That's not a bug, it's how soloing works.

**Comment by fsgregs** [comment]
Marc:  Oh for pete's sake.  I knew that but failed to notice it.  Thanks.  So sorry for making it a bug.  This item closed.
