### ISSUE TITLE
[FEATURE] Where necessary, some palette items need to be force-reset in version 4.1

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#17581]
### Your idea

In version 4.1, the "Expression" item has a new dedicated type (see #17001) and soon the "Ornament" item will have a new dedicated type (see #17515). However, palette elements, if not reset, will read from the locally saved palette file, so they will keep using the "old" types. This causes the new features to not work properly, and also crashes.

It is necessary to force the reset of some selected palette items when converting from Musescore 4.0 to Musescore 4.1. These are:
- The "expression" item in the "Text" palette (see https://github.com/musescore/MuseScore/blob/master/src/palette/internal/palettecreator.cpp#LL1545C66-L1545C66) 
<img width="423" alt="image" src="https://github.com/musescore/MuseScore/assets/93707756/cbb9bd4b-f938-42e0-aa67-fe29422066ed">

- The articulation-based items in the "Ornaments" palette (see https://github.com/musescore/MuseScore/blob/master/src/palette/internal/palettecreator.cpp#L825)
<img width="406" alt="image" src="https://github.com/musescore/MuseScore/assets/93707756/1367a602-95cb-458f-98dc-aff5780b7242">

### Problem to be solved

See above description

**Comment by DmitryArefiev** [comment]
Implemented in #17633
