### ISSUE TITLE
Certain tags are not visible in project properties

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#17598]
### Issue type

UI bug

### Bug description

When certain tags are used in the project-property dialog, they disappear when the dialog is re-opened to access/update the value.

The tags concerned are tags which were available in MS3 but have not been added to the default MS4 GUI.

Tags I tested are:

movementTitle
movementNumber
workNumber

### Steps to reproduce

Start a new score
Open project-properties
Add a new tag: movementTitle
Enter a value for the tag: TEST
Click OK
Re-open project-properties
The tag/value which was just created does not appear.

Open Format->Style->Header-Footer
Click in one of the textboxes and keep the mouse still
Tooltip should appear and shows the movementTitle exists and has a value.

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by bkunda** [comment]
I think we need more info about this one. What function do these tags actually perform? Are these tags critical? 
FWIW we have broad plans to properly support the concept of different "movements" in future, so I suspect that might have been why these particular tags were removed (@Tantacrul might know more about this).

**Comment by Jojo-Schmitz** [comment]
It is a compatibility issue (too) those tags did exist in Mu3 and now are no longer visible/available

**Comment by Jojo-Schmitz** [comment]
And a UI/UX issue, you add a tag and it doesn't show, without any indication why, just because you picked a 'reserved' name

**Comment by henkdegroot** [comment]
> What function do these tags actually perform? Are these tags critical?

To my knowledge there is no functionality associated to these tags. People are just using them to have an easy method in score to set some values. As the tags exists in MS3, some users will be using them. 
It just is silly that when you manually add a tag with a certain name, that when you go back into the same dialog to edit it, it no longer appears. While if you are just using a tag name which did not exist in MS3, they remain in place and can be editted.

I would not suggest to re-add the "missing" tags, but only show them when a value is set to the tag (either by migrating from MS3 of by manually creating them).

**Comment by cbjeukendrup** [comment]
This was indeed just a small bug ("small" in the sense of complicatedness). Whether they have a special function or not, and whether we consider them standard tags or not, they should not disappear when they were there or when the user adds a tag that happens to use that name. A fix is in #17615.
