### ISSUE TITLE
Crash if you save a template in continuous view

### ISSUE THREAD

**Issue by divitoau** [musescore/MuseScore#17596]
### Issue type

Crash or freeze

### Bug description

If you create a template and save it into your template folder while it is in continuous view (in the hopes that the template will already be in continuous view whenever you create a score with it), musescore will crash immediately when you click "my templates" in the "create from template" menu in the "new score" window

### Steps to reproduce

1.  create a new score with any instrumentation
2. switch to continuous view
3. save the score in the "templates" folder
4. quit musescore
5. open musescore
6. create a new score
7. click "my templates"

### MuseScore Version

OS: macOS 13.3, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231360302, revision: github-musescore-musescore-24a7f7b

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macos 13.3.1

### Additional context

Apple M2 chip,
16 GB memory

**Comment by zacjansheski** [comment]
If the first score is not continuous view, "My Templates" does open, but if you select a score with continuous view the program crashes.

This leads me to believe this has to do with the rendering of the preview

Recreated:
OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231370302, revision: github-musescore-musescore-fc44a51

**Comment by bkunda** [comment]
Yeah this is really bad, because it's not just opening the specific template score that causes the crash – it actually inhibits the opening of _any_ template score. 
I agree with you @zacjansheski that this is a P0.

**Comment by L0uisc** [comment]
I could reproduce the bug on 19 May's master on Windows 10. The crash occurs [here](https://github.com/musescore/MuseScore/blob/master/src/notation/view/continuouspanel.cpp#L465) due to `m_notation` being null. I don't know why it's null yet.

**Comment by cbjeukendrup** [comment]
I think that is because the only place where `ContinuousPanel::setNotation` is called is in `AbstractNotationPaintView::onCurrentNotationChanged`, which is (correctly) not called for TemplatePaintView, because TemplatePaintView completely overrides `AbstractNotationPaintView::onNotationSetup()`.

**Comment by L0uisc** [comment]
Makes sense. The other option I thought about was making template score previews always render in page view. The size and dimensions of the preview is page-like.

**Comment by cbjeukendrup** [comment]
That might be a good idea anyway, but it would make sense to me to fix this crash too, because otherwise it might re-surface in a different way in the future.

**Comment by L0uisc** [comment]
I moved the `setNotation()` calls on members from `AbstractNotationPaintView::onCurrentNotationChanged()` to `AbstractNotationPaintView::setNotation()` and called `setNotation()` from `AbstractNotationPaintView::onCurrentNotationChanged()`. It fixes the crash, but now, when opening a score with part scores, switching from a part to another and back changes the zoom level in the first part to 375%. This is not the case on current master, so my change caused the issue. I suspect it has something to do with the matrix changing earlier or later now, though I'm not 100% sure.
