### ISSUE TITLE
Crash when adding chord symbol

### ISSUE THREAD

**Issue by ThaBaer** [musescore/MuseScore#17590]
### Issue type

Crash or freeze

### Bug description

MuseScore freezes for a couple of seconds and exits when adding a chord symbol.

The crash happens when the symbol is rendered. Typing, backspacing and fully deleting does not trigger the crash.
Also it only happens on the last two bars of the score in question.

### Steps to reproduce

1. Open attached score
2. Go to the first note of the last bar
3. Add a chord symbol (ctrl-k)  like "C7"
4. Exit the editor by clicking anywhere else

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009, Arch.: x86_64

### Additional context

[MS-Diag.zip](https://github.com/musescore/MuseScore/files/11488846/MS-Diag.zip)
[Don't Get Around Much Any More.zip](https://github.com/musescore/MuseScore/files/11488850/Don.t.Get.Around.Much.Any.More.zip)

**Comment by zacjansheski** [comment]
Hello!

Could you please provide more context to help us diagnose the issue?  Could you provide details on your mixer/VST settings?

**Comment by MarcSabatella** [comment]
FWIW, I can reproduce in 4.0.2 using just defaults, but not on current master.  Oddly, I *thought* I tested this yesterday on master and still saw the crash, but I don't see it now even using a variety of older master builds.

**Comment by zacjansheski** [comment]
I was able to replicate
Windows 11 , Ver. 4.0.2
I was unable to replicate in OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231391516, revision: github-musescore-musescore-ca2e8d8

I will close this issue
