### ISSUE TITLE
White Pages PDF Export

### ISSUE THREAD

**Issue by RrOoSsSsOo** [musescore/MuseScore#17608]
### Issue type

Other type of issue

### Bug description

MuseScore 4 (4.0, 4.0.1 and 4.0.2) exports the pages following the one that contains this fragment as blank/white.
Score was originally created with MuseScore 3.x, [WhitePageExport.mscz.zip](https://github.com/musescore/MuseScore/files/11499468/WhitePageExport.mscz.zip) attached.

![image](https://github.com/musescore/MuseScore/assets/1734343/78e931ee-2d6d-4c80-80c1-a8802e7b3051)

Other strange thing is that the probel affects also "zoom level":

- At 80-100% pages 2-3 are shown
![image](https://github.com/musescore/MuseScore/assets/1734343/065f436c-1864-43f4-85d3-42febbad44d4)

- At 10-50% only first is shown (2-3 desappear)
![image](https://github.com/musescore/MuseScore/assets/1734343/e44d7928-dc27-4f94-bbf2-8fe8da7c7d67)

### Steps to reproduce

1. Open the example file attached
2. Export in PDF

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows, Linux

**Comment by MarcSabatella** [comment]
FWIW, there have been several forum reports of this.  I can reproduce in 4.0.2 but not current master, so I'd like to consider it fixed, but I'd also like to understand where it comes from and if there is a workaround for now.

A curious secondary effect in 4.0.2 - all pages but the first disappear on screen if you zoom out then reappear when you zoom in.  That makes it easier to experiemnt to see what is going on.  I find deleting the first triplet makes the issue go away.  This is a ncie simple example; the others in the forum were more complex.

**Comment by RrOoSsSsOo** [comment]
I confirm that on master >= 961dbaa PDF and Zoom are fixed.
