### ISSUE TITLE
Multimeasure rest measure number ranges are not displayed in score and not properly positioned in parts

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17611]
### Issue type

Engraving bug

#### Multimeasure rest measure number ranges are not displayed in score

![Capture](https://github.com/musescore/MuseScore/assets/90187801/43780d0f-d35c-463c-bbde-cca0e1f4b73f)

#### Multimeasure rest measure number ranges are not properly positioned in parts

![Capture2](https://github.com/musescore/MuseScore/assets/90187801/96af7888-368e-41ec-9f23-ce5dbd82a61c)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/c7c17258-cafc-4110-8efd-e220cfeb4ea8

### MuseScore Version

4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows10

**Comment by cbjeukendrup** [comment]
Maybe this would be resolved by https://github.com/musescore/MuseScore/pull/17675?

**Comment by DmitryArefiev** [comment]
Yes, actually #17675 fixes the issue (tested on Win)

**Comment by DmitryArefiev** [comment]
Fixed in #17675
