### ISSUE TITLE
Score audio will not update when the score was originally uploaded from the musescore app.

### ISSUE THREAD

**Issue by Kainaluking** [musescore/MuseScore#17612]
### Issue type

General playback bug

### Bug description

When I upload my score from the musescore app, any further changes are not reflected in the score audio, even when updated from the website. Tempo changes are shown by the placement of the highlighted measure, but are not reflected in the audio.

### Steps to reproduce

1. In the musescore app with a score open, click "file"
2. click "publish to musescore.com"
3. publish the score
4. make changes to the score and update the score on the website
5. playback the audio of the score

### MuseScore Version

OS: macOS 13.3, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651546, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

macOS Ventura 13.3.1

**Comment by shoogle** [comment]
> update the score on the website

You need to update the online score from within MuseScore, not via the website Upload page.

Click "Publish to musescore.com" again. The score will be uploaded to the same webpage as before and this time the audio will be updated.

Please reopen the issue if that doesn't happen.
