### ISSUE TITLE
MuseScore freezes/crashes when Palm Mute has no beginning

### ISSUE THREAD

**Issue by xlaech** [musescore/MuseScore#17622]
### Issue type

Crash or freeze

### Bug description

When removing notes that had palm mute to them applied without removing the palm mute, the program freezes and needs to be manually stopped as soon as one tries to change the remaining Palm Mute. My guess would be, that the beginning of the palm mute is not reset resulting in something like a nullpointer exception.

I tried to create an example file, but when I save the broken file and reopen the file, the PM gets removed - either the save or the load process seems to be aware of this oddity and removes the "underdefined" palm mute.

### Steps to reproduce

1. Create 2 bars of notes
2. Add a palm mute that starts on the last note in the first bar, but continues into the second bar
3. Remove all notes in the first bar
4. Select the remaining palm mute
5. Try to drag it to the remaining bar => crash

### Screenshots/Screen recordings

**Basic Setup:**
<img width="1680" alt="I - Basic Setup" src="https://github.com/musescore/MuseScore/assets/8291938/3fd0c61b-80ad-4a0e-9837-17e28a083f9a">

**Selecting the first bar**
<img width="1680" alt="II - Select First bar" src="https://github.com/musescore/MuseScore/assets/8291938/9fa94c73-95b6-47de-a193-3c432f7ff51e">

**Removing the first bar**
This will keep the palm mute, which makes sense, since it still it needed for the second bar. However we can already see, that the beginning seems to be set incorrectly.
<img width="1680" alt="III - remove will keep PM" src="https://github.com/musescore/MuseScore/assets/8291938/eaf70ede-5498-41f7-a937-7984e145bbf7">

**Changing the PM**
My cursor is not shown in this screenshot, but selecting is no issue, but as soon as I try to change the PM e.g. by dragging muse score freezes.
<img width="1680" alt="IV - changing remaining PM crash" src="https://github.com/musescore/MuseScore/assets/8291938/ff19d627-5f9e-4927-95ed-e75987e0546a">

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

macOS 12.06

**Comment by xlaech** [comment]
Also reported in #15865

**Comment by Jojo-Schmitz** [comment]
FWIF: 3.x is not affected by this bug
