### ISSUE TITLE
Figured bass entries are not linked between Score and Parts

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17625]
### Issue type
Score <-> Parts issue

### Steps to reproduce

* If you add figured bass in Score it doesn't appear in Part

* If you add figured bass in Part it doesn't appear in Score

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/c5e9ffd4-0176-434b-a74c-708480c3b025

### MuseScore Version

4.1

### Regression

No.

### Operating system

Windows10

### Additional context

The same in **MS3.6.2**

**Comment by DmitryArefiev** [comment]
@oktophonie Not sure it should be **Score <-> Parts** or just **Score -> Parts** dependency (as Expected result here)

**Comment by Jojo-Schmitz** [comment]
Had come up quite a while ago in  https://musescore.org/en/node/332146, with a different potential fix back then
