### ISSUE TITLE
Misinterpretation of beams over rests when importing from MuseScore 3

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#17632]
### Issue type

Engraving bug

### Bug description

When importing scores from MuseScore 3 into MuseScore 4, some information relating to the beam type is lost.

### Steps to reproduce

1. Create a new score in MuseScore 3
2. add 2 notes with a rest between them, and add e.g. a 16th sub beam over said rest.
3. Save the score, and open it in MuseScore 4
4. the sub beam information is lost, a regular beam is present.

See example file linked below
[Beam import.zip](https://github.com/musescore/MuseScore/files/11509744/Beam.import.zip)

### MuseScore Version

4.0.2

### Regression

Choose option...

### Operating system

Windows 10

**Comment by oktophonie** [comment]
Already fixed in master
