### ISSUE TITLE
Trills, which last until the very end of the piece, don't trill. (MS Basic)

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#17646]
### Issue type

General playback bug

### Bug description

See title and video.

https://github.com/musescore/MuseScore/assets/78870770/46f8fa3a-8ef4-47eb-aab7-da7f34c16e11

### Steps to reproduce

1. Fill the last measure (4/4) with a whole note.
2. Add a trill to it. 
3. Playback.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231390304, revision: github-musescore-musescore-e3d5173

### Regression

I don't know

### Operating system

Windows 10

**Comment by somethingstarted** [comment]
can yall assign me to this? i'm gonna take a stab at it. already browsing around in midirender.cpp and related files to get started on researching this one.

**Comment by somethingstarted** [comment]
i also found that there are more than just trills affected. downpralls, upralls and prallpralls also have the same result if put on the very last bar too. it affects other instruments too- specifically the choir- likely others too. so i'm now thinking it might be ornaments related.  still researching. just posting a quick status update

**Comment by DmitryArefiev** [comment]
Regression from MS3 (**occurs in 4.0.0**. as well)
