### ISSUE TITLE
Musescore in batch mode deletes ALL files under the current working directory

### ISSUE THREAD

**Issue by LHKoi** [musescore/MuseScore#17656]
### Issue type

File corruption

### Bug description

After calling
"C:\Program Files\MuseScore 4\bin\MuseScore4.exe" -o "C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott\Nun danket alle Gott. mscx" "C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott\Nun danket alle Gott.mscz"
Exists a new EMPTY file "Nun danket alle Gott.mscx", a new directory META-INF with a rather empty "container.xml", which is also quite empty (see below).
All other files are DELETED.
A further attempt shows that ALL files/directories under the current directory are deleted, META-INF is created under the current directory and only the empty .mscx file is created in the original directory.
Musescore4 4.0.4
Tested on Microsoft Windows 10 Enterprise Evaluation (10.0.19044 Build 19044) (Hyper-V)

Translated with www.DeepL.com/Translator (free version)

### Steps to reproduce

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>tree /f /a
Folder PATH listing
Volume serial number is 661E-DB26
C:.
| Nun danket alle Gott.mscz
| test.mscz
| test.txt
|
---testfolder
test2infolder.txt

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>dir nun*
Volume in drive C has no label.
Volume Serial Number is 661E-DB26

Directory of C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott

12/05/2023 07:45 34.379 Nun danket alle Gott.mscz
1 File(s) 34.379 bytes
0 Dir(s) 107.785.617.408 bytes free

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>
C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>"C:\Program Files\MuseScore 4\bin\MuseScore4.exe" -o "C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott\Nun danket alle Gott.mscx" "C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott\Nun danket alle Gott.mscz"

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>tree /f /a
Folder PATH listing
Volume serial number is 661E-DB26
C:.
| Nun danket alle Gott.mscx
|
---META-INF
container.xml

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott> dir nun*
Volume in drive C has no label.
Volume Serial Number is 661E-DB26

Directory of C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott

12/05/2023 08:36 0 Nun danket alle Gott.mscx
1 File(s) 0 bytes
0 Dir(s) 107.784.589.312 bytes free

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>type META-INF\container.xml
<?xml version="1.0" encoding="UTF-8"?>

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>

### Screenshots/Screen recordings

![MS4-davor](https://github.com/musescore/MuseScore/assets/134151602/cdb561c8-7992-4aae-a777-d502a586003e)
![MS4-danach](https://github.com/musescore/MuseScore/assets/134151602/49bc31fc-cbda-41ff-8659-e51c8446e0dd)

### MuseScore Version

Musescore 4 4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 Enterprise Evaluation (10.0.19044 Build 19044) (Hyper-V)

**Comment by Erriez** [comment]
Same under Linux with command:

```bash
$ ./MuseScore-4.0.2.230651545-x86_64.AppImage "song.musicxml" -o "song.mscx"
```

I lost ALL files(!!!) in this directory and did not have a backup. Thanks. )-;
