### ISSUE TITLE
Glissandos Deleted When Rhythms are Regrouped

### ISSUE THREAD

**Issue by greenfierydragon** [musescore/MuseScore#17654]
### Issue type

Other type of issue

### Bug description

In my score I have a glissando. When I go to `Tools > Regroup rhythms` the glissando disapears.

### Steps to reproduce

1. Create a score
2. Add two notes, say E4 and E5
3. Add a glissando between them
4. Select everything
5. Go to `Tools > Regroup rhythms`

## Before
![image](https://github.com/musescore/MuseScore/assets/21034889/02f7d534-fae4-4564-8f07-f949434ca64e "Before")

## After
![image](https://github.com/musescore/MuseScore/assets/21034889/9dbeb528-dae5-45a0-81e6-4a09249d0495 "After")

### MuseScore Version

4.0.2.

### Regression

I don't know

### Operating system

Archlinux

**Comment by cbjeukendrup** [comment]
Maybe technically related to https://github.com/musescore/MuseScore/issues/15726; maybe not.

**Comment by oktophonie** [comment]
Closing in favour of https://github.com/musescore/MuseScore/issues/18127 (which duplicates this, but also adds some extra info)
