### ISSUE TITLE
[Muse Sounds Issue] Linux Violoncello Solo E4 pitch plays earlier than notated

### ISSUE THREAD

**Issue by joecorporon** [musescore/MuseScore#17653]
### Issue type

Muse Sounds bug

### Bug description

E4 pitch plays earlier than notated, only on Muse Sounds - Violincello Solo. This sounds like a layered sound sample and one or more of the layers plays early, at least on Linux. I don't have another OS on which to test further.

### Steps to reproduce

1. Notate some music using Muse Sounds - Violoncello Solo, including some E4 pitches.
2. On playback of E4 you will hear some of the sound layers sound early.

### MuseScore Version

OS: Manjaro Linux, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-, revision: github-musescore-musescore-

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Manjaro 22.1.2 and Manjaro 22.1.1

### Additional context

1. This bug only happens when using Muse Sounds - Violincello Solo
2. I only have the Linux version and have no other OS options.
3. This bug did not happen in Musescore 4.0.1 or earlier as far as I'm aware.

**Comment by joecorporon** [comment]
Just updated Muse Sounds and the issue is gone. Thanks for your help!

**Comment by cbjeukendrup** [comment]
Closing as completed!
