### ISSUE TITLE
segfault when pressing 'tab' multiple times from Playback Controls

### ISSUE THREAD

**Issue by fenugrec** [musescore/MuseScore#17660]
### Issue type

Crash or freeze

### Bug description

100% reproducible segfault when pressing 'tab' after setting a Loop marker via the Playback Controls dlg.

### Steps to reproduce

1. open score or create one from template (e.g. Grand Staff)
2. click / set cursor in a random measure
3. drag the Playback Controls panel so it becomes the floating dialog with buttons for setting loop markers
4. click 'set loop marker left'
5. press 'tab' about 10-15 times to attempt to bring focus back to the score (context : I wanted to use the keyboard to navigate a few measures to the right with Ctrl+Right then set the other loop marker)
6. segfault. Distro build doesn't have debug syms; if nobody else can reproduce I will have to compile if a backtrace would be needed.

### MuseScore Version

OS: Manjaro Linux, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-, revision: github-musescore-musescore-

### Regression

I don't know

### Operating system

Linux (Manjaro)

**Comment by Jojo-1000** [comment]
Can reproduce on Win 10 (focus detached play panel by clicking and press tab).
The crash is in navigationcontroller.cpp line 676:

https://github.com/musescore/MuseScore/blob/796dc69830be0214dd53919e1342536d37088194/src/framework/ui/internal/navigationcontroller.cpp#L669-L680
It seems that the navigation is not properly defined (all the sections are disabled, `nextSec` is null) and there is no check for that.
If you use tab to *enter* the panel you can still leave it, but when you click in it crashes when trying to tab out.
