### ISSUE TITLE
Basse chiffrée

### ISSUE THREAD

**Issue by btuncq** [musescore/MuseScore#17678]
### Issue type

Engraving bug

### Bug description

Bonjour,

Il était possible de Musescore 3 de mettre plusieurs chiffrages (basse chiffrée) sur une même note.
En tapant Ctrl + le chiffre qui correspond au rythme nous pouvions écrire précisément le chiffrage sur les rythmes correspondant (sur une même note).

Ça n'est plus possible sur Musescore 4, avez-vous une solution?

Par avance merci, et merci pour ce super logiciel.

### Steps to reproduce

- écrire une ronde.
- cliquer sur la note
- Ctrl + G pour écrire la basse chiffrée
- Puis Ctrl+5 devrait permettre d'écrire un chiffrage une noire après, mais toujours sur la ronde.

Mais ça ne fonctionne plus sur musescore 4

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/134282300/b4987e33-e8c6-4340-8a30-511cdc524d35)

### MuseScore Version

Musescore 4

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by oktophonie** [comment]
Duplicate of e.g. https://github.com/musescore/MuseScore/issues/17030 (and fixed, I think, in master already)
