### ISSUE TITLE
Cloud Scores path is hardcoded

### ISSUE THREAD

**Issue by KaiJan57** [musescore/MuseScore#17672]
https://github.com/musescore/MuseScore/blob/796dc69830be0214dd53919e1342536d37088194/src/project/internal/projectconfiguration.cpp#L342

Please add a configuration option in `MuseScore4.ini` to prevent MuseScore from creating a superfluous `$HOME/Documents/MuseScore4/Cloud Scores` directory

**Comment by cbjeukendrup** [comment]
FWIW, In MuseScore 4.1, the cloud scores folder will be moved to the hidden user data directories, since exposing this folder to the user is asking for trouble.
