### ISSUE TITLE
"Repeat last bar" symbol doesn't repeat pizzicato and arco instructions

### ISSUE THREAD

**Issue by ThatOtherAndrew** [musescore/MuseScore#17680]
### Issue type

General playback bug

### Bug description

When using the "repeat last bar" symbol, instructions to play pizzicato or arco don't seem to be repeated, and the playback engine retains whatever the last instruction was.

### Steps to reproduce

1. Select a string instrument capable of playing pizzicato and arco (e.g. Violin I)
2. Create a bar which contains `pizz.` and `arco` instructions from the `Text` palette
3. Add the `Repeat last bar` symbol in the next bar from the `Repeats & jumps` palette
4. Play the bars

### Screenshots/Screen recordings

<img width="478" alt="image" src="https://github.com/musescore/MuseScore/assets/26030336/b7fa3f1a-7b7d-4ee5-8c45-d18ae806ff2b">

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
Replicated in 4.0.2 Windows 11 and nightly
This functions desired here in MuseScore3
Not a very common use case I believe

**Comment by DmitryArefiev** [comment]
Fixed in #20598
