### ISSUE TITLE
Muse Sounds Feature Request: Human Playback Genre Performance

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#17688]
### Your idea

So I understand that Muse Sounds can playback every score in it's own cinematic modern style of playing, though I'm wondering if there could be a feature where we can have it playback these scores in other customizable music genre human playback styles. Finale has different human playback styles, so why not let Muse Sounds do the same.

For instance, the examples of playback would be:
-Baroque
-Pop
-Viennese Waltz
-Rock
-Jazz
etc.

I thought it would be interesting if Muse Sounds had a feature like that.

### Problem to be solved

Adding different music genre playback styles for Muse Sounds

**Comment by bkunda** [comment]
Closing as not planned.
