### ISSUE TITLE
Aux Channel Mute and Solo functionality

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#17703]
### Issue type

UI bug

### Bug description

The solo and mute buttons on the aux channel should turn on and off the effects.
In other words: Mute should turn off the effects in that channel, Solo should turn off effects in other channels.

### Steps to reproduce

1. Open or create a score with audio effects visible in the mixer.
2. Aux channel 1 and 2 should be visible in the mixer and effects should be assigned to them.
3. Play the score.  Pressing the solo (S) button changes color but does not change playback.  Pressing the Mute (M) button does nothing.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/7bd1fbcc-8690-443d-9dec-aac70ff24689

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231420826, revision: github-musescore-musescore-230479a

### Regression

No.

### Operating system

OS: macOS 11.6, Arch.: x86_64,

### Additional context

This is pertaining to the release of the mixer with added reverb controls.

https://github.com/musescore/MuseScore/pull/17570

**Comment by bkunda** [comment]
After discussing with @jessjwilliamson, we agree that:

- We _want_ to implement solo functionality for the aux channels in the near future. Given @RomanPudashkin's advice that implementing this now (for 4.1) could introduce instability, we will **disable** these buttons for now, and re-enable them when the feature is working.
- We realised that the **solo** functionality of the master channel is redundant (it doesn't work, and it isn't required), so this should be removed and the **mute** button centered.
  
<img width="672" alt="Screenshot 2023-06-30 at 12 48 52 pm" src="https://github.com/musescore/MuseScore/assets/86290556/30d81c68-cf53-4048-840e-043ae2017211">

**Comment by MarcSabatella** [comment]
Is it meant that the mute button on master actually do anything?  Currently (4.0.2 and latest 4.1 nightly) it doesn't.  If it's too late to fix that, maybe we could disable or remove that for now as well.

**Comment by zacjansheski** [comment]
https://github.com/musescore/MuseScore/pull/18325 will disable the Solo buttons and enable functionality of Mute buttons on the aux channels
