### ISSUE TITLE
Undoing and re-adding certain objects causes extra ones added (Clefs, Time signatures, Key signatures, Barlines, Repeats, Layout)

### ISSUE THREAD

**Issue by LupusCaeruleus** [musescore/MuseScore#17718]
### Issue type

Other type of issue

### Bug description

_Update_: Also affects **Clefs**, **Time sigs** and **Key sigs**.

This bug seems to occur only on some objects of the panels **Barlines**, **Repeats & Jumps** and **Layout**.

When certain objects from the 3 panels are added then undo-ed, re-adding them will add one extra object to the next bar. See Steps to reproduce and Screen recording for more details.

### Steps to reproduce

1. Select a bar (or a range of bars) on the staff.
2. Add any of the following objects below, by clicking them in their panels.
　**Repeats & Jumps Panel:** Segno symbols, Coda symbols, Texts, Repeat signs.
　**Barlines Panel:** Barlines.
　**Layout Panel:** Stave spacers, Frames, Insert one bar before selection.
3. Press Ctrl+Z (or use other methods) to undo.
4. Repeat step 2.
5. One extra object is added to the next bar.

Expected behaviour: No extra objects should be added.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/70313425/c1ed39bc-2ae0-40e4-9ddf-a96e43d90bae

https://github.com/musescore/MuseScore/assets/70313425/3e016377-01aa-4d40-87fc-07166424a24e

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

### Additional context

I noticed that after adding and undoing, the blue range selection box extends a little bit to the right and seems to enclose the barline on the right. Maybe this is the issue?

**Normal selection:**
![image](https://github.com/musescore/MuseScore/assets/70313425/38a8dfa5-5e42-447d-aad7-306befd53450)

**After adding and undoing:**
![image](https://github.com/musescore/MuseScore/assets/70313425/3204e07c-d6af-4820-96c5-43911f98cc3d)

**Comment by zacjansheski** [comment]
Possible duplicate https://github.com/musescore/MuseScore/issues/15851
