### ISSUE TITLE
Musescore crashes when opening a file

### ISSUE THREAD

**Issue by Lenrad123** [musescore/MuseScore#17720]
### Issue type

Crash or freeze

### Bug description

Musescore opens for about 5 seconds, then closes itself without any error message.
After converting the backup into .zip and .mscx it shows this error message: Error=XML_ERROR_PARSING_TEXT ErrorID=8 (0x8) Line number=1

### Steps to reproduce

1. Try to open a .mscz file

### MuseScore Version

4.0.2.230651553

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

This worked in the same Musescore version, I last edited it on 23.05.23 at about 20:30, then couldn't open it the next day.

**Comment by cbjeukendrup** [comment]
If this happens with a specific score, we will of course need a copy of that score, so that we can investigate. Could you please upload it here? (To do so, wrap it in a zip file or rename `.mscz` to `.zip`, so that GitHub accepts it.)

**Comment by Jojo-Schmitz** [comment]
It is the score from https://musescore.org/en/node/346577#comment-1191457

**Comment by mart661331** [comment]
I have the same problem, for a month now I think.

For one score i have split the score in 2 parts. That helped....

Now one part is not opening in may 25th nightly

Windows 11

**Comment by MarcSabatella** [comment]
@mart661331 same for you then - we'd need to see the actual score.  But, there is no reason to assume it's the same problem as this.  Crashes can be symptoms of entirely unrelated problems.  Better to open a new issue and attach the score there.  If it does turn out to be a duplicate, the issue can be closed.

**Comment by Lenrad123** [comment]
[ajr_Worlds_Smallest_Violin.zip](https://github.com/musescore/MuseScore/files/11568446/ajr_Worlds_Smallest_Violin.zip)

**Comment by zacjansheski** [comment]
Recreated on Mac 
Diagnostic files
[17720.zip](https://github.com/musescore/MuseScore/files/11576338/17720.zip)

**Comment by zacjansheski** [comment]
I was able to open the file without issue in the latest nightly build on Windows 11

**Comment by MarcSabatella** [comment]
Did you try a nightly build?  If so, which night?  I’m guessing you only tried release builds.  To get a nightly build, go to the Download page on musescore.org and scroll down.  This won’t replace your release build, but you can use it for testing and to work on scores that crash the release version.

**Comment by zacjansheski** [comment]
Please do check the nightly build to help us ensure this is resolved

[Violin-Score_and_Parts.zip](https://github.com/musescore/MuseScore/files/11578171/Violin-Score_and_Parts.zip)

**Comment by Lenrad123** [comment]
Thank you so so much! You just saved me.
I did just try and download the latest nightly build, but I'm having the exact same issue, where it just closes without an error message.

**Comment by Jojo-1000** [comment]
I can reproduce the crash on master in debug mode (Win 10)
``` 
1  mu::engraving::Part::startTrack                                                    part.cpp                        529  0x140cf661b 
2  mu::engraving::Part::harmonyCount                                                  part.cpp                        751  0x140cf95ff 
3  mu::engraving::Part::updateHarmonyChannels                                         part.cpp                        797  0x140cf9a15 
4  mu::engraving::rw400::Read400::readScore400                                        read400.cpp                     258  0x140dd2f6a 
5  mu::engraving::rw400::Read400::read                                                read400.cpp                     65   0x140dd11a0 
6  mu::engraving::MscLoader::loadMscz                                                 mscloader.cpp                   165  0x1408dade2 
7  mu::engraving::EngravingProject::loadMscz                                          engravingproject.cpp            147  0x14281b39e 
8  mu::project::NotationProject::doLoad                                               notationproject.cpp             195  0x1417a4139 
9  mu::project::NotationProject::load                                                 notationproject.cpp             159  0x14179f380 
10 mu::project::ProjectActionsController::doOpenProject                               projectactionscontroller.cpp    214  0x14179208d 
11 mu::project::ProjectActionsController::openProject                                 projectactionscontroller.cpp    197  0x141785a2a 
12 <lambda_14a0ac51a6f1da72e48b13ef9d0060ee>::operator()                              applicationactioncontroller.cpp 102  0x141c56fb7 
13 deto::async::AsyncImpl::Functor<<lambda_14a0ac51a6f1da72e48b13ef9d0060ee>>::call   asyncimpl.h                     27   0x141c5914b 
14 deto::async::AsyncImpl::onCall                                                     asyncimpl.cpp                   64   0x14061bd50 
15 <lambda_9a3bee7739572ed3ab3ddadb95de802c>::operator()                              asyncimpl.cpp                   42   0x14061be1a 
16 std::invoke<<lambda_9a3bee7739572ed3ab3ddadb95de802c> &>                           type_traits                     1525 0x1406416f4 
17 std::_Invoker_ret<void,1>::_Call<<lambda_9a3bee7739572ed3ab3ddadb95de802c> &>      functional                      652  0x14062e554 
18 std::_Func_impl_no_alloc<<lambda_9a3bee7739572ed3ab3ddadb95de802c>,void>::_Do_call functional                      823  0x14062533b 
19 std::_Func_class<void>::operator()                                                 functional                      870  0x14064ef1f 
20 mu::framework::Invoker::doInvoke                                                   invoker.cpp                     64   0x1406e4046 
... <More>                                                                                                                              
```
https://github.com/musescore/MuseScore/blob/15d6c8bf9da9b3a66d06d4deed6f11b3a628ead8/src/engraving/libmscore/part.cpp#L527-L530

The part named "Stimme" (3rd part in excerpt "Altsaxophon", line 126862 in mscx file) has no staves in its list, but `_staves->front()` is accessed without a check. So there is some corruption in the file, but this should not result in a crash as the other parts are fine.

If I add a check for empty staves in harmonyCount the score opens fine, I only get a warning repeatedly:

    15:26:04.579 | WARN  | main_thread | MasterScore | rebuildExcerptsMidiMapping: rebuildExcerptsMidiMapping: no part in master score is linked with Stimme

When I open the "Altsaxophon" part, it is visible. However, if I try to enable another track that is not already in that part it causes another crash.

> I was able to open the file without issue in the latest nightly build on Windows 11

That is interesting, because the file definitely is corrupted, maybe on your system there was no access violation.
