### ISSUE TITLE
Melismas should allow words to pass over barlines

### ISSUE THREAD

**Issue by DrChipmunk** [musescore/MuseScore#17721]
### Your idea

Words with mellismas over the end of one bar and the beginning of the next should be typeset over multiple notes.

### Problem to be solved

When a melisma begins right at the end of one bar and continues into the next bar, the word is unable to pass over the invisible bar boundary, resulting in unbeautiful behaviour, especially for long, one-syllable words.

![melisma_feature_example](https://github.com/musescore/MuseScore/assets/42274716/a38e5243-40cc-44d0-88a0-6b96dde52044)

![melisma_feature_example_2](https://github.com/musescore/MuseScore/assets/42274716/549da346-dcfe-413c-bd04-02c01da870ce)

It would look more natural and use less room on the page for these words to be written over the invisible barline. There used to be hacky ways to resolve this problem, but they don't seem to work anymore.

Related to https://musescore.org/en/node/305593

### Additional context

See also https://musescore.org/en/node/317608, with a request for more real-world examples.

**Comment by cbjeukendrup** [comment]
It looks like this is covered by https://github.com/musescore/MuseScore/issues/17423, which is on the radar! Thanks for reporting anyway.

**Comment by oMrSmith** [comment]
> There used to be hacky ways to resolve this problem, but they don't seem to work anymore.

You should be able to decrese the leading space of the barline to work around...

![image](https://github.com/musescore/MuseScore/assets/78870770/e1a012c9-f9bb-4b25-bf1d-2b73c284720c)

**Comment by jjbveld** [comment]
Solution: select 'world' and disable autoplace. You can now drag both the note and the text.

**Comment by oMrSmith** [comment]
For the time being it is better to use "Leading Space" for the barline,
because disabling autoplace will also bypass the horizontal alignment.
