### ISSUE TITLE
Selecting "below" for measure numbers just puts them under the first part instead of under the bottom stave

### ISSUE THREAD

**Issue by pgrimes2002** [musescore/MuseScore#17722]
### Your idea

Put the numbers at the very bottom of the score rather than just under the top part when you select "under" instead of "above" for measure number placement. Also, have the option to have measure numbers and rehearsal marks be shown at the top of each new bracket like in lots of professionally engraved scores. Currently, you can have it on all of the staves, but not just the staves at the top of a group of bracketed staves.

### Problem to be solved

Especially in marching band scores, it is nice to have all of the measure numbers below the score, and currently there is no way to do that.

**Comment by MarcSabatella** [comment]
In the past we’ve always held that the existing “placement” property should remain as it is, relative to the staff, but that there should simply be a *different* property to control which stave(s) an element appears on (and 4.0 has already taken steps in this direction with tempo markings repeated above the strings, etc).
