### ISSUE TITLE
MuseScore launcher using ~4-6Gb of VRAM when idle

### ISSUE THREAD

**Issue by 9291Sam** [musescore/MuseScore#17736]
### Issue type

Other type of issue

### Bug description

While developing a Vulkan application, I ran into an issue where I was only able to access about 2GB of my GPU's 8Gb of VRAM before having to fallback to system memory

### Steps to reproduce

1. Have the muse score launcher running in the background.
2. Open task manager and watch your VRAM usage
3. Kill the muse score launcher process
4. Observe massive drop in VRAM usage

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/25729215/07b9ab90-2ec2-4c76-b35e-6769bb35be75)

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

Windows 10.0.22621.1702

**Comment by cbjeukendrup** [comment]
If with "the MuseScore launcher" you refer to Muse Hub, please report this issue to the Muse Hub team directly instead: https://musehub.zendesk.com/

**Comment by 9291Sam** [comment]
Will do!
