### ISSUE TITLE
MuseScore 4.1.0-dev Crashes when exporting MIDI files

### ISSUE THREAD

**Issue by ChriiMoral** [musescore/MuseScore#17746]
### Issue type

Crash or freeze

### Bug description

When selecting to export separate parts in MIDI format, the program crashes as soon as a folder location is selected, with no residual message or anything of the sort.

### Steps to reproduce

1. Open a score with various parts (I haven't tested is this changes depending on the amount of parts and the length of the score)
2. Go to File > Export > Select All (in the video I excluded the Main Score) > Export
3. Select your file location to save the MIDI files.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/63615949/ce0b0e2a-9a10-4635-b1c9-d91b2e3e2405

### MuseScore Version

4.1.0-dev

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

The score I worked with is 4 minutes long (at 120 bpm, so it's long) and it features an entire symphony orchestra (so, more than 20 parts). I have not tried this with shorter scores, or scores with fewer parts.

MuseScore version that still works: **MuseScore 4.0.2**

**Computer Specs.**
**Processor**: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz   3.20 GHz
**Installed RAM**: 28.0 GB
**System type**: 64-bit operating system, x64-based processor

**OS Edition**: Windows 11 Pro
**Version**: 22H2
**OS build**: 22623.730
**Experience**: Windows Feature Experience Pack 1000.22636.1000.0

**Comment by zacjansheski** [comment]
I have replicated this with several scores.  Attached is the smallest/simplest score I have replicated with.

[MS4_Bach__Sechs_kleine_Präludien_2 Prelude in C Minor_BWV934.zip](https://github.com/musescore/MuseScore/files/11615841/MS4_Bach__Sechs_kleine_Praludien_2.Prelude.in.C.Minor_BWV934.zip)
[17746DiagnosticFiles.zip](https://github.com/musescore/MuseScore/files/11615845/17746DiagnosticFiles.zip)

**Comment by zacjansheski** [comment]
I am not getting this crash now.  Do you still get the crash on the nightly?

**Comment by ChriiMoral** [comment]
Hi there! I'm glad to notify that the issue is gone! Exporting multiple MIDI parts work as expected!

**Comment by cbjeukendrup** [comment]
Thanks, that's good news!
