### ISSUE TITLE
Dot position UI no longer works

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#17749]
### Issue type

Engraving bug

### Bug description

The option to change the dot position (in the inspector panel) is no longer working

<img width="820" alt="image" src="https://github.com/musescore/MuseScore/assets/21022311/a1006431-f922-4e0d-8d75-8a6dd1185f9e">

### Steps to reproduce

Create dotted note on a line and try the options in the inspector

### MuseScore Version

4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS

**Comment by HemantAntony** [comment]
Can you check if #17763 fixes this issue?

**Comment by Tantacrul** [comment]
It is definitely producing the result I want! Thanks Hemant! 😄

@RomanPudashkin @Eism @cbjeukendrup - if you're happy can this be inducted into the international merging hall of fame?

**Comment by cbjeukendrup** [comment]
I think @asattely would be the ideal person to review this PR. (From a pure code-technical POV it looks good, but I don't know the context super well.)

**Comment by HemantAntony** [comment]
Cool! I have to fix my vtest failures first. I broke a couple things 😅
