### ISSUE TITLE
MuseScore 4 displays wrong fonts in Japanese

### ISSUE THREAD

**Issue by SakiPapa** [musescore/MuseScore#17740]
### Issue type

UI bug

### Bug description

When the MuseScore UI is set to Japanese, the wrong glyphs (Chinese glyphs) are used.

### Steps to reproduce

1. Preferences.. > General > Languages > 日本語 (Japanese)
2. Press "OK"
3. Restart MuseScore 4 on Japanese UI.
4. All the UI Characters displays in Chinese glyphs.

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 12.6.6

### Additional context

This information would be useful for this issue.

https://heistak.github.io/your-code-displays-japanese-wrong/

**Comment by Jojo-Schmitz** [comment]
MuseScore version 4.2? I guess you mean 4.0.2, right?
It is 'just' the wrong glyps, but the corect language/translation, isn't it?

**Comment by SakiPapa** [comment]
Oops, it's 4.0.2 not 4.2 !
Yes, only the glyphs are wrong, and the language/translation is correct.

**Comment by Jojo-Schmitz** [comment]
So an issue with the font that is being used. Only on Mac or also on Windows and Linux?

**Comment by SakiPapa** [comment]
The glyphs are displayed correctly on Windows 11. I do not have a Linux environment, so I do not know what happens on Linux.

The glyphs for menu characters are displayed correctly on Mac as well. The glyphs in both preferences and home windows are incorrect.

**Comment by bakajikara** [comment]
Seems to be an Qt issue (fixed in Qt 6). See: https://bugreports.qt.io/browse/QTBUG-85598

Adding "Hiragino Sans" to font substitute might be a workaround.
https://bugreports.qt.io/browse/QTBUG-81924?focusedCommentId=497035&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-497035

**Comment by SakiPapa** [comment]
I have confirmed that this problem with Japanese glyphs can be solved by specifying the font face as follows

Preferences > Appearance > Font Face > Hiragno Sans

By default, the font face was set to "Hiragino Sans GB".

**Comment by bakajikara** [comment]
#17772 resolves this issue.
Above is the latest nightly and below is the artifact from #17772.
<img width="640" alt="スクリーンショット 2023-06-06 0 47 27 (2)" src="https://github.com/musescore/MuseScore/assets/102702868/dfa2c884-f5d4-4b00-a91c-8cbaa6abc846">

**Comment by cbjeukendrup** [comment]
Oh, that's very good news! Thanks for checking, @bakajikara!

@bkunda In that case this goes back into 4.1 :)
