### ISSUE TITLE
MuseHub Zendesk wtf?

### ISSUE THREAD

**Issue by isolin** [musescore/MuseScore#17750]
### Issue type

Other type of issue

### Bug description

I wanted to ask a question on [MuseHub Zendesk](https://musehub.zendesk.com). I looked through the forum and found out that I will be better off asking directly in the chat. So I politely started the conversation
```
MuseBot> Hi there. Got a question? I'm here to help.
Me> Hi! I absolutely love the Muse Hub sounds.
MuseBot> Sorry to hear this. Which platform are you running Muse Hub on? WIndows MacOS Linux
MuseBot> Thanks, let's transfer you to an agent. Let us know a few details, and we'll connect you right away.

Musebot then asked for name and email.
Musebot> Thank you! Someone will be with you shortly.

After 30 minutes (I tried to say hello a few times) there was no more answer neither form a real person, nor from the bot.
```

I gave up. I didn't even get to ask my question. After this, I feel also sorry that I love Muse Hub Sounds. So **please give up on zendesk, it's useless. Why not having everything concentrated here on github?** The community is larger here and you get more qualified answers. Just as an example of what I mean, look [here](https://musehub.zendesk.com/hc/en-gb/community/posts/10929222861085) to find an incompetent Hub Team member asking if a 42Gb memory leak relates to GPU or CPU memory. From the posted PC specs it is clear that the GPU is a GTX 1070 with 8Gb of VRAM so the memory can only by allocated by the CPU (16 Gb RAM according to specs) expanding to the pagefile to accommodate those additional 26Gb. Of course the disk I/O is a serious bottleneck.

### Steps to reproduce

Tell Zendesk that you absolutely love Muse Hub Sounds.

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

web

**Comment by cbjeukendrup** [comment]
> So please give up on zendesk, it's useless. Why not having everything concentrated here on github?

**Because Muse Hub is an entirely different application, built by entirely different people, from an entirely different team, using entirely different technologies, and it's source code lives in an entirely different (closed source) repository.**

(As has been explained often enough now, I suppose.)

I mean, you wouldn't either send a message to the developers of your favourite app and be like "Hey why is the Microsoft Store support so bad? Can't you fix the Microsoft Store?".

**Comment by isolin** [comment]
I am sorry, I didn't know it is so much separated. You know, `MuseScore` and `Muse Hub` indicate strong affinity. Afaik `Muse Hub` is only used with `MuseScore` (so far). The companies producing them have very similar names, identical seat ... and none of them is a big corporate. So the product identity, branding and legal background indicate just the opposite of an **entirely different application**. I fear `MuseScore` will keep on getting similar inquiries :)
