### ISSUE TITLE
Crash when deleting rest in second voice

### ISSUE THREAD

**Issue by phthalylsulfathiazole** [musescore/MuseScore#17761]
### Issue type

Crash or freeze

### Steps to reproduce

1. go to the Hn part of bar 75
2. select on the note as shown below:
![image](https://github.com/musescore/MuseScore/assets/20604032/fa1beac4-6a6c-49ea-96cd-8932d038533f)
4. press delete to remove the note; the rest is now selected:
![image](https://github.com/musescore/MuseScore/assets/20604032/6f89e395-dca7-4fe4-9e9e-4c1167ae6583)
5. press delete again; MuseScore crashes

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 10

### Additional context

file: [intermezzo2.zip](https://github.com/musescore/MuseScore/files/11584930/intermezzo2.zip)

**Comment by Jojo-Schmitz** [comment]
Latest builds require to re-select the rest (see #13469)

**Comment by DmitryArefiev** [comment]
Fixed in #17882
