### ISSUE TITLE
Guitars Ignore Ties in Playback when Distorted

### ISSUE THREAD

**Issue by Nathanisaduck** [musescore/MuseScore#17779]
### Issue type

General playback bug

### Bug description

It's just as the title says. When guitars have distortion (or overdrive too) they will ignore ties during playback.

### Steps to reproduce

1. Choose a guitar
2. Have it last for 6 beats in 4/4
3. Hit play

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
Thanks, this is reported already in https://github.com/musescore/MuseScore/issues/16968

**Comment by cbjeukendrup** [comment]
Closing as a duplicate. Thanks anyway!
