### ISSUE TITLE
Single-note tremolos on beamed notes make stems too long

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#17789]
### Issue type

Engraving bug

### Bug description

Though single-note tremolos sometimes require extending the stem so that they fit between notehead and beam with enough padding either side, they now appear to be creating too much space between tremolo and notehead almost all the time. Some examples:

![image](https://github.com/musescore/MuseScore/assets/20604032/9c52605b-0d2d-4030-94aa-0fa4acb56640)

### Steps to reproduce

1. Create some beamed notes 8ths or shorter)
2. Add single-note tremolos to the notes. A single slash appears to be fine - the problem only becomes apparent when two or more slashes are used.

### MuseScore Version

OS: Artix Linux, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231500304, revision: github-musescore-musescore-e96b96f

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux, presumably others

**Comment by DmitryArefiev** [comment]
Fixed in #17797
