### ISSUE TITLE
Alterations on trill lines aren't synchronising with previously-created parts

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#17788]
### Issue type

Engraving bug

### Bug description

Once parts have been created for the first time, any alterations made to a trill line will not synchronise with the part (even after closing and re-opening the part).

Alterations to trill lines synchronise correctly before the part has been created for the first time.

### Steps to reproduce

See video

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/86290556/ba2ab501-c506-499e-95b3-10f7ff6f41ce

### MuseScore Version

OS: Windows 11 Pro, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231500723, revision: github-musescore-musescore-888344f

### Regression

No.

### Operating system

Windows 11

### Additional context

@RomanPudashkin FYI

**Comment by oktophonie** [comment]
Pretty sure this is just yet another instance of what's described in https://github.com/musescore/MuseScore/issues/16544
