### ISSUE TITLE
"Ornaments" button in Properties doesn't appear when line ornaments are selected within a range

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#17790]
### Issue type

UI bug

### Bug description

Where a line ornament (e.g. trill line, downprall line, etc.) is selected within a range containing other elements, the "ornaments" button does not appear in Properties. 

### Steps to reproduce

See video

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/86290556/bcf0444e-b0cc-46ba-b24b-acebcdb119ec

### MuseScore Version

OS: Windows 11 Pro, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231500723, revision: github-musescore-musescore-888344f

### Regression

No.

### Operating system

Windows 11

### Additional context

@HemantAntony FYI in case you're interested :-)

**Comment by HemantAntony** [comment]
@bkunda Ah, I got confused. Does #17876 do the trick for you? :)

**Comment by HemantAntony** [comment]
@bkunda Ah, I got confused. Does #17876 do the trick for you? :)

**Comment by HemantAntony** [comment]
@bkunda Ah, I got confused. Does #17876 do the trick for you? :)
