### ISSUE TITLE
[MU 4 issue] MuseScore 4 Crashes on loading screen - MacOS Ventura 13.1

### ISSUE THREAD

**Issue by phoenixofstorm** [musescore/MuseScore#17802]
GitHub Crash Report for MuseScore 4

Issue:
The program crashes on load. After seeing the loading screen, the program crashes without any further progress.

Timeframe:
The issue has been present since the initial installation of MuseScore 4. I decided to wait for an update in the hopes that the problem would be resolved. However, even after updating the app via MHub, the problem persisted. It is worth noting that I have a previous version of MuseScore (MuseScore 3) installed, which is working fine.

Steps Taken:
1. Attempted to launch the app via the terminal.
2. The app crashed once again.
3. Ran the app with the debug flag using the command `./mscore -d`.
4. Received the following output:

```
QEventLoop: Cannot be used without QApplication
QEventLoop: Cannot be used without QApplication
16:41:19.323 | INFO | main_thread | GlobalModule | onPreInit: log path: /Users/***/Library/Application Support/MuseScore/MuseScore4/logs/MuseScore_230531_164119.log
16:41:19.323 | INFO | main_thread | GlobalModule | onPreInit: === Started MuseScore 4.0.2, build number 230651546 ===
16:41:19.401 | INFO | main_thread | DiagnosticsModule | onInit: success start crash handler
16:41:19.416 | WARN | main_thread | Qt | QIODevice::read (QFile, "/Users/***/Library/Application Support/MuseScore/MuseScore4/shortcuts.xml"): device not open
16:41:19.417 | WARN | main_thread | Qt | QIODevice::read (QFile, "/Users/***/Library/Application Support/MuseScore/MuseScore4/midi_mappings.xml"): device not open
16:41:19.762 | ERROR | main_thread | MuseSamplerLibHandler | MuseSamplerLibHandler: Unable to open MuseSampler library, path: /Users/***/Library/Application Support/MuseSampler/lib/libMuseSamplerCoreLib.dylib
16:41:19.762 | ERROR | main_thread | MuseSamplerResolver | checkLibrary: Incompatible MuseSampler library; ignoring
[97809:992134:20230531,164120.488701:WARNING crash_report_exception_handler.cc:240] UniversalExceptionRaise: (os/kern) failure (5)
Killed: 9
```

Additional Information:
- I have MuseScore 3 and MuseScore 2 installed, both are functioning correctly.
- I have not encountered this issue with any other applications or programs on my system.

**Comment by Eism** [comment]
@phoenixofstorm 
Could you please check this build?
https://github.com/Eism/MuseScore/suites/13401318790/artifacts/733935121
