### ISSUE TITLE
Clicking "Staff text properties" in Properties - More  leads into crash

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#17804]
### Issue type

Crash or freeze

### Bug description

Clicking "Staff text properties" in Properties -> More leads into crash.

Also this option is wrongly showed for System text, and missing for Staff text.

### Steps to reproduce

1. add some System text to score (or Staff text, or other Text, and change it to System text in Properties)
2. click Properties tab -> More -> Staff text properties
3. crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1646034/89f31f3d-8c84-474e-89a6-a0fcd60a3570

### MuseScore Version

4.1 master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 22.04

### Additional context

"Staff text properties" shouldnt be there for System text, but should be there for Staff text.

**Comment by zacjansheski** [comment]
Reproduced on Mac OS 11.6.5

**Comment by Jojo-Schmitz** [comment]
Famous last words in the logs:
```
2023-06-07T12:42:08.937 | ERROR | main_thread | Qt         | Object 0x266a75a0 destroyed while one of its QML signal handlers is in progress.
Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
This behavior is NOT supported!
qrc:/qml/MuseScore/Inspector/text/TextSettings.qml:183: function() { [native code] }
```
