### ISSUE TITLE
MusicXML import and export - Implement swing tempo

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#17815]
### Your idea

Implement MusicXML import and export for swing tempo as shown in this example
https://www.w3.org/2021/06/musicxml40/musicxml-reference/examples/swing-element/

### Problem to be solved

This is how swing works in Musescore:

https://github.com/musescore/MuseScore/assets/919446/06b127dd-2fd5-4350-aa53-cf5dbf00c01a

And this is how it sounds after exporting in MusicXML and opening mxl file:

https://github.com/musescore/MuseScore/assets/919446/482c8a5f-01bc-40a2-8662-2af00452652e

### Additional context

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231462149, revision: github-musescore-musescore-2be9061

**Comment by Jojo-Schmitz** [comment]
Came up before in https://musescore.org/en/node/268454

**Comment by cbjeukendrup** [comment]
Closing as superseded by #18752. Thanks for reporting!
