### ISSUE TITLE
Navigation with Alt+Left/Right doesn't work properly with some new Ornaments

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17814]
### Bug description

There are two issues with ornaments navigation:

1. **NEW BUG** (doesn't occur in **4.0.2**): Navigation with **Alt+Right gets stuck on some ornaments**: Inverted turn, Turn, Trill, Short trill, Mordent, Turn with slash, Tremblement, Prall mordent - **THIS IS FIXED IN #18242**

2. Old bug (occurs in 4.0.0 - 4.0.2): Navigation with **Alt+Left skips some ornaments**: all ornaments except Till line, Prallpral line, Downprall line, Upprall line (maybe I missed some not common ornaments) - **THIS IS FIXED IN #18314**

### Steps to reproduce

**BUG 1**

1. Add all mordents
2. Start navigation with **Alt+-->** - on some ornament **navigation stops**, you should use **Right arrow** only to navigate to the next next and then continue with **Alt+-->**

**BUG 2**

1. Add all mordents
2. Go to the last note
4. Start navigation with **Alt+<--** - **some ornaments just skipped**

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/bc2e8f90-ca1a-4989-89e1-ead4a6dbb4f0

### MuseScore Version

5.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows10

**Comment by Eism** [comment]
Fixed the first bug - we simply forgot to add handling for ornaments in the code responsible for navigation.

Didn't fix the second bug - added handling for ornaments, but the logic somewhere got broken and back navigation is not working. Additionally, back navigation is not working also for articulations.

We'll create a separate issue. Maybe @mike-spa can help us fix this bug.

**Comment by mike-spa** [comment]
BUG 2 is not a regression against 4.0 (see video), so I think it shouldn't go in 4.1. Anyway, I've made a fix, PR coming soon :) (and thanks @Eism for fixing the first bug!)

https://github.com/musescore/MuseScore/assets/93707756/ab01c208-e795-49c1-ba67-fc0378497c62

**Comment by DmitryArefiev** [comment]
Fixed in #18242

**Comment by DmitryArefiev** [comment]
**BUG 2** fixed in #18314
