### ISSUE TITLE
MuseScore 3.6 Files with MuseJazz chords crash after attempting to Select All

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#17829]
### Issue type

Crash or freeze

### Bug description

MuseScore 3.6 Files with MuseJazz chords crash after attempting to Select All

Score and diagnostic files attached

I can also reproduce by selecting the first note and shift+click the end of the last bar
[GoTellItOnTheMountain copy.zip](https://github.com/musescore/MuseScore/files/11636030/GoTellItOnTheMountain.copy.zip)
[MuseJazz_3.6_Crash.zip](https://github.com/musescore/MuseScore/files/11636033/MuseJazz_3.6_Crash.zip)

### Steps to reproduce

1. Open the attached score
2. Edit > Select All

or select the first note and Shift + Select the end of the last bar (after the rest)

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231530303, revision: github-musescore-musescore-5745a86

### Regression

Choose option...

### Operating system

OS: macOS 11.6

### Additional context

I have reproduced this on 4.1 and the nightly.

I have reproduces this with similar files.

**Comment by MarcSabatella** [comment]
See also https://github.com/musescore/MuseScore/issues/17590; I suspect this is the same issue.

**Comment by zacjansheski** [comment]
The file on https://github.com/musescore/MuseScore/issues/17590 does not crash when I Select All

**Comment by bkunda** [comment]
Am I right in understand that, because this issue seems to have been fixed by #17895 it is related to the selection of the last measure in the score?
Just want to understand why it's been given a P3 if it's a crash. 
And if it is related to #17895, whether it's a recent regression that would warrant it being included in 4.1.1.

**Comment by zacjansheski** [comment]
It seemed at the time that the issue was targeted to these scores. It wasn't clear to me until https://github.com/musescore/MuseScore/issues/18549 that the problem was more widespread. 

The checks here seem to resolve https://github.com/musescore/MuseScore/issues/18549
