### ISSUE TITLE
Copying and pasting disables playback of subsequent notes and chords after voltas

### ISSUE THREAD

**Issue by theoneandonlytoasty** [musescore/MuseScore#17826]
### Issue type

General playback bug

### Bug description

This has happened to me several times in ms4, it seems that once my file reaches a certain size or amount of notes/information, copying and pasting any notes will disable playback of all notes

### Steps to reproduce

i got it on video [https://youtu.be/BNyT47e4GYs](https://youtu.be/BNyT47e4GYs)

### Screenshots/Screen recordings

see above

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651546, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in MuseScore 3.x and now is broken (it has never been an issue until I started noticing it in march or april of this year)

### Operating system

macOs 13.1

**Comment by zacjansheski** [comment]
I have not been able to reproduce this.  Would you be willing to share a score in which you experience the issue?  (You can share here as a .zip file)

If not, could you provide more details?  How large is the score?  What instruments/settings are you using?

**Comment by zacjansheski** [comment]
Reproduced in 4.0.2 and nightly.  I think this does not have to do with score size, but with the 1st/2nd voltas.   Deleting the voltas seems the problem.
