### ISSUE TITLE
Adding "cresc" to part leads into crash

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#17839]
### Issue type

Crash or freeze

### Bug description

Adding line dynamics ("cresc", "dim", hairpins) to part leads into crash.

### Steps to reproduce

1. open parts
2. add dynamics - "cresc"
3. see crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1646034/c23bd84e-e2d6-49fb-aad6-6a1fb92af3f5

### MuseScore Version

4.1 master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 22.04

**Comment by zacjansheski** [comment]
Recreated on Mac OS on Nightly
[17839Crash.zip](https://github.com/musescore/MuseScore/files/11652393/17839Crash.zip)
