### ISSUE TITLE
Cannot enter special characters in expression text

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#17834]
### Issue type

Choose option...

### Bug description

In the current nightly build on MacOS I am unable to insert special characters in expression text.

### Steps to reproduce

1. Create a new score
2. Add expression text
3. Try to add Special Character (in Properties panel)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/2bfe960e-739f-46f5-818c-13185e0edb3c

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231530303, revision: github-musescore-musescore-5745a86

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: macOS 11.6

**Comment by MengLinMaker** [comment]
Replicated problem on Linux

### MuseScore Version
b443bf7

### Operating system
Linux: Ubuntu 20.04
