### ISSUE TITLE
MusicXML import and export - Tie position above/below doesn't save in musicxml

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#17841]
### Issue type

Other type of issue

### Bug description

This is musescore file (both slur and tie explicitly positioned "below")
![image](https://github.com/musescore/MuseScore/assets/919446/d1b61b57-e10c-4d29-8059-9367660fdad3)

This is musicxml exported and opened in Musescore:
The position for slur saved correctly, but not for tie
![image](https://github.com/musescore/MuseScore/assets/919446/01d78f65-f54f-4a36-a946-bf1c53bb1b07)

If I open exported musicxml in text editor, there is "placement" attribute in slur element:
```xml
<slur type="start" placement="below" number="1"/>
```
and it's missing on tied element:
```xml
<tied type="start"/>
```
If I add placement attribute to the tied element, Musescore still cannot recognize it and will keep tie auto positioned.

### Steps to reproduce

1. Add two notes with a tie.
2. Change tie position
3. Export file to musicxml format
4. Open musicxml

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231462149, revision: github-musescore-musescore-2be9061

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009

**Comment by Jojo-Schmitz** [comment]
Export should be simlpe:
'''cpp
diff --git a/src/importexport/musicxml/internal/musicxml/exportxml.cpp b/src/importexport/musicxml/internal/musicxml/exportxml.cpp
index 075c7f3aae..f6becfef36 100644
--- a/src/importexport/musicxml/internal/musicxml/exportxml.cpp
+++ b/src/importexport/musicxml/internal/musicxml/exportxml.cpp
@@ -3834,7 +3834,7 @@ void ExportMusicXml::chord(Chord* chord, staff_idx_t staff, const std::vector<Ly
         if (tieFor && ExportMusicXml::canWrite(tieFor)) {
             notations.tag(_xml, tieFor);
             QString rest = slurTieLineStyle(tieFor);
-            _xml.tagRaw(QString("tied type=\"start\"%1").arg(rest));
+            _xml.tagRaw(QString("tied type=\"start\%1 placement=\"%2\"").arg(rest).arg(tieFor->up() ? "above" : "below"));
         }
         const Articulation* laissezVibrer = findLaissezVibrer(chord);
         if (laissezVibrer && ExportMusicXml::canWrite(laissezVibrer)) {
'''

**Comment by Jojo-Schmitz** [comment]
Time import does have this code:
```cpp
        if (orientation == "over") {
            tie->setSlurDirection(DirectionV::UP);
        } else if (orientation == "under") {
            tie->setSlurDirection(DirectionV::DOWN);
        } else if (orientation == "auto") {
            // ignore
        } else if (orientation == "") {
            // ignore
        } else {
            logger->logError(QString("unknown tied orientation: %1").arg(orientation), xmlreader);
        }
```

**Comment by Jojo-Schmitz** [comment]
So this change should fix it:
```cpp
diff --git a/src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp b/src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
index 9daef3c31f..72a1382d8a 100644
--- a/src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
+++ b/src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
@@ -6163,6 +6163,7 @@ static void addTie(const Notation& notation, Score* score, Note* note, const tra

     const QString& type = notation.attribute("type");
     const QString& orientation = notation.attribute("orientation");
+    const QString& placement = notation.attribute("placewment");
     const QString& lineType = notation.attribute("line-type");

     if (type == "") {
@@ -6188,6 +6189,22 @@ static void addTie(const Notation& notation, Score* score, Note* note, const tra
             logger->logError(QString("unknown tied orientation: %1").arg(orientation), xmlreader);
         }

+        if (placement == "abobe") {
+              tie->setSlurDirection(DirectionV::UP);
+        }
+        else if (orientation == "below") {
+              tie->setSlurDirection(DirectionV::DOWN);
+        }
+        else if (orientation == "auto") {
+              // ignore
+        }
+        else if (orientation == "") {
+              // ignore
+        }
+        else {
+              logger->logError(QString("unknown tied placement: %1").arg(placement), xmlreader);
+        }
+
         if (lineType == "dotted") {
             tie->setStyleType(SlurStyleType::Dotted);
         } else if (lineType == "dashed") {
```

**Comment by Jojo-Schmitz** [comment]
See https://github.com/musescore/MuseScore/pull/17842

**Comment by Jojo-Schmitz** [comment]
#19132 will be fixing this too, looks like a better and more complete alternative to my #17841
