### ISSUE TITLE
Plugin to break a system in the middle of a measure

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#17855]
### Your idea

It would be awesome to get a plugin - compatible with MU3 & 4 - 
which instantly breaks a system in the middle of a measure,
with all necessary steps combined into one command:

1. split measure
2. hide all barline segments
3. apply system break
4. exclude second half of the measure from bar count 

### Problem to be solved

Breaking a system in the middle of a measure takes several steps in MU 3 & 4
and their number increases with every stave in the score. 
In Sibelius, the same task can be performed in one step, compare:

https://github.com/musescore/MuseScore/assets/78870770/64c98921-5eb0-4d6f-8e2e-97aaf8ad07f3

PS: I used MU3 for demonstration, but it works the same way in MU4.

### Additional context

I would highly appreciate if someone would be willing
program such a plugin and make it also compatible to MU3.
I can't judge on how difficult this would be...
Out of interest: Maybe someone could comment on how many hours 
of effort it would approximately take to program such a plugin.

**Comment by oktophonie** [comment]
Better to implement as a 'real' feature than a plugin; i.e. it should be possible to place a system break anywhere (within reason), not just on a barline.
With that come many questions though, like what to do a bout notes that span the break, how it affects bar number placement, etc. etc.

**Comment by oMrSmith** [comment]
For me the result you get in MU using the workaround is satisfying - just that it takes many steps. Maybe it could become a second version of the "split bar" tool. If so #15487 could relate... But I can also understand if you would prefere to go the kings way ;).

**Comment by XiaoMigros** [comment]
Adding native support would probably take quite a while and I'm going to assume it's not of highest priority at the moment. I [wrote a plugin](https://github.com/XiaoMigros/System-Spacing-Tools) to do it in the meantime, like you wanted (MU3 and MU4 compatible).

**Comment by oMrSmith** [comment]
Wow! Thank you so much! <3 This saves me a lot of time and from what I have instantly tested, it works very well: Like even when adding instruments afterwards, the entire barline remains hidden...

**Comment by Jojo-Schmitz** [comment]
> Adding native support would probably take quite a while and I'm going to assume it's not of highest priority at the moment. I [wrote a plugin](https://github.com/XiaoMigros/System-Spacing-Tools) to do it in the meantime, like you wanted (MU3 and MU4 compatible).

Mind to publish that on https://musescore.org/en/node/add/project_project ?

**Comment by XiaoMigros** [comment]
Oh, it seems I have yet to do it for this set of plugins. Thanks for the reminder ;)
