### ISSUE TITLE
Large Scores Crashing when deleting multiple instruments

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#17859]
### Issue type

Crash or freeze

### Bug description

Large scores crashing when deleting multiple instruments.

This is in the nightly build.

MS 4.0.2 does not crash when performing this same task (but does take a while)

### Steps to reproduce

1. Open a large score (I will provide examples in additional context)
2. Select 4+ instruments in the instruments panel
3. Delete (trash can button)

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231560305, revision: github-musescore-musescore-12e5d3f

### Regression

Choose option...

### Operating system

OS: macOS 11.6

### Additional context

[Mozart_-_Mvt1_Symphony_No._41_-_Jupiter copy.zip](https://github.com/musescore/MuseScore/files/11655353/Mozart_-_Mvt1_Symphony_No._41_-_Jupiter.copy.zip)
[Mvt 4_Beethoven__Symphony_No._9__Op._125 copy.zip](https://github.com/musescore/MuseScore/files/11655359/Mvt.4_Beethoven__Symphony_No._9__Op._125.copy.zip)

**Comment by cbjeukendrup** [comment]
From what I caught in the debugger, this seems to be related to ornaments. There is an assertion failure, and when I disable that assertion, there is a crash. @mike-spa FYI :)
