### ISSUE TITLE
Trill is played as tremolo when 2 or more notes are under the trill (MS Basic, Midi render)

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#17867]
### Issue type

Other type of issue

### Bug description

Reproducible only with MS Basic and Midi render. Sounds ok with MuseSounds

### Steps to reproduce

1. Open the score [trill.mscz.zip](https://github.com/musescore/MuseScore/files/11662831/trill.mscz.zip)
2. Play it
3. Pay attention to group with three notes

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/101250347/e284fd24-25aa-4092-89cd-8c83c055b144

### MuseScore Version

MuseScore 4.0.2 

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 13

**Comment by bkunda** [comment]
@abariska does this problem persist if the notes are tied under the trill line?

**Comment by abariska** [comment]
Yes. Same issue for tied notes

**Comment by bkunda** [comment]
Yeah you're right. I also had this similar problem:

https://github.com/musescore/MuseScore/assets/86290556/f538d99f-764b-476b-8d30-f69c06cbceb1

**Comment by bkunda** [comment]
I'm just bumping the priority on this as it's related to an important new feature, and it's a reasonably common thing to want to do.

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 13, Win 11, Ubuntu 20
