### ISSUE TITLE
Gradual tempo changes like accelerando and ritardando don't seem to affect long notes, causing them to either end early with rit. or sustain a bit into the next measure with accel.

### ISSUE THREAD

**Issue by BoBogus** [musescore/MuseScore#17863]
### Issue type

General playback bug

### Bug description

This only seems to happen to notes within the period that the tempo is changing — everything is perfectly normal on the measure after the tempo changes. I have attached a file showing the issue using short notes on cellos and long notes on violas (although this seems to apply to any sustaining instrument).

It seems that the software calculates the length the note should play based on the original tempo, without factoring in how that time is stretched or contracted by the change in tempo. This would also account for why short notes still work fine — any such miscalculation is too small to notice.

### Steps to reproduce

All that's necessary is to add an accelerando or ritardando with a large tempo change (I used 50% and 200% in my demo file).  Then long notes should be affected as described.

### Screenshots/Screen recordings

I have an example score that showcases the issue.  As you should hear, the cellos (which are playing short notes) never seem to lag or rush at the second measure of each tempo change, but the viola notes (which are long) do.

The score is at https://drive.google.com/file/d/1eMTeMMRHk5VCxzyq6-5ZRf3LnMCjsfVw/view?usp=sharing

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

No.

### Operating system

Windows 10 Version 2009, Arch.: x86_64 (64-bit)

### Additional context

While this issue appears to apply to all three sound engines, it seems to be worst on Muse Sounds.

**Comment by cbjeukendrup** [comment]
Long ago, I made a start at fixing this: https://github.com/musescore/MuseScore/pull/15609 but it is not quite trivial

**Comment by BoBogus** [comment]
If you watch the tempo indicator on the upper left corner, you'll notice it doesn't gradually change, but rather changes every quarter note. I just realized that it I could use that to my advantage by breaking a problematic half note into two tied quarter notes. The interpretation is musically the same, but the software ends up calculating it properly so the note stops in time. Try splitting the whole notes in the viola track in the demo file I sent, and you'll hear the difference. Even just breaking up the whole notes into a dotted half note tied to (and followed by) a quarter note fixed the issue.

So a potential solution (at least, until something more elegant can be discovered) could be for the software to automatically treat long notes as a chain of tied notes no longer than a quarter, whenever they occur within a tempo change (unless the necessary calculations are memory inefficient).
