### ISSUE TITLE
Trouble compiling with arm64 mac

### ISSUE THREAD

**Issue by ryan-mooore** [musescore/MuseScore#17873]
### Issue type

Other type of issue

### Bug description

I have tried to compile from source, following the [wiki entry](https://github.com/musescore/MuseScore/wiki/Compiling-on-Macs-with-Apple-Silicon) exactly for compiling on Apple Silicon. However, libsndfile does not seem to be able to be found during compilation, despite following all steps. Apologies if I am missing something obvious as I am fairly new to building from source like this.

`./build.cmake`:
```
...
[ 37%] Built target context
/Users/ryan/Programming/prs/MuseScore/thirdparty/fluidsynth/fluidsynth-2.1.4/src/sfloader/fluid_sffile.c:30:10: fatal error: 'sndfile.h' file not found
#include <sndfile.h>
         ^~~~~~~~~~~
[ 37%] Built target shortcuts
[ 37%] Automatic MOC and UIC for target diagnostics
/Users/ryan/Programming/prs/MuseScore/thirdparty/fluidsynth/fluidsynth-2.1.4/src/bindings/fluid_filerenderer.c:30:10: fatal error: 'sndfile.h' file not found
#include <sndfile.h>
         ^~~~~~~~~~~
1 error generated.
1 error generated.
make[2]: *** [src/framework/audio/fluidsynth/CMakeFiles/fluidsynth.dir/fluidsynth-2.1.4/src/bindings/fluid_filerenderer.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/framework/audio/fluidsynth/CMakeFiles/fluidsynth.dir/fluidsynth-2.1.4/src/sfloader/fluid_sffile.c.o] Error 1
make[1]: *** [src/framework/audio/fluidsynth/CMakeFiles/fluidsynth.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 37%] Built target converter
[ 37%] Built target rtf2html
[ 38%] Built target beatroot
[ 38%] Built target diagnostics_autogen
[ 38%] Built target learn
[ 38%] Built target languages
make: *** [all] Error 2
```
`cat build_overrides.cmake`:
```
set(ENV{QTDIR} "$ENV{HOME}/Qt/5.15.2/clang_64")
set(ENV{PATH} "/usr/local/bin:$ENV{PATH}")
```
`/usr/local/bin/brew list -1`:
```
==> Formulae
flac
lame
libogg
libsndfile
libvorbis
mpg123
opus
pkg-config
```

NB: I also tried switching the `MUE_COMPILE_BUILD_MACOS_APPLE_SILICON` CMake flag on as mentioned in #15785 , but this didn't seem to make any difference. Regardless, I feel like this flag should be definitely be mentioned somewhere in the wiki for compiling for Apple Silicon.

### Steps to reproduce

1. Follow exact steps on wiki for [Compiling on Macs with Apple Silicon](https://github.com/musescore/MuseScore/wiki/Compiling-on-Macs-with-Apple-Silicon)

### MuseScore Version

4.1.0

### Regression

I don't know

### Operating system

MacOS Ventura 13.2.1

**Comment by bkunda** [comment]
@Eism could you please advise on this one?

**Comment by Eism** [comment]
I'm not sure what the problem is, as everything seems to be working fine for me.
@ryan-mooore I can recommend reinstalling libsndfile:
```
brew uninstall --force libsndfile
brew install libsndfile
```

**Comment by ryan-mooore** [comment]
Unfortunately still failing for me. To clarify, libsndfile should be installed under the intel version of brew only (`arch -x86_64 /usr/local/bin/brew`), not ARM version (`brew`), correct? This is what is stated in the wiki. So after running (`arch -x86_64 /usr/local/bin/brew uninstall --force libsndfile` and reinstalling, this is still failing.

**Comment by ryan-mooore** [comment]
Same issue with earlier releases as well

**Comment by cbjeukendrup** [comment]
Oh, sorry, indeed, in this screenshot I'm using the arm64 version because I'm doing some experimental stuff with native compilation for Apple Silicon. 

What you have is correct. And if you go to `/usr/local/Cellar/libsndfile/1.2.0_1/include` in Finder, do you indeed see the two sndfile.h files there?

**Comment by ryan-mooore** [comment]
After deleting all folders inside **builds**, I was able to compile no problems 🤦 - I don't know why I hadn't thought this would be an issue earlier, but I assumed files in **builds** would be overwritten. However, it seems like the existing failed builds in this folder were affecting my 'new' builds - is this indented behaviour? If so, feel free to close this issue!

I managed to build both using the dual homebrew installation and also natively using the `MUE_COMPILE_BUILD_MACOS_APPLE_SILICON` flag. Should I update the wiki to document building natively?

**Comment by cbjeukendrup** [comment]
@ryan-mooore Normally files in `builds` are indeed overwritten, but sometimes this fails indeed, and then you need to clean things up manually. 

It would be great if you could update the Wiki. I have already added an introduction at the top of the page to mention the different possibilities, but it would be great if you could fill in the details: https://github.com/musescore/MuseScore/wiki/Compiling-on-Macs-with-Apple-Silicon#compiling-in-arm64-mode

**Comment by ryan-mooore** [comment]
@cbjeukendrup I have basically rewritten the entire page for compiling with apple silicon after my personal experience trying to read it, it should be much clearer right now. I've recommended most users go with the native method with the `MUE_COMPILE_BUILD_MACOS_APPLE_SILICON` flag, but not sure whether this is actually what you would be recommending at this stage. Feel free to take out/change the recommendation.

**Comment by cbjeukendrup** [comment]
@ryan-mooore Thanks a lot! I've read through it and it looks good to me. I think all aspects of this issue have been resolved now, right?

**Comment by ryan-mooore** [comment]
Yep all good 👍
