### ISSUE TITLE
Playback has different pitch when switching between audio devices (in Preferences) with different sample rate during one session

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17877]
### Issue type

General playback bug

### Steps to reproduce

1. Make sure your two audio devices connected have different sample rate (e.g. 44 and 48 kHz)
2. Run MU
3. Check playback
4. Go to Preferences>I/O>Audio device
5. Switch to another audio device
6. Check playback - **playback has different pitch** 

### Screenshots/Screen recordings

I have external **Audient iD14 with 44kHz**
![iD44](https://github.com/musescore/MuseScore/assets/90187801/0677a940-963e-471f-a5d9-cf8681a49543)

and internal **Realtek with 48kHz**

![Realtek48](https://github.com/musescore/MuseScore/assets/90187801/ee010bc8-f960-4ebc-a11e-c7a5063ce17f)

### MuseScore Version

4.1

### Regression

No. In MS3 changing between audio devices during one session doesn't work

### Operating system

Windows10

### Additional context

After MU restart all good

**Comment by DmitryArefiev** [comment]
There are two kind of fixes could be here:
1. Correct switching of playback sample rate in real time
2. Show a message to user to restart MU (if sample rate of new device is different)

**Comment by DmitryArefiev** [comment]
Also might happen when switching between internal audio and bluetooth headphones (see #19223)

**Comment by optimizasean** [comment]
Adding to this - it appears to fail on any resolution other than 44.1khz 24bit. Playback speed and pitch are approximate to the sample rate (higher than MU it plays shorter and higher pitch, lower than MU it plays slower and lower pitch).

Requires control of soundcard (cannot function with external soundcards unless Windows can override playback settings for them .*Note: careful may cause issues with other usage of your device including crashing apps, playback failure or issues, general device issues, ... and same goes for other soundcards and playback devices*

Very difficult to identify this was as a specific known bug and that no fix is available as of yet in any version. Happens 100% of the time with MU4 (latest main as of now) in Windows 10/11. Tested across multiple external soundcards and headsets (many do not have the ability to run in other sample rates or are not configurable). In general, having to run your soundcard manually at other sample rates is not desired behavior for any user as it interferes with many other software and their audio playback including browsers/YouTube/... commonly used with MuseScore (like when transcribing or exporting play-along tracks or using other plugins/sound fonts/....).

**Comment by optimizasean** [comment]
I am not too familiar with audio at the playback level in MuseScore - is a potential stopgap measure (or solution) to have a way to scale the playback of the output? If you could either set default as is or detect the soundcard settings and match, then allow further scaling based on a dropdown menu, could this be achieved through existing audio libraries or internal to MuseScore?

I have found some existing forum posts using [Jack](https://jackaudio.org/) to manage audio routing to get around this but it would be ideal to have this ability built in (either as scaling or routing - not sure which is better implementation or difficulty wise).

**Comment by DmitryArefiev** [comment]
> There are two kind of fixes could be here:
> 
>     1. Correct switching of playback sample rate in real time
> 
>     2. Show a message to user to restart MU (if sample rate of new device is different)


@bkunda What about to try implement **№2** in 4.4 release? (it's easier than №1)

**Comment by DmitryArefiev** [comment]
Fixed in #23954

With MuseSounds playback and audio export, should be used sampler v0.100.0.303 or later
