### ISSUE TITLE
[MU4 Task] Remove Parts and add Share on Audio.com in File menu

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17872]
### Task description

Since **Share on Audio.com** is our new feature and it's available on Publish tab together with **Publish to MuseScore.com** and **Export** options,  it should be added to File menu as well

### Actual result:
![Untitled](https://github.com/musescore/MuseScore/assets/90187801/bcb7e9ec-2095-4a41-9f99-d82b5002b1bd)

### Expected result:
- Remove **Parts** from File menu
- Add **Share on Audio.com...** option beneath **Export...**

<img width="400" alt="Screenshot 2023-06-06 at 2 22 09 pm" src="https://github.com/musescore/MuseScore/assets/86290556/21666e33-1725-477e-ba6c-3cedcdbec484">

**Note** the icon in Windows should be the same as for the current option in the **Publish** tab, i.e.:

<img width="178" alt="Screenshot 2023-06-06 at 2 30 23 pm" src="https://github.com/musescore/MuseScore/assets/86290556/0c675e25-bf71-45ff-8740-50d8e95af2e7">

**Comment by DmitryArefiev** [comment]
@HemantAntony Thanks! All good

**Comment by DmitryArefiev** [comment]
Implemented in #17875

**Comment by Jojo-Schmitz** [comment]
Why removing Parts?? How not to generate, control, remove, reset parts?

**Comment by HemantAntony** [comment]
You can just click the "Parts" button directly, instead. It doesn't remove the dialog. It just removed the option from File Menu

**Comment by Jojo-Schmitz** [comment]
I see. But why??

**Comment by bkunda** [comment]
@Jojo-Schmitz because we are adding "Share on Audio.com...", which increases the size of the File menu – which is already bloated with too many options to save your file. Removing "Parts" (which is redundant anyway) saves on space and improves comprehensibility by reducing the number of available options.

**Comment by Jojo-Schmitz** [comment]
Hmm, OK... however, I disagree on this. File > Parts is where I expect this

**Comment by cbjeukendrup** [comment]
I would agree with @Jojo-Schmitz that the Parts dialog is somehow something I would expect in some menu. 

However, in the future, the parts dialog will not be a dialog but a pop-up. Then, it should not be in a menu anymore. So let's leave it like it has become now.

**Comment by Tantacrul** [comment]
I've always thought having an option to expose parts in the main file menu is bizarre. I don't see why it should go under 'file' specifically.

If we want it in the top menu, I'd suggest a different placement, like 'view'

**Comment by MarcSabatella** [comment]
FWIW, I suspect it was in File as a holdover when MuseScore *1* when parts were stored in separate files and not linked.  I agree View is better now.

In general, I like to see most things in menus for accessibility reasons.  Toolbar buttons take more work and thought to access via keyboard, and defining a custom shortcut for this shouldn't be needed just to access the functionality.  Plus the shortcut definition dialog is not accessible itself.
