### ISSUE TITLE
Custom trill, small notes move to new staff when an instrument is added above

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#17880]
### Issue type

Engraving bug

### Bug description

Custom trill, small notes move to new staff when an instrument is added above.  Please see video.

### Steps to reproduce

1. Create a trill with a custom note in the properties panel
2. Add an instrument that goes above the instrument with the trill

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/fc530227-5d1d-4149-a9c4-3403f2561503

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231570309, revision: github-musescore-musescore-279de6d

### Regression

Choose option...

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
Same behavior on Mac OS

**Comment by DmitryArefiev** [comment]
The same as #17771 and was fixed in #17775
