### ISSUE TITLE
problem with piano keyboards

### ISSUE THREAD

**Issue by krutpik** [musescore/MuseScore#17894]
### Your idea

Hello, in version 3 of the program, during playback, on the piano keys panel, you could see which keys are pressed, why is this not in the new version?

### Problem to be solved

.

### Prior art

.

### Additional context

.

**Comment by krutpik** [comment]
> ### Your idea
> 
> Hello, in version 3 of the program, during playback, on the piano keys panel, you could see which keys are pressed, why is this not in the new version?
> ### Problem to be solved
> 
> .
> ### Prior art
> 
> 
> ### Additional context
> 
> .

**Comment by Jojo-Schmitz** [comment]
Duplicate of #14428
