### ISSUE TITLE
Small staff in multi-staff instrument leads to incorrectly resized instrument name

### ISSUE THREAD

**Issue by mmeyn** [musescore/MuseScore#17891]
### Issue type

Engraving bug

### Bug description

This happens only when resizing the uppermost staff of a multi-staff instrument (f. e. right hand of a keyboard instrument).

This scenario is used in Basso Continuo parts for an editorial realization of the BC figures.

### Steps to reproduce

1. Create a new score with a keyboard instrument and at least another instrument.
2. Resize the upper staff of the keyboard instrument to small staff.

### Screenshots/Screen recordings

![grafik](https://github.com/musescore/MuseScore/assets/7814361/95cca886-996f-48c0-91e8-39a8c979eceb)

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

Linux

**Comment by mmeyn** [comment]
Oh, I didn’t say what I expected as correct behaviour: The instrument name of the Cembalo should be the same as Traversflöte, i. e. the font size should match the default staff size whenever there is at least one default sized staff (only when all staves of an instrument are small, the instrument name might be scaled down).

**Comment by mmeyn** [comment]
The `InstrumentName` of a multi-staff instrument is not a property of the `Part` but of the first `Staff`. In `SystemLayout::layoutInstrumentNames` it is moved to the first _visible_ `SysStaff`. I tried to move it to the first `SysStaff` that is both visible and the corresponding `Staff` is not `Pid::SMALL` but that’s not sufficient because then it’s placed incorrectly.

**Comment by Jojo-Schmitz** [comment]
Same issue in Mu3
