### ISSUE TITLE
Crash when open 4.0.2 score with MuseSounds in 4.1 (one score)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17901]
### Issue type

Crash or freeze

### Steps to reproduce

1. MuseSounds should be installed
2. Open [Symphony N4 M1_1111.zip](https://github.com/musescore/MuseScore/files/11688338/Symphony.N4.M1_1111.zip)

### Screenshots/Screen recordings

I created that score in **4.0.2** from full score [Symphony.N4.M1.zip](https://github.com/musescore/MuseScore/files/11688348/Symphony.N4.M1.zip):

https://github.com/musescore/MuseScore/assets/90187801/94fdf95b-c919-4728-a24f-e3b0b276fb6a

### MuseScore Version

4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows10

### Additional context

The initial full score [Symphony.N4.M1.zip](https://github.com/musescore/MuseScore/files/11688348/Symphony.N4.M1.zip) **opens fine in 4.0.2 and 4.1**

**Comment by DmitryArefiev** [comment]
@bkunda I was not able to reproduce the crash using other 4.0.2 score or creating a new score in 4.0.2 with MuseSounds

**Comment by cbjeukendrup** [comment]
It turns out that https://github.com/musescore/MuseScore/issues/18155 is probably the same crash, so apparently it is not entirely specific to this score.

**Comment by DmitryArefiev** [comment]
Fixed in #18273
