### ISSUE TITLE
Adding an instrument crashes MS

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#17908]
### Issue type

Crash or freeze

### Bug description

Adding a transposing instrument crashes MS

This occurs in the nightly, not 4.0.2

### Steps to reproduce

1. Create a score
2. Add a instrument (or use "replace instrument")

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231590306, revision: github-musescore-musescore-43fb654

### Regression

Choose option...

### Operating system

Mac OS and Windows 11

### Additional context

[TransposingInstrumentCrash.zip](https://github.com/musescore/MuseScore/files/11693172/TransposingInstrumentCrash.zip)

**Comment by DmitryArefiev** [comment]
On my side (Win10) it happens when adding **any instrument** (also crash occurs when **replace instrument**)


https://github.com/musescore/MuseScore/assets/90187801/675bac0e-f513-4f69-8119-d8fe8a8c4758

**Comment by DmitryArefiev** [comment]
Fixed in #17918
