### ISSUE TITLE
Stringendo causes playback to misbehave

### ISSUE THREAD

**Issue by Panogen** [musescore/MuseScore#17909]
### Issue type

General playback bug

### Bug description

The string. marking found in the Tempo palette causes some notes to sustain longer than they should, and even play back when they shouldn't. This seems to happen when a tempo marking is used after 'string.' During playback, the notes just before the tempo marking continue to sustain even after the next measure has started. When playing back directly from 'a tempo', the notes play even though they aren't there in the measure. The problem goes away when the stringendo is removed.

### Steps to reproduce

Apply 'string.' from the Tempo palette. In a separate measure, set the tempo to any value.

*This will produce the same effect seen in my screen recording. Note that the "before" and "after" tempos don't have to be the same.*
![image](https://github.com/musescore/MuseScore/assets/73259774/54813b79-b19f-4622-b5c9-e0303b9f3352)

### Screenshots/Screen recordings

In addition to the inappropriate sustain, I noticed that the notes in the third chord in measure 18 are played out of sync, but only when 'string.' is present.

https://github.com/musescore/MuseScore/assets/73259774/6d325386-bfc7-41cb-9829-bd40ccc700a2

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 11

### Additional context

[MuseScore project from the screen recording](https://github.com/musescore/MuseScore/files/11698872/6-8-23.zip)
The problem appears in mm. 18-20.

**Comment by DmitryArefiev** [comment]
Thanks for logging!

It's the same as #14369 (I close the current issue)

> In addition to the inappropriate sustain, I noticed that the notes in the third chord in measure 18 are played out of sync, but only when 'string.' is present.

This I logged separately #17915 (MuseSounds only issue)
