### ISSUE TITLE
Opening parts, then returning to score, score is zoomed in very far

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#17906]
### Issue type

UI bug

### Bug description

Opening parts, then returning to score, score is zoomed in very far

This is in the nightly build, not in 4.0.2

### Steps to reproduce

1. Open a score
2. Open a part
3. Return to score

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/8771478f-6cb9-4309-9b5c-d72454a9a079

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231590306, revision: github-musescore-musescore-43fb654

### Regression

Choose option...

### Operating system

Mac OS and Windows

**Comment by sammik** [comment]
Also going to other parts causes zoom.
If any tab (score or part) is clicked again, it is zoomed to 357%
1. open score with parts
2. open part 1
3. open part 2
4. open part 1 - see zoomed

**Comment by DmitryArefiev** [comment]
Fixed in #18138
