### ISSUE TITLE
Adding instrument to score with custom key signature casues crash

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#17911]
### Issue type

Crash or freeze

### Bug description

Adding instrument to score containing custom key signature casues crash

### Steps to reproduce

1. add custom key signature to score
2. add instrument
3. see crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1646034/3106efcf-2c4b-4261-848b-172abbcd78ce

### MuseScore Version

4.1 master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 22.04

### Additional context

Works in 4.0.2. Crash in master.

May be related to #17908

**Comment by DmitryArefiev** [comment]
Fixed in #17918
