### ISSUE TITLE
Change instrument causes crash

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#17928]
### Issue type

Crash or freeze

### Bug description

In the attached score changing the electric bass to an acoustic bass causes the program to freeze and crash.

Note: This did not happen with the last official release ((64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d).

### Steps to reproduce

1. Open the attached score. 
[crash_change_instrument.zip](https://github.com/musescore/MuseScore/files/11712196/crash_change_instrument.zip)
2. Right-click on the first measure of the Bass staff (Bs.) and select "Staff/Part Properties"
3. Press "Change instrument"
4. Choose Strings - Plucked > Acoustic Bass.
5. Press OK twice.

RESULT: Program freezes then crashes.

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231610304, revision: github-musescore-musescore-644a78d

### Regression

Yes, this used to work in a previous version of MuseScore 4

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64

**Comment by sammik** [comment]
Looks like duplicate https://github.com/musescore/MuseScore/issues/17908#issuecomment-1584461908_
Isn't it fixed by #17918 too?

**Comment by DmitryArefiev** [comment]
Yes, it's duplicate and should be fixed by #17918 (in progress)

Thanks for point it out!
