### ISSUE TITLE
[Accessibility] Palettes "More" and Instruments panel "Settings" not spoken by screen readers

### ISSUE THREAD

**Issue by msviolafangirl** [musescore/MuseScore#17922]
### Issue type

UI bug

### Bug description

This issue highlights a few dialogs which are completely unusable by screen reader users. When opening those dialogs, screen readers announce nothing, and pressing the arrow or tab keys to navigate announces nothing. Tested with Windows and NVDA but likely an issue with other screen readers as well.

### Steps to reproduce

With screen reader enabled:
1. Navigate to a palette e.g clefs, time signatures, dynamics, etc.
2. Navigate down until you get to the more button.
3. Press enter to activate the More button.

And
1. Go to instruments panel.
2. Locate an instrument.
3. Press right arrow a few times to locate the settings button.
4. Press enter to activate.

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
On Linux, you *can* navigate by keyboard (Tab gets you there), but Orca does read anything.

**Comment by zacjansheski** [comment]
Orca is reading the options in more tab and add and instruments settings for me. Ubuntu 20.04.6

**Comment by zacjansheski** [comment]
Also see similar issue with "Add Palette" window https://github.com/musescore/MuseScore/issues/16744

Works as desired on MacOS with VoiceOver

**Comment by msviolafangirl** [comment]
Yep, I'm on Windows with NVDA/Narrator, glad it's working ok on Mac and Linux though.

**Comment by msviolafangirl** [comment]
Update: this issue is no longer a serious problem, and it seems to be fixed. When I try to add a new palette or access the instrument settings screen, I still have to press NVDA+R to bring up screen OCR, and then press escape in order to get NVDA to respond when I arrow through the options. In the instrument settings dialog, it would be good if I could tab through the options instead of arrow, as arrow keys are used to navigate editable text. There should probably be a new issue for this.
