### ISSUE TITLE
multi measure bug

### ISSUE THREAD

**Issue by principaltpt** [musescore/MuseScore#17920]
### Issue type

Engraving bug

### Bug description

multi measure rests don't center

### Steps to reproduce

Change multi measure widths to produce skinnier H bars. Some measures center between the barlines while others default to the left barline. Furthermore, if I choose to move the milti measure rest number down to split the rest symbol, not all rests actually split to show the number.
![IMG_0374](https://github.com/musescore/MuseScore/assets/136114383/39d9505b-74a1-481c-b6e6-cf0d7f087d16)

### MuseScore Version

latest version 4.0.2

### Regression

I don't know

### Operating system

windows 10

**Comment by oktophonie** [comment]
Closing in favour of the duplicate https://github.com/musescore/MuseScore/issues/17941
