### ISSUE TITLE
Disastrous-looking assertion failure when pressing backspace repeatedly in note entry mode in second voice

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#17930]
### Issue type

Choose option...

### Steps to reproduce

1. Enter some notes in voice 2 (or other non-first), and don't exit note entry mode yet
2. press backspace repeatedly

The results are a bit strange: sometimes nothing happens, sometimes it moves the cursor, sometimes it selects a note or rest, sometimes it deletes a note or rest.

In debug builds, an assertion failure occurs, saying that we're trying to remove a Segment from a SegmentList that is not in that SegmentList. 

When I disable this assertion (like in a release build), another assertion failure is hit, and that one is basically saying that the doubly-linked-list structure of a SegmentList is getting corrupted. That sounds a bit worrying. I've not yet had it really crash, but this certainly seems a bit worrying.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/48658420/e4d12a3f-bb1e-462c-8a9c-cbeb17ca6f11

### MuseScore Version

at least master

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 13

**Comment by Jojo-Schmitz** [comment]
No assertion failures do get logged in 4.0.2 (they won't crash there), so I guess it is a regression vs. 4.0?

**Comment by Jojo-Schmitz** [comment]
OTOH I can't reproduce it in latest master either...

**Comment by Jojo-Schmitz** [comment]
Actually I can, but only with master, not with 4.0.2

**Comment by Jojo-Schmitz** [comment]
Ah, I see, that code is nopt activa at all in a release build:
```cpp
void SegmentList::remove(Segment* e)
{
#ifndef NDEBUG
    check();
    bool found = false;
    for (Segment* s = _first; s; s = s->next()) {
        if (e == s) {
            found = true;
            break;
        }
    }
    if (!found) {
        ASSERT_X(String(u"segment %1 not in list").arg(String::fromAscii(e->subTypeName())));
    }
#endif
```

**Comment by Jojo-Schmitz** [comment]
That code is in there since 2016, 32c3100f, so unlikely a 3.6 regression

**Comment by cbjeukendrup** [comment]
It is a regression since MS3 in the sense that in MS3 the backspace key did something different.  

Indeed, these checks are only active in debug mode, but the problems which they are about do occur in release builds.

**Comment by Jojo-Schmitz** [comment]
I see. I guess this came up as part of your investigations reg. #17557.

**Comment by cbjeukendrup** [comment]
Surprisingly, I can't reproduce this anymore. I've no idea what change might have fixed it, but anyway, it's fixed.
