### ISSUE TITLE
Musescore Modern no. 20

### ISSUE THREAD

**Issue by ThomasPlayz-tech** [musescore/MuseScore#17934]
### Issue type

Other type of issue

### Bug description

 I used modern no. 20 in this score but it turned out to be a font I don't really like. could you please fix this bug? thank you. Pc info: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 2.00 GHz, 8.00 GB (7.55 GB usable), 64-bit operating system, x64-based processor, Latest musescore 4 version. Example score: https://musescore.com/user/33851368/scores/11025094

### Steps to reproduce

I dont actually know how to code but maybe you developers could help.

### MuseScore Version

Latest version

### Regression

No.

### Operating system

AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 2.00 GHz, 8.00 GB (7.55 GB usable), 64-bit operating system, x64-based

**Comment by Jojo-Schmitz** [comment]
The problem seems to be that "Modern no. 20" is not available on musescore.com (most likely die to license issues, it is free for personal use, but not for commercial use), but apperantly gets replaced by "DejaVuSans".
The replacing in itselt are probably not the main problem (there's probably no other choice), but replacing a Serif font with a Sans font is... bad

**Comment by bkunda** [comment]
Thanks for this.
I think the best solution for the desktop app would actually be to alert the user to any incompatible fonts, and provide them with basic options to replace them. 
We will raise a task dedicated to this and then close this issue.

**Comment by oktophonie** [comment]
See: https://github.com/musescore/MuseScore/issues/17945

**Comment by ThomasPlayz-tech** [comment]
> Thanks for this. I think the best solution for the desktop app would actually be to alert the user to any incompatible fonts, and provide them with basic options to replace them. We will raise a task dedicated to this and then close this issue.

Welcome. please fix this in the new update. can you make a new update next two months, one months?

**Comment by cbjeukendrup** [comment]
The next update (4.1) is already in stabilisation phase (it will be released in less than a month), so we can't add any new features to it anymore. We will see if anyone has time to do it for the update after that.
