### ISSUE TITLE
Scores with possible corruptions opening as entirely blank in 4.1 or later

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#17940]
### Issue type

File corruption

### Steps to reproduce

When I tried to update and check notes of this score:
https://musescore.com/classicman/scores/189697
  Musescore 4 simply returns an empty file. What's wrong?

### MuseScore Version

4.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows

**Comment by zacjansheski** [comment]
The score opens in 4.0.2 (with corruption message), it does not open in the nightly

**Comment by zacjansheski** [comment]
Corruption message:

Voice too long: Full score, measure 33, staff 1, voice 2. Found: 7/8. Expected: 3/4.
Voice too long: Full score, measure 33, staff 2, voice 2. Found: 7/8. Expected: 3/4.
Voice too long: Full score, measure 40, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 41, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 42, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 43, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 44, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 45, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 46, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 47, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 48, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 50, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 54, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 55, staff 1, voice 2. Found: 4/4. Expected: 3/4.
Voice too long: Full score, measure 56, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 57, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 58, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 59, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 60, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 61, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 62, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 63, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 64, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 66, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 67, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 167, staff 1, voice 2. Found: 26/32. Expected: 3/4.
Voice too long: Full score, measure 169, staff 1, voice 2. Found: 26/32. Expected: 3/4.
Voice too long: Full score, measure 178, staff 1, voice 2. Found: 26/32. Expected: 3/4.
Voice too long: Full score, measure 180, staff 1, voice 2. Found: 26/32. Expected: 3/4.
Voice too long: Full score, measure 203, staff 2, voice 2. Found: 4/4. Expected: 3/4.
Voice too long: Full score, measure 207, staff 2, voice 2. Found: 4/4. Expected: 3/4.
Voice too long: Full score, measure 253, staff 1, voice 2. Found: 7/8. Expected: 3/4.
Voice too long: Full score, measure 254, staff 1, voice 2. Found: 7/8. Expected: 3/4.
Voice too long: Full score, measure 255, staff 1, voice 2. Found: 7/8. Expected: 3/4.
Voice too long: Full score, measure 256, staff 1, voice 2. Found: 7/8. Expected: 3/4.
Voice too long: Full score, measure 257, staff 1, voice 2. Found: 7/8. Expected: 3/4.
Voice too long: Full score, measure 258, staff 1, voice 2. Found: 7/8. Expected: 3/4.
Voice too long: Full score, measure 269, staff 2, voice 2. Found: 4/4. Expected: 3/4.
Voice too long: Full score, measure 270, staff 2, voice 2. Found: 4/4. Expected: 3/4.
Voice too long: Full score, measure 272, staff 2, voice 2. Found: 4/4. Expected: 3/4.
Voice too long: Full score, measure 273, staff 2, voice 2. Found: 4/4. Expected: 3/4.
Voice too long: Full score, measure 274, staff 2, voice 2. Found: 4/4. Expected: 3/4.
Incomplete measure: Full score, measure 289, staff 1. Found: 5/4. Expected: 3/4.
Voice too long: Full score, measure 347, staff 1, voice 2. Found: 16/16. Expected: 3/4.
Voice too long: Full score, measure 347, staff 1, voice 3. Found: 15/16. Expected: 3/4.
Incomplete measure: Full score, measure 436, staff 1. Found: 84/96. Expected: 3/4.
Incomplete measure: Full score, measure 442, staff 1. Found: 84/96. Expected: 3/4.
Incomplete measure: Full score, measure 453, staff 1. Found: 20/20. Expected: 3/4.
Voice too long: Full score, measure 569, staff 1, voice 2. Found: 4/4. Expected: 3/4.
Incomplete measure: Full score, measure 577, staff 1. Found: 100/96. Expected: 3/4.
Incomplete measure: Full score, measure 849, staff 1. Found: 100/96. Expected: 3/4.
Voice too long: Full score, measure 910, staff 1, voice 2. Found: 26/32. Expected: 3/4.
Voice too long: Full score, measure 912, staff 1, voice 2. Found: 26/32. Expected: 3/4.
Voice too long: Full score, measure 921, staff 1, voice 2. Found: 26/32. Expected: 3/4.
Voice too long: Full score, measure 923, staff 1, voice 2. Found: 26/32. Expected: 3/4.
Incomplete measure: Full score, measure 962, staff 1. Found: 10/8. Expected: 3/4.
Voice too long: Full score, measure 964, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 965, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 965, staff 1, voice 3. Found: 7/8. Expected: 3/4.
Voice too long: Full score, measure 966, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 967, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 967, staff 1, voice 3. Found: 7/8. Expected: 3/4.
Voice too long: Full score, measure 968, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 972, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 973, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 973, staff 1, voice 3. Found: 7/8. Expected: 3/4.
Voice too long: Full score, measure 974, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 975, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 975, staff 1, voice 3. Found: 7/8. Expected: 3/4.
Voice too long: Full score, measure 976, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Voice too long: Full score, measure 980, staff 1, voice 2. Found: 8/8. Expected: 3/4.
Incomplete measure: Full score, measure 994, staff 1. Found: 96/96. Expected: 3/4.
Voice too long: Full score, measure 1009, staff 2, voice 2. Found: 7/8. Expected: 3/4.
Incomplete measure: Full score, measure 1032, staff 2. Found: 10/8. Expected: 3/4.
Incomplete measure: Full score, measure 1096, staff 1. Found: 959/896. Expected: 3/4.
Incomplete measure: Full score, measure 1208, staff 1. Found: 169/208. Expected: 3/4.
Incomplete measure: Full score, measure 1212, staff 1. Found: 221/208. Expected: 3/4.
Incomplete measure: Full score, measure 1240, staff 1. Found: 2015/2496. Expected: 3/4.
