### ISSUE TITLE
'Loading new score' dialog appears during factory reset

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#17946]
### Issue type

UI bug

### Steps to reproduce

1. Open MU
2. Top menu > Help > Revert to factory settings

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/9bc5d7c3-dda7-4984-bec0-55df701555c1

### MuseScore Version

4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Window10/Mac13

### Additional context

#16810

**Comment by jessjwilliamson** [comment]
> @bkunda It should be the same as in 4.0.2 (MuseScore splashscreen) + VST scan dialog on top of it, or just empty screen with VST scan dialog?
> 
> How it looks in 4.0.2 (just without VST scan dialog):
> 
>  bandicam.2023-06-12.17-30-09-577.mp4

I'd say splashscreen and VST scan dialog, yes, like usual

**Comment by cbjeukendrup** [comment]
Might make sense to check if this issue still occurs since #18130 has been merged

**Comment by DmitryArefiev** [comment]
Yes, I see it was fixed in 4.1 already (checked on **4.1 release build** , Win10. 

Thanks for point it out!

Closing
