### ISSUE TITLE
Note associated with French word cœur does not print.

### ISSUE THREAD

**Issue by PhenDem** [musescore/MuseScore#17954]
### Bug description

Text for song is in French. The note for word cœur in vocal part doesn't print.
![image](https://github.com/musescore/MuseScore/assets/92341431/f6d706c4-3e56-4ebe-ad37-43840634d0eb)
Link to score: https://musescore.com/user/6293241/scores/10873717/s/cBq7XX

### Steps to reproduce

1 go to score https://musescore.com/user/6293241/scores/10873717/s/cBq7XX
Print score or export as PDF

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/92341431/d14c6e69-f589-4808-9eab-48fbc33ccf95)
pdf image :  
![image](https://github.com/musescore/MuseScore/assets/92341431/f7da134f-85d7-4c03-8599-f3ebcf11e9b8)

### MuseScore Version

Musescore 4.0.2.230651553

### Regression

No

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
That link does not work for me - be sure it's unlisted rather than private.  Better, just ZIP and attach it here.

**Comment by PhenDem** [comment]
I changed it to unlisted.

**Comment by MarcSabatella** [comment]
The link still does not work for me.  Maybe you need a new secret link?  Again, though, it would be simpler to just ZIP and attach the file here...

**Comment by PhenDem** [comment]
Will this work??
https://musescore.com/user/6293241/scores/11123446/s/2TH4b8?share=copy_link

**Comment by PhenDem** [comment]
How do I do that?

**Comment by MarcSabatella** [comment]
To attach a file to your comment, see below where you type your comment, where it says "Attach files by dragging & dropping, selecting or pasting them".  If you dion't know how to ZIp a file, that's OK, you can simply rename the score so that the filename ends in ".zip".  So instead of myscore.mscz (or whatever), change it to myscore.zip.

**Comment by PhenDem** [comment]
[La Famille Demers voice.zip](https://github.com/musescore/MuseScore/files/11744854/La.Famille.Demers.voice.zip)

**Comment by oktophonie** [comment]
The note is set as invisible:
![image](https://github.com/musescore/MuseScore/assets/20604032/d51f05b9-96b2-4081-a694-d614f6ff4bff)
Just check the 'Visible' checkbox (or press V) to fix it.

**Comment by PhenDem** [comment]
Thanks for the help!
