### ISSUE TITLE
Custom name for palate item doesn't stick after save and close

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#17956]
### Issue type

Other type of issue

### Bug description

This worked perfectly for me in 4.0.1 and 4.0.0, I could add an item from the score to a palate, either a pre-existing palate(like with time signatures) or a custom palate. This part I can still do fine. I could then go to the palate item, right click, and go to Properties and change the name from say Time Signature to 8/4 for example. This, I can still do. But, in 4.0.1 and 4.0.0, these custom names would stick after I saved and closed the file. Well, that's the part that's not working for me in 4.0.2 is the sticking after save and close.

As an example of what I mean(and this is exactly what happened a couple days ago), I add staff text and enter a2. I then add a custom palate that I call Instrument numbers. Then I Ctrl + Shift + drag the a2 into that custom palate. Then I right click on a2, go into Properties, and change the Name property from Staff Text to a2 and click OK. I then save and close my file. Upon reopening of MuseScore, the custom palate stays, the a2 item stays, but the a2 name when I mouse over it does not stay, it reverts to Staff Text.

Clarification info by Marc Sabatella:

It seems if you only change a custom name, then the palette is not saved. If you also make any other change, then all changes are saved, including the custom name. I just tested, and this is not different than 4.0.1 or 4.0. It did however work correctly in 3.6.2. So it's a bug, and a regression against MU3, but not against earlier MU4 releases.

### Steps to reproduce

1. Add an item from the score to a palate (Ctr+Shift)
2. Change the custom name for the palate item by going right click -> Properties and entering in the name
3. Save the file
4. Close MuseScore
5. Reopen MuseScore
6. See that the item is still there, but the name has reverted back to before the change

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/6530761/6326204d-ae4e-46ee-a00c-494d4df7834c

### MuseScore Version

MuseScore 4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by VanSHOE** [comment]
Seems connected to https://github.com/musescore/MuseScore/issues/12002

**Comment by zacjansheski** [comment]
Thank you for reporting this.  I am referring to https://github.com/musescore/MuseScore/issues/12002 as the master issue and closing this.
