### ISSUE TITLE
command line svg export only exports first page

### ISSUE THREAD

**Issue by geekabit-nl** [musescore/MuseScore#17960]
### Issue type

Other type of issue

### Bug description

When I export a multi-page score via the GUI, it exports all pages. When I use the command line option to export the same score, it only exports the first page. File naming is also slightly different, with the GUI using '<title>-1.svg', '<title>-2.svg', and the command line export using '<title>.svg', leaving out the '-1' and '-2' parts.

Exported files and zipped Musescore file are attached.

[Brood-en-Vrienten--Als-je-wint.zip](https://github.com/musescore/MuseScore/files/11733021/Brood-en-Vrienten--Als-je-wint.zip)
![Brood-en-Vrienten--Als-je-wint](https://github.com/musescore/MuseScore/assets/47984376/e2464a36-1597-416a-8730-43d647423ab2)
![Brood-en-Vrienten--Als-je-wint-1](https://github.com/musescore/MuseScore/assets/47984376/b74b2f2d-9cf9-4cfc-86cd-150239c3fcd9)
![Brood-en-Vrienten--Als-je-wint-2](https://github.com/musescore/MuseScore/assets/47984376/f12c3b34-41ef-4004-afc9-ce5f5b81a4e1)

### Steps to reproduce

./MuseScore-4.0.2.230651545-x86_64.AppImage Brood-en-Vrienten--Als-je-wint.mscz --export-to Brood-en-Vrienten--Als-je-wint.svg

### MuseScore Version

4.0.2.230651545-x86_64

### Regression

I don't know

### Operating system

Debian Trixie, kernel 6.1.0-9-amd64

### Additional context

In Musescore 3.2 I used a job file to export svg and that did export all pages.

**Comment by DmitryArefiev** [comment]
Can reproduce on Windows10 too (latest master)

Thanks for logging!

**Comment by Erriez** [comment]
Reproducible with MuseScore 4.0.2 AppImage on Linux.
Reported via https://musescore.org/en/node/340436#comment-1195836.

**Comment by DmitryArefiev** [comment]
@geekabit-nl Can you try build from https://github.com/musescore/MuseScore/pull/19468 on your side, on Linux please?

I've tried on Windows - all good.

**Comment by geekabit-nl** [comment]
@DmitryArefiev The export works perfectly now. Thanks!

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev The export works perfectly now. Thanks!

@geekabit-nl Glad to hear. Thanks for checking! (Kudos to @mathesoncalum )

**Comment by DmitryArefiev** [comment]
Fixed in #19468
