### ISSUE TITLE
canceling paper color selector turns paper color to black

### ISSUE THREAD

**Issue by geekabit-nl** [musescore/MuseScore#17967]
### Issue type

UI bug

### Bug description

When I open the paper color selector (Edit, Preferences, Appearance) it shows the correct selected color.
Now when I press cancel or hit escape, the selected color is changed to black.

### Steps to reproduce

Top menu, Edit, Preferences, Appearance
Scroll down to "paper", press colored box (white by default) next to "color:"
On the color selector, press "cancel", or press escape key.
Now the white background should change to black.

### MuseScore Version

MuseScore-4.0.2.230651545-x86_64

### Regression

I don't know

### Operating system

Debian Trixie

**Comment by cbjeukendrup** [comment]
I can reproduce in 4.0.2, but not in [the latest nightly build](https://musescore.org/en/nightly-builds). Fixed by #15468.
