### ISSUE TITLE
(Aux Sends) Aux pan knob doesn't grey out when bypassed

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#17965]
### Issue type

UI bug

### Bug description

Simple note that the colour of the actual aux send knob should be changed when being bypassed as shown here (number 4):

<img width="1521" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/f5eda5a0-316e-4b21-9b90-a2b66499b5be">

### Steps to reproduce

1. open mixer
2. enable aux sends
3. bypass aux send
4. See colour doesn't change on aux send knob

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/71656189/85c724cb-def7-4cff-b590-3995d9baca64

### MuseScore Version

Latest master

### Regression

No.

### Operating system

macOS 13

**Comment by illumimarty** [comment]
Hi, this is my first time looking at this codebase and submitting my first PR. Will welcome any feedback!
