### ISSUE TITLE
Crash file

### ISSUE THREAD

**Issue by amijaishalev** [musescore/MuseScore#17979]
### Issue type

Crash or freeze

### Bug description

This file crashed in two different situations:

1. Adding an instrument (Violin)
2. Ctrl+K 

Case 1 was solved by opening the file in MU4 (not nightly).
Case 2 happend while working on Nightly build.

### Steps to reproduce

1. Open file
2. Select bar
3. Ctrl+K

### MuseScore Version

OS: macOS 13.4, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231630309, revision: github-musescore-musescore-63b36c0

### Regression

I don't know

### Operating system

MacOS

### Additional context

[Crashlog.pdf](https://github.com/musescore/MuseScore/files/11745400/Crashlog.pdf)
[Gloria .mscz.zip](https://github.com/musescore/MuseScore/files/11745410/Gloria.mscz.zip)

**Comment by zacjansheski** [comment]
Thank you, this has been resolved in the latest nightly/master.  I will now close this.
