### ISSUE TITLE
Deleting Sound Folder Creates Limbo State In Muse Hub

### ISSUE THREAD

**Issue by WinFan3672** [musescore/MuseScore#17972]
### Issue type

Muse Sounds bug

### Bug description

Deleting the folder for a Muse Sound causes the Hub to still recognise it, despite it not existing. The Hub refuses to remove it because the files do not exist (which is counterintuitive), meaning it is impossible to fix this. This is most likely an issue with the .instruments file.  

### Steps to reproduce

1. Move a Muse Sounds folder away from your Muse Sounds
2. Relaunch Muse Hub
3. The Sound in question will remain installed yet refuse to remove itself.

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

Arch Linux

### Additional context

This LITERALLY cannot be fixed by the user. Removing .instruments doesn't help, and as far as I can tell, all you can do it open it in a hex editor and try and remove entries related to it.

**Comment by cbjeukendrup** [comment]
I guess that manipulating the Muse Hub data folders is simply not supported. OTOH, I think it would be good if there was a way to recover from this inconsistent state, for the case that such a folder disappeared due to unforeseen causes other than the user.

**Comment by zacjansheski** [comment]
Closing as being managed by Muse Hub team
