### ISSUE TITLE
Ties don't playback correctly when chord is arpeggiated or when system text applies an effect to guitars

### ISSUE THREAD

**Issue by Nathan-Hausman** [musescore/MuseScore#17990]
### Issue type

General playback bug

### Bug description

When a chord is arpeggiated and has a tie, any tied notes will be silent during playback. Additionally, if an effect such as distortion is applied to a guitar with system text, ties act like they don't exist and all notes are played separately. Interestingly, this does not occur for some instruments such as muted trumpet in either MS Basic Soundfont or MuseSounds. I have added a sample project file below.

### Steps to reproduce

1. Create a new score in MuseScore 4 with electric guitar as an instrument.
2. Add a chord that is tied.
3. Add an arppegio to the chord.
4. Add another note or chord that is also tied in a seperate measure.
5. Add the distort system text to that measure
6. Playback

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

Example score, zipped due to file type restrictions
[example.zip](https://github.com/musescore/MuseScore/files/11753138/example.zip)

As far as I can tell this issue occurs with both MS Basic and MuseSounds.

**Comment by DmitryArefiev** [comment]
Thanks for logging!

The distortion issue is  already logged #16968, and arpeggiated chord with ties looks the same as #11936 (I will add the current case there)
