### ISSUE TITLE
MuseHub Will Not Launch Win 10

### ISSUE THREAD

**Issue by jd21234** [musescore/MuseScore#18008]
### Issue type

Crash or freeze

### Bug description

I downloaded MuseHub, and it appears to have installed correctly, but it will not launch. Task Manager shows MuseHub running in the background but it never loads. I was able to download and install MuseScore 4 without it, but I also want to get the instruments, and I can't find where to download them without using MuseHub.  I have restarted the computer, and uninstalled/reinstalled MuseHub multiple times, and run WindowsAppRuntimeInstall.exe as an administrator.  MuseHub shows in Background Apps in Task Manager.  It shows in the Start Menu but not in the system tray icons.  I am on Windows 10 Pro version 10.0.19045. Thank you for any help you can provide.  

### Steps to reproduce

Install MuseHub, go to Start Menu, click MuseHub icon.

### Screenshots/Screen recordings

![MuseHub Task Mgr 06-15-23](https://github.com/musescore/MuseScore/assets/136741280/e44f78e0-aede-49e5-a3b1-63715225dacc)

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

Windows 10

**Comment by bkunda** [comment]
Hi @jd21234, as this is a MuseHub-specific issue, can we please ask you to raise it with the MuseHub support team?
https://musehub.zendesk.com/hc/en-gb
Thanks!
