### ISSUE TITLE
New Score > "Cancel or "Done" or exiting from score wizard puts MuseScore window behind another window

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18001]
### Issue type

UI bug

### Bug description

New Score > Cancel Puts MuseScore window behind another window

In my video, the dark mode window is MS4.0.2, light mode window is the current master

### Steps to reproduce
1. Open explorer
2. Run MuseScore 
3. Revert to factory settings
4. After relaunch, click "New Score"
5. Click Cancel
6. Explorer window behind MuseScore gets focus

[see comment](https://github.com/musescore/MuseScore/issues/18001#issuecomment-1611024855)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/0a148f83-9908-4eb7-bed9-941b224e442a

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231660304, revision: github-musescore-musescore-7db8bc7

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
Also happens when you choose/add an instrument and click "Done"

**Comment by henkdegroot** [comment]
For me this also happens often when I just complete the New Score wizard. Fun fact, it does not happen when I try to make a video of it. I am using Windows 11.

**Comment by zacjansheski** [comment]
For the sake of clarity, this occurs no matter what is behind MuseScore (current master)

Does not need to be another instance of MuseScore, it could be anything.

This occurs when clicking "Cancel" or "Done" or the x to close

https://github.com/musescore/MuseScore/assets/69917893/dfa3a0b3-6877-4c50-bc58-e744c6c9beb6

**Comment by bkunda** [comment]
Yeah that seems pretty bad. Good spot @zacjansheski.

**Comment by zacjansheski** [comment]
The issue no longer occurs in the current master.  Closing.

**Comment by DmitryArefiev** [comment]
@zacjansheski PreviuosIy, I also was unable to reproduce it but now I found how to trigger that issue again. 
It's **reproducible after factory reset**. 
(I'll modify the steps in description)


https://github.com/musescore/MuseScore/assets/90187801/de4031e2-eb5c-455c-91a3-6014c2400eba
