### ISSUE TITLE
Cloud scores don't have labels (marks) in File > Open recent dropdown

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#18014]
### Issue type

UI

### Bug description

If you have scores on disk and in cloud with the same name you can't distinguish them in Recent score list in File menu

![Capture](https://github.com/musescore/MuseScore/assets/90187801/3cb5e495-1f57-4908-baa4-834157a8c9b6)

### MuseScore Version

4.1 nightly master

### Operating system

Windows10

**Comment by jessjwilliamson** [comment]
Nice spotting Dmitry! I will propose something about it :) Should be easy to put a cloud icon next to the name, now we have the unicode icon thanks to @bkunda!

**Comment by jessjwilliamson** [comment]
The only thing I realised is that MacOS uses their own OS context menu though. However, referencing from Photoshop, they've been able to tackle this issue and put a cloud icon from their mac OS typeface. Is this possible @cbjeukendrup ? 
<img width="780" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/da7ffbd1-843d-40c5-8492-98e47f34dc7c">

**Comment by cbjeukendrup** [comment]
In theory this must be possible. It looks like Qt provides some functionality for putting icons in native menu items, so we can try if that gives a satisfactory result. Otherwise, we will need to hack it ourselves, which is not easy. In any case this will require investigation, and I'm not sure if it's worth the time investment right now.

**Comment by jessjwilliamson** [comment]
> In theory this must be possible. It looks like Qt provides some functionality for putting icons in native menu items, so we can try if that gives a satisfactory result. Otherwise, we will need to hack it ourselves, which is not easy. In any case this will require investigation, and I'm not sure if it's worth the time investment right now.

That's fine, this can be planned for 4.2 :)

**Comment by shoogle** [comment]
If a member of the community would like to try adding a cloud symbol ☁ [`\u2601`](https://www.fileformat.info/info/unicode/char/2601/index.htm) to the "Open recent" menu to see how it looks on macOS then feel free!

**Comment by nasehim7** [comment]
Greetings @shoogle and team! I will be happy to take this up :D

**Comment by nasehim7** [comment]
Hi team, I have made the required changes, raised the PR and here is the screenshot of how it looks:

![UI](https://github.com/musescore/MuseScore/assets/18035782/941c2f86-c36a-4000-8c80-57664e406d16)

I am not sure about "Clear Recent Files" item. Is it fine to keep it like this?

**Comment by DmitryArefiev** [comment]
@jessjwilliamson What do you think?

**Comment by jessjwilliamson** [comment]
If that's the unicode cloud design for macos, I'd like to see it in other OS. Windows, Linux maybe. @DmitryArefiev how does it look on Windows? :)

**Comment by DmitryArefiev** [comment]
@jessjwilliamson I've checked all OSs.

Mac:
<img width="766" alt="Screenshot 2024-03-08 at 18 33 26" src="https://github.com/musescore/MuseScore/assets/90187801/fce08fc2-c4aa-498a-a584-e019609440fa">
Win:
<img width="593" alt="Screenshot 2024-03-08 182647" src="https://github.com/musescore/MuseScore/assets/90187801/36740407-a214-4148-b0fc-ea1b222e6554">
LinuxUbuntu:
![Screenshot from 2024-03-08 18-29-16](https://github.com/musescore/MuseScore/assets/90187801/24f6ada3-54ec-472c-b889-00ef69e6b953)

**Comment by jessjwilliamson** [comment]
Thank you so much Dmitry for showing these! Hmm @bkunda what do you think?
Personally Not a fan of the different cloud designs provided by their OS. If it is possible we could implement our own cloud icon, I guess that's how Adobe has done it. I've checked both mac and window versions of Photoshop and they use the same cloud icon they've implemented themselves. Is this possible @cbjeukendrup?

**Comment by jessjwilliamson** [comment]
> See PR [#21802 (comment)](https://github.com/musescore/MuseScore/pull/21802#issuecomment-1986421747) for an experiment using the cloud emoji instead of the cloud text character.
> 
> The emoji looks more like what [Photoshop is using](https://github.com/musescore/MuseScore/issues/18014#issuecomment-1594429925), but it only works on macOS. We would need to use a different font to see the emoji on Windows, or we would need to add the emoji glyph to the current font.

For reference, this is what the cloud icon looks like on Photoshop on Windows 
![image (3)](https://github.com/musescore/MuseScore/assets/71656189/b884fca3-0326-4357-b078-dd191b9dafd7)
