### ISSUE TITLE
Translations for trills don't work

### ISSUE THREAD

**Issue by Yanko64** [musescore/MuseScore#18019]
### Issue type

Other type of issue

### Bug description

some strings such as 3061 "mordent", 3067 "short trill" ,and  3071-3073: "turn", "inverted turn" and "turn with slash" don't work even though they are translated in transifex

### Steps to reproduce

1. use Musescore in a language other than English
2. go to palettes 
3. select the ornaments palette in that language 
4. hold the cursor above some of the options there such as the turn, the inverted turn, the mordent etc.
the text that should display above them is not translated   

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/65133734/0f1e9e64-e764-40e5-a061-ff69b203d67b

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231670304, revision: github-musescore-musescore-d6ace8b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
Most Ornaments are affected, all except "Trill line", "Up mordent" and "Down mordent".

"Muted (closed)" is affected too (in Articulations), in a very strange way, under `More...` is is translated, obt in the paletter itself it is not, even if deleted there and readded from `More...`

**Comment by Jojo-Schmitz** [comment]
Found a fix for Ornaments, see #18022
