### ISSUE TITLE
Scores saved in 4.1 loses all page and style settings when opened in 4.0

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#18010]
### Issue type

Engraving bug

### Bug description

If you save a score with custom page or style settings using 4.1, then open in 4.0, you get a dialog (expected) that it was saved in a newer version.  If you open anyway, you get the score but without the page & style settings.

### Steps to reproduce

1. Create score in 4.1
2. Set staff scaling to smaller in Format / Page settings, change score font to MuseJazz in Format / Style / Score, and/or any make other page or style settings
3. Save
4. Open in 4.0.2

Result: the settings are lost

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231660305, revision: github-musescore-musescore-7db8bc7

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linix / Debian 11

**Comment by oktophonie** [comment]
Opening a file from a newer version in an older version in "unsupported", so I can't imagine we'll be addressing this.

**Comment by MarcSabatella** [comment]
For the record, we have never introduced such an incompatibility in a “minor” release.  So this is going to need to be very clearly communicated and explained to users.

The good news is, unlike a “major” release, there is little reason not to update.
