### ISSUE TITLE
Quickly copying and pasting or selecting multiple bars quickly does not work as intended

### ISSUE THREAD

**Issue by metasekk** [musescore/MuseScore#18020]
### Issue type

UI bug

### Bug description

- When attempting to select a range of bars (say, between Bar 1 and Bar 2), performing "Click [on Bar 1] > Maintaining Shift > Click [on Bar 2]" _in quick succession_ results in selecting only Bar 2, as if the 'Shift' inbetween the clicks had been lost.

- When attempting to copy and paste a bar from one place to another (say, from Bar 1 to Bar 2), performing "Click [on Bar 1] > Ctrl+C > Click [on Bar 2] (> then Ctrl+V on Bar 2)" _in quick succession_ results in a list selection on Bar 1, as if the "+C" in "Ctrl+C" had been lost, in which case everything happens as though only "Click [on Bar 1] > Maintained Ctrl > Click [on Bar 2]" had been performed.

In both cases, it most often happens when Bar 1 had not been selected before, in which case the UI appears to be oftentimes very slow to select it. Otherwise, if Bar 1 had already been selected just before, it works as intended and the UI response is quick.

### Steps to reproduce

1. Open/create a new score.
2. Follow the steps described in the "Bug description" section, on any couple of bars (Bar 1 & Bar 2) of the score.

### Screenshots/Screen recordings

I provide two poor videos (one for each case) [here](https://github.com/musescore/MuseScore/assets/120221700/8377c8c7-f4f3-4ad6-9273-260ea403cd93) and [here](https://github.com/musescore/MuseScore/assets/120221700/33dd112e-ff32-49b7-ae23-d25a57f220f3), which are unlikely to be of great help, as the series of keys and clicks cannot be seen nor heard.

I have tried using a virtual keyboard and a mouse-click indicator to highlight the succession of keys and left-clicks pressed. Strangely, as soon as one of them is active, the behaviour of MS4 UI changes, and the mouse freezes for ~1 s after the first click to select Bar 1, in which case the two bugs described above cannot be reproduced.

### MuseScore Version

Checked on 4.0.2 and Nightly 231550315-master-b443bf7-x86_64

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Win10 (22H2); RAM: 16Go; CPU: Intel Core i5-9300H (2.40GHz)

### Additional context

Note n°1: To go further, I have mapped the shortcut "Ctrl+C" on Windows with the key ~ on the keyboard. It this case, performing "Click [on Bar 1] > ~ > Click [on Bar 2] > Ctrl + V" puts a C in Bar 2, as though the key 'C' had been used instead of 'Ctrl+C'.

Note n°2: The quickness here ('in quick succession') seems to depend strongly on the content of the score. Example: when trying to select a range of bars in heavy scores with MuseSounds active, this behaviour is always observed, even when waiting ~2s between "Click [on Bar 1] + Shift" and "Click on Bar 2". Thus, this bug might be insignificant in lightweight scores, but trying to copy and paste or select a range of measures becomes gruelling in large scores (in which case, selecting Bar 1 can take up to several seconds so that the bug always show up).

For your information, this has only been checked in scores where Muse Sounds were active.

**Comment by zacjansheski** [comment]
I'm finding this difficult to reproduce, I'm using a Symphony Orchestra template with >1000 measures
Windows 11, 8GB RAM, Processor: Intel(R) Celeron(R) N5095 @ 2.00GHz   2.00 GHz

Is there any additional information that might help me reliably reproduce?

https://github.com/musescore/MuseScore/assets/69917893/8f768103-a111-405e-ab0e-144386bcc572

**Comment by metasekk** [comment]
That is a bit surprising to me...

In my case, it definitely has something to do with the Muse Sounds.

I have just checked that in both cases that I had described, I had MuseSounds activated as the default playback setup (with MuseSampler v0.3.2). Then, everytime I try to select the "Bar 1" described above, my CPU quickly reaches 100% just to select a new bar.

However, I have just tried activating MS Basic as the default profile instead. The two problems then completely disappear, and I get the same results as in the video which you have provided. Meanwhile, my CPU never exceeds 16% when performing the same series of keys.

Does it help?

**Comment by zacjansheski** [comment]
Very helpful, thank you!  Adding the MuseSounds label to help pinpoint the issue.

**Comment by metasekk** [comment]
I have re-checked the issue with Musescore Beta 4.1 ([MuseScore-4.1.0.231731239-x86_64.msi](https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/testing/MuseScore-4.1.0.231731239-x86_64.msi)), where MuseSampler is updated from version 0.3.2 to 0.4.0.25. Both problems are gone; besides, selecting bars in quick succession now never increases CPU usage by more than 40% on my computer. I suspect that MuseSampler v0.3.2 was still used in the Nightly builds that I had used to report the issue. I apologise for that, because I should have made it clear! 

Should I close the issue?
