### ISSUE TITLE
Command-line option --score-mp3 not implemented

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#18033]
### Issue type

Other type of issue

### Bug description

In MS3, the score can be exported using the command-line to mp3 format using the option: --score-mp3
This option is missing in MS4.

<img width="234" alt="image" src="https://github.com/musescore/MuseScore/assets/13550012/00dddb74-8bd0-43c4-8a30-a2523688461e">

### Steps to reproduce

Try to export a score using the --score-mp3 option via command-line

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11, Ubuntu

### Additional context

Using the -o option and specify the mp3 extension, the export works fine. So not sure if this command-line option is still needed. Just let me know, so the handbook can be updated accordingly,

**Comment by henkdegroot** [comment]
See #8398, which was reported for this CLI option as well. Seems we no longer need/want this option.

**Comment by Erriez** [comment]
`--score-mp3` is documented on https://musescore.org/en/handbook/4/command-line-usage.

`MuseScore4.exe "pathname\score-filename.mscz" -o "pathname\output-filename.mp3"`

This method works on both Windows and Linux AppImage.

Notes:
- On Windows, the prompt returns immediately and generated MP3 file is 0KB.
- On Linux, the prompt returns when the MP3 has been created, so different behavior.
- Generation on both Windows and Linux takes some time and after a while the MP3 file is created correctly.

**Comment by bkunda** [comment]
I've been advised that this feature was implemented in v.3 for musescore.com backend reasons, and that since v.4 this is no longer required by the website team. 
We also have another way of exporting mp3s in v.4.
Would be good to know whether this is still really needed in v.4 (and why) so we can prioritise accordingly.

**Comment by cbjeukendrup** [comment]
I think we can indeed say farewell to the `--score-mp3` option. The `-o xxx.mp3` option should work fine; if there are ever any problems with this option, please let us know in a new issue. Thanks!

**Comment by cbjeukendrup** [comment]
(We do need to remove it from the Handbook page though.)

**Comment by henkdegroot** [comment]
Handbook updated.
