### ISSUE TITLE
Muse Sounds: microtonal tuning does not work during real playback, only when 'previewing' notes

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#18036]
### Issue type

Muse Sounds bug

### Steps to reproduce

1. Create score and add some notes
2. In Properties > Playback, change the tuning of some of the notes
3. Playback using Muse Sounds
-> the pitches are "rounded" to the nearest semitone. MuseSampler seems to ignore the `offset_cents` parameter of `ms_NoteEvent_3` (and probably same with `ms_NoteEvent_2`). I verified that MuseScore does specify this parameter correctly. 

When you just click on individual notes to hear them, the tuning _is_ honoured. 

### MuseScore Version

master (4.1); MuseSampler 0.4.0.25

### Regression

Choose option...

### Operating system

macOS 13

**Comment by iamtesch** [comment]
Thanks for the report -- I believe this is a sampler issue.  I'll look into the cause here.

**Comment by Vykoiazon** [comment]
there is this unintended pitch change on a note which has no altered tuning in muse sounds clarinet

https://github.com/musescore/MuseScore/assets/120861729/8415b993-73cf-4f29-841e-bec74cac089b

**Comment by Fristover** [comment]
this might be a different issue that should be logged separately, I guess you can open a new one and see if it's reproducible with more notes!

**Comment by cbjeukendrup** [comment]
@Vykoiazon That's indeed not related to this issue, please open a new issue for that. Thanks!

**Comment by Tantacrul** [comment]
This is now rolled out. If you open / refresh the MuseHub, and make changes, you'll hear microtonal playback.

There is one bug I've found (50 cents sounds incorrectly), which I think should be logged separately. However, the actual playback is working now.

**Comment by Jojo-Schmitz** [comment]
So is this available to 4.1 too, or does this require some additional fixes from 4.2?

**Comment by Jojo-Schmitz** [comment]
From #19413 I gather it to be the former, right?

**Comment by Tantacrul** [comment]
@Jojo-Schmitz it doesn't require fixes in MS so should be working now. You just need to open the Muse Hub and refresh updates (although it should be automatic)

**Comment by Jojo-Schmitz** [comment]
Thanks
