### ISSUE TITLE
Translation: “bracket” palette should be just “Klammern” in german

### ISSUE THREAD

**Issue by mmeyn** [musescore/MuseScore#18046]
### Issue type

UI bug

### Bug description

The bracket palette is named incorrectly as “eckige Klammern” in german. If my english is correct, the brackets [{( have the following names:

[ eckige Klammer = bracket OR square bracket
{ geschweifte Klammer = brace OR curly bracket
( runde Klammer OR Klammer = parenthesis OR round bracket

The general term (like “bracket” in english) is “Klammer”, plural form “Klammern”.

### Steps to reproduce

1. Use german as UI language.
2. Find the bracket palette.

### Screenshots/Screen recordings

![Bildschirmfoto vom 2023-06-19 16-00-39](https://github.com/musescore/MuseScore/assets/7814361/924cd720-b9f3-4868-95ac-5bea2520bee5)

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

Linux (probably OS-independent)

**Comment by Jojo-Schmitz** [comment]
Maybe... but more for the OP: update your translations, that issue got gixed 7 months ago ;-)

**Comment by Jojo-Schmitz** [comment]
Hmm, not in 4.0.2, but I do see it in 4.1, Dunno why though?

**Comment by Jojo-Schmitz** [comment]
There are some contexts where "Brackerts" gets translated as "Eckige Klammern":

* ../../src/inspector/view/qml/MuseScore/Inspector/notation/accidentals/AccidentalSettings.qml, line 58
   (right next to Parentheses -> Runde Klammern)
* ../../src/notation/view/widgets/editstyle.cpp, line 698
* ../../src/notation/view/widgets/editstyle.cpp line1119
*    (here too right next to Parentheses -> Runde Klammern)

And 2 contexts, where Brakets is translated as Klammern:

* ../../src/palette/internal/palettecreator.cpp, line 933 (and that's the one that should be used here)
* ../../src/notation/view/widgets/editstyle.ui, line 6282

**Comment by Jojo-Schmitz** [comment]
So why isn't is using the right one.

**Comment by mmeyn** [comment]
> Maybe... but more for the OP: update your translations, that issue got fixed 7 months ago ;-)

Oh … you’re right. I installed MuseScore via a Linux packet manager, the latest update is from April 20th, installed by me on May 7th. I didn’t know the translations are not updated automatically. It’s sort of weird that MuseScore didn’t tell me this at least once.

**Comment by mmeyn** [comment]
Updating the translations works for me but maybe this could be a hint to find a better solution (like warning the user that this has to be done by hand from time to time, automatically checking for translation updates, or force a translation update at least with a new release).

**Comment by Jojo-Schmitz** [comment]
Updating translations works for 4.0.2, but apparently doesn't help for the upcomming 4.1

**Comment by Jojo-Schmitz** [comment]
I was wrong, it fixes 4.1 too. So this issue can get closed

**Comment by cbjeukendrup** [comment]
I'll close this issue, and create a feature request about automatically offering to update translations.

**Comment by cbjeukendrup** [comment]
See #18049
