### ISSUE TITLE
[Accessibility] Tab navigation gets stuck in Braille panel

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#18068]
### Issue type

UI bug

### Bug description

When navigating the UI with the Tab key, focus gets stuck in the Braille panel. It is not possible to navigate away from the Braille panel by pressing Tab.

__Workaround:__ Press Ctrl+Tab or Shift+Tab to navigate away from the braille panel.

### Steps to reproduce

1. Launch MuseScore
2. Enable the Braille panel in Preferences > Braille.
3. Return to the score and press Tab repeatedly to navigate the UI.

Navigation will get stuck in the Braille panel.

### MuseScore Version

Latest nightly (5560227)

### Regression

No.

### Operating system

Windows 11

### Additional context

I guess that the tab key is being swallowed by the TextArea. See https://doc.qt.io/qt-5/qml-qtquick-controls2-textarea.html#tab-focus, although the solution proposed there won't work for us because we are using a custom navigation system.

It's ok to swap the TextView for a different component as long as the braille remains visible and is still sent to a connected braille display.

**Comment by MarcSabatella** [comment]
Hi - this was actually reported yesterday in https://github.com/musescore/MuseScore/issues/18054

**Comment by DmitryArefiev** [comment]
Fixed in #18134
