### ISSUE TITLE
Capo doesn't place correct in Guitar palette if 4.1 installed on top of 4.0.2

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#18065]
### Issue type

UI bug

### Bug description

**Not correct:**

![Capture](https://github.com/musescore/MuseScore/assets/90187801/6a9e20bb-4d35-4ce1-a770-8a40e04bf6a8)

**Correct:**

![Capture2](https://github.com/musescore/MuseScore/assets/90187801/73c1afbc-89e6-4eae-ba04-60fa8a61ca12)

### Steps to reproduce

1. Run 4.0.2 Release build
2. Reset factory
3. Add any palette to Palettes panel
4. Close 4.0.2
5. Install 4.1 (release mode build)
6. Open Guitar palette

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/3242d9e3-51d5-410a-af3c-3e9f0fc5f866

### MuseScore Version

4.1 master (in release mode)

### Regression

No

### Operating system

Windows10/Mac13

### Additional info

Reset palette works fine to fix wrong position

**Comment by mike-spa** [comment]
I implemented a while ago some compatibility code for palette elements, perhaps it can be useful https://github.com/musescore/MuseScore/blob/master/src/palette/internal/palettecompat.cpp (though mine was about exchanging old with new items).

**Comment by DmitryArefiev** [comment]
Fixed in #18387
