### ISSUE TITLE
Translations missing entirely

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#18071]
### Issue type

Other type of issue

### Bug description

There are no translations at all on the 4.1.0 Beta PortableApp
(I don't want to test the installable version as that'd replace my 4.0.2 installation)

### Steps to reproduce

There's no translation ".qm* files for musescore or instruments in ...App/MuseScore/locale, only qt,
Updating translations does sort of work, it downloads them to ...Data/settings/locale, but they don't get used at all

### MuseScore Version

4.1.0 Beta, PortableApp

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by bkunda** [comment]
Tested translating to German on macOS and Win Master (4.1 beta). Translation worked as expected.
So it would seem this issue affects only the Beta PortableApp.
I have made inquiries with our dev team about this.

**Comment by Jojo-Schmitz** [comment]
The 4.0.2 Portable App didn't have that issue

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz Could you please try if this helps? https://github.com/musescore/MuseScore/actions/runs/5328724536

**Comment by Jojo-Schmitz** [comment]
Yes, that fixes it, thanks.

Another issue: on start of the ...paf.exe Windows shows this warning:
![Screenshot 2023-06-21 104150](https://github.com/musescore/MuseScore/assets/1786669/c1739668-8c2f-452c-8ffc-69ec7ad06590)
When clicking on "Weitere Informationen" this:
![Screenshot 2023-06-21 103839](https://github.com/musescore/MuseScore/assets/1786669/db3a72d6-0e05-462d-ac82-25fa3b06edb8)

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz This should become a signed portable windows build: https://github.com/musescore/MuseScore/actions/runs/5344537986 Would be great if you could test it when ready.

**Comment by Jojo-Schmitz** [comment]
Yup, monotiring the build as we speak ;-)

**Comment by Jojo-Schmitz** [comment]
Nope, same issue still
