### ISSUE TITLE
User shouldn't be able to open 4.2 scores (and greater) in a previous version of 4 (4.1 or greater)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#18083]
### Steps to reproduce

1. Create a score in **4.1** (or save old score in 4.1)
2. Open it in **4.0.x** - **a warning message appears but user can open 4.1 score**

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/84543ec3-500a-4845-8761-60a1ac05e1be

### Expected behaviour

This dialog should appear when the user attempts to open a 4.1 score in a previous version:

<img width="527" alt="DIALOG-backwards-compatibility" src="https://github.com/musescore/MuseScore/assets/86290556/9f2a761a-3d68-4519-b50d-d9502de5cc79">

### MuseScore Version

4.1

### Operating system

all

**Comment by DmitryArefiev** [comment]
Implemented in #18358

**Comment by jeetee** [comment]
FWIW, I totally missed this change being here and I feel that it is not a good one.

Not allowing files from other *major* releases in older ones and breaking file compatibility in those is an expectancy. But not allowing downgrades between **minor** releases is in my view a semantically no-go in versioning.

A minor release is all about adding **non-breaking** features, and bug fixes. Sure, it may add to the file format; but those additions should be just ignored in older minor versions. Opening newer scores in older versions (within the same major release branch) that way will result in the new feature just being dropped. As such, it'll *never* result in corrupted or unusable score, simply in the same score with the same limitations as if it was made in that version.

What I'm completely missing here is the motivation for dropping this downgrade versioning established practice (also see semver.org) and general user expectancy. A reply providing such a rationale and/or opening the discussion on the necessity would be appreciated. (@bkunda ?)

**Comment by Jojo-Schmitz** [comment]
To me this is a serious regression

**Comment by shoogle** [comment]
We discussed this internally. While we don't want to drop forwards compatibility just for the sake of it, the reality is that we are making too many changes between "minor" versions that we can't hope to preserve compatibility in both directions. Nor do we want to slow down the pace of those changes, or to hold them back for the next major release.

Semantic versioning is mostly useful for software libraries. If we were a library (i.e. catering to developers rather then end users) then we could simply bump the major version every few months with each breaking change. However, as a consumer application there are other factors to consider beyond compatibility, so bumping the major version willy-nilly isn't an option.

These days people are used to living in a fully connected environment, receiving automatic updates, etc. There may be a few people in schools who are stuck with whatever version is installed on the school system, but the vast majority will have no trouble updating to the latest version. Bumping the major version wouldn't do anything for the people who can't upgrade.

Personally, I was in favour of keeping the warning with "open anyway" option on the off-chance that it does work, but it was thought that this could lead to data loss as people pass scores between incompatible versions, and the score wouldn't look right in the old version anyway. In the end we decided it is simpler to make no promise of forward compatibility between minor versions.

**Comment by lgvr123** [comment]
> These days people are used to living in a fully connected environment, receiving automatic updates, etc. There may be a few people in schools who are stuck with whatever version is installed on the school system, but the vast majority will have no trouble updating to the latest version. Bumping the major version wouldn't do anything for the people who can't upgrade.

I don't really agree with this vision. 
For sure, most people wouldn't have technical issues with upgrading to new versions.

But not anyone is willing to do it every now and then. On one side, you have the early-adopters, ready to jump on every new version. On the other side, you have the late-adapters, preferring to install a new version only when it has proven to be stable enough, preferring stability over new stuff.

On top of this you have all the users still using MU3.6. Some advanced users are reluctant to update to MU4.x due to some features having disappeared, or no longer working.

In between, you have version maze, that makes it very difficult to collaborate with other people on a same score.

**Comment by shoogle** [comment]
We don't anticipate the early vs. late adopter thing to be an issue for minor releases. Sure, people might wait a week or two for the inevitable patch release, but after that everyone should be able to upgrade without fearing the consequences.

These days we have more resources for testing, so we should catch most problems before the release. Also, we rarely remove features in minor releases, and if we do it's usually to replace it with something better.

Major releases are the exception of course. For those releases you can expect big changes, so it's understandable that some users want to stick with the previous version for a little while after the release. Perhaps we should consider versioning the file extension in future to make that side-by-side environment more manageable, but don't expect us to implement any form of forwards compatibility between versions.
