### ISSUE TITLE
Palette Scale property sets itself to 0.

### ISSUE THREAD

**Issue by Tralen** [musescore/MuseScore#18080]
### Issue type

UI bug

### Bug description

If I edit the preference for `paletteScale` in the Advanced tab, it will set itself to zero on next launch and the palette UI will only show lines or garbled icons, making it impossible to use.

Setting it back to 1 or to any other value won't work, it will always reset to zero and the palette UI will be broken. The only solution is to manually remove the `paletteScale` line from the MuseScore `.ini` file.

### Steps to reproduce

1. Go to **Preferences** > **Advanced**
2. Change the `application/paletteScale` entry to any other value.
3. Restart the program and check the palette icons.

### MuseScore Version

OS: Linux Mint 21, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d

### Regression

Choose option...

### Operating system

Linux Mint 21 - MATE

### Additional context

My `inxi -b` output:
```
System:
  Host: primario Kernel: 5.15.0-71-generic x86_64 bits: 64
    Desktop: MATE 1.26.0 Distro: Linux Mint 21 Vanessa
Machine:
  Type: Laptop System: LENOVO product: 82MF v: IdeaPad 3 15ALC6
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: NO DPK serial: <superuser required>
    UEFI: LENOVO v: GLCN40WW date: 07/23/2021
Battery:
  ID-1: BAT0 charge: 35.0 Wh (97.0%) condition: 36.1/38.0 Wh (94.9%)
CPU:
  Info: 6-core AMD Ryzen 5 5500U with Radeon Graphics [MT MCP] speed (MHz):
    avg: 1519 min/max: 1400/2100
Graphics:
  Device-1: AMD Lucienne driver: amdgpu v: kernel
  Device-2: Chicony Integrated Camera type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu resolution: 1920x1080~60Hz
  OpenGL: renderer: RENOIR (renoir LLVM 15.0.6 DRM 3.42 5.15.0-71-generic)
    v: 4.6 Mesa 22.2.5
Network:
  Device-1: Realtek RTL8822CE 802.11ac PCIe Wireless Network Adapter
    driver: rtw_8822ce
Drives:
  Local Storage: total: 1.14 TiB used: 1001.78 GiB (85.6%)
Info:
  Processes: 320 Uptime: 16d 21h 26m Memory: 9.58 GiB used: 3 GiB (31.4%)
  Shell: Bash inxi: 3.3.13

```

**Comment by cbjeukendrup** [comment]
I think this has been fixed long ago, see #15322 for example. Could you please try it out the latest nightly build (https://musescore.org/en/nightly-builds)?

**Comment by Tralen** [comment]
Thank you. It is indeed fixed on the nightly build.Closing it now.

**Comment by Tralen** [comment]
Thank you. It is indeed fixed on the nightly build. Closing it.
