### ISSUE TITLE
[4.1] 'Your score could not be opened' dialog pops up when trying to open cloud score (unsigned)

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#18090]
### Issue type

Other type of issue

### Bug description

Think the messaging of this dialog could be addressed better that this is a cloud score that requires the user to sign in, rather that an abrupt 'your score could not be opened, please try again later' which appears like it's corrupted.

### Steps to reproduce

1. Sign out of musescore account
2. Open a cloud score
3. See dialog (error)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/71656189/fd93a608-03af-41b0-bda8-8b0f91d2f64b

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

macOS 13

**Comment by Jojo-Schmitz** [comment]
For me cloud scores don't open at all, if I try a file dialog shows instead, to select/open a local file.
Is that because those online scores of mine are all 3.6 scores?

**Comment by Jojo-Schmitz** [comment]
> > For me cloud scores don't open at all, if I try a file dialog shows instead, to select/open a local file.
> > Is that because those online scores of mine are all 3.6 scores?
> 
> That should have changed since #17764 has been merged

It has, thanks
