### ISSUE TITLE
Minimise, Maximise, Close buttons missing

### ISSUE THREAD

**Issue by xiAbcde** [musescore/MuseScore#18096]
### Issue type

UI bug

### Bug description

For some reason, the Minimise, Maximise, and Close buttons are not there.
Also, I have 'hidden' taskbar on (the taskbar only shows when the mouse navigates to the bottom of the screen) but when Musescore is open the taskbar doesn't show.

### Steps to reproduce

I'm not sure. All I did was open Musescore

### Screenshots/Screen recordings

![Screenshot 2023-06-21 172153](https://github.com/musescore/MuseScore/assets/122308768/49acbb6a-2326-4ad5-9366-dcf26da94e08)

### MuseScore Version

4.0.2-230651553

### Regression

I don't know

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
This has been fixed a while ago in the latest master branch. You can try it out in the nightly builds: https://musescore.org/en/nightly-builds or in the soon-to-be-released MuseScore 4.1 beta; watch the MuseScore Discord server or MuseScore.org website for news on that.

**Comment by xiAbcde** [comment]
I'm not sure I understand, how does this nightly builds thing work?

**Comment by cbjeukendrup** [comment]
It is explained on the Nightly Builds page itself:
> **Windows**
> The .7z file you download is a compressed [7-zip](https://www.7-zip.org/) archive; use the free program 7-zip to extract it. Once extracted, find the subfolder called bin and double-click the MuseScore4 executable that's inside.

In a bit more detail:
1. click the [Nightly builds for Windows](https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/?C=M;O=D) link
    <img width="754" alt="Scherm­afbeelding 2023-06-21 om 19 46 32" src="https://github.com/musescore/MuseScore/assets/48658420/46b44a2f-a841-4cff-aee7-cef4b4d76ec0">
2. Click the "[MuseScoreNightly-latest-master-x86_64.7z](https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/MuseScoreNightly-latest-master-x86_64.7z)" link to download the latest one
3. The downloaded file is a 7z file, which is a kind of zip file. Use the [7-zip](https://www.7-zip.org/) utility to extract this 7z file. 
4. The result should be a folder. Inside that folder, there should be a bunch of folders, and one of them is called `bin`. Go into the `bin` folder. There you will find `MuseScore4.exe`. This is the MuseScore app; double-click it to run it.
