### ISSUE TITLE
Musescore 4 paper background revert to default

### ISSUE THREAD

**Issue by zorba77** [musescore/MuseScore#18104]
### Issue type

UI bug

### Bug description

Musescore do not save the paper background setting, so when you close the app the setting is lost and when you open it again a white background is shown.

### Steps to reproduce

On linux (I cannot check other os):
- I open Musescore 4
- I set a paper background
- I close Musescore 4
- When I open it again the paper setting is lost and the background is White
This is true also in the last 4.1 Nightly build

### MuseScore Version

4.1 nightly build and 4.02

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Ubuntu 20.04

**Comment by MarcSabatella** [comment]
Probably a duplicate of https://github.com/musescore/MuseScore/issues/16930

**Comment by bkunda** [comment]
Steps are the same, so closing (duplicate)
