### ISSUE TITLE
Turn should come before inverted turn in Ornaments palette

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#18121]
### Issue type

UI bug

### Bug description

The inverted turn shows up first in the ornaments palette. The regular turn should probably come first, just as the short trill comes before mordent (which technically is an inverted mordent, but SMuFL just calls it mordent).
This would standardize the order of ornaments so that the "plain" version of an ornament comes before its inverted version.

### Steps to reproduce

1. Open the Ornaments palette
2. See that "Inverted turn" is the first element, then "Turn" comes after

### Screenshots/Screen recordings

<img width="305" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/24ee1594-2b7e-4ca0-aa6d-d4fc9f43b9eb">

### MuseScore Version

OS: macOS 12.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231720302, revision: github-musescore-musescore-d05ff44

### Regression

No.

### Operating system

All

**Comment by Jojo-Schmitz** [comment]
I could easily add this to #18022, which changes code in direct vincinity

**Comment by Jojo-Schmitz** [comment]
BTW: mordent and short trill got swapped in SMuFL a couple years ago

**Comment by Jojo-Schmitz** [comment]
Another problem is the handbook, https://musescore.org/en/handbook/4/ornaments, it would need to get changed

**Comment by avvvvve** [comment]
I'm currently rewriting that handbook page for the 4.1 release, which is why I came across this! I could update with a new screenshot.

I had the same thought that it will take some adjusting for users that are accustomed to how it is now. @bkunda @jessjwilliamson, do we have a pattern for a one-time tooltip-style alert to tell users something like "this feature has moved"?

**Comment by oktophonie** [comment]
Unnecessary - people should know what symbol they are using, and I doubt anyone's ever input a score that uses so many turns (inverted or not) that they are going on muscle memory to input them :) Just move the thing
