### ISSUE TITLE
'Loading new score...' window shows regardless of whether a new score has been opened or not

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#18129]
### Issue type

UI bug

### Bug description

When opening a second instance of the program, the splash screen defaults to 'Loading new score...' even if no new score has been opened.

### Steps to reproduce

1. Open MuseScore
2. Open MuseScore again

### MuseScore Version

4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment]
See the builds from https://github.com/musescore/MuseScore/pull/18130; it should be better there.
