### ISSUE TITLE
Musescore 4 won't boot up

### ISSUE THREAD

**Issue by vruzzen** [musescore/MuseScore#18133]
### Issue type

Other type of issue

### Bug description

This has been an issue that alot of people have been experiencing, but none of the fixes that have worked for others have worked for me.

When I boot up Musescore, the initial pop-up stays on my screen for about 2-3 seconds, and then.. nothing. It just closes without actually opening up Musescore.

I have tried running Musescore as administrator, deactivating my audio manager software, tried downloading a test version of Musescore 4 that was published in a different forum about a similar issue that apparently fixed this. Didn't work either.

This bug wasn't present in earlier versions of Musescore (i.e. Musescore 3 and below).

### Steps to reproduce

..I think this part's pretty redundant for my issue.

### MuseScore Version

Musescore 4

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

Considering some people have said this is an 'audio device prioritization issue', I do have an external audio interface & VoiceMeeter installed. Other than that there's nothing more I can provide.

**Comment by cbjeukendrup** [comment]
Have you already tried the latest beta of MuseScore 4.1? It includes another attempt to fix this. See https://musescore.org/en/node/351505.

**Comment by zacjansheski** [comment]
Closing, no response
