### ISSUE TITLE
Append measures after a measure before a meter change should keep old meter

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#18149]
### Your idea

The command to append measures after a selection will use the time signature of the *following* measure if different from the time signature of the selected measure.  This is coiunter-intuitive and also misses out on an opportunity to solve a long-standing problem.

### Problem to be solved

MU3 only had a command to insert before a selected a measure, not to append after.  There was a never-ending debate about which time signature should be used if you tried to insert the first measure of a new time signature, with either answer being right half the time and wrong half the time.

Now that we have an append after command as well, it would be great if it's behavior were actually different from insert before.  So in this example:

![image](https://github.com/musescore/MuseScore/assets/1799936/98e1f6ae-7c95-4eec-b1f7-cb48867f7ddd)

Selecting the 4/4 bar and choosing append after would give you new 4/4 bars, while selecting the 3/4 bar and choosing insert before would give you new 3/4 bars.  Because actually creating more 4/4 bars in that scenario is unnecessarily difficult (you need to insert *before* the existing 4/4 bar, then cut/paste it to the last newly created bar).

### Additional context

Similar issues potentially exist with respect to key and clef changes; the solution should seem consistent across all through cases.  Also, probably, with respect to double barlines etc.  Would be nice if append vs somehow did things that seemed intuitive for all of these cases.  But time signatures are the worst case right now because attempting to fiddle with them cause rebarring of the music that you almost certainly don't want.

**Comment by Jojo-Schmitz** [comment]
Yes, an Append in measure N is not the same as an Insert in measure N+1, but apparently got implemented that way.
ISTR to have mentioned that back when that Append got implemented.

**Comment by sammik** [comment]
@MarcSabatella see #19415
