### ISSUE TITLE
Microtonal accidentals should affect glissando angle

### ISSUE THREAD

**Issue by miiizen** [musescore/MuseScore#18143]
### Issue type

Engraving bug

### Bug description

Currently, standard accidentals applied to notes change the angle of glissando lines accordingly, microtonal accidentals do not.  

This is currently done by checking the pitch of both notes on the same line/space [here](https://github.com/musescore/MuseScore/blob/master/src/engraving/layout/v0/tlayout.cpp#L2203), but microtonal accidentals don't have an effect.  

### Steps to reproduce

1. Place two notes of the same pitch one after the other
2. Add a microtonal accidental to one of the notes
3. Add a glissando lines between the notes.  It remains a horizontal line.

### Screenshots/Screen recordings

Standard accidentals change gliss. angle
![image](https://github.com/musescore/MuseScore/assets/26510874/ec3110f8-c711-4622-aed3-0fc02979e48e)

Microtonal accidentals don't
![image](https://github.com/musescore/MuseScore/assets/26510874/bea1c797-a668-432c-a6bd-5e010e63977e)

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

Windows 11

**Comment by sammik** [comment]
Another case notes with 8va

![8va-gliss](https://github.com/musescore/MuseScore/assets/1646034/0a9cab0d-8af8-4e3d-a1e2-7ff690e9f6e8)

**Comment by sammik** [comment]
Regarding microtonal accidentals.

General problem is, that there is no real support for microtonality implemented yet, and microtonal accidentals are decorative only at the moment.

In theory, we can check microtonal accidental of note, but it doesnt resolve situation like following, becouse all notes states as "natural"
![microtonal-gliss](https://github.com/musescore/MuseScore/assets/1646034/5bb46541-bb6a-47b4-9598-71cd992491b9)

But may be, we should also check "tunig" value of note and take it into account too.
