### ISSUE TITLE
Assigning MIDI CC Value with Komplete Kontrol M32

### ISSUE THREAD

**Issue by PacDrum** [musescore/MuseScore#18151]
### Issue type

Other type of issue

### Bug description

While trying to assign a MIDI CC value by pressing the corresponding knob on the MIDI Keyboard (Komplete Kontrol M32), the assigned value by MuseScore 4.0.2 is always CC0 for all the knobs on this keyboard, from CC14 to CC29 (Page 1 and 2 on the keyboard) and from CC102 to 117 (page 3 and 4 on the keyboard):
![image](https://github.com/musescore/MuseScore/assets/137532800/e6a25a37-310f-464a-8ea2-061db2df9b52)

After turning the desired knob to assign the value:
![image](https://github.com/musescore/MuseScore/assets/137532800/4a85b8fb-6fde-4194-9f81-754bb37cede4)

### Steps to reproduce

1. On the **Edit** dropdown menu select **Preferences**
2. Go to Midi Mappings
3. Select an Action and press **Assign MIDI mapping...**
4. Turn any knob on the Komplete Kontrol M32

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/137532800/bfbad20b-c90f-4eeb-a5da-bbdb717156d4)

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

Windows 11

**Comment by bkunda** [comment]
@cbjeukendrup FYI

**Comment by cbjeukendrup** [comment]
This looks very much like #15219, which has been fixed recently. Could you please try the 4.1 beta or nightly builds? See https://musescore.org/en/nightly-builds or https://musescore.org/en/node/351505.

**Comment by DmitryArefiev** [comment]
Yes, the same as #15219, and was fixed in **4.1**
