### ISSUE TITLE
Crash loading specific score

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#18155]
### Issue type

Crash or freeze

### Bug description

The attached score crashes on open, using the most recent nightly build on Linux that I am able to run (from before the build environment change the other day).  No useful info is printed to the console.

[My Cello Concerto.zip](https://github.com/musescore/MuseScore/files/11853625/My.Cello.Concerto.zip)

It loads fine in 4.0.2.

### Steps to reproduce

Unzip score & open score - crash

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231720346, revision: github-musescore-musescore-d05ff44

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linix / Debian 11

### Additional context

Score comes from https://musescore.org/en/node/351537#comment-1195741, which is about another issue that I was trying to confirm if it still exists on 4.1.  Pretty sure it does, and likely isn't relevant here, but just in case - the issue that was originally being reported here is another case of https://github.com/musescore/MuseScore/issues/16917, which also has a number of other duplicate reports.

**Comment by cbjeukendrup** [comment]
It turns out that the crash in https://github.com/musescore/MuseScore/issues/17901 has very similar Address Sanitizer output to this one, so they are probably related.

**Comment by cbjeukendrup** [comment]
And here is number 3! https://github.com/musescore/MuseScore/issues/17657 (I'll close that issue as a duplicate, because it has no useful info extra info and is unclear)

**Comment by mike-spa** [comment]
@cbjeukendrup thanks! I've figured out where and why it happens, working on a solution now

**Comment by DmitryArefiev** [comment]
Fixed in #18273
