### ISSUE TITLE
[Musicxml export] - Better pedal export

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#18159]
### Issue type

Other type of issue

### Steps to reproduce

Since Musescore's accessibility issues with inspector for lines are not solved, I have to report this issue by text description.
When a pedal line has both line and begin+end pedal symbols, Musescore exports it correctly. But:
1. When no line is shown, please apply line="no";
2. When end text is unchecked, only pedal start is exported, no stop. Line="no" will tell us there's only a pedal down symbol. I asked Michael Good about this, and he replied so.
3. When there's a special text for pedal line, please export just the text, with or without the line according to the line visibility.
  Sorry, it's a bit complicated, but I'm not able to produce them myself. You can try them in the inspector.

### MuseScore Version

4.0

### Regression

No.

### Operating system

all

**Comment by rettinghaus** [comment]
@hhpmusic could you please check with latest nightly build on master? I think all points are addressed.

**Comment by hhpmusic** [comment]
File here.
[pedal.zip](https://github.com/musescore/MuseScore/files/13612238/pedal.zip)

**Comment by rettinghaus** [comment]
"resume" indicates, that there is no hook at the beginning of the line (usually the case when there is also a symbol). 
"change" basically only makes sense when another line follows (so the hooks form an inverted V).

**Comment by hhpmusic** [comment]
Thanks, except the text, all are solved. In the engraving guidance I'll ask Musescore engravers not to input text into pedal lines, then everything will go well.
