### ISSUE TITLE
Piano treble clef playback stops working after adding elements to bass clef

### ISSUE THREAD

**Issue by NinjaNas** [musescore/MuseScore#18163]
### Issue type

General playback bug

### Steps to reproduce

1. Make a score with piano (MuseSounds or MS Basic)
2. Add notes to the treble clef, see that playback works
3. Add notes to the bass clef, see that playback works ONLY for bass clef
4. Move the notes in the treble clef, see that playback works for both clefs
5. Add text or roman numeral analysis to bass clef*, see that playback works ONLY for bass clef

*Playback works as normal when adding text to treble clef

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/54213302/cad646b4-9994-4f59-b64a-a50633d8bbe6

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231750501, revision: github-musescore-musescore-fcaa649

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

Playback is also affected by moving the bass notes around, adding accents and staccato to them, and adding rests.
I have had a score where this affects multiple measures just by changing one element of the bass clef.
It was working fine in 4.0.2

**Comment by MarcSabatella** [comment]
I can confirm a problem immediately after entering notes, seems to fix itself at some point.

**Comment by zacjansheski** [comment]
Confirmed, also on Mac OS.  I did experience it correcting itself at one point.

Labeling as a P0, major regression from 4.0.2

**Comment by bkunda** [comment]
Also just experienced this myself 


https://github.com/musescore/MuseScore/assets/86290556/c7a67273-2e4a-4b4a-a5d5-4b9e654fea62

@RomanPudashkin this one is a release blocker.

**Comment by DmitryArefiev** [comment]
Fixed in #18243
