### ISSUE TITLE
[Musicxml export regression] - All expression text not exported

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#18166]
### Issue type

Other type of issue

### Steps to reproduce

Today when I checked my braille transcriptions, I suddenly found the 4.1 builds, including recent nightly versions, don't export expression text at all. 4.02 is ok. I think it lasts quite a long time, and I've transcribed lots of braille scores under this situation without any notice. I'm heavily worried because I'm misleading all blind musicians reading my scores! I don't know how big work I have to do to bring such expressions back, because they are difficult to find again! Please check this example, the "dolce" at beat 1 marked as expression is not exported, but the one at beat 3 as normal staff text is exported.
[expression.zip](https://github.com/musescore/MuseScore/files/11859035/expression.zip)

### MuseScore Version

4.1

### Regression

Yes, this used to work in MuseScore 4.02 and now is broken

### Operating system

all

**Comment by Jojo-Schmitz** [comment]
Is it a regression vs Mu3 or vs. 4.0.2? It is flaged as the former, but I understand your desciption to mean the latter?

**Comment by hhpmusic** [comment]
> Is it a regression vs Mu3 or vs. 4.0.2? It is flaged as the former, but I understand your desciption to mean the latter?
Now I edited the text for 4.02. I checked my scores, and the recent 3 big chamber scores are effected by this issue. So this regression appeared at the beginning or middle of May.

**Comment by Jojo-Schmitz** [comment]
Here's what `git log` knows about changed to musicxml export:
```
commit f36923392fa5e53841416b7bf4d6b7546be03b04
Author: Casper Jeukendrup <48658420+cbjeukendrup@users.noreply.github.com>
Date:   Sun Jun 18 23:07:37 2023 +0200

    Fix crash when exporting to MusicXML after toggling MMRests

    The problem: when MMRests are disabled, measures still keep a reference to their MMRest measure (in order to preserve that MMRest measure and its properties). This means that the `mmRest1` method might return this MMRest, even when MMRests are disabled (so the method would be expected to return the measure itself). This is fixed by checking inside that method if MMRests are actually enabled.

    Additionally, this commit gives that method a slightly nicer name: `coveringMMRestOrThis()`.

commit 0d84c9a32d9a458769ff0450fba9c3e0b754c083
Author: Roman Pudashkin <r.pudashkin@gmail.com>
Date:   Mon May 29 16:53:38 2023 +0300

    added the Capo element

commit 574abd01eebfebc4452d4547d6b7c01876ec992f
Author: Igor Korsukov <igor.korsukov@gmail.com>
Date:   Thu Jun 1 12:12:06 2023 +0300

    [engraving] moved MSC_VERSION to Constans

commit 6f5a881b7df13a5d6ebdd798959d491e9fdee22a
Author: asattely <a.sattely@musescore.com>
Date:   Thu May 18 21:07:26 2023 -0400

    Consolidate staff/chord anchors into trinary above/below/auto

commit 0540c4c0accbc7fe8dd67cc204960d565678df81
Author: Igor Korsukov <igor.korsukov@gmail.com>
Date:   Thu May 18 19:26:14 2023 +0300

    removed  from INJECT macro

commit 4f31fe5cb588fff9d0d190461ef0a4e9a36c1334
Author: Sakari Bergen <sakari@yousician.com>
Date:   Wed Nov 30 15:55:29 2022 +0200

    Handle breath marks for chords/notes in addition to rests
```

**Comment by Jojo-Schmitz** [comment]
But I can confirm the issue.
There's one line added in 4.1:
```xml
        <instrument-sound>keyboard.piano</instrument-sound>
```
and 5 lines deleted:
```xml
      <direction placement="below">
        <direction-type>
          <words default-y="-42.42" relative-y="-25.00" font-style="italic">dolce</words>
          </direction-type>
        </direction>
 
```

**Comment by Jojo-Schmitz** [comment]
I have the feeling that 0d84c9a might be the culprit, it adds capo as annotations, I don't see yet though how/why it might have destroyed expression texts, but its changes are in very close proximity

**Comment by MarcSabatella** [comment]
Expressions texts are now a new element type, not just a particular text style applied to staff text.  I would assume there simply wasn’t proper MusicXML added when this change was made in https://github.com/musescore/MuseScore/pull/17001.  @mike-spa

**Comment by Jojo-Schmitz** [comment]
Ah, then a simlpe `e->isExpression() || ` might be missing in exportxml.cpp

**Comment by Jojo-Schmitz** [comment]
See #18170

**Comment by Jojo-Schmitz** [comment]
>  but the one at beat 3 as normal staff text is exported.

There is no such other expresion/staff text in your sample score

**Comment by hhpmusic** [comment]
> > but the one at beat 3 as normal staff text is exported.
> 
> There is no such other expresion/staff text in your sample score
Why? Can't you see a piece of text "dolce" at beat 1? That is expression text.

**Comment by Jojo-Schmitz** [comment]
No **other**.just that _dolce_

**Comment by hhpmusic** [comment]
> No **other**, just that _dolce_

Strange. I can hear staff text dolce at beat 1 when navigating in my mscz file. Only Musicxml doesn't have dolce at beat 1. If you can't find it, please add it at your side to try.

**Comment by Jojo-Schmitz** [comment]
Well, you wrote:

>Please check this example, the "dolce" at beat 1 marked as expression is not exported, but the one at beat 3 as normal staff text is exported.

There is the _dicle_ at beat 1 (and it indeed got lost on export), bit there's nothing at beat 3

**Comment by hhpmusic** [comment]
> Well, you wrote:
> 
> > Please check this example, the "dolce" at beat 1 marked as expression is not exported, but the one at beat 3 as normal staff text is exported.
> 
> There is the _dicle_ at beat 1 (and it indeed got lost on export), bit there's nothing at beat 3

That's good, only the one at beat 1 is the issue, so other things are not needed.

**Comment by Jojo-Schmitz** [comment]
@oktophonie I'll do the port as soon as the version for master got merged
