### ISSUE TITLE
MuseScore crashes after changing from external plugin to MS Basic, and then back (VST->MS Basic->VST, Windows 11)

### ISSUE THREAD

**Issue by Flipleerr** [musescore/MuseScore#18172]
### Issue type

Crash or freeze

### Bug description

When changing from an external plugin to MS Basic, and then back to said plugin (in my case it's Spitfire's BBC Symphony Orchestra library), MS4 crashes.

### Steps to reproduce

1. Switch to an external plugin in the mixer.
2. Then switch back to MS Basic.
3. Finally, reapply external plugin as mentioned above.
4. Observe.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/99bc8d30-abaf-487b-8857-d5bfb382db50

### MuseScore Version

4.0.2

### Regression

From @DmitryArefiev: Also **happens in 4.0.0** (if doesn't reproduce try several times to switch then close the score)

### Operating system

Windows 11

### Additional context

OS Name	Microsoft Windows 11 Home
Processor	Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz, 2401 Mhz, 2 Core(s), 4 Logical Processor(s)
Installed Physical Memory (RAM)	8.00 GB

**Comment by zacjansheski** [comment]
Confirmed in 4.0.2 and Current Master
(In video I used sforzando, it took me two tries while I was recording)

https://github.com/musescore/MuseScore/assets/69917893/7416f302-686a-4858-a870-41be064fdb08


[VST-BASIC-VST-Crash.zip](https://github.com/musescore/MuseScore/files/11885794/VST-BASIC-VST-Crash.zip)

**Comment by DmitryArefiev** [comment]
Can easy reproduce on my side as well with **BBC SO** (Windows10, **4.2 master**). 
Also **happens** in **4.0** (if doesn't reproduce try several times to switch then close the score)

That's probably similar to #18583 #18755

(Attaching video demo to the description)

**Comment by DmitryArefiev** [comment]
Fixed in #20148
