### ISSUE TITLE
Very slow commandline MP3 convert nightly 4.1.0-dev build fcaa649

### ISSUE THREAD

**Issue by Erriez** [musescore/MuseScore#18174]
### Issue type

Other type of issue

### Bug description

I noticed a 10 times slower commandline conversion from `.mscz` to `.mp3` file with nightly Appimage 4.1.0-dev build fcaa649 (with high CPU load) versus 4.0.2 which was much faster.

### Steps to reproduce

Conversion with 4.0.2 Appimage:
```bash
$ time ./MuseScore-4.0.2.230651545-x86_64.AppImage "Garry Moore - Parisienne Walkways.mscz" -o "Garry Moore - Parisienne Walkways.mp3"
/lib/x86_64-linux-gnu/libjack.so.0
/lib/x86_64-linux-gnu/libnss3.so
QEventLoop: Cannot be used without QApplication
QEventLoop: Cannot be used without QApplication

real	0m11,562s
user	0m14,090s
sys	0m4,796s
```

Conversion with Nightly 4.1.0-dev Build fcaa649:
```bash
$ time ./MuseScoreNightly-latest-4.1.0-x86_64.AppImage "Garry Moore - Parisienne Walkways.mscz" -o "Garry Moore - Parisienne Walkways.mp3"
/lib/x86_64-linux-gnu/libjack.so.0
/lib/x86_64-linux-gnu/libnss3.so

real	1m48,590s
user	2m53,228s
sys	0m42,544s
```

### Screenshots/Screen recordings

N.A.

### MuseScore Version

4.0.2 vs 4.1.0-dev build fcaa649

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 22.04

### Additional context

N.A.

**Comment by RomanPudashkin** [comment]
@Erriez could you please try this build? Is it any better?
https://github.com/RomanPudashkin/MuseScore/actions/runs/5414928150

After you try it, please open the Diagnostic menu and press "Save diagnostic files". Attach the archive here or send it to my email: r.pudashkin@gmail.com

Thanks!

**Comment by Erriez** [comment]
@RomanPudashkin Thanks for looking into this issue. Here is the comparison:

```
$ time ./MuseScore-4.0.2.230651545-x86_64.AppImage "Garry Moore - Parisienne Walkways.mscz" -o "Garry Moore - Parisienne Walkways.mp3"
/lib/x86_64-linux-gnu/libjack.so.0
/lib/x86_64-linux-gnu/libnss3.so
QEventLoop: Cannot be used without QApplication
QEventLoop: Cannot be used without QApplication

real	0m13,072s
user	0m13,522s
sys	0m5,775s


$ time ./MuseScore-4.2.0.231801709-x86_64.AppImage "Garry Moore - Parisienne Walkways.mscz" -o "Garry Moore - Parisienne Walkways.mp3"
/lib/x86_64-linux-gnu/libjack.so.0
/lib/x86_64-linux-gnu/libnss3.so

real	0m12,957s
user	0m12,509s
sys	0m5,990s
```

Please find the log attached: [user.zip](https://github.com/musescore/MuseScore/files/11909239/user.zip) as I prefer to communicate via Github. Is this sufficient information for you?

Thanks!

**Comment by RomanPudashkin** [comment]
@Erriez thanks for your help! Could you please try to reproduce this issue using the latest 4.1.0 nightly build? You can get it here:

https://ftp.osuosl.org/pub/musescore-nightlies/linux/4x/nightly/?C=M;O=D

**Comment by Erriez** [comment]
@RomanPudashkin This works perfect!

```
$ time ./MuseScoreNightly-latest-4.1.0-x86_64.AppImage "Garry Moore - Parisienne Walkways.mscz" -o "Garry Moore - Parisienne Walkways.mp3"
/lib/x86_64-linux-gnu/libjack.so.0
/lib/x86_64-linux-gnu/libnss3.so

real	0m12,230s
user	0m15,028s
sys	0m6,873s
```

Thank you very much for your great support! :+1:

**Comment by RomanPudashkin** [comment]
Thanks for testing! This issue either was fixed here https://github.com/musescore/MuseScore/pull/18186 or was originally caused by some external factors
