### ISSUE TITLE
Multiple bugs related to tremolos between notes in MS 4.1

### ISSUE THREAD

**Issue by LupusCaeruleus** [musescore/MuseScore#18173]
### Issue type

Engraving bug, UI bug

### Bug description

This issue consists of 5 issues related to tremolos between notes.

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231731239, revision: github-musescore-musescore-7d15ce0

-----

### 1. _Our good old friend_

When opening a score saved in MS 3.x, tremolos between notes are rendered incorrectly, until a "redraw" update is triggered.

![image](https://github.com/musescore/MuseScore/assets/70313425/f92e4a80-b9cb-44e6-b8d2-a04c2ae11320)

**Steps to reproduce:**

1. Download and open the file → [Sample File - Jupiter The Planets.zip](https://github.com/musescore/MuseScore/files/11859911/Sample.File.-.Jupiter.The.Planets.zip)
2. See the bars of Piano I on page 4.
3. Do anything that updates the score, the notes will be fixed.

https://github.com/musescore/MuseScore/assets/70313425/d46e6738-5837-4c7b-8639-faad2e448b76

**Regression:**
No. Also present in MS 4.0.

-----

### 2. The 3rd style of the tremolo beam is identical to the 2nd one

**Steps to reproduce:**

1. Select a tremolo between two quarter notes (or greater duration), click the 3rd style in the properties panel.
2. See the result.

https://github.com/musescore/MuseScore/assets/70313425/91dfb294-276d-4d36-b6ca-9c8a1d2c3c57

**Regression:**
Yes. Works in MS 3.x.

-----

### 3. Sometimes the tremolo beam is forced horizontal

I have not figured out the conditions that trigger this bug, but it only seems to happen between a chord and another chord/note.

**Steps to reproduce:**

1. Create the tremolos below.
2. Compare the results.

![image](https://github.com/musescore/MuseScore/assets/70313425/482bc21f-382b-4cf0-8d57-0cdc5c472414)

Also notice the incorrectly forced-horizontal tremolo beams in the screenshots from bugs **I.** and **V.** They should behave exactly the same as normal note beams.

**Regression:**
Yes. Works in MS 3.x.

-----

### 4. Adjusting the angle of a tremolo beam then changing the stem direction will completely ruin the rendering

**i.** The first part is a UI bug. Unlike independent notes, pressing X to flip the tremolo beam will not update the state of the Stem direction buttons in the properties panel. The buttons will only update after the user de-select and re-select the tremolo notes.

**Steps to reproduce:**
1. Select a tremolo beam, press X for multiple times.
2. See the Stem direction buttons in the properties panel.

https://github.com/musescore/MuseScore/assets/70313425/808ec850-563c-46a4-893a-98dbca63fc3b

**ii.** The second part is an engraving bug. Manually adjusting the angle of a tremolo beam then changing the stem direction twice will cause the stems fail to be drawn, with the tremolo beam misplaced.

**Steps to reproduce:**
1. Select a tremolo beam, use any of its three square "control points" to adjust its angle or positioning.
2. Press X twice.
3. See the result.
4. Arbitratily Press X and the Reset stem direction button in the properties panel. See the result.

https://github.com/musescore/MuseScore/assets/70313425/a816b105-cd4e-42d0-80a0-7b7417659237

5. And if you are lucky enough, you may even get this eventually.

https://github.com/musescore/MuseScore/assets/70313425/c75efb5f-128a-4195-b27f-6fed9f3a35d9

6. Finally, save the file and re-open it. All tremolo beams will return to normal, along with any of your modifications. So, it is technically impossible to save the adjustments of angles and positioning of tremolo beams.

**Regression:**
No. It is impossible to adjust tremolo beams independently before 4.1.

-----

### 5. Using Ctrl+click in Note input mode will allow user to add notes in between the tremolo notes

**Steps to reproduce:**
1. Select a beam with tremolo between notes, enter note input mode, press and hold Ctrl key, then click.
2. New notes are inserted in between the tremolo notes rather than after them.

https://github.com/musescore/MuseScore/assets/70313425/59e00ef5-c7b9-44fd-a7ca-87163c2b8285

3. Save the file and re-open it. The tremolos will be fixed, by re-grouping the new-added notes.

![image](https://github.com/musescore/MuseScore/assets/70313425/35b168d5-e37d-4d2c-971d-d6b35f05cd7a)

**Regression:**
No.

### Steps to reproduce

See above.

### MuseScore Version

4.1.0-231731239

### Regression

It varies.

### Operating system

Windows 10

**Comment by oktophonie** [comment]
Points I, II and III addressed by https://github.com/musescore/MuseScore/pull/18259
