### ISSUE TITLE
Piano switches hands

### ISSUE THREAD

**Issue by Bin3r** [musescore/MuseScore#18177]
### Issue type

General playback bug

### Bug description

The B eighth note in the right hand plays back at the same pitch as the B quarter note in the left. If I raise the note in the right hand it plays at the annotated pitch, i.e. two octaves above middle C. However, when I return it to its original position it drops two octaves. Deleting and re-entering the measure did not correct the problem. I've never had this problem before and it is isolated to this one instance in the score.

When uploaded and played back on the cloud. The right hand B plays true but the left hand B is split into two eighths.

Full score on Musescore
https://musescore.com/user/30371377/scores/11279047?share=copy_link

Screen shot of the guilty measure.
![image](https://github.com/musescore/MuseScore/assets/137756872/77cc747c-593c-43fc-9685-c0e26f62ea57)

### Steps to reproduce

1. Note entry
2. Playback

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 Home, Version 22H2

### Additional context

Using MS Basic

**Comment by zacjansheski** [comment]
I am unable to reproduce this issue.  The pitches are playing as expected on Mac and Windows as well.  Could you try with different headphones or speakers?  
Maybe check that the pitch reads correctly in the bottom left hand corner of MuseScore when selecting:
RH: A5, B4
LH: F2, C3, B3

**Comment by cbjeukendrup** [comment]
And maybe try what happens if you export the audio as MP3 or so, and listen to the resulting audio file? And maybe upload that here?
