### ISSUE TITLE
4.1 beta or nightlies won't launch (Linux)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18182]
### Issue type

Other type of issue

### Bug description

None of the 4.1 nightlies or beta version AppImages will launch.

1. Download latest nightly AppImage
2. Right click, select Permissions > Allow executing file as program, close.
3. Double-click file.

RESULT: Nothing happens, although the App shows as running in the "System monitor",

### MuseScore Version

4.1 (all)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux Mint 20.1

**Comment by Eism** [comment]
@rgreen5 
Please check this build
https://github.com/Eism/MuseScore/actions/runs/5377230612/jobs/9755420030

**Comment by MarcSabatella** [comment]
Works for me!

**Comment by rgreen5** [comment]
> @rgreen5 Please check this build https://github.com/Eism/MuseScore/actions/runs/5377230612

Yes, this one opens OK and seems to be playing back fine.
