### ISSUE TITLE
MuseScore 4 doesn't start if SteelSeries Sonar is being used

### ISSUE THREAD

**Issue by NetherGranite** [musescore/MuseScore#18190]
### Issue type

Other type of issue

### Bug description

If SteelSeries's Sonar software is used and an output device is set to one of Sonar's virtual cables, then MuseScore 4 displays a splash screen on launch and then closes, and nothing else shows up.

This issue has been reported before but seems to have been lost in crosslink spaghetti, so I just wanted to make sure it was still present in an open issue. #16278 was closed due to inactivity and under the assumption that it would be fixed in the next update, and #17089 was closed on suspicion of being a dupe of #15235, which itself was closed as it was fixed.

### Steps to reproduce

1. Install SteelSeries Sonar and set the default Windows output device to one of its outputs e.g. "SteelSeries Sonar - Gaming."
2. Install MuseScore 4 and try to run it.

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by webfischi** [comment]
Is this fixed or could it be connected to my issue #18557 because of spacial audio having more than 2 channels, to narrow down the issue

**Comment by cbjeukendrup** [comment]
@webfischi This should be fixed in 4.1, but @NetherGranite please confirm this. 
If it's not fixed, then it's likely related.

**Comment by webfischi** [comment]
@cbjeukendrup Sample rate is fixed, but not if you have more than 2 channels, switched my card to stereo mode and suddenly MuseScore was able to run.

**Comment by NetherGranite** [comment]
@cbjeukendrup Yes, it does work!

**Comment by cbjeukendrup** [comment]
Thanks for letting us know! Then I'll close this issue. (But https://github.com/musescore/MuseScore/issues/18557 is apparently still actual.)

**Comment by NetherGranite** [comment]
@cbjeukendrup Sounds are a few octaves higher and too fast when using Sonar though. Does that ring a bell or should I open a new issue?

**Comment by cbjeukendrup** [comment]
That reminds me of #15615, which has a fix pending. Does that make sense?

**Comment by cbjeukendrup** [comment]
Or, probably more likely, #17648.

**Comment by cbjeukendrup** [comment]
That's good to know! I've heard that that PR still needs some work before it can be merged, but I've listed it for 4.2, so hopefully it won't be forgotten.
