### ISSUE TITLE
[MU 4.1 Beta] Incorrect key signature after instrument change with multiple transposing instruments

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#18197]
### Issue type

Engraving bug

### Bug description

I was testing the fixes in #17601 and stumbled on this seemingly related glitch.  In a score with at least 3 instruments, two of which are transposing (differently) after adding instrument changes to each stave in turn and then adding another instrument change, the key signatures in the other staves are incorrect 

![InstrumentChangeGlitch](https://github.com/musescore/MuseScore/assets/60138048/5fc8964d-a110-49e2-8070-1b108e4ebc4c)

### Steps to reproduce

1. Create new score with one non-transposing and two differently transposing instruments – e.g. Flute, Soprano Sax, Alto.  Key Signature = C Max (concert)
2. Add whole notes (e.g concert G) to each instrument and each bar
3. Add instrument changes as follows:

- Bar 2, Top Staff – Change to Soprano Sax
- Bar 3, Middle Staff – change to Alto Sax
- Bar 4 Bottom Staff – Change to Flute
- Bar 5 Top Staff – Change to Alto Sax

4.  Note that key signature in middle and lower stave have also changed in Bar 5 with middle staff (currently Alto Sax) 2 sharps, bottom staff (currently Flute) 3 sharps.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/60138048/d19a252e-96da-4abf-b240-ca1eb0ce4afc

### MuseScore Version

4.1.0-231731239, revision: github-musescore-musescore-7d15ce0

### Regression

I don't know

### Operating system

Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 

### Additional context

I am not sure if this is a regression as Instrument Changes were pretty broken before the fixes in #17601.  It is not clear to me if this is a case that was missed in those fixes or whether one of those fixes broke something else.

I tried to reproduce with scores having only one instrument, and only two instrument.  It seems that 3 instruments is the minimum required and that two of those must be transposing instruments possibly with different transpositions.   I have not tested all combinations of 3 transposing/non-transposing instruments.

**Comment by sammik** [comment]
I cannot reproduce it in 4.1 nightly

OS: Ubuntu 22.04.2 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231760502, revision: github-musescore-musescore-fcaa649

Tried also master (4.2) nightly, works fine here.

**Comment by oktophonie** [comment]
I can't reproduce in current 4.1.0 branch either; perhaps I am missing something.

**Comment by SteveBlower** [comment]
I'll try again tomorrow.  Busy playing this evening.

**Comment by SteveBlower** [comment]
This is very odd.  Today I can't reproduce the example I demonstrated yesterday.  However, I can reproducibly show the same problem if I add further instrument changes.  If I save that score and reload, the incorrect key change is no longer present.

For the record, here is a screen grab of the whole process from creating the score, through entering the notes, adding the instrument changes, saving and reloading.


https://github.com/musescore/MuseScore/assets/60138048/db48de0e-d46b-4aa9-b355-d5ca7fa92e07


This is 100% reproducible today on my PC.  I will try again after a reboot.

**Comment by SteveBlower** [comment]
I tried again with 4.1.0 Beta after rebooting my PC and found exactly the same behaviour as in my latest screen grab.

I then downloaded and installed latest nightly (64-bit): 4.2.0-231780315, revision: github-musescore-musescore-1614004.  The behaviour is exactly the same; a spurious key signature is added to the middle staff in measure 8 as per my screen grab.  After saving and reloading the spurious key signature has disappeared.

One further thing I note is that after adding the 6th instrument change to Sopranos Sax on the bottom stave in measure 7 a double bar and courtesy key signatures on the top and bottom staves appear at the end of the first system.  A courtesy key signature is appropriate for the bottom stave as that is changing from Flute to Sop Sax and therefore a new key signature is required.  However, no courtesy key signature is needed for the top staff as that is continuing as Alto Sax.  The double bar and courtesy key signatures persist after saving and reloading.  They are removed by disabling courtesy key signatures in Format>Style>Page but reappear after re-enabling them.  

With a fresh score I tried disabling courtesy key signatures before adding the instrument changes, but still got the spurious key signature on the middle staff in measure 8 but no double bar at the end of the first system and (obviously) no courtesy key signatures.  Re-enabling courtesy key signatures gave the same result with a double bar at the end of the first system and an unneeded courtesy key signature for the top staff.

If no-one else can reproduce this, is there anything I can tell you about my system that would help diagnose what I (but not you) are seeing?

**Comment by oktophonie** [comment]
Sammik already filed the issue about the unnecessary end-of-system cautionaries: https://github.com/musescore/MuseScore/issues/18212

**Comment by SteveBlower** [comment]
I can reproduce the instrument change/spurious key signature issue on a second PC (system details OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231731239, revision: github-musescore-musescore-7d15ce0).

Further experimentation has identified that similar behaviour can occur with similar but different steps.  If I set up the score with whole note concert Gs as before but add instrument changes on odd numbered bars as follows

Top staff bar 3 To Soprano Sax
Middle Staff bar 5 to Alto Sax
Bottom Staff bar 7 to Flute
Top Staff bar 9 to Alto Sax  
I get the following result (spurious key signature bottom staff measure 9).

![InstChGlitch1-01](https://github.com/musescore/MuseScore/assets/60138048/6364e26d-7bd5-41af-82d4-5d6e32000521)

With even more experimentation I get a feeling that the problem may have something to do with more than one instrument change being added before and after a soft system break,  However, I have not experimented systematically enough to fully identify the necessary conditions for the glitch to occur.

**Comment by sammik** [comment]
@SteveBlower please, check, if same problem occurs, when score is not C major - a minor

I think, I found a case, but I am not 100% yet.

Thank You!

**Comment by sammik** [comment]
It seems to me, that isolated case is this:
1. score have to contain at least one transposing instrument
2. local key signature is added to untransposing instrument to measure, which was system measure before

see (I added same **local** key sig both times)

https://github.com/musescore/MuseScore/assets/1646034/7ff7264e-025a-4e39-bb86-3505917ba4cc

It is not regression, same issue is in MU 3.6.2

But I have no Idea, why it happens.

**Comment by sammik** [comment]
possible related (duplicate?) #14510

**Comment by SteveBlower** [comment]
> @SteveBlower please, check, if same problem occurs, when score is not C major - a minor

I tried with C minor.  Similar but different wrong result

![InstChGlitchCmin01](https://github.com/musescore/MuseScore/assets/60138048/23d0558b-cffd-4dd2-99a7-9cf50cdd465a)

This time when changing the top stave from Alto Sax (natural key signature) to Flute (should get a 3 flat key signature) there is no key signature added to the Flute stave

I then tried with F Maj.  Similar but yet another different wrong result.

![InstChGlitchFMaj01](https://github.com/musescore/MuseScore/assets/60138048/4e9e1dda-fdeb-454b-8e0e-e4f4d24b391f)

This time changing the middle staff from Flute (1 flat) to Soprano Sax the Soprano Sax correctly gets a 1 sharp key signature but the top staff (continuing as Flute) gets a spurious 1 sharp key signature and the bottom staff (continuing as Soprano Sax) gets a spurious 1 flat keys signature.

I tried one more in G Max and got yet another different wrong result.

![InstChGlitchGMaj01](https://github.com/musescore/MuseScore/assets/60138048/431b5cbf-4a69-4df0-8f94-e1b5a0652104)

This time changing the bottom staff from Flute to Soprano Sax in measures 7 puts spurious but correct key signatures on the top and middle staff (i.e. 4 sharps for Alto Sax on the top staff, 1 sharp for Flute on the middle staff).  However, these are not needed as this is the second measure of the system.  Adding a further change to Flute from Alto Sax on the top staff puts the correct key signature (1 sharp) on the top staff but incorrect key signatures on the middle staff (continuing as flute but gets 4 sharps) and bottom staff (continuing as Soprano Sax but gets 1 sharp).

I am sure there is some sort of pattern to this, but I haven't yet identified it.

One further comment: I tried the exercise with MU3 adding instrument changes (from the Add.Text menu rather than the palette) and got yet another different wrong result.  So not a regression but another bug that has evaded the net to date.


![InstChGlitchCMajMU301](https://github.com/musescore/MuseScore/assets/60138048/e0ae7609-b37c-4bb1-aa49-3b984b4d0be1)

**Comment by sammik** [comment]
Okay, I finally got, what exactly is going on.

When removing System header from measure (measure, which was first measure of system before), all apropriate segments are disabled, but content is not erased. 

Than, if user adds local key signature to such measure, KeySig segment is enabled again, which causes all key signatures in all staves (they were not removed) are shown again.

working on it

(mostly done already)

**Comment by sammik** [comment]
@SteveBlower please check PR build, is it is correct now
https://github.com/musescore/MuseScore/suites/13951327279/artifacts/777381275

thank You

**Comment by SteveBlower** [comment]
Yes, That looks like it has fixed the spurious key signature on instrument change.  

Well done and thanks.
