### ISSUE TITLE
Reproducible file corruption when copy-pasting nested tuplets and part is generated

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#18209]
### Issue type

Choose option...

### Bug description

Cut and paste of measure 1 into measure 2 consistently causes file corruption.

Take the first measure and paste (CRTL+C and CRTL+V) into the next measure and it consistently causes a file corruption when trying to save.  Before confirming the save, press CTRL+Z to undo and error goes away.

I believe it's the presence of the 16th note triplet nested inside the larger eighth note triplet.

The problem is very repeatable.  I trimmed my entire score down to just one instrument and one two measures and it still happens.

### Steps to reproduce

1. Select the whole first measure (CTRL+C)
2. Paste the measure into the next measure (CTRL+V)
3. Attempt to save the file
4. The following error appears when saving:
Incomplete measure: Part score: Violin, measure 2, staff 1. Found: 25/24. Expected: 4/4.

### Screenshots/Screen recordings

This score has become corrupted and contains errors.
Incomplete measure: Part score: Violin, measure 2, staff 1. Found: 25/24. Expected: 4/4.

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Choose option...

### Operating system

Windows 10 Home Version 22H2

### Additional context

[musescore corruption.zip](https://github.com/musescore/MuseScore/files/11876870/musescore.corruption.zip)

**Comment by mike-spa** [comment]
Reproducible steps:

- Create score with any number of instruments.
- Open all (or some of) the parts.
- Write some nested tuplets (such as the the ones in the example).
- Range-select the nested tuplets (or the measure containing them). Copy-paste it somewhere else, **as long as the instrument it's being pasted on has the part open**.
- Look at the part. The manually entered tuplets are fine. The pasted tuplets are wrong: basically, they've lost the "nesting". 

At this point the file is damaged, saving it and reopening it will show the corruption warning. Ctrl+Z before saving, or deleting the full measures, corrects the corruption.

****** NOT A REGRESSION ******
You can reproduce the issue with identical steps in Musescore 3.6.

**Comment by DmitryArefiev** [comment]
Fixed in #18238
