### ISSUE TITLE
Cannot insert key signature after first page when selecting a single note or rest

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18202]
### Issue type

Engraving bug

### Bug description

I believe this is both an engraving and UX issue

I cannot insert key signatures after the first page when selecting a single rest or note, the whole bar must be selected.

### Steps to reproduce

1. Create a score or open a template
2. Select a note or rest after the first page
3. Try to put in a new key signature

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/d54aa511-b4ac-4001-8264-c2f5f58ede67

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231770504, revision: github-musescore-musescore-fcaa649

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: macOS 11.6

**Comment by oktophonie** [comment]
Mid-measure key signatures are still possible, but, for now, only by adding a local one to all parts (or all desired parts) in the desired place, and this change is intentional.

**Comment by sammik** [comment]
Only first system of second page seems to be affected.

I am able to add key signature to rest on second system of second page.
