### ISSUE TITLE
Line break before local key signature casues adding unneeded cautionary signatures and undeletable key signatures to all staves

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#18212]
### Issue type

Engraving bug

### Bug description

If local key signature is in score and user adds line break to previous measure, unnecesary cautionary keysigs, and new undeletable key signatures are added to all other staves.

### Steps to reproduce

1. add local key signature to score
2. ad line break in measure before key signature
3. see - all staves have cautionary key signature, even if the dont need them
4. remove line break
5. see - new key signatures are in all staves, and are unremovable

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1646034/1531e774-3e5a-4ebc-9c4b-06ca4c6ff25f

### MuseScore Version

4.1, and master too

### Regression

No.

### Operating system

Ubuntu 22.04

**Comment by Jojo-Schmitz** [comment]
4.1 or master (which is at 4.2 meanwhile) or both?

**Comment by sammik** [comment]
> 4.1 or master (which is at 4.2 meanwhile) or both?

Both
