### ISSUE TITLE
[4.1] New Braille icon and re-size Preferences window

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#18223]
### Issue type

UI bug

### Bug description

1. New Braille icon needs to be implemented in Preferences by using the new Musescore icon font. It's currently an eye-closed icon.
2. Preferences height window needs to be adjusted now we have a new Braille side button - this has caused to make a scrolling feature which makes the Braille button at the bottom, hidden (only when General is being selected)

### Steps to reproduce

1. Open Preferences
2. See bottom of the left side - Braille side button.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/71656189/76d85039-28ac-408b-95ff-534c59274e8c

### MuseScore Version

Latest master

### Regression

No.

### Operating system

macOS 13

**Comment by jessjwilliamson** [comment]
@HemantAntony   
Me and @bkunda thought you'd like to take a look at this one? Let us know :D

**Comment by HemantAntony** [comment]
I'm working on it! Can you give me the hex code for the new icon?

**Comment by jessjwilliamson** [comment]
> I'm working on it! Can you give me the hex code for the new icon?

just messaged you on Discord!
