### ISSUE TITLE
Tied notes flip directions in single-line staves.

### ISSUE THREAD

**Issue by musondanolan** [musescore/MuseScore#18220]
### Issue type

Engraving bug

### Bug description

When doubling the length of notes in a single-line staff, the note is inconsistent with its direction by default.

### Steps to reproduce

1. Add a note in a single-line percussion instrument.
2. Select the note
3. Press w to double the length of the note
4. Repeat until the note spans several measures

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/16511571/d4c9f6db-8697-452b-8f36-5757f44fd40f

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230551516, revision: github-musescore-musescore-d23f054

### Regression

No.

### Operating system

OS: Windows 10 Version 2009, Arch.: x86_64

**Comment by oktophonie** [comment]
Fixed in 4.1 (perhaps by https://github.com/musescore/MuseScore/pull/17419 or similar)
