### ISSUE TITLE
[4.1] Aux sends values don't set to 0% when switching to VSTi, while aux sends are hidden

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#18221]
### Issue type

Other type of issue

### Bug description

A rule states that "If a user switches an instrument from MS Basic or Muse Sounds to a VSTi, then the Aux sends are automatically set to 0%". 
This is working if the aux sends are on display, however, this does NOT work if the aux sends are *hidden*. 

### Steps to reproduce

1. Open mixer with Muse sounds instruments and aux sends hidden
2. Switch from a muse sound to a VSTi
3. Display aux sends
4. See error on aux sends knobs

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/71656189/908fe76f-9e68-4ea9-bd7d-2939183f578c

### MuseScore Version

Latest nightly

### Regression

I don't know

### Operating system

macOS 13

**Comment by DmitryArefiev** [comment]
Fixed in #19275
