### ISSUE TITLE
Musescore 4 Crash (after selecting all notes and dragging them down/up with mouse, one score) 

### ISSUE THREAD

**Issue by flameshower** [musescore/MuseScore#18232]
### Issue type

Crash or freeze

### Bug description

In Musescore 4, when I try to shift a large amount of notes down a pitch, the program crashes.

### Steps to reproduce

1) Open [attached score](https://musescore.com/user/29123756/scores/6637980) in MS 4.0.2
2) Ctrl+A all notes
3) Drag them down a pitch
4) MS 4.0.2 crashes

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
I can confirm the crash when actually dragging the notes.  No crash when changing pitch normally with Down arrow, but also - the pitch doesn't change either (I think the tab staves get in the way of that).

**Comment by DmitryArefiev** [comment]
The same on my side:



https://github.com/musescore/MuseScore/assets/90187801/ed408f2c-bbb7-4e0a-9087-24287f79bbed

**Comment by zacjansheski** [comment]
I think the issue is Measure 89


<img width="217" alt="Screen Shot 2023-06-28 at 12 20 04 PM" src="https://github.com/musescore/MuseScore/assets/69917893/d0b935c7-899b-413f-9c47-3d549c416a38">

**Comment by oktophonie** [comment]
If useful, here's the guilty bar isolated (as a 4.1 file, where the crash still happens)
[daft-punk-crash.zip](https://github.com/musescore/MuseScore/files/11917704/daft-punk-crash.zip)
