### ISSUE TITLE
Aux 2 Audio effects do not turn off on individual instruments

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18230]
### Issue type

UI bug

### Bug description

Aux 2 Audio effects do not turn off on individual instruments.  This works on aux 1, not on aux 2.

### Steps to reproduce

1. Add an audio effect to an Aux 2 channel
2. Turn it off on an individual instrument (it will not turn off)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/eca7501b-dfe4-4320-a79c-31f17d794a24

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231781456, revision: github-musescore-musescore-e01f1e8

### Regression

I don't know

### Operating system

OS: macOS 11.6

**Comment by RomanPudashkin** [comment]
> Add an audio effect to an Aux 2 channel

In the video, you added the Delay effect to the **Master** channel, not to the aux 2 channel (which can be enabled from the tree dot menu). That's why you can't disable Delay using the aux 2 bypass button. This works as expected
