### ISSUE TITLE
System text and tempo text appear twice in custom parts when adding second instrument then first

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18231]
### Issue type

Engraving bug

### Bug description

In a custom part, if you add the second instrument in the score, then the first, tempo text and system text will appear twice.

### Steps to reproduce

1. Make a score with more than one part
2. Add tempo and system text
3. Create a custom part
4. Add instruments starting with the second instrument, then the first
5. Press M (if custom part has no notes)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/a51c2c5f-d0e8-49a1-824c-9921b1669556

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651546, revision: github-musescore-musescore-dbe7c6d

### Regression

No.

### Operating system

OS: macOS 11.6

**Comment by DmitryArefiev** [comment]
@zacjansheski I see this is fixed in #19773. Please reopen if you able to reproduce it on your side
