### ISSUE TITLE
Slides disappear in files imported from earlier MS versions (4.02 and before)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18240]
### Bug description

When importing an MS 4.02 file (or earlier) into MS 4.1, slides appear to disappear altogether (they are not merely invisible). However they still affect playback and you can still hear the timing glitch reported in #18176.

### Steps to reproduce

1. Open the attached MS4.02 score in both MS4.02 and MS 4.1. 
[slide_issues.zip](https://github.com/musescore/MuseScore/files/11892964/slide_issues.zip)
2. Note that in measure 6 there is a slide in MS4.02, but this has disappeared in MS 4.1
3. Play back measures 5 onwards.
4. Note the invisible slide still plays back (albeit wrongly) and that the timing glitch reported in #18176. is still apparent.

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231790502, revision: github-musescore-musescore-41a5ebe

### Regression

The slide was visible in MS 4.02 (although it  didn't playback correctly.

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by oktophonie** [comment]
The file was saved in 4.0.2, so can't be opened in 3.6.
Anyway. the slide remains in 4.1 but has ended up ridiculously thin:
![image](https://github.com/musescore/MuseScore/assets/20604032/695f2ce0-2532-4174-8da3-fbd080685b07)
which appears to be a regression on/missed case for https://github.com/musescore/MuseScore/issues/17610 - @mike-spa

**Comment by rgreen5** [comment]
Have corrected OP and title.
