### ISSUE TITLE
No playback on some notes in a volta repeat

### ISSUE THREAD

**Issue by Serge-45** [musescore/MuseScore#18253]
### Issue type

General playback bug

### Bug description

After modifying some notes in a sequence with a 1. and 2. volta, some subsequent notes are not played back anymore.
It could be similar to https://github.com/musescore/MuseScore/issues/17826 even if the procedure to reproduce is different.

### Steps to reproduce

Easy steps to follow in order to reproduce the bug from a new blank file:

1. Create this simple 3-measure piece from the default template:
![image](https://github.com/musescore/MuseScore/assets/33224328/b02e481e-8d40-4854-8d16-8f316ae68cd2)

2. Change note duration in the second measure by selecting the A note and typing "6"
![image](https://github.com/musescore/MuseScore/assets/33224328/28607556-808f-43fc-8499-2cd3736ebcf8)

3. Suppress the first note (B) by selecting the B and typing "0"
![image](https://github.com/musescore/MuseScore/assets/33224328/c216b670-15e4-4638-8b91-881c8f0e441d)

4. Restore the first note by typing Ctrl-Z
![image](https://github.com/musescore/MuseScore/assets/33224328/5bbe6385-8cc4-4160-a2c5-02b2baa5e99d)

5. Start playback with the "space" key
==> the G on the third measure is not played.

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231790501, revision: github-musescore-musescore-41a5ebe

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

### Additional context

This happens quite frequently after modifying notes but not always. No obvious reason why. In some cases, the muted notes are in the 1. volta.
Changing the pitch or duration of the silent notes often makes them back to normal.
Saving and reloading the file makes as well everything working well.

**Comment by zacjansheski** [comment]
Confirmed


https://github.com/musescore/MuseScore/assets/69917893/5e556a92-304b-44d8-ab63-fe205f2fb0b5
