### ISSUE TITLE
[4.1] Toggle buttons are wrong colour

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#18274]
### Issue type

UI bug

### Bug description

A tiny issue that the toggle button - particularly in dark mode do not match the design requirements. The white colour should be WHITE_COLOUR on both themes:
<img width="1015" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/87905342-f1f6-47cd-9933-9d3cca737f63">
<img width="990" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/ab9ab145-dbd3-46a2-8bf5-a0e384da117b">

### Steps to reproduce

1. Turn app into dark mode.
2. Go to Dev Tools
3. Go to UI Gallery
4. Scroll down to Toggle Button. see colour error

### Screenshots/Screen recordings

In latest master the toggle button currently looks like this - which appears okay in light mode but it's wrong in dark mode: 
<img width="121" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/5eb74907-c1f3-427d-8c49-c83c8f9a07cf">
<img width="125" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/83360a0c-9e3f-4a5d-8bbd-298abc031510">

All the circle shapes should be white_colour.

### MuseScore Version

Latest master

### Regression

No.

### Operating system

macOS 13

**Comment by jessjwilliamson** [comment]
@HemantAntony Would be great to look at this please!

**Comment by HemantAntony** [comment]
@jessjwilliamson check #18275 :)
