### ISSUE TITLE
How to achieve batch convert for transposing chromatically to key in cmd?

### ISSUE THREAD

**Issue by monetjoe** [musescore/MuseScore#18272]
### Your idea

For windows users, the musescore.exe should support batch convert for transposing chromatically to key in cmd,
so that users can call this function in Python to make mxl score data augmentation.

### Problem to be solved

Update doc for batch convert for transposing chromatically to key in cmd to let users know how to use this function
or
develop this new function in musescore.exe and let users know how to use it

**Comment by GunGunGun** [comment]
I support this, MuseScore should support batch converting because this is 2023, we are in the world of AI so manual should be keep minimal to save time.

**Comment by cbjeukendrup** [comment]
MuseScore already supports batch conversion, since ages actually. However, it does not yet support specific "score transformations" in that, which is what this issue is about specifically.

**Comment by GunGunGun** [comment]
> MuseScore already supports batch conversion, since ages actually. However, it does not yet support specific "score transformations" in that, which is what this issue is about specifically.

I know it supports `-j` to batch convert `JSON jobs`, but I'm curious what is its limitations (maximum number of files and such) ?

**Comment by GunGunGun** [comment]
Plus the command-line needs a lot of improments, for example converting from v1 sheet to midi, the program just crashes in this case.

And there's even memory leak when working with `-j` to batch convert multiple sheets, memory just keep increasing because the program doesn't even try to free up unused memory from previous convert jobs.

**Comment by m41w4r3exe** [comment]
It is nearly impossible to batch convert with MuseScore 4, I can never manage to make it work, I would be really happy to hear if anybody could manage to do it. There are basically no logs, no output (even with -d option) it just crashes with no converting. Also unhandled memory leak is an issue as mentioned.

With MuseScore 3, it somehow works slightly better, at least there is output, yet it is still cumbersome, I can only convert hundreds of scores, but always fails when I try to convert thousands.

Some improvements to batch converting would be highly appreciated!

**Comment by nikbucher** [comment]
@m41w4r3exe I have had similar experiences. It worked for me with MuseScore 3, but so far, I haven't been able to get it to work with MuseScore 4. :-(

**Comment by monetjoe** [comment]
Hey guys~ Is the batch transpose working with MS 3.x mentioned by you here? https://musescore.org/en/project/batch-transpose

@nikbucher @GunGunGun @m41w4r3exe @cbjeukendrup 

Although we can call that plugin in cmd by:
"C:\Program Files\MuseScore 3\bin\MuseScore3.exe" -p BatchTranspose.qml -o test2.pdf test2.mscz

It looks like only one interval can be set in the .qml per batch transpose
![image](https://github.com/user-attachments/assets/35d2083e-ce31-4d83-b4e6-391b61eb4f02)

To get the transpose in 15 different keys, we first need to determine the original key of the sheet music to figure out the other 14 keys. Then, we need to prepare the necessary intervals, which might involve having ±12 intervals ready in QML for batch transposing into 15 different keys. This process is quite complex but feasible.

**Comment by pacebes** [comment]
HI

I have a preliminar version of a patch that could do what you asked for: [patchForTransposingChromaticallyToKeyInCmd.zip](https://github.com/user-attachments/files/17309961/patchForTransposingChromaticallyToKeyInCmd.zip)

It adds a new command line parameter "-c" (from chromatic ) to specify the desired translation with a number
- Always Transpose Chromatically By Interval
- The number identifies (see the image) the type of translation . 4 for "Major Second" up, -4 for "Major Second" down, 12 for "augmented fourth" up and 12 for "augmented fourth" down
- So, "/MuseScore4.exe -c -3 -o output2-3.mscz test2.mscz" will create the file "output2-3.mscz" from the file test2.mscz and will transpose down with a "Minor second" ( [test2.zip](https://github.com/user-attachments/files/17310097/test2.zip) )

![TransposeByIntervalOptions](https://github.com/user-attachments/assets/0ccb5410-3757-4244-92bd-3aa0a1a6092d)

This patch has made many assumptions and needs to be debugged before going on a pull requests. I think this code needs to be checked before continuing the work. The way the command line option has been added should also be reviewed.

I would appreciate any feedback

**Comment by jeetee** [comment]
A separate transpose command line option makes no sense imho. Using the plugin approach would be way more flexible. Certainly when you keep in mind that you can create transposed mscz's and then use them as input for a next round of transposing.

**Comment by pacebes** [comment]
HI

I'll work on some changes to allow the parameter in a ".json" file. It shouldn't be difficult.  I also need feedback about if something like this could be acceptable (value with the same meaning as in previous coments). Same for the way I have "solved" it.

```
[
    {
        "in": "test1.mscz",
        "out": "test1o.pdf",
        "ct": "-3"
    }
]

```

**Comment by pacebes** [comment]
Hi

I have just made a patch that supports both ways. Command line (as described before) and a json task job such as:

> [
>     {
>         "in": "test3.mscz",
>         "out": "test3.musicxml"
>     },
>     {
>         "in": "test3.mscz",
>         "out": "test3.pdf"
>     },
>     {
>         "in": "test1.mscz",
>         "out": "test1-3.mscz",
>         "ct": "-3"
>     }
> ]
> 
> 

As I commented before this is just to test if this can be done. Some MuseScore people should check if this is the right way to be done as well as if the way to define the interval could be done this way.

Current patch:

```
pacebes@cozuelos:/C/D/MuseScore$ git diff
diff --git a/src/app/cmdoptions.h b/src/app/cmdoptions.h
index 48fd78ad1f..9f2e4c13e0 100644
--- a/src/app/cmdoptions.h
+++ b/src/app/cmdoptions.h
@@ -108,6 +108,12 @@ struct CmdOptions {
         QMap<ParamKey, QVariant> params;
     } converterTask;

+
+    struct {
+        std::optional<int> intervalListNumber;
+    } transpose;
+
+
     struct Diagnostic {
         DiagnosticType type = DiagnosticType::Undefined;
         QStringList input;
diff --git a/src/app/internal/commandlineparser.cpp b/src/app/internal/commandlineparser.cpp
index 2217a0b060..58c32b5efb 100644
--- a/src/app/internal/commandlineparser.cpp
+++ b/src/app/internal/commandlineparser.cpp
@@ -1,3 +1,4 @@
+/*
 /*
  * SPDX-License-Identifier: GPL-3.0-only
  * MuseScore-Studio-CLA-applies
@@ -27,6 +28,7 @@
 #include "global/internal/baseapplication.h"

 #include "log.h"
+#include "engraving/dom/utils.h"

 using namespace muse;
 using namespace mu::app;
@@ -84,6 +86,7 @@ void CommandLineParser::init()
     // Converter mode
     m_parser.addOption(QCommandLineOption({ "r", "image-resolution" }, "Set output resolution for image export", "DPI"));
     m_parser.addOption(QCommandLineOption({ "o", "export-to" }, "Export to 'file'. Format depends on file's extension", "file"));
+    m_parser.addOption(QCommandLineOption({ "c", "transpose-chromatically" }, "Chromatic transposing to a file", "numberOfIntervals"));
     m_parser.addOption(QCommandLineOption({ "j", "job" }, "Process a conversion job", "file"));
     m_parser.addOption(QCommandLineOption("extension", "Use extension to process a conversion job", "uri"));

@@ -295,6 +298,22 @@ void CommandLineParser::parse(int argc, char** argv)
         }
     }

+    if (m_parser.isSet("c")) {
+
+        std::optional<int> val = intValue("c");
+        if (val) {
+            m_options.transpose.intervalListNumber = val;
+        }
+        else {
+           LOGE() << "Option: -c not recognized intervalListNumber" << m_parser.value("c");
+        }
+
+        if ( abs(m_options.transpose.intervalListNumber.value()) > (mu::engraving::intervalListSize-1)) {
+            LOGE() << "Maximun interval number " << (mu::engraving::intervalListSize - 1);
+        }
+    }
+
+
     if (m_parser.isSet("P")) {
         if (m_options.converterTask.outputFile.isEmpty()) {
             LOGE() << "Option: -R no output file specified";
diff --git a/src/app/internal/consoleapp.cpp b/src/app/internal/consoleapp.cpp
index cebb244d1e..ce2388bf05 100644
--- a/src/app/internal/consoleapp.cpp
+++ b/src/app/internal/consoleapp.cpp
@@ -280,7 +280,7 @@ int ConsoleApp::processConverter(const CmdOptions::ConverterTask& task)
         ret = converter()->batchConvert(task.inputFile, stylePath, forceMode, soundProfile, extensionUri);
         break;
     case ConvertType::File:
-        ret = converter()->fileConvert(task.inputFile, task.outputFile, stylePath, forceMode, soundProfile, extensionUri);
+        ret = converter()->fileConvert(task.inputFile, task.outputFile, stylePath, forceMode, soundProfile, extensionUri, m_options.transpose.intervalListNumber.value());
         break;
     case ConvertType::ConvertScoreParts:
         ret = converter()->convertScoreParts(task.inputFile, task.outputFile, stylePath);
diff --git a/src/converter/iconvertercontroller.h b/src/converter/iconvertercontroller.h
index 1d4427715e..df698cc137 100644
--- a/src/converter/iconvertercontroller.h
+++ b/src/converter/iconvertercontroller.h
@@ -38,7 +38,8 @@ public:
     virtual muse::Ret fileConvert(const muse::io::path_t& in, const muse::io::path_t& out,
                                   const muse::io::path_t& stylePath = muse::io::path_t(), bool forceMode = false,
                                   const muse::String& soundProfile = muse::String(),
-                                  const muse::UriQuery& extensionUri = muse::UriQuery()) = 0;
+                                  const muse::UriQuery& extensionUri = muse::UriQuery(),
+                                  int transposeIntervalListNumber = 0) = 0;

     virtual muse::Ret batchConvert(const muse::io::path_t& batchJobFile,
                                    const muse::io::path_t& stylePath = muse::io::path_t(), bool forceMode = false,
diff --git a/src/converter/internal/convertercontroller.cpp b/src/converter/internal/convertercontroller.cpp
index 67dcc832a2..318ddf7f26 100644
--- a/src/converter/internal/convertercontroller.cpp
+++ b/src/converter/internal/convertercontroller.cpp
@@ -1,3 +1,4 @@
+/*
 /*
  * SPDX-License-Identifier: GPL-3.0-only
  * MuseScore-Studio-CLA-applies
@@ -33,6 +34,8 @@
 #include "convertercodes.h"
 #include "compat/backendapi.h"

+#include "engraving/dom/utils.h"
+
 #include "log.h"

 using namespace mu::converter;
@@ -73,7 +76,17 @@ Ret ConverterController::batchConvert(const muse::io::path_t& batchJobFile, cons
             progress->progressChanged.send(current, total, job.in.toStdString());
         }

-        Ret ret = fileConvert(job.in, job.out, stylePath, forceMode, soundProfile, extensionUri);
+        std::string optionCT = job.optionCT.toStdString();
+        int intervalListNumber = 0;
+
+        if (optionCT.length() == 0) {
+            intervalListNumber = 0;
+        }
+        else {
+            intervalListNumber = std::stoi(optionCT);
+        }
+
+        Ret ret = fileConvert(job.in, job.out, stylePath, forceMode, soundProfile, extensionUri, intervalListNumber);
         if (!ret) {
             errors.emplace_back(String(u"failed convert, err: %1, in: %2, out: %3")
                                 .arg(String::fromStdString(ret.toString())).arg(job.in.toString()).arg(job.out.toString()));
@@ -95,11 +108,12 @@ Ret ConverterController::batchConvert(const muse::io::path_t& batchJobFile, cons
 }

 Ret ConverterController::fileConvert(const muse::io::path_t& in, const muse::io::path_t& out, const muse::io::path_t& stylePath,
-                                     bool forceMode, const String& soundProfile, const muse::UriQuery& extensionUri)
+                                     bool forceMode, const String& soundProfile, const muse::UriQuery& extensionUri, int transposeIntervalListNumber)
 {
     TRACEFUNC;

     LOGI() << "in: " << in << ", out: " << out;
+
     auto notationProject = notationCreator()->newProject(iocContext());
     IF_ASSERT_FAILED(notationProject) {
         return make_ret(Err::UnknownError);
@@ -134,6 +148,14 @@ Ret ConverterController::fileConvert(const muse::io::path_t& in, const muse::io:
     // standart convert
     else {
         if (suffix == engraving::MSCZ || suffix == engraving::MSCX || suffix == engraving::MSCS) {
+
+            // Only available values
+            if ( (transposeIntervalListNumber != 0) && (abs(transposeIntervalListNumber) < mu::engraving::intervalListSize ) )
+            {
+                notationProject->transposeScore(transposeIntervalListNumber);
+            }
+
+            LOGI() << "notationProject save ";
             return notationProject->save(out);
         }

@@ -219,6 +241,7 @@ RetVal<ConverterController::BatchJob> ConverterController::parseBatchJob(const m
         Job job;
         job.in = correctUserInputPath(obj["in"].toString());
         job.out = correctUserInputPath(obj["out"].toString());
+        job.optionCT = obj["ct"].toString();

         if (!job.in.empty() && !job.out.empty()) {
             rv.val.push_back(std::move(job));
diff --git a/src/converter/internal/convertercontroller.h b/src/converter/internal/convertercontroller.h
index f67394c380..5cf97f6eba 100644
--- a/src/converter/internal/convertercontroller.h
+++ b/src/converter/internal/convertercontroller.h
@@ -22,6 +22,7 @@
 #ifndef MU_CONVERTER_CONVERTERCONTROLLER_H
 #define MU_CONVERTER_CONVERTERCONTROLLER_H

+#include <list>
 #include <list>

 #include "../iconvertercontroller.h"
@@ -51,7 +52,8 @@ public:
     muse::Ret fileConvert(const muse::io::path_t& in, const muse::io::path_t& out,
                           const muse::io::path_t& stylePath = muse::io::path_t(), bool forceMode = false,
                           const muse::String& soundProfile = muse::String(),
-                          const muse::UriQuery& extensionUri = muse::UriQuery()) override;
+                          const muse::UriQuery& extensionUri = muse::UriQuery(),
+                          int transposeIntervalListNumber = 0) override;

     muse::Ret batchConvert(const muse::io::path_t& batchJobFile,
                            const muse::io::path_t& stylePath = muse::io::path_t(), bool forceMode = false,
@@ -82,6 +84,7 @@ private:
     struct Job {
         muse::io::path_t in;
         muse::io::path_t out;
+        muse::String optionCT;
     };

     using BatchJob = std::list<Job>;
diff --git a/src/project/inotationproject.h b/src/project/inotationproject.h
index a68582da2a..0edc74a35a 100644
--- a/src/project/inotationproject.h
+++ b/src/project/inotationproject.h
@@ -77,6 +77,8 @@ public:

     virtual notation::IMasterNotationPtr masterNotation() const = 0;
     virtual IProjectAudioSettingsPtr audioSettings() const = 0;
+
+    virtual void transposeScore (int transposeIntervalListNumber = 0) = 0;
 };

 using INotationProjectPtr = std::shared_ptr<INotationProject>;
diff --git a/src/project/internal/notationproject.cpp b/src/project/internal/notationproject.cpp
index c30076c1c7..589f13455e 100644
--- a/src/project/internal/notationproject.cpp
+++ b/src/project/internal/notationproject.cpp
@@ -459,6 +459,30 @@ void NotationProject::setCloudAudioInfo(const CloudAudioInfo& audioInfo)
     m_masterNotation->masterScore()->setMetaTag(AUDIO_COM_URL_TAG, audioInfo.url.toString());
 }

+void NotationProject::transposeScore(int transposeIntervalListNumber )
+{
+    TransposeOptions options;
+
+    options.mode = TransposeMode::BY_INTERVAL;
+
+    if (transposeIntervalListNumber < 0)
+    {
+        options.direction = TransposeDirection::DOWN;
+    }
+    else {
+        options.direction = TransposeDirection::UP;
+    }
+    options.interval = abs(transposeIntervalListNumber);
+    options.key = Key::C;
+    options.needTransposeKeys = true;
+    options.needTransposeChordNames = false;
+    options.needTransposeDoubleSharpsFlats = true;
+
+    m_engravingProject->masterScore()->cmdSelectAll();
+    m_engravingProject->masterScore()->transpose(options.mode, options.direction, options.key, options.interval, options.needTransposeKeys, options.needTransposeChordNames,
+        options.needTransposeDoubleSharpsFlats);
+}
+
 Ret NotationProject::save(const muse::io::path_t& path, SaveMode saveMode)
 {
     TRACEFUNC;
diff --git a/src/project/internal/notationproject.h b/src/project/internal/notationproject.h
index 3f2600e614..609f2f8347 100644
--- a/src/project/internal/notationproject.h
+++ b/src/project/internal/notationproject.h
@@ -38,6 +38,8 @@
 #include "notation/inotationconfiguration.h"
 #include "projectaudiosettings.h"
 #include "iprojectmigrator.h"
+#include "notation/notationtypes.h"
+

 namespace mu::engraving {
 class MscReader;
@@ -100,6 +102,9 @@ public:
     notation::IMasterNotationPtr masterNotation() const override;
     IProjectAudioSettingsPtr audioSettings() const override;

+    virtual void transposeScore(int transposeIntervalListNumber = 0) override;
+
+
 private:
     void setupProject();

@@ -119,6 +124,7 @@ private:
     void listenIfNeedSaveChanges();
     void markAsSaved(const muse::io::path_t& path);
     void setNeedSave(bool needSave);
+    void transposeScore();

     mu::engraving::EngravingProjectPtr m_engravingProject = nullptr;
     notation::IMasterNotationPtr m_masterNotation = nullptr;
```

**Comment by pacebes** [comment]
Hi @cbjeukendrup 

Do yo think we should create a PR ?.  Should it include only the "json" way to transpose a score or should it also include the command line option as well?.

**Comment by cbjeukendrup** [comment]
This may need a bit of thought, to ensure that the JSON format stays consistent and extensible. For example, the name "ct" is perhaps too cryptic. And of course it would be logical to support other transpose types (i.e. other than chromatic) too. 

And, on the one hand, I agree with @jeetee, that it would be questionable to introduce new transpose functionality while that can already be achieved in a much more general way, namely using plugins. 
On the other hand, transposing a score is a relatively common operation, so if anyone who wants to do that needs to write their own plugin just for that, that is not ideal either.

So, I think we should generalise the concept of "transformations". Right now there would be two types of transformations supported:
- transpose (which would have some sub-options for chromatic / diatonic / to-key)
- apply a plugin

A suitable JSON schema might look like this:
```json
[
    {
        "in": "test.mscz",
        "out": "test.pdf",
        "transform": [
            {
                "type": "transpose",
                "options": {
                    "to_key": "…" // or: "by_interval" or "diatonically"; see also BackendApi::parseTransposeOptions
                }
            },
            {
                "type": "plugin",
                "options": {
                    "uri": … // to be implemented later
                }
            }
        ]
    }
]
```
Since "transform" takes an array, this would make it possible to apply multiple transformations to the same score; built-in ones, like "transpose", but also plugins. 

Regarding implementation: it would be great if it can be implemented in such way that more kinds of transformations can easily be added in the future. 

The next question is of course how to do this with the non-batch CLI option. One option is that we let people specify transforms in a JSON string. In fact, that is how the `--score-transpose` option currently does it. I'd not literally reuse the syntax from that option, but rather reuse the format of the batch convert command, for example
```
mscore input.mscz --transform '[{"type":"transpose","options":{"by_interval":3}}]' -o output.mscz
```

Does this sound like a good idea? Or is it naive or overcomplicated? Do we think one "transformation" at a time is enough, because it people want multiple they can create a plugin?

**Comment by pacebes** [comment]
Thanks a lot @cbjeukendrup 

It seems a bit obvious now but I didn't know (yes, it was really obvious) that it was already implemented and in a much better way than my code.

Now
- I have read "https://musescore.org/en/node/341539"
- I have installed jq from https://jqlang.github.io/jq/download/
- I have installed base64 from https://sourceforge.net/projects/base64-for-windows/
- And then the following command works:
`./MuseScore4.exe --score-transpose  '{"mode": "by_interval", "direction": "up", "transposeInterval": 12, "transposeKeySignatures": true}' test1.mscz |  jq -r '.mscz'| base64 -i -d  > transposed_test.mscz

I can open the "transposed_test.mscz" with MuseScore and it is a right transposed file.

It seems that the "--score-transpose" mode allows all kind of transposing. So, this issue is about ...???
- Adding these options to a json file so..
-- You can to "pipe" output of a process as an input to the next 
-- You can in one step decide that the output is a PDF or a transposed mscz or ...
- Decide the syntax of the transposing options 
- ...

I suppose it is up to @monetjoe  to give his opinion as he was the creator of the issue

Anyway, I am interested in implementing this issue once it is clear what to implement with your support.

**Comment by monetjoe** [comment]
> Thanks a lot @cbjeukendrup
> 
> It seems a bit obvious now but I didn't know (yes, it was really obvious) that it was already implemented and in a much better way than my code.
> 
> Now
> 
> * I have read "https://musescore.org/en/node/341539"
> * I have installed jq from https://jqlang.github.io/jq/download/
> * I have installed base64 from https://sourceforge.net/projects/base64-for-windows/
> * And then the following command works:
>   `./MuseScore4.exe --score-transpose  '{"mode": "by_interval", "direction": "up", "transposeInterval": 12, "transposeKeySignatures": true}' test1.mscz |  jq -r '.mscz'| base64 -i -d  > transposed_test.mscz
> 
> I can open the "transposed_test.mscz" with MuseScore and it is a right transposed file.
> 
> It seems that the "--score-transpose" mode allows all kind of transposing. So, this issue is about ...???
> 
> * Adding these options to a json file so..
>   -- You can to "pipe" output of a process as an input to the next
>   -- You can in one step decide that the output is a PDF or a transposed mscz or ...
> * Decide the syntax of the transposing options
> * ...
> 
> I suppose it is up to @monetjoe to give his opinion as he was the creator of the issue
> 
> Anyway, I am interested in implementing this issue once it is clear what to implement with your support.

Thanks a lot for your efforts on this issue, here are some features that we may care about:
1. Does MuseScore3 also support --score-transpose arg with such JSON?
2. Does it also work in systems without UI? (For example UIless Linux)

I ever tried to use plugin mode to conduct command line transposing by "*\MuseScore3.exe" -p BatchTranspose.qml -o output.mscz input.mscz, it is highly relied on Qt UI. I ever successfully exported a score on that way, but the output score had no difference to the input score, which means it did not make any change on the score, the plugin did not take effect but only the MuseScore main exe was working. So I did not trust "-p" mode, your "--score-transpose" way may be a good alternative.

**Comment by cbjeukendrup** [comment]
- MuseScore 3 should also support `--score-transpose` indeed. However, I realised that this option is currently broken; a fix has been merged into the master branch (4.5) but I'm not yet sure whether we can also backport it to 4.4.3.
- This option works without GUI; it is used for the MuseScore.com backend, which of course runs in a GUI-less environment. 
- In a future version of MuseScore, we will introduce a new plugin framework; with this framework, plugins that don't _need_ a GUI will be better able to run indeed in a completely GUI-less mode.

**Comment by pacebes** [comment]
So...

Is there something to be done in this issue ?

**Comment by cbjeukendrup** [comment]
Perhaps not really pressingly, since it is / will be possible to achieve the goal using the `--score-transpose` option. However, this option is actually rather meant for the MuseScore.com backend, which is also the reason that it exports to JSON rather than to a file in the desired format. So it would be nice to implement a more user-friendly transpose option. 

Regarding what I said above about a "transformation" option: I think it is overcomplicated. Any compound transformation pipeline can be achieved by writing a plugin. Instead, I would propose the addition of a simple `--transpose` option, that works together with `-o`, and accepts the same JSON format as `--score-transpose`. For the `-j` JSON format, it could be done like this:
```json
[
    {
        "in": "test.mscz",
        "out": "test.pdf",
        "transpose": {
            // same format as `--score-transpose`
        }
    },
]
```

**Comment by cbjeukendrup** [comment]
@pacebes Exactly! I'll assign this to you then. 

When you're ready, feel free to open a Pull Request directly; giving feedback on a pull request is more convenient than giving feedback on a patch in a comment.

**Comment by pacebes** [comment]
PR created

Command line option including options inline:
`./MuseScore4.exe -o output.mscz --transpose  '{"mode": "by_interval", "direction": "up", "transposeInterval": 12, "transposeKeySignatures": true}' test1.mscz
`

Command line option with json :
`./MuseScore4.exe -j procesa.json`

working json example:
```

[
    {
        "in": "test1.mscz",
        "out": "test1-12.mscz",
        "transpose": {
			"mode": "by_interval", 
			"direction": "up", 
			"transposeInterval": 12, 
			"transposeKeySignatures": true
			}
    },
    {
        "in": "test1.mscz",
        "out": "test1-12.pdf",
        "transpose": {
			"mode": "by_interval", 
			"direction": "up", 
			"transposeInterval": 12, 
			"transposeKeySignatures": true
        }
    },
    {
        "in": "test1-12.mscz",
        "out": "test1--12.mscz",
        "transpose": {
			"mode": "by_interval", 
			"direction": "down", 
			"transposeInterval": 12, 	
			"transposeKeySignatures": true
        }
    },
    {
        "in": "test1-12.mscz",
        "out": "test1--12.pdf",
        "transpose": {
         "mode": "by_interval", 
		 "direction": "down", 
		 "transposeInterval": 12, 
		 "transposeKeySignatures": true
        }
    },
    {
        "in": "test2.mscz",
        "out": "test2.pdf"
    },
    {
        "in": "test3.mscz",
        "out": "test3.musicxml"
    }
]

```

**Comment by PRamoneda** [comment]
Thanks for this PR @pacebes! Do you know if this is already working in Muusescore 4.4.4?   I am trying it with a python script and it doesn't work 
`import os
import subprocess
import json
import base64

# Ruta de MuseScore en Mac
MUSESCORE_PATH = "/Applications/MuseScore 4.app/Contents/MacOS/mscore"

# Archivos de entrada y salida
INPUT_FILE = "example.musicxml"
OUTPUT_JSON = "musescore_output.json"
OUTPUT_MSCZ = "example_transposed.mscz"
PROCESS_JSON = "process.json"

# Crear el archivo JSON para MuseScore
process_data = [
    {
        "in": INPUT_FILE,
        "out": OUTPUT_MSCZ,
        "transpose": {
            "mode": "by_interval",
            "direction": "up",
            "transposeInterval": 6,
            "transposeKeySignatures": True
        }
    }
]

with open(PROCESS_JSON, "w") as f:
    json.dump(process_data, f, indent=4)

print(f"Archivo JSON creado: {PROCESS_JSON}")

# Ejecutar MuseScore con el archivo JSON
command = [
    MUSESCORE_PATH,
    "-j", PROCESS_JSON
]
print(f"Ejecutando comando: {' '.join(command)}")

result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
`

**Comment by pacebes** [comment]
> Thanks for this PR [@pacebes](https://github.com/pacebes)! Do you know if this is already working in Muusescore 4.4.4? I am trying it with a python script and it doesn't work
> 

Hi @PRamoneda . It seems that it does not work with 4.4.4. I have tested with 4.5.0 prerelease (OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.5.0-, revision: github-musescore-musescore-) and it works with the following json:

```
[
    {
        "in": "example.musicxml",
        "out": "example_transposed.mscz",
        "transpose": {
            "mode": "by_interval",
            "direction": "up",
            "transposeInterval": 6,
            "transposeKeySignatures": true
        }
    }
]

```

Please, take into account that "true" is in lowercase ("true" instead of "True"). Otherwise you would get:

`2025-01-30T08:09:20.966 | ERROR | main_thread     | ConsoleApp::processConverter | failed convert, error: [1302] illegal number`

**Comment by FrancRos31** [comment]
> Do you know if this is already working in Muusescore 4.4.4?

This PR belongs to the 4.5 project, it shouldn't work in the 4.4.4. Check the 4.5 nightly builds.

**Comment by PRamoneda** [comment]
Thank you so much to all!! This is working

**Comment by SashaOv** [comment]
I tried this with [today's nightly PDF](https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/MuseScore-Studio-Nightly-latest-4.5.0-x86_64.paf.exe) and it did nothing when given a JSON job. The JSON job support seems to be broken.

**Comment by FrancRos31** [comment]
@SashaOv I suggest you to open a new report if you're still experiencing this.
