### ISSUE TITLE
Special Character Behavior Issue

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18285]
### Issue type

UI bug

### Bug description

Special character entry is broken.  This worked in 4.0.2 and is broken in the nightly

### Steps to reproduce

1. Add special characters to text, add various types.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/952ea2a7-8f94-419a-88b1-7094d0dccb82

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651546, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, worked in previous version of 4

### Operating system

Mac OS 11.6, Windows 11, Ubuntu 20.04.6

**Comment by cbjeukendrup** [comment]
Specifically, if you enter a SMuFL character and _then_ a Unicode character, that doesn't work. 

It looks like this has been caused by 2a1db7aa5dc2b0514203225f0efe76fe82e4769f.
