### ISSUE TITLE
Missing dialog when adding 'extra' note within space of tuplet

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#18288]
### Issue type

UI bug

### Bug description

It used to be that if you added an extra, bar-stretching note (by Ctrl+clicking) in a position that fell inside a tuplet (in any stave), you'd get this dialog:
![image](https://github.com/musescore/MuseScore/assets/20604032/16d85bea-b306-4817-8ae3-c3c7da18d4d0)

But now it just fails silently. This is another example of https://github.com/musescore/MuseScore/issues/12887 and I'd guess has a very similar fix.

### MuseScore Version

4.1.0

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Linux

**Comment by cbjeukendrup** [comment]
Actually I'm seeing even more worrying behaviour at the moment, making the score totally corrupted...

https://github.com/musescore/MuseScore/assets/48658420/4b931fba-53e0-4306-bf54-0e35ff32ef08
