### ISSUE TITLE
[4.0.2] Update close message needs spaces

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#18298]
### Issue type

UI bug

### Bug description

After installing an update from within MuseScore, the popup telling you to close the app is missing spaces after punctuation.

Text as it appears:
"MuseScore needs to close to complete the installation.If you have any unsaved changes,you will be prompted to save them before MuseScore closes."

Fixed text:
"MuseScore needs to close to complete the installation. If you have any unsaved changes, you will be prompted to save them before MuseScore closes."

### Steps to reproduce

1. Install an update
2. See that spaces are missing after punctuation in the popup

### Screenshots/Screen recordings

<img width="520" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/c8f7da22-dd42-424c-b3c5-346d7f96e049">

### MuseScore Version

4.0.2, updating to 4.0.2-230651546

### Regression

I don't know

### Operating system

macOS 12.6, Arch.: x86_64

**Comment by cbjeukendrup** [comment]
This is the same problem as https://github.com/musescore/MuseScore/issues/16533, which will be fixed in 4.1.

**Comment by avvvvve** [comment]
Didn't see that one - thanks!
