### ISSUE TITLE
No thumbnail when Ctrl+Shift+Dragging an element

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#18294]
When Ctrl+Shift+Dragging an element to copy it (to a different place or to the Palettes), there is no thumbnail image of the element being dragged. Instead, there is only a white 2x2 pixmap. 

In case anyone from the community would like to give this a try: the relevant code is in `NotationInteraction::startDragCopy`. One can take inspiration from `PaletteCellIconEngine`.

**Comment by re1san** [comment]
Hey, I would like to work on it :)
