### ISSUE TITLE
Ctrl+E and "Add / Text / Expression text" still add staff text

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#18301]
### Issue type

Engraving bug

### Bug description

The new expression text type is very nice, and I see we are automatically mapping old staff text with expression text style to it.  But, Ctrl+E and "Add / Text / Expressions text" still add the old-style staff text.

### Steps to reproduce

1. new score
2. select first measure rest
3. Pres Ctrl+E and type some text
4. Look at status bar

Result: it's staff text, not expression text.  Same for Add / Text / Expression text, and also the "+" menu on the toolbar (all of the share the same command code, so not surprising).  So if you add it where there is a dynamic, it isn't laid out like expression text should be either.

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231790502, revision: github-musescore-musescore-41a5ebe

### Regression

No.

### Operating system

Linux / Debian 11

**Comment by rgreen5** [comment]
Related: #16822?

**Comment by cbjeukendrup** [comment]
> Related: #16822?

Not quite; that issue is just about what it _says_ in the status bar, but this issue is about what it really _is_ under the hood. And in this case, the difference is not just which text style it uses, but since 4.1, expression text is really a separate kind of element.
