### ISSUE TITLE
MuseScore 4.0.2 - Software Fails to Launch, Stuck on Loading Splash Screen

### ISSUE THREAD

**Issue by Wasans1** [musescore/MuseScore#18316]
### Issue type

Crash or freeze

### Bug description

When attempting to open MuseScore 4.0.2, the software gets stuck on the loading splash screen and fails to launch.

The issue occurs specifically on a laptop model Vivobook_ASUSLaptop M6500QC_M6500QC with Realtek(R) Audio. Window version: 22H2(OS build 22621.1848)

### Steps to reproduce

1. Go to the MuseScore 4.0.2 installation folder.
2. Double-click on the MuseScore executable file to launch the application.
3. Observe that the MuseScore splash screen appears with the message "loading".
4. Wait for some time, and notice that the splash screen closes without launching the software.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/138212900/e7c43936-0ffa-42ae-bdee-6ac63880e8fe)
there is not much thing to show. splash screen just closes after about 1 second.

### MuseScore Version

4.02

### Regression

I don't know

### Operating system

Windows 11

### Additional context

Windows 11 (10.0.22621 Build 22621)
AMD Ryzen 7 5800H with Radeon Graphics, 3201Mhz
NVIDIA GeForce RTX 3050 Laptop GPU
16GB RAM
[logs.zip](https://github.com/musescore/MuseScore/files/11915758/logs.zip)

**Comment by cbjeukendrup** [comment]
Please try the beta version of 4.1 or the "nightly builds": see respectively https://musescore.org/en/node/351505 and https://musescore.org/en/nightly-builds.

**Comment by Wasans1** [comment]
It works!!!!! Thank you so much. I love u
