### ISSUE TITLE
Tremolo stem direction does not update in Properties panel when tremolos are flipped with keyboard shortcut

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#18312]
(Spun off from https://github.com/musescore/MuseScore/pull/18259; thanks to @LupusCaeruleus for the original)

### Issue type

UI bug

### Bug description

Unlike independent notes, pressing X to flip the tremolo beam will not update the state of the Stem direction buttons in the properties panel. The buttons will only update after the user de-select and re-select the tremolo notes.

### Steps to reproduce

1. Select a tremolo beam, press X for multiple times.
2. See the Stem direction buttons in the properties panel.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/20604032/e8ef884d-fff1-4ed7-b2fd-dd6d5b9c86d1

### MuseScore Version

4.1.0

### Regression

No.

### Operating system

Windows 10, Linux

**Comment by wizofaus** [comment]
Looks like a simple fix, happy to put my hand up for it.

**Comment by cbjeukendrup** [comment]
@wizofaus That would be great! Shouldn't be too complicated indeed, see for example `StemSettingsModel::onNotationChanged` for inspiration
