### ISSUE TITLE
MS4.1-Beta2 Linux: Playback audio starts to crackle, slows, and ultimately stalls if Aux-sends Reverb is first enabled, then later disabled

### ISSUE THREAD

**Issue by ShawTakeuchi** [musescore/MuseScore#18332]
### Issue type

General playback bug

### Bug description

**Problem:**

Playback with and without reverb is stable.  However, if reverb is enabled during playback, then later disabled, the audio starts to crack, and the playback tempo slows to a stall.
  
**Environment:**

*  Linux MS4.1-Beta2 2023-06-30 Pre-release nightly
*  MuseSounds w/ Muse-hub Beta 2023-06-30 (hub 1.0.1.450)  
*  Ubuntu Studio 22.04/LTS
*  Dell Latitude i5-M560/2.67GHz, 4-cores, 4GB, SSD (Ancient!)

* About dump:  “OS: Ubuntu 22.04.2 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231810502, revision: github-musescore-musescore-ea50c6d”

### Steps to reproduce

Steps to Reproduce:

1  Start MuseScore, load attached score “ReverbOn-TestStr”
2  Verify MuseSounds activated
3  Verify Reverb is on (Blue) for all busses
4  Click Play, play until end of music (~10 measures), then pause
5  Turn off Reverb on all busses (push the blue Reverb buttons)
6  Rewind and Playback
7  Around measure 8, the playback audio will start to crackle.

Rewinding and playing back does not recover from this condition.
Turning ON all the Reverb buttons AND playing back will recover from the condition.

For a non-fail case, please also see “ReverbOff-TestStr” test file.  Keeping Reverb off will not induce this problem (skip step-2 above)

### Screenshots/Screen recordings

[TestScores.zip](https://github.com/musescore/MuseScore/files/11919601/TestScores.zip)

### MuseScore Version

OS: Ubuntu 22.04.2 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231810502, revision: github-musescore-musescore-ea50c6d

### Regression

I don't know

### Operating system

Ubuntu Studio 22.04LTS

### Additional context

Other Information:

Participating testing on older/slower machine because bugs are often more pronounced.

CPU Loading seems to be nominal when playback fails

Tried increasing the Audio Buffer size (4096) – no change

May be related to these:
https://github.com/musescore/MuseScore/issues/18037
https://github.com/musescore/MuseScore/pull/18186

**Comment by RomanPudashkin** [comment]
@ShawTakeuchi thanks for reporting this problem! Please try this fix

https://github.com/musescore/MuseScore/pull/18368

**Comment by ShawTakeuchi** [comment]
@RomanPudashkin Apologies I just found the artifacts build.  Tested and confirmed fixed!

I also retested https://github.com/musescore/MuseScore/issues/18037 and found no problems.

Thank you!

**Comment by DmitryArefiev** [comment]
Fixed in #18368
