### ISSUE TITLE
Should not allow changing duration of trill cue notes

### ISSUE THREAD

**Issue by LupusCaeruleus** [musescore/MuseScore#18330]
### Issue type

UX/interaction, UI bug

### Bug description

Selecting a trill cue note and trying to change its duration / add aug dots to it / change it to a rest causes weird behavior. Such operations should not be allowed, or the logic should be changed.

https://github.com/musescore/MuseScore/assets/70313425/9a817ef1-4865-473a-b7fd-deee44d3562c

-----

Additionally, selecting a trill cue note and trying to create a tuplet triggers this error message box:
![image](https://github.com/musescore/MuseScore/assets/70313425/04dff569-fa35-4b0b-a1d5-63ed52c34fdd)
Maybe the error message can be changed to a more appropriate one (like "This operation makes no sense"), or just simply remove the message box (same as when trying to create a tuplet on a grace note)?

### Steps to reproduce

1. Create a trill with a cue note.
2. Select the cue note, then try to change its duration / add aug dots to it / change it to a rest by clicking the buttons in the toolbar.
3. See the results.

### MuseScore Version

4.1.0-231731239

### Regression

No.

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
Please sched a light onme: how to create a trill cue note?

**Comment by cbjeukendrup** [comment]
By creating a trill and setting the interval to something larger than a second

**Comment by Jojo-Schmitz** [comment]
Thanks, so this is not a Mu3 regression, but just because that feature doesn't exist there
