### ISSUE TITLE
"app seems to be turned off in the background" glitch

### ISSUE THREAD

**Issue by Musiclover3841** [musescore/MuseScore#18335]
### Issue type

Other type of issue

### Bug description

Each time i open music on musecore (app) it tells me "app seems to be turned off in the background" even though it turned on in the background 

### Steps to reproduce

Musecore
Open music
Glitch

### Screenshots/Screen recordings

![Screenshot_20230630_222823_MuseScore](https://github.com/musescore/MuseScore/assets/138269964/2176126a-43ef-4347-a435-8abc23a04cb5)

### MuseScore Version

Latest version

### Regression

No.

### Operating system

Phone

### Additional context

![Screenshot_20230630_222823_MuseScore](https://github.com/musescore/MuseScore/assets/138269964/9e574d97-0f78-4d24-b8ae-859d348b7a5a)

**Comment by MarcSabatella** [comment]
For issues with the mobile apps, you need to contact the support team from musescore.com (see contact info on that site).
