### ISSUE TITLE
Drum editor - note symbols and stems not alligned

### ISSUE THREAD

**Issue by Johan-v** [musescore/MuseScore#18337]
### Issue type

UI bug

### Bug description

When inputing notes in a percussion stave with drumset as instrument.
After N the drum editor does not look right.

### Steps to reproduce

1. Edit a perscussion part with drumset as instrument

### Screenshots/Screen recordings

![afbeelding](https://github.com/musescore/MuseScore/assets/30358005/d7c38ba8-7b65-4e9c-9fe6-a2b554208409)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-231810308, revision: github-musescore-musescore-fb36c11

### Regression

I don't know

### Operating system

Windows 10

**Comment by bkunda** [comment]
@cbjeukendrup do you have any clues as to when/how this came about?

**Comment by zacjansheski** [comment]
@igorkorsukov this first appeared three days ago.  Could this have been from one of your PRs?

https://github.com/musescore/MuseScore/pull/18325#issuecomment-1614915561

**Comment by asattely** [comment]
> @igorkorsukov this first appeared three days ago. Could this have been from one of your PRs?
> 
> [#18325 (comment)](https://github.com/musescore/MuseScore/pull/18325#issuecomment-1614915561)

I've reset my master branch to before this commit and the issue still remains. Still searching for the culprit!

**Comment by cbjeukendrup** [comment]
By the way, this is only a problem on the master branch, 4.1 is fine.

**Comment by asattely** [comment]
This commit seems to be at least partially at fault: cd60608df71433af51c557a5862d55f2981abf53

**Comment by bkunda** [comment]
> By the way, this is only a problem on the master branch, 4.1 is fine.

ok thank goodness.

Let's just make sure that the changes which caused this don't make it anywhere near 4.1.

Otherwise, good call @cbjeukendrup moving it to 4.2.

**Comment by igorkorsukov** [comment]
Thanks for the research, I'll take it to fix
