### ISSUE TITLE
Pressing 'Save' during playback rewinds playback to start of selection

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#18339]
### Issue type

General playback bug

### Bug description

When pressing save on a score, regardless if any changes are present or not, playback rewinds to the start of the selection. If there's no selection, no rewind takes place.

### Steps to reproduce

1. Create a new score
2. (Optional) Save the score
3. Select e.g. the first measure
4. Start playback
5. Save the score again, playback rewins

### MuseScore Version

4.1

### Regression

Choose option...

### Operating system

Windows 10

**Comment by bkunda** [comment]
Is this a regression on 4.0.2? Or on an earlier version?

**Comment by XiaoMigros** [comment]
It's definitely a regression over Mu3, but I don't currently have 4.0.2 installed so I can't say what it's like there

**Comment by MarcSabatella** [comment]
I can’t reproduce in 4.0.2 but can in 3.1, so it does seem to be a recent (if relatively minor) regression.

**Comment by XiaoMigros** [comment]
No longer encountering this issue in 4.1.1
