### ISSUE TITLE
Grand staff distance no longer working

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18342]
### Issue type

UI bug

### Bug description

The **Grand staff distance** setting (Style > Page > Disable vertical justification of staves) has stopped working altogether.

### Steps to reproduce

1. Open the attached piano score. 
[Corelli - allegro_(clementi).zip](https://github.com/musescore/MuseScore/files/11927121/Corelli.-.allegro_.clementi.zip)

2. Open Style > Page > Disable vertical justification of staves
3. Make various adjustments to the Grand staff distance (GSD).
4. Then press the reset button

RESULT: Nothing happens in the score while you are adjusting the GSD. Also note that the reset button does not highlight, and the score jumps momentarily when the button is pressed.

I also suspect that the other properties in "Disable vertical justification of staves" may not be working either.

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231820502, revision: github-musescore-musescore-7185eb8

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by MarcSabatella** [comment]
Seems to me the settings works fine, the score just doesn't update until you leave the spinbox.  I believe this was a deliberate change for performance reasons, but that's being reconsidered - see https://github.com/musescore/MuseScore/issues/17511.

**Comment by rgreen5** [comment]
> Seems to me the settings works fine, the score just doesn't update until you leave the spinbox. I believe this was a deliberate change for performance reasons, but that's being reconsidered - see #17511.

I was clicking on the spinner arrows and (understandably) expecting an immediate update. But it turns out you actually have to click onto another part of the style menu to get the update. As you mentioned, this is being dealt with elsewhere so I'll close the thread.
