### ISSUE TITLE
Muse reverb wet/dry mix sounds wrong

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18344]
### Issue type

Other type of issue

### Bug description

There seems to be a problem with the way that wet and dry signals are combined when the MuseSounds reverb is in use.

As you increase the reverb, the volume in the Master channel also increases. But surely the dry signal should decrease in volume as the wet signal increases, so you might expect the volume in the Master channel to stay roughly the same.

This is demonstrated in the recordings below.

### Steps to reproduce

1. Watch and listen to this piano piece played back in MS3:

https://github.com/musescore/MuseScore/assets/87246583/a0466324-87cd-4c0b-b196-fc2138acba03

Notice that there is an agreeable transition from Dry (no reverb) to Wet (100% reverb). In fact the master volume decreases slightly as the reverb increases.

2. Now watch and listen to the same piece played back in MS4:

https://github.com/musescore/MuseScore/assets/87246583/ea607a61-1fb9-4f1a-a03e-bbb02c1e8f17

This time the effect is not so agreeable. As the reverb level increases the master volume also increases quite markedly whereas the sound should soften with increasing reverb.

IMV, some adjustment is needed to improve the reverb sound in MS4.

Here is the original MS4 file: 
[Corelli - allegro_(clementi).zip](https://github.com/musescore/MuseScore/files/11927233/Corelli.-.allegro_.clementi.zip)

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231820502, revision: github-musescore-musescore-7185eb8

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64.

**Comment by DmitryArefiev** [comment]
I think it's expected because this is difference between **send** effect and **insert** effect


https://github.com/musescore/MuseScore/assets/90187801/0febfdce-68d1-4e31-a863-090a3beb08f3

**Comment by rgreen5** [comment]
OK, I understand now. I think it's OK to close.
