### ISSUE TITLE
Expression that does not snap to dynamic is not automatically placed

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#18351]
### Issue type

Engraving bug

### Bug description

When you untick "Snap to dynamic", Expression is not automatically placed.
Since Expressions have incorrect offset value when placed on the upper side, they overlap the staves,
<img width="495" alt="image" src="https://github.com/musescore/MuseScore/assets/102702868/711981b7-2add-4cda-b284-80f78e4faac3">

### Steps to reproduce

1. Create an Expression
2. Flip the Expression
3. Untick "Snap to dynamic"
4. The Expression overlaps the staves

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/102702868/dc7683b7-fff8-4e30-8a0d-db9f937197c0

### MuseScore Version

4.1 Nightly

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by bakajikara** [comment]
I misunderstood the issue. In fact, even in version 4.0, the offset value of Expression text was 2.5 when placed on the upper side.
But they didn't overlap the staves because of Auto-place. The problem is that in 4.1, if you uncheck the "Snap to dynamic" checkbox, the Auto-place does not work.
(But at the same time I would suggest changing the offset value to -1 when placed on the upper side, as in dynamics.)

**Comment by MarcSabatella** [comment]
The merged PR partially fixes the issue in that autoplace should now at least keep the text above the staff.  But it's still not right that the offset shows as positive for expression text that has been flipped above the staff.  There should be separate expressionPosAbove and expressionPosBelow settings accessible form the style dialog as there are for staff text etc.  Unless the intent is to inherit the dynamic pos above/below, but that isn't happening either.
