### ISSUE TITLE
Regression - Musescore 4 Fretboard Has Minimum of 4 Strings. Version 3 allowed

### ISSUE THREAD

**Issue by pjaromin** [musescore/MuseScore#18352]
### Issue type

Other type of issue

### Bug description

Unable to work on dulcimer music with chord charts in Musescore 4 as the new Fretboard editor has a minimum of 4 strings. Mountain dulcimers (and plenty of other instruments as well) typically feature 3 courses. Please eliminate the minimum. 

### Steps to reproduce

View the "Fretboard diagram" settings panel and attempt to reduce the number of strings below 4. The UI won't allow fewer than 4 strings. 
There is no such limit in Musescore 3.

### Screenshots/Screen recordings

<img width="238" alt="image" src="https://github.com/musescore/MuseScore/assets/3874504/c9e0ee54-e81e-47f7-aab3-062d4e5e36e8">

### MuseScore Version

4

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
Don't entirely eliminate the minimum, but set it to 1 (that's what Mu3 has too)
Similar for visible frets: in Mu4 the minimum is 3, in Mu3 it is 1
