### ISSUE TITLE
PNG/SVG export creates only one page of score (last page)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#18369]
### Steps to reproduce

1. Open score with more than one page
2. Export PNG or SVG

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/4ec7ab1b-69d0-44d7-9738-a4e9c82c43e9

### MuseScore Version

4.1 hightly build

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows10

**Comment by cbjeukendrup** [comment]
I'll take care of this one

**Comment by DmitryArefiev** [comment]
Fixed in #18377
