### ISSUE TITLE
Mixer: allow SOLO to be applied to multiple tracks

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18373]
### Your idea

Currently SOLO can only be applied to one track at a time in the mixer. However, it would be useful if solo could be applied simultaneously to any number of tracks.

### Problem to be solved

Currently if you want to isolate a few tracks from a mix you have to mute the tracks you _don't_ want to hear. However, with multiple solo selection you can SOLO the tracks you _do_ want to hear. This is especially useful for isolating a few instruments from a large line-up.

**Comment by MarcSabatella** [comment]
This is actually a bug - a regression from 4.0.2 (as well as MU3) - @bkunda .  All previous versions of MsueScore allowed multiple tracks to be soloed.  Seems to have happened sometimes in May or June.
