### ISSUE TITLE
Playing to MIDI plays all the staves despite the selected staves

### ISSUE THREAD

**Issue by lgvr123** [musescore/MuseScore#18389]
### Issue type

General playback bug

### Bug description

When I select a part of my score and play it, the [normal behaviour](https://musescore.org/en/handbook/4/playback-controls#To_play_back_selected_instrument_parts_only) is that it plays only the selected part.

![selectMidi](https://github.com/musescore/MuseScore/assets/50494/e4216c17-3e9a-4a2e-a45c-5f6ab72531ff)

This is not the case with MID I output: all the staves are played.

### Steps to reproduce

1. Open a multi-staves score
2. Configure MU4 to play to a MIDI output
3. Select a measure from one staff
4. Play it

Expected:
Only the selected measure/staff is played

Actual;
All the staff are played

### Screenshots/Screen recordings

See https://musescore.com/user/36377501/scores/11363188/s/7jiuxK

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

Windows 10

### Additional context

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

**Comment by lgvr123** [comment]
Same workflow and use case as in [Staves and voices not played to MIDI output correctly](https://github.com/musescore/MuseScore/issues/18382#issuecomment-1625566256).

**Comment by zacjansheski** [comment]
@lgvr123 

Could you take a look at https://github.com/musescore/MuseScore/pull/18827 and confirm if it resolves your issue?

**Comment by lgvr123** [comment]
I'm not sure to understand the exact status of this issue. Anyway I can't test its fix for now (holidays).

**Comment by cbjeukendrup** [comment]
There was a fix, but it turned out to introduce bigger problems, so the fix was reverted and a different solution will need to be found.

**Comment by zacjansheski** [comment]
@lgvr123 

Could you try https://github.com/musescore/MuseScore/pull/22924 and confirm if the issue is resolved for you?

**Comment by lgvr123** [comment]
How can I test it ?

**Comment by oktophonie** [comment]
The instructions are [here](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests).
