### ISSUE TITLE
Repeatable crash when deleting rest

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#18399]
### Issue type

Crash or freeze

### Bug description

Muse Score 4 crashes every time I attempt to delete a rest in the second voice.

See attached .mcsz score and screenshot (zipped).

### Steps to reproduce

1. In measure 41 of the clarinet part, select the dotted half note rest in second voice
2. Press "delete" key in an attempt to remove the rest from second voice.
3. Program crashes every single time.

### Screenshots/Screen recordings

[crash_repeatable.zip](https://github.com/musescore/MuseScore/files/11951890/crash_repeatable.zip)

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 10 Home Version 22H2

### Additional context

Let me know if I can capture the crash logs for you (not sure where they are located and/or if a debug setting needs to be turned on).

System info here:

OS Name	Microsoft Windows 10 Home
Version	10.0.19045 Build 19045
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DELL-XPS1-2710
System Manufacturer	Dell Inc.
System Model	XPS One 2710
System Type	x64-based PC
System SKU	To be filled by O.E.M.
Processor	Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz, 3101 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. A14, 5/25/2018
SMBIOS Version	2.7
Embedded Controller Version	1.04
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	03VTJ7
BaseBoard Version	A01
Platform Role	Desktop
Secure Boot State	On
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.2728"
User Name	DELL-XPS1-2710\scott
Time Zone	Central Daylight Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	9.54 GB
Total Virtual Memory	59.9 GB
Available Virtual Memory	52.2 GB
Page File Space	44.0 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not Modern Standby, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by cbjeukendrup** [comment]
I can reproduce this in 4.0.2, but not in the development builds of 4.1, which means that it has been fixed at some point. Could you please try the nightly builds (https://musescore.org/en/nightly-builds) to see if it's indeed fixed for you too?

**Comment by oktophonie** [comment]
This sounds exactly the same as https://github.com/musescore/MuseScore/issues/17761

**Comment by seisfeldt** [comment]
Thank you folks.  I tried the nightly build and it looks like it was fixed.  Please close if you agree.
(Next time I'll try the latest nightly build before reporting issues)

**Comment by cbjeukendrup** [comment]
Glad to hear that. Thanks for checking!
