### ISSUE TITLE
4.1 Regression: no instrument category selected when opening New Score dialog

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#18427]
**To Reproduce**
1. Launch MuseScore
2. Click "New score"
3. Select the "Select instruments" tab, if it is not yet selected

**Expected:** The topmost instrument family is selected initially, so that the Instruments column is filled with the instruments from that family
**Actual:** No instrument family is selected, and thus the Instruments column is initially empty.
<img width="1136" alt="Scherm­afbeelding 2023-07-06 om 02 13 00" src="https://github.com/musescore/MuseScore/assets/48658420/693489e8-949f-43ca-889d-39575d15cc0d">

**Comment by cbjeukendrup** [comment]
@bkunda @DmitryArefiev I believe this is a regression from a recent PR. I'm not sure how important this is; it could be a bit of an annoyance. What do you think, should we try to make a last-minute fix for 4.1?

**Comment by MarcSabatella** [comment]
From an accessibility standpoint it does take an already-awkward dialog and make it that much harder to navigate through, since exploring the dialog with Tab will no longer reveal the purpose of that middle column.

**Comment by DmitryArefiev** [comment]
> @bkunda @DmitryArefiev I believe this is a regression from a recent PR. I'm not sure how important this is; it could be a bit of an annoyance. What do you think, should we try to make a last-minute fix for 4.1?

@cbjeukendrup @bkunda I've tested #18429, all good there
