### ISSUE TITLE
Specific .capx file crashes MuseScore

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18446]
### Issue type

Crash or freeze

### Bug description

This is a confirmed issue from the MuseScore forum 
https://musescore.org/en/node/329800

The attached .capx file crashes MS4 and 3
[BWV_0988.capx.zip](https://github.com/musescore/MuseScore/files/11969752/BWV_0988.capx.zip)

### Steps to reproduce

1. Open MuseScore
2. Open the attached .capx file

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231870504, revision: github-musescore-musescore-690c096

### Regression

No.

### Operating system

OS: macOS 11.6

### Additional context

Basic .capx files open without issue

[test01.capx.zip](https://github.com/musescore/MuseScore/files/11969759/test01.capx.zip)

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.org/en/node/329800
