### ISSUE TITLE
Voice glissando not playing correctly

### ISSUE THREAD

**Issue by SpanishCat** [musescore/MuseScore#18452]
### Issue type

General playback bug

### Bug description

When adding a fall/slide out/slide in/any form of a glissando, the following happens:
A. The slide effect doesn't play
B. The note continues playing for much longer than it should. Stops only when the next note starts.

### Steps to reproduce

1) Add "voice" instrument to project.
2) Add a quarter note (though it's probably the same with any length).
3) Mark the note and add some slide effect from the "arpeggios & glissandi" category.
4) Play and pay attention to the length of the note in the playback.

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

Windows 10

### Additional context

Sound is MuseScore basic unmodified. No VSTs or any special sounds.

**Comment by bakajikara** [comment]
Probably the same issue? #15268

**Comment by zacjansheski** [comment]
This is MS Basic only.
Similar issues:
https://github.com/musescore/MuseScore/issues/16389
https://github.com/musescore/MuseScore/issues/16890
