### ISSUE TITLE
[GitHub] Use proper license filename

### ISSUE THREAD

**Issue by Panquesito7** [musescore/MuseScore#18469]
### Issue type

Other type of issue

### Bug description

The current license filename is not detected correctly by GitHub, even if the license is GPLv3.0.
For GitHub to detect it, the license filename must be renamed to `LICENSE`, `LICENSE.md`, or `LICENSE.txt`.

### Steps to reproduce

You can see this at the right top of the repository (screenshot below). You'll see that GitHub found unknown licenses.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/51391473/713c3a1f-07a1-479e-85df-d850c2f609a0)

### MuseScore Version

I don't think this applies here.

### Regression

I don't know

### Operating system

Microsoft Windows 10.

**Comment by oktophonie** [comment]
Previously reported as https://github.com/musescore/MuseScore/issues/14356 and fixed in https://github.com/musescore/MuseScore/pull/16308, but seemingly back

**Comment by Panquesito7** [comment]
Strange. 👀

**Comment by chunga2020** [comment]
I can handle this
