### ISSUE TITLE
Corruption/crash when changing duration of a deleted chord

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#18461]
### Issue type

Crash or freeze

### Bug description

When deleting all the notes in a chord, and then changing the duration (without click on/selecting anything else), there is now some unexpected behaviour:
- If the duration changed to fits within the measure, the rests don't fill as expected and corruption occurs
- If the duration doesn't fit in the measure, MuseScore crashes

Possibly this issue relates to a broader issue with deleting chords, as sometimes when working in second+ voices the cursor gets 'stuck' and I can't delete all the notes/rests in the voice (by hitting delete repeatedly) without reclicking.

### Steps to reproduce

1. Create a new score
2. Add a whole note to the first measure
3. Delete it, and press any number from 1-9 (8 or 9 will cause a crash)

### MuseScore Version

4.1.0-231710728

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by DmitryArefiev** [comment]
I can reproduce the crash in 4.1.0-231720304 but not in latest 4.1 build

Can you try this build please?
https://github.com/musescore/MuseScore/actions/runs/5482927548

**Comment by XiaoMigros** [comment]
Yes, seems to be working in the latest build but not the beta version I was running. Thanks!
