### ISSUE TITLE
"Create a linked staff" in MuseScore 4.1 causes the program to crash

### ISSUE THREAD

**Issue by orkuun** [musescore/MuseScore#18477]
### Issue type

Crash or freeze

### Bug description

Hello,
MuseScore 4.1 (RC) crashes when trying to link standard staff to tablature staff. (Sorry, my English is not very good. I couldn't find exactly how to write it. It will be better understood if you watch the video.)

### Steps to reproduce

1. New Score
2. String - Plucked/ Electiric Guitar (tablature)
3. Done
4. Instruments (tab)/Electric Guitar/ Staff Type/ Create a linked staff
5. Crash....

### Screenshots/Screen recordings

https://youtu.be/WM7VqoTIN_I

### MuseScore Version

MuseScore 4.1 RC

### Regression

I don't know

### Operating system

Windows 10, Linux Mint 21.1 Cinnamon

**Comment by oktophonie** [comment]
Nasty. Seems to occur when creating a linked staff for any sort of tab staff (where that staff is not itself a linked staff); adding a linked staff to a standard staff works fine,

**Comment by cbjeukendrup** [comment]
Working on it
