### ISSUE TITLE
Transposing instruments Concert C's, C flats, and C sharps play in wrong octave after adding a "flipping" key signature

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18473]
### Issue type

General playback bug

### Bug description

Adding the 6 or 7 sharps key sigs to an F Horn part causes G's to play up an octave
Similar behavior for the concerts C's with other transposing instruments when adding a key signature that flips from sharps to flats.

### Steps to reproduce

1. Create a score with F Horn
2. Add 6 or 7 sharps key sigs, (displayed in flats for F Horn) before the G's
3. G's are up an octave

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/84d1ec5b-0f71-4390-9cf6-255f83a0f639

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231881726, revision: github-musescore-musescore-5f333a2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

All

**Comment by zacjansheski** [comment]
@sammik please take a look at this.  It would be wonderful to get this fixed this weekend :)

**Comment by zacjansheski** [comment]
If it is helpful

[FHornTest.zip](https://github.com/musescore/MuseScore/files/11985134/FHornTest.zip)

**Comment by zacjansheski** [comment]
Same behavior with 
Eb instrument A's
Bb Instrument D's
etc.

**Comment by MarcSabatella** [comment]
Also in case it helps - this only applies to notes that already existed in the score before changing the key signature.  And this wasn't just caused by yesterday's fix for import, but appears to have broken since the key simplification was added.  Presumably a similar underlying issue involving some tpc confusion somewhere leading to an incorrect octave being calculated.

**Comment by sammik** [comment]
I am sorry, I am out off laptop.
May be to night, or at least monday morning.

**Comment by sammik** [comment]
@zacjansheski #18500 

It should be done, but please, test it carefully, and also, if it, for some reason, didnt affect playback of capo instruments.

Thank You
