### ISSUE TITLE
Aux channel strip labels should simply be "Aux 1" and "Aux 2", and shouldn't update to show any plugin names

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#18471]
### Issue type

UI bug

### Bug description

In light of recently reported confusion around the aux channel strip names, @Tantacrul and I have resolved that the simplest way to label the aux channel strips should be "Aux 1" and "Aux 2", rather than taking the name of any plugins applied to that strip.

_Current behaviour, showing Aux 1 labelled as "Reverb" and Aux 2 labelled as "Master"_:

<img width="658" alt="Screenshot 2023-07-07 at 6 59 04 pm" src="https://github.com/musescore/MuseScore/assets/86290556/3f3199dd-db07-4540-8184-8b890d4e0af8">

In addition, the channel strip name should not change when a plugin is replaced. It should simply remain "Aux 1" and "Aux 2".

Note this change should affect only the **channel strips**, not the label in the aux sends (adjacent to the knobs). 

  

### Steps to reproduce

n/a

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231881326, revision: github-musescore-musescore-0759bc9

### Regression

No.

### Operating system

all

### Additional context

N.B. Resolving this would also resolve https://github.com/musescore/MuseScore/issues/17514, which reports that MS needs to be restarted in order to update the channel strip label. 

@jessjwilliamson FYI

**Comment by bkunda** [comment]
Just to be clear: at this stage, we only want to change the name of the aux channel strip to show "Aux 1". 
It's important that the label next to the aux send knob still bears the name of the first plugin shown in the channel strip. This is currently how the user will be able to identify which channel strip their aux sends refers to (even without necessarily needing to understand anything about audio production and mixing terminology).

**Comment by HemantAntony** [comment]
Okay, I updated the PR accordingly, can you check again? @bkunda

**Comment by jessjwilliamson** [comment]
@HemantAntony I just tested your PR myself, and it absolutely makes more sense now :) @bkunda you can have a test yourself and see if you also approve this. I think this was a good shout to not overcomplicate the name of the actual aux channel itself. Well done!

**Comment by RobFog** [comment]
Should this issue be moved to the MuseScore 4.1.1 milestone seen as the fixes were ported in #18802?

**Comment by Tantacrul** [comment]
I'm adding it to 4.1.1 just now, since it should have been in 4.1.0
