### ISSUE TITLE
Playback of pitch change in slides is poor

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18482]
### Issue type

General playback bug

### Bug description

Playback of the pitch changes of **slides in** and **slides out** is poor in MS4.  There are related issues with bends as well (see #14443). The pitch problems are compounded by issues with timing (see #18176).

### Steps to reproduce

1. Open the attached MS3 file in MS4. 
[slides_ms3.zip](https://github.com/musescore/MuseScore/files/11990466/slides_ms3.zip)

2. Play back the file.

RESULT: The changes in pitch are not realistic, to say the least.

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by bkunda** [comment]
We intend to improve bends and slides in the next major release.

**Comment by bkunda** [comment]
Closing as this is now outdated.
