### ISSUE TITLE
Slides in imported MS3 files are invisible

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18480]
### Issue type

UI bug

### Bug description

A problem was fixed in  #18240 causing files imported from earlier versions of MS4 to be virtually invisible. However the same fix needs to be extended to imported MS3 files which have the same problem.

### Steps to reproduce

Open the attached MS3 file in both MS3 and the latest MS4 RC. 
[slides_ms3.zip](https://github.com/musescore/MuseScore/files/11990436/slides_ms3.zip)

RESULT: The slides are virtually invisible in the MS4 RC

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231881723, revision: github-musescore-musescore-5f333a2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by oktophonie** [comment]
Please don't file multiple issues in one. If the playback issue isn't covered by e.g. https://github.com/musescore/MuseScore/issues/18176 then file it separately.
