### ISSUE TITLE
Increase the limit value of time signature scale beyond 300% (MuseScore4 regression)

### ISSUE THREAD

**Issue by clemburt** [musescore/MuseScore#18493]
### Your idea

In MuseScore 4, would it be possible to increase the limit values of horizontal and vertical time signature scales beyond 300%?

It was possible in MuseScore3 and it is very useful for large conductor scores

### Problem to be solved

Increasing the limit values of horizontal and vertical time signature scales beyond 300%?

**Comment by cbjeukendrup** [comment]
This has already been fixed by #16732. That means it will be fixed in the next update, MuseScore 4.1, which is to be released within a few days.
