### ISSUE TITLE
Undoing after copy-pasting rest causes crash

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#18499]
### Issue type

Crash or freeze

### Bug description

Undoing after copy-pasting rest with beam type set to "join beams" causes crash.
I was only able to reproduce it when using grand staff.

### Steps to reproduce

1. Create a new score with grand staff
2. Change the rest's beam type property to "join beams"
3. Copy-paste the rest on the other staff
4. Undo
5. Crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/102702868/885e7515-37a4-4463-a8c1-ffbea8062a9e

### MuseScore Version

latest 4.1.0 nightly

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

log file: [MuseScore_230710_145437.log](https://github.com/musescore/MuseScore/files/11998249/MuseScore_230710_145437.log)

**Comment by oktophonie** [comment]
Weirdly, only seems to happen if doing this when copying/pasting between two staves of a grand staff in bar 1. Do it to/from bar 2 and it's fine. Also, if you try it in bar 2 (say) first, then do it in bar 1, it'll also be fine.
