### ISSUE TITLE
MuseScore crashes on startup

### ISSUE THREAD

**Issue by universalhandle** [musescore/MuseScore#18512]
### Issue type

Crash or freeze

### Bug description

After the icon is clicked, there is no user feedback whatsoever (except that the Ubuntu app launcher is dismissed).

This is a new computer/installation. MuseScore did work on here a few weeks ago. (While setting up the new computer, I grabbed several scores from my old machine and opened them on the new machine.) Since then, the only notable thing I can think of that I've done to the system is switch Ubuntu's language from English to Spanish.

When I encountered the segfault, I thought perhaps MuseScore was crashing because some language files were missing, so I switched back to English, logged out of my session and logged back in. The segfault behavior continues.

### Steps to reproduce

1. Press the Super key.
2. Type MuseScore.
3. Click on the MuseScore icon.

### MuseScore Version

3.6.2

### Regression

I don't know

### Operating system

Ubuntu 23.04

### Additional context

If I open a terminal and type `dmesg -w` before performing the repro steps, I get this output:

```
[ 1989.581797] audit: type=1400 audit(1689011017.381:253): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/19457/usr/lib/snapd/snap-confine" pid=21981 comm="snap-confine" capability=12  capname="net_admin"
[ 1990.065971] audit: type=1107 audit(1689011017.865:254): pid=1154 uid=100 auid=4294967295 ses=4294967295 subj=unconfined msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/" interface="org.freedesktop.DBus.Peer" member="Ping" mask="send" name="org.freedesktop.Avahi" pid=21981 label="snap.musescore.mscore" peer_pid=1152 peer_label="unconfined"
                exe="/usr/bin/dbus-daemon" sauid=100 hostname=? addr=? terminal=?'
[ 1990.231675] mscore[21981]: segfault at 0 ip 00007f21054d1a04 sp 00007fff54ed47a0 error 4 in libQt5XcbQpa.so.5.9.5[7f2105431000+fe000] likely on CPU 0 (core 0, socket 0)
[ 1990.231697] Code: f9 ff 48 8b 33 48 85 f6 75 ec 4c 89 e2 4c 89 ee 31 ff e8 ff 2d f9 ff 4c 89 e7 49 89 c6 e8 e4 20 f9 ff 4c 89 ef e8 ac f0 f8 ff <41> 8b 06 85 c0 7e 1e 45 31 e4 31 db 49 8b 46 08 83 c3 01 4a 8b 3c
```

**Comment by cbjeukendrup** [comment]
There will not be any updates to MuseScore 3.x, so the question is: does this also happen with the latest development builds of MuseScore 4.1? (https://musescore.org/en/nightly-builds)

If not, we'll have to close this issue.

**Comment by universalhandle** [comment]
Thanks, @cbjeukendrup. It would seem the snap has gotten out of date, as 3.6.2 is the latest available there. I uninstalled it and downloaded the AppImage instead, and wow does everything look different in 4.x but obviously no problem with segfaults. I wonder if some system updates must have come down after I installed 3.x that caused an incompatibility.

Anyway, I'll close this now -- nothing to see here.

**Comment by cbjeukendrup** [comment]
Thanks! Updating the version on the Snap store has been requested; it turns out that this is not trivial, since it is unclear who is supposed to be responsible for this. See #15994.

**Comment by universalhandle** [comment]
> it is unclear who is supposed to be responsible for this

This is a familiar feeling 😃

I'm not partial to snaps, but in the Ubuntu "store" there is a 2.x deb which is obviously unmaintained and the 3.6.2 snap (and I'm vaguely remembering there might even be a second snap?), so I figured the latter was "official." As is pointed out in the thread, MuseScore is listed as the author/maintainer.

Thanks for your help!
