### ISSUE TITLE
Bug report menu entry leads to out-of-date issue tracker

### ISSUE THREAD

**Issue by monsoma** [musescore/MuseScore#18517]
### Issue type

Other type of issue

### Bug description

When openin the menu entry (sorry, I have only the german names)
   Hilfe -> Programmfehler melden 
   (could be translated to Help -> Report bug)
my browser opens the login page of musescore.com (https://musescore.com/user/login?destination=%2Fcas%2Flogin).
From there I can navigate to the deprecated issue tracker (https://musescore.org/en/comment/1197846#comment-1197846).

Please update the link to this issue tracker at github.com.

### Steps to reproduce

see description

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
The "Report a bug" option will be removed in MuseScore 4.1. Instead, users can go to the MuseScore.org forum.

We don't want to send users to GitHub; GitHub is really the task list of the developers, so this must stay clear and only contain workable issues and tasks, and no duplicates, etc...
Therefore, users should go to the forum first, where they can discuss their issue and where they will be helped by our long-time community members. In the few cases that there is indeed a real reproducible bug in MuseScore, that has not been logged on GitHub before, then those volunteers give instructions to open a well-written GitHub issue.
