### ISSUE TITLE
Installing MuseHub / Musesounds in a classroom environment

### ISSUE THREAD

**Issue by pshutch** [musescore/MuseScore#18529]
Hi, im trying to setup MuseSounds in a classroom environment, we are a school in the UK. I have installed MuseScore V4 no problem but having problems with MuseHub.  Is there any better way of installing MuseSounds in a classroom environment other than MuseHub ?

**Comment by bkunda** [comment]
Hi @pshutch,
We are going to need a fair bit more information about what your requirements are here. 
What exactly do you need for a classroom environment setup?

**Comment by pshutch** [comment]
Hi

An installer for MuseHub that installs for all users, when I install musehub and then log on as a student I don’t see the software

Or preferably an installer or set of instructions that allows me to install all the musesounds to the correct location on each computer in one go

Thanks

Paul

**Comment by DominicMaas** [comment]
Hey, this specific situation is mentioned in more detail here:

- https://musehub.zendesk.com/hc/en-gb/community/posts/12185601342877
- https://musehub.zendesk.com/hc/en-gb/community/posts/10132082885789

**Comment by cbjeukendrup** [comment]
In that case, I suggest to continue this discussion on https://musehub.zendesk.com/, which is the intended place for Muse Hub issues. GitHub is actually only intended for MuseScore issues. Hope that's okay, @pshutch!
