### ISSUE TITLE
'normal' tone option missing from 'Guitar' palette by default

### ISSUE THREAD

**Issue by Calzep** [musescore/MuseScore#18522]
### Issue type

UI bug

### Bug description

By default, the 'Guitar' palette is missing the object to switch an electric guitar to a normal tone (the default clean sound). The object appears in the 'Text' palette but not the 'Guitar' palette.  The 'normal' tone object also does not appear under the 'More' list when opened from the 'Guitar' palette.

### Steps to reproduce

1. Select the "Default" workspace
2.  Click "Add Palette"
3.  Select the "Guitar" palette

Note the absence of the 'normal' tone option.

### Screenshots/Screen recordings

![Screenshot 2023-07-11 192359](https://github.com/musescore/MuseScore/assets/125546742/9689a602-401c-4d40-8ff4-c150ddc7bbd6)

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

Windows 11

**Comment by HemantAntony** [comment]
@bkunda I made a PR :) #18601

**Comment by zacjansheski** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/18601
