### ISSUE TITLE
Range selection box on percussion stave is not drawn properly sometimes and can be misleading

### ISSUE THREAD

**Issue by LupusCaeruleus** [musescore/MuseScore#18535]
### Issue type

UI bug

### Bug description

https://github.com/musescore/MuseScore/assets/70313425/0f71722a-b695-4160-a8f7-7e329e5d2914

1. When selecting a single empty bar of a one-line stave, the selection box seems shifted downwards. However, this is not the case if more than one bar is selected, or if there are notes in the same bar of another stave.
2. Notes in the same bar of another stave also affect the range selection box on the two-line stave, and cause multiple-bar selection box to expand vertically.
3. Despite what the blue border seems to indicate, the actual "interaction area" of the bar is much thinner than the selection box, making it very easy for the user to accidentally de-select the range.
 -- Also, I would suggest increasing the interaction area size of one-line staves, as it is currently so thin that it is barely possible to drag-drop elements (especially Layout ones) onto it without zooming-in.

### Steps to reproduce

See screen recording.

### MuseScore Version

4.1.0-231920501 (latest-4.1.0)

### Regression

No.

### Operating system

Windows 10

**Comment by wizofaus** [comment]
Can't reproduce #1 or #2? With #3 I can definitely see if you click some number of pixels just inside the selection rectangle it unexpectedly deselects, happy to have a look?

**Comment by bkunda** [comment]
We made some changes in 4.3 to the selection box. I think this might have fixed this issue because I can no longer reproduce it. 

https://github.com/musescore/MuseScore/assets/86290556/e38b616a-10d7-45bf-a1d7-e1ca6b00ed4d

@LupusCaeruleus if we've missed something here then I'd be happy to reopen this issue.
