### ISSUE TITLE
Missing letter in Page settings dialog

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#18534]
### Issue type

UI bug

### Steps to reproduce

![Capture](https://github.com/musescore/MuseScore/assets/90187801/1c90336e-61b1-4901-9e6e-5a897374296e)

### MuseScore Version

4.1 RC

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
Sorry, that's my screwup, fixed now (in the en_US translations).
Update translations in some 15 minutes to see.

**Comment by DmitryArefiev** [comment]
@Jojo-Schmitz All good now. Thanks for quick fix!
