### ISSUE TITLE
fff and ppp default placement touches barline

### ISSUE THREAD

**Issue by ghost** [musescore/MuseScore#18542]
### Issue type

Engraving bug

### Bug description

The default placement of the dynamics fff and ppp after a barline (not at the beginning of a score), slightly touch the barline and force user to manually move them.  

### Steps to reproduce

See screenshot below...

### Screenshots/Screen recordings

![360100778_2334803716725869_7281951798763947947_n](https://github.com/musescore/MuseScore/assets/139315507/851a6786-bf12-42bf-a2b0-103dab421ac1)

### MuseScore Version

4

### Regression

I don't know

### Operating system

Ventura 13.4.1

### Additional context

I reset all default settings upon opening a brand new project.

**Comment by oktophonie** [comment]
Fixed in 4.1 (https://github.com/musescore/MuseScore/pull/17001)
