### ISSUE TITLE
MuseScore crashes when the last bar is removed, then selected

### ISSUE THREAD

**Issue by Neldor258** [musescore/MuseScore#18549]
### Issue type

Crash or freeze

### Bug description

Hey there!
I'm having a bit of trouble with my version 4.0.2 of MuseScore, running on Windows 10 x64.

In the following situation(s), MuseScore crashes to desktop:
[Having opened the attached file; the last bar being assigned a change of beat count or however you call it in English...]

- if I remove the last bar via CTRL+DEL >>> then trying to select the bar = crash
- if I remove the change of beat count via select and DEL, then remove the last bar via CTRL+DEL >>> then trying to select the bar = crash

Note: Selecting other bars in-between the removal of the last bar and the selection of it works fine, so it really seems not being able to handle the actual reselection of the last bar, which by that time is the previously second to last bar.
I also tried pasting a multiple bar melody in a way that it reaches into the corrupted bar and it shows and plays fine. Still, when trying to select that bar, it crashes...

In case it would matter in any way:
- I'm using the German version, i.e. localization
- I'm using the new MuseSounds libraries as standard loaded in the project

If any further information is required, I'll be happy to provide it!
Thanks in advance for looking into it!

PS: The issue was first posted on musescore.org and replied to by Jojo-Schmitz with "Confirmed and still the case with the just released 4.1.0, please report on GitHub" - 2023/07/12

[bugtest 07-23.zip](https://github.com/musescore/MuseScore/files/12028132/bugtest.07-23.zip)

### Steps to reproduce

- Remove the last bar and select the new last bar or 
- Clear the last bar, select it, remove it, then try to select it again
- Feel free to experiment further with copying, pasting and editing the melody in the range of the corrupted bar (after removal)

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 x64

### Additional context

AMD FX(tm)-8150 Eight-Core Processor              3.60 GHz
RAM	16,0 GB
64-Bit-Betriebssystem, x64-basierter Prozessor

NVIDIA GeForce RTX 2060
DirectX-Version:	12 (FL 12.1)

Windows 10 Home

**Comment by zacjansheski** [comment]
I am able to reproduce in the current master

**Comment by cbjeukendrup** [comment]
> Related to #17829 and so fixed by #17895?

This is indeed the case, so it should be better in the next nightly build. 

But @mike-spa, that's interesting: apparently it is _still_ possible nowadays to get a score into a state where the last segment is disabled. But in this case it seems to fix itself after saving and reloading the file.

**Comment by zacjansheski** [comment]
I'm finding this very easy to reproduce.

Change the time signature of the last measure.  
Delete that measure. 
Select the new last measure.

**Comment by zacjansheski** [comment]
Confirmed in earlier versions of 4 as well (not a recent regression)

**Comment by zacjansheski** [comment]
Fixed with https://github.com/musescore/MuseScore/pull/17895

Now ported
