### ISSUE TITLE
The number of strings in the fretboard is not more than 4

### ISSUE THREAD

**Issue by Evgenioni** [musescore/MuseScore#18543]
### Issue type

Other type of issue

### Bug description

You can put 4, 5, 6 strings in the diagram. It is not suitable for 3 string instruments such as balalaika and cuban tres.

### Steps to reproduce

1. Insert fretboard diagram (from palette)
2. Select the diagram and go to its Properties -> Settings
3. Reduce the number of strings

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/2331446/74a85738-2d77-4305-8171-f647cf24b933)

### MuseScore Version

4.1RC

### Regression

I don't know

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
Ahm fount it, commit e2d1fefba7, PR #18354, issue #18352
