### ISSUE TITLE
rests vertical disalignment under same beam

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#18555]
### Issue type

Engraving bug

### Bug description

When there are multiple rests under a beam and one does not collide with the beam, it can be autoplaced in the regular spot and the next rest will be displaced up or down.

### Steps to reproduce

1. put two eighth rests in a row
2. add an eighth note above or below the staff after them
3. beam the first two rests to the note

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/120861729/fa052d33-761f-4319-881b-653099f86476)

### MuseScore Version

4.1

### Regression

No.

### Operating system

windows

**Comment by Vykoiazon** [comment]
![image](https://github.com/musescore/MuseScore/assets/120861729/fd31d44a-142b-4008-ae17-81fd9f69dbdc)

above the staff notes could make both rests move together because they would both collide with the beam

**Comment by Vykoiazon** [comment]
![image](https://github.com/musescore/MuseScore/assets/120861729/bee447bc-2351-4dd6-865c-681f7571952b)

Rests can get reset to default position after editing another nearby bar, but it fixes itself after moving anything on the same bar the rests got moved. Saving and reopening does not fix the rests if they were saved in that location.

**Comment by Jojo-Schmitz** [comment]
Doesn't happen in Mu3, so is a regression
