### ISSUE TITLE
Upgrading MuseScore keeps the old version entry

### ISSUE THREAD

**Issue by SilverGreen93** [musescore/MuseScore#18562]
### Issue type

Other type of issue

### Bug description

Just automatically updated today to MuseScore 4.1.0 from MuseScore 4.0.2 by using MuseHub app.

In Windows Settings -> Apps, there can be seen both versions installed, but actually on disk there is only 4.1.0 installed. (4.0.2 was most likely overwritten without removing the 4.0.2 entry from the registry)

See screenshot below.

~~I haven't tested upgrading without MuseHub (using the standalone installer), but I think the outcome must be the same.~~
I can confirm that this is NOT MuseHub issue.
I installed MU 4.1 on another pc using the standalone installer (without MuseHub) and the same issue can be seen.

### Steps to reproduce

1. Have MS 4.0 installed
2. Use MuseHub to update to 4.1 or just use the standalone installer.
3. Notice the installed apps reported by windows.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/24845602/a052dd37-a69c-4c65-891e-2cc6592da427)

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
Maybe related: I remember that on Windows, Muse Hub often gives a warning like "Failed to uninstall application" when trying to update MuseScore. I suppose that this means that it fails to uninstall the old version before installing the new one.

**Comment by SilverGreen93** [comment]
I can confirm that this is NOT MuseHub issue.
I installed MU 4.1 on another pc using the standalone installer (without MuseHub) and the same issue can be seen.

**Comment by bkunda** [comment]
@DmitryArefiev pls investigate

**Comment by DmitryArefiev** [comment]
This is the same as #15167

**Comment by DmitryArefiev** [comment]
> I can confirm that this is NOT MuseHub issue.
> I installed MU 4.1 on another pc using the standalone installer (without MuseHub) and the same issue can be seen.

Only this is the difference, but I still **can't reproduce**  it (as I mentioned in #15167)


@SilverGreen93 Did you try on both installers? (install 4.02 from msi and update with 4.1.0 from msi)

**Comment by SilverGreen93** [comment]
> > I can confirm that this is NOT MuseHub issue.
> > I installed MU 4.1 on another pc using the standalone installer (without MuseHub) and the same issue can be seen.
> 
> Only this is the difference, but I still **can't reproduce** it (as I mentioned in #15167)
> 
> @SilverGreen93 Did you try on both installers? (install 4.02 from msi and update with 4.1.0 from msi)

What I tested back then was 4.0.2 installed with MuseHub and after that installed 4.1.0 over from msi installer. Will test again 4.0.2 to 4.1.0 msi and come back.

**Comment by SilverGreen93** [comment]
It looks like clean installation of msi package for 4.0.2, followed by 4.1.0 works fine.
But if I install 4.0.2 msi and then use MuseHub to upgrade to 4.1.0 I get
![image](https://github.com/musescore/MuseScore/assets/24845602/67586d93-9ecd-4fc5-ac38-d1a09f105088)
And then both show up again as installed.

**Comment by DmitryArefiev** [comment]
@SilverGreen93 Thanks for testing! I'll close the bug as duplicate and leave a reference to the current issue in #18562.

I have 4.0.2 msi file and can upload it, if you want to have it. Please let me know
