### ISSUE TITLE
Crash when deleting Harp pedal diagram added to multimeasure rest

### ISSUE THREAD

**Issue by RrOoSsSsOo** [musescore/MuseScore#18563]
### Issue type

Crash or freeze

### Bug description

Adding an Harp pedal diagram to a **multimeasure rest**

![image](https://github.com/musescore/MuseScore/assets/1734343/79cc5d0b-1001-4db7-a1a6-c5ea783d5c99)

Select and press _Canc_

![image](https://github.com/musescore/MuseScore/assets/1734343/d6663c27-5e14-4f93-b61c-c9ef3ef8c8be)

In my case there isn't any crash if it is added to a single measure.

![image](https://github.com/musescore/MuseScore/assets/1734343/dab6497d-b4fb-4bcf-94f4-9077cbc0c9fb)

A temporary fix to delete is delete everything in the measure(s), not only the diagram

![image](https://github.com/musescore/MuseScore/assets/1734343/6476f94c-c5ab-4862-96bd-b7c3c3256d8c)

### Steps to reproduce

1. Select a multimeasure rest
2. From Harp palett add Harp pedal diagram
3. (Move it from original position)
4. Try to delete the Harp pedal diagram FROM Part, not from Score

or

1. Open attached file
2. Delete FROM Part, not from Score, pedal diagram as first operation

### MuseScore Version

4.1.0

### Regression

No.

### Operating system

Windows 11

### Additional context

[Harp pedal diagram delete crash.mscz..zip](https://github.com/musescore/MuseScore/files/12038454/Harp.pedal.diagram.delete.crash.mscz.zip)

**Comment by bkunda** [comment]
I'm unable to reproduce this crash on macOS:


https://github.com/musescore/MuseScore/assets/86290556/01223e88-0bbb-4d9b-a9e6-808f7da70d5e

What I did notice though, was something odd going on with the multimeasure rests in the score attached to this issue: the multimeasure rests seem to be divided into 3 bars and 28 bars (i.e. two different multimeasure rest objects):

https://github.com/musescore/MuseScore/assets/86290556/c3f572da-5695-4a1c-9128-10cdb4416d13

If I start a new score and toggle multimeasure rests, there is only one multimeasure rest object:

<img width="461" alt="Screenshot 2023-07-14 at 2 58 29 pm" src="https://github.com/musescore/MuseScore/assets/86290556/ea9291b3-b016-43b2-a36e-1a4445872e8f">

In the attached score, deleting all (but one) bar and re-adding new bars produces only one multimeasure rest object, and when I then add and delete the harp pedal diagram, there is no longer a crash. 

So it seems to me that this crash has to do with the multimeasure rests in the particular score attached. 

@mike-spa perhaps you might be able to shed some light on what could be going on here. I'm hoping it's a quirk with this score and not a general issue concerning the harp pedal diagram 🙂.

**Comment by mike-spa** [comment]
Here's the simpler way to reproduce it:

1. Insert a pedal diagram
2. Move it away from the default position, e.g. between staves
3. Activate MM rests
4. Delete diagram.

https://github.com/musescore/MuseScore/assets/93707756/17b7c3bc-3847-41d1-b077-e77fd1aa523f
