### ISSUE TITLE
Hyphens not working correct in multiple note phrases

### ISSUE THREAD

**Issue by BillEllison** [musescore/MuseScore#18578]
### Issue type

Other type of issue

### Bug description

![Screenshot 2023-07-13 at 4 33 23 AM](https://github.com/musescore/MuseScore/assets/139494570/44087d23-d9b3-4e4f-91e8-67879de9f262)
 Note:  hyphens do not carry over when using multiple notes in series.

### Steps to reproduce

Click hyphen to start syllabication.
Press space, space, space (or alternatively the arrow keys) to move text box to next note.
Hyphen should follow text box over to next note.

### Screenshots/Screen recordings

![Screenshot 2023-07-13 at 4 33 23 AM](https://github.com/musescore/MuseScore/assets/139494570/2f3e9bfa-9617-46d6-bae2-59bbd85b3ef8)

### MuseScore Version

4.1.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 13

**Comment by oktophonie** [comment]
Did it ever work like this? You are supposed to press `-` repeatedly for each note you wish the hyphens to extend over.

**Comment by BillEllison** [comment]
Is that a change from the last version?  I don’t remember having to do that before, and I must have been mistaken.  When I press (-) hyphen after each note, it works just fine.  Sorry for the time wasted.
