### ISSUE TITLE
Harp pedal pitch feedback doesn’t care about enharmonics

### ISSUE THREAD

**Issue by mmeyn** [musescore/MuseScore#18577]
### Issue type

UI bug

### Bug description

Pitches are colored red when they don’t match the pedal diagrams. That’s nice but I think they should respect enharmonic notation: An F♯ is something different than a G♭.

### Steps to reproduce

For example:
1. Write some music containing F♯ and G♭.
2. Add a harp pedal diagram with F natural and G♭.
3. See that the F♯ are colored black.

### Screenshots/Screen recordings

![Harp_full_score](https://github.com/musescore/MuseScore/assets/7814361/59dae172-38e3-4095-a41b-f115554ae231)

### MuseScore Version

4.1.0

### Regression

Choose option...

### Operating system

Linux

### Additional context

[Harp_bugs.zip](https://github.com/musescore/MuseScore/files/12042704/Harp_bugs.zip)
This zip contains the mscz score for the screenshot above.

**Comment by mmeyn** [comment]
Is there already someone working on this? If not I’d like to try it. I think I already found out what is going on here (harp pedal diagrams translate pedal states to `int` for MIDI pitch number but should instead translate to the `Tpc` spelling of pitches).

**Comment by oktophonie** [comment]
Go for it!

**Comment by DmitryArefiev** [comment]
Fixed in #18902
