### ISSUE TITLE
Audio glitches and playback becomes unstable when USB headphones are plugged in.

### ISSUE THREAD

**Issue by iceypotato** [musescore/MuseScore#18579]
### Issue type

General playback bug

### Bug description

When plugging in my USB headphones and when I play the score in Musescore, the audio becomes glitched and the playback is much faster and more glitchy. In the past, plugging in my headphones would instantly crash Musescore, but it seems to have been fixed.

### Steps to reproduce

1. Plug in USB headphones
2. Launch Musescore and load a score
3. Play the score
4. Listen to the audio

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/40870742/b74de1bb-bb6e-485e-806e-7ac3c60bc8ae

Log file: [MuseScore_230713_105608.log](https://github.com/musescore/MuseScore/files/12042900/MuseScore_230713_105608.log)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

No.

### Operating system

Windows 11

### Additional context

Plugging in my headphones used to crash musescore, so at least it is functioning.

**Comment by bkunda** [comment]
@iceypotato what model headphones are you using? 

Can you please attach the diagnostic files so we can look into it further?

**Comment by MarcSabatella** [comment]
That isn't clear to me.  I just know that every day we get a handful of reports from users about glitchy audio, and when we tell people to try setting their audio device to 44.1 kHz, they almost always report that fixed it.

**Comment by IndigoNao** [comment]
For the sake of reference, I have notated the difference I encountered when I experienced this issue. When I load MuseScore with my bluetooth headphones already connected, then remove them afterwards, everything gets pitched down by a quarter tone. Similarly, if MuseScore loads without my headphones, and then I connect them, everything gets pitched up by a quarter tone.

**Comment by DmitryArefiev** [comment]
Should be fixed by #23954. But that PR **doesn't cover** audio device **hotplug cases**

For MuseSounds see https://github.com/musescore/MuseScore/pull/23954#issuecomment-2283553013

**Comment by DmitryArefiev** [comment]
Please reopen if still occurs
