### ISSUE TITLE
Notes on single-line staves appearing at incorrect vertical position

### ISSUE THREAD

**Issue by dhcpercussion** [musescore/MuseScore#18589]
### Issue type

Choose option...

### Bug description

Today I downloaded the latest version of MuseScore 4.1 (before that, I had the earlier version of MuseScore 4). Unfortunately, I asked it to replace that earlier 4.0 app.

I am writing a significant snare drum book: the latest version - MuseScore 4.1 - has messed up some of my work.

Please help by providing a link to the earlier version of MuseScore 4 so that my file can open in the ways I created it.

### Steps to reproduce

Some notes appear about 3-4 octaves below the single line staff (those weird low notes are always connected to a slur). I tried deleting those note with their slur, then I re-added the note with its slur, but the note then goes back to its low position. Also the text in my numerous text frames (which indicate the etude number) is no longer centered in the frame, and the text won't stay centered after I re-center it. 

### Screenshots/Screen recordings

<img width="498" alt="Screen Shot 2023-07-14 at 1 04 11 AM" src="https://github.com/musescore/MuseScore/assets/139531192/1d2b34ae-3be4-47eb-9c38-45d058750b2c">

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231921401, revision: github-musescore-musescore-2e3a93a

### Regression

Choose option...

### Operating system

OS: macOS 12.6, Arch.: x86_64

**Comment by dhcpercussion** [comment]
[cbjeukendrup](https://github.com/cbjeukendrup): 

Github mentions it does not support the mscz file type when I drag the MuseScore file into this window. I could drag in a pdf version but not sure that will help, thanks.

**Comment by dhcpercussion** [comment]
Thanks so much for the link to the older 4.02 version of MuseScore - most of my work went back to normal.

**Comment by oktophonie** [comment]
To attach an .mscz file, just put it into a .zip file, or even just change the file extension to .zip first.

**Comment by dhcpercussion** [comment]
[SD_BOOK_DAVIDCARLISLE_BugExamples.mscz.zip](https://github.com/musescore/MuseScore/files/12051021/SD_BOOK_DAVIDCARLISLE_BugExamples.mscz.zip)

Two examples are uploaded.

**Comment by MarcSabatella** [comment]
I've posted the text alignment issue separately - https://github.com/musescore/MuseScore/issues/18600

**Comment by dhcpercussion** [comment]
[MarcSabatella](https://github.com/MarcSabatella): I see your video, thanks.

**Comment by cbjeukendrup** [comment]
This can be reproduced even from scratch: 
1. Create score with snare drum
2. Add some notes in the last measure of the first system
3. Add notes in the first measure of the second system
4. Add a slur from the last note of the first system to the first note of the next system. Make sure that this slur has direction "Auto"; if it's either explicitly "Above" or explicitly "Below", the problem does not occur.

**Comment by dhcpercussion** [comment]
[cbjeukendrup](https://github.com/cbjeukendrup): I think MuseScore's one-line snare drum staff defaults at stems down. For this project, I prefer stems up, so in MuseScore 4.02, I manually created stems up by selecting notes as I composed, with typing X. 

When I opened my file a few days ago for the first time in MuseScore 4.1, some stems were facing down and others up. So I forced them all up in 4.1 by using Command A, then in Properties > Notation > Notes > Stem >  Stems Up. Doing this may have caused the some of those "auto" slurs to go way vertically low.

As I'm writing the book, I've not been doing sweeping Command A gestures...because I'm writing a book as a draft. But now with Command A: I've forced all Stems Up (as described above) and forced all Slurs Down (Properties > Notation > Notes > Slurs > Down). All low note problems have seemed to go away (as you wrote). Thank you.

**Comment by MarcSabatella** [comment]
FWIW, instead of forcing stem directions up manually with "X", the better method would be to edit the drumset definition to set the stems up automatically (and as discussed elsewhere, this should probably be default anyhow).  But unfortunately, changing the drumset does not affect already-entered notes (although it probably should).  Still, this could save you some work going forward.

**Comment by dhcpercussion** [comment]
Thank you Marc, great tip, and it works well (I've edited the Drumset for more complex percussion works and forgot about that stem direction option for this SD book). I bought your MuseScore 3 course about two years ago because I was asked to teach a music tech class at the university here. I'd taught that class previously using Finale for the music notation component, but I wanted to use MuseScore. Your course was very helpful!
