### ISSUE TITLE
Attempting to add tuplet to linked staff causes crash

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18595]
### Bug description

Attemting to add a tuplet to a linked staff causes a crash. See https://musescore.org/en/node/352228.

### Steps to reproduce 
Edited By @DmitryArefiev 

1. Create score using **Guitar+Tablature** template
2. Click first measure
3. Press N
4. Press Ctr/Cmd+3

RESULT: The application will hang (even perhaps for some time) then crash. Same thing happens in normal mode.

https://github.com/musescore/MuseScore/assets/90187801/32bf9c55-04d8-4e22-968a-92efcf738cb9

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a

### Regression

Yes, this used to work in **MuseScore 4.0.2**

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64.

**Comment by RomanPudashkin** [comment]
@mike-spa it looks like this PR fixed the crash for master/4.2. You need to port it to 4.1.1 later (when we create the branch)
https://github.com/musescore/MuseScore/pull/18385

**Comment by DmitryArefiev** [comment]
Fixed in #18661
