### ISSUE TITLE
Crash setting horizontal frame width value greater than certain value

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#18592]
### Issue type

Crash or freeze

### Bug description

MuseScore 4.1 crashes if setting horizontal frame with greater than 102
Same crash happens for left gap and right gap fields for horizontal frame

### Steps to reproduce

1. Create empty score
2. Append horizontal frame at the end
3. set width or gap value (properties panel) greater than 102

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/a4cd7366-359a-46d1-9435-711772288acc

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

Windows 10 Version 2009

### Additional context

Did not find opened issue for this case

**Comment by mercuree** [comment]
Possible regression, cannot reproduce on Musescore 4.0.2

**Comment by zacjansheski** [comment]
For me it happens when I go over 106


[HorizontalFrameCrash.zip](https://github.com/musescore/MuseScore/files/12051758/HorizontalFrameCrash.zip)

https://github.com/musescore/MuseScore/assets/69917893/9fcc849c-249f-4082-a7e5-aa0889341b5a

**Comment by zacjansheski** [comment]
Confirmed regression, does not occur in 4.0.2

**Comment by cbjeukendrup** [comment]
Here's a guess about the discrepancy in the value at which the crash occurs: maybe it's because Zac's default paper size is Letter instead of A4, and thus the systems are wider?

**Comment by mercuree** [comment]
> Here's a guess about the discrepancy in the value at which the crash occurs: maybe it's because Zac's default paper size is Letter instead of A4, and thus the systems are wider?

Yes, A4 is default page size for my system. And after changing page size to Letter, Musescore crashes with 106  value
