### ISSUE TITLE
Ctrl+R reset removes pedal text markings

### ISSUE THREAD

**Issue by mdeluca70** [musescore/MuseScore#18603]
### Issue type

Engraving bug

### Bug description

Pressing Ctrl-R to reset shapes and positions removes pedal markings. A line remains on the score where the pedal marking used to be, but can not be selected.  The pedal is still active in the score (playback holds the notes as indicated), but the marking is now gone and can not be edited.

### Steps to reproduce

1. Open a new score and add piano as the instrument
2. Add notes to the piano score, and then add a pedal notation from the Keyboard palette.  Extend the pedal to hold notes for an entire measure
3. Press Ctrl+A to select the entire score, then Ctrl+R to reset shapes and positions.  

![Screenshot 2023-07-14 092707](https://github.com/musescore/MuseScore/assets/100440500/c6531a56-0796-4213-9987-77de87e16981)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

Win 11

**Comment by oktophonie** [comment]
See also the somewhat-relevant https://github.com/musescore/MuseScore/issues/16922

**Comment by Jojo-Schmitz** [comment]
This is a regression vs. Mu3
