### ISSUE TITLE
Alignment lost for text in text frame

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#18600]
### Issue type

Engraving bug

### Bug description

If you set custom alignment on text in a text frame (center or right instead of left), this is lost on the next edit, or on save/reload.

### Steps to reproduce

1. Create a score
2. Add text frame
3. Add text to that frame
4. In properties, see the text to center
5. Add a note to the score or any other edit

Result: the text reverts to left aligned

### Screenshots/Screen recordings

![text-align](https://github.com/musescore/MuseScore/assets/1799936/ecd03003-039c-49e9-a7d3-2f8939afff64)

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Debian 11

### Additional context

It's more about management of the element properties than engraving per se, but I don't know that we have a better category currently.

**Comment by MarcSabatella** [comment]
@bkunda Could this be triaged for possible consideration in 4.1.1?  It's a regression against 4.0.2, and when considering the case of 4.0 (or older) scores imported into 4.1, it causes loss of data, which we have traditionally considered as high a priority as crashes and corruption.  It's probably a trivial fix.

For scores created within 4.1, I'm a bit less concerned because the workaround of using a vertical frame is viable.

**Comment by cbjeukendrup** [comment]
I don't know if this will make it into 4.1.1 but at least here is a fix: #18736 
And indeed, in the end, it's trivially correct (and safe enough, I'd say), but I did have to watch twice before I saw where it went wrong :)

**Comment by MarcSabatella** [comment]
Thanks!
