### ISSUE TITLE
Key signature resetting/changing when inserting a measure before measure 1

### ISSUE THREAD

**Issue by orangefanta1** [musescore/MuseScore#18611]
### Issue type

Engraving bug

### Bug description

When inserting a new measure at the beginning of the score (when in the open/atonal key) it changes the key signature back to Concert C.

### Steps to reproduce

1. open musescore 4
2. new score
3. go to "choose instruments"
4. add horn in F and piano
5. select any key signature
6. click done
7. on the score screen change the key signature of the first measure to "open/atonal"
8. select the first measure of the score and press [Ins] to insert a new measure before measure 1
9. key has now switched to C Major

### Screenshots/Screen recordings

https://youtube.com/shorts/NWpuyXlrNAE

### MuseScore Version

4.1.0

### Regression

No.

### Operating system

Windows 10 Home

### Additional context

I am using the most recent version of Musescore 4 (4.1.0) but this was also happening before downloading the update today.
This will happen repeatedly when adding new measures before measure 1 when the key is set to open/atonal (like, no matter how many times I set it to open/atonal, if I insert a new measure again it will change it back to C Major)

**Comment by sammik** [comment]
@oktophonie please check #18653
