### ISSUE TITLE
Y axis value greyed out in "flag offset" settings after 4.1

### ISSUE THREAD

**Issue by bhperes6** [musescore/MuseScore#18625]
### Issue type

UI bug

### Bug description

The Y axis value in "flag offset" can't be changed anymore after the last update (4.1)

### Steps to reproduce

1. type an 8th note
2. select the flag 
3. go to "properties" > "show more"
4. in "flag offset" the Y axis value is greyed out and can't be changed.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/139638256/b83f1c08-7137-46e5-ba91-92a59fda3ab7

### MuseScore Version

4.1.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by oktophonie** [comment]
I have a hazy recollection that this is by design. Why do you need it? To move the flag vertically you can extend or shorten the stem.

**Comment by bhperes6** [comment]
> I have a hazy recollection that this is by design. Why do you need it? To move the flag vertically you can extend or shorten the stem.

As I said in my original post on "support and bug reports", I'm working on a project in which it's important for me that every little aspect of the score is fully customizable. In this project I almost don't use the "auto-place" option. I determine the placement of every single element in the score. I understand that the latest versions of Musescore may appeal to a more casual public, for whom it's important that things are done automatically for the sake of time efficiency, but seasoned users like me (I've been using MS for 10 years now) should not be disregarded. If this change is by design, so why not get rid of the setting altogether? Why just grey it out? (please don't do that lol).

![colcheia](https://github.com/musescore/MuseScore/assets/139638256/2a4d8fdf-ee58-4d89-b580-f0538ebaf617)

here is a example of a eight note if I don't change the flag offset settings in this project. As you can see, it's kinda ugly. I'm going back to 4.0.1 just to be able to change it.
