### ISSUE TITLE
Create Time Signature dialog elements are too small to use

### ISSUE THREAD

**Issue by joshjaysalazar** [musescore/MuseScore#18627]
### Issue type

UI bug

### Bug description

When trying to create a new time signature, the elements to adjust beam grouping are entirely too small to see.

### Steps to reproduce

Go to the Create Time Signature dialog (see screenshot, could be system-dependent? I have tried a number of preference adjustments and DPI adjustments to no avail)

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/36433522/1506321f-67db-4973-9778-9e878e0f544f)

### MuseScore Version

4.1.0

### Regression

No.

### Operating system

Windows 10

### Additional context

Running on a 1080p monitor, at the standard 1920x1080 resolution. Windows UI scale factor is at 100%.

**Comment by MarcSabatella** [comment]
Are you finding other UI elements also sized badly?  Like, palette items, also the score itself at 100% zoom (should be life sized - same as the physical paper it is to be printed on)?

Unfortunately different systems handle hihg DPI displays and scaling differently, so it's difficult to always get this right automatically.  I recommend asking for help on the Support forum on musescore.org and including your system info there - also be sure to mention the size of the display and its DPI.  Also say how the palettes display, and the score.  Then we can better suggest appropriate workarounds.

**Comment by joshjaysalazar** [comment]
I don't mind the palette sizing, although it is admittedly small, but as you can see, the score is *teensy* at 100%

![image](https://github.com/musescore/MuseScore/assets/36433522/5fe214fb-23f9-4d9c-889f-df3da4bc7c1f)

Otherwise the UI seems fairly readable. No overly small text, no overly small buttons (like on the toolbar along the top). I will note that I did try using the compatibility settings to adjust the scaling, and while it did make the palette items much bigger, the size of the problem section in the create time signature dialog actually stayed the same! So I reset to factory default settings, just in case something strange was happening there, and now changing compatibility settings doesn't do anything, no matter what setting I choose.

I also tried using the command line -D flag, which doesn't seem to work anymore for MuseScore 4? If I'm missing something obvious there, by all means I will try it. Can't seem to find any help there across the web.

Regarding my monitor, it's a pretty standard 24" 1080p monitor. No downscaling or anything needed for that. 1920x1080 resolution, 100% scale in the Windows settings.

**Comment by MarcSabatella** [comment]
There are workarounds for situations like this, but as I mentioned, please ask for help on the Support forum on musescore.org where we can assist better.

**Comment by bkunda** [comment]
I can only affirm @MarcSabatella's suggestion here.
If in the course of seeking support on musescore.org you find this to be a generalisable issue, we can re-open the issue here. 
Thanks and hope you find a solution!
