### ISSUE TITLE
custom time sig numbers not transferring to parts

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#18620]
### Issue type

Engraving bug

### Bug description

when the display numbers of a time signature is altered in a score, the parts still have the default signature numbers on that measure instead of the custom numbers.

### Steps to reproduce

1. make a custom time sig with altered numbers on a score
2. export to parts
3. see the parts have the default numbers instead

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/120861729/cd78555c-1744-4201-a0a6-cac21000c5c4)

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

windows

**Comment by Vykoiazon** [comment]
dragging that same custom time sig into the part fixes it for that part but does not affect other parts so it has to be manually changed on every part now

**Comment by Vykoiazon** [comment]
repeat signs not on barlines (attached to notes or rests) also do not transfer from the score to parts and have to be manually added on each part

**Comment by Vykoiazon** [comment]
trill bracket notes showing which note to trill to also does not transfer from score to parts

![image](https://github.com/musescore/MuseScore/assets/120861729/cd041657-19ec-4ecc-8bf3-a5f14a07ca44)

**Comment by oktophonie** [comment]
I could only reproduce the barline example in a new score. For the others it would be useful it you could describe the sequence of events more clearly.

In any event, the entire matter of transference/linking between score and parts is one of the primary targets being worked on for 4.2 (see https://github.com/musescore/MuseScore/issues/16544)

**Comment by oktophonie** [comment]
In 4.2, these modified time signature numbers now do transfer to parts.

However, a minor problem remains: if modifying the numbers in the _part_, the time sig will become desynchronised (i.e. shown as orange) in the part, but the numbers will not actually change in the part or in the score. While it's hard to imagine a use case for this, there's also no real reason for it to not work.

Barlines also seem to transfer as far as I can tell. Aux trill notes likewise work fine (still).
