### ISSUE TITLE
Customized rest positons in MS3 are reset in MS4, resulting in collisions with fingering 

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18623]
### Issue type

Engraving bug

### Bug description

In the attached MS3 file the positions of rests have been adjusted to avoid collision with fingerings. However in MS4.1 (and perhaps before?) the custom-positioned rests are being reset to default; this causes collisions with existing fingerings.

### Steps to reproduce

Open the attached MS3 file in both MS3 and MS 4.1 (and MS 4.02?). Note the collisions between fingerings and rests in MS 4.1 due to the latter having been reset.

[rests_fingering.zip](https://github.com/musescore/MuseScore/files/12061472/rests_fingering.zip)

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by oktophonie** [comment]
By design, as the rest placement algorithm is entirely new.
