### ISSUE TITLE
Upload failed: ''Score could not be opened/This score is invalid'' popup

### ISSUE THREAD

**Issue by hayleek19847** [musescore/MuseScore#18622]
### Issue type

Cloud saving/loading issue

### Bug description

I was working on a really important project and it was finally starting to turn out good, but it was getting late and I was working on it for hours. I saved it, and when I went back to open it, it gave me the popup mentioned in the title. I tried numerous time to open it again and looked in my web score manager and it wasn't there.

### Steps to reproduce

1. Make a score
2. Close and save it
3. Choose to save it to the cloud
4. Re-open it

### MuseScore Version

4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

it happened to me on mac os monterey 12.6.2 and i think windows 11

**Comment by cbjeukendrup** [comment]
I assume you are trying to reopen the score from the Recent Scores view, right?

**Comment by hayleek19847** [comment]
Yes.

**Comment by cbjeukendrup** [comment]
In that case, I have an idea of what might be going on; probably the score failed to upload and therefore it has no valid score id. 

You can probably retrieve your score from `~/Library/Application Support/MuseScore/MuseScore4/cloud_scores`. The filename is probably something like `not_uploaded_0.mscz`.

**Comment by TimJentzsch** [comment]
I'm facing the same issue, after saving a score to the cloud.

```
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf
```

I located the `not_uploaded_0.mscz` file at `AppData/Local/MuseScore/MuseScore4/cloud_scores`, but opening this file also gives the "Your score could not be opened/This score is invalid." popup.

**Comment by cbjeukendrup** [comment]
You need to copy the score out of the cloud_scores folder; then it should be possible to open it. (Otherwise MuseScore still tries to treat it as a cloud score: it makes the decision exclusively based on the file path.)

**Comment by TimJentzsch** [comment]
That worked for me, thank you!

**Comment by shoogle** [comment]
We should warn the user if the upload fails, and also check for these `not_uploaded` scores and try to recover them.

**Comment by cbjeukendrup** [comment]
Came up again in https://github.com/musescore/MuseScore/issues/20074

**Comment by bkunda** [comment]
> We should warn the user if the upload fails, and also check for these not_uploaded scores and try to recover them.
@shoogle if you haven't already done so, feel free to raise a feature request issue for this. 

Otherwise I think this could now be closed as the proposed solution worked in at least one of the cases discussed above.
