### ISSUE TITLE
rejecting staff spacer placement on one line staff

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#18621]
### Issue type

Other

### Bug description

dragging a staff spacer on a one line staff is almost always rejected showing the error symbol when it is supposed to attach to the staff easily

### Steps to reproduce

1. get a one line staff with multiple rows
2. drag a staff spacer to a bar
3. see if it can be attached or not to the staff

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/120861729/fd7f4caa-f8e1-4d9a-b3b3-985eb9c3d4a1)

it is sometimes possible to place the spacer but most of the time it shows this error symbol and does not attach to the bar

### MuseScore Version

4.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

windows

**Comment by Vykoiazon** [comment]
it requires a very specific mouse placement (which is hard to find) for it to not show the error sign and the + sign instead which allows the spacer to attach on the staff

**Comment by MarcSabatella** [comment]
FWIW, drag & drop is rarely the efficient way to add palette items - much easier normally to first select the measure then click the palette item.  But yeah, one-line staves are tricky.  There is supposed to be a zone above & below them where you can click to select etc, but it does seem that zone isn't honored for drop.

**Comment by oktophonie** [comment]
Possibly something to do with https://github.com/musescore/MuseScore/pull/16078 (?)

**Comment by bkunda** [comment]
I can no longer reproduce this (we might have resolved it when the new drag+drop behaviour was implemented, or even earlier perhaps when we made a fix to spacers). 

Happy of course to reopen this if it can still be reproduced.
