### ISSUE TITLE
One thread or core of CPU stops working when MuseScore 4 is running

### ISSUE THREAD

**Issue by scilxurkel001** [musescore/MuseScore#18636]
### Issue type

Other type of issue

### Bug description

This issue (or bug) may not be attention by some people because now CPUs have more than 4 cores (or threads), but I got this issue for CPUs less than 4 cores (or threads)
Now the issue is in MuseScore.org (https://musescore.org/en/node/339733) but no useful information was provided there.
As the title suggests, when MuseScore 4 was turned on, one thread (or one core) of CPU seemed to stop working (the usage was less than 5%) no matter what operations or actions you did (for instance, open Microsoft Edge to search the web)

### Steps to reproduce

1. Open Task Manager, turn to "Performance" tab, Right-Click the CPU usage graphs and select "Logic processors"
2. Open MuseScore 4, and do any operations that uses CPU.
3. See the usage of CPU, and found one thread less than 5%.

(P.S. : I even disabled all my CPU configtion options, but it's just useless.)

### Screenshots/Screen recordings

Previous test video is here:
https://user-images.githubusercontent.com/82962664/225812583-70c9d044-2b51-4797-a548-fa0a9edec492.mp4

Then we did the test again, here is the video:

https://github.com/musescore/MuseScore/assets/82962664/9c1536af-8706-4ff1-8767-79cb12af5231

### MuseScore Version

MuseScore 4 RC and later version, MuseScore 4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11 22H2 (22621.1413) and now Windows 10 22H2

### Additional context

Now tested CPU: Pentium E5400
Previous test CPU: Intel (R) i5-4200M @2.50GHz (4 Cores)
You can find this issue in:
MuseScore 4.0.0 RC1
MuseScore 4.0.0 Release
MuseScore 4.0.1 Release
MuseScore 4.0.2 Release
MuseScore 4.1 Release
(Unsure for Nightly Version, because I didn't test for it)

Exceptions (In two versions of MuseScore, it's well):

MuseScore 4.0.0 Beta
MuseScore 4.0.0.223391656

The CPU will not return normal until a restart to PC.
This issue is same as https://musescore.org/en/node/339733.
And now it's yet not solved.
If it can't be solved, I cannot use the newer version of MuseScore. PLEASE!!!

**Comment by scilxurkel001** [comment]
I also found one thing: before (MuseScore 4.0) was CPU 1 stopped, and now (MuseScore 4.1) is CPU 0 stopped. In addition, there was no such problem when testing MuseScore 4.1 on the test platform of Windows 11 22H2 with i5-8900 CPU. That is to say, there is no problem with more modern CPUs and more modern systems. The CPUs that feedback the problem are the older Pentium E5400, i5-2500 and i5-4200M. The Pentium E5400 test platform is equipped with Windows 10 22H2 system. At present, this CPU is not used to test on Windows 11 22H2. The i5-4200M test platform has been handed over to others and can no longer be used for testing

**Comment by scilxurkel001** [comment]
The latest test turned out that it's a problem of CPU, not the system.
(The i5 8400 with Windows 10 runs well.)
And forgive me that I misrepresented i5 8400 as i5 8900.

**Comment by scilxurkel001** [comment]
Now in Ubuntu 22.04 LTS, this issue disappeared.
So I should install a Ubuntu for it XD

**Comment by scilxurkel001** [comment]
In response to this problem, I still give a temporary solution to make it easier for other people who encounter this problem to use it temporarily.

First, install the Windows and Ubuntu dual system on the physical machine, or use VMware to install the Ubuntu system. In addition, you also need the MuseScore 4.0 installation package (version 4.0.0.223391656) without this problem. I have a copy here, but only the MSI file. Download link: China Mirror: https://sxk001.lanzouw.com/ik8Nt0hyaw7g)

Now, first check the update on Ubuntu, then install libfuse2 (execute the command sudo apt install libfuse2), and go to MuseScore.org to download MuseScore 4.1 for Linux. 1 AppImage file, after the attributes are changed to "Runable" and "Read and Write", double-click to run. In this way, you can open files from MuseScore 4.1.

If you want to export audio using Muse Sounds, please go to the Windows system, because I have tested that the Linux version of Muse Hub cannot run on Ubuntu 22.04 LTS at all. And because MuseScore 4.0 can open MuseScore 4.1 files, but there will be problems that are not enough to affect audio playback, this method is feasible. After downloading Muse Sounds on Muse Hub, open the file with MuseScore 4.0 provided above and export the audio.

This is only a temporary solution, and I hope that developers can fix this problem as soon as possible. MuseScore is a very useful Notification Software, and I hope it gets better.

PS: As for why not using MusicXML: MusicXML exported by MuseScore 4.1 will have more or less problems when opened in all old versions of MuseScore, including missing titles, typographical errors, etc., which is why MusicXml is not used.

**Comment by scilxurkel001** [comment]
Though the test of file replace, I have comfirmed that the problem occurs in "MuseScore4.exe".
But the info may not useful.

**Comment by GutterinCode** [comment]
Use nightly version, well it's still same issue but when you close the app it makes the core\thread back to online. I'm using core i3 2th generation and I had same issue here. The specific download is MuseScoreNightly-latest-4.3.0-x86_64-portable.exe. If you have tried it then I may appreciated it, but if you don't then try these nightly version. I just give some little trick so whenever you really needed.

**Comment by scilxurkel001** [comment]
> Use nightly version, well it's still same issue but when you close the app it makes the core\thread back to online. I'm using core i3 2th generation and I had same issue here. The specific download is MuseScoreNightly-latest-4.3.0-x86_64-portable.exe. If you have tried it then I'd appreciated it, but if you don't then try these nightly version. I just give some little trick so whenever you really needed.
> 
> Edit: Have you interested in bios settings? Just in case, it may has to do with the bios settings. I had setting called "T state support" disabled, and the thread/core is automaticly online after MuseScore closed. Its located somewhere those ACPI settings placed (e.g. C3 support, Intel speed-step).

Yes, when I disabled the C1E Support and SpeedStep, the thread/core is returned to normal, but no, when MuseScore 4 is running, one core/thread(CPU 0 in Task Manager) still stops working, even with the latest Nightly Edition.  
Now I'm using Dorico and I found that MuseScore is still using Qt 5.15 but Dorico 5 is using Qt 6, and Dorico 5 has no problem with my CPU. Maybe this is the reason? (But Dorico 4 with Qt 5 has no problem either! I rather believe it is MuseScore itself cause the problem occurs...)

**Comment by scilxurkel001** [comment]
MuseScore 4.3.1 has solved this issue.
Now it has been closed, but if the issue occurs in next versions, it will be reopened.
Thanks for your efforts.
