### ISSUE TITLE
Crash  if changing expression text style

### ISSUE THREAD

**Issue by tsjam23** [musescore/MuseScore#18630]
### Issue type

Crash or freeze

### Bug description

Musescore 4.1 crashes while changing expression Text style in properties panel if measure contains notes.
Crashes on change to Composer, Title, Subtitle, Even/odd lyrics, Reheaersal mark, Repeat text left/right, instrumentname long/short, Dynamics, HArp pedal diagram.

Also it will crash if you first create expression text for an empty measure, change expression text style and then input some notes.
Doesn't crash for Musescore 4.0.2
Based on report from https://musescore.org/en/node/352403

### Steps to reproduce

1. Create empty score
2. input some notes
3. Add expression text
4. Set expression text style to Composer (or Title, Subtitle, Even/odd lyrics, Reheaersal mark, Repeat text left/right, instrumentname long/short, Dynamics, HArp pedal diagram)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/133224452/0cbd7c92-6276-48e8-9c3a-fb3d3c52deed

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment]
I'll take this one :)

**Comment by DmitryArefiev** [comment]
Fixed in #18647
