### ISSUE TITLE
Program crashes when using Cmd+Y

### ISSUE THREAD

**Issue by contrappuntista** [musescore/MuseScore#18635]
### Issue type

Crash or freeze

### Bug description

OS: macOS 13.4, Arch.: x86_64,
MuseScore version (64-bit): 4.1.0-231921401,
revision: github-musescore-musescore-2e3a93a

Independently of the file I am working on, clicking Cmd+Y causes the program to crash. Pretty specious when switching between QWERTY and QWERTZ keyboard setups (program crashes when you are expecting to undo the last action).

### Steps to reproduce

1. Open Musescore
2. Open any .mscz file
3. Input Cmd+Y
4. Result

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231921401, revision: github-musescore-musescore-2e3a93a

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: macOS 13.4, Arch.: x86_64,

**Comment by DmitryArefiev** [comment]
Fixed in #18657
