### ISSUE TITLE
AppImage file won't execute on Ubuntu: "AppImages require FUSE to run."

### ISSUE THREAD

**Issue by Flimm** [musescore/MuseScore#18633]
### Issue type

Other type of issue

### Bug description

It looks like this version of MuseScore was compiled using an old version of AppImage. Because of this, it won't launch on Ubuntu 23.04. Newer versions of AppImage support newer versions of Ubuntu, like 23.04. For more information, read [this article and its comments](https://www.omgubuntu.co.uk/2023/04/appimages-libfuse2-ubuntu-23-04).

### Steps to reproduce

I downloaded the MuseScore application for Linux, in the AppImage format, from the website ([link](https://musescore.org/en/download/musescore-x86_64.AppImage)). I made the file executable, and then I attempted to run it. Nothing happened. I'm running Ubuntu 23.04.

I attempted to run it from the terminal, and this is the error message that I saw:

```
$ ./MuseScore-4.1.0.231921359-x86_64\(1\).AppImage 
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

### MuseScore Version

OS: Ubuntu 23.04, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

Ubuntu 23.04 (x86_64)

**Comment by bkunda** [comment]
@igorkorsukov @shoogle when you get time can you please provide your assessment about what would be required to address this? Thanks!

**Comment by ydalton** [comment]
Last time I heard AppImages still required libfuse2 in order to run. The article you linked doesn't say anything about AppImages using libfuse3, and it even tells you to install libfuse2 to get AppImages working. I could be wrong, though.

**Comment by AntonioBL** [comment]
From what I see, there are two versions of `appimagetool `at the moment: the "classic" one, distributed in the Github repository [AppImage/AppImageKit](https://github.com/AppImage/AppImageKit), and a new static-build one from the repository [AppImage/appimagetool](https://github.com/AppImage/appimagetool) (this repository was created 3 weeks ago).
MuseScore is using the up-to-date "classic" version of `appimagetool`, see [here](https://github.com/musescore/MuseScore/blob/f5f09175e2ca897272a40fc9a82a6edd548927e7/build/ci/linux/tools/make_appimage.sh#L53C3-L53C29), but it could switch to the static version by chagning the repository at that line (maybe also a coouple of other changes in the packaging script). This new version is still probably labelled as experimental, but it should work without the additional libfuse2 dependency.

**Comment by AntonioBL** [comment]
@Flimm : you can try to see if the following test AppImage of master branch works even without libfuse2:
https://github.com/AntonioBL/MuseScore/suites/14517667739/artifacts/821079092
(the zip archive contains the test AppImage and other folders that are not needed: you can delete them)
I swapped the old appimagetool with the newer one, and the resulting AppImage should have all the required libraries (e.g. libfuse2) statically linked.

**Comment by Flimm** [comment]
Thanks @AntonioBL . The download you provided worked on my system, which doesn't have `libfuse2` installed.

**Comment by AntonioBL** [comment]
@Flimm : thank you for testing.
I will thus proceed with a pull request

**Comment by Flimm** [comment]
The latest release `./MuseScore-4.1.1.232071203-x86_64.AppImage` that was released two days ago still has this problem.

**Comment by AntonioBL** [comment]
@Flimm : indeed, the new AppImage format is used at the moment only in master branch (i.e. future 4.2 version).
However, there seem to be some problem with the new format, see https://github.com/musescore/MuseScore/issues/18830
I suspect it could be an interaction between the AppImageLauncher and the AppImage itself.

**Comment by shoogle** [comment]
Sadly we had to revert this fix. See https://github.com/musescore/MuseScore/issues/18830#issuecomment-1656306321 for an explanation.

Feel free to re-open this issue when https://github.com/TheAssassin/AppImageLauncher/issues/585 has been resolved upstream.

---

In the meantime, when Ubuntu users see this message:

```
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

The workaround is:

```Bash
sudo add-apt-repository universe   # only needed in minimal environments (e.g. Docker, Live USB, etc.)
sudo apt install libfuse2
```

**Comment by worldwideweary** [comment]
FWIW, by proxy, looks like Linux Mint will also have this problem...
