### ISSUE TITLE
Crash when moving tempo lines in parts

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#18644]
### Issue type

Crash or freeze

### Bug description

Musescore 4.1.0 (4.0.2 also) crashes when moving tempo mark (tested with rit. and accel.). It's hard to reproduce in real multi-measure score, but I got crash for 1 and 2 measure scores. 

The real score you can find here https://musescore.org/en/node/352431 (also crashes when moving rit. in parts)

### Steps to reproduce

1. Create score with two instruments (for example, violin and piano), containing 2 measures (time signature 4/4)
2. Make quarter rests on last measure
3. Add ritenuto to the last rest.
4. Open Parts for Piano
5. Try to move ritenuto by mouse and Musescore will crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/5f43f723-956d-4e0d-b5e4-7ddf06321ae7

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

Windows 10 Version 2009

**Comment by cbjeukendrup** [comment]
This seems to be related to this whole story: [#16796](https://github.com/musescore/MuseScore/issues/16796)

(Preventing this crash from happening seems easy, but we might want to work on a real solution instead)
