### ISSUE TITLE
Playback issues with Grace Notes using  Electric Guitar Modes

### ISSUE THREAD

**Issue by meatexe** [musescore/MuseScore#18654]
### Issue type

General playback bug

### Bug description

Whenever a Electric Guitar in any mode (Distorted, Overdrive etc.) plays a Grace Note the playback for the Grace note will play as the default sound.

### Steps to reproduce

1. Make a note on a Electric Guitar staff
2. Select any mode for the guitar to be on
3. Place a Grace note on the note you just placed
4. Press play

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/139741941/008bc694-5860-452a-8fd9-854beea56f28

### MuseScore Version

4.1 

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11 I'm not to sure about other OS

### Additional context

This bug occurs using SoundFonts and MS Basic, I haven't tested it out with VSTs

**Comment by chunga2020** [comment]
Can confirm it also happens on Linux

**Comment by bkunda** [comment]
@zacjansheski pls check for reproducibility

**Comment by zacjansheski** [comment]
This is still actual and similar to the issue of pizz not working on grace notes
https://github.com/musescore/MuseScore/issues/19266
