### ISSUE TITLE
Marching Bass Drums

### ISSUE THREAD

**Issue by brandonbrookspercussion** [musescore/MuseScore#18674]
### Your idea

This is a minor one but visually and for playback sake it would be helpful.

1. There is a note head for unison bass drum section playing. There needs to be an X head notation available as well. There are individual ones for rim clicks for example. There isn't for unisons.

2. Number of bass drums. While most drum lines use up to 5 basses, some do use more. Currently there is no way to notate more than 5.

3. There is no letter assigned to the top bass drum. (Example bottom bass can be entered via the A key on the keyboard). You have to manually select that note. Having a letter assigned would greatly speed up the notation/writing process.

4. Is there any way to have the ability to just drag the "pitches" vs having to hit specific notes.

5. No buzz roll sound for basses.

### Problem to be solved

See above. It was easier to condense the info. 

### Prior art

No

**Comment by Motorblade** [comment]
This is all possible using the [MuseScore Drumline plugin](https://musescore.org/en/mdl). I'd either wait for the plugin to be ported to MuseScore 4 or stick to MuseScore 3 for drumline writing for now.

**Comment by PholMC** [comment]
There's a tutorial I used to add MDL to MS4: https://www.youtube.com/watch?v=ccV8kR8hKzU

**Comment by brandonbrookspercussion** [comment]
Thank you guys. I will have to try some of this ASAP. I am in the middle of percussion camp at the moment.

**Comment by brandonbrookspercussion** [comment]
Ok. One week of band camp down.

I've taken a look at doing this and it seems an overly complicated way to set up Musescore 4 for marching percussion and frankly I'm in a time crunch. 

I did the steps for MS3. 

Will there be a fix for this to make it less complicated.

**Comment by brandonbrookspercussion** [comment]
Also if I. Trying to write for both hand to play at once on tenors, do I have to create a second voice. That's also a bit cumbersome. 

Example and workaround. Drum 4 8th notes with L hand. R hand plays 2 and 4 on drum 1. I couldn't enter all the 8ths on drum 4 and add drum 1. I had to enter all 8th notes on drum 4 except count 2 & 4  on drum 1, then go back and add the missing 8th notes on drum 4. Weird.

**Comment by brandonbrookspercussion** [comment]
Another quirk/bug I've run into a few times. When working with the battery template, the snare sound won't play back. If I add another snare staff, the sound on that staff will play.

**Comment by MarcSabatella** [comment]
For general help using MuseScore, please ask on the official Support forum on musescore.org.  Be sure to attach your score and describe the problem in enough detail to allow us to understand and assist.

**Comment by zacjansheski** [comment]
All of these issues will be resolved in one way or another in our next release.  (Shortcuts updated in MS Basic, new sounds will be available with new drumline library)

See https://github.com/musescore/MuseScore/pull/20823

Closing this issue now, thank you!
