### ISSUE TITLE
problems with the score reproduction and sounds 

### ISSUE THREAD

**Issue by depiesligeros** [musescore/MuseScore#18678]
### Issue type

General playback bug

### Bug description

im a linux user, the problem that i have began when i updated the system a few days ago. i was trying to continue my work  but i noticed that the sound did no came out or even reproduce. 

### Steps to reproduce

1. open musescore
2. write some notes 
3. does not sound/ play the piece (does not reproduce)

### Screenshots/Screen recordings

![logs](https://github.com/musescore/MuseScore/assets/84427988/5779e974-5759-4562-8b1c-1a8f966646a1)

### MuseScore Version

musescore4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Arch Linux  x86_64

**Comment by depiesligeros** [comment]
i solve the problem changing the sound system, from pulse audio to pipewire...
now it has sound and it reproduce everything fine, even with musehub

**Comment by cbjeukendrup** [comment]
That sounds like it is related to #11220. I'll close this issue, but will add your case to #11220.
