### ISSUE TITLE
[TIED NOTES] Trills that do not last the length of a tie do not play the full tie

### ISSUE THREAD

**Issue by Motorblade** [musescore/MuseScore#18676]
### Issue type

Choose option...

### Bug description

BK EDIT:
@RomanPudashkin there's a lot of content below (some of which was also repeated in various duplicate issues, which I've now closed). The below summary hopefully captures all the main issues, organised according to sound technology: 

#### Muse Sounds

- If the trill line doesn’t last at least the full duration of all the tied notes, playback will stop after the first note (Same if only a single note trill is applied to the first note).
- If a trill is applied to any note other than the first note of a tied group, the trill sample will not be triggered

https://github.com/musescore/MuseScore/assets/86290556/1ca2d31a-506f-40bd-9609-bff59dfaf115

#### SoundFont/VST

- If the trill line doesn’t last at least the full duration of all the tied notes, only the first and final notes in the trill group will play. If a single note trill is applied to the first note, playback will stop after the first note. 
- If a trill line is applied to any note other than the first note of a tied group – and it extends all the way to the end of the trill group – then the trill will only sound on the final note of the group. If the trill line does not extend to the last note in the group, then the trill will not play at all.

https://github.com/musescore/MuseScore/assets/86290556/71e589a7-b19f-45d8-b389-70a7bad9acd3

-----------------------------------------------

ORIGINAL ISSUE DESCRIPTION

When applying a trill marking to tied notes, only the first note of the tie will play. Any tied notes after the first note will be silent.

Expected behavior would be either to play and trill all remaining notes in the tie, or to trill the affected note(s) and sustain for the rest of the tie. Currently the rest of the tie is not played at all.

This affects both MS Basic and Muse Sounds. MS Basic seems to have more issues with this.

Here is the file showing the error:
[Trill tie playback error.zip](https://github.com/musescore/MuseScore/files/12074286/Trill.tie.playback.error.zip)

### Steps to reproduce

1. Tie multiple notes together.
2. Add a trill marking to the first note of the tie, without dragging the trill line to every note.
3. Upon playback, only the first note of the tie will play.

### MuseScore Version

4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

Choose option...

### Operating system

Windows 10

**Comment by zacjansheski** [comment]
Here is a video recording for visibility purposes (Both MuseSounds and MS Basic)


https://github.com/musescore/MuseScore/assets/69917893/5d30c87a-9d61-4366-bb4d-8bd2173ce86b

**Comment by Vykoiazon** [comment]
![image](https://github.com/musescore/MuseScore/assets/120861729/f5985d1f-7feb-4d8e-9f30-be5a6cbe58e0)

trills on a tied note do not playback unless the tie is removed

**Comment by MarcSabatella** [comment]
Another data point: with MS Basic at least, in 4/4, *exactly two notes* tied and trilled - plays fine.  *More than two notes* all tied and trilled, though, and only the first and last notes play; everything is silenced in the middle notes:

https://github.com/musescore/MuseScore/assets/1799936/02fa6fca-a365-426d-9b6d-92f3034a0fb4

**Comment by s11141827** [comment]
I hope it gets updated soon

**Comment by s11141827** [comment]
> Another data point: with MS Basic at least, in 4/4, _exactly two notes_ tied and trilled - plays fine. _More than two notes_ all tied and trilled, though, and only the first and last notes play; everything is silenced in the middle notes:
> trill-tie.mp4

I'm having this issue too when I play Stravinsky's Firebird on the Musescore Player

**Comment by MarcSabatella** [comment]
> > Another data point: with MS Basic at least, in 4/4, _exactly two notes_ tied and trilled - plays fine. _More than two notes_ all tied and trilled, though, and only the first and last notes play; everything is silenced in the middle notes:
> > trill-tie.mp4
> 
> I'm having this issue too

Please top spamming the GitHub issue tracker with “me too” comments.  There is no reason to respond to an existing issue unless it is a to provide new information that will enable developers to reproduce a bug they are having trouble with, or something equally significant.  And *especially* refrain from posting the same “me too” comment to multiple threads.

**Comment by Dima12357** [comment]
The same problem is described in issues #21109 and #22031

**Comment by sudo-matcha** [comment]
I have a possible new datapoint since I haven't noticed any users reporting the problem while using a linux distro. Im using Musescore Studio 4.3 on Ubuntu Studio (KDE X11 env).
I came across this issue while writing this string part. Only the top note of the chord continues;all the other notes get silenced.

https://github.com/musescore/MuseScore/assets/77501966/d1edc6e7-d1dd-4324-8075-0337a2292c38
