### ISSUE TITLE
Problem with Tin Whistle Tablature plugin in MU4.1

### ISSUE THREAD

**Issue by gb1232** [musescore/MuseScore#18680]
### Issue type

Other type of issue

### Bug description

Whistle Tablature Plugin no longer works on MuseScore 4.1/

### Steps to reproduce

1. Dreate a staff with Instrument - Tin Whistle
2. Enter some notes
3. Go to Plugins > Composing/Arranging Tools > Tin Whistle Tablature

### Screenshots/Screen recordings

![Screen Shot 2023-07-14 at 3 43 12 PM](https://github.com/musescore/MuseScore/assets/139798299/6bf3efb0-9238-4a52-bed8-8b813fa3ca96)

### MuseScore Version

Version 4.1.0.231921401 Revision 2e3a93a

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 12.6.6

### Additional context

I have recently upgraded from MuseScore 4.0 to 4.1. It appears that the Tin Whistle Tablatre plugin no longer works. When I try and add the tablature to my score, the following error message is displayed:

"No selected staff in the current score uses a tin whistle instrument

Use tab "Instruments -> Add" to select instruments"

The tablature is displayed correctly when I use MuseScore 4.0 on the same score.

Here is the beginning of the plugin file:

//=============================================================================

//  MuseScore

//  Music Composition & Notation

//

//  Tin Whistle Tab Plugin

//  Requires the tin whistle font downloaded from Blayne Chastain:

//    https://www.blaynechastain.com/tin-whistle-tab-sibelius-plugin/

//

//  Based on the Note Names Plugin which is:

//  Copyright (C) 2012 Werner Schweer

//  Copyright (C) 2013 - 2016 Joachim Schmitz

//  Copyright (C) 2014 Jörn Eichler

//

//  and also based on the Recorder Woodwind Tablature plugin:

//  Copyright (C)2011 Dario Escobedo, Werner Schweer, Jens Iwanenko and others

//

//  This program is free software; you can redistribute it and/or modify

//  it under the terms of the GNU General Public License version 2

//  as published by the Free Software Foundation and appearing in

//  the file LICENCE

//=============================================================================

import QtQuick 2.15

import QtQuick.Dialogs 1.3

import MuseScore 3.0

MuseScore {

  version: "4.1"

  description: "This plugin provides fingering diagrams for the tin whistles, requires `TinWhistleTab.ttf` font"

  title: "Tin Whistle Tablature"

  categoryCode: "composing-arranging-tools"

Is there a more recent version of the plugin for MuseScore 4.1?

Thanks,

Gary Burke

**Comment by cbjeukendrup** [comment]
I just downloaded the latest version of this plugin from https://musescore.org/en/project/tin-whistle-tablature, and it seems to work just fine for me. Is that the same one as you are using?

**Comment by gb1232** [comment]
I installed the updated plugin and it works as expected. Thanks for the help.
