### ISSUE TITLE
On Linux, MuseScore 4.1 can overwrite read-only files

### ISSUE THREAD

**Issue by RexDjere** [musescore/MuseScore#18681]
### Issue type

Other type of issue

### Bug description

I'm writing a books of 500 saxophone etudes which I keep in my home directory: /home/myusername/Sync/500_Daily_Saxophone_Etudes/mscz/

I name each etude by its number, for example 050.mscz, or 442.mscz.  After I finanalize each etude, I set it to read-only so that I don't inadvertently change it after it's finalized. I then use the sha256sum cli function to get the etude's hash, and record it in a records file. I verified that each etude has 444 permissions (read-only for user, group, and other) using the ls -l command.

To my surprise, the MuseScore 4.1 appimage binary can still save over the MuseScore file, even though it is set to read-only. Steps to reproduce are below.

### Steps to reproduce

1. Download Musescore 4.1 appimage on a Pop!_OS 22.04 LTS system.
2. Make the MuseScore appimage executable.
3. Create a new MuseScore score in your home directory.
4. Save the new Musescore score in your home directory.
5. Make the new score read-only using either CLI command chmod 444 newscore.mscz, or using the GUI interface.
6. Open the read-only score using the MuseScore 4.1 appimage.
7. Make a change to the score, and attempt to save the changed version.

Expected behavior:
MuseScore should say something like "the file cannot be saved because it is read-only".

Actual behavior:
MuseScore saves over the file, and after the save, the file is no longer read-only.

### Screenshots/Screen recordings

I don't have the ability to screen capture right now, but I have verified the behavior above on my Pop!_OS 22.04 LTS system several times in the last few days.

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

Pop!_OS 22.04 LTS

### Additional context

I trust the MuseScore developers, but this seems like a security issue: is it possible that MuseScore could write over read-only Linux system files?

**Comment by bkunda** [comment]
@cbjeukendrup @igorkorsukov could either of you please help with a response here? Thanks!

**Comment by RexDjere** [comment]
@cbjeukendrup I've never seen a program be able to write over a file that I explicitly made read-only before, so I was really concerned when I noticed it. I explicitly set the file's permissions to 444 meaning that the the user, group, and other should only be able to read the file. If a program doesn't respect the user's set permissions, is it safe to run the program?

**Comment by MarcSabatella** [comment]
The norm is that a program would ask for permission before overwriting a read-only file (see for instance the "mv" command in Linux).  Anyhow, the program is definitely safe, even if it contains this quirk that no one had yet noticed or pointed out before - so thanks for being the first :-)

**Comment by cbjeukendrup** [comment]
MuseScore does nothing weird as far as I can tell, and I'd say it's the responsibility of your (file) system to enforce that permissions are respected. 

More specifically, MuseScore ultimately makes use of the `QFile::rename` and `QDir::rename` methods from the Qt framework. You could try creating a dummy test application using Qt and check if it behaves the same.

**Comment by cbjeukendrup** [comment]
By the way, how does MuseScore 3 behave, for comparison?

**Comment by RexDjere** [comment]
@MarcSabatella and @cbjeukendrup Thank you so much for the very informative responses. So what I'm taking away from what you've said is that this isn't really a bug, it's just a feature of Linux, and MuseScore is 100% safe to run as an appimage, correct?

**Comment by cbjeukendrup** [comment]
Yes, MuseScore should be just as safe as any other Qt-based application (and there are _a lot_ of those 🙂)

**Comment by cbjeukendrup** [comment]
However, to be more cautious, we could, as Marc suggests, implement a feature to check by ourselves if the target file is read-only, and if so, ask the user a question about that.

**Comment by MarcSabatella** [comment]
For me, with 3.6.2 on Linux, a save operation on a read-only file just silently fails.  No warning or error, and the file is not updated.  You still have the asterisk on the tab, you still get a warning when you try to close, so that is how you know the save failed, but - yeesh.

**Comment by johny4** [comment]
Hello! Can I have a go on this issue? I was able to replicate it on Linux and can confirm that Windows has a different behaviour when saving to read-only files.

**Comment by cbjeukendrup** [comment]
@johny4 Yes, you're welcome!
