### ISSUE TITLE
MuseScore system package on Linux Mint is still on MuseScore 2

### ISSUE THREAD

**Issue by RustoMCSpit** [musescore/MuseScore#18682]
### Issue type

Other type of issue

### Bug description

MuseScore Flatpak and System Package on Linux Mint's Package Manager need updates, furthermore, I din't think MuseHub is on the Package Manager

### Steps to reproduce

Download System Package or Flatpak on the Linux Mint Package Manager

### MuseScore Version

4

### Regression

I don't know

### Operating system

linux mint stable jammy

**Comment by bkunda** [comment]
@cbjeukendrup @igorkorsukov could either of you please help with a response here? Thanks!

**Comment by cbjeukendrup** [comment]
Packages from third-party repositories and package managers are not maintained by us. (Perhaps some used to be in the past, but nowadays they aren't anymore.) So I'm afraid we can't do much about this, and you'll need to find out who currently maintains Linux Mint MuseScore packages. 

Muse Hub (and Muse Sounds) are not open source, which might be the reason that they are not available via most package managers. But this too is up to the maintainers of those package managers.

I'll close this issue for now, but if we do need to do something, we can reopen it (or if it's something specific, for example build-related, someone can open a new issue).

**Comment by RustoMCSpit** [comment]
> Packages from third-party repositories and package managers are not maintained by us. (Perhaps some used to be in the past, but nowadays they aren't anymore.) So I'm afraid we can't do much about this, and you'll need to find out who currently maintains Linux Mint MuseScore packages.
> 
> Muse Hub (and Muse Sounds) are not open source, which might be the reason that they are not available via most package managers. But this too is up to the maintainers of those package managers.
> 
> I'll close this issue for now, but if we do need to do something, we can reopen it (or if it's something specific, for example build-related, someone can open a new issue).

https://flathub.org/apps/org.musescore.MuseScore
thats the source, having someone else maintain it sounds like a massive security risk

**Comment by cbjeukendrup** [comment]
But that's the case with almost all packages in almost all package managers, right?
We simply don't have enough resources to provide, and test(!), 20 different build scripts that can build for 20 different package managers on I don't know how many Linux distros. That's why we provide and recommend the AppImage version.

**Comment by RustoMCSpit** [comment]
> But that's the case with almost all packages in almost all package managers, right? We simply don't have enough resources to provide, and test(!), 20 different build scripts that can build for 20 different package managers on I don't know how many Linux distros. That's why we provide and recommend the AppImage version.

sorry for naievty buts whats an appimage

**Comment by cbjeukendrup** [comment]
AppImage is a format to distribute apps in a single file that can run on all kinds of Linux distributions. To run, just make the AppImage file executable and run it. You can also "install" an AppImage. Here's more about it: https://appimage.org and https://github.com/AppImage/appimagekit

You can download MuseScore's AppImage directly from https://musescore.org.
