### ISSUE TITLE
Issues of displaying fonts in various UI elements

### ISSUE THREAD

**Issue by 0xfadead** [musescore/MuseScore#18704]
### Issue type

UI bug

### Bug description

Multiple UI elements have problems with displaying the cantarell font.
Changing the font in `Edit -> Preferences -> Appearance -> Font Face` does not fix the issue.

On startup:
```
(mscore:22550): Pango-WARNING **: 17:09:12.488: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 11'

(mscore:22550): Pango-WARNING **: 17:09:12.488: font_face status is: <unknown error status>

(mscore:22550): Pango-WARNING **: 17:09:12.488: scaled_font status is: out of memory

(mscore:22550): Pango-WARNING **: 17:09:12.488: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 11'

(mscore:22550): Pango-WARNING **: 17:09:12.488: font_face status is: <unknown error status>

(mscore:22550): Pango-WARNING **: 17:09:12.488: scaled_font status is: out of memory

(mscore:22550): Pango-WARNING **: 17:09:12.559: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 11'

(mscore:22550): Pango-WARNING **: 17:09:12.559: font_face status is: <unknown error status>

(mscore:22550): Pango-WARNING **: 17:09:12.559: scaled_font status is: out of memory

(mscore:22550): Pango-WARNING **: 17:09:12.559: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 11'

(mscore:22550): Pango-WARNING **: 17:09:12.559: font_face status is: <unknown error status>

(mscore:22550): Pango-WARNING **: 17:09:12.559: scaled_font status is: out of memory
```

On opening the file dialog:
```
(mscore:22550): Pango-WARNING **: 17:10:35.854: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 15.83984375'

(mscore:22550): Pango-WARNING **: 17:10:35.854: font_face status is: <unknown error status>

(mscore:22550): Pango-WARNING **: 17:10:35.854: scaled_font status is: out of memory

(mscore:22550): Pango-WARNING **: 17:10:35.854: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 15.83984375'

(mscore:22550): Pango-WARNING **: 17:10:35.854: font_face status is: <unknown error status>

(mscore:22550): Pango-WARNING **: 17:10:35.854: scaled_font status is: out of memory

(mscore:22550): Pango-WARNING **: 17:10:35.887: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Medium 11 @wght=500'

(mscore:22550): Pango-WARNING **: 17:10:35.887: font_face status is: <unknown error status>

(mscore:22550): Pango-WARNING **: 17:10:35.887: scaled_font status is: out of memory

(mscore:22550): Pango-WARNING **: 17:10:35.888: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Medium 11 @wght=500,wght=500'

(mscore:22550): Pango-WARNING **: 17:10:35.888: font_face status is: <unknown error status>

(mscore:22550): Pango-WARNING **: 17:10:35.888: scaled_font status is: out of memory
```

### Steps to reproduce

1. Open musescore
2. Click on "Open other..."

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/69577313/926320ab-b16b-4570-aaaa-6ff3786599b7)
![image](https://github.com/musescore/MuseScore/assets/69577313/d8ac34c2-9ed6-4753-879e-d984f317c0fc)

### MuseScore Version

MuseScore4 4.1.0 (newest extra/musescore version)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Arch Linux 

### Additional context

Cantarell does in fact exist and is accessible:
```
$ fls /usr/share/fonts/cantarell 
total 176K
drwxr-xr-x 1 root root   72 Jul 19 14:40 .
drwxr-xr-x 1 root root  196 Apr 30 14:46 ..
-rw-r--r-- 1 root root 167K Dec 10  2021 Cantarell-VF.otf
-rw-r--r-- 1 root root 1.5K Jul 19 14:40 fonts.dir
-rw-r--r-- 1 root root 1.5K Jul 19 14:40 fonts.scale
```

Complete musescore console log:
https://pastebin.com/fbBVPHgF

**Comment by cbjeukendrup** [comment]
Did this work in 4.0.2 and is it broken in 4.1?

**Comment by ProjektOpensource** [comment]
> Did this work in 4.0.2 and is it broken in 4.1?

I did not use Musescore in a while, therefore I can't give any exact version number, sorry.
But I can say, that it definitely worked in a former version of Musescore 4.

**Comment by chunga2020** [comment]
I used 4.0.2, and I can at least confirm that the file picker was displaying correctly in 4.0.2

**Comment by ajyoon** [comment]
I was just about to report this same issue 
![file-viewer](https://github.com/musescore/MuseScore/assets/15976214/91bea219-0243-4858-ba90-bee5ad308623)

Musescore 4.1.0 on GNOME 44.3

**Comment by ajyoon** [comment]
[This issue from another project using Qt](https://github.com/telegramdesktop/tdesktop/issues/5156) looks very similar

**Comment by ajyoon** [comment]
I can confirm this still occurs on master as of 0c62c78fa8e024f4f30fa9cf07408c9d6e97583e. I could not bisect the issue because for some reason my cmake can't build earlier releases. I also attempted to `chmod 775` my cantarell font files in `/usr/share/fonts`, then running `fc-cache` and relaunching musescore, but no dice.

**Comment by ajyoon** [comment]
Just confirmed that installing `qgnomeplatform-qt5` fixed the issue for the file dialog on my end too. I also confirmed the color picker is still broken as described. Thanks for sharing the workaround!

**Comment by 0xfadead** [comment]
Update: qgnomeplatform-qt[5, 6] has been removed from the arch repos for some reason(?)

**Comment by electron271** [comment]
having the same issue, and the reason it was removed is since it is no longer maintained

**Comment by electron271** [comment]
workaround found, downgrade to 4.0.2-2

**Comment by MarcSabatella** [comment]
Is this reproducible for you using the current supported version (4.1.1, AppImage)?  And are there any other fonts that have this problem, or just cantarell?

**Comment by salexan2001** [comment]
I can reproduce this issue in musescore version 4.1.1 using the official archlinux package.

Removing the cantarell-fonts (`pacman -Rdd cantarell-fonts`) makes the text appear in the dialog correctly... but of course this leads to many other text-displays being broken.

**Comment by MarcSabatella** [comment]
There's not really any such thing as an "'official archlinux package" for MuseScore.  Repository maintainers do indeed sometimes create their own packages, but third-party builds like these often have problems due to incorrect build procedures.  That is a big reason why MuseScore develops, tests, and supports the AppImage as the official / supported build for Linux.  You can download (and optionally install) this directly via the msuescore.org download page.

So the question remains, does the official supported 4.1.1 AppImage build work correctly for you, and also, is cantarell the only font with an issue?

**Comment by salexan2001** [comment]
Thanks for clarifying this!

I just checked the AppImage (Version: 4.1.1.232071203): I do not see any issues with fonts, especially with the Cantarell-font in the dialogs in this version.

**Comment by 0xfadead** [comment]
I can confirm that **the FileDialog** is not broken in the AppImage, the ColorPicker in `Preferences -> Appearance -> any ColorSelector` is broken (as can be seen in the photo below).

![image](https://github.com/musescore/MuseScore/assets/69577313/edb4173a-bcea-4ebf-b55c-a276d8d6f3d1)

**Comment by salexan2001** [comment]
In my case the ColorPicker is fine in the AppImage.

**Comment by phmccarty** [comment]
A workaround was mentioned in an Arch Linux forum thread to install `cantarell-static-fonts` from the AUR instead of `cantarell-fonts` from the main repos. That workaround fixed the display issue for me, so it might provide more hints about a solution.

https://bbs.archlinux.org/viewtopic.php?pid=2120705#p2120705

**Comment by 0xfadead** [comment]
Thanks for the workaround!
This fixes Musescore.
I also noticed, that it fixed another font issue in the `Luxcoreui`, which was broken as well.
Because of this I'm starting to think, that this is rather an issue with `cantarell-fonts` or an in-between API rather than Musescore itself, though other parts of the OS worked perfectly with the normal `cantarell-fonts` package.

**Comment by phmccarty** [comment]
> Thanks for the workaround! This fixes Musescore. I also noticed, that it fixed another font issue in the `Luxcoreui`, which was broken as well. Because of this I'm starting to think, that this is rather an issue with `cantarell-fonts` or an in-between API rather than Musescore itself, though other parts of the OS worked perfectly with the normal `cantarell-fonts` package.

Yep, it appears to be a side-effect of the Arch Linux musescore package not linking to the system-installed freetype library. I confirmed this by cherry-picking the commit merged from https://github.com/musescore/MuseScore/pull/19000 and testing a local build.

Downstream bug report for tracking: https://bugs.archlinux.org/task/79782

**Comment by JustinS-B** [comment]
@phmccarty Thanks for the `cantarell-static-fonts` workaround, that fixed it for me too. I tried the `qgnomeplatform-qt5` one first, but that had no effect for me, but switching the fonts nailed it.

**Comment by muxina-credo** [comment]
> A workaround was mentioned in an Arch Linux forum thread to install `cantarell-static-fonts` from the AUR instead of `cantarell-fonts` from the main repos. That workaround fixed the display issue for me, so it might provide more hints about a solution.
> 
> https://bbs.archlinux.org/viewtopic.php?pid=2120705#p2120705

This solved the issue for me. But when will one know when to revert to the `cantarell-fonts` ?

**Comment by phmccarty** [comment]
> > A workaround was mentioned in an Arch Linux forum thread to install `cantarell-static-fonts` from the AUR instead of `cantarell-fonts` from the main repos. That workaround fixed the display issue for me, so it might provide more hints about a solution.
> > https://bbs.archlinux.org/viewtopic.php?pid=2120705#p2120705
> 
> This solved the issue for me. But when will one know when to revert to the `cantarell-fonts` ?

If you have an account on the Arch bug reporting system, you can watch [the issue](https://bugs.archlinux.org/task/79782) to receive notifications about when that bug's status changes.

**Comment by Fifis** [comment]
I was able to recreate this behaviour on Arch Linux 6.6.1 + KDE where Cantarell was set as the default font. This issue does not appear in the AppImage version:

![2023-12-04_01-26](https://github.com/musescore/MuseScore/assets/5990916/bb9826ee-4c62-49cd-8666-2731e83eb04f)

However, with `cantarell-fonts` (that are not static), the result with the `musescore` package from AUR is tofu:

![2023-12-04_01-54_1](https://github.com/musescore/MuseScore/assets/5990916/9182903b-3c87-423a-be6f-a2fb0cf31034)

Not only that, but the menu font reverts to some fixed-width option:

![2023-12-04_01-54](https://github.com/musescore/MuseScore/assets/5990916/d28fc9c6-3e11-4432-8ed4-106ffb887e8b)

The corresponding console log message is appropriate:

```
(mscore:272478): Pango-WARNING **: 01:37:02.175: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 11'
(mscore:272478): Pango-WARNING **: 01:37:02.175: font_face status is: <unknown error status>
(mscore:272478): Pango-WARNING **: 01:37:02.175: scaled_font status is: out of memory
```

Whilst using static Cantarell fonts indeed solves the problem, maybe a fail-safe option could be added in the form of ‘if Cantarell fonts not found / inaccessible / generic Pango error, fall back to the default sans-serif font’? I believe that the behaviour should be consistent between the top-bar menu (substituted font, but at least something legible) and export dialogue (tofu, which is illegible).

**Comment by phmccarty** [comment]
The original Arch Linux bug report was migrated to this Gitlab issue: https://gitlab.archlinux.org/archlinux/packaging/packages/musescore/-/issues/2

The problem should be fixed in `musescore 4.1.1-4`, pushed to the repo a few hours ago.

**Comment by phmccarty** [comment]
> Whilst using static Cantarell fonts indeed solves the problem, maybe a fail-safe option could be added in the form of ‘if Cantarell fonts not found / inaccessible / generic Pango error, fall back to the default sans-serif font’? I believe that the behaviour should be consistent between the top-bar menu (substituted font, but at least something legible) and export dialogue (tofu, which is illegible).

I agree that it would be nice for MuseScore to fall back to another appropriate font in case the default font throws Pango errors.

**Comment by 0xfadead** [comment]
This issue seems to be fixed (I have no bugged fonts).
I am therefore closing this issue as completed.

Thanks to everyone who helped fix it!
