### ISSUE TITLE
Musescore crashes when inputing tuplets to staff with tabulature

### ISSUE THREAD

**Issue by 3YY3** [musescore/MuseScore#18708]
### Issue type

Crash or freeze

### Steps to reproduce

Open Musescore
1. click 'New score'
2. Create from template / Category - Solo / Template - Guitar + Tablature
3. click 'Done'
4. click 'Tuplets' / choose any (triplet for example)

### MuseScore Version

4.1.0

### Regression

I don't know

### Operating system

Win 10 x64

### Additional context

[crashlog.zip](https://github.com/musescore/MuseScore/files/12099280/crashlog.zip)

**Comment by oktophonie** [comment]
Duplicate (yet another) of https://github.com/musescore/MuseScore/issues/18595 and will be fixed in 4.1.1 (which will be released soon).

If this crash is blocking your work, you can get 4.1.1 (the latest nightly) here:
https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/?C=M;O=D

**Comment by 3YY3** [comment]
I was searching for bug containing 'triplet' specifically, not 'tuplet', my fault. I appologise. Thanks for info.
