### ISSUE TITLE
Incorrect FSF address

### ISSUE THREAD

**Issue by jamesjer** [musescore/MuseScore#18710]
### Issue type

Other type of issue

### Bug description

The Fedora Linux distribution is doing a license audit.  During that effort, we found a number of MuseScore files that have an incorrect address for the FSF.  They moved from 675 Mass Ave, Cambridge, MA 02139 to 51 Franklin Street, Suite 500, Boston, MA 02110-1335 in 2005, so the old address is now 18 years out of date.  The affected files:
- sandbox/engraving/config.h
- SetupConfigure.cmake
- share/styles/cchords_muse.xml
- share/styles/cchords_nrb.xml
- share/styles/cchords_rb.xml
- share/styles/cchords_sym.xml
- share/styles/chords_jazz.xml
- share/styles/chords_std.xml
- share/styles/chords.xml
- share/styles/jazzchords.xml
- share/styles/stdchords.xml
- src/framework/testing/gtest.cmake
- src/framework/testing/qtest.cmake
- src/framework/uicomponents/view/selectmultipledirectoriesmodel.cpp
- src/framework/uicomponents/view/selectmultipledirectoriesmodel.h
- thirdparty/rtf2html/CMakeLists.txt
- tools/bww2mxml/bww2mxml.pro
- tools/bww2mxml/mxmlwriter.h
- version.cmake

The address has been updated in the FSF's copy of both the [GNU Library General Public License, version 2.0](https://www.gnu.org/licenses/old-licenses/lgpl-2.0.html) and the [GNU Lesser General Public License, version 2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html), so I think it should be harmless to update it in your files as well.

### Steps to reproduce

N/A

### MuseScore Version

4.1.0

### Regression

No.

### Operating system

N/A

**Comment by bkunda** [comment]
@igorkorsukov @cbjeukendrup can you please advise on this one? Thank you!

**Comment by cbjeukendrup** [comment]
Yes, this is trivial; we just need to update the license text at the top of each code file. Those license headers deserve some cleanup anyway; for example `.cmake` files were not handled when we did the big cleanup a few years ago. 

Also, I think that at some point we need to update the copyright year everywhere, and replace "MuseScore BVBA" with "MuseScore Limited".

**Comment by BrownianNotion** [comment]
Hi, new contributor here, I'd be happy to help on this issue if it's still relevant! 
As I understand, it's just a matter of replacing the FSF address in the listed files? I assume the other things mentioned like copyright year and replacing "MuseScore BVBA" with "MuseScore Limited" should go under a separate issue/PR?

**Comment by cbjeukendrup** [comment]
@BrownianNotion If you could update the entire license info header, that would be great! And example of a file that has the correct header is the root `CMakeLists.txt` file.
(Of course, the type of comment needs to be different for each file type: `# ` for CMake and sh, `/* */` for cpp/qml, `<!-- -->` for xml...)
