### ISSUE TITLE
Crash after clear all measures, delete all instruments, Undo, Redo and Undo

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#18748]
### Issue type

Crash

### Steps to reproduce

1. Create score
2. Add some notes
3. Open all parts
4. Close all parts
5. Save score
6. Reopen score (instead of steps 1-6, just open [Untitled score.zip](https://github.com/musescore/MuseScore/files/12129773/Untitled.score.zip) )
8. Select all and clear measures
9. In Instrument panel, Delete all instruments
10. Undo
11. Redo
12. Undo

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/82496862-a2f0-4530-9ebd-cf56dec5d4cd

### MuseScore Version

4.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows10

**Comment by DmitryArefiev** [comment]
Could be related to #17494

**Comment by bkunda** [comment]
Bumping this one because the repro steps are very niche, and it's extremely unusual to want to delete every instrument in the score.

**Comment by DmitryArefiev** [comment]
Fixed in #21240
