### ISSUE TITLE
Switching between long lists of Effects in Mixer get sticky

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18756]
### Issue type

UI bug

### Bug description

I have a large amount of MeldaProduction Effects installed.  Moving the mouse over them quickly causes the window to do a burst (see video).

### Steps to reproduce

Move curser quickly over large list of Effects in mixer

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/e07a6080-7faa-493e-8ebd-97e0414077ef

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232021702, revision: github-musescore-musescore-dfdbbec

### Regression

No.

### Operating system

OS: macOS 11.6

**Comment by bkunda** [comment]
I can no longer reproduce.

@zacjansheski can you try it again and close this if it's resolved?

**Comment by zacjansheski** [comment]
It is fixed!
