### ISSUE TITLE
Lyrics Hyphen over two+ notes does not appear in Nightly

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18750]
### Issue type

Engraving bug

### Bug description

Lyrics Hyphen does not appear in Nightly

### Steps to reproduce

1. Add notes to a score
2. Add lyrics, then hyphens over two+ notes

### Screenshots/Screen recordings

<img width="937" alt="Screen Shot 2023-07-21 at 11 33 23 AM" src="https://github.com/musescore/MuseScore/assets/69917893/629f108c-a657-4aef-8bbd-73fcf2ffa6be">

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232020302, revision: github-musescore-musescore-1610221

### Regression

Yes, this used to work in **MuseScore 4.0.2**

### Operating system

OS: macOS 11.6

**Comment by oktophonie** [comment]
@igorkorsukov It does seem that this PR was responsible, but it's strange that this problem arises only in master, but not in 4.1.

To clarify: if we input a lyric containing hyphens, like this:
![image](https://github.com/musescore/MuseScore/assets/20604032/9fc067d2-7fab-4f07-87d9-b7c139a72063)
in 4.1, as soon as we leave editing mode, we get this, which is what we would expect:
![image](https://github.com/musescore/MuseScore/assets/20604032/5a8d2f77-49d4-401e-94d5-52d8c187eedc)
however, in master, the hyphens then disappear as described, plus the first syllable recentres itself:
![image](https://github.com/musescore/MuseScore/assets/20604032/49d84fcd-f9dc-41f5-99ca-f39e5fb0ec98)

**Comment by igorkorsukov** [comment]
I will continue my research..

**Comment by mike-spa** [comment]
The problem started with #17575
