### ISSUE TITLE
Cannot apply notehead Alt. Brevis to note

### ISSUE THREAD

**Issue by awrog** [musescore/MuseScore#18765]
### Issue type

Other

### Bug description

I can apply all kind of noteheads to a note, but not the notehead Alt. Brevis

### Steps to reproduce

1. Select notehead
2. Choose notehead Alt. Brevis. 
3. The selected notehead does not change
4. verification, select any other notehead, that works
See screenrecording below

### Screenshots/Screen recordings

![MS4-no-notehead-brevis](https://github.com/musescore/MuseScore/assets/12153667/4727f53a-b869-46c4-ba2a-3920b33709b4)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

No.

### Operating system

Windows 10 Pro 10.0.19045

**Comment by mercuree** [comment]
Is it really a bug?
It works for double whole note
![image](https://github.com/musescore/MuseScore/assets/919446/6acb4433-d47f-41a9-87e6-d017d29c4c47)

**Comment by awrog** [comment]
If you change the metre to 4/2 I could easily choose E brevis from the
palette without the need to change the note head.
I'd like to change the notehead of a whole note in a 4/4 measure into a
brevis.
A lot of baroque and renaissance vocal music has such a last note.

**Comment by DaddyLudwig** [comment]
I've seen the brevis in Vivaldi and such, but I thought it was just extending the measure into an 8/4 measure and putting a double whole note there. That's always how I've interpreted such a final brevis.

**Comment by awrog** [comment]
I could change just the one measure (via properties of the measure), but
simplest is to just change the notehead without changing the lengt of the
note. I know it can be done, but not just from this palette, so it seams.
The alt brevis gives the impression it can be done.

**Comment by MarcSabatella** [comment]
You *can* change just one note to the Alt brevis notehead - it just has to be actual breve.  This is for historical reasons relating to how this notehead ended up being being to MuseScore in the first place and how it is represented in the SMuFL standard.

It’s probably possible to revisit all that at this point.  So yes, as a feature request, it’s something that I think should be considered.  Meanwhile, though, it’s not a bug - it’s working as originally designed.  You simply need to have a breve if you want to use this alternate notehead for it.

**Comment by awrog** [comment]
Thanks Marc, this is enlightening!

**Comment by MarcSabatella** [comment]
FWIW, I'd still love to see this looked at again as a feature request, so consider rewording and reopening it.

I'm fuzzy on the details, but my sense is the design was in part based on a notion that some people might want to have all breves notated using the alt brevis notehead, and the current implementation makes this simple - just select all and apply the notehead, and it changes only the notes that it should.  This is, of course, an effective hack but terrible design.  Better to just have a style setting or some such.  Could even be modeled after the notehead customization options in the drumset editor, or whatever that looks like after the redesign.
