### ISSUE TITLE
Harp diagrams do not affect glissando playback

### ISSUE THREAD

**Issue by sdsdsggg** [musescore/MuseScore#18763]
### Issue type

General playback bug

### Bug description

when placing a harp diagram, the glissando isnt affected. even after trying every single sound type for the glissando (white keys, black keys, chromatic, diatonic, portamento) it still wont work.

### Steps to reproduce

1. create a new score with instrument: harp
2. make the tempo: Grave. (so you can hear every single not the gliss plays)
3. place a harp diagram and set it to whatever you want
4. place in 2  following bars a whole note in whatever range you'd like
5. place a gliss between those notes
6. click the play button and you will hear that the gliss is not accurate to the diagram

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

Windows 10

**Comment by oktophonie** [comment]
In progress: https://github.com/musescore/MuseScore/pull/17824
