### ISSUE TITLE
Allow independent thickness settings for slurs and ties

### ISSUE THREAD

**Issue by ghost** [musescore/MuseScore#18769]
### Your idea

A humble call to re-look at slurs and ties in MuseScore. They look too similar and are confusing, and I have had several other engravers and conductors through the years over at a Facebook page called "Music Engraving Tips", tell me the same thing. "Music Engraving Tips" is a Facebook page where many professional music publishers, engravers, conductors, and others working in the industry give advice on Music Engraving (oh, they ALL use SIbelius and Dorico and Finale...but I think I earned their respect through the years). Please see "additional content" for the feedback I got from a Finale and Sibelius user over at the before-mentioned Facebook page, whose name I will omit. 

### Problem to be solved

It would drastically improve the professional quality and image of MuseScore. I think this is one of the biggest improvements MuseScore can make and should focus on. 

### Prior art

It appears that in Sibelius and Finale slurs are slightly thicker than ties. In MuseScore 4, it looks like ties and slurs are the exact same thing. I just want to make MuseScore better, you know?

### Additional context

These are the comments on slurs and ties I received just recently from a Sibelius and Finale user whose name I will omit:

"Maybe it’s a MuseScore thing, but some of the slurs look like ties, and vice versa. It is important, especially when you have an arched line between two notes in different systems (like in the 1st violin and viola in bars 12-13, for instance), that you are immediately able to tell whether it’s a tie or a slur, because bowing depends on it. In bar 12 I’m not in doubt about the tie in the 1st violin, but in the viola it might as well be a slur. I would check your ties/slurs again to make sure they are what they are supposed to be." - Name omitted for privacy

"I think it’s because in MuseScore they carry the same line thickness, attach similarly to the notes, and slurs on stepwise movement have almost no tilt (in some cases in your score I had to zoom in very close and align the ends of the slur/tie to the edge of my screen to see that there were in fact a slight difference between the end and the beginning of the slur; I wouldn’t have been able to tell in a printed version). I work most in Finale, and there the slurs are slightly but noticeably thicker than the ties, and they attach “broader” to the notes, if that makes sense, than the ties, which are flatter, thinner and more “between” noteheads. The same seems to be the case in Sibelius." - Name omitted for privacy

**Comment by DanielParker72** [comment]
Here the score that pertains to the comments above: https://musescore.com/user/44071886/scores/11548261 .  Good evening. I love MuseScore!

**Comment by oktophonie** [comment]
I've retitled this according to what it's actually asking for. Seems perfectly reasonable.

**Comment by SteveBlower** [comment]
I wish this had been raised first in the discussion forum as this issue tracker is not really the place for discussion on the merits of suggested features.  But it wasn't and so I will weigh in here with my thoughts.

To quote from "Behind Bars": _'The slur is the same tapered arc as the tie, although the tie may have a flatter curve to allow room for slurs and to differentiate between the two'_  The important thing here is that it is not the *thickness* that differentiates, it is the *positioning*.

Of course, Behind Bars is not the only authority on engraving practice, but then neither are Sibelius or Finale or a Facebook group.  Having made a  quick scan of my library including scores by Baerenreiter, Boosey & Hawkes, Chester, Novello, Peters, Schott, OUP, UE, Wilhelm Hanson, I have found no examples that contradict Gould's guidance.   Actually, the Peters score I looked at *does* have some variation in thickness, but there is as much variation within the collection of slurs or ties as there is between slurs and ties as categories (just sloppiness I guess).

Is this difference in thickness of slurs and ties a real thing?  I would certainly take issue with the proposition that *"It would drastically improve the professional quality and image of MuseScore."*

Having said that, if some users want to not follow what seems to me to be standard practice, then of course another option could be provided (and added to the list of features that need to be maintained).

**Comment by oktophonie** [comment]
I don't agree with the basic premise of the issue, nor with the remarks made by the quoted Sibelius/Finale users, nor would I ever engrave a score where the thickness of slurs and ties were different in any significant way, but hey. Some people might want to, and if they want to contract the sacred wisdom handed down to us in _Behind Bars_ (please just stop quoting it, people), then that's up to them.

SMuFL font metadata has provision for separate thickness settings for slurs and ties, and the metadata that comes with certain fonts might make use of this to make a distinction; that seems as good as reason as any for us to at least provide the capability to do it, so that we can honour those choices in those cases, if they arise. At the moment we just read one and ignore the other.

**Comment by SteveBlower** [comment]
As I see it, it is really a matter of where limited resources are best directed - to fix things that are plain wrong or to implement and maintain features that allow quirky personal preferences.

But again, this is not really the spot for such philosophical discussions.  Perhaps if anyone wants to continue we could do so in the Musescore Git hub Discussions Forum or on Musescore.org.

**Comment by DanielParker72** [comment]
I'm still learning everyone, and I'm humble enough to own up to that...and I wouldn't want to engrave any score in MuseScore 4 that would go against modern engraving practices...so yeah, it looks like I'm wrong. So please, I think my original title is more appropriate, as upon finding out that slurs and ties carry the same thickness, and that's been the standard.. let's obviously not change it nor add a option that would go against that in any way. I just wanted to relay my experiences with sharing my scores with working professionals in the music industry and my personal engraving mentors, and in the future I will definitely go to the forums and get confirmation before posting to this forum. I love MuseScore 4, I really do, and thanks for hearing me out.

**Comment by SteveBlower** [comment]
We are all learning :-)  

Musescore has taught me a lot about engraving and it is depressing how much recently published music I am asked to play from is difficult to read. Learning about engraving has helped me understand *why* it is difficult to read - incorrectly grouped notes, poorly placed page turns, overly compressed notes, full measure rests for incomplete pick up measures, divisi sections with accidentals that are supposed to apply to both parts but which are only stated on one part, ambiguously positioned directions (does that apply to this staff or the one above?) etc.  And it is the player that gets the glares from the MD, not the engraver.  I hope that I can avoid such embarrassments in the scores I provide.
