### ISSUE TITLE
Piano key signatures: Options "" and "" are indistinguishable

### ISSUE THREAD

**Issue by BenWiederhake** [musescore/MuseScore#18776]
### Issue type

UI bug

### Bug description

When creating a new partiture, the UI offers some kind of key for the piano (it also does for some other, select instruments, where this makes sense). In addition to the piano not being bound to a particular key anyway, the two options "" and "" (emptystring and emptystring) don't seem to make sense.

### Steps to reproduce

0. This probably depends on some local config, since the exact same file on the exact same computer didn't behave like that a few days ago. However, I don't know what changed, I think I only updated unrelated packages if any :/
1. Open MuseScore 4.1.0 in a German locale
2. Create a new partiture
3. Type "Kla" ("Klavier") in the instrument search bar

### Screenshots/Screen recordings

![Bildschirmfoto_2023-07-23_21-02-41](https://github.com/musescore/MuseScore/assets/2690845/7af0ab6b-afc3-4e1d-8f82-34b4e0350126)
![Bildschirmfoto_2023-07-23_21-03-06](https://github.com/musescore/MuseScore/assets/2690845/ba78ea4e-4577-465a-8f47-b4279225e709)

### MuseScore Version

OS: Debian GNU/Linux trixie/sid, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Debian

### Additional context

The "KeySignatureListView: Binding loop detected" errors look very suspicious:

```
21:08:06.847 | WARN  | main_thread | Qt         | QQmlComponent: Created graphical object was not placed in the graphics scene.
21:08:07.485 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: file-new
21:08:07.997 | INFO  | main_thread | MultiInstancesProvider | openNewAppInstance: success start: "/tmp/.mount_MuseSc5Qdgo7/bin/mscore4portable" , args: QVariant(QStringList, ("--session-type", "start-with-new")) 
21:08:08.055 | INFO  | main_thread | GlobalModule | onPreInit: log path: /home/user/.local/share/MuseScore/MuseScore4/logs/MuseScore_230723_210808.log
21:08:08.055 | INFO  | main_thread | GlobalModule | onPreInit: === Started MuseScore 4.1.0, build number 231921359 ===
21:08:08.056 | ERROR | main_thread | LanguagesService | setCurrentLanguage: Error loading translator "/tmp/.mount_MuseSc5Qdgo7/share/mscore4portable-4.1//locale/qt_de.qm" 
21:08:08.056 | INFO  | main_thread | IpcSocket  | connect: success connected to ipc server
21:08:08.056 | INFO  | 140626662246080 | IpcServer  | listen: id: "e872db464d78445dae9682e71ae20d9e" 
21:08:08.092 | INFO  | main_thread | MultiInstancesProvider | openNewAppInstance: created new instance with ID: "e872db464d78445dae9682e71ae20d9e" 
21:08:08.126 | INFO  | main_thread | DiagnosticsModule | onInit: success start crash handler
21:08:08.134 | ERROR | main_thread | MuseSamplerLibHandler | MuseSamplerLibHandler: Unable to open MuseSampler library, path: /home/user/.local/share/MuseSampler/lib/libMuseSamplerCoreLib.so
21:08:08.134 | ERROR | main_thread | MuseSamplerResolver | checkLibrary: Incompatible MuseSampler library; ignoring
21:08:08.135 | ERROR | main_thread | MuseSamplerLibHandler | MuseSamplerLibHandler: Unable to open MuseSampler library, path: libMuseSamplerCoreLib.so
21:08:08.135 | ERROR | main_thread | MuseSamplerResolver | checkLibrary: Incompatible MuseSampler library; ignoring
21:08:08.139 | WARN  | main_thread | AbstractCloudService | readTokens: Could not find the tokens file: /home/user/.local/share/MuseScore/MuseScore4/musescorecom_cred.dat
21:08:08.139 | WARN  | main_thread | AbstractCloudService | readTokens: Could not find the tokens file: /home/user/.local/share/MuseScore/MuseScore4/audiocom_cred.dat
21:08:08.649 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.649 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.649 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.649 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.650 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.650 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.650 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.650 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.651 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.651 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.651 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.651 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.652 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.652 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.652 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.652 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.653 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:08.653 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:174:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
21:08:09.254 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: file-new
21:08:09.279 | ERROR | main_thread | App        | run: error: qrc:/qml/MuseScore/Project/internal/NewScore/KeySignatureSettings.qml:116:13: QML KeySignatureListView: Binding loop detected for property "rows"
21:08:09.279 | WARN  | main_thread | Qt         | qrc:/qml/MuseScore/Project/internal/NewScore/KeySignatureSettings.qml:116:13: QML KeySignatureListView: Binding loop detected for property "rows"
```

I think MuseScore 4.0.2 didn't have any kind of key signature selection, and this UI element is new (and broken) in 4.1.0.

**Comment by shoogle** [comment]
This is a problem with the German translation. When the UI is set to English, these instruments are called "Piano" and "Upright piano", and they appear separately in the UI. However, in German they have both been translated as "Klavier", so they appear as one instrument.

To confirm:

1. Set UI language to German and restart MuseScore.
2. Create a score with both "Klavier" instruments and save.
4. Set UI language to English and restart MuseScore.
5. Open the score, right-click on each "Klavier" staff and open **Staff/part properties**.

Instrument 1 | Instrument 2
---|---
![image](https://github.com/musescore/MuseScore/assets/11011881/8259107b-a4e1-4188-a7bb-707680844d59) | ![image](https://github.com/musescore/MuseScore/assets/11011881/2ee2a722-f2f4-40ee-81f9-d3e30a592077)

@Jojo-Schmitz, please could you fix this in the translation?

To catch this in future, I  might be able to create an automated test that would spot duplicate names in translations for instruments that have unique names in English.

**Comment by Jojo-Schmitz** [comment]
I'll fix the German translation

**Comment by Jojo-Schmitz** [comment]
Not sure there's a problem, "Grand Piano" is translated as "Flügel", "Upright Piano" as "Klavier", plain "Piano" as "Klavier"

**Comment by shoogle** [comment]
> "Upright Piano" as "Klavier", plain "Piano" as "Klavier"

There's the problem. You need to add the German word for "upright", or whatever you would call that instrument in German.

If you don't want the word "upright" to appear in the score then you can do it like this:

- Track name: "Piano (upright)"
- Long name: "Piano"

But in German.

**Comment by Jojo-Schmitz** [comment]
Upright Piano is Klavier. As well normally as the generic Piano. Only the Grand Piano is Flügel. Theres no other terms available.
Only option would be to translate the generic Piano as Piano, but IMHO that wouldn't be right.

**Comment by shoogle** [comment]
You could translate the track name for "Piano" as "Piano (generic)"?

**Comment by shoogle** [comment]
Or "Piano" could be "Flügel" and "Grand Piano" could be "Konzertflügel"?

**Comment by mmeyn** [comment]
> Or "Piano" could be "Flügel" and "Grand Piano" could be "Konzertflügel"?

No, that would be simply wrong. The generic term is “Klavier”, “Flügel” is only for grand piano. “Konzertflügel” would translate as “concert grand” or “concert grand piano” and refers to a long grand piano like the Steinway D-274 or the Bösendorfer Imperial (there are slightly smaller “Konzertflügel” too).

As Jojo-Schmitz said, there is no special term for upright piano that is *commonly* used. There is however the term “Pianino” for an upright piano that is very rarely heard. You can find it f. e. in Alban Bergs Wozzeck (there is a “Pianino” = upright piano on the stage).

**Comment by MarcSabatella** [comment]
The term "upright piano" is very common in the US at least, which covers any vertically-strung piano, including consoles and spinets.  "Pianino" I've never heard of and have no idea what it might refer to.

It's kind of silly to have "upright piano" listed as a separate instrument, though.  The instrument is normally just "piano" - published scores rarely make a distinction.  I suspect the reason we have separate entries for upright vs grand in the instrument list is to get the right default sound.  I guess that's a good reason, but maybe we think about whether there is a better way to handle this.

Something like "Piano (grand)" and "Piano (upright)" in the instrument list makes sense to me, with both simply displaying as "Piano" in the score.  I wouldn't see a need for a separate "Piano" but I suppose it's harmless enough in English.  If it causes problems in German though, I am happy to see it go away.

**Comment by shoogle** [comment]
Perhaps we should rethink how the pianos are classified in English, but the earliest that will happen is MuseScore 4.2. Right now, the issue with the indistinguishable Klavier instruments in German needs to be fixed in the German translation, preferably in the next day or two before we release MuseScore 4.1.1.

In German, the instrument track names could be changed to:

Klavier (generisch)
Klavier (aufrecht)

Or anything else as long as they are different. If one is changed the other can remain just "Klavier".

**Comment by Jojo-Schmitz** [comment]
I changed Upright Piano to Pianino
Leaves.the other 2

**Comment by shoogle** [comment]
@Jojo-Schmitz, thanks. I notice you changed both the `trackName` and the `longName`, so it will appear as "Pianino" in the score as well as in the Instruments dialog. However, the `shortName` is still "Klav." so you'll need to update that too for consistency otherwise it will look strange on subsequent systems.

**Comment by Jojo-Schmitz** [comment]
Ah, yes, I forgot those

**Comment by Jojo-Schmitz** [comment]
Changed trackname to Klavier/Piano and longname back to Klavier

**Comment by Jojo-Schmitz** [comment]
Also changed the tracknames (and only those) of Drumsets to Schlagzeug and Reed Organ to Harmonium/Reed Organ

**Comment by Jojo-Schmitz** [comment]
Using Transifex on a mobile phone is a royal pain...

**Comment by Jojo-Schmitz** [comment]
Now Reed Organ to Saugwind Harmonium

**Comment by shoogle** [comment]
> I changed trackname to Klavier/Piano and longname back to Klavier

Thanks, I think that is best. We don't want to alter the name in the score just to fix a UI bug.
