### ISSUE TITLE
Horns A6 when playing eighth notes is staccato even when slurred

### ISSUE THREAD

**Issue by AZEntertainment** [musescore/MuseScore#18771]
### Issue type

Muse Sounds bug

### Bug description

If you go to Horns A6 in Muse sounds and enter eight notes in a medium bpm (like 100 bpm) it plays as staccato even when slurred or in tenuto. This was an issue since Musescore 4 beta was released. To reproduce, use Horns A6 and set the bpm to a medium tempo preferably 100. Then enter eight notes, it plays as staccato.

### Steps to reproduce

1. Open Musescore
2. Create new score
3. Add new instrument and pick "Horn in F"
4. Open the mixer
5. Change the instrument to Muse sounds "Horns A6" in Muse Brass
6. Set the tempo to 100
7. Enter eight notes
8. Playback and it will not be slurred even if you slur it or add Tenuto.

### MuseScore Version

4.1.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11 Pro 22H2 Build 22621.1992

### Additional context

[Example.zip](https://github.com/musescore/MuseScore/files/12138079/Example.zip)
https://musescore.org/en/node/352538

**Comment by Valdessir** [comment]
I think this is fixed now with the recent versions of Musebrass.

**Comment by LucySuccubus** [comment]
Can confirm this is fixed with the current version of Musesounds. eighth notes can now play legato when a slur is added effective to virtually all Musebrass instruments.

**Comment by zacjansheski** [comment]
Closing per comment above
