### ISSUE TITLE
 feature request about putting note durations in musescore

### ISSUE THREAD

**Issue by alireza1385mamani** [musescore/MuseScore#18781]
### Your idea

I like to be able to change the tension of a note without erasing it and retyping it.

### Problem to be solved

It solves a problem about putting note durations with keyboard in musiscore 4

### Prior art

Actually, when I was using sibalius I could change the duration of the note without retyping it by using the same keyboard shortcuts that we have in here.

### Additional context

I think it would be way faster. thanks.

**Comment by sammik** [comment]
It is possible. Select note, and click number.

It is not possible in note input mode, as in note input mode it changes duration of note to be written.

**Comment by MarcSabatella** [comment]
And to be clear, in normal mode, you don't need to pysically click the duration button - the keyboard works just as well.  In note input mode, use Shift+Q/W to decrease/increase duration.

So definitely, already possible.  In the future, please use the official support forum on musescore.org when asking for help using MuseScore.

**Comment by alireza1385mamani** [comment]
Ok. Thanks

**Comment by worldwideweary** [comment]
Aside: Interesting that `Shift+Q/W` takes into consideration the current toggle state. So for example, `Q/W` which doubles/halves the toggle state (not just the currently selected note/rest duration of the score) *will* affect the result of a `Shift+Q/W` while applying changes within Note-Entry. Could be advantageous if harnessed properly...
