### ISSUE TITLE
Lines and Text lines in palettes are not well centered within their cell

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#18787]
Text lines in the Palettes are not centered very nicely in their cells. Ottava lines are the most problematic, but some others are not ideal either. This is only the case on the master branch, and not in 4.1.x; however, before it was as broken as it is now, it was not perfect either.

### Screenshots
master:
<img width="302" alt="Scherm­afbeelding 2023-07-24 om 20 55 31" src="https://github.com/musescore/MuseScore/assets/48658420/35fc2b3b-eea8-4dac-98dc-de9037f3ab5b">

4.1.x and older: 
<img width="302" alt="Scherm­afbeelding 2023-07-24 om 20 56 06" src="https://github.com/musescore/MuseScore/assets/48658420/cbb976af-36df-4536-8d28-9640f981d497">

### Additional context
Probably related to recent palette layout refactoring

**Comment by SiboVG** [comment]
Hey, could I work on this?

**Comment by cbjeukendrup** [comment]
Yes, welcome!
