### ISSUE TITLE
Zooming out and switching to publish tab causes a crash most of the time

### ISSUE THREAD

**Issue by Attackoh** [musescore/MuseScore#18791]
### Issue type

Crash or freeze

### Bug description

See title

### Steps to reproduce

1. Zoom out until it is at 5%
2. Switch to publish from score or vice versa
3. Crash?

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/120669196/ee2c9ab9-d358-4565-ab86-83dbfd97aec0

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

Windows 10

**Comment by worldwideweary** [comment]
_While I'm up_, figured_ I'd check and shutdown did not occur when following the formula : 4.1 (not 4.1.1).
Albeit a little *gummy* feeling, there was no crash. Maybe it was score specific? 


https://github.com/musescore/MuseScore/assets/7139517/85f5ebdd-8a1f-4ce4-a95c-3c01f2eaf148

**Comment by Attackoh** [comment]
Doesn't seem score specific on my end. The crash doesn't always trigger for me.

**Comment by zacjansheski** [comment]
Perhaps sharing a score in which this happens would help us reproduce.  I have not been able to reproduce this yet.

**Comment by zacjansheski** [comment]
Closing, not reproducible
