### ISSUE TITLE
Crash after adding thirds on tied notes

### ISSUE THREAD

**Issue by MichLeon** [musescore/MuseScore#18796]
### Issue type

Crash or freeze

### Steps to reproduce

In attached score:
1 Select all
2 Press Alt + 3 to create thirds
3 Undo
4 Press Alt + 3 again.
Crash

Image shows loose ties after first Alt+3.
First report on https://musescore.org/en/node/352714

### Screenshots/Screen recordings

[See comment ](https://github.com/musescore/MuseScore/issues/18796#issuecomment-1649396831)

### MuseScore Version

MU: 4.1.0-231921402, rev: 2e3a93a - MU:: 4.1.1-232050501, rev: dfdbbec  - MU: 4.2.0-232050502, rev: 9be710d

### Regression

Yes, this used to work in **4.0.2**

### Operating system

Windows 11

### Additional context

[Crash_after_adding_thirds.zip](https://github.com/musescore/MuseScore/files/12157754/Crash_after_adding_thirds.zip)
![After_Alt+3](https://github.com/musescore/MuseScore/assets/102731553/40cfd42e-bb70-447e-a167-cec6d86be646)
 Win 11 AMD Ryzen 9 5900X 12 (x2) -Core Processor - AMD RAdeon RX 6700 XT

--------

Related to #16636

**Comment by MichLeon** [comment]
Originslly posted on https://musescore.org/en/node/352714

**Comment by DmitryArefiev** [comment]
There are two issues here that appeared in **4.1.0**: broken tie and crash. Occurs not only with thirds.

Easy to reproduce with cases like that:


https://github.com/musescore/MuseScore/assets/90187801/83eeec3f-bbed-47ef-9195-f5baf0db2ce4

----------------------

Also, I found that on some scores the crash occurs right after adding thirds on whole score (also doesn't occur in **4.0.2**)
1. Open [Smoke test 15.zip](https://github.com/musescore/MuseScore/files/12159002/Smoke.test.15.zip) or 
[starwars_basic.zip](https://github.com/musescore/MuseScore/files/12159005/starwars_basic.zip)
2. Ctrl+A
3. Alt+3

https://github.com/musescore/MuseScore/assets/90187801/8b1c0149-dce2-4066-b21a-573c573f3373

**Comment by Tantacrul** [comment]
I can replicate the broken tie on MacOS but not the crash. Must be a Windows thing?

<img width="496" alt="image" src="https://github.com/musescore/MuseScore/assets/21022311/8bc1b868-7458-4eff-a551-55493446fb38">

**Comment by DmitryArefiev** [comment]
Some weird things with this bug..

On Mac, I reverted factory settings and got the result you have (no crash)
Restarted MS, now I get the crash again

**Comment by cbjeukendrup** [comment]
See also #17256 and my comment there at the bottom; that PR might have a solution.

**Comment by DmitryArefiev** [comment]
Fixed in #18799
