### ISSUE TITLE
System brackets messed up in horizontal continuous view

### ISSUE THREAD

**Issue by mmeyn** [musescore/MuseScore#18798]
### Issue type

Engraving bug

### Bug description

In the attached score the system brackets are messed up when I change to horizontal continuous view: some bracket tips are inverted, some brackets span the wrong systems. Vertical continuous and page view are fine.

I tried, without success, to reproduce this problem with a newly created score.

### Steps to reproduce

1. Rename the attached file (.zip → .mscz) and open it.
2. Look at the score in horizontal continuous view.
[Brackets_continuous_view.zip](https://github.com/musescore/MuseScore/files/12158915/Brackets_continuous_view.zip)

### Screenshots/Screen recordings

horizontal continuous:
![horizontal_continuous](https://github.com/musescore/MuseScore/assets/7814361/0bb78d84-20be-4d33-a52f-cd1cded3f056)

vertical continuous:
![vertical_continuous](https://github.com/musescore/MuseScore/assets/7814361/8cc367da-3d2f-42f3-9ccd-cac23f83a58e)

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

OS: Manjaro Linux, Arch.: x86_64

**Comment by mmeyn** [comment]
I’m sorry, I obviously sent that before the file upload (21 KB score and 70 KB screenshot) was complete. It seems like the upload is currently not working. I’ll try again later.

**Comment by mmeyn** [comment]
Changed the WIFI network and uploaded the screenshots and score file.

**Comment by zacjansheski** [comment]
This is pretty interesting.  Brackets get this way from showing and hiding instruments.  I can reproduce by hiding/showing instruments at the ends of the brackets

https://github.com/musescore/MuseScore/assets/69917893/00faa36a-bd16-42a8-ab92-2226b6ccd340

**Comment by zacjansheski** [comment]
Here is the score I used to reproduce.
1. Open Score
2. Go to continuous view
3. Hide Violin I, Violoncello, Piccolo, and Bassoon
4. Show Violoncello and Piccolo

[BracketTest.mscz.zip](https://github.com/musescore/MuseScore/files/12162442/BracketTest.mscz.zip)

**Comment by zacjansheski** [comment]
In your score, there are many invisible instruments, but the main source of the weirdness is caused by the invisible tuba (bottom of the second bracket

https://github.com/musescore/MuseScore/assets/69917893/7e11e7d6-bcc3-4e6d-afa0-c60b51e5c58c

**Comment by mmeyn** [comment]
May I try this?

What I found out so far:
- src/engraving/rendering/dev/systemlayout.cpp line 1968 and 1973: `show()` is always true for staves in horizontal continuous view.
- I suppose this is because for horizontal view `ScoreLayout::collectLinearSystem` is called instead of `SystemLayout::collectSystem` this doesn’t call `SystemLayout::hideEmptyStaves`.
- Calling `hideEmptyStaves(system, ctx, true)` in `ScoreLayout::collectLinearSystem` (after making it public for testing purposes) “fixes” the issue.

What’ I haven’t found out yet:
- Which parts of the `hideEmptyStaves` code are needed to fix this issue. I think one would only want to hide staves (empty or not) that are hidden by the user in the instruments panel but I don’t know yet how that translates to code.

**Comment by cbjeukendrup** [comment]
There is `Staff::show()` and `SysStaff::show()`; `Staff` represents the staff in the whole score, and is affected by the settings in the instruments panel, while `SysStaff` represents a staff in a system, and is affected by the layout calculations.

**Comment by mmeyn** [comment]
> What I haven’t found out yet:
> 
>    * Which parts of the `hideEmptyStaves` code are needed to fix this issue. I think one would only want to hide staves (empty or not) that are hidden by the user in the instruments panel but I don’t know yet how that translates to code.

After reading and understand what this does (see also [this thread](https://musescore.org/en/node/353409)) I think everything is needed.

> What I found out so far:
>
>    * […]
>    * Calling `hideEmptyStaves(system, ctx, true)` in `ScoreLayout::collectLinearSystem` (after making it public for testing purposes) “fixes” the issue.

This would be a very simple fix which has only one problem: that method is `private`. Possible fixes:
1. make it `public`
2. move it to another place where both `SystemLayout` and `ScoreLayout` can access it
3. make `friend`s

As I’m new to the MuseScore code and have never used `friend` (I grepped for it and saw that it is used in some places) I’d need help with option 2. or 3.

**Comment by cbjeukendrup** [comment]
@mmeyn Sorry for the ultra late reply (I thought I had already replied, but apparently not).

I think it's fine to make the method public, since there are more methods in SystemLayout that are public and used in ScoreLayout. 

But I had another thought about the desired behaviour: in continuous view, I think only staves that are explicitly hidden by the user should be hidden. Even when "hide empty staves" is enabled and a staff is empty, I think it should still appear in (horizontal) continuous view. This way, the user can use continuous view to enter notes on those staves, without having to disable and re-enable "hide empty staves".

**Comment by mmeyn** [comment]
> @mmeyn Sorry for the ultra late reply (I thought I had already replied, but apparently not).

No problem, I had neither my computer with me nor internet access the past ~10 days and there would have been enough other issues I could have tried to resolve meanwhile ;)

> I think it's fine to make the method public, since there are more methods in SystemLayout that are public and used in ScoreLayout.

OK, thanks for that hint.

> But I had another thought about the desired behaviour: in continuous view, I think only staves that are explicitly hidden by the user (via the Instruments panel) should be hidden. Even when "hide empty staves" is enabled and a staff is empty, I think it should still appear in (horizontal) continuous view. This way, the user can use continuous view to enter notes on those staves, without having to disable and re-enable "hide empty staves".

This was my first thought too. Then I felt like this would be an unnecessary limitation of the user’s possibilities. Other arguments for just using `hideEmptyStaves(system, ctx, true)`:
1. When using MuseScore’s default settings, nothing is hidden, because the horizontal continuous view is treated like the first system (that’s the `true` in the call). The user would have to set “hide empty staves in the first system”.
2. Copying large parts of that method might be a source for errors in the present and also in the future when something is changed.
