### ISSUE TITLE
CPU Spikes/delays when selecting notes/articulations/etc. while Muse Sounds is selected as the active playback profile in large scores

### ISSUE THREAD

**Issue by CerealSSBU** [musescore/MuseScore#18803]
### Issue type

Muse Sounds bug

### Steps to reproduce

1. Have a large project. (For example: fill all parts in the Symphony orchestra preset with 256 measures of A4 quarter notes)
2. Put accents or staccatos on all notes.
3. Switch the active playback profile to Muse Sounds.
4. Select various notes/articulations/etc and watch your CPU suffer.
5. Switch to MuseScore Basic.
6. Select various notes/articulation/etc and observe normal operating conditions.

### Screenshots/Screen recordings

[see comment](https://github.com/musescore/MuseScore/issues/18803#issuecomment-1708249943)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

No.

### Operating system

Windows 10

**Comment by iainhallam** [comment]
I seem to be hitting similar CPU spikes with a 188-bar score in 11 staves, but only (at present) in the continuous (horizontal) score view - things are much better in page view. Perhaps if I had a larger score I'd see it in page view as well. Changing playback profile to Muse Basic sorts out the issue immediately.
