### ISSUE TITLE
Re-implementation of the 'Style' option in context menu from MU3

### ISSUE THREAD

**Issue by ShibuyaCyana** [musescore/MuseScore#18837]
### Your idea

![style button](https://github.com/musescore/MuseScore/assets/39703247/064362a9-7dde-47f6-b07d-9338b26a978b) ![nothing in MU4](https://github.com/musescore/MuseScore/assets/39703247/652483c0-7067-4f6f-a6cd-f06f301576be)

There was a style option in right click context menu in MU3, but it was removed in MU4; yes I can still save and load styles, but this one is still helpful when creating a style or temporary changing something, or I'll have to dig through a long and random style list without search function to find the entry I need.
It _is_ a little confusing with the _properties_ tab, but still useful sometime, especially for text styles. maybe we can move everything in the style list to _properties_ tab? is this already in a todo list?

### Problem to be solved

See idea section above

**Comment by kir12** [comment]
So an interesting addendum to this issue -- if you right click on the page for the score itself (i.e. not on any specific elements) a `Style...` option will appear, at which point clicking it will bring up the Style menu. (Behavior analogous to how it was in MuseScore 3).
![image](https://github.com/musescore/MuseScore/assets/11183158/7c93ea47-f9fa-4723-a61f-61340da5825a)

Besides that, I've been interested in having a hand at this issue but am having difficulty determining what part of the codebase handles right click user inputs (in particular those that pertain to right clicking within the notes); my idea being that once that location is determined I can get a better sense of what change I need to make. Common intuition suggests that one of the C++ files in `src/notation/internal` may handle right click inputs to draw up the correct QWidget as specified by one of the QML files in `src/notation/qml/MuseScore/NotationScene` but that's all I was able to figure out so far. Could someone guide me in a helpful direction to go?

**Comment by cbjeukendrup** [comment]
The notation view is mainly defined in `src/notation/qml/MuseScore/NotationScene/NotationView.qml`. There, you will find an instance of `NotationContextMenuModel`. This class is implemented in C++, see `src/notation/internal/notationcontextmenumodel.{h,cpp}`.
(For the sake of completeness, I should also mention `AbstractNotationPaintView`, which is the C++ class where the actual painting of the notation view happens, and the input handling too, although that's mostly delegated to NotationViewInputController.)

**Comment by mathesoncalum** [comment]
Hey @kir12 - are you working on this right now? I think I can get this squared away reasonably quickly if not.
