### ISSUE TITLE
Guitar tablature: Can't change string with 8va symbol

### ISSUE THREAD

**Issue by ShibuyaCyana** [musescore/MuseScore#18834]
### Issue type

Other type of issue

### Steps to reproduce

1. add a guitar staff and linked tablature staff
2. write some notes and put a 8va line above them
3. try to change string and it doesn't work

### Screenshots/Screen recordings

![guitar 8va](https://github.com/musescore/MuseScore/assets/39703247/86990d28-55a5-43d3-8743-433474053ab5)

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11 22H2

### Additional context

It's not really working in MS3, in which adding a 8va line won't change the fret number

**Comment by zacjansheski** [comment]
Thank you for reporting.  This is a known issue https://github.com/musescore/MuseScore/issues/14218

I will close this and refer to that (more examples there)

**Comment by ShibuyaCyana** [comment]
OK, I did some search but didn't hit that one, I'll follow it instead.
