### ISSUE TITLE
Sustained notes are not re-attacked when notated in different staves of the same instrument.

### ISSUE THREAD

**Issue by bleistift-zwei** [musescore/MuseScore#18846]
### Issue type

Muse Sounds bug

### Bug description

Take this excerpt for example:
![grafik](https://github.com/musescore/MuseScore/assets/60063716/8ec08080-65e5-462c-a692-03f885e68bfe)

Note that the left hand in measure 1 contains an _a_ which is repeated on beat 3 in the right hand.

During playback I expected the _a_ to sound twice, once in the chord and once when it’s played individually in the right hand. This is how it’s played back by MS Basic.

When playing back the score with Muse Sounds, the _a_ in the right hand is not played.

### Steps to reproduce

1. Open the attached score.
2. Use MuseSounds as the soundfont.
3. Play back.
[skipped-note-repro.zip](https://github.com/musescore/MuseScore/files/12209039/skipped-note-repro.zip)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/60063716/ab31a08b-4cc5-4b6d-a75f-4bee0a4c1488

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10 Home N; Version: 22H2; Build: 19045.3208

### Additional context

The issue surfaces differently when the second measure is missing. Then the right-hand _a_ is played, but delayed, as if it waited for the chord to stop playing.

**Comment by DaddyLudwig** [comment]
I also have problems in this regard, especially in Bach keyboard works, cause Bach has this note overlap between the hands a lot.
