### ISSUE TITLE
Text: More section closes when you click on a different text item

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18844]
### Issue type

UI bug

### Bug description

If you click on a text item then open the **Text: More** subpanel (**Properties** panel), the subpanel closes when you click on another text item. 

Surely, the subpanel should stay open until _the user decides_ to close it. 

### Steps to reproduce

1. Open the attached score. 
[text_more.zip](https://github.com/musescore/MuseScore/files/12208000/text_more.zip)

2. Click on a right-hand guitar fingering in the score, for example (p, i, m, a)
3. Click on the Properties panel > Text > More button.
4. Now click on another rh guitar fingering in the score.

ACTUAL RESULT: The More "subpanel" closes
EXPECTED RESULT: The "More" subpanel should stay open unti the user decides to close it.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Don't know.

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by rgreen5** [comment]
If you carry out the instructions in the OP, but using the **Appearance** subpanel instead, the panel stays open throughout. This is as expected, and the **More** subpanel should behave similarly.

**Comment by zacjansheski** [comment]
https://github.com/musescore/MuseScore/assets/69917893/b449db3f-e806-4303-8a34-cc25718e07d9

**Comment by avvvvve** [comment]
This seems to be resolved in 4.4.2 when selecting between elements of the same type. It's still a problem when clicking between two different text types, but that issue is logged separately/more generally in https://github.com/musescore/MuseScore/issues/18770 so I'm closing this as completed.
