### ISSUE TITLE
Bass drum and Snare drum went missing

### ISSUE THREAD

**Issue by JustTheEMailGuy** [musescore/MuseScore#18851]
### Issue type

Other type of issue

### Bug description

It just started recently, I haven't had this problwm before 4.1 or at least haven't noticed it
Usualy when I click on "untuned percussion" I see the bass drum and snare drum (which if I remember correctly had been called "concert snare drum" and "concert base drum")
After this update I see "small drum" and "big drum" instead. After searching for the snare drum in various ways, I actualy found "snare drum", I didn't find the bass drum, but I did find "bass drums".
Happy with the replacement I opend up my sheet music and see that these are totally different instruments with multiple lines and mutliple types of hitting the drums. These don't work with the "bass drum" and "snare drum" of musescounds.
Now I'm sad :(

### Steps to reproduce

1. click on new sheet music in musescore
2. go to untuned perscussion instruments
3. be sad that it isn't there anymore/3. See that it's for some reason only my problem

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
They are present for me.  It could the same glitch in the translations that resulted in Vocals / Altos showing a "A. Bu." until updating translations.  Go to Edit / Preferences and click the button to update your translations and see if that fixes it (restart will be required).

**Comment by JustTheEMailGuy** [comment]
@MarcSabatella, intrestlingly, updating the the translation and restarting did not seem to change anything, but your reply did help!
I'm using the german translation and it is indeed a translation problem, updating just didn't fix it.
The "big drum" ("Große Trommel") is actualy the "bass drum". The "small drum" ("Kleine Trommel") is actualy the "snare drum".
Thanks for helping!

**Comment by shoogle** [comment]
@Jojo-Schmitz, see above.

@JustTheEMailGuy, is Muse Sounds working as you expect with these instruments?

**Comment by JustTheEMailGuy** [comment]
@shoogle, yes they do!
They work just like the musescore bass drum and snare drum should.
But now it's just labelled weirdly.
![PXL_20230731_223008172](https://github.com/musescore/MuseScore/assets/127684945/427a337e-93c6-46d1-94c6-146a20fdb1a2)

**Comment by Jojo-Schmitz** [comment]
"Große Trommel" is the translation for "Concert Bass Drum", `trackName` and `longName`.
Different from a drumeset's "Bass Drum", as far as I can tell?
Simular for "Kleine Trommel" and "Concert Snare Drum".

But indeed there seem to be no non-concert bass drum.

There are "Bass drums" though (plural?!?), and there is "Snare drum" (Singular), but both for/from Marching percussions?

Not sure how to resolve this?

**Comment by shoogle** [comment]
In English US and UK we have "Bass Drums" (plural) and "Concert Bass Drum" (singular). Here's how they look in the score:
![image](https://github.com/musescore/MuseScore/assets/11011881/cf4bdf88-7e20-434a-91bc-8edcf3e4a31b)

It looks like the top one is more than one drum, hence the plural I guess.

It's the same with the "Tenor Drums" (plural), though in this case there is no concert variant.
![image](https://github.com/musescore/MuseScore/assets/11011881/7d94e39b-7149-4435-9ceb-692e874e1e0a)

On the other hand, we have the "Snare Drum", "Concert Snare Drum" and "Piccolo Snare" (all singular):
![image](https://github.com/musescore/MuseScore/assets/11011881/56476b00-7b98-4112-87a9-f6175c82bb30)

@oktophonie, are these all as you would expect? Should the top snare drum be plural, perhaps?

**Comment by Jojo-Schmitz** [comment]
OK, I changed the `trakename`s to "Konzert Basstrommel" and "Konzert Snare Drum"

**Comment by shoogle** [comment]
@zacjansheski, that seems sensible to me. We would only do it in the UI of course. In the score you wouldn't see either "concert" or "marching".

@oktophonie, what do you think to that and also the comment above re. "snare drum" (singular) vs. "snare drums" (plural)?
