### ISSUE TITLE
Tied notes and trill's major/minor doesn't work properly (Ms Basic)

### ISSUE THREAD

**Issue by orkuun** [musescore/MuseScore#18868]
### Issue type

General playback bug

### Bug description

When using MS Basic sounds, if the trill note lengthens with a tie to the other measure, the trill's major/minor ' feature does not work properly.

### Steps to reproduce

if you can watch the video i tried to show it there

### Screenshots/Screen recordings

https://youtu.be/vxxezOi3RKk

### MuseScore Version

MuseScore 4.1.1

### Regression

I don't know

### Operating system

Linux Mint 21, Windows 10

**Comment by wizofaus** [comment]
Has anybody started working on this? If not, I can have a look.

**Comment by cbjeukendrup** [comment]
@wizofaus I think this one is still free!

**Comment by wizofaus** [comment]
Can't reproduce with latest master. Is it possible to attach a score (or a section thereof) @orkuun?

**Comment by wizofaus** [comment]
Happens with or without tie, and I wouldn't expect it in *either* case actually!

**Comment by wizofaus** [comment]
Note that there were technically two separate fixes - one to ensure that when playback is determined on a note-by-note basis that any trill spanners attached to previous notes but extending over the current one are honoured correctly, and the other to ensure that when modifying trill properties (including undo/redo), that the "update range" over which playback data has to be regenerated covers the whole length of the trill (vs just the note it starts on).
