### ISSUE TITLE
Turning Solo on/off while playing causes rest of score to be out of sync

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18865]
### Issue type

General playback bug

### Bug description

While playing,  pressing the solo button causes the rest of the score to pause.  When turning the solo button off, the rest of the score starts to play out of sync.

This is in the current master, not in 4.1.1

### Steps to reproduce

1. Play a score
2. Turn on solo for an instrument, let it play for a while
3. Turn off solo, playback will be out of sync

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/7761a84c-3b0e-4cd1-aab2-9ff65be73ca8

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232130307, revision: github-musescore-musescore-e686e1c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

All

**Comment by zacjansheski** [comment]
Likely caused by: https://github.com/musescore/MuseScore/pull/18827

**Comment by zacjansheski** [comment]
Probably the same issue, metronome has similar behavior currently
https://github.com/musescore/MuseScore/assets/69917893/13033660-04c3-4232-87b0-dc046a684c42

**Comment by adazem009** [comment]
@RomanPudashkin I wasn't sure if my fix was good because I didn't know whether the process() method should be called when a channel is muted. And it seems it must be called.
What about passing a `bool muted` parameter to the method? That would require changes to multiple interfaces with the process() method though.

**Comment by RomanPudashkin** [comment]
> What about passing a `bool muted` parameter to the method? That would require changes to multiple interfaces with the process() method though.

Unfortunately, this doesn't look like a very elegant solution. Too many things in the audio subsystem depend on this method.  I'll think later about how to apply this type of optimization
