### ISSUE TITLE
Muse Sounds Oboe playing C a semi-tone low

### ISSUE THREAD

**Issue by majenkotech** [musescore/MuseScore#18869]
### Issue type

Muse Sounds bug

### Bug description

The Oboe is playing middle C a semi-tone low, at least when in a decending scale. Take the following one-bar score with both flute and oboe playing the same three notes:

[BadOboe.zip](https://github.com/musescore/MuseScore/files/12231830/BadOboe.zip)

That's a simple E-Db-C run.  The Oboe sounds the last note lower than the flute - about a semitone:

https://github.com/musescore/MuseScore/assets/3812892/e2b16c0e-4462-492e-8ccf-c9dc27d17f7d

### Steps to reproduce

Load and play the attached score

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10

**Comment by mmeyn** [comment]
This seems to be the same issue as #17603

**Comment by DavidJohnKelly** [comment]
Still having this issue

**Comment by cbjeukendrup** [comment]
Indeed, https://github.com/musescore/MuseScore/issues/17603 is still open, so no need to comment
