### ISSUE TITLE
Impossible to directly select a text element if it coincides with a break symbol; Ctrl+click doesn't work

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18862]
### Issue type

UI bug

### Bug description

It is not possible to directly select a text element by clicking on it if it coincides with a system/section/page break.

### Steps to reproduce

1. Open the attached file. 
[overlapping_elements.zip](https://github.com/musescore/MuseScore/files/12227447/overlapping_elements.zip)
2. Try to click on the last RH guitar fingering on system 1, the one that coincides with the system break.
RESULT: The system break is selected instead
3. Use Ctrl+click to try to shift the selection on to the fingering
RESULT: It does not work; Ctrl+click simply causes the selection of the system break to alternate ON and OFF.

In fact. Ctrl+Click does not seem to work at all, though it is described in the handbook – see [Overlapping elements](https://musescore.org/en/handbook/4/selecting-elements#Overlapping_elements).

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by MarcSabatella** [comment]
Ctrl+click being broken is reported separately as https://github.com/musescore/MuseScore/issues/10225
