### ISSUE TITLE
Audio export randomly skipping notes at 48000Hz

### ISSUE THREAD

**Issue by majenkotech** [musescore/MuseScore#18875]
### Issue type

Muse Sounds bug

### Bug description

When exporting as WAV (or MP3 for that matter) randomly (yet predictably within a score) notes will be omitted from the export. These notes sound normally when playing the score, it's only during export that they are missing.

This score, which uses the MuseSounds Harpsichord instrument, demonstrates the problem. Load it and play it and it plays fine.

[SkippedNotes.zip](https://github.com/musescore/MuseScore/files/12233913/SkippedNotes.zip)

But when exporting it skips a couple of notes. This phrase was copied from another score which the same problem but with different notes - when copying and pasting the notes that were skipped in export changed, so it's shouldn't be something associated with the notes themselves, but where they are in the score?

This is the export:

https://github.com/musescore/MuseScore/assets/3812892/ef9f6645-692a-4b02-94c8-5518e1771003

### Steps to reproduce

Load the file and export it as WAV.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

Note that this is not just limited to Harpsichord, it does it with other instruments as well.

I'm also seeing HEAD on Linux behave in exactly the same way - same notes skipped and everything.

**Comment by zacjansheski** [comment]
I am unable to reproduce this, are you making any adjustments to sample rate?

**Comment by majenkotech** [comment]
Nope, everything is default, and it does it for both MP3 and WAV, and on different computers and operating systems.

**Comment by zacjansheski** [comment]
Interesting, I have tried on 3 devices: Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11

Could it be specific to Windows 10?

**Comment by majenkotech** [comment]
If it was I wouldn't expect to see it happen on Linux (Arch)....

**Comment by majenkotech** [comment]
If it helps, here's the full score where I first noticed the problem. The cut-down version above is a copy-and-paste of one of the harpsichord sections from this.

[Turrican_II-World1.zip](https://github.com/musescore/MuseScore/files/12266803/Turrican_II-World1.zip)

**Comment by cbjeukendrup** [comment]
I can't reproduce this either. Are you sure that Muse Sounds is up to date on your computer? (see Muse Hub)

**Comment by majenkotech** [comment]
Yep, everything is up to date (something I am in the habit of checking every time before I start working on anything).

**Comment by majenkotech** [comment]
I'm just setting up a spare computer with Windows 11, and noticed that export on here is defaulting to 44100Hz, whereas on my windows 10 and linux machines it defaults to 48000Hz. I'm running a test export now (it takes forever, this is an ancient computer) at 44100, and then if that works I'll do another at 48000 to see if it then fails.

**Comment by majenkotech** [comment]
OMG, that's totally it.  It only happens at 48000Hz export, which seems to be the default on both my main computers. Maybe not the fresh-install default though. Try exporting the sample file above at 48000Hz...

**Comment by MarcSabatella** [comment]
See also https://github.com/musescore/MuseScore/issues/17849, and a number of other issues relating to sample rate dependencies.

**Comment by cbjeukendrup** [comment]
I can indeed reproduce it too when switching to 48000 Hz. Thanks for your investigation!
(And the default is indeed 44100, but if you've ever switched to 48000, that will be remembered, so that might be a point of confusion here.)
