### ISSUE TITLE
MuseScore 4.4.1 hangs on 'Scanning audio plugins' and won't load

### ISSUE THREAD

**Issue by Kevsy** [musescore/MuseScore#18884]
### Issue type

Crash or freeze

### Bug description

MuseScore starts to launch, but hangs on 'Scanning audio plugins' (per screenshot). It has hanged at 0% (once) and 53% (twice) but gets no further in each case. The plugin SPL HawkEye.vst3 is named in the hanging progress popup window.

### Steps to reproduce

1. Launch MuseScore 4 from either the Dock or MuseHub

### Screenshots/Screen recordings

![Screenshot 2023-08-02 at 14 19 51](https://github.com/musescore/MuseScore/assets/7903978/64381d89-9995-4799-8c90-3ddc8406cfa3)

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Monterey 12.6.8

### Additional context

Mac mini (Late 2014)
Processor 2.6 GHz Dual-Core Intel Core i5
Memory 16 GB 1600 MHz DDR3
Graphics Intel Iris 1536 MB
145GB storage remaining

**Comment by zacjansheski** [comment]
I am unable to reproduce.  Did you install Hawkeye with the PA installation manager?

@RomanPudashkin would logs help with this

<img width="178" alt="Screen Shot 2023-08-02 at 11 23 33 AM" src="https://github.com/musescore/MuseScore/assets/69917893/eaad28b0-46f8-4c91-9301-aaf3f25c658c">

**Comment by Kevsy** [comment]
Thanks @zacjansheski  - I have the PA installation manager, but had not installed the plugin. I think it was part of a trial bundle given when I bought another plugin for Logic. So I activated and installed the plugin (via Logic and PA installation manager)  and MuseHub now opens fine - it succesfully scanned through all the other plugins, even those that were also in the same trial bundle.
Thanks again for your time!
