### ISSUE TITLE
add these free midi files to musescore for people to access in app

### ISSUE THREAD

**Issue by RustoMCSpit** [musescore/MuseScore#18881]
### Your idea

https://github.com/Fannon/midi-chords-and-scales-pack/issues/2

heres a list of free midi resources, add them in app for people to use and experiment with

### Problem to be solved

writers block

**Comment by Tantacrul** [comment]
I opened one 'scale' in MuseScore and got this, so I don't think we'll want to dedicate resources to including this in the build ourselves. Perhaps a community member can be persuaded to look through each of the scales and arrange them in a way that is useful for MS4. However, I'm closing this issue, since it isn't really actionable. I'd recommend asking on our Discord server instead.

<img width="450" alt="image" src="https://github.com/musescore/MuseScore/assets/21022311/33068dfe-791c-455d-bfc8-7f9313b4af0b">

**Comment by RustoMCSpit** [comment]
> I opened one 'scale' in MuseScore and got this, so I don't think we'll want to dedicate resources to including this in the build ourselves. Perhaps a community member can be persuaded to look through each of the scales and arrange them in a way that is useful for MS4. However, I'm closing this issue, since it isn't really actionable. I'd recommend asking on our Discord server instead.
> 
> <img alt="image" width="450" src="https://user-images.githubusercontent.com/21022311/259348337-33068dfe-791c-455d-bfc8-7f9313b4af0b.png">

i think the general concept is still good and id recommend asking the discord to upload .midi files and then build them into musescore

**Comment by Tantacrul** [comment]
The actual scales and chords need to be validated so users never see anything like this. It could be part of a new section in the 'Home' tab, where we allow users to browse various types of community content.

**Comment by RustoMCSpit** [comment]
> The actual scales and chords need to be validated so users never see anything like this. It could be part of a new section in the 'Home' tab, where we allow users to browse various types of community content.

well i mean, no harm beforehand askimg the discord to submit midi chords and then packaging them all i guess

**Comment by RustoMCSpit** [comment]
> The actual scales and chords need to be validated so users never see anything like this. It could be part of a new section in the 'Home' tab, where we allow users to browse various types of community content.

hookpad handles chords way better than musescore, you should try it out if you were serious about implementation
