### ISSUE TITLE
Adding pizz. to a sustaining non-string instrument in MS Basic causes note to sound indefinitely

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18889]
### Issue type

Other type of issue

### Bug description

Adding pizz. to a sustaining non-string instrument in MS Basic causes note to sound indefinitely

### Steps to reproduce

1. create a new score with sustaining non-string instrument (flute, trombone, oboe, organ, voice)
2. Be sure instrument is assigned to MS Basic
3. add pizz to it (don't ask why, just do it!)
4. click on the note/start playback
5. the note sounds endlessly

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/f5dbf9d2-d6d2-418a-bcea-baa0b60a3ed5

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232140302, revision: github-musescore-musescore-6d005d2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

All

**Comment by MarcSabatella** [comment]
FWIW, this comes up quite often in real-world situations where someone starts with a score originally written strings and then changes instruments to winds.  Until you remove the pre-existing arco & pizz indications, you get the infinite sustain.

**Comment by RomanPudashkin** [comment]
working on it
