### ISSUE TITLE
Renaming an instrument should also rename the Mixer

### ISSUE THREAD

**Issue by gertfriend** [musescore/MuseScore#18903]
### Issue type

UI bug

### Bug description

If renaming a instrument also the Mixer (found variable <trackName>) should be renamed to identify better an instrument in the Mixer

### Steps to reproduce

Go to Instruments (F7)
Select to rename an Instrument
Confirm renaming

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
See also.  This is mentioned in the discussion there as part of a proposed solution, although the main issue is about part names, not mixer channel names.
