### ISSUE TITLE
Musescore.com "Update this score" >> "Replace file" fails to update file

### ISSUE THREAD

**Issue by RexDjere** [musescore/MuseScore#18915]
### Issue type

Other type of issue

### Bug description

Creating a new score and uploading it to Musesore.com works fine. But if you update the score and try to upload the updated version, it looks like it works, but the update actually fails.

UPDATE: I was able to find a workaround: when I save to cloud, it works better. Updating an existing file still fails, but I was able to find a slightly complicated workaround. I can continue working on the book.

### Steps to reproduce

1. Create a new score in the MuseScore desktop application.
2. Upload the score to MuseScore.com.
3. Make a change to the score.
4. Try to upload the changed version to MuseScore.com.
5. It goes through all of the normal processes, but the changed score is not actually uploaded.

This problem just appeared today for me (Aug. 3, 2023). I successfully updated scores a couple of days ago.

### MuseScore Version

4.1.1

### Regression

No.

### Operating system

Pop!OS 22.04

![Screenshot from 2023-08-03 16-58-52](https://github.com/musescore/MuseScore/assets/1860586/cde86724-afd9-4d5c-ba5d-8381a6f7a145)

**Comment by RexDjere** [comment]
In the score above, I updated the MuseScore.com link on the score, but as you can see, the updated score was never uploaded. I tried several times to update the file: it failed every time.

**Comment by RexDjere** [comment]
I just submitted a help request to MuseScore.com.

**Comment by zacjansheski** [comment]
I am not able to reproduce on MacOS right now.  Has this already been resolved on the .com end?

**Comment by zacjansheski** [comment]
Confirmed issue on 4.1.1 , not an issue in current master

**Comment by zacjansheski** [comment]
Weird, now I can't reproduce. :)

https://github.com/musescore/MuseScore/assets/69917893/9a13ccc9-c1f0-4276-a151-dc2aad9141e8

**Comment by zacjansheski** [comment]
@RexDjere Can you confirm this is still happening?  Does it only occur with certain scores?

**Comment by RexDjere** [comment]
@zacjansheski I haven't tried yet today. It was still happening as of 8 hours ago. I'll try now, and report back the results.

**Comment by RexDjere** [comment]
@zacjansheski Hello!!! It seems to be working now. I updated this score, and uploading the update to MuseScore.com was successful: https://musescore.com/user/18100066/scores/10470385

**Comment by zacjansheski** [comment]
Thank you!
