### ISSUE TITLE
Drumset note entry noteheads gone in current nightly

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18910]
### Issue type

UI bug

### Bug description

Drumset note entry noteheads gone in current nightly

### Steps to reproduce

1. Create a score with drumset
2. Go to note entry
3. Noteheads do not appear in drumset window

### Screenshots/Screen recordings

<img width="923" alt="Screen Shot 2023-08-03 at 1 06 20 PM" src="https://github.com/musescore/MuseScore/assets/69917893/7ff7c3e6-b9ea-4bcc-ba20-aa73e5021184">

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232150302, revision: github-musescore-musescore-e5babf1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

All

### Additional context

Similar to closed issue
https://github.com/musescore/MuseScore/issues/18337

**Comment by cbjeukendrup** [comment]
Working on it

**Comment by cbjeukendrup** [comment]
@zacjansheski Sorry that I didn't ask you to test the corresponding PR, but I don't think that's really necessary at this point, since we're still in the middle of libmscore refactoring work, and this issue was related to that.
