### ISSUE TITLE
Crash if removing instrument with volta which was added holding Ctr/Cmd (volta on multiple staves)

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#18925]
### Issue type

Crash or freeze

### Bug description

Musescore 4.1.1 and master crashes if volta is present on second staff/instrument and you try to remove that staff. I can't reproduce this state in 4.1.1, but you can get real scores here https://musescore.org/en/node/353185

### Steps to reproduce

1. open this file https://musescore.org/sites/musescore.org/files/2023-08/Boom%20Boom.mscz
2. Remove guitar tablature from instruments

https://github.com/musescore/MuseScore/assets/919446/f7b7e4ce-e8da-490b-ab32-ee01fd210659

or 

1. Create score with Flute + Piano
2. Select rest on Piano staff
3. Holding Ctr, add Volta line
4. Delete Piano 

https://github.com/musescore/MuseScore/assets/90187801/3f1c304b-2911-41e8-90c8-a1a2cb027431

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

First appeared in **4.0.2**

### Operating system

OS: Windows 10 Version 2009

**Comment by zacjansheski** [comment]
I wonder how the file got in that state, the 1st/2nd endings on both parts instead of just the top part and no info in the instruments menu.

Crash log

[BoomBoomCrash.zip](https://github.com/musescore/MuseScore/files/12264466/BoomBoomCrash.zip)

**Comment by mercuree** [comment]
Musescore 3.6.2 allows to create volta for multiple staves. 
To reproduce you need to create voltas in 3.6.2 and then open it in 4.1.1. Now removing second staff will crash musescore 4.1.1

**Comment by mercuree** [comment]
Sorry, accidently closed

**Comment by mercuree** [comment]
With #18193 build this crash can be easily reproduces

https://github.com/musescore/MuseScore/assets/919446/9e70822a-9e0f-45c0-a415-fbe2d9440609

**Comment by DmitryArefiev** [comment]
Started to crash in **4.0.2**
