### ISSUE TITLE
File not able to load audio samples

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18928]
### Issue type

Other

### Bug description

IME, if you load and play back (even momentarily) a series of MS4 scores using MS Basic, eventually one score will get stuck on the "Loading audio samples" stage. The scores concerned probably need to be multi-instrument and with a variety of instrumentaton from score to score.

See also #17914?

### Steps to reproduce

Note: The scores used don't need to have a large number of instruments.

1. Use MS Basic SoundFont.
2. Load a score (e.g. a four-part choir). Play part of it back. Then close it.
3. Open another score (e.g. Piano and voice). Play part of it back then close it.
4. Continue like this with other scores.

RESULT: You may eventually find that a "Loading audio samples" bar shows when a score is first loaded. This may become frozen and you can no longer load any scores.

If this happens you need to close then reopen the program.

### MuseScore Version

 MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by cbjeukendrup** [comment]
This also reminds me a bit of #17123

**Comment by bkunda** [comment]
@DmitryArefiev have you been able to reproduce this one?

**Comment by DmitryArefiev** [comment]
@rgreen5 Can you attach the scores please if you find a way with 100% reproducibility?

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

I can't reproduce now. Ok to close.

**Comment by DmitryArefiev** [comment]
Glad to hear. Thanks!

Closing
