### ISSUE TITLE
Save opened palleters after restart the Musescore

### ISSUE THREAD

**Issue by andriisivak** [musescore/MuseScore#18926]
### Your idea

do not close opened palleters
![Screenshot_1](https://github.com/musescore/MuseScore/assets/13085837/b092fc59-3841-418a-8106-8bcfe0e2893b)

### Problem to be solved

opened before palleters should stay opened after Musescore restart

**Comment by andriisivak** [comment]
Windows 10, Musescore 4.1.1

**Comment by cbjeukendrup** [comment]
This looks like a duplicate of #17064. Thanks for reporting though!
