### ISSUE TITLE
Changing voices does not assign new voice to ties

### ISSUE THREAD

**Issue by oMrSmith** [musescore/MuseScore#18938]
### Issue type

Notation issue

### Bug description

Changing notes with ties to another voice
does not assign the new voice to the ties.

### Steps to reproduce

Please watch the following short clip:

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/78870770/e4d8309d-4137-415d-a705-82d2138b2c43

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230990506, revision: github-musescore-musescore-8582f3a

### Regression

No, this doesn't work in MU3 either.

### Operating system

Windows 10

**Comment by oktophonie** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/18546
