### ISSUE TITLE
"Fingerings" should be spelt "Fingering"

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18933]
### Issue type

UI bug

### Bug description

There is a spelling mistake in the "Text styles" section of the Style dialog; it also occurs in the corresponding section of the Properties panel. It may seem a small difference but the plural form may give the misleading impression that this style applies to _all_ fingering types.

**Suggestion**: "Fingerings" should be spelt "Fingering", as it was in MS3.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64.

**Comment by Jojo-Schmitz** [comment]
Update your translations (Preferences > Check for translation updates), then restart MuseScore

**Comment by rgreen5** [comment]
Thanks. Fixed.
