### ISSUE TITLE
Allow custom templates

### ISSUE THREAD

**Issue by andriisivak** [musescore/MuseScore#18932]
### Your idea

Allow custom templates, as it was in Musescore v3.x.x, to quick creation of a new sheet music with own settings / instruments.
Windows 10, Musescore 4.1.1
![image](https://github.com/musescore/MuseScore/assets/13085837/65000049-5aba-4bf9-9d29-005f5f25e1a4)

### Problem to be solved

saving own settings and quick access to creation of own sheet music

**Comment by rgreen5** [comment]
AFAICS, this is already possible. Just save the template in the "Templates" folder.

**Comment by cbjeukendrup** [comment]
That's right, it's already possible. @andriisivak Is there any difference with MS3 that you would like to see fixed?

**Comment by Jojo-Schmitz** [comment]
This indeed is possible already. Only it is called "My Templates" (and is the only item in the category listing that is translated, but see #14900)

**Comment by andriisivak** [comment]
> That's right, it's already possible. @andriisivak Is there any difference with MS3 that you would like to see fixed?

another one is [here](https://github.com/musescore/MuseScore/issues/18927)
thx!

**Comment by andriisivak** [comment]
> That's right, it's already possible. @andriisivak Is there any difference with MS3 that you would like to see fixed?

nope, all was good in MS3 for me. thx!

**Comment by Jojo-Schmitz** [comment]
But what's wrong with Mu4 then?

**Comment by andriisivak** [comment]
> But what's wrong with Mu4 then?

hmm, but how can I create and save my own template? i don't see this possiblity in Musescore v4.1.1🤔

**Comment by Jojo-Schmitz** [comment]
The very same as in Mu3: just save a score into your Templates folder

**Comment by andriisivak** [comment]
> The very same as in Mu3: just save a score into your Templates folder

thanks! yesterday I tried and without success. will try again later, thx again

**Comment by andriisivak** [comment]
but i tried to re-save my old MS3 template.. maybe it's my mistake)

**Comment by MarcSabatella** [comment]
That would be a bad idea, since much has changed about the default settings etc.  better to create a new one.  But in general it should work, it just might produce unexpected results.  Nothing about the process itself has changed though.

If you need further help learning to use MuseScore, please ask in the official Support forum on musescore.org.  Then if it turns out that there is a bug relating to some aspect of this and others can confirm it, you can open an issue here.

**Comment by andriisivak** [comment]
i tried to create a new template and place it to MC4 "templates" folder, but it didn't appear in the list of templates😐
anyway, thank you for your help, i will find the answer on the forum on musescore.org
we can close this ticket👌

**Comment by andriisivak** [comment]
finally it's a win😅
we should save a new template not in system folder, but in user folder
for example: not in "C:\Program Files\MuseScore 4\templates", but in "D:\Documents\MuseScore4\Templates"

great!🤘😇

**Comment by Jojo-Schmitz** [comment]
Yes, of course, same as in Mu3
And you may need to restart MuseScore
