### ISSUE TITLE
Application crashes upon sleep

### ISSUE THREAD

**Issue by richarddeem** [musescore/MuseScore#18930]
### Issue type

Crash or freeze

### Bug description

Using Windows 11 Pro, The Musescore application crashes whenever the system goes into sleep.

Category: Muse.Service.Interop.ServiceCore
EventId: 0

Other alert: 46: UDP error: An existing connection was forcibly closed by the remote host from: 2600:1700:d470:5940::410 op: sock_read

### Steps to reproduce

Leave MuseScore application running
Put system into sleep
Wake up from sleep

### MuseScore Version

4.1.1

### Regression

No.

### Operating system

Windows 11 Pro

### Additional context

Device name	Rich-PC
Processor	Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz   3.70 GHz
Installed RAM	32.0 GB (31.7 GB usable)
Device ID	E1FE1525-5489-47E4-AC71-8A52558490BE
Product ID	00330-53340-07490-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by cbjeukendrup** [comment]
> Category: Muse.Service.Interop.ServiceCore

That sounds like it has to do with Muse Hub / Muse Sounds...

**Comment by richarddeem** [comment]
Is there something that can be done to prevent the service from crashing?

**Comment by cbjeukendrup** [comment]
I'm not sure. Perhaps @DominicMaas can help debugging this?

**Comment by DominicMaas** [comment]
This event shouldn't be an issue, (current version of Hub automatically logs "errors" to the event viewer - kinda spamming it). Just talking about TCP sockets, so unrelated to any crashes.

**Comment by cbjeukendrup** [comment]
Okay, so then we have the following:
- MuseScore crashes for a completely unknown reason;
- Muse Hub logs a completely unrelated message to the event viewer.

Is that right @richarddeem? 

It might be helpful if you could upload MuseScore's own diagnostic files: you can obtain them in MuseScore using "Diagnostic" > "Save diagnostic files".

**Comment by zacjansheski** [comment]
Closing this.

Lack of activity and there is not an indication that this is a widespread issue.
