### ISSUE TITLE
Clicking on an empty bar and hitting "Play" does not start the Mixer playing, as it did in MS 3.6

### ISSUE THREAD

**Issue by fsgregs** [musescore/MuseScore#18936]
### Issue type

General playback bug

### Bug description

In MS 4.1, clicking on the bar or measure space does not play any notes or start the song playing in the Mixer as it does in MS 3.6.   In MS4, I have to click on a rest or note in the measure to get some sound.  I guess I can get used to it, but it is not an improvement and is awkward.  It should be that either clicking the bar OR the note will play the song from that point, as it does in MS 3.6

### Steps to reproduce

1.  Open a song in MS 4.1
2. Enter a few notes in any bar/measure, using any instrument
3. Click on the 1st note and press the play key (>).  The Mixer will begin playing the notes
4. Return to bar 1 and click on the bar/space (not a note).  Press Play.  Nothing happens
5. This did not occur in MS 3.6

### MuseScore Version

MS 4.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
This is a feature, not a bug.  Selecting a full measure or any other range *solos* the selected staves.  So it's a quick way to hear only one staff, or a group of adjacent staves.  If you wish to hear the whole score, then hit Esc to clear the selection, or select a single note - or *anything* other than a full measure.

If you need further assistance using MuseScore, please ask for help on the official Support forum on msuescore.org. Only open issues here on GitHub if other users there can confirm the behavior you are seeing is a bug, is reproducible, is not already reported, and is not already fixed for an upcoming release.

**Comment by fsgregs** [comment]
Marc:  Drat.  I see what you mean.  I had no idea that clicking on a bar containing notes would play only the notes **on that instrument**, nor that hitting ESC then play would resume the entire song playing.  Somehow, I did not discover that when using MS4.  In MS3.6, clicking on even an empty bar then play would start the entire song playing.

I like the new feature.  Thanks for the clarification.
