### ISSUE TITLE
Option to add double barline before key signature change automatically

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#18941]
### Your idea

When entering a key change, MuseScore should have a preference (off by default?) to create a double barline before the new key, as is conventional in traditional notations.

### Problem to be solved

At present I have to go back to each key change and add the double barline manually. In other applications, this can be created automatically saving time. As some people prefer not to have this happen automatically, it should be a preference setting that can be on or off.

### Prior art

Sibelius inserts these automatically as extra elements, rather than as part of rendering, so they can be individually deleted if desired.

### Additional context

Discussed on MuseScore forums (https://musescore.org/en/node/302860) but I couldn't find an issue for this. The approach described, creating the double barline as part of the addition of a key change, seems much more flexible than trying to automatically render them during layout.

**Comment by oktophonie** [comment]
Also for time sigs (see my needless duplicate at https://github.com/musescore/MuseScore/issues/21127)

**Comment by XiaoMigros** [comment]
I'd still like to tackle this :)

**Comment by iainhallam** [comment]
> Also for time sigs (see my needless duplicate at #21127)

Though this would need to be a separate option from the key signatures - I'd use the key one, but not time.
