### ISSUE TITLE
Adding notes to a chord toggles articulation instead of preserving

### ISSUE THREAD

**Issue by WHS241** [musescore/MuseScore#18948]
### Issue type

UI bug

### Bug description

The UI for adding articulation during note entry is confusing; if the icon is highlighted, adding notes to a chord toggles the articulation (on-to-off as well as off-to-on) rather than enforcing the articulation mark. The toggling can become an issue if multiple articulations are chosen.

### Steps to reproduce

1. Enter note entry mode
2. Choose an articulation (can either select from note entry bar or use keyboard shortcuts)
3. Enter a note. As expected, the articulation is applied to the note, and the articulation remains selected in the note bar.
4. Add a second note in the same place (can use either mouse or Shift-[note]). The articulation disappears, but the note entry bar still has the articulation highlighted.
5. Continue adding notes. While the bar still displays the articulation as highlighted, the chord toggles between having the articulation applied and removed.
6. Choose a second articulation while the first is currently applied, then continue adding to the chord. The chord now toggles _between_ the two articulations, rather than apply both simultaneously.

### Screenshots/Screen recordings

https://drive.google.com/file/d/1w00U_4BM-QQDk7GhJ-YvZ_79WhkiVs-1/view?usp=drive_link

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Linux

**Comment by bkunda** [comment]
@mathesoncalum FYI (in case this one is up your alley!)
