### ISSUE TITLE
Crash if copy/paste on local time signature staff

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#18940]
### Issue type

Crash or freeze

### Bug description

Musescore 4.1.1 crashes if you try to copy/paste some notes on a staff with local time signature if time signature has changed afterwards.
based on this score https://musescore.org/en/node/351213

### Steps to reproduce

1. Create local time signature (CTRL + drag & drop icon with time signature)
2. change time signature after a few measures
3. type some notes
4. copy/paste those notes to the next measure

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/f8782c5f-d972-4a67-899c-fb3278fecdc3

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009

**Comment by zacjansheski** [comment]
[18940_DiagnosticFiles.zip](https://github.com/musescore/MuseScore/files/12294132/18940_DiagnosticFiles.zip)
