### ISSUE TITLE
Crash if trying to change instrument for staff without key signature

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#18957]
### Issue type

Crash or freeze

### Bug description

Musescore 4.1.1 and master crashes when trying to change instrument with the following conditions:
1. Musescore file created with previous versions (created for 3.6.2 and 4.0.2)
2. Soprano Saxophone is the current instrument
3. Key signature is completely removed for current staff (in previous versions of Musescore it was allowed to do so removing key signature completely)

based on report https://musescore.org/en/node/352301

### Steps to reproduce

1. Create/open file with musescore 3.6.2 or 4.0.2
2. Set instrument Soprano Saxophone
3. Remove key signature and save file
4. Open this file with Musescore 4.1.1
5. Change instrument for current staff
6. Crash

### Screenshots/Screen recordings

Demo with file created in Musescore 4.0.2

https://github.com/musescore/MuseScore/assets/919446/96b08eae-8bff-4872-be7d-3c85a23eb9db

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009

### Additional context

Empty score created with Musescore 4.0.2
[emptySopranoSax4.0.2.zip](https://github.com/musescore/MuseScore/files/12281684/emptySopranoSax4.0.2.zip)

**Comment by sammik** [comment]
Crash is caused by forgotten null check, but I propose also to add import check for older scores, and force initial keysig if missing.
Otherways other problems may appear (incorrect instrument change keysigs) in souch scores
Working on it.
