### ISSUE TITLE
Setting tempo in "New Score" wizard always sets tempo to quarter note = [Tempo]

### ISSUE THREAD

**Issue by CoyoteFox** [musescore/MuseScore#18962]
### Issue type

Other type of issue

### Bug description

When setting the tempo in the new score wizard, if you choose to show the tempo on the score, the playback will always default to quarter note = [whatever tempo you chose]. This happens even if you selected 8th note = [tempo] or half note = [tempo] or any other option while setting up the score. Despite the score appearing correct, the playback will be wrong. The tempo marking in the upper right-hand corner corroborates this.

### Steps to reproduce

1. Open the new score wizard
2. Continue through the wizard until you get to the page titled "Addintion score information"
3. Click on  the tempo marking and check "Show tempo marking on my score"
4. Select any of the note lengths (except quarter note) and set a tempo number
5. Click Done

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/87743167/38e5d924-35d9-4318-8354-ae3d712c38b7

(The audio recording didn't work. Hopefully this still shows the issue),

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
Looks related to #14678

**Comment by CoyoteFox** [comment]
It definitely is, I'll close this one as a duplicate
