### ISSUE TITLE
Adding expression text to multimeasure rest shouldn't break it

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#18969]
### Issue type

Engraving bug

### Steps to reproduce

https://github.com/musescore/MuseScore/assets/90187801/f7015932-bcf7-4125-ba5b-53c378b588c2

### MuseScore Version

4.2.0 master

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows10

### Additional context

#18919

**Comment by oktophonie** [comment]
I'd say that's a matter of opinion.

**Comment by MarcSabatella** [comment]
As long as it's just expression text that breaks mmrests and not staff or tempo text or rehearsal marks (and indeed this is true), I could buy into calling this a feature...

**Comment by SteveBlower** [comment]
Or rather the converse surely; expression doesn't break, staff, tempo rehearsal marks do break.

**Comment by MarcSabatella** [comment]
I think you are thinking of a different sense of "break" than what I see in this issue.  "Exclude" is actually more like it.  That is, currently in 4.1.1, an expression text on a measure cause the measure to not be eligible for inclusion in an mmrest at all.  Whereas other text will *break* the mmrest but not *exclude* the measure from inclusion.

So, right now, if you start with this:

![image](https://github.com/musescore/MuseScore/assets/1799936/023feedb-b9b8-4606-bf38-7dc541bc4c3f)

It turns into this:

![image](https://github.com/musescore/MuseScore/assets/1799936/9758c185-51df-4158-b70c-ef44e8397126)

The behavior for the staff text is absolutely correct - it breaks but doesn't exclude.  But the expression text - a new element type for 4.1 - does something different.  *Probably* it should be handled the same as staff text, but that's what's a matter of opinion.

**Comment by DmitryArefiev** [comment]
Fixed in #19001
