### ISSUE TITLE
Written notes don't match played notes

### ISSUE THREAD

**Issue by toto-polo** [musescore/MuseScore#18968]
### Issue type

Engraving bug

### Bug description

I copied and pasted some notes from another staff, but they displayed incorrectly on my clarinet staff. The played sounds don't match the written sounds. It sounds as it should but the note on screen is incorrect. 

Attached is my score in MuseScore format.

### Steps to reproduce

I manage to reproduce the bug

1. Create a score with 2 instruments : Guitar and Bb Clarinet
2. Use kontakt player vst for guitar
3. I use"Session guitariste : Picked Acoustic" librairie
4. Write 1/4 notes (like only C) on guitar staff
5. Copy paste note by note on clarinet staff
6. Some notes are falsy paste on clarinet staff but sounds the good pitch in comparison to what they're copied from
7. In my attached video, the last note is incorrect

### Screenshots/Screen recordings

The bug reproduce in a new session with random notes and many copy / paste. In this video the bug comes for the final note :

https://github.com/musescore/MuseScore/assets/39052403/f3a605d1-f3ab-42b7-b014-a2285ad2bc59

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS 11.7.1

### Additional context

Musescore project : [https://drive.google.com/file/d/1tOx4Ld0M3cIJ7omaHaqS5p2JGcZLMVQ_/view?usp=sharing](url)

**Comment by zacjansheski** [comment]
I am able to reproduce at least a similar issue without a VST
@sammik could you take a look at this?

https://github.com/musescore/MuseScore/assets/69917893/5eec1ea4-b15d-4a71-8f5d-5ac092f193fe

**Comment by zacjansheski** [comment]
Able to reproduce in all versions of MS4

**Comment by sammik** [comment]
Happens always, when pasting between instruments with different transpositions (not only from guitar to clarinet, but also from clarinet to guitar), and pasting to rest with same duration as pasted note has.

Thats why, it happens only "sometimes".

Fix on the way.
