### ISSUE TITLE
Measure repeat number collides with barline and repeat symbol

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#18961]
### Issue type

UI bug

### Bug description

This affects two- and four-measure repeats. if the staff uses less than 5 lines the measure repeat number may collide with the barline and the repeat symbol:

![measure_repeats](https://github.com/musescore/MuseScore/assets/87246583/db358367-d881-4194-87a4-3aa05f3dbf11)

### Steps to reproduce

Open the attached MS4 file and observe the layout of measure repeat signs.
[measure_repeats.zip](https://github.com/musescore/MuseScore/files/12282413/measure_repeats.zip)

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by oktophonie** [comment]
See also: https://github.com/musescore/MuseScore/issues/16426
