### ISSUE TITLE
Linux Mint Jammy Jellyfish LTS Flatpak / AppImage Musescore 4 will not play 

### ISSUE THREAD

**Issue by RustoMCSpit** [musescore/MuseScore#18994]
### Issue type

General playback bug

### Bug description

Playback does not work, press space and you just see a frozen line

### Steps to reproduce

1. Press Space
2. Nothing occurs

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

linux mint jammy jellyfish lts

**Comment by cbjeukendrup** [comment]
See perhaps #11220 for some workarounds that might work

**Comment by cbjeukendrup** [comment]
Also, the Flatpak is not supported/maintained by us, so it would be good to know if this also happens with the AppImage from https://musescore.org.

**Comment by RustoMCSpit** [comment]
> Also, the Flatpak is not supported/maintained by us, so it would be good to know if this also happens with the AppImage from https://musescore.org.

doesnt work eithet

**Comment by RustoMCSpit** [comment]
btw i am using pipewire if that means anything

**Comment by Jojo-Schmitz** [comment]
If it is in the AppImage too, then please reflect that in the title

**Comment by RustoMCSpit** [comment]
@oktophonie what is this a duplicate of

**Comment by Jojo-Schmitz** [comment]
I guess #11220

**Comment by RustoMCSpit** [comment]
> I guess #11220

Fedora 35 ?

**Comment by Jojo-Schmitz** [comment]
Yet another Linux
