### ISSUE TITLE
Opening this score crashes the nightly, not 4.1.1

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18990]
### Issue type

Crash or freeze

### Bug description

I can open this score in 4.1.1,  I cannot open it in the current master

### Steps to reproduce

Open this score

[Bach_-_Brandenburg_Concerto_No._3_-_BWV_1041.mscz.zip](https://github.com/musescore/MuseScore/files/12303302/Bach_-_Brandenburg_Concerto_No._3_-_BWV_1041.mscz.zip)

### MuseScore Version

OS: macOS 11.7, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232210302, revision: github-musescore-musescore-05f017f

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

All

### Additional context

[BrandenburgCrash.zip](https://github.com/musescore/MuseScore/files/12303288/BrandenburgCrash.zip)

**Comment by Jojo-Schmitz** [comment]
The score stems from 3.3.4. Later releases of MuseScore (not exactly sure when that got introduced) do remove pictures not used in the score, so yes, that is correct behavoir.
