### ISSUE TITLE
Crash when using template with notes and slurs

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#18995]
### Issue type

Crash or freeze

### Bug description

Musescore 4.1.1 and 4.2.0 crashes when trying to load musescore file as template if it contains notes with slurs

### Steps to reproduce

1. Create score and type some notes with slurs
2. save it to the templates folder (Documents/MuseScore4/Templates)
3. Create new score (Create from Template -> My templates - > select that file)
4. Click "Done" button
5. Crash...

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/af39064d-d1fa-485d-9ee2-47bf021cc0bf

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009

**Comment by zacjansheski** [comment]
I just tried this on the current Master Windows 11 and Mac OS 11.6.5.  Template opens without notes

https://github.com/musescore/MuseScore/assets/69917893/13a411cd-c975-4344-9579-9aeb15cc656a

**Comment by mercuree** [comment]
Confirm no crash with MuseScore version (64-bit): 4.2.0-232222302, revision: github-musescore-musescore-9bff4c6
Should I close this issue?
I have another score which still crashes while using as template, but it was created with older (3.3.2) versions of musescore and it's not so significant to fix.
[Bach_-_Brandenburg_Concerto_No._3_-_BWV_1041.zip](https://github.com/musescore/MuseScore/files/12323071/Bach_-_Brandenburg_Concerto_No._3_-_BWV_1041.zip)

**Comment by zacjansheski** [comment]
Let's close, based on the file name I'm guessing that's the same as this recently closed issue. https://github.com/musescore/MuseScore/issues/18990

If something comes up after the next set of builds we can open a new report.  Thanks!
