### ISSUE TITLE
No Playback (MS Basic) + Crash with Gradual Tempo Change with 0% tempo change amount

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#19009]
### Issue type

Crash or freeze

### Bug description

Playback not working if there is gradual tempo change anywhere in score with setting 0% amount.
Also musescore crashes if you clear measure under that tempo

### Steps to reproduce

1. create score and enter few notes
2. add rit. or any other gradual tempo after a few measures
3. set tempo amout property to 0% - now playback is not working anymore
4. Add some notes under tempo
5. Clear measure
6. Crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/acb31d49-1c7b-46db-891d-0d249f3cf62e

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009

**Comment by zacjansheski** [comment]
[RitZeroCrash.zip](https://github.com/musescore/MuseScore/files/12346046/RitZeroCrash.zip)

**Comment by zacjansheski** [comment]
To reproduce this crash, the rit must end within a measure (not attached to barline)

https://github.com/musescore/MuseScore/assets/69917893/e25c61df-2404-4c5a-8cf2-01c7dde19e61

**Comment by bkunda** [comment]
Demoted because the steps to reproduce are very niche/specific.
