### ISSUE TITLE
Muse Strings causing MS4 to crash after score importing

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#19005]
### Issue type

Muse Sounds bug

### Bug description

So I recently updated the strings in Muse Hub. Now whenever I try to open up a saved MuseScore file I have attached to my account, the application crashes.

What was the cause of one of the Muse Strings presets to make MS 4 crash like this?

Again, it happened whenever I imported an online saved score, and waited for the sounds to load.

[A Dream from the Past.mscz.zip](https://github.com/musescore/MuseScore/files/12314101/A.Dream.from.the.Past.mscz.zip)

### Steps to reproduce

1. Open the .mscz file I've attached.
2. Wait for the Muse sounds to load.
3. See if the crash also occurred on your end.

### MuseScore Version

4.1.0

### Regression

I don't know

### Operating system

Mac OS Monterey v12.6.8

**Comment by MarcSabatella** [comment]
The score loads as expected for me in the current release, 4.1.1.  Please update and see if that fixes it for you as well.

If so, please also test with some scores to see if all scores using Muse Strings are crashing or just this one.  It could be just coincidence that the crash started aroudn the time of the Muse Strings update.

**Comment by zacjansheski** [comment]
Closing, not reproducible
