### ISSUE TITLE
note spacing

### ISSUE THREAD

**Issue by mart661331** [musescore/MuseScore#19007]
### Issue type

Engraving bug

### Bug description

awful spacing when more notes in a system 
![sp;acing 2023-08-10 173607](https://github.com/musescore/MuseScore/assets/110895947/8ef627ef-e7d1-4afe-b2c9-d7cc5f3f87ee)
[spacing.zip](https://github.com/musescore/MuseScore/files/12314620/spacing.zip)

### Steps to reproduce

see files

### MuseScore Version

latest nightly 

### Regression

I don't know

### Operating system

Win 11

**Comment by MarcSabatella** [comment]
Looks like you've disabled autoplace for some elements, added custom offsets, and also decreased the minimum note distance in Format / Style / Measure (as well as other distances and margins).  As far as I can tell, this seems to be showing the correct result of those customizations.
