### ISSUE TITLE
Incorrect MusicXML export of some Figured Bass elements

### ISSUE THREAD

**Issue by mgavioli** [musescore/MuseScore#19019]
### Issue type

File corruption

### Bug description

**Action**: export a score to MusicXML;
**Condition**: a figured bass element contains a non-standard figured bass item (possibly on purpose, as for some B.c. notation not supported yet);
**Result**: the f.b. item is not exported and the f.b. element results empty, which is non-syntactical and result in a XML impossible to import.
**Expected result**: one possible solution is NOT export an empty f.b. element at all.

### Steps to reproduce

The attached file contains:

- a minimum case score with just one measure of one instrument with two F.B. element, the first correct and the second non-standard;
- the MusicXML export of the above: in line 93-94 of it, the empty figured bass element can be seen.

[Figured bass export to MusicXML test.zip](https://github.com/musescore/MuseScore/files/12320243/Figured.bass.export.to.MusicXML.test.zip)

### MuseScore Version

4.1.1

### Regression

No.

### Operating system

Runnig Linux Mint 21.2 here, but I expect this to happen on any OS

**Comment by mgavioli** [comment]
I think it is the case to notify @lvinken ...

**Comment by Jojo-Schmitz** [comment]
It doesn't prevent the MusicXML import, but gives an error which can get ignored...

**Comment by cbjeukendrup** [comment]
@mgavioli Could you please try if https://github.com/musescore/MuseScore/pull/21772 fixes it? (See 
[How to download test builds from pull requests](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests) for instructions, if necessary)
