### ISSUE TITLE
MS4 on Ubuntu - constant CPU load / battery drain

### ISSUE THREAD

**Issue by isolin** [musescore/MuseScore#19011]
### Issue type

Other type of issue

### Bug description

I looked at the list of CPU related issues, but I am surprised that i didn't find any similar complaints. Please correct me if I am wrong.

I am using the appimages of MuseScore4 for Ubuntu, always the latest version available. As soon as I start it, a new process `/tmp/.mount_MuseSc{random_string[6]}/bin/mscore4portable starts and it constantly uses one core of my CPU at 100%. The workload is the same all the time long, even if I am doing nothing. Even when there is no score opened. The intense fan sound of my desktop computer reminds me that I should not dare trying out MS4 on my laptop. Its battery would discharge quite rapidly. 

What is going on there? Why does an app need to do anything when there is no user input, no playback, no export tasks ... it should be in an idle state. This is a specialty of v4, v3 always runs without any such issues.

### Steps to reproduce

1. Keep checking `htop` or any other process-viewer
2. Start the Linux AppImage of MuseScore4
3. Watch the 100% constant load on one of the cores

### MuseScore Version

4

### Regression

No.

### Operating system

Ubuntu 20.04

**Comment by isolin** [comment]
@RomanPudashkin as far as I can see there are no 4.2.0 nightlies for Linux, only for Windows. I will be glad to test it, but please send me a valid link.

I am using 4.1.1 on Ubuntu. I did not observe any improvement regarding the above described issue when comparing to the previous 4.x versions.

**Comment by Jojo-Schmitz** [comment]
There are master builds of the nightlies, those are what b4.2 will become

**Comment by isolin** [comment]
It's fantastic! It does spike 100% CPU usage during playback, but otherwise it is down at 10-15%. 

Also, it seems that problems with loading instruments for playback are gone (need to test more). Before I needed to wait up to an hour before the strange cracking noise during live playback has been replaced by properly loaded samples.
