### ISSUE TITLE
Trilled notes in the middle of tied notes are not played

### ISSUE THREAD

**Issue by Masato-Kato** [musescore/MuseScore#19029]
### Issue type

General playback bug

### Steps to reproduce

1. Create a new score.
2. Place three or more consecutive notes and join them with tie.
3. Place a Trill Line starting at the first note and ending at the last note.
4. Play them.
You will see the first and last notes are played but the middle notes are not played (no sound).

![TrillProblem0001](https://github.com/musescore/MuseScore/assets/3334545/46a22305-307c-48ab-a192-49a6f86f353f)

### MuseScore Version

4.1.1-232071203

### Regression

I don't know

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
See also https://github.com/musescore/MuseScore/issues/18676.  That is originally about something slightly different, but this case is also discussed in the comments.

**Comment by DmitryArefiev** [comment]
> See also #18676. That is originally about something slightly different, but this case is also discussed in the comments.

@MarcSabatella Thanks for mentioning! Yes, it's better to cover all cases in one bug (#18676)

@Masato-Kato Thanks for logging!

Closing as duplicate
