### ISSUE TITLE
"Local relayout" feature is missing in ver. 4.x

### ISSUE THREAD

**Issue by mgavioli** [musescore/MuseScore#19020]
### Issue type

Engraving bug

### Bug description

The "local re-layout" feature, present up to version 3.x, is missing in ver. 4.x.

As a remind, the "local re-layout" feature applied to a single beamed group and engraved it according to its own internal structure and regularity, ignoring alignments with other part(s) which may result in irregular spacing (sample attached, created on ver. 2.3.2; look at the differences in the lower part).

This is rather important to ensure a smoother flow of a part, particularly if playing a single instrument from the score is assumed or even simply possible. In fact it was the default (or at least quite common for entire scores!) for manually engraved scores even in the (non-late) XX century. It is a characteristic quite important to engrave scores of the quality that MuseScore strives to attain.

![Without_local_relayout](https://github.com/musescore/MuseScore/assets/1420743/203931e4-31c6-4e3c-943e-f5611fe6a69d)
![With_local_relayout](https://github.com/musescore/MuseScore/assets/1420743/7d1be4a2-9e91-47d3-a5a0-a0477abd738c)

### Steps to reproduce

As this refers to a **missing** feature, there is nothing one can do!

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Runnig Linux Mint 21.2 here, but I expect this to happen on any OS

**Comment by oktophonie** [comment]
This was removed by design.

**Comment by mgavioli** [comment]
I see. And it has been replaced by something else?
