### ISSUE TITLE
Renaming parts doesn't mark score as changed

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19023]
### Steps to reproduce

1. Open score
2. Rename part - score is not marked as changed (asterisk doesn't appear)

Also, [see comment](https://github.com/musescore/MuseScore/issues/19023#issuecomment-1708455820)  about renaming parts not generated (opened) before  

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/375d7fc9-773d-4a7e-8561-ef84ec862e2c

### MuseScore Version

4.2.0 master

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows10

**Comment by RrOoSsSsOo** [comment]
A releted problem of that issue is that if you rename a part(s) and **you don't open it/them**, even saving, re-opening the file the part(s) remain with old name!

The trick is:
- Rename part(s)
- Open part(s) in tab(s)
- Save
- Close part(s) tab(s)

**Comment by DmitryArefiev** [comment]
Yes, you're right. Will add it to the description

**Comment by Gai-Luron** [comment]
Hello,
This issue is still present on last nightly version : 
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232740304, revision: github-musescore-musescore-5070991
