### ISSUE TITLE
Augmentation dots not showing on full tab staves

### ISSUE THREAD

**Issue by Pajaholic** [musescore/MuseScore#19036]
### Issue type

Engraving bug

### Bug description

Dotted notes do not display correctly in bass tab (full). The attached image (Musescore Tab issue.jpg) shows one bar created in both v3 and v4. The two notes are a dotted crotchet and a minim, but in v4 these look like an undotted crotched followed by a minim. v4 also strips the dots from scores created in v3.
![Musescore Tab Issue](https://github.com/musescore/MuseScore/assets/56545757/1b7ae7a0-4702-4805-8034-fd01e62b899d)
On the Musescore forum, user cadiz1 requested that I report this issue on GitHub (thread: https://musescore.org/en/comment/1203271)
User cadiz1 noted that this appears to be confined to "Tab (full)"

Additional to this bug is that while writing for "bass guitar tablature (full)", the dotted value cannot be selected via the keyboard. I tried this also for violin in standard notation and this issue seems confined to tablature as the keyboard shortcut does not work with "bass guitar tablature (common)" also.

### Steps to reproduce

Either:
Select bass guitar tablature (full) as the instrument for the stave and then attempt to add dotted crotchets, dotted quavers, dotted minims etc. The notes appear on the score undotted.
Or:
Open a score that uses bass guitar tablature (full), contains dotted notes and that was created in version 3. Version 4 strips the dots from the score.
User cadiz1 requested that I try two test files (bass V3.mscz and bass V4.mscz), the image below shows the first opened in both version 3 and 4 and the latter in version 4 only (I assume it was created in version 4 since it wouldn't open in version 3).
![Musescore Test](https://github.com/musescore/MuseScore/assets/56545757/7a3d3fdb-736a-45a2-95b9-94672697f006)

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 64-bit

### Additional context

Version with incorrect behaviour is version 4.1.1 [OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf]

Correct behaviour in previous version 3.6.2 [OS: Windows 10 (10.0), Arch.: x86_64, MuseScore version (64-bit): 3.6.2.548021803, revision: github-musescore-musescore-3224f34]

**Comment by Jojo-Schmitz** [comment]
Mu3.7 has the same issue:
![bass_V3 7](https://github.com/musescore/MuseScore/assets/1786669/775a54e8-4ff5-4ba5-b7e3-080ec2c74c43)
Different stem direction vs. Mu4 though

**Comment by redfoxshk** [comment]
![``](https://github.com/musescore/MuseScore/assets/61365522/8d4e8201-b5be-40fd-b8a7-6a3c0535fd8b)
This issue is related to whether the software can be used normally. It seems that we need to roll back to version 3.6.2 in order for it to work properly.

**Comment by Gravifer** [comment]
Is this possibly related to the fix made to issue #13407 ?
