### ISSUE TITLE
Custom time signature as a shortcut for beaming a bunch of notes doesn't work anymore

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#19034]
### Issue type

Other type of issue

### Bug description

I used to be able to make a custom time signature to match any beaming I came across with enough frequency to justify it. Like say the 1 + 3 2/4 beaming in Beethoven's Fifth or beaming all the eighth notes together in 3/4. Now it doesn't work anymore.

### Steps to reproduce

1. Go to Time Signatures palate and click on More -> Create Time Signature
2. Create a 2/4 or 3/4 time signature with all the eighths beamed together in Time Signature Properties
3. Click Add to add the time signature to the palate
4. Now add a string of eighths in 2/4 or 3/4
5. Place in the newly made time signature
6. Notice that it doesn't automatically beam all the eighths together despite Time Signature Properties saying it should

### MuseScore Version

MuseScore 4.1.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
This works as expected for me if I add the new time signature by selecting a measure - or the original time signature - and then clicking the palette item.  It does not work, however, if I add the time signature by drag and drop *and* the old time signature was otherwise the same as the new.

**Comment by DaddyLudwig** [comment]
That's generally how I add my time signatures is by drag and drop. It's one of many long term habits I have.
