### ISSUE TITLE
"Reload plugins" button does not update plugins

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#19041]
### Issue type

Other type of issue

### Bug description

Changing the directory for instance to relocate and then using the reload plugins function didn't work, but only showed up after a complete application restart. Pretty sure this a a regression from 3.x

### Steps to reproduce

Add plugins to folder, or change out plugins directory, then reload plugins.

### MuseScore Version

4.2 Nightly

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

XFCE Linux

**Comment by cbjeukendrup** [comment]
Duplicate of #13220
