### ISSUE TITLE
dot on dotted note on crossed staff beaming placed inside the staff line when there is another dotted note above it

### ISSUE THREAD

**Issue by Yanko64** [musescore/MuseScore#19057]
### Issue type

Engraving bug

### Bug description

I have trouble wording the title, but the issue is that when moving a dotted note that is on a line to the staff above (cross-staff beaming), the dot will be placed inside the line when there is another dotted note on the top staff
it also occurs when the bottom note is below middle C, 

### Steps to reproduce

1. create a score with a grand staff
2. input a dotted note on the bottom staff (preferably above middle C to see the issue more clearly)
3. move the note to the top staff
4. input a dotted note on the top staff 

the dot on the bottom note should be placed inside the line

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/65133734/af68c12c-41bb-4899-8664-074fa637c185

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

No.

### Operating system

Windows 10

**Comment by oktophonie** [comment]
Naming things is hard :)
Good catch!

**Comment by Jojo-Schmitz** [comment]
Sems a regression vs 3.x
