### ISSUE TITLE
Dropdown box not wide enough in Preferences>Import>MIDI

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#19059]
### Issue type

UI bug

### Bug description

Pointed out by @bkunda  Would be great if this specific box can be as wide as the one above. This is best seeing this in English, UK languages which is what I'm using.

### Steps to reproduce

1. go to preferences
2. then to import
3. see error in MIDI section.

### Screenshots/Screen recordings

<img width="569" alt="Screenshot 2023-08-15 at 17 50 53" src="https://github.com/musescore/MuseScore/assets/71656189/bfa7bc3c-db08-400a-972f-0c5f2614aba4">
<img width="873" alt="Screenshot 2023-08-15 at 17 50 19" src="https://github.com/musescore/MuseScore/assets/71656189/aac300af-af66-414b-84bd-049466508137">

### MuseScore Version

Musescore 4.1.1

### Regression

I don't know

### Operating system

MacOS

**Comment by cbjeukendrup** [comment]
I've marked this as "Good first issue". 
- Easy solution: just increase the hard-coded width of the dropdown to a higher hard-coded value
- More advanced solution: automatically calculate the required width based on all menu items (and perhaps, in addition, set a minimum width for this particular dropdown)
