### ISSUE TITLE
Adding tempo text to multi-measure rests produces bad playback results

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#19075]
### Issue type

General playback bug

### Bug description

Adding tempo text to multimeasure rests produces bad playback results

### Steps to reproduce

1. Open score (I used string quartet)
2. Add notes to measure 3
3. Enable multi-measure rests
4. Add tempo with Opt-Shift-T, check that play head does not match actual
5. Add more notes to measure 3, play for unusual results

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/df089231-bf22-44fa-92a3-be8fbf3dcd83

### MuseScore Version

OS: macOS 11.7, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232281156, revision: github-musescore-musescore-2836cbd

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

All

**Comment by zacjansheski** [comment]
This only occurs when adding the tempo text with the shortcut Opt-Shift-T

**Comment by DmitryArefiev** [comment]
Tried on my side. Yes, it happens only when adding tempo with shortcut and not related to multi-measure rest.
All normalized after reopening the score. 
The same bug in 4.0.0. 

https://github.com/musescore/MuseScore/assets/90187801/056ccdf7-f00f-4812-a8c8-740ab4a7de1f



@zacjansheski Please modify summary and description

**Comment by zacjansheski** [comment]
This is a dupe of https://github.com/musescore/MuseScore/issues/13662
My bad!
