### ISSUE TITLE
System text prevents ottava from saving correctly

### ISSUE THREAD

**Issue by mhogrefe** [musescore/MuseScore#19082]
### Issue type

Other type of issue

### Bug description

[cant-modify-ottava.mscz.zip](https://github.com/musescore/MuseScore/files/12372149/cant-modify-ottava.mscz.zip)

In this example file, if you modify the ottava to extend over both notes, after saving and reopening the ottava is back to just being over one note.

Removing the system text fixes the problem, and it seems that the problem only occurs when the text is not at the same time as either note, hence the need for a second staff in the minimal example.

### Steps to reproduce

1. Open attached file
2. Delete the ottava that is over the first note
3. Create an ottava over both notes
4. Save
5. Reopen
6. Observe that the ottava is only over the first note once again.

### Screenshots/Screen recordings

See attached file, but here's a screenshot as well:

<img width="452" alt="Screen Shot 2023-08-17 at 1 42 35 PM" src="https://github.com/musescore/MuseScore/assets/641461/9d6764a6-0b99-40e8-92fc-156ced61bce8">

### MuseScore Version

OS: macOS 12.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

macOS 12.6.1

**Comment by zacjansheski** [comment]
Only gets longer when clicking and dragging

https://github.com/musescore/MuseScore/assets/69917893/4b07b1ea-00b7-402b-9cc0-2eb36e2e905e

**Comment by bkunda** [comment]
Hi here,
There seem to be a few quirks with the score you've provided.
It doesn't seem to have any instruments in the Instruments panel.
Also it doesn't seem possible to select the bar in the upper stave properly.

Could you try re-creating this example (maybe with a video) and see if the problem persists? 

Otherwise we are having issues reproducing this one.

**Comment by zacjansheski** [comment]
@bkunda Here is the issue created from scratch

https://github.com/musescore/MuseScore/assets/69917893/6053c312-dc9e-4336-b33b-50cc91183da8

**Comment by mhogrefe** [comment]
@zacjansheski Thanks for recreating the bug!

@bkunda Sorry about the quirks. I created my example by reducing a larger score.

**Comment by Jojo-Schmitz** [comment]
Same issue in Mu3
