### ISSUE TITLE
Editing notes with arpeggio over-extends arpeggio, clicking and dragging only makes it longer

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#19083]
### Issue type

Engraving bug

### Bug description

Moving a note on a chord with an arpeggio makes the arpeggio extend too much

### Steps to reproduce

1. Make a chord
2. Add an arpeggio
3. Move the bottom note down with the down arrow

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/93663ff3-715e-45d5-9dfe-ca6fbfa93c62

### MuseScore Version

OS: macOS 11.7, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232290302, revision: github-musescore-musescore-f976592

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: macOS 11.6

### Additional context

Works correctly in 4.1.1
Issue is in Master

**Comment by zacjansheski** [comment]
Only gets longer when clicking and dragging
https://github.com/musescore/MuseScore/assets/69917893/418b59bd-0543-44b3-9180-a77e19baf606

**Comment by metasekk** [comment]
For your information, I've also noticed (see video below) that:
- Straight arpeggios and bracket arpeggios are not affected by the issue;
- Arpeggios also extend when making any change (entering notes outside of the chord, dropping items from the palette, pasting selections...) on other staves on the same line;
- The extended arpeggios reappear normally when re-opening the score after saving, but the "Arpeggio" items in the palette still look strange;


https://github.com/musescore/MuseScore/assets/120221700/0b48bf2a-9f07-40de-970a-38483dadded4
