### ISSUE TITLE
Falls, doits, etc. do not play correctly for electronic synths

### ISSUE THREAD

**Issue by mhogrefe** [musescore/MuseScore#19099]
### Issue type

General playback bug

### Bug description

Falls, doits, plops, scoops, and slides do not play correctly for several instruments in the "Electronic" category. I've tried the Square Synthesizer, Saw Synthesizer, and Sine Synthesizer. Regardless of which type of bend is used, there is no change in pitch at all, and the note plays for much longer than written, sometimes indefinitely. See the attached video.

In other bug reports related to bends I've seen people questioning whether a particular instrument needs bend support, so I'll provide justification in this case. I transcribe video game music, and bends occur often in it. For example, there should be a scoop in the Pulse staff in measure 4 of [this score](https://musescore.com/user/41962746/scores/10655725), but I have to use grace notes instead. This introduces an extra attack that shouldn't be there. 

Similar issues:
https://github.com/musescore/MuseScore/issues/14443
https://github.com/musescore/MuseScore/issues/17415

I don't think this is a dupe because this behavior is different than what's in those issues. They might have the same underlying causes though.

### Steps to reproduce

1. Create a score with a Square Synthesizer, Saw Synthesizer, or Sine Synthesizer instrument
2. Add a note
3. Attach a fall, doit, plop, scoop, or slide to the note
4. Play

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/641461/a54ce809-6b00-401b-adc7-41cfb59e325c

### MuseScore Version

OS: macOS 13.5, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

No.

### Operating system

macOS 13.5

### Additional context

This happens with MS Basic or with MuseSounds enabled. It sounds exactly the same either way, so I don't think these instruments have MuseSounds support.

**Comment by zacjansheski** [comment]
Hello!

Thank you for reporting!  The issue with the extended playback has been resolved in master build.  
https://github.com/musescore/MuseScore/actions/runs/5921454270

Full support of these techniques can be logged as a feature request.

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/18891
