### ISSUE TITLE
Range selection borders are sometimes too small

### ISSUE THREAD

**Issue by Fristover** [musescore/MuseScore#19097]
### Issue type

UI bug

### Bug description

If you right click an articulation, dynamic, or anything that's outside of the range selection borders you'll see different options, if you do it outside, MS thinks you didn't have any range selection and treats whatever you clicked as if nothing more is selected (that's my guess at least...)

This has been happening since ever I think, not sure if it's already reported but I couldn't find it here on github, feel free to close it if it's a duplicate hehe

### Steps to reproduce

1. Add a bunch of notes, dynamics and articulations, make sure notes a bit separated or above the staff
2. Select some notes, you'll see the selected area doesn't always cover every articulation and dynamic
3. Right click on an articulation/dynamic/whatever that's _outside_ the range borders, go to "select..." and you'll see "similar", "similar on this staff" and "more..." (you'll see the borders disappear too)
4. Do the same again, now selecting something _inside_ of the borders, you'll now see "similar in this range" and "more..." (and the borders won't disappear!!)

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/68985619/29dde17a-23a6-43d8-bbf7-b9c8e231c365)

![image](https://github.com/musescore/MuseScore/assets/68985619/ba6b4fda-aa3b-4a80-942d-9a7d3b8dae8d)

![image](https://github.com/musescore/MuseScore/assets/68985619/514070fa-7c6b-451c-9612-719a8c2933ff)

### MuseScore Version

4.1.1.232071203

### Regression

I don't know

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
For clarity/visibility

https://github.com/musescore/MuseScore/assets/69917893/c667869a-95e0-4134-950d-9d0b8b8c71af

**Comment by bkunda** [comment]
Just to be clear, I think the solution here should be that the selected elements outside of any highlighted box _behave_ as if they were inside the box. 

We _don't_ need to increase the visual size of the box to encompass all elements it contains.

**Comment by cbjeukendrup** [comment]
> We _don't_ need to increase the visual size of the box to encompass all elements it contains.

Whether we do this or not, we should at least do it consistently; currently, the box is _sometimes_ extended, and _sometimes_ not:
<img width="387" alt="Scherm­afbeelding 2023-09-10 om 01 25 28" src="https://github.com/musescore/MuseScore/assets/48658420/34d6707f-7e9e-4ee7-a252-cd41f39d28de">
<img width="387" alt="Scherm­afbeelding 2023-09-10 om 01 26 05" src="https://github.com/musescore/MuseScore/assets/48658420/2be71a7e-2399-4a1d-b9c1-ff7b87840b5b">
