### ISSUE TITLE
"This score has become corrupted" message when changing actual measure duration with opened parts

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#19092]
### Issue type

File corruption

### Bug description

Musescore shows "This score has become corrupted and contains errors" message if you change actual measure duration, then return back default values for that measure. This happens if part for that instrument is opened.

Affected versions (which I checked):
4.0.2
4.1.1
4.2.0 (master)

### Steps to reproduce

1. Create empty document (from Treble clef template)
2. Go to Parts -> Select and open Piano part
3. Go back to main score
4. Right click on any measure -> Measure properties - > Measure duration -> Set Actual: 2/8 - > OK
5. Repeat step 4, but set value back to 4/4 - > Ok
6. If you try to save file, Musescore will show message "This score has become corrupted and contains errors"

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/190833d4-e1a0-49e5-9771-94437401bcc6

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232300304, revision: github-musescore-musescore-741c7e6

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009

**Comment by bkunda** [comment]
Does the anomoly in the part persist when the part is closed and reopened? 
(@zacjansheski)

**Comment by zacjansheski** [comment]
@bkunda the score remains corrupted and the measure has odd rest markings in both score and part


https://github.com/musescore/MuseScore/assets/69917893/1db66d1e-9c2a-49cd-8353-4a4ad2c7561e

**Comment by sammik** [comment]
I made fix, see #19492

**Comment by Jojo-Schmitz** [comment]
Apparently Mu3 has the same issue.
