### ISSUE TITLE
[TIED NOTES] Tied notes from first volta continues to be sustained in the second volta

### ISSUE THREAD

**Issue by Attackoh** [musescore/MuseScore#19104]
### Issue type

General playback bug

### Bug description

Notes that are tied to notes inside the first volta will continue to be played in the second volta.

### Steps to reproduce

1. Go to this score [Lake of eternal sleep.zip](https://github.com/musescore/MuseScore/files/12387339/Lake.of.eternal.sleep.zip)
2. Skip to 3:15. Notice bug.

This playback bug occurs in every instrument, copy and paste the F horn part to other instruments and same thing occurs.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/120669196/ecf8dae4-2af1-4b1c-b8ec-1e62f855974d

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10

**Comment by zacjansheski** [comment]
Minimal example:

https://github.com/musescore/MuseScore/assets/69917893/c959c51b-0621-459b-9e33-1ecbda82ecf8

[Tie+Volta.zip](https://github.com/musescore/MuseScore/files/12409967/Tie%2BVolta.zip)

**Comment by bkunda** [comment]
Will be important to stamp this one out!

**Comment by wizofaus** [comment]
Happy to have a look at this if you nobody else is - is it only MS Basic or Muse Sounds too?

**Comment by zacjansheski** [comment]
@wizofaus the issue occurs with both MS Basic and Muse Sounds

**Comment by wizofaus** [comment]
Thanks. Do you know if anyone has started looking at it?

**Comment by zacjansheski** [comment]
@RomanPudashkin have you started work on this one?

**Comment by RomanPudashkin** [comment]
@zacjansheski I'm not working on it, so @wizofaus you can try to fix it

**Comment by wizofaus** [comment]
Thanks, again, if you can assign it that'd be great.

**Comment by wizofaus** [comment]
Won't be trivial to fix, as the logic to determine playback duration with ties doesn't have ready access to whether it's doing it as part of a repeat or not, but will have a go.

**Comment by wizofaus** [comment]
Related, ties over barlines, which for the most part don't actually make sense:

![image](https://github.com/musescore/MuseScore/assets/5364225/ed456c0c-09ca-40c4-85fe-501718d3d113)

But in principle could (but don't play back "correctly"):

![image](https://github.com/musescore/MuseScore/assets/5364225/92c7705e-905f-44e7-8167-3af7070fc0fd)

**Comment by wizofaus** [comment]
Confirmed this is still happening in 4.4, and my PR still fixes the issue, but hasn't been reviewed yet (have resolved merge conflicts).
