### ISSUE TITLE
Parts Cue Size don't update 

### ISSUE THREAD

**Issue by amijaishalev** [musescore/MuseScore#19103]
### Issue type

Engraving bug

### Bug description

I updated cue size on the main score and opened the parts.
Cue size didn't update on the parts (which requieres to do it manually).
I closed the parts and re-toggled cue size then re-open parts, cue size is still not updated.

### Steps to reproduce

1. start new score and enter notes
2. Open parts
3. Select and change to cue size on the score
4. Go to part - cue size should not be updated

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

MacOS 13.4.1 (22F82)

### Additional context

OS: macOS 13.4, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

**Comment by oktophonie** [comment]
Covered by https://github.com/musescore/MuseScore/issues/16544. Closing as duplicate
