### ISSUE TITLE
MS4 score crashes program on playback and export (one score)

### ISSUE THREAD

**Issue by magataganm** [musescore/MuseScore#19117]
Crash or freeze

### Bug description

I can't seem to figure out what might be wrong with this score. When I load the score (attached) and playback, the application crashes at different locations towards the end of the score. If I try to export the score to MP3, it also crashes at different progress levels into the score. I have rebooted the machine and retried as well as tried it on different machines (W10 & W11) with no luck. I'm attaching the score in case someone can help.

Thanks!

### Steps to reproduce

Either playback or export to MP3
[Please see Issue on Forum and it's attached score](https://musescore.org/en/comment/1204630#comment-1204630) Issue type

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/108586064/a0aa7a1e-4d71-40b9-802b-a10767ae7386)

### MuseScore Version

v4.1.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

W10 & W11

### Additional context

Confirmed in 4.1.1 on Windows 11. But not in the latest development build, not on playback at least. But even there on MP3 export.

Crash happens in MuseSamplerCoreLib.dll

Last lines in the logs are

023-08-21T15:31:53.931 | DEBUG | 31424 |  | operator : Deselected preset 'Woodblock' from channel 0
2023-08-21T15:31:53.931 | DEBUG | 31424 |  | operator : Unloading sample 'High Woodblock'
2023-08-21T15:31:53.965 | INFO  | 31424 | FluidSynth | addSoundFonts: success load soundfont: C:/Users/Jojo/Documents/GitHub/MuseScore/msvc.install_x64/sound/MS Basic.sf3
2023-08-21T15:31:53.965 | DEBUG | 31424 |  | operator : Selected preset 'Woodblock' on channel 0
2023-08-21T15:31:53.967 | DEBUG | 31424 | MuseSamplerWrapper | setIsActive: Toggled playing status, isPlaying: 1
2023-08-21T15:31:53.968 | INFO  | 31424 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
2023-08-21T15:31:53.968 | DEBUG | 31424 | MuseSamplerWrapper | setIsActive: Toggled playing status, isPlaying: 1
2023-08-21T15:31:53.968 | INFO  | 31424 | MuseSamplerWrapper | flushSound: ALL NOTES OFF
2023-08-21T15:31:53.969 | DEBUG | 31424 | MuseSamplerWrapper | setIsActive: Toggled playing status, isPlaying: 1
2023-08-21T15:31:53.969 | INFO  | 31424 | MuseSamplerWrapper | flushSound: ALL NOTES OFF

---------------------------------------------------

from @DmitryArefiev : the issue **not so easy to reproduce**... Sometimes you should play score several times (from beginning to end) to get the crash 
Tested on Win10. Occurs in **4.2 master** and in **4.1.1/4.0.2**

**Comment by zacjansheski** [comment]
Crash confirmed on Windows only

Score attached

[GF Handel -- Precipitoso nel mar from Aci, Galatea e Polifemo (HWV 72 Act 1 No. 9) for String Trio (1).zip](https://github.com/musescore/MuseScore/files/12398210/GF.Handel.--.Precipitoso.nel.mar.from.Aci.Galatea.e.Polifemo.HWV.72.Act.1.No.9.for.String.Trio.1.zip)

**Comment by zacjansheski** [comment]
Crashes (playback and mp3 export) only occur with Muse Sounds activated

[HandelCrashes.zip](https://github.com/musescore/MuseScore/files/12398501/HandelCrashes.zip)

**Comment by RomanPudashkin** [comment]
It looks like this crash was introduced with an update of MuseSampler. @DmitryArefiev can reproduce it with 4.0.2. @iamtesch could you help with this issue? Thanks!

**Comment by magataganm** [comment]
> @DmitryArefiev @zacjansheski can we please double check whether this issue is still valid? (It's not clear to me which version of musesampler is the potential culprit here, but I half wonder whether any more recent updates to it have affected this issue).

I had long since forgotten about this issue (August 2023). I did try the score again just now and the export works fine.
