### ISSUE TITLE
Instrument muted after tied notes in repeats

### ISSUE THREAD

**Issue by ShibuyaCyana** [musescore/MuseScore#19119]
### Issue type

General playback bug

### Bug description

100% reproduce case provided.
A weird bug that make notes become (implicitly) muted after a pair of notes tied using a special method ~~at the start of~~(<- not necessary) in a repeating measure following a special repeat pattern.

### Steps to reproduce

1. write something like this using any instruments and any sound, including VSTi (fingering numbers are not required):
![image](https://github.com/musescore/MuseScore/assets/39703247/ffdf80de-c713-4afb-9902-1303c1516907)
2. delete note 2 then write an eighth note into that position (not necessarily a C);
3. selecting note 1, add a tie, then press play
4. every note becomes muted after the tie, including the following measure :)
5. notes will play again after repeat

P.S.
1. the 5th measure is not needed to reproduce this issue, but if you delete it make sure the score ends with a repeat sign.
2. except the 5th measure, it seems that every other measure and repeat sign is needed to reproduce this issue. more bars can be added, but not less
3. it won't work if you directly tie note 1 with note 2
4. in step 2, writing a quarter note or a half note will also takes effect
5. it reproduces when note 1 is a 16th note, but doesn't when it's a quarter note
6. notes will make sound again if selecting all note, untick 'play' then tick it again

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/39703247/a40fd4c0-6f05-4b77-992a-e756e05a6c7d

[mscz file here](https://github.com/musescore/MuseScore/files/12398612/example.zip) in case of in need

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

**Comment by MarcSabatella** [comment]
I can confirm.  It seems any edit operation that forces the playback info to be regenerated will fix it.  That includes save/reopen, so attaching a score won't really help.
