### ISSUE TITLE
[MU4 Task] Update 'Share on Audio.com' dialog

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#19115]
The 'Share to Audio.com' dialog will now have the same UX as the 'Publish to MuseScore.com' dialog. This means:
- Visibility will be turned into a dropdown - Public and Unlisted 
- 'Anyone will be able to listen to this audio' + 'Only people with a link can listen to this audio' text will be removed.
- When dialog triggers 2nd time after the first share, 2 radio buttons will appear: 
      - Replacing the existing audio
      - Upload as new audio file

Note:      
When there is an online audio file to replace, the name and visibility displayed in MuseScore are taken from the online file (the user might have edited these settings on audio.com since the dialog was lasted opened).
The online audio file must belong to the logged in user. If it is someone else's audio then the radio buttons do not appear.

New design:
1st share dialog
<img width="591" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/def1d548-4911-433f-ba76-1dc773dfdec1">

2nd share dialog
<img width="581" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/7468d5cc-93f9-4882-8247-5c24aafdbb88">

**Comment by shoogle** [comment]
To enable replacing audio, the audio.com audio ID should be stored in _File > Project properties_ like this:

![image](https://github.com/musescore/MuseScore/assets/11011881/0efd4736-29f8-4294-b6bf-f6a3e4e03bb9)

Note: It wouldn't be accurate to label this field 'audio source'. The score is the source for the audio, not the other way around.

The audio.com developers tell me they will implement redirects for URLs like this:
- From: https://audio.com/audio/1774493136793930 (URL based on audio ID)
- To: https://audio.com/shoogle/audio/test (the corresponding permalink)

But that's just a nicety for users who copy and paste the URL. We shouldn't rely on this mechanism in the code. We should take the audio ID off the end of the URL and use it in API requests like we do for MuseScore.com.
