### ISSUE TITLE
Transposed chord symbols don't play correctly

### ISSUE THREAD

**Issue by adazem009** [musescore/MuseScore#19128]
### Issue type

General playback bug

### Bug description

Chord symbols should play in the correct octave after transposing the part.

For example, when you transpose a part 2 octaves down, chords play 2 octaves lower. Transposition should apply to chords, but the notes should be automatically transposed (by octaves) so that they're not too low or too high.

Playing chords too low also causes the violins from Muse Sounds not to play some notes at all.

### Steps to reproduce

1. Create a chord symbol.
2. Transpose the part 2 octaves down.
3. Make sure concert pitch is disabled.
4. Play the score.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/68537469/ad32242f-0db0-4c9a-a99d-14af00a362ef

### MuseScore Version

4.1.1

### Regression

No.

### Operating system

Windows, Linux, macOS

**Comment by MarcSabatella** [comment]
What *should* happen is that the transposition is applied to the TPC for the chord symbol to determine the correct pitch for the root, and then the chord voicing should be generated from that with no further transposition applied.
