### ISSUE TITLE
Accelerandos and Rits.

### ISSUE THREAD

**Issue by Beniegenie** [musescore/MuseScore#19135]
### Your idea

 Accelerandos and rits. should be able have their final tempo determined by a tempo mark at the end.

### Problem to be solved

 Accelerandos and rits. have to have their final tempo decided by a percentage in properties. It is a hassle to find the right percentage to get the right end tempo.

### Additional context

An a tempo mark would be very useful as well.

**Comment by mmeyn** [comment]
Looks like a duplicate of #18359.

**Comment by Beniegenie** [comment]
@mmeyn Apparently, it is.
