### ISSUE TITLE
[MU 4 Task] Playback button popup should hide irrelevant options

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#19152]
**Task Description**

Currently, the Playback button popup displays a row for every element that has playback properties, and rows are disabled for element types that are not in the current selection. See the screenshot below, where only a note is selected, but "Arpeggio", "Fermata", and more take up unnecessary space.
<img width="299" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/b1e85d4c-f3d8-4fdc-8421-e6784176bfe3">

Instead of disabling these rows, they should be hidden when the selection does not contain that element. So if only a note is selected, it will display as follows:
![image](https://github.com/musescore/MuseScore/assets/20806406/555a78be-570c-4a8d-a6a7-947821ef9cbd)

**Comment by DmitryArefiev** [comment]
Fixed in #19212
