### ISSUE TITLE
German translation: “major” should be “groß” or “Dur” depending on context

### ISSUE THREAD

**Issue by mmeyn** [musescore/MuseScore#19153]
### Issue type

UI bug

### Bug description

When you specify the interval of an ornament like a turn, you can choose between minor second and major second which are correctly translated as “kleine Sekunde” and “große Sekunde”:
![Bildschirmfoto vom 2023-08-24 14-17-00](https://github.com/musescore/MuseScore/assets/7814361/02076bfd-7896-4304-8d1c-7f8c565a2a99)
For trills, the selection of the interval is done in two steps because larger intervals (not only seconds) are possible. In this case, “minor” and “major” are incorrectly translated as “Moll” and “Dur” which are the terms for minor and major _chords_ and _key signatures_ but not for minor and major _intervals_:
![Bildschirmfoto vom 2023-08-24 14-17-37](https://github.com/musescore/MuseScore/assets/7814361/338afe2b-41b6-4ed0-a475-399911a750ad)

### Steps to reproduce

1. Set language to german.
2. Input a note with a trill.
3. Edit the trill interval in the properties (“Eigenschaften”) tab.

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

–

### Additional context

This is done differently for instrument transposition in the instrument/staff properties dialog where all the intervals are in one big list:
![Bildschirmfoto vom 2023-08-24 14-22-07](https://github.com/musescore/MuseScore/assets/7814361/4ffb48d9-798d-4365-9df0-4e92c9bc5061)

The strings which this issue is about are numbers 3483 and 3484 on Transifex. As @Jojo-Schmitz said the problem is that there can be only one translation in each context (here `inspector`). The strings “Minor” and “Major” live also in the context `project/newscore` (numbers 4908 and 4909) where they also stand for key signatures.

**Comment by en-programmerare** [comment]
Swedish suffers from the same issue.

**Comment by Jojo-Schmitz** [comment]
My PR should fix that too
