### ISSUE TITLE
[Musicxml export] - Missing line end

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#19165]
### Issue type

Other type of issue

### Bug description

[22.zip](https://github.com/musescore/MuseScore/files/12436696/22.zip)

### Steps to reproduce
1. Export the attached MuseScore File to MusicXML
2. Open the MusicXML file in MuseScore
3. Please see bar 248, the poco rit line has its end missing. If this is really a visible line, both the beginning and end should be exported.

### MuseScore Version

4.1

### Regression

No.

### Operating system

All

**Comment by rettinghaus** [comment]
fix included in #19132

**Comment by Jojo-Schmitz** [comment]
This is a regression vs Mu3, in the sense that gradual tempo changes just don't exist there.
IOW: nothing to port back to Mu3 ;-)
