### ISSUE TITLE
 "corrupted size vs. prev_size".

### ISSUE THREAD

**Issue by z46-dev** [musescore/MuseScore#19163]
### Issue type

Muse Sounds crash

### Bug description

Working on a score transcription of some star wars stuff, mu4 keeps crashing! I have seen zero corruption notifications, yet there are some issues in it!

### Steps to reproduce

1. Open up the score
2. Select a note in the Piccolo part of m26 (I usually selected the rest)
3. If the application has not crashed, start the playback, then stop it a few measures after.

*It's worth noting that I am using Muse Sounds for everything here!

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/45317380/360f2fc6-f7b0-497a-8a6f-fcbe8d0a28e0

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Windows 11, Ubuntu Desktop LTS

### Additional context

[The Battle of Crait.zip](https://github.com/musescore/MuseScore/files/12433517/The.Battle.of.Crait.zip)

**Comment by MarcSabatella** [comment]
I can reproduce this without much effort, selecting things in bar 26 on and off.  But, so far I can't if switch to MS Basic.  The log message "corrupted size vs. prev_size" seems to be a malloc thing.

**Comment by cbjeukendrup** [comment]
This seems a Muse Sounds crash indeed
<img width="1276" alt="Scherm­afbeelding 2023-08-25 om 11 58 30" src="https://github.com/musescore/MuseScore/assets/48658420/dda1af34-c6cb-458a-9995-d2d716bacf6a">

**Comment by zacjansheski** [comment]
We are no longer able to reproduce this.  On 3.2 or master
Feel free to open another issue if new evidence arises thank you!
