### ISSUE TITLE
Rests missing in parts for second voice

### ISSUE THREAD

**Issue by Mansent** [musescore/MuseScore#19182]
### Issue type

Choose option...

### Steps to reproduce

1. Create this score:
![Bildschirmfoto vom 2023-08-26 19-57-12](https://github.com/musescore/MuseScore/assets/23057910/12bdb60f-6084-4073-8240-302fdfb55a4b)
2. Delete the rest in second voice
3. Open the part for this instrument
4. Only display 2nd voice in the part
You get this:
![Bildschirmfoto vom 2023-08-26 20-00-17](https://github.com/musescore/MuseScore/assets/23057910/f75b1c80-2f18-4feb-bb29-0e736f0e4253)
I would expect that since the first voice is missing, the rests are properly displayed

### Screenshots/Screen recordings

Here the practical example how i stumbled on this to show why it makes sense to fix this. I have an orchestral score with this flute line:
![Bildschirmfoto vom 2023-08-26 19-46-20](https://github.com/musescore/MuseScore/assets/23057910/b8fc5252-d3dd-40a3-ac42-4251504d6c5a)

In orchestral scores, it is common practise to leave out the rests for the second voice. However if I generate part for the second flute, it looks like this:
![Bildschirmfoto vom 2023-08-26 19-52-10](https://github.com/musescore/MuseScore/assets/23057910/34f1799f-b337-422f-b1f7-3aa03a61880e)

This is not useful to the flute player. In this example I also get this ugly whole note rest which doesn't belong there.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Choose option...

### Operating system

Linux Mint 21.1, Arch.: x86_64

**Comment by cbjeukendrup** [comment]
In a way, related to https://github.com/musescore/MuseScore/issues/15616
