### ISSUE TITLE
Linked Staves in Parts: Changing the voice for a note doesn't work (when using Voices visible in the score feature)

### ISSUE THREAD

**Issue by Mansent** [musescore/MuseScore#19180]
### Issue type

Engraving bug

### Bug description

Here a musescore file, which demonstrates the problem in a minimal reproduction
[Bug2.zip](https://github.com/musescore/MuseScore/files/12446164/Bug2.zip)

### Steps to reproduce

1. Create a new score with just one instrument
2. Enter a chord with two notes in 1st voice
3. Open the part of the instrument
4. Create a linked stave in the instument tab
5. Configure: 1st stave only shows first voice, 2nd stave only second voice
6. Select one note in the chord
7. Press ctrl + alt + 2 to move it to second voice

Following problems occur:
- The note is still displayed in the first stave which should only show first voice
- If I go back to the full score, the note I changed to 2nd voice now is in the 3rd voice

### Screenshots/Screen recordings

This is my part, first stave shows only first voice, 2nd stave is a linked stave and shows only 2nd voice
![Bildschirmfoto vom 2023-08-26 19-24-16](https://github.com/musescore/MuseScore/assets/23057910/2529d86a-e94c-464c-b710-0eb56bbbc8e0)

Now I select the lower note and press ctrl + alt + 2 and get this
![Bildschirmfoto vom 2023-08-26 19-24-49](https://github.com/musescore/MuseScore/assets/23057910/38604901-e675-4aee-ba32-4e66f4dd47e3)
Suddenly the first stave shows a note in the 2nd voice - it is configured not to. 

Now I switch from the part back to the full score and suddenly the changed note is in 3rd voice 
![Bildschirmfoto vom 2023-08-26 19-25-10](https://github.com/musescore/MuseScore/assets/23057910/8ae96dc7-160e-4860-b50f-76e4bf1300a8)

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Linux Mint 21.1, Arch.: x86_64

### Additional context

Also see https://github.com/musescore/MuseScore/issues/19180#issuecomment-1699212682

**Comment by DmitryArefiev** [comment]
@bkunda The issue is not only with linked stave. The problem here is because **Voices visible in the score** option doesn't work properly in part. If you show only 3rd and 4th voices, it makes visible notes in **3rd** and **4th** voices only, but **when selected, they are detected as 1st and 2nd**


https://github.com/musescore/MuseScore/assets/90187801/56723569-b919-43a9-9596-0ba3c87d423f
