### ISSUE TITLE
Crash on MusicXML import of score with marcato, tenuto and staccato in the same note

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#19186]
### Issue type

Crash or freeze

### Bug description

Importing a MusicXML previously exported from MuseScore causes crash

### Steps to reproduce

1. Take the score (mscz) from https://musescore.org/en/node/354050 and open it in MuseScore
2. Export it as MusicXML
3. Import it in any Mu4 version

Or
1. Take the MusicXML file (mxl) from https://musescore.org/en/node/354050 and import it in and Mu4 version

Result in either case:

Crash!

(Instead of taking the files from musescore.org you can take them from the attached)
[music388-389.zip](https://github.com/musescore/MuseScore/files/12447969/music388-389.zip)

### MuseScore Version

4.1.1, should be in 4.1.0 too, Happens in 3.7 also

### Regression

Yes, this used to work in MuseScore 3.x and 4.0 and now is broken

### Operating system

Windows 11

### Additional context

Suspected code came in via #16828, as far as I can tell the crash happens in `bool MusicXMLParserNotations::skipCombine(const Notation& n1, const Notation& n2)`, in any of the first 3 statements

```cpp
bool MusicXMLParserNotations::skipCombine(const Notation& n1, const Notation& n2)
      {
      bool placementsSpecifiedAndDifferent = n1.attribute("placement") != "" &&
                                             n2.attribute("placement") != "" &&
                                             n1.attribute("placement") != n2.attribute("placement");
      bool upMarcatoDownOther = (n1.name() == "strong-accent" && n1.attribute("type") == "up" &&
                                n2.attribute("placement") == "below") || 
                                (n2.name() == "strong-accent" && n2.attribute("type") == "up" &&
                                n1.attribute("placement") == "below");
      bool downMarcatoUpOther = (n1.name() == "strong-accent" && n1.attribute("type") == "down" &&
                                n2.attribute("placement") == "above") || 
                                (n2.name() == "strong-accent" && n2.attribute("type") == "down" &&
                                n1.attribute("placement") == "above");
      bool slurEndpoint = _slurStart || _slurStop;
      return placementsSpecifiedAndDifferent || upMarcatoDownOther || downMarcatoUpOther || slurEndpoint;
      }
```
Apparently MuseScore is trying to combine Marcato, Tenuto and Staccato rather than just 2 of them (Marcato and Staccato or Marcato and Tenuto)

**Comment by Jojo-Schmitz** [comment]
Also a regression vs. 4.0, apparently

**Comment by rettinghaus** [comment]
Also happens with the combination of `<accent/>`, `<staccato/>` and `<strong-accent/>`.

**Comment by Jojo-Schmitz** [comment]
Yes, any combination of 3. Or more than 2?
