### ISSUE TITLE
Rit. that doesn't span full bar not properly displayed in parts

### ISSUE THREAD

**Issue by Mansent** [musescore/MuseScore#19181]
### Issue type

Engraving bug

### Steps to reproduce

1. Create a score with two instruments
2. fill the first bar of the first instrument with notes
3. select the second half of the bar and add a rit.
 
![Bildschirmfoto vom 2023-08-26 19-34-45](https://github.com/musescore/MuseScore/assets/23057910/cbe42a95-981e-41f8-abfd-3a25b780d21c)

Now open the part for the second instrument. The rit is displayed incorrectly.

![Bildschirmfoto vom 2023-08-26 19-35-17](https://github.com/musescore/MuseScore/assets/23057910/ad42bbc4-11e8-4ec0-b01d-cbbaca22d6f6)

If you have an actual score with more music in it, it looks even worse

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Linux Mint 21.1, Arch.: x86_64

**Comment by mercuree** [comment]
Maybe related #18644

**Comment by cbjeukendrup** [comment]
And #16796. I think we can close this issue as a duplicate, since it is sufficiently covered by #16796 and #18644. Will be fixed in 4.2/4.3.
