### ISSUE TITLE
Caesuras playback inconsistently

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#19194]
### Issue type

General playback bug

### Bug description

Caesuras playback inconsistently.  In following example, each eighth note should play followed by a 2 second (default) caesura between each.  What happens is the first 8 notes play without pause, and then the passage plays correctly.

### Steps to reproduce

1. Open MuseScore and start a new score
2. Create a scale of eighth notes and place a caesura after each (see example).
3. Press playback button
4. When the file is closed and then re-opened, the playback seems to be correct.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/137847641/1fe998f6-6096-4df4-97c0-c40f21ba5743)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232390501, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10 Home 10.0.19045 Build 19045

### Additional context

Seems to happen with both MuseSounds and MS Basic.

**Comment by seisfeldt** [comment]
[incorrect ceasura playback.zip](https://github.com/musescore/MuseScore/files/12449331/incorrect.ceasura.playback.zip)

**Comment by MarcSabatella** [comment]
Indeed, this is a known issue - see https://github.com/musescore/MuseScore/issues/15305

**Comment by DmitryArefiev** [comment]
> Indeed, this is a known issue - see #15305

Thanks! Closing as dupe
