### ISSUE TITLE
Extend range of violoncello sound in Muse Sound

### ISSUE THREAD

**Issue by luis-j** [musescore/MuseScore#19190]
### Your idea

Extend the range of the violoncello sound in Muse Sound a 12th upwards. 

### Problem to be solved

The Muse Sound violoncello sound only reaches G5, which was considered safe for orchestral parts in 19 and early 20 century orchestration, but doesn't cover solo parts in more recent music. This is a random list of pieces for string quartet or solo cello, written in the last 60 years by some of the leading composers of the last century, with their top notes:

Luciano Berio - Sincronie for String Quartet (1964) → Bb5
https://youtu.be/3vFNC2L1xTM?si=mAitNJlOJ3QPvDqb&t=988

Luciano Berio - Sequenza XIVa, for solo cello (2002) → B5
https://youtu.be/zOmuji8xM24?si=z6pVOw8g7P_vNv_x&t=665

György Ligeti - String Quartet Nº 2 (1968) → C#6
https://youtu.be/rMd6EEqukWo?si=5g5xJqSTgHstZSTh&t=703

Brian Ferneyhough - String Quartet No. 2 (1979/80) → D6
https://youtu.be/p8RTPYaWXj8?si=tqSWdKll49cMqZN1&t=399

Akira Nishimura - String Quartet Nº 2 "Pulse of the Lights" (1992) → Eb6
https://youtu.be/EZecL3Fmqe8?si=9eLYVFDP36WAgd60&t=270

Witold Lutosławski, String Quartet (1964) → Bb6
https://youtu.be/483BhgffOO0?si=RNlncg28fnSQVHpJ&t=1307

Georg Friedrich Haas - AUS.WEG (2010) → B6
https://youtu.be/KoFfArXdgsc?si=uGr-ak5I0FXTm89s&t=300

**Comment by mmeyn** [comment]
Also, Elgar’s cello concerto goes up to E7. That’s about where the fingerboards of most cellos end.
https://youtu.be/VoNVKgZ0D3U&t=160

**Comment by mmeyn** [comment]
Other, more often played pieces that go above G6, that came to my mind without long research are
- Haydn cello concerto C major → at least C6 (solo cello)
- Shostakovich 5th symphony → A5 (tutti)

I think some of the pieces mentioned by @luis-j use flageolet. Currently, flageolet stops at about F6.
- Mahler 1st symphony → A6 (tutti, flageolet)
- Atterberg 3rd symphony → B6 (solo, flageolet)

**Comment by Fristover** [comment]
Related to ( #16244), but with valuable info here

**Comment by DaddyLudwig** [comment]
Beethoven's Scottish Songs go up to at least C6 in the cello part.

**Comment by luis-j** [comment]
None of the examples I cited are indicated as flageolet (I found several, by the way).
In any case, I think the cello sound should extend up to E6.

**Comment by luis-j** [comment]
Excuse me, @mmeyn , you said: "currently, flageolet stops at about F6." How do you access those sounds? I tried bot the text "harmonics" and the small circle in articulations, but I only get up to G5, like in modo ordinario.

**Comment by mmeyn** [comment]
@luis-j You are right, the pitches you named are reached without flageolet. I must admit I had just a brief look and saw a lot of flageolets. The only piece where I had a closer look was the one by Haas. And that has a flageolet C7. I did not look further but the B6 is ordinario.

I get the correct flageolet sound with current Muse Sounds and MuseScore 4.1.1. I didn’t manage to include the sound in the screen recording so you have to believe me but here you can see how I input the flageolets:

https://github.com/musescore/MuseScore/assets/7814361/f683ef83-bd63-4633-85b4-19e2a3b8e224

**Comment by cbjeukendrup** [comment]
Combined into #16244
