### ISSUE TITLE
Ritenuto and Accelerando don't end

### ISSUE THREAD

**Issue by benwaffle** [musescore/MuseScore#19192]
### Issue type

General playback bug

### Bug description

If I add a ritenuto or accelerando marking to my piano score, during playback it will start slowing down/speeding up correctly, but the tempo never reverts to the original tempo after the marking. It stays too fast/slow.

This happens with MuseSounds and with MS Basic. Adjusting the length of the rit/accel doesn't change anything.

### Steps to reproduce

1. Write some notes
2. Add a ritenuto
3. Play it back
4. Notice that the music slows down permanently and never reverts to the original tempo

### Screenshots/Screen recordings

<img width="862" alt="Screenshot 2023-08-27 at 6 28 05 PM" src="https://github.com/musescore/MuseScore/assets/1713819/4f937446-925f-4237-ac0c-109d1fa2f6c3">

### MuseScore Version

OS: macOS 13.5, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

macOS ventura 13.5.1

### Additional context

See measure 60

[hw62.mscz.zip](https://github.com/musescore/MuseScore/files/12448951/hw62.mscz.zip)

**Comment by DaddyLudwig** [comment]
That rit. text is ritardando which is a long term slowing down of tempo. Accelerando likewise is long term speeding up unless immediately followed by a Tempo or Tempo I or whatever. There are no markings in MuseScore that are "Gradual change to x and then immediately a Tempo", you have to put the a Tempo in yourself using tempo text.

**Comment by DmitryArefiev** [comment]
@DaddyLudwig Thanks for explanation!

@benwaffle Yes, it **works as expected**. If you want to revert/change tempo at the end of rit line you should specify it with specific tempo mark

**Comment by benwaffle** [comment]
Thanks, got it
