### ISSUE TITLE
Trill lines stop playing through multi-measure ties

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#19195]
### Issue type

General playback bug

### Bug description

Single trill lines placed over notes that are tied across several measures stop playing (except for the first and last measures of the trilled ties).  A trill lines stretched over multiple tied measures plays okay.
See image below and sample file attached.

### Steps to reproduce

1. Create several measures of the same note.
2. Tie all the notes together.
3. Create a trill line to fill each measure.
4. Playback stops in middle measures (between first and last)

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/137847641/12e81468-e0f3-44c5-9e7c-8ffb06937a56)
[incorrect trill playback.zip](https://github.com/musescore/MuseScore/files/12449401/incorrect.trill.playback.zip)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232390501, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10 Home 10.0.19045 Build 19045

**Comment by DaddyLudwig** [comment]
Related https://github.com/musescore/MuseScore/issues/19029
