### ISSUE TITLE
Click on "Instrument name" > "Style" opens wrong option menu

### ISSUE THREAD

**Issue by Aurivox** [musescore/MuseScore#19203]
### Issue type

UI bug

### Bug description

A click on properties > instrument names > styles opens the "tabulator styles" option menu, but should open text styles > instrument names (long or short). Tried with several scores

### Steps to reproduce

1. click on instrument name (short or long) 
2. go on property panel on side
3. click on instrument names/ style properties.
4. style option menu is opening with "tabulatur styles"

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/103463374/b238a007-9b77-4b68-ab93-0563111a7674

### MuseScore Version

OS: macOS 13.4, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

13.4.1 (c) (22F770820d)

**Comment by DmitryArefiev** [comment]
Fixed in #Implemented in #19267
