### ISSUE TITLE
[MU 4 Task] Make dynamics and hairpins affect note velocity

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#19207]
**Task description**
Dynamics and hairpins currently control playback loudness in VST/MS Basic instruments by changing volume. Instead, dynamics and hairpins should affect the velocity parameter of notes.

This change is necessary to implement forthcoming automation features.

**Comment by DmitryArefiev** [comment]
Implemented partially in #22953 for not SND instruments (such as Piano, and see case in #13877 ) for MS Basic and VST. 

For **VST**, it depends on instrument you select in MuseScore. 
- If to use **not SND** instruments  (such as Piano, Guitar, Harp), dynamics and hairpins will affect the velocity parameter of notes.
- If to use **SND** instruments (such as Flute, Violin) it will work like in master (dynamics and hairpins control loudness by changing volume)
