### ISSUE TITLE
Hidden rests in tablature affect staff/tab spacing; they should have no effect

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#19204]
### Issue type

Engraving bug

### Bug description

If __Show rests__ is checked in Staff/Part properties > Advanced style properties > Note values, the hidden rests should have no affect on the grand staff distance (i.e. space between the staff and its tablature).

However, this is not the case. Hidden rests can still affect staff to tablature spacing, resulting in extra-large gaps between staves.

### Steps to reproduce

1. Open the attached MS4 score. 
[invisible_rest_issue.zip](https://github.com/musescore/MuseScore/files/12456898/invisible_rest_issue.zip)
2. Note the space between the staff and its paired tablature, which is larger than it should be.
3. In Staff/Part properties > Advanced style properties > Note values, check **Show rests**.

RESULT: The hidden rests are revealed and are evidently the cause of the extra space.

4. Make the rests invisible (V).

RESULT: Now the staff/tab spacing is correct.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by oktophonie** [comment]
See also https://github.com/musescore/MuseScore/issues/19850
