### ISSUE TITLE
Updating scores on Musescore.com fails.

### ISSUE THREAD

**Issue by RexDjere** [musescore/MuseScore#19219]
### Issue type

Other type of issue

### Bug description

I noticed this issue yesterday: updating scores on Musescore.com silently fails. The process looks like normal, but the score remains the old version after the process is complete. This is a re-curring bug, I have had it happen to me in the past.

### Steps to reproduce

1. Select a score on MuseScore.com and select " Update this score" from the right-hand drop down menu.
2. In the top section, select "Replace file" and choose an updated MuseScore file on your local computer.
3. Hit the bottom "Save" button.

MuseScore.com will look like it's going through the normal processes, but the score is never actually updated.

### Screenshots/Screen recordings

N/A

### MuseScore Version

4.1.1.232071203 Revision e4d1ddf

### Regression

I don't know

### Operating system

Pop!OS 22.04

### Additional context

N/A

**Comment by cbjeukendrup** [comment]
Does this happen with one specific score, or with all scores? 
And do you know when was the last time that it worked correctly? 

(We'd need to figure out if this is a problem in the desktop app or on the .com side...)

**Comment by bkunda** [comment]
Confirmed, it is an issue on the musescore.com side. 

Another team is now working on resolving this problem, so we can close this here.

**Comment by RexDjere** [comment]
@bkunda Thank you and thank you and the team for MuseScore 4: it's excellent!!!!!
