### ISSUE TITLE
MS4.1.1 Crashes when accidentally typing a large number into time signature

### ISSUE THREAD

**Issue by ironmatic1** [musescore/MuseScore#19224]
### Issue type

Crash or freeze

### Bug description

Opened and tried typing in 12/8 but didn't delete the 4, making the value 41, and it crashed. Tried again with several numbers.

### Steps to reproduce

1. Open a score
2. Open Time signatures in palettes and select Create time signature
3. Input any large number

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/143594534/c5be3c62-f5f3-451e-8ae0-068cb4e50330)

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
No crash in 3.6.2, so a regression (there's a hang though, once you go to 4 digits)

**Comment by Jojo-Schmitz** [comment]
No crash in 4.0.2 either /but the same hang when going 4 digits)

Actually I can't reproduce it with 4.1.1, no crash (just that hand mentioned above

**Comment by Jojo-Schmitz** [comment]
To prevent the freeze I guess there should be some kind of upper limit this dialog accepts?

**Comment by Jojo-Schmitz** [comment]
It is basically a matter of patience, just wait long enough and even 4000/4 is working i.e. returning from the "freeze".
May of course depend on how powerfull the CPU is.
