### ISSUE TITLE
After connecting a new output device, playback is in the wrong pitch

### ISSUE THREAD

**Issue by DomantasMi9** [musescore/MuseScore#19223]
### Issue type

General playback bug

### Bug description

When I connect a new output device, and play the score, it plays it in the wrong pitch.

### Steps to reproduce

1. Go to any score
2. See if it plays normally (the right pitch)
3. Connect a new output device (for me the bug works with bluetooth headphones)
4. Play the score (it should play the wrong pitch)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/103833783/b91c57d4-ed4f-45f4-8d54-5be01912fe97

In that moment, I connected my headphones via Bluetooth.

### MuseScore Version

MuseScore 4.1.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

This bug works on MS Basi and Musesounds. About VST I'm not sure, I don't use it.

**Comment by DmitryArefiev** [comment]
@MarcSabatella Thanks!

Yes, it's duplicate. Closing
