### ISSUE TITLE
[MU4 Task] Preferences changes

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#19227]
Due to adding a new setting related to a new audio.com dialog [Github task to be made yet] (Under Save & publish > Publish to MuseScore.com), We decided to change some things around in Preferences. Here as it follows:

<img width="666" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/e66f5868-5ef3-46e5-a7b0-f22561d69dc8">
<img width="552" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/1e447f32-7894-4cf2-9234-c85bf43b2897">
<img width="579" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/42a09aa0-b436-4f38-a93d-8bf8c255ca6e">

**Comment by bkunda** [comment]
Thanks @jessjwilliamson.

I didn't think this task needed so many assignees, but for the sake of monitoring, I'll add here:
@avvvvve @shoogle @RomanPudashkin
