### ISSUE TITLE
Audio Playback Stops Playing Randomly

### ISSUE THREAD

**Issue by JBran05** [musescore/MuseScore#19264]
### Issue type

General playback bug

### Bug description

Sometimes when I change a rhythm or a note for a part, when I play back the audio that part will then cease playing at the adjustment I made. Usually the audio will come back later in the part but will still be missing no matter how many times you play the bugged part back. The only way to fix this seems to be to cut and paste the part back into itself or restarting Musescore. Instruments I have experienced this with is all saxes and the drumset but those are the only ones I have used since this issue arose.

### Steps to reproduce

Legit no clue

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/143971291/ef5e1669-e9a9-43fc-8ad3-5a62d7559e6a

### MuseScore Version

4.1.1.23071203

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS Catalina 10.15.7

### Additional context

MS Basic

**Comment by JBran05** [comment]
Same thing just happened when I changed the amount of times of the barline from 2 to 3. Audio cuts out randomly for no reason during the repeats.

**Comment by MarcSabatella** [comment]
The temporary glitch (fixes itself on next regeneration of playback info) when changing repeat count is already know - see for example https://github.com/musescore/MuseScore/issues/15112 and https://github.com/musescore/MuseScore/issues/17986.  Hard to say if the original report is another case of this or something else, though.

**Comment by zacjansheski** [comment]
For reproducibility:
1. Open the attached file (Playback set to MS Basic)
2. Select the first note of the Baritone Sax Part
3. Press . (to make a dotted eighth note) and "R" to repeat it
4. Play, notice the drum set stops playing on the last bar the first time.


https://github.com/musescore/MuseScore/assets/69917893/d82d83b0-f414-4f0e-90eb-e8527f268949



[Reproducing_19264.mscz.zip](https://github.com/musescore/MuseScore/files/12526545/Reproducing_19264.mscz.zip)

**Comment by zacjansheski** [comment]
I wonder if it has to do with using R in repeated sections.  If I just use R on the first notes, all playback stops on the last bar.

Same issue with Muse Sounds


https://github.com/musescore/MuseScore/assets/69917893/e9beea4b-1fad-4bc2-ae49-ae97f7bee207

**Comment by zacjansheski** [comment]
Similar to https://github.com/musescore/MuseScore/issues/18253
