### ISSUE TITLE
Playing techniques (sul pont, pizz, tremolo, mute etc.) don't work on grace notes, arpeggios and tremolos 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19266]
### Issue type

General playback bug

### Bug description

The similar issues were logged for pizz+tremolo or pizz+arpeggio ( #16359 #14491 #19255).
The current issue created to cover all cases (all was mentioned in https://github.com/musescore/MuseScore/issues/16359#issuecomment-1429999900)

### Strings

**pizz, sul pont, harmonics, sul tasto, col legno** don't work on **tremolos, grace notes** and **arpeggios**

(sul pont, harmonics, sul tasto, col legno, tremolo playback text marks are implemented only in MuseSounds)

https://github.com/musescore/MuseScore/assets/90187801/212f91c4-90f4-47e9-ae58-363d3c64ff50

[pizz test.zip](https://github.com/musescore/MuseScore/files/12512480/pizz.test.zip)

### Brass

**mute** doesn't work on **tremolos, grace notes**
(reproducible only **MS Basic only**, because mute isn't implemented in MuseSounds #14191)

https://github.com/musescore/MuseScore/assets/90187801/0baacda5-5f3d-4cff-9686-baefc7748d71

[brass test.zip](https://github.com/musescore/MuseScore/files/12512571/brass.test.zip)

### MuseScore Version

4.2.0 master

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

all

### Additional context

#16359
#14491
#19255

**Comment by zacjansheski** [comment]
Similar: https://github.com/musescore/MuseScore/issues/14491

**Comment by DmitryArefiev** [comment]
Fixed in #20216
