### ISSUE TITLE
Style from right click menu shoud lead to Text Styles specific sub-section in Styles dialog (Instrument names, Composer, Subtitle etc.) 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19288]
### Issue type

UI bug

### Bug description

It was fixed for **Properties > Style settings** button in #19267, but **not** for **Style** option in **right click menu**

Style option was re-implemented in #19267

Also, [see comment](https://github.com/musescore/MuseScore/pull/19267#issuecomment-1705505219) about sub-sections of Text Styles

### Steps to reproduce

1. Select Instrument name
2. Right click menu
3. Select Style - it opens Style>Text styles>**Title** instead of Style>Text styles>**Instrument name (long)**

https://github.com/musescore/MuseScore/assets/90187801/1651fb21-d923-4cde-ac40-9d8a4f98b532

(the same with Composer, Subtitle etc, but most important is Instrument name issue)

### MuseScore Version

4.2 master

### Regression

No.

### Operating system

all

### Additional context

#19267 #19203 #18837

**Comment by DmitryArefiev** [comment]
Yes sure!

**Comment by vashutangri** [comment]
Hey, got bogged down by some work...unfortunately I wasn't able to reproduce the issue. Not getting the style option in the menu, using windows 11. Would appreciate any help! 

https://github.com/musescore/MuseScore/assets/89914873/fa4d64a2-4b4f-42ec-a09f-e5b266633fad

**Comment by re1san** [comment]
Hi, I would like to work on this issue ^^'

**Comment by DmitryArefiev** [comment]
Fixed in #20740
