### ISSUE TITLE
Adding tied notes in Note Input mode only works if note to tie from was entered in same input 'session'

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#19282]
### Issue type

Other type of issue

### Bug description

When adding notes in note input mode, the shortcut 'T' adds the previous chord to the current cursor position, and ties the previous chord to the new one.
This only works when the original chord was entered in the current input 'session', so if you come back to the position later and try to use the shortcut it doesn't do anything.

### Steps to reproduce

1. create a new score, and add a note
2. exit note input mode
3. select the rest just after the note
4. enter note input mode
5. press 'T'

### MuseScore Version

4.1.1

### Regression

No.

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
The tie command works according to what is selected.  So, don't select the rest - select the chord you want to tie.

I think perhaps you are getting confused by the fact that while entering notes, the cursor always advances just past the note you've entered, but the note you've just entered is selected - that's what make commands like tie, or the up/down arrows, work.

No doubt it's possible to create alternative designs, but anyhow, it's not a bug as is.

**Comment by XiaoMigros** [comment]
Hmm. I thought Mu4 was trying to phase out retroactively applying stuff to existing notes entered (see shortcuts Q and W), but I guess this isn't really a bug then, even if it feels like one
