### ISSUE TITLE
String data: "Always open" field cut off

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#19306]
### Issue type

UI bug

### Bug description

The "Always open" field in the String data dialog box (Staff/Part properties) is cut off:

![string_data](https://github.com/musescore/MuseScore/assets/87246583/3b186910-146b-4380-9299-eaba76872e73)

Widening the window makes no difference.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by Jojo-Schmitz** [comment]
A) check #19306
B) in 4.1 refresh your translations, I've 'translated' "Always open" to use 2 lines now, "Always\nopen" for en_US (and for de too)

**Comment by rgreen5** [comment]
> … in 4.1 refresh your translations, I've 'translated' "Always open" to use 2 lines now …

Yes. That did the trick.

**Comment by bkunda** [comment]
@Eism I think I specified something for this in the alternate strings tuning design. Will this be addressed in your current implementation?

**Comment by Eism** [comment]
@bkunda 
It is already fixed in #19307 and we can merge it into master(after testing) and I will rebase my branch

@abariska FYI

**Comment by abariska** [comment]
@Eism some edits needed in Jojo's fix. I commented in the PR

**Comment by abariska** [comment]
@Eism the fix https://github.com/musescore/MuseScore/pull/19307 is tested and can be merged
