### ISSUE TITLE
Trying to update my set's description (set 6378790), I keep getting "Page not found" error.

### ISSUE THREAD

**Issue by RexDjere** [musescore/MuseScore#19310]
### Issue type

Other type of issue

### Bug description

Tonight, I tried to update this set's description by adding a link to my to my GitHub page:
https://musescore.com/user/18100066/sets/6378790

The link that I tried to add was this one:
https://github.com/RexDjere/500_Daily_Saxophone_Etudes

The update failed. It took me to this page, which said "Page not found. Sorry about that":
https://musescore.com/score/collections/set/update-process?id=6378790

Interestingly, updating the description field in  my other set still works fine:
https://musescore.com/user/18100066/sets/6410209

My book (the paper version) already contains the URL of the 6378790 set page, so I would really rather not have to delete it and create a new one. Any assistance getting this one updating again would be greatly appreciated. Also, my book is coming out soon on Amazon, so I'll need to update the 6378790 set description to include a link to the book on Amazon.com. 

The last time I successfully was able to update the 6378790 set description was sometime yesterday. The failures just happened a few minutes ago.

### Steps to reproduce

1. I was logged into my MuseScore.com account.
2. I went to my set here: https://musescore.com/user/18100066/sets/6378790
3. I hit the "Update this set" button, and tried to add my GitHub page link to the set's description section.
4. The update failed. It took me to this page, which said "Page not found. Sorry about that":
https://musescore.com/score/collections/set/update-process?id=6378790

### MuseScore Version

4.1.1.232071203 Revision e4d1ddf

### Regression

Choose option...

### Operating system

Pop!OS 22.04

### Additional context

![Screenshot from 2023-09-07 00-23-13](https://github.com/musescore/MuseScore/assets/1860586/b2dc7171-32b2-4dad-8e4b-ac5daa434b76)

**Comment by shoogle** [comment]
Please use https://musescore.com/contact to report any problems you are having with MuseScore.com
