### ISSUE TITLE
Keep getting message about could not connect to musescore.com please check your interent.

### ISSUE THREAD

**Issue by George145s** [musescore/MuseScore#19318]
### Issue type

Cloud saving/loading issue

### Bug description

I am trying to open my compositions which are saved onto the msuescore cloud how ever keep getting this message.
I am a school student so went to my IT department who after some testing showed it was not being blocked by any of their servers or blockers. please can this be fixed.

### Steps to reproduce

open MS4
click open files 
opened the score 
score doesn't open and message apears 

### Screenshots/Screen recordings

<img width="1512" alt="Screenshot 2023-09-05 at 20 36 20" src="https://github.com/musescore/MuseScore/assets/132397130/9a03ba5d-4afb-46ce-b186-18850dc8d5fd">

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS

**Comment by shoogle** [comment]
Is this a school computer or a laptop you can take home? If it's a laptop, does it work when you connect it to a different network outside the school?

**Comment by George145s** [comment]
its my laptop and ive tryed it on several networks at home and school

**Comment by cbjeukendrup** [comment]
Could you please upload the log files from Diagnostic > "Save diagnostic files" (within MuseScore)?

**Comment by George145s** [comment]
Hi On 7 Sep 2023, at 16:49, Casper Jeukendrup ***@***.***> wrote:Could you please upload the log files from Diagnostic > "Save diagnostic files" (within MuseScore)?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by cbjeukendrup** [comment]
@George145s It looks like something went wrong with your latest comment. In my experience, replying via email often doesn't work well. Better to comment here on GitHub directly.

**Comment by MarcSabatella** [comment]
Also see https://musescore.org/en/node/354424, and be sure the scores are actually present on musescore.com.  That is, log on to the website with your web browser and be sure you see them.

**Comment by cbjeukendrup** [comment]
Logging out from the desktop app and logging in again might also help... 
(And in MuseScore 4.2, there will be more accurate error messages, so that we can hopefully get a better idea of what's the problem. But those diagnostic files would also be useful, if you could still upload those.)

**Comment by George145s** [comment]
i get a message saying something went wrong and we cant process that file?
