### ISSUE TITLE
[MusicXML Import] Crash if stop wavy-line is missing

### ISSUE THREAD

**Issue by tsjam23** [musescore/MuseScore#19322]
### Issue type

Crash or freeze

### Bug description

Musescore crashes if open broken musicxml file where `<wavy-line type="stop">` is missing.
I guess every `wavy-line` should have an ending pair:
```xml
<!-- start part-->
<notations>
   <ornaments>
      <trill-mark/>
      <wavy-line type="start" number="1" default-y="12.50"/>
   </ornaments>
</notations>
<!-- some other xml elements -->
<!-- end part -->
<notations>
   <ornaments>
      <wavy-line type="stop" number="1"/>
   </ornaments>
</notations>
```
But in case end part is missing, Musescore should't crash and somehow handle this situation: ignore ornament or display warning message
It was reported here https://musescore.org/en/node/354428

### Steps to reproduce

1. Download [attached sample](https://github.com/musescore/MuseScore/files/12553181/musicxml_open_crash.zip) or real score [here](https://musescore.org/en/node/354428)
2. Try to open it with Musescore 4.1.1

### MuseScore Version

MuseScore version (64-bit): 4.1.1

### Regression

I don't know

### Operating system

Windows 10

### Additional context

Sample file to reproduce crash 
[musicxml_open_crash.zip](https://github.com/musescore/MuseScore/files/12553181/musicxml_open_crash.zip)

**Comment by Jojo-Schmitz** [comment]
See #19329

**Comment by Jojo-Schmitz** [comment]
Apparently a regression vs. Mu3

**Comment by Jojo-Schmitz** [comment]
#18766 fixes this
