### ISSUE TITLE
Add tootip in Mixer to view truncated track name.

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#19338]
### Your idea

Add tooltip to view complete track name in Mixer.

### Problem to be solved

With a long track name, it's not easy to choose the right track to mute or unmute especially when there are a lot of instruments

Ex : 
Tuba Contrebasse en Sib
Tuba Contrebasse en Do
![image](https://github.com/musescore/MuseScore/assets/1835871/b7fc480e-2372-4d53-8289-155715a9ccbd)

**Comment by DeclanCUBuff** [comment]
I'm interested in taking this on if it's available

**Comment by dwlakes** [comment]
Can I try fixing this?

**Comment by cbjeukendrup** [comment]
Yes, but note that a pull request has already been created here: https://github.com/musescore/MuseScore/pull/19414
This pull request still needed some refinements though, and hasn't had any activity for several months, so it seems unlikely that that contributor will come back to make those refinements anytime soon.

So you can do two things: either start from scratch yourself, or take the code from that PR and make the necessary refinements.

**Comment by dwlakes** [comment]
Ok, I'll try working on it as soon as I can get MuseScore to compile and run :)
