### ISSUE TITLE
No fretboard diagram beyond 12th fret?

### ISSUE THREAD

**Issue by RudoSaxx** [musescore/MuseScore#19340]
### Issue type

UI bug

### Bug description

It seems not possible to define a fretboard diagram starting beyond the 12th fret,

### Steps to reproduce

1. Place a fretboard diagram from the palette to a guitar stave of the score.
2. Ensure that the Properties panel is open.
3. Ensure that the Settings tab is open.
4. Enter a fret number higher than 12, or try to get beyond 12 by pressing the up arrow.
5. See that any entered fret number higher than 12 will be overwritten by 12, or that you cannot get above 12 with the up arrow.

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11 Pro

### Additional context

Worked with the inspector in MS 3.6.2

**Comment by Jojo-Schmitz** [comment]
But in the fretboard diagram you can place fingerings in fret 17

Another new limit: you can't show more than 6 frets in Mu4, in Mu3 the limit was 99
The limit for the starting fret was 99 too
These old limits were not really reasonable though, way too hight

I guess 16 to 24 might be a good limit for the starting fret, 6 for the number of frests seems reasonable, not sure whether more are ever needed?

**Comment by cbjeukendrup** [comment]
I believe someone requested more frets here: #12781

I don't see a reason to put very tight limits on any of these controls, as long as the engraving engine handles it somewhat gracefully. I don't have a strong opinion about the exact numbers.

**Comment by RudoSaxx** [comment]
Jojo, do I take you right in that the fret number limit also occurs with your build? So you can place a finger in the 17th fret but you have to expand the visible frets to 6 for that, starting from the 12th, and that would be the absolute limit? If so, it is exactly what I experienced.  

But thank you for presenting a possible workaround for voicings up to the 17th. It is not nice because it needs more space for the diagram obviously, and might suffice sometimes but not at any occasion with a 24 fret guitar.

**Comment by RudoSaxx** [comment]
Casper, you are right, but #12781 relates to the number of visible frets while my post referred to the fret number (i.e., where the diagram begins). I would second that request either way though.

**Comment by Jojo-Schmitz** [comment]
Yes, that's what I meant
