### ISSUE TITLE
Tooltip for "Always open" in string data dialog

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#19362]
The string data dialog appears when you right-click on a guitar or lute staff, go to **Staff/part properties**, and click **Edit string data**.

![image](https://github.com/musescore/MuseScore/assets/11011881/e1daef23-78d4-47ef-8a1c-05506e199039)

@Jojo-Schmitz [suggests](https://github.com/musescore/MuseScore/pull/19307#issuecomment-1709887347)  adding a tooltip to explain what "Always open" means:

> Strings that are not over the fretboard, like on some Lutes.

We could add a title to the tooltip and give a [specific example](https://en.wikipedia.org/wiki/Theorbo):

> **Always open**
> A string that is not over the fretboard, as occurs on some lutes like the Theorbo.

Basic formatting is possible for tooltips even in these old dialogs. See **Format > Styles > Header, footer** for an example.

![image](https://github.com/musescore/MuseScore/assets/11011881/ea933554-993b-4caa-b42e-be5b8030658d)

**Comment by shoogle** [comment]
@Jojo-Schmitz, perhaps you could investigate whether it is possible to put a tooltip on the "Always open" heading text and also on the checkboxes? @bkunda will confirm the wording with you.

**Comment by bkunda** [comment]
Despite those old tooltips looking horrible (and one day, we shall replace them!), I think a tooltip in this case is sensible, especially given the meaning of that column label is so opaque. 

I'd suggest the tooltip should succinctly describe to the user what effect checking one of those boxes will actually have. 

Example: 

**Always open**
On tablature staves, fret positions other than "0" cannot be entered on strings marked 'always open'. Useful for instruments with strings that are not on the fretboard.

**Comment by shoogle** [comment]
@bkunda, did you intend to use double quotes for `“0”` and single quotes for `‘always open’`?

I think it would be useful to add "such as the theorbo" in case the user is curious and wants to learn more.

**Comment by Jojo-Schmitz** [comment]
or "such as some lutes"

**Comment by shoogle** [comment]
I don't think that is specific enough. You can search for pictures of lutes and not come up with any that have strings off the fretboard.

Actually, I think "torban" is the best instrument to use. Take a look at the picture! https://en.wikipedia.org/wiki/Torban

**Comment by shoogle** [comment]
Implemented in #19307
