### ISSUE TITLE
Second ending hairpin applies to first repeat

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#19365]
### Issue type

General playback bug

### Bug description

Reported here https://musescore.org/en/node/354538
>[Samwit](https://musescore.org/en/user/1861577) • Sep 10, 2023
>In a repeated section with a first and second ending, the hairpin in the second ending happens in the first measure of the repeat.
>
>For example, the attached score starts forte, but when the section repeats, a diminuendo to piano happens in the first measure, >even though that is only present in the second ending.

### Steps to reproduce

1. Create/Get score with two voltas (sample [repeat_dynamic_bug.mscz.zip](https://github.com/musescore/MuseScore/files/12578975/repeat_dynamic_bug.mscz.zip))
2. Add Hairpin (Decrescendo) to the second volta
3. Play score, first repeat gets quieter

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/7f2c726e-51bb-4082-8690-64f85a615200

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf
MuseScore version (64-bit): 4.2.0-232440304, revision: github-musescore-musescore-b4607ac
### Regression

I don't know

### Operating system

Windows 10

**Comment by zacjansheski** [comment]
I couldn't open the attached file, but I could reproduce.  It seems to be a MS Basic issue (or at least more noticeable with MS Basic

https://github.com/musescore/MuseScore/assets/69917893/6fadde22-4480-43bf-ab84-8d750339d3d0
[PlayBackBug.mscz.zip](https://github.com/musescore/MuseScore/files/12589274/PlayBackBug.mscz.zip)

**Comment by mercuree** [comment]
Can't reproduce anymore in MS 4.3.0 master. It works even in MS 4.2.0 release. Probably fixed
