### ISSUE TITLE
Left panel tabs ( Palettes / Instruments / Properties ) not showing

### ISSUE THREAD

**Issue by DanGioGames** [musescore/MuseScore#19364]
### Issue type

UI bug

### Bug description

- Left panel tabs ( Palettes / Instruments / Properties ) are not showing anymore when opening any score file, or creating a new score.
- Trying to access them with View/Palettes or /Instruments or /Properties crashes MuseScore without error message.
- Resetting parameters solves the problem.
- I cannot as for now reproduce the issue.
- I'm using MuseScore 4.1.1 on 2 different machines, Win10 computer and Win11 laptop. Issue appeared on the Win11 laptop.

First reported here : https://musescore.org/en/node/340052

### Steps to reproduce

I don't know.

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Windows 11

### Additional context

Diagnostic files, created *after* parameters reset :
[230911.zip](https://github.com/musescore/MuseScore/files/12580654/230911.zip)

**Comment by cbjeukendrup** [comment]
The crash logs can be exported using [MuseScore menu bar] > Diagnostic > Save diagnostic files.

**Comment by DanGioGames** [comment]
Thanks. I did that just now, I don't know if it's still valuable after I reset parameters... Here it is anyway.
[230911.zip](https://github.com/musescore/MuseScore/files/12580651/230911.zip)

**Comment by bkunda** [comment]
@DanGioGames do the panels return if you choose View > Restore the default layout? 
What about after a factory reset?

**Comment by DanGioGames** [comment]
> do the panels return if you choose View > Restore the default layout?

I didn't try it. If I manage to reproduce the bug, I'll try it.

> What about after a factory reset?

I think that's what I did, and it solved the problem :

<img width="473" alt="musescore4resetmenu" src="https://github.com/musescore/MuseScore/assets/75941029/020c1634-1df0-4f50-b7db-072023fdd2a4">

**Comment by DmitryArefiev** [comment]
> I think that's what I did, and it solved the problem. 

Oh great! If it will happen again please reopen the bug
