### ISSUE TITLE
Pressing the Home key while a slur/tie is selected causes crash

### ISSUE THREAD

**Issue by noname1477** [musescore/MuseScore#19368]
### Issue type

Crash or freeze

### Bug description

Happens with every type of slur I've tried (normal ones, grace note -> regular note, note -> pause etc.). Only happens with Pos1 specifically, other navigation keys work as expected. Also still crashes in the latest nightly build (as of 2023-09-11).

### Steps to reproduce

1. Add two notes, then add a slur.
2. Press Pos1.
3. The app closes.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 11

### Additional context

Example log file: [MuseScore_230911_231842.log](https://github.com/musescore/MuseScore/files/12580492/MuseScore_230911_231842.log)

**Comment by cbjeukendrup** [comment]
Is it right that "pos1" means the "Home" key? (I didn't know, I had to look it up 😄)

**Comment by noname1477** [comment]
I guess so, all my keyboards have always called it "Pos1". But then again, they're all German keyboards, so English ones might be different.

**Comment by Jojo-Schmitz** [comment]
Yes, the German Pos1 ley is the English Home key

**Comment by zacjansheski** [comment]
Reproduced with "home" key

In 4.0.2, the app doesn't crash, but it doesn't go to the beginning of the score either.
