### ISSUE TITLE
Discord rich presence integration

### ISSUE THREAD

**Issue by navickasm** [musescore/MuseScore#19369]
### Your idea

Allow the user to, when using Musescore, have specific information about what they are doing show up as a "now playing" (using the Game SDK) in Discord.

### Problem to be solved

Currently, a QML plugin has to be enabled which makes a file with score information AND a node.js server running on the user's computer that has to be enabled every single time MS is run, which reads this file and does the discord stuff.

It can be accessed at https://github.com/FireController1847/musescore-rich-presence.

### Additional context

Potential design ideas:
The LargeImage and LargeText would be the MS4 logo and "Musescore 4" respectively
The Details would have the status/page (i.e. "Main Menu", "Editing Plugins", "Working on Score [Name]", etc.)
The ActivityTimestamps would have a Start and the UNIX timestamp to show how much time is elapsed
State would alternate through different attributes of the score (omposer/arranger, number of parts, number of measures,  number of pages, etc)

If this feature is implemented, it would be nice to customize exactly what is shown (especially the different things that appear in the State), even if it's through a configuration file not accessible in the actual app to avoid unnecessary clutter that an average person wouldn't need.

There's an SDK guide for C++ but I don't use C++ that much so I'm not sure if it will be much help (I think it will though):
https://discord.com/developers/docs/game-sdk/sdk-starter-guide

Also a helpful reference image for where every thing goes:
![Screenshot 2023-09-11 173442](https://github.com/musescore/MuseScore/assets/112985139/45cf9b05-1ee9-422a-a80c-01788c510e0e)

**Comment by shoogle** [comment]
I haven't been able to find any licensing information for Discord's SDK, so I'm not sure whether we can use it in a [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) application like MuseScore.

**Comment by navickasm** [comment]
If this is still worth pursuing, I believe the only source of licensing information is the _Discord Developer Policy_, available [here](https://discord.com/developers/docs/policies-and-agreements/developer-terms-of-service).

**Comment by shoogle** [comment]
I think this kind of functionality is best left to a plugin or extension. Many users would object to having software broadcasting what they are doing, or even the capability of doing so. Those that do want this might ask for integrations with other clients besides Discord. And then there's the performance and maintenance burden to consider, all for negligible benefit.

All told, I don't think we want this in MuseScore's codebase, but if there's anything we can do to make it easier for plugin/extension developers to implement this then please let us know. On the face of it, something like this should be possible without requiring a separate Node.js server or having to run the plugin manually on each launch.
