### ISSUE TITLE
Tab and Enter keys won't work in add measure windows

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#19379]
### Issue type

UI bug

### Bug description

Tab and Enter(Keyboard and numpad) don't work in add Measure windows
Azerty French Keyboard

### Steps to reproduce

1 Open new score
2 Add measure : Ctrl+Ins
3 Need to use mouse, Tab and Enter won't work

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/issues/19379#issuecomment-1717466199

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232550304, revision: github-musescore-musescore-5ebfeb9

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by DmitryArefiev** [comment]
This is a regression comparing with **4.1.1**


https://github.com/musescore/MuseScore/assets/90187801/04228d37-243e-42f5-8493-2e70ad7e63e2

**Comment by zacjansheski** [comment]
Basically the same as https://github.com/musescore/MuseScore/issues/19279

Let's close this and refer to that.
