### ISSUE TITLE
Create key signatures panel  and Accidentals palette have missing symbols

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19374]
### Steps to reproduce

* Open Palettes > Key signatures > More
* Open Palettes > Accidentals

### Screenshots/Screen recordings

![Capture](https://github.com/musescore/MuseScore/assets/90187801/e7f6dfc1-0ed5-4451-8c7c-1bf9f1ad058d)

and https://github.com/musescore/MuseScore/issues/19374#issuecomment-1717711096

### MuseScore Version

4.2.0 master

### Regression

Yes, this used to work in **MuseScore 4.1.1**

### Operating system

Windows 10

**Comment by sammik** [comment]
Accidentals are missing in Palette too

![missing_accidentals](https://github.com/musescore/MuseScore/assets/1646034/1236b91b-1d37-47c7-8418-f5798762f127)

**Comment by DmitryArefiev** [comment]
Thanks! Will add it

**Comment by zacjansheski** [comment]
Bumped to P0 on account of the missing Accidentals from the main palette
