### ISSUE TITLE
Lines with symbols lose colors

### ISSUE THREAD

**Issue by rettinghaus** [musescore/MuseScore#19371]
### Issue type

Engraving bug

### Bug description

When coloring line elements with glyphs, the glyphs lose their color through saving and reopening. To be precise, the chosen color is still selected but is not shown in MuseScore. Only the drawn lines keep showing their color.

### Steps to reproduce

1. Add a line with symbols.
2. Assign color.
3. Save.
4. Open file.

### Screenshots/Screen recordings

<img width="393" alt="image" src="https://github.com/musescore/MuseScore/assets/7693447/7a62103b-639c-4fe4-816e-a5643565bd94">

after saving and reopening:
<img width="393" alt="image" src="https://github.com/musescore/MuseScore/assets/7693447/6faf832b-8538-4e12-851e-630c30a15f32">

### MuseScore Version

4.1.1. and Nightly

### Regression

I don't know

### Operating system

macOS 13.5

**Comment by Jojo-Schmitz** [comment]
Mu3 doesn't allow coloring those text elements (and the wiggly line, which is text under the covers) at all, resp. doesn't need a save/close/reopen to not show them anymore.

**Comment by rettinghaus** [comment]
Works nice, except for trills.

![image](https://github.com/musescore/MuseScore/assets/7693447/43efe061-819c-4032-8fde-2be66d9dbfcd)

**Comment by Jojo-Schmitz** [comment]
Indeed. Nor fpr other wavy lines
