### ISSUE TITLE
Instrument change from unpitched to pitched causes incorrect note placement in same measure

### ISSUE THREAD

**Issue by GabeS573** [musescore/MuseScore#19396]
### Issue type

Engraving bug

### Bug description

When a pitched instrument has an instrument change to an unpitched instrument followed by a change back to the pitched instrument in the same measure, the remainder of the measure will place certain notes on incorrect lines.

### Steps to reproduce

1. Create a score with a Marimba (single staff)
2. Add an instrument change to Cymbal
3. Later in the same measure, add an instrument change back to Marimba (single staff)
4. Observe that any notes in the same measure with pitch A3 will incorrectly be placed on the top line of the staff.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/91428485/ecefc027-073c-42c1-af07-8740495d957a)

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 11

### Additional context

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

**Comment by zacjansheski** [comment]
Additionally, changing the notehead for the cymbal in this example affects the noteheads after as well

<img width="616" alt="Screen Shot 2023-09-15 at 5 03 48 PM" src="https://github.com/musescore/MuseScore/assets/69917893/e7419bcd-c6ad-4c85-b837-e1be5a862dbf">
