### ISSUE TITLE
Clicking Bold/Italic/Underline on properties panel prevents user from continuing to type lyrics with keyboard

### ISSUE THREAD

**Issue by Aurivox** [musescore/MuseScore#19407]
### Issue type

UI bug

### Bug description

When clicking Bold/Italic/Underline on properties panel it is not possible to type lyrics. But you can type lyrics and change properties later.

### Steps to reproduce

1. create new score with some notes
2. mark note
3. Command + L (macOS)
4. Writing is not possible

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/103463374/a9ccbb51-4ac3-46c4-b638-b9658401ea35

### MuseScore Version

OS: macOS 13.5, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 13.5.1

**Comment by bkunda** [comment]
Weirdly, if I continue pressing keys for long enough after having selected a style property (like "bold"), the selection focus returns to where the input cursor is and I can carry on typing. 
Definitely a weird interaction bug. @mathesoncalum I wonder if this might be one for you?

**Comment by mathesoncalum** [comment]
@bkunda Yeah I can certainly take a look!
