### ISSUE TITLE
Microtonal support doesn't work during playback

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#19408]
### Issue type

Muse Sounds bug

### Bug description

It is unclear to us if this is on the Muse Sounds side or MuseScore side. Muse Sounds have pushed an update that allows microtonal playback, which can be tested (see video). The issue occurs during playback.

### Steps to reproduce

Follow video:

### Screenshots/Screen recordings

https://www.dropbox.com/scl/fi/meep1xlvtlzheu9suj830/Microtonal_Issues.mov?rlkey=ytzd42l3jatp367nz4uv7dchn&dl=0

### MuseScore Version

4.1

### Regression

No.

### Operating system

MacOS

**Comment by cbjeukendrup** [comment]
This looks a lot like a duplicate of https://github.com/musescore/MuseScore/issues/18036

**Comment by oktophonie** [comment]
Yes, but is it?

**Comment by Tantacrul** [comment]
Yeah, it is. Closing.

**Comment by Tantacrul** [comment]
I've added Roman to the other issue and helpfully plonked it in the 4.2 release. However, it may be 100% a Muse Sounds issue.
