### ISSUE TITLE
Tempo changes break note durations

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#19418]
### Issue type

General playback bug

### Bug description

The length of a note currently depends on the score's tempo when the note started.

If, at 60 BPM, you have a whole note, and in the middle of the note, the tempo changes to 120 BPM, the note will be 4 seconds long instead of 3. If you have more notes after that, it can cause irritatingly dissonant overlaps.

Of course, the opposite can happen (the tempo decreases mid-note), in which case the note will be too short.

### Steps to reproduce

Create a score where the tempo changes in the middle of a note.
Press play.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Windows 10 Version 2009, Arch.: x86_64

**Comment by cbjeukendrup** [comment]
Seems related to #15609 and the issues mentioned in that PR

**Comment by ThePython10110** [comment]
Yes, it does seem to be related to that.
