### ISSUE TITLE
Dynamic change and long crescendo after a repeat causes playback error

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#19417]
### Issue type

General playback bug

### Bug description

The attached score playback is corrupt at bar 124. When you start the playback, it sounds like quarter notes, while the bar contains a half-dotted note tied to the next bar. Playback remains like this for a few bars until it picks up the actual written note values.

[Doyen.mscz.zip](https://github.com/musescore/MuseScore/files/12641060/Doyen.mscz.zip)

Someone else tested using this score and removed many instruments and bars. The "extract" for the score still plays incorrect. However, if you remove the repeat barline in bar 1 the playback work as expected.

[Veteran.mscz.zip](https://github.com/musescore/MuseScore/files/12641063/Veteran.mscz.zip)

### Steps to reproduce

Load attached score and check the playback.

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
Interesting bug!  It seems like it is caused by the change of dynamics after the repeat and the crescendo going past a rest.


https://github.com/musescore/MuseScore/assets/69917893/bee80071-2164-474e-9f2d-ecb8ed396ee9

**Comment by zacjansheski** [comment]
I think this would be the minimal way to reproduce

https://github.com/musescore/MuseScore/assets/69917893/f5556671-7f0b-4f77-a4b7-b3e7f3fb0a41

**Comment by henkdegroot** [comment]
@zacjansheski , thank you so much for this. I can at least work around the issue. Change the cresc. to stop before the rest and start a new cresc. at that position works for me.
