### ISSUE TITLE
Crash after applying shortcut for Measure properties

### ISSUE THREAD

**Issue by MichLeon** [musescore/MuseScore#19425]
### Issue type

Crash or freeze

### Bug description

Assign a shortcut to Measure properties, e.g. Ctrl + Alt + M
Select a note. Apply shortcut. Crash.

### Steps to reproduce

1. In Preferences > Shortcuts assign a shortcut to Measure properties, e.g. Ctrl + Alt + M
2. Select a note.
3. Apply shortcut.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: -e4d1ddf

### Regression

No.

### Operating system

Windows 11

### Additional context

[MuseScore_230916_181459.log](https://github.com/musescore/MuseScore/files/12641535/MuseScore_230916_181459.log)

**Comment by MichLeon** [comment]
came up on https://musescore.org/en/node/351668

**Comment by vashutangri** [comment]
Hey, would love to work on this!

**Comment by Jojo-Schmitz** [comment]
I can't reproduce the crash. Mut the measure properties dialog doesn't show either, not even when lecting a measure tahter than a note.
Mu3 doesn't have that issue BTW, but it doesn't have (the option to assign) a shortcut for measure properties

**Comment by vashutangri** [comment]
Hey, so I wanted to add that the problem I was facing when I tried working on this was different. If you use another shortcut (Ctrl+Alt+W) then it works and the dialog opens while assigning Ctrl+Alt+M to anything, not just measure/staff properties,  doesn't work (atleast for me). Is this the same for everyone? Also would love a hint as to where to look to solve this issue

**Comment by wizofaus** [comment]
Definitely crashes for me in debug build anyway, and had similar problem myself. Will change so that using "Measure properties" automatically selects the whole measure based on what's selected if I can.

**Comment by Jojo-Schmitz** [comment]
Could this be related to #22246 ?

**Comment by wizofaus** [comment]
Have confirmed crash still occurs in 4.4, and updated PR that fixes it.

**Comment by wizofaus** [comment]
This crash is still happening, and I just lost work because of it (was using 4.4.2 at the time).  It's been P1 since September last year and my PR has been sitting there for quite some time. @zacjansheski
