### ISSUE TITLE
After using lyrics [SPACE] function, I can't use the pitch keyboard shortcuts or some other functions 

### ISSUE THREAD

**Issue by llamanking** [musescore/MuseScore#19449]
### Issue type

UI bug

### Bug description

The layout of my sheet: Vocal + Piano.

When I use lyrics to go to the next syllables [SPACE], I cannot edit the notes using the keyboard shortcuts like:
pitch: ABCDEFG,
articulations: t (tie) , [SHIFT + V] (accent)

But weirdly, flat, natural, and sharp shortcuts work...

When I restart the application, the shortcuts work again.

Could you all let me know if this is happening to other users? 

Thanks!

### Steps to reproduce

1. Create a music sheet with a vocal.
2. Add random notes (or get a sample sheet without lyrics)
3. Use [CTL + l] next to the vocal note
4. Type in the syllable
5. Type [SPACE] to enter the next syllable
6. Go to any rest notes or notes and try to add the note using the keyboard shortcuts (this reproduces the pitch bug)
7. Go to any note with the same pitch and try to add a tie bar (this reproduces the articulation bug)
8. Go to any note without an accent and try to add it (this reproduces the articulation bug).

### MuseScore Version

4.1.1-232071203

### Regression

No.

### Operating system

Windows 10

**Comment by llamanking** [comment]
Additional information: The sheet music I am using had been imported from a PDF version (for a key change).

**Comment by MarcSabatella** [comment]
Can you describe what you mean by "go to" in steps 6, 7, and 8?  As far as I can tell, you are still in lyric entry mode at this point.  So of course the letter keys will simply enter letters into the lyrics rather than enter notes.  If I press Esc to leave lyric mode, then select a note and go into note input mode, the letters A-G enter notes as expected, and T and SHift+V also work as expected.

But it's possible the issue you are seeing has something to do with the specific score.  Please ZIP and attach that, then be more precise about your instructions exactly what notes you are selecting and how you are selecting them, which lyrics you are entering, etc.

**Comment by llamanking** [comment]
> Can you describe what you mean by "go to" in steps 6, 7, and 8? As far as I can tell, you are still in lyric entry mode at this point. So of course the letter keys will simply enter letters into the lyrics rather than enter notes. If I press Esc to leave lyric mode, then select a note and go into note input mode, the letters A-G enter notes as expected, and T and SHift+V also work as expected.
> 
> But it's possible the issue you are seeing has something to do with the specific score. Please ZIP and attach that, then be more precise about your instructions exactly what notes you are selecting and how you are selecting them, which lyrics you are entering, etc.

Hi Marc, what you did in your steps is precisely what I did (but mine didn't work as yours did). Here is the zip file. 
FYI -- the lyrics and the title are in Korean. 

[고속도로_로맨스_E.zip](https://github.com/musescore/MuseScore/files/12666978/_._E.zip)

**Comment by llamanking** [comment]
Nevermind! It wasn't a bug, it was my fault that I didn't click back the [ALT] key after I changed the language (stupid of me)! Apparently, if I want to use the keyboard shortcuts, it must be in English layout.

**Comment by MarcSabatella** [comment]
Good job figuring that out!  Fwiw, you can customize your shortcuts in Edit / Preferences / Shortcuts, so if you’re normally using a Korean or other layout, it might work to just use those same keys even though they get interpreted differently by the system.  But I don’t know for sure that this would work, and I also don’t know if you would prefer to stay in the other layout or not.
