### ISSUE TITLE
Crescendo, Decrescendo, Pedal lines: text offset does not survive save/reopen

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#19460]
### Issue type

Engraving bug

### Bug description

Pedal text offset does not survive save/reopen

### Steps to reproduce

1. Create a file with Pedal markings with text
2. Assign new text offset values in the properties panel
3. Save, close and reopen
4. Offset value returns to 0

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/c0cd2c54-5d3a-4eea-8a38-6a11d2924470

### MuseScore Version

4.1.1

### Regression

No.

### Operating system

OS: macOS 11.6

### Additional context

Discovered when testing this PR https://github.com/musescore/MuseScore/pull/19454

**Comment by mathesoncalum** [comment]
There may be more to this than we initially thought @zacjansheski - I discovered the same is happening for diminuendo and other engravings (for beginning, continuing, and end text). Weirdly, this seems to have been a problem for diminuendo since MS3, but Pedals look like a regression since then.

Probably worth figuring out the exact scope of this and when particular aspects were broken.

**Comment by zacjansheski** [comment]
MS3 before save
<img width="489" alt="Screen Shot 2023-09-21 at 10 55 50 AM" src="https://github.com/musescore/MuseScore/assets/69917893/0f9ae2e9-edd5-4f2f-97ae-7b589f30b015">


After quit and reopen
<img width="603" alt="Screen Shot 2023-09-21 at 10 57 01 AM" src="https://github.com/musescore/MuseScore/assets/69917893/8d8b7d3a-e28b-4210-b0e6-8f33f0334fb7">

**Comment by zacjansheski** [comment]
MS4.0.2

Before save
<img width="739" alt="Screen Shot 2023-09-21 at 11 02 24 AM" src="https://github.com/musescore/MuseScore/assets/69917893/a3dbc8bb-e482-4695-ada1-673c41919ad3">


After close and reopen

<img width="870" alt="Screen Shot 2023-09-21 at 11 02 59 AM" src="https://github.com/musescore/MuseScore/assets/69917893/5308015f-ce4c-4b28-a60a-eda915720570">

**Comment by zacjansheski** [comment]
4.1.1 Only horizontal offset capabilities

Before save
<img width="867" alt="Screen Shot 2023-09-21 at 11 11 40 AM" src="https://github.com/musescore/MuseScore/assets/69917893/140ca552-0822-43e6-beba-bcd4cfdafe82">


After close and reopen

<img width="859" alt="Screen Shot 2023-09-21 at 11 11 58 AM" src="https://github.com/musescore/MuseScore/assets/69917893/7a90aa54-6931-45d0-972d-a2a1697ce45e">

**Comment by zacjansheski** [comment]
As @mathesoncalum stated:
Pedal Offset lost on save: MS3 regression
Crescendo/Decrescendo Offset lost on save: Not a regression
