### ISSUE TITLE
Crash when hiding instruments in file imported from Musescore 3 or musicxml

### ISSUE THREAD

**Issue by dulciepercy** [musescore/MuseScore#19486]
### Issue type

Crash or freeze

### Bug description

Happened in two files, one imported from Musescore 3 (just piano) and one from musicxml export from Sibelius.  I added a new stave and instrument.  When hiding instruments from the Instrument Panel the program crashes.

### Steps to reproduce

Import a file from Musescore 3 or MusicXML 
Add an instrument
Hide the original instrument

### MuseScore Version

4.1.1 and 4.2.232560304

### Regression

I don't know

### Operating system

Windows 11

### Additional context

[musediag.zip](https://github.com/musescore/MuseScore/files/12699727/musediag.zip)

**Comment by cbjeukendrup** [comment]
@dulciepercy Here is a quick attempt to fix this: #19521
Could you please try the build from that pull request (see https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests) and let me know if that fixes it?

**Comment by cbjeukendrup** [comment]
Also, from the output from the log files, it looks like there are also some issues with the score in question. If possible, it would be great if you could upload it, so that we can investigate.

**Comment by cbjeukendrup** [comment]
@dulciepercy It would be great if you could reply to the comments above!

**Comment by cbjeukendrup** [comment]
Closing, because no reply and the probably fix that I mentioned above has been merged via #19866.
