### ISSUE TITLE
"change instrument text" on score affecting wrong line

### ISSUE THREAD

**Issue by Vykoiazon** [musescore/MuseScore#19483]
### Issue type

Engraving bug

### Bug description

When multiple [change instrument text] lines are above each other in the same bar of a score, not all of them work properly, changing an instrument text can affect the staff below it instead of the intended staff.

### Steps to reproduce

1. add change instrument text on two staves on the same bar and beat
2. change staff/part properties "short instrument name" for the top staff with the change instrument text (by double clicking the instrument abbreviation on the next system or page)
3. see the lower staff actually gets affected by the text change instead of the top and the top staff instrument is not actually changed in soundfont or range expectations

### MuseScore Version

4.1.1-232071203

### Regression

No.

### Operating system

windows

**Comment by sammik** [comment]
I cant reproduce it following exactly mentioned steps.

**Comment by HeinzVo** [comment]
This bug already was present in MuseScore 3.6

**Comment by zacjansheski** [comment]
Reproduced in current nightly


https://github.com/musescore/MuseScore/assets/69917893/5e361adb-caaa-4e09-8914-2ae3ca2d72ac

**Comment by sammik** [comment]
Happens, only if instrument change is added to lower staff first.
Also affects instrument itself, not only instrument name.


https://github.com/musescore/MuseScore/assets/1646034/8a8c3701-424f-40c5-8d5e-cdb08e42298b

**Comment by sammik** [comment]
please, check #19566
