### ISSUE TITLE
Vertical offset of notehead extends stem

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#19488]
### Issue type

Engraving bug

### Bug description

Applying vertical offset to a notehead at a certain point exends the stem as well

### Steps to reproduce

Select a note head
Adjust the vertical offset.
To get here 
- go to the Properties panel
- Select "Head"
- "Show more"
- "Notehead Offset" is at the bottom

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/4b8f01e4-e648-49bd-a1ee-ed153f246e75

### MuseScore Version

OS: macOS 11.7, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232650302, revision: github-musescore-musescore-3e859ed

### Regression

No.

### Operating system

All

### Additional context

Was present in 4.0, vertical offset disabled in 4.1, re-enabled and returned in the current master.

**Comment by Jojo-Schmitz** [comment]
Apparently a regression vs. 3.x
