### ISSUE TITLE
Typo in german translation "zurücksetzten" instead of "zurücksetzen"

### ISSUE THREAD

**Issue by inatuwe** [musescore/MuseScore#19496]
### Issue type

Other type of issue

### Bug description

"Are you sure you want to reset this part?" is translated to:
"Sind Sie sicher, dass sie diesen Auszug zurücksetz**t**en wollen?", so correct would be:
"Sind Sie sicher, dass sie diesen Auszug **zurücksetzen** wollen?".

### Steps to reproduce

1. Push the toolbar button "Auszüge" (Parts).
2. From the three dots on the right side select "Zurücksetzen" (Reset).

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10

### Additional context

![image](https://github.com/musescore/MuseScore/assets/61066311/128e0a3f-150e-4656-97cd-e5182a6d6b17)

**Comment by mmeyn** [comment]
It is unfortunately a very common spelling error in german to write “tzt” where “tz” would be correct.

There is the word “jetzt” (= now) and words that have “tz” in it that need an additional (spoken!) “t” for third person (he/she/it) or past tense like “Er setzt diesen zurück.” or “Sie haben diesen Auszug zurückgesetzt.”

**Comment by Jojo-Schmitz** [comment]
Fixed, update your translations in about 15 minutes

**Comment by inatuwe** [comment]
Wow! I'm amazed! This is a very fast reaction time :-). I updated the translations and can confirm it's fixed. Thank you!
