### ISSUE TITLE
Soft hyphen in lyrics breaks layout

### ISSUE THREAD

**Issue by tsjam23** [musescore/MuseScore#19503]
### Issue type

Engraving bug

### Bug description

[Soft hyphen](https://en.wikipedia.org/wiki/Soft_hyphen) character adds much space between staves of two instruments if entered or present in lyrics.
The score with soft hyphen was saved in MS3 and was reported here https://musescore.org/en/node/354996
This file opens fine in MS 3.6.2, but layout is broken if opened in MS 4.1.1
It also breaks layout in MS 4.1.1 from scratch, so this is NOT MS3 import issue.
You can type soft hyphen on windows using ALT + 0173 (in Musescore it works for me if I turn off Num lock key first)

![image](https://github.com/musescore/MuseScore/assets/133224452/aba0e766-6a74-4c63-87c0-f1505c075fcc)

### Steps to reproduce

1. Create new score with two instruments
2. Enter some notes on first staff and add lyrics text, which contains soft hyphen
4. Layout breaks

### MuseScore Version

MuseScore version (64-bit): 4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment]
Very likely related to https://github.com/musescore/MuseScore/issues/19252#issuecomment-1703099499

**Comment by Jojo-Schmitz** [comment]
Supporting soft hypens on copy and paste might be quite useful, also with copy lyrics from clipboard

**Comment by wizofaus** [comment]
Reproduced, happy to have a look at this.

**Comment by wizofaus** [comment]
Caused by the tightBoundRect returned by Qt for this character. Not quite sure what the best way to address at this point is, could treat the weird high value it returns as a special case?

**Comment by cbjeukendrup** [comment]
I think @igorkorsukov had the idea of switching away from QFontMetrics and related, and reimplement it using FreeType directly, hoping that this fixes this and other issues.

**Comment by wizofaus** [comment]
I have a fix but it means that the soft hyphen on its own simply isn't displayed at all as Qt can't actually calculate a bounding rect for it (basically thinks it takes up no space).  But maybe that's fine, as it doesn't really make sense for a soft-hyphen to be shown unless it is used as part of a word that does need to break across two notes?
Anyway, basically you have to ignore the tightBoundingRect returned by Qt (which is garbage) and use an empty one instead.

**Comment by igorkorsukov** [comment]
> I think @igorkorsukov had the idea of switching away from QFontMetrics and related, and reimplement it using FreeType directly, hoping that this fixes this and other issues.

This work is on hold for now...
It's quite easy to get font metrics, it's done and there are no problems with it.
But for everything to work as it should, we also need to render the text yourself, not Qt, and that’s where the problems. If the metrics are obtained in one way, but the text is rendered Qt , then they may simply be slightly different.
