### ISSUE TITLE
UI bug, the empty accidentals palette. Please check it out.

### ISSUE THREAD

**Issue by Auase** [musescore/MuseScore#19505]
### Issue type

UI bug

### Screenshots/Screen recordings

![2222](https://github.com/musescore/MuseScore/assets/56365735/36742dfc-cd03-4adb-89f0-22855bb65595)

### MuseScore Version

4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
You mean the empty accidentals palette? I can confirm that, but please be more explicit in your descritopn and the title
And it is is not an egraving bug, but a UI one

**Comment by Auase** [comment]
@Jojo-Schmitz 
I'm really sorry. I expressed myself inappropriately. I see that the Labels have been corrected. Do I still need to modify the title?

**Comment by oktophonie** [comment]
Yes.

**Comment by Jojo-Schmitz** [comment]
Maybe related to #19501 ?

**Comment by zacjansheski** [comment]
I think this is a duplicate of https://github.com/musescore/MuseScore/issues/19374
Please confirm
