### ISSUE TITLE
Crash on note input with percussion instruments

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#19516]
### Issue type

Crash or freeze

### Bug description

When entering note input mode on a percussion instrument in the current master, MuseScore crashes.  Drumset window does not appear.

### Steps to reproduce

1. Create a score with a percussion instrument
2. Select a bar and enter note input mode with "n"

### MuseScore Version

OS: macOS 11.7, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232680302, revision: github-musescore-musescore-624343a

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: macOS 11.6

### Additional context

[DrumsetCrash.zip](https://github.com/musescore/MuseScore/files/12715497/DrumsetCrash.zip)

**Comment by DmitryArefiev** [comment]
Fixed in #19808

**Comment by zacjansheski** [comment]
This issue is persisting in the current nightly

[PercCrash.zip](https://github.com/musescore/MuseScore/files/13206496/PercCrash.zip)

**Comment by cbjeukendrup** [comment]
Working on it
