### ISSUE TITLE
Incorrect creation date in project properties when using custom template

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#19524]
### Issue type

Other type of issue

### Bug description

When creating a score using a custom template, the creation date in the project properties is not set to today's date but instead reflects the creation date of the template.

### Steps to reproduce

1. Create a new score using a custom template.
2. Go to Project properties.
3. Observe that the "Creation date" does not reflect today's date but instead shows the template's creation date.

### MuseScore Version

MuseScore 4.0 and after

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by frnkwang** [comment]
Hi, is this still open? I'm interested in trying this for my first issue!

**Comment by cbjeukendrup** [comment]
Yes, welcome!
