### ISSUE TITLE
Crash on exporting audio

### ISSUE THREAD

**Issue by nweininger** [musescore/MuseScore#19523]
### Issue type

Crash or freeze

### Bug description

Exporting my score to an audio file causes a crash at about progress bar 28%. I've tried MP3, FLAC, OGG, WAV export all with the same result. MIDI export works. If I export the score to MusicXML, then reimport into MuseScore, the crash still happens. This is all with 4.1.1 on Ubuntu 22.04.

### Steps to reproduce

1. Open the attached (zipped) 
[lechadodi.zip](https://github.com/musescore/MuseScore/files/12720649/lechadodi.zip)
score in MuseScore 4.1.1.
2. Select Export to MP3, WAV, OGG, or FLAC.
3. Wait till it gets about 28% through the exporting process.

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Ubuntu 22.04

**Comment by zacjansheski** [comment]
I am unable to reproduce on Ubuntu or MacOS

Could you share diagnostic files and specs of your device? (CPU, GPU, RAM, etc.)

**Comment by nweininger** [comment]
Sure. The device is a Framework Laptop with a Core i7-1185G7 CPU, integrated GPU, and 32GB of RAM. By diagnostic files I assume you mean the ones created by Diagnostics -> Save diagnostic files, and I've attached these: 
[musescorediagnostics.zip](https://github.com/musescore/MuseScore/files/12729944/musescorediagnostics.zip)

**Comment by zacjansheski** [comment]
@nweininger sorry this issue has gotten a bit stale.  Is the issue still actual in the current version of MuseScore Studio?

**Comment by zacjansheski** [comment]
Closing, no response
