### ISSUE TITLE
Adding Key signatures and Undo doesn't update key signatures change on the next system

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19528]
### Issue type

Choose option...

### Steps to reproduce

1. Open Classical Orchestra template
2. Select first measure
3. Add key signatures
4. Undo 

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/41dbbba7-2ea8-4ea7-a424-fe19ffb8144d

### MuseScore Version

4.2.0 master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by zacjansheski** [comment]
Additional info:
Does not occur on all templates
Does not persist if the first measure of following page changes
Does not persist after save and reopen (as shown on video)

**Comment by sammik** [comment]
I am pretty sure, it is same issue as #18751

**Comment by sammik** [comment]
so, not the same, just cousine

fix: #19540
