### ISSUE TITLE
Refinements checklist for new Tie features

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#19532]
@oktophonie feel free to dump everything here.

1. Add new icons provided by @jessjwilliamson to Style menu and Property panel (fixed in https://github.com/musescore/MuseScore/pull/19988)
2. Ensure that ties to outside notes clear ledger lines when flipped
3. Start ties on dotted notes before the dot (at least on outer notes)
4. Improve (i.e. usually reduce) 'tucking' on outside-style ties on inner notes
5. Prevent inner ties endpoints from being further out than outer ties (except in cases of offset notes)
6. Refine algorithm to thin short ties more gradually

**Comment by sammik** [comment]
![ties](https://github.com/musescore/MuseScore/assets/1646034/cca97aab-925e-4b3b-b9db-f6241f42b4da)

If altered unison group is tied to, ties are different, depending, if tiedBack note is first in group, or not.
