### ISSUE TITLE
MuseSounds are loading slower on macOS Sonoma 14.0 (comparing with macOS Ventura)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19557]
### Issue type

Performance issue

### Bug description

On macOS **Sonoma**, Classical Orchestra  template with **MuseSounds** takes **16-19sec**
On macOS **Ventura** , Classical Orchestra template with **MuseSounds**  takes **1-2sec**

No difference with **MS Basic**

### Steps to reproduce
macOS **Sonoma 14.0 (23A344)**, M1 laptop

https://github.com/musescore/MuseScore/assets/90187801/4df7775a-83d0-406f-9c90-3e44b20c33a4

macOS Ventura 13.6, same M1 laptop

https://github.com/musescore/MuseScore/assets/90187801/66e13f7f-5c73-46a2-b063-ad03616aa10e

### MuseScore Version

4.2.0 master/4.1.1/4.0.0

### Regression

Regression on OS side (worked in previous macOS)

### Operating system

macOS Sonoma 14.0 (23A344), MacBook Air M1 2020, 8GB, 13inch.

**Comment by DmitryArefiev** [comment]
FYI @bkunda I put this to 4.2 project with P1 to have it on our radar

**Comment by zacjansheski** [comment]
Same issue for me.

"Concert Band" template takes about 30sec to load with Muse Sounds on Sonoma
Less than a second with MS Basic on Sonoma.
Less than a second with MuseSounds/MS Basic on Ventura on the same device.

**Comment by RomanPudashkin** [comment]
It turned out that [this PR](https://github.com/musescore/MuseScore/pull/22535) quite significantly optimized Muse Sounds loading by eliminating useless ms_init calls

**Comment by zacjansheski** [comment]
Looks resolved to me!

**Comment by danielle-sopalski** [comment]
Massively exciting to hear! Thank you, @RomanPudashkin!

**Comment by DmitryArefiev** [comment]
Tested on **4.3.1** and **4.4** builds. **All good** on my side too

Closing
