### ISSUE TITLE
Add "Collapse/Expand all" actions to Instruments panel

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#19562]
### Your idea

The Palettes panel has actions for "Collapse all palettes" and "Expand all palettes" in the context menu that appears when clicking the three-dot-icon button.
<img width="325" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/73c21f9e-5461-4a86-8c7d-f7f3c854c6e3">

The Instruments panel should have similar options. The full context menu would appear as follows:
![image](https://github.com/musescore/MuseScore/assets/20806406/48543ba7-c6d3-4bfd-9113-d022c1c01f8c)

- Instrument ordering
- DIVIDER
- Collapse all instruments
- Expand all instruments
- DIVIDER
- Close
- Undock

### Problem to be solved

This would allow users to quickly see the contents of each instrument, or close all of them, without having to do so individually. This will be especially useful when we introduce other types of "layers" to instruments, like automation lanes, where users might want to see all instruments open at once.

**Comment by MaxiSchwindler** [comment]
I've opened a pull request for this: #19995
