### ISSUE TITLE
Can't remove key signature in mmRest mode

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#19575]
### Issue type

UI bug

### Bug description

Can't remove keysign in mmRest mode

### Steps to reproduce

1 Create new score
2 Add note in firts measure
3 Change key sign in second measure
4 Add note at measure 8
5 Go in mmRest mode (key M)
6 Try to remove keysign not work
7 Exit from mmRest mode
8 Now you can remove keysign

### Screenshots/Screen recordings

Can remove keysign
![image](https://github.com/musescore/MuseScore/assets/1835871/b920683a-e9d8-4221-89f2-0c900b59450d)

Can't remove keysign
![image](https://github.com/musescore/MuseScore/assets/1835871/2ea562d9-7aae-40e2-90bb-24a5b512542d)

### MuseScore Version

MuseScore version (64-bit): 4.2.0-232740304, revision: github-musescore-musescore-5070991

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

**Comment by sammik** [comment]
see #19665
