### ISSUE TITLE
Instrument name (long) is misaligned when attached to an ossia stave

### ISSUE THREAD

**Issue by joexcm** [musescore/MuseScore#19577]
### Issue type

Engraving bug

### Bug description

Instrument name at the start of the score is misaligned if it has an ossia part on a second stave above it.
Seems to be because it is aligned to the small stave of the ossia.

### Steps to reproduce

1. Create score with two single stave instrument (e.g. Alto and Tenor voices)
2. Add some notes to both parts for two lines of music
3. Add second stave to Alto
4. With top Alto stave, tick 'small stave' and 'hide all bars that do not contain notation (cutaway)
5. In Style options - Score, tick 'hide all empty staves within systems' and untick 'don't hide empty staves in first system'
6. Top stave (Alto) is out of alignment
7. To remedy, go to Style - Text Styles - Instrument name (long), and untick 'follow stave size'

### Screenshots/Screen recordings

https://screenrec.com/share/3WiJEMfu5B

### MuseScore Version

OS: macOS 13.5, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

macOS 13.5

### Additional context

[Musescore bug demo.mscz.zip](https://github.com/musescore/MuseScore/files/12777376/Musescore.bug.demo.mscz.zip)

**Comment by oktophonie** [comment]
Fixed by https://github.com/musescore/MuseScore/pull/19161
