### ISSUE TITLE
Title Frame not present in parts from an imported XML file

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#19576]
### Issue type

Other type of issue

### Bug description

Title Frame not present in parts from an imported XML file

### Steps to reproduce

1 Import this XML part
2 Generate parts
3 No title frame in parts

### Screenshots/Screen recordings

Conductor
![image](https://github.com/musescore/MuseScore/assets/1835871/6d1acb2e-2df8-4a16-8521-deb4203b7f43)

Part
![image](https://github.com/musescore/MuseScore/assets/1835871/ac3a2f1a-93b0-40e3-9ab9-dc2ec08fba7c)

### MuseScore Version

MuseScore version (64-bit): 4.2.0-232740304, revision: github-musescore-musescore-5070991

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64, 

### Additional context

XML file Zipped (This XML file was created with MuseScore, but this occur when i use XML file exported by other programs)
[au clair.zip](https://github.com/musescore/MuseScore/files/12777297/au.clair.zip)

**Comment by oktophonie** [comment]
Possibly (?) related: https://github.com/musescore/MuseScore/issues/16057 and/or https://github.com/musescore/MuseScore/issues/19476

**Comment by sammik** [comment]
see #19606
