### ISSUE TITLE
Parenthesis on alteration not working

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#19574]
### Issue type

UI bug

### Bug description

Parenthesis on alteration not working

### Steps to reproduce

1 Create new score
2 Add note
3 Add accidental to the note
4 Try to put accidental in parenthesis

Result nothing, even if i use propertie panel

Edit : Try to move an note element ( like crescendo ), update the view and parenthesis appear

### MuseScore Version

MuseScore version (64-bit): 4.2.0-232740304, revision: github-musescore-musescore-5070991

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

**Comment by Gai-Luron** [comment]
Edit : Try to move an note element ( like crescendo ), update the view and parenthesis appear

**Comment by cbjeukendrup** [comment]
It seems I cannot reproduce this (on macOS), but perhaps I'm doing something wrong. Could you provide a video where this happens?

**Comment by Gai-Luron** [comment]
https://github.com/musescore/MuseScore/assets/1835871/b1101e9d-c57c-4d09-b106-f388158c2764

**Comment by cbjeukendrup** [comment]
@Gai-Luron Thanks, I can reproduce now. It seems that it depends a bit on the specific notes and the amount of notes; sometimes it happens, sometimes not.

**Comment by Gai-Luron** [comment]
Sometine i have a crash if i have already a crescendo on a note, i put alteration, then parenthesis on this note, move crescendo to make parenthsis visible; and restore crescendo position with Ctr+R. This occur only on part. But i can't reproduce it all the time. If i find how to do that it all time i write a new issue.

**Comment by cbjeukendrup** [comment]
@Gai-Luron Hopefully this fix will work: #19579
