### ISSUE TITLE
Crash when revert action "Hide Head note" on part

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#19584]
### Issue type

Crash or freeze

### Bug description

Crash when revert action "Hide Head note" on part

### Steps to reproduce

1 Create New Score
2 Add 2 instruments
3 Add note on second instrument
4 Create part from second instrument
5 Go on part and hide Head Note
6 Revert "Hide Head Note" With Ctrl+Z
7 Crash

### MuseScore Version

MuseScore version (64-bit): 4.2.0-232740304, revision: github-musescore-musescore-5070991

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

**Comment by Gai-Luron** [comment]
https://github.com/musescore/MuseScore/assets/1835871/baef1f31-2283-42c8-96ea-d58e165fb48b

**Comment by Gai-Luron** [comment]
https://github.com/musescore/MuseScore/assets/1835871/7f535972-4758-496e-a8fa-b37621b56b39

**Comment by zacjansheski** [comment]
Regression from 4.1.1, diagnostic files attached

[InvisNoteHeadPartCrash.zip](https://github.com/musescore/MuseScore/files/12793163/InvisNoteHeadPartCrash.zip)
