### ISSUE TITLE
Second measure of double repeat is considered empty by cutaway logic

### ISSUE THREAD

**Issue by nicolaiskogheim** [musescore/MuseScore#19581]
### Issue type

Engraving bug

### Bug description

The cutaway feature hides the second measure of a double repeat sign.

I would expect the second measure to not be hidden.

### Steps to reproduce

1. Open a score
2. Insert a double repeat from the **Repeats & Jumps** palette.
3. Right click on a measure while avoiding any elements, to access the "Staff/Part properties..."
4. Enable the "Cutaway" checkbox, located to the right in the window.
5. Click **OK**

### Screenshots/Screen recordings

<img width="356" alt="Screenshot 2023-10-01 at 21 35 43" src="https://github.com/musescore/MuseScore/assets/2117636/4d1438b8-20e0-42cf-a29a-d58e2c73e0ce">

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

OS: macOS 13.5, Arch.: x86_64

### Additional context

[Double repeat cutaway bug.mscz.zip](https://github.com/musescore/MuseScore/files/12778065/Double.repeat.cutaway.bug.mscz.zip)

**Comment by nicolaiskogheim** [comment]
**Poor workaround**: Attach **Staff text** on the hidden measure, and replace the text with a space character, so that it is not visible.

What makes the workaround poor, is that you now have an unselectable text element on the measure. If you later decide to hide the measure, you need to know about:
**Reverting workaround**: Select the measure and either hit <kbd>v</kbd>, or uncheck **Visible** in the **Properties** menu.

Non-workarounds:
1. Using expression text or similar: A) they alter the sound, B) if you hide them, the measure will still be hidden. (I would call this expected/wanted behaviour).
2. Using the "Visible" toggle in the measure **Properties**:  It does not affect visibility of Cutaway measures.

**Comment by Jojo-Schmitz** [comment]
As Mu3 doesn't support 2-measure repeats, this is sort of a regression vs Mu3, but at least Mu3 is not affected by it
