### ISSUE TITLE
Can't select second slur on one note

### ISSUE THREAD

**Issue by jdfergusson** [musescore/MuseScore#19599]
### Issue type

UI bug

### Bug description

Creating two slurs from one note of different lengths leaves one of the slurs 

### Steps to reproduce

1. Add four notes
2. Create a slur between notes one and two, and a slur between notes three and four. 
3. Select all four notes and create a slur (by pressing S)
4. Try and select the larger slur

### Screenshots/Screen recordings

![simplescreenrecorder-2023-10-03_18 29 30](https://github.com/musescore/MuseScore/assets/6746295/4c110cdc-179d-43ab-926b-7fe28b62ee2e)

Here's what I'm aiming for, if you're wondering why it's necessary
![image](https://github.com/musescore/MuseScore/assets/6746295/49944bbc-7144-4290-8e72-895c060c5811)

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Linux (AppImage)

**Comment by MarcSabatella** [comment]
Confirmed.  Workaround: select via keyboard navigation (click first note, press Alt+Right twice).

**Comment by zacjansheski** [comment]
Thank you for logging this!  On MacOS, it is selectable, but only towards the end points. Is it the same for you?
https://github.com/musescore/MuseScore/assets/69917893/4fabd40b-5bf0-4aba-9f73-56efb5ec42a1

**Comment by jdfergusson** [comment]
Yes, that is the same for me. 

Having played with that a bit more, I can say also that it sometimes is selectable, depending on the beam direction of the four notes. For example, Up Up Down Down leaves the slur selectable in the middle, as does Down Down Up Up, and Down Down Down Up leaves approximately the first third of it selectable.

**Comment by zacjansheski** [comment]
This appears to be resolved in latest master and 4.2
Closing this unless there is new evidence of the issue, thank you!
