### ISSUE TITLE
Beam doesn't follow offset stem

### ISSUE THREAD

**Issue by jdfergusson** [musescore/MuseScore#19595]
### Issue type

Engraving bug

### Bug description

Offsetting a quaver that is beamed doesn't result in the beam staying attached to the stem.

### Steps to reproduce

1. Add two quavers, and ensure they are beamed.
2. Select either one. On the "Properties" tab, increase or decrease the Notehead offset (under Note > Head > Show more) and increase or decrease the Stem offset (Note > Stem > Show more)
3. Optional: Try and increase or decrease the Flag offset (Note > Stem > Show more), with no visible effect. 

#### Expected outcome
Either the beam should follow the stem, or the flag offset should affect beams as well as flags

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/6746295/46b53b8b-1bc9-4af8-86f1-38b4e9fa4cb6)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
This is not different than MU3 - if you move the notehead or stem only, then indeed, only the notehead or stem moves.  If your goal was to move the entire note, do that directly (via the offset in the Appearance section) - don't move the notehead and stem separately.

**Comment by oktophonie** [comment]
As far as I'm concerned the current behaviour is as intended - offsetting the stem or the notehead moves just the stem or the notehead. If you offset the entire chord, the beam will follow.

**Comment by jdfergusson** [comment]
That's all fair, thanks for the quick responses - I hadn't realised that the appearance dialog would allow you to move the whole chord. That's very useful.

I still don't think the flag offset is working, unless I'm misunderstanding what it's supposed to be doing. But that would be a separate issue.

Thanks
