### ISSUE TITLE
Vertical spacing bug

### ISSUE THREAD

**Issue by RetroRonin63158** [musescore/MuseScore#19598]
### Issue type

Engraving bug

### Bug description

Every time I make a change to my score, it zooms out/stretches out the score and staves by an unreasonable amount, off of the pages.

How it was replicated by another user (their words):

-the problem seems to occur with any editing action but only in measure 15 or later.
-saving and reloading after the problem occurs seems to restore the correct appearance but further editing makes it screw up again.
-Selecting everything and resetting positions does not resolve the problem
-Selecting everything and resetting beam properties to AUTO does resolve the problem but leaves the beams in an unwelcome state.
-Creating a new score and copy/pasting from the original score results in another score with identical behaviour.

### Steps to reproduce

I stated it in the description- but to me it was completely random with exact same conditions (bug just appears to occur at a certain (random) point when composing).

But to be more specific I was moving notes about (adding, removing, changing to flats or sharps or naturals- adding literally any kind of notations to bars 15 and onwards) and the app would stretch the score as seen in BOTH screenshots.
It would also remove the glissando that I added to the dotted quaver on bar 20, as seen in the second screenshot. Or shift the position of the notes.

### Screenshots/Screen recordings

![Screenshot (1216)](https://github.com/musescore/MuseScore/assets/146869721/66632755-d641-4ce1-aad6-8fd45b027b5b)

![image](https://github.com/musescore/MuseScore/assets/146869721/fe4f4643-a4e4-4c05-bd85-7015bb7c7bad)

### MuseScore Version

4.1.1.232071203

### Regression

No

### Operating system

Windows 10 (latest)

### Additional context

All stated in description section (that is all I can understand of the issue).

### Musescore file

[My toccata.zip](https://github.com/musescore/MuseScore/files/12795603/My.toccata.zip)

**Comment by MarcSabatella** [comment]
In order for someone to investigate, please ZIP and attach your score and give *precise* steps to reproduce the problem (easy exactly what measure you are selecting to edit, and exactly what editing operation you are performing).

**Comment by RetroRonin63158** [comment]
> In order for someone to investigate, please ZIP and attach your score and give _precise_ steps to reproduce the problem (say exactly what measure you are selecting to edit, and exactly what editing operation you are performing).

Just done that- these are the precise steps, because I have been doing so many things but it got bothersome after some time, so I reported the bug. I mentioned what I knew and what another musescore user noticed was happening from his side as well as this is as precise as I can describe it. It really is doing that for ANY changes.

**Comment by SteveBlower** [comment]
I am that other user who confirmed the problem.  

It looks like you removed your score from the forum thread.  Without that it will be impossible for anyone to investigate further.  Please attach it again here.  You will need to zip it or alternatively change the file extension to .zip so that Github can handle it.

**Comment by MarcSabatella** [comment]
OK, I can confirm that if I go to measure 16, select the first note, and hit Up then Down to raise and lower the pitch, I get the extra space between systems.  I think the beam extended over the rest in the corss-staff notation in measure 18 is the key - if I reset that, the problem goes away, but it returns as soon as I try adding the beam back.

**Comment by RetroRonin63158** [comment]
> I am that other user who confirmed the problem.
> 
> It looks like you removed your score from the forum thread. Without that it will be impossible for anyone to investigate further. Please attach it again here. You will need to zip it or alternatively change the file extension to .zip so that Github can handle it.

>yeah nw, I did that, just had some issues with winrar :D Although the suggested change in cross staff notation did indeed help the issue- I still would rather use it later on, so I'll just change it in the end when finishing my composition :)
