### ISSUE TITLE
Allow for the removal of admin privileges needed for MuseHub in MuseScore

### ISSUE THREAD

**Issue by RustoMCSpit** [musescore/MuseScore#19609]
### Your idea

MuseScore itself needs to be re-worked to move things like installing a system level directory, installing updates, etc.. to user-level actions exclusively (as a setting decided by the user) which will remove the need for admim priviliges (e.g. sudo but this applies to all operaring systems). I made the issue here as this is focusing on the MuseScore issue, not the MuseHub issue, both need re-working.

### Problem to be solved

Unneccesary admin privileges

### Additional context

https://musehub.zendesk.com/hc/en-gb/community/posts/8450771193629-MuseHub-runs-with-excessive-privileges-on-Linux-and-MacOS-posing-a-serious-security-threat

https://musescore.org/en/node/339877

'It used sudo to install the Muse Sampler framework itself (which installs to a system level directory so that we can guarantee it's location, which allows Muse Score to find it on every system and localisation without additional configuration etc), and also to install updates to itself if necessary.

We are exploring moving these to user-level actions, but it requires changes to not just Hub, but also Muse Score and Muse Hub.'

**Comment by cbjeukendrup** [comment]
If someone tells us what needs to be done, we can have a look 😉

MuseScore already looks for MuseSampler in the user's own folders first before falling back to the system-wide location. And for updating itself, MuseScore doesn't need privileges either: on Windows, it will just launch the MSI installer and let the user take it from there (so the user will be prompted by Windows "do you want to allow this installer to make changes blah blah" like always when you install something using an installer); on other OSs, it will just show the user the downloaded installer file, and let the user do the rest. So, exactly the same as when you had manually downloaded and double-clicked the installer file.
But Muse Hub tries to do everything automatically, and in such way that the user will never be prompted for their password once Muse Hub has been installed. Therefore it uses root permission.

**Comment by RustoMCSpit** [comment]
> If someone tells us what needs to be done, we can have a look 😉
> 
> MuseScore already looks for MuseSampler in the user's own folders first before falling back to the system-wide location. And for updating itself, MuseScore doesn't need privileges either: on Windows, it will just launch the MSI installer and let the user take it from there (so the user will be prompted by Windows "do you want to allow this installer to make changes blah blah" like always when you install something using an installer); on other OSs, it will just show the user the downloaded installer file, and let the user do the rest. So, exactly the same as when you had manually downloaded and double-clicked the installer file. But Muse Hub tries to do everything automatically, and in such way that the user will never be prompted for their password once Muse Hub has been installed. Therefore it uses root permission.

i apologise for not having the technical knowhow to answer this but i linked a discussion and can find more relevent to this. regardless, musescore shouldnt need root permission and should allow the user to manually do everything instead

**Comment by bkunda** [comment]
Having checked with our developers, there appears to be no action required here on the desktop side. 

To clarify: MuseHub used to install MuseSampler in system directories (e.g, /usr/local/lib), but this is no longer the case, so root privileges are not required. However, MuseScore is still compatible with the old installation paths (we will first try to find MuseSampler in the user-level directories, and then try to find it in the system directories).

If the Muse Hub team needs anything further from our (desktop) side, they will tell us themselves.

Therefore closing this issue as there is nothing actionable for the desktop app in relation to this issue.

**Comment by RustoMCSpit** [comment]
> Having checked with our
> Therefore closing this issue as there is nothing actionable for the desktop app in relation to this issue.

can the issue i intially linked be updated then by the devs then?
