### ISSUE TITLE
Midi Output to Widibud MIDI Interface to Roland FP-30 broken. Works in ms3, but not in ms4

### ISSUE THREAD

**Issue by marcelser** [musescore/MuseScore#19604]
### Issue type

General playback bug

### Bug description

This works perfectly in MuseScore 3.6.2 but not on 4.1.1

### Steps to reproduce

1. Start MuseScore 4.1.1
2. Select "Widibud" as Midi Input/Output Device
3. Play some mscz file (no midi output at all)

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

Probably exactly same bug as [19337](https://github.com/musescore/MuseScore/issues/19337)

**Comment by DmitryArefiev** [comment]
> Probably exactly same bug as #19337

@marcelser I thinks it is. Let's close this as duplicate and just recheck when #19337 will be fixed
