### ISSUE TITLE
Midi Keyboard input improvement request

### ISSUE THREAD

**Issue by JustTheEMailGuy** [musescore/MuseScore#19617]
### Your idea

When inputing notes via midi, I would say, it should automaticaly place the notes as heard on the keyboard.
When pressing the C on the keyboard, I think, the note that should be placed, should sound like a C, even for transposing instruments.

### Problem to be solved

It would solve the need to manualy transpose the notes or the need to memorise how every instrument transposes individualy.

**Comment by shoogle** [comment]
This is already the case if you enable 'Concert pitch' in the bottom right of the MuseScore window.

![image](https://github.com/musescore/MuseScore/assets/11011881/5c9183b3-64c6-4aa3-b0b5-87879d365a77)

Simply enable concert pitch to enter the notes, then disable it once you have finished entering to see the notes at transposed pitch.

Why don't we use the correct sound when concert pitch is disabled? The reason is that most people want to press C on the keyboard and see a C in the score, even if the sound is really Bb (or whatever). Tying it to concert pitch mode gives you the choice.

**Comment by cbjeukendrup** [comment]
See also #15594

**Comment by shoogle** [comment]
@Jojo-Schmitz does the German translation

**Comment by Jojo-Schmitz** [comment]
I've inherited that translation from before MuseScore 1.0.
I never really liked it, but didn't have a better idea, do you?

**Comment by shoogle** [comment]
It might be useful to know what 'concert pitch' is called in other applications that provide a German translation.

**Comment by Jojo-Schmitz** [comment]
Indeed

**Comment by Jojo-Schmitz** [comment]
From Wikipedia, https://de.wikipedia.org/wiki/Transponierendes_Instrument:

Transponierendes Instrument ist die übliche Bezeichnung für [Musikinstrumente](https://de.wikipedia.org/wiki/Musikinstrument), bei denen die [Notation](https://de.wikipedia.org/wiki/Notation_(Musik)) nicht in der Tonhöhe erfolgt, die erklingen soll („klingende Notation“)[[1]](https://de.wikipedia.org/wiki/Transponierendes_Instrument#cite_note-klingend-1), sondern...
...
„Klingende Notation“, „klingend notiert“ ist das Gegenteil von transponierter Notation und bedeutet: die Notation entspricht dem realen Klang. Ulrich Michels: dtv-Atlas zur Musik. Tafeln und Texte. Deutscher Taschenbuch Verlag, München 1977, Band 1, [ISBN 3-423-03022-4](https://de.wikipedia.org/wiki/Spezial:ISBN-Suche/3423030224), S. 47.

So the current translation doesn't really seem wrong

**Comment by shoogle** [comment]
The German Wikipedia refers to it as ['Kammerton'](https://de.wikipedia.org/wiki/Kammerton). Or perhaps the equivalent of "Score in C".

**Comment by Jojo-Schmitz** [comment]
"Kammerton" is a different thing IMHO. And "in C" would be confused for "in C-Major"

**Comment by Jojo-Schmitz** [comment]
I don't have Finale, Sibelius, Capella, so can't check what those call it

**Comment by JustTheEMailGuy** [comment]
Well...
I don't have any of those either and "Klingende Notation", is seemingly the official term.
The term does make sense, but back when it was invented, digital notation likely wasn't an issue.

I asked an AI if alternate terms exist and it confirmed there to be some and named: "Reale Notation", "Absolute Notation" und "Dirrigentennotation".

Problem is, AI's prone to make things up. After a quick search on all of these I ended up emptyhanded.
So I can't confirm that these in any way shape or form exist.

But the first two are at least easier to understand and there likely wouldn't be any missunderstandings :/

Still not optimal...
