### ISSUE TITLE
On Mu3, 2 and 1 import custom measure stretch gets lost

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#19625]
### Issue type

Engraving bug

### Steps to reproduce

1. Take a Mu3 (or Mu2 or Mu1) score that has modified the stretch of some measures
2. Import into Mu4
3. Notice that visually the stretch seems to get honored (and I confirmend in a debug session that it does in fact gets read, in 
https://github.com/musescore/MuseScore/blob/2c3304c8a1212d2c9eb2a596343a262563d50165/src/engraving/rw/read400/measurerw.cpp#L124-L130
4. Check measure properties and see that it is **not** recoded there!
5. Save, close, reopen and see that visually it now vanished too. In a dbug session I verified that it doesn't get written. It seems that  constructor `Measure::Measure(System* parent)` gets used, that initializes `m_userStretch` with `1.0`, and that value henceforth doesn't get updated

### MuseScore Version

4.1.1

### Regression

No.

### Operating system

Windows 11

**Comment by oktophonie** [comment]
It's intentional that the layout stretch is reset when migrating to 4.x. So the bug is just that it's ever shown in the first place.

**Comment by Jojo-Schmitz** [comment]
Why intentional? It's been chosen for a reason

**Comment by oktophonie** [comment]
See https://musescore.org/en/node/330793

**Comment by Jojo-Schmitz** [comment]
And why then is it being read in the first place?

**Comment by Jojo-Schmitz** [comment]
Why then is it read in the 1st place? Not just vor Mu3, but also for Mi2 and Mi1 scores?

**Comment by Jojo-Schmitz** [comment]
And why isn't this a regression?
