### ISSUE TITLE
Playback freeze after closing laptop (bluetooth headphones disconnect and reconnect)

### ISSUE THREAD

**Issue by JustTheEMailGuy** [musescore/MuseScore#19620]
### Issue type

General playback bug

### Bug description

Playback works just fine usualy, but after closing and reopening the laptop, playback freezes completely. This is only solvable after reloding the sheet music.

### Steps to reproduce

1. Open sheet music
2. Close laptop
3. Open laptop
4. Start playback of sheet music

### MuseScore Version

4.1.1.232071203

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

There is another thing, which could be associated with this:
When closing my laptop, my bluetooth headphones disconnect and they reconnect upon opening.
There is another unusual playback bug I only get with Musescore.
Playback has a pretty noticable speed and pitch shift, if I connect or disconnect any bluetooth audio device during the time sheet music is open.
If I reconnect (re-unconnect) the pitch and speed returns to normal.
This only happens if sheet music is already opened, reloading the sheet music will solve the problem.
Connecting or disconnecting any bluetooth audio device when no sheet music is open, will not cause there to be any pitch or speed change upon on opening the sheet music.

**Comment by zacjansheski** [comment]
Does this only occur when using the bluetooth headphones?  There are a few similar issues reported.

https://github.com/musescore/MuseScore/issues/18579
https://github.com/musescore/MuseScore/issues/17877
https://github.com/musescore/MuseScore/issues/17836

**Comment by JustTheEMailGuy** [comment]
@zacjansheski after some testing I found out that playback seems to only freeze, if my bluetooth headphones disconnect and reconnect upon closing and reopening it.

**Comment by JustTheEMailGuy** [comment]
For quite a bit it has regressed further for me, sometimes crashing the whole opened Musescore tab.

It actualy seems to be pretty mixed.
Extremely rarely nothing happens,
most of the times playback freezes and notes stop making sounds if clicked on,
and sometimes the tab crashes completely or even multiple or all of the musescore tabs.

**Comment by JustTheEMailGuy** [comment]
The issue seems to have been fixed since the switch to the new musehub and the late updates!

**Comment by zacjansheski** [comment]
Thank you! I will closed this as resolved then.

**Comment by JustTheEMailGuy** [comment]
After further testing it's sadly more complex.
I just got lucky and the freezes did become fewer, but still do happen...

Connecting the bluetooth headset **when the laptop is already open** now seemingly:
-never crashes musescore anymore,
-doesn't freeze playback 
-Doesn't cause a pitch shift in playback (which it used to)

Disconnecting the headset again when the laptop is opened:
-Crashes Musescore completely most of the time
-Does nothing the other times

Now to the thing about the Musecore Playback when the headphones connect due to opening the Laptop:
-Does nothing
-Or freezes Playback
-It **doesn't** seem to crash Musescore anymore during my tests

Sorry for any inconvenience because of my quick judgement
