### ISSUE TITLE
[Musicxml Export] - Missing rehearsal mark

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#19636]
### Issue type

Other type of issue

### Bug description

[Hovland Pilgrimsmesse op 111.zip](https://github.com/musescore/MuseScore/files/12825240/Hovland.Pilgrimsmesse.op.111.zip)

### Steps to reproduce

This is an organ part I'm transcribing for Norwegian Library For The Blind. At bar 16, the rehearsal B is missing, only an empty direction tag is exported.

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

all

**Comment by Jojo-Schmitz** [comment]
I can't confim this, the rehearsal mark B is there after export to MusicXML and import back. Just below the top staff rather than above

**Comment by hhpmusic** [comment]
I'm using v4.1.1, and only rehearsal C is exported, both A and B can't, and so do many metronome marks before multimeasure rest. Thus, all direction tags at multimeasure rests are missing. What version are you using?

**Comment by Jojo-Schmitz** [comment]
4.1.1, 3.6.2. 3.7.0 and 4.2.0 (latest build)
I only checked rehearsal mark B in measure 16, and it is there after the Mu -> XML -> Mu roundtrip

**Comment by hhpmusic** [comment]
Thanks, with the latest build it exports, probably I used a middle version with temporary regression.
