### ISSUE TITLE
Chords Symbols not correctly exported in "Parties" (french name)

### ISSUE THREAD

**Issue by FranckDhersin** [musescore/MuseScore#19651]
### Issue type

Other type of issue

### Bug description

Hello,
I've written a score whit many parts.
When I clic on "parties" (parts), the chors symbol are not correctly exported.
Only the simple ones are correct (those without m, 9, 7, 13 etc)
![Sans titre1](https://github.com/musescore/MuseScore/assets/145439357/89f8132a-9f3e-4272-8158-c95e6b73b2e8)
![Sans titre2](https://github.com/musescore/MuseScore/assets/145439357/51b725b2-4108-4d7c-acd4-3074c5ee08f9)

### Steps to reproduce

1. write a multiple part arrangement
2. on a single stave, add chords symbol
3. clic on "parties" (parts)
4. not exery symbol is exported. Only the simple ones are correct (those without m, 9, 7, 13 etc)

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

**Comment by FranckDhersin** [comment]
But if you export it via musicxml to musescore3, all the chors are correctly screened on musescore3...

**Comment by Jojo-Schmitz** [comment]
Is that score also a MusicXML import? If so, this is a known uissue and fixed i the next release

**Comment by Jojo-Schmitz** [comment]
On the part(s) check Format > Style > Chord symbols > Style and toggle away from and back to Jazz

**Comment by FranckDhersin** [comment]
Hello !
No, that wasn't an XML import, it was a multipart arrangement made from scratch with musescore4.
Your solution has fixed it.  
Many Thanks !

**Comment by MarcSabatella** [comment]
In that case we would need to you ZIP and attach your score in order to investigate.  Probably it somehow has corrupted chord description settings.

**Comment by FranckDhersin** [comment]
Here it is.
The solution described by Jojo-Schmitz works but I have to do it each time I open the score.
[Soul Bossa Nova.zip](https://github.com/musescore/MuseScore/files/12840073/Soul.Bossa.Nova.zip)

**Comment by zacjansheski** [comment]
I haven't been able to reproduce this so far.  (Using attached score, Windows 11, using French language)  
Please let me know if I am misunderstanding the issue or if anyone else is able to reproduce.

https://github.com/musescore/MuseScore/assets/69917893/8858c301-bcfc-42cf-8971-9aa2e32039e8

**Comment by MarcSabatella** [comment]
I also tried and failed to reproduce any sort of problem with the attached score or with any other.  My guess is that it was a temporary condition that fixed itself on the save of the score attached here, so that's why we aren't able to reproduce now.  But I don't know how that temporary condition was triggered.

**Comment by FranckDhersin** [comment]
@zacjansheski  @MarcSabatella 
Well, that doesn't work every time here... I have download the score from my post to be sure we have the same.
Here is the result : 

https://github.com/musescore/MuseScore/assets/145439357/004e7ce7-ba80-4513-bdfb-a54758781688

**Comment by FranckDhersin** [comment]
I've opened both the attached file and the original one on another computer : it works perfectly well....
Maybe something on my computer but I don't know what... Anyway, thanks to the solution given by jojoschmit, I can manage to go through this strange issue.
Thanks for your help but I think you should close this issue (and the other one)

(OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf) ----

**Comment by Jojo-Schmitz** [comment]
Maybe Help > Revert to factory settings birngs it back to senses?

**Comment by FranckDhersin** [comment]
Well, I have already uninstall and re-install MS4 but I still have this problem...

**Comment by Jojo-Schmitz** [comment]
Reinstall keeps the old (and potentially bogus) settigs

**Comment by FranckDhersin** [comment]
OMG ! Yes, that worked. I go back to factory settings and thats works well. Many Thanks !
