### ISSUE TITLE
Transposing and chord symbols

### ISSUE THREAD

**Issue by frareinif** [musescore/MuseScore#19667]
### Issue type

Engraving bug

### Bug description

I tried to transpose a choir piece with chord symbols. Selecting "Transpose" -> "to next key..." transposes the voices, but not the chord symbols. Choosing the "Intervall" option transposing the chord symbols works as it should.

### Steps to reproduce

1. Enter a note
2. Add a chord symbol
3. Transpose to next key
4. chord symbol does not change
5. Transpose intervall: chord symbol changes

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Linux mint 21.1

**Comment by sammik** [comment]
I cannot reproduce it.
Could you please post a affected score, or videoscreen at least?
Thank You.

**Comment by bkunda** [comment]
@zacjansheski pls also check for reproducibility

**Comment by zacjansheski** [comment]
I have also been unable to reproduce this.  As @sammik said, please share a screencapture and/or a score to help us diagnose.

**Comment by zacjansheski** [comment]
Closing as stale / not reproducible
