### ISSUE TITLE
note name plugin should change to chords when theres more than one note

### ISSUE THREAD

**Issue by RustoMCSpit** [musescore/MuseScore#19661]
### Your idea

i dont want to see c e g; i want to see 'C'

have it as a setting

### Problem to be solved

showimg notes rather than chords

**Comment by MarcSabatella** [comment]
Sounds like you want an algorithm to help identifier chords.  There are other plugins for that.  Please ask for help on the forums in musescore.org if you need further assistance.

**Comment by RustoMCSpit** [comment]
> Sounds like you want an algorithm to help identifier chords. There are other plugins for that. Please ask for help on the forums in musescore.org if you need further assistance.

should the note names plugin not have a feature to enable this? or maybe have a native plugin dedicated to this? also what other plugins are you talking about?

**Comment by MarcSabatella** [comment]
There are a number of different plugins that people have developed to attempt that sort of analysis.  See the Download / Plugins on musescore.org, look for ones that talk about "chords" or "harmony".  These are two entirely different types of plugins serving two entirely different purposes - one to simply name notes, the other to do an analysis of the music and apply some sort of AI algorithm to attempt to label chords that are identified.

Again, please use the forums on msuescore.org when you have questions about using MuseScore.  If something you are encountering is confirmed by more experienced users there to be an actual bug, or consensus is reached among people there about some new proposed feature, *then* GitHub is the place to log the the issue formally.  It's not the place to get support or brainstorm ideas.
