### ISSUE TITLE
Open file command (Ctr/Cmd+O) doesn't work

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19663]
### Steps to reproduce

1. Run MU
2. Click File>Open or use **Ctr+O** shortcut - **nothing happens**

(Drag'n' Drop works fine)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/ea4bf09b-ca07-4a28-a0e8-2ec791cc64a4

### MuseScore Version

4.2.0 master

### Regression

Yes, this used to work in **MuseScore 4.1.1**

### Operating system

Windows 10

### Additional context

Recent changes

**Comment by cbjeukendrup** [comment]
My fault, I'll fix in a few minutes

**Comment by DmitryArefiev** [comment]
Fixed in #19664
