### ISSUE TITLE
Notes no longer properly displaced for the interval of a 2nd between voices when part of a beamed cross-stave group

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#19669]
### Issue type

Engraving bug

### Bug description

This is my entry for the most opaque issue title this month.

Take this:
![image](https://github.com/musescore/MuseScore/assets/20604032/fda1e6d4-fa31-4bab-8c64-7765a0ba2fa4)

and move the C to the stave below:
![image](https://github.com/musescore/MuseScore/assets/20604032/b37d9cdf-9846-452b-88cd-8eb3519ed93c)

The D loses its proper offset. (This has been the case since at least MU3, if not forever.)

### MuseScore Version

4.0.2, 4.1.1, master

### Regression

No.

### Operating system

Linux

**Comment by Jojo-Schmitz** [comment]
Indeed the same in Mu3, But not in Mu2
