### ISSUE TITLE
note name plugin should be toggle on/off

### ISSUE THREAD

**Issue by RustoMCSpit** [musescore/MuseScore#19660]
### Your idea

i dont want to have to select a portion of my score everytime i want to see note names, i want to toggle it on so that as i type the names appear above.

also impacts color plugin

### Problem to be solved

tedious re-clicking of the same button

**Comment by MarcSabatella** [comment]
This is already present, just set this option in staff/part properties, advanced style properties.

In the future, when you have questions about how to use MuseScore, please ask for help on the support forum on musescore.org first.

**Comment by RustoMCSpit** [comment]
> This is already present, just set this option in staff/part properties, advanced style properties.
> 
> In the future, when you have questions about how to use MuseScore, please ask for help on the support forum on musescore.org first.

can there be a toggle in the tools ---> plugins window (beside where you toggle it on and off) as well?

**Comment by MarcSabatella** [comment]
These are two entireely different plugins serving two entirely different purposes - one to simply name notes, the other to do an analysis of the music and apply some sort of AI algorithm to attempt to label chords that are identified.

Again, please use the forums on msuescore.org when you have questions about using MuseScore.  If something you are encountering is confirmed by more experienced users there to be an actual bug, or consensus is reached among people there about some new proposed feature, *then* GitHub is the place to log the the issue formally.  It's not the place to get support or brainstorm ideas.
