### ISSUE TITLE
'Disable Score Download' Checkbox, 'genre' Selection are reset when updating an online score

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#19678]
### Issue type

Cloud saving/loading issue

### Bug description

When updating an existing score published to MuseScore.com, some information is lost that was previously set in the online saving menu. These include the 'Disable Score Download' option (only available to pro/staff users) and the 'genre' field (which iirc wasn't around when the musescore.com api was last updated)

### Steps to reproduce

1. Publish an online score, change the download settings or genre
2. Publish it again, replace existing score
3. Previously stated settings are reset

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by shoogle** [comment]
Thanks. I've reported this to the website team.

**Comment by shoogle** [comment]
Should be fixed now. If not, feel free to reopen.
