### ISSUE TITLE
Cue notes appearing larger than regular notes

### ISSUE THREAD

**Issue by Postoli** [musescore/MuseScore#19671]
### Issue type

Engraving bug

### Bug description

When setting notes to "Cue size", the notes are appearing larger than regular notes, rather than smaller. Screenshot is attached. 
<img width="947" alt="Screen Shot 2023-10-10 at 10 56 43 pm" src="https://github.com/musescore/MuseScore/assets/147510877/b4c64b19-2be9-4b6a-ada3-6b6c2f276814">

### Steps to reproduce

1. Insert note
2. Click Note
3. Appearence
4. Tick "Cue size"

### Screenshots/Screen recordings

<img width="947" alt="Screen Shot 2023-10-10 at 10 56 43 pm" src="https://github.com/musescore/MuseScore/assets/147510877/d51cbf46-59e8-45f7-ae6a-a43da7af44ff">

### MuseScore Version

4.1.1

### Regression

No.

### Operating system

macOS Monterey 12.2.1

**Comment by oktophonie** [comment]
Please attach a file where this can be reproduced. (Put it in a .zip or rename it to end .zip)

**Comment by Postoli** [comment]
[MS4 Cue size bug.zip](https://github.com/musescore/MuseScore/files/12856983/MS4.Cue.size.bug.zip)

**Comment by Jojo-Schmitz** [comment]
As you did set Format > Style > Sizes > Size small notes to 140% that is to be expected and as far as I can tell by design

**Comment by Postoli** [comment]
Thank you!! The score was sent to me from someone and I couldn't figure out where to find it or if there was something wrong in there

**Comment by Jojo-Schmitz** [comment]
In such cases of doubt better first go to the forums on musescore.org
