### ISSUE TITLE
Gjs-CRITICAL error under Linux Mint / Black screen 

### ISSUE THREAD

**Issue by frareinif** [musescore/MuseScore#19677]
### Issue type

Other type of issue

### Bug description

During the past week some times the screen started to change between black and normal in a 3 seconds rhythm. Sometimes the icons of my taskbar started to vanish... at first I did not relate it to my recent switch from MS 3 to 4.  I then found these messages in my ~/.xsession-errors:

```
(cinnamon:1885): Gjs-CRITICAL **: 23:03:07.015: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1885): Gjs-CRITICAL **: 23:03:07.015: The offending signal was stream-added on GvcMixerControl 0x55788af1e230.
```

These messages only appear when running MS 4 and after loading a score, sometimes immediately, sometimes after a while. I then have to close MS because waiting to long results in a no longer accessible desktop.

So as it seems, there is problem with MS 4 under Linux MInt.

### Steps to reproduce

1. Run MS 4
2. Load a score

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Linux Mint 21.1

### Additional context

Maybe helpful, I can't export to mp3, too.

**Comment by frareinif** [comment]
![grafik](https://github.com/musescore/MuseScore/assets/120204595/c0f8a98e-cd4f-4641-ac80-bd601a9e5950)

Ok, seems to be a flatpak based issue... and as it seems (https://musescore.org/en/node/321711), you don't support flatpak. :-/

**Comment by igorkorsukov** [comment]
@bkunda 

> @igorkorsukov @cbjeukendrup pls advise on this issue

We do not support flatpak

**Comment by cbjeukendrup** [comment]
If it does work correctly with the AppImage from MuseScore.org, there is not much we can do about this indeed.

**Comment by frareinif** [comment]
Ok, thanks. I removed the flatpak and now running the recent appimage, works!

**Comment by Jojo-Schmitz** [comment]
Report that problem to the flatpak folks
