### ISSUE TITLE
Brace is visually missing in Bracket Palette

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#19682]
### Issue type

UI bug

### Bug description

In the current master, the brace does not appear visually in the "Brackets" palette.

### Steps to reproduce

Open the "Brackets" palette.  The box that usually houses the brace will appear empty.  It can still be added to the score as usual.

### Screenshots/Screen recordings

<img width="318" alt="Screen Shot 2023-10-11 at 9 53 26 AM" src="https://github.com/musescore/MuseScore/assets/69917893/1e1b9fe4-7d67-4a90-9192-ff3cd6f8bb2a">

### MuseScore Version

OS: macOS 11.7, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232840302, revision: github-musescore-musescore-111ba8e

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: macOS 11.6

**Comment by zacjansheski** [comment]
This does not seem to be an issue in the current nightly, I will close this.

**Comment by zacjansheski** [comment]
Oddly, If I revert to factory settings, it reappears, but then I close and reopen the program and it disappears


https://github.com/musescore/MuseScore/assets/69917893/a680b411-8c3d-4571-8b3a-d3471c1d9cd4

**Comment by zacjansheski** [comment]
Resetting the palette does not restore visibility

**Comment by DmitryArefiev** [comment]
Fixed in #20128
