### ISSUE TITLE
Breath Controller (CC2) data is missing in MIDI Export files  

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19680]
### Issue type

Export issue

### Steps to reproduce

1. Export MIDI from [4.0.1 cresc.zip](https://github.com/musescore/MuseScore/files/12869215/4.0.1.cresc.zip) in **4.2** and **4.0.1**
2. Open that MIDI files in DAW ( [from 4.2.zip](https://github.com/musescore/MuseScore/files/12869300/from.4.2.zip) 
[from 4.0.1.zip](https://github.com/musescore/MuseScore/files/12869301/from.4.0.1.zip)) - see 4.2 midi file, breath controller data is missing

### Screenshots/Screen recordings

![Capture2](https://github.com/musescore/MuseScore/assets/90187801/94a01816-454c-40a1-be60-e2052fd2d9d9)

### MuseScore Version

4.2 master

### Regression

Yes, this used to work in **MuseScore 4.0.1**

### Operating system

all

### Additional context

Was broken in **4.0.2** with #16232

**Comment by zacjansheski** [comment]
Related to (possibly the same as) https://github.com/musescore/MuseScore/issues/19096

**Comment by DmitryArefiev** [comment]
Yeah, it's the same
