### ISSUE TITLE
Muse Sounds strings rumble

### ISSUE THREAD

**Issue by JustTheEMailGuy** [musescore/MuseScore#19700]
### Your idea

Remove rumble and minimise reverb of the string sections.

### Problem to be solved

In the background of the string sections of violins 1 and 2, is some kind of low background rumble, which sometimes turns into a full on electronic buzz and the viola section as the same issue, just less excessive.
The Violin section 1 and 2 also still have a very noticable reverb after turning reverb off.
The Cello section is free from these problems, but does features what sounds like white noise.

If you have the whole string section playing, that realy stacks.
I have a feeling that this could also be some sort of bug.

### Additional context

Musehub tells me that Musestrings is on the newest version.

**Comment by JustTheEMailGuy** [comment]
I do have an MP3 file as an example...
I just don't know a way to upload the file
Would follow instructions, if possible and needed

**Comment by Jojo-Schmitz** [comment]
Rename to .zip and attach that

**Comment by JustTheEMailGuy** [comment]
[testviolin.zip](https://github.com/musescore/MuseScore/files/12909913/testviolin.zip)

It starts at 1:38
(you do need good enough speakers/headphones to hear it, but I think it's pretty noticable though)

**Comment by sammik** [comment]
same problem reported in #14245

**Comment by sammik** [comment]
here is test file @JustTheEMailGuy posted above, with begining silence cut off.
[testviolin-cut.zip](https://github.com/musescore/MuseScore/files/12910446/testviolin-cut.zip)

**Comment by cbjeukendrup** [comment]
In that case I will close this issue as a duplicate, but add a link to it in the other issue.
