### ISSUE TITLE
Multi measure rests don't work properly

### ISSUE THREAD

**Issue by LightProgRock** [musescore/MuseScore#19710]
### Issue type

Engraving bug

### Bug description

My multi measure rests are not gathered : in parts, there are several one after the other while it should be one big multi measure rest.
I have tried looking at bars if they were specifying to cut here, but no.
This score has been created in MS3 but it's huge and I don't want to create the structure again so I'd rather avoid it if I can.
I tried to export the piano part as midi and import it again, as it's the kind of things that tends to solve this kind of bug, but to no avail

### Steps to reproduce

See the provided score, in any part except piano
[07 - Dive.zip](https://github.com/musescore/MuseScore/files/12896381/07.-.Dive.zip)

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

No.

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment]
The multi-measure rests are broken because every six measures there is an (invisible) key signature. To fix it, apply a key signature to those measures that does have accidentals, so that you can see it and select it and delete it.

**Comment by MarcSabatella** [comment]
The score contains tons of key signature changes that are breaking the multimeasure rest - (almost) all "open/atonal", so they don't actually appear in the score.  Remove them and the measures combine as expected.  Assuming you don't mean there to be *any* such changes, add a new key signature somewhere, then right click, Select / More, then Delete.  You'll see a warning that the initial key signature can't be deleted, which is true,  But the the bogus ones will now be gone.

Do you have any idea how those extra key signatures got there?  If they weren't added explicitly, that much could be a bug, but we'd need to know how to reproduce it.  But given they are there now, the rests are behaving properly.  I suppose a special exemption could be made for key signatures that don't display, but normally that should never happen, unless you deliebrately keeo re-adding C or open/atonal key changes.

**Comment by cbjeukendrup** [comment]
I've just created #19711 about the fact that these key signatures can't be seen nor deleted in a convenient way. 

Unless that the existence of these key signatures in this score was caused by a bug (instead of that you added them deliberately), I propose to close this issue and refer to #19711.

**Comment by LightProgRock** [comment]
Oh wow ! Great, thank you !
It was not a bug, this piece was once polytonal and I decided (for the sanity of the musicians, especially the pianist because the left and right hands didn't play in the same key so their signatures was different) to switch to atonal. It was a long time ago so I forgot, and it was impossible to see them so I wonder how you all did it. Thanks for your celerity !!
