### ISSUE TITLE
Widescreen monitor: Zoom level broken

### ISSUE THREAD

**Issue by VukanJ** [musescore/MuseScore#19724]
### Issue type

Other type of issue

### Bug description

I am using a widescreen monitor with resolution 5120x1440. As you can see in the attached screenshot, even though the zoom level is at 5%, nowhere near 100%, it appears like the document is presented at a very high zoom level. It is not possible to zoom out further, and therefore I am not able to edit scores. When I set the display resolution to 3840x1080 and open a document, it is at a normal zoom level. Then, when I change back to 5120x1440 and restart musescore, the zoom level is incorrect again.

### Steps to reproduce

Set resolution to 5120x1400
Open a musescore file

### Screenshots/Screen recordings

<img width="1141" alt="zoom" src="https://github.com/musescore/MuseScore/assets/12143010/9e76a931-c3a9-4b34-9b55-b9072ef3fb12">

### MuseScore Version

Musescore4 4.1.1

### Regression

I don't know

### Operating system

ArchLinux

**Comment by cbjeukendrup** [comment]
This reminds me very much of #16002, which has been fixed on the master branch just after the 4.1 branch was created, see #17759. Would be good to try the latest nightly: https://musescore.org/en/nightly-builds

**Comment by VukanJ** [comment]
Thanks! I searched for "Widescreen" under issues but nothing came up. It does indeed look like the problem that was reported before. I can't open the AppImage file, but I can try to compile musescore on the master branch

**Comment by VukanJ** [comment]
After building musescore, I can confirm that the master branch version does not have this issue any more. Thanks for the help
