### ISSUE TITLE
Musescore does not have Musesounds

### ISSUE THREAD

**Issue by RichardJECooke** [musescore/MuseScore#19721]
### Issue type

Muse Sounds bug

### Bug description

- Go to https://musescore.org/en/download
- Click the download button for Linux
- Download https://cdn.jsdelivr.net/musescore/v4.1.1/MuseScore-4.1.1.232071203-x86_64.AppImage
- Make it executable
- Run it
- New score
- View menu - Playback
- Musesounds is disabled :(

### Steps to reproduce

As above

### Screenshots/Screen recordings

None

### MuseScore Version

As above

### Regression

I don't know

### Operating system

Ubuntu 23.04

**Comment by Jojo-Schmitz** [comment]
Evern if you also download and install https://pub-c7a32e5b5d834ec9aeef400105452a42.r2.dev/Muse_Hub.deb ?

**Comment by zacjansheski** [comment]
@RichardJECooke Is this still actual?  Have you tried Jojo's link?

**Comment by zacjansheski** [comment]
Closing as stale
