### ISSUE TITLE
Capo effect is not fully reverted when Undo applied to it

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#19729]
**Steps to reproduce**
1. Open any guitar score (e.g. [Greensleeves_Guitar_Easy 2.mscz.zip](https://github.com/musescore/MuseScore/files/12917347/Greensleeves_Guitar_Easy.2.mscz.zip))
2. Play it to hear the key of the score
3. Apply a Capo 1 to all strings
4. Play to be sure the key is changed
5. Apply Undo
6. Play from the first note under the Capo sign

**Screenshot**

https://github.com/musescore/MuseScore/assets/101250347/655827ee-c517-454f-b156-457f01fbec8c

**Actual result**
Capo effect is reverted when Undo applied

**Comment by bkunda** [comment]
Unable to reproduce in latest master.

@abariska can you please recheck? 

https://github.com/musescore/MuseScore/assets/86290556/f3d36c17-da41-45c0-98c3-035230d93a53

**Comment by abariska** [comment]
Confirm.
Closed as "**Can't reproduce**"
