### ISSUE TITLE
Chord Symbols

### ISSUE THREAD

**Issue by Musicnotes234** [musescore/MuseScore#19742]
### Issue type

General playback bug

### Bug description

 I am working with Mu3 and same address I gave my students: https://musescore-3.en.softonic.com/
Everything is working good, but Chord Symbols doesn't work.
My students can't Play back with chords. They can play only melody.
We write Chord Symbols with Ctrl+k, everything is ok. But they can't get play back with chords

### Steps to reproduce

1.When I open INSPECTOR and activate chord symbol I have option PLAY - INTERPRETATION -Voicing and Duration, but my students haven't such option.
2.We tried to go FORMAT - STYLE- CHORD SYMBOLS ..., but they haven't PLAY option
3.Then we tried to press RESET ALL STYLES TO DAFAULT , but nothing help

### MuseScore Version

MuseScore3

### Regression

No.

### Operating system

Window 10

### Additional context

Only one option doesn't work- to play back with all chords

**Comment by cbjeukendrup** [comment]
Now about this issue: if I'm not mistaken, chord symbol playback was introduced in MuseScore 3.5. And from that Softonic link, it looks like it will give you MuseScore 3.3.4. So that might explain why it is not working for you.

**Comment by Jojo-Schmitz** [comment]
This issue stems from, or at least is related to https://musescore.org/en/node/355678 and there I mentioned that in Mu4 there is no Format > Style > Chord symbols Play checkbox anymore.
Isn't this a bug?

Thanks for reminding me that chord playback started with 3.5 only, I had completely forgotten that ;-)

**Comment by MarcSabatella** [comment]
I *think* it was was deliberate, replaced with a new global toggle for chord symbols program-wide (in playback toolbar settings).  Between that and the ability to mute the appropriate channels, plus set playback for chords individually, a style setting seems potentially superfluous and likely to just cause confusion to have yet another place to possibly set this.
