### ISSUE TITLE
[Tuning] Tuning can't be applied to staves when applying it to the linked one

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#19748]
**Streps to reproduce**
1. Open the score
[Tuning test.mscz.zip](https://github.com/musescore/MuseScore/files/12935399/Tuning.test.mscz.zip)

2. Try to use tuning for the linked staves by applying it to the linked one

**Screenshot**

https://github.com/musescore/MuseScore/assets/101250347/be0568d3-d25d-41bf-8f4c-b739a88d5dc4

**Expected result**
Tuning can be applied but placed above the top one from linked staves

**Comment by DmitryArefiev** [comment]
Fixed in #19771
