### ISSUE TITLE
The elements' color picker doesn't have the Alpha setting

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#19750]
### Issue type

UI bug

### Steps to reproduce

1. Select an element
2. in the Properties tab select its color
3. Notice the lack of the field to set the Alpha channel
4. Check Format > Style > Text style > (any) > Color
5. Voilá, there is the Alpha channel

### Screenshots/Screen recordings

Mu3 (Inspector and Format > Style ...):
![image](https://github.com/musescore/MuseScore/assets/1786669/008b5617-5d86-4614-96d2-800321463db3)

Mu4 properties tab:
![image](https://github.com/musescore/MuseScore/assets/1786669/d439da75-9957-49c0-9daf-c7380d60cc70)

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by jeetee** [comment]
Duplicate of #13652 ?

**Comment by Jojo-Schmitz** [comment]
Darn, yes
