### ISSUE TITLE
Trying to delete an existing system results in a crash

### ISSUE THREAD

**Issue by ardourmanual** [musescore/MuseScore#19751]
### Issue type

Crash or freeze

### Bug description

Trying to delete an existing system results in a crash

### Steps to reproduce

1. When there are 2 systems: Click on the lower system
2. Press delete.

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Linuxmint 21.2 

### Additional context

[Set_Fire_to_the_Rain - Adele LS.zip](https://github.com/musescore/MuseScore/files/12948042/Set_Fire_to_the_Rain.-.Adele.LS.zip)
 
Try it with the lower system in the score added

**Comment by Jojo-Schmitz** [comment]
Issue stems from https://musescore.org/en/node/353175

**Comment by zacjansheski** [comment]
If I am understanding this correctly, it is resolved in the current master.  Crashes in 4.1

It is one of those scores with empty instrument names.  There is a (I think unrelated) crash when selecting parts

**Comment by zacjansheski** [comment]
Parts crash is a regression to 4.1.1


https://github.com/musescore/MuseScore/assets/69917893/f52df052-7f86-4276-83c1-cbf32db0d8a2

[PartsCrash.zip](https://github.com/musescore/MuseScore/files/12953047/PartsCrash.zip)

**Comment by zacjansheski** [comment]
Please confirm the originally posted crash is resolved in the current nightly

https://musescore.org/en/nightly-builds

**Comment by ardourmanual** [comment]
Resolved in 4.1.1. nightly
