### ISSUE TITLE
Messed up 8th note connection bar across staves

### ISSUE THREAD

**Issue by vlacatocc** [musescore/MuseScore#19765]
### Issue type

Engraving bug

### Bug description

I have a problem in a specific score (posted on the bugs forum before and attached as a file there: [link](https://musescore.org/en/node/355755#comment-1211683)).

I have a problem in the attached score, measure 76 on the piano (lowest 2 staves). The piano melody is the accompaniment for the vocals in the upper staves and is displayed in a smaller format. The problem occurs with the 4th note (high "la" ("A")) in the left hand, which should (according to the original printout) be moved to the upper stave (right hand). When trying to move that note (with shortcut ctrl-shift-arrowup or with the button on the menu), it gets all messed up with some parts of the connection being drawn (in both upper and lower staves) and some not. The notehead itself however remains in the lower stave. Futhermore, the move of the note doesn't persist. Whenever changing tabs or saving the score, the note returns back to the lower stave.

The shortcut and the button do work cause I've used them throughout several other scores. It's just this one that is messed up.

This screenshot shows the current situation:

![Schermafbeelding 2023-10-18 113258](https://github.com/musescore/MuseScore/assets/23449589/0d003962-9f27-42f2-8300-f6fb909c5518)

This one the messed up situation:

![Schermafbeelding 2023-10-18 113149](https://github.com/musescore/MuseScore/assets/23449589/d6397523-26cd-4cb6-ad76-6d58818ccc74)

And finally what I want to achieve (done by drawing some manual lines for now):

![Schermafbeelding 2023-10-18 113415](https://github.com/musescore/MuseScore/assets/23449589/0bd5ec2b-f5cf-4715-9ed5-ae0ed3f590f4)

The MuseScore file itself is attached on the linked bug forum: direct link to the file [here](https://musescore.org/sites/musescore.org/files/2023-10/The%20Seal%20Lullaby%20-%20E.%20Whitacre%2C%20J.R.%20Kipling.mscz).

### Steps to reproduce

Try moving a note from the lower stave to the upper one or vice versa (on the piano staves). The fourth note in measure 76 needs to move to the upper stave by using ctrl-shift-arrowup or the button in the toolbar. The engraving gets messed up and the change is not persistent. This doesn't seem to work in other places either in this specific file.

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Windows 10 and Windows 11 (also tested by a teacher of mine on MacOS with the same result)

### Additional context

Before posting here, I made a post in the bug report forum ([here](https://musescore.org/en/node/355755#comment-1211683)). The MuseScore file that is causing the problem is attached in that post.

**Comment by oktophonie** [comment]
Nasty! I can reproduce this in 4.0 and 4.1.
In master, it _looks_ all right when I cross-stave the note (visually), but still the change doesn't persist over save/reload. Will investigate.
