### ISSUE TITLE
Debug build doesn't show bounding boxes when enabled

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#19767]
### Issue type

UI bug

### Bug description

Maybe my personal build is lacking something since apparently I'm not even getting regular boxes like H/V/T boxes to show in my debug build except for when they're selected....

but if I enable **`Diagnostic -> Engraving -> Show element bounding rectangles`**, I don't get the desired behavior as with a MS3 debug-build. Nothing shows up, even other options (like skylines). Not sure if this is a particular personal build issue, so a confirmation would be nice...

### MuseScore Version

Master branch

### Regression

I don't know

### Operating system

Linux Mint 21.1

**Comment by Jojo-Schmitz** [comment]
At least a Mu3 regression

**Comment by cbjeukendrup** [comment]
This is because the `MUE_ENABLE_ENGRAVING_PAINT_DEBUGGER` CMake option is disabled. I think we don't really need a CMake option for that, so I'll remove it.

**Comment by cbjeukendrup** [comment]
@worldwideweary Could you please check if the builds from https://github.com/musescore/MuseScore/pull/19780 have the desired effect?
