### ISSUE TITLE
Fallback to MS Basic if soundfont is missing

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#19768]
### Issue type

General playback bug

### Bug description

Currently Musescore plays silence if soundfont files are missing.
Musescore should fallback to MS Basic if it cannot load soundfonts

Reported [here](https://musescore.org/en/node/354717)
Musescore file is [here](https://musescore.org/sites/musescore.org/files/2023-09/Love_Is_Love_Is_Love_Is_Love_-_Abbie_Betinis%20%282%29.mscz)

### Steps to reproduce

1. Open [file](https://musescore.org/sites/musescore.org/files/2023-09/Love_Is_Love_Is_Love_Is_Love_-_Abbie_Betinis%20%282%29.mscz)
2. Try to play
3. No sound

### MuseScore Version

MuseScore version (64-bit): 4.2.0-232730304, revision: github-musescore-musescore-5791ea7

### Regression

I don't know

### Operating system

windows 10

**Comment by RomanPudashkin** [comment]
@mercuree should be fixed here: https://github.com/musescore/MuseScore/pull/22540

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 13
