### ISSUE TITLE
Changing repeat barline to normal doesn't render properly or doesn't happen when it's near to multi measure rest

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19778]
### Issue type

Choose option...

### Steps to reproduce

1

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/15f5e233-8c12-410a-9512-214cd9972911

### MuseScore Version

4.2 master

### Regression

No.

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
Same Mu3.

**Comment by sammik** [comment]
please, check fix #19783
