### ISSUE TITLE
Changing fermata type is not reflected in parts

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#19781]
### Issue type

Engraving bug

### Bug description

If you change fermata to short fermata, it will not reflect in parts.
Closing and reopening the project will not help.
However, if you select fermata in parts and toggle (off/on) "Style/appearance" switch, fermata will be syncronised with main score

### Steps to reproduce

1. Create score from template Treble clef
2. Open Piano parts and return to Main score
3. Enter note, select it and set "Fermata above" (this fermata will appear in parts)
4. Select note again and change fermata to "Short fermata above" (fermata in parts will NOT change)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/1bd9727f-b87f-4842-a025-a46084b730c6

### MuseScore Version

MuseScore version (64-bit): 4.2.0-232920304, revision: github-musescore-musescore-8b4c3b3

### Regression

I don't know

### Operating system

windows 10

**Comment by Jojo-Schmitz** [comment]
Confirmed. And Mu3 behaves the same
