### ISSUE TITLE
Tracking changes in the score with git

### ISSUE THREAD

**Issue by jodros** [musescore/MuseScore#19799]
### Your idea

Well, the .mscz files seems to be binary, so we cannot view the history of changes in the score using a version control system like git, what I'd like to do.

### Problem to be solved

It would be easier to revert the changes in the score made in any moment of the project, and mostly: it would be possible to read the content without having to open the app, which is useful when working with a lot of files.
Another pro is that we could use CLI tools like grep to work with the files...

**Comment by jeetee** [comment]
Consider "saving as" in the uncompressed format, which'll give you xml comparison for the score.

**Comment by jodros** [comment]
> Consider "saving as" in the uncompressed format, which'll give you xml comparison for the score.

Thank you, I've never seen this option before, problem solved.
