### ISSUE TITLE
Error compiling musescore on ubuntu mantic

### ISSUE THREAD

**Issue by dacorsa** [musescore/MuseScore#19794]
### Issue type

Other type of issue

### Bug description

i'm trying to compile musescore on ubuntu mantic , i have installed these dependencies:

sudo apt-get build-dep musescore3
sudo apt install libqt5network5 libqt5networkauth5 libqt5networkauth5-dev mksh qtquickcontrols2-5-dev libpoppler-dev libpoppler-qt5-dev libportmidi-dev midicsv

but i receive this error during compile:

-- Configuring plugins
-- Configuring plugins_tests
-- Configuring print
-- Configuring project
-- Configuring project_test
-- Configuring update
-- Configuring workspace
-- Configuring vst [stub]
-- Found 'gzip'. Man pages will be compressed.
-- Found 'ln'. Symlink aliases will be created for MuseScore executable and the man pages.
-- Configuring done (4.3s)
CMake Error at thirdparty/KDDockWidgets/src/CMakeLists.txt:298 (target_link_libraries):
  Target "kddockwidgets" links to:

    Qt5::GuiPrivate

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

-- Generating done (0.4s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
CMake Error at build.cmake:232 (message):
  Configure step failed with status 1.  See output above for details.

i have installed also these:
sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
but musescore tell me that qt is not installed:

-- The following REQUIRED packages have not been found:

 * Qt5

can you help me , please?

best regards

### Steps to reproduce

Compile musescore from github 

### MuseScore Version

latest

### Regression

Choose option...

### Operating system

ubuntu 23.10

**Comment by cbjeukendrup** [comment]
A quick search on the internet tells me that you probably need `qtbase5-private-dev` or some package like that. Alternatively, install Qt using Qt's official "online installer", as described here: https://github.com/musescore/MuseScore/wiki/Install-Qt-and-Qt-Creator#install-via-the-online-installer-recommended

**Comment by dacorsa** [comment]
thanks for your reply, installing that dependences works well but when i run the project i see:

14:32:45 dacorsa@NanoKDE /app/MuseScore $ cd /app/MuseScore ; cmake -P build.cmake -DCMAKE_BUILD_TYPE=Release run
QMake version 3.1
Using Qt version 6.5.3 in /home/dacorsa/Qt/6.5.3/gcc_64/lib
-- QT_LOCATION: /home/dacorsa/Qt
-- QT_VERSION: 6.5.3
-- QT_COMPILER: gcc_64
-- SOURCE_PATH:       /app/MuseScore
-- BUILD_PATH:        /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Make-Release
-- INSTALL_PATH:      /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Make-Release/install
-- MSCORE_EXECUTABLE: /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Make-Release/install/bin/mscore
-- CPUS: 32
-- GENERATOR: Unix Makefiles
-- BUILD_TYPE: Release

~~~~ Actualizing Run step ~~~~

RUN_ARGS: 
14:32:46.729 | INFO  | main_thread | GlobalModule | onPreInit: log path: /home/dacorsa/.local/share/MuseScore/MuseScore4Development/logs/MuseScore_231021_143246.log
14:32:46.729 | INFO  | main_thread | GlobalModule | onPreInit: === Started MuseScore 4.2.0-dev, build number  ===
14:32:46.730 | ERROR | main_thread | LanguagesService | setCurrentLanguage: Error loading translator "/app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Make-Release/install/share/mscore-4.2//locale/qt_it.qm" 
14:32:46.730 | INFO  | main_thread | IpcSocket  | connect: success connected to ipc server
/app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Make-Release/install/bin/crashpad_handler: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

can you help me?

**Comment by dacorsa** [comment]
I install qtbase5-private-dev from package manager but i'd like using qt installer, but where is?:
![immagine](https://github.com/musescore/MuseScore/assets/36949692/44cf9eaf-4949-4b39-9d65-810b92ec2691)

**Comment by cbjeukendrup** [comment]
If you're using the online installer, it is already installed by default if you install the other packages, so you don't need to do anything extra. 

However, we use Qt 5.15.2, and not Qt 6. MuseScore doesn't compile with Qt 6. 

For compiling MuseScore, you only need these components (all from Qt 5.15.2):
- "Desktop gcc 64-bit" (or whatever it's called; just the base package, so to speak)
- "Qt Network Authorization" (from "Additional libraries")

Furthermore, Qt Creator is very useful to have, for editing QML files. 

But CMake and Ninja can probably better be installed via your system's package manager; that will probably give you more up-to-date versions. These two packages are very general, and not related to Qt itself, so there isn't a good reason to install them via Qt's installer.

**Comment by dacorsa** [comment]
In my Qt installation i see only this, what is?:

![immagine](https://github.com/musescore/MuseScore/assets/36949692/bc148d85-6d00-44c9-aa7d-6f37cc4fc93b)

**Comment by dacorsa** [comment]
how can compile MuseScore with qt5.15.2? musescore find automatically qt6, can i use this:
-DCMAKE_PREFIX_PATH=/home/dacorsa/Qt/6.5.3/gcc_64 
or
-DCMAKE_INSTALL_RPATH=/home/dacorsa/Qt/6.5.3/gcc_64/lib

with /usr/lib/x86_64-linux-gnu/qt5/bin/ or /usr/lib/x86_64-linux-gnu/qt5 ??

thanks best regards

**Comment by cbjeukendrup** [comment]
See the "Locating Qt" section on this page: https://github.com/musescore/MuseScore/wiki/Compile-on-the-command-line#locating-qt

It specifies how to tell the build script where it should look for Qt. You can enter the path to Qt 5.15.2 there.

**Comment by dacorsa** [comment]
ok thanks,
so i have created a file:
nano /app/MuseScore/build_overrides.cmake

within:

# build_overrides.cmake
list(APPEND CONFIGURE_ARGS -G Ninja) # build with Ninja
# build_overrides.cmake
set(ENV{QTDIR} "/home/dacorsa/Qt/5.15.2/gcc_64") # or wherever Qt is located

but not works, see always qt 6.5.3, any ideas?

![immagine](https://github.com/musescore/MuseScore/assets/36949692/011711e7-2891-43f6-a12d-c69fcb5fe7d2)


thanks

**Comment by cbjeukendrup** [comment]
`cmake --parallel $(nproc) -P build.cmake -DCMAKE_BUILD_TYPE=Release` is the correct one.

The build script prepends the value `$ENV{QTDIR}/bin` to the PATH variable, and then looks for `qmake`. The fact that it finds the wrong version means that it somehow doesn't find `qmake` in $ENV{QTDIR}/bin. You need to double-check if `qmake` is indeed in that bin folder, and if it's executable etc. You can try if it works by running `/home/dacorsa/Qt/5.15.2/gcc_64/bin/qmake --version`.

**Comment by dacorsa** [comment]
Yes, the output is:
23:49:38 root@NanoKDE /home/dacorsa # /home/dacorsa/Qt/5.15.2/gcc_64/bin/qmake --version
QMake version 3.1
Using Qt version 5.15.2 in /home/dacorsa/Qt/5.15.2/gcc_64/lib

but the output is always:
-- Including personal build overrides
QMake version 3.1
Using Qt version 6.5.3 in /home/dacorsa/Qt/6.5.3/gcc_64/lib
-- QT_LOCATION: /home/dacorsa/Qt
-- QT_VERSION: 6.5.3
-- QT_COMPILER: gcc_64
-- SOURCE_PATH:       /app/MuseScore
-- BUILD_PATH:        /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Make-Release
-- INSTALL_PATH:      /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Make-Release/install
-- MSCORE_EXECUTABLE: /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Make-Release/install/bin/mscore
-- CPUS: 32
-- GENERATOR: Unix Makefiles
-- BUILD_TYPE: Release

~~~~ Actualizing Configure step ~~~~

CONFIGURE_ARGS:  -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Make-Release/install -DCMAKE_BUILD_TYPE=Release -DMUE_COMPILE_BUILD_64=ON
CMake Deprecation Warning at CMakeLists.txt:23 (cmake_policy):
  The OLD behavior for policy CMP0091 will be removed from a future version
  of CMake.

the file 
nano /app/MuseScore/build_overrides.cmake
is:
# build_overrides.cmake
list(APPEND CONFIGURE_ARGS -G Ninja) # build with Ninja
# build_overrides.cmake
set(ENV{QTDIR} "$ENV/home/dacorsa/Qt/5.15.2/gcc_64") # or wherever Qt is located

**Comment by cbjeukendrup** [comment]
`"$ENV/home/dacorsa/Qt/5.15.2/gcc_64"` looks incorrect. That should be either
```cmake
set(ENV{QTDIR} "$ENV{HOME}/Qt/5.15.2/gcc_64")
```
(which means: use the value of the `HOME` environment variable, followed by `/Qt/5.15.2/gcc_64`)

or
```cmake
set(ENV{QTDIR} "/home/dacorsa/Qt/5.15.2/gcc_64")
```
(which means: use literally the path `/home/dacorsa/Qt/5.15.2/gcc_64`)

**Comment by dacorsa** [comment]
ok thanks,
but same result:
nano /app/MuseScore/build_overrides.cmake
#build_overrides.cmake
set(ENV{QTDIR} "/home/dacorsa/Qt/5.15.2/gcc_64")
#build_overrides.cmake
list(APPEND CONFIGURE_ARGS -G Ninja) # build with Ninja

-- Including personal build overrides
QMake version 3.1
Using Qt version 6.5.3 in /home/dacorsa/Qt/6.5.3/gcc_64/lib
-- QT_LOCATION: /home/dacorsa/Qt
-- QT_VERSION: 6.5.3
-- QT_COMPILER: gcc_64
-- SOURCE_PATH:       /app/MuseScore
-- BUILD_PATH:        /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release
-- INSTALL_PATH:      /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release/install
-- MSCORE_EXECUTABLE: /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release/install/bin/mscore
-- CPUS: 32
-- GENERATOR: Ninja
-- BUILD_TYPE: Release

~~~~ Actualizing Build step ~~~~

[0/2] Re-checking globbed directories...

**Comment by cbjeukendrup** [comment]
And what if you try the following:
```shell
$ export PATH=/home/dacorsa/Qt/5.15.2/gcc_64/bin:$PATH
```
(i.e. set the PATH variable yourself)

After that, does `qmake --version` (just `qmake`, not the full path) produce the correct result?

And `cmake -P ./build.cmake`?

**Comment by dacorsa** [comment]
00:29:12 root@NanoKDE /home/dacorsa # cd /app/MuseScore/
00:29:54 root@NanoKDE /app/MuseScore master# export PATH=/home/dacorsa/Qt/5.15.2/gcc_64/bin:$PATH
00:29:59 root@NanoKDE /app/MuseScore master# qmake --version
QMake version 3.1
Using Qt version 5.15.2 in /home/dacorsa/Qt/5.15.2/gcc_64/lib
00:30:04 root@NanoKDE /app/MuseScore master# cmake -P ./build.cmake
-- Including personal build overrides
QMake version 3.1
Using Qt version 6.5.3 in /home/dacorsa/Qt/6.5.3/gcc_64/lib
-- QT_LOCATION: /home/dacorsa/Qt
-- QT_VERSION: 6.5.3
-- QT_COMPILER: gcc_64
-- SOURCE_PATH:       /app/MuseScore
-- BUILD_PATH:        /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-RelWithDebInfo
-- INSTALL_PATH:      /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-RelWithDebInfo/install
-- MSCORE_EXECUTABLE: /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-RelWithDebInfo/install/bin/mscore
-- CPUS: 32
-- GENERATOR: Ninja
-- BUILD_TYPE: RelWithDebInfo

~~~~ Actualizing Configure step ~~~~

CONFIGURE_ARGS:  -G Ninja -G Ninja -DCMAKE_INSTALL_PREFIX=/app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-RelWithDebInfo/install -DCMAKE_BUILD_TYPE=RelWithDebInfo -DMUE_COMPILE_BUILD_64=ON
CMake Deprecation Warning at CMakeLists.txt:23 (cmake_policy):
  The OLD behavior for policy CMP0091 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

**Comment by cbjeukendrup** [comment]
Then I really don't know. Either I'm missing something, or something strange is going on. @shoogle Could you maybe help?

**Comment by dacorsa** [comment]
ok hope someone can help us :)

**Comment by lyrra** [comment]
@dacorsa what was the result (error messages etc) of running ```cmake -P ./build.cmake ``` ? That deprecation warning CMP0091 has been around since forever and shouln't stop the build.

**Comment by dacorsa** [comment]
@lyrra for me compile well, but not start MuseScore:
-- Installing: /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release/install/lib/cmake/KDDockWidgets/KDDockWidgetsConfig.cmake
-- Installing: /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release/install/lib/cmake/KDDockWidgets/KDDockWidgetsConfigVersion.cmake
-- Installing: /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release/install/share/applications/org.musescore.MuseScore.desktop
-- Installing: /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release/install/share/metainfo/org.musescore.MuseScore.appdata.xml
-- Installing: /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release/install/share/man/man1/mscore.1.gz
-- Installing: /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release/install/share/man/man1/musescore.1.gz
-- Installing: /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release/install/share/mime/packages/musescore.xml

build.cmake: Complete after 2 minutes and 47 seconds

and running:
11:42:09 dacorsa@NanoKDE /home/dacorsa $ /app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release/install/bin/mscore 
11:42:13.904 | INFO  | main_thread | GlobalModule | onPreInit: log path: /home/dacorsa/.local/share/MuseScore/MuseScore4Development/logs/MuseScore_231022_114213.log
11:42:13.904 | INFO  | main_thread | GlobalModule | onPreInit: === Started MuseScore 4.2.0-dev, build number  ===
11:42:13.905 | ERROR | main_thread | LanguagesService | setCurrentLanguage: Error loading translator "/app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release/install/share/mscore-4.2//locale/qt_it.qm" 
11:42:13.905 | WARN  | main_thread | IpcSocket  | connect: failed connect to server
11:42:13.906 | WARN  | main_thread | IpcSocket  | connect: failed connect to server
11:42:13.906 | INFO  | main_thread | IpcSocket  | connect: success connected to ipc server
11:42:13.906 | INFO  | 140646690059968 | IpcServer  | listen: id: "84662cf44c6340509639e3da6be7870a" 
/app/MuseScore/builds/Linux-Qt6.5.3-gcc_64-Ninja-Release/install/bin/crashpad_handler: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by dacorsa** [comment]
PS: after installing:
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb

sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb

MS starts well and seems working:

![immagine](https://github.com/musescore/MuseScore/assets/36949692/6ca39880-1cbf-4bb9-b43d-09b4c30e01af)

**Comment by dacorsa** [comment]
Seems only font too small ... but it's ok

**Comment by cbjeukendrup** [comment]
My Italian is not great, but it looks like there's something wrong with paths and folders. I'd suggest deleting the build folder and trying again from scratch.

Also, the needed Qt version is 6.2.4 nowadays.

**Comment by dacorsa** [comment]
it's a problem use QT6.5.3??? i deleted all but not works

Thanks

**Comment by cbjeukendrup** [comment]
If it works for you with Qt 6.5.3, then that's also okay, but you might encounter some unexpected bugs. But as long as that doesn't disturb you, it's fine.

**Comment by cbjeukendrup** [comment]
Yes, that looks like it should work! I don't remember ever having to set `Qt6StateMachine_DIR`, but perhaps that's necessary on your machine.
Also, in general we recommend installing Qt via Qt's own online installer instead of via the package manager, because then you can select more easily which version you want and you don't need to worry about choosing the right packages, but if you have found a working set of packages for your system, then there's no need to change that. 

Is it okay to close this issue now?

**Comment by dacorsa** [comment]
ok thanks

**Comment by dacorsa** [comment]
@cbjeukendrup
