### ISSUE TITLE
Unable to select invisible fretmarks (or notes)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#19802]
### Issue type

UI bug

### Bug description

In MS3, even if a fretmark was invisible, you could still select it and cause it to sound – just like a visible fretmark. This was handy as it enabled you to make the fretmark visible again by pressing "V" without having to enable "Show invisible" first.

This feature has been lost in MS4, and attempting to click on an invisible fretmark merely selects the measure instead.

### Steps to reproduce

1. Open the attached file in MS3 and MS4. 
[invisible_fretmarks.zip](https://github.com/musescore/MuseScore/files/13069059/invisible_fretmarks.zip)
2. Try to click on the invisible voice 2 fretmarks in tablature (on string 3).

RESULT: In MS3 the invisible fretmarks are selected, make a sound, and can be made visible with "V". In MS4 the measure is selected instead; you have to enable "Show invisible" before being able to select invisible fretmarks.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64

**Comment by MarcSabatella** [comment]
To be clear - you have turned off display of invisible elements.  I don't believe it was ever intended that they would be selectable when not shown in MU3 - that seems like a bug now fixed.

**Comment by rgreen5** [comment]
> … that seems like a bug now fixed.

Agreed.
