### ISSUE TITLE
Windows 11 - Error when moving app from main monitor to alternate monitor

### ISSUE THREAD

**Issue by Gary255** [musescore/MuseScore#19809]
### Issue type

UI bug

### Steps to reproduce

1. Open musescore on main monitor
2. Maximise
3. Move to am alternate monitor (same resolution in my case)
4. The "standard" three buttons - Minimise, Maximise, Close are not displayed on the title bar.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
I can't reproduce

**Comment by Gary255** [comment]
OK. It must be specific to my PC. I have 4 monitors and can reproduce at
will. My workaround is always to use the main monitor. If I accidentally
move it to another monitor, I have to change that monitor to become main
before I can close the app.

I don't mind if you close it.

Regards,
Gary

**Comment by bkunda** [comment]
@Gary255 could you pls give us some more info about the arrangement of your displays? 
(Even a screenshot of your display settings in Win would be helpful). 
Thanks!

**Comment by Gary255** [comment]
Here are my display settings. Monitor 3 is my main monitor.

[image: image.png]

Here is a full screen MuseScore on Monitor 3

[image: image.png]

Here is the top right hand corner

[image: image.png]

Here is the top right hand corner after I move MuseScore to Monitor 1. The
minimise, restore and close buttons have disappeared.
To close <useScore, I right-click the taskbar icon and "Close Window".
[image: image.png]

Regards,
Gary

**Comment by iainhallam** [comment]
@Gary255 does pressing F11 to exit full-screen mode get the controls back for you?

**Comment by Gary255** [comment]
Iain,

I can't reproduce the problem. Perhaps an update has fixed it since I
reported.

Gary

**Comment by iainhallam** [comment]
Interesting - I'm on 4.2.1 and it's still an issue for me.

**Comment by cbjeukendrup** [comment]
Actually this seems a duplicate of https://github.com/musescore/MuseScore/issues/19942, which is more recently updated, so I'll close this one.
