### ISSUE TITLE
Crash after switching from pitched staff to unpitched percussion staff and click Edit drumset

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19812]
### Issue type

Crash

### Steps to reproduce

1. Open [crash.zip](https://github.com/musescore/MuseScore/files/13113870/crash.zip)
2. Click on Xylophone staff
3. Press N
4. Click on Drumset staff (Drum input palette appears)
5. Click Edit drumset

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/f38075f1-c118-4c5e-b74d-807f6e508868

### MuseScore Version

4.2 master

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

All

**Comment by abariska** [comment]
@DmitryArefiev it's enough to enable notation mode with selected drums/percussion instrument to trigger this crash
https://github.com/musescore/MuseScore/assets/101250347/16b6cc51-ecb8-4347-bb1e-4a76829453d4

**Comment by DmitryArefiev** [comment]
@abariska Nope.. It's another crash which was fixed in #19808 but not in master yet

**Comment by DmitryArefiev** [comment]
Fixed in #20134
