### ISSUE TITLE
Crescendo hairpin behaves opposite if it's followed by piano dynamics

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#19817]
### Issue type

General playback bug

### Bug description

This only happens if dynamics comes right after hairpin. 

Anchor point at the end of measure (playback is wrong)
![image](https://github.com/musescore/MuseScore/assets/919446/b67af72a-3b21-4484-addd-e20b24c1527d)

Anchor point before last note of measure (playback is correct)
![image](https://github.com/musescore/MuseScore/assets/919446/a1d1420d-cc0a-4b0b-b6e2-beacb3c7a4f0)

Reported [here](https://musescore.org/en/node/356012)

### Steps to reproduce

1. Create crescendo hairpin on the first measure
2. Extent hairpin to the full measure
3. Put piano dynamics on the next measure
4. Hairpin behaves opposite while playing

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/bfab66d5-a11d-4b47-8092-0942fad71cbd

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

windows 10

**Comment by mercuree** [comment]
Maybe this is an expected behavior. See [discussion](https://musescore.org/en/node/356012)
Will close this issue if confirmed

**Comment by Jojo-Schmitz** [comment]
FWIW: in Mu3 such a hairpin does nothing (to the velocity of the notes spanned), not even when given a user velocity change
