### ISSUE TITLE
Allow approximately equal signs to work on tempo text

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#19819]
### Your idea

BPM texts can sometimes have _approximately equal to_ signs in publications. From what I can tell, it seems MuseScore doesn't recognize these if there's not an actual '=' sign present in the tempo text, so the user has to explicitly change the property in the inspector/property panel for the score to follow the BPM number. An automatic conversion would work for a few approximately equal signs...

I haven't looked through MS4's code for this, but in MS3 there's:

```cpp
void TempoText::updateTempo()
      {
      // cache regexp, they are costly to create
      static QHash<QString, QRegExp> regexps;
      static QHash<QString, QRegExp> regexps2;
      QString s = plainText();
      s.replace(",", ".");
      s.replace("<sym>space</sym>"," ");
```

merely adding a few replacements before doing the regex checking after this block of code would do it.
The two signs that I have in mind are wavy and the dotted equal signs:

≒ and ≈

something like an additional:

```cpp
s.replace("≒", "=");
s.replace("≈", "=");
```

would do the trick 

### Problem to be solved

"Follow tempo text" would respect, instead of only the = sign, some approximately-equal-to signs also during playback

**Comment by Jojo-Schmitz** [comment]
How about adding "ca." (for"circa")?

**Comment by Jojo-Schmitz** [comment]
and/or "approx."?
