### ISSUE TITLE
properties 'match staff size' , text styles 'follow staff size'

### ISSUE THREAD

**Issue by fp22june** [musescore/MuseScore#19820]
### Issue type

UI bug

### Bug description

https://github.com/musescore/MuseScore/blob/master/src/notation/view/widgets/editstyle.ui#L13648C30-L13668

thank you!

### Steps to reproduce

.

### MuseScore Version

.

### Regression

No.

### Operating system

.

**Comment by fp22june** [comment]
after further testing, "xxx staff size" checkbox naming may not be accurate. the two options refer to spatium dependent.

overall scaling can be changed with 

- page settings > definiton of sp. : inch , mm

individual staff(s)'s size can be change on changed with 

- staff/part prop > line distance : how much sp.
- staff/part prop > scaling : percentage

individual staff(s) do not affect if unchecked

**Comment by bkunda** [comment]
If I understand the issue correctly, it is that the "follow staff size" checkbox in the Styles dialog bears a different label to the "match staff size" checkbox in the Properties panel. 

Bearing in mind the requirement to ensure the label is easily understandable by everyone, I'd move to use "follow staff size" in both instances.

**Comment by aditya-chari25** [comment]
Hi, I would I like to work on this issue

**Comment by aditya-chari25** [comment]
Hi, I was looking into this issue, I found the follow staff size being present in the styles dialogue but couldn't locate the "match staff size" in Properties panel, can I get a help with this, whether is it invoked by selecting the staffs in the score sheet or is it invoked in someother way?

**Comment by MarcSabatella** [comment]
Select a staff text element, look at the bottom of the Properties panel, click Show more.

**Comment by Jojo-Schmitz** [comment]
Select a text and then in the Properties tab click on "Show more"

The string "Match staff size" is in src/inspector/view/qml/MuseScore/Inspector/text/TextSettings.qml, line61

**Comment by aditya-chari25** [comment]
> Select a staff text element, look at the bottom of the Properties panel, click Show more.
Thanks @MarcSabatella, understood where the mistake needs to be changed.
