### ISSUE TITLE
Finesse engraving for guitar bends

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#19823]
This issue contains a checklist of finesse tasks for the most recent guitar bends implementation (#19746).

It will be continuously updated.

### To do
- [x] Improve horizontal spacing for double (and triple)-stop grace note bends to chords [See video](https://www.dropbox.com/s/j5mbewfepdvtg3m/grace-note-bends-chords-horizontal-alignment.mov?dl=0)
- [x] Adding bends to range selection chord causes extreme multiplication of bends [See video](https://www.dropbox.com/s/w61wj506ljn0vx0/bends-range-selection-bug.mov?dl=0)
- [x] Changing note value at the start of a bend should delete the bend [See video](https://www.dropbox.com/scl/fi/uyn6tjvgyai46ctzfw6gt/note-value-change-should-delete-bend.mov?rlkey=vyi2xztoliuiwh9opoq6bsdhm&dl=0)
- [x] Vertical arrow for pre-bends on chords collides with tab fingering 

<img width="116" alt="Screenshot 2023-10-27 at 11 02 43 am" src="https://github.com/musescore/MuseScore/assets/86290556/e9a5c93b-f50d-419f-9518-d1d4f813c2e9">

- [x] Collision avoidance required for pre-bends and slurs:

<img width="250" alt="Screenshot 2023-10-27 at 11 19 19 am" src="https://github.com/musescore/MuseScore/assets/86290556/08389dfe-8e9c-4342-983d-15808096453b">

- [x] Improve default content scaling for new bends icons in palettes

_Current_
<img width="300" alt="Screenshot 2023-10-27 at 11 21 51 am" src="https://github.com/musescore/MuseScore/assets/86290556/b4cb4ab7-c6e1-4f74-822d-cb53129120c8">

_Desired default scaling_
<img width="300" alt="Screenshot 2023-10-27 at 11 22 59 am" src="https://github.com/musescore/MuseScore/assets/86290556/500b7aa8-bdd0-4809-ac86-7999d0b754e1">

### Proposed interaction constraints
(Not necessarily bugs, but constraints to prevent janky engraving for unplayable circumstances) 
- [x] Allow no more than one grace note bend or pre-bend on a single note [See video](https://github.com/musescore/MuseScore/assets/86290556/58a1dc08-025c-4b2a-9261-473dd7042e2d)
- [x] Disallow slight bends on regular bends

<img width="115" alt="Screenshot 2023-10-27 at 10 20 23 am" src="https://github.com/musescore/MuseScore/assets/86290556/8b59732d-50d6-44c0-b313-55eccd7ed4e5">

- [x] Disallow pre-bends on regular bend arrival notes

<img width="102" alt="Screenshot 2023-10-27 at 10 21 53 am" src="https://github.com/musescore/MuseScore/assets/86290556/e7fab8e7-9840-4004-a4f0-325be60d9f07">

- [x] Disallow pre-bends on main notes preceded by a grace note bend

https://github.com/musescore/MuseScore/assets/86290556/16ef6d42-fe0a-4159-8790-01fc18bab0e9

- [x] “Show hold line” not responding

https://github.com/musescore/MuseScore/assets/86290556/22338e82-6101-4c42-9df2-609aeef99bf1

**Comment by oktophonie** [comment]
- [ ] Follow slur rules with regard to direction; in case of mixed stem direction, bend should go above. Currently:
![image](https://github.com/musescore/MuseScore/assets/20604032/8b3d077f-02d1-41ca-9b83-6355aad740a2)
