### ISSUE TITLE
Audio.com. New Upload flow

### ISSUE THREAD

**Issue by Eism** [musescore/MuseScore#19821]
### Your idea

The only difference from the current create POST is `"method":"PUT"` field. There is no need for URL encoding of the file upload, just stream binary file contents as is and specify Content-Type header with the correct mime-type.

Add a new field when creating or updating audio on the website (see `AudioComService::doCreateAudio`):
```
QJsonObject json;
json["method"] = "PUT";
```

Implement this approach for direct audio upload (see `AudioComService::doUploadAudio`):
```
curl 'https://.../...' \
-X 'PUT' \
-H 'Content-Length: 8449920' \
-H 'Content-Type: audio/mpeg'
```

### Problem to be solved

This will simplify the code for uploading audio to the website.

**Comment by bkunda** [comment]
@Eism had you intended this for v.4.2?
