### ISSUE TITLE
Chord changes made in transposed part are copied verbatim back to main score instead of being transposed back

### ISSUE THREAD

**Issue by chrisdiamand** [musescore/MuseScore#19834]
### Issue type

Engraving bug

### Bug description

Hi! I'm writing for jazz combo, so am mostly editing on the main score with all instruments in concert, then I look at the individual transposed parts occasionally to format and fix up any enharmonic issues.

However, when I modify chords in the transposed parts (e.g. saxes/trumpts), I've noticed that they do not get transposed "back" in the main score - they are instead copied back verbatim! So if I write say an A# chord in the main part, it shows up initially as B# in the trumpet part (correct) - but if I open the trumpet part and change that B# to a C, the main score will now also show C! Instead of being transposed back to Bb, (or maybe remaining as A# which would also be acceptable - I don't mind if the enharmonics are odd in the concert part as long as the individual parts are OK).

### Steps to reproduce

The most minimal reproducer I've found is as follows:

- Open MuseScore
- New score with cmd+N
- Select Brass -> Trumpet in Bb and add to the instrument list, then hit "done"
- A blank 32-bar 1-stave score score appears. Tick the "concert pitch button" in the bottom right
- Add an A# chord to the first bar by selecting the rest and hitting Ctrl-K
- Click Parts -> Open All
- Double click the B# chord and change to C
- Toggle back to the concert score - the chord is now a C in both parts!

This is a regression since MS3 - in MuseScore 3, changing B# to C in the trumpet part causes the concert part to go from A# to Bb.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/2286650/0ea78f36-66e0-4f3a-bfba-ded01f91bc9e

### MuseScore Version

OS: Debian GNU/Linux 12 (bookworm), Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

MacOS 13, Debian 

### Additional context

This happens on at least MuseScore-4.0.1.230121751-x86_64.AppImage and MuseScore-4.1.1.232071203-x86_64.AppImage, as well as 4.1.1 on OS X.

I tried building from source to bisect it, but I kept hitting the following assertion when editing the chord in the trumpet part, on `master`, `4.0.2` and `4.1.1` branches.
  musescore: /home/chris/src/MuseScore/src/engraving/libmscore/realizedharmony.cpp:212: void mu::engraving::RealizedHarmony::update(int, int, int): Assertion `_harmony->harmonyType () != HarmonyType::STANDARD || (_notes.begin()->second == rootTpc || _notes.begin()->second == bassTpc)' failed.

That assertion did not trigger using the releases I downloaded.

**Comment by Jojo-Schmitz** [comment]
Youu mean it happens in Mu3 too? The OP stated otherwise though

**Comment by zacjansheski** [comment]
> Youu mean it happens in Mu3 too? The OP stated otherwise though

I mean the issue is in all versions of 4, not a recent regression.  For developer's info.

**Comment by chrisdiamand** [comment]
> I mean the issue is in all versions of 4, not a recent regression. For developer's info.

Yep - I had no problems on MS3, but the steps I posted will trigger the issue on at least 4.0.1 and 4.1.1.

**Comment by sammik** [comment]
Another related issue - if user opens chord for editing but confirm it without changes, it changes again and again in part (or score).


https://github.com/musescore/MuseScore/assets/1646034/dcb022c4-4447-4999-be13-f92f44b217af
