### ISSUE TITLE
Exporting individual parts does not maintain resized page size

### ISSUE THREAD

**Issue by asda488** [musescore/MuseScore#19840]
### Issue type

Other type of issue

### Bug description

Resizing a score to a non-default size and then attempting to export a pdf, svg or png of a specific part results in the export having a different size to the supposed (resized) size, it is instead A4 (or original size) (this does not happen with exporting "Main score"). 

### Steps to reproduce

1. Create a new project with two or more parts
2. Resize page to non-default (for me non A4)
3. Export a specific part as png, pdf or svg
4. When opened, specific part export will not have the new size.

### Screenshots/Screen recordings

N/A

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10

### Additional context

Here is the test score I was working on (A4 landscape):  [halzion.zip](https://github.com/musescore/MuseScore/files/13187295/halzion.zip)
Here is the "Main score" export: [halzion.pdf](https://github.com/musescore/MuseScore/files/13187299/halzion.pdf)
Here is the piano part only export: [halzion-Piano.pdf](https://github.com/musescore/MuseScore/files/13187305/halzion-Piano.pdf)
Apologies if this is not the right place to file the bug.

**Comment by zacjansheski** [comment]
I think this is by design.
Parts are generated with default page size, but you can select "apply to all parts" in page settings and they will export as desired.

https://github.com/musescore/MuseScore/assets/69917893/47b1bd37-b9cf-4555-abc0-41c40d8fa0fe

**Comment by asda488** [comment]
Ah right thanks, that would make a lot of sense, looks like I didn't read the menu properly, marking as resolved.

**Comment by asda488** [comment]
Although I do have a small question, surely it is more intuitive to have the default resize apply to all parts rather than just one part?

**Comment by zacjansheski** [comment]
I believe it could cause more problems for people that don't want to use the same page sizes for score and parts.
