### ISSUE TITLE
Implement tenor clef ottava bassa

### ISSUE THREAD

**Issue by FloraCanou** [musescore/MuseScore#19843]
### Your idea

I'd like to have the tenor clef (c-clef on the second line) ottava bassa implemented, with the concert pitch switch adding/removing the little "8" for octave-transposing bass instruments written in tenor clef. 

### Problem to be solved

It could be useful for high bass instrument parts in concert pitch. 

### Prior art

Smufl has `U+E05D cClef8vb` (C clef ottava bassa). It's also present in the master palette under the symbols/clefs list. But it currently doesn't work as a clef; it's just a symbol.

**Comment by Jojo-Schmitz** [comment]
Like this?
![image](https://github.com/musescore/MuseScore/assets/1786669/0898baa0-2a97-45ea-adfe-e89c97864204)

If so, I got it working for Mu3, will port it to Mu4 too, so this issue can get assigned to me

**Comment by Jojo-Schmitz** [comment]
See #19844

**Comment by FloraCanou** [comment]
Yup, that's the functionality I asked for.
