### ISSUE TITLE
Breath marks expand measures irregularly

### ISSUE THREAD

**Issue by RedCoder09** [musescore/MuseScore#19848]
### Issue type

Engraving bug

### Bug description

When creating a score, adding breath marks made the bars wider, but other bars didn't adjust to compensate, therefore making the measure ends uneven.

### Steps to reproduce

1. Create an empty score.
2. Add a breath mark on the last bar of a system.
3. Add a whole note on the last bar of a system.

### Screenshots/Screen recordings

![Screenshot 2023-10-27 110120](https://github.com/musescore/MuseScore/assets/70098883/3a89da03-6d83-4bb4-8324-f34fb082181d)
![Screenshot 2023-10-27 121532](https://github.com/musescore/MuseScore/assets/70098883/10229c01-5bdb-4350-b9d1-5575af1088fc)
[https://musescore.org/en/node/356126](url)

### MuseScore Version

4.1.1232071203

### Regression

I don't know

### Operating system

Windows 10

### Additional context

 The Horn part in the attached score in the forum link is where this bug is happening.

**Comment by MarcSabatella** [comment]
The link doesn't seem to work, but pasting that URL directly into a browser does.  The score itself is [here](https://musescore.org/sites/musescore.org/files/2023-10/Autumn%20Dream.mscz).  To reproduce the problem, load the score, then go to Parts and open the horn part.  But I can also reproduce in a score from scratch - a breath mark on the last bar of a system within a part seems to shorten it and leave a gap - but only in certain cases.  Four quarters followed by a breath mark are fine; a whole note is not.

BTW, it seems you have all sorts of crazy high stretch values on your measures - did you maybe use that as a substitute for actually adding system breaks?  Don't - use breaks instead.  If I add breaks then reset the stretch, things do improve slightly, but it's still off.

**Comment by RedCoder09** [comment]
> The link doesn't seem to work, but pasting that URL directly into a browser does. The score itself is [here](https://musescore.org/sites/musescore.org/files/2023-10/Autumn%20Dream.mscz). To reproduce the problem, load the score, then go to Parts and open the horn part. But I can also reproduce in a score from scratch - a breath mark on the last bar of a system within a part seems to shorten it and leave a gap - but only in certain cases. Four quarters followed by a breath mark are fine; a whole note is not.
> 
> BTW, it seems you have all sorts of crazy high stretch values on your measures - did you maybe use that as a substitute for actually adding system breaks? Don't - use breaks instead. If I add breaks then reset the stretch, things do improve slightly, but it's still off.
I usually use system breaks a lot, I don't know why I had such big stretch values. I must've been possessed.
I'll add your reproduction steps into the issue - thanks for that!

**Comment by bkunda** [comment]
@miiizen can you pls look into this one?

**Comment by Jojo-Schmitz** [comment]
Mus4eScore version 5.1.1232071203 ???
