### ISSUE TITLE
Non-measure aligned hairpins can get lost in part when deleting their start/end notes and closing/reopening file

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#19853]
### Issue type

Choose option...

### Steps to reproduce

1. Create score (1 instrument is enough)
2. Write notes
3. Add hairpin, not aligned to measures
4. Open part
5. In the part, clear the notes from a measure that overlaps with the hairpin
6. Save and reopen file -> hairpin is gone in part

In the contents of the mscz file, some traces do appear: but in the mscx for the part score, only the start point of the spanner is written, and therefore it gets lost on reading.

### MuseScore Version

at least 4.1.1 and master as of 28-10-2023

### Regression

I don't know

### Additional context

_Not_ related to #19852; see this comment why: https://github.com/musescore/MuseScore/issues/19852#issuecomment-1783882445

**Comment by wizofaus** [comment]
Has anybody started working on this? If not, I can have a look.

**Comment by oktophonie** [comment]
@wizofaus No thank you, @mike-spa is looking at this.
