### ISSUE TITLE
creating parts (excerpts) is unundoable; undoing it leads into unstable state, potentialy crash

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#19857]
### Issue type

Crash or freeze

### Bug description

If creating parts (opening them for the first time) and than try undo, program leads into unstable state and potentially crash.

### Steps to reproduce

1. create new score
2. write couple of notes
3. create part
4. switch to score (not necessary)
5. undo several times (notes disapears from score, which is intended, but part remains there)
6. switch to part - see notes are in part
7. try to change some note (select and press up arrow)
8. crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1646034/52be789d-b800-4de0-8a8b-d7eaba5c0851

### MuseScore Version

master

### Regression

I don't know

### Operating system

Ubuntu 22.04

### Additional context

If save score, it is saved without part, so next time is opened correctly - without part.

**Comment by bkunda** [comment]
@zacjansheski pls check for reproducibility.
@cbjeukendrup pls comment!

**Comment by cbjeukendrup** [comment]
When I tried recently, I couldn't reproduce, but right now I can. Perhaps that means that it was a _very recent_ regression and that _my_ master branch was outdated when I tried. At least a regression on 4.1.1, as far as I can see.
