### ISSUE TITLE
Template XML includes typo

### ISSUE THREAD

**Issue by ChrisIsBomba** [musescore/MuseScore#19867]
### Issue type

File corruption

### Bug description

On line 22 of 04-Marching_Band.mscx, a quotation mark is left out. This causes the template to not be shown in MuseScore.

### Steps to reproduce

1.  Open "MuseScore 4\templates\07-Band_and_Percussion\04-Marching_Band"
2. Look at that error isn't that nuts

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

### Additional context

**<Order id="marching-band>** should be **<Order id="marching-band">**

**Comment by cbjeukendrup** [comment]
Incidentally, I discovered this too yesterday, and added a fix to https://github.com/musescore/MuseScore/pull/17615
