### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by jcstange** [musescore/MuseScore#19873]
### Issue type

Other type of issue

### Bug description

I've been trying to download Musescore 4 for Macos for a couple of days from the official website and it seems to not work. It returns: 

>Access to XMLHttpRequest at 'https://github.com/musescore/MuseScore/archive/v3.5.2.zip' from origin 'https://musescore.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

While reading the network request I found this very github repository and the release page, I've tried to download it from there, and the download also doesn't work through the browser. I got to download it from cli with:

```
curl -OL https://github.com/musescore/MuseScore/releases/download/v4.1.1/MuseScore-4.1.1.232071203.dmg
```

### Steps to reproduce

1. Click the link
2. Nothing happens

### MuseScore Version

Lastest

### Regression

No.

### Operating system

macOS Sonoma 14

**Comment by MarcSabatella** [comment]
I'm not sure where you are getting that link from - it appears to be a very old version.  You should be clicking the big download button on the main musescore.org page, or the "Download for Mac" link on the Download / Software page.  Either should actually then download the Muse Hub app which handles the rest of the download including Muse Sounds.  Even if you go out of your way to click the plain "MuseScore without Muse Hub" link (and hence without Muse Sounds), the file you should be getting is musescore.dmg

For further assistance, please ask for help on the Support forum (also on musescore.,org)

**Comment by Jojo-Schmitz** [comment]
Unless of course really wand that old version, MuseScore 3.5.2. But you could get that also from here (for Mac): https://ftp.osuosl.org/pub/musescore-nightlies/macos/3x/stable/

**Comment by jcstange** [comment]
It seems to be a Google Chrome thing, it works on Firefox.
Isn't `https://musescore.org/en/download` the official page 
I solved my problem with `curl` but I'm sure other people will be impacted by it

Also the links from `https://github.com/musescore/MuseScore/releases/` won't work for the same reason.

**Comment by bkunda** [comment]
I'm unable to reproduce this on macOS (13.1) using Chrome Version 118.0.5993.117 (and the URL pasted in the message reply above).
Is your version of Chrome up to date? 
@DmitryArefiev can you please try reproduce this too?

**Comment by DmitryArefiev** [comment]
@bkunda All works fine on my side too.
masOS **Sonoma 14.1** (23B74), **Google Chrome 119.0.6045.105** (Official Build) (arm64)
