### ISSUE TITLE
Booting problems after installing MuseScore 4

### ISSUE THREAD

**Issue by sphere-a** [musescore/MuseScore#19889]
### Issue type

Other type of issue

### Bug description

After installing MuseScore 4 from AppImage on Ubuntu 23.04 and letting the computer go into suspend mode, authentication fails and shutting down is not an option. The only possibility is a hard-restart after which Ubuntu doesn't boot anymore.

### Steps to reproduce

1. Install MuseScore 4 from AppImage on Ubuntu 23.04.
2. Let the computer go into suspend mode.
3. Try to authenticate yourself.
4. After failing to authenticate hard-restart you computer.
5. It doesn't boot anymore.

### MuseScore Version

4.x

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Ubuntu 23.04

**Comment by cbjeukendrup** [comment]
How certain is it that MuseScore was indeed the cause of this, and that it wasn't something else?
Since we have many Ubuntu users and this issue has not been reported before, it seems a bit unlikely to me...

If you're really sure that installing MuseScore caused it, it might be an AppImage issue rather than a MuseScore issue, since the "install" command is provided by AppImage and doesn't contain MuseScore-specific code.

**Comment by MarcSabatella** [comment]
Seems more likely, then, that the issue would be with FUSE2, which I assume installs some system libraries etc.  Installing the AppImage shouldn't make any changes at all that could affect the stability of the system - it just adds a ".desktop" file  and some icons and so forth - and in your local folders at that (unless you use sudo).

So maybe try getting back to a clean slate, checking to be sure all is well, then install FUSE2 and see if you can reproduce the problem.  If not, then - without doing anything else - try installing the AppImage without sudo and see if the problem truly returns.  Hard to see how that would be possible though.

**Comment by sphere-a** [comment]
After completely reinstalling Ubuntu and FUSE2 I can confirm that FUSE2 is what caused this issue.

With this in mind, how can I still install MuseScore 4 from its AppImage? (Any other approach will be very welcomed)

**Comment by MarcSabatella** [comment]
I'd start by reporting the problem with FUSE2 to its developer and/or to the Ubuntu developers.  They'll want to fix this, but they might have a workaround already.  Failing that, try the MuseScore support forum at musescore.org, where other Ubuntu users might have encountered this.  Still seems odd that you're the only person reporting this so far, given that we've got tons of Ubuntu users.  So maybe some other user has additional insight into why you experience this but others apparently do not.

**Comment by sphere-a** [comment]
Thank you for your help!
