### ISSUE TITLE
Finesse guitar bends widget in Properties

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#19898]
This issue contains a checklist of finesse tasks for the new interactive guitar bends widget in Properties (implemented in https://github.com/musescore/MuseScore/pull/19871).

It will be continuously updated.

### To do

- [x] Remove “line thickness” setting

<img width="303" alt="Screenshot 2023-11-01 at 1 14 38 pm" src="https://github.com/musescore/MuseScore/assets/86290556/647d92ee-bd92-433e-ad7e-00fea96e8ca0">

---

- [x] Accessibility
Bends not yet selectable, so I expect we haven’t yet set this up yet.

---

- [x] States

Hover state missing. Focus state should only be used for keyboard focus (accessibility) [See video](https://www.dropbox.com/s/xqn77435a9bhlnz/hover-states-widget.mov?dl=0)

---

- [x] Widget label

<img width="298" alt="Screenshot 2023-11-01 at 1 31 11 pm" src="https://github.com/musescore/MuseScore/assets/86290556/fb87afce-7ce4-40f9-a2f1-9d4d7d8c2bcb">

---

- [x] Lines should not be able to extend past the grid border:

![Frame 1669](https://github.com/musescore/MuseScore/assets/86290556/203540de-081a-4c61-b450-1cfb0693db76)

--- 

- [x] Widget should be disabled when pre-4.2 bend is selected:

<img width="566" alt="Screenshot 2023-11-01 at 2 28 08 pm" src="https://github.com/musescore/MuseScore/assets/86290556/ba32c574-8c36-4b54-8f6b-9d17090a5d57">

**Comment by bkunda** [comment]
@mike-spa @abariska FYI

**Comment by DmitryArefiev** [comment]
- [ ] Issue with **bend down**


https://github.com/musescore/MuseScore/assets/90187801/a3914f66-8580-4c46-98e8-77931c151498

**Comment by DmitryArefiev** [comment]
- [ ] Issue with **slight bend**. It should not move the initial note pitch when moving the 2nd point


https://github.com/musescore/MuseScore/assets/90187801/d847e693-984b-42e4-a1ca-456966b38f85

**Comment by bkunda** [comment]
All these tasks appear to have been completed now, so I'll close this issue for the time being.
