### ISSUE TITLE
Crash when switch on "Style / appearence" option in properties of linked frame

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#19909]
### Issue type

Crash or freeze

### Bug description

Crash when switch on "Style / appearence" option in properties of linked frame

### Steps to reproduce

1. score with linked frame
2. open part
3. in properties turn off "Style/ appearance"
4. turn it on - CRASH

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1646034/71a645fc-2670-4114-a753-d417d65aba88

### MuseScore Version

master

### Regression

No.

### Operating system

Ubuntu 22.04

**Comment by avvvvve** [comment]
It's also crashing when turning on 'Style/appearance' in parts for:

- Notes & rests
- Slurs
- Ties
- Articulations
- Dynamics
- Trills
- Horizontal frames
- Vertical frames
- Staff text
- Pedal markings

And it's _not_ crashing when turning it on for these elements:

- Tempo text
- Dots on dotted notes
- Measure numbers
- Barlines
- Key signatures
- Clefs
- System text
- Rehearsal marks

Certainly not a comprehensive list but figured it might be useful context!

**Comment by mike-spa** [comment]
@avvvvve are you sure? Cause I can easily reproduce the crash on horizontal frames, but not on the others. Could you provide detailed steps?

**Comment by avvvvve** [comment]
The above comment is fixed in #20103!
