### ISSUE TITLE
Tremolo beam disappearing

### ISSUE THREAD

**Issue by GiovanniPieri** [musescore/MuseScore#19918]
### Issue type

Engraving bug

### Bug description

Tremolo between notes, when represented as a single full beam (stem to stem) sometimes disappears depending on the position of the notes. The width of the measure may 

### Steps to reproduce

1. Create a score from scratch
2. Add quarter notes with fully beamed tremolo in between
3. According to the pitch of the notes the beam may disappear
Please, see attached video for further details

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/149786998/fd7ff489-fd86-49f4-9014-e471ee2a0654

### MuseScore Version

4.1.1 and 11/2/2023 latest nightly

### Regression

I don't know

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
I can confirm following the steps enter in the video:

1) empty treble clef score, all defaults
2) enter quarter notes C4 C5 F4 F5
3) add tremolo eighth between notes to the C4 and the F4
4) set both to the second style (showing all beams connected between stems)

Result: second tremolo beam disappears.
