### ISSUE TITLE
Playback bar erases tuplet brackets

### ISSUE THREAD

**Issue by LWChris** [musescore/MuseScore#19924]
### Issue type

UI bug

### Bug description

As the playback bar scrubs accross the score during playback, the area that was previously occluded by the moving bar needs to be constantly redrawn as the bar moves on. It appears that apart from the opening bracket hook the redrawing misses out on the bracket.

As the blue bar moves across, it looks like it erases the bracket (incl. the number and end hook) until the area is redrawn due to playback stop, a scroll event, or when playback bar moves to next system.

This happens for

- all types of tuplets (tested with 3 and 12)
- only brackets (tested with triplets that had no bracket)
- all modes (tested with Score and Publish)
- all views (tested with page view and both continuous views)
- all zooms (tested with 200, 356 and 400%)

### Steps to reproduce

1. Create a score that uses tuplets with a bracket.
2. Playback the score
3. The area with the tuplet bracket isn't redrawn until scroll or playback stop.

### Screenshots/Screen recordings

Here are three screenshots of the same bit taken at different points in time during playback.

![grafik](https://github.com/musescore/MuseScore/assets/845152/43b102b8-9635-42fe-886e-367ee3a4e70a)

### MuseScore Version

(64-bit) 4.2.0-233070304, revision: github-musescore-musescore-492cac4, portable nightly

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10 Version 19045, Arch.: x86_64

### Additional context

Worked in (64-bit) 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf (non-portable install).

**Comment by oktophonie** [comment]
See also: https://github.com/musescore/MuseScore/issues/19885

**Comment by cbjeukendrup** [comment]
I believe I had this happen recently for pedal lines as well. Still not sure how to reproduce it exactly though.

**Comment by zacjansheski** [comment]
I believe we can close this.  I can not reproduce it anymore.  Feel free to open a new issue if new evidence occurs.  Thank you!
