### ISSUE TITLE
Repetition of Speech on Articulation, Ornaments & Some Other Items (all screen readers)

### ISSUE THREAD

**Issue by jmwmusic** [musescore/MuseScore#19934]
### Issue type

UI bug

### Bug description

Screen reader is saying the name of ornaments, articulation marks, Up/down bow and various other items followed in some instances by their position twice.

### Steps to reproduce

1.  using arrow keys navigate to a note with a staccato dot.
2. You will hear the note name/octave, bar number/beat, then staccato below staccato below.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/40c871d2-88a1-4db9-8033-c74769f0da73

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

Windows 10 with NVDA

**Comment by bkunda** [comment]
@DmitryArefiev pls investigate

**Comment by DmitryArefiev** [comment]
Occurs with all screen readers. Unfortunately not fixed with #19943 

Will add video to description

**Comment by jmwmusic** [comment]
This seems to be now resolved in 4.4.  I've checked speech with NVDA on staccato, tenuto, accent, marcato, up/down bow, turn, trill and mordent and all now correctly say "articulation staccato below bar 1 beat 1" etc with no repetition.
