### ISSUE TITLE
Toggling Concert pitch for a score with Trumpet and Trombone in Bb maj does not update trumpet key signature

### ISSUE THREAD

**Issue by PowerTravel** [musescore/MuseScore#19939]
### Issue type

Engraving bug

### Bug description

Version: 
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Steps to reproduce

1: Start musescore
2: Create a score for Trumpet, trombone in Bb
3: Toggle the concert pitch checkbox on and off

Result: 
The trumpet is stuck with the Bb key signature from Concert pich on.

Expected result
The trumpet should show C key signature and the  trombone the Bb signature

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/7239156/761981ea-f275-4163-89e1-e197a2e9fa78)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/19047, and already fixed for 4.2.

**Comment by PowerTravel** [comment]
Yep, looks like a duplicate.
