### ISSUE TITLE
Loop playback markers don't reposition upon switch from/to continous horizontal view

### ISSUE THREAD

**Issue by LWChris** [musescore/MuseScore#19937]
### Issue type

UI bug

### Bug description

If you have a loop region with markers and switch from/to continous horizontal view, the markers are placed incorrectly. It appears the offsets relative to the page border aren't re-calculated upon view switch.

### Steps to reproduce

1. Create a loop region
2. Switch to continuous view (horizontal); markers are misaligned
3. Pan around; markers stay misaligned
4. Switch back to page view; markers are properly aligned again
5. Switch to continuous view (horizontal) and disable/re-enable loop; markers are now properly aligned
6. Switch back to page view; markers are now misaligned in this view.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/845152/7f18642b-3c3a-4f9e-be3a-8a6524c24e41

### MuseScore Version

(64-bit) 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10 Version 19049, Arch.: x86_64

**Comment by DmitryArefiev** [comment]
Fixed in #20625
