### ISSUE TITLE
"Move instrument down" does not work after "Remove instrument"

### ISSUE THREAD

**Issue by pavel-jelinek** [musescore/MuseScore#19957]
### Issue type

UI bug

### Steps to reproduce

1. Create a new score with four instruments - for example"SATB".
2. Press I.
3. Click "Tenor" in the right part of the "Instruments" dialog and click "Remove". Tenor will be removed, three instruments remain.
4. Immediatelly, click instrument "Soprano" and click arrow "down". 

Now Soprano should move under Alto, but it does NOT happen, no matter how many times I click.

 - - - - -
 The behavior is different if the removed voice is _immediatelly_ under the voice I am trying to move down. In that case the voice does move down, but I have to click the arrow more  than once.

### MuseScore Version

OS: Windows 10 (10.0), Arch.: x86_64, MuseScore version (64-bit): 3.6.2.548021803, revision: github-musescore-musescore-3224f34

### Regression

I don't know

### Operating system

Win 10

**Comment by zacjansheski** [comment]
Issue is from MS3.
Not an issue in current version of 4.
