### ISSUE TITLE
New Audio.com dialog glitches showing browser when publishing to musescore.com

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#19961]
### Issue type

UI bug

### Bug description

When the new "Would you also like to share your music on Audio.com?" (calling this 'new dialog') triggers, this also suppose to open musescore.com from the browser but doesn't show this successfully when the new dialog pops up (0:13 in video).

Note this only happens for uploading in musescore.com, not audio.com - this works fine.

I tried different methods, like when the new dialog doesn't appear anymore after I clicked 'remember my choice', showing musescore.com works as it should (0:57 in video)
supposed

### Steps to reproduce

Make sure it is factory reset app or download latest nightly with new implementation of this dialog

1. Open or make new score
2. Publish
3. Click publish to Musescore.com...
4. Go through publishing steps
5. See error with browser after 'saving online...' while new dialog is triggered.

### Screenshots/Screen recordings

https://www.dropbox.com/scl/fi/w5y2ojei6ls87ursshrt4/Screen-Recording-2023-11-07-at-12.56.53.mov?rlkey=ce3yghak63tq3u6jt43xap2wt&dl=0

### MuseScore Version

Latest nightly (7th November 2023)

### Regression

I don't know

### Operating system

MacOS 13

**Comment by mathesoncalum** [comment]
Trouble replicating this one, tried on Mac Ventura with Firefox & Chrome. Could you take a look @zacjansheski?
