### ISSUE TITLE
String tunings: Notation problem with Tuning presets

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#19964]
### Issue type

Other type of issue

### Bug description

There's a problem with the new String Tunings feature – specifically the presets.

If you use any of the "Tune down" or baritone settings, the tablature fretmarks look OK and play back as expected. However, the accompanying music staff notation is not likely to be readable because it is in the wrong written pitch.

For example, if the guitar tuning is standard-1 (tuned down one step) the music staff notation still needs to be written as if the guitar were tuned to EADGBE. If the tuning is Drop D-1 (tuned down one step), the music staff notation still needs to be written as if the guitar were tuned to DADGBE. And so on.

AFAICS, the solution is to provide a **playback** detune feature for the instrument staff system. See #16838. This will allow the guitarist to tune down playback but keep the string tunings at concert-pitch.

### Steps to reproduce

1. Create a blank guitar + tablature score
2. Set the tuning (using String tunings text) to standard tuned down one step, say
3. Now enter a 0 (zero) on each string in the tablature

ACTUAL RESULT: The tablature looks and sounds OK but the standard notation is in the wrong written pitch.
EXPECTED RESULT: The music staff notation should be written as if the guitar were still tuned to EADGBE, whatever the tune-down setting.

### MuseScore version
MuseScore version (64-bit): 4.2.0-233110304, revision: github-musescore-musescore-5148846

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64.

**Comment by bkunda** [comment]
Well spotted. I've been working on this one today!
As a sort of lightweight solution to implementing this, we had designed it so you could apply a transposition to the standard stave – without affecting the tablature stave (this is the bit that still isn't working) – thereby allowing the standard stave notation to be read at the appropriate "playable" pitch. 
I'm working with one of our devs at the moment to get this working and will update this issue when I have more info.
Thank you!

**Comment by bkunda** [comment]
@rgreen5 see https://github.com/musescore/MuseScore/pull/19965

**Comment by bkunda** [comment]
Closing as this should be resolved with #19965
