### ISSUE TITLE
Voice 2 lyrics melisma diappears

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#19962]
### Issue type

Engraving bug

### Bug description

I'm working on a score containing Christmas carols for SATB in closed score (staves S+A, T+B), so there are often differing rhythms between two of the parts. For instance, I have a bar at the moment that contains a dotted minim for the sopranos, and three slurred crotchets for the altos. In order to make the lyrics match the music, I'd normally (in another score writer) put the altos in voice 2, and then enter lyrics into voice 2 with underscores to match the length of the melisma.

When I do this in MuseScore 4, the line appears, then the cursor is positioned under the next bar, which generally already contains lyrics for voice 1, so I click away to exit entering the lyrics. At which point the melisma line disappears.

### Steps to reproduce

1. Open the file https://musescore.org/sites/musescore.org/files/2023-11/Disappearing%20voice%202%20lyrics%20melisma.mscz
2. Add melisma to the "Two" lyric using underscores
3. Click elsewhere to finish editing

### MuseScore Version

4.1.1-232071203, revision: [e4d1ddf](https://github.com/musescore/musescore/commit/e4d1ddf)

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

**Comment by Jojo-Schmitz** [comment]
It is actually (also) a regression vs. 4.0.2
