### ISSUE TITLE
New shortcuts shouldn't overwrite user created shortcuts (4.1.1 > 4.2 update)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19967]
### Bug description

In #19902,  some new shortcuts were added for bends **Alt+B** and **Ctr+Alt+B** (Option+B, Cmd+Option+B).

If user assigned those shortcuts for other actions in **4.1.1** (or earlier), when he update with **4.2**, those shortcuts will be reassigned to bends

### Steps to reproduce

1. In **4.1.1**, create **Alt+B** and **Ctr+Alt+B** for some actions
2. Close 4.1.1
3. Install **4.2**
4. Open 4.2
5. Check Preferences>Shortcuts:
 **Alt+B** and **Ctr+Alt+B** are present and assigned to the same actions but they don't work. 
Now **Alt+B** and **Ctr+Alt+B** work for bends (and assigned to them too)

### Screenshots/Screen recordings

**4.1.1**

https://github.com/musescore/MuseScore/assets/90187801/bd9ab0a7-332d-41b1-95b2-f0b3d016e40e

after update with **4.2**

https://github.com/musescore/MuseScore/assets/90187801/531f7603-f5eb-4e0c-8310-11894eeaab80

### MuseScore Version

6.2 master (stable version)

### Regression

I don't know

### Operating system

Windows 10

(same on Mac13.6)

### Additional context

#19902

**Comment by bkunda** [comment]
@Eism do a user's custom shortcuts currently persist when updating to a new app version? 
If they do, then I guess it should be the case that any new commands we introduce would just have no shortcut assigned to them (if the same shortcuts were already assigned elsewhere). Is this possible? 
Obviously if the user performed a factory reset, they would lose all their custom shortcuts anyway, which would be the way of establishing any new defaults we set.
