### ISSUE TITLE
New bends disappear after changing time signature

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19978]
### Steps to reproduce

1. Add some bends 
2. Change time signature in 1st measure

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/fd941c30-0fdf-4105-9144-348bf85955a5

### MuseScore Version

4.2.0 master

### Regression

Doesn't happen with old bend

### Operating system

all

**Comment by oktophonie** [comment]
This is just the same as https://github.com/musescore/MuseScore/issues/15726

**Comment by DmitryArefiev** [comment]
Oh you're right. I'll add info there. Thanks!
