### ISSUE TITLE
R shortcut to repeat staccato notes is inconsistent

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#19970]
### Issue type

Other type of issue

### Bug description

So, I run into cases of repeated staccato notes/chords a lot. And to make it go faster, I generally use the R shortcut after placing the first staccato note/chord And ideally, it would be consistent in that no matter how many notes are played, the staccato repeats along with the pitch. But that is not the case. Instead it alternates between repeating the staccato and not repeating the staccato. 

### Steps to reproduce

1. Insert a staccato note
2. Add an interval above the note
3. Press R
4. See that the staccato repeats
5. Add a second interval above
6. Press R again
7. See that the staccato does not repeat

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/6530761/fae848ca-f745-419e-b7ae-95004e85d3fb

### MuseScore Version

MuseScore 4.1.1

### Regression

I don't know

### Operating system

Windows 10

### Additional context

Expected behavior:

Repeat the staccato regardless of number of notes if staccato is toggled on.

**Comment by MarcSabatella** [comment]
The problem with adding notes to a chord removing staccato is already fixed for 4.2.  But the problem with "R" remains.  You don't need chords to see the issue either: enter a single staccato note in note input mode (Shift+S, C) then press "R" to repeat it and it's lost on the copy.  It's true indeed that it works correctly for chords of even numbers of notes only.

**Comment by DaddyLudwig** [comment]
I put in some 3 note staccato chords in a Beethoven piece just now and used the R shortcut to repeat those chords and it repeated the staccato as well as the 3 notes, so I'll close this as fixed.
