### ISSUE TITLE
[MU4 Task] Add logos on share on/publish to... dialogs

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#19980]
As the Share on/Publish on dialogs look too similar, having logos to add will help differentiate the look of the dialogs between them. The logos can be in SVG - _if they need to be in png, let me know._

Link to Figma project has been sent to the devs.

<img width="930" alt="image" src="https://github.com/musescore/MuseScore/assets/71656189/19aa83f6-3939-41ba-8211-a2af192c27f3">

I will also list the HEX colours provided of the SVG logos for each theme:
Light mode:
Musescore - 0065C3
Audio - 000000

Dark mode:
Musescore - 8EC9FF
Audio - FFFFFF

High contrast Light
Musescore - 000000
Audio - 000000

High contrast Dark
Musescore - FFFFFF
Audio - FFFFFF

**Comment by DmitryArefiev** [comment]
Implemented in #20008
