### ISSUE TITLE
MuseScore 4.1.1 problem on Mac with USB MIDI-IN interface connected to CASIO Previa PX-S5000 e-piano

### ISSUE THREAD

**Issue by zr-jl** [musescore/MuseScore#19990]
### Issue type

Other type of issue

### Bug description

While the same piano works well on the same iMac with MuseScore 3.6, it doesn't work at all with MuseScore 4.

To give you a useful overview of the problem, 
the MIDI IN function works without a hitch in the following configurations, which I used for all my tests this morning

MIDI instrument	Computer type	computer OS	 MuseScore version	other application OK
E-Piano CASIO	PC	Win 10	MS 4.1.1	
E-Piano CASIO	iMac	Monterey 	MS 3.6	
E-Piano CASIO	iMac	Monterey	-	GarageBand
Keyboard AKAI MPK miniplus	iMac	Monterey	MS 4.1.1	
Wind Synth ROBKOO	iMac	Monterey	MS 4.1.1	

But I can't enter notes with MuseScore 4.1.1 on my iMac when I connect it via USB to our new CASIO Previa PX-S5000 e-piano.

For the record, with MacOS I had no problems with MIDI configuration, as the screenshot below shows

and I made sure that the MuseScore 4 Midi I/O preferences were set correctly. 

In the player, I checked that MIDI in was activated

And I've put myself in the position of entering scores (N
[MuseScore 4 problem on Mac with USB MIDI-IN interface connected to….pdf](https://github.com/musescore/MuseScore/files/13319270/MuseScore.4.problem.on.Mac.with.USB.MIDI-IN.interface.connected.to.pdf)
) for the test 

[MuseScore 4 problem on Mac with USB MIDI-IN interface connected to….pdf](https://github.com/musescore/MuseScore/files/13319273/MuseScore.4.problem.on.Mac.with.USB.MIDI-IN.interface.connected.to.pdf)
[MuseScore 4 problem on Mac with USB MIDI-IN interface connected to….pdf](https://github.com/musescore/MuseScore/files/13319275/MuseScore.4.problem.on.Mac.with.USB.MIDI-IN.interface.connected.to.pdf)

### Steps to reproduce

see attached pdf 

### MuseScore Version

OS: macOS 12.7, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

No.

### Operating system

MacOS Monterey 12.7.1

**Comment by zr-jl** [comment]
sorry I sent the same attached pdf file 3 times

**Comment by DmitryArefiev** [comment]
@zr-jl Please try build from #20568 (https://github.com/musescore/MuseScore/actions/runs/7274008016)

**Comment by zr-jl** [comment]
@DmitryArefiev I'm willing to do the requested test, but could you please tell me in more detail the procedure to follow to apply the "software patch" before doing this test on my mac, in advance thank you for your indications or for the appropriate link.
I'll be back home on January 8 to carry out the test according to the instructions I'll have received.
In the meantime, I wish you a happy new year 2024.

**Comment by cbjeukendrup** [comment]
Instructions how to download and run this test version can be found here: https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests

**Comment by zr-jl** [comment]
@cbjeukendrup @DmitryArefiev 
I was able to carry out a quick test just before leaving on a trip.
The test was positive: notes played on the ePiano PX-S5000 connected to the Mac via USB are entered into MuseScore 4.3 dev when the software is in default entry mode (step time): 
### In short, problem #19990 no longer exists with the MuseScore 4.3 version now available.
Many thanks to everyone involved for this quick and useful correction.
Best regards,
Greetings from Switzerland,
Jean-Louis
P.S. Could you please take a stand on my suggestion/question #20750 when the time comes?
Thank you in advance for your help/opinion on this matter.
