### ISSUE TITLE
Repeats cause playback to drop measures

### ISSUE THREAD

**Issue by samsoeder** [musescore/MuseScore#19999]
### Issue type

General playback bug

### Bug description

I've noticed when working on projects that pieces containing repeats have issues dropping notes and entire measures randomly. Both in playback and on audio export.

The issue happens randomly and usually happens to an entire measure but sometimes a single note is dropped right after a repeat.

Cutting the measure and pasting it back in usually fixes the issue but sometimes it will cause a different measure to stop working.

### Steps to reproduce

1. write a piece with many repeats
2. playback randomly breaks

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/119996302/cac5e0b6-6eb9-4abb-a40a-aebc2016f32e

### MuseScore Version

 MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

### Additional context

I can provide a project file if needed. I am using a custom soundfont for playback however the bug also occurred on the version of the project using MuseSounds.

**Comment by zacjansheski** [comment]
To the best of my understanding this if fixed in 
https://github.com/musescore/MuseScore/pull/22522
@samsoeder might help to check in that build
