### ISSUE TITLE
Tuplets across barline

### ISSUE THREAD

**Issue by michaelpfox** [musescore/MuseScore#19993]
### Your idea

I'd like to be able to apply a tuplet going from one measure into another measure, across the barline.

### Problem to be solved

Can't write tuplets across barlines.

### Additional context

I have a very syncopated section and the tuplet goes across the barline.

**Comment by cbjeukendrup** [comment]
Closing as a duplicate of https://github.com/musescore/MuseScore/issues/19234. 

This is definitely something that is planned, but in preparation for this feature (and other features) MuseScore's internal data model is getting a significant overhaul, so it may still take a while.
