### ISSUE TITLE
Mac cmd+scroll zoom has unusably large increments

### ISSUE THREAD

**Issue by joexcm** [musescore/MuseScore#20007]
### Issue type

UI bug

### Bug description

On macOS, the cmd+scroll method of zooming uses different increments to cmd+/cmd- or the zoom in/out buttons in the interface, making it unusable. I am using a [conventional, generic mouse](https://www.amazon.co.uk/TeckNet-M002-Classic-Wireless-Mouse/dp/B001DHECXA) (not a magic mouse).

cmd+ and cmd- use sensible zoom increments of 25% from 15-100%, then increments of 50% from 100-200%.
However, when zooming in with cmd and the mouse scroll wheel, Musescore jumps by factors of 4. Starting at 100%, zooming out by one click goes to 25% and zooming in goes to 400%, neither of which are very useful.

I propose amending the cmd+scroll zoom combination to match the cmd+/cmd- increments. I have a suspicion this issue arose from making Musescore work nicely with the finer control of the magic mouse and touch pad.

### Steps to reproduce

Using a generic wireless USB mouse, hold cmd while scrolling in and out on a score.

### Screenshots/Screen recordings

Sensible cmd+/cmd- behaviour: https://screenrec.com/share/GRfBctSv9Y
Unusable cmd+scroll behaviour: https://screenrec.com/share/NWObrAikXy

### MuseScore Version

OS: macOS 13.5, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

macOS Ventura 13.5.2

**Comment by philipplndwhr** [comment]
That's weird, I am using almost identical specifications and I do not experience this bug. Instead, my zooming with Cmd+Scroll goes in increments of 4 percentage points.

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

I am using a Logitech B100 mouse and the following setup:
<img width="806" alt="image" src="https://github.com/musescore/MuseScore/assets/109522890/a4c13125-409e-4e7d-b378-f60147214589">
I noticed that my scrolling increments did not change even if I increase the scrolling speed in the settings.

**Comment by joexcm** [comment]
Ahh I have found the answer. 
I'm using an app called [unnatural scroll wheel](https://github.com/ther0n/UnnaturalScrollWheels) that allows you to invert the scrolling direction and the options I had selected - 'invert vertical scrolling' and 'disable scroll acceleration' - are creating the issue I had. I guess I'll have to submit to Mac scrolling convention... Thanks for your help Philipp
