### ISSUE TITLE
Bar numbers within systems collide with other objects

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#20009]
### Issue type

Engraving bug

### Bug description

When bar numbers are changed to be at intervals, rather than just at the start of each system, there's no collision avoidance. I'd expect the note in my example to have given extra space to its left to avoid colliding with the bar number, which shouldn't move. This style of bar numbers is much more common in pop a cappella music than I see elsewhere, so I run into it all the time.

### Steps to reproduce

1. Change bar numbers to be at interval 1, rather than every system, and move them closer to the stave.
2. Enter notes to fill up the line, perhaps including accidentals.

### Screenshots/Screen recordings

![2023-11-13 Musecore 4 1 1 bar number collision](https://github.com/musescore/MuseScore/assets/282030/9b64f149-2cf4-4a2b-ab28-ae3d6d4b6fb4)

This is meant to show bar 20.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

**Comment by oktophonie** [comment]
Fixed by https://github.com/musescore/MuseScore/pull/23743
