### ISSUE TITLE
simple copy/paste operation doesn't work

### ISSUE THREAD

**Issue by daeavelwyn** [musescore/MuseScore#20005]
### Issue type

Other type of issue

### Bug description

Hello,

I try to copy a line in my V2 staff to put it in my Va staff  and this simple operation doesn't seems to work on my side..
Technical infos : OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

I tried to attach my score here but it seems github doesn't allow this.

### Steps to reproduce

1-enter notes on multiple voices
2- use the selection tool (right click) to selection only note of voice 4 on the current staff
3- hit ctrl+c or use edit > copy
4- click another staff
5- hit ctrl+v or use edit > paste

Expected Behaviour : 
My notes should be copied on the new staff

actual behaviour: 
nothing happens...

![note-copy-error](https://github.com/musescore/MuseScore/assets/4292225/9ba0cb21-c3f0-4597-8159-a16b6320a045)

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Windows 10

**Comment by philipplndwhr** [comment]
Actually, I have never seen this working in my entire time using Musescore. I believe that this is not a regression and that it is not the way it would be intended to copy a bunch of notes.

I attached a demonstration of how one should do it instead, please check if this approach works for you:
1. using the selection filter (Filtre de sélection), only select the voice(s) which you intend to copy
2. holding down shift, select the range you want to copy
3. paste it in the desired target

Note that this approach does not overwrite notes in the other voices!

https://github.com/musescore/MuseScore/assets/109522890/11b129e4-9152-4b6c-88c5-9c24f39c5a64

Longer explanation:
The selection tool selects similar objects as you would do it when you hold down the Control key. You can verify that this approach does not work when you try copying notes from the first and only voice as well.

**Comment by MarcSabatella** [comment]
Indeed, this is by design - it has never been possible to copy arbitrary collections of individual notes.  Only *ranges*, which may indeed filters applied to limit to a given voice.

There has been some discussion of someday revamping the selection process in a manner that might eventually allow for copy/paste of discontiguous selections of individual notes.

**Comment by daeavelwyn** [comment]
Hello,

Thanks for the reply. As mentioned, this behaviour isn't an evidence, and I hope futher improvements would bring a bit of coherence into this.
