### ISSUE TITLE
When exported as audio at some sample rates, some MuseSounds staves sound out of sync with each other

### ISSUE THREAD

**Issue by metasekk** [musescore/MuseScore#20019]
### Issue type

General playback bug

### Bug description

MuseSampler was recently updated from version 0.4.1.34 to 0.4.3.38.

With this update a problem in the exported audio of scores seems to have appeared, similar to #19232. 
Now some instruments that use MuseSounds are also out of sync with each other when exported as audio at all sample rates except 48000 Hz (see the video below). The de-synchronisation does not affect the playback ; it is only reflected in the exported audio. 

Although the issue is similar to #19232, I logged it separately, given that, contrary to the former, the latter is clearly a regression compared to the previous versions of MuseSampler.

### Steps to reproduce

See an instance in the video below. It either involves the use of notes with and without articulations (stacatissimo, here) in a row, or pauses. The sample rate used for exportation was 44100 Hz.
See also the score provided by https://musescore.org/en/node/356677 as a comprehensive example. 

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/120221700/1a25f569-5840-4dec-a8b0-e5b70500634b

### MuseScore Version

Checked on both 4.1.1 and 4.2.0 MuseScoreNightly-233150307-master-b719b39-x86_64

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Win10 (22H2); RAM: 16Go; CPU: Intel Core i5-9300H (2.40GHz)

### Additional context

All formats (.flac, .ogg,...) are concerned. Contrary to #19232, the de-synchronization is independant of the length of the score (it doesn't need to be a large one).

It was also reported on musescore.org, in particular in https://musescore.org/en/node/356727, https://musescore.org/en/node/356626, https://musescore.org/en/node/356793, https://musescore.org/en/node/356957, https://musescore.org/en/node/357131, https://musescore.org/en/node/357236, https://musescore.org/en/node/357380, https://musescore.org/en/node/357380, https://musescore.org/en/node/357501, https://musescore.org/en/node/357666, https://musescore.org/en/node/357695. It might be related to https://musescore.org/en/node/356677, https://musescore.org/en/node/357496 and https://musescore.org/en/node/356565 as well.

**Comment by MicrotonalMatt** [comment]
I encountered this as well. For me it occurred only when I exported the score at lower sample rates, setting sample rate to 48000 Hz exported a usable file. 44100 is slightly out of sync, and 32000 is very out of sync.

**Comment by metasekk** [comment]
@MicrotonalMatt I can confirm it on my side ! Thank you very much for having pointed it out. I've modified the description of the issue accordingly.

**Comment by metasekk** [comment]
Seems to have been solved in MuseSampler 0.5.0.51 (updated yesterday). Could someone confirm ?

**Comment by metasekk** [comment]
Closing it as not reported nor reproducible since MuseSampler 0.5 (re-tested in 0.6 - **pass**).
