### ISSUE TITLE
Note with harmonics text never stops playing on playback

### ISSUE THREAD

**Issue by Munhuggas** [musescore/MuseScore#20028]
### Issue type

General playback bug

### Bug description

When adding text harmonics to a note the note never stops playing when clicking the note or starting playback of the score (in my case by pressing space).

### Steps to reproduce

1. Start a new score with any instrument that may sustain
2. Add a note of any length
3. Click the note and notice it will stop playing after a short while
4. Click the note and then add harmonics from the text palette
5. Click the note to play it indefinitely

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

macOS Ventura Version 13.5.2 (22G91)

### Additional context

A score which replicates this bug. Click on the note to make it sound forever.
[Note with harmonics sustain indefinitely.mscz.zip](https://github.com/musescore/MuseScore/files/13357608/Note.with.harmonics.sustain.indefinitely.mscz.zip)

**Comment by zacjansheski** [comment]
This has been resolved in the current nightly build.  Please confirm.

**Comment by zacjansheski** [comment]
Closing, it is fixed in master/nightly
