### ISSUE TITLE
Mac OS Sonoma MS maximized on second monitor.  Play controls and Parts/Mixer button are not clickable

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20020]
### Issue type

UI bug

### Bug description

Mac OS Sonoma MS maximized on second monitor.  Play controls and Parts/Mixer button are not clickable

### Steps to reproduce

1. On Mac OS Sonoma with a second monitor maximize MuseScore
2. Try to use playback controls or click "Mixer" or "Parts". I usually need to click multiple times.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/eae872eb-fc53-43db-9f10-f72a9f99cc57

### MuseScore Version

OS: macOS 14.0, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233170302, revision: github-musescore-musescore-371d75e

### Regression

No.

### Operating system

Mac OS 14

### Additional context

Works as expected on Mac OS 11.7.10 and 13.6 with the same hardware

**Comment by bkunda** [comment]
@zacjansheski I'm no longer able to reproduce this. Could you please re-check it?

**Comment by zacjansheski** [comment]
Apologies for the long video, but the behavior is odd for me.  You can see that it works sometimes.  It could very well be specific to my setup, if so we can certainly close this

https://github.com/user-attachments/assets/b4a2a1b6-3fbe-4ffa-b85b-74843d4163a5

**Comment by zacjansheski** [comment]
I just updated to 14.6.1 and the issue is the same for me. It seems like the hit box doesn't go all the way to the top of my screen, but the Home/Score/Publish buttons work perfectly fine.  Shortcuts work perfectly fine.

Once again, it could very well be my setup.  It would be helpful to confirm if I am the only one experiencing this.

**Comment by avvvvve** [comment]
@zacjansheski FWIW I also can't reproduce this on beta running Sonoma 14.5

**Comment by zacjansheski** [comment]
Thanks for checking!  I'll close this, assuming it is just happening on my setup.
