### ISSUE TITLE
Flute 2 is rushing ahead

### ISSUE THREAD

**Issue by Leonerd-04** [musescore/MuseScore#20021]
### Issue type

Muse Sounds bug

### Bug description

Flute 2 from MuseSounds is around a 16th note ahead of Flute 1. I did compare this to the rest of my score; Flute 1 is in time, but not Flute 2.

### Steps to reproduce

1. Write anything that uses the Flute 2 sound that involves other instruments
2. See that Flute 2 is out of sync with them by about a 16th.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/87563929/29aa8888-f14a-4a2d-ae42-84d063e8ddc2

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

KDE Neon 5.27

### Additional context

Flute 2 sounded just fine until I updated my MuseSounds library around 2 days ago.

I demonstrate this by playing Flute 1 and Flute 2 together in the recording. This is a passage that they are supposed to play in sync. I am able to get the playback in sync by switching the 2nd flute to Flute 1, or switching it to MS Basic.

**Comment by Tat0Dev** [comment]
Also having the same issue with multiple instruments in my Wind Ensemble score; a lot of non-first chair wind instruments keep leading the metronome by a 16th or more.

**Comment by as-Circe** [comment]
I'm having the same issue with flute 2 skipping ahead in chamber music. Only in the last few days since I downloaded an external SoundFont, and this issue persisted even after I deleted it and refreshed my SoundFont library.

**Comment by MarcSabatella** [comment]
If you go to Diagnostic / Muse Sampler / Check Muse Sampler, what version does it report?

As far as I can tell the issue is fixed in 0.5, so you might need to update it by running Muse Hub if it isn't already set to do automatic background updates.  I'm also not sure if 0.5 is released on all platforms or is only in beta Muse Hub / Muse Sounds Manager.

If you find the issue persists using 0.5 Muse Sampler, please ZIP and attach a score that demonstrates the problem and says exactly which notes you are hearing a problem with.

**Comment by s11141827** [comment]
Also I've typed out Robert Buckley's arrangement of the Rite of Spring by Stravinsky down on Musescore so I could listen to what it sounds like & there's like Trills w/ a Stacatto Quarter note at the end that don't actually work on all the instruments, & also the long trill when selected on Flute 2 stops short so I think musesounds woodwinds needs another update.

**Comment by Leonerd-04** [comment]
> If you go to Diagnostic / Muse Sampler / Check Muse Sampler, what version does it report?
> 
> As far as I can tell the issue is fixed in 0.5, so you might need to update it by running Muse Hub if it isn't already set to do automatic background updates. I'm also not sure if 0.5 is released on all platforms or is only in beta Muse Hub / Muse Sounds Manager.
> 
> If you find the issue persists using 0.5 Muse Sampler, please ZIP and attach a score that demonstrates the problem and says exactly which notes you are hearing a problem with.

This does seem to be the case. I switch back that score to Flute 2 and it sounds in sync now. Muse Sampler was v0.5.1.
