### ISSUE TITLE
Irregular measure indictors hidden when 'Show formatting' is disabled

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#20045]
### Issue type

UI bug

### Bug description

The grey plus (+) and minus (-) indicators that show when a bar has too many/few beats for the time signature are hidden when the **View > Show > Formatting** option is disabled.

Instead, their visibility should be controlled purely by the **View > Show > Mark irregular measures** option.

![image](https://github.com/musescore/MuseScore/assets/11011881/3bc33e07-5019-41c0-bb02-c9696b9bda61)

### Steps to reproduce

1. Create a score.
2. Right-click on first measure > Measure properties.
3. Add 1 beat to actual duration.
4. Apply & OK.
5. Right-click on second measure... subtract 1 beat from actual duration.
6. Ensure **View > Show > Mark irregular measures** is _enabled_.
7. Ensure **View > Show > Formatting** is _disabled_.

**Expected result:** The (+) and (-) indicators should be visible.
**Actual result:** The (+) and (-) indicators are hidden.

### Screenshots/Screen recordings

'Show formatting' enabled | 'Show formatting' disabled
---|---
![image](https://github.com/musescore/MuseScore/assets/11011881/053ad422-483f-4274-a1ff-af0f3cd69c33) | ![image](https://github.com/musescore/MuseScore/assets/11011881/ab234cc8-4ebc-4bf6-8ba0-c81761bc6970)

### MuseScore Version

Latest nightly

### Regression

No.

### Operating system

Windows 11

### Additional context

The **View > Show > Formatting** option rightly controls whether layout breaks are displayed (i.e. page and system breaks).

![image](https://github.com/musescore/MuseScore/assets/11011881/c5c34f51-aa8e-4ea0-8fec-6606c74fdfbe)

**Comment by aditya-chari25** [comment]
hi, if this issue hasn't been assigned to anyone, I would like to take a look into it.

**Comment by cbjeukendrup** [comment]
@aditya-chari25 Note that there is already an open PR for this issue:
<img width="1310" alt="Scherm­afbeelding 2023-12-27 om 17 26 00" src="https://github.com/musescore/MuseScore/assets/48658420/825df0a5-1e76-4d15-beb8-eb6f6449b7f7">
So it has already been taken :)
