### ISSUE TITLE
Playback speed unsteady

### ISSUE THREAD

**Issue by rtbo** [musescore/MuseScore#20051]
### Issue type

General playback bug

### Bug description

I recently switched from Fedora workstation to Ubuntu 23.10 (on the same laptop).
With default pipewire settings (buffer 1024, samplerate 48000), the playback speed is unsteady, jumping from too slow to too fast, and creating scratchy sound.
If I change pipewire settings to buffer 512, samplerate 48000, then the sound is back to normal.

On Fedora I never had this problem, (but never paid attention to pipewire settings there)

```
$ uname -a
Linux laptop 6.5.0-10-generic #10-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 13 13:49:38 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Steps to reproduce

set pipewire settings to `1024 48000`
log out / log in
open musescore and play any score

### MuseScore Version

OS: Ubuntu 23.10, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Ubuntu 23.10

**Comment by bkunda** [comment]
Could you please attach a video example?

**Comment by rtbo** [comment]
[simplescreenrecorder-2023-11-17_23.28.07.webm](https://github.com/musescore/MuseScore/assets/3889105/c4df11ca-8d90-4bc7-a445-b802db8fd5cf)

**Comment by zacjansheski** [comment]
Is this still actual?

Does it have anything to do with buffer size?  (have you tried changing in preferences?)

**Comment by rtbo** [comment]
It got a lot worse since I upgraded to Ubuntu 24.04.
I can't use MuseScore anymore at all. The buffer size of both pipewire and MS have an impact on the playback quality but none of the combinations I've used work.
I've tried the 3 buffersize proposed by MS, with 1024 and 2048 buffersize of pipewire.

pipewire 1024 / MS 1024

https://github.com/musescore/MuseScore/assets/3889105/7ed0fb6b-41c4-402e-bd2f-056f8e80bb43


pipewire 1024 / MS 2048

https://github.com/musescore/MuseScore/assets/3889105/de41a482-0b37-47bf-92ee-b68ab9d040a5


pipewire 1024 / MS 4096

https://github.com/musescore/MuseScore/assets/3889105/ddada66e-9e2d-406f-9855-7049166fb39d


pipewire 2048 / MS 1024

https://github.com/musescore/MuseScore/assets/3889105/c3ed0048-b117-4b53-8ffe-3a293a826128


pipewire 2048 / MS 2048

https://github.com/musescore/MuseScore/assets/3889105/ab793ba7-4377-41be-aa3b-04bfe1d0abea


pipewire 2048 / MS 4096 

https://github.com/musescore/MuseScore/assets/3889105/fc5a8083-d440-4bc0-8a61-3f690fbbfb95

**Comment by MarcSabatella** [comment]
Did you try 44.1 kHz sample rate?  It is a known issue that on many systems you need to set that explicitly.

**Comment by rtbo** [comment]
Yes it works normally if I set pipewire sample rate to 44100 Hz.

For other pipewire users having this problem, I had to run the following commands before starting MS:
```sh
pw-metadata -n settings 0 clock.allowed-rates '[44100 48000]'
pw-metadata -n settings 0 clock.force-rate 44100
```
(only 48000 was allowed)

**Comment by zacjansheski** [comment]
Closing as buffer size issue is covered in https://github.com/musescore/MuseScore/issues/18701
