### ISSUE TITLE
Unexpected interval changes when adjusting microtonal bends

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#20068]
### Issue type

Other type of issue

### Bug description

Two parts to this issue: 

- After setting the right curve point of the **Customize bend** widget at a microtonal interval, then moving the left curve point, the right point unexpectedly drops half a step. [See video](https://www.dropbox.com/s/ln2i4sunwedu201/microtonal-bends-3.mov?dl=0)
- When editing a `slight bend`, moving the end-point of the bend curve horizontally in the **Customize bend** widget causes unexpected accidentals to be applied to the standard stave

https://github.com/musescore/MuseScore/assets/86290556/4832f40a-7ba9-4d8f-ac1a-04f1cc0620ea

### Steps to reproduce

See above

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233210854, revision: github-musescore-musescore-6e926f9

### Regression

No.

### Operating system

macOS 13.1

### Additional context

Relates to https://github.com/musescore/MuseScore/pull/19950

**Comment by bkunda** [comment]
Can confirm this is still valid in 4.2.0-233250302

**Comment by DmitryArefiev** [comment]
Fixed in #20147
