### ISSUE TITLE
Select section not working

### ISSUE THREAD

**Issue by ale47p** [musescore/MuseScore#20062]
### Issue type

Other type of issue

### Bug description

the "select section" tool is not working in version 4. in old version 3.6.2 it worked

### Steps to reproduce

1. create 3 sections (using Section break from Palettes>Layout)
2. select the first measure of the second section
3. go to Edit > Select section
4. nothing happens

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/5f4ba17c-757a-452c-98b9-344a625e7a04

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233210304, revision: github-musescore-musescore-e475522

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

win 10

**Comment by DmitryArefiev** [comment]
Confirm on my side. Added a video demo to the description

**Comment by ale47p** [comment]
nice job guys, much appreciated!
