### ISSUE TITLE
Grace note stems over-extend below D3

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#20075]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Grace note stems increase steadily in length from c#3 downwards below the staff.
![grace_note_stems](https://github.com/musescore/MuseScore/assets/87246583/5799c799-db5c-49c5-9166-1839fd52e7d8)

### Steps to reproduce

1. Add an acciaccatura to a note on the staff
2. Move the grace note steadily down in pitch using the arrow key.

RESULT: All is well until you get to C#3 below the staff. Then the stem starts to extend in length as the note gets lower.

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233210304, revision: github-musescore-musescore-e475522

### Regression

I don't know

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by oktophonie** [comment]
The stems intentionally extend to within the stave. Admittedly they go a bit too far at the moment (https://github.com/musescore/MuseScore/issues/17827). Besides that there's no issue as far as I can tell.
