### ISSUE TITLE
Score is invalid

### ISSUE THREAD

**Issue by beanmam476** [musescore/MuseScore#20074]
### Issue type

Cloud saving/loading issue

### Bug description

I tried uploading a score to the cloud, but it didn’t work and now I can’t open it. It says “your score could not be opened, this score is invalid.” I’ve looked on the musescore forum and people say to go into the app data files, but I can’t do that because I’m on a Chromebook.

### Steps to reproduce

I have no idea how to reproduce this. I just tried saving a score to the cloud and it didn’t work.

### MuseScore Version

4

### Regression

I don't know

### Operating system

Chromebook

**Comment by beanmam476** [comment]
how do i do that?

**Comment by Jojo-Schmitz** [comment]
I missread, hence deleted my comment again.

But see https://musescore.org/en/node/356875
