### ISSUE TITLE
Bends: Can't apply a downbend after a prebend on the same fretmark (tablature)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#20082]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

It is common to apply both a prebend and a downbend to the same note/fretmark.

![prebend_downbend](https://github.com/musescore/MuseScore/assets/87246583/f8638cfb-aac9-4bdf-a9a8-8af3d4b72f0d)

The problem is that although you can perform this two-step operation _in any order_ in a standard music staff, the tablature staff insists on you applying the downbend first; if you apply a prebend first, the program won't allow you to apply a downbend to follow.

The behaviour in tablature should be the same as for a standard staff. It should be possible to apply a prebend and downbend to the same fretmark in any order.

### Steps to reproduce

1. Add a 14 fretmark to the third string (say), then a 12 fretmark.
2. Add a prebend to the 14 fretmark
3. Now try to add a standard bend to the same fretmark.

ACTUAL RESULT: Nothing happens.
EXPECTED RESULT: A downbend should be applied.

4. Now reverse the order of application: downbend first, then prebend.

RESULT: Success.

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233220304, revision: github-musescore-musescore-53d463f

### Regression

No.

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by bkunda** [comment]
Marking this as a P1 because it is a limitation on how tab-only-users can apply this particular type of common bend.

**Comment by DmitryArefiev** [comment]
Fixed in #20147
