### ISSUE TITLE
MuseScore deleted nearly all my slurs

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#20086]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Strange problem with MS4.1.1 I haven't encountered before. I have a piece I'm engraving for string quartet (4 staves) and when I opened my most recent revision, I noticed nearly all the slurs were missing from all four staves. I don't know exactly when or how this happened.

So, I was a bit frustrated, but having never seen this before I assumed it was a one-off and I re-entered all the slurs in the score in a new revision and everything looked great. I opened the individual parts and these looked fine. When I reopened the file at a later time, I noticed the slurs were gone again in 3 of the staves, but this time the cello slurs remained. I noticed the parts are just fine and contain all the slurs, so they were only deleted from the score.

Here's the only clues I can find:
1. Possibly happens on file open or close (I'm not sure of this, but I didn't observe it happening when I was working on the file).
2. Doesn't seem to delete the slurs in the individual parts.
2. It seems to keep the slurs when there is a tie inside the slur (see picture).
3. Doesn't happen with ties, only slurs.

I have no idea how this happened, nor how to recreate it, but it's a fairly serious issue.

I wish I could recreate this - I guess maybe it's possible that my file got corrupted somehow (since I've not seen this before), but that shouldn't happen anyhow, or at the program should report the file is corrupted.

Tried the forum with no results:
https://musescore.org/en/node/356795

### Steps to reproduce

Unknown.  Happened between revisions 1 (correct) and 2 (missing).  I recreated all the slurs for revision 5 and then it somehow happened again as I was working the individual parts (which have the slurs).  Maybe somebody can carefully compare revisions 1 and 2 to see if there is some clue or corruption as to what happened.
[Elegy.zip](https://github.com/musescore/MuseScore/files/13401096/Elegy.zip)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10 Home 10.0.19045 Build 19045

**Comment by cbjeukendrup** [comment]
Strange... this seems a sort of reversed version of https://github.com/musescore/MuseScore/issues/16096!

**Comment by seisfeldt** [comment]
If there is a debug mode or a debug version of the software - I'd be willing to add the slurs back and see if we can catch it.

**Comment by seisfeldt** [comment]
Also - is there a way you can diff version 1 and 2?  If I can get a list of the changes I made, maybe I can recall what I did and work through those changes again and see if I can recreate it.

**Comment by seisfeldt** [comment]
I figured out how to diff.  Here's a Diff Report from Beyond Compare.  I was making very limited corrections to the part.  You can clearly see that all these were removed whole-cloth.
 <Spanner type="Slur">
  ....
 </Spanner>

One possible clue I found is that the Thumbnail images between revision 1 and 2 both show the slurs.  Does this imply this occurred during the file save?  (i.e. after the thumbnail generation but before the file was closed?
[Diff_Report.zip](https://github.com/musescore/MuseScore/files/13401207/Diff_Report.zip)
)

**Comment by bkunda** [comment]
@zacjansheski this and the related #16096 seems to require some dedicated troubleshooting to figure out some reproduction steps. Let's mark this as a priority for once we get past 4.3.

**Comment by cbjeukendrup** [comment]
@seisfeldt Since this is very similar to #21286, and that issue has been fixed recently, I think it's likely this one has been fixed too. Could you download the latest `master` nightly build from https://musescore.org/en/nightly-builds and verify if the issue cannot be reproduced anymore?

**Comment by seisfeldt** [comment]
Hello,
I will give the nightly a try and play around a bit, esp. with creating parts. However, I was never able to reproduce the issue so it's probably okay to close this.  We can always reopen if it reoccurs.  Thanks!
