### ISSUE TITLE
Distort and Overdrive annotations do not work on notes with bends or on slides

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#20108]
### Issue type

General playback bug

### Bug description

It sounds like MS4 is not applying the Distort or Overdrive annotations to notes with bends in them, but is reverting to the clean tone. The same thing for slides.

See the attached score.
[overdrive_and_bends.zip](https://github.com/musescore/MuseScore/files/13416489/overdrive_and_bends.zip)

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233240304, revision: github-musescore-musescore-53d463f

### Regression

I don't know

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by zacjansheski** [comment]
Similar to:
https://github.com/musescore/MuseScore/issues/18654
https://github.com/musescore/MuseScore/issues/19266

**Comment by DmitryArefiev** [comment]
Fixed in #20216
