### ISSUE TITLE
Musescore 4 import / export MusicXML bar-style element

### ISSUE THREAD

**Issue by alanwhite** [musescore/MuseScore#20109]
### Issue type

Import/export issue

### Bug description

When importing a musicxml 4 file, with a barline element that sets bar-style to heavy-light, but has no repeat marks, Musescore 4 ignore and replaces with a single bar line.

When editing the score and setting the barline to what Musescore calls "reverse final barline" it renders fine on the screen. It is wrongly exported as musicxml bar-style light-heavy, i.e. the wrong way round.

### Steps to reproduce

Import a musicxml file with a barline with bar-style heavy-light and no repeat
Witness said barline rendered as a single bar line
Edit bar line to be "reverse final barline" and export as musicxml
Inspect exported file and see incorrectly tagged as bar-style light-heavy, instead of heavy-light

### MuseScore Version

OS: macOS 14.0, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

macOS Sonoma 14.0

**Comment by rettinghaus** [comment]
This has been fixed already in development version.

![image](https://github.com/musescore/MuseScore/assets/7693447/5227e441-1e01-42b0-91ae-6b17ac05af41)
