### ISSUE TITLE
Home key or fn+left arrow do not move screen to start of score when a slur/tie is selected

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20146]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When a slur/tie is selected, the end or fn+right arrow takes the focus to the end of the score as expected, but home or fn+left arrow does not go to the beginnning of the score

### Steps to reproduce

1. Create a slur/tie
2. Select the slur/tie
3. Try to use home or fn+left arrow

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/5cb0fa4f-1a97-411b-a406-d6e9312939cc

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233260301, revision: github-musescore-musescore-acb1bad

### Regression

No.

### Operating system

All

### Additional context

Until recently this actually caused a crash, that was fixed, but the actual functionality still needs to be fixed.

**Comment by cbjeukendrup** [comment]
The source code indicates that some special behaviour is intended when pressing the home key for slurs: https://github.com/musescore/MuseScore/blob/5384a156e72412c735cb34ccf6e865e3e30a8c0f/src/engraving/dom/slur.cpp#L134-L141

**Comment by wizofaus** [comment]
Happy to make this change if it's agreed what the new behaviour should be - I did a fair bit of work on this a few years back, so it's even possible something I introduced.  Does 3.6 have the same problem?

**Comment by cbjeukendrup** [comment]
3.6 works correctly. I would suggest just returning that behaviour (i.e. Home key always just scrolls to start).

We can then decide on a new, more logical, shortcut for the "reset current handle" functionality. I would propose the `R` key, in line with `Ctrl+R` for "Reset shapes and positions".

@bkunda Agree?

**Comment by wizofaus** [comment]
There is quite a lot of code to support the Home key as a special case, even this:

```bool EngravingItem::isEditAllowed(EditData& ed) const
{
    return ed.key == Key_Home;
}``` 

which seems odd...

**Comment by wizofaus** [comment]
Ok I just retested and Home works fine when a slur is selected. Only behaves differently if you select a specific grip - but:
a) on my keyboard, this is only true for the "Home" key above Num Lock, NOT the Home on the Num. Key pad!
b) it doesn't actually reset the grip position anyway! Code definitely executes but doesn't seem to do anything.

**Comment by cbjeukendrup** [comment]
I don't think it's Mac-specific. The behaviour I'm seeing is similar to what you describe:
- Whether scrolling works while a slur is selected seems to depend on how it was selected. When I click directly on the slur, the grip handles become visible; in that case, scrolling doesn't work. When I select the slur via Shift+drag, or by Ctrl+clicking it twice, or any way that doesn't cause the grip handles to become visible, scrolling works fine. 
- I'm not sure about numeric keypad since I don't have one.
- Whether "Home" actually resets the handle position, seems to depend on which handle. The upper left and upper right handles do respond, but the others don't.

**Comment by wizofaus** [comment]
The "off" property for most of the handles doesn't seem to ever be used.  I would think it would be quite useful to request a specific handle to be reset to its default position, but I'm not sure how feasible that is - it's not clear the information is even stored in a way that makes that possible.

Hmm, weird though, now I am able to reproduce the behaviour initially described even though no grip handle is shown as selected - and I can see how to fix that much at least.

**Comment by wizofaus** [comment]
Think I might have figured it out with the middle grip handle - you have to reset the offsets of the two either side.

**Comment by wizofaus** [comment]
Fixed Undo too.  And Ties.  However "home" still does nothing if the "drag" grip - which controls the overall relative position of the whole item on the score - is selected.

**Comment by Jojo-Schmitz** [comment]
It is a Mu3 regression

**Comment by wizofaus** [comment]
> Ok I just retested and Home works fine when a slur is selected. Only behaves differently if you select a specific grip - but: a) on my keyboard (Windows laptop), this is only true for the "Home" key above Num Lock, NOT the Home on the Num. Key pad! b) it doesn't actually reset the grip position anyway! Code definitely executes but doesn't seem to do anything.
> 
> Maybe initially reported issue is Mac-specific? In which case I can't really help sorry...

Confirmed that there was a difference between Home key on Numeric Keypad vs the standalone home key, have fixed.
