### ISSUE TITLE
Chord symbol text is not properly reverted when undoing after editing chord symbol

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#20165]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Steps to reproduce

1. Make score
2. Make Chord symbol (and exit edit mode)
3. Edit Chord symbol to another chord
4. Undo

Expected: changes back to old chord
Actual: nothing happens

### Screenshots/Screen recordings

Master (broken):

https://github.com/musescore/MuseScore/assets/48658420/18ebfbd3-ebc4-42d2-be39-a8ee4b553e26

(After undoing the first time, which doesn't have the desired effect, I undo another time, which removes the chord symbol as expected; but when redoing, MuseScore crashes at the very end of the video. It's due to an assertion failure though, so probably no crash occurs in release builds)

4.1.1 (correct):

https://github.com/musescore/MuseScore/assets/48658420/f29c2e0d-60d7-4096-97fa-45ef62282ff5

### MuseScore Version

master; **Regression on 4.1.1**

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

\*

**Comment by sammik** [comment]
Possibly same problem in other texts, see #20159

**Comment by miiizen** [comment]
The figured bass text is its own messy and long standing issue unfortunately - the behaviour is the same going back to MS3

**Comment by Jojo-Schmitz** [comment]
I don't see any undo problems in Mu3 with Figured bass

**Comment by Jojo-Schmitz** [comment]
Edit: Hmm, actually I do...
Edit2: but not in 3.7 it seems?

**Comment by Jojo-Schmitz** [comment]
Edit3: the issue from #20159 is in Mu3.7 too, but in general it behaves better on Furgured bass undo

**Comment by cbjeukendrup** [comment]
Git Bisect seems to point at https://github.com/musescore/MuseScore/commit/c35963f27dc6338b9cd49117145ccb6274c2b227 as the guilty commit...

**Comment by cbjeukendrup** [comment]
I'll limit the scope of this issue to the visual aspect, which is what's actually a 4.1.1 -> 4.2 regression; the playback part, which has been broken since forever, is (now) covered by #14604
