### ISSUE TITLE
Presence of full bend makes MuseScore Crash when revealing in part

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20172]
### Issue type

Crash or freeze

### Bug description

If you have a full bend in a part (score with more than one instrument) MuseScore will crash when revealing in custom part.

### Steps to reproduce

1. Open Solo Guitar
2. Add an instrument (must be above the guitar)
3. Add a full bend to the guitar part
4. Open a new custom part
5. Reveal the guitar

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/94239b73-7303-48cb-b26e-cb9ddd8ff58a

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233281140, revision: github-musescore-musescore-23f3925

### Regression

I don't know

### Operating system

All

### Additional context

Found testing Beta.  Related to new feature.

**Comment by zacjansheski** [comment]
[BendCopyPastePartCrash.zip](https://github.com/musescore/MuseScore/files/13460582/BendCopyPastePartCrash.zip)

**Comment by zacjansheski** [comment]
[BendPartCrash.zip](https://github.com/musescore/MuseScore/files/13460885/BendPartCrash.zip)

**Comment by cbjeukendrup** [comment]
I could have a fix ready quite soon, if no one else is working on this yet :)
