### ISSUE TITLE
Corruption after inserting measure before different time signature

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#20173]
### Issue type

File corruption

### Steps to reproduce

**Case 1** with empty measures

https://github.com/musescore/MuseScore/assets/90187801/481f26e2-813b-4b5d-be14-c48880a14ed3

**Case 2** with measures with notes

The bug becomes more serious if to add a notes to a new measure right after inserting 

https://github.com/musescore/MuseScore/assets/90187801/6ab64d33-65d9-4a84-a35d-aef1da29419e

### MuseScore Version

4.2 master

### Regression

Yes, this used to work in a previous version of **MuseScore 4.1.1**

### Operating system

Windows10

**Comment by sammik** [comment]
I think `const Fraction currentTimeSig = sigmap()->timesig(tick.ticks() - !options.moveSignaturesClef).nominal();`
https://github.com/musescore/MuseScore/blob/a150a9b7b0b84caadcb66962160ee895569ebedb/src/engraving/dom/masterscore.cpp#L501
should fix it

**Comment by cbjeukendrup** [comment]
@sammik Are you planning to open a PR for that, or shall I have a look?

**Comment by sammik** [comment]
@cbjeukendrup please, do it, I am out of computer until Christmass, as much as possible
thanks
