### ISSUE TITLE
Changing Clef overwrites "TAB" clef on linked staff

### ISSUE THREAD

**Issue by donbox** [musescore/MuseScore#20180]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When using a linked staff to show guitar tabulature, changing the clef in the traditional staff (say from G8vb to G) overwrites the "TAB" clef on the linked staff. Deleting the clef on the linked staff restores it to "TAB."

### Steps to reproduce

1. Create an Acoustic Guitar instrument.
2. Add a linked staff.
3. Change the linked staff from "Standard" to "Tab. 6-str. simple"
4. Select the first bar of the first staff (non-tab staff).
5. Change the clef from G8vb to G.

Then note that your "TAB" clef in the second staff now has a giant treble clef. When you delete it, the original TAB clef is restored.

### MuseScore Version

4.1.1.232071203

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 13.0

**Comment by scorster** [comment]
Sounds like the fix is underway, but [on .org there's a similar post with a simpler set of replication steps.](https://musescore.org/en/node/323807) and @worldwideweary just asked if it's been reported to Github.
