### ISSUE TITLE
Relative path resolves to http url

### ISSUE THREAD

**Issue by zDEFz** [musescore/MuseScore#20190]
### Issue type

Opening/saving issue

### Bug description

Opening a mscz file or similar from a relative path is broken with assuming from implementing #19138 
As workaround I could use `mscore "$(realpath Anime/The\ Ancient\ Magus\'\ Bride/Junna\ Here/Junna\ Here.mscz)"`

Versions tested working: 4.1.0, 4.1.1
Versions tested broken: 4.3.0

We assume this might be a QT bug https://doc.qt.io/qt-5/qurl.html#isLocalFile

### Steps to reproduce

1. `cd` into a folder e.g `/sheets`
2. `mscore Anime/The\ Ancient\ Magus\'\ Bride/Junna\ Here/Junna\ Here.mscz`

### MuseScore Version

4.3.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

archlinux

### Additional context

http://ix.io/4MqW

**Comment by cbjeukendrup** [comment]
Hm, this is a slightly stupid one indeed. It seems not a Qt bug, but rather a consequence of using [`QUrl::fromUserInput`](https://doc.qt.io/qt-5/qurl.html#fromUserInput). It looks like the other overload would have some options to fix this issue. 
Thanks for finding this!

**Comment by cbjeukendrup** [comment]
@zDEFz This PR should fix it: https://github.com/musescore/MuseScore/pull/20193 
Would be great if you could test that! (If needed, instructions can be found at https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests)

**Comment by zDEFz** [comment]
> @zDEFz This PR should fix it: #20193 Would be great if you could test that! (If needed, instructions can be found at https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests)

Yea it works.
