### ISSUE TITLE
Invalid MusicXML exported for time signatures cut time (Bach) and cut triple time

### ISSUE THREAD

**Issue by lvinken** [musescore/MuseScore#20196]
### Issue type

Import/export issue

### Bug description

See [this page of the MusicXML spec](https://www.w3.org/2021/06/musicxml40/musicxml-reference/data-types/time-symbol/) for the allowed time signatures symbols. It contains neither "cut2" nor "cut3".

The solution is trivial, in ExportMusicXml::timesig() remove the if statements with TimeSigType::CUT_BACH and TimeSigType::CUT_TRIPLE.

### Steps to reproduce

1. Export the MuseScore file in the attached file as MusicXML
2. Import and validate the result

### MuseScore Version

unstable prerelease for 4.2.0

### Regression

No.

### Operating system

Ubuntu 22.04

### Additional context

[Time_sig_MS420.zip](https://github.com/musescore/MuseScore/files/13466259/Time_sig_MS420.zip)

**Comment by Jojo-Schmitz** [comment]
My screwup, I'll fix it ;-)
