### ISSUE TITLE
MusicXML import of common and cut time is too strict

### ISSUE THREAD

**Issue by lvinken** [musescore/MuseScore#20207]
### Issue type

Import/export issue

### Bug description

The time signature with common symbol is imported only when the signature is 4/4, cut when 2/2. This is overly strict. In case common or cut is not recognized, the time signature is ignored and the nominal measure duration will be set to 4/4, which may be incorrect. See determineTimeSig() in files importmxmlpass1.cpp and importmxmlpass2.cpp.

### Steps to reproduce

1. import attached file [Time_sig_common_cut_4_2_MS420.zip](https://github.com/musescore/MuseScore/files/13467807/Time_sig_common_cut_4_2_MS420.zip)

### MuseScore Version

MuseScore unstable prerelease for 4.2.0

### Regression

No.

### Operating system

Ubuntu 22.04

**Comment by Jojo-Schmitz** [comment]
As #20197 is in very close proximity, I might add that there

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz I guess it would indeed be fine to include that in #20197 and #20198. That solution doesn't ensure that the time signature has correct measure length for those symbols (i.e. a whole note) but that's no hard requirement in MuseScore either, right?

**Comment by Jojo-Schmitz** [comment]
Well, __not__ ensuring the 'correct' measure length is what this issue is all about ;-)

**Comment by cbjeukendrup** [comment]
Well there is a distinction between allowing 4/4 instead of 2/2 and allowing 3/8 instead of 2/2 :)

**Comment by Jojo-Schmitz** [comment]
I guess this now allows allows for the just rempoved CUT_TRIPLE, 9/8

**Comment by Jojo-Schmitz** [comment]
Done
