### ISSUE TITLE
Bends: Tablature displays grace note stem of prebend in error; inc. issue with fretmark stem alignment

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#20206]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Take an example like the following:
![prebends_bug](https://github.com/musescore/MuseScore/assets/87246583/75b46e0d-a6fe-4fe1-9642-0b29dbc9c761)

MS4 render this by default as:
![prebends_bug2](https://github.com/musescore/MuseScore/assets/87246583/bdb0e890-99cc-4880-8060-fd76e7dafdef)

(ignore the differences in fretmark numbers between the two. This is an artefact of different notational approaches)

MS displays the grace note stems of prebends in error (and those of slides as well).

Another related issue is the horizontal displacement of the stem in relation to the fret mark number. IMV, this should align with the fretmark number itself.

Zipped MS4.2 dev file: 
[prebend_bug.zip](https://github.com/musescore/MuseScore/files/13467555/prebend_bug.zip)

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233300503, revision: github-musescore-musescore-5b1fa37

### Regression

No.

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by oktophonie** [comment]
In your file, if I switch the stave to standard I see this:
![image](https://github.com/musescore/MuseScore/assets/20604032/a0cec4ba-c313-4c0f-8850-3809353647b3)
Implying that you input these as grace notes and added bends to them. If I delete those grace notes and instead add a 'grace note bend' item to each main note, and switch back to '6-stave tab common', then:
![image](https://github.com/musescore/MuseScore/assets/20604032/a3b6a613-0621-4599-ad39-7747aa34cd95)
If you achieved this another way, can you explain how?

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233390504, revision: github-musescore-musescore-7d2cae5

> octophonie wrote, "If you achieved this another way, can you explain how?"

Good point. I'm using the latest nightly, so I can only go on that. There seems to be a bug which makes the grace note stems appear if the user copies the bend in a certain way. I'll open a separate issue and this may lead to the closing of this one.

**Comment by rgreen5** [comment]
See #20326.
