### ISSUE TITLE
Linux Musescore nightly (C2023-11-26 06:25) won't run 

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#20200]
### Issue type

Other type of issue

### Bug description

The latest Linux nightly  (C2023-11-26 06:25) won't run.

### MuseScore Version

D/K

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64

**Comment by oktophonie** [comment]
Runs perfectly fine here, so we'll need more info to go on.

**Comment by cbjeukendrup** [comment]
The build from 06:25 is a `aarch64` build (aka `arm64`), while you indicate you have an `x86_64` OS. Those ARM builds are new since a few days, so is it possible that you just accidentally downloaded one of those, instead of the `x86_64` build?
