### ISSUE TITLE
Right-click Select Similar broken in Master

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20255]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

In the 4.2 Beta I can select all grace notes, bends, slurs, etc with right click, select, similar.

This does not work in Master

### Steps to reproduce

1.  Open
[bend_adjustment.zip](https://github.com/musescore/MuseScore/files/13502390/bend_adjustment.zip)
or other file with these elements
2. Select a grace note, slur, bend, or any element
3. Right click - Select - Similar

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/7e7be655-5c48-4018-8996-e932bd2cfbe8

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.3.0-233330338, revision: github-musescore-musescore-fe9e9e6

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by Tantacrul** [comment]
Nice find.

**Comment by Jojo-Schmitz** [comment]
I hope that isn't related to #20137 (and #20187 for 4.2)

**Comment by Jojo-Schmitz** [comment]
Darn, apparently it is, reverting both commits from that PR fixes the issue. Reverting just the 2nd commit does not resolve it though.
As #20187 got merged into 4.2 after the Beta release, that's be affected too (but the Beta is not)

**Comment by Jojo-Schmitz** [comment]
And it isn't just grace notes, slurs and bends, but basically all elements :-(

**Comment by worldwideweary** [comment]
@Jojo-Schmitz  after looking thru your port, i recognize the problem more than likely being the lack of initialization in the Struct of line 457 
```cpp
Struct FilterNotesOptions
```

The beat and measure should be initialized practically equivalent to how FilterElementsOptions has it in notationtypes.h. Try that :)

**Comment by Jojo-Schmitz** [comment]
Yes, I'm looking into that as we speak

**Comment by Jojo-Schmitz** [comment]
That's not the issue though

**Comment by Jojo-Schmitz** [comment]
Actually `FilterElementsOptions` inherits those from `FilterElementsOptions`.
But the initialisation of `beat` apparently os wrong, should be `Fraction beat{ 0, 0 };` (to mean all beats)

**Comment by Jojo-Schmitz** [comment]
See #20266
