### ISSUE TITLE
"Exclude from parts" checkbox not checked by default when adding vertical/text frame to main score

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#20250]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When adding a **Vertical frame** or **Text frame** to the main score, the `Exclude from parts` checkbox should be checked by default, allowing the user to un-check the box in order to show the frame in all parts. 

Currently, the checkbox is not checked by default. Despite this, the selected frame does not appear in the part. 

Toggling the checkbox on and off reveals the selected frame in the parts (Good: this aspect of the feature isn't entirely broken; Bad: it's quite difficult to discover this, which I'm sure will lead people to conclude that this aspect of the feature IS broken).  

### Steps to reproduce

[See video for reproduction steps](https://www.dropbox.com/scl/fi/c81fysedu37ow42x710lw/score-parts-vertical-frames.mov?rlkey=tyv3u1j9lrnt0m3ot24x7cawy&dl=0)

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233330506, revision: github-musescore-musescore-c6bc567

### Regression

No.

### Operating system

macOS 13.1

### Additional context

@oktophonie please feel free to re-assign as necessary, however I was thinking it could be appropriate for either @mike-spa or @miiizen 🙂

**Comment by oktophonie** [comment]
I'm inclined to say that "Exclude from parts" should in fact _not_ be checked by default for frames; I now forget our reasoning for trying to do it that way, but it's already caused confusion once: https://github.com/musescore/MuseScore/issues/20171

In any case, the actual behaviour and checkbox state should match, so the bug remains.

**Comment by MarcSabatella** [comment]
I don't know the reasons for doing it that way in 4.2, but FWIW, even though it's different from previous behavior, I don't think it's necessarily a bad idea.  It's pretty common to *not* want frames other than the default title frame to appear in parts.  Fancy cover pages, blocks of text for conductor notes or dialog in musical theater, etc.  And also, there is the matter that frames within a score break systems in places that may or may not make sense in the parts.  Hard to say if those cases are more common than things like titles of movements which of course should be present in parts in the same locations, though.

Either way, it's going to be a bit non-obvious how to get the other behavior.

**Comment by bkunda** [comment]
As far as I can recall, I believe the decision to exclude frames from parts by default was because of their effect on layout. On thinking it through now, however, I'm of the opinion that inserting a frame in the score and seeing it (potentially) bork the layout of a part poses a greater imperative to the user to look for a way to revert that behaviour, than the opposite scenario –I.e. _not seeing said frame at all in any part_, leaving one to presume that frames no longer sync. 

So I too am in favour of having the **Exclude from parts** checkbox un-checked by default in these cases.
