### ISSUE TITLE
Hide SMuFL fonts in Preferences > Appearance > Font, to prevent issues caused by the large line height of these fonts

### ISSUE THREAD

**Issue by TwoClocks** [musescore/MuseScore#20257]
Edit: see also the discussion below

### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

There is no way to either enable, or disable a plugin from the UI. The buttons to do so are missing. See screenshot.

Plugins work fine, if manually enabled by adding to the plugins.json file.

Using Wayland and sway as window manager under Linux. Although the issues persist if run with `QT_QPA_PLATFORM=xcb`.  Running like this fixes the menus drawing in the middle of the screen, so I think it uses X11 (I can't tell from logs).

The same behavior in arch package and appImage.

### Steps to reproduce

Open plugin manager. Select a plugin. Observe lack of "enable" or "disable" buttons.

### Screenshots/Screen recordings

![2023-11-29-111838](https://github.com/musescore/MuseScore/assets/5883156/08a09f25-d1af-4ff6-9405-eaf73e35eb31)

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Linux (arch) / wayland / Sway

**Comment by cbjeukendrup** [comment]
This seems a font issue on your OS; apparently MuseScore (or actually, QML) treats the font as if it has a very tall line height. That is why all those buttons look so extremely janky there, and the content of that plugin panel is so tall that the buttons don't fit anymore.

It's not good that the height of that panel is apparently hard-coded, so we should fix that. But to fix the font issue in general, you could try selecting a different font in Preferences > Appearance.

**Comment by TwoClocks** [comment]
Changing the font worked.

Strangely two of the MuseScore fonts do not work. Specifically "MScore" and "MuseJazz"

**Comment by cbjeukendrup** [comment]
Ah, I guess that explains it: MScore and MuseJazz are not really text fonts; they contain the musical symbols that are used to render the score (they are "SMuFL" fonts). That's why they have such a strange line height. We might want to remove them from that list, to avoid confusion.

**Comment by bkunda** [comment]
Per @cbjeukendrup's suggestion, we should perhaps just hide music fonts from the Appearance font selector dropdown to help users avoid getting into this problem.

**Comment by cbjeukendrup** [comment]
> Or pimp them up to fully fledged fonts?

I don't think that's worth it. (Note that Bravura for example has the same problem.)

**Comment by re1san** [comment]
Hey, I can work on this issue
