### ISSUE TITLE
Pedal doesn't work with MuseSounds Upright Piano

### ISSUE THREAD

**Issue by Beniegenie** [musescore/MuseScore#20260]
### Issue type

Muse Sounds bug

### Bug description

When there is a repeating bass F with the piano instrument and muse sounds upright piano, the audio does not sound like there is the pedal mark.

### Steps to reproduce

Use the MuseScore Piano
Switch it to the Muse Sounds upright piano in the mixer
Write a series of repeating bass F notes
Put a pedal mark

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

macOS Big Sur

**Comment by MarcSabatella** [comment]
I'm not hearing a problem with this; could you please attach a specific score?  Of course, it will be hard to discern the effect if it's literally just one repeated note, so better if you can find an example where it would be easier to tell if there is pedal or note (like adding an F# after a couple of F's and connecting them all via the pedal, which is what I tried).

**Comment by Beniegenie** [comment]
@MarcSabatella https://musescore.com/user/44281985/scores/13130695

**Comment by Beniegenie** [comment]
@MarcSabatella https://musescore.com/user/44281985/scores/13130695

**Comment by MarcSabatella** [comment]
I have loaded the score.  Sounds fine offhand.  Which measure specifically do you believe to have a problem?  Note the pedal martkingsa are added incorrectly for the most part - they should join up on the first beat of measure.  But within the pedal lines you did add, I hear it pedaling just fine in the measures I checked.

**Comment by Beniegenie** [comment]
@MarcSabatella I did start with them joining on the first beat of each measure, but it still sounded the same as it does now. It always seems to happen when it's playing the bass F.

**Comment by Beniegenie** [comment]
@MarcSabatella

**Comment by Beniegenie** [comment]
@MarcSabatella Did you hear it with the link?

**Comment by MarcSabatella** [comment]
That is the score I tested, yes.  As I said, the pedal was added incorrectly, so it’s hard to know what you.  But again, maybe one of the Muse Sounds developers will be able to hear it, and that’s what really matters - not whether *I* can.

I am just trying to help you refine your bug report to make it easier for people to reproduce the issue.  My advice to you is, see if you can create a simple test score without all those other instruments and with the pedal added correctly.  that would make it easier to tell if there is a real problem or just your ears playing tricks on you.

**Comment by Beniegenie** [comment]
@MarcSabatella Okay, but like I said, it sounded exactly the same either way. If you saw any of my other scores, you'd know that that is the way I always put the pedal in. Also, sorry, I didn't see your reply in my notifications.

**Comment by zacjansheski** [comment]
Closing as stale / can't reproduce
If there is still an issue with the MuseSounds instruments, please report to MuseHub support team: https://support.musehub.com/hc/en-gb/requests/new.
