### ISSUE TITLE
Import this XML file create a corrupt score on MuseScore Master

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#20273]
### Issue type

Import/export issue

### Bug description

Import this XML file create a corrupt score on MuseScore Master when key signature change. Look at Measure 18 when key signature change.
Edit : Same Bug in 4.2 Dev, work fine in 4.1

### Steps to reproduce

Load the XML file
[Mission corrupt.zip](https://github.com/musescore/MuseScore/files/13517501/Mission.corrupt.zip)

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/1835871/859cfd42-530f-4b54-b3ed-f3f52e61b05a)

### MuseScore Version

MuseScore version (64-bit): 4.3.0-233340304, revision: github-musescore-musescore-057ab20

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

**Comment by cbjeukendrup** [comment]
It seems you didn't attach the XML file...

**Comment by Gai-Luron** [comment]
> It seems you didn't attach the XML file...

Done. Sorry

**Comment by Jojo-Schmitz** [comment]
In 3.7 too :-(

**Comment by miiizen** [comment]
Do you know if this was exported from Sibelius?

**Comment by Jojo-Schmitz** [comment]
No:
```xml
  <encoding>
   <software>Neuratron PhotoScore</software>
   <encoding-description>MusicXML 2.0</encoding-description>
  </encoding>
  <source>Scanned sheet music</source>
 ```
