### ISSUE TITLE
Please modify the visual representation of notes when using the instrument panel (for example, piano) so that the keys for the left and right hands are distinguishable by different colors.

### ISSUE THREAD

**Issue by Gunayrr** [musescore/MuseScore#20282]
### Your idea

I have a suggestion and a request. Please modify the visual representation of notes when using the instrument panel (for example: piano) so that the keys for the left and right hands are distinguishable by different colors (as in the second 2.picture).
<img width="1583" alt="1 picture" src="https://github.com/musescore/MuseScore/assets/152647375/f3aaea7e-6beb-410e-b886-95e6522c9304">
<img width="1579" alt="2 picture" src="https://github.com/musescore/MuseScore/assets/152647375/fcee0525-932c-4de9-9f8b-9d7e1464eed7">

Thank you,
Best regards,
Gunay Rzayeva

### Problem to be solved

This would help even non-professionals correctly identify which hand is playing which notes.

**Comment by Jojo-Schmitz** [comment]
As said in https://musescore.org/en/node/357392 already: this is a musescore.com request and as such needs to be made there
