### ISSUE TITLE
editing "line" object's length causes problem

### ISSUE THREAD

**Issue by gnzgg** [musescore/MuseScore#20292]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Hi ! I'm running in an issue with the "line" object:

/!\ Steps to reproduce section contains a test file, which I think should work and is an important step to see if this issue is limited to my specific setup, also the rest of this post probably contains some unrelated/unimportant details, sorry about that :) /!\

I'm currently transcribing some Renaissance polyphony, which contains ligatures. The way I was taught to note these is to do something like this:

![Capture d'écran 2023-12-03 113055](https://github.com/musescore/MuseScore/assets/63004183/b0fe2a3b-2e80-4841-bd80-3020f95ebb6c)

To do these, I select the notes that are part of the ligature, add a "Line" object and edit its properties to my liking and it's all good !

now, I find that the default length of the line tends to be a bit longer than I like, especially with longer note values, because it covers the entire length of the note rather than stopping right after the note symbol

-line object, default length
![Capture d'écran 2023-12-03 113241](https://github.com/musescore/MuseScore/assets/63004183/51fa490e-813d-4fa7-a802-971fcff4672e)

so I simply click&drag the little box to the right of the line to edit the length of the line object to my liking, and everything's fine (it is a little bit imprecise, but it does the job)

However, this seems to conflict with another feature I use:

I'm transcribing a piece which has a first "Kyrie" part with 4 voices, a "Christe" part with 3 voices (superius is silent), then a second Kyrie with 4 voices.

The way to get this to look right is actually really simple, right click the staff, edit "part properties" (not sure that's the exact name in english) and set it to "Hide when empty" to "Always"

(WARNING!!!!!: french)
![Capture d'écran 2023-12-03 114538](https://github.com/musescore/MuseScore/assets/63004183/6ef05f08-e505-423a-9cb0-b0d06a0d77db)

in order to get this :

![Capture d'écran 2023-12-03 114807](https://github.com/musescore/MuseScore/assets/63004183/50ab3170-afe4-4727-aab5-76c52ac0c5da)

Now, the issue happens when I try to edit the line's length, it's kinda hard to explain so i made a little video for it, but trying to edit the line's length leads to weird issues where the line teleports and it's just kinda weird.
https://www.youtube.com/watch?v=bNyQrf0-OII

Workaround for me was to unhide the hidden staff, edit everything to my liking and hide it again

### Steps to reproduce

I have made a test file (change .txt file back to .mscz)
[test.txt](https://github.com/musescore/MuseScore/files/13538798/test.txt)

scroll to page 2 and try to edit the length of the line objects, by selecting the little white square to the right and dragging, I have written those that work for me and the one that doesn't, but if you try to delete bars, or change vertical spacing, that will make some difference and another one may become problematic etc, so... it's weird !

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Windows 11

**Comment by bkunda** [comment]
@gnzgg I can no longer reproduce this using your attached score in the current master. 

I suspect that the new anchors system we've recently built may have resolved this issue. 

Could you please try it again and confirm whether it's solved on your end? 

Otherwise we'll close this issue. Thanks!
