### ISSUE TITLE
Note has wrong pitch

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [musescore/MuseScore#20297]
### Issue type

General playback bug

### Bug description

The E in measure 17 in the bass clef in [this score](https://musescore.com/user/28888108/scores/6257783) is showing up as A3 when you click on it in Musescore, and is playing as A3 as well. You can delete and recreate it, but I was wondering how this happened in the first place. (I am not the owner of this score.)

### Steps to reproduce

Unfortunately I don't know

### MuseScore Version

4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

Windows 10 Version 2009 or later, Arch.: x86_64

**Comment by oktophonie** [comment]
For some reason it is an A but it's had a Y-offset applied so it looks like an E:
![image](https://github.com/musescore/MuseScore/assets/20604032/0ca6c3bd-1f77-4551-8cd4-7b9b3072b154)
So, if necessary, you can reset the offset and make it a real E instead.
