### ISSUE TITLE
Correct the order of note name vs note itself drawing

### ISSUE THREAD

**Issue by macias** [musescore/MuseScore#20291]
### Your idea

Please change the order of drawing note name and the note itself. It is important for 1/8 and shorter notes. Please take a look at the image, the "tail" of the note obscures its name.

![note-drawing](https://github.com/musescore/MuseScore/assets/1228047/fa1fa9e5-6cb7-4687-aaba-2ae67894e0e9)

### Problem to be solved

Readability of the score which is especially important for older people or/and with disabilities.

### Prior art

N/A

### Additional context

N/A.

**Comment by MarcSabatella** [comment]
Meanwhile, the workaround is to select the noteheads (eg, right-click one, select / similar), then use the Appearance section of the Properties panel to arrange "To front".  Or, equivalently, send the flags "To back".
