### ISSUE TITLE
Bends: neither copy nor repeat (R) command work correctly in note input mode

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#20325]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

In note input mode, if you use copy or the repeat command, the bend doesn't copy in full, only the "parent" note.

(Copy/repeat in **normal** mode is covered in another issue).

### Steps to reproduce

1. Open the attached MS4 file (tab in C# minor)
![bend_copy_issue1](https://github.com/musescore/MuseScore/assets/87246583/f83172a4-22c2-4cf7-aecd-a4368a7d5eda)
2. Select fretmark 14
3. Apply a grace note bend
4. Now apply copy, navigate to the next position and paste
**Actual result**: Only the parent note is copied
**Expected result**: The whole bend is copied?
5. Undo the steps and repeat the procedure but this time using the repeat command twice
6. **Actual result**: Only the parent note is copied
**Expected result**: The whole bend is copied?

[bend_copy_issue.zip](https://github.com/musescore/MuseScore/files/13559455/bend_copy_issue.zip)

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233390504, revision: github-musescore-musescore-7d2cae5

### Regression

No

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by mike-spa** [comment]
When selecting a single chord, grace notes are never copied, even on standard stave. And they shouldn't.
