### ISSUE TITLE
Grace note bends: Copy and repeat command cause grace note stem to appear on first copy (normal mode)

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#20326]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

If you use repeat or copy on an existing grace note bend _in normal mode_, the first instance of copy/repeat results in the grace note stem appearing. This disappears if you repeat the copy/repeat command. 

### Steps to reproduce

1. Open the attached MS4 file (tab in C# minor) 
[bend_copy_issue.zip](https://github.com/musescore/MuseScore/files/13559541/bend_copy_issue.zip)
2. Click on the fretmark 12 bend and use repeat (R)
**Actual result**: The grace note stem copies as well
Expected result: No grace note stem
3. Use repeat again
**Result**: The bend is copied as expected.

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233390504, revision: github-musescore-musescore-7d2cae5

### Regression

No.

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by bkunda** [comment]
I suspect I'm missing something here. Isn't this expected behaviour? [See video](https://www.dropbox.com/scl/fi/l8ilmalxfhu3ujbgs035x/issue_bend-R.mov?rlkey=un8u2sv41dzzb39al7x43komw&dl=0)

**Comment by bkunda** [comment]
@rgreen5 can you please upload a video showing exactly what the issue is here. 
I'm still unable to reproduce it.

**Comment by rgreen5** [comment]
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

AFAICS, the problem is now fixed. Issue can be closed.
