### ISSUE TITLE
Engraving Bug: transposed voices can have false key signature after line breaks

### ISSUE THREAD

**Issue by philipplndwhr** [musescore/MuseScore#20348]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Line breaks can falsify the key signature for transposing instruments.

The playback is still playing the correct notes and the notes are displayed correctly in the lower left corner.
<img width="1440" alt="image" src="https://github.com/musescore/MuseScore/assets/109522890/49e3f306-2ca0-497b-a55d-862340913529">

### Steps to reproduce

1. Have a score with a transposing instrument (and maybe an instrument reading in C)
2. choose the key signature such that the transposing instrument "cancels" the accidentals: e.g. Alto Sax and three flats
3. turn off concert pitch mode
4. insert a line break
5. observe behaviour as in the screenshot attached

### Screenshots/Screen recordings

<img width="599" alt="image" src="https://github.com/musescore/MuseScore/assets/109522890/3b8d14c3-e487-41da-9ab7-1ffb7f2c6699">

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

I don't know

### Operating system

macOs 13.x

### Additional context

A workaround exists:

1. click onto the first bar of the new line
2. drag & drop the correct key signature again
3. problem solved

This workaround may not be appropriate for large scores and/or orchestral scores which derive voices from the score

**Comment by cbjeukendrup** [comment]
I could indeed reproduce this in 4.1.1, but not in the master branch; so this has already been fixed for the soon-to-be-released 4.2. You can try it in the builds from https://github.com/musescore/MuseScore/releases/tag/v4.2.0-beta.2 or in the nightly builds (https://musescore.org/en/nightly-builds).

I'll close this issue, but please let us know if you still find additional problems in 4.2 / 4.3 builds!
