### ISSUE TITLE
Aarch64 (ARM64) Linux builds fail to launch when using a kernel with 16 KB PAGESIZE (please add support for other kernel page sizes?)

### ISSUE THREAD

**Issue by rxhfcy** [musescore/MuseScore#20342]
### Issue type

Crash or freeze

### Bug description

Aarch64/ARM64 Linux builds seem to basically crash on startup if kernel PAGESIZE is 16 KB (not 4 KB).

**_Suggestion_**: please also support other page sizes than 4 KB?
16 KB support is required for at least these:
- Asahi Linux on Macs with ARM processors ("Apple Silicon") (no 4 KB support)
- Raspberry Pi 5 with the default 16KB kernel of 64-bit Raspberry Pi OS ([blog post](https://www.raspberrypi.com/news/benchmarking-raspberry-pi-5/) that talks about 16KB)

More information: on ARM, 4 KB is not the only PAGESIZE possible (some systems use 16 KB or 64 KB). 

I tested with Aarch64 (ARM64) Linux on an "Apple Silicon" (ARM64) M1 MacBook Air, (re)booting straight to bare [Asahi Linux](https://asahilinux.org/about/) / Fedora [Asahi Remix](https://asahilinux.org/2023/08/fedora-asahi-remix/) "on the metal" (without using macOS), and the Asahi Linux kernel will only have support for 16 KB page size, because that's what the hardware expects.

Here is some more information about "broken" software that doesn't yet work on ARM64 Asahi Linux (includes links to details on how several previously unsupported applications have already been fixed to support 16 KB page size!):
https://github.com/AsahiLinux/docs/wiki/Broken-Software#if-package-supports-aarch64-why-doesnt-it-work
(random example link from that page about Chromium (fixed in 2022): "[ARM64 supports 4kb, 16kb, and 64kb page sizes. Previously, only 4kb was supported by Chromium. This patch adds 16kb support](https://bugs.chromium.org/p/chromium/issues/detail?id=1301788#c23), as is used for example by Asahi Linux on M1 Macs")

PS. Why I'm reporting this: The 4.2 Beta 2 announcement [added experimental builds for ARM Linux](https://github.com/musescore/MuseScore/releases/tag/v4.2.0-beta.2) and asked to "Please let us know if you encounter any issues."

Also, I was able to quickly test (on macOS, using QEMM in UTM) that the same build did work in a similar Fedora 39 ARM64 VM that was using 4K pages, so I'm pretty sure 16K support is the issue here (i.e. not a Fedora bug).

### Steps to reproduce

0. Use a kernel with 16 KB page size (e.g. Asahi Linux on ARM MacBook Air M1 or Raspberry Pi 5 with the default 16KB kernel)
1. Try to run the Linux Aarch64 / ARM64 build

What happens (doesn't open at all, only shows an error message):
```
$ ./MuseScore-4.2.0.233381325-experimental-aarch64.AppImage 
/lib64/libjack.so.0
/lib64/libnss3.so
/tmp/.mount_MuseScsp9iiA/bin/mscore4portabletesting: error while loading shared libraries: libsndfile.so.1: ELF load command address/offset not page-aligned
$
$ getconf PAGESIZE
16384
```

(the same problem also happens with the latest arm64 Linux nightly)

### MuseScore Version

MuseScore 4.2 Beta 2 (Pre-release)

### Regression

No.

### Operating system

Fedora Asahi Remix 39 (ARM64 Linux)

**Comment by cbjeukendrup** [comment]
It seems libsndfile from apt is used; see https://github.com/musescore/MuseScore/blob/efbc26031019475dd18e0693a54db9b4c8ff889f/build/ci/linux/setup-arm.sh#L85. If that isn't working, I guess we'd have to find a different place to get it from, or build it (and all its dependencies?) from source... 
@theofficialgman What are your thoughts about this issue?

**Comment by marcan** [comment]
Is there some weird ELF mangling going on as part of the AppImage build process? In the original file GNU_RELRO and DYNAMIC sections are part of the data pheader too, while in the new file they are not.

It sounds to me like something is patching the DYNAMIC section, and in the process moving it out of the existing LOAD pheader and adding a new one... and getting the section alignment wrong.

**Comment by marcan** [comment]
Yup, this is patchelf's fault: https://github.com/NixOS/patchelf/issues/474

**Comment by marcan** [comment]
Actually, not so sure. It looks like patchelf correctly considers the base page size for ARM64 to be 64K: https://github.com/NixOS/patchelf/blame/917ea45b79de04f69059f42a8e2621f7caeae1c9/src/patchelf.cc#L361

Is this build of patchelf built using `--with-page-size=4096`? If so, *that* is the problem. The default autodetect behavior should be correct as far as I can tell, on ARM64.

**Comment by theofficialgman** [comment]
I looks to me like linuxdeploy handles copying and stripping copied binaries as part of the appimage build process
https://github.com/musescore/MuseScore/actions/runs/7109599307/job/19354779005#step:7:17747
maybe stripping causes the EFL mangling?

**Comment by theofficialgman** [comment]
and the patchelf bug that was fixed in 0.12 that causes this https://github.com/NixOS/patchelf/commit/0470d6921b5a3fe8e92e356c8e11d120dbbb06c0 .... focal has 0.10

```
Currently patchelf uses the host system's page size (determined at build
time) as the default section load memory alignment. This causes multiple
issues
```

**Comment by theofficialgman** [comment]
patchelf 0.14.3 from jammy builds fine on ubuntu bionic in my testing (that just what I had easily available). I'll add it to a ppa or the setup script

**Comment by marcan** [comment]
3+-year-old software strikes again... (also hi @delroth).

FWIW, this is a theme in ARM64 land. If you are using any frameworks, builds, tools, etc. that are more than 2 years old, they are highly likely to be buggy or broken in some way. ARM64 Linux is only just taking off, and things were *very* broken just a few years ago. Even if you wouldn't do so otherwise on x86-64 for e.g. better host system compat, you're much better off going for newer stuff on ARM64. It's not just stuff like this; e.g. I got major *Qt* (QML javascript crashing) and *GCC* (miscompiling) bugs fixed and very recently a *glibc* bug fixed (TLS segfaults with dynamic loading).
