### ISSUE TITLE
Breaking up beamed notes when changing note duration does not show flag until further edits are made

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20358]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Changing a beamed eighth note to sixteenth, or a similar action, will not produce the correct flag.

### Steps to reproduce

1. Create a score and add a bar of eighth notes
2. Change an eighth note to a sixteenth
3. It will look like a quarter note (no sixteenth flag). rests appear correctly
4. Switching to a different page view or making another edit in the score will correct the issue

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/72fdc2e8-561a-4246-95ca-22168431e90d

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.3.0-233410302, revision: github-musescore-musescore-efbc260

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 14

### Additional context

This worked correctly in 4.1.1

**Comment by zacjansheski** [comment]
It is actually more fundamental than my original report.  Notes just need to be beamed for the bug to occur



https://github.com/musescore/MuseScore/assets/69917893/88b6d706-904e-4380-bec2-2e66f496132b

**Comment by zacjansheski** [comment]
This is a really recent regression, doesn't happen in the build from 3 days ago

**Comment by Eism** [comment]
the first bad commit https://github.com/musescore/MuseScore/commit/34fb37b5992ddc495b22893c4ea1715545998f8c

**Comment by Eism** [comment]
Removed from the 4.2 project because the problem commit was merged only to the master

**Comment by sammik** [comment]
I think this one #20864 is the same.
