### ISSUE TITLE
Accidental Sync Options Don't work

### ISSUE THREAD

**Issue by jonarnoldmusic** [musescore/MuseScore#20350]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

In MuseScore 4.2, accidentals have toggles for Position and Style/Appearance under "Score and part synchronization" but changing position or appearance on either score or parts does not have an equivalent effect in the opposite location. Toggling the sync button does change the highlighted color of the accidental but has no effect on the properties.

I would also like the ability to sync bracket type and the "small accidental" property, but this doesn't seem to supported by the current UX, so I filed a feature request as  #20351 . This was also discussed in comments on issue #16544 .

### Steps to reproduce

Add an accidental to the score
Open the part
Move the accidental
The accidental in the score is unchanged

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233281140, revision: github-musescore-musescore-23f3925

### Regression

No.

### Operating system

Windows 11

**Comment by oktophonie** [comment]
This is resolved by https://github.com/musescore/MuseScore/pull/20319 which removes the non-functional toggles. (That PR isn't in the beta 2 but will be in the release)
