### ISSUE TITLE
Musescore crash after copying linked staff repeat measure

### ISSUE THREAD

**Issue by YoavShilon05** [musescore/MuseScore#20365]
### Issue type

Crash or freeze

### Bug description

After selecting both repeat measures on two (or more) linked staves, copying and pasting, Musescore Crashes

### Steps to reproduce

1. Create a new Musescore project with a one staff instument.
2. on the 'Instruments' panel, select the dropdown on your instrument, click the gear icon and select 'Create a linked staff'
3. from the 'Palettes' menu, drag the 'Repeat last measure' item into one of the staves.
4. Select (using shift click) both of the repeat measures on the linked staves.
5. Copy.
6. Select an empty bar in the socre and paste. Musescore should crash.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/54374032/eaec7100-6b0b-41cc-8d52-38ce7282f3bf

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233420505, revision: github-musescore-musescore-cc2aa2b

### Regression

No.

### Operating system

Windows 10

**Comment by zacjansheski** [comment]
Crash occurs in 4.0.2, does not occur in 4.0.1

**Comment by zacjansheski** [comment]
[LinkedRepeatBarCrash.zip](https://github.com/musescore/MuseScore/files/13614480/LinkedRepeatBarCrash.zip)
