### ISSUE TITLE
In a text object you can't click at the end of a selection, only the beginning

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#20361]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

This was an issue in MS3 as well. If you select a word (or phrase, in fact anything) within a text object, such as the following
![click_bug](https://github.com/musescore/MuseScore/assets/87246583/7d40734e-ba17-4172-a0d0-41af2ee8906d)
you cannot click to the right of the selection, only to the left of it.

This may seem trivial but actually it is a continuous annoyance for the user: say, when you are tring to add something to the end of a line.

### Steps to reproduce

1. Create a text object
2. Double-click a word to highight it
3. Try to click just to the right of it
**Actual result**: The selection remains uncancelled and you cannot click onto the desired location
**Expected result**: You should be able to cancel the selection and click on to the desired location.
4. Now highlight the word again, and this time try to click just to the left of the seected text
**Result**: You _can_ click to the desired location, as expected.

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

No.

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by NathanPrazeres** [comment]
Can I please be assigned to this bug?
