### ISSUE TITLE
Realizing a chord sometimes generates wrongly sounding notes

### ISSUE THREAD

**Issue by LupusCaeruleus** [musescore/MuseScore#20377]
### Issue type

General playback bug

### Bug description

See screen recording. Notice the C♭5 note in the first A♭m chord is sounding an octave lower.

Not present in MuseScore 3.6.

https://github.com/musescore/MuseScore/assets/70313425/3c3b27bf-cb23-40b6-bb7c-dcf8f668b020

### Steps to reproduce

1. Enter the chords Em, A♭m in a same bar.
2. Select the two chords, right-click and realize them.
3. Notice the wrongly sounding C♭5 note in the A♭m chord. Saving and re-opening will not correct this glitch.

### Screenshots/Screen recordings

See above.

### MuseScore Version

4.1.0-231731239

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

**Comment by sammik** [comment]
If I remember correctly, this was already fixed in master. Isnt it?

**Comment by oktophonie** [comment]
Fixed by https://github.com/musescore/MuseScore/issues/18968 etc
