### ISSUE TITLE
Ties disappearing in continuous view

### ISSUE THREAD

**Issue by RotoSound** [musescore/MuseScore#20382]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

In scroll view when deleting a tie will make all the ties in subsequent bars to get invisible. Switching to page view makes the ties visible again (see attached file).
[Tie redraw bug in scroll view Mu42.zip](https://github.com/musescore/MuseScore/files/13623634/Tie.redraw.bug.in.scroll.view.Mu42.zip)

### Steps to reproduce

1. Open the attached file.
2. Chose scroll view.
3. Delete the first tie.
4. Watch the ties in the subsequent bar go invisible.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233420505, revision: github-musescore-musescore-cc2aa2b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11.

**Comment by oktophonie** [comment]
For info: missing ties will reappear as soon as next layout happens. Is definitely in 4.2 (not just master), but not 4.1.
