### ISSUE TITLE
Plugin developed for 4.0.x crashes on 4.1.x on MacOS

### ISSUE THREAD

**Issue by jacobdill75** [musescore/MuseScore#20380]
### Issue type

Crash or freeze

### Bug description

Back in December 2022 I wrote a tuning plugin (using Bill Hail's tuning plugin as a template) for MuseScore 4.0 on macOS. I revisited it recently to publish it, but it crashed my MuseScore 4.1 app on Mac. It works fine on windows for 4.1 and I went ahead and published it, with the disclaimer of this problem I am having. When running Musescore in debug mode, the only detail I get is that it crashed from a universal exception.

### Steps to reproduce

1. Download plugin from https://musescore.org/en/project/121719-edo-tuning
2. Open a Score in MuseScore 4.1.x on Mac
3. Enable EDO Tuning Plugin
4. Run Plugin

### MuseScore Version

4.1.x

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Catalina

**Comment by jacobdill75** [comment]
This crash also happens with the vanilla tuning plugins in MS4

**Comment by MarcSabatella** [comment]
Did you see the note in the 4.2 beta announcement:

> Reminder for plugin authors: if your plugin uses the TextField component from QtQuick.Controls 1.0, please replace it with the TextEdit component from QtQuick.Controls 2.15 (or from QtQuick.Controls 2.2 if you require compatibility with MuseScore 3). See [issue #19326](https://github.com/musescore/MuseScore/issues/19326) for details. Thanks!
