### ISSUE TITLE
Mu3 score reported as broken in Mu4

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#20400]
### Issue type

Import/export issue

### Steps to reproduce

The attached (zipped) score
[bongo esp.zip](https://github.com/musescore/MuseScore/files/13633481/bongo.esp.zip)
opens fine in Mu3(.6.2), but in Mu4(1.1 at least and later) it reports:
Error=XML_ERROR_EMPTY_DOCUMENT ErrorID=13 (0xd) Line number=0

Extracting the mscx, and importing that in Mu4 works just fine.
As does opening and resaving with Mu3 and importing that in Mu4

Edit: As does renaming the mscz file to fully match the name of the mscx inside.

### MuseScore Version

4.1.1, 4.2.0 Beta and latest master

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

Culprit seems to be the name of the mscx, "..bongo español.mscx", or its encoding (esp. that of the "ñ"?) in META-INF/container.xml, as "<rootfile full-path="..bongo español.mscx">"

Originally came up in https://musescore.org/en/node/357693

Edit: the real culprit seems the mcsz filename originally starting with 2 dots (and the mscx internally still does), but got those dots 'renamed away'

**Comment by cbjeukendrup** [comment]
I can confirm that it opens fine in MS3, while in BBEdit (which I normally use for quickly viewing the contents of mscz files) the main mscx doesn't show up at all. So the ZIP is perhaps a little bit corrupted, or maybe indeed some decoders are unhappy about the `ñ`...

**Comment by Jojo-Schmitz** [comment]
Originally came up in https://musescore.org/en/node/357693

**Comment by cbjeukendrup** [comment]
macOS built-in zip utility too; _but_ the file appears as a hidden file, because the filename starts with two dots
<img width="324" alt="Scherm­afbeelding 2023-12-11 om 12 00 24" src="https://github.com/musescore/MuseScore/assets/48658420/5074b1e7-e133-48ad-856f-61b0edaa3a9f">

**Comment by Jojo-Schmitz** [comment]
Yes, those dots are an additional problem on Mac and Linux

**Comment by krtschil** [comment]
Changing the special characters (the dots and the spanisch character) in the zip file does not change the behaviour. Muse 4.1.1 does not open it.
When I extract the .mscx file it will open in Musescore correctly without an error message.

I saved this to a new file and looked at the content. Different from the original one from the original poster and opens in Musescore without problems.
(I am on Linux)
[bongo2.mscz.zip](https://github.com/musescore/MuseScore/files/13635884/bongo2.mscz.zip)

**Comment by Jojo-Schmitz** [comment]
Of colurse nit, you'd need to change the mscx filename __and__ the corresponding entry in META_INT/container.xml. If you'd do, it'd work

**Comment by Jojo-Schmitz** [comment]
OK, that did work when I tried

**Comment by mercuree** [comment]
This file opens fine in MU4 if you rename `bongo esp.mscz` to `..bongo español.mscz` (same name as mscx file inside archive)
Unicode character in filename has no effect to this issue (at least on my system win10)

**Comment by Jojo-Schmitz** [comment]
It is not the MSCZ filename itself, but the filenames inside the MSCZ

**Comment by mercuree** [comment]
> It is not the MSCZ filename itself, but the filenames inside the MSCZ

Yes. But the magic is that if you rename the mscz file, it starts to open. You don't need to touch files inside archive at all.

**Comment by Jojo-Schmitz** [comment]
I can't confirm that

**Comment by mercuree** [comment]
https://github.com/musescore/MuseScore/assets/919446/e4411cbb-746a-4396-8fef-1b4b2143c34c

**Comment by Jojo-Schmitz** [comment]
OK, confirmed, very strange

**Comment by Jojo-Schmitz** [comment]
> Just create new musescore file and save with file name started with dots. Then rename file to anything else and it becomes corrupted.

I can confirm this too!

**Comment by cbjeukendrup** [comment]
Thanks a lot for the hints here! I think I'll have a solution ready soon.
