### ISSUE TITLE
When renaming part, it should allow to create more than one SPACE in name.

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#20408]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Steps to reproduce

https://user-images.githubusercontent.com/90187801/201347454-d53fe893-f1cc-4b6a-974f-74ba68cb7535.mp4

### MuseScore Version

4.2 master

### Regression

I don't know

### Operating system

Windows10

**Comment by Jojo-Schmitz** [comment]
Doesn't #20404 fix this? @cbjeukendrup ?
