### ISSUE TITLE
Crash after Add Staff, Undo, Create Linked Staff

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20415]
### Issue type

Crash or freeze

### Bug description

MuseScore crashes when adding a staff to an instrument without a caesura when a caesura is present in other instruments.

### 1. Crash with specific score (initial report)

1. Open 
[Smoke 12:9:2023 Crash.mscz.zip](https://github.com/musescore/MuseScore/files/13638161/Smoke.12.9.2023.Crash.mscz.zip)

2. Add a staff to the bass guitar part (reproducible on all intruments in this score except the guitar that already has a linked staff)
3. Undo
4. Add a linked staff to the bass guitar part
5. Crash

https://github.com/musescore/MuseScore/assets/69917893/ffda7346-a98f-4ae9-84b9-53c5400ce398

### 2. Another crash with non specific score (https://github.com/musescore/MuseScore/issues/20415#issuecomment-1927339271)

1. Add Flute and Oboe
2. Open parts
3. Add staff to Oboe
4. Undo
5. Redo 
6. Undo

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233451422, revision: github-musescore-musescore-b955d47

### Regression

I don't know

### Operating system

Mac OS 14

### Additional context

[AddUndoAddLinkedCrash.zip](https://github.com/musescore/MuseScore/files/13638172/AddUndoAddLinkedCrash.zip)

**Comment by zacjansheski** [comment]
Looks like it has to do with the caesura

**Comment by DmitryArefiev** [comment]
I can reproduce on my side (Windows10, 4.3 master) with these steps too:
1. Open [Smoke 12:9:2023 Crash.mscz.zip](https://github.com/musescore/MuseScore/files/13638161/Smoke.12.9.2023.Crash.mscz.zip)
2. Add a staff to the bass guitar part 
3. Undo
4. Redo


https://github.com/musescore/MuseScore/assets/90187801/605c6d03-b1db-4793-9f84-a42b614ad55a

**Comment by DmitryArefiev** [comment]
Actually, the case from my previous comment also happens with any score that has more then one staff and opened parts
1. Add Flute and Oboe
2. Open parts
3. Add staff to Oboe
4. Undo
5. Redo 
6. Undo

(will add these steps to the description)

https://github.com/musescore/MuseScore/assets/90187801/b284221e-2f09-473f-b1ac-8efbc692b1f7
