### ISSUE TITLE
Copy & paste chord over rest does not work

### ISSUE THREAD

**Issue by macias** [musescore/MuseScore#20438]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When copying & pasting chords over rests nothing happens, there is no error, no feedback, and no proper action.

### Steps to reproduce

1. Place single note in the measure.
2. Place chord (I am testing 4 notes) in the measure
3. Place two rests of the same length as note and chord, for example 1/4
4. Copy note and paste it over first rest
5. It works as expected, rest is replaced with the note -- OK
6. Copy all notes from the chord and paste it over the second rest
7. Nothing happens -- no feedback and no action, BUG

### MuseScore Version

MuseScoreNightly-latest-4.2.0-x86_64

### Regression

I don't know

### Operating system

Linux / openSUSE 15.3

**Comment by MarcSabatella** [comment]
Closings line yoh are trying to copy a list selection of notes, like maybe you used Ctrl+click to select the notes individually?  That is not supported.  You should be using g a range selection (with blue box around it) when copying and pasting multiple notes.

**Comment by macias** [comment]
@MarcSabatella thank you for the response. Yes, I was ctrl+clicking on all notes within the chord.

I understand it is not supported currently, but can we convert this report into Feature one? Is rationale for supporting such feature needed?

**Comment by MarcSabatella** [comment]
It gets much more complication - what happens if the notes selected are not I. The same chord, for instance, or indeed are randomly scattered between multiple voices, staves, and measures.  So that’s why so far no one has come up with a design for such a feature that makes sense.  But there are requests already - see for instance https://github.com/musescore/MuseScore/issues/19046

**Comment by macias** [comment]
Thank you again. If you feel this is a duplicate of the other mentioned report, I will add explanation there, so everything would be in the one place.

**Comment by bkunda** [comment]
I think this issue can be closed as it now has coverage in #19046
