### ISSUE TITLE
MuseScore 4 is unusable with my audio device

### ISSUE THREAD

**Issue by Axade1874** [musescore/MuseScore#20439]
### Issue type

Muse Sounds bug

### Bug description

The sound is extremely high and accelerates to what feels like three times the original speed.
With default audio device there is the Problem, with Nvidia Broadcast as audio device, the problem is gone

Default audio device is "beyerdynamic dt770 pro 250 ohm" with "Creative Sound BlasterX G6"

### Steps to reproduce

Simply create a new score and place a note or fill a measure

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/153683275/841a582e-449e-4289-af12-a1ba07c07c93

https://github.com/musescore/MuseScore/assets/153683275/871467ae-6982-4a63-8911-8094028b192a

### MuseScore Version

4.1.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
Sounds like your audio device is probably set to a very high sample rate.  Try turning it down to something more like 44.1 or 48 kHz.

**Comment by Axade1874** [comment]
> Sounds like your audio device is probably set to a very high sample rate. Try turning it down to something more like 44.1 or 48 kHz.
> 
> This a known general issue, not specific to muse sounds.

yep, had it on 24 bit, 96 kHz.
But the problem persists even at the lowest setting (16 bit, 44.1 kHz).

**Comment by MarcSabatella** [comment]
Did you restart MuseScore after changing the device sample rate?

**Comment by Axade1874** [comment]
Yes, after every audio change I restarted it.

**Comment by cbjeukendrup** [comment]
This sounds similar to https://github.com/musescore/MuseScore/issues/17648 and https://github.com/musescore/MuseScore/issues/19931; so it would be related not to sample rate / buffer size, but to the number of audio channels. Is it possible that your default device has not just two channels, but four/six/eight, for example for some kind of surround effect? Either physically, i.e. with many speakers, or virtually, i.e. surround emulated by two speakers?

**Comment by Axade1874** [comment]
Yes, that's my problem...
If I activate the so-called "direct mode", the sound card switches to stereo and it works

![image](https://github.com/musescore/MuseScore/assets/153683275/9291670e-1019-4d53-94fd-07cd22f028e3)

A solution to this would be really great... I would also simply redirect the sound to stereo within the program, like in Musescore 3.

**Comment by cbjeukendrup** [comment]
Thanks for the reply. In that case, I think we might want to close this issue as a duplicate, since it is almost certainly the same problem as either https://github.com/musescore/MuseScore/issues/17648 or https://github.com/musescore/MuseScore/issues/19931 (or both; these issues may actually be duplicates of each other). Issue https://github.com/musescore/MuseScore/issues/17648 is currently on the list for 4.3, so let's see if we'll indeed find a solution in time.
