### ISSUE TITLE
Incorrect display of the text of the "ottava bassa" line

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20465]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The "ottava bassa" line has the wrong symbol (_8va_, but it should be _8vb_). The same is true with the lines "quindicesima bassa" (_15_) and "ventiduesima bassa" (_22_) 

### Steps to reproduce

1. I am entering notes 
2. I add the "ottava bassa" line to the entered notes
3. I uncheck the box next to "show only numbers"

### Screenshots/Screen recordings

![Снимок экрана (54)](https://github.com/musescore/MuseScore/assets/134041121/ba37ebcc-36ca-44a6-b053-c956aea5378a)
![Снимок экрана (56)](https://github.com/musescore/MuseScore/assets/134041121/23229df4-4c40-4a7e-be27-1bd590b7411d)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

In general, it is necessary to make sure that by default these lines have symbols when entering (8va, 8vb, and so on). At the moment, when adding these lines, the check mark next to "show only numbers" is set by default. I believe that this check mark should be there only at the user's request

**Comment by MarcSabatella** [comment]
This is kind of a religious issue - some editors do use 8vb, but others use 8vb, and others still use just the number.  It is by design that MuseScore uses the number only by default, and that it also uses va instead of vb when turning off the numbers only option.  If you prefer the vb, you can get that by changing the text to `<sym>ottavaBassaVb</sym>`.  And you can then add a customised line back to your palette (Ctrl+Shift+drag) for easy reuse.

I have no opinion on whether it could ever make sense to revisit these defaults, but anyhow, for now, it's by design, and that's how you override them.

**Comment by Dima12357** [comment]
> This is kind of a religious issue - some editors do use 8vb, but others use 8vb, and others still use just the number. It is by design that MuseScore uses the number only by default, and that it also uses va instead of vb when turning off the numbers only option. If you prefer the vb, you can get that by changing the text to `<sym>ottavaBassaVb</sym>`. And you can then add a customised line back to your palette (Ctrl+Shift+drag) for easy reuse.
> 
> I have no opinion on whether it could ever make sense to revisit these defaults, but anyhow, for now, it's by design, and that's how you override them.

I managed to do this only with the "ottava bassa" line. This text does not work on the lines "quindicesimo bassa" and "ventiduesima bassa". I have attached screenshots of what I got in the end.
![Снимок экрана (61)](https://github.com/musescore/MuseScore/assets/134041121/ed11548f-afa4-43ff-b094-4c0790ee323f)
![Снимок экрана (59)](https://github.com/musescore/MuseScore/assets/134041121/f6dfc952-1283-4ef5-a857-d5f9c4a2c75a)

**Comment by oktophonie** [comment]
8vb is incorrect, so this is by design.

**Comment by Jojo-Schmitz** [comment]
8va stands for otta**va**, and is the Italian equivalent to 8**th**, the "va" is the "th". Similar for the "ma" at 15ma (quindicesi**ma**) and 22ma (ventiduesi**ma** ). Those "a" don't stand for alto!
Whether it is bassa or alto is defined by whether it is below or above the staff

**Comment by Dima12357** [comment]
> 8va stands for otta**va**, and is the Italian equivalent to 8**th**, the "va" is the "th". Similar for the "ma" at 15ma (quindicesi**ma**) and 22ma (ventiduesi**ma** ). Those "a" don't stand for alto! Whether it is bassa or alto is defined by whether it is below or above the staff

Thank you for the clarification. Now I understand everything.

**Comment by Jojo-Schmitz** [comment]
As mentioned further up, this is a common misconception, even with some otherwise respected publishers ;-)

**Comment by MarcSabatella** [comment]
For the record, quindicesimaBassaMb and ventiduesimaBassaMb exit if you should truly need them.  See https://github.com/musescore/MuseScore/blob/49131424c776bf461beffaa8e6ee1c4e63089e82/src/engraving/types/symnames.cpp#L98 should you ever want to hunt down other symbol names from the SmuFL standard.  And if you have further questions about using MuseScore, please ask on the Support forum on musescore.org.
