### ISSUE TITLE
Crash in 4.2 changing note duration on attached score

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20474]
### Issue type

Crash or freeze

### Bug description

When changing the note duration of the last note in the tambourine part on the second page of the attached score, MuseScore 4.2 crashes

### Steps to reproduce

1. open 
[crash-14Dec23.mscz.zip](https://github.com/musescore/MuseScore/files/13673685/crash-14Dec23.mscz.zip)
2. Go to second page, first bar, tambourine
3. Select the last note and change it to a quarter note
4. Crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/ebb13f31-c4fb-4a03-bbc3-2dea5f2df88d

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233471824, revision: github-musescore-musescore-21cfc4e

### Regression

I don't know

### Operating system

Mac OS 14

### Additional context

Diagnostic files:

[Dec14Crash.zip](https://github.com/musescore/MuseScore/files/13673706/Dec14Crash.zip)

**Comment by RomanPudashkin** [comment]
Looks like this crash has been fixed in master with [this commit](https://github.com/musescore/MuseScore/pull/20335/commits/f61582a6c703c544ea286fe4070be7e5152b9fc3)
