### ISSUE TITLE
Single-level placement of dynamic symbols

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20475]
### Your idea

The screenshot attached below shows that the crescendo/diminuendo hairpins are at different levels. I would like to see it as shown in the second screenshot. That is, the forks should be on the same level.
![1](https://github.com/musescore/MuseScore/assets/134041121/d6189b84-8d74-4708-a86d-bf71d7e20fdd)
![2](https://github.com/musescore/MuseScore/assets/134041121/26f7e449-7952-4e0f-9322-0fa13ccb7914)

### Problem to be solved

If this problem had been solved, the score would have looked neater. And it looks so ugly when the hairpins are located on different levels. Just below I attached a file where from 506 to 515 measures these hairpins
 are located (by default) as shown in the first screenshot
[multi-level_hairpins(dyn).zip](https://github.com/musescore/MuseScore/files/13673737/multi-level_hairpins.dyn.zip)

**Comment by oktophonie** [comment]
Pretty much covered by https://github.com/musescore/MuseScore/issues/16845 and the discussion therein. Hopefully not far off.
