### ISSUE TITLE
Arpegiated Tied notes have wrong duration

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20477]
### Issue type

General playback bug

### Bug description

Arpegiated chord in this example does not sustain for full duration

![Screen Shot 2023-12-14 at 15 18 32](https://github.com/musescore/MuseScore/assets/69917893/5f6df239-543a-4c66-bc22-586acd3e38ba)

### Steps to reproduce

1. Open
[minimal_example.mscz.zip](https://github.com/musescore/MuseScore/files/13673965/minimal_example.mscz.zip)
2. Play, duration ends at barline, not full duration

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233471824, revision: github-musescore-musescore-21cfc4e

### Regression

I don't know

### Operating system

Mac OS 14

**Comment by Jojo-Schmitz** [comment]
Mu3 too :-(
