### ISSUE TITLE
The preview window in the page settings

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20482]
### Your idea

In Musescore 3, a preview window was available in the Page settings section. This feature has been removed in Musescore 4. The question is, why? It was a very useful feature!
![Снимок экрана (75)](https://github.com/musescore/MuseScore/assets/134041121/7705f2c5-8f23-4afc-89be-721a398303e3)
![Снимок экрана (76)](https://github.com/musescore/MuseScore/assets/134041121/ce74baa7-6b17-4284-8999-edca7b081087)

### Problem to be solved

It will be possible to adjust the settings at the same time and monitor how the appearance of the score changes in the preview window. For example, when adjusting the staff space, I do not see if I have adjusted the space sufficiently, since there is no preview window.

**Comment by MarcSabatella** [comment]
The score itself is your preview now - unlike MU3, it updates live.  You can zoom your score way out if you need more context than what you can already see.
