### ISSUE TITLE
The pedal diagram for the harp does not matter for the diatonic glissando

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20491]
### Issue type

General playback bug

### Bug description

Despite the fact that the pedal diagram in the key of "D" is indicated at the beginning of the harp part, the glissando is played in the key in which the key signature of the part is indicated.The glissando style is diatonic.

### Steps to reproduce

everything is shown in the screenshot. The mscz file is also attached.

### Screenshots/Screen recordings

![Снимок экрана (80)](https://github.com/musescore/MuseScore/assets/134041121/083af47c-a308-41dd-9231-1326bc3ba562)
[Harp_glissando.zip](https://github.com/musescore/MuseScore/files/13677015/Harp_glissando.zip)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

No.

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
This is a known limitation of 4.1, but it should work as expect in 4.2.  Please try it out in a nightly build or the beta (see Announcements forum on musescore.org if you need more info).
