### ISSUE TITLE
Incorrect abbreviated names of instruments in Russian

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20519]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

I noticed that by default there are some incorrect instrument names in the score style. I had to manually rename some batches of instruments. For example, why is the abbreviated name of a Snare drum "**Сопр. Уд.**"? Or why in the abbreviated version of the name "Contrabass clarinet" is the next word after "Контрб." written with a capital letter, and not with a lowercase one? Below I have attached a table of recommended abbreviations for the names of the parties. Please fix it.
Those names of instruments that do not have abbreviations should not be invented! For example, Violas. Well, there is no abbreviation for the name Viola in Russian. Why not write the same word in an abbreviated version?
[add_07 (1).pdf](https://github.com/musescore/MuseScore/files/13693331/add_07.1.pdf)

### Steps to reproduce

-

### Screenshots/Screen recordings

What is wrong is circled in red

![Снимок экрана (86)](https://github.com/musescore/MuseScore/assets/134041121/7a43a7f0-7bca-4480-82a4-130e2ac002c7)
![Снимок экрана (87)](https://github.com/musescore/MuseScore/assets/134041121/a085d3d5-2dbd-4106-8a31-4398175cbba6)
![Снимок экрана (85)](https://github.com/musescore/MuseScore/assets/134041121/40a9903f-6dc0-4acf-b703-fb94feac8665)
![Снимок экрана (88)](https://github.com/musescore/MuseScore/assets/134041121/b53df4d1-e296-4873-8f92-833caf71e171)
![Снимок экрана (89)](https://github.com/musescore/MuseScore/assets/134041121/6b96e3c9-0b6a-4957-a805-b631600a681c)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

No.

### Operating system

Windows 11

**Comment by shoogle** [comment]
@Dima12357, translations are submitted by the community. If you'd like to help, please create an account at https://explore.transifex.com/musescore/musescore/ and then you'll be able to change the translation to whatever you like (within reason).

For more info, see this [Wiki page](https://github.com/musescore/MuseScore/wiki/Help-translate-MuseScore). If you need help, please ask in the `#translation` channel of our [Discord server](https://musescore.org/en/handbook/developers-handbook/references/developer-group-chats).

**Comment by Jojo-Schmitz** [comment]
Those updated translations would show up in 4.2, not (any longer) in 4.1.1 though

**Comment by Dima12357** [comment]
> Those updated translations would show up in 4.2, not (any longer) in 4.1.1 though

Thanks, I get it) When will the new version be officially released?

**Comment by shoogle** [comment]
We put out a release candidate for 4.2 yesterday, so the final release could happen any day now.

Now is the time to add any translations you want to appear in the release.
