### ISSUE TITLE
Weird issue with repeats and tremolos

### ISSUE THREAD

**Issue by Fristover** [musescore/MuseScore#20528]
### Issue type

General playback bug

### Bug description

When adding tremolos to a piece with repeat bars _before_ them, the tremolo notes seem to play 1 or even 2 measures too early. 
Update: with further testing I realized tremolos are just ignoring repeat bars, lol.

Happens with both MS Basic and Muse Sounds and with every instrument I've tried

### Steps to reproduce

1. Download and open this file (delete the .zip extension, don't extract): 
[eh.mscz.zip](https://github.com/musescore/MuseScore/files/13698133/eh.mscz.zip)
2. Click "Play"
3. See (hear) the issue

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/68985619/20001fac-5fb0-476c-8b44-75cc2d72129c

### MuseScore Version

4.2 RC

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11, latest canary build

### Additional context

I remember this not being an issue back in 4.1

**Comment by cbjeukendrup** [comment]
Thanks for finding this! I think this regression is serious enough to try to fix it before release.

I've created a potential fix here: https://github.com/musescore/MuseScore/pull/20529

**Comment by DmitryArefiev** [comment]
Fixed in #20529
