### ISSUE TITLE
Tempo Text added from palette doesn't use custom font face

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#20542]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Adding a tempo text from the palette doesn't set the font face to the value set in style/text styles/tempo.

### Steps to reproduce

1. Create a new score
2. In Style/Text Styles/Tempo, set the font face to not-Edwin.
3. Add a tempo text to the score.

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in MuseScore 4.1

### Operating system

Windows 10

**Comment by oktophonie** [comment]
Could not reproduce at first in 4.2, but could once I'd reset the Tempo palette.
Also puts me (heavily) in mind of https://github.com/musescore/MuseScore/issues/13377

**Comment by XiaoMigros** [comment]
Seems to work in latest master, closing for now
