### ISSUE TITLE
Font face ComboBox in Properties doesn't allow text input

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#20543]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

When clicked on the font face combobox in properties, pressing a letter on the keyboard doesn't scroll to that letter font.

### Steps to reproduce

1. Create a new score, add a text element
2. select it, open the font face combobox in properties
3. press 'E' for Edwin; a note E is added in the score instead.

### MuseScore Version

4.2.0

### Regression

I don't know

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
I believe this is a duplicate of https://github.com/musescore/MuseScore/issues/16508

**Comment by XiaoMigros** [comment]
That is correct, thank you
