### ISSUE TITLE
Make a port to wayland in the Linux app

### ISSUE THREAD

**Issue by iWisp360** [musescore/MuseScore#20550]
### Your idea

I think it's time to make this app work natively with wayland, as well as legacy xorg support for LTS systems.

### Problem to be solved

There are a lot of flickering in the app and crashes with a Xwayland session, and the most popular distributions are starting to use Wayland by default.

**Comment by cbjeukendrup** [comment]
For things like this, we almost entirely depend on what Qt supports. Currently, I believe we use 5.15.2 on Linux, but we may want to switch to a self-built Qt 5.15.11, or even the KDE patch collection.

Anyway it would be more useful to log specific issues. These ones currently exist:
- https://github.com/musescore/MuseScore/issues/18598
- https://github.com/musescore/MuseScore/issues/11244 (closed, but back in 4.2; but more or less covered by 18598)
- https://github.com/musescore/MuseScore/issues/18689
- https://github.com/musescore/MuseScore/issues/17275
- https://github.com/musescore/MuseScore/issues/15285
- https://github.com/musescore/MuseScore/issues/10218

Are there any specific other problems?

**Comment by iWisp360** [comment]
There are not any other problems, this is my only issue when using musescore, i am pretty well with my gnome xorg session, but maybe in the future xorg will be dropped, screwing a lot of users

**Comment by raffaem** [comment]
Looks like 4.4 will use Qt 6 ([announcement](https://musescore.org/en/node/361412)).

Hopw to get Wayland support by then?

**Comment by cbjeukendrup** [comment]
Some significant improvements for Wayland have been made in 4.4 (RC downloadable at https://musescore.org/en/node/367322). The Qt Wayland libraries are now packaged with the AppImage again, and a crash that occurred when running in Wayland mode has been fixed, as well as "the" popup positioning issue. Many of the issues I mentioned earlier in https://github.com/musescore/MuseScore/issues/20550#issuecomment-1861757387 have been closed or are about to be closed. 

Therefore I think this overarching issue can be closed now; we will fix the remaining issues individually. Thanks!

**Comment by ell1e** [comment]
For what it's worth, it seems like the [flathub version](https://flathub.org/en/apps/org.musescore.MuseScore) currently doesn't launch with Wayland. On my system, it only opens up when the X11 socket is available.
