### ISSUE TITLE
Visual bug in continuous mode

### ISSUE THREAD

**Issue by BenignPigeon** [musescore/MuseScore#20551]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The score I am working on has been exported from sibelius via the dolet 8 plugin into a musicXML file format. With that out of the way in case it's important, a visual bug as seen in the image below has taken place in continuous view mode.
![image](https://github.com/musescore/MuseScore/assets/85837722/406050d0-ebd4-430d-93b5-c3127ae9e4a8)

My score is supposed to look like this [but in continuous mode]:
![image](https://github.com/musescore/MuseScore/assets/85837722/ecfd70bd-ee88-49ef-a2fd-aa57fd8901a6)

Here is a video of me switching between the modes with another visual bug [appearing numbers which aren't even page numbers] appearing in normal mode.

https://github.com/musescore/MuseScore/assets/85837722/bd52eba2-de67-4d8c-b3de-085bf5ce3f73

### Steps to reproduce

1. Export via musicxml 

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
Happens in 4.0.2 but worked in a previous 4.x version? Really?
Please a) share the score (and the MusicXML) and b) try out 4.2.0, which got released today

**Comment by MarcSabatella** [comment]
My guess is 4.0.2 was a typo and 4.2.0 was meant (seems to read that way now), and that those are insanely large ties, and this is another case of https://musescore.org/en/node/357941

**Comment by Jojo-Schmitz** [comment]
https://musescore.org/en/node/357986 might be another victim

**Comment by LugPaw** [comment]
In the thread above, it seems to suggest that the issue was fixed 13 hours ago, but I dodnloaded 4.2.0 just a few hours ago and had the same problem as the OP.

**Comment by MarcSabatella** [comment]
You are misunderstanding the information you are seeing.  A fix was created 13 hours ago internally, but it hasn’t been merged yet, so there is no nightly build to test yet, and no 4.2.1 release including the proposed fix has been released yet either.

**Comment by oktophonie** [comment]
Reopening: https://github.com/musescore/MuseScore/pull/20559#issuecomment-1867740294

**Comment by Jojo-Schmitz** [comment]
Needed for 4.2.1 too, so better keep open

**Comment by RomanPudashkin** [comment]
> Needed for 4.2.1 too, so better keep open

It's in "Needs porting". We'll port it later and move it to "Done"
