### ISSUE TITLE
Sounds continue across Section Break

### ISSUE THREAD

**Issue by dulciepercy** [musescore/MuseScore#20557]
### Issue type

General playback bug

### Bug description

There should be a default 3s silence between sections (using Section Break from Layout Palette.  Using a sound like cello or violin the sound continues across the break.

This was working fine in the nightly portable from earlier this week 4.2.0.23460505.  This versions still plays back correctly and loads Muse Guitars.  Just playing back differently in release version.

### Steps to reproduce

1. Create string score
2. Enter section break
3. Enter note of bar length at end of first and beginning of second section
4. Hit Play

### MuseScore Version

4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by RomanPudashkin** [comment]
Caused by: https://github.com/musescore/MuseScore/commit/f7a332c27632252636cf9750380b8ed7718d1b95

(the change inside PlaybackEventsRenderer::renderNoteEvents)

**Comment by Jojo-Schmitz** [comment]
Is that also caesing the same problem for breaths and caesuras? Or is that a separate issue

**Comment by RomanPudashkin** [comment]
> Is that also caesing the same problem for breaths and caesuras? Or is that a separate issue

That's a separate issue, but the cause is very similar

**Comment by Cutieguwu** [comment]
Seeing this behaviour with at least Tenor Saxophone as well. Behaviour is not influenced by changing between Muse Sounds and Soundfonts. I suspect this is present for all instruments.

Any note before a section break continues playing during what should be silence.

Manjaro linux
MuseScore 4.2


https://github.com/musescore/MuseScore/assets/109807080/8f1245de-030b-4db9-989c-fc62cac65ef9

**Comment by Jojo-Schmitz** [comment]
It is not a matter of which instrument is used

**Comment by DmitryArefiev** [comment]
Fixed #20982
