### ISSUE TITLE
Instruments can not get muted in mixer independently in score and parts

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#20564]
### Issue type

General playback bug

### Steps to reproduce

In a score (e.g. closed score SATB + Piano) with parts (for Choir, i.e. Men and Women) chord symbols (above the Womens staff) mute them in the main score (as there is a full piano they'd otherwise collide with).
Now in the part (for Choir) they are muted too, but would be valuable for (self-)rehearsal.
If you unmute them in the part, they unmute in the main score too, which then collides with the piano notes.

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

See also #18092
For me this is one of several issues that prevent me from switching from Mu3 to Mu4

**Comment by bkunda** [comment]
This is a known issue and has been raised [here](https://github.com/musescore/MuseScore/pull/19433#issuecomment-1790343290) in this PR. We aim to address it when the PR gets picked up again by @mathesoncalum.

**Comment by Jojo-Schmitz** [comment]
But #19235 is a different thing, it is abpout the option to mutu or unmute hidden instruments
