### ISSUE TITLE
Can't remove an instrument under specific circumstances having added an instrument

### ISSUE THREAD

**Issue by symonjim** [musescore/MuseScore#20567]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Download piano score from MuseScore. Add instrument - violin. Copy piano bass clef staff of music to violin staff. Transpose all of that up one octave. Remove piano from score. Result: The score goes blue/blank, i.e. both instruments are removed.

Attempted workaround: Add another violin. Copy all from first added violin to second added violin. Remove piano from score. This works leaving the two violins. Remove the second added violin. This works leaving the first added violin as desired except that the part is no longer labeled as a violin. Sound is of a violin.

original score: (Here we are doing MuseScore bug reports but it won't let me attach a .mscz file even though that may have embedded info of use.)

[Chopin_Nocturne_in_D-Flat_Major_Op._27_No._2.pdf](https://github.com/musescore/MuseScore/files/13718748/Chopin_Nocturne_in_D-Flat_Major_Op._27_No._2.pdf)

### Steps to reproduce

See bug description for steps to reproduce.

### MuseScore Version

OS: Windows 10 (10.0), Arch.: x86_64, MuseScore version (64-bit): 3.6.2.548021803, revision: github-musescore-musescore-3224f34

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 (10.0), Arch.: x86_64

**Comment by MarcSabatella** [comment]
To attach a MuseScore file, ZIP it, or just rename it to end in .zip

**Comment by symonjim** [comment]
Closing. I neglected to read the manual pages which do state that you cannot copy and paste from one staff of a piano score.

**Comment by MarcSabatella** [comment]
? You can definitely copy and paste from piano staves.  Sounds like you are having some sort of problem understanding how to use MuseScore.  Please ask for help in the Support forum at musescore.org and attach your score and describe what you are trying to do in more detail there.
