### ISSUE TITLE
cresc. line is not clickable

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#20561]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Steps to reproduce

1. Add cresc. line to score
2. Try to click on the line

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by DmitryArefiev** [comment]
Fixed in #20590
