### ISSUE TITLE
Playback cursor eats cresc. line

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#20562]
### Issue type

Engraving bug (incorrect score rendering)

### Steps to reproduce

1. Add cresc. line to score
2. Start playback

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/139459177/c3add696-95f0-48bb-8e02-6e10a043a9f3

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by DmitryArefiev** [comment]
Fixed in #20590
