### ISSUE TITLE
cresc. line disappears when the start text is out of view

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#20560]
### Issue type

Engraving bug (incorrect score rendering)

### Steps to reproduce

1. Add cresc. (or dim.) line to the score
2. Scroll until the cresc. text is out of view
3. The line disappears

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/139459177/54d4ae88-eb3b-4ab9-93c4-73198d820e38

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in MuseScore 4.1

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
It's a bit of a long shot, but somehow I think this might turn out to be related to https://github.com/musescore/MuseScore/issues/19924#issuecomment-1851884312.

**Comment by DmitryArefiev** [comment]
Fixed in #20590
