### ISSUE TITLE
4.2.0 ARM appimages removed after release 

### ISSUE THREAD

**Issue by theofficialgman** [musescore/MuseScore#20578]
### Issue type

Other type of issue

### Bug description

Arm appimages were posted prior to yesterday on 4.2 release. Today they are gone.

### Steps to reproduce

Go to latest release page

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux

**Comment by RomanPudashkin** [comment]
I removed them because they were causing problems with updating to 4.2 on linux (when users clicked on the update button, we always downloaded the arm build). But that's not the fault of the arm builds. There is a bug in our update system, that has to be fixed first before publishing the arm builds :(

**Comment by theofficialgman** [comment]
@Eism since this was assigned to you, I will point out the issue
the updater only checks the filetype (hardcoded to appimage) when parsing github assets for what file to download 

https://github.com/musescore/MuseScore/blob/1107b06e687dc6856b45f4d384b0d1f395de5daf/src/update/internal/updateservice.cpp#L43-L54

https://github.com/musescore/MuseScore/blob/1107b06e687dc6856b45f4d384b0d1f395de5daf/src/update/internal/updateservice.cpp#L176-L189

You will need to do a more holistic check for architecture and filetype when matching. buildcpuarchitecture and currentcpuarchitecture from QT should be suitable (you might want to use the former so as to not change the architecture of the application from what they are currently using (eg: arm userspace with arm64 linux kernel)).

https://doc.qt.io/qt-5/qsysinfo.html#buildCpuArchitecture

also take care to map the QT names to the names used by the assets (arm->armv7l, arm64->aarch64, x86_64->x86_64)

**Comment by Eism** [comment]
@theofficialgman please check the update for builds from my [PR](https://github.com/musescore/MuseScore/pull/20928) for arm/aarch64, If you have

I've created a release with arm and aarch builds(from the latest release) for testing. To access it, you'll need to enable 'allowUpdateOnPreRelease' in the settings in DevTools -> Settings.
