### ISSUE TITLE
Pedals do not work on mallet percussion instruments

### ISSUE THREAD

**Issue by a-bozo** [musescore/MuseScore#20579]
### Issue type

General playback bug

### Bug description

Any time I write pedaling, using any of the provided pedal lines, mallet percussion instruments that use pedal (i.e. Vibraphone, Glockenspiel) do not respond to it and play the music as if it were written to be "dry" or without pedal. Duly note that piano pedaling still responds. 

### Steps to reproduce

1. New Score using any amount of vibraphones
2. Write a sixteenth note run- pedaling differences are easiest to distinguish in fast passages
3. Go to 'lines"
4. Select any of the pedal notation and apply it to the entire sixteenth note run
5. Listen to playback

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by bkunda** [comment]
Confirmed with the vibraphone – pedal worked in 4.1.1, doesn't work in 4.2.

**Comment by DmitryArefiev** [comment]
Fixed in #20929
