### ISSUE TITLE
Edit > Undo/Redo menu items: display the name of the action to be undone/redone

### ISSUE THREAD

**Issue by macias** [musescore/MuseScore#20573]
### Your idea

Currently the two menu items read like this:
* Undo
* Redo

It would be much more helpful to have it with appropriate names, example:
* Undo Add 1/4 note
* Redo Color change

It is especially important because I cannot tell if given action is registered for undo in the first place. So real example was:
* Stretch -> Increase layout stretch
* I didn't see what happened so to be sure...
* Undo
* Apparently Stretch was not registered, so Undo triggered "Undo Note insert", which in turn (just accident) change the page break

### Problem to be solved

More informative UI, and less surprises.

### Prior art

N/A

### Additional context

None.

**Comment by Jojo-Schmitz** [comment]
Might be done via a tooltip

**Comment by MarcSabatella** [comment]
Did you have any measures selected when issuing the stretch command?  If not, no surprise nothing was stretch and that therefore there was nothing to undo.  But if you are finding that increase stretch with an actual selection doesn’t undo, please open a separate issue for that, with score and steps to reproduce.

**Comment by macias** [comment]
@MarcSabatella  Thank you for tips, I am beginner so I probably did something stupid, but the issue here is not stretch -- it was just example, but undo/redo -- I don't know what I am about to undo or redo. And since they store history even advanced user would (probably) not know by heart what 5th undo in a row would undo.
