### ISSUE TITLE
Glissandos don't play back on tied notes.

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#20570]
### Issue type

General playback bug

### Bug description

Glissandos don't play back on tied notes. This is true for soundfonts, VSTs, and Muse Sounds.

I am aware of #19380 (which is unrelated and actually seems to be fixed) and #12971 (which may be the same problem).

### Steps to reproduce

1. Tie notes together.
2. Attempt to use a glissando beginning from the last tied note.
3. Be sad when nothing happens :(

### Screenshots/Screen recordings

It goes directly from the G to the E in this image, with no glissando:
![image](https://github.com/musescore/MuseScore/assets/87204246/bdff5083-d0a6-4533-9b4f-106e8bbdd41d)

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x and now is broken

### Operating system

OS: Windows 10 Version 2009, Arch.: x86_64

**Comment by bkunda** [comment]
Confirmed this used to work with SoundFont in 4.1.1 and no longer works in 4.2.

**Comment by handrews** [comment]
This is also happening for me with basic sounds (macOS 12.6, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c), note that my MacBook's actual processors are Apple M1s.

**Comment by WhatGoesUp** [comment]
This issue also applies to guitar bends on tied notes. Circled notes in image won't play.
MS version info: OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c
![Tied bends](https://github.com/musescore/MuseScore/assets/155248678/35315c48-11f3-4a48-af9b-3a39e496cc3f)

**Comment by WhatGoesUp** [comment]
This still does not work in 4.2.1 for Muse Guitars Vol 1. Works for all other Muse Sounds I've tested though. Should I open a new issue for that?
