### ISSUE TITLE
Playback bug with tied (whole-)notes after tempo change (note duration is longer/shorter than it should)

### ISSUE THREAD

**Issue by Muetzenkrieger** [musescore/MuseScore#20577]
### Issue type

General playback bug

### Bug description

I found that in the new Musescore version (4.2) whole notes, which are tied over a barline last much longer than notated. Sometimes they last a whole extra bar sometimes just a half note insted of a quarter etc.
This occures only after a tempo change (in my case from 50 bpm to 100 bpm) and when I tried to recreate the bug in a new score without the tempo change, it worked fine.

### Steps to reproduce

**Case №1**

1. Open [A Walk On The Milkyway_neu_CB - copy.zip](https://github.com/musescore/MuseScore/files/13740206/A.Walk.On.The.Milkyway_neu_CB.-.copy.zip)
2. Go to **C** rehearsal mark (measure 22)
3. Play Alto Sax staff

https://github.com/musescore/MuseScore/assets/90187801/9d4abbcc-db02-45a6-9a95-5417b97f0cea

**Case №2**  https://musescore.org/en/node/358085

1. Open [Gallery 3.zip](https://github.com/musescore/MuseScore/files/13741528/Gallery.3.zip)
2. Play from measure 87

https://github.com/musescore/MuseScore/assets/90187801/ec9e8e5e-8f97-4832-af13-064ddda6c7a7

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in **MuseScore 4.1.1**
### Operating system

Windows 10

### Additional context

Could be related to #15609 changes

**Comment by DmitryArefiev** [comment]
@Muetzenkrieger Please attach the score

**Comment by Muetzenkrieger** [comment]
I can't upload mscz files here. Here is a link from which you can download it:

https://www.dropbox.com/scl/fi/ci0imz0bvmbynplo8t65z/A-Walk-On-The-Milkyway_neu_CB-copy.mscz?rlkey=b0bzv3qiupiyk5xiupx3eqix6&dl=0

I hope this works.

**Comment by MarcSabatella** [comment]
For future reference, you can upload scores here by zipping them, or even just renaming their extension from mscz to zip.

I can confirm the issue in this file - tied notes at letter C seem way off.

**Comment by DmitryArefiev** [comment]
Thanks! I can reproduce it too. This a fresh regression (works in 4.1.1)

**Comment by DmitryArefiev** [comment]
> Please also check (the score from) https://musescore.org/en/node/358085, seems the almost exact opposite, a long tied note stops playing back prematurely

Yes, it's probably the same and related to #15609 (doesn't occur before those changes).

I'll add https://musescore.org/en/node/358085 case to the description

Thanks!

**Comment by cbjeukendrup** [comment]
I will look into this later today

**Comment by MarcSabatella** [comment]
There is a possibly related case that *does* occur in 4.1.1 - see https://www.reddit.com/r/Musescore/comments/18e8hnc/another_problem_with_ties/.  I can confirm the score attached to that plays the tie too short in both 4.1.1 and 4.2.  I guess not surprisingly, the PR here doesn't fix this case.

**Comment by DmitryArefiev** [comment]
Fixed in #20644
