### ISSUE TITLE
Measure and Staff/Part properties dialogs don't work via keyboard (and crash)

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#20580]
### Issue type

Crash or freeze

### Bug description

This is a sneaky one. When opened via the keyboard, the dialogs appear to work properly right up until you click the OK button.

When you click OK in:

- **Staff/Part properties:** MuseScore crashes.
- **Measure properties:** The dialog closes as you would expect, but the score is **not** updated to reflect whatever changes you made in the dialog.

Also, both dialogs crash if you try to use the next/previous staff/measure buttons in the bottom left of the dialogs.

### Steps to reproduce

1. Select a note or rest.
2. Press Shift+Right to create a range selection.
3. Press the Menu key or Shift+10 shortcut.
4. Choose **Measure properties** or **Staff/Part properties**.
5. Make some changes and click OK, or use the next/previous measure/staff buttons in the bottom left of the dialog.

### Screenshots/Screen recordings

Staff/Part properties | Measure properties
---|---
![image](https://github.com/musescore/MuseScore/assets/11011881/85110a93-2190-4501-a296-583c288ff555) | ![image](https://github.com/musescore/MuseScore/assets/11011881/b0d21814-6cef-4965-b712-57efa82917a2)

### MuseScore Version

Master and 4.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

Fix on the way.

**Comment by mercuree** [comment]
Maybe related issue #19425

**Comment by DmitryArefiev** [comment]
Fixed in #20581
