### ISSUE TITLE
Vertical frame height reset to something other than 0

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#20583]
### Your idea

When clicking the reset button above the height property of a vertical frame, it should revert to a default value (perhaps 10 spaces, which new frames are created at) rather than 0. As we're resetting the height properties, this should also re-enable `autoSizeEnabled` (seemingly hidden property that defaults to On for new frames) on the frame.

### Problem to be solved

At present, resetting the height of a vertical frame makes it 0. If you deselect the frame, it's then invisible and you can't select it again.

### Additional context

See #20584 for more info on `autoSizeEnabled`.

**Comment by bkunda** [comment]
There indeed does appear to be some jankery going on here. Needs further investigation @zacjansheski @DmitryArefiev 

[See video](https://www.dropbox.com/s/n1dpvx22zxw2ref/vertical-frame.mov?dl=0)

**Comment by zacjansheski** [comment]
The problem in Bradley's video is a regression in 4.2 from 4.1.1
