### ISSUE TITLE
Tie to hidden grace note after is broken in part

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#20596]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Tie to hidden grace note after is broken in part

### Steps to reproduce

see video

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1646034/07de7824-c1a9-4120-b43d-2c05c95d4f47

### MuseScore Version

4.2

### Regression

No.

### Operating system

Ubuntu 22.04

**Comment by SteveBlower** [comment]
I just ran into this one (in MU 4.3.0) while creating a score with a harp part full of let rings.  It looked fine in the score but the harp part looked like a child had scribbled all over it.  

![image](https://github.com/musescore/MuseScore/assets/60138048/881125bc-49cf-49e9-8ebe-ee6b42ad8fd2)


For the record, the problem also occurs with unhidden grace notes after (I forgot to hide some).

And a (tedious) workaround is to toggle each tie in the part on and off again with keyboard shortcut T.
