### ISSUE TITLE
Slurs/ties with a custom direction in Mu3 looses thise when imported into Mu4

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#20597]
### Issue type

Import/export issue

### Steps to reproduce

Have a Mu3 score with ties and slurs
Change them to above or below rather than automatic, best to the opposite of what they show.
Open that score in Mu4

-> Slurs and ties got set to automatic

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

This can seriously destroy the layout and may cause the need for a major overhaul of the score

**Comment by mercuree** [comment]
Can't reproduce. Is it specific to certain score?

**Comment by oktophonie** [comment]
All that should be reset is explicit direction of ties between chords (as described [here](https://musescore.org/en/node/330793)); slurs and single-note ties should not be affected. That's the behaviour I experience in 4.0, 4.1 and 4.2.

**Comment by Jojo-Schmitz** [comment]
[Mary,_Did_You_Know.zip](https://github.com/musescore/MuseScore/files/13728530/Mary._Did_You_Know.zip)
Check this one, measure 2, 2nd tie in Piano bass clef, measure 8, Piano bass clef, 2 of the 3 the ties, measure 11-12, piano treble clef, the bottom slur

**Comment by oktophonie** [comment]
Well, it's working as described since 4.0.

**Comment by Jojo-Schmitz** [comment]
Do you really not see that these changes ties look rather bad in Mu4?
