### ISSUE TITLE
No longer able to drag a section of music to transpose it.

### ISSUE THREAD

**Issue by samsoeder** [musescore/MuseScore#20606]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Before musescore 4.2 it was possible to select a section of music and drag it up or down to diatonically transpose the entire selection. This no longer works and musescore only transposes the note you drag.

### Steps to reproduce

Select a section of music
grab a note and drag it
only a single note is transposed.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/119996302/29c90124-f8f1-46ab-ac96-569a8be13f8b

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

**Comment by bkunda** [comment]
Confirmed it is a regression from 4.1.1 (tested macOS).

**Comment by MarcSabatella** [comment]
It surprises me greatly that this comes up as often as it does - who knew so many people were using drag to transpose selections! - but this is another that is reported multiple times per day in the forums and social media.  I'd recommend bumping the priority if there is any chance of it not making 4.2.1 otherwise.

**Comment by cbjeukendrup** [comment]
Caused by https://github.com/musescore/MuseScore/commit/c72fbfff42ee92b40b95a4d10dc7ebf709a4874d (@mathesoncalum FYI 🙂)
