### ISSUE TITLE
Muted sounds are very soft

### ISSUE THREAD

**Issue by FranktheCat5** [musescore/MuseScore#20604]
### Issue type

General playback bug

### Bug description

Muted brass instruments sound considerably softer than marked. Straight mutes soften a bit, but not nearly so much.

### Steps to reproduce

Mark a trumpet, horn, or trombone line as muted (con sord.)

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by bkunda** [comment]
I wonder whether this is really an issue?
To my ear, the relative volume differences seem quite reasonable [here](https://www.dropbox.com/s/tm6hac2hr3f9g44/brass-mutes.mov?dl=0)

I'll close this for now unless it transpires there is a genuine bug here.

**Comment by MarcSabatella** [comment]
To my the volume difference between open and muted is consistent with the overall large dynamic range of Muse Brass.  But FWIW, it seems to be a pretty common complaint based on discussion on Discord and elsewhere - many people are perceiving the volume differences to be more than they expect.
