### ISSUE TITLE
The ability to add the prefix "sub" to the glyph of the dynamics

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20613]
### Your idea

I suggest adding glyphs with the prefix "sub" (subito) to the dynamics palette, for example "sub p"

### Problem to be solved

This will allow the reader/performer to understand that the dynamic quickly, almost suddenly, changes the volume to about the appropriate range

**Comment by oktophonie** [comment]
You can do this yourself; for example:

- Add a 'p' dynamic to the score
- Double click it to edit and type 'sub ' before the 'p'
- Hold down Ctrl+Shift and drag the 'sub p' item into the Dynamics palette (or wherever you want it) - see the [handbook](https://musescore.org/en/handbook/4/palettes#add-score-elements)

**Comment by bkunda** [comment]
For something like this, it seems there already exists a workable way of achieving this goal. Realistically speaking, we won't be able to prioritise it as a new feature any time soon (of course if somebody else wants to take it up, then that's fine – I could see these kinds of elements being tucked away under "More" in the relevant palettes. But again...it's very easy for the user to do this on a needs-basis). 
Closing for now unless a significant use case is presented.
