### ISSUE TITLE
In a single part consisting of several staffs, one glyph of dynamics covers all the staffs of the part

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20612]
### Issue type

General playback bug

### Bug description

If a glyph of dynamics is added to a note on any of the several staffs of the party, then the corresponding volume of the dynamics will cover all the staffs of the party. This is wrong. The glyph of the dynamics should not cover the entire party as a whole, but only the corresponding staff.

### Steps to reproduce

-

### Screenshots/Screen recordings

![Снимок экрана (951)](https://github.com/musescore/MuseScore/assets/134041121/b7477979-3a42-4c99-8a88-59e3bab56852)

https://github.com/musescore/MuseScore/assets/134041121/e5a6033a-ef43-4231-8a64-861ce71edbfc

[Glyphs.zip](https://github.com/musescore/MuseScore/files/13733567/Glyphs.zip)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 11

### Additional context

This bug works not only with the string part, but with all other parts that have two or more staffs.

**Comment by oktophonie** [comment]
This will (should!) be addressed by https://github.com/musescore/MuseScore/issues/19137

**Comment by Dima12357** [comment]
In this issue, I described the coverage of dynamics not by votes, but by
staffs in the composition of the party! Although the voices are also
important. I believe that my issue should have similar content to issue
#16812 <https://github.com/musescore/MuseScore/issues/16812>

чт, 21 дек. 2023 г. в 14:16, Simon ***@***.***>:
