### ISSUE TITLE
Replace Instrument dialog: OK/Cancel buttons wrongly positioned when instrument description is long

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#20617]
### Issue type

UI bug (incorrect info or interface appearance)

### Steps to reproduce

1. In the instruments panel, click an instrument's ⚙️ button 
2. click "Replace instrument"
3. Click on different instruments and see how the buttons are dancing around

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/48658420/b6cbef7e-9c67-4543-8550-3a6bc447bd39

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

\*

### Additional context

_Probably_ used to work in 4.1.1 but I'm not too sure

**Comment by bkunda** [comment]
Confirmed in macOS. This is a regression from 4.1.1:

4.1.1:
<img width="627" alt="Screenshot 2023-12-21 at 3 45 28 pm" src="https://github.com/musescore/MuseScore/assets/86290556/b9101787-fabb-4bf7-a06d-e82042ebdb24">

4.2:
<img width="615" alt="Screenshot 2023-12-21 at 3 45 33 pm" src="https://github.com/musescore/MuseScore/assets/86290556/8bca08d0-019c-4cc5-ad5e-d0f86bb75d58">

**Comment by DmitryArefiev** [comment]
Fixed in #20723
