### ISSUE TITLE
Crash on score created from template containing slurs

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#20620]
### Issue type

Crash or freeze

### Bug description

A score created from a template containing slurs will crash on editing

### Steps to reproduce

1. save and extra the attached score to your Templates folder
2. create score from that template, all default setting
3. Ctrl+A to select all

Result: crash

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Debian 11

### Additional context

The score itself is nothing special - just a mostly empty file created from the Treble template.  It contains just two notes - and a slur.  Delete the slur from the score and resave to your Templates folder, now you can create scores from it safely.  At least in my initial tests, it's that simple - any template containing a slur will create a score that crashes almost immediately.

**Comment by MarcSabatella** [comment]
Forgot the file - but it really is just two notes with a slur...

[slur.zip](https://github.com/musescore/MuseScore/files/13734969/slur.zip)

![image](https://github.com/musescore/MuseScore/assets/1799936/94b71d60-9760-4980-b0dc-61057c82e911)

**Comment by Jojo-Schmitz** [comment]
Came up in https://musescore.org/en/node/358086

**Comment by Jojo-Schmitz** [comment]
Workaround: directly after having created the score, save it, close, reopen
