### ISSUE TITLE
Score and parts synchronization strings need English (US) localization

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#20636]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The score and parts feature has text that has not been localized to US English—just need to swap in some Zs.

- "Score and part synchronisation" should read "...synchronization"
- "Synchonise with main score" should read "Synchronize..."

### Steps to reproduce

1. Set language to "English (US)" in Preferences > General (and restart if required)
2. Open a part
3. Select a note
4. In properties, see the spelling errors listed in the description

### Screenshots/Screen recordings

<img width="308" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/58a72921-1341-4022-b202-7a84833b17c7">

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

No.

### Operating system

OS: macOS 14.1, Arch.: x86_64

**Comment by Jojo-Schmitz** [comment]
Preliminar but immediate fix: I've updated the tzranslations

**Comment by Jojo-Schmitz** [comment]
Plus PRs for master and 4.2.1

**Comment by cbjeukendrup** [comment]
I've merged the PRs without testing because testing won't make sense until the US English versions are pushed to Transifex and get translated back into UK.

Temporarily re-opening until I we push the strings to Transifex (which turns out to be not as trivial as expected: https://github.com/musescore/MuseScore/pull/20641#issuecomment-1867114639)

**Comment by cbjeukendrup** [comment]
Yes, it seems to work well now; in Dutch, after a "Check for language updates", the correct translation shows up in both 4.2.1 and 4.2.0, and US English has the right thing now in both versions too.
