### ISSUE TITLE
Drag multiple notes in guitar TAB to adjacent strings

### ISSUE THREAD

**Issue by apbreaux** [musescore/MuseScore#20633]
### Your idea

In Musescore 3 I was able to select multiple notes in my tab and then hold+drag them, as a group, to adjacent strings. I am not able to do that in Musescore 4. Is there a way to make that possible?

### Problem to be solved

Dragging more than one note at a time to change fingering.

**Comment by oktophonie** [comment]
I think this is the same as https://github.com/musescore/MuseScore/issues/20606 - it used to work in 4.1 but something's gone awry in 4.2.

Good news is that we're going to do our best to fix this for the imminent 4.2.1 patch.
