### ISSUE TITLE
Change MMrest default shortcut

### ISSUE THREAD

**Issue by jeetee** [musescore/MuseScore#20650]
### Your idea

Please consider changing (or removing) the default shortcut for toggle multimeasure rest display to something less accidental prone than `M`. (Ctrl/Cmd+Shift+M is available).

### Problem to be solved

Prevent support requests from users (mostly on qwerty layouts) that activate mmrest display by accident, likely when going for note input.
As we already automatically enable mmrest display in parts by default, the user action of toggling them should not be that common to warrant a single-stroke key press residing in the risk area of other high volume actions.

**Comment by bkunda** [comment]
Good suggestion. Let's run with Ctrl/Cmd+Shift+M then :-) 
Thanks!

**Comment by vashutangri** [comment]
Hey, I would love to work on this issue. I do have a question, should I just replace with the new shortcut in shortcuts.xml or should I change the -Mac and _AZERTY XML files as well?

**Comment by cbjeukendrup** [comment]
Yes, editing all three of those files is good.
