### ISSUE TITLE
New added instrument doesn't show

### ISSUE THREAD

**Issue by rubiot** [musescore/MuseScore#20655]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Sometimes I add a new instrument to an existing score and it does not show in the main score, even thou it is visible in the instruments tab.
I found out that if I create a part for it, add some notes and go back the the main score it displays correctly.
It doesn't happen in every score, but once it happens it is consistent.

### Steps to reproduce

1. Open an existing score.
2. Go to the Instruments tab and press "Add" button. The instrument doesn't show in the main score.
3. Click the "Parts" button, add the part for the new instrument, and add some notes.
4. Go back the the main score. The part now shows.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/8127450/16e36323-1532-4c08-a82b-39972ef99ec6

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-233560505, revision: github-musescore-musescore-757fb4c

### Regression

I don't know

### Operating system

Windows 11

### Additional context

[Newly added instrument hidden.zip](https://github.com/musescore/MuseScore/files/13753092/Newly.added.instrument.hidden.zip)

**Comment by MarcSabatella** [comment]
Your score is set to hide empty staves 0 you must have forgot you enabled that at some point.  Turn this option back off in Format / Style / Score.

**Comment by rubiot** [comment]
Hmmm... I don't remember changing this setting. But, even though this is expected behavior, I'd say this is not what a user expects after adding a new instrument. Perhaps there's a better way to handle this. Maybe the little eye icon could reflect the actual status of the stave and overwrite it if clicked.
