### ISSUE TITLE
Range Select Hairpins (w/ Selection Filter?) Like Dynamics & Notes

### ISSUE THREAD

**Issue by rich777300** [musescore/MuseScore#20664]
### Your idea

My idea is to have a way to be able to select multiple hairpins across multiple staves/systems like we can with notes, dynamics, etc. using the [SHIFT] key.

Holding [SHIFT], it would be nice to be able to click for example a hairpin in say the first measure of the topmost stave in my score, then click a hairpin in a later measure in the bottommost stave in my score, and all hairpins in between will be selected.

Maybe we can ensure it's only hairpins (or anything else we want) via selection filter, just that right now I can't find a way to get selection filter to work with hairpins like I can for dynamics: deselect Voices 1-4 and clicking dynamics using [SHIFT] works but not hairpins

### Problem to be solved

Unless there's an alternative I don't know about, I have to hold [CTRL] and click like 20 individual hairpins down my score everytime I change my mind about something I'm writing.

### Additional context
Solution is to select a range, right click say a hairpin, then go Select > Select similar in this range

**Comment by MarcSabatella** [comment]
Even though there is a way  select range, right-click hairpin, select / similar in this range - it's still a valid request.  But, a duplicate of https://github.com/musescore/MuseScore/issues/19865
