### ISSUE TITLE
adding caesura causing playback problems after 4.2 update

### ISSUE THREAD

**Issue by wiffy28** [musescore/MuseScore#20669]
### Issue type

General playback bug

### Bug description

when i add a caesura, it will not pause and causes mismatch between the playback bar indicator and the actual playback
also, playback timing of individual parts are also messed up
i was editing the same score while ago in ver 4.1 and it wasn't a problem there, but since i edited and saved using 4.2, now i can't edit using the old (properly working) 4.1 app 
i managed to salvaged it by exporting the score to midi, and then reopening that in the 4.1 app, but it lost all the dynamics and slurs, accent, etc

### Steps to reproduce

add a caesura to a note
start the playback

### Screenshots/Screen recordings

1. playback in 4.2 (bugged)

https://github.com/musescore/MuseScore/assets/154666339/6570b89c-7ea7-41b5-a2e4-18dc68814b65

2. playback in 4.1 (proper)

https://github.com/musescore/MuseScore/assets/154666339/56943f35-e114-4883-8eae-b719e5826aa1

### MuseScore Version

4.2, also tried the latest 4.2.1 nightly but same problem

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.1.1

**Comment by wiffy28** [comment]
seems like the video link of the first one isn't working, i am reattaching it

1. playback in 4.2 (bugged)
https://github.com/musescore/MuseScore/assets/154666339/a6487db2-9ac3-409c-ab2c-25091d382d7e

**Comment by MarcSabatella** [comment]
See also https://github.com/musescore/MuseScore/issues/20557.  Seems to be the same basic cause, and presumably the same change can be applied to both cases, but it will be important to be sure both are tested.

**Comment by DmitryArefiev** [comment]
@wiffy28 Can you attach video with sound please?

**Comment by MarcSabatella** [comment]
I can reproduce this easily with any score - the last note before a caesura always sustains when there should be silence.  It's been reported often in the forums as well.  Here is a simple example:

[Screen recording 2023-12-28 7.13.35 AM.webm](https://github.com/musescore/MuseScore/assets/1799936/7e31aba5-1444-4930-91a3-3aa09b66dffe)

**Comment by MarcSabatella** [comment]
@bkunda I see this hasn't yet received a priority or been added to the 4.2.1 project.  next to the super-sized ties, this is easily the most commonly-reported issue we are seeing in the forums, social media, etc, with multiple reports per day on average.  It's *probably* the same underlying cause as #20557 as mentioned previously, but we definitely don't want this to fall through the cracks!

**Comment by DmitryArefiev** [comment]
Fixed #20982
