### ISSUE TITLE
Score rendering completely incorrect after upgrade

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#20665]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

See attached image.  The score (previously saved in most recent 4.1.x release with no changes) is now rendered completely incorrectly in the Continuous view (horizontal).  The view in the Navigator is also corrupted.  The Page view seems to be okay.
![Muse score 4 2 bad rendering](https://github.com/musescore/MuseScore/assets/137847641/e760dcd6-c938-4869-9f19-d1777064e4d9)
![Muse score 4 2 bad rendering2](https://github.com/musescore/MuseScore/assets/137847641/3bc554c0-1e0a-4b9a-af20-39a74eb5af86)
![Muse score 4 2 bad rendering3](https://github.com/musescore/MuseScore/assets/137847641/8fc9de9c-5d89-4f2f-a1a9-9407bcf98f74)

It also seems to take several seconds longer to open the file than previously.

### Steps to reproduce

1. Open attached MS4 file 
2. Observed incorrect rendering in Continuous View (horizontal).

### Screenshots/Screen recordings

[
![Muse score 4 2 bad rendering](https://github.com/musescore/MuseScore/assets/137847641/9bf07fe9-e163-4f94-b4d2-383cca70a945)
![Muse score 4 2 bad rendering2](https://github.com/musescore/MuseScore/assets/137847641/a8841808-a57e-43f1-896f-a04420c1d944)
](url)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10 Home 10.0.19045 Build 19045

### Additional context

See attached Musescore file.
[Bad rendering.zip](https://github.com/musescore/MuseScore/files/13758085/Bad.rendering.zip)

**Comment by seisfeldt** [comment]
I tried the latest nightly build  4.2.1-233570505 and I don't see the problem.  Hopefully the bug has been identified.  Thanks!

**Comment by mmeyn** [comment]
This looks like #20551.
