### ISSUE TITLE
Bold and insert measure are on the same keybind

### ISSUE THREAD

**Issue by PholMC** [musescore/MuseScore#20660]
### Issue type

Accessibility issue (e.g. for keyboard-only or screen reader users)

### Bug description

When resetting your preferences or fresh installing Musescore, for some reason, CTRL+B is assigned to "Insert measure at the end of a score" and "Format text: bold". I don't think this was an issue back in MS3.

### Steps to reproduce

1. Go into Edit > Preferences > Shortcuts, and then click "reset preferences".
2. Search "CTRL+B" in the shortcuts menu and you should see the shortcut being assigned to two different actions.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/124211487/77320386-4c81-4223-9f43-b8bed905331e)

### MuseScore Version

4.2.0

### Regression

I don't know

### Operating system

Windows 10

**Comment by MarcSabatella** [comment]
See also https://github.com/musescore/MuseScore/issues/14496.  It's always been the case that Ctrl+B has different actions assigned for text and music, but it used to work without conflict.  Now it seems only one of these can be active at once.

**Comment by bkunda** [comment]
Seems this might actually duplicate #14496. Let's close it for now (unless there's something unique about the reproduction steps here).
