### ISSUE TITLE
Musescore on linux is not playing audio at all

### ISSUE THREAD

**Issue by echometerain** [musescore/MuseScore#20690]
### Issue type

General playback bug

### Bug description

This is both a playback bug and a crashing bug. When I open an existing score and press play, the playhead appears but never moves and no sound is produced. When I select a note, no sound is produced either. When I open a new score with a ms-basic instrument, the same behavior persists. When I open a new score with a muse sounds instrument, musescore crashes shortly after placing the first note.

### Steps to reproduce

Playback issue:
1. open musescore
2. open an existing score
3. press spacebar
4. doesn't play

Crashing issue:
1. open musescore
2. open a new score
3. enter a note
4. crashes

### Screenshots/Screen recordings

https://youtu.be/mdU1vpQPCfw (file was too big to fit on github)
[ms_diagnostic.zip](https://github.com/musescore/MuseScore/files/13761892/ms_diagnostic.zip) (all the logs are from after the factory reset)

### MuseScore Version

4.2, 4.1.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

KDE Neon 5.27 x86_64, based on Ubuntu Jammy 22.04

### Additional context

I originally encountered this issue on version 4.1.1 but I switched to 4.2 today and the issue persists. I encountered it shortly after replacing `pipewire-media-session` with `wireplumber`, but everything else on my computer works as usual so I'm not sure if my problem is caused by that or not. The sound on my computer (main linux partition) stopped working entirely when I tried to switch it back so I don't think I can do that.
Also, on that day, muse hub seemed to have auto-updated and booted into a completely different user interface. It spawned a dialog asking for my permission to run a shell command. I do not remember what command it was, only that I accepted it without a second thought. After I ran into this issue, I attempted to reinstall muse hub and every muse sounds library. When I installed the latest binary from the muse website, it booted into the old interface. I was never able to reproduce the new gui nor the command dialog again. There was no update to muse hub.

I have tried:
- uninstalling musescore
- using the flatpak version instead of the appimage
- musescore>help>revert to factory settings
- removing and reinstalling muse sounds
- manually purging all files associated with musescore
- copying `libMuseSamplerCoreLib.so` from `~/.local/share/MuseSampler/lib/` `~/.var/app/org.musescore.MuseScore/data/MuseSampler/lib/` because the terminal output said musescore couldn't find it in that location

I use a Inspiron 14 7420 laptop with a intel i7-12700H CPU and a RTX 3050 Mobile GPU. The muse sounds libraries "percussion", "brass", and "woodwinds" are installed. Musescore used to work on my machine until recently and it still works when I installed on my windows partition.

**Comment by MarcSabatella** [comment]
FWIW, it works fine on other Linux systems, so it's almost certainly connected to how your audio is configured.  Unfortunately, I'm no expert in that, but I can say, if things on your worked with pipewire-media-session before, presumably it's possible to get it to do so again,  If you need further help, try asking for help on the Support forums on musescore.org, or on a more general Linux support site.

And yes, Muse Hub on Linux has been replaced by Muse Sounds Manager, and no by popular request it no longer uses a service with root permissions, hence the need to manually give permission for installation into system folders.  Yu can redownlaod the Muse Sounds Manager by scrolling down to the bottom of musehub.,com

**Comment by bkunda** [comment]
It seems this issue has already been covered elsewhere (see, for example, https://github.com/musescore/MuseScore/issues/11220). 
Will close this for now, but happy to re-open if it transpires that there is something unique about this particular case. 
Thanks!
