### ISSUE TITLE
Arpeggio indicator misbehaves when applied on multiple voices in a chord

### ISSUE THREAD

**Issue by Jessidhia** [musescore/MuseScore#20691]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

The Arpeggio indicator seems to misbehave when applied on notes that are on separate voices, in particular when notes are moved across staves.

While preparing a demo file to report this I was actually able to find one case where it works completely fine, but it had not occurred to me to input the notes in that particular way, I felt that they belonged as bass notes represented across staves; but this might be due to a theory misunderstanding.

I put this as an Interaction bug, and not an Engraving bug, due to how the arpeggio indicator can be unrepairable depending on the order the voices are assigned to the chord (c.f. measures 4 and 5 in the example file).

Playback is incorrect in all cases, even in the one with correct engraving, but due to https://github.com/musescore/MuseScore/issues/14362.

### Steps to reproduce

1. on a Piano 4/4 grand staff,
2. add a chord with A2 and E3 half-notes, and a C4 dotted quarter-note
    - this requires either the A2+E3 to be in voice 1 and the C4 in voice 2, or vice-versa
3. apply an arpeggio to the chord and extend it to both voices
    - if the C4 was placed in the Treble staff, everything engraves correctly (!)
    - if the C4 was placed in the Bass staff, the arpeggio only engraves correctly if the C4 is specifically in voice 1 *and* it is not moved across staves with the "cross-staff beaming" feature; moving it across causes the engraving to be positioned weird and conflicts with any preexisting Treble clef notation.
    - if the C4 is in Bass staff voice 2, the arpeggio indicator completely collapses and any attempt to fix it by dragging the points causes it to revert to only voice 1 or only voice 2.

### Screenshots/Screen recordings

<img width="966" alt="image" src="https://github.com/musescore/MuseScore/assets/73085/9a9e7257-9362-4eb4-a32b-bc53942918d8">

If I try to put the A and E in voice 3 instead, something incredible happened for a moment — the arpeggio kept growing indefinitely with every edit to the text label, even undo... but upon saving the file it repaired itself.
<img width="958" alt="image" src="https://github.com/musescore/MuseScore/assets/73085/91f598d5-80a5-486b-9b88-aaa4dad189a9">

More importantly, though, using voice 3 here forces an added rest for voice 1 that cannot be removed, only made invisible.

For reference, this is the bar of [the original score](https://youtu.be/R6_5pHQ3VTs) that I was transcribing as an exercise:
<img width="445" alt="image" src="https://github.com/musescore/MuseScore/assets/73085/f11a07c3-0639-4139-a89f-fe1df5001a1a">

### MuseScore Version

OS: macOS 14.2, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Both Windows and macOS

### Additional context

[Arpeggio bug report.mscz.zip](https://github.com/musescore/MuseScore/files/13761990/Arpeggio.bug.report.mscz.zip)

**Comment by Jessidhia** [comment]
<img width="464" alt="image" src="https://github.com/musescore/MuseScore/assets/73085/d09a4a24-8294-47be-88de-bb68a752f039">

Ah, another interesting engraving issue is that the beam/rest in measure 5 did not get auto-adjusted for the voice 2 notes that were moved across to the treble staff, but they can just be manually flipped/moved. This technically also happens in measure 3 but that one is weird in other ways.

**Comment by nmu-nyasan** [comment]
I think this issue should be logged as an "Engraving bug".
@oktophonie
