### ISSUE TITLE
Part rename doesn't mark score as having unsaved changes

### ISSUE THREAD

**Issue by AAAlex-123** [musescore/MuseScore#20698]
### Issue type

Opening/saving issue

### Bug description

Renaming any part doesn't mark the score as dirty/unsaved, as indicated by the asterisk next to the score's name.

This has two effects:
1. The user doesn't press 'save' because the score isn't marked as unsaved.
  2. Closing the score after renaming the part doesn't show the "do you want to save changes before closing" dialog so the user thinks their changes have been saved but in reality they're discarded.

Notes:
1. Manually saving the score (either with Ctrl+S or via File>Save / File>Save As / File>Save A Copy) properly saves the renamed part.
2. Performing any other action which marks the score as dirty/unsaved causes the user to press 'save' or (if they don't press save) triggers the "do you want to save changes before closing" dialog, thereby saving the renamed part.

### Steps to reproduce

1. Open any score
2. Open the 'Parts' dialog
3. Rename any part (notice that this doesn't mark the score as dirty/unsaved)
4. Close the 'Parts' dialog
5. Close the score without performing any other action (this does not trigger the "save before closing" dialog)
6. Reopen the score
7. The renamed part was never saved

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
... and renaming a part seems to be not undoable either. That has a very related technical cause.

**Comment by cbjeukendrup** [comment]
This fix should do: #20702 :)

**Comment by bkunda** [comment]
@DmitryArefiev pls check

**Comment by Jojo-Schmitz** [comment]
Regression vs.3.x at least

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev pls check

Yes, I've logged that sometimes ago  #19023 
Will close mine as duplicate since the PR already linked
