### ISSUE TITLE
Replacement of Instrument doesn't update the Key Signature

### ISSUE THREAD

**Issue by ccaecha** [musescore/MuseScore#20706]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Let's say I have a transposing instrument in the main score, say Alto Saxophone(Eb). I open the part and check that the key is correct. I go back to the main score and change the instrument ("Replace Instrument") to a different transposing instrument of a different key, say Tenor Saxophone(Bb). When I go back to the part, the key is not updated but stays at what it was with my first instrument.

Originally discussed here: https://musescore.org/en/node/358290#comment-1220226

### Steps to reproduce

1. Create a new document with Alto Saxophone. For an example, I pick G Major key (Concert Pitch) for the piece. Since Alto Saxophone is a Eb instrument, a G Major key piece will be written/displayed as E Major.
2. I then open the "Alto Saxophone" part and check that it is showing E Major which is correct.
3. I go back to the main score tab. I open the Instrument tab. I click on the cog button next to Alto Saxophone and then click on the "Replace instrument" button.
4. I select Tenor Saxophone, which is an Bb instrument.
5. Main score is now displaying the score with new key A Major, which is correct.
6. I click on the Part tab, which is now called "Tenor Saxophone".
7. In this part, it is still showing E Major key in the signature, but I expect it to change to A Major.

### MuseScore Version

4.2.0

### Regression

Is fine in 4.0, went wrong in 4.1

### Operating system

Windows 10

**Comment by sammik** [comment]
Additional context
workround: switching "Concert pitch" of and on in part fixes it

**Comment by jfarnsworth7** [comment]
I just updated to the most recent version available:
![image](https://github.com/musescore/MuseScore/assets/104859250/5d12b1c7-6f15-4cd8-8a6c-d0ccfb5f47a4)
And even the workaround specified by https://github.com/sammik doesn't work. Do you have another workaround for this? If not, is it possible to revert to version 4.0 in the meantime?

**Comment by MarcSabatella** [comment]
The workaround works for me.  If you have a score where it does not, please ZIP and attach it.

You wouldn't want to go back to pre-4.2.1 versions over this - way too many far more serious bugs exist in those (with no easy workarounds) that have been fixed meanwhile!
