### ISSUE TITLE
Muse Guitars: Notes are cutt off if followed by rests, and if it's the last note of the score

### ISSUE THREAD

**Issue by cadiz2** [musescore/MuseScore#20703]
### Issue type

Muse Sounds bug

### Bug description

The recent 4.2 update included Muse Guitars Volume 1. The "Acoustic Guitar" sample  has a bug. A guitar note will not sustain for its full duration (e.g. 1/4 note for instance) where there is a rest following the note (and if it's the last note) That is the note regardless of duration will be played staccato.

    

### Steps to reproduce

1. New score for guitar 
2. Enter a few notes, some of which are followed by rests
3. Launch playback
4. Result: Notes followed by rests are cut off, as if staccato had been applied to them (ditto for the last note)

### MuseScore Version

Version 4.2

### Regression

Yes

### Operating system

Windows10

### Additional context
1.Bug report on forum: https://musescore.org/en/node/358280

2.Test file: 
[test_3.zip](https://github.com/musescore/MuseScore/files/13766594/test_3.zip)

**Comment by LupusCaeruleus** [comment]
Here is another similar case when I use some custom time sigs, the last notes of every two bars are cut off.


https://github.com/musescore/MuseScore/assets/70313425/42ddae17-be56-4dc5-a142-a2082be037f8



[Oasis.zip](https://github.com/musescore/MuseScore/files/13766661/Oasis.zip)
(Rename the .zip to .mscz to open)

**Comment by cadiz2** [comment]
I cannot reproduce here. I've kept only the guitar staff (and reduced the tempo) for better hearing. And then, I don't see anything special. 
[1Oasis.zip](https://github.com/musescore/MuseScore/files/13766700/1Oasis.zip)

**Comment by cadiz2** [comment]
Just curious. On my desktop computer, I find that I don't have this problem. Could the version of Muse Sampler be to blame? On the desktop, it's version 0.5.1. And on the laptop (where it doesn't work), it's version 0.4.3?

**Comment by LupusCaeruleus** [comment]
> Just curious. On my desktop computer, I find that I don't have this problem. Could the version of Muse Sampler be to blame? On the desktop, it's version 0.5.1. And on the laptop (where it doesn't work), it's version 0.4.3.?

Maybe it's the case. My MuseSampler version is 0.4.0 (and MuseHub always fails to uninstall and update it).

**Comment by cadiz2** [comment]
I think that's it. I updated Muse Sampler on my laptop, and there are no more problems. Solved. Sorry about the noise.
