### ISSUE TITLE
Crash on closing with trill lines on empty measure

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#20700]
### Issue type

Crash or freeze

### Bug description

Musescore 4.3.0 crashes on exit if file contains trill lines on an empty measure.
It will crash if you put trill line on a whole rest.
Also it will crash if you select empty measure and put a trill line there, but in this case you have to save, reopen file and close it again.
p.s. I have no idea why we have ability to put trills on an empty measure or rest, but since it's possible, it shouldn't cause the crash.
Also this crash happens with a sample score [new score.zip](https://github.com/musescore/MuseScore/files/13756598/new.score.zip) from #20662

### Steps to reproduce

1. Create new score from treble template
2. put a trill line on a whole rest
3. try to close file without saving
4. Crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/99a64f20-eda2-448b-bf20-6b22931ebd8a

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.3.0-233590304, revision: github-musescore-musescore-21ccaca

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 10

### Additional context

This is regression in master. Can't reproduce in 4.2.0 and 4.2.1 nightly

**Comment by cbjeukendrup** [comment]
I reproduced the crash in an AddressSanitizer build, and that suggested that it is related to #20369

**Comment by mercuree** [comment]
Can't reproduce anymore. Maybe fixed by #20369
