### ISSUE TITLE
Musescore 4.2 wouldn't save a file, then wouldn't start again - even after uninstalling and downloading again

### ISSUE THREAD

**Issue by Philocrites** [musescore/MuseScore#20712]
### Issue type

Opening/saving issue

### Bug description

After downloading Musescore 4.2 (using Mac OS 13.6.3) I was able to work on a file for a few hours, saving it a couple of times. Then the app told me it couldn't save the file, so I saved a copy and quit. When I tried doubleclicking the new copy of my file in the Finder, my Mac said Musescore 4 can't be opened. After restarting my laptop, I opened the Musescore Hub, but clicking Musescore there generated the same error. I could not redownload and reinstall the software at this point because my Mac said Musescore Hub was still running. After restarting again, I opened Musescore Hub and uninstalled the software and then downloaded and installed it again. After reinstalling, clicking Musescore generated the same error. 

I then used Internet Archive to download Musescore 4.1, thinking I might be able to go back to an earlier version of my score. That version wouldn't open either. I cannot open any of my Musescore files now.

### Steps to reproduce

1. In the finder, doubleclick a Musescore file. Or, in Muse Hub, click Musescore.
2. The MacOS says Musescore 4 cannot be opened.
3. Restart the computer.
4. Open Muse Hub and follow the instructions for uninstalling Muse Hub.
5. Restart the computer.
6. Download Musescore 4.2 and install.
7. Same problem!

### Screenshots/Screen recordings

I don't know how to make a screen recording.

### MuseScore Version

Musescore 4.2.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS 13.6.3

### Additional context

n/a

**Comment by MarcSabatella** [comment]
Sounds like you'll need to do a factory reset of the program - something must be off in a preference setting somewhere.  See https://musescore.org/en/handbook/4/revert-factory-settings.  And if you have further trouble, please ask for help in the Support forum on musescore.org.  if it turns out there is a bug and steps to reproduce it are found, then you can come back here and describe it.
