### ISSUE TITLE
MuseScore 4.2 crashes when appending frames on scores with opened parts.

### ISSUE THREAD

**Issue by matzehecht** [musescore/MuseScore#20716]
### Issue type

Crash or freeze

### Bug description

As stated in the title my MuseScore crashes if I try to append a frame. This happens for all types of frames (text frame, vertical frame, and horizontal frame). It's interesting that this only happens when I am appending frame but not when I insert a frame.
I reproduced this in multiple scores. All of them had a master score and multiple parts (I added multiple instruments and opened their parts).

Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: [eb8d33c](https://github.com/musescore/musescore/commit/eb8d33c)

Log lines occured in the respective time frame:

```bash
2023-12-25T15:23:16.407 | WARN  | main_thread     | Qt              | QQmlComponent: Created graphical object was not placed in the graphics scene.
2023-12-25T15:23:16.762 | WARN  | main_thread     | Qt              | QQmlComponent: Created graphical object was not placed in the graphics scene.
2023-12-25T15:23:19.666 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: append-textframe
```

Also reported in the MuseScore Forum: https://musescore.org/en/node/358292

### Steps to reproduce

1. Open MuseScore
2. Create a score with 1 instrument
3. Click on "Add" > "Frames" > "Append text frame" => Everything works fine
4. Delete the frame again and add a second instrument to the score
5. Click on "Add" > "Frames" > "Append text frame" => Everything works fine
6. Delete the frame again
7. Click on "Parts"
8. Click on "Open All" (or select one and click on "Open Selected")
9. Click on "Add" > "Frames" > "Append text frame"
10. MuseScore crashes

**Short steps:**

1. Open score 
2. Open parts
3. In score, Append any frame (Add > Frames > Append frame)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/38589070/049e363d-514e-4fc7-8fa7-c142a2fdfdb2

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in **MuseScore 4.1.1**

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
Another report in https://musescore.org/en/node/358416
