### ISSUE TITLE
Adding an interval to a selection should keep selection on all added notes

### ISSUE THREAD

**Issue by ComposingPlanarian** [musescore/MuseScore#20720]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

see the screen recording for a better idea of the problem

### Steps to reproduce

1. enter note-input mode, make a few notes in tandem
2. select the measure
3. use alt+3 to add a third to all
4. use alt+3 to add another third to all...except it only did for the last note. The expected behavior is that it does it to all notes.
5. use the up or down arrow key to make the new top notes sharp or flat. It will only do for the last one.
6. if I want to add an articulation like a staccato, it will only apply to the last one

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/116992111/64a092c0-5375-4fc8-ac59-e8b1a4df6cd9

### MuseScore Version

4.2.0

### Regression

I don't know

### Operating system

Windows 10

**Comment by ComposingPlanarian** [comment]
The video doesn't seem to work so I'll attach another recording here:

https://github.com/musescore/MuseScore/assets/116992111/6abaaeeb-f5b4-43db-9f42-9dd6521fdc40

**Comment by XiaoMigros** [comment]
@bkunda what exactly needs designing here? I'd happily take this off your hands..

**Comment by bkunda** [comment]
> @bkunda what exactly needs designing here? I'd happily take this off your hands..
> 
> To me the expected behavior would be a resulting list selection with the newly added notes, allowing for easy manipulation of accidentals, articulation & more

Yes now that I look at it again, it seems like the expected behaviour should be pretty clear.
IF a list/range selection is made, then it should persist – and survive any changes to note length, etc. – until the user clears the selection.
