### ISSUE TITLE
Musescore crashes on drum note input/ clicking pencil icon or hitting N

### ISSUE THREAD

**Issue by Nachtzug1** [musescore/MuseScore#20725]
### Issue type

Crash or freeze

### Bug description

As soon as I select N or click the pencil icon, MS chrashes. This happens only with unpitched percussion as a solo score or on a score with mutliple instruments.
I have re-installed MuseHub and MS multiple times, deleted all MuseSounds etc. updated to the latest version...
It only happens with unpitched percussion note input. (which is particularly frustrating, as I use MS almost exclusively for drum notation). This used to work in MS3 and the nightly builds of MS4 

### Steps to reproduce

To replicate an example:

 1)   create a piano score, try note input.
 2)  add instrument: unpitched percussion (doesn't matter which one, snare drum, bass drum, mixed percussion...)
 3)   try note input
 4)   MS chraches

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/121099814/d844cdc2-57e4-4971-8493-59d99895cfdf

### MuseScore Version

4.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Win 10

**Comment by MarcSabatella** [comment]
I can't reproduce any such problem.  If you are seeing this in one of your scores, please ZIP and attach that specific score (if it happens with all scores you've tried so far, simply pick any one of them, after verifying that it definitely crashes on that specific score).

You mention having reinstalled, but did you try Help / Revert to factory settings?  That's more likely to fix configuration problems than reinstalling.

Also, it looks like you are using a translation of the interface; it's possible the bug somehow relates to one of the translated strings for the names of the notes in the drumset.  See if it fixes itself if you switch to English (US) in Edit / Preferences / General.

**Comment by Nachtzug1** [comment]
@MarcSabatella you, Sir, are the best! I don't know what configuration might have caused the problem, since I haven't changed anything except the language, but reverting to factory settings did the trick! Now it does work in German, also.
Thank you ever so much.
