### ISSUE TITLE
System breaks and page breaks are only added to the score when the mouse cursor is on top a staff, as opposed to between staves

### ISSUE THREAD

**Issue by gosh-darn** [musescore/MuseScore#20731]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When adding layout elements such as system breaks and page breaks, I would expect to be able to place them anywhere within a measure. However, the software only allows me to add these elements when my cursor is located on top of a staff. This means that despite having the colored box present to indicate that a measure is targeted, letting go of the left mouse button when the cursor is located in the space between staves results in no element being added.

An additional problem is that of the colored box itself. I would expect its targeting to update whenever my cursor is located within a measure. The shape of the box implies this should be possible. However, it only updates its targeting whenever the cursor is on top of a staff. Once again this means that moving the cursor to the space between staves will not update the targeting.

The result of this behaviour is that the act of adding layout elements is frustrating, even for a long time user of the software.

EDIT: After posting the issue, I've noticed that the targeting also fails whenever the cursor is on top of a notehead or rest. This is not included in the screenrecording, but should be considered as part of the issue.

### Steps to reproduce

1. launch musescore notation software
2. create a new score with the grand staff template
3. open the layout palette
4. drag system break element to space between staves
5. release left mouse button

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/26469320/5794ad16-d77a-45fb-bda1-91eeea7287c0

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-233610505, revision: github-musescore-musescore-a84a215

### Regression

I don't know

### Operating system

Windows 11 Home 22H2

**Comment by MarcSabatella** [comment]
I could certainly imagine the drop zone being extended, but for the record - drag & drop is never the recommended way to add palette elements.  Instead, simply click the palette item to apply it to the selected measure or other elements in your score.  And for systems breaks in particular, simply pressing Enter does it even more quickly (Ctrl+Enter for page breaks).

**Comment by gosh-darn** [comment]
Thanks, Marc! The shortcut you mentioned seems like a better way to do it.

**Comment by bkunda** [comment]
We actually have a design in the can already to improve the way palette elements get dragged onto the score. I'd expect a fix for this in one of the forthcoming releases.
