### ISSUE TITLE
Crossstaff ties create a small unwanted tie elsewhere on the page or point in the wrong direction

### ISSUE THREAD

**Issue by MRoth1910** [musescore/MuseScore#20747]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

I am working on scores for psalmody accompanied by the organ, so there are two staves. It is not uncommon to change the voice with which one plays a note, between the alto and tenor for example, at the mediant of a psalm (the asterisk in the liturgical text). In my case, this tie is at the end of the staff.

Normally, before 4.2, there would be a little tie at the end of the line and at the beginning of the next, and the organist would just have to deal with this note at the end of the line moving to the other voice. Now, if I change the score (it seems to be anything: adjusting barlines, lyrics, notes…), the tie shoots up or down to the other staff, which indicates more clearly that the note is in a different voice, but then there is a little tiny tie at the bottom of the bass staff, which looks ugly, and I don't want that.

Sometimes I have a related problem: changing the staff of the note to enter the tie and only changing the note back to the correct staff leads the tie to point elsewhere, e.g. a note moved from the bass staff to the treble staff and tied, then moved back will have a tie that points downwards.

### Steps to reproduce

1. The score needs to have 2 staffs, treble and bass, such as a piano score.
2. At some point in the music, enter the same pitch (such as C4) in each staff, on different beats.
3. then change the staff of one note (I always do the first note…).
4. Tie the two notes.
5. Move a note back to the correct staff.
6. Either the tie points downwards, or there is an extra tie element floating around somewhere on the page.

### Screenshots/Screen recordings

<img width="987" alt="Screenshot 2023-12-28 at 12 12 13" src="https://github.com/musescore/MuseScore/assets/68782573/cc762060-c2ad-4e7d-90cf-4c902d54446b">
<img width="987" alt="Screenshot 2023-12-28 at 12 29 09" src="https://github.com/musescore/MuseScore/assets/68782573/c4f2892c-ade2-48da-bd51-28a6a1542eb1">

### MuseScore Version

 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Sonoma 14.1.1

### Additional context

On page 4 (nb I did change the words before getting around to submitting the issue, but the problem is still there.)

And on page 5.

[Psaumes_aux_vêpres_Circoncision.mscz.zip](https://github.com/musescore/MuseScore/files/13789024/Psaumes_aux_vepres_Circoncision.mscz.zip)

**Comment by Jojo-Schmitz** [comment]
Stems from https://musescore.org/en/node/358423
