### ISSUE TITLE
Coda at multi measure rest of length 1 appears twice

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#20742]
### Issue type

Engraving bug (incorrect score rendering)

### Steps to reproduce

Have a score, with a single empty measures (like the one from https://musescore.org/en/node/358375#comment-1220591)
apply a coda to it
set multimeasure rests' min number of empty measures to 1 (Format > Style > Rests)
enable multi measure rests:

![image](https://github.com/musescore/MuseScore/assets/1786669/41c2db09-eeff-443c-9759-0494f02dc1b9)

Same issue with Coda Variation, Segno, Segno Variation, To Coda, Fine... basically all jump markers

### MuseScore Version

4.2.0, 3.6.2

### Regression

No.

### Operating system

Windows 11

**Comment by sammik** [comment]
> Same issue with Coda Variation, Segno, Segno Variation, To Coda, Fine... basically all jump markers

except Da Capo and Dal Segno and its variants

**Comment by Jojo-Schmitz** [comment]
These are jump instructions, not markers
