### ISSUE TITLE
Pitch of Instrument

### ISSUE THREAD

**Issue by MarkMoke** [musescore/MuseScore#20749]
I have started a Project using Musescore 4.
I have selected a Baritone Treble Clef.
When I add a note, for example, Lower ‘F’ on the Stave, the sound produced is for the Higher ‘F’.
The same applies to the Euphonium that I have selected.
NOTE: On a previous Project this was not an issue.

Any help much appreciated

MarkMoke

**Comment by MarcSabatella** [comment]
Please ZIP and attach the score you are having trouble with and say which is note is not playing correctly for you.

When I create a new score add a "baritone horn (treble clef)", it works as expected, all notes sounding a major ninth lower than written.

**Comment by MarkMoke** [comment]
Hello Marc.

 

  I have been playing around with it some more.

 

If I select the CONCERT PITCH button on the bottom of the screen both the Baritone and Euphonium revert to BASS CLEF

 

If I manually select a Clef from the Clef Palette…that’s when the pitch is wrong.

 

So, If I do the Arrangement with the CONCERT PITCH activated….and add notes in the BASS CLEF……

…when the Project is finished and I TURN OFF CONCERT PITCH…it should be Ok.

 

Thanks for your help

 

Mark

**Comment by bkunda** [comment]
@MarkMoke it sounds like your problem here is resolved?
I'll close it for now, but happy to re-open if it appears there is an actual bug.
