### ISSUE TITLE
OT Sine player crashes Musescore 4.2.1

### ISSUE THREAD

**Issue by Lightwreather** [musescore/MuseScore#20746]
### Issue type

VST bug

### Bug description

Switching an instrument to Orchestral Tool's Sine Player, loading up the instrument, and then closing the window causes Musescore to crash. I have tested this with a full symphony template and a fresh file, and it happened both times. 
Strangely enough this doesn't seem to occur with other VSTs. With no instrument loaded in sine player, it occasionally closes fine, but at other times exhibits the same behaviour as with an instance with a loaded instrument

### Steps to reproduce

1. Open up a Musescore file,
2. Switch one of the instrument to a VST Sine player instance
3. Load an instrument in sine player, this step is occasionally not neccessary
4. close sine player window

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/51205130/1155a793-79d0-4a8f-98ac-67eee18e8a19

### MuseScore Version

4.2.0.233521125

### Regression

I don't know

### Operating system

MacOS Ventura 13.6

### Additional context

Log:
[sinecrash.zip](https://github.com/musescore/MuseScore/files/13788858/sinecrash.zip)
Sine player was downloaded from the Orchestral Tool's website [link](https://www.orchestraltools.com/store/get-sine)

System:
CPU: Apple M1
Memory: 8GB
GPU: Apple M1
Drive type: SSD

**Comment by J-from-Nucleon** [comment]
Note: Updated to MS 4.2.1, issue still persists

**Comment by J-from-Nucleon** [comment]
Bump
