### ISSUE TITLE
Editing notes in repeated section after arpeggio kills playback.

### ISSUE THREAD

**Issue by GolldenFalcon** [musescore/MuseScore#20752]
### Issue type

General playback bug

### Bug description

Updated: See @mercuree 's video

Editing notes in repeated section after arpeggio kills playback.

Upon editing a note in any fashion (moving a note up or down in pitch, adding a glissando, etc.) underneath a volta, all notes following the edited one are muted, however do not show they are muted in the properties window. The notes do not play on playback, nor do they display any volume when opening the mixer. This issue is temporarily fixed by restarting Musescore. Also can be temporarily fixed by un-checking and re-checking the "Play" checkbox in the properties window of the note.
[Volta Bug.zip](https://github.com/musescore/MuseScore/files/13791512/Volta.Bug.zip)

### Steps to reproduce

1. Select a note
2. Edit it in some fashion; Raise the pitch/lower the pitch/add articulations that change playback like glissandos or slides
3. Start playback

### Screenshots/Screen recordings

https://youtu.be/O4Nyv4MMCp0

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 10, 64 bit

**Comment by bkunda** [comment]
@DmitryArefiev @zacjansheski pls check

**Comment by MarcSabatella** [comment]
FWIW, I was able to reproduce this although the specific symptoms seemed to vary - sometimes it was other notes within the volta that failed to play, sometimes it was notes at the beginning of the following repeat, sometimes it was notes in the next volta.  But I could only reproduce with this score - I didn't succeed in reproducing the problem from scratch.

**Comment by silvncr** [comment]
Would like to add that the issue is present on the 4.2.1 nightly portable build.

```
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240250505, revision: github-musescore-musescore-d757433
```

I haven't experimented much, but it mostly happens around trills and grace notes.

**Comment by zacjansheski** [comment]
Just for visibility/reproduction purposes:
Go to measure 32, delete the arpeggio, playback stops working on that measure

https://github.com/musescore/MuseScore/assets/69917893/a03d28cb-d632-42c1-b8eb-e7dc17279f2b

**Comment by zacjansheski** [comment]
I haven't been able to reproduce outside of this score, but definitely still happens in master.

Would like to find a more minimal example.

@RomanPudashkin  Reminds me a bit of https://github.com/musescore/MuseScore/issues/19264

**Comment by mercuree** [comment]
[arpeggio_playback_issue.zip](https://github.com/musescore/MuseScore/files/14624967/arpeggio_playback_issue.zip)

https://github.com/musescore/MuseScore/assets/919446/1e25f079-9dab-4387-86b5-9f57b63dcfb9

**Comment by zacjansheski** [comment]
Looks like this is a regression between 4.1.1 and 4.2.0
