### ISSUE TITLE
Why does rit. not change the speed

### ISSUE THREAD

**Issue by matt-dong-123** [musescore/MuseScore#20755]
### Issue type

General playback bug

### Bug description

I tried accel., and it worked, but when I tried rit., it just won't work for some reason.

### Steps to reproduce

1. Drag rit. from the palettes menu
2. Playback

### MuseScore Version

4.2.0.233521125

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14

**Comment by bkunda** [comment]
@DmitryArefiev @zacjansheski pls check
