### ISSUE TITLE
Measure number not refreshed after excluding from count

### ISSUE THREAD

**Issue by rainermarwan** [musescore/MuseScore#20768]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Measure number not refreshed after "exclude from measure count" in Measure Properties under certain unknown circumstances

### Steps to reproduce

1. Create Project as listed in appended PDF (Musterpartitur2.pdf)
2. measure number at beginning on line 2 shows 10.
3. select measure 5 and enter measure properties
4. choose/check "Exclude from measure count"
5. press "Apply"
6. look at measure number at line 2. 
7. This should change to 9 but does not (still 10).
8. Advance to measure 6, 7 with "exclude ...." and Apply
9. Measure number in line 2 still unchaned (should be 7).
10. (It is also unchanged after pressing OK to close the Properties at this point.)
11. Advance to measure 8 click "exclude from measure count" and Apply
12. Measure count in line 2 changed to "6"!!!!!!!
13. Advance to measure 9 click "exclude from measure count" and Apply
14. Measure count in line 2 changed to "5".
15. Vice versa it happens the opposit scenario
16. uncheck at measure 9 and apply changes to 6
17. uncheck at measure 8 and apply changes to 7
18. uncheck at measuer 7 and apply still shows 7
19. uncheck at measure 6, 5 and apply till shows 7  at nex line
20. Close properties still shows 7
21. press "M" two times refreshes measure number to 10

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 11, PC Intel i9 (13900), 32m storage, disk 2tb ssd Grafik Nvidia rtx3060 12GB

### Additional context

[Musterpartitur2.pdf](https://github.com/musescore/MuseScore/files/13798825/Musterpartitur2.pdf)

**Comment by rainermarwan** [comment]
Problem does not occur 4.1.0

**Comment by sammik** [comment]
I think, it may be related to #20141

**Comment by Jojo-Schmitz** [comment]
Possible, if so, then likely https://github.com/musescore/MuseScore/pull/20141/files#diff-bed316b00834b5800585ebe9c9ad5bc3cfd3bd26a17025ffdc3e4a11f54c2ab0L448-R451

**Comment by rainermarwan** [comment]
Additional testing shows:
The problem also occours when using the section break from the layout-palette. The measurenumbers are not refreshed starting at the second line of the new section. Pressing "M" twice (Multimeasure on/off) is a temporary solution.
