### ISSUE TITLE
Opening and closing mixer while note input mode is enabled causes strange visual bug in score view

### ISSUE THREAD

**Issue by DavidMcCaulley** [musescore/MuseScore#20761]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

When toggling the mixer with note input mode enabled _and_ the mouse is in the score viewport, very strange visual artifacts can appear (see screen recording below). 
 
In short, this seems to happen when all of the following are all true at the same time:

- The mouse cursor is within the score viewport
- Note input is enabled
- The mixer is then toggled either on or off

The behavior goes away when either

- Note input is toggled off
- The mixer is toggled off with the mouse outside of score view

I noticed this especially when using a keyboard shortcut to toggle the mixer (since the mouse would most likely be in the score viewport anyway). But this also works with clicking the mixer button and quickly moving the mouse to the score viewport before the mixer opens (this only happens in a larger score where the mixer takes a half second to open).

### Steps to reproduce

1. Enter note input mode in any score
2. Make sure mouse cursor is within score viewport
3. Toggle mixer on and off one or two times _with mouse cursor still in score view_
4. See result

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/31858876/04918dd6-2034-4064-adbf-81a3fd575a50

**Note that only the keyboard shortcut for the mixer is being pressed when the visual bug happens**

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: macOS 13.5, Arch.: x86_64

**Comment by oktophonie** [comment]
Can also reproduce in Windows. Only happens when the mixer is docked to the main window, not if it's free-floating.

**Comment by DmitryArefiev** [comment]
Fixed in #20909
