### ISSUE TITLE
Sudden abort of pdf export

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#20780]
### Issue type

Crash or freeze

### ### 
[ysaye sonatas.zip](https://github.com/musescore/MuseScore/files/13802322/ysaye.sonatas.zip)

### Screenshots/Screen recordings

When exporting pdf from this score, Musescore crashes after a second.

### MuseScore Version

4.2

### Regression

Yes, this worked in MuseScore 4.1.1

### Operating system

Windows 11

**Comment by mathesoncalum** [comment]
For anyone looking to test this (and the above PRs) - the problem exists solely in Sonata 2. You can use [this file](https://github.com/musescore/MuseScore/files/13829890/Sonata2.zip) to repro without the long loading times of the entire score.

**Comment by Jojo-Schmitz** [comment]
That score crashes on load already for me ?!?

**Comment by mathesoncalum** [comment]
@Jojo-Schmitz Yeah the problem definitely isn't limited to PDF exporting - it loads just fine on my end but certain basic interactions will cause a crash.
