### ISSUE TITLE
Drumset preview pane not showing correct stem direction

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#20785]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The drumset preview window is not showing the stems in the selected direction, as set in the drumset settings.
All stems are shown in the Up direction.
Also when Editting the drumset, the preview of the note in that dialog is not showing the selected stem direction.

### Steps to reproduce

1. Start a New Score
2. Select the Drumset as instrument
3. Start Note Entry (this will show the Drumset window)
4. Check the content of the window:
![drumset-view](https://github.com/musescore/MuseScore/assets/13550012/7f5a5467-818b-4347-a6bc-fb28454b09f5)

6. Click Edit drumset
7. Select the Bass Drum 1
![drumset-view-bassdrum](https://github.com/musescore/MuseScore/assets/13550012/acaedbfe-a453-4b1e-bdd0-104fd3f70742)

### MuseScore Version

4.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
Also a regression vs 4.1.1 - it worked correctly there.
