### ISSUE TITLE
Repeat text should not require a range selection to apply

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#20793]
### Issue type

Accessibility issue (e.g. for keyboard-only or screen reader users)

### Bug description

Because repeats are added to measures rather than individual notes, drag and drop highlights the full measure, and a measure (or at least a range) is also required to be selected when adding the repeat by clicking in the palette.  But, there is no logical reason I can think of why there *must* be a range selected to apply the repeat text.  It makes the process especially awkward for blind users navigating by keyboard and not understanding why repeat text won't seem to apply.

### Steps to reproduce

1. click a note
2. click the "DS al Coda" in the palette

Result: nothing happens

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240010504, revision: github-musescore-musescore-b955511

### Regression

No.

### Operating system

Debian 11

### Additional context

I have a sense we might have originally required a measure to be selected in order to discorage people from thinking they  could apply these markings mid-measure.  But, it's a UX issue worse than the problem it was trying to solve and especially for accessibility.

**Comment by oMrSmith** [comment]
Being able to select a barline and apply a "D.S." to it, would make more sense to me
than being able to select the first note of a bar and then have the "D.S." be added at the end of the bar.

**Comment by Jojo-Schmitz** [comment]
Esp. as this does work for repeat barlines
