### ISSUE TITLE
Persistent crash when closing MuseScore 4.3.0 commit 602a95d756 on macOS Sonoma

### ISSUE THREAD

**Issue by lvinken** [musescore/MuseScore#20800]
### Issue type

Crash or freeze

### Bug description

Self-built MuseScore commit 602a95d756 crashes on every quit.
Does not happen with 4.20 (commit eb8d33c7af7).

### Steps to reproduce

Start MuseScore
Quit

### MuseScore Version

OS: macOS 14.2, Arch.: arm64, MuseScore version (64-bit): 4.3.0-, revision: github-musescore-musescore-

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Sonoma 14.2.1

### Additional context

Error message on console:
mscore(24716,0x1d8cbd000) malloc: *** error for object 0x1212ca878: pointer being freed was not allocated

Relevant part of problem report:
Process:               mscore [24633]
Path:                  /Users/USER/*/mscore.app/Contents/MacOS/mscore
Identifier:            org.musescore.MuseScore
Version:               4.3.0 ()
Code Type:             ARM-64 (Native)
Parent Process:        zsh [24579]
Responsible:           Terminal [553]
User ID:               502

Date/Time:             2024-01-02 17:05:07.6417 +0100
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12
Anonymous UUID:        B06756F3-51D2-ADC3-5A52-0A5E18F76058

Sleep/Wake UUID:       73579285-C0C5-4CD6-AC51-C2F612142F40

Time Awake Since Boot: 20000 seconds
Time Since Wake:       3911 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   mscore [24633]

Application Specific Information:
abort() called

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1824a60dc __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1824ddcc0 pthread_kill + 288
2   libsystem_c.dylib             	       0x1823e9a40 abort + 180
3   libsystem_malloc.dylib        	       0x182300b08 malloc_vreport + 908
4   libsystem_malloc.dylib        	       0x1823043f4 malloc_report + 64
5   libsystem_malloc.dylib        	       0x182318ebc find_zone_and_free + 308
6   mscore                        	       0x104a6fc7c mu::engraving::EngravingObject::~EngravingObject() + 356 (engravingobject.cpp:138)
7   mscore                        	       0x104d8a0f8 mu::engraving::compat::DummyElement::~DummyElement() + 64 (dummyelement.cpp:49)
8   mscore                        	       0x104d8a228 mu::engraving::compat::DummyElement::~DummyElement() + 4 (dummyelement.cpp:47) [inlined]
9   mscore                        	       0x104d8a228 mu::engraving::compat::DummyElement::~DummyElement() + 12 (dummyelement.cpp:47)
10  mscore                        	       0x104b9bac8 mu::engraving::RootItem::~RootItem() + 36 (rootitem.cpp:42) [inlined]
11  mscore                        	       0x104b9bac8 mu::engraving::RootItem::~RootItem() + 36 (rootitem.cpp:39) [inlined]
12  mscore                        	       0x104b9bac8 mu::engraving::RootItem::~RootItem() + 52 (rootitem.cpp:39)
13  mscore                        	       0x104b9eea4 mu::engraving::Score::~Score() + 540 (score.cpp:265)
14  mscore                        	       0x104b1e150 mu::engraving::MasterScore::~MasterScore() + 4 (masterscore.cpp:103) [inlined]
15  mscore                        	       0x104b1e150 mu::engraving::MasterScore::~MasterScore() + 12 (masterscore.cpp:103)
16  mscore                        	       0x10497a83c mu::engraving::EngravingModule::onDestroy() + 40 (engravingmodule.cpp:224)
17  mscore                        	       0x1048119c0 mu::app::App::run(int, char**) + 7024 (app.cpp:371)
18  mscore                        	       0x1047ffc70 main + 2164 (main.cpp:372)
19  dyld                          	       0x18215d0e0 start + 2360

**Comment by cbjeukendrup** [comment]
Probably would be fixed by https://github.com/musescore/MuseScore/pull/20369

**Comment by RobFog** [comment]
> Probably would be fixed by #20369

#20369 was merged. @lvinken can you confirm it fixes this crash?

**Comment by lvinken** [comment]
Tested commit 75fe9addbfd, no crashes in a dozen MuseScore runs. My previous build crashed on every close, so the crash indeed seems fixed (I assume it is, but the conclusion may not yet be statistically valid).

**Comment by cbjeukendrup** [comment]
Combined with the stack trace you posted, that does seem enough reason to close this issue :) 
We can always reopen it if necessary.
