### ISSUE TITLE
Cross staff beam + Grace notes crashes

### ISSUE THREAD

**Issue by RhinoHaggis** [musescore/MuseScore#20808]
### Issue type

Crash or freeze

### Bug description

If a group of notes have a cross staff beam,
  1. adding grace notes crashes or
  2. If Grace notes can be added, subsequent adjustment of the cross-staff beam crashes.

Specifically, add a **pair** of  sixteenth-note grace notes to one of the main notes.  Dragging the cross staff beam crashes the app.

### Steps to reproduce

1. Create a group of beamed notes
2. Move some notes cross-staff
3. Add two 16th-note Grace notes to one of notes
4. Adjust the cross-staff beam
5. If no crash, move the beam to cross its own center line (flip it)

Steps 2&3 interchangeable. Crash as early as creation of Grace Notes (if beam is already cross staff). Crash is certain by step 5.

Verified several times on a new project with no other elements. Scope is probably wider. I was too shy to repeatedly crash the app hunting for scope.

### MuseScore Version

4.2.0.233521125  Rev. eb8d33c

### Regression

I don't know

### Operating system

MacOS Monterey

**Comment by RhinoHaggis** [comment]
Ok. It’s not cross-staff specific. I can reproduce as long as the notes are all on bar lines between the staffs.  Dragging the beam over it’s center line crashes.
I searched for cross-staff issues before posting. I will search again and remove this if it’s a duplicate.

**Comment by oktophonie** [comment]
Please attach a file (.zip it) that sets up the problem. It's not clear if the grace notes need to be attached to a cross-stave note, for example.

I've not been able to reproduce this but I also don't fully understand the reproduction steps. That said I did notice this interesting corruption when dragging this beam from its default position:
![image](https://github.com/musescore/MuseScore/assets/20604032/5c88c24b-0d7c-4b5f-b5d5-956fa589a0a8)
![image](https://github.com/musescore/MuseScore/assets/20604032/4f6f6770-f023-4248-bbff-4c7e8e9ca276)
(no idea if related)

**Comment by zacjansheski** [comment]
I got a crash after a few tries, I have to make a range selection including the grace and primary note to reproduce, is that the same bug as you described?

https://github.com/musescore/MuseScore/assets/69917893/65f28c17-1476-4974-84fa-8b8b574c1819

**Comment by zacjansheski** [comment]
Crash report

[xStaveGraceCrash.zip](https://github.com/musescore/MuseScore/files/13836010/xStaveGraceCrash.zip)

**Comment by zacjansheski** [comment]
It looks like a regression, I can't reproduce in 4.1.1

**Comment by RhinoHaggis** [comment]
@zacjansheski it might be the same.  Here is a file showing my original setup.
[beam drag crash report.mscz.zip](https://github.com/musescore/MuseScore/files/13837584/beam.drag.crash.report.mscz.zip)

And dragging the beam upward to cross to up-beams:

https://github.com/musescore/MuseScore/assets/155490832/0bd3eb32-f636-4dd4-9453-8f97fc6e76ea

**Comment by RhinoHaggis** [comment]
I originally assumed it was cross-staff related, since I do edits like this all the time.  However... 
[beam drag crash report v2.mscz.zip](https://github.com/musescore/MuseScore/files/13837614/beam.drag.crash.report.v2.mscz.zip)
I was wrong
https://github.com/musescore/MuseScore/assets/155490832/9a62ac5c-951f-47cd-a182-0bd4191072e1

**Comment by RhinoHaggis** [comment]
Ignoring the grace notes for a moment, if the three main notes are not on ledger lines, there is no crash.
Musescore also crashed when I tried positioning the beams FIRST and then added the grace notes.  On addition of the second grace note, crash.

Even if my files crash for you, too... after watching your video, the exact scope of the bug seems unclear.
