### ISSUE TITLE
MuseScore 4.2 Crashes when closing everytime

### ISSUE THREAD

**Issue by dannsh13** [musescore/MuseScore#20809]
### Issue type

Crash or freeze

### Bug description

Here is the beginning of the dump
Translated Report (Full Report Below)
-------------------------------------

Process:               mscore [12041]
Path:                  /Applications/MuseScore 4.app/Contents/MacOS/mscore
Identifier:            org.musescore.MuseScore
Version:               4.2.0 (233521125)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2024-01-02 17:47:47.4710 -0500
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12
Anonymous UUID:        4342D85A-A7CA-78C6-962C-7CB84FEE62C6

Sleep/Wake UUID:       F646A821-86F1-49F7-9B76-5E5012E25FF4

Time Awake Since Boot: 89000 seconds
Time Since Wake:       3901 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x13DD86C44)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000000c
Exception Codes:       0x0000000000000001, 0x000000000000000c

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [12041]

VM Region Info: 0xc is not in any region.  Bytes before following region: 140722957418484
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      mapped file              7ffc9de38000-7ffcc6850000 [650.1M] r-x/r-x SM=COW  ...t_id=3f4f7093

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x13DD86C44)

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libqtlabsplatformplugin.dylib 	       0x13dd86c44 0x13dd71000 + 89156
1   libqtlabsplatformplugin.dylib 	       0x13dd86bc4 0x13dd71000 + 89028
2   libqtlabsplatformplugin.dylib 	       0x13dd854de 0x13dd71000 + 83166
3   libqtlabsplatformplugin.dylib 	       0x13dd7f016 0x13dd71000 + 57366
4   QtCore                        	       0x11a11515f QObjectPrivate::deleteChildren() + 287
5   QtCore                        	       0x11a114ed3 QObject::~QObject() + 2003
6   libqtlabsplatformplugin.dylib 	       0x13dd7f316 0x13dd71000 + 58134
7   QtCore                        	       0x11a11515f QObjectPrivate::deleteChildren() + 287
8   QtCore                        	       0x11a114ed3 QObject::~QObject() + 2003
9   QtQuick                       	       0x115075fce QQuickItem::~QQuickItem() + 862
10  QtQuick                       	       0x115208766 0x114f62000 + 2778982
11  QtCore                        	       0x11a11515f QObjectPrivate::deleteChildren() + 287
12  QtCore                        	       0x11a114ed3 QObject::~QObject() + 2003
13  QtGui                         	       0x11905d1c4 QWindow::~QWindow() + 100
14  QtQuick                       	       0x11509f22f QQuickWindow::~QQuickWindow() + 1087
15  libqtquicktemplates2plugin.dylib	       0x13daf1876 0x13dac2000 + 194678
16  QtQml                         	       0x115c71aa9 QQmlApplicationEngine::~QQmlApplicationEngine() + 201
17  mscore                        	       0x105d602e6 mu::ui::UiEngine::quit() + 38
18  mscore                        	       0x104c506e4 mu::app::App::run(int, char**) + 6548
19  mscore                        	       0x104c3d2a5 main + 2325
20  dyld                          	       0x20842e386 start + 1942

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffe34294 0x7ff7ffe30000 + 17044

Thread 2:: caulk.messenger.shared:17
0   ???                           	    0x7ff898a4ea78 ???
1   libsystem_kernel.dylib        	    0x7ff80848f9aa semaphore_wait_trap + 10
2   caulk                         	    0x7ff813063c7e caulk::semaphore::timed_wait(double) + 150
3   caulk                         	    0x7ff813063b98 caulk::concurrent::details::worker_thread::run() + 30
4   caulk                         	    0x7ff8130638bc void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
5   libsystem_pthread.dylib       	    0x7ff8084cf202 _pthread_start + 99
6   libsystem_pthread.dylib       	    0x7ff8084cabab thread_start + 15

Thread 3:: caulk.messenger.shared:high
0   ???                           	    0x7ff898a4ea78 ???
1   libsystem_kernel.dylib        	    0x7ff80848f9aa semaphore_wait_trap + 10
2   caulk                         	    0x7ff813063c7e caulk::semaphore::timed_wait(double) + 150
3   caulk                         	    0x7ff813063b98 caulk::concurrent::details::worker_thread::run() + 30
4   caulk                         	    0x7ff8130638bc void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
5   libsystem_pthread.dylib       	    0x7ff8084cf202 _pthread_start + 99
6   libsystem_pthread.dylib       	    0x7ff8084cabab thread_start + 15

Thread 4:: com.apple.CFSocket.private
0   ???                           	    0x7ff898a4ea78 ???
1   libsystem_kernel.dylib        	    0x7ff80849891e __select + 10
2   CoreFoundation                	    0x7ff8085d346f __CFSocketManager + 637
3   libsystem_pthread.dylib       	    0x7ff8084cf202 _pthread_start + 99
4   libsystem_pthread.dylib       	    0x7ff8084cabab thread_start + 15

Thread 5:: QThread
0   ???                           	    0x7ff898a4ea78 ???
1   libsystem_kernel.dylib        	    0x7ff80849684a poll + 10
2   QtCore                        	       0x11a14b24e qt_safe_poll(pollfd*, unsigned int, timespec const*) + 94
3   QtCore                        	       0x11a14cad8 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 792
4   QtCore                        	       0x11a0eb306 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 502
5   QtCore                        	       0x119f3a83c QThread::exec() + 140
6   QtCore                        	       0x119f3b708 0x119f1b000 + 132872
7   libsystem_pthread.dylib       	    0x7ff8084cf202 _pthread_start + 99
8   libsystem_pthread.dylib       	    0x7ff8084cabab thread_start + 15

Thread 6:
0   runtime                       	    0x7ff7ffe5294c 0x7ff7ffe30000 + 141644

Thread 7:
0   ???                           	    0x7ff898a4ea78 ???
1   libsystem_kernel.dylib        	    0x7ff80848fa2e mach_msg2_trap + 10
2   libsystem_kernel.dylib        	    0x7ff80849de3a mach_msg2_internal + 84
3   libsystem_kernel.dylib        	    0x7ff808496b62 mach_msg_overwrite + 653
4   libsystem_kernel.dylib        	    0x7ff80848fd1f mach_msg + 19
5   mscore                        	       0x1063573ce crashpad::MachMessageWithDeadline(mach_msg_header_t*, int, unsigned int, unsigned int, unsigned long long, unsigned int, bool) + 398
6   mscore                        	       0x106359a8b 0x104c32000 + 24279691
7   mscore                        	       0x106359732 crashpad::MachMessageServer::Run(crashpad::MachMessageServer::Interface*, unsigned int, int, crashpad::MachMessageServer::Persistent, crashpad::MachMessageServer::ReceiveLarge, unsigned int) + 290
8   mscore                        	       0x10634ef48 0x104c32000 + 24235848
9   libsystem_pthread.dylib       	    0x7ff8084cf202 _pthread_start + 99
10  libsystem_pthread.dylib       	    0x7ff8084cabab thread_start + 15

Thread 8:: caulk::deferred_logger
0   ???                           	    0x7ff898a4ea78 ???
1   libsystem_kernel.dylib        	    0x7ff80848f9aa semaphore_wait_trap + 10
2   caulk                         	    0x7ff813063c7e caulk::semaphore::timed_wait(double) + 150
3   caulk                         	    0x7ff813063b98 caulk::concurrent::details::worker_thread::run() + 30
4   caulk                         	    0x7ff8130638bc void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
5   libsystem_pthread.dylib       	    0x7ff8084cf202 _pthread_start + 99
6   libsystem_pthread.dylib       	    0x7ff8084cabab thread_start + 15

Thread 9:: AQConverterThread

### Steps to reproduce

Quit or Closing every time

### MuseScore Version

4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS 14.2.1 (23C71)

**Comment by Fristover** [comment]
Maybe related to #20692

**Comment by dannsh13** [comment]
Ok I looked over #20692  It just seems strange that I reinstalled 4.2 and the closing crash still happens. I have several console crashes if one whole one would help..  I would think that if this not occurring with others, then the problem is with my MACOS since my last update. As a former Mainframe Programmer (IBM 1040, 1070, 360, 370) Assembler, Cobol, CICS, etc. I am aware that bits can get flipped no matter how hard you try to code perfectlly.

**Comment by cbjeukendrup** [comment]
Judging from the attached crash dump, this one is different from all other ones I've seen so far. 

Also, it happens relatively deeply inside Qt, which opens the possibility that it is a Qt problem and not a MuseScore problem. 
At some point we will probably switch to a slightly more version of Qt (5.15.12 instead of 5.15.9) which might do something about it; you never know.

It's strange that this happens consistently for you, while most others don't have it. Maybe you are using some special accessibility settings of macOS? Or is there anything else that might be special about your OS and settings?

**Comment by cbjeukendrup** [comment]
> OK update I started have trouble opening Musescore so I deleted the app and reinstalled. Looked like an update version. I have been using the app and have had no problems and closes just fine.

Uhm oh, I saw this addition only just now. For such significant updates, please post a new comment instead of silently editing your existing comment ;-)

So that means we can close the issue?

**Comment by bkunda** [comment]
Closing as this has apparently been resolved, but of course let's reopen it if the problem persists.

**Comment by cbjeukendrup** [comment]
I will reopen this, as it's still active according to https://musescore.org/en/comment/1224684. 

It turns out to be the same crash as https://github.com/musescore/MuseScore/issues/18572, which apparently also affects some Macs, and not only Linux as was thought back then.

The good news is that it has been fixed for Linux, but the bad news is that the fix for Linux introduced other problems on macOS (namely that the menu bar didn't work at all), so therefore it was applied only on Linux.
Anyway, that does give us some information about in which direction to look for a solution.

**Comment by cbjeukendrup** [comment]
Closing as superseded by #21252, since that issue is doesn't have a complicated close/reopen history yet :)
