### ISSUE TITLE
Slash notation is "backwards" in scores created before 4.2

### ISSUE THREAD

**Issue by Droj** [musescore/MuseScore#20804]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

After upgrading from 4.1 to 4.2, I opened a score that uses slash notation to make some corrections. Slashes in the opened score are displayed correctly at first. However, toggle slash notation causes them to turn into slashes that behave like regular notes, because they are off-center, move when I shift pitch, etc. Toggling again causes them to turn into notes that behave like slashes, but with regular note heads, i.e. they do NOT move when pitch is shifted, and they are centered on the staff. 

This does not seem to be an issue with new scores created with 4.2.

This is a show-stopper for upgrading to 4.2, because it would require a lot of rework on many scores/lead-sheets of mine that use slash notation. I will need to stick with 4.1.1, for now, where this does not seem to be a problem.

### Steps to reproduce

1. open score saved with version previous to 4.2 containing slash notation
2. select staff with slashes
3. toggle slash notation
4. observe shifted notes with slash heads
5. shift pitch to move the slash-head notes
6. toggle slash notation to return to slashes
7. observe notes centered on staff (as slashes should be) with regular note heads
8. shift pitch 
9. observe that notes do not move

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1145085/4745cff5-6374-41ef-bf50-505450a039d8

### MuseScore Version

OS: macOS 13.5, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in MuseScore 4.1

### Operating system

MacOS 13.5

### Additional context

[bad_slashes_from_older_score.mscz.zip](https://github.com/musescore/MuseScore/files/13812951/bad_slashes_from_older_score.mscz.zip)

The attached is a portion of the score I was trying to edit with 4.2, where I could not get slash notation to work. I am able to reproduce the same issues with this.

**Comment by MarcSabatella** [comment]
I can reproduce this in the given score and also in one I create from scratch, *if* the staff in question has parts generated.

@mike-spa I don't think any of the actual slash notation code has changed (just a few minor engraving details), but - I suspect the new property linking system might be what is getting in the way here, and that in  https://github.com/musescore/MuseScore/blame/e0f941733ac2c0959203a5e99252eb4c58f67606/src/engraving/dom/cmd.cpp#L3805-L3808 we are now toggling the property twice if there is a linked part.  Not sure if makes sense to remove the loop or to make setSlash() a little smarter - the other things it does may still need to be done per linked note.

**Comment by MarcSabatella** [comment]
Here is an example created and saved in 4.1.1 for easy comaprison.  Select bar 2 and do Tools / Toggle rhythmic slash notation.  In 4.1.1, you get the correct results - looks the same as bars 1 & 3.  In 4.2, you get the right pitches but the slash heads remain.

[rhythmic-slash-rename-to-mscz.zip](https://github.com/musescore/MuseScore/files/13813299/rhythmic-slash-rename-to-mscz.zip)

@Droj - normally it would be pretty unusual to need to edit slash notation in this way, but when it does come up, you can set the notehead manually and it should work, as far as I can tell.

**Comment by Droj** [comment]
Thanks, @MarcSabatella, that file shows the issue as well! I agree one can set the note head manually, which can work, however the next toggle of slash notation will revert to using the wrong note heads and it would need to be redone.
