### ISSUE TITLE
[feature request] - jsmidgen musescore and cuda - idea for a project based in jsmidgen musescore and cuda (automatic music generation) 

### ISSUE THREAD

**Issue by tiagomoraismorgado** [musescore/MuseScore#20828]
### Core Concept
- Develop an AI system with a sophisticated understanding of music theory, akin to ChatGPT's language capabilities. This system aims to generate jsmidgen files, providing a formalized musical dialogue, which can themselves generat musescore projects that can be rendered with c++ and cuda or otherwise rendered in real time

### Objectives
- Create an abstraction layer, inspired by ChatGPT, to express complex musical ideas and generate cascades of Musescore files.
- Extend functionality beyond mere MIDI files, enabling the creation of intricate compositions using jsmidgen.
- Implement CUDA and C++ for efficient rendering, allowing the generation of an extensive library of high-quality music files.

### Problem Statement
- The challenge lies in formalizing intricate musical concepts and leveraging an abstraction layer similar to ChatGPT. The goal is to produce an abundance of Musescore files using jsmidgen and efficiently render them with CUDA and C++.

### Previous Work
- Grounding upon Algorrithmic Composition thought coming from a rich history of AI experiments in music creation, spanning from early Koenig and Xenakis to the thoguht of Bach Palestrina and Guillaume de Machaut.

### Contextual Relevance
- Addressing the increasing demand for automated tools capable of generating vast amounts of music, particularly for virtual reality, augmented reality, mixed reality, and hybrid reality systems.

### Fascinating Additional Insights
- Integration flexibility extends across diverse environments, encompassing Unity, Unreal Engine, Cryengine, Godot, Processing, OpenFrameworks, Cinder, P5Js, Threejs, and more.
- Seamless binding capabilities to a wide array of programming languages including C++, Java, Python, Nodejs, Ruby on Rails, Bash, PowerShell, and others.
- Compatibility extends to music-oriented platforms such as Ableton, MaxMSP, Puredata, Csound, and Supercollider.
The system's adaptability is highlighted by its capacity to be invoked through system commands, making it applicable across an extensive range of language libraries and framework APIs.

**Comment by cbjeukendrup** [comment]
Thanks for your post! It is not entirely clear to me yet what you are really requesting though. It seems you would like to have a tool to generate music, in the format of MIDI files, and import those in MuseScore. Probably such a tool already exists, and MuseScore already supports importing MIDI files, to render them as good-looking scores (as far as that is possible with MIDI files, which are inherently not appropriate for music _notation_). So what would you like _us_ to do?

**Comment by tiagomoraismorgado** [comment]
**"what am i requesting"**
I'm requesting a relatively straightforward task: take the Jsmidgen library and enhance it to enable the export of MuseScore files through batch or non-real-time rendering. Additionally, I'm looking for improvements in formalizing the generation of Jsmidgen files, incorporating music theory through artificial intelligence and text-based descriptors. The ultimate goal is to find a method, preferably using C++ and CUDA, to efficiently render a large number of bounced files—imagine handling a thousand pieces of music generated from a single script. It's important to note that this constitutes a distinct project, and the decision of whether it should be implemented by the MuseScore team or another entity is open for discussion. The broader aim is to create an infrastructure that can be seamlessly integrated into various environments beyond MuseScore. And for single purposes, ranging from integration with music apps, to VR/AR/XR/MR apps to a whole series of other scenarios, like automating music generation or real time music reproduction (by rendering a single idea in real time in order to provide a non linear music generator), and so

**"So what would you like us to do?"**
*Keep the matter unresolved for the time being; refrain from closing the issue and instead, keep it open-ended. Allow for the possibility of someone expressing interest in taking it up. Maintain an open stance and be patient until a willing individual comes forward to address the issue.*

**Comment by cbjeukendrup** [comment]
So you're requesting something to be done in the JSMidgen library. Why don't you open an issue at their repository? The MuseScore team has definitely no time to work on other people's projects that are not related to MuseScore.



> * _Keep the matter unresolved for now._
> * _Do not close the issue; maintain an open-ended approach._

This is not really how GitHub Issues are supposed to work. 
- There should be as few issues as possible open
- An open issue must be either about a real bug
- Or about a _concrete, clear, and actionable_ feature request 
- Issues should only be about things that need to be solved by making changes to the source code _in this repository_. Muse Sounds issues are the only exception to this.
- Support requests or not-yet-concrete ideas belong in the forums on MuseScore.org.
- Issues about other projects (either third-party or from other Muse Group sub-companies) belong in the respective issue trackers for those projects. 

A reason for this is that GitHub Issues are basically the To Do list of the developers. Nobody wants to have non-actionable items on their To Do list.

**Comment by cbjeukendrup** [comment]
To be clear, it's not that we are not willing; but this is simply not yet the right place for this request. Also, since there literally thousands of important issues that need to be fixed, we cannot do massive niche projects that don't even directly involve MuseScore just to support one person's very specific workflow. 
I understand that this is sad if that one person happens to be you, but I hope that you understand our situation too. We don't have the resources to make all users happy all at once, so we need to make choices; and we make the choice to work on those things that make most users happy, at least we do our best to do so.

**Comment by tiagomoraismorgado** [comment]
ok, absolutely no problem. musescore is a great tool for making music. i will keep using it for sure for a long period of time
