### ISSUE TITLE
Musescore4 says An unknown error occurred while saving this file while saving

### ISSUE THREAD

**Issue by LuoYi-SG** [musescore/MuseScore#20827]
### Issue type

Opening/saving issue

### Bug description

While trying to save, this error keep popping out. No matter how many times I  try to save the file. It happens whether I save the file online or offline.

### Steps to reproduce

1. New file
2. Write some stuff
3. Save online
4. Try editing and saving the file more times

### MuseScore Version

4

### Regression

No.

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
Unfortunately that's not much information to go on.  Please ask for help on the official Support forum on msuescore.org and include more information - the exact MuseScore version from Help / About, what OS you are on, the exact pathname of the folder you are trying to save to and the filename you are trying to use, etc.  Then if anything else is able to figure out how to reproduce the problem you are seeing, you can update this issue with that information.

Also try Help / Revert to factory settings.

**Comment by cbjeukendrup** [comment]
In addition to the above, please upload the diagnostics information that you can export from MuseScore using "Diagnostic" > "Save diagnostic files".

**Comment by zacjansheski** [comment]
Closing as stale

**Comment by Jojo-Schmitz** [comment]
Maybe a duplicate of #20728
