### ISSUE TITLE
Musescore 4.2 crashes when open a score file saved on previous Musescore version

### ISSUE THREAD

**Issue by NeidelAmps** [musescore/MuseScore#20832]
### Issue type

Opening/saving issue

### Bug description

I installed actual release 4.2. After it Musescore crashes if I open one of score files saved on previous Musescore version (see attachment). Against this, Musescore 4.1.1. installed on another pc opens my score without any problems. It seems that an error has crept in..

### Steps to reproduce

1. Start Musescore 4.2
2. Open one of attached score files 
3. Musescore tries to open the file but crashes before at end of load

### MuseScore Version

4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

[FileExamples.zip](https://github.com/musescore/MuseScore/files/13830468/FileExamples.zip)

**Comment by oktophonie** [comment]
Actually the same root cause as https://github.com/musescore/MuseScore/issues/20780
