### ISSUE TITLE
Musescore Ask For Help

### ISSUE THREAD

**Issue by pgmrpmt** [musescore/MuseScore#20853]
### Your idea

Can we change the Ask For Help link in musescore from the forum to point to GitHub?

### Problem to be solved

I've been reporting and researching bugs and fixes in the Forum and just discovered GitHub is the authority now.  All of us that missed the line in the manual are still using the forum.  Thanks

**Comment by MarcSabatella** [comment]
The forums on musescore.org *is* the correct place to ask for help.  So you aren't missing anything.

Now, *if* after posting to the forum, something is confirmed to be an actual bug that is reproducible given the score you provide and steps you list, and that it isn't already reported (or already fixed for an upcoming release), *then* it would be appropriate to open a GitHub issue.  Directing people to GitHub as their first place to get help is definitely not appropriate, as it would result in thousands of spurious issues from people asking basic support questions.

Of course, for people who are more experienced in such matters who understand the difference between a support question and a bug report, and who know how to check for themselves if an issue is already reported here on GitHub, and have a good sense of what's involved in making sure they provide all the information necessary to reproduce an issue, it isn't *necessary* to go to the forum first.  So as people gain more familiarity with the process, people are certainly welcome to come here first of their own accord.  But for new users, it's important they go to the forums first.
