### ISSUE TITLE
Trill color not respected after opening score

### ISSUE THREAD

**Issue by krasko78** [musescore/MuseScore#20856]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Open the attached score. In m.29-33 the left hand has a trill with the wavy line. Upon opening the score, this is displayed in black although if you select the trill and go to Appearance in the Properties panel, you will see that the color should be #c80064 rather than black. Changing the color correctly updates on the screen, but if the score is closed and reopened, the trill is black again and the previously chosen color is still there, just not respected. Interestingly, the trill in m.19-21 does honor its color (the same for both trills in this score).
[Bach - BWV 775 - Two-part Invention No.4 in D minor (copy).zip](https://github.com/musescore/MuseScore/files/13850860/Bach.-.BWV.775.-.Two-part.Invention.No.4.in.D.minor.copy.zip)

### Steps to reproduce

See the description above.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/154632626/55b1c2ea-0271-4b42-972c-8ae2622f34ca)

### MuseScore Version

4.2

### Regression

I don't know

### Operating system

Windows 10

**Comment by krasko78** [comment]
Allow me to try and help with this one even though it's been only a couple of days that I've been looking at MU's code. Here is my 2 cents:
1. The problem does NOT happen with trills with segments in the file. The segments saved inside the <trill> element carry the trill color inside themselves. This explains why the trill in m.19-21 is not black.
2. However, if all the segments of a trill have their default values, the segments are not saved to the file and are recreated on open. The problem arises from the fact that the trill color from the file (<trill> -> <color>) is copied into the trill's line color (see TRead::readProperties() - line 3774) but when the segments are created their color is set from the trill's color rather than the line color (in Trill::createLineSegment() - line 260). Changing the trill color in the Properties panel correctly updates both the line color of the trill and the color of the sgments (in Trill::setProperty()). For a trill, it is the line color that gets saved in the file for a trill.
Hope this helps. :)

**Comment by krasko78** [comment]
@miiizen Could you do it for me instead? I have never created a pull request to master and I believe it will take me time to find out how to do it properly, accept the necessary agreements, etc. Plus I have been having some busy days lately. It is really a small change. Thanks.

**Comment by Jojo-Schmitz** [comment]
I'll do it. If you tell  me your email address, I'll credit you for it too

**Comment by krasko78** [comment]
krasyo.kiryakov@gmail.com
Maybe it is a good idea to remove my comment ("// or seg->setColor(getProperty(Pid::COLOR).value<mu::draw::Color>());") ?
Thanks.

**Comment by Jojo-Schmitz** [comment]
Thanks, all done

**Comment by krasko78** [comment]
Jojo, someone else is going to approve the PR, correct?

**Comment by Jojo-Schmitz** [comment]
Yes
