### ISSUE TITLE
Score causes crash during export of mp3 (Muse Sounds Acoustic Nylon Guitar?)

### ISSUE THREAD

**Issue by Poseidis** [musescore/MuseScore#20851]
### Issue type

Crash or freeze

### Bug description

This score causes a crash when trying to generate an mp3 around 6% of the way through, after being prompted to generate an mp3 file, on the "Exporting audio..." screen. This happens both in using the "Export as mp3" option through Files > Export as well as Publish > Publish to MuseScore.com. I haven't tested other methods.
[Enjoy the Evening, Divine One - Fire Emblem Engage (Evening Somniel Theme).zip](https://github.com/musescore/MuseScore/files/13847488/Enjoy.the.Evening.Divine.One.-.Fire.Emblem.Engage.Evening.Somniel.Theme.zip)

### Steps to reproduce

1. Open score in MuseScore 4
2. Click File > Export > Export as mp3 audio OR Publish > Publish to MuseScore.com

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10 Version 2009 or later, Arch.: x86_64

### Additional context

I created this score in MuseScore version 4.0.0 and used the "Publish to MuseScore.com" option to publish it on the website. After the guitar Muse Sounds pack came out, I wanted to update the online playback with the new sounds, as well as making some small changes to notation later in the score (past the crash point). I opened the file, went into the mixer, and changed the MS Basic acoustic guitar to Muse Sounds "Acoustic Nylon". **There were no issues during playback within the editor, and there were no issues exporting after I changed the guitar sounds back to MS Basic soundfonts.** Given there are 70 measures in the score and it fails 6% through, I'm assuming that it's because of something around measure 4 or 5.

**Comment by bkunda** [comment]
@zacjansheski pls investigate

**Comment by zacjansheski** [comment]
I was not able to reproduce this crash
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240090505, revision: github-musescore-musescore-45f916e
MuseSampler 0.5.1

Are you using default sample rate?

![Screenshot 2024-01-09 105423](https://github.com/musescore/MuseScore/assets/69917893/92667c46-5580-4017-a90c-2652da4077a3)

Could you share diagnostic files?

**Comment by Poseidis** [comment]
I ended up having another issue with the Muse Sounds guitars, similar to the one described here: https://github.com/musescore/MuseScore/issues/20627
After some investigating, I realized that my MuseSampler was at version 0.3.2, which was likely causing this problem as well. There was no way for me to directly update MuseSampler other than completely reinstalling Muse Sounds. However, once I got MuseSampler v0.5.x, this problem was fixed.

I find it very strange that MuseSampler does not update automatically, especially if the user must go out of their way to even view the version, let alone understand what it is for and successfully change the version. Still, this issue

**Comment by cbjeukendrup** [comment]
Yeah, the situation regarding MuseSampler updates is pretty suboptimal right now. It _should_ auto-update, but apparently it doesn't always and there is not way to trigger an update manually. This is one of the problems described in #20704.
