### ISSUE TITLE
Changing the Text style does not update the Properties panel

### ISSUE THREAD

**Issue by krasko78** [musescore/MuseScore#20859]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

Changing the `Text style` of a text object in the Properties panel doesn't immediately update [the other text properties of] the Properties panel until the text object is unselected and selected again. This is also true when the `Text style` is reset or changed via Undo/Redo.

### Steps to reproduce

1. Select a text object.
2. Go to the Properties panel, expand "Show more" and in the "Text style" drop-down list select another text style.

PROBLEM TO OBSERVE: The property values in the Properties panel (font name, size, style, etc.) do not update to reflect the new text style.

3. Unselect and select the text object again. The Text properties are updated correctly with the new values.
4. Press CTRL+Z or click menu Edit -> Undo.

PROBLEM TO OBSERVE: The property values in the Properties panel (font name, size, style, etc.) do not update to reflect the UNDO. `Text style` is not updated either.

5. Unselect and select the text object again. The Text properties are updated correctly with the new values again.
6. Press CTRL+Y or CTRL+SHIFT+Z or click menu Edit -> Redo.

PROBLEM TO OBSERVE: The property values in the Properties panel (font name, size, style, etc.) do not update to reflect the REDO. Neither does Text style.

7. Click the small Reset button (with the arrow) on the `Text style` property.

PROBLEM TO OBSERVE: Again, nothing is updated except for Text style.

NOTE: the selected text object updates properly in the score every time. It is just the Properties Panel that doesn't.

### MuseScore Version

4.2

### Regression

No

### Operating system

Windows 10

**Comment by Sadaf-A** [comment]
greetings @Eism I would like to pick this up could you please assign
