### ISSUE TITLE
Particular Instrument selectable in MS Basic

### ISSUE THREAD

**Issue by ArisoWizard** [musescore/MuseScore#20869]
### Your idea

In previous versions of MuseScore, it was possible to select individual instruments from MS basic or imported .sf2-files. For example if I have a tenor sax as my lead instrument in a score but I change my mind and I want a warm synth sound, I have no option to get the classic synth sound from the MS basic library.

### Problem to be solved

Lack of ability to use the old MS basic patch to its full potential (some sounds just aren't available in the new MuseSounds)

### Prior art

MuseScore 3 and below solved this by having a detailed view of the individual instruments in a sound patch. One could create a drop-down menu with, at first, a list of all installed sf2-files including MS basic, and if you click on them, you can choose which particular sound you would like to use.

**Comment by MarcSabatella** [comment]
This is already possible, please see your duplicate issue https://github.com/musescore/MuseScore/issues/20868

Also note, if you want to change an instrument, the mixer isn't the right way to do it - this changes playback sound only, not all the important attributes like the staff name, transposition, clef, etc.  To change instruments, use the Instruments panel, not the mixer.  The mixer is only for changing between variants of a single instrument, like from one piano sound to another.

In the future, when you have questions about how to use MuseScore, please ask on the official Support forum on musescore.org
