### ISSUE TITLE
using sf2 files in musescore

### ISSUE THREAD

**Issue by ArisoWizard** [musescore/MuseScore#20868]
### Issue type

General playback bug

### Bug description

In every version of musescore since at least 2.0, it was possible to select an individual instrument from an .sf2-file, or even from MS Basic. This is sadly no longer possible.

### Steps to reproduce

1. press F10 to open mixer
2. try to select specific instrument from MS Basic

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10, Windows 11

**Comment by MarcSabatella** [comment]
Are you sure you are using 4.2.0?  It's definitely possible, and with improved organization compared to older versions:

![image](https://github.com/musescore/MuseScore/assets/1799936/622bfe38-070a-4ef2-bde0-9555fd1e33b3)

**Comment by zacjansheski** [comment]
Closing as stale
