### ISSUE TITLE
"Wrong rhythm" when change time signature (in fact only missing eight flag)

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#20864]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When time signature changes, sometimes flag is missing on eight note, so it looks like incorrect rhythm.

### Steps to reproduce

see video

https://github.com/musescore/MuseScore/assets/1646034/887f3782-ef00-4cf3-8200-fb42def5dcf4

### MuseScore Version

master (4.3)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 22.04

### Additional context

It worked even in 4.2

**Comment by oktophonie** [comment]
It fixes itself after the next redraw.

**Comment by oktophonie** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/20358
