### ISSUE TITLE
Add "Note anchored line" causes repeatable crash

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#20875]
### Issue type

Crash or freeze

### Bug description

Program crashes when attempting to add anchored line across piano grand staff.  See attached picture and video for details.
Occurs in MuseScore 4.2.  Tried latest nightly build from 1/6/2024 and it still crashes

### Steps to reproduce

1. Open the attached MuseScore file "anchored line crash.mscz" (zipped)
2. Navigate to measure 255 in the piano (Klavier) part.
3. Select the B-flat dotted quarter note in the second voice of the top piano staff
4. CTRL-click to additionally select the B-flat dotted eighth note in the bottom piano staff.
5. Go to Add --> Lines --> Note anchored line
6. Observe program crash.

I pasted this measure in a new score and there was no crash and the anchored line was created.

### Screenshots/Screen recordings

![anchored_line_crash](https://github.com/musescore/MuseScore/assets/137847641/f01f478a-a7d1-4f03-9442-4c73c0423076)

https://github.com/musescore/MuseScore/assets/137847641/9f9e6b6f-0ce5-40a1-8b8b-dceda29cae3a

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Edition	Windows 10 Home Version	22H2 Installed on	‎12/‎5/‎2020 OS build	19045.3803 Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Additional context

[anchored_line_crash.zip](https://github.com/musescore/MuseScore/files/13855946/anchored_line_crash.zip)

**Comment by XiaoMigros** [comment]
If it's of any help, I have a repeatable crash in MU3 where adding a note anchored line to an instrument appearing in another part causes a crash too.

**Comment by zacjansheski** [comment]
Diagnostic files:

[AnchoredLineCrashDiagnostic.zip](https://github.com/musescore/MuseScore/files/13866203/AnchoredLineCrashDiagnostic.zip)

**Comment by zacjansheski** [comment]
Feel free to share the MU3 file as well!  Thank you!

**Comment by Jojo-Schmitz** [comment]
Yes, please share thet Mu3 score

**Comment by oktophonie** [comment]
Still seems to be an issue when the line is added to a separate piano _part_ (though fine in score)
