### ISSUE TITLE
Selecting the title and then Voice 2 crashes

### ISSUE THREAD

**Issue by joelallison** [musescore/MuseScore#20872]
### Issue type

Crash or freeze

### Steps to reproduce

- Click a note on the score
- Click the title of the score
- Click voice 2

### MuseScore Version

4.2.0.233521125

### Regression

Works in 3.6.2, broken since 4.0

### Operating system

MacOS 14.0

**Comment by MarcSabatella** [comment]
Confirmed.  Sending the title to voice 2 doesn't make sense of course, but it shouldn't crash either.
