### ISSUE TITLE
Search in the special characters dialog

### ISSUE THREAD

**Issue by adazem009** [musescore/MuseScore#20882]
### Your idea

Add a search box to the special characters dialog so that symbols can be quickly found by typing their names.

### Problem to be solved

It often takes a lot of time to find some symbols.

### Additional context

The "Common symbols" tab currently helps with common symbols, but a search feature would be better.

**Comment by avvvvve** [comment]
Thanks for the suggestion! We could replace the special characters dialog with the new symbol picker popup I recently designed for another feature, once that's built. Might need to just tweak what the buttons say for this context. Will come back to this once we start building that.

![image](https://github.com/musescore/MuseScore/assets/20806406/42034b84-2689-4854-af36-29c18235a4ac)

**Comment by avvvvve** [comment]
Closing as this is planned as a part of this issue: https://github.com/musescore/MuseScore/issues/21059
