### ISSUE TITLE
Tremolos do not survive copy/paste in master

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20886]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Tremolos do not survive copy/paste in master

### Steps to reproduce

1. Write a tremolo on a note
2. Copy and paste in a different measure
3. Tremolo is not pasted, only the note

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/d4e1f001-bc25-4db1-a816-840befc48e55

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.3.0-240080302, revision: github-musescore-musescore-4cbc720

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 14

**Comment by igorkorsukov** [comment]
fixed
