### ISSUE TITLE
 [MuseHub] Add release notes for updates of Muse Sounds / Muse Sampler

### ISSUE THREAD

**Issue by metasekk** [musescore/MuseScore#20888]
### Your idea

It would be highly benefical if there were some kinds of release notes for Muse Sounds (respectively, MuseSampler).

### Problem to be solved

As for now, it is very difficult to determine whether an issue opened on GitHub pertaining to Muse Sounds has been processed by new updates of MuseSounds (respectively, MuseSampler). In particular, it can be noticed that issues opened on GitHub with the flag "Muse Sounds" are rarely closed, and seem to be accumulating instead. Those fortunate enough that _are_ closed, however, are often closed by the users who opened the issue, replying something like "Just updated Muse Sounds and the issue seems gone" or "I updated Muse Sampler on my laptop, and there are no more problems", yet there is no way to formally confirm that it has been solved indeed. Thus, it is likely that a significant number of MuseSounds-related issues are still open while solved in practice, either because it couldn't be proved they were solved, or because they were simply forgotten.

**Comment by cbjeukendrup** [comment]
Related to #14286, but still somewhat different: for MuseScore and Audacity, release notes at least _exist_ somewhere on the internet, but for Muse Sounds / MuseSampler, there is simply _nothing_.

**Comment by cbjeukendrup** [comment]
I think this can be closed now, since this basically has been implemented with Muse Hub V2.

**Comment by metasekk** [comment]
(Still no update for MuseSampler however? It seems to be updated on the fly, inconspicuously)
