### ISSUE TITLE
MuseScore 4.2.0-233521125 Running Very Slowly

### ISSUE THREAD

**Issue by dhcpercussion** [musescore/MuseScore#20889]
### Issue type

Other type of issue

### Bug description

MuseScore 4.2.0-233521125 is running very slowly, It's a larger book (right now at 60 pages) but with only one line of melody. Any thoughts? Thank you!

### Steps to reproduce

1. Launching file with app already open takes about 30 seconds to load in.
2. Entering notes, text, dynamics, cutting/pasting, etc. responds about 3-20 seconds after my keyboard entries.
3. This lag significantly interrupts work flow.

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c.

### Regression

I don't know

### Operating system

I am using macOS 12.6, 2.6 GHz 6-Core Intel Core i7, 16 GB 2400 MHz DDR4

### Additional context

This file was originally started in MuseScore 3. I'm continuing composing the book using Musescore 4.

**Comment by MarcSabatella** [comment]
Please ZIP and attach the score with the problem.  It's somewhat normal that larger files are slower to work with, but perhaps there is something going on making this particular score even worse than it should be.

**Comment by dhcpercussion** [comment]
Thank you, Marc. I shut down my computer for five minutes, then rebooted. It seems to be running faster than before and at an acceptable speed. Thanks - this case is maybe closed.

**Comment by dhcpercussion** [comment]
I'll close it.

**Comment by JDexterus** [comment]
I have noticed this as well.  It seems, regardless of the score being worked on that, over time, MuseScore 4.2.1 gets more and more sluggish.  To me it seems it may be a memory usage concern because if I save the score and close MuseScore, then reopen it, it runs normally again....for a while.  Perhaps it is telling me I need to take a break!

Mac M1 mini with 8 GB
Sonoma 14.2.1

**Comment by cbjeukendrup** [comment]
To confirm that it is a memory problem, you could use the Activity monitor utility. It would be useful to look at the Memory page, specifically the overall "memory pressure" and the memory usage of MuseScore.

**Comment by JDexterus** [comment]
Finally getting back to this.  MuseScore became very sluggish today while working on a 4-part choral/piano piece.  Please see the attached pics from the Activity monitor.  Thanks. MuseScore was the only application running, aside from Preview and Activity Monitor.
￼￼

**Comment by cbjeukendrup** [comment]
Since you replied via email, the attached images got lost. Please try posting them directly using GitHub (click the "view on GitHub" link at the bottom of the email)

**Comment by JDexterus** [comment]
Thanks.  Here are the pngs.

![MuseScore Mem Use](https://github.com/musescore/MuseScore/assets/151408917/39eb00c3-679a-4e84-bf96-9b5ff9e94035)
![MuseScore CPU](https://github.com/musescore/MuseScore/assets/151408917/bc3457c7-8c86-4f03-ad3d-6af649a97b9a)

**Comment by cbjeukendrup** [comment]
Thanks! Well, yes, that's a memory issue. 6.19GB memory usage is huge. 

Does it immediately become that much when you launch MuseScore and open the score, or does it gradually grow while working?

Recently there was another similar report (#22094), so we will investigate the problem as part of that issue.

**Comment by JDexterus** [comment]
I haven't actually tracked the memory usage over time, but will do so.  It seems to build up, because for a while MuseScore responds normally.  When I do notice that it is lagging, the lagging then quickly accelerates until I finally have to close it down and begin again.  I will keep an eye on memory usage over time.
