### ISSUE TITLE
Incorrect display of the glissando line

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#20894]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

The glissando line, for unknown reasons, goes down somewhere, although it should go up

### Screenshots/Screen recordings

![Снимок экрана (98)](https://github.com/musescore/MuseScore/assets/134041121/70be27d7-fa41-426b-8649-9c3c30e7eb0e)
[Mammoths(AltEnd).zip](https://github.com/musescore/MuseScore/files/13871068/Mammoths.AltEnd.zip)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 11

**Comment by oktophonie** [comment]
Sounds an awful lot like https://github.com/musescore/MuseScore/issues/15295
