### ISSUE TITLE
'Insert special characters' does not load when opening Properties with text editing active 

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#20922]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

If the properties panel is not currently active (i.e. it's closed or a different panel tab is open above it) AND a text object is in editing mode, making Properties active does not show the 'Insert special characters' button in the text section as it should.

Normally, with Properties active, the button shows up once a user starts editing a text element (see first half of screen recording below).

### Steps to reproduce

1. Close the properties panel (F8)
2. Double click into a text element in the score
3. Open the properties panel, see that 'Insert special characters' is not there
4. Move the cursor within the text element and see that it shows up

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/20806406/2cd4d285-30be-4bf8-b4e1-f60d8d409087

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

OS: macOS 14.1, Arch.: x86_64

**Comment by wizofaus** [comment]
Just had this now, it's very odd, will have to try with latest master.
