### ISSUE TITLE
Grace notes split from beams don't get flags

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#20923]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When splitting grace notes from a beam (either through changing the beam mode or deleting other grace notes), the resulting non-beamed grace notes don't have a flag. The flag is added upon relayout.

### Steps to reproduce

1. Create a new score
2. Add 2 grace notes to a normal note, so that the grace notes are beamed together
3. remove one of the grace notes or change its beammode.
4. (To add the flags) change any of the notes' pitch.

### MuseScore Version

4.2.0

### Regression

I don't know

### Operating system

Windows 10

**Comment by oktophonie** [comment]
Similar to https://github.com/musescore/MuseScore/issues/20358
