### ISSUE TITLE
Cmd+Delete measures and undo crashes MuseScore

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#20947]
### Issue type

Crash or freeze

### Bug description

MuseScore crashes inconsistently when I command+Delete measures and undo in this score.  I hope the logs reveal better information since it is inconsistent.

[DeleteFirstBarUndoCrash.mscz.zip](https://github.com/musescore/MuseScore/files/13892075/DeleteFirstBarUndoCrash.mscz.zip)

### Steps to reproduce

1. Open Score
2. Select first measure
3. Cmd+Delete
4. Undo

If that doesn't work, try with a larger selection

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/6a789d5b-8ad4-4ff0-895f-6b5a0cc22a69

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240101719, revision: github-musescore-musescore-8edeb20

### Regression

I don't know

### Operating system

Mac OS 14

### Additional context

[DeleteUndoCrash.zip](https://github.com/musescore/MuseScore/files/13892827/DeleteUndoCrash.zip)

**Comment by zacjansheski** [comment]
Another video if it helps at all

https://github.com/musescore/MuseScore/assets/69917893/faf02241-4fb9-44ec-93b8-d26e2296d9a5

**Comment by DmitryArefiev** [comment]
Fixed in #21024
