### ISSUE TITLE
Better configurability of turns

### ISSUE THREAD

**Issue by ThatOnePianist** [musescore/MuseScore#20958]
### Your idea

Turns are essential for writing music, especially Baroque-styled music. But MU has some problems with it.
First of all, you can't adjust the speed of the trills.
Second of all, you can't adjust where the are, on the note or after the note? (see image)
![image](https://github.com/musescore/MuseScore/assets/151048770/9ce75bf1-96f2-4c14-a834-309bd04f0d76)

### Problem to be solved

Just, many Baroque-styled pieces and just better working in general.

**Comment by bkunda** [comment]
Closing as a duplicate
See https://github.com/musescore/MuseScore/issues/20097
And https://github.com/musescore/MuseScore/issues/19694
