### ISSUE TITLE
Huge & misplaced tie mark when moving note between voices

### ISSUE THREAD

**Issue by tmr232** [musescore/MuseScore#20967]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When I move a note between voices, I get a huge tie marking drawn. It doesn't go away if I return it to the original voice.

![image](https://github.com/musescore/MuseScore/assets/1386239/b8057b74-75dc-4fbd-bf92-8a833dca4738)

### Steps to reproduce

1. Load the attached score
2. Go to bar 89
3. On the last beat of the bar, select the note on the 6th string (the lowest one)
4. Move it to voice 2

[defying grabity sample.zip](https://github.com/musescore/MuseScore/files/13906770/defying.grabity.sample.zip)

### Screenshots/Screen recordings

![huge-tie-on-change-voice](https://github.com/musescore/MuseScore/assets/1386239/dd8371bb-e32b-4489-8c95-f458f85ddafc)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 11

**Comment by oktophonie** [comment]
Akin to https://github.com/musescore/MuseScore/issues/20551  but not fixed by https://github.com/musescore/MuseScore/pull/20559 / https://github.com/musescore/MuseScore/pull/20656
