### ISSUE TITLE
Changing duration of multiple notes should leave all selected

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#20962]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When selecting multiple notes (list selection):
![image](https://github.com/musescore/MuseScore/assets/20604032/a24a48b7-2909-4f7a-a011-928ae9a16ce5)
Changing their duration (selecting a note duration, or adding dot(s)), either via the toolbar or the relevant keyboard shortcuts, then leaves nothing selected:
![image](https://github.com/musescore/MuseScore/assets/20604032/b6c3126c-ffb7-4285-8747-66b3a6146442)
When it would be far more useful if the originally selected notes remained selected:
![image](https://github.com/musescore/MuseScore/assets/20604032/082dbc31-7626-48cc-a01d-b3fe568fa61a)
(which does happen when adding articulations from the toolbar, for example)

Curious exception: selecting multiple _rests_ and adding a dot to them will leave the first rest selected.

I'm not entirely sure what should happen in the case of a range selection.

Not unrelated: https://github.com/musescore/MuseScore/issues/20720 (and indeed https://github.com/musescore/MuseScore/issues/13469)

### MuseScore Version

4.2

### Regression

No

**Comment by XiaoMigros** [comment]
I'd like to try my hand at this one
