### ISSUE TITLE
Custom workspace resets to default configuration when closing MuseScore

### ISSUE THREAD

**Issue by marchfra** [musescore/MuseScore#20990]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

I created a new workspace (making sure to check all the boxes) and edited the toolbar, the palettes number, order and content and made all the customisations that I like to have when using MuseScore. Except that when I close and reopen the program, none of those edits were recalled, my custom workspace looks just like the default one.

### Steps to reproduce

1. Create a new workspace, ticking all the boxes in the prompt that appears
2. Make some modifications to the toolbar and the palettes order and content
3. Close and reopen MuseScore
4. None of the modifications are recalled. Custom workspace looks just like the default one.

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 14.1 Intel

**Comment by MarcSabatella** [comment]
Make sure to close all other open MuseScore windows first, before making your changes.  Otherwise their customizations may overwrite each other.

**Comment by bkunda** [comment]
@DmitryArefiev can you pls try reproduce this one? 
@marchfra did Marc's suggestion [here](https://github.com/musescore/MuseScore/issues/20990#issuecomment-1889807806) help resolve this for you?

**Comment by marchfra** [comment]
Yes, I had other instances open and somehow I didn't realise it.
Still, it was quite difficult to set up my workspace because MuseScore kept crashing and losing my progress, so I would edit a palette, then quit MuseScore and reopen it so it wouldn't crash and lose the progress. I did all this without opening a document, and I later found the whole process to be much more stable with a document open.

**Comment by DmitryArefiev** [comment]
> Yes, I had other instances open and somehow I didn't realise it.

So, we don't support that workflow now. Please create a new workspace with only one MuseScore instance (one window opened)

Also, there is another bug with workspaces #12822
