### ISSUE TITLE
Glissandi disappear in extracted parts

### ISSUE THREAD

**Issue by julenComposer** [musescore/MuseScore#21008]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Dear all, I'm extracting parts from a large orchestral score. Some parts I had to create from scratch. When creating a new part and adding instruments to it with the eye button of the instruments panel (F7) glissandi that were in the score disappear.
This happened to me only when porting an instrument into a new part that I created myself.

### Steps to reproduce

1. Create an ensemble score with instruments playing glissandi.
2. Go to "parts".
3. Create a new part.
4. Open that new part.
5. From the instrument panel import an instrument performing glissandi into that new part.
6. Check if glissandi are missing from the part.

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

No

### Operating system

Windows 11

**Comment by oktophonie** [comment]
Sounds like https://github.com/musescore/MuseScore/issues/16096.
If you can attach a score (.zip it) where this problem can be reliably reproduced, it would be very helpful.

**Comment by julenComposer** [comment]
Oh sure, I apologise for being this late.
[Orkeststuk I - in vier scénes 03_Jan_2023.zip](https://github.com/musescore/MuseScore/files/13943525/Orkeststuk.I.-.in.vier.scenes.03_Jan_2023.zip)

Thank you!

**Comment by MarcSabatella** [comment]
I can reproduce this from scratch as well.

1) new score for one instrument
2) add two notes with a gliss between them
3) go to File / Parts
4) Open all

Result: gliss is there, as expected

But then:

5) go back to File / Parts
6) create new Part
7) Open selected
8) in Instruments panel, show the instrument

Result: no gliss.  You don't actually need to follow steps 3-4; that's just to show gliss in parts *does* work normally.

So it seems the default part containing the instrument gets the gliss, but subsequent ones don't.  This issue appears to only affect gliss, not tremolo, slurs, or hairpins.

[Screen recording 2024-01-15 4.24.36 PM.webm](https://github.com/musescore/MuseScore/assets/1799936/2c246239-23a7-400e-bd99-2e08215ad8d3)

**Comment by MarcSabatella** [comment]
Same behavior in 4.1.1 and 4.0, BTW.

**Comment by nr397** [comment]
The previously listed steps still cause this issue with cross-staff glissandi.

https://github.com/user-attachments/assets/3c17f4a7-6205-4c3a-a53a-e7e87fd17112
