### ISSUE TITLE
Change how Adding Special Character function

### ISSUE THREAD

**Issue by Chilaila** [musescore/MuseScore#21005]
### Your idea

When inserting special characters from the "Special Character Screen" it keeps the focus on the said screen. Please change it so that the focus goes back to MuseScore so one do not need to click the MuseScore screen in order to keep typing.

### Problem to be solved

Continuously clicking between the two screens. It will decrease typing with lots of special characters tremendously. Especially when working with multiple screens.

### Additional context

I've tested by focusing MuseScore and clicking the character I wanted to add, and did not find any problems. So if it can be done automatically it would not hinder the way it's already working. Just focus back to MuseScore after every character that has been inserted. By doing so you do not have to manually focus MuseScore to keep on typing, saving time and efford.

**Comment by rgreen5** [comment]
This could be a restatement of #18946.

**Comment by Chilaila** [comment]
Seems so, yes. Did not see it using the search phrase I used.

**Comment by cbjeukendrup** [comment]
No problem :) Then I will close this was a duplicate!
