### ISSUE TITLE
Transparent dialogue box

### ISSUE THREAD

**Issue by philipplndwhr** [musescore/MuseScore#21007]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

On the side panel, on various palettes, the button "more" leads to visual bugs

### Steps to reproduce

1. Open a palette in the side menu
2. click the "more" button at the top of a palette
3. experience a visual bug with a chance?

HOWEVER: This behaviour cannot be reproduced every time, maybe at a rate of 40%. Clicking an element from the pop-up usually resolves the issue.

### Screenshots/Screen recordings

<img width="541" alt="the repeat last measure symbol (under repeats & jumps) has a weird green texture" src="https://github.com/musescore/MuseScore/assets/109522890/d07ab2bf-709e-4e36-ba78-62efc3a2d89d">

<img width="496" alt="transparent background when clicking the more button under the text palette" src="https://github.com/musescore/MuseScore/assets/109522890/2c8a7f42-2edb-4df8-9993-8d51afe13f8e">

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: macOS 13.x

**Comment by bkunda** [comment]
@zacjansheski pls investigate

**Comment by bkunda** [comment]
@philipplndwhr are you experiencing this on a native mac display, or an external display?

**Comment by philipplndwhr** [comment]
It is happening on a native Mac display (13" Retina from 2020).
I have not checked if it happens on an external screen as well.

**Comment by zacjansheski** [comment]
I haven't been able to reproduce on similar device (13" Macbook macOS 13.6)
Does a revert to factory settings stop the strange behavior?

**Comment by zacjansheski** [comment]
@philipplndwhr Is this still happening for you on 4.2.1?
Have you tried a factory reset?

**Comment by zacjansheski** [comment]
Closing: no response, can't reproduce
