### ISSUE TITLE
Bar number displays incorrectly when using bar number offset

### ISSUE THREAD

**Issue by marchfra** [musescore/MuseScore#21047]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

If I set a bar number offset in the bar properties, a few bars later the offset isn't "remembered" and it displays the bar number without the offset. I then have to open the bar properties of the bar with the incorrect number, set any offset and apply, and then reset the offset to 0 and apply, and now the offset iI set before is remembered. This keeps happening every few bars, so even if I reset a bar I have to reset the bar number every 4 bars, for example.

### Steps to reproduce

1. Set a bar number offset
2. Check that all subsequent bar numbers are correct (you may need to force a system break to really appreciate the issue)

### Screenshots/Screen recordings

<img width="1054" alt="image" src="https://github.com/musescore/MuseScore/assets/73989695/fb4e9c90-ddde-48e6-9dfe-4a3af8fb945f">

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS Sonoma 14.1.2 (23B92)

**Comment by oktophonie** [comment]
Same as https://github.com/musescore/MuseScore/issues/20768, fixed in 4.2.1
