### ISSUE TITLE
Ties connect non-selected note

### ISSUE THREAD

**Issue by irwir** [musescore/MuseScore#21043]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

To create a tie, selected two notes in one bar with Ctrl+click  but yet another note was tied.

### Steps to reproduce

Create a  4/4 score, add quarter notes: C1, C1, E1, C1
Use Esc to make sure nothing is selected.
Click note 1, then add note 2 to selection with Ctrl+click.
Click `Tie` button or use 'T' shortcut.
Expected one tie to be created, but there would be two: note 1 to note 2, and note 2 to note 4.

### MuseScore Version

4.2.0

### Regression

I don't know

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
The tie command *starts* a tie with the selected note - you aren't supposed to select multiple notes.  If you do select multiple notes, a tie is created starting from each, by design (useful in a number of situations).

**Comment by irwir** [comment]
Thanks for the clarification, ,but still looks like a bug.
If C1 and E1 were selected, no tie could be created.
Also, tie between notes 2 and 4 makes no sense because of duration.

**Comment by Jojo-Schmitz** [comment]
If the 2nd and 3rd get selected, only the 2nd gets a tie, and to the 4th, the 3rd doesn't, as there isn't another note of that bpitch anywhere later.

Yes, ties __normally__ only connect __adjacent__ notes of the same pitch, but MuseScore does also __allow__ ties on non-adjacent ones. It is a feature, not a bug

**Comment by Jojo-Schmitz** [comment]
And needed/used for some arpeggio / let ring scenarios

**Comment by irwir** [comment]
Thanks. Logic and music may create strange combinations (features).
Fun facts.
Sibelius allows ties for different pitches, but there seems to be a plugin to convert such ties to slurs. It is possible to connect notes with both slur and tie.
PriMus has the most natural behaviour, it ties only adjacent notes of the same pitch.

**Comment by Jojo-Schmitz** [comment]
In short: Sibelius has a bug and PriMus is lacking a feature ;-)
