### ISSUE TITLE
Instrument Change — Title mismatch

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#21040]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

• **Change Instr.** is shown in the Text palette
• But the menu option is Add>Text>**Instrument Change**

### Steps to reproduce

Look in the Text Palette and compare to the menu Add>Text>**Instrument Change**

### MuseScore Version

MuseScore 4.2

### Regression

I don't know

### Operating system

MacOS 13.5.2

**Comment by bkunda** [comment]
By design: in the palette, "Change inst." is placeholder text for the in-score element; in the menu, it is an instruction.

**Comment by Jojo-Schmitz** [comment]
Adding either results in the same thing, an Instrument Change text
