### ISSUE TITLE
[TIED NOTES] Glissando on tied note sustains first note throughout (Muse Sounds)

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#21048]
### Issue type

Muse Sounds bug

### Bug description

On Muse Sounds only, a glissando on a tied note sustains the initial note throughout the glissando.

### Steps to reproduce

1. Enter two tied notes with a glissando to a third note
2. Play

Result: the tied note sustains through the glissando.  For piano, the note decays fast enough you might not notice, but for winds, it's obvious to the the point where the sustained note can actually make it hard to hear the glissando at all.

### Screenshots/Screen recordings

[Screen recording 2024-01-17 8.28.36 AM.webm](https://github.com/musescore/MuseScore/assets/1799936/8a6cbafa-14da-4d29-8ef1-767a7573515b)

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240170504, revision: github-musescore-musescore-9e59c8a

### Regression

I don't know

### Operating system

Debian 11

### Additional context

The same behavior happens with current Muse Sampler in 4.1.1, but I cannot say if a previous version of Muse Sampler might have behaved differently.

In 4.2, glissandi on tied notes don't play at all.  This is tested with a current nightly build in which that bug is fixed, but playback for Muse Sounds remains incorrect.

See also https://github.com/musescore/MuseScore/issues/19380 which is about a different issue with glissandi on tied notes for MS Basic only that is not a regression, and https://github.com/musescore/MuseScore/issues/20570 which is the now-fixed issue regarding glissandi on tied notes in 4.2 in general.

**Comment by bkunda** [comment]
@RomanPudashkin this looks like another manifestation of the tied-notes issue we've seen before :-)
