### ISSUE TITLE
Properties popup doesn't allow scrolling, preventing access to certain menu options

### ISSUE THREAD

**Issue by Panogen** [musescore/MuseScore#21044]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

When multiple elements of different types are selected, MuseScore provides the ability to edit the properties of each type of element selected by clicking on the respective button, which will open a popup window with the associated settings. However, this window does not permit vertical scrolling. Additionally, opening the "show more" dropdown (for example, in the properties for "Note") will cause the main "Properties" panel to scroll down, rather than repositioning the popup in order to fit the added options. Combined, these problems make it impossible in these scenarios to access certain options, such as notehead type and size.

### Steps to reproduce

1. Select a group of notes that has multiple types of elements, such as accidentals or articulations.
2. Open the "Properties" panel and click on "Note".
3. Press "Show More".
4. It is impossible to scroll down to the new options.

### Screenshots/Screen recordings

First: behavior with only one element type (a notehead). All menu items are accessible.
Second: behavior with a notehead and an accidental selected. Many menu items are now inaccessible.

https://github.com/musescore/MuseScore/assets/73259774/c24d347b-e1d1-4bab-a527-f52cd29f8b4c

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

No.

### Operating system

Windows 11

**Comment by bkunda** [comment]
@zacjansheski pls check this in RC.

**Comment by zacjansheski** [comment]
This seems to be a Windows specific issue

@Panogen are you using multiple monitors?  Are you using special scaling? (from what I can tell this makes the issue more noticeable)

**Comment by Panogen** [comment]
> @Panogen are you using multiple monitors? Are you using special scaling? (from what I can tell this makes the issue more noticeable)

No, I'm on single-monitor, and can't recall touching any scaling settings.

**Comment by Eism** [comment]
@XiaoMigros 
Can you provide more information on how we can reproduce the bug?

**Comment by XiaoMigros** [comment]
Like in the video above, when opening the note tab via the button that appears with range selections, opening 'show more' scrolls incorrectly. Im using a Windows 10 laptop with default scaling settings. Can reproduce consistently.

**Comment by zacjansheski** [comment]
@Eism here is a video showing the difference between MacOS and Windows.  The window gets pushed up to show the bottom options.

https://drive.google.com/file/d/1avYjT7aJ_bQNY5TVhPEVfuRPSjuY2mK-/view?usp=sharing

**Comment by zacjansheski** [comment]
[Bach__Sechs_kleine_Praludien_4_Prelude in D Major_BWV 936.zip](https://github.com/musescore/MuseScore/files/14101109/Bach__Sechs_kleine_Praludien_4_Prelude.in.D.Major_BWV.936.zip)

@Eism Here is a score with some elements to select to populate the properties window

**Comment by bkunda** [comment]
@avvvvve did you try reproducing this?
@zacjansheski this one might need to be re-checked since the change to Qt6 (just to see if it hasn't inadvertently been fixed).

**Comment by XiaoMigros** [comment]
I'm no longer facing this exact issue in the latest master

**Comment by avvvvve** [comment]
@bkunda it seems like this isn't an issue anymore - the popup seems to always open to its full height.
@zacjansheski would you like to re-check this just to be sure?

**Comment by zacjansheski** [comment]
No longer reproducible, looks like it was fixed. by a QT Update
