### ISSUE TITLE
Option to hyphenate the later line in lyrics

### ISSUE THREAD

**Issue by Offert4324** [musescore/MuseScore#21045]
### Your idea

When transcribing lyrics, about half of publishers (maybe more) put a hyphen that spans two lines at the beginning of the later line as well as the end of the earlier line when there is a line break in the middle of a word. Currently, MuseScore is set up to only hyphenate the earlier line, and it would be nice to have the option to hyphenate the later line as well, so that users can adapt to the style of the publisher they are working with or their own preferences. 

### Problem to be solved

I think it could be possible to choose whether or not to use hyphens on later lines in Format→Style, just as one can choose how to display accidentals when key changes are made.

### Additional context

Here's an excerpt from the score of the opera "Turandot" for reference.
![image](https://github.com/musescore/MuseScore/assets/104715700/18fa9170-bdad-42d7-b3e5-fad3f35b72d8)
![image](https://github.com/musescore/MuseScore/assets/104715700/d7be7f8c-8e60-40a2-b4d4-030cb2da687d)

Also, to emphasize that this is not just the preference of a minority, here's a list of various works and their publishers, along with whether or not they hyphenated the latter of the two lines. I picked the works off the top of my head, with no particular bias, except that I avoided duplicating publishers.

Puccini: Turandot (Ricordi, 1977) - hyphenated
Mozart: Die Zauberflöte (Bärenreiter, 1970) - no hyphen
Berg: Wozzeck (Universal Edition, 1955) - no hyphen
Offenbach: Les contes d'Hoffmann (Alkor-Kassel, 1982) - hyphenated
Bizet: Carmen (Edition Choudens, 2014) - hyphenated
Wagner: Parsifal (Schott, 2013) - hyphenated
Rameau: Platée (Durand, 1907) - hyphenated
Strauss: Die Frau ohne Schatten (Adolph Fürstner, 1919) - no hyphen
Handel: Alcina (Deutsche Händelgesellschaft, 1868) - hyphenated
Shostakovich: The Nose (DSCH, 2015) - hyphenated
Brahms: Ein deutsches Requiem (Breitkopf & Härtel, 1926-27) - no hyphen
Dvořák: Rusalka (SNKLHU, 1959) - no hyphen
Stravinsky: The Rake's Progress (Boosey & Hawkes, 2017-18) - hyphenated
Adès: Totentanz (Faber Music, 2013) - hyphenated
Messiaen: Saint François d'Assise (Alphonse Leduc, 1990) - hyphenated
Verdi: Il Trovatore (Schirmer, 1898) - no hyphen
Poulenc: Gloria (Éditions Salabert, 1960) - hyphenated
Reger: Drei Gesänge (Bote & Bock, 1909) - no hyphen
Tchaikovsky: Eugene Ongein (Muzyka, 1965) - hyphenated
Falla: El retablo de maese Pedro (J. & W. Chester, 1924) - hyphenated

**Comment by oktophonie** [comment]
Good idea, and just needs a simple checkbox.

**Comment by wizofaus** [comment]
Yes, agree this is needed and should be the default. I actually can't any scores that don't do this.

**Comment by Offert4324** [comment]
@wizofaus 
I first also thought so, but Marc Sabatella suggested the opposite. (https://musescore.org/en/node/330255) So I can't be completely sure that publishers that don't do so are in just a small minority. Hyphenated scores are more prevalent in these 20 samples, but it may be worth further investigation.

**Comment by wizofaus** [comment]
It's conceivable that it's somehow different for jazz charts? But all the classical & pop vocal repertoire I have to hand definitely shows hyphens at the start of each system when the first syllable is not the start of the word.

**Comment by MarcSabatella** [comment]
You can see a little more history regarding this in https://musescore.org/en/node/279160.  One relevant observation there is that other programs provide the option and default to "off".  Since much of the early work on MuseScore was modeled on Sibelius' behavior, I suspect that is how the default got the way it is.  When I first saw this being discussed, I did my own investigation (looking across classical, pop, and jazz), and found the leading hyphen in a little *less* than half the scores I checked, where the list above shows them in a little *more* than half.  Collectively, that suggests it probably really is quite close to 50/50.  In any case clearly, both are common enough to be supported regardless of whether the actual percentages are 60/40 or 40/60.

**Comment by wizofaus** [comment]
Providing users can change the "global" default for new scores I'm not that fussed either way. But are we ok with it being a score style? Is there any case you might to turn off on a per case basis?

**Comment by Jojo-Schmitz** [comment]
IMHO it should be a per score setting

**Comment by wizofaus** [comment]
There's already a style under "Lyrics" called "always force dash" that kinda sounds like it should cause this behaviour, but obviously not (I haven't really investigated what it does do). Maybe a second checkbox "Redisplay dash at start of system"?  But out of curiosity what is the normal process for changing any the global defaults in the Format|Style dialog?  And yes I know how to Load/Save styles, but for a setting like this (and it's not the only one) I'd want to set a global default that applied to all new scores (esp. when importing from xml which I'm doing a lot of currently!).

**Comment by oktophonie** [comment]
I should probably point out that this is being worked on right now as part of https://github.com/musescore/MuseScore/issues/21166.

**Comment by wizofaus** [comment]
One argument in favour of it being not "per score" is that it may be something that makes sense in some languages but not others? I did see a comment suggesting it's not typically done when lyrics are in German (though the first "German" score I had at hand, Carmina Burana, definitely does do it - admittedly it's not modern German!).  So if you have a mixture of languages used in a score maybe there might be a case for at least being able to hide them in certain cases.

**Comment by wizofaus** [comment]
> I should probably point out that this is being worked on right now as part of #21166.

Ah well in that case I won't spend any more time on it, thanks.
