### ISSUE TITLE
Unable to edit slurs - they flip sometimes

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#21057]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When editing slur curve by draging hook, it sometimes flips itself.

### Steps to reproduce

1. slured notes have to be in bottom part of staff (stems up by default)
2. number of slured notes have to exceed measure duration by two beats
3. slur have to be under notes by default
4. grab sume inner hooks of slur and try to move - see slur flips during edit, and flips back after edit

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1646034/7558365d-13be-4a38-97fe-462d72084628

### MuseScore Version

master

### Regression

I don't know

### Operating system

Ubuntu 22.04

### Additional context

Hard to say, if it is regression on 3.6.2, as slur was not placed under notes in souch situation there.

**Comment by Jojo-Schmitz** [comment]
How did you add the slur, using the keyboard shortcut "S" or the Master palette?
Or using the Lines or Articulations palette?

In the latter case you can't change the slur's shape at all, not sure whether that is related, but it came up in https://musescore.org/en/node/360411

**Comment by Jojo-Schmitz** [comment]
...and seems to be a reggressoin of 4.2.1 vs. 4.2.0!

**Comment by sammik** [comment]
> How did you add the slur, using the keyboard shortcut "S", Add > Lines > Slur, or the Master palette's Lines or Articulations palette? Or using the 'standard' Lines or Articulations palette?
> 
> In the latter case you can't change the slur's shape at all, not sure whether that is related, but it came up in https://musescore.org/en/node/360411 and seems to be a reggressoin of 4.2.1 vs. 4.2.0! Works again after save, close, reopen.

Same results, with any "slur creation" method.

**Comment by Jojo-Schmitz** [comment]
Then this seems unrelated

**Comment by sammik** [comment]
> Then this seems unrelated
But I am on Linux.

**Comment by Jojo-Schmitz** [comment]
Ah, yes, that apparently is a plain Windows issue
