### ISSUE TITLE
Empty measure gets whole rest added in second voice

### ISSUE THREAD

**Issue by irwir** [musescore/MuseScore#21056]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When changing duration of notes and rests in two voices, a whole rest in voice 2 could be automatically added to the following empty measure.

### Steps to reproduce

Empty score 4/4, one staff with two empty measures  - by default filled with whole rest in voice 1.
In the first measure select voice 2, quarter note, enter C1 four times.
Select note 3, change it to quarter rest.
Change this quarter rest to half rest - the following measure has full rests in voices 1 and 2.

### MuseScore Version

4.2.0

### Regression

No; v3 also

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
Same issue in Mu3, so indeed not a regression
