### ISSUE TITLE
Changing text type from properties panel does not reflect in parts

### ISSUE THREAD

**Issue by pgrimes2002** [musescore/MuseScore#21053]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

I originally inputted text as staff text, but wanted to change to system texts so that all parts included the text. Despite changing the text to system text in the score, that was not reflected in the parts as they did not include any of the text that I switched to system text using the properties panel.

### Steps to reproduce

1. Create parts
2. Apply staff text to a stave in the score
4. Change that text to system text using the properties panel
5. Observe that the parts do not include the text as one would expect

### MuseScore Version

4.2.0

### Regression

I don't know

### Operating system

macOS 14.2.1

**Comment by avvvvve** [comment]
@pgrimes2002 This is not really a bug, but rather a unfortunately confusing piece of UX.

The "Text style" dropdown in Properties does NOT change the element type (i.e. from Staff text to System text); it lets you select from a list of presets that apply formatting to the text. Elements like Staff text come pre-loaded with the appropriate text style, but selecting something else in the dropdown does not change how the element works - it just changes which style in "Format > Style... > Text style" is used for that element.

It's completely understandable why you'd think it would work the way it did. There's a feature request (#16844) that already gets at this issue, so I'm closing this one for now.
