### ISSUE TITLE
Accidentals should reflect the staff they are written in when notes are beamed across staves

### ISSUE THREAD

**Issue by Panogen** [musescore/MuseScore#21061]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Accidentals on a note typically aren't rendered if the same accidental has appeared previously in the same measure and is not separated by the use of a different accidental on the same note. This behavior works correctly if there is no cross-staff beaming (i.e. all the notes are in their "home" staff). However, when cross-staff beaming is introduced, the notes that have been transferred to a different staff "remember" the previous notes in their "home" staff, instead of looking to the notes in the staff they were transferred to.

### Steps to reproduce

In one staff, write two of the same note, then add the same accidental to both of them by using either the up or down arrow. The accidental should not be visible on the second note. Then, select the second note and move it to a different staff using Ctrl+Shift+UP/DOWN. The accidental still isn't rendered, despite the same note not being present earlier in that staff.

### Screenshots/Screen recordings

The 8th notes were written in the LH staff and set to be beamed across the staves using Ctrl+Shift+UP.
The highlighted flat shouldn't be there. It cannot be removed, otherwise the note would play as B♮.
A workaround would be to simply hide the flat with V.
![image](https://github.com/musescore/MuseScore/assets/73259774/e151bf5c-4513-43a5-82c6-5dfd61a9da26)

The converse would be this example.
The highlighted note is a C♯, but the accidental does not appear when the note is transferred to the RH staff; it just looks like a C♮.
A workaround would be add the accidental manually, but this can be tedious and error-prone if a score has many instances of this issue.
![image](https://github.com/musescore/MuseScore/assets/73259774/15e4ebb9-2d95-4568-8ecb-11a96d274226)

### MuseScore Version

MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

No.

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
Sample score for testing (done with 3.x)
[Unbenannt.zip](https://github.com/musescore/MuseScore/files/14232092/Unbenannt.zip)
