### ISSUE TITLE
Muted Bass trombone playback is one octave too low

### ISSUE THREAD

**Issue by Zephereth** [musescore/MuseScore#21068]
### Issue type

Muse Sounds bug

### Bug description

The muted bass trombone muse sounds sound playback is one octave lower than intended.

### Steps to reproduce

1. Score with bass trombone (using Muse Sounds playback)
2. Use the mute text
3. Playback is one octave lower than it should be
4. (You can work around it by using the 8va bass clef)

### MuseScore Version

4.2

### Regression

I don't know

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
Closing as resolved, since https://github.com/musescore/MuseScore/issues/21132 which was a duplicate was closed too
