### ISSUE TITLE
Fretboard diagram settings need review

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#21088]
A number of issues exist with fretboard diagrams that need to be systematically scoped and solved (initially at the design level). 

These include:

- Orientation (Vertical/Horizontal) should be a score-wide setting (relocated from Properties to Styles)
- Option to remove the 'dangling' vertical lines at the bottom
- New option for finger numbers at the bottom of the diagram (below each string)
- Option for whether to show barre as thick straight horizontal line (as currently) or as dots connected with a curved line ('slur')
- Configurable text format for barre position ('3' or '3fr', for example)
- Option to control nut width; nut should also be drawn 'on top' of the diagram (growing upwards as it gets thicker, otherwise it encroaches into the topmost fret space
.
.
.
(Other issues to be identified and added here)

**Comment by scorster** [comment]
Here are some [.org Fretboard Diagram requests.](https://musescore.org/en/node/313074) to consider whist mulling.

Regarding the proposed Vertical/Horizontal Fretboard orientation, mentioned above, I'd like to see that implemented as a Section setting. Then we can I could have horizontal scale diagrams in one section and vertical chord diagrams in other sections. 
Use case: Illustrate scales and arpeggios in horizontal orientation on one page, with the next page showing chord chart for improvisation.

**Comment by kbrand5333** [comment]
We also need a much larger variety of diagrams to choose from (I sent a file to Simon) or a simple and shareable way to add more diagrams.  Just the C major scale root position major, minor, and 7 chords are definitely not sufficient.
