### ISSUE TITLE
Mobile App doesn’t recognize my existing subscription

### ISSUE THREAD

**Issue by MadseaOMalley** [musescore/MuseScore#21080]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

Hi, I’ve been in contact with George for the last several weeks about in this issue and still don’t have a resolution. I have a pro subscription,  but am forced to create a new account and select the trial subscription to get into the mobile app. I was charged for two subscriptions last year (with the same email/user name) so I do not want to do this again. I have videos and screen shots of my login process but still can’t use the app without selecting the trial subscription. There is no “x”

to use to close out of that trial selection screen. Please help, not having access to my subscription via the mobile app really limits my subscription’s usefulness.

### Steps to reproduce

Download and open App, select login from the “Let’a get started page”, select “continue with email” on the next page, enter email address and password and select “sign-in”. Then get a “Let’s get Started, create your account to access millions of scores” page and then get several
Profile information pages before finally getting a page on how the trial subscription works with no option to exit out without starting a subscription. 

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/157065529/bd1d8b47-f3a3-411d-a4dc-76472093c956)

### MuseScore Version

2.12.96

### Regression

No.

### Operating system

iOS 17.2.1.

**Comment by Fristover** [comment]
I think this issue doesn't belong here, this github is for the desktop notation software, not for the mobile app [IIRC the mobile app is handled by a different team more related to MuseScore.com (the score sharing website) rather than MuseScore and Musescore.org (the notation software and its website)].

**Comment by MadseaOMalley** [comment]
Thanks for letting me know - just FYI, this is what I received in response to a request for support - Visit our support forums - https://musescore.org/en/forum/6and https://github.com/musescore/MuseScore/issuesBest regards,MuseScore support team(Office hours: Monday - Saturday from 07:00 - 15:00 GMT)That’s how I ended up in GitHub. On Jan 18, 2024, at 2:27 PM, Fristover ***@***.***> wrote:﻿
I think this issue doesn't belong here, this github is for the desktop notation software, not for the mobile app [IIRC the mobile app is handled by a different team more related to MuseScore.com (the score sharing website) rather than MuseScore and Musescore.org (the notation software and its website)].

**Comment by MadseaOMalley** [comment]
I thought I had gone into the help center but I’m not seeing the option selected. I just saw a link to the iOS forum so I assume that’s where I should have gone. On Jan 18, 2024, at 3:16 PM, Casper Jeukendrup ***@***.***> wrote:﻿

just FYI, this is what I received in response to a request for support - Visit our support forums - https://musescore.org/en/forum/6and https://github.com/musescore/MuseScore/issuesBest regards,MuseScore support team

Hm... that should probably not have happened. Where/how did you submit your support request?

**Comment by MadseaOMalley** [comment]
Would you be able to tell me where I should try to get support on my issue? I haven’t gotten anywhere for 2 weeks so I’m getting a little frustrated. Thank you. On Jan 18, 2024, at 3:16 PM, Casper Jeukendrup ***@***.***> wrote:﻿

just FYI, this is what I received in response to a request for support - Visit our support forums - https://musescore.org/en/forum/6and https://github.com/musescore/MuseScore/issuesBest regards,MuseScore support team

Hm... that should probably not have happened. Where/how did you submit your support request?

**Comment by cbjeukendrup** [comment]
Unfortunately, I don't know much more than that you need to contact the MuseScore.com team for that, which you've already done as you say. I've sent them a message asking to look into this.

**Comment by MadseaOMalley** [comment]
Thank you so much!  On Jan 18, 2024, at 7:32 PM, Casper Jeukendrup ***@***.***> wrote:﻿
Unfortunately, I don't know much more than that you need to contact the MuseScore.com team for that, which you've already done as you say. I've sent them a message asking to look into this.

**Comment by cbjeukendrup** [comment]
@MadseaOMalley they ask what's your username and subscription email address on MuseScore.com :)

**Comment by MadseaOMalley** [comment]
:)) my email/username is ***@***.*** George for back to me this morning and addressed the issue appropriately!! Thank you so much for your help. On Jan 19, 2024, at 2:32 AM, Casper Jeukendrup ***@***.***> wrote:﻿
@MadseaOMalley they ask what's your username and subscription email address on MuseScore.com :)

**Comment by cbjeukendrup** [comment]
Funnily enough, GitHub redacted your email from your comment, because you replied via email instead of directly on GitHub :)

Anyway, glad to hear it got resolved!
