### ISSUE TITLE
Crash after inserting some measures using Insert key and Undo all

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#21098]
### Issue type

Crash or freeze

### Bug description

This looks like #21049  ( https://github.com/musescore/MuseScore/issues/21049#issuecomment-1896328925 ) but decided to log it separately  

### Steps to reproduce

1. Open Treble clef template
2. Select first measure
3. Press **Insert** for about 10 times
4. Undo all actions (it's better to press and hold Ctr+Z)

 

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/b375a859-3aa1-4ad5-80b1-864eba6d5901

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in **MuseScore 4.0.2**

### Operating system

Windows 10

**Comment by irwir** [comment]
> 1. Open Treble clef template

Bass clef will do the same.
4.2.0, Windows 11
Crashing due to CX being 0; could be a null object reference.

**Comment by irwir** [comment]
In my case it was necessary to insert at least 11 measures, or there would be no crash.
The attempted fix did not give any explanation for this behaviour.

**Comment by DmitryArefiev** [comment]
Fixed in #22279
