### ISSUE TITLE
Ties becoming Gigantic under certain circumstances

### ISSUE THREAD

**Issue by Grimmkiner** [musescore/MuseScore#21100]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Adding a non-tied note to a tied note makes the non-tied note have a gigantic "backwards" tie.
This tie can be moved, flexed ect.

### Steps to reproduce

1. Connect two notes with a tie
2. add a second note to the first note, making it a diad (or more - each additional note adds another huge slur)
3. Huge slurs!

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/157135277/5d71b48c-84ab-425d-a1a4-811983c7fdc4

![Screenshot 2024-01-19 152437](https://github.com/musescore/MuseScore/assets/157135277/0b3929a9-1c9a-46b9-998a-2b93a7669ad3)

### MuseScore Version

 rch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 11

**Comment by oktophonie** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/20551https://github.com/mu, sescore/MuseScore/issues/20951, https://github.com/musescore/MuseScore/issues/20665, etc.
Fixed in 4.2.1
