### ISSUE TITLE
Ignore 8va and Pedal marking during playback

### ISSUE THREAD

**Issue by ErlingIv** [musescore/MuseScore#21104]
### Your idea

Have an ignore flag (play/notplay?) for pedal and 8va markings.

### Problem to be solved

No problem, just an idea.
But for piano scores with lots of pedal settings, it is not possible to change the instrument to organ and keep the pedal settings. That sounds quite bad!
So a flag to ignore them would be useful.
And to be able to have 8va in a score to keep the original layout of a score, but change the playback would also be useful.

**Comment by Jojo-Schmitz** [comment]
Having a Play property for all line elements that influence playback (ottava, pedal, let ring, hairpins, etc.) would IMHO be a good thing.
Of course the default should be set to "on"
