### ISSUE TITLE
Musescore 4.2 Crashes due to a loop in ItemImplicationWidth

### ISSUE THREAD

**Issue by yourpizzadad** [musescore/MuseScore#21105]
### Issue type

Crash or freeze

### Bug description

Each time I open Musescore, it would have the load screen for about 4 to 10 seconds, eventually coming unresponsive. When I open the logs, it says it is because of a loop in the ItemImplicationWidth area. 

### Steps to reproduce

N/A
[MuseScore_240118_195916.log](https://github.com/musescore/MuseScore/files/13996154/MuseScore_240118_195916.log)

### MuseScore Version

4.2

### Regression

No.

### Operating system

Windows 10 64-bit

**Comment by cbjeukendrup** [comment]
I wouldn't directly draw the conclusion that this binding loop is the cause of the crash. This binding loop is there for everyone namely, and binding loops are in general not likely to cause a crash. 
To find out what _is_ causing the crash, it would be helpful if you could upload a ZIP'ed copy of your `%LOCALAPPDATA%\MuseScore\MuseScore4` folder. Besides the log files, it contains crash dumps which may contain more useful information.

**Comment by yourpizzadad** [comment]
[MuseScore4.zip](https://github.com/musescore/MuseScore/files/13998972/MuseScore4.zip)

**Comment by bkunda** [comment]
@DmitryArefiev pls investigate

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev pls investigate

I don't think I can help much here..  I can't reproduce it on my side

**Comment by DmitryArefiev** [comment]
@yourpizzadad Can you update to 4.2.1 and check again please? 

Also, if the issue still persists (in 4.2.1) can you Revert to factory settings? (Top menu>Help>Revert to factory settings)

**Comment by yourpizzadad** [comment]
Same issue. Is there a way to revert to factory settings via the command line? I tried looking at the handbook but was confused about how to do that. @DmitryArefiev 
[MuseScore_240126_033411.log](https://github.com/musescore/MuseScore/files/14064433/MuseScore_240126_033411.log)

**Comment by Eism** [comment]
I don’t see crash dumps in the sent MuseScore4 folder, which is strange

There may be a problem with the audio device
Can you run MuseScore with another device? for example, connect headphones to your machine and run MuseScore

**Comment by DmitryArefiev** [comment]
> Same issue. Is there a way to revert to factory settings via the command line? I tried looking at the handbook but was confused about how to do that. @DmitryArefiev [MuseScore_240126_033411.log](https://github.com/musescore/MuseScore/files/14064433/MuseScore_240126_033411.log)

@yourpizzadad Don't know.. 
Did you reverted factory settings in regular mode? (just clicking Top menu>Help>Revert to factory settings)

**Comment by MarcSabatella** [comment]
If the program crashes on startup, then reverting from the command line is going to be easier than using the menu :-).

As far as I know [the instructions in the Handbook](https://musescore.org/en/handbook/4/revert-factory-settings) as to how to revert to factory settings from the command line for each OS should work fine.  At which step did you encounter a problem with the steps for Windows?

Once you are able to figure out how to use the command line, you can also try using the "-s" option to disable audio and see if that works around the problem, which would help confirm if that's the source of the problem.

**Comment by DmitryArefiev** [comment]
> If the program crashes on startup, then reverting from the command line is going to be easier than using the menu :-).

Ahhh)) You're right of course!

**Comment by DmitryArefiev** [comment]
@yourpizzadad To Revert settings you can just remove:


* **MuseScore4.ini** from c:\Users\username\AppData\Roaming\MuseScore\
* and **MuseScore4** folder from c:\Users\username\AppData\Local\MuseScore\

**Comment by zacjansheski** [comment]
Closing as stale
