### ISSUE TITLE
Score playback insistently starts on last edited note on newly opened scores.

### ISSUE THREAD

**Issue by Valdessir** [musescore/MuseScore#21119]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When a score is newly opened, upon pressing play for the first time, the score will play on the last note you have inputted or edited regardless if you play from a highlighted area, or press play from the beginning. This only happens when you press play for the first time since you opened said score. Afterwards, the bug no longer happens.

### Steps to reproduce

1. Open a new score.
2. Input notes.
3. Highlight anywhere and press play, or press play from the beginning.
4. Observe how the score will play on where the last edited/inputted note is.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/102687285/1e1545aa-0bce-4bf6-8f3d-3af5545fade3

Attached to this is an OBS recording of bug reproduction.

### MuseScore Version

Musescore 4.2.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

I do not recall observing this behavior in past versions of Musescore 4, but I am certain, with confirmation by testing my copy of Musescore 3.6.2, that the behavior is not present.

**Comment by zacjansheski** [comment]
Looks like this is resolved by https://github.com/musescore/MuseScore/pull/21033
