### ISSUE TITLE
Gradual tempo changes too coarse

### ISSUE THREAD

**Issue by Panogen** [musescore/MuseScore#21115]
### Issue type

General playback bug

### Bug description

Often, gradual tempo changes such as "accel." will sound erratic and choppy due to them using overly long time intervals. This is especially noticeable with major time changes, such as when doubling the tempo over just a few bars. The interval by which the tempo changes seems to vary due to factors beyond my understanding. For example, the tempo sometimes steps on every beat; other times, on every bar. It creates somewhat of the equivalent of terraced dynamics, but for tempo changes, which is undesirable.

### Steps to reproduce

Write a couple bars of music, then input an significant gradual tempo change, such as an accelerando by 200%. It is likely that the tempo will be incremented every bar, making the change feel less gradual than it should.

### Screenshots/Screen recordings

This shows two different presentations of this issue. The first is on the stringendo starting at m. 316. The tempo increments every half a bar, or every 2 beats, since these measures are in 4/4. The second is on the accelerando starting at m. 319. The tempo here increments every bar, or every 4 beats. Pay attention to the tempo indicator on the top right.

https://github.com/musescore/MuseScore/assets/73259774/37ac057a-e5d8-42e9-8169-c8042ad688a0

I thought the discrepancy might have stemmed from accel. and string. being handled differently, so I tested them both on a fresh score. To my surprise, I found they both behaved exactly the same here and changing tempo every bar.

https://github.com/musescore/MuseScore/assets/73259774/ffa6b555-a987-42f3-bfcf-42c026e92962

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

No.

### Operating system

Windows 11

### Additional context

The projects in the two videos: [tempo.zip](https://github.com/musescore/MuseScore/files/13999691/tempo.zip)

**Comment by cbjeukendrup** [comment]
Indeed, currently gradual tempo changes are not that gradual at all, but create exactly four tempo change points... https://github.com/musescore/MuseScore/blob/b3693b37af00cdd1e8207d8f6cc4c348405aaa23/src/engraving/dom/score.cpp#L449-L452

**Comment by jeetee** [comment]
For reference: The TempoChanges plugin applied tempo changes on each segment in the range, if the change was more than a 0.1qpm difference.

**Comment by wizofaus** [comment]
Any chance this could be prioritised for 4.4? I'd be happy to contribute a PR, obviously changing the "4" is very simple, but I would think more sensible is to have the tempo change at a *minimum* every "beat" (480 ticks), and only use the step count for very gradual tempo changes over less than 4 beats.  Would have to see how it sounded in compound meters though.

**Comment by cbjeukendrup** [comment]
One "step" at least every quarter note is one option; another option would be to insert so many steps that each step is at most 10% higher/lower BPM than the previous step. Maybe using a combination of the two is even better ("so many steps that every step is at most 10% difference, but at least one per quarter note"). And maybe as an additional rule, there must be at least 4 steps in total.

If you could create a PR for that, that would be great, and depending on the timing we may also be able to include that in 4.4. 

My only concern about this issue is performance. The more steps, the more entries in TempoMap, and thus the more expensive ticks -> time conversions become. That may be a problem for playback rendering.

**Comment by wizofaus** [comment]
10% is quite a big jump though. If you had a gradual accel from say q=100 to q=180 over 10 measures I'd want tempo adjustments at least twice a measure (and preferably 4 times, I.e. 40 in total, each increasing by roughly 2 bpm). In the context of everything else the playback engine has to deal with that doesn't seem like a particularly great imposition?

**Comment by wizofaus** [comment]
It looks like it's already been changed to 6? (and now in playbackcontext.cpp). But still way too coarse.

**Comment by wizofaus** [comment]
This works pretty well:

            int totalTicks = tempoChange->ticks().ticks();
            int stepsCount = std::max(8, totalTicks / 480);
            std::map<int, double> tempoCurve = TConv::easingValueCurve(totalTicks,
                                                                       stepsCount,
                                                                       newBps.val - currentBps.val,
                                                                       tempoChange->easingMethod());

However it could definitely generate too many in some cases (particularly over very short tempo changes, e.g. over a single beat).  It sounds fine for all the cases I tested, but maybe could cause performance issues for huge scores?
I'd also say the number of tempo adjustments you need depends on what note values you've used - if there's literally only 2 1/8 notes that span the accel. and nothing else, there's not much point having 8 tempo adjustment steps.  Not very often that would happen, though you see accel. over a triplet sometimes.

**Comment by wizofaus** [comment]
[accel.mscz.zip](https://github.com/user-attachments/files/16475928/accel.mscz.zip)
Attaching test score.

**Comment by wizofaus** [comment]
Unfortunately while the changes to the functional code were quite straightforward, the change to TempoChangesDuringNotes test is not going to be, so before I commit to that, I'd like to get at least some consensus that what I've proposed is a worthwhile improvement (it's undoubtedly vastly better than what we have currently, but there are still some extreme scenarios it won't be ideal for).

**Comment by DmitryArefiev** [comment]
Fixed in #23879
