### ISSUE TITLE
Make linked tab creation more automated

### ISSUE THREAD

**Issue by jonasberlinma** [musescore/MuseScore#21111]
### Your idea

The precondition is that you are using a regular g clef staff with a linked 6 string tab staff. When adding notes to the g clef staff the notes are added to the tab, but there is no intelligence about what string to use. You always have to reorder the notes on the tab to make it possible to play. I'm not sure how it chooses the strings and fret but is seems like it could do a better job. Add a Cmaj7 chord: C-E-G-B on the g clef staff and you end up with frets 9-0-1-0 on strings 4,3,2,1, which is clearly impossible to play. The feature would look at the previous note and find an inversion in the same position or one up or one down.

### Problem to be solved

Simplifies the task of fixing the position and inversion of every chord you enter to make it playable.

### Additional context

I don't know the code base well enough yet to have an idea how to implement it, but I am trying to figure it out. If it could be done through a plugin that may be the cleanest.

**Comment by scorster** [comment]
I  can't reproduce this.

My steps in MS4.2:
• New>Solo>Guitar + Tab
• Add C-E-G-B on beat 1

![Guitar + TAB CM7 chord in linked TAB staff](https://github.com/musescore/MuseScore/assets/121324720/168629c6-5962-4cc4-b9dd-a37bf5d2d295)

**Comment by jonasberlinma** [comment]
I see. I added C and E one octave higher higher:

￼

Jonas Berlin
***@***.***
+1-857-210-4763

**Comment by jonasberlinma** [comment]
<img width="224" alt="Screenshot 2024-01-21 at 11 17 51 AM" src="https://github.com/musescore/MuseScore/assets/26146396/2b373583-6896-48ac-a65c-8f5a9ed4791e">

**Comment by jonasberlinma** [comment]
Guess it's a bit more complicated. Typing in a standard drop 2 Cmaj7:

<img width="136" alt="Screenshot 2024-01-21 at 11 53 00 AM" src="https://github.com/musescore/MuseScore/assets/26146396/bf016428-2c5e-4bd3-bfc9-2137010c9606">

the feature would make the score one of:

<img width="285" alt="Screenshot 2024-01-21 at 11 54 25 AM" src="https://github.com/musescore/MuseScore/assets/26146396/bf981003-8773-464c-bab0-5d9b35ecb301">

depending on the position the previous note was played in.

**Comment by jonasberlinma** [comment]
I'll close this for now and see if I can provide you with a better thought through feature.
