### ISSUE TITLE
Time stamp text is in wrong place in toolbar

### ISSUE THREAD

**Issue by zx2c4** [musescore/MuseScore#21113]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The text looks like this in 4.2:

![image](https://github.com/musescore/MuseScore/assets/10643/3632ddc9-f84f-404b-ad64-63ec3d4d86e8)

### Steps to reproduce

Weirdly, I don't see this with the appimage. I only see this if I build it myself. Any ideas why that might be?

### MuseScore Version

4.2

### Operating system

Linux

**Comment by cbjeukendrup** [comment]
Maybe it has to do with the Qt version you are using. For the AppImage, that is Qt 5.15.2 from Qt's own "online installer".

**Comment by zx2c4** [comment]
I'm using 5.15.12.

**Comment by bkunda** [comment]
Closing this for now as it seems to be peculiar to the build configuration. 
But happy to re-open if the issue proves to be more systemic.
