### ISSUE TITLE
Black blobs where shadow should be when compositing is disabled

### ISSUE THREAD

**Issue by zx2c4** [musescore/MuseScore#21114]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

Menus have a big black blob around them when I disable compositing in KWin/X11:

![image](https://github.com/musescore/MuseScore/assets/10643/ecb96384-3973-4970-a842-91d1d0101611)

I assume there's supposed to be a shadow rendered here. Instead, you probably shouldn't try to render a shadow when compositing isn't enabled. Or just let Qt do its own thing instead of whatever odd custom theming is happening here.

### Steps to reproduce

Open a menu.

### MuseScore Version

4.2

### Regression

No.

### Operating system

Linux

**Comment by cbjeukendrup** [comment]
I think this is a duplicate of #15399, isn't it?

**Comment by zx2c4** [comment]
Yes, thanks.
