### ISSUE TITLE
Playback Cursor Makes Dots behind Dotted Notes Vanish (Tabs only)

### ISSUE THREAD

**Issue by moontan** [musescore/MuseScore#21120]
### Issue type

General playback bug

### Bug description

During playback, dots behind notes disappear when the cursor passes them.

### Steps to reproduce

1. Create a few dotted notes in a bar or two on tablature staff (or open  [tabs with dots.zip](https://github.com/user-attachments/files/16614677/tabs.with.dots.zip))
2. Start playback from the beginning of the first of these bars.
3. Watch the dots get wiped out one by one and reappear either when playback stops or when focus is changed.

### Screenshots/Screen recordings

https://youtu.be/pxpDgNBVunU

### MuseScore Version

4.2.0-233521125 (64 bit), revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

MacOS 13.6

**Comment by bkunda** [comment]
Seems like a further instance of https://github.com/musescore/MuseScore/issues/20608 and https://github.com/musescore/MuseScore/issues/19885

**Comment by cadiz2** [comment]
Reported again: https://musescore.org/en/node/361269

**Comment by DmitryArefiev** [comment]
Still happens in **4.4**. Occurs only on tablature staves


https://github.com/user-attachments/assets/4416cfbc-de4a-4cb4-ad34-5faf2ed5a662

**Comment by DmitryArefiev** [comment]
Fixed in #24576
