### ISSUE TITLE
Add option for double barlines before key signature and time signature changes

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#21127]
### Your idea

Add options for when a key signature or time signature change should cause the preceding barline to become a double barline, automatically (assuming it isn't already another type, like a repeat), with options:
- never
- always
- only at end of system [perhaps more accurately, 'only before a cautionary at the end of a system' - which is MuseScore's current behaviour for key signatures; if the cautionary is turned off, the double barline also becomes a single]

Naturally it should remain possible to override this in any specific case by explicitly changing the barline.

**Comment by DaddyLudwig** [comment]
I would very much appreciate this. May be a very small thing, but small things add up, so this would definitely save some time for me with my transcriptions vs what I currently do adding all the double barlines manually. Especially in operas and Romantic Era pieces where I often see mid-section changes.

**Comment by XiaoMigros** [comment]
I'd like to tackle this

**Comment by oktophonie** [comment]
I was sure this already existed. Must look harder
