### ISSUE TITLE
Articulations on barline causes crash / isn't loaded

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#21121]
### Issue type

Opening/saving issue

### Bug description

When opening a file which contains an articulation on barline, MuseScore 4.2.0 crashes.
MuseScore 4.2.1 doesn't load such articurations.

This is a minimal sample file which contains l.v. symbol applied to the first barline. 
[Untitled score.zip](https://github.com/musescore/MuseScore/files/14001667/Untitled.score.zip)

### Steps to reproduce

1. In MuseScore 4.1.1 or earlier, create a file containing an articulation applied to barline.
2. Open it with MuseScore 4.2.0. MuseScore crashes.
3. Open it with MuseScore 4.2.1. Crash doesn't happen, but the articulation disappears.

### MuseScore Version

MuseScore 4.2 and later

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
The crash is fixed in 4.2.1 indeed, but support for articulations on barline may come later - see https://github.com/musescore/MuseScore/issues/20945

**Comment by Jojo-Schmitz** [comment]
So it is a duplicate (of the remaining issue from #20945)
