### ISSUE TITLE
Single voice parts for non-first voice 'corrupt' when deleting rest in main score

### ISSUE THREAD

**Issue by randoguyname** [musescore/MuseScore#21137]
### Issue type

File corruption

### Bug description

When deleting rests of voice 2 (and presumable other voices apart from the first) on a main score, a part score that solely contains voice 2 'corrupts', saying that there is an 'empty bar'.

### Steps to reproduce

1. Create a new score
2. Add a part score which only shows Voice 2
<img width="290" alt="Screenshot 2024-01-22 at 2 51 06 pm" src="https://github.com/musescore/MuseScore/assets/43623624/55b334f2-660d-4830-aa51-e8230106af2e">

3. Write some notes in voice two then delete the entire bar (on main score)
<img width="1552" alt="Screenshot 2024-01-22 at 2 51 35 pm" src="https://github.com/musescore/MuseScore/assets/43623624/341bce74-d688-4903-8938-54aed3eeb93e">

<img width="1552" alt="Screenshot 2024-01-22 at 2 51 47 pm" src="https://github.com/musescore/MuseScore/assets/43623624/0188a8b9-859b-4a43-9cfc-eb526150dc24">

4. Observe empty bar in part score
<img width="1552" alt="Screenshot 2024-01-22 at 2 51 54 pm" src="https://github.com/musescore/MuseScore/assets/43623624/184171ee-d257-46c4-a572-80f91f11a304">

5. Attempt to save and see this warning
<img width="795" alt="Screenshot 2024-01-22 at 2 56 31 pm" src="https://github.com/musescore/MuseScore/assets/43623624/692c095f-5f13-4d83-96d0-e1ce0f7fee69">

### MuseScore Version

OS: macOS 14.2, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

macOS 14.2.1

**Comment by randoguyname** [comment]
I will also add this workaround: delete the bar only in the part score and hide the rest on the main score.

**Comment by oktophonie** [comment]
See also: https://github.com/musescore/MuseScore/issues/19182

**Comment by cbjeukendrup** [comment]
@mike-spa This issue is assigned to me, but isn't this exactly what you were working on recently?

**Comment by mike-spa** [comment]
Yes, indeed it is possible that this may be fixed by #23783. @oktophonie could you please also check for this while testing that PR? In any case, I'll reassign this to me
