### ISSUE TITLE
Adding Muted sounds for musebrass

### ISSUE THREAD

**Issue by s11141827** [musescore/MuseScore#21146]
### Your idea

I've wanted to add the Muted sounds in Musebrass so that way it would sound like you're using a mute

### Problem to be solved

Another problem to solve is the muted playing technique when using it w/ Brass instruments.

**Comment by MarcSabatella** [comment]
Brass mutes have been supported since Muse Sample 0.5 a month or so ago.  Check you version from within MuseScore via Diagnostic / Muse Sampler, and if it's older than that, fire up Muse Hub and update.

**Comment by s11141827** [comment]
Right

**Comment by s11141827** [comment]
Yes but I've gotta find a way to make sure it truly works

**Comment by MarcSabatella** [comment]
It does truly work.  If you need help figuring out how to add the mute notation from the palettes - or with any other aspect of using MuseScore - please ask on the official Support forum on musescore.org

**Comment by s11141827** [comment]
Thanks, I will!

**Comment by s11141827** [comment]
Mutes & Brass Instruments always sound Amazing together.

**Comment by s11141827** [comment]
I was able to update musesampler & Boom now I have Muted sounds on the Musesounds Brass Instruments.

**Comment by s11141827** [comment]
> Brass mutes have been supported since Muse Sample 0.5 a month or so ago. Check you version from within MuseScore via Diagnostic / Muse Sampler, and if it's older than that, fire up Muse Hub and update.

I got muse sampler updated to 0.5.1 & now I have the muted sounds.

**Comment by s11141827** [comment]
Awesome, thanks for the update!
