### ISSUE TITLE
Crash when trying to extend an underscore from syllable attached to a rest

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#21143]
### Issue type

Crash or freeze

### Steps to reproduce

1. Open [crash_short.zip](https://github.com/musescore/MuseScore/files/14012175/crash_short.zip)
2. In measure 4, extend underscore from 'Re' (Shift+-)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/607452df-f11c-4b69-ae31-1739585c7628

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
In Mu3 nothing happens, no crash but also no added melisma.

**Comment by zacjansheski** [comment]
FIXED by https://github.com/musescore/MuseScore/pull/21877
