### ISSUE TITLE
Align endpoints of 'floating' ties in tab staves where possible

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#21140]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When 'outside' style chord ties are on, and 'show ties only' is on for tab staves, the endpoints of ties should align when there is no reason not to.

Current:
![image](https://github.com/musescore/MuseScore/assets/20604032/26c18ebe-c5b4-4c35-99ed-9a67c4c80124)
(the inner ties are, in effect, adjusting for fret marks that aren't actually there).

Better:
![image](https://github.com/musescore/MuseScore/assets/20604032/6de4de8e-2d01-4f74-965d-86bf22d0f285)

Even when 'inside' style ties are on, hanging ends of ties can be further 'in', that is, they similarly don't have to adjust outwards for fret marks that aren't shown. Current:
![image](https://github.com/musescore/MuseScore/assets/20604032/2f6081b8-aa43-4588-a1d9-1df08405ddac)

Better:
![image](https://github.com/musescore/MuseScore/assets/20604032/bbebef6c-2a64-4f10-b222-fb8db862b773)
(this will also apply to single notes with 'inside' ties)

### Steps to reproduce

.

### MuseScore Version

master

### Regression

No.

### Operating system

Any

**Comment by abariska** [comment]
🟢 FIXED
Tested on macOS 13
