### ISSUE TITLE
[REPEATS] Dynamics sound at the wrong time when toggling "Play repeats" (when unchecked)

### ISSUE THREAD

**Issue by yoavshati** [musescore/MuseScore#21152]
### Issue type

General playback bug

### Bug description

It seems like the dynamics' placement in time doesn't recalculate when toggling between playing and not playing repeats.
In the video I used MuseSounds, but this bug appears in MS Basic. I also only had one repeated measure, but if I had more (either in the same repeated section or in different places) they would also add to the dynamics coming in early/late.
Causing the sound engine to recalculate the dynamics' locations fixes this until the next time you toggle the repeats, as seen in the video when I removed and replaced a dynamic mark

### Steps to reproduce

1. Create a score with a dynamic mark and at least one repeated measure before it
2. Should sound correct
3. Toggle "Play repeats" in the playback menu or using a custom keybind
4. The dynamic sounds in the wrong place

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/40692715/13eb2d27-759b-44a5-857d-565371c0d31e

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

Worked in **4.0.2**

### Operating system

Windows 11

### Additional context

#22862 - similar issue and should be rechecked after fix

**Comment by DmitryArefiev** [comment]
Fixed in #23671
