### ISSUE TITLE
Musescore4 crashes when "limit scroll to page borders" is activated

### ISSUE THREAD

**Issue by HarrieGeboers** [musescore/MuseScore#21159]
### Issue type

Crash or freeze

### Bug description

When you activate "limit scroll area to page borders" in combination with a vertical page scroll (in "Preferences" > "Canvas"), if you click on "Pubish" Musescore4 will crash. Aften you've disabled "limit scroll area to page borders" the issue is gone.

### Steps to reproduce

1. In Score view, go to preferences>canvas
2. activate Vertical page scroll and "limit scroll area to page borders", click OK
3. In Score view, click on "Pubish" (to open that view)
4. Musescore4 crashes immediately (maximize window if it doesn't crash on step 3)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/24f3aea8-0588-436c-bc23-c50bc3a71d21

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

No

### Operating system

Windows 11

### Additional context

[crashlog.zip](https://github.com/musescore/MuseScore/files/14021217/crashlog.zip)

**Comment by DmitryArefiev** [comment]
Fixed in #21425
