### ISSUE TITLE
Child elements are not visibly selected in range selections

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#21175]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

Some score elements have multiple objects that can be individually positioned (i.e. in guitar bend in tablature, the note that is bent to, or the chord symbol attached to fret diagrams).

When a measure containing one of these elements is selected, the "parent" object is shown in the selected color but the "child" object is not. Both should appear selected.

### Steps to reproduce

1. Add a fret diagram to a score
2. Click on the measure it is attached to
3. See that the fret diagram itself is blue, but the chord symbol is not

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/20806406/74bb93da-c28b-49b7-b5e1-401e23aa891b

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

OS: macOS 14.1, Arch.: x86_64

**Comment by mathesoncalum** [comment]
Looks similar to #18187, I Imagine the fix will be somewhat similar too.
