### ISSUE TITLE
MS4 ignores musicxml property <notehead>none</notehead>

### ISSUE THREAD

**Issue by MortenHe** [musescore/MuseScore#21187]
### Issue type

Import/export issue

### Bug description

I created the scrore Invisible.mscz where the third note in the first bar is set to invisible. After exporting it to Invisible.musicxml this note has the tag none.
When opening the musicxml file in Musescore again all 4 notes are visible.

It seems to me like this tag is ignored during import?

### Steps to reproduce

1. Create a score with invisible notes and save it as musicxml
2. When opening the musicxml file that invisible notes are visible again.

### MuseScore Version

4.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 Pro

**Comment by XiaoMigros** [comment]
@MortenHe can you test #21189? Should be fixed there. [Here's how to run test builds](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds)

**Comment by MortenHe** [comment]
Yes, it works. Thank you very much!
The only thing is that the stem is still visible, but I think I can solve this by editing the musicxml

**Comment by Jojo-Schmitz** [comment]
That's the Todo on the code...

**Comment by XiaoMigros** [comment]
If you make a new issue for it then maybe...

**Comment by MortenHe** [comment]
Sure! 👏
