### ISSUE TITLE
Cannot update Muse Sampler to 0.5

### ISSUE THREAD

**Issue by Skye-ey** [musescore/MuseScore#21183]
I am using Musescore 4.2.0, and have the new guitar sounds downloaded. However, my Muse Sampler refuses to update. When checking Muse Sampler within the Musescore 4 app, it says "Muse Sampler library is detected, version 0.4.1". When opening Muse Hub for the first time after turning my computer on, a popup says "Unable to uninstall Muse Sampler", followed by a popup saying "Unable to install Muse Sampler", followed by a popup saying "Unable to download Muse Sampler". When I check for updates within the Muse Hub settings, it tells me that everything is up to date. How do I fix this?

**Comment by MarcSabatella** [comment]
This seems to happen on certian systems for reasons I don't think anyone understands yet.  Uninstall/reinstall of Muse Hub may solve it.  Or you might be able to find and delete just the Muse Sampler itself.

For further assistance, please ask on the MuseScore support forum at musescore.org, or the Muse Hub support site at musehub.zendesk.com.  I am not seeing discussion of this on Zendesk yet, so I'm guessing you'll have better luck getting suggestions on musescore.org.

**Comment by bkunda** [comment]
Yes this seems like an issue on the MuseHub side. Please follow @MarcSabatella's suggestions for advise from the MuseHub team.
