### ISSUE TITLE
MuseScore freezes when opening score

### ISSUE THREAD

**Issue by yucongj** [musescore/MuseScore#21185]
### Issue type

Crash or freeze

### Bug description

I was able to open [this score](https://musescore.com/user/4887176/scores/6368039?share=copy_link) in 4.0.0, but after I upgraded MuseScore to 4.2.0, it failed to open it. The program froze when I tried to open the score using 4.2.0.

The score was created in MuseScore 3.5.

### Steps to reproduce

1. Go to [this score on MuseScore](https://musescore.com/user/4887176/scores/6368039?share=copy_link), and download the score in the Musescore format.
2. Open this score on MuseScore 4.2.0.

### MuseScore Version

4.2.0, 4.2.1

### Regression

Yes, this used to work in MuseScore 4.0.x and 4.1.x

### Operating system

macOS 14.1.1

**Comment by oktophonie** [comment]
Sadly, opening it in 4.1.1 and saving it doesn't help either - it'll still hang when opening in 4.2.x.

**Comment by Jojo-Schmitz** [comment]
Same when saving with 3.6.2
