### ISSUE TITLE
Adding an octave doesn't work

### ISSUE THREAD

**Issue by turion** [musescore/MuseScore#21197]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Adding an octave with Alt+8 doesn't work, while all other intervals (Alt+7, Alt+9) work. This used to work in Versions 2 I believe, but is broken since 3. (But the "Regression" drop down doesn't give this option.) I have no keyboard shortcuts defined. Reproducible on fresh installs in the same operating system.

### Steps to reproduce

1. Enter any note
2. Press Alt+8
3. Nothing happens

### MuseScore Version

4.1.1

### Regression

No.

### Operating system

NixOS 23.05

### Additional context

This is what `mscore` outputs when I start it from the console and press alt+7, alt+8, alt+9. In all other contexts, the key 8 works.

```
18:01:57.251 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: interval7
18:01:58.805 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: undo
18:02:10.820 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: interval9
18:02:16.493 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: undo
```

**Comment by MarcSabatella** [comment]
This works fine for me on Debian running the 4.2.1 AppImage, with a US QWERTY keyboard layout.  So, first step, update to 4.2.1.  In doing so, be sureto download the official AppImage and not any third party build as those often have issues.

Then if you continue to have trouble, go to Edit / Preferences / Shortcuts, find the octave command, and reset it (even if it *appears* to be set to the default Alt+8.  Then try the command again.  If that still fails, go back and this time try defining a *different* shortcut.  If that succeeds, this suggests to me your OS may be reserving Alt+* for some reason.

**Comment by turion** [comment]
> Then if you continue to have trouble, go to Edit / Preferences / Shortcuts, find the octave command, and reset it (even if it appears to be set to the default Alt+8.

I tried this, it doesn't work. Entering Alt+8 in that situation has no effect.

> If that still fails, go back and this time try defining a different shortcut. If that succeeds, this suggests to me your OS may be reserving Alt+8 for some reason.

This succeeded in fact, thanks! I couldn't find out what captures this shortcut, but now with your input I'm guessing it can't be musescore.
