### ISSUE TITLE
MS 4.2.1: last tied note sounds again in guitar w/distort or overdrive

### ISSUE THREAD

**Issue by handrews** [musescore/MuseScore#21195]
### Issue type

General playback bug

### Bug description

Last tied note sounds again in guitar with distort or overdrive.

### Steps to reproduce

* Use the standard electric guitar instrument
* Apply either "distort" or "overdrive" from the guitar pallette
* Add tied notes (either a single tie, or a series of ties)
* Play, and hear that the last note in the tie series sounds as if it were not tied

I have uploaded [a minimal score showing the issue](https://musescore.com/user/59723386/scores/14084380/s/kMZxQl).

### MuseScore Version

OS: macOS 12.6, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in **MuseScore 4.2.0**

### Workaround

Disable Play for the last tied note in Properties https://github.com/musescore/MuseScore/issues/21195#issuecomment-1908797969

### Operating system

MacOS 12.6, Apple Silicon M1.  But also in online cloud playback

**Comment by MarcSabatella** [comment]
I can confirm this seems broken currently, using MS Basic.  Odd, in that this had been the case all along (https://github.com/musescore/MuseScore/issues/16968) but was supposedly fixed before 4.2, and I thought I remembered confirming it.  Was it fixed and then broken again?

Using Muse Sounds, "distort" has no effect at all - see https://github.com/musescore/MuseScore/issues/20791

**Comment by handrews** [comment]
@MarcSabatella I just checked, and it was broken in 4.1.1 but fixed in 4.2.0 (and now broken in 4.2.1).

**Comment by MarcSabatella** [comment]
Confirmed - easy come, easy go!  Workaround: disable Play for the last tied note.

**Comment by DmitryArefiev** [comment]
Previously was logged as #16968

**Comment by NicolaRulli** [comment]
Just a thing - the "overdriven" text has the effect of making the last tied note play again EVEN on instruments where it doesn't have an intended effect to  begin with (I used it on bass)

**Comment by handrews** [comment]
@NicolaRulli Oh that might explain why some of the tied bass notes in one of my scores keep sounding!  I had not yet tracked down what causes it but I think I put "distort" on that part at some point (presumably the same effect as "overdriven" since both have this problem with guitar).
