### ISSUE TITLE
Exporting Mp3

### ISSUE THREAD

**Issue by megelisofon** [musescore/MuseScore#21196]
### Issue type

Import/export issue

### Bug description

When I try to export MP3 files of 2 or more parts in one combined audio file, I'm not given the option: I only see export each selection as individual files. I'm not sure how to fix this - I'd love to use these as practice tracks for my choir, which would need to include the piano accompaniment along with their specific part. I've attached a screenshot below.

### Steps to reproduce

1. file

2. export

3. mp3

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/157036584/8a6800de-513a-40f9-8bcb-28732a082d99)

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
To export a file containing specific instruments, create a custom part (within the Parts window - see button on main toolbar) and add whatever instruments you want to it, then export that.  Or use the Mixer to mute tracks as desired in the main score and export that.

In the future, lease use the Support forum on musescore.org when asking for help using MuseScore.  Then if something is confirmed to be a bug or a missing feature, you can open an issue here on GitHub.

**Comment by megelisofon** [comment]
Thank you for your reply - I tried MuseScore forums, but struggled to find what I was looking for. When I reached out to customer support, they suggested I look here.

**Comment by MarcSabatella** [comment]
To be clear, the forums *are* the support offered for MuseScore.  If you don't find an existing thread there that answers your question, then start a new thread there.  I assume you must have contacted the support team for the score-sharing website musescore.com, but that's *only* for that website (and their mobile apps), not for MuseScore itself.

**Comment by bkunda** [comment]
Yes, the mixer is definitely one of the easiest ways to achieve this.
Closing for now as this is not really a bug.
