### ISSUE TITLE
MS4 Stem invisibilty is ignored when importing musicxml

### ISSUE THREAD

**Issue by MortenHe** [musescore/MuseScore#21193]
### Issue type

Import/export issue

### Bug description

When making a note inivisible (notehead + stem) and exporting it to musicxml the note is visible again when re-importing the musicxml.
The notehead part has alreday been fixed by https://github.com/musescore/MuseScore/issues/21187
The stem is still visible on import.

### Steps to reproduce

1. Create a score with an invisible note (notehead + stem)
2. Export as musicxml
3. Import musicxml -> stem is visible

### MuseScore Version

4.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 Pro

**Comment by Jojo-Schmitz** [comment]
Not a Mu3 regression, the same Todo in the code there

**Comment by MortenHe** [comment]
Sorry, I didn't know that it was already an issue in Mu3

**Comment by rettinghaus** [comment]
Another problem here is that MuseScore differentiates between chords with invisible stems and without stems. If the MusicXML says `<stem>none</stem>` I'd guess it means a chord without a stem?

**Comment by Jojo-Schmitz** [comment]
Yes, IMHO the entire concept of invisible elements is unknown in MuscXML
