### ISSUE TITLE
Play Panel Tempo override field resists 58%

### ISSUE THREAD

**Issue by jeetee** [musescore/MuseScore#21201]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Tempo % field only accepts 58% the 2nd time you enter it.
Witnessed both on MacOS and Windows in MS4.2(.1)

### Steps to reproduce

1. Undock the play panel to be able to access the Tempo % field
2. Click into the % text field
3. Type 58 and hit enter/return to confirm
Bug: Tempo slider + value in field are changed to 57

4. Type 58 again and hit enter/return to confirm
Tempo slider and field now accept the value of 58

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10, MacOS

**Comment by bkunda** [comment]
Wow. Amazing work identifying this one 😅.
I can't promise it's a high priority, but a worthy one to raise nevertheless!

**Comment by jeetee** [comment]
Due to the very limited impact it might be a good first community issue.

**Comment by vashutangri** [comment]
Interestingly the tempo does change to what the 58% is but it shows 57%. For example, if the tempo is 200 and I put 58% then the field shows 57% but the tempo value does actually change to 116.

**Comment by vashutangri** [comment]
> Interestingly the tempo does change to what the 58% is but it shows 57%. For example, if the tempo is 200 and I put 58% then the field shows 57% but the tempo value does actually change to 116.

So the issue is basically in the view of tempo slider. Somewhere in the snippet 
```
        TempoSlider {
            width: playbackActions.width - 12
            visible: root.floating
            value: playbackModel.tempoMultiplier

            onMoved: function(newValue) {
                playbackModel.tempoMultiplier = newValue
            }
        }
```
But I'm unable to find any logical inconsistencies here since the slider is working for the rest of the values. @jeetee @cbjeukendrup @bkunda Mentor, would love any hints as to what I might be missing? Thanks :)

**Comment by re1san** [comment]
I think this issue is related to how floating point numbers are represented internally in binary. For example in the video below when I am scrolling up and down on the slider the values set on slider are not exact multiples of 0.05(stepSize of the slider). And then the value in text field is set as integral part of slider.value * 100.

https://github.com/musescore/MuseScore/assets/105774228/c6a84372-6f83-410b-bac2-0bb182b89b78

Taking the ceiling value should correct this ig.

**Comment by LeulProgramming** [comment]
I also had no idea you could edit that percentage. Interesting!

**Comment by cwasserman1** [comment]
is this fixed?

**Comment by jeetee** [comment]
> is this fixed?

No, the status is still open, as you can see on top of this issue..

**Comment by re1san** [comment]
@cwasserman1 I have made a PR that fixes this, waiting for the review :)
