### ISSUE TITLE
Flatpak update to version 4.2.1 fails

### ISSUE THREAD

**Issue by KelvinNovais** [musescore/MuseScore#21226]
### Issue type

Other type of issue

### Bug description

When opening the app and there's an update available, it pops up a window asking if the user wants to update. 
When clicking to update, MuseScore tries to install the new version, and relaunches.

The problem is that it pops up the update window again, and never successfully installs.

As far I know, Flatpak won't let the app change its root files that are needed to update; so, this kind of update/pop up should be omitted from Flatpak installations, and the updates handled by the Flatpak.

### Steps to reproduce

1. Open the app;
2. After the window to update appears, click on "Install update";
3. Wait for app ask to restart;
4. Open it again - it will ask again for the update.

### MuseScore Version

4.2.0

### Regression

I don't know

### Operating system

Fedora 37

**Comment by MarcSabatella** [comment]
I'm not sure how Flatpak normally handles updates, but that's probably something to report to those folks.  However, a similar issue exists for the official AppImage as well - the in-app update doesn't really work.  But the AppImage supports the "update" command-line option which does work nicely.

**Comment by Alexander-Wilms** [comment]
I think one could trigger the update by running `flatpak-spawn --host flatpak update org.musescore.MuseScore`

**Comment by s11141827** [comment]
> I think one could trigger the update by running `flatpak-spawn --host flatpak update org.musescore.MuseScore` from inside the sandbox.

Great idea

**Comment by KelvinNovais** [comment]
By running `flatpak-spwan --host <command>`, you run that command on the host operating system, right?
Here are the results:
```shell
❯ flatpak run --command=/bin/bash org.musescore.MuseScore
[📦 org.musescore.MuseScore ~]$ flatpak-spawn --host flatpak update org.musescore.MuseScore
Portal call failed: org.freedesktop.DBus.Error.ServiceUnknown
[📦 org.musescore.MuseScore ~]$ 
exit
```
It seems MuseScore doesn't needs/use a D-Bus connection (I'll let to developers say).
![image](https://github.com/musescore/MuseScore/assets/83086622/7a52c9c6-6118-46bc-b595-808a3a4dafbc)

But, if the command was successfully executed?
```shell
❯ flatpak update org.musescore.MuseScore
Looking for updates…

Nothing to do.
```
No updates for MuseScore package. Moreover, if there are flatpak updates available, they are handled automatically by the OS software store.
In my opinion, if the packager (AppImage/Flatpak) already supplies an updater, this kind of message could be omitted.

_Here it's an opportunity to say: thanks for this great app!_

**Comment by s11141827** [comment]
> By running `flatpak-spwan --host <command>`, you run that command on the host operating system, right? Here are the results:
> 
> ```shell
> ❯ flatpak run --command=/bin/bash org.musescore.MuseScore
> [📦 org.musescore.MuseScore ~]$ flatpak-spawn --host flatpak update org.musescore.MuseScore
> Portal call failed: org.freedesktop.DBus.Error.ServiceUnknown
> [📦 org.musescore.MuseScore ~]$ 
> exit
> ```
> 
> It seems MuseScore doesn't need/use a D-Bus connection (I'll let to developers say). ![image](https://private-user-images.githubusercontent.com/83086622/299966705-7a52c9c6-6118-46bc-b595-808a3a4dafbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODA2MjMsIm5iZiI6MTcwNjI4MDMyMywicGF0aCI6Ii84MzA4NjYyMi8yOTk5NjY3MDUtN2E1MmM5YzYtNjExOC00NmJjLWI1OTUtODA4YTNhNGRhZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE0NDUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwODg5M2ZkNjljNzZiOGMyMDNhMjBkNjNmNjRhYmMwZjU0YzBlZTY2ZmU4YTRiNmYwMWRkN2YwYjczNzZiMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j60r0lMwIMtf56GWE2r3_qk_Us5q_vHhJ6ahK8fUYa4)
> 
> But, if the command could be successfully executed?
> 
> ```shell
> ❯ flatpak update org.musescore.MuseScore
> Looking for updates…
> 
> Nothing to do.
> ```
> 
> No updates for MuseScore package. Moreover, if there are flatpak updates available, they are handled automatically by the OS software store. In my opinion, if the packager (AppImage/Flatpak) already supplies an updater, this kind of message could be omitted.
> 
> _Here I have the opportunity to say: thanks for this great app!_

I think that's good

**Comment by charlesneimog** [comment]
Flatpak will update when https://github.com/flathub/org.musescore.MuseScore updates the build. This is not an error of Musescore.

**Comment by shoogle** [comment]
> it pops up a window asking if the user wants to update.

The Flatpak is distributed via [flathub.org](https://flathub.org/) so it probably shouldn't be checking for updates from [musescore.org](https://musescore.org/).

The Flatpak maintainer should be able to disable the checks by setting the CMake option [`-DMUE_BUILD_UPDATE_MODULE=OFF`](https://github.com/musescore/MuseScore/blob/940f5ce4c83c9168e3be0e1509664a7abffcf9e8/CMakeLists.txt#L111) within the Flapak build scripts. If you're the Flatpak maintainer and this doesn't work for you, feel free to reopen this issue.
