### ISSUE TITLE
Corruption warning says unable to save, bad measure duration, manually undo changes

### ISSUE THREAD

**Issue by NicolaRulli** [musescore/MuseScore#21234]
### Issue type

Opening/Saving issue

### Bug description

Twice in a score I've had it: inability to save due to a warning that one or several bars were shorter than their nominal value (ie, 3/4 time signature, but the program only finds 2/4), yet looking at the affected measures they appear to have the correct amount of content. Selecting the whole measure and deleting its content removes the issue and allowed saving again.

### Steps to reproduce

It happens randomly, the only reoccurring elements were:
1. same score
2. both instances had more than one voice of content
3. both instances had one or more voices filled with slashes
4. one instance certainly had invisible elements, maybe the other too
[La Gran Banda-2.zip](https://github.com/musescore/MuseScore/files/14066370/La.Gran.Banda-2.zip)

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 10 home x64

**Comment by MarcSabatella** [comment]
I am able to save this score with no corruptions reported.  Please give the precise steps to reproduce the issue.

**Comment by krasko78** [comment]
4.2.1 is out, why not upgrade? :)

**Comment by NicolaRulli** [comment]
@krasko78 I have upgraded, but I have seen no other mention of this issue on here so I imagine it hasn't been fixed, or at least not intentionally. And since the bug happened in 4.2, that's what I write in the report.

@MarcSabatella sadly there are no more known steps. I said above what I know to be the specific shared characteristics of the bars that triggered it, that's all I could gather. Also, since it prevents saving, it's not a bug I can provide a project file for, because any file I upload is going to be one I managed to save. and thus either pre-bug or post-deleting the offending bar. Maybe something could be found in the log, but even that might be asking too much.

**Comment by NicolaRulli** [comment]
Anyway if it happens again I will copy the precise error message, try to export a MIDI, screenshot the offending bars, switch views, whatever.

**Comment by MarcSabatella** [comment]
More useful than any of that will be steps to reproduce the problem, starting from an uncorrupted copy of the file.  As in:

1. load the uncorrupted score
2. (do stuff)
3. save

If you can find the steps that lead to the corruption, that's really what's needed here.  Merely knowing that a corrupt score exists isn't very useful in itself most of the time.  But if it does happen again, it certainly;y wouldn't *hurt* to attach the corrupted score (don't fix it; just save anyway) and your best recollection as to what the most recent edits you had performed are.

Realsitically, until you have it down to precise steps, it's really better to discussion and brainstorm in the forums on msuescore.org. and then only open an issue here once others have confirmed they can reproduce the problem with the score and steps provided.

**Comment by NicolaRulli** [comment]
Ok, got it

**Comment by bkunda** [comment]
Closing this for now as it appears non-reproducible. 

Let's of course re-open it if reproduction steps can be identified.
