### ISSUE TITLE
Random individual chord symbols, hairpins, dynamics, rehearsal marks missing from parts

### ISSUE THREAD

**Issue by NicolaRulli** [musescore/MuseScore#21232]
### Issue type

Engraving bug (incorrect score rendering)

### Steps to reproduce

1. create a score with more than 1 instrument (I didn't check if it happens with a single instrument)
2. place chords, hairpins, dynamics, or rehearsal marks
3. open a part
Approximately 1 in 8 chords and 1 in 2 of the other types will be missing.

### Screenshots/Screen recordings

Open this score, go to the "parts" menu from the toolbar, and open any of the instruments that aren't trumpet, trombone, drums (because I manually fixed/half-fixed those)
[La Gran Banda-2.zip](https://github.com/musescore/MuseScore/files/14066052/La.Gran.Banda-2.zip)

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521124, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

Windows 10 home x64

**Comment by oktophonie** [comment]
Closing in favour of https://github.com/musescore/MuseScore/issues/21286, but thanks for the attached score here which we will use for investigation.
