### ISSUE TITLE
Make playback of bends disabled by default (or able to be set disabled by default) until they're fixed

### ISSUE THREAD

**Issue by NicolaRulli** [musescore/MuseScore#21238]
### Your idea

Bends, scoops, falls, plops, doits, slides in and out from above and below all are currently unusable in terms of playback, starting too early and making the target note extremely short. I saw that the fix is currently planned for 4.4, which I imagine will take a year approximately if not more? Wouldn't it be better to straight up have them disabled until then, instead of having the users disable each one individually every time they use them?

### Problem to be solved

Having to disable playback of the broken bend system for every individual instance

**Comment by MarcSabatella** [comment]
I strongly disagree, many bends work fine and users shouldn't be punished for using them.

Meanwhile, if you'd like to disable all of yours, no need to do it one at a time, just select them all and doit it all at once.

**Comment by NicolaRulli** [comment]
To select them all one must have already written them all, so it's not an option for works in progress. As for many bends working fine, in ms4 I've only heard guitar-style bend notation and glissandi sometimes work correctly. All the others are always wrong.

**Comment by MarcSabatella** [comment]
You can select all similar at any time during your work in progress.

Falls and doits generally work fine, same for slides.  Scoops and plops have issues as reported in https://github.com/musescore/MuseScore/issues/18265.

If you want a bend that defaults to not playing, simply customize one and add it back to your palette.

**Comment by NicolaRulli** [comment]
I apparently must have missed some customisation options, then. I'll look into that. I had assumed that, since the "Play" option didn't have the little **s** button to "set as default" next to it, no such thing could be done.

**Comment by MarcSabatella** [comment]
I just mean, add a bend to your score, disable Play, then Ctrl+Shift+drag it back to your palette for easy reuse.  Then you'll always have a choice when adding a bend whether it plays by default or not, simply by choosing the appropriate palette element.

For further questions about how to use MsueScore, please use the Support forum on musescore.org.
