### ISSUE TITLE
Invisible line formatting issues

### ISSUE THREAD

**Issue by Isywsy** [musescore/MuseScore#21247]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

'cresc.', 'dim.', 'rit.' etc. with the line hidden still adjusts vertically as if the line was still shown. When you manually adjust this it appears fine but as soon as the score refreshes from any change or reload it resets back.

### Steps to reproduce

Add a dim. over a couple bars, with some high notes above the stave in the second bar.
Deselect 'Show line'.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/25776851/02207185-79f8-4002-8878-947acd9ad94e)

### MuseScore Version

4.2.1.240230937

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

Probably linked to https://github.com/musescore/MuseScore/pull/20930

**Comment by oktophonie** [comment]
Indeed broken in 4.2.1:
![image](https://github.com/musescore/MuseScore/assets/20604032/85109471-00dd-4e62-b836-d1426d9059e3)

Differently broken in master:
![image](https://github.com/musescore/MuseScore/assets/20604032/0411bffd-0d2d-41db-ba8f-51609bfa46a5)
