### ISSUE TITLE
How do I install MuseSounds/Muse Sounds Manager on Arch-Based Linux?

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [musescore/MuseScore#21258]
### Issue type

Muse Sounds bug

### Bug description

Bottom text

### Steps to reproduce

None of the links/tutorials i've seen point to a currently working solution.

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Manjaro

### Additional context

Do you think the choices you've made in life will lead to a regrettable existence?

**Comment by MarcSabatella** [comment]
To install on Linux, go to https://musescore.org, click Download / Software, then click the link for either the DEB or RPM file and then follow whatever instructions your specific distribution recommends from there (normally just double-clicking the downloaded file).

If you have further questions, please use the official Support forum - also on musescore.org - when asking for help using MuseScore.

**Comment by iFUCKINGHATEcomputers** [comment]
o fuck there it is. im tarded

![MS](https://github.com/musescore/MuseScore/assets/72257963/e3c102db-22d7-4dc9-9888-93a62937779b)

**Comment by iFUCKINGHATEcomputers** [comment]
wait no what the fuck
https://musescore.org/en/node/353503
https://aur.archlinux.org/packages/muse-sounds-manager-bin
https://aur.archlinux.org/packages/muse-hub-bin

**Comment by MarcSabatella** [comment]
again, please do not use this issue tracker just to ask support questions.  If you need help installing a DEB or RPM file, please use the official support forum on MuseScore.org.  Or, really, any general support forum for your Linux distribution, since the process should be the same across all DEB or RPM files.

**Comment by iFUCKINGHATEcomputers** [comment]
yoooo alright this shit worked
https://dev.to/nabbisen/installing-aur-packages-bdf
