### ISSUE TITLE
Incorrect rest placement when multiple voices are present

### ISSUE THREAD

**Issue by lanye74** [musescore/MuseScore#21254]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When I'm working with a second voice, in some specific scenarios, my voice 1 rests are not placed where they should be. Instead, they are placed above voice 2. It's difficult to articulate; the screen recording describes it more exactly.

This can be worked around by... moving the rest, or setting its position, but ideally that wouldn't be necessary.

### Steps to reproduce

1. Open a (new) score
2. In a blank measure, input 8 repeated eighth notes, and delete the 7th
3. In voice 2, input 4 repeated quarter notes above the eighth notes
4. Delete the first 3 quarter notes and their rests
5. (Optional) Flip the beams of all placed notes
6. Observe incorrect voice 1 rest placement
7. Observe that if you move the voice 1 rest, it is always placed relative to the voice 2 note

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/50891500/34cb2a1f-b008-4894-8af9-82b0070e8c5c

In an actual score:
![2024-01-27 21_46_49-Greenshot](https://github.com/musescore/MuseScore/assets/50891500/599e9d29-61a2-43f9-b0e8-de60f9a6c8f6)
The high Bb is voice 2, and the eighth rest attached to it is voice 1

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10

### Additional context

[bug_report.mscz.zip](https://github.com/musescore/MuseScore/files/14074724/bug_report.zip) (apologies, I can't upload mscz files directly)

**Comment by XiaoMigros** [comment]
What behavior would you expect to get, exactly? It's by design that the voice 1 rests are placed above the voice 2 contents, regardless of situation.

**Comment by lanye74** [comment]
Maybe this is an incorrect 'bug' report—I hesitated on creating this issue multiple times—but the placement of the voice 1 rest just doesn't seem logical to me. It's not a big deal to move it myself, I just would think that it would be near the eighth notes by default as opposed to so far away

**Comment by Vincentwang987** [comment]
It feel like it would just be better to make to eighth notes becomes voice 2 and just make the high note voice 1 and make the rests invisible.

**Comment by lanye74** [comment]
Maybe so. In either case, I'll close this issue. Apologies all 🥲
