### ISSUE TITLE
Make `Alt+Shift+[Number]` Add Below by Interval Default

### ISSUE THREAD

**Issue by aarvinr** [musescore/MuseScore#21265]
**Edit (1/28):** This behavior is already made possible by adding it as a keyboard shortcut in `Edit > Preferences > Shortcuts`. However, this issue requests the behavior be made default (see [this comment](https://github.com/musescore/MuseScore/issues/21265#issuecomment-1913823570)).

---

### Your idea

This feature would let you add a note by a certain interval below the current note, using the `Alt+Shift+[Number]` keyboard shortcut. For example, using `Alt+Shift+4` on a C would add a G to the same chord. This mimics the behavior of `Alt+[Number]` for adding notes by a certain interval above the current note.

### Problem to be solved

Currently, you can add notes by a certain interval above the current note using the `Alt+[Number]` keyboard shortcut. However, there is no equivalent for adding notes below the current note with the keyboard.

### Additional context

In addition to the functionality, a reference of the shortcuts should also be added to the `Add > Interval` context menu. This is for clarity, as the buttons to add an interval above currently reference their shortcuts.

**Comment by krasko78** [comment]
You can assign these shortcuts yourself in Edit -> Preferences -> Shortcuts. The command names start with "Enter interval", e.g. "Enter interval: fourth below". Once assigned, the shortcuts will appear on the main menu as well as the "+" toolbar button menu.

**Comment by aarvinr** [comment]
> You can assign these shortcuts yourself in Edit -> Preferences -> Shortcuts. The command names start with "Enter interval", e.g. "Enter interval: fourth below". Once assigned, the shortcuts will appear on the main menu as well as the "+" toolbar button menu.

Thanks, that's nice to know. I'll live this up, however, since this should probably the default behavior as it makes sense when the up intervals already have shortcuts. I also don't believe `Alt+Shift+[Number]` is used for anything else, all though I might be wrong about that.

**Comment by MarcSabatella** [comment]
The only reason they are not assigned by defaults for interval below is that it doesn’t work (produces a conflict) on systems that use Shift just to produce the numbers (e.g., French AZERTY keyboards).  At some point we really a better system for differentiating shortcuts based in keyboard layout.  For now, though, that’s a limitation that would be faced.
