### ISSUE TITLE
Hairpins don't respect Format > Style... > Dynamics > Placement

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#21264]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When setting dynamics placement to above the staff, new hairpins are still placed below the staff, but they should go above with the markings themselves.

### Steps to reproduce

Open a new score, set the placement of dynamics to above in the Style dialogue, enter a new hairpin.OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

### Additional context

Note that this is not a request for a full per-staff dynamics system (see #16509), just for hairpins to respect the current score-wide setting.

**Comment by MarcSabatella** [comment]
Hairpins aren’t dynamics internally and obey different style settings.  Which isn’t ideal and could definitely be improved.  But anyhow, for now, simply set the placement for hairpins to make them default above.

**Comment by iainhallam** [comment]
Wow! I'd not even noticed in the style settings that there was a separate entry for Hairpins (there are so many in that list, and it's 14 places away from Dynamics!). That list of settings needs organising some... Thanks.
