### ISSUE TITLE
Selection bounding box is wrong

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#21261]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

![2024-01-28 MuseScore selection bug](https://github.com/musescore/MuseScore/assets/282030/b7467b98-0b28-4042-8897-02f3df675437)

In this screen, only the bottom bar is in fact selected - if I press delete at this point, all bars apart from the bottom bar are unaffected. But this bounding box seems to indicate all bars from top to bottom are selected.

### Steps to reproduce

Unknown sadly. Switching away to another view and back stopped the behaviour for a while, but then it came back. I closed the application and reopened it, and it was fine, then it started doing it again.

I can send the file to someone on the team to have a look at, but I can't post it publicly.

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

**Comment by iainhallam** [comment]
It's just started again after I cut and pasted a tempo marking. I've not seen this in the extensive editing I've done in page view recently, so perhaps it only happens in continuous horizontal view.

**Comment by dcorson-ticino-com** [comment]
I see this also often, had it on 4.2 and still now on 4.2.1
I have been unable to find a way to provoke it, which is why I haven't posted an issue.
But it does happen quite often.
It may be related to continuous horizontal view as I always work that way.

**Comment by oktophonie** [comment]
Also see https://github.com/musescore/MuseScore/issues/11054
