### ISSUE TITLE
Add "Note anchored line" into the "Lines" palette and change the default positioning

### ISSUE THREAD

**Issue by LupusCaeruleus** [musescore/MuseScore#21279]
### Your idea

Currently, the note anchored line is hidden deeply in Add > Lines and it is difficult for many users to realize its existence. It would be better to add it into the "Lines" palette or somewhere else to be easily found.

The endpoints of the created anchored line are by default centered on each of the two note heads, which is not commonly used outside of some contemporary notation. I would suggest changing the default positioning to make the ends of the anchored line clear the both notes by a short distance (as if a glissando line without the text and playback effect) so that the line can be used to indicate voices passed to another stave, which I believe would be more widely used. 

![image](https://github.com/musescore/MuseScore/assets/70313425/74af28f6-95bf-4a37-962b-9669b4db1a33)
![image](https://github.com/musescore/MuseScore/assets/70313425/b8a3fb23-d9ef-400b-9815-c1f38f0fe30d)

### Problem to be solved

Make note anchored lines more useful.

**Comment by XiaoMigros** [comment]
I wouldn't be so keen on changing the actual default positioning, but perhaps a sensible reposition can be calculated when first being added to the score.

**Comment by DaddyLudwig** [comment]
I'm all for adding the Note anchored line into the Lines palatte. I was trying to add note anchored lines to a Bach fugue the other day and it took me a while to figure out how. Anything that can make it easier, I'm for that.

**Comment by Jojo-Schmitz** [comment]
The layout part is adressed in #24992
