### ISSUE TITLE
Playback issue with repeats after section break (MS Basic: note is too long; MuseSounds: note is too short)

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#21289]
### Issue type

General playback bug

### Bug description

Musescore keeps playing measure with repeat sign if section break is present before.
This is a regression. Works fine in 4.2.0
The [score](https://github.com/musescore/MuseScore/files/14097139/Cello_Suite_No_1_Strings_0.mscz.zip) (remove .zip before opening) with this issue was Initially reported [here](https://musescore.org/en/node/359664)

### Steps to reproduce

1. Create empty score (String quartet template was used to reproduce)
2. Insert a section break 
3. Input some notes after section break
4. Insert Right (end) repeat sign 
5. Now playback is broken

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/ee4c8ca7-4945-4ff6-8494-4756f7a9eef3

### MuseScore Version

4.2.1, 4.3.0

### Regression

Yes, this used to work in Musescore 4.2.0

### Operating system

windows 10

**Comment by DmitryArefiev** [comment]
@bkunda I move this to 4.3 since there is a similar case with MuseSounds

**Comment by DmitryArefiev** [comment]
Fixed in #21998
