### ISSUE TITLE
Style settings page should not be remembered when openning a new score during one MS session

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#21294]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Steps to reproduce

1. Open score
2. Open Style dialog
3. Select **Text styles>Title**
4. Click OK and close Style dialog
5. Close score
6. Open another score in the same MS instance (window)
7. Open Style dialog - it opens in **Text styles>Title** page 

**Expected result:** It should open the  default page (Score) for a new score (or specific page if it was triggered by selecting specific element and clicking Style in right click menu, see #20740)

https://github.com/musescore/MuseScore/assets/90187801/a0bc8a6b-5e93-46d7-bf05-83b6660972a4

### MuseScore Version

4.2.1

### Regression

No.

### Operating system

all

### Additional context

The same in MS3.6.2

**Comment by mklimek** [comment]
I guess there's a typo in "MuseScore Version", probably you meant 4.2.1

**Comment by nasehim7** [comment]
Greetings @DmitryArefiev I was able to replicate it on my machine and started to explore the codebase. From my initial analysis I see that when no Item is selected, `AbstractMenuModel::handleMenuItem()` function is invoked which restores the last action data for that action code. I also see that when we select a notation and call the "Style" menu item, `NotationContextMenuModel::makeElementItems()` this is the function that comes into play. Even when we are in the same MS instance, when nothing is selected and "Style" menu is clicked, it should restore the default "Score" option. This is as well the expectation, right? in addition to multiple instance, restoring the same menu item data. Hope my understanding is correct :)

**Comment by nasehim7** [comment]
I have made the changes and here is the updated application look which has the below behaviour:

1. When no element is selected in the notation context menu and style menu is called, it shows default “score” setting.
2. When score appearance style setting is clicked, shows default “score” setting.
3. When style setting is clicked from the format menu, shows default “score” setting.
4. No style setting is kept outside a score.

https://github.com/musescore/MuseScore/assets/18035782/0cfc1050-469a-4e67-ba9b-b6d25e22cfce

let me know your take on it, @DmitryArefiev

**Comment by DmitryArefiev** [comment]
@nasehim7 Yeah, I'll check the PR. Thanks!

**Comment by DmitryArefiev** [comment]
Fixed in #21744
