### ISSUE TITLE
Plugin UI is too slow to react to user interactions

### ISSUE THREAD

**Issue by lgvr123** [musescore/MuseScore#21303]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

The time taken by the UI of plugin to react to button click is slow.

This observable with the plugin [TapTempo](https://github.com/lgvr123/musescore-taptempo/blob/ResponsivenessIssue/taptempo/taptempo.qml).

When clicking the "Tap" button at 120bpm (withe the help of an external metronome), in MU3.6.2, the UI reacts fast enough and the plugin is able to compute the 120bpm.

In MU4.2.1, the UI is not able to react fast enough for computing such BPMs. There is a limit at +-115bpm. This corresponds to a delay of 0.5" between events. The UI is not able to handle events with <0.5s between them.

### Steps to reproduce

1. Open the TapEditor plugin
2. Click on the Tap button at a pace faster than 115bpm

### Demo in MU4.2.1 (using MU3.7 plugin editor)
![tempoMU37](https://github.com/musescore/MuseScore/assets/50494/a89b7120-1f06-445b-9b52-bfbfabe6a5f8)

One can see that the plugin misses a few clicks

### Demo in MU3.6.2
![tempoMU36](https://github.com/musescore/MuseScore/assets/50494/0b0aa40a-1eea-4d2e-bc04-0bd3077a16e3)

One can see that the plugin handles all the clicks

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows10

**Comment by XiaoMigros** [comment]
My tempo tapper plugin works fine in 4.2.1....

**Comment by lgvr123** [comment]
Above 115bpm ?

**Comment by XiaoMigros** [comment]
![image](https://github.com/musescore/MuseScore/assets/116587995/8614fbf0-5dde-49d5-977a-0548ba6694d5)

**Comment by iainhallam** [comment]
I'm seeing a lot of general slowdowns in 4.2.1 that I didn't get in 4.2.0, but I haven't been able to isolate any one thing that causes it.

**Comment by Jojo-Schmitz** [comment]
> Demo in MU4.2.1 (using MU3.7 plugin editor)

How do you do that?

**Comment by lgvr123** [comment]
> How do you do that?
Should be read as "Demo with the MU3.7 plugin editor, illustrating the same issue as in MU4.2.1"

**Comment by Jojo-Schmitz** [comment]
Ah, I see.

**Comment by lgvr123** [comment]
> My tempo tapper plugin works fine in 4.2.1....

I investigated this.

After analysis, the issue resides at the UI QML components.

I took [XiaoMigros' plugin](https://github.com/XiaoMigros/Tap-BPM), and replaced all the Musescore specific UI components by native QML components (e.g. `MU.FlatButton`replaced by `Button`). 

In this case, XiaoMigros' plugin is not able any more to handle a tempo >115bpm.

The workaround would be to be build MU4 specific plugin. Because these `MuseScore.UiComponents 1.0` are not supported by MU3.6.2 and MU3.7.

**Comment by XiaoMigros** [comment]
Have you tried using the latest Qt versions??

**Comment by lgvr123** [comment]
> Have you tried using the latest Qt versions??

I tried with both `QtQuick 2.9` and `QtQuick 2.0`. With the same result.
Is this what you meant ?

**Comment by Jojo-Schmitz** [comment]
> The workaround would be to be build MU4 specific plugin. Because these `MuseScore.UiComponents 1.0` are not supported by MU3.6.2 and MU3.7.

How does mix and match with your claim that 3.7 has the same issue?

**Comment by XiaoMigros** [comment]
For this reason the Qt versions should be tested. @lgvr123 Try `QtQuick 2.15` and `QtQuick.Controls 2.15`

**Comment by lgvr123** [comment]
> For this reason the Qt versions should be tested. @lgvr123 Try QtQuick 2.15 and QtQuick.Controls 2.15

No changes. 

> How does mix and match with your claim that 3.7 has the same issue?

The w/a works for MU4.x but not for MU3.7, unfortunately. So, as of now, the plugin works on MU3.6.2 with the original version, on MU4.2.1 with the new version, but not on MU3.7.

**Comment by lgvr123** [comment]
@XiaoMigros Where have you find the documentation on those new UI components ? They differ a lot from the original QML ones.

**Comment by XiaoMigros** [comment]
There is no documentation, only trial and error ;)

**Comment by Jojo-Schmitz** [comment]
> > For this reason the Qt versions should be tested. @lgvr123 Try QtQuick 2.15 and QtQuick.Controls 2.15
> 
> No changes.
> 
> > How does mix and match with your claim that 3.7 has the same issue?
> 
> The w/a works for MU4.x but not for MU3.7, unfortunately. So, as of now, the plugin works on MU3.6.2 with the original version, on MU4.2.1 with the new version, but not on MU3.7.

So it hardly is related to these MuseScore internals. More likely to the Qt version used, 5.15.2 in Mu4 and Mu3.7 (Mac and Win64) vs. 5.9.9 in Mu3.6.2 (and Mu3.7 Linux and Win32)

**Comment by lgvr123** [comment]
Summary of the tests:

| Code<br/>Qt version |Using QML `Button`<br/>2.0              |<br/>2.9 |<br/>2.15 |Using `MU.FlatButton`<br/>2.0                 |<br/>2.9 |<br/>2.15 |
|------------|------------------|-----|------|---------------------|-----|------|
| 3.6.2      | **OK**               | **OK**  | N/A  | N/A                 | N/A | N/A  |
| 3.7        | KO               | KO  | KO   | N/A                 | N/A | N/A  |
| 4.2.1      | KO               | KO  | KO   |                     |     | **OK**   |

**Comment by lgvr123** [comment]
Per this [StackOverflow discussion](https://stackoverflow.com/questions/67908324/qml-faster-button-clicking) I changed on the `onClicked` by a `onReleased` which responses faster than the `onClicked`. This solution solves the responsiveness issue in both MU3.7, MU4.x.

I guess this is an acceptable solution and that this issue can be closed.
