### ISSUE TITLE
Where are MuseScore UI image resources in source code?

### ISSUE THREAD

**Issue by librarymark** [musescore/MuseScore#21305]
I am building a touch screen (a Nextion screen with an ESP32) to use with note entry and I cannot find the images that make up the toolbars, like of the various notes accidentals, articulations, etc. Where are they in the source code? Right now I am using bits and pieces of screen shots of MuseScore but I need better resolution images. Thanks!

**Comment by XiaoMigros** [comment]
This is better asked on the forums as it's not an issue with the software. [The icons are all stored in a font](https://github.com/musescore/MuseScore/blob/master/fonts/mscore/MusescoreIcon.ttf)

**Comment by librarymark** [comment]
> This is better asked on the forums as it's not an issue with the software. [The icons are all stored in a font](https://github.com/musescore/MuseScore/blob/master/fonts/mscore/MusescoreIcon.ttf)

Thanks! Sorry to have bothered you.
