### ISSUE TITLE
Musescore implements note off incorrectly and results in stuck notes if you allow it to play MIDI out. 

### ISSUE THREAD

**Issue by nathan-stewart** [musescore/MuseScore#21316]
### Issue type

General playback bug

### Bug description

If you allow Musescore to use MIDI out, and it sends notes (playback, editing) the note off is sent incorrectly and may result in notes becoming stuck. 

### Steps to reproduce

Enable MIDI I/O on interface
Play, pause
Send note information from MIDI controller. - inevitably multiple (but not all) notes will be stuck. 

### MuseScore Version

OS: Debian GNU/Linux 12 (bookworm), Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230938, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Debian Bookworm

**Comment by nathan-stewart** [comment]
After determining what was going on,  I believe this is a duplicate of 19254

**Comment by zacjansheski** [comment]
Closing as duplicate of https://github.com/musescore/MuseScore/issues/19254

**Comment by cbjeukendrup** [comment]
> After determining what was going on, I believe this is a duplicate of #19254

Closing, in that case
