### ISSUE TITLE
Half-open hi-hat symbol as articulation

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#21317]
### Your idea

This is the symbol used for half-open hi-hat in the "Guide to Standardized Drumset Notation" by Norman Weinberg

*Update*
Defined in SMuFL as U+E7F7 (in the Percussion playing technique pictograms block)

<img width="309" alt="Screen Shot 2024-02-01 at 10 12 34 AM" src="https://github.com/musescore/MuseScore/assets/69917893/8e9ca212-41c6-47ff-9557-2881abf3972c">

It would be nice to have this as an articulation we can assign playback values to

### Problem to be solved

Need ability to notate half-open hi-hat

### Additional context

Perhaps this can be added to a be-spoke drum kit palette in the future

**Comment by LupusCaeruleus** [comment]
The half-open technique defined in SMuFL should be U+E7F7 (in the _Percussion playing technique pictograms_ block), and the symbol used in the screenshot above is in fact a medieval time signature U+E912.

**Comment by zacjansheski** [comment]
Thank you, updating description
