### ISSUE TITLE
Tremolos Not Playing Properly in Strings Section

### ISSUE THREAD

**Issue by TRF29568** [musescore/MuseScore#21315]
### Issue type

Muse Sounds bug

### Bug description

In the strings section of a score I'm working on (to clarify: two violin sections, viola section, cello section and contrabass section), the playback is not rendering the tremolos properly.

### Steps to reproduce

1. Open new score.
2. Input full string sections (two violin sections, viola section, cello section and contrabass section).
3. Insert two notes and put the 32nd between notes tremolo in all instruments.
4. Play the score.

### Screenshots/Screen recordings

https://drive.google.com/file/d/1N1zqKMSAgZQPb-DRwUeivO3aP_WZe-6q/view?usp=sharing

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.1.2

### Additional context

Only happens on one score (8. The Cyclone). File is here: https://drive.google.com/file/d/1cfrMU_aeAVx45laKxIl4RDKx_apihZJF/view?usp=sharing

**Comment by TRF29568** [comment]
Saw someone added the 'needs info' label, so figured I could step in and explain a few things.
1) This issue only occurs when I already have the strings section implemented into the score.
2) Based on what I've played back just now, the issue starts with viola and cello sections followed by both violin sections (measures 17 & 18 of the score). Contrabass does not have this issue until measure 143 (towards the end of the score).
3. This issue does not affect any other scores.

**Comment by zacjansheski** [comment]
Seems to play back as expected when I opened on my device
What Muse Sampler version do you have?
to check:
Diagnostic>Muse Sampler>Check Muse Sampler

https://github.com/musescore/MuseScore/assets/69917893/91a9afd1-6e92-4751-9b34-e8b340a85658

**Comment by TRF29568** [comment]
Version 0.4.3. Lemme check and see if there's an update.

**Comment by TRF29568** [comment]
Yep, found the issue. Lemme see if it resolves. I'll let you know.

**Comment by zacjansheski** [comment]
Yes, make sure to close and reopen the program.

If that doesn't work, try a factory reset.

If that doesn't work, please share diagnostic files.

**Comment by TRF29568** [comment]
Hi there! Bit of an update:
So I just tried playing back the score and it's still giving me the same issue with the tremolos, even if I revert to just single instruments instead of a full section.

**Comment by zacjansheski** [comment]
Closing as this issue has gotten stale (several updates since logged)
If you still experience an issue, please report to MuseHub support team: https://support.musehub.com/hc/en-gb/requests/new.
