### ISSUE TITLE
Kontakt reopens with a blank screen (any VSTi)

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#21329]
### Issue type

VST bug

### Bug description

After setting a track to a Kontakt instrument, close and reopen Kontakt.
Result: Get a blank screen instead of a functioning instance of Kontakt

Confirmed in v4.2 and 4.21
https://musescore.org/en/node/359455

### Steps to reproduce

1. Add VSTi
2. Close VSTi window
3. Reinitiate the **SAME VSTi** by selecting it in pop-up list in Mixer (not just clicking on VSTs name in Mixer)

https://github.com/musescore/MuseScore/assets/90187801/c489e899-dcc0-4e26-909a-cff12a56aa3b

Workaround is to close and reopen the score. Actually, maybe you have to restart MuseScore.

### MuseScore Version

5.2.1 and 4.2

### Regression

Yes, this used to work in  **MuseScore 4.1.1**

### Operating system

MacOS 13.5.2

**Comment by Apprisco** [comment]
<3 thanks for the report, got too lazy to do it myself.
![image](https://github.com/musescore/MuseScore/assets/34324909/891b552f-1cc8-4871-98b1-5547ca1130d8)
This is what happens whenever you reopen a Kontakt window after choosing 1 instrument. 
Makes it basically unusable as if you close the kontakt window you have to reopen Musescore and wait for everything to load again.
ESPECIALLY when musescore takes 5 hours to load Kontakt.
It's really great, honestly, because I can get some insane sounds on MuseScore with this now, but using it is a huge pain.
This wasn't an issue back in 4.1 nightlies.

**Comment by bkunda** [comment]
FWIW I cannot reproduce on macOS

**Comment by bkunda** [comment]
@zacjansheski pls investigate

**Comment by zacjansheski** [comment]
I did not reproduce this (Tried with Kontakt 5 and Kontakt 7)

https://github.com/musescore/MuseScore/assets/69917893/98849ef4-1eff-40af-b517-6da8d865d5fd

**Comment by Apprisco** [comment]
Only explanation here is that we're using kontakt 7 portable. Can you try that instead?

**Comment by Apprisco** [comment]
![image](https://github.com/musescore/MuseScore/assets/34324909/55493a99-2099-4d35-b8c5-087f929a2ea4)
Can reproduce with every instrument, every VST, every time

**Comment by scorster** [comment]
I don't know what Kontakt 7 Portable is.

I tested again today with Picked Nylon and Stradivari violin and found no issue when closing and reopening a Kontakt Native Instruments instrument. 

Well report back if I encounter the problem initially posted.

scorster

**Comment by Apprisco** [comment]
Portable is a non program files install- it goes in any folder and is a .exe.
That's the version most commonly used now.

**Comment by DmitryArefiev** [comment]
@scorster I can repro with these steps. Are you using the same?

1. Add VSTi
2. Close VSTi window
3. Add the same VSTi (not just clicking on Kontakt name in the Mixer)

https://github.com/musescore/MuseScore/assets/90187801/c489e899-dcc0-4e26-909a-cff12a56aa3b

**Comment by scorster** [comment]
Hi Dmitry, 

Yes. Exactly. On MacOS 13.5.2;  MuseScore 4.2.1

As you described, Step 3 provokes the empty Kontakt window. 

scorster

**Comment by DmitryArefiev** [comment]
Cool. Thanks for confirmation! I'll those steps to description

**Comment by scorster** [comment]
Thanks for working to get the kinks out of the MuseScore/Kontakt connection.

Now there's this: https://musescore.org/en/node/359683#comment-1229828

**Comment by bkunda** [comment]
I can now reproduce this using Kontakt 6.8, following the updated repro steps above. 
@scorster it seems like there are issues with Kontakt 7, which are described [here](https://github.com/musescore/MuseScore/issues/21372). It might be helpful to have your updated report about Kontakt 7.8 included there. 
@DmitryArefiev @zacjansheski @RomanPudashkin I think we need to push this as a priority for investigation and resolving, particularly if something has been affected since v.4.2.

**Comment by Apprisco** [comment]
This is very interesting. I cannot reproduce that issue anymore with a proper Kontakt 7 install, 7.8 to be clear- NON PORTABLE.
Also portable instances took a whole minute to load the first time I opened MS4 and Kontakt each session.
Now it's basically instant. 
I also cannot reproduce the instrument issue on kontakt 7.8 system wide install, portable has been removed.

**Comment by DmitryArefiev** [comment]
Strange.. It still happens on my side. Did you try these steps?

1. Add VSTi
2. Close VSTi window
3. Reinitiate the **SAME VSTi** by selecting it in pop-up list in Mixer (not just clicking on VSTs name in Mixer)

**Comment by Apprisco** [comment]
It happens for Kontakt 7 Portable.
That's what I mean.
It doesn't happen for 7.8 native, it happens for 7.8 portable.
There is no pop up list for me, I need to load Kontakt not the vst.

**Comment by scorster** [comment]
Problem persists with Kontakt 7.9

https://musescore.org/en/node/359683#comment-1235218

**Comment by bill0287** [comment]
I am going to chime in here too. I just downloaded "The Free Orchestra 1 and 2" with Kontakt 7.9. I am on MS4.2.1 on Windows 11. When I try to access Kontakt via VST, it "opens" the program and shows the libraries, but when I open a library, there are no instruments shown, No errors, just an empty screen. Standalone Kontakt works fine, and the VST works fine in a different notation program.

**Comment by bill0287** [comment]
I am seeing the same behavior when using Halion Sonic.

**Comment by bkunda** [comment]
@RomanPudashkin @DmitryArefiev did we perhaps make a change recently that might render this issue no longer as valid? 

At least on macOS, I am unable to re-instantiate the VSTi window via the repro steps above (not just for Kontakt, but other VSTi plugins as well). Tested in both 4.3.1 and master. 

This actually strikes me as unproblematic. I'd hazard a guess that clicking on the actual plugin name in the mixer slot is not just a far more convenient, but also a more obvious way of calling the currently-loaded plugin window. At least now _nothing_ gets triggered by re-selecting the currently selected context menu item (as opposed to an empty window being loaded). 

https://github.com/musescore/MuseScore/assets/86290556/e8821370-3aff-4652-869e-7684391e42d6

**Comment by bkunda** [comment]
It seems that at some point the ability to trigger an active VST plugin's dialog by re-selecting it from the context menu ended up being disabled. Moreover, those of us who have tested this recently are unable to reproduce it. 
So I'll close it for now, but of course we should re-open it if the problem proves persistent.

**Comment by kezonogueira** [comment]
It keeps happening to me, using OS: macOS 12.7, Arch.: x86_64, MuseScore Studio version (64-bit): 4.5.2-251141402, revision: github-musescore-musescore-ac9d3bc

![Image](https://github.com/user-attachments/assets/8ffe86ae-244d-4a95-8b3a-08da4540bf67)

**Comment by scorster** [comment]
I haven't had encountered the blank Native Instruments VST window since the last fix.

I'm using:

Kontakt 7.10.7
MuseScore 4.5.2 
MacOS 13.5.2
