### ISSUE TITLE
 'x' noteheads are not vertically centered on ukulele TAB staff lines

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#21331]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

 'x' noteheads are not vertically centered on ukulele TAB staff lines

Reported here: https://musescore.org/en/node/358331#comment-1220368

### Steps to reproduce

- Create a ukulele score with linked tablature
- add a note
- set its notehead style to x

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

macOS 13.5.2

**Comment by oktophonie** [comment]
Is actually currently being worked on as part of 
https://github.com/musescore/MuseScore/issues/16500
