### ISSUE TITLE
[TIED NOTES] Guitar bend and arrival note does not play after tied note

### ISSUE THREAD

**Issue by WhatGoesUp** [musescore/MuseScore#21345]
### Issue type

General playback bug

### Bug description

When a standard bend is applied to a note that is tied to a previous one, the bend note is not played. This applies to both Muse Sounds and MS Basic.

![Standard bend does not play after tied note](https://github.com/musescore/MuseScore/assets/155248678/f3aa3467-8c18-4aff-8d0c-249a6ce0d361)

### Steps to reproduce

1. Tie two arbitrary notes.
2. Add a note a full step up after the second tied note.
3. Add a standard full bend from the last tied note to the new note.
4. Playback, the new note will not play.

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10

### Additional context

This may or may not be related to #12971

**Comment by erinic04** [comment]
The bend does play if there is a bend at the start of the tied note, however, so you can have something like a grace note bend set to the same note as the main note and then it will work. However, even with this bends still don't work if they don't start on the last notehead of the tied note eg. bend over two whole notes.

**Comment by abariska** [comment]
Another case: the target note of the second bend in a row has no sound at all when there's a tied note before 

https://github.com/user-attachments/assets/47e064c1-d1c4-499a-b4ad-e10c9cd94d3b

**Comment by DmitryArefiev** [comment]
Fixed in #25376
