### ISSUE TITLE
Maximising on secondary monitor instead starts fullscreen

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#21344]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

I drag my application windows around a fair amount to arrange them on my three monitors under Windows 10. If I use the title bar to drag the MuseScore window to the top of the primary screen that has the taskbar on it, the window maximises - all well and good. If I do the same with the aim of maximising on either of my secondary screens, the window instead goes full-screen, and I lose the title bar and window controls to close or minimise it.

I can get it back by pressing F11 to exit full-screen but there doesn't seem to be a way to maximise the window on these secondary screens (pressing the maximise button on a secondary screen does the same as dragging the title bar, and just goes full-screen).

### Steps to reproduce

1. Open MuseScore on a system with multiple monitors
2. Drag the window to a secondary monitor
3. Maximise

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

**Comment by henkdegroot** [comment]
Same as #19942 and #19809

**Comment by iainhallam** [comment]
Apologies - I didn't find that originally.
