### ISSUE TITLE
Fedora 39 sound issues - possibly Pipewire related

### ISSUE THREAD

**Issue by svnsbck** [musescore/MuseScore#21358]
### Issue type

General playback bug

### Bug description

Hi! 
Earlier I updated my Fedora 39 packages and as a result Musescore 4.2.1 playback stopped working.  This was with AppImage and the packaged version from the repository.

After some digging I downgraded Pipewire to the previous version and it started to work as expected.

The package in question was pipewire-1-0.2-1.fc39-x86_64

Thought someone would like to know.

### Steps to reproduce

Update Pipewire

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Fedora 39

**Comment by runarcn** [comment]
I'm having the same issue. It seems to have something to do with the I/O buffer not... existing? Whenever I tried to set one it just crashed the program. It also doesn't detect any audio outputs, though I can see that it doesn't do that after downgrading Pipewire either - probably not too important.

OS: Fedora Linux 39 (Workstation Edition), Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230938, revision: github-musescore-musescore-d757433

Here's a video of it. I forgot to enable mouse recording though :P
[Screencast from 2024-02-04 11-48-52.webm](https://github.com/musescore/MuseScore/assets/52424029/3cd84a3b-791b-4cb6-9582-fe18dba9deef)

**Comment by jimishol** [comment]
I confirm the same happens on opensuse tubleweed, as it is reported in https://bugzilla.opensuse.org/show_bug.cgi?id=1219523. Appimages of musescore 4.2.0 or 4.2.1 are not able to playback too, but i just checked that current flatpak runs ok and do produce playback sound.

**Comment by bkunda** [comment]
@DmitryArefiev pls investigate

**Comment by runarcn** [comment]
Hi again,
Seems to work for me now on latest appimage with `pipewire-1.0.3-1.fc39.src.rpm`. Tested in both SwayFX and GNOME.

**Comment by DmitryArefiev** [comment]
> Hi again, Seems to work for me now on latest appimage with `pipewire-1.0.3-1.fc39.src.rpm`. Tested in both SwayFX and GNOME.

@runarcn Hi! Do you mean on latest appimage of MuseScore (4.3 master build)?

**Comment by DmitryArefiev** [comment]
@runarcn Cool. Thanks! That means it's fixed on Linux side now

@svnsbck Can you check on your side please?

**Comment by svnsbck** [comment]
Hi,

sorry for the late reply, but the latest update pipewire fixed that issues for me as well on Fedora 39 with the latest AppImage.
