### ISSUE TITLE
Missing beat in voice 2 after deleting notes

### ISSUE THREAD

**Issue by ShibuyaCyana** [musescore/MuseScore#21355]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Steps to reproduce

Open a new score and enter these following notes, delete some notes in voice 2 by pressing backspace one by one, then re-enter some:
![Voice 2](https://github.com/musescore/MuseScore/assets/39703247/232d9d52-9842-49e7-9810-87de27e3482c)

Strangely it doesn't cause a corruption when saving.
Regression notice: I only have 3.2.0 installed, it behaves as expected.

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

### Additional context

I thought I read this one somewhere but couldn't find it...

**Comment by cbjeukendrup** [comment]
Possibly somewhat related to #17931
