### ISSUE TITLE
Some third party VST's doesn't detect musescore off - on pedal

### ISSUE THREAD

**Issue by Philip4dk** [musescore/MuseScore#21353]
### Your idea

Make the off - on a bit slower for better compatibility with more VST's 

### Problem to be solved

Too fast pedal changes

### Additional context

I'm using pianoteq VST

**Comment by ThePython10110** [comment]
I'm pretty sure this also applies to Vital Synth.

**Comment by RomanPudashkin** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/22910
