### ISSUE TITLE
Musescore 4.2.1 repeatable crash on playback (or measure delete) with one score (MuseSounds only, Windows only)

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#21367]
### Issue type

Crash or freeze

### Bug description

Musescore 4.2.1 crashes during playback with attached "crashes on playback.mscz" file.

Tried latest nightly build and still crashes.

### Steps to reproduce

1. Select a measure prior to measure 38 as the starting point.
2. Press playback button (or space bar)
3. When measure 38 arrives, MS crashes.

(Also seems to crash if you start playback in a measure after 38, but will play correctly from beginning to measure 38).

### MuseScore Version

OS: **Windows 10** Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240350505, revision: github-musescore-musescore-47a80eb

**Doesn't occur** on **Mac**

### Regression

I don't know

### Operating system

Edition	Windows 10 Home Version	22H2 Installed on	‎12/‎5/‎2020 OS build	19045.3996 Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Additional context

[crashes on playback.zip](https://github.com/musescore/MuseScore/files/14159800/crashes.on.playback.zip)
[crashes on playback4.zip](https://github.com/musescore/MuseScore/files/14695490/crashes.on.playback4.zip) - short version

**Comment by DmitryArefiev** [comment]
Can reproduce on my side. Happens with **MuseSounds** and only with **Violin 1 (Solo)** 


Uploading bandicam 2024-02-05 18-27-53-939.mp4…

**Comment by seisfeldt** [comment]
Update - I am not able to delete the measure without a crash.  Any ideas on how I can restore my file so I can continue working it?  Thanks.

**Comment by DmitryArefiev** [comment]
Just try to switch to MS Basic

**Comment by seisfeldt** [comment]
Thanks Dmitry - that worked for now!

**Comment by DmitryArefiev** [comment]
Fixed in musesampler side. Tested on latest 4.3/master builds, Win10 with musesampler **0.6.0.138**

**Comment by DmitryArefiev** [comment]
@seisfeldt Unfortunately, you can get the fix only when musesampler will be updated to **v6** via MuseHub

**Comment by seisfeldt** [comment]
No problem.  The MS Basic works for now.  Thank you for fixing!
