### ISSUE TITLE
Bends do not work with non-guitar instruments

### ISSUE THREAD

**Issue by UltimateCactus** [musescore/MuseScore#21369]
### Issue type

General playback bug

### Bug description

Bends do not work for instruments that are not guitars.

### Steps to reproduce

1. Create new score with instrument "Flute"
2. Add a whole note
3. Add a full bend from guitar palette
4. Play
5. No bend is heard - notes are played individually

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/89234997/8dc4e92f-b3b5-4733-9b93-3cc509fb1895)

### MuseScore Version

4.2.1.240230937

### Regression

I don't know

### Operating system

Windows 10

### Additional context

I have tried this with both flutes and recorders, and neither work. I tried with acoustic guitar and the bends did work.
As a slight side note, I'm not sure that the bends should look like this, I would expect them to look more like the screenshot in [this related issue](https://github.com/musescore/MuseScore/issues/13544). That being said I am not a professional musician and am not aware of the generally accepted scripting of bends.
As far as I know prior to MuseScore 4.x bends did work on all instruments. [This score](https://musescore.com/user/7746406/scores/11768992) published in 2023 has working bends on instruments that are not guitars.
In addition to this, I find it odd that bends are not able to go downwards, as many instruments are perfectly capable of doing so, as well as that they are in the guitar palette, as they are not at all exclusive to guitar.

I apologise if this duplicates any issues. I searched for issues but couldn't find any with this exact issue.

**Comment by MarcSabatella** [comment]
That notation really is only used for guitar - for other instruments, you would normally use a glissando line, with the playback set to "portamento" style.

It's certainly possible that at some point, playback support for the guitar-specific bend notations might be added to other instruments as well.  So this is a reasonable feature request; although not really a bug.  For now, best to stick to the standard notations like glissandi that are already understood by both human musicians and MuseScore.

In the future, when you have questions about how to use MuseScore, please ask on the official support forum on musescore.org
