### ISSUE TITLE
Build fails with CMake version 3.28.2 specifically

### ISSUE THREAD

**Issue by theramzay** [musescore/MuseScore#21360]
### Issue type

Other type of issue

### Bug description

I’ve tried to compile from source v4.2.1/4.2.0/4.1.1/4.1.0 with this instructions
1) https://github.com/musescore/MuseScore/wiki/Install-dependencies#macOS
2) https://github.com/musescore/MuseScore/wiki/Compiling-on-Macs-with-Apple-Silicon#compiling-in-arm64-mode

### Steps to reproduce

1) clone project
2) checkout 4.2.1 branch
3) instal dependencies from `Install-dependencies#macOS` wiki
4) go through all steps in `Compiling on Macs with Apple Silicon`

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

macOS 14.3

### Additional context

CMake logs with errors

[cmake_error.log](https://github.com/musescore/MuseScore/files/14157191/cmake_error.log)

**Comment by Jojo-Schmitz** [comment]
make[2]: *** No rule to make target `src/framework/global/CMakeFiles/global.dir/cmake_pch_arm64.hxx.pch', needed by `src/framework/global/CMakeFiles/global.dir/Unity/unity_4_cxx.cxx.o'.  Stop.

**Comment by cbjeukendrup** [comment]
Did you indeed add `-DMUE_COMPILE_BUILD_MACOS_APPLE_SILICON=ON` when calling `./build.cmake`? And have you already tried deleting the `builds` folder and rebuilding? It's a weird error, that might mean something is simply corrupted in the current `builds` folder.

**Comment by ramzzzay** [comment]
> Did you indeed add `-DMUE_COMPILE_BUILD_MACOS_APPLE_SILICON=ON` when calling `./build.cmake`? And have you already tried deleting the `builds` folder and rebuilding? It's a weird error, that might mean something is simply corrupted in the current `builds` folder.

Yes. This is how I’ve compiled it first time just after git clone & checkout:

<img width="2038" alt="image" src="https://github.com/musescore/MuseScore/assets/5748239/be30b20c-683e-4257-b6fa-abd8b3ec1b2a">

Here I’m done it again, but with cleaning:

<img width="1180" alt="image" src="https://github.com/musescore/MuseScore/assets/5748239/6580cd84-d09a-40d4-acce-a15888d78cb8">

<img width="601" alt="image" src="https://github.com/musescore/MuseScore/assets/5748239/27610328-2097-46b9-ab36-90e0435e39dc">
<img width="2168" alt="image" src="https://github.com/musescore/MuseScore/assets/5748239/435dcd7e-8fbd-4330-a10b-390dfb4eb018">

Here error logs after second run:
[cmake_error_after_clean.log](https://github.com/musescore/MuseScore/files/14161867/cmake_error_after_clean.log)

**Comment by Jojo-Schmitz** [comment]
Still the same error as befor

**Comment by cbjeukendrup** [comment]
Another thing you can try: using the "Ninja" generator instead of "Makefiles". To do that, add `-GNinja` to the `./build.cmake` command.

**Comment by ramzzzay** [comment]
> Another thing you can try: using the "Ninja" generator instead of "Makefiles". To do that, add `-GNinja` to the `./build.cmake` command.

Thanks, I’ve tried, but same error ;’(

<img width="2168" alt="image" src="https://github.com/musescore/MuseScore/assets/5748239/265a8482-1317-4355-b707-58bf09527a10">
<img width="2168" alt="image" src="https://github.com/musescore/MuseScore/assets/5748239/7f98473c-263e-41f5-b30e-3038b8d43d7f">

Logs:
[gninja_error.log](https://github.com/musescore/MuseScore/files/14176424/gninja_error.log)

**Comment by Eism** [comment]
Try to disable Unity
`-DMUE_COMPILE_USE_UNITY:BOOL=OFF`

**Comment by ramzzzay** [comment]
> Try to disable Unity `-DMUE_COMPILE_USE_UNITY:BOOL=OFF`

<img width="2168" alt="image" src="https://github.com/musescore/MuseScore/assets/5748239/9f2a8ced-1367-40ff-b1c8-a59e8a19d744">

Logs:
[cmake_disabled_unity.log](https://github.com/musescore/MuseScore/files/14176794/cmake_disabled_unity.log)

**Comment by Eism** [comment]
I called ./build.cmake without any flags on my machine - no problems

I would recommend you to reinstall Qt according to this documentation - https://github.com/musescore/MuseScore/wiki/Install-Qt-and-Qt-Creator

It looks like you installed Qt via the command line, try installing via the official installer as described in the article above. 
Also it may be worth uninstalling the previous version before installing. The installer has an option to remove all components.

**Comment by ramzzzay** [comment]
> I called ./build.cmake without any flags on my machine - no problems
> 
> I would recommend you to reinstall Qt according to this documentation - https://github.com/musescore/MuseScore/wiki/Install-Qt-and-Qt-Creator
> 
> It looks like you installed Qt via the command line, try installing via the official installer as described in the article above. Also it may be worth uninstalling the previous version before installing. The installer has an option to remove all components.

Yep, I’ve used this guide for Apple Silicon Mac.
https://github.com/musescore/MuseScore/wiki/Compiling-on-Macs-with-Apple-Silicon#compiling-in-arm64-mode

<img width="628" alt="image" src="https://github.com/musescore/MuseScore/assets/5748239/b7053c97-25d4-4590-a9dd-e2d189dce34a">

**Comment by Jojo-Schmitz** [comment]
Is this related to #21385? If so it should be fixed

**Comment by ramzzzay** [comment]
> Is this related to #21385? If so it should be fixed

just have tried latest master commit (e9c4b72b0fba481d0030bbce495dad1ae5dedc16), same error :’(

**Comment by cbjeukendrup** [comment]
@theramzay
@Eism and me have done some research and I believe that this may be a bug in CMake 3.28.2. Fortunately, it seems fixed in version 3.28.3, which is already available via HomeBrew, so after running `brew upgrade`, things should become better. Could you please try if that solves it for you?

**Comment by cbjeukendrup** [comment]
That's impressive! I realise that I've actually never taken the time to really look at the performance difference. That does make it worthwhile to look into creating universal builds.
