### ISSUE TITLE
Concert Toms has 6 different notes but only 3 pitches

### ISSUE THREAD

**Issue by EvansSC1** [musescore/MuseScore#21377]
### Issue type

Muse Sounds bug

### Steps to reproduce

1. Create a New Score
2. Add Concert Toms instrument
3. Play all 6 defined notes
4. Hear only 3 different pitches, split among the 6 notes

### MuseScore Version

4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

No.

### Operating system

Windows 10

**Comment by zacjansheski** [comment]
Will be fixed in next release, thank you!
