### ISSUE TITLE
After solo/muting in parts, exporting to MIDI crashes MuseScore

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#21378]
### Issue type

Crash or freeze

### Bug description

Likely caused by https://github.com/musescore/MuseScore/pull/20758

### Steps to reproduce

1. Make a score with parts
2. Solo/mute in parts
3. Export parts to MIDI

### MuseScore Version

OS: macOS 14.2, Arch.: x86_64, MuseScore version (64-bit): 4.3.0-240360302, revision: github-musescore-musescore-35f7430

### Regression

No.

### Operating system

Mac OS 14

**Comment by zacjansheski** [comment]
[PartSoloCrash.zip](https://github.com/musescore/MuseScore/files/14171598/PartSoloCrash.zip)

**Comment by zacjansheski** [comment]
https://github.com/musescore/MuseScore/assets/69917893/2ff259eb-029f-4b83-b554-0942f6b249cb

**Comment by mathesoncalum** [comment]
Doesn't seem to be caused by #20758. I also noticed you don't need to do any solo-muting to repro.

1. Create score, add some notes
2. Open all parts
3. Export all parts to MIDI (_kaboom_)

Looking into it now.

**Comment by bkunda** [comment]
According to @RomanPudashkin, this seems to have been caused by https://github.com/musescore/MuseScore/pull/20824
