### ISSUE TITLE
MuseScore 4 Application crashes when opening up Kontakt VST (Kontakt 7.8.1, Mac only)

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#21372]
### Issue type

Crash or freeze

### Bug description

So yesterday, I was working om making some score edits to one of my arrangement pieces, though after when I tried to open up a VST plugin within the mixer for further playback adjusting, somehow, MuseScore crashes. Not just for that piece, but for any new composition I start composing.

What exactly could be the cause of this to happen? So far, it's the result of one of the plugins like Kontakt 7 Player, or any other instrument plugin I use.

### Steps to reproduce

1. Open up MuseScore
2. Insert an .mscz file with everything set to MS Basic.
3. Go to the mixer and select an instrument to change the sound.
4. Select any plugin from the VST3 option.

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS Monterey v12.7.3

**Comment by zacjansheski** [comment]
I have not been able to reproduce this.  Neither with Kontakt or other VSTs.

Could you share diagnostic files?  Diagnostic>Save diagnostic files

**Comment by DmitryArefiev** [comment]
No crash on my side too (MS4.2.1, Kontakt7, Mac13.6)

**Comment by paulcharpntier** [comment]
I have the same problem, do you find a solution?

**Comment by DmitryArefiev** [comment]
@paulcharpntier With what plugins (and macOS) version? Please attach a video demo and diagnostic files (Top menu>Diagnostic>Save diagnostic files)

**Comment by cbjeukendrup** [comment]
Also, if macOS generates a crash report, please attach that too (for example as a text file)

**Comment by paulcharpntier** [comment]
In my case MS4.2.1, Kontakt7, MacBook Pro16,1)

**Comment by waytgibbs** [comment]
I have the same issue with Kontakt 7 Player on 2020 iMac (64 GB RAM), Sonoma 14.2.1. Screen cap and diagnostic files attached. No crash report generated by the OS. 
I have had no problems so far using other VST3s by Spitfire. 
Using Kushview Element to connect to older version (Kontakt 6.2.2) works during that Musescore session, but MS4 crashes if the file is saved with that instrument assignment and then reopened.

https://github.com/musescore/MuseScore/assets/6627581/596dc5a6-65cd-46b2-9926-53989522d317

[Musescore diagnostic files.zip](https://github.com/musescore/MuseScore/files/14292757/Musescore.diagnostic.files.zip)

**Comment by RJJHENRY** [comment]
I am having the same issue. 
I am on Windows 11 and use Kontakt 7 for a suite of steel drum sounds. Files with those instruments already set have been opening with MSBASIC instruments, and when I try to re-assign a sound from Kontakt 7, the Kontakt interface loads then freezes; Musescore also freezes. I have to use the task manager to quit Musescore.

**Comment by scorster** [comment]
As reported [here on .org](https://musescore.org/en/node/359683#comment-1229828), MuseScore hangs and eventually abends when I attempt to open Kontakt 7.8 in MS 4.2.1's mixer. Restarting MuseScore makes no difference. Restarting my MacBook Air M2 24 GB made no difference.

No MacOS crash log generated. Just a silent crash. 

Kontakt 7.8 works fine elsewhere, such as Logic Pro.

PianoTeq and Korg VST plugins both work fine. Switching back to Kontakt causes an immediate crash.

scorster

**Comment by DmitryArefiev** [comment]
Thanks for details! I've updated my Kontakt to the latest version (**7.8.1**) and now **can reproduce** the crash easily on Mac13.6

Can reproduce in earlier MS versions as well (4.0.1)

**Comment by scorster** [comment]
[DmitryArefiev](https://github.com/DmitryArefiev)wrote > *Thanks for details! I've updated my Kontakt to the latest version (7.8.1) and now can reproduce the crash easily on Mac13.6*

Likewise. Thanks for your latest report! It's heartening to know you're able to replicate the crash.

I upgraded tonight from Kontakt 7.8 to 7.8.1—just to check if it would make a difference±but indeed the crash persists in MuseScore 4.2.1 on MacOS 13.5.2.

**Comment by RomanPudashkin** [comment]
Qt is somehow involved in this crash. The crash doesn't happen in master (4.4), which uses Qt 6.2.1 but does happen in other versions of MuseScore that still use Qt 5.15

**Comment by waytgibbs** [comment]
I just compiled MS 4.4 from the repository, after installing Qt 6.2.4. The Folders preferences pane in the 4.4 app no longer includes a VST3 folder selection box. And MuseScore 4.4 doesn't appear to scan the system for VSTs, as no virtual instruments are listed in the mixer other than Soundfonts, Muse Sounds, and the MS Basic voice. I hope the developers haven't given up on supporting third-party software instruments!
![image](https://github.com/musescore/MuseScore/assets/6627581/f70d0fae-d614-47d6-8b3d-7e936cd30113)

**Comment by DmitryArefiev** [comment]
All good on my side (latest master on Qt6.2.4, Mac13.6):
<img width="940" alt="Screenshot 2024-03-14 at 12 26 51" src="https://github.com/musescore/MuseScore/assets/90187801/ac0dbb23-866a-41a0-b49a-bf9a0c2ba595">

**Comment by Eism** [comment]
@waytgibbs 
I think you forgot to configure the project to support VST

<img width="1025" alt="Screenshot 2024-03-14 at 12 55 01 PM" src="https://github.com/musescore/MuseScore/assets/10116828/a36c1b5b-7526-4d3c-841d-c358a72a7661">

**Comment by waytgibbs** [comment]
Thanks—I compiled from the command line, didn't see that config req noted in the docs. I will rebuild and test with my Kontakt 7 setup and some other VST3s.

**Comment by DmitryArefiev** [comment]
After update Kontakt 7 to version **7.9.0** it also **crashes in 4.4** builds (master branch base on Qt6)

**Comment by DmitryArefiev** [comment]
Fixed in #22339 (#22327)

**Comment by UlikGames** [comment]
I have The Grand 3 from steinberg when I load it it just close itself

**Comment by jjrussell** [comment]
I'm still getting this crash on the latest musescore 4.4. Is the PR with the fix from back in April in 4.4.0?

Is there any information I could collect to confirm if it's the same issue?
It happens as soon as I try to set a kontakt 7 instrument to any instrument sound in the mixer. 

OS: macOS 14.5, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

**Comment by cbjeukendrup** [comment]
@jjrussell There's a new report of such a crash: https://github.com/musescore/MuseScore/issues/24331

The fix was included in 4.4 as well as 4.3, but perhaps it was later broken again in 4.4, without anyone noticing it.

It's probably better to continue the discussion at https://github.com/musescore/MuseScore/issues/24331, rather than here at this closed issue.

**Comment by jjrussell** [comment]
Thanks for the pointer. I didn't see that other issue. I'll watch that one. Thanks.

**Comment by scorster** [comment]
Kontakt 7.10.6 working here on MacOS 13.5.2 with MSS4.3. 2 

OS: macOS 13.5, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

**But MSS4.4 crashes** when I select Kontakt from the Mixer.

OS: macOS 13.5, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

**Comment by cbjeukendrup** [comment]
@scorster As noted in https://github.com/musescore/MuseScore/issues/24331#issuecomment-2324591812, there is a potential fix that can be tried out.
