### ISSUE TITLE
media-sound/musescore-4.2.1 compilation fails against dev-qt/qtcore-5.15.12-r1 / dev-qt/qtxml-5.15.12 (gentoo)

### ISSUE THREAD

**Issue by berndf** [musescore/MuseScore#21381]
### Issue type

Other type of issue

### Bug description

There is a simple patch attached to the gentoo bug report:
https://bugs.gentoo.org/923748

### Steps to reproduce

Try to compile against newest version 5.15.12 of Qt5. We are not sure why default includes were tightened - Qt defaults or build options...

### MuseScore Version

4.2.1

### Regression

No.

### Operating system

gentoo (fully up to date)

### Additional context

Buildlog is attached to the gentoo report.

**Comment by zx2c4** [comment]
https://github.com/musescore/MuseScore/pull/21385
