### ISSUE TITLE
Missing lines in MusicXML export

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#21390]
### Issue type

Import/export issue

### Steps to reproduce

I'm now doing this:
https://musescore.com/user/1397281/scores/14219449
I'm almost at the end, but I have discovered the serious problem that MuseScore doesn't export any cresc./dim. texts in individual parts, only the top ones are exported. For example, bar 28 piano part, there's a dim., but not exported; bar 802, strings, all cresc.'s are not exported. I have to break my braille translation and I'm not sure how many misleading scores I have translated. What's wrong? Does this only happen when system lines are included?

### MuseScore Version

4.2.1

### Regression

Yes since 4.2.1.

### Operating system

Windows

**Comment by hhpmusic** [comment]
I just checked all string quartets I did from the OpenScore String Quartets, and found all cresc./dim. are like this, meaning such lines are missing from all parts except part 1. I can't believe how many wrong braille scores I've produced! I have to stop all transcriptions related to Musescore files!

**Comment by hhpmusic** [comment]
Ok, I found it's just a regression between 4.2.0 and 4.2.1, so I'll redo any scores done after 4.2.1.

**Comment by oktophonie** [comment]
I can't reproduce this with the piano dim. in b28, but I can with the strings example (3 bars before fig 139). However, this behaviour is the same in 4.2.0 and 4.2.1 as far as I can tell.

**Comment by hhpmusic** [comment]
Then the regression might happen after the 4.2 preview. Anyway, it does impact my recent work.
