### ISSUE TITLE
0-byte file when export Uncompressed .musicxml and Uncompressed .xml 

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#21420]
### Issue type

Import/export issue

### Steps to reproduce

The latest nightly build has this exported as 0 byte:
https://musescore.com/user/35916268/scores/9376147

### MuseScore Version

4.3.0 nightly

### Regression

Yes, this used to work in **MuseScore 4.2.1**

### Operating system

Windows

**Comment by oktophonie** [comment]
Cannot reproduce, either in the latest nightly (4.3.0-240400304) nor current master; exporting/reimporting works fine (though admittedly takes a while).

You should probably be aware that significant refactoring work is taking place on the MusicXML code at the moment, so nightly builds may be more unreliable than usual.

**Comment by hhpmusic** [comment]
Please try exporting uncompressed Musicxml, and you'll get a 0-byte file.

**Comment by Jojo-Schmitz** [comment]
_4.2.3 nightly_???

**Comment by DmitryArefiev** [comment]
> Please try exporting uncompressed Musicxml, and you'll get a 0-byte file.

Checked on Win10 and latest 4.3 master. 

Yes, the problem occurs with **uncompressed .musicxml** and **uncompressed .xml** (exporting compressed .mxl works fine)

I'll edit the summary

![Screenshot 2024-02-09 145523](https://github.com/musescore/MuseScore/assets/90187801/b2109fb5-33d7-4904-80d8-2227af74ffbb)

**Comment by igorkorsukov** [comment]
Thank you! I'll take care of it

**Comment by igorkorsukov** [comment]
@DmitryArefiev please retest, at the moment all good for me

**Comment by hhpmusic** [comment]
Now it's ok, probably fixed when doing the prall lines.

**Comment by Jojo-Schmitz** [comment]
Rather unlikely.
@igorkorsukov any better idea what might have fix this?

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev please retest, at the moment all good for me

@igorkorsukov Yes, all good on my side too. 

Tested in latest master on **Win10**, Mac13.6, LinuxUbuntu22.04 - **FIXED**

**Comment by igorkorsukov** [comment]
> Rather unlikely. @igorkorsukov any better idea what might have fix this?

no ideas, I didn’t notice when it broke and when it was fixed...
we can find bisects using git bisect, but I'm busy with other things, so I'm happy that it just works :) (although of course I wonder what it was)
