### ISSUE TITLE
Dots make space for invisible flags

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#21448]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Dots are horizontally offset to accomodate for flags, even if the flag is invisible.
![image](https://github.com/musescore/MuseScore/assets/116587995/d0b4e2a3-f399-4158-92a2-bd9fc0de4af7)

### Steps to reproduce

1. Create a new score, add a dotted eighth
2. Make the flag invisible

### MuseScore Version

master

### Regression

No.

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
Not a 3.x regression, but only because there the dots don't make place for the flags...

**Comment by oktophonie** [comment]
duplicate of https://github.com/musescore/MuseScore/issues/9941
