### ISSUE TITLE
Glissando Line Vanishes at the End of a Copy-Pasted Measure

### ISSUE THREAD

**Issue by moontan** [musescore/MuseScore#21441]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

The glissando on the last note of a copy-pasted measure is displayed as existent in the palette, but not in the score. When I add a tie, it reappears, but instantly disappears at the end of the other copy of the measure, and vice versa.

### Steps to reproduce

1. Create a measure and populate it with notes.
2. Add a glissando line.
3. Copy the measure's content and paste it elsewhere in the score.

### Screenshots/Screen recordings

https://youtu.be/KFC8vily6kc

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

OS: macOS 13.6, Arch.: x86_64, \\

**Comment by moontan** [comment]
This is one symptom of generally weird behaviour of glissandi on pretty much every score I write. They get displayed and then all of a sudden I don't see them any more when I get to the relevant passage later. I have no idea whatsoever as for what might be the cause for this.

**Comment by dcorson-ticino-com** [comment]
My observation is that glissandi need a certain horizontal space between the notes to be displayed properly.
If this space is reduced during formatting or copying, for whatever reason, the glissando is not displayed.
Glissando display should have a way of enforcing this minimal required horizontal spacing.

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

**Comment by oktophonie** [comment]
Glissando lines _do_ have an enforced minimum spacing.

It would be useful to have a specific score where this problem occurs, for testing. Again, I can't reproduce this from scrach.

**Comment by dcorson-ticino-com** [comment]
Here you are, as it opens in measure 8 there is a glissando.  Only the line shows, move the C to the right to see "gliss." showing.
Now copy measure 8 to, for example, measure 12.  All indications of glissando in measure 8 disappear.  In measure 12 there is also no indication.  Move the C to the right in both places to get the glissando to appear.
I hope this helps.
Don
[GlissTest.zip](https://github.com/musescore/MuseScore/files/14309912/GlissTest.zip)

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

**Comment by wizofaus** [comment]
This sounds similar to a problem I've experienced. If you open the following score 
[gliss-bug.mscz.zip](https://github.com/musescore/MuseScore/files/15440871/gliss-bug.mscz.zip)
 (rename from .zip to .mscz), and try to add a *dynamic* in the first measure, the gliss. lines disappear. Undo does NOT restore them. Moving notes around can also cause them to disappear and reappear randomly.
 But then it didn't happen when creating a brand new score with the same notes!

**Comment by wizofaus** [comment]
Confirmed the above problem (adding a dynamic to the attached score and having the glissandi lines disappear) still happens with master.  And other users have definitely experienced similar issues with disappearing lines.
