### ISSUE TITLE
New Score Auto-Generated Tempo Marking Assumes Quarter Note Tempo

### ISSUE THREAD

**Issue by CoolSpy3** [musescore/MuseScore#21454]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When creating a "New Score", if the user selects a tempo marking that is not "Quarter-Note = ...", the newly-created score will display the correct tempo marking, but playback will be relative to the quarter-note tempo.
Ex.
Half-Note = 80 will play as Quarter-Note = 80

### Steps to reproduce

1. Create a New Score
2. Choose any instruments
3. On the "Additional score information" screen, go into the tempo menu
4. Select "Show tempo marking on my score"
5. Change the note type to anything besides "Quarter-Note"
6. Press "Done"

Workaround:
1. Select the auto-generated tempo marking
2. Go to the "Properties" panel
3. Uncheck and recheck "Follow written tempo"

OR

1. Delete the auto-generated tempo marking
2. Go to the "Tempo" panel in the sidebar
3. Add the appropriate tempo marking from the palette

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/55305038/c9d252d3-4c36-4e86-9f00-a505dbb47c54

### MuseScore Version

4.2.1.240230937

### Regression

I don't know

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment]
Seems a duplicate of #14678

**Comment by CoolSpy3** [comment]
Ah, my bad! I must've missed it when I scanned through the open issues.

**Comment by cbjeukendrup** [comment]
No worries! It's often difficult to find existing issues unless you know precisely which one you're looking for...
