### ISSUE TITLE
open old musescore 3 files in musescore 4 and all x noteheads for guitar have been changed to parentheses

### ISSUE THREAD

**Issue by nate-enns** [musescore/MuseScore#21463]
### Your idea

The old shortcut "shift x" from musescore 3 changed from x notehead to notehead with parentheses in musescore 4. Therefore, when any old musescore files are opened in musescore 4, then all x noteheads have been changed to notes with parentheses. Hope there will be a future remedy for this other than going back and changing them all manually. 

### Problem to be solved

The old shortcut "shift x" from musescore 3 changed from x notehead to notehead with parentheses in musescore 4. Therefore, when any old musescore files are opened in musescore 4, then all x noteheads have been changed to notes with parentheses. Hope there will be a future remedy for this other than going back and changing them all manually.

**Comment by scorster** [comment]
Related to:  https://github.com/musescore/MuseScore/pull/21371

**Comment by nate-enns** [comment]
Thank you, glad it's being looked into.
