### ISSUE TITLE
Dotted notes are missing the dot for guitar when using "full" tablature

### ISSUE THREAD

**Issue by nate-enns** [musescore/MuseScore#21460]
### Your idea

When notating for guitar with "full" tablature, all of the dots are missing from dotted eights, dotted quarters, etc. I feel this is a regression because the dots were include for full tablature in musescore 3. I realize the dots are visable in treble clef with a linked staff, but there are too many times guitarists would prefer to just use the tablature without a linked staff. 

### Problem to be solved

When notating for guitar with "full" tablature, all of the dots are missing from dotted eights, dotted quarters, etc. I feel this is a regression because the dots were include for full tablature in musescore 3. I realize the dots are visable in treble clef with a linked staff, but there are too many times guitarists would prefer to just use the tablature without a linked staff.

**Comment by oktophonie** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/19036, is fixed in master/the next release.

**Comment by nate-enns** [comment]
Thanks, glad to hear it.
