### ISSUE TITLE
When instruments are invisible only option is to not hear them

### ISSUE THREAD

**Issue by nate-enns** [musescore/MuseScore#21461]
### Your idea

In musescore 4, when instruments are made invisible the instruments are no longer heard. I can see how that is a good feature, but it would be nice to be able to have the option to still hear them if desirable. I think there are users who like the old musescore 3 feature of being able to hide an instrument but still hear it. Would it be possible for a future version of musescore 4 to have both options?

### Problem to be solved

In musescore 4, when instruments are made invisible the instruments are no longer heard. I can see how that is a good feature, but it would be nice to be able to have the option to still hear them if desirable. I think there are users who like the old musescore 3 feature of being able to hide an instrument but still hear it. Would it be possible for a future version of musescore 4 to have both options?

**Comment by MarcSabatella** [comment]
This is being worked on for a future update.

Meanwhile, though, you can still hide parts and still hear them.  The trick is you need to hide the *staff* rather than the whole *instrument*.

**Comment by nate-enns** [comment]
Thanks for your quick reply. The workaround you mentioned is very helpful in the meantime.
