### ISSUE TITLE
Default size of x noteheads too small

### ISSUE THREAD

**Issue by nate-enns** [musescore/MuseScore#21462]
### Your idea

The x notehead size is a lot smaller than what is usually found in sheet music. I know there is a workaround where you can make the noteheads small in properties, and then make the small note size above 100%, but this is pretty tedious procedure. It would be a nice improvement if there was a way to adjust the size of x noteheads or maybe even all noteheads in general in properties. 

### Problem to be solved

The x notehead size is a lot smaller than what is usually found in sheet music. I know there is a workaround where you can make the noteheads small in properties, and then make the small note size above 100%, but this is pretty tedious procedure. It would be a nice improvement if there was a way to adjust the size of x noteheads or maybe even all noteheads in general in properties.

**Comment by oktophonie** [comment]
The X notehead is a perfectly standard size, unless you're referring to the x on tab staves, which is being addressed as part of https://github.com/musescore/MuseScore/pull/21371

**Comment by nate-enns** [comment]
Yes, I was referring to the x on tab staves, glad it's being addressed.
