### ISSUE TITLE
Brass and Suspended Cymbal Crescendos are Choppy and Glitched

### ISSUE THREAD

**Issue by Fungiscrusher84** [musescore/MuseScore#21505]
### Issue type

Muse Sounds bug

### Bug description

A brass crescendo using hairpins from pianissimo to forte is not happening smoothly and is choppy in an exported wav file. It sounds as if it is overlapping in some way or reinitiating the beginning of the note. The same thing is happening with the suspended cymbal in both a wave export AND in midi playback in Musescore.

### Steps to reproduce

1. Open a score in G minor with "Horn in F", "Trumpet in Bb", "Trombone", "Bass Trombone", "Cymbals" -set to Sus. Cymbal in mixer, "Marimba", all using Muse Sounds
2. Set tempo to Quarter note = 68
3. Set Time Signature to 4/4
4. Create a pedal tone roll (32nd tremolo) on the Marimba at piano
5. On Beat 4 of x measure begin a crescendo with the suspended cymbal at pianissimo (use 32nd tremolo as 16th note tremolo is not working), tie to 32nd tremolo whole note in following measure, tie to eighth note in the measure after that at forte
6. On Beat 1 of x+1 measure begin a crescendo with voicings like shown:
![Screenshot 2024-02-13 115833](https://github.com/musescore/MuseScore/assets/59238545/93891255-fb94-4c83-bfc1-da8ada625c11)
7. Listen for midi playback of the suspended cymbal choppiness (also possibly the brass in playback)
8. Export to .wav and listen for choppiness of brass and suspended cymbal

### MuseScore Version

OS: Windows 10 Version 2009 or later (Note: it's actually Windows 11 Build: 23H2 Version: 22631.3007), Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
Please consider attaching a score to save us time, even just this excerpt to reproduce.

You can attach as a .zip file

**Comment by zacjansheski** [comment]
@Fungiscrusher84 am I missing anything?

[21505.mscz.zip](https://github.com/musescore/MuseScore/files/14439048/21505.mscz.zip)


https://github.com/musescore/MuseScore/assets/69917893/8d023e2c-8305-44fe-9aa2-5396ff254888

**Comment by Fungiscrusher84** [comment]
@zacjansheski Interesting. I don't hear it in your playback OR in my playback anymore, but I was absolutely hearing it previously. Perhaps it has something to do with my full instrumentation for a bigger piece? I attached the section of my score that has the problem as well as the wav export (converted to mp3 for github's sake).
[A Hidden Kingdom.zip](https://github.com/musescore/MuseScore/files/14439205/A.Hidden.Kingdom.zip)

**Comment by zacjansheski** [comment]
I'm glad it isn't there anymore!

With no way to reproduce or relevant logs, there isn't any further action to take here.  Thank you!
