### ISSUE TITLE
"harmonics" in the guitar pallette changes the sound but doesn't play the right notes for natural harmonics in TAB

### ISSUE THREAD

**Issue by nate-enns** [musescore/MuseScore#21539]
### Your idea

Natural harmonics for guitar should change the sound and change the note for playback for tablature. When you add the harmonics text from the guitar pallette it just changes the sound to harmonics but it should also change the notes as follows: 12th fret harmonics=up one octave, 7th fret harmonics=up an octave + 5th (17th), 5th fret up two octaves, 4th fret= two octaves + major 3rd. It would also be nice if there was an easy way to add the pointed parentheses to notes in tablature to indicate the use of harmonics.

### Problem to be solved

Natural harmonics for guitar should change the sound and change the note for playback for tablature. When you add the harmonics text from the guitar pallette it just changes the sound to harmonics but it should also change the notes as follows: 12th fret harmonics=up one octave, 7th fret harmonics=up an octave + 5th (17th), 5th fret up two octaves, 4th fret= two octaves + major 3rd. It would also be nice if there was an easy way to add the pointed parentheses to notes in tablature to indicate the use of harmonics.

**Comment by nate-enns** [comment]
to clarify, should be this much higher than the open string: 12th fret harmonics=up one octave, 7th fret harmonics=up an octave + 5th (17th), 5th fret up two octaves, 4th fret= two octaves + major 3rd

**Comment by irwir** [comment]
[Documentation](https://musescore.org/en/handbook/4/guitar-techniques#Notating_harmonics) suggests several ways of writing harmonics. Is it not enough?
