### ISSUE TITLE
Voltas

### ISSUE THREAD

**Issue by RotoSound** [musescore/MuseScore#21538]
### Issue type

General playback bug

### Bug description

MuseScore seems to not respect 1st, 2nd, 3rd endings.
[Jump error.zip](https://github.com/musescore/MuseScore/files/14302433/Jump.error.zip)

### Steps to reproduce

1. Insert 1st, 2nd and 3rd ending.
2. Put a Dal Segno at the end of ending 1 & 2.
3. Playback and notice that the 1st ending gets played twice and then the plackback stops entirely.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10.

**Comment by jeetee** [comment]
Volta's are alternative endings for normal repeats; your score has no repeats in them, so only the first volta can be honored.

Jumps do not increase the repeat count as per standard notation convention, but either play the last normal repeat (default, and in your score thus also the first and only playthrough) or from the 1st repeat (if "play repeats" is checked, but in your score that same only playthrough).

To fix your score, replace the segno with a start repeat barline and each D.S. with just plain end repeats.
Also refer to the online manual on Volta's for further reference: https://musescore.org/en/handbook/4/voltas

**Comment by RotoSound** [comment]
Thanks for the answer. You are right. Please delete my post.
