### ISSUE TITLE
Qt 6.2 Issues

### ISSUE THREAD

**Issue by igorkorsukov** [musescore/MuseScore#21542]
###  Description

Collection of issues when switching to Qt 6.2

### Steps to reproduce

**Build on CI** 
At the moment, we can build a version for Windows with Qt 6 using CI. 
To do this, you need to start manual build, and in the parameters form specify: `Build with Qt5 - off`
<details>

![image](https://github.com/musescore/MuseScore/assets/3818029/b9f7ce57-236e-4367-84bd-383a3a1c7544)

</details>

**Build local:**
* Install Qt 6.2.4 for your system
* Install Qt5 Compat module
* Install Qt Network Auth
* Install Qt State Machine
* Add Qt 6.2.4 to your IDE (if required)
* Delete file CMakeLists.txt.user
* Disable project cmake option MUE_COMPILE_QT5_COMPAT (should be OFF)
* Open the project and select Qt 6.2.4 and Qt 5.15 for its configuration
* Activate configuration with Qt 6.2.4
* Run cmake and build
* Enjoy

<details>

![image](https://github.com/musescore/MuseScore/assets/3818029/8220baa8-0e97-470f-b3de-47277b7b7baa)

</details>

### MuseScore Version

master

### Operating system

All

**Comment by igorkorsukov** [comment]
Can't find QtQuick.Controls 1 in plugins

**Comment by igorkorsukov** [comment]
Quit the application does not work

**Comment by cbjeukendrup** [comment]
Crash when opening Format > Style, because QQuickWidget is only supported with the OpenGL rendering backend.

Workaround: use the OpenGL backend.
Real solution: definitively get rid of all QWidgets.

**Comment by cbjeukendrup** [comment]
Images missing in "How would you like to save" dialogs, because Qt 6 interprets the relative paths relatively to the wrong QML file

**Comment by cbjeukendrup** [comment]
@igorkorsukov We might want to close this issue because it's easier to work with individual issues for each problem, and Dmitry is already creating individual issues, partly duplicating those mentioned here in comments.
