### ISSUE TITLE
Staff line color of staff type changes isn't saved

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#21551]
### Issue type

Opening/saving issue

### Steps to reproduce

1. Add a staff type change to score
2. Go to Properties
3. Change staff line color
4. Save and reload
5. The staff line color is back to black.

### MuseScore Version

MuseScore 4.0 and later

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by sammik** [comment]
please check #21966
