### ISSUE TITLE
Issues with Palette context menu placement and dismissal

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#21553]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

**Expected behavior**
Right-clicking a palette places the context menu in the same place it appears if the three-dot icon is clicked. Clicking the heading of the palette to expand or collapse it dismisses the context menu.

**Actual behavior**
When right-clicking, the menu shows up in a didferent place and it persists when the palette is expanded/collapsed.

### Steps to reproduce

1. Open Palettes
2. Right click on one, see that the menu does not appear beneath the "..." button
3. Click the title of a palette. See that it can be expanded/collapsed, but the context menu remains open

### Screenshots/Screen recordings

The beginning shows the correct placement of the context menu. The rest shows the incorrect behavior.

https://github.com/musescore/MuseScore/assets/20806406/78e91d79-047f-4351-b130-bfcdf700f69e

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

OS: macOS 14.1, Arch.: x86_64

**Comment by krasko78** [comment]
I have a fix for this issue. However, I don't agree that when right-clicking the header, the menu should appear below the ellipsis button. It makes much more sense for the menu to appear at the mouse coordinates.
