### ISSUE TITLE
Crash when attempting to add doits, falls, plops, scoops, slides to grace notes

### ISSUE THREAD

**Issue by gabzony** [musescore/MuseScore#21563]
### Issue type

Crash or freeze

### Bug description

adding doits, falls, plops, scoops, or slides to grace notes crashes the application immediately

### Steps to reproduce

1. Create a grace note
2. Select grace note
3. Open "Arpeggio/glissando" menu
4. Select doit/fall/plop/scoop/slide

### Screenshots/Screen recordings

https://i.imgur.com/7N647nm.mp4 <- video
[musescore diagnostic.zip](https://github.com/musescore/MuseScore/files/14320345/musescore.diagnostic.zip)

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10 Version 22H2 (19045.4046)

### Additional context

CPU: Intel Core i7 7700K
GPU: GeForce GTX 1080
RAM: 16,0GB Dual-Channel DDR4 @ 1070MHz
Drive type: Musescore installed on an HDD, Windows install drive is an SSD

**Comment by zacjansheski** [comment]
I haven't been able to reproduce this
Am I misunderstanding the issue?  Does it happen with a specific score?
Please share any additional info that might help us diagnose/reproduce.  Thank you!


https://github.com/musescore/MuseScore/assets/69917893/471e140c-0cf4-4997-82b0-5e3214480add

**Comment by gabzony** [comment]
Hello

I've attached the score I was working on at the time. Hope that helps you diagnose the issue!

Gab
________________________________
Från: Zac Jansheski ***@***.***>
Skickat: den 20 februari 2024 20:31
Till: musescore/MuseScore ***@***.***>
Kopia: gabzony ***@***.***>; Author ***@***.***>
Ämne: Re: [musescore/MuseScore] Crash when attempting to add doits, falls, plops, scoops, slides to grace notes (Issue #21563)


I haven't been able to reproduce this
Am I misunderstanding the issue? Does it happen with a specific score?
Please share any additional info that might help us diagnose/reproduce. Thank you!

https://github.com/musescore/MuseScore/assets/69917893/471e140c-0cf4-4997-82b0-5e3214480add

**Comment by zacjansheski** [comment]
I see diagnostic files and the video.
When I rewrite the notes in the video and add doit, fall etc.  I do not get a crash, something else must be a factor.
You can share .mscz files here as .zip files

**Comment by zacjansheski** [comment]
Thank you!

I have a minimal example now, the linked staff was a key part of this.

1. Open score template: Guitar + Tablature
2. Write a note with a grace note
3. Change the pitch of the grace note
4. Add doit/fall/plop/etc..

https://github.com/musescore/MuseScore/assets/69917893/129dd03c-1ab9-4b5c-89e5-591aba1fcdda

**Comment by zacjansheski** [comment]
Regression occured between 4.0.2 and 4.1.0

Fresh diagnostic files:
[GraceCrash.zip](https://github.com/musescore/MuseScore/files/14351141/GraceCrash.zip)

**Comment by rgreen5** [comment]
Another instance attached here.
[slide_crash.zip](https://github.com/musescore/MuseScore/files/15366594/slide_crash.zip)

Clicking on any of the slides in measure 1 causes a freeze then crash.

**Comment by bkunda** [comment]
Demoting for now because, although it's quite bad, it's unfortunately not a recent regression.
