### ISSUE TITLE
Coloring a beamed chord colors whole beam group

### ISSUE THREAD

**Issue by rettinghaus** [musescore/MuseScore#21572]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When selecting a beamed chord and coloring it, everything in the whole bream gets colored (except all the stems from unselected chords/notes). 

I would expect only the selected chord to be colored. 

### Steps to reproduce

1. beam some chords
2. select a chord
3. color it
4. all chords are colored

### Screenshots/Screen recordings

<img width="376" alt="image" src="https://github.com/musescore/MuseScore/assets/7693447/9caefe83-7ffc-4fd9-a46a-ea9845d1cea3">

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

macOS 14

**Comment by cbjeukendrup** [comment]
The cause of this is probably similar to the one of #21285
