### ISSUE TITLE
Flutter tongue interrupts tied notes in some woodwinds

### ISSUE THREAD

**Issue by julenComposer** [musescore/MuseScore#21592]
### Issue type

Muse Sounds bug

### Bug description

Dear devs, apparently at least some woodwinds cannot produce continuous fluttertonguings across tied notes, so you can distinguish the attack of each note as they were not tied. I've found this occurring on flute, alto saxophone and baritone saxophone, but it might happen as well to other instruments.

### Steps to reproduce

1. Create a score with some woodwinds, including at least flute, alto and baritone saxophones,
2. Make sure you're using Muse Sounds for the playback
3. Write some tied notes on each staff,
4. Apply 32nds tremolos to all the notes,
5. Hit playback and check if tied notes produce continuous fluttertonuge sounds or if it gets interrupted on each note

### MuseScore Version

4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

### Additional context

I'm really sorry, but I can't really remember if this used to work in previous versions or not. I somehow bet it did, otherwise I think I would have noticed.

**Comment by Valdessir** [comment]
Probably related to #20327

**Comment by bkunda** [comment]
@RomanPudashkin looks like another instance of our tied note issues.
