### ISSUE TITLE
Resequence rehearsal marks counts all system objects

### ISSUE THREAD

**Issue by bakajikara** [musescore/MuseScore#21617]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When multiple system objects are present, as in the SATB+Piano template, the Resequence rehearsal marks count all system objects and do not work properly.

### Steps to reproduce

1. Create a score using a template with multiple system objects, e.g., SATB+Piano template.
2. Add some rehearsal marks to the score.
3. Execute Resequence rehearsal marks.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

No.

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
Got to be a Mu3 regression, as that can't have system texts on staves other than the topmost
