### ISSUE TITLE
Updating measure numbers after section break regression

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#21621]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Measure numbers after a section break do not update as they did in 4.1.1 after unchecking "Reset Measure numbers for new section"

### Steps to reproduce

1. Make a score with a section break
2. Uncheck "Reset Measure numbers for new section" in properties

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/96f04ba5-282e-4b7e-8ee2-ec5324fe23a2

### MuseScore Version

OS: macOS 14.2, Arch.: x86_64, MuseScore version (64-bit): 4.3.0-240520506, revision: github-musescore-musescore-0fa51e6

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 14

**Comment by worldwideweary** [comment]
This seems to be due to #20141 for optimizing layout.
Probably @mike-spa should double-check the section break layout code...
