### ISSUE TITLE
The shortcuts W/Q for lengthening/shortening a note jump to the next note

### ISSUE THREAD

**Issue by avronp** [musescore/MuseScore#21639]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Q/W have been features of all versions of museScore which worked seamlessly on the current note.
Now the cursor loses focus and jumps to the next note to shorten/lengthen it

### Steps to reproduce

1. Enter a note
2. Press Q (or W)
3. The cursor jumps to the next note

### MuseScore Version

 4.2.1.240230937

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
This is not actually a bug by a deliberate design change intended to improve note input on tablature staves, which normally require Shift to access the duration keys.  Also to emulate a note input system used by other tablature program, apparently.

However, I am not at all convinced this change should have been made to apply to standard staves, and support seeing this reverted there.  See also https://github.com/musescore/MuseScore/issues/10680 for further context.

Meanwhile, Shift+Q/W continue to work retroactively.
