### ISSUE TITLE
Bold, Italics and other standard font editing shortcuts don't work

### ISSUE THREAD

**Issue by avronp** [musescore/MuseScore#21638]
### Issue type

Other type of issue

### Steps to reproduce

1. Select some text
2. Click <CTRL> + B or <CTRL> + I.
3. Nothing happens

### MuseScore Version

 4.2.1.240230937

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
This has been reported befoe, see for example https://github.com/musescore/MuseScore/issues/17989 and https://github.com/musescore/MuseScore/issues/14496 - thanks for reporting, though!
