### ISSUE TITLE
Vertical spacers not visible in the score when selected from the Layout Palette

### ISSUE THREAD

**Issue by avronp** [musescore/MuseScore#21641]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When selecting one of the vertical spacers fro the layout panel no line spacer appears in the score. The expand box at the end of the spacer line seems to appear only when selecting the line twice.

### Steps to reproduce

1. Open the layout palette
2. Select one of the vertical line spacers
3. Drag to stave or staff where it is to be used
4. No vertical line appears and the expand box appears intermittently

### MuseScore Version

 4.2.1.240230937

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
Closing, unable to reproduce, no response
