### ISSUE TITLE
Musescore does not open

### ISSUE THREAD

**Issue by pavanleeuwen** [musescore/MuseScore#21656]
### Issue type

Opening/saving issue

### Bug description

I was alerted by Musescore that i had to upgrade to the next version. I clicked this button, and a reinstall started. At a certain moment the new version Musescore opened, with topleft the text "Musescore4" on a totally white screen. I closed Musescore, and and downloaded MuseScore-4.2.1.240230937-x86_64.msi. I had the option to "repair" and/or "install". I used both options with the same result. I also used "De-install" feature of Windows. Same result. When i open this install from a name.mscz file, Musescore opens with the "name" in the topleft corner on this white screen. Please advice

### Steps to reproduce

see above
![musescore white screen](https://github.com/musescore/MuseScore/assets/161045672/9407169c-42f6-4cbe-a219-218f89de7313)

### Screenshots/Screen recordings

There is no Help, as Musescore does not open. It was installed from MuseScore-4.2.1.240230937-x86_64.msi

### MuseScore Version

It was installed from MuseScore-4.2.1.240230937-x86_64.msi

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

It was installed from MuseScore-4.2.1.240230937-x86_64.msi

**Comment by DmitryArefiev** [comment]
@pavanleeuwen I've never seen that strange issue..

1. From what MuseScore version you're updated to 4.2.1?
2. What Windows version you have (Pro, Home etc.)?
3. All latest updates are installed on your Windows 10?


Also, you can try to reset Factory setting by deleting these folders:
* c:\Users\_username_\AppData\Local\MuseScore\MuseScore4\
* c:\Users\_username_\AppData\Roaming\MuseScore\

That might help. But you will lost your custom workspaces, shortcuts etc. (copy them to another location if you want to save it)

**Comment by pavanleeuwen** [comment]
Hi Dmitry,

 

I have now 



I don’t know the previous version.

I deleted the directories as you pointed out, and it worked immediately without reinstall!

 

Please see below for some answers to your question.

 

Thanks for the advice, 

 

Regards, 


Pieter

**Comment by DmitryArefiev** [comment]
> I deleted the directories as you pointed out, and it worked immediately without reinstall!
Glad to see it works now! Thanks!

Closing
