### ISSUE TITLE
Crash while typing in palettes search

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#21657]
### Issue type

Crash or freeze

### Bug description

Sometimes, while typing in the search bar in the palettes panel, MuseScore 4.3 crashes.

This has happened to me 5 or 6 times but I can't figure out exact steps to replicate it. It feels random but usually does not happen when using the search right after opening a score.

### Steps to reproduce

1. Have a score open for a while, do some engraving
2. Open palettes
3. Type in the search bar
4. Crash

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: macOS 14.1, Arch.: x86_64

**Comment by avvvvve** [comment]
Looks like this was mentioned in #12753 in 4.0

**Comment by zacjansheski** [comment]
Reproduced (lets keep this open)

[PaletteSearchCrash.zip](https://github.com/musescore/MuseScore/files/14389122/PaletteSearchCrash.zip)

**Comment by zacjansheski** [comment]
https://github.com/musescore/MuseScore/assets/69917893/0eb30866-712e-4a55-ac0c-5d5f567cfa7e

**Comment by krasko78** [comment]
I can confirm this. Crash happens in **QmlToolTip::showToolTip** (in moc_qmltooltip.cpp). See attached acreenshot. I am able to reproduce it relatively easily by hovering over a palette element and before the tooltip appears (I think the delay is 500ms) I press CTRL+F9 quickly. Most likely sometimes showToolTip gets called on a destroyed element even though there is logic that hides/cancels the tooltip when the element gets destroyed. It looks like depending on the timing, this does not always work which explains the random behavior.
![palette_search_crash](https://github.com/musescore/MuseScore/assets/154632626/7324ab1c-7dbc-4f07-a351-556904865313)
.
