### ISSUE TITLE
[Qt6 migration] 4.0.0  doesn't see user plugins

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#21659]
### Steps to reproduce

1. Add 
[abc_import-4.0.0.zip](https://github.com/musescore/MuseScore/files/14387382/abc_import-4.0.0.zip)
[batch_export-master.zip](https://github.com/musescore/MuseScore/files/14387383/batch_export-master.zip) to c:\Users\_user name_\Documents\MuseScore4Development\Plugins\
2. Run MuseScore

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/a3add52a-ac0d-4725-8e7e-b9ac0700bc90

### MuseScore Version

4.4.0

### Regression

Yes, this used to work in **MuseScore 4.3**

### Operating system

Windows11/Mac13.6

**Comment by cbjeukendrup** [comment]
The reason is that these plugins are not valid for Qt 6; they need to be rewritten. Perhaps, instead of ignoring them completely, we could display these plugins as "invalid", so that the user understands what's going on. Maybe we can even catch the error messages that Qt gives when trying to load these plugins, and somehow convey these to the user, so that the user can try to fix them.

**Comment by bkunda** [comment]
Okay, so a simple design solution here would be to still show the "invalid" plugins with a reduced opacity, and perhaps a warning sign label. 

But at this stage the 0-development solution (preferable from a time POV) though would be just to ensure we have this covered in our documentation. @shoogle could you please add this as an FAQ on the website? (E.g. "Why aren't some of my plugins showing up in MuseScore Studio").

**Comment by shoogle** [comment]
**Note for plugin authors:** [these commits](https://github.com/musescore/MuseScore/commits/7fe32bacbc9287b716d40462afb713da52bbde97/share/plugins?since=2024-02-20&until=2024-02-21) show the changes required to get plugins working with Qt 6.

**Comment by Jojo-Schmitz** [comment]
The good part is that these 2  plugins never really worked for Mu4, due to #13593/#20822

**Comment by Jojo-Schmitz** [comment]
But these tips don't seem to help much, I can only get a blank window for batch_convert

**Comment by lgvr123** [comment]
Hi, is there a "plugin migration cookbook" somewhere ? 
In order to help the plugins' developer not reinventing the wheel for every migration.
I received already notifications from users that several of my plugins don't work any more on MU4.4. And this will take a hell of a time migrating everything and while maintaining a cross-version compatibility (MU3.6.2-3.7/MU4.0..4.3/MU4.4). 
Some support will definitively welcome and helpful.

**Comment by shoogle** [comment]
> is there a "plugin migration cookbook" somewhere?

@lgvr123, do [these commits](https://github.com/musescore/MuseScore/commits/7fe32bacbc9287b716d40462afb713da52bbde97/share/plugins?since=2024-02-20&until=2024-02-21) help? Look at the diff for the QML files within each commit.

**Comment by shoogle** [comment]
How do the [4.4 comments](https://github.com/musescore/MuseScore/wiki/Updating-plugins-for-MuseScore-Studio-4.4#plugin-title-etc) get parsed? Is that a Qt feature or something we've added ourselves?

**Comment by Jojo-Schmitz** [comment]
We added that.

**Comment by shoogle** [comment]
Right, but how does it work? Are we parsing comments manually or does Qt provide that as a feature?

**Comment by Jojo-Schmitz** [comment]
IIRC the former.

**Comment by cbjeukendrup** [comment]
See `ExtPluginsLoader::parseManifest`.

To be honest, I'm _really_ not a fan of this approach of parsing QML files manually, and don't fully understand why we don't just load the QML file as a temporary QML component, then get its properties, and then discard the object. But maybe parsing manually is significantly more performant, I guess...

**Comment by jeetee** [comment]
Or use a default JSON parser if you don't want to go full instantiation. It'd also solve a bunch of other very naïve parsing assumptions such as which time of string delimiter quotes should be used etc..

**Comment by cbjeukendrup** [comment]
Contrary to what the name suggests, `ExtPluginsLoader::parseManifest` parses QML files rather than JSON. (And feeding QML into a JSON parser doesn't go well.)

`ExtensionsLoader::parseManifest` which is for "new" extensions, does use a normal JSON parser.

**Comment by lgvr123** [comment]
I'm following closely this discussion: should I read (between the lines) that you aim at providing a king of retro-compatibility for plugin's written following the 4.0...3 rules/framework ? And that it won't be necessary to adapt all the plugin's running fine under 4.0..3 to have them working on 4.4 ?

**Comment by lgvr123** [comment]
> Here is such a guide: https://github.com/musescore/MuseScore/wiki/Updating-plugins-for-MuseScore-Studio-4.4
Is it possible to **generate** some kind documentation for all the `Muse.UIComponents` ?

**Comment by MarcSabatella** [comment]
Regarding the "4.4" comments - does that mean "4.4 or later", or will we also need to continually update plugins with new comments for 4.4.1, 4.4.2, 4.5, etc?  I would certainly hope not, but it does seem a kind of oddly specific choice of syntax.
