### ISSUE TITLE
Keyboard Shortcut to Move Dynamics between chords/rests

### ISSUE THREAD

**Issue by julenComposer** [musescore/MuseScore#21664]
### Your idea

Dear devs, I propose to you to extend the functionality of the `shift`+`left`/`right` shortcut now used to extend/shorten slurs, lines and hairpins also to move around other items of the score, such as dynamics or texts.

### Problem to be solved

Currently, by dragging dynamics with the mouse, also the hairpins connected to them will stretch along. 

https://github.com/musescore/MuseScore/assets/122049426/8b668ba0-00e6-4ae7-a16c-68196af28fa9

However, as you can see, in this way you have to adjust the position of the item by hand, whereas with the keyboard shortcut users might save some time, because it would be managed automatically, just as for lines and slurs.

https://github.com/musescore/MuseScore/assets/122049426/c2c6b3f9-24d7-482e-b516-0abd72935bdb

(here I've created an hairpin with "ppp" in the beginning just to show you the possible feature, but please imagine an actual dynamic being moved instead)
Also, in this way you could extend the keyboard controls, maybe for an even more fluent workflow.

**Comment by oktophonie** [comment]
This will be coming as part of https://github.com/musescore/MuseScore/pull/21633

**Comment by avvvvve** [comment]
@julenComposer Happy to say this has been implemented in #21633, which you can try out in the [latest master](https://ftp.osuosl.org/pub/musescore-nightlies/)! It should be available in the upcoming 4.4 release. Closing this issue as resolved.

**Comment by julenComposer** [comment]
Very cool, thank you all a lot! Glad to have added something to this!
