### ISSUE TITLE
`minimumTieLength` not respected for tie segments ending after forward repeat on new system

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#21667]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

![image](https://github.com/musescore/MuseScore/assets/116587995/96c91ab1-fe16-48ab-9980-a1b6fd50c3c6)
In the top example, the tie segment follows the `minTieLength` style setting and is the correct size.
In the bottom example, the tie segment is too small. This effect becomes increasingly visible as `minTieLength` increases, whereby the lower tie does not change size.

### Steps to reproduce

1. Add a forward repeat on a new system
2. Add a tie that ends on a note just after said repeat.

### MuseScore Version

4.2.1

### Regression

No.

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
No difference using the vtest score in Mu3, so this got to be a Mu3 regression

**Comment by cbjeukendrup** [comment]
@oktophonie Because the linked PR was closed due to inactivity, this was moved out of "in progress", so you might want to consider whether this should stay in the 4.4 project.
