### ISSUE TITLE
Request to add a missing instrument name

### ISSUE THREAD

**Issue by tpgettys** [musescore/MuseScore#21662]
### Your idea

I have created a score, and wish to change an instrument, so I double-click the instrument name, and am presented with a dialog titled "Staff/Part properties". Under "Part properties" there is a button titled "Replace instrument...". When I click that, at the top-left is button titled "Family".

After I select the Early Music family, I see "Treble Viol", "Alto Viol" and "Tenor Viol", but inexplicably, there is no "Bass Viol". Instead, there is a "Viola da Gamba". There are four sizes of Viola da Gamba, Treble, Alto, Tenor and Bass. Please change "Viola da Gamba" to say "Bass Viol".

### Problem to be solved

There is an instrument missing from the family of Viola da Gamba, specifically the Bass Viol

**Comment by tpgettys** [comment]
I have no problem with that.  The most important thing is to add a "Bass Viol" to the list.

On the one hand, keeping Viola da Gamba as well may create uncertainly in the user's mind (what does that mean?  What is the distinction between it and the others?)  In the recorder family there are 8 'flavors' offered in MuseScore.  Should we then add a generic "Recorder" for that group as well?

On the other hand, when one says 'The Viola da Gamba' they almost certainly mean a bass viol.  Likewise, 'The Recorder' almost certainly is an Alto Recorder.

**Comment by Jojo-Schmitz** [comment]
Seems there was a generic instrument in 3.x, like a plain Recorder (to mean the Soprano Recorder!), similar for Trumpet to mean Trumpet in Bb, but there isn't anymore in 4.x?

**Comment by tpgettys** [comment]
I can see the value of having a generic instrument, especially for a transposing instrument like the trumpet.  Bb makes sense for a "Trumpet".  Likewise Bass Viol for "Viola da Gamba", and Alto Recorder for "Recorder" (the alto plays at pitch, whereas the soprano plays an octave higher than written).

**Comment by Jojo-Schmitz** [comment]
Ahh! Aparently I confsed that due to their German names, Soprano Recoder -> C-Flöte, Alto Recorder -> F-Flöte, but that's just their lowest pitch, not their transpositioning

**Comment by MarcSabatella** [comment]
I disagree that most people associate the generic term "recorder" with alto.  The soprano is *by far* more common, at least in the US.  Every school child learns to play one as part of the regular curriculum.  Pretty much everyone in the US is familiar with soprano recorder and knows it simply as "recorder", and few even know that other recorders exist.

It may of course be different in other countries, or within the field of early music specialists.

**Comment by Jojo-Schmitz** [comment]
As mentioned, same in Germany

**Comment by oktophonie** [comment]
'Generic' instruments were removed because they were literally duplicates of a more specific instrument with a different name, so they were needless clutter in the definitions file.

What might be nice is a way to define alternative names (aliases) for instruments, so that you can find them (and add them to the score) with different names.

**Comment by Jojo-Schmitz** [comment]
Something like

```xml
            <Instrument id="recorder-generic">
                  <init>soprano-recorder</init>
                  <family>recorders</family>
                  <trackName>Recorder</trackName>
                  <longName>Recorder</longName>
                  <description>Soprano or descant. Pitched in C.</description>
                  <genre>common</genre>
                  <genre>classroom</genre>
            </Instrument>
```
BTW, soprano recorder currently is in `<genre>earlymusic</genre>` in in that only, that seems very wrong. There also is
```xml
            <Instrument id="recorder">
                  <family>recorders</family>
                  <description>Soprano or descant recorder, pitched in C.</description>
                  <musicXMLid>wind.flutes.recorder</musicXMLid>
                  <clef>G8va</clef>
                  <barlineSpan>1</barlineSpan>
                  <aPitchRange>72-93</aPitchRange>
                  <pPitchRange>72-98</pPitchRange>
                  <Channel>
                        <!--MIDI: Bank 0, Prog 74; MS General: Recorder-->
                        <program value="74"/> <!--Recorder-->
                  </Channel>
                  <genre>common</genre>
                  <genre>classroom</genre>
            </Instrument>
```
But that is is lacking track-, long- and short name?!?! And so not offered at all. Seems e remnant of the former 'generic' one

**Comment by Jojo-Schmitz** [comment]
For the topic at hand here:
```xml
            <Instrument id="bass-viol">
                  <init>viola-da-gamba</init>
                  <family>viols</family>
                  <trackName>Bass viol</trackName>
                  <longName>Bass viol</longName>
                  <shortName>B. Vl.</shortName>
                  <description>Bass viol, also known as Viola da gamba.</description>
                  <genre>earlymusic</genre>
            </Instrument>
```

**Comment by Jojo-Schmitz** [comment]
See my draft/sample PR #21719

**Comment by Jojo-Schmitz** [comment]
Similar issue for Flageolett, Ocarina and probably many many more

**Comment by tpgettys** [comment]
My reading of the above comment by [oktophonie](https://github.com/oktophonie) is that there are no longer any generic instruments.  Since someone is addressing this request they might want to add "Soprano recorder" to the "Classroom" family.  Right now there is only a tin whistle in the woodwinds.

**Comment by shoogle** [comment]
> After I select the Early Music family, I see "Treble Viol", "Alto Viol" and "Tenor Viol", but inexplicably, there is no "Bass Viol". [...] Please change "Viola da Gamba" to say "Bass Viol".

@oktophonie, are you happy with this change?

**Comment by tpgettys** [comment]
I just installed v4.3.1 and there is *still* no Bass Viol in the instrument list!  The bass is simply one of the instruments in Viola da Gamba family (and arguably the most common), so its omission is perplexing.    Can I do something to help this along?

**Comment by shoogle** [comment]
@tpgettys, that's to be expected. Firstly, the issue is still open, which means it hasn't been fixed yet. Secondly, when it does get fixed, the fix will arrive in a minor release (e.g. 4.4) rather than in a patch release like 4.3.1.

Patch releases are reserved for important bug fixes, whereas this issue is more of a suggestion / feature request.
