### ISSUE TITLE
The name of the item in the Order dropdown box of the Choose Instruments window is Orchestral instead of Orchestra

### ISSUE THREAD

**Issue by scoreorder** [musescore/MuseScore#21668]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The name of the item in the Order dropdown box of the Choose Instruments window is Orchestral instead of Orchestra. I propose to change the name Orchestral to Orchestra in order to name the items of the Order dropdown box consistently after music ensembles.

### Steps to reproduce

1. Create new score
2. Open Order dropdown box

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/160652750/957ac3c3-af8d-4250-83ef-b4a3b845d913)

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Windows 11

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/22514
