### ISSUE TITLE
The order of the Bass Trombone instrument and the Contrabass Trombone instrument is incorrect

### ISSUE THREAD

**Issue by scoreorder** [musescore/MuseScore#21670]
### Issue type

Other type of issue

### Bug description

The order of the Bass Trombone instrument and the Contrabass Trombone instrument is incorrect. I propose to change the order.

### Steps to reproduce

1. Create new score
2. Add Bass Trombone instrument
3. Add Contrabass Trombone instrument

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/160652750/3a1b9535-b437-4e99-ba09-bbac17aa7e0f)

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
Seems to ba a Mu3 regression, that does have them in the correct order

**Comment by zacjansheski** [comment]
FIXED by https://github.com/musescore/MuseScore/pull/21810
