### ISSUE TITLE
Muse Sounds doesn't play back accent marks. It used to

### ISSUE THREAD

**Issue by Thedoczek** [musescore/MuseScore#21673]
### Issue type

General playback bug

### Bug description

A while ago I made a piece that relied heavily on snare drum doing accents - visible [here](https://thedoczek.github.io/Skylines/ArcadeMemories.mp3) (this one was made in May 2023, the very beginning is enough). However, I am currently not able to reproduce this behavior, because accent is played as a regular note. This is not limited to snare drum, but to all instruments. Here's [a sample I rendered today](https://drive.google.com/file/d/14yCCggimAXH-7Q0N8O24SMuzXJ4BZfxZ/view?usp=sharing) - the beginning of the exact same piece (note that it's not 1:1 copy - it's sligtly faster and may have slightly different volume proportions). You can see thall all the drum notes are played equally

### Steps to reproduce

1. Place a note
2. Add an accent mark to it
3. The accent mark is not played back, as it used to be

### Screenshots/Screen recordings

Here's the score screenshot if anyone needs for reference
![image](https://github.com/musescore/MuseScore/assets/69758777/9bc8e50c-8e0f-4167-8b00-742110a2a3fe)

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by bkunda** [comment]
@zacjansheski pls check whether this has already been fixed.

**Comment by zacjansheski** [comment]
Fixed in Muse Sounds
