### ISSUE TITLE
Multimeasure rests causes crash when using Realize Chord Symbols feature

### ISSUE THREAD

**Issue by cadiz2** [musescore/MuseScore#21672]
### Issue type

Crash or freeze

### Bug description

The title sums the problem

### Steps to reproduce

1. Create new score,  6 measures, with the third measure containing  a Chord symbol, and a filled last measure.
2.  Press "M" for enabling multimeasure rests. 
3. Save/Close/Reload
4. Select All 
5. Menu Tools -> Realize Chord Symbols

Result: crash

### Screenshots/Screen recordings

![Video chord symbols](https://github.com/musescore/MuseScore/assets/114975887/ef564d46-8c4d-4c8f-bf8e-3856c7d7a898)

### MuseScore Version

 MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

Yes. Works with 3.6.2.
I don't know for versions 4.0. or 4.1 (or 4.2.0) 

### Operating system

Windows10

### Additional context

No crash if the filled last measure is removed. 
And of course if multimeasure rests are disabled.

Related post on the forum: https://musescore.org/en/node/360966

**Comment by Jojo-Schmitz** [comment]
Works in 4.1.1, crashes in 4.2.0 and 4.2.1, so a 4.2 regression

**Comment by Jojo-Schmitz** [comment]
Crashes with 3.6.2 too

**Comment by Jojo-Schmitz** [comment]
No it does not.

But it does when there is no note in the measure with the chord symbol

**Comment by Jojo-Schmitz** [comment]
There are still issues:
When relizing a chord symbol in a multimeasure rest, like this:
![image](https://github.com/user-attachments/assets/86cdeacc-ea97-41da-8e5b-99e07b927e5f)
We end up with this:
![image](https://github.com/user-attachments/assets/90aee331-c41e-4b26-8799-6179a585314b)
Not really wrong, just pretty strange, without Format > Style > Score > Display note values across measure boundaries being set.
Also strange are the accidentals on the tied to chord. Disabling multimeasure rests turns it into this:
![image](https://github.com/user-attachments/assets/b9e3aa9d-64d0-4341-beea-7e6c3e18da3d)
