### ISSUE TITLE
Clef changes collide with multi-measure rests in old-style

### ISSUE THREAD

**Issue by dpMusicman** [musescore/MuseScore#21683]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When using old-style multi-measure rests, H-bar multi-measures (longer than the maximum, e.g. 9 as the default) will collide with clef changes.

### Steps to reproduce

1. Create a clef change a number of bars beyond the maximum of old-style rests (e.g. 10)
2. In the Style window, select Rests > Multimeasure rests > Old-style multimeasure rests

### Screenshots/Screen recordings

<img width="398" alt="clef change collision" src="https://github.com/musescore/MuseScore/assets/91439512/218ad4e3-fdbe-4dc4-a162-187f84a35cc4">

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

macOS 13

**Comment by LupusCaeruleus** [comment]
Seems related to https://github.com/musescore/MuseScore/issues/17810?
