### ISSUE TITLE
Unchecking show barlines makes barlines move randomly and add space to the end of a system.

### ISSUE THREAD

**Issue by onnogli** [musescore/MuseScore#21680]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

The barline at the end of the page gets moved away from the margin. This doesn't tell MuseScore that anything has changed in the score, and it can't be saved. So opening the file again will change the amount of space there.

### Steps to reproduce

- Add an instrument
- Go to Staff/Part properties
- Uncheck Show Barlines
- One of
  - Click and drag the barline
  - Changing concert/transposed pitch
  - Changing page view
 - Barline moves away from the right

### Screenshots/Screen recordings

This is what it looks like when I open the score
![image](https://github.com/musescore/MuseScore/assets/103379965/e28ac31a-7ead-4075-ae44-5b87db2ab65e)

This is what dragging the barline does.
![2024-02-25 17-19-00](https://github.com/musescore/MuseScore/assets/103379965/3b8f8784-16f5-4469-a8de-f9d23b349ec0)

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937

### Regression

I don't know

### Operating system

Windows 10

**Comment by oktophonie** [comment]
Closing as some form of https://github.com/musescore/MuseScore/issues/21485
