### ISSUE TITLE
The symbol and the verbal instruction "laissez vibrer" (l.v.)

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#21684]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Dear comrades, first of all, I want you to understand that I know that this problem is partially formulated under the #20919  and #16726 . I want to combine these formulations and create a separate query dedicated to this term in more detail. There will be more information here. 
"_Laissez vibrer_" — this is an instruction not to damp an instrument that has natural sustaining
resonance. The instruction applies to sounds that are sustained naturally by
an instrument, not held manually, and which are not to be damped until
indicated (if at all). 
Usually, this instruction is never fully written out and instead the abbreviation l.v. is used. Instead of a verbal indication, in practice, a symbol is most often used - the so-called "French" tie.
The abbreviation l.v. should be indicated to the right of the note or replaced with a line.

Currently, there is still no normal correct automatic placement of this symbol in Musescore. Instead of putting the tie to the right of the note, the program automatically places it above (or below) the note/a chord in the center: 
![Снимок экрана (107)](https://github.com/musescore/MuseScore/assets/134041121/4f2b5273-19fc-4cde-b015-b1fbcd064ed0)
I want to take into account that in the case of a chord, the tie should move away from each note of the chord (or on individual notes - at the user's choice)! This practice is usually used on the harp: 
![Снимок экрана (108)](https://github.com/musescore/MuseScore/assets/134041121/533ee3d8-5f82-4c19-8290-e033f5511c69)
Currently, unfortunately, the Musescore development team has not yet solved this problem (if it ever started to solve it at all). I consider this a tragedy, because the problem has existed for a very long time, and such symbols are very widely and often used in harp and percussion. 
Of course you can say: why don't you use a verbal designation instead of a symbol? There is a very simple explanation for this: it is visually better to distinguish a symbol, it is easier to notate and convenient to use. And in order to add the l.v. instruction, I also need to apply the correct location for this instruction - move it as shown in the example above. Moreover, the instructions may not always accurately convey which note needs to be made to vibrate:
![Снимок экрана (109)](https://github.com/musescore/MuseScore/assets/134041121/d84ee3e5-25a7-40e9-bf9e-f4a5ed671b97)
This instruction is so often used that I suggest adding this symbol to the toolbar - a symbol or a verbal indication "L.V." (but first you need to make sure that the symbol is displayed correctly in the notation). In the style settings of this instruction, you can set either "symbol" or "word designation" (l.v.) by default. The most important thing is that the user can choose the notation style that is convenient for him.

### Steps to reproduce

1. Enter any note/chord on the stave.
2. Add to this note/chords a symbol from the palette (code name: "articLaissezVibrer")

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

No.

### Operating system

Windows 11

### Additional context

Please do not close my issue as a duplicate, but leave it open, since my issue describes this problem more extensively.

**Comment by Dima12357** [comment]
At the same time, I am silent about the more complex notation of this instruction: 
![Снимок экрана (111)](https://github.com/musescore/MuseScore/assets/134041121/2cb49e46-d850-4e04-836a-85e1479989b3)

**Comment by oktophonie** [comment]
Yes, it describes the problem extensively, but we are already perfectly aware of the requirements and this _is_ a duplicate. It also is a feature request rather than a bug. Also, please don't post excerpts from _Behind Bars_ which we're all perfectly capable of reading for ourselves.
