### ISSUE TITLE
[Qt6] Cmd+A (Select all) shortcut doesn't work on macOS

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#21696]
### Issue type

Qt6.2 migration bug

### Steps to reproduce

1. Open score
2. Press Cmd+A

### MuseScore Version

4.4

### Regression

Yes, this used to work in **MuseScore 4.3**

### Operating system

Mac13.6

**Comment by cbjeukendrup** [comment]
This seems fixed on the master branch, most likely by https://github.com/musescore/MuseScore/pull/23003, so I think we can close it
