### ISSUE TITLE
Edit staff type

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#21698]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When changing the type of the staff from five-line to one-line (two or more - it does not matter), the one-line staff is automatically aligned along the upper line of the staff. In theory, the staff should align with the center line of a five-line staff, whether it is one-line, two or more (any other with less than five lines). This is written in the manual of Kurt Stone and Elaine Gould (I cannot publish excerpts at the urgent request of the contributor, although this would simplify the search for evidence to confirm what I have said). 
![Снимок экрана (115)](https://github.com/musescore/MuseScore/assets/134041121/d556a7bc-23d0-4c91-beaf-8f284cbdc591)
But that's not the main problem. It is very good that currently there is a possibility of vertical alignment of a new type of staff. This way I can align a single-line staff along the center line with a five-line staff. But unfortunately, some elements are not aligned vertically. This applies to the percussion key, staff text, ties, as well as staff text line. It looks very ridiculous.
![Снимок экрана (116)](https://github.com/musescore/MuseScore/assets/134041121/fdd7500a-84aa-43fa-a567-ab1cac36700d)
Ideally, it should be done so that when alternating such staffs, the middle lines are a priori aligned and this would not have to be done manually.

### Steps to reproduce

https://github.com/musescore/MuseScore/assets/134041121/64e9619f-2cae-4bc0-93fa-45d64f9a8147

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

**Comment by oktophonie** [comment]
PLEASE look to see if issues already exist - or even fixes, because there's an open PR that does what you want: https://github.com/musescore/MuseScore/pull/20767

**Comment by sammik** [comment]
@oktophonie I think, this is a different issue.

Not noncentering one-line staff is issue, but wrong placement of some elements on staff with offset is issue.
namely: text, lines, ties
(clef was already fixed in past)

see:

https://github.com/musescore/MuseScore/assets/1646034/1a9e7775-a060-45c2-9bec-05d3f4bddff5

So I think, it should be reopened, but retitled, of course.

**Comment by oktophonie** [comment]
Such things exist as other issues, e.g. https://github.com/musescore/MuseScore/issues/19039, https://github.com/musescore/MuseScore/issues/19222 etc

**Comment by Dima-S-Jr** [comment]
> Such things exist as other issues, e.g. #19039, #19222 etc

@oktophonie, do these things exist in any issues?

https://github.com/musescore/MuseScore/assets/134041121/427986ce-a8f6-4c83-9386-43cece356198

![Снимок экрана (350)](https://github.com/musescore/MuseScore/assets/134041121/077907fa-b48f-4250-825c-381ce77bdf52)
