### ISSUE TITLE
Numbering of bar repeats signs

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#21704]
### Your idea

I suggest making automatic numbers over the signs of bar repeats.
![Снимок экрана (123)](https://github.com/musescore/MuseScore/assets/134041121/dc6a2b9e-dd5b-42aa-8735-f53c2c173592)

### Problem to be solved

This will allow the players (or the conductor) to better navigate long repetitions of the same measure.
At the moment, the numbering of such repeats cannot be set either manually or automatically.
I suggest creating such a numbering style so that the user can either assign such automatic numbering or cancel it.

**Comment by MarcSabatella** [comment]
This is already possible to do automatically via the settings in Format / Style / Measure repeats, as well as manually by adding text (although there isn't currently an option to center the text automatically).

In the future, please ask on the forum at musescore.org to confirm whether a feature already exists - or whether an existing request for it already exists, or to develop a consensus about how a proposed feature could work - before opening an issue here on GitHub.

**Comment by Dima12357** [comment]
> This is already possible to do automatically via the settings in Format / Style / Measure repeats, as well as manually by adding text (although there isn't currently an option to center the text automatically).
> 
> In the future, please ask on the forum at musescore.org to confirm whether a feature already exists - or whether an existing request for it already exists, or to develop a consensus about how a proposed feature could work - before opening an issue here on GitHub.

Thank you so much for the clarification.
