### ISSUE TITLE
[Feature Request]: Auto MIDI Note Velocity with Dynamic Markings

### ISSUE THREAD

**Issue by cunningar0807** [musescore/MuseScore#21710]
### Your idea

One time I've accidentally changed the Note Velocity in the playback properties, and it applied to all of the selected elements in the parts. After when I've reset the note velocity to 64, I thought things were normal. When I exported the MuseScore project into .midi format and imported the file into other daw programs like GarageBand or Reaper, it turns out that the Note Velocities remained the same, but the breath control is being used as the dynamics.

So what I'm thinking here is that there should be a new feature where there will be an option for us to set all the selected elements of the note velocities and set them to "automatic", so that way they can match up with the written dynamics that are being breath controlled.

### Problem to be solved

Constantly manually adjusting note velocity takes forever, so Instead of resetting the Note Velocities to default at 64 in the midi file exporting process, they should be set to automatic instead, alongside the breath controled playback of the dynamic markings.

**Comment by avvvvve** [comment]
We have this task (#19207) to make dynamics affect the velocity of notes, so will close this as a duplicate.
