### ISSUE TITLE
Incorrect alignment of the ends of the tuplets brackets

### ISSUE THREAD

**Issue by Dima12357** [musescore/MuseScore#21711]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

In one bar between the staves, the ends of the tuplet brackets are not aligned according to the last duration in a metrically separate group. 
![Снимок экрана (142)](https://github.com/musescore/MuseScore/assets/134041121/a60ee20b-2929-45f8-81b9-fd538a14f8c9)
Although the bracket (as traditionally) can only extend to the last duration, but the end of the bracket must align with the end of the last duration on the adjacent staff.

This traditional type of notation makes rhythm unnecessarily difficult to read. It is now usual to extend the bracket to the position of the hypothetical final division of the tuplet, so that the numeral occurs at the rhythmic centre of the group. This makes complex rhythms quicker to read: 
![Снимок экрана (143)](https://github.com/musescore/MuseScore/assets/134041121/8c19234e-fea1-4dc3-9267-cef2bcb8f4cc)
![Снимок экрана (144)](https://github.com/musescore/MuseScore/assets/134041121/bb7d1ea7-a393-41d9-bdb2-d10c15314992)

### Steps to reproduce

-

### MuseScore Version

OS: Windows 10 Version 2009 orMuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

**Comment by oktophonie** [comment]
Yet another duplicate. Stop it.
https://github.com/musescore/MuseScore/issues/19851
