### ISSUE TITLE
Umlauts missing in several menus/dialog, instead only the " is shown

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#21721]
### Issue type

UI bug (incorrect info or interface appearance)

### Steps to reproduce

1. Set MuseScore to German
2. Restart
3. Test the dialogs and menus, see below

### Screenshots/Screen recordings

The Instruments tab:
![image](https://github.com/musescore/MuseScore/assets/1786669/cfb9750f-2b57-4636-b94d-682291edd414)
the ü is missing 3 times
In the properties too, here an ä is missing, also in the toolbar tooltips:
![image](https://github.com/musescore/MuseScore/assets/1786669/2b4ee1c9-58cf-4117-8412-78a94ce1ea51)
Similar in the selection filter 
Not in the Palettes though 
Except for Add Palette...
![image](https://github.com/musescore/MuseScore/assets/1786669/a23c9227-dc8a-41c2-bde5-6c0febc2a84e)
Also in Edit > Preferences > Common:
![image](https://github.com/musescore/MuseScore/assets/1786669/238aebda-fdb4-4792-9b0f-06d357f3df86)
and others

### MuseScore Version

4.4/master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

Selfbuild, using Qt6

**Comment by Jojo-Schmitz** [comment]
Seems the nightly builds are not affected?!?

**Comment by bkunda** [comment]
@DmitryArefiev pls check in 4.3. Thanks!

**Comment by DmitryArefiev** [comment]
Confirm it doesn't happen in 4.3, 4.4 (master) on Win10

@Jojo-Schmitz I also can't reproduce on PR artifact (e.g. https://github.com/musescore/MuseScore/actions/runs/8112995932 )

![Capture3](https://github.com/musescore/MuseScore/assets/90187801/84147243-48d1-4291-b09e-752e442527bb)

**Comment by Jojo-Schmitz** [comment]
Try updating translation and rester, then try again?

**Comment by DmitryArefiev** [comment]
Tried that.. Still no success

But I see you a have a different font. What font are a have in Preferences?

**Comment by Jojo-Schmitz** [comment]
Very good question!
![image](https://github.com/musescore/MuseScore/assets/1786669/0d638555-11a4-4aaf-a889-c76194ef6180)
None!
Let me revert to factory settings...

**Comment by Jojo-Schmitz** [comment]
And voilá problem solved

**Comment by DmitryArefiev** [comment]
Cool!  Good the problem is solved. If we find the steps then we reopen the ticket

**Comment by Jojo-Schmitz** [comment]
Might be related to my switch from building with Qt5.15 to 6.2

**Comment by DmitryArefiev** [comment]
Good point! I'll check that area when start 4.4 testing more deeply
