### ISSUE TITLE
Appended text frame disappears with Navigator open

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#21720]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

If the Navigator is open while appending a text frame, the frame disappears, either immediately or upon adding text.

### Steps to reproduce

1. New score, Treble Clef template, all defaults
2. Enable View / Navigator
3. Add / Frames / Append text frame

Result: score scrolls to bottom of page but no text frame is visible.  Or, if the frame *does* display - which it might in continuous vertical view - try double-clicking it and typing some text.  The frame will disappear at that point.

In at least some cases, depending on whether the Navigator was open and closed previously, one might not always see this, so if you have trouble reproducing, close MuseScore completely and repeat the above steps before doing anything else.  At first it seemed the issue was confined to cases where the Navigator is set to open by default (because it was open when MuseScore was last closed), but I think that was a red herring.  I can reproduce this 100% of the time if I start MuseScore without the Navigator as per the steps above.

Note the frame *is* added, and it may reappear if you then trigger a relayout via an edit.

This seems possibly related to https://github.com/musescore/MuseScore/issues/14970, and who knows, maybe even to https://github.com/musescore/MuseScore/issues/15591

### Screenshots/Screen recordings

[Screen recording 2024-02-27 7.53.41 AM.webm](https://github.com/musescore/MuseScore/assets/1799936/29bd6f3f-24b1-4f0c-b78b-e011989643b0)

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230938, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Debian 11

**Comment by zacjansheski** [comment]
Looks to me like a regression that occured between 4.1.1 and 4.2


https://github.com/musescore/MuseScore/assets/69917893/baf9a5c4-2935-4d17-8392-19f5003bb398
