### ISSUE TITLE
Update in-app name references to use "MuseScore Studio"

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#21722]
In keeping with the recent product rebrand, there are a few main tasks we'll need to prepare ahead of the 4.3 release: 

- [x] Update app loading/splash screen with new design (supplied by @Tantacrul).
- [x] Update app name wherever it appears in a menu item

There may be others that I haven't thought of (I'll defer to the likes of @cbjeukendrup @RomanPudashkin @igorkorsukov @Eism to advise here).

**Comment by Jojo-Schmitz** [comment]
> In keeping with the recent product rebrand, there are a few main tasks we'll need to prepare ahead of the 3.6 release:


??? 3.6 release?

**Comment by cbjeukendrup** [comment]
- [ ] macOS installer:
    - [ ] Update the filename of the .dmg installer
    - [ ] Update the background image of the .dmg installer
    - [ ] Update the filename of the .app itself
    - [ ] Update Info.plist if necessary, and entitlements file perhaps
- [ ] Windows installer: 
    - [ ] Update the filename of the .msi installer
    - [ ] Update texts in the installer
    - [ ] Update left banner on first page of installer
    - [ ] Update top banner on second pages of installer
    - [ ] Update the name of the app as registered with the OS (oh no...)
    - [ ] ???
- [ ] Linux installer:
    - [ ] Update the filename of the AppImage
    - [ ] Update .desktop file
    - [ ] ??????

**Comment by shoogle** [comment]
Common practice is to avoid spaces in filenames, so we'll need a decision on whether to use:

- `MuseScoreStudio` (nothing)
- `MuseScore-Studio` (hyphen)
- `MuseScore_Studio` (underscore)

Or take the risk with spaces  (e.g.  `MuseScore Studio.exe`).

**Comment by Jojo-Schmitz** [comment]
To be save for Mu5, better add a 4 to the executable name (on Windows, at least) too

**Comment by jessjwilliamson** [comment]
Another to add to list as mentioned by comms team are youtube thumbnails - musescore in minutes videos contain 'Musescore 4' which appears in the Learn tab. 
With artwork for the installers I can update those :)
