### ISSUE TITLE
Implement 'music symbol scale' for segnos and coda markers

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#21757]
Coda/segno markers (as often appear in 'Repeat text left'-style text), as dynamics and tuplets and ottavas do as of https://github.com/musescore/MuseScore/pull/20934, should:
- be taken from the Musical _symbols_ font
- have a ''Musical symbols scale" setting (defaulting to 100%)

The new default size for 'Repeat text left' can than be 11pt (to match 'Repeat text right').

**Comment by XiaoMigros** [comment]
I'd like to try this :)
