### ISSUE TITLE
Crash when setting a beamed note to stemless

### ISSUE THREAD

**Issue by mike-spa** [musescore/MuseScore#21753]
### Issue type

Crash or freeze

### Steps to reproduce

1. Enter something with a beam
2. Select a beamed note and set it to stemless

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/93707756/69c22c52-5548-4ded-a6f2-ea06712b4168

### MuseScore Version

Current master

### Regression

I don't know

### Operating system

Any

**Comment by zacjansheski** [comment]
Thankfully this crash does not occur in 4.3
Only in 4.4
