### ISSUE TITLE
Crash loading this score

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#21783]
### Issue type

Crash or freeze

### Bug description

Open This File Ms4.4.0 crash in Version (64-bit): 4.4.0-240620304, revision: github-musescore-musescore-c80ad76

### Steps to reproduce

Open This File Ms4.4.0 crash

### MuseScore Version

MuseScore version (64-bit): 4.4.0-240620304, revision: github-musescore-musescore-c80ad76

### Regression

Yes, this used to work in a previous version of MuseScore 4.x
Work in version (64-bit): 4.4.0-240580304, revision: github-musescore-musescore-5a682ba

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

### Additional context

[Crassh4.zip](https://github.com/musescore/MuseScore/files/14470259/Crassh4.zip)

**Comment by DmitryArefiev** [comment]
Occurs only in **4.4 master** (doesn't occur in 4.2.1 and 4.3 nightly builds). Could be related to Qt6 migration

**Comment by igorkorsukov** [comment]
I check, not related with Qt6 (crash on Qt5 too). Related with Engraving module.

**Comment by DmitryArefiev** [comment]
For **4.3** (not for 4.4) was fixed in #21902
