### ISSUE TITLE
All my notes are red

### ISSUE THREAD

**Issue by davsun55** [musescore/MuseScore#21814]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

All my note bodies are red and I can't see how to change them. A google search indicates that they may be 'out of the voice range', but they aren't - at least that I can see. See attached. 
I have tried exporting to XML and reimporting but that doesn't fix it.
[C102-The old, old story.zip](https://github.com/musescore/MuseScore/files/14486879/C102-The.old.old.story.zip)

### Steps to reproduce

I've no idea how this happened. I did import this score from a previous format (MusicTime I think).

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/51256983/c3dddbd5-f249-4185-afb9-e63430342796)

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Windows 11 latest version

**Comment by Jojo-Schmitz** [comment]
Please use the support forum opn musescore.org for things like this: it isn't a bug, just wrong usage.

The instrument hied in that scire is Crotales!?!? And that has a range of C6 to C8, so all your notes are too low, hence MuseScore colors them red for you.
This is by design.

**Comment by davsun55** [comment]
Too hard to resolve the source, but fixed by firstly changing the staff range to C0-C9. But I think I could also have resolved by replacing the instrument. Thanks for the hint above. :)
