### ISSUE TITLE
After deleting sound flag, cannot add one again to the same text object

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#21816]
Currently, we have this behavior for deleting a sound flag:
0. (If sound flags are hidden on the score) click some staff text with an edited sound flag
1. Click the sound flag button
2. Press delete
3. The sound flag is deleted
4. Click text
5. No sound flag button shows up (it should, in its pre-edited state)

The interaction should be:
1. Delete sound flag, text gets deselected
2. Click text again
3. Sound flag button shows up

**Comment by Eism** [comment]
If user selected sound presets/techniques(we updated text according selection) and after that user deleted sound flag, should we reset text to default (Staff text)? What if user added custom text, should we still reset to default?
