### ISSUE TITLE
Musescore Will Not Open Any Scores

### ISSUE THREAD

**Issue by joecorporon** [musescore/MuseScore#21822]
### Issue type

Crash or freeze

### Bug description

Musescore will not open any scores.

### Steps to reproduce

1. Open Musescore.
2. Open a score.
3. Musescore crashes.

### MuseScore Version

4.2.1-1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Endeavour OS (similar to Arch Linux)

### Additional context

This is a development as of this morning. Yesterday everything was working fine.

System Info:
Operating System: EndeavourOS 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.6.20-1-lts (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6500T CPU @ 2.50GHz
Memory: 15.0 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530
Manufacturer: HP
Product Name: HP Elite Slice

[MuseScore_240305_081545.log](https://github.com/musescore/MuseScore/files/14495807/MuseScore_240305_081545.log)

**Comment by joecorporon** [comment]
For some reason the AppImage version works but the installed version doesn't.

**Comment by Jojo-Schmitz** [comment]
The 'inslatted' version is not supported here, only the AppImage is
