### ISSUE TITLE
Kushview Element playback inaccurate

### ISSUE THREAD

**Issue by Code-Viper828** [musescore/MuseScore#21832]
### Issue type

VST bug

### Bug description

When KV_Element is used as the audio for an instrument, it does not playback the correct notes

### Steps to reproduce

1. Add KV_Element VST as instrument
2. Play score
3. Pause and restart

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10

**Comment by zDEFz** [comment]
> ### Issue type
> 
> VST bug
> ### Bug description
> 
> When KV_Element is used as the audio for an instrument, it does not playback the correct notes
> ### Steps to reproduce
> 
>     1. Add KV_Element VST as instrument
> 
>     2. Play score
> 
>     3. Pause and restart
> 
> 
> ### Screenshots/Screen recordings
> 
> _No response_
> ### MuseScore Version
> 
> OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433
> ### Regression
> 
> I don't know
> ### Operating system
> 
> Windows 10
> ### Additional context
> 
> _No response_

I use the same VST as workaround for faulty MIDI #21795
(Most) notes seem correct at first glance (PianoTeq) but what is not OK is that the first notes seem to be skipped

What is your exact issue? Please provide a comparison

**Comment by Code-Viper828** [comment]
During playback via KV Element, one tone will play the entire time, frequently creating dissonance, and filling rests

**Comment by zDEFz** [comment]
> During playback via KV Element, one tone will play the entire time, frequently creating dissonance, and filling rests

Wait I don't understand/

Is MuseScore playing the tone back?
Is KV Element pushing out something "wrong" ?

You should be more clear about what is the source of this issue

**Comment by Code-Viper828** [comment]
I do not know what the source of the issue is. All I know is that playback when using KV Element is not what I wrote in the score (I went to the Discord for the issue first and I was told to report the issue here until I figured out which end the issue was on, since loading KV Element in a different DAW did not have this issue)

**Comment by bkunda** [comment]
@Code-Viper828 yesterday we merged a fix that _might_ fix this issue, but will need your help to see if it worked. 
Could you please re-test using the latest nightly? Many thanks!

**Comment by Code-Viper828** [comment]
Where do I get the latest build?

**Comment by RomanPudashkin** [comment]
@Code-Viper828 you need the latest nightly: [MuseScoreNightly-latest-master-x86_64.7z](https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/MuseScoreNightly-latest-master-x86_64.7z)

**Comment by zacjansheski** [comment]
Closing as stale
