### ISSUE TITLE
MuseScore4.2.1 musicXML Import ignores ('editorial') <accidental> attribute 'parentheses'

### ISSUE THREAD

**Issue by OhNotAgainSam** [musescore/MuseScore#21847]
### Issue type

Import/export issue

### Steps to reproduce

1. create a musicXML file for a short monophonic score in cMaj (eg. 3 Measures). The score should include some "sharp" notes. This can be done by exporting an appropriate sample score in musicXML from a music notation App (eg. MuseScore)
2. using a text editor on the exported musicXML file, find all occurrences of <accidental>sharp... and edit these to become: &lt;accidental editorial="yes" parentheses="no"&gt;sharp&lt;/accidental&gt;
3. save the edited musicXML file, and then import it to MuseScore4. Verify that MuseScore4 shows all sharps WITH parentheses (#). 
While typing this hash-in-parentheses on this report, the following popped up: 
(#21835 Don't bracket accidentals if the XML says not to). 
It seems this bug may already have been reported, but I don't know how to use the pop-up here. #

### Screenshots/Screen recordings

![grafik](https://github.com/musescore/MuseScore/assets/162360740/e953f253-52ab-4c10-bb8e-1a191ae653e0)

### MuseScore Version

MuseScore4.2.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 Pro ver. 22H2 OS Build 19045.4046

### Additional context
Benefit of a fix:  I can offer only my own use-case:  
I have a musicXML score from a "custom application" which I want Musescore to render correctly. My score is not intended to be Common Western Music Notation. It will be an approximation to "Griffschrift" for interpretation by a musician playing a "diatonic Accordion". In principle Musescore provides a convenient mechanism to get my (musicXML) score rendered and exported to PDF. 
I chose "editorial" rather than "cautionary" for the accidentals on the premise that a human editor can in principle write whatever they want on the score. The combination editorial/parentheses appears to be valid:  https://w3c.github.io/musicxml/musicxml-reference/elements/accidental/

**Comment by Jojo-Schmitz** [comment]
Sample XML file (taken from https://musescore.org/en/node/361415):
[musicXML.Test3_.ed_.musicxml.zip](https://github.com/musescore/MuseScore/files/14516246/musicXML.Test3_.ed_.musicxml.zip)
