### ISSUE TITLE
master branch cannot be built for iOS

### ISSUE THREAD

**Issue by litong01** [musescore/MuseScore#21879]
### Issue type

Other type of issue

### Bug description

Use Qt Creator with Qt 6.2.4 cannot build musescore for iOS. When try to build, Qt Creator will show the following errors.

```
project has asked CMake to find a package configuration file provided by
Qt6LinguistTools, but CMake did not find one.

Could not find a package configuration file provided by Qt6LinguistTools
with any of the following names:

  Qt6LinguistToolsConfig.cmake
  qt6linguisttools-config.cmake

Add the installation prefix of &quot;Qt6LinguistTools&quot; to CMAKE_PREFIX_PATH or
set &quot;Qt6LinguistTools_DIR&quot; to a directory containing one of the above
files.  If &quot;Qt6LinguistTools&quot; provides a separate development package or
SDK, be sure it has been installed.

Call stack:
  <a href="olpfile:///Users/tli/hl/src/github.com/MuseScore/CMakeLists.txt::185::-1">/Users/tli/hl/src/github.com/MuseScore/CMakeLists.txt:185</a> (include)
  <a href="olpfile:///Users/tli/hl/src/github.com/MuseScore/build/cmake/FindQt6.cmake::50::-1">/Users/tli/hl/src/github.com/MuseScore/build/cmake/FindQt6.cmake:50</a> (find_package)</code>
```

### Steps to reproduce

1. Clone the github project
2. Open the project using Qt Creator
3. Try to build musescore for iOS, then the errors will display.

### MuseScore Version

github master branch

### Regression

I don't know

### Operating system

Mac OS X

### Additional context

This is not crash, it is just that Qt Creator cannot build musescore for iOS target. It build mac version ok.

**Comment by litong01** [comment]
it will be super nice to have instructions on how to build muse score for iOS devices.

**Comment by jeetee** [comment]
Building for iOS is not currently supported.

**Comment by cbjeukendrup** [comment]
Incidentally, I recently experimented a bit with compiling for iOS. The first step is to fix some OS detection stuff in CMake. I got this part done, and could make a Pull Request, although that would make much sense since there are no short-term plans to create iOS builds. 

The next step is to get an iOS version of libsndfile. 
Then, the audio and midi drivers will need to be rewritten for iOS. 
What needs to happen after that is still unknown.

**Comment by Jojo-Schmitz** [comment]
I guess every step towards supporting iOS helps? Even if the futur direction and timing is still unclear

**Comment by litong01** [comment]
@Jojo-Schmitz @cbjeukendrup that is great. thanks for commenting on this issue. @cbjeukendrup Can you share the PR which fixed CMake? apple store has the version of musescore with subscription, I am always confused by that app and this repo, what is the relationship between the muse score on app store and this repo?

**Comment by Jojo-Schmitz** [comment]
The mobile app is not open source. It is basically a viewer only.

**Comment by MarcSabatella** [comment]
@litong01 I fear you may have some unreasonable expectations here.  MuseScore - the actual music notation program which is in the process of being renamed to MuseScore Studio to reduce confusion - does not work on iOS, period.  It's not just a matter of fixing a cmake file.  It was simply never designed to work on that platform and the code to support it does not exist.

That's not to say MuseScore Studio couldn't someday be ported to IOS someday, but there would be *much* more to it than just tweaking some configuration files.  As mentioned, new audio code would need to be created; also the UI would also have to be redesigned in a pretty major way to work on smaller screens and be touch-friendly and not require use of a keyboard.  And probably a whole bunch of other OS-specific things that would need to be added to the existing code, just as there are currently a whole bunch of OS-specific things for Windows, macOS, and Linux.  If it were simple it would have happened already many years ago.
