### ISSUE TITLE
Crash when deleting a single note with lyric continuation

### ISSUE THREAD

**Issue by marczellm** [musescore/MuseScore#21872]
### Issue type

Crash or freeze

### Bug description

MuseScore crashes when deleting a single note in the attached file.

[bugrepro.zip](https://github.com/musescore/MuseScore/files/14549904/bugrepro.zip)

### Steps to reproduce

1. Open the attached score
2. Click on the last note
3. Press Delete
4. MuseScore crashes

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Windows 10

**Comment by cbjeukendrup** [comment]
Incidentally, this seems a 4.1.1 -> 4.2.0 regression.
