### ISSUE TITLE
Score has become corrupted message if clearing measure with trill and parts

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#21889]
### Issue type

Opening/saving issue

### Bug description

I get this message when trying to save score with parts and cleared measure after saving trills
![image](https://github.com/musescore/MuseScore/assets/919446/4c6555fe-c178-4c55-aceb-ac9ee3b1c463)

### Steps to reproduce

1. Create score from treble template
2. Enter quarter note
3. Open piano part, then close piano part
4. Add trill line for note
5. Save and close score
6. Reopen score
7. Clear measure and try to save score

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/aefc5be2-4dca-4549-bec2-7b500c9db9b2

### MuseScore Version

4.2.1, 4.4.0 master

### Regression

I don't know

### Operating system

windows 10

**Comment by zacjansheski** [comment]
Regression occured between 4.0.2 and 4.1.0

**Comment by mercuree** [comment]
Can't reproduce anymore since 4.4.0 release. Probably fixed
