### ISSUE TITLE
Musescore Edit drumset change of notehead not working

### ISSUE THREAD

**Issue by acmhome** [musescore/MuseScore#21887]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Changing the notehead for Crash cymbal using Edit Drumset - Edit Noteheads to Void Notehead with X on A line is not working for crotchets/quarter notes. This is now the standard notation, at least in UK.

### Steps to reproduce

I have created a large booklet for drumset.  

Default Crash cymbal is non-standard (at least for UK) notation. Need to change to hollow (void) notehead with cross.
![image](https://github.com/musescore/MuseScore/assets/163006795/959fb38f-45e4-4825-9f52-c0d451423ef5)

(number 5 in picture shows default).

On this staff (Key to notation bar) , Rt Click - Edit drumset.
Select 49 Crash Cymbal 1 - edit noteheads
Crotchet (quarter note) change to "void notehead with X"
Minim (half note) change to "half notehead with X"
OK
![image](https://github.com/musescore/MuseScore/assets/163006795/b8c91f24-82be-430e-9fcf-f97275ad8d00)

Result (number 5 in picture) is normal notehead
![image](https://github.com/musescore/MuseScore/assets/163006795/b215a4dd-b05f-4092-8fb6-9bc179e2979a)

Starting afresh is not an option as this is a large piece of work!

Thanks very much

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

**Comment by rgreen5** [comment]
Looks similar to  #12872?

**Comment by zacjansheski** [comment]
I can't reproduce this issue from scratch, is there anything else about your score that might be causing it not to change?

https://github.com/musescore/MuseScore/assets/69917893/6de763ae-4d6a-4d1c-bd83-042ec123d701

**Comment by zacjansheski** [comment]
Closing as stale
