### ISSUE TITLE
Reverse flat accidental overlaps with other accidentals

### ISSUE THREAD

**Issue by looptailG** [musescore/MuseScore#21895]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

The reverse flat accidental can overlap with other accidentals applied to neighbouring notes.

[Musescore file containing a couple of examples.](https://github.com/musescore/MuseScore/files/14564149/AccidentalsOverlap.zip)

### Steps to reproduce

1. Add a note to the score, and apply the reverse flat accidental to it.
2. Add another note to the chord, above the previous note, close enough for the accidentals to potentially overlap (for example a 6th above).
3. Add an accidental to this new note.  Some accidentals, like the sharp, will overlap with the reverse flat applied to the first note.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/99362337/04ac4083-cbcf-49bd-8dc5-aeac1b7761da)

### MuseScore Version

4.2.1-240230937

### Regression

I don't know

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
So might need to get reported against https://github.com/MuseScoreFonts/Leland

**Comment by oktophonie** [comment]
Just so, I did the cutouts wrong. Raised [here](https://github.com/MuseScoreFonts/Leland/issues/37)
