### ISSUE TITLE
Dynamics overriding snare drum accents

### ISSUE THREAD

**Issue by 5GuysBurgersAndBillNyes** [musescore/MuseScore#21893]
### Issue type

Muse Sounds bug

### Bug description

Putting dynamics on the snare drum part of a score while utilizing the muse sounds snare drum prevents the playback of accents. If you don't put a dynamic marking, accents will play, but as soon as there is a dynamic marking, accents will no longer play.

### Steps to reproduce

1. Create a new score with a snare drum part
2. Add some notes, some with accents, some without
3. Add a dynamic marking and playback
4. Remove the dynamic marking and playback again

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

**Comment by 5GuysBurgersAndBillNyes** [comment]
Didn't know there was another one, my b. So it will just get worked on through that issue?

**Comment by DaddyLudwig** [comment]
Yes
