### ISSUE TITLE
Crash after deleting all measures and Undo (one score with opened parts)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#21890]
### Issue type

Crash or freeze

### Steps to reproduce

1. Open [Smoke Test 29.zip](https://github.com/musescore/MuseScore/files/14562678/Smoke.Test.29.zip)
2. Delete all measures
3. Undo

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/1a66c89e-f219-430a-b9cf-7f3701eccc15

### MuseScore Version

4.3

### Regression

Yes, this used to work in **MuseScore 4.2.1**

### Operating system

Windows 10

**Comment by mathesoncalum** [comment]
Same root cause as #21783

**Comment by DmitryArefiev** [comment]
For **4.3** (not for 4.4) was fixed in #21902
