### ISSUE TITLE
Pedal marking and bend support is arbitrary

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#21899]
### Issue type

General playback bug

### Bug description

Pedal markings only play back on specific instruments. Note that this is based on the *instrument* type, not the soundfont. This means that, for example, a guitar instrument, *regardless of what sound it's set to in the mixer* does not support pedal markings. But a piano instrument *with the same exact sound* will work.

Also, only guitar-like instruments support bends, which is annoying because any time you want to use synths with pitch bend, you have to use a guitar instrument.

This seems to apply to soundfonts, Muse Sounds, and VSTs.

This could be related to #21066.

### Steps to reproduce

1. Create a score with a guitar instrument (guitar isn't the only instrument that has this problem, but I'm not going to test all of them to make a list).
2. Add some notes, using a pedal marking.
3. Test it and note that the pedal marking has no effect.
4. Using Staff Properties, change the instrument type to piano (various other instruments also work, but again, I'm not going to test all of them).
5. Note that the pedal marking now works.
6. Change the sound in the mixer back to whatever the guitar was set to.
7. The pedal still works.

Also you could do the opposite with bends (they only work on guitar-like instruments)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/87204246/df138de5-926e-4e94-8d6a-9a0d10154c3a

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

OS: Windows 10 Version 2009, Arch.: x86_64

**Comment by bkunda** [comment]
Can you please provide an example where it might be useful to apply a pedal marking, but where the correct playback currently isn't triggered? 

(As far as I'm aware, there is some intentionality to the current behaviour, being that it doesn't really make sense to put a piano pedal mark on a guitar, however if there are some use cases for which this kind of behaviour is required, we can certainly try to address it).

**Comment by ThePython10110** [comment]
In some cases, short notes can get cut off before they realistically should. Normally I'd make the pedal marking invisible (since it's just for playback).

https://github.com/musescore/MuseScore/assets/87204246/081cdbbc-2781-4dbc-a9f6-40c8210deb59

**Comment by ThePython10110** [comment]
Bends are likewise limited to guitar-like instruments.

**Comment by lgvr123** [comment]
@ThePython10110  Using a piano pedal on a guitar is a bit odd. You can use the "Let Ring" who's working (I guess) like you intent it to work.

For the Bends, indeed. It seems limited to string instruments, while other instruments permit blends. A.o. many reeds and woodwinds.

**Comment by ThePython10110** [comment]
I didn't know about "Let Ring." Did it exist in MS3?

**Comment by lgvr123** [comment]
Yes. This is the default notation for guitar, bass, etc...

**Comment by erinic04** [comment]
The let ring marking doesn't work how you might expect it to. From my limited testing trying it on my harp part, it doesn't seem to let it ring for long (exactly twice the written duration, no more no less), and it also makes the part louder, which I don't want.
Just twice the note length doesn't really make any sense, as for eighth notes and such it only rings out for a quarter note total, which is much less than you would expect. enabling the pedal markings on other instrument types gives more options to the user, which is always good (maybe you can have an option to enable the playback on other instruments for pedal and bends so people who don't know what they're doing don't make bad notation)

**Comment by zacjansheski** [comment]
I am closing this, the over-arching report is by-design and we won't take focused action based on this.

Feel free to open a feature request for unsupported, practical functionality.  Thank you!
