### ISSUE TITLE
musicxml: hidden notehead is not imported correctly

### ISSUE THREAD

**Issue by gesellkammer** [musescore/MuseScore#21939]
### Issue type

Import/export issue

### Bug description

When importing a musicxml file, "<notehead>none</notehead>" within a note element is not imported correctly

### Steps to reproduce

1. Make a score in musescore
2. hide a notehead
3. save as musicxml
4. import the musicxml file in musescore
5. the notehead is not hidden anymore

The same musicxml file is imported correctly in other software

### MuseScore Version

4.2.1

### Regression

Choose option...

### Operating system

macos, linux

**Comment by Jojo-Schmitz** [comment]
IIRC that had been fixed recently, have you tried a recent nightly build?

**Comment by Jojo-Schmitz** [comment]
I don't find it, so well possible that I remembered incorrectly, sorry

**Comment by gesellkammer** [comment]
I tried it with a nightly build of 3.3.24 (MuseScoreNightly-latest-4.3.0-x86_64.AppImage) and the error is still there. Here is a musicxml file to use for testing
[hidden.zip](https://github.com/musescore/MuseScore/files/14612415/hidden.zip)

**Comment by Jojo-Schmitz** [comment]
Strange, code dealing with that is there:
```cpp
        } else if (m_e.name() == "notehead") {
            noteheadColor = Color::fromString(m_e.asciiAttribute("color").ascii());
            noteheadParentheses = m_e.asciiAttribute("parentheses") == "yes";
            noteheadFilled = m_e.attribute("filled");
            auto noteheadValue = m_e.readText();
            if (noteheadValue == "none") {
                hasHead = false;
            } else {
                headGroup = convertNotehead(noteheadValue);
            }
        } else if (m_e.name() == "rest") {
```

**Comment by Jojo-Schmitz** [comment]
And the latest builds do import it as invisible, 4.4 as well as 3.7

**Comment by gesellkammer** [comment]
That's great! The nightly builds are somewhat behind, I guess. The stems should be left visible since the musicxml directive is only for the notehead.

**Comment by Jojo-Schmitz** [comment]
No, nightly builds are at most 24h behind.
But there are 2 types, 4.3.0 and master/4.4.0
