### ISSUE TITLE
Soprano Saxophone staccato F#5 squeaks above mp

### ISSUE THREAD

**Issue by EvansSC1** [musescore/MuseScore#21945]
### Issue type

Muse Sounds

### Bug description

The Soprano Saxophone staccato F#5 (transposed) note squeaks at any dynamic above mp (most prevalent at default dynamic and mf)

### Steps to reproduce

1. Create new score
2. Add soprano saxophone
3. Add F#5 with staccato
4. Observe squeak

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10

**Comment by bkunda** [comment]
I'm not exactly hearing a squeak. @EvansSC1 does this correspond with what you heard? 

https://github.com/musescore/MuseScore/assets/86290556/bc615fed-8230-4afa-80a5-622036b0e499

Ultimately it's much more helpful for us if you can please post a screen recording (with audio) so we can quickly understand the problem.

**Comment by zacjansheski** [comment]
Closing, no response
