### ISSUE TITLE
Snare Drum does not respect accents when given a dynamic

### ISSUE THREAD

**Issue by EvansSC1** [musescore/MuseScore#21944]
### Issue type

Muse Sounds bug

### Bug description

The snare drum instrument only respects accents when it does not have any sort of dynamic. 

Interestingly I can kind of hear an attempt at accents at forte, but the w

### Steps to reproduce

1. Create Score
2. Add Snare Drum Instrument
3. Write some notes
4. Apply a dynamic
5. Notice that the accents are ignored

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10

**Comment by DaddyLudwig** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/21243

**Comment by EvansSC1** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/21243

**Comment by EvansSC1** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/21243
