### ISSUE TITLE
MuseScore crash after apply "Regroup Rythms" (one score)

### ISSUE THREAD

**Issue by huilianpatrikseidel** [musescore/MuseScore#21953]
### Issue type

Crash or freeze

### Bug description

In large scores, when select a measure on an staff with two or more voices, and apply "Regroup rythm", the MuseScore crash.

### Steps to reproduce

1. Open the score attached on this bug reporter
2. Select a measure with two voices (e.g. **Flutes 1&2, 2nd measure**)
3. Go to "Tools" menu and apply "Regroup Rythms"
4. Musescore crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/65817799/4fc98769-37b7-4994-8766-a6dc2d824a5a

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10, Arch.: x86_64,

### Additional context

[score.zip](https://github.com/musescore/MuseScore/files/14617419/score.zip)
[Funiculi, Funicula_short.zip](https://github.com/musescore/MuseScore/files/14834340/Funiculi.Funicula_short.zip) - small version of initial score

**Comment by DmitryArefiev** [comment]
**Can reproduce** the crash in 4.3 and 4.4 (Windows and Mac) with the attached score only. Bur can't recreate it from a scratch

**Comment by DmitryArefiev** [comment]
@huilianpatrikseidel Do you have another scores where the similar crash occurs?
