### ISSUE TITLE
Musescore is unable to play sounds in soundfonts whose preset number is greater than 127

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#21965]
### Issue type

General playback bug

### Bug description

I have a soundfont that I am using in Musescore where the preset numbers from any given bank have the possibility to go above 127. 
![image](https://github.com/musescore/MuseScore/assets/21023353/b2dca48d-0d35-42e5-81fa-b0a583bd2435)
Using the image as an example, Musescore plays back everything up to and including the "Goron Mines Wind," but does not produce any audio when using any of the presets after it in the same bank. These sounds all work for playback within Polyphone, they just don't work at all in Musescore. This eliminates the possibiliy to use almost half of this bank of sounds, as the preset numbers go all the way up to 239.

### Steps to reproduce

1. Have a preset in a soundfont whose bank number is greater than 127 (doesn't require all previous numbers to be filled)
2. Select the preset for a staff in the mixer
3. Attempt to play anything on that staff

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/21023353/92777584-09d6-4007-b32d-9005e3a4062a

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Reported on Windows 11

**Comment by C7667DPR** [comment]
I don't believe this is an issue with MuseScore itself, rather the limitations of MIDI and SoundFont. Per the SoundFont technical specifications, a bank is defined as the following: "MIDI bank - A group of up to 128 presets selected by a MIDI “change bank” command." I think the only solution for this is to divide the bank into several banks with this 128 preset limit, or use a different file format than SoundFont. I'll link the specifications to look at here: http://www.synthfont.com/sfspec24.pdf

**Comment by C7667DPR** [comment]
Ok great, I don't see another way of fixing this as of yet, so do you want to mark this issue as resolved and leave it as reference?

**Comment by erinic04** [comment]
Yeah that sounds reasonable
