### ISSUE TITLE
Many percussion instruments do not respect accents

### ISSUE THREAD

**Issue by EvansSC1** [musescore/MuseScore#21960]
### Issue type

Muse Sounds bug

### Bug description

Many percussion instruments do not play accents any louder than unaccented notes:
- Marimba
- Xylophone
- Vibraphone
- Glockenspiel
- Crotales
- Chimes
- Bongos
- Triangle

### Steps to reproduce

1. Create new score
2. Add any of the instruments above
3. Add notes
4. Add accents
5. Observe that the accents are ignored

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10

**Comment by oktophonie** [comment]
It is unhelpful to have the same issue six times over where the only difference is the name of the instrument. I have combined the others into this one and closed them. If you find the same issue affecting other instruments, you can edit the description here to extend the list.

**Comment by Dima12357** [comment]
@EvansSC1, as far as I understand, accents are not heard on almost all instruments in Muse Sounds, if _mf_ and quieter are indicated. Therefore, I propose to combine the issue, designating not only percussion but everything in general (taking into account the fact that the dynamic designation from _mf_ and quieter is indicated).

**Comment by DaddyLudwig** [comment]
> @EvansSC1, as far as I understand, accents are not heard on almost all instruments in Muse Sounds, if _mf_ and quieter are indicated. Therefore, I propose to combine the issue, designating not only percussion but everything in general (taking into account the fact that the dynamic designation from _mf_ and quieter is indicated).

Indeed, I've noticed that too. Piano seems to be one of the few instruments that do sound different with the accent mark vs without the accent mark at mf or lower, though it's a lot more subtle than at f and at ff, the accents become virtually non-existent in playback for all instruments in my experience. Indeed sf in an ff passage actually decreases the volume a bit for the note marked sf, a sort of reverse accent.

**Comment by zacjansheski** [comment]
Fixed in Muse Sounds
