### ISSUE TITLE
Impossible to mute a channel (e.g. chord symbols) in score, but unmute in a part

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#21964]
### Issue type

General playback bug

### Steps to reproduce

1. Take In the Closes Score SATB + Piano score with chord symbols at the top (Women) staff
2. Create a part "Choir" that includes Women and Men
3. In the main score open the mixer and mute the chord symbols channel (for them not to conflict with the piano staff on playback)
4. Check in the Choir part: chore symbols are muted, unmute (as an aid for rehearsal)
5. Check in main score: they are enabled there again

In Mu3 it was possible to mute/solo, unmute/unsolo them idependantly in main score and parts, not any more in Mu4, as this is recorded in the one and only audiosettings.json

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

Problem also shows when importing a score with such settings from Mu3, the mute setting just gets ignored.

Possible solution: have an audiosettings.json per excerpt, just like they have their own style file and viewsettings.json.

**Comment by cbjeukendrup** [comment]
Does this differ from #20564, fixed by #20758?

**Comment by Jojo-Schmitz** [comment]
Darn, I did serach for ussies with "mute" in title
