### ISSUE TITLE
Crash when dragging note 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#21999]
### Issue type

Crash or freeze

### Bug description

This crash was found by @RomanPudashkin (in Debug mode). Was introduced in #21350

It's very hard to reproduce in a normal mode, but possible in a big score when dragging note quickly

### Steps to reproduce

1. Drag note very quickly to Palettes side

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/af6452a9-ee3f-46ef-ae49-5bf485673b12

### MuseScore Version

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac13.6

### Additional context
[crash.zip](https://github.com/musescore/MuseScore/files/14669055/crash.zip)

**Comment by cbjeukendrup** [comment]
To reproduce in debug builds, all you need to do is simply drag the note to a very high or low pitch.
