### ISSUE TITLE
Select All + Break Inner Beams produces odd results

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#21991]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Select All + Break Inner Beams produces odd results

### Steps to reproduce

1. Make a score and add some 8th notes
2. Select all
3. Using the properties panel, break inner beams

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/4307f6c1-dcad-45ec-9e4a-7e5407f39f3e

### MuseScore Version

4.3

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 14

### Additional context

Works in 4.1.1 broken in 4.2.0

**Comment by zacjansheski** [comment]
https://github.com/musescore/MuseScore/issues/21809

Likely a result of this behavior

**Comment by DmitryArefiev** [comment]
The same with Join beams
