### ISSUE TITLE
"Add Tempo marking" menu item does not update playback

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#21994]
### Issue type

General playback bug

### Bug description

Playback tempo is not updated when you add a tempo marking via the menu item.

### Steps to reproduce

1. Create a new score and add some notes to the first two or three measures.
2. Select the first note and go to Add > Text > Tempo marking, or use the keyboard shortcut Option Shift T.
3. Leave the default "quarter = 80" as it is.
4. Click away from the Tempo marking to confirm it, and hit play.
5. Hear error: Notes still play at default 120 bpm, even though the playhead moves correctly at 80 bpm.

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 12.7.2

### Additional context

If, while creating the tempo marking, you change the tempo from 80 to something else (like 81), it has no issue, only if you leave it at the default.
It also has no issue if you change the tempo *after* the tempo marking creation.
And finally, this issue is not present when adding a tempo marking from the palettes—only from the menu, as far as I can tell.

**Comment by SteveBlower** [comment]
Confirmed following the steps above.  

But it seems to be a temporary problem only.  If I open a part and then go back to the main score, or if I save and reload, the playback is correct at 80 BPM.

**Comment by MarcSabatella** [comment]
This is already reported in https://github.com/musescore/MuseScore/issues/13662
