### ISSUE TITLE
Length change of voice 2 note/rest adds unnecessary rest to following measure

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#21992]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Increasing the length of a voice 2 (or 3 or 4) note/rest while not in Note Input Mode adds an unnecessary same-voice rest to the following measure, which has to then be manually deleted.

### Steps to reproduce

1. Create a new score.
2. Enter Note Input Mode and set voice to 2, 3, or 4.
3. Add a quarter note or quarter rest to the first beat of the first measure.
4. Exit Note Input Mode.
5. Select the quarter note/rest and change its duration to half (for example by pressing "6" on your computer keyboard).
6. See error: A same-voice rest is added to the following measure.

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

macOS 12.7.2

### Additional context

Same issue happens when you change it from a half to a whole, or from a 16th to an 8th—just *any* increase in length of the note or rest.
This behavior began in version 2.0.

**Comment by Jojo-Schmitz** [comment]
Please double check whether a nightly build still has that issue, ISTR having seen a fix related to this recently

**Comment by cbjeukendrup** [comment]
#21056 is the one we're looking for. That's indeed closed, so please check the nightly builds from https://musescore.org/en/nightly-builds.

**Comment by Riley-Sullivan** [comment]
Confirmed. The latest 4.3 nightly still has the issue.

**Comment by oktophonie** [comment]
Yes. The fix will be in 4.4.

**Comment by Jojo-Schmitz** [comment]
Som tra a nightly build from master
