### ISSUE TITLE
Strings through MuseSounds not playing the proper tremolo notation

### ISSUE THREAD

**Issue by TRF29568** [musescore/MuseScore#22012]
### Issue type

General playback bug

### Bug description

The string section on MuseSounds is not playing the correct notation for the 32nd between notes tremolo.

### Steps to reproduce

1. Insert a cello, violin, viola or contrabass into the score.
2. Insert a 3nd between notes tremolo in between two notes.
3. Playback and the issue should come up.

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.1.2

### Additional context

OS: macOS 14.2, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

I am using MuseSounds for playback.

Here's the link to the file: https://drive.google.com/file/d/1lOiqreUpRBjXFRfGwMj4gZKQhPz942gD/view?usp=sharing

**Comment by zacjansheski** [comment]
The .wav you shared is empty

<img width="1183" alt="Screenshot 2024-03-22 at 1 57 19 PM" src="https://github.com/musescore/MuseScore/assets/69917893/978afc80-081b-46f6-9ccd-f30a130c5b32">

**Comment by zacjansheski** [comment]
There is a typo in the reproduction steps it isn't clear what you are saying here:

"Insert a 3nd between notes tremolo in between two notes."

**Comment by TRF29568** [comment]
Weird. I’ll try again when I get home from work tonight.On Mar 22, 2024, at 1:58 PM, Zac Jansheski ***@***.***> wrote:﻿
The .wav you shared is empty
Screenshot.2024-03-22.at.1.57.19.PM.png (view on web)

**Comment by TRF29568** [comment]
I meant to put 32nd between notes tremolo. My fault.

**Comment by zacjansheski** [comment]
I am closing this report,  we need details like screen shares, scores, and expected behavior to do anything actionable.

https://github.com/musescore/MuseScore/assets/69917893/fae62d24-6e6a-4295-89b8-ddd401333e4e
