### ISSUE TITLE
Trill playback way too fast at some tempos

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#22026]
### Issue type

General playback bug

### Bug description

Trill playback using MS Basic (and VSTs) is almost comically fast at some tempos.

### Steps to reproduce

1. Make a new score and make sure it is using MS Basic (not Muse Sounds).
2. Set the tempo to Quarter = 107.
3. Add a whole note and attach a trill to it.
4. Play it back and hear error: trill playback is too fast

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 12.7.2

### Additional context

It seems that trills get progressively faster from 5 bpm to 107 bpm, and then it starts slower again from 108 bpm to 199 bpm.
I think mostly Muse Sounds instruments are fine because they mostly use pre-recorded trills.

**Comment by bkunda** [comment]
Closing because it seems to duplicate https://github.com/musescore/MuseScore/issues/19694.
