### ISSUE TITLE
Period in new score Title truncates default file name in save dialog

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#22027]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

The suggested file name in the save to disk dialog is shortened to the character before a period.

### Steps to reproduce

1. Open the New Score Wizard.
2. Choose a template or add instruments and click Next.
3. Set title to "Piano Sonata No. 21 in B-flat major"
4. Save project to disk.
5. See error: The default title is "Piano Sonata No"

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

macOS 12.7.2

### Additional context

One possible solution is to delete the period, so that the Save dialog would show "Piano Sonata No 21 in B-flat major".
Note that in 4.0.2, the window title (on Mac at least) was also "Piano Sonata No" even before the project was saved. This was fixed in 4.1.

**Comment by Jojo-Schmitz** [comment]
It is (at least) a Mu3 regression

**Comment by DaddyLudwig** [comment]
I’ve noticed this in MS3 and MS4. It’s kind of annoying for me to put in say "Symphony no. 3 in Eb" for title and Eroica for subtitle and Op. 55 in the Lyricist portion of the score setup only to get by default "Symphony no" and having to extend it manually to "Symphony no. 3 in Eb Op. 55 (Eroica)" I’m glad that MS4 saves umlauts as such for like lieder and other pieces with German titles, but the truncation at the period is kind of annoying.

**Comment by Jojo-Schmitz** [comment]
Oh, then I take back my claim that it is a Mu3 regression

**Comment by Jojo-Schmitz** [comment]
No, Mu3 does it right. It (and 1.3 and 3.6.2) do trucate the name shown in the tab (Mu4 does not), but not the filename on saving.
So it is a Mu3 regression

**Comment by re1san** [comment]
Hey, I would like to work on this issue.

**Comment by daijingz** [comment]
@re1san Do you need any assistance? I want to do some steps for this issue, which will be helpful for your next step's contributions on this issue (just some investigations into the relevant codes, all this information will be posted on this issue page).
Is this acceptable for you?

**Comment by re1san** [comment]
Sure @daijingz, it will be helpful 🙂

**Comment by daijingz** [comment]
@re1san Oh I see you have some updates. Feels already done.
