### ISSUE TITLE
Disable sound flag context menu actions where appropriate

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#22030]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

**Part 1**
'Reset to default sound' should be disabled when:

- Instantiating a sound flag (done)
- After the sound flag has just been reset (done)
- The 'Modify sound' and 'Extended techniques' selections are already set to the default (done)

https://github.com/musescore/MuseScore/assets/20806406/f93d5ba9-f537-48be-ac0b-589545b3cbb5

**Part 2**
When 'Sound flag options are not available for this sound', neither option in the context menu should be available, so we should simply disable the '...' button for this state.

<img width="334" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/2a19ac2a-02cb-407b-ac49-63206d742040">

### MuseScore Version

PR: #21989

**Comment by Eism** [comment]
@avvvvve 
This is probably old data saved in the sound flag from previous builds.
Please try to reproduce the bug on a new score and provide all the steps.

**Comment by avvvvve** [comment]
@Eism Tested in 4.3. 'Part 1' looks complete but see 'Part 2' (it's under the big video so it might have been looked over):

> When 'Sound flag options are not available for this sound', neither option in the context menu should be available, so we should simply disable the '...' button for this state.

**Comment by DmitryArefiev** [comment]
Part 2 fixed in #22306
