### ISSUE TITLE
Incomplete duration of the trill when applied to tied notes

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#22031]
### Issue type

General playback bug

### Bug description

The trill only works on the first note (out of several) in the event that the glissando line does not reach the last tied note. The remaining tied notes stop playing.

https://github.com/musescore/MuseScore/assets/134041121/e3217347-306c-4c36-9964-b1e2f97ca98e

### Steps to reproduce

1. Add some tied notes.
2. Add a glissando line to these tied notes, but do not stretch the line to the last tied note inclusive.
3. Click "Play".

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

### Additional context

In addition, the trill also does not sound if it is added to the second tied note. 

https://github.com/musescore/MuseScore/assets/134041121/555fc81c-1535-4019-b800-5971da726bdc

It happens that the trill does not need to be played until the very end, which is why it is doubly important to specify the exact place of the end of the sound, as I described in issue #21764

**Comment by bkunda** [comment]
Closing as these cases are covered in #18676
