### ISSUE TITLE
Linked staves do not maintain staff type when enabling "Small staff"

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#22045]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

A linked staff cannot be changed to small and maintain its type; it reverts to its previous type first. By "type" I mean, for example, Standard, Tab 6-str, Tab ukulele, etc.

### Steps to reproduce

1. Make a new score using the "Guitar + Tablature" template.
2. Go to the Instruments panel and click the drop down widget beside "Guitar".
3. Click the gear button beside "[LINK] Tablature" and change the staff type (to "Standard" for example).
4. Enable the "Small staff" checkbox.
5. See error: Staff type reverts to what it was before.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/163907533/d5646a57-ecb8-4c0b-a738-2a7800a5d927

### MuseScore Version

4.2.1 (and all 4.x)

### Regression

No

### Operating system

macOS 12.7.2

### Additional context

The issue is not specific to the "Guitar + Tablature" template, it was only chosen for convenience; you can recreate this issue with any guitar staff and adding a linked staff to it.

Important: closing the pop-up after changing the staff type seems to "confirm" the selection, so if you then reopen it (with the gear icon), you can successfully change the size to small.

**Comment by mathesoncalum** [comment]
Same happens with the cutaway option. Looking into it.

**Comment by Jojo-Schmitz** [comment]
Apparently a Mu3 regression
