### ISSUE TITLE
Exported WAV on Linux full of stutter

### ISSUE THREAD

**Issue by Crono23** [musescore/MuseScore#22049]
### Issue type

Import/export issue

### Bug description

Exported WAV files are full of stutter every second. Doesn't matter if I use MS Basic or Muse Sounds, how long or short the piece, how many the instruments, the results are still the same.

### Steps to reproduce

1. Make a new score and choose the instrument
2. Write music
3. Export
4. Take a listen to the audio

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Fedora 39

**Comment by Crono23** [comment]
So I tried uploading a test score to dropbox as proof, but the audio file magically fixed itself. The stutter is gone and the duration gets cut in half (from the lack of stutter). Anyone got an idea on what's happening?

![Screenshot from 2024-03-24 23-26-00](https://github.com/musescore/MuseScore/assets/88884864/d3e3271a-f7ee-43b4-a6cd-1dc6085c66a3)

![Screenshot from 2024-03-24 23-26-38](https://github.com/musescore/MuseScore/assets/88884864/b6dc4492-a6cb-4858-b9ad-0c958ccd43f8)

**Comment by Crono23** [comment]
Tried downloading the audio file to see if Dropbox changed it, and the stutter came back when played locally. Here's the [audio file](https://www.dropbox.com/scl/fi/1spwthpue8uhrg0avlabt/C-scale-test.wav?rlkey=dzs5pwwepp4zp7ci6znd5qhym&dl=0) if you want to check.

**Comment by Crono23** [comment]
Exported mp3 files are fine. Tried with both short and a long piece. I don't have this problem in non-PipeWire distro such as Linux Mint or Elementary OS.

My conclusion, it seems like MuseScore on Linux with PipeWire produces problematic WAV files which introduces stutter every second and doubles the duration. The WAV acts normal when it's uploaded and played through a web player like in Dropbox. WAV from DAW like Reaper plays just fine, so it's not a codec/media player issue on my system.

Any help would be appreciated!

**Comment by dcorson-ticino-com** [comment]
Could it be that your Pipewire is not running at the same frequency as Musescore?
If I understand correctly MS runs at 44100Hz.  Is your Pipewire running at 48000 or 96K?

**Comment by Crono23** [comment]
> MS runs at 44100Hz

Good to know. I'll try matching PipeWire with it.
> Is your Pipewire running at 48000 or 96K?

I will check next time.

I'm currently in ElementaryOS finishing my project and I have bad news. I got the same stutter even though the distro uses Pulseaudio. I think I misremembered because I used to immediately master the audio in Reaper, in which it became normal. Currently using this workaround as well.

**Comment by Fristover** [comment]
Maybe it's because I'm on Windows, but I downloaded your file and everything is just fine... I'll try on Linux later and update this comment.

**Comment by bluebear94** [comment]
I get the stutter on my Linux system, even when PipeWire is running at 44.1 kHz.

**Comment by DmitryArefiev** [comment]
This is the same as #23606
