### ISSUE TITLE
Angled pedal brackets don't work in MuseScore 4

### ISSUE THREAD

**Issue by RustyBust** [musescore/MuseScore#22051]
### Issue type

General playback bug

### Bug description

These bugs are happening with the Angle-bracket pedals which can be found in the "Keyboard" or "Lines" palettes. See below for details
I've tested this with both MS Basic and Muse Sounds. The bug occurred on both.

### Steps to reproduce

**Overlapping pedal lines (00:02)**
1. Add a pedal with angle brackets on a measure preceding an empty (centered whole rest) bar, ending on the empty bar. 
2. Add a pedal with angle brackets onto the empty bar. 
3. Place notes onto the empty measure.

(Playback example for both is at (00:21))

**Sustain pedal releasing late (00:36)**
In the playback at 00:21, the second bar did not have sustain pedal playback. This may be (just a guess) due to the pedal marking from the previous measure releasing after the pedal from the current measure starts. 
Additionally, at 01:18, we can see that when the pedal ends before the start of the next note, the sustain pedal playback works. 
To reproduce:
1. Add a pedal from one measure, with an angle bracket ending on the next.
2. Add a pedal with double angle brackets on that measure.

From [the MuseScore 4 Handbook](https://musescore.org/en/handbook/4/pedal): 
> Functionally, if that note is attached to another marking's start anchor, the following marking will automatically connect and make a shape resembling "-^-", which is indicative of the piano technique "pedal released and pressed again without releasing this note". 

Please note that the example at 00:37 is generally preferred over the example at 01:18 for notation/engraving.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/126639439/1be416dc-9c5d-45a9-938d-25f7381791cf

### MuseScore Version

OS: macOS 14.2, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Probably OS-independent

### Additional context

The file in the recording was created immediately prior to the recording.

**Comment by mike-spa** [comment]
As far as I can tell, this issue is already fixed in the current master (it's reported from version 4.2.1, and it probably got fixed as a result of the anchors PR). I've tried a few combinations, and as far as I can tell the sustain always starts/stops where it should, and also that engraving issue when entering note in the empty bar with a pedal already applied is gone.

https://github.com/musescore/MuseScore/assets/93707756/f7e19628-2134-477d-a1a0-3f04a710d53c
