### ISSUE TITLE
Add preferences for missing engraving UI colors

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#22062]
### Task description
Currently in Preferences > Advanced, users can set the colors that appear for voices 1-4 when selected in the score. Other UI colors that appear while engraving should also be included here as additional rows so users can control the appearance of MuseScore to their liking.

This includes:

- All voices
     - Upcoming feature
     - This will be added in #19137
- Anchor color
     - The color of the line the is drawn from an element anchored to a beat position
          <img width="136" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/fee96d69-4b04-459c-811a-a37492135453">
     - Currently, this is just controlled by the Voice 4 color, but we could break this out into its own category.
- Desynchronized color
     - The color an element turns when it's desynchronized in a part.
     - Currently hard-coded as #FF9300
          <img width="151" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/11b8a593-b311-489d-a3a9-9a7179ff579f">

### Proposed design
![image](https://github.com/musescore/MuseScore/assets/20806406/e8df42da-a3bc-409a-aa79-38a6c12c2ebe)

**Comment by SteveBlower** [comment]
Perhaps this issue https://github.com/musescore/MuseScore/issues/13678 could also be considered

**Comment by avvvvve** [comment]
@SteveBlower Good catch - I think we can include a "Formatting color" option to cover that case!

![image](https://github.com/musescore/MuseScore/assets/20806406/0fc38a95-3b04-4006-9bbf-29e355623a78)

**Comment by iwoithe** [comment]
Seeing no one has taken this issue, I'm happy to work on it :slightly_smiling_face:

**Comment by iwoithe** [comment]
@avvvvve What is the colour for `All voices color`?
