### ISSUE TITLE
[Muse Hub Issue] "The muse background service is not running"

### ISSUE THREAD

**Issue by entschri** [musescore/MuseScore#22072]
### Issue type

Other type of issue

### Bug description

This issue started after my E: drive (which is the drive I use to store muse sounds) broke. I then tried to change the installation location, and it gave me this message.
![image_2024-03-26_203837464](https://github.com/musescore/MuseScore/assets/77518045/9d0e08a3-dcb2-4b02-90ab-71747dabb4e0)
I've reinstalled Muse Hub and I've tried manually starting the helper, but whenever I do, it instantly turns off.
It will also show this on the bottom at all times.
![image_2024-03-26_204027902](https://github.com/musescore/MuseScore/assets/77518045/98f58af3-2a02-4114-8e30-5f500b092ae3)

### Steps to reproduce

1. Go to settings
2. Try to change Install Location from Custom to Default
3. Message above will be shown.

### MuseScore Version

Muse Hub Version 1.0.2.800 (x64)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by zacjansheski** [comment]
Did you log this on the Muse Hub page? (zendesk)

**Comment by entschri** [comment]
Yeah, I just did.

**Comment by DominicMaas** [comment]
Can you try the latest version of Muse Hub and see if that fixes anything (you might need to migrate on startup, but it's handled automatically).

**Comment by zacjansheski** [comment]
Closing as fixed in V2
