### ISSUE TITLE
Sound flag buttons should not appear when published to musescore.com

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#22073]
### Description
Sound flags buttons (i.e. the circle with the speaker icon) should not be rendered at all in scores published to musescore.com.
![image](https://github.com/musescore/MuseScore/assets/20806406/1b64b738-d7c4-4411-a628-8eed9d55022e)

### Steps to reproduce
1. Create a score with sound flags
2. File > Publish to musescore.com
3. After publishing and processing, see that the circle and missing icon are displayed. Neither should appear.

**Comment by avvvvve** [comment]
@zacjansheski Feel free to add any other context I may have missed! I tried publishing but my score has been processing for a long time, so I haven't reproduced it yet.

**Comment by Eism** [comment]
@avvvvve @zacjansheski 
Should be fixed, please recheck

**Comment by DmitryArefiev** [comment]
Checked on latest 4.3 builds (Win/Mac). **All good** on my side
