### ISSUE TITLE
Non-modal plug-in “window” without Qtquick.dialogs

### ISSUE THREAD

**Issue by TeeDeeY** [musescore/MuseScore#22084]
When using qt6.2.4, plugins supposedly can’t use qtquick.dialogs any more.

My prior plug-in dialog was not modal (it was floating) and allowed switching back and forth between the score and the dialog box. 

When I made a revised plug-in (edit: MuseScore 4.4 Master using Qt 6.2.4) without using “.dialogs”, the new window would not give up control.

How do I made a plug-in window that is not modal (I want a floating window )?

Thanks

**Comment by TeeDeeY** [comment]
Using Window { }, I can have a nonmodal window but I have to explore how to make it work in Qt5 and Qt6.

**Comment by TeeDeeY** [comment]
“Dialog” type not required to have a non-modal window in Qt5.  The default seems to be non-modal.  

A build of the master directory for v4.4 gives the modal behavior.

**Comment by TeeDeeY** [comment]
I tried the default lily pond lyrics plug-in.  The modal mode blocked seeing the score being changed.  My plug-in isn’t the only one affected.

**Comment by igorkorsukov** [comment]
@TeeDeeY Thank you for bringing this to our attention. Next week I will try to make it possible to configure the dialog so that it is not modal.

**Comment by igorkorsukov** [comment]
@TeeDeeY Now all dialogs with plugins are not modal by default.
For extensions of the new format, we can specify a modality (also not modal by default).
(documentation about extensions of the new format will come later)

**Comment by TeeDeeY** [comment]
I hope the updated plug-in/extension system allows working across multiple instances of the program and access to the full (all items, nothing removed) copy/paste buffer.  :-)
