### ISSUE TITLE
Crash after pasting a specific selection

### ISSUE THREAD

**Issue by sclsj** [musescore/MuseScore#22097]
### Issue type

Crash or freeze

### Bug description

Copy pasted a certain selection - program crashed

### Steps to reproduce

1. Store this data in your clipboard (viewed using clipboard viewer)
[com.trolltech.anymime.application--musescore--stafflist.txt](https://github.com/musescore/MuseScore/files/14798323/com.trolltech.anymime.application--musescore--stafflist.txt)
2. Paste this in a score
3. MuseScore 4 should crash (reproduced using both my own native compiled version and official release)

### Screenshots/Screen recordings

[mscore crashes.zip](https://github.com/musescore/MuseScore/files/14798330/mscore.crashes.zip)

### MuseScore Version

4.2.1 (lastest)

### Regression

I don't know

### Operating system

macOS 12

### Additional context

I copied from a selection in a project I was working on. Let me know if you want the project. Unfortunately I don't have that project saved when musescore crashes so I'm not sure if it still contained content that can trigger this bug.

**Comment by DmitryArefiev** [comment]
@sclsj Please add more details to repro steps. What should be copied/pasted from this long txt file?


https://github.com/musescore/MuseScore/assets/90187801/b6bec2e5-af1a-4ef5-b1fd-cdc96517ee2c

**Comment by sclsj** [comment]
This should be written to the clipboard (pasteboard) under the key `com.trolltech.anymime.application--musescore--stafflist`.

**Comment by sclsj** [comment]
This is essentially what gets written to the pasteboard when a section of music is copied in MuseScore. Unfortunately I don't program in macOS so I don't know how you would write this exported file into the pasteboard. I just searched online how I can export pasteboard that is custom application data and found this sample XCode project provided by Apple that can do this.

**Comment by sclsj** [comment]
So, to answer your question: I don't know how. Since MuseScore writes this to the pasteboard in the first place, I'm sure someone knows how.

**Comment by sclsj** [comment]
<img width="1052" alt="截屏2024-03-29 下午4 17 31" src="https://github.com/musescore/MuseScore/assets/38654636/ad983a22-c34f-461b-9e0e-55239474473f">
Ignore the two entries below containing "paste". These are from Paste, a clipboard history manager which records my clipboard history, which comes in handy in these cases.

**Comment by sclsj** [comment]
Update: try this solution by GPT-4. It works on my machine.
https://chat.openai.com/share/af60cb29-1d38-4feb-a95d-23af5fa12809

**Comment by zacjansheski** [comment]
Closing as stale
