### ISSUE TITLE
Random chance of crash on startup

### ISSUE THREAD

**Issue by RannyBergamotte** [musescore/MuseScore#22107]
### Issue type

Crash or freeze

### Bug description

Opening musescore has only like a 1/10 chance of success. Usually it crashes on startup. How far it gets into is also random, sometimes the startup splash shows, sometimes the startup splash window shows up empty, sometimes it just says "loading mscore".  I then have to spam open.

### Steps to reproduce

Attempt to open Musescore

### MuseScore Version

4.2

### Regression

Been always broken since musescore 4 released. Musescore 3 works fine.

### Operating system

Arch Linux (wayland and xwayland, pipewire)

### Additional context

```sh
> mscore

(process:111607): Gtk-WARNING **: 12:52:38.350: Locale not supported by C library.
Using the fallback 'C' locale.
12:52:38.472 | INFO  | main_thread     | GlobalModule::onPreInit | log path: /home/mab/.local/share/MuseScore/MuseScore4/logs/MuseScore_240329_125238.log
12:52:38.472 | INFO  | main_thread     | GlobalModule::onPreInit | === Started MuseScore 4.2.1, build number  ===
12:52:38.475 | WARN  | main_thread     | IpcSocket::connect | failed connect to server
12:52:38.475 | WARN  | main_thread     | IpcSocket::connect | failed connect to server
12:52:38.475 | INFO  | main_thread     | IpcSocket::connect | success connected to ipc server
12:52:38.476 | INFO  | 135115063690944 | IpcServer::listen | id: "b97bcd7e7238426aaf64bedb3809ea9e"
12:52:39.237 | WARN  | main_thread     | DiagnosticsModule::onInit | crash handling disabled
12:52:39.441 | WARN  | main_thread     | AbstractCloudService::readTokens | Could not find the tokens file: /home/mab/.local/share/MuseScore/MuseScore4/musescorecom_cred.dat
12:52:39.441 | WARN  | main_thread     | AbstractCloudService::readTokens | Could not find the tokens file: /home/mab/.local/share/MuseScore/MuseScore4/audiocom_cred.dat
/usr/include/c++/13.2.1/array:211: constexpr const std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) const [with _Tp = mu::engraving::PropertyValue; long unsigned int _Nm = 1433; const_reference = const mu::engraving::PropertyValue&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
fish: Job 1, 'mscore' terminated by signal SIGABRT (Abort)
```

**Comment by RannyBergamotte** [comment]
I put the playback creates crash on a seperate issue: #22108
The logs for when musescore does succesfully open in that about 1in10 chance is there

**Comment by MarcSabatella** [comment]
Are you using the supported AppImage, or a third party build?  "mscore" is not the usual installed name for the AppImage.  Be sure to remove any unsupported third-party builds if you experience problems with them, and try again using the official build.  The crash looks like a known one that occurs with certain third-party builds - see https://github.com/musescore/MuseScore/issues/20878

**Comment by RannyBergamotte** [comment]
Using App image, it does work now, thanks! I did see there was a discussion to use flatpaks instead, I would love to see a flatpak instead in the future for the many advantages it provides. I'm still experiencing playback stuttering for the #22108 , I'll do some more tests tomorrow and a screen record.
