### ISSUE TITLE
window is maximized and can't move it (Linux with tiling window manager)

### ISSUE THREAD

**Issue by lyrra** [musescore/MuseScore#22116]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

Window manager is in tiling-mode but floating, which means windows can be resizable and moved around.
But musescore forces maximized mode, and window cant be moved around.

### Steps to reproduce

...

### MuseScore Version

master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

linux 

### Additional context

using a tiling window manager like awesome-wm, and set it into float mode

**Comment by DmitryArefiev** [comment]
@lyrra Please add more details to steps to reproduce (how to trigger awesome-wm, with what settings). 
Or you can add a video capture with the whole process.

It's regression in 4.4 master comparing with 4.3 builds?

**Comment by lyrra** [comment]
This got resolved by installed qml6-module-qt-labs-platform/stable
