### ISSUE TITLE
Volta positioned too high above key signatures

### ISSUE THREAD

**Issue by SnyBr** [musescore/MuseScore#22115]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

If a volta is placed on a measure containing a key signature, the volta is positioned unreasonably high in some cases.

Current volta placement:
![Screenshot from 2024-03-30 12-47-52](https://github.com/musescore/MuseScore/assets/105515763/744f5206-861e-4b8b-9ea8-037f64e71fee)

Expected volta placement:
![Screenshot from 2024-03-30 12-49-32](https://github.com/musescore/MuseScore/assets/105515763/e35a3736-71c9-4597-acd5-28741a113567)

### Steps to reproduce

Add a volta to a measure containing a key-signature.

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230938, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Ubuntu 22.04.4 LTS

### Additional context

@Jojo-Schmitz confirmed that the volta is avoiding the key-signature skyline with the following screensnips:

![image](https://github.com/musescore/MuseScore/assets/105515763/ec92064b-716f-4d05-8daa-d30bffab8918)

![image](https://github.com/musescore/MuseScore/assets/105515763/bc30cc37-1bd7-4314-a453-87c8a9da396b)

![image](https://github.com/musescore/MuseScore/assets/105515763/bf5def65-3153-45bd-a5c1-e82d92b7a756)

**Comment by Jojo-Schmitz** [comment]
That image seems a bad example, as the last (2) accidental doesn't 'stick out'  of the staff...

Anyeay, I've just tested and the issue is not resolved, please reopen

**Comment by mike-spa** [comment]
What do you mean "attaching the volta to the measure"?

**Comment by Jojo-Schmitz** [comment]
selecting the measure, clicking the volta

**Comment by mike-spa** [comment]
![image](https://github.com/musescore/MuseScore/assets/93707756/d3c3f166-615b-4da2-b537-87a186f10df6)

This is what I get. Can you please double check which branch you're building from?

**Comment by Jojo-Schmitz** [comment]
Master, latest version

**Comment by mike-spa** [comment]
Sorry, neither I nor @oktophonie can reproduce the issue with the current master, so either you gives us clearer reproduction steps or I don't think we can do much about it

**Comment by Jojo-Schmitz** [comment]
Ops, sorry, apparaently I rebased from origin (my fork) rather than upstream...
Lemmi retest
