### ISSUE TITLE
Continuous view measure selection glitch

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#22113]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

There is a strange glitch in continuous view when you select measures. I have created a small score that recreates the issue, but it is something that I see other times, usually in larger, more complicated scores, with lots of articulations, etc., always in horizontal continuous view.

### Steps to reproduce

1. Open the provided score, and make sure it is set to horizontal continuous view.
2. Add a tempo marking to the first measure.
3. Experiment selecting different measures, and ranges of measures, as illustrated in my provided screen recording.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/163907533/0d115c78-29c6-4414-8963-77c44efe9436

### MuseScore Version

4.2.1

### Regression

Choose option...

### Operating system

macOS 12.7.2, but also Windows 10

### Additional context

[Continuous View Selection Bugs.mscz.zip](https://github.com/musescore/MuseScore/files/14809222/Continuous.View.Selection.Bugs.mscz.zip)

**Comment by Riley-Sullivan** [comment]
I should have added that this is a MS3 regression; that is, it began in MS4.

**Comment by zacjansheski** [comment]
Regression occurred between 4.1 and 4.2

**Comment by mike-spa** [comment]
@zacjansheski @oktophonie I have always found selection boxes to be a complete mess in Musescore, so I'd like to take the opportunity to fix this once and for all. Besides the new glitch reported in the issue, here's just a couple more obvious problems I know of:

a) The selection includes the height of those notes, but in the wrong bar.
![image](https://github.com/musescore/MuseScore/assets/93707756/ded82515-0a16-4eea-a6de-25eaa7e9d1d2)
![image](https://github.com/musescore/MuseScore/assets/93707756/feb8dd81-fb99-4e11-96fe-d25daf899455)


b) When a measure is selected, the left-edge of the selection box sometimes starts at the barline, sometimes at the first chord
![image](https://github.com/musescore/MuseScore/assets/93707756/0113680c-7d85-4380-b1bb-78e1f78b372b)
![image](https://github.com/musescore/MuseScore/assets/93707756/5d8716d7-3849-4cd8-926d-cc2ffc206428)

You've probably encountered more stuff like this, in which case to let me know.

**Comment by zacjansheski** [comment]
@mike-spa here is a small collection selection box issues.  If you are keen to fix any of them feel free to change assignment!

https://github.com/musescore/MuseScore/issues/21261
https://github.com/musescore/MuseScore/issues/11054
https://github.com/musescore/MuseScore/issues/19097
https://github.com/musescore/MuseScore/issues/15483
https://github.com/musescore/MuseScore/issues/10342
