### ISSUE TITLE
Linux: Same instrument can't play the same note twice

### ISSUE THREAD

**Issue by Lunaaacy** [musescore/MuseScore#22134]
### Issue type

General playback bug

### Bug description

Given in the video

### Steps to reproduce

given in the video

### Screenshots/Screen recordings

https://files.catbox.moe/ctci8g.mp4

### MuseScore Version

Version 4.2.1 (appimage)

### Regression

Choose option...

### Operating system

Elementary OS 7.1 Horus

**Comment by MarcSabatella** [comment]
This was a known issue, already fixed for the next update - see https://github.com/musescore/MuseScore/issues/15306

**Comment by cbjeukendrup** [comment]
Closing as per the comment above
