### ISSUE TITLE
no-webview option in manpage

### ISSUE THREAD

**Issue by Vivien-G** [musescore/MuseScore#22138]
### Issue type

Other type of issue

### Bug description

The manpage for MuseScore4 advertises a `-w | --no-webview` option, that mscore doesn't know about.

### Steps to reproduce

$ man mscore

> -w | --no-webview
> Disable the web view component in the Start Centre

$ mscore -w

> MuseScore4: Unknown option 'w'.

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Gentoo Linux

### Additional context

It looks like this option was relevant up to MuseScore3 but is not any more: [latest PR](https://github.com/musescore/MuseScore/pulls?pulls?q=is%3Apr+webview) containing *webview* is over 3 years old.

I've grep'd the full 4.2.1 tree for things like *web*, *webview* and *QtWeb*. The only places that seemed of any relevance are in file `build/Linux+BSD/mscore.1.in`, lines 44 and 232-233. Branches 4.3.0 and master have the same version of that file.

It seems like MuseScore4 has never had a use for this option, from [4.0 rc](https://github.com/musescore/MuseScore/blob/4.0_rc/src/appshell/commandlinecontroller.cpp) to [master](https://github.com/musescore/MuseScore/blob/master/src/app/commandlineparser.cpp), whereas it was present in [3.6.1](https://github.com/musescore/MuseScore/blob/3.6.1/mscore/musescore.cpp) (lines 7753, 7717).

**Comment by cbjeukendrup** [comment]
Indeed, MuseScore 4 doesn't use QtWebEngine anymore, so this option is obsolete and should be removed from the manual.
