### ISSUE TITLE
piano note doesnt sound after new score or bringing the score back

### ISSUE THREAD

**Issue by anamikabanerjee** [musescore/MuseScore#22141]
### Issue type

Muse Sounds bug

### Bug description

when I open the  score in Muse Score I cant play the sounds on the piano keyboard or when I create a project or open another project I have to continuously  go to edit mode and doing the sound then come back to select mode pls fix this bug so I don't have to do this over and over again

### Steps to reproduce

1.press p to open the piano 
2.close and reopen it
3.you can't play the sounds of the notes on the piano unless.(step 4.)
4.you go to edit mode and click the note and delete the notes in the staff(or if you want it to be you will not delete it)
5.if you want to test the sounds you can go back by going in select mode

the problem is I don't want the piano keyboard notes sound by doing this over and over again if the complete beginner gets this problem he/she might face problem 

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/152690618/ffa271f2-e12c-4f4b-8fa4-bb7ded9e538f

### MuseScore Version

4.2

### Regression

I don't know

### Operating system

windows 11

**Comment by zacjansheski** [comment]
Closing as duplicate
