### ISSUE TITLE
When resetting a sound flag that has unique 'Extended techniques' options for different 'Modify sound' options, the extended techniques buttons do not update properly

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#22146]
https://github.com/musescore/MuseScore/assets/20806406/324aca33-2a6e-477e-8a33-0e76a209e39a

### Steps to reproduce
1. Add a 'Suspended cymbal' instrument to the score (with Muse Percussion: Sus. Cymbal selected as the sound)
2. Add staff text to it and click the sound flag button.
3. Switch between 'Large - Mallets' and 'Large - Sticks' and see that the 'Slice' extended technique is only available when 'Large - Sticks' is selected
4. Select 'Large - Sticks' so that 'Slice' is visible
5. Click '...' and 'Reset to default sound'
6. See that 'Large - Mallets' gets selected but 'Slice' is still available as an option. It should not appear.

Note that closing the popup and reopening fixes it, so the UI just needs to be refreshed upon reset.

**Comment by DmitryArefiev** [comment]
Fixed in #22306
