### ISSUE TITLE
Realize Chords does not open dialog in AppImage linux version

### ISSUE THREAD

**Issue by slosar** [musescore/MuseScore#22166]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Trying to click "realize chords" does not do anything either clicking a chord and then choosing "realize chords" from the right-clock context menu or tools->realize chord symbols.   A warning is issued on the panel
```
8:03:49.989 | WARN  | main_thread     | Qt              | QQmlComponent: Created graphical object was not placed in the graphics scene.
```

### Steps to reproduce

Use the the AppImage linux version. Click on a chord. Attempt to activate "realize chords". Exactly the same procedure opens a dialog box under Windows.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1197186/63ee07c5-906b-42d2-9eb4-53b2d439444b

### MuseScore Version

OS: Ubuntu 23.10, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230938, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Linux, Lubuntu 23.10

### Additional context

xmonad is the window manager, although I doubt that would matter.

**Comment by MarcSabatella** [comment]
This works fine for me on Linux (Debian 12).  Is it possible you previously had a second monitor attached and the dialog is trying to display there?  I see that same warning, BTW, so that's probably not relevant although you never know.
