### ISSUE TITLE
QT6 qmake usage incorrect

### ISSUE THREAD

**Issue by theofficialgman** [musescore/MuseScore#22178]
### Issue type

Other type of issue

### Bug description

there appears to be an issue in `build/cmake/GetUtilsFunctions.cmake`
it does not account for the binary name for QT6 changing to `qmake6`. there is no `qmake` for qt6 releases.

this results in the following error if `qmake` from qt5 is not installed
```
qmake: could not find a Qt installation of ''
CMake Error at build/cmake/GetUtilsFunctions.cmake:105 (message):
  

  Error running Qt with command:

    /usr/bin/qmake --version

  Console output directly above may provide more information about the error.

  Do you have the correct version of Qt installed? Is it available in your
  PATH environment variable?

  See https://musescore.org/en/handbook/developers-handbook/compilation
```

### Steps to reproduce

attempt to build with `-DMUE_COMPILE_QT5_COMPAT=OFF` and `qmake` from qt5 not present

### MuseScore Version

git master

### Regression

No.

### Operating system

Linux

**Comment by shoogle** [comment]
My Qt 6 installation has both `qmake` and `qmake6` inside Qt's `bin` folder, though they are identical.

```Bash
 $ cd /c/Qt/6.2.4/msvc2019_64/bin
 $ sha256sum qmake.exe qmake6.exe
2449f28305e9db1150c80e524f134eb3421c3e1e87227b95ed8af587e019ee6e *qmake.exe
2449f28305e9db1150c80e524f134eb3421c3e1e87227b95ed8af587e019ee6e *qmake6.exe
```


 I'm using the official Qt on Windows. Perhaps Linux distributions only ship the `qmake6` executable?

Anyway, if you want scripts to work with `qmake6` simply edit [these lines](https://github.com/search?q=repo%3Amusescore%2FMuseScore+fn__require_program%28QMAKE&type=code):

```C++
fn__require_program(QMAKE Qt --version "https://musescore.org/en/handbook/developers-handbook/compilation" qmake)
```

To look like this:

```C++
fn__require_program(QMAKE Qt --version "https://musescore.org/en/handbook/developers-handbook/compilation" qmake qmake6)
```

Adding `qmake6` on the end tells the CMake function `fn__require_program()` that `qmake6` is an [alternative name](https://github.com/musescore/MuseScore/blob/6af0ba19b93c9766d47d5c6a72a5ade4db119209/build/cmake/GetUtilsFunctions.cmake#L86) for the `qmake` command.
