### ISSUE TITLE
Time signatures aren't copied to clipboard

### ISSUE THREAD

**Issue by Tadaboody** [musescore/MuseScore#22197]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Steps to reproduce

1. Create a measure with a time signature change
2. select it with shift + arrow keys
3. copy it 
4. paste it
the time sig change are not copied and the whole phrase becomes off

### Screenshots/Screen recordings

<img width="944" alt="image" src="https://github.com/musescore/MuseScore/assets/6463334/8fe36fe0-15eb-41d3-b009-7c13f3309c73">
The first line is the original line, selected and copied.  
The second one is the pasted, note the missing change to 5/8 in measure 2 and the chaos afterwards

### MuseScore Version

OS: macOS 12.7, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

macOs

**Comment by oktophonie** [comment]
Duplicatee of https://github.com/musescore/MuseScore/issues/15590
