### ISSUE TITLE
MuseScore crashes when changing theme

### ISSUE THREAD

**Issue by KelvinNovais** [musescore/MuseScore#22206]
### Issue type

Crash or freeze

### Bug description

The app crashes whenever the system theme is changed.

Additionally, even if you set (Edit > Preferences > Appearance > "Follow system theme") to false, Musescore crashes anyway.

### Steps to reproduce

1. Open the app (it doesn't care which page you are)
2. Change the system theme
3. Wait some time and see it crashing

### Screenshots/Screen recordings

[Screencast from 2024-04-05 00-23-26.webm](https://github.com/musescore/MuseScore/assets/83086622/a62117e6-9b9e-442e-b3dd-8b0586d81f0a)

### MuseScore Version

4.2.1 (Flatpak)

### Regression

I don't know

### Operating system

Fedora 39

### Additional context

Terminal output:

```
(...)

00:36:21.671 | WARN  | main_thread     | Qt              | Could not find color scheme  ""
00:36:21.674 | WARN  | main_thread     | Qt              | Could not find color scheme  ""
00:36:21.704 | WARN  | main_thread     | Qt              | Could not find color scheme  ""
00:36:21.706 | WARN  | main_thread     | Qt              | Could not find color scheme  ""
```

**Comment by Jojo-Schmitz** [comment]
Does the AppImage crash too? Only that is supported here...

**Comment by zacjansheski** [comment]
I haven't reproduced with appimage on Ubuntu

**Comment by KelvinNovais** [comment]
AppImage works perfectly on Fedora.

Maybe the problem is caused by KDE flatpak runtime: it may mask the theme keyword when it changes, or something else... I'm not sure...

But, if the theme wasn't found, isn't it possible to keep the current configuration? Of course this isn't the best solution, however avoids crashing the app.

**Comment by zacjansheski** [comment]
I am closing this as we are only actively working on supporting AppImage
