### ISSUE TITLE
No sound, playback on Linux (MuseScoreNightly 240960304 master)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#22214]
### Bug description

This is a recent regression in master (4.4)

**Doesn't occur** in **4.3** builds

### Steps to reproduce

1. Open MuseScoreNightly-240960304-master on Linux
2. Start playback - **playback cursor doesn't start**

### MuseScore Version

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux Ubuntu 22.04.3 LTS

**Comment by lyrra** [comment]
I belive this is related to my PR https://github.com/musescore/MuseScore/pull/21861.
I can reproduce this by killing jack, and then run Musescore with either jack or alsa device.
The error is mitigated by running jack.
I'll look into it to see if I can find any cause to why.

**Comment by lyrra** [comment]
Problem is with the PR after all:
At https://github.com/musescore/MuseScore/blob/master/src/framework/audio/audiomodule.cpp#L117

```
#if defined(JACK_AUDIO)
    m_audioDriver = std::shared_ptr<IAudioDriver>(new JackAudioDriver());
#else
    #if defined(JACK_AUDIO)
    m_audioDriver = std::shared_ptr<IAudioDriver>(new JackAudioDriver());
    #else
...
#endif // JACK_AUDIO

```

We need to disable jack-audio because we can't select between alsa or jack at runtime, it is fixed at compile-time.
