### ISSUE TITLE
Add Simile text item to the Text palette

### ISSUE THREAD

**Issue by bobniqu** [musescore/MuseScore#22210]
### Your idea

Suggest you add "Simile" to the pick list of Text options.

### Problem to be solved

Saves you from having to type it in manually all the time.

**Comment by cbjeukendrup** [comment]
Similar to #19716, except that this one just requests a text item for it, which is very reasonable in my opinion, while #19716 also requests playback support for it, which is very difficult to implement, because it's almost impossible for a machine to guess what the "Simile" marking applies to.

**Comment by bobniqu** [comment]
I understand that. I wasn’t looking for playback support, just a simple way of adding “vib.” In italics, much like you just add “tremolo,”  which is already in the Text palette, preferably in italics.

**Comment by cbjeukendrup** [comment]
@bobniqu Actually there is a way to get a "Simile" item in your palettes in the current version of MuseScore already:
1. Create the item in a score
2. With Ctrl+Shift pressed (or Cmd+Shift if you're on Mac), drag the item to the palette where you want it.

**Comment by bobniqu** [comment]
Thanks. Works.

**Comment by wizofaus** [comment]
> I understand that. I wasn’t looking for playback support, just a simple way of adding “vib.” In italics, much like you just add “tremolo,” which is already in the Text palette, preferably in italics.

But in fact "vib." and "tremolo" are performance techniques, and hence usually *not* done in italics (and usually placed above staff).

**Comment by wizofaus** [comment]
> @bobniqu Actually there is a way to get a "Simile" item in your palettes in the current version of MuseScore already:
> 
> 1. Create the item in a score
> 2. With Ctrl+Shift pressed (or Cmd+Shift if you're on Mac), drag the item to the palette where you want it.

I'd still think there might be a case for including "sim." in the factory defaults - except that I note Gould recommends against over-using it, and given how easy it is to copy & paste articulations/expressions/etc. there is an argument for not encouraging composers/score publishers from sprinkling their score with "sim." instructions.
