### ISSUE TITLE
Default position of redirection incorrect

### ISSUE THREAD

**Issue by DominAbbus** [musescore/MuseScore#22247]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

In the attached screenshot, I put the "Fine" redirection just before the time- and key sig.
I would expect the text to be right-aligned with the double barline, instead of the end of the barline.
It is simple enough to drag the text to the correct position, however, when the music is reformatted, this may still lead to awkward positioning.

### Steps to reproduce

new score / enter some bars
add a hard line break, key- and time signature somewhere at the end of the first line.
place a Fine redirection at the bar before the key- and time signature change

result:
the Fine is right aligned at the end of the (physical) space reserved for that bar

expected:
the Fine to be right aligned with the logical end of the bar, which is at the double barline. 

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

### Additional context

![image](https://github.com/musescore/MuseScore/assets/76609300/13269b0c-06a1-4a3b-adbd-a58b676f8b0a)

**Comment by XiaoMigros** [comment]
I'd like to try this!
