### ISSUE TITLE
All Instruments are missing in master (MuseScore 4.4.0.240990304 nightly master)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#22262]
### Steps to reproduce

1. Create new score

https://github.com/musescore/MuseScore/assets/90187801/433eb002-b9f8-4659-a0c5-d3f359430ad0

### MuseScore Version

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context
Recent regression

**Comment by DmitryArefiev** [comment]
Fixed in #22252

**Comment by Jojo-Schmitz** [comment]
Just got fixed, see #22252

**Comment by DmitryArefiev** [comment]
Yeah, thanks!
