### ISSUE TITLE
Improve parenthesis removal UX

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#22298]
### Your idea

It would be easier to work with parenthesis for ghost notes and courtesy accidentals if they can be toggled like elements in the top menu (such as accent/marcato etc.)

### Problem to be solved

After adding parenthesis, removing them can be a bit of a hassle.  You either need to rewrite the notes or delete the parenthesis one at a time.

https://github.com/musescore/MuseScore/assets/69917893/234fc02b-1a6d-45fd-b8fd-65bf9d23ead7

**Comment by bkunda** [comment]
What about the current toggles in Properties? Don't they achieve what you're asking for here?

**Comment by zacjansheski** [comment]
Ha, didn't think of that, thanks!
