### ISSUE TITLE
[MU4 Issue] Playback misses several notes

### ISSUE THREAD

**Issue by cfiderer** [musescore/MuseScore#22299]
When playing the attached score, several notes are missing.
Observed with 

- MuseScore 4.2.1 
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

- [MuseScoreNightly-latest-4.3.0-x86_64-portable.exe](https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/MuseScoreNightly-latest-4.3.0-x86_64-portable.exe) from 09.04.2024 
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.3.0-241000900, revision: github-musescore-musescore-0d450c6

- [MuseScoreNightly-latest-master-x86_64-portable.exe](https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/MuseScoreNightly-latest-master-x86_64-portable.exe) from 09.04.2024
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.4.0-241000304, revision: github-musescore-musescore-cd0e887

[Light the Fire Within.zip](https://github.com/musescore/MuseScore/files/14923511/Light.the.Fire.Within.zip)

**Comment by MarcSabatella** [comment]
Assuming you mean the notes like the F at the end of beat 1 in the top staff, that's because the same notes is being sustained in the bottom staff, and Muse Sounds does not currently support this (human musicians fake it by cutting the earlier note short).  This is expected to be fixed in the 4.3 but only when the next version of Muse Sampler is released.

See https://github.com/musescore/MuseScore/issues/15306 for further info.

**Comment by cfiderer** [comment]
Thank you @MarcSabatella for pointing this out. It was astonishing for me to hear these dropouts because the score was written in MuseScore 3 - and there it played completely.

**Comment by MarcSabatella** [comment]
MuseScore 3 didn’t support Muse Sounds, of course - only soundfonts.  So meanwhile that’s the workaround - switch to soundfonts when writing music that requires notes to overlap like this.

**Comment by bkunda** [comment]
@RomanPudashkin has actually fixed this issue (fairly recently) for Muse Sounds, by enabling each stave to use its own separate track. 
The fix won't be heard until the next sampler update though (which will be coming soon!).

**Comment by DmitryArefiev** [comment]
Confirm. It **sounds fine** with the musesampler **v6** in **4.3/4.4** (Win10)

https://github.com/musescore/MuseScore/issues/15306#issuecomment-1972711244

**Comment by DmitryArefiev** [comment]
> MuseScore 3 didn’t support Muse Sounds, of course - only soundfonts. So meanwhile that’s the workaround - switch to soundfonts when writing music that requires notes to overlap like this.

@cfiderer You can also try VSTi (it should be VST3). It works fine on my side with Kontakt and musesampler v5
