### ISSUE TITLE
Can't open Musescore (or Muse Hub) at all after fresh installation.

### ISSUE THREAD

**Issue by thomasnoakes04** [musescore/MuseScore#22316]
### Issue type

Crash or freeze

### Bug description

After encountering a problem with Muse Sounds not showing up, I fiddled with both (Musescore and Muse Hub) programs for a while before uninstalling and reinstalling. Now after a fresh install, neither of the programs will open at all. Musescore will display a splash as expected, which will quickly close and the program will not open. Muse Hub doesn't do anything, not even minimises to the system tray.

I appreciate that Muse Hub has its own issue tracking site, but I figured there may be a common problem so I'd try here for both programs.

### Steps to reproduce

1. Open Musescore (From Start Menu, executable, search, etc...)
2. Loading splash displays
3. Program does not open

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Windows 11

### Additional context

Previously, I had installed Musescore *using* Muse Hub. When I reinstalled, I had to download the installer from the "Download MuseScore without Muse Hub" section of musescore.org.

**Comment by bkunda** [comment]
As far as we know, this seems like it could be an issue specific to your environment.
@cbjeukendrup if you have a moment, could you please help troubleshoot this one? 
Alternatively, a request can always be put to the [support forum](https://musescore.org/en/forum/6) on musescore.org.

**Comment by thomasnoakes04** [comment]
I'm worried it might be, but I have no idea what could be causing it on my end. I'd be more than happy to provide specs etc. What concerns me is this is a fairly new installation of Windows, and MS4 and Muse Hub worked absolutely fine about a week ago.

**Comment by thomasnoakes04** [comment]
UPDATE: uninstalling and reinstalling the .NET framework seems to have fixed it. Windows Event Viewer showed Muse Hub having trouble using .NET 6.x.y. Further investigation shows another program had downloaded and installed .NET 8 (the latest version).
