### ISSUE TITLE
Latest master build doesn't start (MuseScoreNightly 241011542 master)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#22317]
### Bug description
Previous nightly master was fine

### Steps to reproduce

https://github.com/musescore/MuseScore/actions/runs/8634050285

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/8dc0fe48-5d3b-4196-ac3b-d796c9766866

### MuseScore Version

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac13.6/Win10

**Comment by Jojo-Schmitz** [comment]
Self-build version don't start either

**Comment by Jojo-Schmitz** [comment]
And I can confirm that #22319 fixes it
