### ISSUE TITLE
Tempo notation is incorrectly duplicated in scores for a symphony orchestra

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#22338]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Tempo notation in the score should be duplicated not only above the 1st or 2nd violins, but above the entire bowed string group. At the moment, in Musescore, when adding solo bowed string instruments, the tempo notation remains above the 1st violins.

### Steps to reproduce

1. Create a new score using the "Symphony Orchestra" template
2. After that, add the instrument "violin (solo)"

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/134041121/76b3a442-3151-4474-8a04-08c5bae68dbc

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

**Comment by bkunda** [comment]
@oktophonie is this likely to be something that needs the new system objects UI to solve?

**Comment by Jojo-Schmitz** [comment]
Yes, it does. Question is whether doing it is the RightTing (tm)

**Comment by oktophonie** [comment]
Will be addressed as part of https://github.com/musescore/MuseScore/issues/24100
