### ISSUE TITLE
Sound flag doesn't apply to left hand after reopening score (MuseSounds Keys)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#22374]
### Issue type

General playback bug

### Steps to reproduce

1. Open [hammond.zip](https://github.com/musescore/MuseScore/files/14966973/hammond.zip)
2. Apply sound flag to right hand (works only with musesampler v6)
3. Check playback (left hand sounds with sound flag effect)
4. Save and reopen score
5. Check playback - left hand sounds **without** sound flag effect

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/b6be2430-afb1-49e6-8c61-f4b837e68ce3

### MuseScore Version

4.3

### Regression

No.

### Operating system

all

**Comment by Jojo-Schmitz** [comment]
Question is which of the 2 behavoirs is correct or to be expected.
