### ISSUE TITLE
Unit tests broken in CI

### ISSUE THREAD

**Issue by rettinghaus** [musescore/MuseScore#22370]
### Issue type

Other type of issue

### Bug description

For some time now the CI unit tests are broken on master. They seem to be green, but not a single test is run, it just drops the line

> No tests were found!!!

### Steps to reproduce

Check some recent runs from PRs, e.g. 

- https://github.com/musescore/MuseScore/actions/runs/8643624752/job/23697043168
- https://github.com/musescore/MuseScore/actions/runs/8643169514/job/23695627800
- https://github.com/musescore/MuseScore/actions/runs/8632392540/job/23662966263

### Screenshots/Screen recordings

<img width="820" alt="image" src="https://github.com/musescore/MuseScore/assets/7693447/bb141cc3-99d7-4ee9-a9d2-9dada16f2eab">

### MuseScore Version

master branch

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

GitHub CI

### Additional context

I investigated it a bit and I think everything stems from commit e2c4e89e4c7b45990d44b21bda69ef165a8bcf3f by @igorkorsukov. Before this the tests ran as expected on master.

**Comment by Jojo-Schmitz** [comment]
Fortunately the 4.3.0 branch is not affected
Getting all tests to run again on mater will probably reveal quite a few failures

**Comment by Jojo-Schmitz** [comment]
As this issue renders us blind to unit test failures, I think a P0 prio is due

**Comment by Jojo-Schmitz** [comment]
See [6511abf](https://github.com/musescore/MuseScore/pull/22372/commits/6511abf49966c64b7f664eab4e41fcc0e6f6d607), it git at least a few tests to run

**Comment by Jojo-Schmitz** [comment]
Is #22402 supposed to fix this?
