### ISSUE TITLE
Shortcut for Preferences>Note Input>Play Notes When Editing

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#22382]
#### Regarding: Preferences>Note Input>**Play Notes When Editing** 

I have not found an **Action** for Preferences>Note Input>**Play Notes When Editing** in MuseScore 4 Preferences, so I'm requesting the addition of one if one does not currently exist. (Rationale and use case below ... in the **_Problem to be Solved_** section of this post.) 

Additionally, I advocate for a toggle button that the user can add to MuseScore 4's main toolbar, for ease of access.

One could argue that such a toggle is readily accomplished via a "mute" button on a QWERTY keyboard, but:

- I don't think it's safe to assume that all keyboards have such a key
- we won't attain versatile solution even with keyboards that have a "mute" key 

### Further considerations:

**First:** A QWERTY or an AZERTY mute button likely only mutes sound routed to the "System Output", or directly routed to Internal Speakers or headphones. Thus it won't mute sound sent to an audio interface, which may be central to a user's audio configuration.

**Second:** Muting all sound output would be undesirable in a context where I just want to toggle **Play Notes When Editing** Off, such as:

a) when I want to hear MuseScore's playback—just not MuseScore note entry or note selection
b) when I want to hear sound emanating from another music/audio app
c)  when I want to hear sound emanating from another music/audio app *and* from MuseScore's playback. And this is frequently true! 
d) when I need to hear MuseScore's playback *and* audio from a Zoom session—again, the goal is to specifically omit sound only of MuseScore note entry or note selection
e) In my studio, when a student it playing or a person is talking, there's no reason to distract the person by my editing. And I may have the student practicing along with another recording or MuseScore file, thus simply muting all sound is not a solution.

### Problem to be solved

Sometimes I need a way to quickly and temporarily silence the sounds MuseScore makes on input or selection.

Here's a use case: In my studio (or on a music lesson Zoom call) a student is  practicing with a hardcopy of a score I've created. I notice something I want to edit or add to the score. While he or she practices I want to quickly and easily toggle off **Play Notes When Editing** so I can silently make changes. (The requested MuseScore shortcut would make all this readily possible. )

In contrast, if I mute all sound output I'm effectively muting anyone on the Zoom call. Muting a private student on Zoom is rarely advisable as it can lead to an uncomfortable disconnect if they are trying to communicate with me.

**Comment by pacebes** [comment]
To clarify what this is about:
- We ask for an "action" for "Preferences>Note Input>Play Notes When Editing"
-  A toggle button... Next to "Parts" row or next to "notes" row ?
![image](https://github.com/user-attachments/assets/93f84b48-4c96-45f6-9487-a0c6143e6369)
- The toggle button... should also change the behavior (Play/don't play) for the next session (as in Preferences Window) or should only change the value of the current session ?. 
- If it should only change the behavior during the current session... shall it prevail over the "Preferences ...".??

**Comment by pacebes** [comment]
I don't know if adding an action for ""Preferences>Note Input>Play Notes When Editing" makes sense because the "OK" button will change modified properties.

**Comment by scorster** [comment]
> To clarify what this is about:
> 
> *  an "action" for "Preferences>Note Input>Play Notes When Editing [has been requested]"

Correct. And thanks for your interest.

> * A toggle button... Next to "Parts" row or next to "notes" row?

I think the best place would be in the Play Panel, either near or within the Play Panel's Gear menu.

> * The toggle button... should also change the behavior (Play/don't play) for the next session (as in Preferences Window) or should only change the value of the current session ?

I had imagine the preference setting persisting between MuseScore sessions. 

> * If it should only change the behavior during the current session... shall it prevail over the "Preferences ..."??

Sorry. I'm not sure what preferences it would prevail over.

Thanks again, scorster

**Comment by pacebes** [comment]
HI @scorster 

I figured out a way to make both options work:

- We can have an icon between Play panel and undo buttons: See:

![image](https://github.com/user-attachments/assets/abd6ffcc-b1f7-4f60-b32c-7cfbc285e595)

We could change the icon between 
![image](https://github.com/user-attachments/assets/f894d552-def0-484b-a128-a14517966b55)
and 
![image](https://github.com/user-attachments/assets/4876b497-1ff0-47b1-be5e-5fbf579283c6)
if playing when editing is active or not


- We could also add an option within the gear menu within the play gear menu as you suggested:
![image](https://github.com/user-attachments/assets/bb271cf8-f38e-4edf-a0e6-7efd2baa34f3)

We could use any icon you like and the "tick" would display if the mute is active or not.

Please, choose which one you find better and assign the issue to me to continue working on it (there is still some work to be done before I can create the pull request.

**Comment by cbjeukendrup** [comment]
@avvvvve Could you please advise about the above?

**Comment by scorster** [comment]
@pacebes

Nice progress!

## Regarding the placement of the icon in the toolbar

Everything to the right of the Gear icon is non-interactive, aside from the superfluous Undo / Redo icons. So I'm still leaning toward placing it immediately before or after the Gear icon.

I know toolbar real estate is a precious commodity, so there's likely to be push back on adding an icon, so we could fall back on only placing the option in Gear menu. But I think this option is more important than displaying the Undo and Redo icon. I don't think I ever even noticed they're there; and in 2024 I think most people know the keystrokes or use the Edit>Undo or Edit>Redo. BUT we can be grateful there's not a floppy disk icon for saving! 

## Regarding icon design

Was unable to open your .odt file ...

I think a simple speaker icon could be confusing, as it implies muting all playback.

At some point I submitted candidate icons (perhaps in a different discussion.) I'm not attached to them, but here they are:

     ![Pencil-Speaker icons for Sound on Edit](https://github.com/user-attachments/assets/af06d14c-e82f-4c64-9090-8450c7596d14)

When you're ready I can attach as PNG or SVG. 

## Regarding the Gear menu

Nice that you added toggle to the Gear menu! I'm going to think on wording.

Indeed the tick/checkmark means only one icon required.

**Comment by scorster** [comment]
BTW, at the opening of this thread my *second* request was for a toolbar control that toggles

My first request was for an Action, so I could assign a shortcut:

*I have not found an **Action** for Preferences>Note Input>**Play Notes When Editing** in MuseScore 4 Preferences, so I'm requesting one be added if one does not currently exist.*

That may be the simples solution and something that users can control with a shortcut of their choice.

**Comment by pacebes** [comment]
> @pacebes
> 
> Nice progress!
> ## Placement of the icon in the toolbar
> 
> Everything to the right of the Gear icon is non-interactive, aside from the superfluous Undo / Redo icons. So I'm still leaning toward placing the icon immediately before or after the Gear icon.
> 
> I know that toolbar real estate is a precious commodity, so there's likely to be push back on adding an icon. So we could fall back on only placing the option in Gear menu. But I think this editing option is more important than displaying the Undo and Redo icons. (I don't think I ever even noticed them out there in right field—and in 2024 most people know the keystrokes or use the Edit>Undo or Edit>Redo. BUT we can be grateful there's not a floppy disk icon for saving!)
> ## Icon design
> 
> Was unable to open your .odt file ...
> 
> I think a simple speaker icon could be confusing, as it implies muting all playback.
> 
> At some point I submitted candidate icons (perhaps in a different discussion.) I'm not attached to them, but here they are:
> 
> When you're ready I can attach as PNG or SVG.
> ## The Gear menu
> 
> Nice that you added the toggle to the Gear menu! I'm going to think on wording.
> 
> Indeed the tick/checkmark means only one icon required in the menu.

I have attached now a PDF with the icon list so you could choose one: [MuseScoreIconsList.pdf](https://github.com/user-attachments/files/17615288/MuseScoreIconsList.pdf)

I presume that adding icons is something "global" (an address should be assigned) that should be reviewed by MuseScore team.  There may even be a user interface design group responsible for reviewing the user icon design. Am  I right @cbjeukendrup ?.  If there is no need to review the icon I would appreciate any help about how to add the icon and which address should be given to them.  I have created the attached PDF with https://tophix.com/font-tools/iconfont-viewer and uploading the MusescoreIcon.ttf file.

So, what we would like to do now is:
- Create an Action (Its name for the time being is "play-notes-when-input").  ** I am open to suggestions**
- Include a "toggle" within the gear menu. I am also waiting for a label name... please
- Icon: I would like you to choose an existent icon (attached PDF)

Is that OK

**Comment by pacebes** [comment]
> BTW, at the opening of this thread my _second_ request was for a toolbar control that toggles
> 
> My first request was for an Action, so I could assign a shortcut:
> 
> _I have not found an **Action** for Preferences>Note Input>**Play Notes When Editing** in MuseScore 4 Preferences, so I'm requesting one be added if one does not currently exist._
> 
> That may be the simplest solution and it something that users can toggle with a shortcut of their choice. Wait, now I'm wondering.
> 
> Can Actions be toggles??

Yes, as far as I know. The Action is a function that can change the value of a property (true if false and false if true)

**Comment by pacebes** [comment]
I have a working version with:
- Action code: **toggle-play-notes-when-editing**
- Synchronization between Preferences Window "Play notes when editing" option and this "Play notes when editing" toggle Menu Option
- This is the current version:
![image](https://github.com/user-attachments/assets/de99b2c8-f3fa-4f5f-9499-0f9cde5f17ab)

![image](https://github.com/user-attachments/assets/350671b8-c334-411c-8622-5b6d0d0141eb)

- We can change the icon and the text. It's up to you @scorster 

So, what should we do now ?
- Are we going to have a different icon or a new icon icon for this menu option ?
- Should I create the Pull request when both decisions are made ?

**Comment by cbjeukendrup** [comment]
Let's wait for @avvvvve's opinion, he is one of the designers in the team, so he can definitely help!

**Comment by pacebes** [comment]
Ok.
Just remember than we could also hace this menu option without icon

**Comment by pacebes** [comment]
I have checked again this issue and I have found that, although it is still open it appears as: "Fixed by https://github.com/Jojo-Schmitz/MuseScore/pull/423"

![imagen](https://github.com/user-attachments/assets/cf44c4cc-a58e-454e-b1b3-a58ec081e9c0)

Is it already fixed or it is up to @avvvvve to decide what should be done ?

**Comment by cbjeukendrup** [comment]
"Fixed by https://github.com/Jojo-Schmitz/MuseScore/pull/423" means that Jojo ported some fix to his 3.7 repo. 
But for the master branch, there is no decision or solution yet.

**Comment by scorster** [comment]
Here's a related preference I wanted today: the option to hear clicked notes in tracks that are muted in the Mixer. I think I'd always want that ON. 

Interestingly though when it's OFF it (like the current default behavior) it would suffice for the original request in this thread!

**Comment by pacebes** [comment]
So. You are asking for two different things
1.- The one I have already implemented:

**Comment by scorster** [comment]
> So. This issue asks for two different things: 1.- The one I have already implemented: a toggle option to activate-deactivate playing notes when editing synchronized with Preferences Window "Play notes when editing" option ![imagen](https://private-user-images.githubusercontent.com/3304588/386071062-c44e3ad9-be84-4754-9e49-84bc02cb0121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTY2OTAsIm5iZiI6MTczMTY1NjM5MCwicGF0aCI6Ii8zMzA0NTg4LzM4NjA3MTA2Mi1jNDRlM2FkOS1iZTg0LTQ3NTQtOWU0OS04NGJjMDJjYjAxMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMDczOTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNhMjU3YmU4MjlkYzJkMDYwODFmNDAxZTVjNjJjOTM3YmY3NTc0MjViYzlhZjQ3YWZiZjE0MGUzNDQ2ZWM5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.UT9gI1bSlphgq1lziP61UEqVqWquiuUcB6O4AheComE)
> 
> 2.- An additional option (I presume next to "Play notes when editing") which could be called "Ignore mixer mute when editing". If this option is "on": 2.1. If "play notes when editing" is "on": ignore instrument Mute settings in Mixer and play notes when editing for every instrument: ![imagen](https://private-user-images.githubusercontent.com/3304588/386073490-168f648d-e888-41e8-afe3-7076a4ebd4dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTY2OTAsIm5iZiI6MTczMTY1NjM5MCwicGF0aCI6Ii8zMzA0NTg4LzM4NjA3MzQ5MC0xNjhmNjQ4ZC1lODg4LTQxZTgtYWZlMy03MDc2YTRlYmQ0ZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMDczOTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTk0MTU3YTNhNWRmNmMyNGRkOWRlY2Y1MzgwNzU4ODUxNGIwY2E4ZTYzOTkyMjBkZjIxMmVlOGJhOTE2ODI3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Re4muWgPagpzHAY10v_ZcJ6bT0gmIrPwg25U4qOUjGw)
> 
> 2.2. If "play notes when editing" is "off": current behavior.


> Am I right?. 

Yes, this all sounds good to me. 

> Which icon should we use for this "Ignore mixer mute when editing"?

I'm going to have to think on that!

**Comment by scorster** [comment]
First thoughts this morning for the Override Mixer Mute on Note Selection

![Override Mixer Mute ](https://github.com/user-attachments/assets/436ba29d-d9f7-4027-ab37-9d516961600d)

**Comment by pacebes** [comment]
Hi
I have just found a way to deal with the "Override Mixer Mute on Note Selection" option. 

@cbjeukendrup , I need to know if 
1.- I can deliver these changes or they have to be reviewed by @avvvvve , 
2.- If I can deliver these changes, what about the new icons?. Are they to be integrated by @avvvvve ( and providing me with a new MusescoreIcon.ttf file or should I integrate them (and assign them an address within the ttf file and delivering the new file )?

**Comment by pacebes** [comment]
By the way @scorster , I presume this "Override Mixer Mute on Note Selection" doesn't need to be kept between sessions. The option state will be lost if you exit from MuseScore and start it again

**Comment by scorster** [comment]
> By the way @scorster , I presume this "Override Mixer Mute on Note Selection" doesn't need to be kept between sessions. The option state will be lost if you exit from MuseScore and start it again.

Right. We don't people tripping over persistent settings, but personally I would want this ON and always ON. I can't imagine it confusing people ... although I was initially confused when I clicked a note in a muted track and heard nothing. Can we assume this was by design?

If you want to use either of my icons I can attach them and save you a few minutes of time.

**Comment by pacebes** [comment]
I have made the "override mixer mute on Note selection" true whenever you start the program
![image](https://github.com/user-attachments/assets/0c9020c0-3a1e-464a-851f-55eda19329ee)

About the icons. I'm sorry but I haven't found a way to add icons (PNG or SVG or whatever) to MusescoreIcon.ttf. I would appreciate if you, @scorster , provide me with the icons,  subject to @avvvvve  approval, and give me some hints about how to add them to the ttf file. I have tried with birdfont without success.

@cbjeukendrup , any feedback about how to proceed would be appreciated

**Comment by scorster** [comment]
Sure. Just let me know when you're ready ... and which icons you want. 

BTW, your Mixer icon is a good choice.

**Comment by pacebes** [comment]
If you think the Mixer icon is a good choice we can keep this one for  "Override Mixer Mute on Note Selection" option. 

About "Play notes when editing" on/off icon... I think we should wait to @cbjeukendrup  and @avvvvve . I have understood that we depend on their approval. They could provide us with what you are asking for ( bounding box dimensions and the resolution if we need rasterized rather than SVG)

**Comment by pacebes** [comment]
Sorry to bother you @cbjeukendrup. 

I presume we should wait for something to be said about this issue: if we can include the options in this menu and the icons we could use. Am I right?

I will freeze the code until something is decided.

**Comment by avvvvve** [comment]
@scorster @pacebes Sorry for the delayed response! The Note input page in Preferences has become a moving target via several community and internal projects so it's taken some time to step back and bring it all together.

So there are two separate requests here:

### 1. Add a shortcut to toggle on/off the existing "Play notes when editing" preference in Preferences > Note input

As mentioned above, we redesigned the Note input Preferences page to accommodate this new feature: #24352. As shown in the [spec I posted there](https://github.com/user-attachments/files/17639455/Preferences.Note.input.MIDI.pdf), we're changing the wording of "Play notes when editing" to "Hear playback when adding, editing, and selecting notes". When turned off, everything immediately beneath this toggle gets disabled.

So here's what I'd like to do:

- Yes, add this to the Playback toolbar context menu (from the gear icon) but use the existing pencil icon (U+EF63 in the MusescoreIcon font) since it's already associated with note input. _Note: We may come back with a new icon as a follow-up. Combining the speaker and pencil might be the right direction._
- Change the title to "Hear playback when editing" and place it after "Pan score automatically".
     <img width="507" alt="image" src="https://github.com/user-attachments/assets/d037091a-78b5-4765-819b-63badf6027c1">
- Add an action in Preferences > Shortcuts to toggle it, titled "Toggle hear playback when editing" (and include the pencil icon)


### 2. Add a new preference to control whether, when the above preference is ON, you hear notes added/clicked/selected on instruments that are muted in the mixer.

This indeed should be added as a preference, and should _not_ reset every session. It should be a child item of the above "Hear playback..." preference in the Note input page.

However, it should _not_ be included as a toggle in the Playback toolbar menu, because:
-  There is not an obvious utility in needing to toggle this often, especially given the general shortcut for "Hear playback..." we're adding above
- Since it's one of several child settings of "Hear playback..." it doesn't make sense to elevate only this option to the context menu and not the others (and we shouldn't elevate ALL of them either—at that point, just open Preferences!)

So, this is what should be implemented:
- Add a checkbox "Play notes on muted tracks" to Preferences > Note input as pictured below in the new design. It should be _off_ by default to retain the current behavior.
     <img width="539" alt="image" src="https://github.com/user-attachments/assets/d4a574cb-01fd-475e-ba0b-ca045238084a">
- Since this new design hasn't been implemented yet, feel free to just add it as a sub-checkbox of the existing "Play notes when editing" preference underneath "Play chord symbol when editing"


A note about icons: As you can probably tell, we have a defined icon style that we adhere to, so we (the MuseScore Studio design team) will handle creating these ourselves. No harm in suggesting ideas but (for now) it's up to us to draw and add them to the font.

**Comment by pacebes** [comment]
Ok @avvvvve .

You are now assigned to this issue. Could you please assign it alto to me to continue working on it?

Thanks

**Comment by pacebes** [comment]
I will create two pull requests. One for each request

1. Add a shortcut to toggle on/off the existing 

Gear menu:
![image](https://github.com/user-attachments/assets/b9901721-f43a-4d1c-842c-ca697373c179)

Shortcut

![image](https://github.com/user-attachments/assets/7a8258f8-0df9-4a11-a139-d09cd517ae97)

**Comment by pacebes** [comment]
The pull request https://github.com/musescore/MuseScore/pull/25671 implements the first part of the functionality: **Add a shortcut to toggle on/off the existing "Play notes when editing" preference in Preferences > Note input**

**Comment by pacebes** [comment]
I have created the second Pull request (https://github.com/musescore/MuseScore/pull/25683) to implement the Part 2: **2. Add a new preference to control whether, when the above preference is ON, you hear notes added/clicked/selected on instruments that are muted in the mixer.**

It is built OK in Linux and Windows, but building fails in MacOs with an error that doesn't seem to have nothing to do with the pull request itself:
```

In file included from src/framework/audio/CMakeFiles/muse_audio.dir/Unity/unity_0_cxx.cxx:10:
In file included from /Users/runner/work/MuseScore/MuseScore/src/framework/audio/audiomodule.cpp:75:
In file included from ../src/framework/audio/internal/platform/osx/osxaudiodriver.h:29:
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/MacTypes.h:548:16: error: reference to 'Point' is ambiguous
typedef struct Point                    Point;
               ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/MacTypes.h:544:8: note: candidate found by name lookup is 'Point'
struct Point {
       ^
../src/framework/draw/types/geometry.h:154:7: note: candidate found by name lookup is 'muse::Point'
using Point = PointX<int>;
      ^
```
does anyone know someone I can talk to about this problem?

Thanks in advance

**Comment by cbjeukendrup** [comment]
This has been closed automatically because the first PR corresponding to it was merged; but of course, the second problem that came up in this thread (playback preview for muted channels) has not yet been resolved. I could of course reopen this issue, but it seems better to open a dedicated issue for that, and then edit the description of https://github.com/musescore/MuseScore/pull/25683 to refer to that new issue. @scorster May I ask you to open such issue?

**Comment by pacebes** [comment]
I presume I should create a new Pull Request once this issue is open.
Should I also delete the previous one I created to deal with it ( https://github.com/musescore/MuseScore/pull/25683 ) a iterate over the new Pull request created

**Comment by cbjeukendrup** [comment]
@pacebes No, you can just edit the description of the existing pull request; then everything will be fine (or actually, I can help with that, once the new issue is open)
