### ISSUE TITLE
Dynamic aligns with invisible cresc./dim. line

### ISSUE THREAD

**Issue by SnyBr** [musescore/MuseScore#22384]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

If a cresc./dim. line with the "show line" property disabled is extended to connect/snap to the next dynamic, then the dynamic is aligned to the same vertical position as the line.

Current behaviour:
![Screenshot from 2024-04-13 20-26-02](https://github.com/musescore/MuseScore/assets/105515763/848dbf98-b83a-41bb-91f1-886ed4140e78)

Expected behaviour:
![Screenshot from 2024-04-13 20-26-26](https://github.com/musescore/MuseScore/assets/105515763/5b252ab2-cc8f-4e68-ab30-2dd8c831bd13)

### Steps to reproduce

1. Enter a few notes, ensuring that any dynamics/cresc./dim. lines attached to the first and last note would be on different vertical positions.
2. Enter a dynamic marking on the last note (p, mp, f, etc).
3. Enter a cresc./dim. marking on the first note
4. Extend the cresc./dim. line (using shift+right arrow) until it connects with the dynamic on the last note. The cresc./dim. and dynamic should now be aligned
5. Select the cresc./dim. and untick the "Show Line" option. The cresc./dim.'s line now turns invisible, but the dynamic on the last note is still aligned as if the line was visible.

### MuseScore Version

4.2.1

### Regression

I don't know

### Operating system

Ubuntu 22.04.4 LTS

**Comment by Dima12357** [comment]
In this case, it would be more logical to implement intuitive automatic placement with a diagonal change in order to save space.
![Снимок экрана (245)](https://github.com/musescore/MuseScore/assets/134041121/38dc744b-cb8b-4a61-933e-d1fc205629fd)

**Comment by oktophonie** [comment]
Note: the fix to this issue will effectively be undone by https://github.com/musescore/MuseScore/pull/23046, which allows you to control alignment and line visibility independently.

**Comment by Dima-S-Jr** [comment]
What is interesting is that now the text _cresc._/_dim._ they remain at the same level as the dynamics (even if the line is invisible):

https://github.com/user-attachments/assets/1972e470-9af8-4fcf-a6ea-ccb65102d01b

**Comment by cbjeukendrup** [comment]
That's basically the same as the original issue, but the other way around; but I think Simon's comment applies here too: it can be prevented by disabling "Snap to next". 
(I guess that the reason that it is not prevented by default, is that the alignment may be desired sometimes.)
