### ISSUE TITLE
Musescore 4 sends strange messages to midi out on every measure change

### ISSUE THREAD

**Issue by harakiriman** [musescore/MuseScore#22386]
I have just monitored an empy score midi out, and found that Musescore sends strange midi messages on every measure, just when crossing the bar line. See attached image.
![Captura de pantalla 2024-04-13 140342](https://github.com/musescore/MuseScore/assets/166954563/d5ce7225-e0b3-4e5e-a275-b54a07cc3b91)

_Originally posted by @harakiriman in https://github.com/musescore/MuseScore/issues/22354#issuecomment-2053756273_
 
MIDI-OX : http://www.midiox.com/
Virtual midi driver to route messages to MIDI-OX: https://www.nerds.de/en/loopbe1.html

**Comment by Steven1955** [comment]
Who should I contact? I would like to help resolve this issue. Definitely have programming experience. However, I don't know where to start. How do I get access to the development platform? Can someone help me on my way?

**Comment by shubham-shinde-442** [comment]
@Steven1955 To contribute, you need to check wiki. All things is already there.
 Link - https://github.com/musescore/MuseScore/wiki

**Comment by MarcSabatella** [comment]
I believe this is the metronome, and this is already reported as https://github.com/musescore/MuseScore/issues/12552

**Comment by harakiriman** [comment]
Not only. The sustain pedal and pitch bend events shoudn't be there too.

**Comment by knoike** [comment]
@MarcSabatella 
What about those pitch bend and sustain pedal events?
He(@harakiriman ) says that these things are also strange.

Plese see related post in musescore.org forum.
https://musescore.org/en/node/341519#comment-1237003

**Comment by zacjansheski** [comment]
@harakiriman 

Could you try https://github.com/musescore/MuseScore/pull/22924 and confirm if the issue is resolved for you?

**Comment by zacjansheski** [comment]
Thank you!

Please follow the [link to the PR](https://github.com/musescore/MuseScore/pull/22924) and follow these [instructions](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests)

**Comment by harakiriman** [comment]
Done.

I made the same test, monitoring midi out while playing an empty score, and no midi messages are sent now.

Test passed succesfully.
Good work.

________________________________
De: Zac Jansheski ***@***.***>
Enviado: miércoles, 22 de mayo de 2024 18:19
Para: musescore/MuseScore ***@***.***>
Cc: harakiriman ***@***.***>; Mention ***@***.***>
Asunto: Re: [musescore/MuseScore] Musescore 4 sends strange messages to midi out on every measure change (Issue #22386)


Thank you!

Please follow the link to the PR<https://github.com/musescore/MuseScore/pull/22924> and follow these instructions<https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests>
