### ISSUE TITLE
slur goes straight through a duplet

### ISSUE THREAD

**Issue by DominAbbus** [musescore/MuseScore#22389]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

See the attached file. In bar 11, the slur slashes through the "2" of the duplet.

### Steps to reproduce

Open the attached file
Delete the slur in bar 11
Re-apply the slur.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

### Additional context

[Alpenhornzauber - copy.zip](https://github.com/musescore/MuseScore/files/14970246/Alpenhornzauber.-.copy.zip)
![image](https://github.com/musescore/MuseScore/assets/76609300/ee03398e-ad31-4901-92f5-6ef9cdc9c47d)

**Comment by Dima12357** [comment]
@DominAbbus, I think this is a duplicate of issue #15336.

**Comment by Daniel-R15** [comment]
Came up again in the MuseScore Support forum:
**Slurs and tuplet brackets/numbers overlap**
https://musescore.org/en/node/382384

See mm. 21-26 in the score attached to the forum post.
