### ISSUE TITLE
Timpani 4th Round Robin 'B2' note is silent using piano dynamics

### ISSUE THREAD

**Issue by Thiago-Morais** [musescore/MuseScore#22395]
### Issue type

Muse Sounds bug

### Bug description

Every Timpani 4th Round Robin 'B2' note is silent using piano dynamics

### Steps to reproduce

1. Add a Timpani instrument
2. Add at least 4 B2 notes
3. Apply the 'Piano' (p) dynamics
4. Every 4th note is silent

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/21369746/c9787298-6391-46a1-8654-494754bdaa1a

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64, 

### Additional context

[Error - Timpani don't play 4th B note .zip](https://github.com/musescore/MuseScore/files/14972513/Error.-.Timpani.don.t.play.4th.B.note.zip)

**Comment by zacjansheski** [comment]
Fixed by https://github.com/staffpad/Instruments/pull/158
