### ISSUE TITLE
4.2.1 - Keyboard Shortcut Issue on AZERTY Keyboards

### ISSUE THREAD

**Issue by Jetinho** [musescore/MuseScore#22394]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Bug Report: MuseScore 4.2.1 - Keyboard Shortcut Issue on AZERTY Keyboards

Summary: Users with AZERTY keyboards are experiencing a critical issue in MuseScore 4.2.1 where keyboard shortcuts used to change note durations (Shift + number keys) are non-functional. This problem, reported across various operating systems, particularly affects Mac users without numeric keypads. The shortcuts worked correctly in previous version 4.2.0, indicating a regression in the latest update.

Steps to Reproduce:

Impact: This bug severely affects usability for users relying on keyboard shortcuts for efficient score editing.

For more details, refer to the user discussion [here](https://musescore.org/fr/node/359708). and [here in english](https://musescore.org/en/node/359722)

### Steps to reproduce

Use an AZERTY keyboard.
Attempt to change note durations using Shift + number keys.
Expected Result: The note duration changes as per the input.
Actual Result: No change in note duration occurs.

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS

**Comment by zacjansheski** [comment]
@Jetinho 
could you confirm if https://github.com/musescore/MuseScore/pull/22906 resolves this issue?

**Comment by Jetinho** [comment]
> @Jetinho could you confirm if #22906 resolves this issue?

Hi @zacjansheski, I don't know how I can test it.
Is there a wiki where I can find the information about how to run a local version of musescore directly from the repo ?

I could be interested in contributing to the project after learning the basics of the environment.

**Comment by oktophonie** [comment]
@Jetinho There is indeed a guide [here](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests).

**Comment by Jetinho** [comment]
Thanks @oktophonie and @zacjansheski, I just checked and the problem is solved indeed 👍
