### ISSUE TITLE
Expose new text inference MusicXML option as command-line flag

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#22409]
For batch processing of MusicXML files, the new 'Infer text type based on content where possible' option (implemented in https://github.com/musescore/MuseScore/pull/21908) is to be exposed via a command-line flag. (The option is turned off by default, so the presence of this flag in a command will turn it on.)

**Comment by Jojo-Schmitz** [comment]
Can't we generalize this for any setting?

**Comment by Jojo-Schmitz** [comment]
Like `mscore --internalsetting name=value`, here `mscore --internalsetting import/musicXML/importInferTextType=true`

**Comment by igorkorsukov** [comment]
> Can't we generalize this for any setting?
> 
> Like `mscore --internalsetting name=value`, here `mscore --internalsetting import/musicXML/importInferTextType=true`

There are several disadvantages to this approach: 
* In a method with a declaration of options, we will not see the real options
* Accordingly, these options will not be in the documentation, in the help
* It will be necessary to add additional parsing value: "key=val"
* This expression will not be standardized, developers may start adding different variants
* If you add a space between  "key=val", then everything will break and it will not be obvious why

**Comment by igorkorsukov** [comment]
For specific options, I would prefer to declare them like: `module_option"

Like this: 
```
    // Diagnostic
    m_parser.addOption(QCommandLineOption("diagnostic-output", "Diagnostic output", "output"));
    m_parser.addOption(QCommandLineOption("diagnostic-gen-drawdata", "Generate engraving draw data", "scores-dir"));
    m_parser.addOption(QCommandLineOption("diagnostic-com-drawdata", "Compare engraving draw data"));
    m_parser.addOption(QCommandLineOption("diagnostic-drawdata-to-png", "Convert draw data to png", "file"));
    m_parser.addOption(QCommandLineOption("diagnostic-drawdiff-to-png", "Convert draw diff to png"));
```
