### ISSUE TITLE
i can't install musehub 

### ISSUE THREAD

**Issue by shougami** [musescore/MuseScore#22417]
hi,i am having problem installing musehub, the installation will only open at "getting ready ..." for you, then after that nothing follows. I did this a few times, still have no luck. I monitored this at task manager, and it will completely disappear after the "getting ready..." message. I am running in windows 11. I hope someone could help me here because I also seen the same issues at musehub zendesk but it seems no one can entertain those problems and give solution.

**Comment by bkunda** [comment]
I'm really sorry, but unfortunately we can't solve this problem for you on the MuseScore Studio side (the Hub zendesk really is the place to go for this).
