### ISSUE TITLE
Tremolo note pair tied to note in next measure will cause a crash

### ISSUE THREAD

**Issue by birdwellmusic** [musescore/MuseScore#22418]
### Issue type

Crash or freeze

### Bug description

A measure with tremolo where the last note in the tremolo is tied to the first note in a subsequent measure may cause a crash. Further, attempting to generate a part with this "tied tremolo" scenario produced a crash.

![image](https://github.com/musescore/MuseScore/assets/22352556/d186b09a-ed53-4945-b50b-6a77edec6166)

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Steps to reproduce

1. create two half notes in a measure and apply the tremolo (two line, 16th notes) which will visibly changed the notes to two whole notes.
2. in the subsequent measure, add an eighth note;
3. in the preceding tremolo measure create a tie to the eighth note in the subsequent measusre

In my current version ( 4.2.1-240230937) this may produce an immediate crash.

If this doesn't produce an immediate crash, try creating a Part for this staff. In my current version this "tied tremolo" scenario cause a crash every time, until I remove the tie.

### MuseScore Version

4.2.1-240230937

### Regression

I don't know

### Operating system

Windows 11

**Comment by oktophonie** [comment]
Wasn't able to reproduce this one in 4.2.1 (Linux and Windows), nor master, either with a part or not.

**Comment by zacjansheski** [comment]
I also haven't been able to reproduce

@birdwellmusic we need more information to diagnose.  
Could you share the musescore file? (you can post here as a .zip)  
Could you share diagnostic files? (Diagnostic>Save Diagnostic Files)

**Comment by birdwellmusic** [comment]
I was also unable to replicate this today, either in my original score or in a newly re-created score. So at this point I'm wondering if it was just something else (my OS, some other condition?) causing the issue. Sorry for the fuss. The crash was so consistent yesterday and I was able to replicate and the only thing that seemed to fix it was to take away the tied note from the tremolo measure.

**Comment by cbjeukendrup** [comment]
> Could you share diagnostic files? (Diagnostic>Save Diagnostic Files)

This might give us helpful information to find out what happened. So if you could upload that, we can maybe still fix the problem so that it never happens again. Otherwise we'll probably have to close this issue, if there's no way to reproduce it.
