### ISSUE TITLE
Cant disable update checking

### ISSUE THREAD

**Issue by lyrra** [musescore/MuseScore#22439]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

unchecked the box "Automatic update check".
Still musescores tries to contact amazon.

### Steps to reproduce

.

### Screenshots/Screen recordings

![bild](https://github.com/musescore/MuseScore/assets/243748/787fd648-d26f-4452-bae5-61bfa5dfea69)

```
16:54:15.396 | ERROR | 140583087609536 | NetworkManager::execRequest | [503] Error transferring https://updates.musescore.org/feed/musesampler.latest.xml - server replied: 
16:54:15.396 | ERROR | main_thread     | UpdateScenario::doCheckForMuseSamplerUpdate | Unable to check for update, error: [1702] 
```

### MuseScore Version

master

### Regression

I don't know

### Operating system

debian bookworm

**Comment by Eism** [comment]
This checkbox for MuseScore updates, not for MuseSounds updates

**Comment by lyrra** [comment]
> This checkbox for MuseScore updates, not for MuseSounds updates

But isn't checking for updates to MuseSounds something MuseHub should do?

**Comment by lyrra** [comment]
closing, tested and it seems the checkbox covers both musescore and musesampler.
