### ISSUE TITLE
MusicXML ex- and them import moves title to footer

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#22467]
### Issue type

Import/export issue

### Steps to reproduce

1. Open the attached score
    https://github.com/musescore/MuseScore/files/15014139/Mu4-Test_4_mxl_issue.zip
2. Export to MusicXML
3. Import it (or this)
    https://github.com/musescore/MuseScore/files/15013504/Test_Mu4.zip
4. See that the title frame is empty (or rather has the content of the next frame), but there's a frame at the bottom of the (next) page containing the title, so it looks like the 1st and 2nd frame swapped their places.
    ![323292044-81362c99-9c51-473d-b791-aa5e71903482](https://github.com/musescore/MuseScore/assets/1786669/941add4f-2767-484f-9c53-f0be043931af) (Image from Mu3.7, which has a nother problem, it hides empty staves)

Culprit, or rather trigger, seem to be the other frames that score has, as removing those 'fixes' the issue.
I haven't (yet) been able to reproduce the issue from scratch though.

### MuseScore Version

All, as far as I can tell, at least 3.6.2 up to latest master

### Regression

No.

### Operating system

Windows 11

**Comment by lvinken** [comment]
This is by design, see function addCreditWords() in file importmxmlpass1.cpp.

**Comment by Jojo-Schmitz** [comment]
Hmm, but is it good design? The result is pretty unexpected, at least pretty undesirable.

**Comment by lvinken** [comment]
Hi all,

a little extra information on this issue. MuseScore's MusicXML importer currently creates a maximum of two vertical frames to put MusicXML credits in. These frames collect the credits in the top and bottom half of the page. If there are more credits in the bottom half than in the top half of the first page, they get swapped. The purpose is to correct the (IMHO) annoying Sibelius export, which puts title, composer etcetera (incorrectly ?) in the bottom half. Unfortunately for some corner cases this leads to unexpected results. Disabling this behavior is trivial, see https://github.com/lvinken/MuseScore/commit/9cb02b16cebf6847726a12a4b9267a3a11f9ec57.

To illustrate the effect of this change, the attached zipfile contains a number of PDFs generated by MuseScore with (names ending in "doSwap false") and without ("as is"). Output by Finale NotePad is also included.

Feedback and suggestions welcome and appreciated.
Regards, Leon.

[issue_22467_fix.zip](https://github.com/user-attachments/files/15518041/issue_22467_fix.zip)

**Comment by lvinken** [comment]
Sibelius files used were found on MuseScore.org:

- Chocolates variation 4.10.19: https://musescore.org/en/node/289264
- Hallelujah_Cohen: https://musescore.org/en/node/281306
- Pemulwuy: https://musescore.org/en/node/286768
