### ISSUE TITLE
Huge and unremovable space between text frames

### ISSUE THREAD

**Issue by juancarlangas** [musescore/MuseScore#22465]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Just create a text frame after the first default title frame, or create two consecutives text frames, and MuseScore creates a **huge space between them**. There are unremovable

![Screenshot_20240417_123114](https://github.com/musescore/MuseScore/assets/72962922/77fe3d02-d382-415e-be2a-3bef31fca944)

### Steps to reproduce

1. Create a new score
2. Insert a text frame as the first element after the title frame
   or
   Insert two text frames consecutively

### MuseScore Version

OS: Ubuntu 22.04.4 LTS, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230938, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Kubuntu 22.04.2 LTS x86_64

**Comment by MarcSabatella** [comment]
This is not a bug.  The default gap above and below all vertical and text frames is 7 sp, which is appropriate for many frames but obviously not for all.  You can easily override this either for specific frames or score-wide in the Properties panel.

**Comment by juancarlangas** [comment]
@MarcSabatella Thank you very much. Proceed to delete. Thanks

**Comment by juancarlangas** [comment]
@MarcSabatella Thank you very much. Proceed to delete. Thanks
