### ISSUE TITLE
 Opening Mu4.mxl (musicxml) file with Mu3.7 

### ISSUE THREAD

**Issue by youtsos** [musescore/MuseScore#22464]
### Issue type

Opening/saving issue

### Bug description

Opening the file renders a messed up score file.
--Lyrics mixed up with staves.
--Score Title become score footer.

### Steps to reproduce

Export Mu4 file as musicxml
Open file with Mu3.7

### Screenshots/Screen recordings

OS: Windows 10 Version 2009 or later, Arch.: x86_64
MuseScore version (64-bit): 3.7.0.8709592029,
revision: GitHub-Jojo-Schmitz-MuseScore-edc0289
![Test_Mu4](https://github.com/musescore/MuseScore/assets/167244247/81362c99-9c51-473d-b791-aa5e71903482)

### MuseScore Version

3.7

### Regression

No.

### Operating system

Windows 11

### Additional context

 Jojo Schmitz replies on Musescore Forum:
 
1) Well, I guess it comes from this in importmxmlpass2.cpp:

      StringData* t = new StringData;
      QString visible = _e.attributes().value("print-object").toString();
      QString spacing = _e.attributes().value("print-spacing").toString();
      if (visible == "no" ) {
            // EITHER:
            //  1) this indicates an empty staff that is hidden
            //  2) this indicates a cutaway measure. if it is a cutaway measure then print-spacing will be yes
            if (spacing == "yes") {
                  measure->setStaffVisible(staffIdx, false);
                  }
            else if (measure && !measure->hasVoices(staffIdx) && measure->isOnlyRests(staffIdx * VOICES)) {
                  // measures with print-object="no" are generally exported by exporters such as dolet when empty staves are hidden.
                  // for this reason, if we see print-object="no" (and no print-spacing), we can assume that this indicates we should set
                  // the hide empty staves style.
                  _score->style().set(Sid::hideEmptyStaves, true);
                  _score->style().set(Sid::dontHideStavesInFirstSystem, false);
                  }
...
I just don't see how/why that mxl takes that code path, it doesn't have "print-object" set at all

2)  Ctrl+A, Ctrl+R seems to fix the misplaced lyrics.

3)  That's the same in 4.6.2, 3.7 Evolution, 4.2.1 and latest master build, so at least very consistent.

**Comment by Jojo-Schmitz** [comment]
You'd need to open this issue against a different repo, https://github.com/Jojo-Schmitz/MuseScore/issues/new

**Comment by Jojo-Schmitz** [comment]
The lyrics muxup is a plain 3.7 issue, and due to "Hide empts Staves" being checked on MusicXML import for some strange reason

**Comment by Jojo-Schmitz** [comment]
[Test_Mu4.zip](https://github.com/musescore/MuseScore/files/15013504/Test_Mu4.zip)
Here's the mxl file, as taken from https://musescore.org/en/node/362955

**Comment by Jojo-Schmitz** [comment]
The header issue is with Mu4 rtoo, please reopen

**Comment by Jojo-Schmitz** [comment]
Here's the mscz
[Mu4-Test_4_mxl_issue.zip](https://github.com/musescore/MuseScore/files/15014139/Mu4-Test_4_mxl_issue.zip)

**Comment by Jojo-Schmitz** [comment]
Culprit is the existence of othger vertical frames (in addition to the title frame), that seems to throw the MusicXML import off track

**Comment by Jojo-Schmitz** [comment]
Can you please reopen (and remove the 3.7 references from the title at least)

**Comment by cbjeukendrup** [comment]
It would be better to create a clean new issue, containing only the problem that is relevant to MS4.

**Comment by Jojo-Schmitz** [comment]
Done, see #22467
