### ISSUE TITLE
Cannot access RewindMode enum

### ISSUE THREAD

**Issue by looptailG** [musescore/MuseScore#22505]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When writing a plugin for Musescore and trying to use the enum `RewindMode` from the `Cursor` class, you get the following error message (or similar error messages, depending on which enum value you're trying to access):

```
14:-1: TypeError: Cannot read property 'SCORE_START' of undefined
```

[ExampleFiles.zip](https://github.com/musescore/MuseScore/files/15049079/ExampleFiles.zip)

### Steps to reproduce

1. Open any file in Musescore.
2. Run the example plugin atteched to the bug description section.
3. You will get the following error message: `Cannot read property 'SELECTION_START' of undefined`

### MuseScore Version

4.2.1-240230937

### Regression

No.

### Operating system

Windows 10

### Additional context

[Link to the original discussion on the forum.](https://musescore.org/en/node/363091#comment-1237951)

**Comment by XiaoMigros** [comment]
This is not the correct way to use the enum: `Cursor.SCORE_START` or `Cursor.SELECTION_START` work in 3.x and 4.x

**Comment by looptailG** [comment]
Indeed, that way it works.

I guess we misunderstood how it works, from the documentation it seemed like you had to call it with `Cursor.RewindMode.SCORE_START`.

**Comment by XiaoMigros** [comment]
A better way than the documentation is to look at existing plugins (for example, my github profile) :)

**Comment by looptailG** [comment]
I'll definitely keep this in mind, thanks for the help.

**Comment by Jojo-Schmitz** [comment]
Oops, I guess then this issue can get closes

**Comment by Jojo-Schmitz** [comment]
There is another problem though: feeding invalid stuff as an argument to `rewind()` seems to be getting ignored entirely (and seem to result in `0` resp. `Cursor.SCORE_START` being taken).
