### ISSUE TITLE
MuseHub compromised/used as backdoor vector

### ISSUE THREAD

**Issue by GeneralProtectionFault** [musescore/MuseScore#22506]
### Issue type

Other type of issue

### Bug description

MuseHub is frequently the source of inbound connection attempts from various IPs.

### Steps to reproduce

Install MuseHub/content, install Malwarebytes--RTP (real-time) protection active.  There is usually a detection within a couple days.
Attaching Malwarebytes logs with 3 examples of inbound connection attempts from the MuseHub application.
[MuseHub_InboundBlocked.zip](https://github.com/musescore/MuseScore/files/15050011/MuseHub_InboundBlocked.zip)

### MuseScore Version

MuseHub 1.0.2.800

### Regression

I don't know

### Operating system

Windows 10

### Additional context

Obviously there is web traffic occurring from MuseHub, but the program should not be making attempts to connect to user's computers without consent.

**Comment by jeetee** [comment]
Muse Hub uses p2p traffic to download it's sound updates..

**Comment by Jojo-Schmitz** [comment]
a) Disable the Community Acceleration in MuseHub's options, then at least foreign IPs won't contact you. And yers, this should really be disabled by default, and/or being asked for on initial install.
b) I believe you'd need to bring that up with the MuseHub team at https://musehub.zendesk.com/
c) This isn't new at all and had been brought numerous times, so far to no avial though :-(

**Comment by cbjeukendrup** [comment]
This title seems clickbait, because there is quite a big difference between accepting incoming connections and being "compromised/used as a backdoor vector".

Anyway, as said, this doesn't belong here but on https://musehub.zendesk.com/. If Muse Hub engineers don't respond there, they will even less likely respond here.

**Comment by GeneralProtectionFault** [comment]
Clickbait?  To what end, so that I can make money through my popular Github posts?  I will concede that I'm certainly no cybersecurity expert, but the idea that I opened this to "get attention" is asinine.

I get that Malwarebytes might throw some false positives, but getting connections from the US, Belize, etc... is not "just" incoming connections. 

What @Jojo-Schmitz said is precisely the point (and thank you for pointing out the option to disable).  So, agreed, it's not necessarily compromised, I suppose I ought to have said "potential" compromise, but it definitely shouldn't be allowing traffic to anyone else who has MuseHub without my consent.

Anyway, I was not aware of the other site where I could report a MuseHub-specific issue, so I will check that out.

**Comment by cbjeukendrup** [comment]
Sorry for being too mistrusting towards you. Unfortunately it happens often that people use untrue overly dramatic statements to draw attention towards themselves or to harm the reputation of others. 

I'm happy to hear that things have now been clarified, both w.r.t. what this traffic is and about the Muse Hub website. (Perhaps, after explaining this again and again to other users, I had assumed too quickly that this would be known to you too….)
