### ISSUE TITLE
Some notes inconsistently ignored by playback during repetitions

### ISSUE THREAD

**Issue by akberg** [musescore/MuseScore#22516]
### Issue type

General playback bug

### Bug description

Notes are sometimes ignored in playback, seemingly at random, and usually in relation to a repetition. I'm attaching a specific example of this bug occuring.

### Steps to reproduce

1. From samples.zip, open the main.mscz. 
4. Copy some or the entire 1st house measure (16) from a wind part to the rotary organ.
6. Play score, notice that the first measure is muted in the second repetition.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

### Additional context

[samples.zip](https://github.com/musescore/MuseScore/files/15059521/samples.zip)

**Comment by zacjansheski** [comment]
To the best of my understanding, this is fixed in
https://github.com/musescore/MuseScore/pull/22522
@akberg might help to check in that build
