### ISSUE TITLE
Some group mix-ups in Mixer>MuseSounds 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#22530]
### Issue type

UI bug (incorrect info or interface appearance)

### Steps to reproduce

![Untitled](https://github.com/musescore/MuseScore/assets/90187801/f94de972-8052-4bac-bcd5-f20ac6cbfb05)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/cef44185-445c-4a75-9ad9-ae6b9507791e

### MuseScore Version

4.3

### Regression

Yes, this used to work in **MuseScore 4.2.1**

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
Fixed in the latest Muse Sound updates
