### ISSUE TITLE
MS 4.2 crashes with Muse Sampler 0.6.0 when entering notes

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#22543]
### Issue type

Crash or freeze

### Bug description

MuseScore 4.2 (current stable version) crashes with Muse Sampler 0.6 from Muse Hub Beta. The crash occurs when entering a note or clicking on an existing note. Playback works fine on scores that already contain notes.

### Steps to reproduce

Enter a note or click on an existing note.

### MuseScore Version

MuseScore 4.2.1 (current stable release)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11 & macOS

### Additional context

**Workaround:** Turn off _Preferences > Note input > Play notes when editing_.

**Comment by RomanPudashkin** [comment]
Yes, this has been fixed in 0.6.1

**Comment by RomanPudashkin** [comment]
> Confirmed on Windows 11. Has anyone tried macOS?

Yes, I've tried on macOS - no crash
