### ISSUE TITLE
[Sound Flag] "nonvib" string is not translatable

### ISSUE THREAD

**Issue by JLWALTENER** [musescore/MuseScore#22553]
### Issue type

Other type of issue

### Bug description

 In Sound Flag Property, 'nonvib' is not translatable.

### Steps to reproduce

Add a Sound Flag staff text to a stave.
Open the Sound flag property.
The nonvib string is not translated, an is not present on Transifex.

### Screenshots/Screen recordings

![SoundFlag Nonvib](https://github.com/musescore/MuseScore/assets/28805324/fe092507-f1aa-4841-91b9-aa6324ec1cd8)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241101557, revision: github-musescore-musescore-49f06da

### Regression

No.

### Operating system

Windows 11

**Comment by cbjeukendrup** [comment]
As far as I know, these strings except "Ord. (default)" are dynamically loaded at runtime from Muse Sounds (MuseSampler). So there is no way to predict in advance which strings will occur. (The user can namely theoretically have infinitely many Muse Sounds sound packs installed which may contain infinitely many sound flag options.)

So, these strings can be anything and aren't known in advance, and thus can't be sent to Transifex, at least not from our side. I think it's primarily up to the Muse Sounds team to come up with an idea for how to still make these strings translatable.

**Comment by Jojo-Schmitz** [comment]
Or at least make them reasonably understandable, line in thise case maybe "non-vibrato" (if that is the real meaning)

**Comment by bkunda** [comment]
I'll have a chat with the Muse Sounds team about this one. Meanwhile I believe @cbjeukendrup is right – this isn't something we can fix on the MS Studio side because the articulation text is being dynamically loaded via the sampler.
