### ISSUE TITLE
Ability to add custom Templates

### ISSUE THREAD

**Issue by heisluft** [musescore/MuseScore#22555]
### Your idea

Would it  be possible to create and use custom templates within the "New score" wizard? 

### Problem to be solved

For example, I'd like to add a template for choir + orchestra or Orchestras whose staff count lies between that of the Classical orchestra and Symphony orchestra. 
I also tend to rename the instruments to their italian names, which is just my personal preference, but I know other people might not like this as much. Allowing to create templates with different naming or even ordering would solve this issue in an elegant manner.

### Prior art

I only ever really used MuseScore so I don't know whether this has been done before.
I feel that the capabilities already exist but are just not accessible via a wizard:
- We can already rename Instruments from within the score
- We can already reorder them when in the "choose instruments" submenu
- The orchestra templates already rename the Violins from "Violins (section)" to "Violins I" and "Violins II"
### Additional context

This is really more of a QOL improvement than anything else, but it'd be a nice to have

**Comment by XiaoMigros** [comment]
[You already can](https://musescore.org/en/handbook/4/templates-and-styles#saving-template)
