### ISSUE TITLE
"Helicon" doesn't have an abbreviated short instrument name

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#22562]
### Issue type

Other type of issue

### Steps to reproduce

Add Helicon to a score and check...

### MuseScore Version

any

### Regression

No.

### Operating system

any

**Comment by shoogle** [comment]
@oktophonie, do you have a preferred short name for the Helicon? 'Hel.' perhaps?

**Comment by oktophonie** [comment]
sounds perfectly delicious to me!

**Comment by Jojo-Schmitz** [comment]
Fixed in the en_US and en_GB translations for now
