### ISSUE TITLE
Adding rehearsal marks and system text on multiple staves

### ISSUE THREAD

**Issue by Christof1981** [musescore/MuseScore#22578]
### Your idea

I suggest adding a tick box under **Stave/Part properties > Advanced style properties** that gives the option to show/hide system text.

### Problem to be solved

While MuseScore 4 makes the rehearsal marks and system text automatically appear above the strings or piano in certain templates, the issue is that there doesn't seem to be any way around this—of adding system text if it's not there by default (for example, if you build a score using individual instruments rather than a template), or doing away with it if you don't want it there (it can be hidden, but that's not quite the same thing). This would make the rehearsal marks and system text fully customisable.

**Comment by oktophonie** [comment]
This is coming! Most of the infrastructure is there, we just still haven't built the UI yet (though there is a design for it already).

**Comment by wizofaus** [comment]
@oktophonie Having just figured out how to get this working by editing the mscx file, and having previously offered to help with this, I'm happy to put my hand up if there's anything area in particular that needs work, though admittedly I'm not super keen on QML-based UI changes.

One thing I can see being potentially a challenge is that the current mechanism only seems to apply to newly added tempo markings in a score that has the right SystemObjects settings in the template.  But obviously some of us will have existing scores where we either accepted it was too hard to show tempo markings etc. on other staves, or used various hacks that'd prefer to avoid, so if there were a simple way to take an existing Tempo Marking (or other system text item) and choose which other staves it should be shown on that'd be handy.

**Comment by oktophonie** [comment]
Thanks, but this is all in hand.
I'll close this feature request as it's now supplanted by this task for 4.5: https://github.com/musescore/MuseScore/issues/24100.
