### ISSUE TITLE
nonuplet - nontuplet

### ISSUE THREAD

**Issue by orkuun** [musescore/MuseScore#22586]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

Something caught my attention on trasifex... While lines 1406 and 2081 say "nonuplet", line 1733 says "nontuplet". Friends on discord said that the correct one should be "nonuplet".

https://discord.com/channels/818804595450445834/818852942882275379/1233122892665851984

### Steps to reproduce

Menu / Add / Tuplets / Nontuplet

### MuseScore Version

4.3 Beta, 4.2.1

### Regression

I don't know

### Operating system

Linux Mint 21.3, Win10

**Comment by Jojo-Schmitz** [comment]
The actual sting to fix is "&Nontuplet"

**Comment by Jojo-Schmitz** [comment]
See #22588 and #22589

**Comment by Jojo-Schmitz** [comment]
Meanwhile I'll fix it in the en_US and en_GB translations
