### ISSUE TITLE
Glissando Lines Occasionally Disappear Across Page Breaks

### ISSUE THREAD

**Issue by CoolSpy3** [musescore/MuseScore#22585]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Occasionally, when editing a score, glissando lines will randomly disappear (IIRC, I've only noticed this occurring across page breaks, but I could be wrong). This occurs after editing seemingly unrelated parts of the score.

Possibly related to #21441 .

### Steps to reproduce

Sorry I couldn't provide a more minimal case, I've seen this bug pop up a few times, but this is the only time I've been able to reproduce it.

1. Open the attached score file
2. Delete any note in measure 116 or 117
3. Notice that the glissando between measures 119 and 120 disappears on page 34 (but not page 35).

To resolve:
1. Select the dotted half note in measure 119
2. Change its pitch either up or down with the arrow keys
3. Change its pitch back
4. Notice that the glissando reappears

### MuseScore Version

(64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 10

### Additional context

Relevant score file:
[Santa Barbara Skies.zip](https://github.com/musescore/MuseScore/files/15124143/Santa.Barbara.Skies.zip)

**Comment by wizofaus** [comment]
Yes, definitely observed this quite a lot and attached a score with instructions on how to make it happen in the comments of https://github.com/musescore/MuseScore/issues/21441
