### ISSUE TITLE
All pedal lines start with `Ped.`

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#22591]
### Issue type

UI bug (incorrect info or interface appearance)

### Steps to reproduce

Just open the Keyboard palette.

The Ped. doesn't get added to the score though (except for the 1st and 2nd palette entry)

### Screenshots/Screen recordings

![Screenshot 2024-04-26 102714](https://github.com/musescore/MuseScore/assets/1786669/e615b218-fa65-4c37-a24e-4616518388a8)

### MuseScore Version

4.3.0-Beta PortableApp

### Regression

Yes, this used to work in  **MuseScore 4.1.1**

### Operating system

Windows 11

### Additional context

May **need a factory reset to reproduce**, esp. when not using the PortableApp.

**Comment by bkunda** [comment]
@mike-spa I imagine we'd need to force-reset this palette. Could you look into this please?

**Comment by Jojo-Schmitz** [comment]
Proably the same with #22590

**Comment by miiizen** [comment]
I've definitely come across this, but can't recreate it right now.  Would you be able to save and attach the keyboard palette? Thanks @Jojo-Schmitz

**Comment by Jojo-Schmitz** [comment]
[Tasteninstrument.zip](https://github.com/musescore/MuseScore/files/15148686/Tasteninstrument.zip)
Here we go

**Comment by Jojo-Schmitz** [comment]
Will check.

You may need to revert to factory settings, esp. when not using the PortableApp

**Comment by miiizen** [comment]
Ok, second attempt is up

**Comment by Jojo-Schmitz** [comment]
Works, but only after a factory reset

**Comment by Jojo-Schmitz** [comment]
Your lates version seems to fix it completly

**Comment by Jojo-Schmitz** [comment]
I wonder whether #20766 is related too?
