### ISSUE TITLE
Chord symbols on fret diagrams are not exported to MusicXML

### ISSUE THREAD

**Issue by jugo6** [musescore/MuseScore#22592]
When I try to export a score to xml or mxl, plain chords are transmitted, but chords with fretboards disappear. I tried to select all similar chords (without fretboard), copy and paste (to have a line with just chords), but it pastes only one by one (other issue actually).
[chord export test.zip](https://github.com/musescore/MuseScore/files/15128056/chord.export.test.zip)
![image](https://github.com/musescore/MuseScore/assets/67692783/d8be9270-2b71-4968-88e6-b318de99e304)
![image](https://github.com/musescore/MuseScore/assets/67692783/69cc3217-f650-494f-809a-1b9050e1037c)

**Comment by Jojo-Schmitz** [comment]
In the original example at https://musescore.org/en/node/334422#comment-1238698, in one case it even worked for the fretboard diagram, in a case where there were 2 chord symbols at.
![Screenshot 2024-04-25 154630](https://github.com/musescore/MuseScore/assets/1786669/37cf36bf-fa73-4c9c-8167-e3330e08410c)

**Comment by Jojo-Schmitz** [comment]
See also #16902

**Comment by Jojo-Schmitz** [comment]
Actually a Mu3 regression
