### ISSUE TITLE
Voice notes unevenly spaced when offset is applied

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#22596]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Look at the attached example:

![offsets](https://github.com/musescore/MuseScore/assets/87246583/91ca9866-3d76-45c7-a362-e504e1efac21)

The chords in voice 4 have been offset to prevent them colliding with notes in other voices. However this has had the effect of creating an irregular space in front of the next notes.

It would be good if the algorithm could automatically respace the notes so that they are evenly apart again.

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

No.

### Operating system

OS: Linux Mint 20.1, Arch.: x86_64,

**Comment by oktophonie** [comment]
The current behaviour is exactly as intended; the 16th note segments start as equally spaced, but then various things cause items to graphically extend left and right of those equal, 'ideal' segments (accidentals, offsets, etc), at which point extra space is only created by padding settings, i.e. to keep a minimum distance between items and prevent them from colliding.

Creating extra space to make things look more unequal might be desirable in some cases, but done universally would be a bad idea - it results in wasted horizontal space (a bad idea when you want to conserve space more often than not) and, while it might look optically nice at first glance, it is ultimately causing even _more_ distortion of the equal spacing when you consider the segments in their entirety. Therefore, this should be left to the user to adjust manually only in cases where they may particularly want it.
