### ISSUE TITLE
Line component of TextLines ignores Text alignment

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#22601]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

The line component of TextLine based elements (cresc. lines, ottavas, pedals, etc.) ignores the horizontal alignment of the text when calculating its length. This can lead to an ugly gap.

**Left-aligned (correct)**
![image](https://github.com/musescore/MuseScore/assets/116587995/969aad7a-6d04-425e-9edf-112b6e3d882e)

**Center-aligned**
![image](https://github.com/musescore/MuseScore/assets/116587995/532b3074-689c-4503-90bd-9e69c8e690e2)

**Right-aligned**
![image](https://github.com/musescore/MuseScore/assets/116587995/782fc4bb-dcbe-4a96-ba88-1bb4597dc4e0)

### Steps to reproduce

1. Add a cresc. line to the score
2. Change the text alignment of the begin text

### MuseScore Version

master

### Regression

No.

### Operating system

Windows 10

**Comment by worldwideweary** [comment]
P.S., if you don't mind, how can a user of Mu4 get the offset of the text like this with these changes? I'd imagine there's a way, but I'm not familiar much with the differences. A quick test and i couldn't figure it out with the text-style options. Originally in 3, 1) Right alignment + 2) a Y-offset  within inspector would allow for this (or at the end of a text etc). 

![image](https://github.com/musescore/MuseScore/assets/7139517/70a1beb4-537a-4448-9e76-fbd072b96928)

Using "Placement" to not be auto but rather "above" or whatever would allow for the text to be detached from the line positioning

**Comment by XiaoMigros** [comment]
Hi, this can currently still be achieved using x- and y-offset in properties. the 'placement' option would work as well but is not exposed in properties at the moment

**Comment by worldwideweary** [comment]
Gotcha. Thanks for the response. For some reason I was thinking at the time of the question that the x-offset would be score-wide or would be overwritten by the alignment.
