### ISSUE TITLE
MS Ver 4.4 plug-in compatibility

### ISSUE THREAD

**Issue by TeeDeeY** [musescore/MuseScore#22606]
### Your idea

Change version 4.4 plugin use of “title” so some plug-ins can be compatible from 3.6 to 4.4+.    Possibly create a default title like done in version 4.2 if no title is given.  Then, ask plug-in writers to not use title and allow musescore to always assign it.  Also, allow menuPath in future MS versions, even if you ignore it. 

### Problem to be solved

Leaving off “title:” in MS 4.4 causes problems (loading and plugin menu listing).  In 3.6, using “title:” can keep a plug-in from loading.  3.6 requires menuPath. 

I thought MS 4.4 had a problem with menuPath but it seems fine while using a currently nightly.  I need to recheck.  MS 4.2 complains but worked with it.  

I tried using Component.onCompleted to assign title, but couldn’t get it to properly assign title in MS 4.4 but that could be due to my incorrect usage.  There is a component load method that may work but I wanted to start this suggestion and maybe a solution already exists.  

### Additional context

It would be nice if a simple plugin could work across all the versions.  I am almost there but the MS 4.4 title requirement keeps compatibility from happening.  MS 3.6 hates title declarations.

**Comment by TeeDeeY** [comment]
MS 4.4 and 4.2 have different assignment styles for title.  It seemed that one type would not work for both.

  Component.onCompleted: {
        if (mscoreMajorVersion >= 4) {
          if (mscoreMinorVersion >= 4) {
            title: "TITLE_HELLO"
          } else {
            title=qsTr("TITLE-HELLO");
          }
       } else {   
       }

  }

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.org/en/node/337468#Tips-for-adapting-plugins-for-4.x
