### ISSUE TITLE
Screen goes blank after tooltip disappears from top menu

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#22641]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The screen goes blank after hovering over a button on the top menu, seeing info dialogue, then moving mouse to remove info dialogue.

### Steps to reproduce

1. Create a score
2. Hover mouse over item in top menu, like "Voice 2". The info dialogue should appear
3. Move mouse again and info dialogue disappears, as well as the entire score
4. Score does not reappear until doing something like zoom in.

Also happens in palettes, anything with that little dialogue box with pointer.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/3953ca73-e6ea-4399-8403-e9bdb4ccb925

### MuseScore Version

OS: macOS 14.4, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241211748, revision: github-musescore-musescore-f2bf2bd

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 14

**Comment by mathesoncalum** [comment]
I'm getting this issue all over the place - e.g. while saving

**Comment by mathesoncalum** [comment]
Looks to have been introduced with [this commit](https://github.com/musescore/MuseScore/commit/09200b3cc1d3f8e6b930b9616284f912a22f76f2) (FYI @cbjeukendrup @Eism)

**Comment by zacjansheski** [comment]
There are various "flashing" instances of this.

Clicking out of mixer settings menu then clicking on score, selecting and deselecting boxes

Please let me know if I need to log this separately 

https://github.com/musescore/MuseScore/assets/69917893/8ca54b06-c04d-4011-83b6-44401761d6e9

**Comment by bkunda** [comment]
According to @zacjansheski this still occurs in master, so we're keeping this open for now. @cbjeukendrup FYI.
