### ISSUE TITLE
"Tubular bells" missing from Select Instrument dialog 

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#22642]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The instrument apparently known as "Chimes" in the US is, as far as I'm aware, known as "tubular bells" almost everywhere else in the English speaking world.  The translation for EN (GB) should then surely be "Tubular bells" (or "Tubular bells/chimes").

### Steps to reproduce

1. Ensure language is EN (GB).
2. Add a change instrument indication to any score
3. In the Instrument search box type "tubular bells" (or anything similar), nothing shows up
4. Type "chime" and select that, and confirm that the chosen instrument sounds exactly like tubular bells!

### MuseScore Version

4.2

### Regression

I don't know

### Operating system

Windows 11

**Comment by Fristover** [comment]
Same thing happens with spanish, they're called "Campanillas" (Little Bells, huh) instead of "Campanas Tubulares" (Tubular Bells) which is the term most spanish speakers use (at least from what I know, I still haven't found anyone calling them Campanillas)...

**Comment by Jojo-Schmitz** [comment]
Fixed for en_GB and es, for 4.3.0 and later

**Comment by wizofaus** [comment]
This can be closed, it appears to already fixed!
