### ISSUE TITLE
Replace Instrument button in instrument panel does not work

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#22640]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

Replace Instrument button in instrument panel does not work

### Steps to reproduce

1. Go to instrument panel
2. Select the cog wheel next to an instrument
3. Select "Replace Instrument"
4. Select Instrument window should appear.  Nothing happens

### MuseScore Version

OS: macOS 14.4, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241211748, revision: github-musescore-musescore-f2bf2bd

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 14

**Comment by bkunda** [comment]
Same status as #22641
