### ISSUE TITLE
Bad dB balance for Viola (solo) in pianissimo dynamic

### ISSUE THREAD

**Issue by tenshimoya** [musescore/MuseScore#22655]
### Issue type

Muse Sounds bug

### Bug description

Solo viola is often troublesome in playback, being extremely quiet in the lower dynamics, compared to all the other string instruments, which makes the playback levels unbalanced. Tried changing levels in the mixer, but would later get too loud in the louder dynamics. 
My only fix at the moment is to change the dynamics of quiet viola parts to something like _mf_ (where it actually starts to be noticeable) only for playback, and then change it back when I need to produce a final score. Another fix has been to change the playback instrument in the mixer to Viola**s** but it isn't the sound I'm going for if I'm writing for string quartet, and it's also very unbalanced levels-wise, being louder than the solo strings. 

### Steps to reproduce

1. Set instruments to Violin I (solo), Violin II (solo), Viola (solo), and Violoncello (solo) [a classic string quartet]
2. Write a chord spread in between the instruments and set all the dynamics to _pp_
3. During playback, the viola is almost indiscernible. It is a good 20-30 dB behind the rest of the strings.
4. Problem is even worse with sul pont., as well as tremolo. 

### MuseScore Version

MuseScore (64-bit): 4.2.1-240230937

### Regression

I don't know

### Operating system

Windows 11

### Additional context

https://github.com/musescore/MuseScore/assets/168729846/42d15e5e-2db1-4bd3-ba3c-f6cc2c416052

On this demonstration, you can see the issue at play

**Comment by DaddyLudwig** [comment]
For what it's worth, I find setting the Viola to +8 dB and the Cello to +3.3 dB sufficient to balance out both the quiet and loud dynamics for the most part, at least in a transcribing classical music context. If any of the string instruments get too quiet for me to hear them well in a passage marked pp or p after this mixer adjustment(especially if it's in one of the violins where mixer adjustment for p would imbalance f or it's in the high tenor register of the cello), I add an invisible mp mark and that works. 

That's just been my experience though.

**Comment by sampleeditor** [comment]
Resolved with Muse Strings 0.4.20 update
