### ISSUE TITLE
Mu4.3's style files report wrong version

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#22652]
### Issue type

Other type of issue

### Steps to reproduce

Open/create a score
Save a style
Open the style file with an editor

2nd line reads
```xml
<museScore version="4.20">
```
but should read
```xml
<museScore version="4.30">
```
same as in the score file itself

### MuseScore Version

4.3.0 Beta/RC

### Regression

No.

### Operating system

Windows 11

**Comment by Jojo-Schmitz** [comment]
At first glance looks like a rather minor issue, but IMHO is not and should get fixed before release

**Comment by Jojo-Schmitz** [comment]
Hmm, see,s the score version hasn't been updated either?
There are differences, added style tags, though:
* hideTabClefAfterFirst
* tabShowTiedFret
* tabParenthesizeTiedFret
* parenthesizeTiedFretIfArticulation

**Comment by Jojo-Schmitz** [comment]
Would a new defaults version be needed too?

**Comment by Jojo-Schmitz** [comment]
Also 4.3 changes the handling of tremolos, like added the tag<xml><TremoloSingleChord></xml>

**Comment by Jojo-Schmitz** [comment]
See #22658

**Comment by cbjeukendrup** [comment]
> Also 4.3 changes the handling of tremolos, like it added the tag `<TremoloSingleChord>`

That should only be the case in 4.4/master. Is there anything that indicates otherwise?

**Comment by Jojo-Schmitz** [comment]
You're right, I must have misinterpreted something
