### ISSUE TITLE
Crash when selecting whole bar (on viola)

### ISSUE THREAD

**Issue by NowaNowa-2** [musescore/MuseScore#22715]
### Issue type

Crash or freeze

### Bug description

A bug which occurd shortly after updating to 4.3, MuseScore crashes when selecting a whole bar that isn't exactly Bar 1. 

### Steps to reproduce

1. Input notes into the violas stave on bar 2, for me this occurred only on violas for some reason and bar 2 is where it crashed for me.
2. Attempt to select all notes by clicking on the bar.
3. Crash.

- - - - - - - - - - - - - - - - - - - - - - - - -

#### Easy steps:

1. On Windows with MuseSounds installed, open 
[crash testing.zip](https://github.com/musescore/MuseScore/files/15250481/crash.testing.zip)
2. Select bar 2 on Violas stave

also [see comment](https://github.com/musescore/MuseScore/issues/22715#issuecomment-2107117026) 

### Screenshots/Screen recordings

https://drive.google.com/file/d/1NDZ6lG-PGzAabNH6IvBSwLZ4KiRHOL-z/view?usp=sharing

I had to upload the recorded video to google drive.

### MuseScore Version

4.3

### Regression

I don't know

### Operating system

Windows 10

### Additional context

[crash testing.zip](https://github.com/musescore/MuseScore/files/15250481/crash.testing.zip)
[MuseScore diagnostics.zip](https://github.com/musescore/MuseScore/files/15250483/MuseScore.diagnostics.zip)

**Comment by bkunda** [comment]
Thanks for raising this @NowaNowa-2. 
We're most likely going to need some more information to help debug this one. Could you please upload the score to the issue description above (you'll need to compress it to a .zip file to do this). 
I also suspect the diagnostic files might be helpful (you get these by going to the "Diagnostic" menu and selecting "Save diagnostic files". 
Then one of our devs can look into it further.
Thanks!

**Comment by NowaNowa-2** [comment]
Hello! Thank you for responding! Yes I can do that, here are both the Diagnostic files and the score. Apologies because it's my first time reporting issues.
[crash testing.zip](https://github.com/musescore/MuseScore/files/15250418/crash.testing.zip)
[MuseScore diagnostics.zip](https://github.com/musescore/MuseScore/files/15250419/MuseScore.diagnostics.zip)

**Comment by DmitryArefiev** [comment]
This is interesting bug. I **can reproduce** from a scratch on **Windows** (not on Mac) with **MuseSounds only** with these steps:
1. Open Symphony orchestra template
2. In bar 2 on violas stave, add the same note as on video
3. Select that 2nd bar
4. Close and save score
5. Reopen score
6. Select that 2nd bar


https://github.com/musescore/MuseScore/assets/90187801/a93084a6-c3df-47aa-b74c-e6c77b785fa5



Crash occurs in **4.1.0** as well (with the same sampler version)

**Comment by DmitryArefiev** [comment]
Fixed on muse sampler side. 

Tested in 4.3 and 4.4 with musesampler **0.6.2.192** on Win10, Mac13.6, LinuxUbuntu22.04 - **FIXED**  

Closing

**Comment by DmitryArefiev** [comment]
@NowaNowa-2 You will get the fix together with muse sampler update to version **0.6.2** via MuseHub

**Comment by NowaNowa-2** [comment]
Attempted to update Muse Hub by reinstalling it and Muse Sampler is now being redundant -_-

**Comment by DmitryArefiev** [comment]
@NowaNowa-2 Unfortunately, I'll not get **v0.6.2** now. It's not released yet. But I should not have "not installed" as well.

Try to check updates in MuseHub:

https://github.com/musescore/MuseScore/assets/90187801/5c995b1a-4965-48a3-b837-b32ced0c58d2
