### ISSUE TITLE
Bring the piano roll editor back

### ISSUE THREAD

**Issue by justmeh** [musescore/MuseScore#22717]
### Your idea

Remember in Musescore 3 where you could right click and you have the option to edit the notes in a piano roll like a DAW? It's pretty useful, especially for workflow reasons. I tried looking for it in Musescore 4 and it doesn't exist. So I was hoping that if I "feature request" that feature here. It would be brought back, and hopefully I'm right. To improve the piano roll, you could give it a more modern UI with more convenient controls, without having to use as many keyboard shortcuts. But that's pretty much it.

### Problem to be solved

It would help beginners to understand note lengths and their notation, without jumping straight into notation. It would also give a better workflow for people that use DAWs quite often and have to use Musescore sometimes.

### Prior art

https://musescore.org/en/handbook/3/piano-roll-editor

**Comment by erinic04** [comment]
https://github.com/musescore/MuseScore/issues/20256

**Comment by erinic04** [comment]
There's a really good amount to read about in one of the links from that issue, I suggest you read through!
