### ISSUE TITLE
Sounds don't work

### ISSUE THREAD

**Issue by cajdk91** [musescore/MuseScore#22726]
### Issue type

Muse Sounds bug

### Bug description

I've downloaded the sounds I need, but some of them is not working..

In this screenshot both the Clarinet and the Viola is supposed to be playing, but no sound is coming out..

### Steps to reproduce

?

### Screenshots/Screen recordings

![Screenshot 2024-05-08 at 22 38 25](https://github.com/musescore/MuseScore/assets/169308981/0bf7d566-7218-4117-aa89-1d0330230be9)

### MuseScore Version

Version 4.3.0.241231433

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS latest

**Comment by MarcSabatella** [comment]
Please ZIP and attach the actual score and give precise steps to reproduce the problem, so others can investigate.
