### ISSUE TITLE
MS: Alto Flute with "nonvib" variant is transposed up one whole tone

### ISSUE THREAD

**Issue by majenkotech** [musescore/MuseScore#22720]
### Issue type

Muse Sounds bug

### Bug description

As per the title: using "nonvib" stave text on the Alto Flute sound transposes the whole sound up one semitone

### Steps to reproduce

Use Alto Flute on a stave. Add stave text. Switch to "nonvib".

### MuseScore Version

4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

No.

### Operating system

Windows 11

**Comment by bkunda** [comment]
@matthewreadbass this seems like one to look at with some urgency :-)

**Comment by bkunda** [comment]
Minimum example here: 

https://github.com/musescore/MuseScore/assets/86290556/43240747-3a3d-4958-9c96-e867b6c8b4da
