### ISSUE TITLE
Muse Sounds removes some sounds randomly.

### ISSUE THREAD

**Issue by Violoncellotenorclef** [musescore/MuseScore#22735]
### Issue type

Muse Sounds bug

### Steps to reproduce

None. It's random.

### MuseScore Version

4.3

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

**Comment by Violoncellotenorclef** [comment]
Sadly, Its apparently random to me. It deletes itself after 5 days - 2 weeks. I don't know how though,

**Comment by MarcSabatella** [comment]
More likely it’s that Muse Hub is trying to automatically update a sound in the background, but something goes wrong part way through the update (like your internet goes down) and leaves the sound unusable.

**Comment by Violoncellotenorclef** [comment]
> More likely it’s that Muse Hub is trying to automatically update a sound in the background, but something goes wrong part way through the update (like your internet goes down) and leaves the sound unusable.

I see. I'll delete this.
