### ISSUE TITLE
Break beam left does not affect the dotted rest

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#22732]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

The beam cannot be extended to a dotted rest. Instead, the dotted rest beam type automatically reverts to the "no beam" type.

### Steps to reproduce

1. Enter a dotted rest value of 1/8 or less.
2. After that, enter the notes with the same value.
3. Try to extend the beam to a dotted rest.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/134041121/0d3f59d0-34a4-464f-b411-39588b7c2fef

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

Yes, this used to work in MuseScore 4.2.1

### Operating system

Windows 11

**Comment by DaddyLudwig** [comment]
I also had an issue with beams and dotted note values, namely that breaking the beam between a pair of eighth notes and a dotted eighth in 2/2 is impossible without setting the second eighth to No Beam. I thought this beaming issue with dotted note values was time signature specific, but I guess it isn't.
