### ISSUE TITLE
soundflag for sax: growling

### ISSUE THREAD

**Issue by DominAbbus** [musescore/MuseScore#22742]
### Your idea

addition of a soundflag for the growling technique (basically what we do is humming into the horn.) This results in a raw, distorted sound. It's about as idiomatic for sax as overdrive is for rock guitar.

### Problem to be solved

it would allow for the rendering of 80's sax solo's.

**Comment by sampleeditor** [comment]
The saxes in Muse Woodwinds already have growls that show up in Extended techniques within Staff text.
