### ISSUE TITLE
TABLATURE staff without showing TAB clef crashes MuseScore at opening

### ISSUE THREAD

**Issue by cadiz2** [musescore/MuseScore#22759]
### Issue type

Crash or freeze

### Bug description

All is in the title

### Steps to reproduce

1. Create new score for Acoustic Guitar **(Tablature)** or Banjo **(Tablature)** no matter
2. Right-click the staff -> Staff/Part Properties -> Untick "Show Clef" -> OK
3. Save/Quit
4. Reload
Result: CRASH

### MuseScore Version

Version 4.3

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Additional context

- Same crash with the template Guitar + Tablature (but if both clefs, Treble clef et TAB clef, are hidden in Staff/Part Properties) Works at opening if the TAB clef is hidden and Treble clef showed.

- I know there have been changes with the TAB clefs for 4.3. 
Could the fix of this issue be involved? https://github.com/musescore/MuseScore/issues/20180

- Related post on forum: https://musescore.org/en/node/363885

**Comment by zacjansheski** [comment]
Confirmed regression of 4.2

**Comment by zacjansheski** [comment]
Diagnostic files:

[TabCrash.zip](https://github.com/musescore/MuseScore/files/15294868/TabCrash.zip)

**Comment by zacjansheski** [comment]
Reproduction score (if helpful)
[TabCrash.mscz.zip](https://github.com/musescore/MuseScore/files/15294871/TabCrash.mscz.zip)

**Comment by cbjeukendrup** [comment]
I'm about to open a PR

**Comment by cadiz2** [comment]
Thanks!
Could you please check that this patch also covers this use case (probably?) that has just appeared on the forum, here: https://musescore.org/en/node/364024

On the attached file (*BWV 527 Bc*), the TAB clef is not displayed, but the lower staff shows a bass clef. So it doesn't crash when you open the file. 
On the other hand, as the OP points out, it does crash when creating the parts, so
1. Open this file
2. Parts -> "Open all"
Result: crasch

**Comment by zacjansheski** [comment]
https://github.com/musescore/MuseScore/pull/22802 does resolve that issue as well!

**Comment by cadiz2** [comment]
Great. Thanks!
