### ISSUE TITLE
Musesounds not showing

### ISSUE THREAD

**Issue by det0ga** [musescore/MuseScore#22754]
### Issue type

Muse Sounds bug

### Bug description

I downloaded the new museScore version 4.3.0 directly from musescore.org (I have muse hub, but I've experienced problems with updating through muse Hub in the past). Now when I open museScore and open a project, it doesn't show me the option for muse sounds in the mixer. In muse Hub it shows me all the muse sounds correctly installed and I've even tried to redownload them (the Sounds are on an external drive but in Muse Hub everything is showing fine and both Muse Hub and MuseScore have Full disk access).

### Steps to reproduce

1. uninstall museScore 4.2.1
2. go to musescore.org
3. Download MuseScore Studio without Muse Hub
4. Install MuseScore Studio
5. Open Muse Hub
6. Open MuseScore Studio
7. Open the Mixer

### MuseScore Version

OS: macOS 14.4, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.4

**Comment by MarcSabatella** [comment]
Probably your Muse Sampler is missing or damaged.  What does Diagnostic / Muse Sampler / Check Muse Sampler report?  I'm guessing the custom install location is causing problems.

In general, better to ask on the support forum when you are having problems, so other experienced users can help diagnose what is going on, and then only post to GitHub if something is confirmed to be an actual bug rather than just a configuration problem on your system.

**Comment by det0ga** [comment]
Thanks for the reply, 
Yes, the muse sampler was missing. I tried to find where it belongs so I could copy it there, but seemingly couldn't. After uninstalling all the muse content (muse Hub, MuseScore... ) and downloading everything again it was fixed (but I had to download through musescore.org because downloading through muse Hub gave me trouble). 

Sorry if I posted this in the wrong place. I often get confused about what is Muse Hub and what is MuseScore and in which forum I should write what.

**Comment by MarcSabatella** [comment]
Glad it’s working!

As for where to post - in general, most of the time, unless you are absolutely sure something is a bug and you have precise steps to reproduce it and have checked that it isn’t reported already, the first place to go are the forums at MuseScore.org.  There people can help sort out if it’s an actual bug or not, and whether it’s been reported if so, and where to report it if it hasn’t been already.
