### ISSUE TITLE
Unable to delete instrument names from beginning of staves.

### ISSUE THREAD

**Issue by bleistift-zwei** [musescore/MuseScore#22758]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

One used to be able to delete the instrument names that appear before the staves. That is no longer possible.

### Steps to reproduce

1. Create a new score with at least 2 instruments.
2. Right-click one of the instrument names and select ‘Delete’ from the context menu.
Alternatively, select one of the instrument names and press ‘Del’.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/60063716/3d640d8c-76ec-4710-8c0a-af5d28911684

OBS didn’t record the context menu. The mouse movements you see are me right-clicking the instrument name and then clicking ‘delete’.

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10 Home N 22H2

### Additional context

This happens since the update to 4.3.0. I don’t know which version I ran before the update, but my guess is that it was 4.2.x.

A workaround is to remove the instrument names from the instrument properties, but that is suboptimal, since it also removes the names from the instruments panel (cf. #18289)

**Comment by MarcSabatella** [comment]
I can confirm it worked in 4.2,1 and is now broken in 4.3x

Better workaround is to double click the name to open Staff/Part properties, then edit the long/short names there.

**Comment by XiaoMigros** [comment]
Possibly intended behavior, see #22550 which resolves this issue through other means

**Comment by oktophonie** [comment]
#22550 is for 4.4 - there's no intended change in 4.3 as far as I know

**Comment by cadiz2** [comment]
One more: https://musescore.org/en/node/363968

**Comment by cbjeukendrup** [comment]
Caused by https://github.com/musescore/MuseScore/commit/b6088bc3713e7d89cf26137654cdf6254dbf909a
