### ISSUE TITLE
Crashes when the tab is closed

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#22761]
### Issue type

Crash or freeze

### Bug description

When you close the tab of the edited score, a crash occurs.

### Steps to reproduce

1. Launch MuseScore Studio
2. Open/create a score
3. Close the score.
4. MuseScore Studio will crash.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/134041121/03c6f49c-4229-4dce-8640-20a274fd7ee4

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

I don't know

### Operating system

Windows 11

### Additional context

In the previous version, this also happened, but rarely, and now all the time.

**Comment by Dima-S-Jr** [comment]
Please note that neither #13933 nor #17914 are related to this problem, since the crash works both with and without a Mixer.

**Comment by cbjeukendrup** [comment]
It may be helpful if you upload the "diagnostic files": Open MuseScore, Click "Diagnostic > "Save diagnostic files…", save it somewhere, and upload it here.

**Comment by Dima-S-Jr** [comment]
[for #22761.zip](https://github.com/musescore/MuseScore/files/15295592/for.22761.zip)

**Comment by Eism** [comment]
@Dima-S-Jr 
In the attached diagnostic file there is a crash dump, but it seems that it is not from 4.3 version. Make sure you are using the latest version of MuseScore, try to reproduce the crash and generate the diagnostic files again.
PS: I can't reproduce the crash on my machine

**Comment by Dima-S-Jr** [comment]
> @Dima-S-Jr In the attached diagnostic file there is a crash dump, but it seems that it is not from 4.3 version. Make sure you are using the latest version of MuseScore, try to reproduce the crash and generate the diagnostic files again. PS: I can't reproduce the crash on my machine

[crash.zip](https://github.com/musescore/MuseScore/files/15331575/crash.zip)

**Comment by Dima-S-Jr** [comment]
https://github.com/musescore/MuseScore/assets/134041121/9be8db9d-7bfc-428d-b20e-3f02af95987f
The crash is still happening exactly in version 4.3

**Comment by Dima-S-Jr** [comment]
https://github.com/musescore/MuseScore/assets/134041121/ec7302f3-c6a6-40d6-995e-6a921ca84214

**Comment by Eism** [comment]
It's strange that there are no logs in the diagnostic files, they would help a lot.
Please check C:\Users\<user name>\AppData\Local\MuseScore\MuseScore4\logs
If there are files with .log extensions, please send them all in archive (you can archive the whole logs folder and send)

**Comment by Dima-S-Jr** [comment]
> It's strange that there are no logs in the diagnostic files, they would help a lot. Please check C:\Users<user name>\AppData\Local\MuseScore\MuseScore4\logs If there are files with .log extensions, please send them all in archive (you can archive the whole logs folder and send)

Unfortunately, I did not find any files with the `.log` extension in the path you specified.

https://github.com/musescore/MuseScore/assets/134041121/b3f32c1b-b76f-4951-a4e8-f32109370885

I'm surprised that I'm the only one facing this problem. Maybe there is someone else with the same situation who will have these files?

**Comment by DmitryArefiev** [comment]
**Can't reproduce** on my side (4.3, Win11)

@zacjansheski Can you try it please?

**Comment by DmitryArefiev** [comment]
@Dima-S-Jr Can you check you Muse Sampler version please? (Top menu>Diagnostic>Muse Sampler>Check Muse Sampler)

**Comment by Dima-S-Jr** [comment]
> @Dima-S-Jr Can you check you Muse Sampler version please? (Top menu>Diagnostic>Muse Sampler>Check Muse Sampler)

![Снимок экрана (346)](https://github.com/musescore/MuseScore/assets/134041121/c3222054-97be-4047-bfe3-72ac7a1d68b1)
Version 0.6.1

**Comment by Dima-S-Jr** [comment]
Oh, a miracle! The crash stopped happening after the system was restarted. @macaquedev, you and I are namesakes😅 However, I did not get off with one restart. I had to reinstall MuseScore Studio a couple of times (and, accordingly, restart the system a couple more times). 
I'm closing this issue for now, if the problem shows up again, I'll open it again.
