### ISSUE TITLE
Muse Sounds Clarinet in Eb, incorrect (and Interesting) audio playback

### ISSUE THREAD

**Issue by C-Dorner** [musescore/MuseScore#22777]
### Issue type

Muse Sounds bug

### Bug description

I Was working on a project and noticed something odd with my playback. 

When the Eb Clarinet is slurring between concert F#5 to D#5, the D# does not sound and instead an audio sample can be heard of the player making a sound in disgust. This only happens at Piano (P) dynamics and below. 

### Steps to reproduce

1) Select Eb Clarinet, loading in MuseSounds Clarinet in Eb sound
2) write in Concert F#5 and D#5 and write a slur between the two notes
3) Set dynamic to piano (P) or less

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/169567943/d13987cf-9ada-4556-88e1-7d7d32941237

### MuseScore Version

4.3

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

This issue only occurs when using MuseSounds Clarinet in Eb soundfont and when the dynamic is at Piano (P) or less

**Comment by Valdessir** [comment]
"This" 😂

**Comment by DmitryArefiev** [comment]
Can reproduce in MS **4.1.1** as well (sampler 0.6.1, Win10)

**Comment by TobyTwo32** [comment]
Tested on the latest Muse Sampler Update 0.6.3.196 and Woodwinds Beta update. It seems its fixed. Can anyone reproduce?

**Comment by DmitryArefiev** [comment]
I still can reproduce with v.**0.6.3** installed from MuseHub regular (not beta) (4.3 on Windows10)

@iamtesch Muse sampler with the fix is only available on **MuseHub Beta**?

**Comment by DmitryArefiev** [comment]
Checked in **MSS4.3** with **MuseHub Beta** (latest updates) on Win10/Mac13.6. **FIXED**

Should be available soon in MuseHub updates

Closing
