### ISSUE TITLE
Allow copy and repeat commands to work with measures containg two-measure and four-measure repeat symbols

### ISSUE THREAD

**Issue by rgreen5** [musescore/MuseScore#22770]
### Your idea

Probably a minor thing, but I noticed that copy/repeat works with one-measure repeats but not with two-measure and four-measure repeats. Perhaps this facility could be added as well?

**Comment by MarcSabatella** [comment]
Thanks for posting, but this is a duplicate of https://github.com/musescore/MuseScore/issues/21634
