### ISSUE TITLE
Extra F-sharp heard on violas D-sharp to G-sharp transition

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#22783]
### Issue type

Muse Sounds bug

### Bug description

There is an extra F-sharp heard during the transition between D-sharp and G-sharp.

### Steps to reproduce

1. Create a new score with violas (section). Make sure Muse Sounds is activated.
2. To the first measure add a D-sharp 4 half note followed by a G-sharp 4 half note.
3. Hit play and hear the extra F-sharp 4 note during the transition between the D-sharp and the G-sharp.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/163907533/a7795fda-3001-4d4b-9311-d3100415c6fb

### MuseScore Version

4.3

### Regression

I don't know

### Operating system

macOS 12.7.2

### Additional context

This issue occurs in all dynamics. And all note lengths, as far as I can tell.
Not sure of the Muse Strings version number, but it was updated to the latest version as of May 12, 2024.

**Comment by sampleeditor** [comment]
Resolved with Muse Strings 0.4.15 (beta)
