### ISSUE TITLE
Notes of identical pitch but different length not playing back correctly while using Muse Sounds 

### ISSUE THREAD

**Issue by ndxw** [musescore/MuseScore#22781]
### Issue type

Muse Sounds bug

### Bug description

A note that occurs while a different note of identical pitch is still playing causes that note to not play. 

This does not happen to notes that are the same pitch but in a higher/lower octave. It also does not happen when using default sounds. Not sure if I described the issue thoroughly enough in words so it may be best to just watch the video included.

### Steps to reproduce

1. Create new piano score
2. Enable Muse Sounds
3. Place a middle C whole note in right hand
4. Place four middle C quarter notes in left hand
5. Press space to play

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90407174/f66a350f-0ac2-4c23-aa65-ab36e89ee4f4

### MuseScore Version

4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

No.

### Operating system

Windows 11

**Comment by MarcSabatella** [comment]
This is already fixed in 4.3, so just update (and also update Muse Sounds) and all should be well.
