### ISSUE TITLE
MS4 menus close too quickly

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#22780]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Navigating menus in MS4 is difficult due to menus closing too quickly after you leave them, causing inaccurate targeting of menu items if you don't move the mouse in a perfectly horizontal direction. Noticeable especially when choosing instruments or VSTs, etc. in the mixer, but applicable also to the “Add” menu in the Note Input toolbar, and possibly elsewhere.

### Steps to reproduce

1. Go to the mixer.
2. Go to Muse Sounds > Muse Keys.
3. Move your mouse on an angle downward to something near the bottom of the Muse Keys menu.
4. See error. The Muse Keys menu closes because your cursor for a brief millisecond accidentally passed into a different menu.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/163907533/b2544beb-e27e-49b8-9ddd-c35a664871db

### MuseScore Version

4.3

### Regression

No.

### Operating system

Every OS

### Additional context

When you move to a different menu there should be a delay of a few milliseconds before it closes the first menu (just enough so that it is sure that you actually meant to go to a different menu.)
For an example of proper behavior, see the upper menubar on macOS, as demonstrated in the attached screen recording. Windows 11 employs a similar strategy for system menus.
Also see the discussion on the forums for more details. https://musescore.org/en/node/363832

**Comment by cbjeukendrup** [comment]
Related to https://github.com/musescore/MuseScore/issues/15136
