### ISSUE TITLE
The Notehead group in a single-line percussion stave is reset.

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#22794]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

The Notehead group in a single-line percussion stave is reset to its original value when reactivated from _Muse Sounds_ to _MuseScore Basic_.

### Steps to reproduce

1. Add to the score any instrument that is notated on the same line. 
2. Make sure that the _Muse Sounds_ profile is activated
3. In the drumset settings, change the Notehead group to any other.
4. Activate the _MuseScore Basic_ profile
5. Save and close the scores. (note: after that, MuseScore Studio will crash)
6. Open this score again. 
7. You will see that the Notehead group has been reset to its original value.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/134041121/f2a029eb-116b-4873-9af3-e3a203d2ca37

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

Yes, this used to work in MuseScore 4.2.1

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
Although it is imperfect, it is currently by design that changing the instrument in the mixer resets the percussion noteheads to the defaults.  This is the only way to expose the full range of different sounds in new instruments selected in the mixer.

If you write notes after step 4, the noteheads will change.

You can undo the notehead changes.

**Comment by zacjansheski** [comment]
https://github.com/musescore/MuseScore/assets/69917893/91ff1c82-f5a6-4a45-b61d-d6a6b624f99d

**Comment by Dima-S-Jr** [comment]
>This is the only way to expose the full range of different sounds in new instruments selected in the mixer.

I don't quite understand what you mean.

**Comment by zacjansheski** [comment]
It will make more sense as more Muse Sounds capabilities are supported/available.

I believe the toms are a clear example.  Muse Sounds has 3 toms with rims.  MS Basic has 6 toms without rims.  These respective sounds can only be exposed clearly by resetting the "drumset"
