### ISSUE TITLE
Muted notes issue has worsened in 4.3

### ISSUE THREAD

**Issue by NicolaRulli** [musescore/MuseScore#22806]
### Issue type

General playback bug

### Bug description

There has been for a long time a bug that led to playback randomly permanently failing to perform large swaths of notes until the program was restarted. It now consistently takes just a handful of minutes for that to happen, requiring a restart (and to go through the slow sample loading, and the resetting of the timeline's zoom).
I'm picking regression due to the massively increased occurrence frequency

### Steps to reproduce

1. work on a score for a while, having a decent number of measures (20?) and instruments (6?)
2. begin playback from any point
You will hear that some notes are not played, and often even the entirety of the score past a certain point.

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

**Comment by RomanPudashkin** [comment]
@NicolaRulli could you try on this build? Is it any better?
https://github.com/musescore/MuseScore/actions/runs/9077279138/artifacts/1500574302

**Comment by NicolaRulli** [comment]
Will try and get back to you

**Comment by RomanPudashkin** [comment]
@NicolaRulli is it any better? :)

**Comment by bkunda** [comment]
Closing for now as we suspect this should be fixed by [this PR](https://github.com/musescore/MuseScore/pull/22522). 
We can reopen if the problem persists, however we will need more information in order to fully investigate the issue (Including the score file and clearer reproduction steps).
