### ISSUE TITLE
MuseScore crashes when using certain VST plugin (dearVR Micro)

### ISSUE THREAD

**Issue by SOSnake** [musescore/MuseScore#22826]
### Issue type

Crash or freeze

### Bug description

If I start a project and add dearVR Micro and start playback MuseScore crashes. When I start playback with the plugin off and then turn the plugin(s) on whilst the playback is running MuseScore doesn't crash and will not crash using the plugin for the rest of the session. When closing musescore and opening it back up this needs to be repeated.

1  instrument works fine. But when adding multiple instances (so more than one) the crashing occurs. This happens with BOTH MuseSounds and other VSTs/SoundFonts.

### Steps to reproduce

1. Open MuseScore.
2. Create a score with more than one instrument (2 is sufficient).
3. Add a couple notes if you want (optional).
4. Add the plugin dearVR Micro (download link (without needing to make an account and stuff, remove quotes from link): "https://archive.org/download/dearVR_MICRO").
5. Turn playback on. NOTE: This might work the first time, but when saving the project and fully restarting MuseScore when pressing play with multiple dearVR Micro instances this problem occurs and MuseScore crashes.

IF YOU WANT IT TO WORK:
6. Do all previous steps except step 5.
7. Start playback with the plugin disabled.
8. Whilst playback is on, start enabling the plugin on all tracks and now the plugin will work for the rest of the session.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/46374966/bdbfd6f1-d373-4b90-9dd5-d77110f0b2d2

### MuseScore Version

4.3

### Regression

I don't know

### Operating system

Windows 11

### Additional context

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74 _(copy pasted from "Help > About MuseScore Studio")_

**Comment by bkunda** [comment]
@SOSnake yesterday we merged a fix that _might_ fix this issue, but will need your help to see if it worked. 
Could you please re-test using the latest nightly? Many thanks!

**Comment by zacjansheski** [comment]
Closing, no response
