### ISSUE TITLE
French horn randomly starts playing fff at the beginning of a crescendo

### ISSUE THREAD

**Issue by macaquedev** [musescore/MuseScore#22828]
### Issue type

Muse Sounds bug

### Bug description

Well, it's in the title.... bar 15 of a file that I cannot attach because GitHub won't let me, but I can email it to whoever needs it if that's easier.
But at least I've got a screen recording.

### Steps to reproduce

Open the file, press play, wait until bar 15, then the horn randomly starts blaring at fff

### Screenshots/Screen recordings

 

https://github.com/musescore/MuseScore/assets/69220675/a8807974-38d8-47d6-8d3f-a760b5bf2414

### MuseScore Version

MuseScore Studio 4.3

### Regression

I don't know

### Operating system

Windows 11

### Additional context

MuseScore 4.3 (I think this kind of thing happened in 4.2 as well, earlier than that, I don't have a clue, sorry)

**Comment by Dima-S-Jr** [comment]
The problem, as it turned out, is much more serious. See #22862

**Comment by oktophonie** [comment]
@macaquedev To attach a file, put it into a .zip or just rename .mscz to .zip.

**Comment by macaquedev** [comment]
for some reason I opened this file again (this time MuseScore 4.3.2) and it doesn't do this anymore.... how odd!

**Comment by macaquedev** [comment]
blah, scratch that. the problem's back and worse than ever. 🤣

**Comment by MarcSabatella** [comment]
Then definitely ZIP and attach the actual score we people can examine it in order to begin investigating the problem.

**Comment by macaquedev** [comment]
[horn thing.zip](https://github.com/user-attachments/files/15844463/horn.thing.zip)
here, try this

**Comment by bkunda** [comment]
@macaquedev I'm going to suggest this might have been resolved, because I cannot reproduce it on my end. 

But I am running updated sampler and libraries, so it's also possible the fix might not yet be in production. 

Perhaps check it out again, but for now I'll mark this as resolved. If after 4.4 is released the problem continues to persist for you, then we can reopen it.
