### ISSUE TITLE
Violas (section) associated with certain notes and a tempo marking crashes the program at opening/or launching playback

### ISSUE THREAD

**Issue by cadiz2** [musescore/MuseScore#22830]
### Issue type

Crash or freeze

### Bug description

It's all summed up in the title. 

### Steps to reproduce

1. Create a three-measure score for **Violas** (section)
2. Write some notes and rhythms, the ones you can see on the GIF and in the attached .mscz test file: 
[Violas test.zip](https://github.com/musescore/MuseScore/files/15313681/Violas.test.zip),
 and not others apparently...
3. Save/close
4. Reopen: with no tempo marking, it doesn't crash (as in the attached GIF) when loading audio samples. On the other hand, if you add a tempo marking, and start playback, it crashes (as seen on the GIF). 

Alternatively (other scenario): if the tempo marking is already present on the score (as on the score attached to the OP on the forum - see link in "Additional context", 
or on the same minimal test file: [Violas test tempo.zip](https://github.com/musescore/MuseScore/files/15313909/Violas.test.tempo.zip),  the file shuts down at opening (more precisely: when audio samples are being loaded)

### Screenshots/Screen recordings

![Video violas tempo](https://github.com/musescore/MuseScore/assets/114975887/b4162d27-44a4-4060-b0fb-4b6acb13c75b)

### MuseScore Version

4.3

### Regression

I don't know

### Operating system

Windows 10

### Additional context

- Change instrument to **Viola** (solo) solves the issue. 

- I cannot reproduce eg with Cellos (section). And by changed the pitch of notes,  the problem seems to evaporate (and if I remove the third measure too...) In short, it's hard to pinpoint a precise trigger. It's a combination of certain things (certain notes, a tempo marking, and the Violas instrument) that trip up MuseScore. 

- Related post on forum : https://musescore.org/en/node/364053

**Comment by cadiz2** [comment]
And as the OP pointed out in his last message on the forum, with a tempo marking of 79 (for example), no crash. So, what happens? 
[tempo 79.zip](https://github.com/musescore/MuseScore/files/15324964/tempo.79.zip)
See:

**Comment by bkunda** [comment]
Just to clarify, is this only when using MuseSounds? Or Soundfont/VST too?

**Comment by cadiz2** [comment]
I was using Muse Sounds. Well, I'm confused, I can't reproduce right now.  I've just checked the Muse Sampler version, it's 0.6.3. From memory, I had version 0.6.1 when I downloaded version 4.3 several days ago. I don't know what version I had three days ago.  Perhaps an update to Muse Sampler solved the problem?

**Comment by DmitryArefiev** [comment]
> Perhaps an update to Muse Sampler solved the problem?

Yeah! We had some crashes related to Muse Sampler and they were fixed in with a new version (0.6.3)

Please reopen if happens again
