### ISSUE TITLE
Erratic Loop Player Behavior (BUG)

### ISSUE THREAD

**Issue by smokeadvisor** [musescore/MuseScore#22846]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

Hello,

I have transcribed a score in which, before playing the end, you have to make two complete turns and, in the third, replace the last 4 measures with the 4 that correspond to the end.
To do this, I have indicated the repetition and put the corresponding CODA indications so that, in the automatic playback it works as it should (two turns and in the third to CODA for the end).
However, when I try to play it with the loop player it works poorly (it repeats the first 4 bars in each lap and does not respect the CODA indication.
Conceptually it would be like in the old cassette players that if you pressed normal play it would play the content of the tape once, but you could also put it on a loop (not all players supported that function) with which the tape would play completely as many times as you wanted until you stopped the process.
I think it is a fairly clear bug, I attach the project file and the diagnostic files so that you can verify what I say and the BUG is corrected.
Thank you very much in advance for your patience,

### Steps to reproduce

Execute my attacehd project and try to loop playback for the entire score
[TOTPSY-Completo-V2.5.zip](https://github.com/musescore/MuseScore/files/15323693/TOTPSY-Completo-V2.5.zip)
Also attached my diagnostic files
[Diagnostico-Musescore-4.3_2024051401.zip](https://github.com/musescore/MuseScore/files/15323702/Diagnostico-Musescore-4.3_2024051401.zip)

### MuseScore Version

4.3

### Regression

No.

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
All seems to work as expected in 4.3.1

(I sped it up and dropped a repeat in the interest of time)

https://github.com/musescore/MuseScore/assets/69917893/54a6603d-05c3-4318-a697-23d0e208648a

**Comment by smokeadvisor** [comment]
Hi Zac,

Good evening. I see that it works on your Mac with MSC 4.3.1
I hope it works aswell on Windows 11 but seem Version 4.3.1 it's not relesased yet.
When do you think will be available that release?

Thanks

**Comment by zacjansheski** [comment]
Likely within the next week.  I will double check on Windows.
