### ISSUE TITLE
Allow users to add a zero-duration arrival note for a guitar bend

### ISSUE THREAD

**Issue by headboy2002** [musescore/MuseScore#22848]
### Your idea

My purpose is to make guitar bends in Musescore be more Guitar-Pro-like.
You can compare the following three:
![屏幕截图 2024-05-16 014652](https://github.com/musescore/MuseScore/assets/34545416/c0b83036-e8e8-4758-b7f7-f039d536ddef)
![屏幕截图 2024-05-16 014612](https://github.com/musescore/MuseScore/assets/34545416/0e09fd32-9f00-4a5f-b3de-4eaed5bb342a)
![屏幕截图 2024-05-16 013454](https://github.com/musescore/MuseScore/assets/34545416/b58cd158-779d-4dff-ac74-02b7d3afaebf)
The first two are created by Guitar Pro 8, and the last is created by Musescore 4.3. For Guitar Pro users, the way that Guitar Pro represents bending is more straightforward. I'm considering if Musescore can do the same.

### Problem to be solved

I think the problem is, "bends in MuseScore connect two notes together: a ‘starting note’ and an ‘arrival note’." If we let the duration of the starting note be the duration of the bend, then the duration of the arrival note is unnecessary. So can we allow users to add a zero-duration arrival note for a guitar bend?

### Prior art

It seems the way MuseScore handles guitar bends is the same as Dorico's and Finale's, etc. However, Guitar Pro handles it in a different but a better way. Since Guitar Pro is popular among guitarists, we can take it as a reference.

**Comment by rgreen5** [comment]
IMV, the notation method used by MS4 is better as it provides more musical information to the user.

Example 1 above (GP8), exact durations are not made explicit; the user interprets the bend using the shape as a visual guideline.
 
But MS4 is geared towrds the notation-reading musician, and in so doing it provides exact information about pitches and durations of notes. In fact, the same standards as would apply to any other musical instrument.

IME, the MuseScore approach is the one favoured by publishers.

Vive la difference!
