### ISSUE TITLE
Crash when Show clef is unchecked

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#22842]
### Issue type

Crash or freeze

### Bug description

Crash occurs when opening score which has Show clef option unchecked.
Initially reported [here](https://musescore.org/en/node/364088). Show clef is unchecked in parts, which causes crash on opening.
Crash will not occur if there is only one staff in the score
This is a regression from 4.2.1. It would be great to fix this in 4.3.1

### Steps to reproduce

1. Create score from treble clef template
2. Go to Staff/Part properties
3. Uncheck Show clef and click OK
4. Save score and close
5. Open score again

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/dbd9ba8b-a98a-42ae-9129-f139dd585cc4

### MuseScore Version

4.3.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 10

**Comment by cadiz2** [comment]
I guess it's the same issue (a duplicate) of: https://github.com/orgs/musescore/projects/46?pane=issue&itemId=62720015

**Comment by mercuree** [comment]
@cadiz2 Yes, Can't reproduce with 4.3.1 nightly. Probably duplicate and should be closed
