### ISSUE TITLE
Instrument written range

### ISSUE THREAD

**Issue by Magnus26** [musescore/MuseScore#22850]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The organ does not have the correct written range. It should be for the pedal C-f¹, and for the manuals C-g³, with an alternative C-g¹ and C-c⁴ respectively.

### Steps to reproduce

1. Open "Staff/Part properties" in an organ score.
2. Look at "Usable pitch range".

### MuseScore Version

4.3

### Regression

I don't know

### Operating system

Q4OS

**Comment by bkunda** [comment]
I'm not sure it's possible to specify a precise range for every conceivable size of organ. 
Closing for now unless it ends up being more of an issue.

**Comment by shoogle** [comment]
What we could do is find the range of notes that most organs can play (maybe the 66th percentile) and use this as the amateur range. Notes outside this range would be coloured orange to indicate that they are only playable on some organs.

Then we find the highest and lowest notes playable on any organ anywhere (or the 95th percentile) and use that as the professional range. Notes outside this range would be coloured red to indicate that they are not possible on any organ (or only on extremely rare organs).

**Comment by Magnus26** [comment]
> What we could do is find the range of notes that most organs can play (maybe the 66th percentile) and use this as the amateur range. Notes outside this range would be coloured orange to indicate that they are only playable on some organs.

Yes, I have already given the most common range (that could be labeled "amateur range" although it has no direct connection to amateur organists or amateur organs), and the range found on often very large instruments in many concert halls.

> Then we find the highest and lowest notes playable on any organ anywhere (or the 95th percentile) and use that as the professional range. Notes outside this range would be coloured red to indicate that they are not possible on any organ (or only on extremely rare organs).

The highest and lowest tones sounding in an organ depends on the stops used in the instrument, but the ranges when inputting notes in a notation program are only about the ranges of the keyboards, including the pedal keyboard. The notation program Igor Engraver uses the ranges C-f¹ and C-g³.

**Comment by Magnus26** [comment]
> The notation program Igor Engraver uses the ranges C-f¹ and C-g³.

What ranges are used in Dorico, Sibelius and Finale?
