### ISSUE TITLE
Lute tablature crashes MuseScore

### ISSUE THREAD

**Issue by Wim4rk** [musescore/MuseScore#22861]
### Issue type

Crash or freeze

### Bug description

When setting up a new score with a lute tablature the program crashes.

### Steps to reproduce

1. Create a new score using the guide
2. Choose **lute (tablature)** in the instruments list
3. Press next
4. Press done
5. Program crashes

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/ec02b964-9fbe-4252-8a44-6d6c284bd5be

### MuseScore Version

4.3

### Regression

Yes, worked in **MuseScore 4.2.1**

### Operating system

Windows 11, Os Ventura 13.6.6

**Comment by DmitryArefiev** [comment]
Yes, **can reproduce** on my side  (**4.3**, Windows10)


https://github.com/musescore/MuseScore/assets/90187801/c81f367c-4cd2-4f05-a1cd-77e4a2ba70a4

Thanks for logging!
