### ISSUE TITLE
Play Sound Track From Individual Part

### ISSUE THREAD

**Issue by bobniqu** [musescore/MuseScore#22865]
### Your idea

Playing back whole score while looking at only 1 part.

### Problem to be solved

OK. As an example, I have a piece with 19 parts. I am playing 3rd trumpet. If I click on Parts and open up 3rd trumpet, I get the 3rd trumpet music. If I play the soundtrack, I get only the 3rd trumpet, not the full score. But what if while I'm looking at the 3rd trumpet part but want to play back all 19 parts? I suggest a button or something to provide that option i.e., playing back all the parts while looking only at 3rd trumpet.

**Comment by avvvvve** [comment]
@bobniqu Closing, because this functionality is already merged into master via #20758 and should be available in the 4.4 release! Feel free to try it out in the master build ([available here](https://ftp.osuosl.org/pub/musescore-nightlies/)) if you want to see it in action now.

**Comment by bobniqu** [comment]
Thanks, but where is this feature in the version?

**Comment by avvvvve** [comment]
There isn't a single-click button to hear all instruments in a part (yet!), but now it is possible to unmute any/all tracks in parts. Previously, instruments that were hidden in the instruments panel could not be unmuted in the mixer at all.

We'll address the second part—un-muting all instruments in fewer clicks—in this feature request: #22767
