### ISSUE TITLE
Elements that can stretch are not aligned in continuous view (horizontal) mode

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#22870]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Elements such as the trill line, octave line, dynamic changes, tempo changes, etc. are not aligned according to the engraving rules when viewed continuously (horizontally). 
Dynamic elements are not aligned in a random (incomprehensible to me) order, that is, they are aligned somewhere, and they are not aligned somewhere.

### Steps to reproduce

1. Open the score
2. Turn on the continuous (horizontal) viewing mode 
3. Add the above-mentioned elements to the notes that go beyond the stave on ledger lines

### Screenshots/Screen recordings

![Снимок экрана (343)](https://github.com/musescore/MuseScore/assets/134041121/6f8a2d6a-10c1-4fc1-bedf-7589e67edac9)
![Снимок экрана (341)](https://github.com/musescore/MuseScore/assets/134041121/5570c78c-69bf-4de5-a689-ea49eeb23743)
![Снимок экрана (340)](https://github.com/musescore/MuseScore/assets/134041121/f6feee2c-fba8-43c2-88f2-3629f2e945a8)
![Снимок экрана (339)](https://github.com/musescore/MuseScore/assets/134041121/28ca5e92-8d7f-4d31-9cfd-4119d394f004)

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

No.

### Operating system

Windows 11

### Additional context

Part of this release is already available in #19925. 
I am not completely sure that I have given a complete list of elements that cannot be aligned during continuous viewing. I ask the team members to check all the elements. So far, I have encountered non-alignment of only the elements I have listed above.

**Comment by MarcSabatella** [comment]
If I understand correctly, this is a known and rather deliberate limitation of continuous view: vertical collision avoidance of lines is skipped for performance reasons.  This particular type of collision avoidance normally works system by system, but in continuous view there is only one system, so it would require processing the entire score.  It’s certainly at some point that restriction could be lifted (and either pay the performance penalty or find a way around it), but currently anyhow it is by design.

**Comment by Dima-S-Jr** [comment]
> If I understand correctly, this is a known and rather deliberate limitation of continuous view: vertical collision avoidance of lines is skipped for performance reasons. This particular type of collision avoidance normally works system by system, but in continuous view there is only one system, so it would require processing the entire score. It’s certainly at some point that restriction could be lifted (and either pay the performance penalty or find a way around it), but currently anyhow it is by design.

Well, then it's worth thinking about how to ensure correct engraving during continuous viewing without compromising performance.
