### ISSUE TITLE
"B♭ Contrabass Tuba" part shows up in C instead of Bb

### ISSUE THREAD

**Issue by D-N-N-D** [musescore/MuseScore#22871]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

I want to create a Bb (Contrabass) Tuba part. When selecting this instrument it turns out the part is not transposing. This can also be seen when clicking on the instruments name: in the 'Transposition' no values are available.

### Steps to reproduce

1. Create a new score
2. Choose a Trombone and a Contrabass Tuba (Bb)
3. Choose a key signature of your like and add it
4. Both the parts have the same type and the same amount of key signatures

### Screenshots/Screen recordings

![Screenshot from 2024-05-16 22-01-35](https://github.com/musescore/MuseScore/assets/170042224/62f53aa9-8e2b-4b5d-a467-3f224d251a6a)
[NoTransposition.zip](https://github.com/musescore/MuseScore/files/15340381/NoTransposition.zip)

### MuseScore Version

4.3.0

### Regression

No.

### Operating system

Fedora (but it should also happen on other OSs)

### Additional context

I think the solution is to add the following to the instruments.xml file:

<transposeDiatonic>-8</transposeDiatonic>
<transposeChromatic>-14</transposeChromatic>

for <Instrument id="bb-tuba">

as this is working with the Sousaphone in Bb. But maybe there are more things to adjust - that is something you know better!

Thank you for analyzing and fixing!

**Comment by D-N-N-D** [comment]
After submitting it turns out that the xml tags are gone. This is what I meant in the 'Additional context':

> <transposeDiatonic>-8</transposeDiatonic>
> <transposeChromatic>-14</transposeChromatic>

**Comment by oktophonie** [comment]
It is not a transposing instrument; it's merely pitched in in B flat.

**Comment by SteveBlower** [comment]
In the UK brass band tradition.  Bb contrabass tuba is a transposing instrument, written in treble clef.  And it __is__ available in the Choose instruments menu (as is the smaller Eb version).

![Tuba](https://github.com/musescore/MuseScore/assets/60138048/0e80b9b2-d913-4fc7-9c18-4abadf54b62e)

**Comment by D-N-N-D** [comment]
In many European countries, at least in The Netherlands (Bb Bas) and in France (Bombardon sib), the Tuba is in Bb, so it is a transposing instrument in the HaFa world (Harmonie, Fanfare). It is notated in bass clef (F) and one octave higher (than played). To reach this goal, which Tuba should I then pick from the list?

This should sound the same:
![Screenshot from 2024-05-17 11-57-55](https://github.com/musescore/MuseScore/assets/170042224/2b0e4e55-8305-4e27-b8e0-15531c18e560)

**Comment by D-N-N-D** [comment]
I also checked wikipedia. In the English version my point is not mentioned, but when I look at the Dutch version on https://nl.wikipedia.org/wiki/Tuba_(instrument) the following is stated:

Internationaal schrijft men voor de tuba op reële toonhoogte in de bassleutel. [...] In brassbands schrijft men echter altijd getransponeerd in de vioolsleutel. In andere blaasorkesten hangt het af van de geografische context. Zo zal men in Duitsland en de Verenigde Staten de tuba altijd op reële toonhoogte (klinkend) schrijven, **terwijl men in België en Nederland de brassbandnotatie overneemt of getransponeerd in de bassleutel schrijft**. [...]

Translated: "while in Belgium and The Netherlands the brassband notation is used or it is transposed in the bass clef".

**Comment by SteveBlower** [comment]
That is a new one for me. I thought bass clef tubas were all written at concert pitch.  It may explain why I have found parts with many ledger lines above the bass clef that are way above my compass.  I thought it was because I was a lousy tuba player.

If you right click in the stave you can set the transposition in the stave/part properties.

![TubaTranspose](https://github.com/musescore/MuseScore/assets/60138048/22870b43-a05a-4af4-84c4-1508909e7179)

**Comment by D-N-N-D** [comment]
In symphony orchestras bass clef tubas are written at concert pitch. Yes, indeed, you can change that in the transposition. You can also use the Sousaphone in Bb.

But if there is a separate instrument 'Contrabass Tuba (treble clef) in Bb' why couldn't a new instrument like 'Contrabass Tuba (bass clef, one octave higher) in Bb' be added. That would solve always changing the transposition or editing the instruments.xml file.
