### ISSUE TITLE
Implement "Flip direction" shortcut action for new dynamics & hairpins

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#22886]
The 'X' keyboard shortcut which triggers the "Flip direction" action doesn't work for cycling through above/below position of dynamics and hairpins in #22662.

It should do the following:
1. If Position is set to Below, pressing X switches Position to Above
2. If Position is set to Above, pressing X switches Position to Below
3. If Position is set to Auto...
     - And the object is below the staff, pressing X switches Position to Above
     - And the object is above the staff, pressing X switches Position to Below

You won't be able to set Position back to Auto using the X shortcut. The shortcut should have no bearing on "Center between staves".

Logging now to not hold up merging #22662!

**Comment by mike-spa** [comment]
Completed in #23426
