### ISSUE TITLE
NVDA Stops Reading File Menu's Items After Navigating to Sibling Menus (it says "blank")

### ISSUE THREAD

**Issue by NinjaNas** [musescore/MuseScore#22883]
### Issue type

Accessibility issue (e.g. for keyboard-only or screen reader users)

### Bug description

When using keyboard navigation, NVDA will stop reading menu items after moving to a new file menu.

### Steps to reproduce
**Case 1**
1. Alt + F
2. See that NVDA works
3. Hit Left Arrow to close the menu
4. Note that it suddenly says blank when trying to read the file menu
5. Hit Right Arrow and see that it suddenly is able to read the file menu again
6. Hit Down Arrow and see that all of the menu items read blank
7. This now affects all other file menus until focus is lost on the file menu and Alt + F is used again

**Case 2** (https://github.com/musescore/MuseScore/issues/19987#issuecomment-2335048247):
Appeared after #20191

1.	 Press Alt F to open File menu, press right arrow.  You will hear “Application Menu Panel Edit Button”.  You should just hear Edit or the first item in the Edit menu.
2.	Press right arrow twice and you hear “Application Menu Panel Add Button”.
3.	Press Right arrow a third time and you hear “Blank”.  Sometimes this carried on saying blank for me with further arrow presses, sometimes it moved on to the next item with a second press.
4.	Press left arrow to move back to the Add menu and then press down arrow, for each press you just hear “blank” instead of the items of that menu.  It may be moving down visually and just not announcing, or may not be moving at all, not sure.
5.	Press Esc to return to the score and close menus.
6.	Press Alt F to open File menu and press down arrow several times to for example move down to close.
7.	Press right arrow to move over to the edit menu, again it just says “blank”.  Note this is the same thing NVDA says when you press down arrow and move on to an empty line in a document.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/54213302/ab70d0c8-6e64-4f2c-b88a-0ce5824f7f1e

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

Became more serious in **4.4.0**

### Operating system

Windows 10

### Additional context

Relevant files may include:
src/framework/ui/internal/navigationcontroller.cpp 
src/appshell/view/navigableappmenumodel.cpp

src/appshell/qml/platform/AppMenuBar.qml
src/framework/uicomponents/qml/Muse/UiComponents/StyledMenuLoader.qml
src/framework/uicomponents/qml/Muse/UiComponents/internal/StyledMenu.qml

Additional Info:
https://github.com/musescore/MuseScore/pull/20191#issuecomment-2099180477

**Comment by bkunda** [comment]
@zacjansheski please check regression status and whether other parts of the app are similarly affected. Thanks!

**Comment by oktophonie** [comment]
See also https://github.com/musescore/MuseScore/issues/20732

**Comment by zacjansheski** [comment]
Not an issue with Narrator or VoiceOver

**Comment by jmwmusic** [comment]
In 4.4.1 it is now possible with NVDA to arrow along the menus, but as soon as you arrow down you just hear blank for each key press.  So, pressing Alt F then right arrow you hear "application menu panel edit button" - should just say Edit or announce the first item in the Edit menu.  Then pressing down arrow says blank for each key press.  Similarly, if in the File menu and you arrow down to say close, and then press right arrow you will just hear blank.

**Comment by DmitryArefiev** [comment]
After #20191 it became a kind of regression (see **Case 2** from the description and the comment below). 
Changing to P1

**Comment by DmitryArefiev** [comment]
Fixed in #24638

**Comment by jmwmusic** [comment]
This works well now for menus where items are available, but still says blank if you move over an item that is not available.  I'm not sure if these are  visually shown but dimmed?  For example, open MuseScore but do not open a file, most of the edit menu says "blank" as you move down it as does the next menu to the right.  Usually these would either jump over unavailable items or possibly speak them and say "dimmed".
