### ISSUE TITLE
Repeat line wrong size and position in mmRest mode

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#22930]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When you have a repeat line on empty measures, Go in mmrest Mode typing "m" result in wrong size and position of repeat line.

### Steps to reproduce

1 Create a new score
2 Add Reapeat line in some rest measure
3 Go in mmRest mode
4 Look at size and position of repeat line

### Screenshots/Screen recordings

Normal mode
![image](https://github.com/musescore/MuseScore/assets/1835871/be58b715-a3fe-4979-80f3-14f3d58bb9bd)
mmRest mode
![image](https://github.com/musescore/MuseScore/assets/1835871/a06f2174-05ae-4f67-9a54-cfd52f590817)

### MuseScore Version

MuseScore Studio version (64-bit): 4.4.0-241420305, revision: github-musescore-musescore-449a64e

### Regression

Yes, this used to work in a previous version of MuseScore 4.x
Regression occured between 4.3.1 and 4.4 (Master)

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

**Comment by zacjansheski** [comment]
Issue is in master, not 4.3.1
