### ISSUE TITLE
Crash when pasting bends

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#22935]
### Issue type

Crash or freeze

### Bug description

There are several crashes that can happen when copy pasting guitar bends. First, when you paste a bend onto a note without a note directly after it, Musescore Studio will crash instantly. Second, if you paste a bend onto a note of a different duration than the original note you copied the bend from, it will also crash, but this time it is a freeze of the program rather than an instant crash (not responding).

### Steps to reproduce

First Crash:
1. input a bend from one note to another
2. copy the bend
3. paste the bend onto a note without a note directly after it
4. Crash
Second Crash/Freeze:
1. input a bend from one note to another, taking note of the duration of the first note
2. copy the bend
3. paste the bend onto another note of different duration than the initial bend
4. Freeze, leading to eventual crash

### Screenshots/Screen recordings

Crash 1:

https://github.com/musescore/MuseScore/assets/21023353/352b3d77-30ea-4f08-b1df-cb1874012f22

Crash 2/Freeze:

https://github.com/musescore/MuseScore/assets/21023353/13f07528-96ca-477a-a53e-b10db15dd93b

Crash 2/Freeze wins out over Crash 1:

https://github.com/musescore/MuseScore/assets/21023353/102e8ed7-8740-46f4-a0b9-27fdf9daf757

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

I don't know

### Operating system

Reported on Windows 11

**Comment by DmitryArefiev** [comment]
Easy to reproduce. The same in **4.2.0** (when new bends released) 
Thanks for logging!


@bkunda - I put this to **4.4** since it's not a regression
