### ISSUE TITLE
Muse Sounds Brass and Choir not updated in release channel

### ISSUE THREAD

**Issue by mdeluca70** [musescore/MuseScore#22957]
### Issue type

Muse Sounds bug

### Bug description

There are a few github items that are closed (such as https://github.com/musescore/MuseScore/issues/22530) which require Muse Sounds libraries to be pushed to the release channel. 

I have two Windows installations (different computers) - one on the release channel, and on using the beta hub. I can monitor the Muse Sounds library versions by reading the .dlcache file, which is located in the Muse Hub Downloads folder.
The computer on the release channel is on Brass 0.4.1 and Choir 0.3.12. This computer does not show sound flags for Brass, and has Brass and Choir showing up in the mixer incorrectly.

The computer on the beta channel is on Brass 0.4.3 and Choir 0.3.16. The sound listing in the mixer is corrected, and sound flags are present for the Brass instruments.

For me, all other sound libraries on on the same versions on both machines

### Steps to reproduce

Check Muse Sounds versions available in release channel, and compare to what is in beta channel.

### MuseScore Version

4.3

### Regression

No.

### Operating system

Win 11

**Comment by MarcSabatella** [comment]
@shoogle @bkunda this is the issue that we were discussing on GitHub - these two sound sets seem like they should be updated along with 4.3 but for whatever reason were not - still stuck in beta only.  We’re getting support questions pretty much every day about this.

**Comment by mdeluca70** [comment]
Note that this issue was also raised on zendesk when 4.3 was launched

https://musehub.zendesk.com/hc/en-gb/community/posts/18704198107165

**Comment by bkunda** [comment]
Great, thanks for this. I believe @sampleeditor and @matthewreadbass are on to this.

**Comment by bkunda** [comment]
Fix is awaiting release to beta.

**Comment by bkunda** [comment]
I think this can be closed now as it's effectively outdated following the release of Hub v.2.
