### ISSUE TITLE
"Join" and "Break inner beam (8th)" type beams are misplaced in opened v4.2.1 score

### ISSUE THREAD

**Issue by ingvarskagg** [musescore/MuseScore#22952]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Appeared only on my score with all beam properties collected, and it can be reproduced only if the score was saved in the MU Studio v4.2.1 and then opened in v4.3 or 4.3.1 nightly build

### Steps to reproduce

1. Open the score [Beam properties 4.2.1.mscz.zip](https://github.com/musescore/MuseScore/files/15416025/Beam.properties.4.2.1.mscz.zip)
2. Note the Beams in the measures starting from 3rd 

### Screenshots/Screen recordings

<img width="1502" alt="Screenshot 2024-05-23 at 15 16 44" src="https://github.com/musescore/MuseScore/assets/149785325/c0b4a914-21bc-40b3-9dfc-cf375b67c436">

### MuseScore Version

4.3

### Regression

Yes, this used to work in a previous version of MuseScore 4.2.1

### Operating system

macOS 14

### Additional context

Beams are fine if I create a score in the MU Studio v4.3 or earlier one (tried 4.0.2 accidentally, and all's good there too)

**Comment by MarcSabatella** [comment]
FWIW, this does not appear to be a recent regression; same error opening the score in 4.2.1.  It appears to be due the specific combination of beaming across the system break: the first note of bar 6 is set to "join beams" while the last rest of the preceding measure is set to break inner 16th.  A very unusual combination, and changing any one of those three things (the system break, the break inner 16th on the rest, or the join beats at the start of the next bar) fixes it.  But it's also not clear to me how to reproduce from scratch.
