### ISSUE TITLE
Language switch and translation updates are not reflected in the some Palette element's tooltips

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#22960]
### Issue type

UI/UX bug (incorrect info or interface appearance)

### Bug description

Language switch and translation updates are not reflected in the some Palette element's tooltips, not even after a restart of MuseScore

### Steps to reproduce

1. Check e.g. the Grace notes palette and an element's tooltip
2. Switch to another language and/or update translations
3. Restart MuseScore (the need for this is an IMHO quit serious regression vs. Mu3!)
4. Check e.g. the Grace notes palette and an element's tooltip: still the same language/string

Affected are:

* all elements of the Beams properties palette
* probably some elements of the Accidentals palette (the parentheses and brackets), I can't see those though
* some elements of the Layout palette (there for the 3 frames, staff type change and insert measure)
* one element of the Noteheads palette (the parentheses)
* all elements of the Grace notes palette
* some elements of the Guitar palette (the 4 bends)

i.e. all elements that in palettecreateor.cpp get added via `appendActionIcon()` rather than `appendElement()`!

Workaround: use the ... menu of these palettes and reset them

### MuseScore Version

Probably all Mu4 version, but verified with 4.3.0, 4.3.1-dev, 4.4.0-dev

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11, most probably others too

### Additional context

Came up in #22923

**Comment by Jojo-Schmitz** [comment]
Still the case and just came up again on Discord

**Comment by FrancRos31** [comment]
> some elements of the Guitar palette (the 4 bends)

The issue just reappeared after changing the translation from italian to english US (OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97). The 4 bends showed the italian translation in the english version, resetting the palette fixed the problem.

**Comment by zacjansheski** [comment]
@FrancRos31 I haven't reproduced an issue with switching between Italian and US English.  If you are consistently reproducing please open a new issue

**Comment by FrancRos31** [comment]
@zacjansheski So, I checked again if the issue is still present: everything works as it should. But, I ran into this after switching many times between Italian and English US. 
![4](https://github.com/user-attachments/assets/bcee65d2-b3d0-45bc-bfd5-13b384ec3bc4)
English US, but the names displayed in the cells are in Italian. It happened only this time, I can't reproduce it. Just FYI.

**Comment by cbjeukendrup** [comment]
Maybe it only reproduces if between switching languages you also make some change to the palettes that causes them to be persisted.

**Comment by FrancRos31** [comment]
Issue still present and reproducible, this time between French and Italian (and vice versa).

The elements involved are: distorsion, overdrive, harmonics, jazz tone and normal in the GUITAR palette.
Before watching the video, these are the expected cell names for each language:

FRENCH
distort 
overdrive
harmonics
ton jazz
Normal

ITALIAN
distor
sovramodulazione
armonici
tono jazzistico
normale

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

https://github.com/user-attachments/assets/9bf99d66-0529-4e70-a62f-6fdf8e4e43d8

Don't know if other languages are involved, but now the problem moved from the tooltips to the elements' name.
