### ISSUE TITLE
Pedal markings attached to notes in RH in grand staff show in incorrect location

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#22969]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

It's not at all uncommon in piano music for the pedal markings to be relative to notes in the RH staff (e.g. arpeggiations etc.) where the LH staff either has nothing or no notes that change with the harmony.
Yet if you try to attach pedal markings to RH notes, the pedal mark appears between the RH and LH staff, which I'm prepared to say is virtually never what's wanted.  

### Steps to reproduce

1. Create a new score for piano
2. Add a bunch of rapid notes (8ths/16ths, etc.) into the RH staff
3. Select a few and add a pedal mark to go under them
4. The pedal mark incorrectly appears between the staves.

### MuseScore Version

4.3

### Regression

No.

### Operating system

Windows 11

### Additional context

Personally I don't think there's *any* need to showing pedal markings between the staves of a single instrument. But if there were some truly bizarre case it might be wanted, by all means add some flag to support it.  For my money though the pedal markings should always be shown beneath the bottom-most visible staff of any instrument.

I'm aware there is another workaround using hidden rests in v2 (e.g.), however this makes the score quite hard to work with and I found a lot of weird behaviour with this too.

**Comment by oktophonie** [comment]
I don't see why we'd prevent showing a pedal line on other staves, even if such a thing would be, in your opinion, 'truly bizarre'.

But with the anchors system coming in 4.4, and already in master, you can attach pedal markings on the bottom stave to any rhythmic position even if there's no note there.

**Comment by wizofaus** [comment]
Ok, but is it a simple as just selecting the range of music you want and adding the pedal mark?

**Comment by wizofaus** [comment]
I tried to use this today, and I couldn't figure out how to easily add or copy/paste pedal marks so they were attached to specific beats (I got there eventually but I got the impression it's not quite working as designed...). This is what I was trying to create:

![image](https://github.com/musescore/MuseScore/assets/5364225/cd9f0353-e1ed-4f28-8f19-a151d4698158)
