### ISSUE TITLE
Tablature score crashes on opening

### ISSUE THREAD

**Issue by RickyChitarrone** [musescore/MuseScore#22985]
### Issue type

Choose option...

### Bug description

I created a lute tablature duet score/parts which crashes MuseScore when I try to reopen it. 

The event is preceded by playback abnormalities: notes being played simultaneously from elsewhere in the score in addition to where I've selected; parts marked "Play" require toggling off and back on to get them to play. After the crashing, the "Home → Scores New and Recent" doesn't show the file among the thumbnails, even though I'd been saving it throughout the editing process. The Mac OS menu bar "Apple → Recent Items" does list the file, however. 

In all instances the files undergo extensive formatting, and at some time over the process of editing/saving the file it becomes unopenable. I couldn't say what triggers it.

For some more detailed history, the MuseScore.com bugs forum person I'd been speaking with, Cadiz1, mentioned that tablature without the "TAB" clef will behave like this, that it's a known bug. But the version I edited with clefs, now in "MuseScore 4.3.1.241470504 Nightly", had the same behavior. I refer you to my bugs forum thread with user Cadiz1, https://musescore.org/en/node/364505. 

I don't know if it's relevant, but in addition to MuseScore Evolution 3.7.0.9232793350 Nightly and Musescore 4.3.0, I also have  installed on the same drive the Nightlies 4.3.0.241360504, 4.3.1.241440504, 4.3.1.241460504 and 4.3.1.241470504.

I attach the most recent file with this behavior "Duet in A". Evolution will open the file. I also have attached a file that began crashing without clefs, "1025 tab RS (original)". I've suspended work until this can be resolved. 

Thanks for your help! Let me know what you discover.

[Duet in A.zip](https://github.com/musescore/MuseScore/files/15448971/Duet.in.A.zip)
[1025 tab RS (original).mscz.zip](https://github.com/musescore/MuseScore/files/15448994/1025.tab.RS.original.mscz.zip)

### Steps to reproduce

Open either mscz file in any version of MuseScore 4.3.x. Various symptoms preceding the app's inability to continue working with my project are described above.

I believe that something during the formatting process causes the file to make Musescore crash if I need to reopen it. 

### MuseScore Version

4.3.0 and 4.3.1.241470504 Nightly

### Regression

Choose option...

### Operating system

Mac Mini M1 2020, OS 13.3, 16GB memory

### Additional context

Here's the top of the most recent crash log when attempting to open the Duetto in A. If you want the whole thing, let me know. It's too long to include in the this forum without exceeding character count.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               mscore [18975]
Path:                  /Applications/MuseScore 4.3.1.241470504 Nightly.app/Contents/MacOS/mscore
Identifier:            org.musescore.MuseScore
Version:               4.3.1 (241470504)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-05-26 17:33:28.2011 -0400
OS Version:            macOS 13.3 (22E252)
Report Version:        12
Anonymous UUID:        358585A6-E551-895C-0BF6-A9855C0C80D2

Time Awake Since Boot: 14000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000022
Exception Codes:       0x0000000000000001, 0x0000000000000022

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [18975]

VM Region Info: 0x22 is not in any region.  Bytes before following region: 140722820562910
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      mapped file              7ffc95bb4000-7ffca4060000 [228.7M] r-x/r-x SM=COW  ...t_id=f4310007

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   mscore                        	       0x100e223c4 mu::engraving::EngravingObject::score() const + 4
1   mscore                        	       0x100ecb6f4 mu::engraving::LinkedObjects::mainElement() + 164
2   mscore                        	       0x10117fb06

**Comment by RickyChitarrone** [comment]
Hi folks. I'm grateful someone, Eism, is looking into this, but I don't understand any of what's being noted above in the comments. Is this a good time to sit tight and let this play out with the big kids?

**Comment by oktophonie** [comment]
It just means a [fix](https://github.com/musescore/MuseScore/pull/22992) has been made. If you want to test it for yourself the instructions are [here](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds).

**Comment by RickyChitarrone** [comment]
Is this fix already incorporated into the the May 28 nightly build of 4.3.1? Please pardon me for not really understanding all this information!

**Comment by oktophonie** [comment]
It will be in the 29 May nightly.
(and also the actual 4.3.1 release which will hardly be far behind)

**Comment by RickyChitarrone** [comment]
Thanks! I really appreciate your work and the talent that goes into it. I
understand that lots of you are volunteers. Wonderful!

Co-Director


* Tempesta di Mare Philadelphia Baroque Orchestra * 1034 Carpenter St
Philadelphia PA 19147
***@***.***
www.tempestadimare.org
Professor of Baroque Lute and Theorbo
* Peabody Conservatory*
Johns Hopkins University
1 East Mt Vernon Place
Baltimore MD 21202
***@***.***
www.peabody.jhu.edu
<http://www.peabody.jhu.edu/conservatory/faculty/stone_richard/>
------------------------------
richardstonelute.com
215-868-5068 cell
215-339-4067 home
