### ISSUE TITLE
Request to add "Snares Off" notation and sounds to MuseScore 4

### ISSUE THREAD

**Issue by TRF29568** [musescore/MuseScore#23008]
### Your idea

I think it would be beneficial to have a "snares off" notation and sound, especially since some music compositions call for it.

### Problem to be solved

This would solve the issue of me having to use a tom-tom on a drumset as a substitute for the "snares off".

### Additional context

I would like to see this added in the "Text" palette of the Palettes menu.

**Comment by zacjansheski** [comment]
To be clear, you are asking for snares off for the drum kit instrument?

It does already exist for the muse sounds concert snare

![Screenshot 2024-05-28 161108](https://github.com/musescore/MuseScore/assets/69917893/af20028e-c784-4e84-908a-ebf5c6dc20cc)

**Comment by TRF29568** [comment]
Where would I find this specifically? I'm not seeing it.

**Comment by MarcSabatella** [comment]
Add staff text (e.g., from menu or palette or Ctrl+T), click the sound flag icon, then select the appropriate sound.

For further help learning to use MuseScore, please ask on the support forum at MuseScore.org

**Comment by TRF29568** [comment]
Got it. Thanks!
