### ISSUE TITLE
Crash when entering dash in build from current git sources

### ISSUE THREAD

**Issue by lenborje** [musescore/MuseScore#23002]
### Issue type

Crash or freeze

### Bug description

Get current develop code from git and build.
When entering a dash on a voice where another voice has more notes in the same interval, MuseScore crashes.

### Steps to reproduce

1. Unpack the attached zip.
2. Open Hallo_world.mscz in MuseScore
3. Select the first note in the second voice. (An f.)
4. Add lyrics to this note, enter any syllable. 
5. Press the hyphen button to enter a dash. Works on MuseScore 4.3.0, crashes in current code from git.

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/20604032/987f65db-3f9c-4543-a720-3e8e5183b5c4)
### MuseScore Version

Current head: commit 723753443b4406902440ad942e574d9166acf074 

### Regression

Yes, this used to work in **MuseScore 4.3.1**

### Operating system

MacOS

### Additional context

MuseScore file in the attachment: [Hallo_world.zip](https://github.com/musescore/MuseScore/files/15467286/Hallo_world.zip)

Excerpt from MacOS crash report:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               mscore [82987]
Path:                  /Applications/mscore.app/Contents/MacOS/mscore
Identifier:            org.musescore.MuseScore
Version:               4.4.0 ()
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-05-28 11:43:04.4825 +0200
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        2A904E6F-E535-CA66-9F27-04045FB6A678

Sleep/Wake UUID:       8D6DB9E1-37E5-4A69-8740-5A2E21F7E11F

Time Awake Since Boot: 430000 seconds
Time Since Wake:       827 seconds

System Integrity Protection: enabled

Crashed Thread:        12

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   mscore [82987]

Application Specific Information:
abort() called

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	       0x1969a466c _nanov2_free + 352
1   mscore                        	       0x102e15eb4 mu::engraving::TablatureFretFont::~TablatureFretFont() + 88
2   mscore                        	       0x102e0d8b4 std::__1::vector<mu::engraving::TablatureFretFont, std::__1::allocator<mu::engraving::TablatureFretFont>>::~vector[abi:ue170006]() + 48
3   libsystem_c.dylib             	       0x196a302e8 __cxa_finalize_ranges + 476
4   libsystem_c.dylib             	       0x196a30070 exit + 44
5   mscore                        	       0x1029db4f0 crashCallback(int) + 320
6   libsystem_platform.dylib      	       0x196ba3584 _sigtramp + 56
7   mscore                        	       0x1036f3844 mu::notation::NotationInteraction::navigateToNextSyllable() + 652
8   mscore                        	       0x103711490 std::__1::__function::__func<mu::notation::NotationActionController::registerAction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, void (mu::notation::INotationInteraction::*)(), mu::notation::NotationActionController::PlayMode, bool (mu::notation::NotationActionController::*)() const)::$_85, std::__1::allocator<mu::notation::NotationActionController::registerAction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, void (mu::notation::INotationInteraction::*)(), mu::notation::NotationActionController::PlayMode, bool (mu::notation::NotationActionController::*)() const)::$_85>, void ()>::operator()() + 92
9   mscore                        	       0x1033823d8 muse::actions::ActionsDispatcher::dispatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, muse::actions::ActionData const&) + 328
10  mscore                        	       0x1033a8a74 muse::shortcuts::ShortcutsController::activate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) + 216

**Comment by DmitryArefiev** [comment]
Tested on Win10. **Crashes** in **master** only (doesn't crash in 4.3.1)
