### ISSUE TITLE
Select | more for articulation shows wrong text in "Element type" field

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23019]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

If you select any articulation mark, then use the Select|more option from the context menu, the "Element type" field in the subsequent dialog is incorrectly populated with the Element *subtype*.  Which is confusing, because it gives the impression that clicking OK will only select other objects of the same subtype, but that is only true if you also check the "same subtype" checkbox, otherwise it will actually select all articulation elements.

### Steps to reproduce

1. Create a new score with two notes, add a staccato to one and an accent to the other
2. Click the accent, then from the context menu, choose Select|more
3. The next dialog has an "Element type" field, which says "Accent above" (or below), but really should say "Articulation"
4. Click OK. Both articulations (staccato and accent) are selected - correct behaviour, but arguably unexpected given the dialog suggests only elements of "type accent above" would be selected.

Note that even the inclusion of "above" in the subtype is wrong - as even if you do click "Same subtype" (the subtype also being shown, correctly, as "Accent above"), it will also select "accent below" articulations.

### MuseScore Version

4.3

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

**Comment by XiaoMigros** [comment]
I address this in #20850

**Comment by wizofaus** [comment]
That PR is crazy old, that's the sort of thing I was trying to get a conversation going about in discord...
