### ISSUE TITLE
Latest build (4.3.1 source?) crashes adding key signature to empty score

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23015]
### Issue type

Crash or freeze

### Bug description

Adding a key signature to an empty score is enough to crash application

### Steps to reproduce

1. Create any empty score
2. Add key signature

### MuseScore Version

4.3.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

[1;32m13:24:51.962 | INFO  | 53264           | FluidSynth::addSoundFonts | success load soundfont: C:/Users/WizOf/source/repos/wizofaus/MuseScore/builds/Win-Qt6.2.4-msvc2019_64-VS17-RelWithDebInfo/install/sound/MS Basic.sf3[0m
[1;32m13:24:51.992 | INFO  | 53264           | FluidSynth::addSoundFonts | success load soundfont: C:/Users/WizOf/source/repos/wizofaus/MuseScore/builds/Win-Qt6.2.4-msvc2019_64-VS17-RelWithDebInfo/install/sound/MS Basic.sf3[0m
Exception thrown: read access violation.
**el** was nullptr.

Line 211 of notationinteraction.cpp:

        if (el->hasVoiceApplicationProperties()) {
            el->setInitialTrackAndVoiceApplication(el->track());
        }
        
        Needs a null check.

**Comment by RomanPudashkin** [comment]
>Line 211 of notationinteraction.cpp:

@wizofaus this piece of code doesn't exist in 4.3.1

**Comment by wizofaus** [comment]
So is master now 4.4? Wasn't sure...

**Comment by RomanPudashkin** [comment]
yes, master is 4.4
