### ISSUE TITLE
Changes in beam properties with dotted eighths and sixteenths not observed on score

### ISSUE THREAD

**Issue by dpMusicman** [musescore/MuseScore#23029]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When attempting to beam together multiple instances of the rhythm [dotted eighth, sixteenth], the score does not observe them, not changing from the original beaming.

### Steps to reproduce

1. Create a new score with a 4/4 time signature
2. Input the following rhythm = dotted eighth, sixteenth, dotted eighth, sixteenth
3. Select the second dotted eighth (beat 2) and apply the beam property "Join beams".

### MuseScore Version

4.3.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 13

**Comment by MarcSabatella** [comment]
Update to 4.3.1 - this was just fixed
