### ISSUE TITLE
Musescore crashes when Bluetooth Headphone is disconnected

### ISSUE THREAD

**Issue by gvangorp** [musescore/MuseScore#23028]
### Issue type

Crash or freeze

### Bug description

I am using a Bluetooth QuietComfort ANC headphone for arranging on remote locations.
Regularly, when I am in a hurry, I disconnect the headphone whilst Musescore is running. This makes Musescore stuck and crash, probably due to a audio switch.
This can also happen when you turn the Headset on when you have Musescore open. Then Musescore freezes.
So, when Musescore is not running very stable when switching to/from Bluetooth audio...

### Steps to reproduce

1. Make sure the Bluetooth headphone is connected.
2. Open Musescore and start edit a score.
3. Disconnect the Bluetooth headphone.
4. CRASH

### MuseScore Version

4.2.1.240230937

### Regression

I don't know

### Operating system

Windows 10

**Comment by Eism** [comment]
Could you try 4.3.1?
https://github.com/musescore/MuseScore/releases/tag/v4.3.1

**Comment by zacjansheski** [comment]
Closing, no reply
