### ISSUE TITLE
Regression: 4.3.1 broken appimage install function 

### ISSUE THREAD

**Issue by theofficialgman** [musescore/MuseScore#23031]
### Issue type

Other type of issue

### Bug description

Regression in 4.3.1. musescore appimages can no longer be installed.

```
/tmp/MuseScore.AppImage: 1: Syntax error: word unexpected (expecting ")")
MuseScore.AppImage failed to run its own installation procedure. Please review errors above.
```

This regression was caught by the pi-apps auto update CI and prevented shipping this broken version to pi-apps users

https://github.com/Botspot/pi-apps/actions/runs/9294870171/job/25580904130#step:7:1646

### Steps to reproduce

./MuseScore.amAppImage install

### MuseScore Version

4.3.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux

**Comment by MarcSabatella** [comment]
Is that ARM only?  I didn’t have any difficulty installing prerelease builds of 4.3.1 on Intel.  But the final release I got by running “update”, so I guess it’s possible something broke just between the RC and the final release.  Seems rather unlikely though,.

**Comment by theofficialgman** [comment]
Ah sorry this isn't a musescore issue, it works fine on a native system. I forget that our auto update CI results in errors executing some appimages (it uses QEMU) due to mangled ELF headers https://github.com/Botspot/pi-apps/actions/runs/9296445521/job/25584990861#step:3:1361

**Comment by theofficialgman** [comment]
I have resolved the issue by adding a binfmt for type 2 appimages https://github.com/pguyot/arm-runner-action/pull/112/commits/8fa2336196c297c2e28187d5ba097b3061524861
