### ISSUE TITLE
Some elements are lost/shifted when using join measure

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#23030]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Affected elements:
* slurs disappear after save/reopen
* hairpins shifted
* Gradual Tempo change shifted and disappear after save/reopen

This issue was [mentioned ](https://github.com/musescore/MuseScore/pull/21883#issuecomment-1991597364) earlier and came up again https://musescore.org/en/node/364634

### Steps to reproduce

1. Create empty score
2. Leave several empty measures, type notes
3. Add slurs to them
4. Add hairpins
5. Select two empty measures -> Tools -> Measures -> Join selected measures
6. Hairpins will shift immediately to the right. Slurs will disappear after save/reopen.

### Screenshots/Screen recordings

Slurs lost, hairpins shifted:

https://github.com/musescore/MuseScore/assets/919446/395cf874-e591-41fa-a648-4d2f94e6147d

Rit. lost:

https://github.com/musescore/MuseScore/assets/919446/80bcaf93-b306-4eca-8f19-934c4530e4cc

### MuseScore Version

4.3.1, 4.4.0 master

### Regression

I don't know

### Operating system

windows 10

**Comment by mercuree** [comment]
Came up again https://musescore.org/en/node/358862#comment-1245363

**Comment by axiomizer** [comment]
I ran into what I presume is a variant of this bug, where the slurs are shifted.

https://github.com/musescore/MuseScore/assets/138620999/7afe933f-ff9d-483d-90d2-3f0849ef5235
