### ISSUE TITLE
Chord Symbols Root Letter disappearing in parts when .mss file used in Score Preferences to set defaults for parts

### ISSUE THREAD

**Issue by tommy-banana** [musescore/MuseScore#23047]
### Issue type

Engraving bug (incorrect part rendering)

### Bug description

When I have a .mss style export file selected in the Style for Part section in Score preferences, chord symbols in the parts do not display the root note letter - for example Cmin7 shows as min7. If you click on the chord box and it becomes active you can see the root letter (eg C in the example just given) is there in the box once opened.

The issue can be fixed in each individual part by going to style>chord symbols and changing to Chord Appearance Style to Jazz or to jazz and then back to Standard.

If I delete the .mss from Score preferences>Style for Part it stops happening on newly created scores but remains an issues whenever I open a score create when the .mss file was linked in preferences. If you correct the problem, save the score, then open the score the problem will have returned . I have tried this with 2 different .mss files. I haven't changed the chord font.

### Steps to reproduce

0) Save a style Format>Save Style from an existing score.
1) Set .mss file as Style for Part in Musescore Score Preferences (nb git hub won't let me load man .mss file). 
2) Create new score . 
3) In the score create chord symbols in one part - chord must have chord names/extensions eg Cmin7 or Bbmaj7  not just C or Bb.
4) Open that part . 
If you are seeing same problem chords should look like min7 and maj7 so C and Bb missing from chord symbols. If you double click on the chord symbol you will se the root letter (C, Bb) is there but not visible.
5) Delete preference s from Preferences>Score.Style for Part and repeat. Once the .mss part is deleted, if you create a new score and add chord symbols the chords should display correctly in the part.

### Screenshots/Screen recordings

screen recording https://youtu.be/r9s2Ffejy1A

### MuseScore Version

4.3.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac Sonoma

**Comment by Jojo-Schmitz** [comment]
please zip such an .mss file and attach the zip archive

**Comment by Jojo-Schmitz** [comment]
See also #20991

**Comment by tommy-banana** [comment]
Ok will do Tom Bancroft+447974 983701Sent from my iPhoneOn 2 Jun 2024, at 18:32, Joachim Schmitz ***@***.***> wrote:﻿
please zip such an .mss file and attach the zip archive
