### ISSUE TITLE
Crash on changing measure duration

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#23041]
### Issue type

Crash or freeze

### Bug description

Changing measure duration is causing crash

### Steps to reproduce

1. change measure duration

### MuseScore Version

master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x
Issue is in Master. Not an issue in 4.3.1

### Operating system

Linux Mint (Ubuntu 22.04)

**Comment by zacjansheski** [comment]
Here are diagnostic files if they help anyone

[MeasureDurationCrash.zip](https://github.com/user-attachments/files/15552467/MeasureDurationCrash.zip)

**Comment by sammik** [comment]
same #23626
