### ISSUE TITLE
Slurred staccato is inaudible on some instruments

### ISSUE THREAD

**Issue by BulbaCat** [musescore/MuseScore#23057]
### Issue type

Muse Sounds bug

### Bug description

Some instruments such as trumpet, trombone and harp play staccatos very quietly when slurred. 

### Steps to reproduce

1. enter notes on harp
2. add slur and staccato
3. playback

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69719660/0d47fefa-8678-409f-b57d-bc13871b95cb

### MuseScore Version

4.3.1.241490900

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 11

**Comment by wizofaus** [comment]
Also occurs with Fl 1, Trumpet & Trombone - but only Muse Sounds.

**Comment by Burke-Maester** [comment]
So for me (as of June 8th 2024):
```
Piccolo                                - good
Flute 1                                - plays, but quietly and delayed
Flute 2                                - plays, but not staccato
Alto, Bass and Contrabass flutes       - good
Oboe, English Horn, E♭ Clarinet        - plays, but quietly
B♭ Clarinet                            - plays, but not slurred
Bass Clarinet                          - plays, but quietly
Soprano Sax                            - plays, but loudly
Alto Sax                               - plays, but extremely quietly
Tenor Sax                              - good
Bari Sax                               - doesn't play
Contrabassoon/Bassoon                  - good
------
Horn in F                              - good
Horns a6                               - plays, but loudly
Trumpet, Trombone                      - plays, but extremely quietly
Trumpets a4, Trombones a4              - good
Bass Trombone, Tuba, Cimbasso          - plays, but extremely quietly
------
Violin(s) 1, Violin(s) 2, Viola        - good
Violas                                 - plays, but extremely quietly
Violoncello                            - plays, but not staccato
Violoncelli                            - good
Contrabasses                           - plays, but extremely quietly
------
Soprano, Alto, Tenor, Bass, Men, Women - plays, extremely delayed
Full Choir                             - doesn't play slur, very "jagged" (super large attack)
------
All Guitars                            - good
------
Harp                                   - plays, but extremely quietly
------
Celesta, Dream, Grand, Soft, Suitcase,
Upright, Wurly, Harpsichord            - good
Hammond Organ                          - plays, but not staccato
```

Those are the ones I've checked; I hope that list is helpful.

System data:
OS: macOS 14.4,
Arch.: x86_64 (running on Apple Silicon),
MuseScore Studio version (64-bit): 4.3.1-241490902,
revision: github-musescore-musescore-026c26b
(Copied from the About MuseScore Studio)

**Comment by bkunda** [comment]
Fix is apparently in progress and is awaiting merge.

**Comment by benwaffle** [comment]
Would this be the same bug? These are Muse Sound Trumpets, and the 3rd note of the 2nd bar is inaudible.

<img width="921" alt="Screenshot 2024-07-14 at 4 37 41 PM" src="https://github.com/user-attachments/assets/2f6b90dc-ef75-4218-a590-76b1da3b32c2">


[musescore-trumpet-bug.mscz.zip](https://github.com/user-attachments/files/16228731/musescore-trumpet-bug.mscz.zip)

**Comment by wizofaus** [comment]
Yes, same bug, and I think there's at least one or two duplicate reports.

**Comment by bkunda** [comment]
I believe this has been fixed (tested with harp, trumpet, trombone, baritone sax). 

Here's the latest example from above: 

https://github.com/user-attachments/assets/07ec8890-94d3-42ad-9ee3-013c4c19b07b

If any specific instances of this issue are uncovered, they should be raised via Muse Hub customer support.
