### ISSUE TITLE
Section Viola problem playing Ab in some circumstances

### ISSUE THREAD

**Issue by mdeluca70** [musescore/MuseScore#23056]
### Issue type

Muse Sounds bug

### Bug description

Under certain circumstances (see example below), Ab plays as combination of Ab and G. See attached video. Possibly related to https://github.com/musescore/MuseScore/issues/22783?
Does not appear to be effected by dynamic used.

### Steps to reproduce

1. Load new score, select violas (section). Set key signature to Eb.
2. Enter notes as follows: Fb, C, Ab, Fb, Eb, C, Ab, Eb, D (see attached video) (Note - Fb can also be written as the more conventional E natural)
3. Note that first playing of Ab is OK, but second one plays a double note.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/100440500/623f628c-cd43-4c2b-8d42-b26ddd1008a9

### MuseScore Version

4.3.1

### Regression

I don't know

### Operating system

Win 11

### Additional context

Muse Sounds Strings ver 0.4.12

**Comment by sampleeditor** [comment]
Resolved with Muse Strings 0.4.15 (beta)
