### ISSUE TITLE
Crash when editing “Cue size” of one multimeasure rest  number

### ISSUE THREAD

**Issue by cadiz2** [musescore/MuseScore#23050]
### Issue type

Crash or freeze

### Bug description

As written in the title.

### Steps to reproduce

1. Create a score with a few notes and 2/3 MM rests. 
2. Select these MM rests, and in Properties, check “Cue Size”.
3. Save / Quit / Reload
4. Select **a single MM rest** (this is the problem) -  see GIF below - and uncheck “Cue Size”.

Result: crash

### Screenshots/Screen recordings

![Video cue size](https://github.com/musescore/MuseScore/assets/114975887/1d00b3f8-8530-40d9-b1df-ad2e35d0dc95)

### MuseScore Version

4.3.1

### Regression

I don't know

### Operating system

Windows 10

### Additional context

If you select **ALL** mm rests (then uncheck “Cue Size”), the crash does not occur. Even 2 MM rests (I may have a freeze though)

**Comment by bkunda** [comment]
@zacjansheski pls check for regression status

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/365000, albeit slighly different scenario. Sampls score and steps descibed there

Looks to me like it crashes in the desctructor of NoteEvent

**Comment by Jojo-Schmitz** [comment]
Same workaround: press M twice (togle multimeasure rests off and back on), prior to doing those other moditications

**Comment by cadiz2** [comment]
After investigation and testing with portable versions 4.2.0, 4.2.1, 4.3.0, and 4.3.1, I can say that this is **a regression of 4.3.1.** Works (no crash) with 4.3.0 and previous versions.

**Comment by Jojo-Schmitz** [comment]
At https://musescore.org/en/node/365019 is another such report, again a different scenario, but seemingly the same issue

**Comment by Jojo-Schmitz** [comment]
Seems we need a 4.3.2...

**Comment by cadiz2** [comment]
Another variant, I presume. Removing (Del keystroke)  the contents  of 1 measure just after a MM rest crashes the program.

![Video_2024-06-08_091006](https://github.com/musescore/MuseScore/assets/114975887/015ab92c-5f3c-4e99-b2f3-96f7fb6b22c2)

**Comment by cadiz2** [comment]
Another one (when editing a tempo marking): https://musescore.org/en/node/365033

**Comment by Jojo-Schmitz** [comment]
I wonder whether #23146 resolves this

**Comment by Jojo-Schmitz** [comment]
Tested: it does!
