### ISSUE TITLE
Trills do not copy/paste in master

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#23089]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When copy/pasting a trill or using "R" the trill does not appear.

### Steps to reproduce

Write a whole note with a trill
Copy and Paste that measure.  Or select measure and press "R"
Trill will not appear

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/1f45c92e-786f-4859-9367-5299cf8f0fc2

### MuseScore Version

OS: macOS 14.4, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241560302, revision: github-musescore-musescore-2ce1f78

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 14

**Comment by metasekk** [comment]
For your information, this also seems to happen with other spanners (Pedal marks, crescendos,...). Besides, I can manage to copy-paste them, but I need to extend the selection to the next bar (as though it needed to include the endpoint of the anchor of the spanner).

https://github.com/musescore/MuseScore/assets/120221700/670a6f08-5c8f-435c-94df-9e3712ed7b1a
