### ISSUE TITLE
[musescore/musescore - feature request] enhancing musescore harp sample libraries, with new steinberg harp  free instrument

### ISSUE THREAD

**Issue by tmm88** [musescore/MuseScore#23108]
https://www.steinberg.net/vst-instruments/navia-harp-free/?gclid=CjwKCAjwvIWzBhAlEiwAHHWgvcCq8oqWKtMuVDZOwbgI0ixv4NFceDyxIsZ42hXf98jhbCHlOOkr3BoCU9gQAvD_BwE

please consider including these samples as part of musescore sample library. the samples are original from steinberg, are free and can be converted into a format for musescore, allowing to either stack them with the already existing samples, or even replacing them, and coming out with something that may potentially be better in a way

**Comment by bkunda** [comment]
This is really a matter for the developers of Muse Sounds.
Will pass the idea on. Thank you! 
Closing this ticket as it's not directly related to MS Studio.
