### ISSUE TITLE
Huge memory leak with MuseSounds/MuseSampler

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#23112]
### Steps to reproduce

1. Open Task Manager (and watch MuseScore)
2. Open big score with MuseSounds ([MS4SOUNDS_Beethoven__Symphony_No._9__Op._125.zip](https://github.com/user-attachments/files/15618052/MS4SOUNDS_Beethoven__Symphony_No._9__Op._125.zip))
3. Playback, stop playback/start playback, start playback from beginning etc.
4. Observe RAM amount (it's growing)
5. Close score - RAM is not released  as it should
6. Open score again - it takes more RAM than before

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/06273838-c46f-4613-9563-3b41a3dcb705

### MuseScore Version

4.4

MuseSampler 0.6.3 (latest version from MuseHub)

### Regression

**Doesn't occur** in **4.2.1** (with the same musesampler version)

### Operating system

Windows10

**Comment by metasekk** [comment]
FYI, the part where closing and reopening a score doesn't release memory when using MuseSounds has alredy been reported here: https://github.com/musescore/MuseScore/issues/22721

**Comment by DmitryArefiev** [comment]
I reopened that previously because it appeared **again** on **Mac** with the same memory loss after closing score. 
But now it looks much better, not so serious memory leaks after closing score. 
Results on Win (similar on Mac) on latest 4.4 master and musesampler 0.100.0.299:

1. Measure memory - **177Mb**
2. Open [MS4SOUNDS_Beethoven__Symphony_No._9__Op._125.zip](https://github.com/user-attachments/files/16531228/MS4SOUNDS_Beethoven__Symphony_No._9__Op._125.zip) and close it (after loading samples)
3. Measure memory - **686Mb**
4. Open and close the same score
5. Measure memory - **929Mb**
6. Open and close the same score
7. Measure memory - **1047Mb**
8. Open and close the same score
9. Measure memory - **1217Mb**
10. Open and close the same score
11. Measure memory - **1309Mb**

**Comment by DmitryArefiev** [comment]
I will log this (the comment above) separately since the memory leak is not so huge now
