### ISSUE TITLE
Super long delay during note input when using 4096 buffer size (Windows only)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#23138]
### Steps to reproduce

1. Change buffer size to 4096
2. Restart app
3. Open score
4. Input some notes

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/eb61f7ab-af3f-44b7-9bf9-ca6a847f8dfd

### MuseScore Version

4.4

### Regression

Yes, this used to work in **MuseScore 4.3.1**

### Operating system

Windows 10

**Comment by bkunda** [comment]
Demoting to P2 because of unreliable reproducibility, and because 4096 is unlikely to impact as many users (compared with those who use our default buffer size).

**Comment by DmitryArefiev** [comment]
False alarm... I had not ordinary sample rate settings in DevTools. After Factory reset all good
