### ISSUE TITLE
Musescore Studio 4.3.1 doesn't load

### ISSUE THREAD

**Issue by tarcisiobalbo** [musescore/MuseScore#23142]
### Issue type

Crash or freeze

### Bug description

My MuseScore Studio 4.3.1 doesn't load. I tried to reinstall with or without MuseHub, withouth having success.
I tried to install a previous version, but the result is the same. So i think there could be a sort of incompatibility with my OS (MacOS Sonoma 14.15).
I own a MacBook Retina 13inch 2020, with a processor 1,1 GHz Intel Core i5 quad-core, Intel Iris Plus Graphics 1536 MB, 8Gb RAM.

### Steps to reproduce

1. Click on the icon of MuseScore
2. The app start loading and crashes immediately before opening.

### MuseScore Version

4.3.1

### Regression

No.

### Operating system

macOS 14

**Comment by bkunda** [comment]
Sorry to hear you are experiencing this issue!
With only the information provided to go on, it seems like there's something particular about your environment that may be causing this issue. 
I'd first suggest you approach the support forum on musescore.org to ask for troubleshooting assistance.
If the problem can be generalised (via clear reproducible steps), then please raise the issue again here so we can solve it. 
Thank you.
