### ISSUE TITLE
Crash when sending bracket to back

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23144]
### Issue type

Crash or freeze

### Bug description

Sending a system bracket to the back via the properties pane reliably crashes MuseScore

### Steps to reproduce

1. Create a new score with a bracket (e.g. Piano, any ensemble template)
2. Select the bracket
3. Select "appearance" in the properties panel
4. Click "Send to back"
5. Crash!

### MuseScore Version

4.3.1

### Regression

No

### Operating system

Windows 11

### Additional context

Using master, this is the stack trace on crash:

'MuseScore4.exe' (Win32): Loaded 'C:\Windows\System32\sxs.dll'. 
Exception thrown at 0x0000000140ABA381 in MuseScore4.exe: 0xC0000005: Access violation reading location 0x00000000000000B8.

[1;31m10:24:44.045 | ERROR | main_thread     | crashCallback   | Oops! Application crashed with signal: [11] SIGSEGV-Invalid memory reference[0m

MuseScore4.exe!mu::engraving::Page::scanElements(mu::engraving::Spanner * data) Line 243
	at C:\MS4\src\engraving\dom\page.cpp(243)
MuseScore4.exe!mu::engraving::Page::elements() Line 477
	at C:\MS4\src\engraving\dom\page.cpp(477)
MuseScore4.exe!mu::inspector::AppearanceSettingsModel::allElementsInPage() Line 162
	at C:\MS4\src\inspector\models\general\appearance\appearancesettingsmodel.cpp(162)
MuseScore4.exe!mu::inspector::AppearanceSettingsModel::pushToBackInOrder() Line 215
	at C:\MS4\src\inspector\models\general\appearance\appearancesettingsmodel.cpp(215)
MuseScore4.exe!mu::inspector::AppearanceSettingsModel::qt_metacall() Line 239
	at C:\MS4\builds\Win-Qt6.2.4-msvc2019_64-VS17-RelWithDebInfo\src\inspector\inspector_autogen\include_RelWithDebInfo\SSI7ORFQR4\moc_appearancesettingsmodel.cpp(239)
Qt6Core.dll!QMetaObject::metacall(QObject * object, QMetaObject::Call cl, int idx, void * * argv) Line 322
	at C:\Users\qt\work\qt\qtbase\src\corelib\kernel\qmetaobject.cpp(322)

**Comment by zacjansheski** [comment]
Issue is present in all versions of MS4
