### ISSUE TITLE
Muse sounds triangle plays open when mute is inputted

### ISSUE THREAD

**Issue by BulbaCat** [musescore/MuseScore#23150]
### Issue type

Muse Sounds bug

### Bug description

Muse sounds triangle plays open for both open and mute. It also plays the same sound for staccato, but plays both mute and open correctly for accents, tenutos, and slurs. 

### Steps to reproduce

1. input open and mute notes on triangle + articulation
2. play

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69719660/65a02ace-022a-4e09-8fa7-7a1ee8adef30

### MuseScore Version

4.3.1.241490900

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 11

**Comment by zacjansheski** [comment]
This will be resolved in the next Muse Sounds release

**Comment by zacjansheski** [comment]
This is resolved in the current version of Muse Percussion
