### ISSUE TITLE
[TIED NOTES] Tremolo samples are being re-triggered by ties 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#23168]
### Issue type

Muse Sounds bug

### Bug description

Tied notes appear to be causing tremolo samples to be re-triggered, causing a perceptible interruption in what should be a continuous sound. 

This is especially noticeable at certain lower dynamics. 

Tested with Muse Strings (various instruments) and Muse Timpani, all of which manifest this bug in slightly different ways.

### Steps to reproduce

See below video (Muse Violins 1). Note: 

- The presence of barlines does not appear to be a contributing factor here
- The breve at the end shows that a continuous tremolo sample of up to 8 beats is possible, but isn't being triggered if two semibreves are tied:

https://github.com/musescore/MuseScore/assets/86290556/08477fa4-82ac-43e6-9f92-36b5c20a6e6f

The example of Muse Violin 1 (Solo) is particularly egregious, with some unwanted portamento creeping in between the ties (although, oddly, only at this pitch and if this passage were transposed down one semitone):

https://github.com/musescore/MuseScore/assets/86290556/4d84a7e4-e0b4-4459-826f-407fa6e2534a

### MuseScore Version

OS: macOS 14.5, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241610302, revision: github-musescore-musescore-f96203d

### Regression

No.

### Operating system

macOS 14.5

### Additional context

@sampleeditor @davidwhearn FYI

**Comment by Riley-Sullivan** [comment]
Perhaps connected to [this](https://github.com/musescore/MuseScore/issues/16333) issue.

**Comment by bkunda** [comment]
Given there are other more egregious tied-note bugs at the moment – and with our current 4.4 timeline in mind – this one should be bumped to the next release.
