### ISSUE TITLE
incorrect beam creation

### ISSUE THREAD

**Issue by rainermarwan** [musescore/MuseScore#23162]
### Issue type

Engraving bug (incorrect score rendering)

### Steps to reproduce

Create a Score with some instrument
Enter Notes like Screenshot
Select the whole measure and use the beampropertey like screenshot.
See the result!  The beam presentation ist not correct at the end. It has to stop at the last "real" note independent of the selection.
To circumvent this problem you have to change the beamproperty of the following gracenote to "auto" or single(withount beam). 

### Screenshots/Screen recordings

![grafik](https://github.com/musescore/MuseScore/assets/85316863/ed5dbc29-b573-49d6-a51d-e1a89007285a)

### MuseScore Version

4.3.1

### Regression

No.

### Operating system

Windows 11, PC Intel i9 (13900), 32m storage, disk 2tb ssd Grafik Nvidia rtx3060 12GB

**Comment by oktophonie** [comment]
This is by design; sometimes you may want a beam spanning to or from a rest. To achieve the result you want, you should apply 'join beam' only to the rests you actually wish the beam to go over.

**Comment by rainermarwan** [comment]
I can circumvent the problem, but this presentation of beams does not exist in musik. i have never seen it.

**Comment by oktophonie** [comment]
It may not be 'conventional' but it is not particularly rare either. Here's one example:
![image](https://github.com/musescore/MuseScore/assets/20604032/cc78475a-0f38-4f2a-b391-1177f0e6b736)

**Comment by rainermarwan** [comment]
I'm sorry, but this seems to be another screenshot of a musescore generated score. If this is not the case, please tell me the original score by name, opus, or anything else (maybe in imslp, etc.). I have never seen such rather unplayable music. It looks like a testcase. But nevertheless you can close my issue.

**Comment by oktophonie** [comment]
How gracious, you're much too kind. It's from Stockhausen's Piano Pieces I-IV, published by Universal Edition in 1954.

For more examples, look at pretty much any piece by Elliott Carter from 1960ish on (none of which were done in MuseScore either).
