### ISSUE TITLE
Crash accessing Format|Style (master)

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23181]
### Issue type

Crash or freeze

### Bug description

Accessing Format|Style causes crash, regardless of score

### Steps to reproduce

1. Create/open any score
2. Select Format|Style (either from top menu or context menu)

### MuseScore Version

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

 

	MuseScore4.exe!std::_Xout_of_range(const char * _Message) Line 25	C++
 	[Inline Frame] MuseScore4.exe!std::unordered_map<enum mu::engraving::MSQE_Sid::Sid,mu::notation::StyleItem *,std::hash<enum mu::engraving::MSQE_Sid::Sid>,std::equal_to<enum mu::engraving::MSQE_Sid::Sid>,std::allocator<std::pair<enum mu::engraving::MSQE_Sid::Sid const ,mu::notation::StyleItem *>>>::at(const mu::engraving::MSQE_Sid::Sid &) Line 455	C++
>	MuseScore4.exe!mu::notation::AbstractStyleDialogModel::styleItem(mu::engraving::MSQE_Sid::Sid id) Line 49	C++
 	MuseScore4.exe!mu::notation::NotesPageModel::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 77	C++
 	[Inline Frame] Qt6Qml.dll!QQmlPropertyData::readPropertyWithArgs(QObject *) Line 359	C++
 	[Inline Frame] Qt6Qml.dll!QQmlPropertyData::readProperty(QObject *) Line 353	C++
 	Qt6Qml.dll!loadProperty(QV4::ExecutionEngine * v4, QObject * object, const QQmlPropertyData & property) Line 142	C++
 	Qt6Qml.dll!QV4::QObjectWrapper::lookupGetterImpl<unsigned __int64 <lambda>(void)>(QV4::Lookup * lookup, QV4::ExecutionEngine * engine, const QV4::Value & object, bool useOriginalProperty, QV4::Lookup::getterQObject::__l2::unsigned __int64 <lambda>(void) revertLookup) Line 274	C++
 	Qt6Qml.dll!QV4::Lookup::getterQObject(QV4::Lookup * lookup, QV4::ExecutionEngine * engine, const QV4::Value & object) Line 417	C++
 	Qt6Qml.dll!QV4::QObjectWrapper::virtualResolveLookupGetter(const QV4::Object * object, QV4::ExecutionEngine * engine, QV4::Lookup * lookup) Line 950	C++
 	Qt6Qml.dll!QV4::Moth::VME::interpret(QV4::JSTypesStackFrame * frame, QV4::ExecutionEngine * engine, const char * code) Line 745	C++
 	Qt6Qml.dll!QV4::Moth::VME::exec(QV4::JSTypesStackFrame * frame, QV4::ExecutionEngine * engine) Line 560	C++
 	Qt6Qml.dll!QV4::Function::call(const QV4::Value * thisObject, const QV4::Value * argv, int argc, const QV4::ExecutionContext * context) Line 101	C++
 	Qt6Qml.dll!QQmlJavaScriptExpression::evaluate(QV4::CallData * callData, bool * isUndefined) Line 278	C++

**Comment by wizofaus** [comment]
Probably this https://github.com/musescore/MuseScore/pull/23159/files ?

**Comment by bkunda** [comment]
@RomanPudashkin @cbjeukendrup I can also reproduce this in today's nightly.
Would be good to fix this as soon as possible. Thank you!

**Comment by cbjeukendrup** [comment]
I'll fix it
