### ISSUE TITLE
MuseScore crashes to desktop when pressing ESC whilst picking a screen color in the color picker

### ISSUE THREAD

**Issue by nCuky** [musescore/MuseScore#23208]
### Issue type
Crash or freeze

### Intro
I originally reported this bug [in the forums](https://musescore.org/en/node/365116). @Jojo-Schmitz [asked](https://musescore.org/en/node/365116#comment-1245923) me to report it on GitHub, so here I am.

**Thank you very much!**

### Issue type
Crash

### Bug description
When trying to Pick a Screen Color, in the Color Picker, then pressing the ESC key without selecting any color, MuseScore crashes and closes, without any error message.

**Explanation:**
I want to pick a Fill Color for a Staff Text box in my score.
I go to its properties, and click "Fill Color". The color picker pops up.
I click "Pick a screen color". The cursor changes to a big "+" sign, for picking any color on the screen. Also, beneath the "Pick Screen Color" button a notice appears, saying: "Cursor at xxx yyy; Press ESC to cancel".
I regret, I don't want to pick any color - I want to cancel. I click ESC, the "+" cursor stays as it is (I can still move the cursor freely), but something weird happens: In the "Properties" palette, most of the buttons disappear, and after 1-2 seconds the whole MuseScore app crashes and closes without any message.

### Steps to reproduce

1. Open any score.
2. Add a Staff Text and click it.
3. In the properties sidebar click "> show more", then click "Fill color".
4. In the color picker, click "Pick Screen Color".
5. Press ESC on your keyboard.

### Severity
Minor.

### Score file:
[staff text color picker crash.mscz](https://musescore.org/sites/musescore.org/files/2024-06/staff%20text%20color%20picker%20crash_1.mscz)

### Screenshots/Screen recordings
https://github.com/musescore/MuseScore/assets/25561013/3aab72eb-55e3-4143-a815-c17d277ecb67 (video has no audio because audio is not needed)

### MuseScore Version
4.3.1-241490900

### Regression
I don't know

### Operating system
Windows 10

### Additional context
**Log File:** [MuseScore_240610_213213.txt](https://musescore.org/sites/musescore.org/files/2024-06/MuseScore_240610_213213_1.txt)

MuseScore Studio version (64-bit): 4.3.1-241490900,
revision: [026c26b](https://github.com/musescore/musescore/commit/026c26b)

OS:			Windows 10 Pro 
Version:		22H2
OS build:		19045.4412
Architecture:	x86_64
System type:	64-bit operating system, x64-based processor

Processor:	AMD Ryzen 7 2700X Eight-Core Processor, 3.70 GHz
Installed RAM:	32.0 GB
GPU:		NVIDIA GeForce RTX 4070 Ti
Drive:		Hard-disk drive

**Comment by wizofaus** [comment]
Reproduced, and happens any time you access the "Pick a screen color" option then press Esc. Triggers something in QColorDialog::getColor( ), almost seems to be a Qt issue, but I'm assuming there's a workaround.

**Comment by wizofaus** [comment]
Have a fix, that ensures keyboard navigation/shortcuts (including ESC) work correctly while color selection dialog is displayed (regardless of whether you're in "Pick a color" mode).
