### ISSUE TITLE
Hairpins to extend to next dynamic, if one occurs before the end target

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#23210]
Currently, a hairpin attached to a single note will extend to the next note or rest, e.g.

![image](https://github.com/musescore/MuseScore/assets/20604032/f4ce1c97-cda5-404e-8d43-d3d36af00a6f)
![image](https://github.com/musescore/MuseScore/assets/20604032/102ed0ae-3fa8-4b5d-a6e1-a7fb746bae0f)

We can now have dynamics (dynamics, cresc/dim lines, hairpins) in the _middle_ of notes though; in these cases it would be nice if a hairpin would extend to the position of the dynamic (assuming that both dynamic and hairpin are applied to the same voice(s)).

So, this
![image](https://github.com/musescore/MuseScore/assets/20604032/4e533df4-a512-4f8a-bc16-ad77823fa2e1)
would become this
![image](https://github.com/musescore/MuseScore/assets/20604032/cc80431f-2169-4e4a-8033-7374ee747ab2)
(and not this, which we currently get)
![image](https://github.com/musescore/MuseScore/assets/20604032/f1004657-34c4-4a66-a5cc-fa2252592b8d)

Presumably this could be generalised to work over ranges; so adding a < to this
![image](https://github.com/musescore/MuseScore/assets/20604032/051057f6-9fc3-458f-8aa8-e39937b877ef)
would actually produce this
![image](https://github.com/musescore/MuseScore/assets/20604032/c2c69666-6be9-47aa-942e-cf566c9b2a9d)
unless this is considered perilous(?)

**Comment by wizofaus** [comment]
I would think if you only select a single note (and certainly a range) and apply a hairpin, it should only cover the sounding range that's selected.  Tied notes are obviously a bit of special case, so the proposed change adding a *p* to a whole note tied to the next I wouldn't necessarily mind, but if it weren't tied then I definitely wouldn't expect it to (certainly if there any intervening rests before the next dynamic mark).  But maybe you should be able to select a the *p* and add a hairpin?
