### ISSUE TITLE
Anchor lines not shown when moving dynamics

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#23211]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When moving dynamics around using Shift+Left/Right, the purple anchor line which indicates the position to which it attached should be shown; currently it is not.

(Compare the behaviour of hairpins being moved in the same way, or all items - including dynamics - when dragged with the mouse. The line is shown in all these situations.)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/20604032/9fa570b7-6ab0-4451-bce5-1eb391a89da2

### MuseScore Version

master (OS: Artix Linux, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241640931)

### Regression

No.

### Operating system

Linux / any

**Comment by SteveBlower** [comment]
Is this also relevant #12844?

**Comment by MovableFormula** [comment]
This should be fixed here I think https://github.com/musescore/MuseScore/pull/23046

**Comment by wizofaus** [comment]
I definitely observed this - only in master right? Didn't report because I assumed the feature just wasn't finished yet.

**Comment by oktophonie** [comment]
@SteveBlower Indeed - actually I'll just close this issue as it's basically a duplicate of yours (just with added anchor-i-ness).
@MovableFormula Unfortunately not - I logged this to keep track of it as a remaining piece of this for us to do.

**Comment by wizofaus** [comment]
Actually I realised I misread, I thought this was in reference to the new feature to allow you to drag spanners to various "time anchor" points in a measure. Which wasn't working yet for text-based dynamic indications yet either last time I checked.
