### ISSUE TITLE
Power cycle (switchover to battery backup) not handled properly in musescore

### ISSUE THREAD

**Issue by sheetsofsound** [musescore/MuseScore#23221]
### Issue type

Crash or freeze

### Bug description

Here's a quirk for you. I have my system on a UPS so I don't lose data. I had musescore open and was editing a file. Power shutdown and musescore immediately closed (without prompting) although the computer. Fortunately, I save periodically so I only lost a few minutes worth of changes. About 10 minutes later, power cycled again and again musescore immediately shutdown and I lost a few minutes worth of changes.

No other program shut down. I typically have 4-5 editors open. Photoshop, reaper, fret diagram2, word, etc. In both cases, only musescore shut down. Windows allows you to call a kernal function to register for events such as this
RegisterPowerSettingNotification()

I'm guessing musescore isn't handling the power cycle switch over to backup properly.

Anyone ever run into this? 

### Steps to reproduce

have computer on battery backup (UPS)
run musescore, make some changes, do not save
Turn off power source, allowing switchover to UPS
Musescore will close

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.1-241490900, revision: github-musescore-musescore-026c26b

### Regression

I don't know

### Operating system

windows 11

### Additional context

n/a

**Comment by cbjeukendrup** [comment]
Could you export the diagnostic files from within MuseScore, by doing Diagnostic > Save diagnostic files, and then upload the resulting ZIP file here? That might contain useful information.  

I would guess that this might have to do with audio: MuseScore allegedly still sometimes crashes when (dis)connecting audio devices, and the power shutdown might have a similar effect. But that is only a quite uneducated guess.

**Comment by zacjansheski** [comment]
Closing: No reply
