### ISSUE TITLE
Instruments playing at incorrect dynamics and flickering

### ISSUE THREAD

**Issue by meatexe** [musescore/MuseScore#23242]
### Issue type

General playback bug

### Bug description

Instruments using the muse sounds and soundfonts will play at incorrect dynamics at random parts of a song, for example when an instrument could be doing a crescendo to a forte . And it will start the next note at a forte when it is finished but then immediately go down to a mezzo-piano/piano for the next note, or the opposite for softer dynamics

### Steps to reproduce

I've tried to reproduce it but I haven't gotten a solid way to do it, although it seems to happen when a lot of instruments are playing at once
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -- - - - - - - - - -

1. Open [Example.zip](https://github.com/user-attachments/files/15871156/Example.zip)
2. Play Alto Sax at mm17

(also see [comment](https://github.com/musescore/MuseScore/issues/23242#issuecomment-2168492950), [comment](https://github.com/musescore/MuseScore/issues/23242#issuecomment-2173402651) )

### Screenshots/Screen recordings

 both of these where using the muse sounds but I still got the same result using soundfonts such as MS Basic

https://github.com/musescore/MuseScore/assets/139741941/38b086b9-7966-43ae-8567-71b3c60bdadb

https://github.com/musescore/MuseScore/assets/139741941/cd53c5a5-87d7-468a-b74f-2158557f092a

### MuseScore Version

Musescore Studio - 4.3.2.241630831 Muse Sampler - 0.6.3.196

### Regression

Yes, this used to work in a previous version of MuseScore 4.x
Regression occurred between 4.3.0 and 4.3.1

### Operating system

Windows 11 I'm not to sure about another OS

**Comment by bkunda** [comment]
Do you get the same results if you change the buffer size?

**Comment by bkunda** [comment]
Also could you please attach the scores? Thanks!

**Comment by meatexe** [comment]
> Do you get the same results if you change the buffer size?

I don't know how to change the buffer size

**Comment by zacjansheski** [comment]
To change buffer size:

Edit>Preferences>I/O
Default is 1024

I haven't been able to reporduce these issues from scratch.  Maybe you can share a score that has the issue?  You can do so here as a .zip file

**Comment by meatexe** [comment]
> Also could you please attach the scores? Thanks!

https://drive.google.com/drive/folders/13TcVuzjECZ9DAti5PBnrCI1tT3X1T5l3?usp=sharing

**Comment by zacjansheski** [comment]
Confirmed, issue remains when changing buffer size

**Comment by zacjansheski** [comment]
Looks like a regression occured between 4.3.0 and 4.3.1
Open the attached MusicXML file:

[Example.musicxml.zip](https://github.com/user-attachments/files/15841596/Example.musicxml.zip)

Play Alto Sax at mm17
In 4.3.0 - stable dynamics
In 4.3.1 - Dynamics get suddenly louder in the middle of the bar

**Comment by zacjansheski** [comment]
I am continuing to investigate this.  The cause seems to have something to do with the drumset 2 part.  Deleting that part makes the playback issue go away, but deleting the drumset 2 music in that section doesn't fix the issue.   Can you think of anything unusual about the drumset 2 part?


https://github.com/musescore/MuseScore/assets/69917893/45eb98dc-7a44-4c18-a712-1a91685b7594

**Comment by DmitryArefiev** [comment]
Checked on my side. Yes, I see it's related to one measure repeats in **Drum Set 2** part. But you need to reopen the score to get the effect:

https://github.com/musescore/MuseScore/assets/90187801/71f60c24-3390-465f-87bc-73e3d0dccb5f

**Comment by zacjansheski** [comment]
Blipping/odd dynamics reproducible from scratch using various dynamics and measure repeats

https://github.com/musescore/MuseScore/assets/69917893/18fd57a0-6a68-403e-b766-8f41f1053501
