### ISSUE TITLE
Workaround for Master Linux terminal error: wl_proxy_marshal_flags

### ISSUE THREAD

**Issue by TeeDeeY** [musescore/MuseScore#23254]
### Issue type

Crash or freeze

### Bug description
Not a high priority crash issue!  The program runs in the GUI.

This is just to describe a quick workaround (in Ubuntu terminal) in case someone sees a crash and this message:
/tmp/.mount_MuseScLQ0XF7/bin/mscore4portablenightly: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags

When running the appimage in the terminal, there can be a warning that "QT_QPA_PLATFORM=wayland"  is not set.

Do not do that! Or, you can get the above error crash.  Confirmed it crashes in Ubuntu 24.04 as well.   

Solution is to not " $export QT_QPA_PLATFORM=wayland " as suggested in the warning message.

This is running in the terminal, so this message is mostly for people running in debug.  This is to document the issue, in case someone set it up and forgot about making the setting earlier.

"$export QT_QPA_PLATFORM=" undoes it.

I don't want figure out the correct method at the moment (finding libEGL_mesa.so.0, etc.).

### Steps to reproduce

See above.  Don't set the export in a .bash_aliases file or similar.

### MuseScore Version

This was reproduced in two different June nightly master 4.4s. 

A different error shows up in 4.2.1.  

### Regression

I don't know

### Operating system

Ubuntu 22.04

### Additional context

On the command line, error shown is:
/tmp/.mount_MuseScLQ0XF7/bin/mscore4portablenightly: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags

**Comment by TeeDeeY** [comment]
A workaround is listed.

**Comment by MarcSabatella** [comment]
The workaround is only good if your environment is otherwise set up to run in X11 mode (at least that's my understanding of when it works versus doesn't).  On my system, that environment variable was never set in the first place, and I get the same wl_proxy_marshal_flags error.  The way I have found to avoid it is to explicitly set QT_QPA_PLATFORM to "xcb".  Or otherwise force MuseScore Studio to run in X11 mode.
