### ISSUE TITLE
Portamento glissandos are completely broken in almost every way (not Muse Sounds related)

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#23253]
### Issue type

General playback bug

### Bug description

There are quite a few things wrong with the "portamento" style glissando line.
First of all, when you select a note with a portamento glissando on it, the preview sound is the entire glissando, usually lasting 5 seconds or more, instead of the preview sound just being the note.
Second, portamento glissandos that start on a tied note that also ties to a note afterwards currently do nothing at all. The only way to get the glissando to sound is if it starts at the start of the note.
Third, the top note of the glissando is played like normal, with an articulation and everything, when there should be no articulation at all at the top, just bending up to the top note and staying there, the same as the bends currently work.
Fourth, the playback of the portamento glissando is not smooth. Rather, it currently goes a half step up at a time, with a small barely audible quarter tone note just before it get up the half step. It plays back as this:
![image](https://github.com/musescore/MuseScore/assets/21023353/832bfea8-e719-40a6-a219-0d90d3d37b4d)

### Steps to reproduce
1:
1. Put a portamento glissando on a note
2. Click on it

2:
1. Input 3 notes tied together
2. Add the portamento glissando to the second of the 3
3. Playback and notice that the glissando is completely ignored

3:
1. Input a portamento glissando
2. Playback and notice that the top note is rearticulated

4:
1. Input a portamento glissando (the longer, the more noticeable)
2. Playback and hear it basically do a chromatic glissando

### Screenshots/Screen recordings

1:

https://github.com/musescore/MuseScore/assets/21023353/7d1bd401-3fa8-41ae-a48d-1e883bdbec9c

2:

https://github.com/musescore/MuseScore/assets/21023353/1816125e-d310-49ff-9e6b-2fa280309701

3:

https://github.com/musescore/MuseScore/assets/21023353/4042de56-b333-4499-b39e-d9ec693f3fe8

4:

https://github.com/musescore/MuseScore/assets/21023353/1fb9bb1d-bbb0-487e-b044-d3bcad8c53d5

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I don't know

### Operating system

Reported on Windows 11

### Additional context

This type of glissando has never really worked 100% correctly, but I don't know what specific issues arose when
Currently, this type of glissando is completely useless to me (especially because of #4)
This is also not a Muse Sounds related issue, I used a soundfont when I discovered this and I imagine it probably does exactly the same thing with VSTs.
Perhaps the code for the guitar bends can be reused for these in some way, as the guitar bends sound way way better than these glissandos do and have basically no issues

**Comment by LucySuccubus** [comment]
I think the source of this issue is that portamento glissando's playback property is chromatic. Have you tried manually setting the playback setting to portamento to see if it improves?

**Comment by erinic04** [comment]
That is the portamento setting on the glissando, which is the massive problem.

**Comment by wizofaus** [comment]
It definitely occurs using "portamento", and with MS Basic too. I was going to report the same issue.

**Comment by RustyBust** [comment]
I noticed this as well when writing in a portamento in a very slow tempo. 
Also, sometimes when you write very fast portamenti it will keep going even after the glissando ends.
Additionally, when you click on a note with portamento it will play the glissando out.

**Comment by bkunda** [comment]
Just looking through this now, there are too many issues of varying importance to be helpfully contained in a single issue. 

So I am going to close this and replace it with better contained issues. 

As I see it: 

1. Preview mode plays the portamento on initial note selection: this seems to apply only to soundfont, and only if the portamento playback option is selected. 

2. Portamento does not play from a tied note: affects Muse Sounds only

3. Arrival note of a portamento is re-articulated: affects soundfont only

4. Evenness over long notes: this is something that should be fixed properly with a user-defined control (see, for example, the widget in Properties we now have for guitar bends). Muse Sounds, for example, will hold the first note and slide only towards its end (this aligns with conventional performance practice, but isn't necessarily helpful for more modern music). MS Basic – on the other hand – tries to evenly distribute the portamento over the full length of the note, but without much evenness (it sound stepped). Perhaps using pitch-bend might improve this, but it wouldn’t necessarily apply to every instrument (e.g. it wouldn't make sense for a flute to pitch bend evenly over a long, sustained, period of time).

**Comment by bkunda** [comment]
See also: https://github.com/musescore/MuseScore/issues/20925
