### ISSUE TITLE
Add ability to add lyrics to grace notes

### ISSUE THREAD

**Issue by nCuky** [musescore/MuseScore#23282]
### Your idea

Hello team. 
Please add the ability to type **lyrics directly under grace notes**.
Currently, there is no way to "assign" a single lyric/syllable to a grace note. When typing the lyrics and moving the cursor between notes, the "lyrics-typing-box" (I don't know the correct name for it) moves to be under the next **regular** note, skipping the grace notes in between.

### Problem to be solved

It would allow to assign lyrics/syllables to grace notes themselves, not just to regular notes.

### Additional context

This issue is based off the MuseScore.org [forums issue #44411](https://musescore.org/en/node/44411) by [ABL](https://musescore.org/en/user/11921), which mentions the following previous issues:
- [Lyrics under grace notes](https://musescore.org/en/node/332679)
- [Adding Sticking To Grace Notes in Percussion Music](https://musescore.org/en/node/325339)
- [Lyrics on fioritures](https://musescore.org/en/node/277352)
- [Lyrics underneath a grace note?](https://musescore.org/en/node/183341)

@Jojo-Schmitz [asked me](https://musescore.org/en/node/44411#comment-1178273) to report this on Github, so here I am.

**Comment by Dima-S-Jr** [comment]
Isn't that what it says [here](https://github.com/musescore/MuseScore/issues/18484#issuecomment-1627626657)?

**Comment by Jojo-Schmitz** [comment]
Yes, #18484 is certainly related

**Comment by Jojo-Schmitz** [comment]
And I didn't check for an existing one, my bad
