### ISSUE TITLE
MuseScore Studio crashes upon inserting Text Frame after cross-stave notes with slur

### ISSUE THREAD

**Issue by basaigh** [musescore/MuseScore#23294]
### Issue type

Crash or freeze

### Bug description

This only appears to happen in large scores, if there are other criteria I haven't been able to find them.

### Steps to reproduce

*UPDATE* see @zacjansheski 's comment for minimal reproduction steps

1. Open a score with cross-stave notes with a slur
2. Add a text frame after cross-stave notes with a slur
3. Observe MuseScore Studio crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/53559772/8f175e06-a394-44af-8e04-9f842bd6534e

### MuseScore Version

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241700506, revision: github-musescore-musescore-d60cca9

### Regression

Yes, this used to work in a previous version of MuseScore 4.x
Works in 4.3.2, crashes in 4.4

### Operating system

Windows 11

### Additional context

[Music from FROZEN.zip](https://github.com/user-attachments/files/15892940/Music.from.FROZEN.zip)

**Comment by zacjansheski** [comment]
[AppendTextFrameCrash.zip](https://github.com/user-attachments/files/15915535/AppendTextFrameCrash.zip)


I have reproduced with a few other scores,  I have even larger scores that don't crash, still investigating

**Comment by zacjansheski** [comment]
It has to do with the harp part, no crash after deleting

The minimal way to reproduce the crash is to add a text frame after two cross-stave notes with a slur

1. Open "Grand Staff" template
2. Write two cross-stave notes with a slur
3. Add a text frame after the notes
4. Crash


https://github.com/musescore/MuseScore/assets/69917893/2a6df560-8891-41ec-b8d0-7abc5ddd13e6

**Comment by Jojo-Schmitz** [comment]
I can't reproduce with that, in lasted code from master

**Comment by Jojo-Schmitz** [comment]
And I believe to have found the culprit, a nullptr deferefences in `MeasureBase::top()`
