### ISSUE TITLE
[Task] Align fretboard diagram feature with HL engraving requirements

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#23295]
This will introduce changes and additions to the properties and style settings of the Guitar fretboard element.

See confluence page with same name as this issue for more detail on requirements. And message me for the Figma link!

<img width="958" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/ec403bdb-722f-4f25-9f5f-1e03ae2e64b8">

**Comment by Tantacrul** [comment]
I can't recall if we let the user save chord diagrams to be reused later?

At some point we'll need to discuss the general idea of being able to save styles and other engraving elements as profiles, which would allow users to quickly create new scores without having to recreate these kinds of elements.

I've did a lot of thinking about this two years ago. Might be a good idea to start chatting through it.

Nice to see this improvement though!

**Comment by Jojo-Schmitz** [comment]
> I can't recall if we let the user save chord diagrams to be reused later?

We do, sort of, by adding them toi a palette

**Comment by bkunda** [comment]
> At some point we'll need to discuss the general idea of being able to save styles and other engraving elements as profiles, which would allow users to quickly create new scores without having to recreate these kinds of elements.

We do already have Format > Save Style and Format > Load Style. This preserves all the Style settings, allowing the user to load them in other scores. 

> I can't recall if we let the user save chord diagrams to be reused later?

Probably worth mentioning that the current task is only the MVP for this feature. The next step will include a vastly improved fretboard diagram management system, allowing the user to store and manage hundreds of chord symbols and add/swap them out easily from within the score (without needing to use the palettes).
