### ISSUE TITLE
Sforzando crash

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#23290]
[Smoke_1232024.zip](https://github.com/user-attachments/files/15891637/Smoke_1232024.zip)

Opening this score crashes MuseScore Studio
The crash has to do with how Sforzando is loaded

Issue is in Master (As of writing this, I have only reproduced in latest PR builds on Windows)

Crash report:
[OpenFileCrash.zip](https://github.com/user-attachments/files/15888097/OpenFileCrash.zip)

_Originally posted by @zacjansheski in https://github.com/musescore/MuseScore/issues/23281#issuecomment-2176251541_

**Comment by zacjansheski** [comment]
@RomanPudashkin This is an slippery one to me, but I understand you are able to reproduce.
https://github.com/musescore/MuseScore/pull/23281#issuecomment-2176412210
Assuming we see the same issue as a regression, it should be fixed for 4.4

**Comment by DmitryArefiev** [comment]
@zacjansheski Can you check it again please? I **can't reproduce** with the attached score on Win/Mac

**Comment by zacjansheski** [comment]
Not reproducible in master
