### ISSUE TITLE
Viola sounding F# as well as G# when only G# present

### ISSUE THREAD

**Issue by JaimeShirazi** [musescore/MuseScore#23319]
### Issue type

Muse Sounds bug

### Bug description

This score has played back incorrectly ever since I first installed MuseScore 4 and the problem persists to this day. Sorry for not reporting this sooner if this is undocumented, I just wasn't familiar with GitHub until this year. This is a transcription of a really beautiful moment from zelda breath of the wild, and really demonstrates the quality of some of the orchestral samples in Muse Sounds in my opinion, if not for this one weird playback quirk (and a number of other problems with the transcription that I only see/hear now in retrospect, with more experience)

### Steps to reproduce

1. Download the musescore file from [here](https://drive.google.com/file/d/1w5jlWBlXqL9bGpOc52-qpAzWDzMVytMv/view?usp=sharing) or unzip the attached musescore file 
[Viola Playback Issue.zip](https://github.com/user-attachments/files/15921555/Viola.Playback.Issue.zip)
2. Play back the score with the correct corresponding Muse Sounds
3. Observe the Viola part in the 4th bar, on beat 3.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/73824309/b575f24a-9125-4240-a696-6d13b8a7504e

### MuseScore Version

4.3.2.241630831

### Regression

No.

### Operating system

Windows 11

### Additional context

This was originally a sibelius score that I ported over. In fact, I was also able to dig up the musicxml file I'm pretty sure I would've used to import it. [Here that is,](https://drive.google.com/file/d/1WVJBnGvdDB6XjzgB8U1-4QlxC-2Dj3Dc/view?usp=sharing) or you can download this file on github below (had to zip it because of github's supported file formats, use the drive link if you don't want to be unzipping on your PC)
[daruksMettle.zip](https://github.com/user-attachments/files/15921582/daruksMettle.zip)
Just to be extremely painfully detailed in case it ends up being useful for whatever reason:
Created on 15th of Feb 2023 with Sibelius 2020.9 (the edition that locked you into having 16 instruments, and cost hundreds of dollars 😡)
Ported over to MuseScore with musicxml on the 24th of July 2023 (I don't remember what version, sorry. Judging by the other "date created" metadata of the files in my MuseScore 4 scores folder though, this would've been the day I first installed MuseScore 4, so probably whatever was the latest version at the time).
Sorry if this was a known issue with the MuseScore version that was used to import it!

**Comment by sampleeditor** [comment]
Resolved with Muse Strings 0.4.14 (beta)
