### ISSUE TITLE
brew doctor warning for /usr/local/lib/libMuseSamplerCoreLib.dylib

### ISSUE THREAD

**Issue by pointmatic** [musescore/MuseScore#23328]
### Issue type

Other type of issue

### Bug description

I'm working on some software development on my new Mac, and reinstalling my environment. I'm on MacOS Sonoma 14.5 with M3 Max. 

Obviously, Homebrew is a necessary tool, and when I run `brew doctor` I get the following warning. 

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libMuseSamplerCoreLib.dylib
```

I like a clean environment with no warnings. I installed MuseScore and MuseHub with all the defaults. 

Any thoughts here?

### Steps to reproduce

1. Install MuseScore / MuseHub on MacOS Sonoma
2. Install [HomeBrew](https://brew.sh/) from the MacOS terminal
3. run the `brew doctor` command from the MacOS terminal

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

### Regression

I don't know

### Operating system

MacOS Sonoma 14.5

**Comment by cbjeukendrup** [comment]
This is normal: MuseSampler (the engine behind MuseSounds) is installed to /usr/local/lib. There is no rule that says that HomeBrew is the only program that is allowed to write to this directory, so it should be fine. (If HomeBrew needed such a rule, they should have chosen their own location.)

So, this HomeBrew warning is nice to detect unexpected situations, but this case is completely expected :)

**Comment by pointmatic** [comment]
Thanks, @cbjeukendrup. And a glance at the [Homebrew Manpage](https://docs.brew.sh/Manpage#doctor-dr---list-checks---audit-debug-diagnostic_check-) clarifies that `brew doctor` is for the maintainers to troubleshoot stuff. 

```
Please note that these warnings are just used to help the Homebrew maintainers with debugging if you file an issue. If everything you use Homebrew for is working fine: please don’t worry or file an issue; just ignore this.
```

This is a side effect of MacOS not having a proper package manager.
