### ISSUE TITLE
Custom line thickness changes upon reopening a score

### ISSUE THREAD

**Issue by cnmfernandogarciaalvarez** [musescore/MuseScore#23333]
### Issue type

Opening/saving issue

### Bug description

I am using lines to notate notes being held for a certain number of seconds. I stablished said line's thickness at 0.5. After saving, closing and reopening the file, all lines of this kind increased by 0.12 points, thickness keeps increasing after saving, closing and reopening again.

### Steps to reproduce

Place a "Line" object from the "Lines" pallete, go to its Properties, increase the tickness value, save and close, open again.

### Screenshots/Screen recordings

<img width="1047" alt="Captura de Pantalla 2024-06-22 a la(s) 12 09 29" src="https://github.com/musescore/MuseScore/assets/173568299/a8a5f008-4d44-4a16-9882-b71a0c0eb812">
<img width="1012" alt="Captura de Pantalla 2024-06-22 a la(s) 12 11 46" src="https://github.com/musescore/MuseScore/assets/173568299/b0bb9f47-4f6d-4b69-bb25-942211fa52fa">

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

### Regression

I don't know

### Operating system

OS: macOS 12.7, Arch.: x86_64

### Additional context

This also happen with any line's style, straight, dashed and dotted.

**Comment by cnmfernandogarciaalvarez** [comment]
<img width="304" alt="Captura de Pantalla 2024-06-22 a la(s) 12 08 27" src="https://github.com/musescore/MuseScore/assets/173568299/334b0bf9-9ba8-4167-a5da-d1e9442a3b42">

**Comment by oktophonie** [comment]
Cannot reproduce (Windows, 10 July nightly)

**Comment by MarcSabatella** [comment]
In the past we’ve seen issues like this if the staff scaling property is set to something other 100%.  If I set the staff scale to 125%, I see this exact behavior in 4.3.2mas well as the latest nightly build of master.

@cnmfernandogarciaalvarez if you’re using staff scaling to make the score larger, be aware that normally that should be done through Format / Page settings.  The scaling in the staff/part properties is means more for creating different size staves within the same score, not for general scaling of the entire score.  And it is indeed somewhat buggy.

If you are seeing this in a score that *doesn’t* have a custom staff scaling set, please ZIP and attach it.
