### ISSUE TITLE
Crackling/stuttering audio when mixing dynamic and fast notes

### ISSUE THREAD

**Issue by joaoe** [musescore/MuseScore#23335]
### Issue type

General playback bug

### Bug description

This is quite weird to explain so I'll let the recording explain by itself.
https://www.youtube.com/watch?v=atBoBiZwPLM 

Basically, as far as I understand, there are two instruments, one has fast notes, the other long notes with dynamics. The fast note instrument will interfer with the dynamics of the slow one, plus cause the sound to stutter.

In the recording
1. notice how the forte chord is immediatelly dampened and all other chords are played much lower. That does not obey the dynamics markings.
2. if I add a crescendo with the forte, then the stuttering starts and will keep on going while the other instrument has the 8th notes.
3. if the first instrument with the 8th notes is deleted, the bug is gone.

### Steps to reproduce

1. download musescore file [bug_dynamics.mscz.zip](https://github.com/user-attachments/files/15942121/bug_dynamics.mscz.zip)
2. give it a play 

### Screenshots/Screen recordings

https://www.youtube.com/watch?v=atBoBiZwPLM 

### MuseScore Version

4.3.2-241630831

### Regression

I don't know

### Additional context

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

**Comment by MarcSabatella** [comment]
I believe this is a known issue with measure repeats specifically - see https://github.com/musescore/MuseScore/issues/23242

It is already fixed for the next update.

**Comment by joaoe** [comment]
@MarcSabatella Thanks. I noticed this was a regression from 4.2 and affects many scores.

**Comment by joaoe** [comment]
Just tested in the nightly build. It is fixed. Excellent.
