### ISSUE TITLE
More usable default drum kit voicing

### ISSUE THREAD

**Issue by Koopa1018** [musescore/MuseScore#23331]
### Your idea

Would greatly appreciate if, when writing drum parts, kick+snare defaulted to sharing a voice, and hi-hat defaulted to a separate voice.

### Problem to be solved

The short answer is, the current default voice arrangement makes common drum parts a pain to write, because it violates the note-writing logic present in the rest of MuseScore.

The long answer is:
Consider this basic backbeat.
![image](https://github.com/musescore/MuseScore/assets/29995463/8d8ad107-3413-4e84-94a8-acacf163a642)
Observe that the kick and snare alternate beats, while the hi-hat runs over top in a continuous stream of 8th notes. Most other drum patterns are simple variations of this one.

My experience of trying to write this with the common pattern is usually as follows:
- add first hit (kick)
- add second hit (snare)
- no that's not what I wanted
![image](https://github.com/musescore/MuseScore/assets/29995463/dbb2269b-7682-49f2-bbf3-62ec8b572356)
- delete snare and manually add on the next beat
- write only the snare part, ignoring kick hits (counterintuitive)
- fill in the kicks
- score now looks like this:
![image](https://github.com/musescore/MuseScore/assets/29995463/90822d1f-abb4-4a27-be2d-bf4e80618734)
- begin writing hi-hat part
- the hi-hat ate my snare drum
![image](https://github.com/musescore/MuseScore/assets/29995463/1b7c4e19-95a6-4ebe-b1b0-b50405ffacf9)
- finish hi-hat part, ignoring the vanishing snare drum hits
- try to rewrite snare part
- the snare drum ate my hi-hat
![image](https://github.com/musescore/MuseScore/assets/29995463/23d7736f-7e60-416a-b3e8-fcebb3668001)
- undo, then take pains to re-add each snare hit as a chord note this time
- thank goodness I'm done
- what do you mean the next section has a new drum pattern

Compare that to the workflow for writing melodic lines:
- add the first note (G)
- add the second note (A)
- add the third note (C)
- add the fourth note (A)
- dotted-quarter duration
- add the fifth note (E)
- flip the fifth note up an octave
- add the sixth note (E)
- ...
- 👍

And when I use a modified drumset where kick and snare share a voice and hi-hat has its own voice:
- add first hit (kick)
- add second hit (snare)
- add third hit (kick)
- add fourth hit (snare)
- eighth duration
- add hi-hat hit 1 & 2 &...
- ...
- 👍

(buut now you've gone and added two _extra_ drum kit instruments, so now I have to maintain _three_ drumset files instead of one.)

### Prior art

Afraid I don't remember how Finale did it. It's been a hot minute since I last used that.

### Additional context

I am aware that what I'm asking for may not produce technically-correct drum parts, but @Tantacrul knows what putting technical correctness over usability did to Dorico 😈

**Comment by zacjansheski** [comment]
We have a plan for improving this experience.  I'm going to close this because it is not the right direction for us.

For your information:
"Hands up, feet down" is the most common way to notate.
"All in one voice" is the second most common.
"Cymbals up, drums down" is least common.

In other words, it would be better to put everything in one voice than do what you are suggesting.

We should make it easier to use all three and switch between them, since they are all accepted methods, but using "Hands up and feet down" as the default makes the most sense.

**Comment by Koopa1018** [comment]
Yeah...I figured you might say that. Hoped you would at least take note of the experience I was having, though.
(Incidentally, is there a place to submit UX complaints? I didn't see an option for it in the bug report menu, so I figured this was the next best thing.)

**Comment by zacjansheski** [comment]
To be clear, your experience is noted, but changing the default voicing isn't the way forward.

Feel free to share thoughts and discuss on the General Discussion forums https://musescore.org/en/forum/11  or Discord
