### ISSUE TITLE
Nightly Master 4.4 Linux crashes on third press of mixer button

### ISSUE THREAD

**Issue by TeeDeeY** [musescore/MuseScore#23347]
### Issue type

Crash or freeze

### Bug description

Press mixer button three times.  Program crashes. 

Use bar View/mixer three times.  Crashes program.  

### Steps to reproduce

New and prior scores.  See above.  

### MuseScore Version

4.4.0.241760505 rev 5203474

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 22.04

### Additional context

Works correctly on master from a few of days ago.  Rev 1c28ffe

Master from day before seems to be same and also crashes. 

Also, rev 88c99a3 crashes. 

Note: 1c28ffe had a bug in lyrics that was fixed in the updates that crash.  The lyrics bug showed a flash of the purple connector when entering lyrics.  The connector can be left behind after editing prior lyrics.

**Comment by cbjeukendrup** [comment]
Turns out to have the same cause as https://github.com/musescore/MuseScore/issues/23338
