### ISSUE TITLE
Staccato playback broken for Muse Sounds contrabass low B  

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23361]
### Issue type

Muse Sounds bug

### Bug description

Repeated low B staccato notes for Contrabasses do not play back correctly (generating some weird rhythmic pattern)

### Steps to reproduce

1. Create a new score using Contrabasses (section) with Muse Sounds
2. Enter 8 A2s (B on 2nd bottom line of staff), mark as staccato, then another measure the same, but with B2s
3. Play back with good quality speakers and/or headphones
4. Expected: you hear 8 evenly spaced staccato A's then 8 evenly spaced staccato B's
5. Actual: A's are fine, B's are played with some odd extra rhythms

### Screenshots/Screen recordings

[_Sample score_](https://musescore.com/user/7209246/scores/18736021/s/YCkW8M)

### MuseScore Version

4.3.1

### Regression

I don't know

### Operating system

Windows 11

### Additional context

In isolation it doesn't sound totally whacky, though it certainly doesn't sound like a real instrument playing - but in combination with other string parts it's bad enough that I have to resort to various tricks to get around it.

**Comment by bkunda** [comment]
Can you please provide a screen recording with audio so we can see immediately understand the issue?

**Comment by wizofaus** [comment]
@bkunda I've download latest nightly build and latest sampler and redownloaded Muse Strings (after some instruments had stopped working completely!), and this problem still persists. Can report via Muse Hub if you think it's more likely an issue there - it doesn't happen, for instance, with CineStrings solo contrabass.

**Comment by zacjansheski** [comment]
@wizofaus When an issue is library specific, it would be best to report via Muse Hub.

Since this is library specific I will close here.
