### ISSUE TITLE
Add Shortcut for Transposing a Note by Whole Tone

### ISSUE THREAD

**Issue by lhytmp** [musescore/MuseScore#23373]
### Your idea

Hello MuseScore Team,

I would like to suggest adding a feature that allows users to transpose selected notes by a whole or half tone along the scale of the current mode using a keyboard shortcut . Currently, we can only transpose notes by a semitone using the arrow keys. This feature would greatly improve the workflow for many composers and arrangers who frequently need to make such adjustments.

Thank you for considering this suggestion.

Best regards,
lhytmp

### Problem to be solved

Currently, we can only transpose notes by a semitone using the arrow keys.

### Prior art

Some apps allow users to transpose selected notes by a whole or half tone along the scale of the current mode using a keyboard shortcut .

**Comment by DaddyLudwig** [comment]
There actually already is a diatonic transposition shortcut if that’s what you’re getting at by whole tone, it’s Alt + Shift + Up or Down
