### ISSUE TITLE
Crash with Braille panel open: adding stave to instrument with a dynamic

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#23378]
### Issue type

Crash or freeze

### Steps to reproduce

1. In preferences, make braille panel visible
2. New empty score with a single-staff instrument (e.g. flute).
3. Add a dynamic (e.g. _**mp**_).
4. In the **Instruments panel**, expand the Flute and click "Add stave". Crash!

### Screenshots/Screen recordings

<img width="600px" src="https://github.com/musescore/MuseScore/assets/11011881/6cbe3ccc-30c9-4f98-9cd0-99d5eb1901c3"/>

### MuseScore Version

4.3 and latest nightly

### Regression

Yes, this used to work in MuseScore 4.1.1
Broken in 4.2.0

### Operating system

Windows 11

**Comment by zacjansheski** [comment]
I haven't reproduced on 4.3.2 MacOS
OS: macOS 14.4, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

**Comment by zacjansheski** [comment]
Also haven't reproduced on Windows 11 4.3.2

**Comment by zacjansheski** [comment]
It does crash with the braile panel open

**Comment by zacjansheski** [comment]
Diagnostic files

[BrailleDynamAddStaffCrash.zip](https://github.com/user-attachments/files/16017634/BrailleDynamAddStaffCrash.zip)

**Comment by zacjansheski** [comment]
Regression occured between 4.1.1 and 4.2.0
