### ISSUE TITLE
Tempo changes (accel. rit. etc. in the palette) should have the option to check or uncheck "play"

### ISSUE THREAD

**Issue by Lumi618** [musescore/MuseScore#23380]
### Your idea

I think we should be able to check or uncheck the "play" checkbox for these tempo controls found under the playback button in the properties tab, so that MuseScore will not attempt the tempo changes. 

### Problem to be solved

Currently, the automatic tempo changes using the accel, rit, etc in the palette don't always give you the result you want in your music, especially if you want the change to occur gradually. Being able to check or uncheck the "play" checkbox for these tempo controls would allow you to still have the nice looking accel., rit, etc. lines in the score, but you could control the tempo of the piece yourself using tempo markings.

**Comment by jeetee** [comment]
Possible workaround: use a system text line instead of a tempo line.

**Comment by MarcSabatella** [comment]
Or use the tempo change line but set the amount to 100%.  Arguably better in terms of MusicXML export, also any potential aligning features that might be implemented.  But yeah, being able to disable Play should be possible for anything that affects playback.

**Comment by Lumi618** [comment]
@MarcSabatella That was one of the first things I tried actually! It doesn't work because the tempo change line keeps returning to the starting tempo at the designated intervals it is supposed to change at, even if I have put my own tempo markings along the way.

**Comment by Lumi618** [comment]
@jeetee This does work, but If you have used other premade text in the palette, they won't match. I can't seem to find a way to make the system line "accel." bold, or bigger to match the premade ones, meaning I might have to change the other premade tempo markings to system lines as well to make them cohesive throughout the score.

**Comment by cbjeukendrup** [comment]
Might be resolved by #22890

**Comment by XiaoMigros** [comment]
It should be, going off what I tested and the changes made to `score.cpp`
