### ISSUE TITLE
'Minimum Tie Length' style setting incorrectly spaced

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#23388]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

![grafik](https://github.com/musescore/MuseScore/assets/116587995/75067319-f4eb-43e8-93c9-a3a92282f047)

### Steps to reproduce

1. Open Format/Style/Slurs & Ties

### MuseScore Version

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

Used to work correctly in previous 4.4 versions (perhaps Qt6 related?)

**Comment by nmu-nyasan** [comment]
I think this has been fixed by d9ee710729038309999a3c9b390d81f36b966a12, so this issue can be closed.
