### ISSUE TITLE
No Soprano Voice on Mixer

### ISSUE THREAD

**Issue by orkuun** [musescore/MuseScore#23382]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

Hello, I am using MuseScore Studio 4.3.2(x64) and MuseSound Manager Beta 1.1.0.587(x64) on Linux Mint operating system. I guess after the last MuseScore Studio update MS Studio can't find the soprano voice. I deleted the soprano in the folder containing the sounds, and then MS Manager noticed the absence and reinstalled the soprano. However, MuseScore Studio still cannot find the soprano voice. And I'm getting this bug in MS Studio 4.4.0 as well.

### Steps to reproduce

1. New Score
2. add Vocals/Soprano - Done
3. F10 (mixer)
4. and no MuseSound's Soprano voice 

### Screenshots/Screen recordings

![No Sop](https://github.com/musescore/MuseScore/assets/35005568/bc6c45c1-ef44-4d4e-88a2-4fa5a1ee2f6a)

### MuseScore Version

4.3.2, 4.4.0(ninghtly)

### Regression

I don't know

### Operating system

Linux Mint 21.3 Cinnamon

**Comment by MovableFormula** [comment]
Alt click the choir in musehub and uninstall it then reinstall.

**Comment by orkuun** [comment]
unfortunately alt+click (uninstall) doesn't work. So I manually deleted and reinstalled and it didn't work. MuseScore still doesn't see the soprano voice.

**Comment by MarcSabatella** [comment]
What specifically do you mean when you say Alt+click "doesn't work"?  Do you mean it doesn't uninstall, or that the uninstall was not effective in resolving the issue?

On some Linux systems, Alt+click doesn't work directly as that gesture is reserved by the OS apparently.  But you can still trick the system into allowing the operation by using Alt+Tab to switch to another window, then Alt+Tab back.  Now you'll have delete buttons you can click normally.
