### ISSUE TITLE
[Qt6] Unusable and very buggy menu bar in full screen (Windows only)

### ISSUE THREAD

**Issue by yukraya** [musescore/MuseScore#23399]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

The menu bar causes black screens when interacting with it in full screen.

I suppose the problem comes from the transition to qt 6.2.4. Exclusive full screen bug?

I specify that when I set musescore in full screen, it displays the "press alt z" nvidia popup then disappears. (we can't see it because of the black screen) This was not the case in the latest release of musescore (4.3.2). I also point out that doing 'alt z' freeze the entire screen and does not open the nvidia context menu. The only way to stop freezing is to alt tab or shutdown.

I tried disabling the NVIDIA context menu in the NVIDIA settings but the problem persists.

### Steps to reproduce

1. Lauch Musescore nightly build.
2. Set it to full screen.
3. Use the menu bar.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/50635001/e3927480-7cb6-457e-bbb8-2ff0e3b24011

### MuseScore Version

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241800505, revision: github-musescore-musescore-62c3c0e

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

I have a RTX 4060 with latest drivers.

**Comment by krasko78** [comment]
Similar issue for me with Windows 10 and AMD Radeon. On my machine I get a black screen only for a moment when switching between the menus. The menus don't open (are invisible actually) but if I hover the mouse over where the menus should be, they sometimes appear and sometimes disappear as I move the mouse over them, again with a flickering black screen for a fraction of a second. It seems that hovering the mouse over one submenu shows the menu along with the submenu, then moving the mouse down to the next or up to the previous submenu hides the menu, etc. Menu items that don't display submenus seem to be non-problematic per se but when moving the mouse from a non-submenu item onto a submenu causes the menu to disappear. So depending on the direction and what menu item you are coming from and landing on, the effect of submenus hiding and showing the menu can actually be reversed. It is fun. :)

**Comment by krasko78** [comment]
I also see the flickering black screen in full screen mode when any dialog / popup is shown, e.g. the "Do you want to save" dialog, or the Appearance popup in the Properties panel.

**Comment by cbjeukendrup** [comment]
There is a slight chance that has a connection to https://github.com/musescore/MuseScore/issues/22369

**Comment by DmitryArefiev** [comment]
@bkunda Confirm. This is a serious issue for users that prefer to work in full screen on Windows.

I can reproduce it on both my Windows laptops (with Intel and AMD graphics)

**Comment by cbjeukendrup** [comment]
I have some hope that this will be resolved by #23438, but I can't test that myself.

**Comment by DmitryArefiev** [comment]
Yeah, it's **much better**. The only minor issue I found is File, Edit tabs are blinking a little bit when moving mouse through Top menu:

https://github.com/musescore/MuseScore/assets/90187801/016b3335-9998-48f1-9587-3813dac80670

**Comment by cbjeukendrup** [comment]
Ah yeah. I think I've seen similar things in different places, also in other Qt apps. I wouldn't directly have an idea about what's causing that, but it's so minor that I doubt it's worth our time.

**Comment by DmitryArefiev** [comment]
Fixed in #23438

**Comment by krasko78** [comment]
Looks good but why does the title (to the right of the menubar) disappear in full-screen mode?

**Comment by cbjeukendrup** [comment]
Judging from the code, that's intentional, but personally I wouldn't know why. If it bothers you, feel free to open a new issue about this.
