### ISSUE TITLE
'Edit lyrics text style' button not working in Style > Lyrics

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#23393]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

In the new Lyrics styles for 4.4, the 'Edit lyrics text style' button should link the user to the 'Text styles' page of styles and land them on the 'Lyrics odd lines' style.

Currently, the button appears to do nothing. It does in fact select the 'Lyrics odd lines' style in the text styles page, but it doesn't actually navigate you to that page.

https://github.com/musescore/MuseScore/assets/20806406/5a693ae4-c663-4a3f-913b-4cecc390e3a5

### Steps to reproduce

1. Format > Style
2. Go to Lyrics
3. Click 'Edit lyrics text style'
4. It doesn't navigate to the 'Text styles' page

### MuseScore Version

4.4 master (June 28, 2024)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.5

**Comment by mike-spa** [comment]
As far as I can see, this doesn't happen anymore. Probably got fixed as part of https://github.com/musescore/MuseScore/pull/23381. @avvvvve please reopen if needed.
