### ISSUE TITLE
[TIED NOTES] Portamento doesn't get triggered from a tied note (Muse Sounds & VST)

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#23414]
### Issue type

General playback bug

### Bug description

When a portamento line starts from a tied note, the portamento effect does not get triggered (Muse Sounds & VST only). 

Specifically: 

Muse Sounds: 

- No portamento when "portamento" style is chosen in Properties > Playback
- Portamento _is_ heard when "chromatic" style is chosen, however another issue here is that there is an overlap between the duration of the tied note and the start of the "chromatic" portamento/gliss. This is a problem for instruments that play a portamento/gliss chromatically (e.g. flute). 

VST:

-  No portamento when "portamento" style is chosen in Properties > Playback
- Portamento _is_ heard when "chromatic" style is chosen. The "overlap" problem (see above) does not occur.

### Steps to reproduce

See video: 

https://github.com/musescore/MuseScore/assets/86290556/94d890f9-1e47-4309-948e-c3689fd0a251

### MuseScore Version

OS: macOS 14.5, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241830505, revision: github-musescore-musescore-f0f2bd8

### Regression

No

### Operating system

macOS 14.5

### Additional context

@zacjansheski pls check for regression status

**Comment by MarcSabatella** [comment]
Possibly related is https://github.com/musescore/MuseScore/issues/12971 even though that also about MS Basic, and about falls instead of glissandi.  But the similar symptom could indicate an issue in some shared code.

**Comment by erinic04** [comment]
Also doesn't work for soundfonts if the glissando starts on a tied note like shown, but also goes over the top of a tied note, i.e. 3 tied whole notes, the glissando starts on the second one

**Comment by zacjansheski** [comment]
Not a regression

**Comment by Dima-S-Jr** [comment]
Also, please note that slides/bends do not sound after the tied notes. This applies to both MS Basic and Muse Sounds.

https://github.com/user-attachments/assets/cc679101-c52d-45c7-9d41-2fb46ebe2176

**Comment by bkunda** [comment]
Seeing as how this is not a regression, and given the timeline for 4.4, I think this should be bumped and possibly addressed as part of a dedicated tied notes sprint.
