### ISSUE TITLE
Swapping triplet number (keyboard "x") adds bracket

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#23410]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When swapping the location of the triplet number "3" by pressing (X), the state of the bracket changes.  Would be better if the state were preserved.
This only happens in bracket "Auto" mode.  If bracket or no bracket selected, the state is preserved.

### Steps to reproduce

1. Create a triplet. by default there is no bracket (see first image)
2. Select the number "3".
3. Press (x)
4. The number moves to the other side of the triplet bar, however the bracket property is added. (see second image)

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/137847641/55465dbc-ad57-4052-b0d7-358ea2a1c811)
![image](https://github.com/musescore/MuseScore/assets/137847641/1828278f-584d-4942-9caf-c7fcb8109d57)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I don't know

### Operating system

Edition	Windows 10 Home Version	22H2 Installed on	‎12/‎5/‎2020 OS build	19045.3996 Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by oktophonie** [comment]
This is actually by design (in 'Auto' mode a bracket is not shown when the numeral is at the beam side, but is shown when it's on the other side); see https://github.com/musescore/MuseScore/issues/17852
