### ISSUE TITLE
'Parts' and 'Mixer' text size became smaller in 4.4 master

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#23417]
### Issue type

UI bug (incorrect info or interface appearance)

### Steps to reproduce

Compare 4.3.2 and 4.4 

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/850a120c-4819-4d1a-b451-563228648cc9

### MuseScore Version

4.4 master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

all

**Comment by cbjeukendrup** [comment]
Possibly caused by https://github.com/musescore/MuseScore/pull/23182 (that's an unverified guess though)

**Comment by DmitryArefiev** [comment]
Fixed in #23579
