### ISSUE TITLE
Very tall text cursor when editing text of dynamics

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#23435]
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

The text cursor is really tall if you double click a dynamic to edit the text

MS4.3.2
<img width="101" alt="Screenshot 2024-07-02 at 3 59 26 PM" src="https://github.com/musescore/MuseScore/assets/69917893/f732ae7b-a563-41d3-86ec-dbe8492b8046">

Master
<img width="84" alt="Screenshot 2024-07-02 at 3 59 39 PM" src="https://github.com/musescore/MuseScore/assets/69917893/1e21b3f3-da83-479c-a983-0c838177c5b9">

### Steps to reproduce

1. Double click a dynamic cursor will be very tall

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/75b1fe5c-178e-47c3-af7e-f59e3e3448f9

### MuseScore Version

OS: macOS 14.4, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241840302, revision: github-musescore-musescore-f0f2bd8

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 14, Windows 11

**Comment by oktophonie** [comment]
This occurred before as https://github.com/musescore/MuseScore/issues/11173. But now perhaps needs to be re-fixed because of Qt 6 and/or since https://github.com/musescore/MuseScore/pull/23356.

**Comment by DmitryArefiev** [comment]
Tested in **latest master** on Win10, Mac13.6 - **still occurs**

 

https://github.com/user-attachments/assets/0b44fecd-4184-490b-b8ba-5dc61da165b2
