### ISSUE TITLE
Insert measure after selection (selected barline) puts new measure(s) before barlines of the current measure instead of after

### ISSUE THREAD

**Issue by skdonnelly** [musescore/MuseScore#23465]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Steps to reproduce

1. create a score
2. put a repeat or double barline at the end of the last measure (or anywhere in the score)
3. select the measure that ends with a repeat or double barline
4. in the menu choose Add > Measures > Insert after selection
5. enter any number of measures and hit OK
The inserted measures will be **before** the double barlines/repeats instead of after it. The same problem occurs whether you select the measure itself or the barlines, there is no way to insert after the barline or repeat. Either both cases should insert after the barlines, or if you select the measure then the insert could insert after the current measure but before the barlines, and if you select the barlines themselves then the insert could insert the new measure after the barline. There should be some way to do so.

Expected result: [see comment](https://github.com/musescore/MuseScore/issues/23465#issuecomment-2253090805) and [comment ](https://github.com/musescore/MuseScore/issues/23465#issuecomment-2253435392)

### MuseScore Version

MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64,

**Comment by sammik** [comment]
It is intended (as far, as I know).

If You want not to move repeat barlines, You need to "insert before" next measure (or "insert at the end of score", if you ar in las bar).

Insert before doesnt move barlines.
Insert after does move barlines.

**Comment by skdonnelly** [comment]
Even if intentional it's still a bug: if I specifically select the **barline only**, that barline is my selection. I then insert a measure "after" the selection: it puts the new measure *before* the barline, so it's inserting something **before** my selection, not after.

**Comment by sammik** [comment]
@skdonnelly please check #23619
(or Win build directly [here](https://github.com/musescore/MuseScore/actions/runs/9931505636/artifacts/1699919548))

**Comment by DmitryArefiev** [comment]
> The inserted measures will be before the double barlines/repeats instead of after it. The same problem occurs whether you select the measure itself or the barlines, there is no way to insert after the barline or repeat. Either both cases should insert after the barlines, or if you select the measure then the insert could insert after the current measure but before the barlines, and if you select the barlines themselves then the insert could insert the new measure after the barline. There should be some way to do so.


There are two issues here, and №1 is expected (I think) because when you select the measure, the barline (or clef) remains unselected :

1. The inserted measures will be before the double barlines in **selected measure** instead of after it.
2. The same problem occurs whether you **select the barlines (or clef)**


#23619 fixes №2: 


https://github.com/user-attachments/assets/a6557337-b92f-40ff-b3a1-b19f24730969


@bkunda @oktophonie @avvvvve Just to confirm, №1 is expected or we want to change the behaviour?

**Comment by avvvvve** [comment]
@DmitryArefiev Yes, (1) is expected! #23619 is working as I'd expect it to, both when a full measure is selected that has a special barline on either end and when a barline itself is selected.

**Comment by DmitryArefiev** [comment]
Cool, thanks!

Fixed in #23619
