### ISSUE TITLE
Velocity setting no longer works

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#23470]
### Issue type

General playback bug

### Bug description

Changing the velocity of a note via Properties > Playback no longer has an audible effect. 

### Steps to reproduce

See video: 

https://github.com/musescore/MuseScore/assets/86290556/07313a53-9012-42f0-88f6-cd3505a445b0

### MuseScore Version

OS: macOS 14.5, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241830505, revision: github-musescore-musescore-f0f2bd8

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.5

### Additional context

This is a very recent regression.

It worked in the nightly of 28.06.24
It no longer worked in the nightly of 01.07.24

(I don't have the intervening nightlies readily at hand to check precisely which one it stopped working in, but hopefully this helps).

**Comment by MattiasSimson** [comment]
Also in the nightly builds and 4.4 - the velocity  option for Musescore Sounds will not be applied?
