### ISSUE TITLE
Program Crash when viewing solo part and different instrument is selected from Instruments tab

### ISSUE THREAD

**Issue by seisfeldt** [musescore/MuseScore#23477]
### Issue type

Crash or freeze

### Bug description

MuseScore closes unexpectedly when viewing a Part and then one of the other instruments is attempted to be unhidden from the Instruments tab.

### Steps to reproduce

1. Open the attached file.
2. Select the "Violin" part tab (step 1 in picture)
3. Select the Instruments tab on the left (step 2 in picture)
4. Press the closed eyeball to unhide the Flute instrument (step 3 in picture)
5. Program crashes consistently
(Note doesn't crash other instances of Musescore that are currently open)

### Screenshots/Screen recordings

![Program Crash](https://github.com/musescore/MuseScore/assets/137847641/c044d9f7-4567-4aa7-aaf2-acea834b6e7b)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I don't know

### Operating system

Edition	Windows 10 Home Version	22H2 Installed on	‎12/‎5/‎2020 OS build	19045.3996 Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by seisfeldt** [comment]
[crash.zip](https://github.com/user-attachments/files/16102863/crash.zip)

**Comment by cbjeukendrup** [comment]
It looks like I _can_ reproduce this on 4.3.2, but _not_ on the master branch. That suggests that it may already have been fixed for the next update. You can try this yourself in the nightly builds: https://musescore.org/en/nightly-builds

**Comment by seisfeldt** [comment]
Hi @cbjeukendrup  - I tried it with the latest nightly build and the crash seems to have been resolved.
I will close the ticket for now.  Thank you for the quick follow-up.

**Comment by cbjeukendrup** [comment]
Great, thanks for checking!
