### ISSUE TITLE
Weirdness caused by [de]crescendos and measure repeat signs

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#23476]
### Issue type

General playback bug

### Bug description

If a crescendo or decrescendo starts before a measure repeat sign in another instrument, and ends inside/after it, the sound keeps going back and forth between the original and correct dynamic.

This applies to soundfonts, Muse Sounds, and VST's, and all lengths of measure repeat signs. It doesn't matter whether the measure repeat sign is actually repeating anything.

It's possible that the dynamic change has to be large for the glitch to occur, either that or it's just hard to tell that it's broken. I can hear it with p < mf, but not p < mp.

### Steps to reproduce

1. Add any instrument with a crescendo or decrescendo that spans multiple measures.
2. Add a measure repeat in another instrument that starts in the middle of the [de]crescendo.
3. Play it back.

### MuseScore Version

4.3.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10, Linux Mint

### Additional context

[Irritating Bug.zip](https://github.com/user-attachments/files/16102775/Irritating.Bug.zip)
(this is an MSCZ file, I just changed the extension)

**Comment by bkunda** [comment]
@zacjansheski pls check whether this persists in current master.

**Comment by ThePython10110** [comment]
It seems like it's fixed in the latest nightly build.
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241870305, revision: github-musescore-musescore-a654c72

**Comment by RomanPudashkin** [comment]
fixed by https://github.com/musescore/MuseScore/pull/23274
