### ISSUE TITLE
Crash when opening/closing mixer quickly on big score, e.g. Symphony Orchestra template (Master, Windows)

### ISSUE THREAD

**Issue by metasekk** [musescore/MuseScore#23505]
### Issue type

Crash or freeze

### Bug description

See the title

### Steps to reproduce

https://github.com/musescore/MuseScore/assets/120221700/07659b4a-f5a6-4464-af8c-26bae52a1731

### MuseScore Version

Tested on latest 4.4 master (cff770b) 

### Regression

Yes, this used to work in **MuseScore 4.3.2**

### Operating system

Win10 (22H2); RAM: 16Go; CPU: Intel Core i5-9300H

### Additional context

Found when re-testing #23158 after https://github.com/musescore/MuseScore/issues/23495#issuecomment-2213288577.
I couldn't reproduce it in 4.3 (watch the video above).

I hope it isn't a duplicate (I searched in the currently opened issues, but couldn't find one corresponding). Close to #9467 but without requiring playback. EDIT: I just discovered it was equivalent to #13903 which was closed last month.

**Comment by cbjeukendrup** [comment]
It took me way too long to find out, but this is a Qt bug: https://bugreports.qt.io/browse/QTBUG-102729
Fortunately, it has been fixed in a next version. So there we go again, building Qt 6.2.9 from source. Yay....

**Comment by DmitryArefiev** [comment]
Fixed in #24969
