### ISSUE TITLE
impossible to compile on linux

### ISSUE THREAD

**Issue by dacorsa** [musescore/MuseScore#23510]
### Issue type

Crash or freeze

### Bug description

impossible to compile

### Steps to reproduce

steps to compile:
git clone https://github.com/musescore/MuseScore.git
cd /app/MuseScore/
sudo git checkout default
sudo git reset --hard
sudo git pull
/app/MuseScore/ninja_build.sh

### MuseScore Version

latest code

### Regression

I don't know

### Operating system

ubuntu 24.04

### Additional context

[session-muse.log](https://github.com/user-attachments/files/16128101/session-muse.log)

**Comment by dacorsa** [comment]
FAILED: src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx.o 
/usr/bin/ccache /usr/bin/c++ -DKORS_LOGGER_QT_SUPPORT -DKORS_PROFILER_ENABLED -DMUE_BUILD_APPSHELL_MODULE -DMUE_BUILD_BRAILLE_MODULE -DMUE_BUILD_CONVERTER_MODULE -DMUE_BUILD_IMAGESEXPORT_MODULE -DMUE_BUILD_IMPORTEXPORT_MODULE -DMUE_BUILD_INSPECTOR_MODULE -DMUE_BUILD_INSTRUMENTSSCENE_MODULE -DMUE_BUILD_NOTATION_MODULE -DMUE_BUILD_PALETTE_MODULE -DMUE_BUILD_PLAYBACK_MODULE -DMUE_BUILD_PROJECT_MODULE -DNDEBUG -DQT_CONCURRENT_LIB -DQT_CORE5COMPAT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORKAUTH_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_QMLBUILTINS_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICKTEMPLATES2_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_STATEMACHINE_LIB -DQT_SUPPORT -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSCRIPT_INTERFACE -Dappshell_QML_IMPORT=\"/app/MuseScore/src/appshell/qml\" -Dmuse_dockwindow_QML_IMPORT=\"/app/MuseScore/src/framework/dockwindow/qml\" -Dmuse_global_EXPORTS=1 -Dmuse_global_QML_IMPORT=\"\" -Dmuse_ui_QML_IMPORT=\"/app/MuseScore/src/framework/ui/qml\" -Dmuse_uicomponents_QML_IMPORT=\"/app/MuseScore/src/framework/uicomponents/qml\" -I/app/MuseScore/build.release/src/appshell -I/app/MuseScore/src/appshell -I/app/MuseScore/build.release/src/appshell/appshell_autogen/include -I/app/MuseScore/build.release -I/app/MuseScore/src -I/app/MuseScore -I/app/MuseScore/framework -I/app/MuseScore/framework/global -I/app/MuseScore/framework/testing/thirdparty/googletest/googletest/include -I/app/MuseScore/src/framework -I/app/MuseScore/src/framework/global -I/app/MuseScore/src/framework/testing/thirdparty/googletest/googletest/include -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtGui/6.7.0 -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtGui/6.7.0/QtGui -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/6.7.0 -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/6.7.0/QtCore -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtDBus/6.7.0 -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtDBus/6.7.0/QtDBus -I/app/MuseScore/build.release/src/framework/global -I/app/MuseScore/build.release/src/framework/ui -I/app/MuseScore/build.release/src/framework/uicomponents -I/app/MuseScore/build.release/src/framework/dockwindow -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtGui -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtDBus -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtWidgets -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtNetwork -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtNetworkAuth -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQml -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQmlIntegration -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQmlBuiltins -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQuick -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQmlModels -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtOpenGL -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQuickControls2 -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQuickTemplates2 -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQuickWidgets -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtXml -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtSvg -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtPrintSupport -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore5Compat -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtStateMachine -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtConcurrent -isystem /home/dacorsa/Qt/6.7.0/gcc_64/mkspecs/linux-g++ -O2 -std=gnu++17 -Wall -Wextra -fPIC -Winvalid-pch -include /app/MuseScore/build.release/src/framework/global/CMakeFiles/muse_global.dir/cmake_pch.hxx -MD -MT src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx.o -MF src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx.o.d -o src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx.o -c /app/MuseScore/build.release/src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx
In file included from /app/MuseScore/src/engraving/dom/../types/types.h:36,
                 from /app/MuseScore/src/engraving/dom/chordrest.h:28,
                 from /app/MuseScore/src/engraving/dom/articulation.h:28,
                 from /app/MuseScore/src/notation/notationtypes.h:34,
                 from /app/MuseScore/src/notation/internal/inotationundostack.h:29,
                 from /app/MuseScore/src/notation/inotation.h:28,
                 from /app/MuseScore/src/project/types/projecttypes.h:37,
                 from /app/MuseScore/src/project/irecentfilescontroller.h:30,
                 from /app/MuseScore/src/appshell/view/appmenumodel.h:37,
                 from /app/MuseScore/src/appshell/view/navigableappmenumodel.h:29,
                 from /app/MuseScore/src/appshell/view/navigableappmenumodel.cpp:22,
                 from /app/MuseScore/build.release/src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx:10:

**Comment by cbjeukendrup** [comment]
Looks like you're building with Qt 6.7. As per the instructions at https://github.com/musescore/MuseScore/wiki/Install-Qt-and-Qt-Creator and related pages, Qt 6.2.4 is needed.

Also, the log snippet that you have posted does mention the location of the error, but not what the error is :)

**Comment by dacorsa** [comment]
OK guys thanks for all, but i tried also with the embedded qt6 but i have another error, so can you help to understand what file of musescore i can send you to investigate more on the error?

thanks

**Comment by bkunda** [comment]
Seems like this is a support request. 

Can I please ask you to raise it on the musescore.org forum? 

If there ends up being a reproducible bug, please feel to raise it again here. Thanks!

**Comment by cbjeukendrup** [comment]
Let's keep the discussion here, but it's fine that the issue is closed already. 

@dacorsa what is the error message that you see when running the compilation command?

**Comment by dacorsa** [comment]
i have added all the output of my terminal, i didn't see any error only this:
FAILED: src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx.o
/usr/bin/ccache /usr/bin/c++ -DKORS_LOGGER_QT_SUPPORT -DKORS_PROFILER_ENABLED -DMUE_BUILD_APPSHELL_MODULE -DMUE_BUILD_BRAILLE_MODULE -DMUE_BUILD_CONVERTER_MODULE -DMUE_BUILD_IMAGESEXPORT_MODULE -DMUE_BUILD_IMPORTEXPORT_MODULE -DMUE_BUILD_INSPECTOR_MODULE -DMUE_BUILD_INSTRUMENTSSCENE_MODULE -DMUE_BUILD_NOTATION_MODULE -DMUE_BUILD_PALETTE_MODULE -DMUE_BUILD_PLAYBACK_MODULE -DMUE_BUILD_PROJECT_MODULE -DNDEBUG -DQT_CONCURRENT_LIB -DQT_CORE5COMPAT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORKAUTH_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_QMLBUILTINS_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICKTEMPLATES2_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_STATEMACHINE_LIB -DQT_SUPPORT -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSCRIPT_INTERFACE -Dappshell_QML_IMPORT="/app/MuseScore/src/appshell/qml" -Dmuse_dockwindow_QML_IMPORT="/app/MuseScore/src/framework/dockwindow/qml" -Dmuse_global_EXPORTS=1 -Dmuse_global_QML_IMPORT="" -Dmuse_ui_QML_IMPORT="/app/MuseScore/src/framework/ui/qml" -Dmuse_uicomponents_QML_IMPORT="/app/MuseScore/src/framework/uicomponents/qml" -I/app/MuseScore/build.release/src/appshell -I/app/MuseScore/src/appshell -I/app/MuseScore/build.release/src/appshell/appshell_autogen/include -I/app/MuseScore/build.release -I/app/MuseScore/src -I/app/MuseScore -I/app/MuseScore/framework -I/app/MuseScore/framework/global -I/app/MuseScore/framework/testing/thirdparty/googletest/googletest/include -I/app/MuseScore/src/framework -I/app/MuseScore/src/framework/global -I/app/MuseScore/src/framework/testing/thirdparty/googletest/googletest/include -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtGui/6.7.0 -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtGui/6.7.0/QtGui -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/6.7.0 -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/6.7.0/QtCore -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtDBus/6.7.0 -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtDBus/6.7.0/QtDBus -I/app/MuseScore/build.release/src/framework/global -I/app/MuseScore/build.release/src/framework/ui -I/app/MuseScore/build.release/src/framework/uicomponents -I/app/MuseScore/build.release/src/framework/dockwindow -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtGui -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtDBus -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtWidgets -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtNetwork -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtNetworkAuth -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQml -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQmlIntegration -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQmlBuiltins -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQuick -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQmlModels -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtOpenGL -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQuickControls2 -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQuickTemplates2 -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQuickWidgets -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtXml -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtSvg -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtPrintSupport -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore5Compat -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtStateMachine -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtConcurrent -isystem /home/dacorsa/Qt/6.7.0/gcc_64/mkspecs/linux-g++ -O2 -std=gnu++17 -Wall -Wextra -fPIC -Winvalid-pch -include /app/MuseScore/build.release/src/framework/global/CMakeFiles/muse_global.dir/cmake_pch.hxx -MD -MT src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx.o -MF src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx.o.d -o src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx.o -c /app/MuseScore/build.release/src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx

**Comment by dacorsa** [comment]
Excuse me but unity is not a file of GNOME GUI? i have KDE why i have to compile this component?

FAILED: src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx.o 
/usr/bin/ccache /usr/bin/c++ -DKORS_LOGGER_QT_SUPPORT -DKORS_PROFILER_ENABLED -DMUE_BUILD_APPSHELL_MODULE -DMUE_BUILD_BRAILLE_MODULE -DMUE_BUILD_CONVERTER_MODULE -DMUE_BUILD_IMAGESEXPORT_MODULE -DMUE_BUILD_IMPORTEXPORT_MODULE -DMUE_BUILD_INSPECTOR_MODULE -DMUE_BUILD_INSTRUMENTSSCENE_MODULE -DMUE_BUILD_NOTATION_MODULE -DMUE_BUILD_PALETTE_MODULE -DMUE_BUILD_PLAYBACK_MODULE -DMUE_BUILD_PROJECT_MODULE -DNDEBUG -DQT_CONCURRENT_LIB -DQT_CORE5COMPAT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORKAUTH_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_QMLBUILTINS_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICKTEMPLATES2_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_STATEMACHINE_LIB -DQT_SUPPORT -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSCRIPT_INTERFACE -Dappshell_QML_IMPORT=\"/app/MuseScore/src/appshell/qml\" -Dmuse_dockwindow_QML_IMPORT=\"/app/MuseScore/src/framework/dockwindow/qml\" -Dmuse_global_EXPORTS=1 -Dmuse_global_QML_IMPORT=\"\" -Dmuse_ui_QML_IMPORT=\"/app/MuseScore/src/framework/ui/qml\" -Dmuse_uicomponents_QML_IMPORT=\"/app/MuseScore/src/framework/uicomponents/qml\" -I/app/MuseScore/build.release/src/appshell -I/app/MuseScore/src/appshell -I/app/MuseScore/build.release/src/appshell/appshell_autogen/include -I/app/MuseScore/build.release -I/app/MuseScore/src -I/app/MuseScore -I/app/MuseScore/framework -I/app/MuseScore/framework/global -I/app/MuseScore/framework/testing/thirdparty/googletest/googletest/include -I/app/MuseScore/src/framework -I/app/MuseScore/src/framework/global -I/app/MuseScore/src/framework/testing/thirdparty/googletest/googletest/include -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtGui/6.7.0 -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtGui/6.7.0/QtGui -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/6.7.0 -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore/6.7.0/QtCore -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtDBus/6.7.0 -I/home/dacorsa/Qt/6.7.0/gcc_64/include/QtDBus/6.7.0/QtDBus -I/app/MuseScore/build.release/src/framework/global -I/app/MuseScore/build.release/src/framework/ui -I/app/MuseScore/build.release/src/framework/uicomponents -I/app/MuseScore/build.release/src/framework/dockwindow -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtGui -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtDBus -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtWidgets -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtNetwork -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtNetworkAuth -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQml -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQmlIntegration -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQmlBuiltins -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQuick -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQmlModels -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtOpenGL -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQuickControls2 -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQuickTemplates2 -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtQuickWidgets -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtXml -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtSvg -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtPrintSupport -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtCore5Compat -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtStateMachine -isystem /home/dacorsa/Qt/6.7.0/gcc_64/include/QtConcurrent -isystem /home/dacorsa/Qt/6.7.0/gcc_64/mkspecs/linux-g++ -O2 -std=gnu++17 -Wall -Wextra -fPIC -Winvalid-pch -include /app/MuseScore/build.release/src/framework/global/CMakeFiles/muse_global.dir/cmake_pch.hxx -MD -MT src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx.o -MF src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx.o.d -o src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx.o -c /app/MuseScore/build.release/src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx
In file included from /app/MuseScore/src/engraving/dom/../types/types.h:36,
                 from /app/MuseScore/src/engraving/dom/chordrest.h:28,
                 from /app/MuseScore/src/engraving/dom/articulation.h:28,
                 from /app/MuseScore/src/notation/notationtypes.h:34,
                 from /app/MuseScore/src/notation/internal/inotationundostack.h:29,
                 from /app/MuseScore/src/notation/inotation.h:28,
                 from /app/MuseScore/src/project/types/projecttypes.h:37,
                 from /app/MuseScore/src/project/irecentfilescontroller.h:30,
                 from /app/MuseScore/src/appshell/view/appmenumodel.h:37,
                 from /app/MuseScore/src/appshell/view/navigableappmenumodel.h:29,
                 from /app/MuseScore/src/appshell/view/navigableappmenumodel.cpp:22,
                 from /app/MuseScore/build.release/src/appshell/CMakeFiles/appshell.dir/Unity/unity_3_cxx.cxx:10:

**Comment by cbjeukendrup** [comment]
No, those Unity files have to do with CMake's [unity build](https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD.html#prop_tgt:UNITY_BUILD) feature. 

It is really strange that you are not seeing any other output. Perhaps you're somehow only seeing stderr or only stdout but not both. 

What command are you using to start the compilation? Are you using the `build.cmake` script, or are you using CMake directly? 

Also, which CMake generator are you using, is it Ninja or Makefiles?

**Comment by dacorsa** [comment]
Good morning,
with this command:
cmake --parallel $(nproc) -P build.cmake -DCMAKE_BUILD_TYPE=Release
i have this log:
[session-muse2.log](https://github.com/user-attachments/files/16173128/session-muse2.log)

**Comment by dacorsa** [comment]
with this command:
/app/MuseScore/ninja_build.sh
i have this log:

[session-muse.log](https://github.com/user-attachments/files/16173213/session-muse.log)

**Comment by cbjeukendrup** [comment]
Thanks, that contains useful information. 
The problem turns out to be that you are still using Qt 6.7 instead of 6.2.4. See https://github.com/musescore/MuseScore/wiki/Compile-on-the-command-line#using-buildcmake-recommended under "Locating Qt" how to tell the `build.cmake` script where it should look for Qt; make sure to tell it to look for Qt 6.2.4.

**Comment by dacorsa** [comment]
Good morning all Guys,
i tried to edit this file : build_overrides.cmake with:

# build_overrides.cmake
set(ENV{QTDIR} "$ENV{HOME}/Qt/6.2.4/gcc_64") # or wherever Qt is located

with this path:
/usr/lib/qt6/bin
/usr/lib/x86_64-linux-gnu

but not works...

so i downloaded the old version with qt installer: 6.5.3 and works:
[1313/1315] Building CXX object src/app/CMakeFiles/mscore.dir/internal/consoleapp.cpp.o
In file included from /app/MuseScore/src/engraving/devtools/drawdata/drawdatatypes.h:25,
                 from /app/MuseScore/src/engraving/devtools/drawdata/idiagnosticdrawprovider.h:29,
                 from /app/MuseScore/src/app/internal/consoleapp.h:38,
                 from /app/MuseScore/src/app/internal/consoleapp.cpp:23:
/app/MuseScore/src/framework/draw/types/geometry.h:449:23: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  449 |     inline PolygonX<T>() = default;
      |                       ^
/app/MuseScore/src/framework/draw/types/geometry.h:449:23: note: remove the ‘< >’
/app/MuseScore/src/framework/draw/types/geometry.h:450:23: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  450 |     inline PolygonX<T>(const std::vector<PointX<T> >& v) : std::vector<PointX<T> >(v) {
      |                       ^
/app/MuseScore/src/framework/draw/types/geometry.h:450:23: note: remove the ‘< >’
/app/MuseScore/src/framework/draw/types/geometry.h:452:24: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  452 |     inline PolygonX<T>(size_t size) : std::vector<PointX<T> >(size) {
      |                        ^~~~~~
/app/MuseScore/src/framework/draw/types/geometry.h:452:24: note: remove the ‘< >’
[1314/1315] Linking CXX executable src/app/mscore

-rwxr-xr-x 1 root root 74758416 lug 12 11:32 /app/MuseScore/build.release/src/app/mscore

so we can close this ticket, thanks for all, musescore is not ready for qt 6.7.0 :)

ciao see you soon
