### ISSUE TITLE
Playback one note too short

### ISSUE THREAD

**Issue by SystemsModelling** [musescore/MuseScore#23514]
### Issue type

General playback bug

### Bug description

Why is the F#4 in measure 17 staff 2 beat 4 sounding so short?
A muse sound bug?
The F#4 in measure 14 sounds OK.

### Steps to reproduce

Play measure 17 of the piece shown

### Screenshots/Screen recordings

https://musescore.com/user/29209262/scores/19635643/s/RUmGDZ?share=copy_link

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

Choose option...

### Operating system

Win 10

**Comment by SystemsModelling** [comment]
I found that the properties / playback showed a velocity of -28. In the original score I copied from it was -6. I corrected it to 64 and it's OK now.
https://musescore.com/the_alex/scores/5760735

**Comment by MarcSabatella** [comment]
Crazy coincidence in that I just today submitted #23486 that should fix this for future imports!

**Comment by SystemsModelling** [comment]
All explained 🙂
