### ISSUE TITLE
Current master doesn’t use title: “plug-in-title” in the onCompleted section as in prior 4.4

### ISSUE THREAD

**Issue by TeeDeeY** [musescore/MuseScore#23518]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

As I noted here: https://github.com/musescore/MuseScore/issues/23421#issuecomment-2211492950

Using conditional logic, a basic plugin could be used in 3.6 through 4.4.  

The latest master doesn’t accept the title addition o the onCompleted section as earlier 4.4 versions.  

### Steps to reproduce

Try use attached plugin in additional context area.  Enable plugin.  
the menu won’t show a title.  There will be () marks but no title.  

### Screenshots/Screen recordings

See attached plug-in additional context section.  It works in 3.6,  4.2 and recent 4.4 versions but not current master. 

### MuseScore Version

Current master 

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 22.04

### Additional context

[allversions.zip](https://github.com/user-attachments/files/16134724/allversions.zip)

**Comment by igorkorsukov** [comment]
For 4.4 this option is no longer available, we are gradually moving to a different plugin system, as a result, we no longer load (execute) plugins at application startup.

As a workaround, I can advise you to set a static name for 4.4, and in `onCompleted` set the name for 3.6, then the result you need will be achieved. Will this work for you?

**Comment by Jojo-Schmitz** [comment]
@igorkorsukov Could you provide some sample plugin code for that proposal?

**Comment by igorkorsukov** [comment]
> @igorkorsukov Could you provide some sample plugin code for that proposal?

Like this 
```
import MuseScore 3.0
import QtQuick 2.1

MuseScore {
    id: plugin
    title: "Title for MS4.4+ "  

    Component.onCompleted: { 
        if (mscoreMinorVersion < 4) {
                  plugin.title = "Title for MS3.6"  
        }
    }
}
```

**Comment by Jojo-Schmitz** [comment]
That's what I was affraid of: Mu3 won't accept that:
`Line 6: Cannot assign to non-existent property "title"`
Mu3 generates the title from the tail component of `menuPath`, e.g.:
`menuPath: "Plugins.Title for MS 3.6"

**Comment by igorkorsukov** [comment]
Now I understand the problem, I will make an improvement to fix it

**Comment by igorkorsukov** [comment]
I added fix and there is an example of usage
https://github.com/musescore/MuseScore/pull/23551

**Comment by igorkorsukov** [comment]
> What about `thubnailName` and `categoryCode`? I believe they'd need the same treatment.

This marker can be added before any property

**Comment by Jojo-Schmitz** [comment]
Not on Mu3...

**Comment by Jojo-Schmitz** [comment]
Ah, I see, thanks

**Comment by TeeDeeY** [comment]
Thanks all! 
// for 3.x keep using menupath at start as usual
menuPath: "Plugins.MS3MenuName" 

// special 4.4 compatibility method ;-)
// won’t cause errors in 3.6/3.7
//4.4 title: “title for 4.4”

// title for 4.0 to 4.3.  
Component.onCompleted: {  
        if (mscoreMajorVersion >= 4) {
        if (mscoreMinorVersion <= 3) {
           var tString = "Title for MS4.0 to 4.3x " 
          title=qsTr(tString);
          }
      } 
 }
