### ISSUE TITLE
Crash when pasting formatted multi-line text with formatting

### ISSUE THREAD

**Issue by TeeDeeY** [musescore/MuseScore#23520]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Write text with two lines and Italic
2. Copy Paste into a text frame or staff text or sim

this works in 4.3.2
I think all three were needed to be set to crash but I didn’t try all combinations.  

### Supporting files, videos and screenshots

[MuseScore_240708_154504.log](https://github.com/user-attachments/files/16135163/MuseScore_240708_154504.log)

As far as this tracker goes:
This box was confusing. I initially didn’t know where the three dots were to attach the log.  

Too much text above the box made the input box hard to see on a smartphone.  Maybe the box borders need to be much thicker on this bug report tracker.  

### What is the latest version of MuseScore Studio where this issue is present?

Nightly 8b06e64 crashes like earlier nightly

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 24.04

### Additional context

I don’t think it’s related to control shift drag crash directly but could be connected indirectly.  

https://github.com/musescore/MuseScore/issues/23318#issue-2365185403

https://github.com/musescore/MuseScore/assets/69917893/f8770995-5206-4789-bbf0-feeaa0b8c239

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by TeeDeeY** [comment]
On my working score, this was crashing.  My initial workaround was to make a new frame, type “frame” in default text, and then save the score and exit musescore.  Then, I open the score and can copy paste into the new frame successfully.  New frames could be incorrectly made in some way.

**Comment by TeeDeeY** [comment]
An inconsistent behaviour is that I made the last page of the song with a frame with six empty lines - just carriage returns.  It looks good.  Then, I save and reopen, and no carriage returns are there.  The frame is empty.  I use empty carriage returns so the dimensions match a prior frame’s dimensions based in the same number of lines, the font, etc.  it’s convenient to allow saving an “empty” frame (multiple carriage returns)

**Comment by bkunda** [comment]
@zacjansheski pls check

**Comment by zacjansheski** [comment]
I'm going to simplfy this report

It is simply a crash caused by pasting text with multiple lines and formatting into a text frame

https://github.com/musescore/MuseScore/assets/69917893/31ee1cf9-0c89-4a09-be3d-a18584faac21

**Comment by DmitryArefiev** [comment]
Tested in **latest master** on Win10, Mac13.6, LinuxUbuntu22.04. **No longer occurs**
