### ISSUE TITLE
Memory leak after exporting scores as audio (MP3 only)

### ISSUE THREAD

**Issue by metasekk** [musescore/MuseScore#23531]
### Issue type

General playback bug

### Description with steps to reproduce

Exporting a score as audio (mp3) results in a sustained high RAM consumption after the end of the process, when the software is idle again.

### Supporting files, videos and screenshots

The video below uses this test score ([Toy_score_for_exportation_time.zip](https://github.com/user-attachments/files/16143432/Toy_score_for_exportation_time.zip)).

https://github.com/musescore/MuseScore/assets/120221700/862b3016-123a-42e2-80f2-97eca333ebe7

Interestingly enough, as shown in the video, the issue does not arise when cancelling the process halfway through.

### What is the latest version of MuseScore Studio where this issue is present?

Tested on latest 4.4 master (cff770b) and 4.1.0. Not a regression.

### Regression

No.

### Operating system

Win10 (22H2); RAM: 16Go; CPU: Intel Core i5-9300H

### Additional context

Found when re-testing #21520.

This issue is of particular concern on large scores, where the exportation process can reach high RAM amounts (>7 Go) that are never released (until the software is restarted).

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
@DmitryArefiev can you please check this?

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev can you please check this?

Checked on Win10. This happens with **MS Basic as well**, but **only** with export **MP3**

**Occurs** in **MS 4.0.0** as well
