### ISSUE TITLE
Playback cursor erases some lyrics elements sometimes  

### ISSUE THREAD

**Issue by TeeDeeY** [musescore/MuseScore#23539]
### Issue type

UI

### Description with steps to reproduce

-Enter many notes with lyrics ending with exclamation marks “!”
-Tempo to 30 Bpm to slow things down. 
-start playback in measure before lyrics
-Zoom in to lyrics to see more clearly 
-Play music
-After the playback bar passes over, often the upper part of the ! symbol is partially cut off, then restored much later than it should be.  

Note: not all exclamation points are affected.  Sometimes the upper part of a semicolon is affected.  As soon as stop is pressed, the display is corrected.  After a system break, the display seems corrected.  If the measure is stretched out, no parts seem to be cut off.  

You must watch carefully.  
4.2.1 doesn’t have this problem. 
Recent master builds have this problem.  
See video.    
  

### Supporting files, videos and screenshots

[Screencast from 07-09-2024 12:40:03 PM.webm](https://github.com/musescore/MuseScore/assets/159660491/591e7fd1-d807-44bc-8ce8-f8d6cbe076b5)

### What is the latest version of MuseScore Studio where this issue is present?

Nightly July 6. (Edited)
Confirmed error using latest linux master 8cada5f

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 22.04

### Additional context

In video, exclamation points after yesterday and hello are affected.  Others are not.  

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
The tempo marking in the video is affected too...

**Comment by oktophonie** [comment]
Similar to https://github.com/musescore/MuseScore/issues/19885, https://github.com/musescore/MuseScore/issues/20562

**Comment by TeeDeeY** [comment]
Tested using the artifact file.  The lyrics seem correct.  The tempo can still be slightly cut off at the rightmost area.  Using a tempo of 30 bpm shows it.  This is zoomed at 635%, which most people won’t look at it.  Quite obvious at 1600%.  I can post a video if needed, but if it’s not reproducible on all machines, it may not be worth working on this right now.

**Comment by TeeDeeY** [comment]
The issue with tempo is not a regression like the lyrics.  I can reproduce the tempo issue in 4.2.1 on Ubuntu 24.04.
