### ISSUE TITLE
Change "Snap to previous/next" toggles to checkboxes

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#23545]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

Hairpins and tempo lines have new snapping properties. We originally designed them as toggles, but as @mathesoncalum pointed out, when you have multiple different hairpins selected where their toggle states are not the same, there is no indeterminant state of the toggle to signal to the user a mixed state.

Though our toggle component does not have this state, the checkbox component does.

### Places to use a checkbox instead of a toggle

- Hairpin properties
- Tempo line properties

### Supporting files, videos and screenshots

<img width="476" alt="image" src="https://github.com/musescore/MuseScore/assets/20806406/18ea55b4-c6ba-4826-851a-0d8af8b56681">

### What is the latest version of MuseScore Studio where this issue is present?

4.4 master

### Regression

No.

### Operating system

macOS 14

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by kibibyt3** [comment]
Can I take this one?
