### ISSUE TITLE
Lyric underscores colliding with previous text

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#23552]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

The required clearance between the end of a syllable and a lyric underscore has been lost; the line starts on top of the last character. Possibly a consequence of https://github.com/musescore/MuseScore/pull/23356

### Supporting files, videos and screenshots

![image](https://github.com/musescore/MuseScore/assets/20604032/a3f5dee0-5ede-4abd-b6f1-c2b0258e9656)

### What is the latest version of MuseScore Studio where this issue is present?

10 July nightly

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux, Windows

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
It wouldn't surprise me if this has a link with https://github.com/musescore/MuseScore/issues/23539 (which is probably also a bounding box / shape issue)

**Comment by mike-spa** [comment]
Plot twist, the issue seems to be happening on the nightly builds but in none of our local builds
