### ISSUE TITLE
[Muse Strings] Playback is altered on subsequent notes after a bend

### ISSUE THREAD

**Issue by metasekk** [musescore/MuseScore#23584]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

Guitar bends on Muse Strings produce weird "ghost" sounds at the end of all the following notes. The pitch of the ghost notes seems to depend on the direction of the bend (lower pitch if the bend went downwards, higher if it went upwards). Removing the bends does not clear those artifacts (until restart of the software).

Tested with the **latest Muse Strings** version available in Muse Hub Beta (as of 11/07/2024).

### Supporting files, videos and screenshots

Watch this video:

https://github.com/musescore/MuseScore/assets/120221700/1c577463-2caf-44b1-9209-647d408a7bbc

### What is the latest version of MuseScore Studio where this issue is present?

Tested on 4.4 master and 4.3, with Muse Sampler 0.6 and 0.5. Likely not a regression of MuseScore Studio.

### Regression

No.

### Operating system

Win10 (22H2); RAM: 16Go; CPU: Intel Core i5-9300H

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
Does this happen if you use the bends on an actual guitar instrument? 

This feature wasn't actually designed to be used on bowed strings, so I'm quite surprised they're doing anything at all!

**Comment by metasekk** [comment]
It doesn't happen on any instrument of the Muse Sounds Guitars Vol.1. I was surprised too when I saw that guitar bends do seem to work on certain bowed strings (like Violoncellos (section)), while it doesn't on others (Violins (section)).

**Comment by metasekk** [comment]
Closing as this issue is broader than expected at first, while reopening a reframed one as #25909 .
