### ISSUE TITLE
Nightly Portable 4.4 Windows crashes after pressing DEL after deleting a note in voice 2

### ISSUE THREAD

**Issue by Christian150373** [musescore/MuseScore#23585]
### Issue type

Crash or freeze

### Description with steps to reproduce

Musescore crashes after deleting a note in voice 2 and pressing DEL on the keyboard again

Must be in note input mode on the first beat of the measure to reproduce

### Supporting files, videos and screenshots

https://github.com/musescore/MuseScore/assets/175350042/b024237e-fe3d-4fcf-9f8b-7bb1ea39bec2

[Diagnostic.zip](https://github.com/user-attachments/files/16182183/Diagnostic.zip)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScoreNightly-latest-master-x86_64-portable (Download 2024_07_11)

### Regression

Yes, worked in 4.3.2, broken in master

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
Must be in note input mode on the first beat of the measure to reproduce
