### ISSUE TITLE
Allow fermata time stretch greater than 400%

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23609]
### Your idea

Fermatas should be allowed to stretch the time by far longer than 400% (5 times the original note length).

### Problem to be solved

It's not unusual for a fermata to occur on a 1/16 note (or rest) with the intention that the note is held for far longer than 5 times its face value.  One example might be the top B "ce" in the final "vincero" of Nessun Dorma, however admittedly many notated versions of that don't even show a fermata, but it's certainly common for that 1/16 note to be sustained for up a full measure (~250 times its face value, i.e. over 6000%).

### Prior art

Musescore is already perfectly capable of playing fermatas longer than 400% if you edit the mscx file etc.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Bhavya418** [comment]
I would like to take up this issue and solve it.

**Comment by cbjeukendrup** [comment]
Nice, welcome!

**Comment by cbjeukendrup** [comment]
I'd propose a maximum value of 10000%; that allows the note to be 100x as long and I guess that would be sufficient.

**Comment by Jojo-Schmitz** [comment]
Just came up again in https://musescore.org/en/node/366352

**Comment by Jojo-Schmitz** [comment]
And maybe we want it in times rather than % ?

**Comment by wizofaus** [comment]
Far bigger issue is that the way fermatas are played back is simply wrong when you have multiple fermatas at different beat positions across staves (which is reported separately). But no reason not to make the trivial UI change here to allow values up to 10000% that I can think of.

**Comment by cbjeukendrup** [comment]
Indeed, there's this issue how fermatas are played back exactly: https://github.com/musescore/MuseScore/issues/15569 So it's a bit more involved than just halting on the last beat of the note instead of the first one.

**Comment by chilkaditya** [comment]
hi, I want work on this issue. I understand the issue, if we want to set fermata  time stretch greater than 400% its automatically set 400%.
After seeing the symid_p.h, there is 7 types of fermata and max of them is FermataVeryLong which is returning 4.0 in Fermata::propertyDefault() method. For tackling this issue we have to define new fermata type? or we can just return greater than 4.0 for FermataVeryLong type,  or something else we have to do. Any suggestions would be appreciated.

**Comment by Jojo-Schmitz** [comment]
a) it is already assigned to @Bhavya418 (but since a month without any apparent activity)
b) no, there's no new fermata needed, just a change in the UI that allows that setting to get changed, which currently limits it to 400%
c) @wizofaus 400% is 4 time, not 5 times, or am I missing something here? Or is is "strech by", i.e. 100%+setting rather thsan "stretch to"?

**Comment by chilkaditya** [comment]
Hi @Jojo-Schmitz, I am new here, can I work on this good first issue to start with my contribution towards MuseScore? And I also solved the issue using your instruction.

**Comment by wizofaus** [comment]
I always assumed 0% = no stretch, but I admit I didn't test.

**Comment by Jojo-Schmitz** [comment]
@chilkaditya just create a PR with your fix

**Comment by Jojo-Schmitz** [comment]
@wizofaus yes, setting it to 0% is possible, but doesn# seem to have any effect, plays the same as 100% as far as I can tell
Seems another bug, setting below 100% should __shorten__ the note
Actually it does, just 0% doesn't __skip__ it engtirely, 1% almost does though. 

So either 0% should be disallowed, or skip the affercted duration

**Comment by cbjeukendrup** [comment]
The fix has been merged to master. If anyone becomes very happy if this gets included into 4.4.0 too, feel free to create a version for the 4.4.0 branch, since the fix seems safe enough.

**Comment by Jojo-Schmitz** [comment]
Done
