### ISSUE TITLE
Choppy sound using MuseScore Studio 4.3.2 on UbuntuStudio 22.04 LTS

### ISSUE THREAD

**Issue by rolodoom** [musescore/MuseScore#23616]
### Issue type

General playback bug

### Description with steps to reproduce

1. Full UbuntuStudio 24.04 LTS install, and updated.
2. Install MuseScore using `MuseScore-Studio-4.3.2.241630832-x86_64.AppImage install`
3. Open an score, or create a new one and playback
4. Choppy sound on note input and playback

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/b724b9bb-9904-4b38-8e80-9e7757cb6bed

### What is the latest version of MuseScore Studio where this issue is present?

OS: Ubuntu 24.04 LTS, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

UbuntuStudio 24.04 LTS

### Additional context

In my daily life I use different Linux distributions, and until now I have not had this problem with the `appimage` version in others (Fedora, Debian, Manjaro, other Ubuntu flavors)

So I think the problem has to do with the audio settings. It seems important to me to be able to find the problem because UbuntuStudio is the flavor of Ubuntu to use as a professional audio station.

 The problem is also present on Nightly Build 4.4.0:  OS: Ubuntu 24.04 LTS, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241960305, revision: github-musescore-musescore-ee86cbc

**edit:** _Forgot to mention that I can export to wav/mp3 without any gap on the audio. The problem is only on playback._

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
Generally this is a sample rate mismatch.  Try setting your device to use (or at least allow) 44.1 kHz.  With pipewire, for instance, the default on my installation is to only allow 48, which won’t work indeed.

And if you need further assistance in using MuseScore Studio, please ask for help on the official Support forum at MuseScore.org.

**Comment by mmendelson222** [comment]
My issue appears to be the same issue.   The playback is uneven to the point of being useless. 

Brand new Mac Mini (M2, 16G) and am working with MuseScore 4 for the first time.

https://github.com/user-attachments/assets/54596f64-1d25-4d5e-9c17-9f6bc8b95cf8

MuseScore 4 info:
OS: macOS 14.5, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: [22b46f2](https://github.com/musescore/musescore/commit/22b46f2)

Computer:
      Model Name: Mac mini
      Chip: Apple M2
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
     OS: Sonoma 14.5
      System Firmware Version: 10151.121.1
      OS Loader Version: 10151.121.1

**Comment by MarcSabatella** [comment]
Same answer applies.

**Comment by rolodoom** [comment]
> Generally this is a sample rate mismatch. Try setting your device to use (or at least allow) 44.1 kHz. With pipewire, for instance, the default on my installation is to only allow 48, which won’t work indeed.
> 
> And if you need further assistance in using MuseScore Studio, please ask for help on the official Support forum at MuseScore.org.

Thanks for your response!!!

But why this?? I mean, it's not supposed for MuseScore to use the sample rate of the system device? it's kind o weird. Reaper, Ardour, Audacity and other audio on the system has no problem with this.

As you instructed, I changed the pipewire settings using the Ubuntu Studio Audio Configuration to 44.1Khz and to choppy sound has disappeared.

**Comment by RomanPudashkin** [comment]
@mmendelson222 what sample rate is your system using? Does setting it to 44.1 kHz help?

**Comment by MarcSabatella** [comment]
FWIW, Until last week I had just been setting my sample rate to 44.1 kHz explicitly (pw-metadata, the “clock.force-rate” parameter and all was fine, but it bothered me to have to set it globally.  Then I discovered it worked to just set clock.allowed-rates to include both 48 and 44.1, while leaving the default at 48.  So I assume MuseScore Studio is *trying* to set the clock to 44.1 and if it works, great, but if it fails, then you get the stutters.

**Comment by mmendelson222** [comment]
> @mmendelson222 what sample rate is your system using? Does setting it to 44.1 kHz help?

Thanks for asking - I have tried a number of things. Following Marc's and others' advice, I tried setting my sampling rates to 44.1 (mac seems to have these in the "Audio Midi Setup").  

Seems like no matter what settings I use, I see the same problem. 

![Screenshot 2024-07-14 at 12 40 47 PM](https://github.com/user-attachments/assets/77c54e3f-4feb-4126-8ca8-ca0c4ab97b8a)

I also set up an external bluetooth speaker, in case something is different about that. Same result. 
![Screenshot 2024-07-14 at 12 40 10 PM](https://github.com/user-attachments/assets/3b650ea1-85ae-4b7e-9d4b-04da8a8453a7)

I wonder if there's somewhere else I need to be setting them.  Some of the comments above "pw-metadata" I think refer to PipeWire.  I think that's for Linux, not mac.

**Comment by rolodoom** [comment]
> FWIW, Until last week I had just been setting my sample rate to 44.1 kHz explicitly (pw-metadata, the “clock.force-rate” parameter and all was fine, but it bothered me to have to set it globally. Then I discovered it worked to just set clock.allowed-rates to include both 48 and 44.1, while leaving the default at 48. So I assume MuseScore Studio is _trying_ to set the clock to 44.1 and if it works, great, but if it fails, then you get the stutters.

Mark, about `clock.allowed-rates`, where are you changing it?? I really don't know what UbuntuStudio is changing when using `ubuntustudio-audio-configuration` that seems to be the default program to change the audio configuration on this system, only think I'm sured is that is being changed globally 'cause it needs my password. 

On Debian, I configure the jack/pipewire on a local file `~/.config/pipewire/jack.conf` that is originally copied from `/usr/share/pipewire/jack.conf` but I think is not the case on UbuntuStudio.

As I said earlier, the problem it's 'fixed' when I change to 44.1 KHz, but it's still annoying 'cause I like to use my DAW with 48Khz. So I will close this thread but still keeping track if this change in a near future. Thanks

**Comment by RomanPudashkin** [comment]
I'm going to reopen and close it as a duplicate of https://github.com/musescore/MuseScore/issues/18701 (so it's a known problem)

**Comment by mmendelson222** [comment]
OK I realize that there are a couple of different environments represented here (e.g. mac, ubuntu), but FWIW: 

I just installed MuseScore 4.4.2 and the problem is fixed for me.

**Comment by frob** [comment]
I think the real question people should be asking here is, why doesn't musescore support 48KHz?

**Comment by MarcSabatella** [comment]
It does now - you can set that in Edit / Preferences / Audio & MIDI.

**Comment by frob** [comment]
I also had to up the sample but that did it. Thank you, I was looking everywhere for that setting and couldn't find it.
