### ISSUE TITLE
Muse Sounds Violins 2 notes are delayed before stacatto

### ISSUE THREAD

**Issue by benwaffle** [musescore/MuseScore#23618]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

Open the attached mscz file, and hit play. Notice how the second note of each bar is delayed.

### Supporting files, videos and screenshots

[musescore-violins2-bug.mscz.zip](https://github.com/user-attachments/files/16228774/musescore-violins2-bug.mscz.zip)

<img width="924" alt="Screenshot 2024-07-14 at 5 05 57 PM" src="https://github.com/user-attachments/assets/365206aa-1e66-4108-a3e5-f81028853c57">

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.2, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 14.2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
We suspect this one might be a library-specific issue. Could you please raise it by contacting Muse Hub support?
https://support.musehub.com/hc/en-gb/requests/new
Many thanks!

**Comment by benwaffle** [comment]
ok, contacted
