### ISSUE TITLE
MuseScore Sounds are very quiet (Acoustic guitar)

### ISSUE THREAD

**Issue by piqpoq64** [musescore/MuseScore#23620]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

With 4.3.2 (AppImage version), I have to max out the Master fader to +12 dB in order to get the output levels in line with the rest of the system audio to be audible, leaving no headroom to increase the loudness. Verified used the levels display on an external audio interface; MuseScore is outputting about 20 dB lower than all other system audio when using the instruments from Muse Sounds Manager. 

EDIT: Can also be verified by playing a pure tone at 100% volume using sox, e.g., `play -n synth 30 sin 1000 vol 0dB` and comparing to MuseScore.

This seems similar to, but is not the same as, the bug with the choir (that bug specifically says choir voices).

### Supporting files, videos and screenshots

Any Acoustic Guitar part.

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

I was unable to check

### Operating system

Ubuntu 22.04.4 LTS

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by sampleeditor** [comment]
@piqpoq64 Just to clarify, using any Muse Sounds library or sound, even when setting the dynamic to fff results in too low of an output, but not so with a VST or MS Basic?

**Comment by Jojo-Schmitz** [comment]
It is esp. Muse Choir and apparently also the sound at hand here, not every sound

**Comment by sampleeditor** [comment]
@Jojo-Schmitz Muse Choir is naturally lower in volume and will be addressed soon. We just need to confirm that the other Muse Sounds libraries are playing back at a decent level for you?

**Comment by dcorson-ticino-com** [comment]
> @Jojo-Schmitz Muse Choir is naturally lower in volume and will be addressed soon. We just need to confirm that the other Muse Sounds libraries are playing back at a decent level for you?

We have heard many things in the last months here.
I can not speak for others and other libraries, but the violas in MuseStrings are all too quiet and need to be turned up in the mixer to be heard at reasonable relative volumes to the other strings. I have them up about 6db in the mixer every time.

**Comment by sampleeditor** [comment]
@Jojo-Schmitz We are working through many of these things and appreciate your input and patience :) I will mention volume levels to the Muse Sounds team. We have to carefully balance the natural recording level of the Violas to the rest of the Muse Strings, as they are likely from the same space and recording session, but we can look at levels on a per library basis, such as choirs, and bring them up.

**Comment by DaddyLudwig** [comment]
I also find that I need to turn up the solo cello sound to about +3.3 dB to balance with anything really that isn’t another cello. Cello Piano duo at 0 mixer adjustment, can’t hear the cello well, the piano overwhelms it. With the cello at +3.3 dB and the piano at 0 dB, they are more equal in sound.

**Comment by bkunda** [comment]
This issue seems to be related to the libraries themselves, so will close it here for now. 
It'd be best if it was raised separately via the Hub support (if using v.2), or otherwise here: https://support.musehub.com/hc/en-gb/requests/new).
