### ISSUE TITLE
Error al mostrar las paletas y el centro de inicio en Musescore 3.

### ISSUE THREAD

**Issue by Slimjess** [musescore/MuseScore#23635]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

Al abrir Musescore 3, no están visibles las paletas ni el centro de inicio. Están cargadas, ya que me permite cambiarlas de lugar , pero no se pueden ver. En Musescore 4 las paletas se ven perfectamente.

He vuelto a los ajustes de fábrica y reinstalado varias veces, pero nunca se soluciona.
Windows10.

### Supporting files, videos and screenshots

Musescore 3
![Paletas 3](https://github.com/user-attachments/assets/fe796fb3-40fd-41a1-be86-508e49ea4bc6)
Musescore 4
![Paletas 4](https://github.com/user-attachments/assets/90d6bc38-7a4f-4fe7-b1e1-a43afb972ebe)

### What is the latest version of MuseScore Studio where this issue is present?

Musescore 3.6.2

### Regression

I was unable to check

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
As gar as this ropository here is concerned MuseScore 3 is dead, but feel free to report this issue over on https://github.com/Jojo-Schmitz/MuseScore/issues/new/choose
It might be an issue with your graphics driver, esp. whether it supports OpenGL

**Comment by cbjeukendrup** [comment]
Since MuseScore 3 is out of support, and it is working correctly in MuseScore 4, I'm afraid there is not much you can do here, so I'll have to close this issue.
Of course, we recommend that you switch to MuseScore 4 as soon as possible, but if you have pressing reasons to keep using MuseScore 3, you might be interested in [MuseScore 3 evolution](https://sites.google.com/view/musescore-3-evolution/), an unofficial community project that builds upon MuseScore 3 and contains _some_ of the improvements that are found in MuseScore 4. 
We'd be interested to hear what's preventing you from switching to MuseScore 4. Feel free to let us know in a comment on this issue.

**Comment by Jojo-Schmitz** [comment]
Rather https://github.com/Jojo-Schmitz/MuseScore/wiki ;-)

**Comment by Slimjess** [comment]
> Dado que MuseScore 3 ya no recibe soporte y funciona correctamente en MuseScore 4, me temo que no hay mucho que podamos hacer aquí, por lo que tendré que cerrar este problema. Por supuesto, le recomendamos que cambie a MuseScore 4 lo antes posible, pero si tiene razones urgentes para seguir usando MuseScore 3, puede que le interese [MuseScore 3 evolution](https://sites.google.com/view/musescore-3-evolution/) , un proyecto comunitario no oficial que se basa en MuseScore 3 y contiene _algunas_ de las mejoras que se encuentran en MuseScore 4, así como algunas correcciones para mantenerlo compatible con los sistemas operativos modernos. Nos interesaría saber qué le impide cambiar a MuseScore 4. No dude en hacérnoslo saber en un comentario sobre este problema.

La razón por la que Musescore 4 no es operativo para mí es el elevado número de partituras con el que trabajo. Tenerlas recogidas en un mismo espacio de trabajo me ayuda a compararlas y poder trabajar de forma más ágil con ellas. Tener una ventana aislada para cada partitura no es para nada operativo ni eficaz.

**Comment by cbjeukendrup** [comment]
I see. Fortunately, that is definitely going to be fixed in a future update!

**Comment by Slimjess** [comment]
> Mejor https://github.com/Jojo-Schmitz/MuseScore/wiki ;-)

Buenas tardes,

Después de descargar e instalar la versión Evolution, he podido comprobar que no se soluciona el tema de las paletas. En esta versión también son invisibles.

Gracias por intentarlo. Saludos cordiales.

**Comment by Jojo-Schmitz** [comment]
Then report it at https://github.com/Jojo-Schmitz/MuseScore/issues/new/choose
Preferably in English ;-)

**Comment by Slimjess** [comment]
> Entonces repórtalo en https://github.com/Jojo-Schmitz/MuseScore/issues/new/choose Preferiblemente en inglés ;-)

Reportado
