### ISSUE TITLE
Harp Pedals breaking multi measure rests

### ISSUE THREAD

**Issue by Postoli** [musescore/MuseScore#23645]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Insert Harp pedals (diagram or text)
2. Click M to turn on multi measure rests
3. Note how the multi measure rest has been broken by the harp pedals

### Supporting files, videos and screenshots

![Image 16-7-2024 at 2 46 pm](https://github.com/user-attachments/assets/5e070a31-a90d-46db-b829-f69b3527d10b)

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2-241630832

### Regression

I was unable to check

### Operating system

macOS 14.1

### Additional context

According to Marc Sabetella:
"multimeasure rests shouldn’t break for these.  There are already exceptions made for several other element types, this one should be added to the list.  Please report this to the developers by opening an issue on GitHub."

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Postoli** [comment]
Having the same issue again. Regression?

<img width="312" height="210" alt="Image" src="https://github.com/user-attachments/assets/ed484eac-80c9-4cc6-892a-3d558b3bf29a" />

**Comment by FrancRos31** [comment]
> Having the same issue again. Regression?

Seems it is. However, there's a different bug on my side:

https://github.com/user-attachments/assets/d50d3cd8-0de2-4e85-b71c-78f05893646c

OS: Windows 10 Version 22H2 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.7.0-260219043, revision: github-musescore-musescore-bb01dd2

**Comment by FrancRos31** [comment]
@Postoli I think this ticket can be reopened.

**Comment by Postoli** [comment]
@FrancRos31 agreed, though looks like I don't have permission to do that. @mike-spa ?

**Comment by FrancRos31** [comment]
Before I forget completely, I'll make another attempt :) 
@zacjansheski, can you help us?

**Comment by zacjansheski** [comment]
Opened a fresh report
