### ISSUE TITLE
Muse Sounds playback is really loud when not assigning any dynamics in master (regression)

### ISSUE THREAD

**Issue by metasekk** [musescore/MuseScore#23642]
### Issue type

General playback bug

### Description with steps to reproduce

Previously (before 25/06, https://github.com/musescore/MuseScore/commit/a6a2bd8770d8d982e18ea8b85187560b80156943), not assigning any dynamics to a staff resulted in a "default" dynamics seemingly between _mf_ and _mp_ (same as MS3, I suspect).

In recent 4.4 builds (after 25/06, https://github.com/musescore/MuseScore/commit/a6a2bd8770d8d982e18ea8b85187560b80156943), playback is very loud instead, as though the default was now somewhere above _fff_.

I tracked the regression, it happened between 25/06 and 26/06, and more precisely between https://github.com/musescore/MuseScore/commit/4c65e4258ac354f3bc370f0cd594c5cbb9a41cd9 (no regression) and https://github.com/musescore/MuseScore/commit/a6a2bd8770d8d982e18ea8b85187560b80156943 (regression). Therefore, it seems to be **an unforeseen side effect introduced by #23247**.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/3716575c-9fc5-453d-8da6-b5c134d72253

### What is the latest version of MuseScore Studio where this issue is present?

Master (4.4), where it has been happening since 25/06/2024. Did **not occur** before (4.3 in particular).

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Win10 (22H2); RAM: 16Go; CPU: Intel Core i5-9300H

### Additional context

Can only be heard when using Muse Sounds, not VSTi nor MS Basic.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
Fixed in #23715

**Comment by DmitryArefiev** [comment]
@metasekk Should be fine in #23715. Please recheck if I missed something
