### ISSUE TITLE
MuseSounds trombone drastic change in dynamics

### ISSUE THREAD

**Issue by SiposAttila1995** [musescore/MuseScore#23669]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

I have a simple trombone melody made out of eighth notes, with crescendo and diminuendo. I've noticed that if I play it less than tempo quarter note = 100 the playback sounds natural. If I play it with >= 100 there is a sudden unnatural change in the dynamics.

See the attached screen recording.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/24d6a7b6-e008-466e-a046-e19352a2e36f

[240715_cresc.zip](https://github.com/user-attachments/files/16283203/240715_cresc.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0.242000306

### Regression

I was unable to check

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
@matthewreadbass @sampleeditor my thinking is that this one might need to be solved at the library level (pls correct me if I'm wrong). 
@SiposAttila1995 could you please raise this from within the Hub (if you are using v.2 already)? If not, then pls raise a ticket here: https://support.musehub.com/hc/en-gb/requests/new
Thank you.

**Comment by SiposAttila1995** [comment]
@bkunda Sure, I sent the bug report through the Hub.

**Comment by bmarwell** [comment]
I also added https://support.musehub.com/hc/en-gb/requests/13102 since this is still not solved :(
