### ISSUE TITLE
Hovering over most articulations in palette, info text says "Articulation"

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#23660]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. In Master, check text that appears when hovering over articulations in palette

For example, hovering over Accent should read "Accent"

On Windows I had to do a factory reset to reproduce

### Supporting files, videos and screenshots

![Screenshot 2024-07-17 141237](https://github.com/user-attachments/assets/a6df2b30-a41a-470b-b266-1eb9eda3c452)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241990305, revision: github-musescore-musescore-3b83778

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

All

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
@XiaoMigros This might be one for you to look at :)

**Comment by XiaoMigros** [comment]
Yes, thanks, I'll take this!
