### ISSUE TITLE
View Timeline freezes program

### ISSUE THREAD

**Issue by dulciepercy** [musescore/MuseScore#23674]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Open a score or make a new one
2. Select Menu-View-Timeline, or select F12 to view timeline
3. watch as program freezes

### Supporting files, videos and screenshots

[diagnostic musescore.zip](https://github.com/user-attachments/files/16285642/diagnostic.musescore.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242000306, revision: github-musescore-musescore-8e3b4f2

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
Only occurs on windows

@igorkorsukov looks like this resurfaced since closing https://github.com/musescore/MuseScore/issues/22415

**Comment by igorkorsukov** [comment]
@zacjansheski  please check https://github.com/musescore/MuseScore/pull/23762

**Comment by DmitryArefiev** [comment]
Fixed in #23762
