### ISSUE TITLE
insert measure doesnt move clef, if it is after barline

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#23676]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. write clef
2. set it "after barline"
3. insert measure before measure with clef
4. see - clef remains in measure, where it was before

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/d327bb96-d333-4f93-966e-3bb65ada04d9

### What is the latest version of MuseScore Studio where this issue is present?

master

### Regression

I was unable to check

### Operating system

Ubuntu 22.04

### Additional context

I guess, we forgot this case (clef after barline), when we were working on #19415 

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
Fixed in #23619
