### ISSUE TITLE
Some layout and engraving differences when import 3.6.2 score (one score)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#23684]
### Issue type

Import/export issue

### Description with steps to reproduce

1. Open [La_Campanella_-_Grandes_Etudes_de_Paganini_No._3_-_Franz_Liszt.zip](https://github.com/user-attachments/files/16312319/La_Campanella_-_Grandes_Etudes_de_Paganini_No._3_-_Franz_Liszt.zip) in 3.6.2 and 4.4
2. Compare results

### Supporting files, videos and screenshots
![Capture](https://github.com/user-attachments/assets/c3a404a4-a59d-4de9-880d-02d29000a29e)
![Capture2](https://github.com/user-attachments/assets/01d0a818-28de-4af7-90e5-2fec7ed51e77)

https://github.com/user-attachments/assets/31fcfec6-d25e-4c37-bc63-c49c810a7f1d

### What is the latest version of MuseScore Studio where this issue is present?

4.4 master

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by mike-spa** [comment]
This is not a bug, it is literally the result of the fact that horizontal spacing was completely rewritten in version 4.0. It is totally expected that in version 4 the default number of measures in any given given system may be different than what it was in 3.6. This case is a bit unlucky in that new spacing system fitted just one less measure in the first page, but that measure happened to contain a page break, which then caused the next page to be almost empty. Nothing we can do about that. 

[Well, one thing we could do is make the whole thing even smarter and act predictively, i.e. don't break the page at measure X if measure X+1 has a page break. But that is a long stretch away from our current capabilities.]
