### ISSUE TITLE
Builds for Windows crash on start (PRs and Nightly)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#23687]
### Issue type

Other type of issue

### Description with steps to reproduce

Open https://github.com/musescore/MuseScore/actions/runs/10009174225

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/bf9f3b02-5966-49bd-8bcf-c793547b6232

### What is the latest version of MuseScore Studio where this issue is present?

4.4 master

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 10

### Additional context
[1520f419-48a5-4947-9c4f-e35bb90b8d22.dmp](https://github.com/user-attachments/files/16313590/1520f419-48a5-4947-9c4f-e35bb90b8d22.dmp)

[MuseScore_240719_174828.log](https://github.com/user-attachments/files/16313593/MuseScore_240719_174828.log)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
I can't reproduce

**Comment by Jojo-Schmitz** [comment]
OK, mine is Windows 11 too

**Comment by cbjeukendrup** [comment]
It is this one on Sentry: https://sentry.musescore.org/musescore/sandbox/issues/148159/?query=is%3Aunresolved

That code was introduced by https://github.com/musescore/MuseScore/pull/23664. It is crashing in `extensionsconfiguration.cpp:153` at `.size()`. 
@igorkorsukov FYI :)

**Comment by Jojo-Schmitz** [comment]
So it may depend on which plugins are installed?

**Comment by cbjeukendrup** [comment]
This might be something that occurs when you have previously used a different development build, that produced a plugin config file that is incompatible with the latest format. So perhaps after a factory reset it doesn't crash anymore and the problem cannot be reproduced anymore when using only new builds. That's just a completely unverified guess though, but might lead to a workaround, and to an explanation of why some can reproduce it and some not.

**Comment by Jojo-Schmitz** [comment]
Or maybe just remove that plugin config file, config.json in your Plugins directory
