### ISSUE TITLE
Font size in PDF export differs from editor and other exports

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#23692]
### Issue type

Import/export issue

### Description with steps to reproduce

1. Add text element to the score.
2. Set to a text font other than Edwin.
3. Export to PDF and compare it with editor and PNG export

### Supporting files, videos and screenshots

PDF Export:
![PDF Export](https://github.com/user-attachments/assets/a72757c0-b551-4f23-bb1b-cb0822e627f4)

PNG Export:
![PNG Export](https://github.com/user-attachments/assets/fd2a8787-fd56-4362-ae1a-118908860ad2)

Compare:
![Compare](https://github.com/user-attachments/assets/066662fb-deee-4b44-9065-86b80a21af9e)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242010305, revision: github-musescore-musescore-5c912b2

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 11 23H2

### Additional context

Possibly related to #23655, but it seems that only the text font was affected in my environment, so I logged this as a separate issue.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by igorkorsukov** [comment]
I can't reproduce 

![image](https://github.com/user-attachments/assets/4e31cd90-0e70-42e2-8273-516004fd0a2c)

@nmu-nyasan please re-check

@DmitryArefiev  please confirm

**Comment by nmu-nyasan** [comment]
@igorkorsukov
It still occurs in the latest nightly builds.
However, it appears to depend on the font being used; it happens with some fonts and not with others. For common Western fonts, I confirmed that it occurs with the Arial font.
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/d6f65e57-8299-404e-8d85-85213a38a0e7">
Additionally, it does not seem to happen when the display scaling is set to 100%.
