### ISSUE TITLE
The track name is Hand Cymbals instead of Cymbals

### ISSUE THREAD

**Issue by scoreorder** [musescore/MuseScore#23699]
### Issue type

Other type of issue

### Description with steps to reproduce

1. Create new score
2. Add Hand Cymbals instrument

The track name is Hand Cymbals instead of Cymbals. It is not common to use the instrument name Hand Cymbals in orchestral scores. It is common to use the instrument name Cymbals. I propose to change the track name Hand Cymbals to Cymbals.

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/ce578412-f13f-4f19-ade8-ea70b672d20d)

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
Using "Hand Cymbal" is a concious choice to diffentiate the instrument from "Suspended Cymbal" or a drum kit's "Crash Cymbal"

https://en.wikipedia.org/wiki/Clash_cymbals

There are several "correct" names for this instrument, so this is more-so an opinion rather than a bug.
