### ISSUE TITLE
Crash when clicking a piano keyboard key after adding 2nd instrument

### ISSUE THREAD

**Issue by vvahut** [musescore/MuseScore#23704]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Create a new score with an instrument, e.g. flute
2. Make piano keyboard visible (View -> Piano keyboard)
3. Click a note from the toolbar (e.g. Quarter note)
4. Add a 2nd instrument, e.g. flute
5. Click some piano key from the piano keyboard
6. *crash*

### Supporting files, videos and screenshots

I don't think additional files are necessary here, but I might as well provide a screenshot of the state before the piano key click.
![Screenshot from 2024-07-21 09-34-00](https://github.com/user-attachments/assets/5f487ec3-ce9d-4658-a2dd-f925d8b1acf9)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Ubuntu 22.04.4 LTS, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

### Regression

I was unable to check

### Operating system

Ubuntu 22.04.4 LTS

### Additional context

Bug exists also in:
OS: Ubuntu 22.04.4 LTS, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242030305, revision: github-musescore-musescore-cd25d06

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by unelma** [comment]
Replicated successfully following exactly the given prescription.

Version: OS: macOS 13.6, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

**Comment by bkunda** [comment]
It strikes me that note input mode should be deactivated when inserting a new instrument.

**Comment by DmitryArefiev** [comment]
Fixed in #23750
