### ISSUE TITLE
VST FX Plug-in (Vienna Suite Pro) crashes MuseScore

### ISSUE THREAD

**Issue by TobyTwo32** [musescore/MuseScore#23713]
### Issue type

Crash or freeze

### Description with steps to reproduce

You'll need to get this paid VST to be to test (Vienna Suite Pro)

1. Open MuseScore with any orchestral Score.
2. Open mixer and choose the instrument you want to add FX plug-in (in this case Vienna Equalizer Pro X64)
3. Open the plug-in and choose the preset you want
4. Immediate crash
5. Sometimes step 3 doesn't work and crashes anyways

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/07e91262-ca94-437e-916b-993e1d885a52

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

If possible I can test with other plug-ins from FX library.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by TobyTwo32** [comment]
I did some playtesting it seems only the Vienna Equalizer Pro x64 crashes MuseScore. I tested the same VST in Audacity and it doesn't crash.

**Comment by bkunda** [comment]
@TobyTwo32 yesterday we merged a fix that _might_ fix this issue, but will need your help to see if it worked. 
Could you please re-test using the latest nightly? Many thanks!

**Comment by TobyTwo32** [comment]
@bkunda It is fixed on the latest 4.4 nightly, I used the portable version.

**Comment by zacjansheski** [comment]
Closing as fixed in nightly (per comment above)
