### ISSUE TITLE
MuseSampler 0.100 crashes MuseScore 4.4 with paid premium libraries (OT, Spitfire, etc)

### ISSUE THREAD

**Issue by TobyTwo32** [musescore/MuseScore#23722]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. MuseScore 4.4 bin
2. Choose any instrument
3. Choose said paid library instrument
4. Crash

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/e34c9e3b-4cdb-4de9-b8ad-79f65dfc4421

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Fristover** [comment]
Same here, will drop the diagnostic files over here...
[crash.zip](https://github.com/user-attachments/files/16337738/crash.zip)

**Comment by wizofaus** [comment]
Confirmed this only happens when using 4.4 with new MuseSampler library.  If you use 4.3 with new library or 4.4 with old, it's fine.

**Comment by bkunda** [comment]
This has been fixed on the sampler side.

**Comment by wizofaus** [comment]
Where do we get the new sampler?
