### ISSUE TITLE
Simile Marks Pasting Doesn't Work and Collides File

### ISSUE THREAD

**Issue by ElixirAmongUs** [musescore/MuseScore#23742]
### Issue type

File corruption

### Description with steps to reproduce

1. Go to a score
2. Add Simile Marks
3. Copy
4. Delete everything you copied
5. Paste it back
6. Simile marks disappear and rests are not shown either

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/c6c2f41b-e8f9-4288-ac16-a22ea4349097)

### What is the latest version of MuseScore Studio where this issue is present?

v4.3.2

### Regression

I was unable to check

### Operating system

Lenovo

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
I think with "simile marks" you refer to what we tend to call "measure repeats", is that right?

**Comment by bkunda** [comment]
@cbjeukendrup pls investigate

**Comment by cbjeukendrup** [comment]
@ElixirAmongUs I can't really replicate anything like what's shown in your screenshot. It would be very helpful if you could share a screen recording or video of what you do exactly, and if you could upload the score in question (wrap it in a ZIP file, or rename it by replacing `.mscz` with `.zip` so that GitHub allows you to upload it).

**Comment by zacjansheski** [comment]
Closing, no response

**Comment by ElixirAmongUs** [comment]
You need to paste the simile marks OVER MEASUREMENTS.

**Comment by cbjeukendrup** [comment]
@ElixirAmongUs thanks! I think I see the problem now. I've created a slightly clarified version of this issue here: https://github.com/musescore/MuseScore/issues/24186
Let's refer to that issue instead. Thanks for discovering this problem!

**Comment by ElixirAmongUs** [comment]
Thank You!
