### ISSUE TITLE
Can't select "swing" text

### ISSUE THREAD

**Issue by sheetsofsound** [musescore/MuseScore#23758]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

With visibility set to not show invisible, I did the following:

- Added tempo
- added swing at 55%
- made both invisible
- toggled show visibility
- Can no longer select the swing text. When I do, it selects frame of the title instead

### Supporting files, videos and screenshots

[Using 12 step below displacement on C Blues.zip](https://github.com/user-attachments/files/16367238/Using.12.step.below.displacement.on.C.Blues.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

No.

### Operating system

windows 11

### Additional context

this has been a bug since 3.x

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by sheetsofsound** [comment]
https://github.com/user-attachments/assets/c2a22c6d-c810-411f-b0dc-e6030607d9e3

**Comment by bkunda** [comment]
https://github.com/musescore/MuseScore/pull/21438 should have reinstated the ability to Ctrl+Click an item that's being hidden beneath a frame (which is most likely what's happening in the present case). 
So we can mark this as resolved for now. Happy to reopen if this fix doesn't work for you @sheetsofsound!

**Comment by MarcSabatella** [comment]
It's another workaround (in addition to the workaround of using keyboard navigation, or sending the frame to back of the stacking order).  But, it shouldn't be necessary - it's still an issue that the frame is so high in the stacking order to begin with, or that the code can't sort out that the text should be preferred for selection.

There was a related issue involving images - see https://github.com/musescore/MuseScore/issues/12934 and https://github.com/musescore/MuseScore/issues/13664 - that was solved by adding a special case for the case of frame vs image (https://github.com/musescore/MuseScore/pull/15139/files#diff-26bd3810778f254978e70572c39acd61846cc6e935d6376e25848725b8597e3f).  What's weird is, the code right above the changed lines looks like it is trying to do the same for text, but for whatever reason, it doesn't seem to work here.

**Comment by sheetsofsound** [comment]
So you're saying ctrl click will select the swing text?

**Comment by cbjeukendrup** [comment]
Yes, Ctrl+Click will cycle through elements at the same location. That was broken in current releases, but will be fixed in 4.4. 

Invisible elements are placed beneath visible elements; see `NotationInteraction::elementIsLess` and `elementLessThan`. I don't really have an opinion on whether that makes sense or should be changed.

**Comment by scorster** [comment]
I haven't tested for other instances, but it I drag a guitar fretboard diagram half way into a vertical frame, I can drag it by the portion that's outside of the frame. I have to use control/command to select it in the z axis. Then I can drag it. This is considered good for the current state of play? 

BTW, when I control/command click the fretboard diagram (at a point within the frame) that incurs a very buggy drag of the frame size, like dragging the frames risize handle, but prone to running out of control—I reported this issue elsewhere, but don't presently have time to search for it.
