### ISSUE TITLE
Measure numbers collide with other elements

### ISSUE THREAD

**Issue by Tadaboody** [musescore/MuseScore#23760]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

with measure numbers on for every measure, the number collides with notes under the clef, clef symbols like treble 8va and more - seriously hurting readability

### Supporting files, videos and screenshots

<img width="363" alt="image" src="https://github.com/user-attachments/assets/8c24bbfe-1fe8-43d5-afb6-3002de558f92">
<img width="468" alt="image" src="https://github.com/user-attachments/assets/a1c44739-6c3f-4d86-b235-9d4ba036cf05">

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 12.7, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241231433, revision: github-musescore-musescore-5f36e74

### Regression

No.

### Operating system

macOS 12

### Additional context

The clef one is not so bad, and the note collisions  can be fixed manually by moving the measure number to be aligned with the bar to its middle, but gets tedious when the score includes a double digit number of these happenings

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Mikey12045** [comment]
I'm having the same problem in 4.7. Measure numbers collide with accidentals and slurs.

<img width="260" height="162" alt="Image" src="https://github.com/user-attachments/assets/536b6b6f-d23f-4d68-9869-14685e012f20" />

<img width="330" height="208" alt="Image" src="https://github.com/user-attachments/assets/783c4dd2-7e75-4e4d-8bb6-949b3a567119" />

**Comment by MarcSabatella** [comment]
I cannot reproduce this - for me the measure numbers do move to avoid notes.  Are you sure you didn't disable autoplace for those numbers?  Please ZIP and attach the score with the problem.

**Comment by Mikey12045** [comment]
I've already fixed the ones in that doc. Auto Place is checked, though, both in that piece and in my Starting Doc (fake template.) If it shows up in the next piece, I'll go further. Thanks!
