### ISSUE TITLE
MuseScore 4.4 can crash if you close score before waiting for audio samples to load

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23799]
### Issue type

Crash or freeze

### Description with steps to reproduce

1) ensure you have no other MuseScore processes running 
2) start 4.4
3) open a largish score that uses Muse Sounds, but before it's finished loading audio samples, close the *tab* for the score, to return to the Home Screen
4) wait a little...
5) Process exits unexpectedly

### Supporting files, videos and screenshots

N/A

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

May not happen with every possible score using Muse Sounds, can attach an example if it's hard to reproduce.
Note if there are other MuseScore processes running you won't really notice the crash because the process exits on closing the score tab anyway. 

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
I haven't been able to reproduce this yet.  We have encountered and fixed in the past.  If you have an example that consistently reproduces the crash that would be very helpful.

https://github.com/musescore/MuseScore/issues/19736
https://github.com/musescore/MuseScore/issues/13933

**Comment by wizofaus** [comment]
Haven't had it happen with the latest nightly.

**Comment by zacjansheski** [comment]
Closing as not present in nightly
