### ISSUE TITLE
When entering a time code in the playback toolbar, it jumps to a different time than what you enter

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#23793]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Open score
2. Enter some number of seconds in the playback toolbar
3. Once you finish typing, it changes to something different than what you typed. To what it changes depends on the BPM of the score. 

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/b7df866b-1283-4b4d-9097-acdf75767c87

At the beginning of this video, I try to type "17", and then I try to type "12". 

### What is the latest version of MuseScore Studio where this issue is present?

73cc0009d99b76d1070e2155b22cc9d79a696fdc

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

\*

### Additional context

The cause is that it calls `seek(msecs_t`, but that overload does not exist; we only have `seek(secs_t` and `seek(midi::tick_t`. Because `msecs_t` is an integral type and `midi::tick_t` too, as opposed to `secs_t` which is `double`, the `midi::tick_t` overload is taken; so the milliseconds are interpreted as midi ticks, which results in wrong values.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
A fix for this will conflict with https://github.com/musescore/MuseScore/pull/19038, so we should perhaps wait for that to be merged first. Alternatively, cherry-pick parts of that PR into the fix for this issue.

**Comment by DmitryArefiev** [comment]
Fixed in #23794
