### ISSUE TITLE
Scores with multibyte characters in the name do not open in a new window (Cyrillic names also)

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#23811]
### Issue type

Opening/saving issue

### Description with steps to reproduce
**Case 1**:
1. Open MuseScore Studio and open any score.
2. Return to the “Score” tab with the score still open.
3. Open a score whose names contain multibyte characters.

**Case 2**:
1. (MuseScore Studio is not run)
2. Open a score whose names contain multibyte characters from Windows Explorer

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/ea05a40f-6674-4100-9c63-4ee0483e2686

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242110305, revision: github-musescore-musescore-bd4bcee

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 11 23H2

### Additional context

The dialog telling you that the file failed to load shows a garbled string of UTF-8 characters interpreted as Shift_JIS.
![image](https://github.com/user-attachments/assets/b3c1585a-a652-4bac-bf17-dd905dbaea78)
https://tools.m-bsys.com/dev_tools/char_corruption_for_developer.php
![tools m-bsys com_dev_tools_char_corruption_for_developer php](https://github.com/user-attachments/assets/58577dce-7449-49b6-9798-dfe6715d7e5e)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by nmu-nyasan** [comment]
This issue also occurs when double-clicking a file from Explorer.
The only way to open a file with multibyte characters in its filename is to start MuseScore Studio with no other scores open and select the score listed on the “Scores” tab.
If the file contains multibyte characters in its filename, there is no way to open a score that is not listed on the “Scores” tab (e.g., an mscz file downloaded from the web), nor can you open more than one file at a time.

@bkunda @cbjeukendrup (sorry for mentioning)
I believe that if version 4.4 is released with this bug still present, it will cause confusion.
Could you please reconsider the priority and fix this before the 4.4 release?

**Comment by DmitryArefiev** [comment]
> This issue also occurs when double-clicking a file from Explorer.

Yes, I can reproduce it too

https://github.com/user-attachments/assets/2e25bd3d-de48-4095-9cbe-dbbef9f83466

@bkunda Since it occurs not only in multi-instance mode I propose to change it to **P1**

**Comment by CarlGao4** [comment]
I described the issue more detailed and had guessed the cause of this issue in #24258
