### ISSUE TITLE
The last note of the part is cut off (SoundFont only)

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#23812]
### Issue type

General playback bug

### Description with steps to reproduce

1. Enter some notes.
2. It is easier to hear the problem if the reverb is turned off in the mixer.
3. Start playback.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/e33b6fde-a0b7-4898-97f8-9b56419c1be8

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241990630, revision: github-musescore-musescore-d553d91

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11 23H2

### Additional context

Only occurs on audio test builds in Discord announcements, not on nightly.
Occurs regardless of buffer size.
Does not occur with Muse Sounds.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
Fixed in #23851
