### ISSUE TITLE
Playback of musesounds instruments is delayed with lots of instruments (when using Rewind)

### ISSUE THREAD

**Issue by jcourtne** [musescore/MuseScore#23823]
### Issue type

General playback bug

### Description with steps to reproduce

1. Open musescore file
2. start playback and it works correctly
3. rewind to the beginning (or any point in the middle)
4. playback of musesounds instruments is delayed

Sometimes, this delay can last up to a measure (i.e. several seconds) before correct playback resumes.

In my experimentation, this does not occur with single-instrument scores.t

### Supporting files, videos and screenshots

This example isn't too bad
https://github.com/user-attachments/assets/727b1f6c-e363-402d-8f4a-9c90498ac7ce

second example 
https://github.com/user-attachments/assets/9b3fc036-c02e-4a9e-87f6-e8fdc1029e6c

This contains the first part (I didn't really want to share the whole score...)
[slow playback.zip](https://github.com/user-attachments/files/16414456/slow.playback.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

No.

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit)

### Additional context

The weirdest thing is it always works when you first open the score, but not when you rewind/select a particular playback point.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
Roman says it's expected for now, the rewind is a heavy operation on muse sampler side..

@konradglas Can this be improved? 


(also, the issue should be rechecked when musesampler v100 will be released)

**Comment by DmitryArefiev** [comment]
@jcourtne What is your hardware? (CPU, RAM)

**Comment by jcourtne** [comment]
@DmitryArefiev here's the system info
```
System Information report written at: 08/02/24 09:13:57
[System Summary]

Item	Value	
OS Name	Microsoft Windows 10 Home	
Version	10.0.19045 Build 19045	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
ystem Manufacturer	ASUS	
System Model	System Product Name	
System Type	x64-based PC	
System SKU	SKU	
Processor	AMD Ryzen 9 5900X 12-Core Processor, 3701 Mhz, 12 Core(s), 24 Logical Processor(s)	
BIOS Version/Date	American Megatrends Inc. 3402, 3/22/2021	
SMBIOS Version	3.3	
Embedded Controller Version	255.255	
BIOS Mode	UEFI	
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.	
BaseBoard Product	ROG CROSSHAIR VIII HERO	
BaseBoard Version	Rev X.0x	
Platform Role	Desktop	
Secure Boot State	Off	
PCR7 Configuration	Binding Not Possible	
Hardware Abstraction Layer	Version = "10.0.19041.3636"	
Installed Physical Memory (RAM)	128 GB	
Total Physical Memory	128 GB	
Available Physical Memory	117 GB	
Total Virtual Memory	147 GB	
Available Virtual Memory	134 GB	
Page File Space	19.0 GB	
Page File	C:\pagefile.sys	
Kernel DMA Protection	Off	
Virtualization-based security	Not enabled	
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not Modern Standby, Un-allowed DMA capable bus/device(s) detected, TPM is not usable	
Hyper-V - VM Monitor Mode Extensions	Yes	
Hyper-V - Second Level Address Translation Extensions	Yes	
Hyper-V - Virtualization Enabled in Firmware	No	
Hyper-V - Data Execution Protection	Yes	
```

**Comment by wizofaus** [comment]
There's already a v100 version floating around you can download and I can confirm it significantly reduces these sorts of delays.

**Comment by jcourtne** [comment]
With the upgrade to 4.4, I am no longer seeing this issue.
