### ISSUE TITLE
Trombone scoops and falls don't work correctly

### ISSUE THREAD

**Issue by xman2156** [musescore/MuseScore#23826]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

1. Create score with Muse Sounds trombone
2. Add fall, doit, plop, etc.
Actual behavior: Either plays the note at a louder dynamic with no modifier, plays the note at a louder dynamic but does play the modifier, or plays the note with no modifier at all.
Expected behavior: Falls/scoops are actually played along with no change to dynamic

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/343aedb7-104b-409a-aed3-cb9182989c5a
[Trombone Falls.zip](https://github.com/user-attachments/files/16418027/Trombone.Falls.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0-242110829, revision: b820226

### Regression

No.

### Operating system

macOS 14.5

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
As this is a Muse Sounds specific issue, could you please raise it by contacting customer support from within the Muse Hub? (Or alternatively, by using this form? https://support.musehub.com/hc/en-gb/requests/new).
Thanks!
