### ISSUE TITLE
Score crashes when deleting time signature

### ISSUE THREAD

**Issue by mhogrefe** [musescore/MuseScore#23839]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Open the attached score, crash.mscz.
2. Select the 3/4 time signature in the Violin 1 staff.
3. Hit backspace to attempt to delete the time signature.
4. Observe that MuseScore crashes.

I've attached the error log. It might be from the crash of a slightly older file than the one I'm attaching; after deliberately triggering this crash several times, I can't seem to find the most recent logs.

I'm not sure exactly how to reproduce this from scratch. I created the example file by reducing a larger score.

### Supporting files, videos and screenshots

[crash.mscz.zip](https://github.com/user-attachments/files/16432812/crash.mscz.zip)
[crash-log.txt](https://github.com/user-attachments/files/16432813/crash-log.txt)

https://github.com/user-attachments/assets/a0095ead-91eb-46ea-ae75-f2b0b214c8cf

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.3, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

### Regression

I was unable to check

### Operating system

macOS 14.3

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
This crash does not occur in master/nightly.
https://musescore.org/en/nightly-builds
In the future, please check if issues are reproducible on the master/nightly branch before reporting here.  Thank you!
