### ISSUE TITLE
Note input from MIDI keyboard doesn't work for voices 2-4

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#23845]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Using a MIDI keyboard, input notes into voice 1
2. Switch to voice 2
3. Attempt to input notes with MIDI keyboard. Nothing happens.

The same behaviour is reproducible using voices 3 and 4.

Note input via computer keyboard and mouse are unaffected.  

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/6a9ed67a-f625-4ffa-93d7-3061561f15ef

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.5, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.0-242120301, revision: github-musescore-musescore-70c122e

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

macOS 14.5

### Additional context

Regression occurred between nightly builds from 25 July and 26 July 2024.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by RomanPudashkin** [comment]
Caused by https://github.com/musescore/MuseScore/pull/23750/commits/b7d9a0ceb5290b1bcc49e2296ae43b51be871fff
