### ISSUE TITLE
Copy score, including time signatures

### ISSUE THREAD

**Issue by LilithSilver** [musescore/MuseScore#23850]
### Your idea

Implement a feature to copy/paste all score properties, including time signatures and system elements.

### Problem to be solved

Currently, it's impossible to copy a complicated time signature structure, yet this is a frequent operation (at least for me). The time signatures must be manually reconstructed every single time. 

### Additional context

This request has been logged [here](https://musescore.org/en/node/165746) for many years, but the latest comments say to go to GitHub. I did not find a similar issue, so I thought I'd open one.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by avvvvve** [comment]
Hi @LilithSilver! This has already been requested in https://github.com/musescore/MuseScore/issues/15590. Since there's a lot of discussion on that issue already, I'm closing this one as a duplicate.
