### ISSUE TITLE
Opening "System text properties" duplicates system text in certain templates

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#23862]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

<img width="863" alt="image" src="https://github.com/user-attachments/assets/0789eb10-ff63-49dc-8110-f6b1426dee4d">

### Known templates where this happens

- Classical orchestra
- Symphony orchestra

### Steps to reproduce
1. Create a new score with a template listed above
2. Add a system text element (or the Swing element) to the score
3. Right click on it and select "System text properties..."
4. Hit OK in the dialog (you don't have to change anything)
5. See that the system text is duplicated.

If you try and delete the duplicated text, it deletes both. If you continue opening the dialog, more duplicates will be added. Undo produces strange results.

It's worth further investigation to make sure this is a template issue.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/e4405097-597e-456b-8976-47c9425a56a1

### What is the latest version of MuseScore Studio where this issue is present?

Nightly (and 4.3.2)

### Regression

Worked in 4.1.1, broken in 4.2.0

### Operating system

macOS 14.5

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
@zacjansheski pls check regression status

**Comment by zacjansheski** [comment]
Worked in 4.1.1, broken in 4.2.0
