### ISSUE TITLE
Crash when clicking on the accidental of an ornament

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#23860]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Add an ornament to a note on the score
2. Set the accidental to visible
3. Click on it

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/e45aa9e7-8917-4ca6-84d2-10322f103d79

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242120305, revision: github-musescore-musescore-70c122e

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

All

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
Confirm on my side. Occurs on all OSs. Will add video to the description

Thanks for logging!

**Comment by DmitryArefiev** [comment]
Fixed in #23866
