### ISSUE TITLE
[Issue - Big Report - musescore/Musescore] -  Gradual Accelerando Not Applied to Viola Motifs in String Quartet Arrangement on MuseScore

### ISSUE THREAD

**Issue by tmm88** [musescore/MuseScore#23872]
### Issue type

General playback bug

#### Description:
When orchestrating a string quartet using MuseScore, a long and gradual accelerando applied to viola motifs is not properly executed during playback. This issue occurs specifically when writing for a viola section within the context of a string quartet. Despite correctly inputting the accelerando notation over an extended passage, the playback does not reflect the intended gradual increase in tempo, resulting in a static tempo throughout the passage.

#### Steps to Reproduce:
1. Create a new string quartet score in MuseScore.
2. Write a motif or passage for the viola part.
3. Apply a long and gradual accelerando to the viola motif using the standard tempo change tools.
4. Play back the score to observe the tempo changes.

#### Expected Behavior:
The playback should gradually increase in tempo according to the accelerando applied, creating a seamless and natural tempo change that affects the entire passage.

#### Actual Behavior:
During playback, the accelerando is not correctly interpreted by the software. The tempo remains constant throughout the passage, ignoring the accelerando notation.

#### Impact:
This issue disrupts the creative process for composers and arrangers using MuseScore for string quartet arrangements. Accurate tempo changes are critical in creating expressive and dynamic performances, and the inability to realize these changes in playback can hinder the user’s ability to accurately preview their work.

#### Possible Workarounds:
- Manually adjusting tempo markings at multiple points in the score as a temporary solution, although this can be tedious and does not always produce a smooth transition.
- Exporting the score to another DAW (Digital Audio Workstation) for more precise tempo control, though this adds additional steps to the workflow.

#### Environment:
- **MuseScore Version:** [Musescore 4]
- **Operating System:** [Windows 11]
- **Hardware Specifications:** [Acer predator helios ph350-51]

#### Additional Notes:
This issue may be specific to how MuseScore handles tempo changes in particular contexts, such as specific instrument sections or when multiple tempo changes are applied simultaneously. It would be beneficial to investigate whether this issue occurs with other instruments or in different ensemble settings.

#### Suggested Actions:
It is recommended to address this playback inconsistency in a future update of MuseScore to enhance the functionality and reliability of tempo changes, particularly for users arranging for string quartets or other ensembles where such changes are common.

### Supporting files, videos and screenshots

[![Problems with accelerando in small orchestration setup in musescore](https://img.youtube.com/vi/cze_XLiv9MM/0.jpg)](https://www.youtube.com/watch?v=cze_XLiv9MM)

### What is the latest version of MuseScore Studio where this issue is present?

4

### Regression

No.

### Operating system

windows 11

### Additional context

I am familiar with MuseScore, having used it for some time, though mostly for simpler tasks. MuseScore is indeed a versatile and powerful tool for music notation, and it has evolved significantly over the years. If you've been using it primarily for straightforward projects, where people might not have explored its more advanced features. I am interested in getting more out of MuseScore or trying out specific features, such as advanced engraving, orchestration, or custom playback, 

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
Can you please upload a video showing a minimum example? 
It sounds like it's something that could be shown very quickly. The information you've provided above is actually beyond the scope of our issue reporting guidelines, which is making a quick triage of this quite difficult.

**Comment by tmm88** [comment]
I recently attempted to upload a video to my markdown, but unfortunately, it was too large to upload successfully. However, in working on my latest project, I've encountered an issue that I wanted to share with you. I’ve accumulated a collection of around 200 to 300 musical motifs for the viola, which I intended to orchestrate for a string quartet. However, I've noticed that when these motifs are arranged for the quartet, certain elements don’t translate as well as I’d hoped—some parts fall out of range, and the overall texture doesn’t quite achieve the effect I was aiming for.

Despite this, I want to take a moment to congratulate you on the incredible developments happening with MuseScore 4. The software has become an indispensable tool for me, and I genuinely appreciate the hard work and dedication that has gone into making it what it is today. MuseScore’s progress is nothing short of inspiring, and I wish that all open-source projects could develop at the pace and with the quality that MuseScore is achieving. It’s a joy to work with, and I’m grateful for the continued improvements and features that make it such a powerful tool for musicians.

Keep up the fantastic work, and know that your efforts are truly appreciated. Cheers to the entire team!

**Comment by zacjansheski** [comment]
@tmm88 Thank you for all the kind words.

I believe you can accomplish what you are looking in your scores for by experimenting with a few things.
1.  Experiment with the playback property (percentage of tempo change)
2. Add more "checkpoint" tempo markings (they can be invisible)

If you are not sure how to get the desired results, consider searching the forums or asking for help there. https://musescore.org/en/forum

I will now close this issue. Please understand, github is a place for cut-and-dry bugs and tasks, not superlative language, high art discussion, or lengthy niceties.  Although it seems to come from a place of kindness, this report has several more paragraphs than necessary for us to address an issue.  When filing a bug report examples and details must be as minimal as possible.
