### ISSUE TITLE
The track name is "Concert Toms" instead of "Tom-toms"

### ISSUE THREAD

**Issue by scoreorder** [musescore/MuseScore#23877]
### Issue type

Other type of issue

### Description with steps to reproduce

1. Create new score
2. Add "Concert Toms" instrument

The track name is "Concert Toms" instead of "Tom-toms". It is not common to use the instrument name "Concert Toms" in orchestral scores. It is common to use the instrument name "Tom-toms". I propose to change the track name "Concert Toms" to "Tom-toms", the long name "Toms" to "Tom-toms", the short name "Toms" to "Tom-t." and the description "Concert tom-toms." to "Tom-toms.".

See https://www.breitkopf.com/work/9276/concerto-in-f

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/9f1ee383-9625-46eb-9076-36a2f97089f6)

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

No.

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
This is pretty strictly opinion and I don't think we should change it.

The term "Tom-tom" is usually associated with the double headed drum-kit toms

The term "Concert toms" is generally used for the single headed drums played in the back of the orchestra / concert band

**Comment by scoreorder** [comment]
The instrument name "Tom-toms" refers to single-headed or double-headed tom-toms. The instrument name "Concert Toms" refers to single-headed tom-toms or to single-headed or double-headed tom-toms for concert use.

It is not common to use the instrument name "Concert Toms" in orchestral scores. It is common to use the instrument name "Tom-toms". The major music publishers use the instrument name "Tom-toms" in orchestral scores. I propose to use the instrument name that is common to use in orchestral scores.

**Comment by bkunda** [comment]
There have been a number of similar requests for specific instrument name changes before. 

The way to solve this isn't to address each request one at a time (especially where there is real contention about the different ways the same instrument can be termed), but to develop a more systemic solution. Two ideas include: 

- Enabling more flexibility when using search terms, so typing "Tom-toms" could still retrieve "Concert toms"
- Building a system that allowed the user to effectively bypass the hardcoded instrument names with those of their choosing. This could be particularly useful for publishing houses who routinely wish to use certain instrument names that differ from ours, or indeed for stylistic/locational preferences (E.g. choosing to use French names, even if the application isn't being run in French). 

Closing this issue in preference for a more systemic solutions that should provide much greater flexibility for users in cases like these.
