### ISSUE TITLE
[musicxml] Stem colors not imported

### ISSUE THREAD

**Issue by jacobtylerwalls** [musescore/MuseScore#23885]
### Issue type

Import/export issue

### Description with steps to reproduce

Open the attached file.
Notice stem color (red) does not appear.

### Supporting files, videos and screenshots

[stem_color.txt](https://github.com/user-attachments/files/16482661/stem_color.txt)

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2.241630832

### Regression

No.

### Operating system

macOS

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by rettinghaus** [comment]
Fixed with #21433, will be available in MuseScore 4.4.

**Comment by cbjeukendrup** [comment]
Thanks @rettinghaus!
