### ISSUE TITLE
Ability to place l.v. ties in expected location and configure playback duration

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#23924]
### Your idea

Would like the ability to easily select several notes and add an "l.v." tie to them such they appeared to be positioned like a tie branching off the notehead, rather than the current behaviour of appearing over the stem, and to then control how much they should cause the note duration to be extended by during playback.

### Problem to be solved

![image](https://github.com/user-attachments/assets/75a103de-0fb5-48a5-a595-15c17615541a)
Is a typical example of use the l.v. tie in piano or guitar writing to indicate that each note should be held down (piano) or plucked but not dampened (guitar) as long as possible or until the harmony changes.  Currently this a) is time-consuming to do given the default positioning of l.v. ties (and the inability to make them shorter) and b) doesn't affect playback at all.

### Additional context

For playback, just the ability to specify the "sounding duration" of the note, in ticks or beats or even as a % would be fine.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment]
https://github.com/musescore/MuseScore/issues/16726 covers this fine. Closing as duplicate.
The default placement is better in 4.4, which is a start.

**Comment by wizofaus** [comment]
#16726 doesn't cover playback at all, which is arguably the most useful thing...
