### ISSUE TITLE
Problems adding key signatures to a range

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#23936]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

Normally, adding a key signature to a range will add the change at the start of the range, and 'cancel' it (reverting to whatever key signature was previously in force) at the end. For example, starting with this:
![image](https://github.com/user-attachments/assets/21001766-3921-4985-9392-f001a8d51449)

If we add a D major key sig to the selected range, we get:
![image](https://github.com/user-attachments/assets/afda5d07-6ce9-4805-94c8-d23c6fdf9536)

Which seems fair enough.

However, if there is _already_ a key signature change at the end of the range, it will be overwritten. So this:
![image](https://github.com/user-attachments/assets/77020ea2-b5ed-4bed-9b99-37fd7e516cca)

Becomes this (overwriting the Ab with Bb):
![image](https://github.com/user-attachments/assets/15d7887c-c5fc-42af-987e-d365d4e8b94a)

A fun exception: in this same situation, if you replace the range with the _same_ key signature that is already there, then the key sig change at the end of the range is just deleted. So this:
![image](https://github.com/user-attachments/assets/980a4ae8-c5e0-4ab4-ba5d-faa0d497a16d)

Becomes this (if you apply D major):
![image](https://github.com/user-attachments/assets/a781c7e9-d880-49a8-8db4-4edac100e3b7)

It gets worse. If you try doing this repeatedly it'll get even more random, and sometimes I see the key signatures get shifted by a bar. _The horror ... the horror ..._

### Supporting files, videos and screenshots

See above

### What is the latest version of MuseScore Studio where this issue is present?

3.6 (at least) up until master

### Regression

No.

### Operating system

Linux (but presumably any)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by sammik** [comment]
Same happens to clefs and time signatures too.

(And after undo, range selection is extended by one measure, even if blue recangle doesnt looks like it is)
