### ISSUE TITLE
Odd results fp cresc. before D.S.

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#23940]
### Issue type

General playback bug

### Description with steps to reproduce

1. Create a score like in the video or open the attached file (in "additional context")
2. Play, note the dynamic drop on beat 3 of the bar before the D.S.  dynamic should drop on the note directly after beat one

Note: Occurs with MS Basic and Muse Sounds

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/dea880aa-eb89-45b2-bbd1-894faa97039d

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.4, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.0-242190301, revision: github-musescore-musescore-6945d85

### Regression

Yes, this works in **MuseScore 3.6.2**

### Operating system

Mac OS 14

### Additional context

[DS fp cresc.mscz.zip](https://github.com/user-attachments/files/16516454/DS.fp.cresc.mscz.zip)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
This is not a nightly regression. The reason why this differs from 4.3.2 is because we changed hairpin behavior for non SND instruments (such as Piano). If use **Violin**, the same **happens in 4.0 - 4.4**

4.4 master:

https://github.com/user-attachments/assets/3c5806a9-f492-4ed9-9bc1-d6e0999629ef


4.3.2:
https://github.com/user-attachments/assets/cd7a9461-3808-45ca-bb06-0dca5b6bd95f
