### ISSUE TITLE
Muse Sound playback froze when hide/change instrument in MuseScore

### ISSUE THREAD

**Issue by NathanGithub2013** [musescore/MuseScore#23976]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

1. Find a score that has multiple instruments
2. Start playback (all instrument uses Muse sound
3. Change or hide an instrument in the Instrument tab
Results: The audio playback glitches for a few second

### Supporting files, videos and screenshots

[Screen Record.zip](https://github.com/user-attachments/files/16571814/Screen.Record.zip)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore 4.3.2.241630831 OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I was unable to check

### Operating system

Windows 10

### Additional context

MuseScore Studio 4.4 with Muse Hub

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
Can you please confirm whether this _only_ occurs in Muse Sounds? (I.e. does it also do this when using VST or SoundFonts)? 

Could you also please provide your system specs? 

And one more request: if you could please also check this in the latest nightly, that info would be useful. 

Thanks!

**Comment by NathanGithub2013** [comment]
> Can you please confirm whether this _only_ occurs in Muse Sounds? (I.e. does it also do this when using VST or SoundFonts)?
> 
> Could you also please provide your system specs?
> 
> And one more request: if you could please also check this in the latest nightly, that info would be useful.
> 
> Thanks!

I had tried using SoundFont with MS Basic and it work fine
So only Muse Sound gliches

Specs:
Windows 10 Pro 22h2
CPU : intel Core i5 2530M
Ram : 8GB
SSD SATA 128GB

**Comment by mathesoncalum** [comment]
Very likely to be a duplicate #21537 then? As discussed over there apparently this is also possible to repro with MS Basic, it's just a lot harder.
