### ISSUE TITLE
Lyrics not working in VOXOS Epic Choir 

### ISSUE THREAD

**Issue by TimBomBom** [musescore/MuseScore#23973]
### Issue type

VST bug

### Description with steps to reproduce

I recently purchased VOXOS Epic Choir from musehub, but the lyrics are totally broken. I am stuck with the default Ahh sound on pretty much all voices. 
Expected behaviour: Lyrics change the syllable being sung (i.e. ahh --> ooh). 
Observed: Lyrics have no effect on the syllable

I filed a bug report through musehub but it has been radio silence for days. Not even a confirmation email. Writing here to see if anybody else has this issue or knows a fix.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/b6a89a72-67dd-45ed-ab2c-5a23ab474c9d

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I was unable to check

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
Thanks for reporting this @TimBomBom, and sorry that this particular feature in the library isn't yet working as expected.

In good news, the support on the MuseScore Studio side for this specific feature has actually been developed, and is about to be released in the next update to MuseScore Studio. We anticipate a beta any day now, so the full public release shouldn't be more than a week or so away. 

Thanks for your patience with this, and I hope you enjoy using the lyrics feature when 4.4 comes out very soon.
