### ISSUE TITLE
Tuplet numbers not recognizing change of colour

### ISSUE THREAD

**Issue by mccoydtromb** [musescore/MuseScore#23985]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Select one or multiple tuplet numbers (I have tested with triplets)
2. In the Properties panel, click the Appearance button, then the colour picker.
3. Choose any colour other than black.
4. Tuplet number remains black.

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/0f101104-9118-45ef-8c65-04a501737e3d)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I was unable to check

### Operating system

Windows 10

### Additional context

I actually wanted to make these invisible without altering the layout, so if you can do that instead, win!

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
Fix in current master, so will be in 4.4

**Comment by mccoydtromb** [comment]
Thanks. Should have done my research better!
