### ISSUE TITLE
Sound is choppy during Note Input after switching to 2048/4096 buffer size (MuseSounds only)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#24018]
### Issue type

General playback bug

### Description with steps to reproduce

1. Open score
2. Switch from 256-1024 to **2048** or **4096**
3. Input some notes

Doesn't occur if to reopen score
Doesn't occur with **MS Basic**

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/01cb16af-2fa0-4c8b-b4c6-7801e8f514d1

### What is the latest version of MuseScore Studio where this issue is present?

4.4 master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Win/Mac

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
I've been advised that this problem is no longer reproducible after closing and reopening the score.
This warrants lowering its priority.

**Comment by DmitryArefiev** [comment]
Fixed in #24122

**Comment by DmitryArefiev** [comment]
There is still a minor issue: some delay with proper switching to new buffer size after clicking OK in Preferences.
On **Win**, you hear the first note is choppy. On **Mac**, just a silence (during note input) first second.
**Win**

https://github.com/user-attachments/assets/170931ad-e058-4e06-bac3-007fe6b22684

Since it's hard to fix, let's see if users complain about that
