### ISSUE TITLE
Tremolo Bar is almost invisible

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#24019]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. In master / 4.4 RC, look at the Tremolo Bar element in the Guitar Palette

### Supporting files, videos and screenshots

<img width="308" alt="Screenshot 2024-08-13 at 11 47 33 AM" src="https://github.com/user-attachments/assets/860948af-0f84-45cb-905b-deb0edeadb1e">

https://github.com/user-attachments/assets/35b9dc92-a975-4cb5-9325-66dd2fb1b181

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.4, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.0-242261026, revision: github-musescore-musescore-f032f62

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

All

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by miiizen** [comment]
The line width property has changed from `Millimetre` to `Spatium` (https://github.com/musescore/MuseScore/pull/23875).  This issue will probably be caused when setting the line width in `TremoloBar::setProperty`.
