### ISSUE TITLE
Crash when holding Ctrl / Cmd on a selected dynamic

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#24022]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Add a dynamic to the score
2. With the dynamic selected, hold <kbd>Ctrl</kbd> / <kbd>Cmd</kbd>, then click and drag the dynamic
3. Crash

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/7d58b09b-7996-4403-90eb-73ad6f5af052

### What is the latest version of MuseScore Studio where this issue is present?

Nightly Aug 13; 4.4 Beta

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

macOS 14.5

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
Diagnostic files:

[dynam_cmd_drag_crash.zip](https://github.com/user-attachments/files/16616905/dynam_cmd_drag_crash.zip)

**Comment by DmitryArefiev** [comment]
Fixed in #24112
