### ISSUE TITLE
Changing the clef does not affect the order of the key signature accidentals

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#24026]
## Issue type

UX/Interaction bug (incorrect behaviour)

## Description with steps to reproduce

If you insert a different clef in the middle of the system and then (in the same system) change the key signature, the order of accidentals of the key signature will remain the same as before the clef change.

1. In the middle of the system, change the clef
2. After (in the same system) change the key signature (for example, to G major / E minor)

### Expected behaviour

It was expected that when changing the key signature, the accidental (♯) would be located on the 2nd line of the stave, as it should be with the bass clef, but instead the accidental was located on the first line of the stave (as with the treble clef), despite the fact that before there was a clef change (from treble to bass).

## Supporting files, videos and screenshots

https://github.com/user-attachments/assets/0cb38929-4d49-43ec-9649-dc8a6056cc60

## What is the latest version of MuseScore Studio where this issue is present?

4.4.0-242260502, revision: github-musescore-musescore-75dc214

## Regression

Same in all 4.x, works in 3.6

## Operating system

Windows 11

## Checklist

- ✅ This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- ✅ I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- ✅ I have attached all requested files and information to this report
- ✅ I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by evertvanaart** [comment]
I was able to reproduce and fix this, see PR for details:
https://github.com/musescore/MuseScore/pull/24522
