### ISSUE TITLE
Pedal marking becomes larger

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#24027]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Create a score in 4.3.2 and add a pedal line.
2. Save the score.
3. Open the score in 4.4.0.
Expected Result: The size of the pedal marking is the same as in version 4.3.2.
Actual Result: The size of the pedal marking becomes larger than in version 4.3.2.

### Supporting files, videos and screenshots

4.3.2 Screenshot
![image](https://github.com/user-attachments/assets/b502060d-a6e0-4846-9445-317adca456ab)

4.4.0 Screenshot
![image](https://github.com/user-attachments/assets/7f9671d3-c61e-4508-85ee-7d4929a1e5ec)

Sample score
[Pedal test.zip](https://github.com/user-attachments/files/16606546/Pedal.test.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242260502, revision: github-musescore-musescore-75dc214

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 11 23H2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
This is by design. Pedal markings were previously using the Musical Text font (erroneously) and now use the Musical Symbols font, where they now appear at the correct size relative to music notation as intended by the font designer(s). See https://github.com/musescore/MuseScore/issues/17885. Same goes for segno symbols, ottavas, etc, in 4.4.

If you wish to change the size you still can (Style > Text styles > Pedal > Musical symbols scale).
