### ISSUE TITLE
Tempo marking on new score always playing as if it were for quarter note

### ISSUE THREAD

**Issue by josiasmat** [musescore/MuseScore#24042]
### Issue type

General playback bug

### Description with steps to reproduce

Steps to reproduce:
1. Create a new score, put any instrument, click Next.
2. On step 2 (additional score information), check "Show tempo marking on my score" and select any note duration other than a quarter note. Click Done.
3. Enable metronome and play.

Expected behaviour: tempo should follow the selected note duration.
Current behaviour: tempo is set for the quarter note.

Current workaround:
1. On the score, select the tempo marking.
2. In the properties panel, uncheck and check "Follow write tempo".

Tested with MuseScore 4.3.2 and 4.4.0-beta.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/69437e46-e648-4761-a5fb-61242017aa03

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0-beta

### Regression

I was unable to check

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
This strongly reminds me of https://github.com/musescore/MuseScore/issues/14678, are we sure it's a regression and not a duplicate?

**Comment by josiasmat** [comment]
> This strongly reminds me of #14678, are we sure it's a regression and not a duplicate?

Yes, you're right. It's a duplicate of #14678. Sorry for not catching that.

**Comment by zacjansheski** [comment]
Closing per comments above
