### ISSUE TITLE
Property popups protrude from the screen

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#24076]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. Open the Properties panel
2. Select multiple types of elements
3. Click on the element type button
Expected: Popups open in a position where they do not extend to the left or top of the screen
Actual: Popups extend to the left and sometimes to the top of the screen.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/aa57c969-0f77-4d5c-9b3d-1c7b8c965c17

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242290502, revision: github-musescore-musescore-d7e0049

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 11 23H2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
Fixed in #24102

@nmu-nyasan **Popups extend to the left** - this is fixed . But I see some differences with 4.3.2 (Popups extend to the top sometimes to the top of the screen.). Can you recheck it on your side and log it separately please?

**Comment by nmu-nyasan** [comment]
Logged under #24136

**Comment by DmitryArefiev** [comment]
Thanks!
