### ISSUE TITLE
Changing rhythm under slur may destroy slur

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#24081]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. write two (or more) slured quarter notes
2. change penultimates note duration to dotted quartet
3. see - slur is broken
4. save and open - see, slur disapeared

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/5f04fbea-a908-4ac3-9228-29249e154f8a

### What is the latest version of MuseScore Studio where this issue is present?

master

### Regression

Yes

### Operating system

Ubuntu 22.04

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
There is a regression, in the sense that the "false" slur is there in master, not in 4.3.2


https://github.com/user-attachments/assets/1b775c6a-870c-469f-9ce2-4ac8af21e60c

**Comment by sammik** [comment]
> There is a regression, in the sense that the "false" slur is there in master, not in 4.3.2
> 
I was notsure, if it is regression, or progression.

**Comment by mathesoncalum** [comment]
Caused by the deletion of [this line](https://github.com/musescore/MuseScore/pull/23174/files#diff-b3cccd1453066451c7ec79b920fd5743be3e0a8ed027955435e2dda2bcdaa5a9L1476) (FYI @miiizen @mike-spa)
