### ISSUE TITLE
"cresc./dim." leading to an invisible dynamic don't do anything

### ISSUE THREAD

**Issue by Fristover** [musescore/MuseScore#24093]
### Issue type

General playback bug

### Description with steps to reproduce

Dynamic changes don't work if the dynamic after them is set to invisible

To reproduce:
- Add a note (easier to test with a long one)
- Add a dynamic change (line, hairpin, whatever)
- Add a dynamic after the change
- Play and notice it works
- Make the dynamic invisible
- Play and notice it doesn't do anything

### Supporting files, videos and screenshots

Video here:

https://github.com/user-attachments/assets/b5bca44b-0318-4702-a5f2-22b71360508e

### What is the latest version of MuseScore Studio where this issue is present?

4.4 beta

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

Happens with Muse Sounds and MS Basic.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
Fixed in #24096
