### ISSUE TITLE
List Selection of Hairpins, only one hairpin moves at a time

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#24104]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. List select multiple hairpins
2. Click and drag.  In 4.3.2, all selected hairpins move, in master, only the one clicked moves.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/a8baf9cf-7e5b-43e4-8a2f-15d231f8f8d5

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.4, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.0-242320503, revision: github-musescore-musescore-bf7a77e

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 14

### Additional context

I recognize the behavior of anchors makes this a different beast.

I also think it would be best if list-selected hairpins can be extended/shortened together.  By click dragging or shift+arrows.  (logged as feature request https://github.com/musescore/MuseScore/issues/24119 )

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by avvvvve** [comment]
Adding that you can also only move one dynamic at a time in a list selection (though pre-4.4, neither dynamic would move if you used arrow keys on the list selection, it would just select the next element).

https://github.com/user-attachments/assets/f923c719-7aae-4111-b04f-abb387568c28
