### ISSUE TITLE
Unable to select Musical text font independently from Musical symbol font in Format > Style settings (Empty dropdown occurs)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#24132]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Go to Format > Style > Score
2. Select MuseJazz in Musical symbol font popup (notice that )
3. Notice that Musical text font is empty (but it successfully changed in the score)
4. Now try to change  Musical text font other than MuseJazz Text - **no changes in the score**

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/29c47887-1502-48de-80b4-2196420cc929

### What is the latest version of MuseScore Studio where this issue is present?

4.4 master

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
The UI glitch (empty dropdown) aside, I don't think there's a bug here, because the musical text font is - correctly - not used for anything in the score any more. There may be some small exceptions. Segnos, dynamics, etc, all come from the musical symbols font. Therefore, I wouldn't expect to see any changes in the score if it is changed.

**Comment by XiaoMigros** [comment]
Using musical symbols within an actual text element _should_ still use the musical text font

**Comment by DmitryArefiev** [comment]
Tested in **4.4 release build** on Win10, Mac13.6, LinuxUbuntu22.04. The **empty dropdown no longer occurs**. 

Other things with Musical text font is a separate discussion.

Closing
