### ISSUE TITLE
MuseSounds Accent Interpretation 

### ISSUE THREAD

**Issue by Zagubionna** [musescore/MuseScore#24135]
### Your idea

MuseSounds should change how it interprets the volume levels of accents on certain instruments. I think ideally, an accent should start louder (probably around one dynamic level above the current specified dynamic), and then pretty quickly go back down to the **original dynamic level.**

### Problem to be solved

On a few instruments, a good example for recreation being the Alto Saxophone, the accented note does start louder than other notes, but after that it acts almost like a fortepiano, going down many dynamic levels below the specified dynamic. The accent is being over-dramatically interpreted and doing more than it needs to, and the sudden quietness almost sounds like the player is restraining themselves. It takes away a lot of power from held notes during playback, and it does not flow well with any regular notes that come after. I am not saying this is an "incorrect" interpretation of the articulation, but I think on software like this it would be best for interpretations to be simpler and more consistent so that they are less likely to not work in certain situations. I've included an image and video of the context I am writing this from where the accents' lack of sustained volume is particularly problematic with what I am trying to write.

![Saxccents](https://github.com/user-attachments/assets/7a632a7c-589d-4436-822b-d712f8113f41)

https://github.com/user-attachments/assets/baa8ca5d-b4bc-4bab-b389-81addbb3baf3

https://github.com/user-attachments/assets/9538c30d-e265-4c20-a0c6-f54d311dedbb

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
Since this is a Muse Sounds specific issue, can you please raise it by contacting customer support via the new Muse Hub? 

(If you aren't yet on Hub v.2, you can use [this link](https://support.musehub.com/hc/en-gb/requests/new)

Thank you!
