### ISSUE TITLE
Dynamics added to v2 notes do not extract into parts correctly

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#24150]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. Create a new score using, say, the Classical Orchestra template
2. In the flute line add some v1 notes in a few places, and attach at least one dynamic. Add some v2 notes in a few places, and attach at least one dynamic to any of the v2 notes added.
3. Open the "Parts" dialog and create a new part (call it "Flute 2")
4. In the instruments panel, click show on "Flutes"
5. Expand to show the "Treble clef" staff, click on the setting icon
6. Uncheck all but voice 2
7. Note that any dynamics added to the Flute 2 line in step 2 are missing.

### Supporting files, videos and screenshots

https://musescore.com/user/7209246/scores/20259424/s/mFFELE

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

I understand changes were made in 4.4 to support dynamics affecting playback for different voices (which is great), but I don't quite understand why if I've selected a v2 note and added a dynamic that that dynamic appears not to belong to the same voice as the note (which is how 4.3 and earlier versions behave).

Slightly related, but not a regression (it's the same in 4.3): I also notice if I add a dynamic to the Flute 2 part, it automatically gets added to Flute 1 too. And yet the same is not true for notes!

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
In your example, the 'Voice 2' dynamic is assigned to 'All voices'. If following the steps you describe, a 'Voice 2' dynamic would appear in the part, following the steps you describe. But 'All voices' dynamics appear to only appear in the part if voice 1 is shown.

**Comment by wizofaus** [comment]
I just added the dynamic to a note in v2, the way it works in 4.3. There wasn't even a note in the same place in v1 that it would make sense to attach it to.

**Comment by wizofaus** [comment]
I don't think any "fix" is needed here, just a way to make users aware of the option in Preferences to switch back to the 4.3 behaviour:

![image](https://github.com/user-attachments/assets/0ee8b4ac-8f8a-4776-bd17-4ad6ad252698)
