### ISSUE TITLE
Midi Lyric export (4.4.0 preview) does not take repeats into account resulting in missing lyric text

### ISSUE THREAD

**Issue by japj** [musescore/MuseScore#24168]
### Issue type

Import/export issue

### Description with steps to reproduce

1. install a 4.4.0 preview that includes the Midi Lyric export feature (after August 14th 2024)
2. make a score containing notes with lyrics and a simple repeat, including notes and text after the repeat
3. export as midi
4. import this midi again

Results: where repeated text would be, the text from after the repeat is shown, the last notes do not have any text at all

Expected: repeated text to be correct in midi export

### Supporting files, videos and screenshots

Initial score, to be exported as midi
![Repeat with lyrics](https://github.com/user-attachments/assets/c8cb424e-a888-4815-a55b-66f51fc609ae)

Result score, imported from midi
![Repeat with lyrics-1](https://github.com/user-attachments/assets/e704dc06-ac7a-492c-a3d1-54967d9d29bc)

[Repeat with lyrics.mscz.zip](https://github.com/user-attachments/files/16725072/Repeat.with.lyrics.mscz.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.6, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.0-242271422, revision: github-musescore-musescore-a4ac62c

### Regression

I was unable to check

### Operating system

macOS 14.6

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
@bakajikara Would you have a chance to look into this? Otherwise no worries, then someone else can do it :)
