### ISSUE TITLE
Crash when open Properties > Select Color window on Linux

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#24173]
### Issue type

Crash or freeze

### Description with steps to reproduce

![Screenshot from 2024-08-23 18-16-06](https://github.com/user-attachments/assets/4b53c953-e864-4ad8-9ff1-400eeea6cf05)

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

LinuxUbuntu 22.04

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
Could be related to #24121 changes

**Comment by igorkorsukov** [comment]
I also did a little research yesterday, according to my results, the problem occurs because of this change https://github.com/musescore/MuseScore/commit/6492fbe9144e2d8078a6dfd1b498e9573e6e3658

**Comment by DmitryArefiev** [comment]
Fixed in #24223
