### ISSUE TITLE
Joining scores (Compilation de partitions ou Création d'une messe)

### ISSUE THREAD

**Issue by Cyrille2ack** [musescore/MuseScore#24183]
Existe-t-il une possibilité de joindre plusieurs partitions dans un seul fichier avec leurs différents titres et formats ? 
Si oui, veuillez me le montrer.
Merci.

Is there a possibility to join multiple scores in one file with their different titles and formats? 
If yes, please show me.
Thank you.

**Comment by shoogle** [comment]
Questions like this belong on the forums. We have a French forum at https://musescore.org/fr/forum

That being said, the easiest way to join scores is to export (File menu > Export) each score as a separate PDF file, then join the PDFs together using a web-based tool. Search online for "merge pdfs"  and you'll find lots of options. You upload the separate PDFs to one of these sites and then download the resulting, merged document.

If you need multiple scores *within* MuseScore (i.e. not as PDFs), currently the only way it to copy and paste notes between the scores. You'll probably have to recreate the text frames manually at the start of each section.
