### ISSUE TITLE
Voltas should not be applied to beats

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#24189]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Select note or rest
2. Click on volta on the palette
Expected: Volta is applied to the measure that contains the selected note / rest
Actual: Volta is applied to the beat of the selected note / rest

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/1ec71afa-6143-4b17-89ee-d24bf5eb3237

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242370503, revision: github-musescore-musescore-ceea06a

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 11 23H2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by VighneshJadha** [comment]
You can see one such case in Kiss the Rain by Yiruma.

**Comment by XiaoMigros** [comment]
Similar problem when inserting beats at the start of a measure with a volta:
![image](https://github.com/user-attachments/assets/4d19e255-cd05-4e4a-abcd-4ec8337f8bb3)
