### ISSUE TITLE
Ghost Hit on Muse Sounds Drum Kit can be a bit louder to hear in ensembles

### ISSUE THREAD

**Issue by AuraDJ** [musescore/MuseScore#24226]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

1. Add Round Brackets to Snare Drum (or any other Drum that can be affected by Brackets)
2. Start Playback

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/73e53054-de43-47af-a792-d352d98b7b6b

Muse Sounds Drumkit vs Touhou Soundfont (Ghost hit mapped to 105)
(Score can be downloaded on musescore.com)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0-242390800

### Regression

No.

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
The ghost notes in the MuseSounds drum kit stave mapped to a different pitch?  They will not play if that is the case.  Needs to be 38 with a parenthesis.

**Comment by zacjansheski** [comment]
https://github.com/user-attachments/assets/7bcf26ef-25ac-4722-aef6-8ef7947b8996

**Comment by bkunda** [comment]
This issue appears to be specific to the Touhou Soundfont.
Unfortunately, we don't currently plan to address it.

**Comment by AuraDJ** [comment]
The issue is, that the ghost notes from Muse Sounds are barely hearable. The Touhou font is only here for a comparison.

**Comment by zacjansheski** [comment]
Can you provide the score?  In the video I shared, I think the ghost notes are appropriately audible

**Comment by AuraDJ** [comment]
The problem is, that while it is barely audible, when you hear to the drum kit in isolation, it becomes completely inaudible, once you mix in other instruments. When it should be barely audible, when other instruments are mixed in.
In other words: while the current loudness is more realistic (for the quietest possible played ghost notes). It becomes too quiet for a full band mix. It even gets nearly lost in a full drum mix.
