### ISSUE TITLE
Continually Repeating Note Entry In MuseScore 4.4

### ISSUE THREAD

**Issue by mrmayfield** [musescore/MuseScore#24264]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Open MuseScore 4.4 and start a new score.
2. Select any instrument and click Done.
3. Enter any note using the keyboard.

Expected Behavior: note will appear on staff

Actual Behavior:  the note will repeat until the entire score has been filled.

Alternatively, if you enter a not using the mouse the note will appear correctly and then appear multiple times following the initial entry and then MuseScore will crash.

Also:

1. Open MuseScore 4.4 and select and existing score.
2. Add a new note to the score using keyboard entry.

Expected Behavior: note will appear in the selected location

Actual Behavior: note appears in the selected location and repeats overwriting all existing notes until the end of the score.

### Supporting files, videos and screenshots

No applicable video available.

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux (Fedora 40)

### Additional context

I am running MuseScore Fedora on a Thinkpad. I am using the official Appimage - MuseScore-Studio-4.4.0.242390800-x86_64

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
Sounds like you have a MIDI loop on your system.  If you have trouble finding out where that is happening in your system configuration, please ask for help on the official Support forum.

**Comment by mrmayfield** [comment]
> Sounds like you have a MIDI loop on your system. If you have trouble finding out where that is happening in your system configuration, please ask for help on the official Support forum.

Thanks for the feedback. I will check out that possibility and report back if I find out anything useful. I would still like to keep this issue open since the problem does not occur with the same system/setup when I use 4.3. It seems like something the developers would like to investigate since I doubt I will be the only person with the problem.

**Comment by mrmayfield** [comment]
> Sounds like you have a MIDI loop on your system. If you have trouble finding out where that is happening in your system configuration, please ask for help on the official Support forum.

Thanks again for the help. I just checked my configuration files (asound.conf and .asoundrc) and both were empty. In addition, I checked sound/midi connections that were in existence using Qjackctl. No loop backs showed up. However, when I disconnected MuseScore 4.4 from my output (using Qjackctl), the repeating notes stopped, and then started again when I reconnected the link.

So, it does look like there is some kind of loop back, but it does not appear to come from my system set-up or at least not anything that is obvious.

**Comment by MarcSabatella** [comment]
Why are you using Qjackctl with MuseScore in the first place?  If you're not using MIDI input or output, you shouldn't have that connected.  But if you *are* using MIDI input and/or output, you definitely need to configure your system in such a way you don't get MuseScore's MIDI output being routed back to its input.

**Comment by mrmayfield** [comment]
I am not using MIDI input/output. I just Qjackctl to check connections. I don't normally have it running and did not have it running when I first discovered the issue.

**Comment by mrmayfield** [comment]
The latest nightly master (29 Aug. 2024) seems to have fixed the issue. As such, I will close this issue. Thanks to Marc for responding with suggestions.

**Comment by cbjeukendrup** [comment]
Just in case: the fact that it's fixed in the nightly build may also mean that it's a MuseScore settings issue. Nightly builds namely don't read/write configuration from/to the same folder as release builds, so that they can be used independently. 
If the issue indeed comes back in the next release, you can fix it by resetting to factory settings (Reset preferences, in the Preferences dialog), or taking a look at Preferences > Audio/MIDI.
