### ISSUE TITLE
White Screen after update 

### ISSUE THREAD

**Issue by T92G** [musescore/MuseScore#24269]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Download Musescore 4.4 (.msi installer, MuseHub, Nightly builds).
2. Launch the .exe file.
3. It will show a blank screen.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/542c22d2-b28b-42b3-ba2b-333db765e173

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by fancellu** [comment]
Ditto. Used to work fine. First it refused to come up, at all, then it came up with the big white window. 

However if I minimize them maximize the window, then it renders properly

**Comment by ImposibleALX** [comment]
I have that problem too

**Comment by DominicMaas** [comment]
We've received a few of these through the Muse Hub support channels as well (no crash logs, just generic reports)

**Comment by alex-rivera-pm** [comment]
I have the same issue. 4.3.2 was working fine.

**Comment by Jojo-Schmitz** [comment]
There seems to be a workaround (https://musescore.org/en/comment/1254679#comment-1254679):

1. WIN + R and type cmd, then press ENTER
2. copy/paste:
    set QT_QUICK_BACKEND=software
    then press ENTER
3. copy/paste: "C:\Program Files\MuseScore 4\bin\MuseScore4.exe"
    then press ENTER.

**Comment by Eism** [comment]
Can you test [this build](https://github.com/musescore/MuseScore/actions/runs/10631127275/artifacts/1874226703) from https://github.com/musescore/MuseScore/pull/24313?
It would also be very helpful if you could let us know what video card you have in your machine?

**Comment by T92G** [comment]
> Can you test [this build](https://github.com/musescore/MuseScore/actions/runs/10631127275/artifacts/1874226703) from #24313? It would also be very helpful if you could let us know what video card you have in your machine?

It also gave me a blank screen (I don't know if my antivirus played a role).

![imagen](https://github.com/user-attachments/assets/bd7ae0ee-51bb-43ec-8994-40c40a407924)

**Comment by DmitryArefiev** [comment]
@T92G Hi! Can you provide some details please?

1. What is your environment? (laptop/workstation, display resolution, dpi scaling in Windows (100,150% etc.))
2. Are you updated from 4.3.2?
3. Are you using default location (Program Files\) ?
4. Does your user name in Windows contain some specific symbols (specific to Spanish) or space?

**Comment by DmitryArefiev** [comment]
@T92G Can you try this build on your side? https://github.com/musescore/MuseScore/actions/runs/10634681512

**Comment by moving-bits** [comment]
I've tried the linked build (https://github.com/musescore/MuseScore/issues/24269#issuecomment-2321644856), but still get a blank screen.

Anything specific you need for debugging?

**Comment by cbjeukendrup** [comment]
That's sad news. What you could do is:
1. In Windows Explorer, enter `%LOCALAPPDATA%\MuseScore` in the address bar
2. Create a ZIP archive of the `MuseScore4` subfolder that you see there
3. Upload it here

Hopefully that gives us another clue. Thanks in advance!

**Comment by moving-bits** [comment]
Here are the files for release version 4.4.0 [ms4.zip](https://github.com/user-attachments/files/16822353/ms4.zip) as well as for 4.4.1 development version [ms4development.zip](https://github.com/user-attachments/files/16822355/ms4development.zip)

**Comment by mercuree** [comment]
I think developers need to know which backend was used. Can you attach zip once again?
1. Go to development build (bin folder with MuseScore4.exe)
2. CTRL+L (cursor will focus in address bar), then type cmd and press ENTER
2. Copy/paste this string to opened terminal window and press ENTER:
```
set QSG_INFO=1&& "MuseScore4.exe" --debug
```
3. Close Musescore and create zip archive as you did before and attach it here on github.
There should be string like `DEBUG | main_thread     | Qt| Using QRhi with backend D3D11` in log file.

Also you can try setting opengl backend and check if it works for you:
1. copy/paste this string and press ENTER
```
set QSG_RHI_BACKEND=opengl&& "MuseScore4.exe" --debug
```

**Comment by DmitryArefiev** [comment]
@T92G Can you also provide some details please?

1. What is your environment? (connected monitor or internal display, display resolution, dpi scaling in Windows (100, 125,150..%))
2. Are you using default location for 4.4 installation (Program Files\) ?
3. Does your user name in Windows contain some specific symbols (specific to Spanish) or space (you can find it here C:\Users\**_your user name_**)?

**Comment by moving-bits** [comment]
> I think developers need to know which backend was used. Can you attach zip once again?
> set QSG_INFO=1&& "MuseScore4.exe" --debug

Here's a new zip after a run with `--debug` parameter. Quite a few error messages are included now:
[ms4development2.zip](https://github.com/user-attachments/files/16824201/ms4development2.zip)

> Also you can try setting opengl backend and check if it works for you:
> set QSG_RHI_BACKEND=opengl&& "MuseScore4.exe" --debug

This DOES work for me :-)

(BTW: Thanks for the detailed descriptions on how to run MuseScore with different parameters.)

**Comment by mercuree** [comment]
Thank you! Based on provided logs I can assume that in your case backend D3D11 is used (this is [default](https://doc.qt.io/qt-6/qtdatavisualization-known-issues.html) backend for qt6):
```
2024-08-31T11:59:37.150 | DEBUG | main_thread     | Qt              | Using QRhi with backend D3D11
  Graphics API debug/validation layers: 0
  QRhi profiling and debug markers: 0
  Shader/pipeline cache collection: 0
2024-08-31T11:59:37.150 | DEBUG | main_thread     | Qt              | threaded render loop
2024-08-31T11:59:37.151 | DEBUG | main_thread     | Qt              | Using sg animation driver
2024-08-31T11:59:37.151 | DEBUG | main_thread     | Qt              | Animation Driver: using vsync: 16.68 ms
```
and this backend failed with ATI Radeon HD 4600 Series:
```
2024-08-31T11:59:37.415 | DEBUG | 3244            | Qt              | Using sg animation driver
2024-08-31T11:59:37.415 | DEBUG | 3244            | Qt              | Animation Driver: using vsync: 16.68 ms
2024-08-31T11:59:37.416 | DEBUG | 3244            | Qt              | DXGI 1.2 = true, FLIP_DISCARD swapchain supported = true
2024-08-31T11:59:37.416 | DEBUG | 3244            | Qt              | Adapter 0: 'ATI Radeon HD 4600 Series' (vendor 0x1002 device 0x9490 flags 0x0)
2024-08-31T11:59:37.416 | DEBUG | 3244            | Qt              |   using this adapter
2024-08-31T11:59:37.416 | DEBUG | 3244            | Qt              | Adapter 1: 'Microsoft Basic Render Driver' (vendor 0x1414 device 0x8C flags 0x2)
2024-08-31T11:59:37.443 | DEBUG | 3244            | Qt              | MSAA sample count for the swapchain is 1. Alpha channel requested = yes.
2024-08-31T11:59:37.443 | DEBUG | 3244            | Qt              | rhi texture atlas dimensions: 2048x2048
2024-08-31T11:59:37.454 | WARN  | 3244            | Qt              | Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
2024-08-31T11:59:37.454 | WARN  | 3244            | Qt              | Failed to build graphics pipeline state
2024-08-31T11:59:37.455 | WARN  | 3244            | Qt              | Failed to create vertex shader: Error 0x80070057: Falscher Parameter.
2024-08-31T11:59:37.455 | WARN  | 3244            | Qt              | Failed to build graphics pipeline state
...
```
I hope this information is useful for developers.
Also I wonder if there is any difference in using `software` backend or `opengl`.

**Comment by igorkorsukov** [comment]
Thank you very much for the information, it will help a lot!
We have already added a detective error with graphics and automatic switching on the software.
But it seems that it does not work as expected, it does not reproduce for us, so we cannot debug this solution ourselves. Your logs provide information on what the problem might be, on Monday we will continue to solve this problem.

**Comment by moving-bits** [comment]
Thanks for your dedicated work on it! Let me know when I shall test with a new build or when I can provide you further insights for analysis.

**Comment by igorkorsukov** [comment]
This build fixes the display of some elements (for example, plugins, avatar) in software mode.
(except for floating panels)
https://github.com/musescore/MuseScore/actions/runs/10669249340

**Comment by moving-bits** [comment]
> @moving-bits please try this build [musescore/MuseScore/actions/runs/10669249340?pr=24377](https://github.com/musescore/MuseScore/actions/runs/10669249340?pr=24377)

Good news: This build does start on my machine. From the logfile I guess it reverts to "software" backend after having detected some GS errors. Logfiles are here: [ms4development.zip](https://github.com/user-attachments/files/16840305/ms4development.zip)

**Comment by igorkorsukov** [comment]
We found that the software backend does not work perfectly, there is a issuess... so our research is not finished yet

**Comment by igorkorsukov** [comment]
@moving-bits please check this build https://github.com/musescore/MuseScore/actions/runs/10685193103?pr=24407  

In the previous solution, we immediately switched in the software.
In the new solution, we go through the graphic APIs one by one

For Windows, the typical situation is as follows: 
* Direct3D11 - default Api (there are problems)
* OpenGL - we are doing a check, maybe it will work for you.. 
* Software - used if others do not work

**Comment by moving-bits** [comment]
Thanks for the update. The build does work for me, it uses "OpenGL" on my system.

First program start takes "quite some time" (> 10s?), subsequent starts are significantly faster (more like 3-4s), both with `--debug` parameter applied.

**Comment by RomanPudashkin** [comment]
Confirmed as fixed (here and on the [forum](https://musescore.org/en/node/367548#comment-1256281))
