### ISSUE TITLE
[MS 4.4] MuseScore 4.4 no longer plays "Piano Sustain Pedal" properly on VSTs

### ISSUE THREAD

**Issue by Ysabelle12** [musescore/MuseScore#24273]
### Issue type

VST bug

### Description with steps to reproduce

Sustain pedal no longer works properly on 4.4 when it was working properly on ANY older version such as 4.3.2 and older.

See video below
[![YouTube](http://i.ytimg.com/vi/u8H7g078BTA/hqdefault.jpg)](https://www.youtube.com/watch?v=u8H7g078BTA)

As you can see in the video, the sustain pedal AFTER Measure 3 just HOLDS down and no longer repedals every bar. For some WEIRD reason it starts repedalling at Measure 71 for a brief moment and stops again at Measure 74.

I've also tested this in nightly and it doesn't fix the issue. This also affects Mac as I've tested it on them as well.

I've tested this on 
Kontakt 7.10.6
Kontakt 6.8.0
They all happen in this and not just that instrument, it also affects the other sample so it's recreatable issue.

Sheet Music used can be found here.

[https://musescore.com/user/69102031/scores/14016613](url)

Repedalling works properly on the sheet music above, it was uploaded with MuseScore 4.3.2

### Supporting files, videos and screenshots

[![YouTube](http://i.ytimg.com/vi/u8H7g078BTA/hqdefault.jpg)](https://www.youtube.com/watch?v=u8H7g078BTA)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore 4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11, MacOS Sonoma

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Ysabelle12** [comment]
VST is part of my essential workload for professional use as it gives me more control on Piano sounds.

**Comment by MqcCheeze** [comment]
@Ysabelle12 yes this very much affects MIDI exports, I've got some projects upwards of 30/40 minutes long and I am not going to re-enter every single pedal event again. I hope it gets fixed quick

Here's the issue with it

https://github.com/musescore/MuseScore/issues/24318

**Comment by Ysabelle12** [comment]
@MqcCheeze Hopefully this gets fixed soon

**Comment by DmitryArefiev** [comment]
Fixed in #24507
