### ISSUE TITLE
Unable to insert new key signature on first instrument via drag-and-drop

### ISSUE THREAD

**Issue by cgpqci** [musescore/MuseScore#24276]
### Issue type

Interaction/UX

### Description with steps to reproduce

1. Create a score via "Choose from template."
2. Choose category "Orchestral" and template "Symphony Orchestra."
3. Add key signature in "Additional score information" (_Optional_), then click "Done."
4. Click and drag a key signature from the palette to the first measure of the score.
5. Drop key signature on the first measure of the score (See error) OR Hold <kbd>Ctrl</kbd> and drop key signature on the first measure of the score (See error)

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/59c844a0-48ca-48a9-b104-b07c36996ed1

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

- The click-only method works otherwise, so this is my workaround with this issue.
- This also doesn't happen with the measures past the first.
- I also noticed the wanky behavior of the key signatures in the click-only method; might be worth looking out on.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
(This is an interaction bug, not engraving.)
I can't reproduce this myself, and in any case just did exactly this in a new score in 4.4. Perhaps you might attach a score in which you encounter this problem, just in case there's anything special about it.

**Comment by mathesoncalum** [comment]
This has something to do with transposed instruments - they're not playing nice with the new click and drag interaction. I'll take a look.

**Comment by cgpqci** [comment]
> I can't reproduce this myself, and in any case just did exactly this in a new score in 4.4. Perhaps you might attach a score in which you encounter this problem, just in case there's anything special about it.

Hope you don't mind that it's already worked on, but here: 
[bortkiewicz_op16_pianoconcerto_1.zip](https://github.com/user-attachments/files/16796928/bortkiewicz_op16_pianoconcerto_1.zip)

> This has something to do with transposed instruments - they're not playing nice with the new click and drag interaction. I'll take a look.

Did another look myself; partly that might be the cause, but I just found out it might also be with the template.

- Tried to reproduce with manually adding the instruments while creating the score (via Choose instruments). It didn't yield the bug at all.
- Tried again by using the Classical Orchestra template in "Create from template." Didn't yield it either.
- Tried now with the Symphony Orchestra template. I was able to reproduce it.

I'll update the details above, but this might also be something worth taking note of.

**Comment by mathesoncalum** [comment]
Okay, I figured it out.

The drop logic basically works by finding the nearest valid measure and dropping to the center of it. The problem is that the time signature can actually end up "covering" the center of the measure if it has been offset far enough (by key signatures, etc), causing the drop to be blocked.

Looking into potential solutions now...
