### ISSUE TITLE
Hangs entering fingering before vertical frame

### ISSUE THREAD

**Issue by rsholmes** [musescore/MuseScore#24295]
### Issue type

Crash or freeze

### Description with steps to reproduce

MuseScore reproducibly hangs, requiring a force quit, when doing the following:

 1. Open attached score
 2. Select the one note
 3. Add->Text->Fingering
 4. Enter a number and a space

This appears to have to do with the presence of a vertical frame immediately after the note to which fingering is being added. Without the frame, or if the note is not the last one before the frame, the hang does not occur.

### Supporting files, videos and screenshots

[Untitled score.mscz.zip](https://github.com/user-attachments/files/16800151/Untitled.score.mscz.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Linux Mint 21.2, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: 0fcd11b

### Regression

I was unable to check

### Operating system

OS: Linux Mint 21.2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
Reproduced, diagnostic files here

[FingeringFreeze.zip](https://github.com/user-attachments/files/16805526/FingeringFreeze.zip)

**Comment by zacjansheski** [comment]
Does not seem to be a regression, I can reproduce in all versions of MS4

**Comment by zacjansheski** [comment]
Pretty easy to reproduce

1. Append a text frame
2. Write a fingering on the last note in score
3. Press space

Same thing happens with sticking, does not happen with lyrics
