### ISSUE TITLE
Pedal markings sometimes not connecting

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#24290]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

Sometimes adjoining medal markings connect, sometimes they refuse to do so (within the same score).

Not yet sure how to reproduce.

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/0fe97d1b-57bc-45df-b9a9-abd4bab382ea)
![image](https://github.com/user-attachments/assets/b9145f0b-0dfb-404d-8528-fba548a5b42f)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Any

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by plasma4** [comment]
This is also happening to me; glad it's being fixed!
