### ISSUE TITLE
Unable to disconnect dynamic from hairpin (even with auto-place disabled)

### ISSUE THREAD

**Issue by Postoli** [musescore/MuseScore#24291]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Insert hairpin on grand stave (or stave with joined barlines)
2. Insert dynamic in following bar
3. Insert key change on dynamic destination

### Supporting files, videos and screenshots

<img width="827" alt="Dynamics Key Sig" src="https://github.com/user-attachments/assets/b00970d8-a9ee-47d5-9f4a-ee39eaac1acc">
<img width="818" alt="Dynamics No Key Sig" src="https://github.com/user-attachments/assets/4e55e19d-a83d-4fb9-ab77-5a6225dc3f36">

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0-242390800

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Sonoma 14.1

### Additional context

Even when auto-place is disabled for all related items, it is impossible to disconnect the hairpin from the dynamic marking when a key change is involved. Dragging the hairpin brings the dynamic with it regardless.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
How about if you turn 'Snap to next' off for the hairpin?

**Comment by Postoli** [comment]
Works. Thank you!
