### ISSUE TITLE
The new keyboard shortcut for "Toggle multimeasure rests", Ctrl+Shift+M, doesn't work

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#24321]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

Title says it all:
The new keyboard shortcut for "Toggle multimeasure rests", Ctrl+Shift+M, doesn't work

### Supporting files, videos and screenshots

Changing it to the old shortcut, M, makes it work again

### What is the latest version of MuseScore Studio where this issue is present?

4.4/master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

Srems from https://musescore.org/en/node/367656

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
Hmm, doesn't work on my MacOS device

**Comment by Jojo-Schmitz** [comment]
I did reset the shortcuts to their default.
German, QWERTZ keyboard, Wondows 11

**Comment by zacjansheski** [comment]
This is strange.  It works for me after factory reset on Linux and Windows 11 devices
Does not work on my MacOS device
@cbjeukendrup @DmitryArefiev Could use more eyes on this, let me know if you get different results on your devices

**Comment by Jojo-Schmitz** [comment]
Seerms something on my system 'eats' the Ctrl+SHift+M

**Comment by zacjansheski** [comment]
I think our only options here are to either change the shortcut back to M or use something else.

The complaint with "M" was that users triggered by accident frequently

I would suggest  alt+0 / opt+0
0 is already well associated with rests, seems like a reasonable setting

**Comment by Jojo-Schmitz** [comment]
This issue might well be mine and mine only, and as such not really worth any change (except for my personal shortcuts)?

**Comment by Jojo-Schmitz** [comment]
Found it BTW, it is in the AMD Adrenalin software:
![image](https://github.com/user-attachments/assets/2f061e8c-5437-4e4e-8d05-2d841b1fe71e)

**Comment by Jojo-Schmitz** [comment]
I've disabled it there now, don't really need it.
As far as I'm concerned this issue is resolved...

**Comment by cbjeukendrup** [comment]
Let's perhaps wait a little bit to see if anyone else brings up this problem; if that doesn't happen anytime soon, it's maybe indeed okay to leave the new shortcut as it is.

**Comment by Jojo-Schmitz** [comment]
Only @zacjansheski had the issue too on his Mac?

**Comment by zacjansheski** [comment]
I'm curious if other mac users have this
When I use the shortcut the top menu MuseScore Studio flashes

https://github.com/user-attachments/assets/ed722857-6755-4501-833a-8b03059dc322

**Comment by Jojo-Schmitz** [comment]
So another case of a shortcut being grabed before MuseScore sees it?

**Comment by zacjansheski** [comment]
Must be specific to my system, other mac users don't have that problem.  Let's close
