### ISSUE TITLE
Cannot change view

### ISSUE THREAD

**Issue by urbanrieger** [musescore/MuseScore#24324]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. click on the "Change view (Continous / page)" button.
2. nothing happens

https://github.com/user-attachments/assets/2dce8cab-c610-4ad6-bfc9-00b5781c8c3b

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/170be4ab-a5db-44d9-91a6-3043a7a97d17

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
Do you by chance have multiple displays configured?  There is a known issue where certain popups appear on the wrong one - see https://github.com/musescore/MuseScore/issues/24232

Meanwhile, workaround for this specific symptom would be to define keyboard shortcuts for those commands.

**Comment by urbanrieger** [comment]
Perfect answer, thanks.

Marc Sabatella ***@***.***> schrieb am Fr., 30. Aug. 2024,
19:10:

**Comment by iainhallam** [comment]
Mine does this as well, and I have the multi-monitor bug. It's the same behaviour as the missing Playback and Appearance popup panels.

**Comment by oktophonie** [comment]
Closing as covered by #24232
