### ISSUE TITLE
Copying/pasting symbols will cause them to appear off the top of the page

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#24335]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Create any new score with a note
2. Using the master palette, add any Symbol to the note (must be under the "Symbols" category)
3. Click on the symbol just added
4. Copy & paste it
5. Expected: positioned near the symbol that's selected.
6. Actual: It appears off the top of the score

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/d863c853-f79c-4312-bbfd-f9a1ed8e9ddc)

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

No

### Operating system

Windows 11

### Additional context

The fact the symbol is visible even though positioned off the top of the page is something I've already put up a fix for, but in some way  it's good that fix wasn't in, as otherwise I'd have no idea where it had gone, and just assuming copy/paste wasn't meant to work for symbols for some reason.  At any rate, it obviously shouldn't be positioned there by default.
It's fine if you have a note selected when you paste, and for some reason doesn't seem to happen straight after you first add the symbol (i.e. you need to actively select it first).
The symbol is effectively pasted as a child of the initial symbol, so that if you delete that the stray symbol is also deleted.

Doesn't happen with other non-Symbol items added from the Master palette.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by wizofaus** [comment]
Happy to fix this myself, presumably pretty simple

**Comment by zacjansheski** [comment]
@wizofaus all yours!

**Comment by wizofaus** [comment]
Ok, the only question then is what *should* the behaviour be if you copy a symbol with the default 0,0 offset onto itself?
If we don't do some sort of adjustment you won't see anything at all.  I'm thinking just offset it so that it appears to the bottom right of the existing symbol.
I'm not actually sure what the use cases are for pasting one symbol as a child of another (though it seems potentially useful).

**Comment by wizofaus** [comment]
Also as part of this I found another bug, where if you drag a symbol from a palette (either master or custom palette) over another symbol, then drag it away again (without dropping), it still shows as though it's going to drop it as a child of the target symbol, but when you actually drop it either nothing happens or it can get added as a child of another item on the score.  Essentially at the point you drop it tries to find the parent again based on the current mouse position, rather than whatever target it had already found (and shows anchor lines for). Presume it's OK to fix at the same time.

**Comment by wizofaus** [comment]
Keep discovering various issues with dragging items from palettes on to the score - essentially it's almost impossible currently to cause the symbol to sit in the exact place it's dropped.  In particular when dragging from the master palette the mouse cursor is drawn representing the symbol with the bottom-right corner of the bounding box on the mouse pointer, but in fact when you drop the object, you're dropping it such that the *top-left* bounding box corner of the added symbol will be where the mouse pointer, so it appears to jump annoyingly as you release the mouse button.  But at high zoom levels it's quite clear that the mouse cursor is not really showing you a preview of how the symbol will look on the score, it's just a clue as to what sort of symbol you're dragging.  Unfortunately if you change the mouse cursor so that the top-left corner of the symbol sits where the mouse pointer is, it obscures other information the mouse cursor is showing you.
So while I'll be able to put up a PR that does at least improve on the current behaviour, it's by no means "perfect", whatever that might mean.
