### ISSUE TITLE
[MS 4.4 macOS sonoma] Some VSTs crashing on macOS but works on older version of MS

### ISSUE THREAD

**Issue by Ysabelle12** [musescore/MuseScore#24331]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Open MuseScore 4.4
2. Create new score/Open existing one
3. Change instrument into Kontakt 7

This worked on 4.3.2

So far I've only tested
Older Kontakt like Kontakt 6 and it doesnt crash, 
Other vst I have also doesn't crash musescore (Possibly only Kontakt 7 problem? But works on 4.3.2)

Only Kontakt 7 but I'm not completely sure about other VST
Maybe the new QT update related?

See video below, selecting Kontakt 7 instantly crashes it on mac
HOWEVER, If you already have Kontakt 7 on your previous score, it won't crash MuseScore, Only when you try to open Kontakt 7 UI

### Supporting files, videos and screenshots

[

https://github.com/user-attachments/assets/31f8ffb0-1a00-406d-b568-b6ebe5e9afe3

](url)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore 4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Sonoma

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by hank205** [comment]
Same here. Tested a few Native Instruments VSTs, only Kontact 7 and Komplete Kontrol crashes.
Macbook Air M2
macOS Sonoma 14.6.1
MuseScore 4.4.0
Kontact7 7.10.6

**Comment by tenephor** [comment]
Note that Sampleson Metapiano 1.5 freezes as well.

**Comment by DmitryArefiev** [comment]
The fix for **Kontakt 7 crash** you can check here https://github.com/musescore/MuseScore/actions/runs/10665547114 (or any next nightly build)

**Comment by DmitryArefiev** [comment]
> Note that Sampleson Metapiano 1.5 freezes as well.

@tenephor Please check this on https://github.com/musescore/MuseScore/actions/runs/10665547114

If it still crashes, log a new issue please

I don't have a license to check

Thanks!

**Comment by Ysabelle12** [comment]
Confirmed it doesn't crash kontakt 7 anymore on ### MuseScoreNightly-latest-master-x86_64.dmg
