### ISSUE TITLE
Undo/Redo button not visible after newstart in smaler window

### ISSUE THREAD

**Issue by FoxVocal** [musescore/MuseScore#24344]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

If you use a non full sized window then after a newstart Undo/Redo buttons are hidden behind the right margin. Only after changing to full size and back they appear on their right place.

### Supporting files, videos and screenshots

![Undo-Redo](https://github.com/user-attachments/assets/c4239bb4-e4b9-4497-aabf-8a8a50ec108d)

### What is the latest version of MuseScore Studio where this issue is present?

Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

### Regression

 4.3.2 and 4.4.0

### Operating system

OS: Windows 10

### Additional context

https://musescore.org/de/node/367693

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
Why closed? Please reopen.

**Comment by FoxVocal** [comment]
Closing happened by mistake

**Comment by zacjansheski** [comment]
Regression between 4.3.2 and 4.4.0

Note the off-center Parts and Mixer buttons as well

**Comment by Jojo-Schmitz** [comment]
As far as I remember this happened with 4.3.2 too and with all 4.x versions

**Comment by DmitryArefiev** [comment]
Fixed in #25174 (rechecked in 4.5 master on Win10)
