### ISSUE TITLE
Placeholders in fields on the "Additional score information" menu are the wrong color/opacity

### ISSUE THREAD

**Issue by RustyBust** [musescore/MuseScore#24345]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

When creating a score, on the last page of the wizard ("Additional score information"), the placeholders "Untitled score", "Subtitle", and "Composer / arranger" are white like the text, but they used to be grey.

If I remember correctly, the coloring was correct in MS 4.3.

### Supporting files, videos and screenshots

Bug_stable.mov shows the bug occurring on 4.4 dark mode.
Bug_nightly.mov shows the bug occurring on the 4.4.1 nightly, light and dark mode.

https://github.com/user-attachments/assets/40cf9a0f-e76c-46cc-9a7d-d46e92906898

https://github.com/user-attachments/assets/c1fe1085-4580-4c77-b3a8-39a6802998c1

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1-242440503, revision: github-musescore-musescore-7da0e38

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 14.4

### Additional context

OS: macOS 14.4, Arch.: x86_64
Stable: MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b
Nightly: MuseScore Studio version (64-bit): 4.4.1-242440503, revision: github-musescore-musescore-7da0e38

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by avvvvve** [comment]
Indeed this is a regression. @mathesoncalum, could we bring back the transparency on this placeholder text that we had in 4.3 and before?
