### ISSUE TITLE
Cannot drag and move the external graphic on the score 

### ISSUE THREAD

**Issue by BetonBrut69** [musescore/MuseScore#24353]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Drag and drop a graphic(.svg) file on the desired area
2. Click and drag the graphic
Expected: last version moved the position of graphic without changing its size
Actual: size changes with its position not changing

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/2e2fdf20-0423-4dd3-a8e9-74cc4efc401f

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Monterey 12.7.5

### Additional context

This worked fine in a previous version of **MU4.3** and now it's broken.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by CynthiaCat** [comment]
This is also happening for me for *.png, *.bmp and *.jpg files. Errant behavior began after updating to 4.4.0

**Comment by MarcSabatella** [comment]
Just a note: workaround is to use the offset field in the Appearance section of the Properties panel
