### ISSUE TITLE
Muse sounds don't work in 4.4

### ISSUE THREAD

**Issue by Muetzenkrieger** [musescore/MuseScore#24366]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

After installing the 4.4 update for musescore the MuseSounds don't work. They don't show up in the mixer.

### Supporting files, videos and screenshots

I don't know what to submit here because it is just the MS basic playback...

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by shoogle** [comment]
Please install the new version of Muse Hub from https://www.musehub.com/ and use it to update your sounds to the latest available versions, then let us know whether this fixes the problem for you.

**Comment by Muetzenkrieger** [comment]
Ah, the new Muse Hub is a different app. I was confused because I updated the sounds and Musescore via the old Muse Hub.

**Comment by AnnWann** [comment]
I'm facing this very similar issue but I had download the new version of Muse Hub. Everything is similar except I'm on Windows 10.

**Comment by ekortright** [comment]
> Please install the new version of Muse Hub from https://www.musehub.com/ and use it to update your sounds to the latest available versions, then let us know whether this fixes the problem for you.

I'm on Pop!_OS 22.04 (variant of Ubuntu).  When I go to musehub.com and click Download, I get an error: "Unsupported operating system."  Needless to say, I have been using Muse Sounds with MuseScore 4.3.

**Comment by MarcSabatella** [comment]
@ekortright for Linux, you need Muse Sounds Manager, downloaded from MuseScore.org.  It’s still not updated for the new sounds, but definitely the existing sounds that worked with 4.3 should still work with 4.4 and do for me.  So maybe just reinstall any that somehow got messed up - like maybe an automatic update got interrupted.

**Comment by MarcSabatella** [comment]
Oh, that’s way way too old.  You should be on at least 0.6.  Try uninstalling some sounds and reinstalling.

**Comment by ekortright** [comment]
Thank you.  Yes, uninstalling and reinstalling the sounds seems to make them work on 4.4.1.
