### ISSUE TITLE
Creating time signature doesn't fill entire window

### ISSUE THREAD

**Issue by UnchartedDemon** [musescore/MuseScore#24361]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. open a score
2. go to time signatures
3. try to create a custom time signature 

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/eec9d6f9-a5bd-4c98-8f21-b4d0046d0813)

### What is the latest version of MuseScore Studio where this issue is present?

4.3

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/22493
