### ISSUE TITLE
Crash when UI docked in sidebars and Musescore UI layered underneath score

### ISSUE THREAD

**Issue by lapiscarrot** [musescore/MuseScore#24370]
### Issue type

Crash or freeze

### Description with steps to reproduce

To get the crash:

1. Open a score on Windows 11
4. Dock any one of the palettes in either sidebar, causing it to disappear
5. Toggle any of the other palettes to be visible
6. Crash will always occur, sometimes with a hang beforehand

To get the UI bug:

1. Open a score on Windows 11
2. Click on the score if it is not already covering the UI

### Supporting files, videos and screenshots

Crash video (unlisted):

https://youtu.be/TUJsDPhkCGY

Diagnostic files (Note that the video was recorded on 2024.09.01 at around 21:09:20):

[crash diagnostics without DMP files.zip](https://github.com/user-attachments/files/16831300/crash.diagnostics.without.DMP.files.zip)

I could not locate any crash logs outside of the diagnostic files since the program closed with no error message.

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0.242390800, revision: github-musescore-musescore-0fcd11b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

None of the UI seems to be properly docked into the sidebars when scores first opened

Additionally, regardless of which sidebar a palette is docked in, further palettes that are already visible (so as not to trigger the crash) can only be docked into the right sidebar. Attempting to dock more palettes into this sidebar can trigger a crash, but will never appear to hang even if the crash is delayed.

Crash usually requires step 4 but will occasionally occur without it.

Neither issue was present when this version was first downloaded, but appeared upon restarting my PC [edit: and persisted upon further restarts].

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by lapiscarrot** [comment]
I have also found a similar crash to occur inconsistently when docking the Mixer or the Piano keyboard. The UI elements in question still become invisible when docked, but the crash upon toggling visibility of another element sometimes takes more toggles to occur.

**Comment by lapiscarrot** [comment]
I just pressed "Restore the default layout" and the UI bug and crash both disappeared and I can't figure out how to return to the bugged state. I don't know if the diagnostic files will help with preventing whatever bugged state this was from occuring in the future, but this is no longer a problem for me.

**Comment by MarcSabatella** [comment]
This may or may not be connected to a problem I see reported fairly often with 4.4, where people show screenshots of a similar effect - panels all undocked, even the score, and nothing seems to respond as it should.  I'm not sure they got them by any explicit docking or undocking though - they seem usually to suggest it just started up that way.

I'll keep my eye out for reports like this ging forward and add links here, to see if we can collect info that would help us identify what triggers it.

**Comment by cbjeukendrup** [comment]
@RomanPudashkin Since https://github.com/musescore/MuseScore/issues/24573 was fixed, i.e. this situation shouldn't be reachable anymore at all, do you think we can close this issue?
