### ISSUE TITLE
Playing the score in MuseScore Studio4x, puts a lot of strain on the computer's CPU and GPU and RAM.

### ISSUE THREAD

**Issue by muzyk72g** [musescore/MuseScore#24393]
### Issue type

General playback bug

### Description with steps to reproduce

Playing the score in MuseScore Studio4x, puts a lot of strain on the computer's CPU and GPU and RAM. 
This makes the computer heat up a lot and consumes a lot of power, and thus quickly drains the laptop battery.
The more elaborate the score, the greater the consumption of computer resources.
This is a serious problem. 
In earlier versions of MuseScore 1x, 2x, 3x, the load on the computer was very minimal (then it was very good in this regard).

### Supporting files, videos and screenshots

![CPU and Graph GPU and RAM](https://github.com/user-attachments/assets/98fdca9a-5bf7-44c1-a644-f43952ea8429)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio 4.4

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 (64-bit)

### Additional context

The problem may be with the MuseScore engine, or with the cursor running very smoothly when playing notes.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
Please ZIP and attach the score that causes the problem.  If you see it with multiple scores, just choose any of them.

**Comment by SteveBlower** [comment]
Also check whether your PC meets the requirements listed at the bottom of the download page https://musescore.org/en/download

As with most software, newer versions with more capabilities Version 4 does need more computing power than V 3.

**Comment by RomanPudashkin** [comment]
I'd like to add to the comments above that you shouldn't compare MS3 and MS4 if you're using Muse Sounds (and you are, just looking at your screenshot). MS3 does not support Muse Sounds or VST/effects, nor does it have many engraving enhancements that MS4 has, so increased resource consumption is inevitable. If you want to reduce resource consumption, you can:
1. apply the "MuseScore Basic" profile in the Playback setup dialog (or apply MS Basic manually to each channel)
2. increase the buffer size in the preferences (4096 has the lowest CPU usage)

**Comment by muzyk72g** [comment]
This is true for any large/extended score, written in MuseScore. With any large score, it is the same, that is, high consumption of GPU Graphics Processor, CPU Computer Processor and RAM. This affects (as I wrote earlier) the rapid consumption of the laptop's battery, because the computer's power consumption then is very high (when playing the score with MuseScore Studio 4.4).

**Comment by SteveBlower** [comment]
But you don't say what your system set up is.  What CPU? what memory? SSD or HDD? If your PC doesn't meet the specification recommended to run Musescore 4 then it is likely to push the CPU etc. to its limits and beyond.  

I recently upgraded from Intel i5, 8 Mb, HDD, Win 10 to i7, 16 Mb, SSD, Win 11.  The old system was fine with Musescore v3 but with v4 it  sometimes managed to play chamber orchestral scores, albeit with a few glitches here and there.  The new one takes full symphonic scores in its stride.

Does **your** system meet the specifications?

**Comment by muzyk72g** [comment]
Unfortunately, already these requirements do not meet my computer, which are recommended for MuseScore v4.
Therefore, in order to continue using the latest versions of MuseScore 4x and above smoothly, I decided to write about it on “GitHub” so that it would come to the developers or even the creators of MuseScore to try to reduce the resource requirements for the latest versions of MuseScore. Mainly this affects the playback of a large (multi-track) score. But the problem also applies to long notes, such as playing an entire note, where as it sounds out, the sound is jagged with interruption of the sound being played, and this is on light sounds with MuseScore Sounds Basic (and this should not be the case, this is some kind of problem / bug). 
Immediately after the release of MuseScore4.0, I wrote about this on the MuseScore forum, but so far nothing has been done about it.
I believe that I'm not the only one who is affected by MuseScore4's excessive specifications, but many users who have older (generally, well-functioning) computers, and want to use the latest versions of MuseScore4.
That's why, it's so important to make less demands on the computer's resources, even by introducing some additional feature to change (only for willing users) that would make MuseScore much lighter for the computer.

Translated with DeepL.com (free version)

**Comment by RomanPudashkin** [comment]
@muzyk72g what buffer size are you using? Have you tried changing it to 4096? You can change it in the preferences dialog as shown here
<img width="906" alt="Screenshot 2024-09-05 at 11 23 27" src="https://github.com/user-attachments/assets/4024a156-bb0d-438e-be44-b53caea6478d">

**Comment by MarcSabatella** [comment]
So to be clear: all of the numbers you are reporting are using MS Basic only - nothing you are talking about is specific to using Muse Soiounds, which of course wasn't available on MU3?

Also, when you describe the sound as "jagged", that to me is a sign your audio device sample rate is not matching what MuseScore is expecting.  See if you can set it manually to 44.1 kHz.

**Comment by RomanPudashkin** [comment]
@muzyk72g please try this build (PR: https://github.com/musescore/MuseScore/pull/24576):
https://github.com/musescore/MuseScore/actions/runs/10771839882/artifacts/1908620886

It should consume less CPU/GPU during playback (although, of course, still not MS 1.x level :))

**Comment by zacjansheski** [comment]
Closing, no response
