### ISSUE TITLE
Copy/Paste staves ignores Time signatures (3/4, 4/4, 2/4,...) 

### ISSUE THREAD

**Issue by vespadj** [musescore/MuseScore#24394]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1) Copy staves with times signature changes. 
2) Paste to the end on empty steves

Duplication of all objects is expeted, but time signatures are missed, notes swap between staves (1/4 base time respected).

Workaround: set manually time signatures before Paste. 

### Supporting files, videos and screenshots

None

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

I was unable to check

### Operating system

Ubuntu 22

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DaddyLudwig** [comment]
Ability to copy paste time signatures has already been requested here: https://github.com/musescore/MuseScore/issues/15590
