### ISSUE TITLE
[Muse Sounds Woodwinds] Flute 2 instrument sound playback plays additional, incorrect notes

### ISSUE THREAD

**Issue by Drnagol369** [musescore/MuseScore#24409]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

As far as I know,
-Create a new score, with a flute instrument
-Input some notes into the score
-Change the sound in the mixer tab to Flute 2 in Muse Sounds
-Expected: It plays the correct notes, and doesn't play any additional notes
-Actual: It plays some correct notes initially, then plays the correct notes, but with additional, out-of-tune notes upon those.

Furthermore, I repeated this a few times, and it plays the exact same wrong notes. 
Not just this, but it appears to be the exact same wrong notes no-matter how large the gap is, unless there is no gap, in which case the first - specifically higher - note doesn't play.

I do not know how the Muse Sounds playback system works, but my best guess is that, for some reason, the sample forward of the one played before is being played - in other words, the sample playback has bounds which are too large. That's only a guess, though.

### Supporting files, videos and screenshots

Musescore 4.4 (normal gap)
https://github.com/user-attachments/assets/2f01688c-5daf-411c-bd7b-339dafbc2d2b

Musescore 4.4 (large gap, but still overall same glitchiness)

https://github.com/user-attachments/assets/ecab8577-dd4c-4198-89d5-1bc4ad0f3372

Musescore Nightly 03/09/24 (no gap, but still playback issue)
https://github.com/user-attachments/assets/34f4a41b-29a2-4ef6-9b30-e082130e4c26

### What is the latest version of MuseScore Studio where this issue is present?

Latest nightly build (03/09/24)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

Intel Core I7 12700H
NVIDIA GeForce RTX 3050 Laptop GPU with latest Game Ready drivers (560.94)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
Please report Muse Sounds-specific issues [here](https://support.musehub.com/hc/en-gb) (or via Muse Hub directly). Thanks!
