### ISSUE TITLE
Fioritura Feature

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#24422]
### Your idea

Fioritura: let any note sequence expand or contract to fit the measure; see Gershwin's Rhapsody in Blue,
where bars 1 and 15 have extra notes in the clarinet gliss; see also Chopin Nocturne op. 9 no. 1 in B-flat minor (image below). Musescore would automatically calculate a way to line up the fioritura with any other strict time passages in the same measure (e.g. in the Chopin Nocturne, Musescore would play 22 notes over 12 in measure 3.)
![image](https://github.com/user-attachments/assets/5fdf992a-6db5-449c-8746-c04b2cc77165)

### Problem to be solved

This feature would drastically improve Musescore's power; it would allow pieces by Chopin, Handel, Liszt, Gershwin, and others to be notated in Musescore. As of now, Musescore cannot properly notate any of the following pieces:
Chopin Nocturne op. 9 no. 1 in B-flat minor
Liszt-Paganini Etude no. 6, var 11
Handel Passacaglia in G-minor
etc.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by DaddyLudwig** [comment]
The Chopin example you give can be notated in MuseScore already. If you go to Add -> Tuplets -> Other and then put in a ratio of 22:12, it will give you a 22 tuplet of eighths covering the full 6/4 bar. See:

![image](https://github.com/user-attachments/assets/c1d9e7bb-4a69-411f-bf61-c1f1383c5a88)


https://github.com/user-attachments/assets/8aaea7b8-68da-4787-bcca-2bb90a6a58ec

**Comment by MarcSabatella** [comment]
Maybe I'm missing something, but aren't those just tuplets, you can add already via Add / Tuplets / Other?

**Comment by FrancRos31** [comment]
I managed to copy a cadenza in a trumpet part (trumpet/piano piece) last year (see image). It surely is possible to copy the clarinet solo in Rapsody in blue, but it's very strenuous because of all the tricks involved (merging measures, hiding rests etc and there was an high risk of making crash the program). Nonetheless I find the idea for this feature very praiseworthy: it would save a lot of time and headache.
![2024-09-04 00_30_47-Variazioni su un tema dalla Norma, Arban (partitura) pdf - Adobe Acrobat Reader ](https://github.com/user-attachments/assets/c75f8591-fc94-46a1-82fb-59983051fa57)
.

**Comment by oktophonie** [comment]
I'm closing this as a) the initial example is facilitated via the tuplets feature, b) more complex examples can be achieved by joining measures etc, and c) the request for a real 'free time' mode is covered by https://github.com/musescore/MuseScore/issues/21220

**Comment by wizofaus** [comment]
https://github.com/musescore/MuseScore/issues/21220 is a pretty weird feature request though, this one seems far better thought out, with good examples etc.

**Comment by shoogle** [comment]
@wizofaus, this one convers a feature that already exists (i.e. custom tuplets) whereas #21220 doesn't.
