### ISSUE TITLE
ambitus not applied if part begins with multi measure rest

### ISSUE THREAD

**Issue by amoneti** [musescore/MuseScore#24434]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

Please see details and workaround from Jojo Schmitz in https://musescore.org/en/comment/1256165#comment-1256165; Jojo suggested I report this here.

### Supporting files, videos and screenshots

see link above

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio 4.4

### Regression

I was unable to check

### Operating system

Mac OS 14.16.1

### Additional context

Nothing to add

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
It is __not__ a regression vs. 4.3.2 or 4.3.1 (and I didn't check older 4.x version) but it __is__ a regression vs 3.x

**Comment by Jojo-Schmitz** [comment]
I believeI have to take back that it is a Mu3 regression, that seems tio have the same issue
Ambitus applied to score doesn't show in part(s) and Ambitus applied to a multirest measure doesn't work at all
