### ISSUE TITLE
A serious bug that will cause the sheet music to not load

### ISSUE THREAD

**Issue by TSKnoAya** [musescore/MuseScore#24466]
### Issue type

Opening/saving issue

### Description with steps to reproduce

1. Parentheses cannot be added to the note head. Click the button with parentheses on the right, and the parentheses will not appear on the note head where parentheses should appear.
![image](https://github.com/user-attachments/assets/36a14cd6-e5f4-4181-96f7-acac9bdd0ea6)
2. 2. .mscz files named in Chinese and Japanese cannot be loaded and will be identified as "unknown file type"
![image](https://github.com/user-attachments/assets/d65b3076-7753-417c-a974-0657beaaa97f)
After testing, it was found that the BUG was caused by the garbled code in the loading window
![image](https://github.com/user-attachments/assets/1c276488-7537-4323-8c9a-a84f178b2229)
You can bypass this window to load the file normally. The operation method is "Music Score → Close the currently opened music score". If no music score is currently opened, the "Loading "xxxx.mscz" window will not appear when you open the music score. You can then load Chinese or Japanese music scores.
3. The old version (4.3) cannot load the project saved by the new version (4.4)
![image](https://github.com/user-attachments/assets/474baddc-471c-4287-833b-b162c3a95979)

### Supporting files, videos and screenshots

[MuseScore4.4BUG演示.zip](https://github.com/user-attachments/files/16886292/MuseScore4.4BUG.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0.242390800

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by RomanPudashkin** [comment]
I just replied to you in [this comment](https://github.com/musescore/MuseScore/issues/24464#issuecomment-2330905286). Please open a new issue **only for the first bug on your list**. The second bug has already been fixed

>The old version (4.3) cannot load the project saved by the new version (4.4)

This is by design, so not a bug

**Comment by Jojo-Schmitz** [comment]
See also https://github.com/musescore/MuseScore/issues/24464#issuecomment-2330962532
