### ISSUE TITLE
Weird sub-bracket behavior when deleting Flute 2 in Symphony Orchestra template using Add/Remove instruments dialog

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#24468]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

**Case 1**
1. Open Symphony Orchestra template
2. Open Add or remove instruments dialog
3. Delete Flute 2

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/5387e9e5-d7ae-40a0-9def-71d8313eff54

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this works in the latest released version (**4.4.0**) and is broken in the nightly builds

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
@oktophonie Not sure about 4.4.2.. I've found only 1-2 similar cases in our templates:

https://github.com/user-attachments/assets/f4515b53-2ce3-45e1-80a0-9a9503c48a7a

But this is also a **regression** from **4.4.0**

**Comment by cbjeukendrup** [comment]
Oops, this one may be my fault (#24221 probably)

**Comment by Jojo-Schmitz** [comment]
Seems a Mu3 regression, at least I can't reproduce it there

**Comment by DmitryArefiev** [comment]
Fixed in #24489
