### ISSUE TITLE
Crash when try to select Text color

### ISSUE THREAD

**Issue by juancarlangas** [musescore/MuseScore#24461]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Create a rehearshall or chord text
2. try to change the text color

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/037f8030-9761-44a9-8cfe-1de24fd55298

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0.242390800-x86_64

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Kubuntu 24.04 LTS

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
Thanks for reporting, but this is actually already fixed for the upcoming 4.4.1 - see https://github.com/musescore/MuseScore/issues/24173
