### ISSUE TITLE
会导致乐谱无法加载的严重BUG

### ISSUE THREAD

**Issue by TSKnoAya** [musescore/MuseScore#24464]
### Issue type

Opening/saving issue

### Description with steps to reproduce

1.符头圆括号无法添加，点击右侧带圆括号的按钮，原本应出现圆括号的符头不会出现圆括号
![image](https://github.com/user-attachments/assets/67c1e6d2-c37a-41a1-820a-a29ea97b26f6)
2.中文命名和日文命名的.mscz不能加载，会被识别为“未知文件类型”
![image](https://github.com/user-attachments/assets/efab10f6-f681-48fd-8ca6-c0e0317a51f7)
经过测试，可知是由加载窗口乱码导致的BUG
![4195c19f0f7bebdda1b7dcf2a34d3398](https://github.com/user-attachments/assets/0b79332d-4f59-48bd-8fea-624527bf2c65)
可以通过绕开该窗口正常加载文件，操作方式为，“乐谱→关闭当前已打开的乐谱”，在当前没有打开任何乐谱的情况下，打开乐谱不会出现“正在加载“xxxx.mscz”的窗口，即可加载中文或日文的乐谱
3.旧版本(4.3)无法加载新版本(4.4)保存的工程
![image](https://github.com/user-attachments/assets/3cb07df7-578a-4e34-8d40-c146a2c4e9c4)

### Supporting files, videos and screenshots

[MuseScore4.4BUG演示.zip](https://github.com/user-attachments/files/16885264/MuseScore4.4BUG.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0.242390800

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
3. thhird item is by design and not a bug. However, there's a workaround, see https://musescore.org/en/faq#faq-367692
