### ISSUE TITLE
Screen reader doesn't pronounce Format > Style > Tab names (Linux, Orca)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#24479]
### Issue type

Accessibility issue (e.g. for keyboard-only or screen reader users)

### Description with steps to reproduce

1

### Supporting files, videos and screenshots

![Screenshot from 2024-09-05 17-16-38](https://github.com/user-attachments/assets/089506b8-488f-4c0c-a88b-ad0d7aff481b)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this used to work in **MuseScore 4.3.2**

### Operating system

LinuxUbuntu22.04

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
@DmitryArefiev just to confirm: this is a Linux-specific bug, right? 
I am able to hear the page names read out on Win.

**Comment by DmitryArefiev** [comment]
@bkunda Yes, doesn't occur on Windows. There is the same issue on Mac #17059 but that's not a recent regression as #24479

**Comment by DmitryArefiev** [comment]
After latest Orca (screen reader) update to **v46.1**, this no longer occurs

Tested in **4.4.3** and **4.5** nightly builds on LinuxUbuntu22.04.1 LTS and **Orca 46.1** - **FIXED**

Closing
