### ISSUE TITLE
Chord symbols no longer play after adding them and click on empty space or hit Esc

### ISSUE THREAD

**Issue by csbubbles** [musescore/MuseScore#24485]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

Please refer to https://musescore.org/en/node/367758.

Basically, after entering a new or modifying an existing chord symbol, MuseScore is supposed to play it right after that (configured that way in the settings, and I believe it's the default behavior). It worked fine in 4.3, and it stopped working after updating to 4.4. I verified it by downgrading to 4.3 (still works there), and upgrading to 4.4 (doesn't work) again.

I am attaching the view recording that demonstrate the problem below.

1. Add a chord
2. Click on empty space or hit Escape

### Supporting files, videos and screenshots

[4.3.2.241630832-480.mov_.zip](https://github.com/user-attachments/files/16898642/4.3.2.241630832-480.mov_.zip)
[4.4.1.242490810-480.mov_.zip](https://github.com/user-attachments/files/16898643/4.4.1.242490810-480.mov_.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1.242490810

### Regression

Yes, this used to work in **MuseScore 4.3.2**

### Operating system

macOS 14.5 (23F79)/Windows10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
This works as expected for me in 4.4.1.  Be sure to update to that if you haven't already.  If the problem continues, check your mixer settings to be sure the chord symbols channel isn't muted, and double-check the setting Preferences / Note input / Play chord symbols .  If that's not it, please attach the specific score with the problem.

**Comment by csbubbles** [comment]
The last version that I tried is 4.4.1.242490810. The issue started a few days back when MuseScore got updated to 4.4.0.

The chord channel isn't muted. The chords are being played with the score. The issue is when you enter or change the chords. After your action, it's expected for the chord to be automatically played right away, so you would know for sure if you entered the right one. It works in 4.3, but doesn't work in 4.4. Any new score that you create or any previous one that you load.

As I explained in the bug description and in the support forum, I reinstalled 4.3 and 4.4 a couple of times, and the behavior is 100% reproducible every time – it works in 4.3, and it doesn't work in 4.4. Please refer to the videos that I attached earlier.

I am attaching the screenshot with the settings as well. They are the same in 4.3 and 4.4. It's just they don't seem to be working in 4.4; it never plays the chords after they are entered or changed. I mentioned in the support forum that I tried checking/unchecking those options as well, it doesn't seem to have any effect in 4.4.

<img width="992" alt="Screenshot 2024-09-05 at 1 42 09 PM" src="https://github.com/user-attachments/assets/c4036a76-8916-4d46-896b-de979fd67d7f">

**Comment by csbubbles** [comment]
I am attaching another video, I hope it can help clarify what's going on from the user experience perspective, and a new score which was used in the recording as well. Though, as I mentioned, it doesn't matter which score it is.

[MuseScore 4.4 - Chord issue.zip](https://github.com/user-attachments/files/16900213/MuseScore.4.4.-.Chord.issue.zip)

**Comment by MarcSabatella** [comment]
Ah, I can see in the video you are clicking outside the chord or pressing Esc instead of hitting Space to move to the next beat.  I can now confirm that those specific actions will not trigger the playback, indeed - sorry, it hadn't occured to me to try that.

**Comment by csbubbles** [comment]
Yep, that's right, I usually press Esc to finish the chord symbol change. Sorry, I didn't clarify this part earlier.

**Comment by DmitryArefiev** [comment]
Confirm on my side. The same on Windows 10

I've edited the summary and added steps to reproduce

**Comment by DmitryArefiev** [comment]
Fixed in #24506
