### ISSUE TITLE
Musescore 4.4.1 score crash

### ISSUE THREAD

**Issue by swanhes** [musescore/MuseScore#24492]
### Issue type

Crash or freeze

### Description with steps to reproduce

Opening a score that with 4.4 would open normally, now crashes the app.

Reverting back to 4.4

### Supporting files, videos and screenshots

[d.zip](https://github.com/user-attachments/files/16904188/d.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.6, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.1-242490810, revision: github-musescore-musescore-0b3dd00

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS Sonoma 14.6.1

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by swanhes** [comment]
If more diagnostics are needed I will gladly provide them.

**Comment by oktophonie** [comment]
Are you able to supply the problematic MuseScore file? (.zip it first to attach here)

**Comment by Dima-S-Jr** [comment]
See also the [comment](https://github.com/musescore/MuseScore/issues/24478#issuecomment-2332310491)

**Comment by oktophonie** [comment]
@swanhes I think we have solved this one, but if you could check whether the file(s) in question with a build of https://github.com/musescore/MuseScore/pull/24500 that would be great (or supply us with a file we can check with).

**Comment by swanhes** [comment]
> @swanhes I think we have solved this one, but if you could check whether the file(s) in question with a build of #24500 that would be great (or supply us with a file we can check with).

Sorry to be back only now, I couldn't reply sooner.
I can confirm that the score can now be opened.
Thanks!
