### ISSUE TITLE
Some shortcuts with Cmd/Opt/Ctrl don't work on macOS in 4.4

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#24497]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

**Case 1**
1. Create **Ctr+Cmd+E** shortcut for Export window
2. Close MS
3. Open MS and open a score
4. Try to to use **Ctr+Cmd+E** - it **doesn't open** Export window
5. Now open Export window from File>Export - it opens fine
6. Close Export window
7. Try to to use **Ctr+Cmd+E** again - it **works fine** now

The same issue for adding expression text shortcut (**Cmd+E**)

https://github.com/user-attachments/assets/a7f8ee51-7057-47bb-a0be-e531618118a4

**Case 2**
1. Create **Ctr+E** shortcut for Toggle concert pitch
2. Try to use it - it **doesn't work**

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this used to work in  **MuseScore 4.3.2**

### Operating system

Mac13.6

### Additional context

https://musescore.org/en/node/367571
https://musescore.org/nl/node/367679

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
@DmitryArefiev why did we remove the "regression MS4" label? Surely if it was working in 4.3.2 and broken in 4.4/4.4.1, then it's a regression?

**Comment by bkunda** [comment]
@DmitryArefiev I think this can possibly be downgraded. Primary cmd shortcuts still seem to work (save, copy, paste, undo, open, etc.). Stave text also can be added via cmd+T, so the fact that expression text doesn't work seems like a peculiar problem.

**Comment by cbjeukendrup** [comment]
See also https://github.com/musescore/MuseScore/issues/24938 though, which is probably the same problem under the hood but there copy/paste/save are also broken.

**Comment by DmitryArefiev** [comment]
Fixed in #25093

**Comment by Johan-v** [comment]
Any possible relation to the shift problem with Belgian azerty?

**Comment by DmitryArefiev** [comment]
Was broken recently. Now fixed again in #25273

**Comment by DmitryArefiev** [comment]
> Any possible relation to the shift problem with Belgian azerty?

@Johan-v Nope.. it's another one. #25186 (#14539) unfortunately still exists
