### ISSUE TITLE
Undo of join measure action causes improper scrolling and shifts elements of layout

### ISSUE THREAD

**Issue by Nazaretto** [musescore/MuseScore#24496]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

**Elements affected**: pages, brackets, frames and selection.

### Steps to reproduce
1. Insert enough empty measures to have multiple pages.
2. At the first page in second system leave 3 empty bars from the left and enter few notes in the 4th bar for Voice 1 and Voice 2.
3. Add text to voice 1 with **hyphens**.
4. At the first system select 3+1 bars and join them.
5. Undo the action.
6. Try to scroll the pages from left to right.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/0b6ddc53-2f0f-4c5b-932f-0863b91ac14a

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0.242390800

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 13.5.1

### Additional context

Revision info:
OS: macOS 13.5, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
Related also to https://github.com/musescore/MuseScore/issues/23030
