### ISSUE TITLE
Crash upon inputting notes when VOXOS Women or Men are loaded

### ISSUE THREAD

**Issue by TimBomBom** [musescore/MuseScore#24491]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. create a score with "women" part
2. Assign sound to VOXOS Epic Choir > Women
3. try to input any note
4. crash

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/c20a93e9-a8e2-4ce7-b811-0f0d16db85a5

[MuseScore_240905_212132.log](https://github.com/user-attachments/files/16901667/MuseScore_240905_212132.log)

[MuseScore_240905_212132_again.log](https://github.com/user-attachments/files/16901680/MuseScore_240905_212132_again.log)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.4.1-242490810, revision: github-musescore-musescore-0b3dd00

### Regression

I was unable to check

### Operating system

Windows 10 Version 2009 or later, Arch.: x86_64

### Additional context

This also crashes upon loading the "men" sample, but the others seem fine. I'm not sure if it's relevant, but I uploaded the logs found in my appdata that were generated both times that it crashed. If other uploads/context is needed pls lmk.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by TimBomBom** [comment]
Note that this error still occurs even after patch 1.0.6 released by cinesamples which supposedly "fixed the men and women presets."

**Comment by zacjansheski** [comment]
@TimBomBom Could you please confirm your Muse Sampler version?

Diagnostic > Muse Sampler > Check Muse Sampler

@RomanPudashkin could you please take a look at the diagnostic files?

**Comment by TimBomBom** [comment]
It is muse sampler 0.100.2 as shown in the video

**Comment by DmitryArefiev** [comment]
I **can reproduce** it in **4.4.0** and **4.4.1** with VOXOS Epic Choirs **v1.0.6** and musesampler **v0.100.2.314** (Win/Mac)

There is no crash in **4.3.2**, but also there is **no sound** when using VOXOS Women or Men samples

**Comment by sampleeditor** [comment]
Resolved with VOXOS Epic Choirs 1.0.7
