### ISSUE TITLE
Footer text on parts does not reflect changes in Style diaglogue

### ISSUE THREAD

**Issue by pgrimes2002** [musescore/MuseScore#24503]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

When using scores from the prior release of Musescore, the part footers are in a different font from the Style dialogue. It will change, but only if you do so in the properties panel.

### Supporting files, videos and screenshots

<img width="892" alt="Screenshot 2024-09-06 at 9 47 01 AM" src="https://github.com/user-attachments/assets/2d1533a2-b554-47a5-9483-f93a305b6934">

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Sonoma 14.5

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by mathesoncalum** [comment]
I suspect what's happening here is that the footer text in question consists solely of copyright text, which got given its own style in 4.4 (task [here](https://github.com/musescore/MuseScore/issues/23325), PR [here](https://github.com/musescore/MuseScore/pull/23475)).

@pgrimes2002 can you try going to Style->Text Styles->Copyright and editing the values from there? Does this behave as expected?

![Screenshot 2024-09-06 at 19 37 48](https://github.com/user-attachments/assets/b5e6806f-c699-4d8d-a1e0-10a334dbb27c)

Thanks in advance!
