### ISSUE TITLE
Unable to log into MuseScore.com account since v4.4

### ISSUE THREAD

**Issue by barnabycollins** [musescore/MuseScore#24511]
### Issue type

Cloud issue (opening, saving, logging in/out)

### Description with steps to reproduce

Since upgrading to v4.4, I have found that saving cloud scores gave me the 'Unable to connect to the cloud' error message, no matter my network conditions:

I have realised today that this is because I have been logged out of the MuseScore app, and attempted to log back in, but was unable to.

## Steps to reproduce

- Open MuseScore Studio 4.
- Navigate Home -> My accounts.
- If not logged in, click 'Sign in'.
- Observe that MuseScore.com is opened in a default browser, and redirects you to https://musescore.com/desktop-signin-success after authorising.
- Switch back to MuseScore Studio 4.
- Observe that nothing has changed in the UI.

I've tried various combinations of logging in and out in my browser, restarting my computer, and restarting MS4, and had no luck as yet.

I think this might be a wider problem with the current version, and therefore decided to open an issue, as upon searching for the problem I found a number of recent comments mentioning this problem on the MuseScore forum:

[login fail](https://musescore.org/en/node/367914)
[\*SOLVED\* unable to log in on Musecore 4](https://musescore.org/en/node/342353) (original post is old but has several new comments)

### Supporting files, videos and screenshots

[MS4 Login Issue.webm](https://github.com/user-attachments/assets/b01a6c33-854f-48f3-9726-ff5b4dd90ff9)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11 23H2 (build 22631.4037)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
Thanks for logging this! Since we can't reproduce this ourselves, we'll need a bit more information to be able to fix this.

When you go to Home > Learn, do you see any video tutorials? Or something saying that there is no internet connection?

Could you also do the following:
1. In MuseScore, go to Diagnostic > Save diagnostic files
2. Choose a location on your computer to temporarily save these files
3. Upload the resulting ZIP file here. 

Thanks in advance!

**Comment by barnabycollins** [comment]
Hi @cbjeukendrup - thanks for the quick reply!

Home > Learn shows 'Sorry, we are unable to load these videos right now':

![image](https://github.com/user-attachments/assets/f3779118-6cdf-4f00-86f4-1276f50e40a2)

...and here are the diagnostics:

[ms4-diags.zip](https://github.com/user-attachments/files/16918362/ms4-diags.zip)

I'm not using any kind of special VPN / firewall etc - just on a Wi-Fi connection to my off-the-shelf broadband router - and I've experienced this on three different Wi-Fi networks (home, mobile hotspot and local library).

Thanks for your help!

**Comment by cbjeukendrup** [comment]
Thanks for the information! 
Based on other reports I've seen, I have created a test build that potentially solves the issue; judging from your log files there is a good chance that it will work for you too. You can download it at https://github.com/musescore/MuseScore/actions/runs/10747048367. It would be great if you could let me know if it indeed works!

**Comment by barnabycollins** [comment]
@cbjeukendrup - that's worked perfectly; thank you! The 'Learn' tab is fully populated and I'm able to sign in without issues. I guess I should keep using this version until MS 4.5 is released?

**Comment by Jojo-Schmitz** [comment]
Rather until 4.4.2 is released

**Comment by cbjeukendrup** [comment]
Re. 4.4.2 timeline, I think it will be about two weeks; but this depends on how smoothly we'll be able to fix all issues we want to fix. It's unlikely that we'll go for a 4.4.3, so all issues that we want to fix sooner than 4.5 will have to be fixed for 4.4.2.
