### ISSUE TITLE
The melisma line of the sub voice lyrics extends to the end of the score

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#24519]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

**Case 1: When opening a file created in a previous version**
Open [this file](https://github.com/user-attachments/files/16914334/default.zip) (created with v4.3.2) in v4.3.2 and v4.4.1 and compare.

**Case 2: When entering melismatic lines in v4.4**
1. Create a score
2. Enter sub voice notes
3. Enter lyrics
4. Extend melisma line to the last note of the voice
Expected: Melisma line end on the last note
Actual: Melisma line extends to the end of the score

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/6f591204-e9e7-4d20-b23c-b2a50fd6921a

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore 4.4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11 23H2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
Moving to 4.4.3 as we've now run out of time for 4.4.2.
