### ISSUE TITLE
When is the solo contrabass going to be added to muse sounds?

### ISSUE THREAD

**Issue by Violoncellotenorclef** [musescore/MuseScore#24524]
This instrument is an essential in chamber ensembles, jazz bands, and contemporary music, it's a surprising fact that the solo contrabass
hasn't been added yet.

**Comment by oktophonie** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/23152, and in any case would be better asked of the Muse Sounds team directly via Muse Hub.
