### ISSUE TITLE
Tempo Markings

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#24546]
### Your idea

According to Music Notation: Preparing Scores and Parts, published by Berklee Press, the Tempo markings for marching, orchestral, scores and the like should appear above each choir.
![image](https://github.com/user-attachments/assets/0b4ad910-a565-43a2-b489-b58e78f456f9)

### Problem to be solved

Tempo markings can only be added above the first stave in scores.

### Additional context

Repeat notation (D.S. al fine, to Coda, etc.) should also appear above each choir.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment]
Covered by https://github.com/musescore/MuseScore/issues/24100

**Comment by Dima-S-Jr** [comment]
@Fourniture, may I ask which book this is from?
![365271558-0b4ad910-a565-43a2-b489-b58e78f456f9](https://github.com/user-attachments/assets/b70380e6-b946-41d7-90b8-661dbe7ae39b)

**Comment by Fourniture** [comment]
From "Music Notation: Preparing Scores and Parts" by Matthew Nicholl and Richard Grudzinski, published by Berklee Press in 2007. It's very in-depth, and covers just about every aspect of contemporary score writing practices. I would definitely recommend it to anyone who is serious about music preparation. 
Here is a link to the book on Amazon:
https://www.amazon.com/Music-Notation-Preparing-Scores-Parts/dp/0876390742
