### ISSUE TITLE
Menus and popup windows open in wrong display for multi-monitor setup.

### ISSUE THREAD

**Issue by SiruberJordan** [musescore/MuseScore#24541]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Open Musescore Studio on machine with multi-monitor setup
2. Move MS to other display
3. Click any of the dropdown menu tabs at the top of the window (File, Edit, View, etc.)
4. Select File/New...

Expected behavior:
- Dropdown menu appears below tab
- New Score wizard appears on the same display as MS

Actual behavior:
- Dropdown menu appears on other monitor where MS opens by default
- New Score wizard appears on other monitor where MS opens by default

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/48e53e3e-6c4a-47d8-b7c8-02e38f169c33)
![image](https://github.com/user-attachments/assets/f15f10b9-f355-40e1-b689-b75d95a27fc8)

### What is the latest version of MuseScore Studio where this issue is present?

2024-09-07 05:29 Nightly Build

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

- Regression from 4.3.x (issue was introduced with 4.4 update)
- MS is open in fullscreen on the right hand display in the screenshots (i.e. the left edge of the MS window is the border between the displays)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
Thanks, but this is actually reported as https://github.com/musescore/MuseScore/issues/24232

**Comment by cbjeukendrup** [comment]
Closing as a duplicate

**Comment by AlexanderMaslov** [comment]
[4.4.2]
issue still here.
