### ISSUE TITLE
Crashes when opening certain scores

### ISSUE THREAD

**Issue by nmu-nyasan** [musescore/MuseScore#24559]
### Issue type

Crash or freeze

### Description with steps to reproduce

[This file](https://github.com/user-attachments/files/16922361/Crash.zip) (from which the parts contributing to the crash are extracted from the crashing score) will cause MuseScore to crash when opened.

0. Open the score in 4.3.2. No crash occurs.
1. Open the score in 4.4.1. Crashes.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/ce9d141e-7eea-40d1-b508-0f5aed0f89ee

[MuseScore_240908_223817.log](https://github.com/user-attachments/files/16922392/MuseScore_240908_223817.log)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore 4.4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11 23H2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Dima-S-Jr** [comment]
See #24500

**Comment by nmu-nyasan** [comment]
It was a duplicate, sorry.
I have confirmed that it is fixed in the latest nightly, so I'll close it.
