### ISSUE TITLE
Windows second screen opacity

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#24579]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

Using 2 monitors with Windows 11

Open 4.4.1, move window to other screen and it is see-through

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/a721a431-13fd-4445-96eb-12d224fe6962

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.1-242490810, revision: github-musescore-musescore-0b3dd00

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

Originally reported here
https://musescore.org/en/node/368416

Diagnostic files:
[MuseScoreWindowsOpacity.zip](https://github.com/user-attachments/files/16930547/MuseScoreWindowsOpacity.zip)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
The reason that this issue is in "needs porting" is that it needs porting to the master branch (rather than to 4.4.3). That will happen via the Qt 6.8 PR, where this issue is listed. Since that PR is in the 4.5 project, I think we can now safely move this issue to "Done" in the 4.4.3 project.
