### ISSUE TITLE
Tied notes aren't tied when only one voice is playing

### ISSUE THREAD

**Issue by sbancal** [musescore/MuseScore#24574]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

1. From empty score, with two "instruments": _Vocals.Women_ and _Vocals.Men_.
2. For Soprano: Add a "quarter-note", let's say a "C", then add several tied notes with the "t" key.
3. Do the same for Alto as _Voice 2_ on the same _Women_ staff with an other note, let's say a "G", with several tied notes with the "t" key.
4. Do the same for Tenor and Bass on the _Men_ staff.

Playing it will work as expected: the notes are tied : )

Now:
1. Select all notes (ctrl-a) and uncheck the _Play_ Property
2. Select one note from Alto > right-click > select > More > Same Staff + Same Voice
3. Check the "Play" property

Now Playing it has the problem that tied notes aren't tied any more. This affect also the File > Export > Format _mp3_ feature.

Expected behavior:
No matter if we have only one or several voice playing, the tied notes are expected to sound tied.

### Supporting files, videos and screenshots

[testTiedNotes.zip](https://github.com/user-attachments/files/16928678/testTiedNotes.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

I was unable to check

### Operating system

Ubuntu 22.04

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
Stems from https://musescore.org/en/node/368413

**Comment by bkunda** [comment]
It's very likely this is occurring because the ties may not have been selected (and therefore operated upon) when the "play" checkbox was toggled. 

Does it work for you if you ensure the ties are _also_ included in the selection?

**Comment by sbancal** [comment]
Hi,
I confirm that when I select the ties and activate the "play" toggle, the ties are effective.

**Comment by Jojo-Schmitz** [comment]
Interesting, hadn't noticed that they have a play property now
