### ISSUE TITLE
Musescore main screen is not working correctly, all panels are undocked (after 4.4.0 update)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#24573]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

https://musescore.org/en/node/368003

### Supporting files, videos and screenshots

![Ekrānuzņēmums 2024-09-02 202156](https://github.com/user-attachments/assets/953aba77-6a9b-404f-b195-2dd7273e8f3d)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this works in **MuseScore 4.3.2**

### Operating system

Windows

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
(I've collected some "diagnostic files" about this, will upload them shortly)

**Comment by cbjeukendrup** [comment]
- https://musescore.org/en/node/368167#comment-1256622 -> [meow2.zip](https://musescore.org/sites/musescore.org/files/2024-09/meow2.zip)
- Sent to me via email: [Musescore dianostics.zip](https://github.com/user-attachments/files/16931490/Musescore.dianostics.zip)
- https://discord.com/channels/818804595450445834/818804809784229898/1282325871142633532 -> 
[Diag.zip](https://github.com/user-attachments/files/16931530/Diag.zip)
