### ISSUE TITLE
Changing the duration of 2 measures on 2 consecutive systems corrupts the score. 

### ISSUE THREAD

**Issue by cadiz2** [musescore/MuseScore#24583]
### Issue type

File corruption

### Description with steps to reproduce

1. Score for flute, 8 measures, spread over two systems, time signature 6/8
2. Measure 4 / Measure properties / Change the actual duration to 5/8
3. Measure 5 / Measure properties / Change the actual duration to 1/8

Result: corruption, see GIF. 

### What is the latest version of MuseScore Studio where this issue is present?

4.4. 
Works as expected with 4.3.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

- Does not occur if the change in the actual duration of the two measures is within the same system. 

- A workaround is to change the actual duration of the measure at the start of the second system, then that of the measure at the end of the previous system;

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cadiz2** [comment]
Forgotten GIF


![Video corruption](https://github.com/user-attachments/assets/b1462d28-616f-4ad7-8edb-5dc39af53ebd)

**Comment by zacjansheski** [comment]
Looks like this is fixed in https://github.com/musescore/MuseScore/pull/24562
