### ISSUE TITLE
Can't "unsolo" the metronome track (for scores imported from pre-4.4)

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#24598]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. In MuseScore 4.3.2, create a score where the metronome track is solo'ed 
-> all other channels are auto-muted as long as the metronome track is solo'ed
2. Open that score in 4.4
-> now there is no way to unsolo the metronome track, so all other tracks are stuck auto-muted forever. 

This is a consequence of https://github.com/musescore/MuseScore/commit/21bbcedfbea2b4502355ab04216550336a771bb7.

Possible solutions:
- bring the solo button back for the metronome channel
- programmatically unsolo the metronome whenever reading a file

### Supporting files, videos and screenshots

An affected file is found here: https://musescore.org/en/node/368461
Makes the solo/mute buttons in the mixer look rather mysterious:
<img width="1516" alt="Scherm­afbeelding 2024-09-09 om 18 49 32" src="https://github.com/user-attachments/assets/5b1e0215-8e64-4d10-8e4f-c93a14e79841">

### What is the latest version of MuseScore Studio where this issue is present?

4.4.x; "regression" vs 4.3.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

\*

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
If the reasons for removing the solo button were sound (I suspect they were, but it was a while ago when this decision was made!), then it seems sensible that @cbjeukendrup's second suggestion above could be the preferred solution. I.e.: 

> programmatically unsolo the metronome whenever reading a file
