### ISSUE TITLE
Follow written tempo when 'c.' added to tempo text

### ISSUE THREAD

**Issue by Christof1981** [musescore/MuseScore#24596]
### Your idea

1. Create a tempo, i.e., crotchet = 80.
2. Add a 'c.' to the text, indicating 'circa', so it's crotchet = c. 80.
3. Now change the number, i.e., crotchet = c. 100.

MuseScore will still play it at 80, and in order for it to be played at 100, it is necessary to override the written tempo. My idea is that the tempo text should be more easily customisable so MuseScore will still read the tempo with the addition of text.

### Problem to be solved

The problem is the lack of customisation, and the ability to make tempo text appear as you want it to and play at the correct tempo while removing the extra step of overriding the written tempo.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Jojo-Schmitz** [comment]
I think this actually is a bug, as "crotchet = ca. 80" doesn't have that problem

**Comment by pacebes** [comment]
Hi

I am looking for a good first issue.  I would like to give it a try!

Thanks

**Comment by Jojo-Schmitz** [comment]
Check https://github.com/musescore/MuseScore/blob/272077bebaf5859219d65aa5ab07e5ebd47c1ebd/src/engraving/dom/tempotext.cpp#L269 ;-)

**Comment by pacebes** [comment]
Thanks

I have been looking in this method as you suggest and there are several replacements:

>     s.replace(u",", u".");
>     s.replace(u"<sym>space</sym>", u" ");
>     s.replace(u"≒", u"=");
>     s.replace(u"≈", u"=");
>     s.replace(u"~", u"=");
>     s.replace(u"ca.", u"");
>     s.replace(u"approx.", u"");

I think the easy way is to add something like:
>     s.replace(u"c.", u"");

I don't know if there are any additional texts that should be supported. Is it just "c." ?

Kind regards

**Comment by Jojo-Schmitz** [comment]
I'd stick with that one extra line for now

**Comment by pacebes** [comment]
Ok

**Comment by pacebes** [comment]
I have created the following pull request: 

https://github.com/musescore/MuseScore/pull/24612
