### ISSUE TITLE
Reply to reviews on musehub

### ISSUE THREAD

**Issue by TimBomBom** [musescore/MuseScore#24603]
### Your idea

Allow comments/replies to be made on the reviews people post on musehub. If someone posts a review on a musesounds vst library, somebody can reply with guidance or a fix for an issue they have or something. Otherwise, people may leave bad reviews because they don't know how to fully use their product.

### Problem to be solved

Some people are sort of ignorant of the existence of user guides and such they post a negative review. There is no way to reply to a review or reach out to that person to guide them. Their mistake makes the vst's reputation worse bcs the user doesn't know how to use it. One person on voxos epic choirs left a bad review because they can't find the phoneme list (which is present in the user guide), another negative review on voxos complained that there weren't solo alto tenor or bass, when the full vst also doesn't have them (did they expect a 98.1% discounted version for musescore would have more features than the original??). Another person on the OT First Chairs left a bad review because the sounds are too detached, but nobody is able to tell them that legato playing is activated when notes are slurred and play détaché by default.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
Sorry, this is an issue specific to Muse Hub and not MuseScore Studio. 
You're very welcome to suggest it via Muse Hub customer support though. 
Thanks!
