### ISSUE TITLE
[macOS dev environment] Unable to have a different version of Qt installed by brew

### ISSUE THREAD

**Issue by rpatters1** [musescore/MuseScore#24618]
### Issue type

Other type of issue

### Description with steps to reproduce

When I was initially trying to get my environment set up for MuseScore Studio, I ran into a problem because homebrew had previously installed Qt 6.7.2 as a dependency of some other package. The Qt includes for 6.7.2 were reachable at `/usr/local/include/`.

I installed Qt 6.2.4 at the default location chosen by the Qt installer, `~/Qt`. Then, as documented, I created `build_overrides.cmake` to point the build at that version of Qt using the `QTDIR` environment variable. However, the build kept failing on compiler errors in the Qt headers.

After carefully examining the command line calls to the C++ compiler, I discovered the problem. The `-I/usr/local/include` option appears before any of the `-I` options for Qt. (Note that only some of the files in the build use `-I/usr/local/include`. That made the problem doubly confusing.) That means the compiler was finding the include files at `usr/local/include` because it came first in the chain.

I resolved my problem by uninstalling the brew-installed version, but I had to override a warning that I was removing a dependency for some other packages. This does not seem ideal, and there would appear to be an easy fix: simply emit the `-I` directives for Qt before `-I/usr/local/include`. But I am too new to this environment to know how to make that change.

### Supporting files, videos and screenshots

I fully described the problem above. Unless I break my build environment by reinstalling Qt with homebrew, I can't recover the logs.

### What is the latest version of MuseScore Studio where this issue is present?

Current development environment.

### Regression

I was unable to check

### Operating system

macOS

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
Is this on Apple Silicon? If not, that might explain why I'm not having this: on Apple Silicon, HomeBrew installs to `opt/homebrew` instead of `usr/local`, so if I want the HomeBrew Qt to be used, I explicitly have to add it to PATH. And otherwise it doesn't interfere with anything.

**Comment by rpatters1** [comment]
My system is a Silicon machine, but ngl my homebrew situation is something of a clusterf*k. Because I migrated to my current machine from an x86 machine (and that from an x86 machined before it, etc., etc.), my homebrew is still set up for x86.

At one point it insisted that I needed to switch to the Silicon version, but that caused many problems. So I reverted (thought I don't recall the exact steps). Bottom line: my homebrew is still x86 and still installs to `usr/local`.

**Comment by cbjeukendrup** [comment]
Indeed I use the arm64 and x86 HomeBrew in parallel, but I found that I can actually reproduce it with the arm64 version just as well; but only when compiling on the command line. 

The problem seems `libsndfile`. In `SetupSndFile.cmake`, `${SNDFILE_INCDIR}` is `/usr/local/include` or `/opt/homebrew/include`. So that's where it comes from.

Now we need to try to find out why this does happen on the command line, and not in Qt Creator. I believe Qt Creator doesn't load `.zprofile` and related files, so I think it doesn't have the HomeBrew stuff in its $PATH when it runs CMake. This probably leads to a different route being taken inside `SetupSndFile.cmake`. 

I don't have time to look into this further at the moment (struggling with a too long TO DO list) but if you want to investigate this yourself, then that is where to start looking.

**Comment by rpatters1** [comment]
Whoops, I should have mentioned it was the command-line build. I'll look at it when I get a mo. My own todo list is more than zero now. :)

**Comment by cbjeukendrup** [comment]
Update: it doesn't have to do with command line vs Qt Creator. The reason that it didn't happen for me in Qt Creator was that in Qt Creator I had some CMake options set because of which I was not using HomeBrew libsndfile but another one. Working on a fix.
