### ISSUE TITLE
Lyric lines with multiple dashes have lost at least one

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#24621]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

Lyrics containing multi-hyphen lines now start further from the syllables, making them more difficult to follow in a sight-reading situation.

1. Create a score in MS 4.3.2 with enough notes to trigger multiple dashes in the lyrics line.
2. Add a lyric on the first note, then press hyphen (`-`) until the last note and enter a final syllable, to generate a multi-dash line.
3. Save the score and open in 4.4 to compare.

### Supporting files, videos and screenshots

Minimal test case:

[Reducing hyphens.zip](https://github.com/user-attachments/files/16945989/Reducing.hyphens.zip)

From an actual score:

![Reducing hyphens](https://github.com/user-attachments/assets/2dcfae02-f54a-4455-b5b0-ea81c7953c44)

In this comparison between 4.1.1 and 4.4.1 (though I've checked the versions since, and all up to 4.3.2 show the same behaviour as 4.1.1) the space between the lyric syllables has actually increased slightly due to other spacing changes to the layout algorithm, but the 4.4 series only puts two dashes while earlier versions manage three.

In this extract, the file has the hyphen spacing set to 7sp, and has been opened in each version with no other changes then exported to PDF.

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.4.1-242490810, revision: github-musescore-musescore-0b3dd00

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64

### Additional context

I noticed this in an 80-page score, and going through it page by page, all instances of multi-dash lyrics have lost one and now start further from the syllables they link. On Discord, @oktophonie didn't recall a change to do this, and thought it could possibly be inadvertent with other changes in 4.4.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
What seems to be the case is that the max dash gap is honored correctly, but unlike previous releases, that max gap is also applied to the distance from the syllable itself to the first dash (and same from last dash to second syllable).  Prior to 4.4, the algorithm appeared to use only around half the max dash gap between the first syllable and the first dash (and same for last dash and second syllable).  The change in the number of dashes appoears to be just a side effect of the change in the size of the first & last gaps.

I have no insight into which is more "correct" or whether the change was deliberate or not, though.  Subjectively I like the 4.3.2 version better, and a spot check of published scores suggests it's more common.

**Comment by mike-spa** [comment]
I can confirm that @MarcSabatella is correct in this case. There is nothing wrong with the 4.4 layout: it honors the maximum dash distance (which is 16sp by default), and the dashes are equally spaced. Honestly I just assumed that that's how they're supposed to be when I rewrote this code for 4.4.
The old version seemed to have an implicit additional rule that the first and last gap should be half the length of the others, which indeed results in one more dash being drawn. 
One version isn't more correct than the other (incidentally, the current version is also what SCORE does), but for now we'll revert to the old version, just for the sake of continuity. We may expose a style option for this at a later point.

**Comment by iainhallam** [comment]
Thanks for that.

Dorico, for instance, seems to expose controls for spacing between dashes (same as MuseScore) plus the minimum spacing between lyric and dash as a separate value, then fits in as many dashes and spaces as it can between syllables, not placing any dash closer than the user's preference: https://forums.steinberg.net/t/please-explain-hyphen-spacing-controls/153132.

A style option for syllable-dash spacing in addition to dash-dash spacing would be a welcome addition. Would you like me to open a feature request?
