### ISSUE TITLE
col ottava lines

### ISSUE THREAD

**Issue by mkj42** [musescore/MuseScore#24652]
### Your idea

It would be great to have functional _col ottava_ lines, 8 and 15, above and below.
They indicate to play as written, plus the addition of pitches an octave or two above or below.
They can be faked visually, but having a fully functional line would be even better.

![col ottava](https://github.com/user-attachments/assets/e13a3788-d2c5-4004-bad6-c72c309c7e02)

### Problem to be solved

These come up regularly in printed music.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Dima-S-Jr** [comment]
Please note that the Italian term _coll’ ottava_ translates as "with octave", i.e. either with octave _8va bassa_ or _8va alta_. This is the first time I've heard of _coll’ ottava_ being used to refer to a double octave (_15ma_). 
If there is room, it is always better to write out the octave pitches. However, in cases where there is not enough free room, it is indeed more appropriate to resort to shortening using the _coll’ ottava_ indication.
After all, the request for such an indication has already been raised (see #17015), so I think this is another duplicate.

**Comment by oktophonie** [comment]
- [ ]

**Comment by mkj42** [comment]
Sorry I missed the duplicate feature request.
I did search, but for 'col ottava', not 'coll' 8va'.
