### ISSUE TITLE
cmd() does not work anymore in plugins

### ISSUE THREAD

**Issue by dEtzinger** [musescore/MuseScore#24673]
### Issue type

Other type of issue

### Description with steps to reproduce

Using cmd in your plugins used to work. In my case cmd("select-all") does not work anymore with the current version.

### Supporting files, videos and screenshots

```qml
import QtQuick 2.2
import QtQuick.Controls 2.2
import MuseScore 3.0


MuseScore {
      version: "1.0"
      description: "Shows cmd function does not work"
      title: "BugDisplay"
      pluginType: "dialog"

      requiresScore: true

      width: 800
      height: 400

      function readScore() {
            cmd("select-all");
      }

      Item {
            id:window

            anchors.fill: parent

            Label {
                  id: textLabel
                  text: "Plugin used to show bug";
                  anchors.left: window.left
                  anchors.top: window.top
                  anchors.leftMargin: 10
                  anchors.topMargin: 10
            }
            Button {
                  id: readAllElementsButton
                  text: "Select All"
                  onClicked: readScore()
                  anchors.left: window.left
                  anchors.top: textLabel.top
                  anchors.leftMargin: 10
                  anchors.topMargin: 30
            }
      }
}
```

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
It seems that the problem is not in the plugin API, but in MuseScore itself. When a plugin's window is focused, the UI context is `UiCtxUnknown`, which doesn't match with `UiCtxNotationOpened` which is the context of `select-all`. This probably applies to many actions.

**Comment by bkunda** [comment]
@igorkorsukov can you pls take a look at this?

**Comment by yonah-ag** [comment]
This is still a problem.
See:
https://musescore.org/en/node/381695
https://musescore.org/en/node/380201
https://musescore.org/en/node/372762

**Comment by slimvince** [comment]
Still broken as of MS 4.7 for `form`-type extensions (apiversion=2). This is a distinct case from the original report's apiversion=1 dialog plugin.

I also confirmed the failure on a local build of MuseScore master that includes PR #24887 and all subsequent commits to `src/context/internal/uicontextresolver.cpp` up to `4fa4e6183c` (latest as of May 2026). I am fully up to date with upstream — this is not a case of a fix not yet merged.

**Reproduction context**

An apiversion=2 form-extension (`"type": "form"` in manifest.json) with a valid score open. When the extension dialog has focus, calling `api.engraving.cmd()` for any action registered under the default `isNotationPage` predicate is silently dropped.

Log evidence:

    ActionsDispatcher::doDispatch | no one can handle the action: add-slur
    ActionsDispatcher::doDispatch | no one can handle the action: add-8va

**The intended fix is present but insufficient**

Commit `48aa4949d8` (added resolving context for dialogs) appears to be the explicit attempt to fix this case. Its logic: form-extension dialogs fall through to `UiCtxUnknown`, then PR #24887's `match()` special case fires, `isNotationPage()` returns true, and `cmd()` dispatches. The commit is in my tree and the special case is reachable — but it does not fire in practice.

One candidate for the regression: commit `9c44110595` (optimize currentUiContext()) introduced caching. `currentUiContext()` now returns a cached `m_currentUiContext` that is only refreshed via signals. A subsequent commit `38130460e4` removed several signal subscriptions as "no longer affecting" the resolved context. If the cache holds a stale `UiCtxUnknown` at dispatch time and no signal has triggered a refresh, the special case in `match()` is never reached. I was not able to confirm this from static reading alone.

**An asymmetry that may help narrow the fix**

A sibling `macros`-type action in the same composite extension successfully dispatches `cmd("add-slur")` against the same selection. The macros action runs without pushing a UI window — when triggered by a toolbar button click, the main window regains focus before the handler fires, causing `resolveCurrentUiContext()` to return `UiCtxProjectOpened`. This confirms the dispatcher and `NotationActionController` are healthy. The failure is specific to the form-extension dialog holding focus.

**Scope — affected actions**

Approximately 63 actions registered in `NotationActionController` use the default `isNotationPage` predicate and fail from a form-extension context. A sample by category:

Spanners: add-slur, add-8va, add-8vb, tie, chord-tie, lv, hammer-on-pull-off, add-noteline
Score structure: time-delete, append-measure, insert-measure, split-measure, join-measures
Systems: apply-system-lock, toggle-system-lock, move-measure-to-prev/next-system
Pitch / style: concert-pitch, transpose, pitch-spell, edit-style, staff-properties
Ornaments: add-turn, add-turn-inverted, add-brackets, add-parentheses, add-braces
Selection: notation-select-all, notation-select-section

Confirmed working (uses `noteOrRestSelected` predicate, not `isNotationPage`): add-hairpin.

**What a fix would need to cover**

`resolveCurrentUiContext()` should return `UiCtxProjectOpened` (or a value that satisfies `isNotationPage()`) when a form-extension dialog is the active window and a notation is loaded — not `UiCtxUnknown`. Commit `48aa4949d8` was designed to achieve this via `match()` but is not reliably doing so. The caching layer in `9c44110595` is a likely interaction point worth examining.

**Comment by FrancRos31** [comment]
@slimvince If no one reopens the ticket in a few days, I think it will be no problem to open a new one.
