### ISSUE TITLE
Changing tempo in playback panel moves playback position

### ISSUE THREAD

**Issue by ThePython10110** [musescore/MuseScore#24682]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

The tempo slider in the playback panel affects the playback position... Increasing the tempo moves forward and decreasing it moves backward. This slider should only affect the tempo.

1. Have a score that is playing
2. Change the tempo with the slider in the playback panel.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/7ca9a435-11ef-401c-ab52-18f8b9ecc55a

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11, Windows 10, Linux...

### Additional context

This has always been an issue in MS4, as far as I know. I just somehow never made an issue for it.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
Closing as this seems to be covered in https://github.com/musescore/MuseScore/issues/16084
