### ISSUE TITLE
Screen freezes on YouTube

### ISSUE THREAD

**Issue by mpdst** [musescore/MuseScore#24697]
### Issue type

Crash or freeze

### Description with steps to reproduce

After the 4.4 update, when I send the sheet music to YouTube, the sound plays normally, but the screen freezes. This issue has not been improved even after the 4.4.1 update. Please resolve this issue.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/e506b67a-6924-47f4-a952-a555a9bf4bff

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 10 home

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Eism** [comment]
Thank you for reporting!
We already fixed it in #24614. The following patch (4.4.2) will solve your problem

**Comment by DmitryArefiev** [comment]
Tested on **4.4.2** RC build, Win10. **All fine** on my side
