### ISSUE TITLE
[Engraving] Make ottava bassa written as "8vb" instead of "8va"

### ISSUE THREAD

**Issue by Ysabelle12** [musescore/MuseScore#24707]
### Your idea

Most notation software writes ottava bassa as "8vb." MuseScore, however, uses "8va" for both directions. It would be easier to read if it were written as "8vb," since most beginner books (e.g., Alfred Lesson Book) use that notation. This should be fairly simple to implement, as it's just a matter of changing the text.
Or at least an option to change it to "8vb"

### Problem to be solved

![image](https://github.com/user-attachments/assets/4fd67519-b5e3-470c-86b8-d05713fc7cbe)
Currently you can see it's written as 8va on the bassa side.

In contrast to software like Sibelius:
![image](https://github.com/user-attachments/assets/49c4aa30-0999-4a51-aa55-482690ee4ac8)
Where it's written as 8vb

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bluebear94** [comment]
Also add a style setting for “8vb” vs. “8ba” vs. “8va bassa”.

**Comment by MarcSabatella** [comment]
You already can change the text, in the Properties panel.  There is kind of a religious debate about the 8/8va/8vb thing so there is no pleasing everyone with defaults, but that's why options exist already.

For more help learning to use MuseScore, please ask on the official support forum at musescore.org

**Comment by Jojo-Schmitz** [comment]
A common misconception, the va is t italisn for th, otta**va** 8va -> 8th. Whether it is abobe of below (allta/bassa) can easily get determionined by ´wehner it is notated above of below staff
But still MuseScore does provide an 8vb too
