### ISSUE TITLE
Acknowledgment Button not working

### ISSUE THREAD

**Issue by pankaj-bind** [musescore/MuseScore#24700]
### Issue type

Other type of issue

### Description with steps to reproduce

1) Go to setting
2) Scroll down to end
3) About section
4) Acknowledgment button

### Supporting files, videos and screenshots

![{A15913BF-29B6-4822-92AA-0E3ACB1489AE}](https://github.com/user-attachments/assets/9d66c6a7-5aa4-4cbc-8507-9067071205e9)

### What is the latest version of MuseScore Studio where this issue is present?

Version: 20.19.1378 (x64)

### Regression

Choose option...

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DominicMaas** [comment]
Can confirm that this 404s

**Comment by bkunda** [comment]
Closing this issue needs to be fixed by the Muse Hub team.
