### ISSUE TITLE
Feature Request: Filter for Genuine Email while sign up

### ISSUE THREAD

**Issue by pankaj-bind** [musescore/MuseScore#24701]
### Your idea

I have seen that I can create a new account using a temporary or you can say disposable email. These temporary accounts take unnecessary space in our database.
Here a is a popular temporary email website https://temp-mail.org/en/ you can test.

### Problem to be solved

I can develop a feature which will checks if the email is permanent or temporary while sign up. If it found disposable a message will popup showing such emails are not allowed and if its permanent email so let them go, it will save your database memory, and you will have a community of genuine people.

I will use this https://debounce.io/free-disposable-check-api/ api to correct this issue.

### Prior art

I have seen this kind of feature and have also developed it in "GirlScript Summer of Code"

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
We need some more info here. Could you clarify whether this is about Muse Hub?
If so, please contact the customer support team for Muse Hub directly (either from within the Hub app, or via [this link](https://support.musehub.com/hc/en-gb/requests/new)).

**Comment by pankaj-bind** [comment]
Yes it is

**Comment by zacjansheski** [comment]
Closing, please report to Muse Hub
