### ISSUE TITLE
Voice too long corruption

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#24702]
### Issue type

File corruption

### Description with steps to reproduce

Since 4.4.0 it is possible to make voice 2 longer than actual measure size. See video
During investigation for [this report ](https://musescore.org/en/node/368654) I found one way to do this. Although I don’t know what exactly caused the corruption in that score.
This is a regression since 4.4.0. 
Can't reproduce in 4.3.2

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/19666a81-2d31-4194-abed-d608058f551d

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.5.0-242560303, revision: github-musescore-musescore-ac76040

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
Possibly has something to do with https://github.com/musescore/MuseScore/pull/23911. 

Expected behaviour is probably to shorten the existing note when entering a new note 'in the middle of it'; just like how following notes are sometimes shortened at the front when increasing the duration of a previous note.

**Comment by oktophonie** [comment]
@mercuree Thanks for this report; I managed to encounter this myself yesterday but then wasn't able to work out exactly the steps to reproduce it.
