### ISSUE TITLE
Incorrect fingering rendering with cross-staff notes

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#24718]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

This is only observed for cross-staff notes. See video for details
[Report](https://musescore.org/en/node/368716) and [score file](https://musescore.org/sites/musescore.org/files/2024-09/majorarpeggios.mscz), but can be reproduced from scratch.
Regression in MS 4.4.0

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/a52d428f-3c3b-45c6-abb0-b5412f07ac5c

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.5.0-242570304, revision: github-musescore-musescore-d7a9ce4

### Regression

Yes, this used to work in MuseScore 4.3

### Operating system

windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
@zacjansheski pls check actual regression status
