### ISSUE TITLE
"Find" should scroll found measure/rehearsal number into view regardless of "pan automatically enabled" option

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#24715]
### Your idea

When using Ctrl+F / "Find" to locate a measure or rehearsal number etc., it should always scroll into view. Currently it doesn't if the option "pan score automatically" is turned off in the playback toolbar.  Should also apply to e.g., CTRL+home/end (these keys without "CTRL" scroll as expected).

### Problem to be solved

Current behaviour forced me to look at the code to try to work out why it wasn't scrolling the measure into view.

### Additional context

Normally I'd just log this as a bug, but apparently that's no longer the P.C. thing to do unless you have solid proof the software is not behaving the way it's been designed to.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by SteveBlower** [comment]
This is a duplicate if the more general  https://github.com/musescore/MuseScore/issues/20512 I think.

**Comment by wizofaus** [comment]
Ah it is indeed, will close this
