### ISSUE TITLE
Spurious stem on whole note

### ISSUE THREAD

**Issue by amoneti** [musescore/MuseScore#24717]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

To follow up on [my support thread](https://musescore.org/en/node/368710#comment-1258244):

1. I created the simple file StemTest.mscz shown in figure 1
2. I applied the "Display note values across measure boundaries ...", see figure 2, which added a stem on the whole note
3. I removed that option, see figure 3, which left a half note without a stem

This is in MS4.4.1; as cadiz1 indicated in the support thread, this did not occur in 4.3.2 (and I confirm).

Best, 
Andrea

### Supporting files, videos and screenshots

[StemTest.mscz.zip](https://github.com/user-attachments/files/17002246/StemTest.mscz.zip)

<img width="802" alt="Screenshot-1" src="https://github.com/user-attachments/assets/954d590f-2a28-4d08-927f-05c791c16a17">
<img width="794" alt="Screenshot-2" src="https://github.com/user-attachments/assets/d7997cef-7666-4eee-b17f-5998aaddcbdc">
<img width="792" alt="Screenshot-3" src="https://github.com/user-attachments/assets/29bdece8-d76a-4b1c-b865-0f79f14ca8a9">

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

MS 4.4.1; Mac OS 14.6

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cadiz2** [comment]
See what happens when you use the **“Display note values across measure boundaries, Experimental, early music” feature** in the Format/Style menu in **version 4.3.2 vs. version 4.4** (and therefore 4.4.1). 

![Video stems1](https://github.com/user-attachments/assets/9bdb2a48-bd66-4e3d-9496-f3d62de9a854)
