### ISSUE TITLE
Crash when dragging slur

### ISSUE THREAD

**Issue by Ysabelle12** [musescore/MuseScore#24726]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Create a score
2. Add notes in the measure
3. Add the slur
4. Move the slur

Note this also happens in the latest nightly.. It might've worked in MS 4.3 But I am not able to check. And I'm not sure if this only affects Windows, not macOS

**EDIT**
This worked on MS 4.3.2 

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/d880f0e8-4a96-4fc6-ba3c-6d737c31551b

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore 4.4.1

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Ysabelle12** [comment]
Now imagine you're navigating through your score while writing your piece, and it crashes. That's one scenario I could think of.

**Comment by cbjeukendrup** [comment]
Refinement to the reproduction steps: as shown in the video, it is crucial to click the slur again, so that no "grip handle" is selected, before dragging it.

**Comment by wizofaus** [comment]
Can't reproduce at all with 4.4.0 or local development build, but indeed I can't seem to find a way to select a slur so no grip handle is selected, even though I did work on something related to that recently (Home key resetting the grip handle position) and was able to do so then.

**Comment by wizofaus** [comment]
Ok, just tried again with development build and reproduced:

![image](https://github.com/user-attachments/assets/92bf552f-4d11-40d5-9dfa-55a951967b5c)

**Comment by wizofaus** [comment]
@mike-spa this appears to be due to changes you'd made around how slur dragging worked, though the actual problem (the use of `ups(g).off += ed.delta;` even when g = NO_GRIP = -1, which is corrupting the m_spanner field) has been there a long time, even if it was previously in SlurTieSegment::editDrag( ) - but now in SlurSegment::editDrag()).  Happy to try to fix (as I had changed some of this code recently to fix the behaviour of the Home key), but if you'd prefer to have a look yourself that's fine.
