### ISSUE TITLE
[dev branch] Commit 18e67fafe1 causes assert in dev environment.

### ISSUE THREAD

**Issue by rpatters1** [musescore/MuseScore#24720]
### Issue type

Crash or freeze

### Description with steps to reproduce

Pull any commit in the master branch on or after commit 18e67fafe1, which was merged yesterday at 5:45 am CDT.

- Run Qt Creator to debug MuseScore
- Escape out of any dialog boxes to a blank workspace
- Open a new file (I used the Treble Clef template)
- MuseScore immediately crashes.

Below is part of the Qt debug window that shows the assert where it crashes.

### Supporting files, videos and screenshots

<img width="873" alt="Screen Shot 2024-09-13 at 6 12 38 PM" src="https://github.com/user-attachments/assets/fa5b404f-fe7d-4819-a3a4-aaa83d7b6059">

### What is the latest version of MuseScore Studio where this issue is present?

master branch starting with 18e67fafe1

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

macOS 12.7.6

### Additional context

~~As far as I can tell, this commit was merged directly into the master branch without a Pull Request. I am astonished that a project of this complexity, with so many contributors, does not have an ironclad policy requiring PRs for the master branch. I would encourage that we consider making this an ironclad policy. I'm fairly certain GitHub can enforce it.~~

EDIT: See comments below.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by RobFog** [comment]
That was @igorkorsukov's change.

**Comment by sammik** [comment]
#24688

**Comment by rpatters1** [comment]
The commit history does not show a separate PR merge commit, which is why I was misled. But I think that whatever mechanism we are using should *always* show a separate PR merge commit.

**Comment by cbjeukendrup** [comment]
The commit was apparently merged by squashing or rebasing. 
Regardless of the mechanism being used: when you open the commit on GitHub (can be done easily using the `gh` CLI tool, `gh browse 18e67fafe1bb77310e5a8ef8bd2147a8f59548e2`), you see a link to the PR:
<img width="333" alt="Scherm­afbeelding 2024-09-14 om 18 00 49" src="https://github.com/user-attachments/assets/33797375-8aab-45e6-a799-6a192fb7216b">

**Comment by cbjeukendrup** [comment]
My temporary fix to be able to do stuff:
<img width="625" alt="Scherm­afbeelding 2024-09-14 om 18 08 39" src="https://github.com/user-attachments/assets/de5ea97e-a58d-4e80-9437-0ec70db8acfc">
`std::max<float>(20.0 * std::log10(std::abs(v)), -FLT_MAX);`
