### ISSUE TITLE
Musescore 4.4 resets all hairpins to default height

### ISSUE THREAD

**Issue by RhinoHaggis** [musescore/MuseScore#24737]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. add a hairpin
2. adjust height
3.  save file and close
4. reopen
The height of the hairpin will be reset to default.  Go about it in any order: import a pre-existing score into 4.4, and the hairpin heights will be gone.  Don't know if, after saving in 4.4,  the information is still there and not being retrieved, or if saving in 4.4 erases it.

### Supporting files, videos and screenshots

Writing a brief snippet of music and adding some hairpins:
![hairpin 1](https://github.com/user-attachments/assets/8f8b1b97-a909-4bd3-9eff-ab8accab0396)
Save file, close and reopen:
![hairpin 2](https://github.com/user-attachments/assets/020fc282-2c48-42df-8232-dc8c7254411d)

File is here, but it happens to all hairpins
[hairpin height and tuplet drag test.mscz.zip](https://github.com/user-attachments/files/17006324/hairpin.height.and.tuplet.drag.test.mscz.zip)

Looks cosmetic here, but in a dense scores with diagonal hairpins, things get pretty hairy.

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS 12.6.6

### Additional context

Verified behavior with another user in forums.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
Turns out it's only when the hairpin height is adjusted by dragging the hairpin handle that the change is not saved! (and it's been like that since at least 3.6) If you change it via the Properties panel, it is. #classicmusescore

**Comment by RhinoHaggis** [comment]
Hang on, let's slow down here.  I'm absolutely certain that -for me- this is not true.  I always change hairpin height via the properties panel, because it allows me to set a specific height, rather than an approximate one.  I don't want hand-set hairpins to have random heights in relation to one another.  This is not a "maybe I forgot" situation.  I just finished a 150-page score for upload to IMSLP, and -so that the final edits could be completed and I could move on- I went through the entire score one block at a time, set the height of hairpins in Properties, and exported to .pdf before closing.  I adjusted a total of 0 by dragging the height, and every single one was reset on reopen.

**Comment by RhinoHaggis** [comment]
It's not as obvious in the image of the sample file above, because the last and first hairpins are not adjacent and not aligned, and- since i just slapped them on- I didn't hand-align them.  But you can verify by scrolling to the edge of the window that the smaller -upper- hairpins align perfectly at their open ends.  That's because they are exactly the same height, as set in the properties panel.

**Comment by oktophonie** [comment]
Yes, in 4.4 changes made via properties would also not be saved. See https://github.com/musescore/MuseScore/pull/24771#issue-2530960397

**Comment by RhinoHaggis** [comment]
Ahhhhhhhhh I see. So in fact for me this is why it works in previous versions but not 4.4.  I always use properties and therefore never encountered it until now.  Got it.

**Comment by RhinoHaggis** [comment]
Still adjusting to GitHub. Never been on a bug reporting page they also gave access to the code resolution. Clicked on the 24771 comment above thinking I was about to see a duplicate report, and I couldn’t  understand how I missed it😅
