### ISSUE TITLE
Dragged tuplet numbers go bananas

### ISSUE THREAD

**Issue by RhinoHaggis** [musescore/MuseScore#24738]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

**Current behavior:** Dragged tuplet numbers fly uncontrollably around the score, and the movements cannot be undone.

1. Create several tuplets in a passage.
2. Grab a tuplet number and drag it to a new position.
     [iteration:]
3. if this behaves normally, flip the tuplet label with "x", and try again.
4. If this STILL behaves normally, repeat 2. and 3. with the other tuplet labels
     [resume:]
5. Tuplet wil fly around the score, collide with staves.
6.  Try Undo.  [some or all parts of the movement cannot be undone]

**Expected behavior:**  Tuplet numbers freely draggable with no phantom impingement.

Several behaviors have regressed.  In previous versions, when "brackets" are turned off, tuplet numbers can be dragged freely and naturally into position.  They do not collide, and there are no phantom brackets lumbering around.

Thus the presence of phantom brackets restricting the free placement of the numbers, the unpredictability of drag, and the failure of Undo are all regressions.

### Supporting files, videos and screenshots

Test file:
[hairpin height and tuplet drag test.mscz.zip](https://github.com/user-attachments/files/17006493/hairpin.height.and.tuplet.drag.test.mscz.zip)

On the newly opened file, I flip the first tuplet with "x", and then attempt to drag it:

https://github.com/user-attachments/assets/00afada9-bb5f-4e1a-9ae5-d7e178c82e51

Wheeeeeeeeeeeeeeeeeee!

At the end, I attempt to Undo this drag, and the tuplet number jumps down the page, dragging the staff with it.

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1-242490810, revision: 0b3dd00

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS 12.6.6

### Additional context

Confirmed behavior with another user in forums.

I have not been able to pin down the exact context that leads to the behavior, but I have always been able to reproduce it after a very small number of tries.

Cannot emphasize enough that --whatever the planned purpose of introducing the brackets-- the "new way" (absent any bugs) of moving numbers about by shifting invisible bracket is extremely time consuming.  In a piece with regular running triplets and a hand-set engraving, the change from drag-to-position to slowly-nudge-into-position-by-toggling-back-and-forth-with-the-endpoints is almost unmanageably burdensome. 

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
Regression occured between 4.4.0 and 4.4.1

Also reminds me of https://github.com/musescore/MuseScore/issues/24608

**Comment by Eism** [comment]
@zacjansheski please retest it (fixed https://github.com/musescore/MuseScore/issues/24608)

**Comment by zacjansheski** [comment]
Fixed by https://github.com/musescore/MuseScore/issues/24608
