### ISSUE TITLE
Not all instruments play from main score.  Subset of instruments is random every time I press play.

### ISSUE THREAD

**Issue by davidlbangs** [musescore/MuseScore#24743]
### Issue type

General playback bug

### Description with steps to reproduce

On MuseScore 4.4.1, and all prior versions of MuseScore 4 that I have tried, playback is unreliable on the master score for all of my multi-instrument arrangements.  If these files have anything in common, it would be that they were originally MuseScore 3 files, though I'm not sure if this matters.

If I open a part, such as piano or clarinet, these individual files play fine. 

If I open a file and play the master score, it may work perfectly, or may be totally silent, or a subset of the instruments will play.  The scores usually only have piano and a woodwind instrument.  When playing, I may hear the piano without its chords, or the piano without the other instrument, or just the other instrument.

If I stop playback, move the cursor, and play again, I get another assortment of instruments.
I keep the mixer open so I can try to troubleshoot. However, the mixer settings are not wrong.

I have tried on a Lenovo Windows 11 laptop running Windows 23H2, a brand new MSI laptop with Intel Core Ultra 9 running the release candidate of Windows 24H2, and a Mac M2 Mini running MacOS 14, and very recently MacOS 15 release candidate, however, it doesn't matter.  The same behavior happens on Windows and Mac.

I have tried with both MuseSounds and MSBasic sounds.  Doesn't matter. 
I have tried on laptops with internal sound, and also an external USB mixer.
On Mac M2 Mini, speakers connected to its audio out jack. 
Regardless of computer or OS, or audio configuration, I will experience omitted instruments or silence at times if I start and stop playback of any score.

MuseScore 3.0 playback is reliable in all these cases.

### Supporting files, videos and screenshots

Video file:
https://github.com/user-attachments/assets/9cdd5580-7000-47c9-bc6c-f5d538fed621
I would upload the score, but mscz files can't be uploaded.

The video starts on the piano part, which plays correctly.  I don't have problems playing individual part sheets.
Then it switches to the Bb clarinet, which plays correctly. Af first there are only chords.
Then it switches to the master score, which plays correctly at first. You can hear the piano, its chords and the clarinet together.
Stop the playback.  Click on a different measure and play again. NOTE No Clarinet sound is played.
Stop the playback.  Jump to the beginning and play.  NOTE:  No piano is played.  Video stopped.

If I open the MuseScore 3 version of this file in MuseScore 3, there are never omitted instruments.
If I open this using MuseScore 4.4 on Mac, I get the same bug as on Windows.

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1.242490810

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11 23H@ and 24H2, MacOS 17 and 18 release candidate

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
It's not really clear from the video, but if this just a matter of your having selecting a range and thus MuseScore is playing only the selected instruments?  That has indeed been a feature since 4.0 first released.  If you want to hear all instruments, don't start by selecting a range - select a single element, or if you do select a range, just press Esc to clear it.

If that's not it, please attach your score (ZIP it first so it's allowed by GitHub) and give precise steps to reproduce the problem.

**Comment by davidlbangs** [comment]
Ok, that's actually it.  However, I'm confused about how to start playing from someplace.  Do you really have to select over all the instruments in order to play form a certain point?  That can be dragging down over the whole page to get all the parts.

**Comment by MarcSabatella** [comment]
No, as I said, either select a single element instead of a range, or press Esc after selecting a range.  Either way not plays the full score from that point.

**Comment by davidlbangs** [comment]
Thank you.  I took that to mean it would unselect and thus start from the beginning.  I see what you mean, but it would be great of the line cursor was there to know where playback would start.  I'm fine now, that is just a suggestion.
