### ISSUE TITLE
Flipped slurs on inner voice + move to upper/lower staff

### ISSUE THREAD

**Issue by RhinoHaggis** [musescore/MuseScore#24740]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

Not sure if these count as engraving, UI or corruption.

**Current behavior:** The slurs of an inner voice shifted to upper or lower staff are incorrectly reversed.

Steps:
1. In a previous version, create a grand staff, and some two voice music on the upper staff.  Add slurs to the second voice 
2. Shift voice 2 to the lower staff and place the slurs where you want them.  Save the file.
3. Open file in 4.4.  Wherever the second voice goes to the lower staff, the direction of the slurs (above/below) will be flipped.

**Expected behavior** slurs should face the direction defined in the source file.

### Supporting files, videos and screenshots

File created in 4.2: [Slur flip test.mscz.zip](https://github.com/user-attachments/files/17007134/Slur.flip.test.mscz.zip)

Looks like this: ![Slur flip original](https://github.com/user-attachments/assets/7c3e0b98-7daf-4e1c-aa2e-f7e4da78a7a7)
Same file, opened in 4.4:
![slur flip 4 4](https://github.com/user-attachments/assets/e48ec84d-f025-4f03-8da5-e83f073c9d99)

The melody line is Voice 2 of the upper staff throughout.  All other voices are cue size for clarity.  Whenever this voice is moved to the lower staff, the slurs are flipped by 4.4. 

### What is the latest version of MuseScore Studio where this issue is present?

4.4.1-242490810, revision: 0b3dd00

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 112.6.6

### Additional context

If instead Voice 1  is placed on the lower staff, the slurs are not affected.  I did not verify the behavior for staff 2 voices shifted up, or for voices 3,4.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
Actually it looks like MuseScore _is_ honouring what's in the file: the slurs are set to auto direction (not explicitly 'above') so MuseScore determines which side to put them on based on its own logic.

However, it does seem that this logic has changed between 4.3 and 4.4. I forget when or why now (looking into it) but to be honest it seems more consistent now: voice 2 and 4 slurs go below, voice 1 and 3 slurs go above*, regardless of stem direction. That's how it works on a single stave:
![image](https://github.com/user-attachments/assets/8dd13f2f-6be9-44c0-a4cf-6cbca3fa4ce0)

Before 4.4, this behaviour was different in a cross-stave situation: the slurs would instead go at the stem side, i.e. if you flipped the notes the slur would also flip:
![image](https://github.com/user-attachments/assets/b88de32b-78fd-4bd2-a129-833412314a99)
[that's me just cross-staving the whole bar]

In 4.4 this no longer happens:
![image](https://github.com/user-attachments/assets/09177ce2-d4f8-4002-9733-a5fad38e328a)
To be honest, it feels a bit more consistent that way to me. The cross-stave version behaves just like the non-cross-stave version.

(This obviously raises the question of whether cross-stave voices should automatically flip when they move. In most cases that's probably what you want, so we should implement it at least as an option, but given that currently they don't it makes sense for me for everything to behave in as neutral a way as possible, so you have to explicitly specify everything manually, rather than a mixture of some manual and some automatic behaviour.)

*) _yes, voice 1 slurs go above or below depending on stem direction, if that is the only voice_

**Comment by RhinoHaggis** [comment]
The problem for me is that I just want it to work one way between versions.  If there is a compelling argument for it working one particular way, and that is different from current, then ok.  But it seems to me there are conflicting rule sets in play here.

1. It seems to me that if I have turned off "auto-place" and hand shaped a slur into position on a particular side, - or even if auto place is still on and I hand place a slur - it is not "6 of one, half a dozen of the other".  If I turn of auto-place, I want auto-place off.  If I put a slur in a particular position, I want it in that position.  This is pretty fundamental to being a user.  And musescore needs to go further in that direction.  I could untangle the vast majority of slur-garbage-on-recalculate if
  a) MuseScore never -EVER- turned auto place back on without my permisison and 
  b) instead of arbitrary offsets, I could tell it what I mean: "it's attached to this notehead not the articulation", "the far side of the notehead" , "in front of the stem" etc.

But all of this depends on musescore deciding once and for all which side of a note it thinks a slur belongs on.

2. As a pianist, I am suspicious of statements like "probably what you want most of the time". Much more likely is that the user who doesn't care, doesn't care.  Very simple cases -the only ones where "most times" logic actually work- will look fine either way.  And anyone who wants to change them, can flip them.  But in a complex score with multiple voices, the stem directions and slurring will always have to be managed by the user, and a change in default rule set is a nightmare.  The most work put in, the most work _undone_.

3. If the change of direction is intentional and is going to stay, then the course of action seems pretty obvious: Musescore must correctly determine slur direction when a file created in a previous version is opened, and _reproduce that direction_.  "Auto" or not should not even come in to it.  
a) Determine if a slur is affected by the new rule
b) If affected, then we already know "auto is on, so flip the user toggle on the auto direction.

Auto stays on, the slur appears on the correct side, and the change in behavior has no effect on older files.

**Comment by oktophonie** [comment]
If you want the slur above, set it to 'Above'. If you want it below, set it 'Below'.
If you want to abdicate responsibility for choosing, leave it at 'Auto'.
If you never want any aspect of automatic layout to change, don't ever upgrade to a new version.

Your point 3 is pretty utopian. That would mean we'd have to retain all the layout logic for every prior version in every new version, so we could reference it and apply according to the version of the file we're reading.

**Comment by RhinoHaggis** [comment]
I don't want the slur "above" or "below" as an absolute rule.  I want the automatic behavior.  Then when I need to massage a slur into place, I turn off auto-place.   Nor do I accept that it is the user's job to reverse-engineer the internal fallthrough logic of the app, in order to figure out for herself how to avoid their layout being changed from version to version.  I use the features of musescore in a logical and consistent way, based on the features made available and how they work. It would have taken an uncommon level of cynicism on my part to even fathom that I should have -this whole time- been turning auto-direction off because I might wake up one day and Musescore would have no idea what direction I had set things.  I set the direction using MuseScore's rules.  Whatever arrangement of auto and manual, is not, and should never be, the issue for the user.  Also, MuseScore is engraving software, and -like any other publishing/layout/engraving program- consistency across versions is not a minor concern.

For this particular issue, whether or not it is a bug depends -as we speak- on the personal preference of the developers.  If it's bug, it was a mistake and will be fixed.  If you decide it's not a bug, every musescore user who uses inner voices without turning auto-direction off will have to re-edit old scores. How could this significant effect on user experience be avoided?  By inserting -once- a perfectly definite, closed rule so simple that you could have written it in the time it took to write me that message.  Is this more burdensome than fixing it as a bug, which you would have been willing to do?  Necessary work, if you didn't mean it, but utopian to imagine you would do the work, if you meant the change?  The reason for me reporting it here- a change in behavior- is only relevant to you if the fix does not require you to include a version number in the code that you would write to fix it?  Surely not.  And this fix does not require keeping a working log of previous versions, the rule is closed.  You know right now where the change occurred, and therefore what version number to put a less than or equal sign next to, to make the transition to 4.4 seamless.   This seems like the obvious way to handle any changes to Musescore's default layout preferences that have a significant, easily avoidable effect on the transition between versions.
