### ISSUE TITLE
When you're playing any scores, the playing line disappears if you change to "Publish" screen

### ISSUE THREAD

**Issue by Haru00007** [musescore/MuseScore#24769]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

This bug is occurred if you change to "Publish" screen (Also "Publish" to "Score" screen) when you're playing scores.
Here is how to reproduce this issue:
1. Open any score
2. Click the play button or press the space key to play that score
3. Go to "Publish" screen when you're playing
4. You can see there is no playing line.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/fd6e5a4e-3078-4b1e-a356-877d16eaad96

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11 Home Edition

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
@zacjansheski pls confirm actual regression status
