### ISSUE TITLE
Timpani (musesounds) can play above HiB only when tremolo is attached

### ISSUE THREAD

**Issue by Haru00007** [musescore/MuseScore#24793]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

This bug occurs when you want to play HiB on Timpani (e.g. The Rite of Spring by Igor Stravinsky)

1. Create a new score, add Timpani
2. Add HiB, then playback this score
3. You cannot listen to HiB
4. After that, add tremolos on these HiB notes then playback this score
5. You can listen to HiB (roll)

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/a3b73667-c01d-4575-be18-6f33824345c0

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

I was unable to check

### Operating system

Windows 11 Home Edition

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by matthewreadbass** [comment]
Thanks for bringing this to our attention. As this is the MuseScore repo, I'm going to open a separate ticket in the Muse Sounds repo for this issue.

**Comment by Haru00007** [comment]
> Thanks for bringing this to our attention. As this is the MuseScore repo, I'm going to open a separate ticket in the Muse Sounds repo for this issue.

I see, thank you!
