### ISSUE TITLE
MuseScore Basic playback is glitchy after update to 4.4.2 (from 4.4)

### ISSUE THREAD

**Issue by rpatters1** [musescore/MuseScore#24799]
### Issue type

General playback bug

### Description with steps to reproduce

1. Open attached file
2. Hit play
3. Hear glitches

The glitches become increasingly prevalent the longer it plays.

This did not happen in 4.4. (I skipped the 4.4.1 update, so I don't know about it.) I am using the defaul MuseScore Basic playback option.

### Supporting files, videos and screenshots

[LaCucaracha-Patterson-BQ copy.zip](https://github.com/user-attachments/files/17045125/LaCucaracha-Patterson-BQ.copy.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 12.7.6

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by rpatters1** [comment]
Fooey, it suddenly stopped glitching. I don't know what changed. I was working and suddenly noticed it wasn't doing it any more. If this issue is not of interest, please close it.

**Comment by DmitryArefiev** [comment]
OK. If it will happen again please reopen and attach the diagnostics files (Menu>Diagnostic>Save diagnostic files)

Thanks!
