### ISSUE TITLE
Disabled "Show first" for bar numbers not working after section breaks in 4.4.2

### ISSUE THREAD

**Issue by MiguelVicenteGarcia** [musescore/MuseScore#24809]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

Make a section break
Disable "Show first" in Bar numbers. 
It should hide bar numbers at beginning of new section, but it does not 

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/71f99f61-4b68-4362-a2e9-fa35360f1ba8

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
Stems from https://musescore.org/en/node/368997, which also has a sample score
4.3.2 doesn't have that issue, 4.0.0 has.

**Comment by sammik** [comment]
I think, its my fault. Ill look at it.

**Comment by sammik** [comment]
#24817 done
section breaks on frames was actually the problem
