### ISSUE TITLE
Unable to extend Slur to the next system with Shift+Right

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#24803]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Add slur
2. Extend it to the next system with Shift+Right shortcut

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/2297d674-0a31-49e3-b1bf-e07886197b3c

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in **MuseScore 4.3.2**

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
See also https://github.com/musescore/MuseScore/issues/19956 - a more limited version of this has been a problem forever, but it's worse now indeed.

**Comment by bkunda** [comment]
I think this is a patch candidate, since it used to work in 4.3.2 (therefore broken from 4.4).

**Comment by DmitryArefiev** [comment]
Fixed in #24931
