### ISSUE TITLE
Constant Crashing

### ISSUE THREAD

**Issue by cornomoose** [musescore/MuseScore#24806]
### Issue type

Crash or freeze

### Description with steps to reproduce

Please help!

Musescore 4.4 and 4.4.1 constantly crash!! WHY?!?! I have lost a tremendous amount of work and have to move on to a different notation software. You have a good product, but it is not sustainable! 

I was just made aware of this site and have no pictures to provide. I have moved away from MuseScore for the moment. I need to finish the project asap, and I have lost a lot of time due to the constant crashes. I will come back to it in a week or so with a new project and send in all the data you need.

The biggest issue with 4.4 and 4.4.1 is it really, REALLY does not like working with XML files that have extra beats or rests in a bar. It often thinks the file is corrupt but allows me to work on it anyway. When fixing the additional beat/rest issue, it will crash at random times.

The latest crash happened when I was moving notes from one voice to another and/or deleting unnecessary notes in the same voice.

I attempted to upload the file I am working on, but I got the "We don't support that file type" error.

[MuseScore - Thille Score - Crash file.zip](https://github.com/user-attachments/files/17048213/MuseScore.-.Thille.Score.-.Crash.file.zip)

Jason

### Supporting files, videos and screenshots

Please help!

Musescore 4.4 and 4.4.1 constantly crash!! WHY?!?! I have lost a tremendous amount of work and have to move on to a different notation software. You have a good product, but it is not sustainable! 

I was just made aware of this site and have no pictures to provide. I have moved away from MuseScore for the moment. I need to finish the project asap, and I have lost a lot of time due to the constant crashes. I will come back to it in a week or so with a new project and send in all the data you need.

The biggest issue with 4.4 and 4.4.1 is it really, REALLY does not like working with XML files that have extra beats or rests in a bar. It often thinks the file is corrupt but allows me to work on it anyway. When fixing the additional beat/rest issue, it will crash at random times.

The latest crash happened when I was moving notes from one voice to another and/or deleting unnecessary notes in the same voice.

I attempted to upload the file I am working on, but I got the "We don't support that file type." error.

[MuseScore - Thille Score - Crash file.zip](https://github.com/user-attachments/files/17048308/MuseScore.-.Thille.Score.-.Crash.file.zip)

Jason

### What is the latest version of MuseScore Studio where this issue is present?

4.4 and 4.4.1

### Regression

I was unable to check

### Operating system

macOS 14.6.1 MacBook Pro M3 Max

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
First of all update to 4.4.**2**, then check again

**Comment by Jojo-Schmitz** [comment]
Then attach the score, 'hidden' in a ZIP file

**Comment by cornomoose** [comment]
Thanks for getting in touch! I did the update, but as stated earlier, I need to finish this project with different notation software. I'll come back to MuseScore where there is less "on the line."

I'll figure out the hidden score idea and try to upload it soon!

Thanks again!
Jason

**Comment by zacjansheski** [comment]
Closing as stale
