### ISSUE TITLE
Backward notehead with vanished stem.

### ISSUE THREAD

**Issue by RhinoHaggis** [musescore/MuseScore#24823]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

**Current behavior**
Under unclear circumstances nearby edits can cause noteheads to flip backward and stems to vanish.
(see attached video and file)

### Supporting files, videos and screenshots

editing some objects flips a block of noteheads, and the stems vanish... while editing other objects restores them:
https://github.com/user-attachments/assets/deb7ca00-ea87-4b71-9129-4516e2568d2a

In this file:
[vanished stems n reversed noteheads.mscz.zip](https://github.com/user-attachments/files/17067298/vanished.stems.n.reversed.noteheads.mscz.zip)

- Notes in red force the flip when moved,
- Notes in green restore flipped heads to normal when moved.
- grayed-out notes have no effect

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2-242570931, revision: 3130f97

### Regression

No

### Operating system

Mac OS 12.6

### Additional context

No bug in 4.2, 4.3.   Bug in 4.4.1 an 4.4.2 but not sure about 4.4.0.
So far every occurrence has been on notes with a hand-adjusted beam.   i will add information if I can work out more details.  So far this has been rare (three or four times in a couple hundred pages). That and the action-at-a-distance effect make it hard to see how to pin it down. 

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
A similar example was discussed elsewhere - Facebook or Reddit, I think - recently.  Here is the score:

[squirrely noteheads.mscz.zip](https://github.com/user-attachments/files/17067476/squirrely.noteheads.mscz.zip)

When you first load the score, you see this on the last measure of the second-to-last system:

![image](https://github.com/user-attachments/assets/541f1ae9-bb4e-4064-8384-6da41d1075d4)

After pretty much any edit that triggers a relayout of that system, it fixes itself:

![image](https://github.com/user-attachments/assets/c4f41eba-9e15-4c09-9b67-e482d4370477)

**Comment by MarcSabatella** [comment]
An interesting similarity here is that it's the second note of a six-note run, on the last measure of a system, with the beam edited to an unusually steep angle.

And in fact, armed with that observation, I can reproduce this from scratch.  Enter this just as you see it (including the adjustment t to the beam angle):

![image](https://github.com/user-attachments/assets/f3bf1c05-dacf-4dbd-af31-a083c3586c3a)

Save and reload, then you get this:

![image](https://github.com/user-attachments/assets/02d85ab3-f783-42cc-b03e-5170ab3f57c2)

**Comment by RhinoHaggis** [comment]
Sweet merciful Jesus a reproducible example!  I'm working on long scores right now and every time I cut them down to isolate the example, the behavior changes.  You should check out the attached file to this report.  More noteheads are affected, and the glitch can be turned on and off by nudging different notes on the page.
