### ISSUE TITLE
Musescore looks and works bad 

### ISSUE THREAD

**Issue by re0001** [musescore/MuseScore#24857]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

Hello everyone
I installed MuseScore and its interface looks bad. I run my other apps without problems.
I installed the software using Musi Hub and then only with the software installer.
I send the diagnostic file (created by the software) and a screenshot of the issue.

### Supporting files, videos and screenshots

![bad LOOK](https://github.com/user-attachments/assets/3af8c892-2b9d-4b1e-85af-2faa555dadd8)
[MuseScore Studio 4(diagnostic).zip](https://github.com/user-attachments/files/17084371/MuseScore.Studio.4.diagnostic.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Win 10 version 22h02

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
Hm, yet another Qt graphics problem. You could try if #24644 fixes it ([How to download test builds from pull requests](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests))

**Comment by re0001** [comment]
Thanks for comment.
I installed MuseScore 4.3 version and it is running ok.
Could I get a detrimental impact in other applications, switching to Qt 6.2.9. in order to use MuseScore 4.4.2 version ?

**Comment by cbjeukendrup** [comment]
And what happens when you click "Aceptar"? Normally, this error message should appear only in the log files rather than in the UI. The expected behaviour would be that MuseScore detects the message, then restarts itself with OpenGL instead of D3D11. Does that still happen when you click "Aceptar"?

**Comment by re0001** [comment]
After clicking "Aceptar", the programme closes.

**Comment by re0001** [comment]
Hello I downloaded  MuseScoreNightly-latest-4.4.3-x86_64-portable.exe  
I tested and the problem is no solved.  I got the same message "Failed to initialize graphic backend for  D3D11".
After clicking "Aceptar", the programme closes.

**Comment by re0001** [comment]
I can not check.  I am not a programmer and I did not find instructions.

**Comment by cbjeukendrup** [comment]
The same instructions as earlier apply: https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests

**Comment by re0001** [comment]
Ok. I did not find a file with number 25176 .  I found  this file :   MuseScoreNightly-202302060415-3.x-2513676-x86_64.7z
(It is 2513676 )

Are you talking about this file ?  

On the other hand, in the #25176 link, I did not found a file to install the programme.

**Comment by cbjeukendrup** [comment]
Here is a direct link to the download page: https://github.com/musescore/MuseScore/actions/runs/11347187786

**Comment by re0001** [comment]
I tried   MU4_242891333_Win_25176_[4.4.3] added connect to QQuickWindow__sceneGraphError     and the result did not change. I got the same message "Failed to initialize graphic backend for D3D11".
After clicking "Aceptar", the programme closes.

**Comment by cbjeukendrup** [comment]
That's unfortunate. Could you please do the following:
1. Open Windows Explorer (i.e. open any folder on your computer)
2. In the address bar (i.e. where the path to the current folder is displayed), enter `%LOCALAPPDATA%`
3. Locate the `MuseScore` subfolder and create a ZIP file of it (see https://support.microsoft.com/en-us/windows/zip-and-unzip-files-f6dde0a7-0fec-8294-e1d3-703ed85e7ebc)
4. upload the resulting ZIP file here; if it is too big, try emailing to `c.jeukendrup@mu.se`

**Comment by re0001** [comment]
I send the file.
[MuseScore.zip](https://github.com/user-attachments/files/17387575/MuseScore.zip)

**Comment by cbjeukendrup** [comment]
Here is another build to try: https://github.com/musescore/MuseScore/actions/runs/11360853138
Thanks very much for your patience with this issue!

**Comment by re0001** [comment]
I tried [MU4_242900723_Win_25182_[4.4.3] added connect to sceneGraphError]
Now there is not an error message, but the screen is white.  
I mean, I opened Musescore and after the loading image , the screen turns white.
![error](https://github.com/user-attachments/assets/3b2383a1-9508-4600-93cd-d217e814012f)
![error2](https://github.com/user-attachments/assets/bdff04d9-b960-42db-8858-52a17dc2724c)

**Comment by re0001** [comment]
I send the current log files.
[MuseScore.zip](https://github.com/user-attachments/files/17397995/MuseScore.zip)

**Comment by cbjeukendrup** [comment]
Thanks again! Here is another attempt: https://github.com/musescore/MuseScore/actions/runs/11370940218

**Comment by re0001** [comment]
([MU4_242901740_Win_25188_[4.4.3] added bad message 2 to GraphicsProblemsDetector]

It didn´t work. 
![error3](https://github.com/user-attachments/assets/de69b285-ed0f-4ded-b530-35af4e93251c)

**Comment by re0001** [comment]
[MU4_242910748_Win_25188_[4.4.3] added bad message 2 to GraphicsProblemsDetector]
Now it is working. 

However , I send the info: 
DELL Optiflex (desk computer), 
Intel(R) Core(TM)2 Quad CPU    Q9400  @ 2.66GHz   2.66 GHz, 
RAM 8,00 GB
Windows 10 PRO  22H22
Operating system compilation 19045.4651

![musescoreOKjpg](https://github.com/user-attachments/assets/cbb5bd78-e65c-4915-a21c-af361f4a2f6d)

**Comment by cbjeukendrup** [comment]
That's great news! Thank you so much for your long patience with this. 
Now I think we can close this issue, which would (almost?) clear the way for the 4.4.3 release!

**Comment by re0001** [comment]
Great news! 
Thanks for your work.
