### ISSUE TITLE
Ottava - changing font size does not do anything in my score

### ISSUE THREAD

**Issue by mart661331** [musescore/MuseScore#24858]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

see title, font size stays the same ... now rather big for me

### Supporting files, videos and screenshots

![Schermafbeelding 2024-09-21 164513](https://github.com/user-attachments/assets/4ac7d87c-b13d-4445-94dd-9c4255ccef9f)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

win 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by LupusCaeruleus** [comment]
The number 8 is in fact a symbol `<sym>ottava</sym>` so you need to adjust the **Musical symbols scale** value below.

But I think the UI needs some tweaking as it can be quite misleading for those who didn't realize it.
