### ISSUE TITLE
Fermatas only apply to single segment instead of the entire note duration (if there were some actions with dynamic before)

### ISSUE THREAD

**Issue by DaddyLudwig** [musescore/MuseScore#24852]
### Issue type

General playback bug

### Description with steps to reproduce

See more precise steps in https://github.com/musescore/MuseScore/issues/24852#issuecomment-2374032810

1. Input a note longer than an eighth note
2. Add a fermata
3. Notice that the fermata only affects the note on the first eighth note segment of the duration

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/22d75c5b-a220-480c-93f1-4857b2afc7c3

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio 4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
Good spot. 
Indeed in this case, it definitely makes sense for the fermata to apply to the duration of the note, and not just an individual segment.

**Comment by DmitryArefiev** [comment]
Doesn't occur if to just add a fermata to the whole note. It **requires** initial **steps with dynamics** at first.

1. Add two whole notes
2. Add F to the first note
3. Move F right-left
4. Add fermata

https://github.com/user-attachments/assets/2bbd340b-656e-49fa-8241-1fcd720c9ea2

**Comment by DmitryArefiev** [comment]
Fixed in #24921
