### ISSUE TITLE
MusicXML import ignores chord accidentals in files created by Cubase

### ISSUE THREAD

**Issue by lvinken** [musescore/MuseScore#24865]
### Issue type

Import/export issue

### Description with steps to reproduce

open file Untitled_score_xml_Cubase.xml (in attached zip file)
actual behaviour: both measures contain a B minor chord
expected behaviour: measure one contains a B chord, measure two contains a B minor chord

### Supporting files, videos and screenshots

[368990.zip](https://github.com/user-attachments/files/17088586/368990.zip)

### What is the latest version of MuseScore Studio where this issue is present?

master commit b86e6421

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Sonoma 14.6.1

### Additional context

Issue reported in https://musescore.org/en/node/368990. This is a MuseScore 4.4 regression, file Untitled_score_xml_Cubase.xml is handled correctly by MuseScore 3.6.2 and 4.3.

Root cause is that the "alter = m_e.readText().toInt();" in MusicXMLParserPass2::harmony() fails (silently). This is apparently cause by extra whitespace in the root-alter element. Notice the difference between both xml files in the zip.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
So it is the dufference between
```xml
      <harmony print-frame="no">
        <root>
          <root-step>B</root-step>
          <root-alter>-1
          </root-alter>
          </root>
        <kind text="m">minor</kind>
        </harmony>
 ```
and
```xml
      <harmony print-frame="no">
        <root>
          <root-step>B</root-step>
          <root-alter>-1</root-alter>
          </root>
        <kind text="m">minor</kind>
        </harmony>
 ```

**Comment by Jojo-Schmitz** [comment]
Sample xml from https://musescore.org/en/node/368990#comment-1259859
[het is genoeg.zip](https://github.com/user-attachments/files/17096117/het.is.genoeg.zip)

**Comment by Jojo-Schmitz** [comment]
`bass-alter` has the same issue, see https://musescore.org/en/node/368990#comment-1260723 and #24967
