### ISSUE TITLE
Crash on opening when hidden staff contains grace notes with beam changed

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#24862]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Create empty score
2. Add two 32nd grace notes
3. change beam position
4. make staff invisible
5. save/close/reopen score
6. crash

Regression. Works in MS 4.3.2
Issue is based on this report https://musescore.org/en/node/369140

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/6c8bac45-3444-4432-882f-c153466d83a4

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.5.0-242650304, revision: github-musescore-musescore-58ff01f

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
Regressioin occured between 4.3.2 and 4.4.0

Oddly, I can reproduce on Windows, but not on MacOS
