### ISSUE TITLE
Muse Sounds Mutes

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#24879]
### Your idea

Mutes (i. e. Harmon mute, Wah-wah mute, straight mute, cup mute, etc.), accessible as sound flag options.

### Problem to be solved

There are no options for this currently, and composers writing for a wind band would find this very helpful.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
This is a request for the Muse Sounds team (and I can confirm they already know about it). 
Hence we'll close this one here. 
Thank you!
