### ISSUE TITLE
Pin open "Show more" properties accordion

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#24880]
### Your idea

Add a pin button to the "Show more" accordions in the properties panel. This should configure all "Show more" sections to stay open in the properties panel (and indeed could be a preference - whether to default to pinned).

### Problem to be solved

When I'm editing in depth, I often want to access the properties that are hidden behind the "Show more" accordion, and if I click between several object of the same type, the accordion stays open. Click on blank space or a different type of object, though, and the state is forgotten. The next object I click on in the score has its "Show more" section closed. This is adding dozens if not hundreds of clicks to the process of preparing a score for publication.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by iwoithe** [comment]
Believe this is the same issue/feature request as https://github.com/musescore/MuseScore/pull/15821#issuecomment-1605931488 (but at least afaik was never made into an issue)

**Comment by MarcSabatella** [comment]
FWIW, instead of pinning open the "more" section, you could simply drag those elements to the main section.

**Comment by cbjeukendrup** [comment]
@MarcSabatella That applies to the Palettes, but I believe this issue is about the Properties panel.

**Comment by MarcSabatella** [comment]
Oops, of course you are right!  Similar requests have been made about the settings currently hidden under Appearance.  I believe it was mentioned there were plans to eventually allow individual settings to be pinned.

**Comment by avvvvve** [comment]
Completely agree! We're working on several improvements to the organization of properties and solving this is one of them. However, we'll likely do this with a lighter touch and just say "if a user has expanded 'Show more' in an element type's properties, always show it as expanded until they manually close it". That's logged already in #18770 so I'm going to close this one.
