### ISSUE TITLE
Mixer in version 4.4.2 is not displayed

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#24885]
### Description with steps to reproduce
https://musescore.org/en/node/369069

> the problem has already been reported on other forums:
> In version 4.4.2 the mixer window is not displayed.
> The problem is known on Windows 10 and probably Windows 11

https://musescore.org/en/node/369131

> I have started using version 4.4.2, and I wanted to open the mixer in a score, it is difficult to explain what it looks like, so I attached a screenshot.
> Looks like it has gone blank, but at the bottom left I can see little bits of the mixer itself.
> 
> There is another issue itself: I have a backup of a score (also in .mscz) on a different part of the PC, when I open this, on pressin g the "Play" button, MS immediately shuts down. When I run it again, MS stops responding.

https://musescore.org/en/node/341876

> I can't open the mixer as it has disappeared somewhere.
> I noticed that it would open in random places on the screen each time I opened a new session and it would resize.
> The last time I saw it, it had resized quite small and now today I can't locate it anywhere. I have searched around the edgers f the screen and tried resizing my layout etc but I can't find it anywhere.

### Supporting files, videos and screenshots

![MSMixer](https://github.com/user-attachments/assets/1dbeed6c-5e10-44db-8868-485995cf36f4)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in **MuseScore 4.4.1**

### Operating system

Windows 10, Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by FrancRos31** [comment]
I have a user who reported the same problem with Linux mint 22.
https://musescore.org/it/node/369276#comment-1260027 (italian forum)

**Comment by yoda-jm** [comment]
Almost the same issue on Gentoo (MuseScore 4.4.2), when clicking on "Mixer" (panel or menu) or "F10". The action seems to be sent, but nothing happens:
11:47:25.907 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: toggle-mixer
11:47:25.907 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: dock-toggle
11:47:26.476 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: toggle-mixer
11:47:26.477 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: dock-toggle

**Comment by yoda-jm** [comment]
> Almost the same issue on Gentoo (MuseScore 4.4.2), when clicking on "Mixer" (panel or menu) or "F10". The action seems to be sent, but nothing happens: 11:47:25.907 | INFO | main_thread | ActionsDispatcher::dispatch | try call action: toggle-mixer 11:47:25.907 | INFO | main_thread | ActionsDispatcher::dispatch | try call action: dock-toggle 11:47:26.476 | INFO | main_thread | ActionsDispatcher::dispatch | try call action: toggle-mixer 11:47:26.477 | INFO | main_thread | ActionsDispatcher::dispatch | try call action: dock-toggle

Reverting to 4.3.2 solves the issue

**Comment by MarcSabatella** [comment]
Is that with the official AppImage?  Are you by chance using multiple monitors?  What if you run View / Restore the default layout?

**Comment by yoda-jm** [comment]
This is the official Gentoo package (https://gitweb.gentoo.org/repo/gentoo.git/tree/media-sound/musescore/musescore-4.4.2.ebuild), it seems to use the standard tar.gz source files.
I tried to reset the layout and wipe the user configuration and it is still not showing.
I only have one monitor (so the dock is not on another screen), what is strange is that in the View menu the Mixer item is not checked, letting me think that it has silently failed to "pop" somewhere

**Comment by cbjeukendrup** [comment]
Could it be that Gentoo uses Qt 6.7.2 rather than 6.2.4? If so, I think this is caused by #24866 / #24097.

**Comment by MarcSabatella** [comment]
To be clear, no distribution package or other third-party build can really be considered an "official" version of MuseScore Studio.  The only build created, tested, and supported by the MuseScore team is the AppImage that you get directly from musescore.org or the releases section of GitHub.  I suspect you'll find that works as expected.

**Comment by yoda-jm** [comment]
Yes, Gentoo is now using Qt 6.7.2 (6.8 being tested AFAICT). I was just talking about the official Gentoo package not the MuseScore package.
In indeed seems that the symptoms I am experiencing seems to be similar to the one in the bugs you mentionned (4.3.2 os compiled with Qt5 whereas 4.4.2 is compiled with Qt6 that is currently Qt 6.7.2 on Gentoo).
I did not notice any similar bugs on other software currently using Qt6 on my desktop

**Comment by yoda-jm** [comment]
Gentoo bug tracker for reference: https://bugs.gentoo.org/938968

**Comment by FrancRos31** [comment]
> Yes, this used to work in **MuseScore 4.4.1**

Check this thread: https://musescore.org/en/node/351526. Seems like the problem goes back to version 4.2.1.

**Comment by cbjeukendrup** [comment]
The difficulty with this issue is that it is not very well defined: no very clear description of what's happening, and no steps to reproduce it. 

And I think that there is not one, but actually three problems:
1. Mixer panel _really_ does not open at all in third-party Linux packages that use Qt 6.5+ --> https://github.com/musescore/MuseScore/issues/24885#issuecomment-2377052582
2. Mixer panel _seemingly_ does not open, but in reality it does open but is very small --> https://github.com/musescore/MuseScore/issues/19258
3. Mixer panel does open, but content doesn't load 
    - If VSTs are involved, I think it is related to https://github.com/musescore/MuseScore/issues/23280 / https://github.com/musescore/MuseScore/issues/17123: looks like the audio thread gets stuck while loading those VSTs from a saved file, and the mixer depends on the audio thread, so fails to work if the audio thread is stuck
    - Sometimes, this goes hand in hand with a crash when trying to start playback
    - See also https://musescore.org/en/node/369131#comment-1261712

**Comment by FrancRos31** [comment]
Can't you open a thread in the Announcements section of the forums in which you ask the users to report their issue with the mixer (a messagge for each user)?

> The difficulty with this issue is that it is not very well defined: no very clear description of what's happening, and no steps to reproduce it.
> 
> And I think that there is not one, but actually three problems:
> 
> 1. Mixer panel _really_ does not open at all in third-party Linux packages that use Qt 6.5+ --> [Mixer in version 4.4.2 is not displayed #24885 (comment)](https://github.com/musescore/MuseScore/issues/24885#issuecomment-2377052582)
> 2. Mixer panel _seemingly_ does not open, but in reality it does open but is very small --> [Mixer panel not showing #19258](https://github.com/musescore/MuseScore/issues/19258)
> 3. Mixer panel does open, but content doesn't load
>    
>    * If VSTs are involved, I think it is related to [Addictive Keys VST - No sound at all if MS was closed while VST was used in the mixer #23280](https://github.com/musescore/MuseScore/issues/23280) / [Saving score with VST instruments assigned destroys scores #17123](https://github.com/musescore/MuseScore/issues/17123): looks like the audio thread gets stuck while loading those VSTs from a saved file, and the mixer depends on the audio thread, so fails to work if the audio thread is stuck
>    * Sometimes, this goes hand in hand with a crash when trying to start playback
>    * See also https://musescore.org/en/node/369131#comment-1261712

You can ask if the issue belongs to this list and then, this thread can be translated in the other forums to catch even more users who have this problem. In the time in which bug reports gather, you can focus on the other issues.
