### ISSUE TITLE
Underscore not working as a shortcut (with Shift combination)

### ISSUE THREAD

**Issue by Magnus26** [musescore/MuseScore#24882]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Open Edit -> Preferences and set underscore as the shortcut for tenuto.
2. Try the shortcut in a score. On my computer nothing happens.

### Supporting files, videos and screenshots

![Screenshot_20240923_081723](https://github.com/user-attachments/assets/8188c6f3-6aa4-4625-889e-160ef1089c1b)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

I was unable to check

### Operating system

Q4OS

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
Can you please tell us which type of keyboard you are using? (I.e. what its layout is?)

**Comment by bkunda** [comment]
@DmitryArefiev pls investigate

**Comment by Magnus26** [comment]
> Can you please tell us which type of keyboard you are using? (I.e. what its layout is?)

Swedish QWERTY layout where underscore is accessed via the dash key placed immediately to the left of the right Shift key, so the keys pressed for underscore are Shift+dash.

**Comment by DmitryArefiev** [comment]
> Swedish QWERTY layout where underscore is accessed via the dash key placed immediately to the left of the right **Shift key**, so the keys pressed for underscore are **Shift**+dash.

This is the same as #14539 because Shift is involved
