### ISSUE TITLE
Mid-measure barlines (non-functional) are not shown in parts

### ISSUE THREAD

**Issue by SteveBlower** [musescore/MuseScore#24895]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. In an empty score select a note or rest starting after the first beat
2. Click on a repeat barline in the barline palette (start repeat or end repeat, it doesn't matter)
3. See barline added before the selected note or rest
4. View the instrument as a part
5. Note that the repeat barline is not shown.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/6458a97c-e005-4083-9a6a-8c015d39ab31

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

No.

### Operating system

Windows 11

### Additional context

Related issue on musescore.org https://musescore.org/en/node/369195

Same behaviour in version 3.6.2

It is not clear why non-functional barlines would be needed.  Perhaps adding a repeat barline mid measure should also trigger the "Split measure" operation.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
It __is__ a regression, vs. Mu3...

**Comment by SteveBlower** [comment]
Regression vs MU3?

I can reproduce the problem in 3.6.2

https://github.com/user-attachments/assets/1163d07f-7641-48b9-bd1f-1cebe6a830fb

**Comment by Jojo-Schmitz** [comment]
Hmm, strange. I tiried with existing parts and there it worked, But indeed not woth parts generated later, which is extra stange, as thouse should be a copy

**Comment by Jojo-Schmitz** [comment]
OK, fixed in 3.7 now too ;-)
