### ISSUE TITLE
Rests move abruptly when you try to move them in multiple voices mode

### ISSUE THREAD

**Issue by FrancRos31** [musescore/MuseScore#24910]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Create a piano score
2. insert two voice in one of the staves (the second voice consisting of 8th notes and rests alternating) 
3. move one of the rests in the second voice
Expected behaviour: the rest remain under control of the cursor for all the process.
Actual behaviour: the rest move abruptly away from the cursor when you hold it and return abruptly in position when you release it.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/37bdff14-237e-455f-a605-4aa3ba0675d2

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

I was unable to check

### Operating system

Windows 10 Pro

### Additional context

I think it's the auto placement that causes the issue.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by FrancRos31** [comment]
I think this is related to #22622.

**Comment by irwir** [comment]
This report is only one case in the issue #21297.

**Comment by FrancRos31** [comment]
I'm going to close this and update my video there.
