### ISSUE TITLE
Copying, Pasting, Saving shortcuts on MacOS are defective/confused with page view shortcuts

### ISSUE THREAD

**Issue by BabySploon** [musescore/MuseScore#24938]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

Hello, 

The keyboard shortcuts for saving, copying, and pasting are malfunctioning. This is on MacOS Ventura 13.7

While using the command+S (save) shortcut, no saving actually happens. I believe somewhere in the code the command and control keys have been mixed up. The shortcuts are set to the default command+ as in previous versions. However, whenever I press command+V, I get vertical view. Whenever I do command+P I get page view. However, according to the shortcuts vertical view and page view are ctrl+v and ctrl+p, respectively (screenshots shown. When those shortcuts are engaged nothing happens). It is worth noting that command+X (cut) does work. As does command+shift+X (swap with clipboard). Somehow command+S and command+P are reset after a manual click of file>save but command+V still engages vertical view. 

### Supporting files, videos and screenshots

[MuseScore4.4Bug.zip](https://github.com/user-attachments/files/17156958/MuseScore4.4Bug.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS 13.7

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
This seems related to https://github.com/musescore/MuseScore/issues/24497.

In MuseScore, could you click Diagnostic > Save diagnostic files, and upload the resulting ZIP here? And which keyboard layout do you use?

On my own MacBook, I can't exactly reproduce this behaviour; it's slightly different. Shortcuts with Ctrl do nothing, while shortcuts with Cmd seem to work fine for me. Strange...

**Comment by cbjeukendrup** [comment]
I found steps that sometimes reproduce it:
1. Set Ctrl+C shortcut to "Check MuseSampler" (you might need to try a different action, but this one seemed to "work" (as in, reproduce the bug) for me)
2. (maybe: quit and reopen MuseScore
3. Press Ctrl+C -> nothing happens (or sometimes, "Check MuseSampler" gets indeed performed)
4. Press Cmd+C -> "Check MuseSampler" is performed, instead of Copy

And I also think I've found a fix.

**Comment by DmitryArefiev** [comment]
> I found steps that sometimes reproduce it:
> 
>     1. Set Ctrl+C shortcut to "Check MuseSampler" (you might need to try a different action, but this one seemed to "work" (as in, reproduce the bug) for me)
> 
>     2. (maybe: quit and reopen MuseScore
> 
>     3. Press Ctrl+C -> nothing happens (or sometimes, "Check MuseSampler" gets indeed performed)
> 
>     4. Press Cmd+C -> "Check MuseSampler" is performed, instead of Copy
> 
> 
> And I also think I've found a fix.

This case is Fixed in #25093

**Comment by DmitryArefiev** [comment]
@BabySploon Can you try this build please? https://github.com/musescore/MuseScore/actions/runs/11246994647 

(See [How to download test builds from pull requests](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests) )
