### ISSUE TITLE
String "Show graphics info ..." not in Transifex

### ISSUE THREAD

**Issue by Magnus26** [musescore/MuseScore#24942]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. Open Edit -> Preferences.
2. Click on Shortcuts and in the list to the right look up "Show graphics info..."
3. That string is not in Transifex and thus can't get a translation.

### Supporting files, videos and screenshots

![Screenshot_20240927_100211](https://github.com/user-attachments/assets/cacf5bd4-f219-40c5-9ec4-6fffe885fb62)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

I was unable to check

### Operating system

Q4OS

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
I can't find that string anywhare in the MuseScore code.
Hmm, I do, soft of, but `Show g&raphics info…`
https://github.com/musescore/MuseScore/blob/968f4e4bb39787a434a0c32c57bf5ac6b66ef5f4/src/framework/diagnostics/internal/diagnosticsactions.cpp#L52

**Comment by Jojo-Schmitz** [comment]
It probably crept in after 4.4.0 got released and as such hasn't yet been pushed to Transifex, but will for 4.5?

**Comment by Magnus26** [comment]
> I can't find that string anywhare in the MuseScore code. Hmm, I do, soft of, but `Show g&raphics info…`

Do you see "Show graphics info..." in MuseScore Studio's user interface like in the image I attached?

**Comment by Jojo-Schmitz** [comment]
Yes. And in Diagnose > System too

**Comment by Magnus26** [comment]
OK; there I have the r underlined.

**Comment by cbjeukendrup** [comment]
I've pushed it to Transifex, after updating the source strings file without `-no-obsolete`, to preserve compatibility with 4.4.0 and 4.4.1. 
If you translate the string now, not only 4.4.3 but also 4.4.2 will benefit from it.

**Comment by Magnus26** [comment]
> I've pushed it to Transifex, after updating the source strings file without `-no-obsolete`, to preserve compatibility with 4.4.0 and 4.4.1. If you translate the string now, not only 4.4.3 but also 4.4.2 will benefit from it.

What about "Show graphics info..." without the & before r?

**Comment by Jojo-Schmitz** [comment]
The occurrence in the shortcut list uses the same string

**Comment by Magnus26** [comment]
That ignoring has not worked on some other strings.

**Comment by Jojo-Schmitz** [comment]
It does here

**Comment by cbjeukendrup** [comment]
When it doesn't, it's usually a translation error, where translators added a `&` where they shouldn't have. Will need to be corrected on a case-by-case basis on Transifex.
