### ISSUE TITLE
Additional options for single bar "multimeasure" rests

### ISSUE THREAD

**Issue by rpatters1** [musescore/MuseScore#24947]
### Your idea

While researching #23918 I realized that whereas the requested feature in that issue already exists, there are a couple of other nice-to-have options with regards to multimeasure rests that encompass a single measure.

- the ability of a single bar "multimeasure" rest automatically to have the same width as an empty bar.
- automatically suppress the printing of a multimeasure rest range under a single-bar multimeasure rest, and instead display the measure number normally (if it would be displayed otherwise).

Beyond this, other settings that would be nice are:

- for old symbols, a different spacing value when there are 3 or more symbols so that they can be more closely spaced.

### Problem to be solved

Currently, both the spacing and measure number positioning of a single-bar multimeasure rest can appear awkward if

- old-style symbols are being used
- measure ranges beneath mm rests is selected

### Prior art

I have not researched what Dorico does. These were options in my Multimeasure Rest plugin for Finale.

### Additional context

I am opening this issue separately so that #23918 can be closed. If this is a desirable feature I'm willing to work on it.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
Thank you for these suggestions!

This is something we'd actually prefer to work on in-house since it intersects with the horizontal spacing algorithm. 

Assigning @mike-spa.

**Comment by rpatters1** [comment]
>This is something we'd actually prefer to work on in-house 

To be clear, I was not intending to change the way it behaves at all.

If it is a global style setting, the staff property setting would have to be modified to be a 3-state selection. I'm not sure what the correct UI for this is, but I am sure there is precedent.

**Comment by rpatters1** [comment]
Whoops, I responded to the wrong issue. I get why you would prefer to work on it in-house.

**Comment by rpatters1** [comment]
I would say that #25199 did not really address this issue. In particular, I think it would be useful to have

- the ability to suppress the mm rest range on a single bar mm rest and instead display the measure number normally (or not, if that's what the options dictate).
- the ability to space old-style mm rest symbols differently for 2 symbols vs. 3 or more. Indeed, in many editions the spacing of the symbols is proportional to the width of the mm rest. It might be more useful to specify minimum distance to barlines.

It appears I am not able to re-open this issue. If need be, I'll create a new one.

**Comment by zacjansheski** [comment]
Sorry for the mess.  For our purposes it would be better to close and open a fresh feature request.
