### ISSUE TITLE
Musescore crashes when deleting rows Flatpak

### ISSUE THREAD

**Issue by MiniApollo** [musescore/MuseScore#24959]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Open attached file
2. Select the region between the two final bar
3. Press delete key
4. Musescore crashes

### Supporting files, videos and screenshots

[Testing.zip](https://github.com/user-attachments/files/17174060/Testing.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

I was unable to check

### Operating system

Flatpak on Gentoo Linux Wayland Hyprland GCC x86-64

## Error message:
12:22:43.823 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: notation-delete
/usr/include/c++/13.2.0/bits/stl_vector.h:1232: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::back() [with _Tp = mu::engraving::MeasureBase*; _Alloc = std::allocator<mu::engraving::MeasureBase*>; reference = mu::engraving::MeasureBase*&]: Assertion '!this->empty()' failed.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
As you may be aware, Flatpak is not a supported configuration, and has known issues.  See in particular https://github.com/musescore/MuseScore/issues/24648.  Meanwhile, if you download and optionally install the official AppImage downloaded directly from musescore.org, that should work.

**Comment by MiniApollo** [comment]
Thank you for the reply.
I fixed the issue by installing the package from the Gentoo repos.
I see someone has already reported the problem, so I close this issue.

**Comment by MarcSabatella** [comment]
The versions from third party distributions aren't really supported either and will likely have other problems.  The AppImage is the only one actually built, tested, and supported by the MuseScore team.  Someday that might change, but for now, if you want to avoid problems, best to stick to the official builds.
