### ISSUE TITLE
Regroup-Rhythms deselcts notes when selection contains a rest or when selection starts on other that first beat. 

### ISSUE THREAD

**Issue by Ash-86** [musescore/MuseScore#24955]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Make a selection of a phrase without rests. 
2. apply regroup-rhytms --> selection marquee is maintained
3. replace any note with a rest within the selection. 
4. apply regroup-rhythms. --> marquee selection disappears. 

1. 1. Make a selection of a phrase that starts on a beat other than the first. 
2. apply regroup-rhytms --> selection marquee is maintained yet the notes are deselected.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/06cb8aa9-e31d-46ae-82e3-139576e6bab6

https://github.com/user-attachments/assets/faab7aa7-c89d-4ec5-8983-d2dd3ecef9a2

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
This should indeed be fixed, but to get a better view of how to prioritise this, does it cause any big problems or annoyances?

**Comment by Ash-86** [comment]
I don't think any big problem, no.

**Comment by AxelMatstoms** [comment]
I've started to work on this issue, and have fixed it on my fork. I'm planning to write a few tests for this behavior before submitting a PR. Could I be assigned to this issue?
