### ISSUE TITLE
Muse Sounds Oboe out of tune when legato from Db4 to C4

### ISSUE THREAD

**Issue by RustyBust** [musescore/MuseScore#24960]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

When legato or tenuto is used on the muse sounds oboe with either no sound flag or Ordinary, going from Db4 to C4, C4 is very out of tune.

### Supporting files, videos and screenshots

<img width="865" alt="image" src="https://github.com/user-attachments/assets/27b6c76e-5670-4c73-bf56-170a94149327">
[oboe out of tune 2.mscz.zip](https://github.com/user-attachments/files/17175458/oboe.out.of.tune.2.mscz.zip)
ithub.com/user-attachments/files/17175454/oboe.out.of.tune.mscz.zip)
[oboe out of tune.mp3.zip](https://github.com/user-attachments/files/17175455/oboe.out.of.tune.mp3.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.4, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

I was unable to check

### Operating system

OS: macOS 14.4, Arch.: x86_64

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
Can you please raise this issue via [Muse Hub customer support](https://support.musehub.com/hc/en-gb/requests/new)? 

Closing here as this is a MuseSounds-specific issue.
