### ISSUE TITLE
‘Merge matching rests’ default value as a staff style property

### ISSUE THREAD

**Issue by rpatters1** [musescore/MuseScore#24983]
### Your idea

Add a `Merge matching rests by default` option to the Staff Style properties that checks (or unchecks) `Merge matching rests` accordingly when new staves are created.

### Problem to be solved

The `Merge matching rests` option in the Staff properties is an excellent feature, but I and (I suspect) many others would like it always to default to checked when starting a new project or importing a MusicXML. To this end, I would like to see a new style property that accomplishes this.

I've been assured that one can do this with templates, but that cuts me off from all the built in templates unless I go through and recreate every one of them.

### Prior art

Finale added this feature as a document-level setting a number of years ago, due to clamorous demand from the user base. Since that version, it is the default setting for all new documents, even the bare-bones "New document without libraries". As with MuseScore, it can be overridden with manual edits on specific rests.

### Additional context

This is a project I could work on, if there is consensus that it is a good idea.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
Can I just confirm: do you mean you'd like this to be a global style property (so affecting all staves; not a staff style property that has to be set on a per-stave basis)?

**Comment by rpatters1** [comment]
A global style property affecting all staves would be fine with me. But I would be satisfied with a global style property that overrides the settings in the templates when staves are created.

An alternative would be to set the property in all the packaged templates, but I'm not crazy about that. (Nevertheless, this is more akin to what Finale did when they introduced the feature.)

**Comment by cbjeukendrup** [comment]
I think our preference would be to make it a global style setting, that users can override per-staff if they want, but by default staves would follow the global setting. Is that right @bkunda?

**Comment by rpatters1** [comment]
>I think that having merged rests as the default is not ideal.

Different strokes. This is why it will be an option. I also think there needs to be a way to change all staves at once, which would be in line with the idea of changing it later in the process.

Also, is selecting the highest numbered voice the right choice? It seems to me like it should select the lowest numbered voice.

**Comment by SteveBlower** [comment]
Yes, a choice, but my comment discusses which choice should be the default.  The original issue suggests merging should be the default and I disagree for the reasons I gave.

**Comment by rpatters1** [comment]
If someone would like to assign this to me, I'll work on it.

The default value of the new setting will be current behavior (i.e., unchecked).
