### ISSUE TITLE
Modified stem length changes after Saving-Loading on small staves

### ISSUE THREAD

**Issue by LupusCaeruleus** [musescore/MuseScore#25004]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Create a score with small staves.
2. Enter a note on a small stave, then change its stem length in the Properties panel.
3. Save the score, then close and reload it.
4. Notice the stem length has changed.

Expected: The stem length should remain the same as when the score was saved.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/e1a777b7-9cb8-43e0-aee4-b3f7acba781b

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3-242750503 (latest nightly build), revision: github-musescore-musescore-81203f7

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

Each time saved, the length of the stem becomes 10/7 (1/Small stave size) of the Length value in the Properties panel.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
@zacjansheski pls check regression status

**Comment by zacjansheski** [comment]
Regression occured between 4.3.2 and 4.4.0
