### ISSUE TITLE
Muse Sounds found from file manager but not command line

### ISSUE THREAD

**Issue by lilygruman** [musescore/MuseScore#25018]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

Expected:
MuseScore should detect the same MuseSounds libraries in the same location regardless of how it is opened.

Actual:
MuseScore finds and loads MuseSounds (v0.6.3) as expected when opening a file from a file manager (in my case, Nemo), but fails when run from the command line, claiming it is incompatible.

I could not figure out myself what the difference is between how Nemo handles its "Open" and "Open With..." directives and what I am typing on the command line.

### Supporting files, videos and screenshots

After uninstalling and reinstalling with `pacman`:
```
$ mscore
```
[mscore.log](https://github.com/user-attachments/files/17238637/mscore.log) (program crashes).

With a file as argument:
```
$ mscore Documents/MuseScore4/Scores/24-09-02.mscz
```
The program runs successfully but fails to load MuseSounds: 
[mscore-with-argument.log](https://github.com/user-attachments/files/17238640/mscore-with-argument.log)

As a bonus, when run via `$ xdg-open [filename].mscz` the file is recognized as a zip archive and opened in my archive manager (File Roller).

Video of successfully opening from file manager:
[mscore-nemo-video.zip](https://github.com/user-attachments/files/17238565/mscore-nemo-video.zip)

Video of opening the same file from the command line:
[mscore-terminal-video.zip](https://github.com/user-attachments/files/17238603/mscore-terminal-video.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

I was unable to check

### Operating system

Arch Linux (6.11.1-arch1-1)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
This may be a weird question, but are you sure that the same version is used when running `mscore` from the command line as when opening a file from the file manager? (You can check the version number in the About dialog)

**Comment by MarcSabatella** [comment]
It appears you are running an unsupported third party build of MuseScore ("pacman" is not a supported way of installing MuseScore, and "mscore" is not the correct executable name for the official build).  The fact that it runs from your window manager suggests you do have the correct build installed also.  That would normally be "mscore4portable", so try running *that* from the command line.  If that isn't installed, try running from your window manager, and then in the terminal, run "ps -ef | grep mscore" to see what the actual command line is, and then try running that yourself.

If you don't have the official MuseScore build (the AppImage), download it from the main download page on musescore.org, make it executable, then run it with the "install" option to install it.  Best to first uninstall any third party builds.

**Comment by lilygruman** [comment]
> This may be a weird question, but are you sure that the same MuseScore version is used when running `mscore` from the command line as when opening a file from the file manager? (You can check the version number in the About dialog)

I did think this was a possibility but I had dismissed it since uninstalling and reinstalling the pacman package affected the file manager as well, so I couldn't envision how another install of MuseScore would still be the target after pacman had disassociated and reassociated the MIME type.

Regardless, the version run from the command line is still 4.3.2.

> It appears you are running an unsupported third party build of MuseScore ("pacman" is not a supported way of installing MuseScore, and "mscore" is not the correct executable name for the official build). The fact that it runs from your window manager suggests you do have the correct build installed also. That would normally be "mscore4portable", so try running _that_ from the command line. If that isn't installed, try running from your window manager, and then in the terminal, run "ps -ef | grep mscore" to see what the actual command line is, and then try running that yourself.
> 
> If you don't have the official MuseScore build (the AppImage), download it from the main download page on musescore.org, make it executable, then run it with the "install" option to install it. Best to first uninstall any third party builds.

`mscore4portable` is not in my `PATH`. After opening with the file manager:
```
$ ps -ef | grep mscore
lily        2636    2565 99 12:45 ?        00:00:11 /usr/bin/mscore /home/lily/Documents/MuseScore4/Scores/Demo/Brahms Waltz (local).mscz
```
As it turns out, if I run on the command line with the full qualified `/usr/bin/mscore` it works fine. Normally I'd think that meant the one on the path and the one in `/usr/bin` are different, but:
```
$ which mscore
/usr/bin/mscore
```
I'm thinking there must be something about using the relative path that makes MuseScore look in different places.

Nevertheless, I switched to the AppImage and it worked fine, and I'll use that for the time being. I will say though, pacman is typically the primary means of installing packages on Arch, so it is surprising to me that it yields a different result, and disappointing that it is not "supported". If I pursue this any further, I'll bring it to the attention of the pacman package maintainer, since it's their build that had the odd behavior.
(here's the [package info](https://archlinux.org/packages/extra/x86_64/musescore/) and [repo](https://gitlab.archlinux.org/archlinux/packaging/packages/musescore), if anyone needs to know)

Anyway, thanks for humoring me, even though this didn't turn out to be an internal problem. Hopefully this was still informative in some way.

**Comment by cbjeukendrup** [comment]
Since this is specific to the `pacman`-provided build, which we don't have control over, I think this will have to be solved by the `pacman` maintainers, or at least investigated by them. Therefore, I will close this issue for now. However, if their investigation determines that any concrete action from our side is necessary to facilitate a fix, this issue can be reopened (or a new issue can be created). Thanks!
