### ISSUE TITLE
Move the "Diagnostic" menu into the "Help" menu

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#25015]
### Your idea

I would prefer to make the "Diagnostic" menu a submenu of the "Help" menu, instead of its own menu.

### Problem to be solved

- At least on macOS, it's very unusual to put any menu at the right of the Help menu
- Especially in some translations, like Dutch, the total width of all menus is quite big; if we can reduce it slightly by removing the Diagnostic menu, that would be an improvement
- People would only ever need this menu in the unfortunate event that they have to report a bug. There is no value in having to stare at it all the rest of the time.

### Additional context

Would Diagnostic**s** be more correct?

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Magnus26** [comment]
"Would Diagnostics be more correct?"

I would say yes. Let's hear from the native English speakers. I have actually translated it into Swedish as if it said "Diagnostics" instead.

**Comment by MarcSabatella** [comment]
To me (native speaker) either could potentially be correct.  But, with the “s” it is a (plural) noun, without it is more of an adjective as it is not so often used as a singular noun Menus are normally bounds or verbs, and the nouns are most often plural (aside from “File”).

So I guess would vote “Diagnostics” but don’t care strongly,

**Comment by bkunda** [comment]
I heartily agree with this proposal :-)

**Comment by avvvvve** [comment]
<img width="379" alt="image" src="https://github.com/user-attachments/assets/3f80f4f6-dbcb-48c3-8b5b-f23a5b488063">

Here's how I'd recommend we (re)organize the Help menu. It strikes me that we don't need a divider line between everything:

Check for update
~-~-~
Online handbook
Ask for help
~-~-~
Diagnostics >
~-~-~
About MusicXML...
~-~-~
Revert to factory settings
