### ISSUE TITLE
Crash when attempting to move slur at end of score

### ISSUE THREAD

**Issue by blucrunch** [musescore/MuseScore#25034]
### Issue type

Crash or freeze

### Description with steps to reproduce

With note input mode off, select a note at the end of the score, as here:
![17 01 05 - 2024 09 26](https://github.com/user-attachments/assets/78df7e1d-1347-4f75-94a5-0ec2e91b5d16)

Click the slur button to add a slur to that note:
![17 01 18 - 2024 09 26](https://github.com/user-attachments/assets/aca0f238-056a-4fbc-8819-5ff393a25aba)

Attempt to click and drag the slur from somewhere near the middle but not on a resizing box, and immediate crash.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/b2f8b8ee-7c4c-4275-b142-1d86f45eb177
[diagnostic files.zip](https://github.com/user-attachments/files/17250666/diagnostic.files.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

I was unable to check

### Operating system

Windows 10

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by blucrunch** [comment]
Actually, the goal is to add a tie through the repeat. I've used tricks in other places in other scores, like having invisible voice 2 notes to tie through to. If there's a better way to do this, I'd definitely do it that way.

**Comment by Ysabelle12** [comment]
#24726

**Comment by blucrunch** [comment]
> #24726

Bah, sorry. I searched for it and it didn't come up.

**Comment by zacjansheski** [comment]
Closing as duplicate / not reproducible in nightly
