### ISSUE TITLE
Add API for mixer settings

### ISSUE THREAD

**Issue by ingvarskagg** [musescore/MuseScore#25036]
### Your idea

The idea is to transfer parameters of instruments set up in mixer which can be used in exported MIDI

### Problem to be solved

Can be used for solving issues such https://github.com/musescore/MuseScore/issues/17371 or similar

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by RomanPudashkin** [comment]
This can already be achieved by using the following interfaces: IProjectAudioSettings and INotationSoloMuteState
