### ISSUE TITLE
Template Issue - Brass Band template is using incorrect name for 2nd Horn part

### ISSUE THREAD

**Issue by henkdegroot** [musescore/MuseScore#25046]
### Issue type

Other type of issue

### Description with steps to reproduce

When creating a score using the Brass Band template, the resulting score is showing:

![image](https://github.com/user-attachments/assets/21a60208-d972-4696-a652-b094ce1adf61)

The Alto Horn 1 is listed twice, while it should be one Alto Horn 1 and one Alto Horn 2. Like with the Baritone, Trombone, etc.

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/b6fbd8a0-a2dd-4fd0-85bf-d0706a33a577)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
Regression vs. Mu3...
