### ISSUE TITLE
[Musicxml Export] - Tempo are not exported as system texts and lines

### ISSUE THREAD

**Issue by hhpmusic** [musescore/MuseScore#25048]
### Issue type

Import/export issue

### Description with steps to reproduce

  I can't find the previous thread I posted about better Musicxml 4 export. Sorry for this!
  In the recent version, I found all system texts are exported correctly as Musicxml 4 system tags. However, all tempo texts are still exported as common words. They are also system elements, and should apply the same system settings as system texts. For example, this score, all tempo texts are exported as words, and all tempo modulations are correctly exported as system texts and lines.
[Fantasie sur un theme Espagnol.zip](https://github.com/user-attachments/files/17264480/Fantasie.sur.un.theme.Espagnol.zip)

### Supporting files, videos and screenshots

  I can't find the previous thread I posted about better Musicxml 4 export. Sorry for this!
  In the recent version, I found all system texts are exported correctly as Musicxml 4 system tags. However, all tempo texts are still exported as common words. They are also system elements, and should apply the same system settings as system texts. For example, this score, all tempo texts are exported as words, and all tempo modulations are correctly exported as system texts and lines.

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

No.

### Operating system

Windows

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by rettinghaus** [comment]
@hhpmusic are you referring to #17431?

**Comment by hhpmusic** [comment]
Yes, but since that thread has not been updated, and this has only be halfly solved, I had to open a new one.
