### ISSUE TITLE
Hairpin height resets after closing+reopening

### ISSUE THREAD

**Issue by dpMusicman** [musescore/MuseScore#25054]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Insert a hairpin into the score.
2. Change the height of the hairpin.
3. Save and close the file.
4. Reopen the file.

### Supporting files, videos and screenshots

<img width="684" alt="crescendo bug before" src="https://github.com/user-attachments/assets/3d814a37-b488-4176-8649-cc17d6f79a9c">
<img width="713" alt="crescendo bug after" src="https://github.com/user-attachments/assets/2f6db32d-c251-490d-a089-24a2a91218dc">

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2.24

### Regression

I was unable to check

### Operating system

macOS 13.2.1

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
This should be fixed already in 4.4.3 nightly builds - see https://github.com/musescore/MuseScore/issues/24737

**Comment by zacjansheski** [comment]
Closing per comment above
