### ISSUE TITLE
Keyboard shortcut for Paste Half Duration is already in use by macOS

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#25059]
### Issue type

Choose option...

### Description with steps to reproduce

The keyboard shortcut Command Shift Q for paste half duration is already used by macOS for logging out the computer. It therefore doesn't work in MuseScore Studio.

### Supporting files, videos and screenshots

![Dialog](https://github.com/user-attachments/assets/c30ff7bc-aa14-4150-8f22-c15e668e5dc5)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio 4.4.2

### Regression

I was unable to check

### Operating system

macOS 12.7.2

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
Those shortcuts have already been changed to Ctrl+Shift+Q/W, i.e. Ctrl instead of Cmd. To get the new defaults, you'll need to reset them in Preferences > Shortcuts.

**Comment by cbjeukendrup** [comment]
I found the previous issue about this, and its fix: https://github.com/musescore/MuseScore/issues/13951
So I think we can close this.
