### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by Magnus26** [musescore/MuseScore#25072]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. Set the interface language of MuseScore Studio to Swedish (traditional).
2. Open the palette Diverse.
3. Place the mouse pointer on the diminuendo hairpin and see that the tooltip shown is in English.
4. Place the mouse pointer on the diminuendo line and see that the tooltip shown is in English.

### Supporting files, videos and screenshots

![Screenshot_20241007_184830](https://github.com/user-attachments/assets/3a0db5f1-f278-40bf-a989-b9178c8e7382)
![Screenshot_20241007_184856](https://github.com/user-attachments/assets/cbeb927e-e77b-4be2-b6e0-7db368654608)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

I was unable to check

### Operating system

Q4OS

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
We made some fixes for this in 4.4.x, and I think a palette reset should resolve it (and after that, switching languages should work without ever needing another palette reset).

**Comment by Magnus26** [comment]
> We made some fixes for this in 4.4.x, and I think a palette reset should resolve it (and after that, switching languages should work without ever needing another palette reset).

Thanks, Casper. A reset solved the problem.

**Comment by Magnus26** [comment]
You're welcome, and thanks for the additional information. I understand that there are many much more urgent problems to solve.
