### ISSUE TITLE
Infer <type> from <duration> in MusicXML import

### ISSUE THREAD

**Issue by olin256** [musescore/MuseScore#25103]
### Your idea

While `<duration>` is a required element inside `<note>` in MusicXML, `<type>` is not. However, if I import a file with `<type>`s missing, all I get is grey rests. Couldn't the information about note type be inferred in an obvious way from the duration and `<divisions>`?

### Problem to be solved

MusicXML files with missing `<type>` elements would still be imported in a meaningful way.

### Prior art

For example, OSMD
https://opensheetmusicdisplay.github.io/demo/
handles this problem in the suggested way.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Jojo-Schmitz** [comment]
I'd rather call it a but that wo don't do this already, with `<type>` clearly being optional

**Comment by Jojo-Schmitz** [comment]
Can you provide a sample MusicXML file?

**Comment by olin256** [comment]
Just use the "Hello world" file from the MusicXML W3 page and remove `<type>`:
[hello.txt](https://github.com/user-attachments/files/17311400/hello.txt)

**Comment by Jojo-Schmitz** [comment]
It imports that as a quarter note rather than as a whole note (and then consequently adds an invisible dotted half rest)

**Comment by olin256** [comment]
This is what I get:
![hello](https://github.com/user-attachments/assets/326e03b6-8cce-4924-90b5-394d20768a81)
OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

**Comment by Jojo-Schmitz** [comment]
Opps, you're right. In Mu3 I get 
![image](https://github.com/user-attachments/assets/0f72f48a-3831-4211-9d13-1e4fa8d67c44)
though

**Comment by Jojo-Schmitz** [comment]
Mu3 can't determine the duration in the MusicXML import, so it assumes quarter, in durationtype.cpp, I guess Mu4 doesn't make that assumption anymore

**Comment by Jojo-Schmitz** [comment]
I believe I found the spot where it a) goes wrong and b) can get fixed, at least for Mu3 (will look into  Mu4 later)
