### ISSUE TITLE
Have a way to set a key mode (major/minor)

### ISSUE THREAD

**Issue by amypellegrini** [musescore/MuseScore#25119]
### Your idea

Having a mechanism to define whether a key is major or minor when setting a key signature.

### Problem to be solved

When exporting to Music XML, capturing this information could improve interoperability with other software that may rely on the key signature mode to infer the key (e.g. A minor, instead of C Major, or D minor instead of F Major, based on the key signature).

### Prior art

This is already part of the Music XML spec, although it's not required for setting a key and the possible values are loosely defined. I suspect "major" and "minor" could be considered base use cases straightforward to support.

To support this Musescore would have to provide the following:

- A UI to enable users to set this (it could be via the key signature palette, or some other way)
- A way to record this information in mscz format
- Setting the element in Music XML when exporting it
- Having the ability to leave this undefined and handling gracefully other import/export scenarios that may occur

https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/mode/

### Additional context

I'm writing external software that consumes Music XML from different sources, and I want to provide good interoperability with Musescore. I expect my target audience to be avid users of Musescore.

The software I'm writing would generate a Jazz backing track arrangement based on a chord chart (similar to Band in a Box or iRealPro), and supports importing chord charts from Music XML. As you can see in the screenshot, the key selector dropdown  allows users to select a key to transpose in a similar fashion as a Jazz musician would do when transposing a Jazz standard, or when stating the key ("... we are playing Autumn Leaves in C minor" or "let's play a 12 bar Blues in Bb major").

I know a feature like this is a big ask and it will most likely take some time (if ever) to see the light of day, assuming this feature is really desired, so I'm open to suggestions on how to workaround this. I'm also willing to collaborate as an OSS contributor either with the design or implementation if there is consensus that this should be implemented.

![tempFileForShare_20241010-155848](https://github.com/user-attachments/assets/1b809e03-94ff-4943-9748-3cc9f9085d32)

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment]
When you select a key signature, there is a 'Mode' dropdown in Properties:
![image](https://github.com/user-attachments/assets/db806fe8-e812-4566-b621-003f04b85ee8)

Off the top of my head I don't know if it exports properly, or how you access it if you're in C major!

**Comment by amypellegrini** [comment]
Thanks @oktophonie this is fantastic! I didn't knew about this feature. C major would just be mode major with zero fifths, that is how the software will infer it. I will confirm if Music XML export captures this.

**Comment by amypellegrini** [comment]
Yes indeed! 
![image](https://github.com/user-attachments/assets/56928a44-21a0-4665-a21a-f1eac94cb6cb)

Thanks

**Comment by Jojo-Schmitz** [comment]
It's been me to implement it, years ago. And later to fix it to export too ;-)

**Comment by amypellegrini** [comment]
Thanks in retrospect! @Jojo-Schmitz :)
