### ISSUE TITLE
Create From Template -> Orchestral -> Symphony Orchestra has 2 x "Trumpet in Bb 1" parts

### ISSUE THREAD

**Issue by callumjohnspiller** [musescore/MuseScore#25124]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Create a new score
2. Create From Template -> Orchestral -> Symphony Orchestra
3. Observe that the created score has 2x "Trumpet in Bb 1" parts instead of having a Trumpet in Bb 2

### Supporting files, videos and screenshots

[orchestral template error.zip](https://github.com/user-attachments/files/17334410/orchestral.template.error.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

Suspect this is just a case of a misconfigured preset

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by FrancRos31** [comment]
Check #25046, same issue in the brass band template.

**Comment by Jojo-Schmitz** [comment]
Regression vs. Mu3...
