### ISSUE TITLE
Measure stretch and Minimum Measure Width functioning improperly

### ISSUE THREAD

**Issue by MikePia** [musescore/MuseScore#25147]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Premise is trying to display a 1 measure example that does not take the entire width
2. Create the measure of music with 8 notes/rests or more
3. Right click the measure
![image](https://github.com/user-attachments/assets/6e34ddf0-c946-4efe-a3d4-08183199fd4a)
![Screenshot from 2024-10-13 13-34-26](https://github.com/user-attachments/assets/c11db02a-155c-431c-96d2-2cda9d761866)
, select measure properties
4. Adjust the Layout stretch till it changes.
5. I found at .70, the width is adjusted to about 1/5 the width, and at .71, it takes the entire width
![image](https://github.com/user-attachments/assets/dd4f9e15-6e4e-4302-b1b7-d8ea8155279e)

Found similar behavior setting Minimum measure width
1. Set stretch at .70
2. go to styles->Measure
3. adjust Minimum Measure width till ti changes. The change moves from its current size (~1/5/ width to full width with nothing inbetween)

### Supporting files, videos and screenshots

![Screenshot from 2024
![Screenshot from 2024-10-13 13-36-51](https://github.com/user-attachments/assets/64d1ecd2-6caf-4305-b675-ba69caacc263)
-10-13 13-34-26](https://github.com/user-attachments/assets/4ef31521-a395-4fc0-88e6-ff4010603338)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Ubuntu 22.04.5 LTS, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

### Regression

I was unable to check

### Operating system

Ubuntu 22.04

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
It is debatable as to whether what you are doing should work differently than it does, but in any case, fiddling with stretch is the wrong way to achieve the result you are trying to achieve.  Instead, add a horizontal frame and size it to take up the amount of space you want, and the measure with automatically take the rest.

**Comment by cbjeukendrup** [comment]
The behaviour is indeed expected; when the measure width reaches a certain threshold, it is justified to fill the entire system. This threshold happens to be configurable in Format > Style > Page, at the bottom. Depending on your use case, you can either 
- set that threshold to a high value, or
- if you're planning to take a picture of just that one measure, you could use Continuous View and take a screenshot of that, or
- use Marc's suggestion of using a horizontal frame (see the "Layout" palette).

I think that closes this issue. If you need more advice, feel free to ask at https://musescore.org/forum. Or, if you really think there is a bug here, let us know, then we can reopen this issue.

**Comment by MikePia** [comment]
I can't tell you how impressed I am to have received responses and so quickly.  The responses make sense.  Good luck and here is to getting all the fallout from Finale's demise :)
