### ISSUE TITLE
No bend in playback when the bend starts from the tied note

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#25159]
**Steps**
1. Open the score
2. Play it 
3. Pay attention to there's no bend in playback

Reproducible on both MS Basic and Musesounds 

**Screencast**

https://github.com/user-attachments/assets/dbc8336f-ed7c-4eb6-83db-bb67363c96f5

Tested on macOS, MS Studio 4.4.3

**Comment by RomanPudashkin** [comment]
Duplicate of https://github.com/musescore/MuseScore/issues/21345
