### ISSUE TITLE
Unable to change colour of Instrument Name

### ISSUE THREAD

**Issue by Postoli** [musescore/MuseScore#25204]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Click on Instrument Name (either Long or Short)
2. In Properties, click "Style Settings"
3. Set the text colour to anything other than black
4. Note that the colour does not change

### Supporting files, videos and screenshots

![Image 17-10-2024 at 9 56 pm](https://github.com/user-attachments/assets/aec7f013-43ee-4564-820a-db30e2b23081)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2-242570931

### Regression

No

### Operating system

macOS Sonoma 14.1

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by krasko78** [comment]
Can be assigned to me. I have created a PR. Thanks!
