### ISSUE TITLE
Individual n/32 time signature corrupts auto beaming

### ISSUE THREAD

**Issue by Brixy** [musescore/MuseScore#25210]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

Hi guys,

long-time MuseScore user here. I think I found a bug. But I have never followed the MuseScore development.

It is not possible to restore the default beam grouping for the 4/4 bar using the "time signature properties" window. The 5/32 somehow corrupts auto beaming completely.

Also "auto" from the beams palette does not have any effect.

Grouping beams individually still works.

### Supporting files, videos and screenshots

![musescore](https://github.com/user-attachments/assets/bd624b43-3b54-4065-8076-d236e4a0f7b7)

[musescore.zip](https://github.com/user-attachments/files/17435562/musescore.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

I was unable to check

### Operating system

Linux/Wayland

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
See also https://github.com/musescore/MuseScore/issues/21733, which seems related is not the same issue.
