### ISSUE TITLE
MuseScore 4.4.2 hangs upon opening

### ISSUE THREAD

**Issue by onaforeignshore** [musescore/MuseScore#25224]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Open the program
2. Wait while it is "Scanning audio plugins"
3. The app then hangs 

### Supporting files, videos and screenshots

<img width="795" alt="Screenshot 2024-10-19 at 17 14 17" src="https://github.com/user-attachments/assets/2e68551d-2da0-487c-8a96-a7a4eb4ec4d3">

[MuseScore_241019_171805.log](https://github.com/user-attachments/files/17445348/MuseScore_241019_171805.log)

[Sample of MuseScore Studio.txt](https://github.com/user-attachments/files/17445349/Sample.of.MuseScore.Studio.txt)

### What is the latest version of MuseScore Studio where this issue is present?

Can't access the program, but it happens from 4.0.0 to the latest nightly build

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Sequoia 15.0.1 (24A348)

### Additional context

This used to work when I had the original MuseHub. When I installed the new MuseHub, and updated everything, it just stopped working.

I have tried removing the plugins from /Library/Audio/Plugins/VST3 and /Library/Audio/Plugins/Components
I have tried removing the settings in ~/Library/Application Support/MuseScore/MuseScore4

**When I went into Settings -> General -> Language & Region while the App was hanging and changed the order of a Preferred Language, MuseScore loaded and worked.**

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
This part of the attached sample file:
```c++
    +                                                     2400 muse::extensions::ExtensionsProvider::reloadPlugins()  (in mscore) + 296  [0x10363e9bc]
    +                                                       2400 muse::extensions::legacy::ExtPluginsLoader::loadManifestList(muse::io::path_t const&, muse::io::path_t const&) const  (in mscore) + 408  [0x103626e54]
    +                                                         2400 muse::extensions::legacy::ExtPluginsLoader::manifestList(muse::io::path_t const&) const  (in mscore) + 120  [0x103627168]
    +                                                           2400 muse::extensions::legacy::ExtPluginsLoader::parseManifest(muse::io::path_t const&, muse::io::path_t const&) const  (in mscore) + 68  [0x103627690]
    +                                                             2400 muse::io::File::readFile(muse::io::path_t const&, muse::ByteArray&)  (in mscore) + 76  [0x102320c5c]
    +                                                               2400 muse::io::FileSystem::readFile(muse::io::path_t const&, muse::ByteArray&) const  (in mscore) + 176  [0x1022ecf70]
    +                                                                 2400 QIODevicePrivate::read(char*, long long, bool)  (in QtCore) + 676  [0x108c12258]
    +                                                                   2400 QFileDevice::readData(char*, long long)  (in QtCore) + 148  [0x108c05404]
    +                                                                     2400 ???  (in QtCore)  load address 0x108bdc000 + 0x33110  [0x108c0f110]
    +                                                                       2400 read  (in libsystem_kernel.dylib) + 8  [0x190f929b0]
```
suggests that it might not have to do with audio plugins, but with QML plugins. 

Do you have anything in `~/Documents/MuseScore4/Plugins`? If yes, does it help to (re)move that temporarily?

And is there perhaps a "MuseScore 4 wants to access files from your Documents folder" popup somewhere?

**Comment by onaforeignshore** [comment]
I did not get a popup for file access, but I did find a QML plugin called "MuseScore TempoChanges-3.3.0" in that folder. When I removed it, MuseScore worked as usual again.

It must have been there for a long time, but MuseScore has worked until now. It might be helpful to have some sort of check for invalid plugins in that folder and notify users in the future.

**Comment by DmitryArefiev** [comment]
@onaforeignshore I can't reproduce it with this plugin https://github.com/jeetee/MuseScore_TempoChanges/releases/tag/3.3.0 in **4.4.2** on **macOS13.6**

Can you put back that plugin and check again please?

**Comment by onaforeignshore** [comment]
That may be because my folder contains this file in addition to the ones listed on the github

TempoChanges.qmlc

(I can't upload that file type here though)

**Comment by onaforeignshore** [comment]
[TempoChanges.qmlc.zip](https://github.com/user-attachments/files/17475571/TempoChanges.qmlc.zip)

**Comment by onaforeignshore** [comment]
I have just restored the folder (with the QMLC file), and MuseScore opened normally. There doesn't seem to be any issue anymore.

**Comment by DmitryArefiev** [comment]
> [TempoChanges.qmlc.zip](https://github.com/user-attachments/files/17475571/TempoChanges.qmlc.zip)

Hm.. Can't reproduce with this file too..

@igorkorsukov Can this qmlc file be involved in the bug, what do you think?

**Comment by cbjeukendrup** [comment]
I think it's more likely to be a macOS issue or an issue with your harddrive, given that it's hanging in `read  (in libsystem_kernel.dylib) + 8  [0x190f929b0]`. 

(Also, @onaforeignshore , what about the comment that you deleted, about that restoring the file did not bring the issue back?)

**Comment by DmitryArefiev** [comment]
Good. Thanks for investigation!
