### ISSUE TITLE
Note input spams notes

### ISSUE THREAD

**Issue by PianoMan5129** [musescore/MuseScore#25233]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

When I click on the note input button and start inputting notes into my score, it rapidly spams notes and the only way to stop it is by exiting out of the note input mode.

### Supporting files, videos and screenshots

[Screencast from 2024-10-19 17-58-28.zip](https://github.com/user-attachments/files/17447642/Screencast.from.2024-10-19.17-58-28.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Fedora Linux 40

### Additional context

When I connect an external MIDI keyboard, I do not experience this issue.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
Sounds like you have a MIDI loop on your system - you have MuseScore configured to send MIDI out to a device that is then also turning around and sending it back to MuseScore as input.  You need to either tell MuseScore not to output to or input from that device, or set the device not to echo its input to its output.

**Comment by PianoMan5129** [comment]
Thanks! The midi input and output were both set to midi through. I set them to no device, which fixed the issue.
