### ISSUE TITLE
Chord Symbols should be freely positionable anywhere in a measure, like dynamics

### ISSUE THREAD

**Issue by XiaoMigros** [musescore/MuseScore#25249]
### Your idea

As of 4.4 dynamics can be attacted not just to notes or rests, but to any point in a measure. Chord symbols should receive this ability too, as the current system (attachable to notes, rests, or main beats of a measure) is not flexible enough and has a less smooth UX.

### Problem to be solved

Especially for lead sheets chord changes don't always occur on main beats or beats of the melody. Allowing them to be freely positionable would make creating such lead sheets easier and less 'hacky'.
Additionally, it is not possible to move existing chord symbols to positions not anchored to notes or rests, they have to be created on such positions. Adding the functionality for dynamics would allow for repositioning them with shift+left/right.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by jeetee** [comment]
I'm assuming this issue is concerning mouse-input (especially, drag to reposition). Using the keyboard shortcuts, you are not bound to notes/rests/beats as there are "advance by duration" commands as well: https://musescore.org/en/handbook/4/chord-symbols#commands

**Comment by XiaoMigros** [comment]
In part yes, with a mouse it's not possible currently. But also AFAICT it's not possible even with keyboard shortcuts to reposition an existing chord symbol in such a way, only repositioning of the cursor

**Comment by bkunda** [comment]
We may also need to consider this in light of other objects that currently behave in a similar way (figured bass?). 
Some design thinking will likely be needed @avvvvve @oktophonie.

**Comment by XiaoMigros** [comment]
Superceded by #25668?
