### ISSUE TITLE
Breve rests on single line staves should hang down.

### ISSUE THREAD

**Issue by rpatters1** [musescore/MuseScore#25246]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Open a new file with (e.g.) bass drum as an instrument.
2. Set the time to 4/2 or larger.
3. See that the breve rests are above the line.

### Supporting files, videos and screenshots

Gould "Behind Bars" is very clear that breve rests should hang below a single staff line. See p. 38:

<img width="639" alt="Screen Shot 2024-10-20 at 9 51 12 AM" src="https://github.com/user-attachments/assets/a2f3381e-2cee-4402-8160-38df24c4c1c6">

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

I was unable to check

### Operating system

macOS 12.7.6

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by XiaoMigros** [comment]
Despite the issue you linked it's still better to change the default, no?

**Comment by rpatters1** [comment]
>Despite the issue you linked it's still better to change the default, no?

I think it is better to change the default, but #25279 would allow some cleverness around importing existing files and maintaining their current positioning. It is true that there may be very few existing scores that use full-measure breve rests on single-line staves. But what we decide around that is above my pay grade. Personally I tend to be OCD about porting everything without changes.

**Comment by XiaoMigros** [comment]
That's what Finale does to oneself...

**Comment by XiaoMigros** [comment]
I think that would make sense, at a glance the code looks good and that's the most reliable way of getting staff feedback (and if they don't like it they'll tell you to close it!)
