### ISSUE TITLE
Please add a DAW like play/stop shortcut or option (Very basic but a big ergonomy issue for some users)

### ISSUE THREAD

**Issue by ValCT** [musescore/MuseScore#25240]
### Your idea

Simply add a shortcut or option to make the playback behavior of Musescore able to match what is well establish in the DAW world : hit a key to start playback then hit the same key again to stop while resetting playback cursor start position, so that playback will start from the same location again. This could be :
- New shortcut : play/stop with intended bahavior (the stop function of Musescore in fact pauses the playback)
- New option in general settings: "reset playback start position when stopping playback"
*Note* : This must be using the same key. Having to hit a different key to stop and return to initial position is not intuitive for the users in question. The idea is to have true regular "play/stop" button.

### Problem to be solved

Solves an ergonomy and workflow issue that DAW users (or maybe some coming from other notation software) encounters : unusual playback control behavior.
It is a deeply integrated reflex that cannot be change for them and it makes transport in Musescore truly painful to use.
The existence of workarounds (set loop cursors, click back on the desired start point each time playback is stopped...) is not to be argued because it is a workflow issue, things have to be immediate, as a basic control feature of the software.

### Additional context

I belive that a software should be able to fit some of the most basic reflexes that users acquire by using it's counterparts.
I think that Musescore is becoming used by a very large panel of users profiles, not only classical music composers, but all kind of music producers, that could in fact spend most of their time on a DAW rather than on a notation software.
I'm a professional musician and sound engineer (mostly in jazz, rock and folk music) and many people I work with do use mostly DAWs then Musescore in their projects.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by chrisroode** [comment]
Hello, just thinking about this.  Most DAW's use spacebar.  First of all. Does that collide with any non-text entry inputs? That could lead to undefined behavior of this feature.

I would think that the higher case of text entry like lyrics could lead to frustration with the UI accidentally playing, for instance if a user is typing lyrics, bumps the mouse button deselecting the entry and continuing to type, then spacebar could lead to playback starting when the user does not intend to start playback.

A workaround I could see is having the spacebar pause control start when playback is started with the play button. Then the user can pause and unpause with spacebar, and the spacebar remains armed for playback until the user interacts with something indicating that they are returning to editing the music.

**Comment by ValCT** [comment]
@chrisroode my shortcut for play/pause is indeed set to spacebar in Musescore, it didn't cause any trouble while entering text in fields so far, as for the other software i use (if I accidentally unselect the text entry I would not complain about Musescore starting the playback anyway :-) ). If the user is affraid of this, he could set another shortcut. Anyway, my suggestion won't change anything regarding this potential problem, does it ?

**Comment by ValCT** [comment]
Aside from this, the absence of a visual representation of the playback cursor, even when paused or stop, could be a bit disturbing, in many other software the vertical bar stays all the time.
Also, there is an action that has no effect in Musescore : clicking in a blank part of the page. This could be used for setting the playback cursor position, it may be more efficient than having to select a note or a measure.
