### ISSUE TITLE
汉化： 男高音 介绍 文本 有 错字

### ISSUE THREAD

**Issue by PtJade-Ceramic** [musescore/MuseScore#25253]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. 新建 或者 打开 一份 乐谱 文件。
2. 点击 在 菜单栏 之中 的 **视图** 按钮 （按 Alt + V， 快捷键 均 以 Windows 为例， 下同）， 选择 **乐器** 选项（按 U）； 或者 直接 按 **F7**。
3. 点击 某个 乐器 的 **设置** 齿轮 图标。
4. 点击 **替换 乐器** 按钮。
5. 点击 **乐器族** 一栏 的 下拉 列表， 选择 **常见** > **声乐** 选项， 在 **乐器** 一栏 点击 **男高音**； 或者 直接 在 **乐器** 栏 的 搜索框 输入 “男高音”， 选择 相应 的 选项。

会 发现 **男高音** 的 介绍 文本 有 错字。

### Supporting files, videos and screenshots

<img width="479" alt="屏幕截图 2024-10-20 140852" src="https://github.com/user-attachments/assets/b00f90ca-74d0-4d09-855b-dba8d8173138">

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I was unable to check

### Operating system

Windows 11 Version 23H2 (OS 内部 版本 22631.4317)

### Additional context

[Working with instruments _ MuseScore](https://musescore.org/zh-hans/node/329665)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
ENGLISH TRANSLATION OF ABOVE (using ChatGPT)

**Chinese translation: There are typos in the introduction of the tenor**

1. Create or open a score file. 
2. Click the 'View' button in the menu bar (press Alt + V, keyboard shortcuts are based on Windows, same below), and select the 'Instruments' option (press U); or directly press F7. 
3. Click the gear icon for the settings of a specific instrument. 
4. Click the 'Replace Instrument' button. 
5. In the dropdown list under the 'Instrument Family' column, select 'Common > Vocals,' then in the 'Instrument' column, click 'Tenor'; or directly type 'Tenor' in the search box and select the corresponding option. 

You will find that there are typos in the introduction text for the tenor

-----

@cbjeukendrup is there a mechanism for reporting this on Transifex? I'm not sure this is the most helpful place for this kind of issue.

**Comment by PtJade-Ceramic** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by PtJade-Ceramic** [comment]
> ENGLISH TRANSLATION OF ABOVE (using ChatGPT)
> 
> **Chinese translation: There are typos in the introduction of the tenor**
> 
> 1. Create or open a score file.
> 2. Click the 'View' button in the menu bar (press Alt + V, keyboard shortcuts are based on Windows, same below), and select the 'Instruments' option (press U); or directly press F7.
> 3. Click the gear icon for the settings of a specific instrument.
> 4. Click the 'Replace Instrument' button.
> 5. In the dropdown list under the 'Instrument Family' column, select 'Common > Vocals,' then in the 'Instrument' column, click 'Tenor'; or directly type 'Tenor' in the search box and select the corresponding option.
> 
> You will find that there are typos in the introduction text for the tenor
> 
> @cbjeukendrup is there a mechanism for reporting this on Transifex? I'm not sure this is the most helpful place for this kind of issue.

What is the URL of the Transifex project?

**Comment by FrancRos31** [comment]
> What is the URL of the Transifex project?

https://app.transifex.com/musescore/musescore/dashboard/. You have to create an account first.

**Comment by Jojo-Schmitz** [comment]
I checked and couldn't find that string on Transifex.

What's the original English string?

**Comment by PtJade-Ceramic** [comment]
> I checked and couldn't find that string on Transifex.
> 
> What's the original English string?

<img width="479" alt="image" src="https://github.com/user-attachments/assets/f0269dc4-c65a-436f-8a4e-25411db499fb">

**Comment by Jojo-Schmitz** [comment]
Ok, found it. And that little circle at the end of the Chinese string is not the Chinese equivalent for a dot or full stop?

**Comment by PtJade-Ceramic** [comment]
> Ok, found it. And that little circle at the end of the Chinese string is not the Chinese equivalent for a dot or full stop? It seems to be used as that all over the place

![image](https://github.com/user-attachments/assets/4cb8fd34-bc8f-4e3d-a234-fa97ce37746e)
The string has just been corrected at https://app.transifex.com/musescore/musescore/translate/#zh_CN/instruments/434343511?q=translation_text%3A%E7%94%B7%E8%B0%83 .

**Comment by Jojo-Schmitz** [comment]
Ok, found it. And that little circle at the end of the Chinese string is not the Chinese equivalent for a dot or full stop?

**Comment by Jojo-Schmitz** [comment]
So it is not about the little circle but a missing space? If so: that is missing in several other places too

**Comment by Jojo-Schmitz** [comment]
And it is the same 'typo' in the other 2 Chinese variants

**Comment by bkunda** [comment]
> The string has just been corrected at https://app.transifex.com/musescore/musescore/translate/#zh_CN/instruments/434343511?q=translation_text%3A%E7%94%B7%E8%B0%83 .

Thanks for taking care of this @PtJade-Ceramic!

**Comment by Jojo-Schmitz** [comment]
As mentioned: there are many more strings translated without a space, Alto voice, Soprano voice and many more, just 'fixing' the Chinese translation of Tenor voice and just in one of 3 Chinese variants is not cutting it at all.
Then again this isn't really worth an issue on GitHub in the first place...

**Comment by Jojo-Schmitz** [comment]
@PtJade-Ceramic better join the discord server and there the translation is channel
