### ISSUE TITLE
Muse Sounds Cymbals Are Too Toned

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25269]
### Your idea

The Muse Sounds suspended cymbal, tam-tam, and triangle all have a very bell-like tone, with less of an indeterminate pitch. This is not useful for most purposes. The Tam-tam and suspended cymbal are used for their hissing sound, not any ringing.

### Problem to be solved

The pitched sounds of these instruments are very distracting when played in a full score.

### Additional context

These Muse Sounds were likely recorded on very large cymbals and Tam-tams in an effort to get a powerful sound, but such large instruments are almost never used ordinarily.
Please also see Issue #25268

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
Thanks for this suggestion! Because this is a MuseSounds issue, we'd be grateful if you could please contact the MuseHub support team with your request: https://support.musehub.com/hc/en-gb/requests/new.

Many thanks!
