### ISSUE TITLE
Wrong icon in the Accidentals palette

### ISSUE THREAD

**Issue by FrancRos31** [musescore/MuseScore#25266]
### Bug report
(edited after @bkunda comment)

The "Add square brackets" element in the Accidentals palette has the wrong icon
![2](https://github.com/user-attachments/assets/8deb0214-625a-44e7-9e1c-82daaf512af4)

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment]
I think the square bracket icon is actually the wrong icon: it seems to be `IconCode::Code::BRACKET`, which is apparently for brackets at the start of a staff, while the correct icon would be `BRACKET_PARENTHESES_SQUARE` (strange name…).

About the sizes: each palette has its own scale factor, and cells can also have individual scale factors. A designer should specify the desired scales.

Once the desired scales are clear, this should be easy to implement for anyone who wants to try that; see `palettecreator.cpp`.

**Comment by FrancRos31** [comment]
> About the sizes: each palette has its own scale factor, and cells can also have individual scale factors. A designer should specify the desired scales.
> 
> Once the desired scales are clear, this should be easy to implement for anyone who wants to try that; see `palettecreator.cpp`.

Do you know if there's some open issue for this?

**Comment by bkunda** [comment]
So of the two issues here, I think this is the more pertinent one:

- Correct icon needs to be used

As to whether they should be moved out of "More", we already have a (nicer) way of parenthesising accidentals via the Properties panel. If someone wants to add them to the top level of the accidentals palette, it's easy enough to do this too. 

In light of this, I don't think they need to be moved out of "more" by default.

**Comment by WhyMeAgain233** [comment]
Thanks for assigning me this issue! I'm looking forward to working on it.

**Comment by WhyMeAgain233** [comment]
Sorry for the long delay. I've been a little busy with my schoolwork recently, and it took some time to understand the code structure and to figure out where the issue is located.

**Comment by cbjeukendrup** [comment]
No worries, thanks for the PR! My `palettecreator.cpp` hint was a bit less specific than I had realised at first. So, therefore even more, good job!
