### ISSUE TITLE
Minor update "getting started" flow

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#25276]
Page 2 of the "Getting started" flow requires the following updates:

1. New image
2. Updated URL for primary action button. Should point to: https://youtu.be/L8OdWHOjL8c
   
<img width="634" alt="Group 2087328080" src="https://github.com/user-attachments/assets/53a3afee-0854-4c92-bcb1-d75b92acba5d">

**Comment by MarcSabatella** [comment]
Is that lack of space meant to be product-wide?  It still shows with the space in the mixer, playback setup dialog, and probably elsewhere.  Should we all start using the new spelling in our communications / documentation etc?
