### ISSUE TITLE
Musescore 4.4.2 won't start

### ISSUE THREAD

**Issue by Lenbus** [musescore/MuseScore#25272]
### Issue type

Crash or freeze

### Description with steps to reproduce

Somehow MuseScore suddenly stopped starting. With just the exact same version it worked before. 
But now, just the welcome screen appears but then nothing happens.

A common thing I have encountered several times in the past and that occurs here as well: The MuseScore4.exe can not be aborted by the Task Manager. When I try to end the task, just nothing happens. 

Attached you find the logs. It seems, there is a problem with QT/QML.

### Supporting files, videos and screenshots

[MuseScore_241022_000145.log](https://github.com/user-attachments/files/17467345/MuseScore_241022_000145.log)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2 (but somehow I have found 4.2.1 on my PC as well, which does not start neither)

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Lenbus** [comment]
Update: This bugged me so much, that I did a complete re-install of MuseHub (looking completely different now) and MuseScore. Now it works again...

**Comment by cbjeukendrup** [comment]
This seems indeed the kind of rare sporadic error where a reinstall helps. Given that there are no similar reports, I think this is a one-off error. 

I'll leave this open for now so that it gets seen during bug triage later today, but unless anyone thinks otherwise, I think this can be closed.

> MuseHub (looking completely different now)

Indeed, if you now reinstall Muse Hub, you get version 2.0 nowadays. Version 1.0 does not yet automatically update to v2.

**Comment by bkunda** [comment]
Given @cbjeukendrup's assessment, I think we can close this and re-open if it can be reliably reproduced.
