### ISSUE TITLE
Performing initial build, addressing build error Cannot find <ogg/ogg.h>

### ISSUE THREAD

**Issue by chrisroode** [musescore/MuseScore#25289]
Hello,
I am onboarding myself to start helping with museScore.  I encountered this error when performing a fresh build of the code.  Error message below.

```
In file included from /Users/chrisroode/eclipse-mc/museScore/MuseScore/src/framework/audio/thirdparty/flac/flac-1.4.3/src/libFLAC/stream_decoder.c:45:
In file included from /Users/chrisroode/eclipse-mc/museScore/MuseScore/src/framework/audio/thirdparty/flac/flac-1.4.3/src/libFLAC/include/protected/stream_decoder.h:38:
/Users/chrisroode/eclipse-mc/museScore/MuseScore/src/framework/audio/thirdparty/flac/flac-1.4.3/src/libFLAC/include/private/ogg_decoder_aspect.h:36:10: fatal error: 
      'ogg/ogg.h' file not found
#include <ogg/ogg.h>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [src/framework/audio/flac/CMakeFiles/flac.dir/flac-1.4.3/src/libFLAC/stream_decoder.c.o] Error 1
make[1]: *** [src/framework/audio/flac/CMakeFiles/flac.dir/all] Error 2
make: *** [all] Error 2
```

I wanted to open discussion on this type of error because I suspect it might have to do with how my system is configured.  I wanted to check if there was a preferred way to go about resolving this dependency issue.  I'm assuming from the folder path, 'framework/audio/thirdparty' that this code has been incorporated into this repository, and I would like to keep consistent with more experienced developers on my configuration.

**Comment by krasko78** [comment]
Hello and welcome! :) Unfortunately I cannot help you with the error you are having but are you following the oficial docs? I think this page is a good starting point: [Set up dev environment](https://github.com/musescore/MuseScore/wiki/Set-up-developer-environment). Once done with the current page, move on to the next one using the links in the right-hand portion of the page, and in particular under the "Compilation" section. Good luck!

**Comment by chrisroode** [comment]
Thanks for answering.  Turns out I was using the docs on the .org site.  Once I looked at the wiki in github, everything started working fine.

**Comment by chrisroode** [comment]
I'll call this closed.
