### ISSUE TITLE
Musesound manager windows

### ISSUE THREAD

**Issue by zef126** [musescore/MuseScore#25288]
### Your idea

It would be better if there was simply musesound manager on Windows

### Problem to be solved

Musehub is big and full of adds

### Prior art

You already know the linux dist.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
Closing as this is not technically a MuseScore Studio issue (it's related to MuseHub / MuseSounds, which is outside of our control).
