### ISSUE TITLE
Request for Phonetic Symbols

### ISSUE THREAD

**Issue by LittleWishy** [musescore/MuseScore#25290]
### Your idea

Hi all,
I'm noticing that the default Edwin font doesn't exactly support all types of characters yet, which is understandable, but I feel like there's one that needs to be added/implemented. The IPA (International Phonetic Alphabet) is a set of symbols that represent phonemes from any human language. It would be beneficial if the Edwin font also included IPA symbols, if the composer solely wished to work with specific vocal sounds and textures for their pieces. 

### Problem to be solved

You can input IPA symbols by copying/pasting from elsewhere, but the font is inconsistent, as shown below. 
<img width="1084" alt="Screenshot 2024-10-23 at 11 36 50 AM" src="https://github.com/user-attachments/assets/75bf5764-fe09-4065-9fd5-6588892c299b">
It would look nicer if these symbols looked uniform across the whole score. Having two different fonts clash next to each other would look awkward. 

### Additional context

Additionally, please consider looking over the displays on the Master Palette. I can't see symbols that the Edwin font doesn't support, even though the cells are there. 

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment]
This is a huge character set and an extremely large task; it would be much better to use a specialised IPA font, as listed e.g. [here](https://www.internationalphoneticassociation.org/content/ipa-fonts).

We will certainly not be doing this in Edwin in anything like the near future (if ever), I'm sorry to say.

**Comment by MarcSabatella** [comment]
Meanwhile, MuseScore Studio does include FreeSerif and FreeSans, which are much more complete fonts that do include IPA symbols.  So no need to copy/paste, just select one of those fonts for your text using IPA.

**Comment by LittleWishy** [comment]
Fair enough. But my point about the displays in the special characters window still stands. (Using Cyrillic as an example)
<img width="696" alt="Screenshot 2024-10-23 at 12 29 01 PM" src="https://github.com/user-attachments/assets/1b51cea1-15ff-439e-9a72-b6b48bd9f07f">
