### ISSUE TITLE
Expression text overlapping a barline

### ISSUE THREAD

**Issue by FrancRos31** [musescore/MuseScore#25304]
### Your idea

![1](https://github.com/user-attachments/assets/8d748c8c-8def-42db-aec0-ff2861e5f19a)
This is the normal behaviour of expression text overlapping barlines.

There is a workaround for this: add a frame to the text and assign the canvas color to the border and the fill color.
![2](https://github.com/user-attachments/assets/c2afe59e-8c9e-407a-a775-adb5d86cff10)

### Problem to be solved

Is there a way to make this possible without a workaround?

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment]
This is just a subset of this: https://github.com/musescore/MuseScore/issues/22646
