### ISSUE TITLE
Opt+Shift+...  shortcuts not working on Mac 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#25314]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

https://musescore.org/en/node/370772

> The commands **move pitch down diatonically** and **move pitch up diatonically** do not work right now on mac. I have already tried resetting the command to the original version to see if that would fix it, but it did not.

--

1. Select note
2. Using **Opt+Shift+Up/Down** arrow, try to move note diatonically

--------------------------------------------------------------------------------------------
**All shortcuts** that contain **Opt+Shift** don't work on Mac (Add text: Tempo marking - Opt+Shift+T;
Insert bars before selection - Opt+Shift+I)

See https://github.com/musescore/MuseScore/issues/25314#issuecomment-2439504994 https://github.com/musescore/MuseScore/issues/25314#issuecomment-2440076907

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

Yes, this used to work in **MuseScore 4.4.2**

### Operating system

macOS

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
Works in #25273

**Comment by Nazaretto** [comment]
@DmitryArefiev I've noticed that all key binding that have "Option" key in the combination are not working as well.

**Comment by garbusbeach** [comment]
I've got the same issue, after update to 4.4.3
(OS: macOS 15.0, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367)

**Comment by RustyCat-1** [comment]
I noticed that when one tries to, in Preferences, set a keybind that uses Opt+Shift, it doesn't register the shift. For example, I tried to register the keybind "Opt+Shift+Up", but it detected "Opt+Up" instead.
