### ISSUE TITLE
Refine Undo/Redo history dialog

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#25327]
Thanks to @rpatters1's work in #24744, we now have an Undo/redo history dialog: 
<img width="300" alt="Scherm­afbeelding 2024-10-27 om 11 35 32" src="https://github.com/user-attachments/assets/81dd7613-8f72-4053-a345-8a2632095223">

Some more refinements are to be made to this dialog.

### UX/UI
There is no distinction between undo items and redo items. Here is a graphical explanation of how it currently works, in the case that you have already undone three actions:
<img width="479" alt="Scherm­afbeelding 2024-10-27 om 11 39 04" src="https://github.com/user-attachments/assets/27362828-fd0b-480a-a531-f96e367f6c75">
When selecting the e.g. topmost action, that action _and_ the two actions between the topmost and the current state. I.e. this dialog only lets you "time-travel", and _not_ cherry-pick single actions (which would be out of scope and not always possible).

Ideas:
- Let the OK button indicate what's going to happen: "Undo 1 action" or "Redo 3 actions"
- It should be clearer which row in the dialog refers to the "current state". Since the current state refers to a point in time rather than to an action, I would argue it should be its own special row, but @rpatters1 is against that.
- If you select e.g. the 5th action below the current state, that means that all 5 actions between the current state and the selected row will be undone; so I think all of them should be highlighted to indicate that. 
- The current design is basically a copy of Dorico 5's undo history dialog. Instead, we might want to look at Finale's design, which consists of two columns: one for undoing, one for redoing. Although the single-column design is perhaps nice in theory, the two-column design would probably be much more understandable. 

### Technical
- I think `NotationUndoStack::undoRedoToIdx` functions slightly weirdly: I would expect that if `stack->currentIndex() == idx`, then nothing happens. Instead, it currently redoes one command in that case. To prevent confusion in the future, that should perhaps be changed.
- Instead of doing a lot of logic in QML, it would be more efficient to rewrite `UndoRedoHistoryModel` as a `QAbstractListModel`. I've made a start at this; my work-in-progress is here: https://github.com/musescore/MuseScore/compare/master...cbjeukendrup:undohistory/qabstractlistmodel
However, if we switch to a two-column approach, that will obviously have a big influence on the model implementation.

**Comment by rpatters1** [comment]
Also, see the Finale dialog shown in #24509, which uses separate columns for Undo and Redo. This may be a clearer solution,

**Comment by cbjeukendrup** [comment]
FWIW, I made some sketches myself too:
<img width="1316" alt="image" src="https://github.com/user-attachments/assets/b0ffa78f-eb90-4e0f-a5a4-e28b77ad1e73">
but let's wait what the real designers say.

**Comment by cbjeukendrup** [comment]
For the record: inspired by other creative apps outside the music notation world, we decided to turn the thing into a side panel rather than a dialog. This makes it more conveniently usable, and may make it easier to figure out what it does because you can immediately see the result. Compared to Finale's design, it has the advantage that it does not confront the user with the concept of undo and redo stacks.

Final design by @avvvvve; implementation in #25389.
![Undo history panel](https://github.com/user-attachments/assets/38ee8a5e-2060-4b68-831c-e6fc28692ef4)
