### ISSUE TITLE
adding in support for vst au rtas etc. instruments in all platfforms

### ISSUE THREAD

**Issue by tmm88** [musescore/MuseScore#25331]
### adding in support for vst au rtas etc. instruments in all platfforms

**my idea is basically to:**
- *adding in built support for built in plugins into musescore in all platfforms for the sake of supporting vst instruments drectly (without having to use jack midi)*

### Problem to be solved

**since musescore is particularly lightweight it can:**
- *end up being used for producing any genre or subgenre of music, or at least aiding at prototyping such thing*

### Prior art

**similar functionalities in tools like:**
- *dorico*
- *sibelius*
- *finale*

### Additional context

nothing to declare

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment]
VST is already supported. 

Audio Units not, but that's macOS-only and almost all plugins that are available as AU are also available as VST. Are there specific plugins, that would be valuable to use in MuseScore, that are only available as AU? 

I didn't know RTAS, but it seems to be both outdated and proprietary to ProTools, i.e. it is not technically possible (nor legally) for other applications like MuseScore to host RTAS plugins.

**Comment by tmm88** [comment]
I acknowledge everything you are saying and you are doing. please don't impersonify paul jeukendrup, from the institute of sonology, former lead sound engineer of karlheinz stockhausen. otherwise i will report that to the head of the institute of sonology, namely kees tazelaar
