### ISSUE TITLE
adding in an automated mean to convert kontakt sample libraries into musescore sample libraries automatically

### ISSUE THREAD

**Issue by tmm88** [musescore/MuseScore#25332]
### adding in an automated mean to convert kontakt sample libraries into musescore sample libraries

**my idea is basically:**
- *adding in an automated mean to convert kontakt sample libraries into musescore sample libraries*
- *doing it with other sample formats as well*

### Problem to be solved

**problemas to be solved:**
- *alllowing users to expand their libraries faster, without needing to wait for the release of another version*
- *while doing this, tracking which libraries are users installing, and allowing that to be featured in straight away into musescore hub*

### Prior art

- *some earlier features, dating from the late 2000s, alowing ableton to do the versy same thing*

### Additional context

- *nothing to declare*

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
This is more within the scope of MuseHub / MuseSounds. Requests for new libraries can be made by contacting Customer Support: https://support.musehub.com/hc/en-gb/requests/new.
