### ISSUE TITLE
black theme for the sheet

### ISSUE THREAD

**Issue by nobody459** [musescore/MuseScore#25340]
### Your idea

it would be great if the black theme could apply to the sheet (the "page")  too.

### Problem to be solved

it would be easier on user's eyes.

### Additional context

thanx for all the good work !

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by nobody459** [comment]
PS : i ve seen we can change the colour of the sheet to make it black but the problem is that writing black on a black paper is impossible to read

**Comment by cbjeukendrup** [comment]
In Preferences > Appearance, there is an option for this at the bottom:
<img width="818" alt="Scherm­afbeelding 2024-10-27 om 19 13 49" src="https://github.com/user-attachments/assets/d7b9979f-7310-4842-ab1a-059bb3fbb6f4">
