### ISSUE TITLE
Downloading .MSCZ

### ISSUE THREAD

**Issue by BuggZugg** [musescore/MuseScore#25341]
### Your idea

When I download an .MSCZ, it works, but it's coupled with opening on MS software.
I can't download without opening. This is ridiculous. When downloading, it is writen : Open in MuseScore.
I should open it when I want.

### Problem to be solved

Give us the way to download without opening MS.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment]
I'm not seeing this behaviour. When I click the Download button, and choose MuseScore file, then it just downloads the file. And I see a separate "Edit on Desktop" button; only that button opens MuseScore Studio.

But perhaps they are A/B-testing something, which would mean that you and I are intentionally seeing different behaviour. 

I'll forward this to the MuseScore.com team.

**Comment by bkunda** [comment]
This does seem like an issue on the musescore.com end. Thanks for forwarding this on @cbjeukendrup.
