### ISSUE TITLE
Better implode/explode

### ISSUE THREAD

**Issue by Nicholas43983** [musescore/MuseScore#25347]
### Your idea

- Choose how many parts to explode/implode, and where
- By default, explode will only extend to like instruments, and if notes exceed parts, then they will group without interuppting other lines (note the piano is preserved on image 1)
- Parts, when sharing the same rhythmic value, implode onto the same voice AND without duplicates (the whole note is on voice 2 instead of 3, no duplicate notes on the same voice, imagges 2 and 3)
![image](https://github.com/user-attachments/assets/a9f439e7-6f06-4bd1-8a27-c2bf82310e38)
![image](https://github.com/user-attachments/assets/3e85a325-4f5a-4a94-952c-7750b5791226)
![image](https://github.com/user-attachments/assets/0df5993b-4523-4106-ad01-82c786e1b346)

### Problem to be solved

- Taking expanded parts and collapsing them back for revision on the same voice, making writing harmonies more convenient
- Preventing exploding a melodic line into percussion
- Overall non-destructive transformation of a score, that persists between saving and clearing history

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Nicholas43983** [comment]
Basically Explode to relevant/select parts and Implode to one voice/select parts

**Comment by MarcSabatella** [comment]
These features pretty much already exist.  For explode, select a specific set of staves to limit the exploding to just those.  For implode, run it twice to combine the voices into one where possible.
