### ISSUE TITLE
Autoplacement of the canvas is too rigid in note input mode

### ISSUE THREAD

**Issue by FrancRos31** [musescore/MuseScore#25354]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. open a symphonic score with more than one page
2. zoom to 200%
3. move the canvas in the zone between two pages
4. select a measure at the end of the system on the left page (or at the beginning of the system on the right one) and press N to open note input mode (not necessarily the very last or first measure)
5. insert some quarte notes
Actual behaviour: the canvas autoplaces to display only the left page (or the right one).
Expeceted behaviour: the canvas doesn't move when inputting notes.

Sometimes, in an orchestral score, you need to see the last measures of the left page and AT THE SAME TIME the first measures of the right page because a system occupies a page. It would be much better if the pages stay still during this moments.

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

I was unable to check

### Operating system

Window 10 Pro

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by FrancRos31** [comment]
This is more a feature request than a bug, I think. But there's also that bug that I don't know how to reproduce.

**Comment by MarcSabatella** [comment]
FYI, there are already two relevant features that exist to help with situations like this:

1) you can disable “pan score automatically” via the toolbar settings menu
2) you can switch to continuous view, which presents one very wide page

**Comment by FrancRos31** [comment]
Thank you, I'm closing this.
