### ISSUE TITLE
Allow brackets on as many objects as possible

### ISSUE THREAD

**Issue by iainhallam** [musescore/MuseScore#25365]
### Your idea

Allow symbols, and as many other objects as possible, to be given either curved or square brackets.

### Problem to be solved

When preparing editorial scores, it's important to be able to distinguish the contributions of the editor from the original score. Many people use square brackets for this, but I've seen some use rounded parentheses (also seen these used to indicate optional symbols like breath marks). At present, MSS can add parentheses to a note head, and parentheses and square brackets to an accidental, but neither to a symbol. Options for without, parentheses, and square, should be available for all these and more.

### Prior art

ISTR that Sibelius can do this for most objects, and I'm sure it's a feature in Dorico.

### Additional context

I've searched the issue tracker for this, but can't find anything quite right at the moment,

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by iainhallam** [comment]
But apparently my searching was poor, because I've just found #23785.

**Comment by andy-lyttle** [comment]
Handbell notation also frequently uses a combination of (parentheses), [square brackets], \<angle brackets\> and {curly braces} to indicate notes that should be omitted depending on which range of bells are available. For example, a 5-octave choir might play all the notes written, while a 3-octave choir would omit notes that don't exist in their range but also any notes marked in brackets that are in their range. Some text somewhere explains who should omit which notes.
