### ISSUE TITLE
developing a vst version of musescore

### ISSUE THREAD

**Issue by tmm88** [musescore/MuseScore#25363]
### developing a vst version of musescore

**my idea is basically to;**
- *develop a vst version of musescore*

### Problem to be solved

**my idea is basically to;**
- *provide any daw or any software instrument with possibilities for taking advantage of notation software throughout embedding musescore into a vst or audio units thing*

### Prior art

**prior art is:**
- *logic pro score editor*
- *cakewalk sonar score editor*

### Additional context

**nothing to declare**

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
This is an extremely vague proposal and doesn't really make a lot of sense (MuseScore Studio _supports_ VST, but couldn't ever be a VST itself...).

I will note that we've been fielding numerous feature requests of similarly vague or irrelevant nature from this account. (see also https://github.com/musescore/MuseScore/issues/25331, https://github.com/musescore/MuseScore/issues/25331, https://github.com/musescore/MuseScore/issues/25352). Unfortunately this account will need to be temporarily blocked as reading and trying to make sense of these issues is wasting a lot of our time.
