### ISSUE TITLE
I'm struggling to compile MuseScore.

### ISSUE THREAD

**Issue by yblacky** [musescore/MuseScore#25361]
Hi guys,

I'm trying to implement a new feature in MuseScore. However, I can't compile MuseScore, so I can't test whether what I've edited works. I've actually followed all the steps and installed the required software. I've tried it in IntelliJ and CLion. I enter the command via the QT8.0 Windows console. I get the following error code:

```
CMake Error at buildscripts/cmake/SetupQt6.cmake:60 (find_package):
  By not providing "FindQt6StateMachine.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt6StateMachine", but CMake did not find one.

  Could not find a package configuration file provided by "Qt6StateMachine"
  with any of the following names:

    Qt6StateMachineConfig.cmake
    qt6statemachine-config.cmake

  Add the installation prefix of "Qt6StateMachine" to CMAKE_PREFIX_PATH or
  set "Qt6StateMachine_DIR" to a directory containing one of the above files.
-- Configuring incomplete, errors occurred!
  If "Qt6StateMachine" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:158 (include)


CMake Error at build.cmake:232 (message):
  Configure step failed with status 1.  See output above for details.
```
  
  
  Hope someone can help me to solve that.
  I've been trying some hours.
  
  Best regards

**Comment by yblacky** [comment]
I do get the same error in QT Creator

**Comment by cbjeukendrup** [comment]
See https://github.com/musescore/MuseScore/wiki/Install-Qt-and-Qt-Creator; at the moment you still need Qt 6.2(.4), and you need `Qt State Machines` and `Qt Network Authorization`.
