### ISSUE TITLE
Not all alto saxophone sounds (Muse Sounds) are played with the "nonvib" playing technique.

### ISSUE THREAD

**Issue by jp22137** [musescore/MuseScore#25377]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

Does anyone know what might be causing the absence of sound playback for notes from A5 to E♭6 on the alto saxophone using the Muse Sounds set and the "nonvib" technique (Text -> Staff Text)? How can this issue be fixed?

### Supporting files, videos and screenshots

-

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

I was unable to check

### Operating system

Windows 10, Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
This sounds like a MuseSounds-specific issue. We'd be grateful if you could please contact the MuseHub support team with your request: https://support.musehub.com/hc/en-gb/requests/new.

Many thanks!
