### ISSUE TITLE
Hidden notes (in chord) automatically hides all ledger lines but not stems?

### ISSUE THREAD

**Issue by bombasticbobby** [musescore/MuseScore#25378]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

So there are basically two bugs I've found out while using Musescore Studio 4:
1. It's good that glissando can spread staves now, e.g. in piano. However, it does not play in sequence during playback (LH & RH would play simultaneously). 

(so, I had a workaround for my midi files, which is to add the entire chord in one hand, with hidden notes instead)

...which leads me to the 2nd bug:
2. When I hide the top notes, it automatically hides the ledger lines, regardless of whether there are notes beneath that need them. Also, it does not hide the extended stem which is very weird...

[see screenshot above, left screen is Musescore interface, right screen is exported PDF]

Hope musescore can fix this soon!

### Supporting files, videos and screenshots

![Screenshot 2024-10-30 114745](https://github.com/user-attachments/assets/28127640-04e2-4910-839d-50203a0483b5)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

No

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
(Please file each bug or feature request separately, as it makes it much easier to track them. I'll consider the second one here):

It is certainly odd that hiding one note should hide all ledger lines on that chord; only those which are required _only_ by that not should disappear.

Whether or not the stem should disappear or not has been brought up often and is a matter of opinion and context - basically, we need a way to specify it
