### ISSUE TITLE
Mac Delete key no longer works In MSS 4.4.3 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#25373]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

https://musescore.org/en/node/370950

> Until yesterday the **delete key (the one with the "x" in the icon)** would delete a selected object (e.g., note, chord symbol, formatting indicators, etc.). Today this **no longer works**. The delete key to which I'm referring is available on Mac keyboards that include a numeric keypad (please see attachment). The "usual" delete key still works.
> 
> I discovered this anomaly when I started working on my first 4.4.3 lead sheet (attached) this morning.
> 
> This just in... The keyboard shortcut to add a tempo indication no longer works in 4.4.3 on my Mac (Sonoma 14.6.1). This is the stock MuseScore shortcut

### Supporting files, videos and screenshots

<img width="954" alt="Mac Keyboard" src="https://github.com/user-attachments/assets/da4e6870-dcc4-498d-94da-52e5a1b5c765">

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

Yes, this used to work in **MuseScore 4.4.2**

### Operating system

mscOS

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
Confirm on my side ( Mac13.6 laptop with PC full keyboard). **Doesn't occur** in **4.4.2**

Works in #25273

FYI @bkunda

**Comment by FrancRos31** [comment]
Check #25321.

**Comment by FrancRos31** [comment]
No, actually, don't have a Mac laptop, but I think @RhinoHaggis can, maybe?

**Comment by scorster** [comment]
Related .org post

https://musescore.org/en/node/370783
