### ISSUE TITLE
Sharp Symbol Issue in Key Signature Palette

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25391]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

Hovering over the Key Signatures in the palette shows a strange symbol in place of the sharp symbol (#) 
This appears in every place in the palette where a sharp should appear.
The flats appear normally.

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/c2b6d2e8-4c0a-48d6-84fa-c2300127edf2)

### What is the latest version of MuseScore Studio where this issue is present?

Version: 4.4.3.242971445   Revision: eb6b367

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
Thanks for reporting!  This is already known - see https://github.com/musescore/MuseScore/issues/24445 - and just awaiting being able to move to a newer version of the Qt libraries.
