### ISSUE TITLE
Pizz. Playback Issue

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25390]
### Issue type

General playback bug

### Description with steps to reproduce

In the passage, the strings experience difficulty in going from the double whole note to the pizz. eighths. They instead play a forte pizz. on top of a bowed forte eighth.

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/80f8a9ec-35eb-4e35-b438-ba85cdf6baf6)

### What is the latest version of MuseScore Studio where this issue is present?

Version: 4.4.3.242971445   Revision: eb6b367

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

It would help if GitHub allowed score files to be posted. I tried to include the score file itself here, but was informed that the file type is not supported.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
For future reference, you can attach scores here by compressing as .zip files
[StringTest.mscz.zip](https://github.com/user-attachments/files/17601030/StringTest.mscz.zip)


As this is a MuseSounds specific issue, I will log it with their team

In the future, please report MuseSounds specific issues to MuseHub support team: https://support.musehub.com/hc/en-gb/requests/new.

**Comment by Fourniture** [comment]
Thank you. I was not aware that this is a MuseSounds issue...
I thought it had to do with playback coding.

**Comment by MarcSabatella** [comment]
The simple way to check is to compare Muse Sounds vs MS Basic.  If it only affects Muse Sounds, then it is a Muse Sounds issue.

**Comment by zacjansheski** [comment]
Logged with MuseSounds
