### ISSUE TITLE
Grace note should not disappear when deleting a normal note and only selecting the normal note.

### ISSUE THREAD

**Issue by VighneshJadha** [musescore/MuseScore#25393]
### Your idea

A grace note should not disappear when a normal note is deleted/turned into a rest. When you add a grace note to a normal note, only select the normal note, and delete it/turn it into a rest, the grace note also disappears. This should not happen. The grace note should delete when the normal note is selected with the grace note, but not if only the normal note is selected.

### Problem to be solved

This is very useful in composing and transcribing. Classical engravers can cheat. I am working on a score of Chopin's waltz discovered on 26/10/2024. This voice 1 grace note appears here. Note that on beat 1, there is an invisible rest in voice 1.
![image](https://github.com/user-attachments/assets/38e40805-3cde-4c53-a4f5-321e448127c7)
The current workaround is to add a note in voice 1, add a rest from the masterpalette or in voice 3 and make the other voice 3 rests invisible, make the voice 1 note invisible and turn off its playback.
![image](https://github.com/user-attachments/assets/f5871b8c-52bc-4ff6-9f20-c646fc047ed7)

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by DaddyLudwig** [comment]
A simpler way to do what you want in that measure would be to add the grace note to the voice 2 note and then press X to flip the grace note to be stem up.

**Comment by SteveBlower** [comment]
>What if grace notes need to be added to both voices?

Normally, the grace note on the lower voice would have stem down, the one on the upper voice would have stem up.

![Screenshot 2024-11-01 174450](https://github.com/user-attachments/assets/4b526908-d9e7-4bdd-9399-64fc9d08985c)

**Comment by oktophonie** [comment]
Do a grace note after from the previous note.
At this point this request is just noise, so I'm closing it.

**Comment by VighneshJadha** [comment]
> previous note.

How to display it after the barline?  And what if it is needed at the start?
