### ISSUE TITLE
Option to export PDFs with transparent background

### ISSUE THREAD

**Issue by santiclear** [musescore/MuseScore#25407]
### Your idea

The ability to export SVGs with transparent background has already been added (https://github.com/musescore/MuseScore/pull/19996). Could this option be added also to PDF export?

### Problem to be solved

All pdfs exported with Musescore Studio up to 4.4.3 have a solid colour background

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by Jojo-Schmitz** [comment]
Cane up again in https://musescore.org/en/node/369743

**Comment by LeoTaoeee** [comment]
This is @Dleo from discord, please assign this to me and my partner AkiraTatsuya (thats his github username) if possible
