### ISSUE TITLE
Problems with Guitar Harmonics

### ISSUE THREAD

**Issue by ericglam** [musescore/MuseScore#25411]
### Issue type

General playback bug

### Description with steps to reproduce

Guitar Harmonics will play in voice 1 but none of the other voices will play as in voice 2 in the attached example. (actually I am finding it very difficult to play it on an actual guitar, but still Musescore 4 should allow you to put it in the notation)
The example is using a Muse Sound Acoustic Steel Guitar in Musescore Studio 4.4.3.24.
I expect it to play voice 2 even if it plays in Harmonics though I would prefer it to play the same as everything else in voice 2.
There is no real work around except to create another staff just for the Harmonics.

Also the tab does not play the harmonics correctly at the right place on the fret  but the notation staff does.
The work around is to create 2 sets of notes on each of the linked staff one that prints correctly and one that plays correctly hiding the other set of notations that you do not want to see and not playing the one that plays incorrectly. 

Finally I have to use an odd symbol to get the tablature to show the standard symbol for harmonic.  This has been asked for by others for a while: https://musescore.org/en/node/81366  and is the workaround I am using in the attached.

All these problems are in the third measure of the attached.   The notes that will not play are in green.

![Guitar Harmonic Problem](https://github.com/user-attachments/assets/5039c944-13fd-4baf-9eca-5ebcfb84a8a6)

Musescore 4 is a vast improvement over the previous versions of Musescore.  I can use work arounds to get this to play correctly.

### Supporting files, videos and screenshots

[Guitar Harmonic Problems.zip](https://github.com/user-attachments/files/17609481/Guitar.Harmonic.Problems.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

No.

### Operating system

OS: Windows 10 Pro

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
The range of the MuseSound Acoustic Steel Guitar harmonics don't go to D2 (they go as low as B#2)  So it won't play in voice one either.

For reporting issues with MuseSound specific instruments, please report to MuseHub support team: https://support.musehub.com/hc/en-gb/requests/new
