### ISSUE TITLE
Fingering focus and selection

### ISSUE THREAD

**Issue by mike-lev** [musescore/MuseScore#25413]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

After ending a fingering input through pressing ESC it remains focused but looses its selection, therefore its position cannot be adjusted.
It is always necessary to click somewhere else first then select it again.
I could not remember such behavior prior to version 4.4.

### Supporting files, videos and screenshots

[Unbenannte Partitur 2024-11-03 12-59-34.zip](https://github.com/user-attachments/files/17610261/Unbenannte.Partitur.2024-11-03.12-59-34.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by krasko78** [comment]
I have a PR for this one. Someone please assign it to me. Thanks!

**Comment by krasko78** [comment]
The scope of this bug is actually larger: any text (not just fingering) is not moveable after editing it and pressing ESC.

**Comment by krasko78** [comment]
**QA:** [24485](https://github.com/musescore/MuseScore/issues/24485) will have to be re-tested with this one. Thanks!
