### ISSUE TITLE
MS4.4.3 crashes when I drag a range selection that contains a guitar bend

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#25424]
### Issue type

Crash or freeze

### Description with steps to reproduce

Open the score [attached to this .org thread](https://musescore.org/en/node/371216)
Range select measure 1
Drag the selection up or down

Result: MuseScore Studio 4.4.3 abends.

Confirmed on Windows in the same thread. 

**UPDATE 2024-11-04:** I tested several times and MuseScore 4.4.3 does NOT crash when I drag a list selection that contains a guitar bend. Doesn't matter if I drag north, south, east or west.

### Supporting files, videos and screenshots

Sorry. Don't have time to make a video right now. But it wouldn't show anything but the screen disappearing.

### What is the latest version of MuseScore Studio where this issue is present?

MS 4.4.3

### Regression

Don't know. I haven't worked much with bends in MS4.

### Operating system

MacOS 13.5.2 and Window 11 / 4.4.3

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cadiz2** [comment]
Works with version 4.3.2.
Crash/regression with version 4.4.0

**Comment by mercuree** [comment]
Another crash

https://github.com/user-attachments/assets/bf10ecc8-162f-4377-a62c-48529d1b27c1

**Comment by scorster** [comment]
I've updated my original post to mention that:

MuseScore 4.4.3 does NOT crash when I drag a list selection that contains a guitar bend. Only crashes with a range selection.
