### ISSUE TITLE
Undo and Redo controls outside of window boundaries on startup

### ISSUE THREAD

**Issue by j-raybaudserda** [musescore/MuseScore#25421]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

*Nota:* This is a similar issue as the one described in #12813 with a few caveats and additional precisions.

When starting Musescore and either creating a new score or opening an existing one, the redo and undo buttons as well as the zoom level indication appear outside of the window boundaries. Closing the current score to open a new one, or resizing the window resets them to their expected positioning, thus it looks like the placement of said elements is faulty only for the very first editor window opened on startup.

**Steps to reproduce**

1. Open Musescore
2. Create a blank score / Open an existing score from the Scores selection screen
3. Resize the window / Close the current score to open a new one

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/6e3b40d8-cb50-46af-a0fc-d23467dd967a

https://github.com/user-attachments/assets/b9e0e3cd-bf27-4bf0-b734-d77fba7eefb2

<img width="1280" alt="MS4_UI-Controls-Outside-Window-Boundaries" src="https://github.com/user-attachments/assets/28627c48-e9c9-4ffd-b733-597caaf85f64">

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 12.7, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOs 12.7.6

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by scorster** [comment]
For the record, those icons appear in the Toolbar here in 4.4.3-242971445 on Mac OS 13.5.3

But the larger question, recently raised: Do we really need buttons for Undo and Redo in the main toolbar?

**Comment by j-raybaudserda** [comment]
They do appear at the same position in macOs 12.7.6 as well, they just render "cut" on startup (the difference appears clearly in the two videos attached).

That is a fair question though. I guess if one is used to using the keyboard shortcuts to undo / redo an action, they do not make much sense. But then again, one could make the argument that a less proficient user would prefer having dedicated buttons, as they can appear more intuitive to use than a keyboard shortcut. Could a good middle-ground solution be to have an option to toggle their display on or off, in the `Display` menu perhaps ?

**Comment by cbjeukendrup** [comment]
On the master branch, this was (partially?) fixed by https://github.com/musescore/MuseScore/pull/25174, but I seem to recall I saw a comment somewhere that it could still be reproduced in some cases. But perhaps I misremembered that. @Eism do you know that?
