### ISSUE TITLE
Recover a file lost during software update Musescore 4.4.3

### ISSUE THREAD

**Issue by agrantpr** [musescore/MuseScore#25423]
I was just beginning a new score and as I was opening a different score, I was prompted to update to the newest version 4.4.3.  I did this but did not save my new score before the update.  Then I saved it.  When I went to open it again, it tells me I saved it in an older version and then when I open it the whole thing is blank.  Is there anywhere I can recover my work?

**Comment by MarcSabatella** [comment]
For help using MuseScore, please ask in the official support forum at musescore.org.  When you do so, please attach the score you are having trouble with, and also say what OS you are on.

**Comment by cbjeukendrup** [comment]
Closing as per the comment above, but we're happy to help at the forum!
