### ISSUE TITLE
Tenors don't crescendo properly from p to f

### ISSUE THREAD

**Issue by danrip** [musescore/MuseScore#25431]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

Write a melody for tenor, have it crescendo from _p_ to _f_ on the first note in a new bar

![image](https://github.com/user-attachments/assets/5ed45da0-0685-496d-a078-c4cd958dc7d0)

Dynamic will change dramatically instead of gradually building 

This way of notating makes tenors behave more as expected, even if not as intended 

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/4dbe7a29-d91c-40ca-b8b4-3fa73516d692">

Also, restarting Musescore fixes the issue with playback, but it comes back. The combination of a new dynamic in a new bar seems to be problematic for other Musesounds as well, I've experienced the same sort of behavoiur with percussion for example.

### Supporting files, videos and screenshots

[Horse and boy .mscz.zip](https://github.com/user-attachments/files/17630325/Horse.and.boy.mscz.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.5, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

I was unable to check

### Operating system

Sonoma 14.3

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
As this is specific to a MuseSounds instrument, please report to MuseHub support team.  It would be very helpful to them to screen capture of the issue as well.

: https://support.musehub.com/hc/en-gb/requests/new.
