### ISSUE TITLE
Some dynamics combined with expression text are not centered in the grand staff

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#25451]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

As a rule, in MuseScore Studio, the dynamics along with expression text are centered in the grand staff by default. But for reasons I don't understand, some dynamics combined with expression text somehow ignore this rule. 
Take, for example, the **_p_** dynamic. Centering works: 

https://github.com/user-attachments/assets/8274bd42-fd47-4e0e-923f-17345bf6a609

But now let's try to do the same with _**f**_ dynamic. Centering does not occur: 

https://github.com/user-attachments/assets/ab4a6a2c-d120-401c-80a7-d5c4c6983e4f

Below is a list of dynamics that are not centered in combination with expression text:

- **_mf_**
- **_f_**
- _**ff**_
- **_fff_**
- **_ffff_**
- **_fffff_**
- **_ffffff_**
- **_sf_**
- **_sff_**
- **_sfff_**
- **_pf_**
- **_rf_**

### Supporting files, videos and screenshots

See above

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by FrancRos31** [comment]
Issue still present but without expression text. Should I open a new report? 

https://github.com/user-attachments/assets/b1809e84-bce9-4cc6-9378-af9221528be1
