### ISSUE TITLE
Use indentation in Format>Style>Score

### ISSUE THREAD

**Issue by scorster** [musescore/MuseScore#25466]
### Your idea

My eyes would certainly appreciate indentation of properties (and contextual property sections) in the Format>Style>Score dialog. Presently it looks pretty monolithic, and there's plenty of room for indentation. So ... ? 

### Problem to be solved

This would improve the readability dialogs and afford the user the option to visually scan them more quickly.

### Images
This image is an example of properties indented in the dialog, with plenty of room to spare

        ![Format-Score dialog - Indented](https://github.com/user-attachments/assets/4da36e37-f466-45e5-8dc0-ad5867ea8063)

This is how it looks presently

        ![Format-Score dialog - Unindented](https://github.com/user-attachments/assets/d3786aa1-a5f3-4a11-8e38-9969a106b703)

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment]
I don't think we should invest in custom layouts in those legacy dialogs like the style dialog. The options offered by the Qt Widgets framework are limited. 

Also, indenting "display in concert pitch" and "enable indentation on first system" doesn't make sense, since those are not subsettings of the settings above them.

**Comment by bkunda** [comment]
This dialog will also inevitably be overhauled, so I agree with @cbjeukendrup that it doesn't make much sense to invest in custom layouts for these dialogs at this stage.

**Comment by scorster** [comment]
> I don't think we should invest in custom layouts in those legacy dialogs like the style dialog. The options offered by the Qt Widgets framework are limited. Instead, such dialogs should be redesigned holistically, and reimplemented in QML.

Thanks for you input here.

> Indenting "display in concert pitch" and "enable indentation on first system" doesn't make sense, since those are not subsettings of the settings above them.

Thanks for noticing that. I've updated the image in the original post.
