### ISSUE TITLE
Bracket always created on first staff. (Master Version)

### ISSUE THREAD

**Issue by Gai-Luron** [musescore/MuseScore#25471]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. create a new score with more than 2 staves
2. Try to put brackey on other staff than first.
3. Bracket is created on first staff

Look at vidéo

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/ba94ae60-ffa4-40ea-b2c2-99e689212a44

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.5.0-243130303, revision: github-musescore-musescore-86fcaa6

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64, 

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by sammik** [comment]
Also other elements have this issue:
- spacers
- staff type change

**Comment by sammik** [comment]
It seems, this is reason https://github.com/musescore/MuseScore/pull/25236#discussion_r1808285604
@XiaoMigros
