### ISSUE TITLE
Choir Out of Sync

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25479]
### Issue type

Muse Sounds bug

### Description with steps to reproduce

When this passage is entered, the men are horribly out of sync with the women. I entered the women first, then the lower octave of the men, and then the higher octave.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/86e36446-be94-4053-b92d-ae78e48687f3

https://github.com/user-attachments/assets/f96f9808-0ff5-4abf-8243-d47be1f3fd81
[Choir.zip](https://github.com/user-attachments/files/17693236/Choir.zip)

### What is the latest version of MuseScore Studio where this issue is present?

Version: 4.4.3.242971445   Revision: eb6b367

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
Thanks for reporting this. Because this is a MuseSounds issue, we'd be grateful if you could please contact the MuseHub support team with your request: https://support.musehub.com/hc/en-gb/requests/new.

Many thanks!
