### ISSUE TITLE
Remove MuseSounds Option in Github

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25491]
### Your idea

There is currently an option in bug reports to report a MuseSounds issue. 
![image](https://github.com/user-attachments/assets/86fac4dd-e83a-4a1d-8c05-e8305636cb38)
However, I am always directed to contact the MuseHub support team instead. 

> Thanks for reporting this. Because this is a MuseSounds issue, we'd be grateful if you could please contact the MuseHub support team with your request: https://support.musehub.com/hc/en-gb/requests/new.

I request that this option get removed, and instead there simply be a notice directing people to the MuseHub support team for MuseSounds issues, as there seems to be no purpose for it.

### Problem to be solved

This MuseSounds option is very confusing if any and all MuseSounds reports do not belong on GitHub in the first place.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by cbjeukendrup** [comment]
Good point, I'll do this!
