### ISSUE TITLE
Staff/Part properties changes are lost without warning when using up/down buttons

### ISSUE THREAD

**Issue by jonharris7** [musescore/MuseScore#25494]
### Issue type

Other type of issue

### Description with steps to reproduce

1. Open a score with at least 2 instruments.
2. Double-click a instrument name to open the Staff/Part properties dialog box.
3. Make any change in the dialog such as renaming the Short instrument name
4. Press the down arrow to move to a different part
5. Press the up arrow to move back to the original part.

Your changes are lost.  There is no warning about this.
I think it should automatically _Apply_ any changes when using the arrow keys to navigate parts.  Or at least offer to do this.  The current behavior causes data loss with no warning or possibility of undo. 

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/c22b29d9-4699-45ba-abb0-5cfe2f1adca7)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

No.

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
I think the easiest short-term solution would be to remove those arrow buttons entirely. 

Ultimately this dialog is going to be completely overhauled.

**Comment by SteveBlower** [comment]
>I think the easiest short-term solution would be to remove those arrow buttons entirely.

Please, NO!, That would make, for example, setting merge matching rests on all staves in an orchestral score rather tedious and prone to error.

**Comment by cbjeukendrup** [comment]
For merging rests specifically, 4.5 will have a score-wide toggle: https://github.com/musescore/MuseScore/issues/24983

However, if someone wants to go ahead and implement it in such way that clicking those arrows preserves changes until Cancel is clicked, that's of course welcome.

**Comment by MarcSabatella** [comment]
To me it’s not clear what should happen if you make changes for several different staves and then click Cancel - should that undo all the changes or just the current one?  I guess officially it should probably undo all of them, and that would probably be more complicated to implement if the arrow button did an automatic Apply.  But, to me, an interim solution of just doing an apply ion each press of the arrow button would be the best way forward short term.  The button could even be relabeled (via tooltip) to something “Apply and go to next staff” or some such.

**Comment by Jojo-Schmitz** [comment]
Just changing the lable isn't sufficient though...

**Comment by MarcSabatella** [comment]
Indeed, but it's probably "one-line change" (maybe even literally so) to have the button do the Apply.  Which is much simpler than implementing a system to make all the changes made across all staves cancelable.  And with the Apply, they'd be individually undoable as well.

**Comment by jeetee** [comment]
Historic note: when I added those buttons, only two things were on my mind:
1. A way to more easily access staff/part-properties of hidden staves
2. Follow the same logic as existed (at least back then) in the Measure Properties dialog, where pressing the prev/next buttons cancelled previous actions automatically.

I've so often used the Apply+Arrow flow in that dialog that, to me, having them apply would make the most short term (and probably easiest) sense.
From a consistency POV one might also consider/check how this is handled in the Measure Properties dialog as well.

**Comment by MarcSabatella** [comment]
Agreed, same should be implemented for measure properties - although for whatever reason, that seems to come up much less often.  But see also https://github.com/musescore/MuseScore/issues/22128 - the idea of being able to select multiple measures (or, analogously, staves) and apply a single setting across them all is also something to be considered.  But, not, I think, as a replacement for the next/previous staff commands.  SInce one super common usage of those is to change all staff names (to conform with those used ina  published score, for example) and that's not a case of applying the same setting to multiple staves.

**Comment by cbjeukendrup** [comment]
@EightSmart Welcome!
So to summarise, the desired new behaviour is:
- when using those arrow buttons to move to a different staff, the changes made to the current staff are applied instead of discarded
- those arrow buttons should have a tooltip that says "Apply and go to next staff" (or "...previous staff" ofc.)
