### ISSUE TITLE
MuseScore freeze if I add a directory with a lot of sf2 / sf3 files

### ISSUE THREAD

**Issue by ycollet** [musescore/MuseScore#25511]
### Issue type

Crash or freeze

### Description with steps to reproduce

In the preference dialog -> folder, add a soundfont directory with a lot of sf2 / sf3 sound fonts
In the mixer, try to change the soundfont ....

### Supporting files, videos and screenshots

The application freeze for a long time ... And after a while (several minutes) the dialog shows up.
After that, it's nearly impossible to use the menu.
On MS3, you first selected a sf2 file and then selected an instrument.
I think the problem comes from the fact the MS4 open and parses everything to get all the instruments information.
The work around for now is to copy the selected soundfont into ~/Documents/MuseScore4/Soundfonts

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Linux Fedora 40

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
@DmitryArefiev pls try to reproduce on different OSs.

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev pls try to reproduce on different OSs.

This occurs on all OSs. 

Can't reproduce the freeze because I don't have a hundreds of SFs. But with my **~40 SFs**, I see a **sluggishness** when hovering over SoundFonts group, and that **makes it difficult to operate sound founts in mixer (if user has a lot of them):**


https://github.com/user-attachments/assets/ce015ede-572f-42b7-903c-c47983291b98

**Comment by DmitryArefiev** [comment]
> Related (or duplicate)
> 
> #15003

Yeah, I think it's the same. Will close the current issue

**Comment by ycollet** [comment]
Thanks a lot for the check !
