### ISSUE TITLE
Multi-movement bugs (several) - MuseScore 4.4.3 Mac on INTEL and M2 machines, all running Sonoma 14.7.1

### ISSUE THREAD

**Issue by musicofnote** [musescore/MuseScore#25535]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

Working on collections of sonatas for cello and continuo. Some collections have up to 12 sonatas with up to 5 movements per sonata, so up to a total of around 60 movements in one file (collection)

Bug 1:
Let's say a sonata has 5 movements. The Cello part in all alternates between bass clef and tenor clef. I don't want to change all instances of tenor to bass or bass to tenor. But If I do select the 2nd movement only - only the 2nd movement is blue, the sebsequent one are not "marked" (selected). When I drop the bass clef sign onto the existing tenor clef sign, not only is the 2nd movement changed to bass clef, but also ALL the subsequent movements, all instances of tenor clef are changed to bass clef. Same behavior is everything is in bass clef and I want only one movement to be in tenor clef - all subsequent movements change clefs. This can disturb the switching back and forth between the two clefs later, that I transcribed as such and want to keep.

Bug 2: (must have something to do with the file having been imported as XML non-compressed, although the same behavior happen with compressed XML or the antiquated form of XML)
Set the notes in Finale v27, save the set of Sonatas (different set than Bug Nr. 1 above). Exported to XML uncompressed. Opened up in MuseScore and all notes come over perfectly. BRAVO!
But (there's always a but(t)) . Starting in the 2nd movement of the 48 in the file, The measure numbering is off by one. I have to right-click on the first measure and add a measure number to the count. 47 times rinse and repeat. I notice, that no section breaks are set. So my first run through with this imported file is to go, movement by movement and set the "section break" at the end of each movement. Also necessary, because although I very exactly defined the number sections, in Finale, these definition didn't survive the XML transformation.

Any way, Looking at the file when first opened in MuseScore, the last measure of the first movement endes with measure 38. The first measure of the 2nd movement has no measure number showing, but if I force it (right click, Measure Properties \ "always show" ) the is first measure shows number 39. So far so good. BUT this first system has 4 measures, which means, the 2nd system of this 2nd movement should show 43, but it only shows 42. To get it to show 43 as it should, I have to once again r-click on the first measure of the 2nd movement, Measure Properties \ and "add to measure number" and define "1". Then the numbering is correct. Rinse and repeat 47 times.

Now, if I insert a "Section break" onto the last measure of the first movement, the numbering of the 2nd movement changes as it should - kind of. The first measure is 1, but after 4 measures in the first system, the first measure of the second systems should show "5" but it doesn't. It shows "4" instead. So like the paragraph above, I add a measure to the count and it show properly. But before doing this, I forced the first 4 measures to show numbers always and what I got was 1, 1, 2, 3, ... and 4 on the enxt system. After adding a number as described, I got 2, 2, 3, 4 on the first line (no measure "1"), but the subsequent numbering for this movement is correct. Then rinse repeat for the other 46 movements.

Bug 3: (must have something to do with the file having been imported as XML non-compressed, although the same behavior happen with compressed XML or the antiquated form of XML)
If i decide to transpose movement 3 of this same sonata, same set, from the cmaj all the movements have, to b-flat, I mark just this movement, not the subsequent ones since the next ones should stay in cmaj.
Tools / Transpose / To key Flat / down / Transpose key signatures..... The key signature of this transposed movement stays c-maj, but the notes are transposed down a step, with the necessary "accidentals" before the necessary note. This is NOT how this is supposed to work. It should have moved the notes AND changed the key signature to b-flat.

Now, If I FIRST reaffirm the key of cmaj by selcting the movement and dropping the key of c onto the existing key signature in the first meaure of the movement, whne I apply the transposition, it works as it should. proper intrval down and proper ne key signature with 2 flats.

Workaround for avoid the above:
Import XML OR start a new file from scratch, makes no difference.
    1) when editing begins, first re-apply all "section breaks' at the end of each and every movement in the 6 sonatas and their 4 movements each. Then "fix" the broken measure numbering movement for movement as described above.
    2) Note where each stretch of desired tenor and bass clef occurs in each movement, Better yet save as PDF BEFORE editing, and have PDF running parallel to MuseScore to proof the unwanted clef changes and revert, always moving from front to back, cleaning the wreckage as one moves forward through the piece.
    3) Going from movement to movement re-apply each and every key signature, whether or not planning to later transpose.

------------------------------------------------------------------
Just quickly created a new multi-movement document from scratch.

The clef problem is reproducible in a newly created MuseScore document. So it's not caused by the file having been XML. It happens also in a file newly created in MuseScore 4.4.3

The measure number thing is an XML thing. No such thing happening in a all-MuseScore file.

The transposition problem is also a problem with this newly created file. All the "Movements" were in cmaj. When I went to transpose to E-flat maj, the notes changed, but the key signature stayed the same. UNLESS I go, movement for movement and re-affirm the already created/existing key signature of cmaj.

### Supporting files, videos and screenshots

[bugfiles.zip](https://github.com/user-attachments/files/17783871/bugfiles.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

No.

### Operating system

MacOS 14.7.1 on Intel and M2

### Additional context

One of the 2 bugs seems attributable to files imported as XML. The other two also occur in virgin MuseScore created files.

I tried to upload two flies showing this, but ... alas, your system doesn't recognise MuseScore files!!
[bugfiles.zip](https://github.com/user-attachments/files/17783866/bugfiles.zip)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
We will have to close this as it doesn't comply with our issue reporting guidelines.

Please only include one bug in an issue, and be sure to provide a minimal reproducible example of the bug where possible. Descriptions like "Let's say a sonata has 5 movements. The Cello part in all alternates between bass clef and tenor clef. I don't want to change all instances of tenor to bass or bass to tenor. But If I do select the 2nd movement only - only the 2nd movement is blue, the sebsequent one are not "marked" (selected)" don't translate clearly to a precise bug or problem, and make it much harder for us to understand what the core issue is.
