### ISSUE TITLE
Leland font C clef is a bit small

### ISSUE THREAD

**Issue by LupusCaeruleus** [musescore/MuseScore#25544]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Create a score with viola.
2. Zoom in and observe the C clef, notice it does not touch the top and the bottom stave lines.
![image](https://github.com/user-attachments/assets/cfc36335-9391-4db6-a829-1dc684b36833)

### Supporting files, videos and screenshots

This is likely a glyph size issue within the Leland font, as the size looks correct in other fonts.
![image](https://github.com/user-attachments/assets/3090a4d0-eca6-4c0c-b7b7-9f551c48e3b5)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3-242971445

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
By design currently, which isn't to say we won't change it. Would be an issue for the Leland repo anyway, not this one.
