### ISSUE TITLE
Contradictory display of an auxiliary note when trill over a chord

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#25560]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

With the recent implementation of displaying an auxiliary note at second intervals when trill, I noticed some flaws that I propose to fix.
1. In the event that a chord is notated under the trill, regardless of how many notes there are in the chord, there will be one auxiliary note. This contradicts the final sound. 
![Снимок экрана (723)](https://github.com/user-attachments/assets/3c3cb574-bfff-4aab-98e6-ebdec280d418)
(In this case, logically there should be two of them).
2. When trying to add another note to an auxiliary note (to create a chord) by simultaneously pressing the Shift + {C…B} keys, an incomprehensible picture occurs. Take a look (in this case, I tried the keyboard shortcut Shift+ F and Shift + C): 

https://github.com/user-attachments/assets/785b3697-a586-4c87-a712-0031a9662fc4

I believe that the user expects that after such a keyboard shortcut, another note will be added to the auxiliary note. And the behavior that is happening now instead, I think, is illogical.

### Supporting files, videos and screenshots

see above

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.5.0-243230312, revision: github-musescore-musescore-9ef26b8

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
There seem to be two separate issues here. The second issue shows an obvious problem, which we would triage as more urgent than the first issue. 

@Dima-S-Jr could you please create a separate issue for each of these? Thanks!

**Comment by Dima-S-Jr** [comment]
@bkunda, I've reconsidered my speculations about the behavior of the auxiliary note and decided to open another issue regarding manipulation of the auxiliary note. I will close this one, because it does not quite correctly identify the shortcomings.
