### ISSUE TITLE
Crash with Pianoteq 8 at crotchet=152bpm

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#25579]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Create a score with piano
2. Fill a few bars with notes
3. Add a "crotchet=80" tempo marking to first beat of bar 1
4. Replace tempo text with "152"

MuseScore Studio crashes

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/0e278640-a1b0-4d6c-97f9-dcadddd7c923

**Diagnostic files**
[Diagnostic files_20Nov24_2.zip](https://github.com/user-attachments/files/17828422/Diagnostic.files_20Nov24_2.zip)

**Crash report**
[pianoteq-crash-152_20Nov24.zip](https://github.com/user-attachments/files/17828425/pianoteq-crash-152_20Nov24.zip)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore 4.5.0.243250309 Nightly, Introduced in 4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 15.0.1

### Additional context

Despite the specificity of the tempo marking, 152bpm is a sufficiently common tempo mark to warrant prioritising a fix for this. 

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
**Can't reproduce** with Pianoteq 8 **DEMO** (4.5, mac15.1)

**Comment by cbjeukendrup** [comment]
Given that error message, and that the crash is deep inside Pianoteq code, this might be a problem inside Pianoteq itself. Might be good to contact Pianoteq developers about this, so that they can have a look too. 

(Also @bkunda it looks like you're using Pianoteq 8.0.1, while the latest version on the website seems to be 8.4, according to https://www.modartt.com/try; so maybe they already fixed this.)
