### ISSUE TITLE
Adding or removing a playback devices doesn't update the list

### ISSUE THREAD

**Issue by saintmatthieu** [musescore/MuseScore#25587]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. open MuseScore Studio,
2. add a playback device
3. open the playback device list from the preferences

The device is missing.

Alternatively:
1. open MuseScore,
2. remove a playback device
3. open the playback device list from the preferences

The device is still there.

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/15695810-7fc0-42cd-95cb-9dc41d1b26f9)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

I was unable to check

### Operating system

Windows

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
@saintmatthieu I **can't reproduce** with my internal audio interface Audient iD14 MKII in **4.4.3** on **Windows10**

Does it occur with all devices?

**Comment by saintmatthieu** [comment]
Hi @DmitryArefiev ,
just trying it with a Behringer sound card connected with USB, and that works. I doesn't when I plug/unplug a headset with an analog pin, though.
I'm on 4.4.0.

**Comment by DmitryArefiev** [comment]
Hi @saintmatthieu , that's strange.. still can't repro with my Headphones (connected to internal Realtek output)

> I'm on 4.4.0.

Maybe you can try 4.4.3?

Also, does it work in build from your PR #25588?

**Comment by saintmatthieu** [comment]
@DmitryArefiev I cannot reproduce anymore. Now things work even without my change, like you described.
Apologies for the bother.

**Comment by DmitryArefiev** [comment]
Oh good. Please reopen if occurs again. Thanks!
