### ISSUE TITLE
Cannot delete right repeat sign after changing its span or style

### ISSUE THREAD

**Issue by FrancRos31** [musescore/MuseScore#25656]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. open a score
2. add a right repeat sign
3. change its span (or style) via Properties panel
4. try to delete it 

Actual behaviour: the repeat sign is impossible to delete.
Expected behaviour: no problems deleting it.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/57f40780-fc24-41ae-83d7-12372ee6e68d

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

I was unable to check

### Operating system

Windows 10 Pro

### Additional context

Same issue with the right and left repeat sign (the right one can't be deleted).
![1](https://github.com/user-attachments/assets/40b73312-27c0-44d4-ae3d-12ca20c84cf3)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
Strongly reminds of https://github.com/musescore/MuseScore/issues/24534 (it probably has the same cause)

**Comment by FrancRos31** [comment]
Ok, mine is a duplicate. But I think #24534 needs a more general title. I'll upload there the screen capture.

**Comment by cbjeukendrup** [comment]
Adjusted the title of that issue. And yes, feel free to upload the screen capture in a comment there, thanks!
