### ISSUE TITLE
Crash when copy/paste notes with percussion instrument changed

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#25657]
### Issue type

Crash or freeze

### Description with steps to reproduce

This issue is based on a report from https://musescore.org/en/node/372150

1. Create new score (add percussion instrument)
2. Go to Instruments panel and replace percussion with voice
3. Enter two quarter notes, copy any of them and paste into the rest
4. Crash

This is a regression since Musescore 4.4 (I checked 4.4.1)
No crash in Musescore 4.3.2

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/4a92c0a2-595e-4299-81a8-6ebca301dd65

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.5.0-243310311, revision: github-musescore-musescore-afac76a

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 10, MacOS 15.0.1

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
Diagnostic files:
[PercTonalCopyPasteCrash.zip](https://github.com/user-attachments/files/17939954/PercTonalCopyPasteCrash.zip)
