### ISSUE TITLE
Designing a soundbank/plugin similar to VOXOS Choir which works with syllables

### ISSUE THREAD

**Issue by cuneyttyler** [musescore/MuseScore#25695]
### Your idea

I'd like to design an instrument similar to VOXOS Choir which works with syllables.

### Problem to be solved

Musescore store instrument files in .spx file format. I assume that it's a compressed version of .sfz soundfont format. I'm not sure how MuseScore handles syllable processing and retrieving relevant audio from soundfont. Can you provide me with guide on how to achieve this when designing my soundfont? Also, I wonder if it's even possible with soundfont files or this requires a file format which specifically works with MuseScore.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
@cbjeukendrup is correct. Please keep an eye out on the MuseHub website for announcements about this. We're not sure when it will happen, but the ultimate aim is indeed to make it possible for people to develop their own MuseSounds libraries. 

Thank you for your interest!

**Comment by cuneyttyler** [comment]
Thank you! I'll be waiting for it.
