### ISSUE TITLE
Problem with "slide in" dynamics and playback interaction (MuseSounds sample duration)

### ISSUE THREAD

**Issue by UncleRed0899** [musescore/MuseScore#25699]
### Issue type

General playback bug

### Description with steps to reproduce

Apply "Slide in" or "slide in (rough)" dynamic to any note longer than 1/4 note. Press Play, and the playback will cut the instrument sound off after 1-2 beats. 

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/68d712f4-d00f-4dce-a748-ec1417d0b58b

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

I was unable to check

### Operating system

Windows 11 Home

### Additional context

I have not attempted to do this same thing to other instruments, aside from the Trumpet and Bass Trombone/Trombone with Muse Brass sounds. Unsure if this happens on any other instrument. 

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
@DmitryArefiev please check in @RomanPudashkin's latest PR.

**Comment by matthewreadbass** [comment]
This is indeed a Muse Sounds issue

**Comment by metasekk** [comment]
As far as I can tell, the same happens with other (somewhat "random") free Muse Sounds that don't seem to be "looped" in on themselves. A non-exhaustive list, after some testing:

- Muse Strings: Contrabasses, Violons 1, Violins 2, Viola (Solo) **with marcato or accent**. (The other instruments with these articulations are correct.)
- Muse Brass : Trombone **with marcato or accent**. (The other instruments with these articulations are correct.)

**Comment by RomanPudashkin** [comment]
Closed as a report was raised on the muse sounds side
