### ISSUE TITLE
Change "Select" button label in "Create new workspace" dialog

### ISSUE THREAD

**Issue by FrancRos31** [musescore/MuseScore#25690]
### Your idea

I think that "Select" is not the right option in this dialog.
![1](https://github.com/user-attachments/assets/3438ff03-3511-48de-a31a-a363bc5f1849)
A simple "OK" or "Create" would be much better because when you click the button you're not selecting an existing workspace like in the previous dialog.

### Problem to be solved

See above

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
Will be resolved as part of https://github.com/musescore/MuseScore/issues/22801.
