### ISSUE TITLE
Shortcut definitions in "Playback settings" context menu don't update until restart

### ISSUE THREAD

**Issue by avvvvve** [musescore/MuseScore#25702]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

If you change any shortcuts that correspond to an option in the Playback settings context menu, the shortcut shown next to the option in the menu will not update until you restart MuseScore Studio.
![Frame 7](https://github.com/user-attachments/assets/f3a4b742-02e0-46ea-bf69-d517d449e7d3)

1. Open Preferences > Shortcuts
2. Type in "MIDI"
3. Assign a shortcut to "Enable MIDI preferences" (if there is not one already)
4. Open the playback settings menu in the top bar
5. See that the shortcut is not listed (or it's not changed, if a shortcut existed previously)

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/9c158452-2e64-44c2-8ceb-2cdfb7814264

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3 and nightlies

### Regression

No.

### Operating system

macOS 15.1

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by pacebes** [comment]
I would like to work on this issue. Would you please assign it to me ?

Thanks

**Comment by pacebes** [comment]
I have just created the PR to deal with this issue.

**Comment by FrancRos31** [comment]
This issue extends to other menus, too. In the screen capture I show only the Style shortcut (defined as F6) in "Fomat" menu, but maybe there are others.

https://github.com/user-attachments/assets/41736e5c-a4c6-4175-970d-49ee1d1c33d4

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.4-243461245, revision: github-musescore-musescore-2232670

**Comment by cbjeukendrup** [comment]
That should also be fixed in the 4.5 nightly builds, thanks to the linked PR.

**Comment by FrancRos31** [comment]
You're right, I just checked. The title misled me. Thank you!
