### ISSUE TITLE
Open pedal hi-hat

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#25711]
### Your idea

I propose to introduce articulation, which would allow you to create the effect of an open pedal hi-hat:

![Снимок экрана (753)](https://github.com/user-attachments/assets/449aed32-46fc-4497-885d-6d8965490e0c)

https://github.com/user-attachments/assets/0d17f257-e8b5-41cb-aafd-5d950d78c727

Such notation would be useful for a drum kit.

### Problem to be solved

This would allow you to get the appropriate sound, as well as simplify the input of the appropriate articulation.

At the moment, only the appropriate notation can be achieved (and even then, the articulation "open" will need to be moved under the stave, because automatically by default this articulation is always located above the stave, even if it is added to the second voice). 

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by bkunda** [comment]
MS Studio already has notation support for this kind of articulation (albeit with the requirement that it must have its position changed, but this is acceptable given the infrequency of this specific notation requirement). 

For playback support for this articulation symbol, the best thing to do would be to raise a request for addition to a MuseSounds library: https://support.musehub.com/hc/en-gb/requests/new.

Many thanks!
