### ISSUE TITLE
The instrument change cannot be copied

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#25714]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

You can copy/paste the text of the instrument change itself. But if you select a range along with the instrument change text, the instrument change text will not be copied.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/206c5783-ca03-4cc1-902d-e882989af3e8

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

No.

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
Closing as will be covered in https://github.com/musescore/MuseScore/issues/15590
