### ISSUE TITLE
 WavesAudio plugins/vst do not appear

### ISSUE THREAD

**Issue by GyorgyL** [musescore/MuseScore#25721]
### Issue type

VST bug

### Description with steps to reproduce

Hello, it seems the plugins/vst from Wavesaudio aren't supported... Any clues or improvements ? Thank You

### Supporting files, videos and screenshots

Hello, I have bought some plugin from WaveAudio, no on appear on MuseStudioScore

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

No.

### Operating system

Windows 10 PRO

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by DmitryArefiev** [comment]
@GyorgyL Do you have the same result like in #15968 ?

**Comment by GyorgyL** [comment]
No, what do I have is the early reverb seems to be installed IRL but I have upgraded to IR1 and IR1 doesn't appear ....
    Le vendredi 6 décembre 2024 à 15:37:33 UTC+1, Dima Arefiev ***@***.***> a écrit :  
 
 


@GyorgyL Do you have the same result like in #15968 ?

**Comment by DmitryArefiev** [comment]
> No, what do I have is the early reverb seems to be installed IRL but I have upgraded to IR1 and IR1 doesn't appear .... 

Hmm.. 1. Do you have Waves group in Mixer>Audio FX ?

![Screenshot 2024-12-09 165535](https://github.com/user-attachments/assets/807c060d-6fc0-4740-801b-4a4182a016f3)


2. Make sure VST3 version of that plugin is installed (You should have WaveShell1-VST3 xx.xx_x64.vst3 in **c:\Program Files\Common Files\VST3\** )

**Comment by GyorgyL** [comment]
Dear Dima, Yes it is on this file, despite I have 2 others vst3 15.0 x 64 from waves only the older IRL appear ....
    Le lundi 9 décembre 2024 à 15:59:34 UTC+1, Dima Arefiev ***@***.***> a écrit :  
 
 



No, what do I have is the early reverb seems to be installed IRL but I have upgraded to IR1 and IR1 doesn't appear ....


Hmm.. 1. Do you have Waves group in Mixer>Audio FX ?

Screenshot.2024-12-09.165535.png (view on web)
   
   - Make sure VST3 version of that plugin is installed (You should have WaveShell1-VST3 xx.xx_x64.vst3 in *c:\Program Files\Common Files\VST3* )

**Comment by GyorgyL** [comment]
Le lundi 9 décembre 2024 à 15:59:34 UTC+1, Dima Arefiev ***@***.***> a écrit :  
 
 



No, what do I have is the early reverb seems to be installed IRL but I have upgraded to IR1 and IR1 doesn't appear ....


Hmm.. 1. Do you have Waves group in Mixer>Audio FX ?

Screenshot.2024-12-09.165535.png (view on web)
   
   - Make sure VST3 version of that plugin is installed (You should have WaveShell1-VST3 xx.xx_x64.vst3 in *c:\Program Files\Common Files\VST3* )

**Comment by GyorgyL** [comment]
What’s wrong with these vst plug-in ? 


Envoyé depuis Yahoo Mail pour iPhone


Le lundi, décembre 9, 2024, 9:47 PM, Georges GONDARD ***@***.***> a écrit :

 

    Le lundi 9 décembre 2024 à 15:59:34 UTC+1, Dima Arefiev ***@***.***> a écrit :  
 
 



No, what do I have is the early reverb seems to be installed IRL but I have upgraded to IR1 and IR1 doesn't appear ....


Hmm.. 1. Do you have Waves group in Mixer>Audio FX ?

Screenshot.2024-12-09.165535.png (view on web)
   
   - Make sure VST3 version of that plugin is installed (You should have WaveShell1-VST3 xx.xx_x64.vst3 in *c:\Program Files\Common Files\VST3* )

**Comment by DmitryArefiev** [comment]
> What’s wrong with these vst plug-in ? 

@GyorgyL Unfortunately we still don't support Waves API. MuseScore Studio doesn't see all bundle content of one file (WaveShell1-VST3 xx.xx_x64.vst3), it shows the first plugin in the list - #15968 

Also, I've found that **Waves** plugins work only with **one Left channel** (tested 4.4.4, Windows10). So we need to fix it too together with #15968 

I hope we will fix it in the coming year.

You can use **MuseFX** for now (MuseHub>Plugins) or other VST effects (in vst3 format)

**Comment by DmitryArefiev** [comment]
Closing as duplicate since it's the same as #15968
