### ISSUE TITLE
A Part of Shortcuts don't work on macOS

### ISSUE THREAD

**Issue by BlackcatKrnk** [musescore/MuseScore#25734]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Place a note.
2. Select one note. 
3. Press Shift+Opt+↑, the default shortcut for "Raise pitch by a whole step."
4. Does not work.

### Supporting files, videos and screenshots

[診断ファイル_20241205.zip](https://github.com/user-attachments/files/18010222/_20241205.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Sequoia 15.1

### Additional context

It is possible that shortcuts that contain two or more modifier keys may not work. Other than raising the pitch by a whole step, pasting twice as long, etc. did not work.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
This is a known issue already fixed in for the upcoming 4.4.4 update - see https://github.com/musescore/MuseScore/issues/25314

**Comment by zacjansheski** [comment]
Closing per comment above
