### ISSUE TITLE
[Internal testing] Score saved in latest master crashes previous master builds (add ability to open new files in previous versions)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#25736]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Save score in master build from **December 5** (or later) 
2. Open that score in previous master builds (before December 5)
(or open [2.zip](https://github.com/user-attachments/files/18011434/2.zip)) 

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/66d40558-e513-45e4-8e76-cc32368455a3

### What is the latest version of MuseScore Studio where this issue is present?

4.5 nightly

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Win/Mac

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by mike-spa** [comment]
This is expected. This PR https://github.com/musescore/MuseScore/pull/25666 has completely changed the format in which item IDs are written. The new logic can deal with old IDs, but the old logic can't know about the new IDs and how to deal with them, so if you open a new file using old logic it is expected to crash. This, of course, is protected by bumping the file version and making sure users can't open new files with old versions. But in this case, the version had already been bumped before that PR (we were already using the 4.5 tag in our files). So this issue will not be experienced by users, and is only a transition phase for us (we have no reason to keep using older builds to open new files), so I think this can be closed.

**Comment by DmitryArefiev** [comment]
Yeah... But it makes regression testing inconvenient..( Now we can't open 4.5 scores in **4.2.1 - 4.4.4**

Is it possible to add the ability to save score in compatibility mode? Maybe, add that checkbox to DevTools?

**Comment by mike-spa** [comment]
Uhm, ok, let me look into it. I'll come back to you :)
