### ISSUE TITLE
Tuplet Mode

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25758]
### Your idea

Some pieces, especially those for piano, have left hand or right hand parts consisting almost entirely of tuplets. Notable examples include Schubert's Erlkonig, Moments Musicaux No. 4 (Rachmaninoff), and Chopin Opus 25 no. 2. I suggest that Musescore have a "Tuplet mode", where a user can select a tuplet ratio and write in it for as long as they are in that mode.
![image](https://github.com/user-attachments/assets/a1297454-e72c-416d-9307-9302a9d9691c)

### Problem to be solved

It is cumbersome to write out melodies made entirely of tuplets, such as the following:
![image](https://github.com/user-attachments/assets/6c7c3d45-f770-42b2-857a-b9315f235ac2)
This feature would make the process much easier.

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by mmeyn** [comment]
Prior art: LilyPond’s tuplet command. The following code generates four triplets:
```
\tuplet 3/2 { c8 df b } \tuplet 3/2 { c ef df } \tuplet 3/2 { c df b } \tuplet 3/2 { c fs g }
```
![grafik](https://github.com/user-attachments/assets/edc1126f-13ae-457d-832a-110558258fe0)

The same can be written shorter with an optional argument that sets the duration of the tuplets (here 4 for quarter note):
```
\tuplet 3/2 4 { c8 df b c ef df c df b c fs g }
```

Also, you don’t have to hide tuplet numbers but can scale durations instead if you don’t want to show them all:
```
\tuplet 3/2 4 { c8 df b c ef df } c8*2/3 df b c fs g
```
![grafik](https://github.com/user-attachments/assets/90eb365b-0a53-44ca-b25c-69a0ad09788e)

**Comment by mmeyn** [comment]
See also the discussion at #18980.

**Comment by lgvr123** [comment]
Linked request for writing cadenza with tuplets at #24739

**Comment by bkunda** [comment]
Will be covered by https://github.com/musescore/MuseScore/issues/18980
