### ISSUE TITLE
Problem with note flags and stems.

### ISSUE THREAD

**Issue by brenostoliveira** [musescore/MuseScore#25765]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

There is an issue when trying to increase the length of note stems. For individual eighth notes, attempting to adjust them separately causes the flag to become detached from the note. Additionally, it is no longer possible to increase the size of multiple selected stems at once.  

When trying to adjust grouped eighth notes, the flag detachment issue does not occur. However, if you try to increase the size of two or more groups of stems simultaneously, they do not scale proportionally.

Steps:

1. Click on the note stem and drag to increase its length.
2. Trying to drag multiple grouped or individual eighth notes simultaneously.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/96890a5f-3943-4b8d-9978-5a562db28433

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3 / 4.4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

If I remember correctly, this worked fine in MuseScore version 4.4.2.

(EDIT):
I did a deeper investigation and found that the issue with the beams of grouped eighth notes occurs when the "Flatten all beams" option in the Style menu is enabled. Disabling this option allows me to move them uniformly again. If this is how it's supposed to work, then it was my mistake (apologies).

However, the issue with the eighth note flag happens regardless of whether this function is enabled or not.

![image](https://github.com/user-attachments/assets/93049e3f-1bc8-490b-86ec-6c544d03a492)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
I can reproduce the problem with the flag but not the one with the beamed groups.  Can you ZIP and attach your score and say which notes are giving you trouble?

Workaround for the flag issue is to lengthen the stem via Properties instead of directly dragging.

**Comment by brenostoliveira** [comment]
I did a deeper investigation and found that the issue with the beams of grouped eighth notes occurs when the "Flatten all beams" option in the Style menu is enabled. Disabling this option allows me to move them uniformly again. If this is how it's supposed to work, then it was my mistake (apologies).

However, the issue with the eighth note flag happens regardless of whether this function is enabled or not.

![image](https://github.com/user-attachments/assets/93049e3f-1bc8-490b-86ec-6c544d03a492)

**Comment by DmitryArefiev** [comment]
Fixed in #25785
