### ISSUE TITLE
No note is played in a specific score [Muse Sounds only]

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#25766]
### Issue type

General playback bug

### Description with steps to reproduce

I'm sorry to report this, because it's actually a small thing (at least for you), but personally it threw me into confusion. 

This score is attached below. In bars 16-17, the note A♭6 does not sound in the E♭ Clarinet part. I have no idea what's going on. I wrote out this passage in a separate score, tried to listen to it both in Muse Sounds and in MS Basic and everything sounds there! But it doesn't sound like that in this particular score. I have no idea what's going on. It's a mystery to me. 

I don't think this is specifically related to the Muse Sounds library, because it works in a separate score specifically with this passage.

### Supporting files, videos and screenshots

[(bars 16-17 (E♭ clarinet)).zip](https://github.com/user-attachments/files/18048568/bars.16-17.E.clarinet.zip)

Please note that this passage works perfectly in a separate score:

https://github.com/user-attachments/assets/e7020992-71d5-4e24-b995-35635990214c

But in a specific score, this passage does not sound: 

https://github.com/user-attachments/assets/1cae0aca-c354-432a-8a25-0c1e7a1d0369

### What is the latest version of MuseScore Studio where this issue is present?

4.5.0 243420313, revision: 154aba2

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by matthewreadbass** [comment]
As there is a difference in behaviour between the different scores, I believe that this is an issue with how MuseScore is playing back the sample

**Comment by bkunda** [comment]
@zacjansheski pls investigate

**Comment by zacjansheski** [comment]
This is quite odd.  I have found that cmnd+deleting measure 8 restores the playback of the trill, I haven't been able to determine precisely what is going wrong

**Comment by Dima-S-Jr** [comment]
> This is quite odd. I have found that cmnd+deleting measure 8 restores the playback of the trill, I haven't been able to determine precisely what is going wrong

These notes do not sound with or without a trill

**Comment by zacjansheski** [comment]
What notes in what circumstance?

**Comment by zacjansheski** [comment]
https://github.com/user-attachments/assets/c104db3b-1e85-41bd-88ad-1725026aad12

**Comment by Dima-S-Jr** [comment]
> What notes in what circumstance?

Apologize. It turns out that without a trill and without removing bar 8, these notes sound

**Comment by zacjansheski** [comment]
Looks like the issue is that the sample does not play at forte (which must not have made it into the other example score.  

Writing this does not play

@matthewreadbass I believe this is a Muse Sounds issue after all

https://github.com/user-attachments/assets/73035528-bfd8-4927-832d-3eadd5a2593f

**Comment by matthewreadbass** [comment]
Ah! Thanks for the heads-up on the change in dynamic affecting playback. I know what the issue is (specific quirk in the way the sampler handles dynamics). I'll raise a ticket in our bug fix repo

**Comment by Dima-S-Jr** [comment]
However, it is strange why this is happening. If I add **_f_** (without removing bar 8), the trill still won't play: 

https://github.com/user-attachments/assets/017fe1e7-27ac-413d-89b5-0e59a7faebb9
