### ISSUE TITLE
Spanner carry doubled colors

### ISSUE THREAD

**Issue by rettinghaus** [musescore/MuseScore#25783]
### Issue type

Opening/saving issue

### Description with steps to reproduce

Colors are saved twice on trill spanners.

1. Add a (trill) spanner
2. color it
3. save
4. open the mscx file

### Supporting files, videos and screenshots

```xml
<Spanner type="Trill">
  <Trill>
    <subtype>prallprall</subtype>
    <color r="0" g="249" b="0" a="255"/>
    <color r="0" g="249" b="0" a="255"/>
    <Ornament>
      <subtype>ornamentTrill</subtype>
      </Ornament>
    </Trill>
  <next>
    <location>
      <measures>4</measures>
      </location>
    </next>
  </Spanner>
```

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

I was unable to check

### Operating system

macOS 15

### Additional context

This applies to all checked spanners (pedal lines, ottavas, hair pins).
Though not a serious bug, I'm wondering why this happens and should be fixed eventually.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
Not a regression, same issue in Mu3
