### ISSUE TITLE
End of pedal line does not align with notehead

### ISSUE THREAD

**Issue by brettrp** [musescore/MuseScore#25838]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Select the start and end note for a pedal line
2. Click (e.g.) "Pedal (both hooks angled)" in the Keyboard palette
3. The start of the line is aligned with the starting notehead but the end of the line is not -- it's aligned just before the next note (effectively at the end of the duration of the ending note).

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/03915284-89ce-43ba-8a91-e555b98df704

[pedal-issue-4.4.0.mscz.zip](https://github.com/user-attachments/files/18138884/pedal-issue-4.4.0.mscz.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 15.1, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.4-243461245, revision: github-musescore-musescore-2232670

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 15.1.1

### Additional context

Issue did not occur in 4.3.2 and started occurring in 4.4.0

Issue present in nightly OS: macOS 15.1, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.4-243500401, revision: github-musescore-musescore-ffc276d

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
This is by design - pedal lines have been rationalised to work like other spanners (e.g. hairpins, ottavas, let ring, etc), so you select all the notes which they apply to, but not the final one (which is the release or change).

**Comment by Dima-S-Jr** [comment]
@brettrp 

https://github.com/user-attachments/assets/21c9dad9-aaf3-41b7-bec1-4f6ef1600306

**Comment by brettrp** [comment]
@oktophonie @Dima-S-Jr thanks for the feedback. Your video did show me how to annotate the score that I'm working on. But...

> This is by design - pedal lines have been rationalised to work like other spanners (e.g. hairpins, ottavas, let ring, etc), so you select all the notes which they apply to, but not the final one (which is the release or change).
> 
> The end of pedal lines will be drawn just before the next notehead (also by design), unless another line is then added starting on at notehead, at which point they will connect.

I can see the technical appeal of this, but from a pianist's point of view pedal marks are not like the other spanners. Pedal marks really tell you the _point in time_ at which to pedal, not the notes they apply to.

This is obvious when you're notating overlapping pedal, which is where I ran into this. What you are aiming to annotate is "release and replay the pedal at the same time you play this note". What you have to do to annotate this now is find the note _before_ the one you want to annotate, and select that instead. That previous note might be in a previous bar or on a previous page. It's like a perpetual off-by-one error. 

When you say "select all the notes which they apply to" that's not the case for overlapping pedal, because for overlapping pedal the pedal _does_ apply to the last note - you are still holding the pedal when you play that note and you re-pedal as you play it.

**Comment by MarcSabatella** [comment]
On the positive side, though, it does greatly simply the pretty common case where you have a pedal mark you want to apply to one full measure and change at the next downbeat.  It used to be you had to select a measure plus one note.  Now, you just select the measure.

**Comment by cbjeukendrup** [comment]
I believe at some point there was the idea to overhaul pedal lines a bit more thoroughly so that you can just create the line and then apply retakes to it where you want them, instead of having to add separate pieces of lines that can go out of alignment if you don't watch out. I'm not sure if that's still planned, but it might improve the situation further.
