### ISSUE TITLE
Empty mixer remains open even if there's no open score

### ISSUE THREAD

**Issue by FrancRos31** [musescore/MuseScore#25834]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. open a score
2. open the mixer (either via shortcut or button)
3. close MS
4. open MS again
5. press Score in the main tab

Expected behaviour: mixer is closed.
Actual behaviour: empty mixer is open.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/42115a73-a4f3-4939-ad7e-b3e80b96d9c1

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.5.0-243490311, revision: github-musescore-musescore-f461818

### Regression

Broken in version 4.4.4, too.

### Operating system

Windows 10 Pro

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by FrancRos31** [comment]
This is certainly related to #25559, if not a duplicate.

**Comment by MarcSabatella** [comment]
Except as far as I know, this isn’t a bug.  It’s by design that MuseScore remembers its state in terms of which panels are open, which toolbar and palette customizations you have made, etc.

**Comment by FrancRos31** [comment]
> It’s by design that MuseScore remembers its state in terms of which panels are open, which toolbar and palette customizations you have made, etc.

Ok, but there's one thing I don't understand: when no score is open, you can't open the mixer in any way. So, why the program remembers the mixer state when you reopen MS?
![1](https://github.com/user-attachments/assets/3eb43dd6-0bfc-448a-bdd7-2343ee6df133)
In addition, in this state you can't close the mixer via shortcut, it doesn't work, only using the ... button.

**Comment by MarcSabatella** [comment]
As I said, definitely room for tweaking in the specifics of which controls are active when.  But the basic behavior of remembering panel state is not a bug.
