### ISSUE TITLE
2nd Volta Not Playing

### ISSUE THREAD

**Issue by adavismusic89** [musescore/MuseScore#25844]
### Issue type

General playback bug

### Description with steps to reproduce

1. Create a score with first ending that does not repeat but instead skips further down the score
2. Create a second ending that contains Fine
3. At the end of the score use DC al Fine repeat
4. Playback will play through first ending, skip the second ending, go back to the beginning, and then play the first ending again and skips the second ending again

Using the following setup:
OS: macOS 14.7, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.4-243461245, revision: github-musescore-musescore-2232670

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/33af751a-a790-4aca-bf40-72cb75e6791a)

[2nd Volta Playback Issue.mscz.zip](https://github.com/user-attachments/files/18141456/2nd.Volta.Playback.Issue.mscz.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.4

### Regression

I was unable to check

### Operating system

macOS 14.7

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
Pretty much by desing, voltas without repeat barlines don't work
