### ISSUE TITLE
Barlines change shape between staves if one is small staff

### ISSUE THREAD

**Issue by xavierjazz** [musescore/MuseScore#25842]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

https://musescore.org/en/node/372778
[Jojo-Schmitz/MuseScore] 3.7 EVO - barlines change shape between staves if one is small staff. (Issue #725)

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/87887b59-4da2-4a5d-bc20-45b151ccc06f)

### What is the latest version of MuseScore Studio where this issue is present?

4.4

### Regression

I was unable to check

### Operating system

Win 10

### Additional context

![image](https://github.com/user-attachments/assets/0f4688b7-1de7-48b2-a047-e1d8cd077e25)

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
This is not a report for 3.7 Evolution, so better remove that from the title.

It does seem to be a day one issue and indeed annyoed me in the past too

Question is what behavoir is desired here:

1. All connected barlines like for non-small staff
2. All  connected barlines like for small staff
3. Connected barline size follows the size of the barline of the connected to staff
4. Connected barline size follows the size of the barline of the connected from staff
5. If different size, don't connect barlines
6. Keep as it is currently.

Something for @oktophonie I guess?

**Comment by MarcSabatella** [comment]
Note there is a style setting to control whether the barlines scale with staff size or not.  It’s normally off by default, so you shouldn’t see the effect shown here unless you’ve gone out of your way to disable it, or are dealing with an older score created before that option was added.

**Comment by Jojo-Schmitz** [comment]
Oops. That option exists in Mu3 and Mu2 too, but there is ticked by default, so apparently the default changed with Mu4

**Comment by xavierjazz** [comment]
Thanks Marc, I found it, it was invoked (I have no idea how, except it may have been an older score), I changed it and it worked.



Don Naduriak

+1 647 794 8192

***@***.***

https://www.facebook.com/Don-Naduriak-Music-605371769580564/

Mailing list: http://eepurl.com/cwo7jf



________________________________

**Comment by Jojo-Schmitz** [comment]
It is the Mu2 and Mu3 default that is different from Mu4...

**Comment by oktophonie** [comment]
(It seems the default was changed back in https://github.com/musescore/MuseScore/pull/8256, for 4.0).

**Comment by Jojo-Schmitz** [comment]
Thanks for digging that up

**Comment by xavierjazz** [comment]
I'm glad it's all sorted out.

Don Naduriak
647 794 8192
***@***.***
Https://www.facebook.com /Don-Naduriak-Music-605371769580564/
Mailing list: http://eepurl.com/cwo7jf
________________________________
