### ISSUE TITLE
Note Naming Bug: Confusion Between H and B in Sib and Si Notes

### ISSUE THREAD

**Issue by Musi-Coholic** [musescore/MuseScore#25843]
### Issue type

Other type of issue

### Description with steps to reproduce

1. Open a score in Musescore.
2. Hover over a B flat (Sib) note – the program incorrectly displays it as H.
3. Hover over a B (Si) note – the program displays it correctly as B.

### Supporting files, videos and screenshots

This bug occurs in the Hungarian language program, while it does not appear in the English one. I have not checked it in languages ​​other than Hungarian and English.
![Képernyőkép 2024-12-15 190714](https://github.com/user-attachments/assets/3dab1da1-295c-42b9-84c4-252f9d8812d1)
![Képernyőkép 2024-12-15 190630](https://github.com/user-attachments/assets/96b02092-2bc0-4d74-ab42-df5c99a17230)
![Képernyőkép 2024-12-15 190630](https://github.com/user-attachments/assets/0678bef3-bc80-49c2-81a8-0160040d87f8)
![Képernyőkép 2024-12-15 190714](https://github.com/user-attachments/assets/310ee8f9-d49c-4d3c-bff7-8bc4295f2d37)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.4.243461

### Regression

I was unable to check

### Operating system

windows 10pro

### Additional context

This bug occurs in the Hungarian language program, while it does not appear in the English one. I have not checked it in languages ​​other than Hungarian and English.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
So that got to be a translation issue and as such needs to get fixed on Transifex

However: in German B flat (Sib)  is B and B (Si) is H, isn't that the case for Hungarian too?

As per https://de.wikipedia.org/wiki/Anderssprachige_Tonbezeichnungen#%C3%9Cbersicht  the H is used in German, Danish, Norwegian, Swedish (traditional?), Polish, Slovak, Czech, Serbian, Croatian, Hungarian, Latvian (until 1940 and Finish)

Looking at the translations on Transifex for Hungarian, B flat is translated as B and B as H, so everything looks OK to me?

**Comment by Musi-Coholic** [comment]
It would be good not to mix in the German notation, but to stick with the international terminology.
C,  C#,  Db,  D,  D#,  Eb,  E,  F,   F#,  Gb,  G,  G#,  Ab,  A,  A#, Bb,  B

**Comment by Jojo-Schmitz** [comment]
No it is not.
It is a decision to be made by the Hungarian translators. 
And it certainly is not something for this issue tracker here, as there is no bug in the code.
