### ISSUE TITLE
Supporting tuning adjustments (a.k.a. pitch bend) for Muse Strings

### ISSUE THREAD

**Issue by zhenlige** [musescore/MuseScore#25847]
### Your idea

Since microtonal tuning (e.g. making the major third slightly narrower to make it closer to 5/4) is common in strings performances, it would be very useful for Muse Strings to support tuning adjustments. Maybe this is a technical limit, but I hope it can be solved soon.

### Problem to be solved

The current Muse Strings does not support any tuning between semitones (which is useful for both normal and xenharmonic music), while most sounds support.

### Prior art

The MS Basic sounds work, and Muse Keys also works (tested grand piano).

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by zhenlige** [comment]
> This works as expected for me. Be sure you have the current versions of MuseScore Studio (4.4.4), Muse Sampler (0.100.7), and Muse Strings (0.4.23). Run Muse Hub if necessary to update your Muse Sounds installation.

My MuseScore Studio and Muse Strings are the latest. I don't know how to check the version of Muse Sampler (I have searched in Muse Hub but there is no result).

**Comment by zhenlige** [comment]
[帕赫贝尔D大调卡农，但是纯律.zip](https://github.com/user-attachments/files/18152756/D.zip)
At the start of violin 1, the tone between F♯-E should be narrower than the following E-D.
Every note G with “7·” attached should be lower than normal G.
(I am sure I can hear the difference since I can her those with MS Basic)

**Comment by MarcSabatella** [comment]
Many of the adjustments here very small and are probably being dwarfed by the natural variation in pitch in the samples.  Try a larger adjustment and it's more obviously being honored.

**Comment by zhenlige** [comment]
Everything works now. Maybe it's just my ear that is too dumb, or it is an accidental problem.
