### ISSUE TITLE
Page Numbering

### ISSUE THREAD

**Issue by kssmithson54** [musescore/MuseScore#25882]
### Your idea

I would like greater flexibility in MuseScore's page numbering function.

### Problem to be solved

It is customary in published music for a page number to be invisible on the first page of the score. Currently, if page 1 is set to begin on the actual first page of the score the number "1" is visible and cannot be made invisible. Would it be possible to make page numbers the same as any other element in MuseScore which can be made invisible by pressing "v?"

### Checklist

- [X] This request follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting issues
- [X] I have verified that this feature request has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar requests

**Comment by oktophonie** [comment]
If you use the tag `$p` in **Style > Header & footer** for your header or footer, the page number will not appear on the first page. Or you can use `$P` and untick **Show on first page**.

**Comment by Jojo-Schmitz** [comment]
That `$p` is even the default along with the header to not show on 1st page.
However, there's a difference between 1st page and page 1, as soon as you use the page number offset in Format > Page settings the above mentioned setting go pear-shape.
Like setting that page number offset to -1, wanting the first 2 pages (cover page, front and back) to not show any page number, and the 3rd page, the actual page number 1, to not show a page number.

**Comment by kssmithson54** [comment]
Thank you for your very speedy reply, Simon! My problem is that I have
appended a title page to the start of this score. I have set the title page
to "0" in order to force page 1 to the first actual page of the score.
Indeed, the page number does not appear on my "0" page (which is page 1 as
far as MuseScore is concerned) but the number one is at the top of the
first page of the score and should be invisible. The first number I want to
see is a "2" on the next page. Currently it isn't possible to achieve this
and it is, in fact, the industry norm.

I have to say that, despite this issue, I am enjoying MuseScore
tremendously and have found that it solves many of the problems I
encountered with Finale. I've only been using MuseScore for a month and am
just blown away by its capabilities.

Many thanks!
Karen

**Comment by Jojo-Schmitz** [comment]
Here's the code
```cpp
            Char c = s.at(i);
            if (c == '$' && (i < (n - 1))) {
                Char nc = s.at(i + 1);
                switch (nc.toAscii()) {
                case 'p': // not on first page 1
                    if (!m_no) {
                        break;
                    }
                // FALLTHROUGH
                case 'N': // on page 1 only if there are multiple pages
                    if ((score()->npages() + score()->pageNumberOffset()) <= 1) {
                        break;
                    }
                // FALLTHROUGH
                case 'P': // on all pages
                {
                    int no = static_cast<int>(m_no) + 1 + score()->pageNumberOffset();
                    if (no > 0) {
                        const String pageNumberString = String::number(no);
                        const CharFormat pageNumberFormat = formatForMacro(String('$' + nc));
                        // If the default format equals the format for this macro, we don't need to create a new fragment...
                        if (defaultFormat == pageNumberFormat) {
                            newFragments.back().text += pageNumberString;
                            break;
                        }
                        TextFragment pageNumberFragment(pageNumberString);
                        pageNumberFragment.format = pageNumberFormat;
                        newFragments.emplace_back(pageNumberFragment);
                        newFragments.emplace_back(TextFragment());    // Start next fragment
                    }
                }
                break;
```
The comment `not on first page 1` doesn't match the code, but is rather `not on first page`
I believe it would match if the code where
```cpp
                    if (!(m_no + score()->pageNumberOffset())) {
```

**Comment by kssmithson54** [comment]
Thanks, Joachim. I'll do my best to sort this out. It sounds like I should
go back to the default and start again from there. I appreciate your help.

Karen
