### ISSUE TITLE
Wrong display of clefs when using custom templates

### ISSUE THREAD

**Issue by hefnar** [musescore/MuseScore#25905]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

made a custom template for a male choir with some style edits...

1. changed the clefs of both voice staves (standard treble clef) to treble 8va and bass clef respectively
2. saved the file in the template folder
3. opening this custom template, normal treble clefs are shown
4. but they still retain the behaviour of treble 8va and bass clef 

expected behaviour: clefs are displayed the way i configured them and sound like i configured them
actual behaviour: clefs are display as normal treble clefs but retain the sound of the clefs i configured, confusing af

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/606c5a4b-608b-4e58-adb2-ca4f08314c12
[templatescore.zip](https://github.com/user-attachments/files/18221826/templatescore.zip)
[score using template with wrong clefs.zip](https://github.com/user-attachments/files/18221828/score.using.template.with.wrong.clefs.zip)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.4

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
Not a regression at all, been the cse ever since.

Also this won't happen if you use Tenor and Bass as the 'instruments' from the start rather than Voice (and change those to Tenor and Bass)
Like the attached
[Male Choir.zip](https://github.com/user-attachments/files/18221914/Male.Choir.zip)

**Comment by hefnar** [comment]
didn't think you would answer on a sunday and also that fast, thank you.

thank you for the fix. i will use it.
didn't want to use the barbershop template as i made several style changes to my template.

but still, retaining the effect of the clefs i specified while displaying another clef seems very odd to me?

**Comment by Jojo-Schmitz** [comment]
One possible bug I see is that the 'Voice' instrument should probably default to the G clef optional ottava bassa (the litlle 8 in parens)
