### ISSUE TITLE
Crash when attempt to move slur anchor

### ISSUE THREAD

**Issue by BLumia** [musescore/MuseScore#25901]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Open the mscz file provided in the attachment below
2. Click any slur on the sheet (*not* TAB)
3. When the slur is selected, press <kbd>Shift+↓</kbd> (shift + arrow down)
4. See crash

### Supporting files, videos and screenshots

[crash.zip](https://github.com/user-attachments/files/18053398/crash.zip) (see the reproduce steps above to see how to use this attachment)

https://github.com/user-attachments/assets/fb05c020-df4e-41d6-8f1a-2f999602625d

### What is the latest version of MuseScore Studio where this issue is present?

4.4.4

### Regression

I was unable to check

### Operating system

macOS 15.1.1, Windows 11 24H2, Arch Linux rolling

### Additional context

https://github.com/musescore/MuseScore/pull/25777 fixes the crash by adding a `nullptr` check.

The bug is tested under both Windows, macOS and Linux, the fix (PR) linked above was tested under Arch Linux.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
Mu3 doesn't crash opn this, so a Mu3 regression
