### ISSUE TITLE
Musescore playback glitching on Windows 10

### ISSUE THREAD

**Issue by NathanGithub2013** [musescore/MuseScore#25900]
### Issue type

General playback bug

### Description with steps to reproduce

1. Open the score (on Windows 10)
2. Play the score using Musescore
3. Enjoy the disaster

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/2fcb9777-f885-4600-b17a-c787e771e298

https://github.com/user-attachments/assets/9907dc06-eb5f-4a2d-853a-33fca7c2820e

[Proud Of You (old).zip](https://github.com/user-attachments/files/18220791/Proud.Of.You.old.zip)

### What is the latest version of MuseScore Studio where this issue is present?

Version 4.4.4.243461245

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10 Pro for Workstation

### Additional context

Musescore 4.3 and prior used to playback smoothly on my PC, when updating to MS 4.4.4, the playback got glitches and noise. When played on a Windows 11 laptop, the playback works good unlike on Windows 10.
I even tried to change the audio sample rate on the PC and the problem is still there, I tried both Muse Sounds and MS Basic and both performed crappy on the Windows 10 PC but works fine on the Windows 11 laptop

The Windows 10 Pc I used : Sony Vaio VPCJ2, Intel Core i5 2520M, 8 GB RAM, 128 SSD
The Windows 11 Laptop I used : Tosihba Dynabook R63/P (Model Toshiba Portege Z30-B Series) Intel Core i5-5200U, 12 GB RAM, 256 SSD

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by NathanGithub2013** [comment]
+1 info : I used the latest nightly build of MuseScore Studio and the problem isn't solved "yet"

**Comment by NathanGithub2013** [comment]
+1 info : Musescore version : OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.4-243461245, revision: github-musescore-musescore-2232670

**Comment by MarcSabatella** [comment]
What did you change the sample rat e *to*?  Usually 44.1 kHz is the best on Windows from what I have experienced.

If you have further trouble please use the Support forum at musescore.org to ask for help.

**Comment by NathanGithub2013** [comment]
I used 44.1 kHz and 48 kHz but problem not fixed

**Comment by RomanPudashkin** [comment]
Have you tried changing the buffer size in the preferences (to 2048 or 4096)?
<img width="885" alt="Screenshot 2024-12-23 at 10 38 39" src="https://github.com/user-attachments/assets/edb85e18-6172-49bc-9d9c-9f3526b37b54" />

**Comment by SteveBlower** [comment]
Perhaps your Win 10.machine is underpowered for Musescore 4

Intel Core i5 2520M spec

https://www.intel.com/content/www/us/en/products/sku/52229/intel-core-i52520m-processor-3m-cache-up-to-3-20-ghz/specifications.html

i.e. 2 core

System requirements https://musescore.org/en/download#System-requirements

*"4 core (8 recommended)"*

It is surprising that it worked ok with earlier versions of MU 4 though and only baulks at 4.4.4.

**Comment by NathanGithub2013** [comment]
the PC usually perform smoothly on creative software except musescore at 4.4.4

**Comment by NathanGithub2013** [comment]
> Have you tried changing the buffer size in the preferences (to 2048 or 4096)? <img alt="Screenshot 2024-12-23 at 10 38 39" width="885" src="https://private-user-images.githubusercontent.com/67867444/398105376-edb85e18-6172-49bc-9d9c-9f3526b37b54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTYyNDgsIm5iZiI6MTczNDk1NTk0OCwicGF0aCI6Ii82Nzg2NzQ0NC8zOTgxMDUzNzYtZWRiODVlMTgtNjE3Mi00OWJjLTlkOWMtOWYzNTI2YjM3YjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDEyMTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMDc1MTg0ZWQwODFjYjQ5NTQ4YjI1YjI1NDAxOGI1YThhYjM0ZjFiZWM3YTQ2YWY0ODAzNWFiOWY4M2M0MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OQ1YCWkTSKAEiyNh9FrdW8YyQQNTsww7UQOzI0OpHhk">

Oh, that finally works, so basically my PC won't go smoothly with buffer at 1024 and 512. Thanks a lot to Roman and the community for helping me out. I love musescore's open source-ness

**Comment by NathanGithub2013** [comment]
"oh and thanks to Musescore community to made Musescore studio 4 what it is today. I don't have any word for the community's work in building Musescore studio 4 into this perfect" I <3 OPEN SOURCE
