### ISSUE TITLE
Some Soundfonts are Incorrect

### ISSUE THREAD

**Issue by Fourniture** [musescore/MuseScore#25928]
### Issue type

General playback bug

### Description with steps to reproduce

If a user tries to create a score with instruments including whip and thunder sheet, the sound in the score is strange, and only remotely resembles the actual instrument. If one tries to find the source of the strange sound in the mixer's options, it is not to be found, either in MS Basic or MuseSounds. There may be other missing instruments like this, but these are the two I was able to find.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/abc94be6-c222-4388-8865-778b5f7809cf

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.4-243461245, revision: github-musescore-musescore-2232670

### Regression

I was unable to check

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
This isn't a bug - those sounds simply aren't part of the General MIDI standard an d thus aren't part of the default soundfont.  It is of course a valid feature to add these and/or other non-GM sounds.  But it is obviously impossible to have every possible sound in the default soundfont.  For sounds not part of the default, you can try to find and install a third party soundfont.

**Comment by MarcSabatella** [comment]
Feel free to submit a feature request for that as well.  The trick would be in deciding which substitutions are far enough off to need it.  For horn in Eb, the fact that MuseScore substitute a horn in F is not worth mentioning.  For cornet, the fact that it substitutes trumpet is slightly worth mentioned.  For euphonium, the fact that tuba is substituted is more worth knowing, etc.  So if you do open a new feature request, I'd encourage you to first discuss it on the forums at musescore.org and try to arrive at a consensus there before opening an issue that will require further discussion on GitHub to clarify.

**Comment by Fourniture** [comment]
I prefer to keep the popup discussion here, as it is very closely intertwined with the issue above. I would consider it a temporary fix of sorts until a proper compromise can be reached. It should not be difficult for development to assign general midi sounds that are close enough (along with the message notifying the user), or to simply create samples for it. (I intend to raise a request to the MuseSounds team for that.)

**Comment by MarcSabatella** [comment]
GitHub issues are not the place to brainstorm ideas - they are for simple, clearly stated descriptions of a bug, or simple, clearly stated design proposals for a new feature.  And it's important to keep one bug or one feature request per issue - otherwise tracking becomes impossible.  And please keep more open ended discussions in the forums - that is what they are there for.

Meanwhile, it's already the case that each instrument has a "close enough" sound assigned.  If you have suggestions for a closer sound from within the default libraries for these particular instruments (thunder sheet and whip), feel free to edit your original description to add that.

**Comment by Fourniture** [comment]
Thank you for clarifying; I didn't want to load down the team with (seemingly unnecessarily) subdivided issues.
