### ISSUE TITLE
Straight flags are too short in Emmentaler

### ISSUE THREAD

**Issue by VighneshJadha** [musescore/MuseScore#25930]
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. create score
2. change font to Emmentaler (MScore)
3. add notes with isolated flags
4. select flags
5. change flag type to straight

Expected: Straight flags should display their normal size
Actual: They're too short

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/454dd33f-063e-48d8-bec6-3dc79ea7c037

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.4-243461245, revision: github-musescore-musescore-2232670

### Regression

No.

### Operating system

Windows 11

### Additional context

This is a score of Pyotr Ilyich Tchaikovsky's Lebedínoje Ózero.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by oktophonie** [comment]
Emmentaler doesn't have straight flags. These are Bravura's which are used as a fallback. Their design is quite intentional (but if you dislike them you could take it up with Steinberg.)

**Comment by VighneshJadha** [comment]
How to increase the size of the straight flags?

**Comment by MarcSabatella** [comment]
By switching to a font that has longer ones, like the default Leland.

For further questions on how to use MuseScore, please ask on the support forum at musescore.org
