### ISSUE TITLE
Could not find a package configuration file provided by "Qt6NetworkAuth" Ubuntu Linux

### ISSUE THREAD

**Issue by JacobChrist** [musescore/MuseScore#25944]
### Issue type

Other type of issue

### Description with steps to reproduce

1. Cloned repo head at sha: 3ef08b199c2080b5d319da79b19ae650e03b5616
2. cd MuseScore
3. cmake -P build.cmake -DCMAKE_BUILD_TYPE=Release
4. Building fails, see below:

### Supporting files, videos and screenshots

```
CMake Error at buildscripts/cmake/SetupQt6.cmake:60 (find_package):
  By not providing "FindQt6NetworkAuth.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt6NetworkAuth", but CMake did not find one.

  Could not find a package configuration file provided by "Qt6NetworkAuth"
  with any of the following names:

    Qt6NetworkAuthConfig.cmake
    qt6networkauth-config.cmake

  Add the installation prefix of "Qt6NetworkAuth" to CMAKE_PREFIX_PATH or set
  "Qt6NetworkAuth_DIR" to a directory containing one of the above files.  If
  "Qt6NetworkAuth" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:160 (include)


-- Configuring incomplete, errors occurred!
See also "/home/jacob/opt/MuseScore/builds/Linux-Qt-usr-Make-Release/CMakeFiles/CMakeOutput.log".
CMake Error at build.cmake:232 (message):
  Configure step failed with status 1.  See output above for details.
```

### What is the latest version of MuseScore Studio where this issue is present?

sha: 3ef08b199c2080b5d319da79b19ae650e03b5616

### Regression

I was unable to check

### Operating system

Linux 6.8.0-50-generic #51~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

### Additional context

None

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
You need to install `Qt6NetworkAuth`. If you're using the Qt Online Installer, see https://github.com/musescore/MuseScore/wiki/Install-Qt-and-Qt-Creator#select-qt-components; if you're installing Qt via a package manager, you could try to install something like https://packages.debian.org/sid/qt6-networkauth-dev.

**Comment by JacobChrist** [comment]
@cbjeukendrup Should I create a issue to update the wiki that describes setting up the build environment?

**Comment by cbjeukendrup** [comment]
It looks like everything is already in the Wiki, but on this page: https://github.com/musescore/MuseScore/wiki/Install-Qt-and-Qt-Creator
(it turns out that the need to install `qt6-networkauth-dev` (if you're using a package manager) is described at https://github.com/musescore/MuseScore/wiki/Install-Qt-and-Qt-Creator#debian-based-systems.)

**Comment by JacobChrist** [comment]
@cbjeukendrup I see my mistake.  There was no specific instructions on installing Qt on this page: https://github.com/musescore/MuseScore/wiki/Set-up-developer-environment but I do see a little blurb about installing and compiling Qt binaries at the top of the page.  It would be nice if there was a link on this page that pointed to the installation instructions you provided (which I haven't gotten around to testing yet).

**Comment by JacobChrist** [comment]
@cbjeukendrup When I try to install Qt 6 from the command based on the instructions from the Wiki I get some missing packages.  I'm on Ubuntu 22.04.  I'm trying to figure this out on my own just reporting back.

```
linux:~/opt/MuseScore$ sudo apt install qt6-base-dev qt6-base-private-dev qt6-networkauth-dev qt6-declarative-dev qt6-svg-dev qt6-tools-dev qt6-5compat-dev qml6-module-qtqml-statemachine libqt6statemachine6 qt6-scxml-dev libsndfile1-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package qt6-networkauth-dev
E: Unable to locate package qt6-svg-dev
E: Unable to locate package qt6-5compat-dev
```
