### ISSUE TITLE
Bad quality Clarinet synth

### ISSUE THREAD

**Issue by IkeKap** [musescore/MuseScore#3042]
In all honesty, I really find the sound of the Clarinet inside the software really bad. It applies to both the sound within the website as well as the standalone software. Whenever I play a tune with the synth, my speakers start crackling and buzzing (happened on several different computers). The sound does not feel authentic at all. I really like the rest of the software, but I would really like the B flat clarinet audio issues to be fixed

**Comment by MarcSabatella** [comment]
The clarinet sound is a known issue.  Please use the support forum when discussing issues with MuseScore.
