### ISSUE TITLE
PR candidates to be merged to MuseScore 3.3 Beta

### ISSUE THREAD

**Issue by anatoly-os** [musescore/MuseScore#5283]
The following PRs fix the P0 and P1 issues from the issue tracker or were suggested by the community or selected by in-house team.

Included to MuseScore 3.3 Beta:

- [x] https://github.com/musescore/MuseScore/pull/5287
- [x] https://github.com/musescore/MuseScore/pull/5090
- [x] https://github.com/musescore/MuseScore/pull/5246
- [x] https://github.com/musescore/MuseScore/pull/5139
- [x] https://github.com/musescore/MuseScore/pull/4545
- [x] https://github.com/musescore/MuseScore/pull/3633
- [x] https://github.com/musescore/MuseScore/pull/5145
- [x] https://github.com/musescore/MuseScore/pull/4846
- [x] https://github.com/musescore/MuseScore/pull/5182
- [x] https://github.com/musescore/MuseScore/pull/4878
- [x] https://github.com/musescore/MuseScore/pull/4196
- [x] https://github.com/musescore/MuseScore/pull/5277
- [x] https://github.com/musescore/MuseScore/pull/5261
- [x] https://github.com/musescore/MuseScore/pull/5279
- [x] https://github.com/musescore/MuseScore/pull/5175
- [x] https://github.com/musescore/MuseScore/pull/5242
- [x] https://github.com/musescore/MuseScore/pull/5284
- [x] https://github.com/musescore/MuseScore/pull/5250
- [x] https://github.com/musescore/MuseScore/pull/5116
- [x] #5282
- [x] https://github.com/musescore/MuseScore/pull/5280
- [x] https://github.com/musescore/MuseScore/pull/4974
- [x] https://github.com/musescore/MuseScore/pull/5150
- [x] https://github.com/musescore/MuseScore/pull/5271
- [x] Partially merged https://github.com/musescore/MuseScore/pull/4885 (add accordion palette, remove bagpipe embellishment) 
- [x] https://github.com/musescore/MuseScore/pull/5258
- [x] https://github.com/musescore/MuseScore/pull/3461
- [x] https://github.com/musescore/MuseScore/pull/5251
- [x] https://github.com/musescore/MuseScore/pull/5286
- [x] https://github.com/musescore/MuseScore/pull/5285

**Comment by jthistle** [comment]
Can I also suggest #5282?

**Comment by Jojo-Schmitz** [comment]
I believe #5250 won't harm either, nor would #5175. You may want #5214 too.
#3163 is waiting since ages, regardless a 'Priority' tag.
And I still believe #4370 would help users

**Comment by Howard-C** [comment]
Won't #5284 be so good to merge :)))
If it doesn't cause any trouble further, I mean.

**Comment by RobFog** [comment]
"questionable" means "dubious" ([Synonyms at Merriam-Webster](https://www.merriam-webster.com/thesaurus/questionable)). I think you may be wanting to use a word like "unclear"?

**Comment by Jojo-Schmitz** [comment]
Mind to also consider #5286 and #5285?

**Comment by jthistle** [comment]
#5293? It's a P1 issue.

**Comment by anatoly-os** [comment]
@jthistle #5293 is up to the second Beta. See #5298.
