### ISSUE TITLE
PR candidates to be merged to MuseScore 3.3 Beta 2

### ISSUE THREAD

**Issue by anatoly-os** [musescore/MuseScore#5298]
Pull requests in the list fix the P0 and P1 issues from the issue tracker or were suggested by the community or selected by in-house team.

- [ ] https://github.com/musescore/MuseScore/pull/4883 (unclear motivation)
- [x] https://github.com/musescore/MuseScore/pull/4879 (unclear motivation)
- [x] https://github.com/musescore/MuseScore/pull/5270
- [x] https://github.com/musescore/MuseScore/pull/5269 (needs manual testing and cherry-picking changes)
- [ ] https://github.com/musescore/MuseScore/pull/5259 (selection is an error-prone field)
- [x] https://github.com/musescore/MuseScore/pull/5214 (affects only WINSTORE builds, not relevant now)
- [x] https://github.com/musescore/MuseScore/pull/3163 (work in progress, unaddressed review, needs thorough testing, not urgent?)
- [x] https://github.com/musescore/MuseScore/pull/4370 (unclear motivation)
- [x] https://github.com/musescore/MuseScore/pull/5255 (unaddressed review)
- [ ] https://github.com/musescore/MuseScore/pull/4916
- [x] https://github.com/musescore/MuseScore/pull/4443 (unaddressed review, rebase needed)
- [x] https://github.com/musescore/MuseScore/pull/5291
- [x] https://github.com/musescore/MuseScore/pull/5293
- [x] https://github.com/musescore/MuseScore/pull/5295
- [x] https://github.com/musescore/MuseScore/pull/5037 (rebase needed)
- [x] https://github.com/musescore/MuseScore/pull/5297
- [x] https://github.com/musescore/MuseScore/pull/4957

Included to MuseScore 3.3 Beta 2:

**Comment by Jojo-Schmitz** [comment]
Please consider #5291 and #5297

**Comment by jthistle** [comment]
I very much like that we're organizing things like this, but GitHub does provide the 'milestone' feature for exactly things like this - maybe it would make it slightly easier to do it like that for the next milestone? Just an idea :)

**Comment by anatoly-os** [comment]
@jthistle I tried to organise the project, but it was something different. I'll take a look, thanks!

**Comment by jthistle** [comment]
Yes, projects are more for full workflows, i.e. you put a bug in the first column, someone takes it on and moves it to the next column, when it's fixed it gets moved on and so on. It works well for smaller projects, but isn't really what we want here, AFAIK. Milestones seem like exactly what we might want though; it's just a way of tagging PRs to be merged for a specific date/version.

**Comment by mattmcclinch** [comment]
Please also consider #5295, as it fixes a recent regression.

**Comment by Howard-C** [comment]
Maybe #5300?

**Comment by DLLarson** [comment]
PR 5259 has the comment "selection is an error-prone field". 

How so? It's an additive feature so can't break existing code. The code changes are not complex.

No inspection comments have been made to support this judgement.

-Dale
