### ISSUE TITLE
Cannot Display Lyrics Properly in MIDI Files

### ISSUE THREAD

**Issue by fortfall** [musescore/MuseScore#5301]
### Issue Description
1. Add lyric events to a MIDI file.  
2. Open the MIDI file in MuseScore.  
Lyric texts without a note on event at the same ticks are not displayed.  
As illustrated in the attachment, some lyric texts are displayed under both staff, while some are displayed under just one staff (staff having a note on event at the same time). If neither staff has a note on event at the same ticks, the lyric text is not displayed.  
![E6D98028-63DF-42CE-A14A-471D67883005](https://user-images.githubusercontent.com/37922313/64258913-a4c6a980-cf5a-11e9-99f4-f2ab776c120d.png)

**Comment by Howard-C** [comment]
Please use the support forum (https://musescore.org/forum) for help or the issue tracker (https://musescore.org/project/issues) for bug reports.

**Comment by fortfall** [comment]
> Please use the support forum (https://musescore.org/en/forum/6) for help or the issue tracker (https://musescore.org/project/issues) for bug reports.

Resubmitted in issue tracker provided.

**Comment by fortfall** [comment]
> Please use the support forum (https://musescore.org/en/forum/6) for help or the issue tracker (https://musescore.org/project/issues) for bug reports.

Resubmitted in issue tracker provided.
