### ISSUE TITLE
Translation problem in finnish: OK or OK

### ISSUE THREAD

**Issue by rnielikki** [musescore/MuseScore#5348]
In "Edit -> Instruments (In finnish, Muokkaa -> Instrumentit)" dialog,
both buttons(OK/Cancel) are "OK". (Cancel sholud be "Peruuta")

![ok_or_ok](https://user-images.githubusercontent.com/5599742/65661676-ed91ef80-e03a-11e9-86a4-59cdc0e51165.jpg)

**Comment by Howard-C** [comment]
Please post this in the official Translation forum: https://musescore.org/en/forum/9.

**Comment by diligamer** [comment]
### OK
Ok
