### ISSUE TITLE
MuseScore 3.5 Alpha PRs to be merged

### ISSUE THREAD

**Issue by anatoly-os** [musescore/MuseScore#5960]
Leave a comment with the links to the PRs you think are worth merging to MuseScore 3.5 Alpha.

**Comment by MarcSabatella** [comment]
The ones I have had my eye on are:

#5812 
#5919 
#5947 or #5728

As I look through the list, I see a whole bunch of others that I'd love to see even though I haven't really looked at them.  See for instance:

#5886 and #5887 
#5881 (this one can affect layout, though)
#5841 and #5834

**Comment by shoogle** [comment]
#5890
#5959
#5962
#4757

**Comment by Spire42** [comment]
The following PR is an important one to merge for 3.5:

* [PR #5820 · Fix #302114: Wrong default GUI font under Windows](https://github.com/musescore/MuseScore/pull/5820)

These two others aren't as important but are also useful small fixes that are both simple and safe to merge in:

* [PR #5784 · Fix #301929: No reminder to save, if you quit program before entering anything in a new score](https://github.com/musescore/MuseScore/pull/5784)
* [PR #5891 · Fix #303194: Wrong working directory when MuseScore is launched via a file association under Windows](https://github.com/musescore/MuseScore/pull/5891)

**Comment by Howard-C** [comment]
I would say #5956, #5929, #5871, #5644.

**Comment by Jojo-Schmitz** [comment]
* #5944
* #5943
* #5930 
* #5861
* #5862
* #5900
* #5381
* #5859
* #4872
* #5679
* #5634
* #4798
* #5642
* #5953
* #5957

**Comment by njvdberg** [comment]
[#5918 ]

**Comment by blackears** [comment]
#5808 
#5807 
#5813 
#5814

**Comment by SKefalidis** [comment]
Since @MarcSabatella referenced some of my text editing related PRs I believe that the following are also nice improvements:
#5875
#5870 
#5884 (if #5881 is merged, this one follows the same logic)

**Comment by Marr11317** [comment]
#5854 
#5646 
#5628
These are not mine, but I would really love it if they could be part of 3.5
#5795 
#5829 
#5779 
#5381 
#5414

**Comment by Marr11317** [comment]
and mtest for msvc (#5954 ), since it might help with incoming bug fixes

**Comment by shoogle** [comment]
#5760

**Comment by Jojo-Schmitz** [comment]
> These are not mine, but I would really like it if they could be part of 3.5
> #5795

That needs help of a designer for better icons.

**Comment by Howard-C** [comment]
#5972

**Comment by jthistle** [comment]
#5715 would be good, it doesn't affect anything else.

**Comment by anatoly-os** [comment]
Ok, 23 PRs left. If you want to suggest more PRs, please add them as a new comment, don't edit the existing comments.

**Comment by Jojo-Schmitz** [comment]
* [ ] #5976

**Comment by Spire42** [comment]
[ ] #5674

**Comment by Philzen** [comment]
- [ ] #5911

**Comment by Howard-C** [comment]
- [ ] #5888
- [ ] #5889

**Comment by Jojo-Schmitz** [comment]
How about this?
* [ ] #5657

**Comment by MarcSabatella** [comment]
Other than my pair of text style fixsd #5947 and #5728 (two different solutions to same problem) that are already listed, I have one other pending PR from a year ago, fixing a bug in transposition, I'd like to see added.  I did rebase & update it recently and it does seem to work well.

- [ ] #4916

**Comment by IsaacWeiss** [comment]
#5560

**Comment by blackears** [comment]
#5985

**Comment by Howard-C** [comment]
#5987

**Comment by Howard-C** [comment]
#5996

**Comment by anatoly-os** [comment]
Ok, the remaining ones are:

- [ ] #5744
- [ ] #5911
- [ ] #5922
- [ ] #5979 or  #5980
- [ ] #5886 and #5887
- [ ] #4757
- [ ] #5934
- [ ] #4824
- [ ] #5508
- [ ] #5829
- [ ] #5779
- [ ] #5760
- [ ] #5715

**Comment by Jojo-Schmitz** [comment]
There's still

[ ] #5817

**Comment by njvdberg** [comment]
[ ] #5965 
[ ] #6003

**Comment by SKefalidis** [comment]
#6005 ( relates to #5922 )

**Comment by blackears** [comment]
#5808

**Comment by shoogle** [comment]
- [ ] #6006 (fixes regression caused by ~#5982~)

**Comment by IsaacWeiss** [comment]
- [ ] #5811 (adds a small new feature, not interpreted by older versions, but loads just fine)
- [ ] #5888 (minor UI improvement)
- [ ] #6008 (minor UI improvement)

**Comment by AntonioBL** [comment]
If I am not too late:
[-] https://github.com/musescore/MuseScore/pull/5614

**Comment by anatoly-os** [comment]
No more pull requests with NEW functionality will be accepted.

**Comment by worldwideweary** [comment]
Regarding some of my old PRs from December 2019/Jan? 

PR #5564: Page width shortcut, 
PR #5623: Extra default zoom preferences (still marked with x with no explanation/travis update even though runs fine and passes local mtest),
PR #5568: Update range transposition shortcut to selection only, 
PR #5637: Same Beat/Measure options in select all similar dialogue,
PR #5620: Some extra navigation shortcuts to be defined by users if they should like.

By now some might need a rebase actually since it's been so long and never were merged.

**Comment by shoogle** [comment]
- [ ] #6016 (reverts ~#5380~)

**Comment by Howard-C** [comment]
> * [ ]  #6016 (reverts ~#5380~)

- [ ] Or #6017

**Comment by blackears** [comment]
#6014 This fixes a translation issue.

**Comment by anatoly-os** [comment]
3.5alpha branch has been created.
