### ISSUE TITLE
Icons too large

### ISSUE THREAD

**Issue by ArchieMaclean** [musescore/MuseScore#5990]
Kubuntu (Ubuntu version 18.04.4 LTS), MuseScore 3.4.2

Icons are too large.

My whole screen:
![image](https://user-images.githubusercontent.com/52914821/80289910-b5ba6a00-8739-11ea-8d80-cffd6452c620.png)

Screen resolution is 1920x1080.

Let me know if you need any more information :)

**Comment by Jojo-Schmitz** [comment]
We don't use github issues, but https://musescore.org/en/node/add/project_issue?pid=1236

**Comment by MarcSabatella** [comment]
Indeed. But probably your OS is not detecting/reporting the true monitor resolution (in DPI) correctly, so you’ll need to use “-D 180” or whatever
