### ISSUE TITLE
Logo Concept (removes the fermata mark)

### ISSUE THREAD

**Issue by diligamer** [musescore/MuseScore#6026]
This Issue Was Made Because Tantacrul In His Video About MuseScore Laughed About The Fermata Mark, So This Fixes It. The Concept Is Seen Here:
![image](https://user-images.githubusercontent.com/32780515/80912040-d9397200-8d42-11ea-94ac-07ac0eafda49.png)

**Comment by Howard-C** [comment]
Bad idea to me. Besides, we don't use github issues for suggestions or bug reports, please use musescore.org/forum.
