### ISSUE TITLE
no workspace find

### ISSUE THREAD

**Issue by zhouzhihao07** [musescore/MuseScore#6042]
![图片](https://user-images.githubusercontent.com/8677018/81032644-34926e00-8ec3-11ea-8df3-04fbf9300f69.png)

**Comment by Howard-C** [comment]
我们不使用GitHub上的问题追踪器，请到https://musescore.org/en/forum反馈漏洞或提出建议，中文论坛https://musescore.org/zh-hans/forum当然也可以但是很冷清。

**Comment by Jojo-Schmitz** [comment]
We don't use GitHub's issue tracker
