### ISSUE TITLE
Travis CI validation issues

### ISSUE THREAD

**Issue by cclauss** [musescore/MuseScore#6098]
`matrix` --> `jobs`, `dist`, `os`, `sudo` as discussed in #6097
![MuseScore Travis](https://user-images.githubusercontent.com/3709715/82333281-cda6a600-99e6-11ea-8400-cc19d94a770b.png)

**Comment by Jojo-Schmitz** [comment]
We're not using GitHub's issues for this purpose, please enter this into the [issue tracker on musescire.org](https://musescore.org/en/node/add/project_issue?pid=1236)
