### ISSUE TITLE
make release failed [MacOS]

### ISSUE THREAD

**Issue by LaiZhou** [musescore/MuseScore#6150]
MacOS:

`-- ALSA support disabled
CMake Error at CMakeLists.txt:438 (message):
  Error: PulseAudio support requested (BUILD_PULSEAUDIO=ON), but PulseAudio
  was not found.

-- Found lame: /usr/local/Cellar/lame/3.100/lib/libmp3lame.dylib
-- JACK (Jack Audio Connection Kit) >= 0.98.0 found. jack support enabled.
PortAudio found. PortAudio support enabled. INCDIR /usr/local/Cellar/portaudio/19.6.0/include, LIBDIR /usr/local/Cellar/portaudio/19.6.0/lib, LIB -L/usr/local/Cellar/portaudio/19.6.0/lib -lportaudio -framework CoreAudio -framework AudioToolbox -framework AudioUnit -framework Carbon
libvorbis detected /usr/local/Cellar/libvorbis/1.3.6/include /usr/local/Cellar/libvorbis/1.3.6/lib -L/usr/local/Cellar/libvorbis/1.3.6/lib -lvorbis
libogg detected /usr/local/Cellar/libogg/1.3.3/include /usr/local/Cellar/libogg/1.3.3/lib -L/usr/local/Cellar/libogg/1.3.3/lib -logg
libsndfile detected /usr/local/Cellar/libsndfile/1.0.28/include /usr/local/Cellar/libsndfile/1.0.28/lib -L/usr/local/Cellar/libsndfile/1.0.28/lib -lsndfile
-- Precompiled header generation
Configuring telemetry
Configuring google_analytics
Configuring global
-- Creating directory /Users/zhoulai/Downloads/MuseScore-3.4.2/build.release/include/freetype/config
-- Creating file /Users/zhoulai/Downloads/MuseScore-3.4.2/build.release/include/freetype/config/ftconfig.h
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Creating file /Users/zhoulai/Downloads/MuseScore-3.4.2/build.release/include/freetype/config/ftoption.h
-- Configuring incomplete, errors occurred!
See also "/Users/zhoulai/Downloads/MuseScore-3.4.2/build.release/CMakeFiles/CMakeOutput.log".
make[1]: *** No rule to make target `lrelease'.  Stop.
make[1]: *** No targets specified and no makefile found.  Stop.
make: *** [release] Error 2`

**Comment by Jojo-Schmitz** [comment]
We don't use Github's issue tracker, either go to musescore.org or to the developers chat on Telegram
