### ISSUE TITLE
Web Music Reader

### ISSUE THREAD

**Issue by isc30** [musescore/MuseScore#6165]
Hi, I'm working on an interactive tool to play scores with MIDI instruments in the browser and I would love to use the web reader from MuseScore. Is there any place I can look at to be able to use this?
Thanks

**Comment by njvdberg** [comment]
We don't use GitHub's issue tracke for this purpose, go to the forums on musescore.com or the developers' chat on Telegram

**Comment by isc30** [comment]
Can you point me to that chat? Thanks

**Comment by Jojo-Schmitz** [comment]
https://t.me/musescoreeditorchat
