### ISSUE TITLE
MIDI Import Improvement: Recognizing multiple instrument changes in a MIDI track

### ISSUE THREAD

**Issue by Sijiba** [musescore/MuseScore#6169]
When importing a MIDI file, a menu appears to give the option for each track's instrument to be set automatically, which I've found very useful. However, this feature only recognizes 1 instrument per track, which causes information to be lost if there are multiple instrument change events in a track.

I suggest that the MIDI import menu be expanded to do the following:
- list every instrument change in every track when the file is loaded, with some indicator to its position in the track.
- When "apply" is clicked, add an appropriately named "Change Instrument" element at each selected event's location starting on the second instrument marker, leaving the first as the track's primary instrument like it currently does.

**Comment by Jojo-Schmitz** [comment]
We're not using the GitHub issue tracker but out own on musescore.org
