### ISSUE TITLE
Feature request: Improve custom key signature input

### ISSUE THREAD

**Issue by ketsuban** [musescore/MuseScore#6200]
I think the custom key signature dialog box is a bit sad.

1. When you first add an accidental to the stave, the place it actually appears on the staff doesn't correspond terribly closely to where the mouse cursor is.
2. The positioning is completely manual, so it's virtually impossible to produce a professional-looking key signature (by which I mean one which matches the spacing of the builtins) and very possible to make ridiculous key signatures like a single accidental located five miles to the left of the start of the bar.

**Comment by Marr11317** [comment]
We don't use github issues except for development purposes. Use the musescore.org [issue tracker](https://musescore.org/en/project/issues/musescore) or [forum](https://musescore.org/en/forum) instead instead.
