### ISSUE TITLE
We can upload for free but we can not DOWNLOAD for free???

### ISSUE THREAD

**Issue by pluveto** [musescore/MuseScore#6323]
I don't have a international credit card or a paypal account. I can not download anymore.

**Comment by Howard-C** [comment]
This is intended, so there's no use of complaining about it. Also, this is the wrong place. For issues about the MuseScore software, go to the forums or the issue tracker on https://musescore.org. For issues about the musescore.com website, go there instead.

Please don't ignore the message shown when you create issues in this repository:
This issue tracker is used only for tracking development events.
If you want to create bug reports or feature requests, please go to the forums or the issue tracker on https://musescore.org/.
