### ISSUE TITLE
Issues to be solved before we'll release 3.5.1 officially

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#6630]
- [x] Cannot open 3.5.1 on MAC OS 10.13

**Comment by VyachaslavS** [comment]
MuseScore 3.5.1 not replacing 3.5.0 on Mac

**Comment by VyachaslavS** [comment]
- [ ] MuseScore 3.5.1 not replacing 3.5.0 on Windows 10

**Comment by njvdberg** [comment]
- [ ] [3.5.1-versions of Appimages don't seem to be executable](https://musescore.org/en/node/311377)

**Comment by VyachaslavS** [comment]
- [ ] Fix missing library for Linux AppImage

**Comment by njvdberg** [comment]
> * [ ]  Fix missing library GLIBC_2.27 for Linux openSUSE

Is same as previous one.

**Comment by jeetee** [comment]
> * [ ]  MuseScore 3.5.1 not replacing 3.5.0 on Windows 10

To be clear, it does install over 3.5.0, thus replacing it and start menu links are fine too.
The issue is that it still leaves 3.5.0 listed in the applications listing as available for uninstall, next to 3.5.1. So likely a registry thing.

**Comment by Jojo-Schmitz** [comment]
> * [ ]  [3.5.1-versions of Appimages don't seem to be executable](https://musescore.org/en/node/311377)

> * [ ]  Fix missing library GLIBC_2.27 for Linux openSUSE

Try https://github.com/musescore/MuseScore/actions/runs/293033708

**Comment by Jojo-Schmitz** [comment]
> * [ ]  MuseScore 3.5.1 not replacing 3.5.0 on Mac

Might be due to the chnaged application name, "MuseScore 3.5" vs. "MuseScore 3.5.1", which both should be "MuseScore 3"
See https://github.com/musescore/MuseScore/commit/2515c29151962a491f9b44b200d55421f44268f7#r43030098
Too late for MuseScore 3.5.0 (which was named "MuseScore 3.5", see 6890862)

**Comment by vpereverzev** [comment]
> > * [ ]   MuseScore 3.5.1 not replacing 3.5.0 on Mac
> 
> Might be due to the changed application name, "MuseScore 3.5" vs. "MuseScore 3.5.1", which both should be "MuseScore 3"
> See [2515c29#r43030098](https://github.com/musescore/MuseScore/commit/2515c29151962a491f9b44b200d55421f44268f7#r43030098)
> Too late for MuseScore 3.5.0 (which was named "MuseScore 3.5", see [6890862](https://github.com/musescore/MuseScore/commit/6890862c608a3c6fae1a47cb483a3ac7c9e375b0))

Yes, it seems like. I'll revert it at least for 3.5.1

**Comment by njvdberg** [comment]
> > * [ ]   [3.5.1-versions of Appimages don't seem to be executable](https://musescore.org/en/node/311377)
> 
> > * [ ]   Fix missing library GLIBC_2.27 for Linux openSUSE
> 
> Try https://github.com/musescore/MuseScore/actions/runs/293033708

Tested, works.

**Comment by Jojo-Schmitz** [comment]
> > * [ ]   MuseScore 3.5.1 not replacing 3.5.0 on Windows 10
> 
> To be clear, it does install over 3.5.0, thus replacing it and start menu links are fine too.
> The issue is that it still leaves 3.5.0 listed in the applications listing as available for uninstall, next to 3.5.1. So likely a registry thing.

Maybe a UUID thing?

**Comment by vpereverzev** [comment]
> > > * [ ]    MuseScore 3.5.1 not replacing 3.5.0 on Windows 10
> > 
> > 
> > To be clear, it does install over 3.5.0, thus replacing it and start menu links are fine too.
> > The issue is that it still leaves 3.5.0 listed in the applications listing as available for uninstall, next to 3.5.1. So likely a registry thing.
> 
> Maybe a UUID thing?

GUID is the same as usual. I guess the problem is related with LONG_NAME of an app

**Comment by Howard-C** [comment]
- [ ] Prepare the release notes :)

**Comment by Jojo-Schmitz** [comment]
> GUID is the same as usual. I guess the problem is related with LONG_NAME of an app

That long name change is for Mac only as far as I can tel?

**Comment by jeetee** [comment]
> > 
> > Maybe a UUID thing?
> 
> GUID is the same as usual. I guess the problem is related with LONG_NAME of an app

Sorry, sorry, sorry; turns out it is the entry for the RC tripping me up!

**Comment by Jojo-Schmitz** [comment]
* [ ] [311405](https://musescore.org/en/node/311405): Custom workspace reset to Basic

**Comment by Eism** [comment]
> * [ ]  [311405](https://musescore.org/en/node/311405): Workspace reset to Basic - @Eism ? Culprit seems to be your #6535

Ok, I will check

**Comment by VyachaslavS** [comment]
MuseScore 3 for MacOS should work without manually installed libjack

**Comment by worldwideweary** [comment]
Hey Vasily, these aren't absolutely necessary since they don't fix any crashes, but they do fix up some bugs in some activities added in 3.5 that would be nice to get into 3.5.1 instead of waiting for later:

#6554 - Updates Actual Duration of measures to be not absolutely reduced when split 
#6553 - Updates Diatonic Shortcuts (keeping degree alterations) to make sound (when single note) and update screen keyboard accordingly
#6547 - Select Similar Beat's code is now more correct to eliminate lack of function in certain niche cases of actual measure discrepancies.

**Comment by vpereverzev** [comment]
@worldwideweary Yep, I'm aware of it
I'm going to release 3.6 alpha by the end of the October and it will contain your PRs for sure
