### ISSUE TITLE
 Isn't exporting to a .kar file supported? Or do you have any plans to apply?

### ISSUE THREAD

**Issue by kmoon2437** [musescore/MuseScore#6833]
Isn't exporting to a .kar file supported? Or do you have any plans to apply?

**Comment by Howard-C** [comment]
Please don't ignore the message given when creating an issue here:

> This issue tracker is used only for tracking development events.
> If you want to create bug reports or feature requests, please go to the forums or the issue tracker on https://musescore.org/.
