### ISSUE TITLE
Muscscore 3 jianpu qml

### ISSUE THREAD

**Issue by Thethnan** [musescore/MuseScore#7255]

**Comment by Thethnan** [comment]
I would like to get muscscore 3 jianpu QML. Please everyone.

**Comment by MarcSabatella** [comment]
Plugins can be downloaded from musescore.org.  Specifically, the most current Jianpu plugin can be found at https://musescore.org/en/project/jianpu-numbered-notation-0

In the future, to ask questions about MuseScore, please use the Support forum on that same site.

**Comment by Howard-C** [comment]
Please don't ignore the message shown when creating issues here:
> This issue tracker is used only for tracking development events.
> If you want to create bug reports or feature requests, please go to the forums or the issue tracker on https://musescore.org/.
