### ISSUE TITLE
D.S ignoring inner rittornelo

### ISSUE THREAD

**Issue by DouglasDRF** [musescore/MuseScore#7303]
I was trying to transcribe a song and I had to use some ritornello and a D.S, but in the second time from segno it ignores all ritornellos inside this range of bars.

OS: Windows 10 (10.0), Arch.: x86_64, MuseScore version (64-bit): 3.5.2.311459983, revision: github-musescore-musescore-465e7b6

**Comment by MarcSabatella** [comment]
If this is meant as a bug report, please post to the Issue tracker in MuseScore.org with your score and steps to reproduce the problem.  We don't use GitHub for bug reports.

**Comment by DouglasDRF** [comment]
I'm sorry. I found the option to play the repeats of the DS. I thought it should repeat by default.
Thanks.
