### ISSUE TITLE
Staccato position Error && export musicxml

### ISSUE THREAD

**Issue by nuochong** [musescore/MuseScore#7311]
MuseScore (3.6.0.487915347) doesn't export the placement of an articulation (staccato) if you set it explicitly.

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/921#issue-757833071

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/921#issuecomment-765461743

**Comment by Jojo-Schmitz** [comment]
We're not using the GitHub issue tracker for this, please report this in the forums and/or issue tracker on musecore.org

**Comment by nuochong** [comment]
> We're not using the GitHub issue tracker for this, please report this in the forums and/or issue tracker on musecore.org

![image](https://user-images.githubusercontent.com/28994748/105624860-d5fd8d80-5e5f-11eb-8fa2-b9900e5ad2d9.png)

My area is not accessible
https://musescore.org/redirect/post/bug-report?sha=1977cb3&locale=zh_CN&utm_source=desktop&utm_medium=menu&utm_content=1977cb3&utm_campaign=MuseScore3.6.0

**Comment by Jojo-Schmitz** [comment]
Sorry to hear that, but that doesn't change the fact that we don't use GitHub for this.
Does really neither https://musescore.org/en/forum nor https://musescore.org/en/project/issues/musescore work for you?

**Comment by Jojo-Schmitz** [comment]
Anyway, as this is about MusicXML, maybe @lvinken mighht be able to help here

**Comment by lvinken** [comment]
This has simply never been implemented.

**Comment by nuochong** [comment]
Thank you for your understanding. Can we add a complete music XML format export including · staccato · in the subsequent version?
