### ISSUE TITLE
Permission dialog malformed

### ISSUE THREAD

**Issue by habernal** [musescore/MuseScore#7331]
I know you're not using GitHub issue tracker but I don't want to create an extra account on your site for reporting a single bug. So you might want to transfer this issue there, if you like.

First time started MuseScore (Czech locales), the prompt for data collection is malformed, see the screenshot below (includes the app version, too).

![screenshot_2021-01-25_10-05-16](https://user-images.githubusercontent.com/11850778/105818914-c09b7700-5fb7-11eb-983c-d0bb27380829.png)

**Comment by Jojo-Schmitz** [comment]
So you know that this is the wrong place, but use it anyhow???

**Comment by RobFog** [comment]
Rude.

**Comment by habernal** [comment]
It's a feedback from the community, perhaps a bug in the dialog that seems to have a fixed size but should adapt to the content, IMHO. Take it or leave it.

**Comment by Jojo-Schmitz** [comment]
Issues reported here are as good as not being reported.

**Comment by habernal** [comment]
Then go to this Github project's Settings -> scroll down to Features -> unselect Issues and problem solved?

**Comment by Jojo-Schmitz** [comment]
As it says when opening a new issue: we use if for some internal purposes

**Comment by habernal** [comment]
ok, whatever

**Comment by Jojo-Schmitz** [comment]
Thanks for your understanding

**Comment by Jojo-Schmitz** [comment]
There's https://musescore.org/en/node/300775 to cover this (too)
