### ISSUE TITLE
my interface is VERY BIG in 150% screen scale, how to solve it?

### ISSUE THREAD

**Issue by zarhani** [musescore/MuseScore#7440]
Hi I am using 2K screen with 150% screen scaling, and when I launch MuseScore, the interface is very big that buttons nearly take all the space of my screen...How to solve this problem?

**Comment by MarcSabatella** [comment]
Hello!  You will probably need to either set, or unset QT_AUTO_SCREEN_SCALE_FACTOR, or else use the -D command line option to specify the correct resolution in DPI.  If you need further assistance, please ask for help in the Support forum on musescore.org, we do not use GitHub for this.

**Comment by zarhani** [comment]
oops，I am sorry to discuss this in Github :-(   
I added -D command in the shortcut and It solved, thanks

**Comment by Howard-C** [comment]
You can just close this issue.
