### ISSUE TITLE
Big Sur 11.2.1: dark mode when system is in light mode

### ISSUE THREAD

**Issue by tiziodcaio** [musescore/MuseScore#7586]
I don't know why, but my system is in light mode and musescore recognizes it as dark mode.

**Comment by Howard-C** [comment]
Please don't ignore the message shown when creating issues here:
> This issue tracker is used only for tracking development events.
> If you want to create bug reports or feature requests, please go to the forums or the issue tracker on https://musescore.org/.

**Comment by tiziodcaio** [comment]
Oh sorry
