### ISSUE TITLE
Bug report from PVS-Studio

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [musescore/MuseScore#7629]
Hello all.

We have found bugs using [PVS-Studio](https://www.viva64.com/en/pvs-studio/) tool (static code analyzer for C, C++, C#, and Java).

Here is the report: [Short-lived Music or MuseScore Code Analysis](https://www.viva64.com/en/b/0809/).

**Comment by igorkorsukov** [comment]
Thank you for your help!
We will fix these issues.
