### ISSUE TITLE
[MU4 Issue] Extra space in "sff" and 2/2 hides if shrink MU4 window to minimum

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7636]
**Describe the bug**
Extra space in "sff" and 2/2 hides if shrink MU4 window to minimum

**To Reproduce**
1. Create a score
2. Look at palettes section on the instruments panel

**Expected behavior**
2/2 dhould be always visible and "sff" shoul look without spaces 

**Screenshots**
![index](https://user-images.githubusercontent.com/71372310/110157470-430a2880-7df9-11eb-89d1-3ce3f26ebc1e.png)
![2021-03-02 05_21_52-Window](https://user-images.githubusercontent.com/71372310/110157474-43a2bf00-7df9-11eb-90a3-b3251948de69.jpg)

**Desktop (please complete the following information):**
MacOS
Windows 10 x64

**Comment by abarichello** [comment]
Couldn't reproduce this one on Linux 🤔 
![image](https://user-images.githubusercontent.com/16687318/116335313-0cbfa880-a7ad-11eb-853e-5c540b7df132.png)
Everything looks ok on minimum window size

**Comment by vshalkevich** [comment]
Seems fine for Linux
Need to confirm fix on Windows and MacOS
