### ISSUE TITLE
[MU4 Issue] Can`t select multiple instruments by holding Ctrl/Cmd or Shift keys 

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7639]
**Describe the bug**
User can select only one instrument at a time(Bug reproduced also on Score > instrument panel)

**To Reproduce**
1. Start create New Score
2. Choose "Family"
3. Select "Instrument"

**Expected behavior**
User can select multiple instruments by holding Ctrl/Cmd or Shift keys 

**Screenshots**
![4 - Expected result (it is possible to select and add multiple instruments at a time)](https://user-images.githubusercontent.com/71372310/110192265-f39a1b80-7e3d-11eb-99e9-0e5adf4f3b90.png)

![4 - Actual result (cant add multiple instruments at a time)](https://user-images.githubusercontent.com/71372310/110192266-f4cb4880-7e3d-11eb-9edc-d60b24f1bd79.png)

**Desktop (please complete the following information):**
MacOS
Windows 10 x64

**Additional context**

**Comment by wizofaus** [comment]
https://stackoverflow.com/questions/3879591/qml-listview-multiselection might be relevant?
It would appear using the QML ListView here is going to make this tricky.  I don't know Qt/QML at all plus I can't even build in QtCreator so might leave to someone with more expertise in this area.

**Comment by cbjeukendrup** [comment]
@wizofaus Thanks, but we already have a system for multi-selection, see the ItemMultiSelectionModel class. It is just not implemented for the Instruments list. The parts dialog could serve as an example here.

**Comment by RomanPudashkin** [comment]
I'm working on this
