### ISSUE TITLE
[MU4 Issue] zoom in and out on trackpad doesn`t work

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7640]
**Describe the bug**
Zoom in and zoom out doesn`t work with trackpad (screenshot attached)(Bug also reproduces on Score page)

**To Reproduce**
1. Start creating a new score
2. Select "Choose from template"
3. Try to zoom in or zoom out preview page with trackpad

**Expected behavior**
Zoom in and zoom out should work with trackpad

**Screenshots**
![5 - Actual result (The page with a bug)](https://user-images.githubusercontent.com/71372310/110192322-58557600-7e3e-11eb-96ff-5c67aa71634f.png)

**Desktop (please complete the following information):**
Windows 10 (works now)
MacOS (**DOESN'T WORK NOW**)

**Additional context**

**Comment by vshalkevich** [comment]
Issue reproduced again

**Comment by cbjeukendrup** [comment]
I'm working on the fix for macOS. On Windows, it should already work.

**Comment by DmitryArefiev** [comment]
Confirm. Still doesn't work on Mac. 
(I've edited the description)
