### ISSUE TITLE
[MU4 Issue] Addons text description seems cutted if app window resolution is 1020x780 or lower

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7642]
**Describe the bug**
Addons text description seems cutted

**To Reproduce**
1. Go to Home Tab Addons
2. Click on Extensions tab
3. Make application window resolution 1020x780 or lower

**Expected behavior**
Addons text description should be aligned

**Screenshots**

![2020-10-26_23-31-51](https://user-images.githubusercontent.com/71372310/110193045-cef47280-7e42-11eb-8c15-0a44e6fcd1f4.jpg)

**Desktop (please complete the following information):**
Windows 10 x64
MuseScore 4.0.0. 323776504 x86_64

**Additional context**

**Comment by wizofaus** [comment]
Doesn't appear to be sufficient info to reproduce as for me by default there are no extensions installed, so nothing shows up at all when I select "extensions" on this screen. Also is it the windows size or the actual screen resolution that matters?  I can't imagine too many people trying to use MuseScore at a screen resolution less than 1024x768!

**Comment by HemantAntony** [comment]
This appears to be fixed:

https://user-images.githubusercontent.com/88136054/144166527-4b757086-4d84-4ac9-a866-508ac2d3b9e0.mp4
