### ISSUE TITLE
[MU4 Issue] New score replaces existing score without saving

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7643]
**Describe the bug**
New score opened and previous closed without saving

**To Reproduce**
1. Create a score
2. Click "File"
3. Click "New"

**Expected behavior**
New tab should be opened near existing score like in MU3 when you create a new score

**Desktop (please complete the following information):**
Windows 10
MacOS

**Comment by wizofaus** [comment]
This also happens when opening a previously saved score. It doesn't seem the existing score gets closed/destroyed in memory, it's just not visible any more.
