### ISSUE TITLE
[MU4 Issue] Wrong data of file created in MU4

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7644]
**Describe the bug**
I created score yesterday (1 day ago)But in MU4 it said that score has been created 2 days ago

**To Reproduce**
1. Ceate a score and save it
2. The next day create a new score and save it
3. Look at the date of scores created on Home Tab

**Expected behavior**
Score`s date of creation should be displayed correctly

**Screenshots**

![a6LNyWpIFTY](https://user-images.githubusercontent.com/71372310/110193213-dbc59600-7e43-11eb-9477-ea2225bdc8e9.jpg)
![8u235mXZhM8](https://user-images.githubusercontent.com/71372310/110193214-dc5e2c80-7e43-11eb-8139-d50a0b272808.jpg)

**Desktop (please complete the following information):**
Windows 10

**Additional context**
You may see on Windows folder screenshot that there are 2 scores created in different days ("1" and "file") but both of them have the same date in MU4 (2 days ago)

**Comment by njvdberg** [comment]
Date as reported on the <code>Scores</code> page is the `creationDate` as is stored in the score properties, **not** the file creation date. This date isn't updated when the score is saved.

**Comment by vshalkevich** [comment]
@shoogle Need to discuss if this is intended behaviour or we should change it. It might be a minor thing and we may keep this as is

**Comment by shoogle** [comment]
@Tantacrul, in the Home Tab, should "2 days ago" under a score refer to the date the score was created, the date it was last opened, or the date it was last saved?

**Comment by Tantacrul** [comment]
I would say last saved. That was the intention. I agree this is a bug

**Comment by wizofaus** [comment]
The code is
`obj[SCORE_TIME_SINCE_CREATION_KEY] = DataFormatter::formatTimeSinceCreation(meta.creationDate)`
so it's pretty explicitly intended to show that.
I don't really see any reason formatTimeSinceCreation( ) should be called that, vs just formatTimeSince( ), and we can change it to use the O/S's file modification date `QFileInfo(meta.filePath.toQString()).lastModified().date()`.  
But it might be useful to see the creation date too?
