### ISSUE TITLE
[MU4 Issue] There should be a stroke (1px) divider line between the Menu bar and the Note Input bar

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7646]
**Describe the bug**
There should be a stroke (1px) divider line between the Top Bar and the Note Input bar. There should also be a divider line between the Note Input bar and the content underneath (Inspector in the screenshot).

**To Reproduce**
1. Create a score
2. Try to find the divider line between Menu bar and the Note Input bar 

**Expected behavior**
There should be a stroke (1px) divider line between the Top Bar and the Note Input bar. There should also be a divider line between the Note Input bar and the content underneath.

**Screenshots**
![image](https://user-images.githubusercontent.com/11011881/114558239-60d17580-9c62-11eb-9567-38693d0035b5.png)

**Desktop (please complete the following information):**
Windows 10 x64

**Additional context**
NOTE: Make sure that there are not two 1px dividers on top of each other (between the Inspector and the Note Input bar).

**Comment by Alexdotdot** [comment]
just compiled MU4 (master) today. There are, in fact, dividers in the places you suggested. Not much I can do to close this, but I hope this comment boosts the issue so that somebody in charge sees it.

**Comment by Alexdotdot** [comment]
somebody fixed the issue, but this has not been closed. I'm going to tag the author. @vshalkevich
