### ISSUE TITLE
[MU4 Issue] Customising the note input bar often produces wrong results

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7648]
**Describe the bug**
open Customise toolbar > it shows the wrong items and changing item position take no effect on note input bar

**To Reproduce**
1. Create a score
2. open Customise toolbar > it should show the same items as in note input bar and changing item position should take effect on note input bar

**Expected behavior**
Customise toolbar should show the same instruments and in the same order as they are appear in Note input bar

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10

**Comment by wizofaus** [comment]
Can't reproduce? However the Customize toolbar popup has a strange title bar with the text "MuseScore4Development" in it.
