### ISSUE TITLE
[MU4 Issue] Change instrument name > name didnt save on the left panel name

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7652]
**Describe the bug**
Change instrument name - name didnt save on the left panel name Video attached

**To Reproduce**
1. Create a new score
2. Click on option button near the instrument from the left instrument panel
3. Change text in the field "Name on main score"
4. Close settings pop-up (by clicking outside the pop-up)
5. Click on option button near the instrument from the left instrument panel again

**Expected behavior**
Instrument name should be saved in the left instrument panel as in the main score

**Screenshots**

https://user-images.githubusercontent.com/71372310/110194143-f568dc80-7e47-11eb-8eb1-23eb131816d2.mov

**Desktop (please complete the following information):**
Windows 10
MacOS

**Comment by njvdberg** [comment]
Not reproduceble with latest build form [master](https://github.com/musescore/MuseScore/commit/18f857881018c72e9396d264a216352c5c281ece).

**Comment by vshalkevich** [comment]
Can`t reproduce on the latest build. Fixed
