### ISSUE TITLE
[MU4 Issue] Undo deleting instruments doesnt return instruments on left side panel

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7653]
**Describe the bug**
Instruments returns but left side instruments panel still empty

**To Reproduce**

1. Create a score with instruments
2. delete one by one instruments from the left side panel
3. Undo deleting (CTRL + Z)

**Expected behavior**
Undo deleting instruments also should return instruments on the left side panel

**Desktop (please complete the following information):**
MacOS

**Additional context**

**Comment by wizofaus** [comment]
Delete button on an instrument does nothing at all for me actually (it goes disabled but I don't see anything else refresh).
I can delete individual staves though and reproduce the reported bug. Similar bug exists with using arrows to reorder, and in fact it's not hard to get it to crash after using undo/redo.

**Comment by wizofaus** [comment]
I can fix the exact problem described just by adding
`            notation->undoStack()->stackChanged().onNotify(this, [this]() { load(); });` at line 54 of instrumentspaneltreemodel.cpp but there too many other issues with this panel, particularly with not remembering which nodes are expanded/collapsed when there's any change, and I don't think I can realistically fix without better knowledge of how Qt works and proper tools for working with qml etc.

**Comment by njvdberg** [comment]
@wizofaus This issue is already solved with PR #8147

**Comment by wizofaus** [comment]
Confirmed that this appears fixed now @vshalkevich - I'd say this can be closed?
