### ISSUE TITLE
[MU4 Issue] If multiple instruments selected and click to hide them, only one item hidden

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7654]
**Describe the bug**
Only clicked instrument hidden

**To Reproduce**
1. Create a score with multiple instruments
2. Select several instruments from the left side panel
3. Click on an eye near instrument to hide it

**Expected behavior**
All selected instruments should be hidden when we click on an eye near any of selected instruments

**Desktop (please complete the following information):**
MacOS

**Comment by Tantacrul** [comment]
Fixed

**Comment by HemantAntony** [comment]
@Tantacrul this issue still occurs

**Comment by Tantacrul** [comment]
It's not an issue.

**Comment by Tantacrul** [comment]
OK, reopening, since @HemantAntony has a PR for the request ready to be reviewed.

**Comment by RomanPudashkin** [comment]
@Tantacrul could you please check it? I can merge it right now

**Comment by HemantAntony** [comment]
@RomanPudashkin There are two. This is mine: #10203

**Comment by Tantacrul** [comment]
@RomanPudashkin Will do now.

@HemantAntony - actually, you can send any PR's you want tested, which you small to either me, @bkunda or @DmitryArefiev if the engineers are busy. Do recommend this to others also!

**Comment by RomanPudashkin** [comment]
> @RomanPudashkin There are two. This is mine: #10203

@Tantacrul 
Oops, sorry, I meant this PR:
https://github.com/musescore/MuseScore/pull/10656

**Comment by Tantacrul** [comment]
@HemantAntony - the artefact has expired :(

<img width="710" alt="image" src="https://user-images.githubusercontent.com/21022311/166104627-9a053b81-ac1b-4a0c-9024-13915a037140.png">

**Comment by HemantAntony** [comment]
I'll rebase and it should be there soon

**Comment by Tantacrul** [comment]
Tested. Looking good to me.
