### ISSUE TITLE
[MU4 Issue] Palettes and Inruments have more gap than Inspector on Score page

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7655]
**Describe the bug**
Palettes and Inruments have more gap than Inspector on Score page

**To Reproduce**
1. Create a score
2. Click on Palettes tab from the Instruments panel
3. Click on Inspector tab from the Instruments panel
4. Compare the gap on this tabs

**Expected behavior**
The gap between Inspector and score should be the same as Palettes and Instruments have (screenshot added)

**Screenshots**

![Скриншот 26-12-2020 02 19 02](https://user-images.githubusercontent.com/71372310/110194495-89877380-7e49-11eb-92ca-653e4f7ea915.png)

**Desktop (please complete the following information):**
Windows 10
MacOS

**Comment by cbjeukendrup** [comment]
Seems fixed by #8030 (commit 81f4e5d14bdfaef1b4f0a29f63e89e1188c17da4).
