### ISSUE TITLE
[MU4 Issue] Inspector panel doesnt reflects on changes from View panel

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7656]
**Describe the bug**
"Page Margins" checkbox without tick

**To Reproduce**
1. Create a score
2. Click View
3. Tick "Show page margins"
4. Open Inspector tab from instuments panel
5. See "Page Margins" checkbox

**Expected behavior**
"Page Margins" checkbox without tick

**Screenshots**
![image](https://user-images.githubusercontent.com/71372310/110194558-d66b4a00-7e49-11eb-8c16-7b0d66c1710d.png)
![image (1)](https://user-images.githubusercontent.com/71372310/110194559-d703e080-7e49-11eb-90de-093c8f027e5e.png)

**Desktop (please complete the following information):**
Windows

**Additional context**

**Comment by Howard-C** [comment]
Dibs!

**Comment by Howard-C** [comment]
Dibs!

**Comment by Howard-C** [comment]
> Dibs!

Well, turns out the show invisible/unprintable/... are not `Sid`s, it should be a whole new system other than `NotationStyle`. I'll leave the in-house developers to that :)

**Comment by vshalkevich** [comment]
Page Margins from upper menu connected with Page Margin tick from the Inspector (Properties tab for now). That seems good 
Need to double-check Page Margin function.
