### ISSUE TITLE
[MU4 Issue] Can`t save score on Mac

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7659]
**Describe the bug**
Can`t save score on Mac

**To Reproduce**
1. Click File
2. Click Save or other option connected with score saving

**Expected behavior**
Score should be seved in default derectory or popup should appears with save directory selection

**Screenshots**

**Desktop (please complete the following information):**
MacOS

**Comment by mattmcclinch** [comment]
I believe the real issue here is best described in #7766, which has been fixed with #7782.
