### ISSUE TITLE
[MU4 Issue] Score save dialog doesn`t appear

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7660]
**Describe the bug**
Score closes without autosave

**To Reproduce**
Steps

1. Create a score 
2. Click on exit button OR click File > Quit 

Steps 2:

1. Open created score
2. Make schanges in a score
3. Click on exit button OR click File > Quit 

**Expected behavior**
Pop-up should appear suggesting to save changes in our score or to save our score if it is not yet saved. 

**Desktop (please complete the following information):**
Windows 10

**Comment by wizofaus** [comment]
Looks like this requires changing `NotationSwitchListModel::closeNotation(int index)`? But if it's already assigned I'll leave it...Not sure if it makes sense to fix the File|Close command at the same time (currently does nothing).
I also note that currently when you open a second score you can no longer see the first one though it appears to still be internally "open" (held in memory etc).

**Comment by wizofaus** [comment]
NB I have put up a PR that implements File|Close, but it doesn't trigger NotationSwitchListModel::closeNotation so I'm not sure what the central place for processing such close events should be.

**Comment by RomanPudashkin** [comment]
I'm working on it
