### ISSUE TITLE
[MU4 Issue] Part window remembers it`s position after reopening.

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7664]
**Describe the bug**
Part window should not remember position when reopened. It should always be centered
MU saves position and opens in the place where it was last closed

**To Reproduce**
1. open part window
2. change part window position
3. Close part window
4. shrink MU4 window
5. open again part window

**Expected behavior**
MU saves position and opens in the place where it was last closed 

**Desktop (please complete the following information):**
 Windows 10

**Comment by wizofaus** [comment]
As far as I can tell this is the same issue as https://github.com/musescore/MuseScore/issues/7879

**Comment by HemantAntony** [comment]
This appears to be fixed:

https://user-images.githubusercontent.com/88136054/144167130-dc06837e-38db-48e4-8462-f614e4058c2c.mp4

**Comment by DmitryArefiev** [comment]
Tested on latest master build (Win10, Mac12) - NO LONGER OCCURS

Closing
