### ISSUE TITLE
[MU4 Issue] Cancel and open buttons should always be visible

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7665]
**Describe the bug**
If user opens Parts window => Cancel and open buttons should always be visible. Popups should not be able to appear above them. There should be a barrier above the 'Cancel' / 'Open' segment that prevents popups from overlapping the bottom are:

**To Reproduce**
1. opens Parts window
2. see Cancel and open buttons 

**Expected behavior**
Desired behavior when there is no room below: (screenshot attached)

**Screenshots**

![1](https://user-images.githubusercontent.com/71372310/110195096-17b12900-7e4d-11eb-9949-893eee233214.png)
![2](https://user-images.githubusercontent.com/71372310/110195097-1849bf80-7e4d-11eb-86ff-fe867d022ed5.png)

**Desktop (please complete the following information):**
MacOS

**Comment by RomanPudashkin** [comment]
This popup will be removed in https://github.com/musescore/MuseScore/pull/8751
