### ISSUE TITLE
[MU4 Issue] Press Enter or click otside the renaming part does not apply name at Parts dialog

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7666]
**Describe the bug**
Press Enter or click otside the renaming part does not apply name at Parts dialog

**To Reproduce**
1. Create a score
2. Open Parts dialog
3. Add part
4. Enter part name
4. Press "Enter" button from the keyboard OR click outside the renaming part

**Expected behavior**
Entered text in name field should be applied and exit from editing mode

**Screenshots**

![Скриншот 26-12-2020 01 46 42](https://user-images.githubusercontent.com/71372310/110195365-b2aa0300-7e4d-11eb-8f0e-529c9d8a5400.png)

**Desktop (please complete the following information):**
Windows 10

**Comment by wizofaus** [comment]
Had a look at this, but even trying to modify the TextInputField qml to emit a signal when hitting enter that the PartDelegate could handle didn't work, and I couldn't really see how to detect a click in the rest of the dialog at all. There appear to be no other qml dialogs that work like this (where a text-edit field is only shown while editing, and should auto-disappear on clicking away or hitting enter).

**Comment by wizofaus** [comment]
This appears to be fixed now @vshalkevich (there are other issues with this dialog though)
