### ISSUE TITLE
[MU4 Issue] In Score, if selected two rows, delete button erases only one row

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7667]
**Describe the bug**
Notes in Upper row deleted (Screenshot added)

**To Reproduce**
1. Input notes in two rows (one row upper)
2. Select notes in that two rows
3. Press delete button (or right mouse button click on one row and click delete option)

**Expected behavior**
Notes in both selected rows deleted

**Screenshots**
![2020-12-03_23-32-11](https://user-images.githubusercontent.com/71372310/110195772-c1de8000-7e50-11eb-9176-e58a05a32e42.jpg)
https://user-images.githubusercontent.com/71372310/110195782-c9058e00-7e50-11eb-9ec6-54116a69286f.mov

**Desktop (please complete the following information):**
MacOS

**Comment by wizofaus** [comment]
I'm not sure I understand, I watched the video and the behaviour looks correct - it deletes all notes from both the selected staves?
However on one score where I tried it, I couldn't even get the context menu with "Delete" to appear without the selection changing. It works fine when using "Delete" from the Edit menu (but not the Del or backspace key annoyingly - unless you first reveal one of the top-level menus, then backspace works, but not Del).
Undo doesn't work afterwards though.
