### ISSUE TITLE
[MU4 Issue] Empty bottom bar in fullscreen mode on Linux

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7671]
**Describe the bug**
Empty bottom panel in full screen mode appears

**To Reproduce**
1. Open MU4 in a full screen mode

**Expected behavior**
No unnecessary bottom panel

**Screenshots**

![image](https://user-images.githubusercontent.com/71372310/110196065-1125b000-7e53-11eb-9118-2e30a9dc20c4.png)

**Desktop (please complete the following information):**
OS - Linux mint 
OS - Linux ubunty

**Additional context**
(Can`t reproduce on MacOS and Windows 10)

**Comment by cbjeukendrup** [comment]
Seems fixed now (tested on Ubuntu)
