### ISSUE TITLE
[MU4 Issue] Articulations overlaping if note scale less then 100%

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7673]
**Describe the bug**
Articulations overlaping on each other

**To Reproduce**
1.     Open score with notes
2.     Select note
3.     Right click on note and select Staff Properties
4.     Change note Scale from 100% to 80% for example (screenshot attached)
5.     Add articulations to 80% scale note

**Expected behavior**
Articulations should not overlap on each other

**Screenshots**

![Скриншот 28-01-2021 18 46 10](https://user-images.githubusercontent.com/71372310/110196190-ee47cb80-7e53-11eb-9e11-1c5de418b532.png)
![Скриншот 28-01-2021 18 48 07](https://user-images.githubusercontent.com/71372310/110196191-eee06200-7e53-11eb-9db0-4ed65af5efdf.png)

**Desktop (please complete the following information):**
MacOS

**Additional context**
Reproduce rate - 1 of 2 times

**Comment by wizofaus** [comment]
Can't reproduce, can you attach a score?
