### ISSUE TITLE
[MU4 Issue] Playback cursor doesn't work on rests

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7674]
**Describe the bug**
You can not see dynamically blue play bar on empty spaces. It moves dynamically only on notes

**To Reproduce**
1. Create an empty score
2. Add notes in the middle of the score
3. Start playing score from the beggining

**Expected behavior**
You should see that blue playing bar moving throw the score dynamically

**Desktop (please complete the following information):**
Windows 10

**Comment by wizofaus** [comment]
Playback seems totally broken in MU4 for me, even without rests the cursor doesn't move and I don't hear anything played. I can see the current time position increment though.
I'm assuming this a fairly big piece of work that needs to be somehow re-implemented, so I don't think it makes sense for me to attempt it at this point, though I'd certainly like to understand how it works.

**Comment by wizofaus** [comment]
Seems "totally broken" is an exaggeration, but it does seem that the playback information doesn't get properly updated after making modifications to the score, which causes a lot of issues.  I can reproduce the specific issue described here though, that the playback cursor stops moving at a rest longer than a 1/4 note until it reaches the next note.

**Comment by wizofaus** [comment]
BTW if you change the setting application/playback/cursorType in DevTools to 0, the cursor does correctly keep moving through rests, it appears to be related to the STEP mode logic, midiTickPlayed events aren't sent by the sequencer when there's nothing to play. Still investigating, not sure how best to fix, would seem to require binding to positionChanged if there's been no midiTickPlayed event within the time of the current beat unit duration.  Will need to figure out how it's done in MU3 I guess.

**Comment by vshalkevich** [comment]
Cant reproduce this issue
