### ISSUE TITLE
[MU4 Issue] Format > Style - missed section

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7677]
**Describe the bug**
Format > Style - missed section "Create multimeasure rests"

**To Reproduce**
1. Create a score
2. Click "Format"
3. Click "Style"
4. Observe opened menu

**Expected behavior**
Create multimeasure rests should be present

**Desktop (please complete the following information):**
Windows 10 x64

**Comment by mattmcclinch** [comment]
See #6211. Multimeasure rest options have been moved to a new "Rests" page in the style window.

**Comment by shoogle** [comment]
@vshalkevich, looks like this is intentional. Did you notice this yourself or was it pointed out to you by somebody else? If it was pointed out, please tag that person so they can comment if they still think it's an issue.
