### ISSUE TITLE
[MU4 Issue] Play Panel icon "Toggle loop playback" size is 34x34

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7679]
**Describe the bug**
Play Panel icon "Toggle loop playback" size is 34x34

**To Reproduce**
1. Create a score
2. Observe "Toggle loop playback" size on Play Panel

**Expected behavior**
Play Panel icon "Toggle loop playback" size should be 32x32

**Screenshots**

![image (2)](https://user-images.githubusercontent.com/71372310/110196548-44b60980-7e56-11eb-95e8-bb5d23bc0204.png)

**Desktop (please complete the following information):**
MacOS

**Comment by wizofaus** [comment]
Not sure I understand why this specific toolbar icon is being picked out - they're all 35 pixels high, and the "playback settings" button is actually 1px wider than this one. Is the intention that every single toolbar icon should always be exactly 32 x 32 pixels (regardless of screen resolution etc.)?  What about the space between them? Where is this "Figma" I can refer to?

**Comment by wizofaus** [comment]
I've spent 2 hours now fudging around with the widths & heights & spacings etc. in FlatButton.qml and while I can force the bounding rect down to 32x32 I'm not sure what other issues it will cause.
Basically I modified lines 58/59 to be
```
    height: contentWrapper.height + 11
    width: (Boolean(text) ? Math.max(contentWrapper.width + 32, prv.isVertical ? 132 : 0) : contentWrapper.width + 12)
```

**Comment by cbjeukendrup** [comment]
Not actual anymore
