### ISSUE TITLE
[MU4 Issue] Loop playback doesn`t work if right loop marker set in the end of the score

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7680]
**Describe the bug**
Loop playback doesn`t work if loop marker right set in the end of the score 
Loop playback plays only once loopped part

**To Reproduce**
1. Set right loop marker in the end of the score
2. Click on Loop playback
3. Click on Play 

**Expected behavior**
Loop playback should repeat loopped part

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wizofaus** [comment]
Playback almost totally broken for me in MU4 (windows 10), so can't reproduce.

**Comment by wizofaus** [comment]
This seems OK now? @vshalkevich 
Though there's still a separate bug with not being able to click on the last measure to include in a range which makes it slightly hard to test.
