### ISSUE TITLE
[MU4 Issue] Input cursor doesnt drops if user click on Play Panel options

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7681]
**Describe the bug**
Input cursor still shown on Time Indicator (video attached)

**To Reproduce**

1. Create a score
2. Click on time bar indicator on Play Panel
3. Click on any other option on Play Panel 

**Expected behavior**
Input cursor should be hidden after clicking outside the Time Indicator

**Screenshots**

https://user-images.githubusercontent.com/71372310/110196644-ed646900-7e56-11eb-8c58-ab147e2c9a6e.mp4

**Desktop (please complete the following information):**
MacOS
Windows 10

**Comment by RomanPudashkin** [comment]
I'm working on it
