### ISSUE TITLE
[MU4 Issue] If start to play the first score, pause it, open another score, previous score would play 

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7682]
**Describe the bug**
If start to play the first score, pause it, open another score, previous score would play 

**To Reproduce**

1. Open the first score
2. Click on play button from the Play Panel
3. Click pause button from the Play Panel
4. Open the second score
5. Click on play button from the Play Panel

**Expected behavior**
The second (the latest opened) score should be played

**Screenshots**

**Desktop (please complete the following information):**
Linux
(might be Windows and MacOS)

**Additional context**

**Comment by wizofaus** [comment]
Couldn't reproduce but have quite a few playback issues, it only works at all on a few scores and not even completely (e.g. only some parts play), and selecting measures etc. doesn't change the current playback position.

**Comment by wizofaus** [comment]
Based on comments in https://github.com/musescore/MuseScore/pull/8359 this is probably best handled by @vpereverzev
