### ISSUE TITLE
[MU4 Issue] Palettes Tempo enlarges if used Custom workspace

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7685]
**Describe the bug**
Palettes Tempo enlarges if used Custom workspace

**To Reproduce**
1. Create a score
2. Click on 'workspace' on the bottom tab panel
3. Click on "Create new workspace"
4. Click "Select" (to create workspace)
5. Click "Select" (to apply created workspace)
6. Click "Palette" from the left side instrument Panel
7. Click "Tempo" to expand Tempo dropdown

**Expected behavior**
Tempo should be default size (as in default workspace)

**Screenshots**

![2021-03-06 09_46_52-MuseScore 4](https://user-images.githubusercontent.com/71372310/110198084-ecd0d000-7e60-11eb-8217-4c27809231cc.jpg)

**Desktop (please complete the following information):**
Windows 10
Linux Mint

**Comment by wizofaus** [comment]
Couldn't reproduce (Windows)
