### ISSUE TITLE
[MU4 Issue] Cant create new score

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7688]
**Describe the bug**
File > New and shortcut Cmd+N not always working (works via Home screen)
Switching between Home tab and Score tab might fix it temporarily
Switching desktop on macOS or minimizing application might affect this too

**To Reproduce**
1. Click "File" from the upper menu bar
2. Click "New"

**Expected behavior**
Score created via File > New and shortcut Cmd+N 

**Desktop (please complete the following information):**
MacOS

**Additional context**

**Comment by mattmcclinch** [comment]
I believe the real issue here is best described in #7766, which has been fixed with #7782.
