### ISSUE TITLE
[MU4 Issue] Missing score ordering dropdown from MS 3.6

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7689]
**Describe the bug**
Missing score ordering dropdown from MS 3.6
Template categories not in MS3 order, same with individual templates

**To Reproduce**
1. Open New Score Wizard
2. There should be Ordering dropdown like in MuseScore 3.6

**Expected behavior**
ordering dropdown from MS 3.6 present

**Desktop (please complete the following information):**
MacOS
Windows 10

**Comment by njvdberg** [comment]
Known issue, I'm working on this.

**Comment by RomanPudashkin** [comment]
https://github.com/musescore/MuseScore/pull/8267
