### ISSUE TITLE
[MU4 Issue] Search field blocked if user switches between app windows

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7690]
**Describe the bug**
Search field blocked if user switches between app windows

**To Reproduce**
1. Open New Score Wizard
2. switches between app windows
3. Click on New Score Wizard Search field

**Expected behavior**
User can type text in New Score Wizard Search field

**Desktop (please complete the following information):**
MacOS

**Comment by wizofaus** [comment]
Is this MacOS only? Can't reproduce on Win10.

**Comment by cbjeukendrup** [comment]
I can't even reproduce on macOS any more... 
But it's strange, I don't remember anything specific that might have fixed this. It could be a side effect of the new docking system or the new PopupView/DialogView, or it could have to do with changes to how key presses and shortcuts are handled...
