### ISSUE TITLE
[MU4 Issue] File > Open doesn’t work until a score has been loaded (i.e. you must create one first)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7692]
**Describe the bug**
File > Open doesn’t work until a score has been loaded (i.e. you must create one first)

**To Reproduce**
1. Open MuseScore
2. Click on 'File'
3. Click 'Open'

**Expected behavior**
User can open file from the upper menu bar immediately after launching App

**Desktop (please complete the following information):**
MacOS

**Comment by mattmcclinch** [comment]
I believe the real issue here is best described in #7766, which has been fixed with #7782.
