### ISSUE TITLE
[MU4 Issue] Able to click and hold on number spinners but value changes too slowly

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7693]
**Describe the bug**
Able to click and hold on number spinners but value changes too slowly
Speed could accelerate the longer you hold (5 seconds to do entire range)
If no acceleration then it should take longer

**To Reproduce**
1. Start New Score Wizard
2. Click "Next"
3. Click "tempo"
4. Tick checkbox "show tempo marking on my score"
5. click and hold on tempo number spinner

**Expected behavior**

**Desktop (please complete the following information):**
MacOS
Windows

**Comment by Mystic-Slice** [comment]
I am working on it
