### ISSUE TITLE
[MU4 Issue] Time signature is not displayed correctly

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7694]
**Describe the bug**
Time signatures displayed as 2/2 and 4/4 instead of their Signs

**To Reproduce**
1. Start New Score Wizard
2. Select instrument and click "next"
3. Click on "Time Signature" option
4. Click on "C" sign 
5. Click on "_C_ (crossed)" sign

**Expected behavior**
"C" sign  should be displayed on the main preview instead of 4/4
"_C_ (crossed)" sign should be displayed on the main preview   instead of 2/2

**Desktop (please complete the following information):**
MacOS
Windows

**Comment by Howard-C** [comment]
See #7867.
