### ISSUE TITLE
[MU4 Issue] Add slur (shortcut: S), should leave you in edit mode on right-most endpoint

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7697]
**Describe the bug**
Slurs are not working correctly.

**To Reproduce**
- add two adjacent notes
- select the first
- click "S" / add slur command
- slur added, but not in edit mode as it is per MU3
- IMPORTANT - the shortcut to extend the slur (Shift+Alt+ Right arrow) is not working

**Desktop (please complete the following information):**
All

**Comment by wizofaus** [comment]
Specifically the repro steps are:
1. add two adjacent notes
2. select the first
3. click "S" / add slur command
4. slur added, but not in edit mode as it is per MU3

Note that in MU3 the slur isn't in edit mode if you select multiple notes before adding the slur, not quite sure why the difference. Can you confirm we want to preserve/restore MU3 behaviour here @Tantacrul ?

**Comment by Eism** [comment]
@wizofaus 
see https://github.com/musescore/MuseScore/issues/7985#issuecomment-833671601
'EXACTLY like it does in MS3'

I am working on it now

**Comment by wizofaus** [comment]
Are you still working on this @Eism as I've made a lot of changes around edit mode for slurs and in fact I'm still working on it (specifically, detecting when the start/end handles are near noteheads etc., and that anchor lines are drawn correctly). But I haven't done anything with the specific list listed here.

**Comment by wizofaus** [comment]
See my comments in https://github.com/musescore/MuseScore/issues/7985, I didn't actually realise it was possible for an element to be in edit mode without being selected until I looked into this, which is going to be tricky to support. But I have already done the bulk of what's necessary here.

**Comment by Tantacrul** [comment]
Changed to P1 because this is one of the most important notated elements and the inability to extend it using a shortcut is a serious problem.
