### ISSUE TITLE
[MU4 Issue] Zoom out Score to 25% and click to Zoom In hides score from the view

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7717]
Zoom out Score to 25% and click to Zoom In hiides score from the view

**To Reproduce**
1. Create a score
2. Click zoom out button until 25% view
3. Click Zoom in button

**Expected behavior**
Zoom view should be 50% and score should be in the field of view

**Desktop (please complete the following information):**
Linux

**Additional context**
Could not reproduce on Windows 10

**Comment by RomanPudashkin** [comment]
Can't reproduce on the current master
