### ISSUE TITLE
[MU4 Issue] Creating Custom workspace gives Home Page extra tabs

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7718]
**Describe the bug**
If user create custom workspace, restarts app, it can see exta tabs on Home Page 

**To Reproduce**
1. Create a score
2. Create a new workspace
3. Select Custom new created workspace
4. Quit the App
5. Start MU4

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/71372310/110746104-59771080-824d-11eb-9c68-26523c7c4ca3.mp4

**Desktop (please complete the following information):**
Linux Mint

**Additional context**
Could not reproduce on Windows 10

**Comment by Eism** [comment]
An alternative way to reproduce - start the application without settings(first start)

**Comment by cbjeukendrup** [comment]
Seems fixed with new docking system.
