### ISSUE TITLE
[MU4 Issue] Unnecessary Pop-up appears on the score page

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7725]
**Describe the bug**
Unnecessary Pop-up appears on the score page

**To Reproduce**
1. Start MU4
2. Open recent Score OR Create a new score

**Expected behavior**
No pop-ups should appear on the score page

**Screenshots**
![2021-03-12 18_30_17-Window](https://user-images.githubusercontent.com/71372310/110963612-5706da80-8363-11eb-81c4-963d3e98b9d2.jpg)

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Bug noted in this build 
https://github.com/musescore/MuseScore/actions/runs/646331729

**Comment by mattmcclinch** [comment]
This has been fixed now, right?

**Comment by vshalkevich** [comment]
Yes. It is fixed now. I will close the issue. Thanks
