### ISSUE TITLE
[MU4 Issue] Trackpad scrolling doesnt work on Home > Addons > Plugins page 

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7726]
**Describe the bug**
Trackpad scrolling doesnt work on Home > Addons > Plugins page 
Add-ons > Extensions has the same problem.

**To Reproduce**
1. Click on Home
2. Click on Addons
3. Click Plugins
4. Use trackpad to scroll up or scroll down Plugins page

**Expected behavior**
Trackpad scrolls Plugins page up and down

**Screenshots**
![image](https://user-images.githubusercontent.com/71372310/110964372-2d01e800-8364-11eb-8671-0e06e91bffb4.png)

**Desktop (please complete the following information):**
MacOS

**Additional context**
On Plugins page it is possible to; click-and-drag to scroll page or hover mouse of scroll bar and use scroll bar to drag
Trackpad scrolling works fine in Add Ons > Languages

**Comment by cbjeukendrup** [comment]
Add-ons > Extensions has the same problem.
