### ISSUE TITLE
[MU4 Issue] Plus button needs two clicks to works on Note Inpur Bar

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7745]
**Describe the bug**
Plus button needs two clicks to works on Note Inpur Bar

**To Reproduce**
1. Create a score
2. Click on 'Plus' button from the Note Input Bar

**Expected behavior**
Dropdown appears under Plus button

**Screenshots**
![2021-03-18 07_59_11-Window](https://user-images.githubusercontent.com/71372310/111575637-e2e39100-87bf-11eb-9e49-620cf85316c9.jpg)

**Desktop (please complete the following information):**
MacOS

**Comment by vshalkevich** [comment]
Doesn't work at all for Windows for now

**Comment by wizofaus** [comment]
Seems fine under Windows for me?

**Comment by vshalkevich** [comment]
now it works , thanks
