### ISSUE TITLE
[MU4 Issue] Upper menus disappeared after score was created

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7749]
**Describe the bug**
Upper Menus disappeared after score was created

**To Reproduce**
1. Create a score
2. Look at the upper menus (where should be File, Add, etc.)

**Expected behavior**
Upper Menus always present  

**Screenshots**

**Desktop (please complete the following information):**
MacOS

**Additional context**

**Comment by mattmcclinch** [comment]
Isn't this the same as #7691? Why post the same issue twice?
