### ISSUE TITLE
[MU4 Issue] New created score above created score, replaces previous score

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7750]
**Describe the bug**
Only second new score visible. The first created score dissappears
Video attached

**To Reproduce**
1.     Create a score for a scratch (from New Score Wizard)
2.     Click on a Home tab
3.     Click on a New Score (to start creating new score)
4.     Proceed creating second new score till the end

**Expected behavior**
Second new score should be create in a new tab next to previous score tab on a score page (Like in MU3 - try to do steps in MU3 and expected result should be the same)

**Desktop (please complete the following information):**
MacOS

**Comment by mattmcclinch** [comment]
Isn't this the same as #7643?
