### ISSUE TITLE
[MU4 Issue] [enhancement] The width of The grabber on the very left hand side on Note Input Bar should be 32px

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7763]
**Describe the bug**
The width of The grabber on the very left hand side on Note Input Bar is 35px
The width of The grabber on the very left hand side on Note Input Bar should be 32px

**To Reproduce**
1. Create a score
2. Look at Note Input Bar

**Expected behavior**
The width of The grabber on the very left hand side on Note Input Bar should be 32px

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/71372310/111849282-4388e000-891e-11eb-91f4-efebc31fe594.png)

**Desktop (please complete the following information):**
MacOS

**Comment by cbjeukendrup** [comment]
I believe that technically the width of the grabber is okay, but there is an erroneous 3px padding left to the buttons, produced by the GridView containing them.
