### ISSUE TITLE
[MU4 Issue] Ctrl/cmd+scroll not working to zoom

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7764]
**Describe the bug**
Ctrl/cmd+scroll not working to zoom

**To Reproduce**
1. Create a score
2. Ctrl/cmd+scroll up / down

**Expected behavior**
Score zoom in / out

**Desktop (please complete the following information):**
MacOS

**Additional Info**
Also "Pinch to zoom not working" on the score view

**Comment by vshalkevich** [comment]
It seems like issue fixed. Need confirmation from MacOS users

**Comment by HemantAntony** [comment]
This appears to be solved:

https://user-images.githubusercontent.com/88136054/144194547-60ebf11a-4521-4415-ad54-563b64a69a42.mp4

Also, I don't understand what you mean by "Pinch to zoom"

**Comment by cbjeukendrup** [comment]
"Pinch to zoom" means that you can zoom by making a "pinch" gesture with two fingers on the trackpad.

I can indeed confirm that Ctrl/Cmd+Scroll works perfectly on macOS and Windows, as well as "pinch to zoom".

**Comment by HemantAntony** [comment]
> "Pinch to zoom" means that you can zoom by making a "pinch" gesture with two fingers on the trackpad.
> 
> I can indeed confirm that Ctrl/Cmd+Scroll works perfectly on macOS and Windows, as well as "pinch to zoom".

Oh I thought it had something to do with a touchscreen, lol

**Comment by Jojo-Schmitz** [comment]
Well, that too I guess

**Comment by cbjeukendrup** [comment]
In fact, yes: the way I implemented it (using QML PinchArea) should also work on touch screens.

**Comment by DmitryArefiev** [comment]
Tested in master build on Win10, Mac12, LinuxMint 20.2 - DOESN'T OCCUR anymore

Closing 

> In fact, yes: the way I implemented it (using QML PinchArea) should also work on touch screens.

Don't have a laptop with  touch screen, can't check it..
