### ISSUE TITLE
[MU4 Issue] [Improvement] Need Score Playback cursor to indicate where playback will begin from. Score playback cursor dynamically should change position

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7765]
**Describe the bug**
Need Score cursor to indicate where playback will begin from
Score playback cursor dynamically should change position after changing time on Play Panel Menu
Now we can see Score Playback cursoor only when press "play" button on the score.

**To Reproduce**
1. Create a score
2. Change Playback time on Play Panel Menu

**Expected behavior**
Score playback cursor dynamically should change position after changing time on Play Panel Menu

**Desktop (please complete the following information):**
MacOS
Windows

**Comment by Tantacrul** [comment]
A bug as old as time.
