### ISSUE TITLE
[MU4 Issue] Can't undo stave transposition (made via right-click > Stave Properties)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7767]
**Describe the bug**
Can't undo stave transposition (made via right-click > Stave Properties)
Also, can't undo text editing

**To Reproduce**
1. Create score
2. Select note
3. right-click > Stave Properties

**Expected behavior**
stave transposition functions work

**Desktop (please complete the following information):**
MacOS

**Additional context**
About transposition
https://musescore.org/en/handbook/3/transposition

**Comment by wizofaus** [comment]
Reproduced. The undo works for any notes that have been transposed (and key signatures added etc.) but not for the actual staff property itself, working on a fix.
