### ISSUE TITLE
[MU4 Issue] Reset Palette destroys palette

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7769]
**Describe the bug**
Reset Palette destroys palette (makes reset palette disappear)

**To Reproduce**
1. Create a score
2. Click on Palette left side panel
3. Click on three dots on any Palette
4. Click Reset Palette 
5. Click Yes on a pop up

**Expected behavior**
Reseted palette drops to default 

**Desktop (please complete the following information):**
MacOS

**Comment by mattblo** [comment]
In the latest NightlyBuilds, resetting a palette causes Musescore 4 to crash

**Comment by DmitryArefiev** [comment]
Thank for the finding! Can reproduce it. Logged #10163
