### ISSUE TITLE
[MU4 Issue] Can't scroll in popup (need to if it doesn't fit on the screen)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7772]
**Describe the bug**
Can't scroll in popup (need to if it doesn't fit on the screen)

**To Reproduce**
1. Open MuseScore with the lowest possible screen resolution
2. Create a score
3. Add a note
4. Select note
5. Open "Inspector" tab
6. Click on Note Settings
7. Click on head
8. Try to scroll down "netehead" menu

**Expected behavior**
Menues should be able to scroll up and down if they don`t fit in the screen

**Screenshots**
![2021-03-21 05_19_57-Window](https://user-images.githubusercontent.com/71372310/111891576-46aacb80-8a05-11eb-8fe0-2ecd5f5aac4f.jpg)

**Desktop (please complete the following information):**
MacOS
Windows 10

**Comment by Mystic-Slice** [comment]
I am working on it.
