### ISSUE TITLE
[MU4 Issue] Can't edit Instrument names (staff labels) by double clicking on them

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7773]
**Describe the bug**
Can't edit Instrument names (staff labels) by double clicking on them

**To Reproduce**
1. Create a score with two or more instruments (instrumnts name should be displayed on the Score)
2. Double click on the Instrument name on the score

**Expected behavior**
It should be possible to change Instruments name by double click on them

**Screenshots**
![Can't edit Instrument names (staff labels) by double clicking on them](https://user-images.githubusercontent.com/71372310/111891696-c89af480-8a05-11eb-8953-857fde3a98b1.jpg)

**Desktop (please complete the following information):**
MacOS
Windows 10

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
