### ISSUE TITLE
[MU4 Issue] Scrolling too sensitive in customize toolbar dialog

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7774]
**Describe the bug**
If user scroll down it takes on the very bottom of the list. There should be less sensitive scrolling

**To Reproduce**
1. Create a score
2. Click on "Customize toolbar" icon
3. Scroll down 

**Expected behavior**
Scrolling should be less sensitive. One scroll click down for one instrument down

**Screenshots**
![Scrolling too sensitive in customize toolbar dialog](https://user-images.githubusercontent.com/71372310/111891749-229bba00-8a06-11eb-842e-dfe1862633c1.jpg)

**Desktop (please complete the following information):**
MacOS
Windows 10

**Comment by shoogle** [comment]
Also affects Windows.

**Comment by shoogle** [comment]
Definitely affects Windows but I'm not actually able to reproduce on macOS now. I suspect we did the review on Windows originally but I forgot to update the platform name when I copied the review notes from last time. I made a new template page for review notes where the platform is just "template" so I shouldn't forget to update it in future.

**Comment by shoogle** [comment]
Also affects Linux.

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/10085
