### ISSUE TITLE
[MU4 Issue] Soprano trombone named differently if add them via New Wizard Score and Instruments Panel

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7795]
**Describe the bug**
Soprano trombone named differently and different clef if added via NSW vs. Instruments dialog

**To Reproduce**
1. Start creating score
2. Add Soprano trombone instrument on New Score Wizard
3. Click "Done" to proceed to the Score View
4. Click on "Instruments" from the instruments panel
5. Click "Add"
6. Find Soprano trombone and add it on the score
7. Look at the two names of "Soprano trombone" on the Score View

**Expected behavior**
They should be named the same - "Soprano Trombone"
Soprano trombone added via Instruments panel should be named the same as it named via New Score Wizard

**Screenshots**
![2021-03-24 23_20_40-MuseScore 4](https://user-images.githubusercontent.com/71372310/112388379-1a909280-8d04-11eb-99bd-3dbe9ae7f227.jpg)

**Desktop (please complete the following information):**
MacOS
Windows 10

**Comment by Mystic-Slice** [comment]
If I understand it correctly, in the first set of staves, each stave is for the diff instruments added (one through NSW and the other through the palette). The second set of staves is the continuation of the music. The names in the second set of staves are S. Tbn. for providing more space for the sheet music (any instrument's name is shortened from the second set of staves).

**Comment by Mystic-Slice** [comment]
![image](https://user-images.githubusercontent.com/73862377/114075575-4f374900-98c3-11eb-8125-afd882f9cef6.png)
Hope this screenshot provides more clarity.
