### ISSUE TITLE
[MU4 Issue] Glissando Inspector missing text options

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7796]
**Describe the bug**
Glissando Inspector missing text options

**To Reproduce**
1. Create a score
2. Add Glisando on the score
3. Select Glisando
4. Open Inspector tab from the left Instruments panel

**Expected behavior**
Glisando should have text options

**Screenshots**
![Glisando missing text options](https://user-images.githubusercontent.com/71372310/112393107-93dfb380-8d0b-11eb-8091-cd2011ef9a34.jpg)

**Desktop (please complete the following information):**
MacOS

**Additional context**

**Comment by wizofaus** [comment]
Seems to be quite a lot of missing options in the glissando inspector for MU4 vs MU3, so I'm assuming it just hasn't been implemented fully yet?  Also the "gliss." text isn't shown in the palette or added by default as it is in MU3, and there appears to be no way to set this at all.
