### ISSUE TITLE
[MU4 Issue] "Channel and MIDI Properties" text on Inspector bad aligned if MU4 window shrink to minimum

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7797]
**Describe the bug**
"Channel and MIDI Properties" text on Inspector bad aligned if MU4 window shrink to minimum

**To Reproduce**
1. Create a score
2. Add Articulations on the score
3. Select Articulations
4. Open Inspector from the left Instruments panel
5. Minimize MU4 window 
6. Look at "Channel and MIDI Properties" text 

**Expected behavior**
"Channel and MIDI Properties" text should fit in the button on any screen resolution

**Screenshots**

![2021-03-25 01_28_34-MuseScore 4](https://user-images.githubusercontent.com/71372310/112393290-e1f4b700-8d0b-11eb-8803-01f768ae1b7a.jpg)

**Desktop (please complete the following information):**
MacOS
Windows 10

**Additional context**

**Comment by vshalkevich** [comment]
Do Articulations in the Inspector have missing options ?
![2021-03-25 01_28_34-MuseScore 4](https://user-images.githubusercontent.com/71372310/112394251-6eec4000-8d0d-11eb-9909-5a23103a3fa7.jpg)

**Comment by Howard-C** [comment]
> Do Articulations in the Inspector have missing options ?
> ![2021-03-25 01_28_34-MuseScore 4](https://user-images.githubusercontent.com/71372310/112394251-6eec4000-8d0d-11eb-9909-5a23103a3fa7.jpg)

No, but the dialogue has not been migrated yet (or is unable to be triggere by the button)
