### ISSUE TITLE
[MU4 Issue] All single-character shortcuts should be disabled during text and lyric editing

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7815]
**Describe the bug**
While user editing text and pressing single-character shortcut it leads out of the text editing.
Also, Global shortcuts function during text editing (bad) (this might be a separate bug)

**To Reproduce**
1. Create a score with Text (at least Title)
2. Start editing any score text (for example Score Title)
3. Press "C" button from the keyboard (or any single-character shortcut)

**Expected behavior**
All single-character shortcuts should be disabled during text and lyric editing

**Screenshots**

**Desktop (please complete the following information):**
MacOS
Windows 10 x64

**Additional context**

**Comment by wizofaus** [comment]
I fixed this some time back by having the text field being edited process all keystrokes before shortcuts are translated.   I believe it can be closed @vshalkevich
