### ISSUE TITLE
[MU4 Issue] Shouldn't be able to scroll past edge of score

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7818]
**Describe the bug**
Score is scrolling past edge

**To Reproduce**
1. Create a score
2. Try to scroll past edge of score

**Expected behavior**
Shouldn't be able to scroll past edge of score

**Screenshots**

**Desktop (please complete the following information):**
MacOS
Wndows 10

**Additional context**

**Comment by Shivansh-Bakshi** [comment]
Edit->Preferences->Canvas (on the left menu) has an option to limit scroll area to page borders

**Comment by vshalkevich** [comment]
Thanks. 
Need to decide default statements. I will update expected result or just keep as is and close this issue

**Comment by shoogle** [comment]
> Edit->Preferences->Canvas (on the left menu) has an option to limit scroll area to page borders

You shouldn't be able to scroll forever even if that option is disabled.

### Scroll limit on

You should be able to scroll until you see a little bit of background, but mostly just the page.

![image](https://user-images.githubusercontent.com/11011881/113464954-64086e00-93e5-11eb-852c-c6757ca21031.png)


### Scroll limit off

You should be able to scroll until you see mostly background and only a little bit of page.

![image](https://user-images.githubusercontent.com/11011881/113464983-9914c080-93e5-11eb-8c3a-2ab02d1e8438.png)

There should never be a situation where you can see all background and no page.

**Comment by shoogle** [comment]
FWIW, the only reason I can think of for having a "limit off" mode is to make room for floating windows above the score.

### Scroll limit on

If a floating windows covers the left side of the screen then it is not possible to see the left side of the score.

![image](https://user-images.githubusercontent.com/11011881/113868541-b19b2700-97a7-11eb-9209-ba81acb919b0.png)

### Scroll limit off

You can scroll a bit further to see the left side of the score.

![image](https://user-images.githubusercontent.com/11011881/113869003-279f8e00-97a8-11eb-90eb-49b445e9ed63.png)

So we only need to be able to scroll far enough to allow this use-case (e.g. score occupies 25% of viewable area).

Of course the floating window might not be from MuseScore. It could be a calculator, browser tab, or PDF viewer.

**Comment by MarcSabatella** [comment]
The original reason was actually different as I recall - to make sure that as you zoom out, the same spot can remain in focus (centered at mouse cursor for example) - zooming should not move the canvas.  Then you can zoom right back in and be back where you started.  This to me is the crucial use case to continue to support.  But additional windows are nice too.

**Comment by shoogle** [comment]
Good point @MarcSabatella! There's usually a reason somewhere behind the madness!
