### ISSUE TITLE
[MU4 Issue] Scores should open on first page even if previous score was closed on a different page

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7820]
**Describe the bug**
If user closes score on the second or upper page and then open another score, it will be opened from those page which was opened on a previous closed score

**To Reproduce**
1. Create a score with at least 2 pages
2. Close the score on the 2-nd page or higher
3. Open new score with at least 2 pages > score will be opened on the 2-nd page

**Expected behavior**
Scores should open on first page even if previous score was closed on a different page
each score should have its own scrolling and zooming state

**Screenshots**

**Desktop (please complete the following information):**
MacOS

**Additional context**

**Comment by cbjeukendrup** [comment]
I think this should be generalized: each score should have its own scrolling and zooming state. For example, when you have two scores opened (which seems not yet possible), and in score A you are working on page 3 and in score B you are working on page 7, it would be annoying if you had to scroll every time when switching to the other score. This situation could occur for example when working in both the full score and in the parts.

**Comment by vshalkevich** [comment]
Good point
