### ISSUE TITLE
[MU4 Issue] Pressing space, dash, underscore does not move to next note

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7823]
**Describe the bug**
Lyrics editing: pressing space, dash, underscore does not move to next note (try this in 3.6)

**To Reproduce**
1. Create a score
2. Add lyrics and notes
3. Select note
4. press space, dash, underscore

**Expected behavior**
pressing space, dash, underscore should move to next note (try this in 3.6)

**Screenshots**

**Desktop (please complete the following information):**
MacOS

**Additional context**

**Comment by wizofaus** [comment]
In general "space" and other key handling doesn't work when editing lyrics the way it does in MU3.6, it has quite special handling for Lyrics elements (ScoreView::editKeyLyrics) that doesn't exist in the MU4 codebase yet (looks like the MuseScoreView interface is designed to be able to handle this, but there's only a dummy implementation currently).
