### ISSUE TITLE
[MU4 Issue] Changing page size doesnt make effect on a Text (like Title, Lyrics, Author, etc.)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7824]
**Describe the bug**
Changing page size doesnt make effect on a Text (like Title, Lyrics, Author, etc.)

**To Reproduce**
1. Create a score with text (like Title, Lyrics, Author, etc.)
2. Click Inspector from the Instruments Panel
3. Change Page size to A6 (or any other)

**Expected behavior**
Text should change it`s positioning according to Page Size

**Screenshots**
![2021-03-30 05_35_16-Window](https://user-images.githubusercontent.com/71372310/112925224-3045f380-911a-11eb-9c87-1b2cf5f44d9e.jpg)

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by wizofaus** [comment]
Can't reproduce, appears to be fixed?
