### ISSUE TITLE
[MU4 Issue] Background image doesn't work

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7830]
**Describe the bug**
Background image doesn't work

**To Reproduce**
1. Create a score
2. Click on Edit from the upper Menu Bar
3. Click on 'Preferences
4. Click on Folders from the left panel
5. Try to change Image and see it on the score

**Expected behavior**
Image should be centered on the score

**Screenshots**

**Desktop (please complete the following information):**
MacOS
Windows 10

**Additional context**
Need more info about Expected Behavior. Maybe we should change it or add more parameters such as minimum image size?

**Comment by cbjeukendrup** [comment]
I found the problem, PR coming soon
