### ISSUE TITLE
[MU4 Issue] The title bars of each window / dialog are still light coloured after changing theme.

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7849]
**Describe the bug**
The title bars of each window / dialog are still light coloured after changing theme.

**To Reproduce**
1. Click on Edit from the upper Menu Bar
2. Click on 'Preferences
3. Click on Appearance from the left panel
4. Change Theme

**Expected behavior**
The title bars of each window / dialog should change it's colour according to the theme

**Screenshots**

**Desktop (please complete the following information):**
MacOS

**Additional context**

**Comment by cbjeukendrup** [comment]
I am working on some platform theme stuff, and will make sure to include a fix for this!

**Comment by cbjeukendrup** [comment]
@vshalkevich Could you check how this is now that PR #7862 is merged?
On Mac, it should be okay now.

(On Windows, it's maybe also possible, but that seems a bit more difficult.)

**Comment by vshalkevich** [comment]
![2021-04-08 10_00_58-](https://user-images.githubusercontent.com/71372310/113982449-70f7e800-9851-11eb-9710-e19120950797.jpg)
![2021-04-08 10_01_13-](https://user-images.githubusercontent.com/71372310/113982451-71907e80-9851-11eb-9e55-faa936c16ec3.jpg)
Score seems such way on Windows. I am not sure is this intended behavior

**Comment by JGreenlee** [comment]
Looking great on Mac thanks to @cbjeukendrup.

For Windows, we have a couple options. Here is a quick mockup of what I would consider an ideal solution:

![image](https://user-images.githubusercontent.com/15843932/118384920-62cb8300-b5d8-11eb-98db-daf7261558b6.png)

The menus, title bar, and window decorations are condensed onto the same theme-observant bar, which saves vertical screen space and looks much cleaner to my eyes.


Accomplishing the above may prove particularly difficult, so here is an alternative mockup:

![image](https://user-images.githubusercontent.com/15843932/118385165-b4750d00-b5da-11eb-9b19-904ca8b55044.png)


In either case, a custom title bar will have to be built, as styling the existing title bar that Windows provides is not a feasible option. It also seems that Qt itself does not offer a satisfactory implementation of client-side window decorations ([we would lose the ability to snap windows into place](https://github.com/johanhelsing/qt-csd-demo/issues/11)).

So, what should be the course of action?

**Comment by cbjeukendrup** [comment]
@JGreenlee There is currently being worked on something exactly like you suggested 😀. 
It is not visible in normal builds at this moment, but the developers implemented a custom title bar in QML and made the window frameless. We use a mouse area to enable move and resize functionality. However, indeed AeroSnap doesn't work unfortunately, and there are some bugs with the solution and other things we are not fully satisfied with. So my expectation is that we will have to implement a custom Win32 window and place the Qt stuff inside. But maybe we will figure out something different.

**Comment by JGreenlee** [comment]
@cbjeukendrup

Great to hear! I'm not too familiar with Qt but I know that plenty of other programs use custom title bar / decorations. Perhaps studying such code could help in replicating a similar behavior with Musescore's own implementation?

For one, I know that Telegram's desktop app uses Qt and has a custom title bar. The window always works flawlessly. Telegram also gives the option of seamlessly switching between the native title bar and its custom title bar (could also be something to consider?).

Whatever the implementation, I'll keep my eye out for a PR about it ;)
Thanks!

**Comment by vshalkevich** [comment]
Can`t reproduce. Fixed
