### ISSUE TITLE
[MU4 Issue] Can't reorder parts in dialog

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7850]
**Describe the bug**
Can't reorder parts in dialog

**To Reproduce**
1. Create a score
2. Open Parts dialog
3. Add parts and try to reorder it

**Expected behavior**
It is possible to reorder parts (by drag&drop for example)

**Screenshots**

**Desktop (please complete the following information):**
MacOS

**Additional context**

**Comment by wizofaus** [comment]
Confirmed and also note that there's an extra "Untitled" part at the top.
This dialog seems such a radical departure from that in MU3 though I'm not sure it's suitable for working on just yet (plus if it involves Qt stuff I'm probably going to struggle!)

**Comment by njvdberg** [comment]
This is also part of the rewrite as discussed on [discord](https://discord.com/channels/818804595450445834/818848561047273544/851484720331358218)

**Comment by vshalkevich** [comment]
For now it is not needed work
