### ISSUE TITLE
[MU4 Issue] after "Factory reset" Palettes brokes or gone

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7857]
**Describe the bug**
after "Factory reset" Palettes brokes or gone:
On Windows 10 Palettes disappears. 
On MacOS user cannot drag&drop Palettes and Palettes changes background colour

**To Reproduce**
1. Go to "Help" on the Upper Menu bar
2. Click on 'Revert to the factory settings'
3. Create a new score
4. Open Palettes tab

**Expected behavior**
Palettes should work 

**Screenshots**
This is how Background looks after Factory reset
![image_2021_03_31T15_26_38_568Z](https://user-images.githubusercontent.com/71372310/113170796-8f595480-924f-11eb-945d-a2db9d912365.png)
This is how it should look like
![image_2021_03_31T15_27_06_949Z](https://user-images.githubusercontent.com/71372310/113170825-984a2600-924f-11eb-9068-80c685df277e.png)

**Desktop (please complete the following information):**
Windows 10
MacOS

**Additional context**

**Comment by musicalcomposer** [comment]
oh yeah before i switched to flat.io, it looked like that
