### ISSUE TITLE
[MU4 Issue] rename the Inspector to 'Properties'

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7864]
**Describe the bug**
rename the "Inspector" tab (from the instruments panel) to 'Properties'

![2021-04-02 04_13_40-MuseScore 4](https://user-images.githubusercontent.com/71372310/113369453-0aaf2900-936a-11eb-89cf-52ce3ba2255e.jpg)

**Comment by Howard-C** [comment]
I would keep this issue open since there're more references to the Inspector than the one string that got changed here...
