### ISSUE TITLE
[MU4 Issue] Licence violations: VST3 SDK, Google Crashpad Client, OpenSSL

### ISSUE THREAD

**Issue by mirabilos** [musescore/MuseScore#7866]
**Describe the bug**

MuseScore 4 binary distributions violate the licences of multiple components:
- that of MuseScore itself and its GPLv2-only or LGPLv2.x-only licenced dependencies (in all of the named cases), the GPLv2
- that of @steinbergmedia VST3 SDK (in the VST3 SDK case), the GPLv3
- that of OpenSSL (in the OpenSSL case), the SSLEay and OpenSSL licences

The individual violations are caused by:
- combining GPLv2-only code (MuseScore and the aforementioned dependencies) with GPLv3-only code (the VST3 SDK)
- combining GPLv2-only code with Apache2-licenced code (the Google Crashpad client); the Apache2 licence is incompatible with the GPLv2
- combining GPL code with OpenSSL in a way that makes OpenSSL accompany the GPL-licenced code

**To Reproduce**
1. Inspect the git repository, `master` branch

**Expected behavior**
MuseScore binaries are ideally Free Software and at the very least redistributable

Note: this is not the result of a full licence analysis. I only saw @Tantacrul bragging about VST stuff with MuseScore and thought to have a quick look at how this is integrated and found it illegal and found the others (which _probably_ exist in MuseScore 3 (except in the Debian package, of course, which is 100% clean) as well) en passant.

**Comment by mirabilos** [comment]
btw [I warned you about this over six months ago](https://musescore.org/en/MuseScore4#comment-1028726)

**Comment by mirabilos** [comment]
and apparently @dmitrio95 (then a core developer) [knew about this in 2019](https://musescore.org/en/node/294612#comment-946820)

**Comment by JGreenlee** [comment]
Because of the [move to GPLv3 ](https://musescore.org/en/node/320043), I believe this issue can now be closed?

**Comment by Tantacrul** [comment]
> btw [I warned you about this over six months ago](https://musescore.org/en/MuseScore4#comment-1028726)

We all knew VST3 and GPL2 were incompatible. This is why we moved to GPL3. Why not DM one of us and we would have told you, lol.
