### ISSUE TITLE
[MU4 Issue] Can't copy or paste text to or from another program

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7881]
**Describe the bug**
Can't copy or paste text to or from another program

**To Reproduce**
1. Create a score with title  
2. Copy text from another app
3. Double click on score title to change it
4. Try to paste copied text from another program

**Expected behavior**
User can copy and paste text in MuseScore from another apps

**Screenshots**

**Desktop (please complete the following information):**
Linux Ubunty

**Additional context**

**Comment by wizofaus** [comment]
Should be fixed by https://github.com/musescore/MuseScore/pull/8306
