### ISSUE TITLE
[MU4 Issue] Can't add text (staff text, lyrics, tempos, frames, etc.)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7882]
**Describe the bug**
A short and clear description of what the bug is.

**To Reproduce**
1. Try to create a score with text, lyrics, tempos)

**Expected behavior**
It is possible to create text, lyrics, etc.

**Screenshots**

**Desktop (please complete the following information):**
Linux Ubunty

**Additional context**

**Comment by wizofaus** [comment]
I suspect you're seeing what I did which is that palette commands that add elements as children of/anchored to other elements don't trigger a proper refresh so you don't see the newly added elements straight away. Should be fixed by https://github.com/musescore/MuseScore/pull/8274

**Comment by wizofaus** [comment]
@vshalkevich can you still see a problem here?
