### ISSUE TITLE
[MU4 Issue] Re-ordering instruments affects score but not the parts

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7883]
**Describe the bug**
Re-ordering instruments affects score but not the parts
After reordering instruments in Instruments panel they stay unchanged on parts dialog

**To Reproduce**
1. Create a score with at least 2 instruments
2. Change instruments order in Instruments panel
3. Open parts dialog
4. Compare instruments order in Instruments panel and Parts dialog 

**Expected behavior**
Parts ordering should be changed as instruments order

**Screenshots**
![2021-04-03 03_34_32-MuseScore 4](https://user-images.githubusercontent.com/71372310/113463272-91790a00-942d-11eb-8204-ad13a1540ec1.jpg)

**Desktop (please complete the following information):**
Windows 10
Linux Ubunty

**Additional context**

**Comment by RomanPudashkin** [comment]
Not actual anymore (see the last instruments UX document)
