### ISSUE TITLE
[MU4 Issue] No way to create a new part that includes instrument without making visible manually via Instrument panel

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7884]
**Describe the bug**
No way to create a new part that includes instrument without making visible manually via Instrument panel

**To Reproduce**
1. Create a score with instruments
2. Click on Parts dialog
3. Add new part
4. Try to add all instruments in a Parts dialog

**Expected behavior**
There should be possibility to add all instruments from the main score in a parts dialog

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10
 Linux Ubunty

**Additional context**

**Comment by vshalkevich** [comment]
@shoogle Needs more info about expected behavior: what steps should we add all instruments in a part via Parts dialog?

**Comment by shoogle** [comment]
Within the Parts dialog it is possible to select multiple parts by holding Ctrl (macOS: Cmd) or Shift when you click on them.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/11011881/113463806-02440600-93dd-11eb-9790-9e30fbaa492e.png">

If you select multiple parts and press "Open" then each part gets opened in a separate tab. This is good.

If you select multiple parts and then press "Create new part" then the new part is empty. This is bad. I think the new part should contain all instruments from parts that were selected when you pressed the "Create new part" button.
