### ISSUE TITLE
[MU4 Issue] Goes blank after clicking on note and away again

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7885]
**Describe the bug**
Goes blank after clicking on note and away again

**To Reproduce**
1. Create a score
2. Add a note
3. Open inspector tab from the Instruments panel
4. Select a note
5. Deselect note
6. Select a note again
7. Observe Inspector tab

**Expected behavior**
Inspectors should not be blank

**Screenshots**

**Desktop (please complete the following information):**
Linux Ubunty

**Additional context**

**Comment by wizofaus** [comment]
Can't reproduce?
But did notice that clicking ESC after bringing up Note Settings popup didn't behave as expected (it deselected the note rather than just dismissing the popup)
