### ISSUE TITLE
[MU4 Issue] Inspector has white background in all themes 

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7916]
**Describe the bug**
Inspector has white background in all themes 

**To Reproduce**
1. Create a score
2. Change theme (by Edit > Preferences > Appearance > White / Black / High Contrast themes)
3. Open Inspector (from the left side Instrument Panel on the Score View)

**Expected behavior**
Inspector tab should be such color as selected theme

**Screenshots**

**Desktop (please complete the following information):**
MacOS

**Additional context**

**Comment by cbjeukendrup** [comment]
It was not only in the Inspector, but in general with some types of controls. I believe this is fixed since https://github.com/musescore/MuseScore/commit/e7f06617f785699d87c07bbbcdd1bd0de8b9b0cd

**Comment by vshalkevich** [comment]
Can`t check for now on Windows because of broken "MuseScore4.exe" file. 
Will keep open this bug for some time until check it

**Comment by JRYamasaki** [comment]
Can confirm this is fixed using dark mode and high contrast
![image](https://user-images.githubusercontent.com/25189861/117234948-c71d6400-adda-11eb-806a-d9208f6b7110.png)
![image](https://user-images.githubusercontent.com/25189861/117234972-d1d7f900-adda-11eb-8fc0-9de64ff7eafd.png)

Currently on commit 68ef8a6e85725618d5e00998d521a3690731f8ec
