### ISSUE TITLE
[MU4 Issue] Time Signature not centered in box

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7926]
**Describe the bug**
Time Signature numbers not centered in box

**To Reproduce**
1. Click on Creating New Score Wizard
2. Click on 'Next' button
3. Click on "Time Signature"
4. Observe alignment of numbers in the box from the dropdown (screenshot attached)

**Expected behavior**
Time Signature numbers should be centered in the box

**Screenshots**
![2021-04-10 11_51_07](https://user-images.githubusercontent.com/71372310/114264394-5f4e4600-99f3-11eb-89e0-8a24de167c11.jpg)

**Desktop (please complete the following information):**
MacOS

**Comment by Howard-C** [comment]
If you mean the numbers in the scroll box and menu box, I don't see the necessity for them to be centred...

**Comment by JackMechem** [comment]
That is what every other drop down will look like.
