### ISSUE TITLE
[MU4 Issue] Parts and Mixer, Play panel should not be visible at all (not just disabled)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7928]
**Describe the bug**
Parts and Mixer, Play panel should not be visible at all (not just disabled)
When the user runs MuseScore 4 it may see play panel near the upper menu
**This Bug has low reproducing Rate**

**To Reproduce**
1. Start MuseScore 4
2. Observe panel with Home, etc.

**Expected behavior**
No play panel should be near the Home tab

**Screenshots**

**Desktop (please complete the following information):**
MacOS

**Comment by cbjeukendrup** [comment]
Seems fixed with new docking system.
