### ISSUE TITLE
[MU4 Issue] Task to Add gradient to show when scrolling is needed 

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7929]
**Describe the bug**
Gradient in Add-ons, Languages is not obvious enough (scrolling)
Add gradient to show when scrolling is needed (according to Figma)

**To Reproduce**
1. Go to 'Home Tab'
2. Click on 'Add Ons'
3. Click on 'Languages'
4. Locate at bottom of the screen

**Expected behavior**
Taller gradient at the bottom

**Screenshots**
[
![Screenshot 2021-04-13 at 17 00 59](https://user-images.githubusercontent.com/71656189/114587691-cf6ffc80-9c7d-11eb-8505-c2dde208f19d.png)
](url)

**Desktop (please complete the following information):**
MacOS

**Comment by RobFog** [comment]
Something seems to be off with the screenshot. When I click it, that sends me to https://github.com/musescore/MuseScore/issues/url

**Comment by vshalkevich** [comment]
@jessjwilliamson I guess it might be you who added screenshot. Could you, please re-upload screenshot? Can`t open it too
