### ISSUE TITLE
[MU4 Issue] Adopting QML Coding Guidelines

### ISSUE THREAD

**Issue by Furkanzmc** [musescore/MuseScore#7943]
I recently watched Vasily's talk on Qt Desktop Days and found out about MU4 and its use of QML. I see that you have coding guidelines for QML [here](https://github.com/musescore/MuseScore/wiki/CodeGuidelines#qml), but it seems to be very limited. Since it's a new project, I assume not much effort has gone into creating it yet.

I've been using QML for over 7 years now, and I'm working on a similar project to yours where we modernize a legacy system to use QML (Our approach is 100% QML, no Qt Widgets). I started writing QML coding guidelines a while ago to share my experience with it and hopefully to attract community contributions and grow it into something similar to C++ Core Guidelines.

Since you are working on a QML project from the ground up, your experience and contribution would be invaluable to this guideline. I've gotten some feedback from one of the Qt developers, Mitch Curtis, and it was a significant improvement. I've started some side projects to work on `qmllint` and `qmlformat` to integrate some of the aspects of the guideline as well (Currently on hold, waiting for the development of QmlDom to be finished.).

QML does not have great tooling support yet, it's in their list of things to do. And I'm hoping we can build some community guidelines fuelled with diverse experience so we can have tooling to adjust to these.

It'd be great to have your contribution, maybe apply the guidelines to your project. Since MuseScore is a big open source project, helping with building a guideline would be a tremendous contribution to QML community.

You can find the guideline here: https://github.com/Furkanzmc/QML-Coding-Guide/

**Comment by Tantacrul** [comment]
Closing, since it is not an issue with the development of MS4. I do like the request though :)

**Comment by cbjeukendrup** [comment]
In a way, this is definitely related to the development of MS4, since now we're really using QML widely. Personally, I wouldn't like to have to follow strict rules, but it absolutely makes sense to have some kind of pattern. Over time, our own style has emerged, and it is largely in line with the guidelines mentioned above. So thanks for the inspiration, @Furkanzmc!

**Comment by Tantacrul** [comment]
I mean it is not related to the completion and release of MS4, hence why I'm closing it.

However, the idea is excellent.
