### ISSUE TITLE
[MU4 Issue] Many shortcuts are not implemented

### ISSUE THREAD

**Issue by aaaeka** [musescore/MuseScore#7946]
**Describe the bug**
Many shortcuts from the ```shortcuts.xml``` file are not yet implemented in MU4

**List of unimplemented shortcuts by action name**

- [x] chord-tie - #7967
- [x] rest - #7967
- [x] rest-1 - #7967
- [x] rest-2 - #7967
- [x] rest-4 - #7967
- [x] rest-8 - #7967
- [x] up-chord - #7967
- [x] down-chord - #7967
- [x] first-element - #7967
- [x] last-element - #7967
- [x] palette-search - implemented, but  takes long time to complete
- [ ] get-location
- [ ] move-up
- [ ] move-down
- [ ] select-next-measure
- [ ] select-prev-measure
- [ ] select-begin-line
- [ ] select-end-line
- [ ] select-begin-score
- [ ] select-end-score
- [ ] select-staff-above
- [ ] select-staff-below
- [ ] scr-next
- [ ] scr-prev
- [ ] page-prev
- [ ] page-next
- [ ] page-top
- [ ] page-end
- [x] append-measure
- [ ] clef-violin
- [ ] clef-bass
- [ ] reset - implemented incorrectly
- [ ] help
- [ ] zoom100
- [ ] mirror-note
- [x] double-duration
- [x] half-duration
- [x] inc-duration-dotted
- [x] dec-duration-dotted
- [ ] repeat-sel
- [x] enh-both
- [x] enh-current
- [ ] fullscreen - only works with Meta+Ctrl+F, but not with Ctrl+U
- [ ] symbols
- [x] toggle-visible
- [ ] lock
- [ ] print

**Comment by wizofaus** [comment]
I'm doing move-up/move-down (and some others not mentioned here in https://github.com/musescore/MuseScore/pull/8879).  I think quite a number of these (particularly the select- ones) are done already.

**Comment by wizofaus** [comment]
Will start going through these and any others that don't appear to be have been ported from MU3 yet, happy for you to assign to me @Tantacrul.

**Comment by wizofaus** [comment]
palette-search - works but at least in my debug build can sometimes take a *long* time to react, >2 seconds!

get-location - unimplemented, but I'm not 100% sure what it's supposed to do in MU3, do I need to install NVDA?  I can implement code that does mostly the same thing, but will be hard to verify.

select-next-measure, select-prev-measure, select-begin-line, select-end-line, select-begin-score, select-end-score,select-staff-above,select-staff-below - not hooked up, but libmscore implementation still in place, should be straightforward

scr-next, src-prev, page-up, page-prev, page-top, page-end (to support PageUp/PageDn/Home/End) - no code to support these, will require porting (from ScoreView::screenNext/screenPrev/pageNext/pagePrev/pageTop/pageEnd)

append-measure - already works

clef-violin, clef-bass - clef-violin should surely be called clef-treble? Anyway, not hooked up at all, simple enough to re-use implementation from MU3 however I want to fix it not to add the clef in the entry mode cursor position if not in a step entry mode.

 reset - incorrectly implemented, simple fix (it's actually hooked up to reset "text style overrides" currently)

 help - NB command is called "Online Handbook" in Preferences dialog/menu. Not hooked up to shortcut mechanism, only available from Help menu. NB currently this menu command navigates to https://musescore.org/en/handbook-musescore-2 - presumably we'll have a handbook for musescore 4 at some point!

 zoom100 - only partially hooked up, needs an action defined for it.

 mirror-note - not hooked up, but libmscore implementation still present

 double-duration/half-duration/inc-duration-dotted/dec-duration-dotted - already working as per MU3, meaning it only works if only a single note or rest is selected

 repeat-sel - not ported at all, was in  ScoreView::cmdRepeatSelection() in MU3

 enh-both/enh-current - was implemented just recently (by yours truly)

 fullscreen - works fine but note that the current master build doesn't support the factory default Ctrl+U shortcut, I have a fix for that but there is an issue that Ctrl+U means something else in text editing mode, which I'll have to address.

 symbols - not hooked up, but I assume it can just activate the existing "show master palette" command. There had been some discussion around simplifying the master palette to *just* be for symbols. 

 toggle-visible - appears to work fine, though implementation is quite different to MU3, might need to check.

 lock - not implemented at all, there is code to make the NotationViewInputController "readonly", but that locks even zooming commands etc.  However there are quite a few major issues with "lock" in MU3, see https://musescore.org/en/node/311604 so it will make sense to address as many as we can.  Need to consider whether the 'locked' flag should be a property of the actual score that prevents any modifications to it.

**Comment by Tantacrul** [comment]
> Will start going through these and any others that don't appear to be have been ported from MU3 yet, happy for you to assign to me @Tantacrul.

Done!

**Comment by aaaeka** [comment]
Updated the list accordingly.

**Comment by wizofaus** [comment]
I've actually done almost everything now (including the ones https://github.com/musescore/MuseScore/issues/8819), except scr-next/src-prev/page-up/page-prev/page-top/page-end (should be reasonably fairly straightforward), symbols/get-location/help, then the big remaining two are lock and unroll-repeats, which I believe need design discussion before implementing and probably should go into a separate PR. I don't get why 'unroll-repeats' needs to open a whole new score, and this would be quite a weird experience in MU4 as it would launch a new MuseScore process etc.  However there's no straightforward to have it such that the current "notation" being shown has its underlying Score object replaced in such a way that it's undoable.  For "lock" to be useful (and, TBH, in MU3 it really isn't) requires quite a lot of app-wide changes, including having all the various properties dialogs/panels operate in "read only" mode.

@Tantacrul

**Comment by Tantacrul** [comment]
We should jump on a call shortly to go through these when you've time.

**Comment by wizofaus** [comment]
Absolutely, but perhaps not when it's 2AM here :-)

**Comment by RobFog** [comment]
Should this issue be updated now that #8908 has been merged?

**Comment by wizofaus** [comment]
Yeah we should at least tick off the ones that have been implemented (including "move-up" and "move-down"), but there's still quite a number left.

**Comment by HemantAntony** [comment]
It would be great if this list can be updated. If this issue has gone cold, I am okay with creating one

**Comment by Tantacrul** [comment]
I think we need a re-assessment of shortcuts. This issue is now too cold. Closing.
