### ISSUE TITLE
[MU4 Issue] Custom "User" text styles not available in Inspector or Style dialog

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7968]
**Describe the bug**
Custom "User" text styles not available in Inspector or Style dialog

**To Reproduce**
1. Create a score
2. Add lyrics (any text) on the score
3. Open Inspector
4. Select text
5. Try to change Text Style via Inspector (or Style dialog)

**Expected behavior**
User may change Text Style 

**Screenshots**

**Desktop (please complete the following information):**
MacOS

**Comment by HemantAntony** [comment]
This appears to be fixed
