### ISSUE TITLE
[MU4 Issue] Help > About... Replace link to donate page, change text, say GPL version, say build etc.

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7970]
**Describe the bug**
About MuseScore pop-up content is missed

**To Reproduce**
1. Click on "Help" (from the Upper Menu)
2. Click on 'About...'
3. Check About MuseScore pop-up links and text

**Expected behavior**
1) Replace link to donate page with link to contribute page and rephrase to "Help with MuseScore's development".
2) musescore.org link should take you to that page, not musescore.org/en-GB etc. (it should take to the user's language page)
3) Should say GPL version (soon to be GPL 3)
4) should say "development build", "nightly build" or similar (and build version)

**Desktop (please complete the following information):**
MacOS
Windows 10

**Comment by RobFog** [comment]
"it`s" → its

**Comment by Jojo-Schmitz** [comment]
Which URL exactly should the contribute link point to? It IMHO should be the user's language, but https://musescore.org/contribute doesn't redirect properly and e.g. https://musescore.org/de/contribute doesn't exist, it is https://musescore.org/de/unterstuetzung in that case.
Which word should be shown for the link, "development", or "Help"?

**Comment by vshalkevich** [comment]
Need to detail information
@shoogle Could you look at Expected result and add information:
Which URL exactly should the contribute link point to?
Which word should be shown for the link, "development", or "Help"?

**Comment by shoogle** [comment]
@vshalkevich, the link should always point to https://musescore.org/contribute and we should fix the website to do the redirection to translated pages such as https://musescore.org/de/mitwirken based on the user's browser settings.

@Jojo-Schmitz, the link above appears to be the German page though the translation is barely started. Let me know if you can/cannot edit that page.

Here is the current About dialog:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/11011881/115307006-7db3f000-a11d-11eb-8b32-d2aa4fce4ff1.png">

Let's change the following:

> Visit www.musescore.org for new versions and more information.
> Support MuseScore with your [contribution](https://musescore.org/contribute).

To:

> Visit www.musescore.org for new versions and more information.
> Get [help](https://musescore.org/forum) with the program or [contribute](https://musescore.org/contribute) to its development.

with links to https://musescore.org/forum and https://musescore.org/contribute.

It should also say:

> Version: 4.0.0 development build

or "nightly build", and:

> Published under the [GNU General Public License version 3](https://www.gnu.org/licenses/gpl-3.0.html).

with link to https://www.gnu.org/licenses/gpl-3.0.html.

**Comment by shoogle** [comment]
@vshalkevich, BTW, don't feel you have to obey the issue template religiously if it makes more sense to do something else. E.g. *"Help > About looks like [...], it should look like [...]."* would be fine for this issue.

**Comment by Jojo-Schmitz** [comment]
I can translate that https://musescore.org/de/mitwirken

Running into a bit of a problem with getting the requested changes done for master (the interaction of cpp and qml is foreign to me), so created a 3.x PR first.

**Comment by vshalkevich** [comment]
> 
> 
> I can translate that https://musescore.org/de/mitwirken
> 
> Running into a bit of a problem with getting the requested changes done for master (the interaction of cpp and qml is foreign to me), so created a 3.x PR first.

Sounds good. I think it is a good idea

**Comment by Jojo-Schmitz** [comment]
Both PRs,  for 3.x and master,  are ready
