### ISSUE TITLE
[MU4 Issue] Help > MusicXML Links to contributor licenses rather than end-user licenses

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7971]
**Describe the bug**
Links to contributor licenses rather than end-user licenses

**To Reproduce**
1. Go to 'Help' (from the upper menu)
2. Click on 'MusicXML'
3. Check contributor licenses links

**Expected behavior**
Should be links to contributor licenses

**Screenshots**

**Desktop (please complete the following information):**
MacOS
Windows 10

**Additional context**

**Comment by Jojo-Schmitz** [comment]
You want the lonks to change to https://www.w3.org/community/about/process/cla/ and ttps://www.w3.org/community/about/process/cla-deed/ ?

**Comment by vshalkevich** [comment]
Maybe it would be better to have direct links but not redirections

**Comment by vshalkevich** [comment]
@Jojo-Schmitz Thanks for providing links

**Comment by Jojo-Schmitz** [comment]
See #7978

**Comment by Jojo-Schmitz** [comment]
Hmm, actually the URLs I mentioned are still contributor licenses, not end user licenses.

Maybe https://www.w3.org/community/music-notation/ or some link on that page is more what you were thinking of?
I think that "About MusicXML" and the links to the licenses stems from a time before it got handed over to W3C.

**Comment by Jojo-Schmitz** [comment]
See also https://github.com/w3c/musicxml/issues/114

Maybe we'd want https://www.w3.org/community/about/process/final/ and https://www.w3.org/community/about/process/fsa-deed/ ?

**Comment by shoogle** [comment]
@Jojo-Schmitz, I agree, those appear to be the URLs we need. There's the [actual license](https://www.w3.org/community/about/process/final/) and a [human-readable summary](https://www.w3.org/community/about/process/fsa-deed/).

**Comment by Jojo-Schmitz** [comment]
PRs ammended accordingly

**Comment by Jojo-Schmitz** [comment]
Actually we need to change the text too, not just the link, done that now
