### ISSUE TITLE
[MU4 Issue] Adding new staves works in the score but they don't appear in the panel

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7974]
**Describe the bug**
Adding new staves works in the score, but they don't appear in the panel

**To Reproduce**
1. Create a score
2. Add new staves to the score
3. Open instruments panel
4. Try to find added staves

**Expected behavior**
New staves added should be visible in the Instruments panel

**Desktop (please complete the following information):**
MacOS

**Comment by njvdberg** [comment]
Same for deleting staves. After deleting an instrument,  the instrument is gone in the score but still visible in the instruments panel.

**Comment by wizofaus** [comment]
Have been looking at this area - might be able to at least partially fix as part of what I'm working on (though there are some refresh issues with the instrument panel I think I'll have to leave to someone else with more Qt wisdom)

**Comment by njvdberg** [comment]
@wizofaus This is also part of a rewrite of part/excerpts I'm working on. See also the discussion on [discord](https://discord.com/channels/818804595450445834/818848561047273544/851484720331358218)

**Comment by wizofaus** [comment]
Ah ok, well if that's being rewritten I'll leave it alone.

**Comment by njvdberg** [comment]
I guess there is still a lot to fix, so keep up the good work :+1:

**Comment by vshalkevich** [comment]
Fixed for now
