### ISSUE TITLE
[MU4 Issue] Pressing the Tab button should not automatically move you through hidden panels

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7986]
**Describe the bug**
Pressing the Tab button should not automatically move you through hidden panels

**To Reproduce**
1. Create a score
2. Add notes to the score
3. Add text to the score
4. Select text
5. Press "tab" button from your keyboard

**Expected behavior**
Pressing the Tab button should not automatically move you through hidden panels. However, a user should be able to access the actual panel tabs and change to a different panel by pressing **Spacebar** or **Enter**

**Comment by Tantacrul** [comment]
@vshalkevich - you should probably assign @igorkorsukov to these bugs since they relate to the work he is doing.
