### ISSUE TITLE
[MU4 Issue] No keyboard navigation in list

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8029]
**Describe the bug**
No keyboard navigation in list

**To Reproduce**
1. Create a score
2. Click on Options button (Wrench icon)
3. Press Up, down, left, right arrow buttons from your keyboard

**Expected behavior**

Up, down, left, right arrows should work in a Customise toolbar dialog

**Desktop (please complete the following information):**
MacOS
Windows 10

**Comment by RomanPudashkin** [comment]
https://github.com/musescore/MuseScore/issues/8378
