### ISSUE TITLE
[MU4 Issue] Rename "Delete Score" to "Delete" in Parts dialog

### ISSUE THREAD

**Issue by iwoithe** [musescore/MuseScore#8032]
**Describe the bug**
The "Delete Score" confused me until I clicked on it and deleted the part.

**To Reproduce**
1. Open a score (with parts)
2. Click on Parts to open the Parts dialog
3. Click on the three dots to bring up the drop down menu

**Expected behavior**
I expected to see the text "Delete" based on what it did.

**Screenshots**

![rename_delete_score_to_delete_part](https://user-images.githubusercontent.com/73422868/116665153-88516d80-a9d8-11eb-976c-227a561b4e0f.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by RomanPudashkin** [comment]
@Tantacrul please, check this issue

**Comment by Tantacrul** [comment]
Yes. This makes sense. Oversight of mine

**Comment by iwoithe** [comment]
Now that I think about it, having "part" at the end looks really weird to me as both "Duplicate" and "Rename" don't have a suffix.

**Comment by Jojo-Schmitz** [comment]
I agree, either append " part" to the other 2, or remove it here. I'd vote for the latter, as from context it is clear that this is about part.

**Comment by Tantacrul** [comment]
Agreed

**Comment by vshalkevich** [comment]
We discussed and decided that "Delete" is good enough title

**Comment by JRYamasaki** [comment]
Sounds good, string has been changed to just "Delete"

**Comment by Jojo-Schmitz** [comment]
Now the question is whether we want "Delete" or "Remove". For measures we use the former to empty them, the latter to really get rid of them.
