### ISSUE TITLE
[MU4 Issue] Wrong key for transposing instruments when adding to the score later

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#8044]
**Describe the bug**
When adding transposing instruments at an existing score the newly added instruments don't show the correct key.

**To Reproduce**
1. Create a new score with one Clarinet
2. Finish the score

The score look like:
![Screenshot_20210504_144112](https://user-images.githubusercontent.com/48352523/117004800-c7d4ce00-ace6-11eb-9718-a4551b464633.png)
Since score is in C major, the Clarinet will show 2 sharps (which is correct).

3. Open the `Instruments` form by pressing `I`.
4. Add a new Clarinet and close the form.

The score will now looks like:
![Screenshot_20210504_144331](https://user-images.githubusercontent.com/48352523/117005063-1a15ef00-ace7-11eb-9882-4a7b025cbb25.png)
The new Clarinet is missing the 2 sharps.

**Expected behavior**
The score should looks like
![Screenshot_20210504_144457](https://user-images.githubusercontent.com/48352523/117005244-4d587e00-ace7-11eb-9afa-a419e886158e.png)
with both Clarinets the same key.

**Desktop (please complete the following information):**
 - OS: Linux (openSUSE Tumbleweed)

**Additional context**
Observe in MuseScoreNightly-202105030415-master-58e2cbd-x86_64.AppImage

**Comment by njvdberg** [comment]
This should be part of [MU4 - INSTRUMENTS_PANEL](https://github.com/musescore/MuseScore/projects/8).

**Comment by Tantacrul** [comment]
This has been bugging me for ages.

**Comment by njvdberg** [comment]
Will be solved with PR #8149.
