### ISSUE TITLE
[MU4 Issue] Properties (Inspector) has no scroll bar

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8057]
Describe the bug
Properties (Inspector) has no scroll bar. Can`t see all elements

To Reproduce

1) Create a score with text
2) Select text
3) Shrink MU4 window to minimum size
4) Open Properties (Inspector) tab from the Instruments Panel
5) Try to scroll Properties (Inspector) tab

Expected behavior
Properties (Inspector) should has scroll bar when there is no much space to display all items

Screenshots

https://user-images.githubusercontent.com/71372310/117376195-4b561100-aed9-11eb-839a-04bdd4a2929a.mp4

Desktop (please complete the following information):
Windows 10
Linux

**Comment by Mystic-Slice** [comment]
I am working on it.
