### ISSUE TITLE
[MU4 Issue] Properties (Inspector) does not display button for vertical alignment

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8058]
**Describe the bug**
Properties (Inspector) does not display button for vertical alignment

**To Reproduce**
1. Create a score with text
2. Select text
3. Shrink MU4 window to minimum size
4. Open Properties (Inspector) tab from the Instruments Panel
5. Use "tab" button from the keyboard to switch between buttons from Properties > Text area 
6. Using "tab" button from the keyboard you may find absent button on Properties > Text area (absent button is for vertical alignment)

**Expected behavior**
vertical alignment button present in  Properties > Text area

**Screenshots**

https://user-images.githubusercontent.com/71372310/117377061-121ea080-aedb-11eb-8b2e-a0ebe6169fcf.mp4

Desktop (please complete the following information):
Windows 10
Linux

**Comment by Mystic-Slice** [comment]
![image](https://user-images.githubusercontent.com/73862377/119212496-6c705180-bad6-11eb-955d-3319ba594eb3.png)
Is this layout fine?

If the buttons have to be at the same level, we could increase the min-width of the panel

**Comment by cbjeukendrup** [comment]
Fixed in https://github.com/musescore/MuseScore/commit/2525a9757c0a752ee52411a115620f61a24c0c27 (by increasing minimum width)
