### ISSUE TITLE
[MU4 Issue] Pop-up options seems blocked from Note Input Bar

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8061]
**Describe the bug**
Can`t select Pop-up options from Note Input Bar

**To Reproduce**
1. Create a score
2. Add a note
3. Select note
2. Click on any option icon from Note Input bar (for example duplets icon)
3. Try to add duplet, triplet, etc. from pop-up menu

**Expected behavior**
Duplet, triplet, etc. can be added.
Pop-up from Note Input Bar should work

**Screenshots**
![image](https://user-images.githubusercontent.com/71372310/117417417-fe972800-af22-11eb-8407-cbc4cd37a1cf.png)

**Desktop (please complete the following information):**
Linux 
Windows 10

**Additional context**

**Comment by cbjeukendrup** [comment]
I don't think this is a problem of StyledMenu or PopupView, but rather one of the UiActions. 

When you click in the toolbar, the focus moves to the toolbar, so the notation view is unfocused, and the tuplet items only get enabled when the notation view is focused. 
<img width="484" alt="Schermafbeelding 2021-05-07 om 12 18 15" src="https://user-images.githubusercontent.com/48658420/117435588-4f604e00-af2e-11eb-90c1-63ea803f3385.png">
Probably we should just change the context of these actions.
