### ISSUE TITLE
[MU4 Issue] Can't move staff to instrument that does not have any staves

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#8076]
**Describe the bug**
In the Instruments Panel, it's not possible to move a staff to an instrument that does not have any staves. 

**To Reproduce**
1. Create/open a score with (at least) two instruments, both containing one staff.
2. Drag the staff from instrument A to instrument B. 
3. Try to drag the staff back to instrument A (which does not contain any staves any more).
The staff jumps back to instrument B.

**Expected behavior**
The staff should jump to instrument A when instrument A is expanded and hovered, whether it has any other staves or not. 

**Workaround**
Press the "Add Staff" button in Instrument A, to add a temporary staff. Then drag the staff you wanted to drag to Instrument A. This should be successful. Then remove the temporary staff. 

**Screenshots**

https://user-images.githubusercontent.com/48658420/117693772-a4b28e80-b1be-11eb-8f40-d106ae711bd9.mov

**Desktop (please complete the following information):**
 - OS: all (reported on macOS)

**Comment by njvdberg** [comment]
I'm wandering what the meaning of this functionality is. Maybe related to the fact that is not clear what I see in the Instruments panel.
1) What is a staff has an instrument change, what will happen. E.g.  Alto Saxophone doubling on the Clarinet and back. When this Alto Saxophone staff is moved, is the doubling also moved?
2) How about cross staff beaming and one of the staves is moved, what is supposed to happen with this cross staff beam?
3) What if a linked staff is moved, what does this mean? 

I'm not sure whether this is a bug or an unwanted feature :wink:

**Comment by Tantacrul** [comment]
We've removed the option to drag staves from one instrument to the next due to various technical bugs. We decided the solution was more fundamental so removed the capability. Closing.
