### ISSUE TITLE
[MU4 Issue] Pencil icon dropdown has two ticks instead of one

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8084]
**Describe the bug**
Pencil icon dropdown always has two ticks
In this dropdown only one item can have a tick

**To Reproduce**
1. Create a score
2. Click on 'Pencil' icon from the Note Input Bar and hold until dropdown appears
3. Click on any item from the dropdown
4.  Click on 'Pencil' icon from the Note Input Bar and hold until dropdown appears again
5. observe what item ticked

**Expected behavior**
In this dropdown only one item should have a tick

**Screenshots**
![Double tick](https://user-images.githubusercontent.com/71372310/117880495-db68d180-b2b0-11eb-862f-d2d4be0df3bb.jpg)

**Desktop (please complete the following information):**
Windows 10

**Additional context**
In some cases dropdown items don’t aligned. Can't reproduce now

**Comment by cbjeukendrup** [comment]
Working on this!
