### ISSUE TITLE
[MU4 Issue] Expanded section on Instruments Panel should scroll down automatically

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8089]
**Describe the bug**
Expanded section on Instruments Panel should scroll down automatically

**To Reproduce**
1. Create a score
2. Open Palettes/Preferences/Instruments tab
3. Try to expand sections from Palettes/Preferences/Instruments tab 

**Expected behavior**
If expanding section can not be displayed fully in a screen, expanded section should scroll down to the bottom to be fully visible after expanding (video of proper behavior attached)

https://user-images.githubusercontent.com/71372310/118044185-03266b00-b37f-11eb-9504-441686fcd3ad.mp4

**Desktop (please complete the following information):**
MacOS
Windows 10

**Comment by HemantAntony** [comment]
I think this issue has been fixed:

https://user-images.githubusercontent.com/88136054/144696713-68a6a895-6bfb-414a-ba4a-80a7c49c3e3b.mp4

**Comment by Tantacrul** [comment]
A 'nice to have' I don't really think we need.
