### ISSUE TITLE
[MU4 Issue] Main window title bar tasks

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8090]
1. Use standard height for Windows toolbars. No padding above
2. Use native OS font for Windows (Segoe UI)
3. Use native icon symbols for Windows (Segoe MDL2) for top right buttons (minimise, maximise & close)
3. Use button styling that matches that of Windows (see Figma document)
3. Erase '&' symbols from Top Menu
4. Menu Mnemonics (alt+F) should work

**Comment by Tantacrul** [comment]
Please get in touch with me if you need any help with finding the right unicodes for the MDL2 icons or if you have any styling questions.
