### ISSUE TITLE
[MU4 Issue] Separator lines should be visible on Note Input Bar

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8091]
**Describe the bug**
1) Separator lines not visible (Mac & Windows) until you add one in the settings menu. 
2) The name 'Separator Line' is missing from the 'Customise Toolbar' dialog

**To Reproduce**
1. Create a score > Observe Note Input Bar for separator lines 
Next bug:
2. Open 'Customise Toolbar' dialog > The name 'Separator Line' is missing

**Expected behavior**
1) Separator lines visible
2) The name 'Separator Line' visible on the 'Customise Toolbar' dialog

**Desktop (please complete the following information):**
MacOS
Windows 10

**Comment by RomanPudashkin** [comment]
isn't actual anymore
