### ISSUE TITLE
[MU4 Issue] [KDAB] Docking Windows Toolbars should not be resizable

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8092]
**Describe the bug**
Docking Windows Toolbars resizable

**To Reproduce**
1. Create a score
2. Dock (drag&drop) any toolbar as separate window
3. Try to resize docked toolbar

**Expected behavior**
Docking Windows Toolbars should not be resizable

**Desktop (please complete the following information):**
Windows 10

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by Tantacrul** [comment]
This issue has been fixed.
