### ISSUE TITLE
[MU4 Issue] [KDAB] top toolbar elements become displaced if app resized

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8093]
**Describe the bug**
When resizing app, top toolbar elements become displaced and lose their position

**To Reproduce**
1. Create a score
2. Make MU4 window size small (not fullscreen mode)
3. Dock (drag&drop) any of top toolbars (for example Note Input Bar) to make it float
4. change MU4 window position

**Expected behavior**
top toolbar elements (Note Input Bar, etc.) should be stick to MU4 window and keep it`s position inside MU4 if MU4 window will change it`s position or resized

Reproduced for MacOS

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/9597
