### ISSUE TITLE
[MU4 Issue] Same shortcut for all items in "Recent Files" menu.

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#8109]
**Describe the bug**
When the `Recent Files` list contains several files, all files have the same shortcut:

**To Reproduce**
1. Start MuseScore
2. Open a few so the recent files list contains some data.
3. Open en Recent Files submenu.

**Expected behavior**
All items should have an unique shortcut, or no shortcut at all.

**Screenshots**

![Screenshot_20210515_122555](https://user-images.githubusercontent.com/48352523/118357178-1735bc80-b579-11eb-89ba-c138fd835ae1.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by JRYamasaki** [comment]
I'll take a look at this, looks like there should be no shortcuts as thats what MuseScore 3 does. There could also be potential problems with key-mappings if we assigned each recent file a key-binding.

**Comment by cbjeukendrup** [comment]
Indeed, opening recent scores should not have shortcuts. 

The situation is, that both the Open Recent menu items and the normal "Open..." item use the same "file-open" action code; the "Open..." action is without an argument, and the recent scores items are _with_ an argument, namely the path to the score to open. 

I am not sure what would be the best solution; maybe there should be an extra action code like "file-open-recent" which is used only in the Open Recent menu and has no shortcut bound to it.
