### ISSUE TITLE
[MU4 Issue] Home screen: Text cursor remains in searchbox after back-tabbing from right side

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#8134]
Pressing spacebar enters a space in the text field instead of selecting an item from the navigation list on the left side of the Home screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/11011881/119102450-eee30d80-ba11-11eb-8bc0-1f6003f8b7b7.png)

**To Reproduce**
1. Go to the Home screen
2. Press the Tab key to navigate to the page list on the left side.
3. Use the Up and Down to navigate the list and highlight the Scores page (or the Add-ons page).
3. Press Spacebar to select the page, then press Tab to move focus to the searchbox.
4. Now press Shift+Tab to move back to the navigation list. Notice the text cursor remains in the searchbox.
5. Use Up and Down to navigate the list, then press Spacebar to select another item.

**Expected behavior**
Only one control should have keyboard focus at a time. If the navigation list has keyboard focus then Spacebar should select items from the navigation list. It should not be possible to type in text fields unless they have keyboard focus.

**Desktop (please complete the following information):**
 - OS: Windows & macOS

**Comment by DmitryArefiev** [comment]
Tested with Narrator/NVDA (Win10), Orca (Linux Mint 20.2) and VoiceOver (Mac11) - PASS
