### ISSUE TITLE
Documentation claims that VS 2017 is still supported for building but it doesn't appear to be

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8144]
The CMakeSettings.json and build.cmake files are clearly configured for VS 2019, yet changing them to work with VS 2017 triggers other errors.
It seems VS 2017 is no longer supported, so I'd assume the documentation needs updating to reflect this?

**Comment by wizofaus** [comment]
I've made some of my own modifications to https://musescore.org/en/handbook/developers-handbook/compilation/compile-instructions-windows-visual-studio based on observations so far, not sure what the review/publish process is?

**Comment by Tantacrul** [comment]
@shoogle - can you review?

**Comment by shoogle** [comment]
@wizofaus, the developer documentation is a wiki so feel free to update/improve it as you see fit (though do ask before making major structural changes).

As a general goal, I think it makes sense to aim to support the current version of Visual Studio and one version prior. Right now that would be VS 2022 and VS 2019, so it's fine to ditch VS 2017.

I'm not sure it's working with VS 2022 yet but if not then we probably won't get around to fixing that until after MU4 is released.
