### ISSUE TITLE
[MU4 Issue] Close command, and many shortcut keys don't work

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8159]
**Describe the bug**
Key functionality not working:
Close command (after opening score)
Esc key (to deselect etc., and in general to close dialogs etc.)
Cursor keys (including, e.g., Shift+Ctrl+up/down, to move notes to other staves for cross-staff beaming)
Del & backspace key 

**To Reproduce**
1. Build/run MU4 in VS 2019, open a score
2. Click on File|Close
3. Select a note, attempt to use various keys as above
4. Note nothing happens

**Expected behavior**
Functions should work as per MU3

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 
**Additional context**

**Comment by wizofaus** [comment]
Close command issue is duplicate of https://github.com/musescore/MuseScore/issues/7662

**Comment by bkunda** [comment]
FWIW, adding my observations to this one as well:
- Cmd+W now does succeed in closing a score, however no dialog appears to prompt user to save changes
- Esc key still does not close dialogs
- Shortcuts for cross-staff beaming still not working
- Del does remove notes, however backspace does not (and it should, as it does in MS3.6)

**Comment by bkunda** [comment]
Elevated to P1 after consultation with @Tantacrul because cross-staff beamings cannot be entered in MuseScore without this shortcut functionality

**Comment by wizofaus** [comment]
Working on implementing the following commands, none of which are working:

moveUp
moveDown
upChord
downChord
topChord
bottom-chord

**Comment by wizofaus** [comment]
BTW "esc" to close dialogs everywhere might not be trivial to implement, or require changing qml files, and best moved to another issue.  I'm just focussing on shortcut key activated commands for editing/selection navigation within the score.

**Comment by wizofaus** [comment]
Also trying to fix actions with multiple shortcut key sequences like 'delete'. Though interestingly in MU3 "backspace" and "delete" are separate actions - are there cases they do different things editing the score? (vs editing text).

**Comment by Tantacrul** [comment]
Yes. Text editing differences aside, we should make sure backspace is utilised as a method of deleting anything.

**Comment by DmitryArefiev** [comment]
Tested in latest master build (Win10, Mac12, LinuxMint 20.2)


- Close command (after opening score) - FIXED
- Esc key (to deselect etc., and in general to close dialogs etc.) - FIXED
- Cursor keys (including, e.g., Shift+Ctrl+up/down, to move notes to other staves for cross-staff beaming) - FIXED
- Del & backspace key - FIXED

Closing

@wizofaus  Please recheck in latest master. It should be fixed now. Thanks!
