### ISSUE TITLE
[MU4 Issue] The string "Nr." turns into "№" when using Edwin

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#8161]
The string "Nr." in a vertical frame turns into "No" (with the o being underlined and superscripted), when using the Edwin font.
Same happens with staff-and system text and lyrics, even in instrument names, probably more.

**To Reproduce**
1. Take any score, from 3.6 or later, or create one from scatch.
2. In the Title Frame make sure there's the String "Nr.", e.g. in a Subtitle.
3. Make sure it is using the (default) Edwin font (no other font shows this behavoir).
4. See the error, "Nr." turns into "&numero;" (but "No." does not!?).

**Expected behavior**
The string should not get changed and stay "Nr.".

**Screenshots**
This is what it looks like:
![image](https://user-images.githubusercontent.com/1786669/119490278-f2053300-bd5c-11eb-9a30-ec1e60b0cbcc.png)

This is what it should be (or rather stay, like it does for 3.6.2):
![image](https://user-images.githubusercontent.com/1786669/119489793-5c69a380-bd5c-11eb-9ec8-6ffe5eec0df0.png)

**Desktop:**
 - OS: Windows 10

**Additional context**
Same issue is seen with the current 3.x branch. So the culprit got to be one of the commits to that after 3.6.2 got released, and one that also got ported over to master.
Note that in the status bar it still shows "Subtitle: Nr. 330"

**Comment by Jojo-Schmitz** [comment]
See also https://github.com/MuseScoreFonts/Edwin/issues/5

**Comment by maximebochon** [comment]
I expressed a contradictory point of view in the Edwin issue you mentioned: https://github.com/MuseScoreFonts/Edwin/issues/5

**Comment by Jojo-Schmitz** [comment]
I'm not against that glyph, but against the automatic conversion of "Nr." into that glyph, as this is plain wrong. Doing the same for "No." might be OK though, not sure.

**Comment by Jojo-Schmitz** [comment]
Many years ago there had been a long discussion about converting "(C)" into "&copy;", the final decision was to not change stuff under the users' feet, out of the users' control.

**Comment by maximebochon** [comment]
I understand. For sure the user should have the choice. It would be sad that a user get rid of Edwin just because of that, so giving her the choice would definitely be a good thing.

**Comment by maximebochon** [comment]
Actually, I don't reproduce that phenomenon on my MuseScore version and OS:

- Windows 10 (10.0), Arch.: x86_64,
- MuseScore version (32-bit): 3.6.2.548021803,
- revision: github-musescore-musescore-3224f34

**Comment by Jojo-Schmitz** [comment]
Indeed, the issue is only with the development version from the 3.x and the master branch. I stated that in the initial post...

**Comment by Jojo-Schmitz** [comment]
Why using a 32bit version of MuseScore on a 64bit version of Windows?

**Comment by maximebochon** [comment]
I don't have admin rights on the Windows 10 of that computer so I run a portable version of MuseScore. Is there a 64-bit portable version? Or a way to install it without having admin rights?

**Comment by Jojo-Schmitz** [comment]
Ah, I see, no, indeed the PortableApp is 32-bit

**Comment by maximebochon** [comment]
I don't reproduce here neither:

- OS: Ubuntu 18.04.5 LTS, Arch.: x86_64,
- MuseScore version (64-bit): 3.6.2.548021370,
- revision: github-musescore-musescore-3224f34

**Comment by Jojo-Schmitz** [comment]
Again: 3.6.2 is not affected by this issue, only later 3.x and master development versions

**Comment by njvdberg** [comment]
> Many years ago there had been a long discussion about converting "(C)" into "©", the final decision was to not change stuff under the users' feet, out of the users' control. Not even only for the copyright field!

There are still some of these change. Or at least one. The `&` is sometimes converted to `&amp;`. E.g. when changing the name of an instrument from `Flute` into `Flute 1&2`. When reopening the from 2 of the 3 `&`'s are replaced by a `&amp;`. Only `Part name` stays unchanged. I suppose, based on the discussion for years ago this should stay `&`?

**Comment by Jojo-Schmitz** [comment]
Well, that's a different issue, a case whetere we forgort to 'escape' it properly

**Comment by Jojo-Schmitz** [comment]
Actually the `&` shows correcly in score, but gets changes in the Instruments prioperties dialog to that `&amp;`, a bug that got fixed a while ago

**Comment by maximebochon** [comment]
@njvdberg To make it clear, the  "& vs. &amp;" phenomenon is related to XML handling whereas the "Nr. vs. №" issue comes from an advanced font feature called ligatures.

**Comment by njvdberg** [comment]
@Jojo-Schmitz , @maximebochon So two different issues, forget I said something :smiley:

**Comment by Jojo-Schmitz** [comment]
Did you say something? 
;-)

**Comment by njvdberg** [comment]
Me? No!

**Comment by Jojo-Schmitz** [comment]
So this issue can get closed now, with the release or Edwin 0.53, right?

**Comment by Jojo-Schmitz** [comment]
Oops, I can close ths myself...
