### ISSUE TITLE
[MU4 Issue] [KDAB] Dock widgets displayed if dock Instrument Panel tabs

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8163]
**Describe the bug**
Dock widgets displayed if dock Instrument Panel tabs

**To Reproduce**
1. Create a score
2. Drag&drop any of Instrument panels (for example Palettes) > you will see dock widgets

**Expected behavior**
Dock widgets should be changed to a blue highlights in the places where user can put tab

**Screenshots**
![2021-05-25 17_03_45-MuseScore4Development](https://user-images.githubusercontent.com/71372310/119513129-9ea2dd00-bd7c-11eb-8c72-114aa1431721.jpg)

**Desktop (please complete the following information):**
Windows 10

**Comment by RomanPudashkin** [comment]
fixed in
https://github.com/musescore/MuseScore/pull/9649
