### ISSUE TITLE
[MU4 Issue] [KDAB] Double click on docked Instrument Panel returns it to Instrument Panel default place

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8164]
**Describe the bug**
Double-click on docked Instrument Panel returns it to Instrument Panel default place

**To Reproduce**
1. Create a score
2. Drag&drop any of Instrument panels (for example Palettes)
3. Double-click on docked Instrument panel tab (video attached)

**Expected behavior**
Nothing happens with docked panel when user double-click on it

**Screenshots**

https://user-images.githubusercontent.com/71372310/119505379-9004f780-bd75-11eb-97cc-1059dd237904.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by Tantacrul** [comment]
This is not desirable.

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
