### ISSUE TITLE
[MU4 Issue] Crash if enable voice to a newly created Part from Parts dialog

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8171]
**Describe the bug**
Crash if enable voice to a newly created Part from Parts dialog

**To Reproduce**
1. Create a score
2. Click on "Parts" button 
3. Click on "Create new Part" button
4. Click anywhere to save created Part
5. Click on triangle icon in a string with newly created Part > dropdown with voices should appear
6. Click on any checkbox near voice to enable Part voice

**Expected behavior**
If it is impossible to enable Part voices checkboxes should be blocked
No crash should appear after clicking on Part voice checkbox

**Screenshots**
https://user-images.githubusercontent.com/71372310/119555922-1128b280-bda7-11eb-8072-87ad9dfe107b.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by njvdberg** [comment]
When creating a new part (actually an `Excerpt`) it isn't possible to make any voice visible/invisible this this `Excerpt` hasn't any `Part` yet. `Parts` (now called `Instruments`) are assigned to this new `Excerpt` later.
By the way, if it the intention of mimic the MU3 behavior of Voice-to-Part, voices should be mapped, not made visible/invisible.

**Comment by RomanPudashkin** [comment]
No longer actual, see https://github.com/musescore/MuseScore/pull/8751
