### ISSUE TITLE
[MU4 Issue] Replaced Instrument in Parts dialog displayed as it was before replace

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8172]
**Describe the bug**
If user replace instrument via Instruments panel and go to Parts dialog he will see instruments as they were before replacing. 

**To Reproduce**
1. Create a score
2. Open Instruments tab in Instruments Panel
3. Click on option button (gear icon) from the Instruments panel near Instrument 
4. Click "Replace instrument" button
5. Proceed untill replaced instrument displays in the Instruments panel
6. Open Parts dialog

**Expected behavior**
Replaced instruments should be displayed in Parts dialog

**Screenshots**

https://user-images.githubusercontent.com/71372310/119557334-babc7380-bda8-11eb-8102-11a43dc9334d.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by HemantAntony** [comment]
The name of the instrument doesn't change even in the instruments panel now:

https://user-images.githubusercontent.com/88136054/144700534-06cc639e-ea0b-42ee-b29b-a48405175d52.mp4

I have created another issue including the new bug:[#9972](https://github.com/musescore/MuseScore/issues/9972)
