### ISSUE TITLE
[MU4 Issue] Multiple New Score Wizard dialogs opened at the same time

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8179]
**Describe the bug**
It is possible to open multiple New Score Wizard dialogs at the same time
User may open New Score Wizard window several times

**To Reproduce**
1. Click on "Create new score"
2. Click on "Create new score" again _(video attached)_

**Expected behavior**
Only one New Score Wizard dialog can be opened

**Screenshots**
https://user-images.githubusercontent.com/71372310/119670260-6ca77e80-be41-11eb-8631-d32365271316.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by cbjeukendrup** [comment]
So most probably the dialogs are not "modal" (I believe it's not only the New Score dialog that has this problem).
Also, it seems they have no title bar on Windows. On macOS no such problem.

**Comment by vshalkevich** [comment]
Checked. Fixed
