### ISSUE TITLE
[MU4 Issue] Toggling concert pitch in Style dialog messes up key signatures

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#8184]
**Describe the bug**
Toggling concert pitch in Style dialog messes up key signatures. 

**To Reproduce**
1. Open the Format > Style dialog. 
2. Toggle "Display in concert pitch".
3. Press OK.

The key signatures on the score are totally wrong; when sharps or flats should appear, they sometimes disappear instead, or the other way round, or too many appear or disappear. 

**Expected behavior**
The result of the steps above should be exactly the same as toggling the concert pitch button in the status bar (which works fine). 

**Screenshots**

https://user-images.githubusercontent.com/48658420/119822368-dda76e80-bef3-11eb-83af-17e445eb41a5.mov

**Desktop (please complete the following information):**
 - OS: reported on macOS, probably other OSs too

**Comment by njvdberg** [comment]
Solved with PR #8186.
Problem is the style editor fires the command to change to pitch twice so the transposing instruments are transposed twice.
