### ISSUE TITLE
[MU4 Issue] Search field don`t lose focus afrter clicking on an empty space

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8193]
**Describe the bug**
Search field don`t lose focus afrter clicking on an empty space

**To Reproduce**
1. Start MU 4
2. Open Home tab
3. Click in the search field 
4. Click on an empty space on the MU4

**Expected behavior**
Focus should be dropped after clicking on an empty space

**Screenshots**

https://user-images.githubusercontent.com/71372310/119988490-d86b2200-bfce-11eb-969e-48252e6726ba.mp4

https://user-images.githubusercontent.com/71372310/119988496-d99c4f00-bfce-11eb-9f33-3e5dc4097f9e.mp4

**Desktop (please complete the following information):**
 Windows 10
 
 **Additional info**
Reproducible for Search fields on Score and Add-ons tabs

**Comment by RomanPudashkin** [comment]
I'm working on it
