### ISSUE TITLE
[MU4 Issue] [Docking] Dock widget jumps when starting to move it 

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#8197]
**Describe the bug**
Dock widget jumps when starting to move it. 

**To Reproduce**
1. Undock a dock widget
2. Start dragging it
3. The dock widget jumps before it starts following the mouse.

**Expected behavior**
The dock widget should only follow the mouse, not jump.

**Screenshots**

https://user-images.githubusercontent.com/48658420/120067491-3bff5900-c07c-11eb-9d38-65cd9c38daec.mov

**Desktop (please complete the following information):**
 - OS: all (exact same situation)

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
