### ISSUE TITLE
[MU4 Issue] "time signatures" button on inspector doesn't work - can't edit time signatures?

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8205]
**Describe the bug**
The "Change time signature" button that appears when you click the "Time signatures" button under Notation for the properties of a time signature doesn't work, meaning you can't actually edit the time signature properties at all.
(previously: the text for "Show courtesy time signatures..." doesn't quite fit - but this seems to be gone now)
Also this same problem applies to the inspector for notes (the Note Settings button does nothing).

**To Reproduce**
1. Select a time signature
2. Click "Properties" on the LHS
3. Under Notation click "Time Signatures"
4. Nothing happens

**Expected behavior**
Time Signature properties dialog as per MU3 should open up.

**Screenshots**

![image](https://user-images.githubusercontent.com/5364225/120122986-c6b49500-c1ef-11eb-93f7-aff6bc343f03.png)

Also note the "previous sy" text issue.

**Desktop (please complete the following information):**
 Windows 10

**Additional context**
Latest MU4 build from master, built inside Visual Studio 2019

**Comment by wizofaus** [comment]
This appears to be because of
```
void TimeSignatureSettingsModel::showTimeSignatureProperties()
{
    NOT_IMPLEMENTED;
}
```
Though I had to add an onClicked handler to TimeSignatureSettings.qml to even get that far

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/9075
