### ISSUE TITLE
[MU4 Issue] musicxml test testNoteAttributes2 is failing

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8215]
testNoteAttributes2 is failing with a difference between the output xml and the reference xml:
```
           <technical>
-            <fingering font-style="italic">2</fingering>
+            <fingering>2</fingering>
             </technical>
```
But strangely this isn't causing any git workflows to fail, so maybe it only happens in a MSVC 2019 build for some reason?

**Comment by Tantacrul** [comment]
@wizofaus - is this relevant still or should it be closed?

**Comment by wizofaus** [comment]
I'm fine with closing this given it's not causing any issues.
