### ISSUE TITLE
[MU4 Task] Implement memory manager

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#8217]
**Task description**
Implement memory manager which should take care about the life-time of dynamically created elements in libmscore. Manager is going to solve 2 major goals:
- Reduce the amount of memory leaks (at the moment created elements are not clearing from memory, so that even if you have N displayed notes in your score, there will be about N*2 elements in memory)
- Provide an ability to execute additional logic during the creation/deletion of an element, like registration in "Accessibility tree"

**Comment by Tantacrul** [comment]
@vpereverzev - is this issue still relevant? Should I assign it a P number and target it at Beta?

**Comment by igorkorsukov** [comment]
@Tantacrul This task is done
