### ISSUE TITLE
[MU4 Issue] System Actions Menu no longer available

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#8221]
**Describe the bug**
When left clicking on the title bar of window a actions menu should appear with actions to move a window to another workspace/activity or other actions.
This is no longer working for MU4.

**To Reproduce**
1. Open MuseScore
2. Left click on the title bar (or whatever mouse action is defined for this)

**Expected behavior**
A action menu should appear but it doesn't.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux openSUSE Tumbleweed with KDE Plasma 5.21.5

**Additional context**
As a matter of fact, none of the normal title bar actions are working. See also #8220.

**Comment by cbjeukendrup** [comment]
In fact, this is also the case on Windows. Normally, right-clicking the title bar gives a menu for Close, Maximize, Minimize, etc., but in MuseScore it doesn't.

**Comment by Eism** [comment]
coming soon for windows

**Comment by DmitryArefiev** [comment]
Tested on my LinuxMint 20.2 - FIXED in #9611

![Screenshot_2021-11-02_17-20-03](https://user-images.githubusercontent.com/90187801/139876638-2f1d25e3-211e-4999-9d07-eafb6147200e.png)

Closing
