### ISSUE TITLE
[MU4 Issue] No file path visible in recent score list

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#8241]
**Describe the bug**
When trying to open a score from `File->Open recent` (or form the `Score` page) the name of the **score** is visible but there is no way to know which file it is.

**To Reproduce**
1. Open a score
2. Save it using `Save as...`
3. Close the score
4. Go the the `Score` page (or use `File -> Open recent`). Now two identical entries are shown although it are two different files (and most likely different scores).

**Expected behavior**
At least a hint which file is behind an entry in the recent files list.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (but I guess this is the same for other platforms).

**Additional context**
It is common practice to have to make a copy of a document to try something and ensure the the original document is not destroyed. In that case `File -> Save as` is used to make that copy. But in the recent files list only the `workTitle` of the score properties is shown which hasn't changed. When loading a score with a certain name, there is no way to tell which **file** is actually loaded. The only way to find out is load the file and check the score properties. If it is the wrong file, try another.

**Comment by nanu1605** [comment]
@njvdberg @RomanPudashkin  Hi, I am pretty new to open source but would love to work on this issue. Could you please help me with the issue more.

**Comment by cbjeukendrup** [comment]
@nanu1605 The relevant code is at the top of the method `AppMenuModel::setupConnections()`; at least, looking at that method will guide you to the source of the recent files list.
<details><summary>Hint</summary>
... which will be in `RecentProjectsProvider::recentProjectList()`.
</details>

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10473
