### ISSUE TITLE
[MU4 Issue] Scaling "Whole page" works once only

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#8242]
**Describe the bug**
When setting page scaling to `Whole page` the actual scaling is nicely adapted to the size of applications. However, when resizing the main window, the score page is not resized but stays at the previous scaling.

**To Reproduce**
1. Open a score
2. Set page scaling to `Whole page`. Page scaling is adapted to nicely fit into the area (e.g. scaling is now 82%).
3. Resize the application window and observe the scaling percentage, this is **not** changing, despite the larger/smaller window. Not the page doesn't fit into the area anymore.

**Expected behavior**
After resizing the main window the scaling should be adapted to the new window size.

**Screenshots**
Page scaling set to `Whole page`, note the scaling is set to `82%`
![Screenshot_20210603_194751](https://user-images.githubusercontent.com/48352523/120689612-977a7e00-c4a4-11eb-8c0e-f6e54248b632.png)
Now the window is made much smaller:
![Screenshot_20210603_194954](https://user-images.githubusercontent.com/48352523/120689884-e0cacd80-c4a4-11eb-8af1-cb9a1e1e0d66.png)
The actual scaling isn't changed (still `82%`) but the page is far too large for the available space.
Also, the page scaling, although `82%`, is still `Whole page`.
To fit the score in the available space I have to select `Whole page` again (even when it was still active).
![Screenshot_20210603_195221](https://user-images.githubusercontent.com/48352523/120690213-37380c00-c4a5-11eb-8a7b-6d09367cd990.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
none

**Comment by Tantacrul** [comment]
Confirmed, this is still happening. Compare to MS3 to see expected behaviour.

**Comment by DmitryArefiev** [comment]
Hi @cbjeukendrup , checked the builds from #12742.
 
Auto scaling works after I opened the score, changed to whole page and resize the window, but **it doesn't work** if to drag the score before changing view to whole page/two pages and then resize window. That **works fine in MS3**

https://user-images.githubusercontent.com/90187801/187151493-d4377a42-e154-4fb7-8f56-bc5d8dbe2c55.mp4

**Comment by cbjeukendrup** [comment]
Hm... I'm taking a look!

**Comment by cbjeukendrup** [comment]
@DmitryArefiev I pushed some changes and it should be better now! New test builds being created...

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev I pushed some changes and it should be better now! New test builds being created...

@cbjeukendrup Yeah, it's better now. Thanks!
