### ISSUE TITLE
[MU4 Issue] Bottom bar too tall

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#8248]
**Describe the bug**
The bottom bar shows it is too tall.

**To Reproduce**
1. Create Score
2. Locate at bottom of the score

**Expected behavior**
Should be 36 pixels tall.

**Screenshots**
![image](https://user-images.githubusercontent.com/71656189/120835949-e8e64400-c55c-11eb-8c66-5ee8e99659d9.png)
Dark version is the build, Light version is the Figma version.

**Desktop (please complete the following information):**
 - MacOS
 - Windows

**Additional context**
Find information in 'BOTTOM INFO BAR' page in Figma

**Comment by RomanPudashkin** [comment]
I have already fixed this bug in my local branch :)

**Comment by jessjwilliamson** [comment]
> I have already fixed this bug in my local branch :)

Thanks!

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/8293
