### ISSUE TITLE
[MU4 Issue] Wrong shortcuts in MacOS Tooltips

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#8253]
**Describe the bug**
MacOS tooltips are showing 'Ctrl' instead of 'Cmd' - for example, Cmd + Z is for undo in Mac, and Ctrl + Z for Windows.

**To Reproduce**
1. Open Score
2. Hover over Undo button
3. Locate tooltip text

**Expected behavior**
Replace Ctrl to Cmd

**Screenshots**
![image](https://user-images.githubusercontent.com/71656189/120840065-a5da9f80-c561-11eb-92ff-eca7cbab75da.png)

**Desktop (please complete the following information):**
 - Mac OS

**Comment by cbjeukendrup** [comment]
I would prefer to see the symbols, so for example ⌃⌥⇧⌘W.
(By the way, that is the "official" order of the modifiers: Control Option Shift Command.)

**Comment by cbjeukendrup** [comment]
See also: https://discord.com/channels/818804595450445834/818848561047273544/858653905164697630

**Comment by DmitryArefiev** [comment]
Tested on Mac12 - FIXED
