### ISSUE TITLE
[MU4 Issue] MU4 main doesn't obey normal window rules

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#8286]
**Describe the bug**
The color of the title bar shows which window is active or not. However, the MU4 title bar always has the same color, whether it is active or not. Also active windows create a shadow on the not active windows, giving it a kind of 3D effect. MU4 doesn't obey the systems settings and creates it own shadow.

**To Reproduce**
1. Open MU4
2. Open any other application/window
3. Play with window positions and observe behavior of MU4 compared with other windows. MU4 behaves differently.

**Expected behavior**
MU4 should behave as any other application does with respect with window management.

**Screenshots**
In this example the left upper window (`kate)` is active:
![Screenshot_20210609_090017](https://user-images.githubusercontent.com/48352523/121308278-281be880-c901-11eb-92e0-489877b30d7a.png)
The title bar is dark and we see the right lower corner creates a reasonable shade on the right lower corner (`MuseScore`).

Now exchange the position of both windows:
![Screenshot_20210609_090349](https://user-images.githubusercontent.com/48352523/121308696-9fea1300-c901-11eb-92d3-b7f90d21e225.png)
Now `MuseScore` is the active window but there is no way to tell, the title bar still has the same color as before. Eve worse, the title bar has the same color as the right lower window and there is no way to tell which window is active! 

Please note:
On Linux, the active window is necessarily on top. See this example
![Screenshot_20210609_090658](https://user-images.githubusercontent.com/48352523/121309100-11c25c80-c902-11eb-9016-fe4b47e67956.png)
In this example the right lower window is the active window and has the focus!
This might look strange and unwanted but over the years (at least 2 decades) this model several times showed its strength.

**Desktop (please complete the following information):**
 - OS: Linux (openSUSE) with KDE Plasma

**Additional context**
This issue is most likely related to (#8820)[https://github.com/musescore/MuseScore/issues/8220] and (#8821)[https://github.com/musescore/MuseScore/issues/8221].

**Comment by Eism** [comment]
@Tantacrul what do you think about this?

**Comment by wizofaus** [comment]
I assume this is related to the fact that MuseScore now shows a menu where the title bar would normally be, which I originally thought was pretty odd until I realised Visual Studio does the same thing (at, under Windows).  And indeed Visual Studio's title bar *doesn't* change colour to indicate it's active - though there is at least an app icon in the top left corner that does (and is used to access the window's system menu), but it's a very subtle difference.
The latest version of Chrome on windows actually draws its *tabs* on the title bar, and has no app icon to access the system menu - there's a very slight change in colour between it being active and not however.
In general I'm actually pretty surprised how many recent apps, including those published by big names like Microsoft and Google don't follow the default window behaviour that was established years ago.  I'm not sure what it's supposed to gain other than a few pixels of extra space.

**Comment by Tantacrul** [comment]
It gains a few extra pixels of space - and that's extremely valuable in a scoring app, where space is at a premium. I'd also add that there are plenty of other apps that do this on Windows (Adobe, for example). As wizofaus mentioned, there are plenty of Windows apps that do it too.

Ideally, it would be nice if we could set stylings that are unique to Linux distros. However, since they're all different, I don't know how difficult that would be to achieve, or what an agreed upon standard might look like.

What I think would be fine is the idea that linux arranges the file menu in a traditional way as long as it **doesn't affect the Windows version, which should remain as it is**.

If we absolutely have to choose a one-size solution, then we go with the current option as it exists now.

**Comment by njvdberg** [comment]
I agree gaining a few extra pixels of space is important, however, compared with MU3, MU4 is more spacious. The icons are bigger, there is more space around several items.
In this snapshot, MU4 is a the left, MU3 at the right.
![image](https://user-images.githubusercontent.com/48352523/135054872-cc8d22f3-946d-4bd9-9eb6-bd5647bd5f15.png)
Even with the standard KDE/Plasma window decorations, MU3 takes less space as MU4, even with MU3 having a toolbar of two rows. 

It seems to me gaining some space by using smaller icons and decrease the height of bars so there is enough space for the standard menu bar is much better since it keeps the user experience of the window behavior intact.

This becomes even more important now MU4 no longer shows multiple score in one single window but opens all  scores in their own window. Now it is important to easily and quick switch between windows, which is a part of the underlying window manager. But MU4 now ignores the default (and wanted) behavior of the underlying window manager.

So I strongly urge to restore the original Linux/KDE/Plasma/Gnome/... window decorations.

**Comment by Tantacrul** [comment]
I have noticed the height difference myself. I think we can easily shave a few pixels from MS4, so it is  vertically shorter than MS3. We just haven't gotten around to it yet but we will.

**Comment by njvdberg** [comment]
This also means there is space to restore the default window decorations so the behavior of the MU4 windows is "normal" again?
As a matter of fact,  this current behavior is really very annoying, especially when using multiple windows, e.g. when engraving a score and having PDF of an example besides it. Bringing windows to the foreground is very difficult now.

**Comment by DmitryArefiev** [comment]
Tested on latest master build on LinuxMint 20.2 - FIXED in #9611

@njvdberg Please try on your side (with latest master) to make sure all work as expected on Linux OS. Thanks!

**Comment by njvdberg** [comment]
@DmitryArefiev Sorry for not responding earlier, I was on a holiday few week ago and missed this message afterwards.
However I can conform issue is solved. Thanks.

**Comment by DmitryArefiev** [comment]
@njvdberg That's good news! Thanks!
