### ISSUE TITLE
[MU4 Issue] "Shading" not working for MU4

### ISSUE THREAD

**Issue by njvdberg** [musescore/MuseScore#8287]
**Describe the bug**
Depending on the system settings, a double click on the title bar will "shade" the window. The title bar stays, the rest of the main window becomes invisible. This is not working. Instead, the window is maximized.

**To Reproduce**
1. Define `Double-click` as `Shade` (KDE systems settings, `Window behavior` menu).
2. Open MU4
3. Double click on the title bar
4. Window is maximized
5. Do the same with any other application (e.g. Firefox)
6. Window is "shaded".

**Expected behavior**
A consistent behavior of title bar actions of all windows.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (openSUSE) with KDE Plasma

**Additional context**
none

**Comment by DmitryArefiev** [comment]
Tested on LinuxMint 20.2 - FIXED in #9611

Closing
