### ISSUE TITLE
Mesa bug: Corrupted rendering with mesa-dev in MuseScore 3.6.2

### ISSUE THREAD

**Issue by nokangaroo** [musescore/MuseScore#8303]
I am using Artix (a fork of Arch Linux). The packaged version of mesa (21.1.2) does not work for me (it breaks other packages), and the development version results in corrupted rendering (horizontal lines in the interface, fuzzy playback cursor). I tried registering with the MuseScore issues page to report this, but I cannot register with Palemoon.

I bisected mesa, and here is the result:
[code]
f62724ccacffb2a1508647e9004adf02f92f7833 is the first bad commit
commit f62724ccacffb2a1508647e9004adf02f92f7833
Author: Kenneth Graunke <kenneth@whitecape.org>
Date:   Thu May 20 02:02:51 2021 -0700

    iris: Pick a single mmap mode (WB/WC) at BO allocation time

    Previously, iris_bufmgr had the ability to maintain multiple
    simultaneous memory mappings for a BO, one in WB mode (with CPU caches),
    and another in WC (streaming) mode.  Depending on the flags passed to
    iris_bo_map(), we would select one mode or the other.

    The rules for deciding which to use were:

    - Systems with LLC always use WB mode because it's basically free
    - Non-LLC systems used...
      - WB maps for all BOs where snooping is enabled (which translates to
        when BO_ALLOC_COHERENT is set at allocation time)
      - WB maps for reads unless persistent, coherent, async, or raw.
      - WC maps for everything else.

    This patch simplifies the system by selecting a single mmap mode at
    BO allocation time, and always using that.  Each BO now has at most one
    map at a time, rather than up to two (or three before we deleted GTT
    map support in recent patches).

    In practical terms, this eliminates the capability to use WB maps for
    reads of non-snooped BOs on non-LLC systems.  Such reads would now be
    slow, uncached reads.  However, iris_transfer_map recently began using
    staging blits for such reads - so the GPU copies the data to a snooped
    buffer which will be mapped WB.  So, rather than incurring slow UC
    reads, we really just take the hit of a blit, and retain fast reads.

    The rest of the rules remain the same.

    There are a few reasons for this:

    1. TTM doesn't support mapping an object as both WB and WC.  The
       cacheability is treated as a property of the object, not the map.
       The kernel is moving to use TTM as part of adding discrete local
       memory support.  So it makes sense to centralize on that model.

    2. Mapping the same BO as both WB and WC is impossible to support on
       some CPUs.  It works on x86/x86_64, which was fine for integrated
       GPUs, but it may become an issue for discrete graphics paired with
       other CPUs (should that ever be a thing we need to support).

    3. It's overall much simpler.  We only have one bo->map field, and
       manage to drop a significant amount of boilerplate.

    One issue that arises is the interaction with the BO cache: BOs with
    WB maps and WC maps will be lumped together into the same cache.  This
    means that a cached BO may have the wrong mmap mode.  We check that,
    and if it doesn't match, we unmap it, waiting until iris_bo_map is
    called to restore one with the desired mode.  This may underutilize
    cache mappings slightly on non-LLC systems, but I don't expect it to
    have a large impact.

    Closes: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4747
    Acked-by: Lionel Landwerlin <lionel.g.landwerlin@intel.com>
    Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/10941>

 src/gallium/drivers/iris/iris_bufmgr.c | 190 ++++++++-------------------------
 src/gallium/drivers/iris/iris_bufmgr.h |  13 ++-
 2 files changed, 56 insertions(+), 147 deletions(-)
[/code]
The last good commit is 22bfb5355f2e7f0c365b4e50f9f8a77a601b1ccf

I tried building the dev version to see if the bug is fixed there, but so far without success (it built but would not start). There is a PKGBUILD in the Arch User Repository, but it is very old.

**Comment by RomanPudashkin** [comment]
Please, use musescore.org for reporting bugs related to MuseScore 3

**Comment by Jojo-Schmitz** [comment]
Namely https://musescore.org/en/node/add/project_issue?pid=1236
But only if the problem exists with the Linux AppImage too, else it'd be and issue with the Arch Linux package.
Actually you tracked the ussue down to be with Mesa (whatever that is) so not a MuseScore ussue at all?
