### ISSUE TITLE
[MU4 Issue] Context menus from '+' button are disconnected.

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#8307]
**Describe the bug**
Context menus do not connect to each other and has a gap inbetween menus.

**To Reproduce**
1. Go to the + button on Note input bar.

**Video**
https://www.dropbox.com/s/zb2c205kkpx5yht/Screen%20Recording%202021-06-14%20at%2010.32.31.mov?dl=0

**Desktop (please complete the following information):**
 - Mac OS
 - Windows? (not confirmed)

**Comment by cbjeukendrup** [comment]
Fixed
