### ISSUE TITLE
[MU4 Issue] Can't navigate dialogs with tab key

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8313]
**Describe the bug**
The tab key doesn't work as expected in many of the dialogs in MU4, not allowing you to move the focus between the various controls.

**To Reproduce**
1. Go to Edit|Preferences
2. Hit Tab
3. Active control appears to change on main window rather than preferences dialog.
4. Similarly for 2nd page of "New Score" wizard (1st page seems OK).  

**Expected behavior**
All functionality should be navigable via keyboard.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10, built with MSVC 2019

**Comment by Eism** [comment]
fixed
