### ISSUE TITLE
[MU4 Issue] Crash if click Inspector > Style Settings

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8334]
**Describe the bug**
Crash if click Inspector > Style Settings

**To Reproduce**
1. Create a score
2. Select Inspector tab
3. Click on "Style Settings" button on the Inspector tab

**Expected behavior**
Style Settings dialog opens

**Screenshots**
![InkedInspector - Style Settings - Crash_LI](https://user-images.githubusercontent.com/71372310/122257843-0f9b6780-ced9-11eb-8bb4-aee5442915c0.jpg)

**Desktop (please complete the following information):**
 Windows 10

**Comment by cbjeukendrup** [comment]
This crash should be fixed by the last commit of PR #7993.
