### ISSUE TITLE
[MU4 Issue] Metronome not working

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8360]
**Describe the bug**
Regression: When metronome is turned on no 'click' track can be heard during playback as per MU3.

**To Reproduce**
1. Open/create a score
2. Ensure Metronome is active in the playback toolbar
3. Play
4. No click track can be heard

**Expected behavior**
Click track should play as per MU3

**Screenshots**

**Desktop (please complete the following information):**
Windows 10, built with MSVC 2019

**Additional context**

**Comment by DmitryArefiev** [comment]
Tested latest master build on Win10, Mac12, LinuxMint 20.2 - FIXED

Closing
