### ISSUE TITLE
[MU4 Task] [Accessibility] New Score Wizard

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#8366]
**Task description**

Replicate an existing approach on "new score wizard". (Including all the popups)

![2021-06-21 13_52_50-Screen Reader - Google Таблицы — Mozilla Firefox](https://user-images.githubusercontent.com/71372310/122751096-feb37300-d297-11eb-8284-9b9b7eee1ad4.jpg)

![2021-06-21 13_55_28-Screen Reader - Google Таблицы — Mozilla Firefox](https://user-images.githubusercontent.com/71372310/122751384-5ce05600-d298-11eb-9b09-49971378a534.jpg)

See example in 37eaaec3789f0c9ec0b95d817a0634fc04c4a077

**Comment by DmitryArefiev** [comment]
Checked #8366 with Narrator on Win10 and Orca on Linux Mint 20.2 - PASS

Found #9217, #9216 during testing
