### ISSUE TITLE
Three dot '...' button is too big in certain places in the UI

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#8368]
**'...' Menu buttons are too big on the Inspector and Panel Tabs**
This menu button appears on options in the Inspector or on panel tabs and is currently set to 32x32px. This should be changed to 20x20px to maximise the amount of space available for text:

BEFORE
![image](https://user-images.githubusercontent.com/21022311/122743380-d9fed180-d27e-11eb-83a5-334f19e0e116.png)

AFTER
![image](https://user-images.githubusercontent.com/21022311/122743221-b6d42200-d27e-11eb-83d3-e29390c84145.png)

AFTER (Panel Tabs)
![image](https://user-images.githubusercontent.com/21022311/122742767-34e3f900-d27e-11eb-85c4-564d0caf5e34.png)

**Comment by cbjeukendrup** [comment]
Does that also apply for these ones in the Palettes? 
<img width="262" alt="Schermafbeelding 2021-06-21 om 11 59 12" src="https://user-images.githubusercontent.com/48658420/122744406-3d413180-d288-11eb-967c-ac1f9c19cc8e.png">

**Comment by Tantacrul** [comment]
> Does that also apply for these ones in the Palettes?

Yes, it probably should. Good catch!

**Comment by Trainzack** [comment]
I searched the codebase, it looks like this button is also used in the parts window and the notation status bar. Should this be a blanket change across all of these buttons (by changing menubutton)? Or should this be a case-by-case change?

For reference, here's what the button looks like in the parts window and notation status bar as it is now:

![PartDelegate1a](https://user-images.githubusercontent.com/19575360/128103807-d61faacb-a1ad-4054-acc4-714b121c010a.png)
![NotationStatusBar1](https://user-images.githubusercontent.com/19575360/128103681-05155e67-fd70-4777-8514-3cb3408fc5e4.png)

And here is what it looks like after reducing the size to 20x20px and applying vertical centering.


![PartDelegate2b](https://user-images.githubusercontent.com/19575360/128103814-c893a3a5-4d61-4539-b026-a7dff60da44d.png)
![NotationStatusBar2](https://user-images.githubusercontent.com/19575360/128103692-2c099c60-7040-4da8-8b3d-5c3fac1839d3.png)

**Comment by Tantacrul** [comment]
> I searched the codebase, it looks like this button is also used in the parts window and the notation status bar. Should this be a blanket change across all of these buttons (by changing menubutton)? Or should this be a case-by-case change?

I would avoid changing the sizes in though two examples because there is ample space for them already. With the tabs in Palettes / Instruments / Properties, etc, the size of the buttons were causing the names to be truncated and needed to be smaller.

**Comment by Tantacrul** [comment]
@Trainzack I do like the vertical centering though!
