### ISSUE TITLE
[MU4 Task] [Accessibility] Preferences dialog

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#8369]
**Task description**
Replicate an existing approach on the preferences dialog

![2021-06-21 13_50_20-Screen Reader - Google Таблицы — Mozilla Firefox](https://user-images.githubusercontent.com/71372310/122750795-a54b4400-d297-11eb-91b5-be3fd8b67c00.jpg)

See example in 37eaaec3789f0c9ec0b95d817a0634fc04c4a077

**Comment by Eism** [comment]
implemented in #9147
