### ISSUE TITLE
[MU4 Task] [Accessibility] Top-menu

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#8370]
**Task description**
Replicate an existing approach on top-menu popups

![2021-06-21 13_49_36-Screen Reader - Google Таблицы — Mozilla Firefox](https://user-images.githubusercontent.com/71372310/122750725-8c429300-d297-11eb-9a4a-9684d10b18ae.jpg)

See example in 37eaaec3789f0c9ec0b95d817a0634fc04c4a077

**Comment by cbjeukendrup** [comment]
I think we should just create a generalized approach for StyledMenu. (see also #8373)

**Comment by vpereverzev** [comment]
Yep, you're right from the implementation POV, from the management/testing point of view it's much more convenient to separate such things
