### ISSUE TITLE
[MU4 Task] [Accessibility] Parts dialog

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#8374]
**Task description**
Replicate an existing approach on the "parts" dialog

![2021-06-21 13_35_35-Screen Reader - Google Таблицы — Mozilla Firefox](https://user-images.githubusercontent.com/71372310/122749081-95326500-d295-11eb-8373-c86b10d1f2f6.jpg)

See example in 37eaaec3789f0c9ec0b95d817a0634fc04c4a077

**Comment by wizofaus** [comment]
I'm not quite sure what the issue being described is here @vpereverzev but the Parts dialog in its current form doesn't allow assigning instruments at all, or controlling which voices are shown.  "Create new part" seems to do nothing other than create an "empty" part with no instruments assigned to it, which doesn't seem to be useful.  I'm guessing this is still work in progress?
