### ISSUE TITLE
[MU4 Issue] App crashes if closed with opened score

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8400]
**Describe the bug**
App crashes if closed with opened score (seen via dev console)
Text in console:
(Score::~Score(){ core::validScores.erase(this); → double free or corruption (fasttop))

**To Reproduce**
1. Launch MU4
2. Create or open score
3. Close MU4

**Expected behavior**
No crashes

**Desktop (please complete the following information):**
Windows, Linux

**Comment by wizofaus** [comment]
Is there some other step you need to take to reproduce? Definitely doesn't happen for me...
