### ISSUE TITLE
[MU4 Task] Home tab re-arranging layout

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#8406]
**Task description**
The whole Home Tab has had an update when it comes to layout.
This is to improve the spacing when it comes to smaller screens.
The outside spaces are smaller, the tabs are not moved to the left and search with dropdown box to the very right. 
All text style sizes are still the same.

See the update from the original Figma file here:
https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/?node-id=1488%3A297

<img width="1221" alt="Screenshot 2021-06-22 at 14 28 35" src="https://user-images.githubusercontent.com/71656189/122933058-2ec94780-d366-11eb-866f-d54ee920e8a4.png">

**Comment by cbjeukendrup** [comment]
Fixed in PR #8466, isn't it?
