### ISSUE TITLE
[MU4 Issue] App window size/position changes after relaucnhing application on Windows/Linux (doesn't save main window size/position)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8408]
**Describe the bug**
Upper menu buttons as shrink, minimize, close window dissappears in Full screen mode
Also there is a gap between bottom menu and MU4 application in Full screen mode (MU4 shows in fact not in full screen when Full Screen Mode active)
App changes it`s position in window mode and in Full Screen mode (in Full Screen mode it goes out of the screen borders)

**To Reproduce**
1. Open MU4 
2. Expand app to Full Screen Mode 
3. Close MU4
4. Open MU4
5. Close MU4 again
6. Open MU4 again

**Expected behavior**
MU4 opens in Full Screen Mode if it was closed in Full Screen Mode
App window should save it`s position after relaunching App or opens in the middle of the screen if it is in window mode

**Screenshots**
![2021-06-22 03_32_03-MuseScore 4](https://user-images.githubusercontent.com/71372310/122953710-82985880-d387-11eb-991d-182e205d5451.jpg)
![2021-06-22 03_33_01-](https://user-images.githubusercontent.com/71372310/122953717-8330ef00-d387-11eb-9886-a90e3e6e5869.jpg)

https://user-images.githubusercontent.com/71372310/124609986-cb1c3f80-de78-11eb-8161-2585485dc9fc.mp4

**Desktop (please complete the following information):**
Windows 10
Linux

**Comment by DmitryArefiev** [comment]
Tested on Win10, LinuxMint 20.2 - FIXED in #10049
