### ISSUE TITLE
[MU4 Issue] "Do you want to save..." dialog has dangerous "Show this message again" option

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8438]
**Describe the bug**
When closing MuseScore without saving changes to a score the "Do you want to save changes...before saving" dialog has a checkbox "Show this message again". But if you uncheck this all your changes are just discarded without even being asked, and there's no obvious way to turn it back on.

**To Reproduce**
1. Create a new score
2. Add a note
3. Close
4. Observe "Show this message again" checkbox
 
**Expected behavior**
This message should always been shown when closing a score without saving changes, with no option to hide it.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
From chatting to @Tantacrul he basically doesn't see any reason to change from the MU3 prompt, which also uses the word "Discard" rather than "Don't save" for the button.

**Comment by RomanPudashkin** [comment]
The option was added on purpose. This dialog is too annoying at the moment for developers, because we always have "dirty state", even we didn't do any changes in the score. So I have added the ability to disable it. The option will be removed later

**Comment by wizofaus** [comment]
Oh ok...I've been working quite a bit on the undo stack and part of that is ensuring that after undo-ing everything the score is considered "clean", which does work now - though as you note, it is dirty on first opening: surely fixing that would've been easier than adding that checkbox though! I'm happy to include it in the PR I already have up.

**Comment by wizofaus** [comment]
But actually...this behaviour of all new scores being "dirty" by default is the same as MU3, so I don't think we should change it without some discussion.

**Comment by wizofaus** [comment]
Also I just noticed this dialog is not shown when you haven't saved changes to your current score then use File|New to create a new score - even though your old one disappears and is no longer accessible (I believe it might still be in memory)

**Comment by wizofaus** [comment]
Oh all, if you do choose Save on a newly score with modifications on this dialog, then *cancel* from the Save dialog, it goes ahead and closes the document and discards your changes, which isn't expected (it should just return you to the score).

**Comment by wizofaus** [comment]
With the most recent code if I create a new score and try to close without saving I get `Do you want to save changes to the score "" before closing` (vs say, "Untitled").

**Comment by wizofaus** [comment]
...and there's *still* no prompt-to-save dialog if you just open a new score without explicitly closing the current (modified) one.  It's still not clear to me if this action is always supposed to automatically close the current score (it never actually unloads it from memory as far as I can tell). Not sure if the multi-instance work will address this?
Nor is there any prompt for unsaved changes on quitting the whole application.

**Comment by wizofaus** [comment]
BTW in recent builds this prompt has stopped showing at all, appears to be a regression.

**Comment by wizofaus** [comment]
The option is gone now, but still displays "" when closing an unnamed score with unsaved changes

**Comment by vshalkevich** [comment]
A new bug would be created by me
