### ISSUE TITLE
[MU4 Issue]

### ISSUE THREAD

**Issue by dlitvak98** [musescore/MuseScore#8439]
**Describe the bug**
After about a minute of editing a score, the program freezes up and won't work until force quitting. This happens every time.

**To Reproduce**
1. Open musescore and create a score
2. Add a few notes
3. Musescore stops responding to inputs

**Expected behavior**
Just working

**Screenshots**
I've uploaded debug logs to https://pastebin.com/XmJ9355U
The last few lines about an overflow seem to be the issue

**Desktop (please complete the following information):**
 - OS: Manjaro Linux

**Additional context**
If anyone knows where in the codebase this error originates I can try taking a look myself but I haven't been able to find it with grep.

**Comment by MarcSabatella** [comment]
Looks from
Your log line you are taking about 3.6, not a development build of MuseScore 4.  Best to ask for help on the Official support forum on MuseScore.org.  When you do, be sure to attach your score and more precise steps to reproduce the problem.

**Comment by Tantacrul** [comment]
Closing
