### ISSUE TITLE
[MU4 Issue] 'Save as' dialog width issue

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#8443]
**Describe the bug**
The 3 buttons at the bottom should never come across the space underneath the top left icon. It seems the issue is the width size of the top text box "Do you want to save changes...." etc.
The text box according to Figma should be 420 pixels wide, which is the same width as all the 3 buttons combined together (in this kind of dialog with these 3 buttons). 

**Expected behavior**
![Screenshot 2021-06-28 at 14 10 18](https://user-images.githubusercontent.com/71656189/123641839-970ea200-d81a-11eb-8e1e-9d6cb6f4c02a.png)

**Screenshots**
![Screenshot 2021-06-28 at 13 52 00](https://user-images.githubusercontent.com/71656189/123642490-421f5b80-d81b-11eb-867c-ec8f1313ad8b.png)

**Desktop (please complete the following information):**
 - Mac OS

**Additional context**

**Comment by wizofaus** [comment]
This dialog no longer shows at all on Windows. Note also on Window the cancel button should be the rightmost.

**Comment by jessjwilliamson** [comment]
> This dialog no longer shows at all on Windows. Note also on Window the cancel button should be the rightmost.

Yes that is correct.

**Comment by jessjwilliamson** [comment]
![image](https://user-images.githubusercontent.com/71656189/142211238-5a8a8f51-008a-40fc-ab6d-0db88f784072.png)
It's very close now, can we nudge the text to the left a bit more please with the Don't Save button? :)

**Comment by jessjwilliamson** [comment]
@cbjeukendrup can be a tiny fix for you? :)
