### ISSUE TITLE
Meaning of keyboard shortcut popup message is confusing

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8456]
Users who select "Define" in Preferences > Shortcuts are shown a popup containing a confusing instructional message:

**Current message**
<img width="538" alt="Original_Popup_define-keyboard-shortcut " src="https://user-images.githubusercontent.com/86290556/123804265-691b8180-d930-11eb-98f6-2901f929accf.png">

This message is also redundant because the necessary instruction is already included in the "New shortcut" text field. 

A simple heading would make this popup clearer: 

**Proposed replacement text**:
<img width="538" alt="Proposal_Popup_define-keyboard-shortcut" src="https://user-images.githubusercontent.com/86290556/123803903-0d50f880-d930-11eb-875e-c41cb38ccb68.png">

**Expected behavior**
A clear and concise heading ("Define Keyboard Shortcut") should replace the existing two lines of text (in red circle above).

Laptop, MacOS Big Sur

**Comment by PranshuSrivastava** [comment]
Hey @bkunda , I have submitted a PR to fix this issue. Please check it out.

**Comment by bkunda** [comment]
Hi @PranshuSrivastava. Thanks for working on this! 

I just have one small amendment to make, which relates to the text styling of the header "Define keyboard shortcut". I apologise - I should have made this clearer in my issue notes. 

The way this heading currently appears is:
<img width="540" alt="Corrected-popup-v 1" src="https://user-images.githubusercontent.com/86290556/124884084-4ca8d480-e015-11eb-976f-dc3910454be9.png">

The heading "Define keyboard shortcut" should instead be in FiraSans Semibold 22pt, left-aligned, like so:
<img width="538" alt="Proposal_Popup_define-keyboard-shortcut" src="https://user-images.githubusercontent.com/86290556/124884237-6fd38400-e015-11eb-80fc-4c11ece10150.png">

Please also ensure there is no full stop at the end of this heading. And please note the use of capitals (only for the first word, so "Define keyboard shortcut").

Many thanks,
Bradley

**Comment by PranshuSrivastava** [comment]
Hey @bkunda , I have resolved the issue. Please checkout the PR.
