### ISSUE TITLE
MU4 crashes when creating parts

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8457]
MU4 crashes when a part is selected and the "open" button is pressed. 

See these two videos for reproduction: 

https://www.dropbox.com/s/3zojyrv8y4jnt4s/Crashes_Parts-1.mov?dl=0
https://www.dropbox.com/s/ihnucl5liok7w94/Crashes_Parts-2.mov?dl=0

Note: In the first video, the crash only occurred when the "piano" part was opened; the "vocal" part opened correctly. In my second video, it was opening the "vocal" part that triggered the crash. 

MU4 should not crash when a part is opened. 

Apple MacBook Air M1 running OS11.4

**Comment by njvdberg** [comment]
This will be part of the new way of handling parts I'm working on, see also [this document](https://www.dropbox.com/s/rhs2ietylrbzrjt/Instruments_2020_V07_Second_Amendment_V01.pdf?dl=0)
