### ISSUE TITLE
[MU4 Issue] Buttons in languages installation popup panel aren't aligned

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#8460]
**Describe the bug**
The buttons in the installation panels in the section "Languages" are not aligned. This probably also goes for Extensions and Plugins sections, but that can't be confirmed due to #8405.

**To Reproduce**
1. Go to Home > Add-ons > Languages. 
2. Click a language to open its installation popup panel. 
3. The buttons in the popup panel are not aligned. 

A part of the problem is that ProgressButton does not have the same height as a normal button. 
The height of the normal button is also a problem: #8098. So now we have:
- Text button: 29px
- Icon button: 30px
- Progress button: 31px

Hmm...

**Expected behavior**
The buttons should have equal heights and should be aligned. 

**Screenshots**
<img width="857" alt="Schermafbeelding 2021-06-29 om 23 09 56" src="https://user-images.githubusercontent.com/48658420/123868724-5ef98300-d930-11eb-844c-af17a8900726.png">

<img width="1788" alt="Schermafbeelding 2021-06-29 om 23 21 20" src="https://user-images.githubusercontent.com/48658420/123869007-bc8dcf80-d930-11eb-980b-067082d5f861.png">

<img width="2048" alt="Schermafbeelding 2021-06-29 om 23 35 40" src="https://user-images.githubusercontent.com/48658420/123870527-b993de80-d932-11eb-89f7-de27e275be97.png">

**Desktop (please complete the following information):**
 - OS: reported on macOS

**Comment by RomanPudashkin** [comment]
No longer relevant, see:
https://github.com/musescore/MuseScore/pull/10487
https://github.com/musescore/MuseScore/pull/10479
https://github.com/musescore/MuseScore/pull/10509
