### ISSUE TITLE
[MU4 Task] Get rid of QWidgets from libmscore

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#8465]
**Task description**
Get rid of QWidgets from libmscore

**Comment by Jojo-Schmitz** [comment]
Aren't those needed for Plugins?

**Comment by igorkorsukov** [comment]
If they are needed for plugins, then let them be in plugins :)
I will investigate what is why and for what :)

**Comment by jeetee** [comment]
QWidget itself wasn't, but the Q_GADGET / Q_OBJECT declarations were to force MOC to process some files and generate correct types for the QmlEngine.

Removing QWidget parameters from functions within libmscore should not interfere with that.

**Comment by Jojo-Schmitz** [comment]
Ah, right. Sorry for the noise then

**Comment by cbjeukendrup** [comment]
I did a search for what of Qt is still used in Libmscore (just search for "Q" in the Engraving module):

- qreal, QChar, QString, QStringRef, QStringList, QList, QVector, QHash, QSet, Q(Multi)Map, QStack, QPair, etc.
- qMax, qAbs, qMin
- QVariant
- QObject::tr(), qApp->translate(), QT_TRANSLATE_NOOP (if we create our own macro for QT_TRANSLATE_NOOP, let’s give it a better name like MAKE_TRANSLATABLE)
- qDebug(), Q_ASSERT, qWarning, qFatal, Q_UNUSED
- Q_OS_… macros
- Q_GADGET, Q_ENUM, Q_INVOKABLE
- Painting related things (QColor, QBrush)
- Keyboard modifiers, qApp->keyboardModifiers()
- QFile, QFileInfo
- QJson… (check.cpp, scorefont.cpp)
- qDeleteAll, qAsConst
- QRegularExpression (or even the old QRegExp)
- QMessageBox (in cmd.cpp, noteentry.cpp)
- QColorDialog (in edit.cpp)
- QBuffer (element.cpp, paste.cpp, score.cpp, scorefile.cpp)
- QMimeData (paste.cpp)
- QQmlEngine (figuredbass.cpp, score.cpp, but commented out in both those files)
- QImage (image.cpp, paste.cpp)
- QSvgRenderer (image.cpp)
- QCryptographicHash (imageStore.cpp)
- QTextDocumentFragment etc. (instrument.cpp, read114.cpp, textbase.cpp)
- QClipboard (lyrics.cpp, textbase.cpp, textedit.cpp)
- qRegisterMetaType etc. (mscore.cpp)
- QPaintDevice (mscore.cpp)
- QVector2D (note.cpp)
- QDateTime (page.cpp, revisions.cpp)
- QXmlStreamReader
- QDir (scorefile.cpp)
- qZip (scorefile.cpp)
- QTextCursor (textbase.cpp/h)
- QInputMethodEvent (textedit.cpp)
- QFlags
- QQueue (score.h)

So except for QMessageBox and QColorDialog, there are no QWidgets in libmscore any more (some were deleted in PR #8411).
But there are still some Qt GUI related things (Keyboard modifiers, QTextDocumentFragment, QClipboard, QTextCursor, QInputMethodEvent).

**Comment by vpereverzev** [comment]
> I did a search for what of Qt is still used in Libmscore (just search for "Q" in the Engraving module):
> 
>     * qreal, QChar, QString, QStringRef, QStringList, QList, QVector, QHash, QSet, Q(Multi)Map, QStack, QPair, etc.
> 
>     * qMax, qAbs, qMin
> 
>     * QVariant
> 
>     * QObject::tr(), qApp->translate(), QT_TRANSLATE_NOOP (if we create our own macro for QT_TRANSLATE_NOOP, let’s give it a better name like MAKE_TRANSLATABLE)
> 
>     * qDebug(), Q_ASSERT, qWarning, qFatal, Q_UNUSED
> 
>     * Q_OS_… macros
> 
>     * Q_GADGET, Q_ENUM, Q_INVOKABLE
> 
>     * Painting related things (QColor, QBrush)
> 
>     * Keyboard modifiers, qApp->keyboardModifiers()
> 
>     * QFile, QFileInfo
> 
>     * QJson… (check.cpp, scorefont.cpp)
> 
>     * qDeleteAll, qAsConst
> 
>     * QRegularExpression (or even the old QRegExp)
> 
>     * QMessageBox (in cmd.cpp, noteentry.cpp)
> 
>     * QColorDialog (in edit.cpp)
> 
>     * QBuffer (element.cpp, paste.cpp, score.cpp, scorefile.cpp)
> 
>     * QMimeData (paste.cpp)
> 
>     * QQmlEngine (figuredbass.cpp, score.cpp, but commented out in both those files)
> 
>     * QImage (image.cpp, paste.cpp)
> 
>     * QSvgRenderer (image.cpp)
> 
>     * QCryptographicHash (imageStore.cpp)
> 
>     * QTextDocumentFragment etc. (instrument.cpp, read114.cpp, textbase.cpp)
> 
>     * QClipboard (lyrics.cpp, textbase.cpp, textedit.cpp)
> 
>     * qRegisterMetaType etc. (mscore.cpp)
> 
>     * QPaintDevice (mscore.cpp)
> 
>     * QVector2D (note.cpp)
> 
>     * QDateTime (page.cpp, revisions.cpp)
> 
>     * QXmlStreamReader
> 
>     * QDir (scorefile.cpp)
> 
>     * qZip (scorefile.cpp)
> 
>     * QTextCursor (textbase.cpp/h)
> 
>     * QInputMethodEvent (textedit.cpp)
> 
>     * QFlags
> 
>     * QQueue (score.h)
> 
> 
> So except for QMessageBox and QColorDialog, there are no QWidgets in libmscore any more (some were deleted in PR #8411).
> But there are still some Qt GUI related things (Keyboard modifiers, QTextDocumentFragment, QClipboard, QTextCursor, QInputMethodEvent).

Damn, I love you, Casper! It's really useful to see the full list. GJ
