### ISSUE TITLE
[MU4 Task] Updated Radio button

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#8472]
**Task description**
Seeing some opacity issues with the radio buttons, especially the text field colour when that should always be 100% and only the stroke colour changes depending on the states.

This is what the current radio button looks like from the builds:
![Screenshot 2021-06-30 at 12 27 05](https://user-images.githubusercontent.com/71656189/123952875-8129ea00-d99e-11eb-9804-f7068b03a91d.png)
The normal/selected state of the radio button here looks too faded.

I have made a new update on the radio button in the UI and components & styles Figma page.
![image](https://user-images.githubusercontent.com/71656189/123953451-25ac2c00-d99f-11eb-9829-741477144a1f.png)

The radio button now has 3 layers:
- 'BG_Circle' is the text field circle layer and it always stays at 100% opacity.
- 'Stroke' is the stroke only layer, and this layer only changes depending on what state it is in.
- 'Radio_Selected_Dot' This has not changed, but should always be 100% opacity anyway.

**Comment by cbjeukendrup** [comment]
If by any chance nobody is working on this yet, I would like to fix this issue.

**Comment by Eism** [comment]
@cbjeukendrup thanks, no probs

**Comment by jessjwilliamson** [comment]
@cbjeukendrup Sure! Message me on Discord if you have any questions. Thank you! :D
