### ISSUE TITLE
[MU4 Issue] Eye button on Instruments panel closed after opening it via Parts dialog

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8483]
**Describe the bug**
Eye button on Instruments panel closed after opening it via Parts dialog
All eyes in the Instruments Panel closed.

**To Reproduce**
1. Create new score
2. Open Parts dialog
3. Open any Instrument part (it`s tab appears near score tab on the main Score View)
4. Observe Instruments on Instruments panel

**Expected behavior**
Eye button near opened Instrument part should be opened 

**Screenshots**

https://user-images.githubusercontent.com/71372310/124092017-17254980-da5f-11eb-86ff-a0d057f3e4b0.mp4

**Desktop (please complete the following information):**
Windows 10
Linux

**Comment by njvdberg** [comment]
Is part of the PR I'm working on.

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/8795/files
