### ISSUE TITLE
File > Open command does not trigger "open file" dialog

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8486]
When user clicks File > Open, MuseScore 4 appears to cycle through recently opened files.

Expected behaviour: File > Open should trigger the operating system's "open file" dialog.

See this video for reproduction: https://www.dropbox.com/s/80fgplus0glylfd/Issue_open-file-not-working-1.mov?dl=0

Note: files being triggered as a result of File > Open command seem to come from my two most recently viewed files (screenshot below):

<img width="540" alt="Issue_recent-files-screenshot" src="https://user-images.githubusercontent.com/86290556/124131504-3786ef80-dac3-11eb-82d0-7137b33ed7b4.png">

System: MacBook Air M1, MacOS 11.4

**Comment by wizofaus** [comment]
Can't reproduce on Windows 10.
