### ISSUE TITLE
[MU4 Issue] New Score Wizard - Family and Instrument columns should be re-sized

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#8497]
**Describe the bug**
As shown on Figma, the family column is 200 pixels wide. The builds are showing it's 246 wide.
Reducing the width back to 200 can also improve spacing for the Instruments family. So with the family column being 200 pixels, this results that the Instruments family will be 272 pixels wide which will be very beneficial as there are dropdown combo boxes that are struggling to fit in right now - for example, we have a combo dropdown that needs to fit space for an instrument that has '13-course' inside (see screenshot). 

**Expected behavior**
![Screenshot 2021-07-02 at 10 57 16](https://user-images.githubusercontent.com/71656189/124257493-52d61700-db24-11eb-9e70-d08aef9b9257.png)
![Screenshot 2021-07-02 at 11 10 56](https://user-images.githubusercontent.com/71656189/124259276-3fc44680-db26-11eb-94c2-9483341cd55e.png)

**Comment by jessjwilliamson** [comment]
Hi, I just checked the nightly build, and the sizes are incorrect. The Family column is very close, it's showing 197 pixels wide instead of 200 pixels. The Instruments column is showing 246 instead of 272 as I requested. It's showing 'Your score' 3rd column to be extremely wide now because of this. Please check again and update this. thanks :)

*Expected behaviour*
<img width="985" alt="Screenshot 2021-07-13 at 13 19 57" src="https://user-images.githubusercontent.com/71656189/125450432-bf523cb5-fe53-45a8-9215-9b1dec53b902.png">

*Screenshots*
<img width="1332" alt="Screenshot 2021-07-13 at 13 17 16" src="https://user-images.githubusercontent.com/71656189/125450113-a8c30139-2f0b-4dfb-b108-5ba608629b3e.png">

**Comment by jessjwilliamson** [comment]
Hi, @RomanPudashkin @Eism 
I want to bump this issue again, can we please make sure the Instruments column is wider, please. Like a selected state on an instrument would be 276 pixels wide. Additionally, this also solves long-worded instruments (as shown in the screenshot) without the '...' continuous issue and a dropbox can fit next to '12 Hole chromatic harmonica'. For the screenshot, I have re-sized the NSW window on purpose to demonstrate the desired sizing for the default window. 
<img width="325" alt="Screenshot 2021-08-18 at 15 28 11" src="https://user-images.githubusercontent.com/71656189/129916656-d1ac8643-dea5-496f-ab54-3511b07beca1.png">
<img width="326" alt="Screenshot 2021-08-18 at 15 28 26" src="https://user-images.githubusercontent.com/71656189/129916665-6945301c-6eb2-4f8f-9bfa-bbce555db2ec.png">

**Comment by vshalkevich** [comment]
My test instrument says that it is 200x30px maybe it wrong. Could someone else check it?

**Comment by jessjwilliamson** [comment]
> My test instrument says that it is 200x30px, maybe it wrong. Could someone else check it?

That should be the 'Family' column. The very left one yes? :)

**Comment by vshalkevich** [comment]
yes :) 

> 
> 
> > My test instrument says that it is 200x30px, maybe it wrong. Could someone else check it?
> 
> That should be the 'Family' column. The very left one yes? :)
