### ISSUE TITLE
Fretboard Diagrams are using the Wrong UI Colour & Do Not Refresh on the score

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#8498]
**Describe the bug**
Fretboard diagrams are not using the Font Primary colour, which causes them to look incorrect in Dark mode / HC mode.

Changes made in the inspector do not refresh on the score immediately

See video
https://www.dropbox.com/s/cn1efmngpaz1iv4/Fretboard_Diagrams_Wrong_Colour_%26_Do_Not_Refresh_on_The_Score.mov?dl=0

**Comment by Tantacrul** [comment]
@Howard-C - I thought you might like this one.

**Comment by Howard-C** [comment]
I created #8504, but I only (partly) solved the first issue, plus another issue that isn't mentioned here. The part I didn't solve is that when I change the theme, it's gonna need a click on the diagram to change its colour (but after that it will be fine), not sure why it needs that though.

**Comment by Eism** [comment]
fixed on #8504
