### ISSUE TITLE
[MU4 Issue] CTRL+SHIFT+drag to duplicate elements not working

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8512]
**Describe the bug**
Holding down CTRL & SHIFT and dragging any element doesn't behave as per MU3 (though MU3 seems broken for many element types too)

**To Reproduce**
1. Create a score with pedal marks, dynamics, trill lines etc.
2. Hold down CTRL & SHIFT and try to drag them to different locations, including onto the palette to create a custom palette entry
3. Element doesn't move (specifically, the grips don't move horizontally) and no copy is created when releasing mouse, and no palette entries can be created
4. Create a slur, and try the same thing - element can be moved vertically but nothing else

**Expected behavior**
For me, the expected behaviour is that CTRL+SHIFT+drag should create as close a possible of a copy of whatever element is being copied (or a new palette entry if dragged there).
However MU3's behaviour seems to be that
a) for most lines (hairpin, pedal marks, trills, etc.), CTRL+SHIFT+drag easily allows creating a copy of the element, but the length is not remembered, instead it seems to always be created such that it ends at the end of the current measure.
b) for clefs, time/key signatures, it attempts to duplicate it at the *start* of the dropped measure, regardless of where you drop it
c) for other elements (including accidentals & dynamics, text, slurs etc), CTRL+SHIFT+drag works mostly, but you need to be very very careful what you select as the target (which is tricky because of the 🚫 cursor when you're not quite in the right location, making it hard to determine where the tip of the mouse cursor would be), and for slurs the length and control points are all lost, it just creates a new default-shape slur from the target note to the following note.

However, for v4.0, the decision at this point is that ALT+drag to duplicate elements more or less the way it works in v3 (except that ALT+drag also turns off auto-place, to be discussed...)

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10, built with MSVC

**Additional context**
My preference would be to fix CTRL+SHIFT+drag to always create the best possible copy for all elements at the exact location dropped, and make it easier to find possible targets, but at a minimum we should restore MU3 behaviour.
Also, the behaviour seems a little odd in MU3 even for the elements that DO work - it only cares about whether CTRL+SHIFT are held down at the point the mouse-down event occurs - you can then release them and the drag/copy behaviour is still active. OTOH, if you first press & hold the left mouse button (but don't move the mouse), then press CTRL+SHIFT, then move the mouse, the behaviour seem to be the same as CTRL+drag, which seems to allow just adjusting horizontal position (without re-anchoring).
The code for MU3 is ScoreView::mousePressEventNormal with the call to cloneElement() - there doesn't seem to be any equivalent code in MU4 yet at all.

NB palette customisation is covered by https://github.com/musescore/MuseScore/issues/11006

**Comment by Tantacrul** [comment]
@wizofaus - the general shortcut for duplicating elements is to hold the **alt** button & dragging to duplicate. Agreed, it should work for all elements.

What do you think?

**Comment by Tantacrul** [comment]
As a general comment on this issue: if it is something that will take **a lot** of time to achieve, I move that we wait until a later release to fix.

**Comment by MarcSabatella** [comment]
People do use this often for copying lines, since there is often no other good way to copy them alone.

But more importantly, this is how you customize your palette.  The ability to add elements from your score - custom text, customized lines, etc - to palettes is a crucial feature of MU3 that I don't think we can afford to lose.  I don't know that it needs to be in the public alpha necessarily, but certainly by the beta I'd expect it to see all core functionality present.

To be clear: it's the exact same function used for cloning elements within your score as for cloning elements to add to a custom palette.  Presumably once that function is implemented, both features will be able to work.

**Comment by MarcSabatella** [comment]
FWIW, I have no particular attachment to Ctrl+Shift as the mechanism for this, if the consensus is that Alt would be more familiar to people just coming to MuseScore from other software.  But FWIW, currently (in MU3), Alt+drag is used for disabling autoplace while adjusting.  No particular reason they couldn't be reversed, assuming we clearly document the change.

**Comment by Tantacrul** [comment]
I think we should do exactly that: reverse them. The existing system is so janky, contrary to patterns found elsewhere and undiscoverable that it's worth altering now.

**Comment by wizofaus** [comment]
Well regardless of whether it's CTRL or ALT, neither work currently, and worse I just tested ALT+SHIFT+drag on a hairpin and MuseScore crashed.

**Comment by Tantacrul** [comment]
> 

I've just tried to reproduce the crash but can't. If you can pop the steps in a new bug, we'll bump it to the top of the list pronto.

**Comment by wizofaus** [comment]
Suspect I was testing against an older version, doesn't crash with latest thankfully.  But I'm happy to work on making ALT+SHIFT+drag copy, if we're all agreed that's what's wanted...

**Comment by wizofaus** [comment]
Working on this now, but it turns out ALT+drag already has a meaning, which is to turn off auto-place.  Both are important and independent functions so we can't use the same key for both.

**Comment by wizofaus** [comment]
BTW should this be moved to the 4.1 project? @Tantacrul

**Comment by Tantacrul** [comment]
I'd say it's a good candidate for it. We're getting super close to alpha 2, so we're just focusing on that now. However, I need to do a lot of revision of our Beta 1 bugs shortly (as well as many of the new issues that popped up while I was on vacation over the last two weeks).
