### ISSUE TITLE
[MU4 Issue] Can edit properties of "automatic" key signatures at the beginning of each system

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8521]
**Describe the bug**
MU3 disallows editing the "mode" and "show courtesy" flags for automatically created key signatures shown at the beginning of each system - you can only edit them for the actual key signature that was originally added by the user.
MU4 allows editing these properties for generated key signatures but doesn't propagate them as expected.

**To Reproduce**
1. Create a new score
2. Add a key signature at the beginning
3. Select a key signature from a system other than the 1st
4. Edit its "show courtesy" and "mode" properties
5. Select initial key signature (start of score)
6. Observe that mode/show courtesy properties are as per the defaults

**Expected behavior**
Either MU3 behaviour where you can't edit these properties for generated key signatures, or have it apply to all relevant key signatures.

**Screenshots**

**Desktop (please complete the 
following information):**
Windows 10, built with MSVC 10

**Additional context**
This is somewhat (but not entirely) related to the bug reported in MU3 (https://musescore.org/en/node/295910) where editing these properties for the very first key signature in a piece doesn't work.  There are various ways to solve that (it relates to the "key signature map" that is stored for the score, and to the fact that generated key signatures don't get this property and end up overriding the original one), but for editing a generated key signature I can't see a straightforward way of addressing, as there's no link from the generated key signature back to the source element.

**Comment by wizofaus** [comment]
This is now changed from the original behaviour - you can no longer modify the "Show courtesy" or "Mode" properties by default. But if you modify, say, the *colour* of a key signature on a subsequent system, you can now modify these properties, and they do appear to stick.  I'm not sure what the point of allowing that is, but I guess it doesn't cause any harm either.
Happy to close, as I can't really see it causing any issues for a user.

**Comment by Tantacrul** [comment]
Yeah, perhaps closing this and waiting to see if anyone has a problem is the best bet. We need to refine the entire relationship between the inspector and **global styles** / or the ability to **apply changes to all similar items** at some point later anyway.
