### ISSUE TITLE
[MU4 Task] [TECH_DEBTS] Preferences warning

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#8541]
**Task description**

Investigate and fix the cause of the warnings during the opening of the "Preferences" dialog

13:35:46.413 | WARN  | main_thread | Qt         | QQmlComponent: Component is not ready
13:35:46.495 | WARN  | main_thread | Qt         | QQmlComponent: Component is not ready
13:35:46.497 | WARN  | main_thread | Qt         | QQmlComponent: Component is not ready

+

"Cannot open file ':/data/icons/raster-horizontal.svg', because: No such file or directory"

**Comment by cbjeukendrup** [comment]
I'm pretty sure they have been resolved meanwhile. I've not seen them for months. So this one can be closed!
