### ISSUE TITLE
[MU4 Task] [TECH_DEBTS] Provide an alternative solution for the Qt warning fixes

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#8546]
**Task description**
Replace https://github.com/musescore/MuseScore/commit/709fc493a45f925707eb4afe80758b0f6f29c2cc with an alternative solution

**Comment by cbjeukendrup** [comment]
For most of those, I found a solution a couple of months ago when I was experimenting with Qt 6 (because those deprecated things are removed entirely in Qt 6). I will create a PR with those solutions.

**Comment by vpereverzev** [comment]
> For most of those, I found a solution a couple of months ago when I was experimenting with Qt 6 (because those deprecated things are removed entirely in Qt 6). I will create a PR with those solutions.

perfect
