### ISSUE TITLE
[MU4 Task] Allow usage at schools again

### ISSUE THREAD

**Issue by NothanUmber** [musescore/MuseScore#8557]
Currently the privacy policy rules out usage of MuseScore for below 13 year olds, which makes it impractical to use MuseScore at (music) schools. As far as I understood this is because of the (in)ability to agree to data usage for children?

In that case: Would it help to e,g, modify the dialog that asks for permission to use telemetry in a way that it makes clear that children have to click to "no" here and make sure that no data is transferred in that case at all?
Or even disable all online features by default and add a switch in settings that allows to enable these separately for telemetry, auto updates etc.)- and to open a dialog that asks to verify that the user is older than 13 years that has to be agreed before any of these features can be enabled.
Then hopefully the passage about age could be removed from the Privacy Policy and Terms of Use?

Probably 99% of the features should work perfectly fine without any online features. I think allowing children to use MuseScore at all far outweights some slight inconveniences like manual update downloads, no telemetry or crash reports etc. that this group would have to miss out on then.

**Comment by Tantacrul** [comment]
Our lawyers are working on this at the moment. As you've pointed out, the line in question is a legal GDPR requirement that applies to using cloud services (musescore.com) and it should not relate to the regular functioning of the desktop app. I think this needs to be clarified more precisely.

**Comment by Tantacrul** [comment]
I thought I'd leave this open a little longer.

**Comment by NothanUmber** [comment]
Thanks for the feedback, making it clear (and technically ensure) that the software can be used for all ages is important, good to hear that this is now clarified and reconsidered!

Regarding musescore.com: Is the main problem there that children cannot legally create an account on the page that allows to associate their actions with their person?
Perhaps at least public domain scores could be made downloadable without login again then? That would already cover a lot of ground of scores interesting for education.

But that is already slightly off-topic, it's about the main MuseScore application here.

**Comment by Tantacrul** [comment]
Yeah, being able to create an account online is one of those reasons. But also, anyone 13 or younger is not legally able to provide consent for their personal data to be used. GDPR defines an IP address as 'personal data'.

However, it should not be a blanket statement in the PP to cover everything, for the reasons you say.

Cheers!

**Comment by Jojo-Schmitz** [comment]
In that case anyone 13 and younger would not be allowed to visit __any__ website.
Every website on the planet keeps logs with IP adresses and time stamps, as far as I can tell?
