### ISSUE TITLE
[MU4 Issue] Create a linked staff on an empty score leads to crash

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8566]
**Describe the bug**
Create a linked staff on an empty score leads to crash

**To Reproduce**
1. Create a score (don't add anything on it)
2. Click on 'Instruments' via Instruments panel
3. Expand one of instruments 
4. Click on Instrument option (gear icon)
5. Click on "Create a linked staff"

**Expected behavior**
No crash when try to create linked staff

**Screenshots**
![2021-07-07 10_49_02-Untitled](https://user-images.githubusercontent.com/71372310/124881598-36c8ee80-dfd8-11eb-94f5-b931d2ede04b.jpg)

**Desktop (please complete the following information):**
 Windows 10

**Comment by wizofaus** [comment]
Probably my "fault", as I added some code to ensure BracketItems were cleaned up properly on Staff destruction. But the real culprit is the copy ctor for Staff as it just copies the list of BracketItem pointers (_brackets) rather than creating a new list with cloned BracketItems.

**Comment by wizofaus** [comment]
Easiest fix for this is 
```
Staff* Staff::clone() const
{
    Staff* staff = new Staff(*this);
    staff->_brackets.clear();
    for (BracketItem* br : _brackets) {
        staff->_brackets.append(new BracketItem(*br));
    }
    return staff;
}
```
as adding an explicit copy constructor is quite a lot of a boilerplate code that the compiler can generate for us.
For safety we can also make the Staff copy constructor private.

**Comment by wizofaus** [comment]
Actually there is a Staff::init( ) function that already does the right thing, so it would make more sense to override the copy constructor and call that.
