### ISSUE TITLE
[MU4 Issue] Crash if create a new part and switch to Main Score tab

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8569]
**Describe the bug**
Crash if create a new part and switch to Main Score tab

**To Reproduce**
1 Open Parts dialog
2 Create New Part with default name
3 Switch to Main Score (on the score view)

**Expected behavior**
Main score should be visible

**Screenshots**
https://user-images.githubusercontent.com/71372310/124885145-a42a4e80-dfdb-11eb-819b-c5ffec9dbf1d.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by wizofaus** [comment]
This appears to be due to the fact that AbstractInvoker::invoke makes a copy of the callback list, but it's possible for one callback to delete/remove a receiver that occurs later in the list, but it's still in the local copy, hence still gets executed.
