### ISSUE TITLE
[MU4 Issue] Staff size rendered incorrectly after inserting measures

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8588]
**Describe the bug**
If a staff contains staff size changes, inserting an extra measure before it moves the staff change element but renders the extra measures at the wrong size. On saving/closing/re-opening it renders correctly.
 
**To Reproduce**
1. Create a new score
2. From the Layout palette add a staff change element at measure 2 and specify "cue size" using the inspector
3. Select the first measure and choose Insert One Measure from the Add menu
4. Note that newly added measure is shown at cue size even though the staff change element moved along to the following measure

**Expected behavior**
Newly added measure should render at normal size.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**

**Comment by Tantacrul** [comment]
Yeah. Staff size changes are slightly buggy and janky. If you try to undo the actions described above, the results are very strange.

**Comment by wizofaus** [comment]
Still happening, seems to be some disconnect between which measures it thinks should be rendered at different sizes vs which ones do actually have such a size.  Can have a look at it if I get the chance.

**Comment by DmitryArefiev** [comment]
Fixed in #11970
