### ISSUE TITLE
[MU4 Issue] Create New Score > Choose from template > Score preview broken if click Plus or Minus buttons

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8602]
**Describe the bug**
New Score Wizard > Choose from template > Score preview broken if click Plus or Minus 
**To Reproduce**
1. Open New Score Wizard
2. Click "Choose from template tab" upper tab
3. Click Plus or Minus buttons near Score preview

**Expected behavior**
Plus button should get closer, Minus - move away score view

**Screenshots**
https://user-images.githubusercontent.com/71372310/125417964-67cf73e8-1401-41a1-9e7f-4c36a4088b6d.mp4

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/8693
