### ISSUE TITLE
[MU4 Issue] Lyrics have too much vertical spacing between verses and hyphens too high

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8615]
**Describe the bug**
The vertical gap between verses of lyrics is far too great, and hyphens between words are rendered too high (almost top aligned)

**To Reproduce**
1. Create a score with some notes
2. Add a lyric with a hyphen (NB this might not be possible in MU4, you may need to do in MU3 and load)
3. Add a second verse lyric
4. Note that vertical hyphen alignment is wrong and that second verse is shown too far below 1st verse

**Expected behavior**
Same as MU3.6

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10, built with MSVC 2019

**Additional context**
This is seems to be due to the global "FontPaintDevice" that is passed into QFontMetricsF in qfontprovider.cpp for lineSpacing() and xHeight(). If no device is passed in to QFontMetricsF , the values are returned as per MU3.6 and the alignment looks correct.
But I'm not sure what the reasoning behind having this device is, and why it would make sense for some functions but not others.
Update: I believe the correct fix is to actually *not* multiply any info that comes back from fontMetrics by MScore::pixelRatio, which is what happens currently with both lineSpacing() and xHeight() (in textbase.cpp and lyricsline.cpp)

**Comment by Jojo-Schmitz** [comment]
I wonder whether sthis is related to all lyrics being seen as even one, due to a bug, see https://github.com/musescore/MuseScore/pull/8762#pullrequestreview-719646248
