### ISSUE TITLE
[MU4 Issue] Round corners of the selection indicators in New Score Wizard

### ISSUE THREAD

**Issue by iwoithe** [musescore/MuseScore#8624]
While looking at various MuseScore issues, I saw this screenshot.

![Instruments page in New Score Wizard](https://user-images.githubusercontent.com/71656189/125450432-bf523cb5-fe53-45a8-9215-9b1dec53b902.png)

Should the selection indicators (the blue rectangles) have rounded corners? I say this because all of the components (combo boxes, buttons, line edits etc.) all have rounded corners.

**To Reproduce**
1. Open MuseScore 4
2. Click on New Score
3. Click on the ``Next`` button until you see the Instruments page

**Expected behavior**
To see rounded corners on the selection indicators (the blue rectangles).

Feel free to close this issue if the non-rounded corners are intended.

**Comment by RobFog** [comment]
@Tantacrul @jessjwilliamson

**Comment by jessjwilliamson** [comment]
Nope, no rounded corners are intended :)

**Comment by iwoithe** [comment]
Alright. :)
