### ISSUE TITLE
[MU4 Issue] New scores have no barlines/stems etc,

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8626]
**Describe the bug**
Creating a new score using the "Choose Instruments" dialog shows staves with no barlines and when you add notes the stems aren't visible.

**To Reproduce**
1. Home|New Score|Choose Instruments
2. Add at least 1 instrument, click Done
3. Observe score has no barlines (and clef is too close to left edge)
4. Add 1/4 or shorter length notes, observer notes have no stems

**Expected behavior**
Barlines and stems would be nice 

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10/built with MSVC

**Additional context**
Problem doesn't happen creating a score from a template or loading an existing score. Appears to be something messed up with the default score style values.

**Comment by wizofaus** [comment]
Can be fixed by adding precomputeValues() to MStyle constructor or Score::setStyle(), line 5222 before the first return.
Former seems safer...

**Comment by igorkorsukov** [comment]
It looks like we have long ago lost the call to `precomputeValues` of `defaultStyle`, it's strange what worked.
