### ISSUE TITLE
Lyric line spacing is broken

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8638]
By default, lyric line spacing is set to 100%. 
In MuseScore 3.6, this results in a relatively "normal" amount of space between two lines of text. 
In MuseScore 4, the space between two lines of lyric text is far too large by default, and it cannot be corrected by the user.

This video illustrates this problem in greater detail:
https://www.dropbox.com/s/sf8vjnhp5c6xxy4/lyric-line-height-issue.mov?dl=0

This is what the line spacing looks like in MuseScore 4
<img width="1461" alt="Screenshot 2021-07-16 at 20 42 42" src="https://user-images.githubusercontent.com/86290556/125935962-098bd8a1-fc13-467f-a56a-bca5780b4ba8.png">

This is what it **should** look like by default (i.e. expected behaviour; N.B. screenshot taken from MuseScore 3.6)
<img width="1449" alt="Screenshot 2021-07-16 at 20 41 28" src="https://user-images.githubusercontent.com/86290556/125936032-a4150f54-fc62-4799-856e-dfc53029fedc.png">

The setting for this is in Format > Style > Lyrics
<img width="1164" alt="Screenshot 2021-07-16 at 20 41 36" src="https://user-images.githubusercontent.com/86290556/125935862-edefb2eb-c011-4c4c-b12f-a808d4e6faa4.png">

Macbook Air M1 running iOS 11.4

**Comment by wizofaus** [comment]
https://github.com/musescore/MuseScore/issues/8615

**Comment by Jojo-Schmitz** [comment]
I wonder whether sthis is related to all lyrics being seen as even one, due to a bug, see https://github.com/musescore/MuseScore/pull/8762#pullrequestreview-719646248

**Comment by wizofaus** [comment]
> I wonder whether sthis is related to all lyrics being seen as even one, due to a bug, see [#8762 (review)](https://github.com/musescore/MuseScore/pull/8762#pullrequestreview-719646248) and #7627

Don't believe so, I didn't need to touch that to get the correct spacing,  though that isEven definitely looks wrong!
