### ISSUE TITLE
Spacebar command doesn't work correctly in lyric text

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8639]
When the user is entering lyric text, the spacebar **should** move the cursor on to the next note (this is expected behaviour).

Instead, the spacebar only inserts a space after a word; it does **not** move the word on to the next note.

This video illustrates the current behaviour (to be fixed):
https://www.dropbox.com/s/42sofurj263iwbp/lyric-spacebar-issue.mov?dl=0

This video shows the expected behaviour (taken from MuseScore 3.6):
https://www.dropbox.com/s/94mvmqswtthws7s/lyric-spacebar-issue-correct.mov?dl=0

Macbook Air M1 running iOS 11.4

**Comment by wizofaus** [comment]
Already reported and fixed, feel free to test my branch!

**Comment by bkunda** [comment]
Great to hear @wizofaus!

**Comment by wizofaus** [comment]
Now merged, so you should be OK to close this if it's OK in the next nightly build.

**Comment by wizofaus** [comment]
@vshalkevich can you retest and close if all seems to be working thanks
