### ISSUE TITLE
[MU4 Issue] Dynamics shown in wrong size/style when added 

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8652]
**Describe the bug**
Dynamics shown in italics (dynamics codepoints are already styled as italicized so this looks wrong) and shown too small when added to scores.

**To Reproduce**
1. Create a new score
2. Add a dynamic to the first measure
3. Dynamic is shown too small and too slanted

**Expected behavior**
As per MU3 or as per text elements with dynamics symbols inserted.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
This is because when it applies the "Dynamic" text style to the element it overrides the existing formatting information for the dynamics symbol (using "ScoreText" etc.). MU3 doesn't do this, as `setFontStyle` is just a standard setter for an M_PROPERTY. I'm not sure why MU4 changed the behaviour for setFontStyle/setFamily/setSize but it's definitely quite broken as it is.
One option is to restore the MU3 behaviour of how those properties are treated, including to TextCursor::init(), the required call to cursor.init() in createLayout(), and setting layoutInvalid to true in TextBase::setProperty( ).

**Comment by wizofaus** [comment]
Oops, seems this specific problem was my fault, and worse, on other platforms the dynamic doesn't show at all.  However while reverting it is straightforward, there are still a number of other issues with editing text elements especially those using bold/italic text styles and musical symbols.

**Comment by RobFog** [comment]
Fixed?

**Comment by wizofaus** [comment]
Should be, if someone wants to verify on Mac we can close.

**Comment by cbjeukendrup** [comment]
I will check it!

**Comment by wizofaus** [comment]
From all reports this is fine now.
