### ISSUE TITLE
[MU4 Issue] text inspector for styles shows/sets wrong style

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8654]
**Describe the bug**
When viewing/setting the Text style property of a text element in the inspector (in the "More" popup), it shows the wrong current values, and on choosing a different one, the wrong style is applied.

**To Reproduce**
1. Create a new score, add Staff Text
2. Select it and in the inspector, click "More" then note the incorrect Text Style is shown.
3. Choose a different one and note that the element updates to the wrong style

**Expected behavior**
Should show correct style and update as expected

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
This is because the TextType enum in src/inspector/types/texttypes.h needs to exactly match the Ms::Tid enum with the current implementation, but doesn't.
I have a fix to update the former on my branch though if we could find a way of avoiding the need for two otherwise independent enums to align that'd be nicer.

**Comment by DmitryArefiev** [comment]
Tested in master build on Win10, Mac12, LinuxMint 20.2 - the current issue is **FIXED**

Also there are improvements regarding dropdown list in #10862

Closing
