### ISSUE TITLE
Context menus aren't fully selecting objects

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8657]
When an unselected object in the project/score editor is selected with a right-click, the context menu options that appear do not seem to affect the selected object. 

This is notwithstanding the fact that playback of the right-click selected object **does** work.

This video illustrates the issue in greater detail: https://www.dropbox.com/s/5wne1q0rqlp9j5v/Context-menu-issue-1.mp4?dl=0

**Expected behavior**
Right-clicking on any object should simultaneously perform 2 operations:
1. Select the object (i.e. it should become highlighted)
2. Trigger the relevant context menu

Apple MacBook Air M1 running iOS 11.4

**Comment by wizofaus** [comment]
That behaviour is the same as per MU 3.6 though.  I agree it's probably not expected behaviour in most cases, and other apps do tend to behave as you suggest (both selecting the object and showing the context menu). I don't think this is P0 issue though!

**Comment by bkunda** [comment]
I set it as P0 because, in my view, this issue must be fixed before release as the right-click command is a very fundamental system command that currently does not behave as expected (notwithstanding MuseScore 3.6's functionality, which we shouldn't be using as a benchmark in this case). Moreover, it currently does not behave consistently with other apps (and not just music notation apps, but even, for example, your average word processor). This is a matter of ensuring MuseScore feels as "polished" as possible and won't give rise to unpleasant user experiences, particularly at the basic level of ordinary system commands (like right-click). 

I am of course happy for someone to re-classify it as appropriate - I am still fairly new to Github so am very willing to be given some direction if my classifications are off from time to time! 🙂

**Comment by wizofaus** [comment]
Have a look through the list of P1 and P2 bugs - most are far more serious than this,  which has an easy workaround and users have been dealing with for years.  P0 I'd reserve for a critical new problem that prevents users from accessing critical functionality.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by bkunda** [comment]
Thanks for this suggestion @wizofaus, I will check this out! 
I will hasten to add, though, that just because users have been managing a workaround for a problem, doesn't mean we shouldn't be trying to fix it! I hope you agree 🙂

**Comment by wizofaus** [comment]
All bugs should be fixed, but we still have to prioritize them :) anyway, that's just my take on things as a volunteer contributor...

**Comment by RomanPudashkin** [comment]
I'm working on this

**Comment by bkunda** [comment]
Thank you @RomanPudashkin
