### ISSUE TITLE
Tabs in panels unexpectedly click-through to buttons underneath

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8659]
When the right side of the "instruments" and "properties" tabs is selected, the kebab icon beneath is automatically triggered and the relevant context menu appears. 

See this video for demonstration: https://www.dropbox.com/s/7dinae5d6qrmmwx/tab-click-through-issue.mov?dl=0

**Expected behavior**
Clicking _anywhere_ on on these tabs should _only_ trigger the relevant palette. There should be no automatic click-through to the buttons underneath.  

Macbook Air M1 running iOS 11.4
Windows 10 ARM in Parallels

**Comment by wizofaus** [comment]
Apparently "kebab menu" only refers to three *vertical* dots though, and three horizontal dots is a "meatballs menu" (I kid you not...). Are you sure this isn't P0 too? 😛

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
