### ISSUE TITLE
Playback position no longer starts on a selected note (must follow MS3.6.2 functionality)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#8661]
This is a recent regression in the nightly build. I've observed it on Windows.

**Steps to reproduce:**
1. Create a score with notes
2. Start playing score
3. Stop playing score
4. Click on any note (select note)
5. Start playing score again

**Actual result:**
Score saves the stopped place and start playing from it even if selected another note

**Expected result:**
Playing should start from the selected note

**See video:**
https://www.dropbox.com/s/m9ygn82r5h5fyy9/01_Playback_Position01__Not_Starting_from_User_Selection.mp4?dl=0

**Comment by Trainzack** [comment]
This regression is present in the July 3rd nightly build, but not the July 2nd nightly build.
