### ISSUE TITLE
Time signatures not consistently applying to new scores

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8662]
Newly created scores are not being consistently loaded with time signatures, despite one being selected in the "new score" dialog.

I have reproduced this issue in both MacOS and Windows (ARM). I have also tested key signatures and tempo marks, which seem to apply without a problem. The issue is fairly repeatable, but occasionally I did succeed in inserting a time signature, so the issue doesn't seem to be 100% consistent. 

https://user-images.githubusercontent.com/86290556/126163342-7f59924c-6436-45be-ae49-a8f3e8284677.mov

**Expected behavior**
A time signature should appear on a new score, even if the user doesn't make a specific selection in the "Additional Score Information" dialog: i.e. a new score should load with 4/4 by default, unless the user changes it to something else. 

<img width="1537" alt="Screenshot 2021-07-19 at 23 00 58" src="https://user-images.githubusercontent.com/86290556/126163552-c2f7bcd6-ad71-435a-8840-700b3ad7ee86.png">

Macbook Air M1 on MacOs 11.4
Reproduced also in Windows 10 (ARM) via Parallels

**Comment by bkunda** [comment]
N.B. I cite also https://github.com/musescore/MuseScore/issues/8648 (frequent crashes when creating new scores) as this occurred repeatedly during my testing of this issue.

**Comment by bkunda** [comment]
Update: I have been able to consistently trigger this problem in the latest nightly build (12Aug21). No time signature or key signature information is appearing in the new scores I create: 

https://www.dropbox.com/s/5huwwy7uacaeau4/Time-and-key-signatures-not-showing.mov?dl=0

**Comment by wizofaus** [comment]
Reproduced, investigating
