### ISSUE TITLE
Creating new projects overrides current project

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8668]
Projects that are currently open disappear and are replaced when a new project is created. 

https://user-images.githubusercontent.com/86290556/126328044-68254c13-5bd4-4684-a25a-c954aec9008a.mov

The critical implication is that the current project is closed automatically and changes to it are not saved.
It is also not possible to open multiple new scores within the same project window.

**Expected behavior**
Newly created projects should be visible under new tabs alongside projects already open. 
Projects already open should remain open when a new project is created.

Apple MacBook Air M1 MacOS 11.4
Windows 10 ARM in Parallels

**Comment by igorkorsukov** [comment]
Before that, we decided that only separate parts of the current project open in new tabs.
We can open several windows and open a separate project in each one.
Here is the procedure for opening a project https://github.com/musescore/MuseScore/pull/8778/files#diff-d90a84fb3a6627d9390c84560ec5f235e233c1cf1929c69aed8979a196d86a27R92

**Comment by bkunda** [comment]
Does this mean that new projects **only** open in new windows?

**Comment by igorkorsukov** [comment]
1. If the project is already open in the current window, then just switch to showing the notation
2. Check, if the project already opened in another window, then activate the window with the project
3. Check, if any project already opened in the current window, then we open a new window!
4. Else, open project in the current window

**Comment by bkunda** [comment]
Ok, this explanation makes sense to me. Thank you

**Comment by bkunda** [comment]
Hi @igorkorsukov,
I have just noticed an issue related to this one, which is as follows:
Now that we can open multiple projects, each in their own separate window, it seems that each project also has to be closed separately in order to fully "quit" MuseScore. In other words, I can no longer just hold Cmd+Q and quit the entire program in one go; instead, I have to do this for every single open project/file. 
I would like to suggest that the user still be able to completely "quit" the application MuseScore with just one command, which would affect all open projects. 
Thanks!

**Comment by igorkorsukov** [comment]
@bkunda At the moment we can quit:
1. By click on the window close button
2. By click on File->Quit
3. By active shortcut Cmd+Q

When should we close only the current window? and in which all windows?
Probably in 1 case only current ones, and in 2 and 3 all windows?

**Comment by bkunda** [comment]
Hi @igorkorsukov,
Yes I think you're right here.
I would expect File-->Quit and Cmd+Q to close all windows simultaneously (with the relevant "save changes" dialog appearing as appropriate). 
The window close button would just close the selected window (again, triggering the "save changes" dialog).
Thanks! 🙏🏻
