### ISSUE TITLE
[MU4 Issue] If select Tie element, hold Shift keyboard button and click on note > unselected tie and note

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8677]
**Describe the bug**
If select Tie element, hold Shift keyboard button and click on note > unselected tie and note
Pressing shift button (when selected Tie element) and clicking on note unselect all elements

**To Reproduce**
1. Create a score with tie element 
2. Select "tie" element 
3. Press and hold SHIFT button on your keyboard and click on any note

**Expected behavior**
Tie element should be selected with note (two elements selected)

**Screenshots**
https://user-images.githubusercontent.com/71372310/126396854-884efd33-2cf4-4bcb-9113-503477741519.mp4

**Desktop (please complete the following information):**
Windows 
MacOS

**Additional context**
Tie element still selected somewhere in the code when we see it unselected on the score
Selecting Tie and note with CTRL works fine, but doesn't work with SHIFT

**Comment by wizofaus** [comment]
That's the same as in as MU3.6 though? A range can't logically include a tie and just one note...

**Comment by HemantAntony** [comment]
Like @wizofaus said, I also think this is intended. Its not just a slur too. I tried it with an accidental and got the same result. So maybe this should be closed?
