### ISSUE TITLE
"Bar Properties" dialog needs porting to MS4

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8680]
The "Bar Properties" dialog is not yet accessible in MS4. 

<img width="637" alt="Screenshot 2021-07-21 at 17 59 07" src="https://user-images.githubusercontent.com/86290556/126465026-f9fad1bc-d990-4e76-ba79-882b20a3ae57.png">

This dialog should be accessible by right-clicking an empty space in a measure and selecting "Bar Properties" from the context menu that appears. 

**Expected behavior**
The above pictured dialog is triggered when the user right-clicks an empty part of a measure and selects "Bar Properties" from the context menu that appears. 

<img width="545" alt="Screenshot 2021-07-21 at 19 22 58" src="https://user-images.githubusercontent.com/86290556/126465284-c9074055-5a43-428d-a259-ee98430f13ab.png">

Macbook Air M1 running iOS11.4
Repeated in Windows 10 ARM (via Parallels)

**Comment by Jojo-Schmitz** [comment]
It is "Measure properties" (bar is the UK term)  ;-)

**Comment by bkunda** [comment]
"Measure Properties" is indeed how this dialog is described in the handbook. Evidently a discrepancy in the terminology here as MS3.6 calls is "Bar Properties"!

**Comment by wizofaus** [comment]
You can change your language to US-english and it will call it "measure properties".
I'm not a big fan of having command/dialog titles change like that between regional variations of English TBH, took me a while to work out why it was sometimes called "staff" and other times "stave" (I found the use of "stave" for a single staff a bit odd, even if it has the advantage of having a regular plural).

**Comment by Jojo-Schmitz** [comment]
Two nations divided by a common language...

**Comment by wizofaus** [comment]
Well I'm from neither, and while I prefer using *most* GB terms (bar, quaver, crotchet etc. - it's only "stave" I think is weird), when dealing with software and other international users I'm happy to stick to US terminology. Though I don't get why they don't call them 'measure lines'.

**Comment by Jojo-Schmitz** [comment]
Both languages have their inconsistencies. Actually probably all langauages have their inconsistencies.

An Aussie translation might be missing, not sure.

**Comment by wizofaus** [comment]
I do rather like quasihemidemisemiquaver though. Would almost classify as a respectfully decent length word even by German standards, no?

**Comment by RomanPudashkin** [comment]
I'm working on this issue
