### ISSUE TITLE
MuseScore crashes when opening files

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8681]
MuseScore crashes when user opens a file, either from File > Open or from within the home tab.

See video for demonstration: https://www.dropbox.com/s/zehw2m55ysc1diy/ms-crashes-on-open-score.mov?dl=0

I was able to reproduce this in Windows 10, and also after system reboot.

**To Reproduce**
1. Open MuseScore 4 (latest nightly build)
2. Select File > Open
- MuseScore crashes

1. Open MuseScore 4 (latest nightly build)
2. Select an existing score from Home tab > Scores > New & recent
- MuseScore crashes

**Expected behavior**
MuseScore should not crash when scores are opened.

MacBook Air M1 MacOS11.4
Windows 10 ARM (via Parallels)

**Comment by vpereverzev** [comment]
fixed in https://github.com/musescore/MuseScore/pull/8679
