### ISSUE TITLE
Palette elements have incorrect default scaling and positioning

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8690]
Palette elements are appearing by default at a very small size and with incorrect alignment.

<img width="918" alt="Screenshot 2021-07-22 at 20 51 26" src="https://user-images.githubusercontent.com/86290556/126628402-5ae739fd-d059-48d1-8e5a-b43d0b747a5f.png">

<img width="666" alt="Screenshot 2021-07-22 at 20 52 30" src="https://user-images.githubusercontent.com/86290556/126628430-8361b6ce-1387-4bc7-bc65-e82f2c328155.png">

**Expected behavior**
By default, icons should be centre aligned (vertically and horizontally), and scaled at 1.00, as they are in MS 3.6:

<img width="241" alt="Screenshot 2021-07-22 at 20 57 31" src="https://user-images.githubusercontent.com/86290556/126628894-5f03f238-1294-45ef-99b3-6cbcf81a9753.png">

Apple MacBook Air M1 MacOS 11.4

**Comment by cbjeukendrup** [comment]
I found the fix; it was a high resolution issue. I will create a pull request soon, with some more fixes.
