### ISSUE TITLE
[MU4 Issue] Empty Menu Bar popup windows appear and stay opened until closing MU (in some combination of mouse and keyboard actions)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8697]
**Describe the bug**
Empty popup windows from Menu Bar appear and stay opened until closing MU (in some combination of mouse and keyboard actions)

**To Reproduce**
Mouse click and navigation with Tab

https://user-images.githubusercontent.com/90187801/142026012-4216bf9d-c8ec-44f3-8cfa-6b1b602f54b3.mp4

Mouse click to invoke Add menu and Esc to close popup

https://user-images.githubusercontent.com/90187801/142027562-3e9c4e2b-b656-4251-9df9-be970a71cf1b.mp4

**Desktop:**
 Windows 10 / Linux Mint 20.2

**Comment by DmitryArefiev** [comment]
Tested #10235 on Win10, Mac12, LinuxMint 20.2 - FIXED
