### ISSUE TITLE
[MU4 Issue] After changing instrument it sounds like the old one

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8700]
**Describe the bug**
After changing instrument it sounds like the old one

**To Reproduce**
1. Create a score with one instrument
2. Add notes
3. Click Instruments tab from Instruments Panel
4. Click Options button on instrument
5. Click "Replace instrument"
6. Select another instrument
7. Play score

**Expected behavior**
Score should be played with new Instrument notes 

**Screenshots**
https://user-images.githubusercontent.com/71372310/126749785-50a244b1-2f02-4f27-a015-3c2fed5f49c7.mp4

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by wizofaus** [comment]
Confirmed this is still occurring, are there meant to be any unassigned P1 issues @Tantacrul ?

**Comment by Tantacrul** [comment]
I can see Vasily has added it to his list of 'to do's' for playback. A lot (if not all) the playback issues relate to the system he is building at the moment. 

I've assigned it to him for good measure. Cheers!
