### ISSUE TITLE
[MU4 Issue] Text position displaced after clicking on it in random cases

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8701]
**Describe the bug**
Text position displaced after clicking on it in random cases

**To Reproduce**
1. Create a score with text
2. Click on text and try to change it`s position

**Expected behavior**
Text should not change it`s position automatically when user click on it

**Screenshots**
https://user-images.githubusercontent.com/71372310/126751531-e640f6bf-65cc-4e5b-b9ad-71638207584d.mp4

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Low reproducible rate

**Comment by Tantacrul** [comment]
I'm convinced this bug is a troll. First it contains the word 'random' and has a video that I can't comprehend :D

Closing!
