### ISSUE TITLE
Click and drag not working for multiple selections

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8702]
Selecting multiple objects (with ctrl/cmd+click or shift+click) and then clicking on one of the selected objects to move the entire selection **only** moves the last clicked-on object.

https://user-images.githubusercontent.com/86290556/126751486-6d745e63-fb6c-4d79-909f-f6c784f3e625.mov

**Expected behavior**
Clicking on any movable object from a group of selected objects should move the **entire** group of selected objects (even without any key being held down).

Macbook Air M1, MacOS 11.4
Reproduced in Windows 10 ARM (via Parallels)

**Comment by DmitryArefiev** [comment]
Tested in **latest master** on Win10, Mac12, LinuxMint 20.2 - **LOOKS GOOD**

Closing

**Comment by DmitryArefiev** [comment]
@bkunda Please reopen if I missed something ;)
