### ISSUE TITLE
[MU4 Issue] Crash if open Part and switch to Main score and then to the Part

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8704]
**Describe the bug**
Crash if open Part and switch to Main score and then to the Part

**To Reproduce**
1. Create a score
2. Create a part (Open Parts dialog > click on a part > click Open button)
3. Switch to the Main score
4. Switch to the Part score 

**Expected behavior**
Switching between Main score and Parts should not cause a crash

**Screenshots**
https://user-images.githubusercontent.com/71372310/126753555-2c88bc40-4e16-4799-af6c-595faea1fc4b.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/8830
