### ISSUE TITLE
[MU4 Issue] Brackets, Braces and Parentheses under "Accidentals" tab are rendered with a near-black color

### ISSUE THREAD

**Issue by ArjunBoi** [musescore/MuseScore#8714]
The Brackets, Squiggly Braces and Parentheses in the "Accidentals" dropdown under the "Pallete" menu receive a near-black color which makes them impossible to see in High-Contrast modes (and in Dark mode as well).
 

1. Go to "Pallete"
2. Click on "Accidentals" dropdown

**Expected behavior**
Going by the color of its peers, it should be rendered with the primary font color instead.

**Screenshots**
![HC_Black_Palette](https://user-images.githubusercontent.com/72261568/126807163-b2617417-fcb4-40f6-bd89-04067cf06f1e.png)
*The tab in High-Contrast Black*

![HC_White_Palette](https://user-images.githubusercontent.com/72261568/126807246-092e65a5-72fb-41a1-916e-3ddbe94742de.png)
*The tab in High-Contrast White*

![Screenshot from 2021-07-19 20-09-44](https://user-images.githubusercontent.com/72261568/126807279-12a55a9c-33dc-4288-86ce-9f8b59a1133f.png)
*The tab in Dark mode*

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)

**Comment by cbjeukendrup** [comment]
I'm working on a fix!
