### ISSUE TITLE
[MU4 Issue] Note selector jumps left (on a note) if select note and click on Voice 1

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8737]
**Describe the bug**
Note selector jumps left (on a note) if select note and click on Voice 1

**To Reproduce**
1. Create a score
2. Add note on the score
3. Click on a note
4. Click Voice 1 button from the Note Input Bar

**Expected behavior**
Note selector should stay to the right of the note

**Screenshots**
https://user-images.githubusercontent.com/71372310/127181223-00990f17-8e71-41f2-8abf-9927837d2702.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by Tantacrul** [comment]
I'm not sure why this happens but I don't care that it does. It also does this in MS3. I'm pretty sure it is resetting to the start of the measure to save time when changing voices.
