### ISSUE TITLE
[MU4 Issue] Notes can be added on the score during Playback (when Note input triggered via N or clicking Pencil icon)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8739]
**Describe the bug**
Notes can be added on the score while score Playback works

**To Reproduce**
1. Create a score
2. Click on pencil (to select pencil and notes) from the Note input bar
3. Click "Play" button from playback panel 
4. Click on the score > notes added while score is playing

**Expected behavior**
Possibility to add notes should be blocked when score is playing

**Screenshots**

https://user-images.githubusercontent.com/71372310/127183431-61368bd1-0214-412b-be7c-b5bf72af1118.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by wizofaus** [comment]
Actually that sounds like a very useful feature!  On playback you may well notice various errors that you could fix quickly while it's still playing. But I'm not sure what should happen if, for instance, you add or delete large amounts of music after the playback cursor (i.e. would it be able to rebuild the playback and continue playing? Or just play whatever was there before, but that could cause some odd mismatches, esp. if you've deleted all the music that it's still trying to play).

**Comment by Tantacrul** [comment]
Not anymore. Fixed. Closing.

**Comment by wizofaus** [comment]
What do you mean "not anymore". The "issue" as reported still exists - you can still add new notes and change notes while playback is in progress (just not using the toolbar, which is disabled, but with the mouse or keyboard), but as far as I can see it doesn't cause any problems...

**Comment by Tantacrul** [comment]
Ah, the issue description didn't make that clear. I thought it was about the UI itself.

By 'not anymore', I meant 'not anymore'. Try, if you possibly can to not be incessantly insufferable @wizofaus

**Comment by wizofaus** [comment]
I'm actually genuinely curious as to why this isn't considered a useful feature - if were crashing or doing something very unpredictable I'd agree it's probably best preventing (it can be a *little* bit unpredictable, changing the current playback cursor position etc., but not badly so).

**Comment by HemantAntony** [comment]
Won't it be annoying if you remove the ability to add notes during playback? When you hear something you don't like, you will have to turn playback off first and then make the changes after which you continue playback

**Comment by wizofaus** [comment]
Agreed,  but maybe it introduces instability into the playback system.  I'd sacrifice the ability to edit during playback for software that doesn't crash!

**Comment by Tantacrul** [comment]
Is the ability to enter notes during playback causing crashes?

> Agreed, but maybe it introduces instability into the playback system. I'd sacrifice the ability to edit during playback for software that doesn't crash!

**Comment by Tantacrul** [comment]
I guess this could _**possibly**_ be useful although I worry users may accidentally find themselves in note input more and be placing new notes on their score without realising.

If the feature is causing crashes, we should disable it for now. If it is reasonably harmless, I don't have a problem with potentially releasing with it and seeing what comes back.

**Comment by HemantAntony** [comment]
I don't think there an crashes related to this.

Also, users will realise when they add notes accidentally because playback restarts from the added note.

**Comment by Tantacrul** [comment]
> I don't think there an crashes related to this.
> 
> Also, users will realise when they add notes accidentally because playback restarts from the added note.

I'm not so optimistic. On an orchestral score, you could be adding all kinds of notes to woodwinds without realising (and hearing)

**Comment by wizofaus** [comment]
I guess I'd hope that it should be obvious you've added/modified notes even if you have sound off (can't find your headphones and other people around not wanting to be disturbed!). Being able to modify the score during playback seems like a good thing to me. What does Sibelius/Dorico/ Finale etc do?

**Comment by HemantAntony** [comment]
@Tantacrul Is there a final verdict? :)

**Comment by Tantacrul** [comment]
Oh, I'm very much in camp **disallow adding notes during playback**

**Comment by DmitryArefiev** [comment]
Replace the current issue to #17360 (to have two cases in one bug).

Closing
