### ISSUE TITLE
Navigator should be resizable

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8758]
The navigator opens with only a transparent window and does not show a preview of the score. - FIXED

Navigator is also unable to be resized. - **STILL OCCURS**

It does seem to respond to mouse click and drag, but triggers a crash shortly thereafter. - FIXED

Demonstration video:

https://user-images.githubusercontent.com/86290556/127492626-ca42a9b7-0874-41a2-826f-ba6fd7954d68.mov

**Expected behavior**
Score should be visible within the navigator.
Navigator should be resizable.
Click and drag through the navigator should not trigger crash.

Macbook Air M1 MacOS 11.4

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - Now Navigator shows a the score and doesn't trigger a crash but it's **STILL NOT RESIZABLE**

Changing priority and summary

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
