### ISSUE TITLE
Note input colour is incorrect

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8769]
The note cursor in note input mode is currently using a very bright green instead of the correct shade of blue.

Incorrect colour in MS4:

https://user-images.githubusercontent.com/86290556/127651143-13e135ef-3874-475b-b6ce-09ae8f7f5c2e.mov

Correct colour in MS3.6

https://user-images.githubusercontent.com/86290556/127651179-587cf670-71aa-4935-83be-220f7dcc41ff.mov

**Expected behavior**
The note input colour should match the current colours used in MS3.6.

MacBook Air M1, MacOS11.4

**Comment by cbjeukendrup** [comment]
I'm working on this!

Also, the note input colour should take the voice colour into account. In MU3, the colour was calculated by making the relevant voice colour 35% lighter. Of course I could just replicate this behaviour in MU4, but we could also just take the voice color with something like 0.7 opacity. How about that?

**Comment by bkunda** [comment]
Thanks Caspar! That sounds like a logical solution to me 🙂
