### ISSUE TITLE
[MU4 Issue] Tablature instrument not added as expected 

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8774]
**Describe the bug**
Trying to add a guitar tablature staff via the "Inspector" panel creates a regular staff instead

**To Reproduce**
1. Create score using default treble clef template
2. On Instruments panel, click "Add"
3. Search for Acoustic Guitar (tablature)
4. Click [ -> ]
5. Click OK (NB: OK and Cancel are the wrong way around in Windows here! Standard is always to have cancel as the rightmost button in Windows, as per File|Open etc.).
6. New staff is shown but is a standard staff, not tablature

**Expected behavior**
Guitar tablature staff should be added to the score.  Ok button should be left of Cancel on Windows.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - 
**Additional context**

**Comment by bkunda** [comment]
Reproduced in MacOS, where it seems the problem is affecting all tablature staff instruments.

**Comment by DmitryArefiev** [comment]
![Tab staff missing](https://user-images.githubusercontent.com/90187801/134491440-a732d097-fa9c-4d5f-a9f7-13de55b81a53.gif)

**Comment by bkunda** [comment]
I have escalated this to P1. Tablature is critical core functionality.

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9982

**Comment by DmitryArefiev** [comment]
Tested on master build (Win10, Mac11, LinuxMint 20) - FIXED
