### ISSUE TITLE
[Inspector] Tabs have incorrect (inverted) styling

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#8805]
### Bug
The styling for selected and unselected tabs is the wrong way around, so a selected tab ends up looking unselected and visa versa. This problem is more pronounced in Dark Mode (which is strange)

Here's how it should look (see Figma) - notice how the selected tab is using 'TabBold', with no opacity and the unselected tabs are using the text style 'Tab' with 60% opacity.
![image](https://user-images.githubusercontent.com/21022311/128499094-2c8a3c1b-3186-45cc-b2bd-8622b29c6d92.png)

Here's how it looks in MS4. Both are using the 'TabBold' style and something has gone wrong with opacity. (Ignore the different accent colour!)
![image](https://user-images.githubusercontent.com/21022311/128498120-b1e2c036-83ac-4b7e-8f3e-fe41ccdec3fc.png)

**Comment by cbjeukendrup** [comment]
I believe @sidharth-anand said in his blog post that he had fixed this, but he has not yet pushed it to his PR. But, as I mentioned earlier, TabPanel needs to be rewritten completely because it uses the deprecated `QtQuick.Controls 1`. I don't know whether Sidharth has done this too.

**Comment by Tantacrul** [comment]
OK, I'll wait on @sidharth-anand to comment. I initially thought it was a unique styling problem but I obviously didn't look wide enough to realise it was across the app.

**Comment by RomanPudashkin** [comment]
@cbjeukendrup 

There is already StyledTabButton based on QtQuick.Controls 2. It is used in the new score wizard. I believe, we need to reuse it and remove the old component completely

<img width="431" alt="Screenshot 2021-08-06 at 15 14 20" src="https://user-images.githubusercontent.com/67867444/128515716-3cf6c971-6ff4-44fd-852f-3361c9791b06.png">

**Comment by sidharth-anand** [comment]
I wasn't aware of the StyledTabButton. I'll modify the tempo popup to use this instead. 
@cbjeukendrup I haven't rewritten TabPanel, but I could do it once I'm done with the fixes. Should I use QML's `TabBar` since, `TabView` doesn't seem to exist in QtQuick 2?

**Comment by cbjeukendrup** [comment]
Yes, you need to use TabBar together with StyledTabButton and StackLayout. TabBar works significantly different from TabView, so take for example a look at ChooseInstrumentsAndTemplatesPage.qml.
