### ISSUE TITLE
Unintended scroll behaviour when hovering over dropdown menus 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8807]
Scroll behaviour is triggered by hovering over certain dropdown menus (no click required).

See demo video here: https://www.dropbox.com/s/4rd9can00m40rt9/unintended-scroll-1.mov?dl=0

Reproduced on:
- Preferences > Appearance > Font Face
- Preferences > General > Languages
- Edit Drumset > Notehead Group
- Format > Style > Score > Musical Symbols Font

**Expected behavior**
Scrolling through dropdown menu items should only be allowed when the dropdown menu has been opened. 

MacBook Air M1, MacOS 11.4

**Comment by ArjunBoi** [comment]
I raised this issue a while back as well, but i was told by @igorkorsukov that this is a feature? 🤔

**Comment by bkunda** [comment]
I contend that this is a problematic issue: in my case, I was using my trackpad to scroll down the Preferences > Appearance menu, and when I hit the font face drop down I not only began to change the fonts everywhere, but my downwards scroll to the bottom of the window was interrupted by the dropdown. I would say this should not be a feature.

**Comment by ArjunBoi** [comment]
As someone who has been working on that specific menu (i.e. Preferences -> Appearance) for the past month and half, I have encountered this exact behavior countless times, where the dropdown element steals focus from the rest of the page and scrolls through its elements instead. There is also a visible stutter when this happens.
Excited to see this get fixed!

**Comment by Mystic-Slice** [comment]
Yes! This is even more frustrating in places where the dropdown fills the entire width of the container (like in Inspector>Text>Font). This behaviour makes it impossible to scroll normally. I have to use the scrollbar every time.

**Comment by igorkorsukov** [comment]
If we work with the mouse, then this behavior is very convenient, I use this behavior of drop-down lists in many programs.
If we do not want this behavior, I will remove this feature.
