### ISSUE TITLE
Text editing interaction regression: clicking on text is harder and text selection is semi-broken

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#8812]
### Bug
The ability to select different parts of a selected text box is significantly harder in MS4.

### Problems:
See video here. Please note that the first example (where it is working) is MS3. The second example is MS4.
https://www.dropbox.com/s/kqsncswr7t6lk83/Check_out_insertion_point_rubbishness.mov?dl=0

- Compared to MS3, when editing text, the user can't click to reposition the insertion point. It just deselects the text field.
- When editing text, you can't click and drag to select a range of text. Again, it just exits the editing mode

Mac OS - Catalina

**Comment by wizofaus** [comment]
Line 366 of notationviewinputcontroller.cpp
`        if (!hitElement || !hitElement->isText()) {`

needs to be `isTextBase()`.

I have this fix on the branch I'm working on but it won't ready for a while.

**Comment by vshalkevich** [comment]
Cant reproduce
