### ISSUE TITLE
[MU4 Issue] Text properties panel focus/update issues

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8813]
I'm working on a fairly radical overhaul of the text editing to fully implement the intended design where the text properties panel fully replaces the "text editing" toolbar shown in MU3.
But there's at least a few behaviours I'm not really sure how to fix, and they're basically independent from what I'm working on:
a) in MU3 while editing text you can click on bold/italic/underline toggles on either the toolbar or inspector and the focus remains on the textbox, allowing you to keep typing (including navigating with the keyboard).  In MU4 the way Qt is being used it's not obvious how to achieve this.
b) similarly, you can click on a control in the inspector and/or text editing toolbar that can grab the focus (e.g. font face or size dropdown) but then hit ESC to return focus to the text element being edited
c) there's a specific bug with the update of the dropdowns in the Properties panel such that when you select a value from a dropdown (at least, the font face and font size dropdowns), it remains stuck on that value and won't update when the underlying property value is changed when selecting a different element on the score.  If the properties panel is reconfigured to remove that dropdown and it then gets re-added (e.g. selecting a non-text element then back to a text element) it starts working again, correctly updating depending on what element is selected.  The underlying C++/model code seems to be fine.

NB I did manage to fix the "reset"/"save as default style" buttons that weren't working due to a bug in the QML (should have been itemId vs just id in InspectorPropertyView.qml's onHandleMenuItem)

**Comment by Tantacrul** [comment]
I believe we have moved beyond this now. If not, we should open individual issues for each problem.

**Comment by wizofaus** [comment]
All this problems still exist and I believe are all connected, at least a) and b) - do you really want me to create 3 separate issues?
@Tantacrul

**Comment by Tantacrul** [comment]
Well, let me put it like this. We can't fix that which is not described well.

1. Don't know what your question/concern is. I can think of what it _might_ be. You can see where I'm going with this. This is issue reporting 101.
2. Again. Don't know how exactly to action this.
3. This I understand... and I _thought_ had been fixed.

Basically: if you want us to fix it, log as separate issues - in a way that doesn't require us to spend ages trying to understand what you mean.

**Comment by wizofaus** [comment]
Is this better? https://github.com/musescore/MuseScore/issues/11930
