### ISSUE TITLE
[MU4 Issue] Pasting notes onto rests not reliable

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8824]
MU4's behaviour was changed so that when copying and pasting notes, the length is preserved, however it's not reliable currently.  Especially when pasting onto a MM rest (which crashes).

**To Reproduce**
1. Create an empty score
2. Add a 1/4 note to the first measure
3. Copy it to the clipboard
4. Turn on multi-measure rests
5. Select the multi-measure rest and paste
6. MuseScore crashes

However there's a bunch of other problematic behaviours when copying/pasting notes/rests on to existing notes/rests

**Expected behavior**
a) Pasting a note on to a multi-measure rest should behave the same as pasting onto a whole rest, but with the measure pasted into no longer included in the multi-measure rest (as it's no longer empty)
b) Pasting a single note on to a single rest of the same duration: should just convert rest to note (works now, except attached articulations etc. are lost - what logically should be kept?)
c) Pasting a single note on to a single rest of a longer duration: should add note with copied duration and pad out rest (mostly works now, except for articulations, though I did see it misbehave once or twice)
d) Pasting a single note on to a single rest of a shorter duration: should add note with copied duration and remove whatever subsequent note/rests occur within the pasted duration period
e) Pasting a single note on to a single note of the same duration: should just replace note
f) Pasting a single note on to a single note of a longer duration: should replace note with copied note and pad out with rests (to confirm?) - not what's happening now, the note gets split up unexpectedly.
g) Pasting a single note on to a single note of a shorter duration: should replace note with copied note and remove whatever subsequent note/rests occur within the pasted duration period (similar to pasting a range onto a selected range of a shorter duration)
h) Pasting a single note on to multiple (list-selected) rests/notes - tricky one, currently this doesn't work properly unless the note is exactly the same duration as all the target rests.  Logically this needs to allow for cases where the selected targets get replaced - e.g. if you select two consecutive 1/8 rests (or notes) and paste a 1/4 note onto them, the only sensible thing to do is replace both with the single note. But if the 1/8 rests/notes are separated by more than an 1/8, you can sensibly convert both of them to the note being pasted.
i) Pasting a single rest on to a note/rest - not sure, currently this does nothing in MU3 or MU4.
j) pasting a single note/rest onto a selected *range* - not sure, currently this does nothing in MU3 or MU4.
k) pasting a list-selection of notes/rests on to anything - not sure, currently this does nothing in MU3 or MU4.
l) pasting a range selection onto a single note/rest - works fine, same if the single target note/rest had been a range
m) pasting a range selection onto a list of notes/rests - Mu3 error "no destination to paste" (!)
n) copying a chord - actually there appears to be no way of even selecting a single chord and putting it on the clipboard! Only a range containing one chord.
o) pasting a single note on to an individually selected note in a chord of the same duration: chord should remain with updated note (but what if it's the same pitch as a note already in the chord? What if the chord already has *2* pitches at that note?)
p) pasting a single note on to an individually selected note in a chord of a *different* duration: not sure, but easiest is to replace the whole chord with the note (padding out with rests if necessary)
q) pasting a note longer than the measure containing the selected target note: should split note over measures as necessary (to test properly, copy the note from a measure with a time signature greater than that you're pasting into, e.g. a double-whole note from an 8/4 measure onto a note/rest in a 3/4 measure)
r) copying/pasting a note should always preserve all note properties that can be changed via the inspector or the piano roll editor (including playback duration, velocity etc.)
s) tuplets....aarghhh...correctly preserving the duration of a copy & pasted tuplet note is not trivial at all, even if it is potentially useful...for now I have it so that only the note-head duration is preserved, regardless of what sort of tuplet it was originally part of, or pasted on to.  Which is possibly not always what would be expected, but if you do need to "keep" whatever sort of tuplet you're pasting from at the destination (including not-a-tuplet), you can always delete the destination tuplet first, and re-create if necessary.  Also I'd added an exception for the case of pasting a note longer than the tuplet being pasted on to, in that case, the tuplet is replaced entirely. So if you paste a 1/2 note onto a triplet of 3 1/4 notes, the tuplet is preserved (the first note is changed to a 1/2 note inside the triplet), but if you paste a dotted 1/2 note or longer, then tuplet is replaced entirely.  If you really did mean to just paste the 1/2 note as is, not part of a triplet, you have to remove the tuplet first (which is a little painful, it seems you have to select all notes in the tuplet and delete.
t) pasting a note too long to fit on the score (e.g. pasting a whole note into a final 2/4 measure), currently the note is truncated, just as it is when adding from the note entry toolbar.  But I would expect the score to be extended, as per what happens when pasting a single note selected as a range.  In fact in general it's questionable whether pasting a range containing a single note should ever behave differently to pasting just the note itself, but internally they are two very different operations (as a note itself doesn't even have any duration), and there are some cases where the differences are useful.
u) pasting a note such that a tie is required - e.g. pasting a whole note into a 2/4 measure:  a note of the maximum duration permitted by the time signature will be created with all the same properties as the pasted note (except notated duration!), and extra notes created and tied to as necessary to represent the equivalent duration. The extra notes should take on the properties of the pasted note where logical (e.g. color, stem direction, cue note etc.)
v) can't believe I'm up to "v", but there are some real edge cases like pasting a whole note onto a half note that's followed by a half-note tied to a subsequent note. Currently this just replaces the first two half notes, breaking the tie and leaving the subsequent note in place. But this is a bit inconsistent with what happens if pasting onto notes of the same effective durations but that don't need a tie (due to the time signature etc.), where the entire second note is replaced, and the gap padded out with rests as necessary.   But tied notes aren't exactly equivalent to notes of the same effective duration notated without ties - for a start, you can paste *onto* the 2nd of a pair of tied notes (which again requires breaking the tie), but you can't paste "half way" through a single note.
w) gonna run out of letters soon... paste double/half duration should work as expected for single notes.

...more to come

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by wizofaus** [comment]
I have this working pretty well for most cases now, but the behaviour when you paste a note of one length on to a list selection of multiple notes/rests of different durations is perhaps not all that expected/useful - basically it replaces each note in turn, obviously then having to skip ones that were deleted by the previous paste.  It's not *wrong* and produces a musically meaningful result, but the code to support it is probably more complex than can be justified by the usefulness of it!
Also I notice that even now (in MU3), if you select a *range* that's, say, a single 1/8 note, and paste it onto, say, a whole note (either selected individually or as a range), the result is a bit odd - it breaks the whole note up into shorter durations without tying them together.   I would think it's arguably better just to replace the whole note with the 1/8 note and pad out with rests - after all, you normally expect things to be replaced when you paste onto them. That's a relatively easy change to make.
@Tantacrul

**Comment by Tantacrul** [comment]
Did a bit of testing on some other notation apps this morning.

Regarding your list above. I agree with points A-G

Point H: If the user copies one quarter note and then selects a range of, say, notes and rests and then presses paste. I think we should simply paste the note on the _first_ element that was selected and ignore all others.

Point i: rests should be allowed the same copy & paste behaviour as notes - following the rules set out in points a-g. If I select a 32nd rest and paste is on a quarter note, it should replace the quarter note (as a 32nd rest) and the rest of the duration should be padded out with the appropriate rests. It can actually be quite useful to allow this.

Point j: Same as point H.

Point K: I'll need to show you how I think this should work. Too complex via text.

---

The rest are more complex and would benefit from a video call. Would be much faster :)

**Comment by Jojo-Schmitz** [comment]
in a) I hope you mean "measure rest", not "whole rest", do you? Anyway, guessing the desired result is probably wrong as often as right (like you might want to cope the chord instead, or really a (serias of tied) note(s) as long ts the MMRest, so I'd just not allow for it at all.

**Comment by wizofaus** [comment]
Yes you're right,  "whole measure rest", though for 4/4 the result is the same obviously.  But a multi measure rest shouldn't be a special case, it's just a different way of showing measures that are empty in all staves.

**Comment by wizofaus** [comment]
Re pasting a single note onto a selected list (or range) of elements - I'm not sure I agree it's better to just act as though as it's pasting onto the first element only.  Basically "paste" is like a special version of "add element from palette", except it's adding from what's on the clipboard, and if you select, e.g. a _**f**_　dynamic and copy to the clipboard, you can then paste it on a whole list of different notes and it will add it to all of them, the same way it does when adding from the palette. Having said that...
a) it doesn't work like that for ranges currently. e.g. adding a hairpin to a selected range from the palette behaves as expected, but pasting one from the clipboard does nothing.
b) it doesn't work for all types of elements currently even when adding to a list selection, e.g. not even grace notes, which might be useful (if you have an existing grace on the score and you want to add the same grace note to a number of other notes, doing it as a single copy/paste operation would be nice).  But it does work well for a most element types, and is useful because it's often quicker to find an existing element on the score than in the palettes.
c) it's not super consistent with how copy/paste works in most other applications where the expectation is that what's on the clipboard *replaces* what's selected, but a reasonable approximation is Excel - if you paste one cell onto multiple cells, it duplicates the contents across all of the selected cells.
@Tantacrul
