### ISSUE TITLE
Bottom part of score is being cropped out in main project window and new score preview

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8827]
For large scores with many staves, the bottom part of the score is being cropped out/cut off. 

<img width="2022" alt="Group 3" src="https://user-images.githubusercontent.com/86290556/128855831-bda37b08-6ce6-4e73-b3a7-4e36e1847c60.png">

Expected behaviour: the above score should look like this:
<img width="1939" alt="Screenshot 2021-08-10 at 20 58 46" src="https://user-images.githubusercontent.com/86290556/128855851-cdfb236f-3b5e-4543-8fd5-6397abc9274f.png">

Tested on templates for:
- Symphony orchestra
- All band and percussion (except battery percussion)

Also tested on a user-defined score (i.e. not a template) with 19 instruments (20 staves): cut-off was after staff 15.

MacBook Air M1, MacOS 11.5.1

Additional context: 
I noticed this problem can be (kind of) addressed by changing to a larger page size in "page settings". In MS3.6, however, the score scales to whatever page size is selected. This means that page size should not crop out staff content. 

Note:
This issue was not occurring in nightly build from 6 August 2021

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
