### ISSUE TITLE
Double-click in drumset panel does not enter notes as expected

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8828]
Double-clicking on a button in the drumset panel currently does not enter any notes in the score. 

<img width="671" alt="Screenshot 2021-08-10 at 21 38 32" src="https://user-images.githubusercontent.com/86290556/128860577-c5c6b89d-4dc3-45fc-9eaa-b1c02ea306b0.png">

Expected behaviour:
In MuseScore 3.6, double-clicking on any of the panel buttons enters a note directly into the score. This behaviour should also happen in the current MS4 builds

MacBook Air M1, MacOS 11.5.1

Additional context:
We are designing upgrades to the drumset panel, as well as to note entry. While this design process remains ongoing, this issue is being reported to ensure that percussion functionality at least operates as per MS3.6.

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/10719
