### ISSUE TITLE
Staff brackets are not resizable

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8836]
Double-clicking a staff bracket shows a tiny handle that doesn't respond to click and drag.

See video for demonstration (and comparison with expected behaviour from MS3.6): https://www.dropbox.com/s/xfmx9rmkf2xiq1y/Brackets%20not%20resizable.mov?dl=0

**Expected behavior**
1. The resize handle should be visibly larger (as per MS3.6)
2. The resize handle should respond to click and drag with mouse

MacBook Air M1, MacOS 11.5.1

**Comment by cbjeukendrup** [comment]
Point 2 relates to #8694.

**Comment by wizofaus** [comment]
The fix for handles was wrong though, was only working for brackets (or any element) on the first page.  Can't reproduce the tiny handle problem though, it's fine on Windows.

**Comment by HemantAntony** [comment]
For me, the resize works on all pages and the handle looks good too. So, I think this issue is fixed

**Comment by bkunda** [comment]
Agreed @HemantAntony, this does seem to be fixed now. Closing this issue.
