### ISSUE TITLE
[MU4 Issue] Can`t change part name and Crash if open newly created Part

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8839]
**Describe the bug**
Can`t change part name and Crash if open newly created Part

**To Reproduce**
1. Create a score
2. Open Parts dialog
3. Click "Create a part" button
**Can`t change part name:**
4. Double click on newly created part
5. Enter Part`s name
6. Click enter
OR
**Crash if open newly created Part:**
4. Click on newly created Part
5. Click "Open" button

**Expected behavior**
It is possible to change Part name and open part without crash

**Screenshots**
https://user-images.githubusercontent.com/71372310/129200170-4c3a7bfe-8bee-4075-a072-d8c33b0e5c60.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by wizofaus** [comment]
Can't reproduce, seems to be OK now @vshalkevich ?

**Comment by vshalkevich** [comment]
Works fine now, thanks
