### ISSUE TITLE
[MU4 Issue] Score view displaces after switching from Score tab to Publish tab

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8840]
**Describe the bug**
Score view displaces after switching from Score tab to Publish tab

**To Reproduce**
1. Create a score
2. Click on Publish tab (it is located near Score tab)

**Expected behavior**
Score view should be the same on Score tab and Publich tab

**Screenshots**

https://user-images.githubusercontent.com/71372310/129200688-7eb5d87d-0569-4b15-89a7-9e6626f51e3d.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by DmitryArefiev** [comment]
Tested in master build on Win10, Mac12, LinuxMint 20.2 - **FIXED** (no longer occurs)


https://user-images.githubusercontent.com/90187801/160111775-f0d19892-6660-48f6-876a-9a63c7b7bfa7.mp4



Closing
