### ISSUE TITLE
[MU4 Issue] Reverted to Factory Settings works only after manually rerunning MU4

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8845]
Describe the bug
Reverted to Factory Settings works only after manually rerunning MU4

To Reproduce
    1) Click "Help" from the upper Panel
    2) Click on 'Revert to Factory Settings'

Expected behavior
Settings Reverted to Factory Settings  should be applied automatically at the same time as it was clicked

OS
Windows 10

**Comment by HemantAntony** [comment]
This appears to be fixed:

https://user-images.githubusercontent.com/88136054/155311597-b552e49b-286a-494c-b431-9eba60192004.mp4

**Comment by Tantacrul** [comment]
It still isn't fixed completely. Try removing a bunch of palettes and then repositioning windows (moving the inspector to the right), docking the note input bar vertically, etc. A restart is needed for those to be reset.

**Comment by HemantAntony** [comment]
@Tantacrul This is no longer applicable since you have to restart MU4 for changes to take place

**Comment by Tantacrul** [comment]
Thanks @HemantAntony !
