### ISSUE TITLE
[MU4 Issue] Context (right-click) menu for lines with grip handles hard to activate

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8851]
**Describe the bug**
Right-clicking on lines/slurs/etc. with grip handles doesn't reliably bring up the context-menu, if you right click too close to a grip handle (very easy to do for a small tie etc.).  In MU3 right-clicking on a grip handle still brings up the context-menu.
Especially annoying because there appears to be no short-cut to bring up the context menu (vs the Windows standard Shift+F10 which works in Mu3, actually many keyboards even have a dedicated shortcut menu key to the left to the spacebar which should work too)

**To Reproduce**
1. Add a note, and tie it to another one
2. Select the tie
3. Try to right click to bring up a context menu
4. Frequently context menu fails to show if you click too close to a grip handle
5. Hit Shift+F10 (or if your keyboard has it, the shortcut menu key)
6. Context menu doesn't show

**Expected behavior**
Context menu should always show providing you right-click anywhere within the bounding box of an element or use Ctrl+F10.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by wizofaus** [comment]
Fixing the problem of right-clicking on the grips is trivial, just switching the order of a few lines of code.

Getting the Shift+F10 (or for keyboards that have it, the "apps"/menu key) to activate the context menu - wow, took an hour of digging through the internals of Qt but *finally* got it to work with installing the PaintView as an event filter and handling the ContextMenu event, thusly:

```bool NotationPaintView::eventFilter(QObject* obj, QEvent* ev)
{
    if (hasFocus() && ev->type() == QEvent::Type::ContextMenu) {
        showContextMenu(m_inputController->selectionType(), m_matrix.map(m_inputController->hitElementPos().toQPoint()));
    }
    return QObject::eventFilter(obj, ev);
}```

hitElementPos() is a new function that returns the *center* of the last element selected.

@Tantacrul can you confirm this is the desired behaviour when using the keyboard to bring up the context menu - basically to ensure the top-left corner of the menu is in the centre of the last selected object? It's pretty close to what File Explorer and other applications do (I don't know if using the keyboard for the context menu is even a thing on Mac).  It's basically what MU3 does too - though it seems to find the center of *all* selected elements, which works OK for range selections for but list-selections where the elements are very far apart doesn't quite make sense.
The only remaining case is when nothing is selected, in which case the context menu is for the current page, and hence appears in the centre of it.

**Comment by wizofaus** [comment]
I also noticed the "Load style" from the context menu doesn't work, but this is true even when using the mouse and even from the menu Format menu, will log separately.
Another thing (that MU3 also does) is that it's not clear when you have elements selected but then right-click on a blank part of the page that the context menu does NOT apply to what's selected - in, say, File Explorer when you do this, the selected items effectively become unselected, though you can still see an outline of what the "current" item is (whereas MuseScore doesn't support having a "current" element that's unselected).  Perhaps it's safer just to always deselect everything.

**Comment by Tantacrul** [comment]
@wizofaus - yes. That sounds about right to me. Cheers!
