### ISSUE TITLE
Setting tempo in new score wizard triggers crash

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8852]
Making adjustments to tempo settings in the "Additional Score Information" section of the new score wizard consistently triggers a crash. 

<img width="1019" alt="Screenshot 2021-08-13 at 21 45 22" src="https://user-images.githubusercontent.com/86290556/129352570-04374dd0-c225-41dd-9de5-f3d92450f948.png">

Demo video: https://www.dropbox.com/s/v7e3j2it94chdob/Setting-tempo-triggers-crash.mov?dl=0

Specifically: crash is triggered once checkbox "show tempo marking above my score" has been checked and "done" has been clicked.

MacbookAir M1, MacOS 11.5.1

**Comment by wizofaus** [comment]
Can't reproduce on Windows, score was created as expected.

**Comment by vshalkevich** [comment]
Fixed
