### ISSUE TITLE
[MU4 Issue] Load style command does nothing

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8856]
**Describe the bug**
Whether from the Format menu or context menu from right clicking on an empty part of the score, choosing "Load style" does nothing.

**To Reproduce**
1. Open a score
2. Choose Format|Load Style
3. ...?

**Expected behavior**
Dialog to allow loading a style file should appear as per MU3.
 
And "Save style" is missing entirely?

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by wizofaus** [comment]
BTW I started looking at this and while it should be reasonably straightforward to implement:
a) MU3 always prompts the user with a warning if the .mss file version does not exactly match the current version, is that behaviour still what we want (the warning is quite stark, saying "the style file is not compatible with this version")?  Some of the .mss files that are being built into the install are still v3 so would cause this warning - I assume they need to be updated?
b) MU3 does nothing at all if you attempt to load an .mss file that can't be parsed or read (e.g. a random text file or one you don't have permission to read) - is that the right behaviour?
c) the "Save Style" command isn't even being shown currently, but presumably we want to keep this too?

@Tantacrul

**Comment by Tantacrul** [comment]
This seems to have simply been missed. We would want to keep MS3 functionality here as a first step, so these options (and warnings) should be reinstated. I don’t have a strong opinion about what the default folder would be and if we think the messaging is a bit stark, we can reword it.

cheers!

**Comment by wizofaus** [comment]
Happy to put up a PR but I need my text editing fixes merged first, as it involves adding new functions to the ends of the same files.

**Comment by wizofaus** [comment]
How about this? @Tantacrul 
![image](https://user-images.githubusercontent.com/5364225/129625198-4b181e5a-cf4c-423d-bdc7-42579e113fd3.png)

**Comment by Jojo-Schmitz** [comment]
'an older'` maybe? and/or 'may not be fully compatible with this version'

**Comment by wizofaus** [comment]
The check is literally that for exactly the same version, I don't know why.
Happy to add "and may not be compatible".

**Comment by Tantacrul** [comment]
Agreed ‘older version’ might be better. I also wonder whether we should explain the potential consequences too?

**Comment by wizofaus** [comment]
I wouldn't expect loading an "older" version to give a warning at all, it's only loading a file from a newer version that's likely not to work as expected.

**Comment by Tantacrul** [comment]
If there is cause for a warning, give a warning. Otherwise don’t. I’m not sure what could go wrong when opening a style from MS3 but it might be wise to future proof this thing because MS4 will certainly feature a lot of engraving changes over the next year.

**Comment by wizofaus** [comment]
Also after re-saving, e.g. MuseJazz.mss with MU4 the file is quite different, I'm not sure why (my test score looks the same either way)

**Comment by wizofaus** [comment]
I assume that warning was added because of some situation in the past where somebody opened an mss file saved with an older or newer version and something didn't work quite right.  There's no way I can really determine whether there's likely to be any reason an MU3 mss file wouldn't work 100% in MU4, especially, as noted above, the file is quite different when resaved with MU4, so keeping the version check as is is probably best. I'm happy to change the wording but it's hard to know what to add that would be helpful...

Also I haven't addressed the fact that if the file is not a valid .mss file nothing happens at all (the way the code is written doesn't make that entirely straightforward).

**Comment by Tantacrul** [comment]
I'd say something like 'since this is from an older version, it is not guaranteed that...' etc. :)

**Comment by wizofaus** [comment]
"Since this style file is from a different version of MuseScore, your score is not guaranteed to display correctly"?

(again: it really is *newer* versions that are more of an issue, as MU4 can't possibly know in advance what an MU5 style file might have in it).

**Comment by Tantacrul** [comment]
Ah, right. That makes sense. We _could_ potentially create different messages depending on whether the version is newer or older but I wonder about whether or not it's likely to happen very much that a MS4 user will open an MS5 style. I guess it would be worth mentioning the specific version (if possible). If not, your message seems pretty sensible.

**Comment by wizofaus** [comment]
QA will need the following test cases for Load then:
a) valid mss file from current version that can be read successfully: no errors/warnings, style applied
b) valid mss file from newer or older version that can be read successfully: warning as above, if cancel clicked, no action, if OK clicked, style loaded and applied (which sets dirty flag, and can be undone).
c) invalid/corrupted file mss file that can be read: error indicating style file is not valid
d) file that can't be read (permissions or network error), error indicating file is not readable

For Save it's relatively straightforward, though we should show an error if there's a failure writing the file (e.g. network or permissions error). I don't know if MU3 even does that currently, in fact after saving there's no visible feedback that anything happened at all.

**Comment by wizofaus** [comment]
I have this for style file being invalid:
![image](https://user-images.githubusercontent.com/5364225/129636090-6ed07ef7-5c3b-46ec-8a8b-3bd65c2df3ca.png)
And for being unreadable:
![image](https://user-images.githubusercontent.com/5364225/129636169-8dcc74d9-fa7f-4ae9-b35c-5fb2ddd03d7d.png)

(I "faked" this by deleting the file after selecting it while it was paused in the debugger, obviously that would be a pretty odd error to get if you've just selected the file, but if it's a network error or a file you don't have permission to read from you'd see an appropriate message here).

**Comment by wizofaus** [comment]
BTW this is what you get when trying to open a *score* file that's invalid, which I had hoped to use as a model, but, well...

![image](https://user-images.githubusercontent.com/5364225/129636388-6cf7ecbd-ee5e-4e82-9cd7-0232bff91556.png)

**Comment by wizofaus** [comment]
I have a PR for this on my own github clone, but it's dependent on the text-editing-fixes branch (https://github.com/musescore/MuseScore/pull/8815) being merged.

**Comment by wizofaus** [comment]
BTW, the shipped Edwin.mss and Leland.mss are already v4.0 (unlike MuseJazz.mss), but seem to be missing a lot of style properties, even, for instance, pageWidth and pageHeight.  Is this by design, and if so, how do you create such file, as when I re-save those files all those properties get added?

**Comment by Jojo-Schmitz** [comment]
We had changes of style names, so older versions can be a problem. For scores there are compatibility checks, but not for style files or drum sets, etc. So we used to not read those at all, but at a certain point decided to at least try and warn.

**Comment by Tantacrul** [comment]
> I have this for style file being invalid:
> ![image](https://user-images.githubusercontent.com/5364225/129636090-6ed07ef7-5c3b-46ec-8a8b-3bd65c2df3ca.png)
> And for being unreadable:
> ![image](https://user-images.githubusercontent.com/5364225/129636169-8dcc74d9-fa7f-4ae9-b35c-5fb2ddd03d7d.png)
> 
> (I "faked" this by deleting the file after selecting it while it was paused in the debugger, obviously that would be a pretty odd error to get if you've just selected the file, but if it's a network error or a file you don't have permission to read from you'd see an appropriate message here).

Looking good!
