### ISSUE TITLE
[MU4 Issue] nightly does not run on macOS 10.13

### ISSUE THREAD

**Issue by riaanvn** [musescore/MuseScore#8858]
As per comment on thread [Our Progress on MuseScore 4](https://musescore.org/en/node/319957#comment-1091610)
when trying to open a MuseScore 4.0 nightly on macOS 10.13.6, you get an
[error message](https://musescore.org/sites/musescore.org/files/2021-08/Screen%20Shot%202021-08-15%20at%2010.31.15.png) stating the application requires macOS 10.14 or later. 

It *should* work, since Qt 5.15 supports macOS 10.13 as per https://doc.qt.io/qt-5/supported-platforms.html . 
E.g. this limitation is not a Qt one, and must have been imposed elsewhere. 

Looking at [Macs and maximum macOS version](https://musescore.org/en/handbook/developers-handbook/references/versions-reference#macs-macos-maxos), there are a couple of 2010 & 2011 Macs which are not capable of running macOS 10.14, and are affected by this. 

@Jojo-Schmitz states that it just has to be recompiled for macOS 10.13, e.g. may happen later in the development cycle (Alpha/Beta etc.?)

**Comment by cbjeukendrup** [comment]
The reason for this limitation is that we will switch to Qt 6 soon (maybe already for MU4.0, but probably for MU4.1), and Qt 6 does not support 10.13. The idea behind it is that it will cause confusion when 4.1 has different requirements than 4.0.

**Comment by Jojo-Schmitz** [comment]
Which then would drop support for 32-bit Windows too, as far as I can tell

**Comment by riaanvn** [comment]
@Jojo-Schmitz is correct. Hi @cbjeukendrup. I did see your work on the Qt 6 on the Developer discord chat and did not realise that the switch is so imminent. This opens a whole can of worms in terms of dropped support for 32-bit Windows and pre Windows 10, which may be better discussed elsewhere. I started a forum discussion at [Qt 5.15 vs 6.x for MuseScore 4.x development](https://musescore.org/en/node/323841)

**Comment by riaanvn** [comment]
Since the switch to Qt 6.x will not happen before MuseScore 4.0 is released, can the code restricting MuseScore 4.0 running on macOS 11.13 be removed?

**Comment by Jojo-Schmitz** [comment]
Probably not: _The idea behind it is that it will cause confusion when 4.1 has different requirements than 4.0._

**Comment by Tantacrul** [comment]
100%. We can't have a situation where a small number of users can open MS4 on their machine and then **when updating** it suddenly, irreversibly no longer works.

It's just the state of affairs with tech. Annoying as hell.

**Comment by robinboncoeur** [comment]
Not sure if this is helpful, but for those unsupported Macs (2011 and before) there is a solution to upgrade to at least 10.15 (Catalina). I have installed this version by dosdude1 on an iMac 2009, a 2010 MB Pro and  a 2011 MB Pro and they all run flawlessly, even with only 4gig RAM. I will not create a direct link here because my browser warns me it is not a secure site, but this version - with comprehensive instructions - can be found at dosdude1 dot com forward-slash catalina. 
Please let me know if this solution would be considered inappropriate and I will withdraw it.

**Comment by riaanvn** [comment]
@Tantacrul . This is a perfect good reason and one I am happy to accept. I assume this the same reason why the 4.0 nightlies and private alpha do not support 32-bit Windows?

My concern is, I don't see the system requirements which would make these desupported systems clear, specified anywhere (e.g. neither in any of your "progress" announcements nor on https://musescore.org/en/download#Development-builds ). At least if this is made explicit
a) users will stop asking about it in the announcement posts
b) users can plan their upgrades accordingly, whether upgrading to a newer PC/Mac or using the above-mentioned hack. 

I have updated https://musescore.org/en/handbook/developers-handbook/references/versions-reference with my understanding of the situation. However, this is an internal reference doc and not discoverable. 

There are some things that are unclear to me (e.g. whether or not MuseScore 4.0 will run on Window 7 & 8.1 64-bit (technically possible, but is there code that prevents them from installing or running), even though they will be desupported by Qt 6.x.

**Comment by Tantacrul** [comment]
Good point. We'll need to make this clearer and state it in app updates too.
