### ISSUE TITLE
[MU4 Issue] Not starting on Windows 11

### ISSUE THREAD

**Issue by tes-com** [musescore/MuseScore#8864]
**Describe the bug**
MuseScore 4 Nightly 202107090421 is not starting.

**To Reproduce**
Goto \Bin\
Start musescore4.exe

**Expected behavior**
Program starts

**Screenshots**
No screenshot nothing happens

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Logfile:
2021-08-16T16:09:42.235 | INFO  | main_thread | GlobalModule | onInit: === Started MuseScore 4.0.0-Development ===
2021-08-16T16:09:42.300 | INFO  | main_thread | TelemetryModule | onInit: success start crash handler
2021-08-16T16:09:42.338 | INFO  | main_thread | CoreAudioDriver | open: 48000
2021-08-16T16:09:42.346 | ERROR | main_thread |            | logError: AUDCLNT_E_UNSUPPORTED_FORMAT
2021-08-16T16:09:42.346 | ERROR | main_thread | AudioModule | onInit: audio output open failed
2021-08-16T16:09:42.410 | WARN  | main_thread | Qt         | QFSFileEngine::open: No file name specified
[dumps.zip](https://github.com/musescore/MuseScore/files/6993004/dumps.zip)

**Comment by Jojo-Schmitz** [comment]
A build from 2021-07-09 4:21 is pretty antediluvian by now.

Try the latest build, currently from 2021-08-16 04:21

**Comment by tes-com** [comment]
Just downloaded the lastest build result is the same

**Comment by Jojo-Schmitz** [comment]
Works for me, Windows 10.
Windows 11 doesn't really exist currently.

**Comment by tes-com** [comment]
I'm a microsoft beta tester, Windows 11 will be released soon. So would be a great if you test on Windows 11
![windows11](https://user-images.githubusercontent.com/16758637/129580830-4ac4e6d2-bdf3-447c-9002-ca06c0fb5bff.jpg)

**Comment by Jojo-Schmitz** [comment]
Better don't test a pre-Alpha MuseScore on a Beta Windows. Of if you do, don't expect it to work ;-)

**Comment by Jojo-Schmitz** [comment]
And make sure to report this to Microsoft too.

**Comment by Jojo-Schmitz** [comment]
Anyway, thanks for reporting it here. Not sure anyone else is available and ready to test MuseScore on Windows 11

**Comment by mattblo** [comment]
For me it works on Windows 11 (latest NightlyBuilds)

System Information:
Edition Windows 11 Home Insider Preview
Version Dev
Operating system build 22463.1000
Performance Windows Feature Experience Pack 1000.22463.1000.0

**Comment by DmitryArefiev** [comment]
Tested on master build and **Windows 11 Pro** (21H2, 22000.318) - RUNS FINE

Closing
