### ISSUE TITLE
[MU4 Issue] Maximized windows are too big

### ISSUE THREAD

**Issue by Trainzack** [musescore/MuseScore#8869]
**Describe the bug**
When the main window is maximized, it slightly overruns the boundaries of the screen, causing elements near the edge of the screen to be cramped or partly offscreen.

**To Reproduce**
1. Start MuseScore
2. Maximize the window
3. See how the edge of the window is cut off

**Expected behavior**
When the window is maximized , it should take up the user's screen exactly, with no overrun.

**Screenshots**
![MuseScore is partly visible on second monitor](https://user-images.githubusercontent.com/19575360/129813286-781aa9a6-7221-46a5-a5bc-d8c3b193dc75.png)
This screenshot shows MuseScore overruning onto a second monitor (the red area is space not shown by any monitor).

**Computer Info**
 - Model: Dell Laptop (Latitude 5590)
 - Graphics Card: Intel(R) UHD Graphics 620
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-, revision: github-musescore-musescore-

**Comment by wizofaus** [comment]
Pretty sure that's the same problem as https://github.com/musescore/MuseScore/issues/8270 but it manifests differently on different video drivers apparently.

**Comment by RomanPudashkin** [comment]
The fix has been merged:
https://github.com/musescore/MuseScore/pull/8872

@Trainzack could you check this issue on the last master?

**Comment by Trainzack** [comment]
> The fix has been merged:
> #8872
> 
> @Trainzack could you check this issue on the last master?

I just rebuilt the master, and unfortunately I don't see any difference.

**Comment by RomanPudashkin** [comment]
> > The fix has been merged:
> > #8872
> > @Trainzack could you check this issue on the last master?
> 
> I just rebuilt the master, and unfortunately I don't see any difference.

Thanks for testing! Could you add some details about your hardware to the issue description?

**Comment by Trainzack** [comment]
> > > The fix has been merged:
> > > #8872
> > > @Trainzack could you check this issue on the last master?
> > 
> > 
> > I just rebuilt the master, and unfortunately I don't see any difference.
> 
> Thanks for testing! Could you add some details about your hardware to the issue description?

Okay, I added a few more details. Let me know if there is anything specific that would be helpful.

**Comment by wizofaus** [comment]
Can you explain how you got that screenshot? Can't figure it out, even with multiple desktops etc.  Do you need multiple monitors?

**Comment by Trainzack** [comment]
> Can you explain how you got that screenshot? Can't figure it out, even with multiple desktops etc. Do you need multiple monitors?

I have multiple monitors. I used Win+Shift+S (the windows clipping tool) to take the screenshot.

**Comment by Eism** [comment]
@Trainzack could you check my fix #8926 ?

**Comment by Trainzack** [comment]
I can, but not for another 36 hours or so.
