### ISSUE TITLE
[MU4 Issue] Reorder Instruments panel on mouse release

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#8871]
**Describe the bug**
When reordering the instruments in the new Instrumentspanel (e.g. SATB down and piano up) the changes are applied to the score at the same time. This works quite well for small scores! However, if it's a large score with several pages, moving the instruments is quite choppy. 

**To Reproduce**
1. Open a big Score (with many Instruments and Notes)
2. Try to reoder instruments

**Expected behavior**
Apply the changes to the score only when releasing the mouse button. So you could just drag the instrument to the right place and when you release the mouse button the score is "recalculated".
@Tantacrul Maybe even with a small dialog window with progress indicator or at least a hint "Layout is being recalculated" or something similar?

**Comment by mattblo** [comment]
@Tantacrul @jessjwilliamson What about this point for Musescore 4? I find it very annoying in a large score with many instruments to want to move an instrument and first wait a while until the instrument has arrived at the right place. When the instrument is where it should be, there could be a message in a dialog box "Layout is being recalculated" or something like that, which disappears when the calculation is finished.
I don't think it's that complicated to fix this problem and switch it to MouseRelease.

**Comment by Tantacrul** [comment]
I think this makes perfect sense. If we feel we need a 'Recalculating...' message after this is done, we can make one.

**Comment by mattblo** [comment]
Will this improvement still be solved in MU4, or is it not important? I always find it annoying when instruments are rearranged that the instrument panel hangs as soon as the score is larger. Therefore, from my point of view, it would be welcome if this would still find its way into MU4.0.

**Comment by Tantacrul** [comment]
I've given it a P rating and targeted it at our Beta release. This does not mean it'll definitely get in but it is problematic enough that I would like to see it included. It really depends on how much stuff there is to do after alpha.
