### ISSUE TITLE
[MU4 Issue] Changing colour of note doesn't work the first time

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8880]
Changing the colour of a note doesn't work on the first attempt, but works if you change it a second time.
Also the app window loses focus after selecting a colour.

**To Reproduce**
1. In a new score add a note
2. From the properties panel, click Appearance then the black-filled colour rectangle
3. Select a new colour
4. Note that app window goes to the background, and note doesn't change colour
5. Repeat steps 2-3, and note that colour changes as expected (though app window still goes to the background)

**Expected behavior**
Colour changes should work immediately and app window should stay in the foreground after selecting.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**
There's also an issue where undo doesn't remember that different noteheads in a chord have different colours, but note that currently MU4 doesn't allow creating this, you have to create/save the score in MU3.  But then changing the colour of the chord in MU4 and undoing resets them all to the same colour.

**Comment by HemantAntony** [comment]
This appears to be fixed:

https://user-images.githubusercontent.com/88136054/147636783-7e452631-7283-4670-8ae1-0cb104ce4691.mp4
