### ISSUE TITLE
[MU4 Issue] Can't alter properties of noteheads independently from chord

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8881]
MU3 supports altering the following properties of noteheads (and stems and flags) independently:
*) visibility
*) colour
*) "small" size (notes only)
*) playback (notes only)
*) notehead style
etc.
However there appears to be no way to do this in MU4 - changing any of these properties affects all components in the chord, regardless of what's selected.

**To Reproduce**
1. In a new score create a chord of two notes
2. With just one of the notes in the chord selected, try to change various properties (visibility, colour, playback etc.) for just the selected notehead
3. All property changes apply to the whole chord

**Expected behavior**
Not sure, but at least some way in the properties panel to indicate that the property changes should only apply to the selected notehead (or stem/flag etc.) rather than the whole chord

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Artificial harmonics are notated by changing just the top notehead in a two-note chord to a diamond, and turning off playback just for that notehead (and possibly adding an invisible notehead at the correct pitch)

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/9116
