### ISSUE TITLE
[MU4 Issue] Most actions don't work while special characters dialog is still open (even if hidden behind main window)

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8882]
**Describe the bug**
While the special characters dialog is shown it prevents most score/text editing actions from working

**To Reproduce**
1. In a new score add a text element (staff text etc.)
2. Double click to edit
3. Click "Insert special characters" in the properties panel
4. Click on the score - special characters window disappears (it's behind the main window)
5. Exit text editing mode and note that most commands/actions don't work (e.g. inserting notes)
6. Find (if you can!) special characters window and close it - commands start working again

**Expected behavior**
If special characters window doesn't have focus then all commands/actions should work as expected while editing score

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by wizofaus** [comment]
The way InteractiveProvider keeps track of the currently open window doesn't seem to be designed to cope with non-modal windows that you can switch between (it maintains a stack). Nor is the NavigationController able to determine that the Notation section (NotationView) has the current focus, so I'm not sure what to do here.
The only thing I've been able to make work is to change UiContextResolver::currentUriContext to just treat " "musescore://palette/specialcharacters?sync=false" being the current Uri the same as "musescore://notation" which isn't nice and doesn't really work properly as it can't distinguish between the special characters dialog having the focus or not (it *could* if the NotationPaintView could be queried for the focus, but it's not obvious how to do this.  Interestingly NotationPaintView::canReceiveAction() does test for hasFocus() but this is never actually called as far as I can tell.)

Also discovered that Ctrl+Z for undo has stopped working in text edit mode entirely, investigating.

**Comment by Tantacrul** [comment]
This has been fixed. No idea when... but I remember us tackling it a while back. Phew!

Closing!

**Comment by wizofaus** [comment]
Yep, looks good now! (though the special characters dialog seems to disappear of its own accord at some point, not clear what triggers that).
