### ISSUE TITLE
[MU4 Issue] Multi-measure selection cannot select last measure if it contains a whole rest

### ISSUE THREAD

**Issue by Trainzack** [musescore/MuseScore#8885]
**Describe the bug**
When selecting a range of measures with shift, selecting the last measure turns the selection of measures into a selection of objects inside the measures.

Note that if the last measure is divided into notes or rests, selecting those can select the whole last measure. Therefore, this is likely a bug to do with whole rests.

**To Reproduce**
1. Create a new score
2. Shift+click on the first measure to select the measure
3. Shift+click on the second-to-last measure
4. Note that all but the last measure is surrounded by the blue selection rectangle, as expected
5. Shift+click on the last measure
6. Observe that the multi-measure selection has turned into a selection of only the rests

**Expected behavior**

**Screenshots**
A score with all but the last measure selected with a multimeasure selection:
![image](https://user-images.githubusercontent.com/19575360/130172181-9fe5cb6d-1f43-41ff-9b37-d0d0516bf3f7.png)

Shift clicking on the last measure turns it into a selection of all of the rests, not measures:
![image](https://user-images.githubusercontent.com/19575360/130172349-4b26aae1-81bb-4847-80b2-1137050a9456.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-, revision: github-musescore-musescore-

**Comment by wizofaus** [comment]
I'll take this one, I keep noticing it!
