### ISSUE TITLE
[MU4 Issue] sigD = 256 crashes MuseScore

### ISSUE THREAD

**Issue by PopSlime** [musescore/MuseScore#8890]
**Describe the bug**
Selecting notes and rests in a measure whose sigD = 256 crashes MuseScore. Playback also crashes upon reaching the measure.

**To Reproduce**
1. Save a file with a single measure in Uncompressed MuseScore 3 File.
2. Modify the sigD to 256, and modify the length of the rest to match the time signature via an external editor.
3. Open the file in MuseScore and click Play.

**Context**
 - OS: Windows 10 (10.0)
 - Arch.: x86_64
 - MuseScore version (64-bit): 3.6.2.548021803
 - revision: github-musescore-musescore-3224f34

**Comment by Jojo-Schmitz** [comment]
The issue tracker here on GitHub is only used for tzhe current in develeopment 4.0, the master branch

For but in 3.x use the issue tracker on musescore.org.

But please also explain what "sigD" is?

**Comment by Jojo-Schmitz** [comment]
Apart from that modifying the mscx with an external editor is not supported at all.

**Comment by PopSlime** [comment]
So I'm creating a custom time signature, with the denominator (sigD) being 256, however it is not listed in MuseScore (only 2, 4, 8, 16, 32, and 64 are listed), so I have to modifying the file itself. I found that when sigD = 128, which is also impossible to achieve in the app, MuseScore can work perfectly. However it crashes when sigD = 256.

**Comment by Jojo-Schmitz** [comment]
The shortest denominator MuseScore allows in the UI is 64. That is for a reason! Manually chanmge that tio anything higher is not supported, a crash in those cases is basically by design. It certainly is not a bug.

128 is possible BTW. See this as a bonus.

**Comment by Jojo-Schmitz** [comment]
You've opened it as a MU4 issue, but it isn't. It is a limitation of MuseScore that exists ever since

**Comment by PopSlime** [comment]
I see, but I'll be glad if it can be supported in the future. Also it is weird how 1/128 works but 1/256 not, both of which are not supported. Anyway I'll look for a substitution (I have no idea why that piece of music uses such a strange time signature lol). Thanks for your reply :D

**Comment by Jojo-Schmitz** [comment]
Well 128 doesn't crash, but doesn't really work either
Guess we'd better check and forbid and report that explicitly rather than crashing on it.

One place for such a check might be https://github.com/musescore/MuseScore/blob/186ced1fa74fa9b806b754ef17d5c010da772596/src/engraving/libmscore/measure.cpp#L2102

**Comment by PopSlime** [comment]
128 does work in 3.6.2, but yes adding a check is necessary I guess

**Comment by Jojo-Schmitz** [comment]
I've found the place where the malfunctioning at 128th happpens, in 3.x:
https://github.com/musescore/MuseScore/blob/3ca622a447b786a8465dfa451147587140620b59/mscore/measureproperties.cpp#L129-L130

**Comment by Jojo-Schmitz** [comment]
But feel free to submit a fearure request for 128th and 256th, at least the latter would only be possible to provide with MuseScore 4, as MusesScore 36.2 and earlier would crash on them

**Comment by Jojo-Schmitz** [comment]
If it doesn't make it into MuseScore 4, it would have to wait untils MuseScore 5!

**Comment by PopSlime** [comment]
lol
I see

**Comment by Jojo-Schmitz** [comment]
Actually the crash happens at
https://github.com/musescore/MuseScore/blob/186ced1fa74fa9b806b754ef17d5c010da772596/src/engraving/libmscore/sig.cpp#L33-L40
And this reveals that shorter than 128 is not possible without bumping up `MScore::division`, currently 480. This indeed would be a very major change
