### ISSUE TITLE
[MU4 Issue] Behaviour of various Tools menu commands when nothing selected in score

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8895]
As it is currently many of the commands in the Tools menu do nothing if nothing's selected, and it's very unlikely you'd ever want any of them to work on the full score. Actually they're quite inconsistent:

Transpose - both MU3/MU4 automatically shows the whole score as selected if nothing's already selected, but does nothing until you confirm the transposition you want in the dialog.

Explode/Implode/Realise chord symbols - MU3/MU4, do nothing at all if nothing's selected

Voice exchange/Split measure - MU3, give an error (e.g. no staff selected) if nothing appropriate is selected, MU4 - do nothing.

Remove selected change/Fill slashes/Toggle rhythmic slash - do nothing at all if nothing's selected

Respell pitches - if nothing selected, respell all pitches in entire score according to key signature, otherwise only respell selected notes (NB this is a change from MU3 which always did the entire score regardless of selection).

Regroup rhythms/Resequence Rehearsal Marks - if nothing selected, applies to whole score (but unlike Transpose, does not visibly change selection), otherwise, if range selected, applies to that, otherwise (individual items selected), does nothing

Unroll repeats - MU3: creates a new score, and always applies to whole score no matter what's selected. NB: cannot be UNDONE!  MU4: does nothing at all. In fact internally it does create a new score, but no window is opened to show it to the user in.  How do we actually want to implement this?

Copy lyrics to clipboard - MU3/MU4 always copies lyrics of whole score to clipboard (as one long sentence, concatenating all verses from all staves), regardless of what's selected. Note that you can't then paste them back into another score.

Image capture - doesn't exist in MU4.

Remove empty trailing bars - always applies to whole score, regardless of what's selected (makes sense in this case).

Do we really want to have enabled menu commands that simply don't do anything?  I've put mechanisms in place now that it wouldn't be hard to ensure commands are disabled when there's nothing valid selected.

**Comment by wizofaus** [comment]
Might need to split "Unroll repeats" not working out as a separate issue, given it's the most critical problem here, the others are mostly cosmetic.

**Comment by Tantacrul** [comment]
Closing, since these issues have been largely addressed - either by being recognised as features we delay in MS4 or because they are already issues in MS3 that we will resolve in later versions.

**Comment by wizofaus** [comment]
"are already issues in MS3 that we will resolve in later versions." - where is this being tracked then?
