### ISSUE TITLE
[MU4 Issue] Input fields has no borders

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8909]
**Describe the bug**
Input fields has no borders

**To Reproduce**
Find any input field:
1. Launch MU4
2. Observe search field on the Home screen

**Expected behavior**
This is how should be (borders)
<img width="728" alt="на полях отсутствуют границы (1)" src="https://user-images.githubusercontent.com/71372310/130588255-bc60ed2b-937b-4126-959e-ae6dc1c7d5bb.png">

**Screenshots**
This is a bug (no borders on input fields)
<img width="991" alt="на полях отсутствуют границы (2)" src="https://user-images.githubusercontent.com/71372310/130588279-a04a582a-196b-4f4f-babe-cc8e651b33a8.png">

**Desktop (please complete the following information):**
Windows 10

**Comment by cbjeukendrup** [comment]
This is already fixed by @ArjunBoi, as part of PR #8886.
