### ISSUE TITLE
[MU4 Issue] If item selected via navigation it has displaced borders (Parts, Score, My account, Inspector)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8911]
**Describe the bug**
If item selected via navigation it has displaced borders

**To Reproduce**
1. Use navigation to select items  ("tab" button and arrows from the keyboard)
2. observe borders of selected items

**Expected behavior**
borders should not be displaced

**Screenshots**

![Сместились границы  (1)](https://user-images.githubusercontent.com/71372310/130589351-74db72eb-fd0d-4094-b3e9-4d3989da8796.png)
![Сместились границы  (2)](https://user-images.githubusercontent.com/71372310/130589354-0f0991ee-4813-4720-8952-f2304bc4803f.png)
![Сместились границы  (3)](https://user-images.githubusercontent.com/71372310/130589356-fa42ba4b-2cd2-488f-a4ff-6ed98def19e4.png)
![Сместились границы  (4)](https://user-images.githubusercontent.com/71372310/130589357-abf8555e-ff5e-46ff-b513-a4b189e42b74.png)

**Desktop (please complete the following information):**
Linux
MacOS

**Comment by DmitryArefiev** [comment]
Other similar issues logged in #9983

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
