### ISSUE TITLE
[MU4 Issue] Can't see staff names/clefs etc in continuous view when scrolled (missing MU3 functionality)

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8924]
In MU3 when you scroll through the score in continuous view, the current instrument name/clef/key/time signature are shown (in grey) at the left of the page.  This is not shown in MU4, making it very hard to determine this contextual information for each staff when working with/reading from the score.

https://user-images.githubusercontent.com/90187801/144592530-e54ffb1b-7b38-40fa-bfed-b5b1aab4a224.mp4

**To Reproduce**
1. Create a new score with multiple instruments and a good number of measures (I used the 'concert band' template)
2. Use the mouse to scroll the canvas left
3. The instrument names/clefs/key/time signatures can't readily be determined for any staves

**Expected behavior**
Either Mu3 behaviour or some other way to easily determine the clef/key/time signature of the staff you're working on in "Continuous View (horizontal)".

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**
It's a missing **MU3** functionality

**Comment by DmitryArefiev** [comment]
Thank for you for logging this! 

I just added a video demo and priority marks

**Comment by DmitryArefiev** [comment]
@vpereverzev Leave this with P2 in Alpha Release for now..

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/11326
