### ISSUE TITLE
[MU4 Issue] Larger templates (concert band etc.) don't fit on page

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8925]
**Describe the bug**
Creating scores using any of the larger templates such as Concert Band or Symphony Orchestra don't apply the expected the staff scaling and don't fit on the page

**To Reproduce**
1. Create a new score using Concert Band or Symphony Orchestra template
2. Scroll to bottom of page
3. Observe that not all staves fit

**Expected behavior**
As per MU3, staff scaling (in Page settings) should be set appropriately for these templates so they fit.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
