### ISSUE TITLE
[MU4 Issue] Can't edit text in text frames (or resize them)

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8930]
**Describe the bug**
Double-clicking on a newly created text frame to enter text not working, nor is the drag handle

**To Reproduce**
1. Create or open a score
2. Select Add|Frames|Insert Text Frame
3. Double click on the newly added frame to edit the text
4. Nothing happens
5. Try to enlarge the text frame using the drag handle
6. Nada

**Expected behavior**
As per MU3 (which doesn't show a drag handle actually)
You can edit text in an existing frame that already has text just fine.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Alt+Shift+E to edit isn't working either, but this is true in general.

**Comment by DmitryArefiev** [comment]
Tested # in latest master build (Win10, Mac12, LinuxMint 20.2) - the issue **STILL OCCURS**

https://user-images.githubusercontent.com/90187801/149969449-7209fa04-6a54-4289-894b-b12dbd3c4611.mp4

**Comment by DmitryArefiev** [comment]
Tested #10299 on Win10, Mac12, LinuxMint 20.2 - FIXED

(Text frame is not resizable in MU3.6 so it requires additional issue)

**Comment by Jojo-Schmitz** [comment]
Text frames are not supposed to be sizable, they are (supposed to be) sizing as per their content
