### ISSUE TITLE
[MU4 Issue] Dock-panels show incorrectly when more than 3 docked

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8932]
When turning on, for instance, the "selection filter" panel, the display of the dock panel tabs renders incorrectly

**To Reproduce**
1. Open/create score
2. Select "selection filter" from View menu
3. 
![image](https://user-images.githubusercontent.com/5364225/130870027-259a36f5-9dbd-4840-8ec4-67dd90cac80e.png)

**Expected behavior**
Something nicer...

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/9262
