### ISSUE TITLE
[Inspector] tremolo marks are being given the name 'tremolo bar' in the inspector

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#8937]
Reproduce:

1. Place a note on the score
2. Put a tremolo mark on it (see image) 
![image](https://user-images.githubusercontent.com/21022311/130990319-91df1ff7-9028-4a9a-a99e-fad368e329e3.png)
3. Select the tremolo mark and observe the name 'Tremolo bar' in the inspector. It should just be called 'Tremolo'

**Comment by Howard-C** [comment]
Oh look, this is the same problem with #8938 :) See #8955.

**Comment by Jojo-Schmitz** [comment]
That was my gut feeling from the start actually

**Comment by Howard-C** [comment]
This should also be closed now with #9064 merged.

**Comment by Tantacrul** [comment]
Can confirm this one is done. Closing.
