### ISSUE TITLE
[Inspector] Between-note tremolo options not yet implemented

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#8938]
**Describe the bug**
Options do not appear for between note tremolo in MS4 (as they do in MS3)

See video: https://www.dropbox.com/s/f4733beiew5wjhp/01_Between_Note_Tremolo.mov?dl=0

**Comment by Howard-C** [comment]
Thanks for pinging me, I already did this in #6443 but maybe something messed it up… you don't have to reassign the issue but I will take a look.

**Comment by Howard-C** [comment]
#8955, one-liner… the options are mistakenly hidden.
