### ISSUE TITLE
[Inspector] 'Playback' button should be disabled when no settings are available

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#8939]
**Describe the bug**
The 'playback' button is always enabled, even when it does not contain settings for a selected element. This is confusing because users can never tell if an element contains playback settings or not.

See video:
https://www.dropbox.com/s/j28407mt2lgxcxa/01_Playback_Button_Disabled_When_Not_Relevant.mov?dl=0

**Comment by aniketh-varma** [comment]
Hi, I am a first time contributor. Can I work on this issue ? @Tantacrul

**Comment by Tantacrul** [comment]
Of course! Not being a developer, I'll be useless as a source of technical advice but there are plenty of people here who can guide you!
