### ISSUE TITLE
[MU4 Issue] System-final time/key signature should have padding to right

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#8944]
Time signatures and key signatures at the very end of a system, after the last barline, currently finish exactly flush with the stave, but there should be a small amount of padding to the right (1sp will do for now, but this will eventually be configurable).

Currently:
![key-signature](https://user-images.githubusercontent.com/20604032/131002640-dcf77491-3f1d-4f1c-a76b-5aae549f29a6.png) 
![key-signature2](https://user-images.githubusercontent.com/20604032/131002663-45cbea94-a7da-4562-b932-4b9533d49e95.png)
![time-signature](https://user-images.githubusercontent.com/20604032/131002674-f11317c0-f40c-4a94-8f2f-6456cdf212f5.png)

**Comment by Jojo-Schmitz** [comment]
IMHO 1.0 sp is quite a lot, maybe we'd better take the same default value as for `clefLeftMargin?, `0.8`, `timesigLeftMargin, `, `0.63` or `keysigLeftMargin`, `0.5` (seems `timesigLeftMargin, `, `0.63` would be a nice compromise), which should make the courtesy clef, time- or key signature look nicely centered?

**Comment by DmitryArefiev** [comment]
Checked #8944 on Win10, Mac11.13.1, Linux Mint 20.2 - FIXED
