### ISSUE TITLE
[MU4 Issue] [Engraving] Note stems don't take the SMuFL anchors "stemUpNW" and "stemDownSW" into account

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#8952]
**Describe the bug**
The stems of notes and chords don't take the [`stemUpNW` and `stemDownSW` SMuFL anchors](https://w3c.github.io/smufl/latest/specification/glyph-registration-notes-flags.html) of the flag into account. This causes that the stem has an incorrect length. 
For normal flags, this is not very visible (but if you look closely, you might see an edge at some zoom levels when anti-aliasing is turned on). The problem becomes very obvious with straight flags*:

![Straight flags wrong stem length](https://user-images.githubusercontent.com/48658420/131194521-6775afde-b899-417e-b135-fd7f13356b6a.png)

\* Not yet possible, but I will implement this as soon as this issue is fixed and PR #8867 gets merged.

**Additional context**
For the Shadow Note, it already works correctly because I implemented this in PR #7316.

**Comment by oktophonie** [comment]
Be my guest ;)

If you're in that bit of the code, is it worth investigating a fix for `stemUpSE` and `stemDownNW` on certain noteheads like the cross and triangle? They seem _almost_ right, but not quite:
![x-noteheads](https://user-images.githubusercontent.com/20604032/131210350-c4f1431d-3246-412b-8ab0-1af5fe62bdb0.png)

**Comment by Jojo-Schmitz** [comment]
That 'edge' on normal flags:
![image](https://user-images.githubusercontent.com/1786669/131214554-bda188a6-ff44-4ef0-a5d0-8ca4016717dd.png)

**Comment by DmitryArefiev** [comment]
Hi @cbjeukendrup , can you help with creating straight flags please? I'm new to MU and don't find a way how to create straight flags..

**Comment by cbjeukendrup** [comment]
The problem is that there is no way to enable straight flags yet. I can implement that when PR #8867 is merged. (The screenshot at the top of this issue was taken from a development build that was made on top of that PR.) 

For testing PR #9237, you could also look at the position of the grip box to make the stem longer or shorter; that one always appears at the end of the stem line. 
<img width="585" alt="Schermafbeelding 2021-09-23 om 16 36 54" src="https://user-images.githubusercontent.com/48658420/134527634-9fac48ae-1d5c-4d23-b3c5-e26a61ad76f5.png">

**Comment by DmitryArefiev** [comment]
> 
> 
> The problem is that there is no way to enable straight flags yet. I can implement that when PR #8867 is merged. (The screenshot at the top of this issue was taken from a development build that was made on top of that PR.)
> 
> For testing PR #9237, you could also look at the position of the grip box to make the stem longer or shorter; that one always appears at the end of the stem line.
> <img alt="Schermafbeelding 2021-09-23 om 16 36 54" width="585" src="https://user-images.githubusercontent.com/48658420/134527634-9fac48ae-1d5c-4d23-b3c5-e26a61ad76f5.png">

Thanks for the advice! That helped

**Comment by DmitryArefiev** [comment]
Checked #8952 on Win10, Mac11.13.1, Linux Mint 20.2 - FIXED
