### ISSUE TITLE
[MU4 Issue] Offset not correctly set/shown in note properties panel 

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8954]
Trying to change the offset of a note/chord via the note properties panel doesn't work, nor does it properly reflect the note or chord's current offset

**To Reproduce**
1. In a new score add a note
2. In the properties panel adjust the X/Y offset - observe that note does not move
3. Deselect and reselect the note
4. Observe that X/Y offset are 0 again
5. Load a score created with MU3 that has notes (and/or chords) with an offset
6. Select one of them, observe in note properties panel that offset is shown as 0

**Expected behavior**
As per MU3. However note that MU3 allows changing the offset for both the chord and the note individually, it's not clear how you're supposed to choose this in MU4.
Note that as part of other work I've done the x/y offset for *notes* can be changed by dragging with the mouse or cursor keys, but this is never reflected here because it's only showing the offset for the whole chord.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by Tantacrul** [comment]
This is now fixed.
