### ISSUE TITLE
[MU4 Issue] Custom tremolo style set as default doesn't affect new tremolos, nor does it survive upon reload

### ISSUE THREAD

**Issue by Howard-C** [musescore/MuseScore#8957]
**Describe the bug**
Custom tremolo style set as default doesn't affect new tremolos, nor does it survive upon reload.

**To Reproduce**
1. Need to have #8955's fix, otherwise the inspector won't work;
2. Create a minim-based two-note tremolo;
3. Set the tremolo style to a custom one (the second or the third one), then set the custom style as default in the inspector;
4. Add a similar tremolo, notice it doesn't automatically have the default custom style applied (bug 1);
5. Close the file and open again, notice the custom style is gone (bug 2).

**Expected behavior**
4. The new tremolo should automatically have the default custom style applied;
5. The custom style, which has been set as default, should survive a reload.

**Comment by Tantacrul** [comment]
Confirmed. This is still happening.

Quick tutorial for anyone confused about how to do this. Create two quarter notes beside each other:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/21022311/166148447-e69585d5-e290-4e9a-9f7f-ef0492066e77.png">

Select the first note (or both notes) and then choose this option from the 'Temolos' Palette:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/21022311/166148456-c3a6847d-bbdb-45bb-9f6a-02045067db5c.png">

That will give you this:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/21022311/166148485-d79dddfd-3251-473a-81df-935c75432e65.png">

These are the Properties for the tremolo:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/21022311/166148503-71f452c8-69b8-4421-867f-128b4b4443bf.png">

The change the default and choose this option:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/21022311/166148518-a182cbe8-fba3-4a9e-89c1-f3951cd230cc.png">

Now if you try to create another tremolo in a new bar, this style won't be the default.

**Comment by DmitryArefiev** [comment]
Fixed in #11952
