### ISSUE TITLE
[MU4 Issue] Undo add staff (to instrument) crashes

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8959]
**Describe the bug**
Undo-ing adding a staff to an instrument crashes

**To Reproduce**
1. Create a new score using Treble clef template
2. Using Instruments panel add a staff to the Piano instrument
3. Undo
4. Boom!

**Expected behavior**
Not that

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

_links is nullptr

 	MuseScore4.exe!Ms::ScoreElement::unlink() Line 624	C++
>	MuseScore4.exe!Ms::Score::removeStaff(Ms::Staff * staff) Line 2594	C++
 	MuseScore4.exe!Ms::InsertStaff::undo(Ms::EditData * __formal) Line 1067	C++

Inside libmscore so not sure what's changed from MU3, but MU3 Score::removeStaff( ) does NOT have the final call to `staff->unlink();` and this appears to be have been added recently (01ad9cf5dd72fb72ec5b0909f7e6f0f391515b17)

**Comment by RomanPudashkin** [comment]
The fix has already been merged:
https://github.com/musescore/MuseScore/pull/8922/files#diff-66021505ee1467348cfbf0ddb09d0a5eebfc3b02f19295b6a671425dc7557d67R623

Please, check this issue on the actual master branch

**Comment by wizofaus** [comment]
Odd, I got that crash immediately after pulling latest from upstream and rebasing. But I just did it again and it seems OK now, will close once I have it building and confirmed it's no longer crashing
