### ISSUE TITLE
[MU4 Issue] Asserts failing when opening and closing the Style dialog

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#8960]
**Describe the bug**
When opening the Style dialog, an assert fails. When the style dialog is closed again, another assert fails when saving the project (either by hand or by auto-save).

**To Reproduce**
1. Open a score
2. Right-click > Style...
3. Assert fails: element.cpp, line 1433.
4. Close Style dialog.
5. Save score or wait for autosave.
6. Assert fails: xmlwriter.cpp, line 251.

**Expected behavior**
No failing asserts.

**Additional context**
Maybe it is time to move away from QVariant, and write our own container type, maybe based on std::variant. Now that we are mostly using custom types, QVariant is not really nice anymore.

**Comment by wizofaus** [comment]
There's SO many asserts when using a debug version of Qt, I basically have to disable a bunch of functionality (esp. the drumset panel) to actually get MuseScore to run!
I certainly don't think we should just be ignoring them at any rate.
Moving away from QVariant seems consistent with moving Qt out of the libmscore interface.

**Comment by igorkorsukov** [comment]
Fixed by various PRs, in particular by this https://github.com/musescore/MuseScore/pull/9797
