### ISSUE TITLE
[MU4 Issue] uncrustify preferred spacing for multiplication (*) operands is weird

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8961]
**Describe the bug**
Github's uncrustify/code style check action flags the following:

    -            return Ms::MScore::nudgeStep10 * spatium;
    +            return Ms::MScore::nudgeStep10* spatium;

But that makes no sense, they're both operands of a multiplication, and it doesn't expect this where the LHS operand doesn't contain :: 
Doesn't happen with my local uncrustify (Uncrustify-0.73.0_f)

**To Reproduce**
1. Edit a source file containing such a multiplication to add the space before *, save/commit/push/create PR
2. Code-style check fails

**Expected behavior**
Code-style check should be failing on all the current files that have no space before * used as a multiplication operator!

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by Howard-C** [comment]
It's probably because uncrustify thinks `Ms:MScore::nudgeStep10*` should be a pointer type…

**Comment by Jojo-Schmitz** [comment]
The GitHub CI job uses uncrustify 0.72.0. Seems time for an update...

**Comment by cbjeukendrup** [comment]
As far as I know, the CI job uses the version from HomeBrew (a third party package manager for macOS), which has indeed version 72. So we will have to wait for Brew to update the Uncrustify formula (or contribute it to Brew ourselves, but I'm not familiar with that process).

**Comment by Jojo-Schmitz** [comment]
Indeed: https://formulae.brew.sh/formula/uncrustify#default

**Comment by Jojo-Schmitz** [comment]
Hmm, uncrustify 0.72 got released last year November, 0.73 got released May this year, so is not exactly new anymore

**Comment by cbjeukendrup** [comment]
I found this: https://github.com/Homebrew/homebrew-core/pull/77330

I think this means that there was a build error in Uncrustify 0.73.0, making that version unusable for HomeBrew. It was fixed after the release of 0.73.0, so we will have to wait for the next release?

**Comment by Tantacrul** [comment]
@Eism / @cbjeukendrup - is this issue resolved?

**Comment by cbjeukendrup** [comment]
I believe it was fixed, but it's a) not our problem but an Uncrustify bug and b) not really an issue (just a cosmetic code issue that has no influence on the app). So let's close it.
