### ISSUE TITLE
[MU4 Issue] Menus too close to the top edge of the window

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8962]
**Describe the bug**
Compared to other Windows apps like Visual Studio that also draw their menu on the title bar, MuseScore4's menu is hard to make out due to how close it is to the top of the window (and the lack of a distinct border)

**To Reproduce**
![image](https://user-images.githubusercontent.com/5364225/131268962-b269613b-678d-448d-b49f-8fe00534d451.png)

**Expected behavior**
Ideally should look more like Visual Studio's menus (and a darker border would help)

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by JGreenlee** [comment]
Agreed. This issue probably belongs with #8090

But despite this, the top edge of each button is not hoverable or clickable

**Comment by wizofaus** [comment]
![image](https://user-images.githubusercontent.com/5364225/147613493-d96cfb47-e78f-41e1-a670-18bdc42afd05.png)

This is the latest version.  For the given new font size, the gap from the top of the menu text to the top of the windows look OK but - but I'm not sure I'm a fan of having so many font sizes and in particular such a tiny font for the menu.
But if this is the intended design, then I guess it can be closed - @Tantacrul ?

**Comment by Tantacrul** [comment]
I've not seen this on Windows, but that font should be the same as most other file menus on Windows, using 12pt

**Comment by Eism** [comment]
@wizofaus thanks!
fixed in #10191
