### ISSUE TITLE
[MU4 Issue] Palettes/Properties panel fully enabled even when no score open

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8964]
**Describe the bug**
The Palettes and the Properties panel do nothing if no score is open yet appear to be fully enabled, even though clicking on various controls/elements does nothing.

**To Reproduce**
1. Start application, don't open any score
2. Click on "Score" tab (next to "Home")
3. Observe that in Palettes tab all items/controls etc. are fully enabled.  This does allow you customize the palette, but clicking on any of the elements does nothing.
4. Likewise for the Properties panel - the various toggles for "Invisible"/"Frames" etc. are all clickable and appear to toggle but do nothing. The 'Page settings' and 'Style settings' button do nothing either.

**Expected behavior**
As per MU3, if no score is opened, the inspector should show nothing (or be disabled) and likewise for palettes, or at least, if we are going to enable customizing without a score being open, it should be obvious that the various elements you can normally add to a score are disabled (NB MU3 doesn't allow customizing if no score is open).
 
**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by Tantacrul** [comment]
I think disabling properties sounds like a good shout. For Palettes, you can reorganise them in MS4, which seems fine to me. I don't have very strong opinions on this, incidentally.

**Comment by wizofaus** [comment]
Agree it's a fairly minor cosmetic thing, but buttons that look like they should do something then don't when you click on them are a pet peeve of mine!

**Comment by 5yM01** [comment]
Hi, I started working on this issue by reading through the documentation but I'm still a little confused on where in the code to go to in order to 

1. Check that the user is on the score page - UiContext perhaps? 
2. Check that no score is open on the score page 
3. Disable toggling of the properties if 1 and 2 are true - ScoreDisplaySettings maybe?

**Comment by cbjeukendrup** [comment]
@5yM01 Hi! To check if a score is currently opened, you can check if `context()->currentNotation()` is not nullptr. That's all you need to do. To subscribe for changes, use `context()->currentNotationChanged().onNotify(...`.

In these examples, `context()` is will return the instance of `IGlobalContext`. To get access to this method, you need to "inject" it:

```c++
// in the header file

#include "modularity/ioc.h" // *
#include "iglobalcontext.h" // *

namespace mu::… {
class TheClass 
{
    INJECT(/*module_name*/, context::IGlobalContext, context) // *
    …
}
```
For lines marked with `// *`: only add them if not already present.
Replace `/*module_name*/` with the name of the module that contains `TheClass`, for example `notation` or `inspector`.

In the cpp file, you can now call `context()`, which will return the correct instance of `IGlobalContext`.

**Comment by 5yM01** [comment]
@cbjeukendrup Thank you for the advice! I understand it a lot better now.
