### ISSUE TITLE
[MU4 Issue] Refine 'auto' tuplet bracket mode behaviour

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#8969]
1. Where a tuplet's 'Bracket type' is 'Auto', if the tuplet applies to only a part of a beamed group, but there is no subdivision of the internal beams matching the extent of the tuplet, the bracket _should_ be shown.

![tuplet-brackets](https://user-images.githubusercontent.com/20604032/131334774-47cd7ffa-8c6b-4853-b3ed-c81fb46aaf6e.png)

The first bar here shows the default beaming that MuseScore provides for this rhythm, in which case the absence of the bracket is fine. If the inner beams are explicitly joined, however, the bracket should be shown.

2. Conversely, if a beam is joined over a rest, and that beam now spans an entire tuplet group, the bracket should disappear:
3. 
![image](https://user-images.githubusercontent.com/20604032/146919413-c31c674e-b797-48b7-a7d1-d656b5caf4df.png)

**Comment by Nick-Mazuk** [comment]
I'll take this one

**Comment by Nick-Mazuk** [comment]
This may be worth waiting until the beaming project is finish. Determining whether or not the beam is broken requires code that will almost certainly change after rewriting the beaming code.
