### ISSUE TITLE
[MU4 Issue] Accidentals create too much space for arpeggio lines

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#8970]
The presence of an accidental creates too much extra space between an arpeggio line and the following chord. (This affects all vertical lines from the Arpeggios/Glissandos palette, not just the standard wiggle.)

![arpeggios](https://user-images.githubusercontent.com/20604032/131336524-bb2e75e3-0586-4209-96bc-0e43f854ef10.png)

**Should fix:**
https://musescore.org/en/node/292231 (points 1 and 2)

**Comment by Nick-Mazuk** [comment]
I'll take this one

**Comment by vshalkevich** [comment]
Checked on Linux Ubunty, Windows 10, MacOS
Works fine
