### ISSUE TITLE
[MU4 Issue] "Barline distance" style options have unintuitive relationship with "Barline thickness" options

### ISSUE THREAD

**Issue by Trainzack** [musescore/MuseScore#8975]
**Describe the bug**
In the `Barlines` section of the Style options, we have the option to change the thickness and distance of thick barlines and double barlines. However, the distance measurement measures the distance between the *centers* of the barlines, not the *edges* of the barlines.

The result of this is that *increasing* the thickness of a thick bar *reduces* the amount of separation between it and and the neighboring thin bar line.

**To Reproduce**
1. Create a new score or open an existing one
2. Go to Format > Style... > Barlines
3. Change `Thick barline thickness` to 20sp
4. Note how the double bar at the end of the piece is now malformed: the thin bar is inside of the thick bar, and the thick bar intrudes into the preceding measure(s)
5. Change `Thick barline distance` to 10.5sp
6. Note how the separation between the thick and thin barlines is now about 0.5sp

**Expected behavior**
Adjusting the thickness of a barline should not change the separation between it and neighboring barlines.
For example, if `Thick barline thickness` is 20sp and `Thick barline distance` is 0.5sp, the separation between the thick and thin barlines should be 0.5sp.

**Screenshots**
Bug:
![image](https://user-images.githubusercontent.com/19575360/131409292-fe626d0e-9221-420f-bb9b-247683c55777.png)
Workaround:
![image](https://user-images.githubusercontent.com/19575360/131409314-8d55adad-1c31-4a0f-9397-1e6e3b4e92a6.png)

**Desktop:**
 - OS: OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-, revision: github-musescore-musescore-

**Comment by oktophonie** [comment]
Good spot! Though for a double barline it makes sense to me to do it this way (specifying the distance between the centres of the lines), indeed it makes far less sense for a thin-thick barline. It's also inconsistent with the other distance settings, which seem to calculate to/from the outer edges of the lines.

**Comment by DmitryArefiev** [comment]
Checked #8975 on Win10, Mac11.13.1, Linux Mint 20.2 - FIXED
