### ISSUE TITLE
[MU4 Issue] Accessibility Tree is inconsistent

### ISSUE THREAD

**Issue by shoogle** [musescore/MuseScore#8982]
There appears to be a conflict between [Qt's Accessible Object Tree](https://doc.qt.io/qt-5/accessible-qwidget.html#the-accessible-object-tree) and MuseScore's custom accessibility tree. We're trying to avoid using Qt's accessibility tree, but apparently it still exists and this has created a conflict, which probably explains why various screen readers are not working properly in MuseScore 4.

- **Working OK with MU4:** Narrator (Windows), Orca (Linux)
    - However, they are only working on objects with specific roles (e.g. ListItem, StaticText, Button, RadioButton)
    - Objects with other roles are ignored.
- **Not working at all with MU4:** NVDA (Windows), VoiceOver (macOS)

The screen readers that don't work appear to see the Qt object tree but not MuseScore's custom tree.

## Steps to reproduce

To observe the conflict, download and install the free analysis program [*Accessibility Insights for Windows*](https://accessibilityinsights.io/), which shows the information made available to assistive devices via UI Automation (UIA).

1. Start _Accessibility Insights for Windows_ running in "Live Inspect" mode
2. Launch MuseScore and locate the 'Scores' button in the Home tab.
3. Hover the mouse cursor over the 'Scores' button and look at the UIA tree in _Accessibility Insights_ (left screenshot).
4. Now use `Tab` and the arrow keys to give the 'Scores' button keyboard focus. See how the UIA tree changes (right screenshot).

Mouse focus (hover or click) | Keyboard focus (`F6`, `Tab`, arrow keys)
:---:|:---:
![image](https://user-images.githubusercontent.com/11011881/131557671-fed98ac3-a6fa-4523-acb7-f40d41d94d1c.png) | ![image](https://user-images.githubusercontent.com/11011881/131561970-02f9ba70-19fc-4189-af59-0b032b6a19de.png)
Qt Accessibility Tree | MuseScore Accessibility Tree

## Expected behaviour

The UIA tree should be the same in both cases.

It should be one contiguous tree that includes all UI elements that are currently visible.

### Mouse focus UIA tree (Qt Accessibility Tree)

- pane 'Desktop'
    - window 'MuseScore 4'
        - ...
        - scroll bar ''
        - radio button ''
        - __radio button ''__
        - radio button ''
        - ...

I think this is simply the Qt-provided Accessible Object Tree for QWindow. It picks up the QML objects because they are ultimately QObjects and children of the application window. The objects are unnamed because we are not using Qt accessibility.

### Keyboard focus UIA tree (MuseScore custom tree)

- window 'Home menu direction is vertical'
    - radio button 'My account'
    - **radio button 'Scores'**
    - radio button 'Add-ons'
    - radio button ...

This is clearly the custom Accessibility Tree created for MuseScore by @igorkorsukov.

### Expected UIA tree for all focus methods

- pane 'Desktop'
    - window 'MuseScore 4'
        - ...
        - _role1_ 'Home menu direction is vertical'
            - _role2_ 'My account'
            - **_role2_ 'Scores'**
            - _role2_ 'Add-ons'
            - _role2_ ...
        - ...

**_role1_ examples:** Pane, Grouping, List, MenuBar, PageTabList
**_role2_ examples:** RadioButton, ListItem, MenuItem, PageTab

The exact roles chosen for _role1_ and _role2_ are not too important as long as speech output makes sense.

## Possible solution

Notice that the "Keyboard focus tree" does not include the root Desktop item or the MuseScore 4 application window, and the Home menu itself has been detected as a "window". This can probably be fixed in [AccessibleItemInterface::parent()](https://github.com/musescore/MuseScore/blob/b7642bb884fdaea30be3a29ca290f4b15e83c4e8/src/framework/accessibility/internal/accessibleiteminterface.cpp#L71-L76). When there is no parent object, this function should return the accessible interface for the application window itself, which can be discovered using [QAccessible::queryAccessibleInterface](https://doc.qt.io/qt-5/qaccessible.html#queryAccessibleInterface).

Similarly, the accessible interface for the application window needs to return as children all accessible interfaces that return it as a parent (i.e. the tree should be consistent in terms of parents and children). It may be necessary to create a new subclass of [QAccessibleInterface](https://doc.qt.io/qt-5/qaccessibleinterface.html) or [QAccessibleWidget](https://doc.qt.io/qt-5/qaccessiblewidget.html) specifically for the application window. It's direct children would probably be the UI sections or subsections used for key navigation (e.g. Home bar, Palettes, etc.). This is where I need help from @igorkorsukov because he is more familiar with the keynav system, QML, and app architecture to register the UI sections as children of the application window.

If the app window gets an accessible interface then it would need to be installed by the factory function [muAccessibleFactory()](https://github.com/musescore/MuseScore/blob/b7642bb884fdaea30be3a29ca290f4b15e83c4e8/src/framework/accessibility/internal/accessibilitycontroller.cpp#L49-L60). If this happens then I think `"mu::accessibility::AccessibleObject"` can probably be removed from the factory function because child objects would be discoverable through the "child()" functions of the application windows's accessible interface. When I tried creating an example project, I only had to [install](https://github.com/shoogle/accessibility-qt-chart-example/blob/872e2d03afcb824cd7ba3003bb81ebebaec47e72/accessiblepieview.cpp#L43) the interface for the [view](https://github.com/shoogle/accessibility-qt-chart-example/blob/872e2d03afcb824cd7ba3003bb81ebebaec47e72/accessiblepieview.h#L73-L91), not [items](https://github.com/shoogle/accessibility-qt-chart-example/blob/872e2d03afcb824cd7ba3003bb81ebebaec47e72/accessiblepieview.h#L42-L70) in the view, so I think that only the top-most custom interface needs to be installed.

**Comment by igorkorsukov** [comment]
Interesting research, thanks.
And you have good suggestions!
