### ISSUE TITLE
[MU4 Inspector + Playback] Arpeggio playback does not update when settings are changed

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#8994]
**To Reproduce**
1. Create a chord with 4 notes
2. Add an arpeggio mark (see image)
![image](https://user-images.githubusercontent.com/21022311/131671645-79c9af02-ab36-46f7-873d-001944650902.png)

3. Play the chord and listen to how all 4 notes can be heard
4. Open the 'Playback' button in the Inspector and change the 'spread delay' to '3.5'
5. Play the chord again and observe that the length of each note is longer (so far so good)
6. Now add 4 more notes to the chord (see image)
![image](https://user-images.githubusercontent.com/21022311/131671932-8254ec91-a248-412c-a473-46912bed8f68.png)

7. Play back the chord again and observe how only the first 4 notes are heard (it has not updated)
8. Alter the 'spread delay' to '3' and play the chord again. Now you should hear the 4 new notes

Summary: in comparison to MS3, these options do not update properly. In addition, the visual playback of the notes does not work in the same way as MS3, where each note is coloured as it is played. This is a lovely visual touch in MS3 that we should bring to MS4.

**Expected behavior**
Work as in MS3

**Comment by DmitryArefiev** [comment]
Hi @Tantacrul , I сan't reproduce it on the latest master.. Can you try again please?

**Comment by Tantacrul** [comment]
Checking the latest nightly... now the option doesn't appear at all in the inspector :(

![image](https://user-images.githubusercontent.com/21022311/132593572-04b18569-bc5f-4879-bb21-652001a89008.png)

**Comment by RomanPudashkin** [comment]
@Tantacrul 

The option is here

<img width="497" alt="Screenshot 2021-09-09 at 09 47 30" src="https://user-images.githubusercontent.com/67867444/132645098-2a40a8ec-ab48-4545-9b37-379c1bd5ff80.png">

**Comment by Tantacrul** [comment]
Oh god. Late night.

Let's not dwell too much on the irony of me not being able to find the option...

**Comment by Tantacrul** [comment]
Yes. @DmitryArefiev. I can confirm this is no longer happening in the latest nightly.
