### ISSUE TITLE
[MU4 Issue] 'Publish' options should not be moveable.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#8995]
**Describe the bug**
It is currently possible to undock and reposition the settings bar in the 'Publish' tab. There is no need to do this.

![image](https://user-images.githubusercontent.com/21022311/131674140-8fc2ca70-03d8-42d9-9617-823df432147f.png)

**Expected behaviour**
Remove the grip handle to prevent users from moving this settings bar at all.

**Comment by Tantacrul** [comment]
Also... just realised we need a 'Print' icon. @jessjwilliamson !

**Comment by jessjwilliamson** [comment]
@Tantacrul we already do!
<img width="229" alt="Screenshot 2021-09-01 at 22 53 08" src="https://user-images.githubusercontent.com/71656189/131750299-f2dc19a5-b592-48b5-9987-5fdba2265bb9.png">

**Comment by Tantacrul** [comment]
Wow. I couldn't find it.

Unicode is F3B7

**Comment by RomanPudashkin** [comment]
Fixed in
https://github.com/musescore/MuseScore/pull/9597
