### ISSUE TITLE
[MU4 Issue] Navigation focus on Main Score when Dialog opened

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9003]
**Describe the bug**
Navigation focus on Main Score when Dialog opened

**To Reproduce**
1. Create a score
2. Open any dialog (for example Edit > Preferences)
3. Use navigation (push Tab button from the keyboard)

**Expected behavior**
Navigation should start from opened dialog (when dialog opened)

**Screenshots**
https://user-images.githubusercontent.com/71372310/131752347-b751c4ab-25e2-4826-9b04-f4e21c32824f.mp4

**Desktop (please complete the following information):**
 Windows 10
Linux

**Comment by Eism** [comment]
Fixed in
#9600
