### ISSUE TITLE
[MU4 Issue] Invisible key/time signatures cause spacing inconsistencies

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#9007]
Here the lower stave (with invisible items) should exactly match the upper (where those items are simply absent):

![invisible-signatures](https://user-images.githubusercontent.com/20604032/131831279-529c8e11-bc28-4d9f-b7cf-090566d8e985.png)

The invisible items seem unproblematic when at the start of a system, whereupon they align to the first note in the bar, but otherwise cause problems (singly and in combination).

**Comment by DmitryArefiev** [comment]
Checked #9007 on Win10, Mac11.13.1, Linux Mint 20.2 - FIXED
