### ISSUE TITLE
[MU4 Issue] Rests should move vertically to avoid beams

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#9009]
Currently, beams which cross rests are moved, i.e. note stems are extended, in order for a beam to avoid collision with a rest.
Instead, the beam should remain at its normal place (as determined by the algorithm) and the _rest_ should be moved vertically, 1sp at a time, until it clears the beam. There must be at least 0.5sp between the rest and the innermost beam.

If the rest cannot be moved far enough (for example, because it will collide with music in another voice), it should be moved as far as possible, and only then should the beam be moved outward to clear it.

![beams-rests](https://user-images.githubusercontent.com/20604032/131846870-74956d52-2873-4785-87b2-2f9a341074bd.png)

Furthermore, if rests are made invisible, they should not affect the beam position/stem lengths at all, but currently they do (the beams behave as though the rests are visible).

**Should fix:**
https://musescore.org/en/node/279080

**Comment by asattely** [comment]
I'll take this one!

**Comment by ModernMozart** [comment]
Quick question, although I'm not sure if this is a good place to ask it. Can we get a style option to automatically beam notes over rests like this when it's in the same beat?

**Comment by MarcSabatella** [comment]
I like the idea of automating it, but a style option is probably not the right way - better to make this part of time signature properties along with the rest of the beaming rules.  That way it's all in one place, and also you have more control.

Best place to discuss how this might work exactly is the forums.

**Comment by Tantacrul** [comment]
Reassigned to @asattely, since Nick ain't around no more :)

**Comment by Nick-Mazuk** [comment]
Hey… I still following along with things and have fixed at least one bug since leaving!

(in all seriousness, though, Aaron or Mike is definitely the better option to fix this bug right now)

**Comment by Tantacrul** [comment]
@Nick-Mazuk - It hasn't gone unnoticed, despite my last clumsily worded message!

**Comment by Tantacrul** [comment]
Bumping to 4.x as a known issue we'll sort out later.

**Comment by oktophonie** [comment]
(Was replaced by https://github.com/musescore/MuseScore/issues/15301 and fixed by https://github.com/musescore/MuseScore/pull/16719)
