### ISSUE TITLE
[MU4 Issue] Dots should be offset rightward to clear flag

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#9013]
In certain situations, where a note has both a flag and a dot, the flag and dot collide.
In these cases the dot should be offset rightward to clear the flag.

Currently, where a note is on a line and the dot is displaced into the space above, MuseScore attempts to avoid the collision by extending the stem length by 0.5sp. This is not a good solution (it creates inconsistent-looking stem lengths, and usually doesn't avoid the collision anyway.)

![dot-flag](https://user-images.githubusercontent.com/20604032/131856614-994612b8-c46c-4a4d-af90-72f71fcae9fd.png)

This adjustment will not be required in every case where a note has both a flag and a dot, but only:

- when the stem is up
- when the flag symbol actually extends vertically into the space where the dot is drawn; this depends on the stem length and the height of the specific flag glyph itself (which also varies in different fonts)

In the case of a chord, the dots should always align, so if one needs to be offset, they must all be offset.

**Should fix:**
https://musescore.org/en/node/323759

**Comment by DmitryArefiev** [comment]
Checked #9013 on Win10, Mac11.13.1, Linux Mint 20.2 - FIXED
