### ISSUE TITLE
[MU4 Issue] Crash when clicking on the score

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#9015]
**Describe the bug**
Open a new score and click on any element in the score. Musescore Crashes

**To Reproduce**
1. Open a new Score in Musescore 4
2. Click on any element
3. Musescore crashs

**Expected behavior**
No crash and instead show the Image on the first page

**Desktop (please complete the following information):**
 - OS: Windows 10 (NightlyBuild from 3. Sept. 2021)

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/9021
