### ISSUE TITLE
[MU4 Issue] Bottom bar in "Home" tab disappears when switching to another tab

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#9018]
**Describe the bug**
The bar at the bottom of the Home tab disappears when switching to "Score" tab and back again

**To Reproduce**
1. Open Musescore - the bar ath the bottom with the buttons "New" and "Open another..." ist visible
2. Switch to "Score" tab
3. ScSwitch back to "Home" tab
4. The Bar with the Buttons is unvisible
5. Resize window and the bar appears

**Expected behavior**
Allways show the buttons "New" and "Open another..." in "Home" tab

**Screenshots**
Before:
![vorher](https://user-images.githubusercontent.com/63284090/131970279-6e63145a-f189-41a9-b66c-76b7513dd3ad.PNG)

After: 
![nachher](https://user-images.githubusercontent.com/63284090/131970295-09b77eca-af03-4923-b5cc-5abc81ff7160.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by cbjeukendrup** [comment]
See also: https://github.com/musescore/MuseScore/issues/9004#issuecomment-910855679

**Comment by DmitryArefiev** [comment]
Checked #9313, #9004, #9016, #9018 on Win10, Mac11, LinuxMint 20 - FIXED
