### ISSUE TITLE
[MU4 Issue] Select correct brace symbol for each system independently

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#9020]
MuseScore has access to four alternative brace symbols which are to be used according to the number of staves that they span, currently defined as:

- 1 stave: `braceSmall`
- 2 staves: `brace` (the default glyph)
- 3 staves: `braceLarge`
- 4+ staves: `braceLarger`

(see: https://w3c.github.io/smufl/latest/tables/staff-brackets-and-dividers.html)

However, this is calculated using the number of staves belonging to the instrument. Instead, it should be calculated _for each system independently_, based on how many staves the brace needs to span on that system. In, for example, a piano piece, a system with two staves will use `brace`, a system with 3 will use `braceLarge`, etc.

**Should fix:**
https://musescore.org/en/node/322436
(the matter discussed in that issue of aligning the starts of systems to be fixed by #8968)

**Comment by Jojo-Schmitz** [comment]
If you prefix the commit title with "Fix #322436:" that issue would (also) get auto-closed on merging this PR
