### ISSUE TITLE
[MU4 Issue] Use opticalCenter metadata to centre dynamics on notes

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#9027]
SMuFL metadata provides an `opticalCenter` for dynamics glyphs that should be used for centering dynamics on noteheads; see:
https://w3c.github.io/smufl/latest/specification/aligning-dynamics.html

![optical-center](https://user-images.githubusercontent.com/20604032/132033619-8c7cc684-6aae-4ed1-8442-4321937c504c.png)

We should read this data and use it (at least optionally) for centering dynamics. (So far not even Dorico uses this info!)

**Comment by Jojo-Schmitz** [comment]
But we're not using a **_pp_** glyph, instead two _**p**_ ones, creates the need of calulating the center of those 2 (ot 3 of 4...) `opticatCenter`s

**Comment by oktophonie** [comment]
Two adjacent _p_s are actually combined into a _pp_ ligature when rendered, so it's still a single glyph.

**Comment by oktophonie** [comment]
This will have to wait until we switch over to use the music font (e.g. Leland) rather than the musical text font (e.g. Leland Text) for dynamic symbols, so probably after MU4.

**Comment by Nick-Mazuk** [comment]
Note to self: when https://github.com/musescore/MuseScore/pull/9359 is merged, I can continue work on this

**Comment by oktophonie** [comment]
Stretch goal:

Where a dynamic is on the first note of a bar and it collides with a barline connecting an adjacent stave, offset it rightwards to clear the barline. (Generally this will only affect longer dynamics like _fff_ and _ppp_ etc).

![stretch](https://user-images.githubusercontent.com/20604032/136162293-e39c0406-2a23-4fc0-b199-7f7ad68ebb35.png)

**Comment by DmitryArefiev** [comment]
Checked #9027 on Win10, Mac11, LinuxMint 20 - DONE (compared with previous builds)
