### ISSUE TITLE
[MU4 Issue] Can't see appearance properties pop-up while working on score

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9030]
**Describe the bug**
The appearance pop-up that shows info such as current offset etc. disappears as soon as you click away from it, meaning that you can't see the values update as you make adjustments directly on the score.

**To Reproduce**
1. Create a new score, add a note and ensure it's selected
2. In the inspector/properties panel, click "Appearance" to see the offset/leading etc.
3. Now try dragging the note left/right to change the leading space
4. The appearance pop-up has disappeared, meaning you can't see the new leading space value.  
5. In fact even if you click "Appearance" to show the pop-up again it doesn't show the new value (currently it won't update until you change the selection. NB this specific issue is already fixed in the PR I'm working on).

**Expected behavior**
As per MU3, you should be able to see key values in the inspector like leading/offset etc. update as you make adjustments on the score.
Confirmed with @Tantacrul that the intention wasn't for this pop-up to auto-disappear on changing focus back to the score.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by Tantacrul** [comment]
thanks for logging this!

**Comment by san-coding** [comment]
Hey, I am new to open source , can I work on this

**Comment by wizofaus** [comment]
In principle anyone can *work* on any open source github issue, but do note this is already assigned to another developer who's part of the core MuseScore dev team.  Either way @Tantacrul probably should specify first what the cases where the appearance popup-up *should* close are!  E.g. if you click on a different element that doesn't have "appearance" settings (not sure there are any?), but certainly if you deselect all elements, and presumably if you click elsewhere in the properties panel (esp. on the "Appearance" button itself).

**Comment by wizofaus** [comment]
Looks like it's been fixed, closing.
