### ISSUE TITLE
Change color of UI Separators, for a better workflow without distractions

### ISSUE THREAD

**Issue by PhalanXdarKen** [musescore/MuseScore#9032]
Hi there, how can I change the color of the separator lines between UI areas and workspace? I mean that white lines, distract so much. I´d like them to be dark grey

![fdgfhdgfdgfdg](https://user-images.githubusercontent.com/88815060/132141101-44d1c123-2e15-466b-b89f-3b2ee78716cf.png)

**Comment by RomanPudashkin** [comment]
Please, use musescore.org for such questions
