### ISSUE TITLE
[MU4 Issue] Accidentals are stacking on top of each other

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9035]
Changing an existing accidental against a note (e.g. from a sharp to a flat, or vice-versa) adds a new accidental on top of the existing accidental. This also happens when changing the pitch of a note. 

See video for demonstration: 

https://user-images.githubusercontent.com/86290556/132199475-16ab4c9e-5e34-425c-8524-0eeeb4699265.mov

 
**Expected behavior**
Changes to a note's accidental should replace, not overlap, existing accidentals (as per MS3.6).

MacBook Air M1, MacOS 11.5.2

**Comment by wizofaus** [comment]
There's something very wrong with that build in general, I can't even get that far (just crashes on opening a score or if not, the moment I try to modify anything).

**Comment by bkunda** [comment]
Yes there is a big crash problem with the latest nightly (not sure about previous builds as I've only just returned to work today). Basically everything I do is triggering a crash.

**Comment by wizofaus** [comment]
I think it might be that paintDiagnostic function @igorkorsukov  - I had to comment it out.

**Comment by bkunda** [comment]
I think I'll raise a separate issue for the crashes (and link it here too for reference).

**Comment by igorkorsukov** [comment]
> I think it might be that paintDiagnostic function @igorkorsukov - I had to comment it out.
> Though I also just had it crash in `AudioOutputHandler::outputParams` (line 58 of audiooutputhandler.cpp)

I disabled `paintDiagnostic` here https://github.com/musescore/MuseScore/pull/9036

**Comment by igorkorsukov** [comment]
fixed here https://github.com/musescore/MuseScore/pull/9036
