### ISSUE TITLE
[MU4 Issue] Frequent crashes when attempting to create a new score

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9038]
The latest nightly build is crashing easily when attempting to perform a range of functions.

Demo videos show crashes on attempt to create a new score and load a score from a template: 

https://user-images.githubusercontent.com/86290556/132208010-bee3faec-d556-4d85-9a55-a583e7d7de06.mov

https://user-images.githubusercontent.com/86290556/132208019-a61ebe6d-1d2d-467e-b16e-364e1762c5fd.mov

MacBook Air M1, MacOS 11.5.2
Replicated on MacBook Air 2020, MacOS 10.15.7

**Additional context**
@wizofaus notes possible link with [#9035](https://github.com/musescore/MuseScore/issues/9035)

**Comment by igorkorsukov** [comment]
fixed here https://github.com/musescore/MuseScore/pull/9036
