### ISSUE TITLE
[MU4 Issue] Multiple clefs and key signatures are being triggered on note entry

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9039]
Entering notes into a new bar triggers a duplicate instance of clefs, bar numbers and key signatures in later bars. 

See demo video:
(Note: crash on first attempt has been logged in #9038) 

https://user-images.githubusercontent.com/86290556/132208923-703d41f9-9b41-41d8-b0e9-6e9e13f02a5e.mp4

**Expected behavior**
These duplicate instances should not happen

MacBook Air M1, MacOS 11.5.2

**Comment by igorkorsukov** [comment]
fixed here https://github.com/musescore/MuseScore/pull/9036
