### ISSUE TITLE
[MU4 Issue] [VJ] 'Max grand staff distance' behaves unpredictably

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#9041]
Increasing 'Max. grand staff distance' works up to a point as expected, but stops at a certain value - possibly when limited by the 'Max staff distance' or 'Max page fill distance' settings? - and thereafter has no further effect on stave spacing, _but_ does seem to continue causing the curly brace to get thicker and thicker.

Possibly the brace is being scaled (horizontally) according to the theoretical distance that 'Max. grand staff distance' specifies, but not according to the actual spacing of the staves as they appear on the page.

<img width="2590" alt="bracket-fun" src="https://user-images.githubusercontent.com/20604032/132220249-3fbd2feb-78c1-4f76-8ab0-110b5ec0c337.png">

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.org/en/node/326130

**Comment by njvdberg** [comment]
> We'd need so somehow detect and use the actual akkolade distance rather then using the max.

That's indeed what I'm trying to do :smile:

**Comment by njvdberg** [comment]
See PR #9903
