### ISSUE TITLE
[MU4 Issue] [VJ] Music should automatically clear headers and footers

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#9043]
A footer is positioned relative to the bottom page margin, according to the setting in 'Style -> Text Styles -> Footer -> Offset -> Y'. (The default bottom margin is 15mm, the default footer-y-offset is 5mm, so the footer appears 10mm above the bottom of the page.)

The value in 'Style -> Page -> Music bottom margin' determines the distance between the bottom page margin and the music on the bottom stave (measuring to the lowest point of the music on the stave, not to the stave itself).

When the footer is tall (for example if it has several lines) there is a risk of it colliding with the music on the bottom stave, unless the 'Music bottom margin' is increased accordingly.

There is a relatively simple solution to avoid these collisions automatically. If the footer itself extends inside the margin (i.e. if its height is, with default settings, more than 5mm) then the 'Music bottom margin' value should be measured from the top of the footer, not from the bottom page margin.

For consistency this should be applied to the header/'Music top margin' in the same way. (With the default styles, this means the measurement will always be being made from the bottom of the header (page number), since this sits just inside the top margin, i.e. with a y-offset of 0.)

**Comment by DmitryArefiev** [comment]
Checked #9043 on Win10, Mac11.13.1, Linux Mint 20.2 - DONE
