### ISSUE TITLE
Guide windows appearing on top of section it is trying to explain

### ISSUE THREAD

**Issue by Hugo4IT** [musescore/MuseScore#9051]
Hello! I'm very new to musescore and scoring in general, my music teacher used it and when I found it was open-source I was sold... for free I guess. Because I am new, I wanted to follow the included guide but came across this:

![image](https://user-images.githubusercontent.com/48245742/132288300-b3422930-fbd2-4c98-8af7-36db022c758f.png)

I was searching for what it was trying to explain, until I noticed a white line just above the window. Turns out it was trying to explain something it was blocking the view of, this happened in the last guide window as well but I didn't notice it because I thought it was talking about something else.

Guide windows I\'ve noticed to be misplaced:
- File toolbar
- Playback controls toolbar

My system:
- OS: Pop!_OS 21.04 x86_64 (Ubuntu based, GNOME 3.38.4 environment, by system76)
- Musescore version: 3.2.3+dfsg2-9 (installed with `sudo apt install musescore3`)
- WindowManager: Mutter, theme Pop
- Kernel: Kernel: 5.11.0-7633-generic
- Specs: AMD Ryzen 5 3600x; 16Gb DDR4 2400Mhz; RTX 2060 Super; Linux dualboot, installed on 256Gb nvme SSD

**Comment by wizofaus** [comment]
As I understand it the "tours" feature won't be part of MuseScore 4, so this is best logged at musescore.org in case it does ever get brought back or v3.x lives on in some form.

**Comment by Hugo4IT** [comment]
So will musescore 4 be i tuitive enough for complete beginners? Or will it be focused more towards already experienced people

**Comment by RomanPudashkin** [comment]
> So will musescore 4 be intuitive enough for complete beginners?
Yes, it will
