### ISSUE TITLE
[MU4 Issue] Tooltips appearing with undesirable animation

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9056]
Tooltips are currently appearing with an undesirable animation, which appears as if scooting/swooping in from the right.

See demo video: https://www.dropbox.com/s/koft4o07wu472kc/tooltip-animation.mov?dl=0

Expected behaviour: tool tips should simply appear (without animated transitions), as per MU3.6.

MacBook Air M1, MacOS 11.5.2

**Comment by HemantAntony** [comment]
This appears to be fixed in the latest master

**Comment by boryskuzmenko** [comment]
Hi, @HemantAntony. Thanks for your fix!
The animation is removed but there's still some delay before a tip appearing in MU4. About 1 sec. If you see MU3 behavior there's no delay. Could you please fix this as well?

https://user-images.githubusercontent.com/101250347/166307067-4ac036fb-1dd6-43bd-bd9e-594a83ac3df0.mov

**Comment by HemantAntony** [comment]
@boryskuzmenko I never made a fix, I just commented on whether this issue occurs or not. But I'll take the thanks anyway :)

#11504 removes the tooltip intervals for all buttons in MU4 (So not just the toolbar). Tell me if this is not wanted

**Comment by boryskuzmenko** [comment]
@HemantAntony Works great now. Thanks!
**FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

**Comment by boryskuzmenko** [comment]
🟡 **Partly FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

See the issue https://github.com/musescore/MuseScore/issues/11876 for more details
