### ISSUE TITLE
[MU4 Issue] Hairpin text superimpose on Hairpin icon on the score

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9060]
**Describe the bug**
Hairpin text superimpose on Hairpin icon

**To Reproduce**
1. Create a score
2. Add a hairpin on the score (from Palettes tab)
3. Add hairpintext (Click on hairpin > open Properties tab> click "Text" button > enter text in the "Begginning text" field)

**Expected behavior**
Hairpin text should not superimpose on Hairpin icon

**Screenshots**
![2021-09-07 14_14_55-Untitled](https://user-images.githubusercontent.com/71372310/132337847-55ff704c-c35b-42b8-969b-c9ad78cdc07d.jpg)

**Desktop (please complete the following information):**
Windows 10

**Comment by Tantacrul** [comment]
This issue no longer happens.
