### ISSUE TITLE
[MU4 Issue] Another empty window appears after opening a recent score with double click

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9066]
**Describe the bug**
Another MU empty window appears after opening a recent score from Home>Scores with a double click

**To Reproduce**
1. Open MU
2. Home>Scores: Open a recent score with double click - **MU opens two windows, one of which is grey out (and goes to foreground)**  - video attached below

**Expected behavior**
MU opens only one window with active score (how MU3 does)

**Desktop (please complete the following information):**
 - Win10
 - Mac10.15.6
 - Linux 20.2 (the second empty window has only top toolbar)

**Additional context**
Also, a graphic artifact appears for a moment right before opening two MU windows (logged separately as #9110)

**Screenshots**
![double click_win](https://user-images.githubusercontent.com/90187801/132396638-6b3cc193-d359-4c9c-a3f1-538b1d3b221b.gif)

**Comment by DmitryArefiev** [comment]
Tested on latest master build (Win10, Mac11, LinuxMint 20) - STILL OCCURS

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9915

**Comment by DmitryArefiev** [comment]
Tested on latest master build on Win10, Mac12, LinuxMint 20 - FIXED
