### ISSUE TITLE
[MU4 Issue] Remove background stripes in new score/time signature popup

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9074]
There are undesirable background stripes in the time signature popup of the new score wizard.

These are not part of the original design (see Figma master file) and should be removed.

<img width="1139" alt="Screenshot 2021-09-08 at 23 25 17" src="https://user-images.githubusercontent.com/86290556/132518008-1e1d83bc-e551-4dbc-b7d7-97212d65f85a.png">

To access this popup:
1. Open the new score dialog (start MuseScore and select "new score")
2. Click "Next"
3. Click on the time signature selector button 

MacBook Air M1, MacOS 11.5.2

**Comment by Eism** [comment]
fixed on #9147
