### ISSUE TITLE
[MU4 Issue] Score view doesn't refresh properly after adding notes in auto repeat mode (holding a key) on Mac/Linux

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9079]
**Describe the bug**
Score view doesn't refresh properly after adding notes in auto repeat mode (holding a key)

**To Reproduce**
1. Select bar
2. On keyboard, press and hold C (to add C note)

**Expected behavior**
Score should refresh after adding each note

**Screenshots**
![auto repeat](https://user-images.githubusercontent.com/90187801/132545599-f18ea508-6177-4ab9-ab37-5b80a2469de3.gif)

**Desktop**
 - Mac10.15.6
 - Linux Mint 20.2
(Doesn't occur on Win10)

**Comment by HemantAntony** [comment]
This appears to be fixed, if you meant the visible note input stop

https://user-images.githubusercontent.com/88136054/152645446-706a5fcc-9710-4872-a531-875119bdb36d.mp4

.

**Comment by DmitryArefiev** [comment]
@cbjeukendrup You're right, doesn't occur now. Thanks for checking!

Tested on Win10, Mac12, LinuxMint 20.2 - FIXED     

Closing

**Comment by DmitryArefiev** [comment]
@HemantAntony  Ohhh.. yeah! Sorry!
