### ISSUE TITLE
[MU4 Issue] Empty pop-up appears after clicking 3 dots on any Instrument panel tab

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9082]
**Describe the bug**
Empty pop-up appears after clicking 3 dots on any Instrument panel tab

**To Reproduce**
1. Create a score
2. Click 3 dots near Instrument panel tab
3. Drag&Drop instrument panel

**Expected behavior**
No empty pop up appears

**Screenshots**

https://user-images.githubusercontent.com/71372310/132587943-c30dc788-4e75-4598-b40d-a0551a81b62f.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
