### ISSUE TITLE
[MU4 Issue] No icons displayed in Styles dialog

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9087]
**Describe the bug**
No icons displayed in Styles dialog

**To Reproduce**
1. Create a score
2. Opend Style dialog (Upper menu > Format > Styles > Page)
3. Observe icons

**Expected behavior**
Icons displayed

**Screenshots**
<img width="937" alt="Screenshot 2021-09-08 at 12 24 11" src="https://user-images.githubusercontent.com/71372310/132592287-466c2421-b7d6-4992-b2a6-4ca85d617994.png">

**Desktop (please complete the following information):**
MacOS only

**Comment by cbjeukendrup** [comment]
Indeed a macOS only issue. The icons font does not work correctly in some places in the app. The icons in the Palettes are also rendered wrong on macOS:
<img width="300" alt="Schermafbeelding 2021-09-09 om 00 11 19" src="https://user-images.githubusercontent.com/48658420/132592743-7a200a99-d69b-4131-85af-0831d085c46d.png">
All icons that are in `StyledIconLabel`s in QML are fine though.

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/9741
