### ISSUE TITLE
[MU4 Issue] Redefined keyboard shortcuts not active until app restart 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9089]
Changing a keyboard shortcut definition requires app restart in order to take effect. 

See video for demonstration: https://www.dropbox.com/s/epx64valt7h2toz/app-needs-restarting-for-shortcuts-to-work.mov?dl=0

**Expected behavior**
Redefining a keyboard shortcut should take effect immediately (i.e. the app should not need to be restarted for the new definition to take effect).

MacOS 11.5.2, MacBook Air M1

**Background context**
Mentioned by @wizofaus in comments to #8898 
Possibly connected to a series of problems around keyboard shortcuts, including also #9088

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10089

**Comment by DmitryArefiev** [comment]
Tested on latest master build (Win10, Mac12, LinuxMint 20.2) - FIXED

Found a minor issue (shortcut highlights updated only after relaunch). Will log it separately
