### ISSUE TITLE
[MU4 Issue] Musescore crashes with SIGSEGV when clicking glissandis on score i made (attached) 

### ISSUE THREAD

**Issue by lomnom** [musescore/MuseScore#9091]
**Describe the bug**
Musescore crashes with SIGSEGV when opening score i made on a 2012 macbook air running Mojave

**To Reproduce**
1. open the score i attached in musescore
2. click on some of the glissandis 
3. cRasH

**Expected behavior**
i can click the glissandis without a crash

**Screenshots**
https://user-images.githubusercontent.com/57130071/132665534-98c5aad6-8608-4e4b-9898-f6fdfd91152d.mov

**Desktop (please complete the following information):**
 - MACOS mojave

**Additional context**
The score:  [glissadell.mscz.zip](https://github.com/musescore/MuseScore/files/7135515/glissadell.mscz.zip) (https://musescore.com/user/38691124/scores/7003388)
Crash log: https://gist.github.com/lomnom/5ada60dd8a6048d25faddba8aeaf2a45
Sometimes it crashes when opening  
The wrong glissandis are also highlighted when clicking

**Comment by lomnom** [comment]
Whoops, just realised i was using musescore 3

**Comment by Jojo-Schmitz** [comment]
And MuseScore 3.6.2 on Windows 10 doesn't crash on it either
