### ISSUE TITLE
[MU4 Issue] Performance: MU4 is very slow or compleatly freezes when adding multiple articulations in a big score 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9094]
**Describe the bug**
MU4 is very slow or compleatly freezes when adding multiple articulations in a big score 

**To Reproduce**
1. Open [Big_Score.zip](https://github.com/musescore/MuseScore/files/7138238/Big_Score.zip)
2. Select top staff in the first system 
3. Add an accent (see videos below to compare MU4 and MU3)

**Expected behavior**
Performance should be the same as in MU3

**Desktop (please complete the following information):**

**MU4**
https://user-images.githubusercontent.com/90187801/132726179-2c3a0995-e2d7-454b-82ca-3c1020f3c9d4.mp4
**MU3**
https://user-images.githubusercontent.com/90187801/132726205-a3016b2a-d609-4245-a980-a8d60d1dfe6e.mp4

**Comment by DmitryArefiev** [comment]
Can be related to #8440

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9854

**Comment by RobFog** [comment]
compleatly → completely

**Comment by DmitryArefiev** [comment]
Tested on master build (Win10, Mac11, LinuxMint 20) - FIXED
