### ISSUE TITLE
[MU4 Issue] Edit staff dialog | Reset to template doesn't reset all settings

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9107]
**Describe the bug**
Turns out this bug is also in MU3 but "Reset to template" doesn't fully reset all customisations made in the Edit staff dialog, requires multiple firings to fully reset.

**To Reproduce**
1. Access "Staff/part properties" from the context menu for a staff
2. click on 'Advanced style properties'
3. Toggle all available checkboxes (Show clef...Stemless) and choose a different Notehead scheme
4. Choose "Standard" from the template dropdown
5. Click "Reset to template"
6. Note that only the first 4 checkboxes are correctly reset, Notehead scheme is not
7. Click "Reset to template" again - remaining 2 checkboxes are reset. Notehead scheme is not.
8. Click "Reset to template" again - finally the Notehead scheme is also reset.

**Expected behavior**
Reset to template should do exactly that - reset all options as per the template.

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10

**Additional context**
Why is "Reset to Template" available if there's no template selected (or equally, why is it even possible not to have a template selected?)
I don't understand the point of the empty but selectable rectangle under the fully capitalised "STANDARD STAFF" at the top of this dialog?  It changes to "Standard" after clicking reset to template, but still can't be edited in any way.

**Comment by Tantacrul** [comment]
Although there still be remaining MS3 jank here, the particular problem you've described has been fixed. Cheers!
