### ISSUE TITLE
[MU4 Issue] Graphical artifact when switching to Scores from other tabs

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9110]
**To Reproduce**
1. Open MU4
2. Switch from Home to Score
3. Switch from Publish to Score
4. Switch from DevTools to Score 
(see video below)

**Expected behavior**
no artifacts (parts of the left menu in the middle of screen)

**Screenshots**

https://user-images.githubusercontent.com/90187801/133100472-91d0bdae-e06a-48d1-b3dd-0af26c906864.mp4

**Desktop (please complete the following information):**
 - Win10
 - Mac10.15.6 (sometimes happens - see the comment with a video below) 
 - Linux Mint 20.2 (was not able to reproduce for now)

**Comment by cbjeukendrup** [comment]
Also sometimes happens on macOS. Normally, macOS is so quick that you can't see it, but sometimes it still happens.

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Oh cool! Will add it to the description. Thanks!

**Comment by DmitryArefiev** [comment]
Can't reproduce on latest master build (Win10, Mac11.6)

Closing 

@cbjeukendrup Please try on your Mac when you have time. Thanks!

**Comment by cbjeukendrup** [comment]
Actually I just reproduced it on Mac, using the same steps as in my previous comment here (i.e. open a second score that will open in a second instance of the app).

**Comment by DmitryArefiev** [comment]
Hmm.. I see on my mac it's only like a flash. And comparing with a previous old builds it's much better.
But let's leave it as open

**Comment by cbjeukendrup** [comment]
Yes, that's true, it certainly has improved. And it is not disruptive anyway, so should be low priority.

**Comment by DmitryArefiev** [comment]
Hi @cbjeukendrup Can you try it again on you Mac please? It should be much better on the latest master

**Comment by cbjeukendrup** [comment]
Indeed, it seems fixed now!

**Comment by DmitryArefiev** [comment]
Cool! Closing then

Thank you!

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
