### ISSUE TITLE
Images do not display on MS4 scores. They also need an Inspector view too.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9122]
Inspector details are in this document:
https://www.dropbox.com/s/kkeh462rl37cfyy/Inspector_All_Remaining_Popups_V01.pdf?dl=0

The design mockup UI for images in the inspector is in Figma

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by DmitryArefiev** [comment]
Checked #9122  on Win10, Mac11.13.1, Linux Mint 20.2 - FIXED

Found #9265 during testing
