### ISSUE TITLE
[MU4 Issue] Adding Glissando to the score leads to crash

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9123]
**Describe the bug**
Adding Glissando to the score leads to crash

**To Reproduce**
1. Create a score
2. Add Glissando to the score (Palettes > Glissando)

**Expected behavior**
Glissando added

**Screenshots**

https://user-images.githubusercontent.com/71372310/133285007-bc1f7b37-e77d-4287-ad9b-abf8f44e2052.mp4

https://user-images.githubusercontent.com/71372310/133285013-cc70f4dc-535d-4ebb-a39f-e2b9d88fdacb.mp4

<img width="1159" alt="Screenshot 2021-09-06 at 16 48 35" src="https://user-images.githubusercontent.com/71372310/133285016-1e0291f8-7f33-4550-b146-08e0b4495c1c.png">

**Desktop (please complete the following information):**
Windows 10
MacOS

**Comment by wizofaus** [comment]
Specifically adding glissandi from the palette (or by copy & paste) to *rests* causes this. Not quite sure why it only seems to affect glissandi, but for whatever reason they have no parent, which causes this crash.

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by DmitryArefiev** [comment]
Checked #9123 on Win10, Mac11.13.1, Linux Mint 20.2 - FIXED
