### ISSUE TITLE
[MU4 Issue] Time Signature selected if add another time signature

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9124]
**Describe the bug**
Time Signature selected if add another time signature

**To Reproduce**
1. Create a score with two time signature rows
2. Add new Time Signature (Palettes > Time Signature)

**Expected behavior**
Palettes should not look like selected if they are not selected

**Screenshots**
https://user-images.githubusercontent.com/71372310/133285678-b43ac661-9ae4-46ba-8edc-3b5061ab93ae.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by wizofaus** [comment]
This doesn't seem to be specific to time signatures and happens in v3 too, with a slight difference - any time you add something from a palette, then collapse and re-expand the palette, it highlights the item you just added, regardless of what the selection in the score is.
The only difference with v4 is that it always leaves the palette item highlighted even without collapsing/expanding.
As far as I can tell which palette item is currently selected doesn't actually mean anything - yet it usefully *could* if, for instance, there was a shortcut to add the currently highlighted palette item to the score wherever you are. But I would think for now it's simpler just to never leave palette items highlighted.
@Tantacrul

**Comment by wizofaus** [comment]
Actually, I just checked and there *is* such a command "apply-current-palette-element" in v3, that has no shortcut key by default, but you can assign one that such that it does indeed add whatever the last used palette item was to whatever's selected in the score, and yes, it works for key signatures.  That's one of the many actions I haven't yet ported across to v4 but it's questionable whether it makes sense to do so, there's probably only fairly limited circumstances it would be useful. But without having this functionality then having a "current" item showing as selected in the palettes isn't useful.

**Comment by Tantacrul** [comment]
Issue does not seem to still be happening. Closing for now. Please tell me if I'm wrong and I'll reopen.
