### ISSUE TITLE
[MU4 Issue] Selecting "New Score" triggers crash in MacOS

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9128]
Clicking on "New Score" in the new score wizard triggers a crash in MacOS.

https://user-images.githubusercontent.com/86290556/133413648-4c9b9580-74fb-424c-88b5-d084e6f270f7.mov

See crash report here: https://www.dropbox.com/s/xn6fpxz9hixbjpy/crash-1.rtf?dl=0

**Desktop (please complete the following information):**
 MacBook Air M1, MacOS 11.5.2
Note: Could not reproduce in Windows 10

**Comment by jessjwilliamson** [comment]
This is the same with Creating a new customised score through New Score wizard as well! Very important issue!

**Comment by RomanPudashkin** [comment]
I'm working on it
