### ISSUE TITLE
[MU4 Issue] Buttons in note input bar are in wrong order and/or missing

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9129]
The following buttons need correcting in the note input bar (as per the Figma master design file):

1. Note duration buttons: reverse current order
2. Add double-flat button
3. Add double-short button
4. Add voice 2 button

<img width="1515" alt="Screenshot 2021-09-15 at 20 21 01" src="https://user-images.githubusercontent.com/86290556/133416564-ba799f64-af6e-4ab8-ad64-8b1ca903ce00.png">

MacBook Air M1, MacOS 11.5.2
Reproduced in Windows 10

**Comment by Mystic-Slice** [comment]
Hi! @bkunda I would like to work on this issue. 
Can you let me know the order of the hidden items in the first section? Items like 128th,256th,512th, and 1024th notes

**Comment by bkunda** [comment]
HI Ashwath!
The order will be (L-R): shortest note values – largest note values.
So 1024th, 512th, 256th, 128th, 64th, 32nd, 16th, 8th, 1/4, 1/2, whole note.
But of course only from the 64th note downward is shown is the panel by default :-) 
All best!
Bradley

**Comment by Jojo-Schmitz** [comment]
... brevis, longa
