### ISSUE TITLE
[MU4 Issue] Order of templates categories is incorrect in MacOS

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9131]
Three issues here:
1. The list of categories in the "Choose from template" dialog is out of order in MacOS.
2. Please rename the category "templates" to "My Templates" (note capitalisation) and place at the bottom of the list.
3. Please rename the tab item "Choose from template" to "Create from template"

Current list:
<img width="1273" alt="Screenshot 2021-09-15 at 20 42 15" src="https://user-images.githubusercontent.com/86290556/133419417-b8ce9725-569f-402a-b31c-ad8c2ad4639f.png">

**Expected behavior**

1. Order of categories should be as per numbered list here: https://github.com/musescore/MuseScore/tree/master/share/templates
2. "templates" should be renamed to "My Templates" and appear at the bottom of the list
3. "Choose from template" tab label should read "Create from template"
MacBook Air M1, MacOS 11.5.2

**Comment by Jojo-Schmitz** [comment]
and "template" should get renamed to "Templates", "Choose from template" to "Choose from templates"
"My templates might better shown at the top, or just after General, like in MuseScore 3

**Comment by Jojo-Schmitz** [comment]
Not sure about  "My Templates", the capitalization, didn't we just recently decided to no longer do that "Title Case" thing but use "Sentence case" all the way?

**Comment by bkunda** [comment]
I suggest "My Templates" because it apparently stores user-created templates. In this case, "templates" on its own does not communicate this. 

You are right about sentence case, and I'm usually a stickler for consistency in this kind of thing. In this dialog, however, I don't actually mind the use of title case (E.g. "Voice and piano" looks somewhat odd by comparison). But I'm happy to be convinced otherwise on this one. 

"Choose from templates" (in the plural) is technically correct, but I don't think "choose from template" (in the singular) is necessarily _incorrect_. In this case, the user is choosing to create a new score from an existing template (just one, not many). They are of course selecting to do this from a list of many templates. So both options are probably acceptable.

**Comment by Jojo-Schmitz** [comment]
"Choose template", not "Choose **from** template"

**Comment by bkunda** [comment]
I take your point, but actually I think the UI copy for these tab items actually works well the way it is. Having three words instead of two makes for a nice visual distinction between the two tabs. My preference would be to leave it and to focus on addressing the category ordering.

**Comment by Jojo-Schmitz** [comment]
Then it is plural...
Native speakers to the front?

**Comment by wizofaus** [comment]
I'm with you JoJo, either "Choose template" or "Choose from templates", or even better "Create from template".  You can't really choose from a single item.

**Comment by bkunda** [comment]
Ok let it be "Choose from templates" then. I shall update the issue above so our poor devs don't have to go trawling through this conversation feed 😅

**Comment by DmitryArefiev** [comment]
Fixed in #10828
