### ISSUE TITLE
[MU4 Issue] Glitchy squares appear on Time Signature, NSW

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9134]
**Describe the bug**
These squares are on the time signature pop up in New Score Wizard.

**Screenshots**
<img width="400" alt="Screenshot 2021-09-15 at 16 52 07" src="https://user-images.githubusercontent.com/71656189/133466856-258fe8dc-bebc-491b-b15b-49ad05ad0a2d.png">

**Desktop (please complete the following information):**
 - OS: Mac OS

**Comment by Eism** [comment]
duplicate?
https://github.com/musescore/MuseScore/issues/9074

**Comment by jessjwilliamson** [comment]
Woops! Yes, this can be closed
