### ISSUE TITLE
[MU4 Issue] Ambitus items overlays in Properties tab

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9139]
**Describe the bug**
Ambitus items overlays in Properties tab (screenshot with bug added)

**To Reproduce**
1. Create a score 
2. Add Ambitus on the score (Palettes tab > Ambitus > drag&drop Ambitus on the score)
3. Select Ambitus
4. Open Propertiest tab

**Expected behavior**
Ambitus items displayed in Properties tab

**Screenshots**
![Ambitus](https://user-images.githubusercontent.com/71372310/133508950-b58cf6c2-eff6-44cb-a245-9ee897410ef6.jpg)

**Desktop (please complete the following information):**
Windows 10
MacOS

**Comment by cbjeukendrup** [comment]
If nobody else is working on this yet, I'm working on it :)
