### ISSUE TITLE
[MU4 Issue] Cannot use `⌘` shortcuts when editing text

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#9142]
**Describe the bug**

In text boxes, I cannot use `⌘` (command) related shortcuts when editing text. From what I can tell, this applies to all text boxes (both single-line and multiline).

Typically, at least on macOS, the following keyboard shortcuts can be used:

- `⌘ backspace`: deletes the entire line of text, similar to `⌥ backspace` (which deletes the previous word and works correctly)
- `⌘ ArrowLeft`: moves the cursor to the start of the line
- `⌘ ArrowRight`: moves the cursor to the end of the line
- `⌘ ArrowUp`: moves the cursor to start of the first line of text (works correctly)
- `⌘ ArrowDown`: moves the cursor to end of the last line of text (works correctly)

There may be more that I haven't found. As an avid keyboard user, these shortcomings are immediately noticeable and annoying.

**To Reproduce**
1. Create new file
2. Navigate to any text field (e.g., File > Score Properties > Work Title
3. Write some text and try using the above shortcuts

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2

**Additional context**

This may only be an issue on macOS. Don't have a Windows machine to test any alternatives with `Ctrl`.

**Comment by wizofaus** [comment]
Ctrl+Left and Ctrl+Right move to the previous and next _word_ on Windows, and that works fine for me. Likewise Ctrl+Backspace to delete previous word.
Does it work OK for you in MuseScore 3?

**Comment by cbjeukendrup** [comment]
This is one of the main annoyances of Qt on macOS: its text editing keyboard shortcuts do not follow the standard of the OS.

@wizofaus AFAIK, there are currently no QML dialogs with multi-line text input (there isn't even a component for that). There are of course some in Format > Style > Header/footer, but that's Qt Widgets.

**Comment by Nick-Mazuk** [comment]
@wizofaus, for me on macOS, all those keyboard shortcuts (aside from Ctrl+Home and Ctrl+End) work as well, except it's with the option key (⌥).

@cbjeukendrup, didn't know there was a difference between the multi-line widget and single-line dialogs. For what it's worth, I'm experiencing the same issues on both.

**Comment by wizofaus** [comment]
Hmm really, I thought ⌥ was the equivalent of "Alt" on non-Mac keyboards. Alt+left/right in Windows doesn't have any standard meaning in text boxes, the only keys for "start of line" and "end of line" are Home and End.  And this is what's implemented for edit text elements on the score. There's no single shortcut for "delete entire line", you can use shift+home, del to delete everything on the current line up to the cursor position, or Home,Shift+End,Del if you're part way through a line but still want to delete the whole thing, and these all work editing text elements on the score too.
If Mac has different conventions here I'm not sure how we'd accommodate them easily.
Does your Mac keyboard not have a Home or End button? I'm wondering then if ⌘+Left should be treated as meaning "home" (and ⌘+Right as "end").

**Comment by Nick-Mazuk** [comment]
For most things, ⌥ is the same as "Alt", but not with text.

My keyboard (MacBook Pro for reference) doesn't have a dedicated home or end button. The "Home" equivalent is `fn ArrowLeft` (function and left arrow). The "End" equivalent is `fn ArrowRight`. I'm not sure how these home and end equivalents normally behave with text, but as I'm typing right now, home scrolls to the top of this page while end scrolls to the bottom.

**Comment by wizofaus** [comment]
Odd...would be interested how you find editing text elements on the score then, because keyboard behaviour there has definitely been modelled after Windows conventions (I'm not sure what the Linux/X-Windows based conventions are, but given Linux users almost always use keyboards with the same layout/available keys as Windows, I'm guessing they're similar).  
However that's quite unrelated to keyboard behaviour inside text controls on dialog, which is all determined by Qt.
Given a substantial portion of MuseScore developers seem to be Mac users I'm a bit surprised there's not good support for such conventions.

**Comment by Nick-Mazuk** [comment]
The keyboard behavior for score items is different. `⌘ ArrowUp` and `⌘ ArrowDown` works correctly. However, the other `⌘` shortcuts behave almost identically to the typical ⌥ shortcuts (Alt on windows). For instance, `⌘ ArrowRight` does move  the cursor right one word. And `⌘ Delete` deletes the previous word. However, `⌘ ArrowLeft` moves the cursor forward one word _and_ an extra space.

For instance, let's assume you have this text with the cursor at the start:

```txt
|this is some text
```

Pressing `⌘ ArrowRight` moves the cursor here, after the space:

```txt
this |is some text
```

Whereas typically with `⌥ ArrowRight`, the cursor moves to the start of the next space. Likewise, `⌘ ArrowLeft` (which is identical to the normal `⌥ ArrowLeft` moves the cursor from here:

```txt
this is some| text
```

To here

```txt
this is |some text
```

It's interesting that none of the other Mac developers even brought up these issues. Perhaps I just use the keyboard more than most of them, because it was immediately noticeable to me.

**Comment by boryskuzmenko** [comment]
The issue is not actual anymore. All Command related shortcuts work.
Additionally, pay attention that `Command + Backspace` shortcut is not mentioned in any apple documentation as a text editing shortcut. Seems like it should be a specific app shortcut. 
**CLOSED**

**Comment by Nick-Mazuk** [comment]
> Additionally, pay attention that `Command + Backspace` shortcut is not mentioned in any apple documentation as a text editing shortcut. Seems like it should be a specific app shortcut.

`⌘ Backspace` is a universal shortcut. It works virtually everywhere. MuseScore is one of the few places it doesn't work (it may on a more recent build, I haven't tested this in a while). So while it may not be in Apple documentation, it works in every single other app (e.g., Chrome, Safari, Word, Pages, Excel, Finale, Notes, VS Code, Google Docs, Notion, Bear, the list could go on). So if it is an app specific shortcut, it's specific to every single other app I've used (most of the ones I mentioned also use different rendering engines under the hood, which means they all needed to implement this shortcut manually).

**Comment by boryskuzmenko** [comment]
Please, pay attention that all mandatory text editing shortcuts which use 'Command' button - works, which says that this issue is fixed. You can create a separate issue as a feature request to add that specific shortcut to the MuseScore. (BTW, I checked Sibelius and this shortcut works there as a simple 'backspace').
Thank you!
