### ISSUE TITLE
[MU4 Issue] Footer text disappears for multi-line text

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#9159]
**Describe the bug**

Multi-line footers cause text to disappear.

**To Reproduce**
1. Create a new document
2. Go to Format > Style > Header/Footer
3. Start typing some text with line breaks
4. Watch as text disappears on score

**Expected behavior**

Footer text should not disappear. It should be displayed exactly as it is in the settings.

**Screenshots**

https://user-images.githubusercontent.com/5659171/133680750-1b1cdb9f-b844-488a-9b7c-a155f9f68e33.mov

**Desktop (please complete the following information):**
 - OS: macOS 11.6.0

**Additional info:**

I have not checked if the same bug happens to other footers and headers.

Also, I'm working on https://github.com/musescore/MuseScore/issues/9043 which involves much of the same code. If someone works on this issue before a PR for https://github.com/musescore/MuseScore/issues/9043 is merged, there will be merge conflicts.

**Comment by DmitryArefiev** [comment]
Checked  #9159 on Win10, Mac11.13.1, Linux Mint 20.2 - FIXED
