### ISSUE TITLE
[MU4 Issue] Time signature properties dialog, misc. issues

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9161]
**Describe the bug**
When modifying time signature properties, the fields for editing the shown numbers are always editable even when unused, the "other" dropdown has nothing in it, and the Beam Properties buttons don't appear to do anything (and show incorrect icons).
Also in many cases (e.g. after switching to another app and back while it's open) on closing the dialog the main window does not come back to the foreground, I believe this problem applies to quite a few dialogs though.

**To Reproduce**
1. Create a new empty score
2. Access context menu for 4/4 time signature and select "properties"
3. Select 'C' under apperance, note that you can still edit the two text fields above this even though they do nothing
4. Select 'Other' - the dropdown doesn't enable or show any options
4. Click on the various "Beam properties" icons in the bottom right, nothing appears to happen
5. In one case, but I can't reproduce, the field text field for the appearance (top number) became uneditable, meaning I couldn't change the appearance at all.

**Expected behavior**
Fields should be editable when and only if they're relevant.  "Other" should provide list of alternative key signature symbols as per v3, beam properties - actually I don't *expect* this behaviour, but in v3 you can drag these onto notes to cause particular types of beam breaks - had to read the manual to figure that out.
(I wouldn't expect 𝄴 and 𝄵 to appear as explicit options for a time signature that wasn't created as 2/2 or 4/4  either, but v3 does this too)

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by Tantacrul** [comment]
- Dialog foreground / background issue was solved a while ago
- Other dropdown now contains the right options
-  The 'Beam properties' icons are now draggable again... but broken. I'm going to raise this separately because they were working for a time!

The rest is classic MS3 jank. Ultimate plan is to completely replace this nightmare of a dialog.
