### ISSUE TITLE
[MU4 Issue] Upload to musescore.com gives impression that app has crashed

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9164]
**Describe the bug**
The File menu option "Upload to musescore.com" doesn't appear to work (new browser tab not activated?)

**To Reproduce**
1. Create new empty score (e.g. using treble clef template). Go to File|Upload to musescore.com, app crashes or is sent to the background and nothing appears to happen.  But actually I realised it was opening a Web browser tab but it wasn't being brought to the foreground...however despite it being an empty score, it seems to be permanently stuck in "uploading" state.
2. Perhaps more seriously, it appears to automatically save the score first as "Untitled.mscz" (even if you already have a file with that name in your default score directory).

**Screenshots**

**Desktop (please complete the following information):**
Windows 10, default browser Chrome 

**Additional context**
Tested with nightly build from https://github.com/musescore/MuseScore/actions/runs/1244135645
Local build actually crashes reliably but is built with the cloud module disabled.

**Comment by wizofaus** [comment]
This actually seems to be an issue with Chrome on my system and happens consistently no matter where I open a web address from, even opening an html file from a File Explorer window. But the issue with the auto-saving is still worth investigating.

**Comment by Tantacrul** [comment]
Uploading to MuseScore.com is not enabled yet. We will be doing so once MP3 export is ready, so we can test the end to end flow.
