### ISSUE TITLE
[MU4 Issue] Program Start Options on Preferences screen do nothing

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9166]
**Describe the bug**
The options on the Preferences | Program Start screen "Show splash screen" and "Show tours" do not appear to do anything.
"Show navigator" works after restarting and creating/opening a score, though it's not clear why you'd use this rather than the View menu | Show Navigator option (which both shows it immediately and ensures it's shown on after restarting and a score is opened).

**To Reproduce**
1. Start MuseScore, navigate to Edit | Preferences | General | Program start, check all 3 checkboxes - show splash screen, show navigator and show tours
2. Quit and restart application
3. No splash screen is shown, no tours shown, and navigator is not shown until a score is opened.

**Expected behavior**
I'm not sure any of these options need to be shown at all, though I would like to see a splash screen given the slightly sluggish start up time (up to 5 seconds on my system).

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Nightly build from https://github.com/musescore/MuseScore/actions/runs/1244135645

**Comment by Tantacrul** [comment]
Some of these issues persist. Some are gone. I'm going to raise the remaining issues in a new bug.
