### ISSUE TITLE
[MU4 Issue] Many commands not available when Master Palette open

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9167]
**Describe the bug**
When the Master Palette is open many of the standard score editing commands are unavailable even if the score has the focus.

**To Reproduce**

1. Open or create new score
2. Type shift+f9 or navigate to View | Master Palette
3. Click on the score window to bring to the fore
4. Note that almost all commands under Edit|Add|Tools|Format menus are disabled

**Expected behavior**
Master palette being opened should affect command availability

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Nightly build from https://github.com/musescore/MuseScore/actions/runs/1244135645
Seems to be the same problem as occurs with the Special Characters window: https://github.com/musescore/MuseScore/issues/8882

**Comment by Tantacrul** [comment]
I'm closing this because the options now work if a user selects the score. And now that the Master Palette always stays in front, it's not really a massive issue. Arguably not an issue at all.
