### ISSUE TITLE
[INSPECTOR] Options for augmentation dots need to be swapped (they're doing the opposite of what they should be doing!)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9169]
**Describe the bug**
The behaviour of the options for augmentation dots have two issues

1. They should only apply to noteheads that are on a line
2. The 'above' / 'below' options do the opposite of what they should do. They need to be reversed.
3. When there are no augmentation dots applied to the notes, the UI should be disabled

**Video**
https://www.dropbox.com/s/ms43zug3g9ytd3j/Dotted_Notes.mov?dl=0

![image](https://user-images.githubusercontent.com/21022311/133771677-6228a5a7-7f2a-4cc7-82c5-eaf14ecefb1f.png)

**Comment by oktophonie** [comment]
I just stumbled across this same issue today myself.

To clafiry: Martin's point 1 above should read "they should only apply to noteheads that _are_ on a line".

**Also**: if the _dot itself_ is selected, this part of the UI is greyed out; it only becomes accessible when the _notehead_ is selected. Maybe a deliberate decision, fine. BUT, if the note is selected first, and _then_ the dot is selected, the UI remains accessible (not greyed out), but none of the buttons will have any effect.

Another video illustrating this: https://www.dropbox.com/s/905f83v0p335fow/9196%20Dotted%20Notes.mp4?dl=0

**Comment by Tantacrul** [comment]
I think it's fine to say that the UI should work when the dot itself is selected too.

**Comment by Tantacrul** [comment]
@RomanPudashkin - Ping!

This should be a really easy fix. The functions are right but they're just mapped to the wrong button.

**Comment by cbjeukendrup** [comment]
> 2. The 'above' / 'below' options do the opposite of what they should do. They need to be reversed.

This part is fixed by #10459

**Comment by Tantacrul** [comment]
This is now fixed. Closing.
