### ISSUE TITLE
[MU4 Issue] View menu Documents stacked & Documents side by side don't appear to work

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9170]
**Describe the bug**
The view menu commands "Documents stacked" and "Documents side by side" don't appear to do anything, even with full score and multiple parts open

**To Reproduce**

1. Create a new score with a few instruments and open a part for one of the instruments
2. Choose View | Documents side by side or Documents stacked
3. No change in view 

**Expected behavior**
Given the way this works in v3 and the fact that separate scores are loaded into different top-level windows now I'd probably expect these menu items not to be present in v4, but if they are to be present they should emulate how they work in v3, whereby the same score can be shown in two separate views (horizontally or vertically) and all edits made to one are immediately reflected in the other such that pan/zoom is independent between them (while switching between Page View and Continuous View/Single Page is not, which limits usefulness)

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Latest nightly build from https://github.com/musescore/MuseScore/actions/runs/1244135645

**Comment by DmitryArefiev** [comment]
@wizofaus  **Documents side by side** and **Documents stacked** features were removed from MU4 by design and removed from View menu as well in #10300
