### ISSUE TITLE
Score tabs are too big. They need to size according to the number of characters.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9171]
**Describe the bug**
Currently, the score tabs (for the main score and parts) are all the same size, which unnecessarily limits how many you can see at one time.

**To Reproduce**
- Open or create a score with multipl (10+) instruments and open all the parts
- Observe

Current tabs:
![image](https://user-images.githubusercontent.com/21022311/133773099-b350ef30-0079-411f-8c60-a6ad480132df.png)

Desired tabs (See Figma for spacing)
![image](https://user-images.githubusercontent.com/21022311/133773157-d7783029-f83d-454f-a303-42f198d950f8.png)

**Comment by yichong96** [comment]
Hi I would like to try solving this as a first issue. Is this still open ?

**Comment by Tantacrul** [comment]
@yichong96 be my guest. I can provide some visual guidance and testing
