### ISSUE TITLE
Score tabs do not have correct colours

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9173]
**Describe the bug**
Currently, it is hard to tell which tab is selected in both dark and light modes.

Check Figma for the most up to date colours

**Current appearance*
![image](https://user-images.githubusercontent.com/21022311/133773725-a3335500-33e3-42a9-9baf-0dfc7f06091d.png)

**Expected appearance**
![image](https://user-images.githubusercontent.com/21022311/133773759-57b64385-1fd5-43b9-9dd4-a281afd03c6e.png)

**Comment by cbjeukendrup** [comment]
I'm working on a small overhaul of how we work with button colors and opacities, so I'll fix this too.
