### ISSUE TITLE
[MU4 Issue] Slow range-based selection updating

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#9174]
**Describe the bug** 
Really slow/lagging range-based selection via keyboard in extended/contracting the selection. Noticed that it's a little better if only whole rests exist (as opposed to how it's shown in included demonstration with some notes in beginning of selection), if that's of any value. 

Attached is a demonstration of MS3 performing forward/backward selection upon two systems. The same input of keyboard behavior is used on MS4 showing the difference

https://user-images.githubusercontent.com/7139517/133773645-303a6861-b726-4c38-ad34-30b3043559e7.mp4

**To Reproduce**
1. Insert some notes then begin the Shift+Right and Shift+Left behavior

**Expected behavior**
Obviously, should be just as fast as MS3

**Desktop (please complete the following information):**
Linux + XFCE

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - it became much better after #10582  

Closing

**Comment by DmitryArefiev** [comment]
@worldwideweary Can you check on the latest master please? It should be fixed now.

And reopen if the issue still occur on you side.

Thank you!

**Comment by worldwideweary** [comment]
Yes, looks decent - just tried a Nightly AppImage and this currently seems to be a non-issue. Thanks.

**Comment by DmitryArefiev** [comment]
Cool. Thanks!
