### ISSUE TITLE
Parts Dialog: cannot open multiple part scores at once

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9175]
**Describe the bug**
The user can multiselect scores... but can only open one at a time, which can be quite painful.

**See video**
https://www.dropbox.com/s/18pvp22xxmjvu0g/Parts_Can%27t_Open_Multiple.mov?dl=0

**Comment by worldwideweary** [comment]
Hey Martin. 
Aside: For what it's worth, just verified that .mp4 files can be drag+dropped into github comments here for an inline view.

**Comment by HemantAntony** [comment]
Hello, I am currently fixing this and it's almost finished

**Comment by DmitryArefiev** [comment]
Tested on latest master build (Win10, Mac12, LinuxMint 20.2) - FIXED
