### ISSUE TITLE
[MU4 Issue] Page width default zoom level not implemented correctly

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#9176]
**Describe the bug**
When default zoom level is set to [Page width] (not sure how to access this as a regular zoom choice: maybe that hasn't been implemented yet), the result gives a super-zoomed out score at the top-left corner of the screen like so:

![MU4-page-width](https://user-images.githubusercontent.com/7139517/133775217-43ed13be-5cf7-4b10-8bbf-32b8009ee776.png)

**To Reproduce**
1. Go to Edit → Preferences → Canvas → Default Zoom = Page width
2. Make new score 

**Expected behavior**
Oh, you know, like, a score filling the entire canvas as with MS3

**Desktop (please complete the following information):**
Linux XFCE

**Comment by Tantacrul** [comment]
This has been fixed at some point over the last year.
