### ISSUE TITLE
[MU4 Issue] Drop down menus disappear while traversing downward 

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#9180]
**Describe the bug**
Title describes it: the menus disappear on some (most) of the drop downs. Also, I experience some lag for specifically the Add menu.

**To Reproduce**
Carry the mouse through the navigation menus

Not sure if this is OS specific or not, but it shouldn't be of course if this is programmed well enough. 
Here's a demonstration:

https://user-images.githubusercontent.com/7139517/133793881-115a21d4-2888-4200-8107-1eb8daa97536.mp4

**Desktop (please complete the following information):**
Linux XFCE

Aside: a separate issue, but it would be nice if you could use the keyboard to navigate up and down within the menus like in 3.x 3.x. Same with preferences etc. Right now that seems to be disabled and also not working within other dialogs.

**Comment by DmitryArefiev** [comment]
Checked in latest master build on Win10, Mac12, LinuxMint 20.2 - the issue DOESN'T OCCUR on my side

Closing

**Comment by DmitryArefiev** [comment]
@worldwideweary You can check in the master build when you have time.  And please reopen if it still exists.
