### ISSUE TITLE
Metronome Sound Needs to be implemented

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9182]
![image](https://user-images.githubusercontent.com/21022311/133816939-7c03043b-01df-478c-bf9c-d43f8ec1824f.png)

**Comment by Jojo-Schmitz** [comment]
Maybe it could just use the GM wood block sound?

**Comment by Tantacrul** [comment]
What MuseScore 3 uses for now would be a good start.

**Comment by Jojo-Schmitz** [comment]
MuseScore 3 uses a plain synthesized sound for the Metronome, not any soundfont's channel.

**Comment by wizofaus** [comment]
https://github.com/musescore/MuseScore/issues/8360

**Comment by wizofaus** [comment]
> Maybe it could just use the GM wood block sound?

It's better that it doesn't use any sound that could be used by actual instrument playback - woodblock's not that uncommon an instrument to score for and being able to distinguish what you've scored from the metronome would be a bit of a pain.  Plus you need at least two sounds, a "tick" for onbeats and a "tock" for offbeats.

**Comment by Jojo-Schmitz** [comment]
Woodblock has those 2 sounds.

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/8360
