### ISSUE TITLE
Repeats are not working

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9185]
https://user-images.githubusercontent.com/21022311/133819472-8929420b-37ec-43fe-b72a-29be6921f0c9.mov

@vpereverzev - assigned to you so you can reassign it if needed. Not sure who is best placed to tackle it. Perhaps someone in the community may wish to take it on.

**Comment by jeetee** [comment]
Turning on "Play Repeats" (which was off by default**?!**) does not set MasterScore::_expandRepeats

**Comment by Tantacrul** [comment]
Yeah, repeats, MIDI input and whatever else is On by default in MS3 should also be in MS4. An oversight.

**Comment by Tantacrul** [comment]
#10385

**Comment by Tantacrul** [comment]
#10385

**Comment by Tantacrul** [comment]
Just created a separate issue mentioning that those three settings should be on by default: https://github.com/musescore/MuseScore/issues/10385

**Comment by jeetee** [comment]
Fixing repeats itself seems to "work" but brings to light other deficiencies, mostly related to not having an unrolled tempomap (which was an MS3 issue as well). This time around notably the effect is that the totalDuration calculation is wrong, resulting in playback stopping too soon if a repeat is involved.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (checked on builds from #10724)

Closing
