### ISSUE TITLE
When opening a template, titles do not appear

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9186]
https://user-images.githubusercontent.com/21022311/133820162-348452d4-f525-4132-b980-90cefc94c354.mov

**Comment by njvdberg** [comment]
This is same behavior as MU3. The title can be specified on the next page, so use `Next` instead of `Done. This similar as creating a new score when choosing instruments. When pressing `Done` after selection instruments, there will be also no title.

Is it the intention the MU4 behavior will be different as MU3?

**Comment by RobFog** [comment]
Wouldn't it make sense to use the template's title at least if a title is not specified?

**Comment by Tantacrul** [comment]
My thinking is that for a new / inexperienced user, deleting an unwanted title is much easier that finding out how to add one. It's also pretty likely someone would want a title.

I actually think all new scores should have an 'untitled' name and possibly also some dummy text where the composer / transcriber info should be.

**Comment by Tantacrul** [comment]
@njvdberg - to answer your question, I didn't realise MS3 did this, so I guess I am advocating for a change in behaviour.

**Comment by njvdberg** [comment]
Change of behavior, no problem, it isn't the only thing that will change in MU4 :smile:

@Tantacrul So, default title will be "Untitled" and default composer "Composer"?
And this for both new scores created by template or selecting instruments?

**Comment by Tantacrul** [comment]
So, this is one I'd like to get a few opinions on. My initial suggestion would be this:

![image](https://user-images.githubusercontent.com/21022311/143851024-05cea30c-a714-474f-80e4-d4b9dabe1569.png)

I considered suggested copyright info too but it's a little tricky to change and would probably cause more frustration that it's worth!

**Comment by shoogle** [comment]
@Tantacrul, looks good to me! Copyright could be _"Copyright © 2022 Name (edit in File > Score Properties)"_.

**Comment by bkunda** [comment]
I think this amount of information makes sense for a template file. Including copyright info could be useful as a way to expose it to the user (who might have missed it in the setup process). It is easily deleted if unwanted.

**Comment by Tantacrul** [comment]
I think it's a bit tricky to remove the copyright info actually. I would have thought you could click on it and press delete but instead you have to discover the score properties dialog.

On balance, I'd opt not to show it unless we can make it as easy to edit as everything else is.
I do hear what you're saying Peter... just feel like it might cause more trouble than it's worth. Translations, etc.

**Comment by bkunda** [comment]
Oh gosh, if it's not a simple click and delete then yes, let's not expose it in a template. 
(I guess we should not be surprised 🙄

**Comment by njvdberg** [comment]
Proposal of @Tantacrul looks fine to me. I suppose the default texts are translated?

For the copyright, it is actually the value of the variable `$:copyright:` which is substituted in the default footer which is controlled by the style. So, there might be no copyright at all.
This makes an initial copyright very tricky. I agree to leave it out (at least for now).

**Comment by njvdberg** [comment]
@Tantacrul Another question, what about when a user doesn't specify a title or composer... on the 'Additional Score Information` page, should be seen as a conscious choice and the fields are kept empty or should they still get the proposed default values?

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED

There is an issue with text and score layout. But this should be solved separately.

![auto title](https://user-images.githubusercontent.com/90187801/145613775-7b6c28f3-e8ef-4a2e-ad0b-c7ad9e4d2ab0.PNG)

**Comment by oktophonie** [comment]
> There is an issue with text and score layout. But this should be solved separately.

See: #9984
