### ISSUE TITLE
Vertical justification should be on by default for all new scores (as with MS3.6)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9187]
https://user-images.githubusercontent.com/21022311/133820976-d5f575b9-f908-464b-9e31-1afe65e36a9f.mov

**Comment by Jojo-Schmitz** [comment]
Probably those changes for 3.6 have not yet been migrated to master

**Comment by Tantacrul** [comment]
Ah. I understand. I just saw the settings existed and thought something had gone wrong.

We are in the middle of porting over that entire converting old scores -> Leland+engraving improvements design right now.

**Comment by DmitryArefiev** [comment]
Tested on master build on Win10, Mac11, LinuxMint 20 - PASS
