### ISSUE TITLE
[MU4 Issue] backspace while in Note Entry doesn't continue to delete previous notation segments

### ISSUE THREAD

**Issue by worldwideweary** [musescore/MuseScore#9188]
**Describe the bug**
As per title, deletion while in [note entry] will not continue to function after using it once

**To Reproduce**
1. Insert notes 
2. Stay in note entry and press delete multiple times
Result is only deleting the most recently entered note rather than the MS3 behavior of continuing to delete. Although now in MS4 the user can use backspace even while not in note entry (unlike MS3) which seems reasonable, a question then becomes, should backspace also "keep working" while not in note entry or should they be distinguished in action? Probably both should continue:

MS4's behavior: (the funny square with 0008) is backspace being pressed

https://user-images.githubusercontent.com/7139517/133862332-1532a094-dcfe-4fd8-9875-4c60631ca9a7.mp4

MS3's behavior:

https://user-images.githubusercontent.com/7139517/133862350-f627b7fe-004c-4b1c-9df3-58cf66dce39b.mp4

**Desktop (please complete the following information):**
 Linux XFCE

**Comment by wizofaus** [comment]
Hmm, that one's possibly my fault, I did some work around addressing differences between how backspace/delete work in note entry vs regular mode, and while there were some intentional differences with v3 behaviour this wasn't one of them!

**Comment by worldwideweary** [comment]
P.S. I think it's cool that backspace works while outside of note-entry now. 

As an off topic but i think slightly relevant and actually important potential improvement, being able to use [next/prev staff or voice] while having a range selection would be a +1 economical action along with the ability to paste while in note entry. I know that sounds weird, but, for an example of real world use:

Let's say I have a measure with a note and a dynamic+hairpin and I want to copy and paste all that to the staff below. 
1. Range select the measure
2. Copy 
3. Want to go to below staff now, but in range selection I can't use [Next staff/voice] to get there via keyboard so now I have to press escape but then I don't have focus on any ChordRest Element so can press N to get going. Alternatively don't press escape but rather go directly into Note Entry from the range selection, then use [next staff/voice].
4. From here I can paste. But wait, I'm in note entry and that won't let me paste, so now I have to exit note entry 
5. And then finally paste. 

It sounds not important, but for me personally it would improve workflow in certain situations
1. Range selection + copy
2. [Next staff]
3. Paste

Of course this is a different topic altogether

**Comment by Tantacrul** [comment]
I think it would be nice if backspace (and delete) did continuously keep 'going back' to previous notes, in the same way it does for text.

However, the MS3 implementation is very buggy. On Mac, it does some weird stuff, so not the best guide.

However, the request is simple: when in note entry mode, backspace should both delete the current note and also move the cursor backwards to the next note on the left.

**Comment by MarcSabatella** [comment]
FWIW, in *theory* what MU3 does on backspace in note input is "undo".  So, if you happen to be entering notes left to right with no fancy editing, it's a normal backspace.  Otherwise, results will indeed often be surprising.  Plus on top of that, it isn't really a normal undo, it's some sort of special note input mode undo, I think.  I long ago customized my backspace to do a normal delete within MuseScore (yes, in addition to keeping the delete key for this also).  But yes, a true backspace - delete and move backwards - would be even better.

**Comment by Tantacrul** [comment]
Thanks Marc! In that case, I'm going to close this issue because the functionality you described is better off not being in MuseScore 4.

Due to this, implementing backspace properly is a valid feature request I think can be safely moved to 4.x.
