### ISSUE TITLE
[MU4 Issue] Parts are no longer linked to master score after loading

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9191]
**Describe the bug**
If you create a score and a part, the notes in the master score are correctly linked to those in the part, such that, e.g. changing their pitch adjusts those in the parts. But after saving and reloading, the notes are no longer linked. 

**To Reproduce**
1. Create a new score and add a note
2. Open a part from the Parts dialog
3. Change the pitch of the note in the part and observe it changes in the master score
4. Save the score, close and reload it
5. Change the pitch of the note in the part, and observe it doesn't change in the master score
6. You can verify the same occurs changing the master and not updating in the part

**Expected behavior**
Notes should remain linked after loading

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 
**Additional context**

**Comment by bkunda** [comment]
Reproducible in MacOS. This is a critical one as it entirely impairs the creation of parts.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
