### ISSUE TITLE
[MU4 Issue] F6/Tab issues

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9192]
**Describe the bug**
F6 no longer brings up shows/hides selection filter, and instead allows tabbing through windows/sections of the UI but not in a reliable/sensible fashion

**To Reproduce**
1. Start MuseScore and click on "new score" in the Scores page
2. Hit the F6 key
3. Note that the File menu has a strange border around it and hitting tab allows changing focus to various controls on the main window that is disabled for mouse access (due to the modal New Score dialog)
4. Note that you can tab to the New Score control and hit enter bringing up a second New Score dialog
5. Now create/open a score
6. In View menu note that "Selection filter" no longer has F6 shortcut as per v3
7. In preferences|shortcuts search for F6 and note is not mapped to any action
8. Nor can you re-map F6 to selection filter (it's not in the list), but if you map it to another action like "Transpose", F6 now both brings up the Transpose dialog AND changes the keyboard focus to the top level menu, meaning tab doesn't tab through controls on the Transpose dialog, but through top-level UI elements on the main window (which should be disabled...)

**Expected behavior**
* F6 should be clearly mapped to an action that sets keyboard focus to the top-level menu and allows tabbing through top-level UI controls/panes, but NOT when a modal dialog is active and the main window should be disabled
* "Selection filter" should have a different shortcut by default and/or allow remapping
* F6 should generally navigate between entire "panels"/sections of the main window, and tab+arrow keys should allow selecting individual controls within each panel in a more consistent fashion (admittedly even in, say, MS Office, it's not always obvious what it's doing, but I believe F6 moves between top-level panels, TAB is equivalent to Down arrow, Shift+TAB to Up Arrow, and right/left arrow allow selecting items horizontally when there are multiple rows, though the arrow keys stop working for navigation once you land on a field such as a dropdown list.  But in MuseScore, even tab or F6 stops working when you land on, say, the Search field)

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**
See https://github.com/musescore/MuseScore/issues/8946 for other similar issues

**Comment by Tantacrul** [comment]
By design. F6 has been re-used for accessibility to allow users to toggle between the major sections of the app:
Home / Top bar / Side Bar / Score / Bottom bar.

Basically it's a 'faster that tab' way to move the focus around.

Since it is an accessibility feature, we don't expect casual users to really get it and it needs to be well documented @shoogle  / @bkunda.

**Comment by shoogle** [comment]
Yes, like @Tantacrul it's intentional to use F6 to navigate between different UI panels. There are a few other apps that do this and they also use the F6 key, so it's something of a standard.

**Comment by wizofaus** [comment]
The problem with F6 allowing access to the top level window while a modal dialog is displayed is fixed.
The issue of there being NO shortcut for "selection filter" and no apparent way to create such a shortcut isn't.
The issue of having F6 performing multiple conflicting actions if you assign it as a shortcut for a particular command still occurs.
I also noted that "transpose" is no longer available as a shortcut you can map a keyboard shortcut too.  
Further the shortcut assignment dialog no longer even warns when you assign the same key to multiple commands (I've now assigned F6 to about 5 different commands plus the built-in "panel navigate" behaviour, and never saw a single warning that it was already in use).
@Tantacrul

**Comment by Tantacrul** [comment]
I've logged an uber 'shortcuts are borked' P0 bug yesterday.

Apart from that, I'd like to salute the selection filter and honour it's service. Let's reassign it to Ctrl+shift+9+f+1

**Comment by wizofaus** [comment]
I'm afraid that reference went over my head, but the selection filter is still a critical piece of functionality (and still works fine), no longer being able to assign a shortcut key to it is definitely a regression on v3.

**Comment by Tantacrul** [comment]
I'd describe it more like a bad solution to a problem the inspector no longer has. Quite far from critical, IMO

**Comment by wizofaus** [comment]
I don't use it for the inspector/properties panel, but for determining what things I want to copy and paste around the score. Esp. with voices.  There may well be better ways of achieving the same goal, but for that at least it's critical.

**Comment by MarcSabatella** [comment]
As far as I know, there are no other solutions to the problems the Selection Filter addresses - and indeed, these problems have nothing to do with the Inspector.  It's all about range operations like copy/paste.  Don't get me wrong, I was never a fan of the Selection Filter design and would love to see it replaced with a better solution.  But right now, it's what we have, and like all other windows, it needs to be toggleable via a shortcut.

I assume the only reason a shortcut cannot be assigned currently is that actions without a default shortcut don't appear in the list at all.  And once that bug is fixed, it should be possible to assign one manually.  But, one should be assigned by default, and it can't be F6.

**Comment by Tantacrul** [comment]
My point is you can Ctrl+A the entire score and make element-specific changes now without having to tick and untick boxes first. On top of that, you also have right-click to select similar. Both of these are better options, so the selection filter is doubly redundant.

**Comment by wizofaus** [comment]
But right-click + select similar doesn't work for cases like wanting to copy *all* elements from voice 2 to somewhere else in the score (without copying voice 1), and that's just one of many similar sorts of operations.
I'd also say "select similar elements in range" doesn't work at all currently in v4 (I put up a PR over a month ago to fix it, but nobody's looked at it as far as I know).

**Comment by wizofaus** [comment]
Ah ok, turns out that was a build issue - once I'd ensured it was built properly from my branch the option reappeared.  You can in fact use "Select|More...|Same Voice" to select just the *notes* in, e.g. voice 2 (if you happened to click on a note that was voice 2) and use the "In selection" checkbox to select just those in the range you had selected previously but it's nowhere near as powerful and simple to use as the selection filter (which, as I said, allows you to select all types of elements in any number of voices). 
I'd also note the issue with the Select... command (or Select similar in range etc.) not being available is only classified P2, despite it being the only way you can achieve quite a few important operations.  My fix seems to be working fine, I don't know if anyone's been able to test it.

**Comment by MarcSabatella** [comment]
The Selection Filter never was intended for, and seldom would have worked for, limiting a selection to just a single element type for using in the Inspector.  As mentioned, Select All Similar has always been the way to do that.  And indeed, it's great that this isn't needed anymore for using the Properties window (although it still is for performing keyboard-based actions).  But again, not relevant to the purpose of the Selection Filter.

The actual intended purpose for the Selection Filter is not about *selecting* elements of a given type, but about *excluding* certain elements from a range selection, *while keeping it a range selection*.  That's something Select All Similar cannot do - it will only create list selections; never range selections.  The Selection Filter has always been about cases where you *need* range selections (like for copy and paste) but there is a specific voice or element type *don't* want affected as part of the operation.  Also, cases where you want *some* element types to be included along with your notes but not *all*.  Again, Select All Similar just has no way of doing this.

The example @wizofaus gives of copying voice 2 only is a good one, but there are plenty of others too.  Like one I used just the other day: I had a lead sheet and wanted to delete all the notes from it but leave the chord symbols behind.  Ctrl+A to select all, but uncheck Chord Symbols to exclude them from the selection then press Delete.

I am *not* claiming this is the best possible design for how this could be done, but *that* is the sort of the problem the Selection Filter was designed to solve - not as a replacement for Select All Similar or as a way of making the Inspector more useful.
