### ISSUE TITLE
[MU4 Issue] General preferences options do nothing

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9195]
**Describe the bug**
The General page of the Preferences dialog does nothing and no controls work - the auto-save and port number checkboxes are unclickable, and "Update translations" just closes the dialog. The list of languages appears to show correctly but selecting from it does nothing.

**To Reproduce**
1. As per description above

**Expected behavior**
Options should work as per v3.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**
BTW this is especially problematic currently because it seems auto-save is *always* on and can't be turned off - and due to another issue I've reported, this frequently means you lose your work if you're not careful.
While auto-save in principle is a very good idea, I'd argue it's quite important that if auto-save should never overwrite the file you're actively working with, and rather only be used to recover from crashes etc.  If I open a file to try something out with, and deliberately close without saving, I expect to be able to get back to the original file. The undo/redo stack can't always be counted on for that, and doesn't work between loads/saves.

**Comment by Tantacrul** [comment]
These preferences are now working.

Closing this issue.
