### ISSUE TITLE
[MU4 Issue] Undo after opening new part causes odd behaviour

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9196]
**Describe the bug**
After opening a part from a score, undo causes unexpected behaviour, and unlinks part from score, prevent editing etc.

**To Reproduce**
1. Create a new score using any template (treble clef is fine)
2. Add a note to the first measure
3. From the Parts dialog open any part
4. Choose Edit|Undo (or Ctrl+Z) - note that Title moves to very top-left of page
5. Ctrl+Z again, no visible change, but click "untitled" (master score) tab and note that note is now gone. Add a different one.
6. Switch back to Part (Piano) tab, observe that the original note is still present and the multi-measure rest has disappeared leaving a completely empty measure. 
7. Try to add notes into the part score - nothing works.
8. Open the Parts dialog again, you can see the Part present twice now

**Expected behavior**
a) Undo after opening part score can probably safely do nothing, as the new part score should have its own empty undo stack.
b) Parts should never become unlinked from master score after undo
c) Parts should never show twice in dialog (unless you explicitly created them twice!)

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by RomanPudashkin** [comment]
Should be fine in the current master. Please, reopen the issue again if you can still reproduce it  
https://github.com/musescore/MuseScore/pull/10625
