### ISSUE TITLE
[MU4 Task] Footer UX improvements—symbols and urls

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#9208]
There are some nice footer text UX improvements we can make (as suggested by Daniel to me via email):

- Make it easy to insert the ©, ®, ™ symbols
- Style links correctly

We still need to figure out the specifics on how these would work. For instance, we could follow what Microsoft Word does and replace `(c)` with "©". Or we can have a button to insert the copyright symbol. Or both. Or something else entirely.

This is also a low priority issue.

**Comment by Jojo-Schmitz** [comment]
the "(c)" for &copy; trick is what used to work in MuseScore 1, but got removed and deliberatly.

**Comment by Jojo-Schmitz** [comment]
Reason back then: we don't want stuff like this happen automagically.

I would not mind getting it back though.

But mind: the © is usually not in header or footer, but in File > Score properties > copyright and gets into header/foter fir the $C, $c or $:copyright: macro. And that in tuen needs more improvements, like the option to enter multiline copyrights.

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.org/en/node/19780 and https://musescore.org/en/node/279679

**Comment by Jojo-Schmitz** [comment]
and also https://musescore.org/en/node/323913 (for hyperlinks)

**Comment by mirabilos** [comment]
Do *NOT* automatically replace anything. Or, if you must, **DO** make it an opt-in feature.

I would be *very* angry if my text was automatically changed. (And from what I remember, even in Winword it’s an optional feature.)

**Comment by Jojo-Schmitz** [comment]
I wouldn't know how to disable it in Microsoft products like Outlook, Word, Excel. So it if is option it is on by default and the switch well hidden

**Comment by Fourniture** [comment]
I would suggest a ghost copyright symbol that turns to a real one as soon as you start typing. In default of that, there could simply be a tiny button for it under the copyright field. 
My opinion is that this issue is actually somewhat important; it's a hassle to deal with it every time I create a score.

**Comment by Jojo-Schmitz** [comment]
Or simply return to the way MuseScore 1 did it: when seeing "(C)" or "(c)" in the copyright dialog, change to &copy;
