### ISSUE TITLE
[MU4 Issue] Rearranging the instruments, leads to incorrect brackets

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#9210]
**Describe the bug**
Rearranging the instruments, leads to incorrect brackets

**To Reproduce**
1. Create a new Score "SATB Closed Score + Piano"
2. Drag the "women" under the "men" voice

**Expected behavior**
Set the brackets correct or remove them if they are not needed.

**Screenshots**
Bevor rearranging
![Vorher](https://user-images.githubusercontent.com/63284090/134126761-f36888f6-f3d1-468d-b5c5-0b70fa392a14.png)

After rearranging
![nachher](https://user-images.githubusercontent.com/63284090/134126789-a6abe4b6-0f5a-4490-82d6-b86da816cc9f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by njvdberg** [comment]
Worked fine in MU3, I'll have a look.

**Comment by njvdberg** [comment]
When creating a new score  "SATB Closed Score + Piano", the score order is `Choir` which is correct.
However, when changing the order of the staves, the score order becomes `Custom` instead of `Choir (customized)`. Since the `Custom` score order does nothing with bracketing and barlines the bracketing stays where it is (starting at "women" and spanning 2 staves) which is wrong.

**Comment by mattblo** [comment]
Does this mean that this behavior is intentional and nothing needs to be changed? I would at least expect that the parenthesis is removed or added again when I restore the order as at the beginning.

**Comment by mattblo** [comment]
If you set the order to Orchestral, the brackets for women and men are removed. If you set it back to Choir, they will not be added again...

https://user-images.githubusercontent.com/63284090/144417339-9aaae686-4098-4361-9191-c19420ff98c0.mp4

**Comment by njvdberg** [comment]
>Does this mean that this behavior is intentional and nothing needs to be changed? I would at least expect that the parenthesis is  removed or added again when I restore the order as at the beginning.

No, this is not intentional and will be solved (I'm working on it already).

> If you set the order to Orchestral, the brackets for women and men are removed. If you set it back to Choir, they will not be added again...

Indeed, when you delete the brackets, selecting the same score order again doesn't recreate the brackets again. Switching it to another score order, e.g. `Orchestral`, and than back to `Choir` **will** recreate the brackets. Nevertheless something I have to look at.

**Comment by mattblo** [comment]
You may also want to take a look at #10040, #10034, #10038

**Comment by njvdberg** [comment]
> You may also want to take a look at #10040, #10034, #10038

With  a little luck I don't have to. Solving this one most likely solve these too :wink:

**Comment by njvdberg** [comment]
Solved by #10345

**Comment by mattblo** [comment]
> Solved by #10345

Tested! Problem fixed!

**Comment by DmitryArefiev** [comment]
> Does this mean that this behavior is intentional and nothing needs to be changed? I would at least expect that the parenthesis is removed or added again when I restore the order as at the beginning.

> No, this is not intentional and will be solved (I'm working on it already).

Hi @njvdberg this will be solved not in #10345, right?

**Comment by DmitryArefiev** [comment]
Also, found a bug in men/women voices behavior: in Choral order they placed under the piano  
(can be seen in SATB Closed Score + Piano template when switching to Orchestral and return back to Choral)


https://user-images.githubusercontent.com/90187801/151798384-a122beb1-3e3b-4ac1-84dc-3ecfd7bde4c3.mp4

Will log it separately

**Comment by njvdberg** [comment]
@DmitryArefiev Issue #10415 is **not** related to this issue but to a change in `instruments.xml`. See the comment in #10415.
