### ISSUE TITLE
[MU4 Task] [Accessibility] MU requires additional Return/Enter to naviagate screen reader focus to next field/element

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9216]
**To Reproduce**

Case №1 Home tab (described in #8134, #9192)
1. Using NVDA or Orca, Open MU 
2. Start tabbing - it stucks in Search field
3. You need hit Return and then Tab again to go to the next element

![01](https://user-images.githubusercontent.com/90187801/134216095-18e73e9e-5996-4677-9304-b95c577090f1.png)

Case №2 New Score Wizard
1. In New score wizard Tab to Search field
2. To start navigate on instruments below you need hit Return or Tab and hit down arrow to hear a first instrument name 
![02](https://user-images.githubusercontent.com/90187801/137019419-19125506-e98e-420b-a7ab-782151255474.PNG)

Case №3 (New Score Wizard>Additional Score Information)
1. In Additional Score Information, Tab to Title field
2. Then Tab to Composer field - blinking cursor does move **but not screen reader focus**
3. To move screen reader focus you need hit Return **each time** and then navigate with arrow 
![03](https://user-images.githubusercontent.com/90187801/137022309-843b7b75-68b2-4bf6-a7f3-88bada2b4815.PNG)

Case №4 (Instruments panel>Instrument>Settings)
1. Navigate to Settings
2. Then Tab to other fields - blinking cursor does move **but not screen reader focus**
3. To move screen reader focus you need hit Return **each time** and then navigate with arrow 
https://user-images.githubusercontent.com/90187801/137022659-aacbee37-a931-418e-a9c7-23a7bb31fb14.mp4

**Desktop (please complete the following information):**
 - OS:

**Comment by wizofaus** [comment]
Yeah I noticed that too, I mentioned in here https://github.com/musescore/MuseScore/issues/9192

**Comment by DmitryArefiev** [comment]
Cool! Thanks!

**Comment by DmitryArefiev** [comment]
Tested with Narrator/NVDA (Win10), Orca (Linux Mint 20.2) and VoiceOver (Mac11) - PASS
