### ISSUE TITLE
[MU4 Issue] Struggle to dock Mixer back in!

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9221]
**Describe the bug**
I accidentally undocked the mixer window now I can't get it back to how it was. The only option it seems to be is to dock anywhere else apart from the bottom of the app.

https://user-images.githubusercontent.com/71656189/134335746-89b2ff3f-f94f-45d4-a871-cd75681a5904.mov

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac11, LinuxMint 20.2 - PASS
