### ISSUE TITLE
[MU4 Issue] Mixer - Volume number meters glitch when change font in Preferences

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9223]
**Describe the bug**
There seems to be a strange bug where you change the font in Preferences, the numbers on the volume meter looks glitchy like the replaced font is overriding original. It's not changing as it should be. The right side of the volume meter labels behave fine, the left side not.

https://user-images.githubusercontent.com/71656189/134336945-c2044e71-4954-499a-a750-1696c7da8eeb.mov

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by cbjeukendrup** [comment]
I will submit a fix soon!
