### ISSUE TITLE
[MU4 Issue] Crash when displaying/activating the instruments in a new part

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#9224]
**Describe the bug**
Musescore crashes when trying to create a new part and insert/activate an instrument.

**To Reproduce**
1. Create a new Score
2. Create a new Part
3. Open the new Part
4. Enable/make visible one Instrument
5. Musescore crashes

**Expected behavior**
Make the Instrument in the Part visible and do not crash

**Desktop (please complete the following information):**
 - OS: Windows 10 NightlyBuild 22. Sept. 2021

**Comment by DmitryArefiev** [comment]
Checked #9229, #9224 on Win10, Mac11.13.1, Linux Mint 20.2 - FIXED
