### ISSUE TITLE
Pitch of default playback in MS4 is a half-step (semitone) too high. Pitch of VST plugins is accurate.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9225]
**Describe the bug**

1. With the default (MuseScore_General), if you place an 'F' on the score and press play, you will hear an F#.
2. If you then change the playback to a VST plugin, you will hear an F.

For this reason, playback sounds hilariously terrible when you mix default playback with VST :)

Windows 10 only (not confirmed for Mac yet)

**Comment by Jojo-Schmitz** [comment]
Possible fix:

in src/framework/audio/audiomodule.cpp change requiredSpec.sampleRate from 48000 to 44100.

(stolen from https://musescore.org/en/node/327220#comment-1107355)

**Comment by ootjersb** [comment]
I have a crackling sound when using the default playback.  Is that also related to this issue? It is heard a little with Piano, but a lot more with Cornet or Trombone sounds. Using MuseScoreNightly-202201140422-master-9e83219-x86_64

**Comment by DmitryArefiev** [comment]
Retested in master build (Win10, Win11 Mac12, LinuxMint 20.2) - PASS

Closing
