### ISSUE TITLE
[MU4 Issue] Playback cursor is faster than real playback

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#9227]
**Describe the bug**
The playback cursor is faster than the real playback

**To Reproduce**
1.You can try this score (https://musescore.com/user/1050536/scores/6746105)
2. Play it
3. At the latest in bar 12, the difference should be visible and audible

**Expected behavior**
The cursor should show the current position of the playback.

**Screenshots**

https://user-images.githubusercontent.com/63284090/134345668-bef53317-ff9f-4a6b-8ffe-19f054b4fa5a.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 NightlyBuilds 22. Sept. 2021

**Comment by Tantacrul** [comment]
Does it the playhead continue to go faster as time goes on? So after 4 minutes, it would be a few beats ahead, etc?

**Comment by mattblo** [comment]
Yes, the more time passes, the more the two diverge from each other. After about 30 bars, the cursor is a whole bar ahead

**Comment by mattblo** [comment]
Found the following problem. I think it could be the same as already described above: Here the tempo indication is apparently wrongly converted...

https://user-images.githubusercontent.com/63284090/135805725-c95f58fd-9203-4399-a1c1-bfced73f8634.mp4

Also reproduced in another piece:
https://user-images.githubusercontent.com/63284090/135805864-0228aa94-49cb-47c3-958e-c695757fb50c.mp4

**Comment by mattblo** [comment]
Strange: Apparently tempo information is not taken into account at all in MU4, as far as the palyback is concerned.
Can anyone else confirm this?

**Comment by Tantacrul** [comment]
All of this playback stuff is dependant on our new playback events system that @vpereverzev is building right now. It is good to keep these bugs active but they are not individually solvable until the main events work is complete.

It is the one major part of MS4 that is incomplete and therefore all midi / tempo / pitch bugs will need to wait.

**Comment by jeetee** [comment]
I can confirm that the cursor seems to follow the intended playback tempo (tested with a score at 400 qpm) while playback itself doesn't follow it at all.

**Comment by jeetee** [comment]
Any link to which PR/commit closed this @vpereverzev ?
