### ISSUE TITLE
VST: When launching popup, they appear in the wrong position and the window is too small (Windows)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9228]
**Describe the bug**

1. When launching a new VST, the popup window appears in the centre of the screen, rather than the centre of the app. This can feel very strange on larger screens. Centre of the app window is always preferable
2. When launched, the VST window is always very small and does not resize to match the VST UI. This is standard behaviour on other applications.

https://user-images.githubusercontent.com/21022311/134345790-e155a86e-4808-4534-8e46-06244c768645.mp4

![Kontakt](https://user-images.githubusercontent.com/90187801/139906355-62f5ceed-45db-4304-9434-41681e16e24a.PNG)

OS: **Windows10**
Can't reproduce on Mac11

**Comment by Tantacrul** [comment]
I've made this a P1 because it obstructs working with VSTs quite significantly.

**Comment by DmitryArefiev** [comment]
Still occurs in master build (Win10)
![latest master](https://user-images.githubusercontent.com/90187801/144886679-f025c821-4bad-4852-a10e-b4ce32284780.png)

**Comment by DmitryArefiev** [comment]
Hello @jessjwilliamson , can check this in build from #10581 on your side (Windows) please? 

Thank you!
