### ISSUE TITLE
VST settings are not remembered when the project is saved and reopened (also the UI malfunctions slightly)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9230]
**Describe the bug**
This bug shows three different (but related) problems. They are hard to catch on video so I've logged them together.

1. Save a score that is using a VST but don't close MuseScore. Then open the project again and the app will crash.
2. VST settings are not remembered. See video. This is the primary problem.
3. When reopening a file where a VST is being used, the UI prevents the user from accessing the VST (although there is a work around - see video)

OS: Windows 10

Apologies for the dropbox link. The file is over 100mb.
https://www.dropbox.com/s/332hqllnowewq0p/03_VST_Not_Loading_After_Save%2BCrash.mp4?dl=0

(please excuse my cluttered desktop)

**Comment by mattblo** [comment]
similar problem mentioned here #9267
