### ISSUE TITLE
[MU4 Issue] [Accessibility] Narrator adds "MuseScore four development window" before main text very often 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9235]
**To Reproduce**
1. Tab through  New Score > Choose Instruments > Additional Score Information
2. Tab through top ribbon sub menus (File>down list, Edit>down list etc.)

**Desktop:**
 - Narrator, Win10

**Comment by Tantacrul** [comment]
Can't reproduce. @DmitryArefiev - let me know if I need to reopen this!
