### ISSUE TITLE
[MU4 Issue] Mixer window should display up to 'Sounds' row by default.

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9241]
**Describe the bug**
At the moment when opening the mixer for the first time, its view is too short and it only visibly shows the track name up to the Volume text field. It should show by default the full mixer view as high as Sounds row.

**Screenshots**

https://user-images.githubusercontent.com/71656189/134496785-72630654-6673-4889-a770-721ffeb0f7cd.mov

 - OS: MacOS

**Comment by jessjwilliamson** [comment]
Want to bring this issue as related to this https://github.com/musescore/MuseScore/issues/9642

**Comment by cbjeukendrup** [comment]
@RomanPudashkin I tried working on this issue and #9642, but have a question: I can't find a way to change the height of a DockPanel programmatically (I'm not sure which KDDW API I should use). Could you help with that, when you have time?

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10614
