### ISSUE TITLE
[INSPECTOR] 'Text' options should be moved below 'Notation' options by default

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9243]
**Describe the bug**
This is a design change. Currently text options appear above notation options, which is unexpectedly visually noisy and slightly confusing.

See video:

https://user-images.githubusercontent.com/21022311/134510547-15c54b80-65fd-4a69-8216-dc7721f66019.mov

**Comment by RomanPudashkin** [comment]
We already have the issue for this bug:
https://github.com/musescore/MuseScore/issues/9085

I'll close this one
