### ISSUE TITLE
[INSPECTOR] Bold, Italic and Underline options can not be toggled together.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9244]
**Describe the bug**
Something has changed recently, where Bold Italic and Underline options are suddenly exclusive. Very odd regression. See video:

https://user-images.githubusercontent.com/21022311/134510746-7cd7f582-221b-4027-a65e-ea03069bdd21.mov

**Comment by DmitryArefiev** [comment]
Checked #9244 on Win10, Mac11.13.1, Linux Mint 20.2 - FIXED

**Comment by Tantacrul** [comment]
thanks!
