### ISSUE TITLE
[MU4 Issue] No sound during Note Input

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9251]
**Describe the bug**
Cant hear added note sound

**To Reproduce**
1. Create a score
2. Add note on the score

**Expected behavior**
Added note should play while it`s added 
User should hear the added note

**Desktop (please complete the following information):**
Windows 10

**Comment by DmitryArefiev** [comment]
Tested latest master build on Win10, Mac12, LinuxMint 20.2 - FIXED

Closing
