### ISSUE TITLE
[MU4 Issue] Cant open score from default folder if Windows OS version is Russian

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9252]
**Describe the bug**
Cant open score from default folder if Windows OS version is Russian

**To Reproduce**
1. Use WindowsOS with Russian language
2. Create a score
3. Save score to the default folder
4. Try to open score from default folder

**Expected behavior**
Score opened 

**Screenshots**
![Cant open saved score (1)](https://user-images.githubusercontent.com/71372310/134541159-622e5635-ab94-46ef-ae28-ed9872b445f5.jpg)
Blank MU4 after trying to open Score from default folder
![Cant open saved score (2)](https://user-images.githubusercontent.com/71372310/134541164-03476801-4ac4-4e33-b747-9c1ed6432e33.jpg)

**Desktop (please complete the following information):**
Windows 10

**Comment by Tantacrul** [comment]
@DmitryArefiev @boryskuzmenko - would you be able to confirm if this is still happening?

If not, then let's close this one. Thanks!

**Comment by boryskuzmenko** [comment]
🟡**Can not reproduce**🟡
Tested on Windows 11
