### ISSUE TITLE
[MU4 Issue Crash after closing app in MacOS

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9258]
MuseScore 4 triggers a crash message in MacOS some seconds after closing down the app.

Crash only occurs from **score tab**. Crash not reproducible from **home** or **publish** tabs.

Demo video (wait 9 seconds after app closure to see crash report).

![crashes-on-close](https://user-images.githubusercontent.com/86290556/134617786-68ef249f-bb9f-42fb-8acf-8e6e879016eb.gif)

**Expected behavior**
App should not crash on closedown

Macbook Air M1, MacOS 11.6
Not reproducible in Windows 10

**Additional context**
https://github.com/musescore/MuseScore/issues/8650

**Comment by DmitryArefiev** [comment]
Tested on Mac11.6 - CRASH NO LONGER OCCURS

**Comment by DmitryArefiev** [comment]
@bkunda You can try on your side as well. It should be in the next master.
Thanks!
