### ISSUE TITLE
[MU4 Issue] Context menu opens at the bottom always in the right corner (and sometimes appears at the top)

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#9261]
**Describe the bug**
When performing a right-click on a note that is at the bottom of ScoreView, the context menu is opened in the right corner instead of at the selection. 

**To Reproduce**
1. Select a Element at the bottom of a score
2. Right Click on it

**Expected behavior**
Context menu should open at the Selection

**Screenshots**
![Contextmenü always in rigth corner](https://user-images.githubusercontent.com/63284090/134647354-8b94c4e6-0fb8-4f18-b3b9-748b280c1d85.png)

**Desktop (please complete the following information):**
 - OS: Windows 11/Mac 11.6.0/LinuxMint 20.2

**Comment by cbjeukendrup** [comment]
Also on macOS (11.6.0)

**Comment by DmitryArefiev** [comment]
Also sometimes appears at the top
https://user-images.githubusercontent.com/90187801/141994986-c4b5c65b-4ad5-4112-ac90-662d523e49fd.mp4

Will add it to summary

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
