### ISSUE TITLE
[MU4 Issue] The panel tabs go beyond the panel if more than 3 tabs 

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#9262]
**Describe the bug**
If, for example, the Selection filter is displayed in addition to "Properties (Inspector)", "Paletts" and "Instruments", this strange look occurs.

**To Reproduce**
1. Open the Selection Filter

**Expected behavior**
@Tantacrul Show an arrow to navigate through the tabs?

**Screenshots**
![Strange Design with more than 3 Tabs in left Panel](https://user-images.githubusercontent.com/63284090/134650850-46ff70de-cad8-45cf-babb-8d6d537fd4c0.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by cbjeukendrup** [comment]
This is what it is supposed to be like:
<img width="407" alt="Schermafbeelding 2021-09-24 om 11 25 15" src="https://user-images.githubusercontent.com/48658420/134651786-488ba2d2-9a2d-4a33-802b-c22e1f140876.png">
So no-active tabs shrink their width proportionally.

**Comment by bkunda** [comment]
Well spotted @mattblo and @cbjeukendrup! 
In looking at this I've also noticed that the panel doesn't resize in Windows and MacOS (despite there being a resize handle).  
@Tantacrul is this panel supposed to resize horizontally? If not, then we may need to remove that resize handle.

**Comment by Tantacrul** [comment]
These panels are meant to be resizable (although there is a limit to how much they can be resized). Resizing horizontally was working before. 

Thnks @mattblo : I forgot to log this.

**Comment by Tantacrul** [comment]
@RomanPudashkin, @Eism, @vpereverzev - to get this right may take a bit of collaboration with me (to determine the easiest solution). @jessjwilliamson made the initial designs, so she's a good person to ask too.

@jessjwilliamson: in a nutshell, we have a few options with how tabs can work when they resize. Let's get some feedback and potentially make the design simpler if we need to. I feel we have other potential options... but what you've designed may very well be fine. Regarding horizontal resizing of panel, we just need to make sure users can't narrow them to the point where they look really weird.

**Comment by jessjwilliamson** [comment]
> @RomanPudashkin, @Eism, @vpereverzev - to get this right may take a bit of collaboration with me (to determine the easiest solution). @jessjwilliamson made the initial designs, so she's a good person to ask too.
> 
> @jessjwilliamson: in a nutshell, we have a few options with how tabs can work when they resize. Let's get some feedback from the devs first and we can potentially make the design simpler if we need to. I feel we have other options but what you've designed may very well be fine. Regarding horizontal resizing of panels, we just need to make sure users can't narrow them to the point where they look really weird. :)

Agree with everything you say :) This could potentially be "Panel Tabs V3" haha :D

**Comment by mattblo** [comment]
This problem has been partially solved. The text now does not overlap the ScoreTabs, but it is also not completely readable as shown in the picture
![4Tabs](https://user-images.githubusercontent.com/63284090/152531898-5c8dfce6-c05a-4f84-801b-aadff12b1103.png)
.

**Comment by DmitryArefiev** [comment]
Tested #9262 on Win10, Mac12, LinuxMint 20.2 - PASS      

Works this way:


https://user-images.githubusercontent.com/90187801/155991220-07a51ed0-de73-4fd7-b211-ead57d0c81f5.mp4
