### ISSUE TITLE
[MU4 Issue] Main window is 1Px too small when maximized

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#9263]
**Describe the bug**
When the Musescore 4 window is maximized, the background is still visible below it at a height of 1px. The screen is not filled completely.

**To Reproduce**
1. Maximize Musescore 4

**Expected behavior**
The Window should fill the screen completely

**Screenshots**
Windows 10:
![Musescore 4 Win 10](https://user-images.githubusercontent.com/63284090/134655426-7074c166-38e8-4919-8685-ae5e627bf15f.png)
Windows 11:
![Musescore 4](https://user-images.githubusercontent.com/63284090/134655428-071ca2dc-7dbb-419f-938f-3e72eea97dfe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 and Windows 11

**Comment by mattblo** [comment]
@Eism I think you have already made some improvements to the size of the windows. Would that still be possible?

**Comment by Eism** [comment]
@mattblo it was a hack for fixing #8869
see [note](https://github.com/musescore/MuseScore/blob/master/src/appshell/internal/platform/win/winframelesswindowcontroller.cpp#L129)

And I cannot reproduce on Windows 10. 
It is necessary to understand what affects the size of the window. @DmitryArefiev Can you reproduce it?

**Comment by mattblo** [comment]
> @mattblo it was a hack for fixing #8869 see [note](https://github.com/musescore/MuseScore/blob/master/src/appshell/internal/platform/win/winframelesswindowcontroller.cpp#L129)
> 
> And I cannot reproduce on Windows 10. It is necessary to understand what affects the size of the window. @DmitryArefiev Can you reproduce it?

Well if I set the Windows scaling to 150% or higher, I don't have a 1Px line anymore either, but at 100% or 125% I have a... Maybe this helps?

**Comment by DmitryArefiev** [comment]
@Eism @mattblo I **can reproduce** it on my Windows 10, FullHD, 100%

https://user-images.githubusercontent.com/90187801/144019427-caba4218-fe4f-436c-b852-8542eb8243f7.mp4

**Comment by bkunda** [comment]
I have been looking into some scaling issues in Windows and have also found a problem with full screen. I shall post my video about it here rather than create a new issue as I suspect it is related. 
FWIW, the issue I have found concerns an extended-display (laptop + external monitor) setup, and seems to happen after adjusting scaling. In my example, the window is offset negatively on both the x- and y-axis (so there is a gap on both the right and bottom edges of the screen):

**Comment by Eism** [comment]
@mattblo @bkunda @DmitryArefiev 
can you check PR #9956?

**Comment by mattblo** [comment]
As far as I can tell, the problem is now solved for me!

**Comment by mattblo** [comment]
> @mattblo @bkunda @DmitryArefiev can you check PR #9956?

As far as I can tell, the problem is now solved for me!

**Comment by DmitryArefiev** [comment]
@mattblo Thanks!

@Eism Tested on laptop with FullHD display  (Win10). On my side all good now on **100%** and **125%**, but it **still not perfect on 150%**. Please see the video

https://user-images.githubusercontent.com/90187801/147642111-58fbdba5-6206-491b-acdf-2131fbf1dc87.mp4

I can log it separately if you want

**Comment by bkunda** [comment]
> @mattblo @bkunda @DmitryArefiev can you check PR #9956?

This is solved for me also. I was unable to reproduce the issue @DmitryArefiev found above.
