### ISSUE TITLE
[Crash] Close new score without saving

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9264]
**Describe the bug**
If you create a new score, mark it dirty and then attempt to close it without saving, you get a persistent crash on Mac. See video:

https://user-images.githubusercontent.com/21022311/134659335-bdb0c5cf-3fc0-4c8a-ae4e-275e02f1cc71.mov

**Comment by DmitryArefiev** [comment]
To reproduce this MuseScore should use **Dark Theme**

**Comment by DmitryArefiev** [comment]
Checked #9264 on Win10, Mac11.13.1, Linux Mint 20.2 - FIXED
