### ISSUE TITLE
[MU4 Issue] Shadow note dot placement doesn't match with real dot position after input

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9265]
**To Reproduce**
1. Enter Note entry mode
2. Select eight note with dot
3. Enter note with mouse - compare dot position between shadow note and real note

![Dotted shadow note](https://user-images.githubusercontent.com/90187801/134659526-92bf4e8f-dc66-47f4-a8dc-5291a7542b04.gif)

**Desktop (please complete the following information):**
 - OS: Win/Linux/Mac

**Additional context**
Related to #9095

**Comment by cbjeukendrup** [comment]
There is a lot more wrong with the shadow note, especially regarding articulations. Also, the stem direction and length is not always 100% accurate, but I wonder whether that is really a problem.
