### ISSUE TITLE
[MU4 Issue] Mixer Kontakt VST opens in very small window

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9267]
**Describe the bug**
On Windows build (not sure on Mac yet) Kontakt opens in very small window

**Screenshots**

![Kontakt small window](https://user-images.githubusercontent.com/71656189/134666718-18e20dcc-0a7c-4786-a54d-492f3c23d454.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by mattblo** [comment]
Similar problem also mentioned here #9228

**Comment by RobFog** [comment]
Typo in issue title: "Kontak"

**Comment by DmitryArefiev** [comment]
Since it's the same as #9228 let's close the current bug and one per issue (will add Kontakt screenshot to #9228)

Closing as dupe
