### ISSUE TITLE
[MU4 Issue] Context menus - Categorised menus are laggy

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9268]
**Describe the bug**
Norma menus seem to work fine, but when in categories as demonstrated in video, it becomes laggy. It could be that
- Loading information within a category
- The fade animations makes it laggy

Ideally, it would be best to not have these animations as context menus are treated as quick-responsive functionalities. 

Sound on for me speaking

https://user-images.githubusercontent.com/71656189/134669259-746808ad-9377-4529-b799-cc2e91edf021.mov

**Desktop (please complete the following information):**
 - OS: Mac and Windows

**Comment by cbjeukendrup** [comment]
Probably related to #9055.

**Comment by jessjwilliamson** [comment]
> Probably related to #9055.

Correct! Bradley beat me to it!
