### ISSUE TITLE
[MU4 Issue] Multiple VST windows open

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9269]
**Describe the bug**
VST should only have one window per plugin. 
In this case, I have Kontakt, but 3 windows open because I am able to click on the Kontakt Sound button multiple times resulting in multiple windows. This must be only one window per plugin. 

![VST Multiple windows](https://user-images.githubusercontent.com/71656189/134670172-5f8307b2-78a7-467a-b457-be89832f057b.png)

Same for another plugin, to prove it's not just Kontakt.

![VST Multiple windows Super 8](https://user-images.githubusercontent.com/71656189/134670203-490445d7-1739-4332-9e0a-742d499fc6d8.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by RobFog** [comment]
There's a typo in the issue title: "Mulitple".
