### ISSUE TITLE
[MU4 Issue] Scroll bar should be visible when user hover mouse cursor in a tab with a scroll bar

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9271]
**Describe the bug**
when the user hovers over scroll bar, they should see the scroll immediately. It should not disappear until the user has moved away from the panel.

**To Reproduce**
1. Create a score 
2. Add a note on the score
3. Select notehead (note element)
4. Open Preferenses tab
5. Try to scroll "Notehead group" tab

**Expected behavior**

**Screenshots**
For example this section has scroll bar but it is visible only while scrolling
![unknown](https://user-images.githubusercontent.com/71372310/134680555-b18dffe8-2cca-48c4-a885-a1ee0847e4fc.png)

**Desktop (please complete the following information):**
Windows 10
Linux
MacOS

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/11431
