### ISSUE TITLE
[MU4 Issue] If there are several scroll areas they will scroll one after another

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9272]
**Describe the bug**
If there are several scroll areas they will scroll one after another. 
But we want to scroll only those are where mouse cursor is. 

**To Reproduce**
1. Minimize MU4 window
2. Create a score
3. Add a note on the score
4. Select note
5. Open Preferenses tab
6. Try to scroll "head" tab with elements 

**Expected behavior**
If we hover mouse cursor on one area, only for this are should work scrolling
we should 'lock' to a scroll. If a user has started scrolling one scrollbar, they should release their mouse button before they can scroll another. 

**Screenshots**
https://user-images.githubusercontent.com/71372310/134682027-4846d065-34a3-4150-87fa-b320a939e48d.mp4

**Desktop (please complete the following information):**
Windows 10
MacOS
Linux

**Comment by Tantacrul** [comment]
Don't understand issue. Since this issue is so old, I'm guessing it's no longer relevant (since it's about scrolling preferences)

**Comment by HemantAntony** [comment]
@Tantacrul This is fixed in the latest master. So doesn't matter
