### ISSUE TITLE
[MU4 Task] [MULTI_PROJECT_SYSTEM] Implement an ability to open score via "drag-n-drop"

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#9275]
**Task description**
We had this feature in MU3, definitely need to make sure that it's implemented in MU4

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10032

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
