### ISSUE TITLE
Palettes: Search button is slightly taller than 'Add' button and it's driving me crazy >:0 

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9278]
**Describe the bug**
See image:

![image](https://user-images.githubusercontent.com/21022311/134731487-85185f8f-3dd1-4d95-857b-444f4d050265.png)

**Expected**
Search button should be shortened to match 'Add Palettes' button height. On high res screens, it is 2px too tall. I imagine in code, it's probably just one pixel off. Not 100% sure.

**Comment by Dungtran713** [comment]
hey can i try to solve this issue

**Comment by Tantacrul** [comment]
Please :)

**Comment by Jojo-Schmitz** [comment]
Might be as easy as changing the 14 in 
https://github.com/musescore/MuseScore/blob/ade857a00bf29e4b95c613bb0c5829f5852946a5/src/framework/uicomponents/qml/MuseScore/UiComponents/FlatButton.qml#L63** to a 16

**Comment by RomanPudashkin** [comment]
See https://github.com/musescore/MuseScore/issues/8098
