### ISSUE TITLE
[Inspector] Page breaks incorrectly have 'Section Break' settings in the inspector

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9286]
**Describe the bug**
Page breaks have incorrect settings in the inspector
![image](https://user-images.githubusercontent.com/21022311/134780966-ff75bfc9-3b31-477c-9769-f62cb349dd7b.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a page break to a measure
2. Observe 'section break' options in the Inspector

**Expected behaviour**
Page breaks do not have any settings in the Inspector. Remove the Section Break options.

**Comment by Howard-C** [comment]
This issue is probably of the same type with the one I was trying to solve in the second commit of #8955 ("Avoid creating a tremolo section in the inspector if the tremolos selected can't have custom styles). Is there any progress regarding that @RomanPudashkin?

**Comment by DmitryArefiev** [comment]
Checked #9286 on Win10, Mac11.13.1, Linux Mint 20.2 - FIXED
