### ISSUE TITLE
[CRASH] Showing/hiding instruments in the 'Instruments' panel causes a crash

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9288]
**Describe the bug**
See video. Using the 'eye' symbol to show an instrument on a part score reliably causes a crash. See video:

https://user-images.githubusercontent.com/21022311/134788748-ce0044a7-e0ba-4a46-b909-3617f8bd039b.mov

**To Reproduce**
Steps to reproduce the behaviour:
1. Add 4 instruments
2. Open one of the parts
3. Using the 'Instruments' panel, enable one of the hidden instruments

**Comment by RomanPudashkin** [comment]
@Tantacrul

The crash has already been fixed, see:
https://github.com/musescore/MuseScore/pull/9274

Please, check it again on the last master build

**Comment by Tantacrul** [comment]
Confirmed. My nightly was one day too old. Apologies!
