### ISSUE TITLE
[MU4 Issue] Reset some palettes makes them another palette

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#9291]
**Describe the bug**
If a palette is reseted via the Context menu, it becomes a different palette in some cases.
e.g.
Reset of the Clefs palette leads to the KeySignatures Palette
Bevor reset:
![Palettes_Clefs](https://user-images.githubusercontent.com/63284090/134862284-c22e26c8-297c-4c3b-846c-4cd1e8421ead.png)

After reset:
![Palettes_Clefs_reseted](https://user-images.githubusercontent.com/63284090/134862299-b9ed3579-c8f4-442a-af99-1d8fe4399864.png)

Time Signatures -> Brackets
Accidentals -> Articulations
Noteheads -> Lines
Barlines -> Arpeggios & glissandi
Text -> Tempo
Dynamics -> Fingering
Repeats & Jumps -> Fretboard Diagrams
Beam Properties -> empty Palette

All Palettes reseted:
![AllPalettes_reseted](https://user-images.githubusercontent.com/63284090/134862343-ff65d1fd-f630-44f1-8ecc-8f9151f918b1.png)

**To Reproduce**
1. Open a score
2. Reset for example the Accidentals Palette

**Expected behavior**
The palette should just be reset to the default settings without changing the type

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by cbjeukendrup** [comment]
Related to #7769.

**Comment by mattblo** [comment]
This problem is fixed in the latest NightlyBuilds.
