### ISSUE TITLE
[MU4 Issue] Crash on copy and paste of a bar line to another bar line

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#9294]
**Describe the bug**
Musescore crashes when you copy a bar line and paste it on another bar line

**To Reproduce**
1. Create a new Score
2. Copy a bar line
3. Paste it on another bar line
4. Musescore crashes

**Expected behavior**
No crash, but paste the bar line succesfully

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9820
