### ISSUE TITLE
[MU4 Issue] Image added to score doesn't display on another OS (Win->Mac, Mac->Win)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9300]
**To Reproduce**
1. Create a score with image on Win ( [Image_Test_MU3_Win.zip](https://github.com/musescore/MuseScore/files/7237598/Image_Test_MU3_Win.zip) )
2. Open it on Mac

1. Create a score with image on Mac ( 
[Image Test MU4_Mac.zip](https://github.com/musescore/MuseScore/files/7237604/Image.Test.MU4_Mac.zip)
[Test_Image_MU3_Mac.zip](https://github.com/musescore/MuseScore/files/7237603/Test_Image_MU3_Mac.zip)

2. Open it on Win

**Screenshots**
![01](https://user-images.githubusercontent.com/90187801/134941423-422aaf5c-e287-450a-a12a-f5030663c2a5.png)
![02](https://user-images.githubusercontent.com/90187801/134941428-65480865-d675-41fc-8145-b3d02d0d3f9e.png)

**Comment by mattblo** [comment]
When an image is inserted and the score is saved, the image also no longer appears after closing and opening Musescore. Even if the operating system and everything remains the same

https://user-images.githubusercontent.com/63284090/135595262-9e045abe-aace-4fdd-afc5-ca8e5dbc18e7.mp4

.

**Comment by DmitryArefiev** [comment]
Thanks! @mattblo , I've noticed that too. But it occurs only when image is attached to the bar, not to the frame. Logged that as a separate issue - #9279

**Comment by DmitryArefiev** [comment]
Tested in latest master build (Win10, Mac12, LinuxMint 20.2) - **FIXED** (no longer occurs)

Closing
