### ISSUE TITLE
[MU4 Issue] Margins are not shown

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#9301]
**Describe the bug**

In MuseScore 3, you can view the margins by going to View > Show Page Margins. This behavior no longer works in MuseScore 4.

**To Reproduce**
1. Check View > Show Page Margins

**Expected behavior**

The margins should be shown visually in a similar manner to MuseScore 3.

**Screenshots**

This video compares the behavior in MuseScore 3 and MuseScore 4.

https://user-images.githubusercontent.com/5659171/134949655-3b9f93df-a107-43db-9bea-35a50a0104ee.mov

**Desktop (please complete the following information):**
 - OS: macOS 11.6

**Comment by njvdberg** [comment]
Seems to be solved in the latest master.
