### ISSUE TITLE
[MU4 Issue] Arrows on arpeggios do not connect with squiggle (Bravura)

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#9306]
**Describe the bug**

When using Bravura, an arpeggio arrow and squiggle don't line up perfectly. Perhaps the code to draw the arpeggio doesn't account for the repeat offset?

<img width="515" alt="Screen Shot 2021-09-27 at 2 26 59 PM" src="https://user-images.githubusercontent.com/5659171/134987746-08a5535c-f189-4f14-a128-0976bcd3715d.png">

**Expected behavior**

The squiggle and the arrow should seamlessly line up, just like all the other fonts. For instance, this is how Leland looks:

<img width="548" alt="Screen Shot 2021-09-27 at 2 27 23 PM" src="https://user-images.githubusercontent.com/5659171/134987780-e5d497a7-7da7-49a6-81c6-7a02482a26f3.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.6

**Comment by Tantacrul** [comment]
@oktophonie - is this one for 4.0 or 4.x?

**Comment by davidstephengrant** [comment]
This no longer presents in nighlies.

<img width="419" height="726" alt="Image" src="https://github.com/user-attachments/assets/9f66f6dd-c445-49f6-973c-dc28cd539920" />
