### ISSUE TITLE
[MU4 Issue] Tabbing inside a dialog box should trap focus

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#9319]
**Describe the bug**

When inside a dialog box (e.g., the Format > Styles… dialog), tabbing should trap focus to the dialog box. Instead, the tab focus is only on the main window.

**To Reproduce**
1. Go to Format > Styles…
2. Select a focusable field (e.g., "Music top margin" in the "Page" section)
3. Press tab
4. Watch as the tab focus moves throughout the main MuseScore window, not the focused dialog.

**Expected behavior**

When a dialog box is in the front, tabbing should only go through that dialog. At least on the web, this is the part of the [WCAG accessibility requirements](https://www.w3.org/WAI/GL/wiki/Using_ARIA_role%3Ddialog_to_implement_a_modal_dialog_box#Note_on_focus_management). I'm unsure what the best accessibility practices are for desktop applications, but I'd assume they'd be similar if not the same.

**Screenshots**

https://user-images.githubusercontent.com/5659171/135131899-f0162dda-d11d-4e55-afcf-bd04ff21f7d2.mov

**Desktop (please complete the following information):**
 - OS: macOS 11.6

**Comment by Eism** [comment]
fixed on https://github.com/musescore/MuseScore/pull/9639
