### ISSUE TITLE
[MU4 Issue] For default Clef delete option should be grey out

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9321]
**Describe the bug**
Delete option available for Default Clef - after clicking nothing happens
For default Clef delete option should be grey out

**To Reproduce**
1. Create a score
2. Right click on default Clef
3. Observe "delete" option

**Expected behavior**
For default Clef delete option should be grey out.

**Screenshots**
https://user-images.githubusercontent.com/71372310/135159280-8d24aff4-964c-4e34-80aa-1327832c3656.mp4

**Desktop (please complete the following information):**
Windows 10
MacOS
Linux

**Comment by Tantacrul** [comment]
Non-issue
