### ISSUE TITLE
[MU4 Issue] Unable to change title by double click on it

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9322]
**Describe the bug**
Unable to change title by double click on it

**To Reproduce**
1. Create a score
2. Double click on score`s title tab (Mouse Cursor on the screenshot)

**Expected behavior**
Change title by double click on it

**Screenshots**
![Change title by double click on it](https://user-images.githubusercontent.com/71372310/135176903-a748640f-46c8-49ba-9614-4d8fe7a1d80f.jpg)

**Desktop (please complete the following information):**
Windows 10
MacOS
Linux

**Comment by Howard-C** [comment]
Should this really be expected? It would involve disk operations. Do many apps do that?
