### ISSUE TITLE
[MU4 Issue] 3 pixels for scrollbar (from the right score side) to catch it if MU4 in window mode

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9325]
**Describe the bug**
Only 3 pixels for scrollbar (from the right score side) to catch it if MU4 in window mode.

**To Reproduce**
1. Create a score
2. Minimize MU4
3. Try to hover mouse button on the right score scrollbar (video attached)

**Expected behavior**
Scrollbar area should contain the same pixels as it`s icon (more than 3 pixels)

**Screenshots**
https://user-images.githubusercontent.com/71372310/135178553-d8d17bdd-a9f2-4051-9e0a-9488bd0932b4.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by Tantacrul** [comment]
Fixed
