### ISSUE TITLE
[MU4 Issue] Unison notes in multiple voices are often masked when selected

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9343]
Unison notes are not always visibly selected, and appear masked (i.e. not highlighted) behind the same note in a different voice.

See demo video: https://www.dropbox.com/sh/1n0658vcjujs3m9/AACHUrIsZgvxHk-w4llmTTU2a?dl=0

Behaviour is somewhat inconsistent: in some cases, a voice 1 note appears masked behind a voice 2 note, but most of the time a voice 2 note appears masked behind a voice 1 note.

**Expected behavior**
As per MS3.6: whatever voice is enabled should take priority and always be visibly selected (i.e. highlighted), irrespective of unison notes in other voices.

MacBook Air M1, MacOS 11.6
Windows 10

**Comment by wizofaus** [comment]
I'll have a look at this one.

**Comment by wizofaus** [comment]
BTW the specific issue is that the elements that are *selected* should always been drawn over the top of elements that aren't, which is a relatively easy fix.
But what voice is the "current" voice actually has nothing to do with it - that's only relevant in "note input" mode for the voice used for newly added notes.
Having said that, I'd agree there is a usability issue that there should be an easier way to select the notehead for a particular voice when there's a unison between two voices - even in MuseScore 3 it's really not possible using the mouse alone as far as I can tell (ALT+left/right seems to be the easiest).  Not even using the selection filter works, as that which only applies to range selections.  You can use the selection filter, make a range selection around the note then convert to a single item selection (in MS3 you could do use using the "Notes" button on the Inspector, in MS4 there's no single good way of doing so, but you can fudge it by ctrl+clicking the stem, which leaves you with just the notehead selected, providing your range selection hadn't included anything else).
For now I'll just restore the MS3 behaviour as far as drawing order goes.

**Comment by shoogle** [comment]
> there should be an easier way to select the notehead for a particular voice when there's a unison between two voices - even in MuseScore 3 it's really not possible using the mouse alone as far as I can tell

In MuseScore 3 this is done by holding Ctrl and repeated clicking on the notehead until the one you want is selected. This works regardless of how many notes are overlapping from different voices: just keep Ctrl+clicking until you get the one you want.

Ctrl+click is also used to select other objects that overlap, such as to select a text frame behind the text inside the frame.

**Comment by wizofaus** [comment]
Ah, I didn't know that, and in fact I've confirmed that's not been implemented in MS 4.  Will log.
