### ISSUE TITLE
[MU4 Issue] Space is allotted unnecessarily for key signatures on hidden staves

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#9345]
![unnecessary-time-signature-space](https://user-images.githubusercontent.com/20604032/135466132-e08a1ba6-c474-413a-9216-bf000e623bb2.png)

In the second system, the alto saxophone stave is hidden but empty space is allotted for the key signature that would appear on it. Space should only be made for key signatures that are actually visible on the system.

The same problem affects key changes (see the second bar on the second system).

See discussion at: https://musescore.org/en/node/50316

**Comment by Tantacrul** [comment]
Still happening. @oktophonie - lemme know if you expect to target this at 4.0!

<img width="421" alt="image" src="https://user-images.githubusercontent.com/21022311/166335081-528e5ddc-b93d-48c1-8dcc-45fcdc7b3b8f.png">

**Comment by MarcSabatella** [comment]
As you can see in that discussion, this problem goes back a *long* way, all the way to MuseScore 1.  I don't really remember the details, but I do remember the general complication around this.  The issue is that during the early stages of layout while we are calculating initial measure widths, we don't yet know which staves might be empty and thus hidden.  So we don't know yet whether or not we need to account for a key signature on the saxophone staff when calculating the position of the first note on the flute staff.  It's not an unsolvable problem, but it was beyond what I knew how to deal with back in 2015.  I'm kind of surprised to see me saying I couldn't see a solution even in 2020, but hopefully @mike-spa or @asattely can!

**Comment by Nick-Mazuk** [comment]
If I recall correctly, I started work on this in October and realized that it would be expensive to fix it with the current spacing algorithm. If the horizontal spacing algorithm is going to be overhauled at some point, that might be the time to revisit this.

**Comment by mike-spa** [comment]
@MarcSabatella is definitely right in that the decision to hide empty staves has to come after the decision of how many bars you fit in the line, i.e. after horizontal spacing. However, given the new system justification algorithm, there may be a workaround. I'll look into it! :)

**Comment by MarcSabatella** [comment]
I figure the worst case is, there is an additional pass needed to recalculate spacing in that first measure once it is settled that the staff will in fact be hidden.  But if it's possible to do that during the additional pass I believe you are already performing as part of your new horizontal spacing algorithm, that would be great!

**Comment by Nick-Mazuk** [comment]
When I was looking into it last fall, the worst case was actually:

1. Calculate the horizontal spacing to get the measures per system
2. Hide the staves
3. Determine which key signatures don't need space
4. Remove that extra space
5. Now that the extra space is removed, we can actually fit another measure on the system
6. Go back to step 1
7. After recalculating the number of measures, a new staff needs to be shown, causing us to add back in the space for at least one of the key signatures
8. Adding back in this key signature means we can no longer fit that extra measure on the staff
9. Go back to step 1, repeat

Now it's possible to never add back a new measure even if the space allows for it, but that can cause its own issues.

Did I explain this clearly?

**Comment by MarcSabatella** [comment]
@Nick-Mazuk yes, that sort of endless loop is indeed the potential problem, and we've encountered that before in similar cases involving things like key changes right at the system break where we are trying to decide if we will need a courtesy key signature or not.

But I do think doing what @mike-spa suggests is fine.  it might mean we *could* have fit one more measure if we had tried harder, but I'll take that over the current situation, which results is exactly the same number of measures but *also* bad layout of them,
