### ISSUE TITLE
[MU4 Issue] Unable to delete instruments using Instruments window if to start from the bottom of list

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9350]
**Steps to reproduce**
1. Create a new score
2. Open Instruments dialog window with **I** key
3. Add more instruments and click OK
4. Open Instruments dialog window with **I** key
5. Remove instruments starting selection from bottom
(see video below) 

**Screenshots**

![Instruments](https://user-images.githubusercontent.com/90187801/135621118-58b8ed88-6424-4405-8049-bdd49d465201.gif)

**Desktop (please complete the following information):**
 - OS: Win10/Mac11/Linux Mint 20.2

**Additional context**

**Comment by HemantAntony** [comment]
This appears to be fixed:

https://user-images.githubusercontent.com/88136054/152646184-293f5b22-527e-4f76-94d3-f075bfb19cd2.mp4

**Comment by DmitryArefiev** [comment]
@HemantAntony Thanks for checking! Yes, no longer occurs on my side as well.

**Comment by DmitryArefiev** [comment]
Tested in the latest master on Win10, Mac12, LinuxMint 20.2 - FIXED   

Closing
