### ISSUE TITLE
[MU4 Issue] Hidden instruments can still be heard / Blue cursor stays on a hidden instrument

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9357]
**Describe the bug**
Three bugs in this area:
1) Tempo doesnt hide 
2) Blue cursor stay on a hidden instrument
3) Hidden instrument playing 

**To Reproduce**
1. Create a score with one instrument
2. Add notes
3. Click on any note in the score (this step needed to cause 1-nd bug)
4. Hide instrument (Left side panel "instruments > click eye icon near instrument) (this step needed to cause 2-rd bug)
5. Click Play score button

**Expected behavior**
1) if all instruments are hidden, the play button should be deactivated and the user should not be able to play the score. This will prevent the playhead ('blue line') displaying like that
2) if you hide an instrument using the 'Instruments' panel, the instrument should be muted in the mixer. The user should be able to unmute it if they want.
3) Blue cursor should not be visible when all instruments hidden in the score

**Screenshots**

https://user-images.githubusercontent.com/71372310/135734496-814ae692-2a8e-4da1-9e60-2b499c71def9.mp4

**Desktop (please complete the following information):**
Windows 10

**Comment by Tantacrul** [comment]
@vshalkevich - nice find!

1. The tempo is actually not for just one instrument. It's for all instruments, so the tempo marking **should not hide.**
2. I think if all instruments are hidden, the play button should be deactivated. This will prevent the playhead ('blue line') displaying like that
3. Yes, if you hide an instrument using the 'Instruments' panel, the instrument should definitely not play. It should be silent in the mixer (not muted)

**Comment by Tantacrul** [comment]
The issue with hidden instruments playing is the most important part of this bug. I agree it is a P1 issue.

**Comment by Jojo-Schmitz** [comment]
I disagree, hidden staves are often used for playback purposes. We might murte it, but need to allow for unmuting.

**Comment by Tantacrul** [comment]
> I disagree, hidden staves are often used for playback purposes. We might mute it, but need to allow for unmuting.

Hmmm. I see what you mean, although it introduces some inconsistency with parts. We'd just need to keep that in mind.

Perhaps just muting the instrument when it is hidden (in the main score) is safer & more permissive. I'll amend my recommendation above.

**Comment by Jojo-Schmitz** [comment]
Well, I've not been able so far to include an invisble staff in a part, unfortunately, but whatever: it is needed for playback (and rehearsal) purposes in both

**Comment by DmitryArefiev** [comment]
Tested in master build on Win10, Mac12, LinuxMint 20.2

If you hide an instrument using the 'Instruments' panel, the instrument should be muted in the mixer - this is **FIXED**


_The user should be able to unmute it if they want._ - I put this to #10951

_Blue cursor should not be visible when all instruments hidden in the score_ - I put this to #10952

Closing

**Comment by Tantacrul** [comment]
> Whoever MoJo is

MoJo is the final evolutionary stage of the Jojo Pokemon. Even more German. Even more antagonistic :P

We GOTTA start calling him this.
