### ISSUE TITLE
Unable to hear instruments 'turned on' in parts scores

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9358]
**Describe the bug**
You can not hear new instruments when they are turned on in a part score

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new score with a trumpet, horn and cornet
2. Enter some notes in each instrument
3. Open the horn part
4. Press play (you can hear the horn playing)
5. Turn on the cornet instrument using the Instruments panel
6. Press play and notice that the cornet part can not be heard

**Expected behaviour**
When an instrument is 'turned on' it should be audible in the mixer

Please contact @Tantacrul if more info is needed.

**Comment by Jojo-Schmitz** [comment]
Is that a new bug in master/4.0? Because in 3.6.2 it works, once you uncheck the tick box "play part only" on the mixer

**Comment by Tantacrul** [comment]
> Is that a new bug in master/4.0? Because in 3.6.2 it works, once you uncheck the tick box "play part only" in the mixer

I think we should avoid a setting like that. My feeling is that we have everything we need in the existing feature set of mixer itself. We just need to massage the logic a little to get what we want.

**Comment by Tantacrul** [comment]
But to answer your question, yes. The audio engine is completely rebuilt, so there will be some deliberate / unforeseen inconsistencies with MS3.

**Comment by Tantacrul** [comment]
This has inadvertently been fixed with other related improvements to the Instruments panel!
