### ISSUE TITLE
[MU4 Issue] CI build fails with PR title contains `/`

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#9360]
**Describe the bug**

When a PR contains the `/` character, the GitHub Actions test build will fail. Specifically, the build artifacts cannot be uploaded. Here's a sample build failure.

https://github.com/musescore/MuseScore/pull/9359/checks?check_run_id=3783637639

**Expected behavior**

The title of a PR should have no impact to whether or not the build tests succeed.

**Comment by Jojo-Schmitz** [comment]
See faff816 which changed how those  artifact names get generated, Intersitingly not for the (disabled) Windoes 32-bit and PortableApp builds.

**Comment by Jojo-Schmitz** [comment]
See faff816 which changed how those  artifact names get generated, Interstingly not for the (currently disabled) Windows 32-bit and PortableApp builds, which seems another bug (and would probably need the same change).
That commit is now what broke it though, it just removed an `_` from the name.
Maybe `${{ github.event.pull_request.number }}`, i.e. picking on the PR number rather than the title would work here and be more reliable? @igorkorsukov ?

**Comment by igorkorsukov** [comment]
We have added a PR title to the artifact name to make the work of the testers easier. They download hundreds of artifacts, they need to distinguish them from each other easily.
I believe that the `/` symbol is not often present in the title of the PR, but it is better just not to use it. It's about the title of the PR, if it is created automatically from a commit, then we can just edit it.
I believe that making the testers' job easier is more important than being able to use the `/` symbol in the PR title.
Also, I think we do not need to waste time and complicate the CI scripts to be able to specify the `/` symbol in the PR title because there is no need for it.

**Comment by Jojo-Schmitz** [comment]
The PR **number** should make them distinguishable as easy, and even easier (think sorting them by name) than the **title**.

**Comment by Jojo-Schmitz** [comment]
Also it is more than just the / that is forbidden here:
`Invalid artifact name characters include: ",:,<,>,|,*,?,\,/.`

**Comment by cbjeukendrup** [comment]
Maybe even better if _both_ the number and the title are included. 

Anyway, at least on my computer, there is a relatively straightforward way to replace some special characters in the name:
```zsh
tr "/;:$" "_" <<< "\$a/vulnerable;name:"
``` 
gives
```
_a_vulnerable_name_
```

**Comment by Jojo-Schmitz** [comment]
Strange enough `;` is allowed (see above)

**Comment by igorkorsukov** [comment]
> The PR **number** should make them distinguishable as easy, and even easier (think sorting them by name) than the **title**.

It is unlikely that the tester remembers all the PR numbers, in order to find out what this artifact is for, they need to find it on the github - this is a waste of time. It should be borne in mind that a tester works with a dozen PR a day.

I believe the first is better than the second
1. MU4_1296840176_WinAccessibility. Inspector step1.zip
2. MU4_1296840176_Win9351.zip

We set the name for PR, I believe, we can improve the lives of others and make it simple and readable.

**Comment by igorkorsukov** [comment]
> Also it is more than just the / that is forbidden here: `Invalid artifact name characters include: ",:,<,>,|,*,?,\,/.`

We can add a step to the build workflow that will check the title of the PR, so that we know about the problem at the beginning, and not at the end of the build.

**Comment by Jojo-Schmitz** [comment]
Fail fast, fail early ;-)

**Comment by igorkorsukov** [comment]
> Maybe even better if _both_ the number and the title are included.
> 
> Anyway, at least on my computer, there is a relatively straightforward way to replace some special characters in the name:
> 
> ```shell
> tr "/;:$" "_" <<< "\$a/vulnerable;name:"
> ```
> 
> gives
> 
> ```
> _a_vulnerable_name_
> ```

I'm not entirely sure that this can be simply done on CI to set the artifact name (I don't know if it is possible to execute the script and return the name from it in this step). Maybe you give it a try and you will succeed? It would be great!

**Comment by cbjeukendrup** [comment]
Yeah, sure! I will try it today.

**Comment by Nick-Mazuk** [comment]
I see the usefulness of including the PR's title in the builds. And I understand how the artifacts may have forbidden characters. However, there are some issues with two the proposed solutions:

**Just forbid these characters from PRs, so nothing needs to be fixed**

- When creating a PR, there is no indication that certain characters will cause the build to fail, so contributors have no idea it will fail
- If someone does include a forbidden character, there isn't a way to rerun the jobs with a new title without pushing a useless commit (the "rerun workflow" button won't appear for non-member contributors and doesn't appear for me, either)
- Most PR reviewers assume (or at least should assume) that failing tests means a PR is not ready to be merged. Often, you can assume that a PR with failing tests doesn't need immediate review because the author already knows their PR requires adjustments. This code review assumption breaks down when builds/tests fail for any reason unrelated to the code. This would likely make tester's lives harder because now testers need to check every single PR.

**Fail fast, fail early**

- Better than not doing anything since at least feedback is immediate and not 20 minutes late, but it still suffers from every issue above

To me, it seems best to sanitize the input (i.e., replace forbidden characters with a valid one). I don't know if Igor's suggestion will work on CI, but we should try.

Once we allow our tools to erroneously fail, we can no longer trust our tools.

**Comment by igorkorsukov** [comment]
> Yeah, sure! I will try it today.

I figured out how we can do it! :)
We can add a new step for forming the name, execute the script in it and write the name to the environment variable. And then use this environment variable in the formation of the name of the artifact.
It's simple and should work!
@cbjeukendrup if you do not have time to do it, then I can do it tomorrow.

**Comment by igorkorsukov** [comment]
> I see the usefulness of including the PR's title in the builds. And I understand how the artifacts may have forbidden characters. However, there are some issues with two the proposed solutions:
> 
> **Just forbid these characters from PRs, so nothing needs to be fixed**
> 
> * When creating a PR, there is no indication that certain characters will cause the build to fail, so contributors have no idea it will fail
> * If someone does include a forbidden character, there isn't a way to rerun the jobs with a new title without pushing a useless commit (the "rerun workflow" button won't appear for non-member contributors and doesn't appear for me, either)
> * Most PR reviewers assume (or at least should assume) that failing tests means a PR is not ready to be merged. Often, you can assume that a PR with failing tests doesn't need immediate review because the author already knows their PR requires adjustments. This code review assumption breaks down when builds/tests fail for any reason unrelated to the code. This would likely make tester's lives harder because now testers need to check every single PR.
> 
> **Fail fast, fail early**
> 
> * Better than not doing anything since at least feedback is immediate and not 20 minutes late, but it still suffers from every issue above
> 
> To me, it seems best to sanitize the input (i.e., replace forbidden characters with a valid one). I don't know if Igor's suggestion will work on CI, but we should try.
> 
> Once we allow our tools to erroneously fail, we can no longer trust our tools.

You have listed really important reasons to fix this. Thanks.

**Comment by Jojo-Schmitz** [comment]
It is even much worse, `:` is forbidden too, and many titles have "Fix #xxxx:" in the title. See e.g. #9365

**Comment by cbjeukendrup** [comment]
@igorkorsukov I was thinking exactly that! Cool that we're on the same wavelength. 
Sorry, yesterday I was working hard on some improvements to the Inspector, which took quite a bit longer than expected. Today I will give it a try!
