### ISSUE TITLE
[MU4 Issue] Crash when clicking on a note in a little score (not specifiable) 

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#9363]
**Describe the bug**
Musescore crashes when a note is clicked directly after note entry in a 2 bar score

**To Reproduce**
1. Create an new Score
2. Delete the other bars (with Strg + Del), so that there are just 2 bars
3. Enter Notes
4. Klick on a note
5. Crash

**Expected behavior**
No Crash

**Screenshots**

https://user-images.githubusercontent.com/63284090/135808986-c793f4f9-f4ab-45af-b66d-2a9900d07699.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by mattblo** [comment]
This bug still occurs in the current NightlyBuilds. Also, when first entering the notes in the first two bars, then removing the remaining bars with Ctrl+Del, and then clicking on the first note, MuseScore crashes. @igorkorsukov Perhaps you could consider solving this crash?

**Comment by igorkorsukov** [comment]
@mattblo Thank you for the information. I confirm, there is a problem, we will fix it.

**Comment by igorkorsukov** [comment]
@DmitryArefiev This is fixed by https://github.com/musescore/MuseScore/pull/9822 Please check

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev This is fixed by #9822 Please check

Tested on latest master build on Win10, Mac12, LinuxMint 20 - FIXED

Closing

Thanks!
