### ISSUE TITLE
[MU4 Task] New design spec for inserting bars

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9385]
This is a new design that slightly tweaks how users insert bars (measures) in MuseScore:

https://www.dropbox.com/s/s4a5yf9dzypoyf3/UX_Design_Spec_Adding-bars_V2.pdf?dl=0

In a nutshell, we would like to:

- Add a "bars" dropdown section to the properties panel
- Add a popup to this new section, which users can use to quickly specify how many bars they want to enter into a score and where
- Rename current labels for adding bars in the menu bar and contextual menus

We are aiming to have this improved functionality ready for the release of MuseScore 4. 

Please let me know if you have any questions about this.
Thanks!

**Comment by bkunda** [comment]
> "The button to finally add the bars simply has "+". In many pieces of software, this design pattern with an input and a "+" button below it mean "add another input element, please!" as if it were a list. So perhaps adding some verbiage like "Insert" could help make the meaning more clear."

Yes this is an interesting one! The problem with adding some verbiage, such as "Insert bar", is that we also use this to trigger different popups and dialogs. I'm thinking that, on this one, it might be a matter of the user working out how to use this affordance by trying it out. 

> "Likewise, I wasn't entirely sure what the trash can icon meant until it was explained in slide 10. To me it looked like a "Delete the thing right next to it" pattern, which of course doesn't make sense… you can't delete the "insert bars" button! I'm not sure if there's a reason to change it as it's quite elegant once you know what it does. It was just not obvious when I first saw it."

Similarly with this; we also use this pattern in other places, such as the New Score dialog. As you say, it's quite elegant...once you work out what it does! 

<img width="1022" alt="Screenshot 2021-10-07 at 5 24 44 pm" src="https://user-images.githubusercontent.com/86290556/136331071-6b06fccc-0642-441b-96af-e911814af44b.png">

Our routes here might be to either reassess the add/remove button pattern in general, and/or to go ahead and implement this as designed for now and see whether users can easily discover how these buttons work during our early testing phases. We might be surprised!

**Comment by DmitryArefiev** [comment]
Hi @bkunda, can you check this on your side as well please?

I've tested briefly on Win/Linux, and it looks fine. I have only one suggestion: maybe not to close pop-up dialog after each clicking +


https://user-images.githubusercontent.com/90187801/151558373-b37da86b-120e-4245-be90-00ada44f11bf.mp4

Thanks!

**Comment by bkunda** [comment]
Hey @DmitryArefiev, tested briefly in MacOS and it seems to be working really well.
I totally agree with you – let's keep the popup open until the user closes it (by selecting outside of it, as usual). This makes more sense to me now that I can actually see the interaction!
Cheers, and thanks @cbjeukendrup!
