### ISSUE TITLE
[MU4 Issue] Images are not saving in the score

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9399]
**Describe the bug**
Images are not saving in the score (but they still visible on saved score preview)

**To Reproduce**
1. Create a score
2. Add image to the score (by drag&drop)
3. Save score
4. Open this saved score

**Expected behavior**
Image should be saved in the score

**Screenshots**
https://user-images.githubusercontent.com/71372310/136482204-4982f2d7-93e3-4d3c-b4e6-c9ffe1da67e2.mp4

**Desktop (please complete the following information):**
Windows 10 
MacOS
Linux

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
