### ISSUE TITLE
[MU4 Issue] [Inspector] [`OffsetSection`] Reset button is only connected to X offset, not to Y

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#9407]
**Describe the bug**
In the OffsetSection element in the Inspector:
- The reset button only becomes available when the X offset is changed, not when the Y offset is changed
- The reset button only resets the X offset, not the Y offset
The X and Y controls should be seen as one property, so when one of them is changed, the reset button should become available, and the reset button should reset both of them.

**To Reproduce**
1. Select any element in a score
2. Go to Inspector > Appearance
3. Change the values in the Offset section
(Note: also happens with other Offset sections, like in the inspector for notes > Stem > Show more > Stem offset and Flag offset.)

**Possible solutions**
Currently, the X and Y offset are implemented as two different `PropertyItem`s, but they share one `InspectorPropertyView`.
- We could either reimplement them as one `PropertyItem` which has the value of an (X, Y) point
- Or we could add some sort of `MultiPropertyItemView`, which would combine multiple `PropertyItem`s in one view.

**Comment by duanjr** [comment]
I'm curious why didn't we set an `InspectorPropertyView` for each `propertyItem`, that would be more natural.
Maybe for UI factors?

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED in #10603
