### ISSUE TITLE
[MU4 Issue] Volta adds to the next note measure if added to the right part of the selected measure (MU4 doesn't show attachment lines for voltas comparing with MU3)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9413]
**Describe the bug**
Volta adds to the next note measure if added to the right part of the selected measure (video 1 and 2)

That looks weird for user because MU4 doesn't show the attachment lines when adding voltas by drag'n'drop (comparing with MU3) - see video 3

So the **fix is to show the attachment lines when adding voltas by drag'n'drop** (like MU3 does)

**To Reproduce**
1. Create a score
2. Open Palettes tab 
3. Find "Volta"
4. Add Volta to the right part of a measure

**Expected behavior**
Show the attachment lines when adding voltas by drag'n'drop (like MU3 does)

**Screenshots**
1

https://user-images.githubusercontent.com/71372310/136713032-6fff1ab6-18c0-4f0f-80e1-f7cdd342a815.mp4

2

https://user-images.githubusercontent.com/71372310/136713034-5b9350f9-c46a-415d-820c-b2fa79d2b286.mp4

3

https://user-images.githubusercontent.com/90187801/163234413-6f50a992-afe8-4ea1-adae-734e57bf84de.mp4

**Desktop (please complete the following information):**
Windows 10
Linux
MacOS

**Additional context**
See how MU3 handles that problem

**Comment by HemantAntony** [comment]
I think this issue can be closed because connector lines for voltas have been added:

https://user-images.githubusercontent.com/88136054/186093403-5315681f-1e59-4365-ba5b-e7f8c688c062.mp4

**Comment by zacjansheski** [comment]
I am closing this issue.  Connector lines solve issue in current builds.
