### ISSUE TITLE
[MU4 Issue] Items displaced if "Bravura" font selected (Musical fonts should not listed in UI text settings)

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#9415]
**Describe the bug**
Frontend issue - items displaced if "Bravura" font selected (video attached)
 
**To Reproduce**
1. Create a score 
2. Open Preferences (Edit > Preferences)
3. Select "Appearance" tab
4. Select "Bravura" font 
5. Click OK

**Expected behavior**
Font should change but elements should not be displaced because Bravura is musical symbols font. 
**Musical fonts should not listed in UI text settings.**

**Screenshots**

https://user-images.githubusercontent.com/71372310/136713232-9895f294-e2bf-4e87-b65a-938619e408e0.mp4

**Desktop (please complete the following information):**
Windows 
MacOS

**Comment by Jojo-Schmitz** [comment]
Unless it is "Bravura Text"?

**Comment by Jojo-Schmitz** [comment]
Except maybe that Bravura (and other Musical Symbolf Fonts) should not be selectable in the first place?

**Comment by DmitryArefiev** [comment]
Agree. This is a low priority issue. We can fix it later.

**Comment by Tantacrul** [comment]
Not an issue.
