### ISSUE TITLE
[MU4 Issue] Unable to set a custom folder for VST (Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9420]
**Describe the bug**
**Mac** usually has standard location for VST files (not necessary to set a specific path in DAW)
But on **Win** there could be a several places for VST, and sometimes user chooses a custom location to save all plugins (e.g. on another drive).

Should be the way to setup a custom locations (multiple pathes) in MU on **Windows** 
 
![VST user folder](https://user-images.githubusercontent.com/90187801/136817570-e396a6a6-90ed-493e-a164-5988571ab007.PNG)

Also, could be **Rescan**/**Refresh** button (if its possible to add VSTs without restart) or a message about MU restart after adding a new VST locations

**Additional context**
Don't know how VST setup in DAW/Notation software works on **Linux**. It requires some investigation..

**Comment by Tantacrul** [comment]
Already a few complaints about this from people testing the alpha, so I bumped it to a P1.

**Comment by llui85** [comment]
On Linux, the VSTs are scanned in the [following folders:](https://developer.steinberg.help/pages/viewpage.action?pageId=9798275#VST3Locations/Format-OnLinuxplatform)

```
~/.vst3/
/usr/lib/vst3/
/usr/local/lib/vst3/
```

It might also be an idea to add a message about VST3 support only, as it's not what you'd expect for advertised "VST support" (led to a lot of headaches on my part).

**Comment by Tantacrul** [comment]
We will also need to allow users to specify multiple locations. MuseScore 3 did this pretty well for soundfonts. (Although we don't need the weird pen icon :) )

<img width="500" alt="image" src="https://user-images.githubusercontent.com/21022311/161384779-26ab4e33-cfd9-4442-a88a-dd767155277c.png">

**Comment by fgimian** [comment]
Just thought I'd add some thoughts on this from my experience.

With VST3, there is actually a standard location on Windows which is `C:\Program Files\Common Files\VST3`.  In fact, most plugin installers I've come across don't even let you change this.

Even Cubase doesn't let you change scan locations for VST3 plugins, only for VST2 plugins:

e.g.

![image](https://user-images.githubusercontent.com/1811813/161973725-7cab7875-db22-42a4-a39b-7b552a82689c.png)

Huge love
Fotis

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS, Windows 11
