### ISSUE TITLE
[Inspector] In the 'Barlines' section, the 'Left (start) repeat' option behaves incorrectly

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9429]
**Describe the bug**
This is a problem with MS3 that we have inherited for MS4

**Video**

https://user-images.githubusercontent.com/21022311/136942895-765e2ea7-a0cc-4197-b8c1-4602306d2d56.mov

**Comment by Tantacrul** [comment]
I don't know why I marked this as a P3 initially. It is quite broken functionality.

**Comment by wizofaus** [comment]
Can you provide repro steps in text, and I'll have a look, thanks.

**Comment by wizofaus** [comment]
Ok so fixing that specific problem is trivial - the weird thing is why the code was written that way in the first place as there's no good reason for it.
But there are a bunch of other bugs around barlines in the inspector, specifically with the very final barline (which should restrict which possible barline types can be selected) and similarly for any "initial" repeat barline added before the 1st measure.
Technically that's separate to the fix for changing a barline to "left repeat" but I'm guessing you'd rather it be fixed at the same time...

**Comment by wizofaus** [comment]
Ugh really struggling with this, it seems there's a bunch of logic to automagically re-create barline objects as needed according to "measure" properties, which stops many things working as expected (e.g. trying to change a "left repeat" barline to a dotted barline etc. In v3 doesn't even allow this!)

**Comment by wizofaus** [comment]
@Tantacrul I've put up a PR https://github.com/musescore/MuseScore/pull/12099 where you can try out my various fixes (described in the PR), see how you go with it.

**Comment by Tantacrul** [comment]
Moving to 4.x, since it is already an existing MS3 issue and we need to focus on the 4.0 release.

Will reopen when 4.0 is out.

**Comment by wizofaus** [comment]
@Tantacrul the initial reported issue may also happen in v3 but as per my comments above there's several cases where it's worse in v4. I believe the PR I put up went a long way towards addressing those but never received any feedback on it...

**Comment by MarcSabatella** [comment]
I think I pointed this out somewhere before, but don't see it now: I am pretty sure it was never really intended to be supported to create repeats in this fashion.  Seems that snuck in sometime a couple of years ago maybe, and obviously wasn't really tested.  I'd propose simply removing that option again - let people use the palettes as we've always supported / recommended.

**Comment by Tantacrul** [comment]
Yeah, I think that's the most sensible answer now. Just remove repeats from this list completely. @RomanPudashkin or @cbjeukendrup - do you think you could do this?

**Comment by Tantacrul** [comment]
Basically, they never worked properly, so they should just be removed.

- Left (start) repeat
- Right (end) repeat
- Right and left repeat signs

<img width="727" alt="image" src="https://user-images.githubusercontent.com/21022311/188087831-87eab543-7618-4801-94ae-d7b7f2732cfe.png">

**Comment by Tantacrul** [comment]
Also, @HemantAntony - any chance you might be able to help us out? I feel bad reopening a known issue. 😢

**Comment by rgreen5** [comment]
I believe this may be related to #13126 (points 2 and 3?).

**Comment by HemantAntony** [comment]
@Tantacrul I am able to remove those options from the dropdown. I wanted to know if you want me to remove the Repeat style properties also. You can access them after clicking a repeat bar:
![image](https://user-images.githubusercontent.com/88136054/188176798-e3b340f3-c7f3-496a-b0cc-d0706ced7289.png)

**Comment by MarcSabatella** [comment]
Those properties still work on repeat barlines added normally (from the palette), so I don't see any reason to remove this functionality - it's a nice improvement over MU3, where there was only a global style setting for the wingtips.

**Comment by HemantAntony** [comment]
@Tantacrul check #13138

**Comment by wizofaus** [comment]
Do these changes obviate the need for my PR which addressed a number of bugs around e.g. changing an existing repeat barline to a normal barline? How is this done now?

**Comment by MarcSabatella** [comment]
Same as always, I would assume - select and either press delete or change to regular using the palette.  I did manage to create a situation.  I do see a screen-redraw glitch where the latter doesn't immediately redraw the score with the new barline, but it does as soon as you touch almost anything.  That's a separate issue, of course.

**Comment by wizofaus** [comment]
But if you select a repeat, what style barline does it show in the inspector

**Comment by oMrSmith** [comment]
If you select a barline, then chose "left start repeat sign" 
the coresponding barline is created on bar later. Isn't that the whole problem?

![image](https://user-images.githubusercontent.com/78870770/188283277-52ccd2dd-b528-4812-8aeb-069ea06b8cff.png)

**Comment by wizofaus** [comment]
Yes but the proposal is to remove that option. My question is then if you create a repeat by adding from the palette then select the repeat barline what style should it show in the inspector.

**Comment by Tantacrul** [comment]
It's a good question - and I think in the short term, the answer is that we should disable the 'Style' dropdown in that instance.

Only other thing we can do is have dedicated options for 'Repeats' which includes everything except the 'Style' dropdown.

**Comment by wizofaus** [comment]
If that's the preferred design.  Note however that there are unit tests for what should happen when changing properties of barlines, which I fixed too in my PR.

**Comment by Tantacrul** [comment]
I asked @RomanPudashkin to have a peek at both PRs. Since we're really up against it, he recommends the simpler 'quick fix' that Hemant has done because @wizofaus, your solution may take more time for us to merge. However, we'll get back to it after 4.0 is released. Hope you don't mind: we basically need to spend our remaining time focusing on the highest priority issues.
