### ISSUE TITLE
Time Signature Properties popup: Icons not displaying and one dropdown not functioning

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9430]
**Describe the bug**
Two options from the 'Time Signature Properties' panel are not displaying / working in MS4 (see image)

1. The icons for 'Beam properties'
2. The options in the 'Other' dropdown

Please see MuseScore 3 to determine how these should look. If there is a need for the design team to create icons for 'Beam properties' in our icon font, then let us know and we will create them.

![image](https://user-images.githubusercontent.com/21022311/136944330-aec0fed5-4a40-41dc-b450-23b64cd49735.png)

**Comment by cbjeukendrup** [comment]
I just had another idea: how about moving at least those "appearance" settings to the Inspector? I suddenly thought it might actually make sense to have them there, instead of hidden in a dialog.
