### ISSUE TITLE
[Inspector] Ornaments options not displaying in the Inspector

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9432]
**Describe the bug**
See video:

https://user-images.githubusercontent.com/21022311/136950166-e4973539-8c9e-4179-b00e-671f8b430e5b.mov

Below is a screenshot of the spec where I've specified the new arrangement of options. @RomanPudashkin - this can be found on page 15 of the **Inspector_All_Remaining_Popups_V01.pdf** document.

![image](https://user-images.githubusercontent.com/21022311/136949991-17130406-2fdb-4a6a-8ca3-b5a5db14ce4c.png)

**Comment by Tantacrul** [comment]
Note: we should remove the 'Articulation properties' dialog from MS4, since it was never functional in MS3

![image](https://user-images.githubusercontent.com/21022311/136952953-8d20f15e-4fce-4689-8eff-42f8aeb79e52.png)

**Comment by boryskuzmenko** [comment]
**FIXED** in the PR [#10805 ](https://github.com/musescore/MuseScore/pull/10805)
