### ISSUE TITLE
[Inspector] Vertical, Horizontal and Text frames & 'Insert measure' do not have icons in the Palettes menu

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9434]
**Describe the bug**
If you observe the Palettes menu in 'layout' in MS4, you'll see that the **Vertical, Horizontal** and **Text** frame options do not display correctly
![image](https://user-images.githubusercontent.com/21022311/136953794-68a75b50-5aac-43de-937d-7838a1e68003.png)

In MS3, they look like this:
![image](https://user-images.githubusercontent.com/21022311/136953573-0f5289d6-07b9-40db-8dd5-3229633debb1.png)

If new icons are needed, these can be provided. Let us know!

**Comment by Jojo-Schmitz** [comment]
Well, "Insert one measure" existed ever since, shortcut "Ins"

**Comment by HemantAntony** [comment]
> @Tantacrul Tested in latest master build (Win10, Mac12, LinuxMint 20.2) - Vertical, Horizontal and Text frame icons are there now but **Insert one measure icon it still missing**
> 
> ![Capture](https://user-images.githubusercontent.com/90187801/149964707-f9bbde36-c13b-41fd-86a6-f9a9bb60933b.png)

If no one else is working on that, I can make this PR, if I get the Icon Code

**Comment by Jojo-Schmitz** [comment]
Isn't the icon 4 to the left from that the one for "Insertt one measure"? It looks remarkable similar to the corresponding one from MuseScore 3

**Comment by Jojo-Schmitz** [comment]
Hmm, no, that apparently is staff type change. But the icon IMHO does not convey that meaning well.
