### ISSUE TITLE
[Inspector / Crash] Crash caused when changing bracket 'column' or 'span' option

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9437]
**Describe the bug**
See video. Reproduces 100% on Mac OS, Catalina.

https://user-images.githubusercontent.com/21022311/136958047-8337796c-0775-493c-9453-e05e127babaa.mov

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac11, LinuxMint 20 - FIXED
