### ISSUE TITLE
It is not obvious when there is extra information in drop down controls.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9441]
**Describe the bug**
Across MS4, drop down controls are still very problematic because when they are opened, it is **very hard** to know that there is more information available.

### Scrollbars should be on by default

Scrollbars should be **always on** by default when there is scrollable information in a dropdown. This will greatly help the user know that there are more options available.

### The default number of options displayed should be increased from 6 to 18

- Currently, drop downs do not display enough information, usually only showing 6 options. We should change this default of 6 options and change it to 18. This will massively improve the UX of multiple different parts of the app.

Example: the font size dropdown: this has 12 options, but only displays 6. It should display all 12.
![image](https://user-images.githubusercontent.com/21022311/136979480-db19eb22-6438-435a-820d-9283e02ad772.png)

Another example is the 'Order' dropdown in the instruments panel. By default, it shows 6 options even though there are 11. It should display all 11.
![image](https://user-images.githubusercontent.com/21022311/136979673-c36ff25e-e86d-4129-aebb-e966ff8a9691.png)

Interestingly, the 'font' dropdown is larger by default, which makes sense. It seems to be set to a limit of 16. I think this should be 18.

![image](https://user-images.githubusercontent.com/21022311/136980101-ca0e52d8-ed93-4996-9b03-683b0bc91400.png)

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
