### ISSUE TITLE
[Inspector / Score] Selecting key signature regression from MS3. Causes inspector issues.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9445]
**Describe the bug**
Currently, if you select an individual key signature in MS4, it does not select all other key signatures on the same measure as  with MS3. Among other things, this causes the 'show courtesy' option in the Inspector to not function correctly.

See video:

https://user-images.githubusercontent.com/21022311/136994020-0bc6516c-d3af-4bc6-834c-9f54f8e07f1d.mov

**Expected**
Function in the same way as MS3

**Comment by boryskuzmenko** [comment]
**FIXED**
Tested on macOS, Win11, Linux
