### ISSUE TITLE
[Crash] Removing an accidental from an Ambitus causes MS4 to crash.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9447]
**Describe the bug**
See video:

https://user-images.githubusercontent.com/21022311/136996415-18a575de-8ae1-48f0-9148-02bf2aeac55a.mov

I'm making this a P0 on the assumption that it is part of a wider issue with crashing. If was was specific to the Ambitus, I'd probably mark it as a P1 or even P2.

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9831
I fixed the crash (triggering of the assertion in the development build). But it looks like the ambitus is not displayed correctly, if so, then I propose to have a separate issue with a different priority

**Comment by Jojo-Schmitz** [comment]
Apparently affects 3.x too

**Comment by DmitryArefiev** [comment]
Tested #9447 on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)


Found another crash when using ambitus #9866 (not caused by the current fix)
