### ISSUE TITLE
[MU4 Issue] When changing the UI font, text is displayed only in Regular (no bold / semibold, etc.) in UI (Windows, one machine)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9451]
**Describe the bug**
This came from #9354. I didn't see a fix for bold text in UI only on my Windows machine (using Arial or Tahoma)

https://github.com/musescore/MuseScore/pull/9354#issuecomment-934503781

https://user-images.githubusercontent.com/90187801/137016413-64c919c2-d74b-44bc-a156-8ae9ca9527d0.mp4

Will recheck it when installer is ready
  

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2 (19042.1237)

**Comment by Tantacrul** [comment]
Jess and Casper fixed this a few months back. Closing!

**Comment by DmitryArefiev** [comment]
It's still an issue on my side. Checked **Arial**, **Tahoma** , **Book Antiqua** on Windows 10, FullHD, 100% scaling.



https://user-images.githubusercontent.com/90187801/166732488-7d8783b1-6837-4cd4-92f7-ac59df4d89fb.mp4

@jessjwilliamson @cbjeukendrup Can you check this again please on your side? (On Windows 10, FullHD display, 100%scaling)

Thanks!

**Comment by DmitryArefiev** [comment]
@boryskuzmenko Can you check this on your side please? (Windows laptop)

**Comment by Tantacrul** [comment]
Thing is, we're no longer using Fira sans. We should update the issue. It's Segoe on Windows and SF Pro on mac.

![image](https://user-images.githubusercontent.com/21022311/166916241-554b9fa5-590a-4bae-a525-209bbf857b17.png)

So, I've tested Arial, Tahoma and Georgia (because I don't have Book Antiqua on this machine) on Windows:

Arial:
![image](https://user-images.githubusercontent.com/21022311/166916365-20699bd2-e664-45cf-8fec-0be3969cf4a2.png)

Tahoma:
![image](https://user-images.githubusercontent.com/21022311/166916464-26a68f3a-f728-4911-a5b4-e9053100f053.png)

Georgia:
![image](https://user-images.githubusercontent.com/21022311/166916601-9354dbb8-ea60-48e1-8684-a5565be197c2.png)

**Comment by Tantacrul** [comment]
Curios for others to share their experience. I wonder what is specifically causing it to fail on your machine @DmitryArefiev ?

**Comment by DmitryArefiev** [comment]
> Curious for others to share their experience. I wonder what is specifically causing it to fail on your machine @DmitryArefiev ?

@Tantacrul Yeah, curious to know too.. BTW what display resolution, scaling and Windows version you have?

**Comment by Tantacrul** [comment]
![image](https://user-images.githubusercontent.com/21022311/166931496-86e009e5-cdb6-4b17-b734-812f12371448.png)

**Comment by Tantacrul** [comment]
[image: image.png]

**Comment by HemantAntony** [comment]
@DmitryArefiev I can't reproduce. I'm on Windows 11
![image](https://user-images.githubusercontent.com/88136054/166932730-da10e6d1-45e1-4b75-9053-f37983bb45bd.png)

**Comment by jessjwilliamson** [comment]
The initial issue was that the 'bold' was using the Semibold option, which is what we were using as our textfields in Figma, and Fira Sans had semibold, but other fonts like Arial Tahoma etc. didn't have semibold. So fonts that didn't have that Semibold option, it used to go to Regular, which I pointed out to Casper and make that if there is no Semibold in a font, make that into normal Bold instead. 

What you have @DmitryArefiev I wonder if it's coding back to Semibold again. Segoe UI has a Semibold option but not fonts like Arial etc. 

Can you check on this @cbjeukendrup please :)

**Comment by boryskuzmenko** [comment]
> @boryskuzmenko Can you check this on your side please? (Windows laptop)

Can't reproduce this issue. Bold works on each font.

**Comment by cbjeukendrup** [comment]
I also tested it once more on my Parallels Windows, and it works fine, even for Edwin that has no semibold version. Maybe the bold version is somehow not correctly installed on @DmitryArefiev's computer?

**Comment by Tantacrul** [comment]
Do you have a pirated copy of Arial, @DmitryArefiev? 😆

**Comment by DmitryArefiev** [comment]
> Do you have a pirated copy of Arial, @DmitryArefiev? 😆

@Tantacrul Ahhh.. Don't think so😜

Let's close this one and reopen if someone else can reproduce it! :) 




> I also tested it once more on my Parallels Windows, and it works fine, even for Edwin that has no semibold version. Maybe the bold version is somehow not correctly installed on @DmitryArefiev's computer?

@cbjeukendrup I think I just like to setup my OS with turning off some graphical settings, using 100% scaling and small text size everywhere in OS. I've tried to change those settings to default but still no success to find the root cause..

**Comment by DmitryArefiev** [comment]
Closing
