### ISSUE TITLE
[MU4 Issue] Intermittent. Crash when using VST instrument on a track

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9460]
![Mac_Kontakt Player](https://user-images.githubusercontent.com/90187801/137165144-d3e11d71-8020-4a97-81df-0a1629c34b9f.gif)

**Desktop (please complete the following information):**
- VST: Kontakt with loaded library, LAB, IK Sample tank, DiscoDSP OB-xd, Mac12.0.1, M1 laptop
- Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-1377003661, revision: github-musescore-musescore-abc123456

**Additional context**
Adding info from #9534 case on Windows and closing the last one
> When using Kontakt Player 6 factory library als VST instrument Musescore 4 nightlighly build crashes on playback.
> It does not happen when using EWQL Symphonic Orchestra.

**Comment by lyrra** [comment]
This patch avoids a crash, but cant get audio from plugin towards musescore.
Suggestion to use m_processData.numOutputs came from: https://steinbergmedia.github.io/vst3_doc/vstinterfaces/structSteinberg_1_1Vst_1_1AudioBusBuffers.html
Not sure if it is correct, probably not, but can't find a reference example host.

diff --git a/src/framework/vst/internal/vstaudioclient.cpp b/src/framework/vst/internal/vstaudioclient.cpp
index f626904fee..df6933d8a6 100644
--- a/src/framework/vst/internal/vstaudioclient.cpp
+++ b/src/framework/vst/internal/vstaudioclient.cpp
@@ -97,14 +109,20 @@ audio::samples_t VstAudioClient::process(float* output, audio::samples_t samples
 void VstAudioClient::flush()
 {
     for (int i = 0; i < m_processData.numSamples; ++i) {
+        for (int outputsNumber = 0; outputsNumber < m_processData.numOutputs; ++outputsNumber) {
+            int numChannels = m_processData.outputs[outputsNumber].numChannels;
+            for (int s = 0; s < numChannels; ++s) {
+                m_processData.outputs[outputsNumber].channelBuffers32[s][i] = 0.f;
+            }
+        }
         for (audio::audioch_t s = 0; s < m_audioChannelsCount; ++s) {
             for (int inputsNumber = 0; inputsNumber < m_processData.numInputs; ++inputsNumber) {
                 m_processData.inputs[inputsNumber].channelBuffers32[s][i] = 0.f;
             }

-            for (int outputsNumber = 0; outputsNumber < m_processData.numOutputs; ++outputsNumber) {
-                m_processData.outputs[outputsNumber].channelBuffers32[s][i] = 0.f;
-            }
+//            for (int outputsNumber = 0; outputsNumber < m_processData.numOutputs; ++outputsNumber) {
+//                m_processData.outputs[outputsNumber].channelBuffers32[s][i] = 0.f;
+//            }
         }
     }
 }

**Comment by boryskuzmenko** [comment]
The issue is reopened.
Crash is still sometimes reproducible when VST instrument applied and playback is run (Kontakt with loaded library, LAB, IK Sample tank, DiscoDSP OB-xd)
