### ISSUE TITLE
[MU4 Issue] [VST] Changing playback device in Mixer should make score dirty and propose to save before closing

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9469]
**To Reproduce**
1. Change sound device (VST instrument)
 in Mixer
2. Close score - MU doesn't propose to save it (see video below)
![Changing playback configuration](https://user-images.githubusercontent.com/90187801/137334020-388b77a5-6d7e-455e-92d3-05ae3129be7f.gif)

**Desktop:**
Win10/Mac11/LinuxMint20

**Comment by vpereverzev** [comment]
It's just not yet implemented
