### ISSUE TITLE
[MU4 Issue] MU can open multiple copies of Master Palette during one session

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9474]
**To Reproduce**
1. Open score
2. Open Master Palette window
3. Close score (but not MU)
2. Open another score (or the same)
3. Open Master Palette window - you can see two Master Palette windows

![a8U536Ufr9](https://user-images.githubusercontent.com/90187801/137355815-bc329ded-2329-4479-bcf2-0028463bf852.gif)

**Desktop:**
 - OS: Win10/Mac11/LinuxMint20

**Expected Result:**
- MU should close Master Palette after closing current score
- or leave Master Palette opened (after closing current score) and not to create another copy of Master Palette and use that window for next score (like MU3 does)

**Comment by HemantAntony** [comment]
This occurs for Key Signatures and Time Signatures Dialogs too. I'm willing to bet that it occurs for all non-QML dialogs

**Comment by Tantacrul** [comment]
Since it can happen for other windows, I've 'elevated' it to a P3 :)

**Comment by cbjeukendrup** [comment]
@HemantAntony I'd rather bet it happens with all non-modal dialogs, QML or not 😉

**Comment by HemantAntony** [comment]
> Since it can happen for other windows, I've 'elevated' it to a P3 :)

There goes our only P4 bug

> @HemantAntony I'd rather bet it happens with all non-modal dialogs, QML or not 😉

I was going to bet my GSoC Application. Good thing I didn't do that 😀

**Comment by HemantAntony** [comment]
Can no longer reproduce
