### ISSUE TITLE
[MU4 Issue] When an accidental is selected on the score, clicking an accidental in the Note Input Bar does nothing

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#9476]
**Describe the bug**
When an accidental is selected on the score, I would expect intuitively that I can change that accidental by clicking a different accidental in the Note Input Bar, or in the Accidentals Palette. This is not the case; instead, nothing happens. I can only change the accidental by first selecting the note.

**Comment by iwoithe** [comment]
I noticed that this issue also occurs for articulations. Is this something you want fixed as well?

**Comment by iwoithe** [comment]
If happy, I can work on the other elements once the accidentals PR is done.
