### ISSUE TITLE
[MU4 Issue] Unable to run MU if VST plugin has a problems on start on Linux Mint 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9481]
**To Reproduce**
1. Install Linux Mint 20.2 Xfce Edition (from linuxmint.com)
2. Install VSTi from  https://u-he.com/products/zebralette/
3. Try to run MU4

see what Terminal shows - [terminal output.txt](https://github.com/musescore/MuseScore/files/7351823/terminal.output.txt)

**Expected behavior**
If there a problem to run VST instrument, MU should handle the exception and show a message about the problem 
(MU should not be blocked to run)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2 Xfce Edition installed on Win laptop

**Additional context**
Regarding VST problem on that machine, I need some time to investigate why it's not running, maybe some additional packages are not installed

**Comment by Tantacrul** [comment]
@DmitryArefiev - does this issue still persist?

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev - does this issue still persist?

@Tantacrul It's blocked for testing now #11550.. I would like to recheck the current issue when VST will be available on Linux

**Comment by diedeno** [comment]
So how will you use Zebralette without a GUI if this gets fixed?
This happens with lots of Linux VST's, and not only those from u-he.
But they are all unusable anyway since no gui in MS4.0. So why bother.

**Comment by DmitryArefiev** [comment]
> So how will you use Zebralette without a GUI if this gets fixed? This happens with lots of Linux VST's, and not only those from u-he. But they are all unusable anyway since no gui in MS4.0. So why bother.

@diedeno Yes, agree. The VST feature in Linux builds will be blocked for now - #11689
