### ISSUE TITLE
[MU4 Issue] Sidebar separator clashes with text labels when resized; does not reduce to icon-only view

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9488]
When the sidebar in "home" tab is resized, the vertical separator intersects text labels:

![Sibebar-issue](https://user-images.githubusercontent.com/86290556/137707379-5b287386-2481-4a78-bb43-9f336f31932e.gif)

**Expected behavior**
Sidebar should collapse to icon-only view when resized, and the separator should never intersect with text labels

![unknown](https://user-images.githubusercontent.com/86290556/137707638-06358d1c-3203-4702-addb-b4d01cc10f72.png)

MacOS 11.6
Windows 10

**Comment by m-qu** [comment]
This issue manifests slightly differently for me, with the vertical separator obscuring the test without collapsing to icon mode. I'd like to try to fix this issue

**Comment by duanjr** [comment]
I don't know if I undertand it correctly. My understanding is：
When the width is small enough, thoses texts shoule be invisible.
The vertical separator should be able to move smoothly, instead of jumping to far left.

**Comment by bkunda** [comment]
Hi @duanjr, you are correct on both fronts :-)
Btw the "jumpy" movement you see in my example is on account of the low frame rate (alas, it is merely a humble GIF).

**Comment by DmitryArefiev** [comment]
@bkunda or @jessjwilliamson  Please check how it looks now on your side (in master)? Thanks!

**Comment by bkunda** [comment]
Tested in MacOS. Looks good!

**Comment by DmitryArefiev** [comment]
Cool! Thanks!

**Comment by jessjwilliamson** [comment]
Beautiful! - Windows
