### ISSUE TITLE
[MU4 Issue] Revise beam placement algorithm

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#9494]
Within the stave, all beams should straddle a line, hang from it, or sit on it (not hover in the middle).

![beams1](https://user-images.githubusercontent.com/20604032/137855824-b90d4663-6ffe-49fa-8907-8f07f0d2f6da.png)

When slanting beams, avoid wedges between stem, stave line and the inside of beams:

![beams2](https://user-images.githubusercontent.com/20604032/137855844-f84c271c-2d27-4f49-91ad-ad071a965b46.png)

**Comment by RobFog** [comment]
This should be fixed with #9792?

**Comment by oktophonie** [comment]
Indeed so!
