### ISSUE TITLE
Staff/part properties has buttons with missing icons

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9508]
**Describe the bug**
(Mac OS - Catalina)

Right click on a measure and choose the Staff/part properties option. Observe how some icons are missing:

![image](https://user-images.githubusercontent.com/21022311/138056188-d3849424-a7e3-471a-a478-4be8180965c2.png)

Here is the same dialog from MS3
![image](https://user-images.githubusercontent.com/21022311/138056287-4ae86885-5be8-4794-812e-00ca47b2aa80.png)

@jessjwilliamson - can you specify (and make if needed) the correct icons and unicodes here?

**Comment by jessjwilliamson** [comment]
The 4 icons within the Usable pitch range should be our pencil icon - Unicode EF63

The bottom left ones are arrows- Unicode EF37 and EF36 (up then down)
