### ISSUE TITLE
[VST] Play shortcut does not work when VST window is open (Windows only)

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9520]
**Describe the bug**
Open a VST and press the spacebar button to play. Observe that the app doesn't play. It is essential that this works. Currently, if you click on the 'play' button, the VST popup goes behind the app window (another bug) and the overall experience is unusable.

**Fix**
Space bar (or any other shortcut) should work for play

**Additional details**
**Mac** part fixed in #11707
but still occurs on **Windows** (after editing VST controls)

**Comment by DmitryArefiev** [comment]
That fixed partially in #11707 - Looks **GOOD on Mac** , but **still has problems on Windows** (when editing parameters in VST window). 

I'll edit summary and description

@Tantacrul You can try **next master build for Mac** (it looks fine on my side but I'm not 100% sure)

Thanks!

**Comment by DmitryArefiev** [comment]
@Tantacrul Maybe move this to Beta2 since it works on **Mac** ?

**Comment by Tantacrul** [comment]
OK, although we should bump the priority (Windows is by far our larger audience)

**Comment by DmitryArefiev** [comment]
Fixed in #13719

**Comment by DmitryArefiev** [comment]
@Tantacrul The main part is fixed. The only issue left with Kontakt when loading instrument for the first time or reloading instrument.
The **same happens** with **Kontakt** and **ProTools** (v12). But works fine in Reaper.  So the issue can be on Kontakt side as well. 

I logged that separately #13737.
