### ISSUE TITLE
[MU4 Issue - Mixer] Grand Staff (Part 2)

### ISSUE THREAD

**Issue by SketalDaz** [musescore/MuseScore#9522]
**Describe the bug**
Ummm ....... I'm not **labeling** anyone :) .

**To Reproduce**
1. Open Musescore 4 and click "New Score"
2. Select two instrument with a grand staff (i.e. Marimba & Grand Piano)
3. Click "Done"
4. Click "Mixer"

// (1) Note that there are three audio strips for the first instrument and only one for the second instrument.

5. Fiddle with the Faders and Knobs of the two instruments

// (2) Note that the first audio strip is not independent from the second nor the third audio strip.

**Expected behavior**
1. Each staff of a score has their own independent audio strip in the mixer no matter if there is one staff (or multiple stave) for an instrument.
2. Audio Strips should be label to the instrument it represent by default

// **Update:** Out of curiosity, I opened a SATB template and notice that the Saprano staff has 4 extra audio strips. This is when I realize additional expected behaviors associated with this issue.

3. Each voice of a staff (4 voices max) has their own independent audio strip initially hidden behind the Main / Parent audio strip of the staff. So, for each staff there are a total of 5 audio strip with correct labeling.
4. The knob, Audio Fx, and Volume Fader of the Parent audio strip doesn't overwrite the same parameters of any voice audio strips and vice versa.
5. Selecting / Changing the Sound of the Parent Audio Strip Overwrites the Sound of all the Voice Audio Strips.
6. Changing the Sound of a Voice Audio Strip will clear the text of the Sound parameter of the Parent Audio Strip ( Indicating that not all voices have the same sound).
7. Clicking an arrow of a Parent Audio Strip unhides the audio strips of the 4 voices (similar behavior of the palette panel)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I wrote this early in the morning....
Part 2 of #9521 

Thank You!

**Comment by Tantacrul** [comment]
I believe this issue has been resolved with the completion of the core Mixer UI work. Closing.
