### ISSUE TITLE
[MU4 Task - Mixer] Mini Mixer Panel

### ISSUE THREAD

**Issue by SketalDaz** [musescore/MuseScore#9530]
**Task description**
Feature Request: Add a "Mini Mixer" (or a different name you believe sounds cooler) option to the view tab of Musescore 4.

**Expected Behavior**
1. When selecting the option, a vertical panel will be added to the workspace along with the Palette Panel, Inspector Panel. etc.
2. This panel will view two Audio Strips. The following illustration shows an example in a DAW (Cakewalk).

![261557708](https://user-images.githubusercontent.com/92967292/138552118-21dd5b3c-3b43-408b-87ad-20865e7eea5c.png)

3. The Master Audio Strip in the "Mini Mixer" will be the exact replica of the Master Audio Strip in the Main Mixer.
4. The Audio Strip on the left of the Master Audio Strip will view instruments dynamically base on user interaction with the score. For Example: when the user selects a note for the Grand Piano, this Audio Strip will become a replica of the Parent Audio Strip for the grand piano.

**Additional Context**
Issue #9521
Issue #9522

Thank You!

**Comment by Tantacrul** [comment]
Closing issue, since it isn't actionable.
