### ISSUE TITLE
[MU4 Issue] Preferences: English language not present in list

### ISSUE THREAD

**Issue by Marr11317** [musescore/MuseScore#9539]
See https://youtu.be/0Y0X10yiOYg?t=80

**Comment by HemantAntony** [comment]
I think this issue has been fixed:
![image](https://user-images.githubusercontent.com/88136054/147454882-f3c8d165-628a-469c-8ae6-c084a7af4378.png)
Also, I didn't know what English (GB) was. I have seen English (UK) more

**Comment by RomanPudashkin** [comment]
For development builds we don't run lupdate and lrelease targets. Therefore, we don't generate *.qm files in the install path. As a result, LanguagesSeverice marks the current language as NotInstalled and therefore it cannot be displayed in the preferences dialog. We will run these targets before release, so this list will work fine in the release build
