### ISSUE TITLE
[MU4 Issue] Hard to predict result when moving toolbars

### ISSUE THREAD

**Issue by Marr11317** [musescore/MuseScore#9545]
When moving toolbars around, a blue rectangle seems to indicate where the toolbar will be located, but it is super hard to predict the effect of dropping the toolbar.

2 suggestions: 
1) remove the blue rectangle and place a single cursor instead.
or 2) Make a better preview by moving the other toolbars to where they would be placed if the currently selected toolbar was dropped there.

see https://youtu.be/0Y0X10yiOYg?t=236

**Comment by RomanPudashkin** [comment]
The docking behavior was improved here:
https://github.com/musescore/MuseScore/pull/9649
