### ISSUE TITLE
[MU4 Issue] Opening new docks does not always add tabs

### ISSUE THREAD

**Issue by Marr11317** [musescore/MuseScore#9548]
In the video here, instead of placing the appearing dock besides the other docked on the left, it pushes everything to the right.

see https://youtu.be/0Y0X10yiOYg?t=412

**Comment by RomanPudashkin** [comment]
As far as I understand, this isn't a bug. The palettes panel restores its previous position after reopening. But it's very difficult to understand from the description of the issue
