### ISSUE TITLE
[MU4 Issue] Unable to deselect notes (objects) with Ctrl/Cmd

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9567]
**To Reproduce**
1. Select notes with Ctr/Cmd
2. Deselect some notes (holding Ctr/Cmd) - **it doesn't work in MU4**

![deselect](https://user-images.githubusercontent.com/90187801/138732564-e3cc1a57-f24c-4b91-a8c1-5ba87dda12d0.gif)

**Desktop :**
 - OS: Win10/Mac11/LinuxMint20

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please recheck, I can't reproduce at the moment

**Comment by HemantAntony** [comment]
I can't too. But I think I found a bug. Will report that soon. Click and drag a note 2 times. On the 2nd time, it will crash:

https://user-images.githubusercontent.com/88136054/145989392-726bd58e-bd1b-4427-834a-b513fc985a3a.mp4

**Comment by wizofaus** [comment]
I can't reproduce either the Ctrl+Click not deselecting or the crash, nor can I really see what might trigger either.  Are you able to provide a full stack trace @HemantAntony ? Going by what I can see I would say it's not a crash that would occur in a release build, just an assert failure (but still warrants investigation).

**Comment by HemantAntony** [comment]
I am around 120 commits behind the latest version. I am currently updating the code. I will try again and let you know

**Comment by HemantAntony** [comment]
Crash still occurs: #10100. I have created a new issue. I have provided instructions on how to reproduce the crash in the issue

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev Please recheck, I can't reproduce at the moment

Yes, this was fixed in #8908

No longer occurs in master
