### ISSUE TITLE
[MU4 Issue] Crash after closing score during playback

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9572]
**To Reproduce**
1. Open score
2. Start playback
3. Close score (with Ctr/Cmd+W or by clicking X)
![сrash](https://user-images.githubusercontent.com/90187801/138857453-7313450b-0093-45a1-b412-c70e33c16723.gif)

**Desktop:**
 - OS: Win10/Mac11/LinuxMint20

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9817

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED on Win and Linux but **STILL OCCURS** on **Mac** when using Cmd+W to close score during playback. Reopening

Steps to reproduce the crash on Mac
1. Open score
2. Start playback
3. Close score with Cmd+W

**Comment by DmitryArefiev** [comment]
Tested on latest master build on Mac12 using Cmd+W shortcut - **Can't reproduce** crash now

Closing
