### ISSUE TITLE
[MU4 Issue] Crash on put note with triplet

### ISSUE THREAD

**Issue by igorkorsukov** [musescore/MuseScore#9575]
**Describe the bug**
Crash on put note with triplet

**To Reproduce**
1. Create a new score
2. Click shortcut `C` (put note)
3. Select Triplet by Note Input Bar
4. Click shortcut `C` (put note)
5. Crash

**Expected behavior**
Should not crash

**Screenshots**

https://user-images.githubusercontent.com/3818029/138879270-93444594-15b5-4dd8-9fe9-0f156c49d79a.mp4

**Desktop (please complete the following information):**
does not depend

**Comment by bkunda** [comment]
I have been able to reproduce this in the latest nightly builds. This is a critical one to fix as entering tuplets is currently not reliably possible.

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check. PR https://github.com/musescore/MuseScore/pull/9832

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
