### ISSUE TITLE
[MU4 Issue] Multiple monitors - Whole app window only adjusts vertical size

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9576]
When moving the app from original monitor (right - 24") to 2nd monitor (left - 13"), the window does adjust the vertical height which is very good, but it does not do this horizontally. Would be great to do both vertical and horizontal automatically when switching monitors. This should also include going from a smaller monitor to a bigger monitor.

https://user-images.githubusercontent.com/71656189/138884813-403c9d44-6ec3-4783-9c47-80eb85a6254d.mp4

**Desktop (please complete the following information):**
 - OS: Mac OS

**Comment by cbjeukendrup** [comment]
I can't reproduce this currently on macOS. For me, the size of the window is adjusted horizontally too, and it behaves properly like windows from other applications, in this regard. 

So is this still actual?

**Comment by Tantacrul** [comment]
@jessjwilliamson, when you are back, can you re-test this?

**Comment by jessjwilliamson** [comment]
Would like to update this is now working properly and fine on MacOS! I don't have my PC to work with multi screens. @bkunda Can you also check if this issue looks okay to you pls? I think you have multi screens :)

**Comment by bkunda** [comment]
Happy to confirm this does not present as an issue for me in Windows :-)
