### ISSUE TITLE
[MU4 Issue] Palette "More" popups scroll together with palettes  

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9586]
In MacOS, when the "More" popup in palettes is opened, it is possible to scroll the popup outside of the MuseScore project window. This produces some undesirable results:

https://www.dropbox.com/s/wi0d3n2o6r1by3y/pallete-1-scrolling_popups.mp4?dl=0

Behaviour is slightly different in Windows: the "More" popup doesn't move at all when the palettes panel is scrolled. This also results in some undesirable behaviour (where the popup loses connection with its corresponding palette):

![Screen Recording 2021-10-28 at 01 37 01 74 AM](https://user-images.githubusercontent.com/86290556/139088076-446c1244-c7b6-4683-b4d2-37e66dc080b7.gif)

**Expected behavior**
I would suggest that, once a "More" popup has been triggered, scrolling of the palettes panel should be disabled.

 MacOS 11.6, Windows 10

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9835

**Comment by DmitryArefiev** [comment]
Tested on master build (Win10, Mac11, LinuxMint 20) - FIXED
