### ISSUE TITLE
[MU4 Issue] Palette "More" popups are persistent over dialogs

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9587]
When triggering a dialog from a "More" popup in palettes, the popup remains persistent over the subsequently opened dialog.

This also allows the user to open multiple instances of the subsequent dialog:

https://www.dropbox.com/s/nr0ycywjzwicltk/pallete-2-persistent_popup.mp4?dl=0

**Expected behavior**
Once a dialog has been opened from a button in a "More" palette popup, the popup should disappear.

**Desktop (please complete the following information):**
MacOS 11.6, Windows 10

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
