### ISSUE TITLE
[MU4 Issue] Palette items disappear from "More" popup when dragged into palette panel

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9588]
In some palettes, dragging an item from the "More" popup onto the main palettes panel causes other items in the popup to disappear:

https://www.dropbox.com/s/h3req01he4anyai/palette-3-disappearing_palette_items.mp4?dl=0

**Expected behavior**
Only the dragged item should disappear from the "More" popup. All other buttons should remain.

MacOS 11.6, Windows 10

**Additional context**
Grunts and groans in the background belong to my 10 weeks old son. Apologies!

**Comment by Eism** [comment]
@bkunda, I can't reproduce on master

**Comment by bkunda** [comment]
Hi @Eism, it seems this might have already been fixed.
