### ISSUE TITLE
[MU4 Issue] Main popup windows don't close with Esc

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9599]
**Describe the bug**
Main popup windows (Instruments, Parts, Preferences) don't close with Escape button (Esc)

https://user-images.githubusercontent.com/90187801/139275475-30a0bda5-2a10-44c6-8f93-df22d20648c9.mp4

**Desktop (please complete the following information):**
 - OS: Win10/Mac11/LinuxMint20

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10080

**Comment by DmitryArefiev** [comment]
Tested on latest master build (Win10, Mac12, LinuxMint 20.2) - FIXED
