### ISSUE TITLE
[MU4 Issue - Mixer] Labels and Audio Names

### ISSUE THREAD

**Issue by SketalDaz** [musescore/MuseScore#9604]
**Describe the bug**
Labels and audio strip names don't remain visible while scrolling.

**To Reproduce**
1. Open Musescore 4 and create a score using any existing template that has a lot of instruments.
2. Click "Mixer"
3. Condense the height of the Mixer Panel.
4. Scroll vertically 
 
// Notice that the audio strip names disappear

5. Scroll horizontally

// Notice that the parameter labels disappear

**Expected behavior**
Labels and audio strip names should remain visible during scrolling, so users can conveniently identify parameters and instruments when needed.

Recommendation: Since the solo and mute buttons are frequently used during audio editing and are conveniently close to the audio strip name, they should also remain visible.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Relates to #9149

**Comment by Tantacrul** [comment]
This has been noted in three other bugs... and they've all been moved to 4.x. Closing until then.
