### ISSUE TITLE
[MU4 Task - UI Felicia] Shades / Shadows

### ISSUE THREAD

**Issue by SketalDaz** [musescore/MuseScore#9605]
**Task description**
( In relation to #9404 , #9149 ,  &  #9604 )

I'm just want to recommend to add shades / shadows to the UI to help deliver some visual hierarchy to Musescore 4 and satsify users' experience when interacting with the UI. See rough illustrations below to see how I visualize this to occur.

Light Mode (Before & After)

![Musescore4WorkspaceShadowUI_LightMode](https://user-images.githubusercontent.com/92967292/139356408-d11ef46a-ad08-4f0b-b915-52b77bd3d528.png)

Dark Mode (Before & After)

![Musescore4WorkspaceShadowUI_DarkMode](https://user-images.githubusercontent.com/92967292/139356477-5a6fbd78-9c9f-4c76-a5ec-a66863052a25.png)

Thank You!

**Comment by Tantacrul** [comment]
We've made some improvements to drop shadow and have a separate task for it now. Closing this issue.
