### ISSUE TITLE
[MU4 Issue] Instruments panel Staff type doesn't show actual state 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9622]
![Staff type](https://user-images.githubusercontent.com/90187801/139679455-db8e0fb4-b7ea-456b-aecc-b16108466e93.gif)

**Desktop:**
 - OS: Win10/Mac11/LinuxMint20

**Comment by Tantacrul** [comment]
This was fixed last week, thankfully!
