### ISSUE TITLE
[MU4 Issue] Two Musescore 4's open while trying to create a new score

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9631]
**Describe the bug**
This doesn't happen all the time, but sometimes when creating a new score, a whole new window opens resulting in having Musescore 4 WITHIN Musescore 4. Should never work like this

https://user-images.githubusercontent.com/71656189/139834856-30146823-a3b4-4a21-89ad-a73713cbb217.mp4

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by jessjwilliamson** [comment]
> @jessjwilliamson this is because one score is already open in current MU4

How about here?

https://user-images.githubusercontent.com/71656189/139838449-2275de2e-690d-4e13-9bd1-7f973cd64bfd.mp4

**Comment by Eism** [comment]
> > @jessjwilliamson this is because one score is already open in current MU4
> 
> How about here?
> 
>  2021-11-02.11-28-44.mp4

Hm, yes it is strange
Does it reproduce only on Windows? Works fine for me on Linux

**Comment by jessjwilliamson** [comment]
> > > @jessjwilliamson this is because one score is already open in current MU4
> > 
> > 
> > How about here?
> > 2021-11-02.11-28-44.mp4
> 
> Hm, yes it is strange Does it reproduce only on Windows? Works fine for me on Linux

...Well, it's even worse on mac. And this fatal error must be very recent

https://user-images.githubusercontent.com/71656189/139843019-e654ffbb-39c9-458c-a25d-5c8ddd67de14.mov

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9814
