### ISSUE TITLE
[MU4 Issue] Full screen not covering everything

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#9632]
**Describe the bug**
When you go into full screen, you can see a thin transparent line above the windows task bar.

**To Reproduce**
1. Make sure the last window you clicked on is of a noticeable colour compared to your MuseScore theme. Since I am using the dark theme, the last window I clicked on was light themed one.
2. Just click on the fullscreen button on the top right corner.
3. You can see a thin transparent line above the task bar through which you can see the last windows you opened.

**Expected behavior**
It was expected that when in fullscreen, MuseScore would cover the entire space available. Since it does not, there is a thin transparent line.

**Screenshots**
![image](https://user-images.githubusercontent.com/88136054/139840698-8f752ec7-dfdb-4eb5-9a30-2dee8dcbfa57.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by mattblo** [comment]
related to https://github.com/musescore/MuseScore/issues/9263

**Comment by HemantAntony** [comment]
> related to #9263

Should I close this issue, then?
