### ISSUE TITLE
[MU4 Issue] Time digits position moves on every count

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9633]
**Describe the bug**
This relates to the test build https://github.com/musescore/MuseScore/pull/9617

I believe there was a set width to keep the time digits stable but now there seem to be a lack of resulting in the position to move around when score is being played.

https://user-images.githubusercontent.com/71656189/139847219-9254e24c-1919-4105-a76e-450c14197df9.mp4

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by jessjwilliamson** [comment]
> I'm working on it

Just made an issue related similar to this, but how it changes when fonts are involved :) https://github.com/musescore/MuseScore/issues/9727
