### ISSUE TITLE
[MU4 Issue] Volume textbox to be viewed off by default.

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9636]
**Describe the bug**
By default, the volume textbox should be switched off, just the volume fader slider available. 

**Expected behavior**

![Screenshot 2021-11-02 143748](https://user-images.githubusercontent.com/71656189/139868818-8c64f830-4a8e-4d31-975a-b56a78381c83.png)
![Screenshot 2021-11-02 143925](https://user-images.githubusercontent.com/71656189/139868913-c1adbc0c-a3ae-4e9f-a80a-2c3518254192.png)

**Desktop (please complete the following information):**
 - OS: Mac and Windows

**Comment by Tantacrul** [comment]
@jessjwilliamson - worth explaining a bit more: The volume text box is a separate thing to the volume slider. So we'll need a separate name for the volume sliders (so they can also be turned on/off in that context menu too).

Perhaps we can call them 'Volume (text)' and 'Volume'?

What does logic do?

**Comment by jessjwilliamson** [comment]
> @jessjwilliamson - worth explaining a bit more: The volume text box is a separate thing to the volume slider. So we'll need a separate name for the volume sliders (so they can also be turned on/off in that context menu too).
> 
> Perhaps we can call them 'Volume (text)' and 'Volume'?
> 
> What does logic do?

The volume text box is under 'Volume' and the volume slider is under 'Fader'. They are separate views :)

**Comment by Tantacrul** [comment]
@jessjwilliamson  you didn't include the 'fader' name in your visualisation of the mixer.

![image](https://user-images.githubusercontent.com/21022311/139910697-0470c9d8-b11d-4b18-9a28-9c1acb1d3637.png)

**Comment by jessjwilliamson** [comment]
> @jessjwilliamson you didn't include the 'fader' name in your visualisation of the mixer.
> 
> ![image](https://user-images.githubusercontent.com/21022311/139910697-0470c9d8-b11d-4b18-9a28-9c1acb1d3637.png)

Ah! Now it matters, it was not intended to have a name as it was intended to be paired with the text box. To answer your question about Logic, it has this:
![image](https://user-images.githubusercontent.com/71656189/139911368-aa3c7832-4817-4da9-901a-9b637666e3e4.png)

**Comment by jessjwilliamson** [comment]
> @jessjwilliamson you didn't include the 'fader' name in your visualisation of the mixer.
> 
> ![image](https://user-images.githubusercontent.com/21022311/139910697-0470c9d8-b11d-4b18-9a28-9c1acb1d3637.png)

I think the label 'Fader' would be confusing for users because it works as a volume. There was no intention to have a label for the fader itself in the original design before we decide to hide the volume text box. In this case. In previous designs however, I had the idea of using the label 'dB' as Logic does. How about the textbox is labelled as 'dB' and the fader as 'Volume'. How does that sound?

**Comment by Tantacrul** [comment]
Yeah, I realise that now. Let's drop this for the moment and just stick to the vertical space issues.

Thanks!

**Comment by DmitryArefiev** [comment]
Tested in latest master build (Win10, Mac12, LinuxMint 20.2) - PASS
