### ISSUE TITLE
[MU4 Issue] When adding or subtracting a row on the mixer, the window adjusts size.

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9642]
**Describe the bug**
As an example when adding or subtracting an Audio FX, the vertical window of the Mixer should adjust its size automatically. This is not just for audio FXs but also adding or subtracting certain views such as fader, pan, mute and solo etc. This is just as an example.

**Expected behavior**
When removing something from mixer:
![Screenshot 2021-11-02 160548](https://user-images.githubusercontent.com/71656189/139899425-1f99798f-9bf4-4260-a93f-fa18c8fa3c05.png)

When adding something from mixer:
![Screenshot 2021-11-02 160947](https://user-images.githubusercontent.com/71656189/139899573-46edafa8-30db-454b-a7ad-09b759a39c32.png)

**Desktop (please complete the following information):**
 - OS: Mac and Windows

**Comment by SketalDaz** [comment]
Hi @jessjwilliamson , could this be an optional check box ("auto resize") feature on the Mixer? I do see this being very handy especially for users who have large or multiple monitors. But, at the same time, I can see this getting annoying for those who have only a single monitor available and wants to keep the mixer open while heavily focusing on the score.

**Comment by DmitryArefiev** [comment]
Hi @jessjwilliamson I'm testing now #10614.. What do you think about auto resize Mixer when hiding Fader too?

https://user-images.githubusercontent.com/90187801/154946580-ffafed58-5bb2-4df3-8aed-bcc5b22a618c.mp4

**Comment by jessjwilliamson** [comment]
> 

Hi, yes including Fader too. :) I don't think as far as I'm aware we intended to set a minimum height as it's quite large anyway the height seems to stop at a certain number. Not sure why, would like it to be dragged as far as it can go. Do we know the value of the minimum height?

**Comment by DmitryArefiev** [comment]
> Hi, yes including Fader too. :) I don't think as far as I'm aware we intended to set a minimum height as it's quite large anyway the height seems to stop at a certain number. Not sure why, would like it to be dragged as far as it can go. Do we know the value of the minimum height?

@jessjwilliamson Roman has changed the minimum height in the latest change and now it looks better when hiding Fader too.

**Comment by jessjwilliamson** [comment]
> > Hi, yes including Fader too. :) I don't think as far as I'm aware we intended to set a minimum height as it's quite large anyway the height seems to stop at a certain number. Not sure why, would like it to be dragged as far as it can go. Do we know the value of the minimum height?
> 
> @jessjwilliamson Roman has changed the minimum height in the latest change and now it looks better when hiding Fader too.

@RomanPudashkin Great work!! Much better, thank you!
