### ISSUE TITLE
[MU4 Issue] Crash if to select Instrument name in score and hit Enter

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9643]
https://user-images.githubusercontent.com/90187801/139919012-f1a5b7f3-985d-418b-bf5b-75950406976c.mp4

**Steps to reproduce**:
1. Select Instrument name
2. Hit Enter **two times** (or better multiple times)

**Desktop:**
 - OS: Win10/Mac11/LinuxMint20

**Additional context**

**Comment by igorkorsukov** [comment]
@DmitryArefiev Can't reproduce, please check again

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev Can't reproduce, please check again

Can't reproduce it as well now

Tested on master build (Win10, Mac11, LinuxMint 20) - FIXED

Closing

**Comment by DmitryArefiev** [comment]
Roman found a way to reproduce this issue again! Thanks!

1. Select Instrument name
2. Hit Enter **two times**

Reopening

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
