### ISSUE TITLE
[Inspector] Text options are not showing indeterminate states.

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9644]
**Describe the bug**
Unless I'm mistaken (@wizofaus - please let me know. I can't remember if this is covered in your uber PR), text was in a better state before. Now if I choose two different sizes or fonts in the text editor, the respective dropdowns become non-functional. Notice also (in the video below) that the dropdown does not reliably display the correct text size sometimes.

- Choosing two different fonts should enter the font selection dropdown into an 'indeterminate state'. The dropdown should still allow the user to change the font.

- Same rule for font sizes

These are both very common rules in any text editor and have been specified in previous designs before. If needed, I can provide a more detailed explanation of the desired behaviour.

See video

https://user-images.githubusercontent.com/21022311/139941967-296a04cf-2ec6-4533-add2-a6610e981a23.mov

**Comment by wizofaus** [comment]
Last time I'd worked on it you could certainly still choose a new font or size if you'd selected two text elements (or multiple characters from one text element) that had different fonts/sizes. The only thing I hadn't got working was showing a "-" character to mean "multiple values selected", it just showed blank.

**Comment by Tantacrul** [comment]
OK, I think this is a regression then.

**Comment by DmitryArefiev** [comment]
Fixed in #10862
