### ISSUE TITLE
Persistent crash (Mac Catalina) when creating a new score or choosing a template

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9645]
**Describe the bug**
When adding an instrument in the New Score Wizard or choosing a template, the app crashes 100% of the time.

**OS**
Mac Catalina

**Video**

https://user-images.githubusercontent.com/21022311/139942707-7ca351c3-0669-45c8-9c3c-d0250a26348f.mov

**Comment by RomanPudashkin** [comment]
I can't reproduce this crash (macOS Big Sur). I asked @DmitryArefiev to help me

**Comment by Tantacrul** [comment]
I'm getting my builds from the Nightlies. I just installed it again and can no longer reproduce it.

Really sorry, I may have accidentally installed an older build. Closing for now.

**Comment by DmitryArefiev** [comment]
Can't reproduce either on the latest master build and Mac11.6 (M1 laptop)

**Comment by Tantacrul** [comment]
OK, thanks for confirming and sorry again!

**Comment by Tantacrul** [comment]
@DmitryArefiev @RomanPudashkin

Oddly, I just got the nightly build from yesterday (which contains resized new top bar) and the same problem is happening again. Exactly as described above. (Mac Catalina)

**Comment by DmitryArefiev** [comment]
@Tantacrul That's strange.. I've tried https://github.com/musescore/MuseScore/actions/runs/1419821185
on my M1 laptop with BigSur and still can't get a crash.

Maybe try to reset preferences, restart OS and try again?

**Comment by Tantacrul** [comment]
OK, thanks. I'll try again and see what's going on. It is beginning to feel like a "Martin's Laptop" problem :)

**Comment by Tantacrul** [comment]
So, this problem is still happening. I'm using Catalina (not an M1 device). It is persistent regardless of changes I make:

1. Restarted machine
2. Tried resetting MS4 settings.

**Comment by MarcSabatella** [comment]
Could be totally unrelated since as fart as I know this isn't supposed to be an issue anymore, but I don't suppose you have the macOS "hover text" option set?  That causes 3.6.2 to crash, apparently due to something in Qt.

**Comment by Tantacrul** [comment]
Ah! You've led me to the problem!

So, I have a keyboard viewer visible from time to time (see image)

![image](https://user-images.githubusercontent.com/21022311/140621469-a474fa4e-4b6d-436a-b97a-8a520ebc6614.png)

I've just hidden it and now the app is opening a new score properly.

@DmitryArefiev, go to System Preferences > Accessibility. Then scroll down to 'Keyboard' and choose the 'Accessibility Keyboard' tab. Then tick the 'Enable Accessibility Keyboard' option.

You can hide/show the Accessibility Keyboard up here:
![image](https://user-images.githubusercontent.com/21022311/140621549-2ccca2c1-8835-442d-b4b7-287c7e0dc857.png)


I've found that's when it is active, creating a new score persistently crashes.

@MarcSabatella, I could kiss you!

**Comment by cbjeukendrup** [comment]
Reproduced on macOS 12.0.1, M1 chip. The actual crash happens in code of ours (accessibleiteminterface.cpp, line 118), so we might be able to fix it. Maybe something for @igorkorsukov or @Eism?

**Comment by MarcSabatella** [comment]
Crazy, not even the same option that triggers it, or the same bug at our end, but I’m glad my comment somehow turned out to lead to the solution!

I’ll take the kiss in Hershey’s - or better yet, Belgian chocolate if we meet in Brussels
again :-)

**Comment by igorkorsukov** [comment]
> Reproduced on macOS 12.0.1, M1 chip. The actual crash happens in code of ours (accessibleiteminterface.cpp, line 118), so we might be able to fix it. Maybe something for @igorkorsukov or @Eism?

@Eism could you take a look?

**Comment by Eism** [comment]
> > Reproduced on macOS 12.0.1, M1 chip. The actual crash happens in code of ours (accessibleiteminterface.cpp, line 118), so we might be able to fix it. Maybe something for @igorkorsukov or @Eism?
> 
> @Eism could you take a look?

I'm working on it

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev, go to System Preferences > Accessibility. Then scroll down to 'Keyboard' and choose the 'Accessibility Keyboard' tab. Then tick the 'Enable Accessibility Keyboard' option.

@Tantacrul Yes, now I can repro it. Thanks!

**Comment by DmitryArefiev** [comment]
Could be related to #9609

**Comment by DmitryArefiev** [comment]
Tested on Mac11.6 - FIXED
