### ISSUE TITLE
[Inspector] Unable to change stem direction in a note group when selecting other than the first note in group

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9650]
https://user-images.githubusercontent.com/90187801/140068738-26b97894-54e8-491c-9eab-501bf3315dd7.mp4

**To Reproduce**
1. In a group of four eight notes, select 2nd or 3rd or 4th note 
2. Try to change stem direction in Properties - it doesn't work

**Expected behavior**
It should be able to change note goup stem direction  when selecting any note in group

**Additional context**
The same behavior in MU3

**Comment by LovCAPONE** [comment]
Since this issue isn't assigned to anyone I'll fix it and make a PR.

**Comment by Jojo-Schmitz** [comment]
(Easy) Workaround though is to select the note and press X
Or to select the beam and either press X or use the Inspector

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - PASS

**Comment by DmitryArefiev** [comment]
> 
> 
> (Easy) Workaround though is to select the note and press X Or to select the beam and either press X or use the Inspector

Yes, that workaround works. But found a bug: after applying flip direction (with X), changing stem direction in Properties no longer works to that note or group of notes) . Logged as #9779
