### ISSUE TITLE
[MU4 Issue] Docking button gets stuck on hover state

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9657]
**Describe the bug**
The docking button gets stuck on hover mode after I click and drag to dock somewhere else. To solve this hover state issue is to hover over again and it goes away.

https://user-images.githubusercontent.com/71656189/140333184-295ddf63-bacf-41c1-9736-7e657e7596b6.mp4

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
