### ISSUE TITLE
[MU4 Issue] menus wrongly drawn on second monitor

### ISSUE THREAD

**Issue by exegetor** [musescore/MuseScore#9658]
**Describe the bug**
If the MU4 window is maximized, the main dropdown menus will all be drawn disconnected, on a second monitor.
 
**To Reproduce**
1. Install a second monitor.  Place it above laptop.
2. Launch MU4.  Maximize the window on the laptop (i.e. lower monitor).
3. Click the File menu (or Edit, View, Add, etc.)
4. The menu "drops down" from the top of the upper monitor.  It is inaccessible because it is disconnected and the mouse can't reach it (before it disappears, that is).
5.  If MU4 is maximized on the upper monitor, the menus are drawn *behind* the window.  Again, inaccessible.

**Expected behavior**
A dropdown menu should be drawn within and above the main app window always.

**Screenshots**
will do if people can't replicate this

**Desktop**
 - OS: Windows 10.

**Additional context**
none

[EDIT - now that I think about it, here's some additional context.  Hi, I'm David, I'm new here.  I have a lot to learn, but I intend to stay onboard as far as I can.

**Comment by exegetor** [comment]
I have further narrowed the problem to Windows Scaling Factor.  The upper monitor (3440x1440) is at 175%.  The lower monitor (1920x1080) is at 150%.
I'm now fairly confident that my build system and environment, etc. are correct.

I'd like to work with someone one replicating this on one of your devboxes.  If I am correct, Windows Scaling causes a whole suite of glitches in QT/MU4.   I have 5 more related bugs to report but I wanted to take a pause and check with the community before getting to far ahead of myself.

**Comment by bkunda** [comment]
Can verify that this is still an issue:

![windows-dual-display-menus](https://user-images.githubusercontent.com/86290556/144053002-09700e08-f51a-48ea-849d-f4d94f9ebb66.gif)

Am wondering whether it is related in any way to #9263 and #9929?

**Comment by Eism** [comment]
Hey @bkunda and @exegetor!
Can somebody check the build from #9956
I'm not sure, but the fix might solve this issue too(I just can't reproduce this bug on my laptop)

**Comment by bkunda** [comment]
Hey @Eism, I've just checked #9956 and the issue still persists. 
lmk if I can help any further!

**Comment by Eism** [comment]
@exegetor @bkunda @DmitryArefiev
can you check PR #9956?

**Comment by DmitryArefiev** [comment]
I've tested #9956 on **Win10** with laptop display (1920x1080) 150% and monitor (1920x1080) 175% - it's **better now** only the **part of View menu still placed on the second display**  

<img width="960" alt="2 displays" src="https://user-images.githubusercontent.com/90187801/147640013-69bba135-0ae4-4618-a283-52d0121f06dd.png">
 
@bkunda Need your help to check it on your environment

**Comment by bkunda** [comment]
@DmitryArefiev I can reproduce the problem you have found with the View menu. Other menus appear to be drawn correctly.

**Comment by Eism** [comment]
> @Eism I have just discovered other instances where this same issue is being reproduced (this time on MacOS with properties buttons).
> 
>  properties-popups-drawn-on-second-display.mp4 
> Thought I'd mention it here because of its relevance, but would you prefer me to raise this as a separate issue?

thanks! fixed

**Comment by bkunda** [comment]
Sorry to have to reopen this one @Eism, but I've just found this issue persisting in the latest nightly build. 
Seems to affect some popups and anything from the "three-dots" icon.

https://user-images.githubusercontent.com/86290556/160374930-8d9914d9-1efd-4021-9780-c6a43ca6262f.mp4

@DmitryArefiev FYI

**Comment by Eism** [comment]
@bkunda 
please check #10928
