### ISSUE TITLE
[MU4 Issue] Sidebar menu titles rendered blurry on Windows

### ISSUE THREAD

**Issue by arsinclair** [musescore/MuseScore#9660]
**Describe the bug**
Sidebar menu titles rendered blurry on Windows

**Screenshots**
![image](https://user-images.githubusercontent.com/2878904/140598135-9bcd3991-be4f-4038-9bfa-48a9e62cef3b.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 Standard
 - Installer used: MuseScore-3.6.2.548021803-x86_64

**Additional context**
Clean installation (never used before on this machine).

**Comment by RobFog** [comment]
How is this a MuseScore 4 issue if the installer you used is MuseScore-3.6.2.548021803?

**Comment by arsinclair** [comment]
> How is this a MuseScore 4 issue if the installer you used is MuseScore-3.6.2.548021803?

Sorry, but Github only gave two options to choose from: `[MU4] Development issue` and `[MU4] Development task`. I thought this better falls under an issue, than a task. Besides, it wasn't clear what MU stands for, but I guess it is MuseScore?

**Comment by RobFog** [comment]
> Sorry, but Github only gave two options to choose from: `[MU4] Development issue` and `[MU4] Development task`. I thought this better falls under an issue, than a task.

Ah, yes. That is because only issues relating to Musescore 4 should be filed here. This is mostly done by members of the in-house team and other code contributors.

For issues affecting version 3.x please use the issue tracker at https://musescore.org/en/project/issues/musescore

> Besides, it wasn't clear what MU stands for, but I guess it is MuseScore?

Yep.

**Comment by arsinclair** [comment]
Okay, posted there, thanks.

Ref.: https://musescore.org/en/node/326201
