### ISSUE TITLE
[MU4 Issue] Esc doesn't takes out from Note Input mode (right after openning MU and creating a score)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9666]
https://user-images.githubusercontent.com/90187801/140795875-b2d99790-8140-4aef-bfdd-53e5bbcfadca.mov

**To Reproduce:**
1. Open MU
2. Create new score
3. Add some notes with keyboard (hit C, D, E)
4. Hit Escape  - MU is still in Note Enter mode (see video above)

**Desktop:**
Win10/Mac11/LinuxMint20

**Additional details:**
Was introduced recently (doesn't occur in build from Nov 1st)

After step 4, if to add some notes with mouse the issue stops to occur (and in the next opened scores too)

**Comment by wizofaus** [comment]
This is true for ALL actions that are only enabled for "UiCtxNotationFocused" context.
When the notation window is first opened it is not focused until it's clicked on with the mouse.

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10087

**Comment by DmitryArefiev** [comment]
Tested on latest master build (Win10, Mac12, LinuxMint 20.2) - FIXED

**Comment by wizofaus** [comment]
Unfortunately it doesn't seem to be working for other commands requiring the current notation to have the focus including using the cursor keys to navigate around the score (note that *some* commands like plain left/right don't work unless something is selected first, you can achieve this by using eg. Ctrl+F, 1, <enter> though, and at any rate ALT+left/right should definitely work with nothing selected, as should Ctrl+Home = go to first element etc. etc.)
@DmitryArefiev

**Comment by wizofaus** [comment]
Ok I found why the Home key doesn't work - EngravingItem::edit( ) is swallowing it any time you have a single selected element, which MU3 doesn't do, I'm not sure what this was supposed to support.

**Comment by igorkorsukov** [comment]
@wizofaus Thank you very much for the information.
I recently changed the behavior of the navigation system for a number of reasons, so in fact there may be similar problems now.
I will now investigate the problem and fix it.

**Comment by igorkorsukov** [comment]
@wizofaus I fixed it here https://github.com/musescore/MuseScore/pull/10110
