### ISSUE TITLE
[MU4 Issue] Paste (Cmd+V), Zoom In/Out (⌘ - and ⇧ ⌘ +), Undo (Cmd+Z), Redo (Cmd+Shift+Z) don't work each time, only on 1st, 3rd, 5th attempt (Mac only)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9667]
https://user-images.githubusercontent.com/90187801/140798967-e3f44b7c-bc6e-4542-99d6-39ca35631573.mov

**To Reproduce**:
1. Run MU
2. Open a recent score (or create a new one and add some notes)
3. Select 1bar with notes
4. Copy with Cmd+C shortcut
4. Select empty bar
5. Paste with Cmd+V
6. Select next empty bar 
7. Paste with Cmd+V - **nothing happens**
8. Select next empty bar 
9. Paste with Cmd+V - now it works
10. Select next empty bar 
11. Paste with Cmd+V - **nothing happens again** (see attached video above)

**Desktop:**
 - OS: **Mac11.6** (Mac only)
 
**Additional context**
It starts to work after opening Edit menu (see the 2nd part of attached video above)
Doesn't occur in **MU3**

**Comment by cbjeukendrup** [comment]
Same goes for zooming shortcuts (`⌘` `-` and `⇧` `⌘` `+`).

Also, in most macOS apps, including MuseScore 3.6.2, you can also press `⌘` `=` instead of having to press `⇧` `⌘` `+`. This makes using the zooming keyboard shortcuts a lot easier. But in MU4, it does not work; currently you have to use shift to zoom in, and not use shift to zoom out.

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Thanks!

> Same goes for zooming shortcuts (⌘ - and ⇧ ⌘ +).

Added to the Summary

> Also, in most macOS apps, including MuseScore 3.6.2, you can also press ⌘ = instead of having to press ⇧ ⌘ +. This makes using the zooming keyboard shortcuts a lot easier. But in MU4, it does not work; currently you have to use shift to zoom in, and not use shift to zoom out.

Found this logged as #9096

**Comment by DmitryArefiev** [comment]
@vpereverzev  Since it doesn't occur in **MU3** and other commands are involved adding to Alpha Release

**Comment by Tantacrul** [comment]
This is an extremely frustrating issue. With zoom it's bad enough, but with copy and paste, it is terrible. I'm assigning a p1 for this because copy and paste is so core to notation apps.
