### ISSUE TITLE
[MU4 Issue] Reinstate error dialog for Add > Text items

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9668]
**Describe the bug**
In MS3.6, when nothing is selected in the score, and when any of these menu items are selected...
<img width="350" alt="Screenshot 2021-11-09 at 7 41 48 pm" src="https://user-images.githubusercontent.com/86290556/140891500-45d5b02f-9074-4147-b8b4-9db6c32d7970.png">
The following dialog is triggered:
<img width="326" alt="Screenshot 2021-11-09 at 7 41 03 pm" src="https://user-images.githubusercontent.com/86290556/140891541-88a0fbc8-d746-4dcf-afec-8c7d77952914.png">

**This dialog has not yet been ported to MS4.** 

**A similar dialog should also be triggered for items in the Add > Bars and Add > Frames menus. These have also not yet been ported**

**Note:** 
All menu items highlighted above (in red) trigger the same dialog, _except_ **Figured bass**, which triggers this dialog:

<img width="322" alt="Screenshot 2021-11-09 at 7 43 38 pm" src="https://user-images.githubusercontent.com/86290556/140892075-fc261d6f-8a20-40db-aadd-4593566da66e.png">

**Note also:**
The menu item **Fingering** in MS3.6 currently doesn't trigger a dialog. This is probably a bug (it _should_ trigger the dialog).

**Desktop (please complete the following information):**
MacOS 11.6
Windows 11

**Comment by Eism** [comment]
@bkunda do we need the ability to skip the dialog next time?
('show this message again' checkbox)

**Comment by bkunda** [comment]
> @bkunda do we need the ability to skip the dialog next time? ('show this message again' checkbox)

Yes I think we should keep this checkbox. 

For some users, it will be a case of "learn once, never forget", meaning that, once they've learned that certain actions are only available in certain contexts, they can choose disable that error dialog if they find it annoying.

**Comment by Eism** [comment]
@bkunda in MU3, if the user chooses not to show the message again, for example, when trying to add 'staff text', then the dialog is also not shown when trying to add another text from Add->Text.
Do we want to change behavior?

**Comment by bkunda** [comment]
Let's keep it the same as MU3 for now. In a later release, we may do something more sophisticated (like disable all menu options that don't apply because the required object(s) are not selected), but this will need to be thought through a bit more.

**Comment by Eism** [comment]
Ok, implemented

**Comment by DmitryArefiev** [comment]
Hi @bkunda, Can you check this on Windows and Mac please? I'll check it on Linux then.

Thanks!

**Comment by DmitryArefiev** [comment]
@Eism @bkunda What I've found for now:

1. If nothing selected in score, the error dialog is not triggered if text added via Add>Text (separate bug)
2. The error dialog is not triggered for range selection

https://user-images.githubusercontent.com/90187801/149139995-5c475573-2824-4443-a549-03d68eff608f.mp4

**Comment by bkunda** [comment]
Nice spot about the range selection @DmitryArefiev!

**Comment by bkunda** [comment]
Sorry, I have put my comments in the PR: https://github.com/musescore/MuseScore/pull/10244#issuecomment-1011006140
