### ISSUE TITLE
[MU4 Issue] The undo/redo buttons get hidden in small window 

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9679]
**Describe the bug**
When first opening MS4, the undo and redo buttons get hidden on the right unless maximize then de-maximize again it calibrates itself back.

**Screenshots**

https://user-images.githubusercontent.com/71656189/140959770-88ed67e9-10b1-40ba-9f89-7705e5e18d72.mp4

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by cbjeukendrup** [comment]
It also becomes fixed when you just resize the window a tiny bit. The toolbars are not positioned correctly initially when opening MuseScore, but when the window geometry changes, it gets corrected.

Also, at the moment the rightmost ca. 3 pixels are always clipped of.

**Comment by jessjwilliamson** [comment]
> It also becomes fixed when you just resize the window a tiny bit. The toolbars are not positioned correctly initially when opening MuseScore, but when the window geometry changes, it gets corrected.
> 
> Also, at the moment the rightmost ca. 3 pixels are always clipped of.

I'm also realising this is happening at the bottom bar as well and the whole right side if a panel is moved there. This needs to be fixed, yes resizing makes a temporary fix but this shouldn't be happening 
![image](https://user-images.githubusercontent.com/71656189/141115575-76eb37e7-d9e7-4708-93ec-8d22477fced1.png)
