### ISSUE TITLE
[MU4 Issue] Drumset/percussion panel not being triggered

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9707]
**Describe the bug**
The drumset/percussion panel is no longer being triggered as it should.

**To Reproduce**
1. Create a score containing an unpitched percussion instrument
2. Activate "note entry" mode

This panel does not appear at the bottom of the project window:

<img width="759" alt="Screenshot 2021-11-11 at 9 54 37 pm" src="https://user-images.githubusercontent.com/86290556/141286179-89f73807-5a24-4cda-88de-1a87b1053e39.png">

**Expected behaviour**
Drumset/percussion panel should be triggered immediately upon the user entering "note entry" mode on a staff containing an unpitched percussion instrument.

**Desktop (please complete the following information):**
MacOS 11.6
Windows 11

**Comment by DmitryArefiev** [comment]
Tested on latest master build on Win10, Mac12, LinuxMint 20 - PASS
