### ISSUE TITLE
[MU4 Issue] Keyboard shortcuts for chord symbols aren't being recognised

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9708]
**Describe the bug**
Special keyboard shortcuts for **chord symbols** currently don't work in MS4.

**Expected behaviour**
Shortcuts for chord symbols should work as per MS3.6.

**Additional context**
To align with current behaviour in MS3.6, the following special keys should work as follows _when in CHORD SYMBOL edit mode_:
1. **Spacebar**: Moves cursor to next note/rest OR next chord symbol (where a chord symbol has already been entered) 
2. **Shift+Spacebar**: Moves cursor to previous note/rest OR previous chord symbol
2. **Return key**: Exists edit mode (chord symbols still remain selected)
3. **Semicolon/Shift+Semicolon**: Moves cursor to next/previous beat as defined by the meter, regardless of note/rest content
4. **Option+Spacebar (Mac)/Ctrl+Spacebar (Windows)**: Inserts actual space
5. **Tab/Shift+tab**: Moves cursor to start of next/previous bar
6. **Cmd+1...Cmd+9**: Moves cursor forward by corresponding note duration value (regardless of whether any note/rest is present. E.g. Cmd+4 moves cursor forward by an 1/8th note, allowing user to enter a chord symbol in the space 1/8th note to the right of their previous selection, even if there is no note or rest present in that space). 

See also: https://github.com/musescore/MuseScore/issues/9118

**Desktop (please complete the following information):**
MacOS 11.6
Windows 11

**Comment by DmitryArefiev** [comment]
Tested #9708 on Win10, Mac12, LinuxMint 20.2 - ALL EXCEPT **3. Return key** ARE WORKING NOW

Will log it separately
