### ISSUE TITLE
[MU4 Issue] Keyboard shortcuts for figured bass aren't being recognised

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9709]
**Describe the bug**
Special keyboard shortcuts for **figured bass** currently don't work in MS4.

**Expected behaviour**
Shortcuts for figured bass should work as per MS3.6.

**Additional context**
To align with current behaviour in MS3.6, the following special keys should work as follows _when in FIGURED BASS edit mode_ (NOTE: this is very similar to behaviour for chord symbols, with the exception of the **Return key**):
1. **Spacebar**: Moves cursor to next note/rest OR next figured bass digit (where a figured bass digit has already been entered) 
2. **Shift+Spacebar**: Moves cursor to previous note/rest OR previous figured bass digit
2. **Return key**: Moves cursor down one vertical space (allowing user to stack digits vertically). _Does not exit edit mode_. Numbers should remain vertically stacked upon exiting edit mode.
3. **Semicolon/Shift+Semicolon**: Moves cursor to next/previous beat as defined by the meter, regardless of note/rest content
4. **Option+Spacebar (Mac)/Ctrl+Spacebar (Windows)**: Inserts actual space
5. **Tab/Shift+tab**: Moves cursor to start of next/previous bar
6. **Cmd+1...Cmd+9**: Moves cursor forward by corresponding note duration value (regardless of whether any note/rest is present. E.g. Cmd+4 moves cursor forward by an 1/8th note, allowing user to enter a chord symbol in the space 1/8th note to the right of their previous selection, even if there is no note or rest present in that space). 

See also: https://github.com/musescore/MuseScore/issues/9118

**Desktop (please complete the following information):**
MacOS 11.6
Windows 11

**Comment by DmitryArefiev** [comment]
> 3. **Semicolon/Shift+Semicolon**: Moves cursor to next/previous beat as defined by the meter, regardless of note/rest content

@bkunda Found this doesn't work in MU3.6. Should it work in MU4 anyway?

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED      

> **Semicolon/Shift+Semicolon**: Moves cursor to next/previous beat as defined by the meter, regardless of note/rest content
since it's not available in MU3 will be removed in the next Roman's PR

> **Tab/Shift+tab**: Moves cursor to start of next/previous bar

this is replaced with Ctr+left/right
