### ISSUE TITLE
[MU4 Issue] Keyboard shortcuts for percussion sticking aren't being recognised

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9710]
**Describe the bug**
Special keyboard shortcuts for **sticking** currently don't work in MS4.

**Expected behaviour**
The following special keys should work as follows _when in STICKING edit mode_:
1. **Spacebar**: Moves cursor to next note/rest
2. **Shift+Spacebar**: Moves cursor to previous note/rest

**Additional context**
See also: https://github.com/musescore/MuseScore/issues/9118

**Desktop (please complete the following information):**
MacOS 11.6
Windows 11

**Comment by DmitryArefiev** [comment]
Tested on latest master build (Win10, Mac12, LinuxMint 20.2) - FIXED
