### ISSUE TITLE
[MU4 Issue] Opening scores from MacOS system file browser triggers "Home", not "Score" tab 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9712]
**Describe the bug**
When opening a score from the system file browser in MacOS, the user lands in the MuseScore "Home" tab instead of the "Score" tab:

![new-scores-open-in-home-tab](https://user-images.githubusercontent.com/86290556/141298391-3ea0f720-ac4b-458c-ba8f-5ed118042a82.gif)

**Expected behavior**
Opening a score should always take the user straight to the "Score" tab.

**Desktop (please complete the following information):**
MacOS 11.6

**Additional context**
Could not reproduce in Windows

**Comment by DmitryArefiev** [comment]
Tested  on Mac12 - FIXED
