### ISSUE TITLE
[MU4 Issue] Add/remove System Breaks dialog should should match MU3 behaviour

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9719]
**Describe the bug**
**1.** If nothing is selected, when open **Add/remove System Breaks** dialog it should select the whole score to make clear to the user that System Breaks operation will be applied to the whole score (like **MU3** does)
Even so, MU4 makes System Breaks changes in that case (that's expected)

https://user-images.githubusercontent.com/90187801/141475455-2bc56c79-d0a5-4ab1-a9f4-fe165aca3d9a.mp4

**2.** If some object is selected (**NOT** range selection), when open **Add/remove System Breaks** dialog it should select the whole score and change System Breaks changes (like **MU3** does)
Now if rest or note is selected, MU4 doesn't make selection of whole score and **doesn't make System Breaks changes** (the 2nd part is worse)

https://user-images.githubusercontent.com/90187801/141477327-deffb1c0-d62c-4818-84b5-5e8cd22ce998.mp4

 

**Expected behavior**
**MU4** should behave like **MU3** 

**Desktop:**
Win10/Mac11/LinuxMint20

**Comment by LovCAPONE** [comment]
Since this issue isn't assigned to anyone I'll fix it and make a PR.

**Comment by DmitryArefiev** [comment]
Tested on latest master build (Win10, Mac12, LinuxMint 20.2) - FIXED
