### ISSUE TITLE
[MU4 Issue] Note head remains selected when adding new time signature

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9720]
**Describe the bug**
Dragging a time signature onto a note head causes the note head to remain visible as if selected. It is then not possible to deselect the note head.

![time-sig-selected-crash](https://user-images.githubusercontent.com/86290556/141424797-cf3e54b1-cc83-4fdb-94ab-803f62dadd56.gif)

**Expected behavior**
Nothing in the score should appear as selected once a new time signature is dragged onto the score. 

**Desktop**
MacOS 11.6
Windows 11

**Additional context**
- This is also a bug in MS3.6
- As shown in above video, clicking on a subsequent note triggers a crash (known issue: see https://github.com/musescore/MuseScore/issues/9344)
- May also be related to this issue, but not sure: https://github.com/musescore/MuseScore/issues/9124

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10027

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
