### ISSUE TITLE
[MU4 Issue] Shift and Caps keys don't work in New Score Dialog

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9721]
**Describe the bug**
Pressing SHIFT or CAPS LOCK in any of the text fields on the the New Score Dialog (all tabs and screens) **disables** the text field.

https://user-images.githubusercontent.com/86290556/141448222-786ea412-cad0-4b49-b366-4a6d10590e12.mp4

**Expected behavior**
SHIFT and CAPS LOCK keys should allow users to enter capital letters, not disable the text field.

**Desktop (please complete the following information):**
MacOS 11.6
Windows 11

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac11, LinuxMint 20.2 - FIXED
