### ISSUE TITLE
[MU4 Issue] Part name on Mixer doesn't change

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9726]
**Describe the bug**
When editing the part name from the Instruments panel, it doesn't change the name on the mixer either. 

https://user-images.githubusercontent.com/71656189/141502466-3a4bcbf7-7693-4274-9229-9cf013434bf8.mp4

**Desktop (please complete the following information):**
 - OS: Windows and MacOS

**Comment by HemantAntony** [comment]
I have a solution to this issue. But I have no idea why it works. It just works. Maybe this can be a temporary solution?

**Comment by Jojo-Schmitz** [comment]
Submit it and we'll see?

**Comment by boryskuzmenko** [comment]
Also doesn't change in Part name in opened part tab
