### ISSUE TITLE
[MU4 Issue] The Brackets category doesn't match dark theme font colour

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9728]
In dark mode, the Brackets category doesn't match the dark font colour. Works fine in light theme.

https://user-images.githubusercontent.com/71656189/141511449-38074dbc-db09-4ea1-b857-2f56cee20eef.mp4

**Desktop (please complete the following information):**
 - OS: Windows and MacOS

**Comment by cbjeukendrup** [comment]
More or less duplicates #9381.
