### ISSUE TITLE
[MU4 Task] Implement "getting started" screens

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9742]
**Task description**

This task concerns the dialog that appears when the user opens MuseScore for the first time (immediately after installation).

Spec document sent directly to @vpereverzev.

**Comment by cbjeukendrup** [comment]
Isn't this duplicating #9468?

**Comment by vpereverzev** [comment]
@cbjeukendrup do you want to tackle this? It's not such a big, but still interesting task. If so, let me know

**Comment by bkunda** [comment]
Duplicate of #9468

**Comment by cbjeukendrup** [comment]
> @cbjeukendrup do you want to tackle this? It's not such a big, but still interesting visual task. If so, let me know

Yes, sure! Indeed a nice task. Would be great if you or Bradley could send me the specification document.
