### ISSUE TITLE
[MU4 Issue] Instrument name doesn't change in instruments panel when replacing instrument

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9745]
**Describe the bug**
When replacing an instrument, the instrument's name in the instrument panel doesn't update correctly.

https://user-images.githubusercontent.com/86290556/141954519-9d35c968-fae7-4a0a-87a6-cd41bcffa899.mp4

**Expected behavior**
1. Both the instrument panel label AND the part name should update with the name of the replacement instrument 
2. The instrument panel label should follow the name of the instrument in the main score, not the part name
3. The ability to create separate instrument names between the main score and the part should be retained

**Desktop (please complete the following information):**
 - MacOS 11.6
 - Windows 11

**Comment by HemantAntony** [comment]
I have fixed the issue with replaced instruments needing to be updated in the instruments panel with #10014

**Comment by bkunda** [comment]
Thanks for this @HemantAntony! 
A quick question: is there a reason you didn't set the name in the instruments panel to follow the main score name, rather than the part score name (Point 2 above)? It's not a major issue, but I think it would make more sense if the instrument panel name followed the instrument name in the main score rather than the part, as this is what users will be primarily working with. 
It might be an issue for another PR, but I'd be keen to hear your thoughts in case you've happened across something that I've overlooked 🙂. Thanks!

**Comment by HemantAntony** [comment]
I was trying mainly to solve the updating the instrument name part of the issue since there were like three issues related to that. But afterwards, I did try to solve this, I couldn't. But again, it was 3 weeks ago, I have learned a lot since then. So, I will look into this again

**Comment by bkunda** [comment]
Wonderful. Sounds good @HemantAntony. Good luck!

**Comment by HemantAntony** [comment]
I actually managed to fix this: #10221

**Comment by bkunda** [comment]
Many thanks @HemantAntony!

**Comment by DmitryArefiev** [comment]
Tested #10221 on Win10, Mac12, LinuxMint 20.2 - all issues are fixed
