### ISSUE TITLE
[MU3.6.2_backend Issue] Lyrics with a melisma across a system break protrude the system, into the page border

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#9747]
**Describe the bug**
Lyrics with a melisma across a system break protrude the system, into the page border

**To Reproduce**
1. in 3.6.2 have a score with lyrics and melismas.
2. Make sure at least one of those melismas crosses a system break (with the syllable before it being on the last note of the previous measure).
3. File > Save online.
4. See the error when viewing the score on musescore.com.
5. (Alternatively use the artifacts from #9000 and see the issue even locally).

**Expected behavior**
The lyrics' right edge should not protrude into the page border

**Screenshots**
![image](https://user-images.githubusercontent.com/1786669/141995032-85c0e391-2668-4be4-aa03-db9bd9348ac5.png)

**Desktop (please complete the following information):**
 - OS: Any desktop version that includes those 3.6.2_backend fixes (there is no official one), namely those from #9000
 - But the main point of this issue is the backend on musescore.com
 
**Additional context**
The culprit probably is #8296, but could also be #8176 or #8461
As far as I can tell none of those have yet been ported over to master, but as soon as that happens, that branch would also be affected. See also #9581, the first part of porting all those 3.6.2_backend fixes over to master

**Comment by Jojo-Schmitz** [comment]
There's another and related issue, see https://github.com/musescore/MuseScore/pull/9000#issuecomment-969341096
There lyrics with some (negative) `ticks` and/or `ticks_f` like this
```
          <Chord>
            <durationType>16th</durationType>
            <Lyrics>
              <ticks>-1800</ticks>
              <ticks_f>-15/16</ticks_f>
              <text>lyric</text>
              </Lyrics>
            <Note>
              <pitch>62</pitch>
              <tpc>16</tpc>
              </Note>
            </Chord>
```
settings destroy the layour quite badly.
It is compeltely unclear though (to me at least), how those came about.

**Comment by Jojo-Schmitz** [comment]
Example for both issues in https://musescore.com/user/23930/scores/7122651/s/LO8Qg1 
1st issue at several places, measure 5, 15, 18, 21, 26, 51, 54 (here including the Dynamics).
2nd issue at measure 28.

**Comment by gwillen** [comment]
Original reporter here -- the score (with negative tick values) was created in a release version of MuseScore 3, "3.6.2.548021803". Unfortunately, my friend who created it has no idea how she managed that, and I have no insight into reproducing that specific aspect.

**Comment by Jojo-Schmitz** [comment]
The workaround for that 2nd issue is quite easy: double click the next lyrics after the broken one, Press `Shift+Space` to move to the previous note, press `_` to add the missing melisma.

**Comment by Tantacrul** [comment]
@oktophonie - is this one we think is fixed in MS4? Or will we (as I suspect) need to wait for MuseScore.com uploads before knowing?

**Comment by Jojo-Schmitz** [comment]
This might meanwhile be an issue with 3.6.2_backend_musicxml rather than 3.6.2_backend and as such no longer actual?

**Comment by Tantacrul** [comment]
OK, closing for now (unless there is an objection). I don't see us fixing this in favour of focusing on uploads from MS4.
