### ISSUE TITLE
[MU4 Issue] When replacing a VSTi, current VSTi should be closed.

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9753]
**Describe the bug**
This is an unlikely situation but when a current VSTi window is open and a user goes and replaces it with another VSTi (while still open) the old VSTi should close and open with the replaced one. In this situation, the old VSTi still remains open even when it has been replaced. So here I originally had Soundpaint open, then I got and replace it with LABS. When LABS became activated, Soundpaint was still open and active when it should be switched off and closed.

It's hard to see both of the VSTi windows still open always as there is still an issue that the windows get moved behind MS4 when clicked off (Issue about this topic here.. very important this gets fixed https://github.com/musescore/MuseScore/issues/9157)

https://user-images.githubusercontent.com/71656189/142025398-58599ebd-ee48-4133-a59f-42a8646fa0ee.mp4

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by DmitryArefiev** [comment]
Fixed in #10911
