### ISSUE TITLE
[MU4 Issue] Vital - Free VSTi has bad glitch 2nd time opening.

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9756]
**Describe the bug**
VSTi called Vital which is one of the suggested free VSTis to try out, opens and looks fine (also plays fine) when first opened, but has a really bad visual glitch after 2nd time opening.

https://user-images.githubusercontent.com/71656189/142043893-80f5c362-41b3-4f46-8705-ee78f2b8e833.mp4

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by DmitryArefiev** [comment]
Hello @jessjwilliamson , can check this in build from #10581 on your side (Windows) please? 

Thank you!

**Comment by jessjwilliamson** [comment]
@RomanPudashkin Here is Vital. Unable to test the specific issue as it's also having this over-taking the screen issue. Can only use task manager (hence the black screen) to close Musescore to get out of it. 

https://user-images.githubusercontent.com/71656189/154482740-e1348854-613f-4bc8-9501-2f7c1e7173d0.mp4

**Comment by jessjwilliamson** [comment]
> **Describe the bug** VSTi called Vital which is one of the suggested free VSTis to try out, opens and looks fine (also plays fine) when first opened, but has a really bad visual glitch after 2nd time opening.
> 
>  2021-11-16.18-20-40.mp4 
> **Desktop (please complete the following information):**
> 
> * OS: Windows

This glitched UI after 2nd time opening is still happening :(
