### ISSUE TITLE
[MU4 Issue] Volume meter number labels are cut off

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9767]
**Describe the bug**
The right hand side of volume meter number labels are being cut off which is reducing the visibility

![image](https://user-images.githubusercontent.com/71656189/142201384-9ee02192-1c65-4e57-be45-2a401d10a5b3.png)

**Desktop:**
 - OS: Windows, Mac

**Comment by cbjeukendrup** [comment]
I've got a fix :)
