### ISSUE TITLE
[MU4 Issue] Assign MIDI Mapping dialog crashes

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9770]
**Describe the bug**
The dialog to assign MIDI device mappings from Preferences>MIDI Device mapping is currently unable to work without crashing.

https://user-images.githubusercontent.com/71656189/142218431-f31d57c0-50b4-425f-ba61-52f05f4f8ead.mp4

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
