### ISSUE TITLE
[MU3.6.2_backend Issue] Empty measures don't hide on musescore.com

### ISSUE THREAD

**Issue by Jojo-Schmitz** [musescore/MuseScore#9771]
**Describe the bug**
Empty measures don't hide on musescore.com

**To Reproduce**
See the issues and forum topics and the scores that go along with them

**Expected behavior**
The backend in musescore,com (taken from the 3.6.2_backend branch) should render scores the same as the released version, 3.6.2.

**Screenshots**
From Discord, in 3.6.2:
![image](https://user-images.githubusercontent.com/1786669/142220033-b177397b-14a6-49bb-a7fb-8a84979a3aa8.png)
On musescore.com (and in the artifacts of PR #9000 too):
![image](https://user-images.githubusercontent.com/1786669/142220136-f07e5bd7-af26-4fcc-81d9-8c03877f952c.png)

**Desktop (please complete the following information):**
 - OS: Any desktop version that includes those 3.6.2_backend fixes (there is no official one), namely those from #9000
 - But the main point of this issue is the backend on musescore.com
 
**Additional context**
Sample scores:
* https://musescore.com/user/33808446/scores/7080352/s/c2v74K (measure 169 ff.,  from https://musescore.org/en/node/325769, not downloadable)
* https://musescore.com/user/16766271/scores/6748785 (measure 8 ff., from https://musescore.org/en/node/326525)
* https://musescore.com/user/36526887/scores/7115942 (from https://musescore.org/en/node/326525)

As far as I can tell none of those 3.6.2_ backend changes have yet been ported over to master, but as soon as that happens, that branch would also be affected. See also #9581, the first part of porting all those 3.6.2_backend fixes over to master

See also https://musescore.org/en/node/325769 and https://musescore.org/en/node/326525 and https://discord.com/channels/818804595450445834/818804595450445837/910323615252230154

**Comment by Tantacrul** [comment]
@oktophonie - I'm not sure how to prioritise this or whether we expect it to be an MS4 issue. Any advice?

If we think these kinds of issues are 3.6.2 backend specific, then I'll create a new designation for that, so we can remove them from the 4.0 list.

**Comment by Jojo-Schmitz** [comment]
This might meanwhile be an issue with 3.6.2_backend_musicxml rather than 3.6.2_backend and as such no longer actual?

**Comment by Tantacrul** [comment]
I'm closing for the moment because this isn't a 4.0 issue and we're not going to be able to tackle it until after 4.0 is out anyway.

I've marked it as 4.x just so we return to it later during planning.

**Comment by Jojo-Schmitz** [comment]
It is a problem with the 3.6 backend, I don't see how that would change with and 4.0 or 4.x backend?

I'm not sure thoufh whether it really is a 3.6.2_backend issue or a  3.6.2_backend_musicxml one and as such no longer relevant at all.

**Comment by Tantacrul** [comment]
It's counter intuitive to mark it 4.x, I know. But it just means we'll look at the issue after 4.0 is out. Because relevant or not, we won't be addressing it until 4.0 is out.

**Comment by Jojo-Schmitz** [comment]
It is counter intuitive to close it...
