### ISSUE TITLE
[MU4 Issue] Note size renders incorrectly in tempo text in MacOS

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9776]
**Describe the bug**
In MacOS, the size of note characters in tempo text is larger than the regular text size.

![Oversized-noteheads-characters-in-tempo-text](https://user-images.githubusercontent.com/86290556/142397555-b1f3d063-7104-4132-8f8e-8dfe636630be.gif)

**Expected behavior**
Font sizes for note characters and text should be the same.

**Desktop (please complete the following information):**
 - MacOS 11.6
 - Not reproducible in Windows 11

**Comment by Nick-Mazuk** [comment]
Hey Bradley, do you mind sending the document you used to create that? I have an idea of why that might be happening, and having the same document you're using could help validate or refute that theory.

**Comment by oktophonie** [comment]
Fixed now that the latest Leland is in master.
