### ISSUE TITLE
[MU4 Issue] Inserting hairpins using keyboard shortcuts changes score position

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9780]
**Describe the bug**
Using the keyboard shortcuts ">" and "<" ("Shift+," / "Shift+.") to enter hairpin lines works to enter the actual hairpin, but changes the position of the score in seemingly erratic ways:

![hairpins-change-zoom](https://user-images.githubusercontent.com/86290556/142411954-00d1372a-76fd-4c86-a5ec-dda57dd93462.gif)

This behaviour seems to affect hairpins entered over a range, as opposed to those entered on a single note.

I could not reproduce this behaviour when inserting hairpins from the palettes. 

**Expected behavior**
Entering hairpins using key commands should not affect score position.

**Desktop (please complete the following information):**
 - MacOS 11.6
 - Windows 11

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please actualize, I can't reproduce

**Comment by HemantAntony** [comment]
I can reproduce

**Comment by HemantAntony** [comment]
Try moving the score so that only half of the future hairpin will be visible, then use the shortcut, it will move. You can also zoom in a lot and then use the shortcut. Here, when you undo, also the score moves

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
