### ISSUE TITLE
[MU4 Issue] MU adds double text to the note when using navigation (in some cases)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9785]
https://user-images.githubusercontent.com/90187801/142427964-834d4d61-1c94-45b5-8efd-3e5ac368fb6b.mp4

**To Reproduce**
Using navigation with Tab and arrows
1. Add some notes
2. Navigate to Palettes>Text
3. Add Staff text

**Desktop (please complete the following information):**
macOS, Windows, Linux

**Additional context**
Doesn't occur in **MU3**

**Comment by Tantacrul** [comment]
Hey Dmitri, I'm unable to reproduce this on Windows. Is it still happening for you?

**Comment by DmitryArefiev** [comment]
> Hey Dmitri, I'm unable to reproduce this on Windows. Is it still happening for you?

@Tantacrul Yes, it's still reproducible in latest master (all platforms). You should use only keyboard. Sorry about missing steps in the description (added now)



https://user-images.githubusercontent.com/90187801/168049418-159b82c6-46a5-46ff-8058-578e7581aa3c.mp4

**Comment by DmitryArefiev** [comment]
Fixed in #12725
