### ISSUE TITLE
[MU4 Issue] Click and drag does not work while score plays

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9786]
**Describe the bug**
While the score is playing, you can use mouse wheel or scroll bars to scroll while the score is playing, but the click and drag scrolling stops working.

https://user-images.githubusercontent.com/71656189/142432235-9189c7e9-85d4-4d00-bf80-fee9b3308923.mp4

**Desktop (please complete the following information):**
 - OS: Windows (could be Mac also)

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10147

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
