### ISSUE TITLE
[MU4 Issue] Text on the bottom bar squeezes to two lines

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9787]
**Describe the bug**
Just found this issue when I click on a tempo, the text at the bottom left becomes into two lines when it should be just 1.
This is may be related to the recent bottom bar vertical size reduction? https://github.com/musescore/MuseScore/issues/9690

![Screenshot 2021-11-18 144618](https://user-images.githubusercontent.com/71656189/142437766-d8f7e7c7-5745-4a8f-bc38-f6d395a25ce2.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by jessjwilliamson** [comment]
@cbjeukendrup

**Comment by cbjeukendrup** [comment]
It happens because the tempo text contains a newline, which will therefore also appear in the status bar. In the status bar, newlines and other whitespace should be replaced with just a space, which I has implemented in MuseScore 3, but has apparently not been ported. I'll take care of it.
