### ISSUE TITLE
[MU4 Issue] Crash when open score with opened parts

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9789]
https://user-images.githubusercontent.com/90187801/142462477-ea04f01a-a62c-4d8c-8965-1bcdb5826477.mp4

**Desktop:**
 Win10/Mac12/LinuxMint20

**Additional details**:
An old build of MU4 opens that score fine

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9859

**Comment by DmitryArefiev** [comment]
Tested on latest master build on Win10, Mac12, LinuxMint 20 - FIXED (NO CRASH)
