### ISSUE TITLE
[MU4 Issue] Crash when opening style preferences

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#9793]
**Describe the bug**

When trying to open Format > Style, MuseScore crashes due to a seg fault.

**To Reproduce**
1. Create new score
2. Click on Format > Style
3. Observe crash

**Expected behavior**

MuseScore should not crash.

**Desktop (please complete the following information):**
 - OS: macOS 11.6, x86

**Additional context**
Perhaps there was a fundamental change to MuseScore in the last month? I've been primarily working on a month-old branch for the last month. This occurred on the most recent version of Master.

**Comment by njvdberg** [comment]
Confirmed om Linux.
Issue seems to be caused by #9738.

**Comment by jessjwilliamson** [comment]
Accidentally made a duplicate PR of this just now. Confirmed for Windows
