### ISSUE TITLE
[MU4 Issue] Trying to open the Style dialog crashes on Windows

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9795]
**Describe the bug**
Attached video showing the crash:

https://user-images.githubusercontent.com/71656189/142630714-d30293f6-5ff0-43c6-b8d8-c3b8ef1b734f.mp4

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Jojo-Schmitz** [comment]
See #9793

**Comment by Jojo-Schmitz** [comment]
Yep, you've just been quicker to find that out ;-)
