### ISSUE TITLE
[MU4 Issue] Unable to rewrite (replace) file during Export after restarting MU and reopenning score

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9796]
https://user-images.githubusercontent.com/90187801/142632600-f6f3f8ac-b476-46ba-88ca-f770b8cb5fb8.mp4

**To Reproduce**
1. Create score
2. Save it
3. Export PDF
4. Export PDF again - MU is able to rewrite pdf file
5. Restart MU
6. Reopen the same score
7. Export PDF - **MU is unable to rewrite pdf file**

**Desktop:**
 - OS: Windows 10
 Was not able to reproduce on Mac and Linux

**Comment by wizofaus** [comment]
I certainly can't reproduce this and it seems like there might be some other application holding a lock on it.
Are you able to modify/overwrite it any other way? Anything suspicious in terms of what processes are running (multiple MuseScore instances perhaps?).
"An error occurred while writing the file" is shown if either file can't be opened for writing, or if there's some error during PdfWriter.write(), but there's really very few things that can trigger this and none of them are conditions I can see could be triggered here, so I'm pretty strongly suspecting it's the former - and it's not unlikely that some other application is somehow trying open the pdf file and locking it for writing.

**Comment by Tantacrul** [comment]
I've tried this on Windows 10 and I can't reproduce...

Dmitri, I'll close (since there has been a lot of work done on export since) but reopen if you think it's needed!

**Comment by DmitryArefiev** [comment]
> I've tried this on Windows 10 and I can't reproduce...
> 
> Dmitri, I'll close (since there has been a lot of work done on export since) but reopen if you think it's needed!

Yes, the same on my side in latest master (Win10) - CAN'T REPRODUCE NOW
