### ISSUE TITLE
[MU4 Issue] PNG File Export not perfect

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#9802]
**Describe the bug**
Whenever you export a score in png format, the image's edges are "bumpy". Also, the margins are quite small

**To Reproduce**
1. Export in png format in export dialog.
2. Look at the image's right side. 

**Expected behavior**
There shouldn't be these "bumps". Also, the margins should be larger.

**Screenshots**
![pngimage-1](https://user-images.githubusercontent.com/88136054/142720811-0f031198-cd9f-4e30-9c40-a0454ce8498a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I think the margins are the problems behind the bumps.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED  (should be in the next master)
