### ISSUE TITLE
[MU4 Issue] Crash when using text fields to adjust line properties

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9809]
**Describe the bug**
Attempting to adjust line properties via text fields in the **Properties** panel triggers a crash.
This seems to affect all lines (e.g. Cresc., Dim., 8va., etc.) that have editable text fields in the **Properties** panel.

**To Reproduce**
1. Enter a line object (e.g. a Cresc. line)
2. Select the **Properties** panel
3. Highlight the text in the any text field (e.g. the **Dash** field)
4. Replace the text with a different value
5. Hit enter

Crashes occur on hitting **Enter**

![crash-line-edits](https://user-images.githubusercontent.com/86290556/142811173-ff17dfac-ce82-4839-b452-ef5248c64111.gif)

**Expected behavior**
Crash should not occur.

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by igorkorsukov** [comment]
It looks like it has already been fixed, @DmitryArefiev  please check

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (will be in the next master)
