### ISSUE TITLE
[MU4 Issue] Right-click in master palette triggers redundant context menu

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9815]
**Describe the bug**
Right clicking any item in the master palette triggers a redundant, "floating" context menu that seems disconnected from the palette itself. Options in the context menu are all disabled.
This context menu remains on screen for some time, even after the master palette dialog has been closed. 

![master-pallete-strange-menu](https://user-images.githubusercontent.com/86290556/142858220-793494a9-8270-4d9c-8a3d-8f25a34bbf8c.gif)

**Expected behavior**
Nothing should be triggered when right-clicking on a master palette item (per MS3.6)

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by DmitryArefiev** [comment]
Tested #10297 on Win10, Mac12, LinuxMint 20.2 - FIXED
