### ISSUE TITLE
[MU4 Issue] Crash when dragging Note Input bar with overlapping another panel

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9816]
https://user-images.githubusercontent.com/90187801/142858969-cee7f712-92db-45b6-88a4-f598d75ba4a9.mp4

**Desktop**
Win10/Mac12/LinuxMint20

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
