### ISSUE TITLE
[MU4 Issue] Note Input bar does not take right position and view during docking process (Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9818]
https://user-images.githubusercontent.com/90187801/142863534-b4a4cd3e-6be5-42c0-b005-339ce4fe640f.mp4

**Expected behavior**
It should behave like on Mac or Linux (should take vertical position and be not empty)

**Desktop:**
 - OS: Windows only

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by DmitryArefiev** [comment]
Tested on Win10 - FIXED (should be in the next master)
