### ISSUE TITLE
[MU4 Issue] Panels have unnecessary title bar when undocked (Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9821]
https://user-images.githubusercontent.com/90187801/142865847-0b1ec041-5767-4c4c-8585-b8412ead7958.mp4

**Desktop:**
 - OS: Windows only (Win10)

**Additional context**

**Comment by RomanPudashkin** [comment]
I'm working on it

**Comment by DmitryArefiev** [comment]
Tested on Win10 - FIXED (should be in the next master)
