### ISSUE TITLE
[MU4 Issue] The plugins list from context menu exceeds height

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9825]
**Describe the bug**
I'm not sure who to assign but can anyone can help out with this problem?

Taking an example from this plugin patch by Melda, they have a lot of plugins (I believe 37 plugins) but it's not going to fit into one long context menu. On my screen, 32 are visible (of course there will be different results depending on your scale and screen resolution). 

How it is on my screen with 3840 x 2160 resolution with 200% scaling (only showing 32, exceeding above):
![image](https://user-images.githubusercontent.com/71656189/142905729-307eda7d-468b-4f27-b1e6-d8c78989d44e.png)

How it really is showing all 37 plugins (same resolution but 100% scaling):
![image](https://user-images.githubusercontent.com/71656189/142905898-d42d5393-1835-4e70-a9c0-78894a711def.png)
 
Would need to find a solution to shorten the list. Possibly something like this:

https://user-images.githubusercontent.com/71656189/142909842-ade6cbd6-44d0-4056-b4f7-4dc8eb998baa.mov

More chances of situations like this are when finding an instrument or FX in the Mixer with lots of options. This can apply as a general context menu behaviour rule throughout the app, it doesn't have to be specifically for the mixer.

If possible or another solution, please reach out so we can fix this :) Thanks!

**Desktop (please complete the following information):**
 - OS: Windows (and maybe Mac)

**Comment by jessjwilliamson** [comment]
I also noticed that the context menu plugin list on Mac is in a different order than to Windows. Not sure what particular order but both are definitely not alphabetical!

**Comment by jessjwilliamson** [comment]
@Eism This is happening again (Not sure on Windows) 

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/71656189/219620706-721a156b-cdca-475d-8b09-5e624eda93d2.png">

**Comment by DmitryArefiev** [comment]
@jessjwilliamson I can't reproduce it on my side (Win/Mac).. Maybe you have a 2nd monitor connected?

**Comment by jessjwilliamson** [comment]
@bkunda Can you test if this is happening to you please with your multiple monitors? :)

**Comment by jessjwilliamson** [comment]
> @jessjwilliamson I can't reproduce it on my side (Win/Mac).. Maybe you have a 2nd monitor connected?

yes that's correct! This is happening on multiple monitors

**Comment by JesseZ332623** [comment]
＜（＾－＾）＞

**Comment by DmitryArefiev** [comment]
Retested on Mac12.6 and 2monitors setup
