### ISSUE TITLE
[MU4 Issue] Mixer - Strange 'limiter' behaviour when an audio gets clipped

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9827]
**Describe the bug**
Sometimes we are mixing or using audio plugins, clipping happens and we reduce back to normal volume and it's fine.
With MS4, once an audio gets clipped (that means it exceeds 0dB) which creates very loud, unpleasant distortion, it is after that when back to normal the overall volume is completely reduced, unable to recover the initial volume before the clipping happens.

You see here the volume playing at a healthy level before I turn up the output knob (for demonstration purposes to clip the audio). After the audio is clipped, it suddenly goes very quiet, unable to recover normal volume after I turn the output knob back to normal again. I'm not sure if this method was intentional or not but the only way to recover from this is to close the app and re-open for the volumes to reset itself again.

https://user-images.githubusercontent.com/71656189/142919702-8b554de5-43d4-4961-aea9-78d95506f46a.mp4

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by cbjeukendrup** [comment]
@jessjwilliamson Is this still happening?

**Comment by jessjwilliamson** [comment]
> @jessjwilliamson Is this still happening?

Nope! This can be closed - FIXED. many thanks! :D (wow, opening this issue helps us realise how far we've come! well done!)
