### ISSUE TITLE
[MU4 Issue] Playback with Space doesn't start after opening a score (because score doesn't take focus)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9836]
Playback with Space doesn't start after opening a score (because score doesn't take focus). 
You need to click with mouse on empty space and then press Space to start Playback.

https://user-images.githubusercontent.com/90187801/143007360-e6590171-a0d9-4326-8bf4-37ab448b28cc.mp4

**Expected behavior**
After opening score, playback with Space should start without any additional actions with score

**Desktop:**
Win10/Mac12/LinuxMint20

**Comment by jessjwilliamson** [comment]
Hi! Can I add a comment about the spacebar playback:
When you have a VST window open and in front of you, you should be able to press space bar to press play as well (like other DAWs can do!)

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
