### ISSUE TITLE
[MU4 Issue] Navigation with arrows doesn't work together with mouse clicks (in new style windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9839]
**To Reproduce**
**Case 1**
1. Open **Instruments** window (or **Preferences**)
2. Click on any instrument
3. Start to navigate with ↑↓ arrows - it **doesn't work** (you need to start navigation with tab and then arrows start to work)

https://user-images.githubusercontent.com/90187801/143014038-832871b6-54b1-488a-92b9-ad9a0cee3788.mp4

**Case 2**
1. Open **Instruments** window
2. Click on search field
3. Type something (e.g. flute)
4. Start to navigate through the list with ↑↓ arrows - it **doesn't work** (you need to start navigation with tab and then arrows start to work)

https://user-images.githubusercontent.com/90187801/158849269-4ad8b9d3-a6b9-4513-bcc3-d78d08c3fd50.mp4

**Desktop:**
Win10/Mac12/LinuxMint20

**Additional context**
Doesn't occur in **MU3**
In old style windows (Master Palette, Style) it works fine

**Comment by Eism** [comment]
also see #10919

**Comment by DmitryArefiev** [comment]
Fixed in #11233

**Comment by DmitryArefiev** [comment]
> Expected behavior
> The selected input would be Composer, Instead, it selects the "key signature"

@MajesticString Regarding the expected result, MU4 uses **arrows** to navigate within a group and **Tab** to switch between item groups
