### ISSUE TITLE
[MU4 Issue] "Gap above/below" vertical frames displays incorrect values

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9840]
**Describe the bug**
The **Gap above** and **Gap below** text edit fields within the **Vertical frames** Properties panel are showing incorrect values, causing unexpected layout behaviour when altered. 

https://user-images.githubusercontent.com/86290556/143016487-53a84a0f-9f72-4921-8710-e45e924f0ff9.mp4

These fields are also occasionally inclined to show an unnecessary number of decimal places: 
<img width="300" alt="Screenshot 2021-11-23 at 10 28 31 pm" src="https://user-images.githubusercontent.com/86290556/143016506-1bf0f1a7-32e1-4353-b525-b3fc4dd24875.png">

**Expected behavior**
In MS3.6, vertical frames appear to have a default padding of 7sp, although the **Gap above** doesn't seem to have any effect on the topmost vertical frame of a score (perhaps a bug in MS3.6?). At any rate, expected behaviour should include:

- 7sp default "Gap above/below" for vertical frames
- Incremental adjustments to the text edit field that map correctly to the actual repositioning of the corresponding frame in the score
- No more than the usual 2 decimal places in the text edit fields 

**Desktop (please complete the following information):**
 - Windows 11
 - MacOS 11.6

**Additional context**
Does not seem to affect horizontal frames

**Comment by MarcSabatella** [comment]
FWIW, I don't think of the 3.6 behavior as a bug, just maybe a poorly-presented design.  But it works "as expected" when using the gap field in the intended way.  The main point of the gap fields is to allow for additional space between a frame and any content above/below that frame.  For instance, consider a case where a new movement starts mid-way down the page, and you have a frame for its title.  You might well have a larger top gap specified to create some extra white space.  But then, if the layout changes such that the frame is now at the top of the next page, there normally wouldn't be a need for that extra space.  So having the gap only apply "where needed" is the intent here.  At least that's how I always saw it, and it does work well for this use case.

But there are probably better ways this could be handled, like separate controls for space between frame and music vs frame and margin vs frame & another frame.  Also widow/orphan control - a way to make the frame "stick" to the next system, so you don't end up with a movement title on the bottom of one page but the music starting on the next.

Really, if we think of a frame as being akin to a heading in a word processor and think of the kind of control desired and often provided there, that's a decent starting place.
