### ISSUE TITLE
[MU4 Task] [TECH_DEBTS] WinCore audio driver recovering

### ISSUE THREAD

**Issue by vpereverzev** [musescore/MuseScore#9842]
**Task description**
Implement reinitialization of audio-device once it being unavailable using this article from official site - https://docs.microsoft.com/en-us/windows/win32/coreaudio/recovering-from-an-invalid-device-error

**Comment by cbjeukendrup** [comment]
Closing this, since we have switched from CoreAudio to WASAPI, and we are not planning to move back, and with WASAPI this works well. (Right?)
