### ISSUE TITLE
[MU4 Issue] When opening from a MIDI file, MS4 should encourage to save a mscz file

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9845]
**Describe the bug**
A UX flow I think is flawed and should be considered how to go around doing this.

**To Reproduce**
1. Open a .mid (MIDI) file
2. Click on File > Save
3. No dialog shows to save as new file in mscz format. 
4. Exit project
5. Dialog shows "Do you want to save?" Neither Yes or No will save as a mscz file.
6. The project does not show up in the Home tab.

**Expected behavior**
When opening from a non mscz file like a MIDI file, MS4 should encourage user to save as a Musescore project file (mscz). 
I opened a MIDI file myself, made changes of instruments, added title etc, thought I saved it but turned out it never saved as an mscz file.

https://user-images.githubusercontent.com/71656189/143040254-8865b4a5-89fa-45ba-85a9-cf5521065f51.mp4

**Comment by DmitryArefiev** [comment]
Tested in latest master build (Win10, Mac12, LinuxMint 20.2) - FIXED

Closing
