### ISSUE TITLE
[MU4 Issue] Tuplet button should be disabled until a note or rest is being selected (in selection mode)

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9847]
**Describe the bug**
UX rule here:
- The button is disabled when not being used. This includes not being able to open the context menu
- It only becomes active when a note or a rest is being selected on the score.

**Expected behavior**
![image](https://user-images.githubusercontent.com/71656189/143048683-82048221-9849-439a-8df4-fffcc25bdaad.png)
![image](https://user-images.githubusercontent.com/71656189/143048709-c3c60cf8-f1c3-4396-8566-3d229c1ebdca.png)

**Comment by Tantacrul** [comment]
@DmitryArefiev: do you want to talk this through further? I'm aware that there's an issue with tuplets not working on rests while in Note Input mode, correct?

**Comment by DmitryArefiev** [comment]
@Tantacrul Yeah.. I think the description should be updated regarding how it should work in Note Input mode. 
In PR build, Tuplet button becomes greyed out when just enter Note Input mode (hit N)

@jessjwilliamson The new rule should applied only selection mode, right? So, tuplet button should be always on in Note Input mode, right?

**Comment by Tantacrul** [comment]
Yes. It only refers to selection mode (I discussed with Jess)

**Comment by DmitryArefiev** [comment]
Good! Thanks for clarification!

@Eism Could you make a new build given this condition please?

Thanks!

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - PASS
