### ISSUE TITLE
[MU4 Issue] 'Reset shapes and positions' unjoins beams that have been connected over rests

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#9852]
**Describe the bug**
'Reset shapes and positions', when applied to beams that have been explicitly connected over rests, unjoins those beams.

This could be argued as desirable behaviour, but really is the province of the 'Reset beams' option, and in any case is inconsistent as it doesn't undo other manual beam alterations (see the second beat in the example below).

**Expected behaviour**
'Reset shapes and positions' should only undo any manual adjustments made to the vertical position of the beam, and not any adjustments made to the actual formation/splitting/joining of the beam (which instead are undone with 'Reset beams').

**Before**
![image](https://user-images.githubusercontent.com/20604032/143212716-6df3f5be-d05b-486e-8d2f-daafbd32aebe.png)

**After**
![image](https://user-images.githubusercontent.com/20604032/143212782-74cbcc4b-36c5-4478-bc39-0b39118d90d4.png)

(Note, the current MU4 behaviour is the same as the MU3 behaviour.)

**Comment by Jojo-Schmitz** [comment]
Also fixes https://musescore.org/en/node/313821
