### ISSUE TITLE
[MU4 Issue] Unable to edit existing instrument change and invoke Change Instrument dialog (from right click menu)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9853]
Unable to edit existing instrument change and invoke Change Instrument dialog from **right click menu**

See video below

https://user-images.githubusercontent.com/90187801/143218736-d3eb5e23-5968-497e-8dbe-b95e8ecfc211.mp4

**Workaround:**
Delete instrument change and add it again

**Desktop:**
Win10/Mac12/LinuxMint20

**Additional context**
Doesn't occur in **MU3**

**Comment by Howard-C** [comment]
Do we need to make an additional Change Instrument section in Properties just for this one button? I can try to do it if it's needed.

**Comment by DmitryArefiev** [comment]
Fixed in #10844
