### ISSUE TITLE
[MU4 Issue] Crash on "Undo" command after deleting instrument from Instruments dialog

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9856]
**Describe the bug**
**Cmd/Ctrl+Z** triggers a crash in the following flow:

1. In the New Score dialog, set up a score with instruments of your choice
2. Click **Done**
3. Type **I** to open the **Instruments** dialog 
4. Delete an instrument
5. Click **OK** to close the **Instruments** dialog
6. Type **Cmd/Ctrl+Z**
7. MuseScore crashes

**Expected behavior**
Deleted instrument should be reinstated. MuseScore should not crash

![crash-deleting-instrument](https://user-images.githubusercontent.com/86290556/143240661-3842cc51-fc86-4179-8a6b-7e8959e25314.gif)

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Additional context**
This issue was uncovered while reproducing #9350.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
