### ISSUE TITLE
[MU4 Issue] Staff instrument name alignment options produce incorrect results

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9857]
**Describe the bug**
Options for text alignment of instrument staff names **Instrument Name (Long)** and **Instrument Name (Short)** produce incorrect results

**To Reproduce**
1. Go to **Format --> Styles --> Text Styles**
2. Select "Instrument Name (Long)"
3. Toggle **Align text left/right/centre**

This is the result:
![instrument-name-alignment](https://user-images.githubusercontent.com/86290556/143245249-110b9894-21cb-4aac-8eb5-4209a47fcf74.gif)

Note: the same effect results with these options in the **Properties** panel:
<img width="581" alt="Screenshot 2021-11-25 at 12 17 15 am" src="https://user-images.githubusercontent.com/86290556/143245602-e44cc165-2766-4d15-a4da-77acafa283d1.png">

**Expected behavior**
These settings should work as per MS3.6. Text alignment in the score should correspond with the text alignment setting selected by the user in **Text Styles** and **Properties** panel

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10165
