### ISSUE TITLE
[MU4 Issue] When enter Tuplet mode it should select the next rest 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9861]
**To Reproduce**
1. Input note from keyboard
2. To enter Triplet hit Ctr/Cmd+3 - the next rest is not selected
3. Input some notes to fill Triple group - **it adds quarters instead of triplet eights** - see video to compare with MU3 behaviour

https://user-images.githubusercontent.com/90187801/143272119-bd453f32-2bc3-4585-81b9-204e52107c6f.mp4

**Desktop:**
Win10/Mac12/LinuxMint20

**Comment by HemantAntony** [comment]
This issue appears to be fixed in the latest master

**Comment by DmitryArefiev** [comment]
@HemantAntony Thanks for checking!

**Comment by DmitryArefiev** [comment]
Tested in latest master build on Win10, Mac12, LinuxMint 20.2 - **FIXED**

Closing
