### ISSUE TITLE
[MU4 Issue] Crash when pasting ambitus (to another stave)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9866]
https://user-images.githubusercontent.com/90187801/143425855-0753e3d4-7da8-451b-8f3e-e12ac54a1dc7.mp4

**Desktop:**
Win10/Mac12/LinuxMint20

**Additional context**
Doesn't occur in **MU3**

**Comment by Jojo-Schmitz** [comment]
Maybe related to https://musescore.org/en/node/309367 ?

**Comment by DmitryArefiev** [comment]
> Maybe related to https://musescore.org/en/node/309367 ?

@Jojo-Schmitz I can't reproduce https://musescore.org/en/node/309367  Can you try it on your side in MU4 please?
(maybe the steps in 309367 description are not clear for me..)

**Comment by Jojo-Schmitz** [comment]
I can't reproduce it in 3.6.2, so I assume it got fixed quite a while ago (some time after 3.4)

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9898

**Comment by DmitryArefiev** [comment]
Tested on latest master build on Win10, Mac12, LinuxMint 20 - FIXED
