### ISSUE TITLE
[MU4 Issue] Various panels become disconnected when moving project window

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9867]
**Describe the bug**
Various popups get disconnected from the main project window when the latter is moved. 

Example: If the **Appearance** panel is open, and the project window is then moved, the **Appearance** panel does not move with the project window.

![rogue-appearance-popup](https://user-images.githubusercontent.com/86290556/143433996-1f5d5e71-0e41-40e0-9e44-22e110ae5110.gif)

This same behaviour affects other popups, including staff settings popups in the **Instruments** panel:
![popup-doesn't-move-with-window](https://user-images.githubusercontent.com/86290556/143860941-74618014-620f-4d60-bb54-68fb18a9c92b.gif)

**Expected behavior**
All popups should move with the main project window

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Additional context**
The colour discrepancy in the popup top border (triangle indicator) occurred after switching from dark to light mode. I'll raise this as a separate issue.

**Comment by Eism** [comment]
@bkunda could it be better to close the popup?

In our project, popups are closed by clicking on the area outside the popup and the button with which the popup was shown.
The fact that we do not close the popup by clicking on the title bar is a bug that needs to be solved.

**Comment by bkunda** [comment]
> @bkunda could it be better to close the popup?
> 
> In our project, popups are closed by clicking on the area outside the popup and the button with which the popup was shown. The fact that we do not close the popup by clicking on the title bar is a bug that needs to be solved.

If clicking on the title bar **should** close a popup (by design), then yes, I agree it would make sense for popups to close when the project window is moved. 

I can't put my hands on the original design spec at the moment, but I know it was @Tantacrul's design. That being said, I'm not actually opposed to the idea of the popups remaining open when the project window is moved, particularly as some of the more involved ones contain a number of settings that the user might want to see open after they've temporarily repositioned their project window (i.e. it might be _slightly_ annoying to have to reopen the popup again). This is why I made my recommendation above. 

I don't have a strong opinion about this though, so it might be best just to reference the original document (or perhaps @Tantacrul can weigh in with his opinion).

**Comment by Tantacrul** [comment]
Oh, I think the simple solution it to close the popup if the user moves the window. I would think that is expected.

Thanks!

**Comment by bkunda** [comment]
> Oh, I think the simple solution it to close the popup if the user moves the window. I would think that is expected.
> 
> Thanks!

I'm happy with that!

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
