### ISSUE TITLE
[MU4 Task] Wider text edit field in Properties > Appearance

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9870]
**Task description**
To make space for longer text labels, we would like to increase the current width of the text field "Minimum distance" in **Properties > Appearance** from this:
<img width="200" alt="Screenshot 2021-11-25 at 10 47 58 pm" src="https://user-images.githubusercontent.com/86290556/143436603-289c2152-fcd3-4012-95a8-a455936f55dc.png">

...to this:
<img width="292" alt="APPEARANCE_POPUP_SNAP_OFF" src="https://user-images.githubusercontent.com/86290556/143436649-4d2f5600-b723-4eb1-a90e-650111d94ef2.png">

Width of new text field will be 232px, to vertically align with text fields above and below while retaining a 12px margin on the right. 

Click here to see the design file: https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/Musescore-Notation-App-MASTER?node-id=20380%3A651636

Thanks!

**Comment by njvdberg** [comment]
See #9909
