### ISSUE TITLE
[MU4 Task] Wider text edit field in Properties > Hairpin

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9871]
**Task description**
This task contains two components:

1. To make space for longer text labels, we would like to increase the current width of this text field: 
<img width="299" alt="Screenshot 2021-11-25 at 10 54 58 pm" src="https://user-images.githubusercontent.com/86290556/143437443-3321ee1f-e366-4f74-aaeb-3f3d7ec1f270.png"> 

to this:
<img width="322" alt="HAIRPIN_POPUP_CUSTOM" src="https://user-images.githubusercontent.com/86290556/143437506-ac13a474-fc04-46e5-bfbf-c976ff1dd676.png">

Width of the new text field will be 256px with 12px left and right margins.

2. Change current label from: **Height (continuing to a new system)** to **Height (new system)** 

Click here to see the design file: https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/Musescore-Notation-App-MASTER?node-id=20380%3A653095

Thanks!

**Comment by njvdberg** [comment]
See #9909
