### ISSUE TITLE
[MU4 Issue] Placement of bar repeat symbols is imperfect

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#9877]
Either these symbols are a positioned tiny bit too low, or the scale of the symbol is a tiny bit too small. The dots should appear exactly in the middle of the spaces. Also the 2-bar/4-bar repeat symbols should be exactly centered on the middle of the barline (they are a bit too far to the right):

![image](https://user-images.githubusercontent.com/20604032/143466708-756c4579-e135-4fe2-9546-cf0e2f462c9d.png)

Dorico comparison (here the vertical placement is ideal, though the horizontal is not):

![image](https://user-images.githubusercontent.com/20604032/143466964-47c8394f-1aa0-4660-a201-69c5e9d16583.png)

(Font in these examples is Leland)

**Comment by cbjeukendrup** [comment]
Working on it!

**Comment by cbjeukendrup** [comment]
@oktophonie How should the bar repeat sign be positioned on staves with an even number of lines (for example, TAB staves)? Dorico just places it in the middle of the staff, which results in the dots colliding with the staff lines. Shouldn't the symbol be positioned on the line just above the middle? (So, for a 6 line staff, the third line from the top?)

**Comment by oktophonie** [comment]
Not sure there's a standard for this, to be honest - but I'd prefer to do it as you suggest, i.e. where there's an even number of lines, centre the symbols on the line just above the middle.
