### ISSUE TITLE
[MU4 Issue] VST - Doesn't save preset settings

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9881]
**Describe the bug**
This is from BBC Orchestra VSTi

When I set my Violins, Viola, Celli etc to each BBC Orchestra plugin, close project then reopen, all BBCO plugins switch back to the default setting (which is Violin 1)

**To Reproduce**
1. Have a plugin set to Celli or something else other than default Violin from BBC Orchestra
2. Save project 
3. Close MS4
4. Re-open MS4
5. Open the same plugin
6. See it has swapped itself back to the default setting (Violin 1)

**Expected behavior**
When saved and closed project, presets and settings must be saved.

https://user-images.githubusercontent.com/71656189/143494096-c39f5594-35eb-446d-a411-215c6c864a57.mp4

**Comment by DmitryArefiev** [comment]
@vpereverzev Tested on Win10 and Kontakt Player. The issue still occurs: after reopening MU, the instrument added previously is missing.
And the same thing with Audio FX settings.

@boryskuzmenko Confirms that bug on his Mac as well.

**Comment by jessjwilliamson** [comment]
> @vpereverzev Tested on Win10 and Kontakt Player. The issue still occurs: after reopening MU, the instrument added previously is missing. And the same thing with Audio FX settings.
> 
> @boryskuzmenko Confirms that bug on his Mac as well.

Yes this applies to all VST in general, not just the BBC Orchestra I mentioned above

**Comment by Tantacrul** [comment]
I've moved all this info into one bug and marked it a P0 since this is a crucial a problem with VST to fix.

**Comment by Tantacrul** [comment]
See #11567 - where I've added extra info.
