### ISSUE TITLE
[MU4 Issue] VST - Crashes when swapping Audio FX

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9884]
**Describe the bug**
From the 'Kilohearts - Toolbox Free' and 'Blue Cat Freeware Pack'
This happens often while the score is playing - swapping one plugin to another, app crashes.

Kilohearts:

https://user-images.githubusercontent.com/71656189/143498391-2f1604ac-32f5-47d1-aeab-350a433aca13.mp4

Blue Cat:

https://user-images.githubusercontent.com/71656189/143498335-da272194-fd2d-4d25-a468-46f6ba86cd24.mp4

Blue Cat ALL mono versions of plugins strangely just refuses to open or work:

https://user-images.githubusercontent.com/71656189/143498565-71663347-2e4e-4eb9-8793-fc6c38ebbb00.mp4

**Comment by mattblo** [comment]
In the current NightlyBuilds it is also enough to deactivate a plugin and activate it again (at the latest after three times MU4 always crashed for me)

**Comment by jessjwilliamson** [comment]
Solved :)
