### ISSUE TITLE
[MU4 Issue] VST - UI glitch after 2nd time opening

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9885]
**Describe the bug**
This is from the Melda Production (MFreeFXBundle) VST FX pack
This may be happening to all 37 of their plugins (unable to test all due to context menu issue here https://github.com/musescore/MuseScore/issues/9825)
2nd time opening these plugins, there is a black square and no UI visible. This is still happening after multiple attempts trying to open it.

https://user-images.githubusercontent.com/71656189/143497872-bd36a9fb-a922-4d57-bd3a-7a7782ebef09.mp4

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by mattblo** [comment]
For me, under the latest Windows 11 version, there is no UI for the MeldaProduction plugins even when I first open them.

**Comment by jessjwilliamson** [comment]
> For me, under the latest Windows 11 version, there is no UI for the MeldaProduction plugins even when I first open them.

This was recorded also on Windows 11

**Comment by mattblo** [comment]
> This was recorded also on Windows 11

I'm surprised that you can see anything at all. I have just completely rebuilt the laptop with the latest Windows 11 version that can be downloaded from Microsoft. I also get no UI to see the first time I start the plugins.

**Comment by mattblo** [comment]
For me, it's something like this:
On the Master Channel I always get this empty window! On the other channels, however, Musescore sometimes crashes or it takes a long time and then the plugin appears. This repeats sometimes when I close the plugin then and open again on the instrument channel. At some point then appears like in your case, the empty window with the black small bar..

https://user-images.githubusercontent.com/63284090/143584929-72758c13-a0d9-4386-a70f-126bd3dbe35c.mp4

.

**Comment by jessjwilliamson** [comment]
> For me, it's something like this: On the Master Channel I always get this empty window! On the other channels, however, Musescore sometimes crashes or it takes a long time and then the plugin appears. This repeats sometimes when I close the plugin then and open again on the instrument channel. At some point then appears like in your case, the empty window with the black small bar..
> 
>  Musescore.-.MeldaProduction.VST.Plugins_Trim.mp4 
> .

I just downloaded lastest master as of today (26/11/21) and I got the same problem as you from 2nd FX, very bad crash. This is after a merge has happened of trying to make VST dialogs to 'stay in front of the app' but it has resulted into some complications. You can follow this issue here https://github.com/musescore/MuseScore/pull/9830#issuecomment-979975330

**Comment by DmitryArefiev** [comment]
Hello @jessjwilliamson , can check this in build from #10581 on your side (Windows) please? 

Thank you!

**Comment by DmitryArefiev** [comment]
Similar to #10969

**Comment by DmitryArefiev** [comment]
Fixed regarding https://github.com/musescore/MuseScore/issues/10969#issuecomment-1285050209

(I was not able to reproduce it initially so can't check properly)
