### ISSUE TITLE
[MU4 Issue] Two-note tremolo makes stems very long

### ISSUE THREAD

**Issue by Howard-C** [musescore/MuseScore#9889]
Should be caused by something very recently changed, since it only happens after I pulled the latest few commits. Perhaps #9792?

![image](https://user-images.githubusercontent.com/46259489/143536700-81e674f4-5a2c-4e53-b516-c94ee574af56.png)

**Comment by oktophonie** [comment]
Caused by #9792 - will be addressed next week :)
