### ISSUE TITLE
[MU4 Issue] Crash opening styles dialog

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9890]
**Describe the bug**
Opening styles dialog triggers crash in MacOS and Windows:

![crash-opening-styles](https://user-images.githubusercontent.com/86290556/143550877-65d2c314-302c-421e-9fe1-9c58310ea5f2.gif)

**Expected behavior**
MS should not crash

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9899

**Comment by DmitryArefiev** [comment]
Tested on latest master build on Win10, Mac12, LinuxMint 20 - FIXED
