### ISSUE TITLE
[MU4 Issue] Line object end points don't jump to next system when dragged

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9891]
**Describe the bug**
Dragging a line object across multiple systems results in the line object end point remaining on the first system (i.e. it doesn't jump down to the next system):

Video shows **expected behaviour** (from MS3.6) and current behaviour (MS4):
![line-drag-doesn't-follow-end-point](https://user-images.githubusercontent.com/86290556/143559181-7f3a45e6-cf1b-4e5d-a7e3-c92d65e5d019.gif)

This appears to affect all line objects in the **Palettes**, with the exception of slurs, which aren't working as expected anyway (separate issue).

**Expected behaviour**
Line object end point should follow mouse pointer while remaining "snapped" to nearest note.

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
