### ISSUE TITLE
[MU4 Task] New beam group setting for palettes and properties

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9892]
**Task description**
We would like to implement one additional beam group setting: **beam end**, which will cause the selected note to form the last note in a beamed group of notes. 

Here is the design spec: 
[UX-Spec_end-beam-group-setting_V.1.pdf](https://github.com/musescore/MuseScore/files/7608693/UX-Spec_end-beam-group-setting_V.1.pdf)

And the link to the design file in Figma: https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/Musescore-Notation-App-MASTER?node-id=20380%3A654200

Please note: we will be using text icons for the palette and properties buttons (from musescoreicon), not .svg files.

Thanks!

**Comment by Pashkuli** [comment]
nice, I guess

**Comment by abdulazizali77** [comment]
hi @bkunda id like to take a shot at this, had a cursory glance at the code, and im guessing i have to do these
-add new enums eg `ActionIconType BEAM_END`, `BeamMode END`
-add the new icon in `iconcodes.h` as 0xF33C and init in `palettecreator.cpp` `BeamTypeSelector.qml`
-handle/modify logic in `layoutBeams.cpp` `createBeams` 
-register action in `notationactioncontroller.cpp`
-handle action interactions? `actionIconTypeForBeamMode` 
probably some other engraving changes in `beam.cpp` and `layoutbeam.cpp` i havent figured out yet

Unsure
-8th, 32nd, 64th etc notes, i only see one end beam icon for 16th (0F33C) in the musescore ttf. Also the available beam starts differentiate between `Begin` (16th), `Begin 32` and `Begin 64`, whereas theres no middle 32,64, nor are there 128, 256(!) etc notes. I dont have any immediate thoughts on how to solve this UI wise.
-unit tests or e2e tests

**Comment by cbjeukendrup** [comment]
@abdulazizali77 Looks like you've done a very good job researching!

About your doubts,  would suggest the following: 
- The icon shows a 16th note, but I think this should apply for all note values and all beam levels. So, pressing that button will let all beams end at the selected note. I absolutely agree that the other settings are very inconsistent reg. note values; I think it would be a separate task to clean that up.
- Our unit tests are maybe not in a great state at the moment. As far as I can see, the only tests about beams we have currently are about read/write round tripping, and they don't handle beam group settings at all. If you would like to add a test for that, that would be great, but if you don't, it's also okay.

**Comment by abdulazizali77** [comment]
thanks @cbjeukendrup , should i pick this up or shall i leave it to @vpereverzev ?

looking at the alpha release board i see more engraving related bugs eg force horizontal, and i did find other bugs which im not sure where the tracker is ie gripping the beam in MU4 but it wouldnt move as compared to MU3, im wondering if someone(s) is(are) working on a larger overarching redesign of the notes placement/layout? and if so i worry whatever changes i make may contradict those persons re-design decisions

**Comment by cbjeukendrup** [comment]
It would be great if you'd like to work on this! (Since this is a community issue and not listed for any sprint, I don't think anyone from the in-house team is working on it.)

Indeed, @Nick-Mazuk is in the process of refactoring the beaming code. But since you would work mainly with `LayoutBeams::createBeams`, which seems not _very_ closely related with the work Nick is doing, I wouldn't really expect many conflicts (Nick, what do you think?)

**Comment by bkunda** [comment]
Hi @abdulazizali77, thanks so much for taking this on! To confirm what @cbjeukendrup said (he is correct), the 16th-note `begin` (and the new end beam icon), like the 8th note `none`, will apply to all note values and beam levels. 
I'm also alerting @asattely and @oktophonie; if you have any questions about beaming code, then they may also be of assistance. 
Many thanks!

**Comment by abdulazizali77** [comment]
thanks @cbjeukendrup @bkunda , ill get cracking on this then
