### ISSUE TITLE
[MU4 Issue] MU doesn't show asterisk on score title tab after making changes

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9896]
**Now:**

![Now](https://user-images.githubusercontent.com/90187801/143593356-7e0d25dc-5899-4c20-a182-6e12d1e4ce3d.gif)

**Before:**

![Before](https://user-images.githubusercontent.com/90187801/143593370-2270eec9-7f8a-4331-b36e-bd79b4db0ab8.gif)

**Desktop:**
Win/Mac/LinuxMint

**Additional context**
Introduced recently.
MU doesn't show asterisk but knows that score is dirty and propose to save score after making changes

**Comment by jessjwilliamson** [comment]
I also noticed this too but wasn't sure :)

**Comment by Tantacrul** [comment]
Nice spot! I completely forgot about this.
