### ISSUE TITLE
[MU4 Issue] [Inspector] Changing stem direction for note groups in Properties is broken

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9906]
https://user-images.githubusercontent.com/90187801/143785470-a104edb1-6361-46d4-a4a7-a8a453940ef4.mp4

**Desktop:**
Win/Mac/LinuxMint

**Additional context**
Was broken recently

**Comment by Jojo-Schmitz** [comment]
Maybe #9792 or #9800 ?

**Comment by Nick-Mazuk** [comment]
I know why this is happening and can fix it.

**Comment by bkunda** [comment]
This is also affecting single notes in multiple parts:

![stem direction](https://user-images.githubusercontent.com/86290556/145952345-e583a1d7-a375-4718-95a0-4fa840eb6ce9.gif)

Key command `X` is also not functioning here.

**Comment by DmitryArefiev** [comment]
Tested #10290 on Win10, Mac12, LinuxMint 20.2 - FIXED
