### ISSUE TITLE
[MU4 Issue] Crash relating to unpitched percussion instruments

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9907]
**Describe the bug**
MuseScore crashes in either of the following situations:
1. Create new score containing only an unpitched percussion instrument (crash occurs when clicking "Done" in new score wizard)
2. In a score containing unpitched percussion instruments and any other instrument, crash occurs when triggering note entry mode for the unpitched percussion instrument

Demo vide: https://www.dropbox.com/s/1rsuqdccnu3h3dd/crash-unpitched-perc-instruments.mp4?dl=0

**Expected behavior**
MuseScore should not crash
Activating note entry mode for an unpitched percussion instrument should trigger percussion panel

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9917
