### ISSUE TITLE
[MU4 Issue] Clicking Cancel in Save Dialog should not close project

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#9908]
**Describe the bug**
When you close the main project (I did it using the shortcut), it bring about a dialog to Don't Save, Cancel and Save. If you were to click Save and move on, another dialog appears. When you click on cancel, it closes the project.

**To Reproduce**
1. Close the main project
2. You will get a dialog asking you to do one of the following: Don't Save, Cancel or Save
3. Click on Save
4. Then in the succeeding dialog, click cancel
5. It closes the project

**Expected behavior**
Clicking cancel should not close the project. It should bring it back similar to how clicking cancel in the first dialog is.

**Screenshots**
![image](https://user-images.githubusercontent.com/88136054/143822994-94f62ec8-70d4-419e-a5cb-741d57757172.png)
![image](https://user-images.githubusercontent.com/88136054/143823074-3fbb2a00-6186-4522-b980-bb0bc4918076.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by HemantAntony** [comment]
I found the problem. I am currently working on the implementation

**Comment by njvdberg** [comment]
This PR seems to introduce another issue, see #9942.

**Comment by DmitryArefiev** [comment]
Tested #9908 on latest master build (Win10, Mac12, LinuxMint 20.2) - FIXED
