### ISSUE TITLE
[MU4 Issue] Instrument panel popups don't close correctly on Undo key command in MacOS

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9911]
**Describe the bug**
The **Undo** key command in MacOS fails to correctly close popups in the **Instruments** panel.

- Instrument settings popup flashes briefly before disappearing
- Staff settings popup changes position and does not close

![instruments-panel-popup-behaviour-undo-command](https://user-images.githubusercontent.com/86290556/143846981-9319b2c6-007a-4325-a628-7020606df280.gif)

**Expected behavior**
Undo key command should both undo last edit in score while also closing any popups in the **Instruments** panel.

**Desktop (please complete the following information):**
 - MacOS 11.6
 (Not reproducible in Windows)

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
