### ISSUE TITLE
[MU4 Issue] Score position changes when interacting with empty tablature staff

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9912]
**Describe the bug**
Selecting an empty bar on a tablature staff, as well as entering note entry mode on the selected staff, changes the position of the score. 

![score-position-changes-tablature](https://user-images.githubusercontent.com/86290556/143854485-b04d5574-5212-4baf-bb27-6e0d277104eb.gif)

This is pretty crucial as it is currently almost impossible to enter notation into tablature staves with the current behaviour. 

**Expected behavior**
Score should not change position when user clicks on a tablature staff. 

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1) 
 - Windows 11

**Additional context**
May relate to #9775

**Comment by igorkorsukov** [comment]
It makes sense to fix it after solving this issues:  https://github.com/musescore/MuseScore/issues/9812

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
