### ISSUE TITLE
[MU4 Issue] Key commands for tablature notation not correctly implemented

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9914]
**Describe the bug**
A few critical key commands for tablature notation have not yet been ported correctly from MS3.6. These include: 

- Up/Down arrow keys: move up/down between staff lines in note entry mode
- Number row keys (1, 2, 3...): enter pitch into tablature staff using selected rhythmic duration
- Shift+1, Shift+2, Shift+3...: change rhythmic duration 

https://user-images.githubusercontent.com/86290556/143855336-374f341a-b0b0-4753-868d-8c15cf90c742.mp4

This is a fairly critical difference between note entry on a tablature staff and note entry on a standard staff. Without these key commands, note entry in tablature is fairly difficult. 

**Expected behavior**
Key commands for tablature note entry should function as per MS3.6

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1) 
 - Windows 11

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/9986

**Comment by DmitryArefiev** [comment]
@igorkorsukov Tested on Win/Mac. 

Main key commands are implemented now, but also there are some issues.

- Number row keys (1, 2, 3...): enter pitch into tablature staff using selected rhythmic duration - WORKS FINE
- Shift+1, Shift+2, Shift+3...: change rhythmic duration - WORKS FINE
- Up/Down arrow keys: move up/down between staff lines in note entry mode - **there is an issue here**: works through one when moving down/up across lines - video below

 **other issue**: clicking notes on Note Input Bar doesn't change duration (MU3 does it) - video below
 **other issue**: beams and stems have strange position in some cases - video below


https://user-images.githubusercontent.com/90187801/144908652-e4ef1f44-ded4-41a6-98f7-482a6130289d.mp4

"other" issues can be logged separately of course
