### ISSUE TITLE
[MU4 Issue] Title bar window response with text of project name

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#9918]
**Describe the bug**
In our current Windows build, the text of the project name on the title bar can overlap the menus on the left side if it is very long, like this:
![image](https://user-images.githubusercontent.com/71656189/143869885-622a62f8-1496-48b9-9022-8480b37e818d.png)

**Expected behavior**
The project name will still remain in the middle by default, but a way to get around it is when the Window becomes narrower and loses space between the project name and the menus on the left, the left side of the project name stops next to 'Diagnostic'. After that when becoming even more narrow, '...' will appear next to the minimize button (this would happen in extremely long titles).

![image](https://user-images.githubusercontent.com/71656189/143870958-768b29f4-3a05-46b9-8999-4e0e26278dcf.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by cbjeukendrup** [comment]
Replaces #9590

**Comment by wizofaus** [comment]
Even just having the piece title shown in the same font and the same horizontal location as the other menus is potentially confusing, as an obvious example if I happened to be working on an arrangement of a particular well known Beatles Song my title bar would look like...

![image](https://user-images.githubusercontent.com/5364225/144724311-d8c5a8d7-e907-4dab-856d-6a7bf8b225ad.png)

Compare this to, say, Visual Studio which shows the current solution name as follows:

![image](https://user-images.githubusercontent.com/5364225/144724334-d99e0bd5-bba1-4f1e-a6ef-f0f02a7ac3dd.png)

(To be honest, even that's not super obvious, but it's definitely an improvement).
