### ISSUE TITLE
[MU4 Issue] Mouse cursor should not change when hover over boundaries that can't be resized

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9919]
![01](https://user-images.githubusercontent.com/90187801/143875411-67e133de-6da4-4a80-8f57-2c26921f33c5.PNG)

https://user-images.githubusercontent.com/90187801/143875079-33063417-4059-4ead-9186-475983d88780.mp4

**Desktop:**
Win/Mac/LinuxMint

**Comment by Tantacrul** [comment]
I've made this a P2 because users of MS3 will be confused if they see the cursor indicate that something can be resized... and will think it's broken when they find out it can't be.

**Comment by wizofaus** [comment]
Not use MS3 users, I'd think anyone who's ever used any application that allows resizing things with the mouse and shows the appropriate cursor to indicate this!  Will investigate...
