### ISSUE TITLE
[MU4 Issue] Empty window appears for ~1-2sec when running a second copy of MU (Windows)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9920]
https://user-images.githubusercontent.com/90187801/143892679-042e197e-bad8-4db9-b50d-2318ab73985f.mp4

**Expected behavior**
Empty (grey) window should not take so long 

**Screenshots**

**Desktop:**
Windows only (Win10)

**Comment by cbjeukendrup** [comment]
@DmitryArefiev Is this issue still actual? I wondered, because it has been open so long already.

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Yeah, it should be retested long ago.. Thanks for pointing me.

Tested in latest builds of 4.0.2 and master (4.1.0) - **NO LONGER OCCURS**

Closing
