### ISSUE TITLE
[MU4 Issue] Disabling indentation on first system doesn't work

### ISSUE THREAD

**Issue by mattblo** [musescore/MuseScore#9938]
**Describe the bug**
The small check mark "Enable Indentation on first system" in the Style Settings does not change anything if it is disabled.

**To Reproduce**
1. Create a new score
2. Open the style settings
3. Disable the little mark at "Enable Indentation on first system"
4. Nothing changes

**Expected behavior**
Disabling the indentation on first system should set the value to 0,00sp. (Restore the behavior of MU3)

**Screenshots**

https://user-images.githubusercontent.com/63284090/144184291-44edbb43-246f-41d9-8946-e3c83f8b89b8.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by njvdberg** [comment]
Is fixed with PR #9944.

**Comment by mattblo** [comment]
You are also very quick ;-)
