### ISSUE TITLE
[MU4 Issue] Invisible notes in another voice affect dot placement

### ISSUE THREAD

**Issue by oktophonie** [musescore/MuseScore#9941]
Here the invisible note (actually in voice 4) causes the dots to be offset rightward from their normal position:

![image](https://user-images.githubusercontent.com/20604032/144219902-8cd6dfe1-98ba-4cbe-b3be-064509678dd3.png)

Just flipping the stem is enough to correct this:

![image](https://user-images.githubusercontent.com/20604032/144220120-a7c98f47-4008-405d-b317-ac7ae45ab5ae.png)

I assume this is because when the stem of the invisible note is up, that note (and therefore also its dot) is offset, and the visible dots are likewise offset to ensure they align. This would be correct if the note were visible, but invisible items should not affect the spacing of visible ones.

(This behaviour is also present in MU3.6 and presumably earlier)

**Comment by HemantAntony** [comment]
@oktophonie I've been trying to work on this. Does this look good?
![image](https://user-images.githubusercontent.com/88136054/185785991-22d6caaf-7b01-4b2f-b4ad-bc9c2ffe4983.png)

Also the dots are still aligned

**Comment by Jojo-Schmitz** [comment]
Seems not a valid example, as even when visible there won't be a need for that dot to move, as there is no collision with the flag. Looks like the stem is just 0.5sp shorter than in the initial example?

**Comment by oktophonie** [comment]
The example looks fine, but it's not showing the same thing as in the original. The problem arises when the upper voice is flipped to be stems down.

![image](https://user-images.githubusercontent.com/20604032/185787316-b1349794-61d5-4799-b4a2-37432cb8a5e1.png)

It seems the dots aren't avoiding the flag, as such, but are moving by the same amount that the note in the lower voice is offset, so that they line up, as can be seen if we move it lower:

![image](https://user-images.githubusercontent.com/20604032/185787424-7d972379-09bb-4884-a0b0-defd95ef7de7.png)

Whether we want to to happen in general is a separate question; in any case, MuseScore does this for now. However, if the note in the lower voice is invisible, it certainly should _not_ happen.

![image](https://user-images.githubusercontent.com/20604032/185787481-4025c2eb-4f97-4b22-9924-86b074b6a659.png)

I see that, in MU4, making the note invisible leaves the _dot_ still visible, which would appear to be a separate though related issue.
