### ISSUE TITLE
[MU4 Issue] Problem re-docking third panel in MacOS

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9945]
**Describe the bug**
When attempting to re-dock a third panel (either **Palettes**, **Instruments** or **Properties**) to the other two (already docked and accessible as tabs), the third panel struggles to find the docking area and can fail to re-dock: 

https://user-images.githubusercontent.com/86290556/144251684-1c7d53b7-58ea-40ef-a551-de0724dc2cef.mp4

**Expected behavior**
Blue highlighted docking zones should appear and third panel should be able to be re-docked with other two (returning to the "out-of-the-box" default arrangement with three tabs).

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)

**Additional context**
I could not reproduce this in Windows.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
