### ISSUE TITLE
[MU4 Issue] Crash trying to edit shortcuts

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#9953]
**Describe the bug**
Seems trying to set the shortcut key for any action causes a crash

**To Reproduce**
1. Go to Edit|Preferences|Shortcuts
2. Double click on any action in order to modify the shortcut
3. Crash

**Expected behavior**
Not a crash

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

this is nullptr
>	Qt5Widgets.dll!QWidget::palette() Line 4338	C++
 	MuseScore4.exe!mu::ui::UiTheme::drawPrimitive(QStyle::PrimitiveElement element, const QStyleOption * option, QPainter * painter, const QWidget * widget) Line 486	C++
 	Qt5Widgets.dll!QCommonStyle::drawControl(QStyle::ControlElement element, const QStyleOption * opt, QPainter * p, const QWidget * widget) Line 1346	C++
 	Qt5Widgets.dll!QFusionStyle::drawControl(QStyle::ControlElement element, const QStyleOption * option, QPainter * painter, const QWidget * widget) Line 1914	C++
 	Qt5Widgets.dll!QFusionStyle::drawControl(QStyle::ControlElement element, const QStyleOption * option, QPainter * painter, const QWidget * widget) Line 1769	C++
 	Qt5Widgets.dll!QStyleSheetStyle::drawControl(QStyle::ControlElement ce, const QStyleOption * opt, QPainter * p, const QWidget * w) Line 4308	C++

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - FIXED (should be in the next master)
