### ISSUE TITLE
Expand click+drag interaction to all palette elements 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9964]
**Task description**
@vpereverzev, @RomanPudashkin, @Eism, @igorkorsukov we would be interested to know how feasible it is to implement this task for MS4 🙂.

The basic idea is that when the user clicks and drags a palette object onto their score, the pink connector line should immediately find the nearest applicable score object and attach itself to that. When the connector line is showing, the user can release their mouse click (even if they are a long way away from the score) and the object will be applied in the correct position. 
(Note this behaviour is almost identical to how hairpins and other line objects currently work. We would just like to expand it out to _all_ palette objects). 

Using the connector line to show the target score object also means we can remove some of the current cursor iconography, including the red "unavailable" icon in Windows (see pp. 16-17 in the spec for details).

Here is the spec: 
[UX-Spec_Palette-drag-interaction_v.1.pdf](https://github.com/musescore/MuseScore/files/7649385/UX-Spec_Palette-drag-interaction_v.1.pdf)

Let me know what you think! 
Thanks

**Comment by Tantacrul** [comment]
I am bumping this to 4.x.

Annoying, since this is a terrible, terrible problem! However, it isn't a regressions, since the problem exists in MS3.6
