### ISSUE TITLE
[MU4 Issue] Closing one of multiple projects leaves windows open (potential usability trap) 

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9966]
**Describe the bug**
Closing one of multiple open projects causes the score to close, but the project window remains open and the user is left seeing the workspace, wallpaper, and app icon in the system tray.

A potential issue with this is that the user could be forgiven for thinking their project is still open:
- They still see the MuseScore app icon in the system tray. Clicking on it brings forward an "empty" screen.
- They may attempt to quit MuseScore to solve this, inadvertently closing all other open projects.

![Screenshot 2021-12-04 at 12 09 29 am](https://user-images.githubusercontent.com/86290556/144608012-bac84f09-ae68-4386-9074-d346db105747.jpg)

**Expected behavior**
My recommendation would be that, where more than one project is open, closing a project closes the entire window and removes the app icon from the system tray. Only where **only one** project is open should a close command keep the window open (so the user can open another score). 

This behaviour would be triggered by:

- File > Close
- Cmd/Ctrl+W
- Closing the window with the "X" icon in the title bar

**Desktop (please complete the following information):**

**Comment by DmitryArefiev** [comment]
Fixed in #17676
