### ISSUE TITLE
[MU4 Issue] main menu tears away from title bar

### ISSUE THREAD

**Issue by exegetor** [musescore/MuseScore#9968]
**Describe the bug**
Main menu is drawn below the title bar when the window is dragged between monitors.

**To Reproduce**
1. Launch MuseScore4
2. Drag the main window from one monitor to the other
3. Observe the main menu change its appearance during the drag.

**Expected behavior**
Application appearance should not change during the drag.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
QT 5.15.2

Add any other context about the problem here

https://user-images.githubusercontent.com/10360161/144636742-6e88b59a-1901-4c2e-a014-013b1db16204.mp4

**Comment by DmitryArefiev** [comment]
@Tantacrul Yes, still occurs

https://user-images.githubusercontent.com/90187801/170760818-0067605a-927d-426e-b722-a2e16412790c.mp4

**Comment by DmitryArefiev** [comment]
@Eism FYI

**Comment by exegetor** [comment]
I lack the computing resources to compile, so I'm out for the time being, but thanks @DmitryArefiev for the good vid.
I'd also second @VanSHOE.  This bug looks like an example of the broader issue in #11189.

**Comment by DmitryArefiev** [comment]
Fixed in #13528

**Comment by DmitryArefiev** [comment]
@exegetor Should be fine in the next master build

(looks good on my environment)
