### ISSUE TITLE
[MU4 Issue] Replaced instrument not showing up in the Instrument Panel and Parts Dialog

### ISSUE THREAD

**Issue by HemantAntony** [musescore/MuseScore#9972]
**Describe the bug**
Whenever you replace an instrument via the instruments panel, the name of the new instrument should replace the old instrument. Also, it should do the same in the parts dialog.

**To Reproduce**
1. Create a new score
2. Open multiple instruments
3. Open Instruments Panel
4. Click on settings for an instrument
5. Replace the instrument with another instrument
6. Look at the Instruments Panel and Parts Dialog

**Expected behavior**
The names of the replaced instrument should get updated both in the instruments dialog as well as the part dialog.

**Screenshots**
https://user-images.githubusercontent.com/88136054/144701848-29531bf3-96d2-4e56-9c30-1f6605acd993.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Also, when you open the replace instrument dialog, shouldn't the family be common, instead of all instruments?

**Comment by mattblo** [comment]
Related to #9745 and #9726
