### ISSUE TITLE
[MU4 Issue] When adding Pedal with asterisk to selection, position of asterisk is unpredictable and often wrong

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#9975]
**Describe the bug**
When adding a Pedal with asterisk, the asterisk should appear by default at the very end of the last note of the selection (because that is where the pedal should most likely be raised). It should look like this:
<img width="185" alt="Schermafbeelding 2021-12-04 om 16 50 50" src="https://user-images.githubusercontent.com/48658420/144715867-9cb56000-2f21-45cc-957f-a84f6416b12e.png">
*Correct*

---

But most often, when making a selection and clicking the Pedal with asterisk in the Lines palette, the asterisk appears not at the end of the last note, but somewhere just past the start:
<img width="185" alt="Schermafbeelding 2021-12-04 om 16 52 37" src="https://user-images.githubusercontent.com/48658420/144715930-2896af2a-121c-4bb6-bf0b-d0aa7193fe30.png">
*Wrong*

---

In some cases, it _does_ appear correctly. As far as I could figure out, that seems to be the case if and only if the selection consists of only the last element of a bar. So if I would select the half note in this example, I would get a correct result:
<img width="185" alt="Schermafbeelding 2021-12-04 om 16 57 50" src="https://user-images.githubusercontent.com/48658420/144716090-5005bc4c-d27b-4091-9375-0fab3dbbca25.png">
*Correct*

This also applies when the bar contains only one item (for example, a whole note or a whole measure rest).

---

**Additional remarks**
- Adding the "Pedal with line" (in contrast to the asterisk variant) seems to produce correct results consistently. 

- When selecting a single note, the pedal will be added from that note to the end of the bar (and the asterisk will be placed incorrectly). I guess this is by design, but we could revise that. This makes it impossible to add a pedal mark to the first half only of a bar in 4/4 that starts with a half note. This also applies to the "Pedal with line" variant.

- If we want to keep the behaviour mentioned above, I think it should at least take existing pedal marks later inside the bar into account. So it should produce 
  <img width="185" alt="Schermafbeelding 2021-12-04 om 17 14 39" src="https://user-images.githubusercontent.com/48658420/144716595-68474730-9e60-4c46-bf54-d92857915e0f.png">
  instead of
  <img width="185" alt="Schermafbeelding 2021-12-04 om 17 14 09" src="https://user-images.githubusercontent.com/48658420/144716575-c4992d09-0da9-4fb4-b90e-1f293c60ca1c.png">.

- When changing the length / duration of a pedal line manually and then making some changes to the music anywhere else, the modified pedal line sometimes jumps vertically. When undoing the changes made to the music anywhere else, the modified pedal line does not jump back, so you need to undo the change to the pedal line too and then redo it manually.

---

@oktophonie Is all of the above correct in your opinion?

**Comment by oktophonie** [comment]
This is all excellent in principle and would make it consistent with how hairpins etc work (basically we're saying that if we select (say) three notes, the pedal is to the end of the third note; if we wanted the pedal to come off _on_ the third note, we'd apply it to the first two notes)

There seems to be a magic 'end of note' position that the ends of lines can snap to sometimes though it doesn't seem to work consistently for me, so moving the ends of lines is difficult.

**Comment by XiaoMigros** [comment]
Resolved by 4.4?

**Comment by cbjeukendrup** [comment]
Yes, looks like all these things were solved by https://github.com/musescore/MuseScore/pull/21633. @oktophonie @mike-spa fyi.
