### ISSUE TITLE
[MU4 Issue] Beam break tooltips are incorrect

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#9977]
**Describe the bug**

The beam break icons are either missing one line or the tooltip/internal code is wrong. Conversations are likely needed to determine which behavior is desired.

<img width="291" alt="Screen Shot 2021-12-05 at 7 38 10 PM" src="https://user-images.githubusercontent.com/5659171/144783310-a15a677f-db13-4f58-b9a1-b1cefcb9d4a0.png">

<img width="293" alt="Screen Shot 2021-12-05 at 7 38 22 PM" src="https://user-images.githubusercontent.com/5659171/144783325-6b6ba2b1-9895-4f03-ac75-f7eb2dd5106b.png">

As you can see from these images, the first icon shows a beam beginning at the 16th level (not 32nd), and the second at the 32nd level (not 64th).

**To Reproduce**
1. Select a note with a beam
2. Click on the Properties panel
3. Expand the "Note" section and select the "Beam" tab
4. Look under the "Beam types" option to view the icons

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1, Apple Silicon

**Additional context**

These tooltip values line up perfectly with the internal values for the code (e.g., the first toggles `Beam::Mode::BEGIN32` and the second toggles `Beam::Mode:BEGIN64`). This would suggest that the icons are correct. However, musically it makes more sense to allow beam breaks at the 16th level as well, which would suggest all the internal code and the tooltips are incorrect.

**Comment by Tantacrul** [comment]
@oktophonie - seems pretty cut and dry to me. Can you (or a minion) alter this?

Also offering up to the community too, since it seems like a dead simple fix.

**Comment by Tantacrul** [comment]
@Jojo-Schmitz - good point. I've updated the description.

**Comment by MarcSabatella** [comment]
The tooltips are also completely missing for the two icons in the More section.  I might assume they were intended to be feathering since those are missing.  But they don't actually do anything.  So between the icons themselves being meaningless, the lack of a tooltip, and the fact that I don't see them actually doing anything, they are rather mysterious.

**Comment by Tantacrul** [comment]
Urgh! Where have the feathering options disappeared to?

I can't even see them anymore. Goddammit.

**Comment by MarcSabatella** [comment]
At the risk of stirring the pot more:

When I first saw this, I didn't read carefully enough and thought we were talking about the "Beam Properties" *palette* as opposed to the "Beam" section of the Properties *panel*.  FWIW, the names in the palette are different from those in the panel and make more sense to me than the names in the panel.  But more importantly, do we really still need the palette?

**Comment by boryskuzmenko** [comment]
🟢 **FIXED** in https://github.com/musescore/MuseScore/pull/11934
Tested on macOS 12, Win 11, Ubuntu 20
