### ISSUE TITLE
[MU4 Issue] Cannot check codestyle locally on macOS

### ISSUE THREAD

**Issue by Nick-Mazuk** [musescore/MuseScore#9978]
**Describe the bug**

Since https://github.com/musescore/MuseScore/pull/9952 was merged, I cannot locally test the codestyle on macOS.

```bash
Check code style
./build/ci/linux/checkcodestyle.sh: line 25: wget: command not found
Check code style failed
```

**To Reproduce**

I've always checked codestyle by using the running bash script that the GitHub action uses in the repo root:

```
./build/ci/linux/checkcodestyle.sh
```

**Expected behavior**

No error. Should check codestyle.

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1, Apple Silicon

**Comment by igorkorsukov** [comment]
This script is intended for use on CI, not local use.

For local use, you can use:
```
./tools/codestyle/uncrustify_run_dir.sh ./src/
```
Or even better, configure QtCreator so that the style is adjusted when saving files, this is very convenient. If you are using QtCreator.

To use the style checker locally, you need to install `uncrustify` locally.
We are currently using version 0.73.0
The easiest way to install it is to simply build it, this is done with a few commands and add to the paths.
To do this, you need to download the archive with the source code of the corresponding version.
https://github.com/uncrustify/uncrustify/tags

And execute the commands according to the instructions
https://github.com/uncrustify/uncrustify

**Comment by Jojo-Schmitz** [comment]
Do you have a style file for QtCreator? We had one for the previous style at https://musescore.org/sites/musescore.org/files/qt2-musescore.xml

**Comment by igorkorsukov** [comment]
> Do you have a style file for QtCreator?

In QtCreator we can configure the use of uncrustify.

1. Needs to enable Beautifer in the plugins list
![image](https://user-images.githubusercontent.com/3818029/144824032-ae56fcdc-3568-411d-b40f-2d7d3de1e893.png)

2. Specify config for uncrustify
![image](https://user-images.githubusercontent.com/3818029/144824228-7aaf7c5b-9bb5-4d81-9375-2191ba9a731b.png)

3. Enable style adjustments when saving files
![image](https://user-images.githubusercontent.com/3818029/144824374-5721e7fb-d2a1-487b-9b0e-283145ce710b.png)

**Comment by Jojo-Schmitz** [comment]
Does require getting and installing an uncrustify for Windoews (if working on Windows) where such a style file would just format the added/changed code correctly from the start

**Comment by igorkorsukov** [comment]
Unfortunately, the default capabilities of the QtCreator styler and, accordingly, the configurations of this file are very limited and do not allow us to achieve most of the things that uncrustify does.
You can try to create such a style config file for QtCreator ;)

**Comment by igorkorsukov** [comment]
> Does require getting and installing an uncrustify for Windows (if working on Windows)

For Windows, there should be no problems to build uncrustify (by  VS or MinGW), as well as for other platforms.

**Comment by Jojo-Schmitz** [comment]
It is available pre-build from sourceforge.

**Comment by cbjeukendrup** [comment]
In addition to the Qt Creator method Igor mentions above, I run Uncrustify in Terminal.

You first need to install GNU findutils, as macOS ones won't work in this case: `brew install findutils`
But if you have already used the Uncrustify script before, then you probably have this already.

Then, in the MuseScore folder, you run the command 
```sh
PATH="$(brew --prefix)/opt/findutils/libexec/gnubin:$PATH" tools/codestyle/uncrustify_run.sh
```

Additionally, I use the following pre-commit hook:
<details><summary>Uncrustify pre-commmit hook</summary>

  ```bash
  #!/usr/bin/env bash
  
  CURRENT_BRANCH="$(git branch --show-current)"
  
  if [[ "$CURRENT_BRANCH" = "master" ]]; then
      echo "Error: on master branch";
      exit 1;
  fi
    
  #echo "Uncrustifying staged files..."
  
  RELPATH=../..
  staged=$(git diff --name-only --cached)
  
  cd ./tools/codestyle/
  while IFS= read -r file; do
  	ext="${file##*.}"
  	if [ $ext != "cpp" ] && [ $ext != "h" ]; then
  		continue
  	fi
  	cp "$RELPATH/$file" "$RELPATH/$file.bak" 
  	if $( uncrustify -c "$RELPATH/tools/codestyle/uncrustify_musescore.cfg" -l CPP "$RELPATH/$file" ); then
  		mv "$RELPATH/$file.uncrustify" "$RELPATH/$file"
  		rm "$RELPATH/$file.bak"
  		git add "$RELPATH/$file"
  	else
  		#echo $?
  		mv "$RELPATH/$file.bak" "$RELPATH/$file"
  		rm "$RELPATH/$file.uncrustify"
  		#echo "Uncrustify failed for $file"
  	fi
  done <<< "$staged"
  
  #echo "Finished uncrustifying"
  ```
</details>
This works quite well for me.

Of course, this all requires that the correct version of Uncrustify is the first in PATH.

**Comment by Nick-Mazuk** [comment]
Cool! Closing this issue since @cbjeukendrup's solution has been working for me for several days.
