### ISSUE TITLE
[MU4 Issue] Double/halve note duration skips values in note entry mode

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9995]
**Describe the bug**
Using key commands **Q** and **W** quarters/quadruples the note value in input mode (in both standard and tablature staves).

**Expected behaviour**
**Q** and **W** should (respectively) double/halve note duration consistently across standard and tablature staves. 
When in **note input** mode, these commands should effect the to-be-entered ChordRest.
When in **normal** mode, these commands should act on the currently selected ChordRest(s).

**To Reproduce**
1. Create a score
2. Select bar
3. Hit **c**
4. Hit **q** several times, hit **w** several times

**Side-by-side comparison**
![double-half-note-duration](https://user-images.githubusercontent.com/86290556/145017843-4b23bffb-e1a7-4792-aad7-d9a721336692.gif)

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Additional context**
See also #9914 and #8908

**Comment by igorkorsukov** [comment]
@DmitryArefiev I can`t reproduce it seems to be fixed, please check

**Comment by DmitryArefiev** [comment]
@igorkorsukov @vpereverzev I can reproduce it in master build. The issue reproduces only in Input mode

https://user-images.githubusercontent.com/90187801/153852782-e79950ea-c357-4afa-844f-af883fa550f1.mp4
