### ISSUE TITLE
[MU4 Issue] Key command "go to top staff" doesn't completely select note

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9996]
**Describe the bug**
Executing the key command "go to top staff" seems to position the selection point somehow "behind" the correct top-staff note, but doesn't select it per se. It is possible to navigate sideways away from the presumed selection point, which indicates that the key command is functioning _somewhat_, while still not performing as per MS3.6.

**Demonstration video**

https://user-images.githubusercontent.com/86290556/145019886-1efe5e37-5512-4277-a4b1-845bcac1e5a2.mp4

**Expected behavior**
Executing this command should see the target selection point highlighted and immediately editable.

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

**Additional context**
See also #8908

**Comment by igorkorsukov** [comment]
@bkunda  Do we really need this command? 
At the moment there is no such shortcut in MU4, should I add it?
Or, it is enough to move through the elements (Alt+Up, Alt+Down)

**Comment by MarcSabatella** [comment]
Being able to jump to the top staff quickly is very nice for blind users - it saves potentially dozens of keystrokes.  The shortcut doesn't need to be defined by default, although it actually *would* be nice to provide a predefined set of "accessibility shortcuts".

**Comment by bkunda** [comment]
@MarcSabatella's point makes sense to me. I realise it just adds to what is already a rather huge amount of shortcuts, but at some point (perhaps after MS4 now), it would be good to implement https://github.com/musescore/MuseScore/issues/8746, which will allow for categorisation of keyboard shortcuts (including the possibility of @MarcSabatella's suggestion above) 🙂

**Comment by igorkorsukov** [comment]
Ok, I add this shortcut.
I tried to find a key combination for it - and I didn't succeed, it seems as if all the combinations are already used :)

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10236

**Comment by DmitryArefiev** [comment]
Tested #10236 on Win10, Mac12, LinuxMint 20.2 - FIXED
